### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#10]
Navigation is hard.
Make sure the following navigation scenarios work properly:

- `page.navigate('not-a-url')` should return `false`
- `page.navigate('https://expired.badssl.com/')` should return `false`
- `page.navigate('http://example.com/non-existing-page')` should return `false`
- `page.navigate('http://example.com')` with no internet should return `false`
- `page.navigate('data:text/html,hello')` should return `true`
- Page's navigation via inner javascript's `window.location.href = 'http://example.com'` should be reported to puppeteer, probably via the `Navigated` event.

All of this should be also applicable to frame navigation in #4

**Comment by aslushnikov** [comment]
Today, 'page.navigate' waits for the `load` event to fire. We might need an option to wait for `DOMContentLoaded` instead, though I don't know a scenario where this is useful.

**Comment by JoelEinbinder** [comment]
example.com returns status 200 for all paths, so that non-existing-page case won't work. Is the idea to return false for non-200 status codes? I feel like the true/false should be whether or not the current page was rendered with data from that url. So 403/404/200 would be true, but timeout/brokenssl would be false.

**Comment by paulirish** [comment]
Rather than `false`, to me it seems better to reject with an `Error` with a more descriptive message.

**Comment by aslushnikov** [comment]
So the issue with returning `true`/`false` is that it's hard to decide what is a success and what is a failure. For example, navigating to a 404 page might be a valid scenario, since a lot of websites have their own custom-made 404's.

How about:
- we consider navigation failed if there's a navigation timeout or an interstitial
- anything else returns a status code for the main resource

This should address both @JoelEinbinder and @paulirish concerns. What do you guys think?

**Comment by paulirish** [comment]
it could return the fetch `response` object for the main resource
