### ISSUE TITLE
executionContext and evaluateHandle are both undefined

### ISSUE THREAD

**Issue by christopherwk210** [puppeteer/puppeteer#1000]
This bug was happening to me on my local machine, but can easily be seen by going to [try-puppeteer.appspot.com](https://try-puppeteer.appspot.com/) and using the following:

```javascript
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://google.com');
const windowHandle = await page.evaluateHandle(() => window);
```
Which shows `Error running your code. TypeError: page.evaluateHandle is not a function`

Also, the following:
```javascript
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://google.com');
const executionContext = page.mainFrame().executionContext();
```
Outputs `Error running your code. TypeError: page.mainFrame(...).executionContext is not a function`.

I found both of these in the API documentation and couldn't find anywhere that said they were in development or not in the public release, so I'm assuming this is a bug?

**Comment by christopherwk210** [comment]
I was looking at the documentation for 0.12.0 alpha. My mistake.

**Comment by huan** [comment]
So where did you miss in the documentation?

I ran into the same issue but I can not figure it out.

**Comment by christopherwk210** [comment]
@zixia The documentation versions are at the top.

![Reference Image](https://i.imgur.com/wWJkpis.png)

**Comment by huan** [comment]
Ok, thanks!
