### ISSUE TITLE
[Bug]: Chromium installation script does not give an error if you are VPN blocked

### ISSUE THREAD

**Issue by MarcusOtter** [puppeteer/puppeteer#10013]
### Bug expectation

I tried to install puppeteer while I was on a VPN connection. Chromium did not install along with the `npm install ` command, so I tried running the installation script (`node_modules/puppeteer/install.js`) manually. This resulted in the success message output:
```
Chromium (1108766) downloaded to C:\Users\<username>\.cache\puppeteer\chrome\win64-1108766
```
However, `C:\Users\<username>\.cache\puppeteer\chrome\` is an empty folder.

After a while, I figured out this is because my IP address was banned from accessing https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html
![bild](https://user-images.githubusercontent.com/35617441/231540516-ee165b35-6f7b-4bb6-8eeb-383a9bd81617.png)

To fix it, I changed my IP address, and the script started working again. However, the script should NOT say that it successfully downloaded chromium. It should give me an error that helps me understand why the installation failed.

I saw this was also just recently mentioned by @martincomputershare in https://github.com/puppeteer/puppeteer/issues/9533#issuecomment-1505234987

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
1. Have a blocked IP address
2. Install puppeteer with `npm i puppeteer`
3. See Chromium was not installed in `~/.cache/puppeteer/chrome/`
4. Try running `node node_modules/puppeteer/install.js`
5. See successful output message, claiming that Chromium was installed
6. Chromium was not installed, `~/.cache/puppeteer/chrome/` is an empty folder
```

### Error string

no error

### Puppeteer configuration

```TypeScript
-
```

### Puppeteer version

19.8.5

### Node version

18.14.2

### Package manager

npm

### Package manager version

9.3.1

### Operating system

Windows

**Comment by MarcusOtter** [comment]
Well the issue is not code related so I don't know how it would be made automatically reproducible ^^

**Comment by MarcusOtter** [comment]
An easier way to reproduce it would be to mock a response from https://storage.googleapis.com that looks like this:

```
HTTP/2 403 Forbidden

<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>
```

**Comment by netfocusinc** [comment]
I am experiencing the exact same problem you are describing. Very challenging to troubleshoot, as there is error message. 

1. Install puppeteer with `npm i puppeteer`
2. See Chromium was not installed in `~/.cache/puppeteer/chrome/`
3. Try running `node node_modules/puppeteer/install.js`
4. See successful output message, claiming that Chromium was installed

"Chromium (1108766) downloaded to /home/obfuscated/.cache/puppeteer/chrome/linux-1108766"

6. Chromium was not installed, `~/.cache/puppeteer/chrome/` is an empty folder

**Puppeteer version**
19.8.5

**Node version**
14.21..3

**Package manager**
npm

**Package manager version**
9.6.4

**Operating system**
Ubuntu 20.04.6 LTS

**Comment by MarcusOtter** [comment]
@netfocusinc are you able to access https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html ?

When I visit that link I get the result seen in the screenshot above. If you do not get the same, maybe there's a problem with the installation script that shows no error messages at all?

**Comment by netfocusinc** [comment]
Yes, I am able to access https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html

**Comment by OrKoN** [comment]
I think I know what the issue is but the reproduction steps are a bit difficult to replicate exactly. I am going to open a fix and please report after the new version is released if it helped.
