### ISSUE TITLE
[Feature]: There is no way to block third-party cookies.

### ISSUE THREAD

**Issue by anzded** [puppeteer/puppeteer#10011]
### Bug expectation

I just needed to block all third-party cookies in my tests. I read a lot of different topics about this issue and highlighted 2 options
1. Use experiment method Emulation.setDocumentCookieDisabled
2. Use already created chrome user profile with already blocked third-party cookies
Unfortunately nothing of them works for me . When I used Emulation.setDocumentCookieDisabled there was no affect , ie all third-partycookies still continued to load. When tried to use user profile, I faced with issue that profile transfering only works for visual mode, ie headless:false. When headless:true  chrome load deafult profile with all cookies allowed. Below the code snippet that contains both methods. Also the samee behavior on my windows machine and Linux server

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const path = require('path');
const puppeteer = require('puppeteer');
const site = 'some site URL';
(async () => {
const browser = await puppeteer.launch({
    headless: true,
//path to already existing profile where all cokies disabled
    userDataDir:"C:\\Users\\<username>\\AppData\\Local\\Google\\Chrome\\User Data\\Profile 2",
    //or userDataDir:path.resolve("C:\\Users\\<username>\\AppData\\Local\\Google\\Chrome\\User Data\\Profile 2");
});

const context = await browser.createIncognitoBrowserContext();
var pageDesktop = await context.newPage();
await pageDesktop.setDefaultNavigationTimeout(0);

    await pageDesktop.setViewport({
        width: 1920,
        height: 1080,
        isLandscape: true
    });
    const client = await pageDesktop.target().createCDPSession();
    await client.send('Emulation.setDocumentCookieDisabled', {'disabled': true});

    await pageDesktop.goto(site + "?" + Math.random(), {waitUntil: ['load']});
    console.log('Browser is opened');
    await pageDesktop.waitForTimeout(10000);
    const cookies = await client.send('Network.getAllCookies');
    console.log(cookies);
    await pageDesktop.close();
    await browser.close();

})();
```

### Error string

no error

### Puppeteer configuration

```TypeScript
Package.json
{
  "dependencies": {
    "@automattic/vip": "^2.27.0",
    "@supercharge/request-ip": "^1.2.0",
    "aws-sdk": "^2.1298.0",
    "fs": "^0.0.1-security",
    "geoip-lite": "^1.4.7",
    "get-sitemap-links": "^1.0.6",
    "googleapis": "^100.0.0",
    "node.js": "^0.0.1-security",
    "nodemailer": "^6.7.3",
    "path": "^0.12.7",
    "puppeteer": "^19.7.0",
    "puppeteer-extra": "^3.3.6",
    "puppeteer-extra-plugin-recaptcha": "^3.6.8",
    "puppeteer-extra-plugin-stealth": "^2.11.2",
    "strict": "^0.0.0",
    "url-status-code": "^2.0.0",
    "wp-cli": "^0.0.5",
    "xlsx": "^0.18.5"
  }
}
```

### Puppeteer version

19.7.0

### Node version

16.14.1

### Package manager

npm

### Package manager version

9.4.2

### Operating system

Windows

**Comment by anzded** [comment]
Updated puppeteer to 19.8.5 version. Issue still presents

**Comment by OrKoN** [comment]
I think it is a feature request and not a bug. setDocumentCookieDisabled probably does not work because it is about the document.cookies API but cookies can be set in another way.

**Comment by anzded** [comment]
Why feature? User profile import in headless mode does not work but should as I understand, doesn't it?

**Comment by OrKoN** [comment]
The profile import is not a feature of Puppeteer, it's the browser feature, in this case Chromium. Puppeteer has no explicit support for blocking cookies and there is no way to do it with Puppeteer.

**Comment by anzded** [comment]
Got it, thanks. Chromium team already has similar ticket opened. It's a pity. Will be wating for setDocumentCookieDisabled working

**Comment by jrandolf** [comment]
There doesn't seem to be anything actionable here. `setDocumentCookieDisabled` is related to `cookies` as stated by @OrKoN. I think you probably want to clear out other things such as IndexedDB and etc which are more permanent in general.

Let's file a new bug that explicitly outlines what storage systems that you'd like disabled.

It could also be possible to delete IndexedDB and other objects on the Windows object before a page load. This can be done with `evaluateOnNewDocument`. With this, the page no longer has access to those objects, but I think this could break the site.

**Comment by OrKoN** [comment]
Actually, I think it is a valid feature request @jrandolf. I would keep it open to see how many other users need this.

**Comment by anzded** [comment]
No, just wanted to block all third-party cookies. I  do not need IndexedDB or Local storage. setDocumentCookieDisabled not working

**Comment by anzded** [comment]
I think this feature is required by users as iOS devices by default block third-party cookies. Chrome in Incognito mode blocks third-party cookies. And currrently we are not able to test such scenarios.

**Comment by OrKoN** [comment]
This is unlikely to happen since third party cookies are being phased out in Chrome https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/
