### ISSUE TITLE
[Feature]: Task automation feature

### ISSUE THREAD

**Issue by quyhn0302** [puppeteer/puppeteer#10029]
### Feature description

Regarding the old version, specifically the 19.7.2 version I used for 1 of my projects that could automate tasks without having to open chrome (I didn't mean headless: true).

I can downgrade my active chromes with puppeteer and the tasks still work perfectly.
But when the new version seems to require me to turn on chrome to be able to complete tasks such as type, click ...

I think this is a BUG after the update.

My codes are exactly the same but the old version can launch 5 chrome tabs and it works together,
with the new version i have to see each tab for it to work. It's hard to handle.

**Comment by OrKoN** [comment]
Please open a big report with all details filled out.
