### ISSUE TITLE
[Bug]: Target closed: Protocol Error with Node 16 and 18

### ISSUE THREAD

**Issue by amrutha95** [puppeteer/puppeteer#10023]
### Bug expectation

I'm trying to bump the node version from 12 to 16 on our service that uses puppeteer. This service runs as an Azure functions app in a docker container. This is the image we use in our Dockerfile:  mcr.microsoft.com/azure-functions/node:4-node14

I'm running into an error "Protocol error: Target closed" when I try to use puppeteer.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
const site = req.query.site || "";
  
  let siteData: LoadedPage | undefined;
  const startTime = new Date();


    let page;
    let sitePage: puppeteer.Page;
    let pageResponse: puppeteer.HTTPResponse | null;

  
      const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });
      sitePage = await browser.newPage();

      await sitePage.setDefaultNavigationTimeout(120000);
  
      pageResponse = await sitePage.goto(site, {
        waitUntil: ['domcontentloaded'],
      });
      const response = await loadPage(site, context);

      if (!(response instanceof Error)) {
        siteData = response;
      }

      page = siteData?.sitePage;
      pageResponse = siteData?.pageResponse;

      page.setRequestInterception(true);

      const whiteList = ['document', 'plain', 'script', 'javascript'];
      page.on('request', req => {
        const type = req.resourceType();
        if (whiteList.some(el => type.indexOf(el) >= 0)) {
          req.continue();
        } else {
          req.abort();
        }
      });
     
  

    const securityDetails = pageResponse?.securityDetails();
```

### Error string

ProtocolError: Protocol error (Fetch.enable): Target closed. 

### Puppeteer version

18.2.1

### Node version

16

### Package manager

npm

### Package manager version

8.1.2

### Operating system

Linux

**Comment by OrKoN** [comment]
Could you provide the complete snippet including the site (or a site example) you are testing with?

**Comment by OrKoN** [comment]
I suspect that the new image you use does not have all dependencies for Chromium. Could you also try the official image? https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer
