### ISSUE TITLE
Not allowed to access local storage. 

### ISSUE THREAD

**Issue by fernandowski** [puppeteer/puppeteer#1002]
Hello, 

I have problems executing this piece of code 

page.evaluate((browserSessionId) =>
            {
                let sessionJSON = JSON.stringify({sessionId: browserSessionId});
                localStorage.setItem("session", sessionJSON);
                let session = localStorage.getItem("session");
                return session;
            }, sessionId);

when I attempt to access local storage I get the following error. 

Error: Evaluation failed: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at <anonymous>:4:17
    at <anonymous>:7:15
    at Frame.<anonymous> (/home/nodejs/Code/node_modules/puppeteer/node6/FrameManager.js:380:13)
    at next (native)
    at step (/home/nodejs/Code/node_modules/puppeteer/node6/FrameManager.js:355:24)
    at Promise.resolve.then.value (/home/nodejs/Code/node_modules/puppeteer/node6/FrameManager.js:366:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)

I launch the instance of puppeteer like this 
puppeteer.launch({args:['--no-sandbox']})

**Comment by entrptaher** [comment]
works on my end :/
```js
(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();

  await page.goto("http://example.com");
  let things = await page.evaluate(() => {

    // set something
    let sessionJSON = JSON.stringify({"pup": "peteer"});
    localStorage.setItem("session", sessionJSON);

    // get it
    let session = localStorage.getItem("session");

    // return it
    return session;
  });

  console.log(things) // {"pup":"peteer"}
})();
```

Maybe you can provide more info about the page/url etc?

**Comment by fernandowski** [comment]
This is the URL 
http://one-integration.brandify.com

I lunch puppeteer with --no-sandbox flag passed through the args array

**Comment by entrptaher** [comment]
I did this without --no-sandbox and it works.
![image](https://user-images.githubusercontent.com/8284972/31460690-0bcdd2dc-aee9-11e7-9bb9-68a1b84ce5c6.png)

**Comment by fernandowski** [comment]
I forgot to mention that I am running within a docker container using CentOS.

**Comment by fernandowski** [comment]
I will close this issue because it seems that I needed to wait for the page to load before executing my evaluation function. waiting one second resolved the issue.
