### ISSUE TITLE
Strange breaking change in page.evaluate()

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#1003]
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('https://example.org/');
    const result1 = await page.evaluate(() => []);
    console.log(typeof result1);

    await page.goto('https://developer.apple.com/library/content/documentation/Darwin/Conceptual/FSEvents_ProgGuide/Introduction/Introduction.html');
    const result2 = await page.evaluate(() => []);
    console.log(typeof result2);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
puppeteer v0.11.0:
```console
object
object
```
puppeteer v0.12.0-alpha (current master)
```console
object
string
```

**Comment by JoelEinbinder** [comment]
`page.evaluate` returns JSON now. The Apple page overrides Array.prototype.toJSON, and appears to do so incorrectly.

**Comment by vsemozhetbyt** [comment]
@JoelEinbinder @aslushnikov Would it be reasonable to add an option to clean up such overrides (`Array.prototype.toJSON = undefined`)? Because now there is no guarantee to get the needed data from unpredictable sites.

**Comment by JoelEinbinder** [comment]
You can use `page.evaluateHandle` instead of `page.evaluate` to avoid the json serialization. Fighting against the page is going to be a losing battle.

**Comment by aslushnikov** [comment]
That's a good argument towards providing something like `jsHandle.jsonValue({ignoreFormatters: true})`. Or maybe even having it on by default.
