### ISSUE TITLE
[Feature]: Page.WaitStable()

### ISSUE THREAD

**Issue by Fly-Playgroud** [puppeteer/puppeteer#10036]
### Feature description

how to determine when a page has fully loaded and finished rendering. Maybe like `Page.WaitStable()`

**Comment by OrKoN** [comment]
The point in time when an application is fully loaded and finished rendering is very application-specific. It is unlikely that we will add smth like this soon. You can use lower-level methods we already expose to wait for a condition specific to you app: waitForNetworkIdle, check animation frames etc.

**Comment by Fly-Playgroud** [comment]
> animation frames
puppeteer has about this func?

**Comment by Fly-Playgroud** [comment]
> The point in time when an application is fully loaded and finished rendering is very application-specific. It is unlikely that we will add smth like this soon. You can use lower-level methods we already expose to wait for a condition specific to you app: waitForNetworkIdle, check animation frames etc.

puppeteer has func of checking animation frames?

**Comment by Fly-Playgroud** [comment]
> `await page.evaluate(() => new Promise(resolve => { window.requestAnimation(resolve); }))` and other web APIs.

ok thanks

**Comment by jrandolf** [comment]
There doesn't look like anything actionable here. In theory a page can have an ongoing socket connection that may change the web page in a non-trivial way continually. We cannot detect this per app. As stated by @OrKoN, try to work with the current APIs and see how that goes.
