### ISSUE TITLE
[Bug]: STATUS_ACCESS_VIOLATION on youtube.com

### ISSUE THREAD

**Issue by MarcusOtter** [puppeteer/puppeteer#10033]
### Bug expectation

All puppeteer versions after `v18.2.1` give me a STATUS_ACCESS_VIOLATION when trying to access youtube.com (both headless and headful). v18.2.1 and version prior do not seem to give me this error.

**Current workaround**: Downgrade to `v18.2.1`.

![bild](https://user-images.githubusercontent.com/35617441/232508966-bb828591-070d-483e-9d7b-a9ef2295c642.png)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
	const browser = await puppeteer.launch({ headless: false });
	const page = await browser.newPage();
	await page.goto("https://youtube.com");
	const screenshot = await page.screenshot({ encoding: "base64" });
	console.log(screenshot);
	await browser.close();
})();
```

### Error string

Navigation timeout of 30000 ms exceeded

### Puppeteer version

19.9.1

### Node version

18.16.0

### Package manager

npm

### Package manager version

8.4.1

### Operating system

Windows

**Comment by MarcusOtter** [comment]
Also tried on Mac with the same result

**Comment by OrKoN** [comment]
Can confirm! Happens without using Puppeteer too:

```
path/to/Chromium --user-data-dir=/tmp/profile
```

**Comment by OrKoN** [comment]
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/1131172/ works but it will be some time till we roll next release of Chromium

**Comment by MarcusOtter** [comment]
Thanks, I think I accidentally skipped testing `18.2.1`. I tested with `18.1.0` and then `19.0.0`. Will edit the question to make it more clear that `18.2.1` works fine.

**Comment by liynk** [comment]
is it resolved?

**Comment by ggorlen** [comment]
@liynk According to [this comment](https://stackoverflow.com/questions/76283454/is-it-possible-to-use-mutationobserver-to-detect-new-child-nodes-in-the-dom-and/76285456?noredirect=1#comment134527840_76285456), yes, as of 20.0.0.

**Comment by AnkitT0204** [comment]
what is the solution of this bug can you please help me right now i am using pupptteer version 16.7 and i am not able to find out the reason why it is coming and how to resolve it
