### ISSUE TITLE
Set timeout to 0 doesn't disable the timeout

### ISSUE THREAD

**Issue by rohmanhm** [puppeteer/puppeteer#1004]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):

**What steps will reproduce the problem?**
Passing `timeout: 0` at `page.goto` not disabling the timeout.   

_Please include code that reproduces the issue._

```javascript
(async function () {
  const browser = await Puppeteer.launch({ headless: false })
  const page = await browser.newPage()
  const url = 'https://google.com/'
  await page.goto(url, {
    waitUntil: 'networkidle',
    timeout: 0
  })
  await browser.close()
})()
```
**What is the expected result?**
It should not throw error

**What happens instead?**
Throw this error on console.

```bash
(node:7015) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 0ms exceeded
(node:7015) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 0ms exceeded
warning.js:28
(node:7015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning.js:28
```

**Comment by rohmanhm** [comment]
Seems I should update to `v0.12.0-alpha`

**Comment by aslushnikov** [comment]
@rohmanhm you're right, this is a tip-of-tree feature that hasn't been released yet.

The 0.12.0-alpha is a bleeding edge, it's not published on npm. If you want to dogfood the tip-of-tree, please install puppeteer from github directly.
