### ISSUE TITLE
[Bug]: Pdf print page break works incorrect with long images

### ISSUE THREAD

**Issue by Yemelia** [puppeteer/puppeteer#10045]
### Bug expectation

It seems that pdf print page break works incorrect with long images.
It makes it as a background for page instead of separate block.
In the attached video you can find that in the html text block goes after image but on the downloaded pdf file text covers the image.
Please, find attached files

Original html:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div><img src="./testImage.jpg" /></div>
  <div>TestTestTest</div>
</body>
</html>
```

Test image file:

![testImage](https://user-images.githubusercontent.com/23050836/233095235-3935b4dd-85ce-4b3f-b143-8279b0a9f273.jpg)

https://user-images.githubusercontent.com/23050836/233094568-ad7e6fac-2f3c-4b10-95cf-f95ce97b80ab.mov

https://user-images.githubusercontent.com/23050836/233094588-6a004c91-0c2f-420b-9370-2718f1c9f587.mov

### Bug behavior

- [ ] Flaky
- [x] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('http://127.0.0.1:8080/');

  await page.pdf({
    path: 'test.pdf',
    printBackground: true,
    width: '816',
    omitBackground: true,
    height: '1056',
    scale: 1,
  });
})();
```

### Error string

no error

### Puppeteer version

19.9.1

### Node version

16.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
Does it reproduce without Puppeteer?

**Comment by Yemelia** [comment]
> Does it reproduce without Puppeteer?

Yeah. Maybe the root cause is the current chrome version (I have tested with 110 - 112).
Also it works as expected with puppeteer 15.1.0 (chromium version is 104)

**Comment by OrKoN** [comment]
@Yemelia can you try in the latest Chrome and report the issue to crbug.com if it reproduces? Please post the bug ID here.

**Comment by Yemelia** [comment]
Reported the issue to crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=1434694

**Comment by Yemelia** [comment]
According to the chromium team comment this issue will be fixed in chrome 114

**Comment by Yemelia** [comment]
According to the chromium team comment this issue will be fixed in chrome 114
