### ISSUE TITLE
[Bug]: Evaluation failed: TypeError: network error for async function

### ISSUE THREAD

**Issue by Akxe** [puppeteer/puppeteer#10050]
### Bug expectation

I ma getting an error when I run a async function in evalualuate.

This is OK: 
```
expect(await page.evaluate(() => 1)).toBe(1); // OK
const res = await page.evaluate(() => GPMFExtract(
  document.querySelector('[type=file]').files[0],
  { browserMode: true, useWorker: false },
)); // Evaluation failed: TypeError: network error
```
but ```const res = await page.evaluate(() => GPMFExtract(document.querySelector('[type=file]').files[0], { browserMode: true, useWorker: false }));```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

Repo: https://github.com/Akxe/gpmf-extract/tree/dev (`npm run test`)

```TypeScript
describe('Testing the extracted raw data and timing from File', () => {
  /** @type {import('puppeteer').ElementHandle<HTMLInputElement>} */
  let inputHandle;
  beforeEach(async () => {
    await page.goto(`file://${join(__dirname, './browser/index.html')}`, { waitUntil: 'networkidle0' });
    inputHandle = await page.$('input[type=file]');
    await inputHandle.uploadFile(mp4Path);
  });

  test('Library loaded', async () => {
    expect(1).toBe(1);
    expect(await page.evaluate(() => 1)).toBe(1);
    expect(await page.evaluate(() => typeof GPMFExtract)).toBe('function');
    expect(await page.evaluate(() => GPMFExtract?.name)).toBe('GPMFExtract');
    expect(await page.evaluate(() => document.querySelector('[type=file]').files[0] instanceof File)).toBe(true);
  });
});
```

### Error string

network error

### Puppeteer configuration

```TypeScript
I am using `jest-pupeteer` with `.jest-puppeteerrc.json` file: 


{
  "launch": {
    "headless": true,
    "devtools": true,
    "exitOnPageError": false
  }
}
```
```


### Puppeteer version

19.9.1

### Node version

16.13.2

### Package manager

npm

### Package manager version

9.1.2

### Operating system

Windows

**Comment by OrKoN** [comment]
I am unable to run the repro: `npm ERR! Missing script: "dev"` and `npm test` works fine. Please provide a clearer reproducible example.

**Comment by OrKoN** [comment]
I guess you probably try to run a node class in the page context? the GPMFExtract class. I think you should check the guide https://pptr.dev/guides/evaluate-javascript to understand why that would not work.

**Comment by Akxe** [comment]
> I am unable to run the repro: `npm ERR! Missing script: "dev"` and `npm test` works fine. Please provide a clearer reproducible example.

I did fix the typo in the issue body now. Thanks for that. `test` is the command at hand.

> I guess you probably try to run a node class in the page context? the GPMFExtract class. I think you should check the guide https://pptr.dev/guides/evaluate-javascript to understand why that would not work.

I have set up the test so that the `FPMFExtract` is defined in the browser. I do even have tests for it:

```javascript
expect(await page.evaluate(() => typeof GPMFExtract)).toBe('function');
expect(await page.evaluate(() => GPMFExtract?.name)).toBe('GPMFExtract');
```
https://github.com/Akxe/gpmf-extract/blob/a7e22cb7c3c944534a4aaf01f9889665df9f9368/tests/browser.test.js#L21-L22

**Comment by OrKoN** [comment]
I get an error `Evaluation failed: ReferenceError: GPMFExtract is not defined`. Is it the issue you are describing?

**Comment by Akxe** [comment]
No, do you have the latest version of the dev branch?

**Comment by OrKoN** [comment]
yes, I just fetched it.

**Comment by OrKoN** [comment]
it is ccec6a6f1109ba60c781ef529be3dcb4221443c8

**Comment by Akxe** [comment]
Did you run the `npm run test` command? The build step did not run, if you used only `jest`.

**Comment by OrKoN** [comment]
yes, I did

**Comment by OrKoN** [comment]
https://github.com/Akxe/gpmf-extract/blob/dev/tests/browser/index.html#L5 this should be dist.js as the build produces a build.js

**Comment by Akxe** [comment]
I did a hotfix now please pull again

**Comment by Akxe** [comment]
Is it my fault, or is it a real bug?

**Comment by OrKoN** [comment]
It's definitely not a Puppeteer bug as the browser sends it but it might be the browser bug. What does GPMFExtract return? I think that value might not be serialisable. I replace the return value with a plan object things work:

``` 
    const res = await page.evaluate(() => {
        const r = GPMFExtract(
          document.querySelector('[type=file]').files[0],
          { browserMode: true, useWorker: false },
        );
        return {
          timing: {
            videoDuration: 12.078733333333334
          }
        };
    });
    expect(res.timing.videoDuration).toBe(12.078733333333334);
 
```

**Comment by OrKoN** [comment]
@Akxe can you create a smaller repro by maybe replicating the key parts GPMFExtract to return the same kind of data?

**Comment by OrKoN** [comment]
The error comes from `"lineNumber":6732,"columnNumber":12, "url":"file:///Users/alexrudenko/src/pptr-test/gpmf-extract/tests/browser/dist.js`

**Comment by Akxe** [comment]
> or maybe it's some issue with the reading of the file.

Using the `index.html` I did test the file manually. In the last commit (you have) I did replace the `Uint8Array` with a normal Array.

Do I have to wait after `await inputHandle.uploadFile(mp4Path);`? I am not sure...

**Comment by Akxe** [comment]
So If I run the test in Chrome or a new tab of opened Chromium, it does work as expected. If I run it in the opened window of the test it will fail with the **network error**.

However, setting the file to the file selector manually works as expected... What should be done now?

**Comment by Akxe** [comment]
Closing this as the error the whole time was, that I was uploading file that was not present.

Filed a bug report to address throwing when uploading non-existing files... https://github.com/puppeteer/puppeteer/issues/10053
