### ISSUE TITLE
[Bug]: Making puppeteer wait until all list items within container loaded errors out

### ISSUE THREAD

**Issue by 87sam12** [puppeteer/puppeteer#10062]
### Bug expectation

If we are unaware of how many list items are fetched, how to choose selectors and wait for all list items being loaded. Lets imagine they are fetched through ajax.

Lets say following is the vague html fetched and at max 5 li elements. We are not already aware of how many exist on a particular fetch. But maybe in the real scenario there could be 100 list items, and it has pagination of maybe 3 pages.
```html
<ul class='container'>
        <li>item 1</li>
        <li>item 2</li>
        <li>item 3</li>
        <li>item 4</li>
        <li>item 5</li>
    </ul>
```
What should be our puppeteer wait api or whatever thats appropriate which is the simplest way to fetch without missing anything.

Do methods like following work ? (but it still seems vague, and mostly results in errors like :
Execution context was destroyed, most likely because of a navigation; or some other errors)
```js
await page.evaluate(() => 
          document.querySelector('.container').childNodes.length>3
);
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  
  await page.goto('https://listitems.com/');  //imaginary page
  const nxt_page_link_sel = ".next_page_link";
  let next_page_link = await page.$(nxt_page_link_sel, {
      timeout: 1000,
  });
  await page.evaluate(() => 
     document.querySelector('.container').childNodes.length>3
  );
})();
```

### Error string

Execution context was destroyed, most likely because of a navigation.

### Puppeteer version

19.10.1

### Node version

v16.13.2

### Package manager

pnpm

### Package manager version

8.3.0

### Operating system

Linux

**Comment by 12sam12** [comment]
I know. As the issue was an imaginary thing. Actual page is local. So I cant give a reproducible code. But its more like it.

**Comment by OrKoN** [comment]
@12sam12 please create a test page that demonstrates the issue

**Comment by jrandolf** [comment]
Use [Page.waitForFunction](https://pptr.dev/api/puppeteer.page.waitforfunction/)
