### ISSUE TITLE
[Bug]: Error: Node is either not clickable or not an HTMLElement

### ISSUE THREAD

**Issue by KAEN7** [puppeteer/puppeteer#10072]
### Bug expectation

There is a code in waitForSelector that puts a selector to page.click to make it wait for rendering.
However, Error: Node is another not clickable or not an HTMLElement error frequently occurs and often does not work.
Occurrence rate is low in window and high in mac.
I'm guessing you can't wait for the rendered selector, but I'd like to know a solution to the issue.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
await page.waitForSelector(
  "#layer > div > div > div.layer_body > div > div:nth-child(2) > dl > dd > div > div:nth-child(5) > div > div > ul > li"
);

await page.click(
  `#layer > div > div > div.layer_body > div > div:nth-child(2) > dl > dd > div > div:nth-child(5) > div > div > ul > li:nth-child(${
    hour + 1
  })`
);
```

### Error string

Error: Node is either not clickable or not an HTMLElement

### Puppeteer version

^19.11.0

### Node version

v16.13.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by OrKoN** [comment]
Please provide a test page and a test script that demonstrates the issue!

**Comment by jrandolf** [comment]
Using waitForSelector then click is not necessarily atomic. I.e., the element can disappear after the waitForSelector. Puppeteer may be single-threaded in Node.js, but the browser is a separate process, therefore has its own threads etc. This means you cannot expect operations to be atomic between the page and Node.js. To help this, waitForSelector returns a reference that will not disappear if the page removes the node. You can query selector on that reference to return the element you actually want. 

On another note, we are fairly certain their is something wrong with the page. Our tests are exhaustive regarding querying.

**Comment by KAEN7** [comment]
> waitForSelector를 사용하면 클릭이 반드시 원자성일 필요는 없습니다. 즉, 요소는 waitForSelector 후에 사라질 수 있습니다. Puppeteer는 Node.js에서 단일 스레드일 수 있지만 브라우저는 별도의 프로세스이므로 자체 스레드 등이 있습니다. 이는 작업이 페이지와 Node.js 사이에서 원자적일 것이라고 기대할 수 없음을 의미합니다. 이를 돕기 위해 waitForSelector는 페이지가 노드를 제거해도 사라지지 않는 참조를 반환합니다. 해당 참조에서 선택기를 쿼리하여 실제로 원하는 요소를 반환할 수 있습니다.
> 
> 또 다른 메모에서 페이지에 문제가 있다고 확신합니다. 우리의 테스트는 쿼리와 관련하여 철저합니다.

Thank you! It was a great help in solving the problem.

**Comment by luketzh** [comment]
> Using waitForSelector then click is not necessarily atomic. I.e., the element can disappear after the waitForSelector. Puppeteer may be single-threaded in Node.js, but the browser is a separate process, therefore has its own threads etc. This means you cannot expect operations to be atomic between the page and Node.js. To help this, waitForSelector returns a reference that will not disappear if the page removes the node. You can query selector on that reference to return the element you actually want.
> 
> On another note, we are fairly certain their is something wrong with the page. Our tests are exhaustive regarding querying.

This works!
