### ISSUE TITLE
[Feature]: pass puppeteer an internal docker network URL

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#10074]
### Feature description

I posted a [question over on stackoverflow](https://stackoverflow.com/q/76096528/4070848) which hopefully explains the context.  Since posting that, and after some more playing around, I have a sinking feeling that what I'm asking for in that question is just not possible when using puppeteer in this way?  i.e. the ability to use:

```
const url = 'http://srv-captain--mynodehost/app/mypage.html';
await page.goto(url);
```

where the `url` above is an internal URL over the docker network set up between containers.

If this is not possible, perhaps consider this as a feature request... assuming that it's possible at all.

**Comment by OrKoN** [comment]
I don't see why it would not be possible. Since you are using the chromium binary from the docker image, you should ensure it is compatible with Puppeteer: https://pptr.dev/chromium-support

**Comment by OrKoN** [comment]
I assume that your host's DNS is able to resolve `srv-captain--mynodehost`. IIRC, this is the default behaviour in Docker. So, if you can do `curl http://srv-captain--mynodehost/app/mypage.html`, you should be able to navigate using the browser too.

**Comment by drmrbrewer** [comment]
OK I'll check, and I'm relieved that it appears (in principle) like it should be possible already.

BTW the reason I'm installing the chromium binary separately, rather than relying on puppeteer to install the most appropriate, is because I was finding that it was doing so when attempting to run this on an `arm64` platform... see [this issue](https://github.com/puppeteer/puppeteer/issues/7740).  If it wasn't for that, and wanting to have a consistent installation whether or not I'm installing on `arm64` or `amd64` I would leave it to puppeteer (which would be my preference, for an easy life).

**Comment by OrKoN** [comment]
@drmrbrewer I see, if you are on Mac, you should be able to use the Rosetta emulation for Docker. But if you are on an arm64 linux, it is the only way I know. So you just need to double check that your Chromium version matches Puppeteer.

**Comment by drmrbrewer** [comment]
@OrKoN I can confirm that:

1. when I'm in a bash terminal inside the first container (running puppeteer), I can indeed retrieve the content of the html page hosted on the second container (hosting the page content) with: `curl http://srv-captain--mynodehost/app/mypage.html`
2. As mentioned in my linked SO post, the chromium binary installed into the container is `Chromium 112.0.5615.121` which is pretty much identical to the chromium supported by the latest puppeteer, which is `112.0.5614.0`... I'm doubting that the problem would be down to this very minor difference?

**Comment by OrKoN** [comment]
Can you start Puppeteer with the dumpio: true flag and the env var `DEBUG=puppeteer:*` and share the log? Also, can you try to navigate with the parameter waitUntil: `domcontentloaded` to make sure that other resources on the page dont block the nav?

**Comment by drmrbrewer** [comment]
@OrKoN I think you may be onto something with resources blocking the nav.  I'm getting several of these types:

```
puppeteer:protocol:RECV ◀   '{"method":"Log.entryAdded","params":{"entry":{"source":"network","level":"error","text":"Failed to load resource: net::ERR_CONNECTION_REFUSED","timestamp":1.682422317838686e+12,"url":"https://srv-captain--mynodehost/app/lib/lodash(v4.17.21).min.js","networkRequestId":"400765.139"}},"sessionId":"47C55C9E867E7E22CB6281F69AD9DF4E"}'
```

The problem here is, I assume, that the url is `https` rather than `http`, since these local resources won't be accessible over the local network using `https`.  I need to figure out how my html is loading these resources and where the `https` is coming from.

**Comment by OrKoN** [comment]
yeah, it is possible that there is a protocol mismatch and loading is blocked. You can try `ignoreHTTPSErrors` launch opt. If it helps, it's probably due to the protocol mismatch. Note that `ignoreHTTPSErrors` is less secure, so only use it for trusted sites.

**Comment by OrKoN** [comment]
alternatively, you can configure you app to use relative URLs for resources.

**Comment by drmrbrewer** [comment]
@OrKoN  I'm using a slightly convoluted method for loading these resources from the html (I must have thought there was a good reason for this, which was some time ago now, I think to ensure that I wait for all required resources load in the right order, and before the main script is called).  For example, for the `lodash` script which causes the above error, I load it with:

```
addResource('lodash', 'script', './lib/lodash(v4.17.21).min.js')
```

with this function defined as follows (removing various error checking and onload stuff which isn't relevant here):

```
var addResource = function (id, type, url) {
	var isScript = (type == 'script');   // else assume it's CSS
	var head = document.head || document.getElementsByTagName('head')[0];
	var element = document.createElement(isScript ? 'script' : 'link');
	element[isScript ? 'src' : 'href'] = url;
	element.type = isScript ? 'text/javascript' : 'text/css';
	if (!isScript) { element.rel = 'stylesheet'; } // for CSS only
	element.async = 'true';
	head.appendChild(element);
};
```

So why why this end up being loaded as `https://srv-captain--mynodehost/app/lib/lodash(v4.17.21).min.js`?  If it's going to do load it in this way, is there any way to force `http` rather than `https`?  I tried `ignoreHTTPSErrors` but it doesn't seem to help here.

**Comment by drmrbrewer** [comment]
@OrKoN all of my updates to the same reply (above) may have gotten lost, and I'm not sure if this issue has much visibility because it is marked as Closed, so I'm just wondering whether you might have a chance to cast your eye over my reply above?  Thanks!

**Comment by OrKoN** [comment]
@drmrbrewer sorry about that but we don't have time to help you troubleshoot your app. If you have a specific bug, like an interception not working for a specific request or anything like this, feel free to open an issue with a reproducible example that does not require a Docker orchestration (including a Puppeteer script and a test server/page).  Replacing all https with http queries might be a complex task as both the servers and the browser might default to https. I don't think Puppeteer forces https anywhere.

**Comment by drmrbrewer** [comment]
@OrKoN I wasn't really asking you to troubleshoot my app, I was just asking if you might be able to glean anything interesting from the logging generated from puppeteer, which might help to understand whether or not this is a puppeteer issue.  It doesn't occur outside the puppeteer environment (e.g. fetching the raw content internally over the Docker network between containers), and also doesn't occur outside the Docker environment (e.g. loading the Docker-hosted page in a remote Chrome browser directly).  I also don't see how it would be possible to provide a reproducible example that does not require a Docker orchestration, if the problem is specific to running puppeteer within a Docker environment and fetching the page over a Docker network.  If you don't think it's anything that puppeteer is doing, then that's fine and I'll go on my way.  Thanks for your insight up to this point anyway!

**Comment by chan158** [comment]
You can try this, it works for me, inside docker I can use compose services name to access.
[here](https://stackoverflow.com/questions/57167903/chrome-inside-docker-err-connection-refused)
`await puppeteer.launch({
          args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-gpu',
            '--ignore-certificate-errors',
            '--disable-web-security',
            '--enable-features=NetworkService',
          ],
          headless: true,
          ignoreHTTPSErrors: true,
        });`
