### ISSUE TITLE
[Bug]: Timing issue

### ISSUE THREAD

**Issue by sstelmar** [puppeteer/puppeteer#10079]
### Bug expectation

I need to convert an HTML page containing a formula converter to PDF.
I get excellent results when using the https://html2pdf.com/
[Calculation.pdf](https://github.com/puppeteer/puppeteer/files/11325565/Calculation.pdf)

I get incomplete results when using Puppeteer.
[testcalcs-puppeteer.pdf](https://github.com/puppeteer/puppeteer/files/11325553/testcalcs-puppeteer.pdf)

Here's the original HTML as created by my program.
[Calculation (2).zip](https://github.com/puppeteer/puppeteer/files/11325560/Calculation.2.zip)

### Bug behavior

- [ ] Flaky
- [X] PDF

### Minimal, reproducible example

```TypeScript
@page "/Calcs"
@using PuppeteerSharp;

@code 
{
    protected override async Task OnInitializedAsync()
    {
        string outputFile = "testcalcs-puppeteer.pdf";
        await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultChromiumRevision);
        var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            });
        var page = await browser.NewPageAsync();
        await page.GoToAsync("https://localhost:44392/Calculation.html");
        await page.PdfAsync(outputFile);
    }
}
```

### Error string

pdf not rendered correctly

### Puppeteer version

9.1.0

### Node version

v8.9.0

### Package manager

npm

### Package manager version

https://api.nuget.org/v3/index.json

### Operating system

Windows

**Comment by OrKoN** [comment]
You probably want to report it here https://github.com/hardkoded/puppeteer-sharp
