### ISSUE TITLE
[Feature]: How puppeteer monitors recording through code?

### ISSUE THREAD

**Issue by jiankafei** [puppeteer/puppeteer#10085]
### Feature description

My requirement is to be able to listen to user actions from a code level, such as the following:

```js
// Create a new recorder
const recoder = browser.newRecoder();

// Adding Events to the Recorder
recoder.addEventListener('record', (result) => {
    // Result is the JSON data generated by user operations, similar to the data generated in codegen
    // This event is triggered every time the user operates
    // My requirement is to retrieve this data through events in the code
    console.log(result)
})

// start recoder
recoder.start()
```

**Comment by OrKoN** [comment]
hey, this does not look like a feature we support.

**Comment by jiankafei** [comment]
> hey, this does not look like a feature we support.
@OrKoN 
The above code is the code I envisioned, not the code from a real scenario. I hope Puppeteer can provide the API for the functionality I envision.

**Comment by OrKoN** [comment]
Ah, I see. We do not have any plans to support something like this so it is unlikely to happen in the near/mid-term future. You can try the DevTools Recorder https://developer.chrome.com/docs/devtools/recorder/

**Comment by jiankafei** [comment]
> Ah, I see. We do not have any plans to support something like this so it is unlikely to happen in the near/mid-term future. You can try the DevTools Recorder https://developer.chrome.com/docs/devtools/recorder/
@OrKoN 
I tried devtools-recorder. It is similar to other automated testing IDEs, but none of them can meet my requirement scenarios. My requirement scenario is to listen to page operations by writing code, obtain real-time operation records for each step, and then proceed with the following operations. The existing IDEs on the market require users to copy the operation records themselves and then paste them where they need to be used. I want to turn the process of manually copying operation records into an automatic code acquisition and processing method, which would be more convenient.
