### ISSUE TITLE
[Bug]: linux  puppeteer  can`t get element in  iframe but it works in macos

### ISSUE THREAD

**Issue by zaxcler** [puppeteer/puppeteer#10081]
### Bug expectation

linux  puppeteer  can`t get element in  iframe but it works in macos

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
var select = await newPage.$eval("iframe", iframe => {
                var frame = iframe.contentWindow.document
                return frame.querySelector(".select").textContent
            })

or 

            let iframe = await newPage.$("iframe")

            let frame = await iframe?.contentFrame()
            let select = await frame.$eval(".select",e => e.textContent)
```

### Error string

linux  puppeteer  can`t get element in  iframe but it works in macos

### Puppeteer configuration

```TypeScript
const browser = await puppeteer.launch({
        //设置有头模式（默认为true，无头模式）
        headless: true,
        // args: ['--no-sandbox', '--user-data-dir="/User/zaxcler/chromium"', '--disable-web-security', '--disable-features=site-per-process'],
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox', // uid沙盒
            '--disable-web-security', //设置后可以获取iframe内的内容
            '--disable-features=site-per-process', //设置后可以获取iframe内的内容
            '--disable-gpu', // GPU硬件加速
            '--disable-dev-shm-usage', // 创建临时文件共享内存
            '--no-first-run', // 没有设置首页。在启动的时候，就会打开一个空白页面。
            '--no-zygote',
            '--single-process' // 单进程运行
        ],
        // executablePath: '/usr/bin/chromium-browser',
        executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
    });
```

### Puppeteer version

puppeteer-core 19.11.1

### Node version

local node v18.12.1   linux is using pkg file

### Package manager

pnpm

### Package manager version

7.15.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Please provide a script + a test page that demonstrates the issue.

**Comment by jrandolf** [comment]
It's possible that the element hasn't rendered yet. iframes have their own renderer, so you would need to wait for the frame to be ready then wait on the element. See [Page.waitForFrame](https://pptr.dev/api/puppeteer.page.waitforframe) an other `waitFor*` functions for information.
