### ISSUE TITLE
Error "ERR_BLOCKED_BY_XSS_AUDITOR" when redirect to another domain

### ISSUE THREAD

**Issue by datnd0502** [puppeteer/puppeteer#1008]
Error "ERR_BLOCKED_BY_XSS_AUDITOR" when redirect to another domain using https

![ssl-error](https://user-images.githubusercontent.com/10458054/31428075-b54ea864-ae93-11e7-9373-0349ef13bee4.png)

**Comment by aslushnikov** [comment]
Can you share a script to reproduce this?
