### ISSUE TITLE
[Feature]: Docs: summary for puppeteer docker image content (debia/node/Chrome exact versions bundled)

### ISSUE THREAD

**Issue by paulwwisl** [puppeteer/puppeteer#10098]
### Feature description

Please consider having summary for puppeteer docker image content

e.g. exact Linux/debian version
node.js version (major.minor)
Chrome or Chromium version

https://pptr.dev/chromium-support page has relation summary 

---

Alternative please advise how to get such info quickly,  
maybe it is already somewhere in documentation.

**Comment by OrKoN** [comment]
We don't keep track of the exact linux/node versions. Our docker image is here https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile and we build it on every Puppeteer release. The quickest way to get it so launch the container and see what node/linux is there. The version of Puppeteer would tell you which browser version is is compatible with (also see https://github.com/puppeteer/puppeteer/blob/main/versions.js).

This summary would require an extra effort to produce so we are not going to prioritise it for now.
