### ISSUE TITLE
Cannot do anything with provided ElementHandle

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#1009]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `"puppeteer": "^0.11.0"`
* Platform / OS version:
* URLs (if applicable): http://example.com

**What steps will reproduce the problem?**
Return element handle and try to work with it.

_Please include code that reproduces the issue._

```js
(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();

  await page.goto("http://example.com");

  // WORKS
  await page.screenshot({path: "wholePage.png"})

  // DOES NOT WORK
  const title = await page.$('h1');
  await title.screenshot({path: "justTitle.png"});

  await page.close();
  await browser.close();
})();
```

**What is the expected result?**
It should take a screenshot.

**What happens instead?**

Throws error,
```
TypeError: title.screenshot is not a function
```

**Comment by aslushnikov** [comment]
elementHandle.screenshot is on tip of tree, it's not available in PPTR v0.11.0.

Please, install the bleeding edge from github to get the `elementHandle.screenshot`.
