### ISSUE TITLE
How to use Page.addScriptToEvaluateOnNewDocument in CDPSession?

### ISSUE THREAD

**Issue by Gavin0210** [puppeteer/puppeteer#10094]
``` let page = await browser.newPage();  
await page.goto("https://www.google.com")
let testcdp = await page.target().createCDPSession()
await testcdp.send("Page.addScriptToEvaluateOnNewDocument", {"source": "console.log('aaaa')"})
```

when I refresh the page , the is not 'aaaa'  which should been console.log.
whats wrong with me?

**Comment by OrKoN** [comment]
you are probably missing `await testcdp.send("Page.enable")`. I'd suggest that the best place to questions like this is StackOverflow.
