### ISSUE TITLE
[Bug]: Problem with headless: "new" and Windows 10

### ISSUE THREAD

**Issue by lifeboatpres** [puppeteer/puppeteer#10101]
### Bug expectation

If I run: `response = await page.goto(url, {waitUntil: 'networkidle0', timeout: 10000});`
it works but I also get `ERROR: The process "58104" not found.` printed to the screen. With the number being a random number.

In the below minimal example, I didn't even need that code line to generate the error. (But a larger program that included that line generated no error if I just commented out that one line.)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
async function run() {
browser = await puppeteer.launch({
    headless: "new"
  });
   browser.close(); process.exit();
}
run();
```

### Error string

ERROR: The process "58104" not found. (digits are random)

### Puppeteer configuration

```TypeScript
None that I know of.
```

### Puppeteer version

19.11.1

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.6.5

### Operating system

Windows

**Comment by lifeboatpres** [comment]
I'm now labeling this as flaky to try to get past the github-actions bot. It does happen 100% for me, though.

**Comment by lifeboatpres** [comment]
I removed "flaky" since Lightning00Blade showed me the "disable-analyzer" label.

Thank you Lightning00Blade!

**Comment by OrKoN** [comment]
It appears that you are missing an await before `browser.close()`. This is a race condition probably between the process being closed by process.exit() and browser.close().

**Comment by lifeboatpres** [comment]
Thank you very much for the solution! Note that previous versions of Puppeteer didn't have this problem so I was stumped.

**Comment by lifeboatpres** [comment]
Wow! I was having a different problem on the second run of larger programs on Linux with "/home/lifeboat/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262
                reject(new Error([
                       ^

Error: Failed to launch the browser process! undefined
[508614:508614:0503/024321.358244:ERROR:process_singleton_posix.cc(334)] Failed to create /home/lifeboat/.config/google-chrome/SingletonLock: File exists (17)"

Your await before browser.close() fixes this problem as well. Double thanks!!!
