### ISSUE TITLE
[Bug]: Puppeter font issue in the server 

### ISSUE THREAD

**Issue by nharshavreddy** [puppeteer/puppeteer#10104]
### Bug expectation

I am generating the pdf using the puppeteer it was working fine in the local server 
when I am running in the server it have some font issues
attaching the pdf.
[server_pdf.pdf](https://github.com/puppeteer/puppeteer/files/11364188/server_pdf.pdf)
[local.pdf](https://github.com/puppeteer/puppeteer/files/11364206/local.pdf)

### Bug behavior

- [ ] Flaky
- [X] PDF

### Minimal, reproducible example

```TypeScript
let fieldName = object.originalFileName ? object.originalFileName : object.filename
    assetsPath = assetsPath ? assetsPath : ""
    let pageFormat = object && object.pageFormat ? object.pageFormat : "A4";
    return new Promise(async (resolve, reject) => {
        const browser = await puppeteer.launch({ headless: true });
        try {
            const page = await browser.newPage();
            await page.setContent(pdfHtml, { waitUntil: 'domcontentloaded' });
            await page.addStyleTag({ url: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css' });
            await page.addStyleTag({ url: 'https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' });
            await page.addStyleTag({ url: 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600&display=swap'});
            await page.pdf({
                path: fieldName + ".pdf",
                preferCSSPageSize: true,
                printBackground: true,
                margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' },
                format: pageFormat
            });
            if (!fs.existsSync(path.join(__dirname, '../../../reports', assetsPath))) {
                fs.mkdirSync(path.join(__dirname, '../../../reports', assetsPath));
            }
            const currentPath = path.join(__dirname, '../../../', fieldName + ".pdf");
            const destinationPath = path.join(__dirname, '../../../reports', assetsPath, fieldName + ".pdf");
            fs.rename(currentPath, destinationPath, async (err) => {
                if (err) {
                    return reject(err);
                }
                let file = destinationPath;
                await browser.close();
                return resolve(file);
            });
        } catch (error) {
            await browser.close();
            return reject(error);
        }
    });
```

### Error string

no error

### Puppeteer version

14.4.1

### Node version

16.4.2

### Package manager

npm

### Package manager version

8.5

### Operating system

Linux

**Comment by nharshavreddy** [comment]
It was the same issue with new version as well

**Comment by nharshavreddy** [comment]
this is happening when i am using following lines of code

wait page.addStyleTag({ url: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css' });
            await page.addStyleTag({ url: 'https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' });
            await page.addStyleTag({ url: 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600&display=swap'});

**Comment by jrandolf** [comment]
Could you tell us in more detail the exact set up you have?

**Comment by OrKoN** [comment]
@nharshavreddy can you provide a standalone executable script with the a test page that demonstrates the problem? The code you provided is not runnable. Also make sure to wait for external fonts to be loaded before starting to print and check for any errors that might come from external resources.

**Comment by wz57c** [comment]
this problem also exist, when i set headless true, custom fonts will be invalid
