### ISSUE TITLE
ElementHandle screenshot does not count padding (or add options to count the padding/margin)

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#1010]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0-alpha
* Platform / OS version:
* URLs (if applicable): http://example.com

**What steps will reproduce the problem?**
Take screenshot using ElementHandler.

_Please include code that reproduces the issue._

```js
await page.goto("http://example.com");
const title = await page.$('h1');
const screenshot = await title.screenshot({path: "justTitle.png"});
```

**What is the expected result?**
Take screenshot of the highlighted area as from chrome. When I mean highlighted, I mean the margin/padding.

![image](https://user-images.githubusercontent.com/8284972/31430534-f63bee8c-ae92-11e7-9414-4cee8e1f6dd3.png)

**What happens instead?**
![justtitle](https://user-images.githubusercontent.com/8284972/31430418-99eedef0-ae92-11e7-86d1-d2d5686b1ebc.png)

**Comment by ebidel** [comment]
I've meant to file the same bug :) To screenshot just the element, it's a bit painful right now. You need to figure out the element margin and adjust the`clip` property accordingly. 

It would be nice for us to provide an option. For now, here's a workaround that works for me:

```js
await page.goto("http://example.com");
const title = await page.$('h1');

const styles = await page.evaluate(el => window.getComputedStyle(el), title);

const clip = Object.assign({}, await title.boundingBox());
clip.y += parseFloat(styles.marginTop) || 0;
clip.x += parseFloat(styles.marginLeft) || 0;

const screenshot = await title.screenshot({path: "tweet.png", clip});
```
