### ISSUE TITLE
[Docs] Little typo in "Default runtime settings" section

### ISSUE THREAD

**Issue by Suppenterrine** [puppeteer/puppeteer#10113]
I found a typo on this [documentation section](https://pptr.dev/#default-runtime-settings
) at this under section: "_1. Uses Headless mode_".

<img width="545" alt="image" src="https://user-images.githubusercontent.com/23054541/235688960-4d4d7015-9be3-4e31-b137-fc74ba0cfb24.png">

I think it should say "false" here instead of "true".

**Comment by Lightning00Blade** [comment]
The issue seems to have already been fixed in #10063, but it seems the site was not update. With v20.0.0 out this has been fix on the site as well.
