### ISSUE TITLE
[Bug]: Can't mount a writable volume to the docker container

### ISSUE THREAD

**Issue by jsardev** [puppeteer/puppeteer#10115]
### Bug expectation

I expected to be able to mount a volume to the base docker image and write screenshots to it.

What happened instead was that the default `pptruser` does not have permissions to write anything to the mounted volumes. Not sure if this is my lack of knowledge on using Docker, or is the way the image is built/configured.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
`docker run -i --init --cap-add=SYS_ADMIN -v screenshots:/home/pptruser/screenshots --rm ghcr.io/puppeteer/puppeteer:latest touch screenshots/some-screenshots.jpg`
```

### Error string

Permission denied

### Puppeteer version

20.0.0

### Node version

16.17.1

### Package manager

pnpm

### Package manager version

8.2.0

### Operating system

macOS

**Comment by sarneeh** [comment]
This is not a puppeteer issue itself, but the official docker image

**Comment by sarneeh** [comment]
Nevermind, I managed to handle this by creating a custom image and running on `root` user. I had to go with `--no-sandbox`, but couldn't find any other solution.

**Comment by regystro** [comment]
> Nevermind, I managed to handle this by creating a custom image and running on `root` user. I had to go with `--no-sandbox`, but couldn't find any other solution.

Hi. Care to share your custom image Dockerfile? I'm trying to do the same but it's not working.

Thank you.
