### ISSUE TITLE
Maybe need an atomic `waitForNavigation` x times call?

### ISSUE THREAD

**Issue by akauppi** [puppeteer/puppeteer#1012]
I'm using Puppeteer to log in via OAuth sign-in dialogs. 

As part of the login, there are redirects, and this seems to be confusing Puppeteer. I haven't found the right way to deal with this, and currently think it may not exist.

What kind of works (but is fragile):

- Calling `waitForNavigation()` once in headless (the default thing I was doing). The redirect seems to be handled so fast that when I need the page, it's there.
  - On browser (not headless), the above however fails. My Puppeteer code seems to be reading the stuff in the redirect phase, instead of the ultimate page that would follow. Adding another `waitForNavigation()` fixes this (but causes a forever wait in headless).

What works (but is based on manually tuned timeouts):

- Calling `waitForNavigation( { waitUntil: "networkidle"  } )` with a suitably large timeout (400ms for headless, 4000ms for browser, on my machine)

This is not very elegant, since it's not event based (i.e. there's always unnecessary waiting involved).

What would solve this:

Ability to tell Puppeteer to "wait for two navigations to happen", in a single call. The real problem now is that in headless, doing two `waitForNavigation()` consecutively is not working. They need to be atomic.

API suggestion:

It could be a `count: <integer>` field (that defaults to 1).

Attached is a snippet from the source where I discuss this problem (nothing new there):

```
  // NOTE: The sign-in is doing redirections, before actually landing on the app. Is there a better way
  //    to handle this in Puppeteer?
  //
  //    Two things that worked:
  //
  //      If showing browser, call a second '.waitForNavigation()'
  //      If headless, progress seems faster and the redirect has already happened before the second call
  //
  //      Using '{ waitUntil: "networkidle" }'. This works with same code path, but the necessary idle
  //      timeouts vary hugely (we don't want to slow down headless case).
  //
  // Ideally, there would be a way in Puppeteer to say "wait for navigation twice", as an atomic operation.
  //
  await page.waitForNavigation( {
    waitUntil: "networkidle",

    // Headless:  200 ms was too fast
    // Browser:   2000 ms was too fast
    networkIdleTimeout: headless ? 400 : 4000
  });

```

Environment:
* Puppeteer version: 0.11.0
* Platform / OS version: macOS 10.13
* URLs (if applicable): n/a internal

**Comment by akauppi** [comment]
Found a better workaround:

```
await page.waitForNavigation();
await page.waitForSelector("table");
```

- No unneeded waits, no manual timings, no separate code paths for headless and browser
- Need to know an element that exists in the upcoming real page, but not in the intermediate one.

**Comment by ebidel** [comment]
@akauppi if those 2 lines cover your use case, mind closing this issue?

**Comment by akauppi** [comment]
I consider them a workaround, but not reason enough to flush this quite yet.

OAuth logins, or any other flows where the server produces redirects are frequent, and I think Puppeteer could have a way to handle them reliably. The atomic "wait for X times navigation" is what I suggest.

What's wrong with the workaround is that it depends on having a "marker element" (`table` in my sample). Something we just know is in the target page, but not in any of the interim ones.

**Comment by aslushnikov** [comment]
> Ability to tell Puppeteer to "wait for two navigations to happen", in a single call. The real problem now is that in headless, doing two waitForNavigation() consecutively is not working. They need to be atomic.

@akauppi the following works quite well for me in case of client-side redirect:

```js
// Wait for 2 navigations.
await page.waitForNavigation();
await page.waitForNavigation():
```

> What's wrong with the workaround is that it depends on having a "marker element" (table in my sample).

If you don't like waiting for marker element, you can wait for page title or even URL. Alternatively, you can wait for `framenavigated` event for the main frame for X times, and then use `await page.waitForNavigation`.
