### ISSUE TITLE
[Bug]: WebGL2 hardware acceleration is unavailable in WSL2 Linux since v19.8.0

### ISSUE THREAD

**Issue by harveylee** [puppeteer/puppeteer#10127]
### Bug expectation

I expected WebGL2 hardware acceleration to be enabled in WSL2 Linux.

WebGL2 hardware acceleration was working in v19.7.5. Since v19.8.0, hardware acceleration is suddenly unavailable, no change in my code. Tested up to v20.1.0

See also corroborating reports here [#3637](https://github.com/puppeteer/puppeteer/issues/3637#issuecomment-1519968113)

Output of `lsb_release -a`:
```
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```
(i.e. Debian `testing`)

Output of `glxinfo | grep -i opengl`:
```
OpenGL renderer string: D3D12 (Intel(R) Iris(R) Xe Graphics)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 22.3.6
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.1 (Compatibility Profile) Mesa 22.3.6
OpenGL shading language version string: 4.10
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 22.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

Dell XPS 13 9315
Windows 11 Home 10.0.22621 Build 22621
Intel Core i7-1250U processor

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

async function checkGPU (): Promise<void> {
  const browser = await puppeteer.launch({
    headless: true, // Problem exists for headless: new and headless: false also
    args: [
      '--use-gl=egl'
    ]
  })
  const gpuPage = await browser.newPage()
  await gpuPage.goto('chrome://gpu')
  const webgl2 = await gpuPage.waitForSelector('text/WebGL2')
  const webgl2Status = await webgl2?.evaluate(e => e.parentElement?.innerText)
  console.log(webgl2Status) 
  // Puppeteer 19.7.5 output: 'WebGL2: Hardware accelerated'
  // Puppeteer 19.8.0+ output: 'WebGL2: Software only, hardware acceleration unavailable'
  if (!webgl2Status.includes('Hardware accelerated')) {
    throw new Error('No WebGl2 hardware acceleration')
  }
  await browser.close()
}

void (async () => {
  await checkGPU()
})()
```

### Error string

No WebGl2 hardware acceleration

### Puppeteer version

19.8.0

### Node version

18.15.0

### Package manager

pnpm

### Package manager version

7.30.5

### Operating system

Linux

**Comment by OrKoN** [comment]
Does it work if you start the binary without using Puppeteer?

**Comment by OrKoN** [comment]
The version v19.8.0 included the browser update to M112 https://github.com/puppeteer/puppeteer/pull/9841 So I suspect that it does not work because of the change in the browser, so the best would be to file the issue at crbug.com as it is not directly related to Puppeteer.

**Comment by OrKoN** [comment]
Also, try the `--enable-gpu` as `--use-gl=egl` might not work as expected.

**Comment by harveylee** [comment]
> Does it work if you start the binary without using Puppeteer?

`MY_HOME/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome --headless --use-gl=egl --print-to-pdf chrome://gpu` gives me "WebGL2: Hardware accelerated" for both v19.7.5 and v19.8.0

> Also, try the `--enable-gpu` as `--use-gl=egl` might not work as expected.

Using this flag enables hardware acceleration for me on v19.7.5, v19.8.0 and v20.1.0! Thanks for your help.

**Comment by OrKoN** [comment]
We need to update documentation mentioning `--use-gl=egl` and recommend using `--enable-gpu`

**Comment by harveylee** [comment]
Update: I tried with `headless: 'new'` and `--enable-gpu` on v20.1.0:
- `chrome://gpu` returns an empty page
- judging by the performance, it appears that hardware acceleration is turned off

**Comment by OrKoN** [comment]
@harveylee could you please file that against the headless component at crbug.com?

**Comment by OrKoN** [comment]
doc update is here
