### ISSUE TITLE
[Bug]: At headless is false mode, the menu pinning for chrome extension doesn't work.

### ISSUE THREAD

**Issue by honestydeveloper** [puppeteer/puppeteer#10120]
### Bug expectation

Hi,
Actually, Puppeteer is great library for browser automation.
Thank you for puppeteer team!

I have ran puppeteer with headless mode is false and I have installed the some extensions and pined them in the extension menu.
I close the puppeteer and restarted it then the pin doesn't work.
The pin has returned to the unpinned mode.

I will appreciate if you could please tell me how can I fix this issue.
Thanks.
![Untitled](https://user-images.githubusercontent.com/42817736/235970799-84c065a1-edcc-4e9e-a2d5-894d14597ea1.png)
 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({
   headless: false
  });
  const page = await browser.newPage();

  await page.goto('https://www.google.com');

})();
```

### Error string

no error

### Puppeteer configuration

```TypeScript
args: [
    // "--remote-debugging-port=9222",
    // "--disable-dev-shm-usage",
    "--start-maximized",
    // "--restore-last-session"
  ],
  ignoreHTTPSErrors: true,
  ignoreDefaultArgs: [
    "--disable-background-networking",
    // "--enable-features=NetworkService,NetworkServiceInProcess",
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--disable-breakpad",
    "--disable-client-side-phishing-detection",
    "--disable-component-extensions-with-background-pages",
    "--disable-default-apps",
    "--disable-dev-shm-usage",
    "--disable-extensions",
    // BlinkGenPropertyTrees disabled due to crbug.com/937609
    "--disable-hang-monitor",
    "--disable-ipc-flooding-protection",
    "--disable-popup-blocking",
    "--disable-prompt-on-repost",
    "--disable-renderer-backgrounding",
    "--disable-sync",
    "--force-color-profile=srgb",
    "--metrics-recording-only",
    "--no-first-run",
    "--enable-automation",
    "--password-store=basic",
    "--use-mock-keychain",
    "--allow-pre-commit-input",
    "--disable-component-update",
    "--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints",
    // OptimizationHints
    "--enable-blink-features=IdleDetection",
    "--enable-features=NetworkServiceInProcess2",
    "--export-tagged-pdf",
    "--disable-blink-features=AutomationControlled",
    "about:blank",
  ],
```

### Puppeteer version

19.7.5

### Node version

18.13.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Windows

**Comment by OrKoN** [comment]
By default Puppeteer creates a fresh profile, so you need to configure it to be the same folder (`userDataDir` argument in launch). That should probably solve the issue.

**Comment by honestydeveloper** [comment]
@OrKoN , Thank you for your message.
I have already set the user data dir.

**Comment by honestydeveloper** [comment]
I have already used "--user-data-dir" and upgraded the version to the latest but it doesn't yet work.

**Comment by OrKoN** [comment]
@honestydeveloper could you share the exact code you use? the bug report does not mention you use it...
