### ISSUE TITLE
[Bug]: puppeteer 19.9.* cannot be installed behind a corporate proxy

### ISSUE THREAD

**Issue by kevteljeur** [puppeteer/puppeteer#10124]
### Bug expectation

I expected to install puppeteer 19.* for Node.js 14.20.1 on Red Hat Enterprise Linux Server release 7.9 (Maipo) behind a corporate proxy.

What happened instead was the error below.
- The Chromium binary can be downloaded from https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1108766/chrome-linux.zip using wget or curl
- the proxy environmental variables have been correctly set. 
- A change has been made from puppeteer 19.9.* and up so that this no longer works.
- puppeteer 19.8* can be installed as expected.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
> npm install puppeteer@19.9.*

npm ERR! code 1
npm ERR! path [edit]/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 407. URL: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1108766/chrome-linux.zip
npm ERR!     at [edit]/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:121:31
npm ERR!     at ClientRequest.requestCallback ([edit]/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:98:13)
npm ERR!     at Object.onceWrapper (events.js:520:26)
npm ERR!     at ClientRequest.emit (events.js:400:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
npm ERR!     at Socket.socketOnData (_http_client.js:515:22)
npm ERR!     at Socket.emit (events.js:400:28)
npm ERR!     at addChunk (internal/streams/readable.js:293:12)
npm ERR!     at readableAddChunk (internal/streams/readable.js:267:9)

 
npm ERR! A complete log of this run can be found in: [edit]/.npm/_logs/2023-05-03T20_23_05_747Z-debug-0.log
```

### Error string

ERR! Error: Download failed: server returned code 407.

### Puppeteer version

19.9.*

### Node version

14.10.1

### Package manager

npm

### Package manager version

9.6.5

### Operating system

Linux

**Comment by OrKoN** [comment]
Could you please specify what was the exact version that last worked?

**Comment by kevteljeur** [comment]
puppeteer 19.8.5 installs. puppeteer 19.9.0 and up fail at the proxy for downloading the binary. It installs fine when there is no proxy.

I went through the code in detail yesterday before trying out installations of the older versions - I'm aware that puppeteer 20 will not work with Node.js 14.x, we're unfortunately stuck with that for a little while yet - it seems that it is not picking up the environment proxy settings.

**Comment by OrKoN** [comment]
Could you try to install using the latest version?

**Comment by OrKoN** [comment]
puppeteer 20 should still work for Node 14 but it not an officially supported combination.

**Comment by kevteljeur** [comment]
With puppeteer 20, a slightly different error (so I'll have to try this with wget too):

> npm install puppeteer
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@puppeteer/browsers@1.0.1',
npm WARN EBADENGINE   required: { node: '>=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.20.1', npm: '9.6.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'puppeteer-core@20.1.1',
npm WARN EBADENGINE   required: { node: '>=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.20.1', npm: '9.6.5' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path [edit]/pdf_test/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! ERROR: Failed to set up Chrome r113.0.5672.63! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 503. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/113.0.5672.63/linux64/chrome-linux64.zip
npm ERR!     at [edit]/pdf_test/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:119:31
npm ERR!     at ClientRequest.requestCallback ([edit]/pdf_test/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:96:13)
npm ERR!     at Object.onceWrapper (events.js:520:26)
npm ERR!     at ClientRequest.emit (events.js:400:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
npm ERR!     at Socket.socketOnData (_http_client.js:515:22)
npm ERR!     at Socket.emit (events.js:400:28)
npm ERR!     at addChunk (internal/streams/readable.js:293:12)
npm ERR!     at readableAddChunk (internal/streams/readable.js:267:9)

 
npm ERR! A complete log of this run can be found in: [edit]/.npm/_logs/2023-05-05T11_52_41_258Z-debug-0.log

**Comment by kevteljeur** [comment]
Successfully downloaded in the same location with wget (it handles the URL and proxies which are set in the environment as expected - the proxy URL contains the user and proxy password).

**Comment by kevteljeur** [comment]
It is, it seems (I didn't specify the version when installing)

**Comment by mpalourdio** [comment]
Same error for me with latest puppeter version behind corporate proxy
`
npm ERR! Error: Download failed: server returned code 503. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/113.0.5672.63/linux64/chrome-linux64.zip
npm ERR!     at /home/m1bida/Workspaces/devsupport/devsupport-ng/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:119:31
npm ERR!     at ClientRequest.requestCallback (/home/m1bida/Workspaces/devsupport/devsupport-ng/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:96:13)
`
Reverting to ^19.0.0 fixes the problem.

**Comment by RJKeane2000** [comment]
I noticed in the [httpUtil.js](https://github.com/puppeteer/puppeteer/blob/main/packages/browsers/src/httpUtil.ts) file within the browsers package src folder of puppeteer, the url for both the proxy and the custom base url are being parsed to rebuild the options object for the request. Any authentication in the urls are lost. In my case, I'm going through Jfrog to download the browser but I have to authenicate with Jfrog.  I set PUPPETEER_DOWNLOAD_BASE_URL. I noticed the same thing would occur if you are using an authenticated proxy.

For example: 
```
export PUPPETEER_DOWNLOAD_BASE_URL=https://userId:password@company.jfrog.io/artifactory/chrome-for-testing-remote
```

Here's the code in the httpUtil.js that I believe needs to be updated:

```javascript
function httpRequest(url, method, response, keepAlive = true) {
    const options = {
        protocol: url.protocol,
        hostname: url.hostname,
        port: url.port,
        auth: url_1.urlToHttpOptions(url).auth,   <-- This is missing
        path: url.pathname + url.search,
        method,
        headers: keepAlive ? { Connection: 'keep-alive' } : undefined,
    };
    const proxyURL = (0, proxy_from_env_1.getProxyForUrl)(url.toString());
    if (proxyURL) {
        const proxy = new url_1.URL(proxyURL);
        if (proxy.protocol === 'http:') {
            options.agent = (0, http_proxy_agent_1.default)(proxyURL);
        }
        else {
            options.agent = (0, https_proxy_agent_1.default)({
                host: proxy.host,
                path: proxy.pathname,
                port: proxy.port,
                auth: url_1.urlToHttpOptions(proxy).auth, <--- This is missing
                secureProxy: proxy.protocol === 'https:',
                headers: options.headers,
            });
        }
    }

```

Puppeteer version: 20.2.0
Node version: 19.7.0

**Comment by OrKoN** [comment]
Could you try after https://github.com/puppeteer/puppeteer/pull/10227 is released? switched to the proxy-agent module that should handle various proxy types and configurations.

**Comment by akashnigam010** [comment]
> Could you try after #10227 is released? switched to the proxy-agent module that should handle various proxy types and configurations.

This issue is still happening. 
Tried version 20.4.0

**Comment by mpalourdio** [comment]
> Could you try after #10227 is released? switched to the proxy-agent module that should handle various proxy types and configurations.

Fixed for me! Thanks a lot!

**Comment by akashnigam010** [comment]
> > Could you try after #10227 is released? switched to the proxy-agent module that should handle various proxy types and configurations.
> 
> Fixed for me! Thanks a lot!

Which version @mpalourdio?

**Comment by mpalourdio** [comment]
^20.4.0

**Comment by hulmgulm** [comment]
I have the same issue with puppeteer 19.11.1 and 20.8.2 and node 18.16.1. Downloads are failing either with 400 (19.11.1) or 503 (20.8.2). 
Installation of 19.7.3 works fine.

**Comment by OrKoN** [comment]
we reverted the change due to the vm2 security issues.
