### ISSUE TITLE
[Bug]: dead link on website index

### ISSUE THREAD

**Issue by draco31fr** [puppeteer/puppeteer#10123]
### Bug expectation

I expected to access the page linked on the website homepage to https://pptr.dev/api/puppeteer.browserfetcher

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
Go to https://pptr.dev/#puppeteer-core

Clic on the second link on para :
You should use puppeteer-core if you are connecting to a remote browser or *managing browsers yourself*

The link is on the markdown here : https://github.com/puppeteer/puppeteer/blob/main/website/versioned_docs/version-20.1.0/index.md?plain=1#L108
But I can't found the right page to link, could be https://github.com/puppeteer/puppeteer/blob/main/website/versioned_docs/version-20.1.0/api/puppeteer.browser.md ?
```

### Error string

Page Not Found

### Puppeteer version

20.1.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
The class has been removed and we need to update the docs here.

**Comment by draco31fr** [comment]
Thank you @OrKoN for your quick feedback and fix.
