### ISSUE TITLE
[Bug]: Compatibility issues with PUPPETEER_DOWNLOAD_HOST

### ISSUE THREAD

**Issue by elrrrrrrr** [puppeteer/puppeteer#10131]
### Bug expectation

In puppeteer@19.x, when we run the following command, the version can be automatically resolved:

`PUPPETEER_DOWNLOAD_HOST=https://cdn.npmmirror.com/binaries/ npm run postinstall`

The main parameters after resolution are:

|type|architecture|buildId |host|
|---|---|---|--|
|chromium| mac| 1108766| https://cdn.npmmirror.com/binaries/chromium-browser-snapshots|

In puppeteer@20.x, when we run the following command, a 404 error will be displayed:

https://cdn.npmmirror.com/binaries/113.0.5672.63/mac-arm64/chrome-mac-arm64.zip

The main parameters after resolution are:

|type|architecture|buildId |host|
|---|---|---|---|
|chrome|mac_arm|113.0.5672.63|https://cdn.npmmirror.com/binaries|

The new version has updated the default browser type from `chromium` to `chrome`, but it is using the same variable `PUPPETEER_DOWNLOAD_HOST` as before, therefore, we cannot differentiate between them.
Would it be possible to add a new variable to allow for customizable overrides? 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
`npm i puppeteer`
`cd node_modules/puppeteer`
`PUPPETEER_DOWNLOAD_HOST=https://cdn.npmmirror.com/binaries/ npm run postinstall`
```

### Error string

ERROR: Failed to set up Chrome r113.0.5672.63! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.

### Puppeteer configuration

```TypeScript
PUPPETEER_DOWNLOAD_HOST=https://cdn.npmmirror.com/binaries/
```

### Puppeteer version

20.1.0

### Node version

16.19.0

### Package manager

npm

### Package manager version

9.6.2

### Operating system

macOS

**Comment by elrrrrrrr** [comment]
https://github.com/puppeteer/puppeteer/pull/10130

**Comment by elrrrrrrr** [comment]
https://github.com/puppeteer/puppeteer/pull/10128

**Comment by OrKoN** [comment]
Thanks for the report. v20.0.0 is a breaking change because the servers for download changed. Opened https://github.com/puppeteer/puppeteer/pull/10130 addressing this.

**Comment by zombieJ** [comment]
@elrrrrrrr thx for effort https://github.com/cnpm/cnpmcore/pull/455

Is that workaround in cnpm mirror side can I use?
