### ISSUE TITLE
[Bug]: chromium is not work Correctly when --no-sandbox Enabled !! 

### ISSUE THREAD

**Issue by RezaSalaari** [puppeteer/puppeteer#10139]
### Bug expectation

when i trying to launch a chromium with` --no-sandbox ` argument - the response of page is not work
 for example 
page.$ or  page.evaluate or querySelectorAll and all of them is not working while If this argument not passed every thing is ok ! 

what is problem?

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await Puppeteer.launch({ headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']});
```

### Error string

no error 

### Puppeteer version

18.1.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by RezaSalaari** [comment]
`:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
`
Error

**Comment by OrKoN** [comment]
I am unable to reproduce. The error `Running as root without --no-sandbox is not supported.` indicates that --no-sandbox is not provided.
