### ISSUE TITLE
[Bug]: strip debug symbols from libclearkeycdm.so

### ISSUE THREAD

**Issue by akornatskyy** [puppeteer/puppeteer#10134]
### Bug expectation

chrome/linux-112.0.5615.121/chrome-linux64/ClearKeyCdm/_platform_specific/linux_x64/libclearkeycdm.so 442MB
chrome/linux-113.0.5672.63/chrome-linux64/ClearKeyCdm/_platform_specific/linux_x64/libclearkeycdm.so 436MB

debug symbols striped from chrome and *.so files; strip it from libclearkeycdm.so; this reduces lib size down to 5.6MB.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
see file size for libclearkeycdm.so.
```

### Error string

-

### Puppeteer version

20.1.0

### Node version

20.1.0

### Package manager

npm

### Package manager version

-

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
From this issue it's not clear what the problem is. Can you elaborate on what you think the problem is?

**Comment by akornatskyy** [comment]
when you install puppeteer it downloads chrome (chrome for testing)... when you look at `~/.cache/puppetter` directory you will see related downloads. `libclearkeycdm.so` comes with debug symbols, this results in 436MB for that single file. if you strip debug symbols (the way someone did for `chrome` and `*.so` files), the size will be reduced down to 5.6MB.

**Comment by OrKoN** [comment]
Filed https://crbug.com/1442786

**Comment by thiagowfx** [comment]
chrome-for-testing/115.0.5760.0 onwards do not have this issue anymore.

**Comment by thiagowfx** [comment]
ZIP file weighs ~140MB, unzipped size is ~340MB.

**Comment by akornatskyy** [comment]
still the case for chrome 114.0.5735.90; puppeteer 20.6.0.

**Comment by thiagowfx** [comment]
> chrome-for-testing/115.0.5760.0 onwards do not have this issue anymore.

Hi Andriy, only versions above the aforementioned were fixed.
