### ISSUE TITLE
[Bug]: confusing headless browser.version() output

### ISSUE THREAD

**Issue by bmerigan** [puppeteer/puppeteer#10146]
### Bug expectation

Output of `browser.version()` is confusing with the new Chrome.  It no longer indicates if it is running headless.  
[https://developer.chrome.com/articles/new-headless/#new-headless-in-puppeteer](https://developer.chrome.com/articles/new-headless/#new-headless-in-puppeteer)

Prior to the new headless Chrome, the output of browser.version() was `HeadlessChrome/113.0.5672.63`
Now launching puppeteer with `headless: 'new'` results in value of `Chrome/113.0.5672.63`

I understand how this is happening, but I suggest it would be helpful to append `(headless)` onto the end of the Chrome version string when required.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser1 = await puppeteer.launch({headless: true});
  console.log(browser1.version()); // HeadlessChrome/113.0.5672.63
  await browser1.close();
})();

(async () => {
  const browser2 = await puppeteer.launch({headless: 'new'});
  console.log(browser2.version()); // Chrome/113.0.5672.63
  await browser2.close();
})();
```

### Error string

no error

### Puppeteer version

20.1.2

### Node version

18.0.0

### Package manager

npm

### Package manager version

9.6.5

### Operating system

Linux

**Comment by OrKoN** [comment]
@bmerigan what is the use case for having a different version returned for the new headless mode? We aim to minimize the differences between modes and the new headless hits the same code path as the headful so the currently returned version seems appropriate to me.

**Comment by bmerigan** [comment]
I'm not sure if it matters, just noticed this while updating my codebase to use the new syntax, because browser version is something we record.
Are you saying there's no difference in tests when running head-full vs head-less?  That would imply having the ability to choose would be redundant.
