### ISSUE TITLE
[Feature]: Support tab targets

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#10147]
### Feature description

See https://docs.google.com/document/d/14aeiC_zga2SS0OXJd6eIFj8N0o5LGwUpuqa4L8NKoR4/edit?hl=en&forcehl=1#heading=h.n1atlriavj6v

**Comment by Siphosethu-Sidloyi** [comment]
Hi OrKon, 

This feature looks very interesting, I'm am new to Node and to puppeteer and am looking to improve my programming skills, could we work on this feature together? I'm not 100% how I could implement it. Let me know how I can assist

Thanks

**Comment by OrKoN** [comment]
Once the tab targets are fully supported we should enable BackForwardCache and Prerender2 features.
