### ISSUE TITLE
Docs: more explanation for page.evaluateHandle()

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1014]
https://github.com/GoogleChrome/puppeteer/issues/1003#issuecomment-335701745 mentioned that `page.evaluateHandle()` can be used to run code in the context of the page, but in a  "clean room" environment (e.g. avoiding issues with pages that override native methods). Is that right?

The [docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatehandlepagefunction-args) are fuzzy about `page.evaluateHandle()` being a next context. It mentions an alias to executionContext but I think more info on why you'd use either would be good.

**Comment by aslushnikov** [comment]
> can be used to run code in the context of the page, but in a "clean room" environment (e.g. avoiding issues with pages that override native methods). Is that right?

No, the only difference between `evaluate` and `evaluateHandle` is that the former returns a javascript-object, and the latter returns a reference to the in-page object aka JSHandle.

Anybody is welcome to improve docs, we'll be happy to review a PR!

**Comment by yelisaveta** [comment]
Hi @aslushnikov, I have raised a PR for this issue, please see: https://github.com/GoogleChrome/puppeteer/pull/1867

I will be happy to make a PR for this issue as well: https://github.com/GoogleChrome/puppeteer/issues/1051

This is my first contribution to open-source project so I am open to any help/advice to my PR. Thanks!

**Comment by yanivefraim** [comment]
@yelisaveta - are you on #1051? If not, I would like to take it (:

**Comment by yelisaveta** [comment]
@yanivefraim no I am not, feel free to take it!

**Comment by yanivefraim** [comment]
@aslushnikov - I believe this was fixed by https://github.com/GoogleChrome/puppeteer/pull/1867? (it didn't have 'fixes ...' so no reference to PR here)

**Comment by aslushnikov** [comment]
@yanivefraim you're right, thanks
