### ISSUE TITLE
[Bug]: Timed out when launching browser

### ISSUE THREAD

**Issue by juanpablo64** [puppeteer/puppeteer#10155]
### Bug expectation

I expected my browser to launch in headless mode, but all I get is this cryptic message: TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
            headless: true, 
            executablePath: '/usr/bin/chromium',
            args: [ '--disable-gpu', '--disable-setuid-sandbox', '--no-sandbox', '--no-zygote' ]
        });
        //le agregamos al browser la logica para las descargas
        let client = await browser.target().createCDPSession();
        await client.send('Browser.setDownloadBehavior', {
          behavior: 'allow', //allow downloading file 
          downloadPath: dstdir, // specify the download folder
        });

        const page = await browser.newPage({});
        await page.goto('www.google.com.ar');
        await browser.close();
```

### Error string

TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!

### Puppeteer configuration

```TypeScript
headless:true;
 [ '--disable-gpu', '--disable-setuid-sandbox', '--no-sandbox', '--no-zygote' ]
```

### Puppeteer version

19.10.1

### Node version

14.16.1

### Package manager

npm

### Package manager version

6.4.12

### Operating system

Linux

**Comment by OrKoN** [comment]
I am unable to reproduce. Probably the custom browser (/usr/bin/chromium) failed to launch. Use the `dumpio` flag to see the log from the browser. Also, try the bundled browser version with the latest Puppeteer version.

**Comment by juanpablo64** [comment]
Tried with the flag and not even that. It doesn't even log anything. I get the same error message. 

I tried using the bundled version with puppeteer, but I get this error: error while loading shared libraries: libatk-2.0 cannot open shared object file: No such file or directory
