### ISSUE TITLE
[Bug]: TypeError: page.$x is not a function

### ISSUE THREAD

**Issue by sachi-d** [puppeteer/puppeteer#10150]
### Bug expectation

I'm on 20.1.2 and I'm getting the following error:

```
TypeError: page.$x is not a function
    at scrapeText (/Users/sdangalla/Documents/scrape/ap/scrapers.js:8:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

async function scrapeText(url) {
    const browser = await puppeteer.launch();
    const page = browser.newPage();
    (await page).goto(url);

    const [el] = await page.$x('//*[@id="maincontent"]/div[1]/h1');
    const src = (await el).getProperty('src');
    const srcText = (await src).jsonValue();

    console.log({srcText})
}
```

### Error string

TypeError: page.$x is not a function

### Puppeteer version

20.1.2

### Node version

v19.5.0

### Package manager

npm

### Package manager version

9.3.1

### Operating system

macOS

**Comment by jaredmerrill** [comment]
did you ever find how to fix this i have the same problem

**Comment by mahbd** [comment]
I'm facing the same problem

**Comment by GuywithSpectacles** [comment]
Getting the same error

**Comment by Mike-Jagger** [comment]
Getting the same error here too

**Comment by usverger** [comment]
Same. Latest puppeteer 22.10.0

**Comment by usverger** [comment]
https://github.com/puppeteer/puppeteer/pull/11782 it is removed, use $$ function instead

**Comment by nobu-h-o** [comment]
im getting the same error

**Comment by Jimgitsit** [comment]
> #11782 it is removed, use $$ function instead

Bet that broke a lot of code.

**Comment by ifitllc** [comment]
Got the same error on Mac; same code worked well on windows.

**Comment by 1ikenna** [comment]
page.$x is deprecated. Use page.$$ instead and add xpath/. to the full xpath of the element. const [el] = await page.$$('xpath/.//*[@id="maincontent"]/div[1]/h1');
