### ISSUE TITLE
[Bug]: Puppeteer can run on Docker locally, but not on Cloud Run

### ISSUE THREAD

**Issue by richard-here** [puppeteer/puppeteer#10166]
### Bug expectation

I expected no error when trying to run the Puppeteer function in Cloud Run, but it does. On my local Docker Engine (Windows), it runs fine.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
  const puppeteer = require('puppeteer')

  try {
    const html = `<h1>Hello</h1>`
    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--disable-dev-shm-usage', '--no-sandbox'],
    })
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })
    const pdfBuffer = await page.pdf({
      landscape: true,
      printBackground: true,
      width: 681,
    })
    await browser.close()
  } catch (e) {
    // Some logic to handle errors (omitted)
  }
```

### Error string

Could not find Chrome (ver. 113.0.5672.63). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

### Dockerfile configuration

```TypeScript
FROM node:16

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Create app directory
WORKDIR /usr/src/app

# Uncomment to skip the chromium download when installing puppeteer. If you do,
# you'll need to launch puppeteer with:
#     browser.launch({executablePath: 'google-chrome-stable'})
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
```

### Puppeteer version

20.2.0

### Node version

16.15.1

### Package manager

npm

### Package manager version

8.11.0

### Operating system

Windows

**Comment by OrKoN** [comment]
Have you configured the cache dir like the error message says? https://pptr.dev/guides/configuration#changing-the-default-cache-directory it does not look like the binary is added to the image.

**Comment by richard-here** [comment]
> Have you configured the cache dir like the error message says? https://pptr.dev/guides/configuration#changing-the-default-cache-directory it does not look like the binary is added to the image.

I have added the `.puppeteerrc.cjs` file as mentioned in the link above, but it makes it such that Puppeteer cannot run on my local Docker. I am not sure what binary you are referring to, could you please elaborate?

**Comment by OrKoN** [comment]
Puppeteer downloads the browser binary during `npm install` and stores it to the cache folder. That folder needs to be included into the Docker image. So you need to either 1) run npm install when you build a docker image or 2) copy the cached folder installed locally to the docker image (but local binaries need to match the platform + architecture used by docker, so linux x64 binaries need to be used locally).

**Comment by richard-here** [comment]
> Puppeteer downloads the browser binary during `npm install` and stores it to the cache folder. That folder needs to be included into the Docker image. So you need to either 1) run npm install when you build a docker image or 2) copy the cached folder installed locally to the docker image (but local binaries need to match the platform + architecture used by docker, so linux x64 binaries need to be used locally).

Noted. My current situation is that when I include `.puppeteerrc.cjs`, the Puppeteer part of the code can't run in my local Docker container. Without that config file, it runs fine locally. I have not tried running it with `.puppeteerrc.js` on Cloud Run. Do I need to try running it in Cloud Run even though it can't run locally?

In my Dockerfile, I have run `npm install`, and Puppeteer is included in the `package.json` file, which means that the binary file in my local machine does not need to be copied to the Docker image running on Cloud Run. Is that right?

**Comment by OrKoN** [comment]
That's right, you also call `COPY . .` which might overwrite your Puppeteer version (depending on how your versions are pinned in package.json). In any case, just make sure that the npm install puts the binary into the cache folder and that the Puppeteer version is not overwriten.

**Comment by OrKoN** [comment]
Also, `.puppeteerrc.cjs` would need to be there before you run npm install

**Comment by richard-here** [comment]
@OrKoN Just wanted to update you on this. It turns out the error is as you mentioned, I added `.puppeteerrc.cjs` after `npm install` and this seems to caused some error. I updated the Dockerfile to the following and it works.

```
FROM node:16

# See https://crbug.com/795759
RUN apt-get update && apt-get -yq upgrade && apt-get install \
    && apt-get autoremove && apt-get autoclean

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Create app directory
WORKDIR /usr/src/app


# Bundle app source
COPY . .

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production


EXPOSE 8080
CMD [ "node", "./bin/www" ]
```

Thanks for the help!
