### ISSUE TITLE
[Bug]: Can not click the right position of the element

### ISSUE THREAD

**Issue by minggeorgelei** [puppeteer/puppeteer#10168]
### Bug expectation

The offset in the argument is in the right range of the element, but the element is not correctly clicked. I expect the element can be clicked. 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
(async ()=>{
    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
      });
    const page = (await browser.pages())[0];
    let content = '<html><head>   <title>Test Click</title></head><body><li><a href="https://google.com"><img src="download.png" height="60" width="80">Go to index page</a></li></body></html>';
    await page.setContent(content);
    const links = await page.$$('a');
    const link = links[0];
    await link.click({offset: {x: 160, y: 14}, click: 1});
    await browser.close();
})();
```

### Error string
no error
The link should be correctly clicked and jump to the link page, but it is not.

### Puppeteer version

20.2.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by OrKoN** [comment]
The link gets multiple content boxes (because of the image) and Puppeteer takes the first context box as the baseline for the offsets . We need to see if there are solutions to this.

<img width="224" alt="Screenshot 2023-05-12 at 12 12 59" src="https://github.com/puppeteer/puppeteer/assets/399150/4b113c22-2121-43fe-a935-3c9d8faa8134">

**Comment by minggeorgelei** [comment]
Ok, please find some solutions to it. We need to deal with this kind of scenario in our program. Thanks

**Comment by minggeorgelei** [comment]
I use the boundingbox like the code below:
const boundingBox = await link.boundingBox();
const x = boundingBox.x + 160;
const y = boundingBox.y + 14;
await page.mouse.move(x, y);
await page.mouse.down();
await page.mouse.up();
It can correctly click the link element

**Comment by OrKoN** [comment]
your code might not work if the link text wraps on the new line so depending on the exact text position you might click an empty space so bounding box would not work for a general case.

**Comment by minggeorgelei** [comment]
> your code might not work if the link text wraps on the new line so depending on the exact text position you might click an empty space so bounding box would not work for a general case.

OK, a general case needs to be considered.

**Comment by minggeorgelei** [comment]
Hi OrKon,
I'd like to know when this bug is planned to be fixed.
Thanks.

**Comment by OrKoN** [comment]
@minggeorgelei there are no immediate plans on fixing that.

**Comment by minggeorgelei** [comment]
Hi,
I have not found a workaround for it

**Comment by OrKoN** [comment]
It looks like this has been fixed or at least I am not able to reproduce it anymore. What made the difference is the use of the getClientRects API to compute the target clickable point.

**Comment by minggeorgelei** [comment]
I have tested on the newest version. The issue is fixed. Thanks.
