### ISSUE TITLE
[Bug]: new-headless mode downloads files

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#10161]
### Bug expectation

In old-headless mode, if you `page.goto()` a binary file (e.g. docx/xlsx/etc) then the navigation is aborted and that's the end of it. In new-headless mode then it claims to abort it, but a visible download window appears (i.e. it fails to be "headless") and the file is downloaded to the Downloads folder.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

const browser = await puppeteer.launch({ headless: 'new' })
const context = await browser.createIncognitoBrowserContext()
const page = await context.newPage()
try {
  await page.goto('https://unequivocal.eu/dl/example.docx')
} catch (err) {
  console.log(err)
  // need a delay because otherwise the browser exits before the download completes
  await new Promise(resolve => setTimeout(resolve, 5000))
}
await browser.close()
```

### Error string

no error

### Puppeteer version

20.1.2

### Node version

16.14.0

### Package manager

npm

### Package manager version

9.4.0

### Operating system

Windows

**Comment by OrKoN** [comment]
On Mac, I don't get a download window so it might be Windows-specific.

**Comment by jribbens** [comment]
It isn't Windows-specific, it happens on Linux also (at least, the file is downloaded; I don't have a monitor on a Linux server so I can't tell what visible effects happen). (But your bug report form doesn't allow multiple responses to the 'Operation system' question - or the version questions either for that matter.)

I have filed it with Chromium here: https://bugs.chromium.org/p/chromium/issues/detail?id=1444729

**Comment by OrKoN** [comment]
Thanks. File downloading might be as expected if the download also happens in the headful browser. The only difference between headful and the new headless should be that no browser UI is shown on screen.

**Comment by jribbens** [comment]
That would be unfortunate for me, since I need it to continue the existing behaviour, i.e. not to download the file. (Well, ideally I would like it to receive the response into memory and then let me do something with it, but either way I certainly don't want it to start writing things to the filesystem, which is also the opposite of what I consider "headless" to mean.)

**Comment by OrKoN** [comment]
"headless" means that UI windows are not shown and that is it. We aim at minimizing the differences between the headful and headless modes to avoid things like https://github.com/puppeteer/puppeteer/issues/299 You can still use the old headless mode but in the future it will likely become a separate binary.

**Comment by OrKoN** [comment]
For context: https://developer.chrome.com/articles/new-headless/

**Comment by OrKoN** [comment]
We will also need to have a better API around configuring the download behaviour, for sure. I.e., make use of https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior which should work the same way in both modes.

**Comment by jribbens** [comment]
To me, "headless" mode means "the browser is under programmatic control" (since by definition it cannot be under the control of a person, with no UI). So it wandering off writing files to places violates that description.

It is a bit surprising that puppeteer doesn't have an interface to `setDownloadBehavior`. (And calling it via `page.target().createCDPSession().send(...)` seems to make no difference to the behaviour in either old or new headless mode.) But even that wouldn't help me, I don't think, since there seems to be no way of knowing (a) that a download has commenced, (b) that a download has finished, and (c) the filename of the downloaded file.

**Comment by jribbens** [comment]
> > To me, "headless" mode means "the browser is under programmatic control" (since by definition it cannot be under the control of a person, with no UI).
> 
> A headful browser can also be under programmatic control.

Well, yes. "A implies B" does not mean "not A implies not B". But headful browser generally tend to be very hard to get under programmatic control since they contain hundreds of implicit assumptions that there is a human being sitting there watching who can make decisions and be asked to respond to events.

> There are CDP events for downloads https://chromedevtools.github.io/devtools-protocol/tot/Browser/#event-downloadWillBegin but Puppeteer does not support it yet.

Thanks. I think possibly `allowAndName` mode might work for me if I can get it working the way the documentation seems to imply it should.

**Comment by jribbens** [comment]
Someone at chromium.org has closed the bug I opened there as "WontFix", because presumably this individual has a quirky and esoteric understanding of the term "headless".

Could someone with the appropriate permissions please go and re-open the bug there:

https://bugs.chromium.org/p/chromium/issues/detail?id=1444729

@OrKoN

**Comment by danroot** [comment]
I have been unable to get any variation of setDownloadBehavior to work in newer puppeteer.   Previously working code using Page.setDownloadBehavior fails, as does goto method above. Based on https://github.com/puppeteer/puppeteer/issues/3722#issuecomment-679509973 I have a working function that downloads a url to a local file by using fetch in the page context and marshaling the results to the node context.

  ```
page.downloadFile = async function(url, destinationPath) {
    var binaryString =  await page.evaluate(async (url) =>
    {
        var response = await fetch(url, { method: 'GET', credentials: 'include'});
        var blob = await response.blob();
        var result = new Promise((resolve, reject) => {
          var reader = new FileReader();          
          reader.onloadend = () => resolve(reader.result);
          reader.onerror = reject;
          reader.readAsBinaryString(blob);
        });
        return result;
    },url);
    var fileBlob =  Buffer.from(binaryString , 'binary');
    await fsPromises.writeFile(destinationPath, fileBlob);
  };
```

Usage:

```
await page.downloadFile('https://unequivocal.eu/dl/example.docx','./some/path/example.docx')
```

The main downsides I see are:

* translating to string then back to file can't be ideal, but as best I can tell is only way to marshal from page context to node context.  blob and arrayBuffer won't.
* you have to know the url.  In some cases where the page generates a url on the fly on a button click, this may be difficult to obtain.
* you have to know the file name.  In some cases where the server generates the filename, this may be difficult.

But it works for my purposes and I hope it helps others.

**Comment by jribbens** [comment]
@danroot The main downside with that sort of thing from my point of view is it means the fetch is subject to CORS rules.

**Comment by OrKoN** [comment]
Downloading matches the headful browser behaviour and therefore working as expected for the new headless.

**Comment by Loc7** [comment]
Hi guys, I need Puppeteer to stop automatic file downloads too. After reading a lot, I finally think that there is no native way in Puppeteer to handle "content-disposition: attachment" responses. I see there is no interface to intercept and change them. Is there something planned for future versions? Thanks
