### ISSUE TITLE
[Feature]: Ship ESM that uses more modern JavaScript (e.g. private fields)

### ISSUE THREAD

**Issue by connorjclark** [puppeteer/puppeteer#10170]
### Feature description

I noticed that `puppeteer-core` is currently shipping JS to NPM that has code targeted for older JS, pre-private fields:

<img width="986" alt="image" src="https://github.com/puppeteer/puppeteer/assets/4071474/25748f61-1339-47db-aa2d-40fa4bc4a646">
<img width="677" alt="image" src="https://github.com/puppeteer/puppeteer/assets/4071474/faa8d9cb-487c-4ddd-b21d-1ab5a642ef08">

The package.json for this module suggests 16 is the minimum support Node. I believe 12 was the first Node to support private fields. It'd be nice if the shipped code looked more like the source by using `#private` fields.

**Comment by OrKoN** [comment]
@jrandolf could you please take a look?

**Comment by jrandolf** [comment]
We cannot do this yet according to https://node.green/#ES2022

We will enable this once we no longer support Node 16.
