### ISSUE TITLE
[Bug]: Cloudflare Captcha Don't Click (manualy)

### ISSUE THREAD

**Issue by BlackYuzia** [puppeteer/puppeteer#10196]
### Bug expectation

After open website with cloudflare I expect what click on captcha will trigger it, but instead nothing happen. Any else clicks (on other elements) are valid and work.

That happen only in `new headless` mode. In `old headless` captcha could be resolved as usual.

![image](https://github.com/puppeteer/puppeteer/assets/25010528/0d3a50e8-b057-4eba-990e-dd009c73068b)
![image](https://github.com/puppeteer/puppeteer/assets/25010528/e0ddc63a-e548-4fd3-bf1c-8df4364618e7)
(nothing happen if I click on captcha:)
![image](https://github.com/puppeteer/puppeteer/assets/25010528/12dc550c-db89-4bc3-9f86-95c131627722)
![image](https://github.com/puppeteer/puppeteer/assets/25010528/749a84ff-ec9b-4a8c-88dd-da51fdf9d22d)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer"

(async () => {
const browser = puppeteer.launch({
 headless: "new",
 args: [
              "--remote-debugging-port=9222",
            '--remote-debugging-address=0.0.0.0',
]
});
// after that you should go to chrome://inspect, connect to browser, then open page with cloudflare captcha and try resolve it by clicking on it.
})()
```

### Error string

no error

### Puppeteer version

20.2.1

### Node version

18.14.2

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by OrKoN** [comment]
There is not enough information to reproduce the issue. Please provide a runnable script including the test page. I suppose the captcha has some tricks to detect and prevent automation and that might be why it is not working. It is out of scope for Puppeteer though.

**Comment by BlackYuzia** [comment]
@OrKoN are you sure? In old headless mode, all works fine.

**Comment by OrKoN** [comment]
ah, you clicking via the screencast feature of DevTools? then yeah, please report it as crbug.com for the DevTools component. I think it should be reproducible without Puppeteer.

**Comment by BlackYuzia** [comment]
Just for note. Reported https://bugs.chromium.org/p/chromium/issues/detail?id=1446264
