### ISSUE TITLE
"TypeError: globalThis.btoa is not a function"

### ISSUE THREAD

**Issue by kwanso-adeel72** [puppeteer/puppeteer#10197]
### Bug expectation

Bug expectation
Using node 14.21.3
puppeteer 10.4.0
In production when i want to convert html into pdf they said
"TypeError: globalThis.btoa is not a function"

Here is my Code

const browser = await puppeteer.launch({ headless: "new" }); const page = await browser.newPage(); await page.setContent(html); const buffer = await page.pdf(); res.set({ 'Content-Type': 'application/pdf', 'Content-Length': buffer.length }); res.end(buffer); await browser.close();

### Bug behavior

- [ ] Flaky
- [X] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({ headless: "new" }); const page = await browser.newPage(); await page.setContent(html); const buffer = await page.pdf(); res.set({ 'Content-Type': 'application/pdf', 'Content-Length': buffer.length }); res.end(buffer); await browser.close();
```

### Error string

TypeError: globalThis.btoa is not a function

### Puppeteer version

 10.4.0

### Node version

16.21.3

### Package manager

npm

### Package manager version

6.14.3

### Operating system

Linux

**Comment by OrKoN** [comment]
Please use the latest Puppeteer version. I believe it has been already fixed (https://github.com/puppeteer/puppeteer/issues/10173).
