### ISSUE TITLE
[Bug]: ElementHandle.dragAndDrop gets stuck forever

### ISSUE THREAD

**Issue by chirag64** [puppeteer/puppeteer#10204]
### Bug expectation

Expection: When `ElementHandle.dragAndDrop(AnotherElementHandle);` is called, `Element` should be dropped to `AnotherElement`

Actual behavior: When `ElementHandle.dragAndDrop(AnotherElementHandle);` is called, the script always gets stuck at that step. In the code example, you will observe `Before drag and drop` getting logged in console, but not `After drag and drop`.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setViewport({ width: 1366, height: 768 });

    await page.goto('https://www.javascripttutorial.net/sample/webapis/drag-n-drop-basics/');

    await page.waitForSelector('.item');
    const draggable = await page.$('.item')
    const droppable = await page.$('.box:nth-of-type(2)');

    // This is where the actual issue is
    console.log('Before drag and drop');
    await draggable.dragAndDrop(droppable);
    console.log('After drag and drop');

    await page.screenshot({ path: './image.jpg', type: 'jpeg' });
    await browser.close();
})();
```

### Error string

no error

### Puppeteer version

20.2.1

### Node version

16.19.1

### Package manager

npm

### Package manager version

8.19.3

### Operating system

macOS

**Comment by chirag64** [comment]
Even the automated GitHub Action above failed with the error `The action has timed out`.

**Comment by Lightning00Blade** [comment]
You will need to set the `await page.setDragInterception(true);` so the drag'n'drop works as expected.
Will keep this open as at least we should fail after a timeout on our end.
