### ISSUE TITLE
Request Interception Enhancements

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#1020]
Request interception should allow:
- abort request with different errors
- fake the response: headers, status, body.

**Comment by sukrosono** [comment]
That was nice feature to have, can someone tell me what M1 stand for?

**Comment by aslushnikov** [comment]
@brutalcrozt M1 is the next major milestone.

**Comment by entrptaher** [comment]
```
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage({headless: false});
  await page.setRequestInterceptionEnabled(true);
  page.on('request', interceptedRequest => {
    if (interceptedRequest.url.endsWith('.png') || interceptedRequest.url.endsWith('.jpg'))
      interceptedRequest.abort();
    else
      interceptedRequest.continue();
  });
  await page.goto('https://example.com');
  await page.screenshot('test.png');
  // await browser.close();
});
```

This hangs the node process on windows.
Nothing happens if I use setRequestInterceptionEnabled.

**Comment by aslushnikov** [comment]
@entrptaher Doesn't hang for me when I uncomment the `await browser.close()`. Anyhow, it has nothing to do with this issue; please, file another one.

This, btw, is fixed.

**Comment by entrptaher** [comment]
@aslushnikov I did create an issue, https://github.com/GoogleChrome/puppeteer/issues/1110
