### ISSUE TITLE
[Security question]: suspicious network activity by Chrome process

### ISSUE THREAD

**Issue by kopylash** [puppeteer/puppeteer#10203]
Hello, we are using Puppeteer in Docker to render PDF files from own HTML templates.

Recently AWS GuardDuty started raising alerts for suspicious network activity by Chrome process that tries to reach the IP `34.159.75.132`

```
Time - 05/04/2023 08:00:04.534 am
Description:Process exe from container is communicating with a remote host 34.159.75.132 that is known to hold credentials and other stolen data captured by malware.
Title:Container is communicating with a Drop Point.
Type:Trojan:Runtime/DropPoint
featureName:RuntimeMonitoring
threatListName:ProofPoint
actionType:NETWORK_CONNECTION
connectionDirection:OUTBOUND
Remote IP - 34.159.75.132
Below is details of executed file & path:-
runtimeDetails:{
process:{
name:exe
executablePath:/opt/google/chrome/chrome
executableSha256:00492145ac56494764b21c6366835d15d84de7e134fac8cd219a11519f6c6a09
namespacePid:726
pwd:/usr/src/app
pid:23103
}}

SRC Observation:
- This alert was triggered when a process from container is communicating with a remote IP that is categorized as suspicious by ProofPoint threat feed.
- Remote IP is showing clean on VirusTotal
- This behavior could be indicative of a malicious actor that may gained access to the workload, and has downloaded and executed malware or other software as part of the potential compromise
- File is not seen by VirusTotal (Based on Hash value).

```

### What we did for investigation
The IP address is via reverse DNS lookup points to `132.75.159.34.bc.googleusercontent.com` which tends to be GCP.

We follow the [guide of installing Puppeteer in Docker](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) and our Dockerfile start like this
```
FROM amd64/node:16
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && curl -o awscli.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip && unzip awscli.zip && ./aws/install && rm -rf aws*

```

We verified that Chrome is installed from apt repository and public key matches with [official Google linux software repos](https://www.google.com/linuxrepositories/).

**Our next guesses where:**
- it's Chrome sending statistics
- malicious code is injected into our HTML templates

To exclude the option of injected code we added logging for each network request and monitored it for a month. Haven't noticed anything external.
```js
page.on('request', (req) => {
            if (req.isInterceptResolutionHandled()) return;
            const opt = {method, headers: Object.assign(req.headers(), headers)};

            if (process.env.LOG_PUPPETEER_NETWORK === 'true') {
                if (!req.url().startsWith('data:')) { // this excludes base64 images
                    log.info({
                        method: req.method(),
                        url: req.url(),
                        body: req.postData(),
                        resourceType: req.resourceType(),
                    }, `Puppeteer req: ${req.method()} ${req.url()}`)
                }
            }
            req.continue(opt);
        });
```

**Final question**
Has anyone faced similar issue?
Can it be ubuntu automatic updates or some statistics?
Google Chrome binary is 100% legit, but we don't know why AWS GuardDuty marks the IP as suspicious and we don't understand the nature of this traffic.

I'd be thankful for any comments or suggestions 🙏

**Comment by Lightning00Blade** [comment]
@kopylash can you provide the earliest date you started receiving this alerts?

**Comment by m95e** [comment]
They re wrote my source code

**Comment by OrKoN** [comment]
Note that `page.on('request'...` might not capture all requests from a page. For example, it would not currently capture requests from out-of-process iframes.

**Comment by OrKoN** [comment]
Could you reproduce it using DevTools and check the initiator for the request? Chrome should not be sending any stats or getting updates from bc.googleusercontent.com

**Comment by m95e** [comment]
> Could you reproduce it using DevTools and check the initiator for the request? Chrome should not be sending any stats or getting updates from bc.googleusercontent.com

It's me on my own device

**Comment by m95e** [comment]
I'm just creeping . Someone hacked my phone a few months ago and recently

**Comment by OrKoN** [comment]
@m95e please open a separate issue instead of commenting on this one

**Comment by m95e** [comment]
It's the same issue

**Comment by m95e** [comment]
I do have a data collections officer?

**Comment by m95e** [comment]
My developer options were off until recently when my phone was hacked .

**Comment by kopylash** [comment]
> Could you reproduce it using DevTools and check the initiator for the request? Chrome should not be sending any stats or getting updates from bc.googleusercontent.com

@OrKoN If I understood you right, you suggest spawning our Docker container with Puppeteer, then connecting DevTools to it and checking whether we see that traffic when opening one of our HTML templates?

**Comment by OrKoN** [comment]
@kopylash I don't think it has to be in the Docker but, yes, open the HTML templates and see if they load anything suspicious. Are you rendering user-provided content? or are those static templates?

**Comment by kopylash** [comment]
Those are static templates that we fully control, but I will doublecheck

**Comment by OrKoN** [comment]
@kopylash do you load an external scripts?

**Comment by OrKoN** [comment]
@kopylash btw it looks like the domain name points to a Netlify website

**Comment by kopylash** [comment]
@OrKoN sorry, for confusion, but I got the issue. We had wrong reference to normalize.css in our HTML template. It actually points to the HTML page, not to any of CDNs, so Netlify was doing a redirect and that traffic was detected as suspicious. Thanks for pointing out.
```
<link rel="stylesheet" href="https://yarnpkg.com/en/package/normalize.css" />
```
