### ISSUE TITLE
[Bug] overridePermissions() not working for clipboard-copy in headless browser

### ISSUE THREAD

**Issue by AnmolBansalDEV** [puppeteer/puppeteer#10211]
Below is the workaround to the issue. Please resolve the bug in overridePermissions.

 Howdy y'all, in case you're looking for something to copy and paste to enable clipboard permissions, some code that worked to do what @ericcornelissen did, but in the latest version of Puppeteer, is to create a separate CDP session to grant yourself sanitized clipboard permissions. While someone should probably make a PR to expose the `clipboardSanitizedWrite` permissions to `overridePermissions()` this still gets the job done. Note that I couldn't find a way in which puppeteer exposes the `BrowserContextID`, so this only works for the default browser context.

```js
const client = await page.target().createCDPSession();
await client.send('Browser.grantPermissions', {
  origin: "https://command.verkada.com",
  permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'],
});
```

Alternatively, we can use the CDP API [`Browser.setPermission`](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setPermission). As a side note, it looks like this is the API you'd want to use for `panTiltZoom` cameras and `userVisibleOnly` push notifications.

```js
const client = await page.target().createCDPSession();
await client.send('Browser.setPermission', {
  origin: "https://command.verkada.com",
  permission: {
    name: 'clipboard-write',
    allowWithoutSanitization: true
  },
  setting: 'granted',
});

_Originally posted by @rmichnovicz-verkada in https://github.com/puppeteer/puppeteer/issues/3241#issuecomment-1171770074_

**Comment by OrKoN** [comment]
@Lightning00Blade ptal, I think it is a duplicate
