### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lmqgfem** [puppeteer/puppeteer#10213]
### Bug expectation

Puppeteer does not start. When refreshing the browser, it displays an error.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.screenshot({ path: 'example.png' });
  await browser.close();
})();
```

### Error string

Error: Cannot find module 'puppeteer-core/internal/puppeteer-core.js'

### Puppeteer version

20.2.1

### Node version

17.9.1

### Package manager

npm

### Package manager version

8.11.0

### Operating system

Linux

**Comment by jrandolf** [comment]
We cannot reproduce without knowing your set up. We recommend looking very carefully at our tutorial.

**Comment by ingria** [comment]
I was having the same error when I was launching my app via ESM package. I've switched to the native mjs format and now everything works fine.
