### ISSUE TITLE
[Bug]: Chrome Extension Modal Page Access via browser.Targets

### ISSUE THREAD

**Issue by ItsDaveB** [puppeteer/puppeteer#10212]
### Bug expectation

When testing a page, with the extension loaded upon browser launch. 
When clicking a button that triggers a modal from the chrome extension, I expected to be able to access the target of the modal and be able to test against it and manipulate it using puppeteer, due to it being triggered from the page I am originally testing.

But what actually happens, is this target does not appear in the array of browser targets returned, I am guessing due to how this is invoked. 

`browser.targets()`

I also cannot use the extension url directly, because the operation I need to test is only accessible upon button click which as a result triggers the opening of the modal.

But if I do access the extension using a url for a page that is not a modal that is also exposed by the extension, I can actually see this returned in `browser.targets()`. 

Example being: `chrome-extension://lpfcbjknijpeeillifnkikgncikgfhdo/mainPopup.html`

Chrome extension: https://chrome.google.com/webstore/detail/nami/lpfcbjknijpeeillifnkikgncikgfhdo

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
To replicate this the extension needs to be installed, wallet created and invoked on a crypto dex for example. https://app.wingriders.com/swap?from=ada&to=f43a62fdc3965df486de8a0d32fe800963589c41b38946602a0dc53541474958&poolType=constantProduct&transactions=all
```

### Error string

No error.

### Puppeteer version

20.2.1

### Node version

18.9.0

### Package manager

npm

### Package manager version

8.6.0

### Operating system

Windows

**Comment by dpbeaumont** [comment]
I managed to resolve this by connecting puppeteer again to this new instance using remote debugging, this then gave me access to the pages.

` const browserURL = 'http://127.0.0.1:21222';
    const namiBrowser = await puppeteer.connect({ browserURL });
    var namiBrowserPages = await namiBrowser.pages();`
