### ISSUE TITLE
[Bug]: Use waitForFileChooser() in  iframe,   error:Waiting for `FileChooser` failed: 30000ms exceeded

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#10216]
### Bug expectation

 Error:
TimeoutError: Waiting for `FileChooser` failed: 30000ms exceeded

      at Timeout._onTimeout (node_modules/puppeteer-core/src/util/DeferredPromise.ts:

expect:
file chooser works fine.

Plus:Same code works fine in pptr version 5.4.1

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const frameName = 'blalba'
const frame = this.page.frames().find((a) => a.name() === fameName);
//confirmed that the frame does exist and found
const [fileChooser] = await Promise.all([
        frame.page().waitForFileChooser(),
        frame.click(selector),]);
await fileChooser.accept([f]);
```
```


### Error string

TimeoutError: Waiting for `FileChooser` failed: 30000ms exceeded

### Puppeteer configuration

_No response_

### Puppeteer version

19.8.3

### Node version

16.14.2

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by FishBlanche** [comment]
Same code works fine in old version 5.4.1
we upgrade to 19.8.3 recently and the error occurs.
Any idea?

**Comment by OrKoN** [comment]
Please provide a complete reproducible example and try the latest version.

**Comment by FishBlanche** [comment]
> Based on some reason,we need use 19.8.3

and i don not think use the latest version will fix this.

**Comment by FishBlanche** [comment]
according to https://pptr.dev/api/puppeteer.page.waitforfilechooser/
![remarks](https://github.com/puppeteer/puppeteer/assets/19261291/559c3814-8a02-492c-b26c-2d3179b19ed0)
But when i use it in iframe,the dialog pop up and never disappear.
![screenshotiframe](https://github.com/puppeteer/puppeteer/assets/19261291/962463a0-ecea-45d4-9228-379c7b193d65)

**Comment by OrKoN** [comment]
Could you please provide a complete reproducible example? Without seeing the test page it is a guess work. Is the iframe an out-of-process iframe? if it is, it would not work because you wait for the dialog on the page and that part is not ready to deal with OOPIFs.

**Comment by FishBlanche** [comment]
Yeah，confirmed that it's  a oopif.
 frame.page().waitForFileChooser(), i wait for filechooser on the frame's page instead of the master page.It does not work either?

**Comment by OrKoN** [comment]
The frame does not have the waitForFileChooser method. `--disable-features=site-per-process` as docs say you might need both `--disable-features=IsolateOrigins,site-per-process`. You should verify that the right isolation is enabled by checking chrome://process-internals/#site-isolation.

**Comment by OrKoN** [comment]
> frame's page instead of the master page

frame's page is the main page.
