### ISSUE TITLE
Error: not opened

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1021]
I have a very big array of data. I iterate over that array and from within it I call an anonymous asynchronous function that opens a new page using puppeteer and navigates to a URL. This loop works perfectly but after some time it stops working and throwing a "not opened" error and that error is thrown from the line that creates a new page. What should I do?

**Comment by vsemozhetbyt** [comment]
Do you close opened pages after they are not needed?

**Comment by ghost** [comment]
Yes I do

**Comment by ebidel** [comment]
@kepempem Please follow the issue template when filing bugs. Is there a code snippet that repros the issue?
