### ISSUE TITLE
chromeHeadless can't run on linux

### ISSUE THREAD

**Issue by AnjumMomin** [puppeteer/puppeteer#1022]
#

### Steps to reproduce

**Tell us about your environment:**

* chrome version: 61
* Platform / OS version: win7 
*Selenium  version:-selenium server standalone 2.53.1
*java Version:-java 1.8.0_91
* URLs (if applicable):

**What is the expected result?**
my program can in chrome headless successfully

**What happens instead?** 
program can't run 
if am running the headless script using "java -jar 'abc.jar' "
i can't throw any error or exception

**Comment by Garbee** [comment]
> Selenium version:-selenium server standalone 2.53.1

So, is Selenium using Puppeteer now? This repository is specifically about *puppeteer* issues, not headless in general. Especially in relation to integration with other software layers.

**Comment by ebidel** [comment]
You can [definitely](https://developers.google.com/web/updates/2017/04/headless-chrome#drivers) use headless with Selenium.

@AnjumMomin we'll need more information to help debug. If this is a Puppeeteer issue, please reopen with a code snippet that repos the issue. If it's a problem with using headless Chrome in Selenium, than an issue should be posted on their issue tracker. 

I also notice you're using Chrome 61. We recommend Chrome 62 for Puppeteer.

**Comment by janetba** [comment]
@ebidel  I am also having this issue. In two different instances. 
1) When running over docker with the --headless, --no-sandbox, and --disable-gpu I always get the error no session found. 
2) When running with those same flags through my mac. The test run but they do launch a version of Chrome, not the full UI but little Chrome icons show up at the bottom. 

I am running it in version 61. I had no trouble with version 59 but now that I have version 61 this is having issues.

Any pointers on how to fix this?

**Comment by ebidel** [comment]
For 1., I've been able to get headless working in Docker using https://github.com/ebidel/lighthouse-ci/blob/master/builder/Dockerfile.headless

https://bugs.chromium.org/p/chromium/issues/detail?id=750505#c3 fixes 2.) on Mac. Not sure if there were similar issues on Windows with the task bar. If so, it's possible those were fixed on later releases.

**Comment by janetba** [comment]
That worked thank you :)

**Comment by AnjumMomin** [comment]
if some changes in my script to run headless on server?
plz tell me ....i don't know how to run on server ...and what are the changes in my script
