### ISSUE TITLE
Broken glyphs in pdfs

### ISSUE THREAD

**Issue by truthslayer** [puppeteer/puppeteer#1023]
[nyt.puppet.compressed.pdf](https://github.com/GoogleChrome/puppeteer/files/1379541/nyt.puppet.compressed.pdf)

### Steps to reproduce

**Tell us about your environment:**
~> node --version
v8.7.0
~/node_modules/puppeteer> npm list
puppeteer@0.11.0 [...]/node_modules/puppeteer
├─┬ debug@2.6.9
│ └── ms@2.0.0

~> cat /etc/*-release
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.2"
PRETTY_NAME="openSUSE Leap 42.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
openSUSE 42.2 (x86_64)
VERSION = 42.2
CODENAME = Malachite

Running the following code

https://pastebin.com/XPqCH1Ue

followed by the command

`gs` -sDEVICE=pdfwrite -dCompatibilityLeve=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=nyt.puppet.compressed.pdf nyt-pdf.pdf`

should produce a compressed PDF. Instead, there are a bunch of glyph errors:

`GPL Ghostscript 9.15: ERROR: Page 0 used undefined glyph 'g1' from type 3 font 'PDFType3Untitled', key ''`

(complete errors [here](https://pastebin.com/psiNigUX))

I'm not sure exactly what's happening with the PDF rendering such that the fonts get screwy; the PDF looks fine, though it doesn't once it's compressed with GS ending in those errors. Both attached.
[nyt-pdf.pdf](https://github.com/GoogleChrome/puppeteer/files/1379540/nyt-pdf.pdf)

Separately, I wouldn't need to compress the PDF if it were possible to control the quality of the output pdf somewhat via an argument...

**Comment by aslushnikov** [comment]
@truthslayer One thing I noticed is that you don't wait correctly for network idle: the syntax you use is not yet implemented. Given that the page uses webfont, this might be the reason for the error.

To wait for `networkidle` event, you should use the following syntax:

```js
    await page.goto(website, {
      waitUntil: 'networkidle'
    });
```

Waiting for both `networkidle` and `load` is possible, see https://github.com/GoogleChrome/puppeteer/issues/805#issue-258296410

Other then that, I'm not sure what exactly is going on here. It might be an error in either `gs` or chrome's `saveAsPdf`. I'd try filing this upstream to `https://crbug.com/new`.

**Comment by truthslayer** [comment]
Ok, I tried that and still didn't fix the issue. Thanks for the pointer!
