### ISSUE TITLE
[Bug]: EC2 Firefox "extraPrefsFirefox" not working

### ISSUE THREAD

**Issue by tirhande** [puppeteer/puppeteer#10237]
### Bug expectation

Implementing PDF download functionality.
I used it as chromium, but if it is a large file, it may be interrupted due to lack of memory, so I changed it to Firefox.

I gave extra PrefsFirefox option at Puppeteer.launch
```ts
const browser = await puppeteer.launch({
  product: "firefox",
  headless: true,
  extraPrefsFirefox: {
    "print.print_headerleft": "&PT",
    "print.print_headercenter": "&PT",
    "print.print_headerright": "&PT",
    "print.print_footerleft": "&PT",
    "print.print_footercenter": "&PT",
    "print.print_footerright": "&PT",
  },
});
```
It works well in the local environment (MacOS), but it is seen as a Default value in the AWS EC2 environment.

How can I solve this?

### I expected this
<img width="644" alt="스크린샷 2023-05-24 오후 3 25 08" src="https://github.com/puppeteer/puppeteer/assets/74575497/945c3705-83aa-45f1-82db-64edc4250724">

<img width="570" alt="스크린샷 2023-05-24 4 08 57 PM" src="https://github.com/puppeteer/puppeteer/assets/74575497/ce725090-49ff-4c11-9cc7-baee504eb7c8">

### but instead of this

<img width="671" alt="스크린샷 2023-05-24 오후 3 25 19" src="https://github.com/puppeteer/puppeteer/assets/74575497/d8b32fae-2487-4046-8c9d-9c7a8a5eafa6">

<img width="563" alt="스크린샷 2023-05-24 오후 4 07 36" src="https://github.com/puppeteer/puppeteer/assets/74575497/43f83516-998e-4f4c-b37e-0a88048d57bc">

### Bug behavior

- [ ] Flaky
- [X] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
  product: "firefox",
  headless: true,
  extraPrefsFirefox: {
    "print.print_headerleft": "&PT",
    "print.print_headercenter": "&PT",
    "print.print_headerright": "&PT",
    "print.print_footerleft": "&PT",
    "print.print_footercenter": "&PT",
    "print.print_footerright": "&PT",
  },
});
```

### Error string

extraPrefsFirefox not working

### Puppeteer version

13.3.2

### Node version

v14.18.0

### Package manager

npm

### Package manager version

7.24.2

### Operating system

Linux

**Comment by OrKoN** [comment]
cc @whimboo

**Comment by whimboo** [comment]
If it works locally but not in EC2 I assume there is a problem with invoking Firefox. Maybe you can run with with trace logs enabled? Just add `"remote.log.level": "Trace"` to the `extraPrefsFirefox` and check if that gives more details of the individual CDP commands.

**Comment by tirhande** [comment]
@whimboo 

Thank you for your quick reply.!!

[firefox_log_trace_230524.txt](https://github.com/puppeteer/puppeteer/files/11551863/firefox_log_trace_230524.txt)

Is the log of the form correct?

In EC2, the Firefox version is 102.10.0-1.amzn2.0.1 or 113.0.1, (I tried both)
AND

cd ./node_modules/puppeteer && PUPPETEER_PRODUCT=firefox node install.js
(firefox Nightly r115.0a1)

**Comment by tirhande** [comment]
Property "print.save_as_pdf.internal_destinations.enabled" is being applied properly according to true/false.

However, the property "print.print_headercenter" does not apply.
I think this is related to Cairo 1.17.4.

Can I change it to another producer such as skia, quartz, not cairo?

**Comment by whimboo** [comment]
I sadly cannot help with that given that this is not in the area of my expertise. But you could file a bug for that at https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Printing.

**Comment by NicksonYap** [comment]
Sorry for bumping this thread, just to help out those looking to use `displayHeaderFooter`  with Firefox browser in Puppeteer it is no longer working in the latest Puppeteer Firefox that uses the WebDriver BiDi /  `webDriverBiDi` as protocol

due to it not being implemented https://github.com/w3c/webdriver-bidi/issues/741

but `displayHeaderFooter` was actaully working as seen above screenshots https://github.com/puppeteer/puppeteer/issues/10237#issue-1723271192
this is back when the CDP / `cdp` protocol was used

```js
 browser = await puppeteer.launch({
      browser: 'firefox', 
      // protocol: 'webDriverBiDi', // does not support `displayHeaderFooter`
      protocol: 'cdp',  // supports `displayHeaderFooter`

      ...
});
```

however, as of Puppeteer v24 support for CDP for FIrefox was completely removed / disabled in favor of WebDriver BiDi
https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v24.0.0

so in order to use Puppeteer with Firefox browser that uses CDP protocol to get the `displayHeaderFooter`  working use the version right before v24 which is v23.11.1 

```sh
# for PowerShell
$env:PUPPETEER_PRODUCT="firefox"
# for Linux/macOS (not tested by me)
PUPPETEER_PRODUCT=firefox

# install previous Puppeteer version with Firefox browser that uses CDP protocol 
npm install puppeteer@23.11.1 

# install the right puppeteer
npx puppeteer browsers install firefox
```

if using PNPM instead of NPM directly
```sh
# install previous Puppeteer version with Firefox browser that uses CDP protocol 
pnpm add puppeteer@23.11.1 

# install the right puppeteer
pnpm npx puppeteer browsers install firefox
```

and `displayHeaderFooter` should work as above
