### ISSUE TITLE
[Feature]: Support testing autofill

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#10244]
### Feature description

In M115, the CDP support for Autofill testing is rolling out. We need to add a method to trigger it from Puppeteer.

**Comment by madmath** [comment]
Hi, is this supported in puppeteer now? Do you have a link to more information?

**Comment by OrKoN** [comment]
Hey, the documentation for the new method is here https://pptr.dev/api/puppeteer.elementhandle.autofill/ and the CDP domain is here https://chromedevtools.github.io/devtools-protocol/tot/Autofill/
