### ISSUE TITLE
[Bug]: headless: 'new' running from Docker doesn't set screen size

### ISSUE THREAD

**Issue by nesro** [puppeteer/puppeteer#10243]
### Bug expectation

I'm running Puppeteer tests from Docker (on Mac). I'm unable to set `window.screen.width` and `window.screen.height` with the latest version 20.3.0 and the new headless settings.

The example below works fine with `headless: true` as the output is:
`headless=true, window.screen.width=1920, window.screen.height=1080`

but with `headless: 'new'`, it prints:
`headless=new, window.screen.width=800, window.screen.height=600` 

The Docker I use is from `ghcr.io/puppeteer/puppeteer:20.3.0`

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

void (async (): Promise<void> => {
    const width = 1920;
    const height = 1080;
    const headless = 'new'; // or true;
    const browser = await puppeteer.launch({
        headless,
        defaultViewport: { width, height },
        args: ['--no-sandbox', `--window-size=${width},${height}`],
    });
    const page = await browser.newPage();
    await page.goto('https://www.google.com');
    page.on('console', async message => {
        for (const logs of message.args()) {
            console.log(await logs.jsonValue());
        }
    });
    await page.evaluate(
        headlessArgument =>
            console.log(
                `headless=${headlessArgument}, window.screen.width=${window.screen.width}, window.screen.height=${window.screen.height}`,
            ),
        headless,
    );

    await page.close();
    await browser.close();
})();

```

### Error string

no error

### Puppeteer version

20.3.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

macOS

**Comment by OrKoN** [comment]
I believe it is the same as https://crbug.com/1447977

**Comment by kvitekp** [comment]
--window-size switch sets Chrome window size, not the screen size. This is slightly modified script output running on Linux:

headless=new, window.screen.width=800, window.screen.height=600, window.innerWidth=1920, window.innerHeight=1080

**Comment by nivhsay** [comment]
In new headless, chrome uses the underlying window system to fix the bounds on the available screen.
On linux, chrome uses the [Ozone platform](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ozone_overview.md).

While inspecting the process being spawned, I found the arg`--ozone-override-screen-size=800,600` being set.

So to solve this problem, while launching puppeteer on linux, you can overrwrite this flag as part of the args.
In my case, I am using Chrome Stable 114 and I need a 1080 x 1920 window on a 1080 x 1920 screen (portrait).

```js
...
  launch({
    executablePath: 'google-chrome',
    defaultViewport: { width, height },
    args: [
      '--no-sandbox',
      '--start-fullscreen',
      '--disable-gpu',
      `--window-size=${width},${height}`,
      '--disable-setuid-sandbox',
      `--ozone-override-screen-size=${width},${height}`,
      '--headless=new',
    ],
  })
...
```

**Comment by OrKoN** [comment]
Working as expected as per https://crbug.com/1447977

**Comment by TheGP** [comment]
@nivhsay may I know how do you inspect the "process being spawned"? I'm curious because this arg didn't work for me.

**Comment by TheGP** [comment]
@nivhsay I just want to see all launch arguments available too
