### ISSUE TITLE
[Bug]: New headless implementation steals focus when screenshotting even in headless mode

### ISSUE THREAD

**Issue by hansSchall** [puppeteer/puppeteer#10246]
### Bug expectation

Unlike the old implementation, the new one steels focus when taking a screenhot, even in headless mode. When taking screenshots frequently (for example 2 or mote per second), it can be challenging to stop the process (you have to press Ctrl-C and clicking to focus the terminal at the same time)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

function wait(time: number) {
    return new Promise<void>(res => {
        setTimeout(() => {
            res();
        }, time);
    });
}

async function main() {
    const browser = await puppeteer.launch({
        headless: "new" // new
        // --- or ---
        headless: true // old
    });
    const page = await browser.newPage();
    await page.goto("http://example.com/");
    await page.setViewport({ width: 1820, height: 1080 });

    for (let i = 0; i < 10; i++) {
        await wait(500);
        await page.screenshot({ encoding: "base64" });
        console.log("took screenshot");
    }

    await browser.close();
}

main().catch(console.error);
```

### Error string

no error

### Puppeteer version

v20.4.0

### Node version

v20.0.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by OrKoN** [comment]
Seems to work fine on Mac. I will report it to Chromium and see if it can be reproduced on windows.

**Comment by OrKoN** [comment]
https://crbug.com/1449117

**Comment by herecy** [comment]
So what is the status? The bug is closed and a commit was made upstream, but with 115 the issue still occurs.

**Comment by herecy** [comment]
Ok seems it is only in 116.

**Comment by hansSchall** [comment]
Seems to be fixed...

using puppeteer@21.1.0
