### ISSUE TITLE
[Bug]: Pipeline failed "ldd: ./chrome: No such file or directory"

### ISSUE THREAD

**Issue by janaratolonbaeva** [puppeteer/puppeteer#10256]
### Bug expectation

In AWS CodePipeline build failed, when I added `ldd chrome | grep not` and `yum update nss -y`. It couldn't find chrome file or dir. Wht?

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
Build failed, but locale build succeeded
```

### Error string

Running command ldd chrome | grep not ldd: ./chrome: No such file or directory

### Puppeteer configuration

```TypeScript
This is codecept.config.ts

/* External dependencies */
require('ts-node/register');
const { setHeadlessWhen } = require('@codeceptjs/configure');

/* Local dependencies */
const { atomize } = require('./presettings.ts');

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.NODE_ENV);
process.setMaxListeners(Infinity);

exports.config = {
  tests: './integration-tests/tests/**_test.ts',
  output: './integration-tests/output',
  helpers: {
    Puppeteer: {
      url: `https://${process.env.GATSBY_SITE_DOMAIN}`,
      show: false,
      headless: process.env.STAGE === '',
      windowSize: '1420x768',
      chrome: {
        args: [
          '--start-maximized',
          '--lang=en-US,ru-RU,ky-KG',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--headless=new'
        ],
      },
    },
    GeneralHelper: {
      require: './helpers/general.ts',
    },
    LocaleHelper: {
      require: './helpers/localeHelper.ts',
    },
    LoginHelper: {
      require: './helpers/login.ts',
    },
    TransactionsHelper: {
      require: './helpers/transactions.ts',
    },
    AdminHelper: {
      require: './helpers/admin.ts',
    },
    ManagerHelper: {
      require: './helpers/manager.ts',
    },
    AccountantHelper: {
      require: './helpers/accountant.ts',
    },
  },
  include: {
    I: './steps_file.ts',
  },
  name: 'integration-tests',
  atomize,
  plugins: {
    autoDelay: {
      enabled: true,
    },
    retryFailedStep: {
      enabled: true,
      minTimeout: 5000,
    },
    screenshotOnFail: {
      enabled: true,
    },
  },
  enablePreview: false,
  require: ['ts-node/register'],
};
```

### Puppeteer version

20.4.0

### Node version

18

### Package manager

npm

### Package manager version

v9.6.7

### Operating system

Linux

**Comment by janaratolonbaeva** [comment]
I didn't understand you, what dependencies I have to update or install? 
`{
  "name": "averspay-web",
  "version": "1.0.0",
  "description": "averspay-web",
  "author": "Esen Sagynov <kadishmal@gmail.com>",
  "keywords": [
    "gatsby"
  ],
  "scripts": {
    "build": "gatsby build",
    "build:beta": "GATSBY_SITE_DOMAIN=www.beta.averspay.kg gatsby build",
    "clean": "npm run clean:soft && rm -rf .cache public node_modules package-lock.json",
    "clean:soft": "gatsby clean && npm run clean:test",
    "clean:test": "jest --clearCache",
    "deploy": "gatsby-plugin-s3 deploy -y",
    "dev": "gatsby develop",
    "prepare-env": "./prepare-env.js",
    "test": "npm run clean:test && jest src/** --coverage",
    "def-beta": "codeceptjs def",
    "codecept-beta": "codeceptjs run",
    "delete-text": "node change-codecept.conf.ts",
    "test-codecept": "export GATSBY_SITE_DOMAIN=http://localhost:8000 && export TEST_PHONES='777007247,709745440,505007247,700123890' && npm run delete-text && npm run def-beta && npm run codecept-beta"
  },
  "engines": {
    "node": "~18",
    "npm": "~9"
  },
  "dependencies": {
    "@apollo/client": "3.7.14",
    "@reach/router": "1.3.4",
    "@testing-library/user-event": "14.4.3",
    "amazon-cognito-identity-js": "6.2.0",
    "apollo-cache-inmemory": "1.6.6",
    "atomize": "1.0.28",
    "aws-appsync": "4.1.9",
    "aws-appsync-auth-link": "3.0.7",
    "aws-appsync-react": "4.0.15",
    "aws-appsync-subscription-link": "3.1.2",
    "aws-sdk": "2.1383.0",
    "camelcase": "7.0.1",
    "codeceptjs": "3.4.1",
    "gatsby": "4.22.0",
    "gatsby-plugin-google-fonts-v2": "1.0.1",
    "gatsby-plugin-google-gtag": "4.22.0",
    "gatsby-plugin-image": "2.22.0",
    "gatsby-plugin-manifest": "4.22.0",
    "gatsby-plugin-nprogress": "4.24.0",
    "gatsby-plugin-react-i18next": "2.0.4",
    "gatsby-plugin-s3": "0.3.8",
    "gatsby-plugin-sass": "5.22.0",
    "gatsby-plugin-sharp": "4.22.0",
    "gatsby-plugin-sitemap": "5.22.0",
    "gatsby-plugin-styletron": "7.22.0",
    "gatsby-source-filesystem": "4.22.0",
    "gatsby-transformer-sharp": "4.22.0",
    "i18next": "22.5.0",
    "image-conversion": "2.1.1",
    "immutability-helper": "3.1.1",
    "puppeteer": "20.4.0",
    "react": "18.2.0",
    "react-apollo": "3.1.5",
    "react-calendar": "4.2.1",
    "react-cropper": "2.3.3",
    "react-dom": "18.2.0",
    "react-helmet": "6.1.0",
    "react-html-parser": "2.0.2",
    "react-i18next": "12.3.1",
    "react-onesignal": "2.0.4",
    "react-redux": "8.0.5",
    "react-transition-group": "4.4.5",
    "redux": "4.2.1",
    "redux-devtools-extension": "2.13.9",
    "redux-observable": "2.0.0",
    "rxjs": "7.8.1",
    "sass": "1.62.1",
    "styletron-engine-atomic": "1.5.0",
    "styletron-react": "6.1.0",
    "ts-node": "10.9.1",
    "typescript": "5.0.4",
    "util": "0.12.5",
    "uuid": "9.0.0",
    "webpack-filter-warnings-plugin": "1.2.1"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "7.18.6",
    "@testing-library/jest-dom": "5.16.5",
    "@testing-library/react": "14.0.0",
    "@types/jest": "29.5.1",
    "@types/react": "18.2.6",
    "@types/react-helmet": "6.1.6",
    "@types/react-test-renderer": "18.0.0",
    "babel-jest": "29.5.0",
    "babel-preset-gatsby": "3.10.00",
    "cheerio": "1.0.0-rc.12",
    "dotenv": "16.0.3",
    "glob": "10.2.6",
    "identity-obj-proxy": "3.0.0",
    "jest": "29.5.0",
    "jest-environment-jsdom": "29.5.0",
    "jest-fetch-mock": "3.0.3",
    "jest-junit": "16.0.0",
    "jsdom": "22.0.0",
    "jsdom-global": "3.0.2",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "redux-mock-store": "1.5.4",
    "replace-in-file": "6.3.5"
  }
}
`

**Comment by OrKoN** [comment]
Sorry, we cannot offer you a general help for your environment. Please ask this question on StackOverflow. I am sure there are people familiar with AWS CodePipeline and how to configure it there.

**Comment by OrKoN** [comment]
For ldd to work you need to be in the folder where the chrome binary is located. The Puppeteer by default installs it to `~/.cache/puppeteer/chrome/linux-VERSIONUMBER/chrome-linux/`

**Comment by janaratolonbaeva** [comment]
@OrKoN but it not found ldd: ./chrome: No such file or directory
Why?
