### ISSUE TITLE
[Feature]: Pin GitHub Actions to a full length commit SHA

### ISSUE THREAD

**Issue by jaitjacob** [puppeteer/puppeteer#10264]
### Feature description

Considering we use third-party actions, it is recommended as a good security practice to pin GitHub Actions to a full length commit SHA. 

The change would touch `.yml` files in the `.github/workflows/` directory as follows,
Taking `.github/workflows/ci.yml` as an example,
`uses: peaceiris/actions-gh-pages@v3` **versus** `uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 #v3.9.3`

I would like to contribute PR for this.

Read more on this [here](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions).

**Comment by OrKoN** [comment]
That sounds good: one thing to keep in mind is that it would be great to avoid having dependabot updates for every minor bump and when dependabot bumps the hash it should also bump the version comment next to it. Not sure if that is supported by depedabot.

**Comment by jaitjacob** [comment]
>  "...it would be great to avoid having dependabot updates for every minor bump"

We could add the following within our `dependabot.yml` to address the above concern.  I have limited up to 3 PRs per week. Let me know if you rather this to be more or less.
```
updates:
...
...
  - package-ecosystem: "github-actions" # Necessary to update action hashs	
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3` # Allow up to 3 opened pull requests for github-actions versions
...
```

> "... it should also bump the version comment next to it."

 [Here](https://github.blog/2020-06-25-dependabot-now-updates-your-actions-workflows/#:~:text=Dependabot%20creates%20pull%20requests%20that%20update%20the%20action%20to%20the%20latest%20released%20tag%20(e.g.%2C%20v2)%2C%20regardless%20of%20if%20you%E2%80%99re%20currently%20on%20a%20release%20tag%2C%20a%20pre%2Drelease%20tag%2C%20or%20a%20specific%20hash.) is something I found on GitHub's blog confirming it can update to latest tag regardless if we are on a specific hash. I am unsure if it adds a comment.

**Comment by jaitjacob** [comment]
No, I meant dependabot will update hashes to latest hash of the new version. It is the associated semantic version comment next to it that I am unsure about.

**Comment by jaitjacob** [comment]
ok, this should answer our query of whether hash & comment with semvar is updated. yes it does. 

Check: [dependabot/dependabot-core/issues/4691](https://github.com/dependabot/dependabot-core/issues/4691)

**Comment by OrKoN** [comment]
Nice! Let's change to pinned versions then.
