### ISSUE TITLE
[Bug]: Table pagination, rowspan border misalignment

### ISSUE THREAD

**Issue by destinyWD** [puppeteer/puppeteer#10268]
### Bug expectation

Generate PDF table from HTML, set rowspan, and misplace border after pagination ;The old version v9.0.0 is normal, but there are issues after using the latest version
![image](https://github.com/puppeteer/puppeteer/assets/30520379/9107f376-b528-4bf3-bf59-b2e344fdb6f6)
![image](https://github.com/puppeteer/puppeteer/assets/30520379/f2ffe684-08c2-4a1d-8542-b25f6720fe42)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const runPdfTask = async (url,options = {}) => {
  const puppeteerInstance = await pool.acquire();
  try {
    const { page } = puppeteerInstance;
    await page.setViewport({
      width: 1280,
      height: 960
    });
    await page.goto(url,{ waitUntil: 'networkidle0' });
    const pdfFile = await page.pdf(options);
    return pdfFile;
  } catch (error) {
    console.error('Error:', error);
  } finally {
    pool.release(puppeteerInstance);
  }
};
```

### Error string

no error

### Puppeteer version

v20.2.1

### Node version

16.18.1

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by OrKoN** [comment]
Could you please file the bug at crbug.com? You would need to provide a test page to reproduce the issue.
