### ISSUE TITLE
window.chrome is not set

### ISSUE THREAD

**Issue by blue-cp** [puppeteer/puppeteer#1026]
I recently came across a phishing page which has js below for browser detection
```
     <script>
           var isOpera = (!!window.opr && !!opr.addons) || !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0;

            var isChrome = !!window.chrome && !!window.chrome.webstore;

            var isFirefox = typeof InstallTrigger !== 'undefined';

            var isSafari = Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor') > 0;

            var isMobile = function detectmob() {if(window.innerWidth <= 800 && window.innerHeight <= 600) {return true;} else {return false;}};

            if(isChrome || isOpera || isFirefox || isSafari || isMobile == 'true')
           {window.location='redirt.php';}else{document.write('<h2>This browser is not supported!<br>
         <small>Please use a different broswer.</small></h2>');}
            </script>
```

In puppeteer  window.chrome is not set. I tried setting it in page.evaluate however when script loads it is set to null again. Is there a way to set window.chrome object to emulate chrome?

**Comment by schelkun** [comment]
I think chrome object is only defined in Google Chrome (for browser extensions), but puppeteer use Chromium.

**Comment by schelkun** [comment]
Last puppeteer version with automatically downloaded Chromium is working for me well.

```
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        headless: false,
        timeout: 10000
    });
    const page = await browser.newPage();

    await page.goto('https://github.com/GoogleChrome/puppeteer/');

    const result = await page.evaluate(() => {
        return typeof window.chrome;
    });

    console.log(result);
})();
```

This script returns `object`.

**Comment by schelkun** [comment]
Same for `window.chrome.webstore`.

**Comment by blue-cp** [comment]
Interesting. I did setup test page with above script and it did not work work for me. I am using latest puppeteer as well.

I have attached sample test pages. If you can host it locally and point puppeteer to detect.html, you should be able to replicate issue on your side well.

[chrome_test.zip](https://github.com/GoogleChrome/puppeteer/files/1383176/chrome_test.zip)

**Comment by JohnBruce** [comment]
Im seeing the same thing as @abhishekdubey1 .  Its worth noting that I'm using the 3 week old version of puppeteer from npm (which is the latest).

**Comment by JohnBruce** [comment]
@abhishekdubey1 as a workaround you can add chrome to window in a function you pass to `page.evaluateOnNewDocument` by doing something similiar to this example:  https://github.com/GoogleChrome/puppeteer/blob/aa58f25bc1c7f8cf72c70c453f036bb873349164/examples/detect-sniff.js

**Comment by paulirish** [comment]
John's workaround sounds good to me.

It's unlikely puppeteer or headless chrome will attempt to reintroduce the window.chrome object to the page, as it's nonstandard and kinda crazy.

**Comment by blue-cp** [comment]
Thanks all. @JohnBruce  Thanks for the pointer. I will try it out.

**Comment by minodisk** [comment]
@schelkun Does `window.chrome` exist with `headless: true`?

**Comment by aslushnikov** [comment]
@minodisk it doesn't.

**Comment by newhouse** [comment]
Hi everyone, I'm having this same issue using another testing framework (NIghtwatch JS) and believe that it's a Chrome issue when running "headless", and not a Puppeteer (or Nightwatch) issue.

Rather than papering over the cracks, can anyone explain or point to documentation as to **_why_** the `window.chrome` object is not defined during headless mode? @abhishekdubey1 you seemed confident that it does not exist, but do you know why or how come?

I've filed [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=806333) at chromium to see if anyone can answer why the `window.chrome` object is not available in "headless" mode.

This problem breaks some of my tests and I'd love to be able to run in headless!

Thanks to all!

**Comment by swang2019** [comment]
I tested with three different env: 

window.chrome.webstore is not existing in Mac 10.14.3 (Official Chrome 71)
window.chrome.webstore is existing in Windows 10 (Official Chrome 72)
window.chrome.webstore is not existing in Puppeteer launched Chromium 73

**Comment by taewookim** [comment]
there's headless browser detectors leveraging this.
Been 2 years..   Any workarounds?

**Comment by Jakeroid** [comment]
Any updates?
