### ISSUE TITLE
[Bug]:  PUPPETEER_DOWNLOAD_BASE_URL authentication dropped resulting in 401

### ISSUE THREAD

**Issue by RJKeane2000** [puppeteer/puppeteer#10262]
### Bug expectation

When setting the PUPPETEER_DOWNLOAD_BASE_URL to an authenticated Jfrog artifactory URL, the authentication is dropped in the browsers package httpUtil script file. 

I'm working behind a Corporate proxy and we must go through jfrog for any downloads. I set the PUPPETEER_DOWNLOAD_BASE_URL to go through an authenticated jfrog  URL.

Example: 
```
export PUPPETEER_DOWNLOAD_BASE_URL=https://userId:password@company.jfrog.io/artifactory/chrome-for-testing-remote
```

I get this error:

Error: Download failed: server returned code 401. URL: https://user:password@company.jfrog.io/artifactory/chrome-for-testing-remote/113.0.5672.63/win64/chrome-win64.zip

I expect the authentication to be carried forward to the browser request.

Here's the code in the httpUtil.ts that I believe needs to be updated. I added setting the `auth` attribute. I found in my local testing that this works with and without authenticated base URLs. 

```typescript
import {URL, urlToHttpOptions } from 'url';  <---- Needed to import urlToHttpOptions

export function httpRequest(
  url: URL,
  method: string,
  response: (x: http.IncomingMessage) => void,
  keepAlive = true
): http.ClientRequest {
  const options: http.RequestOptions = {
    protocol: url.protocol,
    hostname: url.hostname,
    auth: urlToHttpOptions(url).auth,,  <---- One way to set auth. Works when auth not passed as well.
    port: url.port,
    path: url.pathname + url.search,
    method,
    headers: keepAlive ? {Connection: 'keep-alive'} : undefined,
    agent: new ProxyAgent(),
  };

```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
```

### Error string

no error

### Puppeteer version

20.4.0

### Node version

19.7.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by OrKoN** [comment]
Fixed in https://github.com/puppeteer/puppeteer/pull/10271
