### ISSUE TITLE
Re-enable BiDi tests on macos for Firefox

### ISSUE THREAD

**Issue by juliandescottes** [puppeteer/puppeteer#10272]
https://github.com/puppeteer/puppeteer/pull/10121 disabled macos tests for Firefox

https://bugzilla.mozilla.org/show_bug.cgi?id=1832778 was filed but we have issues to reproduce the issue on our side.
We landed an extended timeout to monitor navigations at https://bugzilla.mozilla.org/show_bug.cgi?id=1816538 which should hopefully be in Firefox Nightly relatively soon.

We should see if this helps and allows to re-enable the tests.

**Comment by juliandescottes** [comment]
Sadly we had to backout the patch as it caused more intermittents on our CI. I will close the issue for now as I don't have a good way for puppeteer to change the timeout, I can reopen once we figured this out.

**Comment by juliandescottes** [comment]
Yesterday we landed a patch at https://bugzilla.mozilla.org/show_bug.cgi?id=1832891, which should hopefully stick. Let's see if this helps with this issue.

**Comment by OrKoN** [comment]
It looks like Firefox BiDi tests on macos timeout frequently https://github.com/puppeteer/puppeteer/actions/runs/5321130027/jobs/9637613731?pr=10423 

```
  14) Frame specs
       "before all" hook in "Frame specs":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/puppeteer/puppeteer/test/build/frame.spec.js)
      at createTimeoutError (/Users/runner/work/puppeteer/puppeteer/node_modules/mocha/lib/errors.js:498:15)
      at Hook.Runnable._timeoutError (/Users/runner/work/puppeteer/puppeteer/node_modules/mocha/lib/runnable.js:431:10)
      at Timeout.<anonymous> (/Users/runner/work/puppeteer/puppeteer/node_modules/mocha/lib/runnable.js:246:24)
      at listOnTimeout (node:internal/timers:569:17)
      at processTimers (node:internal/timers:512:7
 ```

**Comment by OrKoN** [comment]
saw a similar error for the page spec in the previous runs

**Comment by whimboo** [comment]
Which code in Puppeteer is running at this time? What does it wait for?

**Comment by OrKoN** [comment]
It waits for the browser to launch.

**Comment by whimboo** [comment]
If there is a specific test which is failing all the time could we test with a longer timeout and trace logs enabled? I would really like to know what's causing the slowness. With the default logs we sadly don't see anything.
