### ISSUE TITLE
[Bug]: recvmsg: Connection reset by peer (104)

### ISSUE THREAD

**Issue by Ollie1700** [puppeteer/puppeteer#10283]
### Bug expectation

I expected Puppeteer to navigate to links as normal - we have not changed any config.

Instead, we are getting this error: [0531/142448.613680:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
Using the following args for puppeteer:

{
    "executablePath": "/usr/bin/google-chrome-stable",
    "headless": true,
    "ignoreHTTPSErrors": true,
    "slowMo": 250,
    "defaultViewport": {
        "width": 2560,
        "height": 1360
    },
    "args": [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--lang=en-GB,en;q=0.9",
        "--ignore-certificate-errors",
        "--disable-web-security",
        "--disable-features=IsolateOrigins",
        "--disable-site-isolation-trials",
        "--user-agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15'"
    ]
}
```

### Error string

Failed to launch the browser process! [0531/142448.613680:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)

### Puppeteer version

17.1.3

### Node version

16.5.0

### Package manager

npm

### Package manager version

7.19.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Try the latest version and also try using the bundled version of Chrome. There is a possibility that Chrome (/usr/bin/google-chrome-stable) has updated and does not work/is incompatible with the Puppeteer version you use.

**Comment by narita-takeru** [comment]
I got the same error.

```
$ /usr/bin/google-chrome-stable
recvmsg: Connection reset bypeer (104)
```

Segmentation fault with help option.

```
$ /usr/bin/google-chrome-stable -h
Segmentation fault
```

I tried to run using core dump.

```
(gdb) run
Starting program: /opt/google/chrome/chrome
/opt/google/chrome/chrome: /opt/google/chrome/lib/libc.so.6: version `GLIBC_2.25' not found (required by /lib64/libcrypt.so.1)
/opt/google/chrome/chrome: /opt/google/chrome/lib/libc.so.6: version `GLIBC_2.25' not found (required by /lib64/libmount.so.1)
/opt/google/chrome/chrome: /opt/google/chrome/lib/libc.so.6: version `GLIBC_2.25' not found (required by /lib64/libblkid.so.1)
/opt/google/chrome/chrome: /opt/google/chrome/lib/libc.so.6: version `GLIBC_2.25' not found (required by /lib64/libuuid.so.1)
```


It ships with glibc, but that doesn't seem to include GLIBC_2.25.

```
strings /opt/google/chrome/lib/libc.so.6 | grep ^GLIBC_ | grep 2.25

(nothing)
```


I hope this helps you in resolving this issue.

**Comment by johnnietheblack** [comment]
Getting a similar error

**Comment by vickyRathee** [comment]
@johnnietheblack Did you find any resolution? I am getting the same error

```
Jun  8 11:03:00 ip-172-31-56-225 web: CHROMIUM_PATH /usr/bin/google-chrome-stable
Jun  8 11:03:00 ip-172-31-56-225 web: Cannot start browser Error: Failed to launch the browser process!
Jun  8 11:03:00 ip-172-31-56-225 web: [16222:16222:0608/110300.786434:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)
Jun  8 11:03:00 ip-172-31-56-225 web: TROUBLESHOOTING: https://pptr.dev/troubleshooting
Jun  8 11:03:00 ip-172-31-56-225 web: at Interface.onClose (/var/app/current/node_modules/puppeteer/node_modules/@puppeteer/browsers/src/launch.ts:398:11)
Jun  8 11:03:00 ip-172-31-56-225 web: at Interface.emit (node:events:525:35)
Jun  8 11:03:00 ip-172-31-56-225 web: at Interface.emit (node:domain:489:12)
Jun  8 11:03:00 ip-172-31-56-225 web: at Interface.close (node:internal/readline/interface:533:10)
Jun  8 11:03:00 ip-172-31-56-225 web: at Socket.onend (node:internal/readline/interface:259:10)
Jun  8 11:03:00 ip-172-31-56-225 web: at Socket.emit (node:events:525:35)
Jun  8 11:03:00 ip-172-31-56-225 web: at Socket.emit (node:domain:489:12)
Jun  8 11:03:00 ip-172-31-56-225 web: at endReadableNT (node:internal/streams/readable:1359:12)
Jun  8 11:03:00 ip-172-31-56-225 web: at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by scvgoe** [comment]
I install chrome beta instead of stable, if you need use [this script](https://gist.githubusercontent.com/free-lunch/c6e7958bee01bcb79bf5301c3884d928/raw/gistfile1.txt).

**Comment by demilsson** [comment]
Thank you @scvgoe, it seems to work as a temporary fix.

**Comment by scuba-st3v3** [comment]
I solved this problem by ensuring that the user account home directory existed in the container running my application. Also ensure the user has access to the application directory.

```
module.exports = {
  cacheDirectory: join(__dirname, 'src/.cache', 'puppeteer'),
  executablePath: '/usr/bin/chromium-browser',
  args: [
    '--headless=new',
    '--disable-gpu',
    '--disable-dev-shm-usage'
  ]
}
```
https://pptr.dev/troubleshooting#running-on-alpine

**Comment by RameshwarEducloude** [comment]
How to solve this error on AWS Linux machine?

**Comment by leonelvsc** [comment]
> I solved this problem by ensuring that the user account home directory existed in the container running my application. Also ensuring the user had access to the application directory and subsequent files.
> 
> ```
> module.exports = {
>   cacheDirectory: join(__dirname, 'src/.cache', 'puppeteer'),
>   executablePath: '/usr/bin/chromium-browser',
>   args: [
>     '--headless=new',
>     '--disable-gpu',
>     '--disable-dev-shm-usage'
>   ]
> }
> ```
> 
> https://pptr.dev/troubleshooting#running-on-alpine

Thanks! here on rockylinux:9 container solved by creating /home/<theuser> and /var/cache/<theuser>
