### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by sanjanaweb123** [puppeteer/puppeteer#10292]
### Feature description

hello guys
i am using the  puppeteer in nest js for generating the pdf in backend, previously it's working , but after update new version of puppeteer below code stop work and throw the below error 
await puppeteer.launch({
          headless: 'new',
          executablePath: '/usr/bin/google-chrome-stable',
        });
UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
please help how to fix this issues in new version

**Comment by OrKoN** [comment]
Please report the bug properly. There is not enough details in this report. Make sure /usr/bin/google-chrome-stable is compatible with the Puppeteer version https://pptr.dev/chromium-support
