### ISSUE TITLE
[Bug]: Page.content() ignores some HTML comments

### ISSUE THREAD

**Issue by korridor** [puppeteer/puppeteer#10291]
### Bug expectation

The `Page.content()` function should return the full HTML content. ([Docs](https://pptr.dev/api/puppeteer.page.content/))
In my case, all comments outside if the `html` tag disappear.

Example page:
```html
<!DOCTYPE html>
<!-- this comment before the html tag -->
<html lang="en">
<!-- this comment is in the html -->
<head>
   <!-- this comment is in the head -->
  <meta charset="UTF-8">
  <title>TEST</title>
</head>
<body>
    <h1>TEST</h1>
    <!-- this comment is in the body -->
</body>
</html>
<!-- I am a comment after the html tag -->
```

In the response of `page.content()` the comments `<!-- I am a comment after the html tag -->` and `<!-- this comment before the html tag -->` are missing.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; // TS/ESM are all supported.

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://constantin-graf-temp.s3.fr-par.scw.cloud/test.html', {
    waitUntil: 'load'
  });
  let content = await page.content();
  console.log(content);
  await browser.close();
})();
```

### Error string

no error

### Puppeteer version

20.5.0

### Node version

20.2.0

### Package manager

npm

### Package manager version

9.6.6

### Operating system

Linux

**Comment by OrKoN** [comment]
`page.content()` returns `document.documentElement.outerHTML` so comments outside of it are ignored.

**Comment by OrKoN** [comment]
It should probably iterate and serialize direct children of document.

**Comment by OrKoN** [comment]
cc @Lightning00Blade
