### ISSUE TITLE
[Bug]: puppeteer 20.5.0 contains breaking change

### ISSUE THREAD

**Issue by mtrezza** [puppeteer/puppeteer#10294]
### Bug expectation

Upgrading puppeteer from 20.4.0 to 20.5.0 introduces a breaking change in which the `=??` operator is used. This operator is unsupported by Node 14.

If the package intends to follow semver, the release should be retracted (marked as deprecated) and released as a new major version.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
https://github.com/parse-community/Parse-SDK-JS/actions/runs/5134413113/jobs/9241494061#step:10:1
```

### Error string

SyntaxError: Unexpected token '??='

### Puppeteer version

20.0.5

### Node version

14.x

### Package manager

npm

### Package manager version

-

### Operating system

Linux

**Comment by OrKoN** [comment]
It is not a breaking change since the support for node 14 has been dropped in v20.0.0 https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/CHANGELOG.md#2000-2023-05-02

**Comment by mtrezza** [comment]
Right, could you add an engine version to the puppeteer `package.json` file, like the `puppeteer-core` file has? The [docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) say:

> If you don't specify the version (or if you specify "*" as the version), then any version of node will do.

I read this as since there is no engines entry, the package claims to work on any node version.
