### ISSUE TITLE
page.click() doesn't always work

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#103]
The following script hangs for me waiting for "click" to happen on the second link.
However, if I make viewport width 1000 instead of 300, the script works just fine.

```js
const {Browser} = require('puppeteer');
const browser = new Browser({headless: false});

browser.newPage().then(async page => {
  page.on('load', () => {
    console.log('LOADED: ' + page.url());
  });
  // Make width 1000 instead of 300 and the scripts works just fine
  await page.setViewport({width: 300, height: 300}); 
  await page.navigate('https://google.com');
  await page.waitFor('input[name=q]');
  await page.focus('input[name=q]');
  await page.type('blin');
  await page.press('Enter');
  for (let i = 0; i < 10; ++i) {
    let searchResult = `div.g:nth-child(${i + 1}) h3 a`;
    await page.waitFor(searchResult, {visible: true});
    page.click(searchResult);
    await page.waitForNavigation();

    await page.screenshot({path: `screenshot-${i + 1}.png`});
    await page.goBack();
  }
  browser.close();
});
```

Running the script with `DEBUG=*page node scrape.js` shows what's going on.

Looks like we're clicking outside of viewport and the click turns out to be a noop.

@JoelEinbinder, wdyt?

**Comment by JoelEinbinder** [comment]
It looks like `scrollIntoViewIfNeeded` and `scrollIntoView` don't scroll horizontally if the element is only partially offscreen. Then when we try to click the center, it is offscreen.

**Comment by JoelEinbinder** [comment]
I think the correct solution is to force mouse events to stay inside the viewport. This should still click on the right element if it is partially obscured. Working on a patch.
