### ISSUE TITLE
How do I capture browser errors?

### ISSUE THREAD

**Issue by LLLLLamHo** [puppeteer/puppeteer#1030]
**How do I capture browser errors?**

When using puppeteer for automated testing, if the page is wrongly reported due to a JavaScript error, if the error is obtained by puppeteer?

**Comment by TotusSomnium** [comment]
check out https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-page

I'm using something like this for catching javascript errors:
```javascript
page.on("pageerror", function(err) {  
    theTempValue = err.toString();
    console.log("Page error: " + theTempValue); 
}
```

You can also look for exceptions and other things with something like:
```javascript
page.on("error", function (err) {  
    theTempValue = err.toString();
    console.log("Error: " + theTempValue); 
```

**Comment by sukrosono** [comment]
@LLLLLamHo can you describe more specific usage?

```
const puppeteer= require("puppeteer");

(async()=> {
  const browser= await puppeteer.launch();
  const page= await browser.newPage();


  page.on('error', err=> {
    console.log('error happen at the page: ', err);
  });

  page.on('pageerror', pageerr=> {
    console.log('pageerror occurred: ', pageerr);
  })
  const three= await page.evaluate(()=> 1+2);
  console.log('three value is: ', three);
  try {
    await page.evaluate(()=> {
      throw new Error('js throw some error');
    });
  } catch (e) {
    console.log('an expection on page.evaluate ', e);
  }
  await browser.close();
})();
```
With that script you are able to obtain the error via try-catch block, error and pagerror is not fired.
The the spec for [pageerror](https://github.com/GoogleChrome/puppeteer/blob/master/test/test.js#L1329) give a curiosity

**Comment by LLLLLamHo** [comment]
@brutalcrozt thanks It's very detailed

**Comment by LLLLLamHo** [comment]
@TotusSomnium thanks It's very detailed

**Comment by aditodkar** [comment]
@sukrosono @TotusSomnium Any suggestions on how to log stack trace if there are any browser error? err.stack does not show any message. I also tried this: https://gist.github.com/mizchi/f7ea22ef022d586964a80d9aef59becf but did not work
