### ISSUE TITLE
[Bug]: Always takes full screen even if `fullPage` options is not set as true

### ISSUE THREAD

**Issue by RC047** [puppeteer/puppeteer#10327]
### Bug expectation

When I call the function from `page.screenshot()` and it doesn't use any options, and when the response appears the image is always full/long screenshot. This happens when I use the Chrome browser, if I use Chromium it doesn't have a strange problem.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
let puppeteer = require('puppeteer')
let fs = require('fs')

async function ssweb(url) {
	let browser = await puppeteer.launch({
		headless: false,
		executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
	})
	let page = (await browser.pages())[0]
	await page.goto(url, { waitUntil: 'networkidle0', timeout: 5000 })
	let response = await page.screenshot()
	await page.close()
	return response
}

ssweb('https://www.google.com/search?q=puppeteer')
.then(buffer => {
   fs.writeFileSync('path/to/screenshot.jpg', buffer)
})
.catch(console.error)
```

### Error string

no error

### Puppeteer version

20.5.0

### Node version

18.12.1

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not able to reproduce using the bundled browser version. I would assume that Chrome you have installed might be incompatible. See https://pptr.dev/chromium-support for compatibility of versions.

**Comment by jaimeiniesta** [comment]
I'm seeing the same issue. Even if I pass `fullPage: false` or I leave it out as this should be default, I always get a full page screenshot.

Here is a full example

https://github.com/jaimeiniesta/screenshot-nextjs

This is failing in all puppeteer versions from 13 to 18. In Puppeteer 19 it works fine on my machine, but it crashes in Vercel. Versions 13 to 18 work in Vercel but they always take full page screenshots.
