### ISSUE TITLE
[Bug]: When I use page.evaluate ,ReferenceError: common_1 is not defined 

### ISSUE THREAD

**Issue by steady-join** [puppeteer/puppeteer#10339]
### Bug expectation

<img width="954" alt="image" src="https://github.com/puppeteer/puppeteer/assets/29935583/2fbe2263-64ef-4456-951f-6e3786a83873">
<img width="419" alt="image" src="https://github.com/puppeteer/puppeteer/assets/29935583/0794ceac-e082-45c2-b415-dd6f6bb9087e">

for nestjs.

Is it the configuration problem of typescript? or comonjs module ... emm,  how to solve it.Think you

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
setTimeout(async () => {
        await page.evaluate(() => {
          Logger.log('startRecord evaluate');
         
        });
      }, 3e3);
```

### Error string

ReferenceError: common_1 is not defined

### Puppeteer version

20.4.0

### Node version

16.15.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
Please read the [Evaluate JavaScript](https://pptr.dev/guides/evaluate-javascript). In short there is no class `Logger` on the page you are trying to evaluate. You can use the native `console.log` in combination with 
```
page.on('console', log => {Logger.log(`Page logs: ${log.message()}`)})
await page.evaluate(...)
```
( see the [ConsoleMessage](https://pptr.dev/api/puppeteer.consolemessage)) to get the log in NestJS context.
