### ISSUE TITLE
[Bug]: Corporate MITM firewall download failure with puppeteer >= v19.9.0: "self-signed certificate in certificate chain"

### ISSUE THREAD

**Issue by gilly3** [puppeteer/puppeteer#10331]
### Bug expectation

I'm using Node 18 on Windows 10 behind a corporate firewall that re-encrypts all traffic using a custom ca-file.
My `.npmrc` has `cafile = "<path to ca file>"`

I expected to be able to install the latest version of puppeteer without error while behind a corporate firewall that re-encrypts all traffic using a custom ca-file.

But, instead, the latest installable version of puppeteer is 19.8.5.  Starting with v19.9.0, I get an error complaining about a self-signed certificate.  The error is the same for later versions, except that, starting with v20.0.0, "Chromium" changes to "Chrome", and the buildid changes as well.

```
npm ERR! code 1
npm ERR! path C:\git\idicore\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r1108766! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: self-signed certificate in certificate chain
npm ERR!     at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at TLSSocket._finishInit (node:_tls_wrap:959:8)
npm ERR!     at ssl.onhandshakedone (node:_tls_wrap:743:12) {
npm ERR!   code: 'SELF_SIGNED_CERT_IN_CHAIN'
npm ERR! }
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
> npm install puppeteer@19.9.0
```

### Error string

Error: self-signed certificate in certificate chain

### Puppeteer version

20.5.0

### Node version

18.14.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by OrKoN** [comment]
Does setting `NODE_TLS_REJECT_UNAUTHORIZED=0` env var solve the issue? I think previous versions might have included rejectUnauthorized: false on the request level in the code, which is not good for security. I am not sure how configuration in npmrc can be applied here. Probably you need to use `NODE_EXTRA_CA_CERTS`, please let us know if that works.

**Comment by gilly3** [comment]
Setting `NODE_EXTRA_CA_CERTS` did the trick.  Thanks!
