### ISSUE TITLE
How do i judge the tap/click event success?

### ISSUE THREAD

**Issue by fhmd4k** [puppeteer/puppeteer#1033]
The tap/click event sometimes failed in the slow network speed.
For example, it can't trigger a href element to open new tab.(It may be the element position is error in the slow network speed).

I think it's sure to judge the event success state.

**Comment by fhmd4k** [comment]
`Input.dispatchTouchEvent Input.dispatchMouseEvent` from **element position** to trigger event rather than use **dom event** to trigger.
If the position is error,it means the event is failed.
So it's important to how to get a **correct position**.

**Comment by aslushnikov** [comment]
@fhmd4k I'm not sure I follow. What do you mean by 'success'?

**Comment by fhmd4k** [comment]
@aslushnikov I use the `page.tap(a link element)` . 
If i tap success:
1. may open new tab (_blank) or navigate to other page(_self)?
2. may do some javascripts (if some listeners have listened)?
3. and so on

in the `lib/Page.js` find

```js
async tap(selector) {
  const handle = await this.$(selector);
  console.assert(handle, 'No node found for selector: ' + selector);
  await handle.tap();
  await handle.dispose();
}
```

it will call the elementHandle to do, in the `lib/ElementHandle.js`
look at **element.getBoundingClientRect()**

```js
async _visibleCenter() {
  const center = await this.evaluate(element => {
    if (!element.ownerDocument.contains(element))
      return null;
    element.scrollIntoViewIfNeeded();
    //In the slow network, the page may load incompletely. it will get the incorrect position. If the position is incorrect,it will tap failed. 
    //For example:  ( the a link element correct position is 150, 200). In the slow network, it get the incorrect position 150,170.  It can't tap the element successfully.
    const rect = element.getBoundingClientRect();
    return {
      x: (Math.max(rect.left, 0) + Math.min(rect.right, window.innerWidth)) / 2,
      y: (Math.max(rect.top, 0) + Math.min(rect.bottom, window.innerHeight)) / 2
    };
  });
  if (!center)
    throw new Error('No node found for selector: ' + selector);
  return center;
}


async tap() {
  const { x, y } = await this._visibleCenter();
  await this._touchscreen.tap(x, y);
}
```

**Comment by aslushnikov** [comment]
> If i tap success:
> 1. may open new tab (_blank) or navigate to other page(_self)?
> 2. may do some javascripts (if some listeners have listened)?
> 3. and so on

@fhmd4k there's no generic way to determine tap "success", as you defined it here. Every case requires special treatment.

A few ideas:
1. A new tab would be possible to track once #554 lands. The navigations are reported with 'framenavigated' event.
2. JavaScript execution should be observed entirely by side effects it produces. If there are no side-effects, in some cases you can override some method to trace it (see [examples/detect-sniff.js](https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/examples/detect-sniff.js))

**Comment by fhmd4k** [comment]
thanks
