### ISSUE TITLE
Can't bypass Cloudflare protection using headless browser in AWS Lambda.[Bug]: 

### ISSUE THREAD

**Issue by dev1ninja** [puppeteer/puppeteer#10347]
### Bug expectation

I tried to bypass Cloudflare protection using headless browser but I couldn't success.
Headless browser does not be redirected to https://businesssearch.ohiosos.gov/
![image](https://github.com/Sparticuz/chromium/assets/82922629/4df4ea52-da89-4306-86ac-45990c3c52b1)
I tried many packages. Here are the packages what I used.

- @sparticuz/chromium
- puppeteer-extra
- puppeteer
- chrome-aws-lambda
- puppeteer-core

I was able to pass it with `chrome-aws-lambda` when I test it on my local environment. It seems to use the Google Chrome browser where already installed in OS.
Here is script.
```
const puppeteer = require('puppeteer-extra');
const chromiumaws = require('chrome-aws-lambda')
const chromium = require('@sparticuz/chromium');
const puppeteerCore = require('puppeteer-core');

exports.handler = async function (event, context, callback) {

    const StealthPlugin = require('puppeteer-extra-plugin-stealth')
    puppeteer.use(StealthPlugin())

    const browser = await puppeteer.launch({
        // args: chromium.args,
        executablePath: chromiumaws.executablePath,
        headless: chromiumaws.headless,
        ignoreHTTPSErrors: true,
    })
    const page = await browser.newPage();
    console.log("Browser opened!")
    // Go to here https://bot.sannysoft.com/ and check userAgent.
    await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36')

    console.log("Navigating...")
    await page.goto('https://businesssearch.ohiosos.gov/')
    
    await page.waitForSelector('#bSearch', { visible: true });
    await page.type('#bSearch', 'pizza');
};
```
But this script has an error on AWS Lambda. I think it's because there is no installed Google Chrome in AWS Lambda environment.
 "errorMessage": "Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n",

So I tried to use `@sparticuz/chromium`.
Here is script.
```
const chromium = require('@sparticuz/chromium');
exports.handler = async function (event, context, callback) {

    const StealthPlugin = require('puppeteer-extra-plugin-stealth')
    puppeteer.use(StealthPlugin())

    const browser = await puppeteer.launch({
        // args: chromium.args,
        executablePath: await chromium .executablePath(),
        headless: chromium .headless,
        ignoreHTTPSErrors: true,
    })
    const page = await browser.newPage();
    console.log("Browser opened!")
    // Go to here https://bot.sannysoft.com/ and check userAgent.
    await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36')

    console.log("Navigating...")
    await page.goto('https://businesssearch.ohiosos.gov/')
    
    await page.waitForSelector('#bSearch', { visible: true });
    await page.type('#bSearch', 'pizza');
};
```
It opens headless browser where located in `\node_modules\@sparticuz\chromium\bin`.
![image](https://github.com/Sparticuz/chromium/assets/82922629/1daae352-97a8-46e5-9f7c-4baa2d8bb47d)
Here are error messages what I had on AWS Lambda test.
`"TimeoutError: Waiting for selector `#bSearch` failed: Waiting failed: 30000ms exceeded"`
`"errorMessage": "Could not find Chrome (ver. 113.0.5672.63). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.",
`

And that headless browser seems to be not able to pass the Cloudflare Protection.
So I think the best way is to install Google Chrome stable version on AWS Lambda environment and use `chrome-aws-lambda`.
But I don't know how I can I install Google Chrome to AWS Lambda environment.

Is there anyway to pass Cloudflare protection using @sparticuz/chromium modules?
Please take a look at this URL https://businesssearch.ohiosos.gov/ by protected Cloudflare.

Looking forward to your advice.
Thanks.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
a
```

### Error string

Error: Failed to launch the browser process! /tmp/chromium: /usr/lib/x86_64-linux-gnu/libnss3.so: version `NSS_3.30' not found[BUG]

### Puppeteer version

20

### Node version

18

### Package manager

npm

### Package manager version

9

### Operating system

Linux

**Comment by OrKoN** [comment]
it is possible that sites prevent headless access but it is not a feature that we support.

**Comment by dev1ninja** [comment]
Okay

**Comment by Nate-Asmare** [comment]
I got the "Error: Failed to launch the browser process!" when I was running a web scraper on AWS EC2 instance with an Ubuntu base image. What solved it for me was to install the below dependencies. 

sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget


sudo apt install -y libgbm1
