### ISSUE TITLE
Create video with screenshot

### ISSUE THREAD

**Issue by danhanfry** [puppeteer/puppeteer#1034]
sorry for my English.

I'm trying to make a video, from screenshot, but it's too slow

inside a for, I'm saving the buffer
```
const buffer = await page.screenshot({fullPage: true})
buffers.push(buffer)
```

then created a sequence that I sent to ffmpeg
```
var inStream = streamifier.createReadStream(newBuffer);

ffmpeg(inStream)
.inputOption('-r 30')
.videoCodec('libx264')
.format('mp4')
.on('end', () => console.log('end conversion'))
.on('error', (err, stdout, stderr) => {
  console.error(err);
})
.output('video.mp4')
.run();

```

this works very very slow

Do you know a better approach to achieve this? Thank you

the right way, I think it's start Screencast but I do not know how to apply it

**Comment by aslushnikov** [comment]
This kind of screencast implementation is inevitably slow. Implementing fast screencast would require some protocol work, please upvote the #478 if you need one.
