### ISSUE TITLE
[Bug]: Puppeteer no longer working with strict CSP

### ISSUE THREAD

**Issue by kylon** [puppeteer/puppeteer#10346]
### Bug expectation

with csp enabled:
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' data:; connect-src *">`

puppeteer will throw here: https://github.com/kylon/Sharedown/blob/22fb0e24355bf07712b7ae28eeb962d0c24a40d6/sharedown/loginModules/SimpleUniversity365.js#L28

see also https://github.com/kylon/Sharedown/issues/70

no error in puppeteer 19.8.2

how to reproduce:
[sharedown-puppeteercsp.zip](https://github.com/puppeteer/puppeteer/files/11679649/sharedown-puppeteercsp.zip)

- download, unpack and install modules
- run the app
- go to settings and set these fields as shown
![Screenshot_20230607_180143](https://github.com/puppeteer/puppeteer/assets/3252255/6e57e3eb-98d9-49c8-94e3-720ae715295f)

- start the download

you will get this error
![Screenshot_20230607_174925](https://github.com/puppeteer/puppeteer/assets/3252255/ddeb5723-238f-4b13-9451-f43c07107950)

expected behaviour:
open chrome and write "aa" in email input in login page or get an invalid url error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
see above, cannot attach files here
```

### Error string

function cannot be serialized

### Puppeteer version

20.5.0

### Node version

20.2.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Here are my attempt to reproduce this.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self' data:; connect-src *"
    />
    <title>Document</title>
  </head>
  <body>
    <input type="email" name="email" />
    <input type="password" name="password" />
    <button type="button" onclick="click()">
    <script>
      function click() {
        const button = document.querySelector('[type=button]');
        button.innerHTML = 'Clicked'
      }
    </script>
  </body>
</html>
```
```js
import puppeteer from "puppeteer"; // TS/ESM are all supported.

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const page = await browser.newPage();

  await page.goto("http://127.0.0.1:8080/csp.html");
  await page.waitForSelector('input[type="email"]');
  await page.focus('input[type="email"]');
  await page.evaluate(
    () => (document.querySelector('input[type="email"]').value = "")
  );
  await page.keyboard.type("Email");
  await page.waitForSelector('input[type="password"]');
  await page.focus('input[type="password"]');
  await page.keyboard.type("Password");
  await page.click('[type="button"]');

  await browser.close();
})();
```
This seems to work just fine.
Maybe Electron builder does something to the function in `.evaluate()`, Puppeteer tries to stringify that function. You can read more [here](https://pptr.dev/guides/evaluate-javascript)
You can try to pass it as as string to see if that resolves the issue.
```js
 await puppeteerPage.evaluate(`() => document.querySelector('input[type="email"]').value = ''`);
 ```

**Comment by kylon** [comment]
electron-builder is used to build the package, is it even doing something when running with just `yarn start`? because that is what i am doing, i'm not using the appimage, i'm running from terminal with yarn start and its fine with 19.8.2

anyway, i tried your suggestion, but it still fails csp
