### ISSUE TITLE
[Bug]: Failed to launch the browser proccess

### ISSUE THREAD

**Issue by wojtekLs** [puppeteer/puppeteer#10343]
### Bug expectation

I expected working pupeter.
Got error.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
1. Log in as root (screw php)
2. Install pupeter, reffy
3. `reffy --spec html --module refs`
```

### Error string

the browser proccess

### Puppeteer version

Latest

### Node version

Latest

### Package manager

npm

### Package manager version

apt

### Operating system

Linux

**Comment by wojtekLs** [comment]
@OrKoN updated issue daa

**Comment by OrKoN** [comment]
Sorry, I don't know what reffy and it does not seem to be related to Puppeteer. Please report the issue at reffy first and check out https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux to see if your server is configured properly.

**Comment by wojtekLs** [comment]
@OrKoN `reffy` is schema validation tool. When invoked, it should run `puppeteer` that, in turns, should do the comparison.
Instead of `puppeteer` being run, I see an beforementioned error.
