### ISSUE TITLE
[Feature]:  Add options to the page.bringToFront() to change the default behaviour?

### ISSUE THREAD

**Issue by Himly1** [puppeteer/puppeteer#10354]
### Feature description

I have a Puppeteer project that has to run in non-headless mode.

There are two browser pages in total and I need to switch pages constantly, so I use the `page.bringToFront()` method to achieve this, but one problem is that I can't do anything else with headless=false, because chromium will always pops up when the `page.bringToFront()` executed.

I know simple `headless=true` would fix that problem but in my case I cant use that mode.  

Would it be better if add some options to the `page.bringToFront() ` method like `{popUpOnWindow: boolean}`

**Comment by Lightning00Blade** [comment]
Can you try `headless: "new"`, it should have the same behavior as `headless: false`. 
You can read more about it [here](https://developer.chrome.com/articles/new-headless/).

**Comment by Himly1** [comment]
@Lightning00Blade  Thanks for your reply. Yes you are correct. I need to use other apps while my puppeteer project is running in headless mode. If without `page.bringToFront() ` in my code its find it will not be a problem but in my code I need to switch tabs constantly with the code `page.bringToFront()` that makes the chromium pops up constantly while I am using other apps.  

Ok I'll try the new mode `new`  and thanks.

**Comment by Lightning00Blade** [comment]
Closing as not planned as the behavior is expected from headful browser.
