### ISSUE TITLE
Running Puppeteer on Google App Engine

### ISSUE THREAD

**Issue by arliber** [puppeteer/puppeteer#1036]
Hi,

I thought I'd share all the special requirements to deploy a Puppeteer app on top of Google App Engine

`app.yaml`

```
runtime: nodejs
env: flex

manual_scaling:
  instances: 1
```
This configuration is not what makes it run but it might help anyone starting from scratch.

`package.json`

```
{
   .
   .
   .
  "engines": {
    "node": "8.x"
  },
  "scripts": {
    "preinstall": "apt-get update && apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget",
    "start": "node app.js",
      .
      .
      .
  }
}
```
Two things to note here:

1. I set the node version to 8.x since you'll probably need async/await
2. I use the `preinstall` hook to install some libs

`app.js`

```
async function run() {
  const browser = await puppeteer.launch({
    headless: true,
    timeout: 90000,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
 // YOUR CODE HERE :)
}
``` 
Here I disable the sandbox env. and run in headless mode - otherwise, it didn't work for me.

Hope it helps someone, good luck!

P.S. I think it would be useful to add this to the troubleshooting.md doc

**Comment by ebidel** [comment]
The troubleshoot guide has a section on docker and app engine. It points to the try-puppeteer repo, which runs on gae flex :) 

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

**Comment by aslushnikov** [comment]
Hey @LeonLiber, if you think something's missing in troubleshooting.md, feel free to send a PR!

**Comment by maektwain** [comment]
Thanks you saved my life

**Comment by ghost** [comment]
I am getting `UnhandledPromiseRejectionWarning: Unhandled promise rejection: Error: Navigation Timeout Exceeded: 30000ms exceeded` on goto() function. Any extra specification I need to add for this?
I am getting this only for ASP pages

**Comment by steren** [comment]
You can now use `puppeteer` out of the box on the App Engine standard environment:

`app.yaml`:

```
runtime: nodejs8
instance_class: F4
```

And then simply `npm install puppeteer`

In your app, you need to start your browser with this flag:
```
const browser = await puppeteer.launch({
  args: ['--no-sandbox']
});
```

Here is [a full sample](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/headless-chrome)

And here is the [official doc](https://cloud.google.com/appengine/docs/standard/nodejs/using-headless-chrome-with-puppeteer)

**Comment by gijo-varghese** [comment]
@steren is it possible to run puppeteer in GAE Flex?

**Comment by steren** [comment]
I do not think the Node.ja runtime for Flex contains the necessary package to run headless chrome yet.
However, Flex has `runtime: custom` which allows you to bring your own Dockerfile, which would allow you to do so.

**Comment by ebidel** [comment]
@gijo-varghese , https://github.com/ebidel/try-puppeteer/blob/master/backend/app.yaml uses `runtime: custom` and `env: flex`.

**Comment by srjefers** [comment]
It works for me but I just used this code into me _app.yaml_ file
`runtime: nodejs10`

`manual_scaling:`
`  instances: 1`

and this line maybe was the most important thing, into the `package.json`
`"preinstall": "apt-get update && apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget",`

**Comment by giulianobr** [comment]
> You can now use `puppeteer` out of the box on the App Engine standard environment:
> 
> `app.yaml`:
> 
> ```
> runtime: nodejs8
> instance_class: F4
> ```
> 
> And then simply `npm install puppeteer`
> 
> In your app, you need to start your browser with this flag:
> 
> ```
> const browser = await puppeteer.launch({
>   args: ['--no-sandbox']
> });
> ```
> 
> Here is [a full sample](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/headless-chrome)
> 
> And here is the [official doc](https://cloud.google.com/appengine/docs/standard/nodejs/using-headless-chrome-with-puppeteer)

Hi @steren , what's happens on this examples? All info about how to run puppeteer on App Engine gone! There's links on Google Search but no more documentation on GCP pages.

**Comment by paulpierre** [comment]
I was not able to find documentation on running the python port Pyppeteer on Google App Engine Flex so I thought I would share the solution here:

[https://medium.com/@paulpierre/how-to-run-pyppeteer-on-google-app-engine-flex-or-how-i-lost-it-trying-701b09fadf99](https://medium.com/@paulpierre/how-to-run-pyppeteer-on-google-app-engine-flex-or-how-i-lost-it-trying-701b09fadf99)

**Comment by allanlw** [comment]
Examples were removed in this PR: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1461 see discussion here: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/issues/1395#issuecomment-527530506

**Comment by babyrusa** [comment]
I'm running in Flex env and facing similar issue with @ghost above where puppeteer could start (after adding preinstall) but nothing happens after that (it seems like it's freezing/stuck). I'm considering moving to Standard env but just want to post to see if anyone faces similar issue.

**Comment by slowtick** [comment]
I were able to get puppeteer working in app engine standard by having;

1. instance with more cpu/mem in `app.yaml`
```yaml
runtime: nodejs18
service: my-web-crawler

instance_class: F4_1G
```
2. install chromium to /workspace/puppeteer and point puppeteer cacheDirectory to it via `package.json`
```jsonc
{
//...
scripts: {
    // build and others
    "gcp-build": "npm run build && npx @puppeteer/browsers install chromium --path /workspace/puppeteer"
},
"puppeteer": {
    "cacheDirectory": "/workspace/puppeteer"
  }
}
```
3. disable all sandboxes via args
```typescript
const browser = await puppeteer.launch({
  headless: 'new', 
  args: ['--no-sandbox', '--disable-setuid-sandbox'],
});
```

**Comment by korsour** [comment]
hey @slowtick, I'm still getting the following error (actually, the same as before) with your config:

```
This can occur if either
1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
```

could you confirm that your approach still works or maybe there are some other tweaks that need to be done?

**Comment by hverlind** [comment]
> could you confirm that your approach still works or maybe there are some other tweaks that need to be done?

@korsour I can confirm that I was able to get puppeteer running on app engine standard using the above instructions by @slowtick with minor tweaks because you (and me) seem to be using a later version of puppeteer (e.g. your error message talks about `install chrome` while the instructions have `install chromium`). 

Also, it may be more convenient to use a dedicated config file with a relative path and avoid using an absolute path like `/workspace/puppeteer` which may be different when running things locally (this is also the approach recommended in the [Running Puppeteer on Google App Engine](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-google-app-engine) troubleshooting guidelines).

Putting it all together:
1. `app.yaml`
```yaml
runtime: nodejs18
instance_class: F4_1G
```
2. `.puppeteerrc.cjs`
```js
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, 'node_modules', '.puppeteer_cache'),
};
```
3. `package.json`
```json
"scripts": {
  "gcp-build": "npm run build && npx puppeteer browsers install chrome",
},
"dependencies": {
  "puppeteer": "^22.2.0",
}
```
4. New syntax
```js
const browser = await puppeteer.launch({
  headless: true,
  args: ['--no-sandbox'],
})
```
