### ISSUE TITLE
[Bug]: Missing API calls through puppeteer

### ISSUE THREAD

**Issue by kaleaniket-official** [puppeteer/puppeteer#10368]
### Bug expectation

I have been facing one issue with puppeteer.
I am trying to click on one of the option on the page, that redirects to another page.
Once I click on the option manually on the site, there a one API call (along with few other API calls)**, /authorize** , which creates all the session related data/cookies and then the page redirects to the expected page.
 Problem here is its:
1)  working when  clicked manually
2) working when  clicked via puppeteer automation using **puppeteer.launch({channel: 'chrome'}).**
3) **Not working with via puppeteer automation using puppeteer.connect(browserlessIoConfig).**

**we need to get the 3rd option working**

**Observation:**
I have intercepted all the requests that happen after the click is done and observed that the **/authorize** API call is missing in case of puppeteer.connect() but present and working successfully incase of puppeteer.launch().

Am I missing out on something? Any help would be appreciated.

Thanks in advance.

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
.
```

### Error string

.

### Puppeteer configuration

```TypeScript
Using puppeteer-core V16.1.x and above
```

### Puppeteer version

V16.1.x

### Node version

v16.3.0

### Package manager

yarn

### Package manager version

3.3.0

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
Could you please provide a way to reproduce the issue? 
A page that is happening or a repo with the issue you are facing.
