### ISSUE TITLE
[Bug]: waitForNetworkIdle Timeout cleared

### ISSUE THREAD

**Issue by pedrobruneli** [puppeteer/puppeteer#10385]
### Bug expectation

I expect to wait for network idle before making the next move. But when i call waitForNetworkIdle twice, its return Timeout cleared

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
private async clickEnterButton() {
    this.logger('Clicando em entrar')
    await this.page.waitForSelector('#submit-button')
    await this.page.click('#submit-button')
    await this.page.waitForNetworkIdle()
}
```

### Error string

Error: Timeout cleared

### Puppeteer version

20.7.1

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Please provide a test site: if the network never becomes idle on your site, waitForNetworkIdle will always time out.
