### ISSUE TITLE
Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event' in Page.select()

### ISSUE THREAD

**Issue by rudiedirkx** [puppeteer/puppeteer#1039]
* Puppeteer version: 0.12.0
* Platform / OS version: Ubuntu 16.04.3

When I do:

```
page.select('[name="resource_id"]', '25');
```

I get an error:

```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
```

If I comment both `dispatchEvent` lines in `select()`, I get no error. Both fail.

The element exists and is a `<select>` and the selection works. Only the event dispatching does not work.

**Comment by aslushnikov** [comment]
@rudiedirkx do you have a code snippet so that I can repro this?

**Comment by rudiedirkx** [comment]
It's https://github.com/rudiedirkx/puppeteer-demo/blob/94d078af7c3c2ba60afb83c0642d756ec89e6de8/br.js#L82 but it's really only the one line: the `page.select(...)`

**Comment by aslushnikov** [comment]
@rudiedirkx any chance you can share the URL that causes this bug?

**Comment by rudiedirkx** [comment]
No, but this is the relevant HTML:

```
<form method="post" action="/blockreservations/insert" autocomplete="off" onsubmit="return postForm(this, OorA, true)">
	<table class="oneBorder">
		<tbody>
			<tr class="tblUpTitle">
				<th colspan="2">Blokreservering maken</th>
			</tr>
			<tr>
				<td class="tblTitle" width="250">Baan</td>
				<td><select name="resource_id" onchange="checkFormValues(this.form);"><option value="">--</option><option value="2113">Lane 1 (30 min)</option><option value="24">Squash 3 (EMS) (15 min)</option><option value="25">Squash 4 (15 min)</option><option value="26">Squash 5 (15 min)</option><option value="27">Squash 6 (15 min)</option></select></td>
			</tr>
			<tr>
				<td class="tblTitle">Dag</td>
				<td><select name="on_day" onchange="checkFormValues(this.form);"><option value="">--</option><option value="1">Maandag</option><option value="2">Dinsdag</option><option value="3">Woensdag</option><option value="4">Donderdag</option><option value="5">Vrijdag</option><option value="6">Zaterdag</option><option value="0">Zondag</option></select></td>
			</tr>
			<tr>
				<td class="tblTitle">Begintijd</td>
				<td><input name="start_time" class="time replace-with-select" /></td>
			</tr>
... etc ...
```

Maybe the `onchange` ? That's what I'm trying to trigger. Works perfectly in Real Chrome.

**Comment by rudiedirkx** [comment]
Any idea what's happening?

`Page.select()` does a

    element.dispatchEvent(new Event('input', { 'bubbles': true }));

which seems like an `Event` in parameter 1.

Can I try another version or something?

**Comment by aslushnikov** [comment]
@rudiedirkx I can't reproduce this; without a repro this is not actionable. If you can come up with a sharable snippet, I'd be happy to look into this.

cc @alixaxel who implemented original `Page.select`.

**Comment by alixaxel** [comment]
@rudiedirkx I suspect the culprit is the `checkFormValues` function on the `onchange` trigger.

Could you share that function? Along with the HTML doctype of the page?

**Comment by rudiedirkx** [comment]
If I remove the `onchange` attribute, or empty the callback, the exact same happens, so that can't be it.

If I remove the entire inline script block, it still happens.

If I remove ALL JS, it doesn't happen. There's no callback to be fired, but the Puppeteer part works..... Is my JS too hacky? It's possible.

**Comment by rudiedirkx** [comment]
Ooooooh, I might know what it is, but that's unexpected (for me, for you it's obvious). My very old JS lib overrides `window.Event`, so it's not a native `Event` anymore. This is unexpected for me, and obvious for you, because I didn't know the stringified version of the `this.$eval` callback function is called inside the page's context, not in Puppeteer/node context.

    element.dispatchEvent(new Event('input', { 'bubbles': true }));

That's browser JS, not NodeJS.... Ah.

I now see I can reproduce this exact error in Real Chrome:

```
$0.dispatchEvent(new Event('input', { 'bubbles': true }));

VM1042:1 Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at <anonymous>:1:4
(anonymous) @ VM1042:1
```

So, yes, my JS is definitely too hacky. Sorry!

**Comment by yaakovyitzchak** [comment]
Hey guys, I have a a question regarding this:

I'm trying to attempt to get the direct link for a google drive video. To do that, I first navigate to the drive embed-video URL, then click on the play button (There are many of them), then wait for the iframe containing a video element to appear, then get the video element in the iframe, then I'm trying to get the source of the video, but it appears to be null, so I tried getting the outerHTML, and this is what I got in the console:


    <video tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" style="width: 800px; height: 450px; left: 0px; top: 75px;"></video>

Seemingly it hasn't been loaded yet, but I'm not sure what event to wait for, I waited for a timeout of 15 seconds but still got the same result, here's my code:

    var puppeteer = require("puppeteer");
    
        (async() => {
            var browser = await puppeteer.launch();
            console.log("Got browser", browser);
            var page = await browser.newPage();
            console.log(page,"got page");
         
            await page.goto("https://docs.google.com/file/d/1Cyuh41yNfYZU_zL-MHLf_EPJCYnlT7oJ/preview?enablejsapi=1&playerapiid=player4");
            console.log("went to page..");
            
          
          
            var clickEl = ".ndfHFb-c4YZDc-aTv5jf-bVEB4e-RJLb9c";
            var newClickID = ".ndfHFb-c4YZDc-aTv5jf-NziyQe-LgbsSe";
            var clicker = await page.waitForSelector(newClickID);
            console.log(clicker,"got clicker");
        
            await page.click(clickEl);
            console.log("clicked")
        
            var frame = await page.waitForSelector("iframe[id=drive-viewer-video-player-object-0]");
            console.log(frame, "got video frame");
            
            
        
            
            var cf = await frame.contentFrame();
            console.log(cf, "got content frame");
            await cf.waitFor(15000);
            var video = await cf.$("video");
            var src = await cf.evaluate(
                v => v.outerHTML,
                video
            );
            console.log("$$###VIDEO SOURCE::", src);
            await browser.close();
        })();

Any ideas, am I doing something wron? why is the "src" attribute not showing up on the video element?
  [1]: https://github.com/GoogleChrome/puppeteer/blob/v1.13.0/docs/api.md#elementhandleselector-1
