### ISSUE TITLE
[Bug]: waitForNetworkIdle: Error: Timeout cleared

### ISSUE THREAD

**Issue by Pilaton** [puppeteer/puppeteer#10398]
### Bug expectation

After updating puppeteer, waitForNetworkIdle started throwing Timeout cleared error in all my apps and projects.
It looks like the error does not appear on every waitForNetworkIdle.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

async function demoFunc(page) {
  await page.goto('https://jsonplaceholder.typicode.com/');
  console.log('1');

  await page.waitForNetworkIdle({ idleTime: 3000 }); // OK
  console.log('2');

  await page.reload(); // reload or click or other...
  console.log('3');

  await page.waitForNetworkIdle({ idleTime: 3000 }); // ERROR
  console.log('4');
}

async function run() {
  const browser = await puppeteer.launch({
    headless: 'new',
  });
  const page = await browser.newPage();
  await demoFunc(page);
  await browser.close();
}

run().catch(console.error);
```

### Error string

Error: Timeout cleared

### Puppeteer version

20.7.2

### Node version

v20.3.0

### Package manager

pnpm

### Package manager version

8.6.2

### Operating system

macOS

**Comment by Pilaton** [comment]
Latest working version of puppeteer without bug v20.5.0

**Comment by edhale3** [comment]
Experiencing the same thing on second call to waitForNetworkIdle()
