### ISSUE TITLE
[Bug]: Error while trying to launch the browser

### ISSUE THREAD

**Issue by Jelosus2** [puppeteer/puppeteer#10406]
### Bug expectation

I expected to run it smoothly since it worked on my local machine, but when i uploaded it to my Pterodactyl panel in my virtual machine it failed saying that the browser process couldn't be started.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

async function loadBrowser() {
  const browser = await puppeteer.launch({
    headless: 'new'
  });
  const page = await browser.newPage();
  await page.goto('https://mysite.com');
};

loadBrowser();
```

### Error string

Failed to launch the browser process! /home/container/.cache/puppeteer/chrome/linux-114.0.5735.133/chrome-linux64/chrome: 1: Syntax error: "(" unexpected

### Puppeteer version

20.7.2

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.7.1

### Operating system

Linux

**Comment by Jelosus2** [comment]
This code worked on my local machine, but not in my virtual machine with Pterodactyl Panel

**Comment by OrKoN** [comment]
Please make sure that your server has all dependencies and the right Chrome version downloaded: on `npm i puppeteer` Puppeteer downloads the binary for the current platform and if you just copy the binary to a different platform it might not work. Also see https://pptr.dev/troubleshooting
