### ISSUE TITLE
[Bug]: Failed to launch the browser process! syntax error: "(" unexpected on ARM Linux

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#10404]

**Comment by chrxmvtik** [comment]
Hi @caden66, did you manage to resolve this issue? Same thing happened to me recently after upgrading puppeteer to the latest version. Tried multiple possible solutions, doing clean-install, manually installing chrome, but still this issue persist.

> node v20.2.0
> /root/.cache/puppeteer/chrome/linux-114.0.5735.133/chrome-linux64/chrome: 1: Syntax error: "(" unexpected

**Comment by caden66** [comment]
If you create an Issue for it maybe, they will add future support.
