### ISSUE TITLE
[Bug]: npm package JS missing sources and over-transpiled?

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#10403]
### Bug expectation

I needed to debug some behavior between DevTools frontend, the lighthouse panel, the Puppeteer connectionservice and then CDP connection mgmt within pptr. (Again.. we're in the devtools frontend)

Bug 1: I expected sourcemaps to work for stepping through pptr code. It didn't. The NPM package does have sourcemaps, but not original sources (either as files or `sourcesContent`). So.. instead you just see an awkward 404 page in Sources tab. 
I can repro the same problem just debugging w/ node via Chrome DevTools.

<img width="1090" alt="image" src="https://github.com/puppeteer/puppeteer/assets/39191/27191f2b-99fb-4f0d-88dc-b4413a036584">

FWIW if I just put the .ts sources files from the repo in the correct file location (my devtools out/ at least), this worked. So I suspect the fix for the NPM package is easy enough as including them in the publish.

"Bug" 2: I then turn off sourcemaps in devtools. I can see the JS sources now.. but they're overtranspiled IMO. In particular, all the private fields have `__classPrivateFieldGet` invocations.. Those make it so messy its very hard to read the code enough to follow it.

<img width="800" alt="image" src="https://github.com/puppeteer/puppeteer/assets/39191/45122dd2-3d5b-4282-b1ee-13aeb7d616e7">

I attempted to fix this by playing with the typescript configuration but failed. I don't know your node support policy but private class fields are [pretty green](https://node.green/) at this point. (They're definitely solid in browsers)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```js
const puppeteer = require('puppeteer');
console.log(puppeteer); throw new Error('😩');
```

### Error string

😩

### But actually.. a repro: 

For the sourcemaps issue...

create a new folder. `npm init -y`. Copy `examples/search.js` into there. `node --inspect-brk search.js`  set a breakpoint on the `.launch()` line. Step in there.

<img width="472" alt="image" src="https://github.com/puppeteer/puppeteer/assets/39191/b2a3813a-f52f-4f52-8718-09eb2d4d6ad2">

### Puppeteer version

20.7.2

### Node version

19.6.0

### Package manager

npm

### Package manager version

9.4.0

### Operating system

macOS

**Comment by OrKoN** [comment]
"over-transpiled" sounds like https://github.com/puppeteer/puppeteer/issues/10170 ? (e.g., https://github.com/puppeteer/puppeteer/issues/10170#issuecomment-1547519545)
