### ISSUE TITLE
[Bug]: Image detection issue with Next.js Image component

### ISSUE THREAD

**Issue by ProchaLu** [puppeteer/puppeteer#10418]
### Bug expectation

We have encountered a bug in Puppeteer where it is unable to find and detect different image formats when using the Next.js Image component. Our Puppeteer test is designed to check the existence and visibility of images on multiple pages. However, when using certain image formats, Puppeteer fails to locate the images after the new page loads.

Different image formats: 
1. Unoptimized JPEG
2. Optimized JPG 
3. Optimized AVIF
4. Optimized JPG with `unoptimized` Image props
5. Optimized AVIF with `unoptimized` Image props

To reproduce this issue, I have created a [Next.js application](https://next-image-puppeteer.vercel.app/) and a test case that verifies the existence and visibility of different image formats on multiple pages with the Next.js Image component. On the initial page load, the test checks various images on the landing page. Additionally, I have implemented different pages containing a single image format, to ensure proper functionality of route changes and image checks. The following function is used to determine if an image is loaded:
```js
async function isImageLoaded(imageSelector, page) {
  return await page.evaluate((selector) => {
    const image = document.querySelector(selector);
    return image && image.complete && image.naturalWidth > 0;
  }, imageSelector);
}
```
To perform a click and wait for navigation, the following function is utilized:
```js
async function clickAndWaitForNavigation(selector, page) {
  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click(selector),
  ]);
}
```
The outcome of the repro test is as follows:
```
[data-test-id="unoptimized-jpeg"], Loaded? true
[data-test-id="optimized-jpg"], Loaded? true
[data-test-id="optimized-avif"], Loaded? true
[data-test-id="unoptimized-props-avif"], Loaded? true
[data-test-id="unoptimized-props-jpg"], Loaded? true
1. page, unoptimized-jpeg:  true
6. page, optimized-jpg:  false
7. page, optimized-avif:  false
8. page, optimized jpg with unoptimized props :  true
9. page, optimized avif with unoptimized props :  true
```
From the results, Puppeteer is unable to detect the presence of some images, resulting in a test failure. When checking the images on different pages in a different order, other images fail to be detected. However, upon checking the pages with the images a second time, all the images become visible.

While examining the network tab, we observed that there is minimal variation in the network activity regardless of the clicked page. Puppeteer should wait until `networkIdle0`, but it is possible that Puppeteer does not wait for the network to be idle for the required 500ms?
![Screenshot 2023-06-19 at 15 16 34](https://github.com/puppeteer/puppeteer/assets/80746311/94738171-4fbb-4405-8a71-d629dcb147de)

To address this issue, we attempted a workaround by using `await page.waitForNetworkIdle()` after the `clickAndWaitForNavigation` function, which successfully resolved the issue in our production test. However, in the reproduction test, using this workaround resulted in a failure with the error message: `Timeout cleared.`
```
deferred.reject(new Error('Timeout cleared'));
                                ^
Error: Timeout cleared
```
Alternatively, I tried a workaround where the image is checked multiple times, with a 500ms timeout between each check. The test can be implemented as follows:
```js
async function isImageLoadedWithRetries(imageSelector, page) {
  let retries = 0;
  let imageLoaded = false;

  while (retries < 3 && !imageLoaded) {
    imageLoaded = await isImageLoaded(imageSelector, page);
    if (!imageLoaded) {
      await page.waitForTimeout(500);
      retries++;
    }
  }
  return imageLoaded;
}
``` 

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import { launch } from 'puppeteer';

async function isImageLoaded(imageSelector, page) {
  return await page.evaluate((selector) => {
    const image = document.querySelector(selector);
    return image && image.complete && image.naturalWidth > 0;
  }, imageSelector);
}

async function clickAndWaitForNavigation(selector, page) {
  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click(selector),
  ]);
}

(async () => {
  const browser = await launch();
  const page = await browser.newPage();
  await page.goto('https://next-image-puppeteer.vercel.app/');

  const imageSelectors = [
    '[data-test-id="unoptimized-jpeg"]',
    '[data-test-id="optimized-jpg"]',
    '[data-test-id="optimized-avif"]',
    '[data-test-id="unoptimized-props-avif"]',
    '[data-test-id="unoptimized-props-jpg"]',
  ];

  // Check if images are loaded on initial page load
  for (const selector of imageSelectors) {
    const isLoaded = await isImageLoaded(selector, page);
    console.log(`${selector}, Loaded? ${isLoaded}`);
  }

  // Navigate to each image page and check if the image has loaded
  await clickAndWaitForNavigation(
    '[data-test-id="unoptimized-jpeg-link"]',
    page,
  );

  const image1 = await isImageLoaded('[data-test-id="unoptimized-jpeg"]', page);

  console.log('1. page, unoptimized-jpeg: ', image1);

  await clickAndWaitForNavigation('[data-test-id="optimized-jpg-link"]', page);

  const image2 = await isImageLoaded('[data-test-id="optimized-jpg"]', page);

  console.log('2. page, optimized-jpg: ', image2);

  await clickAndWaitForNavigation('[data-test-id="optimized-avif-link"]', page);

  const image3 = await isImageLoaded('[data-test-id="optimized-avif"]', page);

  console.log('3. page, optimized-avif: ', image3);

  await clickAndWaitForNavigation(
    '[data-test-id="unoptimized-props-jpg-link"]',
    page,
  );

  const image4 = await isImageLoaded(
    '[data-test-id="unoptimized-props-jpg"]',
    page,
  );

  console.log('4. page, optimized jpg with unoptimized props : ', image4);

  await clickAndWaitForNavigation(
    '[data-test-id="unoptimized-props-avif-link"]',
    page,
  );

  const image5 = await isImageLoaded(
    '[data-test-id="unoptimized-props-avif"]',
    page,
  );

  console.log('5. page, optimized avif with unoptimized props : ', image5);

  await browser.close();
})();
```

### Error string

no error

### Puppeteer version

20.7.2

### Node version

v18.15.0

### Package manager

pnpm

### Package manager version

8.6.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Possibly the same as https://github.com/puppeteer/puppeteer/issues/10398 @Lightning00Blade PTAL

**Comment by ProchaLu** [comment]
> I assume what happens here is that the image is perhaps loaded from cache so the network is idle but the image is not loaded yet. A more robust version would be the following, I think:
> 
> ```
> async function isImageLoaded(imageSelector, page) {
>   await page.waitForFunction((selector) => {
>     const image = document.querySelector(selector);
>     return !!(image && image.complete && image.naturalWidth > 0);
>   }, undefined, imageSelector);
>   return true;
> }
> ```

Thx, it seems like this is correct way, will test it a couple of times!

**Comment by OrKoN** [comment]
@ProchaLu I assume the issue is solved? let me know if you think there is a bug somewhere here. (apart from the timeout cleared)

**Comment by ProchaLu** [comment]
As mentioned by OrKoN, you can enhance the image check's robustness by using the `page.waitForFunction` method. In this case, you will need to provide a string as the `imageSelector`, as shown in the example below:
```js
export async function isImageLoaded(
  imageSelector: string,
  page: Page,
): Promise<boolean> {
  await page.waitForFunction((selector) => {
    const image = document.querySelector(selector) as HTMLImageElement;
    return !!(image.complete && image.naturalWidth > 0);
  }, undefined, imageSelector);

  return true;
}
```

When using an `imageElementHandle`, I still use the function posted below. With the `page.waitForSelector()` method I ensured that the selector was visible after the route change. 

```js
await Promise.all([
  page.waitForNavigation({ waitUntil: 'networkidle0' }),
  page.click(selector),
]);
await page.waitForSelector('img');
```

After updating to Next.js `13.4.10`, the image check is no longer flaky. Something in Next.js changed between versions `13.4.4` and `13.4.10` that stabilized the checks.
Here is the function using the `imageElementHandle`, which takes advantage of `evaluate` to get the `naturalWidth` property of the image DOM element:

```js
export async function isImageLoaded(
  imageElementHandle: ElementHandle<HTMLImageElement>,
): Promise<boolean> {
  const naturalWidth = await imageElementHandle.evaluate(
    (imageDomElement) => imageDomElement.naturalWidth
  );

  return naturalWidth > 0;
}
```

**Comment by ProchaLu** [comment]
Despite using `waitUntil: networkIdle0`, tests continued to encounter flakiness in Next.js 14 due to unloaded images.

![next-image-component](https://github.com/upleveled/courses/assets/80746311/55363471-2f9e-438f-9c66-2e564687fc26)

While `networkIdle0` ensures initial HTML is loaded and the network is quiet for 500ms, it doesn't account for subsequent image requests. These later requests, even after the initial network idle period, can cause tests to proceed before images are fully loaded, leading to false errors.

To address this, instead of a single evaluation, the function iterates over a predefined interval, waiting for the network to be idle, and validating the existence of the image. This function checks the image for a maximum of 3000ms, with intervals of 500ms between each check. 

```ts
export async function isImageLoaded(
  page: Page,
  imageElementHandle: ElementHandle<HTMLImageElement>,
) {
  for (let totalIdleTime = 0; totalIdleTime < 3000; totalIdleTime += 500) {
    // Don't wait for timeout the first time
    if (totalIdleTime > 0) await page.waitForNetworkIdle({ idleTime: 500 });

    if (
      (await imageElementHandle.evaluate(
        (imageDomElement) => imageDomElement.naturalWidth,
      )) > 0
    ) {
      return true;
    }
  }

  return false;
}
```
