### ISSUE TITLE
[Bug]: Interactions between already open page and new navigation.

### ISSUE THREAD

**Issue by mattzeunert** [puppeteer/puppeteer#10419]
### Bug expectation

I call `goto` on an existing page object and the page loads as expected. However instead of returning from `goto` I then get an error: `Navigation timeout of 30000 ms exceeded`.

I've not been able to reproduce this consistently, and when I wait longer before the navigation that fixes it.

### What I've found happens so far:

```
Initial loader id: D2BAA321FB6F6F054DF1C7581B410956
Page.navigate returns a new loader id: CE76EFD32A1411A4ACDE53F9C62B8075
```

I think LifecycleWatcher then [waits for the loader id to change](https://github.com/puppeteer/puppeteer/blob/d1ffad059ae66104842b92dc814d362c123b9646/packages/puppeteer-core/src/common/LifecycleWatcher.ts#LL272C1-L274C6), but that never happens. Both ids are `D2BAA321FB6F6F054DF1C7581B410956`

```
    if (this.#swapped || this.#frame._loaderId !== this.#initialLoaderId) {
      this.#newDocumentNavigationDeferred.resolve(undefined);
    }
```

### Log suggests other page is still loading in the background

I don't fully understand how the frame loader id updates. If two navigations are in progress, could the previous navigation overwrite the loader id and reset it?

```
{"method":"Page.navigate","params":{"url":"http://localhost:8000/account","frameId":"BEFC40771FE2202D3B44652BF8134C29"},"id":147,"sessionId":"894EA702B7497006590B868ECF7AAEB2"}
// Data received for HTML request from the first navigation
{"method":"Network.dataReceived","params":{"requestId":"D2BAA321FB6F6F054DF1C7581B410956","timestamp":605126.669331,"dataLength":24303,"encodedDataLength":0},"sessionId":"894EA702B7497006590B868ECF7AAEB2"}
// Other resources being loaded in the first navigation
{"method":"Network.requestWillBeSent", ...}
## DOMContentLoaded for the first navigation
{"method":"Page.lifecycleEvent","params":{"frameId":"BEFC40771FE2202D3B44652BF8134C29","loaderId":"D2BAA321FB6F6F054DF1C7581B410956","name":"DOMContentLoaded","timestamp":605126.680005},"sessionId":"894EA702B7497006590B868ECF7AAEB2"}
## Page.navigate response
{"id":147,"result":{"frameId":"BEFC40771FE2202D3B44652BF8134C29","loaderId":"CE76EFD32A1411A4ACDE53F9C62B8075"},"sessionId":"894EA702B7497006590B868ECF7AAEB2"}
## New page DOMContentLoaded
{"method":"Page.lifecycleEvent","params":{"frameId":"BEFC40771FE2202D3B44652BF8134C29","loaderId":"CE76EFD32A1411A4ACDE53F9C62B8075","name":"DOMContentLoaded","timestamp":605126.835797},"sessionId":"894EA702B7497006590B868ECF7AAEB2"}
// New page first paint
{"method":"Page.lifecycleEvent","params":{"frameId":"BEFC40771FE2202D3B44652BF8134C29","loaderId":"CE76EFD32A1411A4ACDE53F9C62B8075","name":"firstPaint","timestamp":605126.848885},"sessionId":"894EA702B7497006590B868ECF7AAEB2"}
## Navigation within document on new page
{"method":"Page.navigatedWithinDocument","params":{"frameId":"BEFC40771FE2202D3B44652BF8134C29","url":"http://localhost:8000/account"},"sessionId":"894EA702B7497006590B868ECF7AAEB2"
## _LifecycleWatcher_navigated log - still referencing old loader
_navigated loader ids D2BAA321FB6F6F054DF1C7581B410956 D2BAA321FB6F6F054DF1C7581B410956
```

## Questions

Do you know if the navigation could somehow be confused by the other navigation that's taking place after clicking in the UI?

Should `#frames` in FrameTree update after the navigation? How does it obtain the new loader id? I could try and look into it more to see why that's not happening in this case.

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// Wasn't able to find a reproducible example, but this is the high-level code

await page.goto(baseUrl + "/project");
await page.click("#nav-link");
expect(page.url()).toContain("/newurl");
await page.goto(baseUrl + "/account");
```

### Error string

Navigation timeout of 30000 ms exceeded

### Puppeteer version

20.7.2

### Node version

v19.8.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

macOS

**Comment by OrKoN** [comment]
According to the CDP the navigation is within the same document (Page.navigatedWithinDocument) so `newDocumentNavigationDeferred` and the loaderId check is not related to it. Could you provide a minimal example that demonstrates the issue?

**Comment by OrKoN** [comment]
For the same document navigation this need to fire: https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/LifecycleWatcher.ts#L270 Although I expect it might be flaky if both click and the last goto trigger the navigation. You might want to try the following:

```
await Promise.all([
  page.waitForNavigation(),
  page.click("#nav-link")
])
```
