### ISSUE TITLE
[Bug]: using puppeteer library the pdf created locally but after deployment the api throw an error

### ISSUE THREAD

**Issue by MudabbarHussain** [puppeteer/puppeteer#10413]
### Bug expectation

 using the puppeteer library the pdf was created locally but after deployment, the API throw an error.
<img width="578" alt="PPTR" src="https://github.com/puppeteer/puppeteer/assets/59447487/4230a622-f671-44b4-af15-10ea29f75b98">

### Bug behavior

- [ ] Flaky
- [X] PDF

### Minimal, reproducible example

```TypeScript
async generatePdf(html: string) {

    const browser = await puppeteer.launch({
      args: [
        // comment line arguments when deploying 
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
      ],
    });
    const page = await browser.newPage();
    await page.setContent(html);
    const pdf = await page.pdf({
      format: 'A4', // Specify the desired page format
      width: '8.5in', // Set the width
    });
    await browser.close();
    return pdf;
  }
```

### Error string

Could not find Chrome (ver. 114.0.5735.133). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npm install`) or\n 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration."

### Puppeteer version

"^20.7.2"

### Node version

"^20.7.2"

### Package manager

yarn

### Package manager version

3

### Operating system

Windows

**Comment by OrKoN** [comment]
Please make sure that your server has the browser binary downloaded: https://pptr.dev/guides/configuration#changing-the-default-cache-directory

**Comment by AdamLuck98** [comment]
@MudabbarHussain were you able to fix the issue? I am getting the same issue on the Vercel server I am stuck and have nowhere to go?

**Comment by Barenyakumar** [comment]
Were you able to solve the issue?
