### ISSUE TITLE
[Bug]: @puppeteer/browsers won't install chromedriver for current revision (114.0.5735.133)

### ISSUE THREAD

**Issue by andyMrtnzP** [puppeteer/puppeteer#10425]
### Bug expectation

This is related to https://github.com/puppeteer/puppeteer/issues/10388

Expected: Chromedriver for `114.0.5735.133` to be installed
Received: An 404 error, implying the servers don't have that version hosted

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import path from "path";
import os from "os";

import { install, Browser, BrowserPlatform } from "@puppeteer/browsers";
import { PUPPETEER_REVISIONS } from "puppeteer-core/lib/cjs/puppeteer/revisions.js";

const chromedriver = await install({
  browser: Browser.CHROMEDRIVER,
  buildId: PUPPETEER_REVISIONS.chrome, //currently 114.0.5735.133,
  cacheDir: path.join(os.homedir(), ".puppeteer-cache"),
  platform: BrowserPlatform.WIN64,
});

console.log(chromedriver.path);
```

### Error string

`Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.133/win64/chromedriver-win64.zip`

### Puppeteer version

20.7.2

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.7.1

### Operating system

Windows

**Comment by OrKoN** [comment]
chromedriver is only available from 115.0.5763.0 (https://github.com/GoogleChromeLabs/chrome-for-testing/issues/22)
