### ISSUE TITLE
[Bug]: screenshot is broken on github action.

### ISSUE THREAD

**Issue by angler99** [puppeteer/puppeteer#10428]
### Bug expectation

Using the puppeeteer to compare the image between origin and new one.

using the selector. 

env is github action.
take a screen shot and compare it with origin images.
using the puppeteer version : 19.1.0

    `await puppeteer.launch({
    args: [
    '--disable-gpu',
    '--disable-gpu-compositing',
    '--disable-gpu-rasterization',
    '--single-process',
    '--ignore-certifacate-errors',
    '--start-maximized',
    '--no-sandbox',
    '--enable-features=NetworkService'
    ],
      defaultviewport: null,
      headless: true,
      isMobile: true
    });`

    `let components = await this.page.$$(selector);

    for(const [index, component] of components.entries()) {

    try {
        await component.screenshot({path: filepath, captureBeyondViewport: false});
    } catch (e) {
  
    }
}`

there are 30 components. and it take a screenshot using loop.
But sometimes the screenshot of component is broken.
it is not expanded fully -> height is short than origin size.
it doesn't draw all items in component etc. -> it have to draw 1,2,3. but it just capture after drawing 1,2. so it doesn't capture 3.

as a result, it take a screenshot before drawing all items in each component.randomly.

all components screen host are captured correctly.
local pc evn, there is no issue.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
`await puppeteer.launch({
    args: [
    '--disable-gpu',
    '--disable-gpu-compositing',
    '--disable-gpu-rasterization',
    '--single-process',
    '--ignore-certifacate-errors',
    '--start-maximized',
    '--no-sandbox',
    '--enable-features=NetworkService'
    ],
      defaultviewport: null,
      headless: true,
      isMobile: true
    });`


    `let components = await this.page.$$(selector);

    for(const [index, component] of components.entries()) {

    try {
        await component.screenshot({path: filepath, captureBeyondViewport: false});
    } catch (e) {
  
    }
}`
```

### Error string

images are broken

### Puppeteer version

19.1.0

### Node version

node:16-browsers

### Package manager

npm

### Package manager version

which package

### Operating system

Linux

**Comment by OrKoN** [comment]
Try using the latest version, and if that does not work, please provide a reproducible minimal example for the issue you are experiencing. The page you are taking the screenshot from is also important as some screenshot options might resize the page. The current issue description does not include enough information to reproduce.
