### ISSUE TITLE
[Bug]: Headless mode 'new' creates foreground window 'Untitled - Chromium'

### ISSUE THREAD

**Issue by iidebyo** [puppeteer/puppeteer#10427]
### Bug expectation

No foreground window to be created.

A foreground window ("the window with which the user is currently working") is created. This window is not visible.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
async function Create () {
  const puppeteer = require('puppeteer')
  const browser = await puppeteer.launch({ headless: 'new' })
  await browser.close()
}
Create()
```

### Error string

no error

### Puppeteer version

20.7.2

### Node version

v18.14.0

### Package manager

npm

### Package manager version

9.4.1

### Operating system

Windows

**Comment by OrKoN** [comment]
@iidebyo could you please post the screenshot of the window that is created?

**Comment by OrKoN** [comment]
Could you describe how do you determine that a window is created?

**Comment by OrKoN** [comment]
Same issue as https://github.com/puppeteer/puppeteer/issues/10246 (tracked upstream in https://crbug.com/1449117)
