### ISSUE TITLE
[Bug]: goto() doesn't read element id in url

### ISSUE THREAD

**Issue by JattMones** [puppeteer/puppeteer#10421]
### Bug expectation

When using a "element id" in a url with `goTo`, the id params seem to be ignored.
```
await page.setViewport(size);
await page.goto(`http://website/endpoint`, {waitUntil: 'networkidle0'});
await page.screenshot({path: `out1.png`, fullPage: true });
await page.goto(`http://website/endpoint#element-id`, {waitUntil: 'networkidle0'});
await page.screenshot({path: `out2.png`, fullPage: false });
```
the element-id I'm referring to is down the page a bit, but the screenshot is taken at the top of the page. Not sure if this is a bug with screenshot or goto. Please let me know if there's another fix or feature that allows we to scroll to the Id and screenshot (although, I would expect putting it in the url to work).

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
await page.setViewport(size);
await page.goto(`http://website/endpoint`, {waitUntil: 'networkidle0'});
await page.screenshot({path: `out1.png`, fullPage: true });
await page.goto(`http://website/endpoint#element-id`, {waitUntil: 'networkidle0'});
await page.screenshot({path: `out2.png`, fullPage: false });
```

### Error string

no error

### Puppeteer version

20.7.2

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by JattMones** [comment]
This is ready for review by a real person that can reproduce the issue

**Comment by OrKoN** [comment]
Could you please provide an example website for reproducing this?

**Comment by OrKoN** [comment]
Seems to be working as expected for me with the following test:

```
import puppeteer from "puppeteer";

const browser = await puppeteer.launch({
  headless: false
});

const page = await browser.newPage();

await page.goto('https://en.wikipedia.org/wiki/North_East_MRT_line', { waitUntil: 'networkidle0' });
await page.screenshot({ path: `out1.png`, fullPage: true });

await page.goto('https://en.wikipedia.org/wiki/North_East_MRT_line#Stations', { waitUntil: 'networkidle0' });
await page.screenshot({ path: `out2.png`, fullPage: false });

await browser.close();
```

Please provide a complete minimal example next time.

[out1](https://github.com/puppeteer/puppeteer/assets/399150/2cead1f3-22ea-44b2-a9c9-be80d5201884)
[out2](https://github.com/puppeteer/puppeteer/assets/399150/053de396-a2bc-4266-9bcf-d7544d036389)

**Comment by JattMones** [comment]
ahh @OrKoN it appears it may only work when headless is set to false.

Thanks for the reply and help! 

(P.S. The website I'm using is currently only available in local dev env, I'll try and supply a fully working example next time)
