### ISSUE TITLE
[Feature]: allow `browsers` to download Firefox Stable/Aurora/ESR in addition to Nightly

### ISSUE THREAD

**Issue by fippo** [puppeteer/puppeteer#10420]
### Feature description

In [this PR](https://github.com/webrtcHacks/adapter/pull/1133) I am trying to remove the dependency on [travis-multirunner](https://github.com/DamonOehlman/travis-multirunner/) but would like to retain the ability to download different FF versions (stable, aurora, esr, maybe dev).

It seems the main obstacle is that the directory structure for FF Nightly is
`https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/{buildId}.{locale}.{platform-specific-stuff}` ([example here](https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/))
while for the other channels the platform and locale come earlier in the path:
`https://archive.mozilla.org/pub/firefox/releases/{buildId}/{platform}/{locale}/<binary>`
[example here](https://archive.mozilla.org/pub/firefox/releases/114.0.1/win64/en-US/)

Would monkeypatching [resolveDownloadUrl](https://github.com/puppeteer/puppeteer/blob/main/packages/browsers/src/browser-data/firefox.ts#L42) to recognize the default nightly baseUrl and call resolveDownloadPath/archive with a different boolean flag be an ok approach?
This would allow "users" to pass a different baseUrl depending on the channel.
The cleaner alternative would be to plumb the channel through (for other browsers as well)

Yet another approach would be the one that [travis-multirunner](https://github.com/nathanoehlman/browser-sleuth/blob/master/lib/firefox.js#LL26C9-L26C120) has taken for a decade and download from 
`'https://download.mozilla.org/?os=' + platform + '&lang=' + lang + '&product=firefox-' + (channel || 'latest');` but I would like less travis-multirunner, not more ;-)

Issue #6894 has some context on switching the default and helpful pointers to download urls

**Comment by OrKoN** [comment]
We want to support this: we need to make use of the channel in https://github.com/puppeteer/puppeteer/blob/main/packages/browsers/src/browser-data/firefox.ts#L69 and also make the download URLs dependent on the channel https://github.com/puppeteer/puppeteer/blob/main/packages/browsers/src/browser-data/firefox.ts#L42

But first we need to find more unique identifiers to use as a buildId. Also, related to https://github.com/puppeteer/puppeteer/issues/10414.
