### ISSUE TITLE
[Bug]: Page.reload() Destroys execution context on certain websites

### ISSUE THREAD

**Issue by Vasile-Peste** [puppeteer/puppeteer#10435]
### Bug expectation
We are trying to visit a webpage, reload it and query a selector.
On certain websites, a "Execution context was destroyed" error is thrown as soon as `$` query selector is used after the page reload.

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import * as Puppeteer from "puppeteer";

const browser = await Puppeteer.launch({
    ignoreHTTPSErrors: true,
    headless: false,
    devtools: true,
    waitForInitialPage: false,
});

const page = await browser.newPage();

await page.goto("https://ilsole24ore.com", {
    waitUntil: "load",
});

await page.reload();

const element = await page.$(".test");

// Error: Execution context was destroyed, most likely because of a navigation.
// Happens for "https://ilsole24ore.com"
// Instead if we try a different websites, like "https://aranzulla.it" it doesn't happen
```

### Error string
Error: Execution context was destroyed, most likely because of a navigation

### Puppeteer version

20.7.3

### Node version

20.3.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

macOS

**Comment by OrKoN** [comment]
minimal repro:

```
import * as puppeteer from "puppeteer";

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto("https://ilsole24ore.com", {
  waitUntil: "load",
});
await page.reload();

const element = await page.$(".test");
```

**Comment by jrandolf** [comment]
If you use `domcontentloaded` instead of `load`, the above script will work, however this is a Puppeteer bug.

The underlying problem here is that the `reload` and `goto` wait on the same events. Some of the events of your `goto` are leaking to your `reload` call because you only wait for the `goto` to `load` your page. This causes `reload` to think it is finished when in reality the events are from the `goto`. This causes a (sort of) race condition.

@OrKoN I think we can solve this by mutexing the navigation. More precisely, we can do something like this in every navigation function:

```ts
declare const mutex: Mutex;

let resolve;
const promise = new Promise(res => resolve = res);
void mutex.run(async () => {
  // Run navigation code
  // Wait for specified event to finish.
  resolve();
  // Wait for remaining events to finish.
});
return promise;
```

 - Create a promise that gets returned to the user and a mutex that waits for a navigation to finish.
 - When a navigat
 - `resolve()` that event.
 - After resolving, contin

**Comment by jrandolf** [comment]
> I am not sure that would work as we also have networkidle events on the list of supported event that might take a long time to occur (possibly infinitely)

Actually the only event that may require waiting is `domcontentloaded`. Once `domcontentloaded` happens, we can perform other navigations.

> Why are we trying to do something on the destroyed context here?

Because the reload finishes prematurely (see my above comment), the `page.$` executes immediately before it has a chance the page has had a change to change it's execution context.

**Comment by OrKoN** [comment]
@jrandolf but `load` event assumes waiting for `domcontentloaded` and `load` should always happen after `domcontentloaded`.

**Comment by OrKoN** [comment]
so 

```
await page.goto("https://ilsole24ore.com", {
    waitUntil: "load",
});
// events received at this point should be: ['domcontentloaded', 'load'].
// reload should reset received events.
await page.reload();
// should clear the received events before this point and start waiting for a fresh pair of ['domcontentloaded', 'load']
```

**Comment by jrandolf** [comment]
In CDP it shows that `domcontentloaded` happens after `load`. In particular, what happens (if you remove `page.reload`) is the `load` happens, then the query, then the `domcontentloaded`. From looking at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event), these events look independent.

Independent of this though, if you wait for both `load` and `domcontentloaded`, the script fails once more which shouldn't be the case. I'll take a deeper look.

**Comment by OrKoN** [comment]
> The DOMContentLoaded event fires when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading.
> The load event is fired when the whole page has loaded, including all dependent resources such as stylesheets, scripts, iframes, and images. This is in contrast to [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event), which is fired as soon as the page DOM has been loaded, without waiting for resources to finish loading.

IMO the DOMContentLoaded almost always comes before the load (especially if the page has resources). It might be that Puppeteer inserts async handling when processing it? Do you have a CDP log for this goto/reload part? We can take a look offline together.

**Comment by jrandolf** [comment]
A functional repro:

```ts
import * as Puppeteer from "puppeteer";

const browser = await Puppeteer.launch({
    ignoreHTTPSErrors: true,
    headless: false,
    devtools: true,
});

const page = await browser.newPage();

await page.goto("https://ilsole24ore.com", {
    waitUntil: "load",
});

await page.reload();

const element = await page.evaluate(() => document);
```
