### ISSUE TITLE
Puppeteer and Brave incognito mode issue

### ISSUE THREAD

**Issue by Kingkross1** [puppeteer/puppeteer#10438]
### Bug expectation

I’m facing an issue with opening an incognito mode in Brave browser with puppeteer. The issue is that when I launch the browser with the "--incognito" flag or create an incognito browser context with puppeteer, it opens an incognito window, but then it also opens another tab with normal mode and performs the task there instead of the incognito mode.
![127679997-488e3466-1bc2-4f2d-88a4-4b2a1a385024](https://github.com/puppeteer/puppeteer/assets/32878063/d2453cea-a026-4a4d-a8c4-8738c1dffba1)
![127680024-0ad954ab-aec3-4031-bc4e-fb1e4416dd69](https://github.com/puppeteer/puppeteer/assets/32878063/61cc4a7c-3085-4c8d-b981-d92cae17990b)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const path = require('path');
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: [
      '--incognito',
    ],
    executablePath: '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',
    headless: false,
  });

  const context = await browser.createIncognitoBrowserContext();

  const page = await context.newPage();

  await page.goto('https://google.com');

})();
```

### Error string

no error

### Puppeteer configuration

```TypeScript
const path = require('path');
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: [
      '--incognito',
    ],
    executablePath: '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',
    headless: false,
  });

  const context = await browser.createIncognitoBrowserContext();

  const page = await context.newPage();

  await page.goto('https://google.com');

})();
```

### Puppeteer version

20.7.3

### Node version

18.15.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

macOS

**Comment by OrKoN** [comment]
It looks like it does not reproduce with Chromium so I suggest you report the issue to the Brave browser team.
