### ISSUE TITLE
add multiple page.emulate() = browser.emulate()

### ISSUE THREAD

**Issue by fhmd4k** [puppeteer/puppeteer#1043]
Use the `page.emulate()` only affect to the one page instance.
add the `browser.emulate()` affect to the browser instance.
For example:
When tap/click a _blank link element, the new page(tab) is no emulated.

`browser.emulate()` need listen target create and distory. When the target create,it must use new Page instance to call `page.emulate()` before the page load.

**Comment by aslushnikov** [comment]
@fhmd4k what's your use case for this? Why is current API not sufficient for you?
