### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#10444]
### Bug expectation

I am calling for the creation of 30 copies of the puppeteer. 29 runs without problems, but when it comes to 30 I get "Error: failed to start the browser process!
The maximum number of clients has been reached"

my system is ubuntu 23.04 , version puppeteer-core -19.7.2

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer-core');

let web = {
    async create() {
        let browser = await puppeteer.launch({
            executablePath: './browser/chrome/',
            ignoreDefaultArgs: ["--enable-automation", "--disable-features=Crashpad", "--no-sandbox", "--disable-extensions"],
            args: [ '--disable-save-password-bubble', '--no-default-browser-check', '--disable-features=InfiniteSessionRestore'],
            ignoreHTTPSErrors: true,
            defaultViewport: null,
            headless: false
        });
       
        let page = await browser.newPage();
        await (await browser.pages())[0].close();
        browsers.push({id: id, browser: browser, page: page});
        return page;
    }
}

async function startWorkerCount(count) {
    for (let i = 0; i < count; i++) {
        await delay(500)
        await web.create();
    }
}

startWorkerCount(30);
```

### Error string

Failed to launch the browser process!

### Puppeteer version

19.7.2

### Node version

18.16.1

### Package manager

npm

### Package manager version

9.6.1

### Operating system

Linux

**Comment by Zavetoriginal** [comment]
I upgraded to the latest version, but it didn't solve my problem.

**Comment by OrKoN** [comment]
I don't think it's a problem with Puppeteer. Keep in mind that each puppeteer.launch launches a browser process that might consume a lot of resources. The error you are seeing is likely coming from your system and if you have enough resources to handle so many browsers consider reconfiguring your system: https://unix.stackexchange.com/questions/368017/cant-start-applications-due-to-maximum-number-of-clients-reached-error
