### ISSUE TITLE
[Bug]: `waitForNavigation()` not waiting for full page visibility in Next.js app 

### ISSUE THREAD

**Issue by ProchaLu** [puppeteer/puppeteer#10447]
### Bug expectation

There is an issue with the `waitForNavigation()` function when utilized within a Next.js app directory. This issue arises when the test scenario involves waiting for the full page to be visible, but `waitForNavigation()` incorrectly considers the page to be ready when the Next.js Loading component is still visible when using the example provided in the Puppeteer documentation, which suggests using the following code snippet:

```js
const [response] = await Promise.all([
  page.waitForNavigation(),
  page.click('a.my-link'),
]);
```

Unfortunately, relying on this example alone leads to flaky behavior due to the presence of the Loading component in Next.js applications. Despite the network tab being idle, the Loading component may still be visible, resulting in an inaccurate determination of page readiness by `waitForNavigation()`. Consequently, the example's approach can lead to unreliable test results.

The test scenario involves clicking on a link within a [Next.js application](https://next-route-puppeteer.vercel.app/), triggering a navigation event. The expectation is to wait for the full page to load and then verify the presence of an `h1` element with the content `PAGE`. 

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import { launch } from 'puppeteer';

async function clickAndWaitForNavigation(selector, page) {
  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click(selector),
  ]);
}

(async () => {
  const browser = await launch();
  const page = await browser.newPage();
  await page.goto('https://next-route-puppeteer.vercel.app/');

  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click('a[href="/page"]'),
  ]);

  const h1Content = await page.$eval('h1', (element) => element.textContent);

  if (h1Content === 'PAGE') {
    console.log('PASS');
  } else {
    console.log('FAIL');
  }

  await browser.close();
})();
```

### Error string

Error: failed to find element matching selector "${selector}"

### Puppeteer version

20.7.3

### Node version

v18.16.0

### Package manager

pnpm

### Package manager version

8.6.0

### Operating system

macOS

**Comment by OrKoN** [comment]
The problem appears to be that Next.js is using same-document navigation so the browser navigation is resolved much earlier than the app-level navigation (first, the browser navigation happens, then the app starts loading things). Since the browser (and thus Puppeteer) is not able to know app-specific criteria for navigation, the recommended solution is to use a more robust approach with waiting for elements explicitly:

```
import { launch } from 'puppeteer';

(async () => {
  const browser = await launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://next-route-puppeteer.vercel.app/');

  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click('a[href="/page"]'),
  ]);

  const element = await page.waitForSelector('text/PAGE');

  console.log(await element.evaluate((e) => e.textContent));

  await browser.close();
})();
```

**Comment by ProchaLu** [comment]
Next.js related issue: 
- https://github.com/vercel/next.js/issues/52265

**Comment by OrKoN** [comment]
@ProchaLu I am not sure it is the problem with Next.js either. Puppeteer is a library for browser automation so it deals with browser/webplatform-level abstractions. What you seem to expect is that Puppeteer is an application-level testing framework. And while Puppeteer can be used to build such a framework, it is not working like that out of the box.  For example, consider a basic app that listens for the [load](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) and 5 seconds later adds a div saying `navigation finished`. From the application perspective, the loading is finished when the UI got updated but in the browser/Web platform terms, the loading is finished when the load event is emitted. Since Puppeteer cannot know all the application-specific abstractions, it cannot interpret the  fact of div being added to the DOM as a navigation. 

Also, in this Next.js test app here there are no actual network requests sent while "loading" is displayed so the network becomes idle much earlier. I would recommend to write a custom helper that detects Next.js specific navigations: for example, you might want to wait till the URL changed and the loading indicator is not shown.

**Comment by karlhorky** [comment]
I would propose that regardless of the pure definitions and responsibility areas of tools, users will not understand it this way, and will try to plug those two together to test applications (because it works out of the box without many custom helpers for many / most common cases).

So I believe that users will continue to do this, and it's good to track this problem, for those people who will inevitably also run into this problem.

And ideally, Puppeteer and/or Next.js should maybe also consider fixing or working around the problem, even if it doesn't fit the project's definitions of purity, if it can be done in a maintainable, minimal way that ideally aligns with common standards like web standards or expectations in the browser automation scene. Even a maintained "recipes section" in the docs for either project would be a good start for that.

**Comment by ProchaLu** [comment]
A workaround would be to add a `data-test-id` to the loading component,
```js
export default function RootLoading() {
  return <h1 data-test-id="loading">Loading</h1>;
}
```
This `data-test-id` is easy accessible and can be used in a `page.waitForFunction` to wait for the loading part to disappear from the page. Here's what the updated test looks like:
```js
await Promise.all([
  page.waitForNavigation({ waitUntil: 'networkidle0' }),
  clickElement.click(),
]);

await page.waitForFunction(() => {
  const loadingElement = document.querySelector('[data-test-id="loading"]');
  return !loadingElement;
});
```
This change ensures that the test moves on only when the loading part is no longer there. This should address the problem of the loading component staying visible when we don't want it to.

**Comment by ProchaLu** [comment]
After investigating the loading states in Next.js, I was able to see some differences that can cause issues with Puppeteer and Next.js in the previous versions. I think since [Next.js `v13.4.20-canary.24`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.24), the loading state behavior has changed.

The [reproduction project](https://github.com/ProchaLu/next-loading-state) contains:

- Landing page featuring the `cookies().get` functionality
- Page for the `cookies().set` operation
- Test page to check the `cookies().get` function
- Content-rich page with both text and image elements
- Page with a client-side timeout of 2 seconds
- Page with a server-side timeout of 2 seconds
- Page equipped with a fetch function for interacting with an external API

The Puppeteer test goes to every page and checks the loading state, and waits for the network to be idle, to see if this can cause an issue when the test runner thinks the page is already loaded.

The biggest difference is that the Next.js Loading component is not showing in the previous versions when the network is pending.

## Loading state with the `cookies().get` and `cookies().set` pages

- ### Loading component is not rendered when making network requests in Next.js `v13.4.9`, [Reproduction](https://github.com/ProchaLu/next-loading-state-old-version):

https://github.com/upleveled/courses/assets/80746311/85ea500b-74a8-4e0b-8e22-627d5084763b

<img width="1262" alt="old-network-pending-no-loading" src="https://github.com/upleveled/courses/assets/80746311/d5acb021-339f-472c-bbcd-910d011b7249">
<img width="1262" alt="old-network-pending-test-no-loading" src="https://github.com/upleveled/courses/assets/80746311/4667d9a3-880e-49b1-89c0-5d28d6a97a56">

- ### Loading component is rendered when making network requests in Next.js `v13.4.20-canary.24`, [Reproduction](https://github.com/ProchaLu/next-loading-state):

https://github.com/upleveled/courses/assets/80746311/38eb7340-2bdc-4a58-808d-a1b95487301d

<img width="1262" alt="new-network-pending-test-loading" src="https://github.com/upleveled/courses/assets/80746311/794773bb-4ade-4833-9ae9-301b306243df">

## Loading state when changing to a page with a server-side timeout

- ### Loading state not rendered with Next.js `v13.4.9`, [Reproduction](https://github.com/ProchaLu/next-loading-state-old-version):

<img width="1262" alt="old-network-pending-timeout-no-loading" src="https://github.com/upleveled/courses/assets/80746311/24243d6c-3e29-43e9-9eb7-bb54ffe814a9">

- ### Loading state rendered with Next.js `v13.4.20-canary.24`, [Reproduction](https://github.com/ProchaLu/next-loading-state):

<img width="1262" alt="new-network-pending-timeout-loading" src="https://github.com/upleveled/courses/assets/80746311/8cd43528-8eb3-4653-8851-c97045951156">

## Loading state when the network is idle after a `fetch`

- ### Loading state rendered and network idle with Next.js `v13.4.9`, [Reproduction](https://github.com/ProchaLu/next-loading-state-old-version):

<img width="1262" alt="old-network-idle-loading-state" src="https://github.com/upleveled/courses/assets/80746311/5d49726b-10c9-4145-bd4f-ba19f4a390cb">

- ### Loading state not rendered and network idle with Next.js `v13.4.20-canary.24`, [Reproduction](https://github.com/ProchaLu/next-loading-state):

<img width="1262" alt="new-fetch-finished-no-loading" src="https://github.com/upleveled/courses/assets/80746311/ef852e09-6e83-4a89-83ae-00d9aa26daab">

## Test results with Next.js `v13.4.9`:

```
goto page and set cookie
❌ not found
goto landing page
❌ not found
goto get cookie page
❌ not found
goto page with images and text
❌ not found
goto page with timeout
❌ not found
goto page with server timeout
✅ found
fetch from Pokemon API
✅ found
lading page second load
❌ not found
```

## Test results with Next.js `v13.4.20-canary.24`:

```
goto page and set cookie
✅ found
goto landing page
✅ found
goto get cookie page
✅ found
goto page with images and text
❌ not found
goto page with timeout
❌ not found
goto page with server timeout
✅ found
fetch from Pokemon API
✅ found
lading page second load
✅ found
```

## Page displaying before network is idle

<img width="1072" alt="network-not-idle-no-loading" src="https://github.com/upleveled/courses/assets/80746311/8fd29d62-dc32-48dd-8fd2-e5ac5b00e8de">

It is unclear for me whether this is an issue, as the page may render before it has fully loaded. Some images may still be pending in the network tab. In cases where these are no network requests, Puppeteer may interpret the network as idle beore the full page is loaded.

## [Reproduction](https://github.com/ProchaLu/next-loading-state-without-loading) without Next.js loading state:

https://github.com/upleveled/courses/assets/80746311/1e650b45-95c1-4ca7-b0dc-9eb4e3b77152

In this test repository, I noticed that network requests always finish before the page changes. This means that the network is idle before the new page is visible. As the screenshots show, before the page changes, the network is idle, and then the page changes.

- ### Network active on the previous page after click

<img width="1261" alt="no-loading-fetch-request" src="https://github.com/upleveled/courses/assets/80746311/f82788c2-fdcf-4ccd-8268-7578ae6ee093">

- ### Network is idle and page changes

<img width="1261" alt="no-loading-fetch-idle" src="https://github.com/upleveled/courses/assets/80746311/b38de5db-ce4f-4194-9e76-52378a0187d7">

## Other differences observed during testing

- Next.js changed the network requests. After recording videos with an older and newer Next.js version, I observed a difference in network requests when deploying the same page.

Next.js v`13.4.9`, 10 requests
<img width="323" alt="Screenshot 2023-09-22 at 12 24 13" src="https://github.com/upleveled/courses/assets/80746311/4566e58d-86ab-4575-89af-6280633e9836">

Next.js v`13.4.20`, 16 requests
<img width="323" alt="Screenshot 2023-09-22 at 12 26 06" src="https://github.com/upleveled/courses/assets/80746311/21ffbe9e-ecdb-4cef-a65b-df02df001faa">

## Conclusion:

The loading state issue with Next.js and Puppeteer that I encountered seems to be fixed in Next.js. I recommend upgrading always to the latest stable release version.

The loading state now works as expected on all pages except pages with client-side timeout are displaying the Next.js loading state. The loading component becomes visible when the network is active and disappears when the network becomes idle.

**Comment by ProchaLu** [comment]
The loading state issue with Next.js and Puppeteer can be fixed by using a more robust way for a route change like OrKoN described in this [comment](https://github.com/puppeteer/puppeteer/issues/10447#issuecomment-1606878952). It is also possible to use the example form the [Puppeteer docs](https://pptr.dev/api/puppeteer.page.waitfornavigation#example) with the latest Next.js version. If you want to get into more detail, you can read my comment above.

```js
function clickAndWaitForNavigation(page) {
  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click('a[href="/page"]'),
  ]);
  await page.waitForSelector('text/PAGE');
}
```

Alternatively, you can use a `data-test-id` inside the `loading.js` file:

```js
export default function RootLoading() {
  return <div data-test-id="loading">...Loading...</div>;
}
```

Then, you can wait for the loading element to disappear in your test:

```js
await Promise.all([
  page.waitForNavigation({ waitUntil: 'networkidle0' }),
  clickElement.click(),
]);

await page.waitForFunction(() => {
  const loadingElement = document.querySelector('[data-test-id="loading"]');
  return !loadingElement;
});
```
