### ISSUE TITLE
Getting different result on different machines in the same environment

### ISSUE THREAD

**Issue by tangna** [puppeteer/puppeteer#10456]
I am trying to measure height of the element using puppeteer@19.11.1.
Simple code gives different results on different machines with the same environment.

```
const page = await browser.newPage();

const headerAPPCopy = Object.assign({
    'User-Agent': 'Mozilla/5.0 (Linux; Android 8.0.0; SM-G955U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36 Edg/114.0.0.0',

})
await page.setExtraHTTPHeaders(headerAPPCopy);
await page.setUserAgent('Mozilla/5.0 (Linux; Android 8.0.0; SM-G955U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36 Edg/114.0.0.0')
await page.emulate(puppeteer.KnownDevices["iPhone SE"]);
await page.setViewport({
    width: 640,
    height: 480,
    deviceScaleFactor: 1,
    isMobile: true,
});
await page.waitForTimeout(10000)
await page.goto(url, {
    waitUntil: "networkidle2",
});
const elementHandleAPP = await page.$('body > div:first-of-type');
const heightAPP = await page.evaluate(el => el.offsetHeight, elementHandleAPP);
const widthApp = await page.evaluate(el => el.offsetWidth, elementHandleAPP);
console.log(widthApp);
```

Adding sample 
https://github.com/tangna/puppeteer-test/archive/refs/heads/main.zip

In the local virtual machine, I get result - 772
In the cloud host, I get result - 835

My operating environment is centos7.9 system, node version v14.16.1, why are the results different?
The following is a screenshot of my running results.

![remoteMachine](https://raw.githubusercontent.com/tangna/puppeteer-test/main/remoteMachine.png)
![localMachine](https://raw.githubusercontent.com/tangna/puppeteer-test/main/localCentos.png)

**Comment by OrKoN** [comment]
please provide a complete example including a test page and validate the issue using the latest version of Puppeteer.

**Comment by tangna** [comment]
I uploaded my demo to github.[code address](https://github.com/tangna/puppeteer-test.git) 
The test page is inside the code,like
`const url = "https://www.event.headline.net/eucpi-meta"`

Also I can't use the latest version of Puppeteer. Because my node version is v14.16.1.Thank you for your reply.

**Comment by tangna** [comment]
I got the same result after installing the font on the server. Thanks
