### ISSUE TITLE
[Bug]: Error: Could not find Chrome in production environment

### ISSUE THREAD

**Issue by ainuraliyah** [puppeteer/puppeteer#10451]
### Bug expectation

I expected my app in production (Linux) could download a generated report file using the puppeteer library. It works safely in my local environment (windows). 

What happened instead was an error while downloading the file in the production environment so the pdf could not be generated. The error message is shown below: 

```
Error: Could not find Chrome (ver. 114.0.5735.133). This can occur if either
1. you did not perform an installation before running the script (e.g. `npm install`) or 
2. your cache path is incorrectly configured (which is: /home/support/.cache/puppeteer). 

For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. at Chrome Launcher.resolveExecutablePath (/home/auction/node_modules/puppeteer-core/lib/cjs/p at Chrome Launcher.executablePath (/home/auction/node_modules/puppeteer-core/lib/cjs/puppeteer: at Chrome Launcher.computeLaunchArguments (/home/auction/node_modules/puppeteer-core/lib/cjs/1 at async Chrome Launcher.launch (/home/auction/node_modules/puppeteer-core/lib/cjs/puppeteer/1
```

I used Chrome ver. 114.0.5735.134 (Official Build) (64-bit). I ran `npm ci` and `npm install puppeteer` but nothing changed.
The ./cache/puppeteer directory is automatically created in the local environment but not in the production.
Any help will be appreciated.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

async generateStream(payload) {
        const browser = await puppeteer.launch({headless: true, userDataDir: './.cache/puppeteer'});
        const page = await browser.newPage();

        const template = fs.readFileSync('./template/reports/my-template.html', 'utf-8')
        const html = mustache.render(template, payload)

        await page.setContent(html);
        await page.emulateMediaType('screen');

        const pdf = await page.pdf({
            format: 'A4',
            printBackground: true,
            preferCSSPageSize: true
        })
        await browser.close();

        return new Promise((resolve, reject) => {
            const stringBase64 = Buffer.from(pdf).toString('base64');
            return stringBase64 ? resolve(stringBase64) : reject('ERROR GENERATE');
        })
    }
```

### Error string

Error: Could not find Chrome (ver. 114.0.5735.133). This can occur if either 1. you did not perform an installation before running the script (e.g. `npm install`) or  2. your cache path is incorrectly configured (which is: /home/support/.cache/puppeteer).   For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

### Puppeteer version

20.5.0

### Node version

v16.14.0

### Package manager

npm

### Package manager version

8.3.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Do you run `npm install` in your production environment? How do you deploy? can you check if the binary is there is in your production environment (at ` /home/support/.cache/puppeteer`)

**Comment by OrKoN** [comment]
Unable to reproduce, so I assume it is a misconfiguration when deploying to the server. Make sure to follow the guidance displayed in the error message: run `npm install` (`npm ci`) during or after deployment to the new environment; or change the configuration to download browser binaries inside your local folder. See https://pptr.dev/#installation and https://pptr.dev/guides/configuration

**Comment by ainuraliyah** [comment]
> 

is it necessary to create a `/home/support/.cache/puppeteer` directory?

**Comment by OrKoN** [comment]
@ainuraliyah it is where the cache directory is located on your server. If you run `npm ci` for installing puppeteer on the server, it is where Puppeteer would download the browser. Alternatively, you can re-configure the cache location but since your local system is a Windows, you still would need a binary for Linux.
