### ISSUE TITLE
Puppeteer failing at killChrome

### ISSUE THREAD

**Issue by pgrantmartello** [puppeteer/puppeteer#1045]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: bash on Windows 10
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. I'm trying to run the npm package decktape which uses puppeteer. It fails `at killChrome (/usr/local/lib/node_modules/decktape/node_modules/puppeteer/lib/Launcher.js:122:19)`
2. I can see Chromium downloading when I install puppeteer, but I'm unable to run Chrome from the command line
3.

**What is the expected result?**
I expect puppeteer to launch headless Chrome

**What happens instead?**
Puppeteer doesn't seem to be able to find Chrome at all.

Please be gentle - I'm really REALLY new to linux/cli stuff. I don't really know what I'm doing yet. If you need further information from me, please try to guide instructions to getting what you need. Thanks!

**Comment by ebidel** [comment]
This sounds like a potential issue with that npm package.  But can you provide  us with more details? Errors, full code that repros the issue, etc.

**Comment by entrptaher** [comment]
Can be linked to this issue https://github.com/GoogleChrome/puppeteer/issues/1047
