### ISSUE TITLE
[Bug]: yarn install is not downloading Chromium

### ISSUE THREAD

**Issue by ghostlexly** [puppeteer/puppeteer#10457]
### Bug expectation

I expected Chromium to be downloaded with `yarn install` command.

It's doesn't install chromium

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
yarn add puppeteer
```

### Error string

Could not find Chrome (ver. 114.0.5735.133). This can occur if either

### Puppeteer version

20.7.3

### Node version

18.16.0-alpine3.17

### Package manager

yarn

### Package manager version

1.22.17

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
If I create a new project with puppeteer, it seems to work correctly. 
It seems `yarn` does not run `postinstall` the second time you do `yarn install` so if you delete the cache.
https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall
Adding `"postinstall": "node ./node_modules/puppeteer/install.js"` to your `package.json` `scripts` seems to work and should have no overhead as we check the checking the cache.
![image](https://github.com/puppeteer/puppeteer/assets/34244704/98bee8fb-eba7-4cd7-8c03-c5cfd55fa965)
