### ISSUE TITLE
[Bug]: WebGL doesn't work on mac-arm

### ISSUE THREAD

**Issue by LeviPesin** [puppeteer/puppeteer#10462]
### Bug expectation

WebGL doesn't work and throws when trying to create a context on Mac ARM (no problem on other OSes).
Unfortunately I don't have a Mac to test but this problem is widely reported by users: https://github.com/mrdoob/three.js/pull/25504#issuecomment-1429458541, https://github.com/mrdoob/three.js/pull/25504#issuecomment-1429505564, https://github.com/mrdoob/three.js/pull/26341#issue-1778040105.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async function() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.evaluate(() => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('webgl');
        if (ctx === null) throw new Error('Error creating WebGL context.');
    });
})();
```

### Error string

Error creating WebGL context.

### Puppeteer version

20.7.3

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

macOS

**Comment by LeviPesin** [comment]
No idea whether it is reproducible on the latest version, but updated.

**Comment by OrKoN** [comment]
Try using the `headless:new` or `headless:false`. There are multiple chromium bugs that sound similar https://crbug.com/1416283 https://crbug.com/1280727 and it does not look like a Puppeteer issue.

**Comment by OrKoN** [comment]
It works on my mac-arm with `headless: new`

**Comment by OrKoN** [comment]
Filed a new bug from Chromium (https://crbug.com/1458737) as it happens without Puppeteer too.

**Comment by OrKoN** [comment]
Closing this issue as it cannot be solved in Puppeteer.

**Comment by LeviPesin** [comment]
Seems like the `--enable-gpu` flag solves the issue.
