### ISSUE TITLE
[Bug]: PDF text line is cropped & added to the next page

### ISSUE THREAD

**Issue by VictorBaron** [puppeteer/puppeteer#10469]
### Bug expectation

When generating a PDF from a web page, the page splitting seems to have a problem.

Since an image is better than 1000 words: 
![image](https://github.com/puppeteer/puppeteer/assets/10496372/2f02fd61-c806-449a-bd86-fad1e86c864a)

The line seems to be split, then the lower half is "glued" on top of the next page.

My configuration to generate this PDF is: 
```ts
    const pdf = await page.pdf({
      format: 'a4',
      timeout: 120000,
      printBackground: true,
      displayHeaderFooter: !!header || !!footer,
      headerTemplate: header?.html ?? '<div></div>',
      footerTemplate: footer?.html ?? '<div></div>',
      margin: {
        top: headerHeight ?? 40,
        bottom: footerHeight ?? 30,
      },
    });
``` 
With headerHeight & footerHeight the clientHeight of the header & footer respectively, if any.
 

### Bug behavior

- [X] Flaky
- [X] PDF

### Minimal, reproducible example

```TypeScript
/* 
* Unfortunately I would need to send all the html content to be able to emulate this behavior.
*/
```

### Error string

no error

### Puppeteer version

20.7.3

### Node version

16.18.0

### Package manager

yarn

### Package manager version

1.22.17

### Operating system

macOS

**Comment by OrKoN** [comment]
I feel like a similar issue has been already reported but I could not find it. In any case, this is a Chromium bug: could you please file it at crbug.com including a minimal reproducible example?

**Comment by adisharma29** [comment]
Any solution for this?

**Comment by OrKoN** [comment]
The issue does not contain a reproducible example. Therefore, closing as not planned. Please re-test in M117.
