### ISSUE TITLE
Bug: `pupeteer-core` ^20.4.0 can't be bundled with `pkg`

### ISSUE THREAD

**Issue by MCHK0306** [puppeteer/puppeteer#10477]
### Minimal, reproducible example

```TypeScript
When I package puppeteer-core 20.4.0 or higher (using pkg) and launch the executable, the following error message occurs. (The error does not occur with puppeteer-core 20.3.0 or lower, but there is a bug in 20.3.0 or lower, so we want to use 20.4.0 or higher)  To begin with, I don't know if the error is caused by pkg or by puppeteer-core.

I think that ****/node_modules/vm2/lib/setup-sandbox.js, which appears in installations after 20.4.0, is causing this problem.
```

### Error string

pkg/prelude/bootstrap.js:657 const error = new Error( ^  Error: File '/**/InventoryTool_v4/node_modules/vm2/lib/setup-sandbox.js' was not included into executable at compilation stage. Please recompile adding it as asset or script. at error_ENOENT (pkg/prelude/bootstrap.js:657:19) at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29) at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18) at Object. (/snapshot/InventoryTool_v4/node_modules/vm2/lib/vm.js:148:57) at Module._compile (pkg/prelude/bootstrap.js:1926:22) at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) at Module.load (node:internal/modules/cjs/loader:988:32) at Module._load (node:internal/modules/cjs/loader:834:12) at Module.require (node:internal/modules/cjs/loader:1012:19) at Module.require (pkg/prelude/bootstrap.js:1851:31) { errno: -2, code: 'ENOENT', path: '/snapshot/InventoryTool_v4/node_modules/vm2/lib/setup-sandbox.js', pkg: true }  Node.js v18.5.0

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I packaged the code containing puppeteer-core with pkg and tried to distribute it, but could not run it.

### Expectation

I need solution.

### Reality

I packaged the code containing puppeteer-core with pkg and tried to distribute it, but could not run it.

### Puppeteer version

higher than 20.4.0

### Node version

18.5.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
This looks like https://github.com/puppeteer/puppeteer/issues/10352, I have not worked with `pkg` perhaps you can mark the `vm2` package as external as most likely you will not hit those code path anyway.
