### ISSUE TITLE
[Bug]: Node 14 error can't install puppeteer

### ISSUE THREAD

**Issue by putuoka** [puppeteer/puppeteer#10470]
### Bug expectation

![image](https://github.com/puppeteer/puppeteer/assets/20880839/919fd7fc-7a5d-4a70-b95b-fa9240a1ffa6)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
1. npm init
2. npm i puppeteer
3. error
```

### Error string

SyntaxError: Unexpected token '??='

### Puppeteer version

latest  puppeteer@20.7.3

### Node version

v14.17.6

### Package manager

npm

### Package manager version

6.14.15

### Operating system

Windows

**Comment by OrKoN** [comment]
Node 14 is not supported anymore.

**Comment by putuoka** [comment]
use puppeteer@13.7.0 if anyone want to use node 14 for puppeteer
