### ISSUE TITLE
[Bug]: Running Headless causes page.click() to error

### ISSUE THREAD

**Issue by sfeliceSNC** [puppeteer/puppeteer#10481]
### Minimal, reproducible example

```TypeScript
My code is for work and cannot be made public.
```

### Error string

Error: Node is either not clickable or not an HTMLElement

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I'd like page.click() to work correctly without error headless or while watching it run.

### Reality

When I use page.click() in headless mode, I get the error message "Error: Node is either not clickable or not an HTMLElement".
I've been experiencing this for a while now, anyone else having this issue?
It's fine when I'm watching it run, no errors!

### Puppeteer version

20.7.3

### Node version

18.12.1

### Package manager

npm

### Package manager version

9.3.0

### Operating system

Windows

**Comment by jrandolf** [comment]
The error describes the situation precisely. Either the node is not clickable because it does not have a visible bounding box or is off the page OR it is not an HTMLElement.
