### ISSUE TITLE
[Bug]: Frame.evaluate hangs indefinitely on Twitter's login page in new headless/headful mode

### ISSUE THREAD

**Issue by DCtheTall** [puppeteer/puppeteer#10483]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

const url = "https://twitter.com/i/flow/login";
const timeout = 5 * 1e3; // 5 seconds.

(async () => {
    const browser = await puppeteer.launch({
        headless: 'new',
        args: [],
        devtools: true,
    });

    const ctx = await browser.createIncognitoBrowserContext();

    ctx.on('targetcreated', async target => {
        try {
            const cdpClient = await target.createCDPSession();
            await cdpClient.send('Target.setAutoAttach', {autoAttach: true, waitForDebuggerOnStart: true});
            await cdpClient.send('Runtime.enable');
            await cdpClient.send('Runtime.runIfWaitingForDebugger');
        } catch (err) {
            console.error(err);
        }
    });

    const page = await ctx.newPage();

    const cdpClient = await page.target().createCDPSession();
    await cdpClient.send('Target.setAutoAttach', {autoAttach: true, waitForDebuggerOnStart: true});

    await page.goto(url, {timeout, waitUntil: 'networkidle0'});

    for (const page of await ctx.pages()) {
        for (const frame of page.frames()) {
            await frame.evaluate(async () => 1);
        }
    }

    await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I also have a reproduction of the issue [in this repo](https://github.com/DCtheTall/puppeteer-bug-repro).

My platform is macOS 13.4.1, Chrome version 114.

I think this is probably related to [#8399](https://github.com/puppeteer/puppeteer/issues/8399) which was closed by its reporter when the responder failed to reproduce the issue. However, in this case my code is able to deterministically reproduce the issue.

I did notice that if you set `autoAttach` and `waitForDebuggerOnStart` to `false` in the `Target.setAutoAttach` invocations then the bug does not occur. Seems like some sort of deadlock?

### Expectation

Puppeteer should finish visiting the page.

### Reality

Puppeteer hangs indefinitely while visiting the page while awaiting `Frame.evaluate`

### Puppeteer version

20.7.4

### Node version

18.4.2

### Package manager

npm

### Package manager version

9.5.0

### Operating system

macOS

**Comment by OrKoN** [comment]
I think you should subscribe to Target.attachedToTarget events on new sessions you create and call `Runtime.runIfWaitingForDebugger` on each one of them. The difference in modes is probably caused by the custom treatment of Out-of-process Iframes in the old headless mode. So, in short, it does not look like the use of CDP in the custom session is correct.

**Comment by OrKoN** [comment]
The following should work:

```
const puppeteer = require("puppeteer");

const url = "https://twitter.com/i/flow/login";
const timeout = 5 * 1e3; // 5 seconds.

(async () => {
    const browser = await puppeteer.launch({
        headless: 'new',
        args: [],
        devtools: true,
    });

    const ctx = await browser.createIncognitoBrowserContext();

    ctx.on('targetcreated', async target => {
        try {
            const cdpClient = await target.createCDPSession();
            await cdpClient.send('Target.setAutoAttach', {autoAttach: true, waitForDebuggerOnStart: true, flatten: true});
            await cdpClient.send('Runtime.enable');
            cdpClient.on('sessionattached', async session => {
                await session.send('Runtime.runIfWaitingForDebugger');
            });
        } catch (err) {
            console.error(err);
        }
    });

    const page = await ctx.newPage();

    const cdpClient = await page.target().createCDPSession();
    await cdpClient.send('Target.setAutoAttach', {autoAttach: true, waitForDebuggerOnStart: true, flatten: true});
    await cdpClient.send('Runtime.enable');
    cdpClient.on('sessionattached', async session => {
        await session.send('Runtime.runIfWaitingForDebugger');
    });

    await page.goto(url, {timeout, waitUntil: 'networkidle0'});

    for (const page of await ctx.pages()) {
        for (const frame of page.frames()) {
            await frame.evaluate(async () => 1);
        }
    }

    await browser.close();
})();
```

and I would also exclude service worker targets and targets of type other as there are a few issues with auto-attach to service workers.

**Comment by DCtheTall** [comment]
@OrKoN thanks for the tip, that seems to have patched the issue on my end. I do see some exceptions when I call `session.send('Runtime. runIfWaitingForDebugger')` but this seems to be due to data races between when frames get navigated/closed, so to be expected.

I think this solves the issue. Thanks!
