### ISSUE TITLE
How can I automate uploading a file using puppeteer

### ISSUE THREAD

**Issue by claude-aj** [puppeteer/puppeteer#10499]
I want to upload a file. The scenario is:

1. Code should open headless browser 
2. Click on upload file icon
3. Select a file and upload it 

I need assistance with step 3. Can you provide guidance on how to accomplish this task?

**Comment by OrKoN** [comment]
Please post this question on StackOverflow if you need help with this. The short answer is: using https://pptr.dev/api/puppeteer.elementhandle.uploadfile/
