### ISSUE TITLE
[Bug]: Header section overlaps on each page of the generated pdf 

### ISSUE THREAD

**Issue by Meenakshise** [puppeteer/puppeteer#10505]
### Minimal, reproducible example

```TypeScript
I have a html file in which I generate lots of charts as a report. I need to attach header to each of the page
 that is generated by the pupeteer using that html. header I am able to attach but on the 1st page it appears 
correctly and the subsequent pages headers overlaps with the page content. Pupeeteer is not adjusting
 the content margin based on the header's height? can you please check once. I have pasted the code
 for the html as well as the pupeeteer code. Html file is chart.html 


pupeeter code
const puppeteer = require('puppeteer');
const fs = require('fs');

async function generatePDF(htmlContent, headerContent) {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    // Set the navigation timeout to a longer duration (e.g., 60 seconds)
    await page.setDefaultNavigationTimeout(60000);

    // Set the HTML content
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    // Click the button and wait for the chart generation
    await Promise.all([
      page.click('#generateChartButton'),
      page.waitForSelector('.chartContainer canvas', { visible: true }),
    ]);

    // Generate PDF
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: headerContent,
    });

    await browser.close();

    return pdf;
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
}

// Usage
const htmlFilePath = 'chart.html';
const headerContent = `
  <div style="text-align: center; font-size: 10px;">
    Header Content
  </div>
`;

// Read the HTML file
fs.readFile(htmlFilePath, 'utf8', (err, htmlContent) => {
  if (err) {
    console.error('Error reading HTML file:', err);
    return;
  }

  generatePDF(htmlContent, headerContent)
    .then((pdf) => {
      // Save the PDF to a file
      require('fs').writeFileSync('output.pdf', pdf);
      console.log('PDF generated successfully.');
    })
    .catch((error) => {
      console.error('Error generating PDF:', error);
    });
});


**html code** 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Chart Example</title>
  <style>
  
  .chart-container {
        position: relative;
        margin-top: 120px; /* Adjust the margin top to leaave space for the header and chart */
        overflow: hidden; /* Ensure the chart is not cut off */
        page-break-inside: avoid;
      }
    
    @media print {
      .header {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        height: 100px; /* Adjust the height as per your header size */
        text-align: center;
        background-color: #f0f0f0; /* Optional: Set a background color for the header */
        font-size: 16px; /* Optional: Set a font size for the header content */
        line-height: 100px; /* Optional: Center the header content vertically */
      }

     
    }
  </style>
</head>
<body>
    <div class="header">
     <p6>   Header Content from html  </p6>
      </div>
      <div class="content">
  <div id="chartsContainer"  class =chart-container></div>

  <button id="generateChartButton">Generate Charts</button>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    document.getElementById('generateChartButton').addEventListener('click', function() {
      const chartsContainer = document.getElementById('chartsContainer');
      const headerHeight = document.querySelector('.header').offsetHeight;
  
      // Generate 20 charts
      for (let i = 0; i < 20; i++) {
        const chartContainer = document.createElement('div');
        chartContainer.classList.add('chartContainer');
  
        const canvas = document.createElement('canvas');
        canvas.id = 'chartCanvas' + i;
        chartContainer.appendChild(canvas);
  
        chartsContainer.appendChild(chartContainer);
  
        const ctx = canvas.getContext('2d');
  
        // Chart data
        const data = {
          labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
          datasets: [{
            label: 'Chart ' + (i + 1),
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
              'rgba(255, 99, 132, 1)',
              'rgba(54, 162, 235, 1)',
              'rgba(255, 206, 86, 1)',
              'rgba(75, 192, 192, 1)',
              'rgba(153, 102, 255, 1)',
              'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
          }]
        };
  
        // Chart options
        const options = {
          scales: {
            y: {
              beginAtZero: true
            }
          }
        };
  
        // Create the chart
        new Chart(ctx, {
          type: 'bar',
          data: data,
          options: options
        });
  
   
      }
    });
  </script>
  
  
</body>
</html>


When you click on the generatecharts button it generates the charts. This is clicked in the pupeeteer code
```

### Error string

no error behavior is wrong 

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

Ideallly the header should be placed in each page. And Header section should be part of my html (it will be a div tag with some chart canvas code in the future but for now i have used a normal div tag with a header) 

### Reality

Header is positioned correctly only on the 1st page and in the remaining pages it overlaps  
[output.pdf](https://github.com/puppeteer/puppeteer/files/11947659/output.pdf)

### Puppeteer version

20.7.4

### Node version

v16.18.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
CSS does not provide a way to use a templates from inside the HTML to use as header/footer. You will have to use the Puppeteer `headerTemplate` and `footerTemplate` to achieve this. If there is data you need to get from the page you can use [Page.evaluate](https://pptr.dev/guides/evaluate-javascript) and use inside that template.
Alternately you could split each Chart in a separate page and have it's own header.

**Comment by Meenakshise** [comment]
@Lightning00Blade 

I have used header template only in the below code. Please check once. Header is overlapping from the 2nd page onwards. Won't the content get adjusted below based upon the header's height. I want to display as many charts as possible in a page. I don't want to display 1 chart per page. Please refer to the sample pdf which I would like to generate. In the below attached pdf if you see there are many charts are displayed and the patient banner and (datetime, obsmodel and obs interval table ) should be a header on each page. I am expecting the same using puppeteer. Is this possible?  I am trying a sample using chart.html and the below code to see if I can attach a header on each page . Please help me to solve this issue. 

[EWSReport ptn05245875 (1) (1).pdf](https://github.com/puppeteer/puppeteer/files/11953826/EWSReport.ptn05245875.1.1.pdf)


const puppeteer = require('puppeteer');
const fs = require('fs');
const { PDFDocument } = require('pdf-lib');

async function generatePDF(htmlContent,  headerClassName) {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    // Set the navigation timeout to a longer duration (e.g., 60 seconds)
    await page.setDefaultNavigationTimeout(60000);

    // Set the HTML content
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    // Hide the "Generate Charts" button in the PDF
    await page.addStyleTag({ content: '#generateChartButton { display: none; }' });

    // Click the button using JavaScript evaluation
    await page.evaluate(() => {
      document.getElementById('generateChartButton').click();
    });

    // Wait for the chart generation
    await page.waitForSelector('.chartContainer canvas', { visible: true });

      // Capture a screenshot of the header content
      const headerElement = await page.$(`.${headerClassName}`);
      const headerScreenshot = await headerElement.screenshot({
        encoding: 'base64',
      });

     // Generate PDF
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate:`<img src="data:image/png;base64, ${headerScreenshot}" />`,
    });

    await browser.close();
    console.log(`PDF generated successfully: `);
    return pdf;
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
}

// Usage
const htmlFilePath = 'chart.html';

// Read the HTML file
fs.readFile(htmlFilePath, 'utf8', async (err, htmlContent) => {
  if (err) {
    console.error('Error reading HTML file:', err);
    return;
  }
  generatePDF(htmlContent,'header')
  .then((pdf) => {
    // Save the PDF to a file
    require('fs').writeFileSync('output-header9.pdf', pdf);
  })
  .catch((error) => {
    console.error('Error generating PDF:', error);
  });
});

**Comment by Meenakshise** [comment]
const pdf = await page.pdf({
    path: pdfFilePath,
    printBackground: true,
    format: 'A4',
    displayHeaderFooter: true,
    headerTemplate: `<div style="width: ${adjustedHeaderWidth}px; height: ${adjustedHeaderHeight}px;"><img src="data:image/png;base64, ${headerScreenshot}" style="width: 100%; height: 100%;" /></div>`,
    margin: {top: "200px", bottom: "100px"}
  });

Solved this issue by adding margin top to the pdf options config

**Comment by chengle0575** [comment]
I face a similar issue.

Add @Page in the style works for me . It seems to be a similar solution with the option setting you provided.
Refer to these two links.
https://developer.mozilla.org/en-US/docs/Web/CSS/@page
https://stackoverflow.com/questions/40399568/headers-and-footers-over-contents-how-can-i-fix-this

**Comment by nikhila-darisa** [comment]
https://github.com/puppeteer/puppeteer/issues/4668#issuecomment-2777891162
