### ISSUE TITLE
[Bug]: Aborting Navigation Request times out with networkidle0

### ISSUE THREAD

**Issue by gerdriesselmann** [puppeteer/puppeteer#10507]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const express = require('express');

const chromeLaunchOptions = {
    headless: true,
    ignoreHTTPSErrors: true,
    timeout: 0,
    args: [
        '--disable-setuid-sandbox',
        '--no-sandbox',
    ],
};
const mockServerPort = 9661;
const redirect_url = 'https://example.com';
const pageWaitUntilOptions = ['load', 'networkidle0'];

async function test() {
    let browser = await puppeteer.launch(chromeLaunchOptions);
    let page = await browser.newPage();

    // Set up a proxy to serve our test content
    let mock = express();
    mock.get('/', function (req, res) {
        res.status(200).type('text/html').send("<script>location.href = '" + redirect_url + "';</script>");
    });
    let server = mock.listen(mockServerPort, async function () {
        await setPageHooks(page);

        await page.goto(`http://127.0.0.1:${mockServerPort}/`, {
            waitUntil: pageWaitUntilOptions,
            timeout: 5000
        }).catch(error =>
            console.log("Caught page error " + error)
        ).then( p =>
            page.content().then(c => console.log("<Page Content>", c) )
        )

        await page.close();
        await browser.close();
        server.close();
    });
}

async function setPageHooks(page) {
    await page.setRequestInterception(true);
    page.on('request', async (request) => {
        if (
            request.isNavigationRequest() &&
            request.frame() === page.mainFrame() &&
            request.url().includes("example.com")
        ) {
            console.log("[Request Aborted] ", request.url());
            return request.abort('aborted');
        } else {
            return request.continue();
        }
    });
}

test();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm trying to let a page render completely and obtain content afterwards. I use networkidle0 to wait for scheduled requests to finish before obtaining content.

I need to prevent JS redirects from being executed, and therefore abort them.

### Expectation

I expect the request to be aborted, and page.goto() to return shortly after.

### Reality

page.goto() blocks and finishes only after timeout is reached.

It does - however - **not** block if I ommit the "networkidle0" like so:

``const pageWaitUntilOptions = ['load'];``

It also does **not** block, if request is aborted without using the "aborted" error code;

`` return request.abort();``

In this case, it will replace the page's content with empty HTML or a Chrome error page, so I can't access the final rendered content any more.

### Puppeteer version

20.7.4

### Node version

16.20.1

### Package manager

npm

### Package manager version

9.7.3

### Operating system

Linux

**Comment by OrKoN** [comment]
Might be a bug in Chrome. Here is what happens:

1) `networkidle0` tells the goto function to wait for a networkidle0 event to be sent by the browser.
2) The first navigation is successful, but it triggers a redirect to example.com immediately so the browser does not send a networkidle0 event.
3) The redirect navigation is aborted and the browser does not send a networkidle0 event in this case either.

**Comment by gerdriesselmann** [comment]
Thank you for your investigation. I filed an according bug on the Chromium project: https://bugs.chromium.org/p/chromium/issues/detail?id=1462258

**Comment by caseq** [comment]
@OrKoN the browser never sends networkidle0, this is something computed by the puppeteer. While this may be induced by the browser bug, I think this needs to be investigated on the Puppeteer side first -- i.e. let's make sure Puppeteer haven't got some of the Network events required for correct evaluation of networkidle0 condition rather than is having some issues with networkidle evaluation logic.

**Comment by OrKoN** [comment]
@caseq the networkidle0 maps 1:1 to the CDP's PageLifecycle(networkIdle) and it is never sent in this case.
