### ISSUE TITLE
[Bug]:  Running postinstall script, failed in 652ms .../node_modules/puppeteer postinstall$ node install.js │ PUPPETEER_DOWNLOAD_HOST is deprecated. Use PUPPETEER_DOWNLOAD_BASE_URL instead. │ ERROR: Failed to set up Chrome r114.0.5735.133! Set "PUPPETEER_SKIP_DOWNLOAD" env v… │ Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirro…

### ISSUE THREAD

**Issue by ruanye** [puppeteer/puppeteer#10504]
### Minimal, reproducible example

```TypeScript
Running postinstall script, failed in 652ms
.../node_modules/puppeteer postinstall$ node install.js
│ PUPPETEER_DOWNLOAD_HOST is deprecated. Use PUPPETEER_DOWNLOAD_BASE_URL instead.
│ ERROR: Failed to set up Chrome r114.0.5735.133! Set "PUPPETEER_SKIP_DOWNLOAD" env v…
│ Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirro…
```

### Error string

 Running postinstall script, failed in 652ms .../node_modules/puppeteer postinstall$ node install.js │ PUPPETEER_DOWNLOAD_HOST is deprecated. Use PUPPETEER_DOWNLOAD_BASE_URL instead. │ ERROR: Failed to set up Chrome r114.0.5735.133! Set "PUPPETEER_SKIP_DOWNLOAD" env v… │ Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirro…

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

 Running postinstall script, failed in 652ms
.../node_modules/puppeteer postinstall$ node install.js
│ PUPPETEER_DOWNLOAD_HOST is deprecated. Use PUPPETEER_DOWNLOAD_BASE_URL instead.
│ ERROR: Failed to set up Chrome r114.0.5735.133! Set "PUPPETEER_SKIP_DOWNLOAD" env v…
│ Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirro…

### Reality

 Running postinstall script, failed in 652ms
.../node_modules/puppeteer postinstall$ node install.js
│ PUPPETEER_DOWNLOAD_HOST is deprecated. Use PUPPETEER_DOWNLOAD_BASE_URL instead.
│ ERROR: Failed to set up Chrome r114.0.5735.133! Set "PUPPETEER_SKIP_DOWNLOAD" env v…
│ Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirro…

### Puppeteer version

20.7.4

### Node version

18

### Package manager

pnpm

### Package manager version

20.7.4

### Operating system

macOS

**Comment by ayangweb** [comment]
Hey👋, did you solve this problem? I am also reporting this error, I can only downgrade from version 20 to 19 temporarily, what about you, how did you solve it, can you share?

**Comment by ayangweb** [comment]
> It appears you are downloading from a mirror that does not work properly: URL: https://npm.taobao.org Please make sure the mirror is compatible.

I checked at my mirror is indeed [https://registry.npmjs.org/](https://registry.npmjs.org/), but install it to the wrong, I want to install version 20 times wrong, but there is no error 19 version!
