### ISSUE TITLE
[Bug]: "Chrome for Testing v" "is only for automated testing. For regular browsing, use a standard version of Chrome that updates automatically"

### ISSUE THREAD

**Issue by brandonsay95** [puppeteer/puppeteer#10516]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

async function main() {
 
  const browser = await puppeteer.launch({ 
    ignoreDefaultArgs: ['--enable-automation'],
    headless: false,
    args: [
        '--hide-crash-restore-bubble',
       // '--start-fullscreen',
       '--test-type',
        '--disable-infobars'
],
    
 });
 const page = await browser.newPage();


}

main().catch((error) => {
  console.error('Error occurred:', error);
});
```

### Error string

Chrome for Testing v" "is only for automated testing. For regular browsing, use a standard version of Chrome that updates automatically

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I dont know if this is a new issue, but I cant find any resources on removing this message from the test version of chrome

### Expectation

No popups so i can use it as a fullscreen reporting engine.

### Reality

Popup about the version of chrome with no ability to dismiss.

### Puppeteer version

20.8.0

### Node version

v18.12.1

### Package manager

npm

### Package manager version

9.8.0

### Operating system

Windows

**Comment by brandonsay95** [comment]
<img width="1014" alt="image" src="https://github.com/puppeteer/puppeteer/assets/38471847/58949fb1-e99d-4f0b-b885-017abd78ccbd">

**Comment by brandonsay95** [comment]
The only info on this i can find is part of the source code , in a  lang file

https://chromium.googlesource.com/chromium/src/+/master/chrome/app/resources/generated_resources_en-GB.xtb

**Comment by OrKoN** [comment]
This one is not removable and it's a product requirement. For a version without this bar, you can use Chromium builds.

**Comment by boris-petrov** [comment]
Just to mention that `--test-type=gpu` seems to remove that infobar.
