### ISSUE TITLE
[Bug]: use cdp mouse click causes timeout error

### ISSUE THREAD

**Issue by TunaCannery** [puppeteer/puppeteer#10513]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');


(async () => {


const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://www.example.com/');

const client  = await page.target().createCDPSession();

await client.send('Emulation.setEmitTouchEventsForMouse', {
    enabled: true,
    configuration: "desktop"
}).catch(e => { });
await page.mouse.click(10,10)

})()
```

### Error string

ProtocolError: Input.dispatchMouseEvent timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

At first, I want to emulate my desktop broswer just like a mobile broswer,so I use cdp method,Emulation.setEmitTouchEventsForMouse, and when I use touchScreen.tap(), the gray dot on the page disappeared and turned into a mouse pointer. I don't know why
and when I use mouse.click(),I just hangs utils throws a timeout error

### Expectation

trigger a mouseEvent and do not throw a timeout error

### Reality

I hangs utils throws a timeout error

### Puppeteer version

19.11.1

### Node version

16.17.1

### Package manager

npm

### Package manager version

8.15.0

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
Please provide a full reproducible example that can be run independently, the the example in the template and not only a snippet.

**Comment by OrKoN** [comment]
I think it's a known CDP bug (@jrandolf cc)

**Comment by jrandolf** [comment]
This is a known bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1415994

The current workaround is to use `Input.emulateTouchFromMouseEvent`.

**Comment by OrKoN** [comment]
Same issue as https://github.com/puppeteer/puppeteer/issues/5730
