### ISSUE TITLE
[Bug]: page.mouse.move() executes slower if devtools is not open

### ISSUE THREAD

**Issue by AYS08** [puppeteer/puppeteer#10524]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: false,
        args: ["--disable-blink-features=AutomationControlled", "--window-size=1200,700"]
    });

    const [page] = await browser.pages();

    async function openDevTools(targetId) {
        const page = await browser.newPage();

        await page.goto("chrome://inspect");

        await page.evaluate((targetId) => {
            chrome.send('inspect', ['local', targetId]);
        }, targetId);

        await new Promise(r => setTimeout(r, 10000));
        
        await page.close();
        return;
    }

    function average(array) {
        return array.reduce((a, b) => a + b) / array.length;
    }

    var targetId = await page.target()._targetId;

    await page.goto("https://example.com/", { waitUntil: 'networkidle0', timeout: 60000 });


    let arr1 = [];
    let arr2 = [];
    let [a, b] = [0, 100];


    for (let i = 0; i < 100; i++) {
        let x = y = a;
        let p = Date.now();
        await page.mouse.move(x, y);
        arr1.push(Date.now() - p);
        [a, b] = [b, a];
    }

    //Opens devtools.
    await openDevTools(targetId);


    for (let i = 0; i < 100; i++) {
        let x = y = a;
        let p = Date.now();
        await page.mouse.move(x, y);
        arr2.push(Date.now() - p);
        [a, b] = [b, a];
    }

    console.log(`Without devtools open: ${average(arr1)} ms\nWith devtools open: ${average(arr2)} ms`);

    await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to emulate human like mouse behaviour using physics to generate a more realistic mouse path and follow that path using page.mouse.move(x,y). It is generally 40-50 points if it is not overshooting but it is higher at around 80 points when it overshoots and readjusts. It took around 1 to 2 seconds for the mouse to finish moving which is slow but i thought would not be an issue. Once I opened devtools in the browser before the mouse started moving and realised that the mouse was moving significantly faster(It is like a 8x - 10x improvement). I do not know if this is an issue with puppeteer or CDP but having the mouse move faster without having to set devtools: true would help a lot. This is not the case with page.mouse.down() or page.mouse.up() it only happens with page.mouse.move()

### Expectation

I expect page.mouse.move() execution time to be irrelevant of weather devtools is open or not just like page.mouse.down() or page.mouse.up()

### Reality

It takes the following times for one page.mouse.move() to be executed
Without devtools open: 26.65 ms (It is sometimes lower at around 18 ms and sometimes higher)
With devtools open: 2.51 ms

This is recent average which I got executing the example code. The results for "Without devtools open" are fluctuating a lot but with devtools open it is stable around 2 - 3 ms

### Puppeteer version

20.8.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Interesting, thanks for the report. @jrandolf would you like to investigate this?

**Comment by OrKoN** [comment]
I think it might be due to DevTools disabling the sync to animation frames for events? https://crbug.com/992954

**Comment by OrKoN** [comment]
If that is a case, then it is more of a bug in the DevTools than in Puppeteer (DevTools disables this feature https://chromestatus.com/feature/6192761317359616).

**Comment by jrandolf** [comment]
Indeed, this is precisely what @OrKoN pointed to. I'd follow  https://crbug.com/992954 for more information.
