### ISSUE TITLE
[Bug]: loaderId is missing on pages with hashes

### ISSUE THREAD

**Issue by vladtreny** [puppeteer/puppeteer#10526]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

(async () => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.goto('https://example.com/')
    let test = await page.goto('https://example.com/#/test')
    console.log(test === null) // why is this null?
    console.log(test.status())
})()
```

### Error string

-

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I get `test` is `null`.

However, I expected to receive a response (`HTTPResponse`). 

Is it expected behaviour that we get `null` instead of response object?

Here loaderId is missing on second `goto`
https://github.com/puppeteer/puppeteer/blob/cbf4f2a66912f24849ae8c88fc1423851dcc4aa7/packages/puppeteer-core/src/common/Frame.ts#L163C1-L163C1

### Expectation

Receive `loaderId` in `const response = await client.send('Page.navigate` (see link above)

### Reality

`loaderId` is missing

### Puppeteer version

20.8.0

### Node version

19.7.0

### Package manager

npm

### Package manager version

9.7.2

### Operating system

macOS

**Comment by OrKoN** [comment]
This is expected because hash navigation are [fragment navigations](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-fragid) and they don't have a network request associated with them.
