### ISSUE TITLE
[Bug]:  Error: Failed to launch the browser process! [0710/171141.838038:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by zgame555** [puppeteer/puppeteer#10532]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
      args: [
        '--disable-setuid-sandbox',
        '--no-sandbox',
        '--single-process',
        '--no-zygote',
      ],
      executablePath:
        process.env.NODE_ENV === 'production'
          ? process.env.PUPPETEER_EXECUTABLE_PATH
          : puppeteer.executablePath(),
    })


  - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
```

### Error string

Failed to connect to socket /var/run/dbus/system_bus_socke

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

error in docker

nodejs_puppeteer  |   Puppeteer old Headless deprecation warning:
nodejs_puppeteer  |     In the near feature `headless: true` will default to the new Headless mode
nodejs_puppeteer  |     for Chrome instead of the old Headless implementation. For more
nodejs_puppeteer  |     information, please see https://developer.chrome.com/articles/new-headless/.
nodejs_puppeteer  |     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
nodejs_puppeteer  |     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
nodejs_puppeteer  | 
nodejs_puppeteer  | Error: Failed to launch the browser process!
nodejs_puppeteer  | [0710/171141.838038:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
nodejs_puppeteer  | [0710/171141.974964:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)

### Reality

nodejs_puppeteer  |   Puppeteer old Headless deprecation warning:
nodejs_puppeteer  |     In the near feature `headless: true` will default to the new Headless mode
nodejs_puppeteer  |     for Chrome instead of the old Headless implementation. For more
nodejs_puppeteer  |     information, please see https://developer.chrome.com/articles/new-headless/.
nodejs_puppeteer  |     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
nodejs_puppeteer  |     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
nodejs_puppeteer  | 
nodejs_puppeteer  | Error: Failed to launch the browser process!
nodejs_puppeteer  | [0710/171141.838038:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
nodejs_puppeteer  | [0710/171141.974964:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)

### Puppeteer version

19.7.2

### Node version

16

### Package manager

npm

### Package manager version

9.6.4 

### Operating system

Linux

**Comment by OrKoN** [comment]
It looks like the permissions are not correct on the system that does not allow dbus to create a socket. See https://github.com/puppeteer/puppeteer/issues/10153#issuecomment-1550050802 for a similar issue.
