### ISSUE TITLE
Integrating coverage reports

### ISSUE THREAD

**Issue by mikeal** [puppeteer/puppeteer#1054]
After some recent PR's we've got some test coverage working w/ browserify-istanbul & puppeteer.

* [Initial PR and discussion.](https://github.com/devongovett/browserify-istanbul/pull/42#issuecomment-336689754)
* [Current tests (working if `tap --coverage` is not enabled)](https://github.com/mikeal/gza/blob/coverage/tests/test-browser.js#L14)

There's quite a bit of hacks that we had to pull to get it working and it still doesn't properly. There's also a bug, that looks like it's from the `puppeteer` side, when running tests with `tap --coverage`.

```  not ok Page Error: Error: ReferenceError: cov_vnbsudnht is not defined     at <anonymous>:1:12 ```

And then a big traceback that completely miss-reports the line that must have generated it.

I'm not an expert on how coverage is instrumented for istanbul/nyc/tap so I'm a little out of my depth at this point, but I figured ya'll had thought a bit about coverage and how it might be best integrated.

/cc @bcoe @izs @alexindigo

**Comment by aslushnikov** [comment]
@mikeal This surfaced a while back: https://github.com/GoogleChrome/puppeteer/issues/763#issuecomment-329333667

Not sure how we can help here though.

**Comment by bcoe** [comment]
@aslushnikov, @mikeal and I have been hammering out an approach that works well with Istanbul and puppeteer ... I wonder if we could figure out a way to make Istanbul not step on the toes of puppeteer, while also documenting somewhere how to get test coverage?

**Comment by aslushnikov** [comment]
@bcoe do you care about coverage of the browser-run code? E.g. given the following script, would you care about coverage of the evaluated function?

```js
await page.evaluate(() => {
  alert('foo');
});
```

**Comment by bcoe** [comment]
If I'm understanding how things work; I don't think we care about the coverage of `alert('foo');` -- the code that we're collecting coverage for will have been pre-instrumented by the user running tests (using a tool like webpack or browserify); It might be enough to place `istanbul ignore next` at a few key places in the puppeteer codebase ...

This might also be of interest, and coincidently got submitted today:

https://github.com/istanbuljs/istanbuljs/pull/108

**Comment by mikeal** [comment]
So, the following code.

```javascript
async () => {
  same(clean(document.querySelector('test-two render').textContent), '2')
}
```

When `.toString()` with coverage enabled is: 

```javascript
async()=>{cov_vnbsudnht.f[0]++;cov_vnbsudnht.s[3]++;same(clean(document.querySelector('test-two render').textContent),'2');}
```

Is there a way to dynamically pull this object from the Node.js scope and represent it in headless Chrome?

**Comment by mikeal** [comment]
To clarify, the reason we are getting errors in `evaluate()` is because this code is injected in to all lines in Node.js when coverage is enabled.

When this is then run in `puppeteer` this object doesn't exist.

We should be able to fix this if we can:

* detect when coverage is enabled
* look for references to coverage objects in evaluate strings prior to evaluation.
* crate a representation of the object in the browser that proxies these calls to the same object on the Node.js side.

**Comment by mikeal** [comment]
@bcoe I don't think that we want to ignore these lines. These are lines of the test file, if they end up being dead code that never runs we actually want that in the report.

**Comment by bcoe** [comment]
@mikeal in general the test file should be skipped for instrumentation; I'm a bit confused as to why the lines of the assertion would be instrumented for test. You can see the [ignore logic here](https://github.com/istanbuljs/istanbuljs/blob/master/packages/test-exclude/index.js#L126).

As long as the source-code being passed to `puppeteer` for execution has been instrumented in full, it will have a coverage tracking object populated in it -- I'm a bit confused how the partially covered snippets of code are making their way into `puppeteer` (I was equally curious when I read through #763).

**Comment by aslushnikov** [comment]
> Is there a way to dynamically pull this object from the Node.js scope and represent it in headless Chrome?

@mikeal You can create harness using the [`page.exposeFunction`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction). 

Something along the lines:
```js
// Provide window.countCoverage function in browser context
await page.exposeFunction('countCoverage', coverageProperty => {
  cov_vnbsudnht[coverageProperty]++; // very rough; there should be array index as well
});
// Add harness to browser context that marshals coverage calls to node
await page.evaluate(covid => {
  window['cov_' + covid] = new Proxy({}, {
   // ... proxy property access over to node using the window.countCoverage
}, covid);
```

**Comment by mikeal** [comment]
@bcoe by default the test file lines are included in coverage. In all my other projects I leave this on because it has actually found a lot of bad tests with dead code in them that we thought was checking for something.

> As long as the source-code being passed to puppeteer for execution has been instrumented in full, it will have a coverage tracking object populated in it -- I'm a bit confused how the partially covered snippets of code are making their way into puppeteer (I was equally curious when I read through #763).

So, check out this line of code https://github.com/mikeal/gza/blob/coverage/tests/test-browser.js#L165

The function passed to evaluate is not executed in Node.js, it is `.toString()`'d and then eval'd in the page's context in puppeteer. Unless we skip coverage of the file in question, that function will be instrumented, and that partial instrumentation will fail when eval'd in puppeteer :)

**Comment by mikeal** [comment]
@bcoe is there only one `cov_${id}` object in the entire process? Is there any way to detect the id(s) of these in the Node.js process?

**Comment by alexindigo** [comment]
Ha, now I remember hitting similar issue with Phantom :) But somehow it slipped my mind this time :)

**Comment by mikeal** [comment]
@alexindigo we're making some progress here :) https://github.com/GoogleChrome/puppeteer/issues/1054

**Comment by bcoe** [comment]
@mikeal there will only be one  `cov_${id}` in the entire project, post instrumentation it will have been inserted at the very top of the test file -- I wonder if you could potentially kick this along with the code that's being serialized ... maybe wrap the default behavior?

_edit: if this can be pulled into some modules that work for the generic case, I'd love to add a section on https://istanbul.js.org/._

**Comment by mikeal** [comment]
@bcoe if there's only one of these with the same name for the entire process then we just need to know its name and find a globally accessible reference to it.

With that we could implement this proxying behavior in `puppeteer` and dynamically insert the proxy object when `globals.__coverage___` exists :)

**Comment by mikeal** [comment]
@bcoe are you sure there is one of these objects per process and not per file? https://github.com/istanbuljs/istanbuljs/blob/aae256fb8b9a3d19414dcf069c592e88712c32c6/packages/istanbul-lib-instrument/src/visitor.js#L15

**Comment by alexindigo** [comment]
Here it's just passed with the arguments 
https://github.com/alexindigo/obake/blob/master/lib/phantom.js
although it's somewhat limited use case.

**Comment by alexindigo** [comment]
Does `__coverage__` object has any metadata in puppeter?

**Comment by mikeal** [comment]
I figured out what the `cv_${id}` objects are and where to find them :)

There's an object *per file* and the key can be derived from the filename. The object itself is actually on the global `__coverage__` object but that object has keys of the entire filename so you just need to re-hash it the same way the coverage system does it.

```javascript
let cv_objects = {}
Object.keys(__coverage__).forEach(filename => {
  let hash = createHash('sha1')
  hash.update(filename)
  let key = parseInt(hash.digest('hex').substr(0, 12), 16).toString(36)
  cv_objects[key] = __coverage__[filename]
})
```

**Comment by mikeal** [comment]
I think that with this I can start working on a patch tonight/tomorrow that can detect coverage and make puppeteer's evaluate function "just work" :)

**Comment by mikeal** [comment]
Alright, PR is sent https://github.com/GoogleChrome/puppeteer/pull/1067

Could use some help fixing Typescript globals errors.

**Comment by aslushnikov** [comment]
Summarizing, there are two issues here: 
1. enabling istanbul to work with pptr - important!
2. collecting coverage inside browser context - less critical, orthogonal to [1] and should be handled separately. For the record, there's a https://github.com/gotwarlost/istanbul/issues/254 that might come handy.

Let's scope this issue to cover [1].

I see a few options to enable istanbul with pptr projects:
1. Fix https://github.com/gotwarlost/istanbul/issues/310 and https://github.com/gotwarlost/istanbul/issues/674 - istanbul spoiling function's `toString()` method. It might be that this could be fixed by injecting the following small code snippet in the beginning of istanbul-preprocessed code:
```js
(() => {
  const originalToString = Function.prototype.toString;
  Function.prototype.toString = () => {
    const code = originalToString.call(this);
    return code.replace(/\bcov_[^;]+/g, '');
  }
})();
```
@mikeal [mentioned](https://github.com/GoogleChrome/puppeteer/pull/1067#issuecomment-337425838) this wouldn't work, though I don't understand why. Having this as an istanbul config option seems pretty safe.

2.  Adding `cov_XX &&` prefix to every istanbul coverage trace. This will make the `cov_XX.s[3]++` trace to become `cov_XX && cov_XX.s[3]++`, and might also help to address https://github.com/gotwarlost/istanbul/issues/119

3. Recommend clients to use istanbul's [code ignore comments](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) to guard pptr's evaluations.

@bcoe @gotwarlost @mikeal thoughts?

**Comment by mikeal** [comment]
@aslushnikov

I don't think this is a good path. This actually breaks the coverage we have working in `cappadonna` and will effectively miss the `.execute(code)` that runs in the browser.

I don't see why an istanbul config option would be useful. This breaks coverage detection in many of the blocks you would configure it for, it's better to just opt those files out of coverage if you're concerned about this.

We actually have something that "just works" if you use a higher level tool https://github.com/mikeal/cappadonna/blob/master/index.js#L95

I know @bcoe is working on integrating with v8's coverage utilities but those are still quite far behind and, as far as I understand it, don't include the level of branch coverage we already have working in istanbul.

If that gets to the point we can rely on it then we would just want to change instanbul's function `.toString()` by default.

**Comment by bcoe** [comment]
@aslushnikov :wave:

I did something similar to what you're proposing, to preserve function names (Istanbul's instrumentation at one point broke Function.name). I'm glad we put in the work to rewrite code in such a way that the name was preserved, but it was a hassle and took quite a few iterations to get right... I think that preserving the original toString() would be significantly more complex and I think would also lead to a significant performance hit when running instrumented code.

What I would rather see would be that we work with the V8 team to close the delta on V8 coverage vs. Istanbul coverage.

Newer versions of V8 do support block level coverage, but I think there are still some missing features (I was playing last night, and for instance conditional assignment seemed to not be covered).

I suggest we loop in folks like @schuay, and see if we can't get V8 coverage in Node.js over the finish line, vs. adding any more complexity to Istanbul's parser -- which I'd honestly love to retire.

**Comment by aslushnikov** [comment]
V8 JS coverage sounds great to me, it's way nicer then what istanbul is currently doing. 

> Newer versions of V8 do support block level coverage, but I think there are still some missing features (I was playing last night, and for instance conditional assignment seemed to not be covered).

@bcoe: do you have a list of missing parts? cc @ak239 who lives and breathes V8.

**Comment by bcoe** [comment]
@aslushnikov I've been working from [this testing repo](https://github.com/bcoe/c8) where I intend to document the deltas I find between Chrome's coverage functionality, and the instrumentation folks have become accustomed to with Istanbul. 

Here are a few related issues:

[discussion on v8 issue tracker, regarding adding deatiled coverage to Node.js](https://bugs.chromium.org/p/v8/issues/detail?id=7015).
[discussion on Node.js project, regarding adding better v8 coverage support](https://github.com/nodejs/node/issues/16531)

@ak239 I would definitely be curious to know your thoughts around v8's built in coverage; here's an example of where I think things are lacking (maybe I'm just not doing things properly?):

**code to instrument:**

```js
const foo = true || (9 + 10)
```

**instrumenter output:**

```json
{
  "result": [
    {
      "scriptId": "56",
      "url": "file://test/fixtures/b.js",
      "functions": [
        {
          "functionName": "",
          "ranges": [
            {
              "startOffset": 0,
              "endOffset": 29,
              "count": 1
            }
          ],
          "isBlockCoverage": true
        }
      ]
    }
  ]
}
```

My expectation would be something that indicates that the block `(9 + 10)` has not been executed... In Istanbul there's the construct `branchMap` which tracks specific branches that have been executed. I think my expectation was that Chrome's `detailed` coverage would provide something close to this level of granularity.

**Comment by alexkozy** [comment]
I left comments about teardown and tearup events. As far as I know precise coverage supports block - level coverage and true || (9 + 10) are not separate blocks.
@schuay, please take a look.

**Comment by schuay** [comment]
V8's block coverage doesn't support short-circuiting boolean operators yet, see: https://crbug.com/v8/6660 and the list of known limitations [here](https://docs.google.com/document/d/1wCydi2HEZRF0skDeLb6CH0abZnTyVo5Vz5u-jhwi7es/edit#heading=h.3zjkrm8zma7b). If this is important to you please let us know.

cc @hashseed

**Comment by hashseed** [comment]
We'd love to help with fixing any issues the community feels are important. We have long-term plans to no longer require reload when block-based coverage is enabled, also to solve the issue in Node.js where reload is not possible. That however will require some more time.

**Comment by aslushnikov** [comment]
CSS and JS coverage landed in pptr a few days ago: [`page.coverage`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-coverage)

Please give it a try!

**Comment by felixfbecker** [comment]
@aslushnikov I don't think `page.coverage()` solves the issue of wanting to run `nyc` on the NodeJS side without breaking Puppeteer's `page.evaluate()`

**Comment by c094728** [comment]
Has there been any progress on this issue?  I have this in my code to allow coverage report to run.

        /* due to this issue https://github.com/GoogleChrome/puppeteer/issues/1054,   
         * the istanbul (coverage reporter) will cause error inside page.evaluate throwing exception. 
         * the following "ignore" comment allows istanbul to succeed */
        /* istanbul ignore next */
        var hrefs = await page.evaluate(() => {
            const anchors = document.querySelectorAll('a');
            return [].map.call(anchors, a => a.href);
        });

**Comment by felixfbecker** [comment]
@c094728 I think that is the proper approach, which I have taken too. You can also put the comment right infront of the arrow function to make sure really _only_ the function is ignored, not the `page.evaluate()` call itself:

https://github.com/felixfbecker/semantic-release-firefox/blob/78fb91f59ed2730536fbd986ab081281a9f019be/src/publish.ts#L106-L111

I don't think Puppeteer can or should do something here - the function must be prevented from being instrumented because it is serialised and sent to another context, but there is no way istanbul/nyc could know that, and no way for Puppeteer to tell istanbul/nyc. The developer is the one who should annotate the function, and they can do so with `istanbul ignore` comments, which works fine.
