### ISSUE TITLE
[Bug]: vm2 is deprecated for critical security issue

### ISSUE THREAD

**Issue by matthew-gerstman** [puppeteer/puppeteer#10547]
### Minimal, reproducible example

```TypeScript
npm install -g puppeteer   
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.

```

It looks like a downstream dependency has a critical security issue and needs to be updated. Is it a big lift to update to isolated-vm?
```


### Error string

The library contains critical security issues and should not be used for production!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

_No response_

### Expectation

Not have a critical security issue

### Reality

It has a critical security issue

### Puppeteer configuration

_No response_

### Puppeteer version

20.8.1

### Node version

16.18.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

macOS

**Comment by jcmaunsell** [comment]
See https://github.com/patriksimek/vm2/issues/533:

> Do to security issues that cannot be properly addressed I (XmiliaH) will stop maintaining this library.
> For a replacement look into [isolated-vm](https://www.npmjs.com/package/isolated-vm).

> The problems that piled up are caused by node intercepting calls from the sandbox and therefore arguments not being wrapped in a Proxy. As isolated-vm does create the sandbox on their own and does not rely on the vm module there shouldn't be hooks added by node that causes such issues.

**Comment by OrKoN** [comment]
we do not directly depend on this but via the proxy-agents package that probably needs to support PAC file proxies for downloads of binaries.

**Comment by OrKoN** [comment]
See https://github.com/TooTallNate/proxy-agents/issues/218

**Comment by jcmaunsell** [comment]
Thanks - but could this transitive dependency still pose a security issue for Puppeteer?

**Comment by OrKoN** [comment]
@jcmaunsell unlikely given that it is only used to process proxy settings (that are set by you as a user or your system administrator) and it is only used during installation to download browser binaries.

**Comment by OrKoN** [comment]
anyway we will like to stop supporting pac file proxies as there seem to be no good solution for this.

**Comment by matthew-gerstman** [comment]
Thanks so much for the quick turnaround here!
