### ISSUE TITLE
[Bug]: extremely slow vscode type intellisense

### ISSUE THREAD

**Issue by erfanium** [puppeteer/puppeteer#10545]
### Minimal, reproducible example

create a app with following dependencies:
```json
"dependencies": {
    "@tsconfig/node18": "^18.2.0",
    "@types/node": "^20.4.1",
    "puppeteer": "^20.8.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6"
  }
```

create a app.ts file like this
```ts
import { launch } from 'puppeteer';
```

open type definition for `launch` using `Go to Definition`.
go to type definition for `PuppeteerLaunchOptions` using `Go to Definition`.

now you got a completely hanged vscode

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

normal vscode type intellisense

### Reality

slow and non-stable vscode type intellisense

### Puppeteer version

20.8.1

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by OrKoN** [comment]
It is blazingly fast for me in vscode. Sounds like a VSCode issue?

**Comment by erfanium** [comment]
@OrKoN maybe. but i have this problem only with `puppeteer` package in my project.
i'll continue investigating this
