### ISSUE TITLE
Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!

### ISSUE THREAD

**Issue by ysaurabh3** [puppeteer/puppeteer#10556]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
```

### Error string

```
Error: Timed out while waiting for the WS endpoint URL
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Using it inside docker image.
Platform / OS version: Rocky Linux 8 running on GCP

I have tried multiple things
- running `node node_modules/puppeteer/install.js` manually inside docker image.
- verify all the dependencies are present for chrome with the help of `ldd chrome`

### Expectation

Get the browser instance

### Reality

It throws error

```
TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!
    at ChromeLauncher.launch (/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:153:23)
```

### Puppeteer version

20.8.2

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Could you turn on the dumpio attribute and provide the browser log?

**Comment by RedChops** [comment]
I'm running in to this inside a Firebase Function, my error message is similar:

```
Error: Unable to launch browser, error message: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!
    at Cluster.<anonymous> (/workspace/node_modules/puppeteer-cluster/dist/Cluster.js:119:23)
    at Generator.throw (<anonymous>)
    at rejected (/workspace/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
```

**Comment by rohinthr** [comment]
Adding timeout while launching the puppeteer will solve this issue.
Try adding `timeout:0` in launching options.

**Comment by arijit-itobuz** [comment]
is there any way to manually trigger TimeoutError ?

**Comment by feelthecoder** [comment]
I'm getting the same error.

**Comment by Zelfapp** [comment]
Same issue, however, I will note that adding `timeout: 0` as @rohinthr suggested, seems to solve it so far, however, I still need to do more testing to confirm.

On `puppeteer v 21.1.1`. Using google cloud function gen2 `onObjectFinalized` trigger with 16GiB memory, 4 cpu, and 120 second timeout. 

On first, and intermittently on subsequent runs of this Cloud Storage trigger function, I am getting `TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!`. So, this is still very much an issue and unless someone can point out in my code something I'm missing, I am waiting for the browser to close before the function completes, etc.

In `package.json` I had to add:

```json
"scripts": {
  "gcp-build": "node node_modules/puppeteer/install.js"
}
```

And then at root of project I added the `.puppeteerrc.cjs config file`:

```javascript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
    // Changes the cache location for Puppeteer.
    cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

**Puppeteer code:**

```javascript
const browser = await puppeteer.launch({
    headless: 'new',
    timeout: 0,
})

const page = await browser.newPage()

// Load the html file that triggered onObjectFinalized as string and pass to setContent
// So, in my use case I'm not even loading a website with puppeteer, just passing html.

await page.setContent(html, { waitUntil: 'domcontentloaded' })
await page.emulateMediaType('screen')

const PDF = await page.pdf({
    path: `/tmp/${pdfFilename}`,
    margin: { top: '.5in', right: '.5in', bottom: '.5in', left: '.5in' },
    printBackground: true,
    format: 'A4',
})

await browser.close()
```

**Comment by supervishman** [comment]
I'm getting the same error. Can't seem to resolve it, even after adding the puppeteerrc

**Comment by JamesMGreene** [comment]
Running into the same thing more commonly all of a sudden while running on GitHub Actions. 😭

**Comment by zhang2118** [comment]
Running into the same issue. Tried setting the timeout to 0, so far the error hasn't come up again for the past few days. puppeteer-core version 21.3.8.

**Comment by astrojuanlu** [comment]
We have been suffering this error intermittently on Read the Docs for the past few weeks.

**Comment by kriskhoury** [comment]
Has anyone found a fix for this? I have been experiencing this on and off for months. I'm still on 20.9.0.

**Comment by vstets23** [comment]
Same issue with AWS Lambda, function just can open a valid URL with Puppeteer

**Comment by OrKoN** [comment]
The error indicates that the browser failed to start up on the system within 30sec. It might indicate missing dependencies or not sufficient memory/cpu (often in Docker/Cloud environments). See https://pptr.dev/troubleshooting for some tips.

**Comment by marcindulak** [comment]
> The error indicates that the browser failed to start up on the system within 30sec. It might indicate missing dependencies or not sufficient memory/cpu (often in Docker/Cloud environments). See https://pptr.dev/troubleshooting for some tips.

My impression is that a more likely reason of this failure inside docker is not a lack of resources, but dbus issues. See
https://github.com/nodejs/help/issues/3220#issuecomment-1228342313 for a `--remote-debugging-port` workaround, which solves the problem for me. Is there somewhere a supported, ci tested and maintained (by puppeteer team) dockerfile of puppeteer with a dbus configuration?

**Comment by OrKoN** [comment]
@marcindulak yeah, see https://pptr.dev/guides/docker which has dbus configured ([source](https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile)). We run a smoke test on GitHub Actions on every commit https://github.com/puppeteer/puppeteer/actions/runs/8375656558/job/22933484768

**Comment by mansi151** [comment]
is anyone can find solution ?

**Comment by jasonc624** [comment]
bump, need solution

**Comment by EDSprog** [comment]
bump, need solution

**Comment by williambaele** [comment]
Just solved this issue on my side. 

I am running my app on a Ubuntu VPS and I was missing some packages

Just followed this article: https://ploi.io/documentation/server/how-to-install-puppeteer-on-ubuntu

Cheers

**Comment by fuelkoy** [comment]
@Zelfapp are you by any reason not awaiting the function containing the puppeteer launch etc.? I came accros this issue prior where not awaiting the function caused this error to appear as in Firebase Functions (v1 and v2) the function excecution stops when the function is ready and any "hanging" procedures can be / will be timed out. 
For AWS I don't know if the same applies. Should be checked tho.

Just throwing this here. Could resolve the issue for someone.

**Comment by kyungseopk1m** [comment]
This issue was very troublesome for me.
It would proceed normally, but occasionally the error would occur again.
So, I added the following code before the page.goto and was able to resolve the problem:
page.setDefaultNavigationTimeout(0);

**Comment by NAUGHTY-BRAND** [comment]
m running it on render solution will be highly appreciated

**Comment by NAUGHTY-BRAND** [comment]
> facing the same issue in windmill platform too

i solved it

**Comment by leozmartini** [comment]
I encountered the same error because I was trying to load an extension with an invalid path. Double-checking the path to the extension fixed the issue for me. Hope this helps anyone facing the same problem!

**Comment by RobJJ** [comment]
Bump: Running into this timeout problem now too. 
My functions have been working perfectly for the past few weeks on a chosen url, but for some reason im now unable to launch the browser.. have tried the solutions mentioned above.
