### ISSUE TITLE
[Bug]: Error running puppeteer within GCP Cloud Run jobs

### ISSUE THREAD

**Issue by MylesNeloms** [puppeteer/puppeteer#10558]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

async function webscraper () {
    const browser = await puppeteer.launch({
        headless: "new",
        args: ["--no-sandbox", "--disable-setuid-sadbox"],
        // args: ["--window-size=1920,1080"],
      });
      const ibContext = await browser.createIncognitoBrowserContext();
      const page = await ibContext.newPage();
      await page.setViewport({width: 1920, height: 1080});

      await page.goto("https://www.forex.com/en-us/market-analysis/economic-calendar/", {waitUntil: "load"});

      await page.waitForSelector(".icon-filter").then(() => console.log("Found the filter"));
      browser.close();
    }

    webscraper().catch(err => {
  console.error(err);
  process.exit(1); // Retry Job Task by exiting the process
});
```

### Error string

Waiting for selector... failed: Waiting failed: 30000ms exceeded at Timeout.<anonymous>

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Originally, I deployed a webscraper via Google Cloud Functions. Recently, this functionality stopped working and instead producing the above error.

I found a way around this by upgrading to the newest puppeteer & node 18. But this resulted in a new error noting that the instance could not find chrome. Checking the puppeteer docs, I found that implementations with cloud functions are not entirely recommended. Instead, they ask that we use CloudRun to ensure that all dependencies are installed in order from launching the chrome browser.

If I download the debian dependencies listed here[1], I get an error noting that the browser could not be launched. Even building my job with the base image of "ghcr.io/puppeteer/puppeteer:20.8.2", I receive an error noting that the chrome browser cannot be found:

======================

If I add an ".puppeteerrc.cjs" file to my job directory, I finally received the 30 second timeout:
------error below------
TimeoutError: Waiting for selector `.icon-filter` failed: Waiting failed: 30000ms exceeded at Timeout.<anonymous> (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:71:32) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7)
------EOF------

-----My dockerfile-----
FROM ghcr.io/puppeteer/puppeteer:20.8.2

COPY package*.json ./

RUN npm i

COPY . .

ENTRYPOINT ["node", "index2.js"]
-----EOF-----

-----Also tried-----
FROM ghcr.io/puppeteer/puppeteer:latest

USER root

RUN apt-get update \
    && apt-get install -y apt-utils ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 \
    libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 \
    libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
    libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
    libxss1 libxtst6 lsb-release wget

RUN apt-get -y install sudo

RUN sudo apt-get install -y xdg-utils

COPY package*.json ./

RUN npm install -g npm@9.8.0

RUN npm i

COPY . .

ENTRYPOINT ["node", "index.js"]
-----EOF-----

------Packages.json-----
{
    "name": "jobs",
    "version": "1.0.0",
    "description": "Node.js sample for Cloud Run jobs",
    "main": "index.js",
    "scripts": {
        "start": "node index.js"
    },
    "author": "Google LLC",
    "license": "Apache-2.0",
    "dependencies": {
        "firebase-admin": "^10.2.0",
        "puppeteer": "^19.2.0"
    }
}
------EOF-----

[1] GCP Puppeteer example: https://codelabs.developers.google.com/codelabs/cloud-starting-cloudrun-jobs#3

[MinimumRepro.zip](https://github.com/puppeteer/puppeteer/files/12065055/MinimumRepro.zip)

### Expectation

I expect the script to run on GCP using the puppeteer base image as it does on my local computer.

### Reality

I receive an error 30 seconds after job execution.

### Puppeteer version

20.8.2

### Node version

18

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by MylesNeloms** [comment]
Apologies for the misguiding link. I grabbed the dependencies from the troubleshooting links in puppeteer docs

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by OrKoN** [comment]
Could you please format the issue properly? it's difficult to read. Also, make sure that after you modify the docker image, that you install the app into the folder where Puppeteer is installed and switch back to the same non-root user.

**Comment by MylesNeloms** [comment]
Thanks I will try this and update soon. Apologies for the formatting, I believe markup may have reformatted my issue text.

**Comment by OrKoN** [comment]
`waitForSelector` is clearly a different issue and the most likely the element does not exist (for example, the  URL you test with is only available locally or if it is a third party website they block/render differently for your server script). Please double check that the content of the page that you expect is actually there.

**Comment by wlhong-allo** [comment]
I spent 2 days and got it working now, check this out:

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-google-cloud-run

You need to enable Google Cloud Run to always allocate dedicated CPU for you otherwise the process will exit as soon as a response is returned without waiting for the puppeteer event to come back.

As of current GCP web UI, goto your cloud run service > Edit & Deploy New Revision > under "Billing" section, select "Instance-based" instead of "Request-based" 

Note that it impact your GCP cost because now there are CPU resources always dedicated for your service:

https://cloud.google.com/run/docs/configuring/billing-settings
