### ISSUE TITLE
[Bug]: Google Translate Feature is not working in headless=false

### ISSUE THREAD

**Issue by honestydeveloper** [puppeteer/puppeteer#10557]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
puppeteer
  .launch({
    headless: false,
    userDataDir: "C:\\puppeteer-test",
    args: [`--proxy-server=192.168.41.196:6094`],
    ignoreDefaultArgs: [
      "--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints",
    ],
  })
  .then(async (browser) => {
    // Create a new page
    const page = await browser.newPage();
    await page.setRequestInterception(true);

    await page.authenticate({
      username: "proxy_user",
      password: "proxy_pass",
    });

    page.on("request", (req) => {
      console.log(req.url(), "\n");
      req.continue();
    });
  });
```

### Error string

No error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Hi, 
Hope doing you well.
I have created the puppeteer app with GUI and tested the translate feature but it didn't work.
I will appreciate if you could please help me.
Thank you.

### Expectation

I want to make the translate feature should be worked in headless=false mode.

### Reality

I have uploaded the two screens.
![2](https://github.com/puppeteer/puppeteer/assets/42817736/cdea6e91-6247-4eb3-a352-bde929ef7dec)
![1](https://github.com/puppeteer/puppeteer/assets/42817736/734392ff-0b73-405f-93ff-6eaeeac4e7ae)

### Puppeteer version

20.8.2

### Node version

18.13.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Windows

**Comment by OrKoN** [comment]
We currently don't support this and don't plan on supporting it. You could try using regular Google Chrome binaries that have this feature.
