### ISSUE TITLE
[Bug]: PDF Quality , width and UI alignment issues 

### ISSUE THREAD

**Issue by Meenakshise** [puppeteer/puppeteer#10561]
### Minimal, reproducible example

```TypeScript
pupeteer code 
const express = require('express');
const puppeteer = require('puppeteer');

const app = express();

app.get('/generate-pdf', async (req, res) => {
    try {
        const browser = await puppeteer.launch();
        const page = await browser.newPage();
       // await page.setViewport({ width: 1200, height: 800 });
        // Perform any Puppeteer actions (e.g., navigate to a page, generate PDF, etc.)
        await page.goto('http://localhost:8080/');
       // await page.waitForSelector('.canvasjs-chart-container');

        await page.pdf({
            format: 'A4',
            margin: {
                top: '20px',
                right: '50px',
                bottom: '50px',
                left: '50px',
            },
           // scale: 1.0, // Adjust the content scaling if needed
            path: 'output.pdf'
        });

        await browser.close();

        res.send('PDF generated successfully');
    } catch (error) {
        console.error(error);
        res.status(500).send('An error occurred');
    }
});

app.listen(3000, () => {
    console.log('Server started on port 3000');
});
```

### Error string

no error pdf quality and width 

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

Hi, 
If you look at the below image it has legend section on the right. And the chart looks like neat. 
![image](https://github.com/puppeteer/puppeteer/assets/5516586/8c9195a6-15e1-4c33-b6b9-de2a5ecbc215)

I tried to generate the pdf for the same and please look at the pdf and see how it got generated. 
[output.pdf](https://github.com/puppeteer/puppeteer/files/12068378/output.pdf)
Legend went down and the PDF size looks like it has shrinked. 

### Expectation

PDF should be same as the html view. Please let me know what is wrong here. And even the alignments also 

### Reality

PDF quality and width issues + UI alignment issues 

### Puppeteer version

20.8.2

### Node version

v16.18.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by OrKoN** [comment]
Please provide a complete example including the HTML/CSS page and Puppeteer script. Make sure that printing using the built-in print dialog in the regular browser yields the desired result. If that does not work or the result is different in Puppeteer, please file a bug at crbug.com as the browser is responsible for PDF generation.
