### ISSUE TITLE
Failed to launch the browser process! 

### ISSUE THREAD

**Issue by asmithv** [puppeteer/puppeteer#10571]
**Suddenly started getting this error while using the puppeteer**

web: /home/webapp/.chromium-browser-snapshots/linux-1083080/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
web: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
web: at onClose (/var/app/current/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
web: at Interface.<anonymous> (/var/app/current/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
web: at Interface.emit (events.js:412:35)
web: at Interface.emit (domain.js:475:12)
web: at Interface.close (readline.js:530:8)
web: at Socket.onend (readline.js:254:10)
web: at Socket.emit (events.js:412:35)
web: at Socket.emit (domain.js:475:12)
web: at endReadableNT (internal/streams/readable.js:1333:12)
web: at processTicksAndRejections (internal/process/task_queues.js:82:21)
web: alunched browser
web: TypeError: Cannot read property 'newPage' of undefined

**Comment by OrKoN** [comment]
See https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux
