### ISSUE TITLE
[Bug]: InstalledBrowser object doesn't have full path to Chromedriver (`@puppeteer/browsers`)

### ISSUE THREAD

**Issue by christian-bromann** [puppeteer/puppeteer#10587]
### Minimal, reproducible example

```TypeScript
import cp from 'node:child_process'
import { install, Browser } from '@puppeteer/browsers'

const chromedriver = await install({
    cacheDir,
    buildId,
    browser: Browser.CHROMEDRIVER
})
cp.spawn(chromedriver.path, [...]) // fails
```

### Error string

Error: spawn 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

The `InstalledBrowser` object is defined as:

```ts
export type InstalledBrowser = {
  path: string;
  browser: Browser;
  buildId: string;
  platform: BrowserPlatform;
};
```

As a developer I would assume that `path` would give me the absolute path to the chromedriver binary so that `cp.spawn(chromedriver.path, [...])` would be possible. However that is not the case, it returns the following:

`/path/to/cacheDir/chromedriver/mac_arm-115.0.5790.98`

leaving the actual driver at:

`/path/to/cacheDir/chromedriver/mac_arm-115.0.5790.98/chromedriver-mac-arm64/chromedriver`

### Expectation

I expect to get the full path of the Chromedriver binary.

### Reality

I only get a subset of the path which requires me to find out in which directory the driver is stored.

### Puppeteer version

v20.8.3

### Node version

v20.2.0

### Package manager

npm

### Package manager version

NPM

### Operating system

macOS

**Comment by OrKoN** [comment]
path on the installedBrowser refers to the root of the installation directory. https://pptr.dev/browsers-api/browsers.computeexecutablepath should be used to find the executable within the installation folder. Added a PR to clarify this in the documentation https://github.com/puppeteer/puppeteer/pull/10588

We should consider also adding the executable path attribute here.

**Comment by christian-bromann** [comment]
Thanks for the quick response. I agree to all of that.
