### ISSUE TITLE
[Feature]: Have the issue with puppeteer events

### ISSUE THREAD

**Issue by chandanray876** [puppeteer/puppeteer#10596]
### Feature description

I have try to create a co-browse app with using puppeteer and it runs also but, I have got the speed issue.
Its running very slow like I am using socket to send event to puppeteer, event firing is good but puppeteer listing to event is very slow.

This is the code I have write to run puppeteer:-

import isRoot from "is-root";
import path from "path";
import { fileURLToPath } from "url";
import puppeteer from "puppeteer";

const dirname = path.dirname(fileURLToPath(import.meta.url));

const eventBlacklist = ["page", "background_page"];

export const cdp = async (page, options, isScroll = false) => {
  const client = await page.target().createCDPSession();

  client.send("Page.setDownloadBehavior", {
    behavior: "deny",
  });
  let frameCount = 0;
   client.send("Page.startScreencast", {
    format: "jpeg",
    maxWidth: options.width,
    maxHeight: Math.trunc(options.width / options.ratio),
  });

  client.on("Page.screencastFrame", async ({ data, sessionId }) => {
    
    global.io.to(options.token).emit("imageData", { data: data });
    frameCount++;

    client.send("Page.screencastFrameAck", { sessionId }).catch(() => {});
  });
};

export default async (options) => {
  const width = options.width;

  const height = Math.trunc(width / options.ratio); 

  const browser = await puppeteer.launch({
    args: [
      "--block-new-web-contents",
      "--disable-breakpad",
      "--disable-dev-shm-usage",
      `--file-url-path-alias=/=${path.join(dirname, "forbidden")}/`,
      "--hide-crash-restore-bubble",
      "--kiosk",
      "--ignore-gpu-blocklist",
      "--no-crash-upload",
      "--no-default-browser-check",
      "--no-first-run",
      "--no-recovery-component",
      isRoot() ? "--no-sandbox" : "",
      isRoot() ? "--no-zygote" : "",
      "--noerrdialogs",
      "--suppress-message-center-popups",
      `--user-data-dir=chrome-user-data/${options.token}`,
      `--window-size=${width},${height + 90}`,
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--single-process",
      "--ignore-gpu-blocklist",
      "--enable-gpu-rasterization",
      "--enable-oop-rasterization",
      "--disable-gpu-driver-bug-workarounds",
      "--enable-accelerated-video-decode",
      "--use-gl=desktop",
      "--enable-zero-copy",
      "--proxy-server='direct://'",
      '--proxy-bypass-list=*'
    ],
    defaultViewport: { width, height },
    executablePath: process.env.CHROMIUM_EXECUTE_PATH || undefined,
    headless: 'chrome',
    ignoreDefaultArgs: [
      "--disable-popup-blocking",
      "--enable-automation",
      "--mute-audio",
    ],
  });

  const page = (await browser.pages())[0];
  await page.setUserAgent(options.userAgent);

  browser.on("targetcreated", async (target) => {
    if (!eventBlacklist.includes(target.type())) {
      return;
    }

    await page
      .goto(target.url())(await target.page())
      .close();
  });

  return { browser, page };
};

I have goal to run at least 1000 session concurrently, but right now hardly 2-3 session is running only.
Can you Please help me with this issue.

**Comment by OrKoN** [comment]
It does not look like a feature request. Also, I am not sure if running thousands of sessions is feasible. If you believe there is a bug, please re-open with all details and a minimal reproducible example.
