### ISSUE TITLE
BiDi waitForNavigation waits both for a navigation and a fragment navigation

### ISSUE THREAD

**Issue by juliandescottes** [puppeteer/puppeteer#10604]
Trying to fix navigation tests for Firefox with BiDi, I noticed that we use Promise.all in the following helper: https://github.com/puppeteer/puppeteer/blob/4a3b8b2d9eda2941769b53dad48b92d9c027d495/packages/puppeteer-core/src/common/bidi/Frame.ts#L223-L242

That seems odd, I guess we should use a race instead and resolve whenever a load or a fragment navigation happens, not both?

**Comment by juliandescottes** [comment]
cc @Lightning00Blade

**Comment by Lightning00Blade** [comment]
Closed by #10671. 
There is still some work to do related to `navigationAborted` and `navigationFailed`, but happy path should work as expected.

**Comment by juliandescottes** [comment]
Thanks for working on all those issues!
