### ISSUE TITLE
Error when clicking on Shadow DOM element

### ISSUE THREAD

**Issue by vitalets** [puppeteer/puppeteer#1061]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: OSX 10.11.6
* URLs (if applicable):

**What steps will reproduce the problem?**
```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://chrisbateman.github.io/guide-to-web-components/demos/shadow-dom.htm');
await page.click('#demo1::shadow p');
await browser.close();
```
**What is the expected result?**
No errors, element will be clicked.

**What happens instead?**
Element is not clicked, error in console:
```
(node:65830) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Node is detached from document
```
**But this code is working well:**
```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://chrisbateman.github.io/guide-to-web-components/demos/shadow-dom.htm');
await page.evaluate(() => document.querySelector('#demo1::shadow p').click());
await browser.close();
```

**Comment by ebidel** [comment]
Hi @vitalets. `::shadow` is deprecated (https://www.chromestatus.com/feature/6750456638341120) so you should not be relying on it as a selector.

Please upvote https://github.com/GoogleChrome/puppeteer/issues/858 to add shadow piercing features to the API.
