### ISSUE TITLE
[Bug]: CDPPage doesn't exist for Target with page type

### ISSUE THREAD

**Issue by eeskov** [puppeteer/puppeteer#10613]
### Minimal, reproducible example

```TypeScript
const puppteer = require('puppeteer');

puppteer.launch({
    headless: false,
    channel: 'chrome',
}).then(async browser => {
    const page = (await browser.pages())[0];
    await page.goto('https://www.example.com');
    const iterations = 10;
    const pagesPerIteration = 10;
    const urls = ['https://www.example.com', 'https://www.google.com', 'https://www.bing.com']; // more reproducable if open different pages
    for (let i = 0; i < iterations ; i++) {
        for (let j = 1; j <= pagesPerIteration; j++) {
            await page.evaluate((_urls) => {
                window.open(_urls[Math.floor(Math.random() * _urls.length)]);
            },urls);
        }
        await new Promise(resolve => setTimeout(resolve, 1000)); // to avoid any race conditions

        const pages = await browser.pages();
        const targets = browser.targets().filter(target => target.type() === 'page');

        if(targets.length !== pages.length){
            throw new Error('target without page');
        }

        while((await browser.pages()).length > 1){ // close all pages except the first one to avoid memory leak
            await (await browser.pages())[1].close();
        }
    }
})
```

### Error string

target without page

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I use automation for pages, that are opened by the user.
After upgrading to Puppeteer 20, I notice sometimes I can't perform it.
All targets are still available, but puppeteer CDPPage doesn't exist for some of them. It occurs randomly.

```
if(target.type() === 'page'){
  await target.page() // will return null
}
```

it doesn't like it is a race. I have an infinite loop, and a CDPPage is never created for these targets.

### Expectation

```
const pages = await browser.pages();
const targets = browser.targets().filter(target => target.type() === 'page');
page.length === targets.length 
```
page should exist for all targets wich type is page

### Reality

sometimes target with type page exists but the page is not

### Puppeteer version

20.9.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
I think the problem is in the line:

```
await new Promise(resolve => setTimeout(resolve, 1000)); // to avoid any race conditions
```

the pages call is asynchronous and it will wait for the newly created pages to initialize, that is if the newly created page has been detected. 1000ms does not seem to be enough for that. You need to use a higher timeout or explicitly wait for the right number of targets before calling the pages.

**Comment by eeskov** [comment]
I can increase this to hours, still will not be available. I've added this only for repro. 
In my app, I use `waitForTarget ` in an infinite loop to track targets.

**Comment by eeskov** [comment]
import * as puppeteer from 'puppeteer';

async function main() {
    const browser = await puppeteer.launch({
        headless: false,
        channel: 'chrome',
    });

    const page = (await browser.pages())[0];
    await page.goto('https://www.example.com');
    const iterations = 20;
    const pagesPerIteration = 10;
    const urls = ['https://www.example.com', 'https://www.google.com', 'https://www.bing.com']; // more reproducable if open different pages
    for (let i = 0; i < iterations ; i++) {
        for (let j = 1; j <= pagesPerIteration; j++) {
            await page.evaluate((_urls) => {
                window.open(_urls[Math.floor(Math.random() * _urls.length)]);
            },urls);
        }
        await new Promise(resolve => setTimeout(resolve, 1000)); // to avoid any race conditions

        const pages = await browser.pages();
        const targets = browser.targets().filter(target => target.type() === 'page');

        if(targets.length !== pages.length){
            throw new Error('target without page');
        }

        while((await browser.pages()).length > 1){ // close all pages except the first one to avoid memory leak
            await (await browser.pages())[1].close();
        }
    }
    await browser.close();
}

main();

typesciprt code

**Comment by OrKoN** [comment]
non-flaky version:

```
const puppteer = require('puppeteer');

puppteer.launch({
  headless: false,
}).then(async browser => {
  const page = (await browser.pages())[0];
  await page.goto('https://www.example.com');
  const iterations = 10;
  const pagesPerIteration = 10;
  const urls = ['https://www.example.com', 'https://www.google.com', 'https://www.bing.com']; // more reproducable if open different pages
  for (let i = 0; i < iterations; i++) {
    for (let j = 1; j <= pagesPerIteration; j++) {
      await page.evaluate((_urls) => {
        window.open(_urls[Math.floor(Math.random() * _urls.length)]);
      }, urls);
    }
    await browser.waitForTarget(() => browser.targets().filter(target => target.type() === 'page').length === pagesPerIteration + 1);
    const pages = await browser.pages();
    const targets = browser.targets().filter(target => target.type() === 'page');

    if (targets.length !== pages.length) {
      throw new Error('target without page');
    }

    for (const p of (await browser.pages())) {
      if (p !== page) {
        await p.close();
      }
    }
  }
})
```

**Comment by eeskov** [comment]
@OrKoN Thanks a lot, for pointing to this.

I used something like this.
```
const foundTargets = new Set();
for(let j = 1; j<= pagesPerIteration; j++){
        const target = await browser.waitForTarget(target => foundTargets.has(target._targetId) === false);
        foundTargets.add(target._targetId);
}
```
and it's not equal to
```
await browser.waitForTarget(() => browser.targets().filter(target => target.type() === 'page').length === pagesPerIteration + 1);
```

thank you very much, sorry for disturbing
