### ISSUE TITLE
BiDi frameNavigated should not only rely on fragmentNavigated

### ISSUE THREAD

**Issue by juliandescottes** [puppeteer/puppeteer#10626]
https://github.com/puppeteer/puppeteer/blob/4568f1bba50db353fafc279ff64be58bcded13f0/packages/puppeteer-core/src/common/bidi/Page.ts#L87

I was checking the failure for `Evaluation specs Page.evaluate should work right after framenavigated`, it seems we expect a FrameNavigated event for this test, which according to the code linked above, means a fragmentNavigated event. But the test is not doing a fragment navigation, and I don't think we should emit the event in this case?

Not sure there is a 1:1 mapping between puppeteer's frameNavigated and fragmentNavigated?

**Comment by Lightning00Blade** [comment]
Here is a list of test that require this:
`Page.waitForNavigation - > should work when subframe issues window.stop()` (Note: Does not work in Chrome as well)
`Frame Management should support framesets`
`Frame Management should detach child frames on navigation`
`Frame Management should send "framenavigated" when navigating on anchor URLs`
`Frame Management should send events when frames are manipulated dynamically`
`Page.evaluate should work right after framenavigated`
