### ISSUE TITLE
[Bug]: Html header and footer issue, If we setting html header only , it always show default htmlfooter on pdf page

### ISSUE THREAD

**Issue by karmegams02** [puppeteer/puppeteer#10623]
### Minimal, reproducible example

```TypeScript
PuppeteerSharp.PdfOptions pdfOptions = new PuppeteerSharp.PdfOptions();
pdfOptions.DisplayHeaderFooter = true;
pdfOptions.PrintBackground = true;
pdfOptions.MarginOptions.Left = "40";
pdfOptions.MarginOptions.Right = "40";
pdfOptions.MarginOptions.Bottom = "40";
pdfOptions.MarginOptions.Top = "40";
string text= await ImageUrlToBase64( "https://i.pinimg.com/564x/59/32/29/593229739184504afd9507cc42a9cb86.jpg");
pdfOptions.HeaderTemplate = "<span style=\"font-size: medium; \">Karmegam</span>";
await page.GoToAsync("https://www.google.com/");
await page.PdfAsync("sample.pdf", pdfOptions);
```

### Error string

show default header and footer.

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

If we setting html header, I expect only header only will be add in pdf document

### Reality

without setting html footer or header, it will print default value on pdf

### Puppeteer version

10.1.2

### Node version

we using console application

### Package manager

npm

### Package manager version

10.1.2

### Operating system

Windows

**Comment by OrKoN** [comment]
are you using puppeteer-sharp? please report the issue there https://github.com/hardkoded/puppeteer-sharp if there is a pdf rendering bug, please report directly to crbug.com for Chromium.
