### ISSUE TITLE
[Bug]: Chinese characters showing as question marks

### ISSUE THREAD

**Issue by wanming1994** [puppeteer/puppeteer#10627]
### Minimal, reproducible example

```TypeScript
margin: {
                top: "26mm", bottom: "14mm", left: "14mm", right: 0,
            },
            format: "A4",
            displayHeaderFooter: true,
            omitBackground: true,
            webkit_print_color_adjust: "exact",
            printBackground: true,
            encoding: 'utf-8'
```

### Error string

Chinese garbled characters

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

![image](https://github.com/puppeteer/puppeteer/assets/33286497/ec8148fb-72ea-4b75-b36a-fee45b658185)

### Expectation

How to solve the problem of Chinese garbled characters? The same text appears normally on top, but garbled characters appear below

### Reality

How to solve the problem of Chinese garbled characters? The same text appears normally on top, but garbled characters appear below

### Puppeteer version

20.9.0

### Node version

16.16.0

### Package manager

npm

### Package manager version

8.11.0

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
Please provide a sample of the text (or part of the html) that is being `garbled`. As we can't verify it without it.
Keep in mind that we only call the browsers internal PDF printing. Are you seeing the same behavior when you try to print from Chrome? Also can you try with a slightly older version of Puppeteer 20.7.2, as that includes an older browser.
