### ISSUE TITLE
[Bug]: Page.goto() method returning null outside cases listed on docs

### ISSUE THREAD

**Issue by gyr1967** [puppeteer/puppeteer#10636]
### Minimal, reproducible example

```TypeScript
for (url of urls) {
  resp = await tab.goto(url, {
    waitUntil: 'domcontentloaded',
  })
  console.log(resp)
  // do other things
}
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

URLs come from users so can be to any site, sometimes there are two URLs in a row that are identical. Tried locally and on AWS. (Tried on most recent puppeteer version, same thing)

### Expectation

Expecting a non-null response except when URL is same but with different hash, or about:blank. As stated in docs [here](https://pptr.dev/api/puppeteer.page.goto/). The link in question is [this one](https://www.dynastyautodetailing.net/)

### Reality

When given a URL that is the same as previous, it can return null. The two cases where this happens in the docs don't include this case.

### Puppeteer version

20.9.0

### Node version

18.12.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by gyr1967** [comment]
tried on 20.9.0, same deal

**Comment by OrKoN** [comment]
Unable to reproduce:

```
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();

  const page = await browser.newPage();

  const url = 'https://www.dynastyautodetailing.net';

  console.log(await page.goto(url, {
    waitUntil: 'domcontentloaded',
  }));
  console.log(await page.goto(url, {
    waitUntil: 'domcontentloaded',
  }))

  await browser.close();
})();
```
