### ISSUE TITLE
[Bug]: Puppeteer Freezes when i put chrome on background , when i get it back to foreground script execution continues

### ISSUE THREAD

**Issue by aarifkara** [puppeteer/puppeteer#10639]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer')
const { exec, execSync } = require('child_process')
const fs = require('fs')
const axios = require('axios')

async function browserStart(useProxy, proxyData, browserPath) {

    const komut = `rd /s /q ${browserPath}`
    let komut1

    if(useProxy == true){

        komut1 = `"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" --disable-gpu --disable-renderer-backgrounding --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --user-data-dir=${browserPath} --remote-debugging-port=30009 --start-maximized --proxy-server=http://${proxyData.proxyHost}:${proxyData.proxyPort}`

    } else{

        //

    }

    if (fs.existsSync(browserPath)) {

        execSync(komut)

    }

    exec(komut1)

}

/*
other functions
*/

(async () => {

    const browserPath = "C:\\Users\\x\\Desktop\\x\\browserProfile\\1"
    const useProxy = true

    if(useProxy == true){

        proxyData = await getProxy(useProxy)
        await browserStart(useProxy, proxyData, browserPath)
    
    } else{
    
        //
    
    }

    endPoint = await getEndPoint()

    browser = await puppeteer.connect({ browserWSEndpoint: endPoint })

    const pages = await browser.pages()
    const page = pages[0]

    /*
    other code ...
    */

}]
```

### Error string

TypeError: Cannot read properties of undefined (reading 'click')

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

first of all, I filled the "Error string" field because I could not leave it blank. but I don't think Error is related to the problem.

When I launch my script more than once, the background chrome browsers freeze or slow down, if I click on any of the background chrome browsers, that chrome browser goes back to normal.

this problem was previously shared in the link below:

https://github.com/puppeteer/puppeteer/issues/4131

but no solution worked for me,

also the first time I had this problem using "--disable-backgrounding-occluded-windows" worked but 2 days have passed and I have the same problem again.
The only thing that changed in 2 days was to update my chrome version from 114 to 115 but I don't think it's related to that.

### Expectation

When i run the above script and have chrome in foreground , the script does its intended work , i expect the script to do the same when I put chrome in background.

### Reality

when i put chromium in background the script flow kind of freezes , until i get chromium in foreground again.

### Puppeteer version

20.9.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
it sounds like it is expected behaviour: the browser throttles the inactive/background tabs so they might not run as expected. You can use `page.bringToFront()` to focus pages that need to be automated. Or consider using the old headless mode that specifically deviates from the standard browser behaviour here.

**Comment by bason247** [comment]
same problem @@ 
 '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-renderer-backgrounding'
  not working
