### ISSUE TITLE
[Bug]: Tried to use http:// protocol, but puppeteer switched to https:// since version 20.0.0

### ISSUE THREAD

**Issue by divomen** [puppeteer/puppeteer#10646]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

async function getPage(options, url) {
  const browser = await puppeteer.launch(options);
  const page = await browser.newPage();
  await page.goto(url);
  await page.waitForSelector("body");
  const res = await page.url();
  await browser.close();
  return res;
}

async function main() {
  const url = "http://ip-api.com/json";
  const headlessUrl = await getPage({ headless: true }, url);
  if (headlessUrl != url) {
    throw new Error("headlessUrl should be equal to url");
  }
  const newHeadlessUrl = await getPage({ headless: "new" }, url);
  if (newHeadlessUrl != url) {
    throw new Error("newHeadlessUrl should be equal to url");
  }
}

main().catch(console.error);
```

### Error string

newHeadlessUrl should be equal to url

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

The problem is that protocol changed from http to https in headful and new headless mode.
Te bug appears in the version 20.0.0 and still exists. Version 19 works fine.

### Expectation

it should return the original url

### Reality

It heturns url with protocol changed to https (from http)

### Puppeteer configuration file (if used)

```TypeScript
nothing special
```

### Puppeteer version

20.9.0

### Node version

18.16.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
I don't think it's a bug, it's just the default browser behaviour. Note that the old headless does not match the regular browser behaviour here as it is technically a custom browser implementation https://developer.chrome.com/articles/new-headless/ You can still use the old headless if you need that custom behaviour.

**Comment by dandrei** [comment]
The fix is to start Chrome with the option:

    --disable-features=HttpsUpgrades
