### ISSUE TITLE
[Bug]: ElementHandle.click() not working for elements injected by Chrome Extension's content script

### ISSUE THREAD

**Issue by lucasrmendonca** [puppeteer/puppeteer#10643]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
import path from 'node:path';

const CHROME_EXTENSION_PATH = path.resolve(process.cwd(), 'myExtension');

(async () => {
  const browser = await puppeteer.launch({
    defaultViewport: null,
    headless: false,
    args: [
      '--start-maximized',
      `--load-extension=${CHROME_EXTENSION_PATH}`,
      `--disable-extensions-except=${CHROME_EXTENSION_PATH}`,
    ],
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  const injectedButton = await page.waitForSelector('#my-injected-button');
  await injectedButton.click();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I have a Chrome Extension that has a content script that injects a button on the page.

It works if I do:

```
await page.waitForSelector('#my-injected-element');
await page.evaluate(() => document.querySelector('#my-injected-element').click()};
```

However, when using ElementHandle class, it doesn't:
```
const injectedButton = await page.waitForSelector('#my-injected-element');
await injectedButton.click();
```

### Expectation

I expected ElementHandles to behave the same for the original page's DOM elements and the Chrome-Extension-injected elements

### Reality

Chrome Extension elements can't be clicked using ElementHandle class

### Puppeteer version

20.9.0

### Node version

16.17.1

### Package manager

npm

### Package manager version

9.8.0

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Hello, can you provide the extension in either a repo or a gist , so we can test with it?

**Comment by lucasrmendonca** [comment]
@Lightning00Blade turns out this was a mistake on my part, the button was being created with "pointer-events: none" at the moment of its creation and after it finished loading, it removed the "pointer-events" property. When using the ElementHandle, the button was clicked while "pointer-events: none" was still in place. However, when using page.evaluate() the button had enough time to load and remove the "pointer-events" property, therefore being able to be clicked.
