### ISSUE TITLE
Unable to install latest version of Puppeteer, but can install last major version v19.11.1

### ISSUE THREAD

**Issue by MArfanM** [puppeteer/puppeteer#10669]
I've been trying to install the latest version of Puppeteer for a project. There are some functions, such as Page.locator() and the second argument of Page.evaluate() that I'd like to take advantage of.

But my past few attempts have failed, due to some certificate errors when it comes to downloading Chrome.
Attempting to download the last major release, v19.11.1, does work however.

I've looked into this similar [issue (2173)](https://github.com/puppeteer/puppeteer/issues/2173), followed some suggestions such as running `sudo npm install -g puppeteer --unsafe-perm=true --allow-root` and disabling my VPN, but none of them worked. The only solution that 'worked' was setting the PUPPETEER_SKIP_DOWNLOAD to True, but this prevents Chrome from being downloaded and renders Puppeteer unusable for me.

I'm not certain what's causing this, anyone have any idea of a solution I could try?

I've attached below the error log. Please let me know if there is any other info you need.

[2023-08-01T12_53_32_034Z-debug-0.log](https://github.com/puppeteer/puppeteer/files/12229359/2023-08-01T12_53_32_034Z-debug-0.log)

**Comment by DatGameh** [comment]
(closing)
