### ISSUE TITLE
[Bug]: Passing userDataDir to Puppeteer does not access the correct saved logins as regular Chrome

### ISSUE THREAD

**Issue by ianwieds** [puppeteer/puppeteer#10666]
### Minimal, reproducible example

```TypeScript
const os = require('os');
const username = os.userInfo().username;
const workingExePath = '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome';
const workingDataBaseDir = `/Users/${username}/Library/Application\ Support/Google/Chrome`

const browser = await puppeteer.launch({
  headless: false,
  executablePath: workingExePath, // supply the user-specific path here
  defaultViewport: {
    width: 1280,
    height: 720
  },
  userDataDir: workingDataBaseDir, // supply the user-specific path here

  args: [
    '--mute-audio', // this mutes the entire browser, not just one tab
    '--profile-directory=Default',
  ]
});

const page = await browser.newPage();
await page.goto('https://mail.google.com/mail/u/0/#inbox');
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I want to use Puppeteer to control the same profile/session as my regular Chrome browser. Specifically, I would like the websites I have logged in to stay logged in when opening a new Puppeteer instance.

### Expectation

Passing `userDataDir` to Puppeteer does not work as expected.

It should open the same session that I normally have access to when opening a non-Puppeteer-spawned Chrome and have all my saved logins so I don't have to login to websites using Puppeteer.

### Reality

I am able to open a Puppeteer Chrome instance and the instance definitely has the bookmarks and profile picture and even the same tabs as a non-Puppeteer-spawned Chrome. The Puppeteer-spawned Chrome instance also has the "Chrome is being controlled by automated test software" message.

However, on the Puppeteer-spawned Chrome, I am not logged in any websites that I am normally on the non-Puppeteer-spawned Chrome browser. So it's like the cookies, storage, or whatever is not working properly or not being used by Puppeteer or something.

To see if I could have any more luck, I manually copied the `userDataDir` to `/Users/${username}/Library/Application\ Support/Google/Chrome_` (just has an underscore at the end) and tried using this new folder with Puppeteer but it still does not work.

### Puppeteer version

20.9.0

### Node version

16.17.0

### Package manager

npm

### Package manager version

8.15.0

### Operating system

macOS

**Comment by jrandolf** [comment]
Could you trying [ignoring default args](https://pptr.dev/api/puppeteer.launchoptions#:~:text=true-,ignoreDefaultArgs,-optional) and specifying your profile directory?

**Comment by OrKoN** [comment]
Make sure that the user data dir is correct by running your standalone browser with the same explicit `--user-data-dir` and other parameters. I am unable to reproduce this behaviour:

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: false,
  defaultViewport: {
    width: 1280,
    height: 720
  },
  userDataDir: '/tmp/data-resused', // supply the user-specific path here
  executablePath: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary'
});

const page = await browser.newPage();
await page.goto('https://example.com');
```

Steps

1)  Run the script
2) Modify local storage
3) Restart and the data is still in the local storage.

which indicates that Puppeteer-launched browser successfully picks up user data dir from previous runs. It's very likely that your regular Chrome stores things in a different path.

**Comment by Hitotsubashi** [comment]
> Steps
> 
> 1. Run the script
> 2. Modify local storage
> 3. Restart and the data is still in the local storage.
> 
> which indicates that Puppeteer-launched browser successfully picks up user data dir from previous runs. It's very likely that your regular Chrome stores things in a different path.

I running these three steps and found out that I can getItem from localStorage even though I have set it in step one.

**Comment by Hitotsubashi** [comment]
I seriously doubt that userDataDir is valid. When I specify userDataDir to start puppeteer, I open chrome://version and find that user-data-dir is another place.
![image](https://github.com/user-attachments/assets/61548818-af03-4cc9-a61e-ee18b97982bb)
![image](https://github.com/user-attachments/assets/497fc0a8-a452-47e4-9d31-a4659cb86674)

**Comment by yehor-anisimov** [comment]
> doubt that userDataDir is valid

I didn't have a luck to reuse my Chrome Profile using this option.
However if I put custom path
```
userDataDir: './FakeChromeProdile'
```
puppeteer is reusing this profile and keep sessions alive between launches.

**Comment by zikalino** [comment]
Indeed, it doesn't work as expected, here's workaround.
I put the datadirectory into raw browser options like this and it worked:

  args = {'executablePath': EXECUTABLE_LOCATION,
          'ignoreDefaultArgs': True,
          'args': ['--load-extension=' + extension_path,
                     '--enable-automation',
                     '--enable-unsafe-extension-debugging',
                     **'--user-data-dir=' + userDir]**}

Note, that the other args should be irreelevant, this is just the config I am currently using for reference.
