### ISSUE TITLE
Puppeteer website (documentation)

### ISSUE THREAD

**Issue by sukrosono** [puppeteer/puppeteer#1068]
## Hosting: 
  -  [ ] github webpage x
  -  add list here

<details><summary>Tools:</summary>

  - [ ] [hugo](https://gohugo.io/)
  - [ ] express
  - [x] JsDoc
  - [x] antwar
</details>

### Structure:
  -  [x] follow proposal #602 
  -  will deploy to [google dev web fundamentals](https://developers.google.com/web/)
     > [detail webFundamentals build](https://github.com/google/WebFundamentals/blob/a51d4eee0118127c094f86de2665ba5643c999e5/gulp-tasks/reference-docs.js#L200)

### Thing to consider:
  - [ ] support offline documentation via [devdocs](https://github.com/Thibaut/devdocs)
       >  [requirement](https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here) in devdocs, [mechanism](https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs)

  - [ ] file related to the site should only live on docs directory
  - [ ]  support translation

**Comment by paulirish** [comment]
FWIW i'm really impressed with the build of [webpack's new docs](https://webpack.js.org/concepts/)

repo: https://github.com/webpack/webpack.js.org

**Comment by sukrosono** [comment]
I primarily vote for hosting on github webpages, because it free. Then use hugo.
But when we have budget to hosting on other place i will vote to use express and it's friend.
I am okay with the rest options,
### approach
Since i have no experience writing documentation, i am leaving it to the internal team to choose.
But i am highly recommend to support offline documentation via devdocs, since i use it a lot. So we choose approach to conform devdocs mechanism. Hopefully when the site is open it also available on devdocs :smile: 


@ebidel Eric i wonder can you edit the first entry to add preferred tools by internal teams and mark a tools as approved one?

**Comment by ebidel** [comment]
Hosting isn't really an issue, but from personal experience building doc sites, I'd shy away from getting into the business of maintaining a custom server for a doc site.

gh-pages is easy but longer-term, I think we probably want documentation hosted on something like developers.google.com/web/tools/puppeteer to take advantage of the team resources, infra, and integration with the rest of our doc content. Lighthouse and [Workbox](https://developers.google.com/web/tools/workbox/reference-docs/latest/) are doing the same. The good news is that d.g.com is mostly markdown files with some metadata and styling. We may be mostly there with the tools @gauntface has built.

One question is how we'd approach updating our reference docs. It could be as easy as moving or mirroring docs/index.md to github.com/Google/Webfundamentals.

@brutalcrozt I know you have some cycles to get started, but I think this is something we should probably punt until after Chrome Dev Summit next week :)

**Comment by gauntface** [comment]
From Workbox side - we are just markdown files on web fundamentals and reference docs are building with a JSDoc theme that is d.g.com friendly.

I don't know how you are generating API docs, but happy to help get them if you want a hand.

**Comment by sukrosono** [comment]
@ebidel Sure.
@gauntface IFAIK currently the api doc, build with node [script](https://github.com/GoogleChrome/puppeteer/tree/master/utils/doclint).

**Comment by aslushnikov** [comment]
There seems to be no progress with this; closing for now. Feel free to write back/re-file to object!
