### ISSUE TITLE
Did you rollbacked to chromium?

### ISSUE THREAD

**Issue by jeandat** [puppeteer/puppeteer#10697]
Since puppeteer v20, Chromium has been discarded in favor of Chrome for Testing. As stated [here](https://github.com/puppeteer/puppeteer/pull/10054).

Strangely on [puppeteer site](https://pptr.dev/chromium-support), CfT has been used a bit but since v20.9, Chromium is back. I wonder why? There is no documentation about that (none that I can find).

It's important for me cause we do install chrome/chromium ourselves as we don't have always access to the net on production.

**Comment by jrandolf** [comment]
Sorry, it seems somewhere along the pipeline the website incorrectly wrote Chromium. Rest assured it's still CfT.

I've fixed the site here: https://github.com/puppeteer/puppeteer/commit/ce18dc6fa9c06751dad87cf631ccf18a63d73d21

**Comment by jeandat** [comment]
Nice. Thanks.
