### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gudhateAkshay** [puppeteer/puppeteer#10693]
### Minimal, reproducible example

```TypeScript
// create browser instance and create page
		const browser = await puppeteer.launch({ headless: "new" });
		const page = await browser.newPage();

		// create buffer from html content
		await page.setContent(HTMLTemplateString, { waitUntil: "domcontentloaded" });
		const attachmentBuffer = await page.pdf(PDFFileOptionsObject);
		const attachmentMimeType = "application/pdf";

		// close browser instance
		await browser.close();
```

### Error string

Error: Failed to launch the browser process!

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

trying to create pdf.

### Expectation

pdf should create

### Reality

error

### Puppeteer version

"puppeteer": "^19.2.2"

### Node version

18

### Package manager

yarn

### Package manager version

1.22.17

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
This usually happens when browser is not install property. Sometime yarn does not run the `postinstall` scripts please see if running `node ./node_modules/puppeteer/install.js` and rerun your script.
If the error persist please post the full logs from the error.
