### ISSUE TITLE
[Bug]: When  headless is false, Puppeteer doesn't work under some websites.

### ISSUE THREAD

**Issue by honestydeveloper** [puppeteer/puppeteer#10690]
### Minimal, reproducible example

```TypeScript
const {addExtra} = require("puppeteer-extra");
const puppeteerVanilla = require("puppeteer-core");
const puppeteer = addExtra(puppeteerVanilla);

// add stealth plugin and use defaults (all evasion techniques)
const StealthPlugin = require("puppeteer-extra-plugin-stealth");
puppeteer.use(StealthPlugin());
puppeteer
  .launch({
    executablePath:
      "D:\\Application\\chrome.exe",
    product: "chrome",
    headless: false,
    userDataDir: "C:\\puppeteer-test",
    ignoreDefaultArgs: [],
  })
  .then(async (browser) => {
    // Create a new page
    const page = await browser.newPage();
    page.goto("https://app.zenrows.com/register");
  });
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Hi,
I have created the puppeteer app which is to drive google chrome on GUI mode(headless=false).

But puppeteer doesn't work on some websites supported security companies such as cloudflare.
The url is https://app.zenrows.com/register

I have tried to use puppeteer-stealth plugin but it's still not working.

Here are my questions;
1) When puppeteer opened on GUI mode, I think it's much like the regular google chrome app.
Why it is detected as the bot app in the security companies?

2) Puppeteer and chrome-remote-interface do rely on devtools-protocol.
But chrome-remote-interface isn't detected in cloudflare company.

What's the reason?

const CDP = require("chrome-remote-interface");

async function example(a) {
  let client;
  try {
    // connect to endpoint
    client = await CDP();
    // extract domains
    const { Network, Page } = client;
    debugger;
    // setup handlers
    Network.requestWillBeSent((params) => {
      console.log(params.documentURL, a);
    });
    // enable events then start!
    await Network.enable();
    await Page.enable();
    await Page.navigate({ url: "https://app.zenrows.com/register" });
    await Page.loadEventFired();
  } catch (err) {
    console.error(err);
  } finally {
    if (client) {
      //   await client.close();
    }
  }
}

example(2);

### Expectation

When headless is false, Puppeteer should not detected as the bot app in the security company.

### Reality

Puppeteer didn't work on https://app.zenrows.com/register

### Puppeteer configuration file (if used)

```TypeScript
ignoreDefaultArgs: [
    "--restore-last-session",
    "--disable-background-networking",
    // "--enable-features=NetworkService,NetworkServiceInProcess",
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--disable-breakpad",
    "--disable-client-side-phishing-detection",
    "--disable-component-extensions-with-background-pages",
    "--disable-default-apps",
    "--disable-dev-shm-usage",
    "--disable-extensions",
    // BlinkGenPropertyTrees disabled due to crbug.com/937609
    "--disable-hang-monitor",
    "--disable-ipc-flooding-protection",
    "--disable-popup-blocking",
    "--disable-prompt-on-repost",
    "--disable-renderer-backgrounding",
    "--disable-sync",
    "--force-color-profile=srgb",
    "--metrics-recording-only",
    "--no-first-run",
    "--enable-automation",
    "--password-store=basic",
    "--use-mock-keychain",
    "--allow-pre-commit-input",
    "--disable-component-update",
    "--disable-features",
    "--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints",
    "--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints,DIPS",
    "--disable-features=Translate,BackForwardCache",
    // OptimizationHints
    // "--enable-blink-features=IdleDetection",
    "--enable-features=NetworkServiceInProcess2",
    "--export-tagged-pdf",
    // "--disable-blink-features=AutomationControlled",
    "about:blank",
  ],
```

### Puppeteer version

21.0.1

### Node version

18.13.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
This is out of scope for the Puppeteer project.
To answer your questions:
1. There are many ways a website can detect automation behavior, Puppeteer does not try to eliminate any of them.
2. I am not familiar with `chrome-remote-interface` but it looks like you are connecting to the browser rather then spawning a new instance like Puppeteer does.
