### ISSUE TITLE
[Bug]: On Raspi -> Syntax error: Chrome Failed to launch the browser process! ")" unexpected

### ISSUE THREAD

**Issue by DrDBanner** [puppeteer/puppeteer#10698]
### Minimal, reproducible example

No matter which node version or puppeteer version I try on the Raspi it's always a syntax error in different lines. 

Same versions on a Mac work flawless. 

### Versions

- Node.js v20.5.0
- puppeteer@21.0.1
- NPM 9.8.0

```
/home/pi/the/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277
                reject(new Error([
                       ^

Error: Failed to launch the browser process!
/home/pi/.cache/puppeteer/chrome/linux-115.0.5790.102/chrome-linux64/chrome: 1: Syntax error: ")" unexpected


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/home/pi/thehive/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)
    at Interface.emit (node:events:526:35)
    at Interface.close (node:internal/readline/interface:527:10)
    at Socket.onend (node:internal/readline/interface:253:10)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Pi
**Distribution** 
Raspian 

**Version** 
Bullseye

**UNAME**
Linux pi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
```


### Error string

Error: Failed to launch the browser process! /home/pi/.cache/puppeteer/chrome/linux-115.0.5790.102/chrome-linux64/chrome: 1: Syntax error: ")" unexpected

### Background

_No response_

### Expectation

Chromium Browser starts

### Reality

Chromium Browser does not start

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

21.0.1

### Node version

20.5.0

### Package manager

npm

### Package manager version

9.8.0

### Operating system

Linux

**Comment by jrandolf** [comment]
Since we do not have a Raspberry Pi for testing, I'm afraid we cannot test this ourselves, however we know our Docker images based on Linux indeed work, so perhaps it's worth investigating the difference between your environment and the one set up by our [Docker image](https://github.com/puppeteer/puppeteer/tree/main/docker).

**Comment by DrDBanner** [comment]
Well, other LInux enviroments work. The only difference is here it's an ARM processor and only the 32bit version. So I guess there might be the issue.

**Comment by duanedyar** [comment]
I experienced the same issue and the workaround resolved the issue.

Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

Node v20.10.0
Puppeteer v21.6.1
