### ISSUE TITLE
[Bug]: Download failed: server returned code 403. URL: https://storage.googleapis.com/juggler-builds/2f959d575a3d61f5dda12e4e2dca1f46a92ab569/firefox-win64.zip

### ISSUE THREAD

**Issue by kabilanvk** [puppeteer/puppeteer#10706]
### Steps to reproduce

npm install puppeteer-firefox

### Expected results

successful installation

### Actual results

Failed with error:
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! ERROR: Failed to download Firefox r2f959d575a3d61f5dda12e4e2dca1f46a92ab569!
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/juggler-builds/2f959d575a3d61f5dda12e4e2dca1f46a92ab569/firefox-win64.zip

_Hitting the URL directly gives an account error._

`<Error>
<Code>UserProjectAccountProblem</Code>
<Message>
The project to be billed is associated with an absent billing account.
</Message>
<Details>
The billing account for the owning project is disabled in state absent
</Details>
</Error>
`

**Comment by OrKoN** [comment]
The old Juggler downloads are not supported anymore (see https://www.npmjs.com/package/puppeteer-firefox).
