### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by paulbjensen** [puppeteer/puppeteer#1070]
Hi,

Thanks for this tool. I've had a great experience using it with Cucumber.js to do integration testing of an app that consists of a React SPA and a REST API served by Express.

I got a Greenkeeper PR to upgrade Puppeteer from 0.11 to 0.12. There were quite a few changes (i.e. deprecation of page.plainText, changes in page.type) that I'm now adjusting to.

Are there any plans for a CHANGELOG.md file?

**Comment by sukrosono** [comment]
:confused:

**Comment by ebidel** [comment]
We're sticking release notes on the releases pages: https://github.com/GoogleChrome/puppeteer/releases. 

That work?

**Comment by paulbjensen** [comment]
Yes, thanks. Sorry I didn't see that.

**Comment by paulbjensen** [comment]
On a side note, I managed to make the changes, and my Cucumber test suite has gone from taking 6m38s to run, to now taking just 1m23s. Lovely upgrade.
