### ISSUE TITLE
[Bug]: Evaluate may hang if frame changes to OOPIF

### ISSUE THREAD

**Issue by liamdalg** [puppeteer/puppeteer#10715]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const OOPIF_BASE = 'http://127.0.0.1:8000';
const BASE = 'http://localhost:8000';

const sleep = t => new Promise(r => setTimeout(r, t));

const browser = await puppeteer.launch({
    headless: 'new',
});

const page = await browser.newPage();
await page.goto(`${BASE}/iframe.html`);

for (const f of page.frames()) {
    console.log(`Evaluating in ${f._id}, ${f.url()}, ${f.isOOPFrame()}`);
    await f.evaluate(() => 1 + 1);
    console.log('Done');
}

await page.$eval('iframe', (f, b) => f.setAttribute('src', `${b}/blank.html`), OOPIF_BASE);

for (const f of page.frames()) {
    console.log(`Evaluating in ${f._id}, ${f.url()}, ${f.isOOPFrame()}`);
    await f.evaluate(() => 1 + 1);
    console.log('Done');
}

await browser.close();
```

### Error string

no error

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

In new headless, if a call to `frame.evaluate` races against the frame changing from a normal iframe to an OOPIF, then it may hang. The minimal example attached requires the two attached files to be available at `localhost:8000`; I've been running it with `python3 -m http.server`.  Note that this is quite flaky given it's a race condition. On my machine it triggers a hang around 20% of the time.

[HTML Files](https://github.com/puppeteer/puppeteer/files/12299487/html.zip)
[oopif.log](https://github.com/puppeteer/puppeteer/files/12299594/oopif.log)

Possibly related to my other bug report #10696.

For now, I've been avoiding this by running with `--disable-features=SitePerProcess`.

### Expectation

Either:
* Evaluation to succeed, or
* `Error: Execution context was destroyed, most likely because of a navigation` to be thrown.

### Reality

`frame.evaluate` hangs indefinitely.

### Puppeteer version

21.0.2

### Node version

18.16.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Looks like there is a race condition here because iframe navigation is asynchronous. We should at least error here.

Adding `await page.waitForFrame(frame => frame.isOOPFrame())` after `await page.$eval('iframe', (f, b) => f.setAttribute('src', `${b}/blank.html`), OOPIF_BASE);` makes it more robust (it seems).

**Comment by OrKoN** [comment]
@liamdalg are you still able to reproduce the issue using the latest version? 

I am not seeing any flakiness in a thousand runs:

```
import puppeteer from 'puppeteer';

const OOPIF_BASE = 'http://127.0.0.1:8000';
const BASE = 'http://localhost:8000';

const sleep = t => new Promise(r => setTimeout(r, t));

const browser = await puppeteer.launch({
  headless: 'new',
});

for (let i = 0; i < 1000; i++) {
  const page = await browser.newPage();
  await page.goto(`${BASE}/iframe.html`);

  for (const f of page.frames()) {
    console.log(`Evaluating in ${f._id}, ${f.url()}, ${f.isOOPFrame()}`);
    await f.evaluate(() => 1 + 1);
    console.log('Done');
  }

  await Promise.all([
    page.$eval('iframe', (f, b) => f.setAttribute('src', `${b}/blank.html`), OOPIF_BASE),
  ]);

  await page.waitForFrame(frame => frame.isOOPFrame())

  for (const f of page.frames()) {
    console.log(`Evaluating in ${f._id}, ${f.url()}, ${f.isOOPFrame()}`);
    await f.evaluate(() => 1 + 1);
    console.log('Done');
  }

  await page.close()
}
await browser.close();
```

**Comment by liamdalg** [comment]
Looks like its fixed on my end too. It no longer hangs as of `v21.7.0` - it either succeeds or exits with `Execution context was destroyed!`. Thanks!
