### ISSUE TITLE
[Bug]: Emit browser events asynchronously

### ISSUE THREAD

**Issue by DudaGod** [puppeteer/puppeteer#10734]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  try {
    const browser = await puppeteer.launch({headless: false});

    browser.on('targetcreated', async (target) => {
      await new Promise((resolve, reject) => {
        reject('foo_bar_baz');
      });
    });

    await browser.newPage();
    await browser.close();
  } catch (err) {
    console.log('ERR:', err);
  }
})();
```

### Error string

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "foo_bar_baz".

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I want to subscribe on `targetcreated` and do some async stuff using puppeteer API. Sometimes my code crashes with various errors inside `targetcreated` callback. I know I can use `try catch` inside my callback, but why all these events emitted with sync `emit`? Why we not use for example `emitAsync` from [eventemitter2](https://github.com/EventEmitter2/EventEmitter2)? In this case, there would be no problems with unhandled rejections.

Similar issue - https://github.com/puppeteer/puppeteer/issues/9514.

### Expectation

I expected that puppeteer will emit browser events asynchronously.

### Reality

Puppeteer emit event synchronously but most users use it like async (many examples in issue).

### Puppeteer version

21.0.3

### Node version

16.16.0

### Package manager

npm

### Package manager version

8.11.0

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
Hello, this is not something we handle as it mean Puppeteer has to swallows error from the user code. Users should deal with error that rise from there code on their own.
Example from the browser native events
![image](https://github.com/puppeteer/puppeteer/assets/34244704/3495ac5f-a35d-49ca-afb4-1f428f4b8060)
Note we use [mitt](https://github.com/developit/mitt) internally to handle our events.

**Comment by DudaGod** [comment]
I just got the error from internal code of puppeteer few times in CI and so far can't reproduce the problem locally. It means I don't have a minimal reproducible example. I'll be back as soon as I find it.
