### ISSUE TITLE
[Bug]: Not Working with PM2

### ISSUE THREAD

**Issue by SlowMotion241** [puppeteer/puppeteer#10733]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer')

;(async () => {
    const browser = await puppeteer.launch({
        headless: 'new',
    })
    const page = await browser.newPage()

    await page.goto('https://api.ipify.org?format=json')
    const html = await page.content()
    console.log(html)
})()
```

### Error string

Error: Failed to launch the browser process!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I use this very simple code and it works great if I launch it through "node code.js"
But if a try use pm2 my code not working. 

### Expectation

I expect the correct work of the code

### Reality

If a try code in Pm2 a have logs:

 Error: Failed to launch the browser process!
3|code       | [0814/142613.006481:ERROR:bootstrap.cc(65)] bootstrap_check_in org.chromium.crashpad.child_port_handshake.60369.127043014.ZVEWIIPXOENYQKZZ: unknown error code (141)
3| code       | [0814/142613.062414:ERROR:file_io.cc(94)] ReadExactly: expected 4, observed 0
3| code       | [0814/142613.062719:ERROR:bootstrap.cc(65)] bootstrap_check_in org.chromium.crashpad.child_port_handshake.60367.127043012.PSJKAVWXRKLJZYWL: unknown error code (141)
3| code       | [0814/142613.117927:ERROR:file_io.cc(94)] ReadExactly: expected 4, observed 0
3|code       | TROUBLESHOOTING: https://pptr.dev/troubleshooting
3|code       |     at Interface.onClose (/Users/me/Documents/JS/my_code/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)
3|code       |     at Interface.emit (node:events:532:35)
3|code       |     at Interface.close (node:readline:586:8)
3|code       |     at Socket.onend (node:readline:277:10)
3|code       |     at Socket.emit (node:events:532:35)
3|code       |     at endReadableNT (node:internal/streams/readable:1346:12)
3|code       |     at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Puppeteer version

21.0.3

### Node version

16.14.0

### Package manager

npm

### Package manager version

8.3.1

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
Hey @SlowMotion241, would be happy to investigate further, can you please provide a repo that this behavior can be reproduce?

**Comment by SlowMotion241** [comment]
I came to the conclusion that this is not the fault of Puppeteer. The problem is also observed when I use Selenium. Probably PM2 does not let the browser run.
