### ISSUE TITLE
[Bug]: XPATH expression works on $x method but not on waitForXPath method of Page object 

### ISSUE THREAD

**Issue by d3vr10** [puppeteer/puppeteer#10743]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'
const browser = await puppeteer.launch({
        headless: "new",
        devtools: false,
        args: [`--window-size=1080,1080`],
        defaultViewport: {
            width: 1080,
            height: 1080
        }
    });
const page = await browser.newPage()
const url = URL('https://www.google.com')
let res = await page.goto(url.href, { waitUntil: 'networkidle0' });
page.waitForXPath('//input[contains(@aria-label, "Phone number, username, or email")]')
//This hits an XPATH syntax error by the querySelectorAll on Document
//For what it's worth, I'm getting around for some reason with page.$x() method, which I expected to report me back the same error.
```

### Error string

Uncaught Error DOMException: Failed to execute 'querySelectorAll' on 'Document': '//input[contains(@aria-label, "Password")]' is not a valid selector.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I was trying to select an HTML input element using XPATH selectors and then proceed to type in, but I got an XPATH syntax error instead. I checked the syntax was ok by checking some XPATH documentation on the web and running the same selector on a chrome web browser dev tools console with the "$x()" function, and it worked.

### Expectation

It gave a result other than a XPATH syntax error.

### Reality

The Page Object waitForXPath method always reports an error concerning the XPATH syntax of the expression I specified above.

### Puppeteer version

21.0.3

### Node version

18.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
I am unable to reproduce with the provided example. Please update it with one that can be consistently verified.
Error I observe a `TimeoutError` which is expected as the selector does not exits on the page.
