### ISSUE TITLE
ERR_NO_SUPPORTED_PROXIES with socks5 proxy

### ISSUE THREAD

**Issue by rmzg** [puppeteer/puppeteer#1074]
Debian Unstable
```
    "puppeteer": {
      "version": "0.12.0",
      "resolved": "https://registry.npmjs.org/puppeteer/-/puppeteer-0.12.0.tgz",
      "integrity": "sha512-H/bylN7FccwbN7JZoSP+xRozxgJEDNy4uC4p727cyttKUVNXYjFuEMueJYHW0pblnrfLEH341SyFJVWhJMLxKQ==",
}
```
Downloading Chromium r508693
Linux 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux

Invocation:
```
const browser = await puppeteer.launch({
    args: ['--proxy-server="socks5://user:password@208.xx.xx.xx:yyyyy"']});
```

General error message:
```
(node:21198) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
    Error: Failed to navigate: https://www.expressvpn.com/what-is-my-ip
```

Debug Error Message:
``` 
RECV {"method":"Network.loadingFailed",
"params":{"requestId":"3631.1",
 "timestamp":1790559.529702, 
"type":"Document",
 "errorText": "net::ERR_NO_SUPPORTED_PROXIES",
"canceled":false}}
```

**Comment by rmzg** [comment]
This flag doesn't seem to work on the actual chromium packaged in the ubuntu xenial repos either, so it might not be specific to puppeteer but I'm running out of ideas to try to get the flag to work.

If I try `--proxy-server=http=socks5://...` it seems to ignore the setting completely.

And for the record, I can pass the exact proxy string to `curl -x` and it works fine.

**Comment by rmzg** [comment]
For other people wandering down this rabbit hole: https://bugs.chromium.org/p/chromium/issues/detail?id=615947

**Comment by fhmd4k** [comment]
chromium doesn't support socks5 auth but support http(s) auth. You only can use `--proxy-server=socks5://ip:port`

**Comment by rmzg** [comment]
I get the exact same error with `--proxy-server=http://user:password@208.xx.xx.xx:yyyy`

**Comment by fhmd4k** [comment]
sorry,i don't know it can't support in the command line. But i think you should try listen all requests to handle auth.

**Comment by aslushnikov** [comment]
@rmzg `page.authenticate` should help authenticate with proxy.

**Comment by sillyh4ck3r** [comment]
instead of using double-quotes:
`		args: ['--proxy-server="socks5://localhost:1081"']`

specify the proxy line without the double quotes:
`		args: ['--proxy-server=socks5://localhost:1081']`

It worked for me!

**Comment by valayDave** [comment]
Checkout this article for proxy implementation for puppeteer. 

https://blog.apify.com/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212

It worked out really well for us

**Comment by dgtlmoon** [comment]
`ERR_NO_SUPPORTED_PROXIES` can also be found when you supply the `username:password` in the `--proxy-server=` url query part ( discovered with https://github.com/dgtlmoon/changedetection.io )
