### ISSUE TITLE
[Feature]: How to use SSL websocket with remote debugging on Puppeteer?

### ISSUE THREAD

**Issue by honestydeveloper** [puppeteer/puppeteer#10747]
### Feature description

Hope doing well. I am going to use SSL web socket for remote debugging on Puppeteer. But in regular, we are using ws://127.0.0.1:9222 for the remote debugging.

I will appreciate if you could please help me. Thank you.

ws://localhost:9222/devtools/browser/b0b8a4fb-bb17-4359-9533-a8d9f3908bd8 to wss://localhost:9222/devtools/browser/b0b8a4fb-bb17-4359-9533-a8d9f3908bd8

**Comment by OrKoN** [comment]
I am not sure if the browsers support SSL sockets. The recommended way for better security is to use pipes (see the pipe option in https://pptr.dev/api/puppeteer.launchoptions/#properties).

**Comment by honestydeveloper** [comment]
If puppeteer is used on remote computer using puppeteer.connect function then it would be dangerous because of the not secured communication.
Do you have a alternative method to avoid this issule?

**Comment by OrKoN** [comment]
@honestydeveloper the secure solution is not expose the browser’s debugging server directly, instead it’s better to start the browser with the debugging pipe and have a custom secure web socket server forward commands. Or automate over a secure network.

**Comment by honestydeveloper** [comment]
if I use pipe option then it could never pass the some security companies.
Thus, I have to use remote debugging as the websocket.
I am not familiar with the automate over a secure network so could you please more explain how to explain it more detail ?

**Comment by OrKoN** [comment]
I am not sure either as it depends on your use case, but that goes beyond the scope of Puppeteer.
