### ISSUE TITLE
[Bug]: Downloading Chromedriver fails due to `unable to get local issuer certificate` error

### ISSUE THREAD

**Issue by christian-bromann** [puppeteer/puppeteer#10765]
### Minimal, reproducible example

```TypeScript
n/a
```

### Error string

unable to get local issuer certificate

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've embedded `@puppteeer/browser` for setting up Chrome and Chromedriver in WebdriverIO.

### Expectation

The package downloads with no issues.

### Reality

Several people [reported issues](https://github.com/webdriverio/webdriverio/issues/10968) when downloading Chrome or Chromedriver:

- one person said: _Once we had them turn off the ZScaler Internet Security it was able to start working for them._
- another one: _ but once I got off the VPN it started working_

### Puppeteer version

latest

### Node version

18.17.1

### Package manager

npm

### Package manager version

NPM

### Operating system

macOS

**Comment by jacekcho** [comment]
To sum up (and adding more logs)

running locally in my case  I get the error:

`2023-08-21T13:08:35.845Z WARN webdriver: Couldn't download Chromedriver v116.0.5845.96: unable to get local issuer certificate, trying to find known good version...`
`2023-08-21T13:08:36.094Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully`
`2023-08-21T13:08:36.094Z INFO @wdio/local-runner: shutting down`
`Error: Error: Couldn't find a matching Chrome browser for tag "116.0.5845.96" on platform "mac_arm"`

running on gitlab fails with an error:

`2023-08-21T13:25:45.231Z INFO @wdio/local-runner: Shutting down spawned worker`
`2023-08-21T13:25:45.233Z WARN webdriver: Couldn't download Chromedriver v116.0.5845.96: Download failed: server returned code 403. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip, trying to find known good version...`
`2023-08-21T13:25:45.481Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully`
`2023-08-21T13:25:45.482Z INFO @wdio/local-runner: shutting down`
`Error: Error: Couldn't find a matching Chrome browser for tag "116.0.5845.96" on platform "linux"`

**Comment by OrKoN** [comment]
So it does look like it's either an issue on the server (which I could not reproduce and we would probably get more reports) or a misconfiguration of SSL on the client / or something is tampering with the network traffic (proxy, VPN, antivirus?). I am not sure we will have a solution for this within Puppeteer.
