### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by adhil-bit** [puppeteer/puppeteer#10766]
### Steps to reproduce

locally its working when deployed to server its getting error like this

0|admin  |   Puppeteer old Headless deprecation warning:
0|admin  |     In the near future `headless: true` will default to the new Headless mode
0|admin  |     for Chrome instead of the old Headless implementation. For more
0|admin  |     information, please see https://developer.chrome.com/articles/new-headless/.
0|admin  |     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
0|admin  |     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

### Expected results

i expect a url 

### Actual results

0|admin  |   Puppeteer old Headless deprecation warning:
0|admin  |     In the near future `headless: true` will default to the new Headless mode
0|admin  |     for Chrome instead of the old Headless implementation. For more
0|admin  |     information, please see https://developer.chrome.com/articles/new-headless/.
0|admin  |     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
0|admin  |     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

**Comment by OrKoN** [comment]
You can suppress this deprecation warning by PUPPETEER_DISABLE_HEADLESS_WARNING or changing the log level.

**Comment by adhil-bit** [comment]
{
    "error": true,
    "message": "Failed to launch the browser process!\n/home/ubuntu/.cache/puppeteer/chrome/linux-116.0.5845.96/chrome-linux64/chrome: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n"
}
