### ISSUE TITLE
Support for geolocation mock?

### ISSUE THREAD

**Issue by hirokith** [puppeteer/puppeteer#1077]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: MacOS
* URLs (if applicable): https://h5.m.taobao.com/trip/home/index.html

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. use puppeteer to capture performance for the page.

```
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');
const iPhone = devices['iPhone 6'];
const co = require('co');
const path = require('path');
co(function* () {
  const PAGE_URL = 'https://h5.m.taobao.com/trip/home/index.html';
  const browser = yield puppeteer.launch({
    headless: false,
    ignoreHTTPSErrors: true,
    args: [
      '--auto-open-devtools-for-tabs'
    ],
    userDataDir: path.join(__dirname, 'user-dir')
  });
  const page = yield browser.newPage();
  yield page.emulate(iPhone);

  try {
    yield page.goto(PAGE_URL);
  } catch (e) {
    console.error(`>> Load page ${PAGE_URL} error encounted: `);
    console.error(e.stack);
  }
  yield page.waitForNavigation({
    waitUntil: 'networkidle',
    networkIdleTimeout: 2000
  });
  const perfEntries = yield page.evaluate(() => performance.getEntries());
  console.log(perfEntries);

  browser.close();

  return stats;
}).then((stats) => {
  console.log('END');
  console.log(stats);
}).catch(e => {
  console.error(e.stack);
});
```

2. allow geolocation permission
3. set the preset geolocation in devtools/sensors:

![image](https://user-images.githubusercontent.com/2196373/31699270-ab8f517c-b387-11e7-92f2-afbaf403bd8d.png)

**What is the expected result?**

The Geolocation preset config is saved to user-dir, and next time chromium should use the settings here to enable geolocation mock.

**What happens instead?**

The settings in devtools/sensors were not persistent, next time the code runs the geolocation settings were reset, which made the code in the page request geolocation failed.

Or is there any way to set the geolocation mock by `args` param when chromium launch?

**Comment by ebidel** [comment]
Since you're passing a `userDataDir`, I'd imagine these settings would be preserved. Could be a bug in Devtools/Chrome. cc @aslushnikov

**Comment by ebidel** [comment]
Ah, likely https://bugs.chromium.org/p/chromium/issues/detail?id=775703?

**Comment by saselovejulie** [comment]
@dickeylth @ebidel 
hi, 

> set the preset geolocation in devtools/sensors:

how do you update chrome location? by javascript code or by yourself operation?
is there any way that i can update my geolocation by javascript and let google map use this geolocation?

**Comment by saselovejulie** [comment]
navigator.geolocation.getCurrentPosition = function(success, failure) { 
    success({ coords: { 
        latitude: 31.230416, 
        longitude: 121.473701
    }, timestamp: Date.now() }); 
} 
maybe i can use this function to change my geolocation, but how could i enable Geolocation from "No override" to "Custom location" with js code on console?
![1508752797](https://user-images.githubusercontent.com/13128637/31883359-3783da84-b81c-11e7-9be4-afa2d2772879.png)

**Comment by ebidel** [comment]
You can't modify devtools settings by running code in the console. That
would be a huge security concern. You could try using the raw devtools
protocol for overriding geolocation settings. Just note that puppeteer
doesn't expose a way to access the raw devtools protocol, so that's harder
to do than it should be.

devtools-protocol/tot/Emulation/#method-setGeolocationOverride

**Comment by aslushnikov** [comment]
This should be easy to implement using the [Emulation.setGeolocationOverride](https://aslushnikov.github.io/vanilla-protocol-viewer/#Emulation.setGeolocationOverride) method. 
Inspiration can be taken from other similar methods, e.g.
https://github.com/GoogleChrome/puppeteer/blob/380bb6a87f23f423df558c2cdb91bad8926464e0/lib/Page.js#L557-L567

I'd be happy to review a PR.

**Comment by AshwinDNair** [comment]
how do you override the geolocation settings? @ebidel

**Comment by ebidel** [comment]
We need to add that feature. What @aslushnikov suggested :)

**Comment by slohmes** [comment]
Is anyone working on a fix for this? If not, I'd like to try implementing it!

**Comment by ebidel** [comment]
@slohmes don't think so. Feel free to send a PR with what was suggested in https://github.com/GoogleChrome/puppeteer/issues/1077#issuecomment-339937531.

**Comment by saikrishna321** [comment]
@ebidel any updates on this ?

**Comment by ebidel** [comment]
We haven't prioritized this but would be willing to accept a PR. As mentioned you can also use the devtools protocol apis to override the settings.

**Comment by saikrishna321** [comment]
@ebidel i see there is PR https://github.com/GoogleChrome/puppeteer/pull/1297 but pretty old. Can you please confirm if i can raise a new PR for the same implementation ?

Can you point to any doc how i can use devtools protocol apis in puppeteer ?

**Comment by ebidel** [comment]
Didn't see that. Seems like we need permission dialog support in puppeteer in order for that PR to work: https://github.com/GoogleChrome/puppeteer/pull/1297#issuecomment-348836978.

You can send raw protocol methods with:
https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-class-cdpsession

**Comment by saikrishna321** [comment]
@ebidel Thanks a lot 👍 let me try

**Comment by saikrishna321** [comment]
@ebidel i tried and the location still set to my current location 

```
const page = await browser.newPage();
  const client = await page.target().createCDPSession();
  await client.send("Network.enable");
  const setCookie = await client.send("Emulation.setGeolocationOverride", {
    latitude: 27.1752868,
    longitude: 78.040009,
    accuracy: 100
  });
  await page.goto("https://maps.google.com");
  await page.waitFor(5000);
  process.exit();
}
```
I was expecting the maps to point to the lat n long given.

**Comment by 298068845** [comment]
Support for Mobile deviceOrientation mock?
