### ISSUE TITLE
[Bug]: error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Tushar-Chavan14** [puppeteer/puppeteer#10779]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
var html = "<h1>hello world</h1>";

      const browser = await puppeteer.launch({
        headless: true,
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
      });
      const page = await browser.newPage();
      await page.setContent(html);
      const pdf = await page.pdf({ landscape: true, width: "198mm" });
      await browser.close();
```

### Error string

 Error: Failed to launch the browser process!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This whole thing works on my local machine but not on my server machine
server has Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1040-oracle aarch64)

### Expectation

I had a html template compiled with handlebars i want to genrate the pdf buffer and send it to client in base64 format

### Reality

before it was working but now i am getting this 

error: Failed to launch the browser process!
0|sfa  | /home/ubuntu/.cache/puppeteer/chrome/linux-116.0.5845.96/chrome-linux64/chrome: 3: Syntax error: ")" unexpected
0|sfa  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
0|sfa  | Error: Failed to launch the browser process!
0|sfa  | /home/ubuntu/.cache/puppeteer/chrome/linux-116.0.5845.96/chrome-linux64/chrome: 3: Syntax error: ")" unexpected
0|sfa  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
0|sfa  |     at Interface.onClose (/srv/www/yield-learning-server/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)
0|sfa  |     at Interface.emit (node:events:525:35)
0|sfa  |     at Interface.emit (node:domain:489:12)
0|sfa  |     at Interface.close (node:internal/readline/interface:533:10)
0|sfa  |     at Socket.onend (node:internal/readline/interface:259:10)
0|sfa  |     at Socket.emit (node:events:525:35)
0|sfa  |     at Socket.emit (node:domain:489:12)
0|sfa  |     at endReadableNT (node:internal/streams/readable:1359:12)
0|sfa  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### Puppeteer configuration file (if used)

```TypeScript
.puppeteer.cjs

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: process.env.PUPEETER_CACHE,
};

where PUPEETER_CACHE=/home/tushar/.cache/puppeteer/
```

### Puppeteer version

21.1.0

### Node version

v18.16.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
Make sure that the server CPU architecture matches your local architecture or download the binaries on the server (e.g., by running `npm install` which would download the matching browser binaries).

**Comment by pvditto** [comment]
@OrKoN the github action is incorrectly flagging this issue as not reproducible because it seems to ignore the reported environment.

@Tushar-Chavan14 your example is failing because Puppeteer does not support Linux aarch64, see https://github.com/puppeteer/puppeteer/issues/7740. 

Unfortunately, Puppeteer does not seem to have a check for this which would allow for a more helpful error message like

```
Your CPU architecture is not yet supported. Please install Chromium version 'exact-version-required' and configure Puppeteer to use it with the xxx and yyy arguments
```
