### ISSUE TITLE
[Bug]: `touchMove()` not firing `touchmove` event in Stencil project

### ISSUE THREAD

**Issue by nick-vincent** [puppeteer/puppeteer#10786]
### Minimal, reproducible example

```TypeScript
import { newE2EPage, E2EPage, EventSpy } from '@stencil/core/testing';

describe('touch events', () => {
  let page: E2EPage;
  let touchStartSpy: EventSpy;
  let touchMoveSpy: EventSpy;
  let touchEndSpy: EventSpy;

  beforeEach(async () => {
    page = await newE2EPage();

    await page.setContent(`
      <html><body>Test</body></html>
    `);

    touchStartSpy = await page.spyOnEvent('touchstart');
    touchMoveSpy = await page.spyOnEvent('touchmove');
    touchEndSpy = await page.spyOnEvent('touchend');

    await page.touchscreen.touchStart(1, 1);
    await page.touchscreen.touchMove(2, 2); // does not work
    await page.touchscreen.touchEnd();
    await page.waitForChanges();
  });

  it('fires touch start', () => {
    expect(touchStartSpy).toHaveReceivedEventTimes(1);
  });

  // touchmove does not get fired
  it('fires touch move', () => {
    expect(touchMoveSpy).toHaveReceivedEventTimes(1);
  });

  it('fires touch end', () => {
    expect(touchEndSpy).toHaveReceivedEventTimes(1);
  });
});
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm working in Stencil and trying to test that touch events are fired correctly.

I've created a barebones Stencil example repo to repro here: https://github.com/nick-vincent/stencil-test-touch-events/

When the [test](https://github.com/nick-vincent/stencil-test-touch-events/blob/main/src/touch-events.e2e.ts) is run, the `touchstart` and `touchend` events fire correctly, but `touchmove` does not get fired:

```ts
await page.touchscreen.touchStart(1, 1);
await page.touchscreen.touchMove(2, 2); // does not work
await page.touchscreen.touchEnd();
```

(I do realize this is potentially not a bug with Puppeteer itself, but figured I need to start somewhere...)

### Expectation

I would expect `touchscreen.touchMove()` to fire a `touchmove` event.

### Reality

```
[50:05.8]  jest args: --spec --e2e --max-workers=8
 FAIL  src/touch-events.e2e.ts
  touch events
    ✓ fires touch start (602 ms)
    ✕ fires touch move (427 ms)
    ✓ fires touch end (381 ms)

  ● touch events › fires touch move

    expected event "touchmove" to have been called 1 times, but was called 0 time

      30 |   // touchmove does not get fired
      31 |   it('fires touch move', () => {
    > 32 |     expect(touchMoveSpy).toHaveReceivedEventTimes(1);
         |                          ^
      33 |   });
      34 |
      35 |   it('fires touch end', () => {

      at Object.<anonymous> (src/touch-events.e2e.ts:32:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        2.238 s, estimated 3 s
Ran all test suites.
```

### Puppeteer version

21.1.0

### Node version

20.3.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by jrandolf** [comment]
Doesn't look related to Puppeteer. Please file with stencil.

**Comment by nick-vincent** [comment]
> Doesn't look related to Puppeteer. Please file with stencil.

@jrandolf: Thanks for your response!

I went ahead and filed [an issue](https://github.com/ionic-team/stencil/issues/4735) with Stencil, but I'd be surprised if it were limited to Stencil projects...

The barebones repo doesn't even contain or test any Stencil components — the test just runs on an empty HTML page.

I'll let you know what the Stencil folks say!

**Comment by nick-vincent** [comment]
@jrandolf Just to follow up here...

So I did file [a bug](https://github.com/ionic-team/stencil/issues/4735) with Stencil, but they also believe the bug is in Puppeteer.

I did some more debugging and I was able to repro without Stencil, so I filed [a new issue](https://github.com/puppeteer/puppeteer/issues/10836) with ya'll.
