### ISSUE TITLE
[Feature]: `@puppeteer/browsers` support different browser versions for Firefox

### ISSUE THREAD

**Issue by christian-bromann** [puppeteer/puppeteer#10787]
### Feature description

It would be awesome if `@puppeteer/browsers` could support for different browser versions the same way Chrome does. Currently only `latest` is supported. Is there a plan to have feature parity here?

**Comment by OrKoN** [comment]
Looks like the duplicate for https://github.com/puppeteer/puppeteer/issues/10420 Also see https://github.com/puppeteer/puppeteer/issues/10414
