### ISSUE TITLE
[Bug]: TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!     at ChromeLauncher.launch

### ISSUE THREAD

**Issue by feelthecoder** [puppeteer/puppeteer#10792]
### Steps to reproduce

1. using linux RHEL 7.9 offline mode to run puppeteer but unable to get the results.
Nodejs version 16.20.1
Puppeteer version 20.9.0

Nodejs can not be upgarded as RHEL 7.9 does not support later version nodejs.

### Expected results

PDF to be generated from the html link but i got timeout error.

### Actual results

It gives error for timeout also i have added timeout:0 as well.

Pleas help to get it resolved

**Comment by OrKoN** [comment]
Please see https://pptr.dev/troubleshooting and it appears that your system does not have all dependencies to run the browser (https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux). Also, use the dumpio flag to see what exactly the browser fails on.
