### ISSUE TITLE
Proposal: Rename page to puppeteer

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#108]
Proposal: Rename `page` to `puppeteer`

The `page` object currently has methods specific to the page, like navigation, as well as convenience methods that forward to the mainFrame or the input objects. Instead, we can have a `puppeteer` object that has all of our convenience methods (for example, anything that works with selectors) and extract page into its own small object.

**Comment by aslushnikov** [comment]
Discussed with @pavelfeldman one more time - decided not to do anything here for now.
