### ISSUE TITLE
clicking a link inside a frame does not work

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1081]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0-alpha
* Platform / OS version: Ubuntu 17.04 64 bits
* URLs (if applicable):

**What steps will reproduce the problem?**
does not find frame

_Please include code that reproduces the issue._
```
const Link = ('div.texto > button');
const Frame = await frame.$('#pkl', el => el.Link);
Frame.click();
```

**What is the expected result?**

**What happens instead?**
```
<iframe src="/datoa/?id=2342" id="pkl" style="width:380px;height:440px" frameborder="0">
<button type="button" class="contactSendEmailButton" onclick="location.href='/email/enviar-mensaje.php?id=197076847'">Click mel</button>

<iframe style="display: none !important; width: 1px !important; height: 1px !important; opacity: 0 !important; pointer-events: none !important;" name="_hjRemoteVarsFrame" title="_hjRemoteVarsFrame" id="_hjRemoteVarsFrame" src="https://vars.hotjar.com/rcj-99d43ead6bdf30da8ed5ffcb4f17100c.html"></iframe>

</iframe> 
```
> Is it possible that this frame is dynamic or generates a random key that I never find? with phantomjs / casperjs works fine with (casper.withFrame ('pkl', function () {just call the id="pkl"

**Comment by aslushnikov** [comment]
@fran0254 that's hard to judge what's going on here. Can you please file a new issue with your full script and URL where you experience this? This would allow us to reproduce this behavior locally and investigate.
