### ISSUE TITLE
[Bug]: setting headless: new means http urls are 307 redirected to https url (and back if it doesn't exsit)

### ISSUE THREAD

**Issue by dwsmart** [puppeteer/puppeteer#10825]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
(async () => {
const browser = await puppeteer.launch({headless: 'new'});
const page = await browser.newPage()

const redirects = [];

const client = await page.target().createCDPSession();
await client.send('Network.enable');
await client.on('Network.requestWillBeSent', (e) => {
    if (e.type !== "Document") {
        return;
    }
    redirects.push({url: e.documentURL, status: e.redirectResponse?.status} );
});

await page.goto('http://example.com/', {
    waitUntil: 'networkidle0'
});
console.log(redirects);
/*
* returns:
* [
*  { url: 'http://example.com/', status: undefined },
*  { url: 'https://example.com/', status: 307 }
* ]
*/
await browser.close();

})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

monitor and diagnose redirect chains

### Expectation

Load the http url as requested, and not redirect.

### Reality

url redirects, almost like it's using HSTS, even if there's no `Strict-Transport-Security` headers

### Puppeteer version

21.1.1

### Node version

16.17.1

### Package manager

npm

### Package manager version

9.6.6

### Operating system

Windows

**Comment by OrKoN** [comment]
That is consistent with the headful behaviour and, thus, working as intended for the new headless.
