### ISSUE TITLE
[Bug]: passing `headless:"new"` to `puppeteer.launch()` cause program blocked.

### ISSUE THREAD

**Issue by cuifanfan** [puppeteer/puppeteer#10824]
### Minimal, reproducible example

```TypeScript
// example.js
const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

(async () => {
  const browser = await puppeteer.launch({ headless: 'new' });
  const page = await browser.newPage();
  await page.goto(
    'file:///C:/Users/CUIFAN/Desktop/%E5%B4%94%E5%B8%86/%E5%AD%A6%E4%B9%A0demo/Node/puppeteer-demo/index.html'
  );
  const pdf = await page.pdf({
    // 隐藏页头页脚
    displayHeaderFooter: false,
    // 输出背景图
    printBackground: true,
    // 输出纸张格式
    format: 'a4',
    // 超时时间，这里的超时时间需要单独设置
    timeout: 180e3
  });

  fs.writeFile(path.join(__dirname, 'cuifan.pdf'), pdf, () => {});

  await browser.close();
})();
```

### Error string

    #error = new Errors_js_1.ProtocolError();   ^  ProtocolError: Page.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I've been trying to convert html to PDF successfully without `headless:"new"` to `puppeteer.launch()` , but it went wrong when I add this config.

### Expectation

I expected to fix this bug.

### Reality

I've been trying to convert html to PDF successfully without `headless:"new"` to `puppeteer.launch()` , but it went wrong when I add this config.

### Puppeteer configuration file (if used)

```TypeScript
no use
```

### Puppeteer version

21.1.1

### Node version

18.9.0

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Could add `dumpio` flag to the launch method and post the browser log?

**Comment by OrKoN** [comment]
Unable to reproduce.
