### ISSUE TITLE
[Bug]: `touchMove()` not firing `touchmove` event  if distance  is < 16px

### ISSUE THREAD

**Issue by nick-vincent** [puppeteer/puppeteer#10836]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  // open blank page
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setViewport({ width: 400, height: 300 });
  await page.goto('http://www.blankwebsite.com');

  // set up listeners
  await page.$eval('html', (el) => {
    ['touchstart', 'touchmove', 'touchend'].forEach((event) => {
      el.addEventListener(event, (e) => {
        const p = document.createElement('p');
        p.innerText = `${event} called: ${e?.touches?.[0]?.clientX}, ${e?.touches?.[0]?.clientY}`;
        document.body.prepend(p);
      });
    });
  });

  // touch & drag 15 pixels
  await page.touchscreen.touchStart(1, 1);
  await page.touchscreen.touchMove(1, 16); // does NOT fire
  await page.touchscreen.touchEnd();

  // touch & drag 16 pixels
  await page.touchscreen.touchStart(1, 1);
  await page.touchscreen.touchMove(1, 17); // does fire
  await page.touchscreen.touchEnd();

  // take screenshot
  await page.screenshot({ path: 'screenshot.png' });
  await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

(This is a follow-up to https://github.com/puppeteer/puppeteer/issues/10786 with further information)

I'm working in Stencil and trying to test that touch events are fired correctly.

I've discovered that the `touchmove` event does not seem to fire if the distance is less than 16px.

I've created a barebones Puppeteer example (no Stencil) to repro [here](https://github.com/nick-vincent/puppeteer-touch-move-bug/
).

```ts
// touch & drag 15 pixels
await page.touchscreen.touchStart(1, 1);
await page.touchscreen.touchMove(1, 16); // does NOT fire
await page.touchscreen.touchEnd();

// touch & drag 16 pixels
await page.touchscreen.touchStart(1, 1);
await page.touchscreen.touchMove(1, 17); // does fire
await page.touchscreen.touchEnd();
```

Screenshot output:

![screenshot](https://github.com/puppeteer/puppeteer/assets/31055081/bacb3155-b9f2-434c-b592-abd52e3e70d1)

### Expectation

I expect the `touchmove` event to fire even if the move was less than 16px.

### Reality

The `touchmove` event does not fire if the move was less than 16px.

### Puppeteer version

21.1.1

### Node version

20.3.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
@nick-vincent is it possible to verify if it fires if you manually move this distance?

**Comment by OrKoN** [comment]
Thanks for the details. I did some digging and I am not sure it's a bug either in CDP or Puppeteer. It seems to be the browser's behaviour to suppress some of the touchmove events https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/input/touch_event_manager.cc;l=495;drc=047c7dc4ee1ce908d7fea38ca063fa2f80f92c77 Note that touchmove might be throttled according to the spec:

```
Note that the rate at which the user agent sends touchmove events is implementation-defined, and may depend on hardware capabilities and other implementation details.
```
https://w3c.github.io/touch-events/#event-touchmove

**Comment by nick-vincent** [comment]
@OrKoN Thanks for your research and reply!

You actually got me down a rabbit hole and I think we finally have the answer:

> ## [Chrome's New Model: The Throttled Async Touchmove Model](https://developer.chrome.com/blog/a-more-compatible-smoother-touch/#chromes-new-model-the-throttled-async-touchmove-model)
>
> During active scrolling touchmove events are **throttled** to 1 event per **200ms**, or if a CSS **15px** slop region is exceeded

So it would seem that this is by design. Surprising that this blog post seems to be the only place it's documented!

(I basically had to perform a manual binary search to determine that the threshold is indeed 15px, heh.)

So I guess you can close this issue! At least it can be a breadcrumb for anyone coming across this in the future.
