### ISSUE TITLE
[Bug]: Loading a page with iframe and with networkidle0 always times out

### ISSUE THREAD

**Issue by psmyrek** [puppeteer/puppeteer#10838]
### Minimal, reproducible example

```TypeScript
const puppeteer = require( 'puppeteer' );

( async () => {
  const browser = await puppeteer.launch( {
    headless: 'new'
  } );

  const page = await browser.newPage();

  try {
    await page.goto( 'https://puppeteer-timeout.tiiny.site/', {
      waitUntil: [ 'load', 'networkidle0' ]
    } );
  } catch ( error ) {
    throw error;
  }

  await page.close();
  await browser.close();
} )();
```

### Error string

TimeoutError: Navigation timeout of 30000 ms exceeded

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

When the page contains an `<iframe>` that loads another HTML file in the `src` attribute, then the `page.goto()` with `networkidle0` always times out. Regardless of whether the path to the HTML file in the `src` attribute exists or not, `page.goto()` always ends with a timeout.

This error exists in both `headless: 'new'` and `headless: 'old'` modes.

Another minimal reproducible example using `express`:

```ts
express()
  .get( '/', function ( request, response ) {
    response
      .status( 200 )
      .type( 'text/html' )
      .send( '<iframe src="whatever.html"></iframe>' );
  })
  .listen( '8000', async () => {
     try {
       await page.goto( 'http://127.0.0.1:8000/', {
         waitUntil: [ 'load', 'networkidle0' ]
       } );
     } catch ( error ) {
       throw error;
     }
  } );
```

### Expectation

Loading a page with an `<iframe>` and with `networkidle0` should not end with a timeout.

### Reality

Loading a page with an `<iframe>` and with `networkidle0` always times out.

### Puppeteer version

21.1.1

### Node version

18.17.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by psmyrek** [comment]
No idea why this issue has been marked as not reproducible. I can easily reproduce it locally.

**Comment by OrKoN** [comment]
It's been fixed in chromium in the latest release.

**Comment by psmyrek** [comment]
@OrKoN Could you please share a link with the bug report or commit in Chromium?

**Comment by OrKoN** [comment]
It might have been https://bugs.chromium.org/p/chromium/issues/detail?id=1462258 or the linked Puppeteer CL.
