### ISSUE TITLE
Make open new tab/pages doesn't switch active window

### ISSUE THREAD

**Issue by rohmanhm** [puppeteer/puppeteer#1083]
### Steps to reproduce
When I create a new page it will change my active window to my new tab. Which is I don't like it because it will disturb me to type in another application.
Actually, I solved the problem by set `headless` mode to `true`. But, that's not what I like to do because I don't see the activity from my browser.

**Tell us about your environment:**

* Puppeteer version: 0.12-alpha
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
When Puppeteer launches new tab it wouldn't change my window active, so I can still continue typing in another application.

**What happens instead?**
When Puppeteer creates and launch new tab it's changed my active window to my new tab, so I can't type to my another app.
If I want to type to my another app I should switch window into it.

**Comment by aslushnikov** [comment]
> When Puppeteer launches new tab it wouldn't change my window active, so I can still continue typing in another application.

@rohmanhm I disagree. Most of the time pptr scripts want to work with the newly opened tabs, so this is a good default.

For your usecase, though, I'd suggest using [`page.bringToFront`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagebringtofront) method to activate tabs when necessary.

Hope this helps!

**Comment by avimar** [comment]
@aslushnikov have you tried this yourself?

When I'm coding, I write code with scraping and then run it on a separate screen.

While that's running with `headless:false`, it grabs the keyboard focus each time a new tab is opened, automatically.

I can't write new code or do anything else while _monitoring_ the script in another screen.

**Comment by aslushnikov** [comment]
> @aslushnikov have you tried this yourself?

@avimar No, I didn't try your setup, but it makes sense.

We can have a "background" option to the `page.newPage()` method to open tabs in the background. This will require some upstream work to support the functionality in the protocol. 

t's unlikely we'll have resources for this any time soon, but I'll be happy to give pointers and review PRs to both chromium and pptr.

**Comment by avimar** [comment]
It's not just new page API, even clicking a link with target blank does
this too.

Is there some systematic way to prevent chrome window from stealing focus?

**Comment by aslushnikov** [comment]
> It's not just new page API, even clicking a link with target blank does
this too.

@avimar ah, this becomes much more broad. Solving this in chromium would be very involved; I don't think it worth the effort.

I'd suggest exploring if it's possible to run chrome in a designated window manager. Another alternative would be using screencast feature when it's implemented: #478.

**Comment by avimar** [comment]
Do you have suggestions for such a designated window manager?

I'm running windows 7 with Dexpot, but actually, the chromium windows automatically pops up on the whichever desktop I'm on.
I looked for some windows 7 anti-focus-stealing, but most it seems only work for windows XP.

I'm actually not sure why chromium ever needs to steal focus? For when a popup windows opens?

**Comment by aslushnikov** [comment]
> Do you have suggestions for such a designated window manager?

@avimar Not on windows; on linux, you might be able to run a nested X windows. 

> I'm actually not sure why chromium ever needs to steal focus?

Me neither; I'm not familiar with chromium focus logic/requirements.

It seems to me that the feasible solution for this would be screencasting; it should be quite cheap when implemented. Closing this in favor of #478.

**Comment by lehni** [comment]
For those coming here looking for a remedy on macOS, there is actually a way to achieve this by modifying `node_modules/puppeteer/.local-chromium/mac-******/chrome-mac/Chromium.app/Contents/Info.plist` and adding this to the beginning:

```xml
<key>LSBackgroundOnly</key>
<string>True</string>
```

So that the file starts like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>LSBackgroundOnly</key>
  <string>True</string>
  <key>BuildMachineOSBuild</key>
```

For more info: https://www.cnet.com/news/keep-applications-from-stealing-focus-when-opening-in-os-x/

**Comment by lopugit** [comment]
> For those coming here looking for a remedy on macOS, there is actually a way to achieve this by modifying `node_modules/puppeteer/.local-chromium/mac-******/chrome-mac/Chromium.app/Contents/Info.plist` and adding this to the beginning:
> 
> ```
> <key>LSBackgroundOnly</key>
> <string>True</string>
> ```
> 
> So that the file starts like this:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>   <key>LSBackgroundOnly</key>
>   <string>True</string>
>   <key>BuildMachineOSBuild</key>
> ```
> 
> For more info: https://www.cnet.com/news/keep-applications-from-stealing-focus-when-opening-in-os-x/

but???? this is just the equivalent of running `puppeteer.launch({headless: true})` ?????

**Comment by lehni** [comment]
@lopugit it is not. You still see the window, it just doesn't steal input focus, so you can keep typing while your system runs e2e tests, for example, but you can keep having an eye on them too.

**Comment by lopugit** [comment]
@lehni it does not open the window for me :'( just behaves like headless = true

**Comment by lehni** [comment]
@lopugit that's strange... On my Mac, the window opens, but does not come to the foreground. Could it be that it's there but hidden by other applications on yours?

**Comment by padamczewski** [comment]
@lehni: The window doesn't open for me as well. Looks like it's run in _headless_ mode.

**Comment by leadscloud** [comment]
> For those coming here looking for a remedy on macOS, there is actually a way to achieve this by modifying `node_modules/puppeteer/.local-chromium/mac-******/chrome-mac/Chromium.app/Contents/Info.plist` and adding this to the beginning:
> 
> ```
> <key>LSBackgroundOnly</key>
> <string>True</string>
> ```
> 
> So that the file starts like this:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>   <key>LSBackgroundOnly</key>
>   <string>True</string>
>   <key>BuildMachineOSBuild</key>
> ```
> 
> For more info: https://www.cnet.com/news/keep-applications-from-stealing-focus-when-opening-in-os-x/

**That's not work for me.**


# **[Solution]:**

solution at this 

[Execution hangs when browser window goes to background
#3156](https://github.com/puppeteer/puppeteer/issues/3156#issuecomment-530609246)


when add 

```
<key>LSBackgroundOnly</key>
<string>True</string>
```

after need also add below chromeArgs

```
const chromeArgs = [
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-renderer-backgrounding'
];
```

**Comment by dougpagani** [comment]
The above solution from @leadscloud does not seem to work anymore.
