### ISSUE TITLE
right click seems don't work

### ISSUE THREAD

**Issue by plantain-00** [puppeteer/puppeteer#1084]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:0.12.0
* Platform / OS version:mac os 10.12.6
* URLs (if applicable):https://plantain-00.github.io/tree-component/demo/vue/index.html

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. a.js
```js
const puppeteer = require("puppeteer");

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.emulate({ viewport: { width: 1440, height: 900 }, userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" });

    await page.goto(`https://plantain-00.github.io/tree-component/demo/vue/index.html`);

    await page.click(".contextmenu .tree-anchor-0-0", { button: "right" }); // right click a node at `contextmenu` part
    await page.waitFor(1000);
    await page.screenshot({ path: `a.png`, fullPage: true });

    browser.close();
})();
```
2.see the generated screenshot, if right click success, the custom contextmenu should appear

**What is the expected result?**

the custom contextmenu should appear in the screenshot

**What happens instead?**

the custom contextmenu didn't appear in the screenshot, seems the right click doesn't work

**Comment by aslushnikov** [comment]
Might be relevant to #1082

**Comment by JoelEinbinder** [comment]
The fullPage screenshot is actually what is causing you problems. You have a `mouseleave` listener on your element to remove the context menu. Taking a fullPage screenshot scrolls the viewport to the top of the page, which causes the mouse to be in a different position on screen, which causes the `mouseleave` event to fire and the context menu to be hidden.

You can take a regular screenshot, or always set your height to be the size of your content instead of 900.

**Comment by a-y-u-s-h** [comment]
@JoelEinbinder I don't understand how to solve this, can you please elaborate? I'm visiting a site that I didn't create (let's take google images for example) and I want to simply right click, and return a screenshot of the viewport with context menu. Is there a way to deal with it? I'm trying to take a screenshot without fullpage, but the context menu still doesn't show up.

**Comment by kaussandeep** [comment]
@a-y-u-s-h  I dont think this has to do with screenshot. 
I have a similar problem and the Context menu after right click fails sometimes.
