### ISSUE TITLE
[Bug]: Could not find expected browser (chrome)

### ISSUE THREAD

**Issue by munna-aziz-hridoy** [puppeteer/puppeteer#10842]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";
import { generateBarcode } from "src/@core/utils/server";

export async function labelPrint(req, res) {
  if (req.method === "POST") {
    const browser = await puppeteer.launch({
      headless: false,
    });
    const page = await browser.newPage();

    const { data, type, size } = req.body;

    let width = size?.width || 2.84;
    let height = size?.height || 1.5;

    const content = await Promise.all(
      data?.map(async (p) => {
        const barcodeImage = await generateBarcode(p?.barcode);

        let htmlElement;

        if (type === "With Expiry Date") {
          htmlElement = `
         <div style="margin: auto">
          <h2 style="font-size: 18px; font-weight: 600; margin: 0">
            ${p?.name}
          </h2>
          <div
            style="
              display: flex;
              justify-content: space-between;
              align-items: center;
              margin: 0;
            "
          >
            <div style="margin: 0">
              <p style="font-size: 18px; font-weight: 600; margin: 0">¥${p?.price}</p>
              <p style="font-size: 13px; margin: 0">Exp: ${p?.expiryDate}</p>
            </div>
            <div>
              <img style="width: 120px; margin-top: 15px;" src="${barcodeImage}" alt="" />
            </div>
          </div>
         </div>
    `;
        } else if (type === "Name Price Barcode") {
          htmlElement = `
         <div style="margin: auto">
          <h2 style="font-size: 18px; font-weight: 600; margin: 0">
            ${p?.name}
          </h2>
          <div
            style="
              display: flex;
              justify-content: space-between;
              align-items: center;
              margin: 0;
            "
          >
            <div style="margin: 0">
              <p style="font-size: 18px; font-weight: 600; margin: 0">¥${p?.price}</p>
            </div>
            <div>
              <img style="width: 120px; margin-top: 15px;" src="${barcodeImage}" alt="" />
            </div>
          </div>
         </div>
    `;
        } else {
          htmlElement = `
         <div style="margin: auto">
          <h2 style="font-size: 22px; font-weight: 600; margin: 0">
            ${p?.name}
          </h2>
          <div
            style="
              display: flex;
              justify-content: space-between;
              align-items: center;
              margin: 0;
            "
          >
            <div style="margin: 0">
              <p style="font-size: 22px; font-weight: 600; margin: 0">¥${p?.price}</p>
            </div>
            <div>
            </div>
          </div>
         </div>
    `;
        }

        return htmlElement;
      })
    );

    const joinedContent = content.join(
      '<div style="page-break-after: always;"></div>'
    );

    await page.setContent(joinedContent);
    const pdfBuffer = await page.pdf({
      width: `${width}in`,
      height: `${height}in`,
      printBackground: true,
    });

    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      'attachment; filename="generated-pdf.pdf"'
    );
    res.send(pdfBuffer);
  } else {
    res.status(405).send({ message: `Method ${req.method} is not allowed` });
  }
}
```

### Error string

Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1045629).

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

I expect it's work on server

### Reality

It's working on my local mechine but not working after deployment

### Puppeteer version

21.1.1

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Have yo tried following the instructions for [Could not find expected browser locally](https://pptr.dev/troubleshooting#could-not-find-expected-browser-locally)?
The error you are getting is for Puppeteer `18.0.5` till `19.1.2` which given that you say locally you are running  Puppeteer `21.1.1` means you are not updating dependencies on deploy.
Please insure that `npm i` is run and the browser is downloaded, you can check the [default cache director](https://pptr.dev/guides/configuration#changing-the-default-cache-directory).

**Comment by munna-aziz-hridoy** [comment]
I've tried the following instruction you provided. It didn't work for me. 
It's giving bellow error: 
`Error: Cannot find module '../generated/injected.js'
Require stack:
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ScriptInjector.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CustomQueryHandler.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/GetQueryHandler.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ElementHandle.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Browser.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/api/api.js
- /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js
- /var/task/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
- /var/task/.next/server/pages/api/label-print.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Hook._require.Module.require (/var/task/___vc/chunk-J4RLMXQF.js:2130:38)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ScriptInjector.js:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ScriptInjector.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CustomQueryHandler.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/GetQueryHandler.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ElementHandle.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Browser.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/api/api.js',
    '/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js',
    '/var/task/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js',
    '/var/task/.next/server/pages/api/label-print.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ]
}
RequestId: b89177cc-abd7-4611-9e38-9047f4f4a41e Error: Runtime exited with error: exit status 1
Runtime.ExitError`

My package.json file: 
`{
  "name": "project-name,
  "description": "Most Powerful & Comprehensive Free MUI React NextJS Admin Dashboard Template built for developers! 🚀",
  "license": "MIT",
  "version": "1.0.0",
  "author": {
    "name": "ThemeSelection",
    "url": "https://themeselection.com/"
  },
  "bugs": {
    "url": "https://github.com/themeselection/materio-mui-react-nextjs-admin-template-free/issues"
  },
  "private": false,
  "repository": {
    "type": "git",
    "url": "https://github.com/themeselection/materio-mui-react-nextjs-admin-template-free.git"
  },
  "homepage": "https://themeselection.com/products/materio-free-mui-react-nextjs-admin-template/",
  "keywords": [
    "react",
    "javascript",
    "admin",
    "typescript",
    "dashboard",
    "material-design",
    "nextjs",
    "material-ui",
    "admin-dashboard",
    "free",
    "mui",
    "admin-template",
    "admin-panel",
    "freebies",
    "nextjs-template",
    "react-dashboard",
    "themeselection"
  ],
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "export": "next export",
    "lint": "eslint --fix \"src/**/*.{js,jsx}\"",
    "format": "prettier --write \"src/**/*.{js,jsx}\""
  },
  "dependencies": {
    "@emotion/cache": "^11.6.0",
    "@emotion/react": "^11.7.0",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.6.0",
    "@mui/lab": "^5.0.0-alpha.70",
    "@mui/material": "^5.4.3",
    "@woocommerce/woocommerce-rest-api": "^1.0.1",
    "apexcharts-clevision": "3.28.5",
    "babel-eslint": "^10.1.0",
    "bwip-js": "^4.1.1",
    "clsx": "^1.1.1",
    "eslint-plugin-react": "^7.29.4",
    "firebase": "^10.3.1",
    "fs": "^0.0.1-security",
    "marked": "^7.0.5",
    "mdi-material-ui": "^7.1.0",
    "next": "12.0.4",
    "nprogress": "^0.2.0",
    "puppeteer": "^21.1.1",
    "react": "17.0.2",
    "react-apexcharts": "^1.3.9",
    "react-datepicker": "^4.5.0",
    "react-dom": "17.0.2",
    "react-firebase-hooks": "^5.1.1",
    "react-hot-toast": "^2.4.1",
    "react-icons": "^4.10.1",
    "react-images-uploading": "^3.1.7",
    "react-perfect-scrollbar": "^1.5.8",
    "react-popper": "^2.2.5",
    "react-table": "^7.8.0",
    "styled-components": "^6.0.7",
    "uuid": "^9.0.0"
  }
}
`

**Comment by Lightning00Blade** [comment]
It looks like you using Next.JS when bundling (for production build) it may cause issues with Puppeteer.
Can you please provide a minimal reproducible repo where this error is observed,
without it it would be very hard determine what the issue is and how to fix it?

**Comment by actuallymentor** [comment]
Anyone finding this from Google: downgrade to puppeteer `16.2.0`.

This is one of those cases where GCP and Puppeteer don't work well together and both think it's your problem to fix, and to be fair none of us are paying for Puppeteer 🤷

**Comment by actuallymentor** [comment]
Circling back, I managed to get the latest puppeteer working doing the following (and I'm not sure what exactly solved it):

1. Add these scripts to `package.json:scripts`

```
    "postinstall": "node node_modules/puppeteer/install.mjs",
    "gcp-build": "npx puppeteer browsers install"
```

2. Create a `puppeteer.config.js` in my `functions` folder with this content:

```js
const { join } = require( 'path' )

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {

    // Default approach
    cacheDirectory: join( __dirname, '.cache', 'puppeteer' ),
    
    // Hardcoded path found by console.log(import.meta.dirname)
    // env var is default in GCP: https://cloud.google.com/functions/docs/configuring/env-var#runtime_environment_variables_set_automatically
    ...process.env.FUNCTION_TARGET && { cacheDirectory: '/workspace/.cache/puppeteer' }, 

    
}
```

For those who are still running into issues, consider a (completely overkill) fallback approach like this:

```js
export async function start_puppeteer() {

    // Function dependencies
    const { default: puppeteer } = await import( "puppeteer" )
    const { log } = await import( "mentie" )

    // Start browser
    const options = {
        args: [ '--no-sandbox', '--disable-setuid-sandbox', '--allow-running-insecure-content', '--ignore-certificate-errors', '--no-default-browser-check' ],
        headless: true
    }

    // Executable paths
    const executablePaths = [
        async () => null, // default
        async () => '/usr/bin/chromium', // expected firebase cloud location
        async () => '/opt/homebrew/bin/chromium', // homebrew install path
        async () => '/usr/bin/google-chrome', // expected google cloud location

        // Puppeteer-chromium-resolver, this downloads chromium if not found
        async () => {

            const { default: PCR } = await import( "puppeteer-chromium-resolver" )
            const stats = await PCR( options )
            log.info( `Puppeteer-chromium-resolver stats:`, stats )
            return stats.executablePath

        }
    ]

    // Keep track of browser start attempts
    let tried_executable_paths = 0
    let browser = null
    while( !browser && tried_executable_paths < executablePaths.length ) {

        try {
            const executablePath = await executablePaths[ tried_executable_paths ]()
            log( `Attempting to start puppeteer with executable path (attempt ${ tried_executable_paths }):`, executablePath )
            browser = await puppeteer.launch( { ...options, executablePath } )
            log.info( `Puppeteer browser started with executable path attempt ${ tried_executable_paths + 1 } of ${ executablePaths.length + 1 }:`, executablePath )

        } catch ( e ) {
            log( `Failed to launch puppeteer (attempt ${ tried_executable_paths + 1 }): `, e.message )
        }

        tried_executable_paths++

    }

    return browser

}
```

If you use the above, make sure to set your `concurrency` setting to something you are comfortable with (I'm at `{ concurrency: 5, memory: "4GiB" }` because the `puppeteer-chromium-resolver` downloads chromium if it is unavailable, and download artefacts are not shared across instances. Without concurrency you run the risk of downloading chromium on every function run.
