### ISSUE TITLE
[Bug]: Unable to use latest Puppeteer in a Docker container

### ISSUE THREAD

**Issue by pidgezero-one** [puppeteer/puppeteer#10855]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
import express from 'express';

export const app = express();
const port = 3003;

app.get('/screenshot', async (req, res) => {
  try {
    const browser = await puppeteer.launch({headless: "new"}); // error happens here with or without headless setting
    const page = await browser.newPage();
    await page.goto('https://example.com');
    const screenshot = await page.screenshot();
    await browser.close();

    res.writeHead(200, {
      'Content-Type': 'image/png',
      'Content-Length': screenshot.length,
    });
    res.end(screenshot);
  } catch (error) {
    console.error(error);
    res.status(500).send('An error occurred');
  }
});
```

### Error string

TargetCloseError: Protocol error (Target.setAutoAttach): Target closed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This is a minimum reproducible example of a problem I'm having in a larger-scale app that uses Puppeteer and runs in a Docker container. In my primary app, I've narrowed it down to the `puppeteer.launch` method. I started seeing this issue after upgrading my app to use Node 18 and the latest version of Puppeteer (last working version is on Node 12 and Puppeteer 12). This bug has been happening for me regardless of whether or not I launch the browser in headless mode. 

The host machine I'm running this on is a M1 Mac, but the production environment is Cloud Run, so I'm specifying amd64 architecture. With early attempts to debug this issue, I was also seeing this error in the Cloud Run environment, and eventually gave up on deploying it until I could get it to work locally. I'm launching the container with `docker-compose up -d --build`.

My dockerfile:
```
FROM ghcr.io/puppeteer/puppeteer:latest
EXPOSE 3003
WORKDIR /app
COPY package*.json ./
USER root
RUN chown -Rh pptruser:pptruser /app
USER pptruser
RUN npm install
COPY . .
RUN npm run build
CMD ["npm", "run", "start"]
```

My docker-compose.yml (my daemon is running with 8 GB memory allocated, so the 4096 memory limit shouldn't be a concern):
```
version: "3"
services:
  puppeteer-test:
    build:
      context: .
      dockerfile: ./build-config/Dockerfile
    environment:
      PORT: 3003
    ports:
      - 3003:3003
    volumes:
      - .:/app
    platform: linux/amd64
    privileged: true
    deploy:
      resources:
        limits:
          memory: 4096M
```
My package.json:
```
{
  "name": "puppeteer-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "npx tsc",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node dist/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/express": "^4.17.17",
    "express": "^4.18.2",
    "puppeteer": "^21.1.1"
  },
  "devDependencies": {
    "@types/node": "^20.5.9",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }
}
```

I've been troubleshooting this issue for about three weeks now to no avail, and have tried more things than I can reasonably list, but some other things I've attempted that give me the same error messages have been:
- using the chrome.json from [this article](https://gigi.nullneuron.net/gigilabs/running-puppeteer-under-docker/) (did not appear to have an impact)
- SSHing into my docker container and running Chrome manually (produces dbus errors, more details [here](https://stackoverflow.com/questions/77004162/puppeteer-docker-protocol-error-target-setautoattach-target-closed))
- trying different base docker images like ubuntu 20.04 and node 18
- installing chrome manually via the dockerfile instead of via puppeteer
- using `/opt/google/chrome/google-chrome` as my executable path
- explicitly specifying `/home/pptruser/.cache/puppeteer` as my path in a puppeteer config file, but this minimum example does not include a config file

I'm not providing a Node or npm version, because I don't know what they are. They're whichever node and npm versions are used by the most up-to-date version of the [docker base image provided by this repo](https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile), since I'm using `ghcr.io/puppeteer/puppeteer:latest` as my base.

### Expectation

Navigating to localhost:3003/screenshot in a browser should present a screenshot image in the browser tab (which it does when I run the codebase in a terminal instead of via docker).

### Reality

Navigating to localhost:3003/screenshot in a browser produces a blank page with simply the text "An error occurred", with error messages present in my docker logs.

### Puppeteer version

21.1.1

### Node version

18.x.x

### Package manager

npm

### Package manager version

?.?.?

### Operating system

macOS

**Comment by OrKoN** [comment]
Does it sounds like https://github.com/puppeteer/puppeteer/issues/9763 ? Note that we still don't have arm64 binaries for Linux. Does turning on the Rosetta emulation for Docker help?

**Comment by OrKoN** [comment]
Note that we run a [test](https://github.com/puppeteer/puppeteer/blob/main/docker/test/smoke-test.js) using the Docker image we provide and they are [successful on GitHub Actions](https://github.com/puppeteer/puppeteer/blob/main/.github/workflows/ci.yml#L352). Does the same test run for your host?

**Comment by pidgezero-one** [comment]
@OrKoN Does turning on Rosetta emulation involve anything other than just running `docker build` in a Rosetta terminal, or is there some other setting I have to supply (other than `linux/amd64` being specified in my dockerfile)?

The contents of the test you link seem to be basically the same as the code that executes on my `/screenshot` endpoint, unless there's something I'm missing in what you're telling me. Thanks for the reply!

**Comment by OrKoN** [comment]
I think it needs to be turned on in Docker Desktop settings: `Use Rosetta for x86/amd64 emulation on Apple Silicon` (https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5)

**Comment by pidgezero-one** [comment]
Oh, I don't use Docker Desktop, I use a combination of Colima and Portainer. I'll have to see if there's some kind of equivalent with that stack.

**Comment by pidgezero-one** [comment]
Update: I was able to use Rosetta for Colima:

```
colima start -a x86_64 --cpu 4 --memory 8 --vm-type=vz --mount-type=virtiofs --network-address --vz-rosetta --dns=1.1.1.1
```

I don't think this makes a difference, but I ran my `docker build` command in a Rosetta terminal as well. Unfortunately, it's still leading to the same error.

**Comment by Varkoff** [comment]
> Does it sound like #9763 ? Note that we still don't have arm64 binaries for Linux. Does turning on the Rosetta emulation for Docker help?

Thank you @OrKoN, I spent the whole day figuring out why my Dockerfile was not working with puppeteer, using `--platform=linux/amd64` on macOS.

It was as simple as enabling Rosetta emulation

**Comment by Varkoff** [comment]
> > > Does it sound like #9763 ? Note that we still don't have arm64 binaries for Linux. Does turning on the Rosetta emulation for Docker help?
> 
> > 
> 
> > Thank you @OrKoN, I spent the whole day figuring out why my Dockerfile was not working with puppeteer, using `--platform=linux/amd64` on macOS.
> 
> > 
> 
> > It was as simple as enabling Rosetta emulation
> 
> 
> 
> What docker context do you use? If it's docker desktop, then I suspect my bug might be colima-related (I don't use docker desktop).

Yes I'm using macOS Docker Desktop.
