### ISSUE TITLE
[Bug]: Rendering a pdf with an empty div that has flex and gap styles, hangs it indefinitely

### ISSUE THREAD

**Issue by jorgebastida** [puppeteer/puppeteer#10852]
### Steps to reproduce

(1) Using Chromium 884014 (92.0.4512.0) : puppeteer-core 10.1.0
(2) Loading the the page content using setContent()
(3) Rendering a pdf of a page with the following content, makes the render hang forever:

`<html><head></head><body><div style="display: flex; gap: 1rem;"></div></body></html>`

(4) If you add any element inside, or text content, it works as expected.

Note: I'm unsure if this is actually a puppeteer bug or a chromium bug, so I reported it here too: https://bugs.chromium.org/p/chromium/issues/detail?id=1479318

### Expected results

Not to hang

### Actual results

It hangs indefinitely

**Comment by Lightning00Blade** [comment]
Running 
```ts
      await page.setContent(
        '<html><head></head><body><div style="display: flex; gap: 1rem;"></div></body></html>'
      );
      await page.pdf({});
```
On latest Puppeteer work without any issue, so closing this issue.

Next time please use the correct template for the `puppeteer` package, as this one is for the `@puppeteer/browsers`.
