### ISSUE TITLE
Allow page use some privacy?

### ISSUE THREAD

**Issue by maicss** [puppeteer/puppeteer#1086]
**Tell us about your environment:**

* Puppeteer version: 0.12
* Platform / OS version: Mac OS 10.12.6
* URLs (if applicable): like google.com or maps.google.com

**Comment by ebidel** [comment]
It's not clear what this is asking for. Can you elaborate on the request and what you're trying to do?

**Comment by maicss** [comment]
![image](https://user-images.githubusercontent.com/9784767/31752473-c2f15b66-b450-11e7-9a22-ebe6407de9a0.png)

How to `Allow` or `Block`.

And others like : Audio etc.

**Comment by Garbee** [comment]
Duplicate of #846

**Comment by aslushnikov** [comment]
@maicss please upvote the issue if you're interested in it to be fixed. We're looking at the most-upvoted issues first.

**Comment by maicss** [comment]
how? add a thumb emoji to https://github.com/GoogleChrome/puppeteer/issues/846 ?

**Comment by ebidel** [comment]
@maicss that works

**Comment by saselovejulie** [comment]
i really need this..

**Comment by GentJashari** [comment]
is this fixed?

**Comment by GentJashari** [comment]
@aslushnikov Is this fixed?
