### ISSUE TITLE
[Bug]: Cannot use the browser immediately after installing it

### ISSUE THREAD

**Issue by rgl** [puppeteer/puppeteer#10867]
### Steps to reproduce

With an empty cache (`~/.cache/puppeteer` does not exist), after installing the browser using `browsers.install`, we cannot use the browser with `puppeteer.launch`.

You can reproduce the problem with the code at https://github.com/rgl/try-puppeteer-in-bun:

```bash
git clone https://github.com/rgl/try-puppeteer-in-bun.git
cd try-puppeteer-in-bun
bun install --frozen-lockfile
rm -rf ~/.cache/puppeteer
bun run main.js
```

### Expected results

Expected it to launch the just installed browser.

### Actual results

It fails with:

```
2023-09-09T14:17:43.077Z Downloading the browser Chrome/116.0.5845.96...
2023-09-09T14:17:49.732Z Launching the browser...
610 |   }
611 |   get stdio() {
612 |     return this.#stdioObject ??= this.#createStdioObject();
613 |   }
614 | 
615 |   spawn(options) {
                 ^
ESRCH: No such process
 syscall: "open"
   errno: -3

      at spawn (node:child_process:615:14)
      at node:child_process:2:40
      at new Process (/home/vagrant/Projects/try-puppeteer-in-bun/node_modules/@puppeteer/browsers/lib/esm/launch.js:104:31)
      at launch (/home/vagrant/Projects/try-puppeteer-in-bun/node_modules/@puppeteer/browsers/lib/esm/launch.js:58:11)
      at /home/vagrant/Projects/try-puppeteer-in-bun/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:60:31
      at processTicksAndRejections (:1:2602)
```

**Comment by OrKoN** [comment]
@rgl does it reproduce in node?

**Comment by rgl** [comment]
@OrKoN, it does work fine with node 18.17.1, but not with bun 1.0.0.

**Comment by OrKoN** [comment]
@rgl is it the problem with bun perhaps?

**Comment by rgl** [comment]
I forgot to mention, the second time its executed in bun, it works fine. It only fails when starting with a clean cache.

**Comment by OrKoN** [comment]
I see, it would sound like some of the buns API are not completely compatible. Note that we don't support bun so if you can figure out what's the difference between bun and node, I would recommend filing an issue against bun.
