### ISSUE TITLE
click sometimes hits the autocompletion DIV instead of 'input[type=submit]'

### ISSUE THREAD

**Issue by ldenoue** [puppeteer/puppeteer#1087]
Unfortunately, page.click('input[type=submit]') seems to click the overlay that appears after the page.type(...).

Instead of using page.click, I'm using:
await page.keyboard.press('Enter');

https://github.com/GoogleChrome/puppeteer/blob/4f64dfd9935e87c2752a4db04867b4a9928c2cd3/examples/search.js#L29

**Comment by aslushnikov** [comment]
@ldenoue the `page.click` mimics user mouse, so if the `page.click` sometimes interferes with the overlay, so would be the user.

Your workaround with `enter` is perfectly fine. Also, you can use `page.mouse` and explicitly pass it coordinates to click.
