### ISSUE TITLE
[Bug]: Failed to open the website link in the PUPPETEER

### ISSUE THREAD

**Issue by jaytheblogger** [puppeteer/puppeteer#10877]
### Minimal, reproducible example

```TypeScript
const bot = require("puppeteer");
const fs = require("fs");

const botConfiguration = {
headless: false,
executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe",
userDataDir: "C:/Users/bot/AppData/Local/Google/Chrome/User Data/",
args: [
'--profile-directory=Profile 28'
]
};

async function runBot() {
const chromeBrowser = await bot.launch(botConfiguration)
const chromeBrowserPage = await chromeBrowser.newPage()
await chromeBrowserPage.goto("https://www.google.com/")
};

runBot();
```

### Error string

ERROR : Failed to launch the browser process!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

i want to open particular chrome "profile 28" with the link of website i have provided

### Reality

first error in terminal error
error: Failed to launch the browser process!

second error it was not able to open website link

third it was successful to open particular chrome profile i wanted the code to open

### Puppeteer version

21.1.1

### Node version

v20.5.0

### Package manager

npm

### Package manager version

9.8.0

### Operating system

Windows

**Comment by OrKoN** [comment]
I am unable to reproduce on my end. What do the logs say if add dumpio: true to the launch?

**Comment by jaytheblogger** [comment]
problem is solved after i closed all the chrome profile that was open.............

but new error in terminal started showing up it says...........

[Puppeteer old Headless deprecation warning:]

In the near future headless: true will default to the new Headless mode for Chrome instead of the old Headless implementation. For more information, please see https://developer.chrome.com/articles/new-headless/. Consider opting in early by passing headless: "new" to puppeteer.launch() If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

**Comment by OrKoN** [comment]
Running multiple instances from the same user data dir is not supported indeed.
