### ISSUE TITLE
[Bug]: Failed to open the website link in the PUPPETEER

### ISSUE THREAD

**Issue by jaytheblogger** [puppeteer/puppeteer#10871]
### Steps to reproduce

`const bot = require("puppeteer");
const fs = require("fs");

const botConfiguration = {
headless: false,
executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe",
userDataDir: "C:/Users/bot/AppData/Local/Google/Chrome/User Data/",
args: [
'--profile-directory=Profile 28'
]
};

async function runBot() {
const chromeBrowser = await bot.launch(botConfiguration)
const chromeBrowserPage = await chromeBrowser.newPage()
await chromeBrowserPage.goto("https://www.google.com/")
};

runBot();``

### Expected results

i want to open particular chrome Profile 28 with the website link i have provided

### Actual results

first error in terminal error
error: Failed to launch the browser process!

second error it was not able to open website link

third it was successful to open particular chrome profile i wanted the code to open

**Comment by OrKoN** [comment]
The bug filed under the wrong category. Please use the main bug form and provide all details required there. I have tested this locally and unable to reproduce.
