### ISSUE TITLE
[Bug]: Page.goBack() in for loop

### ISSUE THREAD

**Issue by Issac-Nguyen** [puppeteer/puppeteer#10885]
### Minimal, reproducible example

```TypeScript
async function testGoback() {
  let i =0;
  while (i < 2) {
    await googlePage.goto('https://24h.com.vn');
    console.log('googlePage.browserContext-'+i);
    console.log(googlePage.browserContext());
    await googlePage.goBack();
    i++;
  }
}
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

for loop 2 times but stuck at line googlePage.goBack();, and the code can not continue to next step.

### Expectation

code can run without stuck at goBack() function in forloop.

### Reality

code stuck at goBack() function in forloop

### Puppeteer version

21.1.1

### Node version

20.6.0

### Package manager

npm

### Package manager version

9.8.1

### Operating system

macOS

**Comment by OrKoN** [comment]
Not able to repro on the latest version with:

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
});
const page = await browser.newPage();

await page.goto(
  'https://google.com'
)
async function testGoback() {
  let i = 0;
  while (i < 2) {
    await page.goto('https://24h.com.vn');
    console.log('page.browserContext-' + i);
    console.log(page.browserContext());
    await page.goBack();
    console.log(
      'went back'
    )
    i++;
  }
}

await testGoback();
await browser.close()
```

**Comment by Issac-Nguyen** [comment]
@OrKoN I can repro this on my local, you need to check wil config headless: false. Below is my code:

const browser = await puppeteer.launch({
    headless: false,
});
const page = await browser.newPage();

await page.goto('https://google.com')
async function testGoback() {
  let i = 0;
  while (i < 2) {
    await page.goto('https://24h.com.vn');
    await page.goBack();
    console.log(
      'went back'
    )
    i++;
  }
}

await testGoback();
await browser.close()

Expected flow: go to google.com -> 24h.com.vn -> go back to google.com -> 24h.com.vn -> go back
Current flow: go to google.com -> 24h.com.vn  -> go back to google.com and stuck here.

**Comment by Issac-Nguyen** [comment]
I just checked and it worked as expected on version 21.2.0. Thanks @OrKoN!
