### ISSUE TITLE
[Bug]: double --disable-features ignores first instance

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#10883]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
console.log(puppeteer); throw new Error('😩');
```

### Error string

😩

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Running devtools interaction tests.. I get this:

![image](https://github.com/puppeteer/puppeteer/assets/39191/c3205ec8-7871-4e33-ac28-a90b9cc9f3db)

I shouldn't get this if `--disable-features=MediaRouter` is set. Looking at the flags that chrome launches with it has two disable-features sets:

`--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints  --disable-features=Prerender2`

It would (definitely) be great if Chrome merged those two but it doesn't. So the second instance wipes out the first.

relevant source, came in recently with the tab target stuff (#10790 #10818): https://github.com/puppeteer/puppeteer/blob/d08ad5fbbe3be4349dd6132c209895f8436ae9e6/packages/puppeteer-core/src/node/ChromeLauncher.ts#L182-L185

--------

devtools repo repro:

```sh
npm run auto-screenshotstest
# note the new prompt
```

### Expectation

no popups about allowing network traffic. (also if you log with `--enable-logging=stderr --v=2` you'll see just how busy that mediarouter is.. sheeeesh!)

### Reality

the intended features werent disabled.

### Puppeteer version

21.1.1

### Node version

19.6.0

### Package manager

npm

### Package manager version

9.4.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Oh, thanks for spotting this!
