### ISSUE TITLE
[Bug]: Puppeteer old Headless deprecation warning:

### ISSUE THREAD

**Issue by jaytheblogger** [puppeteer/puppeteer#10882]
### Steps to reproduce

`const puppeteer = require("puppeteer");
const fs = require("fs");

const botConfiguration = {
  headless: false,
  executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
  userDataDir: "C:/Users/bot/AppData/Local/Google/Chrome/User Data/",
  args: [
    `--profile-directory=Profile 28`
  ]
};

async function runBot() {
  const browser = await puppeteer.launch(botConfiguration);
  await puppeteer.launch();
  const Page = await browser.newPage();
  await Page.goto("https://www.google.com/");
}

runBot();`

### Expected results

want to see no issues in my terminal

### Actual results

Puppeteer old Headless deprecation warning:
.............................

In the near future headless: true will default to the new Headless mode for Chrome instead of the old Headless implementation. For more information, please see https://developer.chrome.com/articles/new-headless/. Consider opting in early by passing headless: "new" to puppeteer.launch() If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

**Comment by markman641** [comment]
I don't want to use the new mode as it uses way more CPU. How do I set the "PUPPETEER_DISABLE_HEADLESS_WARNING"? I tried in both ways below and it didn't work:

`        const browser = await puppeteer.launch({headless: true, PUPPETEER_DISABLE_HEADLESS_WARNING: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--PUPPETEER_DISABLE_HEADLESS_WARNING'
            ]});`

**Comment by CodeRevolutionPlugins** [comment]
I also am not able to disable the warning using PUPPETEER_DISABLE_HEADLESS_WARNING, any help appreciated.

**Comment by O-Q** [comment]
see [this](https://github.com/puppeteer/puppeteer/blob/9673b1f562ed023ebcc6278fef79ecf6def266c0/packages/puppeteer-core/src/node/ChromeLauncher.ts#L52):

you should set `PUPPETEER_DISABLE_HEADLESS_WARNING` to "true" in the environment variable or change the log level.
