### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID received when ignoring HTTPS errors

### ISSUE THREAD

**Issue by TimFletcher** [puppeteer/puppeteer#1088]
Follow up from #861

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: OS X 10.12.6
* URLs (if applicable): https://www.lexdray.com

**What steps will reproduce the problem?**

The following code throws an exception:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  try {
    await page.goto('https://www.lexdray.com', {
      waitUntil: 'networkidle',
      ignoreHTTPSErrors: true,
    });
  } catch (err) {
    console.log(err.message);
  } finally {
    browser.close();
  }
})();
```

**What is the expected result?**

Site is able to be loaded successfully, ignoring any HTTPS errors.

**What happens instead?**

An SSL certificate Error is received: `SSL Certificate error: ERR_CERT_COMMON_NAME_INVALID`. There's two issues at play here:

1. I'm ignoring HTTPS errors, yet still receiving an error
2. I don't think this site has any issue with its SSL certificate.

**Additional Information**
- No errors in Chrome's security panel
- Certificate appears fine [when tested with SSL labs](https://www.ssllabs.com/ssltest/analyze.html?d=www.lexdray.com)

**Comment by simongroom** [comment]
I am having a similar issue. The error code I receive is different - but may be related...
**Environment:**

- Ubuntu
- Puppeteer V 0.12

**What steps will reproduce the problem?**

`const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  let url = 'https://middleware-dev3.netdirect.ca:8888/desktop/index.html#pdf_report/1/1/2304';
  await page.goto(url, {
      waitUntil: 'networkidle',
      ignoreHTTPSErrors: true
  });
  await page.pdf({path: '/tmp/hn.pdf', format: 'A4'});
  await browser.close();
})();`

**What is the expected result?**

load site successfully, ignoring any HTTPS errors.

**What happens instead?**

> Cmiddleware@middleware-dev3:~$ node devruncdsm/test_puppetteer_reports.ts
(node:8836) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SSL Certificate error: ERR_CERT_AUTHORITY_INVALID
(node:8836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gajus** [comment]
Cannot replicate the issue in v0.13.

**Comment by TimFletcher** [comment]
I just tried my code with `0.13.0-alpha` and have the same error I reported in the original issue.

**Comment by gajus** [comment]
Try launching Chrome with `--disable-setuid-sandbox` flag.

**Comment by ricardobruno** [comment]
Hello guys,

I may be missing something, but from a quick look, this looks like a syntax issue, and not necessarily a bug.

@TimFletcher would you try the syntax below:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true
  });

  const page = await browser.newPage();
  try {
    await page.goto('https://www.google.com', {
      waitUntil: 'networkidle'
    });
  } catch (err) {
    console.log(err.message);
  } finally {
    browser.close();
  }
})();
```

@simongroom would you try the syntax below:
```
const puppeteer = require('puppeteer');

(async () => {
const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true
});
const page = await browser.newPage();
let url = 'https://www.google.com';
await page.goto(url, {
      waitUntil: 'networkidle'
    });
await page.pdf({path: '/tmp/google.pdf', format: 'A4'});
await browser.close();
})();
```

PS: To fully test it, you will need to replace the URL with one that triggers a certificate error.

**Reference:**
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions
I only see the ignoreHTTPSErrors within the options of `puppeteer.connect`, and `puppeteer.launch`.
Trying to use it within `page.goto` might have been the issue.

I hope this helps, cheers!

-RB

**Comment by TimFletcher** [comment]
Bingo. Thanks @ricardobruno That was it!

**Comment by simongroom** [comment]
@ricardobruno Thanks - not sure how I missed that, but that change has fixed my issue too.
