### ISSUE TITLE
Page.click() behaves differently than HTMLElement.click()

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1089]
This was a gotcha I ran into when using `Page.click()`:

`Page.click()` scrolls to the element and clicks the very center of it. The scroll to part is ok, but the latter behavior is different from what `HTMLElement.click()` does.

A twitter card with an embedded link to another tweet is a good example of where things can go wrong:

<img width="649" alt="screen shot 2017-10-18 at 8 16 29 am" src="https://user-images.githubusercontent.com/238208/31726788-b3933c44-b3dc-11e7-888d-667f8c20d928.png">

When you call `Page.click()` on that twitter card, pptr clicks the center of the element which is the "web component experience" link area. That's unexpected.

Is there a way we can restrict the click to the target element or wrap `HTMLElement.click()` so both methods are consistent with each other?

cc @JoelEinbinder

**Comment by aslushnikov** [comment]
@ebidel you can always fall back to `HTMLElement.click` for this case.

The twitter example is indeed a good example: every other time I navigate somewhere when in fact I want to open a tweet..
