### ISSUE TITLE
[Bug]: Errors thrown after doing history restoration on page with oopifs/workers

### ISSUE THREAD

**Issue by adamraine** [puppeteer/puppeteer#10892]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: false,
  defaultViewport: null,
  ignoreDefaultArgs: ['--enable-automation'],
  executablePath: process.env.CHROME_PATH,
});
const page = await browser.newPage();
const session = await page.target().createCDPSession();

await session.send('Page.enable');

await page.goto('http://localhost:10200/oopif-scripts.html', {
  waitUntil: ['networkidle0'],
});

await new Promise(r => setTimeout(r, 500));

const history = await session.send('Page.getNavigationHistory');
const entry = history.entries[history.currentIndex];

await session.send('Page.navigate', {url: 'chrome://terms'});

await new Promise(r => setTimeout(r, 500));

await session.send('Page.navigateToHistoryEntry', {entryId: entry.id});

await session.send('Page.disable');

await page.close();
await browser.close();
```

### Error string

Protocol error (Network.enable): Target closed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This is a minified version of how Lighthouse tests the bfcache: https://github.com/GoogleChrome/lighthouse/blob/main/core/gather/gatherers/bf-cache-failures.js#L89

The latest release of puppeteer (21.2.0) has broken this behavior on our test page [`oopif-scripts.html`](https://github.com/GoogleChrome/lighthouse/blob/main/cli/test/fixtures/oopif-scripts.html). All the code needed to serve this test page can be found under the `fixtures` directory that contains `oopif-scripts.html`.

### Expectation

I expected the code to run without throwing any errors or emitting uncaught exceptions. I verified that this is still the behavior for version 21.1.1.

### Reality

The script throws an error.

### Puppeteer version

21.2.0

### Node version

18.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
@adamraine I am unable to reproduce with the bundled version of Chrome for Testing. Do you test with a different Chrome version? Or is it flaky for you?

**Comment by adamraine** [comment]
This is happening with all Chrome version for me. I was using Chrome canary as well as the Chrome that ships in puppeteer.

If it helps, you can serve the test page I was using from a checkout out version of https://github.com/GoogleChrome/lighthouse by running `yarn static-server`, and then the page is available at `http://localhost:10200/oopif-scripts.html`. I haven't gotten this failure on any other page so perhaps there is something unique here going on.

**Comment by OrKoN** [comment]
I have also checked out the version but I used `npx http-server . -p 10200` from the folder containing oopif-scripts.html
