### ISSUE TITLE
Add a flag to ignore webSockets when using {waitUntil: 'networkidle'}

### ISSUE THREAD

**Issue by tibdex** [puppeteer/puppeteer#1090]
Hi,

I like the simplicity of the `{waitUntil: 'networkidle'}` option for generating PDFs as in:

https://github.com/GoogleChrome/puppeteer/blob/aa58f25bc1c7f8cf72c70c453f036bb873349164/examples/pdf.js#L24-L31

https://github.com/GoogleChrome/puppeteer/pull/38 changed the implementation of the `networkidle` check to wait for all created webSockets to be closed before resolving.
However, some web applications keep webSockets open all the time to be notified of interesting events by the server.

It would be nice to benefit from all the logic of `networkidle` while ignoring webSockets.

This could be done by setting `networkIdleInflight` to value greater than 0. The drawback is that it would consider an app with 2 pending HTTP requests to be idle when I would consider one idle only if there were 0 pending HTTP requests and any amount of webSockets open.

So, can we add an `ignoreWebSockets` flag next to `networkIdleInflight` and `networkIdleTimeout`?

I would be happy to send a PR if this proposition is approved.

**Comment by aslushnikov** [comment]
@tibdex in v0.13.0-alpha (current tip of tree) websockets are unconditionally ignored for `networkidle0` / `networkidle2` signals. This happened with our migration to protocol-generated lifecycle events.
