### ISSUE TITLE
page.addScriptTag not working on 0.12?

### ISSUE THREAD

**Issue by pilgerone** [puppeteer/puppeteer#1091]
Hey guys,

On Debian Jessie, running
```
browser = await puppeteer.launch({headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox', '--user-agent="Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"']});
page = await browser.newPage();
await page.goto('https://some.page.com', {waitUntil: 'load'});
await page.exposeFunction('foo', (e) => { console.log("Received " + e); });
var bar = page.addScriptTag({path: '/home/user/node/bar.js'});
browser.close();
```
and considering bar.js being
```
window.foo('test!');
```

I get no response on my console. No error. Nothing.

I should see 'Received test', right!?

**Comment by vsemozhetbyt** [comment]
I think
```js
var bar = page.addScriptTag({path: '/home/user/node/bar.js'});
```
should be
```js
await page.addScriptTag({path: '/home/user/node/bar.js'});
```

**Comment by pilgerone** [comment]
I was bumping into a Content Security Policy restriction. Only found out when I ran chromium *headful*.

Is it expected behavior not to get any errors in this case? Shouldn't we get something back to make debugging a bit easier?

**Comment by aslushnikov** [comment]
Thanks @pilgerone, I filed a separate issue for pages with CSP: https://github.com/GoogleChrome/puppeteer/issues/1229

Please thumb-up it to get it fixed sooner!
