### ISSUE TITLE
page click not fire

### ISSUE THREAD

**Issue by EasonWang01** [puppeteer/puppeteer#1092]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
newest
* Platform / OS version:
windows 10
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```js
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');
const iPhone = devices['iPhone 5'];


puppeteer.launch({headless: false}).then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://google.com');
  const inputElement = await page.$('input[type=submit]');
  await inputElement.click();
  
  // ...
});


```

click not fire.

![222](https://user-images.githubusercontent.com/11001914/31765929-acd756ac-b4f8-11e7-80f0-0cba61bafc18.png)

**What is the expected result?**

**What happens instead?**

**Comment by xprudhomme** [comment]
Could you be more precise about your issue? Because your description is very light, it does not help at all understanding your issue.

From what I see, if you only try to click on the "search" button from Google home page, without even sending a keyword to the search input text, it's 100% normal that nothing happens when you hit the search button.

Try it manually, no event is fired unless you fill in the search input...

**Comment by alixaxel** [comment]
I tried the following snippet:

```javascript
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');
const iPhone = devices['iPhone 5'];

puppeteer.launch({headless: false}).then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.type('[name="q"]', 'hello world');
  const inputElement = await page.$('input[type=submit]');
  await inputElement.click();
  await page.waitFor(5000);
  await page.screenshot({
    path: 'snap.png',
  });
  await browser.close();
});
```

And I get the same result (search results now shown). However, if I set `headless` to `true`, it works.

Seems to be the same issue as described in #1125 & #1126.

**Comment by aslushnikov** [comment]
CLosing as dupe of #1126
