### ISSUE TITLE
Is possible to obtain a website's favicon url?

### ISSUE THREAD

**Issue by Folyd** [puppeteer/puppeteer#1093]
Is possible to obtain a website's favicon url just like Chrome extension api `chrome.tabs.Tab.favIconUrl`?

Link: [https://developer.chrome.com/extensions/tabs#type-Tab](https://developer.chrome.com/extensions/tabs#type-Tab)

**Comment by Garbee** [comment]
You can try requesting the favicon on the domain root and if that fails then query the document for a `rel="icon"` tag and get it from that.

There is no direct API for this. What is your use-case for needing it programatically?

**Comment by Folyd** [comment]
@Garbee Thanks for replying. I can get a website favicon url by this wey:
```js
document.querySelector('link[rel="shortcut icon"]').href
```
