### ISSUE TITLE
Tabs gives same info [Bug]: 

### ISSUE THREAD

**Issue by PMLS3** [puppeteer/puppeteer#10934]
### Minimal, reproducible example

```TypeScript
const caseNumber = await page.$eval(
      '#c_CaseNumberLabel',
      (el: { innerText: any }) => {
        return el.innerText
      },
    )
```

### Error string

no error, just wrong data

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to go trough a site where when you click a case in a table it opens a new tab inside the page, when I want to scrape the data it gives me the same data back as the first scrape i have done on the first case tab I have opened and closed. 

### Expectation

New Data for each tab

### Reality

Getting same data back even though the tab has other data inside

### Puppeteer version

21.2.1

### Node version

v20.5.1

### Package manager

pnpm

### Package manager version

8.7.6

### Operating system

macOS

**Comment by OrKoN** [comment]
Sorry, there is not enough information to either reproduce or understand what the bug is. Consider posting the question to StackOverflow.

**Comment by PMLS3** [comment]
Thanks @OrKoN , here a small reproduciton 
https://github.com/PMLS3/puppeteer-tabs-test.git
