### ISSUE TITLE
[Bug]: Puppeteer does not honer hyphens: auto

### ISSUE THREAD

**Issue by schaakverslaafd** [puppeteer/puppeteer#10947]
### Minimal, reproducible example

```TypeScript
Render an HTML with long words in a paragraph with CSS style hyphens: auto to PDF.
```

### Error string

-

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Creating a PDF of HTML pages with hyphens: auto are not rendered with hyphens.
Tried this with the old and the new headless mode. And also with the executablePath pointing to chrome and the userDataDir pointing to the 'chrome user data dir'. (And starting chrome normally hyphens are rendered.)

I wondered if I missed something and this should be working already because I understood the new headless mode should render more i the same way as the browser normally does.

See #6840.

### Expectation

A pdf with hypens when using the CSS style hyphens: auto.

### Reality

A pdf without hyphens.

### Puppeteer version

21.0.3

### Node version

18.12.0

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Could you provide the repro? In general, PDF rendering bugs can be sent to crbug.com as the implementation is not part of Puppeteer.

**Comment by OrKoN** [comment]
Would you mind posting the issue including the example to crbug.com?

**Comment by schaakverslaafd** [comment]
Thx for your reply!
https://bugs.chromium.org/p/chromium/issues/detail?id=1486763
