### ISSUE TITLE
[Bug]: Unit test "[keyboard.spec] Keyboard should report multiple modifiers" should not use legacy properties of key events

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#10950]
### Minimal, reproducible example

```TypeScript
See details in the background section for the affected Puppeteer unit test.
```

### Error string

Expected: \"Keydown: ; Semicolon 186 [Alt Control]\"\nReceived: \"Keydown: ; Semicolon 59 [Alt Control]\

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

The mentioned test uses legacy properties for key events which are not standardized and differ between browsers. Those properties are `.which` and `.charCode`:

https://github.com/puppeteer/puppeteer/blob/d98f488a514ff9b3bb06923b4fb2d9bfb5919cec/test/src/keyboard.spec.ts#L257-L298
https://github.com/puppeteer/puppeteer/blob/d98f488a514ff9b3bb06923b4fb2d9bfb5919cec/test/assets/input/keyboard.html#L12-L20

The test should be changed to only use standardized properties like `.key`, `.code` and maybe `.data` to verify that the right keys were pressed.

https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html is a good help here.

@OrKoN can you please have a look? Thanks!

### Expectation

Test has to pass in Firefox as well and not fail because legacy properties are used which on purpose are different between browsers.

### Reality

The test fails because of inappropriate checks.

### Puppeteer version

latest

### Node version

latest

### Package manager

npm

### Package manager version

latest

### Operating system

macOS

**Comment by OrKoN** [comment]
@jrandolf PTAL

**Comment by whimboo** [comment]
@jrandolf thanks a lot!
