### ISSUE TITLE
[Bug]: puppeteer@21.3.1 is leaking HeadlessChrome in the user agent

### ISSUE THREAD

**Issue by Kikobeats** [puppeteer/puppeteer#10952]
puppeteer@21.3.1 is leaking `HeadlessChrome` in the user agent under `{ headless: 'new' }`

It can be verified doing `page.evaluate('window.navigator.userAgent')`:

https://github.com/microlinkhq/browserless/actions/runs/6246025551/job/16955830227?pr=517#step:6:48

puppeteer@21.2.1 works fine:

https://github.com/microlinkhq/browserless/actions/runs/6246025551/job/16955830227?pr=517#step:6:46

### Minimal, reproducible example

```
page.evaluate('window.navigator.userAgent')
```

### Expectation

It's unsure if it's happening because `{ headless: 'new' }` stop working

### Puppeteer version

21.3.1

### Node version

18.17.1

### Package manager

npm

### Package manager version

8.7.6

### Operating system

Linux

**Comment by OrKoN** [comment]
Looks like Chrome decided to change it back (AFAIK original plan was to match headful mode): https://bugs.chromium.org/p/chromium/issues/detail?id=1443649  https://chromium-review.googlesource.com/c/chromium/src/+/4692205

Puppeteer just exposes what the browser reports.
