### ISSUE TITLE
page.type has Emoji issues (UTF-8)

### ISSUE THREAD

**Issue by mittermayr** [puppeteer/puppeteer#1096]
Two-folded issue. Some Emojis aren't typed correctly (others seem to work, randomly). And newlines are also ignored (so is `keyboard.press('Enter')`). The solution for newline treatment is to split the text by "\n" and then do line by line, with a `page.type("#target", String.fromCharCode(13));` at the end of it.

### Steps to reproduce

* Puppeteer version: 0.13.0-alpha
* Platform / OS version: OSX, also Debian 9

An empty HTML file, only has the following inside (it also doesn't work with the `<meta charset='utf-8'>` tag added, no difference):

`<textarea id="theTarget"></textarea>`

The code that causes the problem:

`var sample = Buffer.from("8J+RuSBUb2t5byBzdHJlZXQKSmFwYW4g8J+Hr/Cfh7Ug", 'base64').toString('utf8');
await page.type("#theTarget", sample);`

Even without the Buffer and decoding, if you just use the following, it won't work:
`await page.type("#theTarget", "👹 Tokyo street");`

**What is the expected result?**

👹 Tokyo street
Japan 🇯🇵

**What happens instead?**

 Tokyo streetJapan 

**Comment by dosten** [comment]
Hi! Do you found a solution for this issue? I'm having the same issue.

**Comment by JoelEinbinder** [comment]
It unfortunately isn't a high priority at the moment.

**Comment by JoelEinbinder** [comment]
The keyboard event we are abusing to send accepts a 4 character UTF16 string, but it only uses the first character. This is causing large emoji characters to be truncated.

WebKit sends a `char` event for emoji, but Chromium doesn't. So we should add a new protocol method to send just an `input` event.

**Comment by vadimmelnicuk** [comment]
Any updates on the issue?

**Comment by aslushnikov** [comment]
This is fixed on tip-of-tree;  please give it a shot installing the @next version:

```js
npm i puppeteer@next
```

**Comment by vadimmelnicuk** [comment]
I can confirm that the fix works for me. Thanks, @aslushnikov

**Comment by aslushnikov** [comment]
> I can confirm that the fix works for me. Thanks, @aslushnikov

Credits go to @JoelEinbinder  :)

**Comment by vadimmelnicuk** [comment]
@JoelEinbinder thanks for the emoji fix! @aslushnikov however, it seems like it wasn't included in the latest release i.e., 1.6.2. Are you planning to add the fix to 1.6.3?

**Comment by JoelEinbinder** [comment]
As this wasn’t a regression, it will come in the 1.7.0 release.

**Comment by aslushnikov** [comment]
v1.7.0 is out 🎉Type your emoji now! 🔥

**Comment by obiwankenoobi** [comment]
@aslushnikov so I thought `puppeteer@next` fixed my issue - but it did only on my local machine. When I deployed the app to heroku it still showing squares and not emojis. You have any idea why maybe??

**Comment by nollytainment** [comment]
> @aslushnikov so I thought `puppeteer@next` fixed my issue - but it did only on my local machine. When I deployed the app to heroku it still showing squares and not emojis. You have any idea why maybe??

Hey man! did you get around to getting this working? kinda stuck here at the moment.
