### ISSUE TITLE
[Bug]: chrome core dumps are filling up disk space and causing instance to run out of disk space 

### ISSUE THREAD

**Issue by hari-mani** [puppeteer/puppeteer#10965]
### Minimal, reproducible example

```TypeScript
async screenshot(url: string): Promise<Buffer | string> {
    const browser = await puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: [
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--no-sandbox',
          '--disable-dev-profile',
          '--single-process',
          '--no-zygote']});
    try {
      const page = await browser.newPage();
      await page.setUserAgent(USER_AGENT);
      await page.setRequestInterception(true);
      page.on('request', async (request: HTTPRequest) => {
        console.log(request);
        await request.continue();
      });
      await page.setViewport({
        width: 1280,
        height: 800,
        deviceScaleFactor: 1,
      });
      await page.goto(pageUrl, {
        waitUntil: 'load',
        timeout: 60000,
      });
      return await page.screenshot({
        type: 'png',
        clip: {
          x: 0,
          y: 0,
          width: 1280,
          height: 800,
        },
      });
    } catch (err: any) {
      console.error(err);
      throw err;
    } finally {
      await browser.close();
    }
  }
```

### Error string

kernel: traps: chrome[6291] trap int3 ip:558443b94136 sp:7ffcf71b5310 error:0 in chrome[55843f3a3000+ad2e000]

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We have a service that takes in a URL as input and returns a screenshot of the page which is deployed in a container, recently we've been observing the disk space of the instance in which this service is deployed filling up, on checking the reason for this we found out that there were a lot of `core.*` binary files which we being written to the disk which is what is causing the disk space to get filled up. We are not able to reproduce the issue in all of our environments but this behaviour is consistent in our production environment, we are suspecting the volume of requests being served by the service in production environment to be reason why the issue is not reproducible in lower environments. 

### Expectation

`core.*` binary files should not be written when the screenshot of the page is taken

### Reality

`core.*` binary files are getting created causing the instance to run out of memory 

### Puppeteer version

19.6.3

### Node version

18.12.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
I believe you need to disable coredumps on your environment.
