### ISSUE TITLE
[Bug]: ws does not work in the browser. Browser clients must use the native WebSocket object

### ISSUE THREAD

**Issue by ddm50** [puppeteer/puppeteer#10976]
### Minimal, reproducible example

```TypeScript
export default async function Start() {
    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
        executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',

    });
    const page = await browser.newPage();


    await page.setViewport({ width: 1920, height: 1080});
}
```

### Error string

ws does not work in the browser. Browser clients must use the native WebSocket object

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This is with Electron, no idea why it happens. I used it in the past, never had an issue. And without Electron it works fine, but within Electron when I launch it does not.

### Expectation

To work

### Reality

ws does not work in the browser. Browser clients must use the native WebSocket object

### Puppeteer version

21.3.1

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not sure as well. It should work as long as Electron is classified as Node `export const isNode = !!(typeof process !== 'undefined' && process.version);` Not sure perhaps something has changed in Electron? Can you debug it?

**Comment by ddm50** [comment]
> I am not sure as well. It should work as long as Electron is classified as Node `export const isNode = !!(typeof process !== 'undefined' && process.version);` Not sure perhaps something has changed in Electron? Can you debug it?

It seemed to be due to import instead of require.

**Comment by OrKoN** [comment]
I think you need to troubleshoot it with Electron. We ship both cjs and esm formats so you can use either import or require (not sure which import/require you mean). We do not officially support Electron so you would need to find a configuration that works you. If you have a patch that will help to run Puppeteer in Electron, we are happy to review it.

**Comment by sky124380729** [comment]
> > I am not sure as well. It should work as long as Electron is classified as Node `export const isNode = !!(typeof process !== 'undefined' && process.version);` Not sure perhaps something has changed in Electron? Can you debug it?
> 
> It seemed to be due to import instead of require.

I encountered the same problem，have you resolved it ?

**Comment by Juraj-Masiar** [comment]
I'm trying to upgrade from puppeteer 15.5.0 to current 22.6.5 and I'm getting this error.
Maybe the stack trace could help:
```
ws does not work in the browser. Browser clients must use the native WebSocket object

      17 |     this.promise = (async () => {
      18 |       const pathToExtension = path.join(process.cwd(), 'chrome_dev');
    > 19 |       this.browser = await puppeteer.launch({
         |                      ^
      20 |         headless: false,
      21 |         devtools,
      22 |         slowMo,

      at new Object.<anonymous>.module.exports (node_modules/ws/browser.js:4:9)
      at node_modules/puppeteer-core/src/node/NodeWebSocketTransport.ts:20:18
      at Function.create (node_modules/puppeteer-core/src/node/NodeWebSocketTransport.ts:19:12)
      at ChromeLauncher.createCdpSocketConnection (node_modules/puppeteer-core/src/node/ProductLauncher.ts:297:48)
      at ChromeLauncher.launch (node_modules/puppeteer-core/src/node/ProductLauncher.ts:160:27)
      at e2e/bootstrap.ts:19:22
      at Object.<anonymous> (e2e/legacy_long.test.spec.ts:12:5)

Test Suites: 1 failed, 1 total
```

**Comment by Juraj-Masiar** [comment]
I've found a workaround here: https://stackoverflow.com/a/75816520/1376947
1. remove `testEnvironment: 'jsdom',` from the "jest.config.js"
2. now pupeteer will work, but your normal "jest" tests will likely not. To fix that, append ` --env=jsdom` to your test script command, fro example: `"test": "jest --maxWorkers=25% --testPathPattern=\"./src|./test\" --env=jsdom",`

See also: https://github.com/mqttjs/MQTT.js/issues/1141
