### ISSUE TITLE
[Bug]: page.exposeFunction working in webpack development mode but not in webpack production mode 

### ISSUE THREAD

**Issue by harvansh265** [puppeteer/puppeteer#10978]
### Minimal, reproducible example

```TypeScript
const consoleLog = (data) =>{
     console.log('consoleLog' , data)
 }
 const browser = await puppeteer.launch({headless :false , protocolTimeout: 0});
 const page = await browser.newPage();
 await page.exposeFunction('consoleLog' , consoleLog);
 await page.goto(targeturl , {waitUntil:'domcontentloaded'});
 await page.evaluate(() => {
     consoleLog('Log from evaluate');
 })
```

### Error string

Its not throw any error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

page.exposeFunction working in webpack development mode but not in webpack production mode 

### Reality

page.exposeFunction working in webpack development mode but not in webpack production mode 

### Puppeteer version

21.3.1

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by OrKoN** [comment]
Make sure that function names are not minified by Webpack (or other tools).

**Comment by OrKoN** [comment]
In particular, the minification should be off for this part:

```
 await page.evaluate(() => {
     consoleLog('Log from evaluate');
 })
 ```
 
 Alternatively, define evaluated functions as strings.

**Comment by harvansh265** [comment]
But it should throw error like that function is not defined but its not throwing any error even i am using try/catch
