### ISSUE TITLE
how can I go from version 0.12.0 to version 0.13.0-alpha

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1097]
how can I go from version 0.12.0 to version 0.13.0-alpha  to solve certain problems?

**Comment by vsemozhetbyt** [comment]
`npm install https://github.com/GoogleChrome/puppeteer/`

**Comment by fran0254** [comment]
Thank you. I thought I was going to solve the problems of clicking inside the iframes :-(

**Comment by aslushnikov** [comment]
@fran0254 clicking inside the iframes should be solved; what exactly is not working for you?

**Comment by fran0254** [comment]
I want to click on the id inside the frame "click me". (the frame is inside a modal window)

  ```
<div id="modal1" style="text-align: right; top: 709px; left: 490.5px;"><a href="javascript:cerrarw()" class="cerrarw">Cerrar [X]</a><br>

<iframe src="/renovar/?id=238722392" id="ifrw" style="width:380px;height:500px" frameborder="0">

<a id="lren" href="javascript:fczvjrx('238722392','renovar')">Click me</a>

</iframe></div>
```
the code I'm trying to use:

  ```
 const selector = '#lren';
const Frame = await page.frames()[0]; // I have tried with [1], [2] etc ...
await Frame.$eval(selector, el => el.click());
```
Out:

(node:28349) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: failed to find element matching selector "#lren"
(node:28349) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
