### ISSUE TITLE
[Bug]: Evaluate not working for data url.

### ISSUE THREAD

**Issue by runtomaker** [puppeteer/puppeteer#10981]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: false, args: ['data:text/html,home']});

    const pages = await browser.pages();

    var page = pages[0];

    console.log('evaluate');

    await page.evaluate(() => {
    	alert('called')
    });

    console.log('load url');

    await page.goto('https://google.com');
})();
```

### Error string

no error

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background
When calls with **browser.connect** always working. but not working with **browser.launch**. Only Linux.

_No response_

### Expectation

When the browser starts, the data url is loaded, then an alert is displayed and load new url.

### Reality

When evaluate and load url.

### Puppeteer version

21.3.1

### Node version

20.6.1

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Linux

**Comment by OrKoN** [comment]
I am not sure what is the issue exactly: could you clarify? alert is blocking so nothing else can happen in the browser. Use the dialog event to control the alerts `page.on('dialog', dialog => dialog.dismiss())`.
