### ISSUE TITLE
[Bug]: Error: `puppeteer_product` is not a valid npm option

### ISSUE THREAD

**Issue by AAlex-11** [puppeteer/puppeteer#10982]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    product: 'firefox',
    args: ["--no-sandbox"]
  });
  const [page] = await browser.pages();
....
```

### Error string

Error: Could not find Firefox (rev. latest).

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

PS E:\Angular\JS> set PUPPETEER_PRODUCT=firefox
PS E:\Angular\JS> node Puppeteer\Start.js
E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:303
                    throw new Error(`Could not find Firefox (rev. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Firefox (rev. latest). This can occur if either
 1. you did not perform an installation for Firefox before running the script (e.g. `PUPPETEER_PRODUCT=firefox npm install`) or
 2. your cache path is incorrectly configured (which is: C:\Users\Razen\.cache\puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at FirefoxLauncher.resolveExecutablePath (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:303:27)
    at FirefoxLauncher.executablePath (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\node\FirefoxLauncher.js:145:21)
    at FirefoxLauncher.computeLaunchArguments (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\node\FirefoxLauncher.js:94:38)
    at async FirefoxLauncher.launch (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:79:28)
    at async E:\Angular\JS\Puppeteer\Start.js:5:19

Node.js v18.17.0

### Expectation

we expect checking any product workable by default on most usable customer's environment - Windows 10 and Firefox - this environment using more than 90% of any user environments, please check firstly - is your product working in Windows 10 / Firefox and only then in more rare environment like Mac, Linux and other

### Reality

0 verbose cli D:\nodejs\node.exe D:\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@10.0.0
2 info using node@v18.17.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:D:\nvm\v18.17.0\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:E:\Angular\JS\.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:C:\Users\Razen\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:D:\nodejs\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 8ms
17 timing npm:load:configload Completed in 8ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm config set puppeteer_product=firefox
22 verbose argv "config" "set" "puppeteer_product=firefox"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:C:\Users\Razen\AppData\Local\npm-cache\_logs\2023-09-21T17_59_21_623Z-
26 verbose logfile C:\Users\Razen\AppData\Local\npm-cache\_logs\2023-09-21T17_59_21_623Z-debug-0.log
27 timing npm:load:logFile Completed in 7ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 42ms
31 info config set "puppeteer_product" "firefox"
32 timing command:config Completed in 2ms
33 verbose stack Error: `puppeteer_product` is not a valid npm option
33 verbose stack     at Config.set (D:\nvm\v18.17.0\node_modules\npm\lib\commands\config.js:156:15)
33 verbose stack     at Config.exec (D:\nvm\v18.17.0\node_modules\npm\lib\commands\config.js:118:22)
33 verbose stack     at Config.cmdExec (D:\nvm\v18.17.0\node_modules\npm\lib\base-command.js:142:17)
33 verbose stack     at Npm.exec (D:\nvm\v18.17.0\node_modules\npm\lib\npm.js:136:20)
33 verbose stack     at module.exports (D:\nvm\v18.17.0\node_modules\npm\lib\cli-entry.js:61:15)
34 verbose cwd E:\Angular\JS
35 verbose Windows_NT 10.0.22621
36 verbose node v18.17.0
37 verbose npm  v10.0.0
38 error `puppeteer_product` is not a valid npm option
39 verbose exit 1
40 timing npm Completed in 140ms
41 verbose code 1
42 error A complete log of this run can be found in: C:\Users\Razen\AppData\Local\npm-cache\_logs\2023-09-21T17_59_21_623Z-debug-0.log

### Puppeteer version

not started

### Node version

v18.17.0

### Package manager

npm

### Package manager version

10.0.0

### Operating system

Windows

**Comment by OrKoN** [comment]
I believe you need to run npm install with the product env variable set to download Firefox.

**Comment by OrKoN** [comment]
I am not able to reproduce the "puppeteer_product is not valid npm option" error. Please check that you are not providing this option to npm.

**Comment by AAlex-11** [comment]
I have installed firefox and if I try to use in configuration
        executablePath: "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
firefox started and immediately shutdown


node Puppeteer\Start.js
E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:42
    #error = new Errors_js_1.ProtocolError();
             ^

ProtocolError: Protocol error (Fetch.enable): Fetch.enable RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:18:5
UnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:101:7
execute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13
receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45

    at <instance_members_initializer> (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:42:14)
    at new Callback (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:46:16)
    at CallbackRegistry.create (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:86:26)
    at Connection._rawSend (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:208:26)
    at CdpCDPSession.send (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:61:33)
    at #applyProtocolRequestInterception (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\NetworkManager.js:220:24)
    at E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\NetworkManager.js:172:20
    at Array.map (<anonymous>)
    at #applyToAllClients (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\NetworkManager.js:171:60)
    at NetworkManager.setRequestInterception (E:\Angular\JS\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\NetworkManager.js:211:38)

Node.js v18.17.0

**Comment by AAlex-11** [comment]
about reproducing "puppeteer_product is not valid npm option"
try to set system variable
set PUPPETEER_PRODUCT=firefox
than simple start puppeteer with

    const browser = await puppeteer.launch({
        headless: false,
        product: 'firefox',

**Comment by AAlex-11** [comment]
this is two bugs I mention above, with FF path and without it
![Puppeteer-09222023_000844](https://github.com/puppeteer/puppeteer/assets/138773344/0630152b-0a72-4f90-a8ec-488a3008681e)

**Comment by AAlex-11** [comment]
and I have all correct setting in Firefox, including compatibility with chrome

 
![Puppeteer-09222023_001421](https://github.com/puppeteer/puppeteer/assets/138773344/18da5d9b-038d-47ce-bcfc-41178d9c95b7)

**Comment by OrKoN** [comment]
@AAlex-11 did you run npm install after setting the env variable? it's not in the logs you share and I am not able to reproduce on my machine.

**Comment by AAlex-11** [comment]
Yes, of course, look to this screen please and screen I sended you above

![Puppeteer-09242023_102630](https://github.com/puppeteer/puppeteer/assets/138773344/d2dd6ed0-a4a3-46c8-a53e-89e5125461b7)

**Comment by OrKoN** [comment]
@AAlex-11 that is the different error coming from a successfully installed Firefox.
