### ISSUE TITLE
[Bug]: Behaves differently locally than in a github-action

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [puppeteer/puppeteer#11007]
### Minimal, reproducible example

```TypeScript
Repo: https://github.com/ThibaultJanBeyer/DragSelect/tree/refactor/turborepo/DragSelect
I.e. failing remotely: https://github.com/ThibaultJanBeyer/DragSelect/actions/runs/6278010709/job/17050896924?pr=186
```

### Error string

Various expects will have different results

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I’m using puppeteer heavily for functional testing of my selection, drag and drop library, however, unfortunately, when I run my tests locally (i.e. moving mouse to coordinates X,Y and then pressing down and then moving to X+10,Y+20 and then releasing and then getting the selected values) behave differently (will output different elements between the coordinates) than within a github action.

### Expectation

It should be exactly the same no matter which environment it is run on

### Reality

In reality it is not

### Puppeteer configuration file (if used)

```TypeScript
launch: {
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    timeout: 30000,
    headless: true,
    dumpio: true, // Whether to pipe the browser process stdout and stderr
  },
```

### Puppeteer version

21.3.3

### Node version

20.3.1

### Package manager

pnpm

### Package manager version

8.7.6

### Operating system

macOS

**Comment by OrKoN** [comment]
Are you adjusting your tests for the device pixel ratio?

**Comment by OrKoN** [comment]
If you could extra a minimal example from your code that demonstrates the issue, it'd be really helpful.

**Comment by ThibaultJanBeyer** [comment]
Thanks @OrKoN for the quick feedback!
Okay I’ll try adjusting the device pixel ratio (do you have a link on the docs here by any chance?)
And I’ll try to extract a minimal example to demonstrate the issue

**Comment by ThibaultJanBeyer** [comment]
While trying to create a minimal reproducible example I found another unrelated bug: https://github.com/puppeteer/puppeteer/issues/11014
Will continue trying…

**Comment by ThibaultJanBeyer** [comment]
Okay, I solved the other bugs which were not necessarily bugs but rather how the puppeteer works. So just https://github.com/puppeteer/puppeteer/issues/11014 seems like a real one. Going to close this issue thread now. Thank you!
