### ISSUE TITLE
[Bug]: Error with missing `structuredClone` API in Node 16 when doing a screenshot

### ISSUE THREAD

**Issue by ArnaudBuchholz** [puppeteer/puppeteer#11004]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; // TS/ESM are all supported.

global.structuredClone = function () {
  throw Error('Use of structuredClone (which does not exist in Node 16)');
};

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const result = await page.screenshot();
  console.log(result);
  await browser.close();
})();
```

### Error string

Use of structuredClone (which does not exist in Node 16)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility

### Expectation

The code *was* working (puppeteer@20) but it recently broke.

### Reality

I know Node 16 is on the verge of being deprecated but I didn't see any breaking change telling it is no more supported.

### Puppeteer version

21.3.3

### Node version

16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Windows

**Comment by ArnaudBuchholz** [comment]
Updated Node.js version to 16.20.2 (lts/gallium)

**Comment by OrKoN** [comment]
Looks like an accidental change slipped in but we will drop Node 16  support probably next week, the PR is in progress https://github.com/puppeteer/puppeteer/pull/10912

**Comment by ArnaudBuchholz** [comment]
That was fast, thank you !
