### ISSUE TITLE
Roboto-Regular Font with Non-english not displaying 

### ISSUE THREAD

**Issue by RathodAnnu13** [puppeteer/puppeteer#11002]
### Minimal, reproducible example

```TypeScript
I'm using Puppeteer to automate a headless browser, loading a Fabric.js canvas from JSON, and exporting it as an image on the Linux command-line interface (CLI). However, I'm facing issues with non-English fonts not rendering correctly on Linux.

I copied a font from Google Translate, and it displays correctly on the Fabric canvas in the Chrome browser. However, when I load the canvas in Puppeteer on Linux, it returns a blank result. Interestingly, the exact same code works perfectly on the Windows platform.
```

### Error string

Non-English font is not loading on Linux server

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

![image](https://github.com/puppeteer/puppeteer/assets/60641656/6f6137fa-6032-402b-8e89-acfa09cacd83)

### Reality

![hindi_font](https://github.com/puppeteer/puppeteer/assets/60641656/58fc4217-7acb-4b11-b2c6-2c9b3bbb6000)

### Puppeteer version

19.7.2

### Node version

v16.13.0

### Package manager

npm

### Package manager version

8.1.0

### Operating system

Linux

**Comment by OrKoN** [comment]
I believe you need to have the font installed on the system. It's hard to say how exactly the font is loaded without a reproducible minimal example.

**Comment by RathodAnnu13** [comment]
> I believe you need to have the font installed on the system. It's hard to say how exactly the font is loaded without a reproducible minimal example.

I am not sure which FontFamily font was copied onto the Canvas. So, I can't install the font. If I do, the font will display with a different fontFamily. 

Please check the code below.
https://jsfiddle.net/wxkfr71z/
