### ISSUE TITLE
[Bug]: Unable to upload video in chromium browser

### ISSUE THREAD

**Issue by Snej-Corleone** [puppeteer/puppeteer#11011]
### Minimal, reproducible example

```TypeScript
initialize: async () => {
    browser = await puppeteer.launch({
      headless: false,
      ignoreDefaultArgs: false,
      args: [
        "--no-first-run",
      ],
      defaultViewport: null,
      ignoreHTTPSErrors: true,
    });
page = await tiktok.browser.newPage();
await page.setUserAgent(
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
    );
await tiktok.page.goto(website, {
      waitUntil: "networkidle2",
    });
const fileInputSelector = '[data-testid="uploads-dropzone-input"]';
await fileInput.uploadFile(filePath);
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Hello everyone,

I'm relatively new to Puppeteer and have encountered this error. When I try to upload a video (mp4, mov) on a website, I always receive the error: "Thumbnail generation failed for video.mp4. Thumbnail could not be generated." This error is specific to the website, but it only occurs when I access the website using Puppeteer through Chromium. In other browsers (Safari), this error does not occur. Uploading via Puppeteer works(puppeteer does not throw an error), but this error always occurs in the Chromium browser (even when done manually in non-headless mode), so it has to do something with it. I hope I'm in the right place to seek help.

 Thanks to everyone in advance!

### Expectation

upload the specific mp4 file to a website. 

### Reality

Thumbnail generation failed for video.mp4. Thumbnail could not be generated

### Puppeteer version

21.3.4

### Node version

20.5.1

### Package manager

npm

### Package manager version

10.1.0

### Operating system

macOS

**Comment by OrKoN** [comment]
The error looks like it's coming from the website itself. And it looks like it's not related to Puppeteer since you say it also happens when doing the upload manually.
