### ISSUE TITLE
--disable-infobars not working anymore in puppeteer v21

### ISSUE THREAD

**Issue by vdegenne** [puppeteer/puppeteer#11013]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

await puppeteer.launch({
  ...,
  args: [
    '--disable-infobars'
  ]
})
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I upgraded my app to `puppeteer 21.3.4` and the flag is not recognized anymore. I have a persistent banner I can't seem to remove,

![image](https://github.com/puppeteer/puppeteer/assets/2827383/4ea55659-33f3-4e84-ac1f-05baf0bac71f)

### Expectation

Remove the banner.

### Reality

Banner's not removed.

### Puppeteer version

21.3.4

### Node version

v19.6.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by OrKoN** [comment]
`--disable-infobars` is part of Chromium, not Puppeteer. Puppeteer is now using Chrome for Testing which comes with this dialog by default. If you want this to be changed, please file a bug in crbug.com. Also, you can still use chromium or other chrome binaries that don't have this bar.

**Comment by vdegenne** [comment]
Thanks for your answer, and sorry for asking in the wrong place.

**Comment by OrKoN** [comment]
Also, please see https://github.com/GoogleChromeLabs/chrome-for-testing/issues/56 (I believe it's being tracked there)

**Comment by vdegenne** [comment]
@OrKoN I've tried to create a puppeteer config file and changed the revision number to `119.0.6020.3` for testing, but same problem, which is not really a problem, now I understand this banner is specific to Chrome Testing channel. But nothing say in the revision number that its' the testing channel so I'd assume `puppeteer` automatically download from the testing channel when the install script is run, am I right?

Do you happen to know if it's possible to change that (to tell puppeteer to download from the main channel)?

**Comment by OrKoN** [comment]
@vdegenne No, this is not possible. Regular Chrome binaries are not available for download and Chromium binaries (which were previously used) might not work the same way as Chrome for Testing binaries (which aims to be closer to Chrome than plain Chromium binaries). See https://developer.chrome.com/blog/chrome-for-testing/ for the background.

**Comment by vdegenne** [comment]
@OrKoN Thanks it's pretty clear now.
I guess in the meantime I have no better option than downloading Chrome (dev) manually and providing puppeteer with the executable path then?

Anyways, thanks for your generous help.
