### ISSUE TITLE
[Bug]: When selecting twice over text the mouse.move breaks

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [puppeteer/puppeteer#11014]
### Minimal, reproducible example

```TypeScript
https://github.com/ThibaultJanBeyer/demo-flaky-puppeteer/pull/1
```
Branch: https://github.com/ThibaultJanBeyer/demo-flaky-puppeteer/tree/drag-issue

### Error string

none

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

- I create a test that drags 2x the exact same path and length
- When it goes over text
- The drag would break the second time

### Expectation

- Drags both times "exactly" the same

### Reality

- Drags once correctly, the mouse up listener is triggered
- The second time seems completely broken, also mouse up is not triggered

### Puppeteer configuration file (if used)

```TypeScript
See code example
```

### Puppeteer version

See code example

### Node version

See code example

### Package manager

yarn

### Package manager version

See code example

### Operating system

macOS

**Comment by OrKoN** [comment]
Could you extract an executable minimal example from your PR? Note that if the browser is in the dragging state, mouse events are ignored. Perhaps, this might be happening here.

**Comment by ThibaultJanBeyer** [comment]
Hi OrKoN, the bare minimum is on the branch: https://github.com/ThibaultJanBeyer/demo-flaky-puppeteer/tree/drag-issue.
It’s just 2 files really 1 hmtl page and the correspondig spec, the rest is configs. Running `npm test` is all it needs…
Or do you have a sandbox hidden somewhere? 🤔

**Comment by jrandolf** [comment]
In the second one, you are dragging the test so you will see `dragover`, no `mousemove`s.

**Comment by ThibaultJanBeyer** [comment]
Ok but this is different behavior than doing it manually, isn’t it supposed to replicate the same behaviour?
