### ISSUE TITLE
[Feature]: Ability to get the original page source code

### ISSUE THREAD

**Issue by heaven** [puppeteer/puppeteer#11015]
### Feature description

It is possible to get the page content which is a snapshot of the rendered DOM after executing all the scripts. In our use case we need to get the HTML source as returned by the server, then render the page and get the page content.

I wasn't able to find a way of getting the page source as returned by the server and we most likely have to send a separate request to obtain that.

**Comment by OrKoN** [comment]
That should be possible already:

```
import puppeteer from "puppeteer";

const browser = await puppeteer.launch();

const page = await browser.newPage();

const response = await page.goto('https://example.com');

const source = await response.buffer();

console.log(source.toString('utf-8'));

await browser.close();
```

**Comment by heaven** [comment]
@OrKoN, this is awesome, thank you! I tried to find out how to do this, but no luck.
