### ISSUE TITLE
[Feature]: Docker image major version tagging

### ISSUE THREAD

**Issue by midnight-wonderer** [puppeteer/puppeteer#11027]
### Feature description

Hello
Regarding the [release tags of the official Docker images](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer/versions?filters%5Bversion_type%5D=tagged), could you also tag the major version?

Currently, the latest version is [21.3.4](https://github.com/orgs/puppeteer/packages/container/puppeteer/130669137?tag=21.3.4), I can use either `FROM ghcr.io/puppeteer/puppeteer:latest` or `FROM ghcr.io/puppeteer/puppeteer:21.3.4` to build my Docker images.  

It is all or nothing; I can only track `latest` version or `21.3.4`.  
This causes the web ecosystem to either break or become insecure.  
If I track `latest` tag, I risk something breaking because my build systems will pull breaking changes from you guys, too. On the other hand, if I track `21.3.4` tag, I will miss out on the security updates.

It would be great if you also tag the major version (e.g., 21) so I can use `ghcr.io/puppeteer/puppeteer:21` as a base for my docker images. So I can grab (and automate) the security updates more frequently than what is practical at the moment (fixed version).

**Comment by OrKoN** [comment]
> If I track latest tag, I risk something breaking because my build systems will pull breaking changes from you guys, too. On the other hand, if I track 21.3.4 tag, I will miss out on the security updates.

If you track the major version, there is no guarantee that you get security updates you need. The recommended way is to use the latest specific version, and set up a regular update process using smth like dependabot.

**Comment by OrKoN** [comment]
I think we should implement this though. The relevant changes have to happen here https://github.com/puppeteer/puppeteer/blob/main/.github/workflows/publish.yml#L75

**Comment by midnight-wonderer** [comment]
> If you track the major version, there is no guarantee that you get security updates you need. The recommended way is to use the latest specific version, and set up a regular update process using smth like dependabot.

I am very well aware of the fact that major version bumps contain both breaking changes and security updates.

But the option to track the major version should make the manual intervention (e.g., merging something from says, dependabot) less frequent. Different situations should call for different measurements, IMHO.

**Comment by midnight-wonderer** [comment]
Very swiftly; thanks.  
Looking forward to the next release.
