### ISSUE TITLE
[Docs] Update TsDoc Examples to be `@puppeteer/doctest` compatible 

### ISSUE THREAD

**Issue by Lightning00Blade** [puppeteer/puppeteer#11037]
In #10933 we introduced a way to lint example in our documentation, with it we discovered that there is improvement to be made to said examples.
To run the verification process locally use `npm run doctest`.

Note: 
There is a GitHub action was introduced and later (https://github.com/puppeteer/puppeteer/pull/11035) disabled.

**Comment by KyleGrande** [comment]
Hey! Im interested in working on this, could you maybe point me in the right direction where I can find what needs improvements? @Lightning00Blade

**Comment by OrKoN** [comment]
`npm run doctest` should give you the list of examples that are not executable right now. A good start would be to update one of the examples so that doctest can run it. See details about the doctest command here https://github.com/puppeteer/puppeteer/pull/10933

**Comment by OrKoN** [comment]
It's not clear yet if we want to have complete self-contained example or if we can assume a page and a browser instances exist. Also, we might want to avoid concatentating multiple examples into one script cc @jrandolf
