### ISSUE TITLE
[Bug]: An error occurred attempting to use chrome headless shell in puppeteer: Invalid file descriptor to ICU data received

### ISSUE THREAD

**Issue by Vinlic** [puppeteer/puppeteer#11030]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer-core"

(async () => {
    await puppeteer.launch({
        headless: true,
        executablePath: "./chrome-headless-shell/win64-118.0.5993.18/chrome-headless-shell-win64/chrome-headless-shell.exe",
    });
})()
    .catch(err => console.error(err));
```

### Error string

Error: Failed to launch the browser process! [0926/130444.910:ERROR:icu_util.cc(240)] Invalid file descriptor to ICU data received.   TROUBLESHOOTING: https://pptr.dev/troubleshooting

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

From: https://googlechromelabs.github.io/chrome-for-testing/

### Expectation

Normal launch.

### Reality

Error: Failed to launch the browser process! [0926/130444.910:ERROR:icu_util.cc(240)] Invalid file descriptor to ICU data received.   TROUBLESHOOTING: https://pptr.dev/troubleshooting

### Puppeteer version

21.1.1

### Node version

18.16.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
It does not look an issue with Puppeteer: could you raise the issue via crbug.com (headless component)?
