### ISSUE TITLE
Inconsistency with screenshots

### ISSUE THREAD

**Issue by niftylettuce** [puppeteer/puppeteer#1103]
Screenshots are inconsistent of the same page (there are subtle differences such as color).

This happens randomly it seems as well.  For a simple test, use `page.screenshot` and then use https://github.com/gemini-testing/looks-same to do image comparison between the new screenshot and an old screenshot.

It's easily reproducible if you try it a few times.

**Comment by ebidel** [comment]
Please provide a code snippet that repros the issue.
