### ISSUE TITLE
[Bug]: Puppeteer is detected by cloudflare

### ISSUE THREAD

**Issue by joeledwardson** [puppeteer/puppeteer#11046]
### Minimal, reproducible example

```TypeScript
import { launch } from 'puppeteer-core'

;(async () => {
  console.log('launching...')
  const browser = await launch({
    executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe',
    headless: false,
    defaultViewport: null
  })
  console.log('connected')
  const page = await browser.newPage()
  await page.goto('https://nowsecure.nl')
  console.log('waiting for 1 min...')
  await new Promise((r) => setTimeout(r, 60_000))
  console.log('closing...')
  await browser.close()
})()
```

### Error string

N/A

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I have used the simplest possible example in puppeteer with a real browser (no headless) and no automation scripts. 

I have replicated this without puppeteer and clicking on the cloudflare verification button I pass through to the website, which means I suspect that somehow they are able to detect Puppeteer?

I have also replicated this on android, forwarding the port to chrome dev tools via ADB and connected to the debugging port and experience the same result.

See the video below (the clicks on the page are executed manually):

https://github.com/puppeteer/puppeteer/assets/25906558/c5d0be24-3251-4e91-8fa3-e8bb535fed2d

### Expectation

After clicking the verification in Cloudflare (manually), I would expect to pass cloudflare verification and continue to the website

### Reality

Cloudflare re-directs back to the verification no matter how many times I click the verification

### Puppeteer version

21.3.5

### Node version

18.14.2

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by joeledwardson** [comment]
```
import puppeteer from 'puppeteer-extra'
import StealthPlugin from 'puppeteer-extra-plugin-stealth'
puppeteer.use(StealthPlugin())

;(async () => {
  console.log('launching...')
  const browser = await puppeteer.launch({
    executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe',
    headless: false,
    defaultViewport: null
  })
  console.log('connected')
  const page = await browser.newPage()
  await page.goto('https://nowsecure.nl')
  console.log('waiting for 1 min...')
  await new Promise((r) => setTimeout(r, 60_000))
  console.log('closing...')
  await browser.close()
})()
```

I did try using stealth (as well as connecting to chrome running on an android device) with the same result wich leads me to believe that they can detect the puppeteer connection somehow. I just don't understand how if I am not querying anything.

**Comment by SirVizzy** [comment]
I'm currently facing the same issues.

**Comment by lavr2004** [comment]
> ### Minimal, reproducible example
> ```ts
> import { launch } from 'puppeteer-core'
> 
> ;(async () => {
>   console.log('launching...')
>   const browser = await launch({
>     executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe',
>     headless: false,
>     defaultViewport: null
>   })
>   console.log('connected')
>   const page = await browser.newPage()
>   await page.goto('https://nowsecure.nl')
>   console.log('waiting for 1 min...')
>   await new Promise((r) => setTimeout(r, 60_000))
>   console.log('closing...')
>   await browser.close()
> })()
> ```
> 
> ### Error string
> N/A
> 
> ### Bug behavior
> * [ ]  Flaky
> * [ ]  PDF
> 
> ### Background
> I have used the simplest possible example in puppeteer with a real browser (no headless) and no automation scripts.
> 
> I have replicated this without puppeteer and clicking on the cloudflare verification button I pass through to the website, which means I suspect that somehow they are able to detect Puppeteer?
> 
> I have also replicated this on android, forwarding the port to chrome dev tools via ADB and connected to the debugging port and experience the same result.
> 
> See the video below (the clicks on the page are executed manually):
> 
>  Just.a.moment.-.Google.Chrome.2023-09-27.16-04-47.mp4 
> ### Expectation
> After clicking the verification in Cloudflare (manually), I would expect to pass cloudflare verification and continue to the website
> 
> ### Reality
> Cloudflare re-directs back to the verification no matter how many times I click the verification
> 
> ### Puppeteer configuration file (if used)
> _No response_
> 
> ### Puppeteer version
> 21.3.5
> 
> ### Node version
> 18.14.2
> 
> ### Package manager
> npm
> 
> ### Package manager version
> 9.5.0
> 
> ### Operating system
> Windows

<img width="622" alt="Screenshot 2024-01-18 at 15 04 18" src="https://github.com/puppeteer/puppeteer/assets/27898320/c2a0f301-611f-44c9-a673-42027cf3288c">

The solution of Cloudflare is very simple: they just request only this "honest"parameter over the browser API... So:)))

**Comment by TechNoobNG** [comment]
@lavr2004 , how do you suggest that can be solved?

**Comment by wilsonssss** [comment]
hello, any progress?

**Comment by joeledwardson** [comment]
I've since moved to using `chrome-devtools-frontend` package directly, then I have complete control over what commands are sent and received.

It does have a steep learning curve however

**Comment by abnerh69** [comment]
@joeledwardson Please, Can you share some kind of sample code how do you solve Cloudflare issue?

**Comment by thephucit** [comment]
same issue :(((

**Comment by ashutosh-stark** [comment]
Out of curiosity, have you noticed scraper traffic hitting your own APIs
as well?

I’ve been researching how developers protect backend endpoints from
Puppeteer/Playwright traffic that can inflate cloud costs.

Are people mostly relying on Cloudflare or Redis-based rate limiting?
