### ISSUE TITLE
[Bug]:  Typescript fails to recognize that the ElementHandle type has checkVisibility() method.

### ISSUE THREAD

**Issue by nelkutski-locusview** [puppeteer/puppeteer#11059]
### Minimal, reproducible example

```TypeScript
public async clickOnVisibleElementBySelector(selector: string): Promise<void> {
    await page.waitForSelector(selector);
    await page.$$eval(selector, (elements) => {
        const visibleElement = elements.find((element) => element.checkVisibility());  
	(visibleElement as HTMLElement).click();
});

// checkVisibility failing to compile by typescript if a type defined for the function's parameter when removing string type from (selector) ts successfully compiles.
```

### Error string

Property 'checkVisibility' does not exist on type 'Element'.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

trying to use ElementsHandle checkVisibility() method inside a $$eval() function and typescript fails to recognize that the type has this method.

### Expectation

expect typescript to compile successfully 

### Reality

trying to use ElementsHandle checkVisibility() method inside a $$eval() function and typescript fails to recognize that the type has this method.

### Puppeteer version

19.6.3

### Node version

v20.6.0

### Package manager

npm

### Package manager version

0.1.0

### Operating system

macOS

**Comment by jrandolf** [comment]
> Property 'checkVisibility' does not exist on type 'Element'.

Use `(element as HTMLElement)`.

**Comment by nelkutski-locusview** [comment]
@jrandolf it did not work same:
Property 'checkVisibility' does not exist on type 'HTMLElement'.

**Comment by superwoou** [comment]
> @jrandolf it did not work same: Property 'checkVisibility' does not exist on type 'HTMLElement'.

Upgrade typescript version if you use typescript@4
