### ISSUE TITLE
waitForSelector returns undefined

### ISSUE THREAD

**Issue by XcrossD** [puppeteer/puppeteer#1105]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: Windows 10
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

`const btnNext = await page.waitForSelector(".wrapper-next>.mdl-button");
console.log(btnNext);`

This code is performed after an ajax call because only until then will the button be appended to body.

**What is the expected result?**
btnNext should be a element handler. 

**What happens instead?**
console.log shows that btnNext is undefined. I'm not sure what is the expected behavior here. The doc says it will return a promise object, but what will happen if 1. the element is not found or 2. the element doesn't appear before the time limit?

Now I can't really think of a case where returning undefined would make sense. It's either the element is found or timeout error is thrown. Any pointer is appreciated.

**Comment by vsemozhetbyt** [comment]
It seems the doc [does not state](https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#pagewaitforselectorselector-options) that the promise of `page.waitForSelector()` is resolved in element handler:

> returns: <Promise> Promise which resolves when element specified by selector string is added to DOM.

It seems it is just resolved in `undefined` or rejected when timed out.

**Comment by XcrossD** [comment]
@vsemozhetbyt Ah it seems that I misunderstood the documentation. This function will only tell when the element is ready on DOM, but doesn't get the element itself. Thank you.
