### ISSUE TITLE
Add New Exmaple

### ISSUE THREAD

**Issue by Vinlic** [puppeteer/puppeteer#11067]
I have developed an interesting open source project: [WebVideoCreator](https://github.com/Vinlic/WebVideoCreator), which uses puppeteer for video rendering. Can I add it to the examples? :D

**Comment by jrandolf** [comment]
Thanks for using Puppeteer! Sadly, the examples in Puppeteer are meant to advertise basic flows independent of any package except puppeteer, so this would not fit into this scope :)
