### ISSUE TITLE
[Bug]: Css Coverage showing different result on every request.

### ISSUE THREAD

**Issue by bv-sumit** [puppeteer/puppeteer#11065]
### Steps to reproduce

I am trying to find the css coverage for one website. The website has 5 <style> tags with all styling in a single line. The coverage gives incorrect result for those style tags. 
Inline Style tag:
<style>#kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap{border-color:var(--global-palette9, #ffffff);border-radius:20px;border-top-width:5px;border-right-width:5px;border-bottom-width:5px;border-left-width:5px;background:var(--global-palette9, #ffffff);padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;}#kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap:hover{border-color:var(--global-palette9, #ffffff);background:var(--global-palette9, #ffffff);}#kt-info-box_759e76-bc .kt-info-svg-icon, #kt-info-box_759e76-bc .kt-info-svg-icon-flip, #kt-info-box_759e76-bc .kt-blocks-info-box-number{font-size:28px;}#kt-info-box_759e76-bc .kt-blocks-info-box-media{color:#444444;background:#ffffff;border-color:var(--global-palette9, #ffffff);border-top-width:4px;border-right-width:4px;border-bottom-width:4px;border-left-width:4px;padding-top:0px;padding-right:5px;padding-bottom:5px;padding-left:5px;margin-top:0px;margin-right:10px;margin-bottom:0px;margin-left:0px;}#kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap:hover .kt-blocks-info-box-media{color:#444444;background:var(--global-palette9, #ffffff);border-color:var(--global-palette9, #ffffff);}#kt-info-box_759e76-bc h6.kt-blocks-info-box-title{color:#000000;font-size:16px;line-height:16px;font-family:Inter;font-style:normal;font-weight:400;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}#kt-info-box_759e76-bc .kt-infobox-textcontent .kt-blocks-info-box-text{color:#333333;}#kt-info-box_759e76-bc .kt-blocks-info-box-text{font-size:14px;line-height:22.5px;font-family:Inter;font-style:normal;font-weight:400;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}#kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap:hover .kt-blocks-info-box-text{color:#333333;}#kt-info-box_759e76-bc .kt-blocks-info-box-learnmore{background:transparent;border-width:0px 0px 0px 0px;padding-top:4px;padding-right:8px;padding-bottom:4px;padding-left:8px;margin:10px 0px 10px 0px;}</style>
 

I cached the page and then changed the <style> tag to multiline. After that It gives me correct result every time. Is it possible that there is some parsing issue in the library?

 <style>
                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap {
                                                        border-color: var(--global-palette9, #ffffff);
                                                        border-radius: 20px;
                                                        border-top-width: 5px;
                                                        border-right-width: 5px;
                                                        border-bottom-width: 5px;
                                                        border-left-width: 5px;
                                                        background: var(--global-palette9, #ffffff);
                                                        padding-top: 10px;
                                                        padding-right: 10px;
                                                        padding-bottom: 10px;
                                                        padding-left: 10px;
                                                      }

                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap:hover {
                                                        border-color: var(--global-palette9, #ffffff);
                                                        background: var(--global-palette9, #ffffff);
                                                      }

                                                      #kt-info-box_759e76-bc .kt-info-svg-icon,
                                                      #kt-info-box_759e76-bc .kt-info-svg-icon-flip,
                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-number {
                                                        font-size: 28px;
                                                      }

                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-media {
                                                        color: #444444;
                                                        background: #ffffff;
                                                        border-color: var(--global-palette9, #ffffff);
                                                        border-top-width: 4px;
                                                        border-right-width: 4px;
                                                        border-bottom-width: 4px;
                                                        border-left-width: 4px;
                                                        padding-top: 0px;
                                                        padding-right: 5px;
                                                        padding-bottom: 5px;
                                                        padding-left: 5px;
                                                        margin-top: 0px;
                                                        margin-right: 10px;
                                                        margin-bottom: 0px;
                                                        margin-left: 0px;
                                                      }

                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap:hover .kt-blocks-info-box-media {
                                                        color: #444444;
                                                        background: var(--global-palette9, #ffffff);
                                                        border-color: var(--global-palette9, #ffffff);
                                                      }

                                                      #kt-info-box_759e76-bc h6.kt-blocks-info-box-title {
                                                        color: #000000;
                                                        font-size: 16px;
                                                        line-height: 16px;
                                                        font-family: Inter;
                                                        font-style: normal;
                                                        font-weight: 400;
                                                        padding-top: 0px;
                                                        padding-right: 0px;
                                                        padding-bottom: 0px;
                                                        padding-left: 0px;
                                                        margin-top: 0px;
                                                        margin-right: 0px;
                                                        margin-bottom: 0px;
                                                        margin-left: 0px;
                                                      }

                                                      #kt-info-box_759e76-bc .kt-infobox-textcontent .kt-blocks-info-box-text {
                                                        color: #333333;
                                                      }

                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-text {
                                                        font-size: 14px;
                                                        line-height: 22.5px;
                                                        font-family: Inter;
                                                        font-style: normal;
                                                        font-weight: 400;
                                                        margin-top: 0px;
                                                        margin-right: 0px;
                                                        margin-bottom: 0px;
                                                        margin-left: 0px;
                                                      }

                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-link-wrap:hover .kt-blocks-info-box-text {
                                                        color: #333333;
                                                      }

                                                      #kt-info-box_759e76-bc .kt-blocks-info-box-learnmore {
                                                        background: transparent;
                                                        border-width: 0px 0px 0px 0px;
                                                        padding-top: 4px;
                                                        padding-right: 8px;
                                                        padding-bottom: 4px;
                                                        padding-left: 8px;
                                                        margin: 10px 0px 10px 0px;
                                                      }
                                                    </style>

### Expected results

I want the ranges to be same in every request.

### Actual results

Sometimes I am getting empty array of range. Sometimes I am getting correct result.

Chrome browser has also stopped showing coverage of <style> tags with single line styling correctly. They are not clearly showing the used and unused part like they show for multiline.
Is it related?

**Comment by OrKoN** [comment]
Would you mind filing an issue at crbug.com? We only collect the coverage reported by the browser. Also, the issue is filed under the wrong label.
