### ISSUE TITLE
Why page screencasting causes huge CPU usage?

### ISSUE THREAD

**Issue by 11Firefox11** [puppeteer/puppeteer#11062]
### Minimal, reproducible example

```TypeScript
// Goes onto a page with an animation and starts the screencast. Close the browser to stop the script.
import puppeteer from "puppeteer";
(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    args: ["--single-process"],
    defaultViewport: {
      width: 1280,
      height: 720,
    }
  });
  const page = await browser.newPage();
  const client = await page.target().createCDPSession();
  const { windowId } = await client.send("Browser.getWindowForTarget");
  await client.send("Browser.setWindowBounds", {
    bounds: { width: 1280, height: 720 },
    windowId,
  });
  await page.goto("https://www.w3schools.com/css/tryit.asp?filename=trycss3_animation_count2");
  client.on("Page.screencastFrame", async (ev) => {
    try {
      await client.send("Page.screencastFrameAck", { sessionId: ev.sessionId });
    } catch(e) {}
  });
  await client.send("Page.startScreencast", {
    format: "jpeg",
    quality: 100,
    everyNthFrame: 1
  });
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I didn't expect to see such high CPU usage.

### Reality

The [site that the example opens](https://www.w3schools.com/css/tryit.asp?filename=trycss3_animation_count2) has an infinite animation. My CPU usage is very high, most of the time it even grows by time. If I try another site where there isn't much animations, the CPU usage is better. Clearly if a page changes a lot then it causes lots of `Page.screencastFrame` event calls. 
I didn't expect to see such high CPU usage. Futhermore, I don't understand why the CPU usage sometimes grows by time. Is there some kind of [chrome switch](https://peter.sh/experiments/chromium-command-line-switches/) that can help with this? Can I do something about it?

### Puppeteer version

21.3.6

### Node version

20.7.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Linux

**Comment by 11Firefox11** [comment]
What I used on Linux to track CPU usage:


With fish:
```fish
while true; ps -C chrome -o %cpu,%mem,cmd; sleep 0.1; clear; end
```

With bash:
```bash
while true; do; ps -C chrome -o %cpu,cmd; sleep 0.1; clear; done
```

**Comment by OrKoN** [comment]
Would you mind filing this issue at crbug.com? Puppeteer only collects frames reported by the browser and screencasts are not part of Puppeteer's API.

**Comment by 11Firefox11** [comment]
Alright. I will move it there.

**Comment by jrandolf** [comment]
You are acking too fast. `Page.screencastFrameAck` should be throttled.

**Comment by 11Firefox11** [comment]
I wrote you a reply on [crbug.com](https://bugs.chromium.org/p/chromium/issues/detail?id=1489172). 

If you reply, please do it there so I don't have to check two platforms at the same time. 😅

**Comment by Vinlic** [comment]
@11Firefox11 
If you are looking for a way to capture page animations, my repository hopes to help you:
https://github.com/Vinlic/WebVideoCreator
