### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by dimaslanjaka** [puppeteer/puppeteer#11061]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {
	// Launch the browser and open a new blank page
	const browser = await puppeteer.launch({
		product: "firefox",
		headless: false,
	});
	const page = await browser.newPage();

	// Navigate the page to a URL
	await page.goto("https://facebook.com/login.php");

	// Set screen size
	// await page.setViewport({ width: 1080, height: 1024 });

	// Type into search box
	// await page.type(".search-box__input", "automate beyond recorder");

	// Wait and click on first result
	// const searchResultSelector = ".search-box__link";
	// await page.waitForSelector(searchResultSelector);
	// await page.click(searchResultSelector);

	await browser.close();
})();
```

### Error string

error on first run

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

i just install `puppeteer` then write sample script from the readme.md

### Expectation

just trying

### Reality

```log
d:\Workspaces\Kotlin\Android\bot\facebot\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\util\disposable.js:19
Symbol.dispose ??= Symbol('dispose');
               ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (d:\Workspaces\Kotlin\Android\bot\facebot\bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\EventEmitter.js:23:25)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
```

### Puppeteer configuration file (if used)

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache'),
};
```

### Puppeteer version

^21.3.6

### Node version

v14.21.3

### Package manager

yarn

### Package manager version

3.6.3

### Operating system

Windows

**Comment by asfaqehussain** [comment]
Yes, I have faced this issue today with the node version 14.15.3 and Resolved by updating the version to v16+

**Comment by dimaslanjaka** [comment]
> Yes, I have faced this issue today with the node version 14.15.3 and Resolved by updating the version to v16+

is there any puppeteer version which support for node 14?

**Comment by bv-sumit** [comment]
> > Yes, I have faced this issue today with the node version 14.15.3 and Resolved by updating the version to v16+
> 
> is there any puppeteer version which support for node 14?

Yes. Puppeteer with version less than 19 works.

**Comment by AdamVHQ** [comment]
Hello. I am having this same problem when using Node v16.13.2. All I did was install the package and declare it - it's not even actively being used yet.

```
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/adam/WebScraperTest/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:23:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
adam@IS-89210:~/WebScraperTest$ node -v
v16.13.2
```

**Comment by asfaqehussain** [comment]
> Hello. I am having this same problem when using Node v16.13.2. All I did was install the package and declare it - it's not even actively being used yet.
> 
> ```
> SyntaxError: Unexpected token '??='
>     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
>     at Module._compile (internal/modules/cjs/loader.js:1049:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:101:18)
>     at Object.<anonymous> (/home/adam/WebScraperTest/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:23:25)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
> adam@IS-89210:~/WebScraperTest$ node -v
> v16.13.2
> ```

After install the puppeteer go to the directory /node_modules/puppeteer  and run `node install.mjs` and it will install the latest chromium

**Comment by dimaslanjaka** [comment]
> Node 14 is not supported. Please use a supported version of Node (currently 18+).

please set `"engine": { "node": "minimum version node" }` in puppeteer [package.json](https://github.com/puppeteer/puppeteer/blob/main/package.json) to make it easier for others to see the required node version compatibility

**Comment by amitkprimo** [comment]
please help me @dimaslanjaka @bv-sumit @asfaqehussain @AdamVHQ @jrandolf 

I'm using node version v18.16.1

still not working 

/home/*********************node_modules/puppeteer-core/lib/cjs/puppeteer/util/disposable.js:19
Symbol.dispose ??= Symbol('dispose');
               ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/*****************/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:23:25)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

**Comment by dimaslanjaka** [comment]
> please help me @dimaslanjaka @bv-sumit @asfaqehussain @AdamVHQ @jrandolf
> 
> I'm using node version v18.16.1
> 
> still not working 

- clean `node_modules` folder
- clean cache `yarn cache clean` or `npm cache clean --force`
- reinstall `npm install` or `yarn install`

**Comment by phiho2419** [comment]
> > please help me @dimaslanjaka @bv-sumit @asfaqehussain @AdamVHQ @jrandolf
> > I'm using node version v18.16.1
> > still not working
> 
> * clean `node_modules` folder
> * clean cache `yarn cache clean` or `npm cache clean --force`
> * reinstall `npm install` or `yarn install`

I'm using node 18.16.7 also tried your guide but it still showing ""Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token '??='",
        "    at _loadUserApp (/var/runtime/UserFunction.js:222:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1114:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)",
        "    at Module.load (internal/modules/cjs/loader.js:979:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:819:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"

**Comment by dimaslanjaka** [comment]
@phiho2419 do u have multiple nodejs version installed?

**Comment by phiho2419** [comment]
> @phiho2419 do u have multiple nodejs version installed?

yeh I have three of them; 14 16 and 18. Also I have tried to use puppeteer on a small project and it is working properly. The problem just showing on my main project

**Comment by dimaslanjaka** [comment]
> > @phiho2419 do u have multiple nodejs version installed?
> 
> yeh I have three of them; 14 16 and 18. Also I have tried to use puppeteer on a small project and it is working properly. The problem just showing on my main project

try `node -v` at terminal you currently used.

looks like mine node v18

![image](https://github.com/puppeteer/puppeteer/assets/12471057/355d77eb-bb8b-419c-9e62-227e5654126a)

**Comment by phiho2419** [comment]
> > > @phiho2419 do u have multiple nodejs version installed?
> > 
> > 
> > yeh I have three of them; 14 16 and 18. Also I have tried to use puppeteer on a small project and it is working properly. The problem just showing on my main project
> 
> try `node -v` at terminal you currently used.
> 
> looks like mine node v18
> 
> ![image](https://user-images.githubusercontent.com/12471057/280361700-355d77eb-bb8b-419c-9e62-227e5654126a.png)

I'm totally using 18 for every current projects. I don't think the node version is the reason.  Did you resolve it just by change the node version ?

**Comment by dimaslanjaka** [comment]
> I'm totally using 18 for every current projects. I don't think the node version is the reason. Did you resolve it just by change the node version ?

ya just switching node version (download zip node v18.x -> extract to my D:\bin\node which is my system environment sets to), then clean node_modules and reinstall.

I think your problem caused by other dependencies which installed different puppeteer version, try using `resolution` for `yarn` or `override` for `npm` property in `package.json` to force all puppeteer using same version.

**Comment by dimaslanjaka** [comment]
here my puppeteer project https://github.com/dimaslanjaka/source-posts/blob/master/package.json

**Comment by kumaresaninfo** [comment]
Same error i am getting, after node js version upgrade

Node Version :- **v18.19.1**

> Travel@1.0.0 dev
> node --max-old-space-size=14336 node_modules/nuxt/bin/nuxt.js


 FATAL  Invalid or unexpected token                                                                                                                                        21:05:08

  const isBadge = logObj.badge ?? logObj.level < 2;
  ^
  
  SyntaxError: Invalid or unexpected token
  at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)


   ╭──────────────────────────────────────────────╮
   │                                              │
   │   ✖ Nuxt Fatal Error                         │
   │                                              │
   │   SyntaxError: Invalid or unexpected token   │
   │                                              │
   ╰──────────────────────────────────────────────╯
   
   
   
   
<img width="592" alt="Screenshot 2024-02-20 at 9 06 18 PM" src="https://github.com/puppeteer/puppeteer/assets/7290366/fa5d1c08-99b9-4335-a883-0ba0ba6c2c75">

I need solution

**Comment by rakshitbharat** [comment]
@kumaresaninfo no you cant because everything is now dead here.
i am finding proper solution from 100 years now.
