### ISSUE TITLE
RequestFailed when trying to get a CSV

### ISSUE THREAD

**Issue by dchang-dchang** [puppeteer/puppeteer#1107]
Hi All,

Thanks for a really great tool! It's been amazing how much cleaner code looks when using the puppeteer apis vs other tools. I'm having trouble getting the contents of a csv. It looks to be working fine up to and including the response headers but then the request fails and I'm unable to get the contents of the csv.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: Ubuntu 17.04
* URLs (if applicable):

**What steps will reproduce the problem?**
_Please include code that reproduces the issue._

1. Create a csv

test.csv
```csv
a,b,c
c,b,a
```

2. Host it somewhere on the internet

Here we use ngrok but you can use anything
```bash
> python -mSimpleHTTPServer 8000
> ngrok http 8000
```

3. Try to get the contents of the csv

index.js
```node
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  page.on('request', r => {
    console.log('request: ' + r.url + ' ' + r.method);
  }); 
  page.on('requestfailed', r => {
    console.log('request failed: ' + r.url + ' ' + r.method);
  }); 
  page.on('requestfinished', r => {
    console.log('request finished: ' + r.url + ' ' + r.method);
  }); 
  page.on('response', r => {
    console.log('response: ' + r.url + ' ' + JSON.stringify(r.headers));
  }); 

  await page.goto('http://bd5e3284.ngrok.io/test.csv');
})();
```

```bash
> npm install puppeteer
> node index.js
```

**What is the expected result?**

Request Finished event with page.contents() returning a promise of the csv as a string.

**What happens instead?**

Request failure. The response headers and content type and content length all seem correct but it emits a request failure. I've also been unable to get the contents of the file, either with `page.content()` or `response.text()`.

```
request: http://bd5e3284.ngrok.io/test.csv GET
response: http://bd5e3284.ngrok.io/test.csv {"date":"Fri, 20 Oct 2017 13:42:30 GMT","last-modified":"Fri, 20 Oct 2017 13:02:27 GMT","server":"SimpleHTTP/0.6 Python/2.7.13","connection":"keep-alive","content-length":"12","content-type":"text/csv"}
response: http://bd5e3284.ngrok.io/test.csv {"date":"Fri, 20 Oct 2017 13:42:30 GMT","last-modified":"Fri, 20 Oct 2017 13:02:27 GMT","server":"SimpleHTTP/0.6 Python/2.7.13","connection":"keep-alive","content-length":"12","content-type":"text/csv"}
request failed: http://bd5e3284.ngrok.io/test.csv GET
```

**Comment by Garbee** [comment]
Looks like a duplicate of #299 to me.

**Comment by dchang-dchang** [comment]
Indeed! Closing.
