### ISSUE TITLE
[Bug]: Failed to launch the browser process

### ISSUE THREAD

**Issue by DevShakti78** [puppeteer/puppeteer#11070]
### Minimal, reproducible example

```TypeScript
const express = require("express");
const bodyParser = require("body-parser");
const puppeteer = require("puppeteer");

const app = express();
app.use(bodyParser.json());

app.post("/", async (req, res) => {
  return res.status(200).send({ body: req.body });
});

async function callingGoogleAPI(lat, lng) {
  const browser = await puppeteer.launch({ headless: "new" });
  try {
    let api = `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
    const page = await browser.newPage();
    await page.goto(api, { waitUntil: "load" });
    let mainData = await page.evaluate(async () => {
      return {
        title: (await document.querySelector(".DUwDvf")?.innerText) ?? null,
        type: (await document.querySelector("button.DkEaL")?.innerText) ?? null,
        rating:
          (await document.querySelector(
            ".F7nice > span:nth-child(1) > span:nth-child(1)"
          )?.innerText) ?? null,
        address:
          (await document.querySelector("div.MngOvd:nth-child(10)")
            ?.innerText) ??
          (await document.querySelector("div.RcCsl:nth-child(3)")?.innerText) ??
          null,
      };
    });
    return mainData
  } catch (error) {
    console.log(error.message);
  } finally {
    await browser.close();
  }
}

async function callingMapMyIndiaAPI(lat, lng) {
  const browser = await puppeteer.launch({ headless: "new" });
  try {
    let api = `https://www.mappls.com/@${lat},${lng}`;
    const page = await browser.newPage();
    await page.goto(api, { waitUntil: "load" });
    let mainData = await page.evaluate(async () => {
      return {
        address:
          (await document.querySelector(
            "#top_lclick1 > div > div:nth-child(1) > b:nth-child(1)"
          )?.innerText) ?? null,
      };
    });
    return mainData
  } catch (error) {
    console.log(error.message);
  } finally {
    await browser.close();
  }
}

app.post("/api", async (req, res) => {
  try {
    const { lat, lng } = req.body;
    console.log(lat,lng);
    const [result1,result2] = await Promise.all([
         callingGoogleAPI(lat,lng),
         callingMapMyIndiaAPI(lat,lng)
      ]);
    let object = {
      status: true,
      google:result1,
      mapMyIndia:result2,
    };
    return res.status(200).send(object);
  } catch (error) {
    return res.status(500).send({ status: false, message: error.message });
  }
});

app.listen(3000, () => {
  console.log("server is listening on port 3000");
});
```

### Error string

"Failed to launch the browser process!\n[10056:10056:1003/121146.230719:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.\n[1003/121146.235114:ERROR:process_memory_range.cc(86)] read out of range\n[1003/121146.235212:ERROR:elf_image_reader.cc(606)] missing nul-terminator\n[1003/121146.242072:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)\n[1003/121146.242115:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n"

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

just webscrapping in google with lat and long

### Expectation

 "google": {
        "title": "12°59'52.1\"N 80°12'26.4\"E",
        "type": null,
        "rating": null,
        "address": "BLOCK-A1, MAHALAKSHMI APARTMENTS, Secretariat Colony, Adambakkam, Chennai, Ramapuram, Tamil Nadu 600088"
    },

### Reality

getting eroor

### Puppeteer version

21.3.6

### Node version

17.3.0

### Package manager

npm

### Package manager version

8.4.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Please provide a minimal repro without third party modules that are not relevant for the issue.

**Comment by DevShakti78** [comment]
> ```ts only this is relevent please see and help
> try {
>     let api = `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
>     const page = await browser.newPage();
>     await page.goto(api, { waitUntil: "load" });
>     let mainData = await page.evaluate(async () => {
>       return {
>         title: (await document.querySelector(".DUwDvf")?.innerText) ?? null,
>         type: (await document.querySelector("button.DkEaL")?.innerText) ?? null,
>         rating:
>           (await document.querySelector(
>             ".F7nice > span:nth-child(1) > span:nth-child(1)"
>           )?.innerText) ?? null,
>         address:
>           (await document.querySelector("div.MngOvd:nth-child(10)")
>             ?.innerText) ??
>           (await document.querySelector("div.RcCsl:nth-child(3)")?.innerText) ??
>           null,
>       };
>     });
>     return mainData
>   } catch (error) {
>     console.log(error.message);
>   } finally {
>     await browser.close();
>   }
> ```

try {
    let api = `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
    const page = await browser.newPage();
    await page.goto(api, { waitUntil: "load" });
    let mainData = await page.evaluate(async () => {
      return {
        title: (await document.querySelector(".DUwDvf")?.innerText) ?? null,
        type: (await document.querySelector("button.DkEaL")?.innerText) ?? null,
        rating:
          (await document.querySelector(
            ".F7nice > span:nth-child(1) > span:nth-child(1)"
          )?.innerText) ?? null,
        address:
          (await document.querySelector("div.MngOvd:nth-child(10)")
            ?.innerText) ??
          (await document.querySelector("div.RcCsl:nth-child(3)")?.innerText) ??
          null,
      };
    });
    return mainData
  } catch (error) {
    console.log(error.message);
  } finally {
    await browser.close();
  }

**Comment by OrKoN** [comment]
I am unable to reproduce the issue. Please refer to the troubleshooting guide to configure sandboxes as it seems to be the issue here https://pptr.dev/troubleshooting#setting-up-chrome-linux-sandbox
