### ISSUE TITLE
[Bug]: EACCES: permission denied, open '/.config/puppeteerrc' which isn't even a directory on my system!

### ISSUE THREAD

**Issue by notjames** [puppeteer/puppeteer#11076]
### Minimal, reproducible example

```TypeScript
please see https://stackoverflow.com/questions/77217379/no-matter-how-puppeteer-is-installed-runtime-gives-errno-13-config-puppe


#!/usr/bin/env node

const puppeteer = require('puppeteer');
const fs = require('fs').promises;

(async () =>
{
  const browser = await puppeteer.launch(
    {
      headless: false,
      args: ['--autoplay-policy=no-user-gesture-required'],
    });
  // ... puppeteer code
  const cookiesString = await fs.readFile('./cookies.json');
  const cookies = JSON.parse(cookiesString);
  await page.setCookie(...cookies);

  let page = await browser.newPage();

  await networkCache.use(page);
})();
```

### Error string

`EACCES: permission denied, open '/.config/puppeteerrc'`

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I have two scripts that behave exactly the same way; one behaves incorrectly more intermittently than the other IE one always fails (regardless of from where I run it) and one works only when I run it from either the directory where the script resides or in the directory where a symlink to the runtime script exists.

### Expectation

I expect the script to check in `$HOME/.config`

### Reality

```
Error: EACCES: permission denied, open '/.config/puppeteerrc'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at #readConfiguration (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:76:39)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:44:63)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/.config/puppeteerrc'
}

Node.js v19.1.0
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Puppeteer configuration file (if used)

```TypeScript
at 10:07:34 ❯ \cat $HOME/.config/puppeteer/puppeteerrc.cjs 
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

v21.3.6

### Node version

v19.1.0

### Package manager

npm

### Package manager version

9.8.0

### Operating system

Linux

**Comment by notjames** [comment]
> This issue has an outdated Puppeteer version: `20.8.3`. Please verify your issue on the latest `21.3.6` version. Then update the form accordingly.
> 
> [Analyzer run](https://github.com/puppeteer/puppeteer/actions/runs/6409289615)

I've updated the library and the issue persists:

```
❯ npm info puppeteer

puppeteer@21.3.6 | Apache-2.0 | deps: 3 | versions: 843
```


```
/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/ExplorerSync.js:56
                        throw error;
                        ^

Error: EACCES: permission denied, open '/.config/puppeteerrc'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at #readConfiguration (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/ExplorerSync.js:76:39)
    at search (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/ExplorerSync.js:44:63)
    at emplace (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/jimconn/projects/src/bluescape/sre/scripts/aws/aws-sso-cli/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/.config/puppeteerrc'
}

Node.js v19.1.0
```

**Comment by OrKoN** [comment]
@notjames can you reproduce this in a Docker container? what is the value of $HOME variable? Note that Puppeteer is using https://github.com/cosmiconfig/cosmiconfig to resolve configs and it looks like the error comes from that module.

**Comment by OrKoN** [comment]
@jrandolf do you know what might be going on?

**Comment by antizhyk** [comment]
Solve this problem by reinstalling nodejs.  It worked for me.

**Comment by notjames** [comment]
> @notjames can you reproduce this in a Docker container? what is the value of $HOME variable? Note that Puppeteer is using https://github.com/cosmiconfig/cosmiconfig to resolve configs and it looks like the error comes from that module.

I tried reproducing this in a docker container and then I inadvertently hosed my machine, so I haven't had a chance to work on this since. However, @antizhyk suggested re-installing nodejs and while I've been recovering from my machine issue, I recognized (I'm new to node so this was surprising) that node and nodejs packages in ubuntu exist and that seems to be a problem. At any rate, I've not been able to reproduce this. My guess is that this is probably a high-level issue (with node or npm).

**Comment by jrandolf** [comment]
> @notjames can you reproduce this in a Docker container? what is the value of $HOME variable? Note that Puppeteer is using https://github.com/cosmiconfig/cosmiconfig to resolve configs and it looks like the error comes from that module.

Indeed, the error must be coming from there. Perhaps there is an existing config on the installation? FWIU, this may also be a bug in cosmiconfig. I'd recommend filing a bug with them.

**Comment by OrKoN** [comment]
Thanks for posting the details! if it still reproduces for anyone, let's file an issue at https://github.com/cosmiconfig/cosmiconfig perhaps we find the root cause there.

**Comment by d-fischer** [comment]
Please chime in on https://github.com/cosmiconfig/cosmiconfig/issues/332 with more info so I can get to fix it.

**Comment by caraxlr** [comment]
Hi, I have asked the help of the cosmiconfig developers and Daniel has fixed the bug. I was wondering if you would consider using a newer version of cosmiconfig? Thanks!
https://github.com/cosmiconfig/cosmiconfig/issues/332

**Comment by OrKoN** [comment]
@caraxlr dependabot should open a PR to update it soon and then it will be out with the next Puppeteer release

**Comment by nilijev** [comment]
I had some issue, and it was caused by existing /nonexistent directory on the server (owned by elasticsearch.elasticsearch)
While I have no idea how this directory got created (and it shouldn't exist at all), by removing it both elasticsearch and kibana started without issues

**Comment by michael-scheurer** [comment]
In my case I had to change the user of the _/home/cleavr/.config_ folder from _root_ to _cleavr_ with a simple chown

`sudo chown -R cleavr:cleavr /home/cleavr/.config`
