### ISSUE TITLE
[Bug]:  page.evaluate hangs forever

### ISSUE THREAD

**Issue by Hyeoghwan** [puppeteer/puppeteer#11073]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const express = require('express');
const compression = require("compression");

const app = express();
app.use(compression());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

(async () => {
    const browser = await puppeteer.launch({ headless: false, devtools: true });
    const url = "https://kmong.com/gig/491835";

    app.get('/scraper', async (_, res) => {
        console.log(url);
        const page = await browser.newPage();
        await page.goto(url);
        await page.evaluate(() => window.open = {});
        await page.evaluate(() => {
            const tags = Array.from(document.querySelectorAll('body *'));
            console.log('tags', tags);
        });
        // await page.close();
        console.log('close');
        res.status(200).json({ message: 'success' });
    });

    app.listen(55001, async () => {
        console.log(`Puppet-Scraper server listening on port ${55001}`);
    });

})();
```

### Background

```
await page.evaluate(() => {  // hangs forever... 
  const tags = Array.from(document.querySelectorAll('body *'));
  console.log('tags', tags);
});
```

this code hangs, so console.log('close') doesn't run. 
why does it happen?

### Puppeteer version

19.4.1

### Node version

v18.10.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Please provide a repro without any additional modules (e.g., the server) not related to the issue. Also, you are very likely logging in the page content and expect the logs to show up in the node process. Use `page.on('console', console => {...})` for that.

**Comment by Hyeoghwan** [comment]
Here is my fulle example code. 

```

const puppeteer = require('puppeteer');
const compression = require("compression");

(async () => {
    const browser = await puppeteer.launch({ headless: false, devtools: true });

    const url = "https://kmong.com/gig/491835";
    const page = await browser.newPage();

    page.on('console', (msg) => {
        console.log('>>', msg._text);
    })

    await page.goto(url);
    await page.evaluate(() => window.open = {});
    await page.evaluate(() => {
        const tags = Array.from(document.querySelectorAll('body *'));
        console.log('tags', tags);
    });

    console.log('close');

})();
```

Here is my console

```
>> undefined
```

I can't see the log, console.log('tags', tags) and hangs.
so the code doesn't end.

**Comment by OrKoN** [comment]
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false, devtools: true });

  const url = "https://kmong.com/gig/491835";
  const page = await browser.newPage();

  page.on('console', (msg) => {
    console.log('>>', msg.text());
  })

  await page.goto(url);
  await page.evaluate(() => window.open = {});
  await page.evaluate(() => {
    const tags = Array.from(document.querySelectorAll('body *'));
    console.log('tags');
  });

  console.log('close');

})();
```

note that you won't be able to log elements in this way because they cannot be serialized to JSON.

**Comment by Hyeoghwan** [comment]
then, 

logging the element which is not serializable could be hanging???

I mean, 

the code `console.log(tags)`  is hanging on the webiste. 

and then, 

after removing the code, the code was finished successfully.

**Comment by OrKoN** [comment]
@Hyeoghwan I think it's just slow as you try to print all elements to console. It is the same behaviour if you paste 

```
const tags = Array.from(document.querySelectorAll('body *'));
console.log('tags', tags);
```

into the console in DevTools. You will eventually get a timeout error. It seems that the error is caused by the site as it does not happen on other sites. It looks like the site overrides console implementation and that is slow.


<img width="1431" alt="Screenshot 2023-10-05 at 09 05 43" src="https://github.com/puppeteer/puppeteer/assets/399150/7c55b945-5291-40e4-a52e-99d043be68b4">

You can debug it by breaking the script execution after pasting the snippet into DevTools console (no need for Puppeteer).

**Comment by Hyeoghwan** [comment]
thanks!
