### ISSUE TITLE
[Bug]: Permissions aren't Guaranteed whe running outside the project page

### ISSUE THREAD

**Issue by Tainan404** [puppeteer/puppeteer#11074]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

const runPuppeteer = async () => {
  // Launch the browser and open a new blank page  
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      '--use-fake-device-for-media-stream',
      '--use-file-for-fake-video-capture=video.y4m'
    ],
  });
  const context = browser.defaultBrowserContext();
  await context.overridePermissions('https://webcasts.com/webrtc/', ['camera', 'microphone']);
  const page = await browser.newPage();
  await page.setViewport({width: 1080, height: 1024});
  // Navigate the page to a URL
  await page.goto('https://webcasts.com/webrtc/');
  
};

(async () => {
  await runPuppeteer();
})();
```

### Error string

no error

### Background

I tried to run puppeter outside the main project folder, when I do that no permission is Guaranteed to the page.

https://github.com/puppeteer/puppeteer/assets/15806883/75d51349-0e63-4bb7-af7b-3411aabf4dd4

### Expectation

I could run the project from anywhere in the computer and could add it to terminal alias

### Reality

if I run it outer the project folder it doesn't grant the permissions to browser.

### Puppeteer version

21.3.6

### Node version

v18.10.0

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Linux

**Comment by OrKoN** [comment]
I am not able to get the video source show up on the machines I have test this with. Are there extra steps to make it work? As for different launch directories, there really should be no difference but your node requires might resolve against a different puppeteer version if you have it installed on multiple levels.

**Comment by OrKoN** [comment]
Does video.y4m have to exist? If so, make sure you use the absolute path to it, otherwise, it will relative to the current working directory.

**Comment by OrKoN** [comment]
I think that is the very likely reason.
