### ISSUE TITLE
[Bug]: Puppeteer hangs with headless:new mode

### ISSUE THREAD

**Issue by vivekagal1998** [puppeteer/puppeteer#11071]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const browserOptions = {
    args: [
        '--no-sandbox',
        '--disable-gpu'
    ],
    headless: 'new',
    dumbio: true,
}

async function crawlUrl(url){
    let browser;
    let page;
    try {
        browser = await puppeteer.launch(browserOptions);
        page = await browser.newPage();
        await page.setViewport({
            width: 1280,
            height: 720
        })
        await Promise.all([
            page.goto(url, {
                waitUntil: "domcontentloaded",
            }),
            page.waitForNetworkIdle({ idleTime: 1000, timeout: 30000 }),
        ]);        
        
        // Execute some JS code using page.evaluate for example
    } catch (error) {
        console.error(`Error while rendering : ${error.stack}`);
    } finally {
        if(page){
            await page.close();
        }
        console.log(`About to close the browser for ${url}`)
        await browser.close();
        console.log(`Closed the browser successfully`)
    } 
}
await crawlUrl('https://traderie.com/dragonadventures/product/1468360566/recent')
```

### Error string

```
Error while rendering : TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Request)
    at Timeout.<anonymous> (/opt/amazon/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:27:33)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2023-10-03T15:00:53.795Z puppeteer:protocol:SEND ► [
  '
{
    "method": "Target.closeTarget",
    "params": {
        "targetId": "45BC2B7BBA77F9C696FF15E25BCBFC93"
    },
    "id": 4
}
'
]
2023-10-03T15:00:53.795Z puppeteer:protocol:RECV ◀ [ '
{
    "id": 4,
    "result": {
        "success": true
    }
}
' ]
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Hi everyone,
We are facing issue where Program hangs while using headless: new mode. Attached is sample code with headless: new and logs associated to it.

### Expectation

Program should not hang with headless new mode

### Reality

The program hangs intermittently while crawling multiple URLs when there are exceptions thrown in the try block (for example Puppeteer timing out) and finally gets executed, in between page.close() and browser.close()

As can be seen Target.closeTarget is successful meaning the page.close() executed successfully. However, the program now freezes with no logs leading to assumption that it is stuck in browser.close().

I run the same program with ```headless: true``` and it works closing the browser gracefully. Could someone kindly advise over what is going on?

Puppeter version:
```
+-- puppeteer-extra-plugin-stealth@2.11.2
+-- puppeteer-extra@3.3.6
+-- puppeteer@21.0.2
```

### Puppeteer version

21.0.2

### Node version

16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Linux

**Comment by vivekagal1998** [comment]
Could someone kindly guide here what's going wrong as it's impacting our Production system?

**Comment by OrKoN** [comment]
I am unable to reproduce locally. Does it happen outside of your production environment?

**Comment by vivekagal1998** [comment]
@OrKoN Thanks for the response!
It happens both in production and in our gamma environment. Currently, however, we run URL crawls at scale (in millions) and the browser instance is initialized and disconnected for every URL crawl. Not sure initializing and closing browser at scale is the root cause. 
Just FYI, we use dumb-init to remove the defunctant Chrome processes.

**Comment by OrKoN** [comment]
It would be difficult to address without a reproducible example: from looking at the code, I don't see how the close call could hang unless there is some environment-specific issue, e.g., the OS is unable to close the process or some chrome dependencies are missing. I'd recommend checking the browser logs as well as complete CDP logs to understand what might be happening. Also, try the latest version as the issue might be fixed there.

**Comment by patroqueeet** [comment]
happening to me with v21.3.4 inside gitlab CI docker containers, not reproducible in docker locally.

**Comment by OrKoN** [comment]
@patroqueeet any chance gitlab ci runs containers in a read-only mode?

**Comment by patroqueeet** [comment]
if you mean writing to disk blocked: then nope, its downloading code and writing files all the time

**Comment by patroqueeet** [comment]
debugging right now. output:
```$ cd darg.js
$ npm -v puppeteer
8.19.4
$ cd ..
$ echo 'x' > test.html
$ /usr/bin/node darg.js/src/html2pdf.js test.html test.pdf
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
DevTools listening on ws://127.0.0.1:[37](https://gitlab.com/kkd3/darg/-/jobs/5365761577#L37)089/devtools/browser/679c7fd5-db6f-45f6-b992-811e8eb07d1e
[1024/192439.750210:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1024/192439.750573:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1024/192439.770379:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1024/192439.809968:WARNING:sandbox_linux.cc([38](https://gitlab.com/kkd3/darg/-/jobs/5365761577#L38)0)] InitializeSandbox() called with multiple threads in process gpu-process.```

there it hangs, then I have to cancel the CI job.


JS:
```const puppeteer = require('puppeteer');
const fs = require('fs');


(async () => {
  const browser = await puppeteer.launch({
    executablePath: '/usr/bin/google-chrome-stable',
    headless: 'new',
    dumpio: true,
    args: ['--no-sandbox', '--disable-gpu', "--disable-setuid-sandbox"],

  });
  const page = await browser.newPage();
  console.log(process.argv)
  const hasFooter = !!(process.argv[6]);
  const hasHeader = !!(process.argv[5]);

  await page.emulateMediaType('screen');
  await page.goto('file://' + process.argv[2], {waitUntil: 'networkidle2'});
  await page.pdf({
    path: process.argv[3],
    format: 'A4',
    preferCSSPageSize: true,
    displayHeaderFooter: hasFooter || hasHeader,
    headerTemplate: hasHeader? fs.readFileSync(process.argv[5], 'utf8') : '',
    footerTemplate: hasFooter? fs.readFileSync(process.argv[6], 'utf8') : '',
    /* header and footer must alwas both given or none. 40px for proper
     * top of page spacing. 240px for darg header
     */
    margin: {
      top: hasHeader === true ? process.argv[7] : "0px",
      left: "0px",
      right: "0px",
      bottom: hasFooter === true ? "80px" : "0px"
    },
    printBackground: true,
    landscape: process.argv[4] == '1'
  });

  await browser.close();
})();```

**Comment by downey88** [comment]
Same thing happened to me, the issue only in production environment.. It seems not able to handle too many requests..

https://github.com/puppeteer/puppeteer/issues/11489
