### ISSUE TITLE
[Bug]: Error: Navigating frame was detached

### ISSUE THREAD

**Issue by david-matei** [puppeteer/puppeteer#11083]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'
(async () => {
const browser = await puppeteer.launch({
            timeout: 120000,
            headless: false,
            defaultViewport: null,
            args: ['--start-fullscreen', '--disable-features=site-per-process']
        })

        const page = await browser.newPage()
await page.goto("https://github.com/")
})()
```

### Error string

     new Error('Navigating frame was detached')

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I was expecting my code to go to the github page and then take a screenshot.

### Reality

The code gets to github but instantly before the page loads completly it cuts off and I get the error.

### Puppeteer version

21.1.1

### Node version

16.16.0

### Package manager

npm

### Package manager version

9.7.1

### Operating system

macOS

**Comment by OrKoN** [comment]
I am unable to reproduce the issue on the latest version using the provided snippet.
