### ISSUE TITLE
[Bug]: Accessibility tree changed with v21.3.0 causing selectors to break

### ISSUE THREAD

**Issue by kapiljaveri** [puppeteer/puppeteer#11087]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  // await page.goto('internal-url');
  await page.waitForSelector('aria/First Name[role="textbox"]');
  await browser.close();
})();
```

### Error string

TimeoutError: Waiting for selector `First Name[role="textbox"]` failed: Waiting failed: 30000ms exceeded

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

While attempting to update from v21.2.1 to the latest, I saw some of my tests failing due to some accessibility based selectors failing to select the DOM nodes.

I narrowed this down to the update from v21.2.1 to v.21.3.0. This also occurs on the latest version 21.3.7.

My situation:
I have a `textbox` using `aria-labelledby` pointing to a `<label>` element..

```
<div>
  <span
    ><label id="react-aria2669971434-:r1s:" for="react-aria2669971434-:r1r:"
      ><span>First Name</span></label
    ><span></span
  ></span>
  <div>
    <input
      type="text"
      aria-required="true"
      name="firstName"
      id="react-aria2669971434-:r1r:"
      aria-labelledby="react-aria2669971434-:r1s:"
      value="FN-kzgv4srr"
    />
  </div>
</div>
```

Selector:
```
await page.waitForSelector('aria/First Name[role="textbox"]');
```

This works in v21.2.1 but not in any version newer than that.

Looking at the accessibility snapshot, it's clear that something changed because the `name` isn't populated any more.

Working:
<img width="630" alt="v21 2 1 works" src="https://github.com/puppeteer/puppeteer/assets/6692991/ef26f507-a04e-4250-be21-5aed5884867f">

<img width="255" alt="Screenshot 2023-10-06 at 1 35 16 AM" src="https://github.com/puppeteer/puppeteer/assets/6692991/897515bf-16f4-42d6-8a13-3bbb18f7be3f">

Not working:
<img width="535" alt="v21 3 0 does not have name" src="https://github.com/puppeteer/puppeteer/assets/6692991/88448bea-9674-4451-9d83-8815e9b42463">

<img width="199" alt="Screenshot 2023-10-06 at 1 44 20 AM" src="https://github.com/puppeteer/puppeteer/assets/6692991/3e25660e-9bca-4326-9949-7205129e9d8e">

### Expectation

I expect the accessibility tree to have `name` captured correctly allowing the textbox to be selected via the associated label.

### Reality

`TimeoutError` is thrown causing my tests to fail as the textbox cannot be captured with the accessible name.

### Puppeteer version

21.3.7

### Node version

20.3.0

### Package manager

yarn

### Package manager version

3.6.0

### Operating system

macOS

**Comment by OrKoN** [comment]
@kapiljaveri would you mind filing an issue against crbug.com? It does sound like a bug/change in Chromium.

**Comment by kapiljaveri** [comment]
Sure thing! Thank you!!

**Comment by OrKoN** [comment]
@kapiljaveri it would help if you could create a sample test page the shows the issue and perhaps it's also observable in DevTools then.

**Comment by OrKoN** [comment]
@kapiljaveri btw does it reproduce on the latest Puppeteer version? It seems to work for me:

```
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(`
    <div>
    <span
      ><label id="react-aria2669971434-:r1s:" for="react-aria2669971434-:r1r:"
        ><span>First Name</span></label
      ><span></span
    ></span>
    <div>
      <input
        type="text"
        aria-required="true"
        name="firstName"
        id="react-aria2669971434-:r1r:"
        aria-labelledby="react-aria2669971434-:r1s:"
        value="FN-kzgv4srr"
      />
    </div>
  </div>
  `)
  await page.waitForSelector('aria/First Name[role="textbox"]');
  await browser.close();
})();
```

**Comment by kapiljaveri** [comment]
Yeah, I actually tried creating one but was having a super hard time reproducing. I used a super straightforward snippet of that HTML above but it worked in that situation, not sure if there's something else contributing to the issue now 😖

**Comment by kapiljaveri** [comment]
It does fail for me on the latest version, the above snippet you tried works in both 21.3.0 and 21.3.7 so not sure how our internal webpage is having issues with just a version bump.

Also, thanks for the `setContent` tip.

**Comment by kapiljaveri** [comment]
Spent more time looking at this, it's quite flakey, in some situations I was able to get it to work, not others.

Having a hard time reproducing outside of our environment. It's currently rendered inside of a HTMLDialogElement and then inside a `<form>`. Removing additional layers of `flexbox` within the `dialog` and `form` make it work sometimes. And in some cases I don't see a label for `First Name` but see it for `Last Name`. Looking at the captured screenshot failures, everything looks good so definitely confusing.

**Comment by kapiljaveri** [comment]
eg. of what I mean..

```
children: [
        { role: 'button', name: '' },
        { role: 'StaticText', name: 'Profile' },
        { role: 'textbox', name: '', value: 'FN-gop7cld9', required: true },
        { role: 'StaticText', name: 'Last Name' },
        {
          role: 'textbox',
          name: 'Last Name',
          value: 'LN-gop7cld9',
          required: true
        },
        { role: 'button', name: 'CANCEL' },
        { role: 'button', name: 'SAVE', disabled: true }
      ]
```

Last Name is there, but no `StaticText` for `First Name` nor the accessible label

**Comment by OrKoN** [comment]
@kapiljaveri it would be good to get a reproducible example and publish an issue to crbug.com. It looks like the a11y tree updates might be more asynchronous in the latest versions of Chrome and it looks like you are getting a snapshot during an update. Does the issue still reproduce if you add a delay before querying the a11y tree or making sure that the page DOM is stable?

**Comment by kapiljaveri** [comment]
Let me spend some time this week to try and get a good example. I've tried a couple of things and it's flaky in our codebase but hard to repro outside of it. But yeah, it's still failing after some delays. Will provide an update by EOW.

**Comment by OrKoN** [comment]
@kapiljaveri do you use React? there were some reports previously that flakiness might be caused by React's reconciliation https://github.com/puppeteer/puppeteer/issues/9528#issuecomment-1712777612 (not related to a11y though)

**Comment by kapiljaveri** [comment]
I am, but I'm also using `waitForSelector` which should wait for the updates to occur and retry.
