### ISSUE TITLE
[Bug]: Setting "PUPPETEER_SKIP_DOWNLOAD" env var to a falsy value skips browser installation

### ISSUE THREAD

**Issue by xfournet** [puppeteer/puppeteer#11080]
### Minimal, reproducible example

```TypeScript
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
npm install
```

### Error string

--> browser is not installed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I want to disable browser download by default, and so i set
```json
"puppeteer": {
    "skipDownload": true
  }
```
in my package.json

When i want to download the browser and would like to use the PUPPETEER_SKIP_DOWNLOAD env variable (which is preferred to the package.json configuration) and set it to false.

### Expectation

Browser is installed

### Reality

Browser is not installed

### Puppeteer configuration file (if used)

```TypeScript
No Puppeteer configuration file, package.json has

"puppeteer": {
    "skipDownload": true
  }
```

### Puppeteer version

21.3.6

### Node version

20.8.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Windows

**Comment by OrKoN** [comment]
@jrandolf PTAL

**Comment by jrandolf** [comment]
I cannot reproduce this issue.

**Comment by dewebdes** [comment]
> This issue has an outdated Puppeteer version: `21.3.6`. Please verify your issue on the latest `21.6.0` version. Then update the form accordingly.
> 
> [Analyzer run](https://github.com/puppeteer/puppeteer/actions/runs/7179977573)

the issue exists on 21.6.0 (I tested on windows)
maybe I moved to cefsharp
I loved so much puppeteer, but it not stables anymore :(

**Comment by dewebdes** [comment]
In windows, I cannot solve this problem (_in versions <=19...<22_)
But in linux, you can edit this file:
`/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js`
edit **resolveExecutablePath()** Function and retrun the correct path:
`resolveExecutablePath() {
        return '/snap/bin/chromium';
        ....`
