### ISSUE TITLE
What is cookie size?

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#1109]
https://github.com/GoogleChrome/puppeteer/blob/32398d11bdc2cd01c9cfe3e706f629ef90179c91/lib/Page.js#L942

e.g.

```json
{
  "domain": "booking.cineworld.co.uk",
  "expires": 1508519698.186,
  "httpOnly": true,
  "name": "TS01e885cb",
  "path": "/",
  "secure": true,
  "session": false,
  "size": 180,
  "value": "019de3c5d97612720d748b5b78966aa0dcd73c93fb279198d260e7e9ddd0ac05608bdcccb941dae5007a29badf254fe5414f7a67fbc1ba6faa302969d310f6d1be49d250712d9c5c5d1c6ba16a52b1afb75ea54372"
}

```

At first I thought it is the length of the `value`, but it isn't. In this case, the value is 170 characters long, while the size is 180.

**Comment by JoelEinbinder** [comment]
It includes the `name`, which is 10 characters.
