### ISSUE TITLE
[Bug]: Puppeteer 21 not communicating with cromium on arm64

### ISSUE THREAD

**Issue by mariusrak** [puppeteer/puppeteer#11092]
### Minimal, reproducible example

```TypeScript
let browser;
let executablePath;

async function launchBrowser() {
        if (executablePath) {
                try {
                        console.log("launching by exe path");
                        return await puppeteer.launch({
                                executablePath,
                                args: ["--no-sandbox", "--disable-setuid-sandbox"],
                        });
                } catch (e) {
                        log("Error with exe path:", e);
                }
        }
        try {
                console.log("launching by default path");
                return await puppeteer.launch();
        } catch (e) {
                log("caught:", e);
                log("FINDING exe PATH");
                executablePath = await new Promise((res, rej) =>
                        exec("which chromium", (err, out, stderr) => {
                                if (stderr || err) {
                                        rej(stderr || err);
                                } else {
                                        res(out.trim());
                                }
                        })
                );
                log(executablePath);
                return await launchBrowser();
        }
}


async function initBrowser() {
        console.log("init browser");
        if (!browser) {
                console.log("no browser yet");
                browser = await launchBrowser();
                console.log("returning new browser");
        }
        console.log("returning existing browser");
        return browser;
}

initBrowser().then(() => console.log('Browser initialized'))
```

### Error string

none

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been using older version of puppeteer (19) without a problem. But version 21 doesn't work.
I'm running a docker container on an Oracle Ampere machine (arm64) 
Chromium is installed by docker using `RUN apt-get install chromium -y`
Docker image is `node:gallium-buster`

### Expectation

Browser should start and should be accessible.

### Reality

Process hangs and does nothing. 
First time it fails because it is not able to run chrome that comes installed with puppeteer. Then it looks up chromium installed by apt and it seems that it is okay. I get a message about deprecated headless mode. But then it hangs. I can see chromium process started by examining `ps -aux` there is e.g. 
```
root        1041  0.0  0.2 38804488 65652 ?      Sl   01:03   0:00 /usr/lib/chromium/chromium --type=renderer --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disable-breakpad --enable-automation --file-url-path-alias=/gen=/usr/lib/chromium/gen --force-color-profile=srgb --remote-debugging-port=0 --allow-pre-commit-input --field-trial-handle=11772390256001659433,12411231457055470110,131072 --enable-features=NetworkServiceInProcess2 --disable-features=AcceptCHFrame,MediaRouter,OptimizationHints,Prerender2,Translate --enable-blink-features=IdleDetection --lang=en-US --headless --export-tagged-pdf --lang=en-US --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100
```

I stepped through puppeteer code and it seems that puppeteer doesn't receive any message or notification from chromium, that chromium is started.

During stepping I've encountered a message 
```
[1006/004426.742522:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
```
but it seems like it then switched to ws which probably connected but there was no communication. But those are only my guesses.

### Puppeteer version

21.3.8

### Node version

16.20.2

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Linux

**Comment by Choco-milk-for-u** [comment]
> I am unable to reproduce locally. Please see https://pptr.dev/troubleshooting#running-puppeteer-in-docker as the issue is probably related to the docker image. Consider trying the following: 1) checking that all dependencies are installed https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux 2) configure the sandbox 3) make sure dbus is started and has a proper DBUS_SESSION_BUS_ADDRESS in the env vars.

Hello, i have the similar problem. While doing installing google-chrome instead of chromium my app stops freezing. Buth there are much more erros.
Does that mean you have to work with google-chrome instead of chromium if using Docker?

**Comment by mariusrak** [comment]
So I was able to get it running with installing all from here https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile

But I cannot get it running with `chromium` instead of `google-chrome-stable`. Is that behavior expected and is it okay? I would expect chromium to be more lightweight and bit faster and consume less resources, so I would prefer chromium. Is it possible to make it work with chromium?

Thanks.

**Comment by OrKoN** [comment]
@mariusrak it should work but you need to troubleshoot it on your own: we don't distribute `chromium` and also don't test with it.

**Comment by mariusrak** [comment]
Oh, sorry, I've made a mistake. I got it running with `google-chrome-stable` but on amd64 not on **arm64**.

So I tried what was recommended by @OrKoN 

> I am unable to reproduce locally. Please see https://pptr.dev/troubleshooting#running-puppeteer-in-docker as the issue is probably related to the docker image. Consider trying the following: 1) checking that all dependencies are installed https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux 2) configure the sandbox 3) make sure dbus is started and has a proper DBUS_SESSION_BUS_ADDRESS in the env vars.

I installed everything i found in available dockerfiles. I configured sandbox (`args: ["--no-sandbox", "--disable-setuid-sandbox"],`) and I checked dbus and it wasn't started but even if I start it, there's no change.

The issue is, that chromium gets started, I can see it in `ps -aux` output.

I understand that, you are not supporting chromium, but what are we supposed to do on arm? Thanks.

**Comment by mariusrak** [comment]
So my problem was basically that I ran old debian (10) after upgrade to 11 (which offers newest chromium) everything works correctly and there's no problem. Just do `RUN apt-get install -y chromium` and then provide executablePath by `which chromium`.
