### ISSUE TITLE
[Bug]: Observing multiple active tcp connections that do not close until after a few minutes since starting the browser

### ISSUE THREAD

**Issue by sorinfratila** [puppeteer/puppeteer#11107]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });
  const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();
  await page.goto('about:blank');
    setTimeout(async () => {
      await page.close();
    }, 3000);
// intentionally left browser open so you can see the active connections and how long in takes for them to close
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We use puppeteer as a web scanner to evaluate accessibility issues on clients' domains among other things. However it happens that when using puppeteer to start Chrome for testing (CfT), there seem to be a lot more tcp connections that I would not expect to be there that linger for much longer than if I would start CfT or Chrome for that matter. I would expect to have the same or less active tcp connections to my machine when opening CfT with puppeteer than if I would start it manually, so I am wondering if this is a bug and if it's not a bug, how can I start CfT with puppeteer and have the same tcp connections that close right away. Fx if I open Chrome and I run this command before and after opening it (it has a lot of filtered out IPs that I don't care about):
```bash
netstat -n | grep tcp4 | grep ESTABLISHED | awk '{ print $5; }' | sort | uniq -c | sort -nr | grep -v "17.57.155.26\|17.56.9.14\|52.98.154.146\|3.126.186.102\|52.3.106.226\|34.158.0.131\|20.50.201.204\|198.252.206.25\|185.166.143.37\|20.50.73.13\|20.189.173.23\|170.114.52.2\|170.114.2.47\|170.114.14.68\|17.57.146.22\|162.247.241.1\|140.82.114.26\|13.248.151.210\|13.107.42.14\|17.248.237.65\|13.69.68.64\|13.107.21.239\|20.74.35.75\|20.190.181.5\|20.189.173.11\|13.89.179.9\|204.79.197.239\|140.82.113.25\|108.128.193.124\|104.46.162.224\|131.187.124.132\|64.233.165.109\|54.90.66.198\|54.157.192.81\|52.98.149.130\|40.126.53.18\|51.105.232.141\|3.231.47.80\|13.107.138.8\|17.248.237.66\|17.248.237.128\|127.0.0.1\|54.225.73.58\|20.42.65.90\|23.209.125.28\|17.23.18.34\|104.77.212.94\|104.77.212.80\|44.198.45.157\|17.248.237.64\|17.253.107.202\|52.98.154.130\|20.189.173.1\|35.186.224.47\|35.186.224.41\|173.194.222.109\|17.248.237.67\|44.208.210.155\|52.123.129.14\|20.190.160.27\|162.247.243.29\|140.82.114.25\|107.20.88.15\|13.33.141.2\|140.82.113.26\|104.208.16.89\|13.69.239.73\|20.50.73.11\|20.189.173.7\|13.89.178.26\|13.33.141.44\|13.69.116.104\|13.69.116.107\|104.77.212.40\|13.89.179.10\|192.229.221.95\|140.82.112.26\|40.126.32.101\|3.65.102.105\|76.223.31.44\|17.57.146.54\|170.114.2.54\|170.114.14.70\|104.208.16.90\|20.190.181.4\|143.204.237.129\|18.173.5.113\|185.166.143.38\|143.204.237.44\|18.197.249.189\|3.33.235.18\|3.229.81.33\|3.225.166.25\|13.107.136.8\|3.68.170.153\|17.57.146.27\|185.159.159.148\|18.168.253.132\|185.166.143.44\|185.166.143.31\|140.82.121.4\|3.68.61.181\|3.67.131.16\|20.42.73.27\|17.248.237.68\|34.104.35.123\|34.204.231.216\|35.186.224.17\|23.193.116.193\|74.125.131.108\|95.100.155.75\|64.233.165.108\|35.186.224.25\|18.155.153.70\|18.155.153.36\|17.171.47.23\|54.236.122.12\|54.230.206.48\|54.205.219.43\|17.253.107.201\|140.82.112.25\|35.153.89.158\|17.57.146.56\|17.56.138.35\|17.253.52.247\|54.172.44.252\|52.55.72.199\|20.42.65.88\|52.104.68.41\|3.209.172.172\|104.208.16.88\|34.224.127.104\|34.98.74.57\|35.168.168.82\|54.230.206.47\|54.230.206.81\|162.243.219.16\|17.253.107.203\|20.50.80.209\|20.42.73.25\|54.230.206.106\|52.98.228.210\|54.86.231.251\|52.200.46.145\|52.182.143.209\|52.182.143.208\|52.123.128.14\|52.114.77.128\|52.114.77.128\|52.113.205.21\|52.112.92.55\|40.101.1.25\|34.237.73.95\|3.90.158.208\|17.56.9.23\|52.98.151.66\|52.112.39.48\|170.114.14.73\|170.114.0.179\|17.57.146.133\|52.98.151.82\|52.113.194.132\|15.197.213.252\|132.245.231.0\|8.8.4.4\|74.125.205.109\|64.233.162.108\|52.98.228.226\|216.58.207.202\|173.194.73.109\|13.107.5.93\|13.107.42.18\|108.177.14.108\|40.115.3.253\|40.113.110.67\|40.113.103.199\|40.101.1.15\|52.98.149.146\|3.67.245.95\|192.241.242.235\|192.241.242.235\|185.166.143.36\|185.70.42.22\|96.126.102.176\|192.168.64.2" | head -20
```

I get a list of IPs like this that are not normally connected unless I open Chrome (I am not using Chrome normally and I don't have any profiles or extensions added to it, it's just default chrome):
```bash
  1 142.250.74.77.443
  1 142.250.74.35.443
  1 142.250.74.132.443
```

and these connections disappear if I run the same command a few seconds later after Chrome has started.

if I open CfT manually and I run the same command before and after, I get a list that looks like this:
```bash
   1 142.250.74.78.443
   1 142.250.74.77.443
   1 142.250.74.68.443
   1 142.250.74.35.443
```

which looks very similar to before and the connections also disappear a few seconds after the app is open. So far these are all google IPs.

Now if I open CfT with puppeteer as in the example provided (except that in my use case I am using puppeteer-core to manually handle downloading and installing CfT, however I am making sure to use the correct version of CfT for puppeteer), I get connections that don't close down until after a few minutes and even then not all of them close down.

```bash
   1 8.8.8.8.443 - google
   1 142.250.74.77.443 - google
   1 142.250.74.110.80 - google
```

The setup we're using is we are launching the browser with a bunch of arguments* for our use case from which we create and reuse incognito browser context (not entirely sure if this is how it should be done as best practice - closing and reopening the browser from scratch is not really an option due to performance reasons). We also don't do anything that would 'reset' a browser context except we close/reopen the pages from said browser context after each page rendered. In the case of production environment we create 4 browsers, each with its own incognito browser context and reuse these contexts as we render pages on domains. We have a browser pool service that we take/put back browser contexts from/to.

** * **
<details open>
<summary>* Puppeteer arguments list</summary>
<br>
            '--no-sandbox',<br>
            '--disable-setuid-sandbox',<br>
            '--disable-dev-shm-usage',<br>
            '--disable-accelerated-2d-canvas',<br>
            '--disable-gpu',<br>
            '--no-first-run',<br>
            '--no-zygote',<br>
            // Set persistent Window Size for Page<br>
            `--window-size=${this.pageWidth},${this.pageHeight}`,<br>
            '--disable-infobars',<br>
            '--window-position=0,0',<br>
            '--ignore-certificate-errors',<br>
            '--ignore-certificate-errors-spki-list',<br>
            '--disable-prompt-on-repost',<br>
            '--incognito',<br>
</details>

### Expectation

I am expecting that when opening CfT with puppeteer, to see the same behaviour as I see when manually opening Chrome or CfT regarding the number of tcp connections to google APIs and others.

### Reality

The connections persist for a few minutes and some of them until the browser is closed (which in production it's not closed until the whole domain in scanned - can be 1000s of pages).

### Puppeteer version

21.3.8

### Node version

16.19.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
@sorinfratila just to confirm you mean the connections that the browser establishes to servers while browsing and not the connection from Puppeteer to the browser? why do you expect fewer connections with CfT? 

 it does all sound like an issue for CfT.
@thiagowfx what's the best way to proceed?

**Comment by sorinfratila** [comment]
> just to confirm you mean the connections that the browser establishes to servers while browsing and not the connection from Puppeteer to the browser? why do you expect fewer connections with CfT?

@OrKoN Yes the connections that the browser establishes while browsing, but as I mentioned in the description, I tried with both Chrome and CfT outside of puppeteer and both of them close these extra connections in a few seconds after launch, however when opening CfT with puppeteer, these connections persist longer (3-5 minutes) so I thought this might be a puppeteer issue.

**Comment by OrKoN** [comment]
@sorinfratila do you provide the same command line flags in both instances? this is the list of arguments Puppeteer sets by default for launch https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/node/ChromeLauncher.ts#L166

**Comment by OrKoN** [comment]
I am not able to reproduce on my machine (MacOS): I ran the script and the netstat command returns empty list immediately after the start:

```
❯ netstat -n | grep tcp4 | grep ESTABLISHED | awk '{ print $5; }' | sort | uniq -c | sort -nr | grep -v "17.57.155.26\|17.56.9.14\|52.98.154.146\|3.126.186.102\|52.3.106.226\|34.158.0.131\|20.50.201.204\|198.252.206.25\|185.166.143.37\|20.50.73.13\|20.189.173.23\|170.114.52.2\|170.114.2.47\|170.114.14.68\|17.57.146.22\|162.247.241.1\|140.82.114.26\|13.248.151.210\|13.107.42.14\|17.248.237.65\|13.69.68.64\|13.107.21.239\|20.74.35.75\|20.190.181.5\|20.189.173.11\|13.89.179.9\|204.79.197.239\|140.82.113.25\|108.128.193.124\|104.46.162.224\|131.187.124.132\|64.233.165.109\|54.90.66.198\|54.157.192.81\|52.98.149.130\|40.126.53.18\|51.105.232.141\|3.231.47.80\|13.107.138.8\|17.248.237.66\|17.248.237.128\|127.0.0.1\|54.225.73.58\|20.42.65.90\|23.209.125.28\|17.23.18.34\|104.77.212.94\|104.77.212.80\|44.198.45.157\|17.248.237.64\|17.253.107.202\|52.98.154.130\|20.189.173.1\|35.186.224.47\|35.186.224.41\|173.194.222.109\|17.248.237.67\|44.208.210.155\|52.123.129.14\|20.190.160.27\|162.247.243.29\|140.82.114.25\|107.20.88.15\|13.33.141.2\|140.82.113.26\|104.208.16.89\|13.69.239.73\|20.50.73.11\|20.189.173.7\|13.89.178.26\|13.33.141.44\|13.69.116.104\|13.69.116.107\|104.77.212.40\|13.89.179.10\|192.229.221.95\|140.82.112.26\|40.126.32.101\|3.65.102.105\|76.223.31.44\|17.57.146.54\|170.114.2.54\|170.114.14.70\|104.208.16.90\|20.190.181.4\|143.204.237.129\|18.173.5.113\|185.166.143.38\|143.204.237.44\|18.197.249.189\|3.33.235.18\|3.229.81.33\|3.225.166.25\|13.107.136.8\|3.68.170.153\|17.57.146.27\|185.159.159.148\|18.168.253.132\|185.166.143.44\|185.166.143.31\|140.82.121.4\|3.68.61.181\|3.67.131.16\|20.42.73.27\|17.248.237.68\|34.104.35.123\|34.204.231.216\|35.186.224.17\|23.193.116.193\|74.125.131.108\|95.100.155.75\|64.233.165.108\|35.186.224.25\|18.155.153.70\|18.155.153.36\|17.171.47.23\|54.236.122.12\|54.230.206.48\|54.205.219.43\|17.253.107.201\|140.82.112.25\|35.153.89.158\|17.57.146.56\|17.56.138.35\|17.253.52.247\|54.172.44.252\|52.55.72.199\|20.42.65.88\|52.104.68.41\|3.209.172.172\|104.208.16.88\|34.224.127.104\|34.98.74.57\|35.168.168.82\|54.230.206.47\|54.230.206.81\|162.243.219.16\|17.253.107.203\|20.50.80.209\|20.42.73.25\|54.230.206.106\|52.98.228.210\|54.86.231.251\|52.200.46.145\|52.182.143.209\|52.182.143.208\|52.123.128.14\|52.114.77.128\|52.114.77.128\|52.113.205.21\|52.112.92.55\|40.101.1.25\|34.237.73.95\|3.90.158.208\|17.56.9.23\|52.98.151.66\|52.112.39.48\|170.114.14.73\|170.114.0.179\|17.57.146.133\|52.98.151.82\|52.113.194.132\|15.197.213.252\|132.245.231.0\|8.8.4.4\|74.125.205.109\|64.233.162.108\|52.98.228.226\|216.58.207.202\|173.194.73.109\|13.107.5.93\|13.107.42.18\|108.177.14.108\|40.115.3.253\|40.113.110.67\|40.113.103.199\|40.101.1.15\|52.98.149.146\|3.67.245.95\|192.241.242.235\|192.241.242.235\|185.166.143.36\|185.70.42.22\|96.126.102.176\|192.168.64.2" | head -20


```

**Comment by sorinfratila** [comment]
@OrKoN have you tried it multiple times as the browser starts and runs for a bit ? are you using the script I posted above ?

**Comment by sorinfratila** [comment]
> do you provide the same command line flags in both cases?

@OrKoN which cases are you referring to exactly ? for this test I have not provided any flags, just the script from the description, however I did try it with flags as well, the ones that I posted in this issue and for me it's the same result. Maybe I am missing some flags ?

> this is the list of arguments Puppeteer sets by default for launch

I see, I was actually not aware of this list.

**Comment by OrKoN** [comment]
It seems my instance only uses ipv6 so the netstat command with filters would not work. Do you observe the same behaviour when launching the browser without Puppeteer but with the same flags? You can set the env var `DEBUG=puppeteer:browsers:launcher` to see the final launch command.

**Comment by sorinfratila** [comment]
> Do you observe the same behaviour when launching the browser without Puppeteer but with the same flags?

@OrKoN I will try that and will get back to you, thank you.

**Comment by thiagowfx** [comment]
> it does all sound like an issue for CfT.
> @thiagowfx what's the best way to proceed?

If it's indeed some behavior difference between CfT and Google Chrome, please file a bug here: https://github.com/GoogleChromeLabs/chrome-for-testing/issues/new

As far as I know though there should be no difference in this regard (connections closing prematurely).

**Comment by sorinfratila** [comment]
@OrKoN @thiagowfx ok I tried launching chrome with the same default flags as mentioned in the puppeteer docs and it looks like it's the same behaviour, some connections persist particularly the ones to the IP=142.250...

I tried now launching CfT from puppeteer excluding the default arguments and it seems to behave more or less like the default one and I also changed a bit my logic to how we manage browser contexts and there's definitely fewer connections that don't persist too long so I think we can close this.

Thank you for your help.
