### ISSUE TITLE
[Bug]: Issues arise when using await target.page() inside targetcreated.

### ISSUE THREAD

**Issue by jskorlol** [puppeteer/puppeteer#11103]
### Minimal, reproducible example

```TypeScript
this.browser.on('targetcreated', async (target) => {
    if (target.type() === 'page') {
        const page = await target.page()
        console.log(page)
    }
});

const doAsyncTask = async () => {
            try {
                let pages = await this.browser.pages();
                for (const cdpPage of pages) {
                    try {
                        const readyState = await cdpPage.evaluate('document.readyState');
                        console.log(`[${cdpPage.target()._targetId}] Page readyState:`, readyState);
                    } catch (error) {
                        console.error('Error evaluating page:', error);
                    }
                }
            } catch (error) {
                console.error('Error during execution:', error);
            } finally {
                setTimeout(doAsyncTask, 30000);
            }
        };
        doAsyncTask();
```

### Error string

The code hangs indefinitely

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

After a target is created, a page is generated, and once the loading of that page is complete, the evaluate function is used.
Execute the given code and try opening a page by clicking to open a new window.
A delay of 30 seconds is provided to doAsyncTask to avoid issues with waitForNavigation.

### Reality

When running the following code, if a new tab is opened, the "page.evaluate" event is not called on the new target.page().
Sometimes the call is successful, and sometimes it is not.

When calling `await target.page()` inside targetcreated, subsequent calls to evaluate on that page encounter issues.

If the line `const page = await target.page()` is commented out, this issue no longer occurs.

### Puppeteer version

21.3.8

### Node version

18.17.1

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Windows

**Comment by OrKoN** [comment]
I am unable to reproduce using the provided script but it sounds like it could be similar to https://github.com/puppeteer/puppeteer/issues/11089
