### ISSUE TITLE
Document default behavior for setRequestInterceptionEnabled without page.on('request') listener

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#1110]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v 0.12
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):

**What steps will reproduce the problem?**
add `setRequestInterceptionEnabled` to the code.

_Please include code that reproduces the issue._

Code taken from the example on puppeteer docs.
This code does not do anything cause I am not listening for request event. If I don't pass anything, this should just continue, right?

```js
(async() => {
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = await browser.newPage();
    await page.setRequestInterceptionEnabled(true);
    await page.goto('https://example.com');
    await page.screenshot({
        path: "screenshots/example.png"
    });
    await browser.close();
})();
```
So, I must add this following code afterwards,

```js
await page.on('request', interceptedRequest => {
        interceptedRequest.continue();
    });
```
This should be documented.

**What is the expected result?**
It should block the load of any image.

**What happens instead?**
The page does not load. Or the code does not continue.

**Comment by vsemozhetbyt** [comment]
It seems this should be
```js
page.screenshot({path : 'test.png'});
```
and not the
```js
 browser.newPage({headless: false});
```
but
```js
puppeteer.launch({headless: false})
```

**Comment by entrptaher** [comment]
Such noob mistakes. :O

**Comment by entrptaher** [comment]
@vsemozhetbyt Look at this code,

Previously I pasted the wrong code on hurry. This code does not do anything cause I am not listening for `request` event. If I don't pass anything, this should just continue, right?

```js
(async() => {
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = await browser.newPage();
    await page.setRequestInterceptionEnabled(true);
    await page.goto('https://example.com');
    await page.screenshot({
        path: "screenshots/example.png"
    });
    await browser.close();
})();
```

So, I must add this following code afterwards,
```js
await page.on('request', interceptedRequest => {
        interceptedRequest.continue();
    });
```

This should be documented.

**Comment by vsemozhetbyt** [comment]
@entrptaher Maybe you should add a new issue or reopen this one with a different title, like "Document default behavior for `page.setRequestInterceptionEnabled(true);` without `page.on('request')` listener".

**Comment by xxwait** [comment]
Yes,if you don't wanna listening the Request event,set the setRequestInterceptionEnabled be false!

**Comment by aslushnikov** [comment]
I'll be happy to review PRs to enhance documentation.
