### ISSUE TITLE
Iframe with recaptcha not working (2023)

### ISSUE THREAD

**Issue by charleslana** [puppeteer/puppeteer#11116]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer')

async function getToken() {
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--disable-web-security', '--disable-features=IsolateOrigins,site-per-process']
  })
  const page = await browser.newPage()

  try {
    await page.goto('https://patrickhlauke.github.io/recaptcha/')

    await page.waitForSelector('.g-recaptcha > div > div > iframe')
    const elementHandle = await page.$('.g-recaptcha > div > div > iframe')
    const frame = await elementHandle.contentFrame()
    const value = await frame.evaluate(() => document.getElementById('recaptcha-token').value)
    console.log(value)
  } catch (e) {
    console.error(e)
  }

  await browser.close()
}
getToken()
```

### Error string

Timeout or loop

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

As per the problem below using the same example it doesn't work, the selector doesn't find it as it should

https://stackoverflow.com/questions/62371388/how-to-retrieve-recaptcha-token-from-iframe-with-puppeteer

any help? 

### Expectation

Make the iframe efficient

### Reality

Not working with recaptcha

### Puppeteer version

21.3.8

### Node version

v18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by OrKoN** [comment]
I am unable to reproduce locally.  The script works for me.

**Comment by OrKoN** [comment]
Also works for me on Linux. Are there any additional steps to reproduce the issue?
