### ISSUE TITLE
[Bug]: Generating Blank PDFs when rendering fonts from an external locations such as S3

### ISSUE THREAD

**Issue by hhettiarachchi** [puppeteer/puppeteer#11143]
### Minimal, reproducible example

```TypeScript
There are no adequate checks or conditions to ensure blank PDF are not generatd when rendering third party fonts such as poppins from external locations like S3 consistantly. This can be reproduced in in websites such as react or NodeJS with regression testing.
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I'm trying to generate PDFs from a react website, where it generates blank PDFs randomly. 

While troubleshooting it was found that this website is using poppins fonts loaded from a external s3 location. 

### Expectation

PDF's are generated consistantly

### Reality

It produce blank pages during regression testing with 20% of sucess rate. 

### Puppeteer version

20.8.1

### Node version

20.x

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by OrKoN** [comment]
Please provide a specific reproducible example with the issue you have. In general, Puppeteer forwards whatever PDF is generated by the browser and Puppeteer exposes functions to determine if the page is complete before printing.
