### ISSUE TITLE
pages nevers resolves after chrome update restart because tabs dont reload until manually visited

### ISSUE THREAD

**Issue by nibk** [puppeteer/puppeteer#11147]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer-core')

/*
{
  Browser: 'Chrome/117.0.5938.152',
  'Protocol-Version': '1.3',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
  'V8-Version': '11.7.439.21',
  'WebKit-Version': '537.36 (@e3344ddefa12e60436fa28c81cf207c1afb4d0a9)',
  webSocketDebuggerUrl: 'ws://127.0.0.1:9222/devtools/browser/8593a4c2-ef1d-4363-ac5e-f9aeb8de98c5'
}
*/


(async () => {

	// browserWSEndpoint retrieved from http://127.0.0.1:9222/json/version webSocketDebuggerUrl - see comment above


	const browser = await puppeteer.connect({
		defaultViewport: null,
		browserWSEndpoint,
	})

	try {
		// never resolves if chrome has been restarted and opens existing tabs
		const allPages = await browser.pages()
		console.log('got pages')
	} catch (e) {
		console.error('this failed')
	}

	browser.disconnect()
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This is an unusual use case but it keeps happening to me. Using chrome as my browser with devtools protocol listening on 9222
and following a restart triggered by a chrome update the test case I provided hangs when getting a list of pages. 

This seems to be caused by a combination of tab contents not being reloaded after update and the defaultViewport set to null. Revisiting all tabs manually and loading their contents OR leaving defaultViewport at its default value I don't get the issue.

### Expectation

I expected a list of tabs. 

### Reality

await never resolves.  This should at least throw an error or something tangible - preferably a list of tabs :)

### Puppeteer version

21.3.8

### Node version

19.4.0

### Package manager

npm

### Package manager version

9.2.0

### Operating system

Windows

**Comment by nibk** [comment]
tested against 21.3.8 also

**Comment by eldhoseelias** [comment]
How to configure puppeteer in docker ?

**Comment by OrKoN** [comment]
I am not able to reproduce. Perhaps make sure that you launch Chrome with the same flags used by Puppeteer by default to avoid tab backgrounding and throttling,
