### ISSUE TITLE
[FR]: Support npx @puppeteer/browsers install chrome@dev and improve documentation

### ISSUE THREAD

**Issue by thiagowfx** [puppeteer/puppeteer#11140]
### Steps to reproduce

```
npx @puppeteer/browsers install chrome@dev
npx @puppeteer/browser launch chrome@dev
```

### Expected results

Launch the downloaded Chrome for Testing Dev binary: `chrome/mac_arm-120.0.6051.2`, resolved to the same version used by the `install` command.

### Actual results

Puppeteer tries to launch the following binary:

```
chrome/mac_arm-dev/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
```

Note the `chrome/mac_arm-dev`, instead of `chrome/mac_arm-120.0.6051.2` (the `dev` version at the time this issue was filed).

**Comment by thiagowfx** [comment]
cc @OrKoN @Lightning00Blade FYI

**Comment by OrKoN** [comment]
We should probably do the following (for CLI only):

1) resolve the version nickname to a specific version using the same method as the `install` command.
2) if the version that the nickname resolves to is not found locally, print an error and indicate that the version has to be installed first. 

Cons of this approach: it won't work offline and the launch will be slower.
