### ISSUE TITLE
[Question]Chromium download very slow

### ISSUE THREAD

**Issue by peterschussheim** [puppeteer/puppeteer#1114]
I don't claim the slow download speed is the Chrome team's responsibility, rather, I wanted to make them aware of this issue.

As mentioned in the `Puppeteer` readme, `Chromium` is required and will be downloaded when installing from NPM...no problem.  Is it just me or is it **SLOW** to download??  I have plenty of bandwidth and experience fast speeds with everything which is why this is puzzling.

Today alone, I've installed `Puppeteer` and subsequently `Chromium` four separate times with download speeds of **125 - 150KB/s**.

Thanks for all your amazing work on Chrome!  👍

**Comment by ebidel** [comment]
How long is it taking for you? I installed a fresh copy a few times today. It took around probably 10s or less.

**Comment by peterschussheim** [comment]
Weird, today it is taking 10s for me too.  I ran a few tests last night and timed it taking 10 minutes.  Anyways, I will close this issue.  Thanks!

**Comment by suhaotian** [comment]
Hi, you should try [tiny-puppeteer](https://www.npmjs.com/package/tiny-puppeteer) :)
