### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by eldhoseelias** [puppeteer/puppeteer#11146]
NA

**Comment by OrKoN** [comment]
Please use the docker image we provide https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer

**Comment by eldhoseelias** [comment]
@OrKoN How to add puppeteer configuration into my docker file ?
Docker file
-----------

# ---- Base Node ----
FROM node:18.14.0-buster-slim AS base


WORKDIR /srv

COPY package.json .
..
..
..

**Comment by OrKoN** [comment]
@eldhoseelias please post this kind of questions on stackoverflow as this bug tracker is not the right place for it.
