### ISSUE TITLE
Sending 'Enter' to page does not work synchronously

### ISSUE THREAD

**Issue by namelus** [puppeteer/puppeteer#1115]
Hi everyone

Relatively new to Node and Puppeteer. Really excited about both - thanks to you all for your hard work! And also loving this markdown stuff. 3 cheers!!!

This is a 2 part-er 
- one potential issue, and 
- secondly a request for comment / advice.

My code intends to:
1. log into github 
2. search 'john' 
3. click the users' tab
4. take a screenshot
5. and finally close the browser

## Issue and Workaround
I have 1, 4, and 5 accomplished, and am working on 2. With that my reason for writing, i.e. **I'm having trouble sending the Enter / Return key to the page**.

After some experimentation (you'll see the commented experiments in my code below) I eventually discovered that when **commenting the browser.close() command caused the Enter key to be sent to the page successfully**. So I believe that the await is not behaving correctly, ie. synchronously. Either way some issue seems to be there.

## Advice
To work around this I am looking at two candidates to delay before the 4 and then 5 (and eventually 3): **page.waitFor** and **page.waitForNavigation**. I looked at the API doc and couldn't really appreciate the differences in these apart from the inputs of each. Your thoughts / advice?

### Some environment details:
- puppeteer 0.12.0, on a 
- windows 7 home pc, with 
- node 8.7.0

### Here's my code: 

```
const puppeteer = require('puppeteer');
const CREDS = require('./creds');

async function run() {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();

  // dom element selectors
  const USERNAME_SELECTOR = '#login_field';
  const PASSWORD_SELECTOR = '#password';
  const BUTTON_SELECTOR = '#login > form > div.auth-form-body.mt-3 > input.btn.btn-primary.btn-block';


  await page.goto('https://github.com/login');
  await page.click(USERNAME_SELECTOR);
  await page.keyboard.type(CREDS.username);

  await page.click(PASSWORD_SELECTOR);
  await page.keyboard.type(CREDS.password);

  await page.click(BUTTON_SELECTOR);

  await page.waitForNavigation();


  const SEARCH_SELECTOR = 'input.form-control:nth-child(2)';

  await page.click(SEARCH_SELECTOR);
  await page.keyboard.type('john');
  // await page.keyboard.press('Enter');
  // await page.type(SEARCH_SELECTOR, String.fromCharCode(13));
  // await page.type(SEARCH_SELECTOR, 'monkey');
  // const submit = await page.$(SEARCH_SELECTOR);
  // await submit.evaluate( submit => submit.click());
  await page.keyboard.sendCharacter(String.fromCharCode(13));
  // await page.wait

  await page.screenshot({ path: 'screenshots/github.png' });

  browser.close();
}

run();
```

**Comment by ebidel** [comment]
It looks like there may be some bugs with `page.click`. https://github.com/GoogleChrome/puppeteer/issues/1126

BTW, instead of doing the clicking/keyboard combo. You can use `page.type` and pass it a selector directly: https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#pagetypeselector-text-options. I was able to get things working with:

```js
const puppeteer = require('puppeteer');

async function run() {
  const browser = await puppeteer.launch({headless: true});
  const page = await browser.newPage();

  await page.goto('https://github.com/login');
  await page.type('#login_field', 'USERNAME');
  await page.type('#password', 'PASSWORD');
  await page.$eval('[name="commit"]', el => el.click());

  await page.waitForNavigation();

  await page.type('.header-search-input', 'john');

  const formHandle = await page.$('.js-site-search-form');
  await page.evaluate(form => form.submit(), formHandle);
  await formHandle.dispose();

  await page.waitForNavigation();

  await page.screenshot({path: 'github.png'});

  browser.close();
}

run();
```

**Comment by namelus** [comment]
Thanks for that Eric. I'll give it a try :)
