### ISSUE TITLE
Bug: `npm run build --watch` hangs (wireit)

### ISSUE THREAD

**Issue by thiagowfx** [puppeteer/puppeteer#11155]
How to reproduce:

```
npm run build --watch
```

Then make a change in e.g. `packages/puppeteer-core/src/node/ChromeLauncher.ts`.

The command will then hang on `test/installation:build:packages`.

One workaround: Removing that dependency from `build` prevents it from hanging.
Another workaround: Use `npm run build -w puppeteer --watch` instead.

**Comment by OrKoN** [comment]
@Lightning00Blade do you want to support watch and fix this? if not, let's close it and we can also remove it (I am not relying on it).
