### ISSUE TITLE
Generating a PDF includes a white border on the downloaded PDF

### ISSUE THREAD

**Issue by RathodAnnu13** [puppeteer/puppeteer#11172]
### Minimal, reproducible example

```TypeScript
const pdf = await page.pdf({
            path: './pdf/white_border_3.pdf',
            printBackground: true,
            preferCSSPageSize: true,
            height: '800px',
            width: '650px',
            scale: 1,
            margin: {top: '0px',right: '0px',bottom: '0px',left: '0px'}
          })
```

### Error string

A white border is added on my PDF when generated using Puppeteer. 

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

Puppeteer cover the entire page with HTML content without extra white borders

### Reality

[white_border_3.pdf](https://github.com/puppeteer/puppeteer/files/12915840/white_border_3.pdf)

### Puppeteer version

21.3.8

### Node version

16.13.0

### Package manager

npm

### Package manager version

8.1.0

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Hello, can you please provide the HTML used to generate the PDF?
That will make debugging this much easier on our end.

**Comment by RathodAnnu13** [comment]
@Lightning00Blade  please check https://codepen.io/Annu-Valand/pen/RwEzpOd?editors=1111 for HTML

**Comment by rsainiWin** [comment]
I'm facing the same issue

**Comment by tjuzen** [comment]
I'm having the same issue, the PDF generated has a white border on the right and on the bottom. Any fix ?

**Comment by Leon-Kunstek** [comment]
Been experiencing the same problem, turns out it was a part of the background ending up in the document due to page format miscalculation (296mm for A4 paper instead of 297mm), noticed it because it was pushed around by margins. Might be something to look out for, hope this helps someone.

**Comment by nicmeynard** [comment]
issue is still present, and linked to puppeteer as CSS rules and Puppeteer sizes are set correctly, we should not be force to adapt standard CSS to work with Puppeteer.

**Comment by Lightning00Blade** [comment]
@nicmeynard If you have a better reproducible example, please share it here, or open a new issue.
Puppeteer uses the Browser under the hood to generate PDF, so apart from sending the correct command it has no control of how PDFs are generated.

**Comment by Serzhs** [comment]
I had the white border as well, my fix was to change CSS into my HTML part from
```
@page {
    size: A4 portrait;
    margin-top: 20mm;
    margin-bottom: 10mm;
}
```
to
```
@page {
    size: 210.2mm 297mm;
    margin-top: 20mm;
    margin-bottom: 10mm;
}
```

that extra 0.2 mm did the trick
