### ISSUE TITLE
Why does `page.$eval()` throw an error if no match found?

### ISSUE THREAD

**Issue by 59023g** [puppeteer/puppeteer#1117]
Confusing because `document.querySelector()` just returns `null`. 

I'm using Puppeteer to scrape a utterly horrendous .NET UI. Unfortunately I have a scenario where if one element exists, I'll assign it to `version`, if not I look for the dropdown's `selected` value. 

Puppeteer 0.12.0 ( MacOS 10.13 )

```
const getVersion = async () => {
  // this is because if there are multiple versions, .net will create a dropdown
  let single = await resultPage.$eval('#ctl00_ContentPlaceHolder1_lblVersion2', el => el.innerHTML ) 
  if ( +single ) {
    return single
  } else {
    return await resultPage.$eval('#ctl00_ContentPlaceHolder1_lstVersion2 > option[selected="selected"]', el => el.innerHTML )
  }
}
```

Great software by the way. Thank you

**Comment by 59023g** [comment]
I solved it by using `page.evaluate()` with a `document.querySelector()` inside. Still doesn't answer my question about the design decision to throw an error of `page.$eval()` doesn't find a match.

```
const getVersion = async () => {
  // this is because if there are multiple versions, .net will create a dropdown
  return await resultPage.evaluate( () => {
    const single = document.querySelector( '#ctl00_ContentPlaceHolder1_lblVersion2' )
    const dropDown = document.querySelector( '#ctl00_ContentPlaceHolder1_lstVersion2 > option[selected="selected"]' )
    // check if exists
    if ( single ) {
      return single.innerHTML
    } else {
      return dropDown.innerHTML
    }
  } )
}
```

**Comment by ebidel** [comment]
I think one challenge here is that `page.$eval()` does more than one thing. It finds the element  and also runs your callback code. If it just returned `null`, is that b/c the element couldn't be found or the resolve value from the callback?

**Comment by 59023g** [comment]
Fair. 

Element could not be found:
`Error: Error: failed to find element matching selector "#ctl00_ContentPlaceHolder1_lblVersion2"`

It could still find the element and run callback with a `null` value assigned param, right? 

I suppose my confusion lies with docs description of the `page.$eval()` method saying it runs `document.querySelector()` and my subsequent assumption it would behave the same if no element found. 

Really a nit at this point.

( https://github.com/GoogleChrome/puppeteer/blob/master/lib/FrameManager.js#L252 )
