### ISSUE TITLE
[Feature]: Update to remove depricated chrome.sockets.tcp

### ISSUE THREAD

**Issue by Puupuls** [puppeteer/puppeteer#11173]
### Feature description

chrome.sockets.tcp is being phased out of chtome as mentioned here: https://developer.chrome.com/docs/extensions/reference/sockets_tcp/

Some of chromium browsers like MS Edge already have removed support for it

**Comment by jrandolf** [comment]
Hi there, this looks like something that should be reported on crbug.com? Is there something specific you need from Puppeteer?
