### ISSUE TITLE
[Bug]: o código funciona perfeitamente fora do modo headless, porém com o modo ativo, ele nao consegue avançar em etapa, nem lançar erros, sem nenhum tipo de erro aparente, a seguir, meu código:

### ISSUE THREAD

**Issue by Alanissilveira** [puppeteer/puppeteer#11181]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const config = require('./config.json');
const IptuRepository = require('./Repository/IptuRepository.js');
const fs = require('fs');
const pdf = require('pdf-parse');
const axios = require('axios'); 

async function GuiasDeIptu() {


  const browser = await puppeteer.launch({
    headless: true,
    defaultViewport: null,
    args: ['--enable-javascript'],
  });
  const page = await browser.newPage();

  // console.log("Iniciei");
  await page.goto('https://e-gov.betha.com.br/cdweb/03114-365/contribuinte/directlogin.faces?iEntidades=t4EiJk503gM%3D&iDatabases=25QN-yzeEPY%3D');
  console.log("Entrei na url");

  const emitir = await page.$('div[class=\'icone emitir\'] span');
  await emitir.click();
  console.log("cliquei em emitir");


  const cndImovel = await page.$x('//*[@id="3"]/div[2]/ul/li[2]/a');
  await cndImovel[0].click();

  console.log("cliquei em cnd");
  const connectionDb = new IptuRepository(config);

  let input = await connectionDb.gatherSequence();

  // console.log("Input do banco de dados:", input);

  //////////////////seleciona caixa input
  await page.waitForSelector('#mainForm\\:iImoveis', { visible: true });
  const imvBt = await page.$('#modoAcesso > div.grid > div:nth-child(4) > div > div > div > a');
  await imvBt.click();
  console.log("esta visivel");

// transforma o result input atual em string 
  let inputString = input.toString();  


  ///////////escreve a input
  await page.$eval('#mainForm\\:iImoveis', (inputField, value) => {
    inputField.value = value;
  }, inputString);
  await page.click('#mainForm\\:btIImoveis');

  console.log('escrevi input');


  //////////////botao input
  await page.waitForSelector('#mainForm\\:btIImoveis');
  await page.click('#mainForm\\:btIImoveis');

  
await page.waitForTimeout(1000);
  await page.waitForSelector('#mainForm\\:t-imoveis > tbody > tr > td:nth-child(5) > img');
  
     
      await page.click('#mainForm\\:t-imoveis > tbody > tr > td:nth-child(5) > img');
  ////esperar a pagina carregar o novo browser 
   const newTarget = await browser.waitForTarget(target => target.opener() === page.target());
   
   const newPage = await newTarget.page();
 
   console.log('espernado cnd ');
    //////////// Aqui estaria o erro, é uma pagina que esta abrindo um pdf o qual quero pegar
    console.log('esperenado cnd');
   console.log( await newPage.content());
 
  
   const pdfUrl = await newPage.url();
   //// obter o link do pdf
   console.log(pdfUrl);
   
   ///utilizando axios do js para obter o response de pdf
   const response = await axios.get(pdfUrl, { responseType: 'arraybuffer' });
   const pdfBuffer = response.data;
  

  // Ussando pdf-parse para extrair texto do PDF
  const responseCND = (await pdf(pdfBuffer)).text;
  
  console.log(responseCND);
   return responseCND.text;
   

  await browser.close();
}




GuiasDeIptu().then((response) => {
  // Faça algo com a resposta, se necessário
  // Encerre o processo Node.js
  process.exit();
}).
  catch((error) => {
    console.error('Ocorreu um erro:', error);

    // Encerre o processo Node.js com um código de erro
    process.exit(1);
  });
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm using puppeter for web scraping, the page I want to use opens a new page with a Js function that loads a freshly created pdf, the waiting time is normally 5/6 seconds. Outside of headless mode it works perfectly, but in headless mode, which is what I want to use, it doesn't work at all.
.
### Expectation

I hope the code can wait for the pdf to load, so I can get the download link and parse it. I would also like the tool to throw an error, and your answer as to why it doesn't work headless.

### Reality

It hangs, doesn't throw an error, even with triple the waiting time it doesn't advance and doesn't throw an error.

### Puppeteer version

puppeteer@21.3.8

### Node version

v18.15.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
Please update your Bug report to English so I can review it properly. 
Also please make a smaller reproducible example only using `puppeteer` without external packages. as the site you provide can't be access on our end.

**Comment by sentient06** [comment]
English mate. https://www.deepl.com/en/translator

**Comment by Alanissilveira** [comment]
Está atualizado.

**Comment by Alanissilveira** [comment]
> Provavelmente algo relacionado ao Chrome headless não ter um visualizador de PDF #1872 . Você pode tentar usar o [modo New Headless no Chrome](https://developer.chrome.com/articles/new-headless/) e ver se isso resolve seu problema. Para usá-lo no Puppeteer
> 
> ```ts
> const browser = await puppeteer.launch({
>     headless: 'new',
>     defaultViewport: null,
>     args: ['--enable-javascript'],
>   });
> ```

Obrigada amigo, deu certo!

**Comment by Alanissilveira** [comment]
> Provavelmente algo relacionado ao Chrome headless não tem um visualizador de PDF #1872 . Você pode tentar usar o [modo New Headless no Chrome](https://developer.chrome.com/articles/new-headless/) e ver isso resolver seu problema. Para usá-lo no Puppeteer
> 
> ```ts
> const browser = await puppeteer.launch({
>     headless: 'new',
>     defaultViewport: null,
>     args: ['--enable-javascript'],
>   });
> ```



> Provavelmente algo relacionado ao Chrome headless não tem um visualizador de PDF #1872 . Você pode tentar usar o [modo New Headless no Chrome](https://developer.chrome.com/articles/new-headless/) e ver isso resolver seu problema. Para usá-lo no Puppeteer
> 
> ```ts
> const browser = await puppeteer.launch({
>     headless: 'new',
>     defaultViewport: null,
>     args: ['--enable-javascript'],
>   });
> ```

Obrigada amigo, deu certo!

**Comment by Alanissilveira** [comment]
> Provavelmente algo relacionado ao Chrome headless não tem um visualizador de PDF #1872 . Você pode tentar usar o [modo New Headless no Chrome](https://developer.chrome.com/articles/new-headless/) e ver isso resolver seu problema. Para usá-lo no Puppeteer
> 
> ```ts
> const browser = await puppeteer.launch({
>     headless: 'new',
>     defaultViewport: null,
>     args: ['--enable-javascript'],
>   });
> ```
Obrigada amigo, deu certo!

**Comment by Leojoli** [comment]
Caso queira visualizar o navegador execultando os comandos, podera ultilizar o seguinte:

{
 headless: false,
 executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe"
 }
