### ISSUE TITLE
[Feature]: Inquiry about Breaking Content Element in PDF Generation using Puppeteer Sharp (ASP.NET Core MVC)

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#11186]
### Feature description

I am using the Puppeteer Sharp library specifically for PDF generation, and I would like to inquire about breaking a content element when there is not enough space on the page. Specifically, if an element at the bottom of the page cannot be displayed in its entirety due to limited space, I would like it to automatically break and display the element on the next page without causing any errors or incorrect display.

I am wondering if Puppeteer Sharp, specifically for PDF generation, supports this feature or if there is any other way to achieve this goal through different options or methods. My desire is for the last element to automatically break and display correctly on the next page when there is not enough space on the current page.

Thank you very much for your assistance!

**Comment by Lightning00Blade** [comment]
Hello,

Just a reminder that the [Puppeteer Sharp](https://github.com/hardkoded/puppeteer-sharp) is a separate package not maintained by us.

This should be achievable by using CSS property `break-inside: avoid;`

Here is HTML and Puppeteer script I tested it with:
```html
 <head>
    <style>
      body,
      div {
        margin: 0;
        padding: 0;
        width: 650px;
        height: 200px; // Change to example 450px to see it break
        break-inside: avoid;
      }
      div {
        background-color: green;
      }
    </style>
  </head>

  <body>
    <div></div>
    <div></div>
  </body>
```
```ts
await page.pdf({
  path: "./pdf/break.pdf",
  printBackground: true,
  height: "800px",
  width: "650px",
  margin: { top: "0px", right: "0px", bottom: "0px", left: "0px" },
});
```
