### ISSUE TITLE
[Bug]: { Error: Cannot find module 'puppeteer-core/internal/puppeteer-core.js' on Ubuntu Server

### ISSUE THREAD

**Issue by emma-melx** [puppeteer/puppeteer#11191]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const mysql = require('mysql2/promise');

const LOGIN_INTERVAL = 120000; // 2 minutes in milliseconds
const LOGOUT_INTERVAL = 300000; // 5 minute in millisecondspm2

const loginAndRefreshToken = async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

........................
```

### Error string

{ Error: Cannot find module 'puppeteer-core/internal/puppeteer-core.js

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

am expect to run this project with no error by using pm2 

am using Ubuntu server 

### Reality

when i run pm2 logs am get this error app does not running but if i run node app.js it running well

logs error

/root/.pm2/logs/app-out.log last 15 lines:
/root/.pm2/logs/app-error.log last 15 lines:
0|app      |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|app      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|app      |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|app      |     at Module.require (internal/modules/cjs/loader.js:692:17) code: 'MODULE_NOT_FOUND' }
0|app      | { Error: Cannot find module 'puppeteer-core/internal/puppeteer-core.js'
0|app      |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
0|app      |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
0|app      |     at require (internal/modules/cjs/helpers.js:25:18)
0|app      |     at Object.<anonymous> (/var/www/html/token-service/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js:33:14)
0|app      |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|app      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|app      |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|app      |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|app      |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|app      |     at Module.require (internal/modules/cjs/loader.js:692:17) code: 'MODULE_NOT_FOUND' }
 

### Puppeteer version

21.3.6

### Node version

18.18.0

### Package manager

npm

### Package manager version

pm2 - 5.3.0

### Operating system

Linux

**Comment by emma-melx** [comment]
how to update a version ?

**Comment by Lightning00Blade** [comment]
As you state there is no issue on Puppeteer side as your script runs on it's own, so I will be closing this issue.
The question is more suited for https://stackoverflow.com/ 

The way PM2 is set up it changes module resolution, some previous issue with PM2 were resolved when users update to the latest version of it.
A quick search suggest you may need to set up `cwd` in your config for this to work correctly.
