### ISSUE TITLE
test: lazy-oopif-frame.html uses an invalid src for the lazy loaded iframe

### ISSUE THREAD

**Issue by juliandescottes** [puppeteer/puppeteer#11198]
As we started implementing lazy iframe loading in Firefox, the `[oopif.spec] OOPIF-debug OOPIF should support lazy OOP frames` test started failing.

I looked a bit into it, and while I'm not sure why it passed before, the lazy loaded iframe looks odd:

> <iframe width="100%" height="300" src='www.example.com' loading="lazy"></iframe>

With `src='www.example.com'` the iframe will not attempt to load the actual example.com, but just hit a relative path from the base url of the top page. I'm not sure what the intent was, but I guess we should rather use a valid URL which resolves to something on the test server?

**Comment by OrKoN** [comment]
cc @Lightning00Blade
