### ISSUE TITLE
[Bug]: invalid state of textContentCache after mutation in text-node

### ISSUE THREAD

**Issue by Donnatello** [puppeteer/puppeteer#11199]
### Feature description

I would like to start with apologising for using a feature-template, just the bug-template is not suitable for the problem I’m going to describe below. (please change the label of the ticket to "bug")

**Bug:** if a mutation occurs within a text-node (type: 3) without a mutation of the parent element (type: 1) in its text, then [textContentCache](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/injected/TextContent.ts#L70) remains in an outdated invalid state (not updated) due to incorrect MutationOverserver settings that are missing this mutation.
Next, the problem affects TextQuerySelector (custom p-selector).

I found the **root of the problem**:
`TextQuerySelector` has a condition `instanceof Element` before calling `createTextContent` ([TextQuerySelector.ts#L51](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/injected/TextQuerySelector.ts#L51))
Similarly: [TextContent.ts#L135](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/injected/TextContent.ts#L135) and [TextContent.ts#L142](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/injected/TextContent.ts#L142)
And then the cache begins to observe mutations precisely on this Element ([TextContent.ts#L146](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/injected/TextContent.ts#L146))

Problem is in settings: `{ childList: true, characterData: true, }`

> [characterData]
    Set to true to monitor the specified target node (and, **if subtree is true, its descendants**) for changes to the character data contained within the node or nodes. The default value is true if characterDataOldValue is specified, otherwise the default value is false.
see: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe#characterdata

`childList` setting not affect on `characterData`. And the changes on the text-node, that happens to always be a child of the observer target (always Element in case of TextQuerySelector) and an absence of `subtree: true` - doesn’t  trigger the mutation in the observer.

**Fix:** use the following settings `{ childList: true, characterData: true, subtree: true}` here [TextContent.ts#L146](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/injected/TextContent.ts#L146)

I’ve checked the proposed changes locally and after adding a subtree, the search works as expected.
Original (incorrect) state was like this:
`page.locator('::-p-text(NewText)').wait()` - failed
`page.locator('::-p-text(OldText)').wait()` - found Element with "NewText" in.

Information about the environment used and a product version were deliberately omitted as it seems obvious that it doesn’t cause the problem.

**Comment by Lightning00Blade** [comment]
Hello, thank you for issue and PR a colleague of my was assigned to take a look. 
In the mean time, can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that this behavior can be observed?
