### ISSUE TITLE
Rename page.setHTTPHeaders -> setExtraHTTPHeaders

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#112]
It should take an array or map. We want you to be able to specify order.

**Comment by aslushnikov** [comment]
I'm confused about this point.

The protocol accepts only key-value objects as headers. Do we want to have an array-based API here which would convert into vanilla js objects under the hood to pass over to the protocol? In this case, there would be no order in fact.

@pavelfeldman, what was the motivation behind this?

**Comment by Garbee** [comment]
I'd recommend a plain-object or map as parameters instead of an array. Or, we could have it take a manually build `Headers` object as the parameter and let that handle the construction on the user end. Then we simply append each entry to the primary headers object.

**Comment by aslushnikov** [comment]
We've discussed this with @pavelfeldman and it looks like we'd be able to persist the headers order while passing headers in both directions over the protocol.

For the API, the Map seems to be the optimal choice to make it clear there's an order.

For the record: we want headers order because it turned out that there are certain bugs related to http headers order, so clients do care.

**Comment by aslushnikov** [comment]
It turned out that in case of `setExtraHTTPHeaders`, the header order is not preserved.

```js
it('should retain order', SX(async function() {
  // set extra HTTP headers
  await page.setExtraHTTPHeaders(new Map(Object.entries({
    cc: 'cc',
    aa: 'aa',
    bb: 'bb',
  })));
  page.navigate(EMPTY_PAGE);

  // wait for request to be send
  let request = null;
  page.on('request', r => request = r);
  await waitForEvents(page, 'request');
  expect(request).toBeTruthy();

  // extract headers order
  let headers = Array.from(request.headers.keys()).filter(name => name.length === 2);
  expect(headers).toEqual(['cc', 'aa', 'bb']);
}));
```
