### ISSUE TITLE
[Bug]: New Headless Ignores: --disable-features=AutoupgradeMixedContent

### ISSUE THREAD

**Issue by JAD3N** [puppeteer/puppeteer#11207]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {
	const browser = await puppeteer.launch({
		headless: "new",
		// headless: true, // <-- using the old version fixes the problem
		args: ["--disable-features=AutoupgradeMixedContent"], // I have also tried using --disable-web-security and --allow-running-insecure-content
	});

	const page = await browser.newPage();
	await page.goto("http://neverssl.com");

	console.log(page.url());

	if (page.url().startsWith("https://")) {
		throw new Error("This shouldn't redirect to HTTPS!");
	}
})();
```

### Error string

This shouldn't redirect to HTTPS!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been trying to measure redirect timings and noticed that in the new headless mode that I can't disable the autoupgrade to HTTPS.

### Expectation

I'm expecting this to not redirect to HTTPS since I've disabled the feature, the domain is not in any HSTS preload lists and doesn't specify any HSTS headers.

### Reality

For some reason it redirects (307) to HTTPS. It also includes the `Non-Authoritative-Reason` header set as  `HttpsUpgrades`. 

### Puppeteer version

21.4.0

### Node version

18.17.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
Does the behaviour match the `headless: false` behaviour?

cc @thiagowfx it appears that the args are not correctly merged although it does not affect this issue most likely.

**Comment by thiagowfx** [comment]
I checked it locally, the args are being correctly merged:

```
[
  'Translate',
  'AcceptCHFrame',
  'MediaRouter',
  'OptimizationHints',
  'ProcessPerSiteUpToMainFrameThreshold',
  'AutoupgradeMixedContent'
]
```

**Comment by thiagowfx** [comment]
Also, even if we remove all other features, the same error is thrown.

**Comment by JAD3N** [comment]
> Does the behaviour match the `headless: false` behaviour?

Just gave it a go, strangely I can only get it to work with `headless: true`. Is there any other way to prevent auto HTTPS upgrades?

**Comment by OrKoN** [comment]
@JAD3N it does not look so. Could you try filing a feature request at crbug.com but the new headless matches the headful mode in behaviour and there is no bug from Puppeteer's perspective? I am pretty sure it would reproduce without Puppeteer as Puppeteer just passes the arguments down to the browser.

**Comment by OrKoN** [comment]
I believe this is the recent change in Chrome https://blog.chromium.org/2023/08/towards-https-by-default.html and it didn't affect the old headless as that is a technically separate implementation of the browser (see https://developer.chrome.com/articles/new-headless/).
