### ISSUE TITLE
[Bug]: Firefox. Cannot connect to existing browser in private mode

### ISSUE THREAD

**Issue by kovasv** [puppeteer/puppeteer#11203]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; 
const browserURL= "http://127.0.0.1:12345";
const pageURL ="https://podrobnosti.ua/";
// firefox started before in cmd "C:\Program Files\Mozilla Firefox\firefox.exe" --remote-debugging-port=12345 --private-window


(async () => {
    await new Promise(resolve => setTimeout(resolve, 5000));
    const browser = await puppeteer.connect({
        browserURL,
        defaultViewport: null,
        ignoreHTTPSErrors:true,
    });

    const pages = await browser.pages();

    if (pages.length > 0) {
        let page = pages[0]; // Select the first tab
        await page.goto(pageURL);
}})();
```

### Error string

Error connecting to the browser: TimeoutError: Navigation timeout of 30000 ms exceeded

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I Tried to connect to existing Firefox (115.3.1esr (64-bit)
Firefox has been  started in private mode via cmd with command "C:\Program Files\Mozilla Firefox\firefox.exe" --remote-debugging-port=12345 --private-window

method  `await page.goto()`  triggers an error:
Error connecting to the browser: TimeoutError: Navigation timeout of 30000 ms exceeded

If I try to connect to Firefox that has been stared not in private mode - no problem.

### Expectation

possible to connect to existing  incognito mode Firefox and perform   await page.goto(pageURL);

### Reality

 await page.goto(pageURL);  - timeout connection to browser

### Puppeteer version

21.3.8

### Node version

v16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Windows

**Comment by OrKoN** [comment]
cc @whimboo

**Comment by whimboo** [comment]
The Firefox profile as used here is most likely not prepared for Puppeteer and misses certain automation related preferences. This could be seen in the Firefox logs by this line:

> 1698051681427	CDP	WARN	Invalid browser preferences for CDP. Set "fission.webContentIsolationStrategy"to 0 and "fission.bfcacheInParent" to false before Firefox starts.

With both prefs not correctly set any navigation might not work. And this is not something that we are going to change for the experimental CDP support in Firefox. As workaround you could [set those prefs on your own](https://github.com/puppeteer/puppeteer/blob/bcd1a8e597e1d558fac04556be5cd8ed0f92df1d/packages/browsers/src/browser-data/firefox.ts#L224-L228) for the given Firefox profile, but make sure that it's not something that you do for your daily profile.

Please report back if that works. From our side it's a wontfix.

**Comment by kovasv** [comment]
@whimboo  Unfortunately  in my case I cannot launch browser with prefs  because it has been launched by other app. I cannot control it.
Thank's Henrik for your support.

**Comment by whimboo** [comment]
FYI when Puppeteer will support `puppeteer.connect` with the WebDriver BiDi protocol it should then work. @OrKoN might know more already when this is going to happen.
