### ISSUE TITLE
"[device-request-prompt.spec] device request prompt does not crash" is flaky with Firefox

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11215]
See https://github.com/puppeteer/puppeteer/actions/runs/6596315106/job/17922262144

Firefox does not support these CDP commands so we could perhaps skip those tests for Firefox.

**Comment by thiagowfx** [comment]
We skip them by adding them to the test expectations file, correct?

**Comment by OrKoN** [comment]
Yes
