### ISSUE TITLE
"[navigation.spec] navigation Page.goto should return last response in redirect chain" is flaky

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11219]
See https://github.com/puppeteer/puppeteer/actions/runs/6596342669/job/17922321476?pr=11214

cc @Lightning00Blade

**Comment by EliotFR44** [comment]
Same prob here :|

**Comment by OrKoN** [comment]
I have seen it flake again on multiple occasions (example https://github.com/puppeteer/puppeteer/actions/runs/8659330778/job/23745012262?pr=12261)

**Comment by OrKoN** [comment]
Not flaky anymore according to test expecations.
