### ISSUE TITLE
How to Disable images in Puppeteer?

### ISSUE THREAD

**Issue by TheOne1006** [puppeteer/puppeteer#1121]
How disable `<img>`  load

**Comment by vsemozhetbyt** [comment]
Possible solutions:

https://github.com/GoogleChrome/puppeteer/blob/master/examples/block-images.js

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionenabledvalue (see code example)

**Comment by ebidel** [comment]
Yep, we have examples for this.

**Comment by TheOne1006** [comment]
Thanks & good day!

**Comment by d668** [comment]
this sucks

**Comment by xndxcsd** [comment]
> this sucks

@d668 why you say so?

**Comment by ralyodio** [comment]
how do I block css files?

**Comment by MohammadJamali** [comment]
> Possible solutions:
> 
> https://github.com/GoogleChrome/puppeteer/blob/master/examples/block-images.js
> 
> https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionenabledvalue (see code example)

404

**Comment by vsemozhetbyt** [comment]
@MohammadJamali
https://github.com/puppeteer/puppeteer/blob/main/examples/block-images.js
https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagesetrequestinterceptionvalue

**Comment by brauliobo** [comment]
@vsemozhetbyt 404 again :P

**Comment by vsemozhetbyt** [comment]
@brauliobo 
https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.page.setrequestinterception.md
