### ISSUE TITLE
Support additional languages?

### ISSUE THREAD

**Issue by bootstraponline** [puppeteer/puppeteer#1122]
WebDriver allows using any language. It looks like there's no way to have puppeteer clients in other languages? It'd be nice to have a machine-readable API which could then generate clients for arbitrary languages (similar to gRPC or the Google API Discovery format).

I think this would also help advance one of the puppeteer goals:
> Eventually, these other frameworks could adopt Puppeteer as their foundational layer.

**Comment by aslushnikov** [comment]
> It looks like there's no way to have puppeteer clients in other languages?

There's Chrome Remote Debugging protocol that has a lot of clients in various of languages: [protocol clients](https://github.com/ChromeDevTools/awesome-chrome-devtools#chrome-devtools-protocol). Puppeteer is a shim atop of the protocol.

> It'd be nice to have a machine-readable API which could then generate clients for arbitrary languages (similar to gRPC or the Google API Discovery format).

That's the protocol description files, check out [browser protocol](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/browser_protocol.json?q=browser_protocol.json&sq=package:chromium&dr) and [js protocol](https://cs.chromium.org/chromium/src/v8/src/inspector/js_protocol.json?q=js_protocol.json&sq=package:chromium&dr).

**Comment by bootstraponline** [comment]
> That's the protocol description files, check out browser protocol and js protocol.

It looks like no one is generating clients from those JSON files, instead, they're being used as a human reference. Dev tools is lower level than puppeteer. The recently merged JSDoc/TypeScript support is probably the closest match to a machine-readable API for puppeteer itself. 

> There's Chrome Remote Debugging protocol that has a lot of clients in various of languages:

Yeah, I guess I was hoping puppeteer would be more like ChromeDriver. A puppeteer server that exposes a high-level API, and JavaScript is one of the many available clients. It seems like the vision is to have everything only in JS though.

**Comment by aslushnikov** [comment]
> It looks like no one is generating clients from those JSON files, instead, they're being used as a human reference.

On the contrary, they're heavily used for code generation. Check out [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface/).

**Comment by bootstraponline** [comment]
> On the contrary, they're heavily used for code generation. Check out chrome-remote-interface.

What project reads the JSON files and outputs clients in different languages?

For API description JSON, it's [google/apis-client-generator](https://github.com/google/apis-client-generator). For protobuf, it's [googleapis/api-compiler](https://github.com/googleapis/api-compiler)

For dev tools, I'm not seeing anything like that in `chrome-remote-interface`
