### ISSUE TITLE
[Bug]: Output of console.trace() differs from the one returned by the browser

### ISSUE THREAD

**Issue by GianlucaDeStefano** [puppeteer/puppeteer#11237]
### Minimal, reproducible example

Webpage:
```Html
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>Simple example 1</title>
        <script>
            function f1() {
                console.trace();
            }
            eval('f1();');
        </script>
</head>
<body>
    Simple example 1
</body>
</html>
```

Pupppeteer script:
```TypeScript

const puppeteer = require("puppeteer");

const browserInstance = await puppeteer.launch({
                headless: this.headless,
                args: ['--no-sandbox', '--disable-setuid-sandbox'],
})

// get instance of the automatically opened page
const page = (await browserInstance.pages())[0];

// capture trace messages
page.on('console', function (message) {
    if (message.type() === 'trace') {
        let stacktrace = message.stackTrace();
        console.log(stacktrace);
    }
}
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to use ```console.trace()``` to collect call traces in Javascript using puppeteer. 

Given the following page:
```
function f1() {
    console.trace();

}
eval('f1();');

```

### Expectation

From inside the chromium console, I get: 

```
script.js:2 console.trace
eval	@	VM280:1
(anonymous)	@	script.js:4
```
This is perfect, as it represents the correct sequence of call locations with also perfect references to the line in the script. 

### Reality

However,  when I use puppeteer to read the browser's messages I get incoherent results.  In particular, the indexes corresponding to call locations happening inside the ```eval()``` are wrong. 
For example, with the code above, I get that 'f1();' is at line 29337 and column 25. 

```
{"url":"","lineNumber":29337,"columnNumber":25}
```

### Puppeteer version

21.4.0

### Node version

18.18.2

### Package manager

npm

### Package manager version

10.2.1

### Operating system

macOS

**Comment by OrKoN** [comment]
@GianlucaDeStefano please provide a complete script that includes a test page/console.trace script

**Comment by GianlucaDeStefano** [comment]
I have just found out that the issue was caused by a bug in a component of mine.
