### ISSUE TITLE
[Bug]: waitForNetworkIdle timeout due to missing response

### ISSUE THREAD

**Issue by QA-ler** [puppeteer/puppeteer#11235]
### Minimal, reproducible example

```TypeScript
Was not able to reproduce this with minimal example, but hope you can help me anyway.
```

### Error string

Timeout exceeded while waiting for event

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I have a test that uses the waitForNetworkIdle function, but some specific requests are sometimes treated as still running even though they are already done.
```js
await page.waitForNetworkIdle({idleTime: 100, timeout: 120000});
```
![image](https://github.com/puppeteer/puppeteer/assets/121550022/a69d27cd-4e06-45e4-b147-0a1027ac4a22)
Here I added some additional code to debug and as you see the requests are already done.

To check which requests are still active I added a try catch to the waitForNetworkIdle function:
![image](https://github.com/puppeteer/puppeteer/assets/121550022/3e876ec3-decb-4f2b-98c4-005fa3dc126b)

And here you can see that the request in numRequestsInProgress function still has no response
![image](https://github.com/puppeteer/puppeteer/assets/121550022/7eee79cb-b68a-4e9c-9070-c226e3bf17e0)

The strange is that when listening on requestfinished(which shall also be used by puppeteer) you can see that the request already returned about 2 minutes before the timeout of waitForNetworkIdle function containing a response with ok status.

I'm not sure if this could be the reason but the requests this happens all have status code 204 (No content).

### Expectation

If request are done they do not block waitForNetworkIdle function

### Reality

Sometimes already done requests still block waitForNetworkIdle function

### Puppeteer version

20.3.0

### Node version

19.4.0

### Package manager

pnpm

### Package manager version

9.2.0

### Operating system

Windows

**Comment by OrKoN** [comment]
Without a reproducible example it's difficult to help. Perhaps there is a browser bug that misses CDP events for certain requests.

**Comment by SK-FComputer** [comment]
I might have a related issue @OrKoN 

After upgrading Puppeteer to latest version i have chrome processes hanging in my `htop` list.

The example is here:

```ts
export async function createPDF(
	html: string,
	htmlPath?: string,
	writePath?: PathLike
) {
	const browser = await puppeteer.launch({
		headless: 'new',
	});
	const page = await browser.newPage();

	if (htmlPath) {
		await page.goto(htmlPath, { waitUntil: 'networkidle0' });
	} else {
		await page.setContent(html, { waitUntil: 'networkidle0' });
	}

	const pdf = await page.pdf({
		format: 'a4',
		printBackground: true,
		displayHeaderFooter: true,
		headerTemplate: ' ',
		footerTemplate: `
			<div
				style="width: 100%; font-size: 9px; padding: 0px 5mm 0; color: #bbb; position: relative;"
			>
				<div style="position: absolute; right: 15mm; top: -10mm;">
					<span class="pageNumber"></span>/<span class="totalPages"></span>
				</div>
			</div>
		`,
		margin: { bottom: '20mm', left: '20mm', right: '20mm', top: 0 },
	});

	await page.close();
	await browser.close();
	if (writePath) {
		writeFileSync(writePath, pdf);
	}
	return pdf;
}
```

**Comment by SK-FComputer** [comment]
@ me if i need to open a new Bug report

**Comment by OrKoN** [comment]
@SK-FComputer please open a new issue and please provide a complete example that can be run independently

**Comment by QA-ler** [comment]
@OrKoN at the moment I'm not able to give a local reproducible project but I have a suggestion:
Would it be usefull to have another option for waitForNetworkIdle function which provides an array of URLs which puppeteer will not wait for? (or a domain and don't wait for all requests under this domain)
In our case, the blocking requests have no impact on the test or the end user and only capture metrics.
I know it's more of a workaround, but at the moment I have no other idea what I could do.

**Comment by QA-ler** [comment]
@OrKoN does this work together with waitForNetworkIdle function to affect the numRequestsInProgress/inFlightRequestsCount(as it is called in new versions) or is it more of a replacement?
