### ISSUE TITLE
Web site detects bot with my script, why?

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1124]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  0.13.0-alpha
* Platform / OS version: Ubuntu 17.04 64 bits
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://www.milanuncios.com/');
  await page.waitFor(3000);
  await page.screenshot({path: 'example.png'});
  //await browser.close();
})();
```
**What is the expected result?**
![example](https://user-images.githubusercontent.com/32681199/31858751-ede063f6-b6ff-11e7-99f0-d9701cbbb35d.png)

> Translated to English ...

 As you were browsing http://www.milanuncios.com/ something about your browser made us think you were a bot. There are a few reasons this might happen:

You're a power user moving through this website with super-human speed.
You've disabled JavaScript in your web browser.
A third-party browser plugin, such as Ghostery or NoScript, is preventing JavaScript from running. Additional information is available in this support article.

After completing the CAPTCHA below, you will immediately regain access to

**If I use a web browser (Mozilla, chrome ..), this problem does not occur. I do not understand what the problem is if the library puppeteer uses the engine (chrome) I am very surprised, you know that can be?**

**Comment by vsemozhetbyt** [comment]
I cannot reproduce the issue with 0.13.0-alpha on Windows 7 x64 for the first script run. Could it be that you have made many other operations on the site and they looked suspicious for them? Algorithms to detect automation may be elaborate and tricky.

**Comment by Garbee** [comment]
Headless mode does add "Headless" to the user agent string. Pretty easy sign there.

There are other methods of detecting headless though so it isn't like that is the only way. 

They clearly seem to be detecting repeated access traits from the same location and flagging it. This isn't something puppeteer can handle internally.

**Comment by ebidel** [comment]
Right. You could try spoofing the UA to see if that works, but there's likely more advanced detection algorithms behind the scenes. Sites that use captchas and detect scraping bots are put in place to prevent automation. Not much PPTR can do for these scenarios.

Related: https://github.com/GoogleChrome/puppeteer/issues/473
