### ISSUE TITLE
[Feature]: Rename Puppeteer to "Horseman"

### ISSUE THREAD

**Issue by jessicajaniuk** [puppeteer/puppeteer#11278]
### Feature description

For Halloween, consider renaming Puppeteer as a product to "Horseman" because obviously it's a headless test environment.  This is obviously a super serious feature request, not a joke, and shouldn't be closed immediately. ;)

Happy Halloween, Puppeteer...I mean....Horseman team. 🎃

**Comment by OrKoN** [comment]
Thanks, we will take to the OKR planning :) Happy Halloween!
