### ISSUE TITLE
[Bug]: crashes the GCP Cloud run pod

### ISSUE THREAD

**Issue by Dhrumil-Mobiuso** [puppeteer/puppeteer#11277]
### Minimal, reproducible example

```TypeScript
require("dotenv").config(); 
 
const utils = require("./utils"); 
 
const puppeteer = require("puppeteer"); 
 
const psList = require("ps-list"); 
 
const express = require("express"); 
 
const app = express(); 
 
const port = process.env.port; 
 
let urlsCount = 0; 
 
let urlsToBeProcessed = []; 
 
async function launchUrl(urlsAlloted) { 
  try { 
    while (urlsAlloted.length > 0) { 
      let url = urlsAlloted.shift(); 
 
      let waitTimeForAUrlInMs = process.env.waitTime; 
 
      let delayBetweenEachUrlLaunchInMs = process.env.delayBetweenLaunch; 
 
      utils.logInfo( 
        { url: url, urlsCount: urlsCount }, 
        "url processing" 
      ); 
 
      const browser = await puppeteer.launch({ 
        headless: process.env.chromeLaunchInHeadless === "true" ? "new" : false, 
        executablePath: process.env.chromePath, 
        //pipe: true, 
        args: [ 
          "--headless", 
          "--no-sandbox", 
          "--disable-gpu", 
          "--single-process", 
          "--no-zygote", 
        ], 
      }); 
 
      const page = await browser.newPage(); 
 
      await page.goto(url); 
 
      await utils.delay(waitTimeForAUrlInMs); 
 
      var osStats = await psList(); 
 
      for (let osStat of osStats) { 
        console.log(osStat); 
      } 
 
      await browser.close(); 
 
      urlsCount++; 
 
      var osStats = await psList(); 
 
      for (let osStat of osStats) { 
        console.log(osStat); 
      } 
 
      utils.logInfo({ urlsCount: urlsCount, url: url }, "processing done"); 
 
      await utils.delay(delayBetweenEachUrlLaunchInMs); 
    } 
  } catch (err) { 
    console.log(err); 
    utils.logError(err); 
  } finally { 
    utils.logInfo({ urlsCount: urlsCount }, "One set done"); 
 
    launchUrl([...urlsToBeProcessed]); 
  } 
} 
 
async function startPrerendering() { 
  try { 
    let urls = []; 
 
    for (let i = 0; i < 100; i++) { 
      urls.push("https://github.com"); 
    } 
 
    urlsToBeProcessed.push(...urls); 
 
    if (urls.length > 0 && urlsToBeProcessed.length > 0) { 
      launchUrl([...urlsToBeProcessed]); 
 
      app.get("/get", (req, res) => { 
        console.log("SERVER REQUEST"); 
 
        res.status(200).send({ numberOfUrls: urlsCount }); 
      }); 
 
      app.listen(port, () => { 
        console.log("SERVER READY"); 
      }); 
    } else { 
      utils.logError("URLS Not ready"); 
    } 
  } catch (err) { 
    utils.logError(err); 
  } 
} 
 
startPrerendering();


Docker file

FROM node:slim


ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD false

# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install gnupg wget -y && \
    wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install google-chrome-stable -y --no-install-recommends && \
    apt-get install dumb-init && \
    rm -rf /var/lib/apt/lists/*


# Create working directory
COPY . /usr/src/app/PupTest
WORKDIR /usr/src/app/PupTest


# Install NPM dependencies for function
RUN npm install



# Run app
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "index.js"]
EXPOSE 4000
```

### Error string

Uncaught signal: 13, pid=23, tid=23 fault_addr=0.  Uncaught signal: 13, pid=21, tid=21 fault_addr=0.    Navigation error and requesting main frame too early

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I was trying to take screenshots of thousands of urls put in array, to do this I used to launch one chrome instance with multiple tabs and launch urls on each tab and take screenshots.

### Reality

In reality when deployed code found out that the pod crashes after 30 mins or so (GCP CloudRun 4Gb, 2 core and max autoscaling 1 instance) .Then tried launching url on single tab and closing tab after each url processing, Then finally tried closing browser after each url, none of them works and the pod still crashes.
On investigation I found out the browser itself dies.
Steps taken to investigate: 
1. Tried different Docker images, such as the official Puppeteer image and the Browserless image. 
2. Tried putting different flags, such as --single-process, --no-zygote, and --disable-software-rasterizer. 
3. Tried setting pipe: true. 
4. Tried shutting down the browser and page after every N URLs. 
5. Tried shutting down the browser after every URL launch. 
6. Tried keeping the Chrome browser switched on and not using any Puppeteer functions. 
7. Added a process log to the process and found that the PID in the error is of Chrome Crashpad. 
8. Tried adding dumb-init. In this case, the errors seem to go away, but Chrome still dies, and so does the Node process. 
9. Tried Puppeteer cluster. 

Tried all the permutations and combination of above thing

### Puppeteer version

21.4.1

### Node version

20.9.0

### Package manager

npm

### Package manager version

9.8.0

### Operating system

Linux

**Comment by OrKoN** [comment]
I don't think we will be able to help you with the troubleshooting of a cloud deployment. Use the dumpio: true flag to see errors from the browser process, make sure memory and disk space is sufficient and check out some other advice at https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux. Also make sure you close the browser if any errors happen. Are you able to reproduce the issue locally? It would help if you provide a minimal reproducible example.

**Comment by Dhrumil-Mobiuso** [comment]
Thank you for responding quickly, I tried dumpio true Any idea on what could be the issue been stuck here for days

Logs:

Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
 Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Could not bind NETLINK socket: Permission denied (13)
ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
WARNING:audio_manager_linux.cc(53)] Falling back to ALSA for audio output. PulseAudio is not available or could not be initialized.
WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
DevTools listening on ws://127.0.0.1:21247/devtools/browser/5546d0e9-fb70-4d03-9440-e6d3a524827d

**Comment by OrKoN** [comment]
The log does not look like it captures the crash, does it? At least a few links are problematic: 1) you need to start dbus in your image 2) some permission issues Did you make sure that the user that runs Puppeteer has the correct permissions?

**Comment by vinaymavi** [comment]
@OrKoN  are you able to find out the work around of this problem?
