### ISSUE TITLE
Screenshot unit tests that set a viewport cannot capture an outside area without the `fullPage` option

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#11288]
There are two screenshot unit tests that currently fail with Firefox via WebDriver-BiDi:

* Screenshots Page.screenshot should get screenshot bigger than the viewport
* Screenshots ElementHandle.screenshot should capture full element when larger than viewport

Both tests set a smaller viewport and then try to capture a screenshot that is larger. The expected result is taking this area into account which is outside of the viewport and that is invalid without the `fullPage` option. If that option is not set the intersection between the clip rectangle and the viewport needs to be returned and that is what Firefox correctly does but causes the tests to fail.

@OrKoN can someone from the Puppeteer team please have a look? Thanks

PS: As it looks like we also miss a wdspec tests for that scenario. Maybe @jrandolf can add it with his fullscreen and format PR?

**Comment by jrandolf** [comment]
Considering document screenshots were merged, I think we should settle this in WPT before the issue here. We want to use "document" instead of the viewport expansion hack.

**Comment by whimboo** [comment]
The `origin` screenshots that were referenced above are most likely https://github.com/web-platform-tests/wpt/pull/42804, and this PR will be merged soon.

**Comment by whimboo** [comment]
> The `origin` screenshots that were referenced above are most likely [web-platform-tests/wpt#42804](https://github.com/web-platform-tests/wpt/pull/42804), and this PR will be merged soon.

@OrKoN the above mentioned PR got merged yesterday. As such I assume that the expansion hack in Puppeteer can be removed now?

**Comment by jrandolf** [comment]
Twas removed!
