### ISSUE TITLE
'Network.setRequestInterceptionEnabled' wasn't found undefined

### ISSUE THREAD

**Issue by und3fined** [puppeteer/puppeteer#1129]
Hi there,

`Network.setRequestInterceptionEnabled` is removed in Chrome DevTools Protocol

I'm tested in `HeadlessChrome/64.0.3248.0`

Please update puppeteer for new CDP, Thanks.

**How to fix?**

- Edit `puppeteer/lib/NetworkManager.js`
- Change `Network.setRequestInterceptionEnabled` to `Network.setRequestInterception`

```javascript
async _updateProtocolRequestInterception() {
    const enabled = this._userRequestInterceptionEnabled || !!this._credentials;
    if (enabled === this._protocolRequestInterceptionEnabled) return;
    this._protocolRequestInterceptionEnabled = enabled;
    await this._client.send("Network.setRequestInterception", {
        patterns: [{ urlPattern: '*' }]
    });
}
```

**Comment by ngyikp** [comment]
Seems to be addressed at https://github.com/GoogleChrome/puppeteer/pull/1153
