### ISSUE TITLE
[Bug]: Insecure URL is automatically upgraded to Secure when using headless: new

### ISSUE THREAD

**Issue by robjmills** [puppeteer/puppeteer#11297]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {

    const launchOptions = {
        headless: 'old',
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--single-process', '--disable-gpu'],
    };

    const browser = await puppeteer.launch(launchOptions);
    const page = await browser.newPage();

    const url = 'http://www.httpvshttps.com';
    console.log("goto URL: ", url);
    await page.goto(url);
    let currentURL = page.url()
    console.log("current URL: ", currentURL);

    await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I have a test which loads an insecure page on http://domain.com, with insecure assets over http://assets.domain.com - when I set `headless` to `new` the request is upgraded to https://domain.com which then breaks the page entirely, as the assets continue to load from their insecure domain. 

Using my example above the output for `headless: 'new'` is 

```
goto URL:  http://www.httpvshttps.com
current URL:  https://www.httpvshttps.com/
```

when I set `headless: 'old'` (or `headless: true`)

```
goto URL:  http://www.httpvshttps.com
current URL:  http://www.httpvshttps.com/
```

### Expectation

Not automatically upgrade the insecure request

### Reality

It switches the request from http://domain.com to https://domain.com

### Puppeteer version

21.4.1

### Node version

18.18.0

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Linux

**Comment by jrandolf** [comment]
Indeed, new headless is upgrading the URL. Could you clarify what you mean by

> I set headless to new the request is upgraded to https://domain.com/ which then breaks the page entirely, as the assets continue to load from their insecure domain.

Is this for a custom domain? Or for http://www.httpvshttps.com? The latter works fine with the upgrade.

**Comment by robjmills** [comment]
@jrandolf thanks for the reply. You can ignore domain.com really, that was just a placehold/example.

So with http://www.httpvshttps.com/ you can see that setting `headless: 'new'` causes the loading of https://www.httpvshttps.com/ though, and the other headless options don't.

Is this a bug or a feature? if it's a feature, then how can it be disabled?

**Comment by robjmills** [comment]
@jrandolf in case it's unclear, there's no redirection on the web server for http://www.httpvshttps.com/ which is why I chose that site. Going to that URL in Puppeteer, I'd expect the URL to be unchanged, but instead it's changed to https://www.httpvshttps.com/

**Comment by OrKoN** [comment]
This is working as expected as it matches the behaviour for the headful browser. See https://blog.chromium.org/2023/08/towards-https-by-default.html
