### ISSUE TITLE
[Feature]: When i host the nodjs server in digital ocean getting error

### ISSUE THREAD

**Issue by 1990minds** [puppeteer/puppeteer#11302]
### Feature description

const fs = require("fs");
const path = require("path");
const Student = require("../model/student");
const OnetoFourth = require("../model/onetofourth");
const Cosholastic14 = require("../model/coscholastic1to4");
const moment = require("moment");
const puppeteer = require("puppeteer");

exports.readHTML = async (req, res) => {
  try {
    const { studentid, term } = req.body;

    // Find the student by ID
    const student = await Student.findById(studentid)
      .populate("joining_details.class")
      .populate("joining_details.section")
      .exec();

    if (!student) {
      return res.status(404).json({ message: "Student not found" });
    }

    // Use the student's ID to find the associated "coshoolstaic1to4" object
    const cosholastic1to4 = await Cosholastic14.findOne({
      student: student._id,
    });

    if (!cosholastic1to4) {
      return res
        .status(404)
        .json({ message: "Coshoolstaic data not found for this student" });
    }

    // Use the student's ID to find the associated "one to fourth" object
    const onetoFourth = await OnetoFourth.findOne({ student: student._id });

    if (!onetoFourth) {
      return res
        .status(404)
        .json({ message: "One to fourth data not found for this student" });
    }

    // Load your HTML file
    const htmlFilePath = path.join(__dirname, "../../views/index.html");
    const htmlContent = fs.readFileSync(htmlFilePath, "utf8");

    // Create a Puppeteer browser instance
    const browser = await puppeteer.launch({
      headless: "new", 
      protocolTimeout: 10000,
      args: ['--no-sandbox'],
      userDataDir: '/workspace/.cache/puppeteer', // Set headless to false to see the browser
  
    });

    // Create a new page
    const page = await browser.newPage();

    // Set the HTML content of the page
    await page.setContent(htmlContent);

    // Define the PDF file path
    const pdfFilePath = path.join(__dirname, "../../pdf_output/output.pdf");

    // Generate the PDF file
    await page.pdf({ path: pdfFilePath, format: "A4" });

    // Close the browser
    await browser.close();

    console.log("PDF saved at:", pdfFilePath);

    // Send the generated PDF or any other response as needed
    res.status(200).json({ message: "PDF generated successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Server error" });
  }
};

exports.fetchTempletPdf = async (req, res) => {
  try {
    res.sendFile(path.join(__dirname, "../../pdf_output/output.pdf"));
  } catch (error) {
    console.log(error);
    res.status(401).json({ msg: "Something went wrong..!" });
  }
};

Above is the puppeteer controller file in the local dev server  i am able to download the pdf but in live i am getting 
[sans-server-new] [2023-11-03 12:44:15] Error: Could not find Chrome (ver. 117.0.5938.149). This can occur if either
[sans-server-new] [2023-11-03 12:44:15]  1. you did not perform an installation before running the script (e.g. `npm install`) or
[sans-server-new] [2023-11-03 12:44:15]  2. your cache path is incorrectly configured (which is: /workspace/.cache/puppeteer).
[sans-server-new] [2023-11-03 12:44:15] For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
[sans-server-new] [2023-11-03 12:44:15]     at ChromeLauncher.resolveExecutablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:298:27)
[sans-server-new] [2023-11-03 12:44:15]     at ChromeLauncher.executablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:191:25)
[sans-server-new] [2023-11-03 12:44:15]     at ChromeLauncher.computeLaunchArguments (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:98:37)
[sans-server-new] [2023-11-03 12:44:15]     at async ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
[sans-server-new] [2023-11-03 12:44:15]     at async exports.readHTML (/workspace/server/controller/puppeteerController.js:49:21)

**Comment by 1990minds** [comment]
Error is [sans-server-new] [2023-11-03 12:44:15] Error: Could not find Chrome (ver. 117.0.5938.149). This can occur if either
[sans-server-new] [2023-11-03 12:44:15]  1. you did not perform an installation before running the script (e.g. `npm install`) or
[sans-server-new] [2023-11-03 12:44:15]  2. your cache path is incorrectly configured (which is: /workspace/.cache/puppeteer).
[sans-server-new] [2023-11-03 12:44:15] For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
[sans-server-new] [2023-11-03 12:44:15]     at ChromeLauncher.resolveExecutablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:298:27)
[sans-server-new] [2023-11-03 12:44:15]     at ChromeLauncher.executablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:191:25)
[sans-server-new] [2023-11-03 12:44:15]     at ChromeLauncher.computeLaunchArguments (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:98:37)
[sans-server-new] [2023-11-03 12:44:15]     at async ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
[sans-server-new] [2023-11-03 12:44:15]     at async exports.readHTML (/workspace/server/controller/puppeteerController.js:49:21)

**Comment by OrKoN** [comment]
Make sure you download the browser binary on the cloud. Also see https://pptr.dev/troubleshooting for more tips. Closing as it is not a feature request.
