### ISSUE TITLE
[Bug]: "Restore page?" popup showing in headless "new" mode

### ISSUE THREAD

**Issue by Adrien5902** [puppeteer/puppeteer#11306]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
    console.log("starting pupeeteer")
    const browser = await puppeteer.launch({
        headless: "new", //only shows when headless is set to false or "new" and not when set to true
        //crash report only shows up when userDataDir is set
        userDataDir: "C:/Users/USERNAME/AppData/Local/Google/Chrome/User Data" 
    })

    const page = await browser.newPage()
    await page.goto("https://example.com")

    //close it with terminal rather than using browser.close() for it to crash
})()
```

### Error string

Restore pages? Chrome didn't shutdown correctly.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

headless "new" doesnt prevent the Restore pages? popup from showing up

note that the issue only happens when userDataDir is configured and when chrome has crashed before and not using browser.close() make it crash

### Expectation

nothing should show up in headless mode

### Reality

it shows up

### Puppeteer version

21.5.0

### Node version

v18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by OrKoN** [comment]
I was not able to reproduce on Windows. Could you share a screenshot of what you are seeing on screen?

**Comment by Adrien5902** [comment]
Sorry if the image is in french but as I said the "Restore pages?" show ups even thought puppeteer is in headless "new" mode, it only happens when userDataDir is set and if chrome as crashed before since crash reports are stored in user data.
This is just a display bug but you would assume nothing shows up when using headless mode.
For testing purposes if want to reproduce the bug you have to make chrome crash (you can do it by closing terminal while puppeteer is running) then start puppeteer again using headless "new".
![image_2023-11-06_222650137](https://github.com/puppeteer/puppeteer/assets/81705101/e8a57f15-1880-4de1-837a-2a7bc18b54e1)

**Comment by OrKoN** [comment]
@Adrien5902 which terminal app do you use?

**Comment by OrKoN** [comment]
I tried the command prompt on windows and also tried killing the processes via the task manager so far.

**Comment by Adrien5902** [comment]
> @Adrien5902 which terminal app do you use?

vs code's terminal which is windows powershell

**Comment by Adrien5902** [comment]
but it's not that important that it crashes the main thing is that the popup shows up in headless mode and my script is running in background of my personal computer and the popup shows up randomly on my screen

I guess I'll just use headless true instead of "new" for the moment even thought I get the big warning thing when doing so

**Comment by OrKoN** [comment]
@Adrien5902 I am not able to reproduce what you are seeing (also with the windows powershell in vscode)

**Comment by Adrien5902** [comment]
Maybe it could be related to my user settings. I've looked up on the internet and apparently there was an old experimental flag that could disable this popup.
Anyway I've also found that chrome stores if it crashed in the user preferences under `"C:/Users/USERNAME/AppData/Local/Google/Chrome/User Data/PROFILENAME/Preferences"` it is a json file with an exit_type key which is set to `"Crashed"` when last exit was a crash. So if you wanna test this out you could try setting this key and then start puppeteer in your user data dir with headless "new" and the popup should appear.

**Comment by OrKoN** [comment]
@Adrien5902 thanks for the tip but I still cannot reproduce. I see the dialog in headful (headless=false) but I don't see it for the new headless with the same steps. Could you confirm that you have the same version of Chrome as me?  I am running `C:\Users\USERNAME\.cache\puppeteer\chrome\win64-119.0.6045.105\chrome-win64\chrome.exe`

**Comment by Adrien5902** [comment]
i'm getting the issue when using either default chrome 119.0.6045.107 or puppeteer win64-119.0.6045.105

**Comment by OrKoN** [comment]
Filed https://crbug.com/1502181

**Comment by OrKoN** [comment]
The issue was addressed upstream.

**Comment by gratisCobalt** [comment]
dirty workaround would also be to just disable the popup with --hide-crash-restore-bubble arg
