### ISSUE TITLE
[Bug]: `boundingBox()` returns coordinates for elements with `visibility: hidden`

### ISSUE THREAD

**Issue by ProchaLu** [puppeteer/puppeteer#11309]
### Minimal, reproducible example

```TypeScript
import { launch } from 'puppeteer';

export async function isElementVisibleByBoundingBox(elementHandle) {
  return Boolean(await elementHandle.boundingBox());
}

export async function getVisibleElementByBoundingBox(page, selector) {
  const element = await page.$(selector);
  if (element && (await isElementVisibleByBoundingBox(element))) {
    return element;
  }
}

(async () => {
  const browser = await launch({ headless: false });
  const page = await browser.newPage();

  await page.goto('https://puppeteer-boundingbox-isvisible.vercel.app/');

  const elementWithBoundingBox = await getVisibleElementByBoundingBox(
    page,
    '[data-test-id="link-about"]',
  );

  if (elementWithBoundingBox) {
    console.log('[data-test-id="link-about"] is visible with boundingBox()');
  } else {
    console.log(
      '[data-test-id="link-about"] is not visible with boundingBox()',
    );
  }

  await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

The `boundingBox()` method should return `null` if an element is not visible, including if it has the CSS property `visibility: hidden`. This is stated in the [Puppeteer documentation](https://pptr.dev/api/puppeteer.elementhandle.boundingbox): 

> This method returns the bounding box of the element (relative to the main frame), or null if the element is not visible.

![Screenshot 2023-11-06 at 11 09 29](https://github.com/puppeteer/puppeteer/assets/80746311/98ebc42c-3227-48d6-857d-0cfdaa58ea4a)

Expected Puppeteer test result:
```
[data-test-id="link-about"] is not visible with boundingBox()
```

### Reality

The `boundingBox()` method returns the coordinates with the width and height of an element even if it has the CSS property `visibility: hidden`. This means that tests that use `boundingBox()` to check if an element is visible can fail even if the element is not actually visible on the page.

Actual Puppeteer test result:
```
[data-test-id="link-about"] is visible with boundingBox()
```

### Steps to reproduce:

1. Clone repo with `git clone https://github.com/ProchaLu/puppeteer-boundingbox-isvisible.git`
2. install the dependencies with `pnpm install`
3. run the test with `node util/test.mjs` 

If you want to test locally and make some changes, don't forget to change the URL in the `util/test.mjs` file.

### Puppeteer version

21.5.0

### Node version

v20.9.0

### Package manager

pnpm

### Package manager version

8.9.2

### Operating system

macOS

**Comment by ProchaLu** [comment]
Follow up issue to
- https://github.com/puppeteer/puppeteer/issues/7463

**Comment by ProchaLu** [comment]
### Workaround: 

As a workaround, I use `isVisible()` to check if the element is visible or not. 

```ts
export async function isElementVisibleByIsVisible(elementHandle) {
  return await elementHandle.isVisible();
}

export async function getVisibleElementByIsVisible(page, selector) {
  const element = await page.$(selector);
  if (element && (await isElementVisibleByIsVisible(element))) {
    return element;
  }
}
```

**Comment by ProchaLu** [comment]
### Tests with different CSS properties that hide elements

1. `display: none` 

```
[data-test-id="link-about"] is not visible with boundingBox()
[data-test-id="link-about"] is not visible with isVisible()
```

2. `opacity: 0`
```
[data-test-id="link-about"] is visible with boundingBox()
[data-test-id="link-about"] is visible with isVisible()
```

**Comment by Lightning00Blade** [comment]
Thank you for the thorough explanation and examples. 
I believe that the current Puppeteer implementation are correct as [visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility) is said to be `... CSS property shows or hides an element without changing the layout of a document.` which implies that it still affects the layout and has an observable `boundingBox`.

I think the documentation should be update to be more in line with `display: none` explanation [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/display#none).
