### ISSUE TITLE
[Bug]: When Launcing the headless: "new" concurrently and again and again it stops waiting for selector and returns 0 result.

### ISSUE THREAD

**Issue by sasujon13** [puppeteer/puppeteer#11312]
### Steps to reproduce

[Bug]: When Launcing the headless: "new" concurrently and again and again it stops waiting for selector and returns 0 result.

### Expected results

Should Scrape Result as usual.

### Actual results

NA

**Comment by Lightning00Blade** [comment]
Hello @sasujon13, from what I understand this is a Puppeteer issue. Can you open an new issue with the Puppeteer bug template and fill it - [Bug Template](https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%5BBug%5D%3A+). 
Please specify many browsers it starts before observing this issue.

Closing this now and waiting for the new issue.
