### ISSUE TITLE
[Bug]: Launch browser failed with headless: false

### ISSUE THREAD

**Issue by Ligengxin96** [puppeteer/puppeteer#11316]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-core';
 
this.target = await puppeteer.launch({
    channel: "chrome",
    executablePath,
    headless: false,
    ignoreHTTPSErrors: true,
    timeout: 30000,
    dumpio: false,
    pipe: true,
    userDataDir: config.system.coreCacheDirPath,
    waitForInitialPage: true,
    args: [
        "--single-process",
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-extensions",
        "--no-zygote",
        "--shm-size=5gb",
        "--hide-scrollbars",
        "--mute-audio",
        "--disable-timeouts-for-profiling",
        "--disable-dinosaur-easter-egg",
        "--disable-web-security",
        "--disable-ipc-flooding-protection",
        "--disable-background-networking",
        "--disable-backgrounding-occluded-windows",
        "--disable-background-timer-throttling",
        "--disable-renderer-backgrounding",
        "--disable-backing-store-limit",
        "--disable-component-update",
        "--intensive-wake-up-throttling-policy=0",
        "--disable-domain-reliability",
        "--disable-popup-blocking",
        "--disable-sync",
        "--disable-breakpad",
        "--no-pings",
        "--font-render-hinting=none",
        "--no-default-browser-check",
        "--enable-crash-reporter",
        "--block-new-web-contents",
        "--noerrdialogs",
        `--crash-dumps-dir=${config.system.tmpDirPath}/crashpad`,
        "--enable-leak-detection",
        "--use-angle=gl-egl",
        "--enable-unsafe-webgpu",
        "--ignore-gpu-blocklist",
        "--gpu-no-context-lost",
        "--enable-gpu-compositing",
        "--enable-gpu-rasterization",
        "--disable-gpu-driver-bug-workarounds",
        "--enable-native-gpu-memory-buffers",
        "--enable-accelerated-2d-canvas",
        "--enable-accelerated-jpeg-decoding",
        "--enable-accelerated-mjpeg-decode",
        "--enable-accelerated-video-decode",
        "--enable-zero-copy",
        "--enable-oop-rasterization",
        "--enable-gpu-memory-buffer-video-frames",
        "--enable-features=VaapiVideoDecoder,RawDraw,CanvasOopRasterization,PlatformHEVCDecoderSupport"
    ]
});
```

### Error string

system error: TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

launch browser with gui

### Reality

launch browser failed

### Puppeteer configuration file (if used)

```TypeScript
puppeteer.launch args: 
[
    "--single-process",
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-dev-shm-usage",
    "--disable-extensions",
    "--no-zygote",
    "--shm-size=5gb",
    "--hide-scrollbars",
    "--mute-audio",
    "--disable-timeouts-for-profiling",
    "--disable-dinosaur-easter-egg",
    "--disable-web-security",
    "--disable-ipc-flooding-protection",
    "--disable-background-networking",
    "--disable-backgrounding-occluded-windows",
    "--disable-background-timer-throttling",
    "--disable-renderer-backgrounding",
    "--disable-backing-store-limit",
    "--disable-component-update",
    "--intensive-wake-up-throttling-policy=0",
    "--disable-domain-reliability",
    "--disable-popup-blocking",
    "--disable-sync",
    "--disable-breakpad",
    "--no-pings",
    "--font-render-hinting=none",
    "--no-default-browser-check",
    "--enable-crash-reporter",
    "--block-new-web-contents",
    "--noerrdialogs",
    `--crash-dumps-dir=${config.system.tmpDirPath}/crashpad`,
    "--enable-leak-detection",
    "--use-angle=gl-egl",
    "--enable-unsafe-webgpu",
    "--ignore-gpu-blocklist",
    "--gpu-no-context-lost",
    "--enable-gpu-compositing",
    "--enable-gpu-rasterization",
    "--disable-gpu-driver-bug-workarounds",
    "--enable-native-gpu-memory-buffers",
    "--enable-accelerated-2d-canvas",
    "--enable-accelerated-jpeg-decoding",
    "--enable-accelerated-mjpeg-decode",
    "--enable-accelerated-video-decode",
    "--enable-zero-copy",
    "--enable-oop-rasterization",
    "--enable-gpu-memory-buffer-video-frames",
    "--enable-features=VaapiVideoDecoder,RawDraw,CanvasOopRasterization,PlatformHEVCDecoderSupport"
]
```

### Puppeteer version

21.5.0

### Node version

18.16.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by OrKoN** [comment]
What is the browser version that you use?

**Comment by Ligengxin96** [comment]
> What is the browser version that you use?

chrome version: HeadlessChrome/119.0.6045.105

**Comment by OrKoN** [comment]
@Ligengxin96 could you provide a standalone test script that has all parameters specified?

**Comment by Ligengxin96** [comment]
> @Ligengxin96 could you provide a standalone test script that has all parameters specified?

Sure, here is the [repo](https://github.com/Ligengxin96/puppeteer-test) that you can reproduction this issue
[error line](https://github.com/Ligengxin96/puppeteer-test/blob/main/core/renderer/Core.js#L66)

**Comment by qianqianhaiou** [comment]
> 您能否提供一个指定了所有参数的独立测试脚本？

I ran into the same problem, when I specified (userDataDir) and used headless: 'new', the first time puppeteer started it would execute successfully, and then I killed the process (chrome shut down improperly). The launch a second time also can appear (Protocol error (Target. SetDiscoverTargets) : Target closed). Oddly enough, this problem doesn't occur when I don't specify (userDataDir).

MyUserAgent: Mozilla/5.0 (Windows NT 10.0; Win64;  x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

![image](https://github.com/puppeteer/puppeteer/assets/53305864/03c4003a-3fce-4a0f-bcd9-5d5927acaaee)

**Comment by qianqianhaiou** [comment]
> > 您能否提供一个指定了所有参数的独立测试脚本？
> 
> 我遇到了同样的问题，当我指定 （userDataDir） 并使用 headless： 'new' 时，傀儡师第一次启动它会成功执行，然后我终止了进程（chrome 关闭不正确）。第二次启动也可能出现（协议错误（Target.SetDiscoverTargets） ：目标已关闭）。奇怪的是，当我不指定 （userDataDir） 时，不会发生此问题。
> 
> MyUserAgent：Mozilla/5.0 （Windows NT 10.0;Win64的;x64） AppleWebKit/537.36 （KHTML， like Gecko） Chrome/119.0.0.0 Safari/537.36
> 
> ![图像](https://user-images.githubusercontent.com/53305864/285378489-03c4003a-3fce-4a0f-bcd9-5d5927acaaee.png)

I guess it has something to do with the browser not closing correctly

**Comment by OrKoN** [comment]
> Oddly enough, this problem doesn't occur when I don't specify (userDataDir).

If the userDataDir is not specified, a fresh temporary one is created automatically. 
If this is the same issue, it sound a lot like https://bugs.chromium.org/p/chromium/issues/detail?id=1463328 and https://github.com/puppeteer/puppeteer/issues/10517 which should be fixed for the new headless in M119. What does the browser output if you add dumpio: true? 

But those fixes in general don't apply to the headful browser behavior. Incorrect shutdown may indeed cause some corruption to the user data dir. Would you mind opening a crbug.com about that?

**Comment by qianqianhaiou** [comment]
> > Oddly enough, this problem doesn't occur when I don't specify (userDataDir).
> 
> If the userDataDir is not specified, a fresh temporary one is created automatically. If this is the same issue, it sound a lot like https://bugs.chromium.org/p/chromium/issues/detail?id=1463328 and #10517 which should be fixed for the new headless in M119. What does the browser output if you add dumpio: true?
> 
> But those fixes in general don't apply to the headful browser behavior. Incorrect shutdown may indeed cause some corruption to the user data dir. Would you mind opening a crbug.com about that?

Thank you brother, I found a solution, this may be due to chrome closed incorrectly. You should type the Preferences file under User Data (userDataDir), change the exit_type parameter to "Normal", and then make the file read-only (make sure it doesn't affect you).

my "puppeteer-core" version is "^21.5.2"

It works for me

**Comment by Ligengxin96** [comment]
Thank you all for your efforts in finding the issue.
