### ISSUE TITLE
[Bug]: /node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:176

### ISSUE THREAD

**Issue by LonJinUp** [puppeteer/puppeteer#11329]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer')
const readline = require('readline')

const browser = await puppeteer.launch({ headless: true })
const page = await browser.newPage()
 await page.goto(url, { waitUntil: 'load' })
        try {
            await page.type(usernameSelector, username)
            await page.type(passwordSelector, password)
        } catch (error) {
            console.log(error)
        }
```

### Error string

nodeLogin/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:176         static {                ^  SyntaxError: Unexpected token '{'     at Object.compileFunction (node:vm:352:18)     at wrapSafe (node:internal/modules/cjs/loader:1031:15)     at Module._compile (node:internal/modules/cjs/loader:1065:27)     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)     at Module.load (node:internal/modules/cjs/loader:981:32)     at Function.Module._load (node:internal/modules/cjs/loader:822:12)     at Module.require (node:internal/modules/cjs/loader:1005:19)     at require (node:internal/modules/cjs/helpers:94:18)     at Object.<anonymous> (/nodeLogin/node_modules/puppeteer-core/lib/cjs/puppeteer/api/api.js:35:14)     at Module._compile (node:internal/modules/cjs/loader:1101:14)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

node: v16.8.0
puppeteer:21.4.1

### Expectation

I have this problem in the latest version and 21.4.1. How can I fix it?

### Reality

Can not operate

### Puppeteer version

21.4.1

### Node version

16.8.0

### Package manager

npm

### Package manager version

8.1.0

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
Hello @LonJinUp, could you please try updating to Node v16.13.2 or higher, and see if the issue is reproducible.

**Comment by bahadirarslan** [comment]
Hello, 
I am facing the same issue.

Puppeteer version: `21.10.0`
Node version: `v16.19.0`

Interestingly I don't have any problem with the same codebase and node version on my local machine but at my server I have problem. 

Do you have any suggestion?

**Comment by LonJinUp** [comment]
My node has been updated to version 16.8.0, and puppeteer can use 20.0.0.
















At 2024-02-21 04:42:38, "bahadir arslan" ***@***.***> wrote:

Hello,
I am facing the same issue.

Puppeteer version: 21.10.0
Node version: v16.19.0

Interestingly I don't have any problem with the same codebase and node version on my local machine but at my server I have problem.

Do you have any suggestion?

**Comment by Lightning00Blade** [comment]
@bahadirarslan You should verify that the Node Version of your server is over `16.13.2`, as versions prior to that don's support a feature Puppeteer is using ([Class static initialization blocks](https://github.com/tc39/proposal-class-static-block)).
Note: doing `node -v` does not always mean that the Node version shown there will be use expecially if you have an advance setup. You should check from the spawned process via [process.version](https://nodejs.org/api/process.html#processversion).

**Comment by Gagan-meena** [comment]
> @bahadirarslan You should verify that the Node Version of your server is over `16.13.2`, as versions prior to that don's support a feature Puppeteer is using ([Class static initialization blocks](https://github.com/tc39/proposal-class-static-block)). Note: doing `node -v` does not always mean that the Node version shown there will be use expecially if you have an advance setup. You should check from the spawned process via [process.version](https://nodejs.org/api/process.html#processversion).

i am using node version 20.11.0 and "puppeteer-core": "^22.1.0", but still getting this error
\node_modules\puppeteer-core\lib\cjs\puppeteer\api\ElementHandle.js:164
        static {
               ^

SyntaxError: Invalid or unexpected token

**Comment by bahadirarslan** [comment]
> > @bahadirarslan You should verify that the Node Version of your server is over `16.13.2`, as versions prior to that don's support a feature Puppeteer is using ([Class static initialization blocks](https://github.com/tc39/proposal-class-static-block)). Note: doing `node -v` does not always mean that the Node version shown there will be use expecially if you have an advance setup. You should check from the spawned process via [process.version](https://nodejs.org/api/process.html#processversion).
> 
> 
> 
> i am using node version 20.11.0 and "puppeteer-core": "^22.1.0", but still getting this error
> 
> \node_modules\puppeteer-core\lib\cjs\puppeteer\api\ElementHandle.js:164
> 
>         static {
> 
>                ^
> 
> 
> 
> SyntaxError: Invalid or unexpected token
> 
> 
> 
> 

I updated pm2 and it worked. I didn’t think pm2 update command needed after node version change.

**Comment by bahadirarslan** [comment]
Sorry I quoted from wrong person @Gagan-meena 

@Lightning00Blade my problem solved after pm2 update.

**Comment by Lightning00Blade** [comment]
@Gagan-meena I will repeat again just because you have installed Node 20 on your machine does not mean for sure that you use to run Puppeteer will use Node 20. Sadly without information about your setup is impossible to help.

**Comment by Gagan-meena** [comment]
> @Gagan-meena I will repeat again just because you have installed Node 20 on your machine does not mean for sure that you use to run Puppeteer will use Node 20. Sadly without information about your setup is impossible to help.

  "dependencies": {
    "@azure/storage-blob": "^12.11.0",
    "@faker-js/faker": "^8.4.1",
    "@sendgrid/mail": "^7.7.0",
    "aws-sdk": "^2.1555.0",
    "axios": "^0.27.2",
    "bcryptjs": "^2.4.3",
    "cheerio": "^1.0.0-rc.12",
    "cors": "^2.8.5",
    "cron": "^3.1.6",
    "croner": "^8.0.1",
    "cross-env": "^7.0.3",
    "crypto-js": "^4.2.0",
    "dotenv": "^16.0.1",
    "ec-key": "^0.0.4",
    "esm": "^3.2.25",
    "express": "^4.18.1",
    "express-device": "^0.4.2",
    "express-fileupload": "^1.4.0",
    "formidable": "^2.0.1",
    "get-video-duration": "^4.1.0",
    "into-stream": "^8.0.1",
    "ioredis": "^5.3.2",
    "joi": "^17.6.0",
    "jsdom": "^24.0.0",
    "jsonwebtoken": "^9.0.2",
    "jspdf": "^2.5.1",
    "jwks-rsa": "^3.1.0",
    "mongoose": "^6.3.3",
    "morgan": "^1.10.0",
    "multer": "^1.4.5-lts.1",
    "nanoid": "^3.3.7",
    "netlify-lambda": "^2.0.15",
    "node-fetch": "^2.6.7",
    "nodemailer": "^6.7.5",
    "nodemon": "^3.0.3",
    "pdf-creator-node": "^2.3.5",
    "pug": "^3.0.2",
    "puppeteer": "^22.2.0",
    "puppeteer-core": "^22.2.0",
    "sib-api-v3-sdk": "^8.5.0",
    "streamifier": "^0.1.1",
    "winston": "^3.8.1",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.6",
    "gulp": "^4.0.2",
    "gulp-clean": "^0.4.0",
    "gulp-cli": "^2.0.1",
    "gulp-replace": "^1.0.0",
    "gulp-run": "^1.7.1",
    "pack": "^2.2.0",
    "raw-loader": "^4.0.2",
    "web": "0.0.2",
    "webpack": "^5.90.3",
    "webpack-cli": "^5.1.4",
    "webpack-node-externals": "^3.0.0"
  }
  node v20.11.1
  
  code 
  import puppeteer from "puppeteer";

export const generatePdf = async (req, res) => {
  try {
    const { html } = req.body;
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    await page.setContent(html, { waitUntil: "domcontentloaded" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    // Set headers for PDF download
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=tournament.pdf");
    res.send(pdfBuffer);
  } catch (error) {
    console.error(error);
    res.status(500).json({
      success: false,
      message: "Failed to generate PDF",
    });
  }

};

**Comment by Gagan-meena** [comment]
> @Gagan-meena I will repeat again just because you have installed Node 20 on your machine does not mean for sure that you use to run Puppeteer will use Node 20. Sadly without information about your setup is impossible to help.

I am using the ESM package and I received an error while trying to run the server using "-r esm". Do you have any ideas on how to resolve this error while using ESM?

packeag = puppeteer v22.2.0

error  Error: Cannot find module 'puppeteer-core/internal/puppeteer-core.js'

**Comment by Lightning00Blade** [comment]
@Krishnaraj-shankar Please refer to this comment https://github.com/puppeteer/puppeteer/issues/11329#issuecomment-1956204942
Run the script you are trying to run and console log the [process.version](https://nodejs.org/api/process.html#processversion).

Our test already run on Node 20 without issues.

**Comment by chris-deng** [comment]
I am facing the same issue too.

Puppeteer version: 21.10.0
Node version: v16.19.0

I have the same issue on my local machhine with yarn start.

I have tried update node to v18.18.2, puppeteer to v22.0 ,  Still not working.

**Comment by rodrigosantosbh** [comment]
I did this steps below and now it's working:

nvm ls-remote
nvm install 20.12.2
nvm use 20.12.2

**Comment by Krishnaraj-shankar** [comment]
Sure will try

**Comment by Shashankcaptialsetu** [comment]
I am facing same issue 

I have check in node version 16.20.2, 16.20.0, 18.20.2 , 20.12.2 
and my puppeteer version is  "puppeteer": "^21.3.6",

 Ubuntu version  Ubuntu 20.04 (Focal)"
 
/home/projects/scf-api/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:167
2|scf-api  |         static {
2|scf-api  |                ^
2|scf-api  | SyntaxError: Unexpected token '{'
2|scf-api  |     at Object.compileFunction (node:vm:352:18)
2|scf-api  |     at wrapSafe (node:internal/modules/cjs/loader:1031:15)
2|scf-api  |     at Module._compile (node:internal/modules/cjs/loader:1065:27)
2|scf-api  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2|scf-api  |     at Module.load (node:internal/modules/cjs/loader:981:32)
2|scf-api  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2|scf-api  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
2|scf-api  |     at require (node:internal/modules/cjs/helpers:102:18)
2|scf-api  |     at Object.<anonymous> (/home/projects/scf-api/node_modules/puppeteer-core/src/api/api.ts:11:1)
2|scf-api  |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
2|scf-api  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2|scf-api  |     at Module.load (node:internal/modules/cjs/loader:981:32)
2|scf-api  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2|scf-api  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
2|scf-api  |     at require (node:internal/modules/cjs/helpers:102:18)
2|scf-api  |     at Object.<anonymous> (/home/projects/scf-api/node_modules/puppeteer-core/src/puppeteer-core.ts:9:1)

**Comment by Cruzor-Blade** [comment]
The issue still persists up to now
node v20.10.0
puppeteer  ^23.5.3

Very confusing and annoying... Hope a solution is found soon  : |

**Comment by LL0814** [comment]
The issue still persists up to now
node v18.17.0
puppeteer ^23.6.0

Very confusing and annoying... Hope a solution is found soon : |

**Comment by YCMitch** [comment]
Yeah I understand gaslighting everyone about their node versions, but I can also very much guarantee this is occurring on Node v20
