### ISSUE TITLE
[Feature]: Puppeteer.connect should be supported with BiDi protocol

### ISSUE THREAD

**Issue by sadym-chromium** [puppeteer/puppeteer#11335]
### Feature description

[`Puppeteer.connect`](https://github.com/puppeteer/puppeteer/blob/245f38234d16a201d4a601e3a20cc00c40af1806/packages/puppeteer-core/src/cdp/Puppeteer.ts#L147) should be supported via BiDi protocol.

When [`Puppeteer.connect`](https://github.com/puppeteer/puppeteer/blob/245f38234d16a201d4a601e3a20cc00c40af1806/packages/puppeteer-core/src/cdp/Puppeteer.ts#L147) is called with `{protocol: webDriverBiDi}`, a new BiDi connection should be established.

Actual behaviour: new CDP connection is established.

**Comment by sadym-chromium** [comment]
Add support `.connect`  for FF

**Comment by Lightning00Blade** [comment]
Closing as completed by #11451.
