### ISSUE TITLE
[Bug]: addStyleTag does not work when screenshot

### ISSUE THREAD

**Issue by vincent-tsui** [puppeteer/puppeteer#11333]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
    // headless: true,
    // args: ['--no-sandbox']
    headless: false,
    slowMo: 250, // slow down by 250ms
  });
  const page = await browser.newPage();
  await page.emulate(phone);
  await page.goto(url);

  await page.evaluate(() => {
    document.querySelectorAll('img').forEach((item, index) => {
      if(item.dataset.src) {
        item.src = item.dataset.src;
        item.classList.remove('img_loading')
      }
    })
  })
  await autoScroll(page);

  await page.addStyleTag({
    content: `
        #activity-name{display:none!important;}
      `
  });
  await page.screenshot({
    path: originLocalPath,
    fullPage: true
  });
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This project has 2 years ago, it use "puppeteer": "^13.5.2", everything worked.

Today, I want update, so I install puppeteer 21.5.0, and page.addStyleTag didn't worked now.

macos 13.4.1 , node v17.1.0

### Expectation

I expected get a screenshot image,without title.
'#activity-name' is title

### Reality

no css injected when screenshot.

when I set :
    headless: false,
    slowMo: 250,

I saw css injected, and the title had gone.
but when the code running to page.screenshot, the page resize,and the title is show.

So, I change page.screenshot() to page.pdf(),the pdf didn't show the title, it worked.
Just not worked with page.screenshot()

Any ideas? Thanks a lot

### Puppeteer version

21.5.0

### Node version

v17.1.0

### Package manager

npm

### Package manager version

8.1.2

### Operating system

macOS

**Comment by OrKoN** [comment]
Please provide a test URL/page.

**Comment by vincent-tsui** [comment]
```
const puppeteer = require('puppeteer');
const randomNum = parseInt(Math.random() * 10000000);
const pino = require('pino')
const logger = pino(pino.destination({
  dest: './info.log', // omit for stdout
  sync: false // Asynchronous logging
}))

let originLocalPath = __dirname + '/' + randomNum;

const phone = {
  'name': 'iPhone 6',
  'userAgent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1',
  'viewport': {
    'width': 400,
    'height': 667,
    'deviceScaleFactor': 2.25,
    'isMobile': true,
    'hasTouch': true,
    'isLandscape': false
  }
}
const args = process.argv.splice(2);
const url = decodeURIComponent(args[0]);

(async () => {
  try{
    await screenshootPage()
  } catch(e) {
    logger.info({msg: 'error', 'link': url})
    logger.info(e)
    process.exit(1)
  }
})();

async function screenshootPage(){
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox']
    // headless: false,
    // slowMo: 250, // slow down by 250ms
  });
  const page = await browser.newPage();
  await page.emulate(phone);
  await page.emulateMediaFeatures([{ name: 'prefers-color-scheme', value: 'light' }]);
  await page.goto(url);

  await page.evaluate(() => {
    document.querySelectorAll('img').forEach((item, index) => {
      if(item.dataset.src) {
        item.src = item.dataset.src;
        item.classList.remove('img_loading')
      }
    })
  })

  await page.addStyleTag({
    content: `
        #activity-name{display:none!important;}
      `
  });
  await page.pdf({
    path: originLocalPath + '.pdf',
  });
  await page.screenshot({
    path: originLocalPath + '.png',
    fullPage: true
  });
  await browser.close();
}
```

```
{
  "dependencies": {
    "pino": "^8.5.0",
    "puppeteer": "^21.5.0",
  }
}

```

`node index.js 'https://mp.weixin.qq.com/s/8qHjj6hM-Ws5iJEh3gCgNg'`

<img width="917" alt="image" src="https://github.com/puppeteer/puppeteer/assets/12118137/ab4de2bd-bc55-4079-8285-0f99092101bf">

Run this code, you will get a pdf file and a screen image.
As you can see this preview image, pdf without title, but image has title

**Comment by OrKoN** [comment]
What happens is that the screenshot affects the viewport and the page removes any custom style tags on resize.

**Comment by vincent-tsui** [comment]
I have no idea,lol
I tried to add `<style>#activity-name{display:none!important;}</style>` to that page in normal chrome devTool,and change viewport size to trigger resize event, but the title is still hidden.

Maybe chrome's bug? or why it flash and maybe resize when running page.screenshot()?
