### ISSUE TITLE
Puppeteer can't occur console event

### ISSUE THREAD

**Issue by CommanderXL** [puppeteer/puppeteer#1133]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: OS EI 10.11
* URLs (if applicable):

**What steps will reproduce the problem?**

Well. I know puppeteer can catch the uncaught exception through:

```javascript
   page.on('pageerror', () => {})
```

If the error was caught by `try/catch` like:
```javascript
    try {
       const a = 1
       console.log(a.b.c)
    } catch (e) {
       console.log(e)
    }
```
First, this situation will not emit the `pageerror` event. But I'm confused that puppeteer can't emit the `console` event even through there is `console.log` in the `catch` code block.

 
**What is the expected result?**

When the error was caught by `try/catch`, if there is `console.log/console.error` and other `console` method in the catch code block. It will emit the `page.on('console', () => {})` event.

**What happens instead?**

The `console.log` in the catch code block will emit the `page.on('console', () => {})`.

**Comment by vsemozhetbyt** [comment]
I can't reproduce with v0.13.0-alpha on Windows 7 x64:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    page.on('console', msg => { console.log(msg); });

    await page.goto('https://example.org/');

    await page.evaluate(() => {
      try { const a = 1; console.log(a.b.c); } catch (e) { console.log(e) }
    });

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```console
ConsoleMessage {
  type: 'log',
  text: 'JSHandle@error',
  args:
   [ JSHandle {
       _context: [Object],
       _client: [Object],
       _remoteObject: [Object],
       _disposed: false } ] }
```

**Comment by CommanderXL** [comment]
@vsemozhetbyt thanks for your answer. I will check it using `v0.13.0-alpha`. But how can I get the version.The npm hasn't this version.

**Comment by vsemozhetbyt** [comment]
`npm install https://github.com/GoogleChrome/puppeteer/` give you the latest version.

**Comment by CommanderXL** [comment]
@vsemozhetbyt Thanks for your answers. My puppeteer version is old and I update it.
