### ISSUE TITLE
[Bug]: 设置preferCSSPageSize: true, 生成pdf会多生成空白页

### ISSUE THREAD

**Issue by Zengwy-zmc** [puppeteer/puppeteer#11345]
### Minimal, reproducible example

```TypeScript
使用pupeteer ：
await page.goto(url, {timeout: 10000})
page.pdf({
      printBackground: false,
      preferCSSPageSize: true
    })
在网页设置@page {size:214mm 275mm;}会出现空白页
如果网页端设置@page {size:214mm 277mm;} 又不会多出空白页，会因为我的size而不同表现
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

按照设置的@page {size:214mm 275mm;}分页，不要生成空白页

### Reality

生成了空白页

### Puppeteer version

20.9.0

### Node version

16.9.1

### Package manager

yarn

### Package manager version

1.22.5

### Operating system

Linux

**Comment by bruceCzK** [comment]
建议检查一下 css，如果有 `page-break-after`, `page-break-before` 的话最好删了用 `page-break-inside: avoid`，另外用毫米作为单位的话可能换算也会有问题，改成 `px` 试试。
