### ISSUE TITLE
[Bug]: When running npm install, I encountered installation issues.

### ISSUE THREAD

**Issue by xiaopaning** [puppeteer/puppeteer#11349]
### Minimal, reproducible example

```TypeScript
// ...
npm timing build:link Completed in 6ms
npm info run puppeteer@21.5.1 postinstall node_modules/puppeteer node install.mjs
(##################) ⠏ reify:puppeteer-core: info run puppeteer@21.5.1 postinstall node_modules/puppeteer node install.mjs
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

How can I install it

### Reality

When running npm install, I encountered installation issues：

1. 'reify:puppeteer-core: info run puppeteer@21.5.1 postinstall node_modules/puppeteer node install.mjs'  This step took a long time, but it eventually succeeded.

### Puppeteer version

21.5.1

### Node version

v16.20.0

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Windows

**Comment by OrKoN** [comment]
I am unable to reproduce. If the browser download takes too long for you, use the env variable `PUPPETEER_SKIP_DOWNLOAD=true` before running `npm i` to skip the download and download the matching browser separately.
