### ISSUE TITLE
setRequestInterceptionEnabled is true but request.respond is undefined

### ISSUE THREAD

**Issue by ali-habibzadeh** [puppeteer/puppeteer#1134]
I have 
```
const page = await browser.newPage({context: 'default'});
await page.setRequestInterceptionEnabled(true);
```
However request.respond is always undefined
```
page.on('request', onRequestHandler);
const onRequestHandler = (request) => {
    console.log(request.respond); // is always undefined
    reqRejection.shouldReject(request, options) ? request.abort() : request.continue();
};
```

**Comment by vsemozhetbyt** [comment]
`request.respond` is a [function added recently](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#requestrespondresponse). It seems you need `request.response()`, but [it will be `null`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#requestresponse) before `request.continue()` and receiving the responce. Maybe you also need `response` event handler to get response (or `await page.goto()`).

**Comment by ali-habibzadeh** [comment]
I don't want get the response, i want to respond myself in certain cases so I don't need `response`

**Comment by vsemozhetbyt** [comment]
Sorry for the misunderstanding. Then you just need to be sure you use the proper version with `request.respond()` added.

**Comment by ali-habibzadeh** [comment]
The latest available on npm is 0.12.0, I am guessing .respond is part of 0.13.0?
Can you guys do a release schedule like angular so we can plan accordingly (if possible ofcourse)?

**Comment by vsemozhetbyt** [comment]
You can install the latest version by `npm install https://github.com/GoogleChrome/puppeteer/`.

This may probably be added to Readme.md.

**Comment by aslushnikov** [comment]
`.respond()` was added in 0.13.0-alpha and hasn't been released yet.

> Can you guys do a release schedule like angular so we can plan accordingly (if possible ofcourse)?

We'll get there eventually. The project is still very young :)

**Comment by xxwait** [comment]
I will bet your peppeteer version is lower than 0.13.0, cause I also have solve the issue today.
