### ISSUE TITLE
[Bug]: Screencast failing with "Cannot call write after a stream was destroyed"

### ISSUE THREAD

**Issue by tansanDOTeth** [puppeteer/puppeteer#11358]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const browser = await puppeteer.launch({ headless: "new" });
const page = await browser.newPage();
await page.setViewport({ width: 2000, height: 2000 });

const url = "https://ord-mirror.magiceden.dev/content/5aac901599912536b05c983818bf8406e2154780b61b73deebda225fd929219di0";
await page.goto(url);
await page.waitForSelector('use', { waitUntil: 'networkidle0' });
const recorder = await page.screencast({ path: `./videos/test.webm` });

await sleep(2_000);
await recorder.stop();
console.log('Done', url)

await browser.close();
process.exit(0)
```

### Error string

ffmpeg failed to write: Cannot call write after a stream was destroyed.

### Bug behavior

- [x] Flaky
- [ ] PDF

### Background

I have an M1 Mac and I installed ffmpeg via asdf

### Expectation

I expected it to generate a video

### Reality

It's just failing

### Puppeteer version

21.5.1

### Node version

20.5.1

### Package manager

npm

### Package manager version

9.8.0

### Operating system

macOS

**Comment by tansanDOTeth** [comment]
The "reproducible" code is the one I am using locally.

**Comment by OrKoN** [comment]
@jrandolf PTAL

**Comment by OrKoN** [comment]
Btw, I am unable to reproduce with 

```
ffmpeg version N-112324-g9240035c0e-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
```

**Comment by tansanDOTeth** [comment]
> Can you provide a stack trace?

Happy to, could you tell me how can I do that? this is all it shows me when it fails

**Comment by tansanDOTeth** [comment]
Here is my version if it helps:

```bash
$ ffmpeg -v
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/Users/douglasmak/.asdf/installs/ffmpeg/6.0
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
```

**Comment by tansanDOTeth** [comment]
> Btw, I am unable to reproduce with
> 
> ```
> ffmpeg version N-112324-g9240035c0e-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
>   built with Apple clang version 11.0.0 (clang-1100.0.33.17)
> ```

Here is my version if it helps:

```bash
$ ffmpeg -v
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/Users/userA/.asdf/installs/ffmpeg/6.0
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
```

**Comment by OrKoN** [comment]
@tansanDOTeth could you try if it works with a static build for MacOS https://evermeet.cx/ffmpeg/ ?

**Comment by khadeshyam** [comment]
you can use puppeteer-screen-recorder.[check this](https://screenshotone.com/blog/how-to-record-videos-with-puppeteer/)

**Comment by suyue-kanyun** [comment]
I also troubled by this problem, when I run simlar code like above, it works on my mac, but can not work on docker environment(Centos, 8.4.2105, Puppeteer 24.0.0, node 18.0.0, ffmpeg 3.4.2)

so I change to use puppeteer-screen-recorder, then it works well.
