### ISSUE TITLE
SSL Certificate error: ERR_CERT_AUTHORITY_INVALID on certain sites

### ISSUE THREAD

**Issue by sradu** [puppeteer/puppeteer#1137]
Running this script in a Debian environment returns:

(node:7395) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SSL Certificate error: ERR_CERT_AUTHORITY_INVALID

````
const puppeteer = require('puppeteer');

args = [];
args.push('--no-sandbox');
args.push('--disable-setuid-sandbox');

const takeSnapshot = async (page) => {
  await page.screenshot({ path: '/tmp/test.png' });
};

try {
  (async () => {
    browser = await puppeteer.launch({
      headless: true,
      args,
    });

    page = await browser.newPage();

    await page.goto('about:blank', { waitUntil: 'load' });

    await page.goto('https://www.ralphlauren.com/women-clothing-polo-shirts/skinny-fit-big-pony-polo-shirt/412481.html?cgid=women-clothing-polo-shirts&dwvar412481_colorname=Deep+Royal&webcat=women/tops/Polo+Shirts', { waitUntil: 'load' });

    await takeSnapshot(page);
  })();
} catch (err) {
  console.log(err);
}
````

There are other sites as well. Is it because of system certificates?

Thank you!

**Comment by aslushnikov** [comment]
Can't reproduce this on current tip-of-tree: 0.13.0-alpha. Could you please check if it works for you on tip-of-tree?

**Comment by sradu** [comment]
I'm afraid it's still happening with tip-of-tree.

**Comment by sjungwirth** [comment]
I'm running into same issue on another domain. The test script above fails for me as well.

**Comment by aslushnikov** [comment]
@sjungwirth can you share your script/domain?

**Comment by sradu** [comment]
It might be related to Comodo certificates.

**Comment by sjungwirth** [comment]
@aslushnikov I verified using the same script in the original post https://github.com/GoogleChrome/puppeteer/issues/1137#issue-267783452 against `www.frys.com`

**Comment by bondden** [comment]
Also confirm the same problem for [Let's Encrypt](https://letsencrypt.org/) certificate at itms.pro
It works without errors with headless:false

**Comment by hellosze** [comment]
Seeing errors for this site.  http://www.wmcactionnews5.com/ .  
Also used headless:false.

(node:71693) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SSL Certificate error: ERR_CERT_COMMON_NAME_INVALID
(node:71693) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C(node:71693) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Page crashed!

**Comment by sradu** [comment]
I stopped getting errors in the latest Chromium revision. Can anyone else on this issue please confirm? If all is well I'll close this issue.

**Comment by wenJanus** [comment]
I have the same problem. 

09:24:07.722 DEBUG selenium-nodejs.HomePage: navigate
[1120/092408.090:VERBOSE1:network_delegate.cc(31)] NetworkDelegate::NotifyBeforeURLRequest: https://localhost/home
[1120/092408.403:VERBOSE1:navigator_impl.cc(242)] Failed Provisional Load: https://localhost/home, error_code: -501, error_description: , showing_repost_interstitial: 0, frame_id: 1

The error page like:
![image](https://user-images.githubusercontent.com/25690258/32998843-63713fc4-cdd9-11e7-9603-1b9eda81bff1.png)

**Comment by aslushnikov** [comment]
@wenJanus it looks like you're using self-signed certificates on the localhost. Using [`ignoreHTTPErrors`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) puppeteer option should help to get rid of this message.

**Comment by azohra** [comment]
Can I ask why this issue was closed? I don't see any solution and can still reproduce the issue using the submitters attached code example. We are seeing the same issue with our websites. 

The `ignoreHTTPErrors` flag does not seem to effect the outcome. Is the behaviour by chance related to this Headless Chrome bug? https://bugs.chromium.org/p/chromium/issues/detail?id=721739

**Comment by elhigu** [comment]
@tk8817 @aslushnikov the option seems to be `ignoreHTTPSErrors` not `ignoreHTTPErrors`

**Comment by beerendlauwers** [comment]
@tk8817 We had success with setting `Security.setIgnoreCertificateErrors` (https://chromedevtools.github.io/devtools-protocol/tot/Security#method-setIgnoreCertificateErrors) on Chrome 65.0.3325.146. 

More context: https://gitlab.com/DMore/chrome-mink-driver/issues/57

**Comment by FullStackAlex** [comment]
I've got it working with:
`browser = await puppeteer.launch({ headless: false, slowMo: 250, ignoreHTTPSErrors: true });`

**Comment by bangkalog** [comment]
hi @Tech-Nomad I tried your code but this is what i get "HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure" did you experience this also?

**Comment by chrisburkejr** [comment]
@Tech-Nomad Does anyone know why this has to be slowMo set to 250. In the docs it says this is for slowing down puppeteer actions but doesn't look like it should be in production code. 
https://developers.google.com/web/tools/puppeteer/debugging

**Comment by apppli** [comment]
I used self-signed certificates on the localhost, 
`ignoreHTTPSErrors: true, `  > not working in my env
`args.push('--ignore-certificate-errors');` > seems good in my env
