### ISSUE TITLE
Add ability to extend selector mechanism

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#1138]
The current selector logic is restricted to CSS selectors, https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors.

It would be handy if there was a way to override the default selector mechanism, which is now using `document.querySelector`.

As an example of a use case, an equivalent of jQuery's [`:contains()`](https://api.jquery.com/contains-selector/) selector would be extremely useful. I am not suggesting that Puppeteer supported this out of the box, but if there was a mechanism to extend the selector engine, that would be great.

**Comment by aslushnikov** [comment]
Currently, the suggested approach for plugins is to write a bunch of helper methods and publish them as a peer dependency. For example, this particular scenario is implementable atop of current API.

We don't have any plans to improve our extensibility story unless there's a huge demand and the suggested approach proves to be insufficient. Closing this for now.
