### ISSUE TITLE
[Bug]: Error when closing brower after generate pdf

### ISSUE THREAD

**Issue by XHZ360** [puppeteer/puppeteer#11387]
### Minimal, reproducible example

```TypeScript
targetUrl = "https://www.amazon.com/"
const puppeteer = require('puppeteer');
(
  async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    console.log('inited');
    await page.goto(targetUrl);
    console.log('loaded page');
    await page.pdf({path: './test.pdf' });
    console.log('pdf saved');
    await browser.close();
  }
)(
)
```

### Error string

TargetCloseError: Protocol error (Runtime.runIfWaitingForDebugger): Target closed

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

Make it closed correctly without error

### Reality

1. Create page to load website.
2. Call page.pdf to generate pdf file. And the pdf file is generated correctly,
3. Call brower.close and error "TargetCloseError: Protocol error (Runtime.runIfWaitingForDebugger): Target closed"
IF ADD ` await page.waitForTimeout(4000) ` before call brower.close:
    Another error "TimeoutError: Frame was not swapped"
Other pages like "https://learn.microsoft.com/en-us/dotnet/framework" encounter the same problem.

### Puppeteer version

21.5.1

### Node version

16.16.0

### Package manager

npm

### Package manager version

9.6.6

### Operating system

Windows

**Comment by OrKoN** [comment]
I am unable to reproduce with multiple runs and both websites. Are there additional steps to reproduce it?

**Comment by XHZ360** [comment]
The problem didn't occur after disabling the breakpoint "caught error"
I don't know if there are any other issues, but it works correctly.
Is it throwing unnecessary errors?

**Comment by OrKoN** [comment]
How do you enable the breakpoint? The repro you shared has a clean user profile and does not use DevTools. In general, if you set breakpoints in a parallel session that might break Puppeteer as it does not allow Puppeteer to run scripts it needs.
