### ISSUE TITLE
iframe present in the DOM is not listed in page.frames()

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#1140]
Consider the following scenario:

```js
await page.waitForSelector('iframe[src*=tnspayments]');

const frames = await page.frames();

const paymentFrame = frames.find((frame) => {
  return frame.url().includes('tnspayments');
});

```

The selector `iframe[src*=tnspayments]` is resolved, but at this time `page.frames()` does not know of the frame.

This feels like a browser bug.

Adding an arbitrary wait time solves the issues.

```js
await page.waitForSelector('iframe[src*=tnspayments]');

await delay(500);

const frames = await page.frames();

const paymentFrame = frames.find((frame) => {
  return frame.url().includes('tnspayments');
});

```

I suppose a thorough implementation could wait for `frameattached`.

Bringing this up in case it is not a desired behaviour.

**Comment by fran0254** [comment]
I have the same problem 1+

**Comment by aslushnikov** [comment]
Can you guys please share the exact script and URL?

**Comment by gajus** [comment]
> Can you guys please share the exact script and URL?

It is the exact script and it works on any page that includes iframes.

**Comment by aslushnikov** [comment]
> It is the exact script and it works on any page that includes iframes.

It is not runnable. To simplify the life of project maintainers, please provide runnable scripts that include URLs so that we can easily reproduce your issue locally.

**Comment by gajus** [comment]
> It is not runnable. To simplify the life of project maintainers, please provide runnable scripts that include URLs so that we can easily reproduce your issue locally.

Aren't you paid to do this?

Others are contributing their time.

The above is more than enough to reproduce the issue that multiple people reported. Just closing this issue shows your complete indifference to this project.

**Comment by wanglam** [comment]
I have the same problem too..

**Comment by ebidel** [comment]
This script does not repro the issue described in the OP:

```js
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.goto('http://jsbin.com/');
await page.waitForSelector('iframe[src*=runner]');

const frames = page.frames();
const runnerFrame = frames.find(frame => frame.url().includes('runner'));

console.log(runnerFrame.url()); // runnerFrame is in page.frames()

await browser.close();
})();
```

This is why we've asked for a URL and full example to repro the issue. If someone can provide those details, that would be marvelous.

**Comment by achingbrain** [comment]
@ebidel I've put a demo repo together that illustrates the problem: https://github.com/achingbrain/puppeteer-frames

Just `npm install && npm start` and read the console output.

I think it might be something to do with iframes loading remote content because if you comment out [this line](https://github.com/achingbrain/puppeteer-frames/blob/master/html/index.html#L13) everything works as expected.

**Comment by aslushnikov** [comment]
@achingbrain thanks, that's due to the out-of-process iframes. I filed a separate issue: https://github.com/GoogleChrome/puppeteer/issues/2548

**Comment by JoseBarrios** [comment]
I ran into the same issue. I found a workaround/hack that might help folks here:

```Js

  /**                                                                                                    
   * Waits until the iframe is attached and then returns it to the caller                        
   *                                                                                                     
   * @access public
   * @param {object} page - The Puppeteer page API object 
   * @param {string} nameOrId - The name or id of the target iframe                                                                                                                                      
   * @returns {object} The Puppeteer iframe element                                                            
   */                                                                                                    
  async function iframeAttached(page, nameOrId) {                                                                  
    return new Promise(async resolve => {
      const pollingInterval = 1000;                                                                
      const poll = setInterval(async function waitForIFrameToLoad() {                                                                                                       
        const iFrame = page.frames().find(frame => frame.name() === nameOrId);                         
        if (iFrame) {                                                                                    
          clearInterval(poll);                                                                                  
          resolve(iFrame);                                                                               
        }                                                                                                                                                                         
      }, pollingInterval);                                                                                          
    });                                                                                                  
  } 
```

Now, you can get your iframes like this:

```Js
const iframe = await iframeAttached(page, 'YOUR_IFRAME_NAME_OR_ID');
// You can now use the iframe
iframe.doSomething(...);
```

**Comment by tokland** [comment]
This worked for me: https://github.com/puppeteer/puppeteer/issues/5123#issuecomment-559158303
