### ISSUE TITLE
[Bug]: pageNumber class does not take into account the number of pages already generated.

### ISSUE THREAD

**Issue by michaelboublil** [puppeteer/puppeteer#11400]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

(async () => {
   const arrayOfDocuments = ["<div>lala</div>", "<div>lili</div>", "<div>lolo</div>"]
   const browser = puppeteer.launch();
   for (let i = 0; i < arrayOfDocuments.length; i++) {
       const page = browser.newPage();
       await page.setContent(arrayOfDocuments[i]);
       const pdf = await page.pdf({
            path: "result.pdf",
            printBackground: true,
            format: 'A4',
            displayHeaderFooter: true,
            headerTemplate: "<div/>",
            footerTemplate: '<div style="text-align: right;width: 297mm;font-size: 15px;"><span style="margin-right: 1cm"><span class="pageNumber"></span></span></div>',
            margin: {
              bottom: '50px',
            },
          });
   }
}
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

Hello,

While using puppeteer I've noticed an issue that I've noticed no one reported.
In one same browser instance

`const browser = await puppeteer.launch();`

I'm generating multiple pages:

```
for (...) {
    const page = await browser.newPage();

    // Doing what I need to setup the content of my pdf page
    // ...
}
```
and at the end of each loop I'm adding the footer as such:
```
        const pdf = await page.pdf({
            path: "result.pdf",
            printBackground: true,
            format: 'A4',
            displayHeaderFooter: true,
            headerTemplate: "<div/>",
            footerTemplate: '<div style="text-align: right;width: 297mm;font-size: 15px;"><span style="margin-right: 1cm"><span class="pageNumber"></span></span></div>',
            margin: {
              bottom: '50px',
            },
          }) 
```

The problem is that, for every page generated with `newPage()`, the `pageNumber` class starts back at `1`, instead of taking into account the pages already generated in the same browser context.
Is this wanted behaviour ?

Thank you,

### Expectation

I expected `pageNumber` class to start at an update page number when generating more than one page.

### Reality

The pageNumber starts back at 1 for every page generated.

### Puppeteer version

21.5.2

### Node version

16.13.2

### Package manager

npm

### Package manager version

8.1.0

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
The word `page` is used in two different context. So the `newPage()` and `pageNumber` are not linked.
For the first one `newPage()` you are creating what essentially is a new Browser Tab.
While the second `pageNumber` is in the context of the PDF - as in which PDF page does the Footer/Header belongs to.

**Comment by MichaelBoublil** [comment]
Just to make sure I understand, you're telling me that there is no way to make the pages created with the browser context and the page number link together right ?

**Comment by Lightning00Blade** [comment]
No, it's not possible.
Note: your current code overrides the PDF file after each loop.

On theory a workaround you can have a single `newPage` and every page/website that you need to can load be an `iframe` inside that page. 
You may need to add the following CSS. 
```
iframe {
break-after: always;
}
```
But this will create a single PDF which may not be what you are after.
