### ISSUE TITLE
[Bug]: puppeteer.connect to vscode is hanging after upgrade puppeteer-core to 21.4.0 or later versions

### ISSUE THREAD

**Issue by gitforkenny** [puppeteer/puppeteer#11408]
### Minimal, reproducible example

```TypeScript
//Launch vscode "code --remote-debugging-port=9293"
const http = require("http");
const puppeteer = require("puppeteer-core");

async function test() {
  console.log('start');
  let data = await httpRequest( `http://127.0.0.1:9293/json/version`);
  console.log(`data: ${data}`);
  let jsonData = JSON.parse(data);
  console.log(jsonData);
  this._wsEndPoint = await jsonData.webSocketDebuggerUrl;
  console.log(this._wsEndPoint);

  var connectOpt = {
    browserWSEndpoint: this._wsEndPoint,
    defaultViewport: null,
    slowMo: 40,
  };

  try {
    console.log('start connect...');
    this.Browser = await puppeteer.connect(connectOpt);
    console.log('connected');

  } catch (error) {
    console.error(error);
  }

}

 test();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We are using puppeteer-core for our vscode extension testing.  We are using puppeteer-core 20.8.0 currently. We plan to upgrade to newer versions. 
However we get hanging if upgrade to 21.4.0 or later version.  There is no problem on 21.3.8. 

### Expectation

We expect puppeteer.connect() sucessfully.

### Reality

But it's hanging.

### Puppeteer version

21.5.2

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Windows

**Comment by gitforkenny** [comment]
I upgraded node.js to v20.9.0 but got same hanging problem.

**Comment by gitforkenny** [comment]
vscode version is 1.84.1

**Comment by OrKoN** [comment]
What Chromium version does vscode run? Note that Puppeteer works with the following browser versions https://pptr.dev/chromium-support I suspect that vscode uses something older and does not support Tab targets (see https://docs.google.com/document/d/14aeiC_zga2SS0OXJd6eIFj8N0o5LGwUpuqa4L8NKoR4/edit#heading=h.n1atlriavj6v)

**Comment by gitforkenny** [comment]
It's Chromium  114.0.5735.289.

**Comment by OrKoN** [comment]
I see, that version is not compatible with newer versions of Puppeteer. The last Puppeteer version tested with that Chromium version is 20.7.2.

**Comment by gitforkenny** [comment]
Thanks for your quick reponse. We'll follow the list for matched puppeteer version. 
https://pptr.dev/chromium-support
