### ISSUE TITLE
How can I open Internal Browsers URL 

### ISSUE THREAD

**Issue by yhoungdev** [puppeteer/puppeteer#11418]
I want to write a script that backups my Brave sidebar contents. 

  Brave stores the sidebar contents under sidebar_items which is under brave://prefs-internals 

   I want puppeteer to access brave://prefs-internals but it's throwing errors.

I think Puppeteer dosnt access Internal URLs like that because of Security purpose.

Please I need help accessing that.

   I even passed the --disable-web-security but same thing

**Comment by OrKoN** [comment]
This kind of question is better suited for StackOverflow (you can use the Puppeteer tag). Browsers do have additional restrictions about internal pages and those of Brave might be different of Chrome. Perhaps reach out to the Brave development forums.
