### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ems2oa** [puppeteer/puppeteer#11413]
Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
    tôi phải làm gì ?

**Comment by Raguggg** [comment]
### Solution

To resolve this issue and ensure compatibility with future versions of Puppeteer, you can opt in early to use the new Headless mode. Modify your Puppeteer script as follows:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: 'new', // Use the new headless mode
    // other options...
  });

  // Rest of your Puppeteer script

  await browser.close();
})();
