### ISSUE TITLE
[Bug]: 'Navigating frame was detached' when creating pdfs for complicated page

### ISSUE THREAD

**Issue by XiaoYuTW** [puppeteer/puppeteer#11429]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

createPDFs();

async function createPDFs() {

    const browser = await createBrowser();
    const page = await browser.newPage();

    for (let i = 0; i <= 5; i++ ) {
        console.log(`Start printing for No. ${i}`);

        await page.goto('https://de.yahoo.com/?p=us', {
            waitUntil: 'networkidle0',
          });
    
        console.log("Page loaded")
        await page.pdf({
            format: 'A4',
            path: `page-${i}.pdf`
        });
        console.log(`Finish printing for No. ${i}`);
    }

    console.log("Complete successfully");
}

async function createBrowser() {
    const viewportOptions = {
        args: [
            '--allow-running-insecure-content',
            '--autoplay-policy=user-gesture-required',
            '--disable-background-timer-throttling',
            '--disable-component-update',
            '--disable-dev-shm-usage',
            '--disable-domain-reliability',
            '--disable-features=AudioServiceOutOfProcess,IsolateOrigins,site-per-process',
            '--disable-ipc-flooding-protection',
            '--disable-print-preview',
            '--disable-setuid-sandbox',
            '--disable-site-isolation-trials',
            '--disable-speech-api',
            '--disable-web-security',
            '--disk-cache-size=33554432',
            '--enable-features=SharedArrayBuffer',
            '--hide-scrollbars',
            '--ignore-gpu-blocklist',
            '--in-process-gpu',
            '--mute-audio',
            '--no-default-browser-check',
            '--no-first-run',
            '--no-pings',
            '--no-sandbox',
            '--no-zygote',
            '--single-process',
            '--use-angle=swiftshader',
            '--use-gl=swiftshader',
            '--window-size=1920,1080',
        ],
        defaultViewport: null,
        headless: "new",
    }
    console.log("Start to create a browser");

    return await puppeteer.launch(viewportOptions);
}
```

### Error string

Error: Navigating frame was detached

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

We tried to print pdfs for multiple pages using **{"headless":"new"}** mode. But it will throw '**Error: Navigating frame was detached**', when it loads the second page after the first pdf is successfully generated. 

It does work when changing headless mode to **{ "headless": true}**, which used the old headless version.

In addition, we plan to use it in AWS lambda function, that's why there are those flags.

### Expectation

Generating multiple pdfs with {"headless":"new"} mode successfully.

### Reality

Can only generate one PDF, and throw error when calling page.goto("xxx") second time.

### Puppeteer version

21.5.2

### Node version

18.18.2

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Linux

**Comment by OrKoN** [comment]
I believe it's an indication that the browser process crashes. I will try to reproduce tomorrow.

**Comment by OrKoN** [comment]
It does not seem to happen with default arguments so probably one of the arguments is causing this.

**Comment by XiaoYuTW** [comment]
> I believe it's an indication that the browser process crashes. I will try to get more details tomorrow. If the dumpio option is turned, one could see `[1122/203136.458294:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)` which is an indication of a crash that shuts down the browser connection.

Yes, We can see the log with the error.

>It does not seem to happen with default arguments so probably one of the arguments is causing this.

It seems to be the '--single-process' argument. Removing the flag works locally, but fails on the lambda.

**Comment by OrKoN** [comment]
I see, thanks for the feedback. I am afraid you would need to file an issue for chromium (crbug.com). Would you mind opening an issue there? In general I am not sure how well Chromium supports the single process flag for the regular browser.
