### ISSUE TITLE
[Bug]: Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n

### ISSUE THREAD

**Issue by ALFAMAS** [puppeteer/puppeteer#11439]
### Minimal, reproducible example

```TypeScript
import express from "express";
import puppeteer from "puppeteer";
import path from "path";
import sanitize from "sanitize-filename";

const router = express.Router();

router.post("/create/:name", async (req, res) => {
  const name = sanitize(req.params.name);
  const html = req.body;

  if (!name || !html) {
    return res.status(400).json({ error: true, message: "Missing name or html" });
  }

  let browser;

  try {
    // browser = await puppeteer.launch({ headless: "new" });
    browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
    const page = await browser.newPage();

    await page.setContent(`${html}`);
    await page.emulateMediaType("screen");

    const pdfPath = path.join(req.app.locals.backendFolder, "pdf", `${name}.pdf`);
    await page.pdf({
      path: pdfPath,
      format: "A4",
      printBackground: true,
    });

    console.log(`PDF created: ${pdfPath}`);
    await browser.close();

    return res
      .status(200)
      .sendFile(pdfPath, {
        headers: {
          "Content-Type": "application/pdf",
        },
      });
  } catch (e) {
    console.error("Error creating PDF", e);
    if (browser) {
      await browser.close();
    }
    return res.status(500).json({ error: true, message: e.message });
  }
});

export default router;
```

### Error string

{     "error": true,     "message": "Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n" }

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

no background Story

### Expectation

its expected to work

### Reality

It worked in version 18.1.0

### Puppeteer version

v21.5.2

### Node version

v18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by OrKoN** [comment]
I am unable to reproduce: make sure to try the suggestions from the https://pptr.dev/troubleshooting page and make sure that the matching browser version is downloaded after the puppeteer update.

**Comment by ALFAMAS** [comment]
$ chromium-browser --product-version
119.0.6045.159

"puppeteer": "21.5.0",

still same error

Node version
v18.17.1

Package manager
npm

Package manager version
9.6.7

Operating system
Linux

**Comment by ALFAMAS** [comment]
Downgrading to Puppeteer v19.8.0

Fixed my Problem
