### ISSUE TITLE
[Bug]: `ng e2e` with puppeteer fails out of the box

### ISSUE THREAD

**Issue by pfeileon** [puppeteer/puppeteer#11433]
### Minimal, reproducible example

```TypeScript
> ng new test
# ...
> cd test
> ng e2e
# select puppeteer & jasmine
> ng e2e

Building tests 🛠️ ...

Error: spawn ./node_modules/.bin/tsc ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ./node_modules/.bin/tsc',
  path: './node_modules/.bin/tsc',
  spawnargs: [ '-p', 'e2e/tsconfig.json' ]
}

 🛑 Test failed! 🛑
Please look at the output above to determine the issue!
```

### Error string

Error: spawn ./node_modules/.bin/tsc ENOENT

### Expectation

No error. Schematic should configure the `ng e2e` successfully.

### Reality

`ng e2e` fails with the above mentioned error on a completely fresh angular project (angular-cli v17.0.3).

### Puppeteer version

21.5.2

### Node version

18.18.2

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Thanks for the report. Which version of the Angular CLI do you have (ng version)? I am unable to reproduce on Mac but I will try on Windows tomorrow.

**Comment by pfeileon** [comment]
> Thanks for the report. Which version of the Angular CLI do you have (ng version)? I am unable to reproduce on Mac but I will try on Windows tomorrow.

I've just tried it out today so: angular-cli v17.0.3

**Comment by OrKoN** [comment]
Able to reproduce on Windows. Thanks!
