### ISSUE TITLE
[Bug]: evaluateOnNewDocument changes not visible in extension content_script

### ISSUE THREAD

**Issue by pke** [puppeteer/puppeteer#11432]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      `--disable-extensions-except=${extensionPath}`,
      `--load-extension=${extensionPath}`,
    ]
  });
  const page = await browser.newPage();
  await page.evaluateOnNewDocument(() => {
    Object.defineProperty(window, "GM_xmlhttpRequest", {
      value: function({ method = "GET", url, onload }) {
        fetch(url, { method })
          .then(response => response.text())
          .then(responseText => onload({ responseText }))
        }
    })
  });
  await page.goto("some page that the content script is active on");
  await browser.close();
})();
```

### Error string

GM_xmlhttpRequest undefined

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to test my extension and it uses the `GM_xmlhttpRequest` function provided by GreaseMonkey compatible extensions. However, since I am only loading my own extension into the browser this function does not exist.
So I am trying to expose it with `Page.evaluateOnNewDocument` but the script does not see the new function. I guess thats because the extension script runs in a different context/sandbox.

An unfortunatly, using `fetch` inside my content script instead of `GM_xmlhttpRequest` is no alternative, because `fetch` is bound to CSP inside pages which `GM_xmlhttpRequest` can circumvent.

### Expectation

Expected `GM_xmlhttpRequest` to be available in the content script of the extension.

### Reality

`GM_xmlhttpRequest` is not available in the extensions content script.

### Puppeteer version

21.5.2

### Node version

20.0.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
This is expected because `page.evaluateOnNewDocument` only evaluates the script on new documents within the main frame process (in the main world). The extension content script would run in a different isolated world so won't have access to the exposed function.

**Comment by OrKoN** [comment]
I think this issue is similar to https://github.com/puppeteer/puppeteer/issues/1215

**Comment by pke** [comment]
Thanks for the quick response. 
I've tried `exposeFunction` too and then the function is available in the content script! Why is that?

I can't use it though, because the function im exposing would need a function as an argument, which is not serialisable.

**Comment by pirate** [comment]
bump, can this be re-opened? imo puppeteer should expose a way to run `evaluateOnNewDocument` on extension's `background.js` or `service_worker.js` contexts, otherwise there is no way to mock out extension behavior for end-to-end testing.
