### ISSUE TITLE
The problem of Chinese disorderly code

### ISSUE THREAD

**Issue by lisiyizu** [puppeteer/puppeteer#1143]
my puppeteer web deploy in heroku!
the test heroku  site:  https://urlforpdf.herokuapp.com/urltoimg?url=http://www.baidu.com
The problem of Chinese disorderly code:

![image](https://user-images.githubusercontent.com/12014252/31921831-fcb8a9c8-b836-11e7-9583-af1d96d29e92.png)

**Comment by hirokith** [comment]
You're missing fonts support on the system, try install Chinese fonts, for example in RedHat/CentOS:

```
yum install wqy-unibit-fonts.noarch wqy-zenhei-fonts.noarch -y
```

**Comment by Samlin901211** [comment]
Ubuntu:  try to install   sudo apt-get install fonts-wqy-zenhei

**Comment by lisiyizu** [comment]
the proplem is solved!  
heroku need the  buildpack：heroku-buildpack-converter-fonts
https://elements.heroku.com/buildpacks/debitoor/heroku-buildpack-converter-fonts

**Comment by broncha** [comment]
I have installed `ttf-wqy-microhei` `ttf-wqy-zenhei` `xfonts-wqy` but none of them is working!

**Comment by fly0o0** [comment]
Thanks dickeylth!

**Comment by Code1912** [comment]
@dickeylth  thx

**Comment by JasonBoy** [comment]
@dickeylth thx, fix the issue in centos7.3

**Comment by xgqfrms** [comment]
# CentOS 7 & Puppeteer

> test ok

```sh

# root
$ yum groupinstall "Chinese Support"
$ yum groupinstall "Font"

```

**Comment by jiahut** [comment]
By the way, I had packed a image at hub.docker

> docker pull jiahut/puppeteer

**Comment by ruenke** [comment]
> Ubuntu: try to install sudo apt-get install fonts-wqy-zenhei

same problem in debia system was solved by use this cmd!

**Comment by arika163** [comment]
same problem in alpine docker image. was solved by use the following cmd
`apk add wqy-zenhei --update-cache --repository http://nl.alpinelinux.org/alpine/edge/testing`

**Comment by 21paradox** [comment]
手动安装notosans字体的方法 （manual install notosans method） 

```sh
wget https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/08_NotoSansCJKsc.zip
unzip 08_NotoSansCJKsc.zip
mv NotoSansCJKsc-* ~/.local/share/fonts
fc-cache
fc-list
```

**Comment by andyliu1985** [comment]
render or Heroku can install fonts like this

wget https://github.com/notofonts/noto-cjk/raw/main/google-fonts/NotoSerifSC%5Bwght%5D.ttf && mkdir -p ~/.local/share/fonts/noto  && cp *.ttf ~/.local/share/fonts/noto && fc-cache -f -v
