### ISSUE TITLE
[Bug]: [PDF] CIRCLED DIGIT may not be of the same size

### ISSUE THREAD

**Issue by fumi23** [puppeteer/puppeteer#11446]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.setContent(`
おいしいもの<br>
<br>
①焼き鳥<br>
②寿司<br>
`)
await page.pdf({
  path: 'result.pdf',
  format: 'A4'
})
await page.close()
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

[U+2460](https://unicode-explorer.com/c/2460) and its family of characters should be displayed at the same size.

```
おいしいもの

①焼き鳥
②寿司
```

### Reality

Some of characters change the displayed size depending on the preceding and following characters.

<img width="298" alt="image" src="https://github.com/puppeteer/puppeteer/assets/16841915/ba90318a-05b6-4092-965d-1aee475148cf">

[result.pdf](https://github.com/puppeteer/puppeteer/files/13470220/result.pdf)

### Puppeteer version

21.5.2

### Node version

v16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Linux

**Comment by fumi23** [comment]
@Lightning00Blade Thanks, I'll try it.

**Comment by fumi23** [comment]
@Lightning00Blade 
I installed `Noto Sans JP` and specified `font-family`.
```
# fc-list | grep 'Noto Sans JP'
/usr/share/fonts/opentype/NotoSansJapanese/NotoSansJP-VariableFont_wght.ttf: Noto Sans JP,Noto Sans JP Thin
/usr/share/fonts/opentype/NotoSansJapanese/NotoSansJP-VariableFont_wght.ttf: Noto Sans JP,Noto Sans JP Thin:style=Thin,Regular
/usr/share/fonts/opentype/NotoSansJapanese/NotoSansJP-VariableFont_wght.ttf: Noto Sans JP,Noto Sans JP Thin:style=ExtraLight
/usr/share/fonts/opentype/NotoSansJapanese/NotoSansJP-VariableFont_wght.ttf: Noto Sans JP,Noto Sans JP Thin:style=Black
...
```
```diff
 import puppeteer from 'puppeteer'
 
 const browser = await puppeteer.launch()
 const page = await browser.newPage()
 await page.setContent(`
+<p style="font-family: 'Noto Sans JP', sans-serif;">
 おいしいもの<br>
 <br>
 ①焼き鳥<br>
 ②寿司<br>
+</p>
`)
 await page.pdf({
   path: 'result.pdf',
   format: 'A4'
 })
 await page.close()
 await browser.close()
```

Then I got the intended result! Thanks!
<img width="305" alt="image" src="https://github.com/puppeteer/puppeteer/assets/16841915/5cc7426d-bb58-463f-9456-049856a55ef6">
[result.pdf](https://github.com/puppeteer/puppeteer/files/13485790/result.pdf)

**Comment by fumi23** [comment]
Originally, we had Noto Sans (including Noto Sans CJK but not Noto Sans JP) installed in our environment, and `Noto Sans, san-serif` was specified as the font-family. The problem with the small size of `①` occurred even if `<p style="font-family: 'Noto Sans CJK', sans-serif;">` was specified. So this seems to be a problem with Noto Sans (which font is used for which character).

Thank you for your help!

**Comment by Lightning00Blade** [comment]
Something I notices after some debugging -> You are using two different Unicode groups.
So for one you use https://unicode-explorer.com/c/2460, the correct 2 is https://unicode-explorer.com/c/2461
While you are using https://unicode-explorer.com/c/2781.
I have updated the crbug with the information.

**Comment by fumi23** [comment]
> You are using two different Unicode groups.

No.
I understand that there are two different groups in Unicode.
I am using U+2460 and U+2461, not U+2781.

I have seen that the same U+2460 and U+2461 can look different depending on the characters before and after.
In the left image, both 1 and 2 are displayed in a larger size; in the right image, both 1 and 2 are displayed in a smaller size.
![image](https://github.com/puppeteer/puppeteer/assets/16841915/b3b0fb82-587f-437c-9e7c-b31b6c5a9d73)
（①やきとり ②すし; ①天ぷら ②寿司）

And it was a matter of which font was used for which character in HTML, not a PDF issue.
I checked **Rendered Fonts** in Chrome's DevTools and confirmed that 2 is displayed with _Noto Sans CJK JP Regular_ while 1 is displayed with _DejaVu Sans_.
![image](https://github.com/puppeteer/puppeteer/assets/16841915/44b4229d-707e-4efd-a430-19758cbf6992)

**Comment by fumi23** [comment]
And for my part, I am willing to have this Issue closed. It is clear to me that this is not a puppeteer issue.
Thank you very much.
