### ISSUE TITLE
[Bug]: Unexpected Page Property Modifications Upon Retrieval using browser.pages()

### ISSUE THREAD

**Issue by Mideen** [puppeteer/puppeteer#11440]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const wsEndpoint = 'YOUR_WS_ENDPOINT'; // Replace 'YOUR_WS_ENDPOINT' with your actual WebSocket endpoint

  const browser = await puppeteer.connect({ browserWSEndpoint: wsEndpoint });
  const pages = await browser.pages();

  console.log("List of pages:");
  pages.forEach((page, index) => {
    console.log(`Page ${index + 1}: ${page.url()}`);
    
    // Log current viewport size
    console.log(`Viewport size before any alteration: ${JSON.stringify(await page.viewport())}`);
  });

  await browser.disconnect();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Upon invoking browser.pages(), the properties of the existing pages in the connected browser should remain unchanged, including viewport size, context, or any other properties that might be inadvertently modified...The properties of the existing pages retrieved using browser.pages() should match their original states without any unintended modifications, specifically maintaining the correct viewport values.

### Reality

After calling browser.pages(), the viewport values of the retrieved pages seem to be altered. This poses challenges in maintaining the original state of the pages and affects the reliability of automation tasks

### Puppeteer configuration file (if used)

```TypeScript
Steps to Reproduce:

Connect to an existing Chrome browser instance using Puppeteer's WebSocket (browserWSEndpoint).
Retrieve pages using browser.pages().
Monitor and log the properties of the retrieved pages, especially focusing on viewport values.
```

### Puppeteer version

21.5.2

### Node version

v18.16.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by Mideen** [comment]
Same issue with 21.5.2 Puppeteer version

**Comment by OrKoN** [comment]
This is not how Puppeteer is expected to work. Puppeteer pages are even driven and update in realtime. If you want to serialize Page data, do so without invoking any async operations, e.g., before calling `await page.viewport()`.

**Comment by Mideen** [comment]
I appreciate your guidance regarding synchronous serialization to capture page data. Despite attempts to avoid asynchronous operations when serializing page properties using `target.page()`, I'm still encountering persistent alterations, not only in the viewport values. This continues to affect the reliability of data retrieval. Could you kindly provide further insights or suggestions on how to accurately capture and serialize page data without triggering real-time updates in Puppeteer? Thank you for your attention to this .


   const targets = browser.targets();

    const pageTargets = targets.filter(target => target.type() === 'page');
    const serializedPages = [];

    console.log("List of pages:");
    for (const target of pageTargets) {
        const page = await target.page();

        const serializedPage = {
            url: page.url(),
            viewport: page.viewport(), // Serialize viewport
        };
        serializedPages.push(serializedPage);
    }

    // Log serialized page data
    serializedPages.forEach((serializedPage, index) => {
        console.log(`Page ${index + 1}: ${serializedPage.url}`);
        console.log(`Serialized Viewport: ${JSON.stringify(serializedPage.viewport)}`);
    });
    
    
Already opened browser's viewport is 1920*1080 , but after i connected and executed this  i am getting 800*600.

**Comment by OrKoN** [comment]
800x600 is the default viewport Puppeteer sets for each page. Add `defaultViewport: null` to the launch command it leave it unchanged Some APIs like page.viewport() are asynchronous in nature so you cannot deal with them.

**Comment by OrKoN** [comment]
Sorry, I just looked up the viewport API definition again and it's not what I remember :) 

I just synchronously gets the current setting for the viewport not the actual viewport from the page.

You can get the actual viewport via script evaluation. For example

```
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({
    defaultViewport: {
      width: 900,
      height: 850,
    },
  });

  const testPage = await browser.newPage();
  await testPage.goto('https://example.com');

  const pages = await browser.pages();

  console.log("List of pages:");
  await Promise.all(pages.map(async (page, index) => {
    console.log(`Page ${index + 1}: ${page.url()}`);

    // Log current viewport size
    console.log(`Viewport size before any alteration: ${JSON.stringify(await page.evaluate(() => ({ width: visualViewport.width, height: visualViewport.height })))}`);
  }));

  browser.disconnect();
})();
```

**Comment by OrKoN** [comment]
It would also work for the connect scenario you are using but puppeteer.viewport() would return 800x600 because this is the default Puppeteer setting.

**Comment by Mideen** [comment]
"Is it possible to disable all the default properties that Puppeteer sets in an already opened browser?

**Comment by OrKoN** [comment]
> "Is it possible to disable all the default properties that Puppeteer sets in an already opened browser?

You should be able to do that for the viewport using the `defaultViewport: null` in puppeteer.connect. There is no general setting for that.

**Comment by Mideen** [comment]
I'm specifically referring to the viewport as an example, but Puppeteer might modify other properties as well. That's why I'm inquiring about the possibility of disabling all default settings that Puppeteer applies. I'm noticing alterations in properties like the viewport when working with an already-opened browser through Puppeteer, which could indicate changes in other default settings. So, I'm curious if there's a way to turn off or prevent Puppeteer from applying any default configurations when connecting to an existing browser. This way, I aim to maintain the original properties of the pages without any unintended modifications. Any insights or guidance on how to accomplish this would be immensely helpful. Thank you for your attention to this inquiry!

**Comment by OrKoN** [comment]
@Mideen I don't think there is anything except for the default viewport but, in general, it needs to be looked at argument by argument. There is no general flag for that.  I have opened https://github.com/puppeteer/puppeteer/compare/orkon/11440?expand=1 to clarify the behavior for the viewport parameter.

**Comment by younes-zeboudj** [comment]
It took quiet a lot of time to resolve this issue, thanks God it works fine now. Thank you for opening this issue. The solution is to pass `defaultViewport: true` to the browser connect function.
