### ISSUE TITLE
[Bug]: page.setViewport changes window.innerWidth instead of window.screen.width

### ISSUE THREAD

**Issue by maxkoretskyi** [puppeteer/puppeteer#11457]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
	headless: 'new',
	executablePath: 'google-chrome',
	args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
});

const page = await browser.newPage();

await page.setViewport({
  width: 1600,
  height: 1000,
  deviceScaleFactor: 2.5,
});

const el = await page.$$(gridStackPageSelector);
await el.screenshot({ path: filePath, type: 'jpeg', quality: 100 });
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I use headless chrome and puppeteer to take screenshots of DOM elements. 

### Expectation

Given the same numbers for `page.setViewport()` I would expect the screenshots to have the same quality regardless whether the puppeteer is run on my local machine or on the server/inside docker.

### Reality

When I take screenshots on my local machine on Windows with a 4k display the quality of screenshots is very good. When I take screenshots on server inside Docker's Ubuntu machine the quality is very bad. As the debugging info I outputted the following numbers from inside the browser started by puppeteer:

```
+-------------------------+-------+--------+
|         Param           | Local | Server |
+-------------------------+-------+--------+
| window.innerWidth       |  1600 |   1600 |
| window.innerHeight      |  1000 |   1000 |
| window.screen.width     |  1536 |    800 |
| window.screen.height    |   864 |    600 |
| window.devicePixelRatio |   2.5 |    2.5 |
+-------------------------+-------+--------+
```

As you can see, the numbers for `window.innerWidth` and `window.innerHeight` are the same for both. It's the other numbers `window.screen.width` and `window.screen.height` that are different and which I assume contribute to screenshot image quality. And it's those numbers I expected to set through `setViewport`. Instead, it's the `window.innerWidth` and `window.innerHeight` that are set through `setViewport` which produce very bad quality on server.

Is there any way to set `window.screen.width` and `window.screen.height`?

My goal is to produce the screenshots of the same quality as I get when I run puppeteer on my local PC with a display parameters: 3840 x 2160 and scale 250%. Increasing numbers in `setViewport: width = 4000, height = 2000` that affects `window.innerWidth` and `window.screen.height` produced very screenshot with everything scaled down (as if zoomed) with super tiny text. 

### Puppeteer version

21.5.2

### Node version

20.10.0

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Linux

**Comment by OrKoN** [comment]
I believe setViewport is not expected to affect the screen dimensions (it only affects the layout viewport of one page). I assume when the screen size is smaller than the viewport you would get a different screenshot . Did you try using a tool like xvfb-run to configure the screen size?

**Comment by OrKoN** [comment]
Perhaps also fixing the window-size via args might be helpful https://peter.sh/experiments/chromium-command-line-switches/#window-size

**Comment by maxkoretskyi** [comment]
@OrKoN thanks for your input! So what you're saying there's no way for me to configure screen size through puppeteer? If that's the case, could you please give me a bit more info on what to google/research related to your comment:

> Did you try using a tool like xvfb-run to configure the screen size?

As I see,  the command `xvfb-run` is related to the [a display server](https://en.wikipedia.org/wiki/Display_server), particularly [X11](https://en.wikipedia.org/wiki/X_Window_System_core_protocol). Is that something Chromium uses for headless rendering? Should I expect to have some config for X server inside my Ubuntu intallation?

This all is very new for me, sorry for basic questions.

**Comment by OrKoN** [comment]
For example,

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: 'new',
});

const page = await browser.newPage();

await page.setViewport({
  width: 3200,
  height: 2000,
  deviceScaleFactor: 2.5,
});

await page.setContent(`
  <div style="width: 3200px; height: 2000px; background-color: blue; font-size: 200px;">test</div>
`)

const el = await page.$('div');

console.log(await page.evaluate(() => {
  return {
    innerWidth: window.innerWidth,
    innerHeight: window.innerHeight,
    screenWidth: window.screen.width,
    screenHeight: window.screen.height,
  }
}))

await el.screenshot({ path: 'screenshotBig.jpg', type: 'jpeg', quality: 100 });

await browser.close();
```

I seem to be getting the right screenshot although my screen size is smaller than the viewport.

**Comment by maxkoretskyi** [comment]
> Btw, could you post the differences in screenshots using an entire test page (perhaps a dummy page using page.setContent). I wonder if the page content might be affecting the screenshot and not only the screen size.

Here you go. Output from my machine:

```
{
  innerWidth: 3200,
  innerHeight: 2000,
  screenWidth: 1536,
  screenHeight: 864
}
```

Output from server:

```
{
  innerWidth: 3200,
  innerHeight: 2000,
  screenWidth: 800,
  screenHeight: 600
}
```

First you can see a substantial size difference:

![size](https://github.com/puppeteer/puppeteer/assets/6124091/09e9c167-ea23-494b-8e7e-0a996414835d)

And here are the actual screenshots at 500% scale, there's a big difference in how they show:

![compare](https://github.com/puppeteer/puppeteer/assets/6124091/57514379-005d-4238-b7ff-dcc33c6a7d04)

**Comment by maxkoretskyi** [comment]
> Yeah, xvfb-run should allow you to set the screen size like xvfb-run --server-args="-screen 0 1024x768x24" node yourScript.js.

So is my understanding correct that Chromium doesn't directly user `xvfb-run`, because it's not installed in the docker yet the Chromium successfully runs in the headless mode. My guess would be that Chromium directly uses those libraries to construct something similar to `xvfb`, particularly `libxrender1`:

```
  - apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2
    libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
    libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0
    libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
    libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1
    libxss1 libxtst6
```

**Comment by OrKoN** [comment]
`xvfb-run` would set up a virtual screen environment for all subprocesses. I believe it's done via environmental variables. Those other dependencies are needed for Chrome but the screen size is the property of the environment. So did you try with xvfb-run?

**Comment by OrKoN** [comment]
Got a chance to test this one a Linux box, the xfvb-run does not seem to actually help but I still get the screenshot of the right dimensions. These are the images I get: on Linux the screen size is reported as 800x600 too.

[screenshotBig-Linux](https://github.com/puppeteer/puppeteer/assets/399150/efe86cce-d307-4ad0-a289-c9f4d01805a6)
[screenshotBig-Mac](https://github.com/puppeteer/puppeteer/assets/399150/a95188ed-d2a8-42d9-bc28-7cdb5e157acb)

Another thing that might help to change the screensize on Linux is `args: ['--ozone-override-screen-size=2000x2000']`. But I am not sure it is what causes the screenshot differences.

**Comment by maxkoretskyi** [comment]
@OrKoN thanks for your efforts and suggestions!

> but I still get the screenshot of the right dimensions.

for me both are reported in the log as having the same width and height, but different screen sizes. When I checked the details of images, here's what it shows:

![df](https://github.com/puppeteer/puppeteer/assets/6124091/3fad0b46-2c71-48c3-8bb3-71db3f41ced0)

The actual width and height matches the reported numbers for the regular 800x600 screen that was generated on server. For the screenshot taking on my local 4k machine, the actual width shows as 8000px, not 3200px. When I resized this image to 3200px wide, it showed increased dpi. So it seems that on 4k screen the density of pixels is about twice as much as on regular server screen.

**Comment by maxkoretskyi** [comment]
Hey @OrKoN ,
today I discovered a very weird thing. Old versions of Puppeteer, particularly from 18.1.0 and up to 19.0.0 produced very good quality of screenshots. I didn't use bundled version of Chrome, installed it separately. This is the version of the browser outputted from the script:

```
await browser.version(); // HeadlessChrome/119.0.6045.199
```

Do you maybe have any idea what could cause that? We'd like to use the most recent version of Puppeteer, so would be good to investigate this behavior.

Here are the screenshots with exactly the same setup but different Puppeteer versions that shows the difference in image size:

![same browser](https://github.com/puppeteer/puppeteer/assets/6124091/eb58055b-e830-458c-99c9-89b3d49c326f)

**Comment by OrKoN** [comment]
@maxkoretskyi could it be the same similar issue to https://github.com/puppeteer/puppeteer/issues/11498 ? there was some regression in the screenshot behavior https://github.com/puppeteer/puppeteer/issues/11498
