### ISSUE TITLE
[Bug]: CDP's websocket events inconsistent behavior

### ISSUE THREAD

**Issue by michae43** [puppeteer/puppeteer#11456]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({ headless: false });
const page = await browser.newPage();

const session = await page.target().createCDPSession();
await session.send('Network.enable');

session.on('Network.webSocketFrameReceived', ({requestId, timestamp, response}) => {
    console.log('Received:', requestId, timestamp, response.payloadData)
})

// Case 1: expected behavior, websocket frames are logged to the console
await page.goto('https://www.tradingview.com');

// Case 2: CDP events received in puppeteer but don't reach 'Network.webSocketFrameReceived' callback
// await page.goto('https://lolly-bet.com/en/sportsbook');

// Case 3: CDP events are not received in puppeteer
// await page.goto('https://finance.yahoo.com/');
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to retrieve websocket frames received in Puppeteer's browser using a CDP session.
Unfortunately, nothing is logged to the console.
While debugging using `DEBUG=puppeteer:protocol:* node script.js`, I noticed several cases:
- Case 1: expected behavior where websocket frames are printed to the console
- Case 2: websocket frames not reaching callback method written above but protocol's messages are received in puppeteer (running the script with `DEBUG=puppeteer:protocol:*` shows the frames in the DEBUG output but nothing to the console)
- Case 3: websocket frames not reaching callback method and not shown with DEBUG while
  Network.webSocketFrameReceived events are actually emmitted as shown in the
  browser's protocol monitor experimental feature

related issue: #9294 #3547 

### Expectation

Print websocket frames received in the browser from the server to the console for the three websites above.

### Reality

Websocket frames do not reach the Network.webSocketFrameReceived event method.

### Puppeteer version

21.5.2

### Node version

21.2.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Linux

**Comment by OrKoN** [comment]
You enable the events on the main target of the page only. Is there a chance that in the other cases the socket connection is done from an iframe (an out-of-process iframe in the case 2) and perhaps a worker in the case 3? You can enable the target id column in the network monitor and compare target ids for the websocket messages.

**Comment by OrKoN** [comment]
Something like this should cover targets that auto-attach to the page (might exclude some service workers):

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({ headless: false });
const page = await browser.newPage();

const session = await page.target().createCDPSession();

async function subscribe(session) {
  session.on('sessionattached', s => {
    console.log('subsession')
    subscribe(s);
  });
  session.send('Network.enable');
  session.on('Network.webSocketFrameReceived', ({ requestId, timestamp, response }) => {
    console.log('Received:', requestId, timestamp, response.payloadData)
  });
  session.send('Runtime.runIfWaitingForDebugger');
}

await session.send('Target.setAutoAttach', {
  autoAttach: true,
  flatten: true,
  waitForDebuggerOnStart: true,
});

subscribe(session);

await page.goto(...);
```

If there is still an issue with this method, please open a bug for CDP at crbug.com.

**Comment by michae43** [comment]
It seems that the issue was indeed with the target. The snippet you provided
fixed it.
Thank you for your time!

**Comment by arogonov** [comment]
@OrKoN I reckon you deserve a monument, mate. You saved my day, and that's no small feat. Cheers to you!
