### ISSUE TITLE
[Bug]: Frame detached error when calling `page.goto()` with Chrome ToT

### ISSUE THREAD

**Issue by adamraine** [puppeteer/puppeteer#11458]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
import {launch} from 'chrome-launcher';

// Launch Chrome 121.0.6155.0
const chrome = await launch({
  chromeFlags: ['--headless=new'],
});

// Needs to connect to an already open Chrome
const browser = await puppeteer.connect({
  browserURL: `http://127.0.0.1:${chrome.port}`,
})

const page = await browser.newPage();

await page.goto('http://localhost:10200/oopif-requests.html');

console.log(page.url());

await browser.close();
```

### Error string

Error: Navigating frame was detached

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This only seems to happen when puppeteer connects to an already open browser.

It also only happens on the latest Chrome ToT: 121.0.6155.0

HTML file used:

```html
<!DOCTYPE html>
<html>
  <body>
    <h1>Hello frames</h1>
    <iframe id="oopif" src="https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/" style="width: 100vw; height: 110vh;"></iframe>
  </body>
</html>
```

### Expectation

The script to run fine and print the page url

### Reality

Error is thrown on `page.goto()`

### Puppeteer version

21.5.2

### Node version

18.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
I am unable to reproduce on ToT. Any chance that it was caused by the browser crash (looks like that) and reverted in the meantime?
