### ISSUE TITLE
how do i accept chrome location dialog alert?

### ISSUE THREAD

**Issue by saselovejulie** [puppeteer/puppeteer#1146]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: win10 64
* URLs (if applicable): https://www.google.com/search?num=100&newwindow=1&dcr=0&source=hp&q=hotels&oq=hotels

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. when a website request a geo location, chrome will alert a dialog
2. i try to use this code to accept this dialog.
```
    page.on('dialog', async dialog => {
        console.log(dialog.message());
        await dialog.dismiss();
    });
```
3. but it failed, the event didn't trigger.
how could i capture this geo location dialog?

**What is the expected result?**
geo location will trigger the when chrome alert the dialog

**What happens instead?**
nothing happened

![1508822756](https://user-images.githubusercontent.com/13128637/31926217-cd30f24e-b8bf-11e7-9f2d-9656a1ccde3d.png)

**Comment by saselovejulie** [comment]
Electron support this function can solve this alert : 
ses.setPermissionRequestHandler(handler)
handler Function
webContents WebContents - WebContents requesting the permission.
permission String - Enum of ‘media’, ‘geolocation’, ‘notifications’, ‘midiSysex’, ‘pointerLock’, ‘fullscreen’, ‘openExternal’.
callback Function
permissionGranted Boolean - Allow or deny the permission
Sets the handler which can be used to respond to permission requests for the session. Calling callback(true) will allow the permission and callback(false) will reject it.
```
const {session} = require('electron')
session.fromPartition('some-partition').setPermissionRequestHandler((webContents, permission, callback) => {
  if (webContents.getURL() === 'some-host' && permission === 'notifications') {
    return callback(false) // denied.
  }

  callback(true)
})
```
is there any function we support like this?

**Comment by saselovejulie** [comment]
Maybe we can use a chromium-command-line  from this website 
https://peter.sh/experiments/chromium-command-line-switches/

**Comment by saselovejulie** [comment]
@ebidel @aslushnikov 
could you help me? thanks alot

**Comment by Garbee** [comment]
Duplicate of #846

**Comment by hirokith** [comment]
I've also encountered this problem, and I figured out a solution. You could launch puppeteer with customized `userDir` option, and when the permission dialog alerts, you check it manually, after that the choice will be saved to the `userDir/Preferences` file, and next time you run the code, the Chromium could use the saved preference in your customized `userDir`, and should no longer alert the permission dialog.

**Comment by saselovejulie** [comment]
@dickeylth thanks, i will have a tru

**Comment by aslushnikov** [comment]
Closing as dupe of #846.

**Comment by 0x11-dev** [comment]
You can permit geo location api via the new api introduced in v1.8.0. https://pptr.dev/#?product=Puppeteer&version=master&show=api-browsercontextoverridepermissionsorigin-permissions Y

**Comment by Joadison** [comment]
await page.evaluateOnNewDocument(function() {
  navigator.geolocation.getCurrentPosition = function (cb) {
    setTimeout(() => {
      cb({
        'coords': {
          accuracy: 21,
          altitude: null,
          altitudeAccuracy: null,
          heading: null,
          latitude: 23.129163,
          longitude: 113.264435,
          speed: null
        }
      })
    }, 1000)
  }
});
