### ISSUE TITLE
Flaky Test - `Error: Browser was not set-up in time!`

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11472]
Happens in the flaky manner: https://github.com/puppeteer/puppeteer/actions/runs/7046304099/job/19177866980?pr=11471#step:13:906

cc @jrandolf @Lightning00Blade

**Comment by Lightning00Blade** [comment]
That error is part of something else log show `TimeoutError: Timed out after 9000 ms while waiting for the WS endpoint URL to appear in stdout!` I don't know how we don't get the endpoint in that time. Any idea where to start looking?
