### ISSUE TITLE
Upgrade cosmiconfig

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11476]
cosmiconfig has a breaking change that requires defining the strategy for the config search https://github.com/cosmiconfig/cosmiconfig/blob/main/CHANGELOG.md#900

We need to upgrade and test the upgrade manually. 
We then need to run `@dependabot unignore cosmiconfig` to enable the dependabot updates again. cc @jrandolf @Lightning00Blade

**Comment by nitehawk42** [comment]
Is there a workaround for this? This is broken for me now, and downgrading to old versions of puppeteer doesn't seem to help.

**Comment by Lightning00Blade** [comment]
Closing as completed in #11731
