### ISSUE TITLE
[Bug]: When changing headless from true to "new"

### ISSUE THREAD

**Issue by downey88** [puppeteer/puppeteer#11489]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

const genHtmlToPdfContractPptr = async (htmlContent) => {
   const browser = await puppeteer.launch({
        // ignoreDefaultArgs: ['--disable-extensions'],
        args: ['--no-sandbox', '--disable-dev-shm-usage'],
        headless: "new"
   });
   await browser.close();
};
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I am trying to change headless from true to "new" as depreciation warnings showed up.. I am using container.

### Expectation

I expect all runs normally

### Reality

The container suddenly became error after changing to headless : "new"

### Puppeteer version

21.6.0

### Node version

18.19.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Linux

**Comment by OrKoN** [comment]
Please provide more details about what error you are seeing and try using the latest version. See https://pptr.dev/troubleshooting for common problems and our Docker image if you are using Docker https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer

**Comment by downey88** [comment]
@OrKoN pardon me, I will check if the new version 21.5.2 of puppeteer solve the issue, soon I will report back..Hopefully only the version

Thank you

**Comment by downey88** [comment]
![issue_using_headless_new](https://github.com/puppeteer/puppeteer/assets/27220246/2d33992c-31f5-40d1-b5ba-5287a7660b7a)


I am using docker as container  when changing from **headless: true to headless: "new"**, and following to

**https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker**


and here is my Dockerfile
===============
FROM node:18-slim

RUN apt-get update \
    && apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils gnupg nodejs yarn \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN yarn add puppeteer@21.5.2

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_x86_64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init
ENTRYPOINT ["dumb-init", "--"]

CMD ["google-chrome-stable"]

=========================

I have updated my code to

const browser = await puppeteer.launch({
        // ignoreDefaultArgs: ['--disable-extensions'],
        args: ['--no-sandbox', '--disable-dev-shm-usage'],
        headless: "new",
        executablePath: 'google-chrome-stable'
    });
    
================================

Node Version : 18.19.0
NPM Version: 10.2.3
Puppeteer Version: 21.5.2
Kubernetes Version: 1.28 using AWS EKS

Any idea ?? Thank you before...
