### ISSUE TITLE
[Bug]: Data print failure.

### ISSUE THREAD

**Issue by sheduxdev** [puppeteer/puppeteer#11486]
### Minimal, reproducible example

```TypeScript
https://github.com/sheduxdev/JsonToPDF/
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

Print all products from 1 to 416

### Reality

It started at 206 when it should have written all 416 products.

### Puppeteer version

21.5.2

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Windows

**Comment by OrKoN** [comment]
The problem is with the HTML template (height: 100vh;). Save HTML to file and check if it renders correctly before printing.
