### ISSUE TITLE
[Bug]: Puppeteer fails on 21.5.2 on ARM Mac M2

### ISSUE THREAD

**Issue by madhavSoni** [puppeteer/puppeteer#11499]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {

  // Launch the browser and open a new blank page
  const browser = await puppeteer.launch({ headless: 'new' });
//FAILS ON ABOVE LINE
  const page = await browser.newPage();

  // Set screen size
  await page.setViewport({width: 1080, height: 1024});

  // Navigate the page to a URL
  await page.goto('google.com');
  await page.waitForNetworkIdle();

  const buttons = await page.$$('[data-testid^="add-to-cart"]');
  for (const button of buttons) {
    const text = await button.evaluate(el => el.textContent);
    console.log(text);
  }

  await browser.close();
})();
```

### Error string

Error: Failed to launch the browser process!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Puppeteer is failing on the following mac version in the latest version 21.5.2

Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64

### Expectation

The code to work an puppeteer to work as normal after upgrade.

### Reality

It doesn't work and only works in V21.4.1

### Puppeteer version

21.5.2

### Node version

18.17.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

macOS

**Comment by elibenjii** [comment]
downgrading to 21.4.0 has solved the issue for me

**Comment by OrKoN** [comment]
Can you use dumpio: true to see the output from the browser? I don't have an ARM M2 available unfortunately but the same version works for me on ARM M1.

**Comment by madhavSoni** [comment]
Hey all, in debugging the issue, we found what was happening was that the update for puppeteer hadn't completely gone through, causing an incomplete version of the chrome browser to be installed into this folder and cause a segmentation fault

/Users/{name}/.cache/puppeteer/chrome/mac_arm-119.0.6045.105/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing

Deleting this and doing a clean install of puppeteer solved the issue.

Thanks

**Comment by thephucit** [comment]
> Hey all, in debugging the issue, we found what was happening was that the update for puppeteer hadn't completely gone through, causing an incomplete version of the chrome browser to be installed into this folder and cause a segmentation fault
> 
> /Users/{name}/.cache/puppeteer/chrome/mac_arm-119.0.6045.105/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
> 
> Deleting this and doing a clean install of puppeteer solved the issue.
> 
> Thanks

Same issue
