### ISSUE TITLE
how to check if selector exists or is present ?

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1149]
> how to check if selector exists or is present waiting for (x) time or when the page is fully loaded ? with this code it does not work for me.

``
if (await page.$eval('selector', {timeout: 3000})) 
  {
  	console.log('found');
  }
else
{console.log('no found');}
``

**Comment by vsemozhetbyt** [comment]
As a variant:
```js
if (await page.$(selector) !== null) console.log('found');
else console.log('not found');
```

**Comment by apollo17march** [comment]
@vsemozhetbyt not working for me

**Comment by vsemozhetbyt** [comment]
@apollo17march Can you provide a small code example where it does not work?

**Comment by ratkorle** [comment]
This works for me :
`for (let o = 0; o < otherSelectorsPath.length; o++) {
                                    let otherSelectorText;
                                    let otherSelector = otherSelectorsPath[o];
                                    if (!(await page.$(otherSelector)) || (await page.$(otherSelector) === false) || (await page.$(otherSelector) === undefined) || (await page.$(otherSelector) === null) || (await page.$(otherSelector).length === 0)) { //check if selector exist on the page
                                        otherSelectorText = '';
                                    } else {
                                        otherSelectorText = await page.$eval(otherSelector, text => text.innerText); 
                                    }
                                    resultObject.push(otherSelectorText);
                                }`

**Comment by kantuni** [comment]
If you are not certain that a DOM element will appear:

```javascript
try {
  await page.waitFor(selector)
  // ...
} catch (error) {
  console.log("The element didn't appear.")
}
```

**Comment by ivanjeremic** [comment]
> If you are not certain that a DOM element will appear:
> 
> ```js
> try {
>   await page.waitForSelector(selector)
>   // ...
> } catch (error) {
>   console.log("The element didn't appear.")
> }
> ```

Thank you kantuni, this is perfect and not a 50 Line code like someone did here....you are a good coder!

**Comment by kantuni** [comment]
> Thank you kantuni, this is perfect and not a 50 Line code like someone did here....you are a good coder!

My pleasure!

P.S. You can also pass an optional timeout to the `waitForSelector` function. The default timeout is 30 seconds, which is a lot (especially for scrapers).

```js
try {
  await page.waitForSelector(selector, { timeout: 5000 })
  // ...
} catch (error) {
  console.log("The element didn't appear.")
}
```

**Comment by L-Jovi** [comment]
Is `await page.waitForSelector` better than `await page.$(selector)`?

**Comment by vsemozhetbyt** [comment]
@L-Jovi `page.waitForSelector()` will wait for element till it appears or till timeout exceeds. `page.$(selector)` will return the result immediately without waiting. If you sure that the element should already be on the page, you can use  `page.$(selector)`  check, otherwise `page.waitForSelector()` is safer.

**Comment by L-Jovi** [comment]
@vsemozhetbyt Thanks for explanation :)

**Comment by shoroqAltamimi** [comment]
@vsemozhetbyt how to ensure I'm successfully logged in , by ensure some element is present or return element is not present if it failed to log in ??

**Comment by vsemozhetbyt** [comment]
It seems the way is the same: use `page.waitForSelector()` to wait for the element, timeout means failed log-in.

**Comment by shoroqAltamimi** [comment]
@vsemozhetbyt but it doesn't work with me :( 

there is my script  

```
 if (await page.waitForSelector('[data-ghost="Click-MyAccount"]')) {
       console.log("found")
    } else console.log("not found");
```

I need to focus the element in the page and return the element is not present if the login failed

**Comment by vsemozhetbyt** [comment]
Try this:
```js
  try {
    await page.waitForSelector('img');
    console.log('found');
  } catch {
    console.log('not found');
  }
```

**Comment by shoroqAltamimi** [comment]
I'm trying it but nothing happens

**Comment by vsemozhetbyt** [comment]
Do you wait for the default timeout (30 sec)?

**Comment by shoroqAltamimi** [comment]
ya, but I want to focus the div element when it exists 
how I can do it 
I'm trying page.focus(selector) it doesn't work

**Comment by vsemozhetbyt** [comment]
Maybe if you provide a small but complete script example, somebody will be able to help.

**Comment by namename-123** [comment]
Hello, is it possible to use this on Recaptcha?
To wait for it to load.

**Comment by alidanial7** [comment]
`test('should have element', async () => {
  const page = await browser.newPage()
  await page.goto('http://localhost:3000/')
  await expect(page.$('#id') !== null)
}, 100000)`

**Comment by lewyuburi** [comment]
I use

```javascript
await page.waitForSelector('selector', { timeout: 5000 })
  .catch ((error) => {
    console.log("The element didn't appear.")
  })
```

**Comment by iCrashPhones** [comment]
is it possible to use page.waitForSelector for class names, or is there some other way? Most of the elements in my case dont have ids and most of them only have unique class names.

**Comment by UviFarchi** [comment]
> > Thank you kantuni, this is perfect and not a 50 Line code like someone did here....you are a good coder!
> 
> My pleasure!
> 
> P.S. You can also pass an optional timeout to the `waitForSelector` function. The default timeout is 30 seconds, which is a lot (especially for scrapers).
> 
> ```js
> try {
>   await page.waitForSelector(selector, { timeout: 5000 })
>   // ...
> } catch (error) {
>   console.log("The element didn't appear.")
> }
> ```

It works, but in general terms you shouldn't use exception handling for flow control. I would have thought someone who's katnuni would be a stickler for the forms.

**Comment by chanakaDe** [comment]
> 
> 
> If you are not certain that a DOM element will appear:
> 
> ```js
> try {
>   await page.waitForSelector(selector)
>   // ...
> } catch (error) {
>   console.log("The element didn't appear.")
> }
> ```

This saved my day. Simple and quick solution. Thanks man. Much love

**Comment by northmatt** [comment]
> If you are not certain that a DOM element will appear:
> 
> ```js
> try {
>   await page.waitForSelector(selector)
>   // ...
> } catch (error) {
>   console.log("The element didn't appear.")
> }
> ```

That causes a memory leak for me on failed attempts. Basically am constantly checking for a DOM element that will almost never appear over the course of some hours, so a lot of failed attempts will happen. So idk if that is an ideal solution.

**Comment by DvDream** [comment]
> If you are not certain that a DOM element will appear:
> 
> ```js
> try {
>   await page.waitForSelector(selector)
>   // ...
> } catch (error) {
>   console.log("The element didn't appear.")
> }
> ```


What if I expect that the selector won't appear and instead is appearing once my page has loaded? How could I make the test failing with that? thanks :)

**Comment by vsemozhetbyt** [comment]
Maybe this:
```js
await page.waitForTimeout(someTime);
if (await page.$(selector)) throw new Error('Unexpected element.');
```

**Comment by SalimF** [comment]
> Maybe this:
> 
> ```js
> await page.waitForTimeout(someTime);
> if (await page.$(selector)) throw new Error('Unexpected element.');
> ```

do you mean
` if (  await !( page.$( selector ) ) throw new Error( 'Unexpected element.' ) ); `

**Comment by mykhailo-kobylianskyi** [comment]
this method will return true if element exist, and false if element not exist of locator is invalid
```
async isSelectorExists(selector: string) {
  return await this._page.$(selector).catch(() => null) !== null;
}
```

**Comment by CactusWren2020** [comment]
> this method will return true if element exist, and false if element not exist of locator is invalid
> 
> ```
> async isSelectorExists(selector: string) {
>   return await this._page.$(selector).catch(() => null) !== null;
> }
> ```

Would it be possible to show more context? My program crashes when I try to implement this.

**Comment by Aryankesharwani04** [comment]
Why platforms like LeetCode do not throw any error while loading a profile, if profile doesn't exist.
