### ISSUE TITLE
[Bug]: fullPage screenshot when using emulate reloads the page and changes are lost

### ISSUE THREAD

**Issue by carlosvini** [puppeteer/puppeteer#11498]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";
import fs from "fs";
import { KnownDevices } from "puppeteer";

(async () => {
  const iPhone = KnownDevices["iPhone 6"];

  const browser = await puppeteer.launch({
    headless: false,
  });

  const page = await browser.newPage();

  await page.emulate(iPhone);
  await page.goto("https://pt.wikipedia.org"); // any page with enough content to exceed the viewport

  await page.evaluate(function () {
    var overlay = document.createElement("div");
    overlay.innerHTML = '<div style="background: fuchsia">test</div>'
    document.body.insertBefore(overlay, document.body.children[0]); // top so it's easier to see
  });

  console.log("Taking screenshot"); // page is reloaded and changes are lost
  const screenshot = await page.screenshot({
    encoding: "binary",
    type: "jpeg",
    fullPage: true,
  });

  fs.writeFileSync("screenshot.jpg", screenshot);
  await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Upgrading from a very old puppeteer version, we run some scripts to modify the page before taking a screenshot.

### Expectation

We'd like the inserted/modified elements to stay on the screenshot. 

### Reality

Page is reloaded and changes are lost. Might be related to #8690 but the use of emulate() causes it to actually reload, while the other issue says it just resizes.

### Puppeteer version

21.5.2

### Node version

18.19.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by OrKoN** [comment]
@jrandolf PTAL It looks like a regression caused by the recent changes

**Comment by jrandolf** [comment]
I was not able to reproduce this bug on the latest Puppeteer. Here is what I get:

![screenshot](https://github.com/puppeteer/puppeteer/assets/101637635/41916f66-7ab7-4df2-a7f2-69b7bcdc2648)

**Comment by carlosvini** [comment]
Works now with v21.6.0
