### ISSUE TITLE
Screenshot tests are flaky/failing after M120 roll

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11502]
See for the tests that have been affected: https://github.com/puppeteer/puppeteer/pull/11501/files

@jrandolf could you please take a look as well as at the user reported bugs?

**Comment by jrandolf** [comment]
Bisected to https://chromium.googlesource.com/chromium/src/+log/b8b95f5715b4bd2348e537b740048e4b6aa281b1..8026f46b0e73174f33834a26748107d1089a83bf

Doesn't look correct though; local builds work fine. Still investigating.
