### ISSUE TITLE
[Bug]: Navigating frame was detached

### ISSUE THREAD

**Issue by rsainiWin** [puppeteer/puppeteer#11515]
### Minimal, reproducible example

```TypeScript
const puppeteerCore = require("puppeteer-core");
const chromium = require("@sparticuz/chromium");
const { default: puppeteer } = require("puppeteer");

const generateTrecPdf = async (trec) => {
  const data = getInitialData(trec);
  let browser;
  try {
    browser = await puppeteerCore.launch({
      args: ["--disable-features=site-per-process", ...chromium.args],
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: "new",
      ignoreHTTPSErrors: true,
    });
  } catch {
    console.log("running locally");
    browser = await puppeteer.launch({
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-features=site-per-process",
      ],
      headless: false,
    });
  }
  console.log(browser.isConnected()); //prints true

  const hasToc = trec.template.hasToc;
  const tocArray = [1, 2, 3, 5];
  let page = await browser.newPage();
  await page.setViewport({ height: 1052, width: 814 });
  console.log(
    page.isClosed(),
    browser.isConnected(),
    page.browser().isConnected()
  ); // false true true

  // COVER PAGE
  try {
    await page.setContent("<div>TEST</div>");
  } catch (e) {
    console.error(e); // Error: Navigating frame was detached
  }

}
```

### Error string
```
Error: Navigating frame was detached     
at #onFrameDetached (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:109:47)     
at /var/task/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:732     
at Array.map (<anonymous>)     at Object.emit (/var/task/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:716)     
at CdpFrame.emit (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:91:23)     
at #removeFramesRecursively (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:454:15)     at #onClientDisconnect (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:102:42)
```

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I've been using Puppeteer-core for the last 3 months for the same code but it stopped working last night.
I've created a docker image that is deployed to aws lambda for pdf creation 

"@sparticuz/chromium": "119.0.0",
"puppeteer": "21.5.0",

### Expectation

Expected the code to render a simple div with content Test and should not have thrown error

### Reality

Getting error 
For version 
"@sparticuz/chromium": "119.0.0",
"puppeteer": "21.5.0",

``` 
Error: Navigating frame was detached     at #onFrameDetached (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:109:47)     at /var/task/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:732     at Array.map (<anonymous>)     at Object.emit (/var/task/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:1:716)     at CdpFrame.emit (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:91:23)     at #removeFramesRecursively (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:454:15)     at #onClientDisconnect (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:102:42)
```

For version Chromium 112.0.5614.0 - [Puppeteer v19.8.0]
```
ERROR	Error: Navigation failed because browser has disconnected!
at new LifecycleWatcher (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:95:223)
at IsolatedWorld.setContent (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/IsolatedWorld.js:203:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async CDPPage.setContent (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:436:9)
at async generateTrecPdf (/var/task/generateTrec.js:33:3)
at async exports.handler (/var/task/index.js:67:28)
```

### Puppeteer version

21.6.0

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by OrKoN** [comment]
I am unable to reproduce using the latest Puppeteer and the bundled Chrome. It looks like the browser crashes. Please report the issue to @sparticuz/chromium as that is a custom binary distribution. Note that AWS lambda might not have all dependencies for running the new headless or headful mode. See https://pptr.dev/troubleshooting#running-puppeteer-on-aws-lambda

**Comment by Forktechai** [comment]
I encountered the same issue. when i use the base image  public.ecr.aws/lambda/nodejs:16.2023.11.10.17  puppeteer worked well 
 but when i use the base image public.ecr.aws/lambda/nodejs:16. puppeteer  threw an err: Navigating frame was detached

**Comment by malvfr** [comment]
Same thing is happening to me. Tried several approaches but nothing worked yet

**Comment by paustint** [comment]
I started getting this error intermittently (but frequently) once I upgraded puppeteer from `20.8.1` to`21.7.0`

**Comment by nitehawk42** [comment]
This started happening to me when I added `waitUntil` and `timeout` parameters:
```
page.goto(localWebPage, {
	"waitUntil": "networkidle0",
	"timeout": "300000"
});
```

However, it is actually working correctly. I get my page loaded and my screenshot is created by `await page.screenshot(...)`. 

The error happens when it calls `await browser.close();` to cleanup.  My workaround is to just ignore the error.

**Comment by vbuongiovanni** [comment]
Clearing the chrome cache in the puppeteer directory and then reinstalling Chrome for Testing did the trick for me:

Clear cache:
```
rm rf ~/.cache/puppeteer/chrome
```

Reinstall chrome for testing:
```
npx puppeteer browsers install chrome
```

**Comment by sk8killer** [comment]
I add the error while using Puppeteer with firebase emulator.
After commenting "--single-process" argument, the error disappeared and everything works well now.

My code :
```
puppeteer.launch( {
        headless: true,
        devtools: false, // Ouvre DevTools pour faciliter le débogage
        dumpio: true,
        args: [
          "--no-sandbox",
          // "--single-process",
          "--disable-gpu",
          "--disable-dev-shm-usage",
          "--disable-setuid-sandbox",
          "--no-first-run",
          "--no-zygote",
          "--proxy-server='direct://'",
          "--proxy-bypass-list=*",
          "--deterministic-fetch"
        ],
      } );
```

**Comment by tarogege** [comment]
> This started happening to me on puppeteer `21.6.0` and the bundled chrome when I added `waitUntil` and `timeout` parameters:
> 
> ```
> page.goto(localWebPage, {
> 	"waitUntil": "networkidle0",
> 	"timeout": "300000"
> });
> ```
> 
> However, it is actually working correctly. I get my page loaded and my screenshot is created by `await page.screenshot(...)`.
> 
> The error happens when it calls `await browser.close();` to cleanup. My workaround is to just ignore the error.



> This started happening to me on puppeteer `21.6.0` and the bundled chrome when I added `waitUntil` and `timeout` parameters:
> 
> ```
> page.goto(localWebPage, {
> 	"waitUntil": "networkidle0",
> 	"timeout": "300000"
> });
> ```
> 
> However, it is actually working correctly. I get my page loaded and my screenshot is created by `await page.screenshot(...)`.
> 
> The error happens when it calls `await browser.close();` to cleanup. My workaround is to just ignore the error.

It happes when I call await browser.close() and re launch() again.But I think it is not right to keep it open. I still have no idea how to solve it better

**Comment by Neiso** [comment]
> I add the error while using Puppeteer with firebase emulator. After commenting "--single-process" argument, the error disappeared and everything works well now.
> 
> My code :
> 
> ```
> puppeteer.launch( {
>         headless: true,
>         devtools: false, // Ouvre DevTools pour faciliter le débogage
>         dumpio: true,
>         args: [
>           "--no-sandbox",
>           // "--single-process",
>           "--disable-gpu",
>           "--disable-dev-shm-usage",
>           "--disable-setuid-sandbox",
>           "--no-first-run",
>           "--no-zygote",
>           "--proxy-server='direct://'",
>           "--proxy-bypass-list=*",
>           "--deterministic-fetch"
>         ],
>       } );
> ```

Confirm that disabling `--single-process` when generating PDF did the trick for me as of   `"puppeteer": "^23.6.1"`.

**Comment by Vik-vyosim** [comment]
I encountered the same issue and found a way to debug and mitigate it.

To identify the reason and pinpoint which frame is being detached, you can use the following code:

```
page.on('framedetached', (frame) => {
    console.log(`Frame detached: ${frame.url()}`);
});
browser.on('disconnected', () => {
    console.log('Browser disconnected.');
});
```
In my case, setting waitUntil: 'load' helped because the frame detachments were occurring while the page resources were still loading and javascript were being executed.

**Comment by Vikokare** [comment]
I encountered the same issue and found a way to debug and mitigate it.

To identify the reason and pinpoint which frame is being detached, you can use the following code:

```
page.on('framedetached', (frame) => {
    console.log(`Frame detached: ${frame.url()}`);
});
browser.on('disconnected', () => {
    console.log('Browser disconnected.');
});
```
In my case, setting waitUntil: 'load' helped because the frame detachments were occurring while the page resources were still loading and javascript were being executed.

**Comment by Thread7** [comment]
Just thought I would add this piece of info in case it ends up helping someone. I kept getting the "Navigating frame was detached" error inside a function and could not figure out why when all my other functions that performed almost the same actions worked fine. In the end, I had forgotten to place an "await" statement in front of my function call. That fixed it.
