### ISSUE TITLE
[Bug]: captureBeyondViewport does not respect deviceScaleFactor

### ISSUE THREAD

**Issue by maxkoretskyi** [puppeteer/puppeteer#11514]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: 'new',
    executablePath: '/usr/bin/chromium',
    args: ['--no-sandbox'],
  });
  const page = await browser.newPage();
  const url='https://www.scrapingbee.com/webscraping-questions/puppeteer/how-to-take-a-screenshot-with-puppeteer/'
  await page.setViewport({ width: 3840, height: 2160, deviceScaleFactor: 2 });
  await page.goto(url);
  
  try {
    await page.screenshot({ path: `image.jpg` });
  } catch (err) {
    console.log(`Error: ${err.message}`);
  } finally {
    await browser.close();
    console.log(`Screenshot has been captured successfully`);
  }
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Old versions of Puppeteer, particularly from 18.1.0 and up to 19.0.0 produced very good quality of screenshots. Recent versions of Puppeteer, particularly 21.6.0, as well as older version starting from 19.2.0, produced worse quality of screenshots.

I didn't use bundled version of Chrome, installed it separately. This is the version of the browser outputted from the script:

```
const browser = await puppeteer.launch({...})
await browser.version(); // HeadlessChrome/119.0.6045.199
```

Here are the screenshots with exactly the same setup but different Puppeteer versions that shows the difference in image size:

![same browser](https://github.com/puppeteer/puppeteer/assets/6124091/11c35fa3-82b2-40a5-9612-ab6e7286364f)

The screenshot taken with 18.1.0 is twice as larget as the one taken with recent versions, as if the `deviceScaleFactor=2` is not taken into account.

Here's the basic Dockerfile that I used:

```
FROM debian:bookworm-slim

RUN apt update
RUN apt-get install -y nodejs npm
RUN apt-get install -y chromium
RUN apt-get install -y libx11-xcb1 libxcomposite1 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6

RUN mkdir /tmp/screenshot
WORKDIR /tmp/screenshot
COPY script.js script.js
RUN npm init -y

ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm install puppeteer@18.1.0
```

### Expectation

Same quality of screenshots as in 18.1.0

### Reality

Screenshots have worse quality on Linux.

### Puppeteer version

18.1.0, 21.6.0

### Node version

20.3.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by OrKoN** [comment]
@jrandolf please investigate this, it might be a recent regression

**Comment by OrKoN** [comment]
<img width="651" alt="Screenshot 2023-12-07 at 09 21 01" src="https://github.com/puppeteer/puppeteer/assets/399150/98fa449a-df1c-4862-a196-3070d8d1e273">

it looks like the default value for `captureBeyondViewport` got changed (was it in the changelog)? I get the same size if I specify `captureBeyondViewport: true` in the screenshot param. @maxkoretskyi can you try that?

Also, `waitUntil: 'networkidle2'` to ensure the page finished loading before screenshotting:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: 'new',
    executablePath: '/usr/bin/chromium',
    args: ['--no-sandbox'],
  });
  const page = await browser.newPage();
  const url='https://www.scrapingbee.com/webscraping-questions/puppeteer/how-to-take-a-screenshot-with-puppeteer/'
  await page.setViewport({ width: 3840, height: 2160, deviceScaleFactor: 2 });
  await page.goto(url, {
    waitUntil: 'networkidle2'
  });

  try {
    await page.screenshot({ path: `image.jpg`, captureBeyondViewport: true });
  } catch (err) {
    console.log(`Error: ${err.message}`);
  } finally {
    await browser.close();
    console.log(`Screenshot has been captured successfully`);
  }
})();

```

**Comment by maxkoretskyi** [comment]
@OrKoN you just raised my hopes up, alas for some reason it still doesn't work for me. Which version of puppeteer did you use in your Dockerfile? I don't even know where to look... this issue drives me nuts.

![result](https://github.com/puppeteer/puppeteer/assets/6124091/bc606243-268e-498c-b95e-351bcba6a6ea)

**Comment by OrKoN** [comment]
@maxkoretskyi I used the `latest` version

**Comment by maxkoretskyi** [comment]
Hooray! 🎉 Worked with 21.6.0! Let me try to run this on my real use case so I can confirm. Thanks!

**Comment by OrKoN** [comment]
@jrandolf I am not finding the change w.r.t. captureBeyondViewport in the changelog so I think it might be a regression. Could you please verify and restore the old behavior.

**Comment by jrandolf** [comment]
This doesn't look like an issue with the setting of `captureBeyondViewport`. It seems when `captureBeyondViewport` is false, the scale is not respected somehow.

**Comment by jrandolf** [comment]
Upon investigation, there are no issues here with respect to DPR and captureBeyondViewport.

> Old versions of Puppeteer, particularly from 18.1.0 and up to 19.0.0 produced very good quality of screenshots. Recent versions of Puppeteer, particularly 21.6.0, as well as older version starting from 19.2.0, produced worse quality of screenshots.

@maxkoretskyi On Linux, if you run

```sh
identify path/to/image.jpg
```

you'll notice that the image is 7680x4320 which is correct with respect to the dimensions you set and the pixel ratio.

> it looks like the default value for captureBeyondViewport got changed (was it in the changelog)?

@OrKoN tl;dr, CDP and Puppeteer swapped `captureBeyondViewport` logic when Josefine made changes to the flag.

In other words, Puppeteer sent `captureBeyondViewport: true` to CDP and CDP would internally set `captureBeyondViewport` to false when not given a clip and `true` otherwise.

Now, Puppeteer sends `captureBeyondViewport: false` when not given a clip and `true` otherwise to CDP and CDP doesn't do any normalization.

See https://github.com/puppeteer/puppeteer/pull/9153/files) for instance.

**Comment by jrandolf** [comment]
@maxkoretskyi Please upload both the large and small image in a comment so we can see why the size is different.

**Comment by maxkoretskyi** [comment]
@jrandolf so I used the same script from above with the latest version 21.6.0 inside the docker. The only difference in the script between images is `captureBeyondViewport: true` in the `page.screenshot`. Please see attached screenshots. Thanks!
![i1](https://github.com/puppeteer/puppeteer/assets/6124091/883e500e-561e-49e3-ae5d-a19cade0bc28)
![image_l](https://github.com/puppeteer/puppeteer/assets/6124091/963d9caf-8b64-4cc1-b41e-e8f76a9ce3f2)
![image_s](https://github.com/puppeteer/puppeteer/assets/6124091/5dea4b01-a209-459a-b6aa-23d35f47b433)

**Comment by jrandolf** [comment]
@maxkoretskyi Could you upload the images in your issue? You said there is a difference with `18.1.0` and `21.6.0`. Do not modify the `captureBeyondViewport` setting; use the script verbatim as you wrote above and upload the images. Thanks!

**Comment by jrandolf** [comment]
Ah, actually, I've found the issue! There is a simple reason why version 18.1.0 and up to 19.0.0 don't work. That's because Chromium 119 is not supported in those versions! Tl;dr, there are modifications in Chromium that make older versions of Puppeteer incompatible with newer version of Chromium.

See  https://pptr.dev/chromium-support for information on mapping.

**Comment by jrandolf** [comment]
Could you tell me what you are trying to take a screenshot of? If you want to capture the entire document, you can use `fullPage: true`. Otherwise, `screenshot` will capture whatever is in the viewport.

**Comment by maxkoretskyi** [comment]
@jrandolf thanks for your input! I tested today my use case with latest chrome version and latest puppeteer version, the quality of screenshots is good even without `captureBeyondViewport`. I guess what happened is there was some mismatch between the version of puppeteer and chrome that caused this affects. I'll be paying more attention to the mapping you referenced (here)[https://pptr.dev/chromium-support]. By the way, the latest puppeteer version is 26.1.0, but there is only version of chrome the previous v21.5.0. What's the process? When do you add a matching mapping for the latest version?

**Comment by jrandolf** [comment]
We add a matching version whenever a version of Chrome stabilizes and we roll it into Puppeteer because the roll may break Puppeteer and we have to update it.
