### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bahEzope224** [puppeteer/puppeteer#11542]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: 'true',});
    const page = await browser.newPage();
 
    // 2. Aller sur la page de connexion
    await page.goto('https://google.com');
    await browser.close();
})();
```

### Error string

 Puppeteer old Headless deprecation warning:

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been trying to execute this ocde but it's not working 

### Expectation

open the web page 

### Reality

I recieve this message:   
Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

### Puppeteer configuration file (if used)

```TypeScript
not use
```

### Puppeteer version

21.6.0

### Node version

21.4.0.

### Package manager

npm

### Package manager version

10.2.5

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
This is a warning and will not prevent the other part of your code of executing if you need to disable it you can use the following env variable - `PUPPETEER_DISABLE_HEADLESS_WARNING=true`.
Or set the `logLevel` to `'silent'` - https://pptr.dev/guides/configuration.

**Comment by bahEzope224** [comment]
thanks
