### ISSUE TITLE
[Bug]: importing puppeteer

### ISSUE THREAD

**Issue by AkshatDaxini** [puppeteer/puppeteer#11547]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

but it works perfectly with version  15.5.0
```

### Error string

 SyntaxError: Unexpected token '{'

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

As soon as I use const puppeteer = requires('puppetter') its throws an error

### Expectation

Their hould be no error while importing

### Reality

C:\AWrk\SCM\scm-server\node_modules\puppeteer-core\lib\cjs\puppeteer\api\ElementHandle.js:176 static {  ^  SyntaxError: Unexpected token '{'

![bug](https://github.com/puppeteer/puppeteer/assets/47495207/9dc27323-dd3f-414c-a27a-ddc9e194a617)

### Puppeteer version

21.6.1

### Node version

Node v16.10.0

### Package manager

npm

### Operating system

Windows

**Comment by jrandolf** [comment]
We only support Node >=16.13.2

**Comment by Krishnaraj-shankar** [comment]
I'm getting this error. 

node version: 20.11.1
puppeteer version: 22.4.1

How to resolve this?

**Comment by AkshatDaxini** [comment]
Easiest fix to this error was downgrading puppeteer version
