### ISSUE TITLE
[Bug]: Page.click() does not work with an <a> tag and input selector

### ISSUE THREAD

**Issue by Akash-Preet** [puppeteer/puppeteer#11552]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  // Launch the browser and open a new blank page
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Navigate the page to a URL
  await page.goto('YOUR SITE');

  // Set screen size
  await page.setViewport({width: 1080, height: 1024});

  //case 1
  const NavBtn = "#nav > a";
  await this.page.waitForSelector(NavBtn);
  await Promise.all([
      this.page.waitForNavigation(),
      this.page.click(NavBtn)
  ]);
  
  //case 2
  const inputBtn = "[alt='submit']";
  await this.page.waitForSelector(inputBtn);
  await Promise.all([
      this.page.waitForNavigation(),
      this.page.click(inputBtn)
  ]);

  await browser.close();
})();
```

### Error string

Error: Node is either not clickable or not an Element

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We are running puppeteer on AWS lambda and we recently updated the puppeteer version from 20.2.0 to version 21.6.0 and @sparticuz/chromium: "113.0.1" to @sparticuz/chromium: "119.0.0" and we are facing this "Error: Node is either not clickable or not an Element" for most of the selectors.

### Expectation

It should click the <a> tag or submit button and proceed with navigation.

### Reality

It is not navigating and throws the "Error: Node is either not clickable or not an Element" error.

### Puppeteer version

21.6.1

### Node version

18.15.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by jrandolf** [comment]
Could you provide a demo page? That error implies precisely what it says; the node is either not clickable or not an Element.

**Comment by Akash-Preet** [comment]
@jrandolf , I do not have a demo page. All I do is web scrape our site by calling the AWS lambda function. If you see case 1 it's an anchor tag and in case 2 it is an input field of the type button which has the attribute of alt='submit' both are clickable items.

**Comment by OrKoN** [comment]
I'd suggest checking that selectors actually return correct elements. if the element is not laid out (does not have a bounding box), the click will not work. Alternatively, provide a test page for us to double check.

**Comment by ckcr4lyf** [comment]
@OrKoN just FYI, we were very late in upgrading, and today we did v20->v21 and were affected by this. Seems like this is a breaking change (didn't bother to find the diff), but in our case we were clicking on the `<a>` which indeed does not have a bounding box. 

This was fine in v20, and not mentioned in the changelog from what I can tell.

https://github.com/user-attachments/assets/1a1d8eba-dd9b-4147-8e1b-9b05d27a71cd
