### ISSUE TITLE
[Bug]: Html content to PDF convert not working in node v20.10

### ISSUE THREAD

**Issue by rishabhj-c247** [puppeteer/puppeteer#11550]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const fs = require('fs');
(async () => {
	// Create a browser instance
	const browser = await puppeteer.launch({
		headless: 'new',
	});

	// Create a new page
	const page = await browser.newPage();

	//Get HTML content from HTML file
	const html = fs.readFileSync('sample.html', 'utf-8');
	await page.setContent(html, { waitUntil: 'domcontentloaded' });

	//To reflect CSS used for screens instead of print
	await page.emulateMediaType('screen');

	// Downlaod the PDF
	const pdf = await page.pdf({
		path: 'result.pdf',
		margin: { top: '100px', right: '50px', bottom: '100px', left: '50px' },
		printBackground: true,
		format: 'A4',
	});

	// Close the browser instance
	await browser.close();
})();
```

### Error string

/node_modules/puppeteer-core/lib/cjs/puppeteer/util/disposable.js:19 Symbol.dispose ??= Symbol('dispose');

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

It would be great, rather than creating some additional script or polyfill for working with Puppeteer. It would be fixed inside a Node module itself.

### Reality

Unable to generate PDF files from HTML content.

### Puppeteer version

21.6.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Hey @rishabhj-c247,
Our CI is running Node v20.10.0 without any issue, so I don't think there is a problem with this version of Node.
Can you provided the full message of the error, as there is not enough information to go on what may be the cause?

**Comment by rishabhj-c247** [comment]
Hello @Lightning00Blade,
Thank you for your support! The issue has been resolved after upgrading to the latest package of Puppeteer.
