### ISSUE TITLE
 Error: Failed to launch the browser process! 

### ISSUE THREAD

**Issue by MEHARKhaoula** [puppeteer/puppeteer#11577]
i am new to puppeteer and i am getting this error when tryig to print pdf files
`The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`/home/khoula/.nvm/versions/node/v21.5.0/bin/node /home/khoula/.nvm/versions/node/v21.5.0/bin/npm root -g` /home/khoula/.nvm/versions/node/v21.5.0/bin/node '/home/khoula/Desktop/flex-erp/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"http:\/\/127.0.0.1:8000\/browsershot\/view\/eyJpdiI6IjRONlFjNVc4aHMrM3A2NTNFTWNsT3c9PSIsInZhbHVlIjoiK0FIQXpOWXNIc0pRbWxwZjdIQWk5UT09IiwibWFjIjoiMmY4NTI5M2E5NzVkOGYzYTVjYjViYzczM2VlMjE5ZGJhYmEyOTZmOGVkZmEyZjgyYjM3NzQ1NDA4MTJhZjdmMCIsInRhZyI6IiJ9?expires=1703062483&signature=cdae9a9dec62619cc5973d1feab81e7513552bcc63a949eee1d24f06cf5a43c9","action":"pdf","options":{"path":"\/home\/khoula\/Desktop\/flex-erp\/storage\/pdfs\/INV-2023-001.pdf","args":["--no-sandbox"],"viewport":{"width":800,"height":600},"executablePath":"\/usr\/bin\/chromium-browser","waitUntil":"networkidle0","ignoreHttpsErrors":true,"timeout":500000,"format":"A4"}}'" failed. Exit Code: 1(General error) Working directory: /home/khoula/Desktop/flex-erp/public Output: ================ Error Output: ================ [1m[43m[30m Puppeteer old Headless deprecation warning:[0m[33m In the near feature `headless: true` will default to the new Headless mode for Chrome instead of the old Headless implementation. For more information, please see https://developer.chrome.com/articles/new-headless/. Consider opting in early by passing `headless: "new"` to `puppeteer.launch()` If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.[0m Error: Failed to launch the browser process! TROUBLESHOOTING: https://pptr.dev/troubleshooting at Interface.onClose (/home/khoula/Desktop/flex-erp/node_modules/@puppeteer/browsers/lib/cjs/launch.js:259:24) at Interface.emit (node:events:531:35) at Interface.close (node:internal/readline/interface:527:10) at Socket.onend (node:internal/readline/interface:253:10) at Socket.emit (node:events:531:35) at endReadableNT (node:internal/streams/readable:1696:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) node:internal/process/per_thread:233 throw new ErrnoException(err, 'kill'); ^ Error: kill EACCES at process.kill (node:internal/process/per_thread:233:13) at pidExists (/home/khoula/Desktop/flex-erp/node_modules/@puppeteer/browsers/lib/cjs/launch.js:323:24) at Process.kill (/home/khoula/Desktop/flex-erp/node_modules/@puppeteer/browsers/lib/cjs/launch.js:199:13) at process.<anonymous> (/home/khoula/Desktop/flex-erp/node_modules/@puppeteer/browsers/lib/cjs/launch.js:106:18) at process.emit (node:events:519:28) at process.exit (node:internal/process/per_thread:192:15) at callChrome (/home/khoula/Desktop/flex-erp/vendor/spatie/browsershot/bin/browser.cjs:409:17) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { errno: -13, code: 'EACCES', syscall: 'kill' } Node.js v21.5.0`

I am using 
node version v21.5.0
puppeteer 20.5.0

**Comment by praoshealth** [comment]
I got the same error w/ node 20. Downgrading to node 18 fixed it for me

**Comment by MEHARKhaoula** [comment]
i solved the problem by  running these commands in ubunto 22:
`sudo npm install -g puppeteer --unsafe-perm=true --allow-root
sudo apt-get install -y nodejs gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev libxshmfence-dev
cd /usr/lib/node_modules/puppeteer && node install.mjs
sudo chmod -R o+rx /home/yourusername/.cache/puppeteer
`
set the executblePath to:  /home/yourusername/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome

**Comment by deCaldas** [comment]
I solved the problem running this command: `sudo apt-get install libasound2 libcairo2 libpango-1.0-0 libxkbcommon0 libgbm1 libxrandr2 libxfixes3 libxdamage1 libxcomposite1 libcups2 libatk-bridge2.0-0 libnss3`
