### ISSUE TITLE
Add a way to set the root font size, as a user could in the browser settings

### ISSUE THREAD

**Issue by nhoizey** [puppeteer/puppeteer#1157]
**What is the expected result?**

I would like to be able to test how websites behave when a user sets a root font size that is different from the default 16px.

So I need a way to tell puppeteer to change the root font size value.

![image](https://user-images.githubusercontent.com/78213/31995580-58f40256-b985-11e7-9848-9932e74193f2.png)

**Comment by aslushnikov** [comment]
The exact implementation would require plumbing protocol method to chromium first, which is too involved for the scope of the issue.

You can use `page.addStyleTag` to emulate this behavior to some extend.

**Comment by nhoizey** [comment]
@aslushnikov I understand it would be impossible without an evolution in Chromium.

I think I can't use `page.addStyleTag` for this. I want to change the root font size.

**Comment by Garbee** [comment]
Just change the body style and set the font size using an evaluation in page.

**Comment by nhoizey** [comment]
I first would have to check if the CSS sets a font-size on `html` and/or `body`.

And it won't be enough anyway, because Media Queries expressed with `em` or `rem` are relative to the root font size.

In [the media query spec](https://drafts.csswg.org/mediaqueries/#units):

> Relative units in media queries are based on the initial value, which means that units are never based on results of declarations. For example, in HTML, **the em unit is relative to the initial value of font-size, defined by the user agent or the user’s preferences, not any styling on the page**.

**Comment by Garbee** [comment]
AH, `em` wouldn't get affected. That's right. `rem` however still would (I have built experiments in the past that function based on that.)

@aslushnikov This is actually something that is fairly important if sites want to be able to test their accessibility. While it isn't anything that should be jumped right on to be done. I do believe it prudent to have this task as something to be done in the future considering how important it is for a11y.

**Comment by nhoizey** [comment]
@Garbee thanks a lot, it is indeed for a11y testing that I would like to be able to do it.

Should we reopen this issue, or create one elsewhere?

**Comment by aslushnikov** [comment]
> And it won't be enough anyway, because Media Queries expressed with em or rem are relative to the root font size.

Ah, too bad workaround doesn't work.

> Should we reopen this issue, or create one elsewhere?

@nhoizey could you please also file a bug for this at `crbug.com/new`?

**Comment by nhoizey** [comment]
@aslushnikov done: https://bugs.chromium.org/p/chromium/issues/detail?id=782172

**Comment by aslushnikov** [comment]
This can be done now using [`CDPSession`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-class-cdpsession) and protocol's [`Page.setFontSize`](https://vanilla.aslushnikov.com/#Page.setFontSizes):

```js
const client = await page.target().createCDPSession();
await client.send('Page.enable');
await client.send('Page.setFontSizes', {
  fontSizes: {
     standard: 32,
     fixed: 48
  }}
});
```

**Comment by jeffmcmahan** [comment]
@aslushnikov No luck with that workaround, at this point.

Also, absolutely zero luck with any solution of any kind to control the font size at all. Chrome apparently *sucks* at printing HTML documents. The only thing I have consistent success with is appending a `<style>` block to an HTML document before producing a PDF. But I note that `@media print` does not work in Chrome.
