### ISSUE TITLE
[Feature]: Allow caching static resources between launched, without sharing cookies

### ISSUE THREAD

**Issue by abannura** [puppeteer/puppeteer#11587]
### Feature description

Hi, as the title says, it would be great if we could have a cache shared between different browser instances launched using `launch`, but without sharing cookies between them.

Currently, the only way I found for sharing files/resources between browser instances is using `userDataDir`. It works great, except that cookies are also being shared. This is a problem when cookies hold personal information that shouldn't be leaked between browser instances.

I found [this](https://github.com/puppeteer/puppeteer/issues/7404) similar issues, but sadly no one has answered it. As it's mentioned in that issue, one can implement a custom solution that writes/reads to/from a local storage outside of Puppeteer, but it sounds like a common need that would be awesome to have as part of the package.

If there's another idea that I missed for achieving this, I'd really appreciate you pointing me in the right direction 🙏 .

**Comment by OrKoN** [comment]
Have you tried using the https://peter.sh/experiments/chromium-command-line-switches/#disk-cache-dir argument?

**Comment by abannura** [comment]
No, I haven't tried using it, but will definitely do. Thanks for pointing it out!
