### ISSUE TITLE
Waiting for either `load` or `networkIdle`

### ISSUE THREAD

**Issue by Khady** [puppeteer/puppeteer#1158]
I wonder is it is possible to have a behavior which is the "opposite" of the one requested in #805. I'd like to consider goto as done when either `load` is fired or when `networkidle` is ready.

Actually, something even more wonderful would be to be able to express more complex combinations of events. I would like to have something like `["load", ["domcontentloaded", "networkidle0"]]`. goto would return when either `load` is ready or when both `domcontentloaded` and `networkidle0` are ready.

If I can provide a PR, would such a feature be accepted?

**Comment by DSchau** [comment]
Would Promise.race() work for the first (simpler) condition? In fact, it would work for the second too. Something like this

```javascript
await Promise.race([
  browser.goto(URL, { waitUntil: 'load' }),
  browser.goto(URL, { waitUntil: ['domcontentloaded', 'networkidle0'] })
]
```

Note: I haven't tested this, but it _could_ work! Also note the second condition (the array for waitUntil) is already supported https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

**Comment by aslushnikov** [comment]
I'd use the following:
```js
// navigate the page
page.goto(URL);
// and wait for either of events to trigger
await Promise.race([
  page.waitForNavigation({waitUntil: 'load'}),
  page.waitForNavigation({waitUntil: 'networkidle0'})
]);
```
