### ISSUE TITLE
[Docs]: Page.waitForFunction() documentation should be more comprehensive

### ISSUE THREAD

**Issue by benelliott** [puppeteer/puppeteer#11591]
### Feature description

`Page.waitForFunction()` will repeatedly execute the callback until it returns a truthy value or the timeout is exceeded. However this "wait until truthy" behaviour isn't mentioned at all in the API docs and can only be discovered by either reading the source code or via StackOverflow.

I'll attempt a PR in a few minutes.

**Comment by OrKoN** [comment]
Thanks!
