### ISSUE TITLE
Setting a different default timeout for `waitForFunction`

### ISSUE THREAD

**Issue by MarkTiedemann** [puppeteer/puppeteer#1160]
I'd like to set a different default timeout for `page.waitForFunction`.

https://github.com/GoogleChrome/puppeteer/blob/ab9b34cd5dad54e170be916016a4e9b4097231ed/lib/FrameManager.js#L461

Currently, I'm monkey patching the `page.waitForFunction` to set a different default timeout of `5000`.

Any ideas on how to do this in a better way?

**Comment by aslushnikov** [comment]
I'd use a default options object and pass it over everywhere.

Other than that, your approach seems reasonable to me.
