### ISSUE TITLE
[Bug]: Cant connect from external IP

### ISSUE THREAD

**Issue by batata004** [puppeteer/puppeteer#11602]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
 headless: true,
 args: ['--remote-debugging-port=9777', '--remote-debugging-address=0.0.0.0', '--no-sandbox'],
});

const page = await browser.newPage();

await page.goto('https://youtube.com/', {waitUntil: 'networkidle0'});
```

### Error string

No error string

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

If I run Puppeteer in a server openin Chrome with these two flags `--remote-debugging-port=9777 --remote-debugging-address=0.0.0.0` and if I try to connect to Chrome from my home computer, it never finds the Chrome running in the server (chrome://inspect).

It looks like `remote-debugging-address` is doing nothing. I tried seeting it to my server IP, and the same problem. When connecting to the remote Chrome from the remote computer, it works (using localhost:9777), however when I use my home computer to try to connect to the remote Chrome, it never connects.

It's not a firewall problem (it's disabled) and this bug happens on Windows and on Linux too. I never managed to access the remote Chrome interface from an external source.

### Expectation

I should be able to access it remotely.

### Reality

I cant access remotel.

### Puppeteer version

latest

### Node version

latest

### Package manager

npm

### Package manager version

latest

### Operating system

Windows

**Comment by OrKoN** [comment]
It does not sound like a Puppeteer issue. Does it reproduce by running the browser with the same arguments? Would you mind filing a bug against crbug.com if it is the case?

**Comment by batata004** [comment]
I reported it as a bug at https://bugs.chromium.org/p/chromium/issues/detail?id=1514699

If you could star it so it gets a little priority, wouldnt hurt.
