### ISSUE TITLE
[Bug]: Uncaught error when a null variable is passed in 'puppeteer.launch(options)'

### ISSUE THREAD

**Issue by pedro-santos21** [puppeteer/puppeteer#11601]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
opt = null;
browser = await puppeteer.launch(opt);
```

### Error string

TypeError: Cannot read properties of null (reading 'product')

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Passing a null variable in puppeteer.launch(options), commonly by accident

### Expectation

I expected it would catch the error and return a developer-friendly error message. or default options as an empty dictionary and launch with default options

### Reality

It returns:
```
    const {product = this.defaultProduct} = options;
           ^
TypeError: Cannot read properties of null (reading 'product')
```

and points to ```\node_modules\puppeteer-core\src\node\PuppeteerNode.ts:181```

### Puppeteer version

21.6.1

### Node version

21.5.0

### Package manager

npm

### Package manager version

10.2.5

### Operating system

Windows

**Comment by pedro-santos21** [comment]
My bad if it's not a "real problem"!

But I got a bit lost in debugging because of the weird error message and the file it took me to (especially the 'reading product'). Ended up discovering that a tricky part of my code was passing a null 'options' variable."

Looks quite simple to catch and make it clearer, as it's something that could commonly happen to developers.

**Comment by OrKoN** [comment]
Consider using TypeScript to catch errors like this. Puppeteer provides TypeScript types for that reason.
