### ISSUE TITLE
EACCES: permission denied error

### ISSUE THREAD

**Issue by qamarali205** [puppeteer/puppeteer#11613]
In my localhost environment, everything is functioning correctly. Additionally, about 4-5 days ago, the live server, which utilizes NGINX, was also successfully operating without any issues. However, following updates made to unrelated modules' code, a problem arose. It's important to note that these changes were not associated with Puppeteer or the PDF generation system.

Despite the functionality working well locally and previously on the live server, the recent updates to other modules triggered an error in the live environment. It's noteworthy that these alterations did not directly involve the Puppeteer functionality or the process responsible for generating PDFs.

getting error

{
    "success": 0,
    "message": "EACCES: permission denied, open 'flightbooking.pdf'",
    "status": 500,
    "data": {}
}

**Comment by OrKoN** [comment]
The issue indicates that the permissions are not correctly set to open/write flightbooking.pdf. Please make sure the permissions are correct.

**Comment by qamarali205** [comment]
all is correct and same code as previously
