### ISSUE TITLE
[Bug]: how to set proxy for puppeteer with electron

### ISSUE THREAD

**Issue by thebeautyoflove** [puppeteer/puppeteer#11610]
### Steps to reproduce

I can't access a.com without opening a VPN.
b.com can be accessed with or without VPN
when I puppeteer.launch({
    args:['proxy-serve=http://x.x.x.x:0000']
})
b.com is useful always, a.com is not even if use vpn
http://x.x.x.x:0000 this proxy can access a.com
"electron": "^25.2.0",
"puppeteer": "^21.1.0",
 "puppeteer-extra": "^3.3.6",
 node: 18.0.0

### Expected results

a.com can be accessed

### Actual results

I can't access a.com

**Comment by thebeautyoflove** [comment]
const puppeteer = require('puppeteer-extra')
const path = require('path')
const { 
  app, BrowserWindow, BrowserView, Notification,
  ipcMain, Menu, clipboard, autoUpdater, screen 
  } = require('electron');
const r = async (proxy) => {
  const puppeteerOpt = {
    headless: false,
    devtools: true,
    defaultViewport: null,
    defaultArgs: [],
    args: [
      `--proxy-server=${proxy}`,
    ],
  }
  const browser = await puppeteer.launch(puppeteerOpt);
  const page = await browser.newPage();
  page.goto('https://www.facebook.com');
}
r('http://ip:port');
my script :electron-forge start

**Comment by OrKoN** [comment]
It should be possible to use https://peter.sh/experiments/chromium-command-line-switches/#proxy-server or other proxy args. 

P.S. wrong bug template

**Comment by thebeautyoflove** [comment]
> It should be possible to use https://peter.sh/experiments/chromium-command-line-switches/#proxy-server or other proxy args.
> 
> P.S. wrong bug template

sorry, I don't know what you mean
