### ISSUE TITLE
[Bug]: Relative link to local file not clickable when generating pdf

### ISSUE THREAD

**Issue by geral-victor** [puppeteer/puppeteer#11620]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

export async function genPdf(outputFile: string) {
    const htmlContent = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
        </head>
        <body>
            <p><a href=\"./linktofile.pdf\">open pdf file</a></p>
        </body>
        </html>
    `;

    // Launch a headless browser with puppeteer
    const browser = await puppeteer.launch({ headless: "new" });
    const page = await browser.newPage();
    
    // Set the HTML content of the page
    await page.setContent(htmlContent);

    // Generate PDF from the HTML content
    await page.pdf({
        path: outputFile,
        format: 'A4',
    });

    // Close the browser
    await browser.close();
}
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I'm generating some pdfs with puppeteer, and it works well. However, I want to add (relative) links into the generated pdfs to other local files that are in the same directory.

I was able to generate such pdfs with word so I know it is doable.

SO question opened [here](https://stackoverflow.com/questions/77751317/relative-link-to-local-file-not-clickable-when-generating-pdf-with-puppeteer)

### Expectation

Link should be clickable, even with relative path

### Reality

Link is not clickable. (only when specifying an absolute path using `file://` which is not possible for portable files that will be packaged with other files.)

### Puppeteer version

21.6.1

### Node version

21.5.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by OrKoN** [comment]
I don't think that is expected to work as there is no current working directory for content set using `setContent`. `setContent` is set on the `about:blank` page that has no origin (so the link is broken). I think you need to store the html file next to the other files and use `page.goto('file://...')` to open to have a working link that can be printed.

**Comment by geral-victor** [comment]
@OrKoN, tried your idea, this time the link is clickable, but it points towards an absolute path (determined at generation time), which is not working for portable applications (where you package several pdf together and link them together using links).

If I create an HTML file with the example provided and save it, then open it with Chrome, saving as pdf works properly : the link is clickable **and** relative.

**Comment by OrKoN** [comment]
@geral-victor can you share your test file? I am not observing this behavior: the URLs are absolute after printing (tried with 120.0.6099.129, MacOS).

**Comment by geral-victor** [comment]
@OrKoN you are right, my test with chrome was wrong somehow, chrome has the same behaviour of emitting absolute paths (unfortunately).
