### ISSUE TITLE
EACCES: permission denied, open 'flightbooking.pdf

### ISSUE THREAD

**Issue by qamarali205** [puppeteer/puppeteer#11623]
In my localhost environment, everything is functioning correctly. Additionally, about 4-5 days ago, the live server, which utilizes NGINX, was also successfully operating without any issues. However, following updates made to unrelated modules' code, a problem arose. It's important to note that these changes were not associated with Puppeteer or the PDF generation system.

Despite the functionality working well locally and previously on the live server, the recent updates to other modules triggered an error in the live environment. It's noteworthy that these alterations did not directly involve the Puppeteer functionality or the process responsible for generating PDFs.

getting error

{
"success": 0,
"message": "EACCES: permission denied, open 'flightbooking.pdf'",
"status": 500,
"data": {}
}

**Comment by OrKoN** [comment]
Please do not re-post the same issue. This is not a bug with Puppeteer but a permissions problem. Post a question on StackOverflow if you need help debugging.

**Comment by qamarali205** [comment]
ok
