### ISSUE TITLE
[Bug]: Navigation failed because browser has disconnected

### ISSUE THREAD

**Issue by GordonHPepBoys** [puppeteer/puppeteer#11632]
### Minimal, reproducible example
Below examples do not work and cause exceptions
```TypeScript
Background image
{
  "Records": [{
      "body": "{\"storeId\":\"7980\",\"appointmentId\":35027063,\"printType\":\"courtesy\",\"copies\":1,\"bucket\":\"pby-store-docs-test\",\"key\":\"/TEST/Test-File.pdf\",\"html\":\"<b>Test PDF</b><br/><div style=\\\"display:block;background-image:url(https://picsum.photos/200/300);height:200px;width:200px;background-size:contain;background-repeat:no-repeat;background-position:center;\\\">Image Here</div>\"}"
  }]
}

Img Tag

{
  "Records": [{
      "body": "{\"storeId\":\"7980\",\"appointmentId\":35027063,\"printType\":\"courtesy\",\"copies\":1,\"bucket\":\"pby-store-docs-test\",\"key\":\"/TEST/Test-File.pdf\",\"html\":\"<b>Test PDF</b><br/><img src=\\\"https://picsum.photos/200/300\\\" />\"}"
  }]
}
```

### Error string

 "errorType": "Error", "errorMessage": "Navigation failed because browser has disconnected!", "stack": [ "Error: Navigation failed because browser has disconnected!", " at /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147", " at /var/task/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:62", " at Array.map ()", " at Object.emit (/var/task/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)", " at CDPSession.emit (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)", " at CDPSession._onClosed (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:247:14)", " at Connection._onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:128:21)", " at WebSocket. (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)", " at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:124:16)", " at WebSocket.emit (events.js:400:28)" ]

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Print PDF lambda function generates a PDF file using puppeteer from HTML content .
It's deployed as AWS lambda.

Below is the configuration:
npm install chrome-aws-lambda@8.0.2 puppeteer-core@8.0.0 --save-prod

Below is the exception:

"errorType": "Error", "errorMessage": "Navigation failed because browser has disconnected!", "stack": [ "Error: Navigation failed because browser has disconnected!", " at /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147", " at /var/task/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:62", " at Array.map ()", " at Object.emit (/var/task/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)", " at CDPSession.emit (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)", " at CDPSession._onClosed (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:247:14)", " at Connection._onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:128:21)", " at WebSocket. (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)", " at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:124:16)", " at WebSocket.emit (events.js:400:28)" ]

Code anippet
--------async function getBrowser() {
  if (puppeteer) {
    return await puppeteer.launch({ headless: true });
  }
  // if running in lambda return chromium lambda
  if (chromium) {
    return await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true
    });
  }
}

export const html2pdf = async (html = '', url = '', format = 'Legal') => {
  let myBrowser = await getBrowser();
  const page = await myBrowser.newPage();
  const loaded = page.waitForNavigation({
    waitUntil: 'load'
  });

  if (html) {
    await page.setContent(html, { waitUntil: 'networkidle0' });
  } else if (url) {
    await page.goto(url, { waitUntil: 'networkidle0' });
  }
  // await page.setViewport({ isMobile: true, width: 375, height: 667 });
  await loaded;

  const pdf = await page.pdf({ format: format });
  await page.close();
  await myBrowser.close();
  return pdf;
};
----------------------------------

according to some stackoverflow posts we have increased the ephemeral storage and memory to their perspective max: 10240 MB .
Please advise as to solution and how to  debug.
Thanks,

### Expectation

Generate PDF file

### Reality

 Navigation failed because browser has disconnected exception

### Puppeteer configuration file (if used)

```TypeScript
args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true
```

### Puppeteer version

8.0.0

### Node version

18.0.0

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Windows

**Comment by OrKoN** [comment]
The error likely happens because the browser crashes due to missing system dependencies on AWS Lambda. Consider using https://github.com/Sparticuz/chromium instead.

**Comment by GordonHPepBoys** [comment]
Please note the chrome version chrome-aws-lambda@8.0.2 puppeteer that is in the buildspec so the dependency is there.

**Comment by GordonHPepBoys** [comment]
@OrKoN which versions of pupeteer and Sparticuz/chromium do you recommend for our aws lambda project?
