### ISSUE TITLE
[Bug]: Do not expect new headless warning when it's disabled via args

### ISSUE THREAD

**Issue by jecfish** [puppeteer/puppeteer#11633]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const url = 'chrome://gpu';

const browser = await puppeteer.launch({
  args:  ['--no-sandbox','--headless=new']
});

const page = await browser.newPage();
await page.goto(url);
```

### Error string

Puppeteer old Headless deprecation warning:

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

No deprecation warning since I've provided the flag.

### Reality

It outputs warning in the console

### Puppeteer version

21

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.0

### Operating system

Linux

**Comment by jecfish** [comment]
When I run this example: https://github.com/jasonmayes/headless-chrome-nvidia-t4-gpu-support/blob/main/examples/puppeteer/jPuppet.js

with the additional launch param `ignoreDefaultArgs: true`, it will ignore the headless setting. I need to provide the headless config via `args`. Having two similar lines to disable the headless and warning feels like unintentional.

**Comment by beaufortfrancois** [comment]
In the meantime, we can set `PUPPETEER_DISABLE_HEADLESS_WARNING` to true.

**Comment by Lightning00Blade** [comment]
Closing this as `headless=new` is now the default and the warning is never shown.
