### ISSUE TITLE
[Bug]: puppeter npm could not find chrome in gcp console error

### ISSUE THREAD

**Issue by dineshkumar14062001** [puppeteer/puppeteer#11635]
### Minimal, reproducible example

```TypeScript
let browser = await puppeteer.launch({ headless: "new" });

                let page = await browser.newPage();

                await page.setContent(htmlContent);

                await page.pdf({
                    path: localFilePath,
                    format: 'A4',
                    printBackground: true,
                    displayHeaderFooter: true,
                    margin: { top: "1in", right: "0.1in", bottom: "0.5in", left: "0.1in" },
                    headerTemplate: headerTpl,
                    footerTemplate: footerTpl
                });

                await browser.close();

                let pdfBuffer = await fs.promises.readFile(localFilePath);
```

### Error string

[Bug]: Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either 2023-12-26 16:17:49.638 IST  1. you did not perform an installation before running the script (e.g. npx puppeteer browsers install chrome) or 2023-12-26 16:17:49.638 IST  2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer). 2023-12-26 16:17:49.638 IST For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. 2023-12-26 16:17:49.638 IST     at ChromeLauncher.resolveExecutablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:288:27) 2023-12-26 16:17:49.638 IST     at ChromeLauncher.executablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:219:25) 2023-12-26 16:17:49.638 IST     at ChromeLauncher.computeLaunchArguments (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:113:37) 2023-12-26 16:17:49.638 IST     at async ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28) 2023-12-26 16:17:49.638 IST     at async /usr/src/app/routes/services/common-service.js:340:31 2023-12-26 16:17:49.638 IST Could not find Chrome (ver. 119.0.6045.105). This can occur if either 2023-12-26 16:17:49.638 IST  1. you did not perform an installation before running the script (e.g. npx puppeteer browsers install chrome) or 2023-12-26 16:17:49.638 IST  2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer). 2023-12-26 16:17:49.638 IST For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

This code working in my post man, but not working in gcp run 

### Reality

[Bug]: Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either 2023-12-26 16:17:49.638 IST  1. you did not perform an installation before running the script (e.g. npx puppeteer browsers install chrome) or 2023-12-26 16:17:49.638 IST  2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer). 2023-12-26 16:17:49.638 IST For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. 2023-12-26 16:17:49.638 IST     at ChromeLauncher.resolveExecutablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:288:27) 2023-12-26 16:17:49.638 IST     at ChromeLauncher.executablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:219:25) 2023-12-26 16:17:49.638 IST     at ChromeLauncher.computeLaunchArguments (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:113:37) 2023-12-26 16:17:49.638 IST     at async ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28) 2023-12-26 16:17:49.638 IST     at async /usr/src/app/routes/services/common-service.js:340:31 2023-12-26 16:17:49.638 IST Could not find Chrome (ver. 119.0.6045.105). This can occur if either 2023-12-26 16:17:49.638 IST  1. you did not perform an installation before running the script (e.g. npx puppeteer browsers install chrome) or 2023-12-26 16:17:49.638 IST  2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer). 2023-12-26 16:17:49.638 IST For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

### Puppeteer version

21.6

### Node version

16

### Package manager

npm

### Package manager version

8

### Operating system

Linux

**Comment by OrKoN** [comment]
You need to make sure the binary is downloaded (re-install Puppeteer in your server environment) like mentioned in the error message.
