### ISSUE TITLE
[Bug]: browser.goto(url) Navigation Broken

### ISSUE THREAD

**Issue by GamerUprise** [puppeteer/puppeteer#11648]
### Steps to reproduce

You can test with any site containing %0A in the URL.

```
puppeteer.launch({ headless: false }).then(async browser => {
  await browser.goto('https://example.com/example%0A');
}
```

As soon as you have %0A in the URL it will automatically be deleted when navigating to URL.

### Expected results

Expected URL to include %0A upon navigating to page.

### Actual results

The browser will automatically delete the portion containing %0A. Website that I visit depends on this in the URL. Without it the page becomes broken.

**Comment by Lightning00Blade** [comment]
@GamerUprise I will close this one as it uses the wrong template and there is information that we need to easier help you.
You should use this [template](https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%5BBug%5D%3A+).
Also Puppeteer does not expose a method on the `browser` to navigate to a page.
