### ISSUE TITLE
[Bug]: PDF file download is not working in AlmaLinux 8 64bit / Linux OS

### ISSUE THREAD

**Issue by kalidas3** [puppeteer/puppeteer#11642]
### Minimal, reproducible example

```TypeScript
export const pdfGeneration = async (html) => {
    const browser = await puppeteer.launch({ headless: 'new' });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'domcontentloaded' });
    await page.emulateMediaType('screen');
    const pdf = await page.pdf({
        margin: { top: '100px', right: '50px', bottom: '100px', left: '50px' },
        printBackground: true,
        format: 'A4',
    });
    await browser.close();
    return pdf;
};
```

### Error string

Error: Failed to launch the browser process! /root/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I am trying to download pdf file like invoice pdf file from my application

### Expectation

It should create and download pdf file

### Reality

It should not create any pdf file. Just throwing error

### Puppeteer version

21.7.0

### Node version

18.19.0

### Package manager

npm

### Package manager version

10.20.3

### Operating system

Linux

**Comment by OrKoN** [comment]
You are missing required system dependencies to run Chrome https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux
