### ISSUE TITLE
[Bug]: - Error launching browser TimeoutError: Timed out after 100 ms while waiting for the WS endpoint URL to appear in stdout!

### ISSUE THREAD

**Issue by TVARecordings** [puppeteer/puppeteer#11646]
### Minimal, reproducible example

```TypeScript
npm start
```

### Error string

- Error launching browser (TimeoutError: Timed out after 100 ms while waiting for the WS endpoint URL to appear in stdout!)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

It just to work lol

### Reality

`- Error launching browser
TimeoutError: Timed out after 100 ms while waiting for the WS endpoint URL to appear in stdout!
    at ChromeLauncher.launch (C:\Users\TomVa\Documents\rzkytmgr Bot-SadBot OpenWA4.66.3 NodeJS18.16.0 Puppeteer21.6.1 Betaaa\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:149:23)
    at async PuppeteerExtra.launch (C:\Users\TomVa\Documents\rzkytmgr Bot-SadBot OpenWA4.66.3 NodeJS18.16.0 Puppeteer21.6.1 Betaaa\node_modules\puppeteer-extra\dist\index.cjs.js:128:25)
- Timed out after 100 ms while waiting for the WS endpoint URL to appear in stdout!
TimeoutError: Timed out after 100 ms while waiting for the WS endpoint URL to appear in stdout!
    at ChromeLauncher.launch (C:\Users\TomVa\Documents\rzkytmgr Bot-SadBot OpenWA4.66.3 NodeJS18.16.0 Puppeteer21.6.1 Betaaa\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:149:23)
    at async PuppeteerExtra.launch (C:\Users\TomVa\Documents\rzkytmgr Bot-SadBot OpenWA4.66.3 NodeJS18.16.0 Puppeteer21.6.1 Betaaa\node_modules\puppeteer-extra\dist\index.cjs.js:128:25)
- Please delete the ./_IGNORE_Ameca_8120241253 folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.
Error When start bot TimeoutError: Timed out after 100 ms while waiting for the WS endpoint URL to appear in stdout!
PS C:\Users\TomVa\Documents\rzkytmgr Bot-SadBot OpenWA4.66.3 NodeJS18.16.0 Puppeteer21.6.1 Betaaa> `

### Puppeteer configuration file (if used)

```JavaScript
const configObject = {
  sessionId: 'Ameca_8120241253',
  authTimeout: 60,
  autoRefresh: true,
  cacheEnabled: true,
  chromiumArgs: ['--no-sandbox'],
  disableSpins: true,
  headless: false,
  qrRefreshS: 40,
  qrTimeout: 0,
  messagePreprocessor: "AUTO_DECRYPT_SAVE",
  linkParser: "https://link.openwa.cloud/api",
  restartOnCrash: 'start',
  debug: false,
  logInternalEvents: false, //ONLY TURN THIS ON IF ASKED TO!
  logConsoleErrors: false,
  discord: '234717932175884288',
  ezqr: true,
  intervalCap: 5, //process 5 events
  interval: 1000, //within every 1 second window
  concurrency: 2, //make sure to process, at most, 2 events at any one time
  timeout: 100, //make sure there is a 100ms gap between each event processing.
  carryoverConcurrencyCount: true //If there are more than 5 events in that period, process them within the next 3 second period. Make sure this is always set to true!!!

};
```

### Puppeteer version

latest: [v21.7.0](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v21.7.0)

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by TVARecordings** [comment]
> This issue has an invalid Puppeteer version: `latest: 21.6.1`. Versions must follow [SemVer](https://semver.org/) formatting. Please update the form with a valid version.
> 
> [Analyzer run](https://github.com/puppeteer/puppeteer/actions/runs/7447070985)

Updated, still not working

**Comment by OrKoN** [comment]
The timeout applies to the launch command itself. 100ms is too low. Change it to a higher value or leave the default value.
