### ISSUE TITLE
[Bug]: Exposed function promise stays pending on Firefox

### ISSUE THREAD

**Issue by IiroP** [puppeteer/puppeteer#11653]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

// Sample function
const customFunction = () => {
  return "Hello World!";
}

const start = async () => {
  const browser = await puppeteer.launch({
    headless: false,
    protocol: 'webDriverBiDi',
    product: 'firefox',
  });

  const page = await browser.newPage();

  await page.exposeFunction('customFunction', customFunction);

  await page.evaluate(async () => {
    console.log("Starting evaluation") // This prints always
    const result = await window.customFunction();
    console.log("Finished evaluation") // This prints only in Chrome
    console.log(result);
  });
}

start();
```

### Error string

invalid argument A context and a realm reference are mutually exclusive

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm trying to use external function inside Puppeteer browser context with `page.exposeFunction`. It works perfectly when using Chrome, not so much in Firefox.

### Expectation

The sample code should output three lines to *browser* console:
```
Starting evaluation
Hello world!
Finished evaluation
```

### Reality

Exposed function is not evaluated in Firefox, instead the following error is thrown (if run with `env DEBUG="puppeteer:*"`):
```
ProtocolError: Protocol error (script.callFunction): invalid argument A context and a realm reference are mutually exclusive RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
  WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
  InvalidArgumentError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:382:5
  #assertTarget@chrome://remote/content/webdriver-bidi/modules/root/script.sys.mjs:657:13
  callFunction@chrome://remote/content/webdriver-bidi/modules/root/script.sys.mjs:308:63
  handleCommand@chrome://remote/content/shared/messagehandler/MessageHandler.sys.mjs:255:33
  execute@chrome://remote/content/shared/webdriver/Session.sys.mjs:274:32
  onPacket@chrome://remote/content/webdriver-bidi/WebDriverBiDiConnection.sys.mjs:211:37
  onMessage@chrome://remote/content/server/WebSocketTransport.sys.mjs:127:18
  handleEvent@chrome://remote/content/server/WebSocketTransport.sys.mjs:109:14
```

Additionally, if I try to run the exposed function directly on Firefox console, the result is always a promise that stays pending.

### Puppeteer version

21.7.0

### Node version

21.5.0

### Package manager

npm

### Package manager version

10.2.5

### Operating system

Linux

**Comment by whimboo** [comment]
Thanks a lot for the report @IiroP! We are going to fix this problem over on https://bugzilla.mozilla.org/show_bug.cgi?id=1873688 and a fix should be ready soon in Firefox Nightly.

**Comment by whimboo** [comment]
@jrandolf is something else still needed for Puppeteer specifically?
