### ISSUE TITLE
[Bug]: Crash in bundled Chrome for Testing in Puppeteer v21.7.0

### ISSUE THREAD

**Issue by mglasgow** [puppeteer/puppeteer#11672]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {

    try {

        const browser = await puppeteer.launch({
            headless: false,

            args: [
                "--enable-logging=stderr",
                "--v=1"
            ],

            dumpio: true,

            protocolTimeout: 10_000,
        });

        const page = (await browser.pages())[0];

        page.setDefaultTimeout(10 * 1000);

        const cdp = await page.target().createCDPSession();

        await cdp.send('Log.enable');

        cdp.on('Log.entryAdded', async ({ entry }) => {
            console.log(entry);
        });

        const url = "https://duckduckgo.com";
        
        console.log("goto: " + url);

        await page.goto(url, { waitUntil: ["domcontentloaded" /*, "networkidle0" */] });

        console.log("wait 10 seconds before waiting for selector, so 'Aw, Snap' crash page can show");

        const sleep = ms => new Promise(r => setTimeout(r, ms));
        await sleep(10000);

        console.log("waiting for selector input#searchbox_input")
        
        try {
            await page.waitForSelector("input#searchbox_input", {timeout: 10_000});

            console.log("will not reach this line");

        } catch (ex) {
            if (ex.name === "TimeoutError") {
                console.log("timed out waiting for selector, grabbing contents...");
                const contents = await page.content();
            }
        }

        await browser.close();
        
    } catch (e) {
        console.log("unhandled exception:" + e);
        process.exit(-1);
    }
})();
```

### Error string

No error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Trying to use puppeteer v21.7.0 on my x64 macbook pro with MacOS Big Sur 11.7.10 with node v18.19.0. Most complex websites will cause the bundled Google Chrome for Testing to eventually show the "Aw, Snap" crash page. This is running in headful mode.

### Expectation

I was expecting Google Chrome for Testing to not crash, and puppeteer continue to interact with the page.

### Reality

Google Chrome for Testing shows the Aw, Snap page. I have enabled logging as verbose as I know how. It does not show any specific error message, but it does have a warning before the crash happens:

`[0112/181159.541911:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee0178000, 0x2000): (os/kern) invalid address (1)`

I have attached output.log which shows maximum amount of logging I could get from the process: 
[output.log](https://github.com/puppeteer/puppeteer/files/13915870/output.log)

I have also attached a Crashpad minidump from `~/Library/Application Support/Google/Chrome for Testing/Crashpad/pending`: [91994f89-7b6b-4ed2-a46e-c4377b3c295c.dmp](https://github.com/puppeteer/puppeteer/files/13915874/91994f89-7b6b-4ed2-a46e-c4377b3c295c.dmp)

Interestingly, I can also trigger crashes by making the nodejs program sleep for 200seconds before going to a site, then manually going to Google Chrome for Testing window, opening the DevTools, going to Console and typing 'document'. Before I finish typing DevTools window will crash and disappear. Output will show the following:

`[0112/182455.075309:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee9ae4000, 0x2000): (os/kern) invalid address (1)
[1115:259:0112/182455.285419:VERBOSE1:profile_manager.cc(1388)] RemoveKeepAlive(Default, kDevToolsWindow). keep_alives=[kBrowserWindow (1)]`

The minidump for this is: [c9c6340d-187f-4d5f-b1e6-d5bcfd773243.dmp](https://github.com/puppeteer/puppeteer/files/13915899/c9c6340d-187f-4d5f-b1e6-d5bcfd773243.dmp)

### Puppeteer version

21.7.0

### Node version

18.19.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by mglasgow** [comment]
If I open `~//.cache/puppeteer/chrome/mac-119.0.6045.105/chrome-mac-x64/Google Chrome for Testing.app` directly and navigate to duckduckgo, then Aw, Snap crash page appears too.

**Comment by Karthikeyan2752** [comment]
I also faced some issues with puppeteer 21.5.2 installation, i've used node v20.10.0 and and chrome for testing 119.0.6045.105, it is not working for me, but when i use cft 120.0.6099.109 it is working fine.

**Comment by OrKoN** [comment]
@mglasgow does it happen in the later versions or in the stable/beta/dev builds that not Chrome for Testing?

**Comment by mglasgow** [comment]
@OrKoN Good idea. I installed the stable chrome for testing binaries using [these instructions](https://developer.chrome.com/blog/chrome-for-testing/#how_can_i_get_chrome_for_testing_binaries): `npx @puppeteer/browsers install chrome@stable`. Running the app directly allowed me to navigate to duckduckgo.com without a crash, which was promising. It is v120.0.6099.109.

I then copied Google Chrome for Testing.app to `~/.cache/puppeteer/chrome/mac-119.0.6045.105/chrome-mac-x64`, after renaming the existing app. Running my node script above, duckduckgo.com now displays without a crash, and I can interact with the DevTools environment. Excellent!

So sounds like the problem will be fixed in a puppeteer release that bundles the new chrome version, as per [Chromium Support](https://pptr.dev/chromium-support).

**Comment by OrKoN** [comment]
@mglasgow looks like it should be fixed with the next release then. Note that we have not rolled out M120 yet because we encountered flakiness with screenshot capturing. We will roll M121 around end of January though to hopefully fix both issues.

**Comment by OrKoN** [comment]
Btw if you use the latest version of Puppeteer, it should be possible to do `npx puppeteer browsers install chrome@120` to install M120 version and then use the executable path the CLI prints to launch the browser.

**Comment by mglasgow** [comment]
Great, thanks for your time and help.
