### ISSUE TITLE
[Bug]: `page.url()` returns an empty string when browser is launched with a starting URL

### ISSUE THREAD

**Issue by JakobJingleheimer** [puppeteer/puppeteer#11677]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-extra';

const browser = await puppeteer.launch({
  args: [
    '--incognito',
    'https://www.example.com',
  ],
});

const [page] = await browser.pages();

console.log('The current address is: "', page.url(), '"');
// The current address is: ""

await page.goto('https://www.example.com');

console.log('The current address is:', page.url());
// The current address is: " https://www.example.com "
```

### Error string

N/A

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Chrome can be launched with a starting URL by supplying it after all the arguments.

### Expectation

`page.url()` return the current value of the address bar (which I confirmed _is_ indeed also the value of `location.href` in the page's browser console).

### Reality

Puppeteer _does_ launch Chrome with that address, but `page.url()` instead returns an empty string.

### Puppeteer version

21.6.1, 21.7.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by OrKoN** [comment]
I am unable to reproduce locally but, in general, the URL should be there once the page finished navigating. `page.goto` waits for navigation and for the page loaded via args there is no way to wait reliably.

**Comment by JakobJingleheimer** [comment]
Gah, sorry, I JUST realised that was the problem 🤦‍♂️

I added

```js
await new Promise((ready) => page.on('load', ready));
```

Just before the `page.url()`, and voila.
