### ISSUE TITLE
chrome for testing 119.0.6045.105 is not working with puppeteer 21.5.2 installation, but 120.0.6099.109 is working fine

### ISSUE THREAD

**Issue by Karthikeyan2752** [puppeteer/puppeteer#11674]
chrome for testing 119.0.6045.105 is not working for me with puppeteer 21.5.2 installation, it shows npm package errors, but 120.0.6099.109 is working fine with same setup, kindly check and update the chromium support page.

**Comment by OrKoN** [comment]
Could you describe what you mean by not working? 119.0.6045.105 is the latest version Puppeteer ships with and 120.0.6099.109 has not been rolled out yet with Puppeteer.
