### ISSUE TITLE
[Feature]: Rename incognito browser contexts

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11686]
### Feature description

We need to remove mentions of incognito because it makes little sense in a cross-browser setting.

We have options how to name it:

1) keep it named `BrowserContext` and only remove incognito in few APIs.
2) rename everything to `Context`
3) rename everything to `UserContext` to align with WebDriver BiDi

**Comment by jrandolf** [comment]
I agree with (3), to better align with ongoing efforts and distinguish it from the old API.

@Lightning00Blade WDYT?

**Comment by Lightning00Blade** [comment]
I agree (3) sounds like the best options considering cross-browser.

**Comment by Lightning00Blade** [comment]
Closing as completed by the by the linked PRs.
