### ISSUE TITLE
getting heap out of memory in eks container when running puppeteer for more than 2000 iterations

### ISSUE THREAD

**Issue by athilshub** [puppeteer/puppeteer#11698]
I want to scan all the pages of a website(having more than 5000 pages), I'm using puppeteer for this and when I run the code it is failing after 2100 iterations, with the error "CALL_AND_RETRY_last Allocation failed, javascript heap out of memory" below is the logic I'm trying to implement This Code is **running in EKS container** and I'm visiting the same URL inside each iteration but  in actual code it will be dynamic

>
>
>     async function siteLevelCrawl(browser, page, baseUrl){    
> 
>     let i = 0
>     while (i<5000) {
>         try {
>             console.log("memory used ",process.memoryUsage().heapUsed, " bytes")
>             console.log(`page ${i}`)
>             i++
>             await page.goto(baseUrl, {
>               waitUntil: "load",
>               timeout: 120000,
>             });
>             const analyze = await new AxeDevToolsPuppeteer(page,{
>                 rulesetID:'wcag2.1'
>             }).analyze();
>         } catch (error) {
>             console.log('Error occurred -***** ', error);
>         }
>     }
>     return page;
>     }
>
>
 

This is the basic operation I want to do, but since it was failing after 2000  I tried disconnecting the browser after 2000 iteration, then I tried closing the page and the browser after 2000 iterations, but nothing worked,

**Comment by OrKoN** [comment]
Could you please provide the complete executable example and test URLs that show the issue?

**Comment by athilshub** [comment]
@OrKoN Sure, 

> const { AxeDevToolsPuppeteer } = require('@axe-devtools/puppeteer');
> const puppeteer = require('puppeteer');
> 
> async function crawl(){
>     const browser = await puppeteer.launch({
>         ignoreHTTPSErrors: true,
>         headless: false,
>         defaultViewport: null,
>         args: [
>             "--disable-gpu",
>             "--disable-dev-shm-usage",
>             "--disable-setuid-sandbox",
>             "--no-sandbox",
>         ]
>     });
>     baseUrl = "https://en.wikipedia.org/wiki/Taj_Mahal";
>     let page = await browser.newPage();
>     await page.setBypassCSP(true);
>     await page.setViewport({ width: 0, height: 0 });
>     await page.goto(baseUrl, {
>         waitUntil: 'load',
>         timeout: 120000
>     });
>     console.log("redirected to base url", baseUrl);
>     await siteLevelCrawl(browser, page, baseUrl);
>     await page.close();
>     await browser.close();    
>  }
> 
> async function siteLevelCrawl(browser, page, baseUrl){    
>     let i = 0
>     while (i<5000) {
>         try {
>             console.log("memory used ",process.memoryUsage().heapUsed, " bytes")
>             console.log(`page ${i}`)
>             i++
>             await page.goto(baseUrl, {
>               waitUntil: "load",
>               timeout: 120000,
>             });
>             const analyze = await new AxeDevToolsPuppeteer(page,{
>                 rulesetID:'wcag2.1'
>             }).analyze();
>         } catch (error) {
>             console.log('Error occurred -***** ', error);
>         }
>     }
> return page;
> }
> 
> crawl();

This is a sample working code
AxeDevToolsPuppeteer is a licensed library I'm using, and **the issue I'm getting only when running in the container,** when I connected with the container support they said memory leakage is there in the code and needs to optimize it

**Comment by OrKoN** [comment]
How much memory is allocated to the container?

**Comment by OrKoN** [comment]
Do you see the same issue without using @axe-devtools/puppeteer?

**Comment by athilshub** [comment]
Issue was with axedevtools, not puppeteer
