### ISSUE TITLE
[Bug]: `install` command skips download even if binary does not exist

### ISSUE THREAD

**Issue by christian-bromann** [puppeteer/puppeteer#11691]
### Minimal, reproducible example

```TypeScript
n/a
```

### Error string

[0-0] Error: spawn /var/folders/6m/29f5wwbn1898q0mtxxnry4qm0000gn/T/chromedriver/mac_arm-120.0.6099.109/chromedriver-mac-arm64/chromedriver ENOENT

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

WebdriverIO uses `@puppeteer/browsers` to setup Firefox and Chrome driver and browser binaries. By default we are storing them in a temporary directory. It seems that sometimes, the `setup` function skips downloading the driver binary even though the executable is not existing, resulting in an error like shown above.

If I remove the `chromedriver` directory and re-run, the download happens as expected.

Reported issues:
- https://github.com/webdriverio/webdriverio/issues/12028#event-11502370201
- https://github.com/webdriverio/webdriverio/issues/12038

### Expectation

I would expect the package not only to check whether the download directory exist but also whether the binary is available.

### Reality

It seems like the program only checks if the directory is in place, e.g. `/var/folders/6m/29f5wwbn1898q0mtxxnry4qm0000gn/T/chromedriver/mac_arm-120.0.6099.109/chromedriver-mac-arm64/` but doesn't actually verify if it contains a binary.

### Puppeteer configuration file (if used)

```TypeScript
n/a
```

### Puppeteer version

21.7.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by OrKoN** [comment]
Btw there is a dedicate template for @puppeteer/browsers https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug%2C%40puppeteer%2Fbrowsers&projects=&template=issue-browsers.yml&title=%5BBug%5D%3A+

**Comment by christian-bromann** [comment]
Thanks @OrKoN 🙏
