### ISSUE TITLE
[Feature]: Create an EsLint rule to check/add Licence headers

### ISSUE THREAD

**Issue by Lightning00Blade** [puppeteer/puppeteer#11701]
Currently when new files are added we need to manually review, verify and add the correct licence header.
Having a rule to automatically do this will save some development time/friction. 
Example of the header that should exits on each file (.ts,.mjs,.cjs)
```js
/**
 * @license
 * Copyright 2018 Google Inc.
 * SPDX-License-Identifier: Apache-2.0
 */
 ```
If the header does not exist a new one should be added with the current year included.

Note: there are some files we would like to ignore as they are adapted from other open source projects and should keep their respective headers.

**Comment by Lightning00Blade** [comment]
We still need to make it an `error`, and and exceptions to this rule so keeping open.

**Comment by OrKoN** [comment]
I have tried it locally and so far the fixer does not fix the issue very well:

- sometimes adds the license multiple times
- does not detect shebang

Let's disable the fixer for now.
