### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by quajo-king** [puppeteer/puppeteer#11712]
### Minimal, reproducible example

```TypeScript
Exit Code: 1(General error) Working directory: C:\xampp\htdocs\laravel\SHELL-POS-V1\public
```

### Error string

Exit Code: 1(General error) Working directory: C:\xampp\htdocs\laravel\SHELL-POS-V1\public Output: ================ Error Output: ================

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

I want it to be fixed

### Reality

The command "node "C:\xampp\htdocs\laravel\SHELL-POS-V1\vendor\spatie\browsershot\src/../bin/browser.cjs" "{""url"":""file:\/\/C:\\Windows\\TEMP\\637109811-0663194001705840237\\index.html"",""action"":""pdf"",""options"":{""path"":""hello.pdf"",""args"":[],""viewport"":{""width"":800,""height"":600},""displayHeaderFooter"":false}}"" failed. Exit Code: 1(General error) Working directory: C:\xampp\htdocs\laravel\SHELL-POS-V1\public Output: ================ Error Output: ================ [1m[43m[30m Puppeteer old Headless deprecation warning:[0m[33m In the near future `headless: true` will default to the new Headless mode for Chrome instead of the old Headless implementation. For more information, please see https://developer.chrome.com/articles/new-headless/. Consider opting in early by passing `headless: "new"` to `puppeteer.launch()` If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.[0m Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or 2. your cache path is incorrectly configured (which is: C:\Windows\system32\config\systemprofile\.cache\puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. at ChromeLauncher.resolveExecutablePath (C:\xampp\htdocs\laravel\SHELL-POS-V1\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:278:27) at ChromeLauncher.executablePath (C:\xampp\htdocs\laravel\SHELL-POS-V1\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:209:25) at ChromeLauncher.computeLaunchArguments (C:\xampp\htdocs\laravel\SHELL-POS-V1\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:103:37) at async ChromeLauncher.launch (C:\xampp\htdocs\laravel\SHELL-POS-V1\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:69:28) at async callChrome (C:\xampp\htdocs\laravel\SHELL-POS-V1\vendor\spatie\browsershot\bin\browser.cjs:91:23)

### Puppeteer version

21.7.0

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.2.1

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
It seems you are not using Pupeteer but Browsershot which is not maintained by us. 
Please review their section on requirements  - https://spatie.be/docs/browsershot/v4/requirements. 
It looks like the browser is not installed, you can try reinstalling Puppeteer which may help.
