### ISSUE TITLE
[Bug]: Camera access isn't allowed in headless mode

### ISSUE THREAD

**Issue by ruelustin5** [puppeteer/puppeteer#11710]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
  // config
  const browser = await puppeteer.launch({
    headless: true,
    userDataDir: "./user_data",
    args: [
      '--use-fake-ui-for-media-stream',
      '--use-fake-device-for-media-stream',
  ],},);

// start the page
  const page = await browser.newPage();
  await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');
  await page.goto('https://web.snapchat.com/');

// click on the camera icon on the site --> not important for the post
  await page.waitForTimeout(10000)
  await page.waitForSelector('#root > div.Fpg8t > div.Vbjsg.WJjwl > div > div > div > div.L3KxA > div.IiObz.VvubJ > div > div > div > div > div > button')
  await page.click('#root > div.Fpg8t > div.Vbjsg.WJjwl > div > div > div > div.L3KxA > div.IiObz.VvubJ > div > div > div > div > div > button')
  await page.waitForSelector('#root > div.Fpg8t > div.Vbjsg.WJjwl > div > div > div > div.L3KxA > div.IiObz.VvubJ > div.UriZL > div > div > div.eCkjw > div.bcYWo > button')
  await page.click('#root > div.Fpg8t > div.Vbjsg.WJjwl > div > div > div > div.L3KxA > div.IiObz.VvubJ > div.UriZL > div > div > div.eCkjw > div.bcYWo > button')

// screenshots to see in headless mode
  for (let step = 0; step < 1000000; step++) {
    await page.waitForTimeout(2000)
    await page.screenshot({ path: 'example.png' });
  }
})();
```

### Error string

In the website (not in console): "Allow your browser to access your camera"

### Bug behavior

- [ ] Flaky
- [x] PDF

### Background

Operation: The following code is just a minimal example on the Snapchat website (since this site requires access to a camera). It takes screenshots every 2 seconds to demonstrate functionality even in headless mode. There's a small snippet of code to activate the camera on the site. I save the profile to avoid having to reconnect each time.

### Expectation

In 'headless: false' mode, everything works perfectly: the camera on the website (Snapchat) is automatically accessible thanks to the args. However, with the same code, except with 'headless: true', it no longer functions. On the site, there's a message: "Allow your browser to access your camera". I don't understand why it works in graphical but not in headless...

### Reality

![example](https://github.com/puppeteer/puppeteer/assets/39460567/70251fa8-9e19-4bb8-8f94-562922447ce5)

### Puppeteer version

21.7.0

### Node version

20.5.1

### Package manager

npm

### Package manager version

9.8.0

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
@ruelustin5 Hello you can read about the differences [here](https://developer.chrome.com/docs/chromium/new-headless).
Can you try using `headless: "new"` ? That should have the same behavior as `headless: false`.

**Comment by OrKoN** [comment]
The new headless mode is not the default. Please give it a try, and re-open if the camera access still does not work.
