### ISSUE TITLE
[Bug]: Generate A4 format PDF become significantly bigger, when upgrade version from puppeteer-core@19.3.0 to puppeteer-core@19.4.0

### ISSUE THREAD

**Issue by duskstar9623** [puppeteer/puppeteer#11719]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer-core');

(async () => {
   const browser = await puppeteer.launch();
   const page = await browser.newPage();
   await page.goto('http://localhost:8080');
   await page.evaluate(() => { window.scrollBy(0, window.innerHeight) });

   try {
      page.pdf({format: 'A4', path: xxx});
   } catch(err) {
      console.log('xxx');
   }
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

In my project, I use _puppeteer-core_ to print local static pages into A4 format PDF. It has always worked fine.

But after I upgrade the version from `19.3.0` to `19.4.0`, for the same page, the generated PDF becomes larger, and the more pages there are, the more obvious the increase is.

I try many other versions, this problem still exists in the latest version.

### Expectation

I expected it could generate a pdf of about the same size as usual at the same situation, just like I've done countless times on >=`puppeteer-core@19.3.0`.

### Reality

In reality, even if the same page, the generated pdf size get bigger.

### Puppeteer version

21.7.0

### Node version

16.20.0

### Package manager

npm

### Package manager version

8.19.4

### Operating system

Linux

**Comment by OrKoN** [comment]
I don't see any related changes in the changelog https://github.com/puppeteer/puppeteer/compare/puppeteer-core-v19.3.0...puppeteer-core-v19.4.0 Do you use the same Chrome version in tests? Which one?

**Comment by duskstar9623** [comment]
> I don't see any related changes in the changelog [puppeteer-core-v19.3.0...puppeteer-core-v19.4.0](https://github.com/puppeteer/puppeteer/compare/puppeteer-core-v19.3.0...puppeteer-core-v19.4.0) Do you use the same Chrome version in tests? Which one?

Hi @OrKoN , yes I use the same Chrome version to compare. I tested on both versions 120.0.6099.225 and 111.0.5563.146.

On each version of Google Chrome, as soon as I upgrade the version of puppeteer-core to 19.4.0, the generated PDF becomes obvious larger.

For example, originally it was 500KB, but when I used `puppeteer-core@19.4.0` to generate it on the same version Chrome and it was 1MB.

**Comment by duskstar9623** [comment]
Hi @OrKoN , just tracking on this. 
Are there any findings ? Thank you very much.

**Comment by OrKoN** [comment]
@duskstar9623 not yet, it would help if you could post CDP logs (`DEBUG=puppeteer:*`) for both runs via gist.github.com so that it's easier to compare.

**Comment by duskstar9623** [comment]
Hi @OrKoN , I find it's the "_headless_" field of launcher options that only apply to Chrome cause this issue.

Once after updating the puppeteer-core version, I encountered this warning, so I set the value of headless to **'new'**. When I set it back to **true**, the size of the generated PDF file returned to normal.
![puppeteer](https://github.com/puppeteer/puppeteer/assets/145466255/65bab575-269f-4626-b2e7-d9fe0d3b6414)

May I ask you the following questions? thank you very much.

Q1: Why does this happen?
Q2: When headless set to true, is there a way to continue to reduce the size of the generated PDF file while the page content remains unchanged?

**Comment by OrKoN** [comment]
@duskstar9623 headless: new (also it is the new default since v22) is the same as the headful browser. To use the old headless mode set `headless: 'shell'` in the latest Puppeteer version. The article linked in the warning explains the difference between the headless modes.
