### ISSUE TITLE
[Feature]: generate a pdf with PDF/A-3 format

### ISSUE THREAD

**Issue by zevenements** [puppeteer/puppeteer#11715]
### Feature description

purpose: generate a pdf in PDF/A-3 format containing informations in xml format.

use case: in order to meet future accounting and invoicing requirements, pdf files must include informations in xml format (https://fnfe-mpe.org/factur-x/factur-x_en/).

https://stackoverflow.com/questions/74489918/does-puppeteer-support-pdf-a-3
https://stackoverflow.com/questions/57186252/does-puppeteer-support-creating-pdf-a

**Comment by Lightning00Blade** [comment]
Puppeteer uses Chrome's PDF printing so this feature request should be on Chromium bug tracker 
Please file a bug at https://bugs.chromium.org/p/chromium/issues/entry (Component: `Internals>Skia>PDF`)
Here is a bug that mentions that Chrome should produce at least PDF/A-3u crbug/1484941.
