### ISSUE TITLE
[Bug]: ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by N1lzh** [puppeteer/puppeteer#11763]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({  
            args: [
                '--disable-web-security',
                '--disable-features=IsolateOrigins',
                '--disable-site-isolation-trials',
                '--no-sandbox',
                '--disable-setuid-sandbox',
            ],
            ignoreDefaultArgs: [
                '--disable-dev-shm-usage'
            ],
            headless: 'new'
        });
        const page = await browser.newPage();
        page
            .on('console', message => 
              console.log(`${message.type().substr(0, 3).toUpperCase()} ${message.text()}`))
            .on('pageerror', ({ message }) => console.log(message))
            .on('response', response =>
              console.log(`${response.status()} ${response.url()}`))
            .on('requestfailed', request =>
              console.log(`${request.failure().errorText} ${request.url()}`))
    
        // Set the viewport size (adjust as needed)
        await page.setViewport({ width: 1920, height: 1102 });
    
        // Navigate to your HTML page
        await page.goto(url);

        const folderPath = path.join(__dirname, '..', `image`);
        await page._client().send('Page.setDownloadBehavior', {
            behavior: 'allow',
            downloadPath: folderPath 
        });

        //initiate the download
        await page.waitForSelector('button#printButton');

        await page.click('button#printButton');
        console.log('Taken steps to download image');
```

### Error string

[27/01/2024-21:27:37.794] [LOG]   ERR Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES [27/01/2024-21:27:37.794] [LOG]   net::ERR_INSUFFICIENT_RESOURCES

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

The problem here is as follows. The leaflet-easyprint assembles the image from numerous smaller images of the map, so it exports many small parts of the map beforehand. This means that many requests are sent in a short time. On my local pc this works fine, but on my VPS there is the problem that chrome seems to rate limit me (I think). I don't know why this problem only occurs on the VPS. Locally I use normal chrome, on the VPS I use the linux debian chromium package. For information, the VPS runs on linux debian, my pc on windows 11.

### Expectation

I expected that the image would be downloaded the same way on my VPS as on my local mashine.

### Reality

In reality chrome rate limits my VPS (I think) and the image cannot be downloaded properly.

### Puppeteer version

21.9.0

### Node version

20.11.0

### Package manager

npm

### Package manager version

10.4.0

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Like you have observed this behavior comes from Chrome itself. From my understanding the issue is running out of memory or disk. Please verify that if that's the case. Also check it the `tmp` folder doesn't have lingering `puppeteer_dev _` folders from when puppeteer fail to close correctly and couldn't clean the temporary user folder.
