### ISSUE TITLE
Unexpected increase in PDF file size / no way to control image quality

### ISSUE THREAD

**Issue by craigdallimore** [puppeteer/puppeteer#1177]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: MacOS 10.12.6
* URLs (if applicable): https://jsfiddle.net/decoy9697/g6vq3kqf/3/embedded/result

**What steps will reproduce the problem?**

With default settings, create a PDF from the above URL

**What is the expected result?**
The PDF filesize would only be slightly larger than the original assets - <4M

**What happens instead?**

The PDF filesize is approximately 31M, approximately 10 times larger than we might expect.

This is unsurprising in some ways - the single image asset in the sample document is 4032 x 5040, I suspect that some upsampling is taking place in order to preserve the fidelity of the original? This is reasonable, but I'd suggest we a way to configure the PDF renderer with quality settings (as per the PNG renderer). If there is such a setting I apologise, I looked but did not find it.

**Comment by masmerino13** [comment]
Any updates? I'm having the same issue.

**Comment by lmartins** [comment]
I've also observed a similar issue, where adding a 700Kb image caused the file to jump from 250Kb to 7.5Mb.

**Comment by aslushnikov** [comment]
@craigdallimore I tried doing the "Save as PDF" in Chrome 63.0.3239.132 and it indeed resulted in a huge pdf.

This doesn't look like a puppeteer issue; I filed this upstream as [crbug.com/801430](https://bugs.chromium.org/p/chromium/issues/detail?id=801430). Closing this in favor of the upstream bug.

**Comment by aslushnikov** [comment]
For the record: upstream bug has been fixed. The fix is available in current tip-of-tree, installable with `npm install puppeteer@next`

**Comment by craigdallimore** [comment]
Thanks folks. We saw a reduction in size from `31M` to `3.1M`!

**Comment by mlcamilli** [comment]
@aslushnikov @craigdallimore so bessides installing puppeteer@next did you also have to update the chromium version that is installed? We have upgraded puppeteer but aren't seeing any reductions in file size

**Comment by craigdallimore** [comment]
@mlcamilli that's right, the revision we had success with was 551292
The linux zip is [here](https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/551292/chrome-linux.zip)

I believe you should be able to find the revision number that pairs with a particular version of puppeteer by inspecting the puppeteer `package.json`. Hope this helps.

**Comment by justjake** [comment]
There is a related issue upstream in Chrome that results in extremely large PDF output for pages containing emoji. See this Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=921585

Printing these Emoji with Chromium on macOS and Linux both results in ~200MB PDFs:


> 😀 😁 😂 🤣 😃 😄 😅 😆 😉 😊 😋 😎 😍 😘 🥰 😗 😙 😚 ☺️ 🙂 🤗 🤩 🤔 🤨 😐 😑 😶 🙄 😏 😣 😥 😮 🤐 😯 😪 😫 😴 😌 😛 😜 😝 🤤 😒 😓 😔 😕 🙃 🤑 😲 ☹️ 🙁 😖 😞 😟 😤 😢 😭 😦 😧 😨 😩 🤯 😬 😰 😱 🥵 🥶 😳 🤪 😵 😡 😠 🤬 😷 🤒 🤕 🤢 🤮 🤧 😇 🤠 🤡 🥳 🥴 🥺 🤥 🤫 🤭 🧐 🤓 😈 👿 👹 👺 💀 👻 👽 🤖 💩 😺 😸 😹 😻 😼 😽 🙀 😿 😾
>
> 🐶 🐱 🐭 🐹 🐰 🦊 🦝 🐻 🐼 🦘 🦡 🐨 🐯 🦁 🐮 🐷 🐽 🐸 🐵 🙈 🙉 🙊 🐒 🐔 🐧 🐦 🐤 🐣 🐥 🦆 🦢 🦅 🦉 🦚 🦜 🦇 🐺 🐗 🐴 🦄 🐝 🐛 🦋 🐌 🐚 🐞 🐜 🦗 🕷 🕸 🦂 🦟 🦠 🐢 🐍 🦎 🦖 🦕 🐙 🦑 🦐 🦀 🐡 🐠 🐟 🐬 🐳 🐋 🦈 🐊 🐅 🐆 🦓 🦍 🐘 🦏 🦛 🐪 🐫 🦙 🦒 🐃 🐂 🐄 🐎 🐖 🐏 🐑 🐐 🦌 🐕 🐩 🐈 🐓 🦃 🕊 🐇 🐁 🐀 🐿 🦔 🐾 🐉 🐲 🌵 🎄 🌲 🌳 🌴 🌱 🌿 ☘️ 🍀 🎍 🎋 🍃 🍂 🍁 🍄 🌾 💐 🌷 🌹 🥀 🌺 🌸 🌼 🌻 🌞 🌝 🌛 🌜 🌚 🌕 🌖 🌗 🌘 🌑 🌒 🌓 🌔 🌙 🌎 🌍 🌏 💫 ⭐️ 🌟 ✨ ⚡️ ☄️ 💥 🔥 🌪 🌈 ☀️ 🌤 ⛅️ 🌥 ☁️ 🌦 🌧 ⛈ 🌩 🌨 ❄️ ☃️ ⛄️ 🌬 💨 💧 💦 ☔️ ☂️ 🌊 🌫
>
> 👶 👧 🧒 👦 👩 🧑 👨 👵 🧓 👴 👲 👳‍♀️ 👳‍♂️ 🧕 🧔 👱‍♂️ 👱‍♀️ 👨‍🦰 👩‍🦰 👨‍🦱 👩‍🦱 👨‍🦲 👩‍🦲 👨‍🦳 👩‍🦳 🦸‍♀️ 🦸‍♂️ 🦹‍♀️ 🦹‍♂️ 👮‍♀️ 👮‍♂️ 👷‍♀️ 👷‍♂️ 💂‍♀️ 💂‍♂️ 🕵️‍♀️ 🕵️‍♂️ 👩‍⚕️ 👨‍⚕️ 👩‍🌾 👨‍🌾 👩‍🍳 👨‍🍳 👩‍🎓 👨‍🎓 👩‍🎤 👨‍🎤 👩‍🏫 👨‍🏫 👩‍🏭 👨‍🏭 👩‍💻 👨‍💻 👩‍💼 👨‍💼 👩‍🔧 👨‍🔧 👩‍🔬 👨‍🔬 👩‍🎨 👨‍🎨 👩‍🚒 👨‍🚒 👩‍✈️ 👨‍✈️ 👩‍🚀 👨‍🚀 👩‍⚖️ 👨‍⚖️ 👰 🤵 👸 🤴 🤶 🎅 🧙‍♀️ 🧙‍♂️ 🧝‍♀️ 🧝‍♂️ 🧛‍♀️ 🧛‍♂️ 🧟‍♀️ 🧟‍♂️ 🧞‍♀️ 🧞‍♂️ 🧜‍♀️ 🧜‍♂️ 🧚‍♀️ 🧚‍♂️ 👼 🤰 🤱 🙇‍♀️ 🙇‍♂️ 💁‍♀️ 💁‍♂️ 🙅‍♀️ 🙅‍♂️ 🙆‍♀️ 🙆‍♂️ 🙋‍♀️ 🙋‍♂️ 🤦‍♀️ 🤦‍♂️ 🤷‍♀️ 🤷‍♂️ 🙎‍♀️ 🙎‍♂️ 🙍‍♀️ 🙍‍♂️ 💇‍♀️ 💇‍♂️ 💆‍♀️ 💆‍♂️ 🧖‍♀️ 🧖‍♂️ 💅 🤳 💃 🕺 👯‍♀️ 👯‍♂️ 🕴 🚶‍♀️ 🚶‍♂️ 🏃‍♀️ 🏃‍♂️ 👫 👭 👬 💑 👩‍❤️‍👩 👨‍❤️‍👨 💏 👩‍❤️‍💋‍👩 👨‍❤️‍💋‍👨 👪 👨‍👩‍👧 👨‍👩‍👧‍👦 👨‍👩‍👦‍👦 👨‍👩‍👧‍👧 👩‍👩‍👦 👩‍👩‍👧 👩‍👩‍👧‍👦 👩‍👩‍👦‍👦 👩‍👩‍👧‍👧 👨‍👨‍👦 👨‍👨‍👧 👨‍👨‍👧‍👦 👨‍👨‍👦‍👦 👨‍👨‍👧‍👧 👩‍👦 👩‍👧 👩‍👧‍👦 👩‍👦‍👦 👩‍👧‍👧 👨‍👦 👨‍👧 👨‍👧‍👦 👨‍👦‍👦 👨‍👧‍👧 🤲 👐 🙌 👏 🤝 👍 👎 👊 ✊ 🤛 🤜 🤞 ✌️ 🤟 🤘 👌 👈 👉 👆 👇 ☝️ ✋ 🤚 🖐 🖖 👋 🤙 💪 🦵 🦶 🖕 ✍️ 🙏 💍 💄 💋 👄 👅 👂 👃 👣 👁 👀 🧠 🦴 🦷 🗣 👤 👥

**Comment by leandrit1** [comment]
Yeah, using just a few colorful emojis, the PDF file increases greatly
For now I guess we are satisfied with black and white emoji which keeps the size good
https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoEmoji-Regular.ttf

**Comment by vadimbepro** [comment]
I resolved the issue in my program by removing Google Fonts  from page (fonts.googleapis.com)

**Comment by nishantlnmiit** [comment]
> Thanks folks. We saw a reduction in size from `31M` to `3.1M`!

@conradkirschner  How did you reduce the size ,please help me here.

**Comment by nishantlnmiit** [comment]
> For the record: upstream bug has been fixed. The fix is available in current tip-of-tree, installable with `npm install puppeteer@next`

How we can solve this issue , please help me on this.

**Comment by usb248** [comment]
Image of 189ko jump my pdf to 2m..... no way... what did the chromium developers smoke? 
I found a trick.
Put your image into a svg file, chromium does no treatment
