### ISSUE TITLE
[Bug]: Executable path is not properly generated when using `PUPPETEER_BROWSER_REVISION=stable`

### ISSUE THREAD

**Issue by alexandcote** [puppeteer/puppeteer#11781]
### Minimal, reproducible example

```TypeScript
// Set `PUPPETEER_BROWSER_REVISION` to `stable`
// export PUPPETEER_BROWSER_REVISION=stable
// Run `npm install puppeteer --save`

import puppeteer from 'puppeteer'

(async () => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    try {
        await page.goto('https://google.com')
        await browser.close()
    } catch (error) {
        console.log(error)
    }
    await browser.close();
})();
```

### Error string

The executablePath uses `stable` while the path contains the actual browser revision.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

The Executable Path should be generated using the actual installed browser revision.

### Reality

The executable path tries to get the `stable` revision and will never exist.

I was able to temporarily fix the problem using this function:
```ts
async function getExecutablePath() {
  const browsers = await getInstalledBrowsers({
    cacheDir: process.env.PUPPETEER_CACHE_DIR || '',
  });

  if (browsers.length === 0) {
    throw new Error('Could not find a browser to launch');
  }

  const browser = browsers[browsers.length - 1];
  return browser.executablePath;
}
```

### Puppeteer version

21.10.0

### Node version

20.11.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by OrKoN** [comment]
@alexandcote `stable` is not a proper browser revision/version. Puppeteer expects a specific revision, not an alias. Previously, revisions were numeric and nowadays they are version numbers. Puppeteer also expects the user to install the revision that is requested:

```
npx puppeteer browsers install chrome@119.0.6045.105
npx puppeteer browsers install chrome-headless-shell@119.0.6045.105
export PUPPETEER_BROWSER_REVISION=119.0.6045.105
# now any launch function will use 119.0.6045.105 if nothing else is provided via launch arguments
```

**Comment by OrKoN** [comment]
Also, if you need the stable version, we recommend using the version bundled with Puppeteer. Resolving aliases at launch time is unfortunately not very reliable so it is out of scope for Puppeteer for now.

**Comment by alexandcote** [comment]
The weird part is if you only specify `PUPPETEER_BROWSER_REVISION=stable` the stable version is installed properly but the `executablePath` is not generated properly. While you can do `npx puppeteer browsers install chrome@stable` I believe 🤔

**Comment by alexandcote** [comment]
I understand thanks for the context 👍🏻 😄 

Do you see any value in adding a feature to allow consumers to always use the last stable version?

I'm proposing this because when a security issue happens in Chrome, consumers have to wait for a Puppeteer update and update the consumer service (in our case in many different services).

Alternatively, we could install Chrome manually and skip the installation during Puppeteer installation. This required more setup.

What I'm proposing is if `PUPPETEER_BROWSER_REVISION=stable|latest|beta` is used, Puppeteer install the browser like it does today in: `<CACHE>/chrome/<DISTRO>-<REVISION>` but create a symlink so `<CACHE>/chrome/<DISTRO>-<stable|latest|beta>` point to the installed revision. This will allow the executable path to work properly and will require consumers to only set the PUPPETEER_BROWSER_REVISION to use the stable version.

What do you think 😄 ?

**Comment by OrKoN** [comment]
Good suggestion, I would probably go in the direction of adding metadata to the browser folders though.
