### ISSUE TITLE
Add an option to set data attributes on elements added by the API

### ISSUE THREAD

**Issue by rdeltour** [puppeteer/puppeteer#1179]
It would be useful to be able to set [data attributes](https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute) on `script` and `style` elements added by puppeteer.

For instance:

```js
await page.addScriptTag({
  url: 'https://example.com/script.js',
  attributes: { foo: bar },
});
```
would add the following tag:

```html
<script type="text/javascript" src="https://example.com/script.js" data-foo="bar">
```

For instance, I inject a script that (for a reason) selects all the `script` elements in my pages, but then it selects itself (and its dependencies). I'd like to be able to filter out all the elements added by puppeteer. Having a custom `data-*` attribute would allow me to do that. I hope it makes sense.

**Comment by aslushnikov** [comment]
@rdeltour I'd rather make `addScriptTag` and `addStyleTag` return element handles to the added elements.

I'd be happy to review a PR for this.

**Comment by xg-wang** [comment]
@aslushnikov Hi Andrey, how does the `this.evaluate` work inside `addStyleTag`? 
Seems if I change the code to return the Promise which resolves the generated `HTMLLinkElement` it will end up to be a `{ __jsaction: {} }`

The debug log looks like
```
  puppeteer:session SEND ► {"id":10,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"function addStyleUrl(url) {\n      const link = document.createElement('link');\n      link.rel = 'stylesheet';\n      link.href = url;\n      const promise = new Promise(res => {\n        link.onload = function() {\n          res(this);\n        };\n      });\n      document.head.appendChild(link);\n      console.log('link: ', link);\n      return promise;\n    }","executionContextId":2,"arguments":[{"value":"https://unpkg.com/basscss@8.0.2/css/basscss.min.css"}],"returnByValue":false,"awaitPromise":true}} +0ms
  puppeteer:session ◀ RECV {"id":10,"result":{"result":{"type":"object","subtype":"node","className":"HTMLLinkElement","description":"link","objectId":"{\"injectedScriptId\":2,\"id\":2}"}}} +49ms
{ type: 'object',
  subtype: 'node',
  className: 'HTMLLinkElement',
  description: 'link',
  objectId: '{"injectedScriptId":2,"id":2}' }
  puppeteer:session SEND ► {"id":12,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"function() { return this; }","objectId":"{\"injectedScriptId\":2,\"id\":2}","returnByValue":true,"awaitPromise":true}} +2ms
  puppeteer:session ◀ RECV {"id":12,"result":{"result":{"type":"object","value":{"__jsaction":{}}}}} +1ms
```
I would expect the result in RECV 10 to be the returned value of the promise in the stringified function, however it is an object, and is not returned by `addStyleTag`. Do you have any idea how to return the added element handle?

The simple example I used
```
'use strict';

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch({headless: true});
const page = await browser.newPage();
await page.goto('https://google.com');

const res = await page.addStyleTag({
  url: 'https://unpkg.com/basscss@8.0.2/css/basscss.min.css'
});
console.log(res);

await browser.close();

})();
```
also changed the [promise](https://github.com/GoogleChrome/puppeteer/blob/master/lib/FrameManager.js#L393) to resolve the link element.

**Comment by aslushnikov** [comment]
@xg-wang Hi Xingan! 

You should use [`this.evaluateHandle`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatehandlepagefunction-args) instead of [`this.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args). The difference is that `evaluateHandle` would return a JSHandle, whereas `evaluate` will attempt to serialize the results value.

**Comment by rdeltour** [comment]
Awesome, thanks @xg-wang!

**Comment by babakfp** [comment]
😐😐😐😐
So what is the result? Can we add a freaking custom attribute to a script/style tag or not?
Why the documentation sucks? There is no clear explanation on how to do anything! No proper explanations!
