### ISSUE TITLE
page.evaluate should accept a string as an argument

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#118]
^

**Comment by aslushnikov** [comment]
I'm curious how's passing a string simpler than having an arrow function?
Arrow function gets syntax highlighted and only a few characters longer. Given an ide/clever editor, it would be harder to do a typo.

```js
page.evaluate(() => document.innerHTML)
```

vs.
```js
page.evaluate('document.innerHTML');
```

cc @dgozman who understands why strings are nice

**Comment by JoelEinbinder** [comment]
What happens when I want to use typescript or something similar? It will throw errors all over the function.

Additionally I've had a function I want to reuse. I want to pass another function into it as an argument. I can't composite it without doing my own `function.toString()` as an argument and `eval`ing it. I'd rather just composite strings, I know how that works.

**Comment by aslushnikov** [comment]
@JoelEinbinder interesting! Wouldn't it just work if you write the function in typescript? Typescript would transpile it into javascript like everything else.

**Comment by JoelEinbinder** [comment]
But I don't have types for the page context. I'm writing in node. Also variable names will get mixed up.

**Comment by JoelEinbinder** [comment]
We should make `awaitPromise` on runtime evaluate accept non-promise return types. That way we won't have to wrap all of our evaluates in `Promise.resolve`, and can accept strings ending in comments, with source urls, etc.

**Comment by aslushnikov** [comment]
@JoelEinbinder It looks like the `awaitPromise` flag in `Runtime.evaluate` is not experimental and thus can't be changed (@ak239 knows for sure). However, we can implement the behavior in two hops, using the `Runtime.awaitPromise` method – if we really need it.

The typescript example is convincing, thanks.
