### ISSUE TITLE
page.setRequestInterception is null

### ISSUE THREAD

**Issue by tryer3000** [puppeteer/puppeteer#1180]
### Steps to reproduce
**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: ubuntu 17.04

**What steps will reproduce the problem?**
```
    await page.setRequestInterception(true);
```

**What is the expected result?**
API should be invoked

**What happens instead?**
Exception throwed
```
Message:                                                                      
    Failed: page.setRequestInterception is not a function
```

**Comment by panthony** [comment]
@tryer3000 On the `0.12.0`, this method is called `setRequestInterceptionEnabled`.

https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#pagesetrequestinterceptionenabledvalue

**Comment by tpickett** [comment]
the API docs have been updated to reflect the 0.13.0-alpha API Docs. this is probably the source of the confusion.

Also when setting this( page.setRequestInterception ) to false on the 0.13.0-alpa (which is master, why alpha is in master is a mystery...) it causes all kinds of errors about not being set.

**Comment by tryer3000** [comment]
@tpickett Thank you  for your explanation.
