### ISSUE TITLE
[Bug]: i  use puppeteer-core in  Chrome extension ,but is has some question: "urlToHttpOptions" is not exported by "__vite-browser-external", imported by "node_modules/@puppeteer/browsers/lib/esm/httpUtil.js".

### ISSUE THREAD

**Issue by guobcKf** [puppeteer/puppeteer#11809]
### Minimal, reproducible example

```TypeScript
import { onMessage } from "webext-bridge/devtools";
import puppeteer from 'puppeteer-core';
onMessage('init-pop',async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto(chrome.runtime.getURL('popup/index.html'));
})
```

### Error string

"urlToHttpOptions" is not exported by "__vite-browser-external", imported by "node_modules/@puppeteer/browsers/lib/esm/httpUtil.js".

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

可以解决此问题

### Reality

build is error

### Puppeteer configuration file (if used)

```TypeScript
{
  "name": "vue-chrome-ext",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview",
    "watch-build": "vite --watch build",
    "watch-json": "node watch.mjs"
  },
  "dependencies": {
    "naive-ui": "^2.37.3",
    "pinia": "^2.1.7",
    "puppeteer-core": "^21.10.0",
    "puppeteer-extension-transport": "^0.0.6",
    "vue": "^3.3.11",
    "webext-bridge": "^6.0.1"
  },
  "devDependencies": {
    "@types/node": "^20.11.6",
    "@vitejs/plugin-vue": "^4.5.2",
    "chrome-types": "^0.1.253",
    "less": "^4.2.0",
    "rollup-plugin-copy": "^3.5.0",
    "typescript": "^5.2.2",
    "vite": "^5.0.8",
    "vue-tsc": "^1.8.25"
  }
}
```

### Puppeteer version

^21.10.0

### Node version

v16.20.2

### Package manager

npm

### Package manager version

vite ^5.0.8

### Operating system

Windows

**Comment by OrKoN** [comment]
Could you clarify what the Puppeteer issue is? It looks like a problem caused by vite?

**Comment by guobcKf** [comment]
> Could you clarify what the Puppeteer issue is? It looks like a problem caused by vite?

yes，i have use puppeteer-extension-transport and puppeteer-core@^13.7.0 in chrome extensions,but i think it is to old,if i can use most new?

**Comment by guobcKf** [comment]
> Could you clarify what the Puppeteer issue is? It looks like a problem caused by vite?

hello,I have  some question.When I simulate a click to open a new page. After connecting to it, the page method obtained will not respond and it will stay stuck there.

**Comment by OrKoN** [comment]
I think puppeteer-extension-transport is not compatible with the latest Puppeteer versions. See discussion with https://github.com/puppeteer/puppeteer/issues/12022 If you encounter a bug, please file a new issue with a minimal reproducible example but note that we are not able to support old versions for that use case.
