### ISSUE TITLE
[Feature]: Support listing and/or searching with @puppeteer/browsers

### ISSUE THREAD

**Issue by pimterry** [puppeteer/puppeteer#11808]
### Feature description

You can only install a browser via @puppeteer/browsers if you want a latest version, or you know the exact revision. If you're actively trying to test backward compatibility, this isn't very convenient.

It would be very helpful to be able to search for a known browser version somehow. In a perfect world, following patterns of similar tools like npm/fnm/nvm, it would be great to be able to provide a semver range to match against official release versions (`^87`, latest 2017 release, etc).

Right now, as far as I'm aware, the only way to find a specific revision is to manually dig through https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html, which is not a great workflow!

**Comment by OrKoN** [comment]
Currently the following is supported:

```
Examples:
  @puppeteer/browsers install chrome                            Install the latest available build of the Chrome
                                                                browser.
  @puppeteer/browsers install chrome@latest                     Install the latest available build for the Chrome
                                                                browser.
  @puppeteer/browsers install chrome@canary                     Install the latest available build for the Chrome Canary
                                                                browser.
  @puppeteer/browsers install chrome@115                        Install the latest available build for Chrome 115.
  @puppeteer/browsers install chromedriver@canary               Install the latest available build for ChromeDriver
                                                                Canary.
  @puppeteer/browsers install chromedriver@115                  Install the latest available build for ChromeDriver 115.
  @puppeteer/browsers install chromedriver@115.0.5790           Install the latest available patch (115.0.5790.X) build
                                                                for ChromeDriver.
  @puppeteer/browsers install chrome-headless-shell             Install the latest available chrome-headless-shell
                                                                build.
  @puppeteer/browsers install chrome-headless-shell@beta        Install the latest available chrome-headless-shell build
                                                                corresponding to the Beta channel.
  @puppeteer/browsers install chrome-headless-shell@118         Install the latest available chrome-headless-shell 118
```

So you do not need to know the exact version with `@puppeteer/browsers install chrome@115`, you can use the milestone number. Note that we can only support this for CfT https://github.com/GoogleChromeLabs/chrome-for-testing and there are no plans to support for the chromium snapshots.
