### ISSUE TITLE
[Bug]: console events relies on non-specified property

### ISSUE THREAD

**Issue by sadym-chromium** [puppeteer/puppeteer#11816]
### Minimal, reproducible example

```TypeScript
it('should report console logs', async () => {
    const {page} = await getTestState();

    const [message] = await Promise.all([
      waitEvent(page, 'console'),
      page.evaluate(() => {
        return new Worker(`data:text/javascript,console.log(1)`);
      }),
    ]);
    expect(message.text()).toBe('1');
    expect(message.location()).toEqual({
      url: '',
      lineNumber: 0,
      columnNumber: 8,
    });
  });
```

### Error string

TimeoutError: Waiting for console event timed out.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

When using BiDi, Puppeteer checks [if the `log.entryAdded` event relates to the given page based on `source.context` property](https://github.com/puppeteer/puppeteer/blob/ef0d4419bae1766aa36e49296f81516d2e0e84ac/packages/puppeteer-core/src/bidi/Page.ts#L447). It is not always correct, as [`script.source`](https://w3c.github.io/webdriver-bidi/#type-script-Source) can be `null` for workers. Instead, the `realm` property should be used to check if the event relates to one of the page's associated realms. 

Currently, there is [a temporary solution](https://github.com/GoogleChromeLabs/chromium-bidi/pull/1801) in Chromium BiDi used to overcome this Puppeteer limitation, but this solution diverges from the specification.

### Expectation

If no `log.entryAdded:params.source.context` is provided, as specified in the BiDi spec, emit the log events from workers on the related page.

### Reality

If no `log.entryAdded:params.source.context` is provided, as specified in the BiDi spec, the log events from workers are omitted. This leads to `[worker.spec] Workers should report console logs` and `[worker.spec] Workers should report errors` tests [failures](https://github.com/puppeteer/puppeteer/actions/runs/7723460941/job/21053617583?pr=11795).

### Puppeteer version

21.10.0

### Node version

v18.18.1

### Package manager

npm

### Package manager version

9.8.1

### Operating system

macOS

**Comment by jrandolf** [comment]
Looks resolved.
