### ISSUE TITLE
Browser.newPage() returns null when launch with {headless: false}.

### ISSUE THREAD

**Issue by Magicloud** [puppeteer/puppeteer#1182]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: github master head.
* Platform / OS version: Ubuntu Xenial, Chrome and Chromium both at ver 62.
* URLs (if applicable):http://www.nasdaq.com/zh/symbol/amzn

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Code:
```javascript
// somecode
const browser = await puppeteer.launch({headless: false});
const page = await browser.newPage();
await page.goto('http://www.nasdaq.com/zh/symbol/amzn', {waitUntil: 'domcontentloaded', timeout: 5000});
// somecode
```
2. Error in output:
```
(node:357) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'goto' of null
```
3. What I see in GUI:
Chromium starts. An extra blank tab appears.
That is all.

**What is the expected result?**
New page opening the NASDAQ webpage.

**What happens instead?**
Nothing but error.

**Comment by vsemozhetbyt** [comment]
I cannot reproduce on Windows 7 x64 with master head and this code:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
    await page.goto('http://www.nasdaq.com/zh/symbol/amzn', { waitUntil: 'domcontentloaded', timeout: 5000 });

    console.log(await page.evaluate(() => document.title));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by ebidel** [comment]
I can't reproduce this either.

**Comment by itaditya** [comment]
I'm getting the same error

**Comment by voliva** [comment]
Can we reopen this? I also have the same issue, and it's obviously a `.newPage()` returning a null. Let's try to find out what's causing this?

In my case:
* Running with default `executablePath` runs Ok in both headless `true` and `false`
* Running with `executablePath: '/opt/google/chrome/chrome'`:
  - Running with `headless: true` gets stuck at `await browser.newPage();` forever
  - Running with `headless: false` on the spawned browser it creates a new tab with `about:blank` and the value returned is `null` (crashing on the next `page.goto`)

My environment:
`/opt/google/chrome/chrome`: Chrome 62.0.3202.94
Without specifying chrome version, it runs chromium in `./node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome`. This is version Chromium 64.0.3264.0

Note: Chrome 62.0 is the last stable version of chrome for linux - 63.0 is in beta and it crashes inside `.browser.newPage()` with a different error.

I have linux 4.13.0-17-generic with Ubuntu 17.10

**Comment by ebidel** [comment]
AH. There have been changes since Chrome 62 that Puppeteer requires now. This is one of the primary reasons we bundle a version of Chromium, so that it's guaranteed to work with the API. 

Is there a reason you can't use the bundled version?

**Comment by itaditya** [comment]
@ebidel, yes there was an issue with the bundled chromium browser. It always shows aw snap!

**Comment by ebidel** [comment]
@itaditya what version of puppeteer, platform, etc are you using.  @voliva's report says that the bundled version is working with master and Chromium 64.0.3264.0,  linux 4.13.0-17-generic with Ubuntu 17.10.

Also what code snippet reproduces the issue?

**Comment by voliva** [comment]
In my case, the bundled chromium doesn't support widevine media extensions... I guess I'll have to wait for Chrome to be updated then :)

**Comment by itaditya** [comment]
@ebidel : 

System Info - 
Windows 7 32-bit

Node - v8.4.0
Puppeteer - v0.13.0
Chromium - win32-515411

Also when I open chromium from \node_modules\puppeteer\.local-chromium\win32-515411\chrome-win32, I get this 
![image](https://user-images.githubusercontent.com/15871340/33512995-30f60b66-d760-11e7-800f-c03efca78a54.png)

**Comment by jasper2virtual** [comment]
@ebidel 
System Info -
Windows 7 32-bit
Node - v8.7.0
Puppeteer - v0.13.0
use bundle chromium - node_modules\puppeteer\.local-chromium\win32-515411\chrome-win32\chrome.exe

I run this code 
```javascript
const puppeteer = require('puppeteer');

async function run() {
  const browser = await puppeteer.launch({
    headless : false
  });
  const page = await browser.newPage();
  
  await page.goto('https://github.com');
  await page.screenshot({ path: 'screenshots/github.png' });
  
  browser.close();
}
console.log(puppeteer.executablePath());
run();

```
get this screen
![image](https://user-images.githubusercontent.com/17800518/33547193-43ffe2bc-d91e-11e7-99b1-60cc12dbaede.png)
The node hang, I close the chromium, then the node return 
```
(node:6292) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.enable): Target closed.
(node:6292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/17800518/33547306-a8125d20-d91e-11e7-8d6e-74633b2ca9ad.png)

If I set ```headless : true``` , the node hang forever ( as I cannot close the chromium )

**Comment by itaditya** [comment]
@ebidel can you reopen this issue?

**Comment by ghost** [comment]
@jasper2virtual 
have the same problem.
Windows 8.1 32-bit gives "Aw, Snap" whatever I do in chromium - open new page ect. (the same config works on another pc win10 64 bit but I don't know the version).
Will check the version and report
Even if i open the settings/about page i get Aw Snap.

Not actually a puppeteer problem, when i run chromium directly(from utils local-chromium folder), my tablet is stuck and i get a black chromium welcome screen., Checked the version it's 32bit, 

Replaced the chromium puppeteer folder with a downloaded one and it starts/renders the page

**Comment by sebastienros** [comment]
I have the same issue when running from PowerShell, but not when using cmd. I tried with the local chromium and also by setting `executablePath` to the installed chrome with the same result.
