### ISSUE TITLE
[Bug]: console.log() misses some output Puppeteer versions > 21.1.1

### ISSUE THREAD

**Issue by cantonalex** [puppeteer/puppeteer#11845]
### Minimal, reproducible example

```TypeScript
Using Chrome extension that sends logs directly to browser works in any version under 21.1.1 

` page.on('console', (message) => console.log(`Console: ${message.text()}`));`
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Trying to log from Chrome extension in puppeteer works in versions under 21.1.1

### Expectation

log the logs in puppeteer, i can see them in chrome devtools

### Reality

missing from puppeteer logs

### Puppeteer version

22.0.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

?

### Operating system

macOS

**Comment by cantonalex** [comment]
[puppeteer-script-main.zip](https://github.com/puppeteer/puppeteer/files/14181250/puppeteer-script-main.zip)
Here it is as you can see on v21.1.1 works fine and anything above it does not.

**Comment by OrKoN** [comment]
@cantonalex please provide a minimal reproducible example. Also note that not everything shown in DevTools console is a console message (for example, errors are not console messages `page.on('error', ...)`) and what's output might change depending on the browser version.

**Comment by cantonalex** [comment]
@OrKoN i provided the file above
