### ISSUE TITLE
[Bug]:  Protocol error (Network.emulateNetworkConditions): Invalid parameters Failed to deserialize params.downloadThroughput - BINDINGS: mandatory field missing at position 26"

### ISSUE THREAD

**Issue by dielit66** [puppeteer/puppeteer#11841]
### Minimal, reproducible example

```JavaScript
const puppeteer = require('puppeteer')


async function start(){
  const browser = await puppeteer.launch({
    headless: "new" 
  })
  const page = await browser.newPage();
  await page.setCacheEnabled(false);

  await page.emulateNetworkConditions({
    downloadThroughput: 2500,
    uploadThroughput: 2500,  
    latency: 0 
  });
}

start()
```
### Error string

ProtocolError: Protocol error (Network.emulateNetworkConditions): Invalid parameters Failed to deserialize params.downloadThroughput - BINDINGS: mandatory field missing at position 26

### Expectation

Emulate a slow network

### Reality

error  Protocol error (Network.emulateNetworkConditions): Invalid parameters Failed to deserialize params.downloadThroughput - BINDINGS: mandatory field missing at position 26"

### Puppeteer configuration file (if used)

{
  "dependencies": {
    "puppeteer": "^21.11.0"
  }
}

### Puppeteer version

^21.11.0

### Node version

v20.11.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by OrKoN** [comment]
The correct property names are 

```
  await page.emulateNetworkConditions({
    download: 2500,
    upload: 2500,  
    latency: 0 
  });
```

**Comment by xxlifestyle** [comment]
> The correct property names are
> 
> ```
>   await page.emulateNetworkConditions({
>     download: 2500,
>     upload: 2500,  
>     latency: 0 
>   });
> ```

Thank you! Are the values specified for download and upload in bytes?

**Comment by OrKoN** [comment]
@xxlifestyle yes, it's bytes/sec for download/upload and ms for latency

**Comment by OrKoN** [comment]
See https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/NetworkManager.ts#L38 but it looks like the documentation website generator has not picked it up. It should show up here too https://pptr.dev/api/puppeteer.networkconditions once we fix it.
