### ISSUE TITLE
[Bug]: simply navigating to specific site seems to trigger continual 1200% CPU usage

### ISSUE THREAD

**Issue by Mattwmaster58** [puppeteer/puppeteer#11858]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch()//{headless: true});
  const page = await browser.newPage();

  await page.goto('https://orasis-industries.com/');
  await page.waitForTimeout(1000000);
  await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

- When opening this site in a headless Chrome instance, CPU usage rises and stays at 1200% until the site is navigated away from. 
- With {headless: true}, normal CPU usage is observed. 
- Normal CPU usage was observed in all the browsers I had installed.
- I tried with multiple Chrome executables in addition to the default revision (1108766) used by puppeteer: v121.0.6167.85-1, v121.0.6167.139,  and v110.0.5481.77. All reproduced this issue.
- https://www.em-spedition.de/ exhibits high CPU, but only for a second. I am not sure if it's related, but I was unable to get any other site to exhibit such high CPU when it was loaded.

### Expectation

CPU usage to less than or equal to that of a headed browsing session.

### Reality

CPU is pinned inordinately high
![image](https://github.com/puppeteer/puppeteer/assets/26337069/70e01dd7-ce72-4656-baaf-42699328e5db)

### Puppeteer version

22.0.0

### Node version

20.5.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Linux 6.7.2-arch1-2

**Comment by OrKoN** [comment]
@Mattwmaster58 is the cpu usage comes from the Node process? or from the browser process? 1200% is probably not possible in Node so perhaps it's a browser issue?

**Comment by OrKoN** [comment]
I am also unable to reproduce high-cpu usage: I have around 40% and that is due to the animations that the page runs. Do you have GPU enabled/configured? It might be that the headless does not detect the GPU and uses software renderer for animations.

**Comment by OrKoN** [comment]
@Mattwmaster58 you could try out the animation disabling options from https://peter.sh/experiments/chromium-command-line-switches/ but I am not sure if it works.

**Comment by Mattwmaster58** [comment]
Regardless, this doesn't seem to be a puppeteer issue per se - closing for now and thank you for the advice

**Comment by Mattwmaster58** [comment]
For reference: The canvas elements I assume were using a software renderer. I used `--disable-3d-apis` to mitigate this issue.
