### ISSUE TITLE
[Bug]: Can't start a browser via 'launch' method without it erroring [Failed to launch the browser process! undefined]

### ISSUE THREAD

**Issue by BannerBomb** [puppeteer/puppeteer#11857]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
```

### Error string

Error: Failed to launch the browser process! Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I am expecting the code to run a browser like normal.

### Reality

It just errors when initializing the `launch` method.

### Puppeteer version

22.0.0

### Node version

21.6.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by OrKoN** [comment]
I am unable to reproduce: perhaps try with the additional argument `'--disable-setuid-sandbox'`? In general, we do not recommend running without sandbox or as a root, please file a crbug.com/new for the headless component if `--no-sandbox` is not working correctly.

**Comment by BannerBomb** [comment]
> --disable-setuid-sandbox

yea, using this flag still comes out with the same error.
