### ISSUE TITLE
[Bug] `should work with history.replaceState()` is flaky in Firefox BiDi

### ISSUE THREAD

**Issue by jrandolf-google** [puppeteer/puppeteer#11854]
See https://github.com/puppeteer/puppeteer/actions/runs/7802574379/job/21280372826#step:11:511

**Comment by whimboo** [comment]
It's hard to say anything based on the log output given that the stack is pretty much not helpful. I would suggest that we close this issue and better track it as usual in the spreadsheet like all the other failures. @jrandolf does that sound ok?

**Comment by jrandolf** [comment]
@whimboo SGTM
