### ISSUE TITLE
Puppeteer unit tests are leaking opened tabs for default context

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#11865]
There are [14 instances in the unit tests](https://github.com/search?q=repo%3Apuppeteer%2Fpuppeteer+browser.newPage%28%29+path%3A%2F%5Etest%5C%2F%2F&type=code) where `browser.newPage()` is called to open a new tab for testing. If something fails in these tests and the test is not able to close this new tab, it will be leaked because [`getTestState()` only closes tabs automatically for the current browser context](https://github.com/puppeteer/puppeteer/blob/7d1541de68348dbc0d05e393d43d2c8b83233bee/test/src/mocha-utils.ts#L213).

As result this causes a huge amount of remaining tabs open for Firefox at the moment while running the tests. And once we reach the situation that the tab scrollbar is shown in Firefox the situation seems to get even worse (should warrant a different bug on our side).

Shouldn't tests by default use the following code?

```
      const {context} = await getTestState();
      const page1 = await context.newPage();
```

CC @OrKoN

**Comment by OrKoN** [comment]
Some occurrences are fine but some probably need to be switch to use the test context such as https://github.com/puppeteer/puppeteer/blob/7d1541de68348dbc0d05e393d43d2c8b83233bee/test/src/page.spec.ts#L47

**Comment by OrKoN** [comment]
10 occurrences in test/src https://github.com/search?q=repo%3Apuppeteer%2Fpuppeteer+browser.newPage%28%29+path%3A%2F%5Etest%5C%2Fsrc%2F&type=code

**Comment by whimboo** [comment]
Thank you for the quick fix!

**Comment by whimboo** [comment]
@OrKoN btw should we try to remove some flaky test expectations to see if that change has helped (see my comment on Matrix for the side-effect in Firefox)?

**Comment by OrKoN** [comment]
yeah, we should try re-enabling some of the flakes, perhaps all of them in a PR and see if some pass
