### ISSUE TITLE
[Bug]: "Browser.setDownloadBehavior" breaks the links on chrome://downloads page and download bubble

### ISSUE THREAD

**Issue by grcode123** [puppeteer/puppeteer#11871]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const timeout = async () => new Promise((r) => setTimeout(r, 1000000));

(async () => {

  const browser = await puppeteer.launch({
    headless: false,
    ignoreDefaultArgs: ["--enable-automation"],
    ignoreHTTPSErrors: true,
    defaultViewport: null,
  });

  const client = await browser.target().createCDPSession();

  client.on("Browser.downloadWillBegin", (event) => {
    console.log("DOWNLOAD_STARTED");
  });

  client.on("Browser.downloadProgress", (event) => {
    if (event.state == "completed") {
      console.log("****DOWNLOAD_COMPLETED");
    }
  });

  await client.send("Browser.setDownloadBehavior", {
    behavior: "default",
    eventsEnabled: true,
  });

  const defaultContext = browser.defaultBrowserContext();

  const pages = await defaultContext.pages();

  const page = await browser.pages[0];

  try {
    await page.goto("https://pasteur.epa.gov/uploads/10.23719/1528686/SupplyChainGHGEmissionFactors_v1.2_NAICS_CO2e_USD2021.csv");
  } catch (err) {
    console.error(err);
  }

  await timeout();

 // Because we are running in the non-headless mode manually click on the downloaded file

  await browser.close();

  process.exit(0);

})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Basically, unable to open downloaded files from chrome://downloads page (downloads manager page). Links and buttons are not clickable. The same issue when I click on the download bubble or panel at the bottom (for old versions) . It only happens when the download behavior is set to enable download event listeners.
```
await client.send("Browser.setDownloadBehavior", {
    behavior: "default",
    eventsEnabled: true,
  });
```

Download bubble screenshot:
![_13](https://github.com/puppeteer/puppeteer/assets/6558050/241acfde-60fd-4531-bf8a-fc9c9a982207)

Download manager:
![_12](https://github.com/puppeteer/puppeteer/assets/6558050/5cd3a6b6-5d5d-4aae-8c46-7fe837958561)

When no download listeners are set the clicking works fine on chrome://downloads and other places.
Able to reproduce in 19.6.0 as well on the lastest 22.0.0
Also, reproducible on Mac and Windows.

### Expectation

Should be able to click on for ex. "Show in Finder" or click on the filename to open the downloaded file.

### Reality

Links "Show in Finder", folder icon, open icon are not clickable

### Puppeteer version

22.0.0

### Node version

18.19.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by OrKoN** [comment]
Interesting behavior, it looks like a browser bug or perhaps a security measure. Puppeteer does not support this functionality yet, so perhaps you could file this issue at crbug.com/new (component Chromium > Platform > DevTools > Platform)? Perhaps someone there knows if it is expected behavior.
