### ISSUE TITLE
[Bug]: Class extends value undefined is not a constructor or null when importing

### ISSUE THREAD

**Issue by Anay-v2** [puppeteer/puppeteer#11881]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

(async () => {
  // Launch the browser
  const browser = await puppeteer.launch();

  // Create a page
  const page = await browser.newPage();

  // Go to your site
  await page.goto('YOUR_SITE');

  // Query for an element handle.
  const element = await page.waitForSelector('div > .class-name');

  // Do something with element...
  await element.click(); // Just an example.

  // Dispose of handle
  await element.dispose();

  // Close browser.
  await browser.close();
})();
```

### Error string

TypeError: Class extends value undefined is not a constructor or null at ScreenRecorder.ts:252:10 at ScreenRecorder.ts:220:13

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to make a web scraper using puppeteer and vite but whenever I use puppeteer I get this error.

### Expectation

I expected it to properly run puppeteer and go to the web pages I wanted it to

### Reality

In reality, it just throws the error: 
```
TypeError: Class extends value undefined is not a constructor or null
    at ScreenRecorder.ts:252:10
    at ScreenRecorder.ts:220:13
```

### Puppeteer version

22.0.0

### Node version

18.12.1

### Package manager

pnpm

### Package manager version

8.1.0

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not able to reproduce. Could you please try with npm and make sure that the node version is 18.18.0+?

**Comment by Anay-v2** [comment]
![image](https://github.com/puppeteer/puppeteer/assets/87125465/44cd9b32-e5ef-4c71-a219-bb450088ada8)
![image](https://github.com/puppeteer/puppeteer/assets/87125465/ba9fc996-9750-4a6f-9a1b-c97eb19eacc5)
Still not working 🤷🏿

**Comment by OrKoN** [comment]
@Anay-v2 Puppeteer is primarily for NodeJS and looks like you try to bundle it using Vite to run in the browser? It does not look like Vite does it correctly. I would recommend asking on StackOverflow how to solve it.
