### ISSUE TITLE
[Bug]: Browser process 3261 onExit, not working when run in Docker container

### ISSUE THREAD

**Issue by lancejpollard** [puppeteer/puppeteer#11889]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.screenshot({ path: 'google.png' });

  await browser.close();
})();
```

### Error string

Browser process 3261 onExit

### Bug behavior

- [x] Puppeteer hangs at `puppeteer.launch()` in JS

### Background

I am running in a docker container with nodejs installed, using this command, but it just hangs at the `puppeteer.launch()` JS call:

```
docker run -v $(pwd):/home/app --platform linux/amd64 -e PORT=4000 --name foobar -i -t -p 4000:4000 myorg/foobar
```

I tried running like this, but didn't help:

```
docker run --rm --security-opt seccomp=unconfined --shm-size=2G --user root  \
  -v $(pwd):/home/app --platform linux/amd64 -e PORT=4000 --name foobar -i -t -p 4000:4000 myorg/foobar
```

I am seeing this in my logs:

```
puppeteer:browsers:launcher Launching /root/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome
  --allow-pre-commit-input
  --disable-background-networking
  --disable-background-timer-throttling
  --disable-backgrounding-occluded-windows
  --disable-breakpad
  --disable-client-side-phishing-detection
  --disable-component-update
  --disable-dev-shm-usage
  --disable-field-trial-config
  --disable-hang-monitor
  --disable-infobars
  --disable-ipc-flooding-protection
  --disable-popup-blocking
  --disable-prompt-on-repost
  --disable-renderer-backgrounding
  --disable-search-engine-choice-screen
  --disable-sync
  --enable-automation
  --export-tagged-pdf
  --generate-pdf-document-outline
  --force-color-profile=srgb
  --metrics-recording-only
  --no-first-run
  --password-store=basic
  --use-mock-keychain
  --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold
  --enable-features=NetworkServiceInProcess2
  --user-data-dir=/tmp/puppeteer_dev_profile-JLAGWm
  --headless=new
  --hide-scrollbars
  --mute-audio about:blank
  --disable-blink-features=AutomationControlled
  --remote-debugging-port=0
{ detached: true, env: {}, stdio: [ 'pipe', 'ignore', 'pipe' ] }
puppeteer:browsers:launcher Launched 3261
puppeteer:browsers:launcher Browser process 3261 onExit
```

Cross-posting from here: https://stackoverflow.com/questions/77978928/how-to-run-puppeteer-in-docker-linux-container-getting-browser-process-3261-on

I tried following https://dev.to/cloudx/how-to-use-puppeteer-inside-a-docker-container-568c and adding this to my Dockerfile, but no go.

```
# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update
RUN apt-get install gnupg wget -y && \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
  apt-get update && \
  apt-get install google-chrome-stable -y --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*

# With and without this commented in/out
# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
```

### Expectation

I expect to be able to launch a headless browser in amd Linux ubuntu:noble Docker image/container. Here is my full [Dockerfile](https://github.com/termsurf/task/blob/make/Dockerfile). Well actually that is my base image, I then install the `pnpm install` and setup my express app in another.

Within the docker container, I first start a Node.js express app. Then in a REST API endpoint, I call `const browser = await puppeteer.launch()` and do my logic to render a PDF. It just hangs at the `puppeteer.launch()` call though, doesn't move past that. No errors or other logs.

### Reality

What actually happens is it just hangs at the `await puppeteer.launch()` call in JavaScript/TypeScript. It doesn't move beyond that. No logs or anything, beyond what I showed above.

### Puppeteer version

22.0.0

### Node version

20.11.0

### Package manager

pnpm

### Package manager version

8.15.1

### Operating system

Linux

**Comment by lancejpollard** [comment]
Did you run this in a docker container? I doubt it.

**Comment by lancejpollard** [comment]
I was able to get it working locally adding the `--no-sandbox` flag. How do I get it working without that, without running with the privileged user according to https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker ? Using the Docker image user causes a ton of things in my existing docker image to break, any recommendations?

**Comment by OrKoN** [comment]
You can try the following alternatives to configuring the sandbox https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox Also you can try the Docker image we publish that does not use the root user https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer

**Comment by lancejpollard** [comment]
@OrKoN you need to use `cap-add` like described here? https://pptr.dev/guides/docker

Does this mean we can't use puppeteer on google cloud run?

https://stackoverflow.com/questions/57040944/google-cloud-run-and-system-capabilities

**Comment by OrKoN** [comment]
The capability is required for our Docker image. But perhaps it is optional if you configure the sandbox in this way https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#alternative-setup-setuid-sandbox ?

**Comment by OrKoN** [comment]
You could use `dumpio: true` launch argument to see the browser logs. Also, try without using the extra plugins first.

**Comment by lancejpollard** [comment]
@OrKoN I tried without already, same problem, it just hangs. Do you know why it might hang? Locally I get this:

Locally at that point, I get this:


```
puppeteer-extra-plugin:user-data-dir created custom dir /tmp/puppeteer_dev_profile-W9V5BD
puppeteer-extra-plugin:user-data-dir Wrote file /tmp/puppeteer_dev_profile-W9V5BD/Default/Preferences
puppeteer:browsers:launcher Launching /root/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --disable-dev-shm-usage --disable-field-trial-config --disable-hang-monitor --disable-infobars --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --export-tagged-pdf --generate-pdf-document-outline --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold --enable-features=NetworkServiceInProcess2 --user-data-dir=/tmp/puppeteer_dev_profile-W9V5BD --headless=new --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-blink-features=AutomationControlled --remote-debugging-port=0 { detached: true, env: {}, stdio: [ 'pipe', 'ignore', 'pipe' ] }
puppeteer:browsers:launcher Launched 141
...lots more puppeteer logs showing it works
```

**Comment by lancejpollard** [comment]
Also, this is after changing my dockerfile to be close to yours, like this:

```Dockerfile
# this base image has tons of CLI tools installed on it which I need.
FROM --platform=linux/amd64 ghcr.io/myorg/myrepo:latest

ENV NODE_ENV development
RUN mkdir -p /home/app
WORKDIR /home/app
ENV PORT 8080
COPY *.yaml ./
COPY *.json ./

RUN apt-get update \
  && apt-get install -y wget gnupg \
  && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

RUN pnpm install && groupadd -r app && useradd -r -g app -G audio,video app \
  && mkdir -p /home/app/Downloads \
  && chown -R app:app /home/app

USER app

COPY code/ code
RUN pnpm make
EXPOSE ${PORT}
CMD [ "sh", "-c", "pnpm host"]
```

**Comment by OrKoN** [comment]
Could there be a cpu architecture mismatch between the host and the docker container?

**Comment by lancejpollard** [comment]
@OrKoN on google cloud run you mean (architecture mismatch)? No the image works otherwise and is the correct amd64 linux ubuntu:noble image google cloud recommended I am pretty sure. It works for everything else. For example, I can run the `fontforge` CLI tool from within my Node.js app on Google Cloud Run. Would I be able to do that if there was an architecture mismatch do you think? I don't know that much about architectures.

My puppeteer code is basically this now (don't mind the caching, that is premature optimization since it takes a few seconds to start puppeteer):

```ts
import { Browser } from 'puppeteer'
import puppeteer from 'puppeteer'
import __dirname from '~/code/tool/shared/directory.js'
// add stealth plugin and use defaults (all evasion techniques)
// import StealthPlugin from 'puppeteer-extra-plugin-stealth'
import locateChrome from 'locate-chrome'

// puppeteer.use(StealthPlugin())

// https://github.com/lancejpollard/resilient-puppeteer.js/blob/make/index.js

export type PuppeteerCacheItem = {
  active: boolean
  browser: Browser
  proxy?: string
}

const CACHE: Array<PuppeteerCacheItem> = []

export function inactivateBrowser(b: Browser) {
  const item = CACHE.find(x => x.browser === b)

  if (item) {
    item.active = false
  }
}

export async function closeAllBrowsers() {
  for (const item of CACHE) {
    await item.browser.close()
  }
}

export async function getBrowser(proxy?: string, headless = true) {
  const b = CACHE.find(item => {
    if (item.active) {
      return false
    }

    if (proxy) {
      return item.proxy === proxy
    } else if (item.proxy) {
      return false
    }

    return true
  })

  if (b) {
    return b.browser
  }

  // const executablePath = await locateChrome()

  const config: Record<string, any> = {
    headless,
    args: ['--no-sandbox'], // will remove when this at least works.
    // executablePath,
  }
  const item: Record<string, any> = { active: true, proxy }

  if (proxy) {
    config.push(`--proxy-server=${proxy}`)
  }

  // disable user-data-dir
  // config.push('--user-data-dir')

  // HANGS HERE, NO LOGS OF ANY KIND
  item.browser = await puppeteer.launch({
    ...config,
    dumpio: true,
  })

  CACHE.push(item as PuppeteerCacheItem)

  return item.browser as Browser
}
```

## Questions

1. Have you all deployed successfully to Google Cloud (or Google Cloud Run specifically)?
2. I don't think there is a way to do [this](https://pptr.dev/guides/docker) and set `--cap-add=SYS_ADMIN` on Google Cloud Run, I saw that in some StackOverflow post, see https://stackoverflow.com/a/57043978/169992. Is that going to be a problem? If so, does that mean we can't use puppeteer on Google Cloud Run?
3. I'm not getting any `puppeteer` logs after removing the puppeteer-extra and stealth stuff, even though I added `dumpio: true` like the above shows. What should I be seeing?
4. Is my chowned `app` user correct?

**Comment by OrKoN** [comment]
Dumpio: true should log to stdout at least the `DevTools listening on ws://...` message and perhaps more if something goes wrong. 

1. Have you all deployed successfully to Google Cloud (or Google Cloud Run specifically)?

We don't test with Google Cloud specifically. We only run tests for the Docker image we produce using GitHub Actions. Can you try to run the same test file (% adding `--no-sandox` and `--disable-setuid-sandbox` args) ? https://github.com/puppeteer/puppeteer/blob/main/docker/test/smoke-test.js

Could you also try without using the proxy server?

**Comment by lancejpollard** [comment]
I am not currently using the proxy server, but I will add `--disable-setuid-sandbox`. Let me try.

**Comment by lancejpollard** [comment]
Just to be clear, I have this code:

```
export async function convertMarkdownWithPuppeteerNodeLocal(source) {
  console.log('convertMarkdownWithPuppeteerNodeLocal', source)
  const b = await getBrowser()
  console.log('convertMarkdownWithPuppeteerNodeLocal browser loaded')
  // ... rest
}
```

That `getBrowser` is just like above, which is essentially:

```
const puppeteer = require('puppeteer');

(async () => {
  console.log('convertMarkdownWithPuppeteerNodeLocal')
  const browser = await puppeteer.launch({headless: 'new'});
  console.log('convertMarkdownWithPuppeteerNodeLocal browser loaded')
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await browser.close();
  console.log('done');
})();
```

Only `convertMarkdownWithPuppeteerNodeLocal` gets logged.

This does not get logged ever (only on Google Cloud).

```
convertMarkdownWithPuppeteerNodeLocal browser loaded
```

But going to make it `headless: 'new'` instead of `headless: true`, and use `--disable-setuid-sandbox`. Let me try.

**Comment by lancejpollard** [comment]
@OrKoN see my last post, but still, no logs even after adding those `['--no-sandbox', '--disable-setuid-sandbox']` args.

<img width="920" alt="Screenshot 2024-02-12 at 3 13 28 AM" src="https://github.com/puppeteer/puppeteer/assets/28718/891b2cb5-a284-47c3-90c2-3a4ca978bd8a">

It's logging right up to the point of `puppeteer.launch()` but nothing after.

**Comment by lancejpollard** [comment]
@OrKoN also what do you think about this?

> I don't think there is a way to do [this](https://pptr.dev/guides/docker) and set --cap-add=SYS_ADMIN on Google Cloud Run, I saw that in some StackOverflow post, see https://stackoverflow.com/a/57043978/169992. Is that going to be a problem? If so, does that mean we can't use puppeteer on Google Cloud Run?

**Comment by OrKoN** [comment]
@lancejpollard `dumpio` does not use the debug module so you probably should not filter by puppeteer as logs come from the browser.

**Comment by lancejpollard** [comment]
@OrKoN sorry, don't let that throw you off. There are no other logs other than my Node.js express logs :( and the puppeteer ones I showed. There are no browser or other logs...

**Comment by lancejpollard** [comment]
Do I need to set log level somewhere? https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/node/ChromeLauncher.ts#L40

**Comment by OrKoN** [comment]
> Do I need to set log level somewhere? https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/node/ChromeLauncher.ts#L40

no, dumpio is unrelated to Puppeteer's logging/debug. Is there a chance that it is just slow and starts up after some time? Otherwise, I cannot explain hanging: there should be a log somewhere, either in the browser, or in the puppeteer side. The default timeout for launch is 30sec so it should fail there at least.

**Comment by lancejpollard** [comment]
It looks like it uses `debug` module for some things: https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/browsers/src/launch.ts#L22

**Comment by lancejpollard** [comment]
I try and make the REST API call which triggers the `await puppeteer.launch()`, and the express app logs the request immediately and shows the data I'm passing through. Then it gets to that point I showed and just stops and never returns. It works locally like I said, but not on Google Cloud Run. Sigh.

**Comment by lancejpollard** [comment]
@OrKoN like I said before, I get these `debug` logs locally:

```
puppeteer-extra-plugin:user-data-dir created custom dir /tmp/puppeteer_dev_profile-W9V5BD
puppeteer-extra-plugin:user-data-dir Wrote file /tmp/puppeteer_dev_profile-W9V5BD/Default/Preferences
puppeteer:browsers:launcher Launching /root/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --disable-dev-shm-usage --disable-field-trial-config --disable-hang-monitor --disable-infobars --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --export-tagged-pdf --generate-pdf-document-outline --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold --enable-features=NetworkServiceInProcess2 --user-data-dir=/tmp/puppeteer_dev_profile-W9V5BD --headless=new --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-blink-features=AutomationControlled --remote-debugging-port=0 { detached: true, env: {}, stdio: [ 'pipe', 'ignore', 'pipe' ] }
puppeteer:browsers:launcher Launched 141
...lots more puppeteer logs showing it works
```

That is right here: https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/browsers/src/launch.ts#L175-L199

That gets called from https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/browsers/src/launch.ts#L122

That gets called from https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/puppeteer-core/src/node/ProductLauncher.ts#L109

From https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/puppeteer-core/src/node/ChromeLauncher.ts#L38

From https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/puppeteer-core/src/node/PuppeteerNode.ts#L170-L199

From the main `puppeteer.launch` API https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/puppeteer/src/puppeteer.ts#L41

SO, it's hanging somewhere in there.

**Comment by OrKoN** [comment]
@lancejpollard it looks like something is not right with the logging in the stup.  `childProcess.spawn` just spawns the browser subprocess and dumpio:true would pipe subprocess output to the node process stdio. So you should see at least something from the attempt to start the subprocess. What log do you see locally with dumpio: true? You don't need `DEBUG=` for that.

**Comment by lancejpollard** [comment]
@OrKoN can I try using `puppeteer-core` directly, and forking that project to add some logs in there perhaps?

My guess is it could be hanging here:

https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/browsers/src/launch.ts#L168-L171

Or here:

https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/puppeteer-core/src/node/ProductLauncher.ts#L99

**Comment by lancejpollard** [comment]
@OrKoN locally I see just this (turning off `DEBUG=*`):

<img width="1047" alt="Screenshot 2024-02-12 at 3 49 45 AM" src="https://github.com/puppeteer/puppeteer/assets/28718/df14e09a-c848-4b85-8734-d8162ed7f5ba">

**Comment by OrKoN** [comment]
@lancejpollard so nothing like that on Cloud Run? can you try to search for "DevTools" or "ERROR" in the logs?

**Comment by lancejpollard** [comment]
Nope, nothing like that in Cloud Run.

<img width="738" alt="Screenshot 2024-02-12 at 3 56 46 AM" src="https://github.com/puppeteer/puppeteer/assets/28718/174e794c-14cb-4eb0-82a5-1c2ab3b972a7">

Gonna see if I can get this far in the code execution: https://github.com/puppeteer/puppeteer/blob/9c5168cbfcd15578871b7d755ac1978d266ce3da/packages/puppeteer-core/src/node/ChromeLauncher.ts#L122

**Comment by lancejpollard** [comment]
Not really able to figure out how to get the code path to get there. Looks like `#configureStdio` just returns an array, so it's not that...

The only `async` function in the path is https://github.com/puppeteer/puppeteer/blob/97824e2de93f3e2cb88cb14f60498aa541524104/packages/puppeteer-core/src/node/ProductLauncher.ts#L99

So it must be hanging there? Where the `timeout` doesn't have an effect.

**Comment by lancejpollard** [comment]
@OrKoN ah! Could it be failing here because the `/tmp` directory was not added to the `user` or something? https://github.com/puppeteer/puppeteer/blob/acce1d6128b01b8af68775a206b9337653851978/packages/puppeteer-core/src/node/ChromeLauncher.ts#L116

**Comment by OrKoN** [comment]
it should still fail there instead of hanging, but you could try changing the `userDataDir` to something that exists? Also, is it possible that container in CloudRun is attached to a readonly filesystem?

**Comment by OrKoN** [comment]
@lancejpollard the cold starts of the browser might be slow, perhaps, try giving it more memory and CPU.

**Comment by lancejpollard** [comment]
It appears I wasn't using too much CPU/memory?

<img width="726" alt="Screenshot 2024-02-12 at 4 33 00 AM" src="https://github.com/puppeteer/puppeteer/assets/28718/94250ff1-c082-4aea-abb8-ab8312b6ba59">
<img width="705" alt="Screenshot 2024-02-12 at 4 35 10 AM" src="https://github.com/puppeteer/puppeteer/assets/28718/aa2ff8e7-90b9-4dc0-a0ba-9bf93924000f">

**Comment by lancejpollard** [comment]
I do see this randomly occasionally in the logs, but no idea where its coming from:

```
ELIFECYCLE  Command failed.
```

**Comment by lancejpollard** [comment]
@OrKoN the thing is, according to the links I posted above, we should be seeing this log **BEFORE any puppeteer process has started to launch**:

```
puppeteer:browsers:launcher Launching /root/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-update --disable-dev-shm-usage --disable-field-trial-config --disable-hang-monitor --disable-infobars --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --export-tagged-pdf --generate-pdf-document-outline --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold --enable-features=NetworkServiceInProcess2 --user-data-dir=/tmp/puppeteer_dev_profile-W9V5BD --headless=new --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-blink-features=AutomationControlled --remote-debugging-port=0 { detached: true, env: {}, stdio: [ 'pipe', 'ignore', 'pipe' ] }
```

That is never getting logged on Google Cloud Run. Or at least I haven't seen it.

**Comment by lancejpollard** [comment]
@OrKoN after all this, what would you recommend I do to have a fast usage of puppeteer in the cloud (Google Cloud, since that is my architecture)? If Cloud Run is a failure, what would be better?
