### ISSUE TITLE
[Bug]: vurnerability of dependency ip

### ISSUE THREAD

**Issue by w3nl** [puppeteer/puppeteer#11884]
### Steps to reproduce

Npm audit will tell you that it has a dependency of a dependency of a dependency that has a vurnerability.
The dependency is ip.
20.3.0 has not that dependency.
But the dependency ip is not maintained anymore for 2 years.
See also: https://github.com/indutny/node-ip/issues/128

### Expected results

Not depending anymore in the dependency ip, so no audit issues.

### Actual results

High vurnerability of dependency ip

**Comment by chacin04** [comment]
I understand, can we then use the library without problem? @w3nl

**Comment by w3nl** [comment]
I see that the dependency proxy-agent will also work on this: https://github.com/TooTallNate/proxy-agents/issues/280
If they solve it, this puppeteer package will also have the fix.

**Comment by chacin04** [comment]
But is it safe to use puppeteer with the latest version available?  In this moment

**Comment by w3nl** [comment]
I think it depends on your situation.

**Comment by w3nl** [comment]
https://github.com/JoshGlazebrook/socks/releases/tag/2.7.3
This update will solve it

**Comment by w3nl** [comment]
PR for the fix in the puppeteer dependency proxy-agent: https://github.com/TooTallNate/proxy-agents/pull/281

**Comment by w3nl** [comment]
The dependencies op puppeteer are updated: https://github.com/TooTallNate/proxy-agents/releases
With `npm upgrade && npm audit fix` you can fix it for your project.
There is not a update needed for puppeteer.
