### ISSUE TITLE
[Bug]: Setting `Page.setUserAgent()` causes website to not load properly

### ISSUE THREAD

**Issue by LegendaryEmoji** [puppeteer/puppeteer#11888]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer").default;

const USER_AGENT = "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_8) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/30.0.848.0 Safari/532.0.2";

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });

    const page = await browser.newPage();

    await page.setUserAgent(USER_AGENT);

    await page.goto("https://accounts.spotify.com/en/login", {
        waitUntil: "networkidle2",
        timeout: 60 * 1000
    });

    await new Promise((resolve) => setTimeout(resolve, 2 * 60 * 1000));

    await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I was trying to log each request in the page and it was working perfectly. When I needed to set a UserAgent, I tried `Page.setUserAgent()` method, and it caused some problems with the website (the website was not loading properly afterwards).

### Expectation

- It should set the `User-Agent` header without causing any problem.

### Reality

- Using `Page.setUserAgent()` causes problems that prevents the page to load fully and properly.

### Puppeteer version

22.0.0

### Node version

18.10.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by LegendaryEmoji** [comment]
`Page.setExtraHTTPHeaders()` seems to be working fine. Following is the working code:
```js
const puppeteer = require("puppeteer").default;

const USER_AGENT = "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_8) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/30.0.848.0 Safari/532.0.2";

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });

    const page = await browser.newPage();

    await page.setExtraHTTPHeaders({
        "User-Agent": USER_AGENT
    });

    await page.goto("https://accounts.spotify.com/en/login", {
        waitUntil: "networkidle2",
        timeout: 60 * 1000
    });

    await new Promise((resolve) => setTimeout(resolve, 2 * 60 * 1000));

    await browser.close();
})();
```

**Comment by OrKoN** [comment]
Note that headers only override network headers and setUserAgent also affects the `navigator.userAgent`. In this case, it appears that it is a bug in Spotify and they fail to work with this particular user agent (seems to work with other strings).
