### ISSUE TITLE
Improve requestfailed

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#1189]
This is a hard to reproduce problem from anywhere since it happens randomly yet the actual chrome browser deals with it really well. The browser retries and the contents are reloaded in case of error

Some examples of failed responses:
![image](https://user-images.githubusercontent.com/8284972/32115402-8398d7d6-bb68-11e7-912a-517dd4a512ef.png)

![image](https://user-images.githubusercontent.com/8284972/32116777-da52ab9c-bb6d-11e7-95f4-fb6465c18a36.png)

![image](https://user-images.githubusercontent.com/8284972/32114896-98239242-bb66-11e7-91d4-697e5c1685c7.png)

![image](https://user-images.githubusercontent.com/8284972/32115545-0cce7e3e-bb69-11e7-8792-230f80f3c962.png)

A video of whatever is happening above: https://streamable.com/2wiw4

I am using some proxies and this can be the problem with proxies where it does not return any responses, however if I refresh the page, it loads fine. But the solution is not to change the proxies or blame the provider. The solution is to improve puppeteer for better error handling. The proxies works fine with normal chrome/firefox. Just causes problem with puppeteer.

Right now I am using the `response.ok` and reloading the page. On empty responses, the response is `null`. I check for that too and recursively reload the page.

And on other cases, the page loads fine, but you can see the elements are really not loading. But I cannot deal with the inner requests. I can trace the failed requests with the following events,

```
event: 'request'
event: 'requestfailed'
event: 'requestfinished'
```

It emits if there is a request fails, that's nice. But I cannot reload that request, nor did I find any documentation or code related to that.

If I use  the following code,
```
await page.on("request", interceptedRequest => {
 interceptedRequest.continue();
});

await page.once("requestfailed", interceptedRequest => {
 console.log(`Failed to load: ${interceptedRequest.url}`);
 interceptedRequest.continue();
});
```

Then it will say that the request has already been dealt with. I don't know why requestfailed will say that. It would be better if we had a `interceptedRequest.retry(delay, retries, onretriesfailed);` or something there so it would retry after delay, meanwhile the networkidle would just sit tight and wait for me.

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: AssertionError [ERR_ASSERTION]: Request is already handled! <-- What? By whom?
- console.js:188 Console.assert
  console.js:188:23
 - NetworkManager.js:315 Request.continue
   [puppeteer]/[puppeteer]/lib/NetworkManager.js:315:13
```

Same goes for timeouts and hundreds of other errors. Just knowing that there is some error is not good if we cannot deal with it. If there is a way to deal with it using whatever we have now, please guide me thru it. 

If this is a browser limitation, then I wonder how normal chrome deals with it. It's like I cannot do anything with the failed requests if I use puppeteer which is using chrome, but chrome itself can deal these errors very well.

For the reproducing part, I think we can simply use any 404/500 page or navigational timeout event.

Note: there have been other people asking for similar thing, 
https://github.com/GoogleChrome/puppeteer/issues/716
https://github.com/GoogleChrome/puppeteer/issues/574

Thank you.

**Comment by aslushnikov** [comment]
> Then it will say that the request has already been dealt with. I don't know why requestfailed will say that. 

You can call "continue" only once per intercepted request. Once you called "continue", the request is sent to the server. There's no option to "resend" the request for now; however, there are some discussions about adding "response interception" that would help you.

I've filed an issue for this: https://github.com/GoogleChrome/puppeteer/issues/1191 Please thumb-up it if you'd like it to be implemented
