### ISSUE TITLE
[Bug]: Cannot run Docker container on Google Cloud Run without --no-sandbox?

### ISSUE THREAD

**Issue by lancejpollard** [puppeteer/puppeteer#11903]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--user-data-dir=/tmp',
    ],
    timeout: 0,
    executablePath: '/usr/bin/google-chrome',
  });
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.screenshot({ path: 'google.png' });

  await browser.close();
})();
```

### Error string

--no-sandbox

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Posted this security question asking what a hacker can do if you enable `--no-sandbox`: https://security.stackexchange.com/questions/274583/how-does-a-hacker-get-access-to-the-root-user-when-disabling-the-sandbox-in-pupp

I thought it would be beneficial to the community to post this as a bug, because I see many places on StackOverflow and the web suggesting to use `--no-sandbox` on AWS Lambda and Google Cloud Run (both serverless systems), yet all the comments say "**it's a huge security hole! don't do it!**". There are not enough resources describing how to solve this for Lambda and Cloud Run, and I was going to create a security vulnerability issue, but thought a bug would suffice, because it technically is a bug if you have to do this hacked workaround.

### Expectation

I expect to run my Google Cloud Run Docker image/container in secure mode without the `--no-sandbox` flag, so it can handle untrusted user content.

### Reality

The reality is, you cannot do this, as far as I have seen, on Google Cloud Run or AWS Lambda. I am most concerned with Cloud Run since that is what I'm using, but for other people's sake, mentioning Lambda too is important.

On Cloud Run, you cannot follow your [guides](https://pptr.dev/guides/docker). You are unable to do this:

```
docker run -i --init --cap-add=SYS_ADMIN --rm ghcr.io/puppeteer/puppeteer:latest node -e "$(cat path/to/script.js)"
```

Specifically, you can't add `--cap-add=SYS_ADMIN` because you never run `docker run` on these systems, they do it for you and you can't customize how they do it. Please correct me if I'm wrong or missed this in the cloud documentation, but I'm 99% sure you cannot do it on these systems!

This means your only option is to use `--no-sandbox`. If that is such a security hole, yet you _must_ use it, is there a way to mitigate any potential security threats? Like if you ran puppeteer on its own dedicated serverless function, independent of the rest of your app (though it would probably need some secret keys loaded via ENV variables at the least, to connect to external services like S3 or Cloud Storage, for example). Would that solve this?

If not, is there anything possible you could do on your end to implement a new solution (even if you don't do it any time soon)? Is it possible to solve this even?

I saw this Google Cloud Run link to configure containers, maybe you can see a way to pass that `--cap-add` flag in somehow? I couldn't find a way: https://cloud.google.com/run/docs/configuring/services/containers#console

### Puppeteer configuration file (if used)

```TypeScript
None.
```

### Puppeteer version

22.0.0

### Node version

20.11.0

### Package manager

pnpm

### Package manager version

8.15.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Have you tried all options from the troubleshooting guide? https://pptr.dev/troubleshooting#setting-up-chrome-linux-sandbox In particular, https://pptr.dev/troubleshooting#alternative-setup-setuid-sandbox? 

I don't think it is a Puppeteer bug: it is difficult to deploy Chrome to server-environments that are restricted. I would suggest filing an issue at crbug.com for Chrome and reach out to Cloud Run or other hosting providers for possible solutions.
