### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Invalid parameters objectId: string value expected

### ISSUE THREAD

**Issue by redochka** [puppeteer/puppeteer#1190]
I am using `"puppeteer": "^0.12.0"`

Trying to 

<pre>
    const browser = await puppeteer.launch({"executablePath": "/usr/bin/chromium-browser", args: ['--no-sandbox', '--disable-setuid-sandbox']});

    const page = await browser.newPage();
    await page.goto(ADMIN_URL);

    await page.click("#input-username");
</pre>

I get error : 

<pre>
(node:27918) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Runtime.callFunctionOn): Invalid parameters objectId: string value expected
(node:27918) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

Chrome version:
<pre>
$ apt-cache policy chromium-browser
chromium-browser:
  Installed: 62.0.3202.62-0ubuntu0.14.04.1204

$ whereis chromium-browser
chromium-browser: /usr/bin/chromium-browser /usr/lib/chromium-browser /etc/chromium-browser /usr/share/chromium-browser /usr/share/man/man1/chromium-browser.1.gz

</pre>

**Comment by raphi011** [comment]
I have the same error, any ideas?

**Comment by darioalessandro** [comment]
Same thing here:


| K | V |
| -- | --|
| Google Chrome | 62.0.3202.75 (Official Build) (64-bit)|
| Revision | 67b212ffb03c4401235f8961e2d15371b96cde27-refs/branch-heads/3202@{#750} |
| OS | Mac OS X |
|JavaScript | V8 6.2.414.36|
|Flash | 27.0.0.183 /Users/darioalessandro/Library/Application |Support/Google/Chrome/PepperFlash/27.0.0.183/PepperFlashPlayer.plugin|
|User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36|
|Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_10328537 --flag-switches-begin --flag-switches-end |
|Executable Path | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome |
|Profile Path | /Users/darioalessandro/Library/Application Support/Google/Chrome/Default|

Seems like the browser launches and then:

```
Error: Protocol error (Runtime.callFunctionOn): Invalid parameters objectId: string value expected
      at Session._onMessage (node_modules/puppeteer/node6/Connection.js:272:25)
      at Connection.<anonymous> (node_modules/puppeteer/node6/Connection.js:150:19)
      at undefined.next (native)
      at step (node_modules/puppeteer/node6/Connection.js:113:24)
      at Promise (node_modules/puppeteer/node6/Connection.js:131:12)
      at fn (node_modules/puppeteer/node6/Connection.js:109:10)
      at Connection._onMessage (node_modules/puppeteer/node6/Connection.js:133:3)
      at Receiver._receiver.onmessage (node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:143:47)
      at Receiver.dataMessage (node_modules/puppeteer/node_modules/ws/lib/Receiver.js:389:14)
      at Receiver.getData (node_modules/puppeteer/node_modules/ws/lib/Receiver.js:330:12)
      at Receiver.startLoop (node_modules/puppeteer/node_modules/ws/lib/Receiver.js:165:16)
      at Receiver.add (node_modules/puppeteer/node_modules/ws/lib/Receiver.js:139:10)
      at Socket._ultron.on (node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:139:22)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:547:20)

```

**Comment by aslushnikov** [comment]
Puppeteer doesn't work with Chrome M62; the currently-supported chrome version is M64.

**Comment by redochka** [comment]
@aslushnikov ok thanks for the info. Where could see such compatibility info next time? because i suspect compatibility will break again with version 64 after few releases of puppeteer (from my experience with selenium and chrome driver ...)

Also, anyone is able to provide a link to the armhf deb package of chromium 64? because he best we can get right now is version 62 https://launchpad.net/ubuntu/artful/armhf/chromium-browser

**Comment by mrbar42** [comment]
chrome 64 is the current `unstable`, you can get it from here:
`https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb`

(this is chrome though)

**Comment by redochka** [comment]
@mrbar42 i need the armhf not the amd64 build

**Comment by mrbar42** [comment]
oh sorry - missed that
looks like chromium builds of v64 on the chromium dev branch PPA are [failing](https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+packages?field.name_filter=chromium&field.status_filter=published&field.series_filter=) at the moment.
last successful build is v63

keep your eyes on [Successful builds list](https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+builds?build_text=&build_state=built)
