### ISSUE TITLE
Fix tests disabled after refactoring

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11913]
With the following tests have been disabled: https://github.com/puppeteer/puppeteer/pull/11836

We need to investigate the issues and recover test coverage:

[navigation.spec] navigation Page.goto should fail when navigating to bad SSL
  https://github.com/w3c/webdriver-bidi/issues/657

[frame.spec] Frame specs Frame Management should detach child frames on navigation
  https://github.com/w3c/webdriver-bidi/issues/659

[frame.spec] Frame specs Frame Management should send \"framenavigated\" when navigating on anchor URLs
  https://github.com/w3c/webdriver-bidi/issues/657

[frame.spec] Frame specs Frame Management should support framesets
  https://github.com/w3c/webdriver-bidi/issues/659

[navigation.spec] navigation Page.goBack should work with HistoryAPI
  browsingContext.navigationStarted event not emitted for fragment navigation

[navigation.spec] navigation Page.goto should fail when main resources failed to load
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should fail when navigating and show the url at the error message
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should fail when navigating to bad SSL after redirects
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should fail when server returns 204
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should work with anchor navigation
  browsingContext.navigationStarted event not emitted for fragment navigation

[navigation.spec] navigation Page.waitForNavigation should work with DOM history.back()/history.forward()
  browsingContext.navigationStarted event not emitted for fragment navigatio

[navigation.spec] navigation Page.waitForNavigation should work with history.pushState()
  browsingContext.navigationStarted event not emitted for fragment navigation

[network.spec] network Response.fromCache should work

[oopif.spec] OOPIF should support frames within OOP iframes
  Fetch error

[oopif.spec] OOPIF should support lazy OOP frames
  https://bugzilla.mozilla.org/show_bug.cgi?id=187816

[oopif.spec] OOPIF should wait for inner OOPIFs
  Fetch error

**Comment by whimboo** [comment]
Thank you Alex!
