### ISSUE TITLE
[Bug]: addEventListener  for mousedown , click events not working -- resolved refer comments

### ISSUE THREAD

**Issue by rajesh-techie** [puppeteer/puppeteer#11927]
const puppeteer = require('puppeteer');

(async () => {
    try {
        const browser = await puppeteer.launch({
            headless: false,
            executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
        });
        const page = await browser.newPage();

        console.log('Script executed successfully.');
        await page.goto('https://saucedemo.com');
        await page.waitForSelector('#user-name');
        console.log('Page opened successfully.');

        // Set up 'mousedown' event listener at the document level
        await page.evaluate(() => {
            document.addEventListener('mousedown', (event) => {
                console.log('Mouse down event:', event);
            });
        });

        console.log('Event listener set up successfully.');

        // Additional actions can be performed here

        // Close the browser after some time (adjust as needed)
        setTimeout(async () => {
            await browser.close();
        }, 10000);
    } catch (error) {
        console.error('Error:', error);
    }
})();

**Comment by rajesh-techie** [comment]
It doesnt work on windows

**Comment by OrKoN** [comment]
It is not clear what is not working in the example: if you expect to see the console message from the mouse down, you need to listen for it on the Puppeteer page, e.g., `page.on('console', event => console.log(event.text()))`, as messages are not logged by default.

**Comment by rajesh-techie** [comment]
The mouseevent is not captured and console.log message is not throwng in console, whereas for keyboard events it shows on console log

**Comment by OrKoN** [comment]
I am not able to reproduce that. 

```

import puppeteer from 'puppeteer'

const browser = await puppeteer.launch({
  headless: false
});

const page = await browser.newPage();

await page.goto('https://saucedemo.com');
await page.waitForSelector('#user-name');
console.log('Page opened successfully.');

// Set up 'mousedown' event listener at the document level
await page.evaluate(() => {
    document.addEventListener('mousedown', (event) => {
        console.log('Mouse down event:', event);
    });
});

page.on('console', (msg) => {
  console.log(msg.text())
})

console.log('Event listener set up successfully.');

// Additional actions can be performed here

```

outputs when you press the mouse button down

```
❯ node mouseDown.mjs

Page opened successfully.
Event listener set up successfully.
Content is cached for offline use.
Failed to load resource: the server responded with a status of 401 (Unauthorized)
Failed to load resource: the server responded with a status of 401 (Unauthorized)
Mouse down event: JSHandle@object
Mouse down event: JSHandle@object
Mouse down event: JSHandle@object
Mouse down event: JSHandle@object
Mouse down event: JSHandle@object
Mouse down event: JSHandle@object
Mouse down event: JSHandle@object
```

**Comment by rajesh-techie** [comment]
thank you it worked only after the addition of the following : 
page.on('console', event => console.log(event.text()))
