### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hyrumsdolan** [puppeteer/puppeteer#11920]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

async function testXPath() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');

  const elements = await page.$x('//h1');
  console.log(elements)

  await browser.close();
}

testXPath();
```

### Error string

TypeError: page.$x is not a function

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I was trying to use this to target a dynamically changing element in a project and was getting this error.
I attempted to uninstall and reinstall the puppeteer package, and also opened a new directory and created this test.

### Expectation

I expect .$x() to work as a function

### Reality

I get an error saying it is not a function.

### Puppeteer version

22.0.0

### Node version

21.6.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

macOS

**Comment by jrandolf** [comment]
`$x` is no longer supported.
