### ISSUE TITLE
[Bug]: Can't generate a PDF in desktop, tablet or mobile mode. Always in tablet !

### ISSUE THREAD

**Issue by apinard** [puppeteer/puppeteer#11928]
### Minimal, reproducible example

```TypeScript
const http = require('http');
const puppeteer = require('puppeteer');
const devices = puppeteer.KnownDevices;

const PORT = process.env.PORT || 3000;

const server = http.createServer(async (req, res) => {
    try {
        // Extract the URL, filename, and device type from the request query parameters
        const url = new URL(req.url, `http://${req.headers.host}`).searchParams.get('url');
        const filename = new URL(req.url, `http://${req.headers.host}`).searchParams.get('filename');
        let deviceType = new URL(req.url, `http://${req.headers.host}`).searchParams.get('device');

        if (!url) {
            throw new Error('URL parameter is missing');
        }

        const browser = await puppeteer.launch({
          executablePath: "google-chrome",
          args: ['--no-sandbox', '--disable-setuid-sandbox']
        });

        const page = await browser.newPage();

        // Emulate device based on deviceType
        if (deviceType === 'phone') {
            await page.emulate(devices['iPhone X']); // Example for phone
        } else if (deviceType === 'desktop') {
            await page.setViewport({ width: 1280, height: 720 }); // Example for desktop
        } else {
            // Default or other types can be handled here, e.g., tablet
            await page.emulate(devices['iPad']); // Keeping your default tablet mode
        }

        page.setDefaultNavigationTimeout(0);

        await page.goto(url, { waitUntil: 'load' });

        // Generate PDF with additional options
        const pdf = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
        });

        await browser.close();

        res.writeHead(200, { 'Content-Type': 'application/pdf', 'Content-Disposition': `filename=${filename}.pdf` });
        res.end(pdf);
    } catch (error) {
        console.error('Error:', error);
        res.writeHead(500, { 'Content-Type': 'text/plain' });
        res.end(error.message);
    }
});

server.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I have an app where I pass a URL as argument and the script transform it to a PDF and return the PDF to the user.

### Expectation

I have an app where I pass a URL as argument and the script transform it to a PDF and return the PDF to the user.

### Reality

The problem is I can't change the way the PDF is displayed. It's always rendered in tablet mode. I've tried so different things and nothing helped. 

If the URL is:
- ....&device=desktop : the PDF should represent what the html looks in desktop mode.
- ....&device=tablet : the PDF should represent what the html looks in tablet mode.
- ....&device=phone : the PDF should represent what the html looks in phone mode.

How can we achieve this?

Thanks.

### Puppeteer version

22.0.0

### Node version

20.11.0

### Package manager

npm

### Package manager version

8.5.5

### Operating system

Windows

**Comment by apinard** [comment]
My question above is valid. It's running well, I can generate a PDF and it's well rendered. ONLY that I can't manage how to display the PDF in differents modes; desktop, tablet and phone.

**Comment by OrKoN** [comment]
@apinard could you please update the example to include a sample page URL and remove http server logic? Also, could you clarify what differences you expect in PDF rendering for different modes? As PDF rendering happens in the printing mode, it might not be affected by emulation.

**Comment by apinard** [comment]
Hi @OrKoN ,

Thank you for your fast reply. 

I attached an example.

![navigation_and_print_examples](https://github.com/puppeteer/puppeteer/assets/97567768/d5b6de87-5b1b-4387-b10e-b943c97591f8)

Basically, depending of the parameter in the url (desktop, tablet or phone), I could set internally a width/height or use a device like the initial idea.. but it's not working.

Any tips?

Thank you again.

**Comment by OrKoN** [comment]
@apinard the site is responsive and has probably print styles for PDF printing. Printing in the regular browser looks the same

<img width="1506" alt="Screenshot 2024-02-16 at 08 18 05" src="https://github.com/puppeteer/puppeteer/assets/399150/3d3b912c-3d68-494c-b3e6-db686959fd15">

So I don't think there is a bug.

**Comment by apinard** [comment]
@OrKoN ah ok, I didn't know there was the notion of "print styles". I'll take a look. Thank you for your fast answers.
