### ISSUE TITLE
[Feature]: Please check the setViewport function

### ISSUE THREAD

**Issue by nhhoang** [puppeteer/puppeteer#11933]
### Feature description

In Puppeteer, I have encountered some issues with the setViewport function. When executing the command await this.page.setViewport({ width: 1920, height: 1080}), the following problems arise:

- When accessing the website https://abrahamjuliot.github.io/creepjs, there is a deduction of 25 points in the session due to the change in the viewport.
- <img width="718" alt="Screenshot 2024-02-16 at 15 21 11" src="https://github.com/puppeteer/puppeteer/assets/3433969/4a74cb50-eb7a-48b2-bc2c-8fc4f9358892">
- When accessing the page https://redbubble.com/portfolio/images/new, Cloudflare detects it, preventing automated passing.

Some information I have gathered and tested:
- This error occurs only when running the setViewport function.
- This issue is specific to Puppeteer versions 6.0.0 and later; versions 5.5.0 and earlier do not exhibit this problem. However, not running it leads to a window size and viewport mismatch error. Attempting to resize may result in an error.

Could you please review if there is a solution to fix this issue?

**Comment by OrKoN** [comment]
This is out of scope for Puppeteer to help with avoiding automation detection. You can use `defaultViewport: null` to turn off the default viewport setting. Instead you could use the `--window-size` as the argument for Chrome to change the window size instead of emulating the viewport.
