### ISSUE TITLE
[Bug]: `page.on('load')` does not fire in headless mode

### ISSUE THREAD

**Issue by JakobJingleheimer** [puppeteer/puppeteer#11935]
### Minimal, reproducible example

```TypeScript
import { puppeteer } from 'puppeteer-extra';

const browser = puppeteer.launch({
  args: [
    '--incognito',
    'http://app.localhost:3000',
  ],
});

const [page] = browser.pages();

await new Promise((ready) => page.on('load', ready));

// interact with the page
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

When puppeteer is launched with a starting address, the code needs to wait for the page to load instead of waiting for a navigation etc.

### Expectation

In v21.7.0, `page.on('load')` fired.

### Reality

Now, it does not fire in headless mode, but _does_ in non-headless mode (presumably because non-headless mode takes longer to start up?).

### Puppeteer version

22.0.0

### Node version

20.11.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

macOS

**Comment by OrKoN** [comment]
@JakobJingleheimer this way to listen for the load event is inherently flaky. You need to create a new page, set up a listener, then navigate the page. There is just no way to do that if you specify which page to open outside of Puppeteer (the url argument is handled by the browser).

**Comment by JakobJingleheimer** [comment]
Mm, yes I figured it was something like that, but curious that the page on load approach worked 100% of the time (after thousands of runs across multiple OSs), and it suddenly doesn't at all now.

I switched to `await page.waitForSelector()`, which is working.

**Comment by JakobJingleheimer** [comment]
Ah! It's related to puppeteer/puppeteer#11815: I was using `headless: 'new'` to opt into the new headless mode. I neglected to switch it back to `headless: true` after upgrading (which is now using the new). Now that I switched back to `headless: true` on v22, the page-on-load works again.

**Comment by OrKoN** [comment]
@JakobJingleheimer in v22, the headless mode is the new one by default so that could change timings. This is completely arbitrary though and depends on how fast the page loads, if you delay the page load artificially, I believe you would see it fire most of the time. To avoid flakiness, the listener always has to be set up before the action, which is not possible in this case.

To make it non-flaky the following can work:

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  args: [
    '--incognito',
    'https://example.com',
  ],
});

const [page] = await browser.pages();

await page.evaluate(async () => {
    if (document.readyState == 'complete') {
        return;
    }
    await new Promise(resolve => window.addEventListener('load', resolve, {
        once: true,
    }))
})

console.log('ready')

await browser.close()
```

**Comment by JakobJingleheimer** [comment]
Cheers, thanks!

Not sure if you saw my updated message above: there's something wonky with `headless: 'new'` on 22.0.0.

**Comment by OrKoN** [comment]
@JakobJingleheimer it should make no difference I think since “new” is a truthy value but in general yes you need to upgrade to using headless: true for the new headless, and ‘shell’ for the old headless. V22 is a release with quite a few breaking changes.

**Comment by JakobJingleheimer** [comment]
Mm, I saw them 🙂

I dunno why, but `'new'` definitely does make a difference. I just ran the ill-fated page-on-load from my OP a hundred times each for `true` vs `'new'` on v22. It worked 100/100 with `true` and failed (hung) 100/100 times with `'new'` 🤷‍♂️

**Comment by OrKoN** [comment]
I see, I checked if you specify 'new' it looks like the old headless mode will be launched. In any case, we do not support 'new' anymore but perhaps we might want to default to the new mode even in this case.
