### ISSUE TITLE
ServiceWorkers fail if Request Interceptor is enabled

### ISSUE THREAD

**Issue by luanpotter** [puppeteer/puppeteer#1193]
Just create a simple project with Puppeteer and try to access a page that uses Service Workers, having request interception enabled (you don't need to do anything); for instance:

```js
    const puppeteer = require('puppeteer');

    const URL = 'https://googlechrome.github.io/samples/service-worker/basic/';

    // enables request interception but allow everything
    async function mockPage(page) {
        await page.setRequestInterceptionEnabled(true);
        await page.on('request', req => req.continue());
    }

    async function main() {
        const browser = await puppeteer.launch({ headless: false, devtools: true });
        const page = await browser.newPage();
        await mockPage(page);

        await page.goto(URL);
    }

    main().then(data => console.log(data)).catch(err => console.error(err));
```

Check the console to see that the ServiceWorker has failed with the following error:

> Uncaught (in promise) DOMException: Failed to register a ServiceWorker: No URL is associated with the caller's document.

I assume it has something to do with ServiceWorkers also being able to intercept requests. Since ServiceWorkers are very restrictive and require HTTPS request, I thought maybe some certificate error was happening with the Request Interception, so I tryed to add a few options to launch:

 * `ignoreHTTPSErrors: false`
 * `args: ['--ignore-certificate-errors', '--unsafely-treat-insecure-origin-as-secure=' + URL]`

But to no avail.

I'm using the latest Puppeteer stable version, `0.12.0`, and also on the `master` branch, on Linux.

**Comment by aslushnikov** [comment]
This will be fixed once Chromium completes migration onto Network Service.

You can enable network service with `--enable-features=NetworkService` flag, but **beware**: network service is not complete, and certain things don't work yet.

The following works for me:

```js
const puppeteer = require('puppeteer');

const URL = 'https://googlechrome.github.io/samples/service-worker/basic/';

async function main() {
  const browser = await puppeteer.launch({
    args: ['--enable-features=NetworkService'],
    headless: false,
    devtools: true,
  });
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', req => req.continue());
  await page.goto(URL);
}

main().then(data => console.log(data)).catch(err => console.error(err));
```

**Comment by aslushnikov** [comment]
This is working as expected on Puppeteer v1.7.0.
