### ISSUE TITLE
Fix unit tests for proper JSHandle types

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#11945]
At least one test that returns a remote object is failing in both Chrome and Firefox because of an inappropriate check for the remote value type:

* [Page Page.Events.Console should return remote objects](https://github.com/puppeteer/puppeteer/blob/84ad6de2e6d292771cc66523ec7ae91f65281a91/test/src/page.spec.ts#L499-L513)

Here it is checked for `JSHandle@object` instead of `JSHandle@window`.

I didn't check other tests that fail both in Chrome and Firefox. So maybe more are affected.

CC @OrKoN

**Comment by OrKoN** [comment]
@whimboo this is a new test and it would fail anyway because of 

```
      expect(await (await log.args()[3]!.getProperty('test')).jsonValue()).toBe(
        1
      );
```

since WebDriver BiDi does not retain console messages.

**Comment by whimboo** [comment]
Oh, right but that would be the next step and probably warrants a different issueafter such the fix for this issue.

**Comment by Lightning00Blade** [comment]
Closing as completed - https://github.com/puppeteer/puppeteer/pull/12081
