### ISSUE TITLE
[Bug]: boundingBox inside iframe is incorrect 

### ISSUE THREAD

**Issue by TheGP** [puppeteer/puppeteer#11943]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  // Launch browser
  const browser = await puppeteer.launch({
    headless: false,
  });

  console.log('!!');
  // Open a new page
  const page = await browser.newPage();

  await page.goto('https://reviewer.eugenebos.com/automation-test');
  await page.waitForSelector('#textInput');

  const frameElement = await page.$('[src="/automation-test-iframe"]');
  const frameHandle = await frameElement.contentFrame();
  const elementHandle2 = await frameHandle.$('#inputIframe');
  const boundingBox2 = await elementHandle2.boundingBox();

  const boundingBox3 = await frameHandle.evaluate(element => {
    console.log(element,  element.getBoundingClientRect());
    return JSON.parse(JSON.stringify(element.getBoundingClientRect()))
  }, elementHandle2);

  console.log('Bounding box2:', boundingBox2);
  console.log('Bounding box3:', boundingBox3);

  browser.close();
})();
```

### Error string

Bounding box2 doesnt match Bounding box3, y parameter

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

boundingBox2.y === boundingBox3.y

### Reality

boundingBox2.y !== boundingBox3.y

### Puppeteer version

22.1.0

### Node version

21.5.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by TheGP** [comment]
I think it shows the position relative top frame (main page), but I don't see how it is useful.

**Comment by OrKoN** [comment]
If it shows the position relative to the top frame, then it matches the documented behavior https://pptr.dev/api/puppeteer.elementhandle.boundingbox/ It is useful if you want to send input actions (e.g., mouse) to the element because dispatch requires absolute coordinates. If you require the web-exposed bounding boxes, script evaluation is the way to go.
