### ISSUE TITLE
[Bug]: Interact with an existing browser session not possible

### ISSUE THREAD

**Issue by brahimgb** [puppeteer/puppeteer#11953]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-extra';



let wsChromeDebugger="ws://127.0.0.1:9222/devtools/browser/f7e5e6d0-0921-4a86-a5fc-8dfb5ad7c766"

 puppeteer.connect({
       browserWSEndpoint: wsChromeDebugger
  }).then(async (browser : any) => {
    console.log('Running tests..')
    const page = await browser.newPage();
    await page.goto('https://contact.com')
    await page.waitForTimeout(50000)

})
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I tried connecting with both `browserWSEndpoint` and `browserURL`, but neither worked. I noticed that even when providing the wrong connection string, it still doesn't work and opens a new browser.

### Expectation

It should open the new page in an existing browser instead of opening a new browser.

### Reality

When running the code, I first launch Chromium in debugging mode by executing `chromium --remote-debugging-port=9222` in the terminal. Then, I connect to it using the connection string available in the URL `http://127.0.0.1:9222/json/version` and by utilizing the `browserWSEndpoint`.

### Puppeteer version

22.1.0

### Node version

v20.11.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by OrKoN** [comment]
@ibrahimgb what browser version do you use?

**Comment by ibrahimgb** [comment]
@OrKoN

![image](https://github.com/puppeteer/puppeteer/assets/59414164/c8fa3b2f-d79e-4b52-a5b6-19842a3c1e2e)

**Comment by OrKoN** [comment]
@ibrahimgb what arguments do you use to start the browser?

**Comment by OrKoN** [comment]
I am not able to reproduce. Also note that waitForTimeout does not exist in the Puppeteer version you specified. 

I suggest using the matching Chrome for Testing binary instead of Chromium https://pptr.dev/chromium-support and trying without using `puppeteer-extra` (this is not the package provided by us).

**Comment by OrKoN** [comment]
Steps I tried:

```
npx puppeteer browsers install chrome@121.0.6167.160
"~/.cache/puppeteer/chrome/mac_arm-121.0.6167.160/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing" --remote-debugging-port=9222
```

```
import puppeteer from 'puppeteer'

const browser = await puppeteer.connect({
  browserWSEndpoint: 'URL from the launch',
})
const page = await browser.newPage();
await page.goto('https://contact.com')
await page.waitForTimeout(50000)
```

<img width="1502" alt="Screenshot 2024-02-20 at 09 20 26" src="https://github.com/puppeteer/puppeteer/assets/399150/78e540c4-1a86-4cba-a96a-2c3b7541794b">
