### ISSUE TITLE
Handle protocol error from Emulation.setDeviceMetricsOverride method

### ISSUE THREAD

**Issue by oliverdunk** [puppeteer/puppeteer#11964]
## Overview

Starting in [this commit](https://chromium.googlesource.com/chromium/src.git/+/f88fb49cda4e8cf8af81b3654d83d1e2bf347a9d), it is possible for the `Emulation.setDeviceMetricsOverride` CDP command to return an error if it is called for a target that uses auto resizing. This includes extension popups, which are inconsistently exposed as pages today but will be consistently exposed that way in the future.

Puppeteer currently crashes when this happens.

Error:

```
ProtocolError: Protocol error (Emulation.setDeviceMetricsOverride): Target does not support metrics override
```

Stack trace:

```
    at CallbackRegistry.create
    at Connection._rawSend
    at CdpCDPSession.send
    at #applyViewport
    at EmulatedState.<anonymous>
```

This is happening because the [default viewport is set](https://github.com/puppeteer/puppeteer/blob/ceab7a9042fe5fc3f71875e75327bb370f1c43a5/packages/puppeteer-core/src/cdp/Page.ts#L114) when pages are initialized.

To make sure Puppeteer can connect to these targets **and** allow developers to work with them, Puppeteer should instead silently ignore this error (at least [here](https://github.com/puppeteer/puppeteer/blob/ceab7a9042fe5fc3f71875e75327bb370f1c43a5/packages/puppeteer-core/src/cdp/Page.ts#L114), since it wasn't explicitly called by the developer).

## Steps to reproduce

1. Apply the following patch to Chromium, to properly identify popups as pages:

```
diff --git a/extensions/browser/extension_host.cc b/extensions/browser/extension_host.cc
index 0035aedce82f0..7eb58569e5a3d 100644
--- a/extensions/browser/extension_host.cc
+++ b/extensions/browser/extension_host.cc
@@ -108,8 +108,8 @@ ExtensionHost::ExtensionHost(const Extension* extension,
       WebContents::CreateParams(browser_context_, site_instance));
   host_contents_->SetOwnerLocationForDebug(FROM_HERE);
   content::WebContentsObserver::Observe(host_contents_.get());
-  host_contents_->SetDelegate(this);
   SetViewType(host_contents_.get(), host_type);
+  host_contents_->SetDelegate(this);
   main_frame_host_ = host_contents_->GetPrimaryMainFrame();
 
   // Listen for when an extension is unloaded from the same profile, as it may
```

2. Clone this repository: https://github.com/oliverdunk/puppeteer-extension-experiments
3. Update `puppeteer.launch` in `index.ts` with an `executablePath` pointing to your Chromium build.
4. Update the final line in `utils.ts` to use `popup.page()` instead of `asPage()`.
5. Run the tests with `npm install && npm run build && npm start`.

**Comment by OrKoN** [comment]
We need to take a look once https://chromium.googlesource.com/chromium/src.git/+/f88fb49cda4e8cf8af81b3654d83d1e2bf347a9d rolls to stable

**Comment by OrKoN** [comment]
@oliverdunk I am getting the following error on the repro

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [TypeError]: Cannot read properties of undefined (reading 'openPopup')
    at evaluate (evaluate at /Users/alex/projects/pptr-test/puppeteer-extension-experiments/dist/utils.js:57:22, <anonymous>:0:14)
    at #evaluate (/Users/alex/projects/pptr-test/puppeteer-extension-experiments/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:190:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/alex/projects/pptr-test/puppeteer-extension-experiments/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:117:16)
    at async IsolatedWorld.evaluate (/Users/alex/projects/pptr-test/puppeteer-extension-experiments/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:124:16)
    at async CdpWebWorker.evaluate (/Users/alex/projects/pptr-test/puppeteer-extension-experiments/node_modules/puppeteer-core/lib/cjs/puppeteer/api/WebWorker.js:83:16)
 ```
 
 is it past the emulation override error?

**Comment by OrKoN** [comment]
I am not able to reproduce it anymore. So the issue is fixed.
