### ISSUE TITLE
[Bug]: Download failed: server returned code 500 for chromium

### ISSUE THREAD

**Issue by cbachar** [puppeteer/puppeteer#11969]
### Steps to reproduce

Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.133/linux64/chrome-linux64.zip

### Expected results

Chrome should be downloaded, we get 500 error

### Actual results

Failed to download.

**Comment by OrKoN** [comment]
Duplicate of https://github.com/puppeteer/puppeteer/issues/11967

**Comment by cbachar** [comment]
Hi @OrKoN ,
https://github.com/puppeteer/puppeteer/issues/11967 refers to 119.
**I have issue with 114.**

Link still not opening.
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.133/linux64/chrome-linux64.zip

**Comment by OrKoN** [comment]
@cbachar it is the same issue no matter what version you use. The server has na error unrelated to the version.
