### ISSUE TITLE
[Bug]: Puppeteer doesn't use the loaded fonts.

### ISSUE THREAD

**Issue by GledachevY** [puppeteer/puppeteer#11966]
### Minimal, reproducible example

```TypeScript
await chromium.font('url to otf file in S3 bucket')

const browser = await api.aws.createBrowser()
const page = await browser.newPage()
await page.setContent(html, { waitUntil: 'networkidle2' })
const buffer = await page.pdf({
format: 'A4',
displayHeaderFooter: true,
margin: {
top: '80px',
bottom: '70px',
left: '40px',
right: '40px',
}
})

let base64 = btoa(buffer)
```

### Error string

No error.

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

An empty pdf is generated when there are chinese symbols. A chinese font is loaded and it was working before but after a migration from node 16 to node 20, puppeteer-core 21.0.0 to 22.0.0 and sparticuz/chromium 115.0.0 to 121.0.0 the fonts are not loaded

### Expectation

I expect to generate a PDF with chinese symbols when a chinese font NotoSansSC-Regular is loaded.

### Reality

The PDF is rendered without the chinese symbols.

### Puppeteer configuration file (if used)

```TypeScript
return await puppeteer.launch({
    defaultViewport: chromium.defaultViewport,
    executablePath: isLocal ? absoluteFilePath : await chromium.executablePath(),
    headless: true,
    ignoreHTTPSErrors: true,
    args: ['--no-sandbox', '--single-process', '--no-zygote']
  })
```

### Puppeteer version

21.0.0

### Node version

20.0.0

### Package manager

npm

### Package manager version

10.0.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Please open the issue at sparticuz/chromium since it's not maintained by us. The browser should pick up all fonts that are installed on the system,

**Comment by GledachevY** [comment]
Can you tell me from where the browser picks up the fonts in docker image of a lambda function?

**Comment by OrKoN** [comment]
I do not know the details but the logic should be here https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/fonts/linux/font_cache_linux.cc See https://github.com/Sparticuz/chromium?tab=readme-ov-file#fonts for Sparticuz/chromium font advice.
