### ISSUE TITLE
[Bug]: Download failed: server returned code 500 for chromium

### ISSUE THREAD

**Issue by bernatixer** [puppeteer/puppeteer#11967]
### Minimal, reproducible example

```TypeScript
Puppeteer with version 21.6.1 running on Docker returns a 500 to download Chromium.
```

### Error string

Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chrome-linux64.zip

### Expectation

Download the package

### Reality

Servers return a 500 for the link.

### Puppeteer version

21.6.1

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Linux

**Comment by Joker-Qu** [comment]
same issune!

**Comment by delanni** [comment]
We've also seen this. 
These URLs are getting deprecated https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chrome-linux64.zip in favor of https://storage.googleapis.com/chrome-for-testing-public/119.0.6045.105/linux64/chrome-linux64.zip

This should probably be updated in the code for Puppeteer when downloading chromium.

**Comment by XiaoYuTW** [comment]
Same issue for puppeteer 21.7.0

**Comment by thm-andrija** [comment]
Smae issue for puppeteer 21.5.1

**Comment by goranSpaceinch** [comment]
Same issue. From our AWS instance and github actions runner (both ubuntu-latest and our self-hosted), we get a 500 error. Some of our local machines work correctly (can download and can reach it during npm install), some don't, and no clear idea why.

**Comment by koddsson** [comment]
Example failure if that's helpful: https://github.com/modernweb-dev/web/actions/runs/8002558051/job/21856987686

**Comment by bernatixer** [comment]
On our side we upgraded to the new `22.2.0` version and had the issue fixed, even though be aware of the breaking changes that there are, thanks @OrKoN for the suggestion

**Comment by goranSpaceinch** [comment]
Confirming that the URL supplied by @delanni, placed in the PUPPETEER_DOWNLOAD_BASE_URL variable in our github actions yaml file (@OrKoN) resolves the issue for us.

Seems like Google's old URL is cached in some availability zones, which makes them only partially available.

**Comment by siddhigate12** [comment]
```
# node 20 with yarn + npm + puppeteer 21.7.0 version
FROM ghcr.io/puppeteer/puppeteer:21.7.0

...

ENV PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public
RUN npm install -g puppeteer@21.7.0

...
```
If you are running from docker you can set PUPPETEER_DOWNLOAD_BASE_URL variable in Dockerfile
