### ISSUE TITLE
[Feature]: I've done a little tool to easily generate code for puppeteer.

### ISSUE THREAD

**Issue by methaqualon** [puppeteer/puppeteer#11988]
### Feature description

Hey guys!

https://github.com/methaqualon/dragncode

You can play with it and feel free to communicate with me. I'm going to add much of functions in it, such as loops, arrays, some randomizing things (for more humanity).
Create feature requests in dragncode repo with funcs that you think should be in the product.

I have created it because pure puppeteer code is very (in bad point) customizable, but for just checking if some actions is able to be done it is too much.

Thank you!

![Снимок экрана от 2024-02-22 23-48-19](https://github.com/puppeteer/puppeteer/assets/48207388/c9cbfbf3-2a31-44e2-80c0-f765ecdc525a)

**Comment by OrKoN** [comment]
Looks interesting, thanks for sharing! Consider opening a PR to include it in https://github.com/transitive-bullshit/awesome-puppeteer

Also, please note that `waitForTimeout` was deprecated and is already removed in the latest versions.
