### ISSUE TITLE
[Bug]: Puppeteer V22.2.0 Not launching in Docker Container

### ISSUE THREAD

**Issue by invaderb** [puppeteer/puppeteer#11989]
### Minimal, reproducible example

```TypeScript
import * as puppeteer from 'puppeteer';

let page;

const getPage = async () => {
	if (page) return page;

	const browser = await puppeteer.launch({
		headless: 'shell', // Also tried true same issue
		args: ['--no-sandbox', '--disable-setuid-sandbox'],
	}); // hangs here
	console.log('Browser launched');
	page = await browser.newPage();

	return page;
};

export default getPage;

...

// Create a new page
const page = await getPage();


// Docker file
FROM node:20-alpine3.17 AS development
WORKDIR /usr/src/app

RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont
# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Puppeteer
RUN npm i -g puppeteer@22.2.0

# Add user so we don't need --no-sandbox.
RUN addgroup -S pptruser && adduser -S -G pptruser pptruser \
    #&& mkdir -p /home/pptruser/Downloads /app \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /usr/src/app

# Run everything after as non-privileged user.
USER pptruser

CMD [ "npm", "run", "start:dev"]
```

### Error string

No error just hangs

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Before 22.2 puppeteer launch just fine in the docker container but now it's just hanging no errors 
OS macOS Sonoma 14.3
Docker Version
- desktop 4.23.0
- engine 24.0.6

### Expectation

I expect the browser to launch in headless  modle

### Reality

just hangs like nothing is happening

### Puppeteer configuration file (if used)

```TypeScript
none
```

### Puppeteer version

22.2.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by OrKoN** [comment]
I am not able to reproduce. Note that if you are using a custom browser it needs to be compatible according to https://pptr.dev/chromium-support 

For example, the following minimal Dockerfile works:

```
FROM node:18-slim

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

USER node

WORKDIR /home/node

RUN npm i puppeteer@latest
RUN npx puppeteer browsers install chrome

CMD [ "node", "-i" ]
```

```
nodnode node@d8e63713e1ab:~$ node -i
Welcome to Node.js v18.19.1.
Type ".help" for more information.
> const puppeteer = await import('puppeteer')
undefined
> const browser = await puppeteer.launch({headless: 'shell'})
undefined
> await browser.close()
```

Also, see the Dockerfile we provide that is automatically tested before every release: https://github.com/puppeteer/puppeteer/tree/main/docker

**Comment by invaderb** [comment]
For any one having this issue I was able to resolve it by updating to ode:20-alpine3.20 and also adding udev to the package install list

`yaml
FROM node:20-alpine3.20 AS development
WORKDIR /usr/src/app

RUN apk add --no-cache \
      chromium \
      nss \
	  udev \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont
# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Puppeteer v13.5.0 works with Chromium 100.
RUN npm i -g puppeteer@22.11.2

# # Add user so we don't need --no-sandbox.
# RUN addgroup -S pptruser && adduser -S -G pptruser pptruser \
#     #&& mkdir -p /home/pptruser/Downloads /app \
#     && chown -R pptruser:pptruser /home/pptruser \
#     && chown -R pptruser:pptruser /usr/src/app

# # Run everything after as non-privileged user.
# USER pptruser

CMD [ "npm", "run", "start:dev"]
`
