### ISSUE TITLE
[Bug]: WaitForSelector Problem in docker 22.2.0

### ISSUE THREAD

**Issue by Leandree** [puppeteer/puppeteer#11993]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer-extra";
import { launch, getStream } from "puppeteer-stream";
import StealthPlugin from "puppeteer-extra-plugin-stealth";
import fs from "fs";
import { executablePath } from "puppeteer";  

const myfunction = () => {

const browser = await launch(puppeteer, {
    headless: true,
    defaultViewport: null,
    devtools: false,
    args: [
      "--window-size=1920,1080",
      "--window-position=1921,0",
      "--autoplay-policy=no-user-gesture-required",
      "--disable-gpu",
      "--headless=new",
      "--no-sandbox",
    ],
    ignoreDefaultArgs: ["--mute-audio"],
    executablePath: "/usr/bin/google-chrome",
  });

  const page = await browser.newPage();
  // await page.setDefaultNavigationTimeout(0);
  const navigationPromise = page.waitForNavigation();
  const context = browser.defaultBrowserContext();

  await context.overridePermissions("https://meet.google.com/", [
    "microphone",
    "camera",
    "notifications",
  ]);

  await page.waitForTimeout(2500);
  await page.goto("https://meet.google.com/njc-epqn-kmf" + "?hl=en", {
    waitUntil: "networkidle0",
    // ,
    // timeout: 10000,
  });

  await navigationPromise;

  await page.waitForSelector('input[aria-label="Your name"]', {
    visible: true,
    timeout: 50000,
    hidden: false,
  });

}

myfunction();
```

### Error string

WaitForSelector timeout

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am trying to find and input in order to fill it.

### Expectation

I expect the code to find the input based on 'input[aria-label="Your name"]' selector using waitForSelector

### Reality

I have a waitForSelector timeout
I used the exact same code with v22.2.0 and v22.0.0 of the docker image.
This issue only happen using v22.2.0.
PS: it's a code that i have been using with a lot of previous version of the docker image

### Puppeteer version

22.2.0

### Node version

v18.19.0

### Package manager

yarn

### Package manager version

1.22.21

### Operating system

Windows

**Comment by OrKoN** [comment]
Could you output the page's dom when the selector times out? is the element there? Note that Puppeteer does not do anything differently in Docker and the only difference could be in the website.
