### ISSUE TITLE
[Bug]: Puppeteer V22.2.0:  executable not found in Google Cloud Run container

### ISSUE THREAD

**Issue by AmusedArg** [puppeteer/puppeteer#11990]
### Minimal, reproducible example

```TypeScript
await puppeteer.launch({
        headless: 'shell',
        timeout: 0,
      });
```

### Error string

Error: Could not find Chrome (ver. 122.0.6261.57)

### Bug behavior

- [x] Flaky
- [ ] PDF

### Background

I updated to puppeteer 22.2.0 and now my app running on Cloud Run throws that error.
It used to work well with 21.7.0, nothing change in my app code

### Expectation

Puppeteer to open chrome

### Reality

Launch throws an error

### Puppeteer configuration file (if used)

```TypeScript
const { join } = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

22.2.0

### Node version

18.19.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by AmusedArg** [comment]
This is my Dockerfile which Google Cloud uses to build the image, this was working with 21.7.0
`FROM node:18-slim As production

WORKDIR /usr/src/app

COPY package*.json ./

# Install node modules
RUN npm ci --omit=dev

# Bundle app source
COPY . .

# Run the build command which creates the production bundle
RUN npm run build

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN npx puppeteer browsers install chrome

USER node

# Start the server using the production build
CMD [ "node", "dist/main.js" ]

`

**Comment by OrKoN** [comment]
I am not sure why it worked but the issue seems to be that the user is changed after browser is downloaded so the cache folder used to install and to launch the browser are different. The following reduced Dockerfile works:

```
FROM node:18-slim

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

USER node

WORKDIR /home/node

RUN npm i puppeteer@latest
RUN npx puppeteer browsers install chrome

CMD [ "node", "-i" ]
```


```
nodnode node@d8e63713e1ab:~$ node -i
Welcome to Node.js v18.19.1.
Type ".help" for more information.
> const puppeteer = await import('puppeteer')
undefined
> const browser = await puppeteer.launch({headless: 'shell'})
undefined
> await browser.close()

```
