### ISSUE TITLE
Emulate devices?

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#12]
Thanks to the [emulation](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/) domain, we can emulate mobile devices.

Is there a need for such an api in puppeteer? If yes, what's the scenario and what would api look like?

**Comment by aslushnikov** [comment]
@ebidel: do you think this might be needed?

**Comment by paulirish** [comment]
Certainly for testing with different UAs.

In LH we do a [pretty heavy emulation](https://github.com/GoogleChrome/lighthouse/blob/b347c70d1510bd2de07672488d55ab08695eda70/lighthouse-core/lib/emulation.js#L100-L118):

* devicemetricsoverride w/ nexus 5 stats
* setvisiblesize with viewport size
* setuseragentoverride
* settouchemulationenabled (for feature detects, etc)
* the extra ontouch handlers enabled via a `addScriptToEvaluateOnLoad`

One approach here is to separate emulating screen, touch events, and network UA. 
(as throttling and online/offline is already separate)

But yeah I think even casual users will need this. UA spoofing at a minimum, but then screenshots would also necessitate screen overrides.

**Comment by aslushnikov** [comment]
Sweet, there's already [Page.setUserAgentOverride](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetuseragentoverrideuseragent), and @pavelfeldman is addressing the rest in #37

**Comment by aslushnikov** [comment]
Device emulation has landed in https://github.com/GoogleChrome/puppeteer/pull/72.
