### ISSUE TITLE
Potentially use `userContext` in bidi cookies commands instead of browsing context to avoid browser implementation differences

### ISSUE THREAD

**Issue by lutien** [puppeteer/puppeteer#12004]
### Feature description

The Puppeteer implementation of cookies APIs with WebDriverBiDi uses mostly `context` type in `partition` field. From what I've understood in the chromium-bidi mapper it’s implemented as `userContext` id associated with this browsing context, when Firefox implements it as a combination of `userContext` id and `sourceOrigin`, that makes a bunch of test fail in Firefox (see the list below). One solution could be to directly use `userContext` of the browsing context in the partition field with type `storageKey` when sending one of the cookie commands, that should eliminate the differences in the implementations. 

List of affected tests:
- Cookie specs Page.setCookie should be able to set insecure cookie for HTTP website
- Cookie specs Page.setCookie should default to setting secure cookie for HTTPS websites
- Cookie specs Page.setCookie should set a cookie on a different domain
- Cookie specs Page.setCookie should set a cookie with a path
- Cookie specs Page.setCookie should set multiple cookies
- Cookie specs Page.setCookie should set secure same-site cookies from a frame
- Cookie specs Page.setCookie should work
- DefaultBrowserContext page.setCookie() should work

**Comment by OrKoN** [comment]
cc @sadym-chromium

**Comment by OrKoN** [comment]
@lutien what does it fail with? different attributes are reported back I assume? in that case, I think we need to adjust expectations in tests.

**Comment by OrKoN** [comment]
I am not sure using the userContext only would eliminate the differences because AFAIK Firefox requires a sourceOrigin to actually apply the cookie to the site?

**Comment by lutien** [comment]
> @lutien what does it fail with? different attributes are reported back I assume? in that case, I think we need to adjust expectations in tests.

It's not the attributes, but the whole cookies are missing. In some cases, I think it's missing cookies in `document.cookie`

> I am not sure using the userContext only would eliminate the differences because AFAIK Firefox requires a sourceOrigin to actually apply the cookie to the site?
No, it should be fine, you can set with `userContext` and with `domain` in the cookie object (which is a required field anyway).

**Comment by OrKoN** [comment]
Should not it be present in document.cookie if sourceOrigin and userContext are both correct?

**Comment by lutien** [comment]
> Should not it be present in document.cookie if sourceOrigin and userContext are both correct?

I think it should, I think the main problem is in a lot of tests (for example [this one](https://github.com/puppeteer/puppeteer/blob/main/test/src/cookies.spec.ts#L402-L414)) the expectation is that context has one page navigated, but a cookie is set on a different one.

**Comment by OrKoN** [comment]
I see, so you have tried to use `userContext` only (without sourceOrigin) and it fixes those tests? I was under (wrong) impression that Firefox requires sourceOrigin for all cookies.

**Comment by OrKoN** [comment]
@lutien do you know why the context partition key sets sourceOrigin if it is not required?

**Comment by lutien** [comment]
It indicates that in this case this `sourceOrigin` was used, basically explaining that this browsing context’s associated storage partition is a combination of this `userContext` and this `sourceOrigin`. You can say that `sourceOrigin` is required if you want to map back a storage partition for the browsing context, but you can also just request for a specific `userContext`.

**Comment by sadym-chromium** [comment]
@lutien is it what you mean? https://github.com/puppeteer/puppeteer/pull/12017

**Comment by sadym-chromium** [comment]
as discussed offline with @lutien, it's not an issue
