### ISSUE TITLE
[Bug]: Failed to launch the browser process; error while loading shared libraries: libatk-1.0.so.0

### ISSUE THREAD

**Issue by Beslinda** [puppeteer/puppeteer#12003]
### Minimal, reproducible example

```TypeScript
browser = await puppeteer.launch({
      executablePath: puppeteer.executablePath(),
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();
    const pdfOpts = merge({ printBackground: true }, pdfOptions);
```

### Error string

Failed to launch the browser process! /root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory   TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

### Bug behavior

- [x] Flaky
- [ ] PDF

### Background

I am using puppeteer to print some assets of the website

### Expectation

I expect the document to open in a new tab as a pdf

### Reality

I get an error stating: 
**Failed to launch the browser process!\n/root/.cache/puppeteer/chrome/linux-1056772/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory\n\n\nT**

### Puppeteer version

19.2.2

### Node version

16.14.0

### Package manager

yarn

### Package manager version

8.17.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Please make sure to have dependencies required on Linux installed https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux (that includes libatk)
