### ISSUE TITLE
[Bug]: Wrong cache path

### ISSUE THREAD

**Issue by dnsflnv** [puppeteer/puppeteer#12006]
### Minimal, reproducible example

```TypeScript
npm remove puppeteer
npm install puppeteer@21.11.0
npx puppeteer browsers install chrome
npm run build
pm2 restart all
```

### Error string

Could not find Chrome

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Trying to install Puppeteer on prod-server but, got errors with finding the browser path.

### Expectation

Show pdf

### Reality

Error "Could not find Chrome".

My application is not in $HOME folder, and during the installation, Pupeteer was created .cache folder in app path, not in $HOME path, and installed chrome to the same wrong path. So quick solution is just to copy cache in the right directory, or run `npx puppeteer browsers install chrome` from $HOME.

### Puppeteer version

21.11.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by OrKoN** [comment]
What is the output of `npx puppeteer browsers install chrome`? 

I am unable to reproduce. Make sure you do not have any environmental variables set to re-configure the cache dir or puppeteer configuration files. `npx puppeteer browsers install` takes that into account.

**Comment by dnsflnv** [comment]
> What is the output of `npx puppeteer browsers install chrome`?
> 
> I am unable to reproduce. Make sure you do not have any environmental variables set to re-configure the cache dir or puppeteer configuration files. `npx puppeteer browsers install` takes that into account.

Try to run it inside $HOME/subfolder, for example, our app placed in $HOME/backend

`acme@backend-prod:~/backend$ npx puppeteer browsers install chrome`

Output:

`chrome@121.0.6167.85 /home/acme/backend/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome
`

But must be `/home/acme/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome`

**Comment by OrKoN** [comment]
Yes, I am running inside a subfolder too.

Could you share the environmental variables that are set when you run `npx puppeteer browsers install` and the list of files in `/home/acme/backend`? (make sure to exclude any sensitive values, the following needs to be checked 1) env variables prefixed with PUPPETEER_, any sort of .puppeteerrc file). Also, what does `path.join(os.homedir(), '.cache', 'puppeteer')` in `node -i` output?

**Comment by dnsflnv** [comment]
Ok, I understand, thanks.
