### ISSUE TITLE
[Bug]: Puppeteer can't find the browser

### ISSUE THREAD

**Issue by claralop** [puppeteer/puppeteer#12007]
### Minimal, reproducible example

```TypeScript
import Resolver from '@forge/resolver';
import api, {route} from '@forge/api';
import puppeteer from 'puppeteer';

const resolver = new Resolver();

resolver.define('getText', async (req) => {
    //console.log(req);
    console.log("Current context: " + req.context);

    const browser = await puppeteer.launch();

    return 'Hello world!';
});

export const handler = resolver.getDefinitions();
```

### Error string

Error: Could not find Chrome (ver. 122.0.6261.69). This can occur if either  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or  2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.     at ChromeLauncher.resolveExecutablePath (webpack://jira-project-settings-page-custom-ui/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:259:1)     at ChromeLauncher.executablePath (webpack://jira-project-settings-page-custom-ui/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:190:1)     at ChromeLauncher.computeLaunchArguments (webpack://jira-project-settings-page-custom-ui/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:83:1)     at ChromeLauncher.launch (webpack://jira-project-settings-page-custom-ui/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:44:1)     at <anonymous> (webpack://jira-project-settings-page-custom-ui/src/index.js:19:21)     at Object.resolve (webpack://jira-project-settings-page-custom-ui/node_modules/@forge/resolver/out/index.js:53:1)     at async t.<computed> [as handler] (/var/task/index.cjs:1:153936)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Installed puppeter version 22.3.0 in a Forge project using react. The app runs in the cloud.

Although I have followed the configuration instructions, I still cannot find the Chrome browser, although the browser executable is downloaded to the following path of the Forge project (from the root of the project):

.cache/puppeteer/chrome/mac-122.0.6261.69/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing

### Expectation

Have puppeteer find the browser and run it

### Reality

Can't find the browser
That is the configuration:

<img width="391" alt="Screenshot 2024-02-27 at 15 46 58" src="https://github.com/puppeteer/puppeteer/assets/161483461/578d59e8-999d-497f-9915-dd752e44d913">
<img width="978" alt="Screenshot 2024-02-27 at 15 50 00" src="https://github.com/puppeteer/puppeteer/assets/161483461/2f5469cb-ee78-4906-80e5-02e326661188">
<img width="1169" alt="Screenshot 2024-02-27 at 15 52 04" src="https://github.com/puppeteer/puppeteer/assets/161483461/abe3caa0-1276-47bd-9827-5c6105194476">
<img width="1047" alt="Screenshot 2024-02-27 at 15 54 32" src="https://github.com/puppeteer/puppeteer/assets/161483461/bfa6738c-d42f-4365-99b4-e66183b5c613">

What is the problem?

### Puppeteer configuration file (if used)

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

22.3.0

### Node version

18

### Package manager

npm

### Package manager version

10.2.4

### Operating system

macOS

**Comment by OrKoN** [comment]
The browser needs to be downloaded on the server environment as well: so you need to make sure to install Puppeteer after the configuration is available on the server or run `npx puppeteer browsers install chrome` after installation as suggested. The error message shows where it looks for Chrome so you should be able to troubleshoot from there.
