### ISSUE TITLE
Preloading a Script

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#1201]
This might not be an issue, more like a reference to how to mimic preload feature from nightmare/electron. 

If this looks good maybe we can include this in docs.
If this needs improvement, then please suggest.

If we want to change some default page variables before the page loads, we got no way of doing this in puppeteer. If we do, I don't see it in any docs or code.

For example, I might want to change navigator object properties and mock tests.

```js
// overwrite the `languages` property to use a custom getter
Object.defineProperty(navigator, 'languages', {
  get: function() {
    return ['en-US', 'en'];
  },
});

// overwrite the `plugins` property to use a custom getter
Object.defineProperty(navigator, 'plugins', {
  get: function() {
    // this just needs to have `length > 0`, but we could mock the plugins too
    return [1, 2, 3, 4, 5];
  },
});
```

It's easily doable with nightmare,

```js
var Nightmare = require('nightmare'),
  nightmare = Nightmare({
  webPreferences: {
        preload: 'alertMessage.js' // <-- this will get executed first, so we can change whatever object we want
      }
});
```

Note this is not addScriptTag or exposeFunction. exposeFunction will add a function, addScriptTag will do something on load. But, a preload script will load first, and make whatever changes we need to change.

I am testing this function right now, `evaluateOnNewDocument`. But defining a file which will load before every page load seems much more convenient.

Right now, I can do this.
```js
function preload() {
  // overwrite the `languages` property to use a custom getter
  Object.defineProperty(navigator, "languages", {
    get: function() {
      return ["en-US", "en", "bn", "github", "idontknowlanguage"];
    }
  });

  // overwrite the `plugins` property to use a custom getter
  Object.defineProperty(navigator, "plugins", {
    get: function() {
      // this just needs to have `length > 0`, but we could mock the plugins too
      return [1, 2, 3, 4, 5];
    }
  });
}

const page = await browser.newPage();
await page.evaluateOnNewDocument(preload);
```
Or like this in seperate file.
```js
// preload.js
module.exports = function(){
    // overwrite the `languages` property to use a custom getter
    Object.defineProperty(navigator, "languages", {
      get: function() {
        return ["en-US", "en", "bn", "c", "js"];
      }
    });

    // overwrite the `plugins` property to use a custom getter
    Object.defineProperty(navigator, "plugins", {
      get: function() {
        // this just needs to have `length > 0`, but we could mock the plugins too
        return [1, 2, 3, 4, 5];
      }
    });
}

// in out puppeteer
await page.evaluateOnNewDocument(require("./preload"));
```
Maybe we can include some preload scripts/list of files to preload in the `browser.newPage()`
for example, 

```js
browser.newPage({
 preload: "this.js"
})

// or something like this which will execute in order or async
browser.newPage({
 preload: ["this.js"],
 preloadAsync: true
})
```

**Comment by ebidel** [comment]
I really like your separate file example. Nothing wrong with that approach. Great use of `evaluateOnNewDocument`.

Adding an example might be overkill for this use case, but adding an similar example to docs would be good. `evaluateOnNewDocument` needs some example snippets :) Interested in sending a PR?

**Comment by entrptaher** [comment]
Done a sample PR, https://github.com/GoogleChrome/puppeteer/pull/1202
I forgot that this is my first PR on any google repo. I wanted to avoid a PR :grin:.

**Comment by tomgallagher** [comment]
Seems to me that evaluateOnNewDocument runs after the domcontentloaded event. Anyone know of any way to inject a script at document_start, to use a Chrome Extension API analogy? So before the document has loaded?

**Comment by aslushnikov** [comment]
@tomgallagher doesn't look like this to me. The following script prints "Loaded!" for me.

```js
const puppeteer = require('puppeteer');

(async() => {

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.evaluateOnNewDocument(() => {
    window.addEventListener('DOMContentLoaded', () => console.log('Loaded!'));
  });
  page.on('console', msg => console.log(msg.text()));
  await page.goto('http://example.com');

  await browser.close();
})();
```

**Comment by tomgallagher** [comment]
Hmm.

This code produced different results.

In test.js, I have this:

`window.addEventListener('DOMContentLoaded', () => window.turboMessaging('Loaded!'));`

which with the following script:

```
async function getPage(targetURL, pageWidth, pageHeight, useragent) {
    
    const userAgent = useragent;
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setViewport({width: pageWidth, height: pageHeight});
    await page.setUserAgent(userAgent);
    //add the messaging function
    await page.exposeFunction('turboMessaging', text => debug(text) );
    //inject our scripts
    const test = fs.readFileSync('./lib/browser_extensions/test.js', 'utf8');
    await page.evaluateOnNewDocument(test);
    await page.goto(targetURL, {waitUntil: ["domcontentloaded", "networkidle2"]});
    let content = await page.content();
    await page.close();
    await browser.close();
    
}

```
produced this via debug:

```
CHROME-HANDLER Loaded! +2s
  CHROME-HANDLER Loaded! +518ms
  CHROME-HANDLER Loaded! +10ms
  CHROME-HANDLER Loaded! +193ms
  CHROME-HANDLER Loaded! +8ms
  CHROME-HANDLER Loaded! +262ms
  CHROME-HANDLER Loaded! +4ms
  CHROME-HANDLER Loaded! +4ms
  CHROME-HANDLER Loaded! +4ms
  CHROME-HANDLER Loaded! +4ms
  CHROME-HANDLER Loaded! +5ms
  CHROME-HANDLER Loaded! +703ms
  CHROME-HANDLER Loaded! +26ms
  CHROME-HANDLER Loaded! +27ms
  CHROME-HANDLER Loaded! +114ms
  CHROME-HANDLER Loaded! +268ms

```
etc.

I'm a bit mystified by this result. The reason I said earlier that it was firing after domcontentloaded is that I was using mutation summary to watch things being added to a page and the only items that appeared were those I would normally expect to appear after the domcontentloaded event. Also I tested the same page in the browser and the first time, 2 seconds, from debug report was suspiciously high.

**Comment by aslushnikov** [comment]
@tomgallagher I'm not sure I follow: where's the unexpected behavior?

**Comment by tomgallagher** [comment]
Sorry, not the clearest example. I would expect to see loaded once per page if I'm listening for the domcontentloaded event. But I now see from the docs that `page.evaluateOnNewDocument`
 will also fire whenever a child frame is attached or navigated. So that could happen a lot.

However, I'm still not getting the preload scripts right. I'll continue trying.
