### ISSUE TITLE
Cookies are leaking from the "should isolate cookies in browser contexts" test

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12010]
Apparently, only in Firefox CDP.

Enable the following two tests:

```
  Cookie specs
    Page.setCookie
      ✔ should isolate cookies in browser contexts (122ms)

  DefaultBrowserContext
    ✔ page.cookies() should work (58ms)
```

Run `npm run test:firefox:headless`

Actual results:

```
  1) Cookie specs
       Page.setCookie
         should isolate cookies in browser contexts:
     Error: expect(received).toHaveLength(expected)

Expected length: 1
Received length: 2
Received array:  [{"domain": "localhost", "expires": -1, "httpOnly": false, "name": "page1cookie", "path": "/", "secure": false, "session": true, "size": 21, "value": "page1value"}, {"domain": "localhost", "expires": -1, "httpOnly": false, "name": "page2cookie", "path": "/", "secure": false, "session": true, "size": 21, "value": "page2value"}]
      at Context.<anonymous> (test/src/cookies.spec.ts:240:24)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) DefaultBrowserContext
       page.cookies() should work:
     Error: expect(received).toHaveLength(expected)

Expected length: 1
Received length: 3
Received array:  [{"domain": "localhost", "expires": -1, "httpOnly": false, "name": "page1cookie", "path": "/", "secure": false, "session": true, "size": 21, "value": "page1value"}, {"domain": "localhost", "expires": -1, "httpOnly": false, "name": "page2cookie", "path": "/", "secure": false, "session": true, "size": 21, "value": "page2value"}, {"domain": "localhost", "expires": -1, "httpOnly": false, "name": "username", "path": "/", "secure": false, "session": true, "size": 16, "value": "John Doe"}]
      at expectCookieEquals (test/src/mocha-utils.ts:396:19)
      at Context.<anonymous> (test/src/defaultbrowsercontext.spec.ts:25:29)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by OrKoN** [comment]
Regressed since v21.10.0

**Comment by OrKoN** [comment]
@whimboo it looks like the root cause of this is that Firefox CDP does not isolate the user contexts.

**Comment by OrKoN** [comment]
The context is closed and re-created in getTestState so the second test should have blank state.

**Comment by whimboo** [comment]
> The context is closed and re-created in getTestState so the second test should have blank state.

Not for the `page1cookie` cookie given that this is added to the default context. In both tests we use the `page` and not `context` to set it. As such it will not be removed after removing a given user context. Or do I miss something?

**Comment by OrKoN** [comment]
@whimboo the default context is an incognito user context as well (see GetTestState)

**Comment by whimboo** [comment]
@OrKoN would it be ok with you if we mark `[defaultbrowsercontext.spec] DefaultBrowserContext page.cookies() should work` as intermittently failing with CDP for Firefox? It's [perma failing in our CI ](https://treeherder.mozilla.org/jobs?repo=try&revision=2e031f55d96011593d4dd755dca11cfe94cdf89d&searchStr=cdp)when I sync 22.4.0

**Comment by OrKoN** [comment]
@whimboo I have opened a PR to mark it as pass/fail
