### ISSUE TITLE
The provided selector is empty

### ISSUE THREAD

**Issue by iagormoraes** [puppeteer/puppeteer#1203]
I can't type on input tag to simulate a login at Facebook page. I receive a catch on promise:

Error: Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty.

```js
const puppeteer = require('puppeteer')

const scrape = async () => {
    try {
        const browser = await puppeteer.launch({headless: false})
        const page = await browser.newPage()

        await page.goto('https://www.facebook.com/', {waitUntil: 'networkidle'})
        await page.click('#pass')
        await page.type('mylittlesecret')
    } catch(e) {
        console.log('something went wrong: ' + e)
    }
}

scrape()
```

**Comment by vsemozhetbyt** [comment]
What puppeteer version do you use?

**Comment by iagormoraes** [comment]
the latest @0.12.0

**Comment by vsemozhetbyt** [comment]
It seems `page.type()` [requires a selector](https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#pagetypeselector-text-options).

Try to replace
```js
        await page.click('#pass')
        await page.type('mylittlesecret')
```
with
```js
        await page.type('#pass', 'mylittlesecret')
```

**Comment by iagormoraes** [comment]
That worked, much simplified. Thanks a lot!
