### ISSUE TITLE
[Bug]: Chromium linux/x64 builds do not have is_chrome_for_testing build flag

### ISSUE THREAD

**Issue by DanielHeath** [puppeteer/puppeteer#12032]
### Minimal, reproducible example

```TypeScript
Launch chromium@latest
Open devtools
Paste text into devtools console
```

### Error string

The non-testing build of chromium is installed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Text is pasted (permitted when chromium is built in is_chrome_for_testing mode)

### Reality

`Type 'allow pasting'` self-xss warning is shown.

### Puppeteer version

2.1.0

### Node version

v20.11.0

### Package manager

yarn

### Package manager version

3.3.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Hi, thanks for the report but I believe it is working as expected. Chromium builds are just plain Chromium builds and there are currently no chromium builds with is_chrome_for_testing flag available as far as I know cc @mathiasbynens

**Comment by mathiasbynens** [comment]
Indeed. Although it is possible to build “Chromium for Testing” (by enabling `is_chrome_for_testing` but not `is_chrome_for_testing_branded`), it’s not something we officially distribute.
