### ISSUE TITLE
[Bug]: Unable to use vulkan for hardware acceleration in headless mode

### ISSUE THREAD

**Issue by ruochenjia** [puppeteer/puppeteer#12048]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const chrome = await puppeteer.launch({
	pipe: true,
	dumpio: true,
	channel: "chrome",
	product: "chrome",
	timeout: 10000,
	headless: false,
	handleSIGHUP: false,
	handleSIGINT: false,
	handleSIGTERM: false,
	protocolTimeout: 5000,
	defaultViewport: {
		width: 1280,
		height: 720,
		isMobile: false,
		hasTouch: false,
		isLandscape: true,
		deviceScaleFactor: 1
	},
	args: [
		// Flags for using vulkan is explicitly specified
		"--enable-gpu",
		"--use-vulkan"
	]
});
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Hardware acceleration for the headless browser should be enabled, and use vulkan for rendering.

### Reality

Hardware acceleration is enabled, but vulkan is disabled.

Screenshot for the browser instance at `chrome://gpu`:
![image](https://github.com/puppeteer/puppeteer/assets/66373748/ea6a2a4c-de87-4c57-987c-ea9cbd6d4112)

### Puppeteer version

22.4.0

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Could you try the instructions from https://developer.chrome.com/blog/supercharge-web-ai-testing ? It's possible that drivers are missing? If that does not work, please file a crbug.com/new for the Headless component.

**Comment by OrKoN** [comment]
Updated in https://github.com/puppeteer/puppeteer/pull/12052#pullrequestreview-1922046124
