### ISSUE TITLE
[Feature]: Update documentation to run Puppeteer with Docker using Alpine 3.19

### ISSUE THREAD

**Issue by ab14bhardwaj** [puppeteer/puppeteer#12046]
### Feature description

- Currently the documentation on how to run Puppeteer with Docker + Alpine is very old and not helpful as the latest version of Alpine supports Chromium version  "121.0.6167.85" but as per the documentation it's pointing that Alpine only supports Chromium version "100"
- Please update the documentation and add an update to the Puppeteer version supported with the latest Alpine version.

Documentation link: https://pptr.dev/troubleshooting#running-on-alpine
Alpine Latest: https://www.alpinelinux.org/posts/Alpine-3.19.1-released.html

**Comment by OrKoN** [comment]
Puppeteer provides an official Docker image https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer but we rely on community contributions to update guidance for various platforms/docker images/cloud systems (it is probably best not too mention specific versions in the troubleshooting guide) as we cannot follow changes everywhere ourselves. So if you got the latest versions running on Alpine, please open a PR to update the docs.

**Comment by ab14bhardwaj** [comment]
@OrKoN I can now run Puppeteer with the latest Alpine and Chromium versions but I am getting issues where browser processes are not closed and causing the issue.

### Puppeteer Version
-  20.9.0

### Puppeteer Code
```
async function generatePDF(pdfData) {
  const {
    destinationPath,
    html,
    footer = null,
  } = pdfData;

  let browser;

  try {
    // Launch headless browser
    browser = await puppeteer.launch({
      // chrome has updated its default headless mode, to use the new mode you need to use "new" instead of "true"
      // Please revert this incase of any issues and set "headless: true"
      headless: 'new',
      args: ['--no-sandbox', '--disabled-setupid-sandbox'],
      ignoreDefaultArgs: ['--disable-extensions'],
    });

    // Create new page
    const page = await browser.newPage();

    // Set page content
    await page.setContent(html, { waitUntil: ['networkidle0', 'networkidle2'] });

    const defaultConfig = {
      path: destinationPath,
      format: 'A4',
      displayHeaderFooter: true,
      headerTemplate: '<div> </div',
      footerTemplate: footer,
      margin: {
        top: 20,
        bottom: 50,
      },
    };

    await page.pdf(defaultConfig);
  } catch (error) {
    throw new Error('Could not generate pdf');
  } finally {
    // Close browser
    if (browser) {
      await browser.close();
    }
  }
}
```

In the above code, I am always closing the browser but somehow there are zombie processes of chromium which are not getting killed and I keep getting the below error message

```
Failed to launch the browser process!
/usr/bin/chromium-browser: line 12: can't fork: Resource temporarily unavailable
```

**Comment by ab14bhardwaj** [comment]
@OrKoN I was able to fix it using the `tini` package by just adding the below lines in my docker file.

```
RUN apk add --no-cache tini
# Tini is now available at /sbin/tini
ENTRYPOINT ["/sbin/tini", "--"]
```

- [tini](https://github.com/krallin/tini)
- [dumb-init](https://github.com/Yelp/dumb-init) (another alternative)
