### ISSUE TITLE
Helper function to get response of page.goto()

### ISSUE THREAD

**Issue by dustyhorizon** [puppeteer/puppeteer#1205]
Hello,

Is there an easy way to get the response of a page? `page.on('response', () => { ... })` gives the response of every request on the page. However I am looking for something like page.response() to get the page's main response so that I can access data such as the header, statusCode etc.

Currently using Puppeteer v0.12.0 inside a docker container.

Please advise on the matter.

**Comment by vsemozhetbyt** [comment]
`page.goto()` already [resolves to the main response](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options):
```js
    const response = await page.goto('https://example.org/');
    console.log(response.headers);
```
```console
{ date: 'Sun, 29 Oct 2017 13:35:59 GMT',
  'content-encoding': 'gzip',
  'last-modified': 'Fri, 09 Aug 2013 23:54:35 GMT',
  server: 'ECS (lga/1318)',
  etag: '"359670651+gzip"',
  vary: 'Accept-Encoding',
  'x-cache': 'HIT',
  'content-type': 'text/html',
  status: '200',
  'cache-control': 'max-age=604800',
  'content-length': '606',
  expires: 'Sun, 05 Nov 2017 13:35:59 GMT' }
```

**Comment by dustyhorizon** [comment]
Apologies had a brain fart, kept inspecting the page object instead of the returned response ...

**Comment by leo020588** [comment]
It also works for `page.waitForNavigation()`.
```javascript
const response = await page.waitForNavigation();
```
If you need the response after clicking a link:
```javascript
const [response] = await Promise.all([
  page.waitForNavigation(),
  page.click('a')
]);
```

**Comment by gsouf** [comment]
correction to @vsemozhetbyt message, headers is actually a function: ``response.headers()``

**Comment by WISeAgent** [comment]
Is it what you want?
( async () => {
    await page.goto('your_URL_here', {waitUntil: 'networkidle0'});
    const body = await page.content();
})();

**Comment by CaledoniaProject** [comment]
@vsemozhetbyt What would happen if there's a response header named `status`?

```
HTTP/1.1 200 OK
X-Powered-By: PHP/5.5
status: Whatever

<body>
```

**Comment by jisspala** [comment]
> `page.goto()` already [resolves to the main response](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options):
> 
> ```js
>     const response = await page.goto('https://example.org/');
>     console.log(response.headers);
> ```
> 
> ```
> { date: 'Sun, 29 Oct 2017 13:35:59 GMT',
>   'content-encoding': 'gzip',
>   'last-modified': 'Fri, 09 Aug 2013 23:54:35 GMT',
>   server: 'ECS (lga/1318)',
>   etag: '"359670651+gzip"',
>   vary: 'Accept-Encoding',
>   'x-cache': 'HIT',
>   'content-type': 'text/html',
>   status: '200',
>   'cache-control': 'max-age=604800',
>   'content-length': '606',
>   expires: 'Sun, 05 Nov 2017 13:35:59 GMT' }
> ```

in new version, headers is a function. So Use  
console.log(response.headers());

**Comment by mirismaili** [comment]
Another change I saw (in addition to `headers` -> `headers()`) is that `status` is no longer a memeber of *headers*. It has its own method: `response.status()` (and is a `number` not a `string`).

Example with [Chai](https://www.chaijs.com/):
```js
expect(response.status()).to.equal(200)
```

**Comment by ralleh** [comment]
> `page.goto()` already [resolves to the main response](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options):
> 
> ```js
>     const response = await page.goto('https://example.org/');
>     console.log(response.headers);
> ```
> 
> ```
> { date: 'Sun, 29 Oct 2017 13:35:59 GMT',
>   'content-encoding': 'gzip',
>   'last-modified': 'Fri, 09 Aug 2013 23:54:35 GMT',
>   server: 'ECS (lga/1318)',
>   etag: '"359670651+gzip"',
>   vary: 'Accept-Encoding',
>   'x-cache': 'HIT',
>   'content-type': 'text/html',
>   status: '200',
>   'cache-control': 'max-age=604800',
>   'content-length': '606',
>   expires: 'Sun, 05 Nov 2017 13:35:59 GMT' }
> ```

For me response.headers is a function not a JSON? And it doesn't include the status code, that I was looking for:

`{
  server: 'Server',
  'content-type': 'text/html;charset=UTF-8',
  'x-amz-rid': 'N75T0CSRJ0J7V3HY6SRC',
  'accept-ch': 'ect,rtt,downlink',
  'accept-ch-lifetime': '86400',
  'cache-control': 'no-cache, no-transform',
  p3p: 'policyref="https://www.amazon.de/w3c/p3p.xml",CP="CAO DSP LAW CUR ADM IVAo IVDo CONo OTPo OUR DELi PUBi OTRi BUS PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA HEA PRE LOC GOV OTC "',
  'content-encoding': 'gzip',
  'x-xss-protection': '1;',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=47474747; includeSubDomains; preload',
  'x-frame-options': 'SAMEORIGIN',
  date: 'Thu, 05 Nov 2020 04:10:58 GMT',
  vary: 'Accept-Encoding',
  'set-cookie': 'session-id=259-9251268-8017322; Domain=.amazon.de; Expires=Fri, 05-Nov-2021 04:10:58 GMT; Path=/; Secure\n' +
    'session-id-time=2082787201l; Domain=.amazon.de; Expires=Fri, 05-Nov-2021 04:10:58 GMT; Path=/; Secure\n' +
    'i18n-prefs=EUR; Domain=.amazon.de; Expires=Fri, 05-Nov-2021 04:10:58 GMT; Path=/'
}`

Needed to grab it via response.status()

Anyway... how do I grab the statusMessage?

**Comment by ralleh** [comment]
> Another change I saw (in addition to `headers` -> `headers()`) is that `status` is no longer a memeber of _headers_. It has its own method: `response.status()` (and is a `number` not a `string`).
> 
> Example with [Chai](https://www.chaijs.com/):
> 
> ```js
> expect(response.status()).to.equal(200)
> ```

Awesome, was already wondering about it. Do you know how I can grab the status message (error code that corresponds to the status msg, for example not found for 404?

**Comment by markwoodward23** [comment]
As mentioned above, Puppeteer APIs have changed, it's now: 
```
const { status, headers, statusText } = await page.goto(...);
console.log(status()); // 404: number
console.log(headers()); // { object with headers }
console.log(statusText()); // Not found: string
```

**Comment by ralleh** [comment]
> 

Yeah, I got it to work like that but actually statusText() is always an empty string, no matter how I implement it. Does it work for you as intended (aka "Not found" for status 404) and if yes, could you please give a code example?
