### ISSUE TITLE
[Bug]: what's the meaning of response.timing().requestTime?

### ISSUE THREAD

**Issue by suyue0731** [puppeteer/puppeteer#12057]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  page.goto('whatever url')
  page.on('response', (response) => {
    console.log(response.timing())
    // console.log output
    // so, what does the requestTime mean?
    // the document says that: Timing's requestTime is a baseline in seconds
    // but how to convert this baseline to the real world timestamp?
    // {
    //   requestTime: 579833.436389,
    //   proxyStart: -1,
    //   proxyEnd: -1,
    //   dnsStart: -1,
    //   dnsEnd: -1,
    //   connectStart: -1,
    //   connectEnd: -1,
    //   sslStart: -1,
    //   sslEnd: -1,
    //   workerStart: -1,
    //   workerReady: -1,
    //   workerFetchStart: -1,
    //   workerRespondWithSettled: -1,
    //   sendStart: 0.019,
    //   sendEnd: 0.019,
    //   pushStart: 0,
    //   pushEnd: 0,
    //   receiveHeadersStart: 0.588,
    //   receiveHeadersEnd: 0.705
    // }
  })
})
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I expected the requestTime maybe is a timestamp like Date.now()

### Reality

I got a number like 579833.436389 in seconds，how to convert it to the real world timestamp?

### Puppeteer version

21.1.0

### Node version

16.20.1

### Package manager

npm

### Package manager version

8.19.4

### Operating system

macOS

**Comment by OrKoN** [comment]
Probably this is the explanation https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/loader/fetch/resource_load_timing.h;l=103;drc=f4a00cc248dd2dc8ec8759fb51620d47b5114090 so I think you need to add that to the wallTime on the document navigation request.

**Comment by suyue0731** [comment]
> Probably this is the explanation https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/loader/fetch/resource_load_timing.h;l=103;drc=f4a00cc248dd2dc8ec8759fb51620d47b5114090 so I think you need to add that to the wallTime on the document navigation request.

thanks！
