### ISSUE TITLE
[Bug]: load js fail

### ISSUE THREAD

**Issue by SevenWangMr** [puppeteer/puppeteer#12063]
### Steps to reproduce

await puppeteer.launch({
        ignoreHTTPSErrors: true,
        headless: false,
        defaultViewport: null, // 禁用默认视口大小
        args: ['--window-size=1920,1080','--no-sandbox','--disable-setuid-sandbox','--disable-web-security', '--allow-running-insecure-content'] // 设置窗口大小
    });
    
    for (let i = 0; i < cookieJson.length; i++) {
            let domain = cookieJson[i]["domain"];
            const cookies = {
                // url: "https://"+domain,
                url: cookieJson[i]["url"],
                name: cookieJson[i]["name"],
                value: cookieJson[i]["value"],
                domain: domain,
                hostOnly: cookieJson[i]["hostOnly"],
                path: cookieJson[i]["path"],
                secure: cookieJson[i]["secure"],
                httpOnly: cookieJson[i]["httpOnly"],
                session: cookieJson[i]["session"],
                expirationDate: cookieJson[i]["expirationDate"],
                sameSite: ''
            };
            await page.setCookie(cookies).then(() => {
            }, (error) => {
                console.error(error);
            });
        }
                await page.goto("xxxxx", { waitUntil: 'domcontentloaded' });
                
After entering the page, the interface request will dynamically request an HTML, which will load some JavaScript.
Later, an error occurred during page rendering

the error:
chunk-libs.js:15 [import-html-entry]: error occurs while executing entry script https://g1.itc.cn/bsf-mp-prod/mp_micro_contentmanager/202403071626/dist/js/app.a91dc0afd8.js
i @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
(anonymous) @ chunk-libs.js:15
(anonymous) @ chunk-libs.js:15
chunk-libs.js:1 Uncaught TypeError: application 'contentManagement1' died in status LOADING_SOURCE_CODE: 'get' on proxy: property 'createElement' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function createElement() { [native code] }' but got 'function(){ze.__currentLockingSandbox__||(ze.__currentLockingSandbox__=e.name);for(var n=arguments.length,o=new...<omitted>...c}')
    at Object.cc12 (chunk-libs.js:66:8908)
    at r (app.a91dc0afd8.js:1:1469)
    at 0cfb (chunk-libs.js:1:7392)
    at r (app.a91dc0afd8.js:1:1469)
    at 06cf (chunk-libs.js:1:3959)
    at r (app.a91dc0afd8.js:1:1469)
    at 23e7 (chunk-libs.js:25:118709)
    at r (app.a91dc0afd8.js:1:1469)
    at Object.d9f5 (chunk-libs.js:66:40313)
    at r (app.a91dc0afd8.js:1:1469)
    
    The dynamically loaded HTML is
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>发文</title>
        <script>
            if (!window.__POWERED_BY_QIANKUN__) {
                loadScript('https://statics.itc.cn/mpo/bootCDN/common/3.0.6-jquery.min.js')
                loadScript('//js.tv.itc.cn/base/plugin/showPlayer.js')
            }
            function loadScript(url) {
                const script = document.createElement('script')
                script.src = url
                document.head.appendChild(script)
            }
        </script>
        <link href="js/app.a91dc0afd8.js" rel="preload" as="script">
        <link href="js/chunk-element.js" rel="preload" as="script">
        <link href="js/chunk-libs.js" rel="preload" as="script">
        <link href="js/chunk-meet.js" rel="preload" as="script">
    </head>
    <body class="content">
        <noscript>
            <strong>We're sorry but app-vue-history doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
        </noscript>
        <div id="app"></div>
        <script src="js/chunk-meet.js"></script>
        <script src="js/chunk-element.js"></script>
        <script src="js/chunk-libs.js"></script>
        <script src="js/app.a91dc0afd8.js"></script>
    </body>
</html>

        
        

### Expected results

Expect to find the newly loaded HTML referenced JavaScript file

### Actual results

chunk-libs.js:15 [import-html-entry]: error occurs while executing entry script https://g1.itc.cn/bsf-mp-prod/mp_micro_contentmanager/202403071626/dist/js/app.a91dc0afd8.js
i @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
a @ chunk-libs.js:15
(anonymous) @ chunk-libs.js:15
(anonymous) @ chunk-libs.js:15
chunk-libs.js:1 Uncaught TypeError: application 'contentManagement1' died in status LOADING_SOURCE_CODE: 'get' on proxy: property 'createElement' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function createElement() { [native code] }' but got 'function(){ze.__currentLockingSandbox__||(ze.__currentLockingSandbox__=e.name);for(var n=arguments.length,o=new...<omitted>...c}')
    at Object.cc12 (chunk-libs.js:66:8908)
    at r (app.a91dc0afd8.js:1:1469)
    at 0cfb (chunk-libs.js:1:7392)
    at r (app.a91dc0afd8.js:1:1469)
    at 06cf (chunk-libs.js:1:3959)
    at r (app.a91dc0afd8.js:1:1469)
    at 23e7 (chunk-libs.js:25:118709)
    at r (app.a91dc0afd8.js:1:1469)
    at Object.d9f5 (chunk-libs.js:66:40313)
    at r (app.a91dc0afd8.js:1:1469)

**Comment by OrKoN** [comment]
The error happens on the page? It does not look like an issue within Puppeteer. Consider asking on StackOverflow how to achieve what you need.

**Comment by SevenWangMr** [comment]
However, it is normal to open the page in Google Chrome, and this error is reported when opening the page in Puppete
[import-html-entry]: error occurs while executing entry script https://g1.itc.cn/bsf-mp-prod/mp_micro_contentmanager/202403071626/dist/js/app.a91dc0afd8.js
