### ISSUE TITLE
Screenshot seems to be out of sync

### ISSUE THREAD

**Issue by rudiedirkx** [puppeteer/puppeteer#1206]
* Puppeteer version: 0.12.0
* Platform / OS version: Ubuntu 16.04.3

My screenshot function:

```
var screenshotIndex = 0;
async function screenshot(page) {
	const name = 'x' + (++screenshotIndex) + '.png';
	console.log(name);
	page.screenshot({path: name});
}
```

The script:

```
await page.goto(cfg.baseUrl);
await screenshot(page);

await page.type('input[name="username"]', 'personeel');
await page.type('input[name="password"]', 'test');
await screenshot(page);

await page.click('#login');
await page.waitForNavigation();
await screenshot(page);
```

So what I would expect:

1. screenshot of empty login form
2. screenshot of username & password
3. screenshot of page after login and page load

Instead:

1. screenshot of form with username (**incorrect**, screenshot is too late)
2. screenshot of form with username & password (**correct**)
3. screenshot of page after login and page load (**correct**)

I thought it might've been my mistunderstanding async/await and making `screenshot()` async, but it's the same result for manually calling

```
await page.screenshot({path: 'x1.png'});
```

Are screenshots always async? `await` makes it sound like everything waits for the screenshot to be done. It doesn't seem to. I really want it to.

**Comment by ebidel** [comment]
You should be returning the `page.screenshot` Promise in your own screenshot function:

```
async function screenshot(page) {
  ...
  return page.screenshot({path: name});
}
```

**Comment by aslushnikov** [comment]
@ebidel nailed it.

**Comment by rudiedirkx** [comment]
Like I said, if I don't use the screenshot function and call

```
await page.screenshot({path: 'x1.png'});
```

every time, it's still async.

If screenshot() returns a Promise, it doesn't have to be `async`, right? I probably don't understand how async/await works exactly, but I don't think that's the problem.

**Comment by rudiedirkx** [comment]
I don't get it. Now these seem to work:

```
async function screenshot(page) {
	await page.screenshot({path: name});
}
```

and

```
function screenshot(page) {
	return page.screenshot({path: name});
}
```

I'm sure I've tried both.

And now directly calling `page.screenshot()` works too...

So all works like I expect, and probably how it's supposed to. Thanks, I guess =)
