### ISSUE TITLE
[Feature]: Support new `using` syntax for browser and page 

### ISSUE THREAD

**Issue by ymulenll** [puppeteer/puppeteer#12061]
### Feature description

There is a new [ES proposal](https://github.com/tc39/proposal-explicit-resource-management) that is in Stage 3 and was also supported by [TypeScript v5.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management).

It's the [Explicit Resource Management](https://github.com/tc39/proposal-explicit-resource-management).

My feature proposal is to support that for Browser and Page classes by implementing the `Symbol.asyncDispose` symbol, so we could use the `using` syntax instead of having to use the "`let`, `try`, `finally`" approach

**Comment by OrKoN** [comment]
Thanks for the feature request. Browser and Page classes already define dispose symbols so you could probably already use them but we won't be making it the official part of our interface before the proposal moves to the next stage.
