### ISSUE TITLE
[Bug]: Puppeteer Page Proxy Error: useProxyPer[target.constructor.name] is not a function

### ISSUE THREAD

**Issue by ahmedrtx-2** [puppeteer/puppeteer#12064]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const puppeteerPageProxy = require('puppeteer-page-proxy');
(async () => {
    var proxy = "ip:port:username:password".split(":");
    const browser = await puppeteer.launch({
        executablePath:"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
        headless:false,
    });
    const page1 = await browser.newPage();
    await puppeteerPageProxy(page1, `http://${proxy[0]}:${proxy[1]}`);
    await page1.goto('https://www.google.com/search?q=what+is+my+ip+address');
    await browser.close();
})();
```

### Error string

useProxyPer[target.constructor.name] is not a function

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

i want Custom IP per page

### Reality

When I run my code, the browser actually opens and shows me a white page titled about:blank for a few seconds and then this error appears
d:\Projects\Web\App\my-cli-app\node_modules\puppeteer-page-proxy\src\core\proxy.js:92
     useProxyPer[target.constructor.name](target, data);
                                         ^

TypeError: useProxyPer[target.constructor.name] is not a function
     at useProxy (d:\Projects\Web\App\my-cli-app\node_modules\puppeteer-page-proxy\src\core\proxy.js:92:41)
     at d:\Projects\Web\App\my-cli-app\index.js:41:11
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Puppeteer version

21.11.0

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Windows

**Comment by io-store** [comment]
@LeM0-Dev Please help me!

**Comment by OrKoN** [comment]
Please file an issue for the `puppeteer-page-proxy` package. `puppeteer-page-proxy` is not maintained by the puppeteer team and the error occurs with it.
