### ISSUE TITLE
Docker (Running as root without --no-sandbox is not supported)

### ISSUE THREAD

**Issue by RayburnTrading** [puppeteer/puppeteer#12069]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch([{
    executablePath: '/usr/bin/google-chrome-stable',
    args: [ '--disable-gpu', '--disable-setuid-sandbox', '--no-sandbox', '--no-zygote'],
  }]);
```

### Error string

[71:71:0310/171518.544718:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

My Dockerfile is:

```
FROM node:16

# Create app directory
WORKDIR /home/administrator/app
RUN mkdir /wso
RUN mkdir /scrubs
RUN mkdir /download
RUN mkdir /fonts

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN apt-get update && apt-get install gnupg wget -y && \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
  apt-get update && \
  apt-get install google-chrome-stable -y --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
COPY /src/ .
VOLUME "/home/administrator/app" "/home/administrator/app"

EXPOSE 5252
CMD npx nodemon -L server.js
#CMD [ "npm", "install" "npx","nodemon","-L","server.js" ]
```

### Expectation

I'd expect passing --no-sandbox to work

### Reality

[71:71:0310/171518.544718:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

### Puppeteer version

22.4.1

### Node version

16.20.2

### Package manager

npm

### Package manager version

10

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
@RayburnTrading Do you see the same issue if you use the official [Puppeteer Docker image](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer)? 
I can see that we do set a separate `user` for it - [Dockerfile](https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile).
