### ISSUE TITLE
I want use diffrent cookies value on same site and page

### ISSUE THREAD

**Issue by ahmedrtx-2** [puppeteer/puppeteer#12076]
### Minimal, reproducible example

i know that is not issue but...
I want an lib on puppeteer help me to do like that on pages cookies:
Page1 - {name:"cookie1",value:"abc1",domain:"example.com"}
Page2 - {name:"cookie1",value:"abc2",domain:"example.com"}

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

create same cookies name on same url and diffrent value per page

### Reality

none

### Puppeteer version

21.11.0

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
You can already do that by uses [browser.createBrowserContext](https://pptr.dev/api/puppeteer.browser.createbrowsercontext). As the documentation states cookies will not be shared across different context.
```ts
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
// Create a new browser contexts.
const contextA = await browser.createBrowserContext();
const contextB = await browser.createBrowserContext();
// Create a new page in a pristine context.
const pageA = await contextA.newPage();
const pageB = await contextB.newPage();
// Do stuff
await pageA.setCookie(cookieA);
await pageB.setCookie(cookieB);
```
