### ISSUE TITLE
[Bug]: Puppeteer Zooms In When Amcharts or Page Overflows

### ISSUE THREAD

**Issue by Satelliting** [puppeteer/puppeteer#12070]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  // Launch a headless browser
  const browser = await puppeteer.launch();

  // Open a new page
  const page = await browser.newPage();

  // Navigate to a webpage
  await page.goto('https://example.com');

  // Set the dimensions of the viewport to capture the entire page
  await page.setViewport({
    width: 1920,
    height: 1080,
    deviceScaleFactor: 1,
  });

  // Generate PDF from the page
  await page.pdf({
    path: 'example.pdf', // path to save the PDF file
    format: 'A4', // paper format
    printBackground: true, // include background colors and images
  });

  // Close the browser
  await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

When using and not using viewport setting, it seems the screen overflow-x is causing the report to either zoom in more if it fits nicely within the PDF. I need to know how to prevent this. Does puppeteer dynamic zoom? When I set all zoom properties to 1 manually, it still produces the same behavior.

I will caveat this with I am using Webpack and Nunjucks for the HTML files.

### Expectation

The page to stay the same.

### Reality

The page zooms into different sizes. depending on if the page overflows to outside the screen. For example amcharts set to 100% width break the page.

### Puppeteer version

18.0.0

### Node version

13.14.0

### Package manager

npm

### Package manager version

latest

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
@Satelliting Puppeteer use the the same PDF printing mechanism as Chrome, can you verify if you are experiencing this on normal headful Chrome when using `Print... (Ctrl+P)`?
