### ISSUE TITLE
[Bug]: The position of an element is not correct(using BoundingBox() API)

### ISSUE THREAD

**Issue by minggeorgelei** [puppeteer/puppeteer#12071]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date');
  const frames = page.frames();
  for (let i = 0; i < frames.length; i++) {
    const childFrames = frames[i].childFrames();
    for (let j = 0; j < childFrames.length; j++) {
      const frame = childFrames[j];
      const dateElement = await frame.$('#start');
      if (dateElement) {
        const boundingBox = await dateElement.boundingBox();
        console.log('boundingBox', boundingBox);
      }
    }
  }
  await browser.close();
})();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

The aim of the task is to draw a rectangle for this element, so we need to use bounding box to position the element. 

### Reality

Actually, the rectangle for this element is not accurate, we cannot get the right position of this element using BoundingBox API.

### Puppeteer version

21.0.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Windows

**Comment by minggeorgelei** [comment]
After test, in the headless mode, the position is correct, but under non-headless mode, the position is not correct.

**Comment by OrKoN** [comment]
@minggeorgelei it would help if you could provide the correct and incorrect positions you are getting? Could you also try using the latest version?

**Comment by OrKoN** [comment]
```
import puppeteer from 'puppeteer';

async function test(headless) {
  console.log('headless', headless)
  const browser = await puppeteer.launch({headless});
  const page = await browser.newPage();
  await page.goto('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date');
  const frames = page.frames();
  for (let i = 0; i < frames.length; i++) {
    const childFrames = frames[i].childFrames();
    for (let j = 0; j < childFrames.length; j++) {
      const frame = childFrames[j];
      const dateElement = await frame.$('#start');
      if (dateElement) {
        const boundingBox = await dateElement.boundingBox();
        console.log('boundingBox', boundingBox);
        await page.screenshot({
          path: `result${headless}.png`,
        })
      }
    }
  }
  await browser.close();

};

await test(true);
await test(false);
await test('shell')
```

I did a test and I do see slightly different positions across the modes but it looks like it mostly depends on whether:

1) the mode/OS has the scrollbar
2) if the ads are rendered or not

![resultfalse](https://github.com/puppeteer/puppeteer/assets/399150/add5fa01-3d6d-45a3-8c54-1a9c0637fd40)
![resultshell](https://github.com/puppeteer/puppeteer/assets/399150/343f3185-d9eb-438c-b09a-9b986d00c826)
![resulttrue](https://github.com/puppeteer/puppeteer/assets/399150/3f2785ec-99b6-474d-bcc2-cc438171adb7)

Note the the boundingBox returned is always related to the main frame.

**Comment by minggeorgelei** [comment]
Hi Alex, thanks for your replay 
In my computer, there is some difference.
I draw a rectangle around the element, I will post the two pics. The correct one is in headless mode. The incorrect one is in non-headless mode. The incorrect position shown in my computer is bounding box { x: 354, y: 1342.71875, width: 102.328125, height: 21.328125 }(returned by BoundingBoxAPI), and the correct one is bounding box { x: 315.65625, y: 993.734375, width: 108.328125, height: 21.328125 }(returned by BoundingBoxAPI). Please check the attached pics.
Thanks
![correctposition](https://github.com/puppeteer/puppeteer/assets/133333388/6884550e-93e8-4e46-820f-ba4d15f3b975)
![incorrectposition](https://github.com/puppeteer/puppeteer/assets/133333388/eeca3c5a-1463-457b-9b4c-1d025a5b1367)

**Comment by OrKoN** [comment]
You are using the latest Puppeteer version on Windows, right? Could you please confirm which Puppeteer version you have?

**Comment by minggeorgelei** [comment]
I now upgraded the version to 22.6.0 on Windows,  The accuracy of position has improved  a lot . 
If I used the non-fullpage mode to take the snapshot and draw the red rectangle, the position is accurate. If I used the fullpage mode, there's still some difference. Please see the attached pics.
![fullpage](https://github.com/puppeteer/puppeteer/assets/133333388/82360c34-1f0e-4742-b097-72189145e741)
![nonfullpage](https://github.com/puppeteer/puppeteer/assets/133333388/de2cc5a2-5da1-41a5-9b6d-91a9213b075f)

**Comment by OrKoN** [comment]
@minggeorgelei can you reproduce it on a minimal test page (instead of the full mdn website)? It has probably has something to do with the iframe and to take full page screenshot the browser might resize the viewport so perhaps this is what happens here. Also, could you try resizing the viewport upfront using `page.setViewport` so that the entire page fits?

**Comment by minggeorgelei** [comment]
I also tried other websites without using setViewPort at the beginning. Basically  the results are accurate, the rectangles are slightly left to the target elements. For the mdn website, perhaps it is related to the iframe?
![test1](https://github.com/puppeteer/puppeteer/assets/133333388/eaf0c7ac-2eb6-43ae-8f4f-a6d5500b0588)
![test2](https://github.com/puppeteer/puppeteer/assets/133333388/a6c93297-c3ce-4cc7-912f-4e0875ffcb17)

**Comment by OrKoN** [comment]
@minggeorgelei fundamentally, it is not guaranteed that the the position does not change between the last retrieved bounding box and when you take a screenshot (since it is separate operations, and as a whole they are not atomic). If the page is stable, it should generally work (but many pages are not, they might be loading ads, iframes, reactive to resize step). I am not sure if it is a bug with the mdn page in headless. Do you apply the box to the screenshot also taken in the same mode? the page might render differently in different modes since it is observable to the page (e.g., ads might not load in the headless mode).

**Comment by OrKoN** [comment]
```
import puppeteer from 'puppeteer';
import {createCanvas, loadImage} from 'canvas';
import {readFile, writeFile} from 'fs/promises';

async function test(headless) {
  console.log('headless', headless)
  const browser = await puppeteer.launch({headless, defaultViewport: {
    width: 1600,
    height: 1200
  }});
  const page = await browser.newPage();
  await page.goto('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date', {
    waitUntil: 'networkidle2'
  });
  const frames = page.frames();
  for (let i = 0; i < frames.length; i++) {
    const childFrames = frames[i].childFrames();
    for (let j = 0; j < childFrames.length; j++) {
      const frame = childFrames[j];
      const dateElement = await frame.$('#start');
      if (dateElement) {
        const boundingBox = await dateElement.boundingBox();
        console.log('boundingBox', boundingBox);
        await page.screenshot({
          path: `result${headless}.png`,
        });

        const data = await readFile(`result${headless}.png`);
        const image = await loadImage(data);

        const canvas = createCanvas(image.width, image.height)
        const ctx = canvas.getContext('2d');
        ctx.drawImage(image, 0, 0);
        ctx.strokeStyle = 'rgba(255,0,0)'
        ctx.beginPath()
        ctx.lineTo(boundingBox.x, boundingBox.y)
        ctx.lineTo(boundingBox.x + boundingBox.width, boundingBox.y)
        ctx.lineTo(boundingBox.x + boundingBox.width, boundingBox.y + boundingBox.height)
        ctx.lineTo(boundingBox.x, boundingBox.y + boundingBox.height)
        ctx.lineTo(boundingBox.x, boundingBox.y)
        ctx.stroke()
        await writeFile(`result${headless}.png`, canvas.toBuffer('image/png'))
      }
    }
  }
  await browser.close();

};

await test(true);
await test(false);
await test('shell');
```

with this script I get the same results: note networkidle2 and I drew the bounding box on the screenshot taken in the same mode.

**Comment by minggeorgelei** [comment]
Hi Alex,
I tried using your code. It works fine. I think for this case, it has something to do with the network state. After all this is not an atomic operation. There may have loading iframe and ads and some other disturbing factors.
This issue can be closed. Thanks for your replay.
