### ISSUE TITLE
[Bug]: (Firefox) Wheel event doesn't have ctrlKey set to true when Control key is down

### ISSUE THREAD

**Issue by calixteman** [puppeteer/puppeteer#12093]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    product: "firefox",
    headless: true,
    protocol: "webDriverBiDi",
  });

  const data = "data:text/html,<script>window.ctrlKey = false; window.addEventListener('wheel', e => { window.ctrlKey = e.ctrlKey; });</script>";
  const page = await browser.newPage();

  await page.goto(data);

  await page.keyboard.down("Control");
  await page.mouse.wheel({ deltaY: -100 });
  await page.keyboard.up("Control");

  const ctrlKey = await page.evaluate(() => window.ctrlKey);
  if (!ctrlKey) {
    throw new Error("Control key was not pressed");
  }

  await page.close();
  await browser.close();
})();
```

### Error string

Control key was not pressed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

ctrlKey property of the wheel event must be `true`.

### Reality

It's `false`.

### Puppeteer version

22.4.1

### Node version

18.19.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by whimboo** [comment]
Thank you for the issue. After investigation we can say that this is related to our implementation and should also fail in WebDriver classic. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1885542.

**Comment by lutien** [comment]
This issue should be fixed now in Nightly. Let us know if there are still any problems.

**Comment by OrKoN** [comment]
@whimboo @lutien adding a test for this in https://github.com/puppeteer/puppeteer/pull/12547

1) should it work for CDP?
2) it causes some new timeout errors in subsequent tests in firefox-bidi. Do you have any suggestions?
