### ISSUE TITLE
Merge InterceptedRequest with Request

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#121]
the `request.continue()` should accept options object with overrides for the request fields.

**Comment by aslushnikov** [comment]
Are the request object, dispatched via the `request` event, and the one passed over to the request interceptor, the same?

- If they are the same, at which point of time should calls `continue` or `abort` stop throwing and start doing meaningful things?
- If they are not the same, then there's no good reason to have a dummy `continue` and `abort` methods for every request.

Can we have `InterceptedRequest` class which has a `.request` field, pointing to the original request, and methods `continue` and `abort`? 
```js
page.setRequestInterceptor(interception => {
  interception.request.url; // interception.request holds the reference to the original request
  interception.continue({method: 'GET'}); // continues the request, overriding `method`
  interception.abort(); // aborts the request
});
```
@pavelfeldman wdyt?

**Comment by aslushnikov** [comment]
As discussed offline with @pavelfeldman:

```js
// enable request interception
await page.setInterceptRequests(true);

page.on('request', request => {
  // request has `continue` method which throws in case of disabled request interception.
  request.continue({method: 'GET'});
});
```

**Comment by aslushnikov** [comment]
Implementation notes:
- there's no `requestId` in the interception, so requests should be matched by payload
- there's no strict order between request interception and `requestWillBeSent` events, so the implementation would need to race and match them

This doesn't sound that great, so we're considering alternatives.

**Comment by JoelEinbinder** [comment]
Can you clarify the different events and what they mean? What are the states a request could be in?
 I asked before but I'm still confused on them.
