### ISSUE TITLE
framenavigated doesn't work in firefox

### ISSUE THREAD

**Issue by mortinlojen3030** [puppeteer/puppeteer#12117]
I just need to execute the script when the page is navigated. But in firefox framenavigated doesn't work, even evaluateOnNewDocument  doesn't work. What is the way to detect page navigation in firefox?

```
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({
    product: 'firefox',
    executablePath: "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
    headless: false
  });

  browser.on('targetcreated', async (target) => {
    if (target.type() === 'page') {
      const page = await target.page();

      page.evaluateOnNewDocument

      page.on('framenavigated', async () => {
        page.evaluate(() => { alert(123); });
      });
    }
  });
})();
```

**Comment by OrKoN** [comment]
Try using [WebDriver BiDi](https://pptr.dev/webdriver-bidi)

```
  const browser = await puppeteer.launch({
    product: 'firefox',
    headless: false,
    protocol: 'webDriverBiDi'
  });
```
  
That seems to work for me. Note that the CDP support in Firefox is limited and it will be superseded by WebDriver BiDi in the future. cc @whimboo

**Comment by whimboo** [comment]
Yes, we will not fix both for the experimental CDP implementation. Use WebDriver BiDi instead and instead of `evaluateOnNewDocument` you can use `script.addPreloadScript`.
