### ISSUE TITLE
Strategies for Reducing PDF File Size with Puppeteer

### ISSUE THREAD

**Issue by prashanttdwivedi** [puppeteer/puppeteer#12114]
Hello everyone,

In our organization, we're exploring alternatives to wkhtmltopdf, and Puppeteer seems to be the most promising option. However, we've encountered an issue: the PDFs generated by Puppeteer have a significantly larger file size compared to those generated by wkhtmltopdf. Despite attempting compression using Ghostscript, the file size remains 2-5 times larger.

We're reaching out to the community to gather insights on how others have addressed this challenge. Are there alternative methods for compressing PDF files effectively? Additionally, we're curious if Puppeteer offers any built-in features or utilities specifically for compressing PDFs.

Any guidance or experiences shared would be greatly appreciated.

Thank you!

**Comment by OrKoN** [comment]
Note that Puppeteer does not generate PDFs, the browser (Chrome or Firefox) that Puppeteer starts does that. It is imaginable that the smallest PDF is not the top priority for the browsers. There are few options to control PDF size (see https://pptr.dev/api/puppeteer.pdfoptions/): outline=false and tagged=false would result in a smaller pdf. For compressing PDFs, consider looking into solutions outside of Puppeteer.

**Comment by prashanttdwivedi** [comment]
Hi @OrKoN thank you so much for you quick response.

Can you please also help me confirming 1) is there a way to decrese DPI size in puppeteer pdfs? 2) in pdfoptions what does scale means is it related to page zoom in and out?

**Comment by OrKoN** [comment]
Looks like DPI setting exists in Chromium (not exposed to us) and it is set to 72 https://source.chromium.org/chromium/chromium/src/+/main:components/printing/browser/print_to_pdf/pdf_print_utils.cc;l=103;drc=a4c7bbe208f9caf621a85cc5e12aa6892d6a5e7a I think the browser built-in dialog uses 300 so printing via Puppeteer should result in smaller PDFs.

**Comment by stefanholzapfel** [comment]
One remark from my side: We experience way larger PDF filesizes when using Puppeteer > 21.5 (~ x5)

We did try the headless-shell binary and `headless: "shell" ` and also the new headless mode, makes not much of a difference. 

We tested the **same** browser version (129) with current Puppeteer (24) and old Puppeteer (21.5) so imho I think it must be related to Puppeteer. I'm aware that it just uses the print to pdf functionality of Chrome, but maybe different flags were used?

@prashanttdwivedi can you pls try Puppeteer 1.5 to confirm that observation? Thanks!

**Comment by julioxavierr** [comment]
@stefanholzapfel I'm facing the same problems with my app and have been stuck on Puppeteer v22 for a while now. Did you end up figuring out a solution?
