### ISSUE TITLE
[Bug]: `TypeError: Cannot convert undefined or null to object` with resolve argument of a Promise

### ISSUE THREAD

**Issue by calixteman** [puppeteer/puppeteer#12111]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

function createPromise(page, callback) {
  return page.evaluateHandle(
    // eslint-disable-next-line no-eval
    cb => [new Promise(eval(`(${cb})`))],
    callback.toString()
  );
}

function awaitPromise(promise) {
  return promise.evaluate(([p]) => p);
}

(async () => {
  const browser = await puppeteer.launch({
    product: "chrome",
    headless: true,
    protocol: "webDriverBiDi",
  });

  const page = await browser.newPage();
  await page.goto("https://mozilla.github.io/pdf.js/web/viewer.html");
  await page.bringToFront();

  const handle = await createPromise(page, resolve => {
    window.PDFViewerApplication.eventBus.on("textlayerrendered", resolve);
  });
  await awaitPromise(handle);

  await page.close();
  await browser.close();
})();
```

### Error string

ProtocolError: Protocol error (script.callFunction): unknown error Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

It works correctly if I replace `resolve` by `() => resolve()`.
It works correctly with Firefox (Bidi/CDP) and with Chrome (CDP).
I didn't manage to create a test case outside the pdf.js context.

### Expectation

No error.

### Reality

There's an error.

### Puppeteer version

22.6.0

### Node version

18.19.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by OrKoN** [comment]
Needs to be marked as fixed once chromium-bidi is updated.

**Comment by OrKoN** [comment]
Fixed via https://redirect.github.com/GoogleChromeLabs/chromium-bidi/issues/2039
