### ISSUE TITLE
[Bug]: Puppeteer script runs fine when run from command line, but when i trigger it from browser nothing happens

### ISSUE THREAD

**Issue by neelam-hanabaratti-minutus** [puppeteer/puppeteer#12116]
### Steps to reproduce

install and setup puppeteer.
capture SS using node js
trigger the node js program from php ajax file

### Expected results

When i trigger node js program from command line the ss is captured, but not from chrome browser. This is my test.js program
```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const sharp = require('sharp');

puppeteer.use(StealthPlugin());
const { executablePath } = require('puppeteer');

puppeteer.launch({ headless: true, args: ['--no-sandbox'] , executablePath: executablePath() }).then(async browser => {
    console.log('Running tests..');
    const page = await browser.newPage();

    // Retrieve HOST_NAME from command-line arguments
    const HOST_NAME = process.argv[2];

    // Check if HOST_NAME is provided
    if (!HOST_NAME) {
        console.error('HOST_NAME is not provided.');
        process.exit(1); // Exit the script with an error code
    }

    // Set a large viewport size
    await page.setViewport({ width: 1920, height: 1080 });

    await page.goto('https://zabbixip/zabbix/');
    await page.type('#name', 'Admin');
    await page.type('#password', 'zabb!x@Minutus');
    await page.click('[type=submit]');
    await page.waitForTimeout(2000);
    await page.click('.icon-monitoring');
    await page.waitForTimeout(2000);
    await page.evaluate(() => {
        const mapsLink = Array.from(document.querySelectorAll('a')).find(a => a.textContent.includes('Maps'));
        mapsLink.click();
    });
    await page.waitForTimeout(2000);

    // Use HOST_NAME within page.evaluate()
    await page.evaluate((HOST_NAME) => {
        const mapLink = Array.from(document.querySelectorAll('a')).find(a => a.textContent.includes(HOST_NAME));
        if (mapLink) { // Check if mapLink is found before clicking
            mapLink.click();
        } else {
            console.error('Map link not found.');
        }
    }, HOST_NAME);
    await page.waitForTimeout(2000)
    // Scroll to the bottom of the page
    await page.evaluate(() => {
        window.scrollTo(0, document.body.scrollHeight);
    });
    await page.waitForTimeout(2000);

    // Capture a full-page screenshot
    await page.screenshot({ path: '/tmp/testresult.png', fullPage: true });

    await browser.close();
    sharp('/tmp/testresult.png')
        .extract({ left: 200, top: 80, width: 1700, height: 800 })
        .toFile('/tmp/test-new.jpg', function (err) {
            if (err) console.log(err);
        })
    console.log(`All done, check the screenshot. ✨`);
});
```
and here is the ajax call
`<?php
include '/usr/share/zabbix/modules/AuditReport/views/config.php';

// Create a database connection
$conn = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Check if necessary parameters are set
//if (isset($_GET['groupid'])) {
    //$groupid = $_GET['groupid'];
    $groupid = 89;
    echo "Hello";
    $shellScript = "/var/www/html/puppeteer/sample.sh $groupid";
    exec($shellScript);
    // Perform the query to retrieve the group name
    $groupQuery = "SELECT name FROM hstgrp WHERE groupid = $groupid";
    $groupResult = $conn->query($groupQuery);
  //  set_time_limit(200);
    if ($groupResult->num_rows > 0) {
        //echo "Hello!!!";
        $groupRow = $groupResult->fetch_assoc();
        $groupName = $groupRow['name'];
        echo "Hello!!! " . get_current_user() . " + $groupName";
        // echo "Hello!!! + $groupName";
        // Call the node.js script passing the group name
        $nodeScript = "nohup node /var/www/html/puppeteer/test.js $groupName  > /tmp/output.log 2>&1 < /dev/null &";
        //$nodeScript = "node /var/www/html/puppeteer/test.js $groupName  > /tmp/output.log 2>&1 < /dev/null &";
        $output=shell_exec($nodeScript);
        echo $output;
        //sleep(20);
    } else {
        echo "Group not found";
        exit;
    }
//} else {
  //  echo "Missing parameters- from ajax";
//}

// Close the MySQL connection
$conn->close();
?>
`
when i directly run the js or php file it works perfectly. but when i run php file from browser, the SS is not getting stored. there is no output.log either

### Actual results

Not working when tried to run it from browser

**Comment by OrKoN** [comment]
It does not sound like an issue with Puppeteer and more like an issue with invoking node from php. Consider asking on StackOverflow instead.

P.S. also it is the wrong bug template
