### ISSUE TITLE
[Bug]: Puppeteer launch arg not working "--allow-running-insecure-content"

### ISSUE THREAD

**Issue by nickheyer** [puppeteer/puppeteer#12123]
### Minimal, reproducible example

```TypeScript
async function setupBrowser() {
  const DIR = path.join(os.tmpdir(), '<redacted>');
  let browser;
  try {
    browser = await puppeteer.launch({
      dumpio: false,
      product: 'chrome',
      defaultViewport: { width: 1680, height: 916 },
      ignoreHTTPSErrors: true,
      headless: !process.env.HEADED_MODE,
      slowMo: 5, // ms,
      args: [
        '--detectOpenHandles',
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-background-timer-throttling',
        '--disable-dev-shm-usage',
        '--disable-backgrounding-occluded-windows',
        '--disable-renderer-backgrounding',
        '--disable-gpu',
        '--disable-extensions',
        '--ignore-certificate-errors',
        '--allow-running-insecure-content'
      ],
      browserContext: 'default',
      exitOnPageError: false
    });

    await mkdir(DIR, { recursive: true });
    await writeFile(path.join(DIR, '<redacted>'), browser.wsEndpoint(), 'utf8');
  } catch (error) {
    console.error('Failed to launch the browser: ', error);
  }
}
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Opening pop up auth window and interacting with it. 

Can manually change chromium site settings in popup to allow insecure content, but can' t do so programmatically with launch args. 

### Expectation

To change chromium site settings programmatically with launch args. 

### Reality

Can't change chromium site settings programmatically with launch args. 

### Puppeteer version

19.7.5

### Node version

18.18.0

### Package manager

npm

### Package manager version

10.5.0

### Operating system

macOS

**Comment by OrKoN** [comment]
`--allow-running-insecure-content` works fine for me. Note that we do not explicitly support that flag if there are issues with it please file an issue for Chromium at crbug.com.
