### ISSUE TITLE
[Bug]: Refused to set unsafe header

### ISSUE THREAD

**Issue by ahmedrtx-2** [puppeteer/puppeteer#12124]
### Minimal, reproducible example

Inside the evaluate function, when I requested the XMLHttpRequest and set the Cookie header, this error appeared
Refused to set unsafe header "Cookie"
Is there any argument or option that can help me solve this error?

### Error string

Refused to set unsafe header "Cookie"

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

set header cookie without any error

### Reality

shows: Refused to set unsafe header "Cookie"

### Puppeteer version

21.11.0

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Windows

**Comment by OrKoN** [comment]
See https://stackoverflow.com/a/50256898/601499

**Comment by io-store** [comment]
> See https://stackoverflow.com/a/50256898/601499

I want to deactivate this type of protection in the browser. Is there no option in puppeteer to do that? I read what you sent, but it did not help me with anything. I tried xhr.withCredentials and no change occurred.

**Comment by OrKoN** [comment]
@io-store that is not an option. You need to set the cookie using `document.cookie` not as a header.
