### ISSUE TITLE
how can I accept (alert or dialog) or ignore?

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1213]
When I browse through several links on the website, they show me warnings that I want to ignore or accept, is it possible?.

I would like to first check if exists dialog... and then ignore or accept, because it does not let me continue browsing

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#class-dialog and https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#event-dialog

**Comment by fran0254** [comment]
How can I check if exists a dialog or not? And if there exists await await dialog.dismiss ();

**Comment by ghost** [comment]
Same with @fran0254

**Comment by Congee** [comment]
@fran0254 @chanjsq 
A global flag comes to rescue
```
let dialogExists = false;

page.on('dialog', () => {
  dialogExits = true;
});
// and set it to false in page.off()
```

A terrible workaround though. :/

**Comment by johnwaweru** [comment]
```
    * if there's a dialog and you always want to accept */
    page.on('dialog', async dialog => {
      await dialog.accept();
    });
```

**Comment by johnwaweru** [comment]
if there's a dialog and you always want to accept
```
page.on('dialog', async dialog => {
    await dialog.accept();
});
```
