### ISSUE TITLE
[Bug]: No command (timeout) cleanup when when a page closes

### ISSUE THREAD

**Issue by Lightning00Blade** [puppeteer/puppeteer#12132]
### Minimal, reproducible example

```TypeScript
// Running tests with something like `wtfnode` attached
// Easiest test to reporduce is  `AriaQueryHandler` `$$eval should handle many elements` test
```

### Error string

None

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

In CDP if we create close the page we also close the `session` associated with it. 
In BiDi this is not the case as we have a single session, so we should either keep a WeekMap or have a mechanism to clear them. 

### Expectation

After a page is closed, all command timeouts that were created for the page are cleared.

### Reality

The timeouts are still present and the process can't exit. 

### Puppeteer version

22.6.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
> In BiDi this is not the case as we have a single session, so we should either keep a WeekMap or have a mechanism to clear them.

should also something happen on the chromium-bidi side if a running bidi command is affected? P.S. not sure I got how to repro from the description, perhaps, let's add details next week.
