### ISSUE TITLE
VERCEL NEXT JS: Failed to launch the browser process!

### ISSUE THREAD

**Issue by official-grabbers** [puppeteer/puppeteer#12145]
The application works correctly on my local but not on vercel.

ISSUE FACED HERE:

Failed to launch the browser process!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

**Comment by OrKoN** [comment]
Install missing system dependencies as the link suggests https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux
