### ISSUE TITLE
Improve documentation site

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12140]
- [ ] Create a landing page in for the website (currently we copy the repo's main README)
- [ ] Create separate README's for `puppeteer` and `puppeteer-core` (`puppeteer-core` examples don't work)
- [ ] Have a separate README for the mono repo
- [ ] Improve the structure to be as following:

## Getting started

- [ ] What is Puppeteer?
- [ ] Installation (cover install and configuration)
- [ ] System requirements (mention Node/TS version by Puppeteer and hardware requirements by browsers)
- [ ] First script

## Core concepts

- [ ] Browser Management
- [ ] Page Interaction
- [ ] JavaScript Execution
- [ ] Network Control

## Advanced Topics

- [ ] Debugging
- [ ] Interception
- [ ] Headless mode
- [ ] Screenshots and PDFs
- [ ] Cookies
- [ ] File uploads and downloads

## Community

- [ ] Contributing
- [ ] Troubleshooting
- [ ] Links

**Comment by OrKoN** [comment]
cc @Lightning00Blade @matthiasrohmer

**Comment by prajjwal-mathur** [comment]
Hello Alex, 
May I work on this? Also, I am not sure about how the first part is supposed to be done:

> move documentation out of the repo's README to /docs Readme should link to the website instead.
