### ISSUE TITLE
[Bug]: /node_modules/puppeteer-core/lib/cjs/puppeteer/util/disposable.js | Symbol.dispose ??= Symbol('dispose');  | SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by Aswin2255** [puppeteer/puppeteer#12160]
### Minimal, reproducible example

```TypeScript
"puppeteer": "^22.2.0",
```

### Error string

 SyntaxError: Unexpected token '??='

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I encountered an issue when attempting to start my project on an AWS server after installing the Puppeteer package. Despite changing the Node.js version and performing a clean installation by deleting the node_modules directory and reinstalling dependencies, the problem persists. The error message is related to a syntax error originating from the Puppeteer package.

### Expectation

i expected the code to run irrespective of all node version 

### Reality

I encountered an issue when attempting to start my project on an AWS server after installing the Puppeteer package. Despite changing the Node.js version and performing a clean installation by deleting the node_modules directory and reinstalling dependencies, the problem persists. The error message is related to a syntax error originating from the Puppeteer package.

### Puppeteer version

22.6.1

### Node version

18.17.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
> i expected the code to run irrespective of all node version

This statement is not correct `Puppeteer follows the latest [maintenance LTS](https://github.com/nodejs/Release#release-schedule) version of Node.` from [Usage](https://pptr.dev/#usage).
Currently the minimum supported version is 18 which supports that syntax.
Please contact AWS support as they may be using different binaries for their runners. 

Tested with:
```ts
import { launch } from "puppeteer";

(async () => {
  const browser = await launch({
    headless: true,
  });

  const page = await browser.newPage();

  await page.close();
  await browser.close();
})();
```
Result, script runs without issue.
![image](https://github.com/puppeteer/puppeteer/assets/34244704/a5891251-fef8-4091-8054-adbbc293d6d3)

**Comment by wwLoveWj** [comment]
me too,
![998](https://github.com/user-attachments/assets/54199106-e3ed-4af3-b24c-219f3ebe3208)
### version:
 "puppeteer": "^23.10.2",

**Comment by wwLoveWj** [comment]
> 我也是， ![998](https://private-user-images.githubusercontent.com/88973224/394093954-54199106-e3ed-4af3-b24c-219f3ebe3208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDEzNDAsIm5iZiI6MTczMzgwMTA0MCwicGF0aCI6Ii84ODk3MzIyNC8zOTQwOTM5NTQtNTQxOTkxMDYtZTNlZC00YWYzLWIyNGMtMjE5ZjNlYmUzMjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDAzMjQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyOWQ2OTVjZmY0MzEyNGMwYjM2MjY1Yjk3NWUzZTEzNTI2NGI0ODcwODQ0YmJmMTNiNjA1Njc3YzA1MGM0NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORis_q0pZdll1PDAX0c4gsra9nhUEqA_OWp435kWVhw)
> 
> ### 版本：
> “木偶师”：“^23.10.2”，

I think the experience is too bad，I hope it can be resolved as soon as possible，and I wonder why！My English expression is quite poor. If it's a bit impolite, I'm sorry.Because I very like it，and I really want to experience its functions.
