### ISSUE TITLE
Inquiry: ARM Compatibility for Puppeteer

### ISSUE THREAD

**Issue by prashanttdwivedi** [puppeteer/puppeteer#12161]
Hello team,

I hope this message finds you well. I'm reaching out to inquire about the compatibility of Puppeteer with ARM architecture.

I've scoured through the documentation but couldn't find any explicit mention regarding ARM compatibility. To verify this, I conducted some tests by running Puppeteer within an ARM environment, specifically in a Docker container with Ubuntu as the base image. Surprisingly, Puppeteer worked seamlessly in this setup.

However, before proceeding further, I wanted to confirm with the team if Puppeteer is officially supported on ARM architecture. It's crucial for our project's infrastructure planning and compatibility assurance.

Could someone please provide clarity on this matter? Any official documentation or insights regarding Puppeteer's compatibility with ARM architecture would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by OrKoN** [comment]
macos arm64 is fully supported. As for linux arm64, Chrome does not officially support this platform so there are no arm64 binaries for linux https://github.com/puppeteer/puppeteer/issues/7740 It should be still possible to use third-party arm64 chromium builds or use some sort of emulation to be able to run x64 on arm64.
