### ISSUE TITLE
[Bug]: using exposeFunction on a page with an iframe pointing to a pdf causes hang

### ISSUE THREAD

**Issue by eoghanmurray** [puppeteer/puppeteer#12172]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; // TS/ESM are all supported.

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('about:blank');

  // assuming a valid PDF
  await page.setContent('<html><body><iframe src="some-doc.pdf"></iframe></body></html>')

  await page.exposeFunction('test', () => { console.log('test'); });
  // !!! don't get to here
  await browser.close();
})();
```

### Error string

no error (hangs)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This is in a suite of tests and causes the tests to hang
https://github.com/eoghanmurray/rrweb/commit/845bf5cb57caf19b32e15f0f74ce71cbc0d0ce9d#diff-f822a25730eb990747d0f997cbcbf61789e7924c84988c09f3666935d5d6a577R624

### Expectation

not to try to inject the 'test' function into the iframe document, as it isn't a regular javascript environment.

additionally, I expected it not to hang when failing to do so, but to have some sort of timeout to indicate that the injection failed to complete

### Reality

tests hang

### Puppeteer version

22.6.1

### Node version

27.7.1

### Package manager

yarn

### Package manager version

1.2.3

### Operating system

Linux

**Comment by eoghanmurray** [comment]
22.6.2 not released at https://classic.yarnpkg.com/en/package/puppeteer yet

**Comment by OrKoN** [comment]
Not able to reproduce on Mac with:

```
import puppeteer from 'puppeteer'; // TS/ESM are all supported.

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('about:blank');

  await page.setContent('<html><body><iframe src="https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"></iframe></body></html>')
  await page.exposeFunction('test', () => { console.log('test'); });
  // !!! don't get to here
  await browser.close();
})();
```

**Comment by OrKoN** [comment]
Also, not with using a file URL to a local file. Perhaps the issue is specific to Linux.

**Comment by OrKoN** [comment]
Able to repro with a PDF served from a local http server.

**Comment by OrKoN** [comment]
The workaround for now could be to filter out all iframe targets with url about:blank:

```
    targetFilter: t => {
        return !(t.url() === 'about:blank' && t.type() === 'iframe')
    }
```

**Comment by hashimoto-AJ** [comment]
```
$ npm install puppeteer@22.6.2

npm ERR! code ETARGET
npm ERR! notarget No matching version found for puppeteer@22.6.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

22.6.2 not released at https://www.npmjs.com/search?q=puppeteer yet.

**Comment by OrKoN** [comment]
Very likely related to https://github.com/puppeteer/puppeteer/issues/10696
