### ISSUE TITLE
[Bug]: PDF - Currency symbol not displaying(displaying as a small box) while taking print out from Ubuntu server

### ISSUE THREAD

**Issue by kalidas3** [puppeteer/puppeteer#12173]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
export const pdfGeneration = async () => {
  const priceFormat = (value) => {
    let rupee = new Intl.NumberFormat('en-IN', {
        style: "currency",
        currency: 'INR',
    });
    return rupee.format(value);
  }
  // Create a browser instance
  // const browser = await puppeteer.launch({ headless: 'new' });
  const browser = await puppeteer.launch({
    headless: 'new',
    // executablePath: 'google-chrome',
    args: [
      '--accept-lang=en-GB',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
    ],
  });
  // Create a new page
  const page = await browser.newPage();
  await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36")
  const html = `<div>
  <div>Grant Total</div>
  <div>${priceFormat(10)}</div>
</div>`;
  await page.setContent(html, { waitUntil: 'networkidle0' });

  // To reflect CSS used for screens instead of print
  await page.emulateMediaType('screen');
  // await page.emulateMedia('screen');
  // Downlaod the PDF
  const pdf = await page.pdf({
    // path: 'result6.pdf',
    margin: { top: '50px', right: '50px', bottom: '70px', left: '50px' },
    printBackground: true,
    format: 'A4',
    // displayHeaderFooter: true,
    displayHeaderFooter: true,
  });

  // Close the browser instance
  await browser.close();
  return pdf;
};
```

### Error string

Displaying as a box. No Error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I am trying to display currency in the PDF but it is not displaying. I am using Ubuntu server
![image](https://github.com/puppeteer/puppeteer/assets/41969877/b61c1a76-b488-4a04-aac9-2963cf8e89f9)

### Expectation

I expected to display currency symbol in the pdf like below screenshot.
![image](https://github.com/puppeteer/puppeteer/assets/41969877/56c45f08-9c6b-400c-8d94-a8461b3b9cdb)

### Reality

Currency symbol displaying in windows but it is not displaying Ubuntu server

### Puppeteer version

22.6.1

### Node version

18.18.2

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Linux

**Comment by kalidas3** [comment]
I have upgraded to latest version 22.6.1 but no luck

**Comment by OrKoN** [comment]
@kalidas3 is it only in PDFs or also in screenshots? Do you have fonts installed to render the character?

**Comment by kalidas3** [comment]
@OrKoN In browser currency symbol is showing fine. Only PDF it is not showing and I didn't install any fonts in Ubuntu server. The same thing is working fine in windows without any specific fonts installed. Did I miss anything here? Or tell me how can I fix this. Is it required to install specific fonts in Ubuntu server?

**Comment by OrKoN** [comment]
> In browser currency symbol is showing fine.

How do you verify it on the server environment? Doe this help https://stackoverflow.com/questions/56924652/rial-symbol-cant-be-printed-to-pdf-with-puppeteer ?

**Comment by OrKoN** [comment]
It is not reproducible on a Mac too so it probably some missing fonts on the Ubuntu server. Try setting a font-family that is known to be installed on the system, for example, 

```
  const html = `<div>
  <div>Grant Total</div>
  <div style="font-family: Arial, Ubuntu;">${priceFormat(10)}</div>
</div>`;
```

Also, it might be useful to include `<meta charset="UTF-8">` in the html page to make sure it is interpreted as utf-8.
