### ISSUE TITLE
[Feature]: ability to check and possibly installed missing system dependencies

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12188]
### Feature description

For linux, the following packages are required https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/debian/dist_package_versions.json

**Comment by Lightning00Blade** [comment]
Closed by - https://github.com/puppeteer/puppeteer/pull/12580
If any other platform is listed in chromium with packages and you need support please file an new issue issue.
