### ISSUE TITLE
how to play audio in puppeteer join google meet  in a way it can be audible to everyone

### ISSUE THREAD

**Issue by Sandeep-Zedblock** [puppeteer/puppeteer#12184]
i have join the google meet using puppeteer on a server

now i want to play a audio using mic of puppeteer browser

const browser = await launch(puppeteer, {
headless: true,
args: [
"--no-sandbox",
"--disable-setuid-sandbox",
"--use-fake-device-for-media-stream",
],

userDataDir,
});

i tried play audio in the page using page.evaluate it's playing audio but it's only audible in that tab not to other member of google meet

so how to play audio i a way it can be audible to everyone in google meet

**Comment by OrKoN** [comment]
Puppeteer does not offer this feature. Consider asking on StackOverflow how to solve it through other means.
