### ISSUE TITLE
[Bug]: MaxListenersExceededWarning caused by process.on('exit')

### ISSUE THREAD

**Issue by 1known-x** [puppeteer/puppeteer#12187]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer"

const browsers = []
for (let i = 0; i < 10; i++) {
	const browser = await puppeteer.launch()
	browsers.push(browser)
}

console.log('All running...')
```

### Error string

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I want to run multiple browsers concurrently, with a different configuration for each one.

### Expectation

To let me run multiple browsers concurrently.

### Reality

I get `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

After some research, I found out it's because each browser is adding an `on exit` event listener to the main process, and max listeners is set to 10 by default. `@puppeteer/browsers/lib/esm/launch.js:104`

I'm not sure if it's a bug, or there is a workaround to merge all listeners to avoid the warning and possible memory leaks.

This could be a solution, altought it's not very clean:
```js
import puppeteer from "puppeteer"

const browsers = []
const listeners = []
for (let i = 0; i < 10; i++) {
	const browser = await puppeteer.launch()
	browsers.push(browser)

	const lastListener = process.listeners('exit').at(-1)
	process.off('exit', lastListener)
	listeners.push(lastListener)
}

process.on('exit', () => {
	listeners.forEach(listener => listener())
})

console.log('All running...')
```

Another way could be adding the opt to avoid handling of process `on exit` event (just like handleSIGINT, for example), and handle it manually:
```js
import puppeteer from "puppeteer"

const browsers = []
for (let i = 0; i < 10; i++) {
	const browser = await puppeteer.launch({ handleExit: false })
	browsers.push(browser)
}

process.on('exit', () => {
	browsers.forEach(browser => browser.kill())
})

console.log('All running...')
```

### Puppeteer version

22.6.2

### Node version

20.12.0

### Package manager

pnpm

### Package manager version

8.15.5

### Operating system

Linux

**Comment by OrKoN** [comment]
Also, you can use process.setMaxListeners to set the number of instances you expect to launch. I don’t think it’s a bug, Puppeteer needs those listeners per launched process.

**Comment by 1known-x** [comment]
> Also, you can use process.setMaxListeners to set the number of instances you expect to launch. I don’t think it’s a bug, Puppeteer needs those listeners per launched process.

First of all, there must be a reason why the warning is set to 10 by default. Disabling it isn't my cup of tea.

The listeners are not from the launched processes, but from the main proccess where node is running. Each browser is creating an event listener on the main process to kill himself on exit. But too many browsers means too many listeners, and that's why the warning is being triggered.

The solution is merging all browsers to the same event listener that kills them all, and not creating a new event listener for each one.

**Comment by OrKoN** [comment]
> First of all, there must be a reason why the warning is set to 10 by default.

I actually don’t know why 10 is okay but more than 10 warrants a warning. I would be curious to learn.

It sounds like it’d be better to work around the warning on Puppeteer side.
