### ISSUE TITLE
When Javascript is disabled, injecting JS file with addScriptTag failed, where previously injectFile did not

### ISSUE THREAD

**Issue by nazieb** [puppeteer/puppeteer#1219]
### Steps to reproduce

* Puppeteer version: 0.12.0
* Platform / OS version: macOS El Capitan

**What steps will reproduce the problem?**

My use case is I'd like to do some extraction from a local HTML file using jQuery and some third party libraries.

When I used v0.11.0, before calling the `setContent`, I call `setJavaScriptEnabled` so it won't load unnecessary scripts. Then I inject jQuery and others using `injectFile`.

```javascript
            await page.setJavaScriptEnabled(false);
            await page.setContent(html);

            const jqueryPath = require.resolve("jquery");
            await page.injectFile(jqueryPath);

            const result = await page.evaluate(() => {
                $("#some-selector").remove();
                // etc etc etc
            });
```

But since the `injectFile` is removed in 0.12.0, I changed it to use `addScriptTag` instead, so my code looks like this:

```javascript
            await page.setJavaScriptEnabled(false);
            await page.setContent(html);

            const jqueryPath = require.resolve("jquery");
            await page.addScriptTag({path: jqueryPath});

            const result = await page.evaluate(() => {
                $("#some-selector").remove();
                // etc etc etc
            });
```

**What is the expected result?**

My expectation is the result from `evaluate` is the same with previous version using v0.11.0 since the rest of the code is unchanged.

**What happens instead?**

Instead, I got:

```
Error: Evaluation failed: ReferenceError: $ is not defined
```

After some digging I think the problem is because `addScriptTag` is adding the script via [new `<script>` tag](https://github.com/GoogleChrome/puppeteer/pull/996/files#diff-16f3b9739b97830927de83812ac92d78R319) while the `injectFile` is by [evaluating the scripts right away](https://github.com/GoogleChrome/puppeteer/pull/996/files#diff-16f3b9739b97830927de83812ac92d78L317).

Now that I've disabled the javascript on the page, those "injected" scripts are never executed. I've tried removing the line which disabled the Javascript, and my script worked successfully, but after the Chrome requested a lot of remote Javascript files.

My current workaround is I use the old `injectFile` mechanism where I load the JS file and then evaluate the content.

So my proposal is what if those mechanism is also applied on `addScriptTag` with path or content option? So the migration from `injectFile` is more consistent.

**Comment by aslushnikov** [comment]
@nazieb your investigation is totally right, sorry for the inconvenience.

The old `injectFile` is polyfillable with a one-liner:

```js
await page.evaluate(fs.readFileSync('file-to-inject.js', 'utf8'));
```

I'd keep "addScriptTag" as-is so that it does what you'd expect it to - adds a script tag. To workaround your case, I'd use the one-liner.

**Comment by nazieb** [comment]
@aslushnikov it's okay, and hey, that's one liner is awesome. Thanks a lot.

**Comment by voordev** [comment]
Could someone please tell me How would you pass an array or object _defined in my nodejs app
from_ your node code with this?

I need several const available inside this file-to-inject.js file
for example an array.

```
await page.evaluate(fs.readFileSync('file-to-inject.js', 'utf8'));  
```

**Comment by gumuruhsspj** [comment]
> @nazieb your investigation is totally right, sorry for the inconvenience.
> 
> The old `injectFile` is polyfillable with a one-liner:
> 
> ```js
> await page.evaluate(fs.readFileSync('file-to-inject.js', 'utf8'));
> ```
> 
> I'd keep "addScriptTag" as-is so that it does what you'd expect it to - adds a script tag. To workaround your case, I'd use the one-liner.

and the file is located under the same directory... am i right?
