### ISSUE TITLE
[Bug]: insecure download warning when downloading from pdf generator 

### ISSUE THREAD

**Issue by yehudaclinton** [puppeteer/puppeteer#12197]
### Minimal, reproducible example

```TypeScript
In ruby/rails app i get that warning prompt when trying to download pdf in chrome. I know my tls is fine because i dont get this error when using Prawn.
```

### Error string

user warning prompt

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

to download without any errors prompting

### Reality

warning prompting me to accept the download

### Puppeteer version

20.9.0

### Node version

v20.5.1

### Package manager

npm

### Package manager version

9.8.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Could you please add a reproducible example and describe why do you think it is an issue in Puppeteer?

**Comment by yehudaclinton** [comment]
> Could you please add a reproducible example and describe why do you think it is an issue in Puppeteer?

      grover = Grover.new(html, format: Params.paper_size)
      pdf = grover.to_pdf
      return send_data pdf, filename: 'download.pdf', type: 'application/pdf'

**Comment by OrKoN** [comment]
Please report your issue to https://github.com/Studiosity/grover or provide a reproducible example using JavaScript, thanks!

**Comment by yehudaclinton** [comment]
> Please report your issue to https://github.com/Studiosity/grover or provide a reproducible example using JavaScript, thanks!

you are right thats where i should have reported it, but are you also experiencing these new chrome download warnings everywhere recently? i do no like it.
