### ISSUE TITLE
calling addScriptTag returns Promise that is not rejected in case of an error

### ISSUE THREAD

**Issue by marijanlekic** [puppeteer/puppeteer#1221]
### Steps to reproduce

Puppeteer version: 0.12.0
Platform / OS version: macOS El Capitan

**What steps will reproduce the problem?**

If loading external script fails (wrong url, internet is down ...), if you call:

await page.addScriptTag({url: "someurl"});

nothing will happen and execution of a code will be stuck on this line.

**What is the expected result?**

Promise should be rejected because of an error.

**What happens instead?**

Promise is not rejected because in FrameManager.js "onerror" callback is not registered.

**Comment by aslushnikov** [comment]
That's a good one. Should be easy to fix; the code in question is here

https://github.com/GoogleChrome/puppeteer/blob/6dec7cf6e4c5121570c22fc1db89678690d367f7/lib/FrameManager.js#L347-L353

**Comment by robertlyall** [comment]
Simply adding `script.onerror = reject;` works, however it produces a rather cryptic error message:

> Evaluation failed: Event

As far as I'm aware, there isn't a way for me to access an error object from the event itself.

Perhaps I've tried to implement a fix that is _too_ easy, did you have another solution in mind, @aslushnikov? I'd like to have a go at fixing this.

It's also worth mentioning that `addStyleUrl` will also need the same treatment, as the functionality is _almost_ identical.

**Comment by aslushnikov** [comment]
> As far as I'm aware, there isn't a way for me to access an error object from the event itself.

@robertlyall onerror callback gets an error object passed in: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror)

> Simply adding script.onerror = reject; works, however it produces a rather cryptic error message:

You can reject with your own error if you wish to.

> It's also worth mentioning that addStyleUrl will also need the same treatment, as the functionality is almost identical.

Indeed, good call

**Comment by robertlyall** [comment]
Unfortunately, the arguments differ between `element.onerror` and `window.onerror`.

> When a resource (such as an <img> or <script>) fails to load, an error event using interface `Event` is fired at the element, that initiated the load, and the `onerror()` handler on the element is invoked.

In that case, I'll reject both `addScriptUrl` and `addStyleUrl` with my own error.
