### ISSUE TITLE
[Bug]: build failure after deps update 

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12214]
### Steps to reproduce

Have dependabot bump dependencies and try to build the project

### Expected results

Error: src/builders/puppeteer/index.ts(205,1): error TS2742: The inferred type of 'default' cannot be named without a reference to '@angular-devkit/architect/node_modules/@angular-devkit/core'. This is likely not portable. A type annotation is necessary.

### Actual results

No errors

### @puppeteer/ng-schematics version

xxx

### Angular CLI version

xxx

**Comment by OrKoN** [comment]
See https://github.com/puppeteer/puppeteer/actions/runs/8566714098/job/23477022116?pr=12211

**Comment by Lightning00Blade** [comment]
I think we should close this issue as it's a it's not a problem from our implementation. The problem is that `dependabot` does not update all the `Angular` dependencies at once - though I have no clue why. We should just disable the whole `ng-schematics` and update them manually when needed.
