### ISSUE TITLE
[Bug]: Request Interceptor weird behaviour

### ISSUE THREAD

**Issue by kazanemed** [puppeteer/puppeteer#12227]
### Minimal, reproducible example

```TypeScript
            await page.setRequestInterception(true);


            await page.on(PageEmittedEvents.Request, (req) => {
              req.continue();
            }
            );
            const response = await Promise.race([
              page?.goto(url, { waitUntil: ['networkidle0'] }),
              page.waitForTimeout(TIMEOUT_MS_SCREENSHOT).then(() => {
                res.status(500).json({ message: TIMEOUT_ERROR_MESSAGE });
              })
            ]);

            response.request().redirectChain().forEach((redirect) => {
              console.log(redirect.url())
            })
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm tracking redirect chain for urls that has redirects, and I faced a weird bug that came from the request interceptor. 
 

### Expectation

This website: https://bit.ly/PFCxFHVMar23
Get 2 redirects and reach the final destination successfully. 

### Reality

I'm getting infinity of redirects to same url ( when I print req.url() in interceptor ) , in fact , I couldn't even print the response since it didn't reach it ! the main cause is the request interceptor behavior under the hood. When I removed the code block of interceptor everything works fine. This bug is happens with this specific website: https://bit.ly/PFCxFHVMar23

### Puppeteer version

21.10.0

### Node version

18.17.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

macOS

**Comment by OrKoN** [comment]
It is possible that the site detects automation and prevents it by redirecting. Can you reproduce it with a custom server sending same sort of redirects?

**Comment by kazanemed** [comment]
> It is possible that the site detects automation and prevents it by redirecting. Can you reproduce it with a custom server sending same sort of redirects?

Thanks for your reply. Could you please tell me wether you got the same results as mine? Also, could you please clarify for me what you mean by reproducing it with custom server and how is this related to this bug?

**Comment by OrKoN** [comment]
Nope, I am not able to reproduce this. A custom server (e.g., using https://nodejs.org/api/http.html#httpcreateserveroptions-requestlistener) could help to reproduce the issue by replicating and isolating the behavior you are seeing in case it is a Puppeteer issue. But in this case it looks like sometimes the server does infinite redirects. In this case, you can count the redirects in the request handler and abort the request if you encounter too many.
