### ISSUE TITLE
Docs: clarify page.keyboard.type vs page.type with examples and explainer text

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1223]
I was reading API docs. Look at this method for example:
[https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#keyboardtypetext-options](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#keyboardtypetext-options)

It says that I should use:
```page.keyboard.type('Hello');```

But In fact that's not working and I should use:
```page.type('Hello');```

Should be docs fixed?

**Comment by ebidel** [comment]
@JoelEinbinder what do you think about adding info around the differences between `page.type`, `page.keyboard.type`, `handler.type`, etc? The docs are fuzzy on when to use each.

**Comment by trevordmiller** [comment]
It seems `page.type('text')` no longer works, moving from `0.10.2` to `0.13.0` and that I should now use `page.keyboard('text')`? I'm `page.click(selector)`-ing before each type, so I don't need to pass a selector which `page.type` now requires? I'm confused and agree clearer documentation would be helpful. Thanks.

**Comment by trevordmiller** [comment]
Switching from `page.type('text')` to `page.type(selector, 'text')` works well.

# Before (0.10.2)

```javascript
    await page.goto(routes.public.register)
    await page.waitForSelector('[data-testId="userRegisterInputWithEmail"]')
    await page.click('[data-testId="userRegisterInputWithEmail"]')
    await page.type(user.email)
    await page.click('[data-testId="userRegisterInputWithPassword"]')
    await page.type(user.password)
    await page.click('[data-testId="userAccountSubmitButton"]')
    await page.waitForSelector('[data-testId="userSettingsForm"]')
```

# After (0.13.0+)

```javascript
    await page.goto(routes.public.register)
    await page.waitForSelector('[data-testId="userRegisterInputWithEmail"]')
    await page.type('[data-testId="userRegisterInputWithEmail"]', user.email)
    await page.type(
      '[data-testId="userRegisterInputWithPassword"]',
      user.password
    )
    await page.click('[data-testId="userAccountSubmitButton"]')
    await page.waitForSelector('[data-testId="userSettingsForm"]')
 ```

**Comment by JoelEinbinder** [comment]
`page.type` went through a lot of variations. The current, stable variants are:

`page.type(selector, text)` : focuses the selector and then types the text
`page.keyboard.type(text)`: types the text into whatever currently has focus
`elementHandle.type(text)`: Focuses the element, and then types the text.

If you find any documentation that is out of date, let me know! Thanks

**Comment by techsin** [comment]
@JoelEinbinder nice
