### ISSUE TITLE
[Feature]: Inserting a Audio and video Stream

### ISSUE THREAD

**Issue by parteekcoder** [puppeteer/puppeteer#12232]
### Feature description

if I open up a website using puppeteer in headless mode. I am not able to inject audio , video streams into that.

**Comment by OrKoN** [comment]
Could you please provide more details? Do you mean uploading files? If you mean some sort to fake the audio and video input coming from the operating system, then this is not supported and it is out of scope for Puppeteer.

**Comment by parteekcoder** [comment]
Hi @OrKoN 

Can we add a stream to enable bi-directional communication using Puppeteer ? We want to be able to enable conversations in a meeting, where conversations are driven by a bot.
