### ISSUE TITLE
[Bug]: Unable to bundle puppeteer script with wepack

### ISSUE THREAD

**Issue by NabinOjha** [puppeteer/puppeteer#12231]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer') // this is the code in puppeteer script 


//webpack config
const path = require("path")

module.exports = {
  mode: 'none',
  target: 'node',
  entry:  path.resolve(__dirname, "lib/javascript/puppeteer.js"), // Replace 'your_script.js' with the name of your script file
  output: {
    filename: 'puppeteer_bundle.js',
    path: path.resolve(__dirname, 'public/diagnostics/packs/js')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
    ],
  },
  resolve: {
    extensions: ['.js'],
  },
};

NODE VERSION 18.19.1
PUPPETEER VERSION 22.6.3
```

### Error string

ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js Module not found: Error: Can't resolve 'puppeteer-core/internal/node/PuppeteerNode.js' in '/home/nabin/Desktop/work/mindgym-diagnostics/node_modules/puppeteer/lib/cjs/puppeteer'  @ ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js 32:27-83  @ ./lib/javascript/puppeteer.js  ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js Module not found: Error: Can't resolve 'puppeteer-core/internal/puppeteer-core.js' in '/home/nabin/Desktop/work/mindgym-diagnostics/node_modules/puppeteer/lib/cjs/puppeteer'  @ ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js 31:13-65  @ ./lib/javascript/puppeteer.js  ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/getConfiguration.js 50:62 Module parse failed: Unexpected token (50:62) File was processed with these loaders:  * ./node_modules/babel-loader/lib/index.js You may need an additional loader to handle the result of these loaders. |   }).search(); |   const configuration = result ? result.config : {}; >   configuration.logLevel = process.env['PUPPETEER_LOGLEVEL'] ?? process.env['npm_config_LOGLEVEL'] ?? process.env['npm_package_config_LOGLEVEL'] ?? configuration.logLevel ?? 'warn'; |   // Merging environment variables. |   configuration.defaultProduct = process.env['PUPPETEER_PRODUCT'] ?? process.env['npm_config_puppeteer_product'] ?? process.env['npm_package_config_puppeteer_product'] ?? configuration.defaultProduct ?? 'chrome';  @ ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js 33:30-62  @ ./lib/javascript/puppeteer.js

### Bug behavior

- [X] Flaky
- [X] PDF

### Background

I have been trying to build the script before deployment

### Expectation

The script should have been built along with its dependencise

### Reality

ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
Module not found: Error: Can't resolve 'puppeteer-core/internal/node/PuppeteerNode.js' in '/home/nabin/Desktop/work/mindgym-diagnostics/node_modules/puppeteer/lib/cjs/puppeteer'
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js 32:27-83
 @ ./lib/javascript/puppeteer.js

ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
Module not found: Error: Can't resolve 'puppeteer-core/internal/puppeteer-core.js' in '/home/nabin/Desktop/work/mindgym-diagnostics/node_modules/puppeteer/lib/cjs/puppeteer'
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js 31:13-65
 @ ./lib/javascript/puppeteer.js

ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/getConfiguration.js 50:62
Module parse failed: Unexpected token (50:62)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }).search();
|   const configuration = result ? result.config : {};
>   configuration.logLevel = process.env['PUPPETEER_LOGLEVEL'] ?? process.env['npm_config_LOGLEVEL'] ?? process.env['npm_package_config_LOGLEVEL'] ?? configuration.logLevel ?? 'warn';
|   // Merging environment variables.
|   configuration.defaultProduct = process.env['PUPPETEER_PRODUCT'] ?? process.env['npm_config_puppeteer_product'] ?? process.env['npm_package_config_puppeteer_product'] ?? configuration.defaultProduct ?? 'chrome';
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js 33:30-62
 @ ./lib/javascript/puppeteer.js

Getting this errror

### Puppeteer version

22.6.3

### Node version

18.19.1

### Package manager

yarn

### Package manager version

1.22.21

### Operating system

Linux

**Comment by OrKoN** [comment]
See a working example from our tests https://github.com/puppeteer/puppeteer/blob/main/test/installation/assets/puppeteer/webpack/webpack.config.js (tests https://github.com/puppeteer/puppeteer/blob/main/test/installation/src/puppeteer-webpack.spec.ts) 

The `puppeteer-core/internal` error indicates that the module module resolution is not working well in your setup. Generally, issues with third party software should not be reported here. Consider asking on StackOverflow or raising an issue with Webpack.
