### ISSUE TITLE
[Bug]: Stuck at puppeteer.connect()

### ISSUE THREAD

**Issue by lyndonjasa** [puppeteer/puppeteer#12243]
### Minimal, reproducible example

```TypeScript
browser = await puppeteer.connect({
     browserURL: chromeEndpoint
});
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We had just upgraded our node version from 14 to 20, as well as our packages which includes puppeteer (now at 20.6.0 then 22.6.3). It doesn't get resolved when it gets to puppeteer.connect(). I reckon the remote Chromium version might have to do something with it which is currently at 86.0.4240.75.

### Expectation

I was at least expecting an error, but there's none. Just a promise not getting resolved.

### Reality

Code kept getting stuck and cannot proceed

### Puppeteer version

22.6.3

### Node version

20.12.1

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Chromium 86.0.4240.75 is not compatible 22.6.3 See https://pptr.dev/next/supported-browsers for the version compatibility. Since M86 there were changes in how CDP behaves and new versions of Puppeteer expect the new behavior.
