### ISSUE TITLE
Module not found error using webpack.

### ISSUE THREAD

**Issue by chris-herring** [puppeteer/puppeteer#1224]
Puppeteer is working great in development but I'm trying to use webpack to build the release and hitting the following modules not found:
Module not found: Error: Can't resolve 'bufferutil'
Module not found: Error: Can't resolve 'utf-8-validate'
Module not found: Error: Can't resolve 'vertx'

I can reproduce this in a new project with the following files:
package.json

    {
      "name": "puppeteertest",
      "version": "1.0.0",
      "main": "index.js",
      "license": "MIT",
      "dependencies": {
          "puppeteer": "^0.12.0"
      }
    }

index.js
`import puppeteer from 'puppeteer';`

webpack.config.js

    const path = require('path');

    module.exports = () => {
    	const clientBundleOutputDir = './wwwroot/dist';
    
	    return {
            entry: { 'index': './index.js'  },
            resolve: { extensions: [ '.js' ] },
            output: {
                libraryTarget: 'commonjs2',
    			path: path.join(__dirname, clientBundleOutputDir),
    			filename: 'index.js',
    			publicPath: '/dist/'
    		},
    		target: 'node'
    	};
    };

Running webpack then results in:

	WARNING in ./~/ws/lib/Validation.js
	Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Development\Test Projects\puppeteer\node_modules\ws\lib'
	@ ./~/ws/lib/Validation.js 10:22-47
	@ ./~/ws/lib/Receiver.js
	@ ./~/ws/index.js
	@ ./~/puppeteer/lib/Connection.js
	@ ./~/puppeteer/lib/Launcher.js
	@ ./~/puppeteer/lib/Puppeteer.js
	@ ./~/puppeteer ^\.\/.*\/Puppeteer$
	@ ./~/puppeteer/index.js
	@ ./index.js

	WARNING in ./~/ws/lib/BufferUtil.js
	Module not found: Error: Can't resolve 'bufferutil' in 'C:\Development\Test Projects\puppeteer\node_modules\ws\lib'
	@ ./~/ws/lib/BufferUtil.js 35:21-42
	@ ./~/ws/lib/Receiver.js
	@ ./~/ws/index.js
	@ ./~/puppeteer/lib/Connection.js
	@ ./~/puppeteer/lib/Launcher.js
	@ ./~/puppeteer/lib/Puppeteer.js
	@ ./~/puppeteer ^\.\/.*\/Puppeteer$
	@ ./~/puppeteer/index.js
	@ ./index.js

	WARNING in ./~/es6-promise/dist/es6-promise.js
	Module not found: Error: Can't resolve 'vertx' in 'C:\Development\Test Projects\puppeteer\node_modules\es6-promise\dist'
	@ ./~/es6-promise/dist/es6-promise.js 138:16-26
	@ ./~/es6-promisify/dist/promise.js
	@ ./~/es6-promisify/dist/promisify.js
	@ ./~/agent-base/index.js
	@ ./~/https-proxy-agent/index.js
	@ ./~/puppeteer/utils/ChromiumDownloader.js
	@ ./~/puppeteer/lib/Launcher.js
	@ ./~/puppeteer/lib/Puppeteer.js
	@ ./~/puppeteer ^\.\/.*\/Puppeteer$
	@ ./~/puppeteer/index.js
	@ ./index.js

I'm using puppeteer 0.12.0, node 8.3.0. 

Any ideas how to get pass this?

**Comment by ebidel** [comment]
Weird. These warnings/errors are coming from deps of puppeteer. I'm not familiar enough with webpack to know if it's your setup or something else. Any webpack experts out there?

**Comment by DaveRicho** [comment]
Hi @chris-herring, 
Did you end up solving that issue? (or finding a work around?) .
Thanks,
Dave.

**Comment by NicolasRannou** [comment]
Experiencing same behavior - any advice?

FYI seems related to the fact that pupeteer relies on "node" packages that are not web browser friendly (which makes sense) - webpack is trying to pack those packages somehow.

No webpack expert either...

**Comment by DaveRicho** [comment]
Hi @NicolasRannou,

I’m still waiting for this to break something, but so far, we have just added this to our webpack.config.js to remove the warnings (as I said, I am worried it may break something, but so far it seems fine - they are just warnings is what I keep telling myself......):

```
const {  IgnorePlugin } = require('webpack');

// this is in the “plugins” array part of our webpack object  
    // next 3 lines added to remove warnings....might be a problem    
    new IgnorePlugin(/vertx/),
    new IgnorePlugin(/bufferutil/),    
    new IgnorePlugin(/utf-8-validate/),
```


Hope this helps,

Dave.

**Comment by aslushnikov** [comment]
@chris-herring If @DaveRicho's [comment](https://github.com/GoogleChrome/puppeteer/issues/1224#issuecomment-351498586) doesn't fix the issue, I'd suggest asking over in the webpack repo: there should be more people familiar with the matter.

**Comment by XBeg9** [comment]
@aslushnikov did you find a solution? Just got same here :( Thanks

**Comment by joelgriffith** [comment]
Curious as to why folks are bundling with webpack since it primarily is a bundled for browsers. You’re likely to run into more issues with other deps like `ws` that potentially use C-bindings.

**Comment by XBeg9** [comment]
@joelgriffith my serverless service is already bundling with webpack, so I just need one more lambda function inside my service and it doesn't work.

**Comment by DaveRicho** [comment]
@joelgriffith controlling browser with angular/electron app
