### ISSUE TITLE
Unhandled rejection at _onClose

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1225]
This rejection is unhandled:
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Connection.js#L113

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Browser.close): Target closed.`

Or possible this line:
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Connection.js#L208

**Comment by aslushnikov** [comment]
The lines you pointed to are rejecting pending callbacks from the protocol - this is intentional. 
What's the usecase when you have this rejection message? Can you share your script so that we can repro it?

**Comment by schelkun** [comment]
Try to press Ctrl+C while script is waiting 5 sec and you will get unhandled promise rejection.
@aslushnikov 

```js
const puppeteer = require('puppeteer');
const process = require('process');

(async() => {

    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    process.on('SIGINT', async () => {
        await browser.close();
    });

    await page.goto('https://github.com/GoogleChrome/puppeteer');

    try {
        await (new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve();
            }, 5000);
        }));

        console.log('Done!');

        await browser.close();
    } catch (e) {
        console.log('Err', e);
    }
})();
```

**Comment by schelkun** [comment]
@aslushnikov so? :smile:

**Comment by aslushnikov** [comment]
@schelkun if you listen to SIGINT by yourself, you should ask puppeteer to not handle SIGINT. Otherwise, you try to call `browser.close()` twice in a row.

The following worked just fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {

    const browser = await puppeteer.launch({
      handleSIGINT: false
    });
    const page = await browser.newPage();

    process.on('SIGINT', async () => {
        await browser.close();
        console.log('exiting!');
        process.exit(0);
    });

    await page.goto('https://github.com/GoogleChrome/puppeteer');

    try {
      console.log('waiting...');
        await (new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve();
            }, 5000);
        }));

        console.log('Done!');

        await browser.close();
    } catch (e) {
        console.log('Err', e);
    }
})();
```

Hope this helps
