### ISSUE TITLE
[Bug]: Failed to launch the browser process!\nchrome_crashpad_handler: --database is required

### ISSUE THREAD

**Issue by puvan-360softy** [puppeteer/puppeteer#12258]
### Minimal, reproducible example

```TypeScript
nothing
```

### Error string

Failed to launch the browser process!\nchrome_crashpad_handler: --database is required

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

The command \"PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/var/www/xxxxx.com/vendor/spatie/browsershot/src/../bin/browser.cjs' '{\"url\":\"file:\/\/\/tmp\/825023843-0281286001712858894\/index.html\",\"action\":\"pdf\",\"options\":{\"args\":[],\"viewport\":{\"width\":800,\"height\":600},\"displayHeaderFooter\":false,\"margin\":{\"top\":\"10mm\",\"right\":\"10mm\",\"bottom\":\"10mm\",\"left\":\"10mm\"},\"format\":\"a4\",\"printBackground\":true}}'\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /var/www/xxxxx.com/public\n\nOutput:\n================\n\n\nError Output:\n================\nError: Failed to launch the browser process!\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n[118780:118780:0411/180815.391629:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n\n    at Interface.onClose (/var/www/xxxxx.com/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)\n    at Interface.emit (node:events:529:35)\n    at Interface.close (node:internal/readline/interface:534:10)\n    at Socket.onend (node:internal/readline/interface:260:10)\n    at Socket.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n

### Reality

This is working in my local machine. and server i installed all the packages. but getting above error

### Puppeteer version

22.6.4

### Node version

v18.20.1

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
See https://pptr.dev/troubleshooting tips and dependencies required on Linux https://pptr.dev/guides/system-requirements Without a reproducible example (e.g., via Docker), we cannot reproduce the issue.
