### ISSUE TITLE
[Feature]: Accessing WebRTC peerConnection in puppeteer

### ISSUE THREAD

**Issue by parteekcoder** [puppeteer/puppeteer#12271]
### Feature description

Hi , I have launched an headless browser using puppeteer to join an online meeting . How can I access webRTC connection object

**Comment by OrKoN** [comment]
If you use script evaluation to create https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection or access the object that the web app creates if the apps exposes it in some way. We currently do not plan any extra WebRTC specific features.
