### ISSUE TITLE
Force pushing to default branch

### ISSUE THREAD

**Issue by setpill** [puppeteer/puppeteer#12275]
Our mirror of this repo recently broke, as a commit on the `main` default branch was overwritten with another.

Specifically, [PR 12261](https://github.com/puppeteer/puppeteer/pull/12261) was merged as commit [4f659b0](https://github.com/puppeteer/puppeteer/commit/4f659b0acf0282600300f70ead645aa7d724b41f), but later overwritten with an (unverified) commit [ff4f70f](https://github.com/puppeteer/puppeteer/commit/ff4f70f4ae7ca8deb0becbec2e49b35322dba336).

I would just like to double check that this is legitimate.

**Comment by Lightning00Blade** [comment]
@setpill Yes this was intentional and legitimate. 
Previously our commit did not contain a description, and the change was that added a description.
Thanks for the issue and sorry for the inconvenience.
