### ISSUE TITLE
[Bug]: ERROR in DIGITALOCEAN APPLICATION PLATFORM

### ISSUE THREAD

**Issue by ruzlicali-dev** [puppeteer/puppeteer#12281]
### Minimal, reproducible example

```TypeScript
let newUrl;
    const url = req.query.url as string;
    const schema = Joi.object({
      url: Joi.string().required(),
    });
    const { error } = schema.validate({ url });
    if (error) {
      return res.status(400).json({ message: error.message });
    }
    try {
      newUrl = `${SERVICE_ACCOUNT}${url}`;
      /* Launch a headless browser */
      const browser = await launch({ headless: true, executablePath: process.env.CHROME_BINARY });
      const page = await browser.newPage();

      /* Navigate to the URL passed from the frontend */
      await page.goto(newUrl, { waitUntil: "networkidle0" });

      await page.evaluate(() => {
        document.title = "DAILY OCCURRENCE BOOK";
      });

      // Generate PDF
      const pdfBuffer = await page.pdf({
        format: "A3",
        landscape: true,
        printBackground: true, // Enable printing of background colors and images
      });

      /* Close the browser */
      await browser.close();

      /* Set response headers for PDF */
      const today = new Date();
      today.setHours(today.getHours() + 8);
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `'attachment; filename="DOB-DOWNLOADED-${formatDateString(today)}.pdf"'`);

      /* Send the PDF as response */
      res.send(pdfBuffer);
    } catch (error: any) {
      res.status(500).send({ error: "Error generating PDF", message: error.message, url: newUrl });
    }
```

### Error string

"Could not find Chrome (ver. 123.0.6312.105). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or\n 2. your cache path is incorrectly configured (which is: /workspace/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration."

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

Hello.

Puppeter is not working in PRODUCTION (Digitalocean Application Platform) But working in Local.

This error occured: "Could not find Chrome (ver. 123.0.6312.105). This can occur if either\n 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or\n 2. your cache path is incorrectly configured (which is: /workspace/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration."

### Expectation

It should work in PRODUCTION

### Reality

Error Occured

### Puppeteer configuration file (if used)

```TypeScript
None
```

### Puppeteer version

22.6.3

### Node version

v18.18.0

### Package manager

yarn

### Package manager version

1.22.22

### Operating system

Windows

**Comment by OrKoN** [comment]
Please follow the instructions from the error message and try installing Chrome on the server after you deploy. To double check it has been downloaded check the cache path at /workspace/.cache/puppeteer as the error message indicates.
