### ISSUE TITLE
[Bug]: Background is pink when using background: repeating-linear-gradient

### ISSUE THREAD

**Issue by muster-mark** [puppeteer/puppeteer#12288]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

async function main() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent('<div>I\'m a Barbie div in a Barbie world.</div><style>div {height: 200px; width: 200px; background: repeating-linear-gradient(-45deg, #111, #111 10px, #222 10px, #222 20px) }</style>');
    await page.pdf({
        path: 'output.pdf',
        printBackground: true,
    });

    await browser.close();
}

main();
```

### Error string

nO eRrOR

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I want to have a stripy background, so tried to use the css property intended for this.

### Expectation

I expected to get a stripy background.

### Reality

I got a pink background.

### Puppeteer version

22.6.5

### Node version

18.20.2

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
@muster-mark could you please provide a PDF that you get?

**Comment by OrKoN** [comment]
Do you get a different result if you print using the regular print dialog in Chrome and choose save to PDF?

**Comment by Lightning00Blade** [comment]
This looks like an issue with the viewer that's being used
From my VSCode extension I get the described problem (Also I get a `File is corrupted` error):
![image](https://github.com/puppeteer/puppeteer/assets/34244704/2ef3c755-691b-4dd9-bab9-d5e846b11c80)
But opening the same file in Chrome give the correct color:
![image](https://github.com/puppeteer/puppeteer/assets/34244704/c987ed5b-7f7f-4422-8f46-02d5adcf06f8)

**Comment by muster-mark** [comment]
@OrKoN @Lightning00Blade 
Please see attached printed_from_puppeteer.pdf and printed_from_chrome.pdf

[printed_from_chrome.pdf](https://github.com/puppeteer/puppeteer/files/15011626/printed_from_chrome.pdf)
[printed_from_puppeteer.pdf](https://github.com/puppeteer/puppeteer/files/15011627/printed_from_puppeteer.pdf)

Lighting00Blade, you are correct that it does depend on the viewer. I was using Firefox to view the pdfs. It displays correctly in Chrome, as you note, and also Adobe Acrobat reader. Though OrKoN, yes I do get a different result when printing from chrome, as that pdf displays correctly in Firefox.

I am not sure we can we be sure the viewers are to blame here, since the issue is apparent in 2 separate viewers (Firefox and vscode). Perhaps the pdf itself is in fact the issue, but chrome and adobe acrobat are more tolerant of whatever that issue is.

**Comment by OrKoN** [comment]
So if it is shown correctly in Chrome and Adobe Acrobat reader, I believe this is an issue with the specific PDF viewer.

**Comment by muster-mark** [comment]
@OrKoN FWIW Safari also seems to have an issue with the puppeteer file. Although it displays it correctly, it takes an astonishing 35 seconds to render the table, whereas the pdf created by printing in chrome renders almost immediately.

**Comment by muster-mark** [comment]
@OrKoN Also, Apple Preview renders the chrome generated version instantantaneously, but takes about 5s for the puppeteer one.

**Comment by OrKoN** [comment]
@muster-mark Puppeteer's one are also generated by Chrome as Puppeteer does not generate PDFs on its own. Have you tried `tagged: false` in Puppeteer? Perhaps it is worth filing a bug at crbug.com ?

**Comment by muster-mark** [comment]
@OrKoN tagged: false produces the same output. But actually in Firefox it does look like this known issue: https://github.com/mozilla/pdf.js/issues/5046
