### ISSUE TITLE
page.SetContent could accept a URL to set page.url

### ISSUE THREAD

**Issue by rafagsiqueira** [puppeteer/puppeteer#1228]
Could this be possible?

`var expectedContent = '<html><body><div>Test div</div></body></html>';`
`var expectedLocation = 'http://www.teste.org/';`
`page.setContent(expectedContent, {url: expectedLocation});`

page.url() would then be equal to expectedLocation.

**Comment by ebidel** [comment]
Couldn't you just do:

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();

const expectedLocation = 'http://www.teste.org/';
await page.goto(expectedLocation);

const expectedContent = '<html><body><div>Test div</div></body></html>';
await page.setContent(expectedContent);

console.log(await page.url() === expectedLocation);

await browser.close();
```

**Comment by aslushnikov** [comment]
@rafagsiqueira Eric's workaround would work. You can even speed it up with request interception's `respond` method (available in v0.13.0-alpha, current tip-of-tree):

```js
await page.setRequestInterception(true);
page.once('request', req => {
  req.respond({
    body: '<html><body><div>Test div</div></body></html>'
  });
});
await page.goto('http://www.teste.org/');
```

**Comment by rafagsiqueira** [comment]
But if I do page.goto(expectedLocation) wouldn't I be loading the whole content of this page?
The request interception solution is more efficient I believe. Thank you for both solutions!

Still, I think it makes sense, if you can set the page content you should be able to set the url of that page.

**Comment by ruz** [comment]
I would love to see this request reopened. HTML you set as content may have external links, so full code would look something like the following:

```
        await page.setRequestInterception(true);
        page.on('request', (request) => {
          if ( request.url() === data.base_url || request.url() === data.base_url + '/') {
            request.respond({
              body: data.content
            });
          } else {
            request.continue();
          }
          return;
        });
        await page.goto(data.base_url);

```

**Comment by nikolayemrikh** [comment]
+1 to reopen this issue

**Comment by tcamde** [comment]
@ruz 
Just for anybody else trying this.
I had to set the content type in the request.respond to actually make it render my html:

```
request.respond({
          contentType: 'text/html',
          body: yourHtmlString
        })
```

**Comment by cubesnyc** [comment]
+1 to reopen this.

**Comment by paulcarpenter** [comment]
Old ticket I know, but this would be handy for us as well!
