### ISSUE TITLE
[Bug]: Opening the extension popup.html using will return new empty popup without any data how to get popup.html within the context of a specific tab/website

### ISSUE THREAD

**Issue by kala15** [puppeteer/puppeteer#12286]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const browser = await puppeteer.launch({
        // launch the browser in the headful mode
        headless: false,
        // add the extension to the browser
        args: [
        `--disable-extensions-except=${pathToExtension}`,
        `--load-extension=${pathToExtension}`,
        ],
    });
    await sleep(2000)
    // open a new browser tab
    let page = await browser.newPage();

  await page.goto('https://www.example.com/');
  await page.bringToFront();
  await page.goto(`chrome-extension://${extenstionID}/html/popup.html`)
```

### Error string

will open new seprate page which is new empty page 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

is there any work around to get the resultant produced by specific chrome extenstion on specific tab/website. resultant can be in form of popup in from of html should we any changes in manifest v3 file to get the data that should also be fine.
just need the resultant produced by extenstion on specific tab programticaly

### Expectation

await page.goto(`chrome-extension://${extenstionID}/html/popup.html`) page should be within the context of a specific tab/website

### Reality

popoup.html file used is not in  the context of a specific tab/website

### Puppeteer version

22.6.5

### Node version

v18.18.1

### Package manager

yarn

### Package manager version

1.22.21

### Operating system

Linux

**Comment by OrKoN** [comment]
Here is an example of how to open an extension popup using Puppeteer https://github.com/oliverdunk/puppeteer-extension-experiments/blob/main/src/index.ts#L13

**Comment by kala15** [comment]
great the above code opens the pop up as expected.thanks
