### ISSUE TITLE
[Bug]: Could not able to get the selectors when headless: true, but it is working with headless:false

### ISSUE THREAD

**Issue by mahaveer-bh** [puppeteer/puppeteer#12289]
### Steps to reproduce

Getting the error at     
await page
      .waitForSelector(
        config.oktaUserNameSelector,
        config.waitForSelectorTimeOut
      )
      .catch(catchHandler);
where  config.oktaUserNameSelector = "#input28"

### Expected results

 Wait for username selector
 Wait for password selector
Page is ready just before alert

### Actual results

 Wait for Email selector
TimeoutError: Waiting for selector `#input28` failed: Waiting failed: 40000ms exceeded
Wait for username selector

**Comment by OrKoN** [comment]
Please file the bug using the Puppeteer (not @puppeteer/browsers) template and provide a minimal executable example.
