### ISSUE TITLE
[Bug]: when accessing browser.targets() I don't get info about _targetInfo which have property like _targetInfo.title , _targetInfo.type...

### ISSUE THREAD

**Issue by kala15** [puppeteer/puppeteer#12283]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
(async()=>{
       const browser = await puppeteer.launch({
        headless: false,
        devtools: true,
        args: [
            `--disable-extensions-except=${path_to_extension}`,
            `--load-extension=${path_to_extension}`,
            `--headless=false`
            ]
    })
    const targets = await browser.targets();
    const extensionTarget = targets.find( ({ _targetInfo }) => {
        return _targetInfo.title === extensionName && _targetInfo.type === 'background_page';
    });
})()
```

### Error string

return _targetInfo.type === 'background_page';                    TypeError: Cannot read properties of undefined (reading 'type')        ^  TypeError: Cannot read properties of undefined (reading 'type')

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I need to get extenstionID of the extenstion from browser so I can test the extenstion

### Reality

_targetInfo is equal to no type and name info
Target {
  _targetId: 'ABCD',
  _isPageTargetCallback: [Function (anonymous)],
  _initializedCallback: [Function (anonymous)],
  _initializedPromise: Promise { true },
  _closedCallback: [Function (anonymous)],
  _isClosedPromise: Promise { <pending> },
  _isInitialized: true
}

### Puppeteer version

22.6.5

### Node version

18

### Package manager

yarn

### Package manager version

1.22.21

### Operating system

Linux

**Comment by OrKoN** [comment]
Use methods on the target class https://pptr.dev/api/puppeteer.target like `target.type()`:

```
     const extensionTarget = targets.find( (target) => {
        return target.url() === extensionUrl && target.type() === 'background_page';
    });
```

Any properties that start with _ are internal properties and are not part of the documented API so they can stop working at any time.

P.S. Also node 14 and node 16 are not supported by Puppeteer anymore.
