### ISSUE TITLE
[Bug]: Freezing when querying frames on certain websites

### ISSUE THREAD

**Issue by Vasile-Peste** [puppeteer/puppeteer#12292]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

async function main () {
    console.log("Operative");

    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('http://fonologomed.it/');

    const allIframeLinks = [];
    const frames = page?.frames() ?? [];

    for (const frame of frames) {
        try {
            if (!frame?.url() || frame.detached) {
                continue;
            }

            const links = await frame.$$eval('a', (anchors) => anchors.map((anchor) => ({
            href: anchor.href,
                text: anchor.text,
    	    })));

            allIframeLinks.push(...links);
        }
        catch (e) {
            console.log(e);
        }
    }

    console.log(allIframeLinks);
    console.log("Success");
}

main();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We want to retrieve the <a> links from the iframes within a website. This works for the majority of visited websites, but we noticed on certain websites this operation completely is freezing (the Promise is pending forever).
Running the reproducible example on http://fonologomed.it/ will freeze
For a contrarian example, running the reproducible example on https://www.aranzulla.it will NOT freeze

### Expectation

The promise to resolve or at least get an error

### Reality

The operation gets stuck as the Promise never gets resolved

### Puppeteer version

22.6.5

### Node version

20.3.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

macOS

**Comment by Vasile-Peste** [comment]
I guess it cannot be reproduced by the workflow because it gets stuck?

**Comment by AntonioFavero** [comment]
The promise frame.$$eval is never resolved.

**Comment by OrKoN** [comment]
I think it is another example of https://github.com/puppeteer/puppeteer/issues/10696 basically the browser built-in PDF viewer creates empty iframes which never gets an execution context created for them as regular iframe. So the eval calls wait for the context as expected from the Chrome DevTools Protocol, but never gets them for those frames. Maybe it is because it is treated as part of the browser UI although the technical implementation is an iframe.

**Comment by OrKoN** [comment]
A workaround could be like

```
      let parent = frame.parentFrame();
      let skip = false;
      while (parent) {
        if (parent.url().endsWith('.pdf')) {
          skip = true;
          break;
        }
        parent = parent.parentFrame();
      }
      if (!frame?.url() || frame.detached || skip) {
        continue;
      }
```

or more general since it is reasonable to not expect any context on about:blank pages

```
      if (!frame?.url() || frame.detached || frame.url('about:blank')) {
        continue;
      }
```

**Comment by Vasile-Peste** [comment]
Hi @OrKoN,
thank you for the answer

We thought it might be a PDF issue in fact we tried filtering by PDF extension as you proposed in the first workaround. Although we didn't traverse the parent frames so this is why probably our solution didn't work. We will try your first workaround

The second workaround is problematic. In fact in our solution we want to read frames with "about:blank". From our tests it results that calling `frame.url()` on iframes without a src set, returns "about:blank". We have several cases of frames without a src set, they are automatically generated by plugins and widgets, and since they have content we need, we want to read them

**Comment by OrKoN** [comment]
You can also disable PDF viewer via OOPIFs for now via

```
args: [
      '--disable-features=PdfOopif'
    ]
```

**Comment by Vasile-Peste** [comment]
> You can also disable PDF viewer via OOPIFs for now via
> 
> ```
> args: [
>       '--disable-features=PdfOopif'
>     ]
> ```

Thank you,
is there any documentation about this option?

**Comment by OrKoN** [comment]
There is an issue for that https://issues.chromium.org/issues/40268279

**Comment by OrKoN** [comment]
After further investigation, it looks like the feature might not be the reason for hanging (it seems to reproduce now with the feature disabled). It appears that the iframes from the pdf viewer extensions get reported into the page sessions via CDP (although they probably have to be contained to the extension target).

**Comment by przhkv** [comment]
I am experiencing freezing problem for `http` URLs but not `https`. Could that be the main issue here?
