### ISSUE TITLE
Error: Attempted to use detached Frame 

### ISSUE THREAD

**Issue by JayKaku** [puppeteer/puppeteer#12294]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {
  // Set up Puppeteer
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--disable-features=site-per-process"],
  });
  let page = await browser.newPage();

  // Navigate to LinkedIn
  await page.goto("https://www.linkedin.com/", { waitUntil: "networkidle2" });

  // Set the viewport's width and height
  await page.setViewport({ width: 1920, height: 1080 });

  // Login
  await page.waitForSelector("#session_key");
  await page.type("#session_key", "xxxxxxx");
  await page.type("#session_password", "xxxxxxxx");
  await page.click(".sign-in-form__submit-btn--full-width");


  await page.goto("https://www.linkedin.com/feed/");

  // Wait for the feed to load
  await page.$(".feed-shared-update-v2");
```

### Error string

Error: Attempted to use detached Frame '17600A3A4D0A80CA2CEBA03B03BD7DFB'

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Scrapping the element directly

### Reality

Error: Attempted to use detached Frame '17600A3A4D0A80CA2CEBA03B03BD7DFB'

### Puppeteer version

22.6.4

### Node version

20.12.2

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not able to reproduce using the script. Could you provide a non-password protected reproducible example?

**Comment by OrKoN** [comment]
Tried with my LinkedIn account and it does not reproduce as well. Could you provide a CDP log as described here https://pptr.dev/guides/debugging#log-devtools-protocol-traffic ? Make sure to remove your passwords from the log or other personal information.

**Comment by JayKaku** [comment]
> I am not able to reproduce using the script. Could you provide a non-password protected reproducible example?

So it's working perfectly?

**Comment by JayKaku** [comment]
> Tried with my LinkedIn account and it does not reproduce as well. Could you provide a CDP log as described here https://pptr.dev/guides/debugging#log-devtools-protocol-traffic ? Make sure to remove your passwords from the log or other personal information.

I'll try it out

**Comment by OrKoN** [comment]
@JayKaku yeah, I had to adjust selectors because the linkedin page accessible to me had a different layout but yeah it logged in, went to the feed and there were no errors

**Comment by JayKaku** [comment]
> ```ts
>   await page.$(".feed-shared-update-v2");
> ```

so this is where the error comes for me login and feed is all good, I might've missed to mention this

**Comment by JayKaku** [comment]
[scraper_log.txt](https://github.com/puppeteer/puppeteer/files/15030676/scraper_log.txt)
Is this the type of file you were expecting @OrKoN ? This is the 4th command that is being run

**Comment by OrKoN** [comment]
This log filtered out all CDP messages, we would need one with protocol messages, e.g., env DEBUG="puppeteer:*"

**Comment by OrKoN** [comment]
Thanks!  I can see that there is a message in 

```
2024-04-19T16:10:10.237Z puppeteer:protocol:RECV ◀ [
  '{"method":"Inspector.detached","params":{"reason":"Render process gone."},"sessionId":"B43DC6AB5A76928A2BDD988BFBF40F9B"}'
]
```

Which indicates that the browser has crashed. Can you try to reproduce using the latest version of Puppeteer 22.6.5?

**Comment by JayKaku** [comment]
> Thanks! I can see that there is a message in
> 
> ```
> 2024-04-19T16:10:10.237Z puppeteer:protocol:RECV ◀ [
>   '{"method":"Inspector.detached","params":{"reason":"Render process gone."},"sessionId":"B43DC6AB5A76928A2BDD988BFBF40F9B"}'
> ]
> ```
> 
> Which indicates that the renderer page has crashed. Can you try to reproduce using the latest version of Puppeteer 22.6.5?

Just tried it out same error persists in the latest version as well

**Comment by OrKoN** [comment]
@JayKaku could you try with the latest Canary build of Chrome?

**Comment by EwertonDiniz** [comment]
I have the same error! on version 22.6.5 and Latest build of Chrome.

**Comment by JayKaku** [comment]
> @JayKaku could you try with the latest Canary build of Chrome?

Canary builds looks a little more unstable, ` await page.goto("https://www.linkedin.com/feed/");` too leads to Attempted to used detached Frame error so I removed that line and tried it failed again at  `await page.$(".feed-shared-update-v2");`

**Comment by OrKoN** [comment]
@JayKaku could you test without the `args: ["--disable-features=site-per-process"]`?

**Comment by OrKoN** [comment]
When running with Canary, re-use the same userDataDir and enable crash reporting at chrome://crashes/ after a crash you can restart the browser, and get the crash ID from chrome://crashes Share the crash ID so that we could get more details about why the browser crashes.

**Comment by JayKaku** [comment]
> @JayKaku could you test without the `args: ["--disable-features=site-per-process"]`?

Let me try this out and get back

**Comment by cristianvnica** [comment]
I get this error after upgrading to `22.10.0`. I think I'll downgrade back to the previous version I was using `22.4.0` which was relatively more stable.
