### ISSUE TITLE
Page with CSP breaks puppeteer

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#1229]
A page with CSP will break some of puppeteer methods, such as `page.addScriptTag`. At the very least, we should fail gracefully.

It would be ideal to have a way to disable CSP altogether.

Reported in: #1091

**Comment by rakeshpai** [comment]
+1 for ability to disable CSP.

Use case: I'm using puppeteer as a post-build crawler to generate a static dump of my SPA. When crawling, I'd like to inline critical CSS, and add a CSP directive for the CSS text hash. While I'm at it, I want to change the API server from `localhost:port` to `api.example.com`. However, if my page already had a CSP meta tag in it (which is good to have during development so I can catch CSP violations early), puppeteer starts getting funky. Would love it if I can disable CSP altogether when crawling.

**Comment by sradu** [comment]
+1 for ability to disable CSP.

Thank you.

**Comment by yujiosaka** [comment]
In order to disable CSP, it's not a complete solution but adding `nonce-<base64-value>` to script tag will relax the security blocks. It only works for the site where the CSP headers or meta tags have the nonce part. It doesn't work for other sites, but in this way we don't have to change the default behavior or disable security blocks.

I'm working on that idea, but it will be probably difficult to completely disable CSP with current Chrome DevTool Protocol because I don't find APIs to intercept/modify response headers to do that yet.

**Comment by niieani** [comment]
Here's my workaround:

```ts
  import fetch from 'node-fetch'

  const requestInterceptor = async (request) => {
    const url = request.url()
    const requestHeaders = request.headers()
    const acceptHeader = requestHeaders.accept || ''
    if (url.includes('some-website-with-csp.com') && (acceptHeader.includes('text/html'))) {
      const cookiesList = await page.cookies(url)
      const cookies = cookiesList.map(cookie => `${cookie.name}=${cookie.value}`).join('; ')
      delete requestHeaders['x-devtools-emulate-network-conditions-client-id']
      if (requestHeaders.Cookie) {
        requestHeaders.cookie = requestHeaders.Cookie
        delete requestHeaders.Cookie
      }
      const theseHeaders = Object.assign({'cookie': cookies}, requestHeaders, {'accept-language': 'en-US,en'})

      const init = {
        body: request.postData(),
        headers: theseHeaders,
        method: request.method(),
        follow: 20,
      }
      const result = await fetch(
        url,
        init,
      )
      const resultHeaders = {}
      result.headers.forEach((value, name) => {
        if (name.toLowerCase() !== 'content-security-policy') {
          resultHeaders[name] = value
        } else {
          console.log('CSP', `omitting CSP`, {originalCSP: value})
        }
      })
      const buffer = await result.buffer()
      await request.respond({
        body: buffer,
        resultHeaders,
        status: result.status,
      })
    } else {
      request.continue();
    }
  }

  await page.setRequestInterception(true)
  page.on('request', requestInterceptor)
```

Related: #599

**Comment by marcelmattsson** [comment]
@niieani, I'm getting requestStory undefined. is it something I'm missing or where does that variable come from?

**Comment by niieani** [comment]
@marcelmattsson apologies, that was just my logger I forgot to remove before posting (I use `storyboard` for logging). Corrected the snippet above.

**Comment by marcelmattsson** [comment]
haha no worries, guess I'm doing something else wrong then since I'm still getting the EvalError even though I also see the console log telling me its omitting CSP.

**Comment by niieani** [comment]
@marcelmattsson perhaps some TypeScript leftovers were causing it (I'm assuming you're not using it)? I've removed all the types from my snippet now (I think so at least).

**Comment by marcelmattsson** [comment]
Was never CSP in the headers at all... was meta tags with CSP who was the culprit.

**Comment by XBeg9** [comment]
+1 CSP breaks my flow. :( no workarounds as for now.

**Comment by niieani** [comment]
Hi @XBeg9, doesn't my workaround work for you?

**Comment by XBeg9** [comment]
@niieani does not. :(

**Comment by niieani** [comment]
@XBeg9 perhaps similarly to @marcelmattsson you need to actually transform the HTML, not the headers? You have access to the body in `result.buffer()`.

**Comment by divyamvn** [comment]
+1 for fixing this.

Upgrade to v1.0.0, fails all my tests too, due to the same reason (all WaitFor.. methods failing due to CSP)
Rolling back to v0.13.0.

**Comment by sh00tingStar** [comment]
please, turn off that ...

**Comment by wurde** [comment]
This is a problem. I can't even do basic `page.$$(selector)` selections. Wouldn't the simplest solution be to have a Chromium flag that toggles/ignores CSP?

**Comment by XBeg9** [comment]
Just downgrade to version `0.13`, it works great. Waiting for update here

**Comment by xprudhomme** [comment]
When trying to inject a Javascript file, there's no need to downgrade here. Simply replicate the 0.13.0 previous code, such as:

```javascript
  async injectFile(page, filePath) {

    let contents = await new Promise((resolve, reject) => {
      fs.readFile(filePath, 'utf8', (err, data) => {
        if (err) return reject(err);
        resolve(data);
      });
    });
    contents += `//# sourceURL=` + filePath.replace(/\n/g,'');
    return page.mainFrame().evaluate(contents);
  }
```

**Comment by swftvsn** [comment]
Please fix CSP problems, this is affecting us also, but can't downgrade because we need xpath..

**Comment by swftvsn** [comment]
It also seems that if I use the fix @niieani wrote, the page I need to test does not load correctly.

But it's neat to know I can manipulate the requests. :)

**Comment by andrewlinfoot** [comment]
@swftvsn we are using v0.13.0 and needed xpath too so we built out some xpath utils. I copied the file from our project for you. It's technically typescript but you can strip out the types to make it JS with just a few modifications. Hope it helps!

https://gist.github.com/andrewlinfoot/89d74295d263826a921ae6353cae7d5f

**Comment by swftvsn** [comment]
Thanks @andrewlinfoot ! I use typescript too, so it's perfect!

**Comment by tnolet** [comment]
Just bumped into this and this is quite an issue! Confident this will be solved. For anyone just finding this, here is an example of what goes wrong

[![Run with Puppeteer Sandbox](https://puppeteersandbox.com/static/button.svg)](https://puppeteersandbox.com/S0HVfA1j)

**Comment by sean-hill** [comment]
I'm facing this issue as well 😢  👍

**Comment by sradu** [comment]
@aslushnikov  Would it be possible to make evaluateOnNewDocument work as well?

**Comment by aslushnikov** [comment]
>  Would it be possible to make evaluateOnNewDocument work as well?

@sradu it does work for me; here's the test atop of #2289:

https://github.com/aslushnikov/puppeteer/commit/b075337ab02530d0dc711891d82288bb970c2017

Do you have a scenario I can repro?

**Comment by sradu** [comment]
Thanks @aslushnikov! I read the commit log and didn't make the connection that all evaluate() functions are going to work now.

Just yesterday we saw a CSP error using an older tree. We'll retest in the next two days.

**Comment by aslushnikov** [comment]
> Just yesterday we saw a CSP error using an older tree. We'll retest in the next two days.

@sradu Well, actually `evaluateOnNewDocument` should work on 1.2.0 with CSP. I did the test atop of that PR so that I can re-use the testing infrastructure for the CSP.

Do you have an example I can play with?

**Comment by chris-macdonald** [comment]
Thanks @aslushnikov! I've got tests that were passing with an interception workaround (thanks @niieani for the idea)... removed the interception, installed from your fork and the tests still pass. :)

**Comment by garris** [comment]
Thanks @niieani — your solution inspired this simplified approach for a backstopjs usecase https://github.com/garris/BackstopJS/commit/67801c259f340c986bd0c25281a7eb5a79c7bc25

@aslushnikov looking forward to #2324! 🎁

**Comment by niieani** [comment]
Great to hear it was useful @garris! Also looking forward to #2324 :)

**Comment by crisdosaygo** [comment]
Another workaround (without removing CSP from the entire page, which depending on security requirements of your use may leave the site too wide open) is to parse the CSP script-src directive, and pick a URL that is allowed. 

Then in your injected script tag create a fake URL from the origin allowed by CSP, for example, if CSP script-src looks like:

`script-src 'self' https://*.example.com`

then inject a script tag with the following src:

`<script src=https://random343489.example.com/my-fake-path/my-script-001.js></script>`

**then** create a fake "virtual proxy" to intercept requests for:

`https://random343489.example.com/`

and keep an internal map of 

```js
{
  ['my-fake-path/my-script-001.js']: {
    headers: { ... },
    responseBody: '...'
 }
}
```

and serve those headers and body in response to the request you intercepted from  your injected script tag.

**Comment by aespinoza96** [comment]
By setting the flag page.setBypassCSP to true work for me.
https://github.com/puppeteer/puppeteer/pull/2324
