### ISSUE TITLE
[Bug]: `PerformanceNavigationTiming.type` is `navigation` after pressing back button

### ISSUE THREAD

**Issue by BjornDCode** [puppeteer/puppeteer#12306]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () =>{
  const browser = await puppeteer.launch()
  const page = await browser.newPage()

  await page.goto('https://example.com/')
  await page.click('a')
  await page.goBack()

  const entry = await page.evaluate(() => performance.getEntries()[0].toJSON())

  await browser.close()

  console.log(entry.type) // 'navigation'
})()
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We have an e2e test where we grab an instance of `PerformanceNavigationTiming` via `performance.getEntries()[0]` and expect it to be `back_forward`. We recently upgraded from `21.1.0` where it was working correctly

### Expectation

Expected `PerformanceNavigationTiming.type` to equal `back_forward`

### Reality

`PerformanceNavigationTiming.type` equals `navigation`

### Puppeteer version

22.6.5

### Node version

20.7.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Starting with v22 (see the changelog/release node), the [new headless mode](https://developer.chrome.com/docs/chromium/new-headless) that more closely matches the real browser is used by default. The equivalent code for the latest versions is:

```
import puppeteer from 'puppeteer';

(async () =>{
  const browser = await puppeteer.launch({
    headless: 'shell'
  })
  const page = await browser.newPage()

  await page.goto('https://example.com/')
  await page.click('a')
  await page.goBack()

  const entry = await page.evaluate(() => performance.getEntries()[0].toJSON())

  await browser.close()

  console.log(entry.type) // 'back_forward'
})()
```

Note that the old headless mode is technically a different browser implementation and the current behavior of the headless mode matches the headful browser behavior (unlike headless: 'shell')

**Comment by mattzeunert** [comment]
Thanks @OrKoN!

I'm surprised that the less realistic implementation is reporting the back_forward navigation, but not the more realistic one. Does `goBack` / `Page.navigateToHistoryEntry` not count as a real back/forward navigation?

**Comment by OrKoN** [comment]
It does count as a back/forward navigation I believe (see https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/navigation_controller_impl.cc;l=1229;drc=5d803914ee94bf531c2582a097c9ca0b39b9d52d which sets the flag, it is called by `Page.navigateToHistoryEntry`) but perhaps the performance API does not expose it? (to counter fingerprinting or back button highjacking? I am not really sure). If I do the steps manually and call performance.getEntries()[0].toJSON(), I get the same type (`navigate`) as the latest versions of Puppeteer.

**Comment by OrKoN** [comment]
Alright, it looks like back_forward is not actually a spec compliant type https://w3c.github.io/timing-entrytypes-registry/#registry

**Comment by OrKoN** [comment]
So the type is indeed different and it looks like back_forward is possible if the navigation is "applied from history" https://w3c.github.io/navigation-timing/#dom-navigationtimingtype-back_forward

So I am not sure if this is correct implementation in Chrome but Puppeteer's result match the headful and manual testing. If it looks like a bug to you, please file a https://crbug.com/new issue 

P.S. tested with Firefox and Puppeteer and the entry.type is the same (`navigate`)
