### ISSUE TITLE
[Bug]: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by yuntao1997** [puppeteer/puppeteer#12300]
### Steps to reproduce

I have multiple threads, and when I do this for a while, I get an exception

I was looking for some information, found that have the same problem

[https://stackoverflow.com/questions/64426363/how-to-fix-error-spawn-enametoolong-puppeteer](https://stackoverflow.com/questions/64426363/how-to-fix-error-spawn-enametoolong-puppeteer)

```js
async function createBrowser(options = {}) {
    const browser = await puppeteer.launch(options );

    return browser
}


let browser = await createBrowser()

try{
      // do something
}finally{
 browser && browser.close()
}
````

### Expected results

Solve this problem

### Actual results

`
Error: spawn ENAMETOOLONG at ChildProcess.spawn (node:internal/child_process:413:11) at Object.spawn (node:child_process:692:9) at Object.spawn (pkg/prelude/bootstrap.js:2076:27) at new Process (C:\snapshot\wjx-auto-backend\node_modules\.pnpm\@puppeteer+browsers@2.2.1\node_modules\@puppeteer\browsers\lib\cjs\launch.js:146:56) at launch (C:\snapshot\wjx-auto-backend\node_modules\.pnpm\@puppeteer+browsers@2.2.1\node_modules\@puppeteer\browsers\lib\cjs\launch.js:50:12) at ChromeLauncher.launch (C:\snapshot\wjx-auto-backend\node_modules\.pnpm\puppeteer-core@22.6.4\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:80:54) at async PuppeteerExtra.launch (C:\snapshot\wjx-auto-backend\node_modules\.pnpm\puppeteer-extra@3.3.6_puppeteer-core@22.6.4\node_modules\puppeteer-extra\dist\index.cjs.js:128:25) at async createBrowser (C:\snapshot\wjx-auto-backend\utils\puppeteer.js:76:21) at async OrderService._createBrowser (C:\snapshot\wjx-auto-backend\services\OrderService.js:321:25) at async C:\snapshot\wjx-auto-backend\services\OrderService.js:389:27
`

**Comment by OrKoN** [comment]
I am unable to reproduce on Windows 10 with node 18.8.0. The restriction comes from your operating system/file system (perhaps from node)?. Make sure that your executable path is not too long by, for example, moving your code and the browser to a location with a shorter path.

**Comment by yuntao1997** [comment]
This problem doesn't come up all the time, sometimes it comes up every hour or two, sometimes it doesn't

My executable path is fixed.   C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

So that's not the problem?

**Comment by OrKoN** [comment]
The path looks like fine. It is weird that it comes from time to time, Puppeteer only gives this path + arguments to Node via ChildProcess.spawn and as you can see the error comes from Node. Which Node version do you use? do you always send the same arguments when you launch?

**Comment by OrKoN** [comment]
Can you run with the env var `DEBUG=puppeteer:browsers:` and post which arguments are provided when it fails compared to when it is successful?

**Comment by yuntao1997** [comment]
node version is 20.12.2

Ok, I'll try. Thank you

**Comment by OrKoN** [comment]
I tried multiple times with the same node version on windows 10 but it is not reproducible for me

**Comment by yuntao1997** [comment]
Yes, it doesn't come up every time, it only comes up after it's been running for a while

When this exception occurs, I output the current memory, CPU, etc., and they are all normal

I'll add the debug environment variable first, and see the difference when the exception occurs again

**Comment by yuntao1997** [comment]
Sorry, it's my issue. After setting the debug environment variable, I discovered the problem through the logs.

I have a launch args, due to a referencing issue, each time a browser is created, a value is pushed into it. This leads to an exceptionally large number of **launch args** values after running for a while, causing an exception in puppeteer.launch.
