### ISSUE TITLE
[Bug]: Error: net::ERR_FAILED

### ISSUE THREAD

**Issue by harshNotExistent** [puppeteer/puppeteer#12308]
So in my use case I am trying to pre render few thousands of URL and store them in cache for pre-rendering using "puppeteer": "^19.8.3".

Good part is it works for mostly all of the urls,
but a strange scenario comes up where for few 200 urls the puppeteer opens up for a while closes within a sec, with error string as  
"errorText":"net::ERR_FAILED"

What can be the issue here ?

Any help would be appreciated.
Thanks!

**Comment by OrKoN** [comment]
Use try/catch to catch the network errors which are possible when opening URLs. Or provide a minimal reproducible example and fill out the Puppeteer issue template, thanks!
