### ISSUE TITLE
[Bug] puppeteer.launch with cmd file cause spawn EINVAL with recent node security patch

### ISSUE THREAD

**Issue by MikeZeDev** [puppeteer/puppeteer#12302]
### Minimal, reproducible example

```TypeScript
import fs from 'node:fs/promises';
import * as puppeteer from 'puppeteer-core';


fs.writeFile("./helloWorld.cmd", 'echo "Hey there!"', function(err) {
    if(err) {
        return console.log(err);
    }
    console.log("The file was saved!");
}); 
 
  const browser2 = await puppeteer.launch({
      headless: false,
      defaultViewport: null,
      ignoreDefaultArgs: true,
      executablePath: "./helloWorld.cmd",
  });
  
```

### Error string

Error: spawn EINVAL

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I use pupetter to invoke nw.js using pupetter.launch. On Windows, it turns to be a cmd file : `\node_modules\.bin\nw.cmd`.

However, with the recent Node update, [and this security patch ](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2), we got a spawn EINVAL error on Windows when we try to spawn a childprocess from a cmd file.

The solution would be to include `{ shell : true }` when pupetter is using child_process.spawn, i think, or something like that.

### Expectation

Being able to use pupetter.launch ( "cmd file") on Windows platform normally.

### Reality

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at new Process (file:///C:/Users/[redacted]/Documents/VisualStudio/Projects/_test/node_modules/@puppeteer/browsers/lib/esm/launch.js:137:45)
    at launch (file:///C:/Users/[redacted]/Documents/VisualStudio/Projects/_test/node_modules/@puppeteer/browsers/lib/esm/launch.js:42:12)
    at ChromeLauncher.launch (file:///C:/Users/[redacted]/Documents/VisualStudio/Projects/_test/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:54:32)
    at async file:///C:/Users/[redacted]/Documents/VisualStudio/Projects/_test/test.mjs:12:20 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

### Puppeteer version

22.6.5

### Node version

21.7.3

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not sure we would be able to set shell by default as it would be a breaking change and it would require some extra measure to sanitize the input args/executable path. Is there an alternative way to launch nw.js?

**Comment by MikeZeDev** [comment]
> I am not sure we would be able to set shell by default as it would be a breaking change and it would require some extra measure to sanitize the input args/executable path

I dont mean to set it by default, but perhaps something as a new option in pupeteer.launch. Something that will not break anything as its optional.

And yes it will need to be sanitized. But apparently Node maintainers left this work to the end developer. I am not sure what would be the good approach here.

> Is there an alternative way to launch nw.js?

Maybe it could be fixed in our script, of course .The thing is, i opened this issue here because its a breaking change.
Not being able to launch cmd fine on Windows environment can be annoying and possibly affect more people.

**Comment by OrKoN** [comment]
We do not officially support nw.js or launching shell/cmd files though (it just happened to work). Is it possible to workaround the issue by invoking cmd.exe and giving the cmd file as an argument via `args`?

**Comment by MikeZeDev** [comment]
> We do not officially support nw.js or launching shell/cmd files though (it just happened to work). 
Understandable.

> We do not officially support nw.js or launching shell/cmd files though (it just happened to work). Is it possible to workaround the issue by invoking cmd.exe and giving the cmd file as an argument via `args`?

This could be a workaround, yeah. I may try something like that.

**Comment by OrKoN** [comment]
```
      executablePath: "C:/Windows/System32/cmd.exe",
      args: ['/c', 'helloWorld.cmd']
```

The above seems to work for me.

**Comment by MikeZeDev** [comment]
I just have to check it providing arguments for a cmd as other 'args' works that way, thats it.
