### ISSUE TITLE
[Bug]: #<NoSuchFrameException> occurs even when manually navigating to a page while the browser is idle in puppeteer 

### ISSUE THREAD

**Issue by b68h4** [puppeteer/puppeteer#12313]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async ()) => {
      // Launch custom browser and get cdp URL (proxy included custom chromium based browser)
      const browser = await puppeteer.connect({
            browserURL: cdpUrl,
            defaultViewport: null,
            ignoreHTTPSErrors: true,
            protocol: "webDriverBiDi",
        })
       const browserProcess = this.browser.process()!;
       const context = await this.browser.defaultBrowserContext();
       const page = (await this.context.pages())[0];
       page.on("response", async (resp) => {}); // I commented everything there but it didn't work
       await page.goto("https://ifconfig.me", {
            timeout: 30000,
            waitUntil: "domcontentloaded",
        }); // For custom browser proxy authentication
       await this.page.waitForSelector("body"); 
       // Wait for ifconfig.me body (function runs successfully but other sites cause a crash after this function run) i think there is a bug there because if this line is deleted I don't get a crash
       // Only wait in idle and manually go to bot.sannysoft.com or another Cloudflare turnstile included page and get a crash
}
```

### Error string

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<NoSuchFrameException>".] {   code: 'ERR_UNHANDLED_REJECTION' }

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Chromium based browser version: 123.0.6312.46

### Expectation

Open the page without the puppeteer crash

### Reality

`[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<NoSuchFrameException>".] { code: 'ERR_UNHANDLED_REJECTION' }`

Crashed with this error

### Puppeteer version

22.7.0

### Node version

16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

macOS

**Comment by OrKoN** [comment]
I am not able to reproduce. Please make sure the example is executable and uses the Chrome version bundled with Puppeteer. Also, Node 16 is not supported anymore.
