### ISSUE TITLE
[Feature]: Let docker/Dockerfile use node:20-slim as the base image

### ISSUE THREAD

**Issue by Androbin** [puppeteer/puppeteer#12311]
### Feature description

The official [Puppeteer Docker images](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer) currently use node:20 as the base image.
The same [Dockerfile](https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile) using node:20-slim as the base image works just the same.
Users would appreciate the option of choosing the slim variant for their projects.

**Comment by OrKoN** [comment]
> This image does not contain the common packages contained in the default tag and only contains the minimal packages needed to run node. Unless you are working in an environment where only the node image will be deployed and you have space constraints, we highly recommend using the default image of this repository

(source https://hub.docker.com/_/node)

I am not sure we would like to support multiple different variants of Docker images, especially, the ones that are not recommended. Probably, you would need to build your own image if you want to use the slim (or other) variants.

**Comment by OrKoN** [comment]
Given the above, we won't support other base images for now.
