### ISSUE TITLE
Docs: document page.once()

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1231]
https://github.com/GoogleChrome/puppeteer/issues/1228#issuecomment-340869335 has a nice snippet that uses `page.once` but I'm not seeing that in the api docs.

**Comment by aslushnikov** [comment]
That's not puppeteer, that's node: `once` is a standard node.js method on event emitters, similar to `on` and `removeListener`: [node.js events](https://nodejs.org/api/events.html#events_emitter_once_eventname_listener)

**Comment by ebidel** [comment]
Oh nice. Didn't even realize EventMitter had that. Do you think it's worth adding at least one example to the docs. I can imagine a lot of people wanting to catch a first event and ignore the rest.

**Comment by aslushnikov** [comment]
@ebidel sure, we can use it somewhere in the docs where it makes sense. We can also specifically state that page/browser are node's event emitters.
