### ISSUE TITLE
Switch to macos-latest (arm64) in ci

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12327]
See https://github.com/puppeteer/puppeteer/pull/12326

**Comment by OrKoN** [comment]
We do support Puppeteer on mac arm64 but there are some issues on the Github Actions runners. We had a few test failures in Chrome as seen here https://github.com/puppeteer/puppeteer/actions/runs/9356693211/job/25754758510?pr=12328 (not reproducible on live mac arm64 devices) but also Firefox could not be run on macos-latest for some reason  (https://bugzilla.mozilla.org/show_bug.cgi?id=1893921)

**Comment by OrKoN** [comment]
We do support Puppeteer on mac arm64 but there are some issues on the Github Actions runners. We had a few test failures in Chrome as seen here https://github.com/puppeteer/puppeteer/actions/runs/9356693211/job/25754758510?pr=12328 (not reproducible on live mac arm64 devices) but also Firefox could not be run on macos-latest for some reason  (https://bugzilla.mozilla.org/show_bug.cgi?id=1893921)

**Comment by smoya** [comment]
> We do support Puppeteer on mac arm64 but there are some issues on the Github Actions runners. We had a few test failures in Chrome as seen here https://github.com/puppeteer/puppeteer/actions/runs/9356693211/job/25754758510?pr=12328 (not reproducible on local mac arm64 devices) but also Firefox could not be run on macos-latest for some reason (https://bugzilla.mozilla.org/show_bug.cgi?id=1893921)

I guess then you recommend downgrading to `macos-13` in the meantime?

**Comment by OrKoN** [comment]
It is probably a good idea for now, once Firefox is able to run on Github Actions runners we would go back to macos-latest. Note that on local macos-14 arm64 devices we do not experience this issue but so far it is not clear what causes it on Github Actions runners.

**Comment by OrKoN** [comment]
@smoya although perhaps you could isolate the failure that you see and file a bug report in case it is happening with Chrome? I am not sure that our test suite has the same failure.

**Comment by OrKoN** [comment]
It might have something to do with the virtualization Github Actions runners use https://github.com/actions/runner-images/issues/9974#issuecomment-2150347670
