### ISSUE TITLE
Support x/y click offset in page.click()

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1232]
Opening this to capture discussions around https://github.com/GoogleChrome/puppeteer/issues/1089. @JoelEinbinder and I chatted about adding an option to `page.click()` so users could specify an x/y offset for the click (instead of always defaulting to the center of the element).  Currently, there's a fair amount of code that users need to write to do that (get element, get bounding box, use `page.mouse.click()`, etc.) and `page.click` already has most of that built in (get via css selector, scroll to element, click it).

Would be nice to have something shorter.

**Comment by aslushnikov** [comment]
@ebidel @JoelEinbinder is there any api suggestion? x/y might not be very convenient since there are dozens of different coordinate systems.

Should we have "location" argument instead, e.g.:
```js
page.click('.tweet', {
  location: 'topleft' // defaults to 'center', could be also 'topright',...
});
```

**Comment by JoelEinbinder** [comment]
I like offsetX because it corresponds to the property on mouse events

**Comment by aslushnikov** [comment]
offsetX - relatively to what position and in which coordinates? Does it account for transforms?

**Comment by ebidel** [comment]
`offset*` SGTM. That's from the center or the topleft?

> which coordinates? Does it account for transforms?

Does `page.click()` account for those? Whatever it does :)

**Comment by aslushnikov** [comment]
Looks like there's not much need for this - I'll close this until there's more demand.

**Comment by jakegkaplan** [comment]
Is this available? Is there some sort of workaround currently?

**Comment by tnoetzel** [comment]
I would totally use this. Often-times there are overlapping elements that cause issues that an offset would solve...

**Comment by aslushnikov** [comment]
@tnoetzel @GHACK101 using offsets for clicking overlapping elements is very fragile; you can use WebPlatform's [`element.click()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click) method to overcome this:

```js
  await page.evaluate(() => {
    document.querySelector('.tweet').click();
  });
```

**Comment by ashleyR94** [comment]
:+1:  Would like to see the location argument

**Comment by vc1** [comment]
drag element, draw in canvas, canvas game,  gesture animation ?

**Comment by ameliabradley** [comment]
@aslushnikov Why wouldn't the mouse coordinate system function using the same mechanism as the screenshot clip coordinate system? That seems like the most consistent way to implement this feature.

The same arguments about fragility apply to both.

@vc1 brings up a good point. There is a whole class of web applications that Puppeteer is completely incapable of handling because it's missing this one feature.

The workaround would be to simulate a MouseEvent:

```javascript
function click(x,y){
    var ev = document.createEvent("MouseEvent");
    var el = document.elementFromPoint(x,y);
    ev.initMouseEvent(
        "click",
        true /* bubble */, true /* cancelable */,
        window, null,
        x, y, 0, 0, /* coordinates */
        false, false, false, false, /* modifier keys */
        0 /*left*/, null
    );
    el.dispatchEvent(ev);
}
```
(Sourced from [this](https://stackoverflow.com/questions/3277369/how-to-simulate-a-click-by-using-x-y-coordinates-in-javascript/16509592#16509592) StackOverflow answer.)

But I haven't tested this myself, and people report that it doesn't work in canvas.

**Comment by giuseppeg** [comment]
this would be really useful to click on elements within an iframe which we cannot control

**Comment by kumorig** [comment]
> using offsets for clicking overlapping elements is very fragile
When testing if an element is clickable or not `document.querySelector('.tweet').click();` would be useless since it can click anything *even* when the element is overlapped.  I would prefer a fragile method. 

Sorry if this already exist somewhere. This page is the first hit searching for `puppeteer click x y`.

**Comment by aslushnikov** [comment]
> @aslushnikov Why wouldn't the mouse coordinate system function using the same mechanism as the screenshot clip coordinate system? 

This is already implemented with the [`Mouse.click(x, y)`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-mouseclickx-y-options) api.

**Comment by nguyenlam1** [comment]
A feature that I would find useful is to offset from the center when clicking on a selector. 

Example

`page.click('.foo', { offset: { x: 20, y: 20 } }) // Would move the element matching selector foo 20px to the right and 20px down starting from the center.
`

**Comment by azazrehman** [comment]
For clicking the element on its start (specific position). Here I implement it

`let mySelector='div[id="test"]' `
`const myObject = await page.$(mySelector)`                                                            
 `const coOrdinates = await myObject.boundingBox()`
 `await page.mouse.click( coOrdinates.x+1 , coOrdinates.y+1 )`

**Comment by Haris3243** [comment]
> For clicking the element on its start (specific position). Here I implement it
> 
> `let mySelector='div[id="test"]' `
> `const myObject = await page.$(mySelector)`
> `const coOrdinates = await myObject.boundingBox()`
> `await page.mouse.click( coOrdinates.x+1 , coOrdinates.y+1 )`

@azazrehman but it not worked in my case when i changed my object's position to some other point

**Comment by azazrehman** [comment]
> > For clicking the element on its start (specific position). Here I implement it
> > `let mySelector='div[id="test"]' `
> > `const myObject = await page.$(mySelector)`
> > `const coOrdinates = await myObject.boundingBox()`
> > `await page.mouse.click( coOrdinates.x+1 , coOrdinates.y+1 )`
> 
> @azazrehman but it did not work in my case when I changed my object's position to some other point
Can you please share your code so that we can check it
