### ISSUE TITLE
[Bug]: Instructions can be improved/corrected

### ISSUE THREAD

**Issue by thdoan** [puppeteer/puppeteer#12324]
### Minimal, reproducible example

```TypeScript
A couple issues with the README.md...

1. For people who arrive at https://www.npmjs.com/package/puppeteer-core, following the instructions there will not work:


import puppeteer from 'puppeteer';
```

The documentation needs to point out that for puppeteer-core, the correct import is as follows:

```
import puppeteer from 'puppeteer-core';
```

2. This actually won't work in reality:

```
await page.type('.devsite-search-field', 'automate beyond recorder');
```

It's missing the command to press the Enter key in order to perform the search:

```
await page.keyboard.press('Enter');
```
```


### Error string

N/A

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

_No response_

### Expectation

N/A

### Reality

N/A

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

22.7.0

### Node version

18.18.0

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Windows

**Comment by thdoan** [comment]
There's no issue to reproduce, this was only to improve the instructions.

**Comment by OrKoN** [comment]
Will be fixed via https://github.com/puppeteer/puppeteer/pull/12500 the example actually runs for me as is (without enter as there are inline search results showing I believe)
