### ISSUE TITLE
[Bug]: Could not find Chrome (ver. ${this.puppeteer.browserRevision}) on Docker

### ISSUE THREAD

**Issue by vickonrails** [puppeteer/puppeteer#12332]
### Minimal, reproducible example

```TypeScript

// rest of code 
const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox']
        })
  const page = await browser.newPage()
  await page.setContent(html)
  const pdf = await page.pdf({ format: 'A4', printBackground: true })
  await browser.close();
  return pdf

// rest of code
```

### Error string

Could not find Chrome (ver. ${this.puppeteer.browserRevision})

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

An API in my Node project exposes a route that accepts HTML in the body. This markup is used alongside some CSS to generate a PDF and send a buffer back as a response. 

**NB**: I was previous using Bun, but I switched to node to make sure it wasn't a problem with bun.

Here's my docker file
```bash
FROM node

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the application code
COPY . .

# Set environment variable for production
ENV NODE_ENV production

# Specify command to start the application
CMD ["node", "index.js"]
```

I made a [repro here](https://github.com/vickonrails/puppeteer-repro)

### Expectation

The endpoint returns a PDF when running in a docker container as it works when running normally as a node app. 

### Reality

This works when I run as a node app, but when I try to run in a docker container, it gives the following error 

Could not find Chrome (ver. 124.0.6367.60). This can occur if either
1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
2. your cache path is incorrectly configured (which is: /usr/src/app/.cache/puppeteer).\nFor (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration

### Puppeteer configuration file (if used)

```TypeScript
const { join } = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
    // Changes the cache location for Puppeteer.
    cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

"puppeteer": "^22.7.1"

### Node version

"node":"^21.1.0"

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by OrKoN** [comment]
you need to run installation after your copied the config into the project folder

**Comment by OrKoN** [comment]
So probably 

```
FROM node

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
# Copy rest of the application code
COPY . .
RUN npm install

# Set environment variable for production
ENV NODE_ENV production

# Specify command to start the application
CMD ["node", "index.js"]
```

would work.

**Comment by vickonrails** [comment]
Thank you so much for looking into this @OrKoN. Unfortunately, moving the install after the copy command didn't change anything. 

Generally, I think it has to do with the way the chrome browser is resolved in the docker environment (vs my normal running application). Here are a couple of reasons I think so

- `.cache` is present in both docker and normal install (I can even dig deeper to find the Google Chrome For Test)
- It currently points to `/usr/src/app/.cache/puppeteer` which is where puppeteer installs chrome.

But I still can't figure out why it would find it in a docker environment

**Comment by OrKoN** [comment]
@vickonrails perhaps you need to make sure your local node_modules do not get copied to the Dockerfile cause in that case npm install might not install Puppeteer.

**Comment by vickonrails** [comment]
If anyone runs into this, I solved this by installing chrome manually. 

Here's what my `Dockerfile` looks like

```bash
# I'm using bun but you can replace with node
FROM oven/bun

# manually download chromium and some fonts. It's important to know the package manager your base image uses. 
# In this case `oven/bun` is based on debian and apt-get is the package manager

RUN apt-get update && apt-get install -y \
    fonts-dejavu fonts-droid-fallback fonts-freefont-ttf fonts-liberation \
    chromium \
    && rm -rf /var/lib/apt/lists/*

# set the executable path and tell puppeteer to not download chromium
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

WORKDIR /usr/src/app

COPY package*.json ./
COPY . .

# Install after copying the files
RUN bun install

ENV NODE_ENV production

CMD [ "bun", "start" ]
```

I hope this helps someone
