### ISSUE TITLE
ignoreHttpsErrors should be renamed to acceptInsecureCerts

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12341]
- to align with WebDriver
- to actually indicate that the flag only handling insecure certificates and not all SSL/HTTPS errors

**Comment by olivierr91** [comment]
@Lightning00Blade This should be listed as breaking change in the change log. Non-typescript projects will still build but the old flag will not work.

**Comment by Lightning00Blade** [comment]
@olivierr91 Related issue - https://github.com/puppeteer/puppeteer/issues/12989
You can see that this is mentioned at - https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/CHANGELOG.md#2300-2024-08-07
