### ISSUE TITLE
[Bug]: PDF page numbers no longer working in headless: shell

### ISSUE THREAD

**Issue by dannybeckett** [puppeteer/puppeteer#12361]
> Ever since updating to version `22.2.0`, the page number no longer appears. Is anyone else experiencing this issue on a Debian server? It seems to be working fine on a Mac.

_Originally posted by @outbackStack in https://github.com/puppeteer/puppeteer/issues/5345#issuecomment-1963292064_

**Comment by dannybeckett** [comment]
Created an issue from this comment. I am also experiencing lack of page numbers when using `headless: 'shell'`. I also tried adding `--lang=en-US` to the `args` of `const browser = await puppeteer.launch()`

**Comment by outbackStack** [comment]
This issue is currently open at #12196

**Comment by OrKoN** [comment]
Duplicate of https://github.com/puppeteer/puppeteer/issues/12196
