### ISSUE TITLE
Expose underlying chrome process

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#1238]
Hey all - quick question

I need access to the underlying chrome process that is launched by this tool. Is there a way to access it given the API? Would you be willing to expose it?

**Comment by aslushnikov** [comment]
@ORESoftware would you mind sharing your scenario?

**Comment by ORESoftware** [comment]
yeah np, I need to kill the process at will and collect the exit code. Can I get the exit code using this lib as it is? 

To be more specific, I am creating a test runner. Imagine the user uses the --bail option. If a test fails, I need to kill the browser immediately. 

TBH, it helps to have access to the underlying Node.js child process instance, it will never hurt your users.

**Comment by aslushnikov** [comment]
> yeah np, I need to kill the process at will and collect the exit code. Can I get the exit code using this lib as it is?

I guess chrome's exit code will be 0 most of the time (until it crashes?).

> To be more specific, I am creating a test runner. Imagine the user uses the --bail option. If a test fails, I need to kill the browser immediately.

There's `browser.close()` that would close the browser. Would it work for you?

> TBH, it helps to have access to the underlying Node.js child process instance, it will never hurt your users.

I'd rather expose less to avoid misuse. For example, killing chrome turned out to be quite a problem, check out #1047 and #615.

**Comment by ORESoftware** [comment]
ok, np, thanks for the info, I will try to work with it as it is, if I have problems will bring them up later
