### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nyxar77** [puppeteer/puppeteer#12390]
# Minimal, reproducible example
## Main file ( "Index.js" type ="module")

```TypeScript
import puppeteer from "puppeteer";
import { getTheAudio } from "./getTheAudio.mjs";
const browser = await puppeteer.launch({
  headless: false,
});
const page = await browser.newPage();
await page.goto("https://app.ofppt-langues.ma/platform/#/learning-path/mission/DONNER_SES_INFORMATIONS_PERSONNELLES_A1/lesson/FR_FR_A1_GRAMMAR_DEMANDER_ET_DONNER_LA_DATE/activity/FR_FR_A1_GRAMMAR_DEMANDER_ET_DONNER_LA_DATE_EXERCISE_DEMANDER_ET_DONNER_LA_DATE_2/exercise/item/0");

await getTheAudio(page);

```

## The Function: "getTheAudio.mjs"
```TypeScript
import fs from "fs";

export async function getTheAudio(page) {
  page.on("response", async (response) => {
    const url = response.url();
    const extension = url.split(".").pop();
    const contentType = response.headers()["content-type"];
    if (extension === "blu" && contentType === "audio/mpeg") {
      try {
        let audioBlu = await response.buffer();
        fs.writeFileSync("./AudioJunk/generatedAudio.mp3", audioBlu);
      } catch (error) {
        console.error("the error is: ", error);
        return false;
      }
    }
  });
}
```

### Error string

no error

### Bug behavior

- [X] Flaky
- [ ] PDF

#### Description:
The `getTheAudio` function is designed to catch responses with a specific content type (`audio/mpeg`) and save them to a file. However, there are instances where the desired response (`.blu` file) is not detected by Puppeteer's `page.on("response")` event handler, leading to inconsistent behavior.

#### Observations:
- The issue was investigated using Chrome DevTools' Network tab to monitor network activity.
- In some cases, the desired response was not displayed in the Network tab despite being expected.
- Exporting a `.har` file from the Network tab revealed that the response was indeed present, even though it was not detected by Puppeteer or shown in the Chrome DevTools Network tab.

### Expectation
I expected that response to get detected everytime.

### Reality
I receive a bunch of .blu files as a response but it's always the first file that doesn't get detected , sometimes it does, sometimes it doesn't

### Puppeteer version

`22.7.0`

### Node version

`20.12.2`

### Package manager

npm

### Package manager version

`10.2.4`

### Operating system

Windows

**Comment by OrKoN** [comment]
Please include a test page into the example.

**Comment by fe2-Nyxar** [comment]
I just added more code for a better understanding of the issue and changed the Reality paragraph, and I didn't include the URL cause it requires a login authentication

**Comment by OrKoN** [comment]
Please create a test page that shows the problem. Without it there is no way to debug the issue.

**Comment by OrKoN** [comment]
```
await page.goto("SomeUrl");

await getTheAudio(page);
```

the way this is written it looks like a race condition since all requests can already fire by the time getTheAudio is called. So without an executable example it is not possible to debug.

**Comment by fe2-Nyxar** [comment]
Idk what else I should provide cause I'm not that smart :), and the reason I didn't provide more code is gonna dissect you from the issue, so I tried to keep it minimal as much as possible, and for the URL It requires a login, cause it's a school site, I hope that cleared why I couldn't share any more details,  and sorry for the inconvenience

**Comment by fe2-Nyxar** [comment]
since I'm Stupid I asked chatgpt to generate a test: 


```Javascript
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Puppeteer Audio Response Test Page</title>
</head>
<body>
    <h1>Puppeteer Audio Response Test Page</h1>
    <button id="trigger-response">Trigger Audio Response</button>

    <script>
        document.getElementById('trigger-response').addEventListener('click', async () => {
            // Simulate fetching an audio response
            const response = await fetch('/fake-audio-response');

            // Simulate processing the response
            if (response.ok) {
                // Simulate extracting the audio data
                const audioBlob = await response.blob();
                // Simulate playing the audio
                const audioUrl = URL.createObjectURL(audioBlob);
                const audioElement = new Audio(audioUrl);
                audioElement.play();
            } else {
                console.error('Failed to fetch audio response');
            }
        });
    </script>
</body>
</html>
 ```
