### ISSUE TITLE
[Typo] Docs have a misspelling in arhicture

### ISSUE THREAD

**Issue by stevenfollis** [puppeteer/puppeteer#12416]
Small nit on the docs at [https://github.com/puppeteer/puppeteer/blob/main/docs/guides/system-requirements.md](https://github.com/puppeteer/puppeteer/blob/main/docs/guides/system-requirements.md)

> Debian/Ubuntu Linux, with x64 **arhicture**

**Comment by OrKoN** [comment]
Thanks for the PR!
