### ISSUE TITLE
[Bug]: Pages within the electron project cannot be connected

### ISSUE THREAD

**Issue by alaAicy** [puppeteer/puppeteer#12418]
### Minimal, reproducible example

```TypeScript
npm i puppeteer@6.0.0
```

### Error string

 throw new Error();

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I have an electron project using chrome89.0.4389.114 version

### Expectation

The puppeteer version corresponding to chrome89 can be installed

### Reality

npm WARN deprecated puppeteer@6.0.0: < 21.9.0 is no longer supported
npm ERR! code 1
npm ERR! path /Users/ala/myProject/tryp/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  sudo apt install chromium
npm ERR! 
npm ERR! 
npm ERR!  sudo apt install chromium-browser
npm ERR! 
npm ERR! /Users/ala/myProject/tryp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115
npm ERR!                     throw new Error();
npm ERR!                     ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/ala/myProject/tryp/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115:27
npm ERR!     at FSReqCallback.oncomplete (node:fs:198:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ala/.npm/_logs/2024-05-09T06_27_14_887Z-debug-0.log

Same phenomenon in windows

### Puppeteer version

6.0.0

### Node version

16.14.2

### Package manager

npm

### Package manager version

8.5.0

### Operating system

macOS

**Comment by OrKoN** [comment]
`npm i puppeteer@6.0.0` works for me on Mac arm64 so I am not able to reproduce. Note that old versions are deprecated and are no longer supported.

**Comment by alaAicy** [comment]
> `npm i puppeteer@6.0.0` works for me on Mac arm64 so I am not able to reproduce. Note that old versions are deprecated and are no longer supported.

So what are the ways I can connect to 89.0.4389.114 of chrome using puppeteer?

**Comment by OrKoN** [comment]
Consider asking a question on StackOverflow to how to solve the problem you are seeing. Also, try using the puppeteer-core package with 6.0.0 if you only need to connect to electron. In general, old versions are not supported.

**Comment by alaAicy** [comment]
> 此问题有一个不受支持的 Node.js 版本：`16.14.2`。仅`>=18`支持满足要求的版本。请在受支持的 Node.js 版本上验证问题并更新表单。
> 
> [分析仪运行](https://github.com/puppeteer/puppeteer/actions/runs/9013590473)
<img width="894" alt="image" src="https://github.com/puppeteer/puppeteer/assets/52344565/b9b13aeb-bef1-4980-956a-ab95af2f8fa6">
I upgraded the node version to 20.13.0 and it didn't install either

**Comment by OrKoN** [comment]
@alaAicy the error seems to indicate that there is no binary for arm64 (correction: I was actually testing on a intel mac). Back then arm64 was not supported and there were no builds for arm64. Do you even need the chromium binary? You can use `npm i puppeteer-core@6.0.0` or skip the download `npm i puppeteer@6.0.0 --ignore-scripts`

**Comment by alaAicy** [comment]
> intel mac

Okay, thank you.

**Comment by alaAicy** [comment]
> @alaAicy the error seems to indicate that there is no binary for arm64 (correction: I was actually testing on a intel mac). Back then arm64 was not supported and there were no builds for arm64. Do you even need the chromium binary? You can use `npm i puppeteer-core@6.0.0` or skip the download `npm i puppeteer@6.0.0 --ignore-scripts`

Hi，When I connected to electron using puppeteer version 6.0.0, I got an error using browser.newPage()
<img width="1006" alt="image" src="https://github.com/puppeteer/puppeteer/assets/52344565/bc4aa2e8-3101-4549-9d53-9998501490d8">
