### ISSUE TITLE
HTTPRequest is checking for chrome-only error message "Invalid header" 

### ISSUE THREAD

**Issue by juliandescottes** [puppeteer/puppeteer#12412]
Puppeteer expects that errors about headers will contain the message "Invalid header", both in the implementation and in tests:

https://github.com/puppeteer/puppeteer/blob/7712dffffef49282889ec99c1f0a066b826c2988/packages/puppeteer-core/src/api/HTTPRequest.ts#L705-L713

https://github.com/puppeteer/puppeteer/blob/7712dffffef49282889ec99c1f0a066b826c2988/test/src/requestinterception.spec.ts#L763

We should find another way to handle this in a cross browser manner. Maybe we should settle on a dedicated error on the bidi side if that's helpful (see https://github.com/w3c/webdriver-bidi/issues/707)

**Comment by OrKoN** [comment]
@juliandescottes is there a current message that Firefox produces that we could use short-term?

**Comment by juliandescottes** [comment]
@OrKoN I am currently implementing the support for the `headers` argument, but this hasn't landed yet. I don't know yet if we will wait for https://github.com/w3c/webdriver-bidi/issues/707 or if we will use something else in the meantime. I will let you know once it's available (I will probably send a PR here as well)

**Comment by Lightning00Blade** [comment]
Closed by #12483
