### ISSUE TITLE
Proposal (RCF) Refactor test file to separate file

### ISSUE THREAD

**Issue by sukrosono** [puppeteer/puppeteer#1241]
![image](https://user-images.githubusercontent.com/3001652/32264507-9741eef6-bf11-11e7-9317-df6fb16b90c0.png)

Due to length of test file (3100 lines this time), it cause some developer like me. having hard time when working on test. My editor become unresponsive sometimes.

restructure of new test file according the api, 
```
Browser.spec.js
Page.spec.js
Keyboard.spec.js
```

When approved i suggesting we use eslint [max-lines](https://eslint.org/docs/rules/max-lines) to give warning when the lines above certain number.

**Comment by aslushnikov** [comment]
@brutalcrozt Out of curiosity, what's your editor? We have `docs/api.md` that is even longer - how do you edit it?

**Comment by sukrosono** [comment]
@aslushnikov Atom, but i always multitask. :headphones:  from youtube + atom + documentation </> + :file_folder: . It happen after 5 minutes editing the **test.js**, i am not staying long open **docs/api.md**. Also my laptop just old and low spec, it's already 6 years with me.

**Comment by aslushnikov** [comment]
> Due to length of test file (3100 lines this time), it cause some developer like me. having hard time when working on test. My editor become unresponsive sometimes.

Indeed, some of our files are long'ish. We might have to split them eventually, but I'd like to postpone this moment until it's absolutely necessary:
- `test.js` is good enough for the project needs ATM 
- `api.md` is easily searchable with browser's "find in page"

Would you mind trying other editors to see if they work better for you? 
Some nice code editors are:
- [Sublime Text](https://www.sublimetext.com/) is an exceptional piece of software and is available on all major platforms
- [vim](http://www.vim.org/) works smoothly for me on both Mac OS and Linux
- [vscode](https://code.visualstudio.com/) works across all major platforms

I'll close this issue for now, but please let me know how it goes.
