### ISSUE TITLE
[Feature]: Track the originator of http request

### ISSUE THREAD

**Issue by Fly-Playgroud** [puppeteer/puppeteer#12422]
### Feature description

Is there any way to let me know that a certain or several http traffic is triggered by clicking on which element in the page?
I want to know the element that initiates these http traffic

**Comment by OrKoN** [comment]
See https://pptr.dev/api/puppeteer.httprequest.initiator/ which returns the information about the initiator of the request. Note that elements are not initiators of requests so it is not possible to associate a request with a DOM element. Also, see https://github.com/puppeteer/puppeteer/issues/12331
