### ISSUE TITLE
[Bug]: Puppeteer Cache Folder Not Reinstalling in ~/.cache After Update and Reinstallation

### ISSUE THREAD

**Issue by AI-Dev-Lex-Kim** [puppeteer/puppeteer#12424]
### Steps to reproduce

Delete the puppeteer folder in ~/.cache to switch to the latest browser version.
Run npm uninstall puppeteer and then npm install puppeteer to reinstall the expected browser version.

### Expected results

The puppeteer folder should be recreated in ~/.cache after reinstalling puppeteer.

### Actual results

The puppeteer folder is not being created in ~/.cache after the reinstallation process.

**Comment by OrKoN** [comment]
Does it work if you run `npx puppeteer browsers install chrome`?

**Comment by OrKoN** [comment]
```
rm -rf ~/.cache/puppeteer
npm uninstall puppeteer
npm install puppeteer
ls ~/.cache/puppeteer
mac-124.0.6367.91
```

Not reproducible for me.
