### ISSUE TITLE
Inject js into chrome extension

### ISSUE THREAD

**Issue by bambinorest1** [puppeteer/puppeteer#12435]
When a target is created(browser.on('targetcreated') it is assigned the type other. So how to inject js into popup page chrome extension? I know there is a way to create page and follow url chrome-extension://..., but i need inject to popup

**Comment by OrKoN** [comment]
See examples for opening a popup page here https://pptr.dev/guides/chrome-extensions

**Comment by bambinorest1** [comment]
> See examples for opening a popup page here https://pptr.dev/guides/chrome-extensions

I guess that's not exactly what i need. chrome.action.openPopup() is unavailable for me(missing from stable channel). Whatever i don't need manually open extension, i just need inject script when popup is opening by user

**Comment by OrKoN** [comment]
> chrome.action.openPopup() is unavailable for me(missing from stable channel).

It should be available in the bundled Chrome for Testing version.

You should still be able to do the following to wait for the popup target and execute code:

```
const popupTarget = await browser.waitForTarget(
  // Assumes that there is only one page with the URL ending with popup.html and that is the popup created by the extension.
  target => target.type() === 'page' && target.url().endsWith('popup.html')
);
```

Although I am not sure what use case would require injecting code when the user is opening the popup.
