### ISSUE TITLE
[Bug]: Protocol error (DOMDebugger.getEventListeners): Invalid parameters Failed to deserialize params.objectId

### ISSUE THREAD

**Issue by firdous-qasolve** [puppeteer/puppeteer#12434]
### Minimal, reproducible example

```TypeScript
async function getEventListeners(selector, page){
  try{
      if(!client){
        client = await page.target().createCDPSession();
      }
      const {result} = await client.send('Runtime.evaluate', {expression:`document.querySelector("${selector}")`, objectGroup:'handler'});
      const {listeners} = await client.send('DOMDebugger.getEventListeners', {objectId:result.objectId});
      await client.send('Runtime.releaseObjectGroup', {objectGroup:'handler'});
      return listeners.map(listener => listener.type);
  }catch(err){
      logger.error("Error occurred in getEventListeners "+ err);
      return [];
  }
}
```

### Error string

Protocol error (DOMDebugger.getEventListeners): Invalid parameters Failed to deserialize params.objectId - BINDINGS: mandatory field missing at position 8

### Bug behavior

- [x] Flaky
- [ ] PDF

### Background

I am trying to call this function on multiple elements in a document. And it starts throwing error sometimes. 

### Expectation

Please help me with this error, how can we fix it.?

### Reality

It works most of the time, but only fails on few web pages.

### Puppeteer version

19.7.0

### Node version

16.20.1

### Package manager

npm

### Package manager version

8.11.0

### Operating system

Windows

**Comment by OrKoN** [comment]
This is not an issue with Puppeteer since you call CDP directly. The error indicates that objectId is undefined.
