### ISSUE TITLE
Add page bringToFront method

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1244]
We need to add `bringToFront` method to page. Why it doesn't exist in puppeteer?
I can create PR, but I'm not really sure about comment and docs. Is docs auto generated or not?

```js
  /**
   * @return {!Promise<?Response>}
   */
  async bringToFront() {
    await this._client.send('Page.bringToFront');
  }
```

**Comment by aslushnikov** [comment]
> We need to add bringToFront method to page. Why it doesn't exist in puppeteer?

@schelkun there's been no need to. Can you please share your user scenario?

**Comment by satanch** [comment]
@aslushnikov for example, I will open 3 pages (tabs), how can I activate second or first tab?
By using `Page.bringToFront`. It's working for me. Any other way to do tihs?

**Comment by schelkun** [comment]
@aslushnikov for example, I will open 3 pages (tabs), how can I activate second or first tab?
By using `Page.bringToFront`. It's working for me. Any other way to do this?

**Comment by aslushnikov** [comment]
>  for example, I will open 3 pages (tabs), how can I activate second or first tab?

@schelkun that's a good scenario :)

> I can create PR, but I'm not really sure about comment and docs. Is docs auto generated or not?

- Doc is not autogenerated, but  linted
- Comments are [closure annotations](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler).

I'll be happy to review the pr that adds `page.bringToFront` method. Please, make sure to read [CONTRIBUTING.md](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md) if not yet - it has a lot of useful information.
