### ISSUE TITLE
[Bug]: userDataDir do not work

### ISSUE THREAD

**Issue by sunjunqiang1** [puppeteer/puppeteer#12449]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--lang=zh-CN'],
    ignoreDefaultArgs: [
      '--enable-automation'
    ],
    ignoreHTTPSErrors: false,
    // headless: true,
    headless: false,
    timeout: 0,
    protocolTimeout: 0,
    userDataDir: 'userData',
    executablePath: 'C:/Users/sun/Desktop/self/test/puppeteer/chrome-win/chrome-win/chrome.exe'
  });
})()
```

### Error string

none

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

The effect I expected is that after I log in to a certain website, I won't need to log in again when I restart the server or migrate as long as I bring along the 'userData' directory. However, my wish has not been fulfilled.

### Reality

none

### Puppeteer version

^22.8.2

### Node version

18.17.0

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by sunjunqiang1** [comment]
it is my directory
![企业微信截图_17158508591631](https://github.com/puppeteer/puppeteer/assets/49675311/8f95353b-5923-47a8-a95c-d4a69533e91e)

**Comment by OrKoN** [comment]
It looks the userDataDir is set correctly by Puppeteer. Please report an issue to https://crbug.com/new if there is a problem with how Chrome uses the dir
