### ISSUE TITLE
browser.close() didn't close browser

### ISSUE THREAD

**Issue by bartmanskyi** [puppeteer/puppeteer#1245]
browser.close() didn't close browser

```
(async () => {
    let browser = await puppeteer.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        slowMo: 0,
        userDataDir: './chromeuserdata',
        ignoreHTTPSErrors: true,
        headless: true
    });
    let page = await browser.newPage();
    await page.close();
    await browser.close();
})()

```
windows 10
puppeteer 0.12.0

![cant close](https://user-images.githubusercontent.com/12626657/32284910-666bcad4-bf31-11e7-9bad-64fb555f7592.png)

**Comment by aslushnikov** [comment]
@bartmanskyi I see you're using `userDataDir`. We've fixed this in https://github.com/GoogleChrome/puppeteer/commit/ab9b34cd5dad54e170be916016a4e9b4097231ed. Can you please try installing puppeteer from tip of tree and see if it's working for you?

There's also #1047 that might be relevant.

**Comment by bartmanskyi** [comment]
Doesn't work for me. Perhaps I need to downgrade to 0.11.0
doesn't work - v 0.12.0 with headless:true and enabled userDataDir;
works fine - v 0.12.0 with headless:false; (why?)
works fine - v 0.12.0 with disabled userDataDir; 
works fine - v 0.11.0 with headless:true and enabled userDataDir;

**Comment by aslushnikov** [comment]
> Doesn't work for me.

@bartmanskyi I don't see v0.13.0-alpha in the list of revisions you tried. Let me clarify: did you try installing puppeteer from github (so that you can get the un-published version) and run your test against it?

**Comment by bartmanskyi** [comment]
v0.13.0-alpha works, thanks

**Comment by aslushnikov** [comment]
Awesome.

**Comment by ArupKumarBehera** [comment]
I am facing this same issue in 1.12.1, if I set userDataDir. Any help please ?

**Comment by ghost** [comment]
I am facing this same issue in 1.12.1, if I set userDataDir too. Any help please ?

**Comment by LeonidEfremov** [comment]
Same issue =(

**Comment by viponedream** [comment]
Same issue =(
How to fix?

**Comment by gianmassa** [comment]
Same issue here

**Comment by Nemester** [comment]
still facing this issue (version 2.1.1)

**Comment by zNoobs** [comment]
Same issue with v1.11.0, without using userDataDir.
I'm using it with electronjs (v4.2.12), electron-builder v20.39.0, when the app is not packaged it works well (the browser closes), when it's packaged the browser doesn't close.

**Comment by mewtlu** [comment]
Still facing this issue using Puppeteer 3.0.1 with `--user-data-dir`, any chance of an update on it?

**Comment by zNoobs** [comment]
I'm doing like this to be sure to close the browser:
```
let pages = await this.browser.pages();
for (const page of pages) {
	await page.close();
}
await this.browser.close();
```

**Comment by mewtlu** [comment]
Ah interesting, does it seem like the browser is refusing to close when
there are tabs open?

**Comment by voxsoftware** [comment]
5.5.0 and still an issue. Testing on linux. I think occurs in headless mode

**Comment by gcubeda** [comment]
using 5.5.0 on linux in non headless mode, having same issue

**Comment by xtepwxly** [comment]
I also confirm that with version 5.5.0 it happens on Windows 10 with headless mode.
Commenting out `--user-data-dir` solves the issue.

**Comment by gcubeda** [comment]
one of the zombies was for me a background_page not being closed (browser extension) but I solved completely by using `dumb-init`/`tini`.
Watch out that with `dumb-init` when the container receives a `SIGTERM` the browser is closed even if you set the `handleSIGTERM: false` flag (so you won't be able to perform a graceful shutdown) while `tini` does keep it alive

**Comment by truongdinhthien** [comment]
```
  const pages = await browserInstance.pages();
  await Promise.all(pages.map((page) => page.close()));
  await browserInstance.close();
```
