### ISSUE TITLE
[Feature]: create a puppeteer-lite package

### ISSUE THREAD

**Issue by casesolved-co-uk** [puppeteer/puppeteer#12460]
### Feature description

When using puppeteer, both a `chrome` and `chrome-headless-shell` browser are downloaded which take up 356MB and 189MB respectively, i.e. more than 0.5GB of space.

It would be brilliant for headless applications to have a puppeteer-lite package that only includes `chrome-headless-shell`.

If there is a simple way to do this in yarn by including `puppeteer-core` and some other command I would be interested to hear.

Related:
https://github.com/puppeteer/puppeteer/issues/10736
https://developer.chrome.com/blog/chrome-headless-shell

**Comment by OrKoN** [comment]
You can set the env var `PUPPETEER_SKIP_CHROME_DOWNLOAD` to true (or the config option skipChromeDownload) to only download the headless shell. For the opposite, there is a PUPPETEER_SKIP_CHROME_HEADLESS_SHELL_DOWNLOAD variable.

Alternatively, you can use puppeteer-core and @puppeteer/browsers to manage the browser downloads.
