### ISSUE TITLE
[Bug]: TimeoutError when printing a PDF using Chrome 125

### ISSUE THREAD

**Issue by sbj42** [puppeteer/puppeteer#12470]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

async function go() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent('Hello');
    await page.pdf();
    await browser.close();
    console.info('ok');
}

go().catch(console.error);
```

### Error string

Timed out after waiting 30000ms

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm generating HTML and using Puppeteer to convert that into a PDF.  This worked before, but stopped working at some point - now it throws a TimeoutError.  I discovered that the problem occurs with chrome version win64-125.0.6422.60, but does not occur with version win64-121.0.6167.85.

If you modify my test program to set `executablePath` to `chrome.exe` 121, it succeeds and prints ok.

I believe this is the same issue as #12467, but this example is much simpler.

### Expectation

The chrome process exits quickly, `await page.pdf()` returns, the script prints "ok", and node exits.

### Reality

`await page.pdf()` throws `TimeoutError` after 30 seconds.  The error is printed to the console, but chrome and node keep running and never exit.

### Puppeteer version

22.9.0

### Node version

18.15.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by sbj42** [comment]
The issue was not reproducible because of a timeout.  In this test case, node never exits (which is a consequence of the issue), and so the analyzer times out with `Error: The action 'Verify issue' has timed out after 10 minutes.`

**Comment by OrKoN** [comment]
I believe it is this issue https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows Note that the behavior has changed in Chromium in M125 and printing requires a sandbox permissions now. We currently cannot set them up automatically in a secure manner. Also see https://g-issues.chromium.org/issues/338553158

**Comment by sbj42** [comment]
Understood.  To sum up what I see:
* `page.pdf()` will hang indefinitely when using ["Chrome for Testing"](https://developer.chrome.com/blog/chrome-for-testing/) 125+ (which puppeteer installs by default)
* Unless you (a) workaround the issue by changing the permissions of your `.cache/puppeteer/chrome` folder [instructions here](https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows) (note: this workaround is not a good idea for "production" environments!)
* Or (b) point `executablePath` to an earlier Chrome, or a not-for-testing Chrome (i.e. installed using a regular Chrome installer, which sets the permissions in a better way)
* There is an [ongoing discussion](https://issues.chromium.org/issues/338553158) about an improvement to Chrome for Testing, which if implemented could fix the issue

**Comment by Tredoxx** [comment]
> Understood. To sum up what I see:
> 
> * `page.pdf()` will hang indefinitely when using ["Chrome for Testing"](https://developer.chrome.com/blog/chrome-for-testing/) 125+ (which puppeteer installs by default)
> * Unless you (a) workaround the issue by changing the permissions of your `.cache/puppeteer/chrome` folder [instructions here](https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows) (note: this workaround is not a good idea for "production" environments!)
> * Or (b) point `executablePath` to an earlier Chrome, or a not-for-testing Chrome (i.e. installed using a regular Chrome installer, which sets the permissions in a better way)
> * There is an [ongoing discussion](https://issues.chromium.org/issues/338553158) about an improvement to Chrome for Testing, which if implemented could fix the issue

You can also downgrade to 22.6.2, while the problem is fixed

**Comment by richi84** [comment]
I was running into the same issue. For me it was working just setting the '--no-sandbox' flag when lauching the browser. 

    const browser = await puppeteer.launch({
      args: ['--no-sandbox']
    });

I have no clue why. May it could be a permission issue...
