### ISSUE TITLE
How to use XPath to find elements in latest puppeteer-core？

### ISSUE THREAD

**Issue by StrugglingAndroid** [puppeteer/puppeteer#12480]
How to use XPath to find elements in latest puppeteer-core？page.$x is not a function，page.waitForXPath is not a function。

Code below reports timeout error：

```
await page.waitForSelector(`//*[contains(text(), 'XXXXXX')]`);
```

**Comment by OrKoN** [comment]
See https://pptr.dev/guides/page-interactions#built-in-selectors for examples (i.e., prefix the xpath expression with `xpath/`)

**Comment by kelvinwop** [comment]
the provided examples dont work lol

await page.click("::-p-xpath(//h2)");

Encountered error: DOMException: SyntaxError: Failed to execute 'evaluate' on 'Document': The string '' is not a valid XPath expression.
