### ISSUE TITLE
[Bug]: libdrm.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by amehmood-pls** [puppeteer/puppeteer#12481]
### Steps to reproduce

 puppeteer.launch({ headless: true }); is not working on Amazon Linux 2023.

### Expected results

The same NodeJS code is working on Ubuntu 20.04.6 LTS, however facing the issue with Amazon Linux 2023 (al2023). 

### Actual results

 puppeteer.launch({ headless: true }); is not working and failing with the following error:
puppeteer/chrome/linux-125.0.6422.60/chrome-linux64/chrome: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory

**Comment by OrKoN** [comment]
Please see https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux and install missing dependencies (libdrm2).
