### ISSUE TITLE
page.goto(url) cannot downlad the PDF file. 

### ISSUE THREAD

**Issue by UCSBGauchos** [puppeteer/puppeteer#1248]
I need to crawler the web and download the PDF files. However when the link is a PDF file, the page.goto(url) can only render the PDF. It cannot download it. Is there any configuration to enable it?

**Comment by vsemozhetbyt** [comment]
I am not sure, but you can try this:
```js
const response = await page.goto(pdfURL);
fs.writeFileSync(pdfPath, await response.buffer());
```

**Comment by sukrosono** [comment]
I am not sure on what circumstance, but it's the behavior of chrome itself.

**Comment by ebidel** [comment]
Headless doesn't support navigating to a PDF. 

There's a note at the end of https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options.

**Comment by vsemozhetbyt** [comment]
@ebidel It seems @UCSBGauchos means headful mode:

> the `page.goto(url)` can only **render** the PDF. It cannot download it.

**Comment by vsemozhetbyt** [comment]
Maybe this is like some feature request: implement what "Save link as..." context menu item does.

**Comment by aslushnikov** [comment]
With #1191 you'll be able to add a content-disposition header for the responses marked as "pdf". This should result in a pdf being downloaded.

**Comment by UCSBGauchos** [comment]
@aslushnikov Not sure how to do it in the code. Can you give me an example?

**Comment by UCSBGauchos** [comment]
@vsemozhetbyt yes

**Comment by aslushnikov** [comment]
@UCSBGauchos the #1191 is not implemented yet, but it would look something like:

```js
page.setResponseInterception(true);
page.on('response', response => {
  const headers = response.headers;
  if (response.url.endsWith('.pdf'))
    headers['Content-Disposition'] = 'attachment';
  response.continue({headers});
});
```

**Comment by kazaff** [comment]
@aslushnikov  When I ran the code, `page.setResponseInterception` was not be found.

And when `headless` to be set true, maybe the file haven't been download. can you help me to resolve it?

**Comment by gnat42** [comment]
As a workaround I've set puppeteer userDataDir, and then set the chrome profile to download PDFs in the settings. The downside is that navigating to a URL with a PDF causes an error.

```
(node:14662) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/home/gnat/Projects/Web/spin2client/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>
(node:14662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14662) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I really wish this was easier/more programmable.

**Comment by avimar** [comment]
@gnat42 where do I set chrome profile to download PDFs instead of opening them?

**Comment by gnat42** [comment]
@avimar I don't think it actually worked well in the end. I can't remember how I did this, but look at specifying a specific profile. Sorry for the lack of detail, however in the end it didn't work because Chrome itself doesn't support it via headless mode.

**Comment by jlf5655** [comment]
I know that I cannot navigate to a pdf page in headless mode. Does `page.goto()` receive a response from a pdf page and then reject the navigation or does it simply filter out any url with `'.pdf'` at the end?
