### ISSUE TITLE
[Bug]: Docker errors

### ISSUE THREAD

**Issue by kirka-dev** [puppeteer/puppeteer#12492]
### Minimal, reproducible example

```TypeScript
### LAUNCH
const browser = await puppeteer.launch({
  headless: false,
  ignoreHTTPSErrors: true,
  defaultViewport: {
    width: 1280,
    height: 720,
  },
  args: ['--no-sandbox'],
});

### DOCKERFILE
FROM --platform=linux/amd64 node:18

RUN apt-get update
RUN apt-get install -y wget gnupg
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update
RUN apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/api

COPY . .

RUN yarn install

RUN yarn build

EXPOSE 3000
CMD [ "yarn", "start:prod" ]
```

### Error string

Error: Failed to launch the browser process! undefined 2024-05-26T13:38:10.862690680Z [40:56:0526/133810.819672:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory 2024-05-26T13:38:10.862691639Z [40:40:0526/133810.821658:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY 2024-05-26T13:38:10.862692389Z [40:40:0526/133810.821671:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Solution Docker + puppeteer 

### Reality

`Error: Failed to launch the browser process! undefined
2024-05-26T13:38:10.862690680Z [40:56:0526/133810.819672:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2024-05-26T13:38:10.862691639Z [40:40:0526/133810.821658:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
2024-05-26T13:38:10.862692389Z [40:40:0526/133810.821671:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.`

### Puppeteer version

22.10.0

### Node version

v18.20.3

### Package manager

yarn

### Package manager version

1.22.18

### Operating system

Linux

**Comment by OrKoN** [comment]
If you want to run headful browser in Docker, you need to configure the display or use Xvfb. I am not sure you need headful in Docker anyway, so I recommend trying to use the headless: true or headless: 'shell' flag.
