### ISSUE TITLE
hash route change can't emit Page.lifecycleEvent event in SPA 

### ISSUE THREAD

**Issue by CommanderXL** [puppeteer/puppeteer#1249]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0-alpha
* Platform / OS version: mac os
* URLs (if applicable):

**What steps will reproduce the problem?**

Well, In the source code of the [waitForNavigation](https://github.com/GoogleChrome/puppeteer/blob/master/lib/NavigatorWatcher.js#L47-L78) method. When the client send `Page.navigateToHistoryEntry` event, the browser will go back or forward, and the browser will emit the event of `Page.lifecycleEvent`.

However, In SPAs.I jump the page through hash change as the router.But the browser can't emit `Page.lifecycleEvent`.

So in the method of waitForNavigation: 
```javascript
 async waitForNavigation(entry) {
    this._eventListeners = [];

    const navigationPromises = [];
    if (this._timeout) {
      const watchdog = new Promise(fulfill => this._maximumTimer = setTimeout(fulfill, this._timeout))
          .then(() => 'Navigation Timeout Exceeded: ' + this._timeout + 'ms exceeded');
      navigationPromises.push(watchdog);
    }

    this._eventListeners.push(helper.addEventListener(this._client, 'Page.lifecycleEvent', this._onLifecycleEvent.bind(this)));

    //  This promise will be never resolved. So in the promise.race, the watchdog will resolve before this promise

    const pendingEventsFired = new Promise(fulfill => this._pendingEventsCallback = fulfill);
    navigationPromises.push(pendingEventsFired);

    const error = await Promise.race(navigationPromises);
    this._cleanup();
    return error ? new Error(error) : null;
  }

  /**
   * @param {!{frameId: string, name: string}} event
   */
  _onLifecycleEvent(event) {
    if (event.frameId !== this._frameId)
      return;
    const pptrName = protocolLifecycleToPuppeteer[event.name];
    if (!pptrName)
      return;
    this._pendingEvents.delete(pptrName);
    if (this._pendingEvents.size === 0)
      this._pendingEventsCallback();
  }
```

**What is the expected result?**

`Page.lifecycleEvent` event will emit in the SPA when the hash route hash changed.

**What happens instead?**

`Page.lifecycleEvent` never emit in the SPA when the hash route hash changed.

------

Well, I haven't found some event about hash change in the devtools-protocol page. Or is there any idea to solve the situation above?

**Comment by aslushnikov** [comment]
Hi @CommanderXL,

Lifecycle events are sent for the document lifecycle; anchor navigation doesn't affect the document per se. Protocol doesn't expose anything related to the anchor navigation for now.

There's #257 to track progress of battling anchor navigations. Please, upvote!
