### ISSUE TITLE
Errors when accepting several dialogs followed in the same web page

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1250]
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
    for (var i = 0; i < myArray; i++) {
    	await page.click('myArray[i]')  //My array contains several links and each link shows me a warning alert that I want to ignore
	     page.on('dialog', async dialog => {

	     	await dialog.dismiss();	    
	                           
	     });
    }

  await browser.close();
})();
```

> The dialog event, it increases as an array and it is when I throw errors, what could I do? Is it possible to delete the dialog object or reinitialize it when await dialog.dismiss () ;?

(node:10276) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): AssertionError [ERR_ASSERTION]: Cannot dismiss dialog which is already handled!

**Comment by aslushnikov** [comment]
@fran0254 you should move `page.on('dialog')` line out from the loop. Otherwise you end up with dozens of listeners, each trying to dismiss the same dialog.

**Comment by fran0254** [comment]
Ok, and is it possible to check if there is a dialog or not before loading the event?

**Comment by aslushnikov** [comment]
@fran0254 no, you need to subscribe to the event and track the state of the dialog

**Comment by fran0254** [comment]
I've put the call to the event outside the loop but I'm not doing it right, if you can help me. Thank you
```javascript
const puppeteer = require('puppeteer');

(async () => {
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
        await page.goto('https://example.com');
            page.on('dialog', async dialog => {
                 console.log('Load dialog...');                    
         });

              for (var i = 0; i < myArray; i++) {
                
                  await page.click('myArray[i]')  
                  await dialog.dismiss();  
                 }
          // if  alert or dialog I accept or ignore   
          //there are times when dialogue exists and others do not
           

      await browser.close();
})();
```

**OUT ERROR ..**

(node:29793) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: **dialog is not defined**
(node:29793) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment]
@fran0254 the following works just fine for me:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Dismiss every dialog on a page
  page.on('dialog', dialog => {
    console.log('Dismissing a dialog.');
    dialog.dismiss();
  });

  // Navigate and do any clicking
  await page.goto('https://example.com');
  await page.click('selector-1');
  await page.click('selector-2');

  // ...

  await page.close();
  await browser.close();
})();
```

**Comment by stephenjesus** [comment]
I want to return dialog.message(); 

based on the message I want to return the response

**Comment by vAugagneur** [comment]
hi @stephenjesus did you find a solution ?

**Comment by stephenjesus** [comment]
@vAugagneur  yes I found the solution

Create a separate async function and 

Use promise to resolve message
