### ISSUE TITLE
[Bug]: image is cutting during screenshot

### ISSUE THREAD

**Issue by diegoalmada** [puppeteer/puppeteer#12528]
### Minimal, reproducible example

```TypeScript
import chromium from '@sparticuz/chromium';
import puppeteer, { Browser } from 'puppeteer-core';
#puppeteer lauch:
...
  chromium.setGraphicsMode = false;
  return puppeteer.launch({
    args: chromium.args,
    defaultViewport: { ...chromium.defaultViewport, deviceScaleFactor: 2 },
    executablePath: await chromium.executablePath(),
    headless: true,
  });
...
...
//load the elements to html
 const barCodeGeneratorScript = path.resolve(
    'src/public/js/JsBarcode.code128.min.js',
  );
  await page.addScriptTag({ path: barCodeGeneratorScript });

  const qrCodeGeneratorScript = path.resolve('src/public/js/bwip.js');
  await page.addScriptTag({ path: qrCodeGeneratorScript });

  await page.setContent(getTagHtml(order), {
    waitUntil: 'load',
  });

  const tagStyle = path.resolve('src/public/css/style.css');
  await page.addStyleTag({ path: tagStyle });



await page.$(`.tag-volume-${volumeIndex}`);

(await tagElement.screenshot({
    type: 'jpeg',
  })) as Buffer;

```

### Error string

no error

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I'm generating an image with HTML after I'm trying to screenshot this image. But the screenshot is cutting after generation. It is happening sometimes. 

What does someone know happening in this situation ?
![Ok (2)](https://github.com/puppeteer/puppeteer/assets/704744/4d633f4a-3a05-4cde-bfbf-b36c832cdee9)
![error](https://github.com/puppeteer/puppeteer/assets/704744/ebbf4231-9d79-4c8b-ad82-40b2d60b4a86)

### Expectation

Screenshot does not cut in any situation

### Reality

-

### Puppeteer version

22.9.0

### Node version

18.16.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Please update the bug report with an executable example that we can run and try using the latest version using the bundled Chrome version.
