### ISSUE TITLE
try-puppeteer: require('puppeteer') not supported

### ISSUE THREAD

**Issue by ithinkihaveacat** [puppeteer/puppeteer#1253]
https://try-puppeteer.appspot.com/ explains that it's not necessary to `require('puppeteer')` when pasting code, but it turns out it's not allowed, either. This makes it (slightly!) more difficult to copy and paste code.

![screenshot from 2017-11-02 12 22 04](https://user-images.githubusercontent.com/51244/32325825-7c2152b2-bfc8-11e7-8ed9-66c05417aa38.png)

![screenshot from 2017-11-02 12 22 46](https://user-images.githubusercontent.com/51244/32325889-b0b52b8e-bfc8-11e7-9652-24019d9a9c35.png)

**Comment by ebidel** [comment]
This issue was moved to ebidel/try-puppeteer#8
