### ISSUE TITLE
try-puppeteer: (async() => { ... })() fails silently

### ISSUE THREAD

**Issue by ithinkihaveacat** [puppeteer/puppeteer#1254]
The following code (abbreviated version of a file from the `examples` folder) fails silently when entered in the editing component at https://try-puppeteer.appspot.com/:

```js
(async() => {
const browser = await puppeteer.launch();
console.log('Hello, World');
})();

```

Actual:

No output, no error message.

Expected:

The output `Hello, World!`.

**Comment by ebidel** [comment]
This issue was moved to ebidel/try-puppeteer#9
