### ISSUE TITLE
[Bug]:  Whenever puppeteer is started, chrome takes up a lot of memory

### ISSUE THREAD

**Issue by chenxicore** [puppeteer/puppeteer#12540]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
      headless: "new",
      devtools: false,
      timeout: 60000,
      ignoreHTTPSErrors: true,
      args: [
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--disable-web-security",
        "--disable-xss-auditor",r
        "--no-zygote",
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--allow-running-insecure-content",
        "--disable-webgl",
        "--disable-popup-blocking"
      ],
    });
    const page = await browser.newPage();
await Promise.all([
            page.goto(url, {
              waitUntil: [
                "domcontentloaded",
              ],
              timeout: 30000,
            }),
          ]);
```

### Error string

no

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

No matter which machine I boot on or at any time, the memory is 1132g

### Expectation

Memory is no longer so high

### Reality

![20240606-165237](https://github.com/puppeteer/puppeteer/assets/77398587/4a80d3b5-7b2f-4df3-bb0e-b34149cfd256)

### Puppeteer version

22.8.1

### Node version

v20.13.1

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Linux

**Comment by OrKoN** [comment]
I see that you have 8 GB memory in total and the top Chrome process uses 6.6% so about 528 megabytes which seems reasonable if there are some pages loaded. See https://serverfault.com/questions/138427/what-does-virtual-memory-size-in-top-mean If you believe memory usage is a bug with Chrome, please file a bug at crbug.com/new.

**Comment by chenxicore** [comment]
> 我发现您总共有 8 GB 内存，而顶级 Chrome 进程使用了​​ 6.6%，因此大约 528 兆字节，如果加载了一些页面，这似乎是合理的。请参阅https://serverfault.com/questions/138427/what-does-virtual-memory-size-in-top-mean如果您认为内存使用是 Chrome 的一个错误，请在 crbug.com/new 上提交错误。

What I want to say is that the virtual memory virt has always been 1132g. Is this reasonable?

**Comment by OrKoN** [comment]
@chenxicore sure, it is virtual, not the real memory as explained in the stackoverflow answer.
