### ISSUE TITLE
[Bug]: Chromium latest build seem to be broken on Mac with Intel processors

### ISSUE THREAD

**Issue by Manvel** [puppeteer/puppeteer#12553]
### Steps to reproduce

- Ensure you are on the Mac with Intel Processor (In my case I am on Mac with: `2.6 GHz 6-Core Intel Core i` processor)
- Run `npx @puppeteer/browsers install chromium`
- Try launching the Browser using puppeteer

### Expected results

Browser starts

### Actual results

```
Cause:
    spawn Unknown system error -86
```

**Comment by OrKoN** [comment]
```
file /Users/alex/projects/pptr-test/chromium/mac-1311951/chrome-mac/Chromium.app/Contents/MacOS/Chromium
/Users/alex/projects/pptr-test/chromium/mac-1311951/chrome-mac/Chromium.app/Contents/MacOS/Chromium: Mach-O 64-bit executable arm64
```

looks like the binary is actually for arm64

**Comment by OrKoN** [comment]
I don’t think that blog post meant this situation. https://chromium-review.googlesource.com/c/chromium/src/+/5608690 should fix it, looks like archive builder for x64 was reconfigured to arm64 by mistake.

**Comment by OrKoN** [comment]
looks like it has been fixed
