### ISSUE TITLE
try-puppeteer: `waitUntil: 'networkidle0'` not supported

### ISSUE THREAD

**Issue by ithinkihaveacat** [puppeteer/puppeteer#1255]
It looks like try-puppeteer isn't up-to-date to the latest puppeteer release.

To reproduce, go to https://try-puppeteer.appspot.com/ and enter the following code:

```js
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('https://example.com', { waitUntil: 'networkidle0' });

console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();
```

Actual:

Error message: `Error running your code. AssertionError [ERR_ASSERTION]: Unknown value for options.waitUntil: networkidle0`

Expected:

Screenshot appears.

**Comment by ebidel** [comment]
try-puppeteer is still running the latest stable release (0.12.0) which doesn't yet have `networkidle0`. That'll be available in the next release.
