### ISSUE TITLE
Screenshots do not show <video> element thumbnails

### ISSUE THREAD

**Issue by ithinkihaveacat** [puppeteer/puppeteer#1256]
The video controls appear, but not the thumbnail of the video itself.

To reproduce:

1. Go to `https://try-puppeteer.appspot.com/`. Select the "screenshot" example if not already selected.
2. Change the URL to  `https://awesome-ray.glitch.me/`.

(Can reproduce with local script as well, but easier to demonstrate on Try Puppeteer.)

Actual:

![5fa4bcf3-cadc-457b-bd20-b4833010d63f](https://user-images.githubusercontent.com/51244/32326779-fbef8a2e-bfcb-11e7-82de-b79850cd9ec6.png)

Expected:

![screenshot from 2017-11-02 12 48 26](https://user-images.githubusercontent.com/51244/32326827-28ee2e36-bfcc-11e7-828c-6a75f93d1985.png)

**Comment by aslushnikov** [comment]
@ithinkihaveacat the website changed the content and it looks there's no video any more.
I tried with https://www.youtube.com/watch?v=E8C8ouiXHHk and 0.13.0-alpha worked just fine.

**Comment by ithinkihaveacat** [comment]
Sorry, copy and pasted the wrong URL. Please try https://awesome-ray.glitch.me/. (Description also updated.)

**Comment by ithinkihaveacat** [comment]
Actually, even in "headed" mode (i.e. headless: false), the video doesn't appear. Is there anything different with headless mode regarding video?

The source code that fails:

```html
<video controls width="250">
  <source src="https://cdn.glitch.com/60b3de67-4600-42eb-bbf3-1acfab85e986%2FIMG_2221.mp4?1509624739927" type="video/mp4">
</video>
```

**Comment by aslushnikov** [comment]
@ithinkihaveacat ah, that's codecs. That's been discussed in https://github.com/GoogleChrome/puppeteer/issues/291
