### ISSUE TITLE
Discussion: provide stable access to chrome websocket

### ISSUE THREAD

**Issue by EliSnow** [puppeteer/puppeteer#1257]
Over in the chrome-debugging-client project, there is an [ongoing discussion](https://github.com/krisselden/chrome-debugging-client/issues/14) on whether the project should be discontinued in favor of Puppeteer. I think Puppeteer is great and provides a great deal of power but chrome-debugging-client really shines in providing direct access to the Chrome DevTools Protocol, with auto-generated TypeScript typings from the `protocol.json`.

With that discussion in mind, would it be possible for Puppeteer to provide direct, stable access to the underlying websocket so people can issue commands that may not be provided through Puppeteer's standard API? If that's possible, would it be possible to have some sort of auto-generated API (like chrome-debugging-client) that acts directly on top of the websocket, issuing CDP commands?

**Comment by ebidel** [comment]
Note, you can get the raw ws url from https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserwsendpoint. How you use that is up to you :)

There's also an [open issue](https://github.com/GoogleChrome/puppeteer/issues/31) to better expose the raw protocol for power users.

**Comment by EliSnow** [comment]
Wow! Well sorry for the noise then. @krisselden, is there anything you want to add?

**Comment by krisselden** [comment]
@ebidel you can not have multiple clients connected, it is the _connection I would like exposed so one can send/receive debugging protocol messages for API that hasn't received a nice high level wrapper.  If you connect to the websocket chrome disconnects other connections.

**Comment by ebidel** [comment]
As of Chrome 63, multi client is supported! https://developers.google.com/web/updates/2017/10/devtools-release-notes#multi-client

You should be able to use `puppeteer.connect()` to the same browser instance, also have devtools open, etc. It all just works :)
