### ISSUE TITLE
[Question]: Can we call start/stop recorder in Chrome-Devtools by puppeteer? And how to make it.

### ISSUE THREAD

**Issue by del-zhenwu** [puppeteer/puppeteer#12571]
### Feature description

Any suggestion?

**Comment by OrKoN** [comment]
Consider posting a question on StackOverflow instead, providing more details about the use case. The answer is you can probably connect to the DevTools window and click on the start/stop button. See tests for interacting with the DevTools window https://github.com/puppeteer/puppeteer/blob/defda0905fad97945012cd745fb7dbd5e171da2f/test/src/cdp/devtools.spec.ts#L12

**Comment by rublev** [comment]
would also love to know this
