### ISSUE TITLE
[Bug]: on Almalinux 8 (Namecheap) missing libatk-bridge-2.0.so.0 libdrm.so.2 libgbm.so.1libasound.so.2 even if they have been installed!

### ISSUE THREAD

**Issue by scalaxofaiur** [puppeteer/puppeteer#12576]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const getQuotes = async (url) => {
  const browser = await puppeteer.launch({
    headless: true,
    defaultViewport: null,
  });

  // Open a new page
  const page = await browser.newPage();

  // On this new page:
  await page.goto(url, {
    waitUntil: "networkidle2",
  });

  const content = await page.content();

  console.log(content);

  await browser.close();
};

// Start browsing
getQuotes("https://example.net");
```

### Error string

Error: Failed to launch the browser process! /home/XXXXXXXX/.cache/puppeteer/chrome/linux-125.0.6422.141/chrome-linux64/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I installed puppeteer on my Namecheap VPS with Almalinux 8, NodeJs v18.20.2

When i launch the script with

node test.msj

It says that libatk-bridge-2.0.so.0 is not installed.

If i run

ldd /home/XXXXXXXXX/puppeteer/chrome/linux-125.0.6422.141/chrome-linux64/chrome | grep not

Output is

        libatk-bridge-2.0.so.0 => not found
        libdrm.so.2 => not found
        libgbm.so.1 => not found
        libasound.so.2 => not found

However if i have installed this dependencies with

dnf install libatk-bridge-2.0.so.0
dnf install libdrm.so.2
dnf install libgbm.so.1
dnf install libasound.so.2

and if i run

find /usr -name libatk-bridge-2.0.so.0
find /usr -name libdrm.so.2
find /usr -name libgbm.so.1
find /usr -name libasound.so.2

output is correclty

/usr/lib/libatk-bridge-2.0.so.0
/usr/lib/libdrm.so.2
/usr/lib/libgbm.so.1
/usr/lib/libasound.so.2

What is going on?

### Expectation

Targeted page source code in output

### Reality

file:///home/XXXXXXXX/test/node_modules/@puppeteer/browsers/lib/esm/launch.js:301
                reject(new Error([
                       ^

Error: Failed to launch the browser process!
/home/XXXXXXXX/.cache/puppeteer/chrome/linux-125.0.6422.141/chrome-linux64/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (file:///home/XXXXXXXXX/test/node_modules/@puppeteer/browsers/lib/esm/launch.js:301:24)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.20.2

### Puppeteer version

22.11.0

### Node version

18.20.2

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
@scalaxofaiur would you mind filing this issue to https://crbug.com/new ? It definitely looks like a Chrome issue. From Puppeteer side, I can suggest using our container image https://pptr.dev/guides/docker

**Comment by ViniciusFXavier** [comment]
With these commands, you can set up and run the environment on any Linux distribution, including Ubuntu, CentOS, WSL (1, 2), and even [CodeSandbox](https://codesandbox.io/). Follow these steps:

1. **Update Package List and Apply Updates**  
   First, update the list of packages and apply the updates:  
   ```bash
   sudo apt update  
   sudo apt upgrade -y  
   ```  
   This ensures your system is up to date.  

2. **Install Dependencies for Chromium**  
   Install all necessary libraries and dependencies required to run Chromium:  
   ```bash
   sudo apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils  
   ```  
    Yes, there are several dependencies. :sweat:

3. **Handle DISPLAY Issues (if applicable)**  
   If you encounter issues related to the `DISPLAY` environment variable, run the following command to allow Linux GUI apps to connect:  
   ```bash  
   export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0  
   ```  

4. **Install Chromium if Not Found**  
   If Chromium is not installed or cannot be found, add the Chromium repository and install it:  
   ```bash  
   sudo add-apt-repository ppa:chromium-team/stable  
   sudo apt-get update  
   sudo apt install chromium-browser  
   ```
