### ISSUE TITLE
[Bug]: New XPath error on new latest v22.10.1

### ISSUE THREAD

**Issue by OmerWow** [puppeteer/puppeteer#12570]
### Minimal, reproducible example

```TypeScript
import puppeteer, { KnownDevices } from "puppeteer";
import type { Car } from "./types/car";

(async () => {
  const browser = await puppeteer.launch();
  const landingPage = await browser.newPage();

  await landingPage.emulate(KnownDevices["iPad Pro"]);
  await landingPage.goto("https://www.carzone.co.il/");

  const manufacturersURLs = await landingPage.$$eval(
    "a.css-1qs10se.e1aazib31",
    (els) => els.map((el) => el.href),
  );

  console.log(manufacturersURLs);

  const allCars = new Map<string, Car[]>();

  for (let i = 0; i < manufacturersURLs.length; i++) {
    const currentManufacturerURL = manufacturersURLs[i];
    const currentManufacturerName = currentManufacturerURL
      .split("https://www.carzone.co.il/")[1]
      .replace("/", "");

    const manufacturerPage = await browser.newPage();

    await manufacturerPage.emulate(KnownDevices["iPad Pro"]);
    await manufacturerPage.goto(currentManufacturerURL);

    const modelsURLs = await manufacturerPage.$$eval(
      "a.css-egdo2g.e1cpjsih7",
      (els) => els.map((el) => el.href),
    );

    console.log(modelsURLs);

    const modelCars: Car[] = [];

    for (let j = 0; j < modelsURLs.length; j++) {
      const car: Car = {
        pros: "",
        cons: "",
      };

      const modelPage = await browser.newPage();

      await modelPage.emulate(KnownDevices["iPad Pro"]);
      await modelPage.goto(modelsURLs[j]);

      const pros = await modelPage.$eval(
        "::-p-xpath(//*[text() = 'יתרונות'])",
        (el) => el.nextElementSibling?.firstChild?.textContent,
      );
      car.pros = pros || "";

      const cons = await modelPage.$eval(
        "::-p-xpath(//*[text() = 'חסרונות'])",
        (el) => el.nextElementSibling?.firstChild?.textContent,
      );
      car.cons = cons || "";

      modelCars.push(car);

      console.log("current car:", car);
    }

    allCars.set(currentManufacturerName, modelCars);
  }

  await browser.close();
})();
```

### Error string

DOMException: Failed to execute 'evaluate' on 'Document': The string '' is not a valid XPath expression.

### Bug behavior

- [x] Flaky
- [ ] PDF

### Expectation

Basically i just expected it to work since it worked in the previous patch version, v22.10.0, before updating to v22.10.1.

### Reality

Well, in the previous version it worked perfectly, but in v22.10.1 it fails with the following error:

370 |         }
371 |         const { exceptionDetails, result: remoteObject } = await callFunctionOnPromise.catch(rewriteError);
372 |         if (exceptionDetails) {
373 |             throw createEvaluationError(exceptionDetails);
374 |         }
375 |         return returnByValue
                   ^
DOMException: Failed to execute 'evaluate' on 'Document': The string '' is not a valid XPath expression.
q (pptr:internal:3:7033)
q.next (<anonymous>)
Async-from-Sync Iterator.next (<anonymous>)
pptr:internal:3:8078
AsyncGenerator.next (<anonymous>)
a.flatMap (pptr:internal:3:4788)
async a.flatMap (pptr:internal:3:4782)
async de (pptr:internal:3:9005)
async fe (pptr:internal:3:9408)
      at /Users/omerelbaz/Documents/GitHub/AutoWebscraper/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:375:14
      
I'm not sure why, my first guess is that it has something to do with the fact that I'm searching for Hebrew text using XPath, and it looks like it suddenly think I'm looking for no text at all (the error mentions an empty '' string, but you can see from the code provided it is not empty).

Worth noting I'm using Bun but unable to specify that below.

### Puppeteer version

22.10.1

### Node version

22.2.0

### Package manager

yarn

### Package manager version

1.1.12

### Operating system

macOS

**Comment by OrKoN** [comment]
I am unable to reproduce. I get the error:

```
Error: Error: failed to find element matching selector "::-p-xpath(//*[text() = 'יתרונות'])"
```

which looks like a regular error when the element is not found (I didn't check if the element is really there). Could you please update the script to make sure it demonstrates the issue on Node?

**Comment by OrKoN** [comment]
I get the same result with 22.10.0

**Comment by OrKoN** [comment]
Note that we have done some refactoring in 22.10.1 and moved the selector parsing to the Node.js process. I wonder if bun perhaps not behaving in the same way? (we do not support bun)

**Comment by OrKoN** [comment]
We do not explicitly support bun and I am not able to reproduce with Node.
