### ISSUE TITLE
[Bug]: TypeError: page.removeListener is not a function

### ISSUE THREAD

**Issue by AntonPolyakin** [puppeteer/puppeteer#12588]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

            (async () => {
                const browser = await puppeteer.launch();
                const page = await browser.newPage();
                try {
                    let responseEventOccurred = false;
                    const responseHandler = (event) => (responseEventOccurred = true);

                    const responseWatcher = new Promise<void>(function (resolve, reject) {
                        setTimeout(() => {
                            if (!responseEventOccurred) {
                                resolve();
                            } else {
                                setTimeout(() => resolve(), 5000);
                            }
                            page.removeListener('response', responseHandler);
                        }, 500);
                    });
                    page.on('response', responseHandler);
                } catch {
                   //TypeError: page.removeListener is not a function
                }
                await browser.close();
            })();
```

### Error string

TypeError: page.removeListener is not a function

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Everything worked on earlier versions

### Expectation

I expect this to work on the latest version.

### Reality

In reality, I'll have to roll back the puppeteer version.

### Puppeteer version

22.11.0

### Node version

18.16.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Hey, since v22 we only include `on` and `off` to add/remove listeners. Use `page.off('response', responseHandler);`. See the changelog for all breaking changes https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.0.0
