### ISSUE TITLE
[Bug]:  Unexpected sequence & found at index 0

### ISSUE THREAD

**Issue by djereg** [puppeteer/puppeteer#12584]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.setContent(`
        <html>
            <body>
            <div>
                <h1>Title 1</h1>
                <table>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                        </tr>
                    </tbody>
                </table>
                <p>Random text 1</p>
                <h1>Title 2</h1>
                <table>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>2</td>
                        </tr>
                    </tbody>
                </table>
                <p>Random text 2</p>
                </div>
            </body>
        </html>
    `);

    const $div = await page.waitForSelector("div");
    const $tables = await $div!.$$("& > table");

    await browser.close();
})();
```

### Error string

Unexpected sequence & found at index 0

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I would like to select all tables inside the div, but only the child elements. Some tables may contain another table, but I need only the children, and there may be another child elements like `h1` or `p` next to the tables

This worked with 22.8.0, but fails with the error in title with 22.11.0. I upgraded from 22.8.0 to 22.11.0 directly.

### Expectation

I expected... to get the elements by selector like before.

### Reality

In reality, ... I get an error message.

### Puppeteer version

22.11.0

### Node version

21.7.2

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Thanks! it is a bug with nested selector parsing.

**Comment by OrKoN** [comment]
`await $div!.$$(":scope > table")` should yield same results as a workaround.

**Comment by djereg** [comment]
Thank you! If it will be fixed, then I will wait for it. Much easier than changing everywhere the code.

**Comment by djereg** [comment]
BTW, which one is the better to use? `& > table` or `:scope > table`?

I ask because I see the fix, and as I understand that is a fallback solution.

**Comment by OrKoN** [comment]
The `:scope` is an older feature from the Selector 4 spec https://drafts.csswg.org/selectors/#the-scope-pseudo and CSS nesting is a newer one from the css nesting module spec https://www.w3.org/TR/css-nesting-1/ I think you can use `& > table` since all modern browsers support it already. In Puppeteer, we use a selector parser to provide additional features and it does not support `& > table`  out of the box yet but that it was broken for you is a bug, we should fallback to CSS if the parser is not able to parse a selector.
