### ISSUE TITLE
[Bug]: Reopening #5849 Puppeteer does not work on RHEL 8.1 (inside a podman) 

### ISSUE THREAD

**Issue by vpremkum** [puppeteer/puppeteer#12604]
### Steps to reproduce

puppeteer stopped working once we migrated our build servers from RHEL7 to RHEL 8. Please let us know how to fix this .
 
Failed to launch the browser process!     /var/jenkins_home/workspace/acceptance-tests/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file

### Expected results

Failed to launch the browser process!     /var/jenkins_home/workspace/acceptance-tests/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file

### Actual results

Failed to launch the browser process!     /var/jenkins_home/workspace/acceptance-tests/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file

**Comment by OrKoN** [comment]
You need to install all missing system dependencies including libXss as the error indicates. See https://pptr.dev/troubleshooting#running-puppeteer-in-docker and https://pptr.dev/guides/system-requirements I am not sure if Chrome is officially supported on RHEL but here is a list of dependencies required on rpm-based systems https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/rpm/dist_package_provides.json;drc=2e9ec273b0df7d904c20579380822ff349d30ca3.

**Comment by ViniciusFXavier** [comment]
With these commands, you can set up and run the environment on any Linux distribution, including Ubuntu, CentOS, WSL (1, 2), and even [CodeSandbox](https://codesandbox.io/). Follow these steps:

1. **Update Package List and Apply Updates**  
   First, update the list of packages and apply the updates:  
   ```bash
   sudo apt update  
   sudo apt upgrade -y  
   ```  
   This ensures your system is up to date.  

2. **Install Dependencies for Chromium**  
   Install all necessary libraries and dependencies required to run Chromium:  
   ```bash
   sudo apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils  
   ```  
    Yes, there are several dependencies. :sweat:

3. **Handle DISPLAY Issues (if applicable)**  
   If you encounter issues related to the `DISPLAY` environment variable, run the following command to allow Linux GUI apps to connect:  
   ```bash  
   export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0  
   ```  

4. **Install Chromium if Not Found**  
   If Chromium is not installed or cannot be found, add the Chromium repository and install it:  
   ```bash  
   sudo add-apt-repository ppa:chromium-team/stable  
   sudo apt-get update  
   sudo apt install chromium-browser  
   ```
