### ISSUE TITLE
[Bug]: can't launch firefox on puppeteer@21.5.0 on GitHub actions

### ISSUE THREAD

**Issue by NoamGaash** [puppeteer/puppeteer#12611]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
    console.log("opening firefox")
    const browser = await puppeteer.launch({args: ['--no-sandbox'], product: "firefox"});
    console.log("I'm ok")
    await browser.close();
  })();
```

### Error string

TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!     at FirefoxLauncher.launch (file:///home/runner/work/pupeteer-firefox/pupeteer-firefox/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:123:23)     at async file:///home/runner/work/pupeteer-firefox/pupeteer-firefox/index.js:5:21

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm trying to run puppeteer tests with Firefox on GitHub actions.
Locally, everything is great, but seems like on CI the launch command never terminates.

Here is a minimal reproducible example repo I made:
https://github.com/NoamGaash/pupeteer-firefox

### Expectation

I expect `puppeteer.launch` to be finished after a few seconds, or at least provide a meaningful error message

### Reality

it throws timeout exception after 30 seconds.
When `timeout: 0` is used, it hangs until github terminates it.

### Puppeteer version

21.5.0

### Node version

20.14.0

### Package manager

npm

### Package manager version

9.5.1

### Operating system

Linux

**Comment by OrKoN** [comment]
@NoamGaash can you add dumpio: true flag to launch and see if anything is missing? Is Firefox installed by default on GitHub actions? It seems to work in our GitHub actions https://github.com/puppeteer/puppeteer/actions/runs/9561719936/job/26356595014

**Comment by OrKoN** [comment]
The error message indicates that the Firefox binary has not opened a WebSocket connection within 30 seconds, which indicates some problem with the Firefox version available in the workflow. cc @whimboo

**Comment by NoamGaash** [comment]
Thanks for the quick response!
I'm not sure if firefox installed by default in github actions.
Also, just to clarify - I can't reproduce the issue on latest puppeteer version. 

I've added the `dumpio: true` flag:
https://github.com/NoamGaash/pupeteer-firefox/actions/runs/9566239508/job/26371031287

**Comment by OrKoN** [comment]
@NoamGaash could you add `npx puppeteer browser install firefox` after `npm install` and before the script invocation? (to make sure the latest firefox binary is downloaded)

**Comment by NoamGaash** [comment]
I had it here:
https://github.com/NoamGaash/pupeteer-firefox/actions/runs/9565693525/job/26369193672
But it seems like this command does not exist on this puppeteer version

**Comment by OrKoN** [comment]
@NoamGaash do you mean that it works using the latest Puppeteer version? Does anything prevent upgrading? Firefox support is currently experimental so only the latest nightly release is tested against Puppeteer releases. Older versions of Puppeteer might not work with the latest nightly builds of Firefox.

**Comment by OrKoN** [comment]
thanks @whimboo 

@NoamGaash  so you would need to use at least Puppeteer 22.4.0 or better the latest version to be compatible with the latest nightly release.

**Comment by NoamGaash** [comment]
@OrKoN Yes, when using the latest puppeteer version it works.
We will upgrade the puppeteer version, there's no blocker.
It's not very convenient DX-wise, because I spent time investigating a regression made by the supply chain despite locking the version of all my dependencies, but I get it's an experimental feature so it's on us.
Thank you both very much for your help and fast response, I truly appreciate that.
