### ISSUE TITLE
[Bug]: Cannot run smoke tests locally

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#12619]
### Steps to reproduce

1) Check out Puppeteer, npm ci, npm run build
2) cd packages/ng-schematics
3) node tools/smoke.mjs

### Expected results

Tests run

### Actual results

```
➜  ng-schematics git:(main) node tools/smoke.mjs

node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
undefined
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.14.0
```

### @puppeteer/ng-schematics version

latest

### Angular CLI version

N/A

**Comment by OrKoN** [comment]
@Lightning00Blade any ideas?

**Comment by imhappyfor** [comment]
I'm not at all familiar with puppeteer but trying to run the command you posted did give me the same error. It looks like you may be missing some dependencies in the project. To get passed this initial error you can ```npm i angular/cli```
Then after restarting the terminal I ran the same command it failed at calling a command of "schematics ...." 
packages/ng-schematics/tools/projects.mjs
line 34 has a static for building schematics but it seems to not be available when it fails to run this command. Hopefully some of this helps. Cheers

**Comment by Lightning00Blade** [comment]
Closing as complete via #12711
