### ISSUE TITLE
[Bug]: Not all frames are restored on reconnect

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#12613]
### Minimal, reproducible example

```TypeScript
it('should be able to reconnect to a disconnected browser (codesandbox)', async () => {
  const {puppeteer, browser, close} = await launch({});
  // Connection is closed on the original one
  let remoteClose!: () => Promise<void>;
  try {
    const browserWSEndpoint = browser.wsEndpoint();
    const page = await browser.newPage();
    await page.goto(
      'https://codesandbox.io/p/sandbox/funcaptcha-demo-s8srw1?file=%2Findex.html'
    );
    await new Promise(resolve => {
      return setTimeout(resolve, 11000);
    });
    const originalDump = await dumpFrames(page.mainFrame());
    await browser.disconnect();

    const remoteBrowser = await puppeteer.connect({
      browserWSEndpoint,
      protocol: browser.protocol,
    });
    remoteClose = remoteBrowser.close.bind(remoteBrowser);
    console.log(remoteClose);
    const pages = await remoteBrowser.pages();
    const restoredDump = await dumpFrames(pages[0]!.mainFrame());
    console.log(originalDump);
    console.log(restoredDump);
    expect(restoredDump).toEqual(originalDump);
  } finally {
    await remoteClose();
    await close();
  }
});
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Not all frames are restored on reconnection

### Expectation

Restore all the frames

### Reality

The dump has missing frames

Original dump
```
[
  'https://codesandbox.io/p/sandbox/funcaptcha-demo-s8srw1?file=%2Findex.html',
  '    about:blank',
  '    https://nodebox-runtime.codesandbox.io/',
  '    https://worker.codesandbox.io/p/assets/webWorkerExtensionHostIframe-1633eaef.html?vscodeExtHostWorkerSrc=https%3A%2F%2Fworker.codesandbox.io%2Fp%2Fassets%2FextensionHost.worker-7fb0d9e8.js&parentOrigin=https%3A%2F%2Fcodesandbox.io&vscodeWebWorkerExtHostId=3c6542c7-fd18-4070-a40b-31843828b683',
  '    https://s8srw1.csb.app/',
  '        https://client-api.arkoselabs.com/v2/2.6.1/enforcement.bf6c920f19fb49ce16c82aaef4b83f45.html#11111111-1111-1111-1111-111111111111&26a71cac-f9bc-4d66-b762-5cdefac2d03f',
  '            https://client-api.arkoselabs.com/fc/assets/ec-game-core/game-core/1.22.0/standard/index.html?session=70317da269b3720d6.2399850801&r=us-east-1&meta=3&metabgclr=%23ffffff&metaiconclr=%23757575&guitextcolor=%23000000&pk=11111111-1111-1111-1111-111111111111&at=40&ag=101&cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc&lurl=https%3A%2F%2Faudio-us-east-1.arkoselabs.com&surl=https%3A%2F%2Fclient-api.arkoselabs.com&smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager&theme=default (game-core-frame)'
]
```

Dump on restored page

```
[
  'https://codesandbox.io/p/sandbox/funcaptcha-demo-s8srw1?file=%2Findex.html',
  '    about:blank',
  '    https://nodebox-runtime.codesandbox.io/',
  '    https://worker.codesandbox.io/p/assets/webWorkerExtensionHostIframe-1633eaef.html?vscodeExtHostWorkerSrc=https%3A%2F%2Fworker.codesandbox.io%2Fp%2Fassets%2FextensionHost.worker-7fb0d9e8.js&parentOrigin=https%3A%2F%2Fcodesandbox.io&vscodeWebWorkerExtHostId=3c6542c7-fd18-4070-a40b-31843828b683'
]
```

### Puppeteer version

22.11.2

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

**Comment by OrKoN** [comment]
@kblok does it help if you also add 11 sec delay after connecting before dumping the frames?

**Comment by kblok** [comment]
> @kblok does it help if you also add 11 sec delay after connecting before dumping the frames?

I just checked and it didn't help

**Comment by OrKoN** [comment]
Interesting, I wonder what the difference compared to the 'should be able to reconnect to a disconnected browser' test is. We need to create a minimal example for a website to reproduce this in tests.

**Comment by kblok** [comment]
> Interesting, I wonder what the difference compared to the 'should be able to reconnect to a disconnected browser' test is. We need to create a minimal example for a website to reproduce this in tests.

Yeah. The user downstream has the same issue on an internal site, and he found a public website with the same issue.

**Comment by OrKoN** [comment]
I think I found the cause and it is a race between creation of the page instances and targets being attached. I also noticed that pages[0] is not always returning the right page (the order does not seem to be stable). I wonder if this is a (relatively) recent regression.

**Comment by OrKoN** [comment]
So I think the best solution here would be to make sure we maintain the tree relationship between CDP-targets. When a Page instance is created, all child iframe targets have to be added to the frame tree by invoking the attachedToTarget method. I believe the issue only affects the out-of-process-iframes since the local frames are restored based on the Page.getFrameTree results. Unfortunately, the method does not include OOPIFs that have separate targets.
