### ISSUE TITLE
Error: Runtime.evaluate error when 10+ pages in browser

### ISSUE THREAD

**Issue by jharrington-ls** [puppeteer/puppeteer#1261]
# Environment

- **Puppeteer version:** 0.12.0
- **Local Platform:** macOS Sierra 10.12.6
- **Web Platform:** Heroku 16 with buildpack https://github.com/jontewks/puppeteer-heroku-buildpack

# Expected Result
1. Launch Puppeteer browser
2. For each search URL, open a new page in that browser
3. For each new page, wait until network idle and selectors `h3` and `a` are there
4. Scrape the results of the page via `page.evaluate` and then close that page and return the results
5. After all pages have been scraped, close the browser and return the results

# Issue
Everything works locally, I'm only running into an issue when using on Heroku, and only when trying to open a large amount of pages on a single browser instance.

The below code works locally but fails on Heroku with the error

```
Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed. 
 at Session.send
 at ExecutionContext.evaluateHandle 
 at ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/ExecutionContext.js:37:31) 
 at Frame.evaluate (/app/node_modules/puppeteer/lib/FrameManager.js:211:26) 
 at WaitTask.rerun (/app/node_modules/puppeteer/lib/FrameManager.js:520:35) 
 at new WaitTask (/app/node_modules/puppeteer/lib/FrameManager.js:503:10) 
 at Frame.waitForFunction (/app/node_modules/puppeteer/lib/FrameManager.js:447:12) 
 at Frame.waitForSelector (/app/node_modules/puppeteer/lib/FrameManager.js:418:17) 
 at Page.waitForSelector (/app/node_modules/puppeteer/lib/Page.js:818:29) 
 at Promise (/app/api/webScraping/puppeteerGoogleNews.js:65:18) 
 at <anonymous> 
```

The error only occurs on Heroku with a large amount of pages open on a single browser instance in Puppeteer, it works fine with 3-5 pages open, and works ~5% of the time with the 10 pages, but otherwise fails and throws the above error the other 95%.

Below is the code to reproduce the issue. I was double checking to make sure all pages were `await`'d and none were being closed before they were finished with. But the fact that it only has an issue with many pages open makes me think it might be some other issue.

```javascript
const puppeteer = require('puppeteer');
getNews();
async function getNews() {
  const searchUrls = [
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=BigCommerce',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=%22IBM+Websphere"+OR+"Websphere"+AND+"Commerce"+OR+"Websphere"+AND+"Retail"',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=Kibo+Commerce',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=%22Oracle"+AND+"Commerce+Cloud"+OR+"Netsuite"',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=%22OroCommerce"+OR+"Oro+Commerce"',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=PrestaShop',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=(%22Salesforce"+AND+"Commerce+Cloud")+OR+"Demandware"',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=%22SAP+Hybris"+AND+(e+commerce+OR+e-commerce+OR+retail)',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=Shopify+-%22(NYSE:SHOP)"+-"(TSE:SHOP)"+-"(SHOP)"',
    'https://www.google.com/search?hl=en&gl=us&tbm=nws&tbs=sbd:1&num=10&q=Volusion',
  ];

  // Launch browser
  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  // Get all results
  const searchPromises = searchUrls.map(url => singleSearch(browser, url));
  const searchResults = await Promise.all(searchPromises);

  // Close browser
  await browser.close();
}

function singleSearch(browser, url) {
  return new Promise(async (resolve, reject) => {
    // Go to page
    const page = await browser.newPage();
    await page.goto(url, { waitUntil: 'networkidle' });
    await page.waitForSelector('h3 a');

    // Log events
    page.on('console', (...args) => {
      for (let i = 0; i < args.length; i += 1) {
        console.log(`${i}: ${args[i]}`);
      }
    });

    // Get page results
    const searchResults = await page.evaluate(singlePage);

    // Close page and return results
    await page.close();
    resolve(searchResults);
  });
}

function singlePage() {
  const newsElements = document.querySelectorAll('._NId ._cy');
  const articles = [];
  for (let i = 0; i < newsElements.length; i += 1) {
    const el = newsElements[i];
    const article = {
      url: el.querySelector('div div h3 a').href,
      title: el.querySelector('div div h3').textContent,
      publication: el.querySelector('div div .slp span:first-child')
        .textContent,
    };
    articles.push(article);
  }
  return articles;
}

```

**Comment by aslushnikov** [comment]
@jharrington-ls it looks like renderer process crashes, e.g. due to memory constrains.

I'd recommend creating a pool of pages and scheduling tasks among them. This should allow you to process URLs in parallel while avoiding creation of multiple renderers.

**Comment by jharrington-ls** [comment]
Thanks for the info @aslushnikov!

Was looking through the API and saw no mention of pooling pages or scheduling tasks, so just want to double check I'm understanding the solution properly. 

Instead of creating and closing a page for each URL, I should instead:
- Open a small amount of pages on one browser instance (e.g. 3 pages max)
- Loop through URLs and send to any open page
- Once a URL has been processed, instead of closing the page, send the next URL in the queue to the page, have the page go to the URL, process the results, and repeat

Is that correct? Wasn't sure what was considered a renderer or if the bulleted approach above would help with the memory constraints. Thanks again for your help.

**Comment by aslushnikov** [comment]
@jharrington-ls yes, exactly this. This will restrict total amount of pages to 3; whereas in your snippet you create 10 pages simultaneously.

**Comment by iamricky** [comment]
@jharrington-ls Did this solution work for you? I have a similar problem and tried opening just one page but ran into the same issue, which leads me to believe it's not related to the number of renders. I also found [this issue](https://github.com/GoogleChrome/puppeteer/issues/894), which raises more questions.
