### ISSUE TITLE
Unable to click a button to join a meeting on MsTeams

### ISSUE THREAD

**Issue by akumar044** [puppeteer/puppeteer#12614]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer-extra");
const StealthPlugin = require("puppeteer-extra-plugin-stealth");
puppeteer.use(StealthPlugin());

function startMeeting() {
   const browser = await puppeteer.launch({
      headless: false,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
      ],
      ignoreDefaultArgs: ["--mute-audio"],
      executablePath: executablePath("chrome"),
      ignoreHTTPSErrors: true
    });

    const page = await browser.newPage();
    const navigationPromise = page.waitForNavigation();
    
    await page.goto(link, {
      waitUntil: "domcontentloaded",
    });
    await navigationPromise;

    // More logic

    await page.waitForSelector('button[aria-label="Join now"]');
    await new Promise(r => setTimeout(r, 1 * 1000))
    await page.focus('button[aria-label="Join now"]')
    await page.click('button[aria-label="Join now"]');
}

///////////////////////////////////////////////////////////
// Dockerfile

# Use Node.js official image as the base image
FROM node:latest

# Set working directory inside the container
WORKDIR /usr/src/app

ENV DISPLAY=:99

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Install Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
    && apt-get update && apt-get install -y google-chrome-stable

# Install Puppeteer dependencies
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    procps \
    libxshmfence1 \
    libgbm1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatspi2.0-0 \
    libgtk-3-0 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    xvfb

# Copy the rest of the application code
COPY . .

RUN chmod +x /usr/src/app/entrypoint.sh

# Expose port 3000
EXPOSE 3001

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
# Command to run the application
CMD ["node", "app.js"]

///////////////////////////////////////////////////////

// entrypoint.sh

#!/bin/sh
# Start Xvfb
Xvfb :99 -screen 0 1280x720x24 -ac & npm run test
# Export the DISPLAY environment variable
export DISPLAY=:99
# Run the command passed as arguments to this script
exec "$@"
```

### Error string

The "Join now" isn't getting clicked

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I'm trying to join msTeams meeting but the "Join now" button doesn't get clicked when I deploy the changes on an EC2 instance. When I added a few Screenshots, it's visible that the button actually gets focused, it's just not getting clicked.

So far I have tried multiple ways to click the button but none has worked so far
1. await page.evaluate(() => {
      const element = document.querySelector('button[aria-label="Join now"]')
      element.click()
    })

2. page.$eval('button[aria-label="Join now", element =>
    element.click()
  )

This code is working fine on local but just not on EC2

Packages:
"puppeteer": "^22.11.0",
"puppeteer-extra": "^3.3.6",
"puppeteer-extra-plugin-stealth": "^2.11.2"

Any help is greatly appreciated. Thank you!

### Expectation

The "Join now" should get clicked and it should join the meeting

### Reality

"Join now" is not getting clicked on the EC2 instance

### Puppeteer version

22.11.0

### Node version

22.3.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Hi, it sounds like it is a question suitable for StackOverflow rather than a bug report. Consider asking using the puppeteer tag https://stackoverflow.com/questions/tagged/puppeteer If it does not work on AWS, maybe the site blocks access from the data centers to prevent abuse.
