### ISSUE TITLE
[Bug]: Nondeterministic timeouts or race condition in `::-p-aria(name)` on element added shortly after page load

### ISSUE THREAD

**Issue by ggorlen** [puppeteer/puppeteer#12625]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer"; // ^22.11.2

const run = async () => {
  let browser;
  try {
    browser = await puppeteer.launch();
    const [page] = await browser.pages();
    const html = `<!DOCTYPE html><html lang="en"><body><script>
      setTimeout(() => {
        document.body.innerHTML = "<h1>foo</h1>";
      }, 15);
    </script></body></html>`;
    await page.setContent(html);
    const selector = `::-p-aria(foo)`;
    await page.waitForSelector(selector, {timeout: 5000});
    console.log("PASS");
    return true;
  } catch (err) {
    console.error("FAIL:", err.name);
    return false;
  } finally {
    await browser?.close();
  }
};

(async () => {
  const n = 30;
  let failures = 0;

  for (let i = 0; i < n; i++) {
    const success = await run();
    failures += success ? 0 : 1;
  }

  console.log(`Failures out of ${n} runs: ${failures}`);
})();
```

### Error string

TimeoutError

### Bug behavior

- [X] Flaky
- [ ] PDF

### Background

I'm trying to select an element that's added shortly after page load using the `::-p-aria()` p-selector.

### Expectation

I'm expecting that the code gives 100% deterministic results, always finding the selector that's added shortly after page load. I expect that there should be no behavioral difference between `::-p-aria()` and any other p-selector or CSS selector that matches the element.

### Reality

I get nondeterministic timeouts when trying to select an element added shortly after page load with `::-p-aria()`. The timeouts occur specifically with the `::-p-aria()` p-selector and don't seem to occur with any other selectors I've tried (`::-p-text()` or CSS selectors work as expected and successfully find the element every time).

Reproduction also requires a short delay between the page load and the element being added, roughly 15ms on my machine seems optimal for triggering the error.

### Puppeteer version

22.11.2

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by OrKoN** [comment]
Thanks! It looks like it is related to the way waitForSelector polls. By default, it uses the mutation observer to re-run the query like the CSS selectors (I recently fixed a similar bug related to pseudo classes https://github.com/puppeteer/puppeteer/issues/6830). In this case, it looks like nowadays the a11y tree is updated asynchronously in Chrome (IIRC that was not the case a few years back) so when the mutation is detected, the a11y might not be up-to-date yet. The short-term solution is to switch to using the RAF-based mechanism and longer term we probably need to be able to detect when the a11y tree is updated.

In the current version, the workaround would be to turn on `visible: true` in `waitForSelector`:

```
await page.waitForSelector(selector, {timeout: 5000, visible: true});
```

This flag forces RAF-based mechanism since DOM mutations are not required to change visibility.

**Comment by OrKoN** [comment]
Using the `--force-renderer-accessisbility` arg seems to work around the issue as well.

**Comment by greg-gorlen-andela** [comment]
> Using the `--force-renderer-accessisbility` arg seems to work around the issue as well.

That works, but there's a small typo in your flag (extra last 's') that confused me for a minute. Here's the working version:

```js
browser = await puppeteer.launch({
  args: ["--force-renderer-accessibility"],
});
```

**Comment by ggorlen** [comment]
> Using the `--force-renderer-accessisbility` arg seems to work around the issue as well.

That works, but there's a small typo in your flag (extra last 's') that confused me for a minute. Here's the working version:

```js
browser = await puppeteer.launch({
  args: ["--force-renderer-accessibility"],
});
```

**Comment by OrKoN** [comment]
It appears that the issue has been already fixed in M128. I am not able to reproduce with google-chrome-unstable or custom-built Chrome on Linux but I still see some timeouts with Chrome Canary on Mac. @ggorlen are you able to reproduce using the dev channel build of Chrome on Linux?
