### ISSUE TITLE
[Bug]: When Puppeteer >= 22 generating a PDF it always comes out blank

### ISSUE THREAD

**Issue by herberthobregon** [puppeteer/puppeteer#12626]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Navigate the page to a URL
  await page.goto('https://google.com/', {
    waitUntil: 'networkidle2',
  });
  await page.pdf({
    path: 'google.pdf',
  });

  await browser.close();
})();
```

### Error string

PDF is blank

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

When generating a PDF it always comes out blank, this does not happen if I generate an image. Since version `22` it doesn't work but in any version `21` it does work.

### Expectation

Show a page in PDF

### Reality

show blank page

### Puppeteer version

22.11.2

### Node version

20.9.0

### Package manager

pnpm

### Package manager version

9.6.7

### Operating system

Linux

**Comment by jasonswearingen** [comment]
@herberthobregon what was the solution?  I am having the same problem when upgrading to pptr latest, from v20

**Comment by herberthobregon** [comment]
> @herberthobregon what was the solution?  I am having the same problem when upgrading to pptr latest, from v20

, in my case, I replaced the native functions atob and btoa with a buffer implementation. Prior to this, I was using an older version of Node.js.
Therefore, I recommend deleting this implementation, and the problems should be resolved.

**Comment by jasonswearingen** [comment]
thank you for the reply.   @herberthobregon 

for anyone fighting with pdf generation after upgrading to pptr v23+, here is (likely) the solution: https://github.com/puppeteer/puppeteer/issues/13209#issuecomment-2817202802
