### ISSUE TITLE
[Bug]: The code for generating pdf does not generate pdf and timesout after 30000ms, but is apparently able to generate png files

### ISSUE THREAD

**Issue by rahuls-foxberry** [puppeteer/puppeteer#12647]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto("https://news.ycombinator.com", {
    waitUntil: "networkidle2",
  });

  await page.screenshot({
    path: "hn.png",
  });

  await page.pdf({
    path: "hn.pdf",
  });

  await browser.close();
})();
```

### Error string

Timed out after waiting ${ms}ms`, { cause }

### Bug behavior

- [ ] Flaky
- [X] PDF

### Background

I wanted to generate a pdf for a webpage

### Expectation

I wanted to generate a pdf and a png image for a webpage

### Reality

The code is able to generate the png image for the webpage, but when generating pdf it give an error

### Puppeteer version

22.12.0

### Node version

v20.14.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Probably related to the sandbox issue, see https://github.com/puppeteer/puppeteer/issues/12471  and https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows
