### ISSUE TITLE
[Bug]: unable to connect with browserWSEndpoint

### ISSUE THREAD

**Issue by redwanul10** [puppeteer/puppeteer#12653]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

const init = async () => {
  try {
    const browser = await puppeteer.connect({
      browserWSEndpoint:
        "ws://127.0.0.1:39694/devtools/page/bf133a0e-433a-426c-a20b-9c445ea0afad",
        //"ws://localhost:39694/devtools/page/bf133a0e-433a-426c-a20b-9c445ea0afad",

    });
  } catch (error) {
    console.log(error);
  }
};

init();
```

### Error string

ProtocolError: Protocol error (Browser.getVersion): 'Browser.getVersion' wasn't found     at Callback.<instance_members_initializer> (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)     at new Callback (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)     at CallbackRegistry.create (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)     at Connection._rawSend (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)     at Connection.send (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:21)     at _connectToCdpBrowser (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/BrowserConnector.js:21:38)     at _connectToBrowser (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/common/BrowserConnector.js:56:81)     at processTicksAndRejections (node:internal/process/task_queues:96:5)     at async init (/Users/redwanulislam/Desktop/automate-tizen/app.js:6:21)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am developing a Tv app for Samsung TV. I can debug that web app using chrome remote debugger but now I want to automate some ui Task. but it is not connecting to the webSocketDebuggerUrl.

here are the response from the chrome remote debugger 
**endpoint:**  http://localhost:39694/json
### response:
```js
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:39694/devtools/page/e714f85b-04f6-46a5-b83d-29f6d75193d7",
   "faviconUrl": "file:///icon.png",
   "id": "e714f85b-04f6-46a5-b83d-29f6d75193d7",
   "title": "testApp",
   "type": "page",
   "url": "file:///index.html",
   "webSocketDebuggerUrl": "ws://localhost:39694/devtools/page/e714f85b-04f6-46a5-b83d-29f6d75193d7"
} ]
```

**But using javascript websocket I can connect to the ``webSocketDebuggerUrl`` & send raw commands which is working fine !**
### Example:
```js
 // WebSocket URL
  const socketUrl = "ws://localhost:39694/devtools/page/e714f85b-04f6-46a5-b83d-29f6d75193d7";

  // Create WebSocket object
  const socket = new WebSocket(socketUrl);

  // Event handler for successful connection
  socket.onopen = function (event) {
    console.log('WebSocket connection established.');
  };

  // Event handler for incoming messages
  socket.onmessage = function (event) {
    console.log('Message from server:', event.data);

    // Close the WebSocket connection after receiving a message
    // socket.close();
  };

  // Event handler for WebSocket connection close
  socket.onclose = function (event) {
    if (event.wasClean) {
      console.log(`WebSocket connection closed cleanly, code=${event.code}, reason=${event.reason}`);
    } else {
      console.error('WebSocket connection closed unexpectedly');
    }
  };

  // Fire Arrow Left key down event
  const dispatchKeyEventCommand = {
    id: 1,
    method: 'Input.dispatchKeyEvent',
    params: {
      type: 'rawKeyDown',     // Type of the key event ('keyDown', 'keyUp', 'rawKeyDown', 'char')
      modifiers: 0,           // Bit field representing pressed modifier keys (Shift=1, Ctrl=2, Alt/Option=4, Command/Windows=8)
      windowsVirtualKeyCode: 37, // The virtual key code of the key (37 is for Left Arrow)
      nativeVirtualKeyCode: 37,  // The native key code of the key
      text: '',               // Text as generated by processing a virtual key code with a keyboard layout
      unmodifiedText: '',     // Text that would have been generated by the keyboard if no modifiers were pressed
      autoRepeat: false,      // Whether the event was generated from auto repeat (default: false)
      isKeypad: false,        // Whether the event was generated from the keypad (default: false)
      isSystemKey: false,     // Whether the event was generated from a system key (default: false)
    }
  };

  socket.send(JSON.stringify(dispatchKeyEventCommand));

```

Unfortunately puppeteer is not able to connect to the url !

### Expectation

should connect to the chrome that running on my TV

### Reality

not connecting throwing error 
```js
ProtocolError: Protocol error (Browser.getVersion): 'Browser.getVersion' wasn't found
    at Callback.<instance_members_initializer> (/Users/redwanulislam/Desktop/automate-tizen/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
```

### Puppeteer version

22.7.1

### Node version

16.20.2

### Package manager

npm

### Package manager version

8.19.4

### Operating system

macOS

**Comment by OrKoN** [comment]
You need to connect to the browser endpoint and it looks you are connecting to the page endpoint which provides access only to the page target. Puppeteer expects the connection to the browser target. You should be able to get the socket connection from http://localhost:39694/json/version or use the `{browserURL: 'http://localhost:39694'}` when connecting.
