### ISSUE TITLE
the method mouse.up() cannot trigger ondragend event when I drag some controls towards canvas

### ISSUE THREAD

**Issue by nov-liluo** [puppeteer/puppeteer#1265]
* Puppeteer version: 0.12.0
* Platform / OS version: centos

**What steps will reproduce the problem?**
I try to use JavaScript function in my code to trigger this event, is there any batter way in puppeteer?

**What is the expected result?**
I focus the html element，use mouse.down()，then mouse.move(x, y) to the canvas，the canvas will create a node

**What happens instead?**
but element‘s ondrop()  is not triggered， the node isn't exist.

**Comment by aslushnikov** [comment]
@JoelEinbinder could you please take a look? That's your favorite drag-and-dropping!

**Comment by paul-sachs** [comment]
@aslushnikov @JoelEinbinder I'm also seeing something similar, although in my case, I'm working on a react app with react-dnd and the dragend event is being fired but in the wrong place. In my case, I'm using puppeteer 0.13.0 and I'm on mac OS.

```js
// sourceBox is bounding rect of source
console.log('start: ', sourceBox.x + sourceBox.width / 2, sourceBox.y + sourceBox.height / 2);
await page.mouse.move(sourceBox.x + sourceBox.width / 2, sourceBox.y + sourceBox.height / 2);
await page.mouse.down();

// destBox is bounding rect of destination
console.log('end: ', destBox.x + destBox.width / 2, destBox.y + destBox.height / 2);
await page.mouse.move(destBox.x + destBox.width / 2, destBox.y + destBox.height / 2);
await page.mouse.up();
```

I was able to monitor the events `dragstart` and `dragend` to match with the above console logs.

dragstart: { x: 332.6640625, y: 514 } => start: 332.6640625 514
dragend: { x: 869, y: 771 } => end: 790.65625 372

I don't know what I'm missing. The dragstart fires the event I'm expecting, but the dragend fires at something offset by { x: 79, y: 399 }

**Comment by paul-sachs** [comment]
I've created a test repo that reproduces this issue 100% of the time: https://github.com/psachs21/dnd-repo. I'd love a workaround because this is blocking adoption of puppeteer.

**Comment by carpeliam** [comment]
I'm also using [react-dnd](https://github.com/react-dnd/react-dnd), and seeing similar issues. I've forked @psachs21's example to add mouse/drag event logging and uploaded it to http://carpeliam.github.io/dnd-repo/ - the big difference is that a `drop` event is triggered when running the example manually, but not when running via puppeteer.

**Comment by paul-sachs** [comment]
@JoelEinbinder any chance this issue can be looked at? I've looked through the code but haven't made any progress determining the source of the issue. I'm not even sure the issue lies within puppeteer itself.

**Comment by mgkeeley** [comment]
I have the same issue.  It seems that after mouse.down(),  the mouse.move() and mouse.up() calls generate mousemove and mouseup events; but they should be generating dragover/drop/dragend events.
Manually:
```
mouse move (many)
mousedown
mouse move (few)
dragstart
dragover (many)
drop
dragend
```

Via puppeteer:
```
mouse move (many)
mousedown
mouse move (many)
mouseup
```
I am using puppeteer 1.1.0

Possibly it is really a problem in chrome

**Comment by mgkeeley** [comment]
**Update:** 
tried a drag with 20 steps, and modified puppeteer to add a 10ms delay in between each step. I then got the following output (with HEADLESS=1)
```
mouse move (many)
mousedown
mouse move
drag start
mouse move (many)
mouseup
```
If I try with HEADLESS=0
```
mouse move (many)
mousedown
mouse move
drag start
drag end   <---------------   at the real cursor coordinates
mouse move (many)
mouseup
```
So it seems like something in chrome/devtools protocol, where drags are looking at the real cursor state.

**Comment by paul-sachs** [comment]
@aslushnikov @JoelEinbinder any update on this issue?

**Comment by kody-abe** [comment]
@aslushnikov @JoelEinbinder Also seeing this, any update?

**Comment by CyrilQuandalle** [comment]
For information for those who are using ReactDnd it seems the problem is coming from the way the library handle drag & drop, because after testing it with react-beautiful-dnd it works ;-)

**Comment by CyrilQuandalle** [comment]
Any update on this issue @JoelEinbinder ? 
FYI, I tested it with react dnd and with  pure native drag and drop events and the cursor is sticking to the real one in non headless mode so the item can't be dropped automaticaly. I also tested it with react beatutiful dnd codesansbox [example](https://codesandbox.io/s/ql08j35j3q) and it works. One hint would be that the react beautiful dnd example has its lists nested in one same component and mine are not, so they don't share the same context ;-)

**Comment by vripoche** [comment]
Hello,

We have found with @CyrilQuandalle a workaround to simulate the DND Drag&Drop with Puppeteer.
it is not very clean to add simulateDrag and simulateDrop functions in real app window object with React TestUtils functions calls, but we can imagine making a specific build for puppeteer context with that functions.

https://gist.github.com/vripoche/929ea5a5aff47cb0a68de92026939701

**Comment by tonnenpinguin** [comment]
This issue has been around for a bit and I stumbled upon it on the latest puppeteer version as well. Is there any other way than the mentioned workaround to get this to work?

**Comment by CyrilQuandalle** [comment]
Maybe by using puppeteer-recorder. I haven't tried it yet but it could give us at least a hint or a  cleaner solution 😉

https://github.com/checkly/puppeteer-recorder

**Comment by tonnenpinguin** [comment]
I just tried puppeteer recorder. However, that only shows a click event and completely ignores the drag and drop part :confused:

**Comment by CyrilQuandalle** [comment]
That's too bad, I was really hopping it would work 😐. I'll just keep using the workaround then 😉

**Comment by gabrielbusarello** [comment]
Hi guys. I doed an workaround for drag events of elements.
The problem is the drop event, it isn't called on mouseup event. So I took some solutions from one guy who did this for puppeteer and added the drop event in destinationElement. The code is in this gist:
https://gist.github.com/gabrielbusarello/181bf0ff6424c410a7137371f8a04af3
For me worked with react-dnd. I hope that helps you too.
