### ISSUE TITLE
Click method is horrible

### ISSUE THREAD

**Issue by joelnune** [puppeteer/puppeteer#12668]
### Feature description

the click feature doesn't work, i put the class that i need on the method and simple do not click.

**Comment by OrKoN** [comment]
We cannot help you with this little information, please fill out the bug report form to provide necessary details to reproduce the issue https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%5BBug%5D%3A+

Also, please take a look at our click tests https://github.com/puppeteer/puppeteer/blob/main/test/src/click.spec.ts and feel free to open a PR suggesting additional tests.
