### ISSUE TITLE
can't install puppeteer

### ISSUE THREAD

**Issue by premillos** [puppeteer/puppeteer#1267]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: windows 10
* URLs (if applicable): can't support

**What steps will reproduce the problem?**

![image](https://user-images.githubusercontent.com/16378134/32362569-5b4ee95e-c0a5-11e7-85fb-f5ffdf54e9fb.png)

_Please include code that reproduces the issue._

1.yarn add puppeteer

**What is the expected result?**
i can use puppeteer

**What happens instead?**

emmmm

**Comment by aslushnikov** [comment]
are you behind a firewall?

**Comment by premillos** [comment]
@aslushnikov  yes , but i use the shadowsocks and the taobao registry

**Comment by thankwsx** [comment]
set the env  variable to skip download the chromium。
you can just use chrome canary for instead by setting launch params executablePath

**Comment by premillos** [comment]
@thankwsx  thanks i set the npm env can use it

**Comment by plh97** [comment]
i skip install chromium,
after that what should i do

**Comment by ebidel** [comment]
Install a chrome binary by whatever means works for you then use `executablePath ` .

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions

**Comment by hugollm** [comment]
Mine is hanging on 99%. I don't think I'm behind a firewall (but I can't really trust my ISP tho).

```
Downloading Chromium r637110 - 109.4 Mb [====================] 99% 0.0s 
```

The solution I'm using so far (found [somewhere on the internet](http://blog.cc0c.cc/detail/5c8234e6c3955f0bf6fbd273)) is forcing puppeteer to download from a chinese mirror:

```
PUPPETEER_DOWNLOAD_HOST=https://npm.taobao.org/mirrors npm install
```

It works like a charm, but I feel uneasy doing this.

If someone have more information on this issue and why it happens I would like to know. I looked everywhere and couldn't find much details about it. I'm very confused about why a firewall would prevent chromium to download (and not mess with other stuff). Why just chromium?

**Comment by usahai** [comment]
I managed to do what @pengliheng did. How do I reset my target browser from chromium to chrome? Can I set it up in the jest-puppeteer.config.js file?
