### ISSUE TITLE
[Bug]: `element.focus()` is not working (or the selector `:focus` is not working) with new headless mode

### ISSUE THREAD

**Issue by GuillaumeGomez** [puppeteer/puppeteer#12671]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; // TS/ESM are all supported.

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto("some_url");
  const elem = await page.$("#button");
  await elem.focus();
  await page.$("#button:focus"); // fails
  await browser.close();
})();
```

### Error string

Element not found

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I have my GUI framework test (https://github.com/GuillaumeGomez/browser-UI-test/) we use to check docs.rs and rustdoc output. I'm updating the puppeteer version and found new issues with code that was previously working.

Important to be noted: if I use the "old" headless mode, it works as expected.

### Expectation

The element should be found.

### Reality

It doesn't work.

### Puppeteer version

22.12.1

### Node version

v20.15.0

### Package manager

npm

### Package manager version

10.7.0

### Operating system

Linux

**Comment by GuillaumeGomez** [comment]
No clue about the "real" error message, it is wrapped in my framework...

**Comment by OrKoN** [comment]
I am unable to reproduce with 22.12.1:

```
import puppeteer from 'puppeteer'; 

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(
    '<button id="button">test</button>'
  )
  const elem = await page.$("#button");
  await elem.focus();
  const element = await page.$("#button:focus");
  console.log('found', !!element);
  if (!element) {
    throw new Error('Not found')
  }
  await browser.close();
})();
```

 if there is no error, you could add one to demonstrate where it is not working as expected.

**Comment by somebee** [comment]
@GuillaumeGomez I'm experiencing this as well. Still happening for you?

**Comment by GuillaumeGomez** [comment]
I'm not using the last version for now so I suppose?
