### ISSUE TITLE
[Bug]: Use puppeteer in docker, can't launch it

### ISSUE THREAD

**Issue by yunzaifei** [puppeteer/puppeteer#12699]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-core';

const browser = await puppeteer.launch({
  headless: 'shell',
  executablePath: 'google-chrome-stable',
  args: ['--no-sandbox', '--disable-dev-shm-usage'],
});
```

### Error string

Browser was not found at the configured executablePath (google-chrome-stable) at ChromeLauncher.launch 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I use the puppeteer in the docker, the docker is build from `ghcr.io/puppeteer/puppeteer`,  the Dockerfile is
```
FROM ghcr.io/puppeteer/puppeteer

USER pptruser

WORKDIR /app

COPY --chown=pptruser:pptruser ["dist", "package.json", "package-lock.json", "./"]

ENV NODE_ENV production
ENV TZ=Asia/Shanghai

RUN npm ci --omit=dev

CMD ["node", "index.js"]
```

### Expectation

this is my code:
```
import puppeteer from 'puppeteer-core';

const browser = await puppeteer.launch({
  headless: 'shell',
  executablePath:  'google-chrome-stable',
  args: ['--no-sandbox', '--disable-dev-shm-usage'],
});

```

### Reality

the code is OK when not in docker environment, but when I run the code in docker, the error is:
```
Browser was not found at the configured executablePath (google-chrome-stable) at ChromeLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:72:19)
```
when I run 'google-chrome-stable' in docker exec:
```
$ google-chrome-stable
[27:27:0703/144445.324528:ERROR:browser_dm_token_storage_linux.cc(105)] Error: /etc/machine-id contains 0 characters (32 were expected).
[27:53:0703/144445.348861:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[27:27:0703/144445.354140:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[27:27:0703/144445.354205:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
```

### Puppeteer version

22.12.1

### Node version

20.9.0

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Puppeteer checks if executable exists so it expects a full path. Try running `which google-chrome-stable` in Docker and using the full path to the binary that is returned.

**Comment by OrKoN** [comment]
Also, consider using the bundled version of Chrome for Testing without providing an executable path.

**Comment by yunzaifei** [comment]
> Puppeteer checks if executable exists so it expects a full path. Try running `which google-chrome-stable` in Docker and using the full path to the binary that is returned.

It works, Thank you!
