### ISSUE TITLE
[Bug]: build problems using puppert-core in extensions

### ISSUE THREAD

**Issue by elineeen** [puppeteer/puppeteer#12703]
### Minimal, reproducible example

```TypeScript
vite build
```

### Error string

PassThrough" is not exported by "__vite-browser-external”

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Currently i'm building the extension app with vite using pptr-core, and stucked in some modules whether using the example rollup config or not(since node-resolve is already a default vite built-in ). Though i can add externals to rollupOptions to skip these problems in building phase ,i'm not sure these api will works fine without some sort of node polyfills

### Expectation

maybe a better bundle example or some compatible browser api replacement?

### Reality

![image](https://github.com/puppeteer/puppeteer/assets/61259088/7a4d6766-a3a1-43d1-afc7-a83913fc17a9)
![image](https://github.com/puppeteer/puppeteer/assets/61259088/32419e58-6d14-417e-97ac-367f29877737)
currently the build process works fine after adding these externals 
![image](https://github.com/puppeteer/puppeteer/assets/61259088/6fb9255b-cc05-406b-96e2-99bde502192a)

### Puppeteer version

22.12.1

### Node version

18.17.0

### Package manager

yarn

### Package manager version

3.6.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Have you tried this example https://github.com/puppeteer/puppeteer/tree/main/examples/puppeteer-in-browser? It’s also important to import the browser-specific entrypoint like in the example and not the main puppeteer-core entrypoint.

**Comment by elineeen** [comment]
I get your point , but in my case i use connect api in my chrome extension with transport options just like the extension demo instead of the examples which using endpoint. Does this affect build phase?
![image](https://github.com/puppeteer/puppeteer/assets/61259088/31d1b82b-f49f-4bc6-aed8-2c6f90a76fae)

**Comment by OrKoN** [comment]
There is an example specifically for extension: https://github.com/puppeteer/puppeteer/tree/main/examples/puppeteer-in-extension. The rollup config https://github.com/puppeteer/puppeteer/blob/main/examples/puppeteer-in-extension/rollup.config.mjs

It builds for me with the following log:

```
❯ npm run build

> puppeteer-in-extension@1.0.0 build
> rollup -c && cp manifest.json out/


background.js → out...
(!) "this" has been rewritten to "undefined"
https://rollupjs.org/troubleshooting/#error-this-is-undefined
../../packages/puppeteer-core/lib/esm/puppeteer/common/HandleIterator.js
4:  * SPDX-License-Identifier: Apache-2.0
5:  */
6: var __addDisposableResource = (this && this.__addDisposableResource) || function (env, value, async) {
                                  ^
7:     if (value !== null && value !== void 0) {
8:         if (typeof value !== "object" && typeof value !== "function") throw new TypeError("Object expected.");
...and 3 other occurrences
../../packages/puppeteer-core/lib/esm/puppeteer/common/QueryHandler.js
4:  * SPDX-License-Identifier: Apache-2.0
5:  */
6: var __addDisposableResource = (this && this.__addDisposableResource) || function (env, value, async) {
                                  ^
7:     if (value !== null && value !== void 0) {
8:         if (typeof value !== "object" && typeof value !== "function") throw new TypeError("Object expected.");
...and 3 other occurrences
../../packages/puppeteer-core/lib/esm/puppeteer/cdp/ElementHandle.js
4:  * SPDX-License-Identifier: Apache-2.0
5:  */
6: var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
                            ^
7:     var useValue = arguments.length > 2;
8:     for (var i = 0; i < initializers.length; i++) {
...and 3 other occurrences

...and 28 other files
created out in 493ms
```

I think those warnings are not causing any issues.

**Comment by OrKoN** [comment]
@elineeen could you perhaps create a demo project on GitHub with your configuration and the bundler so that we could try it out?

**Comment by elineeen** [comment]
@OrKoN sure, i've created a [demo ](https://github.com/elineeen/pptr-ext-demo)project  ,try it with node v18.17.0

**Comment by OrKoN** [comment]
So it looks like vite does not allow restricting the module resolution to the provided list (our example only allows 'puppeteer-core' and not other modules). In general, externalizing those dependencies should be alright since they are for Node only and only loaded dynamically if Puppeteer runs in Node. Is there a way to configure Vite to not resolve and bundle dynamically imported modules?

**Comment by OrKoN** [comment]
I think we could improve on Puppeteer side to not require so much customization.

**Comment by OrKoN** [comment]
This is now addressed. There is only one warning left:

```
[plugin:vite:resolve] [plugin vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/Users/alex/projects/pptr-test/pptr-ext-demo/node_modules/chromium-bidi/lib/cjs/utils/uuid.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

but that is fine since this is optional if the browser support is not detected. Unfortunately, build tools are not able to detect that.
