### ISSUE TITLE
[Bug]: Page.evaluateOnNewDocument is not evaluated in OOPIFs

### ISSUE THREAD

**Issue by liamdalg** [puppeteer/puppeteer#12706]
### Minimal, reproducible example

```TypeScript
import puppeteer, { CDPSession } from "puppeteer";

const browser = await puppeteer.launch({
  debuggingPort: 9222,
});
const context = await browser.createBrowserContext();
const page = await context.newPage();
const client = (page as any)._client() as CDPSession;

await page.evaluateOnNewDocument(() => {
  globalThis.foo = "bar";
});

await page.goto("http://localhost:8000/iframe.html");

for (const frame of page.frames()) {
  console.log(`Evaluating in ${frame.name() || "parent"}`);
  const result = await frame.evaluate(() => globalThis.foo);
  console.log(result);
}

browser.close();
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Example HTML:

```html
<!-- iframe.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <iframe name="inner" src="http://127.0.0.1:8000/blank.html"></iframe>
</body>
</html>

<!-- blank.html is just an empty file-->
```

`evaluateOnNewDocument` doesn't work for OOPIFs, I assume because you'd need to call `Page.addScriptToEvaluateOnNewDocument` on the new CDP session. If I swap `127.0.0.1` to `localhost` or turn off `SitePerProcess` (so the iframe is no longer an OOPIF), then it works.

I can get it to work if I do something sketchy like:
```ts
const client = (page as any)._client() as CDPSession;

client.on("sessionattached", async (f) => {
  await f.send("Page.addScriptToEvaluateOnNewDocument", {
    source: "globalThis.foo = 'bar'",
    runImmediately: true,
  });
});
```
but obviously this isn't very nice.

### Expectation

Print `bar` both for the `parent` and `inner` frames.

```
Evaluating in parent
bar
Evaluating in inner
bar
```

### Reality

```
Evaluating in parent
bar
Evaluating in inner
undefined
```

### Puppeteer version

22.12.1

### Node version

22.3.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Linux

**Comment by OrKoN** [comment]
https://github.com/puppeteer/puppeteer/issues/10017 is also about this problem

**Comment by OrKoN** [comment]
Note that it would probably work over WebDriver BiDi protocol.
