### ISSUE TITLE
[Bug]: Buffer is not defined while using request.respond in chrome extension(using pptr-core)

### ISSUE THREAD

**Issue by elineeen** [puppeteer/puppeteer#12700]
### Minimal, reproducible example

```TypeScript
cmdPage.on('request', interceptedRequest => {
		if (interceptedRequest.url().indexOf('main.js') > 0) {
			interceptedRequest.respond({
				body: mainReplacerFile,
			})
		} else
			interceptedRequest.continue()
	})
```

### Error string

Uncaught (in promise) ReferenceError: Buffer is not defined

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

Works fine with req.conitnue api but stucked on respond lol. Hope for supporting

### Reality

![image](https://github.com/puppeteer/puppeteer/assets/61259088/c769e6c5-21c3-48a0-9af3-2739f5fc856d)

### Puppeteer version

22.12.1

### Node version

18.17.0

### Package manager

yarn

### Package manager version

3.6.1

### Operating system

Windows

**Comment by OrKoN** [comment]
@Lightning00Blade do you know if we can rewrite without using the Buffer API?

**Comment by Lightning00Blade** [comment]
We should be able to move to `Uint8Array` as it will not be a breaking change `interface Buffer extends Uint8Array` 
And `Uint8Array` is supported in the browser.

**Comment by OrKoN** [comment]
As a workaround, it should be possible to include https://github.com/feross/buffer into your build.
