### ISSUE TITLE
[Bug]: Page.screenshot() can time out with `headless: true` and `protocol: 'cdp'` 

### ISSUE THREAD

**Issue by lPernod-sorare** [puppeteer/puppeteer#12712]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
  let browser = await puppeteer.launch({
    protocolTimeout: 180_000,
    headless: true,
    protocol: "cdp",
  });

  const page1 = await browser.newPage();
  const page2 = await browser.newPage();

  console.time("screenshot1");
  const screen1 = page1.screenshot();
  const screen2 = page2.screenshot();

  const close1 = screen1.then(() => page1.close());
  const close2 = screen2.then(() => page2.close());
  await screen1;
  const page3 = await browser.newPage();
  await page3.screenshot(); // Times out
  const close3 = page3.close();

  Promise.all([close1, close2, close3]).then(() => browser.close());
})();
```

### Error string

ProtocolError: Page.captureScreenshot timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been trying to generate screenshots of pages using puppeteer. We're getting protocol timeouts for page.screenshot for a small number of requests.

While investigating, I found a minimal script that reproduces the issue almost all of the time.

Any  of the following changes to the code cause the problem to disappear:
- `protocol: 'webDriverBiDi'`
- `headless: 'shell'`
- Removing page2, screen2 and close2

Setting `pipe: true` does not resolve the issue.

I've been able to reproduce this issue for many large and small values of protocolTimeout, setting it to 3_000 means the script fails faster. (screenshots usually take ~200ms locally).

### Expectation

I expected page3.screenshot() to resolve in a similar duration to most other calls (<200ms).

### Reality

In reality, it rejects with `ProtocolError: Page.captureScreenshot timed out` even for very large values of `protocolTimeout`(3 minutes). 

I've also been able to reproduce this issue in puppeteer 19.11.1, 20.9.0 and 21.11.0 by making the following changes to the script (to fix api differences in versions before 22):
- removing protocol (as this is 'cdp' by default)
- setting headless: 'new' (equivalent to headless: true in puppeteer 22).

### Puppeteer version

22.12.1

### Node version

22.4.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

macOS

**Comment by OrKoN** [comment]
Inactive tabs in the browser might not get rendered producing no rendered frames to capture a screenshot with. In 'shell' works because it is not matching the behavior of the real browser. The WebDriver BiDi protocol works because it explicitly switches the focus for the tab https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiMapper/modules/context/BrowsingContextImpl.ts#L963 That might be still unreliable if the pages are opened/closed and screenshotted in parallel. In CDP, you need to do it on your own by calling `await page.bringToFront()`. In general, regular Chrome can only take a PDF or a screenshot the active tab. If you need the parallel execution, you should be using the chrome headless shell. The root cause for this behavior is in the browser's throttling behavior and I am not sure there is a good solution there.

**Comment by OrKoN** [comment]
related https://github.com/puppeteer/puppeteer/issues/12598 (`documents.fonts.ready` does not resolve in background tabs because the tab rendering is paused)

**Comment by OrKoN** [comment]
```
import puppeteer from "puppeteer";

(async () => {
  let browser = await puppeteer.launch({
    protocolTimeout:3_000,
    headless: true,
    protocol: "cdp",
  });

  const page1 = await browser.newPage();
  const page2 = await browser.newPage();

  console.time("screenshot1");
  await page1.bringToFront();
  const screen1 = await page1.screenshot();
  await page2.bringToFront();
  const screen2 = await page2.screenshot();

  const page3 = await browser.newPage();
  await page3.bringToFront();
  await page3.screenshot(); // does not time out
  await browser.close()
})();
```

this is a more reliable pattern for taking screenshots with Chrome.

**Comment by lPernod-sorare** [comment]
I'm surprised that it's necessary to call `page.bringToFront()` as that is called by puppeteer itself from when calling screenshot:
https://github.com/puppeteer/puppeteer/blob/0f98b1459bc357c883a74d09baa7aa50ac3fc340/packages/puppeteer-core/src/api/Page.ts#L2485

When debugging the reproduction code with CDP messages by running with `DEBUG="puppeteer:protocol:*" node repro.js`:

```
…
2024-07-05T17:39:30.759Z puppeteer:protocol:SEND ► [ '{"method":"Page.bringToFront","id":16,"sessionId":"C525180D89763B0AA15AA38509E502A3"}' ]
2024-07-05T17:39:30.759Z puppeteer:protocol:SEND ► [ '{"method":"Target.closeTarget","params":{"targetId":"96D2FE27D8FE60EB9D4A41BC18E5949E"},"id":5}' ]
2024-07-05T17:39:30.759Z puppeteer:protocol:SEND ► [ '{"method":"Target.createTarget","params":{"url":"about:blank"},"id":6}' ]
2024-07-05T17:39:30.761Z puppeteer:protocol:RECV ◀ [ '{"id":16,"result":{},"sessionId":"C525180D89763B0AA15AA38509E502A3"}' ]
2024-07-05T17:39:30.761Z puppeteer:protocol:SEND ► [ '{"method":"Page.captureScreenshot","params":{"format":"png","captureBeyondViewport":false},"id":17,"sessionId":"C525180D89763B0AA15AA38509E502A3"}' ]
…
```

There are no devtools messages between the return of Page.bringToFront on `C525180D89763B0AA15AA38509E502A3` and Page.captureScreenshot on `C525180D89763B0AA15AA38509E502A3`, but that call still rejects with a timeoutError.

Therefore, it seems that calling Target.closeTarget / Target.createTarget between calling bringToFront and screenshot is an issue.

---

In the real world scenario, pages are being opened and screenshotted in a request listener of a http server (with some queueing to avoid opening too many pages at the same time).

That causes puppeteer to have a similar CDP trace as that shown in the minimal reproduction and the same result, but the minimal reproduction is more consistent in rejecting with this error.

**Comment by OrKoN** [comment]
@lPernod-sorare so if a tab/target gets closed, another tab gets activated, there is a race condition here (session C525180D89763B0AA15AA38509E502A3 is focused, targetId closes 96D2FE27D8FE60EB9D4A41BC18E5949E, probably activating the next tab that is not C525180D89763B0AA15AA38509E502A3, captureScreenshot for C525180D89763B0AA15AA38509E502A3 waits for the tab to become active).  I'd recommend using the headless shell if you use case is not about testing the behavior of the pages in the background in regular Chrome. 

>  I'm surprised that it's necessary to call page.bringToFront() as that is called by puppeteer itself from when calling screenshot:

you are right, I forgot that it is called there already (I think that was not always the case) 😅 What ultimately matters if the active tab state that should not be changes while the screenshot is running.

**Comment by OrKoN** [comment]
we should implement internal locking mechanism to ensure that at least tab activation changes are not happening during screenshot/pdf operations (probably as an opt-int).

**Comment by lPernod-sorare** [comment]
> That might be still unreliable if the pages are opened/closed and screenshotted in parallel.

As parallel screenshotting works in headless: 'shell', which was the default until Puppeteer 22 ([PR](https://github.com/puppeteer/puppeteer/pull/11815)) would it be worth it to add an information message on https://pptr.dev/api/puppeteer.page.screenshot to call out parallel screenshots / page opening and closing when running new headless mode ? (which could link to internal locking mechanism opt-in once ready)

We've worked around the issue for our use case by avoiding parallel page openings, closings and screenshots for the moment.
