### ISSUE TITLE
[Bug]: page.setCookie() Error

### ISSUE THREAD

**Issue by Pjrogu224** [puppeteer/puppeteer#12720]
### Steps to reproduce

const browser = await puppeteer.launch();
const url = 'https://example.com';
const page = await browser.newPage();
const cookies = [{
  'name': 'cookie1',
  'value': 'val1'
},{
  'name': 'cookie2',
  'value': 'val2'
},{
  'name': 'cookie3',
  'value': 'val3'
}];

await page.setCookie(...cookies);

### Expected results

Set Cookie

### Actual results

run failed ProtocolError: Protocol error (Network.deleteCookies): Overriding cookie1 cookie is forbidden

**Comment by OrKoN** [comment]
One problem might be that you try to set cookies on the about:blank page. Perhaps you could try navigating to the url first or provide the url/domain for the cookies. 

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
const url = 'https://example.com';
const page = await browser.newPage();

await page.goto(url);

const cookies = [{
'name': 'cookie1',
'value': 'val1'
},{
'name': 'cookie2',
'value': 'val2'
},{
'name': 'cookie3',
'value': 'val3'
}];

await page.setCookie(...cookies);
```

In general, I am not able to reproduce the reported error. Please use this template to provide all information necessary to reproduce the issue https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%5BBug%5D%3A+
