### ISSUE TITLE
[Bug]: This problem occurs in 21.12.1

### ISSUE THREAD

**Issue by Genius-ycwei** [puppeteer/puppeteer#12733]
### Minimal, reproducible example

```TypeScript
none
```

### Error string

none

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

<img width="1335" alt="image" src="https://github.com/puppeteer/puppeteer/assets/71883273/94e08289-3483-4e94-9eb5-ccd493eecbca">

### Reality

none

### Puppeteer version

22.12.1

### Node version

18.16.0

### Package manager

npm

### Package manager version

6.14.10

### Operating system

macOS

**Comment by OrKoN** [comment]
Please update the bug report to include a minimal reproducible example.

**Comment by Genius-ycwei** [comment]
<img width="636" alt="image" src="https://github.com/puppeteer/puppeteer/assets/71883273/30645983-2ee2-47fa-89dd-1737a462b9cf">
No error reports, all builds are successful.
