### ISSUE TITLE
[Bug]: bookmarking a page crashes puppeteer browser

### ISSUE THREAD

**Issue by seoular** [puppeteer/puppeteer#12747]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch()


Clicking add bookmark in chrome crashes the puppeteer browser
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

I expected to be able to add bookmarks to my chrome profile.

### Reality

Chrome puppeteer browser crashes.

### Puppeteer version

22.13.0

### Node version

20.15.1

### Package manager

npm

### Package manager version

10.7.0

### Operating system

Windows

**Comment by OrKoN** [comment]
I am able to reproduce in stable but not with the Canary version. It likely indicates that the crash has been fixed in Chromium. The crash ID is 92bdba70fa8e4ef4.

**Comment by OrKoN** [comment]
There is already a bug report for it https://crbug.com/349411316

**Comment by seoular** [comment]
> There is already a bug report for it https://crbug.com/349411316

for some reason i can see the other bug reports but i dont have access to this one

**Comment by OrKoN** [comment]
it's a crash so the access is restricted. The owner reported that it will be fixed in Chrome 128.

**Comment by Lightning00Blade** [comment]
Closing as the latest version of Puppeteer ships with [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) 128.0.6613.84
