### ISSUE TITLE
page.select() should error if it can't find an option with requested value

### ISSUE THREAD

**Issue by jbr** [puppeteer/puppeteer#1276]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13-alpha
* Platform / OS version: macos

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
html:
```html
<html><body><select><option value="12"/></select></body</html>
```
puppeteer:
```js
page.select('select', 12)
```

**What is the expected result?**

Either select the option with the value that is string-equal to the second arg (0.12 behavior) OR throw an error when page.select cannot find a matching option.  The latter solution seems more generally useful.

**What happens instead?**
Select is blanked, no error is thrown

**Comment by aslushnikov** [comment]
@jbr `page.select` returns an array of selected options. You can inspect it to see if the value was actually selected.

**Comment by jbr** [comment]
@aslushnikov Understood.  Why not warn on invalid arguments, though, if numbers aren't coerced to strings?

**Comment by aslushnikov** [comment]
@jbr good call.

Let me convert arguments to strings.
