### ISSUE TITLE
[Docs]: Update FAQ page for Puppeteer v23

### ISSUE THREAD

**Issue by matthiasrohmer** [puppeteer/puppeteer#12769]
### Feature description

Related to https://github.com/puppeteer/puppeteer/issues/12728.

The FAQ page mentions experimental support for both BiDi and Firefox and needs to be updated with v23, ideally also answering the question where CDP will go (Answer: nowhere, things will continue as is).

**Comment by matthiasrohmer** [comment]
Happy to take this once I am back on July 29!

**Comment by OrKoN** [comment]
Thanks, I have added it to the TODO list.
