### ISSUE TITLE
[Bug]: Fetch headers are not being set

### ISSUE THREAD

**Issue by FightRay** [puppeteer/puppeteer#12762]
### Minimal, reproducible example

Fetch requests executed inside page.evaluate do not send the headers passed.
The method and body values are sent accordingly, just not the headers.

```TypeScript
const puppeteer = require("puppeteer");
const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.goto("https://httpbin.org/");

const response = await page.evaluate(async (url, options) => {
    return await fetch(url, {
        method: "POST",
        headers: {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Cookie": "somecookie=340fefe0oef03;"
        },
        body: "[]"
    );
}, "https://httpbin.org/post", {});

// httpbin will return us the headers from our request (they are not set!)
console.log(response);

```
Upon inspecting the page on the network tab as well, you can see the POST request's specified headers are not set in the request headers.
(Some other defaults are set for Accept and Content-Type, and the Cookie header is not set at all)

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

It's important to be able to set a request's headers, as they could malfunction or be rejected otherwise.
In my case, puppeteer is useless without being able to set a fetch request's headers.

### Expectation

I expect the headers passed to the fetch call to be set in the request.

### Reality

The passed headers (Accept, Content-Type and Cookie) are not being set, and the browser's default headers are sent instead. (completely ignoring the page's cookies/cache as well)

### Puppeteer version

22.13.0

### Node version

20.15.0

### Package manager

npm

### Package manager version

10.7.0

### Operating system

Windows

**Comment by FightRay** [comment]
Nevermind, just add 
```typescript
credentials: "include"
```
After body in the fetch call to fix this.

**Comment by jseb16** [comment]
FIghtRay, found your most recent activity. Remember me? Message me bro, been looking for you.
