### ISSUE TITLE
[Bug]: Trying to access response.status() right after the navigation can cause a TypeError "Cannot read properties of null (reading 'status')"

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#12773]
### Minimal, reproducible example

```TypeScript
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    protocol: 'webDriverBiDi',
    headless: false,
  });

  const page = await browser.newPage();

  await page.setRequestInterception(true);
  page.on('request', async request => {
    request.continue();
  });

  const response = await page.goto(`https://developer.mozilla.org/en-US/`);
  console.log(`status=${response.status()}`);

  await browser.close();
})();
```

### Expectation

That the returned `response` object is valid and properties can be accessed.

### Reality

The `response` is undefined unless `await` is used in the interception handler for `request.continue()`. Note that all [Puppeteer docs](https://pptr.dev/api/puppeteer.httprequest.continue#example) do not list `await` and when using Firefox it also works with out `await`.

### Puppeteer version

22.13.1

### Node version

22.2.0

### Package manager

npm

### Package manager version

10.7.0

### Operating system

macOS

**Comment by whimboo** [comment]
@OrKoN can you please take a look?

**Comment by whimboo** [comment]
So `request.continue()` returns a Promise. As such I would expect that using `await` would wait for it. But actually it is not working for Chrome even when I've mentioned it before. Not making the callback an async function fixes the problem.

**Comment by whimboo** [comment]
Note that this also fails with the CDP protocol enabled.

**Comment by OrKoN** [comment]
@whimboo It does not fail with CDP for me. It seems that it might be the issue of early navigate returns since there are some fragment navigations happening on that page. It seems to work with https://wikipedia.org

**Comment by OrKoN** [comment]
I think it make it consistent we would need to land https://github.com/puppeteer/puppeteer/pull/11929 but it had some blockers on both chromium-bidi and Firefox side.

**Comment by whimboo** [comment]
I see. So we probably should get this fixed as part of the next chunk of work.

For my cross-browser example script I can actually use `https://addons.mozilla.org` which works fine as well.

**Comment by OrKoN** [comment]
Looking at this more, it is actually more of the opposite case, the fragment navigated is received right after the real navigation. So there are probably two issues:

1) In Puppeteer, we wait for the latest navigation so need to unblock improvements like https://github.com/puppeteer/puppeteer/pull/11929
2) In chromium-bidi, the history update counts as a fragment navigated, and it looks Firefox is correctly not sending it, that is why it works.

**Comment by whimboo** [comment]
So we first need https://github.com/w3c/webdriver-bidi/pull/740 and then chromium-bidi needs to be updated to emit the new event instead.

**Comment by OrKoN** [comment]
Right, for now, I think we can deprioritze and document this edge case since our API allows returning null for some cases so technically one needs to check if the result is null.

**Comment by OrKoN** [comment]
@whimboo did you investigate how exactly the page is redirecting after the initial navigation? I assume it is via history but after the discussion on Matrix is looks like there could be multiple redirects. I want to add a test for this situation.

**Comment by OrKoN** [comment]
I see the event `'{"type":"event","method":"browsingContext.fragmentNavigated","params":{"context":"092346F42BC26DAB7C323B73DA892FC7","navigation":"ce26eab6-c710-4793-b248-5dd444803907","timestamp":1721290646618,"url":"https://developer.mozilla.org/en-US/"}}'` which could be either a fragment navigation or a history update

**Comment by OrKoN** [comment]
The historyUpdated event would have been really useful, and maybe we need to attach a stack trace to it 😅

**Comment by OrKoN** [comment]
Interestingly, if I open with DevTools on, there are no same document navigations and the script succeeds.

**Comment by whimboo** [comment]
When I use Firefox with `MOZ_LOG="BCWebProgress:5"` logging enabled I can see:

```
[Parent 30551: Main Thread]: I/BCWebProgress OnLocationChange({isTopLevel:1, isLoadingDocument:1}, <null>, https://developer.mozilla.org/en-US/, LOCATION_CHANGE_SAME_DOCUMENT) on {top:1, id:d, url:https://developer.mozilla.org/en-US/}
```

So this looks like some history API usage given that no `HASH_CHANGE` flag is set. Note that we do not yet have a flag or history API usage but would consider adding one once the required HTML spec changes are done.

**Comment by OrKoN** [comment]
@whimboo could you find where it is coming from on the site?

**Comment by OrKoN** [comment]
I am not able to reproduce with replaceState or pushState in atest.

**Comment by OrKoN** [comment]
<img width="1470" alt="Screenshot 2024-07-18 at 10 51 08" src="https://github.com/user-attachments/assets/d34bef50-27c0-4b0a-8d07-145675109d5b">

found where it is coming from, it seems to call replace state multiple times.

**Comment by OrKoN** [comment]
I am still not able to replicate it in the test :/

**Comment by whimboo** [comment]
When I set breakpoints to those two `replaceState` calls the debugger never pauses. Only for the one entry in main.js it sometimes pauses. @jdescottes will have a closer look given that he is more familiar with the DevTools features.

**Comment by juliandescottes** [comment]
As far as I can tell, the calls are all coming from [react-router](https://github.com/remix-run/react-router). FWIW, I can also replicate the issue when testing with Chrome, I think I am testing with the regular Chrome release. @OrKoN are you testing on a specific channel ? Is the test passing successfully for you on Chrome?

**Comment by OrKoN** [comment]
I am testing with stable and I am able to reproduce the issue with Chrome on the live website but not in a test: https://github.com/puppeteer/puppeteer/pull/12777

**Comment by OrKoN** [comment]
I was able to reproduce if I would wait for network idle and not only the load event.
