### ISSUE TITLE
[Bug]: ProtocolError X timed out.

### ISSUE THREAD

**Issue by kozak** [puppeteer/puppeteer#12780]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; 

const browser = await puppeteer.launch({
    args: [
      "--no-sandbox",
      "--headless",
    ],
    dumpio: true
});

  
const page = await browser.newPage();

await page.goto("about:blank")

await browser.close();
```

### Background

Some of our developers have issues when puppeteer browser is started and used from a docker container.  

Browser version tested: `Chrome 126.0.6478.126` and `126.0.6478.182`.   Seems to happen both in `headless: true` and in `headless: 'shell'`. 

Puppeteer was also tested with: `22.12.1` and `22.13.1`

Debug log: 
[puplog.txt](https://github.com/user-attachments/files/16283085/puplog.txt)

Starting the `dbus` daemon gets rid of the warnings, but doesn't fix the issue. 

### Expectation

This should launch the browser, open the blank page and close the browser. 

### Reality

For some developers, this fails with: ProtocolTimeout, see the puplog.txt for details. 

### Puppeteer version

22.12.1

### Node version

20.14.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

Linux

**Comment by OrKoN** [comment]
I am not able to reproduce on either Linux or MacOS. Do you have [required system dependencies](https://pptr.dev/guides/system-requirements) installed? Can you reproduce using our Docker image https://pptr.dev/guides/docker ?

**Comment by mkj80** [comment]
Please resend I didn't know that was supposed to do this I'm sorry what do
I need to do

**Comment by kozak** [comment]
I think this can be closed, it turned out to be an issue with a VScode extension. @Aegonek will provide more details if he will find the time. Thanks for looking into this.
