### ISSUE TITLE
"page.setCookie" fails when using "partitionKey" field in cookie: "Invalid parameters Failed to deserialize params.cookies.partitionKey"

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#12787]
The following script always fails with Chrome and not Firefox when using the `partitionKey` field for a cookie that gets set via `page.setCookie`:

```
    'use strict';
    ​
    const puppeteer = require('puppeteer');
    ​
    (async () => {
      const browser = await puppeteer.launch({
        protocol: 'webDriverBiDi',
      });
    ​
      const page = await browser.newPage();
    ​
      const domain = "addons.mozilla.org";
      const cookie = { name: "John", value: "42", domain, partitionKey: `https://${domain}` };
      await page.setCookie(cookie);
    ​
      await browser.close();
    })();
```

The failure is:

```
ProtocolError: Protocol error (storage.setCookie): unable to set cookie ProtocolError: Protocol error (Storage.setCookies): Invalid parameters Failed to deserialize params.cookies.partitionKey - BINDINGS: string value expected at position 115
```

Here an excerpt from the debug log of Puppeteer:

```
  puppeteer:webDriverBiDi:SEND ►   '{"id":10,"method":"storage.setCookie","params":{"cookie":{"domain":"addons.mozilla.org","name":"John","value":{"type":"string","value":"42"}},"partition":{"type":"storageKey","sourceOrigin":"https://addons.mozilla.org","userContext":"default"}}}'
  puppeteer:webDriverBiDi:SEND ► ] +0ms
  puppeteer:protocol:SEND ► [
  puppeteer:protocol:SEND ►   '{"method":"Storage.setCookies","params":{"cookies":[{"name":"John","value":"42","domain":"addons.mozilla.org","path":"/","secure":false,"httpOnly":false,"partitionKey":{"hasCrossSiteAncestor":false,"topLevelSite":"https://addons.mozilla.org"}}]},"id":9}'
  puppeteer:protocol:SEND ► ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"id":9,"error":{"code":-32602,"message":"Invalid parameters","data":"Failed to deserialize params.cookies.partitionKey - BINDINGS: string value expected at position 115"}}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:webDriverBiDi:RECV ◀ [
  puppeteer:webDriverBiDi:RECV ◀   '{"type":"error","id":10,"error":"unable to set cookie","message":"ProtocolError: Protocol error (Storage.setCookies): Invalid parameters Failed to deserialize params.cookies.partitionKey - BINDINGS: string value expected at position 115"}'
```

At least the BiDi command looks fine to me.

@OrKoN can you please check? Thanks.

**Comment by OrKoN** [comment]
@sadym-chromium could you please take a look?

**Comment by goleary** [comment]
Is anyone aware of any workarounds for this?

This took down one of our services today and the fact that google doesn't host old stable releases is making this a rather large PITA.

**Comment by OrKoN** [comment]
@goleary Puppeteer does not support M127 yet. You will need to wait until a new Puppeteer release is out that we tested with M127.

**Comment by OrKoN** [comment]
So in this example, Chrome actually requires the cookie to have `secure: true` and would reject storing the cookie if it is not secure.

**Comment by nonstopdevelopment** [comment]
Same issue. No issues on any site until the partitionKey is set in the cookies that gets loaded and error happens.

**Comment by OrKoN** [comment]
@marios88 @nonstopdevelopment are you using WebDriver BiDi? if not, it is not the same issue.

**Comment by nonstopdevelopment** [comment]
Have tried the example as well as the standard dev tools and same issue using the example and our own test cases trying to load cookies with partitionKey

`ProtocolError: Protocol error (Network.deleteCookies): Invalid parameters Failed to deserialize params.partitionKey - CBOR: map start expected at position 66`

**Comment by sadym-chromium** [comment]
@OrKoN reassigning to you, as you already on it. Feel free to reassign back, if you want to hand it over to me

**Comment by OrKoN** [comment]
Adding secure: true makes the example work in Chrome. Therefore, closing the issue.

**Comment by JackyBoy666** [comment]
I have this issue awell, using chrome, and cookie already has secure: true.
params.partitionKey - CBOR: map start expected at position 336
