### ISSUE TITLE
inconsistent navigation timeouts when running 10 pages in parallel

### ISSUE THREAD

**Issue by skunkwerk** [puppeteer/puppeteer#1279]
When I run this script multiple times, I always get navigation timeouts - but never the same number, or for the same sites.  What could be wrong?

Version: 0.12.0
OS: Mac OS X 10.13

Code to reproduce:

const puppeteer = require('puppeteer')
async function test()
{
	const browser = await puppeteer.launch();
	
	var sites = ['http://bbcnews.com','http://yahoo.com','http://cnn.com','http://quora.com','http://imgur.com','http://youtube.com','http://azure.com','http://kayak.com','http://medium.com','http://reddit.com'];

	var requests = [];
	for (let site of sites)
        {
		requests.push(run(browser, site))
	}
	results = await Promise.all(requests);
}

async function run(browser, site)
{
	try
	{
		var page = await browser.newPage();
		await page.goto(site, {});
		await page.close();
		console.log('done' + site)
		}
	catch (err) 
  	{
    	console.log(err)
    	return null;
  	}
}

test().catch(console.error.bind(console))

**Comment by vsemozhetbyt** [comment]
I cannot reproduce on Windows 7 x64  with the v0.13.0-alpha and this (slightly reformatted) code:
<details>
<summary>Code:</summary>

```js
'use strict';

const puppeteer = require('puppeteer');

async function test() {
  const browser = await puppeteer.launch();

  const sites = [
    'http://bbcnews.com',
    'http://yahoo.com',
    'http://cnn.com',
    'http://quora.com',
    'http://imgur.com',
    'http://youtube.com',
    'http://azure.com',
    'http://kayak.com',
    'http://medium.com',
    'http://reddit.com',
  ];

  const requests = [];
  for (const site of sites) {
    requests.push(run(browser, site));
  }
  const results = await Promise.all(requests);
}

async function run(browser, site) {
  try {
    const page = await browser.newPage();
    await page.goto(site, {});
    await page.close();
    console.log('done ' + site);
  } catch (err) {
    console.log(err);
    return null;
  }
}

test().catch(console.error.bind(console));
```
</details><br>

**Comment by GautierT** [comment]
Probably related to #1211.
(I still have to make a small repro.)
I think it's a memory issue (heroku - RAM : 512mb) because i can't repro this on local (osx - 10.11.6 - RAM : 8gb)

**Comment by aslushnikov** [comment]
If there's a good repro, please contribute one to the #1211 so that we have something to work with.

Overall, looks like a memory issue.
