### ISSUE TITLE
[Bug]: Failed to launch the browser process!

### ISSUE THREAD

**Issue by imzayedd** [puppeteer/puppeteer#12805]
### Steps to reproduce

const express = require('express');
const puppeteer = require('puppeteer');
const app = express();

app.get('/fetch-content', async (req, res) => {
  const url = req.query.url;
  if (!url) {
    return res.status(400).send('URL parameter is required');
  }

  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto(url, { waitUntil: 'networkidle2' });
    const content = await page.content();
    await browser.close();
    res.send(content);
  } catch (error) {
    console.error(error);
    res.status(500).send('Error fetching content');
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});

### Expected results

The webpage fetches and loads.

### Actual results

Error: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-126.0.6478.182/chrome-linux64/chrome: 1: Syntax error: ")" unexpected

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/home/zayed/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by OrKoN** [comment]
Are you on an arm64 linux? Puppeteer does not support arm64 linux because arm64 builds of Chrome are not available:

1) https://pptr.dev/guides/system-requirements
2) https://github.com/puppeteer/puppeteer/issues/7740
