### ISSUE TITLE
[Bug]: api.js:110 Error details: {"error":"Internal Server Error","details":"Failed to launch the browser process!\n/root/frontendiffusion/backend/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: symbol lookup error: /root/frontendiffusion/backend/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: undefined symbol: snd_device_name_get_hint, version ALSA_0.9\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"}

### ISSUE THREAD

**Issue by Carolzhangzz** [puppeteer/puppeteer#12809]
### Steps to reproduce

I am using an Amazon EC2 instance and Nginx to host my backend application, but while I run the app in the browser, I met a error : 
api.js:110 Error details: {"error":"Internal Server Error","details":"Failed to launch the browser process!\n/root/frontendiffusion/backend/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: symbol lookup error: /root/frontendiffusion/backend/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: undefined symbol: snd_device_name_get_hint, version ALSA_0.9\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"}
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/577742bf-46e7-4556-8fef-cdf29b555955">

### Expected results

API call successfully 

### Actual results

api.js:110 Error details: {"error":"Internal Server Error","details":"Failed to launch the browser process!\n/root/frontendiffusion/backend/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: symbol lookup error: /root/frontendiffusion/backend/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: undefined symbol: snd_device_name_get_hint, version ALSA_0.9\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"}

**Comment by John251314** [comment]
I have same issues, ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20240701.1

**Comment by smartITNinja** [comment]
This workaround worked for me: 

1.- sudo apt-get install libnss3-dev
2.- sudo apt-get install -y libasound2t64 libatk1.0-0t64 libc6 libcairo2 libcups2t64 libdbus-1-3 libexpat1 libfontconfig1 libgcc-s1 libgdk-pixbuf2.0-0 libglib2.0-0t64 libgtk-3-0t64 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget libgbm-dev
3.- in your JS code: 
`const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox']});`

**Comment by kk412027247** [comment]
> This workaround worked for me:
> 
> 1.- sudo apt-get install libnss3-dev 2.- sudo apt-get install -y libasound2t64 libatk1.0-0t64 libc6 libcairo2 libcups2t64 libdbus-1-3 libexpat1 libfontconfig1 libgcc-s1 libgdk-pixbuf2.0-0 libglib2.0-0t64 libgtk-3-0t64 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget libgbm-dev 3.- in your JS code: `const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox']});`
> 
> If you don't want to use the --no-sandbox flag, then this workaround will work: 1.- apt-get install chromium-browser 2.- In your code:
> 
> ```
> const browser = await puppeteer.launch({
>     executablePath: '/usr/bin/chromium-browser'
>   });
> ```
thank thank big bro. It works.

**Comment by Carolzhangzz** [comment]
Thank you !
This Works !

smartITNinja ***@***.***> 于2024年9月2日周一 10:01写道：

**Comment by trexshw** [comment]
> This workaround worked for me:
> 
> 1.- sudo apt-get install libnss3-dev 2.- sudo apt-get install -y libasound2t64 libatk1.0-0t64 libc6 libcairo2 libcups2t64 libdbus-1-3 libexpat1 libfontconfig1 libgcc-s1 libgdk-pixbuf2.0-0 libglib2.0-0t64 libgtk-3-0t64 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget libgbm-dev 3.- in your JS code: `const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox']});`
> 
> If you don't want to use the --no-sandbox flag, then this workaround will work: 1.- apt-get install chromium-browser 2.- In your code:
> 
> ```
> const browser = await puppeteer.launch({
>     executablePath: '/usr/bin/chromium-browser'
>   });
> ```

Thanks!
This works for me in Ubuntu 24.04
