### ISSUE TITLE
os.homedir() results in different path depending on invocation (Windows)

### ISSUE THREAD

**Issue by DanielRuf** [puppeteer/puppeteer#12803]
`os.homedir()` on Windows checks for specific environment variables before falling back to the logic used on other OSes.

I think `os.userInfo().homedir` makes more sense. See also https://github.com/nodejs/node/issues/5582

**Comment by Lightning00Blade** [comment]
Note: User can currently achieve this behavior currently with using a [Configuration file](https://pptr.dev/guides/configuration):
```js
const {join} = require('path');
const {userInfo} = require('os');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(userInfo().homedir, '.cache', 'puppeteer'),
};
```
