### ISSUE TITLE
[Bug]: after updating puppeteer from 22.6.0 to version 22.13.1, render method is getting failed with Error: Report timeout. Last profiler operation: (recipe) chrome-pdf.

### ISSUE THREAD

**Issue by nisarga0101** [puppeteer/puppeteer#12826]
### Minimal, reproducible example

```TypeScript
async generateReport() {
        try {
            await this.jsreport.init();

            const response = await this.jsreport.render({
                template: {
                    content: '<h1>Hello, {{name}}!</h1>',
                    engine: 'handlebars',
                    recipe: 'chrome-pdf'
                },
                data: {
                    name: 'John Doe'
                }
            });

            const buffer = Buffer.from(response.content, 'base64');
            // Save or send the buffer as needed
            console.log('Report generated successfully.');
        } catch (error) {
            console.error('Failed to generate report:', error);
        } finally {
            await this.jsreport.close();
        }
    }
```

### Background

after updating puppeteer to version 22.13.1 , render method is getting failed with error **"Report render failed
(because) report timeout. Last profiler operation: (recipe) chrome-pdf
Error: Report timeout. Last profiler operation: (recipe) chrome-pdf"**

and I am not seeing this issue for puppeteer versions up to 22.8.2, if I update puppeteer above 22.8.2 getting above error

Packages used : 
"@jsreport/jsreport-chrome-pdf": "4.1.0",
  "@jsreport/jsreport-core": "4.4.0",
 "@jsreport/jsreport-handlebars": "4.0.1",

### Expectation

report creation should works fine using @jsreport-core using puppeteer version 22.13.1

### Reality

![image](https://github.com/user-attachments/assets/df29c439-49a1-47e3-8d5c-ce69f2cb13c3)
report creation is failing at render()

### Puppeteer configuration file (if used)

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer-core").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname,'node_modules', '.cache', 'puppeteer'),
};
```

### Puppeteer version

22.13.1

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

Windows

**Comment by OrKoN** [comment]
It might be this issue https://github.com/puppeteer/puppeteer/issues/12471 but better report it to the jsreport project.

**Comment by nisarga0101** [comment]
Hi @OrKoN ,

I’m encountering a problem with report creation in Puppeteer versions 22.9.0 and later. Everything works fine with Puppeteer version 22.8.2. I’ve tried both keeping @jsreport/jsreport-core at older versions and upgrading it to the latest, but the issue persists.

Has anyone else faced similar issues or found a solution? Any guidance on this issue.

Thanks in advance!
