### ISSUE TITLE
[Bug]: v22.14.0 can not starting

### ISSUE THREAD

**Issue by hashimoto-AJ** [puppeteer/puppeteer#12829]
### Minimal, reproducible example

```TypeScript
v22.14.0 can not starting, but v22.13.1 noproblem.
```

### Expectation

```
let param = {
    "headless": "new",
    "ignoreHTTPSErrors": true,
    "args": [
        "--disable-audio-output",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--disable-setuid-sandbox",
        "--headless",
        "--ignore-certificate-errors-spki-list",
        "--lang=ja,en-US;q=0.9,en;q=0.8",
        "--no-first-run",
        "--no-sandbox",
        "--no-zygote",
        "--single-process"
    ]
}
(async () => {
  try{
    let browser = await puppeteer.launch( param )
})().catch((error) => {
  let errdata = [{'error':{'message':error}}];
  console.log('Error '+JSON.stringify(errdata));
});

```

### Reality

console.log

`Error [{"error":{"message":{}}}]
`

### Puppeteer configuration file (if used)

```TypeScript
{
    "headless": "new",
    "ignoreHTTPSErrors": true,
    "args": [
        "--disable-audio-output",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--disable-setuid-sandbox",
        "--headless",
        "--ignore-certificate-errors-spki-list",
        "--lang=ja,en-US;q=0.9,en;q=0.8",
        "--no-first-run",
        "--no-sandbox",
        "--no-zygote",
        "--single-process"
    ]
}
```

### Puppeteer version

22.14.0

### Node version

18.16.1

### Package manager

npm

### Package manager version

9.7.2

### Operating system

Linux

**Comment by OrKoN** [comment]
I am unable to reproduce. 22.14.0  ships with the latest stable Chrome for Testing build so please make sure that you have required system [dependencies](https://pptr.dev/guides/system-requirements) installed and you can use the `dumpio: true` in the launch method to see what exactly is missing for the browser.

**Comment by hashimoto-AJ** [comment]
> I am unable to reproduce. 22.14.0 ships with the latest stable Chrome for Testing build so please make sure that you have required system [dependencies](https://pptr.dev/guides/system-requirements) installed and you can use the `dumpio: true` in the launch method to see what exactly is missing for the browser.

`/root/.cache/puppeteer/chrome/linux-127.0.6533.72/chrome-linux64/chrome: symbol lookup error: /root/.cache/puppeteer/chrome/linux-127.0.6533.72/chrome-linux64/chrome: undefined symbol: httpConnect2`

CentOS Linux release 7.3.1611 (Core)

v22.14.0 is not includeing `httpConnect2`?

**Comment by OrKoN** [comment]
Puppeteer currently does not install [system-level dependencies](https://pptr.dev/guides/system-requirements): the list for rpm is here https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/rpm/dist_package_provides.json I believe this one might be from libcups not being there?

**Comment by hashimoto-AJ** [comment]
> Puppeteer currently does not install [system-level dependencies](https://pptr.dev/guides/system-requirements): the list for rpm is here https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/rpm/dist_package_provides.json I believe this one might be from libcups not being there?

This list rpm not includeing `CENTOS`
my using OS is CentOS7, installed libcups.so but,`httpConnect2`  symbol not found

```
$ nm -D /usr/lib64/libcups.so.2 | grep httpConnect
000000000002c6e0 T httpConnect
000000000002c660 T httpConnectEncrypt

```

**Comment by OrKoN** [comment]
yes, I am not sure Chrome supports CentOS. It looks like libcups might be of the wrong version? since it lists httpConnect and not httpConnect2?

**Comment by siropkin** [comment]
I had the same issue (`undefined symbol: httpConnect2`) on AWS machine and I found a workaround - run Puppeteer with Firefox Instead of Chrome.
To do that I added this command to package.json (we use "yarn"):
```
"scripts": {
     ...
     "install": "puppeteer browsers install firefox",
     ...
}
```

And then in the code I launch puppeteer like this:
```
const browser = await puppeteer.launch({
      browser: 'firefox',
      headless: 'new',
});
```
