### ISSUE TITLE
[Feature]: How to use the docker image as a service container in GitHub Actions

### ISSUE THREAD

**Issue by mihkeleidast** [puppeteer/puppeteer#12827]
### Feature description

I would like to use your official Docker image as a service in GitHub Actions: https://docs.github.com/en/actions/using-containerized-services/about-service-containers

The main idea is that I need chrome running in a container, so I could run puppeteer tests on it.

However, it seems to fail and exits immediately with some errors when starting: https://github.com/mihkeleidast/chromium-service-container-debug/actions/runs/10092665042/job/27906767742

Any advice on how to get this working, or maybe your docker image is not meant for this?

**Comment by OrKoN** [comment]
It is generally not meant to run only the browser by default. You need to override the CMD and provide a Puppeteer script that would start the browser:

```
docker run -i --init --rm --cap-add=SYS_ADMIN ghcr.io/puppeteer/puppeteer:22.14.0 node -e "`cat your-script.js`"
```

Or extend the Docker image and copy your Puppeteer app to the container.

**Comment by OrKoN** [comment]
Also, I don't think CHROMIUM_FLAGS would be picked up this way, I think they need to be provided as part of the CMD.

**Comment by mihkeleidast** [comment]
Hmm, yeah, I don't think GHA allows overriding CMD unfortunately.

> and provide a Puppeteer script that would start the browser

The main idea is to get a browser running, and then connect to that browser via `puppeteer.connect` from the main runner container. So I'm not sure I have anything to put there.

CHROMIUM_FLAGS is another topic indeed, I've been using zenika/alpine-chrome until now (that image also has issues when running in GHA as a service), which picks that up, I did not focus on that env flag when trying your container.

**Comment by OrKoN** [comment]
btw the CMD defaulting google-chrome-stable seems to be an oversight from our side and it will be removed after https://github.com/puppeteer/puppeteer/pull/12580/files lands so that the image would only contain Puppeteer and Chrome for Testing bundled in it.

**Comment by mihkeleidast** [comment]
Got it. Closing as it's not the intended usage, plus I figured out a way to keep using my original image (zenika/alpine-chrome) by not using it as a service, rather I can start the container manually myself on the main runner.
