### ISSUE TITLE
[Bug]: Subsequent puppeteer.connect using browserWsEndpoint hangs if the previous puppeteer.connect navigates to another page 

### ISSUE THREAD

**Issue by seoular** [puppeteer/puppeteer#12834]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({});   

// then another script runs this connect line below: 

const browser = await puppeteer.connect({ browserWSEndpoint: params.browserWsEndpoint})
const pages = await browser.pages();
await pages[0].goto('https://google.com')

// then another script runs this connect line below, but it hangs; however if we do not navigate to another page (in this case google.com), this connect line below works fine
const browser = await puppeteer.connect({ browserWSEndpoint: params.browserWsEndpoint})
// this line never gets reached
```

### Background

I have a threadpool running a script that prelaunches the browsers, then another threadpool running a script which connects to the existing browsers to navigate to another page, then I have another script being ran by the second threadpool to process information on the browser pages, however the final script hangs on puppeteer.connect( --insert specific browserWsEndpoint-- ).

This two threadpool pattern was done so that killing the second threadpool leaves the browsers open.

### Expectation

I expected the final puppeteer.connect() to work properly and allow me to programmatically interact with the browser.

### Reality

In reality, the code hangs on the final script's puppeteer.connect()

### Puppeteer version

22.10.0

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not able to reproduce:

```
import puppeteer from "puppeteer";

const browser1 = await puppeteer.launch({});   

// then another script runs this connect line below: 

const browser2 = await puppeteer.connect({ browserWSEndpoint: browser1.wsEndpoint()})
const pages = await browser1.pages();
await pages[0].goto('https://google.com')
 
// then another script runs this connect line below, but it hangs; however if we do not navigate to another page (in this case google.com), this connect line below works fine
const browser3 = await puppeteer.connect({ browserWSEndpoint: browser1.wsEndpoint()})
// this line never gets reached

console.log('done')
```

prints done for me using the latest puppeteer version.
