### ISSUE TITLE
Refer #1248. How to download the PDF in headful mode.

### ISSUE THREAD

**Issue by UCSBGauchos** [puppeteer/puppeteer#1284]
Old issue. I am running it in headful mode. So how can I download the PDF file without rendering it by goto(PDFurl)

**Comment by UCSBGauchos** [comment]
#1248

**Comment by aslushnikov** [comment]
@UCSBGauchos You should be able to navigate to the pdf and then grab the main resource body:

```js
const response = await page.goto('article.pdf');
const pdf = await response.buffer();
```
