### ISSUE TITLE
[Bug]: page.createPDFStream().pipe is not a function

### ISSUE THREAD

**Issue by danrvc** [puppeteer/puppeteer#12853]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
import fs from 'fs';

async function generatePDF(url){
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  
  await page.goto(url, { waitUntil: 'networkidle2' });

  const pdfStream = await page.createPDFStream();
  const writeStream = fs.createWriteStream('test.pdf');
  pdfStream.pipe(writeStream);

  pdfStream.on('end', async () => {
    await browser.close();
  });

}

const url = 'https://google.com';

generatePDF(url)
  .then(() => console.log('PDF generated successfully'))
  .catch(err => console.error('Error generating PDF:', err));
```

### Background

Trying to generate a PDF using Puppeteer with stream instead of a buffer

### Expectation

To pipe the readable stream to a writable stream

### Reality

pipe is not a function, and the example code is incorrect

### Puppeteer version

22.14.0

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by OrKoN** [comment]
createPDFStream returns a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) instance that does not have the pipe method. If you want to convert it to a Node stream, use Readable.fromWeb:

```
import { Readable } from 'node:stream';
const pdfStream = Readable.fromWeb(await page.createPDFStream());
```
