### ISSUE TITLE
How to install chrome extensions

### ISSUE THREAD

**Issue by daviscai** [puppeteer/puppeteer#1286]
How to install chrome extensions , e.g  Flash Video Downloader

if puppeteer can install chrome extensions , that will be more powerfull

**Comment by ebidel** [comment]
Puppeteer doesn't have APIs for installing Chrome extensions at runtime, but you can load extensions via a cmd line flag when launching Chrome. See https://github.com/GoogleChrome/puppeteer/issues/659#issuecomment-341965254 for the tip.

**Comment by GuilloOme** [comment]
@daviscai, however, there is still a limitation since running a extension only work with `headless: false`

**Comment by aslushnikov** [comment]
@GuilloOme that's the implication of headless mode; extensions could be run only in headful mode.

**Comment by MehdiRaash** [comment]
Is that true for Service Worker as well or **SW** would be implemented?

**Comment by aslushnikov** [comment]
@MehdiRaash service workers work just fine in headless.

**Comment by MehdiRaash** [comment]
So Why serviceWorker has been faded in the diagram? introduction diagram: _faded entities are not currently represented in Puppeteer._
![31592143-089f6f9a-b1db-11e7-9a20-16b7fc754fa1](https://user-images.githubusercontent.com/6185507/32697912-63df5574-c7b0-11e7-8e4e-50569d7169ef.png)
