### ISSUE TITLE
[Bug]: Internal anchor tags do not go to the correct page

### ISSUE THREAD

**Issue by nbyloff** [puppeteer/puppeteer#12869]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

async function main() {
    const browser = await puppeteer.launch({
        headless: 'new',
        timeout: 0,
        ignoreHTTPSErrors: true,
        executablePath: '/usr/bin/chromium',
    });

    const page = await browser.newPage();
    await page.goto('http://host.docker.internal:8080/');

    await page.content();
    await page.waitForFunction('window.report == "ready"');

    const requestOptions = {};
    requestOptions.path = '/home/web/pdf/bugs.pdf';
    requestOptions.waitUntil = 'networkIdle2';
    requestOptions.printBackground = true;
    requestOptions.format = 'A4';
    const result = await page.pdf(requestOptions);

    await page.close();
    await browser.close();

}

main();
```

### Background

I've been using puppeteer inside a docker container for years and recently did package upgrades to get everything on supported versions. After upgrading, the generated links in the PDF do not go to the correct page in the document anymore. Within the document I create, a table of contents is generated using anchor tags references:

````
<a href="#section1">Section 1</a>
....
...
(several pages)
...
...
<h4 id="section1">Section 1</h4>
```` 

A slimmed down example with `Dockerfile` & `docker-compose.yml` file can be [tested here](https://github.com/nbyloff/puppeteer-issue). The base image is php-fpm:8.2 because this docker image is used to mimic the original Docker image where nvm & puppeteer are installed to generate these PDF reports in a queue managed by a PHP service.

### Expectation

After the PDF is generated, in the past you clicked on the intial Section 1 link and it takes you to the exact page with the header at the top of the PDF viewer. 

### Reality

Now it goes to the wrong page (usually 1.5 pages after the header). In my actual live document, sometimes it misses by several pages. 

Maybe related? When I use a text editor to open the PDF, I can find references like this to the `<h4>` ids like this:

````
43 0 obj
<</section1 [11 0 R /XYZ 72 -700.08002 0]
/section2 [38 0 R /XYZ 72 -8977.8301 0]>>
endobj
````

Except if I change those negative numbers to positive, the hash anchor links get me to the correct page, but the header is not top aligned with the PDF reader like the past. But I was throwing darts at this point anyways.

### Puppeteer version

22.15.0

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

macOS

**Comment by OrKoN** [comment]
This looks like the same issue as https://github.com/puppeteer/puppeteer/issues/12601 and it looks like you are not using the binary bundled with Puppeteer so likely the binary is an older version and still contains the bug.

**Comment by nbyloff** [comment]
> This looks like the same issue as #12601 and it looks like you are not using the binary bundled with Puppeteer so likely the binary is an older version and still contains the bug.

Chromium 126.0.6478.182 in this image. If I'm reading [this right](https://issues.chromium.org/issues/347674894) then I need 127?

I downloaded Chromium separately because I had such issues using the bundled version. It was the only recommendation I got. I'll go back and revisit it again. Thanks for pointing me to the issue!

**Comment by OrKoN** [comment]
From the Dockerfile it is hard to see which chromium version it included but Puppeteer 22.15.0 ships with 127.0.6533.88 https://pptr.dev/supported-browsers Generally, any M127 build should contain the fixes. If you still see the issue with M127, let me know. Also, I noticed that your Dockerfile uses an outdated PUPPETEER_SKIP_CHROMIUM_DOWNLOAD, this is removed in the following breaking change https://github.com/puppeteer/puppeteer/pull/10054 If you update from the older version, it might be helpful to go over the changelogs with breaking changes and see if updates have to be done to your set.

**Comment by OrKoN** [comment]
Also, consider using the Docker image we provide https://pptr.dev/guides/docker We pre-install Puppeteer and the browser in there, and run some automated tests to ensure it is functional.

**Comment by OrKoN** [comment]
> Also, consider using the Docker image we provide https://pptr.dev/guides/docker We pre-install Puppeteer and the browser in there, and run some automated tests to ensure it is functional.

It probably won't be directly useful since your image is based on php-fpm but perhaps https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile could be useful to apply in case there issues with running the bundled browser.

**Comment by nbyloff** [comment]
I've come across several threads of  people trying to add puppeteer to non-node images and the final solution was always to "skip chromium download". 

I'll share  updated Dockerfile here when I get it working properly. I actually haven't attempted a docker build with the bundled browser in a very long time since the "skip" worked for years. Your comments make it a lot more clear.  Thanks for all of this!

**Comment by nbyloff** [comment]
I do have an issue with `2.209 E: Unable to locate package google-chrome-stable` during Docker build. I am building on a Mac. I did switch to `node:20` instead of the full hash your Dockerfile has because of that (didn't like amd64).

I am going to step through that and the pack.sh script.

````
FROM node:20
#FROM node:20@sha256:cb7cd40ba6483f37f791e1aace576df449fc5f75332c19ff59e2c6064797160e

# Configure default locale (important for chrome-headless-shell).
ENV LANG=en_US.UTF-8

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] https://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 dbus dbus-x11 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd -r pptruser && useradd -rm -g pptruser -G audio,video pptruser

````

**Comment by nbyloff** [comment]
@OrKoN Question about the `tgz` files in your Dockerfile here: https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile.

I see the [pack.sh](https://github.com/puppeteer/puppeteer/blob/main/docker/pack.sh) script. I am out of my element here but my steps were:

- git clone puppeteer
- Set commit to the v22.15.0 main branch
- Copy `pack.sh` to the puppeteer root folder
- run `pack.sh`

From there it creates the puppeteer-core-latest.tgz, puppeteer-browsers-latest.tgz and puppeteer-latest.tgz

I added those 3 files to my test project and tried to build a new Dockerfile here:

````
# Set master image
FROM --platform=linux/amd64 php:8.2-fpm

ARG UID


# Set the SHELL to bash with pipefail option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN useradd -u $UID -g www-data -m web -d /home/web \
    && mkdir /home/web/.nvm

# Configure default locale (important for chrome-headless-shell).
ENV LANG=en_US.UTF-8
ENV NODE_VERSION=20.16.0
ENV NVM_DIR=/home/web/.nvm
ENV PATH="${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/:${PATH}"

RUN apt-get update \
    && apt-get install -y curl wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] https://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 dbus dbus-x11 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

USER web
WORKDIR /home/web

COPY --chown=web:www-data config/puppeteer-browsers-latest.tgz config/puppeteer-latest.tgz config/puppeteer-core-latest.tgz config/package.json ./

ENV DBUS_SESSION_BUS_ADDRESS=autolaunch:

# Install @puppeteer/browsers, puppeteer and puppeteer-core into /home/web/node_modules.
RUN echo 'export NVM_DIR="$HOME/.nvm"'                                       >> "$HOME/.bashrc" \
    && echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> "$HOME/.bashrc" \
    && echo '[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" # This loads nvm bash_completion' >> "$HOME/.bashrc" \
    && . $HOME/.nvm/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm use $NODE_VERSION \
    && npm i /home/web/puppeteer-browsers-latest.tgz /home/web/puppeteer-core-latest.tgz /home/web/puppeteer-latest.tgz \
    && rm /home/web/puppeteer-browsers-latest.tgz /home/web/puppeteer-core-latest.tgz /home/web/puppeteer-latest.tgz \
    && (node -e "require('child_process').execSync(require('puppeteer').executablePath() + ' --credits', {stdio: 'inherit'})" > THIRD_PARTY_NOTICES)


# set command to run puppeteer script
CMD ["node", "demo.js"]
````

Everything builds fine until the last line:
```
(node -e "require('child_process').execSync(require('puppeteer').executablePath() + ' --credits', {stdio: 'inherit'})" > THIRD_PARTY_NOTICES)
```

Fails with: 
````
107.3 Error: Cannot find module '/home/web/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js'
107.3     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1182:15)
107.3     at finalizeEsmResolution (node:internal/modules/cjs/loader:1170:15)
107.3     at resolveExports (node:internal/modules/cjs/loader:592:14)
107.3     at Module._findPath (node:internal/modules/cjs/loader:669:31)
107.3     at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
107.3     at Module._load (node:internal/modules/cjs/loader:986:27)
107.3     at Module.require (node:internal/modules/cjs/loader:1233:19)
107.3     at require (node:internal/modules/helpers:179:18)
107.3     at [eval]:1:35
107.3     at runScriptInThisContext (node:internal/vm:209:10) {
107.3   code: 'MODULE_NOT_FOUND',
107.3   path: '/home/web/node_modules/puppeteer/package.json'
107.3 }
107.3 
107.3 Node.js v20.16.0

````

The npm install isn't happening. If I remove that last 2 lines (so I don't delete the tgz files) and just run the buiilt image, I can login to the container and run `npm i` against those 3 files and it installs as expected.

Is there another build step I am missing with Docker? should I use a specific node version? I am confused that I don't get an errors installing puppeteer during a docker build, but it's clearly not getting installed properly.

I've also tried adding a `package.json` with puppeteer as a module, and then running this during build:
````
npm install \
&& node /home/web/node_modules/puppeteer/install.mjs
````

But it doesn't seem to work either. Maybe there's some nuance to node & docker I am unaware of?

**Comment by OrKoN** [comment]
Thanks for investigating. A few things I noticed: you do not need to install from .tar.gz files it would be sufficient to install from npm. We do that because we package the image before the NPM release exists. Also, you do not need to run the part to generate THIRD_PARTY_NOTICES unless you plan to re-distribute the the container image. The error seems to indicate that you have not built puppeteer (`npm run build`) before packing it.

**Comment by nbyloff** [comment]
After more digging, I have found that for some reason the `google-chrome-stable` install does not execute JavaScript the same way `chromium` was for me. 

I keep getting a `TimeoutError: Waiting failed: 30000ms exceeded` error because of this:

````
await page.waitForFunction('window.report == "ready"');
````

I thought it was just a timeout because the browser wasn't working, but after stepping through the puppeteer console log, it is loading, just not executing any of the JS I was using with chromium. So `window.report` is never getting set. In my webpage, I have this JS class for a library I use that formats PDFs for me:

````
<script>
    console.log('3');
    class ReportLoadedHandler extends Paged.Handler {
        constructor(chunker, polisher, caller) {
            super(chunker, polisher, caller);
        }

        afterRendered(pages) {
            console.log('4');
            window.report = 'ready'; // var for PDF generation to monitor so we know when to save PDF
        }
    }

    Paged.registerHandlers(ReportLoadedHandler);
</script>
````

The `afterRendered` function is never called using the updated Dockerfile I posted above (with `google-chrome-stable` instead of `chromium`).

I can do screenshots of sites like google.com, but I am trying to save to PDF after the Paged library does all it's formatting (page #s, table of contents, etc), which is `window.report = 'ready';`

I added some console logging so I know the JS library is being loaded, but that JS isn't being executed.

````
page.on('console', message =>
        console.log(`${message.type().substr(0, 3).toUpperCase()} ${message.text()}`))
        .on('pageerror', ({message}) => console.log(message))
        .on('response', response =>
            console.log(`${response.status()} ${response.url()}`))
        .on('requestfailed', request =>
            console.log(`${request.failure().errorText} ${request.url()}`))
```` 

Log output
````
200 http://demo.test:8080/
200 http://demo.test:8080/demo/report.css
200 https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css
200 http://demo.test:8080/demo/paged.polyfill.js <-- this is what executes JS

````

Not sure if you know any JS differences between chrome & chromium, but open to suggestions to track this down. Otherwise, thanks for getting me here!

**Comment by OrKoN** [comment]
I think there should be no difference in JS execution
