### ISSUE TITLE
[Bug]: puppeteer-core not considering PUPPETEER_EXECUTABLE_PATH on M2 chip

### ISSUE THREAD

**Issue by devsheva** [puppeteer/puppeteer#12870]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer-core";

// Launch the browser and open a new blank page
const browser = await puppeteer.launch();
const page = await browser.newPage();

// Navigate the page to a URL.
await page.goto("https://developer.chrome.com/");

// Set screen size.
await page.setViewport({ width: 1080, height: 1024 });
```

### Background

I've been trying to set the chromium executable with env variable as said in the docs `PUPPETEER_EXECUTABLE_PATH`.

### Expectation

It should consider the env variable 

### Reality

It leads to this error that tells to set the `executablePath`

```
❯ node index.js 
file:///Users/mateo/develop/puppeteer_test/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:15
        throw new Error(message);
              ^

Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (file:///Users/mateo/develop/puppeteer_test/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:15:15)
    at ChromeLauncher.computeLaunchArguments (file:///Users/mateo/develop/puppeteer_test/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:82:13)
    at async ChromeLauncher.launch (file:///Users/mateo/develop/puppeteer_test/node_modules/.pnpm/puppeteer-core@22.15.0/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:44:28)
    at async file:///Users/mateo/develop/puppeteer_test/index.js:4:17

```

### Puppeteer version

22.15.0

### Node version

20.14.0

### Package manager

pnpm

### Package manager version

9.6.0

### Operating system

macOS

**Comment by OrKoN** [comment]
puppeteer-core is a library package and does not use any environmental variables or configuration from the puppeteer package. You would need to provide the executable path explicitly in the launch call. More about configuration and puppeteer-core here:

1. https://pptr.dev/guides/configuration/
2. https://pptr.dev/guides/installation

**Comment by devsheva** [comment]
i didn't know this since the docs are the same for both packages, so i thought environment variables would work
