### ISSUE TITLE
[Feature]: Update Docker image base

### ISSUE THREAD

**Issue by lewis-jackson-bots** [puppeteer/puppeteer#12880]
### Feature description

The Dockerfile is currently pinned to an old SHA: https://github.com/puppeteer/puppeteer/blob/d9f2b659e8f19735d80e39351e1e4bacb702a88c/docker/Dockerfile#L1

This version has more Critical and High severity CVEs than the latest `node:20` tag.

Could the SHA be bumped again?

**Comment by OrKoN** [comment]
Thanks for the suggestion, it looks like the dependabot was not finding the dockerfile. The base will be updated in the next release that we plan to make in the next couple of days.
