### ISSUE TITLE
[Bug]: page.PdfDataAsync() gives timeout in Chromium v127 and  above using PuppeteerSharp v18  

### ISSUE THREAD

**Issue by dssmith** [puppeteer/puppeteer#12882]
### Steps to reproduce

**We have this simple c# code to start browser, load html into page, then create PDF, when we point to different versions of Chromium i.e 124 vs 133 we seem to be getting Timeout of 180000 ms exceeded using v133, as if it doesn't generate the PDF:**

	var executablePath = @"[PATH TO CHROMIUM]\chrome.exe"; **//Switch between Chromium versions here**
	var htmlFilePath = @"file:///[PATH TO HTML]";

	var brwLaunchOptions = new LaunchOptions
	{
		Headless = true,
		Args = new[] { "--headless=new" },
		ExecutablePath = executablePath
	};
	
	IBrowser Browser = await PuppeteerSharp.Puppeteer.LaunchAsync(brwLaunchOptions);
	
	var pages = await Browser?.PagesAsync()!;
	
	Console.WriteLine($"Current Open browser pages: [{pages.Length}], Html Path:{htmlFilePath}");

	var page = await Browser.NewPageAsync();

	// Set the dimensions of the PDF page and defaults
	var options = new PdfOptions
	{
		Format = PaperFormat.A4,
		Landscape = false,
		PrintBackground = true,
		PreferCSSPageSize = false,
		MarginOptions = new MarginOptions
		{
			Top = "0px",
			Right = "0px",
			Bottom = "0px",
			Left = "0px"
		},
		DisplayHeaderFooter = false, //assume no header or footer
		HeaderTemplate = "<div/>",   
		FooterTemplate = "<div/>"
	};

	await page.SetViewportAsync(new ViewPortOptions()
	{
		Width = (int)options.Format.Width,
		Height = (int)options.Format.Height,
		DeviceScaleFactor = 1
	});
	
	await page.EmulateMediaTypeAsync(MediaType.Print);
	
	await page.GoToAsync(htmlFilePath);
	
	
	var pdfByteArray = await page.PdfDataAsync(options); **//We Get Timeout of 180000 ms exceeded when using v133**
	
	File.WriteAllBytes(@"c:\temp\PdfSample.pdf",pdfByteArray);
	
	await page.CloseAsync();

### Expected results

We expect the html file to load, and then return byte[] when calling **page.PdfDataAsync()**

### Actual results

We get a **Timeout of 180000 ms exceeded** result when using Chromium v127 and above

**Comment by dssmith** [comment]
Perhaps this might be PuppeteerSharp issue?

**Comment by OrKoN** [comment]
Please report PuppeteerSharp issues to PuppeteerSharp as it needs to be addressed there. I think it could be this issue https://github.com/puppeteer/puppeteer/issues/12471 which has been fixed in Puppeteer.

**Comment by wdelmas** [comment]
This is a known regression in Chrome 125+. The `page.pdf()` call hangs then times out.

**Immediate fix:** Pin to Chrome 124:

```js
const browser = await puppeteer.launch({
  executablePath: '/path/to/chrome-124',
  // or use specific revision with puppeteer.launch({ channel: 'chrome' })
})
```

**Long-term:** This is the hidden cost of Puppeteer — you're implicitly dependent on Chrome's release cycle. Every major version can break your PDF pipeline. If reliability matters, consider services that abstract this away.
