### ISSUE TITLE
(docs proposal) add example tool: http-server-pwa and/or pupperender

### ISSUE THREAD

**Issue by LasaleFamine** [puppeteer/puppeteer#1289]
Hey there, I have made two new modules these days that are related to Puppeteer in some way:

* [pupperender](https://github.com/LasaleFamine/pupperender) - an ExpressJs middleware for rendering PWAs to bots using Puppeteer.
* [http-server-pwa](https://github.com/LasaleFamine/http-server-pwa) - http-server alike server but for serving and rendering PWA (using pupperender).

Do you think are worth to add within the examples README? cc/ @ebidel

**Comment by ebidel** [comment]
Yea, these are similar to puppetron and rendertron. But the express middleware seems generally useful to others. How about just adding that to examples/README? PR?

**Comment by LasaleFamine** [comment]
Yup, I'll prepare a PR for the middleware. Thank you!
