### ISSUE TITLE
[Bug]: Chrome for Testing does not honer hyphens: auto on Windows and Linux

### ISSUE THREAD

**Issue by schaakverslaafd** [puppeteer/puppeteer#12896]
### Minimal, reproducible example

```TypeScript
const fs = require('fs');
const puppeteer = require("puppeteer");

async function createPdf(data) {
  const browser = await puppeteer.launch();
  console.log(`executablePath: ${puppeteer.executablePath()}`);

  const page = await browser.newPage();
  await page.setContent(data);

  const pdf = await page.pdf({
    format: "a4",
    printBackGround: true,
    preferCSSPageSize: true,
    margin: {
      left: 0,
      top: 0,
      right: 0,
      bottom: 0,
    },
  });
  await browser.close();
  return pdf;
}

(async() => {
  const input = fs.readFileSync('test.html').toString()
  const output = await createPdf(input);
  fs.writeFileSync('puppeteer-output.pdf', output);
})();

test.html:
<!DOCTYPE html><html lang="en"> <head> <title>Hyphen test</title> <style> body { text-align: justify; hyphens: auto; width: 550px; } </style> </head> <body> <h2>Hyphen test</h2> <p> Hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation hyphenation. </p> </body> </html>
```

### Background

Creating a PDF of HTML pages with hyphens: auto are not rendered with hyphens. (Tested on windows and linux.)

I think this might be a bug in puppeteer because running `chrome.exe --headless --print-to-pdf [path]/test.html` creates a pdf with hyphens. Creating a pdf from puppeteer using the same executable (CfT: 127.0.6533.88) renders a pdf without hyphens.

See #6840 and #10947

### Expectation

A pdf with hyphens.

### Reality

A pdf without hyphens.

### Puppeteer version

22.15.0

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.8.0

### Operating system

Windows

**Comment by OrKoN** [comment]
it is an upstream issue. I will re-open https://g-issues.chromium.org/issues/353304848

**Comment by Lightning00Blade** [comment]
Closed as https://github.com/puppeteer/puppeteer/pull/13195 please one a new issue if this is still happening.
Will be release with Puppeteer `v23.6.0`
