### ISSUE TITLE
[Bug]: Postinstall script for downloading Chrome throws error when using Yarn P'n'P (Plug 'n' Play)

### ISSUE THREAD

**Issue by islazh** [puppeteer/puppeteer#12900]
### Minimal, reproducible example

```TypeScript
Please see `https://github.com/islazh/yarn-pnp-puppeteer-repro`. Make sure that there are no existing Chrome downloads in the Puppeteer cache.
```

### Background

We have been trying to use Yarn Plug 'n' Play to install dependencies including Puppeteer.

### Expectation

The postinstall script in Puppeteer downloads Chrome which is then used to run Puppeteer tests.

### Reality

An error is thrown because the path to `'puppeteer/internal/node/install.js'` cannot be resolved.
```
Skipping browser installation because the Puppeteer build is not available. Run npm install again after you have re-built Puppeteer.
```
This seems to happen because Yarn PnP "unplugs" Puppeteer during the postinstall - that is, it unzips the code in order to do the postinstall. However, Puppeteer seems to not be able to resolve its dependencies in PnP mode, so it cannot resolve @puppeteer/browsers. 

If I log out the error from `https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer/install.mjs`, I get this:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@puppeteer/browsers' imported from /Users/isla.zhang/Projects/eddrp-participant/.yarn/unplugged/puppeteer-npm-22.15.0-fa225bdb63/node_modules/puppeteer/lib/esm/puppeteer/node/install.js
```

### Puppeteer version

22.15.0

### Node version

20.14.0

### Package manager

yarn

### Package manager version

4.2.2

### Operating system

Linux

**Comment by OrKoN** [comment]
Puppeteer does relies on its dependent packages to download the browser during the installation (in postinstall hook). It does sound like it's the issue with yarn P'n'P? You can skip download during package installation (`PUPPETEER_SKIP_DOWNLOAD=true`) and use `npx puppeteer browsers install chrome` (or yarn's alternative for running package binaries) to download pinned browsers after yarn install. I don't think we care going to change the way we use dependencies during installation but perhaps yarn can support this scenario?

**Comment by OrKoN** [comment]
@Lightning00Blade seems to have additional context on this issue

**Comment by Lightning00Blade** [comment]
I also agree that this is most likely an issue with Yarn PnP.
With https://github.com/puppeteer/puppeteer/pull/12904 It should fix the issue when running the CLI, so the workaround in https://github.com/puppeteer/puppeteer/issues/12900#issuecomment-2273008603 should work out of the box.

As to why this is happening, we use ESM for our post-install script, and my guess is due to the way dependencies are stored you need to have the Yarn PnP ESM loader enabled for it to work correctly.

**Comment by Lightning00Blade** [comment]
Considering they somehow resolve this correctly when their ESM loader is present, they should try to throw or at least warn an user when an `.mjs` file is tried to be loaded without the ESM loader.

I will be closing these now, 
If you want consider posting an issue on Yarn an commenting a link here as well.
