### ISSUE TITLE
[Bug]: named function definition within evaluate causes ReferenceError

### ISSUE THREAD

**Issue by ApocalypseCalculator** [puppeteer/puppeteer#12905]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()

  // Set test content.
  await page.setContent(`<div>test</div>`)

  // Actions to trigger the bug.
  await page.evaluate(() => {
    const somefunction = () => { return false }
    return []
  })

  await browser.close()
})()
```

### Background

Defining functions within the scope of the evaluation is necessary for writing readable code in many cases

### Expectation

Run without issues

### Reality

The following error is thrown: 
```
Error [ReferenceError]: __name is not defined
    at evaluate
```

### Puppeteer version

Present in both 23.0.1 and 22.12.1

### Node version

20.15.1

### Package manager

npm

### Package manager version

10.8.1

### Operating system

macOS

**Comment by ApocalypseCalculator** [comment]
Interesting to note that this issue is not present when using anonymous functions (e.g. inline function within an `Array.map` call), but only when attempting to assign it. The following does not raise an error: 
```ts
  await page.evaluate(() => {
    (() => { return false })()
    return []
  })
```

**Comment by OrKoN** [comment]
If you use any minifiers or bundlers make sure you do not minify the names in the evaluated functions. The minimal reproducible example provided works for me so I am not able to reproduce the issue. See https://pptr.dev/guides/javascript-execution for more details and how to use the string format for evaluated code.

**Comment by ApocalypseCalculator** [comment]
Interesting. It seems like using `tsc` then executing it is fine, but using `tsx` to execute in one go causes this error, any idea why this is happening?

**Comment by OrKoN** [comment]
@ApocalypseCalculator I am not sure, does tsx minify or processes code in any way? can it output the code it compiled to?

**Comment by ApocalypseCalculator** [comment]
Interesting, looks like tsx [uses the esbuild transform API under the hood](https://github.com/privatenumber/tsx/blob/master/package.json#L4). 

I spent some time digging around and found the cached file, and yep, it seems like esbuild is wrapping the inline function for the name. The following is what the example is transformed as: 
```js
(() => {
  const __create = Object.create
  const __defProp = Object.defineProperty
  const __getOwnPropDesc = Object.getOwnPropertyDescriptor
  const __getOwnPropNames = Object.getOwnPropertyNames
  const __getProtoOf = Object.getPrototypeOf
  const __hasOwnProp = Object.prototype.hasOwnProperty
  const __name = (target, value) => __defProp(target, 'name', { value, configurable: true })
  const __copyProps = (to, from, except, desc) => {
    if (from && typeof from === 'object' || typeof from === 'function') {
      for (const key of __getOwnPropNames(from)) {
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable })
      }
    } return to
  }
  const __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule ? __defProp(target, 'default', { value: mod, enumerable: true }) : target, mod))
  const import_puppeteer = __toESM(require('puppeteer'));
  (async () => {
    const browser = await import_puppeteer.default.launch()
    const page = await browser.newPage()
    await page.setContent(`<div>test</div>`)
    await page.evaluate(() => {
      // point of interest: 
      const somefunction = __name(() => { return false }, 'somefunction'); return []
    }); await browser.close()
  })()
})()
```

Well, that certainly solves it. Thanks for your help!

**Comment by Milner39** [comment]
What did you do to get around it? Is tsx not an option for running ts file using puppeteer?

**Comment by ApocalypseCalculator** [comment]
> What did you do to get around it? Is tsx not an option for running ts file using puppeteer?

@Milner39 Yea, I just used `tsc`. You can also use anonymous functions instead which works with `tsx`

**Comment by Milner39** [comment]
Thanks! I ended up just setting up a script that lets me run any ts file with Deno.

```
	"scripts": {
		"drun": "deno run --config=./deno.jsonc -A --unstable-sloppy-imports",
		"start": "pnpm run drun ./"
	},

```

Works pretty good for me because I prefer Deno to Node anyway, but I prefer pnpm's package management.

Only weird thing is you need an empty deno.json(c) file and to set the `--config` flag in the `deno run` command. Deno just can't figure out that the dependencies are already installed otherwise.
