### ISSUE TITLE
[Bug]: TimeoutError: Navigation timeout for https://etvplay.espansionetv.it

### ISSUE THREAD

**Issue by AntonioFavero** [puppeteer/puppeteer#12916]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://etvplay.espansionetv.it');
```

### Background

We are just trying to open this site:  https://etvplay.espansionetv.it
By Chrome Browser or any other browser open normally

### Expectation

Open the https://etvplay.espansionetv.it 

### Reality

Getting error: TimeoutError: Navigation timeout of 60000 ms exceeded

### Puppeteer version

23.0.1

### Node version

v20.12.1

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Linux

**Comment by AntonioFavero** [comment]
The problem continues:

import puppeteer from 'puppeteer';
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://etvplay.espansionetv.it',
    {
        timeout: 120000,
        waitUntil: 'domcontentloaded'
    }
);

**Comment by Lightning00Blade** [comment]
Can't reproduce. The console statement is seen in the terminal.
```js
import { launch } from "puppeteer";

const browser = await launch();
const page = await browser.newPage();
await page.goto("https://etvplay.espansionetv.it", {
  timeout: 120000,
  waitUntil: "domcontentloaded",
});

console.log("Navigated");
await browser.close();
```
