### ISSUE TITLE
[Bug]: Clean script can cause data loss with vendored Puppeteer

### ISSUE THREAD

**Issue by jgraham** [puppeteer/puppeteer#12917]
When we vendor Puppeteer tests into mozilla-central we don't include the `.git` directory because we don't need history, and having multiple nested repos causes problems.

However we recently had a data-loss issue where a Firefox engineer tried to run the puppeteer tests from their hg checkout of mozilla-central, which they had placed inside a git repo containing their config files, with ignore rules used to exclude their work from source control.

In this scenario running [`git clean -Xf`](https://github.com/puppeteer/puppeteer/blob/main/tools/clean.mjs#L13) is a *really* bad idea because it's going to delete whatever is ignored in that git repo, which in the reported case seemed to be most of the home directory.

The same concern also applies if you vendor Puppeteer into a git-based project; in this case anything that invokes the clean script is going to delete all ignored files (e.g. build artifacts, downloaded assets, whatever) from the parent repo.

I don't know exactly what problem the clean script needs to solve, but it seems like it should either have a specific list of directories to remove, rather than relying on the VCS config, or at least confirm that the root of the git checkout is as expected before performing VCS actions.

(We will also look at this on the mozilla-central side to see if we should change the way we're vendoring or invoking the tests, to avoid these problems).

**Comment by OrKoN** [comment]
Do you run the clean script directly and not through the NPM script `npm run clean` defined Puppeteer?

**Comment by jgraham** [comment]
I think it's just running `npm run test:firefox` c.f. https://searchfox.org/mozilla-central/source/remote/mach_commands.py#419-527

**Comment by OrKoN** [comment]
The test commands do not run clean and when the clean is called there it looks like cwd is set correctly https://searchfox.org/mozilla-central/source/remote/mach_commands.py#751 The git clean command is called with args which is the list of files in the current cwd so generally it should not remove anything else.

**Comment by OrKoN** [comment]
What's the git version that was in use? maybe older versions didn't support args?

**Comment by OrKoN** [comment]
I think the mitigation is in place.
