### ISSUE TITLE
More flexible dumpio

### ISSUE THREAD

**Issue by ks07** [puppeteer/puppeteer#1292]
Enabling `dumpio` is quite useful as I'm experiencing some instability with headless chrome, but it can be very noisy.

It would be good if we could filter chrome's output (e.g. to filter out uninteresting messages based on tags like CONSOLE:), as well as redirect it elsewhere (e.g. to a file, or a buffer).

**Comment by sukrosono** [comment]
Did we also want dumping to file and buffer as a feature?

**Comment by ChBernat** [comment]
I believe I can handle this, is there a possibility for me to make it happen, guys?

**Comment by sukrosono** [comment]
@ChBernat
I believe you can handle that 😉. just make sure head to [contributing guide](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md). 

It's save to assume no one working this, because no one assigned.
Because what i found is: usually internal team (a and j) use github assign feature.

---
**P.S.**
living proof: 
- [JoelEinbinder](https://github.com/GoogleChrome/puppeteer/issues/assigned/JoelEinbinder)'s task,
- [Andrey](https://github.com/GoogleChrome/puppeteer/issues/assigned/aslushnikov)'s task.

where i can reach you personally?I prefer chat, for fast reaction.

**Comment by ChBernat** [comment]
I'm mostly using Slack and Hangouts to communicate with people and other developers but if you have any alternative then just let me know! It'd be great to start this feature asap. :smile: 

Either way, here's my e-mail: bernat.christopher@gmail.com

**Comment by aslushnikov** [comment]
Since Puppeteer v1.0.0 there's [`browser.process()`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-browserprocess) that allows you to get the `stderr` and `stdout` and do whatever with it.

**Comment by tsullivan** [comment]
> Since Puppeteer v1.0.0 there's browser.process() that allows you to get the `stderr` and `stdout` and do whatever with it.

Hi @aslushnikov I'm using v1.13.0 and trying to follow this advice. It looks like the `stderr` and `stdout` properties of the object returned by `browser.process()` are `null` value - I'd get a TypeError if I try to set a listener on the `null` value.

If I just `console.log` the object itself, it's:
```
ChildProcess {
  _events:
   [Object: null prototype] {
     exit: { [Function: bound onceWrapper] listener: [Function] } },
  _eventsCount: 1,
  _maxListeners: undefined,
  _closesNeeded: 3,
  _closesGot: 0,
  connected: false,
  signalCode: null,
  exitCode: null,
  killed: false,
  spawnfile: '/Users/...',
  _handle:
   Process { onexit: [Function], pid: 6921, [Symbol(owner)]: [Circular] },
  spawnargs:
   [ '/Users/...',
     '--disable-background-networking',
     '--disable-background-timer-throttling',
     '--disable-backgrounding-occluded-windows',
     '--disable-breakpad',
     '--disable-client-side-phishing-detection',
     '--disable-default-apps',
     '--disable-dev-shm-usage',
     '--disable-extensions',
     '--disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees',
     '--disable-gpu',
     '--disable-hang-monitor',
     '--disable-ipc-flooding-protection',
     '--disable-popup-blocking',
     '--disable-prompt-on-repost',
     '--disable-renderer-backgrounding',
     '--disable-sync',
     '--disable-translate',
     '--enable-automation',
     '--enable-features=NetworkService,NetworkServiceInProcess',
     '--force-color-profile=srgb',
     '--headless',
     '--hide-scrollbars',
     '--metrics-recording-only',
     '--mute-audio',
     '--no-first-run',
     '--password-store=basic',
     '--safebrowsing-disable-auto-update',
     '--use-mock-keychain',
     '--user-data-dir=/var/folders/...',
     '--window-size=3270,1584',
     'about:blank',
     '--remote-debugging-pipe' ],
  pid: 6921,
  stdin: null,
  stdout: null,
  stderr: null,
  stdio:
   [ null,
     null,
     null,
     Socket {
       connecting: false,
       _hadError: false,
       _handle: [Pipe],
       _parent: null,
       _host: null,
       _readableState: [ReadableState],
       readable: true,
       _events: [Object],
       _eventsCount: 2,
       _maxListeners: undefined,
       _writableState: [WritableState],
       writable: false,
       allowHalfOpen: false,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 115717,
       [Symbol(lastWriteQueueSize)]: 0,
       [Symbol(timeout)]: null,
       [Symbol(kBytesRead)]: 0,
       [Symbol(kBytesWritten)]: 0 },
     Socket {
       connecting: false,
       _hadError: false,
       _handle: [Pipe],
       _parent: null,
       _host: null,
       _readableState: [ReadableState],
       readable: true,
       _events: [Object],
       _eventsCount: 3,
       _maxListeners: undefined,
       _writableState: [WritableState],
       writable: false,
       allowHalfOpen: false,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 115718,
       [Symbol(lastWriteQueueSize)]: 0,
       [Symbol(timeout)]: null,
       [Symbol(kBytesRead)]: 0,
       [Symbol(kBytesWritten)]: 0 } ] }
```

Is this intended? I'm looking for a way to get the console logs of the child process integrated into another logging setup.

**Comment by ermik** [comment]
@tsullivan @aslushnikov with `browser.process()` being available only after `puppeteer.launch({})` resolves there's a catch. 

It means that unless `dumpio` is set to `true` there is no way to access Chromium output. This becomes troublesome when one of the switches causes it to abort ahead of remote debugging initialization (e.g. a `--load-extension` with an invalid manifest schema). Ideally `dumpio` accepts `{ stdout?: Writeable, stderr?: Writeable }` as alternative to the `process.` defaults.
