### ISSUE TITLE
[Bug]: not creating the browser

### ISSUE THREAD

**Issue by Todpig** [puppeteer/puppeteer#12925]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://www.globo.com');
})();
```

### Background

not creating the browser

### Expectation

open window

### Reality

dont work

### Puppeteer version

23.0.2

### Node version

node -v ---- v21.7.3

### Package manager

npm

### Package manager version

npm -v ---- 10.8.1

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
I am unable to reproduce, please provide logs of what is going on. You can use `dumpio: true` option when lunching to get the logs from the browser.
Please verify that you meet the [system requirement](https://pptr.dev/next/guides/system-requirements).
Also take a look at [Troubleshooting](https://pptr.dev/next/troubleshooting) for common problems.
