### ISSUE TITLE
"page.setCookie" fails when using "partitionKey" field in cookie: "Invalid parameters Failed to deserialize params.cookies.partitionKey"

### ISSUE THREAD

**Issue by JackyBoy666** [puppeteer/puppeteer#12935]
Uncaught ProtocolError ProtocolError: Protocol error (Network.deleteCookies): Invalid parameters Failed to deserialize params.partitionKey - CBOR: map start expected at position 336
It is a string for this particular web-page.
Seems partitionKey has been updated to a map officially but older sites are still using just a string? cant puppeteer read either/or?
(Cookie already has secure:true)

Original: https://github.com/puppeteer/puppeteer/issues/12787

**Comment by OrKoN** [comment]
could you please provide a minimal reproducible example? Note that the deleteCookie request does not accept a partition key https://pptr.dev/api/puppeteer.deletecookiesrequest

**Comment by JackyBoy666** [comment]
var cookies = await JSON.parse(await files.promises.readFile("cookies.json", "utf-8"));
if ( cookies ) page.setCookie (...cookies);

cookies = await page.cookies();
await files.promises.writeFile('cookies.json', JSON.stringify(cookies, null, 2));

I am only saving and loading with the above, the naughty cookie is:
 {
    "name": "cf_clearance",
    "value": "sEsVhmnci5YgW1SCN2yZMoD.poTl6RP8gl9Rx5e796M-1723419584-1.0.1.1-fve3CBTJt2T7D6mlfed6tobT_xFYAFpOW7xWBkGhHFEJ6KOwweXieKHVMe1fBWgtQJ5Nry3C2Ry81CTVtfcykA",
    "domain": ".g-portal.com",
    "path": "/",
    "expires": 1754955584.614792,
    "size": 161,
    "httpOnly": true,
    "secure": true,
    "session": false,
    "sameSite": "None",
    "priority": "Medium",
    "sameParty": false,
    "sourceScheme": "Secure",
    "partitionKey": "https://g-portal.com"
  },

**Comment by OrKoN** [comment]
I see: I believe this would be fixed by the next release that includes https://github.com/puppeteer/puppeteer/pull/12815

**Comment by JackyBoy666** [comment]
Updated and tested - same issue still present.

**Comment by OrKoN** [comment]
it's not been released yet, the next release that will include the fix is here https://github.com/puppeteer/puppeteer/pull/12937 We will release some time later this week.

**Comment by JackyBoy666** [comment]
You pushed your commit to main, i downloaded it, tried it, it doesnt work. You seem to want to ignore this issue.

**Comment by OrKoN** [comment]
> You pushed your commit to main, i downloaded it, tried it, it doesnt work. You seem to want to ignore this issue.

my change adds a test for exactly this scenario https://github.com/puppeteer/puppeteer/pull/12815/files#diff-4d10015a816a0b3fa2fa2bc7cc330639eb863381055fdf1d49e38dbaecb252dfR382 Please provide an exact reproducible example for your issue.

**Comment by OrKoN** [comment]
Also, please feel free to open a pull request with your test (it would be very much appreciated).

**Comment by JackyBoy666** [comment]
hey buddy, you're one of the webcode wizards, not me. im just telling you it is still failing with the same errors.
i gave you the cookie and the very simple loading/saving cookies code.
maybe look a bit deeper, or pass this issue along to someone else.

**Comment by pwnz22** [comment]
I'm having the same issue with **partitionKey**. Puppeteer version: **23.1.1**

**Comment by OrKoN** [comment]
@pwnz22 could you provide a minimal example that demonstrates the issue you have: https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%5BBug%5D%3A+?
