### ISSUE TITLE
[Bug]: A request failure causes page.goto timeout

### ISSUE THREAD

**Issue by chuoke** [puppeteer/puppeteer#12953]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
const page = await browser.newPage();


  await page.setRequestInterception(true);

  page.on("request", async (req) => {
    console.log(req.url());
    if (req.isInterceptResolutionHandled()) return;

    if (/(ads)[\.\-\_]{1,}/.test(req.url())) {
      await req.abort();
    } else {
      await req.continue();
    }
  });

await page.goto("https://ggzyjy.nmg.gov.cn/jyxx/index_24.html?id=571b3118-bb62-411f-8821-ed79ea05b91a", { waitUntil: "networkidle2" });

await browser.close();
```

### Background

![image](https://github.com/user-attachments/assets/9be82433-547a-4c1e-9442-412f17a3e0be)
this make page.goto timeout.

### Expectation

no timeout;
or Decide what to do in `requestfailed` hook.

### Reality

page.goto timeout

### Puppeteer version

22.13.1

### Node version

18.14.2

### Package manager

pnpm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by OrKoN** [comment]
In DevTools, I see that requests to dcs.conac.cn are never resolved and if you add:

```
  if (req.url().includes('dcs.conac.cn')) {
    await req.abort();
    return;
  }
```

the navigation resolves without timeout.
