### ISSUE TITLE
[Bug]: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object

### ISSUE THREAD

**Issue by aShelist** [puppeteer/puppeteer#12958]
### Minimal, reproducible example

```TypeScript
async waitForCvTitle(title: string) {
   I.waitForElement(`//input[@id="title" and contains(@value,'${title}')]`);
}
```

### Background

I use codeceptjs + puppeteer. When I update puppeteer version, from 20.2.0 to 22.06.0 I got error in my tests.

When my test try wait some element (or visible), code throw error in console. This may be fixed, if i add
`wait(10)` in my code

### Expectation

browser wait element

### Reality

Throw error in console:
`Argument should belong to the same JavaScript world as target object`

### Puppeteer configuration file (if used)

```TypeScript
const showWindow = !JSON.parse(process.env.HEADLESS || false);

module.exports = {
  show: showWindow,
  waitForNavigation: 'networkidle2',
  waitForTimeout: 30000,
  getPageTimeout: 30000,
  windowSize: '1000x1000',
  browser: 'chrome',
  chrome: {
    args: ['--no-sandbox',
      '--window-size=1920,1000',
      '--disable-setuid-sandbox',
      '--disable-web-security',
      // workaround for iframe in {headless: false} mode,
      // see details https://github.com/puppeteer/puppeteer/issues/4964
      '--disable-features=site-per-process',
    ],
    devtools: false,
  },
  manualStart: false,
  restart: false,
  keepCookies: true,
  keepBrowserState: false,
};
```

### Puppeteer version

22.6 or greate

### Node version

v18.16.1

### Package manager

npm

### Package manager version

9.5.1

### Operating system

macOS

**Comment by aShelist** [comment]
[log.txt](https://github.com/user-attachments/files/16624375/log.txt)
Log file with `DEBUG=puppeteer:*`

**Comment by OrKoN** [comment]
Could you please post a minimal reproducible example with using Puppeteer only? If it does not reproduce without CodeceptJS, perhaps the issue is in there? The error indicates that the argument from the wrong world is being provided. Also, the latest Puppeteer version is 23.1.0, please try with the latest version.

**Comment by OrKoN** [comment]
```
import puppeteer from "puppeteer";

const browser = await puppeteer.launch();

const page = await browser.newPage();

const elementPromise = page.waitForSelector(`xpath///input[@id="title" and contains(@value,'test')]`);

await page.setContent(`<input id="title" value="test">`);

const element = await elementPromise;

console.log('element found: #', await element.evaluate(e => e.id));

await browser.close();
```

the following equivalent in Puppeteer seems to work. What are the page interactions in your test?

**Comment by aShelist** [comment]
Thanks, I'll try transfer code on puppeteer only. It stopped working after the version update. On puppeteer 20.2.0 this works fine

**Comment by bernatixer** [comment]
Having the same problem on one of the latest version, still need to find at which one it started appearing

**Comment by eried** [comment]
> Throw error in console: `Argument should belong to the same JavaScript world as target object`

Hey, did you ever find a real solution for this issue?

**Comment by aShelist** [comment]
> > Throw error in console: `Argument should belong to the same JavaScript world as target object`
> 
> Hey, did you ever find a real solution for this issue?

No, unfortunately I still haven't found a solution.

**Comment by eried** [comment]
I added a delay and now it has not crashed again, but clearly there is still something wrong around

**Comment by aShelist** [comment]
> I added a delay and now it has not crashed again, but clearly there is still something wrong around

Did you add a delay in a specific test? For example,
```
...
await page.waitForTimeout(4000)
...
```

**Comment by eried** [comment]
Without this delay, the `waitforselectorasync `was triggering the error
```
                 Console.WriteLine("Waiting for page " + currentPage);

                    try
                    {
                        Thread.Sleep(100);

                        /*for (int i = 10; i < 60; i++)
                        {
                            Thread.Sleep(200);
                            page.ScreenshotAsync("debug_"+i+".png");
                        }*/
                        await page.WaitForSelectorAsync("#vertically-scrolled-table", new WaitForSelectorOptions() { Timeout = 30000 });

                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("No more pages. Finishing");
                        break;
                    }

```

I was trying to find out what happened taking screenshots, but no idea.
