### ISSUE TITLE
No errors raised when select element not found

### ISSUE THREAD

**Issue by chooserich** [puppeteer/puppeteer#1296]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: master version
* Platform / OS version: MacOSX

**What steps will reproduce the problem?**

The documentation [currently states](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#frameselectselector-values) that `frame.select` should raise an error if the value is not found. However there's nothing in the code ([source](https://github.com/GoogleChrome/puppeteer/blob/master/lib/FrameManager.js#L429)) that raises an error in this event.

**What is the expected result?**

An error is raised.

**What happens instead?**

No error is raised.

There should either be an error or the documentation should be updated.

**Comment by JoelEinbinder** [comment]
In theory, `$eval` should raise the error.
