### ISSUE TITLE
[Bug]: Fetch.fulfillRequest ProtocolError: Protocol error (Fetch.fulfillRequest): Invalid InterceptionId.

### ISSUE THREAD

**Issue by Fly-Playgroud** [puppeteer/puppeteer#12961]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer-core";
import {Protocol} from "puppeteer-core";

const browser = await puppeteer.launch({

    executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    // executablePath: "F:\\dangerous\\chrome\\114\\chrome-win\\chrome.exe",
    headless: false,
    // args: [
    //     "--disable-gpu",
    //     "--disable-dev-shm-usage",
    //     // "--disable-setuid-sandbox",
    //     "--no-first-run",
    //     "--no-sandbox",
    //     "--no-zygote",
    //     // "--single-process",
    //     "--disable-web-security",
    //     // "--disable-features=IsolateOrigins,site-per-process",
    // ]
});


const requestStore = new Map<Protocol.Network.RequestId | undefined, Protocol.Fetch.RequestId>();

const page = await browser.newPage();

const session = await page.createCDPSession();


await session.send("Network.enable");
await session.send("Fetch.enable", {
    patterns: [
        {
            requestStage: "Response",
            urlPattern: "*"
        }
    ]
});

session.on("Fetch.requestPaused", async (event) => {
    console.log(event.requestId);
    // if (event.responseErrorReason === undefined) {
    //     await session.send("Fetch.continueRequest", {
    //         requestId: event.requestId,
    //     });
    // }
    await session.send("Fetch.continueRequest", {
        requestId: event.requestId,
    });

    requestStore.set(event.networkId, event.requestId);
});

session.on("Network.loadingFailed", async (event) => {
    console.log("loading failed")
    const interceptedRequestId = requestStore.get(event.requestId);
    if (interceptedRequestId !== undefined) {
        await session.send("Fetch.fulfillRequest", {
            requestId: interceptedRequestId,
            responseCode: 200,
            body: "test"
        });

    } else {
        console.log("not intercepted");
    }

});


try {

    await page.goto("https://www.dedeede.com/");
} catch (e) {
    console.log(e);
}
```

### Background

I tried using `Fetch.fulfillRequest` to modify the response when listening to the `Network.loadingFailed` event.

### Expectation

The response content has been modified to the content I specified.

### Reality

But I  got an error：  #error = new ProtocolError();       
           ^

ProtocolError: Protocol error (Fetch.fulfillRequest): Invalid InterceptionId.

### Puppeteer version

23.1.0

### Node version

20.12.2

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Windows

**Comment by Fly-Playgroud** [comment]
If I cancel the commented out code, the navigation will remain Pending until it times out.

```ts
    // if (event.responseErrorReason === undefined) {
    //     await session.send("Fetch.continueRequest", {
    //         requestId: event.requestId,
    //     });
    }
```

My guess is that `Fetch.continueRequest` was not called in time. As a result, the LodingFailed event has not been triggered.

**Comment by OrKoN** [comment]
That is too late to intercept the request in Network.loadingFailed. You can do that while handling requestPaused. If you received a responseErrorReason or a responseStatusCode in the requestPaused event it implies the response interception state and you can modify it. Note that you are working with CDP directly, therefore, it is out of scope for Puppeteer. Related https://github.com/puppeteer/puppeteer/issues/1191

**Comment by Fly-Playgroud** [comment]
The `responseErrorReason` in the `requestPaused Event` does not have the errorText in the `Network.loadingFailed` event to display the detailed error reason.

**Comment by Fly-Playgroud** [comment]
> The `responseErrorReason` in the `requestPaused Event` does not have the errorText in the `Network.loadingFailed` event to display the detailed error reason.

If `requestPaused Event` 's responseErrorReason could the same as  `Network.loadingFailed` 's `errorText`, that will be prefect!!!

**Comment by OrKoN** [comment]
So the loading failed event happens after the response interception and it is processed by the renderer. For example, a response might be successful in Fetch but then after the response is received by the renderer it still might error due to cors checks, timeouts, access checks etc. I do not think it will be possible to provide the same error text but for response interception you probably should be relying on responseErrorReason and not errorText since errorText is not only determined by the response errors.

**Comment by OrKoN** [comment]
Also, errorText is a localized description of the error so it would be more difficult to parse consistently https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/inspector_network_agent.cc;l=1725;drc=edee6cbe45e58b8c002c89b505aa9e99b07034ef

**Comment by Fly-Playgroud** [comment]
> Also, errorText is a localized description of the error so it would be more difficult to parse consistently https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/inspector_network_agent.cc;l=1725;drc=edee6cbe45e58b8c002c89b505aa9e99b07034ef

OK, thank you! Is there any way to customize the contents of chrome-error://chromewebdata?
