### ISSUE TITLE
[Bug]: Generated PDF gets curropted 

### ISSUE THREAD

**Issue by ALFAMAS** [puppeteer/puppeteer#12979]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
      userDataDir: './tmp',
      headless: true,
      args: [
        '--disable-web-security',
        '--disable-setuid-sandbox',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-background-networking',
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-breakpad',
        '--disable-client-side-phishing-detection',
        '--disable-component-update',
        '--disable-default-apps',
        '--disable-dev-shm-usage',
        '--disable-domain-reliability',
        '--disable-extensions',
        '--disable-features=AudioServiceOutOfProcess',
        '--disable-hang-monitor',
        '--disable-ipc-flooding-protection',
        '--disable-notifications',
        '--disable-offer-store-unmasked-wallet-cards',
        '--disable-popup-blocking',
        '--disable-print-preview',
        '--disable-prompt-on-repost',
        '--disable-renderer-backgrounding',
        '--disable-setuid-sandbox',
        '--disable-speech-api',
        '--disable-sync',
        '--hide-scrollbars',
        '--ignore-gpu-blacklist',
        '--metrics-recording-only',
        '--mute-audio',
        '--autoplay-policy=user-gesture-required',
        '--no-default-browser-check',
        '--no-first-run',
        '--no-pings',
        '--no-sandbox',
        '--no-zygote',
        '--password-store=basic',
        '--use-gl=swiftshader',
        '--use-mock-keychain'
      ],
    });
    const page = await browser.newPage();
    await page.setContent(`${html}`, { waitUntil: 'networkidle0' });
    await page.emulateMediaType("screen");

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();
```

### Expectation

I expected it to work

### Reality

in Reality it didn't
```log
There is no error at the moment but the generated PDF from the version gets corrupted "puppeteer": "^23.1.0",
```

### Puppeteer version

"puppeteer": "^23.1.0",

### Node version

v20.16.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
This does not look like an issue with Puppeteer directly, but with your set-up.
Have you verified that all dependencies are met from the [Troubleshooting](https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux)?
Alternatively does not providing `args` work in `puppeteer.launch`?
You can try to  lunch with `dumpio: true` to see the output from the browser itself.
Also from the error it looks like some permission are not granted.

**Comment by ALFAMAS** [comment]
Fixed the issue it was a problem with the latest version downgrading to 22.13.0 fixed it

**Comment by mb2993** [comment]
We also have issue with the latest versions of Chromium based browsers (tested on Edge and Chrome) on Windows. Downgrading resolved the issue, but that's just a workaround, not a long term solution to the problem. Does anyone know how to fix this in newer versions?

**Comment by ALFAMAS** [comment]
I have fixed the issue with the latest but the pdf generated by the latest version gets corrupted

**Comment by whoisthisstud** [comment]
Same issue here. v23.1.0 results in a corrupted PDF.  

Downgrading to 22.13.0 works.

**Comment by wr1688** [comment]
The more you update, the worse it gets

**Comment by ALFAMAS** [comment]
can you check if the issue still exists the generated PDF gets corrupted with the version "puppeteer": "^23.1.0",

**Comment by ksiczek** [comment]
I've encountered it on the `23.1.1`. We are in an intermediary phase with the same code as a node 18 service and 20.x AWS lambda. The `23.1.1` worked as the lambda but not as the service. Could it be a node 18 issue?

**Comment by ALFAMAS** [comment]
> I've encountered it on the `23.1.1`. We are in an intermediary phase with the same code as a node 18 service and 20.x AWS lambda. The `23.1.1` worked as the lambda but not as the service. Could it be a node 18 issue?

"puppeteer": "^23.4.0",

Try my code 

const browser = await puppeteer.launch({
      userDataDir: './tmp',
      headless: true,
      // headless: false,
      args: [
        '--disable-web-security',
        '--disable-setuid-sandbox',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-background-networking',
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-breakpad',
        '--disable-client-side-phishing-detection',
        '--disable-component-update',
        '--disable-default-apps',
        '--disable-dev-shm-usage',
        '--disable-domain-reliability',
        '--disable-extensions',
        '--disable-features=AudioServiceOutOfProcess',
        '--disable-hang-monitor',
        '--disable-ipc-flooding-protection',
        '--disable-notifications',
        '--disable-offer-store-unmasked-wallet-cards',
        '--disable-popup-blocking',
        '--disable-print-preview',
        '--disable-prompt-on-repost',
        '--disable-renderer-backgrounding',
        '--disable-setuid-sandbox',
        '--disable-speech-api',
        '--disable-sync',
        '--hide-scrollbars',
        '--ignore-gpu-blacklist',
        '--metrics-recording-only',
        '--mute-audio',
        '--autoplay-policy=user-gesture-required',
        '--no-default-browser-check',
        '--no-first-run',
        '--no-pings',
        '--no-sandbox',
        '--no-zygote',
        '--password-store=basic',
        '--use-gl=swiftshader',
        '--use-mock-keychain'
      ],
    });
    const page = await browser.newPage();
    // Set viewport size
    await page.setViewport({
      width: 1500,
      height: 800,
      deviceScaleFactor: 1,
    });

    // Enable JavaScript and wait for network idle
    await page.setJavaScriptEnabled(true);
    await page.setContent(html, {
      waitUntil: ['load', 'domcontentloaded', 'networkidle0'],
      timeout: 60000 // 60 seconds timeout
    });

    await page.emulateMediaType("screen");

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: '0.5cm',
        // bottom: '1cm',
        right: '0.8cm',
        left: '1cm'
      },
    });

    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${name}.pdf"`);
    // res.send(pdfBuffer);
    res.send(Buffer.from(pdfBuffer)); // Send the PDF as response Buffer (V23+++)

**Comment by ksiczek** [comment]
Thank you, @ALFAMAS, but we are bound to the `23.1.1` which is the latest [supported for Chrome 127.0.0](https://pptr.dev/supported-browsers) due to `@sparticuz/chromium`, which does not support 128 or 129 yet.

**Comment by jasonswearingen** [comment]
for anyone fighting with pdf generation after upgrading to pptr v23+, here is (likely) the solution: https://github.com/puppeteer/puppeteer/issues/13209#issuecomment-2817202802
