### ISSUE TITLE
[Bug]: Puppeteer open a new page about:blank and ignores goto code line

### ISSUE THREAD

**Issue by aliendrippin** [puppeteer/puppeteer#12988]
### Minimal, reproducible example

```TypeScript
let puppeteer = require('puppeteer');

(async () => {
  // Launch the browser and open a new blank page
  const browser = await puppeteer.launch({
    headless: false,
    executablePath: '[executable path]',
    userDataDir: '[profile path]',
  });
  const page = await browser.newPage();

  await page.goto('https://example.com');
})();
```

### Background

I've been trying to use puppeteer in a regular Chrome instance reffering to https://github.com/puppeteer/puppeteer/issues/3543,
so Puppeteer open a new page and leaves it about:blank 

### Expectation

I expected to open my website in a new browser tab

### Reality

Browser tab remains about:blank and nothing happens

### Puppeteer version

23.1.0

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

macOS

**Comment by OrKoN** [comment]
I am not able to reproduce with the bundled version of Chrome:

```
let puppeteer = require('puppeteer');

(async () => {
  // Launch the browser and open a new blank page
  const browser = await puppeteer.launch({
    headless: false,
    userDataDir: '/tmp/test'
  });
  const page = await browser.newPage();

  await page.goto('https://example.com');
})();
```

Make sure that you using a compatible Chrome version and we recommend using the Chrome for Testing version that Puppeteer installs by default.

**Comment by aliendrippin** [comment]
> I am not able to reproduce with the bundled version of Chrome:
> 
> ```
> let puppeteer = require('puppeteer');
> 
> (async () => {
>   // Launch the browser and open a new blank page
>   const browser = await puppeteer.launch({
>     headless: false,
>     userDataDir: '/tmp/test'
>   });
>   const page = await browser.newPage();
> 
>   await page.goto('https://example.com');
> })();
> ```
> 
> Make sure that you using a compatible Chrome version and we recommend using the Chrome for Testing version that Puppeteer installs by default.

How do i determine compatible Chrome version for my case?

**Comment by OrKoN** [comment]
@aliendrippin you can find the list here https://pptr.dev/supported-browsers
