### ISSUE TITLE
[Bug]: Performance Degradation in New Headless Mode when using headless 'new' instead of Headless : True.

### ISSUE THREAD

**Issue by Ameer-Jamal** [puppeteer/puppeteer#12982]
### Minimal, reproducible example

```TypeScript
try {
    freeBrowser.browser = await puppeteer.launch({
      headless: true, // Use headless mode for better performance
      userDataDir: DEV_PROFILE_PATH,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-gpu', // Disable GPU for better performance in headless mode
        '--disable-dev-shm-usage',
        '--disable-software-rasterizer',
        '--disable-background-networking',
        '--ignore-certificate-errors',
        `--window-size=${WINDOW_WIDTH},${WINDOW_HEIGHT}`
      ]
    });
    freeBrowser.page = await freeBrowser.browser.newPage();
    await freeBrowser.page.setViewport({ width: WINDOW_WIDTH, height: WINDOW_HEIGHT });
  } catch (e) {
    console.error('Failed to create browser using puppeteer:', e);
  }
}
```

### Background

When switching to the new headless mode in Puppeteer (headless: "new"), I've noticed a significant slowdown in the execution of my scripts compared to the old headless mode (headless: true). The new headless mode appears to be slower and less efficient, which affects the overall performance of my automation tasks. My task is converting a webpage to PDF. this webpage contains images most of the time and I have code to handle image gridding, but leaving all the code the same and just switching from true to new makes it slower by a significant margin.

### Expectation

The new headless mode should perform at least as efficiently as the old headless mode or provide a clear trade-off in terms of additional features or rendering fidelity.

### Reality

The new headless mode (headless: "new") is noticeably slower than the old headless mode (headless: true). The script execution time increases significantly, leading to a decrease in overall performance.

For tasks that take 3 seconds on headless true I noticed it takes 5-7 seconds on headless new. which is large enough to cause problems
Proof: 
When using True : 
![I AM SPEEDD](https://github.com/user-attachments/assets/314358ea-5e87-491f-8a2b-5a2d51752ab2)

When using 'new' : 
![image](https://github.com/user-attachments/assets/73c3fe8d-6722-4d42-900e-8182b0e319fb)

### Puppeteer configuration file (if used)

```TypeScript
const {
  DEV_PROFILE_PATH,
  WINDOW_HEIGHT,
  WINDOW_WIDTH
} = require('./constants');
const {rimraf} = require('rimraf')
const os = require('os');
const fs = require('fs');
const puppeteer = require('puppeteer');

const browsers = [];
let MAX_BROWSERS = 10;
const TIMEOUT = 300000;

const BROWSER = (i) => ({
  browser: {},
  page: {},
  isFree: true,
  number: i
});


const generateBrowsers = (config) => {
  MAX_BROWSERS = config.maxConcurrentPrintOperations;
  for (let i = 0; i < MAX_BROWSERS; i ++) {
    browsers.push(BROWSER(i + 1));
  }
}

const getFreeBrowser = () => {
  for (let i = 0; i < MAX_BROWSERS; i ++) {
    if (browsers[i].isFree)
      return browsers[i];
  }
  return false;
}

const closeBrowser = async (browserContainer) => {
  try {
    await browserContainer.page.close().catch(e => console.error('Failed to close page:', e));
    await browserContainer.browser.close().catch(e => console.error('Failed to close browser:', e));
    browserContainer.isFree = true;
    if (fs.existsSync(DEV_PROFILE_PATH)) {
      await rimraf(DEV_PROFILE_PATH).then(() => {
        console.log(`\t---Headless DEV_PROFILE cleared\t${DEV_PROFILE_PATH}`);
      }).catch(e => console.error(e));
    }
  } catch (e) {
    console.error('Failed to close browser:', e);
  }
}
const initBrowser = async (freeBrowser) => {
  // This code will allow Puppeteer to launch a new instance of the browser as needed
  if (fs.existsSync(DEV_PROFILE_PATH)) {
    await rimraf(DEV_PROFILE_PATH).catch(e => console.error(e));
  }
  freeBrowser.isFree = false;
  try {
    freeBrowser.browser = await puppeteer.launch({
      headless: 'new',
      userDataDir: DEV_PROFILE_PATH,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-gpu', // Disable GPU for better performance in headless mode
        '--disable-dev-shm-usage',
        '--disable-software-rasterizer',
        '--disable-background-networking',
        '--ignore-certificate-errors',
        `--window-size=${WINDOW_WIDTH},${WINDOW_HEIGHT}`
      ]
    });
    freeBrowser.page = await freeBrowser.browser.newPage();
    await freeBrowser.page.setViewport({ width: WINDOW_WIDTH, height: WINDOW_HEIGHT });
  } catch (e) {
    console.error('Failed to create browser using puppeteer:', e);
  }
}

//// --- Rest of code redacted
```

### Puppeteer version

20.7.1

### Node version

 node:20-alpine3.17

### Package manager

npm

### Package manager version

8.19.4

### Operating system

macOS

**Comment by OrKoN** [comment]
We do not expect the new headless mode to have the same performance as the old headless shell browser. See https://pptr.dev/guides/headless-modes/ for more details. In general, the headless mode performance should be the same as the headful browser performance since it is now the same browser implementation running in both modes. The old headless mode also known as Chrome headless shell is a different browser implementation that is more performant but does not behave exactly the same way as regular Chrome. If yotu need better performance for your use case, you can still use it by providing `headless: 'shell'`.

**Comment by OrKoN** [comment]
More details about the old vs new headless mode https://developer.chrome.com/docs/chromium/new-headless#how_does_headless_work

**Comment by Ameer-Jamal** [comment]
Thank you for the clarification @OrKoN
