### ISSUE TITLE
Got 'debugging connection was closed websocket disconnected reconnect when ready by reopening devtools' when accessing devtoolsFrontendUrl  

### ISSUE THREAD

**Issue by Dineshkumar197** [puppeteer/puppeteer#12992]
### Steps to reproduce

I launched a browser using 

  `var browser = await puppeteer.launch({ headless: false,args:["--remote-debugging-port=9225"] });`
  
I accessed http://[remote-ip]:9225/json/list and got 'devtoolsfrontendurl' from this. 
And when I accessed this url I got this error 

### Expected results

I wanted to intereact with the pages in the remote browser. 

### Actual results

When I use **puppeteer version higher than 19**, this problem occurs.

**Comment by OrKoN** [comment]
If you want to open DevTools for the pages, set `devtools: true` in the launch arguments. If the devtoolsfrontendurl URL provided by the browser's JSON endpoints is not working, please file an issue at https://crbug.com/new.
