### ISSUE TITLE
[headless] Impossible to accept/dismiss javascript dialogs

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#13]
Example:
```js
var Browser = require('puppeteer').Browser;
var browser = new Browser();
browser.newPage().then(async page => {
    page.on('dialog', dialog => {
        dialog.accept('test');
    });
    console.log(await page.evaluate(() => prompt('q?')));
    browser.close();
});
```

Dialog accepting/dismissing throws on error on headless: 
>Error: Protocol error (Page.handleJavaScriptDialog): Could not handle JavaScript dialog

Upstream bug: [crbug.com/718235](http://crbug.com/718235)

**Comment by paulirish** [comment]
fixed bug link https://bugs.chromium.org/p/chromium/issues/detail?id=718235
