### ISSUE TITLE
Tracing: allow adding custom tracing categories

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#1300]
(Based on discussion in https://github.com/GoogleChrome/puppeteer/issues/854#issuecomment-342247715)

There should be a way to run tracing with custom categories.

@paulirish suggested having a "sampling" option with optional "hires" parameter.

```js
page.tracing.start({
  path: 'trace.json',
  sampling: true // could be also |false| and |'hires'|
});
```

As a valid alternative, I like letting users specify custom categories:

```js
page.tracing.start({
  path: 'trace.json',
  // Use these categories instead of the puppeteer defaults
  categories: ['disabled-by-default-v8.cpu_profiler.hires', /* ... other categories.. */ ]
});
```

**Comment by slohmes** [comment]
Would implementation for this just involve adding something like
`    if (options.categories)
        categoriesArray.push(...options.categories);
`
to the start method in Tracing.js?

**Comment by aslushnikov** [comment]
@slohmes yes. However, I'd rather use passed-in categories as a substitution for the default ones.

```js
const categories = options.categories || defaultCategories;
```

**Comment by slohmes** [comment]
@aslushnikov Cool. I opened a PR, do you mind taking a look?https://github.com/GoogleChrome/puppeteer/pull/1439

**Comment by aslushnikov** [comment]
For this to be closed: 
- a `jssampling` option should be added to enable js sampling.
The option should add a `disabled-by-default-v8.cpu_profiler.hires` category to the default sampling categories.

**Comment by vaibhavtripathi** [comment]
@aslushnikov @paulirish I setup tracing as:
`page.tracing.start({path: 'tab.trace', screenshots: false, catgories: ['devtools.timeline']});`
I am still getting events from other categories. Is this a bug? Can this issue be repoened?

**Comment by TomasHubelbauer** [comment]
I'm seeing the same issue. Even though `categories` is set, events from other categories still come. According to the PR, this I don't think should be the case. Has anything changed?

**Comment by mathiasbynens** [comment]
@vaibhavtripathi There's a typo in your script (`catgories` instead of `categories`). If this issue still persists in the latest version of Puppeteer, please file a new bug with an example script that reproduces the problem.

**Comment by levesquejf** [comment]
The `categories` parameter of `Tracing.start` is now deprecated. Probably need to use `traceConfig` instead (src: https://chromedevtools.github.io/devtools-protocol/tot/Tracing/#type-TraceConfig).

**Comment by TomasHubelbauer** [comment]
I have looked into this and I am using the `traceOptions` argument with the `categories` field set on it. I can still reproduce this issue, see this repo: https://github.com/tomashubelbauer/globe-perf

**Comment by joshgoodwin** [comment]
Anyone working on a patch for this? I may take a run at it ... looks simple enough here:
https://github.com/puppeteer/puppeteer/blob/main/src/common/Tracing.ts
