### ISSUE TITLE
[Bug]: Browser Navigation Issue with Specific URLs When Using Library for Automated Execution

### ISSUE THREAD

**Issue by hara322** [puppeteer/puppeteer#13008]
### Minimal, reproducible example

```TypeScript
test.js

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 10,
  });
  const page = await browser.newPage();
  await page.goto('private_login_url');
　　　　await page.goto('new_private_url');
})();
```

### Background

When using your library for automated execution in the browser, we're encountering an issue where the screen cannot transition to certain URLs.
Specifically, in test.js, when trying to navigate to private_url and open a new UI page by transitioning to a link with parameters, we encounter an error that prevents the initialization of the destination screen.

Example
When using the standalone CCP-V2
https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-upcoming-changes.html
It's worth noting that when we use a local browser without Puppeteer, the screen transition works without any issues. This leads us to believe that the error might be library-dependent.

<img width="1196" alt="スクリーンショット 2024-08-27 16 47 09" src="https://github.com/user-attachments/assets/b3e1ead1-d88e-4548-8d96-63e3674b2977">

<img width="929" alt="スクリーンショット 2024-08-27 16 48 00" src="https://github.com/user-attachments/assets/a2361778-eb2e-4827-84ab-5fa742554f2c">

### Expectation

We want to display the screen that is shown when not using Puppeteer.

### Reality

In the developer tools console, we see the following error logs:

[FATAL] CSM initialization failed! Please make sure the sharedWorkerUrl is reachable.

connect-csm.js

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>xxxxx</RequestId><HostId>xxxx</HostId></Error>

### Puppeteer version

23.2.0

### Node version

v16.18.1

### Package manager

npm

### Package manager version

8.19.2

### Operating system

macOS

**Comment by OrKoN** [comment]
Please provide a complete executable script that we could run to reproduce the issue.

**Comment by hara322** [comment]
Thank you for your reply.
Is there a way to share the private URL while maintaining security?
Since it's difficult without sharing the actual account, would a video capture not be sufficient?

**Comment by OrKoN** [comment]
Could you create a public URL that demonstrates the issue? note that based on the screenshot, it looks like it is the page error that is not related to the browser navigation. It is possible that it is a bug in the app or the app is blocking automation.

**Comment by OrKoN** [comment]
it looks like it could not load worker files it needs.

**Comment by OrKoN** [comment]
Perhaps you could open the Network panel in DevTools and see what blocks the script.
