### ISSUE TITLE
[Bug]: Can't run on linux

### ISSUE THREAD

**Issue by spencer17x** [puppeteer/puppeteer#13019]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'

const browser = await puppeteer.launch();
const page = browser.newPage();
await page.goto('xxxx');
```

### Background

Run timeout.
Sysmtem:Linux version 5.14.0-70.13.1.el9_0.x86_64 (mockbuild@dal1-prod-builder001.bld.equ.rockylinux.org) (gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9), GNU ld version 2.35.2-17.el9) #1 SMP PREEMPT Wed May 25 21:01:57 UTC 2022

### Expectation

Run on linux

### Reality

Run timeout.

### Puppeteer version

23.2.1

### Node version

v16.17.0

### Package manager

pnpm

### Package manager version

7.14.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Please make sure your Linux system fulfills the system requirements https://pptr.dev/guides/system-requirements It might be useful to inspect browser logs (https://pptr.dev/guides/debugging#print-browser-logs) to see if any system dependencies are missing or if there are any other errors. Node 16 is also not supported by Puppeteer.
