### ISSUE TITLE
[Bug]: "TimeoutError: Navigation timeout of 30000 ms exceeded" in Firefox using protocol: 'cdp'

### ISSUE THREAD

**Issue by Mbaspfd** [puppeteer/puppeteer#13018]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
const browser = await puppeteer.launch({ 
    defaultViewport: null,
    browser: 'firefox',
    protocol: 'cdp',
    headless: false,
    executablePath: 'C:\\Program Files\\Mozilla Firefox\\firefox.exe'
});

  const page = (await browser.pages())[0];
  await page.goto('https://google.com');

})();
```

### Expectation

Navigate to a site without errors

### Reality

When trying to open a site in Firefox using the protocol: 'cdp' I always get the error TimeoutError: Navigation timeout of 30000 ms exceeded.
Although a site is fully loaded.
There is no such problem using the protocol: 'webDriverBiDi'

### Puppeteer version

23.2.0

### Node version

22.3.0

### Package manager

npm

### Package manager version

10.8.3

### Operating system

Windows

**Comment by OrKoN** [comment]
The CDP support for Firefox is deprecated and won't get updates or fixes. Please use webDriverBiDi for this, thanks! cc @whimboo in case you want to investigate on the Firefox side.

**Comment by whimboo** [comment]
Thanks for informing but as @OrKoN said CDP support is deprecated and we do not want to spent more time on it.

**Comment by Mbaspfd** [comment]
> The CDP support for Firefox is deprecated and won't get updates or fixes. Please use webDriverBiDi for this, thanks! cc @whimboo in case you want to investigate on the Firefox side.

Is there a way to connect to an already running Firefox  browser when the webDriver BiDi protocol is used?

**Comment by OrKoN** [comment]
> > The CDP support for Firefox is deprecated and won't get updates or fixes. Please use webDriverBiDi for this, thanks! cc @whimboo in case you want to investigate on the Firefox side.
> 
> Is there a way to connect to an already running Firefox browser when the webDriver BiDi protocol is used?

yes, it should work the same way as with CDP by providing the websocket endpoint URL to the connect options. Although you might need to launch Firefox with WebDriver BiDi enabled (@whimboo is there a documentation how to launch Firefox for BiDi without Puppeteer?).

**Comment by whimboo** [comment]
There is no difference for BiDi. Just use the `--remote-debugging-port %port` argument and the Remote Agent will be started which handles both WebDriver BiDi and the now deprecated CDP protocol.
