### ISSUE TITLE
[Bug]: page.goto() gives error while running on c-panel node server

### ISSUE THREAD

**Issue by Kash5622** [puppeteer/puppeteer#13016]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
                    executablePath: '/usr/bin/chromium-browser'
                });
                const page = await browser.newPage();
                
                await page.goto("https://www.bayut.com/for-sale/property/uae/")
await browser.close();
```

### Background

These error are coming while execute the code
App 1039122 output:     at /home/clikviewstorage/scrapernode.clikviewstorage.com/index.js:98:28
App 1039122 output:     at CdpPage.goto (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:567:31)
App 1039122 output:     at CdpPage.mainFrame (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:391:35)
App 1039122 output:     at FrameManager.mainFrame (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:204:32)
App 1039122 output:     at assert (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
App 1039122 output: /home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18

### Expectation

I expect it open the particular website.

### Reality

These error are coming while execute the code
App 1039122 output:     at /home/clikviewstorage/scrapernode.clikviewstorage.com/index.js:98:28
App 1039122 output:     at CdpPage.goto (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:567:31)
App 1039122 output:     at CdpPage.mainFrame (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:391:35)
App 1039122 output:     at FrameManager.mainFrame (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:204:32)
App 1039122 output:     at assert (/home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18:15)
App 1039122 output: /home/clikviewstorage/nodevenv/scrapernode.clikviewstorage.com/20/lib/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:18

### Puppeteer version

23.0.1

### Node version

20.13.1

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Linux

**Comment by OrKoN** [comment]
I am not able to reproduce:

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
const page = await browser.newPage();
                
await page.goto("https://www.bayut.com/for-sale/property/uae/");
await browser.close();
```

runs without errors. Please make sure you run the latest version of Puppeteer and use the Chrome version bundled with Puppeteer (https://pptr.dev/supported-browsers).

**Comment by Kash5622** [comment]
yeah it runs perfectly on windows but gives error on cloud Linux
