### ISSUE TITLE
[Bug]: Window appears after launch()

### ISSUE THREAD

**Issue by TiAlRo** [puppeteer/puppeteer#13012]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

puppeteer.launch();
```

### Expectation

I expect no visual output.

### Reality

A window appears.

### Puppeteer version

23.2.0

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Windows

**Comment by tumeraltunbas** [comment]
In my case after updating puppeteer from 23.0.2 to 23.2.0, I'm struggling with same case. After launch(), a browser(?) are opened on my screen. I'm attaching an image of case. 
![image](https://github.com/user-attachments/assets/c72d77d9-65bc-4830-8f7d-b2f71440266a)

**Comment by OrKoN** [comment]
Looks like a Windows-specific bug in Chrome M128 https://crbug.com/362706121

**Comment by gian1200** [comment]
This also happens in headless mode on Windows (Karma test) starting v23.1.1.
v23.1.0 is not affected.

**Comment by GladistonXD** [comment]
I worked around it using:
`'--window-position=-10000,-10000'`
but I think it's not ideal

**Comment by UCPr251** [comment]
try `--headless=old`

**Comment by PBHansen** [comment]
This is also happening in puppeteer-core v. 13.5.2 (matches puppeteer versioning afaik), which is several years old.
On several windows machines
Also installed using NPM
Node -v 20.17.0

async function GetNewBrowser(headless = true) {
    return await puppeteer.launch({
      executablePath: chromePaths.chrome,
      headless: headless,
      args: ["--incognito"],
    });
}

**Comment by Lightning00Blade** [comment]
Closed as https://github.com/puppeteer/puppeteer/pull/13195 please one a new issue if this is still happening.
Will be release with Puppeteer v23.6.0.

**Comment by TiAlRo** [comment]
Cool, the bug is solved! Thanks! :)
