### ISSUE TITLE
Page Type Not Working

### ISSUE THREAD

**Issue by shmdhussain** [puppeteer/puppeteer#1302]
### Steps to reproduce
I am trying to type into the text field which is present in the page using the page.type api as in the code 

`(function (exports, require, module, __filename, __dirname) { const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({

        headless: false,
        executablePath: '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome',
        args: ["--window-size=2400,1239"]

    });
    const page = await browser.newPage();
    await page.setViewport({width: 2300, height:1239});

    await page.goto('https://www.google.ae' ,{
        waitUntil: 'load'
    });
    // await page.waitFor("#username");
    await page.type("#lst-ib", "test");
})();
});`

I debugged in console  after I run the above script, what is happening is

Page opens and I am getting the following error in the console see the screenshot attached
string is not typed into the input

![screen shot 2017-11-07 at 16 54 57](https://user-images.githubusercontent.com/4039657/32494711-202a7dd6-c3dc-11e7-889a-88def0229371.png)

My system info
* Puppeteer version:0.12.0
* Platform / OS version:Mac 10.10.5
* URLs (if applicable):

**Comment by aslushnikov** [comment]
I see you run your own chrome instance:
```
   executablePath: '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome',
```
What's the version of the chrome you run?

**Comment by shmdhussain** [comment]
Using chrome Version 62

**Comment by aslushnikov** [comment]
@shmdhussain that's too old; puppeteer 0.12 should work fine with chrome M64

If you need chrome instead of chromium, I'd suggest using Chrome Canary.

**Comment by shmdhussain** [comment]
@aslushnikov Thanks lot now it is working ... I was scratching my head, I didnt know it wont work with chrome 62...I thought it is latest stable, so it will work
