### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xonaman** [puppeteer/puppeteer#13027]
### Minimal, reproducible example

```TypeScript
console.log('Launching browser...');
  const browser = await puppeteer.launch({
    dumpio: true,
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    ignoreHTTPSErrors: true,
    devtools: false,
  });
  console.log('Browser launched:', await browser.version());

  console.log('Loading page...');
  const page = await browser.newPage();
  await page.setContent(/*some-html*/, { waitUntil: 'networkidle0' });
  console.log('Page loaded.');

  console.log('Generating pdf...');
  const buffer = await page.pdf({ format: 'a4' });
  console.log('Pdf generated:', buffer.length, 'bytes');
```

### Background

Hey, I am receiving the following error when working with chromium.

```json
{
  "errorType": "Error",
  "errorMessage": "require() of ES Module /opt/node_modules/get-stream/source/index.js from /opt/node_modules/extract-zip/index.js not supported.\nInstead change the require of /opt/node_modules/get-stream/source/index.js in /opt/node_modules/extract-zip/index.js to a dynamic import() which is available in all CommonJS modules.",
  "trace": [
    "Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/node_modules/get-stream/source/index.js from /opt/node_modules/extract-zip/index.js not supported.",
    "Instead change the require of /opt/node_modules/get-stream/source/index.js in /opt/node_modules/extract-zip/index.js to a dynamic import() which is available in all CommonJS modules.",
    "    at Object.<anonymous> (/opt/node_modules/extract-zip/index.js:4:19)"
  ]
}
``` 

### Expectation

I was using `@sparticuz/chromium^122.0.0` and `puppeteer-core^22.5.0` which worked perfectly fine until now. Probably some dependency, `get-stream` or `extract-zip` had an update.

### Reality

I don't know if that comes from chromium or puppeteer.

I tried upgrading to `@sparticuz/chromium^127.0.0` and `puppeteer-core^23.2.1` but got the exact same error.

Can someone please point me in the right direction?

### Puppeteer version

23.2.1

### Node version

22.7.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Linux

**Comment by OrKoN** [comment]
I am not able to reproduce the issue. Since you use @sparticuz/chromium, are you running on AWS Lambda? Is the Node version different there?  Note that also Puppeteer uses extract-zip dependency, puppeteer-core would not use it because it does not download the browsers by default. I would suggest raising the issue with @sparticuz/chromium to see if it is only reproducible with it. Neither get-stream or extract-zip had updates recently.

**Comment by xonaman** [comment]
@OrKoN okay, thank you. Will do.

**Comment by AhmedBHameed** [comment]
Hey @xonaman 

Did you find a solution ? I am encounter with the same issue.

thank you in advance.

**Comment by xonaman** [comment]
@AhmedBHameed  this is my current workaround (`package.json`):

```json
{
  "overrides": {
    "get-stream": "6.0.1"
  }
}
```

Because `get-stream` was not an ESM module back then at version `6.0.1`.

**Comment by AhmedBHameed** [comment]
@xonaman 

Thank you for your rapid answer. I figured out that the issue from my side is related "ejs-lint". Downgrading to "^1.2.1" resolved my issue. Not sure if it is a good idea but it is just a linter after all.
