### ISSUE TITLE
[Bug]: Issue with PDF Download Using Puppeteer 19.2.2: Internal Server Error

### ISSUE THREAD

**Issue by ashu1230** [puppeteer/puppeteer#13034]
![Screenshot 2024-09-02 170614](https://github.com/user-attachments/assets/8985479b-3b44-48c0-81d4-ed25cf1b410a)
![image](https://github.com/user-attachments/assets/ad2d0e97-fa0b-4bf2-b910-73aef7b4fe31)

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

async function generatePDF(url, pdfPath) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle2' });

  await page.pdf({
    path: pdfPath,
    format: 'A4',
    printBackground: true,
  });

  await browser.close();
}

generatePDF('http://localhost:3033/api/v1/proposal/66222c0a46f185c690761e94/gen-pdf?utcOffset=330', 'output.pdf');
```

### Background

Troubleshooting Steps Taken:

- Verified that the server endpoint works correctly for other operations (e.g., PPT download).
- Checked the Puppeteer version to ensure compatibility.
- Investigated server logs but could not identify a clear issue.

### Expectation

PDF DOWNLOAD WITHOUT ANY ERROR

### Reality

Error Details:
When attempting to download a PDF, I receive a 500 Internal Server Error. Below is the detailed error response captured from the network:

Request:

bash
Copy code
POST https://acumensa-tech-production.up.railway.app/api/v1/proposal/66222c0a46f185c690761e94/share?utcOffset=330
Response:

json
Copy code
```
{
  "data": {
    "errors": {
      "statusCode": 500,
      "message": "Something went wrong!",
      "error": "Internal Server Error"
    },
    "url": "/api/v1/proposal/66222c0a46f185c690761e94/gen-pdf?utcOffset=330"
  },
  "statusCode": 500,
  "message": "Something went wrong!"
}
```
Steps to Reproduce:

1. Using Puppeteer 19.2.2, implement a function for PDF download.
2. Send a request to generate the PDF.
3. Observe the response in the network tab.

Observations:

1. The PPT download functionality works as expected with no issues.
4. The PDF download triggers an internal server error, which suggests that the problem might be server-side or related to the Puppeteer configuration for handling PDFs.

### Puppeteer version

19.2.2

### Node version

18.17.0

### Package manager

yarn

### Package manager version

18.17.0

### Operating system

Windows

**Comment by OrKoN** [comment]
Please try using the latest version of Puppeteer and provide a complete executable example that includes the test page for printing.
