### ISSUE TITLE
centos7.4 cannot install puppeteer because of EACCES error

### ISSUE THREAD

**Issue by zhuyingda** [puppeteer/puppeteer#1303]
My linux vps system info is here:

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core)
Release:	7.4.1708
Codename:	Core

I try to run ` npm install puppeteer@latest ` in my project dir, and got an error:

[root@iZ620vd4tb0Z webster-use]# npm i puppeteer@latest

> puppeteer@0.12.0 install /root/webster-use/node_modules/puppeteer
> node install.js

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/root/webster-use/node_modules/puppeteer/.local-chromium'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.downloadRevision (/root/webster-use/node_modules/puppeteer/utils/ChromiumDownloader.js:99:10)
    at Object.<anonymous> (/root/webster-use/node_modules/puppeteer/install.js:45:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.12.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-07T13_11_52_971Z-debug.log

**Comment by zhuyingda** [comment]
Also, I have changed my project folder `chmod 777`, and the problem still there.

**Comment by elodiegrondin** [comment]
I've got the same issue in my project.
I don't know why exactly but I solved it, using yarn cmd 
`yarn add puppeteer`

**Comment by zhuyingda** [comment]
I have solved my problem.
Actually it is not any problem about puppeteer, it is a problem about npm rule which I did not know.
In centos system(maybe most linux system),  when you run `npm install somepackage` by 'root' user,   you would got this error. It seems like puppeteer install.js do something and trigger this.

Here is my solution:
You can `npm config set unsafe-perm=true`, or you can `su otheruser` and then install puppeteer.

For more info about this npm rule, see [this](https://docs.npmjs.com/misc/config#unsafe-perm)

**Comment by henryatman** [comment]
this is very disgusting node issue，but finally i solved it，just little like above say，

i use com

```npm i -g puppeteer --unsafe-perm``` 

done! 

hope it help you also :)

**Comment by zhuyingda** [comment]
@henryatman I think this is not a node issue, but a security mechanism that we did not know.
Actually, we should not run some browser process as `root` user whenever, because it is not safe.
