### ISSUE TITLE
[Bug]: page.screenshot DataCloneError

### ISSUE THREAD

**Issue by Kikobeats** [puppeteer/puppeteer#13042]
Request Interception is not working at v23.2.2

### Minimal, reproducible example

before v23.2.2:

```TypeScript

page.on('request', req => req.continue()); // => works
```

### Reality

after v23.2.2:

```
page.on('request', req => req.continue());
// DataCloneError: async req => req.continue() could not be cloned.
//   at new DOMException (node:internal/per_context/domexception:53:5)
```

### Puppeteer version

23.2.2

### Node version

20.17.0

### Package manager

pnpm

### Package manager version

9.8.0

### Operating system

Test in Linux and macOS, both failed.

**Comment by OrKoN** [comment]
I am not able to reproduce with (Node 20.17.0):

```js
import puppeteer from "puppeteer";

const browser = await puppeteer.launch();

const page = await browser.newPage();

await page.setRequestInterception(true);
page.on('request', req => req.continue());

const response = await page.goto("https://example.com", { waitUntil: ['networkidle0'] });

console.log(response.status(), response.url())

await browser.close();
```

Please share a complete example that reproduces the issue for you.

**Comment by OrKoN** [comment]
A change that could cause something like that would be in page.screenshot() to use structuredClone since we dropped Node 16 a while ago: https://github.com/puppeteer/puppeteer/commit/6808a1798bcd0285d6c045c65b95df2700975a84 but I do not see how that would affect interception so perhaps the issue originates in some screenshot taking code. Is the Node version used 20.17.0?

**Comment by Kikobeats** [comment]
Closing for now since it seems it isn't a puppeter bug, it's seems to be buggy on my https://browserless.js.org/#/ wrapping. Let me debug better and report back 🙂

**Comment by Kikobeats** [comment]
@OrKoN this reproduces:

```
;(async () => {
  const puppeteer = await require('puppeteer')

  const browser = await puppeteer.launch()

  const page = await browser.newPage()

  await page.setRequestInterception(true)
  page.on('request', req => req.continue())

  const response = await page.goto('https://example.com', { waitUntil: ['networkidle0'] })

  await page.screenshot({
    thisMehodIsNotUsed: req => {
      return req.continue()
    }
  })

  console.log(response.status(), response.url())

  await browser.close()
})()
```

output

```
node test.js

node:internal/per_context/domexception:53
    ErrorCaptureStackTrace(this);
    ^
DOMException [DataCloneError]: req => {
      return req.continue()
    } could not be cloned.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at CdpPage.screenshot (~Desktop/index.js/node_modules/.pnpm/puppeteer-core@23.2.2/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:979:33)
    at async CdpPage.<anonymous> (~Desktop/index.js/node_modules/.pnpm/puppeteer-core@23.2.2/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:164:24)
    at async ~Desktop/index.js/test.js:37:3

Node.js v20.17.0
```

So in my code I'm passing down to `.screenshot` a method not used but internally puppeteer is serializing 🤔

**Comment by OrKoN** [comment]
Could you clarify why there is a need to pass down methods to the screenshot function that are not supported by Puppeteer?

**Comment by Kikobeats** [comment]
It's because browserless.js.io is performing a goto resolution before taking an screenshot and reusing the same props from an object

```js
await browserless.goto(opts)
await browserless.screenshot(opts)
```

Ideally that method should be not passed down. I can resolve this at my end, yes, but I think passing down a whole object quite expected in js world. Eventually any other user is going to report this, maybe puppeteer can just pick the stuff it needs?

**Comment by OrKoN** [comment]
> It's because browserless.js.io is performing a goto resolution before taking an screenshot and reusing the same props from an object
> 
> ```js
> await browserless.goto(opts)
> await browserless.screenshot(opts)
> ```
> 
> Ideally that method should be not passed down. I can resolve this at my end, yes, but I think passing down a whole object quite expected in js world. Eventually any other user is going to report this, maybe puppeteer can just pick the stuff it needs?

it is common, but unfortunately it is not very good for forward compatibility. If Puppeteer eventually adds new props to either of the commands and they conflict with previously provided but unused props, the behavior might be not compatible. We do not validate that extra props at runtime to avoid performance costs but it'd be better to use the APIs explicitly and ideally validate the interfaces using TypeScript.

**Comment by Kikobeats** [comment]
@OrKoN It seems to be resolved in v23.3.0, how is that possible?

**Comment by OrKoN** [comment]
@Kikobeats see the linked pull request

**Comment by Kikobeats** [comment]
Oh great, thanks!
