### ISSUE TITLE
[Bug]: ProtocolError: Network.enable timed out. Increase the 'protocolTimeout'

### ISSUE THREAD

**Issue by deepankar-sundial** [puppeteer/puppeteer#13048]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
            timeout: 0,
            headless: true,
            executablePath: "/usr/bin/chromium",
            args: ['--no-sandbox']
});

const page = await browser.newPage();
await page.setContent(html);
await page.waitForTimeout(1000);
const boundingBox = await page.evaluate(() => {
            const element = document.body;
            const rect = element.getBoundingClientRect();
            return {
                x: rect.x,
                y: rect.y,
                width: rect.width,
                height: rect.height,
            };
});

const imageBuffer = await page.screenshot({ type: 'png', clip: boundingBox });
await browser.close();
```

### Background

Have a simple use-case of loading on html content, screenshoting it

### Expectation

The code should work fine, as it was working.

### Reality

This works fine locally, and was also working fine on docker. untill july-august we started getting a log

```
[Bug]: ProtocolError: Network.enable timed out. Increase the 'protocolTimeout'
```

Acc to a lot of issues already reported https://github.com/puppeteer/puppeteer/issues/11640 

looks like chromium new version published the time introduced this issue. 

Adding `--disable-gpu` flag helped fix this issue.

### Puppeteer version

21.6.0

### Node version

18

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by deepankar-sundial** [comment]
We had observed a lot of spikes in CPU core usage when this function was called.

# The FIX

Adding `--disable-gpu` flag helped fix the timeout issue + CPU spikes returned to normal.

**Comment by OrKoN** [comment]
I am unable to reproduce with the latest Puppeteer version on MacOS:

```
import puppeteer from "puppeteer";

const browser = await puppeteer.launch({
  timeout: 0,
  headless: true,
  args: ['--no-sandbox']
});

const page = await browser.newPage();
await page.setContent(``);
const boundingBox = await page.evaluate(() => {
  const element = document.body;
  const rect = element.getBoundingClientRect();
  return {
      x: rect.x,
      y: rect.y,
      width: rect.width,
      height: rect.height,
  };
});

const imageBuffer = await page.screenshot({ type: 'png', clip: boundingBox });
await browser.close();
```

If `--disable-gpu` flag helps for your environment, you can use it. Note that it disables hardware acceleration and it is generally slower than software acceleration.

**Comment by OrKoN** [comment]
I could not find any relevant changes in Chromium but please file an issue at https://crbug.com/new Include the details about the version where it worked and the version in which it was started breaking, and please update the reproducible example so that it can actually demonstrate the issue.

**Comment by chrisli-03** [comment]
Still having this issue in 24.11.2, --disable-gpu didn't help

**Comment by afishhhhh** [comment]
24.16.1 same issue.
