### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by huangfuying98** [puppeteer/puppeteer#13053]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-core/lib/esm/puppeteer/puppeteer-core-browser.js';

async function onConnectClick() {
  const wsUrl = document.querySelector('#ws').value;

  const browser = await puppeteer.connect({
    browserWSEndpoint: wsUrl,
  });

  alert('Browser has ' + (await browser.pages()).length + ' pages');

  browser.disconnect();
}

globalThis.onConnectClick = onConnectClick;
```

### Background

BrowserWebSocketTransport-D_zAGZMQ.js:7  
WebSocket connection to 'ws://127.0.0.1:50777/devtools/browser/xxxxxxxxxxxx' failed:
at：
create | @ | BrowserWebSocketTransport-D_zAGZMQ.js:6
getConnectionTransport	@	main.js:21219

I am sure that use nodejs can connection to this webSocketDebuggerUrl but web can't connection .

![image](https://github.com/user-attachments/assets/cbdb1b12-7e58-405a-9f3a-f7eea66ee112)

### Expectation

use puppeteer in browser

### Reality

WebSocket connection to 'ws://127.0.0.1:50777/devtools/browser/xxxxxxxxxxxx' failed

### Puppeteer version

puppeteer-core@23.1.0

### Node version

v20.16.0

### Package manager

npm

### Package manager version

1.0

### Operating system

Windows

**Comment by OrKoN** [comment]
You are probably missing https://peter.sh/experiments/chromium-command-line-switches/#remote-allow-origins when launching the browser. Try `--remote-allow-origins=*` to enable all origins but, in general, make sure to only allow trusted origins.
