### ISSUE TITLE
[Bug]: possibly easy fix? A4 dimensions doesn't match actual a4 specification

### ISSUE THREAD

**Issue by DCh06** [puppeteer/puppeteer#13050]
### Minimal, reproducible example

```TypeScript
// works
export const createPDFA4 = async (htmlString) => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlString);
    const pdfBuffer = await page.pdf({path:'x.pdf' , width: "210mm", height: "297mm" });
    await browser.close();

    return Buffer.from(pdfBuffer)
};

// doesnt work
export const createPDFA4 = async (htmlString) => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(htmlString);
    const pdfBuffer = await page.pdf({path:'x.pdf' , format: 'A4' });
    await browser.close();

    return Buffer.from(pdfBuffer)
};
```

### Background

Im trying to create pdf. 3rd party app has a4 validation. When created with ...format: 'A4'..., validator rejects my file. Creating it with set dimensions doesnt have this problem.

Tested on macOS and windows 10

### Expectation

format:'A4' to create exact A4 format 210x297mm

### Reality

there is very small difference, cannot pass through some A4 validators, final format is 210.227 x 297.349

### Puppeteer version

23.2.2

### Node version

v20.9.0

### Package manager

npm

### Package manager version

10.1.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Yeah, Puppeteer defines a4 in inches (8.27 x 11.7 in) because Chrome DevTools Protocol accepts inches for printing and that is probably not precise enough for validators.

**Comment by hangyeol0531** [comment]
I requested PR related to the issue.

https://github.com/puppeteer/puppeteer/pull/13087

**Comment by OrKoN** [comment]
should be closed via https://github.com/puppeteer/puppeteer/pull/13087
