### ISSUE TITLE
Error: spawn UNKNOWN on launch()

### ISSUE THREAD

**Issue by dbauszus-glx** [puppeteer/puppeteer#1305]
Having used puppeteer less than two weeks ago I am no longer able to launch puppetteer on my Windows machine. The launch still works on a Mac Book. The code, or versions have not changed.

Pupetteer 0.12
Node 8.4

All examples are copied straight from the puppeteer api documentation. e.g.

    puppeteer.launch().then(async browser => {
        const page = await browser.newPage();
        await page.goto('https://example.com');
        await page.screenshot({path: 'example.png'});
        await browser.close();
    });

The .launch() always ends in Error: spawn UNKNOWN

**Comment by aslushnikov** [comment]
@dbauszus-glx it looks like the puppeteer doesn't have a chromium instance to start. Can you please:
- check if there's a `.local-chromium` folder in the `node_modules/puppeteer`
- try launching chromium from `.local-chromium` manually

**Comment by dbauszus-glx** [comment]
I thought so initially and reinstalled Chromium but this isn't it. Chromium is installed and runs manually. puppeteer.executablePath() returns the correct path which starts chromium straight away.

**Comment by dbauszus-glx** [comment]
This is bizarre... I remember now what was different when puppeteer was working on my machine. I was evaluating visual studio code. I just started VS Code again and sure enough puppeteer just works. Not a single line of code has changed, no installs, no environment settings. While when started through WebStorm; Puppeteer bombs out on launch every single time.

**Comment by ebidel** [comment]
@dbauszus-glx this sounds like an editor configuration that's affecting your Node env...? Are you launching your puppeteer script from Webstorm or vscode or running it from the CLI?

**Comment by dbauszus-glx** [comment]
Yes, I am trying to launch puppeteer from script.

I double checked the launch configurations. They look to be the same for Webstorm and VSC. Anyways you can close this issue. I will post this to the Webstorm support if it becomes a problem again. Will continue to work with VSC on this project.
