### ISSUE TITLE
[Bug]: Accessing http will intercept https

### ISSUE THREAD

**Issue by chenxicore** [puppeteer/puppeteer#13068]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    devtools: true,
    timeout: 60000,
    protocolTimeout: 0,
    ignoreHTTPSErrors: true,
    args: [
      "--no-first-run",
      "--max-old-space-size=512",
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--disable-web-security",
      "--disable-xss-auditor",
      "--no-zygote",
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--allow-running-insecure-content",
      "--disable-webgl",
      "--disable-popup-blocking",
      "--disable-features=site-per-process"
    ],
  });
  const url = "http://testphp.vulnweb.com/";
  const page = await browser.newPage();

  await page.setRequestInterception(true);
  page.on("request", (req) => {
    console.log(" ----------------->  request: ", req.url(), page.url(), req.method());
    req.continue();
  });
  
  await Promise.all([
    page.goto(url, {
      waitUntil: [
        "load",
        "domcontentloaded",
        "networkidle0",
        "networkidle2",
      ],
      timeout: 30000,
    }),
    page.waitForNavigation({ waitUntil: ["load", "networkidle2"], timeout: 30000}),
  ]);


})();
```

### Background

There is no https request on the site itself, but https will be intercepted

### Expectation

Do not block addresses that do not exist. For example, https://testphp.vulnweb.com/

### Reality

Blocked address: https://testphp.vulnweb.com/
![2dbc8279-b589-4611-accf-6cd1d88a9b70](https://github.com/user-attachments/assets/e8f96f59-4e88-4c4d-b5ac-dd2714671fbf)

### Puppeteer version

23.1.0

### Node version

v20.13.1

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
It seems that this request is the automatic upgrade Chrome tries to perform from HTTP to HTTPS, https://chromestatus.com/feature/6056181032812544
You can try and use `"--disable-features=HttpsUpgrades",` to disable this feature.

**Comment by chenxicore** [comment]
> It seems that this request is the automatic upgrade Chrome tries to perform from HTTP to HTTPS, https://chromestatus.com/feature/6056181032812544 You can try and use `"--disable-features=HttpsUpgrades",` to disable this feature.

puppeteer@20.5.0 Is this normal without this problem?

**Comment by Lightning00Blade** [comment]
You can see on the [supported browser page ](https://pptr.dev/supported-browsers) 
That that version of [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) is 114.0.5735.90,
where the feature did not exist yet.
