### ISSUE TITLE
any target="_blank" solution?

### ISSUE THREAD

**Issue by yfcck** [puppeteer/puppeteer#1307]
These codes can not be solved

https://stackoverflow.com/questions/45806684/puppeteer-how-to-handle-multiple-tabs

https://github.com/GoogleChrome/puppeteer/issues/386

puppeteer：v0.12.0
centos:7.2

**Comment by aslushnikov** [comment]
This is already supported on tip-of-tree pptr, v0.13.0.

It's not released yet on NPM, but 
you can install it from github to help us dogfooding it: `npm install https://github.com/GoogleChrome/puppeteer`
