### ISSUE TITLE
[Bug]: ng e2e --base-url="http://localhost:4200/" results in "Error:  Unknown argument: base-url" with Angular v17.3.9

### ISSUE THREAD

**Issue by PanchoPuncho** [puppeteer/puppeteer#13070]
### Steps to reproduce

ng e2e --base-url="http://localhost:4200/"

results in "Error: Unknown argument: base-url" with Angular v17.3.9 and puppeteer-core

### Expected results

Run e2e tests without spawning the test server.

### Actual results

Error: Unknown argument: base-url

### @puppeteer/ng-schematics version

0.6.1

### Angular CLI version

Angular CLI: 17.3.9
Node: 20.12.2
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 17.3.12
... compiler-cli, core, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.9
@angular-devkit/build-angular   17.3.9
@angular-devkit/core            17.3.9
@angular-devkit/schematics      17.3.9
@angular/cli                    17.3.9
@schematics/angular             17.3.9
rxjs                            7.5.7

**Comment by Lightning00Blade** [comment]
This feature is only available for version `^0.7.0` .
