### ISSUE TITLE
[Feature]: Implement delay to click

### ISSUE THREAD

**Issue by FritzHerbers** [puppeteer/puppeteer#13078]
### Feature description

We are using Chrome recorder, make some small delay adaptions to the recording and export puppeteer Javascript files.

We have to add slight delays to clicks, as a previous input change is processed at the next Angular 'tick' via rxjs, and are not yet available when clicked. (In Chrome recorder and in puppeteer headfull mode we like to see the UI changes, before clicked when replaying a recording).

The exported puppeteer files have a "delay", but puppeteer does not process them as they are not defined in `ClickOptions` or `MouseClickOptions`. 
https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.clickoptions.md

As we would like to make as less changes to the exported files; Please implement delay for click.

```
    {
        const targetPage = page;
        await delay(2000);  <---- have to adapt the puppeteer file and add a delay 
        await puppeteer.Locator.race([
            targetPage.locator('::-p-xpath(//*[@data-test=\\".FORM_MAIN.mainInclude.buttonsInclude...validateButton\\"])'),
            targetPage.locator('::-p-text(Validate Request)')
        ])
            .setTimeout(timeout)
            .click({
              delay: 2000,     <---- contained in the exported puppeteer file, but is not interpreted by puppeteer
              offset: {
                x: 57.8499755859375,
                y: 5.5999755859375,
              },
            });
    }

// the used delay function
function delay(milliseconds) {
    return new Promise((resolve) => setTimeout(resolve, milliseconds));
}
    ```

**Comment by Lightning00Blade** [comment]
You can see that it's defined here on the [MouseClickOptions](https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.mouseclickoptions.md)
And the implementation is here https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/Input.ts#L450.
