### ISSUE TITLE
[Bug]: Page.frames() returns only main frame in chrome extension

### ISSUE THREAD

**Issue by zibsonzs** [puppeteer/puppeteer#13089]
### Minimal, reproducible example

```TypeScript
import {
  connect,
  ExtensionTransport,
  Page,
} from "puppeteer-core/lib/cjs/puppeteer/puppeteer-core-browser.js";

From isolated content:
 await chrome.runtime.sendMessage({type:"init"});

In background worker:

chrome.runtime.onMessage.addListener((message, sender, sendResponse)=>{
if(message.type !== "init")
return;

 const browser = await connect({
    transport: await ExtensionTransport.connectTab(sender.tab.id),
    defaultViewport: null,
  });

  const webNavigationFrames = await chrome.webNavigation.getAllFrames(); // returns valid frames

  const pages = await browser.pages();
  const page = pages[0];
  const frames = page.frames();
   // frames return only main frame. I also tried to create Page object in setInterval to make sure frames are not loaded later but it didn't work
}
```

### Background

chrome.webNavigation.getAllFrames() finds all the frames while page.frames() do not.
I tried page.waitForFrame() and some other tricks with disconnecting, connecting the page again after a while but it just doesn't work.

### Expectation

page.frames() to return all iframes from the page

### Reality

It's returning only main frame

### Puppeteer version

23.3.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Windows

**Comment by OrKoN** [comment]
How many frames to do you have in the tab you connect to? Could you publish a test extension in a separate repo and the test page you use?

**Comment by zibsonzs** [comment]
Html is pretty simple. I have just a simple div and a simple iframe next to it.
```
 <div>
          <button
            onClick={() => {
              load();
            }}
          <iframe name="__tcfapiLocator" src="https://onet.pl" width="600" height="400"></iframe>
        </div>
```

I will try to come up with a simple extension to reproduce the issue tomorrow.

**Comment by OrKoN** [comment]
I do not seem to be able to reproduce in my test, would appreciate if you provide an extension that demonstrates the issue!

<img width="711" alt="Screenshot 2024-09-17 at 09 14 59" src="https://github.com/user-attachments/assets/c3d67f2e-ce44-4277-a2fc-37e2ef183bb7">

Also, consider using https://pptr.dev/api/puppeteer.page.waitforframe/ to wait for the frame to appear.

**Comment by OrKoN** [comment]
Actually, I seem to be able to reproduce it. Although I see two frames, the second frame is not the right one.
