### ISSUE TITLE
[Feature]: Distinguish between different `Touch`es

### ISSUE THREAD

**Issue by emilefokkema** [puppeteer/puppeteer#13084]
### Feature description

Currently, the [`touchMove()`](https://pptr.dev/api/puppeteer.touchscreen.touchmove) method on the `TouchScreen` class takes two parameters, `x` and `y`. But there is no way to specify _which_ of the touches you want to move. (Because multiple touches [can be active](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/targetTouches) at any given time.)

Proposal: change the signature of [`TouchScreen.touchStart`](https://github.com/puppeteer/puppeteer/blob/280e6f82065a2cbbe696673934a9c10610a780c6/packages/puppeteer-core/src/api/Input.ts#L498) to
```ts
abstract touchStart(x: number, y: number): Promise<Touch>
```
where `Touch` would be something like
```ts
interface Touch {
    move(x: number, y: number): Promise<void>
    end(): Promise<void>
}
```
This way it would be perfectly clear which of the touches you're moving or ending. (The presence of the optional `id` property [in the parameters](https://chromedevtools.github.io/devtools-protocol/tot/Input/#type-TouchPoint) to the CDP `Input.dispatchTouchEvent` command at least suggests that something like this is possible.)

**Comment by lballard625015** [comment]
Can I work on this one?

**Comment by OrKoN** [comment]
We need to consider that the API should compatible with WebDriver BiDi as well: https://w3c.github.io/webdriver-bidi/#command-input-performActions

In general, I think the proposed API makes sense.

**Comment by emilefokkema** [comment]
@OrKoN @Lightning00Blade One way to answer my question above is to look at the current behavior. [This test](https://github.com/emilefokkema/puppeteer/commit/45469a703ae3bee7788c33e534b57ce6b2e734d3) (run against chrome-headless) seems to show that the current behavior of

```ts
await page.touchscreen.touchStart(100, 100);
await page.touchscreen.touchStart(200, 200);
await page.touchscreen.touchMove(150, 150);
```

is exactly the same as if it had been

```ts
await page.touchscreen.touchStart(100, 100);
await page.touchscreen.touchMove(200, 200);
```
The second `touchStart` does not result in a new touch at all. So I don't know if this new feature can be implemented in a backwards-compatible way.

**Comment by emilefokkema** [comment]
@ritk20 It does look that way, yes. Unless the [test](https://github.com/emilefokkema/puppeteer/commit/45469a703ae3bee7788c33e534b57ce6b2e734d3) that I wrote has wrong assumptions somewhere. But the question (to @OrKoN or @Lightning00Blade ?) is also: if the test is right and this is in fact the current behavior, then is it a bug or a feature? Because if it is a bug, then the current feature can be implemented in a backwards-compatible way. But if it is a feature, then it cannot (I think).
