### ISSUE TITLE
[Bug]: Unable to render page

### ISSUE THREAD

**Issue by sfresta** [puppeteer/puppeteer#13098]
### Minimal, reproducible example

```TypeScript
const puppeteer_module    = require('puppeteer');
const browser = await puppeteer_module.launch({headless: false});
const page = await browser.newPage();
await page.goto("https://go.affision.com/login/");
```

### Expectation

![screencapture-go-affision-login-2024-09-17-15_11_43](https://github.com/user-attachments/assets/7e35c559-27e7-4c5f-ad47-7419de3f71db)

### Reality

White screen. Seems that the script inside <head> tag is not executed and then the page is not loading.

### Puppeteer version

23.3.1

### Node version

20.17.0

### Package manager

npm

### Package manager version

10.8.3

### Operating system

Linux

**Comment by OrKoN** [comment]
I am able to reproduce but I do not see an issue with Puppeteer. It appears that this web site detects automation and blocks access to the page. Overcoming this sort of protections is out of scope for Puppeteer.
