### ISSUE TITLE
[Bug]: Some pages not loading when using Docker

### ISSUE THREAD

**Issue by omirobarcelo** [puppeteer/puppeteer#13107]
### Minimal, reproducible example

```TypeScript
Since all together is a bit of code, I attach some gists with the minimal reproducible example.

Node.js code  
https://gist.github.com/omirobarcelo/a459f1b4fa6b47b6fb351eba477564fe

Dockerfile  
https://gist.github.com/omirobarcelo/e2f94ac55a2157b6cfeefdf79d6df4ef

Docker Compose  
https://gist.github.com/omirobarcelo/d9c42be9172f0152134ff6402bfd25d4
```

### Background

The goal is to load a page and obtain some cookies that we need to query the backend directly.

This example tries to load the page, resolves captchas if there are any, rejects cookies, waits for an arbitrary selector (an input field), and saves the page cookies into a file.  
We are also using the packages `"puppeteer-extra"`, `"puppeteer-extra-plugin-recaptcha"`, and `"puppeteer-extra-plugin-stealth"`.

And we want to dockerize this code so it can run in Azure. 

### Expectation

The expectation is that the page loads so we can interact enough with it to obtain the cookies and that we can dockerize this code.

### Reality

If I try with https://google.com, it works when I run the code directly in my machine in headless mode and when I dockerize it. But if I try https://www.rentalcars.com, it works when I run the code directly in my machine in headless mode, but when I dockerize it the page never fully loads, so I cannot resolve captchas or even get the contents of the page through `page.content()`, it ends up failing with a `ProtocolError: Runtime.callFunctionOn timed out`.

In some occasions I see that some network requests do not complete, but it is not consistent. As in some times the GTM scripts loads and other times not. It seems in general it has trouble with JavaScript files.

It is worth noting that the main cookie to obtain is a [Reese84](https://github.com/BottingRocks/Incapsula), used for fingerprinting. I do not know if that could be the problem, or maybe I am missing some libraries required for it in the Docker installation. I checked and all the packages mentioned in [here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) and [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/debian/dist_package_versions.json) are installed in the Dockerfile. 

EDIT1: I tried updating the navigation to
```
  await page.goto(url, {
    waitUntil: 'networkidle2',
  });
```
And it failed with `TimeoutError: Navigation timeout of 120000 ms exceeded`.

### Puppeteer version

22.15.0

### Node version

20.13.0

### Package manager

npm

### Package manager version

10.5.2

### Operating system

macOS

**Comment by Lightning00Blade** [comment]
Could you try to provide a version of the code that show the issue, but without using packages other then `puppeteer`, as we don't maintain those ourself. 
I also see that you are using custom image, does the issue reproduce with our official image? 
[Puppeteer Docker](https://pptr.dev/guides/docker)

**Comment by DaWe35** [comment]
I had a similar issue (maybe):

Docker image: node:20-alpine
Puppeteer: "^23.4.0"

Localhost (127.0.0.1) times out.

When I turn on line-by-line debugging, or use `slowMo: 10` then it works.

Line-by-line debugging revealed that if I don't stop the debugger between these lines, then it times out:
```
                const browser = await puppeteer.launch({
                    executablePath: process.env.PUPPETEER_EXECUTABLE_PATH,
                    args: ['--no-sandbox'],
                    slowMo: 10, // slow down by 10ms. I don't know why, but without slowMo, it gets stuck and returns a timeout eventually.
                    timeout: 5000,
                });

                const page = await browser.newPage();
                ```
                
                Can this be a race condition between launch and newPage?

**Comment by OrKoN** [comment]
Is it possible that the site blocks automation (e.g., by injecting infinite js loops) if it detects that the visit is coming from a data center?
