### ISSUE TITLE
[Bug]: Generated PDF from NextJs Doesn't Load Images Properly 

### ISSUE THREAD

**Issue by ALFAMAS** [puppeteer/puppeteer#13104]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
      userDataDir: './tmp',
      headless: true,
      args: [
        '--disable-web-security',
        '--disable-setuid-sandbox',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-background-networking',
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-breakpad',
        '--disable-client-side-phishing-detection',
        '--disable-component-update',
        '--disable-default-apps',
        '--disable-dev-shm-usage',
        '--disable-domain-reliability',
        '--disable-extensions',
        '--disable-features=AudioServiceOutOfProcess',
        '--disable-hang-monitor',
        '--disable-ipc-flooding-protection',
        '--disable-notifications',
        '--disable-offer-store-unmasked-wallet-cards',
        '--disable-popup-blocking',
        '--disable-print-preview',
        '--disable-prompt-on-repost',
        '--disable-renderer-backgrounding',
        '--disable-setuid-sandbox',
        '--disable-speech-api',
        '--disable-sync',
        '--hide-scrollbars',
        '--ignore-gpu-blacklist',
        '--metrics-recording-only',
        '--mute-audio',
        '--autoplay-policy=user-gesture-required',
        '--no-default-browser-check',
        '--no-first-run',
        '--no-pings',
        '--no-sandbox',
        '--no-zygote',
        '--password-store=basic',
        '--use-gl=swiftshader',
        '--use-mock-keychain'
      ],
    });
    const page = await browser.newPage();
    await page.setContent(`${html}`, { waitUntil: 'networkidle0' });
    await page.emulateMediaType("screen");

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();
```

### Background

On the previous versions the code ran smoothly but after I Upgraded to "puppeteer": "^23.1.0", the generated PDF got corrupted and un-useable 

### Expectation

I expected it to work as the previous version "puppeteer": "22.13.0",

### Reality

It doesn't work and PDF gets Curropted 

### Puppeteer version

23.1.0

### Node version

v20.17.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Linux

**Comment by OrKoN** [comment]
Please provide a test page and a complete minimal executable example and clarify what do you mean by a corrupted PDF?

**Comment by ALFAMAS** [comment]
### Express Server 

`import express from "express";
import puppeteer from "puppeteer";
import bodyParser from "body-parser"; // Import body-parser

const router = express.Router();
const textBodyParser = bodyParser.text({ type: 'text/html' });

router.post("/create/:name", textBodyParser, async (req, res) => {
  const name = req.params.name;
  const html = req.body;

  console.log(import.meta.url + " : ", "HTML", html)

  if (!name || !html) {
    return res.status(400).json({ error: true, message: "Missing name or html" });
  }

  try {
    const browser = await puppeteer.launch({
      userDataDir: './tmp',
      headless: true,
      args: [
        '--disable-web-security',
        '--disable-setuid-sandbox',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-background-networking',
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-breakpad',
        '--disable-client-side-phishing-detection',
        '--disable-component-update',
        '--disable-default-apps',
        '--disable-dev-shm-usage',
        '--disable-domain-reliability',
        '--disable-extensions',
        '--disable-features=AudioServiceOutOfProcess',
        '--disable-hang-monitor',
        '--disable-ipc-flooding-protection',
        '--disable-notifications',
        '--disable-offer-store-unmasked-wallet-cards',
        '--disable-popup-blocking',
        '--disable-print-preview',
        '--disable-prompt-on-repost',
        '--disable-renderer-backgrounding',
        '--disable-setuid-sandbox',
        '--disable-speech-api',
        '--disable-sync',
        '--hide-scrollbars',
        '--ignore-gpu-blacklist',
        '--metrics-recording-only',
        '--mute-audio',
        '--autoplay-policy=user-gesture-required',
        '--no-default-browser-check',
        '--no-first-run',
        '--no-pings',
        '--no-sandbox',
        '--no-zygote',
        '--password-store=basic',
        '--use-gl=swiftshader',
        '--use-mock-keychain'
      ],
    });
    const page = await browser.newPage();
    await page.setContent(`${html}`, { waitUntil: 'networkidle0' });
    await page.emulateMediaType("screen");

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${name}.pdf"`);
    res.send(pdfBuffer);
  } catch (e) {
    console.log(import.meta.url + ' : ', "Error creating PDF", e);
    return res.status(500).json({ error: true, message: e.message });
  }
});

export default router;`

frontend import express from "express";
import puppeteer from "puppeteer";
import bodyParser from "body-parser"; // Import body-parser

const router = express.Router();
const textBodyParser = bodyParser.text({ type: 'text/html' });

router.post("/create/:name", textBodyParser, async (req, res) => {
  const name = req.params.name;
  const html = req.body;

  console.log(import.meta.url + " : ", "HTML", html)

  if (!name || !html) {
    return res.status(400).json({ error: true, message: "Missing name or html" });
  }

  try {
    const browser = await puppeteer.launch({
      userDataDir: './tmp',
      headless: true,
      args: [
        '--disable-web-security',
        '--disable-setuid-sandbox',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-background-networking',
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-breakpad',
        '--disable-client-side-phishing-detection',
        '--disable-component-update',
        '--disable-default-apps',
        '--disable-dev-shm-usage',
        '--disable-domain-reliability',
        '--disable-extensions',
        '--disable-features=AudioServiceOutOfProcess',
        '--disable-hang-monitor',
        '--disable-ipc-flooding-protection',
        '--disable-notifications',
        '--disable-offer-store-unmasked-wallet-cards',
        '--disable-popup-blocking',
        '--disable-print-preview',
        '--disable-prompt-on-repost',
        '--disable-renderer-backgrounding',
        '--disable-setuid-sandbox',
        '--disable-speech-api',
        '--disable-sync',
        '--hide-scrollbars',
        '--ignore-gpu-blacklist',
        '--metrics-recording-only',
        '--mute-audio',
        '--autoplay-policy=user-gesture-required',
        '--no-default-browser-check',
        '--no-first-run',
        '--no-pings',
        '--no-sandbox',
        '--no-zygote',
        '--password-store=basic',
        '--use-gl=swiftshader',
        '--use-mock-keychain'
      ],
    });
    const page = await browser.newPage();
    await page.setContent(`${html}`, { waitUntil: 'networkidle0' });
    await page.emulateMediaType("screen");

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${name}.pdf"`);
    res.send(pdfBuffer);
  } catch (e) {
    console.log(import.meta.url + ' : ', "Error creating PDF", e);
    return res.status(500).json({ error: true, message: e.message });
  }
});

export default router;`

Post Data 
Name = Anything 
HTML  = Any Fully Formed HTML Design 
template HTML =

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TB240918241</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <link
      rel="preload"
      as="image"
      href="https://cdn.ticketmet.com/b2b/TM-T1-1715438632643.png"
    /><link
      rel="preload"
      as="image"
      href="https://cdn.ticketmet.com/aircontrols/BG.png"
    /><link
      rel="preload"
      as="image"
      href="https://cdn.ticketmet.com/onetoanother.webp"
    />
    <div class="mx-auto w-[800px] rounded-xl bg-white p-5">
      <div>
        <div class="mb-5 flex items-center justify-between">
          <div class="flex items-center text-sm">
            <img
              src="https://cdn.ticketmet.com/b2b/TM-T1-1715438632643.png"
              alt="TicketMet Logo"
              width="50"
              height="50"
              class="h-14 w-14 gap-1 rounded-md"
            />
            <div class="gap-1 p-1 text-[11px] font-medium leading-[12px]">
              <h1 class="text-lg font-bold leading-5 text-[#3a2ff7]">
                TICKETMET
              </h1>
              <div class="flex items-center gap-1">
                <p>arafat0951@gmail.com</p>
                <p>|</p>
                <p>01727706200</p>
              </div>
              <p>Mirpur, Dhaka 1216</p>
              <a href="https://www.ticketmet.com">www.ticketmet.com</a>
            </div>
          </div>
          <div
            class="flex flex-col gap-1 border bg-zinc-100 px-2 py-[6px] text-xs font-bold text-gray-700"
          >
            <p>
              Status :
              <span
                class="text-[10px] font-bold capitalize bg-blue-600 text-white ml-2 rounded p-1"
                >booked</span
              >
            </p>
            <p class="text-[11px]">
              Ref:<span class="ml-2 text-gray-600">TB240918241</span>
            </p>
            <p class="text-[11px]">
              APNR:<span class="ml-2 text-gray-600">OTVPNN</span>
            </p>
          </div>
        </div>
        <div class="my-4 border">
          <div class="relative w-full overflow-auto">
            <table class="w-full caption-bottom text-sm">
              <thead
                class="[&amp;_tr]:border-b h-7 bg-zinc-100 px-5 text-black"
              >
                <tr
                  class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                >
                  <th
                    class="h-10 px-2 text-left align-middle text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] font-bold"
                  >
                    PNR
                  </th>
                  <th
                    class="h-10 px-2 text-left align-middle text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] font-bold"
                  >
                    Flight Type
                  </th>
                  <th
                    class="h-10 px-2 text-left align-middle text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] font-bold"
                  >
                    Segment Type
                  </th>
                  <th
                    class="h-10 px-2 text-left align-middle text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] font-bold"
                  >
                    Fare Rule
                  </th>
                  <th
                    class="h-10 px-2 text-left align-middle text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] font-bold"
                  >
                    Issue Date
                  </th>
                </tr>
              </thead>
              <tbody class="[&amp;_tr:last-child]:border-0">
                <tr
                  class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                >
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px]"
                  >
                    OSVAAR
                  </td>
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] capitalize"
                  >
                    domestic
                  </td>
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px]"
                  >
                    Oneway
                  </td>
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px]"
                  >
                    <span class="font-semibold text-green-600"
                      >PARTIAL-REFUNDABLE</span
                    >
                  </td>
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px]"
                  >
                    19 September, 2024
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="my-4 border">
          <div class="relative w-full overflow-auto">
            <table class="w-full caption-bottom text-sm">
              <thead
                class="[&amp;_tr]:border-b h-7 bg-zinc-100 px-5 text-black"
              >
                <tr
                  class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                >
                  <th
                    class="h-10 px-2 text-left align-middle font-medium text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px]"
                  >
                    <span class="font-bold">Pax Name &amp;</span>
                    <span class="text-[10px]">SSR</span>
                  </th>
                  <th
                    class="h-10 px-2 text-left align-middle text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] font-bold"
                  >
                    E-Ticket
                  </th>
                </tr>
              </thead>
              <tbody class="[&amp;_tr:last-child]:border-0">
                <tr
                  class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                >
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px]"
                  >
                    MN
                    HB
                  </td>
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px]"
                  ></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="my-4 border">
          <div class="relative w-full overflow-auto">
            <table class="w-full caption-bottom text-sm">
              <thead
                class="[&amp;_tr]:border-b h-7 bg-zinc-100 px-5 text-black"
              >
                <tr
                  class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                >
                  <th
                    class="h-10 px-2 text-left align-middle text-muted-foreground [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] font-bold"
                  >
                    <div
                      class="flex flex-nowrap items-center gap-2 whitespace-nowrap"
                    >
                      <p>Dhaka - DAC</p>
                      <svg
                        stroke="currentColor"
                        fill="currentColor"
                        stroke-width="0"
                        viewBox="0 0 512 512"
                        class="text-base"
                        height="1em"
                        width="1em"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M407.7 224c-3.4 0-14.8.1-18 .3l-64.9 1.7c-.7 0-1.4-.3-1.7-.9L225.8 79.4c-2.9-4.6-8.1-7.4-13.5-7.4h-23.7c-5.6 0-7.5 5.6-5.5 10.8l50.1 142.8c.5 1.3-.4 2.7-1.8 2.7L109 230.1c-2.6.1-5-1.1-6.6-3.1l-37-45c-3-3.9-7.7-6.1-12.6-6.1H36c-2.8 0-4.7 2.7-3.8 5.3l19.9 68.7c1.5 3.8 1.5 8.1 0 11.9l-19.9 68.7c-.9 2.6 1 5.3 3.8 5.3h16.7c4.9 0 9.6-2.3 12.6-6.1L103 284c1.6-2 4.1-3.2 6.6-3.1l121.7 2.7c1.4.1 2.3 1.4 1.8 2.7L183 429.2c-2 5.2-.1 10.8 5.5 10.8h23.7c5.5 0 10.6-2.8 13.5-7.4L323.1 287c.4-.6 1-.9 1.7-.9l64.9 1.7c3.3.2 14.6.3 18 .3 44.3 0 72.3-14.3 72.3-32S452.1 224 407.7 224z"
                        ></path>
                      </svg>
                      <p>Cox&#x27;s Bazar - CXB</p>
                      |
                      <p>Thu, 19 September, 2024</p>
                      |
                      <p>Non-Stop</p>
                      |
                      <span class="flex"
                        ><svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 576 512"
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M432 96a48 48 0 1 0 0-96 48 48 0 1 0 0 96zM347.7 200.5c1-.4 1.9-.8 2.9-1.2l-16.9 63.5c-5.6 21.1-.1 43.6 14.7 59.7l70.7 77.1 22 88.1c4.3 17.1 21.7 27.6 38.8 23.3s27.6-21.7 23.3-38.8l-23-92.1c-1.9-7.8-5.8-14.9-11.2-20.8l-49.5-54 19.3-65.5 9.6 23c4.4 10.6 12.5 19.3 22.8 24.5l26.7 13.3c15.8 7.9 35 1.5 42.9-14.3s1.5-35-14.3-42.9L505 232.7l-15.3-36.8C472.5 154.8 432.3 128 387.7 128c-22.8 0-45.3 4.8-66.1 14l-8 3.5c-32.9 14.6-58.1 42.4-69.4 76.5l-2.6 7.8c-5.6 16.8 3.5 34.9 20.2 40.5s34.9-3.5 40.5-20.2l2.6-7.8c5.7-17.1 18.3-30.9 34.7-38.2l8-3.5zm-30 135.1l-25 62.4-59.4 59.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L340.3 441c4.6-4.6 8.2-10.1 10.6-16.1l14.5-36.2-40.7-44.4c-2.5-2.7-4.8-5.6-7-8.6zM256 274.1c-7.7-4.4-17.4-1.8-21.9 5.9l-32 55.4L147.7 304c-15.3-8.8-34.9-3.6-43.7 11.7L40 426.6c-8.8 15.3-3.6 34.9 11.7 43.7l55.4 32c15.3 8.8 34.9 3.6 43.7-11.7l64-110.9c1.5-2.6 2.6-5.2 3.3-8L261.9 296c4.4-7.7 1.8-17.4-5.9-21.9z"
                          ></path>
                        </svg>
                        :
                        <span
                          ><span>Adt-20kg</span></span
                        ></span
                      >
                      <p class="text-[#ef0711]"></p>
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody class="[&amp;_tr:last-child]:border-0 pb-4">
                <tr
                  class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted"
                >
                  <td
                    class="p-2 align-middle [&amp;:has([role=checkbox])]:pr-0 [&amp;&gt;[role=checkbox]]:translate-y-[2px] pb-4"
                  >
                    <div>
                      <div class="text-sm">
                        <div class="flex gap-2">
                          <img
                            src="https://cdn.ticketmet.com/aircontrols/BG.png"
                            alt="Biman Bangladesh"
                            width="250"
                            height="250"
                            class="h-7 w-7 items-center rounded-lg object-contain"
                          />
                          <div class="flex items-center gap-1">
                            <h4>
                              <span>Biman Bangladesh </span
                              ><span
                                >(BG
                                -
                                437) </span
                              ><span class="font-bold capitalize"
                                >economy
                                -
                                G</span
                              >
                            </h4>
                            <h4>
                              <svg
                                stroke="currentColor"
                                fill="currentColor"
                                stroke-width="0"
                                viewBox="0 0 1024 1024"
                                height="1em"
                                width="1em"
                                xmlns="http://www.w3.org/2000/svg"
                              >
                                <path
                                  d="M908.1 353.1l-253.9-36.9L540.7 86.1c-3.1-6.3-8.2-11.4-14.5-14.5-15.8-7.8-35-1.3-42.9 14.5L369.8 316.2l-253.9 36.9c-7 1-13.4 4.3-18.3 9.3a32.05 32.05 0 0 0 .6 45.3l183.7 179.1-43.4 252.9a31.95 31.95 0 0 0 46.4 33.7L512 754l227.1 119.4c6.2 3.3 13.4 4.4 20.3 3.2 17.4-3 29.1-19.5 26.1-36.9l-43.4-252.9 183.7-179.1c5-4.9 8.3-11.3 9.3-18.3 2.7-17.5-9.5-33.7-27-36.3z"
                                ></path>
                              </svg>
                            </h4>
                            <h4>DH8</h4>
                          </div>
                        </div>
                      </div>
                      <div
                        class="mt-2 flex items-center justify-between text-xs"
                      >
                        <div class="w-[70%]">
                          <p class="font-bold">
                            Dhaka - Hazrat Shahjalal Intl Airport (DAC)
                            T:
                            D
                          </p>
                          <div class="mt-1 flex items-center gap-2">
                            <h1 class="text-green-600">15:30</h1>
                            <p>(03:30 PM)</p>
                            <span>|</span>
                            <p>Thu, 19 Sep 2024</p>
                          </div>
                        </div>
                        <div class="w-1/3">
                          <h4 class="text-center">1h:15m</h4>
                          <img
                            src="https://cdn.ticketmet.com/onetoanother.webp"
                            alt="1toanimg"
                            height="20"
                            width="80"
                            class="mx-auto items-center justify-center object-contain"
                          />
                        </div>
                        <div class="w-[70%] text-end">
                          <p class="font-bold">
                            Cox&#x27;s Bazar - Coxs Bazar Airport (CXB)
                            T:
                          </p>
                          <div class="mt-1 flex items-center justify-end gap-2">
                            <p>(04:45 PM)</p>
                            <h1 class="text-green-600">16:45</h1>
                            <span>|</span>
                            <p>Thu, 19 Sep 2024</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="my-4 border">
          <p
            class="border-b bg-zinc-100 px-4 py-[6px] text-center text-sm font-bold text-black"
          >
            Conditions And Important Notice
          </p>
          <div class="space-y-2 p-4 text-xs">
            <h4 class="flex items-center justify-between font-bold">
              <span>** Cancellation Charges shall be as per airline rules.</span
              ><span>** Date Change Charges as applicable.</span>
            </h4>
            <p class="text-justify">
              <span class="font-bold">E-Ticket Notice: </span>Carriage and other
              services provided by the carrier are subject to conditions of
              carriage which are hereby incorporated by reference. These
              conditions may be obtained from the issuing carrier.
            </p>
            <p class="text-justify">
              <span class="font-bold">Passport/ Visa/ Health: </span>Please
              ensure that you have all the required travel documents for your
              entire journey - i.e. Valid passport &amp; necessary visas - and
              that you have had the recommended inoculations for your
              destination(s).
            </p>
            <p class="text-justify">
              <span class="font-bold">Reconfirmation of flights: </span>Please
              reconfirm all flights at least 72 hours in advance direct with the
              airline concerned. Failure to do so could result in the
              cancellation of your reservation and possible `no-show` charges.
            </p>
            <p class="text-justify">
              <span class="font-bold">Insurance: </span>We strongly recommend
              that you take out travel insurance for the whole of your journey.
            </p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
`

**Comment by OrKoN** [comment]
Please format as code using Markdown or use https://gist.github.com or, perhaps, create a test repository on github

**Comment by ALFAMAS** [comment]
> Please format as code using Markdown or use https://gist.github.com or, perhaps, create a test repository on github

https://gist.github.com/ALFAMAS/948f9e30290dc7c2293cd8e4dce7db14

**Comment by ge-ku** [comment]
Had the same issue, it's because ```Page.pdf()``` returned Buffer and now (since v23) it returns Uint8Array.

So in your code you can change
```res.send(pdfBuffer);```
to
```res.send(Buffer.from(pdfBuffer));```
and it'll work as before.

**Comment by ALFAMAS** [comment]
> Had the same issue, it's because `Page.pdf()` returned Buffer and now (since v23) it returns Uint8Array.
> 
> So in your code you can change `res.send(pdfBuffer);` to `res.send(Buffer.from(pdfBuffer));` and it'll work as before.

Thanks for the Fix but it doesn't load the images

**Comment by ge-ku** [comment]
> Thanks for the Fix but it doesn't load the images

Images are working fine for me, I suggest you try to launch it with ```headless: false``` and without ```browser.close();``` to see how it looks in a browser window.

**Comment by ALFAMAS** [comment]
![image](https://github.com/user-attachments/assets/b22f5e47-2d16-4a86-bcde-394910b30594)

how can fix the images
