### ISSUE TITLE
[Bug]: Error: Could not find Chrome (ver. 127.0.6533.88). 

### ISSUE THREAD

**Issue by Abhiappstec123** [puppeteer/puppeteer#13116]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';      
const browser = await puppeteer.launch({ headless: "true"});
const page = await browser.newPage();
page.setDefaultNavigationTimeout(0);
await page.setContent(htmlContent, { waitUntil: 'domcontentloaded' , timeout: 0 });
 const pdfBuffer = await page.pdf({
                format: 'A4',
                printBackground: true,
                margin: {
                  top: '.6in',
                  bottom: '.6in',
                  left: '.6in',
                  right: '.6in',
                },
                border: {
                  right: ".6in",
                  left: ".6in",
                  top: ".6in",
                  bottom: ".6in",
                },
                landscape: false,
              });
await page.setViewport({ width: 800, height: 600 });
await browser.close();
```

### Background

Above code is working fine in  locally but getting issue in aws hosted server.

### Expectation

In local i can generate pdf but in hosted server  i am getting below error

### Reality

Error: Could not find Chrome (ver. 127.0.6533.88). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: C:\Windows\system32\config\systemprofile\.cache\puppeteer).

### Puppeteer version

"puppeteer": "^22.15.0",

### Node version

v20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
I am unable to reproduce.
Installing version `22.15.0` installs `chrome 127.0.6533.88` correctly and run my script.
Are you skipping `post-install` as that is where we download the browser. 
Alternatively you did you run `npx puppeteer browsers install chrome` as suggested in the output?

**Comment by Abhiappstec123** [comment]
Yes i did run npx puppeteer browsers install chrome.

**Comment by Lightning00Blade** [comment]
Did any error occur while that command was running? Did you get output that the browser was downloaded successfully?

**Comment by Abhiappstec123** [comment]
i did not get any error. it is downloaded successfully

**Comment by Abhiappstec123** [comment]
yup its launching the chrome

**Comment by Lightning00Blade** [comment]
Hmm so it's issue with the set-up on AWS, you can check [Running Puppeteer in the cloud](https://pptr.dev/troubleshooting#running-puppeteer-in-the-cloud), but in general it's possible that Chrome dependencies are not installed and/or other error are happening. 
You can check by adding `dumpio:true` to the launch params, that will show any errors or info that may cause issues.

**Comment by Abhiappstec123** [comment]
thank you for info, i could able to figure out the issue.
