### ISSUE TITLE
[Bug]: Unable to launch firefox. Get an error about @puppeteer/browsers/lib/esm/launch.js:303 reject( new Error

### ISSUE THREAD

**Issue by arunk** [puppeteer/puppeteer#13113]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer-core";

(async () => {
    const browser = await puppeteer.launch({
        executablePath: "c:\\Program Files\\Mozilla Firefox\\firefox.exe",
        headless: false
    });
    const page = await browser.newPage();

    await page.goto("https://www.google.com/");
})();
```

### Background

I am simply trying to launch the firefox browser in a headed mode (headless: false). And I get this error.

### Expectation

That a new instance of the firefox browser should open to the page without any errors.

### Reality

The page opens with this text in the address bar: "http://translate,acceptchframe,mediarouter,optimizationhints,processpersiteuptomainframethreshold,isolatesandboxediframes/" and the node process exits with this error in the console:
```console
/node_modules/@puppeteer/browsers/lib/esm/launch.js:303
                reject(new Error([
                       ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (file:///C:/Users/arunk/Projects/puppet/node_modules/@puppeteer/browsers/lib/esm/launch.js:303:24)
    at Interface.emit (node:events:531:35)
    at Interface.close (node:internal/readline/interface:528:10)
    at Socket.onend (node:internal/readline/interface:254:10)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.17.0
```

### Puppeteer version

23.4.0

### Node version

20.17.0

### Package manager

npm

### Package manager version

10.8.3

### Operating system

Windows

**Comment by arunk** [comment]
And just as a follow up I tested this with chrome.exe. Changed executablePath to my local chrome.exe and it worked.

**Comment by Lightning00Blade** [comment]
Can you try using `dumpio: true` and see if any errors are show in the output. This will show the output coming from the browser.

**Comment by arunk** [comment]
I set dumpio: true, in the puppeteer.launch call, along with executablePath, headless, but I don't see anything in the console. Does the dump appear somewhere else in a log file or something?

**Comment by Lightning00Blade** [comment]
If the browser started correctly you can expect at least something like:
```
WebDriver BiDi listening on ws://127.0.0.1:42241
```
Did you verify that you are seeing something when running Chrome?

CC @whimboo Is there any other preference that needs to set to see browser logs similar to:
```
"remote.log.level": "Trace"
```

**Comment by arunk** [comment]
Ok when I launch chrome, I see this `DevTools listening on ws://127.0.0.1:56625/devtools/browser/f42def18-fe99-440e-ba79-0d9bb4c1b7ba`. But when I change executablePath to firefox, I don't see any message like that. I only see the error message in the console which I posted in my first post.

**Comment by whimboo** [comment]
Yes, please provide a log with the Firefox preference `remote.log.level` set to `Trace`.

**Comment by arunk** [comment]
I passed these preferences to the launch call, and also set `remote.log.level` to Trace in about:config in Firefox. Also when the window popped up I checked about:config and found that `remote.log.level` was indeed Trace. But I'm still seeing nothing in the console of the script. My script looks like this now:
```js
(async () => {
    const browser = await puppeteer.launch({
        executablePath: "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
        //executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
        headless: false,
        dumpio: true,
        extraPrefsFirefox: {
            "remote.log.level": "Trace"
        }
    });
    const page = await browser.newPage();

```

**Comment by whimboo** [comment]
This should definitely print log output to the console. I would have to defer to Puppeteer folks here why this is not happening. @Lightning00Blade or @OrKoN do you have an idea?

**Comment by arunk** [comment]
I tried this on my WSL 2 Ubuntu instance as well, setting the path to the Windows Firefox instance, but it failed with the same error. The same text shown in the browser address bar, and nothing else in the console.

**Comment by Lightning00Blade** [comment]
Could you also run the command with env `DEBUG=puppeteer:*`, that will show internal logging from Puppeteer and `@puppeteer/browsers`.

**Comment by arunk** [comment]
I didn't get much but I got this output:
```
 $env:DEBUG="puppeteer:*"; node .\src\index.js
  puppeteer:browsers:launcher Launching C:\Program Files\Mozilla Firefox\firefox.exe --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-hang-monitor --disable-infobars --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --export-tagged-pdf --generate-pdf-document-outline --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold,IsolateSandboxedIframes --enable-features=PdfOopif about:blank --remote-debugging-port=0 --user-data-dir=C:\Users\arunk\AppData\Local\Temp\puppeteer_dev_chrome_profile-pVDEce { detached: false, env: {}, stdio: [ 'pipe', 'pipe', 'pipe' ] } +0ms
  puppeteer:browsers:launcher Launched 33764 +16ms
  puppeteer:browsers:launcher Trying to kill 33764 +151ms
file:///C:/Users/arunk/Projects/puppet/node_modules/@puppeteer/browsers/lib/esm/launch.js:303
                reject(new Error([
                       ^

Error: Failed to launch the browser process!


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (file:///C:/Users/arunk/Projects/puppet/node_modules/@puppeteer/browsers/lib/esm/launch.js:303:24)
    at Interface.emit (node:events:531:35)
    at Interface.close (node:internal/readline/interface:528:10)
    at Socket.onend (node:internal/readline/interface:254:10)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.17.0
```

**Comment by Lightning00Blade** [comment]
Ooo, I missed the part where you are not providing `browser: "firefox"`.
By default it tries to launch with arguments for Chrome as we can't infer the browser.

**Comment by arunk** [comment]
Yes that fixed the issue. I'm so sorry, but I didn't see anything about passing this parameter in the documentation. Maybe I overlooked it. I'm able to see the firefox browser and interact with it now. Thanks!

**Comment by Lightning00Blade** [comment]
Closing this for now I added a PR to update the documentation with the suggestion.
