### ISSUE TITLE
Puppeteer with firefox in AWS Lambda

### ISSUE THREAD

**Issue by ajanthaselvam** [puppeteer/puppeteer#13114]
Hi
I tried to deploy Puppeteer with firefox in AWS Lambda. It worked fine in my local docker.
But throws the following error in Lambda. 

(firefox:20): dconf-CRITICAL **: 13:41:21.966: unable to create directory '/home/sbx_user1051/.cache/dconf

**Comment by Lightning00Blade** [comment]
Could you try running with the following set-up, add `DEBUG=puppeteer:*`  env variable and. 
```js
const browser = await puppeteer.launch({
        dumpio: true,
        extraPrefsFirefox: {
            "remote.log.level": "Trace"
        }
    });
```
If you can post a Gist of the logs, that would be helpful.

CC @whimboo Are you aware of anything special need to AWS Lambda for it to run Firefox?
