### ISSUE TITLE
Variable name is displayed in an error message instead of resovling to the string it contains

### ISSUE THREAD

**Issue by ericlittley** [puppeteer/puppeteer#13124]
I got the following error message while running puppeteer:

``1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install ${browserType}`) or``

but I believe it should be:

`1. you did not perform an installation before running the script (e.g. 'npx puppeteer browsers install chrome') or`

The offending line is here:
https://github.com/puppeteer/puppeteer/blob/82034fad620751dc6df57251c479466f14139c36/packages/puppeteer-core/src/node/BrowserLauncher.ts#L460

I think the single quotes were supposed to be backticks and the backticks were supposed to be single quotes.  However the firefox error case has firefox hardcoded so it might be better to just hardcode chrome for consistency. 

Tthe firefox error message is here:
https://github.com/puppeteer/puppeteer/blob/82034fad620751dc6df57251c479466f14139c36/packages/puppeteer-core/src/node/BrowserLauncher.ts#L467

**Comment by Lightning00Blade** [comment]
There is already a PR in flight to fix it - https://github.com/puppeteer/puppeteer/pull/13119
