### ISSUE TITLE
[Bug]: Docker version 23.4.1 Cant load Chrome 

### ISSUE THREAD

**Issue by gawsoftpl** [puppeteer/puppeteer#13130]
### Minimal, reproducible example

```TypeScript
FROM ghcr.io/puppeteer/puppeteer:23.4.1 AS base

USER root

WORKDIR /build

RUN npm -g i --force pnpm

USER pptruser

ARG PACKAGE

WORKDIR /home/pptruser/

# Mount deploy directory against Copy
RUN --mount=type=bind,source=.pnpm-store,target=/.pnpm-store \
    --mount=type=bind,source=.,target=/build \
    pnpm --store-dir=/.pnpm-store --filter=$PACKAGE deploy --no-optional --prod /home/pptruser/app/

WORKDIR /home/pptruser/app/packages/libs/puppeteer
```

### Expectation

Load chrome without error

### Reality

In version 23.4.0 everything works fine. In version 23.4.1 when I run puppeteer in Docker image I received error:

I received error:
 Error: Could not find Chrome (ver. 129.0.6668.58). This can occur if either
test-1  |  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install ${browserType}`) or
test-1  |  2. your cache path is incorrectly configured (which is: /home/pptruser/.cache/puppeteer).
test-1  | For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

### Puppeteer version

23.4.1

### Node version

20.17

### Package manager

npm

### Package manager version

pnpm

### Operating system

Linux

**Comment by OrKoN** [comment]
23.4.1 ships with Chrome 129.0.6668.70 and not Chrome 129.0.6668.58 (therefore, 129.0.6668.58  is not expected to be installed in that image). So it looks the Docker image still uses Puppeteer 23.4.0 (the details required to confirm this are missing).  Try to make sure that the image version matches the used Puppeteer version or make sure you install the browser for Puppeteer version you actually use (not sure if pnpm deploy invokes postinstall scripts).

**Comment by gawsoftpl** [comment]
> 23.4.1 ships with Chrome 129.0.6668.70 and not Chrome 129.0.6668.58 (therefore, 129.0.6668.58 is not expected to be installed in that image). So it looks the Docker image still uses Puppeteer 23.4.0 (the details required to confirm this are missing). Try to make sure that the image version matches the used Puppeteer version or make sure you install the browser for Puppeteer version you actually use (not sure if pnpm deploy invokes postinstall scripts).

I have right. I have mismatch puppeteer version in package.json. Now i upgraded puppeteer to 23.4.1 in pnpm and everything works fine.
