### ISSUE TITLE
[Bug]: page.waitForNetworkIdle() TimeoutError: Timed out after waiting 30000ms

### ISSUE THREAD

**Issue by 868618** [puppeteer/puppeteer#13131]
### Minimal, reproducible example

```TypeScript
const page = await browser.newPage();

await page.goto("https://member.bilibili.com/", { waitUntil: "load" });

await page.waitForNetworkIdle();
```

### Background

"puppeteer-core": "^23.4.0"

nodejs v18.20.3

when i use userDataDir for puppeteer.launch then i use waitForNetworkIdle

first time its run ok

then an error occurred `TimeoutError: Timed out after waiting 30000ms`

### Expectation

run ok

### Reality

TimeoutError: Timed out after waiting 30000ms

### Puppeteer configuration file (if used)

```TypeScript
const browser = await puppeteer.launch({
      channel: "chrome",
      defaultViewport: null,
      headless: false,
      userDataDir,
      args: [
        "--disable-cache",
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--no-first-run",
        "--no-sandbox",
        "--no-zygote",
        "--disable-setuid-sandbox",
        "--disable-notifications",
        "--disable-extensions",
        "--disable-geolocation",
        proxyUrl ? `--proxy-server=${proxyUrl}` : "",
      ],
    });
```

### Puppeteer version

23.4.0

### Node version

v18.20.3

### Package manager

pnpm

### Package manager version

9.6.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Sometimes the response for `https://api.bilibili.com/x/internal/gaia-gateway/ExClimbWuzhi` is never received, that's why Puppeteer never considers it finished. Could you please verify that there is no server issue with https://api.bilibili.com/x/internal/gaia-gateway and that it does not delay response indefinitely?

**Comment by 868618** [comment]
> api.bilibili.com/x/internal/gaia-gateway

thanks very much
