### ISSUE TITLE
[Bug]: Blank window appears when using headless chrome (on WINDOWS)

### ISSUE THREAD

**Issue by ArnaudBuchholz** [puppeteer/puppeteer#13145]
### Minimal, reproducible example

```TypeScript
async function main () {
  const puppeteer = require('puppeteer')
  const browser = await puppeteer.launch({
    headless: 'new',
    defaultViewport: null,
    args: [
      '--start-maximized',
      '--no-sandbox',
      '--disable-gpu',
      '--disable-extensions',
      '--log-level=3',
      '--window-size=1024,768',
      '--lang=en-us'
    ]
  })
  const page = (await browser.pages())[0]
  await page.goto('https://www.google.com')
  await new Promise(resolve => setTimeout(resolve, 5000))
  await page.close()
  await browser.close()
}

main()
```

### Background

I use `puppeteer` in [`ui5-test-runner`](https://www.npmjs.com/package/ui5-test-runner) to automate browsers. By default, headless is expected and the running should not interfere with the user desktop.

### Expectation

No window should appear when running headless.

### Reality

Since version `23.2.0`, a blank window appears.

NOTE: this window seems to be sized like the browser window.

My test environment is WINDOWS, I can't tell for other systems.

### Puppeteer configuration file (if used)

```TypeScript
N/A, above script reproduces the problem.
```

### Puppeteer version

23.4.1

### Node version

lts

### Package manager

npm

### Package manager version

lts

### Operating system

Windows

**Comment by PBHansen** [comment]
This is also happening in puppeteer-core v. 13.5.2 
On several windows machine
Also installed using NPM
