### ISSUE TITLE
elementHandle.screenshot clip object uses wrong y value

### ISSUE THREAD

**Issue by cdaringe** [puppeteer/puppeteer#1315]
### problem

calls to `elementHandle.screenshot` use the incorrect y value, resulting in invalid images

### Steps to reproduce

- scroll an element into view
- get an element handle
- call elementHandle.screenshot
- observe chrome scroll to the top of the doc, at y: 0, and capture content from there
  - we use the boundingBox object as a input to `clip`, but when scrolled into view, `boundingBox.y` is ~0 (or a small value), and `Page.screenShot` seems to expect an absolute `y` value, from top of doc

example!  https://www.youtube.com/edit?video_id=TcGYq5d3n4c

puppeteer calls:
```
// Page.js
const result = await this._client.send('Page.captureScreenshot', { format, quality: options.quality, clip })
```

**What is the expected result?**

- a screenshot of the requested element

**What happens instead?**

- a screenshot of the correct dimensions, but at the top of my document, not over my actual element.
- or, in other words, a screenshot of the correct dimensions in the viewport, BUT, the viewport has moved

**Comment by cdaringe** [comment]
ah ha!  see: https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-VisualViewport

confirmed, pup's clip values need to be patched

**Comment by cdaringe** [comment]
... https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot 

^^ would be handy too :)

**Comment by cdaringe** [comment]
rather than being a productive citizen and landing a patch here (which i should :(), i'll at least share the hack fix:

```js
    // get the full height of the document
    var height = await page.evaluate(function () {
      var body = document.body
      var html = document.documentElement
      var height = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight)
      return height
    })
    // set the viewport to be the full height of the document
    await page.setViewport({
      width, // whatever it may be
      height
    })
```

^^ this _only works_ if you're always starting from the top of the document to begin with.

**Comment by cdaringe** [comment]
working on a PR now

**Comment by cdaringe** [comment]
see #1323

**Comment by cdaringe** [comment]
see #1323

**Comment by waqarorakzai** [comment]
My problem was i was setting the Viewport after goTo(), when change it it worked for me perfectly

```
`const puppeteer = require('puppeteer');

async function run(url) {
    let browser = await puppeteer.launch({ headless: true });
    let page = await browser.newPage();
    const VIEWPORT = { width: 1360, height: 780}
    boxes2 = [];
    await page.setViewport(VIEWPORT);
    await page.goto(url, { waitUntil: 'domcontentloaded'});
    await page.waitFor('table');
    await page.waitForSelector('table');
    const el = await page.$$('table');
    for(let i = 0; i < el.length; i++){
        // await console.log(el[i].getBoundingClientRect());
        await el[i].screenshot({
            path: 'link_' +i+ '.png',
        })
    }
    // await processScreens(el, page);
    await page.close();
    await browser.close();
}


const url = "https://github.com/puppeteer/puppeteer/issues/1315";
run(url);
`
```
