### ISSUE TITLE
Trouble using session/cookies through userDataDir?

### ISSUE THREAD

**Issue by natew** [puppeteer/puppeteer#1316]
### Steps to reproduce

Hey all! Not sure at all if this is possible but wanted to be sure. Just wanted to clarify. I'm using userDataDir to point to my Default and active profile. But with `headless: false` I've attempted loading a variety of sites and none show me as logged in.

The docs don't necessarily clarify either way, nor did a quick search.

**What steps will reproduce the problem?**

```
import pup from 'puppeteer'

async function run() {
  const browser = await pup.launch({
    userDataDir: '~/Library/Application Support/Google/Chrome/Default',
    headless: false,
  })
  const page = await browser.newPage()
  await page.goto('https://facebook.com')
  await browser.close()
}

try {
  run()
} catch (err) {
  console.error(err)
}
```

**What is the expected result?**

Uses the session from my regular Chrome.

**What happens instead?**

No session.

**Comment by natew** [comment]
Ah, I see it actually made all my paths relative. If I made the path relative, I now just get a cannot read or write to data directory, which is a step forward.

**Comment by aslushnikov** [comment]
@natew this looks like a dupe of #921 

There are also #1268 and #1270. Please, upvote all of them if you need this functionality in puppeteer!

**Comment by natew** [comment]
Interesting, thanks for the quick reply. I did see those tickets. My own one doesn't seem to work even with `headless: true` for some reason, so not truly a dupe.

So it should load an existing Chrome profile and be able to use those cookies with one of `headless: false` or `headless: true`?

**Comment by natew** [comment]
Just tested and neither seem to use my session on two websites I tested, verified the userDataDir is pointing to the right place.

**Comment by aslushnikov** [comment]
@natew oh wait, I believe the issue is in the '~' that you have as part of the `userDataDir`. Can you please check if it works with absolute path? (Relative path should work too, but bash expansions are not supported).

**Comment by natew** [comment]
I actually tried a ton of combinations including absolute (just put that there to not put my actual user path here).

When I did `/Users/me/Library...` it actually created a relative folder from where I ran the script like: `/tmp/script/Users/me/Library...` which I hadn't noticed. Perhaps from previous attempts. I just tried again with absolute path and it seems to run at least, I don't know how to verify it's using the profile though.

Currently am doing one of:

```js
// either this path
const userProfileDir = Path.join(
  process.env.HOME,
  'Library',
  'Application Support',
  'Google',
  'Chrome',
  'Default'
)
// or this relativized just in case
const userDataDir = Path.relative(__dirname, userProfileDir)
```

but neither seems to get my profile.

Edit: And I can log out that path and verify it's pointing to the right place. And if I change it to be, say, Default2, it creates a dir next to my real profile, so it seems like it's pretty good.

**Comment by aslushnikov** [comment]
@natew Do I get it right that you are trying to re-use the Google Chrome profile directory in Chromium?

**Comment by natew** [comment]
Yes, or alternatively, to use the Chrome executable itself with it's own profile. Basically, want to script my own browser, without having to do some pretty complex copying of cookies/session over. Wasn't sure if it was supposed to work or not.

**Comment by natew** [comment]
Can I ask if this is a security feature thats intended or just incompat?

Would this be rejected as insecure? Just curious because we'd like to implement this for our company, but if it won't be implemented for security it would change plans.

**Comment by aslushnikov** [comment]
@natew to my understanding, this might work fine if both chromium and chrome are the same version. And it easily might not work if chrome/chromium versions are different (which is most of the time).

This, however, should work just fine if you use Chrome Canary with and without puppeteer.
You can ask puppeteer to launch Chrome Canary via the `executablePath` option in `puppeteer.launch`:

```js
const browser = await puppeteer.launch({
  // Path to Chrome Canary
  executablePath: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary'
});
```

Would this solution work for you?

**Comment by natew** [comment]
@aslushnikov that does go a long way. Final question... I'm guessing it's required to use Chromium vs regular Chrome to run? I guess because it's not mentioned anywhere. If it was possible to just run the actual Chrome I have in /Applications that would be ideal as it would require no version matching scripting + no extra download.

Edit: this seems to work for me, at least when not running headless and with some flags, checking a few things...

**Comment by natew** [comment]
Ok so it seems to run vanilla Chrome using the path you gave but it doesn't seem to load the page I give it. If I `DEBUG=puppeteer:*` I see a few things logged out but no page load. Tried with these options:

```
args: ['--no-sandbox', '--disable-setuid-sandbox'],
ignoreHTTPSErrors: true,
```

**Comment by natew** [comment]
Guessing this definitely isn't supported, did a quick test this morning. `await browser.newPage()` returns null. And then doing `await browser.pages()` gives:

```
Protocol error (Page.getFrameTree): 'Page.getFrameTree' wasn't found undefined
Error: Protocol error (Page.getFrameTree): 'Page.getFrameTree' wasn't found undefined
    at Session._onMessage (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/puppeteer/lib/Connection.js:205:25)
    at Connection._onMessage (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/puppeteer/lib/Connection.js:105:19)
    at WebSocket.emit (events.js:159:13)
    at Receiver._receiver.onmessage (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/Users/nw/projects/motion/orbit/apps/crawler/node_modules/ws/lib/WebSocket.js:139:22)
    at Socket.emit (events.js:159:13)
```

On Mac High Sierra, Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by aslushnikov** [comment]
@natew Chrome 62 is too old to work with pptr v0.13.0; I'd try using some older pptr or newer chrome. (Ideally, I'd go with Chrome Canary).

**Comment by rommguy** [comment]
@aslushnikov I have the same problem, using Chrome 64
I've set the executablePath to my Chrome app, and the userDataDir to my Profile dir under Chrome

Still - doesn't matter if I use headless or not, I don't get the right cookies. 

Using mac OS X, puppeteer 0.13

**Comment by entrptaher** [comment]
@aslushnikov if I run google manually with --user-data-dir param, it seems a fault in google chrome rather than puppeteer, any idea how to resolve it?

`/opt/google/chrome/google-chrome --user-data-dir=/home/someone/.config/google-chrome/Default`

**Comment by aslushnikov** [comment]
@entrptaher the `Default` folder is a profile folder rather then a `userDataDir`. Pass the `google-chrome` folder instead:

```
/opt/google/chrome/google-chrome --user-data-dir=/home/someone/.config/google-chrome/
```

**Comment by entrptaher** [comment]
@aslushnikov here, it still feels like a chrome bug to me.

Running normally,
![Imgur](https://i.imgur.com/1v08Uux.png)

Running using `userDataDir` command. I tested with several different combinations.
![Imgur](https://i.imgur.com/oZIytMh.png)

**Comment by aslushnikov** [comment]
@entrptaher are you sure that's the folder chrome uses by default?

The following works for me: 
1. Launch with a fresh userDataDir
2. Login to stackoverflow
3. Close chrome. Re-launch with the same userDataDir
4. Make sure stackoverflow login is still there.

**Comment by entrptaher** [comment]
@aslushnikov,

Code:

```js
const puppeteer = require("puppeteer");

puppeteer
  .launch({
    headless: false,
    executablePath:"/opt/google/chrome/google-chrome",
    userDataDir: "/home/someone/.config/google-chrome/"
  })
  .then(async browser => {
    const page = await browser.newPage();
    await page.goto("chrome://version/");
  });
```

Normal browsing,
![](https://i.imgur.com/vkJrhcd.png)

With the script,
![](https://i.imgur.com/jIpGxVA.png)

Am I missing something really simple perhaps?
Is it the `--disable-sync` param which is causing problem? If yes, how to toggle it? :dizzy_face: 

Found the problem, I toggled [this line](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L52) off and it started working nicely.

```js
const AUTOMATION_ARGS = [
  '--enable-automation',
//  '--password-store=basic', // <-- Toggled this off when used custom data directory and it worked nicely
  '--use-mock-keychain',
];
```

![Imgur](https://i.imgur.com/5VJTqIb.png)

How to ignore it :/ ?

**Comment by EdwardsBean** [comment]
I'm facing the same problem, any help? @entrptaher  not works for me.

**Comment by MrXyfir** [comment]
Any (reasonable) solution to this yet? I think I've tried every possible suggestion and nothing has worked. Is the only option manually saving and injecting cookies?

```ts
// Saving the cookies

const client = await page.target().createCDPSession();
// This gets all cookies from all URLs, not just the current URL
const cookies: puppeteer.Cookie[] = (await client.send(
  'Network.getAllCookies'
))['cookies'];

console.log('Saving', cookies.length, 'cookies');
await fs.writeJSON(cookiesPath, cookies);
```
```ts
// Loading the cookies

try {
  const cookies: puppeteer.Cookie[] = await fs.readJSON(cookiesPath);
  console.log('Loading', cookies.length, 'cookies into browser');
  await page.setCookie(...cookies);
} catch (err) {}
```

Note that `fs` is actually `fs-extra`.

**Comment by davyzhang** [comment]
@MrXyfir, Thank you so much, currently this is the only reliable way that works for me. None of those methods mentioned above work when I try to share my user data dir with headless chromium for doing some automation work on behalf of myself. I found that both sessions reset the authorization cookies so that the headful browser loses its authorization information and need to log in again.

I've wrapped these 2 functions for easier use
```javascript
const fs = require("fs");

async function writeCookies(page, cookiesPath) {
  const client = await page.target().createCDPSession();
  // This gets all cookies from all URLs, not just the current URL
  const cookies = (await client.send("Network.getAllCookies"))["cookies"];

  console.log("Saving", cookies.length, "cookies");
  fs.writeFileSync(cookiesPath, JSON.stringify(cookies));
  // await fs.writeJSON(cookiesPath, cookies);
}
async function restoreCookies(page, cookiesPath) {
  try {
    // const cookies = await fs.readJSON(cookiesPath);
    let buf = fs.readFileSync(cookiesPath);
    let cookies = JSON.parse(buf);
    console.log("Loading", cookies.length, "cookies into browser");
    await page.setCookie(...cookies);
  } catch (err) {
    console.log("restore cookie error", err);
  }
}
```

**Comment by entrptaher** [comment]
@davyzhang and @MrXyfir can you check these issues?
- https://github.com/GoogleChrome/puppeteer/issues/1268
- https://github.com/GoogleChrome/puppeteer/issues/1270
- https://github.com/GoogleChrome/puppeteer/issues/921

**Comment by MrXyfir** [comment]
@entrptaher Yep, I encountered those issues. There is no good solution as far as I'm aware. Any solution would be a fragile hack. Pretty much you'd have to do the same thing as with cookies: save them elsewhere and restore the data when needed. _However_ this is not a simple task by any means because you cannot easily load and set all of the local storage data for all domains at once like you can with cookies. You would need a frame open to a URL of the same origin you wish to manage the local storage of. Ultimately it wasn't worth the effort (for me at least) to write a similar system as I had with cookies.

I think the best solution is to keep complaining until the Chrome and/or Chrome DevTools Protocol developers fix this. If I remember correctly, the issue isn't really with puppeteer, since it mostly is just a wrapper for the DevTools protocol.

**Comment by eightHundreds** [comment]
i found close browser by manual will cause cookie lose

```
async function run() {
  const browser = await puppeteer.launch({
    executablePath: findChrome(),
    headless: false,
    args: [`--user-data-dir=${userData}`],
  });
  setTimeout(async () => {
      await browser.close() // close by api
  }, 20000);
}
```

**Comment by bozdoz** [comment]
Can confirm @eightHundreds.
Cookies are successfully set if I close the browser using the close buttton, but not if I call browser.close() in the script.  

Why is this issue closed?

**Comment by anthonyfrisby** [comment]
> @entrptaher are you sure that's the folder chrome uses by default?
> 
> The following works for me:
> 
> 1. Launch with a fresh userDataDir
> 2. Login to stackoverflow
> 3. Close chrome. Re-launch with the same userDataDir
> 4. Make sure stackoverflow login is still there.

This works really well, just specify a new path in your project file and make your own user data dir rather than using chromes default one.

**Comment by lilcheti** [comment]
> > @entrptaher are you sure that's the folder chrome uses by default?
> > The following works for me:
> > 
> > 1. Launch with a fresh userDataDir
> > 2. Login to stackoverflow
> > 3. Close chrome. Re-launch with the same userDataDir
> > 4. Make sure stackoverflow login is still there.
> 
> This works really well, just specify a new path in your project file and make your own user data dir rather than using chromes default one.

Don't forget to allow all cookies too

**Comment by maliknajjar** [comment]
> @aslushnikov,
> 
> How to ignore it :/ ?

Your solution worked for me
you can add an `ignoreDefaultArgs` property to ignore those two arguments
```js
const browser = await puppeteer.launch({
    headless: false,
    executablePath: '/usr/bin/google-chrome-stable',
    userDataDir: '/home/<USERNAME>/.config/google-chrome',
    ignoreDefaultArgs: [
      '--password-store=basic',
      '--use-mock-keychain',
    ]
  });
```
