### ISSUE TITLE
breakpoint in workspace not firing

### ISSUE THREAD

**Issue by pragmaproducts** [puppeteer/puppeteer#1317]
I am trying out puppeteer but running into debugging issue that I was hoping someone may be able to shed some light on please.

"puppeteer": "^0.12.0"

running test file using node --inspect-brk
added application files to chrome as a workspace.

I can debug the actual puppeteer code but the breakpoints in the web app that puppeteer is running does not fire.

What are the steps to follow to set a breakpoint on the site that you are loading in puppeteer and debug the site not puppeteer?

**Comment by alexkozy** [comment]
AFAIU you would like to debug function that you calls in page context using page.evaluate and other puppeteer methods. We do not have good solution for you right now but you can add "debugger;" statement in your code and run puppeteer in head full mode:
`puppeteer.launch({headless: false, devtools: true})`
As soon as you step over puppeteer function that running code with debugger statement, you should be able to debug this code in DevTools inside controlled browser.

**Comment by pragmaproducts** [comment]
ok will give the devtools option a try, ty

**Comment by aslushnikov** [comment]
Speculatively closing this. Feel free to write back if there are still issues.
