### ISSUE TITLE
[Feature]: Add `-y` flag to install browsers without prompting user for confirmation 

### ISSUE THREAD

**Issue by pirate** [puppeteer/puppeteer#13178]
### Steps to reproduce

```bash
root@b5a583fbfdd7:/app# /npx @puppeteer/browsers install --path /app/browsers chrome@stable
Need to install the following packages:
  @puppeteer/browsers@2.4.0
Ok to proceed? (y)
```

### Expected results

There should be a `-y` flag you can pass so that it automatically installs without prompting the user for confirmation interactively.

### Actual results

It hangs indefinitely when called from `Dockerfile` or via non-interactive script, waiting forever for the user to press (y).

**Comment by OrKoN** [comment]
The question comes from npx and not from Puppeteer. If you want to avoid it, preinstall the package using `npm i @puppeteer/browsers`

**Comment by pirate** [comment]
Ah ok thanks, that was the tip I needed. I didn't realize the prompt was from `npx` and not `puppeteer`.

It turns out you can add `npx --yes ...` or `env npm_config_yes=true npx ...`
https://stackoverflow.com/a/69006263/2156113
