### ISSUE TITLE
[Bug]: deviceScaleFactor is not working

### ISSUE THREAD

**Issue by sxsnwangrenfei** [puppeteer/puppeteer#13188]
### Minimal, reproducible example

```TypeScript
//puppeteer@23.5.3
import puppeteer from 'puppeteer';
var browser = await puppeteer.launch({
    headless: false
});

var page = await browser.newPage();
await page.setViewport({ width: 475, height: 820, deviceScaleFactor:2});
await page.goto('https://github.com/');
```

### Expectation

I want to adjust the scaling ratio of each page based on width and height.

### Reality

The deviceScaleFactor setting on setViewport does not work.

### Puppeteer version

23.5.3

### Node version

18.20.4

### Package manager

npm

### Package manager version

no package

### Operating system

Windows

**Comment by OrKoN** [comment]
the emulation might not affect the page visually but the corresponding Web APIs are emulated:

```
import puppeteer from 'puppeteer';
var browser = await puppeteer.launch({
    headless: false
});

var page = await browser.newPage();
await page.setViewport({ width: 475, height: 820, deviceScaleFactor: 4});
await page.goto('https://github.com/');

console.log(await page.evaluate(() => {
  return window.devicePixelRatio;
})); // outputs 4
```

Could you clarify what do you mean "does not work"?
