### ISSUE TITLE
npm install FAILED because of uncertain proxy config

### ISSUE THREAD

**Issue by zxsoft** [puppeteer/puppeteer#1318]
I'm from china where need a proxy to download google chrome.

so, I set "npm config set proxy [xxx.xxx.xxx.xxx:xxxx]" and  use command "npm install puppeteer --save", but the install failed.

I checked the installer.js file which located "node_modules/puppeteer/installer.js" and noticed the installer used env proxy,that is, HTTP_PROXY and HTTPS_PROXY on the linux environment.

So when I want to download google chrome correctly, I have to use HTTP_PROXY while I'm using a ALREADY-PROXY-CONFIGURED npm instance, that makes this feel weird.

Please consider using `npm config get proxy` when download google chrome, thanks!

**Comment by riponbanik** [comment]
I also find the following error - when downloading is via proxy (env variable is http_proxy/or https_proxy)

puppeteer@0.13.0 install /var/lib/jenkins/workspace/test/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r515411! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/515411/chrome-linux.zip

**Comment by aslushnikov** [comment]
Thanks @zxsoft for filing this! Looks like this was addressed some time ago:

https://github.com/GoogleChrome/puppeteer/blob/12b57e31f386b1bd8845aba0246894fde8fe9ed8/install.js#L40-L50
