### ISSUE TITLE
[Bug]: Throws 'Failed to launch the browser process! undefined' when running puppeteer inside node docker container

### ISSUE THREAD

**Issue by Saranpjs727** [puppeteer/puppeteer#13192]
### Minimal, reproducible example

```TypeScript
# Stage 1: Build the Chrome base image
FROM node:18-slim as chrome-base

RUN apt-get update && apt-get install -y gnupg wget && \
    wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
    apt-get update && \
    apt-get install -y google-chrome-stable --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Stage 2: Build the final image
FROM node:18-slim

ENV PUPPETEER_CACHE_DIR='/usr/bin/google-chrome'

## Copy only essential Chrome files and dependencies
COPY --from=chrome-base /usr/bin/google-chrome /usr/bin/google-chrome
COPY --from=chrome-base /opt/google/chrome /opt/google/chrome
COPY --from=chrome-base /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu

COPY dist/build /app/build

WORKDIR /app/build

EXPOSE 8080

USER 1000


CMD ["node","index.js"]

------

const browser = await puppeteer.launch(
  {
    headless: true,
        executablePath: '/usr/bin/google-chrome,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

Error: Failed to launch the browser process! undefined
```

### Background

I used a multi-stage build to run Puppeteer in a Node Docker container by copying the necessary Chrome dependencies from stage 1 to stage 2. 
However, it throws the error 'Failed to launch the browser process! undefined.' 
I am using this approach to reduce the image size by copying only the essential Chrome dependencies.

### Expectation

Successfully launch puppeteer browser

### Reality

throws the error 'Failed to launch the browser process! undefined.' 

### Puppeteer version

23.5.1

### Node version

v21.1.0

### Package manager

yarn

### Package manager version

4.3.1

### Operating system

Linux

**Comment by OrKoN** [comment]
How do you find which Chrome dependencies are essential? It is very likely that some things are missing. We provide a working and tested Docker image here: https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer / https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile and we recommend using it. For questions about building a custom Docker image, I suggest to publish a question to StackOverflow.

**Comment by Saranpjs727** [comment]
ghcr.io/puppeteer/puppeteer image size is almost 2.3GB. 
 
To reduce the Docker image size, I tried using a multi-stage build process. It works fine with a single-stage build, and the resulting image size is 800MB.
 
 Is there any way I can further optimize the Docker image size while including all the required dependencies for Puppeteer?

**Comment by OrKoN** [comment]
Puppeteer by itself only requires Node. The system dependencies are required by the browser. In case of Chrome, the list of dependencies is provided here https://pptr.dev/guides/system-requirements Our docker image provides Chrome as well chrome-headless-shell (when launching with headless:'shell') so perhaps by using only the headless shell you can make the image smaller. In general, though running the browser would require not only the binary but all related resource files.

**Comment by Saranpjs727** [comment]
Does chrome-headless-shell also requires System dependencies?

**Comment by OrKoN** [comment]
generally, yes, but probably fewer of them, I do not have an exact list.

**Comment by Saranpjs727** [comment]
thanks for the information

**Comment by Saranpjs727** [comment]
I found essential dependency using -  ldd /opt/google/chrome/chrome

**Comment by OrKoN** [comment]
ldd might not find dependencies that are used via dlopen
