### ISSUE TITLE
[Bug]:  Failed to launch the browser process!

### ISSUE THREAD

**Issue by Saranpjs727** [puppeteer/puppeteer#13194]
### Minimal, reproducible example

```TypeScript
My docker file:

FROM node:18-slim
RUN npx puppeteer browsers install chrome
ENV PUPPETEER_CACHE_DIR='/root/.cache/puppeteer/chrome/linux-129.0.6668.100/chrome-linux64/chrome'
COPY dist/build /app/build -- copying build artifact
WORKDIR /app/build
EXPOSE 8080
USER 1000
CMD ["node","index.js"]

const browser = await puppeteer.launch(
{
headless: true,
executablePath: /root/.cache/puppeteer/chrome/linux-129.0.6668.100/chrome-linux64/chrome,
args: ['--no-sandbox', '--disable-setuid-sandbox'],
});
```

### Expectation

Successfully launch puppeteer browser

### Reality

Error:
/root/.cache/puppeteer/chrome/linux-129.0.6668.100/chrome-linux64/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

### Puppeteer version

23.5.1

### Node version

v21.1.0

### Package manager

yarn

### Package manager version

4.3.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Does your image include required dependencies (for this particular error libgobject is missing)? https://pptr.dev/guides/system-requirements Also, consider using the image we provide at https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer / https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile

**Comment by Saranpjs727** [comment]
After adding system-requirement. Its working

RUN apt-get update && apt-get install -y --no-install-recommends \
    # Install glibc and required libraries
    libc6 \
    # Install GTK+ 3.14 or higher
    libgtk-3-0 \
    # Install libglib 2.42 or higher
    libglib2.0-0 \
    # Install libstdc++ 4.8.1 or higher
    libstdc++6 \
    # Install X.Org 1.7 or higher and related libraries
    xserver-xorg-core \
    x11-xkb-utils \
    xfonts-base \
    xfonts-100dpi \
    xfonts-75dpi \
    x11-utils \
    x11-xserver-utils \
    libxext6 \
    libxrender1 \
    libx11-xcb1 \
    libxcomposite1 \
    libxrandr2 \
    libxcursor1 \
    libxdamage1 \
    libxtst6 \
    libasound2 \
    libnss3 \
    ca-certificates \
    fonts-liberation \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libdbus-glib-1-2 \
    && rm -rf /var/lib/apt/lists/*

**Comment by ViniciusFXavier** [comment]
With these commands, you can set up and run the environment on any Linux distribution, including Ubuntu, CentOS, WSL (1, 2), and even [CodeSandbox](https://codesandbox.io/). Follow these steps:

1. **Update Package List and Apply Updates**  
   First, update the list of packages and apply the updates:  
   ```bash
   sudo apt update  
   sudo apt upgrade -y  
   ```  
   This ensures your system is up to date.  

2. **Install Dependencies for Chromium**  
   Install all necessary libraries and dependencies required to run Chromium:  
   ```bash
   sudo apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils  
   ```  
    Yes, there are several dependencies. :sweat:

3. **Handle DISPLAY Issues (if applicable)**  
   If you encounter issues related to the `DISPLAY` environment variable, run the following command to allow Linux GUI apps to connect:  
   ```bash  
   export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0  
   ```  

4. **Install Chromium if Not Found**  
   If Chromium is not installed or cannot be found, add the Chromium repository and install it:  
   ```bash  
   sudo add-apt-repository ppa:chromium-team/stable  
   sudo apt-get update  
   sudo apt install chromium-browser  
   ```
