### ISSUE TITLE
[Bug]: string-set with content does not work

### ISSUE THREAD

**Issue by moberkirchner** [puppeteer/puppeteer#13197]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({ headless: false });
const page = await browser.newPage();

await page.setContent(`
	<script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
	<style>
		.string-set-text {
			display: none;
			string-set: stringsettext content(text);
		}
			
		.site-info::after {
			content: string(stringsettext) ' ' counter(page) ' of ' counter(pages);
		}
	</style>

	<div>
		<div class="string-set-text">Site</div>
		<div class="site-info"></div>
	</div>
`);
```

### Background

I've trying to show pagination info for prints. It works with as expeced with "puppeteer": "22.13.1" but it breaks with 22.14.0 and upward.

### Expectation

I expected that following is shown:
Site 1 of 1

### Reality

In reality, following is shown:
Site '' counter(page)' of' counter(pages)

### Puppeteer version

22.14.0

### Node version

20.17.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Windows

**Comment by Lightning00Blade** [comment]
Please test with latest Puppeteer version, and see if the issue is not resolved.

**Comment by OrKoN** [comment]
It looks like [string-set](https://www.w3.org/TR/css-gcpm-3/) is not implemented natively in Chrome. I can confirm it is not working but it looks like an issue with the paged.polyfill implementation: I get the same results in headful browser without Puppeteer.

**Comment by moberkirchner** [comment]
Also testet with current version 23.5.3 but the problem remains (22.13.1 is the last working version).

**Comment by jonathanpelletier** [comment]
I also face the same issue, even with the latest version of puppeteer (23.6.0). When I revert back to 22.13.1, the page counter starts working again.
