### ISSUE TITLE
Docs recommend using unprivileged user namespaces for sandbox scenario in Ubuntu even though it can introduce vulnerabilities

### ISSUE THREAD

**Issue by artdedeco** [puppeteer/puppeteer#13205]
The docs currently say:

> # [recommended] Enable [user namespace cloning](http://man7.org/linux/man-pages/man7/user_namespaces.7.html)
> User namespace cloning is only supported by modern kernels. Unprivileged user namespaces are generally fine to enable, but in some cases they open up more kernel attack surface for (unsandboxed) non-root processes to elevate to kernel privileges.

> 
> `sudo sysctl -w kernel.unprivileged_userns_clone=1`

At the same time it says this is the recommended approach, it also warns that the approach can introduce [other vulnerabilities](https://security.stackexchange.com/questions/209529/what-does-enabling-kernel-unprivileged-userns-clone-do).

The [Chrome docs on AppArmor restrictions](https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md), which the docs here also links to, do not recommend that approach.

Could the docs expand on why this is the recommended approach over others, such as creating a new AppArmor profile?

**Comment by OrKoN** [comment]
Yeah, I do not think we should recommend that. I think the users need to evaluate different approaches based on their use case.
