### ISSUE TITLE
[Bug]: PDF rendering is broken in version 23.0.0 onwards.

### ISSUE THREAD

**Issue by gpercem** [puppeteer/puppeteer#13209]
### Minimal, reproducible example

```TypeScript
const express = require('express');
const puppeteer = require('puppeteer');

const app = express();
const port = 3000;

app.get('/', async (req, res) => {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.setContent(`
      <html>
        <body>
          <h1>PDF Generation Test</h1>
          <p>This is a test PDF generated by Puppeteer.</p>
          <p>Current time: ${new Date().toLocaleString()}</p>
        </body>
      </html>
    `, { waitUntil: 'networkidle0' });

    const pdf = await page.pdf({ format: 'A4' });

    await browser.close();

    res.contentType('application/pdf');
    res.set('Content-Disposition', 'attachment; filename=test.pdf');
    res.send(pdf);
  } catch (error) {
    console.error('Error generating PDF:', error);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

app.listen(port, () => console.log(`Server running on port ${port}`));
```

### Background

The code given in the example works in version 22.15.0 but not in 23.0.0 onwards.
The possible reason might be this merge: #12823.

### Expectation

It should download a test.pdf file (~44 KB in size). The contents of the file should be visible in any PDF viewer.

### Reality

The downloaded file is a corrupted test.pdf file that is ~488 KB in size. It does not open in any PDF viewer.

### Puppeteer version

23.0.0

### Node version

v20.15.0

### Package manager

npm

### Package manager version

10.7.0

### Operating system

Windows

**Comment by OrKoN** [comment]
I believe res.end serializes arrays as JSON and as pointed out in https://github.com/puppeteer/puppeteer/pull/12823 you would need to convert it to Buffer in Node, e.g., `res.send(Buffer.from(pdf));` starting from v23.

**Comment by jasonswearingen** [comment]
> I believe res.end serializes arrays as JSON and as pointed out in [#12823](https://github.com/puppeteer/puppeteer/pull/12823) you would need to convert it to Buffer in Node, e.g., `res.send(Buffer.from(pdf));` starting from v23.

@OrKoN the workaround should be documented here: https://pptr.dev/api/puppeteer.page.pdf  This change breaks prior pdf generation on nodejs, and the fix is non-obvious.

these methods worked pre v23 are:
- `Buffer.from(decoder.decode(pdf), "utf-8").toString('base64');`  //creates corrupted pdf that's nearly byte identical
- `btoa(decoder.decode(pdfBuffer));` //used to work but now throws some unicode parse errors
