### ISSUE TITLE
[Bug]: Can't install chrome-for-testing behind proxy

### ISSUE THREAD

**Issue by jerrycooper** [puppeteer/puppeteer#13208]
### Steps to reproduce

We have environment behind proxy without connection to internet. And we are using nexus for downloading packages. We use default version of chrome.

in package.json
puppeteer: 23.5.3

in .puppeteerrc
{
  chrome: {
    downloadBaseUrl: "https://our.nexus/components/repository/google-proxy/chrome-for-testing-public"
  }
}

### Expected results

Success installation as with 22.15.0 version.

### Actual results

npm ERR! HTTP 5003: SOCKET ERROR: read ETIMEDOUT Error: read ETIMEDOUT
npm ERR!     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
npm ERR! Error: ERROR: Failed to set up chrome-headless-shell v129.0.6668.100! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR!     at downloadBrowser (file:///home/jenkins/project/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:26:15)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Promise.all (index 1)
npm ERR!     at async downloadBrowsers (file:///home/jenkins/project/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:84:9) {
npm ERR!   [cause]: Error: read ETIMEDOUT
npm ERR!       at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
npm ERR!     errno: -110,
npm ERR!     code: 'ETIMEDOUT',
npm ERR!     syscall: 'read'
npm ERR!   }
npm ERR! }

When I enable NODE_DEBUG, there are connections outside:
pm ERR! HTTP 5003: createConnection storage.googleapis.com:443::::::::::::::::::::: [Object: null prototype] {
npm ERR!   protocol: 'https:',
npm ERR!   hostname: 'storage.googleapis.com',
and
npm ERR! HTTP 5003: createConnection googlechromelabs.github.io:443::::::::::::::::::::: [Object: null prototype] {
npm ERR!   protocol: 'https:',
npm ERR!   hostname: 'googlechromelabs.github.io',

Results for 23.6.0 are same.

**Comment by OrKoN** [comment]
Puppeteer downloads Chrome and chrome-headless-shell binaries by default. It looks like you only configure the download URL for Chrome and also you do not skip the shell download? Could you try to either specify the base download url for chrome-headless-shell or skip the download for it?

**Comment by jerrycooper** [comment]
Thank you very much. I added chrome-headless-shell to config and it works.
