### ISSUE TITLE
browser.pages() is not a function

### ISSUE THREAD

**Issue by wanghongjuan** [puppeteer/puppeteer#1320]
I want to get all content of new page that open it via url forward, instead of using `browser.newPage()`, but I am not clear how to do it. When I trying to use `browser.pages()`, the terminal show "TypeError: browser.pages is not a function".

### Steps to reproduce
Following is my test code:
```bash
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const pages = await browser.pages();
  console.log(pages.length());
})();
```

**Test Environment:**
* Puppeteer version:0.12.0
* Platform / OS version: Ubuntu 16.04

**What is the expected result?**
This method can work well.

**What happens instead?**
It is not a function

**Comment by vsemozhetbyt** [comment]
`browser.pages()` method is added in v0.13.0-alpha (compare [v0.13.0-alpha doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserpages) vs [v0.12.0 doc](https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md)). You can upgrade via `npm install https://github.com/GoogleChrome/puppeteer/`.
