### ISSUE TITLE
[Bug]: ChunkLoadError: Loading chunk 860 failed

### ISSUE THREAD

**Issue by papukumar** [puppeteer/puppeteer#13204]
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
      headless: true,
      args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-3d-apis',
          '--disable-software-rasterizer',
          '--disable-infobars',
          '--no-experiments',
          '--disable-sync',
          '--disable-extensions'
      ],
      userDataDir: `${__dirname}/tmp/chromeDataDir`,
      pipe: true
});
const page = await browser.newPage();
page.on('pageerror', error => {
   console.log("Error:", error); // logs chunkload error
});
await page.goto('https://app.birdeye.com/er-independent-pdf-page/pdf-generate?storageId=profile-impressions-mobile-Splash_Express_Car_Wash-Business-3-164677947656360', { waitUntil: 'domcontentloaded', timeout: 5 * 60 * 1000 });
await page.pdf({
 // pdf options
});
await page.close();
await browser.close();
```

### Background

I am trying to generate pdf of the page url opened. But out of blue I get chunk load error sometimes. My UI is a React app bundled using webpack.

### Expectation

I don't want chunk load error.

### Reality

Getting chunk load error sometimes out of blue

### Puppeteer version

14.0.0

### Node version

14.21.3

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
The error comes from the page and Puppeteer just reports the errors you have on the page. I do not think this can be solved in Puppeteer. You are also taking a PDF after the domcontentloaded is fired which might be too early since the page might still be loading.
