### ISSUE TITLE
[Feature]: Add tabs to tab groups

### ISSUE THREAD

**Issue by CliffRobinson** [puppeteer/puppeteer#13215]
### Add tabs to tab groups

When puppeteer is running in headed mode, be able to add a given tab to an existing tab group or create a new one. This can be used to organise large numbers of tabs (for my use case, this would be comparing components with different configuration at different screenwidths).

**Comment by Lightning00Blade** [comment]
I presume you are talking about `Add tab to new group` functionality in Chrome when you right click a tab.
Puppeteer focuses on automation of the page and at this point there aren't any plans to support "Browser UI" bits.
