### ISSUE TITLE
[Bug]: Option userDataDir returns wrong path to "Profile Path" of Chrome browser

### ISSUE THREAD

**Issue by kytosai** [puppeteer/puppeteer#13217]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const CHROME_EXECUTABLE_PATH2 = `/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary`;

const CHROME_USER_DATA_DIR_PATH2 = `/Users/trantien/Library/Application\ Support/Google/Chrome\ Canary/Default`;

async function main(params) {
  const browser = await puppeteer.launch({
    headless: false,
    devtools: false,
    executablePath: CHROME_EXECUTABLE_PATH2,
    userDataDir: CHROME_USER_DATA_DIR_PATH2,
  });

  const page = await browser.newPage();
}

main();
```

### Background

When I pass a path to my chrome user profile to the userDataDir option, then when I execute the code, I use the command `chrome://version` to check the content line `Profile Path:` I saw that it arbitrarily added an extra `/Default` at the end -> this makes my chrome unable to load the correct profile, I need to proceed with automation processing

![image](https://github.com/user-attachments/assets/d3c154f3-aad6-4bc0-82e7-049ac014f027)

![image](https://github.com/user-attachments/assets/aa31faf3-b4af-46a5-ba09-457ad9d2a453)

### Expectation

I want when I pass a path to the userDataDir option to keep the contents of the path I passed, don't add anything to them.

"Profile Path" of Chrome browser should show: **"/Users/trantien/Library/Application Support/Google/Chrome Canary/Default"**

### Reality

Currently when I pass a path to the userDataDir option it automatically adds `/Default` to the end of the path I passed causing an error that cannot load chrome profile

"Profile Path" of Chrome browser currently show: **"/Users/trantien/Library/Application Support/Google/Chrome Canary/Default/Default"** (double "/Default")

I tried them on browsers: Chrome, Chrome Canary, Microsoft Edge -> all get the same error

### Puppeteer version

23.6.0

### Node version

18.20.4

### Package manager

npm

### Package manager version

10.7.0

### Operating system

macOS

**Comment by OrKoN** [comment]
The profile path is not the user data dir path. The user data dir is the path that would contain all of the browser's profiles. So I believe it is working as [expected](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_switches.cc;l=652;drc=e6fc2038d73ef96ff47deda3146d94d25530e13b).

**Comment by kytosai** [comment]
When I open chrome browser in normal state then I login to slack and I will have the following interface

![image](https://github.com/user-attachments/assets/21ed6bb6-bf3b-4ca5-87cf-0328d6954df0)

But when I start pptr with the code I provided above, they give me the following error (on my avatar right corner) and they don't keep the previous login information

![image](https://github.com/user-attachments/assets/f530361f-3925-4f6e-8472-7a682a39a16e)

I don't know what I set wrong? Because as you can see, my chrome interface when opened with pptr still keeps the same purple color as when I access them in normal state.
