### ISSUE TITLE
[Bug]: page.#timeoutSettings is not accessible anymore (follow-up on #8901 but for `defaultNavigationTimeout` instead of `defaultTimeout`)

### ISSUE THREAD

**Issue by aguyinmontreal** [puppeteer/puppeteer#13238]
### Minimal, reproducible example

Same issue as in #8901 but for defaultNavigationTimeout instead of defaultTimeout

### Background

In #8901 the issue has been fixed for `defaultTimeout` but not for `defaultNavigationTimeout`.

### Expectation

The same way that there's a [Page.getDefaultTimeout](https://pptr.dev/api/puppeteer.page.getdefaulttimeout) to match  [Page.setDefaultTimeout](https://pptr.dev/api/puppeteer.page.setdefaulttimeout), there should be a `Page.getDefaultNavigationTimeout` to match [Page.setDefaultNavigationTimeout](https://pptr.dev/api/puppeteer.page.setdefaultnavigationtimeout)

### Reality

--

### Puppeteer version

23.6.0

### Node version

20.11.0

### Package manager

npm

### Package manager version

10.9.0

### Operating system

Windows

**Comment by satyamkale27** [comment]
I want to work on this issue please assign it to me.

**Comment by Lightning00Blade** [comment]
@satyamkale27 Happy to review a PR.
