### ISSUE TITLE
[Bug]: Impossible to remove top margin from header in page.pdf

### ISSUE THREAD

**Issue by nicolo-ribaudo** [puppeteer/puppeteer#13235]
### Minimal, reproducible example

```TypeScript
import { writeFileSync } from 'fs';
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({ headless: 'new' });
const page = await browser.newPage();
await page.setJavaScriptEnabled(false);
await page.emulateMediaType('print');

await page.goto(`data:text/html,
<!DOCTYPE html>
<html lang="en">
    <head>
        <style>
          html, body {
            margin: 0 !important;
            padding: 0 !important;
          }
        </style>
    </head>
    <body>
        <div style="background:red; width: 50px; height: 50px"></div>
    </body>
</html>

`);

const out = await page.pdf({
    format: 'A4',
    margin: { top: 0, left: 0 },
    displayHeaderFooter: true,
    headerTemplate: `
        <div style="margin: 0 !important; height: 100px; width: 100px; border: 1px solid black"></div>
    `,
    footerTemplate: ' ',
    printBackground: true
});

writeFileSync('out.pdf', out);

await page.close();
await browser.close();
```

### Background

I am trying to add a header when printing the page to PDF, and the header should have no top margin

### Expectation

The header has no top margin

### Reality

The main page (red square) has no top margin, but the "header" (square with the black border) does.

![image](https://github.com/user-attachments/assets/025b88b6-eea3-4fa3-9725-83608743e86a)

### Puppeteer version

23.5.2

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

**Comment by OrKoN** [comment]
You can try `<style>#header {padding: 0;}</style>` for Chrome (https://source.chromium.org/chromium/chromium/src/+/main:components/printing/resources/print_header_footer_template_page.html).

**Comment by OrKoN** [comment]
Or 

```
 <div style="margin-top: -15pt; height: 100px; width: 100px; border: 1px solid black"></div>
```

to account for the default header padding.

**Comment by nicolo-ribaudo** [comment]
This worked, thanks for your help :)
