### ISSUE TITLE
[Bug]: Error "Navigating frame was detached" persists across AWS Lambda invocations after browser crash

### ISSUE THREAD

**Issue by marceloaprado** [puppeteer/puppeteer#13236]
### Minimal, reproducible example

```TypeScript
// handler.ts

import { APIGatewayEvent, Context } from 'aws-lambda';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import { Browser } from 'puppeteer-core';

export const handler = async (event: APIGatewayEvent, context: Context) => {
  const htmlContent = event.body || '';

  let browser: Browser | null = null;

  try {
    // Always launch a new browser instance per request
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: true,
    });

    const page = await browser.newPage();

    await page.setContent(htmlContent, {
      waitUntil: 'networkidle0',
    });

    const pdfBuffer = await page.pdf({
      format: 'A4',
    });

    await page.close();

    // Close the browser after processing
    await browser.close();

    // Return the PDF buffer as response (base64 encoded for API Gateway)
    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/pdf' },
      body: pdfBuffer.toString('base64'),
      isBase64Encoded: true,
    };
  } catch (error) {
    // If an error occurs, close the browser if it's open
    if (browser) {
      await browser.close();
    }

    // Return error response
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message }),
    };
  }
};

Instructions to reproduce:

1. Deploy the Lambda Function
2. Invoke the Lambda function with a large HTML content that is known to cause the browser to crash due to resource constraints.
3. The first request fails as expected due to the browser crash.
4. Invoke the Lambda function again with a valid, small HTML content. Observe the Persistent error: "Error: Navigating frame was detached".
```

### Background

I'm running a TypeScript AWS Lambda function, with Node.js 18.x runtime version, that converts HTML content to PDF using puppeteer-core (v 23.6.0) and @sparticuz/chromium (v 130.0.0). The Lambda function is designed to handle incoming HTML content and return a generated PDF.

To ensure isolation and avoid issues with browser instances, I always launch a new browser instance for each request and close it after processing. No browser instances are reused across invocations.

However, when the Lambda function processes a large HTML file that causes the browser to crash, the subsequent requests in the same Lambda execution environment, even though they launch new browser instances, consistently fail with the error "Error: Navigating frame was detached" when calling browser.newPage() or page.setContent().

### Expectation

I expect that after a browser crash and closure, launching a new browser instance in a subsequent invocation should provide a fresh environment. The new browser instance should function correctly, allowing the Lambda function to process new HTML content and generate PDFs without errors.

### Reality

Despite always launching a new browser instance per request, after a browser crash in a previous invocation, any subsequent attempts to process HTML content result in the error:

`Error: Navigating frame was detached
    at FrameManager._onFrameDetached (.../node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:392:10)
    at CDPSession.emit (events.js:314:20)
    at CDPSession.EventEmitter.emit (domain.js:483:12)
    at CDPSession._onMessage (.../node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:200:12)
    at Connection._onMessage (.../node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:112:17)
    at WebSocket.<anonymous> (.../node_modules/puppeteer-core/lib/cjs/puppeteer/common/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (events.js:316:20)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (.../node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:310:20)
`

This error persists across subsequent invocations within the same Lambda execution environment, effectively causing the function to fail until the environment is recycled (i.e., a new Lambda container is created).

### Puppeteer version

23.6.0

### Node version

18.x

### Package manager

npm

### Package manager version

10.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
I don’t think we can help here. I’d suggest to open an issue with @sparticuz/chromium or reach out to the AWS Lambda community over StackOverflow. Persistent crashes is either a bug in that browser build or some specifics of the AWS lambda environment.

We could take a look if you provide a reproducible example that does not use AWS Lambda and reproduces with a Chrome binary.
