### ISSUE TITLE
[Bug]: Support for Connecting Puppeteer to an Already-Running Firefox Instance via WebSocket and goto() Issue

### ISSUE THREAD

**Issue by Zack-dot-IT** [puppeteer/puppeteer#13267]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
    try {
        const browserURL = "ws://127.0.0.1:9222/devtools/browser/6808d98e-175d-463c-8033-6a0851452d02";
        
        // Connect to the remote instance
        const browser = await puppeteer.connect({
            browserWSEndpoint: browserURL,
            browser: 'firefox'
        });

	const [page] = await browser.pages();

	await page.goto('https://google.com');

        console.log('Never reach here');
    } catch (error) {
        console.error('Error connecting to the remote browser:', error);
    }
})();
```

### Background

I’m working with Puppeteer to automate **Firefox 132.0.1** and appreciate the WebDriver BiDi protocol support for improved compatibility!

I’ve encountered a specific issue when trying to connect Puppeteer to an **already-running** Firefox instance:

- **Connecting via CDP:** I can launch Firefox manually with the **_--remote-debugging-port=9222_** flag and then connect to it using Puppeteer’s connect() function over CDP. This setup works for establishing the connection, but I run into issues with page navigation.

- **Problem with goto() Function:** When using **page.goto()**, the promise never resolves, even though the browser navigates to the specified URL successfully. This behavior only occurs when I connect to an externally launched Firefox instance over CDP. 

It seems that **goto()** hangs _indefinitely_ without throwing any errors. I’ve tried different **waitUntil** options and varied the timeout from very short to very long values, but the issue persists.

### Expectation

The code must reach the console log

### Reality

The goto never resolve, it return **TimeoutError** if I set it to different than 0

### Puppeteer version

23.4.1

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.9.0

### Operating system

Windows

**Comment by OrKoN** [comment]
CDP support in Firefox and Puppeteer is not actively maintained anymore. Generally automation in Firefox might require special settings (like the ones set by Puppeteer during launch) to make it work. Note that you would need to specify the protocol when connecting if you want to connect using CDP. Could you please confirm that you still experience the problem if you start with correct preferences for the protocol of your choice: https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/node/FirefoxLauncher.ts#L33 + https://github.com/puppeteer/puppeteer/blob/main/packages/browsers/src/browser-data/firefox.ts#L190

cc @whimboo

**Comment by gbmocean** [comment]
Thanks for the responses! Here’s what I’ve tried with both protocols:


I used **puppeteer/browsers** to download Firefox:

`npx @puppeteer/browsers@latest install firefox@stable`


_**1. CDP:**_

I'm still encountering the same **Timeout Error**. Here’s a summary of my setup:

**launch.js:**

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        protocol: 'cdp',
        browser: 'firefox',
        headless: false,
        executablePath: 'D:\\test\\firefox\\win64-stable_132.0.1\\core\\firefox.exe',
        extraPrefsFirefox: {
            'browser.tabs.closeWindowWithLastTab': false,
            'network.cookie.cookieBehavior': 0,
            'fission.bfcacheInParent': false,
            'remote.active-protocols': 2,
        },
        debuggingPort: 9223,
    });

    console.log('WebSocket URL: ', browser.wsEndpoint());
})();
```

**connect.js:**

```
const puppeteer = require('puppeteer');

(async () => {
    try {
        const ConnectOptions = {
            browserWSEndpoint: "ws://127.0.0.1:9223/devtools/browser/303e82db-b5bc-4335-b220-ce6ebe072244",
            protocol: "cdp",
        };

        const browser = await puppeteer.connect(ConnectOptions);
        console.log("Connected!");

        const [page] = await browser.pages();
        await page.goto('https://google.com/');
        
        console.log("Never reach here");
    } catch (e) {
        console.log("FAILURE!\n", e);
    }
})();
```

**Output:** I receive "Connected!" and see the page redirected to Google, but **goto()** doesn’t resolve, and it never reaches the next console log.

_**2. WebDriver BiDi:**_

I encountered the same issue as described in [issue #13057](https://github.com/puppeteer/puppeteer/issues/13057) – specifically, the "session not created Maximum number of active sessions .*" error.

**launch.js:**

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        protocol: 'webDriverBiDi',
        browser: 'firefox',
        headless: false,
        executablePath: 'D:\\test\\firefox\\win64-stable_132.0.1\\core\\firefox.exe',
        extraPrefsFirefox: {
            "remote.log.level": "Trace",
            'remote.active-protocols': 1
        },
        debuggingPort: 9223,
    });

    console.log('WebSocket URL: ', browser.wsEndpoint());
})();
```

**connect.js:**

```
const puppeteer = require('puppeteer');

(async () => {
    try {
        const cOps = {
            browserWSEndpoint: "ws://127.0.0.1:9223/session",
            protocol: "webDriverBiDi",
        };

        const browser = await puppeteer.connect(cOps);
        console.log("Connected!");
        await browser.disconnect();
        console.log("Disconnected!");
    } catch (e) {
        console.log("FAILURE!\n", e);
    }
})();
```

**Output:** I received this error : 

> **ProtocolError: Protocol error (session.new): session not created Maximum number of active sessions .***

**Comment by OrKoN** [comment]
Firefox support a single session with WebDriver BiDi so you cannot launch it using Puppeteer that automatically creates a session. You need to launch it manually (or with @puppeteer/browsers API providing those extra preferences). Note that Puppeteer launch in both cases set the preferences correctly so extra prefs are not needed.

**Comment by Zack-dot-IT** [comment]
Thank you! The WebDriver BiDi test works perfectly when launched separately; it connects and navigates smoothly.

**Comment by whimboo** [comment]
That's good to hear. In case you are interested in multiple session support we track that work via https://bugzilla.mozilla.org/show_bug.cgi?id=1862018.

**Comment by OrKoN** [comment]
I will mark the issue as not planned on our end but there is also an issue on the Firefox side to allow starting the browser for automation without needed to specify preferences ahead of time. I could not find a link but perhaps @whimboo has it.

**Comment by whimboo** [comment]
Yes, that would be https://bugzilla.mozilla.org/show_bug.cgi?id=1868965.

**Comment by SerhiiMaksymiv** [comment]
@Zack-dot-IT 
where or how do you get connection uuid?
```
ws://127.0.0.1:9222/devtools/browser/6808d98e-175d-463c-8033-6a0851452d02
```

im trying to establish connection to a running firefox instance, but i cant find session id(?) or what this `uuid` suppose to mean in this context.
In chrome i can get id by fetching `http://localhost:9222/json/version`, but for ff...
when i manually start firefox the output shows only:
```
WebDriver BiDi listening on ws://127.0.0.1:9222
```

**Comment by Zack-dot-IT** [comment]
Yes, you'll not find the `uuid` because it's not required, the connection URL does not include a UUID by default, use :

`ws://127.0.0.1:9222/session`
