### ISSUE TITLE
[Bug]: The program does not run on the server

### ISSUE THREAD

**Issue by sergej-js** [puppeteer/puppeteer#13260]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
    headless: true,
    waitUntil: 'domcontentloaded',
    defaultViewport: { width: 1920, height: 1080 },
});
```

### Background

I'm using ubuntu 22.04
Node.JS version: v20.11.0

Error: 
![{1300ACDD-677D-4543-9C4A-9DFFCB930D46}](https://github.com/user-attachments/assets/5dadbe6f-ad16-4a6e-881f-0370f356d402)

On a local machine with the same version of node js everything works fine

### Expectation

I'm waiting for the application to launch

### Reality

I don't know

### Puppeteer version

^23.6.1

### Node version

v20.11.0

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Linux

**Comment by OrKoN** [comment]
That looks like some misconfiguration of the Node installation (perhaps multiple node versions are installed) and the error indicates that the Node version does not support the syntax. Try running without sudo. If that does not help, I'd recommend asking on StackOverflow what might be wrong.

P.S. waitUntil is not a supported option in launch().
