### ISSUE TITLE
browser.newPage is not a function

### ISSUE THREAD

**Issue by EdmundMai** [puppeteer/puppeteer#1326]
I'm trying to scrape a website that has javascript rendered content. I will call this method using a route.

I can't 1) use async / await and 2) I can't call a self calling function. This is one function I call within a firebase function

```

const findEmail = () =>
  new Promise((resolve, reject) => {
    const browser = puppeteer.launch();
    const page = browser.newPage(); // <--------- fails here
    page.goto("https://celsius.network/");
    const textContent = page.evaluate(
      () => document.querySelector('a[href^="mailto:"]').textContent
    );
    browser.close();

    console.log("EMAIL", textContent); // should be presale@celsius.network
    resolve(textContent);
  }


```

It is giving me this error: `findEmail error:  TypeError: browser.newPage is not a function`

I'm using the latest version of puppeteer

**Comment by MehdiRaash** [comment]
Most methods in Puppeteer are async in nature, so your code basically is **wrong**.
Why you can't  async / await ?

_this is a promise fashion code, if you don't wanna use async/await_
```
 const findEmail = () =>
  new Promise((resolve, reject) => {
    puppeteer.launch().then(function (browser) {
      browser.newPage().then(function (page) {
        page.goto("https://celsius.network/");
        const textContent = page.evaluate(
          () => document.querySelector('a[href^="mailto:"]').textContent
        );
        console.log("EMAIL", textContent); // should be presale@celsius.network
        resolve(textContent);
        browser.close(); 
      });
    });
});
```

**Comment by EdmundMai** [comment]
@MehdiRaash Thanks for the prompt response. When I try this code, it gives me an error:

```
const findEmail = url =>
  new Promise((resolve, reject) => {
    puppeteer.launch().then(function(browser) {
      browser.newPage().then(function(page) {
        page.goto(url);
        const textContent = page.evaluate(
          () => document.querySelector('a[href^="mailto:"]').textContent
        );
        console.log("EMAIL", textContent); // should be presale@celsius.network
        resolve(textContent);
        browser.close();
      });
    });
  });


// express server
exports.emails = firebaseClient.fnHandler((req, res) => {
  console.log("/emails");
  findEmail("https://celsius.network")
    .then(email => {
      console.log("EMAILLLLLLLLL: ", email);
      res.send("/emails | Complete");
    })
    .catch(err => {
      console.log("findEmail error: ", err);
    });
})

```

Error:

```
info: EMAIL Promise { <pending> } 
info: findEmail error:  Error: Protocol error (Runtime.callFunctionOn): Target closed.
```

1. It's returning a promise for the 1st log
2. There's an error "Target closed"

P.S. it seems like I can use async / await.

**Comment by MehdiRaash** [comment]
I'm sorry I should have use then here as well.
```
const findEmail = url =>
  new Promise((resolve, reject) => {
    puppeteer.launch().then(function(browser) {
      browser.newPage().then(function(page) {
        page.goto(url);
        page.evaluate(
          () => document.querySelector('a[href^="mailto:"]').textContent
        ).then(function(textContent){
            console.log("EMAIL", textContent); // should be presale@celsius.network
           resolve(textContent);
           browser.close();
         });
        
      });
    });
  });
```

**Comment by EdmundMai** [comment]
That fixed that error, but for some reason I still don't get any contents
for that node:

error: (node:41590) UnhandledPromiseRejectionWarning: Unhandled promise
rejection (rejection id: 1):
Error: Evaluation failed: TypeError: Cannot read property 'textContent' of
null

**Comment by MehdiRaash** [comment]
Yes, I should have wrapped then for... sorry.
If you do just for example `resolve(111);` and you get 111, for sure your code is Okay, and the problem is about the node, maybe it hasn't been rendered yet.

**Comment by EdmundMai** [comment]
Shouldn't the ".then()" take care of that? Even if I replace the selector
with "body" instead of the mailto link it still fails

**Comment by MehdiRaash** [comment]
you can use `page.waitForSelector(yourselector)`,before retrieving the node for example to make sure, it's rendered.
But just change your code to async/await because in this way your code would get much complicated.

**Comment by MehdiRaash** [comment]
No, `then` has nothing to do about that, for example in `page.evaluate`, its **then** wouldn't know whether wait for a node or not.

**Comment by MehdiRaash** [comment]
this is my code when my node needs to be rendered after the web page received.
```
await page
    .waitForSelector("#forExampleLogginButton")
    .then(() => {
      return Promise.resolve(
        page.evaluate(() => { 
          return window.document
            .querySelector("#forExampleLogginButton")
            .innerHTML;

        })
      )
    })
```

**Comment by MehdiRaash** [comment]
Maybe it would help. but this kind of **then**ish code wouldn't survive of bug.
