### ISSUE TITLE
Camera permisons and choose dialog

### ISSUE THREAD

**Issue by ruslanx3m** [puppeteer/puppeteer#13276]
### Minimal, reproducible example

```TypeScript
not matter
```

### Background

Hi, how I can obtain permisons dialog like this ?

![image](https://github.com/user-attachments/assets/c05c8b8e-77c9-4046-8ce4-b2a88a78decb)

 

### Expectation

![image](https://github.com/user-attachments/assets/9dc956e4-af08-4911-8f14-bbd6c70f4dfb)

### Reality

![image](https://github.com/user-attachments/assets/1e141269-19d8-49b7-b10c-ffa79ef7d6f3)

### Puppeteer version

latest

### Node version

latest

### Package manager

npm

### Package manager version

latest

### Operating system

Windows

**Comment by OrKoN** [comment]
That is at the moment not possible similar to the https://github.com/puppeteer/puppeteer/issues/8813
The only thing that is currently supported in CDP is connecting bluetooth devices https://pptr.dev/api/puppeteer.page.waitfordeviceprompt/#example

**Comment by ruslanx3m** [comment]
No,
I need this dialog to appear so I can manually select the camera. How is this possible?
I can use CDP if needed.

**Comment by OrKoN** [comment]
> No, I need this dialog to appear so I can manually select the camera. How is this possible? I can use CDP if needed.

It should be possible by requesting camera access through web APIs (you can use page.evaluate() to call corresponding functions). If that dialog is only available when interacted via the browser UI, then it cannot be access via CDP.
