### ISSUE TITLE
[Bug]: Does not launch a new page on Linux, but works on macOS. Works on node with Linux and macOS

### ISSUE THREAD

**Issue by andrew-stelmach** [puppeteer/puppeteer#13279]
### Minimal, reproducible example

```TypeScript
console.log("going to google.com")
const browser = await puppeteer.launch({headless, args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',  // Important for CI environments
        '--disable-accelerated-2d-canvas',
        '--disable-gpu',  // Required for some Linux environments
        '--window-size=1920,1080'
]});
console.log("hello")
const page = await browser.newPage();

await page.goto("google.com")
```

### Background

Creating a monkey-testing script to click button randomly on a website. This works locally on macOS with [bun](https://github.com/oven-sh/bun) but does not work on Linux + bun. 

The intended behavior works on node on all platforms

### Expectation

It should open a new tab at the given url.

### Reality

On macOS, it works fine. But with linux, it does not open a new tab

### Puppeteer version

puppeteer@23.7.1

### Node version

v22.5.1

### Package manager

npm

### Package manager version

10.9.0

### Operating system

macOS

**Comment by OrKoN** [comment]
We do not support bun (https://pptr.dev/guides/system-requirements). If there is a fix we can do for it, happy to review a pull request. It's worth checking if you have all system dependencies for running the browser on your Linux host (https://pptr.dev/guides/system-requirements).  Also, see https://pptr.dev/troubleshooting and https://pptr.dev/guides/debugging#debugging-methods-for-the-browser-code
