### ISSUE TITLE
[Bug]: Kubernetes PodSecurityPolicy fails for Puppeteer container due to non-numeric user in Dockerfile

### ISSUE THREAD

**Issue by dulith-muthu** [puppeteer/puppeteer#13270]
### Minimal, reproducible example

```TypeScript
// To reproduce this issue, run a puppeteer Docker container in a Kubernetes environment where PodSecurityPolicy requires runAsNonRoot.
```

### Background

When deploying the Puppeteer container in a Kubernetes environment with a `PodSecurityPolicy` that enforces `runAsNonRoot`, the container fails to start because it cannot verify that the `pptruser` user is non-root. This is due to `USER pptruser` using a non-numeric username, which causes Kubernetes to be unable to verify the non-root status. 

_Suggested Solution_: Use an environment variable (PPTRUSER_UID) and modify the Dockerfile to set USER to a numeric ID instead of the username:
```
ENV PPTRUSER_UID=10042

# Add pptruser.
RUN groupadd -r pptruser && useradd -u $PPTRUSER_UID -rm -g pptruser -G audio,video pptruser

USER $PPTRUSER_UID
```

### Expectation

The Puppeteer container should start successfully in Kubernetes environments with `PodSecurityPolicy` set to `runAsNonRoot`, without violating the policy due to a non-numeric user.

### Reality

The container fails to start due to a `PodSecurityPolicy` restriction when using a non-numeric username (pptruser), with the following error:
```
Error: container has runAsNonRoot and image has non-numeric user (pptruser),
cannot verify user is non-root
```

### Puppeteer version

23.6.1

### Node version

20.18.0

### Package manager

npm

### Package manager version

10.8.3

### Operating system

Linux

**Comment by dulith-muthu** [comment]
Linking [PR #13230](https://github.com/puppeteer/puppeteer/pull/13230) for reference.

**Comment by OrKoN** [comment]
Thanks for the PR!
