### ISSUE TITLE
[Bug]: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Zendimaribg** [puppeteer/puppeteer#13283]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const browser = await puppeteer.launch({
        headless: false,
	args: ['--no-sandbox', '--disable-setuid-sandbox'],
		defaultViewport: null,
	});
	
const page = await browser.newPage();
await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');
```

### Expectation

works without error

### Reality

error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

### Puppeteer version

23.7.1

### Node version

18.20.4

### Package manager

npm

### Package manager version

10.9.0

### Operating system

Linux

**Comment by OrKoN** [comment]
See https://pptr.dev/guides/system-requirements and please make sure you have system dependencies installed. The error indicates that libatk is missing.

**Comment by ViniciusFXavier** [comment]
Hi @Zendimaribg,

With these commands, you can set up and run the environment on any Linux distribution, including Ubuntu, CentOS, WSL (1, 2), and even [CodeSandbox](https://codesandbox.io/). Follow these steps:

1. **Update Package List and Apply Updates**  
   First, update the list of packages and apply the updates:  
   ```bash
   sudo apt update  
   sudo apt upgrade -y  
   ```  
   This ensures your system is up to date.  

2. **Install Dependencies for Chromium**  
   Install all necessary libraries and dependencies required to run Chromium:  
   ```bash
   sudo apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils  
   ```  
    Yes, there are several dependencies. :sweat:

3. **Handle DISPLAY Issues (if applicable)**  
   If you encounter issues related to the `DISPLAY` environment variable, run the following command to allow Linux GUI apps to connect:  
   ```bash  
   export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0  
   ```  

4. **Install Chromium if Not Found**  
   If Chromium is not installed or cannot be found, add the Chromium repository and install it:  
   ```bash  
   sudo add-apt-repository ppa:chromium-team/stable  
   sudo apt-get update  
   sudo apt install chromium-browser  
   ```
