### ISSUE TITLE
[Bug]: window.[prop] set via content script in chrome extension is not accessible via frame.frameElement

### ISSUE THREAD

**Issue by zibsonzs** [puppeteer/puppeteer#13282]
### Minimal, reproducible example

```TypeScript
Settings window.MY_PROP in content scripts in chrome extension with this config in manifest:


 {
      matches: ["http://*/*", "https://*/*", "<all_urls>"],
      all_frames: true,
      js: ["content_main/index.iife.js"],
      world: "MAIN",
    },

```

index.iife.js sets it with window.MYPROP = "test";

```

const f = page.frames()[2]; // any frame

const xd = await f.evaluate(()=>{
window.MY_PROP // works
})


 const frameElem = await f.frameElement();
 
 const xd = await frameElem.evaluate(()=>{
window.MY_PROP // doesn't exist
})
```

### Expectation

MY_PROP to exist in window object when calling evaluate in frameElement.
I want to be able to use a function attached to window and have access to framElement that is only provided via frame.frameElement.

### Reality

window.MY_PROP is undefined

### Puppeteer version

23.4.0

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

Windows

**Comment by OrKoN** [comment]
Content scripts are isolated from the main execution context and Puppeteer runs evaluations in the main world context, so any extensions to window will not be accessible. That should not work any case: could you please update the reproducible example to include a test extension and the complete script you run including a test page?

**Comment by OrKoN** [comment]
I think I overlooked the world configuration in the snippet. I am not very familiar with how that works in extensions but at the first sight this should work although Puppeteer does not do anything special for evaluation here. Are you able to access MY_PROP in DevTools if you choose the context of where the iframe element returned by frameElement is?

**Comment by zibsonzs** [comment]
I know what is wrong. Basically the way it works in all puppeeter page/frame.evaluate calls is that it is executed in the main world. For some reason, when we request  f.frameElement() and run evaluate on it, the evaluate function is executed in the isolated world which I believe is not intended.
If you look into frameElement implementation in the Frame object you'll see this:


```
export const getFrameElement = async (f: Frame): Promise<HandleFor<HTMLIFrameElement> | null> => {
  const parentFrame = f.parentFrame();
  if (!parentFrame) {
    return null;
  }
  using list = await parentFrame.isolatedRealm().evaluateHandle(() => {
    return document.querySelectorAll("iframe,frame");
  });
  for await (using iframe of transposeIterableHandle(list)) {
    const frame = await iframe.contentFrame();
    if (frame?._id === f._id) {
      return (iframe as HandleFor<HTMLIFrameElement>).move();
    }
  }
  return null;
};
```

It's using isolatedRealm which I believe is wrong. I've made a copy of this function into my source code and replaced it with mainWorld and everything works flawlessly.

**Comment by OrKoN** [comment]
@zibsonzs it looks like you are using a slightly older version. This implementation is currently used only for the WebDriver BiDi protocol. The CDP implementation is here https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/Frame.ts#L429 and I believe that one works correctly already. We should fix the non-CDP-specific implementation though.

**Comment by zibsonzs** [comment]
I'm talking about Frame implementation in the api:
https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/api/Frame.ts#L416

**Comment by OrKoN** [comment]
> I'm talking about Frame implementation in the api: https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/api/Frame.ts#L416

Right, and that one is not used in the latest Puppeteer version for CDP. So if you upgrade the Puppeteer version and you use CDP, you should not experience this issue anymore.

**Comment by zibsonzs** [comment]
Thanks for assist!
