### ISSUE TITLE
$ is not a function of ElementHandle.

### ISSUE THREAD

**Issue by lau-a** [puppeteer/puppeteer#1328]
Running puppeteer 0.12.0v

Getting an error where $ is not a function of ElementHandle.  Are elementHandles even meant to have this? Because it's in the documentation: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-elementhandle 

This is what I'm doing:
```

        await page.goto(url)
        var frame = await page.frames()[0];
        await page.waitFor("iframe")
        var child = frame.childFrames()[0]
        // wait for the image cut block to be visible
        await child.waitFor("section[data-type=imagecut]")
        // open the image cut
        let section = await child.$("section[data-type=imagecut] h1")
        await section.click()
        let elements = await child.$$("section[data-type=imagecut] fieldset div")
        for (let element of elements)
        {
            let a = await element.$("a")
            await a.click()
            await child.waitFor(2000)
        }

```

What I expected to happen was that it would find an <a> tag from the reference of the div then I would be able to click it.

Instead, it just gives me that $ is not function of element.

**Comment by vsemozhetbyt** [comment]
`elementHandle.$(selector)` is available from the v0.13.0-alpha. You can upgrade with `npm install https://github.com/GoogleChrome/puppeteer/`.
