### ISSUE TITLE
[Feature]: puppeteer elementHandle by index or by checking textContent

### ISSUE THREAD

**Issue by noname29** [puppeteer/puppeteer#13297]
### Feature description

I have a page similar to this

```
    <div class="myclass">Some Text 1 </div>
    <div class="myclass">Some Text 2 </div>
    <div class="myclass">Some Text 3 </div>
    <div class="myclass">Some Text 4 </div>

```
I want to get the elementHandle of these in puppeter using 

`    await page.$('.myclass');
`
But i want to get the element by index, something similarto

`    await page.$('document.querySelectorAll(\'div[class="myclass"]\')[' +  myIndex ']')
`
or by checking the textContent (pseudo code)

`     await page.$('document.querySelectorAll(\'div[class="myclass"]\').foreach => textContent == Some Text 2')
`

Is it possible to achieve this with puppeteer nodejs ?

**Comment by OrKoN** [comment]
You can use `$$` https://pptr.dev/api/puppeteer.page.__/ to find multiple elements (and then get a match by index or filter) and `page.evaluate()` https://pptr.dev/api/puppeteer.page.evaluate/  to implement custom querying.
