### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by noname29** [puppeteer/puppeteer#13299]
### Minimal, reproducible example

```TypeScript
const session = await page.target().createCDPSession();

await session.send('Input.synthesizeScrollGesture', { 
							x: 100,
							y: 200,
							yDistance: -150
						});
```

### Background

I have this code, and when I use page.goto() as it is scrolling, puppeteer crashes with

### Expectation

```
 return Promise.reject(new Errors_js_1.TargetCloseError(`Protocol error (${method}): Session closed. Most likely the ${this.#targetType} has been closed.`));
                                  ^

TargetCloseError: Protocol error (Input.synthesizeScrollGesture): Session closed. Most likely the page has been closed.
    at CdpCDPSession.send 
```

### Reality

I want a way to detach the session or safely go to the next page, I found `CDPSession.detach()` but cant get it t work 

### Puppeteer version

latest

### Node version

latest

### Package manager

npm

### Package manager version

latest

### Operating system

Windows

**Comment by OrKoN** [comment]
Duplicate https://github.com/puppeteer/puppeteer/issues/13300? Consider posting this kind of questions on StackOverflow. If you believe there is a bug, please fill out the form completely specifying correct versions for the versions you use and a minimal reproducible example that demonstrates the issue.
