### ISSUE TITLE
page.addScriptTag not working

### ISSUE THREAD

**Issue by runjuu** [puppeteer/puppeteer#1330]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^0.12.0
* Platform / OS version: https://try-puppeteer.appspot.com
* URLs (if applicable): https://example.com

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('https://example.com');
const scriptHandle = await page.addScriptTag({ content: "window.__injected = 35;" });
console.log(scriptHandle); // undefined
console.log(scriptHandle.asElement());
const res = await page.evaluate(() => __injected);
console.log(res);
console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();
```

**What is the expected result?**
https://github.com/GoogleChrome/puppeteer/blob/7d18275fb981e01cec4a4fbac61a9c66e46947bc/test/test.js#L2504

**What happens instead?**
`await page.addScriptTag` return `undefined`, and It seems like `window.__injected = 35;` did not add to the page

**Comment by vsemozhetbyt** [comment]
`page.addScriptTag()` resolves to `ElementHandle` in the v0.13.0-alpha. Compare [v0.12.0 doc](https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#pageaddscripttagoptions).

You can upgrade with `npm install https://github.com/GoogleChrome/puppeteer/`.
