### ISSUE TITLE
[Bug]: PuppeteerNode.executablePath() method doesn't take into account headless mode

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#13308]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'
console.log(puppeteer.executablePath())
```

### Background

`PuppeteerNode.executablePath()` returns the path of the main Chrome executable. In fact if you `launch()` with `headless: 'shell'` then this is not the executable that Puppeteer will run. Not only is there no way to ask Puppeteer which executable it will run for 'old headless' mode, the fact that the value returned by this function isn't necessarily the file that will be executed isn't documented.

### Expectation

The moon on a stick.

### Reality

Reality is often a sad let-down.

### Puppeteer version

23.8.0

### Node version

n/a

### Package manager

npm

### Package manager version

n/a

### Operating system

Linux

**Comment by OrKoN** [comment]
Note that the documentation for this method says that it returns the default executable path and the `headless: 'shell'` is not the default mode of running Puppeteer anymore. Generally though, the method is confusing and we should probably remove it or at least document it better. To compute the actual executable path we need to consider specific arguments for the launch function.

**Comment by jribbens** [comment]
Indeed. This has caused me some recent issues because, for reasons of previous changes in puppeteer that I don't entirely recall, I was setting `PUPPETEER_EXECUTABLE_PATH` to the output of `executablePath()` and at some point in the recent past further changes to puppeteer have had the effect that when I was launching it with `headless: 'shell'` this was being silently ignored / overridden by the environment variable, and the numerous subtle differences / bugs between "old headless" and "new headless" were causing many mysterious and inexplicable issues.
