### ISSUE TITLE
[Bug]: Pages with recaptcha crash CDP in docker (ProtocolError: Input.dispatchMouseEvent timed out)

### ISSUE THREAD

**Issue by LewisW** [puppeteer/puppeteer#13317]
### Minimal, reproducible example

```TypeScript
  import puppeteer from "puppeteer";

  const browser = await puppeteer.launch({
    args: ["--no-sandbox", "--disable-gpu"],
  });
  const page = await browser.newPage();
  await page.goto("https://www.google.com/recaptcha/api2/demo");

  await page.mouse.wheel({
    deltaX: 0,
    deltaY: 10,
  });

  await page.mouse.wheel({
    deltaX: 0,
    deltaY: -10,
  });

  console.log("I am never executed");

  await browser.close();
```

### Background

CDP seems to crash when loading pages with recaptcha in docker. I've tried a number of different docker images (my own, the official one and alphine-chrome) and a number of different puppeteer versions (22.6.5 upwards), and a number of different flags - all seem to exhibit the behaviour. It didn't seem to happen on older versions of chrome so I'll try and narrow down where it started. Occasionally the test script will run but the majority of times it will freeze.

Running the script locally in OS X seems to work fine (headless and headfull).

### Expectation

Both actions should be performed and the final console.log should be displayed

### Reality

Puppeteer refuses to run the second action and freezes, eventually timing out.

ProtocolError: Input.dispatchMouseEvent timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at Callback.<instance_members_initializer> (/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:117:12)
    at new Callback (/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:122:3)
    at CallbackRegistry.create (/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:28:22)
    at Connection._rawSend (/node_modules/puppeteer-core/src/cdp/Connection.ts:125:22)
    at CdpCDPSession.send (/node_modules/puppeteer-core/src/cdp/CDPSession.ts:95:29)
    at CdpMouse.wheel (/node_modules/puppeteer-core/src/cdp/Input.ts:470:24)

### Puppeteer version

23.9.0

### Node version

20.18.1

### Package manager

npm

### Package manager version

10.3.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Not able to reproduce using the latest Docker image: 

```
~/pptr-test$ podman run -i --init --cap-add=SYS_ADMIN --rm ghcr.io/puppeteer/puppeteer:23.9.0 node -e "$(cat captcha.cjs)"
I am never executed
```

AFAIK on MacOS the script runs in a virtual machine running a Linux so perhaps there is some issue with it.
