### ISSUE TITLE
Unable to open new pages using connect() and master

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#1331]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: master
* Platform / OS version: OSX
* URLs (if applicable): N/A

**What steps will reproduce the problem?**

```js
/* eslint-disable no-console, filenames/match-regex, import/no-commonjs */

/**
 * @file Ensure that Chrome can properly start and close.
 */
const puppeteer = require('puppeteer');

const test = async () => {
  console.log('Testing if Chrome works');

  const defaultViewport = {
    deviceScaleFactor: 1,
    hasTouch: false,
    height: 1024,
    isLandscape: false,
    isMobile: false,
    width: 1280
  };
  
  const browser = await puppeteer.connect({
    browserWSEndpoint: 'ws://127.0.0.1:9222/devtools/browser/d9f8012e-94b8-4441-ad1e-1cf8de94e57f',
    ignoreHTTPSErrors: true
  });

  console.log('Hello! 1');

  const page = await browser.newPage();

  console.log('Hello! 2');

  await page.setViewport(defaultViewport);

  console.log('Hello! 3');

  const navigationPromise = page.waitForNavigation();

  console.log('Hello! 4');

  await page.goto('https://applaudience.com/');

  console.log('Hello! 5');

  await navigationPromise;

  console.log('Hello! 6');

  await browser.close();

  console.log('Chrome is working expected.');
};

test();

```

**What is the expected result?**

This is the result using v0.12.

```
Testing if Chrome works
Hello! 1
Hello! 2
Hello! 3
Hello! 4
Hello! 5
Hello! 6
Chrome is working expected.

```

**What happens instead?**

This is the result using v0.13-alpha (master).

```
Testing if Chrome works
Hello! 1

```

**Comment by ebidel** [comment]
Hi @gajus, I just pulled from master and that code is working for me.

**Comment by gajus** [comment]
Closing for now.

Unable to replicate the issue.

Will follow up when I figure a consistent way to replicate it.

**Comment by tox2ik** [comment]
please have another look.

$ node --version 
v8.9.1


$ node issue-1331.js 


## Chromium 61.0.3163.79


Error: Protocol error (Target.setDiscoverTargets): 'Target.setDiscoverTargets' wasn't found undefined
    at Connection._onMessage (/T/initio/corda/git/htdocs/editor/js/node_modules/puppeteer/lib/Connection.js:97:25)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/T/initio/corda/git/htdocs/editor/js/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/T/initio/corda/git/htdocs/editor/js/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/T/initio/corda/git/htdocs/editor/js/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/T/initio/corda/git/htdocs/editor/js/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/T/initio/corda/git/htdocs/editor/js/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/T/initio/corda/git/htdocs/editor/js/node_modules/ws/lib/WebSocket.js:139:22)
    at emitOne (events.js:116:13)
Hello! 1
(node:4701) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'newPage' of undefined
(node:4701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


## Google Chrome 62.0.3202.94 

$ node issue-1331.js ws://127.0.0.1:9222/devtools/browser/544b0f04-97c4-411d-b16f-248017c43b09
Testing if Chrome works ws://127.0.0.1:9222/devtools/browser/544b0f04-97c4-411d-b16f-248017c43b09
Hello! 1 object
Hello! 2 object
(node:11166) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'setViewport' of null
(node:11166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
/* eslint-disable no-console, filenames/match-regex, import/no-commonjs */

/**
 * @file Ensure that Chrome can properly start and close.
 */
const puppeteer = require('puppeteer');
const ws = require('process').argv[2];



const test = async () => {
  console.log('Testing if Chrome works', ws);

  const defaultViewport = {
    deviceScaleFactor: 1,
    hasTouch: false,
    height: 1024,
    isLandscape: false,
    isMobile: false,
    width: 1280
  };
  
  const browser = await puppeteer.connect({
    //browserWSEndpoint: 'ws://127.0.0.1:9222/devtools/browser/aa15c21a-1b7d-42ae-b385-cb6a91ae230e',
    browserWSEndpoint: ws,
    ignoreHTTPSErrors: true
  }).catch(console.error);

  console.log('Hello! 1', typeof browser);

  const page = await browser.newPage()
  //.catch(console.error);

  console.log('Hello! 2', typeof page);

  await page.setViewport(defaultViewport).catch(console.error);

  console.log('Hello! 3');

  const navigationPromise = page.waitForNavigation().catch(console.error);;

  console.log('Hello! 4');

  await page.goto('https://applaudience.com/').catch(console.error);;

  console.log('Hello! 5');

  await navigationPromise;

  console.log('Hello! 6');

  await browser.close();

  console.log('Chrome is working expected.');
};

test();
```
