### ISSUE TITLE
[Bug]:Install puppeteer package

### ISSUE THREAD

**Issue by rasulRahmati** [puppeteer/puppeteer#13322]
### Minimal, reproducible example

```TypeScript
npm install puppeteer@latest
npm install --force puppeteer@latest
npm install --legacy-peer-deps puppeteer@latest
```

### Background

I get a weird error every time I try to install puppeteer. also used --force and --legacy-peer-deps

### Expectation

npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.   
npm error code 1
npm error path C:\Users\userName\Desktop\myTests\Next.js\my-app\node_modules\puppeteer
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node install.mjs
npm error **INFO** Skipping Firefox download as instructed.
npm error Error: ERROR: Failed to set up chrome v131.0.6778.85! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm error     at downloadBrowser (file:///C:/Users/userName/Desktop/myTests/Next.js/my-app/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:26:15)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
npm error     at async Promise.all (index 0)
npm error     at async downloadBrowsers (file:///C:/Users/userName/Desktop/myTests/Next.js/my-app/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:84:9) {
npm error   [cause]: Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.85/win64/chrome-win64.zip
npm error       at file:///C:/Users/userName/Desktop/myTests/Next.js/my-app/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:67:31    
npm error       at ClientRequest.requestCallback (file:///C:/Users/userName/Desktop/myTests/Next.js/my-app/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:45:13)
npm error       at Object.onceWrapper (node:events:633:26)
npm error       at ClientRequest.emit (node:events:518:28)
npm error       at HTTPParser.parserOnIncomingClient (node:_http_client:704:27)
npm error       at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
npm error       at TLSSocket.socketOnData (node:_http_client:546:22)
npm error       at TLSSocket.emit (node:events:518:28)
npm error       at addChunk (node:internal/streams/readable:561:12)
npm error       at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
npm error }
npm error A complete log of this run can be found in: C:\Users\userName\AppData\Local\npm-cache\_logs\2024-11-25T04_42_08_850Z-debug-0.log   

### Reality

Install package

### Puppeteer version

latest

### Node version

22.11.0

### Package manager

npm

### Package manager version

10.9.1

### Operating system

Windows

**Comment by OrKoN** [comment]
I am not able to reproduce. I believe the CDN https://storage.googleapis.com/chrome-for-testing-public/ might not be available in your region or not accessible for other reasons. You could skip the download as the error message indicates and try to download the browser in another way.
