### ISSUE TITLE
uploadFile don´t work with selectors css

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1332]
My button does not have (input[type="file"]).

I understand that **_elementHandle.uploadFile_** only works with (input[type="file"]) and not with id and class selectors css ??

`const` uplo = await `page.$(".btnAddPhoto");`
`await` `uplo.uploadFile('image.jpg');`

## Out:

```
(node:3584) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (DOM.setFileInputFiles): _**# Node is not a file input element undefined**_
(node:3584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by JoelEinbinder** [comment]
How does your site receive images? As far as I know, files can only be uploaded to `input` elements with `type="file"`.

**Comment by ebidel** [comment]
@fran0254 can you post a larger code snippet with the url you're testing against. We need more info to be helpful!  

You should be selecting the file input with `page.$` instead of the button that activates the upload. If you're not using a `input type=file` on the page, is the button using [`xhr.send(blob)`](https://www.html5rocks.com/en/tutorials/file/xhr2/#toc-send-blob) to send the file? In that case, it wouldn't be appropriate to use `.uploadFile()`.

**Comment by fran0254** [comment]
how can you check does not exist **input type="file"**. 
Is there a possibility to upload my files using css selectors?

**code of site:**

``` html

<div class="insertadonCol">
    <div class="photoUploaderWrapper">
        <div id="dropArea">
            <form action="/images/upload-image-tmp.php"
                  method="post" class="dropzone" drop-zone="" id="photoUploader"
                  enctype="multipart/form-data"></form>
        </div>
    </div>
</div>
```

**Code of site DOM**

![captura de pantalla de 2017-11-13 08 18 54](https://user-images.githubusercontent.com/32681199/32713932-c5b58944-c84b-11e7-95d5-bbad9da6de6b.png)


![captura de pantalla de 2017-11-13 08 12 19](https://user-images.githubusercontent.com/32681199/32713704-ca7dd7ac-c84a-11e7-8903-503fd2cc4f07.png)

**Comment by ebidel** [comment]
I don't see an `input type="file"` in your markup or code that handles a file upload in your example. But in theory, you could use puppeteer to "drop" a file onto the form and then use `page.evaluate` to call `form.submit()` or do something like https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-elementhandle.

**Comment by fran0254** [comment]
Should I use coordinates to drop the file in the box? Can you please put a small example? I do not know how I could do it ...

**Comment by JoelEinbinder** [comment]
We currently don't have support for drop targets. Filed it as #1376

**Comment by aslushnikov** [comment]
Closing in favor of #1376.
