### ISSUE TITLE
[Bug]: Unable to make use of Puppeteer on Vercel.

### ISSUE THREAD

**Issue by Don-Vicks** [puppeteer/puppeteer#13326]
### Minimal, reproducible example

```TypeScript
Hey Guys, 
So am using this package to process screenshots, it works well on my Laptop however when I deploy it to Vercel. Vercel complains on it not finding the core please how do I fix this?
```

### Expectation

Work as intended on Localhost

### Reality

Fails

### Puppeteer version

23.9.0

### Node version

20x

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Linux

**Comment by OrKoN** [comment]
I think this sort of questions is more suitable for StackOverflow as we are not able to provide Vercel-specifci guidance (except for making sure your node_modules are installed and the browser is downloaded either by npm install or via the puppeteer CLI). Also, see https://pptr.dev/troubleshooting covering various common issues.

**Comment by Don-Vicks** [comment]
Ok, But am curious, On which Platform can I deploy this and have it work well?
