### ISSUE TITLE
connect with wsendpoint to browser do not go to link 

### ISSUE THREAD

**Issue by H91011** [puppeteer/puppeteer#1334]
* Puppeteer version: 0.12.0
* Platform / OS version: 4.4.0-98-generic GNU/Linux Ubuntu 16.04

I try to connect browser with wsendpoint and I connect but I can not go to link

firstly I use this command from terminal: 

`/opt/google/chrome/chrome --remote-debugging-port=9222 `

and I get id from:  http://localhost:9222/json

then,
here is my code :

```
(async () => {
    const browser = await puppeteer.connect({browserWSEndpoint: 'ws://localhost:9222/devtools/page/eedbdd50-cd25-472d-a701-a0302d9ffe2f'});
  const page = await browser.newPage();
  await page.goto('https://www.google.com.tr');
})();
```

Browser open a new tab but do not go to link. It give an error:

```
(node:13131) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Performance.enable): 'Performance.enable' wasn't found undefined
(node:13131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ebidel** [comment]
The url I get back from `browser.wsEndpoint();` is something like:

`ws://127.0.0.1:51835/devtools/browser/e1479161-b5df-471c-919a-b1e0e61892ea`

e.g. "/browser" instead of "/page". If you change that does it work?

**Comment by joelgriffith** [comment]
+1 to @ebidel, the `/browser` endpoint is a special debugging endpoint, and is what puppeteer expects as it's more or less the host route. Giving it another likely results in odd errors that you're experiencing

**Comment by H91011** [comment]
Thanks @ebidel , @joelgriffith  it is working with browser. But when I start with `/opt/google/chrome/chrome --remote-debugging-port=9222`  I do not see in like `.../browser/...` in json response all of it `.../page/...` I want to run spesific port from docker is there any solution for this ?` browser.wsEndpoint();` return different port each time.

**Comment by joelgriffith** [comment]
It's a tricky procedure, which I've faced in a service I run (https://browserless.io). You can find that `/browser` endpoint by hitting: `http://localhost:9222/json/version`. There's a lot of great documentation here: https://chromedevtools.github.io/devtools-protocol/ about the protocol in general, which is useful for knowing if you're going to be dockerizing chrome or trying to add a service-layer on top of it.

**Comment by H91011** [comment]
today I check  `http://localhost:9222/json/version ` but there is not  any link with `.../browser/...`
here is the output: 
 `{
   "Browser": "Chrome/61.0.3163.100",
   "Protocol-Version": "1.2",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
   "V8-Version": "6.1.534.41",
   "WebKit-Version": "537.36 (@57c9d07b416b5a2ea23d28247300e4af36329bdc)"
}`

**Comment by joelgriffith** [comment]
> Chrome/61.0.3163.100

I believe this version of chrome doesn’t return the /browser details in the endpoint I mentioned. If you start it from the CLI then it’ll likely print it. Alternatively you can upgrade your version to a more recent one where it is exported (at least version 63 if I recall correctly).

**Comment by H91011** [comment]
Yes the problem is chrome version I install latest version "Browser": "Chrome/62.0.3202.89" it return right link.

**Comment by andreaderrico2** [comment]
Hi, I have the same problem I think.

I'm able to open a new tab in the smartphone chrome, but the tab remains blank.

my http://localhost:9222/json/version

{
   "Android-Package": "com.android.chrome",
   "Browser": "Chrome/89.0.4389.105",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (Linux; Android 6.0.1; ASUS_Z016S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36",
   "V8-Version": "8.9.255.20",
   "WebKit-Version": "537.36 (@14f44e21a9d539cd49c72468a29bfca4fa43f710)",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/browser"
}

my puppeteer script:

const puppeteer = require('puppeteer');

function run () {
  return new Promise(async (resolve, reject) => {
    try {

      const browser = await puppeteer.connect({ 
        browserWSEndpoint: 'ws://localhost:9222/devtools/browser',
        headless: true,
        devtools: true 
      });
      const page = await browser.newPage();

      
      var url = 'http://www.google.it'
      await page.goto(url, {waitUntil: 'domcontentloaded'});
           

      
      browser.close()
      
    
    } catch (e) {
      return reject(e);
    }
  })
}
run().then(console.log).catch(console.error);

Can you help me? Thanks
