### ISSUE TITLE
[Feature]: Pdf single-page footer, like table tfoot

### ISSUE THREAD

**Issue by ddesign84** [puppeteer/puppeteer#13341]
### Feature description

puppeteer pdf generation

I wanted to implement the end of the page function, but there was no good solution, We hope to get help from the community.

For example: There are 10 lines in total on one page, and 3 lines on the footer

example1：
When the content is less than or equal to 7 lines, the footer is always at the bottom of the page
![image](https://github.com/user-attachments/assets/c261f50d-cefb-460a-8ea1-575543457c4b)

example2：
When the content is greater than 7 lines, the footer is always at the bottom of the second page
![image](https://github.com/user-attachments/assets/83a1d388-92c0-4c04-a688-3ed4df51b0df)

I tried to
'css position fixed' and 'Calculate content height based on DOM's scrollHeight and offsetTop', 
However, the content contains 'table thead tfoot' and 'page-break-inside', and the positioning is inaccurate.

**Comment by OrKoN** [comment]
I think StackOverflow is the most suitable for this sort of questions: https://stackoverflow.com/questions/tagged/puppeteer

If you find a bug, please fill out the bug report form along with a minimal reproducible example.
