### ISSUE TITLE
Environment Variable & npm config for executablePath

### ISSUE THREAD

**Issue by Saturate** [puppeteer/puppeteer#1335]
You can't currently tell other packages to use a bundled chrome version. This could be implemented in the packages, for example [penthouse](https://github.com/pocketjoso/) (See https://github.com/pocketjoso/penthouse/pull/177 for discussions).

However it seems that it would be beneficial to implement this change here, as all consumers would benefit for it, and even use the same bundle version, unless something else was specified.

I'm thinking `PUPPETEER_EXECUTABLE_PATH` in the environment or in the npm config like the rest of the variables.

Here is the current code with no support for this: https://github.com/GoogleChrome/puppeteer/blob/f5bb333cd0c42306f47e7767e5cb8b78af557c27/lib/Launcher.js#L89-L94

**Comment by r3dDoX** [comment]
Did you see `require('puppeteer').executablePath()`?
IMO this is a good way for consumers to get that path.

**Comment by Saturate** [comment]
@r3dDoX 

As I understand it's great for getting the default path.

But due to corporate firewall restrictions I have to use `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` and bundle Chromium with the code package.

As far as I see, right now I can't point penthouse, or another other package that consumes puppeteer to the correct path ie `./build/bundled/chromium/chrome.exe`. It will try to use the default path, fail and give the following error message `Chromium revision is not downloaded. Run "npm instal"`

It could be built into penthouse, so that you could specify a path to use as an option for the `penthouse.launch` call, but it seems better to implement this in the penthouse package.

If people agree, I will create a PR.

**Comment by r3dDoX** [comment]
@Saturate 
ah I see. I misunderstood your problem.

We had a similar problem with our corporate firewall and solved it with the PR #958 by routing the download through our local Nexus Repo which acts as a proxy in that case. Should be in the next release of puppeteer. Maybe it could help you as well

**Comment by Saturate** [comment]
Thanks @r3dDoX, I did see this feature and it could be useful in the future right now - but right now we can't create a mirror of it.

**Comment by Saturate** [comment]
What I also discovered was that the host has to be HTTPS, this was is also a problem on the internal server.

**Comment by aslushnikov** [comment]
> What I also discovered was that the host has to be HTTPS, this was is also a problem on the internal server.

@Saturate the HTTP support was added some time ago.

Closing this based on the discussion in #1337 .
