### ISSUE TITLE
[Bug]:  Error: socket hang up | after update to MacOS Sequoia M1 from Sonoma

### ISSUE THREAD

**Issue by CloudItaly** [puppeteer/puppeteer#13375]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  try {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.setViewport({ width: 1920, height: 1080 });

    await page.goto('https://www.google.com');

    
    // Puoi aggiungere altre operazioni con la pagina qui...
  } catch (error) {
    console.error("Si è verificato un errore:", error);
  }
 
})();
```

### Expectation

Open browser

### Reality

Si è verificato un errore: ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://127.0.0.1:52742/devtools/browser/94306bc8-7c96-4cd7-9028-4aea4d74411e',
    _originalIpc: false,
    _originalSecure: false,
    _originalHostOrSocketPath: '127.0.0.1:52742',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: socket hang up
      at Socket.socketOnEnd (node:_http_client:536:25)
      at Socket.emit (node:events:536:35)
      at endReadableNT (node:internal/streams/readable:1698:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
    code: 'ECONNRESET'
  },
  [Symbol(kMessage)]: 'socket hang up'
}

### Puppeteer version

23.5.1

### Node version

v22.12.0

### Package manager

npm

### Package manager version

10.9.0

### Operating system

macOS

**Comment by CloudItaly** [comment]
after upgrading my macOS from Sonoma to Sequoia, i get that error.

**Comment by OrKoN** [comment]
I am not able to reproduce. Have you tried the latest Puppeteer version? what is the browser's log output when dumpio is set to true?

**Comment by CloudItaly** [comment]
with dumpio = true 

`[39243:259:1207/213116.809606:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.

DevTools listening on ws://127.0.0.1:63141/devtools/browser/4efc46ad-3878-4cbe-b3b7-09d8ea177dee
[1207/213117.510965:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)`

**Comment by CloudItaly** [comment]
**FIX.** 

I don't know why that code with SONOMA works with SEQUOIA it doesn't work.

But replacing this code:
`const browser = await puppeteer.launch({headless: false});`
with this: 
```
const browser = await puppeteer.launch({headless: false,
executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"});
```
now the "headless:false" mode also works fine.
