### ISSUE TITLE
[Bug]: Duplicate Chrome in Docker image, not linked

### ISSUE THREAD

**Issue by markusheiden** [puppeteer/puppeteer#13383]
### Minimal, reproducible example

- `/root/.cache/puppeteer` contains Chrome
- `/home/pptruser/.cache/puppeteer` contains Chrome (and the headless shell).
- All are not linked to e.g. `/usr/local/bin` .

### Background

- This is not a real problem, but not unnecessarily wasting resources would be nice.
- I don't want to download Chrome at runtime.

### Expectation

- Best effort to keep the Docker image small.
- Chrome and the headless shell are installed to e.g. `/opt` and are linked to e.g. `/usr/local/bin` so that they can be used securely and easily.

### Reality

It is quite hard to find the path of the bundled Chrome and the headless shell.

### Puppeteer version

23.10.1

### Node version

22

### Package manager

pnpm

### Package manager version

9.15.0

### Operating system

macOS

**Comment by OrKoN** [comment]
The presence of `/root/.cache/puppeteer` is indeed undesired. As for linking /usr/local/bin and installing into /opt, this is out of scope for this image which is meant to provide a puppeteer installation and it is not meant to be used for running the browser without Puppeteer.

**Comment by OrKoN** [comment]
Also, https://pptr.dev/api/puppeteer.puppeteernode.executablepath/#signature-2 provides the path to the binary for the Puppeteer installation

**Comment by markusheiden** [comment]
I tried `executablePath({ ... })` with many combinations of browser, channel, and headless. I never got the `chrome-headless-shell` binary as result. Why is it in the image? What is its use-case?

**Comment by OrKoN** [comment]
Specifying `headless: "shell"` uses the chrome-headless-shell binary.

```
import puppeteer from "puppeteer"; // 23.10.2 

console.log(puppeteer.executablePath({
  headless: 'shell',
}));

await puppeteer.launch({
  headless: 'shell',
});
```

**Comment by markusheiden** [comment]
Thanks! Sorry for bugging you...
