### ISSUE TITLE
[Bug]: cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by qingyuyu** [puppeteer/puppeteer#13389]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async ()=>{
 const browser= await puppeteer.launch();
 const page = await browser.newPage();
 await page.goto("http://xxxxxx");
})();
```

### Background

node version 12.6.0
npm version 6.9.0

dependencies:
bufferutil"^4.0.1"
puppeteer-core:"^23.10.2"
utf-8-validate:"6.0.5"

### Expectation

I would like to know if puppeteer is supported under the current node version.

### Reality

Error: Cannot find module pupeteer

### Puppeteer version

23.10.2

### Node version

12.6.0

### Package manager

npm

### Package manager version

6.9.0

### Operating system

Windows

**Comment by OrKoN** [comment]
You seem to be installing puppeteer-core and not puppeteer. Either install puppeteer or require('puppeteer-core'). Let me know if that helped.

**Comment by qingyuyu** [comment]
Actually, it did not work. 
Error:Cannot find module 'pupeteer-core/internal/puppeteer-core.js'
I try to install both pupetter,puetter-core. The Error still popped out.

**Comment by OrKoN** [comment]
That indicates an unsupported node version. Puppeteer requires at least Node 18+.
