### ISSUE TITLE
[Bug]: crash with last chromium version in debian repository 

### ISSUE THREAD

**Issue by codati** [puppeteer/puppeteer#13388]
### Minimal, reproducible example

src/index.js:
```js
const puppeteer = require('puppeteer');

const start = async()=>{
    const browser = await puppeteer.launch({
        headless: 'new',
      });
  console.log("run!!")
};
start().then(console.log, console.error);
```
Dockerfile:
```dockerfile
FROM node:22-bookworm
RUN cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.save
RUN sed -e "s/main/main contrib/" /etc/apt/sources.list.d/debian.sources.save > /etc/apt/sources.list.d/debian.sources
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    xdg-utils \
    chromium \
    && rm /var/lib/apt/ -rf
RUN npm install npm -g
COPY --chown=1000:1000 ./package.json /application/package.json
COPY --chown=1000:1000 ./package-lock.json /application/package-lock.json
COPY --chown=1000:1000 ./puppeteer.config.cjs /application/puppeteer.config.cjs
USER node
WORKDIR /application
RUN npm install --production && chown -R node:node /application
COPY --chown=1000:1000 src/ /application/src/
CMD ["npm", "run", "start"]
```
docker-compose.yml:
```yml
services:
  app:
    build: .
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
#    command: ["sleep","999999999"]
```
package.json:
```json
{
  "name": "bug-puppeteer",
  "version": "1.0.0",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "puppeteer": "^23.10.1"
  }
}
```

### Background

I am on a Mac Arm M2 running Docker

to fix temporarily, I force the chromium version in the docker file:
```
    chromium-common=130.0.6723.91-1~deb12u1 \
    chromium=130.0.6723.91-1~deb12u1 \
 ```

### Expectation

not crash

### Reality

```
app-1  | 
app-1  | > bug-puppeteer@1.0.0 start
app-1  | > node src/index.js
app-1  | 
app-1  | TimeoutError: Timed out after waiting 30000ms
app-1  |     at /application/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:258:19
app-1  |     at /application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3986:35
app-1  |     at OperatorSubscriber2._this._next (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1055:13)
app-1  |     at Subscriber2.next (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:678:16)
app-1  |     at AsyncAction2.<anonymous> (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:4863:24)
app-1  |     at AsyncAction2._execute (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1974:16)
app-1  |     at AsyncAction2.execute (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1963:26)
app-1  |     at AsyncScheduler2.flush (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:2235:30)
app-1  |     at listOnTimeout (node:internal/timers:594:17)
app-1  |     at process.processTimers (node:internal/timers:529:7) {
app-1  |   [cause]: undefined
app-1  | }
app-1 exited with code 0
```

### Puppeteer configuration file (if used)

```TypeScript
const { join } = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

23.10.1

### Node version

v22.12.0

### Package manager

npm

### Package manager version

10.9.2

### Operating system

macOS ARM on docker

**Comment by OrKoN** [comment]
I am not able to reproduce (I have not used Docker compose):

```
FROM node:22-bookworm
ENV PUPPETEER_SKIP_DOWNLOAD: true
RUN cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.save
RUN sed -e "s/main/main contrib/" /etc/apt/sources.list.d/debian.sources.save > /etc/apt/sources.list.d/debian.sources
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    xdg-utils \
    chromium \
    && rm /var/lib/apt/ -rf
RUN npm install npm -g
COPY --chown=1000:1000 ./package.json /application/package.json
COPY --chown=1000:1000 ./package-lock.json /application/package-lock.json
COPY --chown=1000:1000 ./puppeteer.config.cjs /application/puppeteer.config.cjs
USER node
WORKDIR /application
RUN npm install --production && chown -R node:node /application
COPY --chown=1000:1000 src/ /application/src/
CMD ["npm", "run", "start"]
```

and 

```
const puppeteer = require('puppeteer');

const start = async()=>{
  const browser = await puppeteer.launch({
    executablePath: '/usr/bin/chromium'
  });
  console.log("run!!")
  await browser.close();
};


start().then(console.log, console.error);
```
outputs `run!!` for me.

**Comment by OrKoN** [comment]
Note that I tried on an Intel Mac but if it fails specifically on MacOS ARM it sounds like a Docker/Debian issue as the could be a wrong binary being installed.

**Comment by Yzedank** [comment]
> ### Minimal, reproducible example
> src/index.js:
> 
> ```js
> const puppeteer = require('puppeteer');
> 
> const start = async()=>{
>     const browser = await puppeteer.launch({
>         headless: 'new',
>       });
>   console.log("run!!")
> };
> start().then(console.log, console.error);
> ```
> 
> Dockerfile:
> 
> ```dockerfile
> FROM node:22-bookworm
> RUN cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.save
> RUN sed -e "s/main/main contrib/" /etc/apt/sources.list.d/debian.sources.save > /etc/apt/sources.list.d/debian.sources
> RUN apt-get update
> RUN apt-get install -y --no-install-recommends \
>     xdg-utils \
>     chromium \
>     && rm /var/lib/apt/ -rf
> RUN npm install npm -g
> COPY --chown=1000:1000 ./package.json /application/package.json
> COPY --chown=1000:1000 ./package-lock.json /application/package-lock.json
> COPY --chown=1000:1000 ./puppeteer.config.cjs /application/puppeteer.config.cjs
> USER node
> WORKDIR /application
> RUN npm install --production && chown -R node:node /application
> COPY --chown=1000:1000 src/ /application/src/
> CMD ["npm", "run", "start"]
> ```
> 
> docker-compose.yml:
> 
> ```yaml
> services:
>   app:
>     build: .
>     environment:
>       PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
>       PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
> #    command: ["sleep","999999999"]
> ```
> 
> package.json:
> 
> ```json
> {
>   "name": "bug-puppeteer",
>   "version": "1.0.0",
>   "main": "src/index.js",
>   "scripts": {
>     "start": "node src/index.js"
>   },
>   "author": "",
>   "license": "ISC",
>   "description": "",
>   "dependencies": {
>     "puppeteer": "^23.10.1"
>   }
> }
> ```
> 
> ### Background
> I am on a Mac Arm M2 running Docker
> 
> to fix temporarily, I force the chromium version in the docker file:
> 
> ```
>     chromium-common=130.0.6723.91-1~deb12u1 \
>     chromium=130.0.6723.91-1~deb12u1 \
> ```
> 
> ### Expectation
> not crash
> 
> ### Reality
> ```
> app-1  | 
> app-1  | > bug-puppeteer@1.0.0 start
> app-1  | > node src/index.js
> app-1  | 
> app-1  | TimeoutError: Timed out after waiting 30000ms
> app-1  |     at /application/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:258:19
> app-1  |     at /application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3986:35
> app-1  |     at OperatorSubscriber2._this._next (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1055:13)
> app-1  |     at Subscriber2.next (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:678:16)
> app-1  |     at AsyncAction2.<anonymous> (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:4863:24)
> app-1  |     at AsyncAction2._execute (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1974:16)
> app-1  |     at AsyncAction2.execute (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:1963:26)
> app-1  |     at AsyncScheduler2.flush (/application/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:2235:30)
> app-1  |     at listOnTimeout (node:internal/timers:594:17)
> app-1  |     at process.processTimers (node:internal/timers:529:7) {
> app-1  |   [cause]: undefined
> app-1  | }
> app-1 exited with code 0
> ```
> 
> ### Puppeteer configuration file (if used)
> ```ts
> const { join } = require('path');
> 
> /**
>  * @type {import("puppeteer").Configuration}
>  */
> module.exports = {
>   // Changes the cache location for Puppeteer.
>   cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
> };
> ```
> 
> ### Puppeteer version
> 23.10.1
> 
> ### Node version
> v22.12.0
> 
> ### Package manager
> npm
> 
> ### Package manager version
> 10.9.2
> 
> ### Operating system
> macOS ARM on docker

**Comment by Yzedank** [comment]
Vamos a provarle
