### ISSUE TITLE
How to scrape 100+ websites

### ISSUE THREAD

**Issue by EdmundMai** [puppeteer/puppeteer#1339]
I have code that loops through a bunch of websites and tries to scrape their emails.

```
return Promise.all(
        _(urls)
          .map(url =>
            findEmail(url)
              .then(email => {
                console.log("found new email!!!!!!!!!: ", email);
              })
              .catch(err => {
                console.log("findEmail error: ", err);
              })
          )
          .value()
      );

```

```

const puppeteer = require("puppeteer");

const findEmail = url =>
  new Promise(async (resolve, reject) => {
    try {
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      await page.goto(url);
      await page.waitForSelector('a[href^="mailto:"]');
      const email = await page.evaluate(
        () => document.querySelector('a[href^="mailto:"]').textContent
      );
      await browser.close();

      const cleansedEmail = email.split("?")[0];
      resolve(cleansedEmail);
    } catch (e) {
      reject(e);
    }
  });

module.exports = findEmail;
```

However, this causes a memory leak and it causes my computer to explode. Is there a more efficient way of doing this?

**Comment by ebidel** [comment]
Please ask "how to" questions like this on StackOverflow.

**Comment by EdmundMai** [comment]
This is a practical question that is only asked because of the lack of documentation on how to properly use this library for multiple requests.

**Comment by Garbee** [comment]
@EdmundMai That is a general programming problem with handling large bodies of tasks. Not something specific to puppeteer or its implementation. And the "proper" method here depends on a few factors and how much scalability is needed. Therefore, StackOverflow with a more specific set of requirements provided is the best choice to ask this kind of question.

You may even realize an existing question very similar already exists to explain how to handle the task you're trying to do. Try not to think in terms of "puppeteer" itself but instead look at the underlying technology being used (primarily Promises here) and look for existing questions on handling multiple tasks with those.
