### ISSUE TITLE
Puppeteer tests against Firefox Nightly are failing

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#13390]
According to @whimboo , the archive format has changed from .tar.bz2 to .tar.xz.

Example failure: https://github.com/puppeteer/puppeteer/actions/runs/12251886667/job/34178310393#step:8:46

This is a breaking change for Puppeteer and users of `@puppeteer/browsers`. The change will presumably roll out to other channels as well.  See https://blog.nightly.mozilla.org/2024/11/28/announcing-faster-lighter-firefox-downloads-for-linux-with-tar-xz-packaging/

If the previous format of archives cannot be provided alongside the new ones, the following needs to be done:

- [ ] based on the Firefox version (which one?), we would need to use a different archive name and download it.
- [ ] we would need to find a dependency that can extract xz archives in Node.

**Comment by whimboo** [comment]
See as well my comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1710599#c50. It should be Firefox 135.

**Comment by OrKoN** [comment]
@christian-bromann FYI (I suspect webdriverio might be affected)

**Comment by whimboo** [comment]
I filed a new bug for particular this regression: https://bugzilla.mozilla.org/show_bug.cgi?id=1936246
