### ISSUE TITLE
[Bug]: Appears when multiple operations are performed on a single page，Attempted to use detached Frame '87082BD0562C0C66598E2B7411FC61D9'.

### ISSUE THREAD

**Issue by xhc-code** [puppeteer/puppeteer#13397]
### Minimal, reproducible example

```TypeScript
This is a complex operation, which involves searching on bing.com.
```

### Background

I am currently on the page for receiving daily tasks, but when I click on different actions multiple times, the message 'Attempted to use detached frame' 87082BD0562C0C66598E2B7411FC61D9 'appears Error, because this is a frequent occurrence, not just for a certain step.

### Expectation

normal use

### Reality

Attempted to use detached Frame '87082BD0562C0C66598E2B7411FC61D9'.

### Puppeteer version

23.10.2

### Node version

v18.12.1

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by OrKoN** [comment]
Could you please provide a minimal reproducible example? it looks like your code retains and tries to act on frames that are detached.
