### ISSUE TITLE
How to get the inner text of elements from the return values of page.$$

### ISSUE THREAD

**Issue by divyamvn** [puppeteer/puppeteer#1341]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: 10.12.6 Mac OS
* URLs (if applicable): 

**What steps will reproduce the problem?**
I have a grid, with several rows and columns. My action creates a new entry into the grid and I would like to validate the same.
In order to do that, I am trying to use page.$$ and get all elements, loop through each and validate whether my required text is present and there by get the row info and eventually perform other actions.
(I would do this in a simpler way if xpath was available.)
```

<div class=“grid disable-selection search" style="width: 840px; height: 505px;">
   <div class="rows" style="bottom: 37px;"><div id="26" class="row  hover">
		<div class="cell cell0" style="width: 105px;">
			<div class="label  ">
				5f3c557
			</div>
		</div>
		<div class="cell cell1" style="width: 105px;">
			<div class="label  ">
				043c6c0-
			</div>
		</div>
		<div class="cell cell2" style="width: 130px;">
			<div class="label  ">
				5f3c557043c6c0
			</div>
		</div>
		<div class="cell cell3" style="width: 110px;">
			<div class="label  ">
				f3c43
			</div>
		</div>
	</div></div></div>
```
 I am getting all elements using the below. elements.length gives proper value of element count.
`const elements = await page.$$("div.grid div.rows div.row div.cell div.label");
`
However, I tried so many ways to get the properties of each element but could not succeed.

```
const data1 = await elements[i].getProperty('value');

const data2 = await elements[i].getProperty('innerText');

const data3 = await elements[i].getProperty('innerHTML');
```
Currently any of the properties are returning same info - the entire node info.
- Is the above, right way to get info of each node?
- Could you suggest what is the best way to get text?
- Also, how can I get the class name?

**What is the expected result?**
I was expecting the getProperty returns the property/attribute values of elements.

**What happens instead?**
Entire JSHandle node info is getting displayed when I console.log data1 or data2 or data3.

**Comment by JoelEinbinder** [comment]
`getProperty` resolves to a JSHandle (imagine if you wanted to get 'parentElement')
Does this work for you? I'll admit it is a bit verbose:
```js
const data1 = await (await elements[i].getProperty('value')).jsonValue();
```

**Comment by divyamvn** [comment]
I did try this as well. It says data1 is "undefined".

**Comment by divyamvn** [comment]
@JoelEinbinder thanks for your suggestion.
I could get it working, by using getProperty('innerHTML')).jsonValue() instead of 'value', as its a div element.

**Comment by antsfee** [comment]
innerHTML only get it'self tag  ?

**Comment by deuexpo** [comment]
ElementHandle instances can be passed as arguments to the page.evaluate:
```javascript
const options = await this.page.$$('li');

for (const option of options) {
    const label = await this.page.evaluate(el => el.innerText, option);
}
```

**Comment by thinkshank** [comment]
answer by @ukrexpo worked for me. Thanks.

**Comment by 1antares1** [comment]
Answer by @ukrexpo
More understandable, natural, more Front-End :)

**Comment by breakingtherabbit** [comment]
Thanks, @ukrexpo ! Works here! Helped me a lot!!

**Comment by NickVlasov** [comment]
you could also use the `$$eval` directly without additional calls to the `page.evaluate` for each item. 
It would be smth like this:
`const labels =  await this.page.$$eval('li', option => options.map(item => item.innerText));`
