### ISSUE TITLE
Set header for a specific request not whole page

### ISSUE THREAD

**Issue by bilal-the-dev** [puppeteer/puppeteer#13410]
With request interception trying to see cookie header, but it doesnt set it. Is this intended?

**Comment by OrKoN** [comment]
Please provide a minimal reproducible example. It's difficult to answer without seeing the code. Generally, the cookies can be set with request interception.

**Comment by bilal-the-dev** [comment]
Hi i am sorry. got busy. Let me share with you the code and whole logs.

**Comment by bilal-the-dev** [comment]
here's the code when it goes to the page and intercepts request.

```js
   if (!this.isLoggedIn)
      throw new Error("Have not logged in into dilution yet");

    const page = await this.browser.newPage();

    let shortInterestData;
    let news = [];

    await this.setDefaultHeaders(page);
    await this.setUserAgent(page);

    await page.setCacheEnabled(false);
    await page.setRequestInterception(true);

    page.on("request", (interceptedRequest) => {
      // console.log(interceptedRequest.url());

      if (
        interceptedRequest.url().endsWith("bundle.b5bf677a06e2a4077dde.js") ||
        interceptedRequest.url().endsWith("css.main.99943a6280f5c20dc93c.css")
      ) {
        const headers = interceptedRequest.headers();
        console.log("REQUEST HIT FOR JS/CSS");

        console.log(interceptedRequest.url());

        console.log(headers);

        headers["cookie"] = "";

        console.log(headers);

        interceptedRequest.continue({ headers });
      } else interceptedRequest.continue();
    });
    page.on("response", async (response) => {
      if (
        response.request().url().endsWith("bundle.b5bf677a06e2a4077dde.js") ||
        response.request().url().endsWith("css.main.99943a6280f5c20dc93c.css")
      ) {
        console.log("RESPONSE RECEIVED FOR CSS/JS");
        console.log(response.request().url());

        console.log(response.request().headers());
      }
      if (response.status() !== 200) return;

      // console.log(response.url());

      if (response.url().endsWith(`getShortInterest?ticker=${ticker}`))
        shortInterestData = await response.json().catch(console.error);
    });

    await page.goto(`${DILUTION_TRACKER_URL}/app/search/${ticker}`, {
      waitUntil: "networkidle0",
    });

    const data = await page.evaluate((rawFactors) => {
      /*eslint-disable */
      const rawFactorsContentArray = rawFactors.map((e) => {
        const text =
          document.querySelector(`svg#${e.selector} + span`)?.innerText ||
          "N/A";

        return { title: e.title, text };
      });

      const historicalText = document.querySelector(
        "#results-os-chart > p + p"
      )?.innerText;
      const cashPosText = document.querySelector(
        "#results-os-chart + p + p"
      )?.innerText;

      const newsButton = document.querySelector("#result-tab-news");

      newsButton?.click();

      return {
        rawFactorsContentArray,
        cashPosText,
        historicalText,
        newsButton,
      };
    }, rawFactors);

    if (data.newsButton) {
      const newsRes = await page.waitForResponse(
        (response) =>
          response.url() ===
            `${DULTUION_TRACKER_API_URL}/getOhlcvTimeSeriesWithNews?ticker=${ticker}` &&
          response.status() === 200
      );

      news = await newsRes.json().catch(console.error);
    }

    // await page.close();

    await page.reload();
    return { ...data, shortInterestData, news };
    ```
    
   [Here](https://codefile.io/f/BgBrxe9hDu) are the logs for respective request and response callback.
   
   The reason i am doing `page.reload()` at end is for me to look at response in devtools. Because as soon as page loads for first time and devtools is opened (configured via options) the first few requests are not captured.
  
<img width="794" alt="a" src="https://github.com/user-attachments/assets/853e48a0-cd2b-4cc3-998f-0212cc970e2e" />

In devtools, the cookies are being sent. But logs say otherwise (in request event, it correctly sets the cookie and in response event, it correctly shows the request cookies were empty string however going to devtools say otherwise)

**Comment by OrKoN** [comment]
So you are trying to remove the cookie header? Could you please make sure that copying the code into a index.js and running `node index.js` reproduces the issue? Here is a related issue in CDP https://g-issues.chromium.org/issues/40888739#comment12 does it sounds similar to your situation? i.e., the cookie is already set by the site and you cannot modify while it should work if the cookies are not set by the site. Perhaps you could adjust that example to reproduce your specific scenario.

**Comment by bilal-the-dev** [comment]
So i tested multiple ways. 

1- [With my old code](https://codefile.io/f/X54CGPsLZ6) it sets cookie when it goes to first page, then on second page it tried to modify the existing cookie on request but is unable to.
2- [With cdp session](https://codefile.io/f/G8Evo59i6H) same issue, on first requests of page when cookie isnt set by server, it sends our own cookie. But on subsequent requests specifically after `https://api.dilutiontracker.com/v1/getUserAttributes` the cookie isnt modified so is the case with `referrer` if we modify , it doesnt send that at all.

**Comment by OrKoN** [comment]
It seems to be the same issue as https://crbug.com/40888739#comment12 (related to cookie and potentially other browser set headers):

```
import puppeteer from "puppeteer";

import http from 'http';

const server = new http.Server((req, res) => {
  if (req.url.includes('favicon')) {
    res.writeHead(200);
    res.end();
    return;
  }
  console.log("Server-seen request data", req.url, req.headers);
  if (req.url?.includes('FIRST')) {
    res.writeHead(200, undefined, {
      'set-cookie': 'DefaultCookie=Cookie set from the page',
      'x-custom-header': 'first page',
    });
    res.end('done')
    return; 
  }
  res.writeHead(200);
  res.end('done')
});

server.listen(3000, () => {
  console.log(`Server listening on port 3000`)
});

const set_url = "http://localhost:3000?FIRST";
const get_url = "http://localhost:3000?SECOND";

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto(set_url, { waitUntil: "networkidle2" });

const secondPage = await browser.newPage();
await secondPage.setCacheEnabled(false);
await secondPage.setRequestInterception(true);

secondPage.on("request", (r) => {
  if (r.url().endsWith("favicon.ico")) {
    r.continue();
    return;
  }

  const headers = r.headers();
  console.log("Resetting cookie headers for " + r.url());
  console.log(headers);
  headers["cookie"] = "";
  headers['x-custom-header'] = '';
  r.continue({ headers });
});

await secondPage.goto(get_url);
```

it works for the x-custom-header and not for the cookie header. I suggest using the dedicated API to change cookies in the browser storage https://pptr.dev/guides/cookies instead of relying on the request interception until that issue is fixed in Chrome.

**Comment by bilal-the-dev** [comment]
I'll explain my use case and hopefully you have a better solution than i have.

So, the bot logs in via my account to the website and sets cookies such as "aws-waf" Its a stock related website. Users will be entering a word that will make the bot go to a page "url/{userEnteredWord}" so there can be multiple pages open at a time. (Multiple users enter the word at same time)

Now on the page, there's one main html file, one js , one css file protected by aws waf. When the page requests these file, it also sends the aws waf cookie which causes the server to return a challenge instead of actual file.

My first solution was to not send the aws cookie with those css/js request but that doesn't work. I tried using `setExtraHTTPHeaders` same issue. 

Then i tried using the browser cookie. On the page load, i was removing the aws waf cookie so it wont be sent on the file requests. Do note that, other api endpoints require this aws cookie and its set by subsequent requests on the same page so it was working fine no issue.

Issue comes with above method is when, say one user opened a page. Bot did it work, scraped half website meanwhile another user opened a page. In that case, bot removed the aws cookie from browser and the previous page that had loaded the half website required the aws cookie to process its remaining requests and now is stuck. This causes issues, i wanted isolation. A page/request dealing with only its own cookies not global browser.


Is there any solution?

**Comment by OrKoN** [comment]
I cannot give you an advice for your specific use case, but it sounds like you plan on mixing data from multiple users/runs in the same browser instance? generally, this does not sound like a good idea. I'd suggest to start a browser instance per user/query or at least a browser profile per user (https://pptr.dev/api/puppeteer.browser.createbrowsercontext/). I am not sure why the "aws waf" would cause the server to return a challenge but I recommend using the site in the way that is supported by the site.

**Comment by bilal-the-dev** [comment]
I realised that i can make a get request to the css/js file without any cookie and get the content in incognito mode.

So, my current solution is a cron job that fetches these files every 30 mins and saves in cache. On bot side, when the page loads, and request is made to get these files, instead of letting the page get response from server i use `request.respondWith` or something like that to respond with the files from cache. This works perfectly fine, since those files are static and it would be pretty rare that they update these files. Nonetheless, bot would get the updated one in 30 mins max.

Do you think is a better idea to do this?

I thought about making the bot avoid the challenge by aws waf at all. I used puppeteer shealth and extra but no use.

I saw that the page repeatedly sends some signals to the aws waf server, it's probably because of those the "aws waf cookie" isn't accepted by server since its "bot-like"

Do you know how to bypass this aws waf challenge?

**Comment by bilal-the-dev** [comment]
Also thought of per browser per user, or context per user. But my use case requires login, the bot cant be logging in the website on each user request right?

It would ban my ip real quick realising so many logins.


And no, i am not mixing multiple users input. Each user get their own scraping data but one user scraping data can affect other page (because the cookie is removed)


And aws waf cookie does affect it. See, the page sends signals to aws server repeatedly and set a cookie on each signal response. When i use my normal browser, it seems the signals are human like and the cookie it sets are fine.

But using automated browser, the signals set cookie which are bot-like hence giving the challenge.

And yeah i tested myself when it was giving the challenge. I removed the aws cookie and it sent original content instead of challenge.

**Comment by OrKoN** [comment]
Generally, scraping of websites you do not own and any sort of bot detection bypass is out of scope for Puppeteer.
