### ISSUE TITLE
[Bug]:  Using puppeteer the `Translate` option of chrome is grayed out. 

### ISSUE THREAD

**Issue by YanivLevi1980** [puppeteer/puppeteer#13414]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {

  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  // Set viewport width and height
  await page.setViewport({ width: 1280, height: 720 });

  const website_url = 'https://ria.ru/world/';
  await page.goto(website_url, { waitUntil: 'networkidle0' });

})();
```

### Background

Puppeteer is being used to launch Chrome as a browser, visiting websites through a proxy. No automation is being performed—Chrome is simply being used to browse pages manually. However, the "Translate..." option in the Chrome menu is grayed out, even when visiting pages with content in a foreign language (e.g., Russian).

![translate_grayed_out](https://github.com/user-attachments/assets/d7cd5e56-4159-4394-9344-741bcb4f165f)

### Expectation

The "Translate..." option in Chrome's menu should be available when visiting a page in a foreign language (e.g., Russian).

### Reality

The "Translate..." option is grayed out when running Chrome under Puppeteer, even when the page content is in a foreign language.

### Puppeteer version

23.10.4

### Node version

21.7.1

### Package manager

npm

### Package manager version

10.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Translate is enabled by default by Puppeteer https://github.com/puppeteer/puppeteer/pull/774 to avoid affecting automation runs. You can use ignoreDefaultArgs: true to enable it by passing different arguments. What is the use case for this?

**Comment by YanivLevi1980** [comment]
Thanks :) What you wrote to me works, however I don't want to ignore all the default args as it could cause other issues. 

  const browser = await puppeteer.launch({
	executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",  // Using Chrome, not chromium
        headless: false,
        ignoreDefaultArgs: true, 
  });
  
  Is there a way to enable the translate option while keeping all the other default args ? 
  
  Another issue which I noticed, is that when using a proxy server, the translate feature fails 
  
          args.args.push(
            ...[
                `--proxy-server=${gateway.IpAddress}:${gateway.Port}`,
                `--proxy-bypass-list=${BypassList.join(',')}`,
            ]
        );
        
![image](https://github.com/user-attachments/assets/3dbf4d0f-9d76-43dd-a7c2-5f83eed2ece2)


The use case of that, is to allow a user to login into acccounts via puppeteer (such as Facebook, VK) through a proxy, also adding an iframe on top, which will allow to user to perform certain actions while browsing these sites. 

Realizing puppeteer wasn't meant for this kind of usage, would be a great to find a solution for that :-)

**Comment by OrKoN** [comment]
You can do or update the default args in another way. I do not think we will introduce an additional way to change that.

```
import puppeteer from 'puppeteer';

await puppeteer.launch({
  headless: false,
  ignoreDefaultArgs: true,
  args: puppeteer.defaultArgs({
    headless: false
  }).map(arg => {
    if (arg.startsWith('--disable-features')) {
      return arg.replace('Translate,', '')
    }
    return arg;
  })
});
```

As for the proxy feature, consider opening an issue in the Chrome tracker if you rule out the issues on the proxy side. In general, Puppeteer and Chrome for Testing (that Puppeteer downloads by default) are meant for automated testing and are not meant to be used by the end users for browsing the web.

**Comment by YanivLevi1980** [comment]
Posting here the full solution in case anyone in the future would have the same issue.

import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
	headless: false, 
	ignoreDefaultArgs: true, 
	args: [
		...puppeteer.defaultArgs({ headless: false }).map(arg => {
			if (arg.startsWith('--disable-features')) {
				return arg.replace('Translate,', '');
			}
			return arg;
		}),
		
		'--proxy-server=YOUR_OWN_PROXY_HERE',
		'--proxy-bypass-list=translate.googleapis.com'  // Ensure translation API is bypassed by the proxy
	],
});

So to bypass the proxy issues I've added `translate.googleapis.com` to `proxy-bypass-list`
