### ISSUE TITLE
[Bug]: EBUSY resource busy every time

### ISSUE THREAD

**Issue by fillwithjoy1** [puppeteer/puppeteer#13428]
### Minimal, reproducible example

```TypeScript
console.log("Not a reproducible example, a computer configuration error");
```

### Background

I've messed up my cherry-picking on my project and I decided to nuke the entire thing and delete the local repo and re-install everything from scratch all over again from the github repo.

Turns out trying to utilise the chrome browser with puppeteer now is corrupted it seems and gives me this

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: EBUSY: resource busy or locked, unlink '\AppData\Local\Temp\puppeteer_dev_chrome_profile-gcAkWD\lockfile'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: '\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-gcAkWD\\lockfile'
}

### Expectation

To work

### Reality

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: EBUSY: resource busy or locked, unlink '\AppData\Local\Temp\puppeteer_dev_chrome_profile-gcAkWD\lockfile'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: '\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-gcAkWD\\lockfile'
}

### Puppeteer version

23.11.0

### Node version

20.17.0

### Package manager

npm

### Package manager version

10.8.2

### Operating system

Windows

**Comment by OrKoN** [comment]
The error indicates that the user profile directory is busy (probably by another running Chrome process). Make sure no other Chrome processes are running from this directory and provide a minimal reproducible example.

**Comment by fillwithjoy1** [comment]
> The error indicates that the user profile directory is busy (probably by another running Chrome process). Make sure no other Chrome processes are running from this directory and provide a minimal reproducible example.

I've restarted and there are no other chrome browser instances running

I can't give a minimal, reproducible example but I will try

const page = await this.browser.newPage();

            await page.goto("https://www.9now.com.au/badminton-olympic-games-paris-2024/episode-2", this.noTimeout);

            await page.waitForSelector('video', this.noTimeout);
            const drmStatus = await this.checkDRMStatus(page);
            log(drmStatus, "debug");

            // Reload page if download task didn't finish after 60 seconds
            this.autoRestart = setInterval(async () => {
                log("♻️ Reloading page", "info");
                await page.reload(this.noTimeout);
            }, 60000);

            // If the download task didn't finish after 5 minutes, skip
            this.autoSkip = setTimeout(async () => {
                log("🕒 Timed out, skipping", "info");
                await this.safelyWait(page);
                await page.close();
                // FIXME: reject();
                resolve([0, 0, 0, 0]);
            }, 290000);

This occurs almost everytime and I'm unsure what's happening

**Comment by fillwithjoy1** [comment]
[Error: EBUSY: resource busy or locked, unlink '\AppData\Local\Temp\puppeteer_dev_chrome_profile-TFlRss\first_party_sets.db'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-TFlRss\\first_party_sets.db'

**Comment by fillwithjoy1** [comment]
Okay so I'm unsure what's happening but here's what I'm doing

1. I'm running main.js
2. Puppeteer creates a new temporary Chrome Dev profile
3. While it's loading the video and listening to requests.url and finds the request url that it's fetching for it closes

Now I had page.close() but removing it has no effect.
Also this time node.js complained about lockfile being busy before it was unlinked.

errno: -4082,
code: 'EBUSY',
syscall: 'unlink',
path: 'C:\\Users\\admin\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-M1T1EG\\lockfile'

**Comment by OrKoN** [comment]
Is it the complete error message? is there a stack trace? perhaps try providing a custom userDataDir to see if that has an issue too?

**Comment by fillwithjoy1** [comment]
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: EBUSY: resource busy or locked, unlink 'C:\Users\joysi\AppData\Local\Temp\puppeteer_dev_chrome_profile-SdOHTX\lockfile'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\admin\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-SdOHTX\\lockfile'
}

**Comment by fillwithjoy1** [comment]
I could show you the entire repo setup if you need

**Comment by fillwithjoy1** [comment]
@OrKoN FOUND IT!

It turns out I might be doing something really wrong.
In essence, I was calling page.close() on a tab when it was finished and then after that I'd call another exit function which would call
`browser.disconnect();
browser.close()`

In that specific order, as I wanted to prevent chrome from throwing up page detached errors whenever I closed the browser. I'm pretty sure somewhere I need to add await, but I'm so unsure about what those two functions do and how I can safely close the browser without it crashing.

`browser = await puppeteer.launch({
            channel: 'chrome',
            headless: false,
            ignoreDefaultArgs: [
                '--disable-component-update'
            ]
        });`

**Comment by OrKoN** [comment]
Doing disconnect and then close is an issue, because disconnect terminates the CDP connection so that the close command cannot be sent to the browser leaving the browser running. Doing just `await browser.close()` should be sufficient if you want to close the browser.
