### ISSUE TITLE
[Bug]: Website not loading specifically for Linux: Headless mode

### ISSUE THREAD

**Issue by snehilshah** [puppeteer/puppeteer#13434]
### Minimal, reproducible example

```TypeScript
const stealth = StealthPlugin();
puppeteer.use(stealth);

const browser = await puppeteer.launch({
  headless: true,
  args: [
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--font-render-hinting=none",
    "--disable-gpu",
    "--no-first-run",
  ],
});

const page = await browser.newPage();

page.setDefaultNavigationTimeout(30 * 1000);
let res = await page.goto(config.pageUrl, { waitUntil: "networkidle0" });

let pageContent = await page.content();
fs.writeFileSync("output.html", pageContent);
```

### Background

Getting the page content some websites, does not include the dynamic content loaded by js/fonts/images only the inital doc is shown. This problem does not occur in windows headless or headfull mode, neither does this happen in linux headfull mode. After some debugging I have noticed that, the number of requests are less in headless mode. I have also used stealth mode plugin to bypass stealth detection.

### Expectation

Whole page content with dynamic js should be shown from `page.content`, in linux headless mode.

### Reality

`page.content` only gets the initial doc, in linux headless mode.

### Puppeteer version

"puppeteer": "^23.11.1",

### Node version

v22.12.0

### Package manager

npm

### Package manager version

10.9.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Please provide a complete executable example including a test site and without the use of third party packages. If the site errors or fails to load or blocks a particular visit, it can happen that dynamic content is not loaded and rendered, so might want to check the console messages on the page for errors and network requests for failed requests. It is also possible for sites to specifically detect and block headless browsers (avoiding any sort of detection is out of scope for Puppeteer).
