### ISSUE TITLE
[Bug]: Why are Chrome cookies lost after closing the browser and reopening?

### ISSUE THREAD

**Issue by YanivLevi1980** [puppeteer/puppeteer#13439]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
    const userDataDir = 'C:\\junk_dir\\zxc'; 

    const args = [
        ...puppeteer.defaultArgs({ headless: false }).map(arg => {
            if (arg.startsWith('--disable-features')) {
                return arg.replace('Translate,', '').replace(',Translate', '');
            }
            return arg;
        }),
        '--start-maximized',
        '--disable-sync',
        '--no-sandbox',
        '--ignore-certificate-errors'
    ].filter(arg => !['--enable-automation', '--disable-extensions'].includes(arg));

    const browser = await puppeteer.launch({
        args,
        acceptInsecureCerts: true,
        headless: false,
        ignoreHTTPSErrors: true,
        defaultViewport: null,
		ignoreDefaultArgs: true,																		   
        userDataDir: userDataDir,
        pipe: true
    });

    // Open a new page
    const page = await browser.newPage();

   // 

})();
```

### Background

I've been trying to use puppeteer as a browser, the following arguments ensures the Translate option of chrome is enabled. however when logging in to Facebook , closing the puppeteer and reopening the cookies are lost (or not used).

### Expectation

When logging to Facebook, closing Chrome, then reopening, the cookies should be saved. 

### Reality

Seems like cookies are lost (or not used) upon chrome reopening. 

### Puppeteer version

23.10.4

### Node version

21.7.1

### Package manager

npm

### Package manager version

10.5.1

### Operating system

Windows

**Comment by OrKoN** [comment]
How do you close the browser? If you close by sending a SIGINT it will kill the browser process which might not save the latest data depending on the implementation. Use `await browser.close()` (SIGTERM, SIGHUP signals should also trigger that) to close the browser gracefully or close via the browser UI. In general, it sounds like an issue to be filed for Chrome if the cookies are lost on graceful shutdown.

**Comment by YanivLevi1980** [comment]
I found out what the issue is, when using **ignoreDefaultArgs: true**  the **userDataDir** is not being added to browser.process().spawnargs though it should. 

As a workaround I will add it manually 


```
    const args = [
        ...puppeteer.defaultArgs({ headless: false }).map(arg => {
            if (arg.startsWith('--disable-features')) {
                return arg.replace('Translate,', '').replace(',Translate', '');
            }
            return arg;
        }),
        '--start-maximized',
        '--disable-sync',
        '--no-sandbox',
        '--ignore-certificate-errors',
	**"--user-data-dir=C:\\junk_dir\\zxc"**
    ].filter(arg => !['--enable-automation', '--disable-extensions'].includes(arg));
```
    
    Would be happy if this would be fixed in the next version of puppeteer.
