### ISSUE TITLE
[Bug]: `window` is not defined when exposing functions using `page.exposeFunction`

### ISSUE THREAD

**Issue by jacksonkasi1** [puppeteer/puppeteer#13437]
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

// Helper function simulation
const get_document_info = () => {
  return {
    title: document.title,
    url: window.location.href
  };
};

const collect_page_data = () => {
  return get_document_info();
};

(async () => {
  const browser = await puppeteer.launch({
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  const page = await browser.newPage();
  
  await page.goto('http://example.com', { waitUntil: "networkidle2" });

  // Expose helper functions
  await page.exposeFunction("getDocumentInfo", get_document_info);
  await page.exposeFunction("collectPageData", collect_page_data);

  // Set up nodeUtils object
  await page.evaluate(() => {
    window.nodeUtils = {
      getDocumentInfo: (args) => window.getDocumentInfo(args),
      collectPageData: () => window.collectPageData(),
    };
  });

  // Execute the data collection
  const result = await page.evaluate(async () => {
    try {
      return await window.nodeUtils.collectPageData();
    } catch (error) {
      console.error("Error:", error);
      throw error;
    }
  });

  await browser.close();
})();
```

### Background

I'm working on a web scraping project where I need to expose several helper functions to the browser context using Puppeteer's `exposeFunction`. These functions are meant to collect various pieces of information from the webpage. However, when trying to execute these functions, I'm encountering a "window is not defined" error, despite the functions being properly exposed to the page context.

### Expectation

I expect the exposed functions to be able to access the browser's `window` object and execute properly in the page context when called through `window.nodeUtils`.

### Reality

The code throws an error: "Error: window is not defined" when attempting to execute the exposed functions. This occurs even though the functions are successfully exposed and attached to `window.nodeUtils` (verified by logging available functions).

### Puppeteer version

^23.11.1

### Node version

v22.11.0

### Package manager

pnpm

### Package manager version

9.14.2

### Operating system

Linux

**Comment by jacksonkasi1** [comment]
Check out this repository: [[WebSketch - Server](https://github.com/jacksonkasi0/WebSketch/tree/main/apps/server)](https://github.com/jacksonkasi0/WebSketch/tree/main/apps/server)

To reproduce the same issue I faced, just install the dependencies and make a call:

1. Clone the repository.  
2. Install dependencies:  
   ```bash
   bun install
   ./setup.sh
   ```
3. Run the application 
```
bun start
```

**Comment by OrKoN** [comment]
exposeFunction exposes your Node (or bun) function and binds it a function call on your page. Correspondingly, the function run your Node (or bun) context which does not have the window object. This is useful you want to call a function from the page to read a file using Node APIs, for example. If all your functions run in the page context, you can just evaluate them there. I think this is working as expected. 

Related docs: https://pptr.dev/api/puppeteer.page.exposefunction/
