### ISSUE TITLE
[Bug]: PDF Reverse Words Copy

### ISSUE THREAD

**Issue by TomFreudenberg** [puppeteer/puppeteer#13442]
### Minimal, reproducible example

```TypeScript
// define the options per output
let pdf_publish_options = {}
// for pdf
pdf_publish_options = {
  path: outputFile,
  format: 'A4',
  landscape: false,
  preferCSSPageSize: true,
  ignoreInvalidPageRanges: true,
  printBackground: true,
  displayHeaderFooter: false
}

// standard log info: script.js:path/input.html|path.output.ext|a4|landscape
console.log(path.basename(args[1]) + ' (' + outputType + '):' + inputFile + '|' + outputFile);

// prepare launch args
puppeteer_args = ['--disable-web-security']
// check special config when running as root
if (process.getuid() == 0) {
  puppeteer_args.push('--no-sandbox')
}
// convert html into pdf
const browser = await Puppeteer.launch({ headless: 'new', args: puppeteer_args }).catch(e => console.error(e));
const page = await browser.newPage().catch(e => console.error(e));

page.on('console', msg => {
  for (let i = 0; i < msg.args().length; ++i)
    console.error(`${i}: ${msg.args()[i]}`);
});

// use the content received by eleventy
await page.setContent(elevResult[0].content, { waitUntil: 'networkidle2' });
// save as pdf
await page.pdf(pdf_publish_options).catch(e => console.error(e));

// stop the headless session
await browser.close().catch(e => console.error(e));

})(); // directly call the async block
```

### Background

I use puppeteer to render html content into PDF.

### Expectation

To get a PDF where I can copy the content from to clipboard.

### Reality

The Content is in "Reverse Order" when copied and the marker is (half) on the lower half of the text.

<img width="329" alt="image" src="https://github.com/user-attachments/assets/dc12b47a-bf2d-4526-a57f-36838d29002c" />

<br>

<br>

**The copied text is:**

<img width="136" alt="image" src="https://github.com/user-attachments/assets/994e7ca4-b999-4a42-886f-3aeb8b673cd5" />

---

If I use puppeteer release v23.0.0 up to v23.7.1 everything works as expected.

I use custom fonts (Noto Sans) but I embedd the ttf fonts data into the CSS like:

```
@font-face {
  /* latin */
  font-family: 'Noto Sans';
  font-style: normal;
  font-weight: 400;
  font-stretch: 0% 200%;
  font-display: swap;
  src: url(data:application/x-font-woff2;charset=utf-8;base64,AAEAA ....);
}
```

I tested all releases up to release v23.11.1 but non newer than v23.7.1 does work.

It does not work on MacOs either.

### Puppeteer version

23.8.0

### Node version

20.11.0

### Package manager

pnpm

### Package manager version

9.15.1

### Operating system

Linux

**Comment by TomFreudenberg** [comment]
looks like [#2206](https://github.com/puppeteer/puppeteer/issues/2206)

**Comment by OrKoN** [comment]
Does it happen if you print using the built-in print dialog? Please include the test page that reproduces the issue including the font files (I think it should happen with any way you print using Puppeteer) into the report and file an issue to https://crbug.com/new as Puppeteer only saves the PDF produced by the browser for your. Issue https://github.com/puppeteer/puppeteer/issues/2206 indicates that this could be an issue with web fonts so perhaps using a different (newer) font file could fix it?

**Comment by TomFreudenberg** [comment]
Hi Alex @OrKoN 

you find a testing repository at:
https://github.com/TomFreudenberg/puppeteer-test

I added a readme and described the tests.
The test HTML and PDF results are already included in the repository.

PDF for "copy" failed on:
1. puppeteer(v23.11.1)/chrome/linux-131.0.6778.69/chrome-linux64
2. puppeteer(v23.8.0)/chrome/linux-131.0.6778.204/chrome-linux64

PDF for "copy" works on:
1. puppeteer(v23.7.1)/chrome/linux-130.0.6723.116/chrome-linux64
2. puppeteer(v23.11.1 OSX)/chrome/mac_arm-131.0.6778.204

Maybe it is not a puppeteer but a chromium-headless problem?

Hopefully the information will help you to indicated the issue.

If I can help in any way, please let me know.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Hi Alex @OrKoN 

to day I tested to use npm release v23.11.1 from puppeteer but changed the linked chromium release to chrome/linux-130.0.6723.116

This works as well, so the issue is "back" with chromium chrome/linux-131.0.6778.???

Cheers
Tom

**Comment by TomFreudenberg** [comment]
I debugged a little bit deeper by using

```
npx @puppeteer/browsers install chrome@131.0.6765.0
```

and

```
npx @puppeteer/browsers install chrome@131.0.6766.0
```

and between this two chrome release the issue occurs.

That's the diff: https://chromium.googlesource.com/chromium/src/+log/131.0.6765.0..131.0.6766.0/?n=10000

You also see a big increase of the resulting PDF size. While the "working" ones are around ~55KB the later and not workings are about ~115KB.

---

Should I profile this issue now on chromium site?

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Hi @mathiasbynens

After reading https://developer.chrome.com/blog/chrome-for-testing maybe you may jump in and guide for the correct follow up?

Thx
Tom

**Comment by TomFreudenberg** [comment]
I opened an issue at: https://issues.chromium.org/issues/386463464
