### ISSUE TITLE
waitFor property change feature request

### ISSUE THREAD

**Issue by pragmaproducts** [puppeteer/puppeteer#1344]
There are a number of scenarios where it is super useful to wait for a property on a element to change. I am looking at this mostly from a testing perspective and being able to do something like.

async propertyHandle.waitForChange();

You can then wait for the class to change to make sure that the desired ui effect is being added.
You can check attribute values to check aria attributes being applied properly.
You can wait for values to change to ensure that expected bindings worked as expected.

I am sure you can currently do it with custom events but the experience is horrid.
A nice clean shorthand would suuuuuper nice, simplifying the code and keeping easier to understand and maintain.

**Comment by JoelEinbinder** [comment]
How about:

```js
await page.waitFor(element => element.getAttribute('aria-label') === 'correct-value', {}, elementHandle);
``` 

Waiting for just any change seems a bit scary. What if your attribute changes twice?

**Comment by pragmaproducts** [comment]
That is certainly a nice example, as reference what I would love to avoid is something like this.

https://github.com/GoogleChrome/puppeteer/issues/1333

For what we do this is a common scenario and as can be seen in the above link can be simplified alot.

To be clear, all i am asking for / begging for is a simplification of the api for waiting on changes to take place, be it styles, attributes or input values.

**Comment by JoelEinbinder** [comment]
I am not sure I understand. Internally, we just use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to listen for all changes. You can combine that with `page.exposeFunction` to receive a callback every time something changes in the DOM. That's what `page.waitFor` does, and then it resolves when the callback function returns true.

**Comment by pragmaproducts** [comment]
If you are only concerned about attributes, then yes, mutation is fine.
Some binding engines do not work on the attributes though, but the properties directly. Aurelia being a example of that.

Having said that, I am not saying that you can't do these things using other mechanisms.
What I am asking for is a less verbose / simplified api as I have demonstrated on the initial post.

Request, simplified api

**Comment by kidwm** [comment]
BTW, is it possible to add waitFor under ElementHandle?

**Comment by aslushnikov** [comment]
@pragmaproducts if i understand correctly, you'd like to have a hook for the javascript property changes.

You can achieve this by using es6 proxies, something along the lines:

```js
async page.exposeFunction('fooChanged', () => console.log('a.foo changed!'));
async page.evaluate(() => {
  // Assume there's "a" with a "foo" property we'd like to track
  const oldFoo = a.foo;
  a.foo = new Proxy(oldFoo, {
    set: function(target, property, value, receiver) {
      target[prop] = value;
      fooChanged();
    }
  });
});
```

I'm not convinced this should be a part of the puppeteer unless there's a bigger demand for the functionality. 

Hope this helps!

**Comment by pragmaproducts** [comment]
You did not understand it correctly but that is ok, i will make my own shorthand for this

**Comment by NagarjunPrasad1** [comment]
@pragmaproducts Did you find a good way to monitor the property changes?
