### ISSUE TITLE
[Bug]: Page goto doesn't work with headless firefox

### ISSUE THREAD

**Issue by Zapeth** [puppeteer/puppeteer#13441]
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer-core'

const browser = await puppeteer.connect({
  browserWSEndpoint: 'ws://127.0.0.1:9222/session',
  protocol: 'webDriverBiDi'
});
const context = browser.defaultBrowserContext()
const page = await context.newPage()
const url = 'https://github.com'

console.debug('navigating to ' + url)
let res = await page.goto(url)
console.debug('page goto returned:', res)

await page.close()
await browser.disconnect()
```

### Background

I want to do some automated testing with puppeteer using an external headless firefox instance (133.0.3), for that I'm trying to get a basic example working.

### Expectation

I expected the page content to be printed to stdout (or at least a connection error if the page failed to load)

### Reality

The page is not loaded and an error from puppeteer is printed to stdout:
```
navigating to https://github.com
file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:97
    #error = new ProtocolError();
             ^

ProtocolError: Protocol error (browsingContext.navigate): unknown error Error: NS_ERROR_FAILURE #checkLoadingState@chrome://remote/content/shared/Navigate.sys.mjs:327:28
onStateChange@chrome://remote/content/shared/Navigate.sys.mjs:422:28
 at https://github.com
    at <instance_members_initializer> (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:97:14)
    at new Callback (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:101:16)
    at CallbackRegistry.create (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:20:26)
    at BidiConnection.send (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Connection.js:51:32)
    at Session.send (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/Session.js:134:42)
    at Session.<anonymous> (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:101:27)
    at BrowsingContext.navigate (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/BrowsingContext.js:313:33)
    at BrowsingContext.<anonymous> (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:101:27)
    at BidiFrame.goto (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Frame.js:336:22)
    at BidiFrame.<anonymous> (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:101:27)

Node.js v20.16.0
```
In the console output of the firefox session a bunch these messages are printed when the test script is executed:
```
NetworkHelper.parseSecurityInfo threw an exception: Security state 0 has no known STATE_IS_* flags.
console.error: "Security state 0 has no known STATE_IS_* flags."
```

Also, if I try to rerun the script with the same browser instance I get this puppeteer error and have to restart firefox (probably because the websocket connection isn't properly closed?):
```
file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:97
    #error = new ProtocolError();
             ^

ProtocolError: Protocol error (session.new): session not created Maximum number of active sessions RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
SessionNotCreatedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:709:5
createSession@chrome://remote/content/webdriver-bidi/WebDriverBiDi.sys.mjs:121:13
onPacket@chrome://remote/content/webdriver-bidi/WebDriverBiDiConnection.sys.mjs:198:55
onMessage@chrome://remote/content/server/WebSocketTransport.sys.mjs:127:18
handleEvent@chrome://remote/content/server/WebSocketTransport.sys.mjs:109:14

    at <instance_members_initializer> (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:97:14)
    at new Callback (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:101:16)
    at CallbackRegistry.create (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:20:26)
    at BidiConnection.send (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Connection.js:51:32)
    at Session.from (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/Session.js:70:49)
    at BidiBrowser.create (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Browser.js:87:43)
    at _connectToBiDiBrowser (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/BrowserConnector.js:21:48)
    at async _connectToBrowser (file:///home/anon/scraper/node_modules/puppeteer-core/lib/esm/puppeteer/common/BrowserConnector.js:26:29)
    at async file:///home/anon/scraper/test.mjs:10:17

Node.js v20.16.0
```

### Puppeteer version

23.11.1

### Node version

20.16.0

### Package manager

npm

### Package manager version

10.8.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Firefox only supports a WebDriver BiDi single session that persists after the WebSocket connection is closed meaning that Firefox needs to be restarted. Also, it is recommended to launch Firefox with Puppeteer as it might require additional preferences for the automation protocol.

**Comment by Zapeth** [comment]
> I believe this is the same issue as #12929 which we should be able to fix with Firefox 134. cc @whimboo @juliandescottes

I saw that issue too but wasn't sure, because the error is slightly different (NS_ERROR_FAILURE instead of NS_BINDING_ABORTED).

Also, from reading the posts I got the impression that it only happens with specific sites (ie https://x.com), but I tried other sites and still got the same error (eg https://codeberg.org or https://info.cern.ch)

**Comment by OrKoN** [comment]
So I tried and with launching via Puppeteer it works:

```
import puppeteer from 'puppeteer'

const browser = await puppeteer.launch({
  browser: 'firefox',
  protocol: 'webDriverBiDi'
});
const context = browser.defaultBrowserContext()
const page = await context.newPage()
const url = 'https://github.com'

console.debug('navigating to ' + url)
let res = await page.goto(url)
console.debug('page goto returned:', res)

await page.close()
await browser.close()
```

I think perhaps the following properties are missing in the profile you launch Firefox with: https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/node/FirefoxLauncher.ts#L36

**Comment by OrKoN** [comment]
I am actually not able to reproduce the issue with the connect() either:

```
.cache/puppeteer/firefox/mac-stable_133.0.3/Firefox.app/Contents/MacOS/firefox --profile tmp --remote-debugging-port=9222
```

```
import puppeteer from 'puppeteer-core'

const browser = await puppeteer.connect({
  browserWSEndpoint: 'ws://127.0.0.1:9222/session',
  protocol: 'webDriverBiDi'
});
const context = browser.defaultBrowserContext()
const page = await context.newPage()
const url = 'https://github.com'

console.debug('navigating to ' + url)
let res = await page.goto(url)
console.debug('page goto returned:', res)

await page.close()
await browser.disconnect()
```

Although I tried on a Mac for now, so it might Linux-specific issue.

**Comment by Zapeth** [comment]
Thanks for checking, `fission.webContentIsolationStrategy` was already set, but I didn't know about `remote.active-protocols`, unfortunately setting it didn't make a difference.

I also tried the bundled firefox version from `puppeteer` and this one seems to work, though I only get a `page goto returned: BidiHTTPResponse {}` output and the methods from https://pptr.dev/api/puppeteer.httpresponse/ dont seem to work (I get an `UnsupportedOperation` error if I use `res.content()` or `res.text()`)

Regarding the issue with my headless firefox instance, maybe there are some build options that are missing or need to be set differently? I'm using Void Linux, which uses this template to build its package -> https://github.com/void-linux/void-packages/blob/master/srcpkgs/firefox/template

**Comment by OrKoN** [comment]
Retrieval of response bodies is not yet supported with Firefox because the WebDriver BiDi protocol does not define this feature yet.

**Comment by OrKoN** [comment]
Here is the list of features that are not supported yet https://pptr.dev/webdriver-bidi#puppeteer-features-not-supported-over-webdriver-bidi (note that it mentions the buffer() getter but it is the same for text()/context()).

**Comment by OrKoN** [comment]
> Regarding the issue with my headless firefox instance, maybe there are some build options that are missing or need to be set differently? I'm using Void Linux, which uses this template to build its package -> https://github.com/void-linux/void-packages/blob/master/srcpkgs/firefox/template


@whimboo do you know why there could be a difference between Firefox we bundle with Puppeteer and the Void Linux build?

**Comment by Zapeth** [comment]
> Here is the list of features that are not supported yet https://pptr.dev/webdriver-bidi#puppeteer-features-not-supported-over-webdriver-bidi (note that it mentions the buffer() getter but it is the same for text()/context()).

Thanks for the link, so if retrieval of response bodies has yet to be defined in the protocol I assume an actual implementation won't be available in the near future?

Also I realized that I always only tested with my existing firefox profile and never with a new one, if I do that the script also works with my local installation.

Maybe the issue is caused by an extension or some some settings from that profile, either way I'll just use a separate profile from now on, thanks again for the help.

**Comment by whimboo** [comment]
@Zapeth if you want to figure out the issue you could create a copy of the Firefox profile and strip it down by removing files or preferences from `prefs.js` (make sure to disconnect from Firefox Accounts first in case you have it enabled). Also you can set the `remote.log.level` preference to `Trace` to get more detailed log output from Firefox. 

It would be good to know what exactly caused this issue but I can understand if you do not have the time to check that. So good to know that a fresh profile works here.
