### ISSUE TITLE
[Bug]: Firebase Cloud Functions V2 with Puppeteer Extra (3.3.6)

### ISSUE THREAD

**Issue by itismejy** [puppeteer/puppeteer#13443]
### Minimal, reproducible example

```TypeScript
any fixes? I got the browser to launch with Puppeteer 18.2.1 and Puppeteer 3.3.6 installed, but stuck with going to new page.

const puppeteer = require("puppeteer-extra");
const AdblockerPlugin = require("puppeteer-extra-plugin-adblocker");
const AnonymizeUA = require("puppeteer-extra-plugin-anonymize-ua");
const BlockResources = require("puppeteer-extra-plugin-block-resources");
const StealthPlugin = require("puppeteer-extra-plugin-stealth");
puppeteer.use(AdblockerPlugin());
puppeteer.use(AnonymizeUA());
puppeteer.use(BlockResources({blockedTypes: new Set(["image", "stylesheet", "font"])}));
puppeteer.use(StealthPlugin());
const browser = await puppeteer.launch({
headless: true,
timeout: 0,
args: [
"--no-sandbox",
"--disable-setuid-sandbox",
],
});
console.log("Browser launched");
console.time("Open Browser");
const page = await browser.newPage(); // crashes here

Im getting this error after the browser launches, when going to page.

Error: Missing target for page (id = 559EF2CA442048B0D1B5B08B215F0B65)
at CDPBrowser._createPageInContext (/workspace/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:277:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async CDPBrowser._createPageInContext (/workspace/node_modules/puppeteer-extra/dist/index.cjs.js:210:30)
```

### Background

Firebase cloud functions, this is my package.json:
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "gcp-build": "node node_modules/puppeteer/install.mjs"
  },
  "engines": {
    "node": "20"
  },
  "main": "index.js",
  "dependencies": {
    "@google-cloud/tasks": "^5.5.1",
    "axios": "^1.7.7",
    "cheerio": "^1.0.0",
    "cors": "^2.8.5",
    "domutils": "^3.2.1",
    "firebase-admin": "^12.7.0",
    "firebase-functions": "^6.2.0",
    "get-urls": "^12.1.0",
    "htmlparser2": "^10.0.0",
    "jsdom": "^25.0.1",
    "luxon": "^3.5.0",
    "node-fetch": "^3.3.2",
    "puppeteer": "^18.2.1",
    "puppeteer-extra": "^3.3.6",
    "puppeteer-extra-plugin-adblocker": "^2.13.6",
    "puppeteer-extra-plugin-anonymize-ua": "^2.4.6",
    "puppeteer-extra-plugin-block-resources": "^2.4.3",
    "puppeteer-extra-plugin-stealth": "^2.11.2",
    "uuid": "^11.0.3"
  },
  "devDependencies": {
    "eslint": "^8.15.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}

### Expectation

Expecting to open the browser and get the page

Error: Missing target for page (id = 559EF2CA442048B0D1B5B08B215F0B65)
at CDPBrowser._createPageInContext (/workspace/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:277:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async CDPBrowser._createPageInContext (/workspace/node_modules/puppeteer-extra/dist/index.cjs.js:210:30)

### Reality

It crashes and gives me this error

### Puppeteer configuration file (if used)

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, 'node_modules', '.puppeteer_cache'),
};
```

### Puppeteer version

18.2.1

### Node version

23.3.0

### Package manager

npm

### Package manager version

10.9.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Version 18.2.1 is outdated and not supported. Please try using the latest version and without using third-party packages like puppeteer-extra. If there is an issue specific to puppeteer-extra, please report it to their repository. Also, please make sure that the Firebase environment has all required system dependencies (https://pptr.dev/guides/system-requirements).
