### ISSUE TITLE
pleas change request.resourceType ==='Document' instead document

### ISSUE THREAD

**Issue by pvtulsiram538** [puppeteer/puppeteer#1348]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by ebidel** [comment]
Lowercase was intentional to be consistent throughout the API. See https://github.com/GoogleChrome/puppeteer/commit/c3fb3671480af81b24cb9902e5e8912764e493d1
