### ISSUE TITLE
The default ChromiumDownloadURL has to be rewritable

### ISSUE THREAD

**Issue by deisser** [puppeteer/puppeteer#1349]
Conditioned by our comapny security policies and proxy we have no way of downloading the chromium files through the provided static 'https://storage.googleapis.com' host URL. We can only proxy the binary download through our artifactory repository manager. To accomplish this we need the default URL to be rewritable.

**Comment by Saturate** [comment]
You can already do this in the newest version, see https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables and `PUPPETEER_DOWNLOAD_HOST`.

**Comment by deisser** [comment]
Thank you I missed it:)
