### ISSUE TITLE
setCookie() doesn't work?

### ISSUE THREAD

**Issue by alixaxel** [puppeteer/puppeteer#1350]
Somehow, I'm not able to retrieve cookies previously set with `page.setCookie()`.

Also, is the `CROSS_PROCESS_PREFIX` argument intended [here](https://github.com/GoogleChrome/puppeteer/blob/9c1935b651bfdf78f5ac835496d38a5a797c30c3/test/test.js#L2955)?

**Environment:**

* Puppeteer version: 0.13.0-alpha
* Platform / OS version: Ubuntu 17.04

**What steps will reproduce the problem?**

`npm run unit -- --filter="should manually set and get cookies"`

```javascript
it('should manually set and get cookies', SX(async function(){
  const cookies = [
    {
      name: 'k1',
      value: 'v1',
      domain: 'httpbin.org',
      path: '/',
      expires: 0,
      size: 4,
      httpOnly: false,
      secure: false,
      session: true,
    },
    {
      name: 'k2',
      value: 'v2',
      domain: 'httpbin.org',
      path: '/',
      expires: 0,
      size: 4,
      httpOnly: false,
      secure: false,
      session: true,
    },
  ];
  await page.setCookie(...cookies);
  await page.goto('https://httpbin.org/cookies');
  expect(await page.cookies()).toEqual(cookies);
}));
```

**What is the expected result?**

Test should pass.

**What happens instead?**

Test fails.

```
Testing on Node v8.2.1
Started
F

Failures:
1) Page Cookies should manually set and get cookies
  Message:
    Expected $.length = 0 to equal 2.
    Expected $[0] = undefined to equal Object({ name: 'k1', value: 'v1', domain: 'httpbin.org', path: '/', expires: 0, size: 4, httpOnly: false, secure: false, session: true }).
    Expected $[1] = undefined to equal Object({ name: 'k2', value: 'v2', domain: 'httpbin.org', path: '/', expires: 0, size: 4, httpOnly: false, secure: false, session: true }).
  Stack:
    Error: Expected $.length = 0 to equal 2.
    Expected $[0] = undefined to equal Object({ name: 'k1', value: 'v1', domain: 'httpbin.org', path: '/', expires: 0, size: 4, httpOnly: false, secure: false, session: true }).
    Expected $[1] = undefined to equal Object({ name: 'k2', value: 'v2', domain: 'httpbin.org', path: '/', expires: 0, size: 4, httpOnly: false, secure: false, session: true }).
        at /home/alix/Work/puppeteer/test/test.js:3033:36
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

Ran 1 of 293 specs
1 spec, 1 failure
Finished in 0.738 seconds
```

**Comment by JoelEinbinder** [comment]
Can you try not specifying `expires: 0`? It looks like the cookies are expiring immediately when you reload the page.

**Comment by alixaxel** [comment]
@JoelEinbinder

If I set `expires` to a timestamp sometime in the future *and* I set `session` to `false`, then it works.

I find this behavior a bit strange though, since with [`nickjs`](https://github.com/phantombuster/nickjs) that relies on `chrome-remote-interface`, the same test yield the behavior I was expecting without needing to modify the values of `expire` and `session`. Could this be related to https://github.com/GoogleChrome/puppeteer/issues/1342?

**Comment by justincy** [comment]
I had the same problem. I was able to keep `session` set to true and just not set the `expires` value.

@JoelEinbinder What threw me off was that `cookies()` was returning an object that had `expires` set to 0 and `session` true so I assumed I needed to pass those same values back to `setCookie()`. In fact I was hoping to just save the entire cookie object and send it back without having to modify it.

**Comment by ginuim** [comment]
I create a new incognito browser context. This won't share cookies/cache with other browser contexts, and it works
```
const browser = await puppeteer.launch();
// Create a new incognito browser context.
const context = await browser.createIncognitoBrowserContext();
// Create a new page in a pristine context.
const page = await context.newPage();
// Do stuff
await page.setCookie(cookie1, cookie2);
await page.goto('https://example.com');
```
