### ISSUE TITLE
Demo "Try Puppeteer" doesn't work

### ISSUE THREAD

**Issue by ximet** [puppeteer/puppeteer#1351]
Step to reproduce:

1) Start https://try-puppeteer.appspot.com
2) Click to button "Run It"

Result: LOG "Error running your code. Error: Page crashed!"

Also I change some code, for example change line await page.goto('https://example.com'); to google.com, and also doesn't work

**Comment by ebidel** [comment]
This issue was moved to ebidel/try-puppeteer#11
