### ISSUE TITLE
Feature request: show console output

### ISSUE THREAD

**Issue by trevordmiller** [puppeteer/puppeteer#1352]
Currently, when puppeteer hits an error, I can't see any console errors in the terminal. I can open set `headless` to false and check the developer tools locally, but in CI running headless I can't see what went wrong. It would be great if console output - especially `console.error`s were piped to stdout. So that you see in headless mode the same output you would see opening the console in devtools in non-headless mode.

**Comment by vsemozhetbyt** [comment]
Does [`console`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-console) event handler suffice?

**Comment by ebidel** [comment]
Yes, the `console` event is the way to go. There's also mention of this in the debugging tips: https://github.com/GoogleChrome/puppeteer#debugging-tips

**Comment by trevordmiller** [comment]
Oh ok thank you, sorry I missed that!

**Comment by pixelprodev** [comment]
came across this thread when searching for something similar.  I noticed in the `puppeteer.launch` options you can specify `dumpio: true` to pipe browser errors and logs to stdout/stderror just like you were searching for.  This way you don't have to worry about missing something you didn't account for in a console handler.

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions

**Comment by stevenvachon** [comment]
I didn't like the appearance of `dumpio`'s output. Instead, I much prefer the result of:
```js
page.on('console', async msg => console[msg._type](
  ...await Promise.all(msg.args().map(arg => arg.jsonValue()))
));
```
