### ISSUE TITLE
[v0.9.0+] Incorrect elementHandle/frame/page.$(selector) return signature in api.md

### ISSUE THREAD

**Issue by seantanly** [puppeteer/puppeteer#1358]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v0.9.0+
* Platform / OS version: -
* URLs (if applicable): 

https://github.com/GoogleChrome/puppeteer/blob/v0.9.0/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/v0.9.0/docs/api.md#frameselector

https://github.com/GoogleChrome/puppeteer/blob/v0.10.0/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/v0.10.0/docs/api.md#frameselector

https://github.com/GoogleChrome/puppeteer/blob/v0.10.1/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/v0.10.1/docs/api.md#frameselector

https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#frameselector

https://github.com/GoogleChrome/puppeteer/blob/v0.11.0/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/v0.11.0/docs/api.md#frameselector

https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/v0.12.0/docs/api.md#frameselector

https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/docs/api.md#frameselector
https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/docs/api.md#elementhandleselector

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#frameselector
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleselector

**What steps will reproduce the problem?**
The described function return signature in the `api.md` is incorrect, while its description is accurate.

`returns: <Promise<ElementHandle>>`

**What is the expected result?**

`returns: <Promise<ElementHandle | null>>`

The api.md needs to be updated, and the corresponding typescript definitions as well.

**Comment by seantanly** [comment]
Looking deeper into `api.md`, there are many other functions whose return signatures are similarly loosely defined as well. 

Though I would argue having the a accurate function signature would save some pain when the developer is skimming through the docs, and missed the description mentioning the occurrence of `null` return value, and thus missed checking for `null`.

If this is the intended convention, feel free to close this issue.

**Comment by ebidel** [comment]
Not intentional. Just imprecision in the docs. We'd love help fixing these if you'd like to submit a PR.
