### ISSUE TITLE
Css selector don't always works

### ISSUE THREAD

**Issue by Kalliser** [puppeteer/puppeteer#1359]
Hello

I noticed a tricky behavior using puppeteer
This code `page.click('body > div.wrapper > div.page > div.main-container.col1-layout > div > div.col-main > div:nth-child(6) > button.button2.btn-continue.btn-commande')` is working fine

But this code don't don't works `page.waitForSelector('body > div.wrapper > div.page > div.main-container.col1-layout > div > div.col-main > div:nth-child(6) > button.button2.btn-continue.btn-commande', {visible: true})`

After some investigation I finally found that the line 
`const node = document.querySelector(selector);`
return null in waitForSelector method but if I change the selector for something simplier like `button.button2.btn-continue.btn-commande` all is working fine.

I suspect that the problem origin is from the `div:nth-child(6)` in the css selector

**Comment by ebidel** [comment]
So does `document.querySelector('body > div.wrapper > div.page > div.main-container.col1-layout > div > div.col-main > div:nth-child(6) > button.button2.btn-continue.btn-commande')` work if you run it in the console on the page?

BTW, `waitForElement` is not an API function.

**Comment by aslushnikov** [comment]
@Kalliser you're using a very strict selector, it might fail easily if some movement happens on the page.

I'd suggest using less strict selector to allow for some flexibility.

**Comment by Kalliser** [comment]
Sorry my mistake I mean `waitForSelector` function; I edit my ticket.

@ebidel No it don't works either in the google chrome console no result is returned for the selector, I precise that the css selector was given by google chrome itself using the element inspector tool
@aslushnikov Sure but the same selector used in page.waitForSelector and page.click should works in both of them or fail in both of them but works in one and fail in another is tricky.

**Comment by ebidel** [comment]
In that case, I wouldn't expect it to work. Not sure why there's a
discrepancy with click() though.

**Comment by Garbee** [comment]
It could be when the action occurs the pages markup changes in the event which causes the second execution to not work. Since in the markup change it breaks the selector.

Try to make your own selector that is specific to the node and not the entire document structure.

**Comment by Kalliser** [comment]
A sample worth thousands words, 
```
const selector = 'body > div.wrapper > div.page > div.main-container.col1-layout > div > div.col-main > div:nth-child(6) > button.button2.btn-continue.btn-commande';

page.waitForSelector(selector, {visible:true}).then(() => {
  console.log('then click');
  page.click(selector).then(() => {
    console.log('then click done');
  });
}).catch((err) => {
  console.log('catch click');
  page.click(selector).then(() => {
    console.log('catch click done');
  });
};
```
In this sample it will output:
```
catch click
catch click done
```

waitForSelector fail to find element but page.click find it. I there is no action on the page before the click.

The problem is not to change my selector (I already do it) but a selector provided by google chrome element inspector itself don't always works in puppeteer .

I can provide a more complete sample if needed.

**Comment by aslushnikov** [comment]
@Kalliser yeah, a sample with the exact URL where you experience this would be very helpful. It's hard to judge what's going on unless we can reproduce this locally.
