### ISSUE TITLE
response.status does not print and screenshot also fails

### ISSUE THREAD

**Issue by VenPot** [puppeteer/puppeteer#1362]
it appears response .status is not printing and screenshot is not taken. Here is the code . i hope i did some thing wrong with the code i wrote as this seems to be basic functionality.

const puppeteer = require('puppeteer');

(async() => {

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto(`https:google.com`, { waitUntil: 'networkidle' });

    page.on('response', async(response) => {
        console.log("response status is ", response.status)
        if (response.ok) {

            await page.screenshot({ path: `../shots/Public/img/sucess.png` })

        }
        else await page.screenshot({ path: `../shots/Public/img/error.png` })

    })

    await browser.close();

})();

**Comment by MehdiRaash** [comment]
You should have declared **page.on('whatever')** before the actual action on page. in async/await fashion.

```
const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();

page.on('response', async(response) => {
    console.log("response status is ", response.status)
    if (response.ok) {

        await page.screenshot({ path: `../shots/Public/img/sucess.png` })

    }
    else await page.screenshot({ path: `../shots/Public/img/error.png` })

})

await page.goto(`https://google.com`, { waitUntil: 'networkidle' });



await browser.close();
})();
```

**Comment by VenPot** [comment]
thank you your comment helps, but the "on response" is being triggered for every response the page gets (eg css ,jquery etc) . My requirement is simple- 

- got to a page, if the page does not open , take a  error screen print.
- if it opens fine , take a success screen print

Any suggestion?

**Comment by MehdiRaash** [comment]
Your welcome.
One way is, **page.goto** would return a response instance as well, so you can count on it, like this.

```
let response = await page.goto('https://example.com');

if(response.status === 200){
   //
} 
```

**Comment by VenPot** [comment]
Thank you :)

**Comment by benhastings** [comment]
For anyone coming late to the game and/or new here - the correct variable is
`response._status`

**Comment by bryanlarsen** [comment]
_status is an internal variable, presumably subject to change.   Get the status via the status function: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#responsestatus
