### ISSUE TITLE
Intermittent TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by avimar** [puppeteer/puppeteer#1363]
https://github.com/GoogleChrome/puppeteer/blob/0467c346b1a23608001dd66d9fe49f147600baa6/lib/NetworkManager.js#L441

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 TypeError: Cannot read property 'url' of undefined
     at new Response (/var/www/node_modules/puppeteer/lib/NetworkManager.js:441:24)
     at NetworkManager._handleRequestRedirect (/var/www/node_modules/puppeteer/lib/NetworkManager.js:174:22)
     at NetworkManager._onRequestWillBeSent (/var/www/node_modules/puppeteer/lib/NetworkManager.js:221:12)
     at emitOne (events.js:116:13)
     at Session.emit (events.js:211:7)
     at Session._onMessage (/var/www/node_modules/puppeteer/lib/Connection.js:210:12)
     at Connection._onMessage (/var/www/node_modules/puppeteer/lib/Connection.js:105:19)
     at <anonymous>
```

Not sure where this is even coming from -- everything that I see has a catch, and my code is even working fine even when this error comes up.

Some malformed response being mishandled?

**Comment by aslushnikov** [comment]
@avimar it looks like we miss the relevant `requestWillBeSent` event from protocol. Do you use browser targets to connect to the page? This would explain this.

**Comment by avimar** [comment]
I do have `browser.on('targetcreated',interceptHandler)` always triggering, to filter out css/images from loading, which then connects via `target.pages()`.

Forgot to mention: this issue appears when running headless, but I hadn't seen it when running visible. But may not be exactly the same version.

Is that enough, or do you need more information? Can for sure test a tip-of-tree deploy.

**Comment by avimar** [comment]
Thanks, I no longer see that error.

However, after updating to master, some code stopped working:

```
await page.click('#selector');
await page.waitForNavigation({timeout:180000,waitUntil:'domcontentloaded'});
```

... I switched to a `waitForSelector` and now it works. Could this be related?

**Comment by aslushnikov** [comment]
@avimar this particular patch should not regress the `waitForNavigation` functionality. However, others might :) I'd appreciate if you file your repro case for us to investigate!

**Comment by avimar** [comment]
Looks like #1412 for future reference.
