### ISSUE TITLE
Feature Request: To have drag and drop feature or mouse hold

### ISSUE THREAD

**Issue by shmdhussain** [puppeteer/puppeteer#1366]
Feature Request: To have drag and drop feature:

Is there any way to drag one element and drop in target specified, I checked Mouse class, It seems it support basic operations, is there any plan to support drag and drop

even hold the mouse on the element to select and move it and stop mouse hold to drop in the target seems fine for drag and drop.

**Tell us about your environment:**

* Puppeteer version: 0.12
* Platform / OS version:Mac 10.10.5
* URLs (if applicable):NA

**Comment by aslushnikov** [comment]
@shmdhussain did you try using `mouse` to emulate drag-and-drop? I mean, doing precisely

```js
// Do drag-and-drop
mouse.down(..);
mouse.move(..);
mouse.up(..);
```

**Comment by shmdhussain** [comment]
@aslushnikov 

I could click on the element like

`await page.click('#searchResultsSidebar li.search-result-item');`

then How could I use Mouse class in that element, to move it after clicking? . 

Thanks in advance for any help. I am newbie to this puppeeter,

My implementation of drag and drop is baed on jQuery UI. I hope it is based on mouse move

**Comment by aslushnikov** [comment]
@shmdhussain you can do something like this:

```js
const e = await page.$('#searchResultsSidebar');
const box = await e.boundingBox();
await page.mouse.move(box.x + box.width / 2, box.y + boy.height / 2);
await page.mouse.down();
await page.mouse.move(100, 200); // move to (100, 200) coordinates
await page.mouse.up();
```

**Comment by alexdong** [comment]
Thanks @aslushnikov for the code. 

What tripped me over was the `await` in `await e.boundingBox();`. The official documentation for [elementHandle.boudingBox](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleboundingbox) seems to forget to mention that the `boundingBox` returns a `Promise`.

**Comment by aslushnikov** [comment]
@alexdong thanks, addressed in https://github.com/GoogleChrome/puppeteer/pull/1437

**Comment by shmdhussain** [comment]
@aslushnikov thanks for your help. now as you said it is working. thanks a lot for your time in helping me. since no time for me ,  not able to implement what your have suggested.

Now I did what you mentioned , it is working like a charm. :)

**Comment by ghost** [comment]
@aslushnikov  .. I tried the solution but its not working.
Here is my code :  
    const ele1 = await page.$('li.ui-orderlist-item:nth-child(2)');
    const ele2 = await page.$('li.ui-orderlist-droppoint:nth-child(7)');
    const box = await ele1.boundingBox();
    const box1 = await ele2.boundingBox();
    await ele1.click();
    await page.mouse.move((parseInt(box.x) + (parseInt(box.width) / 2)), (parseInt(box.y) + 
    (parseInt(box.height) / 2)));
    await page.mouse.down();
    await page.mouse.move((parseInt(box1.x) + (parseInt(box1.width) / 2)), (parseInt(box1.y) + 
   (parseInt(box1.height) / 2)));
    await page.mouse.up();

Please assist.

**Comment by ffMathy** [comment]
Same here.

**Comment by Bhav1907** [comment]
I am also facing this issue . Is anyone has solution for it.

**Comment by josros** [comment]
The proposed solution doesn't work for me neither. When I run the test (headless: false) on macos, it always seems to drop the dragged element at the position where the mouse pointer was located before the test started. So if put the mouse pointer in the correct position, the test occasionally succeeds.
In headless mode, it doesn't work at all.

**Comment by elaine95** [comment]
@aslushnikov I am facing the same issue with using the mouse.down, mouse.move and mouse up, it doesn't simulate drag and drop action.  Puppeteer Version: 1.6.2.

I also tried in out with https://try-puppeteer.appspot.com/ and here is my code to test the drag and drop using page.mouse: 
`const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('http://html5demos.com/drag/');
await page.waitFor(2000);

// Move mouse to the item that will be drag and mouse down
const dragItem = await page.$('a[id="one"]');
const  dragItemBox = await dragItem.boundingBox();
const x = dragItemBox.x + (dragItemBox.width/2);
const y = dragItemBox.y + (dragItemBox.height/2);

console.log(x);
console.log(y);

await page.mouse.move(x,  y);
await page.mouse.down();
await page.waitFor(100);


// Move teh drag item to container and release mouse 
const container = await page.$('div#bin');
const containerBox = await container.boundingBox();
const x1 = containerBox.x +  (containerBox.width/2);
const y1 = containerBox.y + (containerBox.height/2);

console.log(x1);
console.log(y1);

await page.mouse.move(x1,  y1);
await page.waitFor(100);
await  page.mouse.up();


// Supposely the 'Best VPN' item should be drag into container and it should be disappeared on the right side. However it still remain at the same place since the mouse down, mouse move and mouse up didn't quite work and the real drag and drop 

console.log('Finished');
await page.screenshot({path: 'screenshot.png', fullPage: true});
console.log('Screenshot taken');`
![tryPuppeteer](https://user-images.githubusercontent.com/15041131/57934322-79c22800-788d-11e9-8455-806292bd4605.PNG)

**Comment by jcrosetto** [comment]
I thought I would share a solution I got to work on Mac OSX. The site I ran it against uses react-dnd (which uses html5 drag and drop). I would imagine it wouldn't take much modification to get it working with other drag and drop frameworks.

```
async function dragAndDrop(sourceSelector, destinationSelector, page) {
  const sourceElement = await waitForVisibleSelector(sourceSelector, page);
  const destinationElement = await waitForVisibleSelector(
    destinationSelector,
    page
  );

  const sourceBox = await sourceElement.boundingBox();
  const destinationBox = await destinationElement.boundingBox();

  await page.evaluate(
    (ss, ds, sb, db) => {
      const source = document.querySelector(ss);
      const destination = document.querySelector(ds);

      const sourceX = sb.x + sb.width / 2;
      const sourceY = sb.y + sb.height / 2;
      const destinationX = db.x + db.width / 2;
      const destinationY = db.y + db.height / 2;

      source.dispatchEvent(
        new MouseEvent('mousedown', {
          bubbles: true,
          cancelable: true,
          screenX: sourceX,
          screenY: sourceY,
          clientX: sourceX,
          clientY: sourceY
        })
      );

      source.dispatchEvent(
        new DragEvent('dragstart', {
          bubbles: true,
          cancelable: true
        })
      );

      destination.dispatchEvent(
        new MouseEvent('mousemove', {
          bubbles: true,
          cancelable: true,
          screenX: destinationX,
          screenY: destinationY,
          clientX: destinationX,
          clientY: destinationY
        })
      );

      destination.dispatchEvent(
        new MouseEvent('mouseup', {
          bubbles: true,
          cancelable: true,
          screenX: destinationX,
          screenY: destinationY,
          clientX: destinationX,
          clientY: destinationY
        })
      );

      const dataTransfer = new DataTransfer();
      dataTransfer.effectAllowed = 'all';
      dataTransfer.dropEffect = 'move';
      dataTransfer.files = [];

      destination.dispatchEvent(
        new DragEvent('drop', {
          bubbles: true,
          cancelable: true,
          screenX: destinationX,
          screenY: destinationY,
          clientX: destinationX,
          clientY: destinationY,
          dataTransfer
        })
      );

      source.dispatchEvent(
        new DragEvent('dragend', {
          bubbles: true,
          cancelable: true,
          screenX: destinationX,
          screenY: destinationY,
          clientX: destinationX,
          clientY: destinationY
        })
      );
    },
    sourceSelector,
    destinationSelector,
    sourceBox,
    destinationBox
  );
}
```

**Comment by wardnath** [comment]
Thanks @jcrosetto that was the ticket. I needed to modify the code, but the approach is on point. 

For anyone interested, here's my use case. I have a [bigbluebutton server](https://github.com/bigbluebutton/bigbluebutton), and I want to dynamically assign rooms to users. The API does not allow this but has a drag and drop interface to assign users to rooms. 

simply moving the mouse would not work and would produce behavior similar to #2085 

This method did the trick, I needed to simulate drag events, not merely mouse movement. 

The extra piece I needed to do was to create a common DataTransfer object across the drag events (dragstart, drop, dragend). This is because draggable item payload information was set to this object in dragstart action and was carried through to the drop action (though the console does not show this when you print the drop DragEvent).

See React code here to see how that is set in the web application side: https://github.com/bigbluebutton/bigbluebutton/blob/8a26a2657f600ad500ee1d359fb8a5d98f48c145/bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx#L631

I've created a code snippet here to show my modifications to @jcrosetto's code: https://gist.github.com/wardnath/0aa9f293ee964c3a2bc149d9e924822e

**Comment by fgarciajulia** [comment]
First of all thank @jcrosetto, without his initiative I probably would not have solved it.
I am using drag and drop [SortableJS](https://github.com/SortableJS/Sortable) for Vue and the events name are different from what @jcrosetto wrote.

This is my solution:

```
async function dragAndDrop(page, originSelector, destinationSelector) {
  const origin = await page.waitForSelector(originSelector);
  const destination = await page.waitForSelector(destinationSelector);
  const originBox = await origin.boundingBox();
  const destinationBox = await destination.boundingBox();
  const lastPositionCoordenate = (box) => ({
    x: box.x + box.width / 2,
    y: box.y + box.height,
  });
  const getPayload = (box) => ({
    bubbles: true,
    cancelable: true,
    screenX: lastPositionCoordenate(box).x,
    screenY: lastPositionCoordenate(box).y,
    clientX: lastPositionCoordenate(box).x,
    clientY: lastPositionCoordenate(box).y,
  });

  // Function in browser.
  const pageFunction = async (_originSelector, _destinationSelector, originPayload, destinationPayload) => {
    const _origin = document.querySelector(_originSelector);
    let _destination = document.querySelector(_destinationSelector);
    // If has child, put at the end.
    _destination = _destination.lastElementChild || _destination;

    // Init Events
    _origin.dispatchEvent(new MouseEvent('pointerdown', originPayload));
    _origin.dispatchEvent(new DragEvent('dragstart', originPayload));

    await new Promise((resolve) => setTimeout(resolve, 2000));
    _destination.dispatchEvent(new MouseEvent('dragenter', destinationPayload));
    _origin.dispatchEvent(new DragEvent('dragend', destinationPayload));
  };

  // Init drag and drop.
  await page.evaluate(
    pageFunction,
    originSelector,
    destinationSelector,
    getPayload(originBox),
    getPayload(destinationBox),
  );
}

await dragAndDrop(
  page,
  '#origin-selector',
  '#destination-selector',
);

**Comment by szakhar** [comment]
> Перш за все дякую @jcrosetto , без його ініціативи я б, напевно, не вирішив цього.
> Я використовую перетягування [SortableJS](https://github.com/SortableJS/Sortable) для Vue, і назва подій відрізняється від того, що писав @jcrosetto .
> 
> Це моє рішення:
> 
> ```
> async function dragAndDrop(page, originSelector, destinationSelector) {
>   const origin = await page.waitForSelector(originSelector);
>   const destination = await page.waitForSelector(destinationSelector);
>   const originBox = await origin.boundingBox();
>   const destinationBox = await destination.boundingBox();
>   const lastPositionCoordenate = (box) => ({
>     x: box.x + box.width / 2,
>     y: box.y + box.height,
>   });
>   const getPayload = (box) => ({
>     bubbles: true,
>     cancelable: true,
>     screenX: lastPositionCoordenate(box).x,
>     screenY: lastPositionCoordenate(box).y,
>     clientX: lastPositionCoordenate(box).x,
>     clientY: lastPositionCoordenate(box).y,
>   });
> 
>   // Function in browser.
>   const pageFunction = async (_originSelector, _destinationSelector, originPayload, destinationPayload) => {
>     const _origin = document.querySelector(_originSelector);
>     let _destination = document.querySelector(_destinationSelector);
>     // If has child, put at the end.
>     _destination = _destination.lastElementChild || _destination;
> 
>     // Init Events
>     _origin.dispatchEvent(new MouseEvent('pointerdown', originPayload));
>     _origin.dispatchEvent(new DragEvent('dragstart', originPayload));
> 
>     await new Promise((resolve) => setTimeout(resolve, 2000));
>     _destination.dispatchEvent(new MouseEvent('dragenter', destinationPayload));
>     _origin.dispatchEvent(new DragEvent('dragend', destinationPayload));
>   };
> 
>   // Init drag and drop.
>   await page.evaluate(
>     pageFunction,
>     originSelector,
>     destinationSelector,
>     getPayload(originBox),
>     getPayload(destinationBox),
>   );
> }
> 
> await dragAndDrop(
>   page,
>   '#origin-selector',
>   '#destination-selector',
> );
> ```

Thank you man. It works perfectly!

**Comment by angusmunro** [comment]
> First of all thank @jcrosetto, without his initiative I probably would not have solved it.
> I am using drag and drop [SortableJS](https://github.com/SortableJS/Sortable) for Vue and the events name are different from what @jcrosetto wrote.
> 
> This is my solution:
> 
> ```
> async function dragAndDrop(page, originSelector, destinationSelector) {
>   const origin = await page.waitForSelector(originSelector);
>   const destination = await page.waitForSelector(destinationSelector);
>   const originBox = await origin.boundingBox();
>   const destinationBox = await destination.boundingBox();
>   const lastPositionCoordenate = (box) => ({
>     x: box.x + box.width / 2,
>     y: box.y + box.height,
>   });
>   const getPayload = (box) => ({
>     bubbles: true,
>     cancelable: true,
>     screenX: lastPositionCoordenate(box).x,
>     screenY: lastPositionCoordenate(box).y,
>     clientX: lastPositionCoordenate(box).x,
>     clientY: lastPositionCoordenate(box).y,
>   });
> 
>   // Function in browser.
>   const pageFunction = async (_originSelector, _destinationSelector, originPayload, destinationPayload) => {
>     const _origin = document.querySelector(_originSelector);
>     let _destination = document.querySelector(_destinationSelector);
>     // If has child, put at the end.
>     _destination = _destination.lastElementChild || _destination;
> 
>     // Init Events
>     _origin.dispatchEvent(new MouseEvent('pointerdown', originPayload));
>     _origin.dispatchEvent(new DragEvent('dragstart', originPayload));
> 
>     await new Promise((resolve) => setTimeout(resolve, 2000));
>     _destination.dispatchEvent(new MouseEvent('dragenter', destinationPayload));
>     _origin.dispatchEvent(new DragEvent('dragend', destinationPayload));
>   };
> 
>   // Init drag and drop.
>   await page.evaluate(
>     pageFunction,
>     originSelector,
>     destinationSelector,
>     getPayload(originBox),
>     getPayload(destinationBox),
>   );
> }
> 
> await dragAndDrop(
>   page,
>   '#origin-selector',
>   '#destination-selector',
> );
> ```

This worked for me where nothing else would.

Thank you very much!
