### ISSUE TITLE
Chromium process does not close if main nodejs process crashes

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#1367]
This is a test repo for the problem: 
https://github.com/entrptaher/automation-api-example

# How to reproduce:

1. Run the script.
1.1. open `localhost:3000/puppeteer/open/example.com` to open a website using puppeteer.
1.2. open `localhost:3000/nightmare/open/example.com` to open the website using nightmare.
3. Close the cmd forcefully (using close button or xkill or taskkill).

Electron processes will close, but chrome processes will runaway.

# More explanation:
Here we are opening a website using two automation scripts that creates it's own child processes, and we are not closing the browser window cause we want to use it later. It doesn't matter though since the reason chromium hangs is not that.

![2017-11-13 09_59_23-localhost_3000_puppeteer_open_example com](https://user-images.githubusercontent.com/8284972/32709325-b66b8804-c859-11e7-9fcb-b09f303c48dc.png)
![2017-11-13 09_59_39-localhost_3000_nightmare_open_example com](https://user-images.githubusercontent.com/8284972/32709327-bae458f2-c859-11e7-81f3-3c991ba3d3d4.png)

You can see that they are running in background. 
![2017-11-13 09_59_48-task manager](https://user-images.githubusercontent.com/8284972/32709331-bde883f2-c859-11e7-92be-6ea1d300f0bd.png)

Now, If you use Ctrl+C on that cmd prompt, first it will kill the child processes (like chromium), 
then on anther Ctrl+C, it will kill the node process. But if you forcefully close the cmd prompt, say with xkill or the close button, or somehow the node process crashes, then the child processes are hung up. The electron processes are gone, but the chromium processes are still there doing nothing.

![2017-11-13 10_00_10-cmder](https://user-images.githubusercontent.com/8284972/32709336-c7433c80-c859-11e7-8293-101b06982e10.png)

![2017-11-13 10_01_03-pup](https://user-images.githubusercontent.com/8284972/32709340-caf6cef0-c859-11e7-9116-969feb09ef9e.png)

![2017-11-13 10_01_21-task manager](https://user-images.githubusercontent.com/8284972/32709342-cd47484c-c859-11e7-98b9-641c6d146953.png)

I could create a better script to test this out, but this is more realistic than a test script.

# Guesses:
It could be that the puppeteer is not listening for the right process event, it could be something other than `SIGINT` or `exit`.

Related issues: https://github.com/GoogleChrome/puppeteer/issues/1047

**Comment by sukrosono** [comment]
This was valuable information, since i recall the condition on my case is similar to this.

**Comment by entrptaher** [comment]
Alright it worked. Node process took few seconds to close though. Great. Onto finding another bug :)

**Comment by TheGuywithTheHat** [comment]
Any idea when the fix is likely to be released? I'm assuming v0.14.0 or v0.13.1, which might be 2-3 weeks away?

**Comment by entrptaher** [comment]
This is the fastest way to use it,
`yarn add https://github.com/GoogleChrome/puppeteer`

**Comment by TheGuywithTheHat** [comment]
I generally try to avoid non-npm dependencies if possible, so I was just wondering if changing to a github repo dependency would be worth it.

This issue doesn't have a major effect on us, so I won't bother switching unless it'll be a while before this is officially released.

**Comment by sukrosono** [comment]
What about use `yarn add https://github.com/GoogleChrome/puppeteer` for now, than  after team release you can replace it with `npm i puppeteer -D`? In my opinion you can't choose an option without pain in life, the **best** option you can take is the option which give less pain. Kindly pick which suit you.

**Comment by TheGuywithTheHat** [comment]
Due to another issue (already documented here), the installation for puppeteer on some of our computers is a bit more complicated, so I'd like to avoid switching as much as possible. Which evil is the lesser thus comes down to how long we'll have to deal with a few extra orphaned chromiums, which is why I was asking in the first place. Thanks for the suggestions, though.

**Comment by sukrosono** [comment]
@TheGuywithTheHat  Well it turn more complicated than i thought, change directly the source code of installed version?
Did it somehow also cost you?

@aslushnikov can we release `0.13.1` for the shake of puppeteer user, specially for this case?

**Comment by TheGuywithTheHat** [comment]
I appreciate it but I don't think that'll be necessary. It seems like it's more effort for you to make a special release than it is for us to deal with the bug for a few weeks. It really won't be too difficult to temporarily switch to a github dependency, either; I was just wondering which option might save us a few minutes.

**Comment by entrptaher** [comment]
I think you can simply use that one line for now. You know, you could actually save the past 8 hours by writing one line. 
```
yarn add https://github.com/GoogleChrome/puppeteer
```

And when the time comes, you could save another 8 hours by writing another command. It would take only few seconds to write.
```
yarn add puppeteer
```

**Comment by Spongman** [comment]
i get an error calling `browser.close()`:

````

ERROR: The process "15008" not found.
(node:6696) UnhandledPromiseRejectionWarning: Error: Command failed: taskkill /pid 15008 /T /F
ERROR: The process "15008" not found.

    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at forceKillChrome (C:\play\p5.js\node_modules\puppeteer\lib\Launcher.js:160:24)
    at killChrome (C:\play\p5.js\node_modules\puppeteer\lib\Launcher.js:147:9)
    at Browser.close (C:\play\p5.js\node_modules\puppeteer\lib\Browser.js:129:31)
    at process.on (C:\play\p5.js\node_modules\mocha-headless-chrome\runner.js:177:25)
    at process.emit (events.js:164:20)
    at Signal.wrap.onsignal (internal/process.js:198:44)
(node:6696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside
of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> Error: Protocol error (Runtime.evaluate): Target closed.
````

**Comment by aslushnikov** [comment]
@Spongman please file a new issue with a repro. Could it be that you accidentally call `browser.close()` twice?

**Comment by YannickBochatay** [comment]
I still have the problem, using Express and Puppeteer 13.5.1. Three Chromium processes remain after pressing Ctrl+c : 

![puppeteer](https://user-images.githubusercontent.com/527289/203938345-9d2722fe-a814-42f8-a4bd-24c43eafb1ac.gif)
