### ISSUE TITLE
How can we get  response time? Page metrics doesn't have it.

### ISSUE THREAD

**Issue by VenPot** [puppeteer/puppeteer#1368]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by Everettss** [comment]
Response of what? 

If you want to get response for example of `https://example.com` you should use `page.tracing` and then extract from tracing data what is interesting for you.

Here is example:

```javascript
const puppeteer = require('puppeteer');
const fs = require('fs');

const getTimeFromMetrics = (metrics, name) => metrics.metrics.find(x => x.name === name).value * 1000;

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.tracing.start({ path: 'trace.json' });
    await page.goto('https://example.com', { timeout: 60000 });

    const metrics = await page._client.send('Performance.getMetrics');
    const navigationStart = getTimeFromMetrics(metrics, 'NavigationStart');
    await page.tracing.stop();

    // --- extracting data from trace.json ---
    const tracing = JSON.parse(fs.readFileSync('./trace.json', 'utf8'));
    const htmlTracing = tracing.traceEvents.filter(x => (
        x.cat === 'devtools.timeline' &&
        typeof x.args.data !== 'undefined' &&
        typeof x.args.data.url !== 'undefined' &&
        x.args.data.url === 'https://example.com/'
    ));
    const HtmlResourceSendRequest = htmlTracing.find(x => x.name === 'ResourceSendRequest');
    const HtmlId = HtmlResourceSendRequest.args.data.requestId;
    const htmlTracingEnds = tracing.traceEvents.filter(x => (
        x.cat === 'devtools.timeline' &&
        typeof x.args.data !== 'undefined' &&
        typeof x.args.data.requestId !== 'undefined' &&
        x.args.data.requestId === HtmlId
    ));
    const HtmlResourceReceiveResponse = htmlTracingEnds.find(x => x.name === 'ResourceReceiveResponse');
    const HtmlResourceReceivedData = htmlTracingEnds.find(x => x.name === 'ResourceReceivedData');
    const HtmlResourceFinish = htmlTracingEnds.find(x => x.name === 'ResourceFinish');
    // --- end extracting data from trace.json ---

    await page.close();

    let results = [
        {
            variable: 'HtmlResourceReceiveResponse',
            value: HtmlResourceReceiveResponse.ts/1000 - navigationStart
        },
        {
            variable: 'HtmlResourceReceivedData',
            value: HtmlResourceReceivedData.ts/1000 - navigationStart
        },
        {
            variable: 'HtmlResourceSendRequest',
            value: HtmlResourceSendRequest.ts/1000 - navigationStart
        },
        {
            variable: 'HtmlResourceFinish',
            value: HtmlResourceFinish.ts/1000 - navigationStart
        },
    ];

    console.log(results);
})();
```

**Comment by VenPot** [comment]
To your question on what response time? - i am trying to get what Performance.timing would show in a chrome browser. especially the response end and the domInteractive . I will look at your example and post any questions after my work today. Thank you for taking the time to respond!

**Comment by Everettss** [comment]
In `trace.json` you will find `domInteractive` event.
If you want extract `window.performance.timing` you should do this:

```javascript
const performanceTiming = await page.evaluate(() => window.performance.timing);
console.log(performanceTiming);
```

**Comment by VenPot** [comment]
Evaluate did the trick. @Everettss  Thanks  much.

**Comment by DrNBG** [comment]
Can someone please share the code to capture window.performance.timing as I am new to puppeteer... recently started exploring? tried as suggested by @Everettss but in vain. Thanks

**Comment by Everettss** [comment]
@DrNBG you should use solution from [this thread](https://github.com/GoogleChrome/puppeteer/issues/1535#issuecomment-349068200)

```javascript
const performance = JSON.parse(await page.evaluate(
   () => JSON.stringify(window.performance)
));
```
[Here](https://puppeteersandbox.com/MrRF59oh) you can find this code running in the sanbox.

If you are looking for tutorial how to extract window.performance.timing with Puppeteer take a look at this [article](https://michaljanaszek.com/blog/test-website-performance-with-puppeteer#navigationTimingAPI).

**Comment by DrNBG** [comment]
@Everettss, 
Used the code as you shared. Works like a charm! The tutorial is helping me to understand various aspects.
Really appreciated.
