### ISSUE TITLE
How to dismiss certificate dialog of system

### ISSUE THREAD

**Issue by laispace** [puppeteer/puppeteer#1369]
Follow up from https://github.com/GoogleChrome/puppeteer/issues/540 .

How can I control the certificate dialog or just dismiss it?

![image](https://user-images.githubusercontent.com/2217416/32716734-15c7d810-c892-11e7-9646-6561abed6346.png)

**Comment by aslushnikov** [comment]
unfortunately, there is currently no way. Please, upvote the #540.
