### ISSUE TITLE
Feature request: Allow page/frame evaluate's pageFunction to return rejected Promise

### ISSUE THREAD

**Issue by xprudhomme** [puppeteer/puppeteer#1379]
As of today, here is the evaluate default behavior:

> If the function, passed to the frame.evaluate, returns a Promise, then frame.evaluate would wait for the promise to resolve and return its value.

> If the function passed into frame.evaluate returns a non-Serializable value, then frame.evaluate resolves to undefined.

But how about "If the function, passes to the frame.evaluate, returns a rejected Promise.." ?

There is currently no way to catch possible errors/rejected promises happening in the evaluate's pageFunction, after the frame.evaluate call.

### Steps to reproduce

```javascript
    page.evaluate( () => { 
        // WHATEVER CODE BEFORE
        return Promise.reject("MY_CUSTOM_ERROR"); // OR: throw("MY_CUSTOM_ERROR");
    })
    .catch(err => {
        console.log(" Error detected: " + err);
        throw err;
    });
```

**What would the expected result ?**
The error handled by the catch block, chained after the page.evaluate call would be, in that case, "MY_CUSTOM_ERROR" 

**What happens instead?**
Instead, currently it displays " Error detected: undefined"

Most likely because of the way the evaluate method is implemented in ExecutionContext.js:

```javascript
  /**
   * @param {function(*)|string} pageFunction
   * @param {...*} args
   * @return {!Promise<(!Object|undefined)>}
   */
  async evaluate(pageFunction, ...args) {
    const handle = await this.evaluateHandle(pageFunction, ...args);
    const result = await handle.jsonValue().catch(error => undefined);
    await handle.dispose();
    return result;
}
```
@aslushnikov :
Would that make sense to have this new behavior?

**Comment by aslushnikov** [comment]
@xprudhomme thanks for filing this.

I'd align this feature with #1694: we should have the actual evaluation error as one of the pptr error fields.

**Comment by aslushnikov** [comment]
This works as expected in puppeteer v1.6.0. 

The following script prints "error detected" and the caught error:

```
 Error detected: Error: Evaluation failed: MY_CUSTOM_ERROR
```

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.evaluate(() => Promise.reject("MY_CUSTOM_ERROR")).catch(err => console.log(" Error detected: " + err));
    await browser.close();
})();
```
