### ISSUE TITLE
Chromium file download with HTTP

### ISSUE THREAD

**Issue by deisser** [puppeteer/puppeteer#1380]
### Problem
I set the `PUPPETEER_DOWNLOAD_HOST` env to our Artifactory Repository. When it tries to dowload Chromium I get a `unable to verify the first certificate` error.

It would be helpfull to make a **http** request instead of **https**.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Windows 8.1, Yarn 1.3.2

**What steps will reproduce the problem?** 

_Please include code that reproduces the issue._

1. Add puppeteer to package.json
2. Set `PUPPETEER_DOWNLOAD_HOST` to private Artifactory Reposiroty and  `strict-ssl false`in .yarnrc 
3. yarn install
4. receive error
```
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\...\node_modules\puppeteer
Output:
ERROR: Failed to download Chromium r515411! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1104:38)
    at emitNone (events.js:105:13)
```

There has to be a possibility to make a http or https request for the given protocol in  `PUPPETEER_DOWNLOAD_HOST` env.

In `ChromiumDonwloader.js` the function `downloadFile` should be adjusted.
```javascript
function downloadFile(url, destinationPath, progressCallback) {
  let fulfill, reject;

  const promise = new Promise((x, y) => { fulfill = x; reject = y; });

  const options = requestOptions(url);
  const request = https.get(options, response => {
    if (response.statusCode !== 200) {
      const error = new Error(`Download failed: server returned code ${response.statusCode}. URL: ${url}`);
      // consume response data to free up memory
      response.resume();
      reject(error);
      return;
    }
    const file = fs.createWriteStream(destinationPath);
    file.on('finish', () => fulfill());
    file.on('error', error => reject(error));
    response.pipe(file);
    const totalBytes = parseInt(/** @type {string} */ (response.headers['content-length']), 10);
    if (progressCallback)
      response.on('data', onData.bind(null, totalBytes));
  });
  request.on('error', error => reject(error));
  return promise;

  function onData(totalBytes, chunk) {
    progressCallback(totalBytes, chunk.length);
  }
}
```

**Comment by xiaosi-ss** [comment]
me too

**Comment by tglines** [comment]
@deisser can you give an example as to how you're setting the `PUPPETEER_DOWNLOAD_HOST` to artifactory?  I'm trying to do something similar.

**Comment by odyssey-spec** [comment]
me too

**Comment by aslushnikov** [comment]
This should be working fine with pptr 1.0.0:

https://github.com/GoogleChrome/puppeteer/blob/12b57e31f386b1bd8845aba0246894fde8fe9ed8/lib/Downloader.js#L274
