### ISSUE TITLE
click element <a href="hallo"> after waitForNavigation() not working in ver.0.13

### ISSUE THREAD

**Issue by yfcck** [puppeteer/puppeteer#1382]
in ver.0.13 
**
await page.waitForSelector(loginSelector);
let login = await page.$(loginSelector);
await login.click({delay: 100})
await login.dispose();
await page.waitForNavigation();
**
always error of timeout
but use
`await page.waitFor(6000);`
work fine

in the ver.0.12
`await page.waitForNavigation();` 
work fine

**Comment by smoakey** [comment]
@hugesswnn did you discover the issue?

**Comment by yfcck** [comment]
"puppeteer": "^0.13.0"
solved
waitForNavigation() before do not call dispose()

**Comment by yfcck** [comment]
@smoakey   
Hmmm
