### ISSUE TITLE
on headless:false the window pops up each time a new tab is opened

### ISSUE THREAD

**Issue by avimar** [puppeteer/puppeteer#1386]
**Tell us about your environment:**

* Puppeteer version: 0.13.0-alpha
* Platform / OS version: Windows

**What steps will reproduce the problem?**
Click links that open a new tab or create a new tab.

**What is the expected result?**
If the window is minimized, it would stay minimized, and allow me to monitor it when I wanted.

**What happens instead?**
It pops up from the task bar and grabs the keyboard focus.

**Comment by aslushnikov** [comment]
Closing as a dupe of #1083.
