### ISSUE TITLE
Error: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by XVincentX** [puppeteer/puppeteer#1388]
* Puppeteer version: 0.13.0
* Platform / OS version: Windows / Linux with Docker
* URLs (if applicable): [Windows CI](https://circleci.com/gh/ExpressGateway/express-gateway/1654?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) — [CircleCI](https://circleci.com/gh/ExpressGateway/express-gateway/1654?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

Hello guys!
I'm working on [Express-Gateway](github.com/ExpressGateway/express-gateway) and among all our tests we do have a small test that's checking using phantomjs and selenium if a super simple oauth flow is working correctly.

I tried to switch to Puppeteer [in this PR](https://github.com/ExpressGateway/express-gateway/pull/536) but unfortunately I'm getting consistent failures on both Windows (AppVeyor) and Linux with Docker (CircleCI). I honestly can't understand why the navigation is failing.

The page is definitely simple ([no javascript, no styles](https://github.com/ExpressGateway/express-gateway/blob/master/lib/policies/oauth2/views/login.ejs)) and should load almost immediately.

I would really appreciate your help here — as I do not know how to debug this further.

Thanks,
V.

**Comment by joelgriffith** [comment]
In your PR, does `authURL` have a `#` in the URL? There's a small known issue regarding pageload for URL's with an ID in them.

**Comment by guanbiao33** [comment]
the same,
await page.waitForNavigation({timeout:20000}).then(()=>{},()=>{
      console.log('url fail load');
    });
if config headless:false,it does work, otherwise it doesn't work and throw error:
Navigation Timeout Exceeded: 30000ms exceeded

**Comment by XVincentX** [comment]
@joelgriffith 
Hey — so `authURL` is `http://localhost:49553/oauth2/authorize?response_type=code&client_id=fd0cd68b-472d-476b-99d2-ce9eed67dd97&state=ABC123xyz&redirect_uri=http%3A%2F%2Flocalhost%3A49556%2Fcb`

and it's generated through this code:

```javascript
    const authURL = url.format({
      protocol: 'http',
      hostname: 'localhost',
      port: gatewayPort,
      pathname: '/oauth2/authorize',
      query: {
        response_type: 'code',
        client_id: clientID,
        state: state,
        redirect_uri: `http://localhost:${redirectPort}/cb`
      }
    });
```

I do not see any hashbang in it.

It is sometimes passing, but 99% it's not.

**Comment by XVincentX** [comment]
Link to the original PR (for cross linking purposes): https://github.com/ExpressGateway/express-gateway/pull/536

**Comment by JulianKlug** [comment]
experiencing a similar problem whilst loading a simple test page on localhost

**Comment by wouterdialogic** [comment]
I had the same issue.
Check if the url has an #.
If so, remove

`url = url .substring(0, url .indexOf('#'));`

and continue,

**Comment by zhaiduo** [comment]
@wouterdialogic SPA always has an # in URL.

**Comment by ebidel** [comment]
@zhaiduo FWIW, it's now considered an anti-pattern to use `#` in SPA navigation. Google deprecated the `#!` recommendation back in 2015. Instead, you should be using the History API to create real looking URLs.

**Comment by XVincentX** [comment]
Would it be possible to at least know whether this is a confirmed bug or something is wrong on my side?

If the latter, wouldn't it be better to log this situation so people can realize what's going on and fix the things accordingly?

**Comment by UttakarshTikku** [comment]
@joelgriffith 

> In your PR, does authURL have a # in the URL? There's a small known issue regarding pageload for URL's with an ID in them.

Is a workaround possible for this issue?

**Comment by yi-ge** [comment]
How to solve the problem in the new version(1.1.1)?

thank you.

**Comment by ylambda** [comment]
@yi-ge 

I solved this using `page.waitForFunction` and a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)

``` javascript
// element - the element to click for navigation
// query - documentSelector query for the element to watch mutations when the page changes
async clickAndPageLoaded(element, query) {

    // Sometimes a website uses '#' for navigation in a SPA
    // Currently Chrome navigation fails to recognize this
    // Create a mutation observer and poll for changes on the page

    await this.page.evaluate(query => {
        let handler = () => window._TMP_PAGE_LOADED = true;
        let node = document.querySelector(query);
        window._TMP_PAGE_LOADED = false;
        window._TMP_MUTATION_OBSERVER = window._TMP_MUTATION_OBSERVER || new MutationObserver(handler);
        window._TMP_MUTATION_OBSERVER.observe(node, {childList: true});
    }, query);

    return Promise.all([
        this.page.waitForFunction("window._TMP_PAGE_LOADED"),
        element.click()
    ]);
}
```
For this example I changed the window global variables for readability. In my local copy they're very strange looking to avoid clashing with anything on the page.

Things may have been fixed in the newly released v1.2.0 branch. I haven't had the chance to try it there.

**Comment by XVincentX** [comment]
Thanks for the hack! However I'm not willing to put such thing in my code. I'll stick with other solutions for now.

**Comment by yi-ge** [comment]
@ylambda Thank you very much!

**Comment by putuoka** [comment]
@ylambda how about if i get an error when page.goto() function? my url contain # symbol. i'm not even on the selecting element yet and the error comes UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded

**Comment by aslushnikov** [comment]
Closing as a dupe of #257.

**Comment by petarthewizard** [comment]
I don't think this is exactly a dupe but I'll open another issue.
