### ISSUE TITLE
UnhandledPromiseRejectionWarning timeout 30000ms exceeded

### ISSUE THREAD

**Issue by fakirpic** [puppeteer/puppeteer#1390]
```
const browser = await puppeteer.launch({
  headless: true
});
  const page = await browser.newPage();
  page.on('error', msg => { browser.close(); });
  page.on('pageerror', msg => { browser.close();  });
  page.setViewport({width:1366,height:768});
  await sleep(1000);  
  await page.goto('https://google.com');

```
sometimes (not always) i get this error

> (node:45048) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: waiting failed: timeout 30000ms exceeded
> (node:45048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

  page.on('error', msg => { browser.close(); });
  page.on('pageerror', msg => { browser.close();  });

but i have these events. are not they enough to catch this error?

**Comment by Khady** [comment]
What you want is more a try/catch around the call to `page.goto`:

```javascript
const browser = await puppeteer.launch({
  headless: true
});
const page = await browser.newPage();
page.setViewport({width:1366,height:768});
await sleep(1000);
try
  await page.goto('https://google.com');
catch (error) {
  console.log(error);
  browser.close();
}
```

Also, if you want to handle a promise rejection, the good event is not `error` or `pageerror` but `unhandleRejection`:

```javascript
const browser = await puppeteer.launch({
  headless: true
});
const page = await browser.newPage();
process.on("unhandledRejection", (reason, p) => {
  console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
  browser.close();
});
page.setViewport({width:1366,height:768});
await sleep(1000);
await page.goto('https://google.com');
```

**Comment by avimar** [comment]
Correct - they catch an event, but not the failed/thrown Promise.

You can also extend the timeout in the `goto` call: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

**Comment by shabbir1993** [comment]
I've used try/catch as well as promise handling but still the issue remains...

**Comment by aslushnikov** [comment]
@shabbir1993 this might be due to lack of `await` statement next to the promise.

Overall, @Khady gave an [exhaustive answer](https://github.com/GoogleChrome/puppeteer/issues/1390#issuecomment-344506047). Thank you.

**Comment by kselax** [comment]
**process.on...** doesn't work, need to use **catch** or **try catch**
```javascript
await page.goto(url, { timeout: 120000, waitUntil: 'networkidle0' })
    .catch(e => {
      console.log('here I am');
      browser.close()
    })
```

or

```javascript
try {
    await page.goto(url, { timeout: 120000, waitUntil: 'networkidle0' })
  } catch(e) {
    console.log('here I am');
    browser.close()
  }
```

**Comment by noamaankhan** [comment]
This solution still doesnt work. The error is always thrown. I have this example code:

```
try {
      const handle = await page.waitForSelector(selector, { timeout: 0 });
      if (handle === null) {
        return false;
      }
      return true;
    } catch (e) {
      //IT NEVER GETS HERE AND AN ERROR IS THROWN WHEN SELECTOR ISNT VISIBLE ON THE PAGE
      console.error(e);
      return false;
    }

**Comment by avimar** [comment]
@noamaankhan perhaps your error is thrown in the previous step, in the `page.goto` ?

**Comment by noamaankhan** [comment]
> @noamaankhan perhaps your error is thrown in the previous step, in the `page.goto` ?

@avimar No, I followed steps through debugging and logging to confirm it was being thrown on this line.

I also flipped the test usecase and code to test for `hidden: true` and `visible:true` to confirm both respectively.

**Comment by noamaankhan** [comment]
These issues needs to be resolved. Or change the documentation please. Error thrown from waitForSelector is never caught in the catch block surrounding it. Probably because of some internal catch mechanism which ends the test before reaching the catch block surrounding the api.

**Comment by jkliptonia** [comment]
I am having the same issue with page.waitFor

```
try {
        await page.waitFor('div.newForm', { hidden: true, timeout: 10000 });
    } catch (err) {
        page.evaluate(() => console.error(`Puppeteer Error: ${err} -- Please look in errors folder for screenshot of issue`));
    }
```

returns `UnhandledPromiseRejectionWarning: Unhandled promise rejection.` followed by `ReferenceError: err is not defined`
