### ISSUE TITLE
when I use the method "page.type",it throw a exception"Failed to execute 'querySelector' on 'Document'"

### ISSUE THREAD

**Issue by fulldo** [puppeteer/puppeteer#1392]
when I use the method "page.type",it throw a exception"Failed to execute 'querySelector' on 'Document'".

how can i resolve it

**Comment by vsemozhetbyt** [comment]
Could you provide a code that throws?

**Comment by fulldo** [comment]
I didn't know what was wrong until I read the document.
my code is :
`page.type(string)`
but it throw a exception
the document is
`page.type(selector,string)`
i think i use old api

**Comment by joelgriffith** [comment]
Yes this was a change in 0.12.0, you have to specify the selector in 0.12.0 and forward

**Comment by yfcck** [comment]
try this
`

    let passwordIpt = await page.$('#selector');

    await passwordIpt.click({ delay: 100 });

    await passwordIpt.type('123456', { delay: 100 });

    await passwordIpt.dispose();
`
