### ISSUE TITLE
page.collectGarbage()

### ISSUE THREAD

**Issue by pragmaproducts** [puppeteer/puppeteer#1394]
I would like to collect garbage in the process of tests so that I can do metrics and doing traces between operations.

Chrome dev tools has a clear garbage button on the performance tab.
Can we get access to the operations of that button please in the same way as you can do it manually  on the performance tab.

something like page.collectGarbage() would be really appreciated.

**Comment by Everettss** [comment]
Since we are waiting for #31 you can use at this moment [Chrome DevTools Protocol - `HeapProfiler.collectGarbage`](https://chromedevtools.github.io/devtools-protocol/tot/HeapProfiler/#method-collectGarbage): 
```javascript
await page._client.send('HeapProfiler.enable');
await page._client.send('HeapProfiler.collectGarbage');
```

**Comment by aslushnikov** [comment]
cc @a1ph

**Comment by trentmwillis** [comment]
@aslushnikov is this feature still desired? If so, I'd be happy to implement it with some guidance on what exactly the internals should be. Perhaps it is just `HeapProfiler.enable > HeapProfiler.collectGarbage > HeapProfiler.disable`?

**Comment by aslushnikov** [comment]
@trentmwillis @Everettss @pragmaproducts The `page.collectGarbage()` would be quite racy, I'm not convinced this is anyhow useful. Consider the following pptr script:

```js
// This would successfully collect garbage
await page.collectGarbage();
// However, by the time control is returned to pptr,
// the page could've produced a ton more garbage
startCollectingMyMetrics();
```

If you do memory analysis, `queryObjects` API is much more robust.

Can you guys share your usecases?

**Comment by wrager** [comment]
@aslushnikov In my case, I would like to make sure that the scheduled garbage collection can not affect my performance metrics:

``` js
// It would be nice to force the GC here:
await page.collectGarbage();
const startTime = performance.now();
// Some actions that I measure
const endTime = performance.now() - startTime;
```

**Comment by trentmwillis** [comment]
@aslushnikov while that is true, I believe it would be helpful for verifying that certain objects are not being retained (a.k.a., leaking). For example:

```js
// Page has performed some action

// Force a GC to ensure garbage from previous actions has been collected
await page.collectGarbage();

// Verify object has not been accidentally retained after the action
const objs = await page.queryObjects(objectsThatShouldGetCleanedUp);
expect(objs.length).to.equal(0);
```

If there is a better way to approach the above, I'm totally good with that as well. But this is the use case I'm interested in.

**Comment by aslushnikov** [comment]
@trentmwillis I believe `page.queryObjects` already calls gc internally, so it should return only retained objects.

cc @ak239 who can confirm/deny this claim.

**Comment by alexkozy** [comment]
Yes, queryObjects internally calls gc.

**Comment by trentmwillis** [comment]
Awesome, that works for me then! Can't think of another use for this API as of now.

**Comment by aslushnikov** [comment]
> @aslushnikov In my case, I would like to make sure that the scheduled garbage collection can not affect my performance metrics:

Unfortunately, even after calling gc manually, there's no guarantee it won't be triggered during the measured code snippet.

We can re-consider this later if there are more usecases; closing for now.
