### ISSUE TITLE
Please add the initiator information

### ISSUE THREAD

**Issue by thewulf00** [puppeteer/puppeteer#1395]
Requests, that are fired after the basic request is done, are initiated by some source - f.e. a script or something. Since chrome does provide this information in the network tab, I wonder if you can give it via puppeteer?

Example:
![image](https://user-images.githubusercontent.com/20280311/32839936-68063286-ca16-11e7-8f61-c93bd6054cf0.png)

**Comment by jawadst** [comment]
+1, that'd be very helpful

**Comment by zicongxie** [comment]
@aslushnikov  Please! That is useful for me.

**Comment by thewulf00** [comment]
Thank you for your replies. I hoped that somebody will need it too.
@aslushnikov Is it possible to get this? I find puppeteer very useful!

**Comment by Garbee** [comment]
Out of curiosity, could someone provide an example use-case for needing this information through puppeteer?

**Comment by ctavan** [comment]
@Garbee assuming you use puppeteer to analyze a website which includes 3rd-party code like social sharing buttons. You may want to know which requests were initiated by your own 1st-party code and which requests were initiated by 3rd-party code. This could help you spot performance problems like 3rd-party widgets that cause a lot of subsequent requests.

**Comment by sebastianneubert** [comment]
@Garbee Same here. We want to build request maps to vizualise which request was called from where. So we can check, where are performance/memory leaks at 3rd party includes. This could be very helpful to point out, which scripts or iframes initate a waste amount of requests/cookies/trackers. We have all information to build this, except of the initiator of the request.

**Comment by Laywanger** [comment]
+1 I need this to track malvertising
@aslushnikov Is it possible ?

**Comment by aslushnikov** [comment]
We don't currently have initiator information in the request interception events.

Filed upstream: [crbug.com/800623](https://bugs.chromium.org/p/chromium/issues/detail?id=800623)

**Comment by joshgoodwin** [comment]
I believe that initiator is available to the event object (event.initiator) in NetworkManager.js here: 

https://github.com/GoogleChrome/puppeteer/blob/master/lib/NetworkManager.js#L209

You should be able to just forward that property along like you do with event.requestId, no?

**Comment by aslushnikov** [comment]
@joshgoodwin initiator is not available for intercepted requests; that's what the upstream bug is about.

https://github.com/GoogleChrome/puppeteer/blob/8c930843160d7fff76a82bf154f151e2bdd29383/lib/NetworkManager.js#L127-L133

**Comment by sebastianneubert** [comment]
Any news about the refactoring of #1817 and the initiator information in an intercepted request?

**Comment by madecki** [comment]
It would be great to get information about cookie and request initiators!

**Comment by phackt** [comment]
Hello, any news about the initiator attribute ? thanks

**Comment by sebastianneubert** [comment]
Not really as `initiator`. But in the last updates of puppeteer, most requests have the `referer` information in the header, which is fine for me.

    page.on('request', interceptedRequest => {
        const url = interceptedRequest.url();
        header_referer = interceptedRequest.headers()['referer'];
        console.log(interceptedRequest);
        interceptedRequest.continue();
    });

**Comment by phackt** [comment]
@sebastianneubert yes not really the same, you don't have the name of the exact resource involved in the request, also no referer is sent with XHR. The field ```initiator``` is really missing.

**Comment by rylyade1** [comment]
@phackt actually referrer is also sent with XHR, but there is no guarantee of this header being present (e.g when the [referrer policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) is set to 'no-referrer'). In these cases @sebastianneubert your solution will probably throw an exception.

**Comment by nwingert** [comment]
FYI, initiator info is available using CDP directly. Here's an example from the solution I'm using atm. 

// https://github.com/ChromeDevTools/devtools-protocol/issues/56
// increase CallStackDepth to fix initiator stack issue in chrome
const client = await testPage.target().createCDPSession();
await client.send('Debugger.enable');
await client.send('Debugger.setAsyncCallStackDepth', { maxDepth: 32 });

// https://github.com/GoogleChrome/puppeteer/issues/1395    
// puppeteer request events don't propagate initiator currently
// so register for the event directly with CDP instead
await client.send('Network.enable');
await client.on('Network.requestWillBeSent', (params) => {
  const reqURL = params.request.url;
  logger.info(`request to: ${reqURL}`);
  logger.info(`from initiator: ${getInitiatorUrl(params.initiator)}`);
});

getInitiatorUrl is a little recursive function to search the initiator callstack for the info I need, not included because it's too specific to my requirements.

**Comment by aslushnikov** [comment]
To everybody: do I get it right that you guys need both initiator type and a stacktrace?

**Comment by ctavan** [comment]
@aslushnikov speaking for me: yes, both would be great!

This patch worked for me (kind of): https://github.com/ctavan/puppeteer/commit/8cdda1658d563f4b60bee5ae72b726a72e4d1275

With this `initiator()` information at hand I used code like this:

```js
    const initiator = request.initiator();
    let simplifiedInitiator;
    if (initiator.type === 'parser') {
      simplifiedInitiator = {
        type: 'parser',
        url: initiator.url
      };
    } else if (initiator.type === 'script') {
      simplifiedInitiator = {
        type: 'script',
        urls: [...(new Set(initiator.stack.callFrames.map(frame => frame.url).filter(v => Boolean(v))))],
        functions: [...(new Set(initiator.stack.callFrames.map(frame => frame.functionName).filter(v => Boolean(v))))],
      };
    } else {
      simplifiedInitiator = initiator;
    }
```

to extract a "simplified" version of the initiator.

**Comment by FranklinYu** [comment]
Note to myself (hope this helps someone else): the type definition of initiator is at

https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Initiator

**Comment by Marmeladenbrot** [comment]
Any news about that / solution for Puppeteer to get the initiator?

**Comment by Vasile-Peste** [comment]
Is there a way to get a initiator also for cookies?

**Comment by ojaswa1942** [comment]
@Vasile-Peste +1. Looking for this too! Did you find any solution or workaround to this?

Currently the only solution I can think is to create a map between various existing parameters from requests and cookies, but that is likely to give false positives as per my use case (due to possible variations in `domain` and `path` properties of cookies).

But even then, a mapping solution with requests will still not work for cookies set using `document.cookie`.

**Comment by HarshiShah** [comment]
Any plans on adding the initiator information? I see pull requests for this feature open for more than 2 years.

**Comment by whalderman** [comment]
Thank you @jschfflr !

**Comment by BennyAlex** [comment]
@jschfflr

Hello,

Is it also possible to get the whole request Initiator chain?
Thanks!

**Comment by ojaswa1942** [comment]
@BennyAlex Did you happen to extract this information?

**Comment by BennyAlex** [comment]
@ojaswa1942 
No unfortunatelly not :/

**Comment by OrKoN** [comment]
Looks like it's been implemented. I believe you would only get the initiator for the initial request in a redirect chain. Please file  a new feature request for this.
