### ISSUE TITLE
A way to shutdown ServiceWorker

### ISSUE THREAD

**Issue by NekR** [puppeteer/puppeteer#1396]
It would be good if there was a way to shutdown/stop ServiceWorker. This is needed for tests.

**Comment by Everettss** [comment]
Since we are waiting for #31 you can use at this moment one of [Chrome DevTools Protocol - `ServiceWorker Domain`](https://chromedevtools.github.io/devtools-protocol/tot/ServiceWorker/) methods.

For example: 
```javascript
await page._client.send('ServiceWorker.enable');

await page._client.send('ServiceWorker.stopAllWorkers');
// or 
await page._client.send('ServiceWorker.unregister', { scopeURL: "http://your-url" });
```

**Comment by NekR** [comment]
@Everettss thanks for a suggestion, sounds good!

**Comment by aslushnikov** [comment]
Closing as a dupe of #2634
