### ISSUE TITLE
Is Language translation possible?

### ISSUE THREAD

**Issue by marijanlekic** [puppeteer/puppeteer#1400]
Is there any preferred way to translate page on some language when launching browser instance or dynamically (later on)?

**Comment by schelkun** [comment]
Translation is disabled here:
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L44

**Comment by aslushnikov** [comment]
@marijanlekic you now can remove any of the default puppeteer flags with the `ignoreDefaultArgs` option of `puppeteer.launch`. You can selectively filter out puppeteer's default arguments using the `puppeteer.defaultArgs()` method.
