### ISSUE TITLE
regression: using --user-data-dir=profilepath corrupts settings and remove all extensions

### ISSUE THREAD

**Issue by kaytwo** [puppeteer/puppeteer#1404]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: MacOS 10.13.1 (17B48)
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Create an empty directory, say, `/tmp/profile`
2. Launch your installed everyday usage Chrome with that profile: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/profile/`
3. Install an extension, any extension, then quit Chrome
4. Run this code (or anything that launches puppeteer with that profile folder):

```javascript
'use strict';

const puppeteer = require('puppeteer');

(async () => {

  const datadir = '/tmp/profile/';
  const browser = await puppeteer.launch(
    {
      headless: false,
      userDataDir: datadir,
    });
  const page = await browser.newPage();
  await page.goto('https://www.nytimes.com');
  await page.screenshot({ path: 'nyt.png', fullPage: true });
  await browser.close();

})();
```
5. Run everyday usage Chrome again via `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=/tmp/profile/`

**What is the expected result?**

The extension should still be installed, the settings should not be reset

**What happens instead?**
The extension is gone, and navigating to `chrome://settings` gives the error regarding settings being reset (that links to [here](https://support.google.com/chrome/answer/3296214?visit_id=0-636464787731553555-1143793877&p=ui_automatic_settings_reset&rd=2)).

**Comment by aslushnikov** [comment]
@kaytwo this happens because of different chrome versions. Puppeteer runs a very modern version of chromium. It probably migrates the profile directory upwards.

I tried your scenario using solely Chrome Canary, and it worked fine (notice the use of `executablePath` option in `puppeteer.launch`):

```js
const puppeteer = require('puppeteer');

(async () => {
  const datadir = '/tmp/profile/';
  const browser = await puppeteer.launch({
      // Ask puppeteer to run Chrome Canary
      executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
      headless: false,
      userDataDir: datadir,
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png', fullPage: true });
  await browser.close();

})();
```
