### ISSUE TITLE
browser.closePages() feature would be a good idea

### ISSUE THREAD

**Issue by MehdiRaash** [puppeteer/puppeteer#1406]
I think mostly we need to be sure that all pages are closed.
I faced this scenario and I used it for cleaning and resetting, of course I didn't want to close the browser, _just pages_.
I intend to have browser open and staying on just default tab.
Would be a good idea to add?

**Comment by ebidel** [comment]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserpages was added in 0.13.0. you can you use that to loop through open pages and Claire them.
