### ISSUE TITLE
Puppeteer is not working at all

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1410]
Sorry for this issue of dupes, but I just can't use puppeteer.

Critical issues:
* https://github.com/GoogleChrome/puppeteer/issues/827 and https://github.com/GoogleChrome/puppeteer/issues/1325  - no fixes or suggestions, I'm getting this error almost on every run
* https://github.com/GoogleChrome/puppeteer/issues/1373 - page is crashing every time if HTTPS referer is specified, no response in issue :cry: 
* https://github.com/GoogleChrome/puppeteer/issues/1401 - unhandled rejection after crash, and no reaction (rejection) for evaluate on crashed page

What about this issues? Will it be fixed soon?

**Comment by aslushnikov** [comment]
@schelkun thank you for the heads-up. 

> #827 and #1325 - no fixes or suggestions, I'm getting this error almost on every run

Should be addressed by #1415.

> #1373 - page is crashing every time if HTTPS referer is specified, no response in issue 😢
> #1401 - unhandled rejection after crash, and no reaction (rejection) for evaluate on crashed page

I'm looking into these.

**Comment by aslushnikov** [comment]
All addressed.
