### ISSUE TITLE
waitForNavigation doesn't work after clicking a link

### ISSUE THREAD

**Issue by leo020588** [puppeteer/puppeteer#1412]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Win10x64 / Chromium 64.0.3270.0 r516713

**What steps will reproduce the problem?**

```javascript
const puppeteer = require('puppeteer');

(async () => {
	try {
		const browser = await puppeteer.launch({
			headless       : false,
			executablePath : 'D:/path/to/chromium/chrome.exe',
			userDataDir    : 'D:/path/to/userdir',
			args           : ['about:blank']
		});

		const pages = await browser.pages();
		const page = pages[0];

		page.on('load', () => console.log('Loaded: ' + page.url()));

		// goto: page1.html
		await page.goto('https://leo020588.bitbucket.io/page1.html', {waitUntil: 'load'});

		// workaround-fix
		/*await page.evaluate(() => {
			let link = document.querySelector('a');
			link.addEventListener('click', (event) => {
				event.preventDefault();
				event.stopPropagation();
				window.location = link.href;
			});
		});*/

		// click: link (page2.html)
		await page.click('a');

		//
		await page.waitForNavigation({waitUntil: 'load'});
		console.log('page2.html has arrived ... the wait is over');

		//
		await browser.close();

	} catch (e) {
		console.log(e);
	}
})();
```

**What is the expected result?**
`page2.html has arrived ... the wait is over`

**What happens instead?**
`Error: Navigation Timeout Exceeded: 30000ms exceeded`

**Note**
If I uncomment the `workaround-fix` works as espected.

**Comment by leo020588** [comment]
I also tried with chromium win64-515411 that comes with puppeteer. It does not work either.

**Comment by vsemozhetbyt** [comment]
FWIW, if the
```js
		await page.click('a');
```
is replaced by the
```js
		page.click('a');
```
the code seems to work as expected. It may be a race between `page.click()` and `page.waitForNavigation()`.

**Comment by joelgriffith** [comment]
@vsemozhetbyt is correct, this is a race condition (or really an async orchestration problem), so you'll need to have the `page.waitForNavigation()` "ready" before the click action completes.

**Comment by leo020588** [comment]
@joelgriffith how can I do that? Is what @vsemozhetbyt suggested the right way to go?

```javascript
page.click('a');
await page.waitForNavigation({waitUntil: 'load'});
```

In this way can be we sure there will be no race condition?

**Comment by ebidel** [comment]
@leo020588 please close if that addresses the issue.

You could also do this if it's easier to reason about the sequence:

```js
await page.click('a').then(() => page.waitForNavigation({waitUntil: 'load'}));
...
```

**Comment by leo020588** [comment]
@ebidel But, are they not the same?
```javascript
await page.click('a');
// and ...
page.click('a').then(() => {});
```
Both are waiting for `page.click()` to resolve.
I was thinking if it would be a good idea to implement something like:

```javascript
await page.clickLink('a', {waitForNavigationUntil: 'load'})
```

Because not waiting for `page.click()` to resolve, feels someway hackish to me.

**Comment by ebidel** [comment]
Thats slightly different. In my example you're awaiting the resolution of the entire promise chain, not just the `page.click` promise. It's the same as:

```js
(async() => {
const promise1 = Promise.resolve(1);
const promise2 = Promise.resolve(2);
const val = await promise1.then(() => promise2);  
console.log(val); // logs 2
})();
```

So in the first example below, "2" will probably log before`anotherPromiseThatTakesAwhileToResolve` resolves:

```js
page.click('a').then(() => anotherPromiseThatTakesAwhileToResolve);
console.log('2');
```

You can fix that with:

```js
await page.click('a').then(() => anotherPromiseThatTakesAwhileToResolve);
console.log('2');

//or 

page.click('a')
  .then(() => anotherPromiseThatTakesAwhileToResolve)
  .then(() => console.log('2'));

//or use await

page.click('a').then(async() => {
  await anotherPromiseThatTakesAwhileToResolve;
  console.log('2');
});
```

**Comment by leo020588** [comment]
@ebidel Sorry if this is not the place to discuss standard-javascript implementation/understanding. What suggested @vsemozhetbyt works for me. But I still think your suggestion has the same behavior as my code, I would like to clarify if am I wrong for not to confuse other readers before I close the issue.

**OPTION-1** (@leo020588) - my original code doesn't work as expected (**Error: Navigation Timeout**)
```javascript
// I read this as:
// - wait for page.click() to resolve, then after resolves ...
// - wait for page.waitForNavigation() to resolve, then after resolves ...
// - console.log
await page.click('a');
await page.waitForNavigation();
console.log('The wait is over 1');
```
**OPTION-2** (@vsemozhetbyt) - works as expected (**"The wait is over 2"**)
```javascript
// I read this as:
// - trigger page.click(), don't wait to resolve, inmediately after ...
// - wait for page.waitForNavigation() to resolve, then after resolves ...
// - then console.log"
page.click('a');
await page.waitForNavigation();
console.log('The wait is over 2');
```
**OPTION-3** (@ebidel) - doesn't work as expected (**Error: Navigation Timeout**)
```javascript
// I read this exactly the same as OPTION-1
await page.click('a').then(() => page.waitForNavigation());
console.log('The wait is over 3');
```

Edit: I like @aslushnikov's approach better, it makes more sense:
```javascript
await Promise.all([
  page.waitForNavigation(),
  page.click('a')
]);
```

**Comment by ebidel** [comment]
So from a "pure promises perspective" :p, I believe my explanation is correct but the reason 3 doesn't work for the use case is b/c the click actually kicks off a page navigation and you're `waitForNavigation` after that happens. So you hang forever.

What @joelgriffith suggested works great. Just go with that :)

**Comment by aslushnikov** [comment]
@leo020588 another way to think of `waitForNavigation` is that it waits for the navigation to start and complete.

In your case, the `await page.click('a')` returns control to the script too late - the navigation has already started.

The handy way to do this is:

```js
await Promise.all([
  page.click('a'),
  page.waitForNavigation()
]);
```

**Comment by swftvsn** [comment]
So if I understand correctly one needs to start the waitForNavigation _before_ clicking the item like this:
```ts
const promise: Promise<puppeteer.Response> = page.waitForNavigation(waitOptions)
await page.click(selector, clickOptions)
return promise
```
which is better expressed as 
```ts
await Promise.all([
  page.waitForNavigation() 
  page.click('a')
]);
```
as explained earlier.

This is somewhat counter intuitive, as we humans expect to act and then wait for something. Thus it would be nice, if the framework could provide method for this with signature

```ts
async clickAndWaitForNavigation(selector: string, clickOptions?: puppeteer.ClickOptions, waitOptions?: puppeteer.NavigationOptions): Promise<puppeteer.Response>
```

Currently I have this in my project:
```ts
async function clickAndWaitForNavigation(page: puppeteer.Page, selector: string, clickOptions?: puppeteer.ClickOptions, waitOptions?: puppeteer.NavigationOptions): Promise<puppeteer.Response> {
  return Promise.all([
    page.waitForNavigation(waitOptions),
    page.click(selector, clickOptions)
  ]).then((value: [puppeteer.Response, void]) => {
    return value[0]
  })
}
```
Which gives you all the power to click and wait, but none of the details how it should be orchestrated.

I think all projects need this so every project out there have some form of this helper method duplicated, which makes it prime candidate to be included in the library.

**Comment by cdauth** [comment]
I think the way this function works encourages bad programming patterns.

I write my tests using page objects, similar to how Selenium [suggests](https://github.com/SeleniumHQ/selenium/wiki/PageObjects) to do it. Let’s say I have two pages, one of them has a link to the second one.

```javascript
class Page1 {
    async clickLink() {
        await page.$("#link").click();
        let page2 = new Page2();
        await page2.waitUntilLoad();
        return page2;
    }
}

class Page2 {
    async waitUntilLoad() {
        page.waitForNavigation({waituntil:'networkidle2'});
    }
}
```

This code will not work with the current implementation. The workaround is to either call waitUntilLoad() before clicking the link, or to waitForNavigation in Page1.clickLink(). Both is bad, as only Page2 should need to know how to wait for itself to load. Some pages might want to wait for a selector (in which case waiting after the clicking is needed), some might want to wait for navigation (in which case waiting before the clicking is needed).

I think there should be a method to wait for networkidle2 without it being connected to a navigation action, similar to what page.waitForNavigation() was behaving like until version 0.12.0.

Also, another use case that I can think of is when a link causes some AJAX requests without navigating anywhere, and I want to wait for these AJAX requests to finish.

**Comment by cdauth** [comment]
Here is my function to wait for networkidle2 without waiting for navigation first:

```javascript
async waitForNetworkIdle(page) {
    const timeoutError = new Error('Timeout while waiting for network idle');

    await new Promise((resolve, reject) => {
        let listener = (event) => {
            if (event.name == 'networkAlmostIdle') {
                page._client.removeListener('Page.lifecycleEvent', listener);
                resolve();
            }
        };

        page._client.on('Page.lifecycleEvent', listener);

        setTimeout(() => {
            page._client.removeListener('Page.lifecycleEvent', listener);
            reject(timeoutError);
        }, 30000);
    });
}
```

**Comment by ezyang** [comment]
Coming here to say that I was also bit by this sharp edge; maybe a little doc note would be helpful!

**Comment by dowsanjack** [comment]
```
await Promise.all([
  page.click('a'),
  page.waitForNavigation()
]);

```
This still does not work for me. In my use case,  I click on the login button, it starts a spinner, makes a network request, on a successful response, takes the user to a dashboard page. 

Should I be using a different approach?

**Comment by Michaelknigth** [comment]
Hola

**Comment by swftvsn** [comment]
Hey hey, what's up?

**Comment by dowsanjack** [comment]
@aslushnikov would love to hear your thoughts

**Comment by intellix** [comment]
**Version:** 1.1.1

As mentioned in the linked issue, this seems not to work for an SPA that doesn't trigger a load event:

```ts
await Promise.all([
  page.waitForNavigation({ waitUntil: 'networkidle0' }),
  link.click(),
]);
```

Can we perhaps expose something like: `page.waitFor({ waitUntil: 'networkidle0' })`?

**Comment by x-name** [comment]
also don't work in latest

**Comment by krini** [comment]
I have the same issue in version 1.1.1

**Comment by siggerzz** [comment]
Still seeing these issues on 1.2.0

**Comment by aslushnikov** [comment]
> This still does not work for me. In my use case, I click on the login button, it starts a spinner, makes a network request, on a successful response, takes the user to a dashboard page.
> 
> Should I be using a different approach?

@dowsanjack looks like you're dealing with a single-page application. The reason the pattern doesn't work for you is because browser doesn't do any "navigation" - instead, current page DOM is modified. Thus, using `waitForNavigation` won't work.

It's not always clear if a website is doing navigation or not. A good rule of a thumb is to rely on page state instead, using methods `waitForSelector` and `waitForFunction`.

**Comment by intellix** [comment]
@aslushnikov exposing the ability to wait for 0 network requests that doesn't depend on navigation would solve this if it's feasible: 

```ts
page.waitFor({ waitUntil: 'networkidle0' })
```

Imagine you click a button and need to wait for images to load

**Comment by curran** [comment]
FWIW I came across this in the [docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions) and it seems to be the perfect solution, avoiding race conditions and ordering the execution correctly:

```js
// Set up the wait for navigation before clicking the link.
const navigationPromise = page.waitForNavigation();

// Clicking the link will indirectly cause a navigation
await page.click('a.my-link');

// The navigationPromise resolves after navigation has finished
await navigationPromise;
```

**Comment by moeHaydar** [comment]
I had the same problem. Here is the solution I went for:

```
      const sleep = (ms) => {
        return new Promise((resolve) =>
          setTimeout(resolve, ms)
        );
      }

      const requests = new Map();
      requests.set('first');
      page.on('request', (event) => {
        requests.set(event._requestId);
      })

      page.on('requestfinished', event => {
        if (requests.has('first')) {
          requests.delete('first');
        }
        requests.delete(event._requestId);
      })

      await page.click('#SOME_BYTTON');
      
      while (requests.size >1) {
        await sleep(1000);
      }
```

You can also filter requests by any criteria to make have a more efficient solution. In my case, i am interested in all requests.

**Comment by RoyiNamir** [comment]
As a new puppeteer user , I must say this is bad.
I find it hard to find out that : 

`await page.click('a').then(() => page.waitForNavigation());`

Is not like

```
await page.click('a')`
await page.waitForNavigation()
```

I know that that the first example is waiting for the whole chain
but `then` occurs after resolve
and so do `await`.

There must be something wrong going on in the `click` command that looses context or something

There is no point not admitting it.

IMO - it should be fixed or at least adhere to async await pattern and expose the RIGHT awaitable event.

**Comment by jukefr** [comment]
It would be nice to have the `ClickOptions` extend `NavigationOptions` as to be able to specify a `waitUntil` for the `.click()` method (similarly to the `.goto()` method)

**Comment by nfwyst** [comment]
you can handle new target by this: 

```javascript
const [_, popup] = await Promise.all([
      page.click('a'),
      new Promise(resolve => page.once('popup', async (popup) => {
        await popup.waitFor('selector', {
          waitUnitl: ['networkidle0', 'load', 'networkidle2', 'domcontentloaded']
        })
        resolve(popup)
      }))
    ]);
```

**Comment by isaacalves** [comment]
I tried so many things and after about an hour or so this is the only way that it worked for me:

```
await page.evaluate(() => {
  document.querySelector("your_selector").click()
})
await page.waitForNavigation()
```

**Comment by edumachah** [comment]
> I tried so many things and after about an hour or so this is the only way that it worked for me:
> 
> ```
> await page.evaluate(() => {
>   document.querySelector("your_selector").click()
> })
> await page.waitForNavigation()
> ```

This worked for me as well

**Comment by god-s-perfect-idiot** [comment]
> I tried so many things and after about an hour or so this is the only way that it worked for me:
> 
> ```
> await page.evaluate(() => {
>   document.querySelector("your_selector").click()
> })
> await page.waitForNavigation()
> ```

I had to follow a similar approach and it worked fine in some instances. But, I was still being hit by nav timeout in some instances. I was wondering if the OG approach from 2017 is still viable. (Sorry for the necro)

**Comment by m0uneer** [comment]
A workaround for single page application to wait for navigation and get the response status and data. Whether `fetch` or `XHR` is being used to do the `Ajax` request, the main idea should be the same. The following example demonstrates it with `fetch`  

```javascript
  async spaClick (selector) {
    const res = await this.eval(selector, el => {
      window.originalFetch = window.originalFetch || window.fetch
      return new Promise(resolve => {
        window.fetch = function (...args) {
          return window.originalFetch.apply(this, args)
            .then(async response => {
              resolve({
                status: response.status,
                data: await response.clone().text()
              })

              return response
            })
        }

        el.click()
      })
    })

    if (!res) throw new Error('spaClick() Navigation triggered before eval resolves!')
    return res
  }
```

```javascript
const puppeteer = require('puppeteer');
const url = 'http://www.faalkaart.nl';

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    // await Promise.all([
    //   page.waitForNavigation({ waitUntil: 'networkidle0' }),
    //   page.click('selector-that-triggers-navigation'),
    // ]);
    const response = await spaClick('selector-that-triggers-navigation')
    console.log(response) // {status, data}
    await browser.close();
})();

```

**Comment by AleksandrGoroshko** [comment]
this is work for me
`await page2.waitForResponse(response => response.status() === 200)`
