### ISSUE TITLE
using puppeteer to run unit tests of a class definition raise an "class is not defined"

### ISSUE THREAD

**Issue by sagrath23** [puppeteer/puppeteer#1414]
Hi, 

I'm currently working on a library to replace localStorage using a hybrid model of memory storage and IndexedDB (https://github.com/sagrath23/indexedDB).
I want to test my specification of IndexedDBStorage, using Jest and Puppeteer (to get a real instance of window.indexedDB), but, when i execute the test suite, i get this error: 

```
Evaluation failed: ReferenceError: IndexedDBStorage_1 is not defined

      at <anonymous>:7:45
      at step (tslib.js:129:27)
      at Object.next (tslib.js:110:57)
      at tslib.js:103:75
          at new Promise (<anonymous>)
      at __awaiter (tslib.js:99:16)
      at <anonymous>:2:36
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:66:13)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```
 and this is the test case definition: 
```javascript
fit("should create empty storage", (async (done) => {
    const browser = await puppeteer.launch()

    try {
      const page = await browser.newPage()

      //to pass __awaiter function
      await page.addScriptTag({path: "./tslib.js", content: "text/javascript"})
      //to pass IndexedDB Class definition
      await page.addScriptTag({path: "./bundle.js", content: "text/javascript"})

      // tslint:disable-next-line:only-arrow-functions
      const store = await page.evaluate(async function() {
        const store = new IndexedDBStorage("idbTest")
        await store.init()
        return store
      })

      expect(store).toBeDefined()
      expect(store.getStorage()).toBeDefined()

      await browser.close()
      done()

    } catch (err) {
      await browser.close()
      done.fail(err)
    }
  }))
```

### Enviroment to reproduce

* Puppeteer version: 0.12.0
* Platform / OS version: Windows 10
* node version: 8.9.1
* Jest version. 21.2.1

**Comment by sagrath23** [comment]
In order to make this work, i have to use the eval function 
```javascript
const store = await page.evaluate(async function() {
        const store = eval("new IndexedDBStorage.IndexedDBStorage(\"idbTest\")")
        await store.init()
        return store
      })
```
but, when i run the test, a DOMException is launched: 
```
Evaluation failed: DOMException: Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context.

      at <anonymous>:9956:38
          at new Promise (<anonymous>)
      at IndexedDBStorage../src/indexedDB/IndexedDBStorage.ts.IndexedDBStorage.open (<anonymous>:9955:16)
      at IndexedDBStorage.<anonymous> (<anonymous>:9945:51)
      at step (<anonymous>:9928:23)
      at Object.next (<anonymous>:9909:53)
      at <anonymous>:9903:71
          at new Promise (<anonymous>)
      at IndexedDBStorage../src/indexedDB/IndexedDBStorage.ts.__awaiter (<anonymous>:9899:12)
      at IndexedDBStorage../src/indexedDB/IndexedDBStorage.ts.IndexedDBStorage.init (<anonymous>:9939:16)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:66:13)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by entrptaher** [comment]
It says IndexedDBStorage_1 but your code does not have that.
Are you using babel? 
Seems like the first post had a babel mangle issue. 
In the meantime, this issue might help you, https://github.com/GoogleChrome/puppeteer/issues/1270

**Comment by sagrath23** [comment]
Hi @entrptaher , 

I'm using webpack + babel to transpile my TS code into JS. I forget to add the library attribute in output specification in my webpack.config file. 

Adding this, i can get the object defined in console, but, when i use puppeteer in my tests, i have to use the eval function in order to make my test work.

If i write my code in TS in the function that i pass as argument in page.evaluate, i get the class undefined error referenced to IndexedDBStorage_1.

any sugestion is welcome.

**Comment by entrptaher** [comment]
You can transpile the functions in seperate file 
and then evaluate the contents from that file.
Simplex is the opposite word of Complex. 
Let's keep things simple.
:D

**Comment by entrptaher** [comment]
And maybe this will help you, https://facebook.github.io/jest/docs/en/getting-started.html#using-babel

**Comment by entrptaher** [comment]
Say you have the code on another file,

```js
// build.js
async function sample() {
 const store = new IndexedDBStorage("idbTest")
   await store.init();
 return store
}

// In your puppeteer script, assuming the build.js file is in same folder of our script
const externalFile = fs.readFileSync('./build.js', 'utf8');
await page.evaluate(externalFile);
```

You can try things this way. It should work.

**Comment by aslushnikov** [comment]
closing this since this is a babel issue with a good suggested workaround.
