### ISSUE TITLE
Running simultaneous tracings

### ISSUE THREAD

**Issue by simonklb** [puppeteer/puppeteer#1418]
The API docs states that only one tracing can be active per browser. Could someone elaborate on why this is and will this ever change in the future?

Ideally I'd like to open multiple pages and start tracing on each of them simultaneously rather than running multiple browsers in parallel.

**Comment by aslushnikov** [comment]
@JoelEinbinder isn't tracing recording the whole browser all in once? (if this is the case, why do we have tracing under the `page`?)

**Comment by aslushnikov** [comment]
>  I'd like to open multiple pages and start tracing on each of them simultaneously rather than running multiple browsers in parallel.

@paulirish is this something we can do?

**Comment by JoelEinbinder** [comment]
If tracing was a browser method, what page would screenshots be taken of?

**Comment by paulirish** [comment]
Tracing is designed to be browser wide. There is currently no ability to have multiple overlapping traces and I don't expect us to add it anytime soon.

There is a hack implemented to choose which rendering process we take screenshots of. ~It chooses the foreground tab.~ screenshots are only available for the `page` where tracing is invoked.

**Comment by simonklb** [comment]
Thanks, that answers the question for me. Do you have any tips on how to make the tracing a bit more lightweight though?

I'm currently trying out different approaches of measuring page speed and using Puppeteer is the most accurate solution I've found so far. The only problem I have with it is that it's hard to scale without making it costly or impacting the results. You have to be careful when running multiple browsers and tracings in parallell so that they do not hog too CPU.

Net bandwidth is also a problem of course, but that's a totally different beast which I guess is a problem with whatever solution I go with.

**Comment by ArnaudBarre** [comment]
@paulirish 

> There is a hack implemented to choose which rendering process we take screenshots of. It chooses the foreground tab.

I have something like that: 
```ts
const page1 = await browser.newPage();
const page1.tracing.start({ screenshots: true, path: "trace.json" });
// do stuff with page1
const page2 = await browser.newPage();
await page2.bringToFront();
// do stuff with page2
await page1.tracing.stop();
```
But screenshots are only taken on page 1

Is there any way of getting a recording of across multiple tabs?

**Comment by paulirish** [comment]
> Is there any way of getting a recording of across multiple tabs?

the trace by default includes ALL pages/processes. however the screenshot thing doesn't. and probably won't ever.

**Comment by OrKoN** [comment]
Closing this as we won't like to work on this any time soon.
