### ISSUE TITLE
FR: Add dedicated method to page to click and wait for navigation

### ISSUE THREAD

**Issue by swftvsn** [puppeteer/puppeteer#1421]
As discussed in #1412 the current way that click and wait for navigation pattern must be coded is somewhat counter intuitive. It is needed in almost all of the cases I can think of, so it would be nice if puppeteer would provide it.

The signature should be:
```ts
clickAndWaitForNavigation(selector: string, clickOptions?: puppeteer.ClickOptions, waitOptions?: puppeteer.NavigationOptions): Promise<puppeteer.Response>
```

And the implementation could be:
```ts
async function clickAndWaitForNavigation(selector: string, clickOptions?: puppeteer.ClickOptions, waitOptions?: puppeteer.NavigationOptions): Promise<puppeteer.Response> {
  return Promise.all([
    this.waitForNavigation(waitOptions),
    this.click(selector, clickOptions)
  ]).then((value: [puppeteer.Response, void]) => {
    return value[0]
  })
}
```
where `this` is `puppeteer.Page`.

Whaat do you think?

**Comment by alixaxel** [comment]
I think this would be helpful, or at least it should be boldly documented... It's so easy to fall into this trap.

**Comment by aslushnikov** [comment]
I'd appreciate if anyone sends a PR to update documentation.

**Comment by alixaxel** [comment]
@aslushnikov Something like this (English is not my native language)?

> Bare in mind that if `click()` triggers a navigation event and there's a separate `page.waitForNavigation()` promise to be resolved, you may end up with a race condition that yields unexpected results. The correct pattern for click and wait for navigation is the following:

```javascript
await Promise.all([
  this.waitForNavigation(waitOptions),
  this.click(selector, clickOptions),
]).then((value) => {
  return value[0];
});
```

**Comment by symphony2014** [comment]
even though, that still doesn't work,  and the page successed to navigate to new page, but ,exception was throwed,**:(node:12448) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded**
```
const puppeteer = require('puppeteer');

(async () => {
    var url={test:{
        login:"http://er.adminn.dev.ipsos.com.cn/",
        projectMain:"http://er.adminn.dev.ipsos.com.cn/#/admin/project"
    }}
    var waitOptions={waitUntil:"load"}

    const browser = await puppeteer.launch({
        headless:false,
        devtools:false,
    });
  const page = await browser.newPage();
  await page.setViewport({width:1048,height:800});
  await page.goto(url.test.login);
 await page.waitForSelector("#name")
 await page.$$eval("#name",elements=>{
     elements[0].value="";
 })
 await page.$$eval("#password",elements=>{
     elements[0].value="";
 })
 await page.type("#name","system")
 await page.type("#password","system")

await Promise.all([
    page.waitForNavigation(waitOptions),
    page.click("[type=submit]"),
]);

//await page.goto(url.test.projectMain);

await page.waitForSelector(".nav-link");
await page.click('.nav-link a:nth-of-type(3)');
await page.select("select[name=clientId]","170627135337686269")
const contents=await page.$$("tr:nth-of-type(6) td:nth-of-type(7) a:nth-last-of-type(1)");


//await page.waitForSelector("");
//   await page.waitForSelector(".node-value:nth-last-of-typ(1)");
    // await page.waitFor(()=>{
    //     var nodes=page.$$(".node-value");
    //     var last= nodes[nodes.length-1]
    //     return last.children[0].innerText=="Export"


    // })
//     await page.click('.node-value:nth-last-of-type(1)')
  
    await browser.close();
})();
```

**Comment by awesomenkj** [comment]
same here

**Comment by putuoka** [comment]
same here
using waitForNavigation, promise all, and waitForFunction doesn't work. The page loaded after submit not in full DOM yet the next command has executed. so no other choice only use .waitFor() is working for now

**Comment by juancarlosfarah** [comment]
I'm experiencing the same issue as @xsmartweb.

This my code:

```javascript
// this code always times out
const puppeteer = require('puppeteer');
(async () => {
  try {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('http://graasp.eu/ils/5a9d467e45aca55d33eafce6/?lang=en', {waitUntil: 'networkidle2'});
    await Promise.all([
      page.click('#nav > li:nth-child(2) > a'),
      page.waitForNavigation({waitUntil: 'networkidle2'}),
    ]);
    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

Which gives error:

```
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (.../node_modules/puppeteer/lib/NavigatorWatcher.js:71:21)
    at <anonymous>
```

Nevetheless, if I switch `page.waitForNavigation({waitUntil: 'networkidle2'})` to `page.waitFor(10000)`, it works as expected.

```javascript
// this code works as expected
const puppeteer = require('puppeteer');
(async () => {
  try {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('http://graasp.eu/ils/5a9d467e45aca55d33eafce6/?lang=en', {waitUntil: 'networkidle2'});
    await Promise.all([
      page.click('#nav > li:nth-child(2) > a'),
      page.waitFor(10000),
    ]);
    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by aslushnikov** [comment]
@juancarlosfarah your click doesn't do any navigation. Rule of a thumb: if clicking a button doesn't change page URL, then there's no navigation for sure.

For this reason, the `page.waitForNavigation` doesn't work: it's waiting for a navigation to happen sometime in future, and it doesn't.

**Comment by juancarlosfarah** [comment]
@aslushnikov, thanks for the explanation. Got it. In my case I was waiting for the AJAX request to finish. I didn't really see a particular way of doing that in Puppeteer, so I thought it could be encapsulated in the `page.waitForNavigation` method.

**Comment by aslushnikov** [comment]
@juancarlosfarah yes, AJAX is tricky.

If you know AJAX url, you can use `request` events to wait for the response.
Most of the time, though, you'd like a page to render something in response to mouse click. So
I'd suggest to wait for certain elements to appear on the page with `page.waitForSelector` method.

**Comment by juancarlosfarah** [comment]
@aslushnikov, perfect. Thanks for the tip!

**Comment by lgrzybowski** [comment]
@juancarlosfarah 
One solution if you waiting for ajax made my jquery will be writing own function. Something like this:
```
const waitForAjax = async (page) => {
    await page.evaluate(() => {
        return new Promise((resolve, reject) => {
            const times = 10;
            let i = 0;
            const interval = setInterval(() => {
                const ajaxCalls = jQuery.active;
                if (ajaxCalls === 0) {
                    clearInterval(interval);
                    resolve();
                } else if (i === times) {
                    reject('Wait for Ajax function timeout')
                }
                i++;
            }, 500)
        })
    });
};
```
It's working 👌 for me :)
