### ISSUE TITLE
Request for Documentation of ResourceTypes

### ISSUE THREAD

**Issue by quinton-ashley** [puppeteer/puppeteer#1424]
Just wanted to say great job to all the developers of puppeteer, it's really amazing!  I wish GitHub had a compliments page in addition to an Issues page, a star is so impersonal.  Puppeteer is easy to use and just so fun to run with {headless: false} and watch the automation happen.

Anyway I digress, my request is that ResourceTypes be defined, examples would be nice.  Maybe it's already documented in the DevTools docs so a link would suffice but I couldn't find it.  Also on a related note, is there a way/how would one load just the meta tags of a page and nothing else?

> Contains the request's resource type as it was perceived by the rendering engine. ResourceType will be one of the following: document, stylesheet, image, media, font, script, texttrack, xhr, fetch, eventsource, websocket, manifest, other.

**Comment by aslushnikov** [comment]
> Just wanted to say great job to all the developers of puppeteer, it's really amazing! I wish GitHub had a compliments page in addition to an Issues page, a star is so impersonal. Puppeteer is easy to use and just so fun to run with {headless: false} and watch the automation happen.

@quinton-ashley thank you for your warm words! We really appreciate it.

> Anyway I digress, my request is that ResourceTypes be defined, examples would be nice. Maybe it's already documented in the DevTools docs so a link would suffice but I couldn't find it. Also on a related note, is there a way/how would one load just the meta tags of a page and nothing else?

I think I might misunderstand something. Different values of the `resourceType` property are stated in the doc (and you quoted them). There's also an [image-blocking example](https://github.com/GoogleChrome/puppeteer/blob/master/examples/block-images.js) that demonstrates how to use it on practice.

What else would you like to see in the doc?

**Comment by alteredorange** [comment]
I was hoping ad would be a resource type.

**Comment by quinton-ashley** [comment]
I guess I'd just like the docs to say what qualifies as an image vs media or what a texttrack, fetch, eventsource, websocket, manifest, or other is.  I found out you can view the resourceType in the Chrome console under sources and network so I guess people can just learn by looking at them there.

**Comment by GuilloOme** [comment]
@quinton-ashley, like you, I was searching for this info some times ago…  You can find some answers here: https://stackoverflow.com/questions/47083776/how-is-defined-resourcetype-value-provided-by-the-devtool-protocol
and there: 
https://stackoverflow.com/questions/47083776/how-is-defined-resourcetype-value-provided-by-the-devtool-protocol

**Comment by aslushnikov** [comment]
> I guess I'd just like the docs to say what qualifies as an image vs media or what a texttrack, fetch, eventsource, websocket, manifest, or other is.

@quinton-ashley ah indeed, there are no easy rules how these types are inferred. As @GuilloOme pointed out, there's some logic written in the Blink rendering engine, but it's not spec'ced.

I'd say the best approach here is trial-and-error.
