### ISSUE TITLE
how can i install puppeteer

### ISSUE THREAD

**Issue by plh97** [puppeteer/puppeteer#1426]
i use PUPPETEER_SKIP_CHROMIUM_DOWNLOAD to skip  download chromium
i success to install puppeteer , 
but how can i install chromium
 i use `wget https://storage.googleapis.com/chromium-browser-snapshots/Mac/497674/chrome-mac.zip`
i can dowmload it ,there is no problem with it

**Comment by plh97** [comment]
but while i run node 
```js
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
```
it throw this

**Comment by H91011** [comment]
if you chose skip chromium download you try this : 

` const browser = await puppeteer.launch({ executablePath   : 'path/to/chromium"  });`

**Comment by plh97** [comment]
oh .your says pretty  right ,i'ill try this good idea

**Comment by plh97** [comment]
it can't work but.............

**Comment by ghost** [comment]
Two choices for mainland China users:
1. cnpm in place of npm / yarn
2. set `PUPPETEER_DOWNLOAD_HOST = https://npm.taobao.org/mirrors`

**Comment by plh97** [comment]
@chanjsq thanks i fix that problem 
use my hand to install chromium 
&&
```js
  const browser = await puppeteer.launch({
    executablePath : 'C://Users/33318/AppData/Local/Chromium/Application/chrome.exe'
  });
```
suddently found that it is a easy problem ,cost me one day to solve it

**Comment by ghost** [comment]
@pengliheng My pleasure. 😊 If you solved the problem, you can close the issue now. If any more questions, please continue reply.

**Comment by gwuhaolin** [comment]
here has a lib [chrome-finder](https://github.com/gwuhaolin/chrome-finder) can find installed chrome path auto:

```js
const chromeFinder = require('chrome-finder');
await puppeteer.launch({
    executablePath : chromeFinder()
});
```

**Comment by robin-shine** [comment]
> here has a lib [chrome-finder](https://github.com/gwuhaolin/chrome-finder) can find installed chrome path auto:
> 
> ```js
> const chromeFinder = require('chrome-finder');
> await puppeteer.launch({
>     executablePath : chromeFinder()
> });
> ```

works for me~
