### ISSUE TITLE
Tracing screenshot size differs 

### ISSUE THREAD

**Issue by utix** [puppeteer/puppeteer#1427]
I get issue to compute the speed index using `speedline` module.
The size of the screenshots into the tracing file are not all the same.
The strange thing is that the issue occurs around 66% times, running 3 times the same code, the issue occurs twice.

### Steps to reproduce

* Puppeteer version: puppeteer@0.13.0
* Platform / OS version:
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

```
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');
const speedline = require('speedline');

async function run() {
    const iPhone = devices['iPhone 6'];
    const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
    const filename = 'trace.json';

    const page = await browser.newPage();
    await page.emulate(iPhone);
    try {
        await page.tracing.start({path: filename, screenshots: true});
        await page.goto('https://www.amazon.fr');
        await page.tracing.stop();
        const results = await speedline(filename);
        console.log('Speed Index value:', results.speedIndex);
    } catch (e) {
        console.error(e);
    }
    browser.close();
}

run();
```

**What is the expected result?**
Image should all be 375x667 according to the `DeviceDescriptors.js`file
```
{
    'name': 'iPhone 6',
    'userAgent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1',
    'viewport': {
      'width': 375,
      'height': 667,
      'deviceScaleFactor': 2,
      'isMobile': true,
      'hasTouch': true,
      'isLandscape': false
    }
  },

```

**What happens instead?**
The two first pictures size are  376x667, triggering an exception `Images have different sizes!` into ImageSSIM

**Comment by softwarerero** [comment]
I ran into the same issue today. This happens also when setting the device or viewport at all.

**Comment by aslushnikov** [comment]
I can repro this every other time. Seems to be a chromium bug.

**Comment by josenobile** [comment]
headless: false //not happening too often
headless: true, 100% reproducible.

**Comment by ckrishk** [comment]
Hi, 
You there be an update on this issue, am running into this often even on headless false on docker

**Comment by utix** [comment]
I reproduce the issue with `"puppeteer": "^15.1.1",`
Very easy to reproduce with the code provided, no every time but quite often

```
const puppeteer = require('puppeteer');
const speedline = require('speedline');

async function run() {
    const iPhone = puppeteer.devices['iPhone 6'];
    const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
    const filename = 'trace.json';

    const page = await browser.newPage();
    await page.emulate(iPhone);
    try {
        await page.tracing.start({path: filename, screenshots: true});
        await page.goto('https://www.amazon.fr');
        await page.tracing.stop();
        const results = await speedline(filename);
        console.log('Speed Index value:', results.speedIndex);
    } catch (e) {
        console.error(e);
    }
    browser.close();
}

run();
```

**Comment by utix** [comment]
Trace example https://www.dropbox.com/s/g6gtavb8hauhufp/trace.1656359331733.json?dl=0

**Comment by utix** [comment]
How can I help to confirm it ?

**Comment by jrandolf** [comment]
I am no longer able to reproduce.
