### ISSUE TITLE
Waiting for element in shadow DOM to show up

### ISSUE THREAD

**Issue by wwwillchen** [puppeteer/puppeteer#143]
I wrote a simple script to take a screenshot for DevTools setting screen
```javascript
browser.newPage().then(async page => {
    await page.navigate('http://localhost:8090/front_end/inspector.html');
    await page.waitFor(3000);
    await page.press('F1');
    await page.waitFor(/** Wait for an element in shadow DOM with class help-window-main*/);
    const screenshot = await page.screenshot({path: 'devtools.png'});
    browser.close();
});
```

I'm trying to wait for an element in shadow DOM before I take a screenshot. I want to do something like:
```javascript
await page.waitFor(`document.querySelector('.flex-auto').shadowRoot.querySelector('.help-window-main')`)
```

Seems related to https://github.com/GoogleChrome/puppeteer/issues/91 but I don't think the current solution addresses this use case (?)

**Comment by aslushnikov** [comment]
Yes, when the #91 is fixed you'll be able to wait for function. Closing this as a duplicate of #91
