### ISSUE TITLE
Chromium not installed in Docker by yarn

### ISSUE THREAD

**Issue by peterbe** [puppeteer/puppeteer#1430]
### Steps to reproduce

**Tell us about your environment:**
Docker version 17.09.0-ce, build afdb6d4

* Puppeteer version:
0.13.0

* Platform / OS version:
n/a

* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

[Here's a successful build on TravisCI](https://travis-ci.org/peterbe/minimalcss/builds/304846761)
Based on [this Dockerfiler](https://github.com/peterbe/minimalcss/blob/7e891c40f18f055a63fb6612588b99d0a1af53d2/Dockerfile)

The bad thing is that I have to kinda install `puppeteer` twice. 
Note how it first runs `RUN yarn` which installs the packages listed in `package.json` and one of them is puppeteer 0.13. 
However, if I don't run `RUN yarn add puppeteer` I would get this error:
```
▶ docker container run -it --name minimalcss -t minimalcss:tests
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

That extra line of `RUN yarn add puppeteer` 

**What is the expected result?**

That, in Docker, running `yarn` based on a `yarn.lock` and `packages.json` that lists puppeteer, it would install Chromium.

**What happens instead?**

Chromium is not installed. 

I suspect it's user error and that there's something in the documentation about `yarn.lock` etc. in linux that I missed. Perhaps there's value in making this more obvious for newbies like me.

**Comment by ebidel** [comment]
`RUN yarn` may be creating different lockfile than the one you're adding to the image. This may help: https://github.com/yarnpkg/yarn/issues/749#issuecomment-344919948

**Comment by peterbe** [comment]
It say:

> "Note: It's better to install native dependencies, if any, via a separate RUN command coming before yarn install."

Hmm. That's what I had to do and I don't know why. 

So it could very well be user error but I find it odd that if you have `puppeteer` in the `package.json` and mentioned in `yarn.lock` it should be enough. Is the `yarn.lock` somehow preventing installation of Chromium? If so what is the conditional for that?

The `yarn.lock` is basically a snapshot of the `package.json` that specifies exact versions. But what in `yarn add puppeteer` triggers the Chromium install, that doesn't happen when you just have `yarn.lock` and `yarn install`.

**Comment by aslushnikov** [comment]
@peterbe I'd recommend asking in the yarn repo; it looks like we don't have many yarn gurus around here.
