### ISSUE TITLE
page.evaluate - not working as expected

### ISSUE THREAD

**Issue by do-web** [puppeteer/puppeteer#1433]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v.0.13
* Platform / OS version: OSX
* URLs (if applicable):

**What steps will reproduce the problem?**

`  
const result = await page.evaluate(() => {
    return document.querySelector('button').getBoundingClientRect();
});

console.log(result)
`

**What is the expected result?**

Result should be DOMRect Object.

**What happens instead?**

An empty object is the result.

**In version 0.12 all works fine**

**Comment by vsemozhetbyt** [comment]
I am not sure, but it can be caused by the https://github.com/GoogleChrome/puppeteer/pull/1098.
You can try this:
```js
JSON.parse(await page.evaluate(
  () => JSON.stringify(document.querySelector('button').getBoundingClientRect())
))
```

**Comment by aslushnikov** [comment]
The ClientRect is known to misbehave with DevTool's home-grown stringifier.
Surprisingly, I didn't find upstream bug for this, so filed one: https://bugs.chromium.org/p/chromium/issues/detail?id=787154

**Comment by aslushnikov** [comment]
So the outcome (based on the upstream bug discussion) is that this is not a real object and thus we can't properly stringify it.

I don't think there's much else we can do for now; we might invest more in the problem if there's much more demand.

**Comment by parinaya-007** [comment]
I am also facing the same problem. 
page.evaluate() returning empty object.
