### ISSUE TITLE
keyboard.press not working as expected

### ISSUE THREAD

**Issue by alias8** [puppeteer/puppeteer#1436]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: macOS High Sierra

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```
const browser = await puppeteer.launch({ headless: false })
const page = await browser.newPage()

await page.goto('http://localhost:3000')
await page.type("input[type=email]", "abcdefghijklmnopqrstuvwxyz")
await page.keyboard.press("Backspace", {delay: 1000});
await page.waitFor(5000);
await browser.close();
```

**What is the expected result?**
That the backspace key will be held for 1 second, deleting more than one character from the string

**What happens instead?**
Only one character is deleted, 'z'. This would simulate a single press of the backspace key without holding it for 1 second. Perhaps I am misunderstanding the documentation, but how can we simulate a key (backspace, arrowRight etc) being held down for a time period? Thanks for any assistance

**Comment by aslushnikov** [comment]
@alias8 when the key is long-pressed, it's OS responsibility to issue subsequent events. Puppeteer input emulation doesn't operate on such a low level.

If you want to precisely emulate the long-holding of the `backspace` keyboard, then you'll have to issue multiple [`keyboard.down`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#keyboarddownkey-options) calls. All but the very first backspace event will be dispatched with the [`repeat`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat) attribute set to true, which is indistinguishable from what the OS actually does.

```js
// Issue 10 Backspace events, 9 last ones will be with "repeat" set to true 
for (let i = 0; i < 10; ++i) {
  page.keyboard.down('Backspace');
}
```

cc @JoelEinbinder

**Comment by alias8** [comment]
@aslushnikov thanks for the fast reply :)

When using your solution, it appears to press the backspace button 10 times very fast. I needed to simulate the user pressing the "ArrowRight" key for a few seconds (the duration is not important). For anyone else with a similar problem, I have used this:

```javascript
for (let i = 0; i < 20; i++) {
    await page.keyboard.press("ArrowRight", {delay: 50}); 
}
```

There is an overhead to the loop so the total duration of the continuous button press is something like 1200ms instead of 1000ms (20 loops * 50ms per loop)

**Comment by AdnanAliArshadtx** [comment]
Can someone answer this?
https://stackoverflow.com/questions/74606701/alert-dialog-not-closing-in-puppeteer
