### ISSUE TITLE
Timeout option in puppeteer.launch not working

### ISSUE THREAD

**Issue by knowlet** [puppeteer/puppeteer#1438]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Ubuntu 16.04.3 LTS / macOS 10.13.2
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. The code
```js
async init() {
    // const browser = await puppeteer.launch();
    this.browser = await puppeteer.launch({
        timeout: 120000,
        headless: false,
    });

    console.log('Warning up...');

    this.page = await this.browser.newPage();
    this.page.setViewport({ width: 1024, height: 768 });
    return true;
}

async crawl_list(url) {

    console.log('Getting list...');

    try {
        await this.page.goto(url);
        await this.page.waitFor('.bodyMain li a');
    } catch (err) {
        console.log('Timeout! Get list failed.', err);
    }

    const list = await this.page.evaluate(() => {
        let _list = [];
        const links = document.querySelectorAll('.bodyMain li a');
        links.forEach(function(e, i) {
            _list.push(e.href);
        });
        return _list;
    });

    // console.log('url list:', list);

    return list;
}
```

2. According to the [document](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions), `timeout` <number> Maximum time in milliseconds to wait for the Chrome instance to start. Defaults to `30000` (30 seconds). Pass `0` to disable timeout.

3. But the timeout option in `waitFor` is functional.
```js
await this.page.waitFor('.bodyMain li a', { timeout: 120000 });
```

**What is the expected result?**
Wait timeout for `120000` milliseconds.

**What happens instead?**
```
Warning up...
Getting list...
Timeout! Get list failed. Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/Users/knowlet/crawler/node_modules/puppeteer/lib/FrameManager.js:593:58)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by aslushnikov** [comment]
@knowlet the timeout option you're referring to is for the browser startup. This is used when puppeteer starts a browser instance and waits for it to initialize. 

The exception you have happens in the `page.waitFor` function. It is unrelated to the browser startup timeout; you'll have to define it explicitly for every `page.waitFor` call you do.

Hope this helps!

**Comment by ghost** [comment]
@aslushnikov I would like to make this a feature to where you can set a default timeout for all waitFor calls instead of having to do it explicitly for every one. Could you provide me with a few pointers and info on how to get started?

**Comment by presencewebdesign** [comment]
Looks like i was a memory issue for me, I increased the memory in Google Cloud function console
