### ISSUE TITLE
User agent in trace from page.tracing is incorrect

### ISSUE THREAD

**Issue by Khady** [puppeteer/puppeteer#1440]
When using the tracing facilities from `Page.tracing`, the user agent reported in the trace is incorrect. I checked the logs of the webserver and the user agent used for the request is correct. So only the trace is not good.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3b60ad1c39133ed45f72058353f6b6bb26e6b627
* Platform / OS version: debian strectch
* URLs (if applicable): http://halva.khady.info but any url will work

**What steps will reproduce the problem?**

1. save the file bellow as trace.js
2. launch `nodejs trace.js http://halva.khady.info`
3. check the last line of the output, it is not the user agent defined in the code

trace.js:

```javascript
'use strict';

const puppeteer = require('puppeteer');

const URL = process.argv[2];

(async () => {
  console.log("processing url", URL);
  process.on("uncaughtException", (e) => {
    console.error("Unhandled exeption:", e);
    process.exit(1);
  });
  process.on("unhandledRejection", (reason, p) => {
    console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
    process.exit(2);
  });
  const args = [
    "--disable-setuid-sandbox",
    "--no-sandbox",
  ];
  const options = {
    args,
    headless: true,
  };
  const browser = await puppeteer.launch(options);
  const page = await browser.newPage();
  await page.setUserAgent("demo_ua");
  await page.tracing.start({path: "trace.json"});
  const res = await page.goto(URL, { timeout: 30000, waitUntil: "load" });
  await page.tracing.stop();
  await page.close();
  await browser.close();
  const j = require("./trace.json");
  console.log(j["metadata"]["user-agent"]);
})();
```

**What is the expected result?**

```
$ nodejs trace.js http://halva.khady.info
processing url http://halva.khady.info
demo_ua
```

**What happens instead?**

```
$ nodejs trace.js http://halva.khady.info
processing url http://halva.khady.info
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/64.0.3264.0 Safari/537.36
```

**Comment by aslushnikov** [comment]
This is an upstream bug in devtools protocol/tracing. Filed https://crbug.com/787630

**Comment by aslushnikov** [comment]
Given the response in the upstream bug, this works as expected.
