### ISSUE TITLE
Puppeteer is working slower than PhantomJS

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1444]
I have tested puppeteer vs phantomjs using http://google.com as url . Puppeteer is too slow compared to phantomjs.
puppeteer = 8004 ms
phantomjs = 7 ms

Code for phantomjs:
phantom.js
```js
var path = require('path')
var childProcess = require('child_process')
var phantomjs = require('phantomjs')
var binPath = phantomjs.path;
var address = process.argv[2];
var childArgs = [
	path.join(__dirname, 'phantomjs-script.js'),
  	address
];
var child = childProcess.execFile(binPath, childArgs, {timeout:60000}, function(err, stdout, stderr) {
  console.log(stdout);
})
```

phantomjs-script.js
```js
var start = new Date().getTime(), end;
console.log('start: ',start);

var page = require('webpage').create(),
    system = require('system'),
    address, screenWidth, screenHeight;
try {
    address = system.args[1];
    screenWidth = 1000;
    screenHeight = 700;

    page.viewportSize = {width: screenWidth, height: screenHeight};
    page.settings.userAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36";
    page.open(address, function (status) {
        console.log('')
        if (status !== 'success') {
            console.log('Unable to load the address!');
            phantom.exit();
        } else {
            page.render("phantom.png");
            phantom.exit();
        }
    });
} catch(e){
    phantom.exit()
}

end = new Date().getTime();
console.log('end: ', end);
console.log((end-start)/1000);
```

Code for puppeteer
puppeteer.js

```js
var path = require('path');
var childProcess = require('child_process');
var address = process.argv[2];
var childArgs = [
	path.join(__dirname, 'puppeteer-script.js'),
  	address,
  	foldername
];
var child = childProcess.execFile('node', childArgs, {} , function(err, stdout, stderr) {
	console.log(stdout);
});
```

puppeteer-script.js

```js
var start = new Date().getTime(), end;
console.log('start: ',start);
const puppeteer = require('puppeteer');
var address, foldername, screenWidth, screenHeight;
(async() => {

	const browser = await puppeteer.launch();
	const page = await browser.newPage();	

	try {
		address = process.argv[2];
        screenWidth = 1000;
        screenHeight = 700;

		await page.setViewport({width:screenWidth, height: screenHeight});
		await page.goto(address).then(async (msg) => {
            console.log('--------------------------------------------');
            if (msg.ok !== true) {
                console.log('Unable to load the address!');
                await browser.close();
            } else {
                await page.screenshot({path: 'puppeteer.png'});
                await browser.close();                
            }
        });
    } catch(e){
        console.log('INSIDE CATCH EXCEPTION!');
        await browser.close();
	}
    end = new Date().getTime();
    console.log('end: ', end);
    console.log((end-start)/1000);

})();
```

I need to speed up puppeteer.

**Comment by ebidel** [comment]
Your puppeteer-script.js takes ~600ms for me:

<img width="1329" alt="screen shot 2017-11-21 at 10 55 41 am" src="https://user-images.githubusercontent.com/238208/33090972-9dbd4ae8-ceaa-11e7-8a0f-dd26a01ddaed.png">

**Comment by ghost** [comment]
@ebidel , does node version plays role in puppeteer(it is still slow)? Or should I install any software(like Chromium)?

**Comment by ebidel** [comment]
It shouldn't have a noticeable difference. What version are you using?

**Comment by ghost** [comment]
0.13.0

**Comment by ebidel** [comment]
Sorry, I meant what version of node. What platform are you on? 

We'll need more to help diagnosis if there's an issue. How do we reliably reproduce?

**Comment by Everettss** [comment]
For me 7ms seems a little bit too unrealistic. 
I don't know how phantomjs works but check what's the execution time if you @abdurashidv move `console.log((end-start)/1000);` inside `page.open` callback like this: 

`phantomjs-script.js`
```javascript
var start = new Date().getTime(), end;
console.log('start: ',start);

var page = require('webpage').create(),
    system = require('system'),
    address, screenWidth, screenHeight;
try {
    address = system.args[1];
    screenWidth = 1000;
    screenHeight = 700;

    page.viewportSize = {width: screenWidth, height: screenHeight};
    page.settings.userAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36";
    page.open(address, function (status) {
        console.log('')
        if (status !== 'success') {
            console.log('Unable to load the address!');
            phantom.exit();
        } else {
            page.render("phantom.png");
            phantom.exit();
        }
        end = new Date().getTime();  //  <- move here
        console.log('end: ', end);
        console.log((end-start)/1000);
    });
} catch(e){
    phantom.exit()
}
```

**Comment by ghost** [comment]
@ebidel 
windows 10, 8GB RAM, core i5
node v7.8.0

**Comment by icarusmiles** [comment]
@abdurashidv Instead of spawning a new chrome instance maybe connect to an existing already launched instance. It's helped mine.

**Comment by ghost** [comment]
@miles-collier 
Can you give sample code?

**Comment by icarusmiles** [comment]
`const browser = await puppeteer.connect({browserWSEndpoint: "ws://<ip>:<port>/devtools/page/<pageid>" });`

As per the documentation:
`You can find the webSocketDebuggerUrl from http://${host}:${port}/json/version.`

**Comment by xprudhomme** [comment]
Guys, @abdurashidv , there is something huge you seem to have missed here :

The asynchronous nature of Javascript, and the sames applies for PhantomJS. 

Exactly as what @Everettss said, the end time measure should be done within the page.open callback. Let's remember PhantomJS main issue: the JS callback hell, and that's why CasperJS came to the rescue..

Even if the "end = new Date().getTime();" line is written at the end of the file, it will be executed right after the "console.log('start: ',start);" line, because of the way the Javascript's Call Stack + Event loop works. Thereby resulting in only 7ms.

[A nice explained article: ](https://blog.sessionstack.com/how-does-javascript-actually-work-part-1-b0bacc073cf)

**Comment by he11b0rn** [comment]
Hello, i have similar problem, slow loading page.

Code:

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: true});
    const page = await browser.newPage();
    console.time('timeLoadPage');
    await page.goto('https://news.ycombinator.com');
    console.timeEnd('timeLoadPage');
    await page.pdf({path: 'hn.pdf', format: 'A4'});
    await browser.close();
})();
```

timeLoadPage: ~21sec

OS: Win7, Win 10
Node: 8.9.1

**Comment by xprudhomme** [comment]
@he11b0rn : This is more likely due to your internet connection or your computer.

I've run your exact code, and got: 
timeLoadPage: 735.937ms

**Comment by Everettss** [comment]
@he11b0rn If you want to benchmark Puppeteer you should get rid off network layer and test pages on localhost.

**Comment by he11b0rn** [comment]
@Everettss, @Xavatar Thanks for the answers, i have a problem with environment.

**Comment by ghost** [comment]
@Everettss 
I have implemented phantom timing page.open( ... ) and it is showing exact time. Phantom and puppeteer are same but in some occasions puppeteer is better than phantomjs.

**Comment by ghost** [comment]
@ebidel 
It is running slow on the server. 
Specs: Processor: Intel(R) Xeon(R) CPU E5-4650, RAM: 8GB, System Type: 64-bit Operating System

Node version: 7.10

Can you give me advice in enhancing timing of puppeteer?

**Comment by xprudhomme** [comment]
@abdurashidv : You can improve loading time by disabling images loading.

**Comment by ebidel** [comment]
@abdurashidv not sure what to suggest since you also said:

> Phantom and puppeteer are same but in some occasions puppeteer is better than phantomjs.

So that's even more confusing. I don't have a windows machine handy to test, but @he11b0rn was also on Windows. That's the only thing I see at this point, but I wouldn't expect that to be an issue.

**Comment by xprudhomme** [comment]
Since this issue was opened because of a lack of understanding of Javascript's asynchronous nature, it's more likely time to close it ...
