### ISSUE TITLE
Doesnt work in Gooogle cloud functions and app engine due to missing shared library: libpangocairo-1.0.so

### ISSUE THREAD

**Issue by ManiDoraisamy** [puppeteer/puppeteer#1448]
Works in my local machine. But not in production on cloud functions and app engine (flex environment):

Error: Failed to launch chrome! /user_code/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md at onClose (/user_code/node_modules/puppeteer/node6/Launcher.js:262:14) at Interface.helper.addEventListener (/user_code/node_modules/puppeteer/node6/Launcher.js:251:50) at emitNone (events.js:91:20) at Interface.emit (events.js:185:7) at Interface.close (readline.js:320:8) at Socket.onend (readline.js:109:10) at emitNone (events.js:91:20) at Socket.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11)

I reported in cloud functions and they said it has to be fixed in puppeteer: https://issuetracker.google.com/issues/68887435

**Comment by ManiDoraisamy** [comment]
Error from app engine (flex -Node.js):
/app/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

**Comment by Garbee** [comment]
This is a problem with chromium dependencies. Nothing to be fixed here. You need to host the application some other way. The issue tracker has previous issues on this exact topic. Can't look them up since I'm mobile, but should be relatively easy to find.

**Comment by joelgriffith** [comment]
This sole issue has been the motivation for https://github.com/joelgriffith/browserless and its sibling service. Should work anywhere Docker is natively supported

**Comment by Garbee** [comment]
If it is docker then you need to make sure the right [Chromium dependencies](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch) are installed in your image. Still nothing I can tell we need to do about that internally.

The library issues aren't something Puppeteer does or has control over. This is upstream in Chromium. A more accurate issue description is "Issue running Chromium on App Engine and Cloud Functions". Since, even if Puppeteer isn't involved and you're just trying to run Chromium headless on them, it will still fail in the same method.

**Comment by ManiDoraisamy** [comment]
Thanks for the link, Jonathan! I followed ebidel's
https://github.com/ebidel/try-puppeteer from your link and got it working
on App engine Flex.

Obviously, I dont have any control over cloud functions. So, I will try
again with cloud functions team.

@joelgriffith Thanks! That's a nice API. Hope to try it out some time!

**Comment by steren** [comment]
Update:
Node.js 8 for App Engine standard environment and for Cloud Functions now include all the OS packages needed to run puppeteer.

**Comment by vbourdeix** [comment]
From my experience, puppeteer runs well, when deployed on App Engine, though it doesn't from Google Cloud Shell. So if some of you guys have an error such as "error while loading shared libraries: libXss.so.1" when testing directly from Google Cloud Shell (that's what happened to me when I tried to add puppeteer to the hello world example), be aware that it will work as expected when deployed.

**Comment by owenkealey** [comment]
@steren the link to that tutorial is broken.
