### ISSUE TITLE
browser.newPage() is blocked with puppeteer.connect()

### ISSUE THREAD

**Issue by HanXHX** [puppeteer/puppeteer#1450]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13 + current master branch
* Platform / OS version: Debian Stretch
* Uses chrome headless from [Docker](https://hub.docker.com/r/justinribeiro/chrome-headless/)

**What steps will reproduce the problem?**

```javascript
/* eslint-disable no-console, filenames/match-regex, import/no-commonjs */

/**
 * @file Ensure that Chrome can properly start and close.
 */
const puppeteer = require('puppeteer');

const test = async () => {
  console.log('Testing if Chrome works');

  const browser = await puppeteer.connect({
    browserWSEndpoint: 'ws://192.168.200.200:9222/devtools/browser/36b65179-51a0-402b-9dd4-096c808a67c7'
  });
  console.log('Hello! 1');

  const page = await browser.newPage();
  console.log('Hello! 2');

  const navigationPromise = page.waitForNavigation();
  console.log('Hello! 3');

  await page.goto('http://perdu.com/');
  console.log('Hello! 4');

  await navigationPromise;
  console.log('Hello! 5');

  console.log(await page.content());
  console.log('Hello! 6');

  await browser.close();

  console.log('Chrome is working expected.');
};

test();
```

**What is the expected result?**

Like in 0.10.0

```
Testing if Chrome works
Hello! 1
Hello! 2
Hello! 3
Hello! 4
Hello! 5
<html><head><title>Vous Etes Perdu ?</title></head><body><h1>Perdu sur l'Internet ?</h1><h2>Pas de panique, on va vous aider</h2><strong><pre>    * &lt;----- vous êtes ici</pre></strong>
</body></html>
Hello! 6
Chrome is working expected.
```

**What happens instead?**

```
Testing if Chrome works
Hello! 1
```
And the process is blocked...

**Comment by sdeprez** [comment]
+1 same issue with latest chrome stable (tried on latest canary chromium too) launched headless, on Ubuntu 16.04. Note that it works fine with puppeteer 0.12.0.

**Comment by MehdiRaash** [comment]
I've got 0.13.0 on windows, It works fine for me.

**Comment by vsemozhetbyt** [comment]
I have tried this code with puppeteer 1.0.0-rc (Chromium r515411) on Windows 7 x64 and the output is OK:
<details>
<summary>Code:</summary>

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const prelaunched = await puppeteer.launch();

    console.log('Testing if Chrome works');

    const browser = await puppeteer.connect({
      browserWSEndpoint: prelaunched.wsEndpoint(),
    });
    console.log('Hello! 1');

    const page = await browser.newPage();
    console.log('Hello! 2');

    const navigationPromise = page.waitForNavigation();
    console.log('Hello! 3');

    await page.goto('http://perdu.com/');
    console.log('Hello! 4');

    await navigationPromise;
    console.log('Hello! 5');

    console.log(await page.content());
    console.log('Hello! 6');

    await browser.close();

    console.log('Chrome is working expected.');
  } catch (err) {
    console.error(err);
  }
})();
```
</details><br>

**Comment by icarusmiles** [comment]
I tried this with Puppeteer 0.13.0 on Windows 10 x64 and it works for me.

EDIT: Nvm, yeah same issue when using `.connect` for me on Windows 10 x64.

**Comment by jmg1138** [comment]
I have also been looking for a workaround to this behavior. I'm using puppeteer 0.13.0 on a Raspberry Pi (armhf) so I cannot use the x86_64 chromium that comes with puppeteer. In the puppeteer package.json for 0.13.0 it lists chromium revision 515411. I tried looking for that version of chromium but I am not sure how to find a chromium version by its revision number. Anyone have a tip? I tried installing several different recent versions from [launchpad](https://launchpad.net/ubuntu/+source/chromium-browser) but so far nothing has resolved this newPage issue for me.

**Comment by HanXHX** [comment]
It fails too in Ubuntu 16.04 with:
- Google Chrome 62.0.3202.94
- Chromium 62.0.3202.94

**Comment by icarusmiles** [comment]
Still happening, anyone have a workout other than reverting puppeteer version?

**Comment by HanXHX** [comment]
@miles-collier it works but only with chrome shipped in puppeteer.

I have a dirty script:

```sh
#!/bin/sh

HEADLESS="--headless"

if [ -n "$1" ];
then
	HEADLESS=""
fi

./node_modules/puppeteer/.local-chromium/linux-*/chrome-linux/chrome $HEADLESS --no-sandbox --no-first-run --no-default-browser-check --remote-debugging-port=9222 --disable-gpu --incognito --user-data-dir=$(mktemp -d  -t 'chrome-remote_data_dir-XXXXXXXXXXXXXXXXXXXXXx')
```

**Comment by ileathan** [comment]
To be clear, reverting to 0.10.0 allows you guys to run `newPage()` on Raspberry Pi?

Because for me no matter what version I use I get the same never resolving promise.... OP's code stops on `newPage` for 0.10.0 also.

**Comment by aslushnikov** [comment]
The `browser.newPage()` hangs because you use old version of chromium. If you absolutely can't use the bundled chromium, try using older pptr / newer chrome (e.g. Chrome Canary).

We publish puppeteer's chrome versions in our [releases](https://github.com/GoogleChrome/puppeteer/releases).  For example, puppeteer 1.0.0 requires chrome version 65.

**Comment by yijiem** [comment]
How can I try an older version of pptr? I would like to try out v1.2.0.

**Comment by aslushnikov** [comment]
@yijiem you can install specific version using `npm install puppeteer@1.2.0`
