### ISSUE TITLE
Get Custom Attribute value 

### ISSUE THREAD

**Issue by elrapha** [puppeteer/puppeteer#1451]
I am trying to get the value of my custom attribute "data-my-id'"

So far I have 

const elements = await tester.page.$$('.myRow');
        for(var i = 0; i < elements.length;i++)
        {
            const textProp = await elements[i].getProperty('data-my-id');
            var text = await textProp.jsonValue();
            console.log("Text Result ",text);
        }

text is undefined. but textProp is a JsonHandle. How do i get the value of data-my-id ?

Ofcourse this works with standard attributes like id,style etc

**Comment by realzzz** [comment]
met the same problem - how can we get custom property value ?

**Comment by realzzz** [comment]
Ohh. figure it out by my self.. you can use page.evaluate

For example, I need 'data-src' property from imgurlEle (get from .$() method):
```
await page.evaluate( (obj) => {
  return obj.getAttribute('data-src');
}, imgurlEle);
```

**Comment by vsemozhetbyt** [comment]
@elrapha What about this way?
```js
const values = await page.evaluate(
  () => [...document.querySelectorAll('.myRow')]
        .map(element => element.getAttribute('data-my-id'))
);
```

**Comment by elrapha** [comment]
@realzzz  Yes thank you it worked for me.

**Comment by jenni** [comment]
I'm encountering an issue trying to write a wrapper function to get attributes:

```
async getAttributeOf(selector, attr) {
  return this.page.$eval(selector, el => el.getAttribute(attr));
}
```

When I call it:

`const logo = await page.getAttributeOf('.logo', 'src');`
 
...it's throwing:

`Evaluation failed: ReferenceError: attr is not defined`

Why?

**Comment by vsemozhetbyt** [comment]
This function: `el => el.getAttribute(attr)` is evaluated in the browser context, where there is no `attr` variable. Try to add extra arguments:
```js
return this.page.$eval(selector, (el, attribute) => el.getAttribute(attribute), attr);
```

**Comment by zhangtemplar** [comment]
@realzzz thanks, your method works.

Puppeteer is way more difficult to use than selenium.
