### ISSUE TITLE
Update on iterating over page.$(selector)?

### ISSUE THREAD

**Issue by alexhallam** [puppeteer/puppeteer#1452]
I was reading over #303 and #382, but did not see any update on how to `console.log()` all selectors on a page. Maybe an simple example on this issue or in the docs would be helpful.

**Comment by jamesthrosby** [comment]
Are you looking for something along the following lines?
`
const selectors = await page.$$(SELECTOR);
selectors.forEach( (element) => {
    console.log(element);
});
`

**Comment by alexhallam** [comment]
@jamesthrosby  I don't know the `SELECTOR`. I want a list of all selectors on the page without already knowing what they are. It looks like the above code returns elements of the same selector, but you have to know what the selector is.

**Comment by vonGameTheory** [comment]
But a selector is a like a search term -- user-defined in infinite variety.  (There are no "selectors" on the page, there are elements on the page that can match a selection -- a search.) It sounds like you want a list of all DOM elements, in which case the selector would be '*' (asterisk) to select all elements.  Right?

**Comment by alexhallam** [comment]
Yes, I do want a list of all DOM elements. Sorry for the confusion.

**Comment by aslushnikov** [comment]
@alexhallam like @vonGameTheory said, you can use `page.$$` to get ELementHandles for all the DOM elements

```js
const allNodes = await page.$$('*');
```

Hope this helps.
