### ISSUE TITLE
Document how to use DEBUG=

### ISSUE THREAD

**Issue by wwwillchen** [puppeteer/puppeteer#146]
Pavel demo'ed the debugging workflow where you can dump logs by certain types:
```
DEBUG=*protocol node examples/devtools.js
```
It's really useful and it would be nice to document this somewhere. I was trying to debug why my puppeteer wasn't properly loading chrome://* URLs and I only figured it with the debug logs

**Comment by aslushnikov** [comment]
It is documented in [CONTRIBUTING.md](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md), which is supposed to be the "getting started with puppeteer development" page.

We should probably point to it from README.md

**Comment by wwwillchen** [comment]
:o - I didn't find it when I did https://github.com/GoogleChrome/puppeteer/search?l=Markdown&q=debug&type=&utf8=%E2%9C%93

Thanks!
