### ISSUE TITLE
Shouldn't we drop the async keyword here?

### ISSUE THREAD

**Issue by MehdiRaash** [puppeteer/puppeteer#1460]
It seems it's useless.

https://github.com/GoogleChrome/puppeteer/blob/2becd156d0b25ad3fe4f7b91101b32aead70bd96/lib/Connection.js#L28

**Comment by dios-david** [comment]
+1
Since the function returns a Promise, the `async` keyword is unnecessary here.

**Comment by aslushnikov** [comment]
@MehdiRaash you're right, the `async` can be omitted. However, there's no functional difference, so no need to change anything.

FYI: The `async/await` use in the codebase has been discussed before: https://github.com/GoogleChrome/puppeteer/issues/624
