### ISSUE TITLE
Window blur and focus events in headful/headless mode

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1462]
Puppeteer doesn't have any page method to simulate or dispatch `blur` and `focus` window events.

I was trying to evaluate `window.focus();` and `window.blur();` but event was not fired.

I was trying to dispatch:
```js
const event = document.createEvent('Event');
event.initEvent('blur', true, false);
window.dispatchEvent(event);
```

Of course event is **not** trusted after manual dispatching.

After my PR we have `bringToFront` method, which can help with focus in headful, but what about headless. Any suggestions or ideas?

**Comment by faroceann** [comment]
@schelkun, did you manage to find any way to trigger tab/window focus in headless?

**Comment by faroceann** [comment]
@schelkun I was able to implement a call to the activateTarget method from the Chrome Devtools protocol, which works to activate the window in headless mode.

`browserInstance._connection.send('Target.activateTarget', {targetId: page._client.targetId()})`

This can be implemented in the public Puppeteer API on the Target class, but don't have time for a PR immediately.

**Comment by schelkun** [comment]
@maxwellllll this method is not working in headless.

```js
const puppeteer = require('puppeteer');

(async() => {
    try {
        const browser = await puppeteer.launch({
            headless: false,
            timeout: 10000
        });

        const page = await browser.newPage();

        await page.setViewport({
            width: 1280,
            height: 800
        });

        await page.goto('https://schelkun.github.io/padding-link/');

        await page.evaluate(() => {
            window.addEventListener('visibilitychange', (event) => {
               let c = document.createElement('code');
               c.style.display = 'block';
               c.textContent = 'Event fired!';
               document.body.appendChild(c);
            });
        });

        const selectorWaiter = new Promise(async (resolve, reject) => {
            await page.waitForSelector('code');
            console.log('Code tag exist!');
            resolve();
        });

        const targetChanger = new Promise(async (resolve, reject) => {
            await browser._connection.send('Target.activateTarget', {
                targetId: page._client.targetId()
            });
            console.log('Target changed back!');
            resolve();
        });

        await browser.newPage();

        await Promise.all([selectorWaiter, targetChanger]);
    } catch (e) {
        console.log(e);
    }
})();
```

Try to execute with headless `true` and `false`. `visibilitychange` is not working at headless at all.

**Comment by lixiaolihua** [comment]
+1
