### ISSUE TITLE
page.reload() gives 403 after goto() went through.

### ISSUE THREAD

**Issue by murilozilli** [puppeteer/puppeteer#1463]
Node v8.9.0

* Puppeteer version: 0.13-alpha
* Platform / OS version: Ubuntu Gnome 17.04 Zesty
* URL: https://www.macys.com

After using the page.goto("https://www.macys.com") I call page.reload() to get rid of the modal that this website open on the first time you enter it but when I reload it I get a 403.

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(function (browser) {
    browser.newPage().then(function(page) {
        page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36");
        console.log('page opened, going to url');
        page.goto("https://www.macys.com", {timeout:0}).then(async function(response) {
            page.reload().then(function(response) {
                page.screenshot({
                    path: 'teste.png',
                    fullPage: true
                }).then(function(screenshotBuffer) {
                    console.log('screenshot taked');
                });
            });
        });
    });
});

```
I expect to take a screenshot of the website without the modal unexpectedly I take a screenshot of the default "Access Denied" webpage

**Comment by aslushnikov** [comment]
The website is using some anti-bot heuristics to limit automated access.
