### ISSUE TITLE
Lost UI shared context on browser.newPage() when running node from another application

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1464]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: **puppeteer@0.13.0**
* Platform / OS version: **Ubuntu 16.04.3**
* URLs (if applicable): 
https://github.com

**What steps will reproduce the problem?**

1. Save following text as `screenshot.js`:
```js
const puppeteer = require('puppeteer');

console.log('00000');
(async () => {
    console.log('00000');
    const browser = await puppeteer.launch({dumpio: true});
    console.log('00000');
    const page = await browser.newPage();
    console.log('1111');
    await page.goto(process.argv[2]);
    console.log('22222');
    //page.setViewport({ width: 1366, height: 3000 });
    await page.screenshot({path: process.argv[3]});

    console.log('33333');
    await browser.close();
})();
```
2. Launch `python`
3. Run following commands:
```python
>>> import os
>>> os.system('/usr/bin/node screenshot.js "https://github.com" ~/test.jpg')
```

**What is the expected result?**
No message with generated image.

**What happens instead?**
```
00000
00000
[1123/222355.582993:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
[1123/222355.585309:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[1123/222355.585330:ERROR:service_manager.cc(889)] Failed to resolve service name: metrics

DevTools listening on ws://127.0.0.1:42550/devtools/browser/80512d81-0ba3-442e-91a2-0ff74f68a01c
(node:1712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: socket hang up
(node:1712) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I run this code from shell itself it is fine but when I run it from python I get this error. And running `chrome` from same python shell is ok:
```python
In [61]: os.system('./node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome')
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Out[61]: 0
```

**Comment by jayeshanandani** [comment]
how did you solve this?

**Comment by ghost** [comment]
@jayeshanandani I was running python using `proxychains` in order to use a proxy, apparently it was source of the issue, so I didn't use it and it was fine

**Comment by stopsopa** [comment]
I reproduced this on Travis.ci here: [link](https://github.com/stopsopa/docker-puppeteer-reproduce-lost-ui-shared-context)

It's quite important to solve it because this issue makes docker container useless.

**Comment by stopsopa** [comment]
Ok so i reproduced it but on my Linux server after this error script stoppes on await page.content() but on travis it pass through... I give up

actually first .goto() is crashing (unresolved promise) but in timeout try catch I'm trying to execute page.content() but it stuck too.


![image](https://user-images.githubusercontent.com/3743506/40927439-9f9e4f32-6816-11e8-8c7e-d1aa979a0103.png)
![image](https://user-images.githubusercontent.com/3743506/40927531-d9153f1e-6816-11e8-9406-b36c67c021bf.png)

the same on ubuntu
![image](https://user-images.githubusercontent.com/3743506/40928321-ea8b2856-6818-11e8-9b0f-9c20d2e27be9.png)

I think i did everything what i could, now your turn.. ;)
