### ISSUE TITLE
page basic auth dialog cannot dismiss after page.click.

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1465]
Puppeteer version: 0.13.0
Platform / OS version: Win10x64 / Chromium 64.0.3264.0

```js
page.click('a');
page.on( "dialog", async dialog => {
console.log(dialog);
dialog.dismiss();
});
```

page basic auth dialog cannot dismiss after page.click and browser waits for auth action.

**Comment by vonGameTheory** [comment]
Are you intending to send auth credentials?  You can use page.authenticate() for that, although it apparently turns on request interception which seems to have some issues messing up certain headers (like referer) and there was at least one other issue I saw with ssl pages with improper certificates (if you are trying to ignore those errors it hangs).  You can also just set your own auth header with page.setExtraHTTPHeaders(headers) which gets around the interception ( I think, only tested it lightly but I'm trying to avoid using interception until the issues get worked out).

**Comment by ghost** [comment]
I finally found a way to dismiss basic auth window.

```js
await page.authenticate({username:'',password:'' });
page.click('a');
await page.authenticate(null);
```

it works nice. but if it could be closed with a single function, it would be more effective..
