### ISSUE TITLE
waitForNavigation doesn't work after evaluate fetch() or XMLHttpRequest()

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1466]
Puppeteer version: 0.13.0
Platform / OS version: Win10x64 / Chromium 64.0.3264.0

```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({headless:false,userDataDir:'test-profile-dir'});
const page = await browser.newPage();
await page.setRequestInterception(true);
await page.on('request', request => {
    request.continue();
});
await page.goto("https://www.npmjs.com/",{waitUntil: ['networkidle0','load','domcontentloaded'],timeout:10000}).catch(error=>console.log(error));
await page.evaluate(async () => {fetch("https://www.npmjs.com/features").then( response => response.text() ).then( html => document.body.innerHTML=html )}).catch(error=>console.log(error));
await page.waitForNavigation({waitUntil: ['networkidle0','load','domcontentloaded'],timeout:10000}).catch(error=>console.log(error));
await page.goto("https://www.npmjs.com/pricing",{waitUntil: ['networkidle0','load','domcontentloaded'],timeout:10000}).catch(error=>console.log(error));
await browser.close();
})();

```

it returns the result as below

`Error: Navigation Timeout Exceeded: 10000ms exceeded`

**Comment by vsemozhetbyt** [comment]
This code has the same issue with `fetch` line comment out. It seems we are just stuck on `await page.waitForNavigation()` line, waiting for no navigation pending. The code might be this one:
```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({headless:false});
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  await page.on('request', request => {
    request.continue();
  });
  
  await page.goto("https://www.npmjs.com/",{waitUntil: ['networkidle0','load','domcontentloaded'],timeout:10000}).catch(error=>console.log(error));

  await page.evaluate(async () => {fetch("https://www.npmjs.com/features").then( response => response.text() ).then( html => document.body.innerHTML=html )}).catch(error=>console.log(error));

  page.goto("https://www.npmjs.com/pricing",{waitUntil: ['networkidle0','load','domcontentloaded'],timeout:10000}).catch(error=>console.log(error));
  await page.waitForNavigation({waitUntil: ['networkidle0','load','domcontentloaded'],timeout:10000}).catch(error=>console.log(error));

  await browser.close();
})();
```

**Comment by ghost** [comment]
the example you gave does not wait for the page (https://www.npmjs.com/features) to load.
it means page does not wait for networkidle0, load and domcontentloaded options.
you can try it on another page that has a long loading time.

**Comment by vsemozhetbyt** [comment]
@0zgurYalcin If I understand correctly, `page.waitForNavigation` should not wait for `fetch` — it is not navigation of the `page`. But the `page.evaluate()` should wait for the promise of its function to resolve.

**Comment by ghost** [comment]
`page.evaluate()` has no options like waituntil, timeout etc. i tried XMLHttpRequest instead of fetch, and  `page.waitForFunction("window.XMLHttpRequest.readyState==4")` after `page.evaluate()`. but it does not work. i have no idea about how can it wait for fetch or xhr response after page.click() or page.evaluate()..

**Comment by vonGameTheory** [comment]
waitForNavigation is for url changes to the main frame, i.e. in a non-headless browser the url in the address bar would change -- going to a whole new url.  ('framenavigated' is fired also at the start of a navigation event) For in-page requests, I think you'd have to watch the 'request' event (and associated 'requestfinished', 'requestfailed' events).  waitForFunction or waitForSelector might also work (depending).  I have not tried waitForFunction but looks like there are some polling options you could play with.

**Comment by aslushnikov** [comment]
Thank you @vonGameTheory for the investigation.

**Comment by remorses** [comment]
I had the same iussue and resolved using a recursive function that reset itself every request, and after a small time of idle network ( time parameter ) resolves.
```javascript
const waitForLoad = (page, time) => new Promise((resolve) => {
  page.on('rquest', (req) => {
    waitForLoad(page, time)
  })
  page.on('requestfinished', (req) => {
    setTimeout(() => resolve("timeOut"), time)
  })
})
```
use like this
```javascript
await page.click("button")
await waitForLoad(page, 800)

**Comment by erlichmen** [comment]
@remorses  use .once() instead of .on()
