### ISSUE TITLE
setRequestInterception breaks referer and headers

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1467]
If you will try to execute this code:
```js
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        headless: false,
        timeout: 10000,
        devtools: true
    });

    const page = await browser.newPage();

    await page.waitFor(1000);

    await page.setRequestInterception(true);

    page.on('request', interceptedRequest => {
        console.log(interceptedRequest.headers);
        interceptedRequest.continue();
    });

    await page.setViewport({
        width: 1280,
        height: 800
    });

    try {
        await page.setExtraHTTPHeaders({
            'referer': 'http://example.com/'
        });

        await page.goto('http://www.xhaus.com/headers');
        console.log('Done!');
    } catch (e) {
        console.log(e);
    }
})();
```
You will see, that referer and some other headers will be not sent to webserver. Also devtools will show only provisional headers:

![inter1](https://user-images.githubusercontent.com/31924884/33216951-11a7c3b8-d147-11e7-82c0-ceb8cf804873.png)

But normal headers (in Google Chrome for example) should be like this:

![inter2](https://user-images.githubusercontent.com/31924884/33216996-3f4c3c4a-d147-11e7-8396-27ec0919e0e4.png)

**Comment by schelkun** [comment]
@aslushnikov bug, P1?

**Comment by BeckZero** [comment]
+1 same here...

**Comment by MichaelVIU** [comment]
+1

**Comment by getmonyinfo** [comment]
+1 it's still there

**Comment by Glennvd** [comment]
+1 the fact that it breaks the referer actually breaks some sites here. Can someone confirm if this is a puppeteer bug or a chromium bug?

**Comment by MichaelVIU** [comment]
it seems to be a chromium/chrome bug. With actual stable chrome i have the error / with chrome beta it's running ok (don't use puppeteer, but had same problem...)

**Comment by Glennvd** [comment]
I just checked the sample using build 527279 and the problem is still present there.

**Comment by MichaelVIU** [comment]
yes / i've also tried with chromium in the alpine image / but havn't found any posiblity to use beta versions there - it's the last stable version and there it's not working :(
Thats why i use a debian and install beta there.
You can try to use an older chromium version on alpha (in older versions setting headers had also worked)...
e.g. 61.0.3163.100-r0
https://pkgs.alpinelinux.org/packages?name=chromium&branch=&repo=&arch=&maintainer=
perhaps that helps...

**Comment by aslushnikov** [comment]
Dupe of #469. This is due to a fundamental design of the network stack.

Please upvote #469 if you're interested in it. Upvotes help us prioritize work.
