### ISSUE TITLE
Snapshot image quality issue

### ISSUE THREAD

**Issue by chunsli** [puppeteer/puppeteer#1469]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Ubuntu 16.04 LTS
* URLs (if applicable): 

**What steps will reproduce the problem?**
```
  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  })
  const page = await browser.newPage();
  page.setViewport();
  await page.goto(
    `data:text/html;charset=utf-8;base64,${new Buffer(htmlString).toString(
      'base64',
    )}`,
    {
      timeout: 120000,
    },
  )
  await page.screenshot({
    type: 'png',
    path: outputFileName,
    fullPage: true,
  })
```
As you may be able to see below, the quality in image 1 is significant higher than that of image 2. There are blurry edges on both the words and images within the snapshot, I am wondering if there are ways to increase the quality of the snapshot image using puppeteer without increasing the `deviceScaleFactor`, as I need the images to be of specific dimensions.

on Windows PC using chrome to render the HTML and screenshot snipping tool (image 1):
![image](https://user-images.githubusercontent.com/11830348/33226321-42f7c164-d1c6-11e7-87d0-71bd4e044e4b.png)
snapshot using puppeteer on Ubuntu (image 2):
![image](https://user-images.githubusercontent.com/11830348/33226326-5bdd354c-d1c6-11e7-94ba-71290f8c6bd9.png)

**Comment by KyleGoddard** [comment]
having the same issue.

**Comment by vignestion** [comment]
Same issue

**Comment by transitive-bullshit** [comment]
I think the only way to get what you want is to use `deviceScaleFactor` to capture larger screenshots and then scale them down by that factor afterwards, making sure to use a high quality downscaling algorithm (via something like [node-sharp](https://github.com/lovell/sharp)).

**Comment by chunsli** [comment]
@transitive-bullshit we ended up producing 2x `deviceScaleFactor` without downscaling the image. As the images will ultimately be displayed on browsers, we let Chrome deal with the scale down, which produces good results. The downside is the images are not the dimensions we want them to be (2x to be exact).

I wonder why the produced results seem to be different from the rendered image in Chrome vs produced through puppeteer.

Closing this issue as it doesn't seem like there will be a solution in the short run.

**Comment by chunsli** [comment]
Side note, we tried node-sharp as well, the scaled down image quality is not good enough as well.

**Comment by AgCaliva** [comment]
Im having problems with this, it seems that puppeteer is using the navigator to take screenshot, specifically at least in chrome:
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot
I have observed that seems to work ok with full viewport screenshots, but with specific element screenshots it looses some quality and image is a little more fuzzy, at least in Windows 10. Meaning that this problem its probably something in navigator implementation, puppeter should add some function to use your own screenshot software instead in my opinion, but that will probably require headless: false.
