### ISSUE TITLE
Cannot load files from local assets when using page.goto

### ISSUE THREAD

**Issue by lewanowski** [puppeteer/puppeteer#1472]
Hi,

I can't load local assets eg like here:
```
const = html `
  <!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
    </head>
    <body>
      <img src="path/to/local/img.png" />
    </body>
  </html>
`;

const browser = await puppeteer.launch({
  headless: true,
});
const page = await browser.newPage();
await page.goto(`data:text/html,${html}`);
```

When `img` has src with http url, then everyfing works fine.
I've tried a lot of path to place this `img.png` to work, but without success.

**Comment by vonGameTheory** [comment]
I think that is just not allowed for security reasons (in any browser).  You could serve the page from a simple local server (in the same node process) -- then you could use http://localhost/ addresses.

**Comment by ebidel** [comment]
Right. I wouldn't expect this to work, even if you load the page (data url) in a browser.
