### ISSUE TITLE
Chinese characters will not render.

### ISSUE THREAD

**Issue by zone44** [puppeteer/puppeteer#1473]
Installation on Ubuntu 16.04, a screenshot with Chinese characters will return little squares.

**Comment by quasiunafantasia** [comment]
@zone44 i would recommend to check if you have the needed fonts installed on your machine. helped for me

**Comment by wl05** [comment]
I encountered the same problem, someone solved it?

**Comment by aslushnikov** [comment]
Closing as a dupe of #1143.

**Comment by andyliu1985** [comment]
Heroku can install fonts like this

wget https://github.com/notofonts/noto-cjk/raw/main/google-fonts/NotoSerifSC%5Bwght%5D.ttf && mkdir -p ~/.local/share/fonts/noto  && cp *.ttf ~/.local/share/fonts/noto && fc-cache -f -v
