### ISSUE TITLE
How to close the Alert Box?

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1475]

**Comment by tnolet** [comment]
I was looking at the same problem, the solution is in the docs: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-dialog
just set a handler and then dismiss the dialog.

**Comment by ebidel** [comment]
Yep, we have an example of handling alerts in the docs.

**Comment by edujr1** [comment]
I have this code in the page.

$(document).ready(function(){
   alert("abcdef.");
});

When i use page.goto(<page_with_alert>), the page don't finish loading because the alert was actived, and i can't use this "dismiss the dialog" exemples.
Someone have an exemple of solution for me ?

**Comment by vortexau** [comment]
@edujr1 In my experience the ```await page.on(...);``` call needs to occur before ```page.goto(...)```, otherwise as you say the alert triggers and isn't handled.

**Comment by edujr1** [comment]
@vortexau I understand but the alert are triggered when the page is loading after command goto

**Comment by edujr1** [comment]
@vortexau all right, thank you!!!

**Comment by kev1nzh** [comment]
thx all!
