### ISSUE TITLE
The page.waitForNavigation({waituntil:'networkidle2'}) would be waiting until time out if network has already been idled before invoke it. 

### ISSUE THREAD

**Issue by BenjaminChoou** [puppeteer/puppeteer#1476]
For examle:
`    await page.goto("https://www.aqistudy.cn/html/city_realtime.html?v=2.3", { waitUntil: "networkidle2" });
    await page.type("#city", cities[i]);
    await page.tap("a#btnSearch");
    await page.waitForNavigation({ waitUntil: "networkidle2" });    `
After the #btnSearch is tapped, the web uses javascript to access data to render the table. 
I thought using waitForNavigation could get the right result. However, the page would always be waiting until time out. It doesn't work as I expected.
How could I fix it?

**Comment by vsemozhetbyt** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/1412

**Comment by BenjaminChoou** [comment]
@vsemozhetbyt 
I modified my code as you told. 
```
await page.goto('https://www.aqistudy.cn/html/city_realtime.html?v=2.3', { waitUntil: 'networkidle2' });
await page.type('#city', cities[i]);
page.click('a#btnSearch');
await page.waitForNavigation(['networkidle0', 'load', 'domcontentloaded']);
```
But I still got Error: Navigation Timeout Exceeded: 30000ms exceeded.
I don't know what's wrong, and I am still learning puppeteer.
The page [https://www.aqistudy.cn/html/city_realtime.html?v=2.3](url)  is inflated by using javascript.
![20171128001716](https://user-images.githubusercontent.com/19500127/33276806-95f5e37a-d3d1-11e7-9cac-d26baf3312ed.png)

**Comment by vsemozhetbyt** [comment]
@BenjaminChoou If I run the code with `puppeteer.launch({ headless: false });` I can see how it stops after the click. If I try to click manually, I get this error in the browser console:

```console
jquery.easyui.min.js:8834 Uncaught TypeError: Cannot read property 'length' of null
    at Object.render (jquery.easyui.min.js:8834)
    at _544 (jquery.easyui.min.js:7807)
    at HTMLTableElement.<anonymous> (jquery.easyui.min.js:8442)
    at Function.each (jquery-1.8.0.min.js?v=1.2:2)
    at init.each (jquery-1.8.0.min.js?v=1.2:2)
    at init.$.fn.datagrid (jquery.easyui.min.js:8419)
    at city_realtime.html?v=2.3:180
    at getServerData (eval at <anonymous> (jquery-1.8.0.min.js?v=1.2:4), <anonymous>:1:40067)
    at getData (city_realtime.html?v=2.3:177)
    at HTMLAnchorElement.onclick (city_realtime.html?v=2.3:24)
render @ jquery.easyui.min.js:8834
_544 @ jquery.easyui.min.js:7807
(anonymous) @ jquery.easyui.min.js:8442
each @ jquery-1.8.0.min.js?v=1.2:2
each @ jquery-1.8.0.min.js?v=1.2:2
$.fn.datagrid @ jquery.easyui.min.js:8419
(anonymous) @ city_realtime.html?v=2.3:180
getServerData @ VM21:1
getData @ city_realtime.html?v=2.3:177
onclick @ city_realtime.html?v=2.3:24
```

**Comment by vonGameTheory** [comment]
Not sure about your specific code and whether your click is "happening" on the right element to trigger navigation, but in general if you want to make sure you catch an expected navigation event, create the waitForNavigation promise (but do not await it yet) BEFORE you trigger the navigation, i.e. before the click, not after.  And then "await" that created promise, otherwise sometimes it will have happened so fast you will miss it.

So something like:
```
navresponse = page.waitForNavigation(['networkidle0', 'load', 'domcontentloaded']);
page.click('a#btnSearch');
await navresponse;  
```

**Comment by BenjaminChoou** [comment]
@vsemozhetbyt oops, probably because this page can't be accessed from some regions other than China.
@vonGameTheory It still doesn't work. Sad. For now, I use ```await page.waitFor(1000);```

**Comment by vc1** [comment]
调接口抓数据吧

```javascript

var method = 'GETDATA';
var object = {};

function getServerData(method, object, callback, period) {
  const key = hex_md5(method + JSON.stringify(object));
  const data = getDataFromLocalStorage(key, period);
  if (!data) {
    var param = getParam(method, object);
    $.ajax({
      url: '../apinew/aqistudyapi.php',
      data: {
        d: param
      },
      type: "post",
      success: function(data) {
        data = decodeData(data);
        obj = JSON.parse(data);
        if (obj.success) {
          if (period > 0) {
            obj.result.time = new Date().getTime();
            localStorageUtil.save(key, obj.result)
          }
          callback(obj.result)
        } else {
          console.log(obj.errcode, obj.errmsg)
        }
      }
    })
  } else {
    callback(data)
  }
}
```

**Comment by BenjaminChoou** [comment]
@vc1 我用```page.evaluate()```好像不能成功调用啊，最近才开始学的，有些地方没有全搞懂，麻烦你告诉我这个接口怎么正确调用。
谢谢。
```	
        await page.exposeFunction('log',msg=>console.log(msg));
	await page.evaluate(()=>{
		window.log('evaluate');
		getServerData(method,object,(obj)=>{
			console.log(obj.data.rows[0]);
			console.log(obj);
			window.log(obj.data.rows[0]);
		},0.5)
	})
```

**Comment by BenjaminChoou** [comment]
@vc1  如果我这么调用的话
```
	await page.exposeFunction('log', msg => console.log(msg));
	await page.evaluate(getServerData, method, object, function (obj) {
		console.log(obj.data.rows[0]);
		console.log(obj);
		window.log(obj.data.rows[0]);
	}, 0.5);

```
会出现这个情况：
![image](https://user-images.githubusercontent.com/19500127/33465806-df88be94-d684-11e7-89e5-2ce9b649c0db.png)

**Comment by vc1** [comment]
我意思是你调接口，直接发http请求直接就能拿到原始数据，就不用从页面表格上扒了

**Comment by BenjaminChoou** [comment]
@vc1可是这个API的数据编码吧，接口代码里有decodeData等函数，应该不是js自己的方法，我请求过来不是解析不了数据？

**Comment by vc1** [comment]
看一下网页的js就知道了，就是AES DES Base64 的加密编码
![image](https://user-images.githubusercontent.com/9018903/33472158-e739c5d0-d6ab-11e7-9962-87ac97596beb.png)

用接口抓数据，用浏览器监测加密用的key有没有发生变化

**Comment by vc1** [comment]
还有这个issues，后面都用 waitFor 等几秒再操作，肯定不会出错

**Comment by aslushnikov** [comment]
I've translated a few comments up there, but they don't seem to address the initial question..

> I thought using waitForNavigation could get the right result. However, the page would always be waiting until time out. It doesn't work as I expected.

@BenjaminChoou the `waitForNavigation` method waits for the subsequent navigation; in your case, page doesn't navigate away, but instead fetches some data with XHRs. So the `waitForNavigation` doesn't help.

I'd try using `'requestfinished'` event to track exactly when the requests finishes. If the DOM gets mutated, the `page.waitForSelector` is a good way to wait for the page to reach desired state.

Hope this helps.

**Comment by BenjaminChoou** [comment]
@aslushnikov Thank you very much. I think it would fix my problem because it really makes sense. But I've already fixed this by directly requesting APIs from the web. Anyway, next time I would try it.:smiley:

**Comment by JohnDotOwl** [comment]
@aslushnikov is there still no way around this? 
Mine is XHR, any code to wait for XHR when i click a button?
