### ISSUE TITLE
page.goto() method generates `Error: net::ERR_CONNECTION_RESET` error

### ISSUE THREAD

**Issue by ekremney** [puppeteer/puppeteer#1477]
### Steps to reproduce

**My environment:**
(also, I got the same error on https://try-puppeteer.appspot.com/)

* Puppeteer version: v0.13.0
* Platform / OS version: MacOS Sierra 10.12.6
* URLs (if applicable): http://www.personalentwicklungsberatung.de/Arbeitszeugnis/Arbeitszeugnis_-_Bewertungen/arbeitszeugnis_-_bewertungen.html

**Reproduce the problem:**

```javascript
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('http://www.personalentwicklungsberatung.de/Arbeitszeugnis/Arbeitszeugnis_-_Bewertungen/arbeitszeugnis_-_bewertungen.html');

console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();

```

After running the code block above, I got `Error: net::ERR_CONNECTION_RESET` error.

**Comment by vsemozhetbyt** [comment]
I can reproduce on Windows 7 x64.

FWIW, with `puppeteer.launch({ headless: false })` everything is OK.

**Comment by ekremney** [comment]
@vsemozhetbyt could you please try with these options:

```
await puppeteer.launch({
        args: [
        '--no-sandbox',
        '--headless',
        '--disable-gpu',
        '--window-size=1920x1080'
    ]});
```

It also doesn't work on https://try-puppeteer.appspot.com/ as well.

**Comment by vsemozhetbyt** [comment]
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ args: [
      '--no-sandbox',
      '--headless',
      '--disable-gpu',
      '--window-size=1920x1080',
    ] });

    const page = await browser.newPage();
    await page.goto('http://www.personalentwicklungsberatung.de/Arbeitszeugnis/Arbeitszeugnis_-_Bewertungen/arbeitszeugnis_-_bewertungen.html');

    console.log(await page.content());
    await page.screenshot({ path: 'screenshot.png' });

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```console
Error: net::ERR_CONNECTION_RESET
    at navigate (puppeteer\lib\Page.js:479:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by aslushnikov** [comment]
That's the website server rejecting chrome headless as a client.

**Comment by alirezadarban** [comment]
> That's the website server rejecting chrome headless as a client.

I fixed this problem! I changed userAgent in the headers. By that, website server assumed it was a request from a browser and everything is OK!

```
(async function main() {
    try {
        const browser = await puppeteer.launch({headless: true});
        const page = await browser.newPage();
        await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3419.0 Safari/537.36');
        await page.goto('http://example.com');
         //your code
         await browser.close();
    }
    catch(e){
        console.log(e);
    }
})();

**Comment by MadHatter122312** [comment]
@alirezadarban Can you please explain:
`await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3419.0 Safari/537.36');`

What do those values correspond to?  Settings on your local machine?

Did you try using the default userAgent, and that did not work?

**Comment by alirezadarban** [comment]
> @alirezadarban Can you please explain:
> `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3419.0 Safari/537.36');`
> 
> What do those values correspond to? Settings on your local machine?
> 
> Did you try using the default userAgent, and that did not work?

Sorry for my delay to response. 

1st question: I copied it from my Chrome browser. Honestly, I didn't pay attention to values and what they correspond to.

2nd question: Yes, I tried. But it didn't work. Because in default userAgent it has HeadlessChrome instead of Chrome and the server could recognize that it isn't a request from a browser and not response.

**Comment by Quardah** [comment]
> > That's the website server rejecting chrome headless as a client.
> 
> I fixed this problem! I changed userAgent in the headers. By that, website server assumed it was a request from a browser and everything is OK!
> 
> ```
> (async function main() {
>     try {
>         const browser = await puppeteer.launch({headless: true});
>         const page = await browser.newPage();
>         await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3419.0 Safari/537.36');
>         await page.goto('http://example.com');
>          //your code
>          await browser.close();
>     }
>     catch(e){
>         console.log(e);
>     }
> })();
> ```

This solution works for me. I had intermittent ERR_CONNECTION_RESET for multiple monitoring processes and it seems like setting the user agent made it completely stable.

EDIT : made them***

**Comment by i8sumPi** [comment]
> > That's the website server rejecting chrome headless as a client.
> 
> I fixed this problem! I changed userAgent in the headers. By that, website server assumed it was a request from a browser and everything is OK!
> 
> ```
> (async function main() {
>     try {
>         const browser = await puppeteer.launch({headless: true});
>         const page = await browser.newPage();
>         await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3419.0 Safari/537.36');
>         await page.goto('http://example.com');
>          //your code
>          await browser.close();
>     }
>     catch(e){
>         console.log(e);
>     }
> })();
> ```
