### ISSUE TITLE
Puppeteer to download file with Page.setDownloadBehavior

### ISSUE THREAD

**Issue by dallashuggins** [puppeteer/puppeteer#1478]
I am currently having issues downloading a file via URL. The download itself is working, but an incorrect extension of ".crdownload" is added to the end of the working extension. 

### Steps to reproduce

**Environment:**

* Puppeteer version: ^0.12.0

**Steps:**

`const reportLink = await page.$('table.icwTable > tbody#myReportResults > tr:nth-child(1) > td:nth-child(2) > a');`
`await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: './'});`
`await reportLink.click({ clickCount: 1, delay: 100 });`

1. Select the download URL
2. [Set download behavior](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior) with Chrome DevTools Protocol Viewer
3. Click the link to download 

**Ideally the file would be downloaded and the extension would be ".xls".**

Currently the file is being downloaded, but with a file extension of ".xls.crdownload". If I delete ".crdownload" manually the file downloads correctly - how do I stop the extra ".crdownload" extension from being added.

**Comment by kazaff** [comment]
@dallashuggins  when I use this demo code, I'm not sure if the file have been download, I could't find the file in disk. So, `downloadPath: './'` means where? Or, something I miss?

```javascript
const puppeteer = require('puppeteer');

puppeteer.launch({headless: false}).then(async browser => {
  	const page = await browser.newPage();

  	await page.goto('http://localhost/test.html');
  	
  	const reportLink = await page.$('a#test');
  	await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: './'});
  	await reportLink.click({ clickCount: 1, delay: 100 });
});
```

When I set `headless` to false(for make test visible); And set `page._client.send` at same time, the file had seen to be download, but can not find in disk. If `page._client.send` line was commented  out, the download file would be found in  folder "download".

**Comment by ArturPrzybysz** [comment]
@kazaff 
Have you figured it out? I am having a similar problems as you described.

**Comment by dallashuggins** [comment]
@kazaff sorry for the late response, missed your comment. The './' would download the file as a sibling to the file you are running. The download path I used was './reports' which downloads the file to a sibling folder on the same level as the file I am running (in the root directory). 

Here is the section of my code that I am running, which downloads the report into the reports folder and then renames the file to remove the '.crdownload'. Then I'm running a separate function that deletes the files afterwards. I had a lot of issues with puppeteer with the website I am scraping and I found that whenever there's an issue, try page.waitForNavigation - that seemed to be the problem in most instances for me when I didn't get the behavior I hoped for. Also, just a heads up, in the newer version puppeteer the networkidle is no longer an option but networkidle0 and networkidle2 is. 

```
  // Setting to download in a local folder called 'reports' 
  await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: './reports'});
  await page.waitForNavigation({ waitUntil: 'networkidle' });
  // Click to download (reportLink element defined above)
  await reportLink.click({ clickCount: 1, delay: 100 });
  await page.waitForNavigation({ waitUntil: 'networkidle' });
  // Change the name of the downloaded report 
  var folder = './reports'; 
  var filename;
  fs.readdirSync(folder).forEach(file => {
    console.log("Filename", file);
    filename = file;
    var firstSub = filename.substring(0, filename.lastIndexOf("."));
    var ext = firstSub.substring(firstSub.lastIndexOf("."), firstSub.length);
    var secondSub = firstSub.substring(0, firstSub.lastIndexOf("."));
    var lastSub = filename.substring(filename.lastIndexOf("."), filename.last);
    console.log("First Substring: ", firstSub, "Ext: ", ext, "Second Substring", secondSub, "Last Substring", lastSub);
    if (filename.indexOf('.crdownload') > -1) {
      console.log("Filename included 'crdownload'");
      fs.renameSync(folder + "/" + filename, folder + "/" + replaceExt(secondSub, ext), function(err) {
        if (err) console.log('ERROR: ' + err);
      });
    }
  });
```

Let me know if you have any questions about why I did anything here @kazaff or @ArturPrzybysz.

**Comment by dunnkers** [comment]
I just set out to try if this bug occurred to me when trying to download `.csv` files. However, for me, it downloads just fine in headless **and** non-headless.

```js
async function download(page) {
    await page._client.send('Page.setDownloadBehavior', {
        behavior: 'allow',
        downloadPath: './'
    });
    await page.goto(DOWNLOAD_URL);
    await page.click(DOWNLOAD_BUTTON_SELECTOR);
}
```

Using `puppeteer ^0.13.0`, working just fine. ✅

**Comment by aslushnikov** [comment]
@dallashuggins do you have a small script + url so that we can reproduce this locally? Otherwise it's hard to judge what's going on.

**Comment by ebidel** [comment]
Here's a script that repros in 1.0. I'd expect a .csv file to show up in `./downloads`, but it doesn't:

```js
const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch({
  headless: true,
  dumpio: true,
});

const page = await browser.newPage();

const client = await page.target().createCDPSession();
await client.send('Page.setDownloadBehavior', {
  behavior: 'allow', downloadPath: './downloads/'
});

await page.goto('https://www.nseindia.com/products/content/equities/equities/homepage_eq.htm', {waitUntil: 'networkidle2'});

await page.evaluate(async () => {
  const ele = document.evaluate('//a[text()="Short Selling (csv)"]', document,
      null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
  if (ele) {
    ele.click();
  }
});

})();
```

One observation: switch to `headless: false` and you'll get a crash stack trace. This happens when there's no final `browser.close()` as above. Removing `Page.setDownloadBehavior` removes the crash.

**Comment by orliesaurus** [comment]
Hello all, I have a similar scenario and kinda stuck

- Using `headless: true` - nothing gets downloaded, not even in Chrome Download's folder
- Using `headless: false` AND omitting `browser.close()` downloads the file in the Chrome Download's folder and not in the `downloadPath` specified

Relevant code used:
```js
await page._client.send('Page.setDownloadBehavior', { behavior: 'allow', downloadPath: './' });
await page.click('div.browser_display_only > a');
//await browser.close(); //comment or uncomment for different behaviour
```

**Comment by RyanGhd** [comment]
I have sort of similar issue as @orliesaurus 
- using `headless:true` doesn't do anything
- using `headless: false`  + removing `browser.close()`  + using the following code works well
```
await client.send('Page.setDownloadBehavior', {
        behavior: 'allow', downloadPath: path.resolve(__dirname,'downloaded')});
```

@orliesaurus setting `downloadPath` to `path.resolve(__dirname,'downloaded')` solved the issue for me when `headless: false`

**Comment by t0johnso** [comment]
Hey guys, if it helps, what I noticed is that
      await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: './'});
actually saved the file into the node_modules library where puppeteer/chromium was executing. So confirming what  dallashuggins said: "...which downloads the file to a sibling folder on the same level as the file I am running (in the root directory)."

SO if you're running puppeteer out of node_modules, then your path is relative to  the puppeteer module directory:

![image](https://user-images.githubusercontent.com/2677022/37234452-21679a24-23b5-11e8-9c3d-710134ba9fda.png)

**Comment by antoniogomezalvarado** [comment]
Hi guys, i've tried all suggested here but still my code doesn't work - it works with `headless: false` but NOT with `headless: true` 

```
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  console.log("Running with version: " + await browser.version());
  await browser.close();
})();
console.log("Running with executablePath: " + puppeteer.executablePath());

(async () => {
  const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox','--enable-logging', '--v=1']});
  const page = await browser.newPage();
  await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: '/Users/antoniogomez/Downloads/'})
  await page.goto('http://niftyindices.com/resources/holiday-calendar');
  console.log("Clicking");
  await page.click('#exportholidaycalender');
  await page.waitFor(10000);
  await browser.close();
})();
```

Stdout: 
```
Running with executablePath: /Users/antoniogomez/workspace/devops/scripts/clalreporter/node_modules/puppeteer/.local-chromium/mac-536395/chrome-mac/Chromium.app/Contents/MacOS/Chromium
Running with version: HeadlessChrome/66.0.3347.0
Clicking
```
I see this failure in the log:
```
[0313/114554.406319:VERBOSE1:navigator_impl.cc(200)] Failed Provisional Load: data:application/csv;charset=utf-8, %22SR.%20NO.%...2Christmas%22
error_code: -3, error_description: , showing_repost_interstitial: 0, frame_id: 4
```
So the file doesn't get downloaded - Any idea what i'm missing ?

**Comment by antoniogomezalvarado** [comment]
In case anyone has the same issue this solved it for me: https://stackoverflow.com/questions/49245080/how-to-download-file-with-puppeteer-using-headless-true

**Comment by michaelmillar** [comment]
@antoniogomezalvarado I have tried the code in your link but no file appears in the download folder, it only goes into this part at the start, the writeFile part is never triggered when the click event occurs: 

`if (s == 'about:blank') {
                return;
            }`

Here is the code
```

const browser = await puppeteer.launch({headless: true});
browser.on('targetcreated', async (target) => {
    console.log('targetcreated');
    let s = target.url();
    //the test opens an about:blank to start - ignore this
    if (s == 'about:blank') {
        return;
    }
    //This is fast and ugly to unencode the characters after removing the content type
    s = s.replace("data:application/csv;charset=utf-8,", "");
    s = s.replace(/%2F/g, "/");
    s = s.replace(/%2C/g, ",");
    s = s.replace(/%22/g, '"');
    s = s.replace(/%20/g, " ");
    s = s.replace(/%0A/g, "\n");
    s = s.replace(/%0D/g, "");
           
    fs.writeFile("/tmp/download.csv", s, function (err) {
    if (err) {
        console.log(err);
        return;
    }
    console.log("The file was saved!");
    });
});
const page = await browser.newPage();
await page.goto(url, {
    waitLoad: true,
    waitNetworkIdle: true
});
page.on('dialog', async dialog => {
    // this is important because a window.confirm pops up when clicking the download button
    console.log(dialog);
    // I see the dialog object here when clicking the download button  
    await dialog.accept('test');
});
// the selector for the download button
await page.click('#export');

await browser.close();
```

Do you know why the writeFile is not triggered and the file doesn't actually download into the folder?

**Comment by antoniogomezalvarado** [comment]
@mwmichael try this page: https://github.com/GoogleChrome/puppeteer/issues/299#issuecomment-380841130 
I posted a full working example there, let me know how it goes

**Comment by michaelmillar** [comment]
@antoniogomezalvarado Hi, I also tried that exactly (the code above is almost the same) and it doesn't download anything to the folder. The about:blank part is called, but the writeFile never.

**Edit** I managed to download by removing the part where it returns on about:blank. Cheers

**Comment by aslushnikov** [comment]
Dupe of #299 .

**Comment by pargentieri** [comment]
Page.setDownloadBehavior

**Comment by pargentieri** [comment]
Hi I'm downloading a file using Page.setDownloadBehavior , but I need to know when the download is finished.how can I do this ?

**Comment by manojmilani123** [comment]
> I have sort of similar issue as @orliesaurus
> 
> * using `headless:true` doesn't do anything
> * using `headless: false`  + removing `browser.close()`  + using the following code works well
> 
> ```
> await client.send('Page.setDownloadBehavior', {
>         behavior: 'allow', downloadPath: path.resolve(__dirname,'downloaded')});
> ```
> @orliesaurus setting `downloadPath` to `path.resolve(__dirname,'downloaded')` solved the issue for me when `headless: false`

I am facing same issues, but when I add this line: await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: path.resolve(__dirname,'downloaded')}); it gives me an error saying "path is not defined"

**Comment by vsemozhetbyt** [comment]
@manojmilani123 You need `const path = require('path');` in your script first.

**Comment by manojmilani123** [comment]
> await client.send('Page.setDownloadBehavior', {
>         behavior: 'allow', downloadPath: path.resolve(__dirname,'downloaded')});

I need to run the script in headless mode, will this code work?

**Comment by vsemozhetbyt** [comment]
It should work, if I am not mistaken, just add `const client = await page.target().createCDPSession();` before it.

**Comment by manojmilani123** [comment]
Still not working, I am checking in my current node js project folder as
well as downloads folder on my machine, but the file is not getting
downloaded. I am running latest version of puppeteer library as well. However it downloads the file in the downloads directory when I run the browser in non headless mode.

**Comment by vsemozhetbyt** [comment]
Is there a `'downloaded'` folder in the js project folder? Maybe it is necessary to create it before Chrome can use it?

**Comment by manojmilani123** [comment]
@vsemozhetbyt  Created folder but still not working.

**Comment by manojmilani123** [comment]
@vsemozhetbyt  Do you have any idea how I can debug why it is not getting downloaded?

**Comment by vsemozhetbyt** [comment]
Sorry, I have not(

**Comment by manojmilani123** [comment]
@vsemozhetbyt Any ideas on why it is still not working?

**Comment by vsemozhetbyt** [comment]
No( Maybe somebody from https://github.com/GoogleChrome/puppeteer/issues/299 can help.

**Comment by DaveGeneral** [comment]
hey, guys, I have another question, how to change the filename before the download?  not use fs to rename it after downloaded

**Comment by valeriabarros** [comment]
Hey @DaveGeneral , did you find a way to do it?

**Comment by vipulgupta2048** [comment]
[This helped me](https://mixstersite.wordpress.com/2020/08/13/file-download-headless-chrome-chromium-webdriverio-devtools-chromedriver/) out when using WebdriverIO + Puppeteer, not sure who it helps. I am using Chromium headless.

**Comment by vivekvking** [comment]
Whenever you visit a website in puppeteer it auto downloads setup, how to stop that ?

**Comment by gnpandey1234** [comment]
Target Created but file not downloaded: Page.setDownloadBehavior

const puppeteer = require('puppeteer');
module.exports.avivaPrductLoginObtainData = async (request,resp) => {
    let dataSet = {};
    try{
            //Browser Inslize
            const browser = await puppeteer.launch({
                ignoreHTTPSErrors: true,
                headless: false,
                devtools: false,
                args: ['--no-sandbox', '--disable-setuid-sandbox', '--start-maximized'],
                defaultViewport: null,
                //waitUntil: 'networkidle0',
            });
         //Launching Browser 
        let page;
        page = await browser.newPage();
       // await page.setViewport({ width: 1366, height: 768});
        await page.setDefaultNavigationTimeout(0);
        await page.goto('https://login.aviva.com.sg/SQS/login/', {waitUntil: 'networkidle2'});
        //Login Model
        page = await avivaProductModel.avivaLoginModel(request.body, page);  
        await page.waitForTimeout(6000);
        //Redirection of Other Domain url Getting
        if(request.body.policy_for == 'Individual'){
            await page.click("#home_nav-quo-individual");
            await page.waitForTimeout(1000);
            page = await avivaProductModel.avivaIndividualPremimumModelPage(request.body, page);
            
        }
        else if(request.body.policy_for == 'Third Party'){
            await page.click("#home_nav-quo-thirdparty");
            await page.waitForTimeout(1000);
            page = await avivaProductModel.avivaThirdPartyPremimumModelPage(request.body, page);
        }
        **await browser.on("targetcreated", async (target) => {
            console.log("targetcreated");
            if (target.type() !== "page") {
              return;
            }
            try {
              const pageList = await browser.pages();
              pageList.forEach((page) => {
                page._client.send("Page.setDownloadBehavior", {
                  behavior: "allow",
                  downloadPath: path.resolve(__dirname, 'downloads'),
                });
              });
            } catch (e) {
              console.log("targetcreated", e);
            }
          });**
        
        await page.click("#viewBI_link-black");
        await page.waitForTimeout(8000);
        // const allPages = await browser.pages();
        // await page.waitForTimeout(8000);
        // let pdfurl = allPages[2].url();
        // await avivaProductModel.pdfUrlWrite(pdfurl);
        // await avivaProductModel.pdfUrlDownloadByScellScript();
        dataSet =  response("success", "Insurance Result Get", {result:"Result Done"}); //dataResponse
        resp.status(200).json(dataSet);
    }catch(e){
        logger.error(`Exception occurred to fetch details of insurance : ${e.message}`);
        return resp.status(422).json(response(422, e.message, {}));
    }
}


After clicking this id: **viewBI_link-black**  the pdf opening in browser but file not downloaded in given path or in system 

Please help me, I am struggling with this.

**Comment by gnpandey1234** [comment]
I have resolve my self with given plugins:


puppeteer.use(
            require("puppeteer-extra-plugin-user-preferences")({
              userPrefs: {
                download: {
                  prompt_for_download: false,
                  open_pdf_in_system_reader: true,
                },
                plugins: {
                  always_open_pdf_externally: true, // this should do the trick
                },
              },
            })
          );

**Comment by lehni** [comment]
As of 6c960115a3230e247de628b85dea7c1c02582d6d this does not work anymore.

The workaround is to use `page._client().send`, but:

>  but please remember all internal APIs are subject to breakage without notification.

https://github.com/puppeteer/puppeteer/issues/8533#issuecomment-1158878802
