### ISSUE TITLE
Breaks loading https://help.zenefits.com

### ISSUE THREAD

**Issue by natew** [puppeteer/puppeteer#1480]
### Steps to reproduce
```js
const browser = await puppeteer.launch({
  ignoreHTTPSErrors: true,
})
const page = await browser.newPage()
await page.goto('https://help.zenefits.com')
```

Gives the error:

```
FetchError: request to https://help.zenefits.com/ failed, reason: unable to verify the first certificate
at ClientRequest.<anonymous>
```

**Tell us about your environment:**

* Puppeteer version: 0.13
* Platform / OS version: Mac High Sierra
* URLs (if applicable): https://help.zenefits.com

**What is the expected result?**
Loads fine in regular Chrome browser.

**Comment by vonGameTheory** [comment]
I have no trouble loading this page.  (I'm using v1.0.0-rc though, don't know if that's the difference.  I'm also on Windows 10.)

**Comment by aslushnikov** [comment]
I can reproduce this either; this looks like an issue with the environment.

**Comment by EddieOne** [comment]
How do we catch the FetchError?
