### ISSUE TITLE
Exit event limit and double ^C fix

### ISSUE THREAD

**Issue by dusty-commits** [puppeteer/puppeteer#1481]
Greetings, fellow Puppet Masters! 

I wanted to run this PR by you first to see if you would be interested in it before I submit. There's no specific feature or issue to point to (unless I missed it), but it's rather just a small fix to some existing quirks. All lint/doc/tests are passing, and I've submitted the CLA, so it's ready to go. Let me know if this is not the proper place to post this suggestion. 

**Code explanation:**

[This](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR197) resolves #594 for realz. Even though #85 is probably a better way to handle #594's use case, setting the `maxListeners` to `Infinity` on our own `Emitter` is probably safer than setting it on `process` itself. It also allows for future scenarios where more than 11 browser instances need to be loaded.

[This](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR198) is essentially the same array of listeners that used to be added for every browser instance. It now happens only once per process since this emitter is [initialized at the module level](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR217).

On 'exit', [this handler](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR211) will [pass-through](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR213) the same event for any internal browser listeners [added here](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR127).

Likewise, all the current (and future) SIG handlers [will also pass-through](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR206) to their respective listeners. The [process will explicitly exit](https://github.com/vhesener/puppeteer/pull/2/files#diff-cd756d74c4f724a8d0ebe5f47fff175aR207) which resolves an issue where you had to issue the ^C twice in order to exit from command line.

**Comment by aslushnikov** [comment]
Closing this based on discussion in #1528
