### ISSUE TITLE
Dynamic dropdown's not working

### ISSUE THREAD

**Issue by jamupjammy** [puppeteer/puppeteer#1482]
Hi! 

I am using 0.13 version. When trying to fill in forms ( auto insurance ) the dynamic drop downs ( vehicle year , vehicle make & vehicle model are dependent on each other ) . I successfully selected the vehicle year but the 'vehicle make' drop down list is not loading as it should . If I use page.waitforselector(#vehiclemake) it times out so I wait explicitly for 2 / 3 seconds without success. I do see vehicle make in the page snapshot without it's dynamic list being loaded. thanks.

**Comment by aslushnikov** [comment]
@jamupjammy unfortunately, we can't help much without being able to poke into the website you're automating. 

Please, re-file this issue with a link to the website and a good repro steps so that we have something to work with.
