### ISSUE TITLE
headless: false doesn't work after the first time.

### ISSUE THREAD

**Issue by jamupjammy** [puppeteer/puppeteer#1483]
Hi ! 

I have 0.13 installed. For the launch, using headlless: false works the first time but the second time and all further followups - chromium browsers opens up and snaps ( unsuccessful ). I have had the same trouble with previous versions in the preceding weeks. I am using windows 10 OS. Sorry for the basic question. thanks for help in advance.

**Comment by vonGameTheory** [comment]
Need to see some example code that demonstrates problem.

**Comment by jamupjammy** [comment]
Sorry about that. please find below - changing headless: true works fine.  When headless is false, it opens chromium but not the url. just snaps and hangs . If I close the tab after a long wait - gives an unhandled promise rejection - error is pasted below the code. Many thanks and please let me know if something else is required.  

`const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
  	headless: true,
  });
  const page = await browser.newPage();
  await page.goto('http://cdn.skim.gs/images/hpqyje7hwgmkw1uolama/divorce-can-affect-your-pets');
  await page.screenshot({path: 'cutenessOverload.png'});

  await browser.close();
})();`

This is the  Error : 

`(node:20268) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.enable): Target closed.
(node:20268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Finished in 114.4s]`

**Comment by vonGameTheory** [comment]
I'm using puppeteer v1.0.0-rc on Win10 and node 8.9.1.  This code as-is works fine for me, headless true or false.  Where does the "it works the first time, but not the next time(s)" bit come into it?  Running it repeatedly (that works fine too), running more than instance at once, or???

**Comment by jamupjammy** [comment]
I am not sure how you got v1.0.0 ? Where did you get that from ?  I only see V0.13.0 . What does -rc mean ?? 

I meant - when I do a fresh install, the first time I run using headless: false the browser starts and opens the respective url but if I rerun the same program the browser starts but url snaps - doesn't open the url again. thanks.

**Comment by vonGameTheory** [comment]
v1.0.0-rc is available if you download the master from this site and install locally.  (Has some features and bug fixes I couldn't wait for.) rc means "release candidate" (meaning it is a beta that will be the official 1.0.0 if we don't find too many bugs in it before then).

I will try w/ v0.13.0...

**Comment by vsemozhetbyt** [comment]
You can also upgrade to the tip of tree by the
`npm install https://github.com/GoogleChrome/puppeteer/`

**Comment by vonGameTheory** [comment]
Yeah, all works fine for me.  What's your node version?  Maybe you have an anti-virus or firewall program that thinks this process is up to no good?

**Comment by jamupjammy** [comment]
thanks! I installed v1.0.0-rc as you suggested. Same problem . It opens two tabs and both snap when trying to go headfull. One tab is directed to "chrome://welcome-win10/?text=faster" always. Node version is 8.7.0 . unistalled anti virus and disabled firewall with restart of the computer. Issue still persists. I realized it's basically a chromium Aw, snap issue rather than something related to puppeteer.  Some other folks on chromium have had similar issues. Will try to resolve using that thread. thanks for your help!

**Comment by vonGameTheory** [comment]
It is normal for it to open that welcome tab in headful mode.  Go into node_modules/puppeteer (where ever it got installed) -- it puts the chromium version it downloads into subdirectory .local-chromium/something/something and you could launch it manually, try your url and see if it snaps.

**Comment by jamupjammy** [comment]
thanks Von. Sorry for the delay in getting back.
It doesn't work even when i try to open it manually . Same snap error.

**Comment by vonGameTheory** [comment]
Welp, sounds like it has nothing to do with puppeteer or node anyway.  Does regular Chrome browser do that?  Is it only that url or any url with Chromium?  Only guesses would be something to do with your video card (try --disable-gpu) or some weird path error (trying to create a cache/user directory where it can't).  It could be a million other things too.  Try removing puppeteer with npm and make sure the directory is gone, then reinstall so it sets up chromium again -- or just download Chromium by itself and see how that goes (might be a different version though).

**Comment by jamupjammy** [comment]
thanks VonGame for your time and help on this matter. Some kind soul helped me out with this - 
await puppeteer.launch({
        headless: false,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
