### ISSUE TITLE
Not always click as expected 

### ISSUE THREAD

**Issue by sirdody** [puppeteer/puppeteer#1484]
Hi, 

I'm new to both NodeJS (JavaScript) and Puppeteer. My job need automate some task, and bellow is my code. Sometime, it click, but sometime it fail to click. Can you help me fix it? Thanks

//for (var i = 1; i < lettersLength + 1; i++) {
	for (var i = 2; i < 3; i++) {	
		letterSelector = '#browseLetters > li:nth-child(' + i + ') > a';
		const letterElement = await page.$(letterSelector);
		await letterElement.click();
		await page.waitFor(2000);
		//await page.click(letterSelector, {waitUntil: 'networkidle0'});		
		const groupsLength = await page.evaluate(() => {
			let letters = document.querySelectorAll('#browseGroups > li');
			return letters.length;
		});
		
		for (var j = 1; j < groupsLength + 1; j++) {
		//for (var j = 20; j < 21; j++) {
			groupSelector = '#browseGroups > li:nth-child(' + j + ')'
			console.log(groupSelector);
			const groupElement = await page.$(groupSelector);
			await groupElement.click();
			await page.waitFor(2000);
			//page.click(groupSelector, {waitUntil: 'networkidle0'});
			const links = await page.evaluate(() => {
				links = [];
				let words = document.querySelectorAll('#browseResults > li > a');
				for (var word of words){
					console.log(word.getAttribute('href'));
					links.push(word.getAttribute('href'));
				}
				return links;
			})
			allLinks.push(...links);			
		}
		
	}

**Comment by vonGameTheory** [comment]
I have had trouble getting clicks to register on some pages if I don't set the delay option, e.g. element.click({delay:250})

**Comment by sirdody** [comment]
Putting the delay option on click function does not resolve the problem. It only increases the success rate. Since the the webpage implement ajax to load data? Do you know any kind of solution to track the change of DOM element after click?

**Comment by vonGameTheory** [comment]
Do you just need to wait longer (or use a different method to wait until page is ready) -- or is this a page that is continually active?  Those can be tricky.  A complicated solution could involve triggering events with javascript (dispatchEvent), but it likely you're just clicking before it is ready.  Hard to tell without seeing the actual page you're dealing with...

**Comment by aslushnikov** [comment]
Hey @mrlinhhandsomevn,

There might be different problems, e.g. there might be some element over your click target that prevents clicks to go through.

You can try submitting js-simulated clicks like this:
```js
  // ...
  // Instead of letterElement.click()
  page.evaluate(e => e.click(), letterElement);
```

We won't be able to help unless you give us the actual page and the full script that doesn't work for you.

I'll speculatively close this. Feel free to re-file with a good repro if the suggested workaround doesn't help.

**Comment by dobesv** [comment]
For those hunting for answers, the way that `click` works is that it scrolls the element into view, moves the mouse over the center of it, and then clicks on it.

This can fail if:

1. The element to click is covered by another element
2. The element has a child element in the center of it that accepts click events
3. The element moves or animates in some way that it actually moves out of the way when trying to click
4. The element is in a fixed position container and puppeteer calculates its position for clicking incorrectly

The `page.evaluate` method above avoids these issues, although it's not as "pure" as simulating a click it should be good enough for most tests.

**Comment by aslushnikov** [comment]
> The element is in a fixed position container and puppeteer calculates its position for clicking incorrectly

@dobesv This does sound like a bug. Do you have a repro?

**Comment by dobesv** [comment]
Sorry, I don't have a repro, I can't even confirm that was the problem we had.
