### ISSUE TITLE
page.type with disabled input and focus on a different input

### ISSUE THREAD

**Issue by michael-watzinger** [puppeteer/puppeteer#1486]
I encountered some unexpected behavior when I was using page.type on a disabled input field, while the focus was on a different field.

**Example:**
Tested with v0.13.0 on Ubuntu 16.04 and node v0.8.4.

```html
<html>
<body>
	<input type="text" id="username" value="john" disabled="disabled" />
	<input type="text" id="password" autofocus />
</body>
</html>
```

```javascript
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  let username, password;

  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.goto('file:///tmp/test.html');

  await page.type('#username', 'john.doe');
  await page.type('#password', '123456');

  username = await page.evaluate(() => {
    return document.querySelector('#username').value;
  });
  console.log(username);

  password = await page.evaluate(() => {
    return document.querySelector('#password').value;
  });
  console.log(password);

  await browser.close();
})();
```

**Expected Result:**
I expected that the username remains unchanged and the password contains _123456_. Or maybe an Error because I'm trying to type into a disabled input field.

**Actual Result:**
Instead the username remains unchanged and the password contains both the username and the password.

Right now I avoid this issue by checking the disabled attribute before using page.type, which isn't a bad idea anyway.

PS: Thank you for Puppeteer!

**Comment by jesperalmstrom** [comment]
I have the same or a similar issue (sometimes it works as expected):
![logintimingissue](https://user-images.githubusercontent.com/6968138/39257403-b822422c-48b1-11e8-9f16-f930675d4050.png)
Part of the username is entered but the it seems like the focus goes to the password input field to fast. The rest of the username is combined with the password. 
What I can see this site does not have the `disabled` attribute.

@ontwowheels Do you have a code example of your work around?
@aslushnikov Is this the same issue or should I open a new one?

**Comment by aslushnikov** [comment]
@jesperalmstrom it's hard to say without a codesnippet that would reproduce this
