### ISSUE TITLE
long selector overwirtes page.type

### ISSUE THREAD

**Issue by jpajenski** [puppeteer/puppeteer#1487]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.  const inField = "#did-ui > div > div > section > section > form > section > div:nth-child(1) > div > label > span.input-wrapper > input";
2. page.type(inField, "Hello");
3.

**What is the expected result?**
Hello should be written to the input field

**What happens instead?**
A portion of the selector string is written to the input field.

**Comment by fran0254** [comment]
I have the same problem, did you solve it?

**Comment by jpajenski** [comment]
I got around it by doing the following:

const inField = await page..$('#did-ui > div > div > section > section > form > section > div:nth-child(1) > div > label > span.input-wrapper > input');
await inField.click();
await inField.type('Hello');
