### ISSUE TITLE
Centos ./chrome: symbol lookup error: ./chrome: undefined symbol: gtk_widget_get_scale_factor

### ISSUE THREAD

**Issue by Samlin901211** [puppeteer/puppeteer#1488]
there is something wrong with running ./chrome -v --no-sandbox --disable-setuid-sandbox --headless.
It shows me the error './chrome: symbol lookup error: ./chrome: undefined symbol: gtk_widget_get_scale_factor' 

I've seen the issue before but don't know how to solve it?

**Comment by Samlin901211** [comment]
![image](https://user-images.githubusercontent.com/8406620/33356503-cd3fb82a-d4f7-11e7-80be-164199b731f9.png)

**Comment by Samlin901211** [comment]
I've install all centos dependencies in Troubleshooting

**Comment by aslushnikov** [comment]
@Samlin901211 probably the https://github.com/GoogleChrome/puppeteer/issues/536#issuecomment-324966668 might help? 

I don't have much ideas though. I'd try asking in the #290 or on StackOverflow.

**Comment by yilip** [comment]
Any idea to solve this problem?
