### ISSUE TITLE
Feature: If I could control the event framenavigated of  mainFrame?

### ISSUE THREAD

**Issue by CommanderXL** [puppeteer/puppeteer#1489]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: MAC OS 11.0
* URLs (if applicable): 

**What steps will reproduce the problem?**

Well, I use `framenavigated` event to inject custom js code to the browser before other js code excuted:

```javascript
    page.on('framenavigated', async () => {
         await page.addScriptTag('xxxxx')
    })
```

Well. If this page has no other iframes. The custom js code will be injected to the browser only on time. But if the page loaded other iframes, this event would emit several times.So the custom js code will be injected the browser serveral times.

If I could control the mainFrame like: 

```javascript
   page.mainFrame().on('framenavigated', async () => {
        await page.addScriptTag('xxx')
   })
```

Well, in this way, the other iframes or frames will not affect the mainFrame. And the custom js code will be injected to the browser only one time.

**What is the expected result?**

the framenavigate event will be emitted only one time if this page has other iframes or frames.

**What happens instead?**

the framenavigate event will be emitted serveral times if this page has other iframes or frames.And the code I want to inject will be injected serveral times.

**Comment by aslushnikov** [comment]
@CommanderXL The `framenavigated` event is passed a frame. So you can filter out those you don't like:

```js
page.on('framenavigated', async frame => {
  if (frame !== page.mainFrame())
    return;
  await page.addScriptTag('xxxxx')
})
```

**Comment by tomgallagher** [comment]
The framenavigated solution works but with a lag unfortunately. So if you're trying to see how the page changes from first mainframe request, say with a Mutation Observer, lots of changes are missed before the script loads.
