### ISSUE TITLE
Link to selector reference from API doc

### ISSUE THREAD

**Issue by wwwillchen** [puppeteer/puppeteer#149]
Because `selector` is referenced in a lot of places, it would be nice to link to better documentation.

For example:

#### page.$(selector, pageFunction, ...args)

- `selector` <[string]> A selector to be matched in the page

and `<string>` is a link to the String type in mdn. I think it would be nice to link to a more helpful reference like https://www.w3.org/TR/css3-selectors/#selectors because a lot of times I forget the more unusual selectors. 

[string]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type "String"

**Comment by aslushnikov** [comment]
How about having 'selector' word to point to the MDN?

#### page.$(selector, pageFunction, ...args)

- `selector` <[string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)> A [selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) to be matched in the page
