### ISSUE TITLE
Puppetter Page.close() not freeing tab memory 

### ISSUE THREAD

**Issue by ovheurdrive** [puppeteer/puppeteer#1490]
I'm currently using puppeteer for web scraping using one browser instance on which i connect several node apps using the websocket endpoint..
I run it on 50 websites every 15 minutes, with a process queue running 40 of them concurrently.
But as time goes by, the memory utilization goes crazy, and the only solution i found was to restart the browser.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: tip of the tree
* Platform / OS version: Ubuntu 16.04

**What steps will reproduce the problem?**

This is the code i use to initiate the chrome instance
```Javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--remote-debugging-address=0.0.0.0", "--remote-debugging-port=1234"]
  });
  const wsendpoint = await browser.wsEndpoint();
  console.log(wsendpoint);
})();
```

This is the code I use to connect to a remote chrome instance
```Javascript
const puppeteer = require("puppeteer");
const axios = require("axios");

const extract = async () => {
  const url = process.argv[2];
  const remote_ip = process.argv[3];
  const remote_port = process.argv[4];
  const json = await axios.get(`http://${remote_ip}:${remote_port}/json/version`);
  const wsEndpoint = json.data.webSocketDebuggerUrl;
  const browser = await puppeteer.connect({ browserWSEndpoint: wsEndpoint, ignoreHTTPSErrors: true });
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: "domcontentloaded", timeout: 300000 });

  // Extract the results from the page
  const links = await page.evaluate(() => {
    // Function to check if a tag is visually visible on the page
    const visible = (styles, DOMRect) => {
      if (styles.getPropertyValue("display") == "none" || styles.getPropertyValue("visibility") == "hidden" || styles.getPropertyValue("opacity") == 0) {
        return false;
      } else if (DOMRect.x < 0 || DOMRect.y < 0 || DOMRect.height == 0 || DOMRect.width == 0) {
        return false;
      }
      return true;
    };

    const pageSize = { width: document.body.scrollWidth, height: document.body.scrollHeight };
    const tags = Array.from(document.querySelectorAll("a"));
    return tags.map(tag => {
      const styles = window.getComputedStyle(tag, null);
      const DOMRect = tag.getBoundingClientRect();
      const image = tag.getElementsByTagName("img");
      return {
        url: tag.href,
        fontSize: parseInt(styles.getPropertyValue("font-size")),
        position: { x: DOMRect.x, y: DOMRect.y, left: DOMRect.left, right: DOMRect.right, top: DOMRect.top, bottom: DOMRect.bottom, width: DOMRect.width, height: DOMRect.height },
        visible: visible(styles, DOMRect),
        image: image.length > 0,
        pageSize: pageSize
      };
    });
  });
  await page.close();
  await browser.disconnect();
  return links;
};

extract()
  .then(links => {
    console.log(JSON.stringify(links));
  })
  .catch(e => {
    console.log(e.message);
    process.exit(1);
  });
```

**What is the expected result?**

I would expect the chrome instance to be steady on Memory utilization as i close every tab i open using Page.close()

**What happens instead?**

The chrome instance Memory utilization is growing as time goes by, And i need to restart the full chrome process for it to goes down again.

![image](https://user-images.githubusercontent.com/24658300/33359793-ed7ee9b2-d524-11e7-97f2-f687d971bc7c.png)

It might be a chromium related issue, but i'm not sure, so i thought i would start posting it here.

Thank you.

**Comment by szumel** [comment]
I am struggling with the same problem. Any ideas? 

```code javascript 
const puppeteer = require('puppeteer');
const commandLineArgs = require('command-line-args');

const optionDefinitions = [{
    name: 'url',
    alias: 'u',
    type: String
}];

const options = commandLineArgs(optionDefinitions);

puppeteer.connect({
    browserWSEndpoint: 'ws://127.0.0.1:41279/devtools/browser/d3fb4bb7-5204-4f1f-9758-7971d6bc3680'
}).then(async browser => {
    const page = await browser.newPage();
    await page.goto(options.url);
    const bodyHandle = await page.$('body');
    const html = await page.evaluate(body => body.innerHTML, bodyHandle);
    await bodyHandle.dispose();
    await process.stdout.write(html);
    await page.close();
    await browser.disconnect();
    await process.exit(0);
});

```

**Comment by grantstephens** [comment]
I found that by doing `await page.goto('about:blank')` freed everything up before closing the tabs

**Comment by galvez** [comment]
@grantstephens awesome, thank you.

**Comment by KromDaniel** [comment]
Ping from April 2018

**Comment by kireerik** [comment]
I think as of version `1.3.0` opening a `blank` page before closing tabs is no longer needed to fee up memory.

@grantstephens and @galvez can you confirm that?

**Comment by galvez** [comment]
@kireerik I never fully got past a memory issue generating PDFs. But since I control the content, I created a batched PDF printer with `pdftk`. First, create several 10-page PDFs (fast stages). Then join then together with `pdftk`. It'll take a while before I can change this (code in prod now) but will definitely check it out next time I do.

**Comment by pariola** [comment]
Is this still required for latest versions?

**Comment by phonezawphyo** [comment]
Chromium 69.0.3452.0
Node v10.4.0
Debian jessie 8.10

Still needs to goto `about:blank` before `page.close` to clear tab memory.

**Comment by lexy0093** [comment]
> I found that by doing `await page.goto('about:blank')` freed everything up before closing the tabs

it seems this not work on my situation

**Comment by dadmand** [comment]
-Used linux command "pkill Chrome" before start 
-Make service with pm2 { pm2 start app.js --no-autorestart -- --v8-pool-size=0 }  #important to cpu usage
-Close "about-blank" tabs
```
        for (const page of await browser.pages()) {
            if (!await page.isClosed()) {
                const url = await page.url();
                if (url == 'about:blank') {
                    await page.close();
                }
            }
        }
```
