### ISSUE TITLE
page.close() followed by browser.pages() includes closed page

### ISSUE THREAD

**Issue by oldrich-s** [puppeteer/puppeteer#1491]
* Puppeteer version: 1.0.0-rc
* Platform / OS version: Windows 10, X64

**What steps will reproduce the problem?**

* `npm init`
* `npm i github:GoogleChrome/puppeteer#2becd156d0b25ad3fe4f7b91101b32aead70bd96`
* run this code:

```
const Puppeteer = require('puppeteer')

const puppeteer = Puppeteer.launch({
    args: [`--remote-debugging-port=9220`, '--no-sandbox', '--disable-setuid-sandbox'],
    headless: false
})

async function test() {
    const browser = await puppeteer
    const page = await browser.newPage()
    await page.goto('http://google.com')
    await page.close()
    pages = await browser.pages()

    console.log(pages.map(page => page.url()))
}

test()
```

* Prints out:

```
[ 'chrome://welcome-win10/?text=faster',
  'https://www.google.dk/?gws_rd=cr,ssl&dcr=0&ei=wIIeWvnUFoOv6ASBj7igAg' ]
```

* Should print out:

```
[ 'chrome://welcome-win10/?text=faster']
```

EDIT:

It helps to wrap the `pages` call in timeout with 10ms function:

```
setTimeout(async () => {
    const pages3 = (await browser.pages()).map(t => t.url())
    console.log(pages3)
}, 10)
```

**Comment by aslushnikov** [comment]
@JoelEinbinder can you please take a look? I can easily reproduce.

**Comment by JoelEinbinder** [comment]
I can reproduce this on headful, but not on headless. I imagine we aren't waiting long enough in `Target.closeTarget`

**Comment by aslushnikov** [comment]
> I can reproduce this on headful, but not on headless. I imagine we aren't waiting long enough in Target.closeTarget

Doesn't seem to be the case. I've seen the targetdestroyed come in the right time.

**Comment by JoelEinbinder** [comment]
With: 
```js
const Puppeteer = require('.');

const puppeteer = Puppeteer.launch({
  headless: false
});

async function test() {
  const browser = await puppeteer;
  console.log('creating new page');
  const page = await browser.newPage();
  browser._connection.on('Target.targetDestroyed', console.log.bind(null, 'TargetDestroyed'));
  await page.goto('http://google.com');
  console.log('closing page');
  await page.close();
  console.log('reading pages');
  const pages = await browser.pages();

  console.log(pages.map(page => page.url()));
  await browser.close();
}

test();
```

I'm seeing the output
```
creating new page
closing page
reading pages
TargetDestroyed { targetId: 'C919F41133DF1DFE68630E3683F3755F' }
[ 'chrome-search://local-ntp/local-ntp.html',
  'https://www.google.com/?gws_rd=ssl' ]
```

Indicating that the targetDestroyed event comes too late. I'd expect it to arrive before the ack for closeTarget.

**Comment by aslushnikov** [comment]
@JoelEinbinder you're right. And this turns out to be resasonable: WebContents need to run unload handlers and everything; we don't wait for this in protocol. 

We should probably await targetDestroyed in the `page.close()` method.

**Comment by yanivefraim** [comment]
@aslushnikov @JoelEinbinder - I'll be glad to help with this one, with a little guidance from you guys. 
Did you mean to actually wrap something like this:

`client.on('Target.targetDestroyed',...`

inside a promise? I should, of course, check that it is indeed the same target (but checking targetId)

**Comment by yanivefraim** [comment]
Just waiting for `Target.targetDestroyed` will not work here, because it will happen before Browser's `Target.targetDestroyed`. The actual event I need to wait for is `browser.on('targetdestroyed',...`, but I cannot reach it from within the `Page` object.
