### ISSUE TITLE
page.screenshot.type not respected

### ISSUE THREAD

**Issue by hexydec** [puppeteer/puppeteer#1492]
When taking a screenshot, even though the type is specified as "png", puppeteer uses the file extension of the output file to determine the mime type.

### Environment

- Windows 7
- Puppeteer NPM version 0.13.0
- Node version 7.10.0

### Steps to reproduce

Create a basic screenshot script such as this (example.js):
```
(async () => {
	const puppeteer = require('puppeteer');
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.goto("https://google.co.uk/", {waitUntil: "load"});
	await page.screenshot({
		path: "C:/img.tmp",
		type: "png"
	});
	await browser.close();
})();
```

Run the script on the command line:
`$ node example.js`

**What is the expected result?**
The program should take a PNG screenshot of https://google.co.uk/ and save it to "C:/img.tmp".

**What happens instead?**
`(node:65264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id:2): Assertion error: Unsupported screenshot mime type: application/octet-stream`

It seems to be trying to determine the output type from the file extension regardless of the type setting. This may prevent usage of output targets like /dev/stdout.

**Comment by MrMitch** [comment]
https://github.com/GoogleChrome/puppeteer/blob/2becd156d0b25ad3fe4f7b91101b32aead70bd96/lib/Page.js#L615-L629

Puppeteer tries to deduce the mimetype from the file passed in `options.path` even if the type is specified with the `option.type`.

This is problematic when the filename passed in `options.path` already exists and is empty (for example, a temp file created by another process which is calling the screenshot script).

**Comment by MrMitch** [comment]
I've created a PR that addresses this : https://github.com/GoogleChrome/puppeteer/pull/1526
