### ISSUE TITLE
page.goto() hangs with timeout option set

### ISSUE THREAD

**Issue by Saturate** [puppeteer/puppeteer#1493]
**Environment:**
* Node version: 8.9.1
* Puppeteer version: 0.13.0
* Platform / OS version: Windows 8 (6.3 - Build 9600)

This snippet works fine:

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        waitUntil: 'networkidle2',
        ignoreHTTPSErrors: true,
        args: ['--disable-setuid-sandbox', '--no-sandbox'],
        headless: false
    });

    const page = await browser.newPage();
    console.log('page opened, going to url'); 

    await page.goto('file://C:\\testing\\index.html', { timeout: 0 });
    console.log('page loaded');

    await page.screenshot({path: 'example.png'});
    console.log('screenhot saved!');

    await browser.close();
})();
```

But without the `{ timeout: 0 }` or even setting it to ` { timeout: 30000 }`, it just dosen't finish, and just times out.

The file / URL does not matter, this happens no matter what. It happens both in headless and non-headless mode.

**Comment by vonGameTheory** [comment]
timeout:0 had a bug in 0.13.0, but timeout:30000 should work normally (and it sets timeout:30000 as default if you don't)

**Comment by Saturate** [comment]
But I used v ´0.13.0´ and it's the latest version - so are you sure that it was not the `0.12.0` version?

@vonGameTheory @aslushnikov

**Comment by vonGameTheory** [comment]
The bug that causes timeout:0 to fail definitely in 0.13.0 .  (Again, any positive number should work normally.  The bug only affected timeout:0)  I believe it has been fixed now if you install the current tip-of-the-tree version and it will be in the next official release.
