### ISSUE TITLE
Feature Request: ElementHandle.click([selector], [options]) ?

### ISSUE THREAD

**Issue by redice44** [puppeteer/puppeteer#1494]
I find using Element Handles quite useful when looping through nested nodes on a page. 

I find myself using patterns such as: 
```
const children = await page.$$(selector);

for (let i = 0; i < children.length; i++) {
    const childBtn = await children[i].$(btnSelector);
    await childBtn.click();
}
```
Or 
```
await ( await children[i].$(btnSelector) ).click()
```

I think it would be useful to have a short hand that would allow something along the lines of:
```
await children[i].click(btnSelector);
```

Thoughts?

**Comment by aslushnikov** [comment]
@redice44 we try to have selectors only on the page level, this helps to differentiate `page.type` from `keyboard.type`. This is also a nice mnemonic rule for API clients.

I'd keep it like this for now.
