### ISSUE TITLE
Isn't odd debug all application in one single file?

### ISSUE THREAD

**Issue by edygar** [puppeteer/puppeteer#15]
On development environment, shouldn't we use the non-concatenated javascript files?

It is kind odd to debug one huge file and have to figure out in what file is something or another.

**Comment by juanghurtado** [comment]
We could use mincer, (with grunt-mincer), to perform this task in a better way:

https://github.com/nodeca/mincer
https://github.com/pirxpilot/grunt-mincer

It supports sourcemaps.

I'll give it a try (hopefully soon…).

**Comment by juanghurtado** [comment]
Done in cd5cdca

Now we have source maps!
