### ISSUE TITLE
screenshot `path` option is confusing

### ISSUE THREAD

**Issue by wwwillchen** [puppeteer/puppeteer#150]
I would have expected the `path` to be relative to the script path (e.g. `__dirname`) and not the path I'm executing puppeteer from (e.g. `process.cwd()`).

Is this intentional?
https://github.com/GoogleChrome/puppeteer/blob/9363a15cced4b0666b3ce531c2b8f4020edcfc9d/lib/Page.js#L425

At the least, it should be documented in api.md

**Comment by JoelEinbinder** [comment]
I don't think this is intentional. What's the right way to fix this?

**Comment by wwwillchen** [comment]
There's a couple of options:
1) enforce it's an absolute path (https://nodejs.org/api/path.html#path_path_isabsolute_path) - this is the most robust way but also tedious
2) if you assume the puppeteer script is always invoked directly (e.g. node path/to/script.js) you can use `path.dirname(require.main.filename);` https://stackoverflow.com/a/18721515. This feels hacky and is error-prone (e.g. if a library wraps Puppeteer, this doesn't work);

And if none of these options are satisfying 3) maybe just log to the terminal whenever a file is written (?) I know there's DEBUG logs, but as a user I always like to know when a script is writing/modifying a file.

**Comment by JoelEinbinder** [comment]
Do you have an example of another project that handles this?

**Comment by aslushnikov** [comment]
I think resolving against CWD is fine, this is how `fs` module works by default. This, however, should be stated in the documentation.
