### ISSUE TITLE
Your connection is not private 

### ISSUE THREAD

**Issue by Kevindyb** [puppeteer/puppeteer#1501]
### How to avoid or skip it

**NET::ERR_CERT_COMMON_NAME_INVALID**

_When I crawl webpage information, this problem arises_

So,I clicked the tips below to connect.
* Proceed to inv-veri.chinatax.gov.cn (unsafe)

**But when I restart the browser to open the page again, it pops up again**

* Is there any way to avoid or skip this issue when I browse this web page?
* Imported the certificate, restart the node browser is still pop up the above problems

**Thank you!**

**Comment by Kevindyb** [comment]
puppeteer.launch({ ignoreHTTPSErrors: true, headless: false, timeout: 0 })...
I found it.

**Comment by Sebastian-Nielsen** [comment]
What about supporting actual https requests to keep your connection private?
