### ISSUE TITLE
how can i get the final html source code of the dynamic webpage

### ISSUE THREAD

**Issue by zhizunbao84** [puppeteer/puppeteer#1502]

**Comment by Khady** [comment]
https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/docs/api.md#pagecontent

**Comment by zhizunbao84** [comment]
thank you for your reply.
for example, there are some iframes in the webpage, can i get the final source code including source code of iframes?

**Comment by Garbee** [comment]
You'd need to handle combining all of the iframe content together yourself.

**Comment by ebidel** [comment]
Questions like this are more appropriate for stackoverflow.
