### ISSUE TITLE
In headfull mode, huge screenshots have left parts copied above the right parts

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#1503]
See my configuration, the code, and the images in my comments on this issue: https://github.com/GoogleChrome/puppeteer/issues/1500

**Comment by aslushnikov** [comment]
@vsemozhetbyt Is this different from #477?

(I'd appreciate if you can sum up what's this about, the #1500 has a long discussion.)

**Comment by vsemozhetbyt** [comment]
@aslushnikov If I get this right, the #477 is about the lacunas at the end of screenshots, while this issue is about partial duplication during all the screenshot height. See a focused example here:

https://github.com/GoogleChrome/puppeteer/issues/1500#issuecomment-348165681
