### ISSUE TITLE
how to get the Page instance?

### ISSUE THREAD

**Issue by kazaff** [puppeteer/puppeteer#1507]
```
...
var page = await browser.targets()[0].page();
...
```

when I ran the code,  I got:
```
$ node app.js
(node:7716) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Protocol error (Page.getFrameTree): 'Page.getFrameTree' wasn
't found undefined
(node:7716) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

```
My environment:
- Puppeteer 0.13.0
- Node V8.1.1
- Window 7 64bit

I tried to use `Targets`  to instead of , but still no work.

I wonder that this kind of functions still can't to use for now, right?

**Comment by florinamoldovan** [comment]
I also get the same error with the new version of puppeteer (v0.13.0). 

`Error: Protocol error (Page.getFrameTree): 'Page.getFrameTree' wasn't found undefined`

**Comment by ebidel** [comment]
`Page.getFrameTree` was introduced in https://github.com/GoogleChrome/puppeteer/pull/1275.

Are you using a diff version of Chromium than the one that ships with puppeteer?

This works for me on master:

```js
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://www.google.com/search?q=puppeteer');
  const page2 = await browser.targets()[3].page();
  console.log(await page2.title());
  await browser.close();
})();
```

**Comment by benschwarz** [comment]
@ebidel Arrived here from seeing this error and doing a bit of testing. 
It appears that puppeteer using `Page.getFrameTree` is a little problematic in some cases (I think it's only available in Canary), so beta or stable builds of chrome will not work with puppeteer at this point in time.

**Comment by ithinkihaveacat** [comment]
For reference, 0.12.0 appears to work with Chrome, at least for some use cases. (e.g. need Chrome rather than the Chromium that ships with Puppeteer [to make video work](https://github.com/GoogleChrome/puppeteer/issues/291)).

**Comment by ebidel** [comment]
Gotcha. Then this will fix itself when canary makes its way to stable :)
Not sure what stable version our build maps to...on mobile atm. But I know
64 is going beta very soon.

**Comment by paulirish** [comment]
just checked... **Puppeteer 0.13.0 requires a Chromium version that is equivalent to Chrome `64.0.3265.0`.**

---------

And here's how to get a chrome version if you have a chromium revision number or a git sha:

1. get the `chromium_revision` in the puppeteer package.json
1. look it up on https://omahaproxy.appspot.com/ in the "Find Releases" box. (prefix it with an `r`)
1. A few API calls and redirects later, you'll see the Chrome version.

![image](https://user-images.githubusercontent.com/39191/33783908-8c140eaa-dc13-11e7-8ad4-aea928b7b705.png)
![image](https://user-images.githubusercontent.com/39191/33784012-002e9512-dc14-11e7-99f2-7e7041938c40.png)
