### ISSUE TITLE
page not waiting for another page to finish its tasks before continuing

### ISSUE THREAD

**Issue by A-ZC-Lau** [puppeteer/puppeteer#1509]
So I'm accessing two pages. I need something to finish on another page before the first page does something again. However it seems that the first page itself ignores what the second page is doing and just automatically loops once it finishes its own things.

Code below:

```
        for (let item of items)
        {
            await page.waitFor(10000)
            await page.click("#item_"+item)
            await page.click("#i"+item)

            let pages = await browser.pages()
            let tempPage = pages[pages.length-1]

            await tempPage.waitFor("a.orange", {timeout: 60000, visible: true})
            await tempPage.click("a.orange")

            counter++
        }
```

is this a bug or am I misunderstanding something?

**Comment by aslushnikov** [comment]
@FunnyB0y pages are run in parallel in browser (just like in a real browser, if you have all your pages visible simultaneously).

You can probably block page execution summoning alert dialog.

**Comment by A-ZC-Lau** [comment]
How would you recommend I create this synchronous style?

I'm trying to return a promise but it doesn't seem to work (although it's working for `prompt` in another place)

```
await new Promise( (resolve, reject) => {
            await tempPage.waitFor("a.orange", {timeout: 60000, visible: true})
            await tempPage.click("a.orange")
            resolve()
})
```
