### ISSUE TITLE
page.evaluate incorrectly serializes undefined as null

### ISSUE THREAD

**Issue by kdzwinel** [puppeteer/puppeteer#1510]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: macOS / 10.12.6
* URLs (if applicable):

**What steps will reproduce the problem?**

`console.log( await page.evaluate('var x = {a: undefined}; x') );`

**What is the expected result?**
`{}`

**What happens instead?**
`{a:null}`

Current workaround is to `JSON.stringify` result before returning it from the browser context.

Returning `null` instead of `undefined` was breaking [html-sketchapp](https://github.com/brainly/html-sketchapp/issues/29).

**Comment by aslushnikov** [comment]
@kdzwinel thanks for the report. 

cc @ak239

**Comment by alexkozy** [comment]
We can align our behavior with [JSON.stringify behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify): if object property is undefined then ignore it, if array property is undefined then return it as a null.

**Comment by aslushnikov** [comment]
For the record:
- the upstream patch has landed to V8: https://chromium-review.googlesource.com/c/v8/v8/+/834669
- and was rolled into chromium as https://crrev.com/525272

So this will be fixed with a chromium roll.
