### ISSUE TITLE
Console event is not triggered by console errors

### ISSUE THREAD

**Issue by carlosesilva** [puppeteer/puppeteer#1512]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: macOS 10.12.6
* URLs (if applicable): http://do.carlosesilva.com/puppeteer/

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', msg => console.log('PAGE LOG:', msg.text));
  await page.goto('http://do.carlosesilva.com/puppeteer/');
  await page.waitFor(5000);
  await browser.close();
})();
```

**What is the expected result?**
I expect the console event to be triggered for all 4 of the console items shown in the screenshot below:
<img width="845" alt="puppeteer-browser-console" src="https://user-images.githubusercontent.com/6562179/33489265-636abb3a-d681-11e7-9e6d-f0f6fc998cab.png">

**What happens instead?**
It only gets triggered by the first console item which was from a console.log message.
![puppeteer-node-console](https://user-images.githubusercontent.com/6562179/33489019-a05e98d2-d680-11e7-914d-1ec491a8f9f3.png)

**Comment by mwhitaker** [comment]
This works for me:

    const puppeteer = require('puppeteer');

    (async () => {
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      page.on('console', msg => console.log('PAGE LOG:', msg.text));
      page.on('pageerror', error => {
        console.log(error.message);
       });
      page.on('response', response => {
        console.log(response.status, response.url);
      });
      page.on('requestfailed', request => {
        console.log(request.failure().errorText, request.url);
      });
      await page.goto('http://do.carlosesilva.com/puppeteer/');
      await page.waitFor(5000);
      await browser.close();
    })();

```
200 'http://do.carlosesilva.com/puppeteer/'
PAGE LOG: This is a standard console.log message
Error: This is an error we are forcibly throwing
    at http://do.carlosesilva.com/puppeteer/:22:11
net::ERR_CONNECTION_REFUSED https://do.carlosesilva.com/http-only/sample.png
404 'http://do.carlosesilva.com/puppeteer/this-image-does-not-exist.png'
```

I think the section on the [console event](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-console) doesn't make it super clear 

> Also emitted if the page throws an error or a warning.

 that you have to listen to different events, e.g. pageerror, to capture the various messages the console shows.

Cheers,
Michael

**Comment by carlosesilva** [comment]
That did the trick @mwhitaker, thanks!

**Comment by softaria-roman** [comment]
page.on('console', msg => console.log('PAGE LOG:', msg.text));

Should be 

 page.on('console', msg => console.log('PAGE LOG:', msg.text()));

**Comment by joshuaaguilar20** [comment]
Any one having issues with this its missing the function call 
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', msg => console.log('PAGE LOG:', **msg.text()**));
  page.on('pageerror', error => {
    console.log(error.message);
   });
  page.on('response', response => {
    console.log(**response.status()**, **response.url();**
  });
  page.on('requestfailed', request => {
    console.log(request.failure().errorText, **request.url();**
  });
})()

**Comment by aditodkar** [comment]
@mwhitaker @joshuaaguilar20 @softaria-roman Any suggestions how can we print stack trace for browser errors? error.stack did not work for me.
