### ISSUE TITLE
Global timeout settings.

### ISSUE THREAD

**Issue by wmantly** [puppeteer/puppeteer#1514]
The default timeout for most things is 30000ms and each option has the option to set a custom timeout.
Is there a way to change the global timeout to something much longer? I don't want to have to change all of my `waitFor` all over the code base?

**Comment by aslushnikov** [comment]
> Is there a way to change the global timeout to something much longer?

Not yet.

This has been requested a few times already. We should probably add something like `page.setDefaultNavigationTimeout` setting.

**Comment by stackflows** [comment]
That would be **very** helpful. I hope you have the chance to add this soon.

**Comment by MiltonLn** [comment]
I'm needing this feature too!

**Comment by radu125** [comment]
Hi, I would like to work on this feature. Could you please give me a few pointers on where to start and how to approach this?

**Comment by aslushnikov** [comment]
@raduaron26 sure. The plan for this is:
- add a `defaultNavigationTimeout` field to the Page class:

https://github.com/GoogleChrome/puppeteer/blob/0a498bae3a53357f5b793595b3c411183efd9536/lib/Page.js#L68-L81

- use the field everytime we create a navigation watcher to specify default timeout

https://github.com/GoogleChrome/puppeteer/blob/0a498bae3a53357f5b793595b3c411183efd9536/lib/Page.js#L528-L539

- expose a `page.setDefaultNavigationTimeout` method

Hope this helps!

**Comment by spinningarrow** [comment]
I vote to reopen this - `setDefaultNavigationTimeout` is only for the navigation methods (). It does not affect the `waitFor` functions.

**Comment by aslushnikov** [comment]
@spinningarrow yeah we have this as one of the things for #2079

**Comment by lilotop** [comment]
Now you can use the [page.setDefaultTimeout(timeout)](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagesetdefaulttimeouttimeout) to control all wait methods.
