### ISSUE TITLE
how can i delete Multiple element

### ISSUE THREAD

**Issue by plh97** [puppeteer/puppeteer#1520]
![image](https://user-images.githubusercontent.com/14355994/33514237-65892964-d78b-11e7-91b0-068ba3395f1a.png)
## it throw error
```js
 Node is detached from document
```

**Comment by plh97** [comment]
![image](https://user-images.githubusercontent.com/14355994/33514253-92745c32-d78b-11e7-8f49-03830569ee59.png)

**Comment by plh97** [comment]
help me please~~

**Comment by ebidel** [comment]
Questions like this should be asked on stackoverflow.
