### ISSUE TITLE
how to wait for the page render and then i do something and then wait for the page render,then i do something

### ISSUE THREAD

**Issue by plh97** [puppeteer/puppeteer#1521]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by ebidel** [comment]
Questions like this should be asked on stackoverflow.
