### ISSUE TITLE
Feature Request: To click the element in child frame

### ISSUE THREAD

**Issue by shmdhussain** [puppeteer/puppeteer#1524]
Feature Request: To click the element in child frame

I am able to click any element in the main page using the `await page.click('#find'); `

But If i want to click any element in the child frame, how can i do it, I am seeing there is no click method for the frame object, Is there any way to do? I got the reference to child frame, but not able to click any element inside it.

**Tell us about your environment:**

* Puppeteer version: 0.12
* Platform / OS version:Mac 10.10.5
* URLs (if applicable):NA

**Comment by JoelEinbinder** [comment]
You can use 
```js
var element = await frame.$('#find');
await element.click();
```

**Comment by shmdhussain** [comment]
@JoelEinbinder Thanks it is working
