### ISSUE TITLE
'ESRCH', errno: 'ESRCH', syscall: 'kill'

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1529]
I am getting the below error when trying to install a node application. I have followed the steps in both documents in the links below on Ubuntu. Just cannot find out what else to do :/

https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch

The exact steps for installation are as follows

**gbaz@DESKTOP-EPRVA20:~$ npm i -g npm**
/home/gbaz/.npm-global/bin/npm -> /home/gbaz/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/home/gbaz/.npm-global/bin/npx -> /home/gbaz/.npm-global/lib/node_modules/npm/bin/npx-cli.js

npm@5.5.1
added 460 packages in 88.918s

**gbaz@DESKTOP-EPRVA20:~$ npm install -g aws-azure-login**
/home/gbaz/.npm-global/bin/aws-azure-login -> /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/bin/index.js

puppeteer@0.13.0 install /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer
node install.js
Downloading Chromium r515411 - 95.4 Mb [====================] 100% 0.0s
Chromium downloaded to /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/.local-chromium/linux-515411

aws-azure-login@1.0.1
added 106 packages in 93.44s

**gbaz@DESKTOP-EPRVA20:~$ aws-azure-login**
Logging in with profile 'default'...
{ Error: kill ESRCH
at Object._errnoException (util.js:1024:11)
at process.kill (internal/process.js:183:18)
at forceKillChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:162:19)
at killChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:147:9)
at Function.launch (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:137:7)
at 
at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }

**Comment by aslushnikov** [comment]
@gbaz2000 this looks more like a general problem then a pptr issue. Please, re-submit the question to the stackoverflow - it suites better for this kind of questions.
