### ISSUE TITLE
 I want to wait for the picture to load and then screenshots, how should I do

### ISSUE THREAD

**Issue by wl05** [puppeteer/puppeteer#1530]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by vc1** [comment]
1.
http://lmgtfy.com/?q=wait+for+the+picture+to+load

2.
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

3.
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectororfunctionortimeout-options-args

**Comment by ebidel** [comment]
Please ask questions like this on stackoverflow.
