### ISSUE TITLE
how can I understand about "page context" and "browser context"?

### ISSUE THREAD

**Issue by kazaff** [puppeteer/puppeteer#1532]
I mean, if I want to run some code in target page context, something like  Casperjs.evaluate(). In this case, which one the concept of puppeteer is same with?

**Comment by JoelEinbinder** [comment]
I think we have been using them interchangeably to mean the same thing. Code that runs in Chromium as apposed to code that runs in node.

The equivalent of Casperjs.evaluate would be [`page.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args)

**Comment by kazaff** [comment]
@JoelEinbinder yep, I ran a test to figure out. And as you said, they are equal. Thanks.
