### ISSUE TITLE
'taskkill' error when close browser

### ISSUE THREAD

**Issue by Minyar2004** [puppeteer/puppeteer#1533]
### Steps to reproduce

I'm a new user of puppeteer, I started by testing the examples provided puppeteer/examples/. 

I copied `puppeteer/examples/screenshot.js` and i run it with `node screenshot.js`

**Tell us about your environment:**

* Puppeteer version:   puppeteer@0.13.0
* Platform / OS version:  windows 64

**What is the expected result?**

The code create a screenshot and then close the app

**What happens instead?**

The screenshot is created but I have this error : 

```
'taskkill' n'est pas reconnu en tant que commande interne
ou externe, un programme ex?cutable ou un fichier de commandes.
(node:38232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: taskkill /pid 43932 /T /F
'taskkill' n'est pas reconnu en tant que commande interne
ou externe, un programme ex?cutable ou un fichier de commandes.

(node:38232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you help me fix this issue?

Thank you

**Comment by thorn0** [comment]
How come your Windows doesn't have the [taskkill](https://technet.microsoft.com/en-us/library/bb491009.aspx) utility?

**Comment by aslushnikov** [comment]
Yeah, this seems to be an issue with windows distribution: `taskkill` is normally available.

**Comment by Minyar2004** [comment]
It is strange but my Windows doesn't have the taskkill utility.. I migrated my developments on linux to avoid this problem

**Comment by thorn0** [comment]
What version of Windows was it?

**Comment by Minyar2004** [comment]
Windows 7
Copyright 2009 Microsoft Corporation
Service Pack 1

**Comment by irfaan008** [comment]
To everyone who is struggling to run it on windows, I noticed that windows throws the error that "taskkill is not an internal or external command" only if you are running your node app from non windows command line application.
So if you run your node app using **GitBash** or something similar you are prone to get this error.

So to make it work, just run your project using CMD or Powershell.

**Comment by thorn0** [comment]
So it might make sense for Pupetteer to try running `C:\Windows\System32\taskkill.exe` instead of just `taskkill` then. Let's reopen the issue, shall we?

**Comment by irfaan008** [comment]
@thorn0 Yes, if puppeteer can intelligently decide how to run taskkill irrespective of the **command line tool** its running on, then that would be really appreciable. In fact that is what we expect from such a large enterprise backed library. I suggest to reopen for further fix on it.

**Comment by thorn0** [comment]
Usually nobody checks closed issues, so if there's no reaction, please open a new one.

**Comment by kailynbebee** [comment]
> To everyone who is struggling to run it on windows, I noticed that windows throws the error that "taskkill is not an internal or external command" only if you are running your node app from non windows command line application.
> So if you run your node app using **GitBash** or something similar you are prone to get this error.
> 
> So to make it work, just run your project using CMD or Powershell.

Running Powershell as admin (not as non-admin) worked for me running pa11y.
