### ISSUE TITLE
page.evaluate(() => window.performance) is empty object in 0.13

### ISSUE THREAD

**Issue by Everettss** [puppeteer/puppeteer#1535]
This code:
```javascript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://google.com');

    const performance = await page.evaluate(() => window.performance);
    console.log(performance);

    await browser.close();
})();
``` 
will display performance object in version 0.12 (like [here](https://github.com/GoogleChrome/puppeteer/issues/1368#issuecomment-343923909)) but in version 0.13 it shows only empty object `{}`.

`page.metrics()` and `page._client.send('Performance.getMetrics')` is not a solution since they are lacking of a valuable metrics like in `window.performance.timing`.

**Comment by vsemozhetbyt** [comment]
There were some changes in result serialization before the  0.13. You can try this:
```js
    const performance = JSON.parse(await page.evaluate(
      () => JSON.stringify(window.performance)
    ));
```

**Comment by Everettss** [comment]
@vsemozhetbyt It solve the problem. Is it mentioned in API somewhere? It should be.

**Comment by linh232323** [comment]
If above solution didn't work, let try with

```
const performance = JSON.parse(await page.evaluate(
        async () => Promise.resolve(JSON.stringify(window.performance))
    ));
```
