### ISSUE TITLE
Support for Ember Dynamic Selectors

### ISSUE THREAD

**Issue by denniscieri** [puppeteer/puppeteer#1536]
Does Puppeteer have support for Ember dynamic selectors?

The Ember framework provides each element with a unique id in the format ember2599. 
Is there a way to select the nth ember* element?  or some other method?

Any code example is appreciated.

Thanks!

**Comment by tomredman** [comment]
Would also like to know this :) [It was mentioned](https://github.com/GoogleChrome/puppeteer/issues/600) that #382 would fix this, but I'm still not sure how 🤔

**Comment by JoelEinbinder** [comment]
Untested code ahead!

```js
function nthEmberElement(n) {
    return page.evaluateHandle(n => Array.from(document.querySelectorAll('*')).filter(element => element.id.startsWith('ember'))[n], n);
}

await (await nthEmberElement(5)).click();
```

**Comment by tomredman** [comment]
Super helpful @JoelEinbinder! Thanks!
