### ISSUE TITLE
Chromium has now supposedly fixed the /dev/shm issue in Docker / Lambda, please update puppeteer!

### ISSUE THREAD

**Issue by mattcamp** [puppeteer/puppeteer#1540]
https://bugs.chromium.org/p/chromium/issues/detail?id=736452

Please can we have a version of puppeteer which uses the new Chromium? This will hopefully solve so many headaches with running puppeteer inside Docker containers.

**Comment by ebidel** [comment]
We're close. It was reopened and [more work](https://bugs.chromium.org/p/chromium/issues/detail?id=736452#c48) is being done.
