### ISSUE TITLE
Stalls on browser.newPage() running on node.js

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1543]
Am having trouble getting puppeteer get past `browser.newPage()`.

I'm running this on Cloud 9 (Ubuntu 14.04), with Node version 8.9.1.

I installed the puppeteer package as per the readme:

    $ npm i puppeteer

And I'm using the first basic example in the readme, with logging added:

    const puppeteer = require('puppeteer');
    
    (async () => {
        console.log('launch...');
        const browser = await puppeteer.launch();
        console.log('newPage...');
        const page = await browser.newPage();
        console.log('goto...');
        await page.goto('https://example.com');
        console.log('screenshot...');
        await page.screenshot({path: 'example.png'});
        console.log('close...');
        await browser.close();
    })();

What I see in the console is:

    launch...
    newPage...

Any hints as to what else I need to do to make this work?  Any debug info I can provide?

I've also tried launching with:

    const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});

Same result...

Thanks.

**Comment by sukhjitsingh-impactradius** [comment]
@drmrbrewer Try launching with 
`const browser = await puppeteer.launch({dumpio: true, args: ['--no-sandbox', '--disable-setuid-sandbox']});` 
That should output some errors to the screen and maybe point you in the right direction.
I use this config, but it doesn't matter:

`
    // Run with headless: false for debugging with the browser visible
    const browser = await puppeteer.launch(
        {
            dumpio: true,
            headless: false,
            args: [ 
                       '--no-sandbox', 
                       '--disable-setuid-sandbox',
                     ]
        }
    );`

**Comment by drmrbrewer** [comment]
@sukhjitsingh-impactradius thanks, that's a bit more informative (but the errors still don't mean much to me)... can you help with next steps:

	launch...

	[1206/135707.206311:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
	[1206/135707.206884:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
	[1206/135707.206907:ERROR:service_manager.cc(889)] Failed to resolve service name: metrics

	DevTools listening on ws://127.0.0.1:34875/devtools/browser/64327ddb-cdfd-4523-a380-3b12814caf4c
	Fontconfig warning: ignoring C.UTF-8: not a valid language tag

	newPage...

	[1206/135707.243554:FATAL:nss_util.cc(631)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
	#0 0x563f8ab9ad07 base::debug::StackTrace::StackTrace()
	#1 0x563f8abb19c1 logging::LogMessage::~LogMessage()
	#2 0x563f8b4b7c16 base::LazyInstance<>::Get()
	#3 0x563f8b2e14f5 net::CertDatabase::GetInstance()
	#4 0x563f8b2e07f6 net::CachingCertVerifier::CachingCertVerifier()
	#5 0x563f8b29458c net::CertVerifier::CreateDefault()
	#6 0x563f8b485bbe net::URLRequestContextBuilder::Build()
	#7 0x563f8e84054c headless::HeadlessURLRequestContextGetter::GetURLRequestContext()
	#8 0x563f89969669 content::ChromeAppCacheService::InitializeOnIOThread()
	#9 0x563f89cce319 _ZN4base8internal7InvokerINS0_9BindStateIMN7content21ChromeAppCacheServiceEFvRKNS_8FilePathEPNS3_15ResourceContextEPN3net23URLRequestContextGetterE13scoped_refptrIN7storage20SpecialStoragePolicyEEEJSD_IS4_ES5_S9_NS0_18RetainedRefWrapperISB_EENSK_ISF_EEEEEFvvEE7RunOnceEPNS0_13BindStateBaseE
	#10 0x563f8ab9bf97 base::debug::TaskAnnotator::RunTask()
	#11 0x563f8abb5d34 base::MessageLoop::RunTask()
	#12 0x563f8abb6227 base::MessageLoop::DoWork()
	#13 0x563f8abb8dc9 base::MessagePumpLibevent::Run()
	#14 0x563f8abd688f base::RunLoop::Run()
	#15 0x563f899aea16 content::BrowserThreadImpl::IOThreadRun()
	#16 0x563f899aec11 content::BrowserThreadImpl::Run()
	#17 0x563f8ac01b1a base::Thread::ThreadMain()
	#18 0x563f8abfcd23 base::(anonymous namespace)::ThreadFunc()
	#19 0x7f280f76e184 start_thread
	#20 0x7f280976137d clone

	Received signal 6
	#0 0x563f8ab9ad07 base::debug::StackTrace::StackTrace()
	#1 0x563f8ab9a86f base::debug::(anonymous namespace)::StackDumpSignalHandler()
	#2 0x7f280f776330 <unknown>
	#3 0x7f280969dc37 gsignal
	#4 0x7f28096a1028 abort
	#5 0x563f8ab996e2 base::debug::BreakDebugger()
	#6 0x563f8abb1db6 logging::LogMessage::~LogMessage()
	#7 0x563f8b4b7c16 base::LazyInstance<>::Get()
	#8 0x563f8b2e14f5 net::CertDatabase::GetInstance()
	#9 0x563f8b2e07f6 net::CachingCertVerifier::CachingCertVerifier()
	#10 0x563f8b29458c net::CertVerifier::CreateDefault()
	#11 0x563f8b485bbe net::URLRequestContextBuilder::Build()
	#12 0x563f8e84054c headless::HeadlessURLRequestContextGetter::GetURLRequestContext()
	#13 0x563f89969669 content::ChromeAppCacheService::InitializeOnIOThread()
	#14 0x563f89cce319 _ZN4base8internal7InvokerINS0_9BindStateIMN7content21ChromeAppCacheServiceEFvRKNS_8FilePathEPNS3_15ResourceContextEPN3net23URLRequestContextGetterE13scoped_refptrIN7storage20SpecialStoragePolicyEEEJSD_IS4_ES5_S9_NS0_18RetainedRefWrapperISB_EENSK_ISF_EEEEEFvvEE7RunOnceEPNS0_13BindStateBaseE
	#15 0x563f8ab9bf97 base::debug::TaskAnnotator::RunTask()
	#16 0x563f8abb5d34 base::MessageLoop::RunTask()
	#17 0x563f8abb6227 base::MessageLoop::DoWork()
	#18 0x563f8abb8dc9 base::MessagePumpLibevent::Run()
	#19 0x563f8abd688f base::RunLoop::Run()
	#20 0x563f899aea16 content::BrowserThreadImpl::IOThreadRun()
	#21 0x563f899aec11 content::BrowserThreadImpl::Run()
	#22 0x563f8ac01b1a base::Thread::ThreadMain()
	#23 0x563f8abfcd23 base::(anonymous namespace)::ThreadFunc()
	#24 0x7f280f76e184 start_thread
	#25 0x7f280976137d clone
	  r8: ffffb6066d2ebd30  r9: ffffb6066d2ebd20 r10: 0000000000000008 r11: 0000000000000206
	 r12: 00007f27fac36c90 r13: 00000000000000ce r14: 00007f27fac36c88 r15: 00007f27fac36c80
	  di: 000000000000463f  si: 0000000000004650  bp: 00007f27fac367f0  bx: 00007f27fac367f0
	  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f280969dc37  sp: 00007f27fac36648
	  ip: 00007f280969dc37 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000000
	 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
	[end of stack trace]
	Calling _exit(1). Core file will not be generated.
	[0100/000000.432404:ERROR:broker_posix.cc(43)] Invalid node channel message
	[0100/000000.432393:ERROR:broker_posix.cc(43)] Invalid node channel message

**Comment by drmrbrewer** [comment]
Woohoo... got it working... to address the `NSS_VersionCheck` error when running `browser.newPage()` I just did:

    $ sudo apt-get update
    $ sudo apt-get install libnss3

Now the output is:

	launch...

	[1206/142247.390930:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
	[1206/142247.391165:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
	[1206/142247.391182:ERROR:service_manager.cc(889)] Failed to resolve service name: metrics

	DevTools listening on ws://127.0.0.1:35559/devtools/browser/91e111c4-9322-4014-930f-2cf775826dbc
	Fontconfig warning: ignoring C.UTF-8: not a valid language tag

	newPage...
	goto...
	screenshot...
	close...

Should I be worried by the error messages that remain, and that relate to `puppeteer.launch()`?

**Comment by sukhjitsingh-impactradius** [comment]
@drmrbrewer I get those errors, so I assume it's a known issue. Great to hear!
