### ISSUE TITLE
Update Chromium version 

### ISSUE THREAD

**Issue by NetanelBasal** [puppeteer/puppeteer#1544]
The current Chromium version that comes with puppeteer has many bugs. 
I ran into a bug and upgrading to version 65.0.3287.0 solved it.

You can upgrade the current version, please?

For a temporary solution I tried to use my version:
```
 const options = {
    executablePath: '/Users/netanelbasal/Downloads/chrome-mac/Chromium.app'
  } 
```

But I'm getting `Error: spawn EACCES`.

Thanks.

**Comment by dennistang** [comment]
@NetanelBasal when you specify the `executablePath`, you need to use the specify the actual executable, in your case it would be:
```
const options = {
  executablePath: '/Users/netanelbasal/Downloads/chrome-mac/Chromium.app/Contents/MacOS/Chromium'
} 
```
Then you shouldn't get the error.

**Comment by NetanelBasal** [comment]
Thanks, my solution was to fork this repo and change the revision.

**Comment by aslushnikov** [comment]
We've rolled recently, should be fine now

**Comment by ilyadev3301** [comment]
Hello, id like to add a newer version of chromium, where do i put the options variable, thank you
