### ISSUE TITLE
Page events request/response not fired for WebSocket connection

### ISSUE THREAD

**Issue by suppenburger** [puppeteer/puppeteer#1545]
I am browsing the page https://www.bitcoin.de/de/btceur/market.
The page implements a WebSocket connection via wesocket.io. If I understand correctly wesocket.io supports both XHR-Polling and WebSockets.

I case WebSockets are used the page events request/response are not fired if any data is updated on the page. How can I listen to WebSocket updates?

      await page
        .goto("https://www.bitcoin.de/de/btceur/market", {
          waitUntil: ["networkidle2"]
        })
        .catch(() => {});

      page.on("request", async request => {
       });

**Comment by ebidel** [comment]
Two ways. 

1. You could tap into the raw protocol to detect that the websocket is created. That would involve writing some custom code. https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-webSocketCreated
2. Easier would be to inject some JS code before page load what listens for message events.

**Comment by aslushnikov** [comment]
I'd follow the second approach and inject JS code into the page.

**Comment by jsdevtom** [comment]
@aslushnikov I would be very grateful if you would share how you solved this.
