### ISSUE TITLE
page.waitForSelector timeout in Docker container

### ISSUE THREAD

**Issue by ddesna** [puppeteer/puppeteer#1546]
`page.waitForSelectior()` is working pretty welll on my dev machine (mac os) but it stacks on Docker container.

Here is my code:

```javascript
async function scrape (url) {
  debug('Starting Chromium')

  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']})
  const page = await browser.newPage()
  await page.goto(url)
  await page.waitForSelector('#search') // Timeout on this line

  let result = await page.evaluate(() => {
    let results = []
    const items = document.querySelectorAll('#search')
    items.forEach(item => {
      // ...
      results.push({
       // ...
      })
    })

    return results
  })

  await browser.close()
  return result
}

scrape('https://www.google.com/search?q=puppeteer')
```

I have tried to use timout, like `await page.waitForSelector('#search', {timeout: 30000})` but it is still not working.

Anybody know what is the reason of this issue ?

UPDATE: here is my `Dockerfile`

````
FROM node:8

RUN apt-get update && \
apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 80

CMD ["npm", "start"]
````

**Comment by ebidel** [comment]
You should be using `headless: true` on Docker. Does that change anything? 

Can you provide your dockerfile?

**Comment by ddesna** [comment]
Hi @ebidel ! Sorry, I took mistake on my snippet (already edit it). Actually I'm launching it this way: `puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']})`

**Comment by aslushnikov** [comment]
@ddesna I'm not sure what would be the issue here, but it seems to be related to the docker image rather then pptr.

I'd try checking out others containers and see if things work there (I've seen quite a lot of docker containers for puppeteer around that seem to be successfully used).

**Comment by neerajdixit27** [comment]
> `page.waitForSelectior()` is working pretty welll on my dev machine (mac os) but it stacks on Docker container.
> 
> Here is my code:
> 
> ```js
> async function scrape (url) {
>   debug('Starting Chromium')
> 
>   const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']})
>   const page = await browser.newPage()
>   await page.goto(url)
>   await page.waitForSelector('#search') // Timeout on this line
> 
>   let result = await page.evaluate(() => {
>     let results = []
>     const items = document.querySelectorAll('#search')
>     items.forEach(item => {
>       // ...
>       results.push({
>        // ...
>       })
>     })
> 
>     return results
>   })
> 
>   await browser.close()
>   return result
> }
> 
> scrape('https://www.google.com/search?q=puppeteer')
> ```
> 
> I have tried to use timout, like `await page.waitForSelector('#search', {timeout: 30000})` but it is still not working.
> 
> Anybody know what is the reason of this issue ?
> 
> UPDATE: here is my `Dockerfile`
> 
> ```
> FROM node:8
> 
> RUN apt-get update && \
> apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
> libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
> libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
> libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
> ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
> 
> WORKDIR /app
> 
> COPY package*.json ./
> 
> RUN npm install
> 
> COPY . .
> 
> EXPOSE 80
> 
> CMD ["npm", "start"]
> ```

@ddesna  : Can you please let mw know if you were able to solve this issue, its works fine for me in local machine (Mac), but i see the error only in docker. @aslushnikov  : Can you please help on this.

**Comment by us24man** [comment]
Why has this been closed if there is no solution yet ? I am facing the exact same issue. Script works fine on mac os but gives this error when running in docker

**Comment by us24man** [comment]
@ddesna , @neerajdixit27 this might help, so my issue was with setRequestInterception. That was somehow causing the page to not be loaded properly and hence why the waitForSelector was throwing a timeout error. Removing that code worked. 
I was looking for image, css and font in the requests to abort so  maybe the issue was with a specific resource type. I did not check that.

**Comment by mechanoid** [comment]
Facing the same issue, removing `setRequestInterception` did not help so far

**Comment by phpmaple** [comment]
solved anybody?

**Comment by mechanoid** [comment]
For me it turned out, that waitFor wasn't the problem. Instead it was`.click()` not submitting a form in the dockerized chromium, resulting in the timeout. Maybe it is something similar for you.

**Comment by elizabethlyon** [comment]
@mechanoid , how did you resolve your `.click()` issue? I'm facing the same thing.

> For me it turned out, that waitFor wasn't the problem. Instead it was`.click()` not submitting a form in the dockerized chromium, resulting in the timeout. Maybe it is something similar for you.

**Comment by stgolem** [comment]
> For me it turned out, that waitFor wasn't the problem. Instead it was`.click()` not submitting a form in the dockerized chromium, resulting in the timeout. Maybe it is something similar for you.

Same here. Any solutions for this?

**Comment by mechanoid** [comment]
It turned out to be more reliable go explicitly for the `page.locator` API to lookup buttons. When the button still fails, if often happened to be related to buttons that were not accessible. And please be aware that `{ force: true }` does not help you in such case, it does not resolve that issue. You have to go the full journey and make the button visible, like an enduser would. `force` is only bypassing actionable checks, not accessibilty

**Comment by viktaur** [comment]
It's interesting how for me this issue starts to appear when launching multiple Docker container instances (at least 10-15), despite having enough CPU and memory resources. This issue also persists whether I use /dev/shm or /tmp.
