### ISSUE TITLE
Non-fatal errors when calling puppeteer.launch()

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1547]
I'm running puppeteer on Cloud 9 (Ubuntu 14.04), with Node version 8.9.1.

And I'm using the first basic example in the readme, with logging added:

    const puppeteer = require('puppeteer');
    
    (async () => {
        console.log('launch...');
        const browser = await puppeteer.launch();
        console.log('newPage...');
        const page = await browser.newPage();
        console.log('goto...');
        await page.goto('https://example.com');
        console.log('screenshot...');
        await page.screenshot({path: 'example.png'});
        console.log('close...');
        await browser.close();
    })();

What I see in the console is:

	launch...

	[1206/142247.390930:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
	[1206/142247.391165:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
	[1206/142247.391182:ERROR:service_manager.cc(889)] Failed to resolve service name: metrics

	DevTools listening on ws://127.0.0.1:35559/devtools/browser/91e111c4-9322-4014-930f-2cf775826dbc
	Fontconfig warning: ignoring C.UTF-8: not a valid language tag

	newPage...
	goto...
	screenshot...
	close...

Should I be worried by the above errors?  It all seems to work OK regardless, but how do I avoid them appearing?

**Comment by aslushnikov** [comment]
> Should I be worried by the above errors?

@drmrbrewer Nah, these are fine :) They come from chromium internals and are probably used by the chromium developers.

**Comment by drmrbrewer** [comment]
OK I'll be chilled about them, then.  IMHO if they're not important they should be warnings rather than errors?  Never mind, I'll relax.
