### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1548]
I find that the docs are currently a little bit thin when it comes to teaching how caching is handled and customised in puppeteer... there is just one mention of `caching` in the API docs and not a terribly relevant one.

Specifically, it is not clear to me whether http and service worker caching is supported at all, or whether it is supported only for a particular browser session, or across browser sessions, or a fresh one used for each `puppeteer.launch()`, and so on.

There is a rather low-key mention of a `userDataDir` field in the options passed to [`puppeteer.launch()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions), which states:

> userDataDir: <string> Path to a User Data Directory.

Is this the key to unlocking caching?  Certainly, if I provide a folder for this option, then stuff seems to appear in this folder when running puppeteer, including a `Service Worker` subfolder, but it's still not clear to me whether this is actually used for caching.  What happens if no value is provided for this field... where is this stuff put??

The ideal situation is that both http and service worker caching is fully supported, across browser instances, so that the full benefit of caching can be achieved... like in a desktop Chrome environment.

Can anyone enlighten me?  Can the docs be improved in this respect?

**Comment by aslushnikov** [comment]
> What happens if no value is provided for this field... where is this stuff put??

Puppeteer creates a temporary directory for its profile. The directory gets removed when the browser gets closed.

> The ideal situation is that both http and service worker caching is fully supported, across browser instances, so that the full benefit of caching can be achieved... like in a desktop Chrome environment.

@drmrbrewer both http caching and service workers work.

Below is a script to illustrate http caching. This script will start returning 304 for all but the first requests:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  for (let i = 0; i < 10; ++i) {
    const response = await page.goto('https://example.com');
    console.log(response.status);
  }

  await browser.close();
})();
```

**Comment by pokka** [comment]
@aslushnikov I'm ran your code, and got `200` for all, the version is v1.0.0-rc.
please check it, Thanks.

**Comment by drmrbrewer** [comment]
@aslushnikov I'm not sure what your script is meant to prove because, like @pokka, I get `200` for all (v1.1.1).

I think maybe the behaviour is as follows...

- If no `userDataDir` is provided, then puppeteer will create a `userDataDir` for you in `/tmp`... a different one, in a separate randomly-named folder, for each `browser` launched
- A `userDataDir` created for you by puppeteer will be deleted when the associated `browser` is closed (and if you don't close it properly then it will stick around in `/tmp`, but in a random location and therefore of no further use)
- But if you provide your own `userDataDir` when launching a `browser` then that `userDataDir` will *not* be deleted when the `browser` is closed

So, the main difference is in how long the `userDataDir` persists?  If you don't supply your own `userDataDir` then caching will work for that browser, while it lasts, but the cache from one browser cannot benefit a subsequent browser?  If you want the cache to persist, and be available to benefit a new browser, then you need to supply your own `userDataDir`.

But if you have multiple browsers open simultaneously, you need to provide a separate `userDataDir` location for each of them, otherwise they will conflict.  So a custom `userDataDir` is only useful for cache sharing when it is ensured that a single browser will be using the cache at any one time (`launch`, `close`, `launch`, `close`, rather than `launch`, `launch`, `close`, `close`).

Is that right?  Please correct me if not.

**Comment by liuchuangjun321** [comment]
I also encountered the same confusion as you, how should I use the cache? How did you solve it?

**Comment by liuchuangjun321** [comment]
> I find that the docs are currently a little bit thin when it comes to teaching how caching is handled and customised in puppeteer... there is just one mention of `caching` in the API docs and not a terribly relevant one.
> 
> Specifically, it is not clear to me whether http and service worker caching is supported at all, or whether it is supported only for a particular browser session, or across browser sessions, or a fresh one used for each `puppeteer.launch()`, and so on.
> 
> There is a rather low-key mention of a `userDataDir` field in the options passed to [`puppeteer.launch()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions), which states:
> 
> > userDataDir:  Path to a User Data Directory.
> 
> Is this the key to unlocking caching? Certainly, if I provide a folder for this option, then stuff seems to appear in this folder when running puppeteer, including a `Service Worker` subfolder, but it's still not clear to me whether this is actually used for caching. What happens if no value is provided for this field... where is this stuff put??
> 
> The ideal situation is that both http and service worker caching is fully supported, across browser instances, so that the full benefit of caching can be achieved... like in a desktop Chrome environment.
> 
> Can anyone enlighten me? Can the docs be improved in this respect?

I also encountered the same confusion as you, how should I use the cache? How did you solve it?
