### ISSUE TITLE
Only get domain redirects and possible bug found

### ISSUE THREAD

**Issue by leem32** [puppeteer/puppeteer#1549]
### Steps to reproduce

* Puppeteer version:
  0.13.0

**What steps will reproduce the problem?**

I'm trying to get all domain redirects using the Puppeteer api, saved to an array before taking a screenshot of the final URL, but the code I have so far is also getting other redirects.

For example if I `goto youtube.com` then my code will correctly get the redirects 'https://youtube.com/', 'https://www.youtube.com/',, but it will also get other redirects such as doubleclick.net.

I only want to get the redirects which would happen in the URL bar.

I've managed to narrow it down with request.resourceType === 'document'. How can I narrow it down further??

Here's the code:

```javascript
    // node chrome.js http://youtube.com

    const puppeteer = require('puppeteer');
    var url = process.argv[2];

    (async () => {

    const browser = await puppeteer.launch({headless: true, timeout: 30000, ignoreHTTPSErrors: true});
    const page = await browser.newPage();
    // await page.setRequestInterception(true); // hangs with resourcetype

    const urls = [];

    page.on('request', request => {
      // if (request.resourceType === 'document' || request.resourceType === 'script') {
      if (request.resourceType === 'document') { 
      urls.push(request.url);
      request.continue();
      }
    });

    await page.goto(url, {timeout: 20000, waitUntil: 'load'}); //default load

    await page.screenshot({path: 'test.jpg', type: 'jpeg', quality: 80, fullPage: false});
    console.log(urls);

    await browser.close();
    })();
```

I've also found what I believe to be a bug where using `await page.setRequestInterception(true);` with `request.resourceType === 'document` causes the script to hang forever (untill timeout). The bug is apparent using the above script.

**Comment by leem32** [comment]
Please, could I get an answer on this?? Is there any way to get the domain redirects with puppeteer and avoid other urls/redirects such as doubleclick.net, social media widgets etc.
Thanks :)

**Comment by aslushnikov** [comment]
@leem32 You can just parse redirects explicitly; i got it working with the following script:

```js
// node chrome.js http://youtube.com

const puppeteer = require('puppeteer');
var url = process.argv[2];

(async () => {
  const browser = await puppeteer.launch({headless: true, timeout: 30000, ignoreHTTPSErrors: true});
  const page = await browser.newPage();
  // note: add trailing slash since chrome adds it
  if (!url.endsWith('/'))
    url = url + '/';

  // urls hold redirect chain
  const urls = [url];

  page.on('response', response => {
    // handle redirects only
    if (response.status < 300 || response.status >= 400)
      return;
    // if this redirect doesn't attach to the redirect chain - ignore
    if (response.request().url !== urls[urls.length - 1])
      return;
    // parse the redirect location and add to the chain
    urls.push(response.headers['location']);
  });

  await page.goto(url, {timeout: 20000, waitUntil: 'load'}); //default load
  console.log(urls);

  await browser.close();
})();
```

> I've also found what I believe to be a bug where using await page.setRequestInterception(true); with request.resourceType === 'document causes the script to hang forever (untill timeout). The bug is apparent using the above script.

The issue is in the code snippet that you have: you should continue requests outside of the if condition.

**Comment by leem32** [comment]
Hi aslushnikov,

Thanks for this it works well, but does have an issue. It does not work with javascript/meta refresh redirects, so if I `goto` `leemtestserver.com` which uses javascript to redirect to `archive.is`, the code does not detect that redirect to `archive.is`.

Any ideas??

Thanks
Lee :)

**Comment by aslushnikov** [comment]
@leem32 well, yes, for browser-initiated navigations the solution won't work.

I filed the https://github.com/GoogleChrome/puppeteer/issues/1579 that should help to solve your case.

**Comment by leem32** [comment]
@aslushnikov Thanks :) That would be incredibly useful to me as I've hit a dead-end until I can get all redirects from both client and server side.

I've been fiddling around with the  `framenavigated` event, to get client-side redirects and using the `response` event for server-side redirects, but once there's a client-side redirect the `response` event obviously stops following and so doesn't register any server-side redirects that may come after the client redirect.

Will this thread be updated/closed once the new feature is available?

For anyone interested you can get client-side redirects like this:
```javascript
 page.on('framenavigated', frame => {
   if(frame.parentFrame() === null) {
     console.log(frame._url);
   }
 });
or
   page.on('framenavigated', frame => {
   if (frame === page.mainFrame())
     console.log(frame._url);
   })
```

**Comment by aslushnikov** [comment]
> Will this thread be updated/closed once the new feature is available?

@leem32 all the future updates will take place in the #1579, please subscribe to be notified on future changes
