### ISSUE TITLE
Headless chrome is taking too long to open any url as compared to full chrome

### ISSUE THREAD

**Issue by rohankap** [puppeteer/puppeteer#1550]
When I am trying to open pages in Headless chrome through Puppeteer it is taking much time as compared to the Full Chrome.
I am trying to open normal websites in **1366*768** viewport to take their screenshots , But it takes a lot of time to open normal pages in Headless Chrome.
Below are results of my test which I performed by opening 10 urls using both **headless:true** and **headless:false** flags

## Headless:False (Full Chrome)
google.com: 14279.508ms
hacks.mozilla.org: 16213.428ms
apple.com: 17465.563ms
gmail.com: 18820.810ms
dell.com: 19853.047ms
snapdeal.com: 20722.319ms
flipkart.com: 22994.769ms
microsoft.com: 23404.095ms
hp.com: 23963.416ms
amazon.com: 27175.416ms

## Headless:true (Headless Chrome)
google.com: 157191.829ms
gmail.com: 159343.018ms
snapdeal.com: 309226.297ms
hacks.mozilla.org: 337393.393ms
microsoft.com: 369301.073ms
dell.com: 397798.479ms
apple.com: 398685.341ms
flipkart.com: 576905.928ms
hp.com: 1118683.968ms
amazon.com: 2372061.166ms

## **Steps to reproduce:**
1. Execute below script in both Headless Chrome and Full Chrome by setting headless:true and headless:false flag.
2. Time difference between two methods is huge, In Headless Chrome it looks like it get stuck for some time .

## **OS Config**
Windows 7
Puppeteer version 0.13.0
I7 16GB Ram

## **Code :** 
```
var puppeteer = require('puppeteer');

async function capture(url) {
    //console.log(url +': Started');
    console.time(url);
    const browser = await puppeteer.launch({headless:true});
    const page = await browser.newPage();
    page.setViewport({ width: 1366, height: 768 });
    await page.goto('http://'+url, { waitUntil: 'networkidle2', timeout: 3000000 });
    await page.screenshot({path: url+'.jpg',fullPage: true});
    browser.close();
    console.timeEnd(url);

}

capture('hacks.mozilla.org');
capture('google.com');
capture('amazon.com');
capture('flipkart.com');
capture('snapdeal.com');
capture('dell.com');
capture('gmail.com');
capture('apple.com');
capture('microsoft.com');
capture('hp.com');
```

Please let me know if I am missing something or how we can resolve this issue.

**Comment by elviswolcott** [comment]
That discrepancy is definitely troubling and I can't say I've experienced something like that myself. The first thing I'd check is the fact that you're seemingly running `const browser = await puppeteer.launch({headless:true});
    const page = await browser.newPage();
    page.setViewport({ width: 1366, height: 768 });`
within your console.time which means that some of the time you're recording is the browser startup, not the actual page load. It doesn't make sense that headless would take so much longer to start, but it could be part of the problem.

**Comment by rohankap** [comment]
Hi @elviswolcott 

I also tried it by keeping the console.time after the browser startup, but still it is taking lot of time as compared to the full Chrome, Dow you feel I am missing anything from my side ?
If possible can you try the same script on your end with **headless:true** flag and check the results if it is rendering fast.

## Headless:False (Full Chrome)
google.com: 6213.263ms
hacks.mozilla.org:   8265.880ms
gmail.com: 9059.529ms
apple.com: 10174.603ms
microsoft.com: 12392.126ms
snapdeal.com: 12482.235ms
dell.com: 12973.449ms
flipkart.com: 14357.700ms
hp.com: 14994.758ms
amazon.com: 16465.610ms

## Headless:true (Headless Chrome)
google.com: 110487.453ms
gmail.com: 164606.378ms
snapdeal.com: 279386.972ms
hacks.mozilla.org: 310435.915ms
dell.com: 349223.455ms
apple.com: 356963.199ms
microsoft.com: 377993.839ms
flipkart.com: 542503.116ms
hp.com: 1073391.050ms
amazon.com: 1444052.934ms

## **Code :** 
```
var puppeteer = require('puppeteer');

async function capture(url) {
    //console.log(url +': Started');

    const browser = await puppeteer.launch({headless:true});
    const page = await browser.newPage();
    page.setViewport({ width: 1366, height: 768 });
    console.time(url);
    await page.goto('http://'+url, { waitUntil: 'networkidle2', timeout: 3000000 });
    await page.screenshot({path: url+'.jpg',fullPage: true});
    console.timeEnd(url);
    browser.close();


}

capture('hacks.mozilla.org');
capture('google.com');
capture('amazon.com');
capture('flipkart.com');
capture('snapdeal.com');
capture('dell.com');
capture('gmail.com');
capture('apple.com');
capture('microsoft.com');
capture('hp.com');

```

**Comment by elviswolcott** [comment]
Sure. I'll try running it on my machine later today.

**Comment by elviswolcott** [comment]
google.com: 5315.881ms
gmail.com: 11402.987ms
hacks.mozilla.org: 14959.354ms
apple.com: 17977.527ms
dell.com: 22116.532ms
snapdeal.com: 32075.623ms
microsoft.com: 36875.353ms
amazon.com: 40438.456ms
flipkart.com: 49423.692ms
hp.com: 76458.798ms
(headless)
Took a few minutes to get anything, but I had to close the windows because I wasn't getting reults.
(headless:false)

I think part of the long times is that sites like Amazon.com keep on loading tons of other stuff in the background, so between first draw and network idle is a long time.

**Comment by ebidel** [comment]
@elviswolcott @rohankap , what part of the world are you in? Running the script below takes around 400ms for me on a macbook pro, pptr 0.13.0. Both headless and full chrome.

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
const tick = Date.now();
await page.goto('https://www.google.com/');
console.log(Date.now() - tick);
await browser.close();
```

Keep in mind that `networkidle2` delays the `page.goto` promise from resolving until there are no more than 2 network requests for at least 500ms. If Amazon and other sites are making additional requests after page load, the time you're measuring will get pushed out accordingly.

**Comment by elviswolcott** [comment]
>@elviswolcott @rohankap , what part of the world are you in? Running the script below takes around 400ms for me on a macbook pro, pptr 0.13.0. Both headless and full chrome.
US :)

>Keep in mind that networkidle2 delays the page.goto promise from resolving until there are no more than 2 network requests for at least 500ms. If Amazon and other sites are making additional requests after page load, the time you're measuring will get pushed out accordingly.

Yep

>I think part of the long times is that sites like Amazon.com keep on loading tons of other stuff in the background, so between first draw and network idle is a long time.

My last run was: 
Headless: true:

hacks.mozilla.org: 3824.730ms
google.com: 2083.191ms
amazon.com: 7262.995ms
flipkart.com: 9865.672ms
snapdeal.com: 11096.729ms
dell.com: 4507.837ms
gmail.com: 3833.090ms
apple.com: 3260.902ms
microsoft.com: 6025.978ms
hp.com: 12989.067ms

Headless: false:

hacks.mozilla.org: 3552.536ms
google.com: 2945.891ms
amazon.com: 11461.360ms
flipkart.com: 9990.174ms
snapdeal.com: 9931.200ms
dell.com: 4176.103ms
gmail.com: 3412.557ms
apple.com: 2912.285ms
microsoft.com: 6668.066ms
(hp.com got hung up)

using the following test code to better utilize system resources

```
var puppeteer = require('puppeteer');
var browser, page;


async function capture(url) {
    //console.log(url +': Started');
    console.time(url);
    await page.goto('https://'+url, { waitUntil: 'networkidle2', timeout: 3000000 });
    console.timeEnd(url);
    await page.screenshot({path: 'test/'+url+'.jpg',fullPage: false}); //this shouldn't be part of the timing

}

async function test() {
  browser = await puppeteer.launch({headless:false});
  page = await browser.newPage();
  page.setViewport({ width: 2700, height: 1800 }); //my laptops screen

  await capture('hacks.mozilla.org');
  await capture('google.com');
  await capture('amazon.com');
  await capture('flipkart.com');
  await capture('snapdeal.com');
  await capture('dell.com');
  await capture('gmail.com');
  await capture('apple.com');
  await capture('microsoft.com');
  await capture('hp.com');

  browser.close()
}

test();
```

**Comment by aslushnikov** [comment]
Huge part of loading time is usually the network latency.

In the last run, the numbers are more or less aligned between headless and headful; looks like there's no issue.
