### ISSUE TITLE
Add Response.fromDiskCache/fromServiceWorker for better offline PWA testing

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1551]
DTP [supports](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Response) a `fromDiskCache` and `fromServiceWorker` on the Response object.  It would be useful to expose these props on `Response` so users don't have to hack something together:

```js
page._client.on('Network.responseReceived', result => {
  if (!resp.fromServiceWorker) {
    console.log('Not cached by sw:', result.response.url);
  }
});
```

**Use cases**
1. allow authors to verify a sw is caching the expected assets.
2. allow authors to identify which requests are _not_ being cached by sw. Catch regressions on their offline experience.

I hit number 2 recently. Thought I was caching something that I wasn't:

<img width="1160" alt="screen shot 2017-12-07 at 3 40 46 pm" src="https://user-images.githubusercontent.com/238208/33747868-4066a8c6-db7a-11e7-98a2-6af1ab7b3caf.png">

---
I originally approached this similar to the Lighthouse solution: load the PWA, wait for service worker to cache assets, go offline, reload the page and listen for responses that are `!== 200`. 

```js
const page = await browser.newPage();
await page.goto('https://www.chromestatus.com/features', {waitUntil: 'networkidle0'});

await page.evaluate('navigator.serviceWorker.ready'); // wait for sw to become active

await page.setOfflineMode(true); // go offline

page.on('response', resp => {
  if (resp.status !== 200) {
    ...
  }
});

await page.reload({waitUntil: 'networkidle0'});
```

However, this **doesn't work** in Puppeteer. Using Puppeteer, many of the responses will come from the disk cache after the page reload. So, it looks like the responses work offline but they don't!  In Lighthouse, we [disable the disk cache](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L951-L958) to avoid this issue.

Another approach I thought of is to inject code into the page and examine what's in `window.caches`. But that's 1000% overkill.

...much easier to make`fromDiskCache` and `fromServiceWorker` available 👍.

**Comment by aslushnikov** [comment]
These would be nice to have. It's easy to add, the values should be pulled into the response object similarly to the `response.url`:

https://github.com/GoogleChrome/puppeteer/blob/a164524c72443920e0f008d62c5362c08a7794a0/lib/NetworkManager.js#L429-L447

**Comment by JulianKlug** [comment]
+1
