### ISSUE TITLE
When to use `networkidle2`?

### ISSUE THREAD

**Issue by armanm** [puppeteer/puppeteer#1552]
I'm reading the docs for `networkidle2` and understand what it will do but the docs don't really outline its use or why `2` connections instead of 1 or 5. Basically when should one use this flag?

**Comment by mboeser** [comment]
@armanm my best guess would be that some sites are always pinging servers for tracking/analytics purposes every few seconds so setting the network request to a set variable could account for those events. An example could be, the network is consider idle even though there's 2 request happening every so often in 30 seconds (default timeout). Puppeteer would timeout if the network idle was always set to 0... This is a great feature to have for developers to use IMHO.

**Comment by aslushnikov** [comment]
@armanm both `networkidle0` and `networkidle2` events are heuristics to determine page load state. We picked these since we find them working quite good for a lot of real-world use cases.

**Comment by armanm** [comment]
@aslushnikov apologies for continuing the conversation as I don't believe you've answered the question. 

> we find them working quite good for a lot of real-world use cases

You speak of real-world use cases and that is exactly the purpose of this issue. Could you outline an example of such use case?

**Comment by aslushnikov** [comment]
@armanm I won't be giving any specific URLs, but a few of the common scenarios are:
- `networkidle0` comes handy for SPAs that load resources with `fetch` requests.
- `networkidle2` comes handy for pages that do long-polling or any other side activity.

Do you have any concerns about these signals?

**Comment by tomgallagher** [comment]
@aslushnikov 

I have a question on this. Let's say I'm happy to wait for 
>  networkidle2 

but 3 connections remain open. Am I right in saying that the page.goto will then return the promise when the default 30 second time out is hit, assuming I've left it at default? I also read that it will throw an error at this point. Does that mean that node will move on from the await statement?

Sorry, such basic questions. I think the networkidle2 is genius. I've been looking for this event in Javascript or the Chrome Extension APIs for years.

**Comment by aslushnikov** [comment]
> Am I right in saying that the page.goto will then return the promise when the default 30 second time out is hit, assuming I've left it at default?

@tomgallagher that's right

> Does that mean that node will move on from the await statement?

Yes and no; It will reject the async function promise.

>  I think the networkidle2 is genius. I've been looking for this event in Javascript or the Chrome Extension APIs for years.

Thank you, we're happy it helps!

**Comment by tomgallagher** [comment]
@aslushnikov 

Could you by any chance point me to the bit of code in Puppeteer that delivers the networkidle event? And do you happen to know if the same API is open in the Chrome Extension APIs?

Thanks

**Comment by aslushnikov** [comment]
> Could you by any chance point me to the bit of code in Puppeteer that delivers the networkidle event?

Sure. Lifecycle events are handled in FrameManager:
https://github.com/GoogleChrome/puppeteer/blob/c866c175f8e7c581ba54fe75c5daf97206697b72/lib/FrameManager.js#L647-L653

and later processed in NavigatorWatcher:

https://github.com/GoogleChrome/puppeteer/blob/c866c175f8e7c581ba54fe75c5daf97206697b72/lib/NavigatorWatcher.js#L81-L105

> And do you happen to know if the same API is open in the Chrome Extension APIs?

I don't know. I'm not very familiar with Chrome Extension APIs.

**Comment by tomgallagher** [comment]
Many thanks.

**Comment by amotl** [comment]
## `networkidle2` FTW

@aslushnikov commented on Dec 11, 2017:
> both `networkidle0` and `networkidle2` events are heuristics to determine page load state. We picked these since we find them working quite good for a lot of real-world use cases.

Just wanted to let you know we have been able to successfully use the `networkidle2` lifecycle event when working with ["data" URL](https://tools.ietf.org/html/rfc2397)-based content like

    var payload = "data:image/svg+xml;base64,PD94bWwgdmVy...";
    image.attr('src', payload);

Otherwise, [DeckTape](https://github.com/astefanutti/decktape) would stall indefinitely until timing out, obviously not receiving an appropriate page load event.

We can just second @tomgallagher:
> I think the networkidle2 is genius.

Thanks a bunch!

**Comment by leolux** [comment]
Where is the documentation for networkidle2?

**Comment by vsemozhetbyt** [comment]
@leolux You can search in page for `networkidle2` in [docs/api.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md).

**Comment by shtse8** [comment]
one question, why don't let us to choose the active request count for idle we want?

**Comment by ggorlen** [comment]
> 

[This generalization of networkidle](https://github.com/puppeteer/puppeteer/issues/1353#issuecomment-356561654) might work for you.
