### ISSUE TITLE
How to access a pop up frame?

### ISSUE THREAD

**Issue by yasinAtlibra** [puppeteer/puppeteer#1553]
I am using "puppeteer" and trying to do the following.

Open a page, then click a button, which opens a pop up frame, and in which i want to fill an input.
So far, opening the page, clicking the button is ok, but cannot get the pop up frame.  I tried what other people did.

              const frames = await page.frames();
              await page.waitForSelector(selector_of_popupframe) 
              const myframe = frames.find( f => f.name() === 'popupframe');

However, "myframe" is null, never get it.
I checked inside "find" and find out "f.name()" is empty.
But there are "frames" data.
Help!

**Comment by aslushnikov** [comment]
The pop-ups do not belong to the same page - they're a separate pages.
You can track pages creation with the targets api, e.g. [`targetcreated`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-targetcreated) browser event.

You can connect to the target with the [`target.page`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#targetpage) method.

**Comment by joyfulelement** [comment]
I was looking for the same way to access the popup window. There was a code example on the different thread base on @aslushnikov 's comment. Hope this helps for anyone looking for the actual implementation.

https://github.com/GoogleChrome/puppeteer/issues/2968#issuecomment-408526574
