### ISSUE TITLE
try-puppeteer.appspot.com makes a bad impression about the Puppeteer

### ISSUE THREAD

**Issue by Everettss** [puppeteer/puppeteer#1555]
The fallibility of [try-puppeteer.appspot.com](https://try-puppeteer.appspot.com/) is making a bad impact on the Puppeteer PR. Newcomers probably for the first try of  Puppeteer will go to the try-puppeteer.appspot.com and this site doesn't work too often (as we wish to). **This can have an impact that Puppeteer is broken technology** (not a website).
Possible solutions:

- Remove reference to try-puppeteer.appspot.com
- Or try to make try-puppeteer.appspot.com less unreliable

**Comment by ebidel** [comment]
Agreed :( Unfortunately there are a bunch of stuff I've ran into with this app:
- the key feature is allowing people to run arbitrary code, but that makes it hard to do cleanup work (e.g. reclaim memory) when chrome/pages crashes. Page crashes are pretty frequent and the VM eventually runs out of memory.
- I thought some of the additions to puppeteer's unhandled promises cleanup would help 1, but it didn't. 
- I tried reusing an existing chrome instance across requests, but the node process ends up eating up too much memory. That setup ends up being much worse than launching chrome per request
- headless chrome has bugs ([see /dev/shim issue](https://bugs.chromium.org/p/chromium/issues/detail?id=736452)) in container env like docker.

One thing I still want to try is `dumb-init` but haven't got around to it yet. Until these are addressed, I think it's safe to downplay the demo site. I've removed it from the top of the repo.

**Comment by tnolet** [comment]
@ebidel @Everettss maybe I can help. I've been working on a project of which Puppeteer is quite a large part. As a part of this, I created a playground that is pretty much a rip off of @ebidel 's work (sorry...). I saw this issue and decided to rush it out today. 

I will be developing and supporting this full time: adding server capacity, fixing bugs etc. I think I worked around some of the VM, memory and Docker issues. I'll do a writeup about this later.

Also, I will be adding all the examples from https://github.com/checkly/puppeteer-examples
Feel free to use it or put it in the README.md for people that didn't find this issue:

https://trypuppeteer.com

**Comment by ebidel** [comment]
@tnolet neat. LMK when that writeup is available! Also feel free to send me PRs :)

**Comment by tnolet** [comment]
@ebidel I touched the Puppeteer source code a bit,  and I have one or two ideas about hooks and a configuration options that would make running Puppeteer "at scale in the cloud" a bit more convenient. More to come soon 😎

**Comment by paambaati** [comment]
@tnolet +1, LMK too.

@ebidel Continuing our Chrome-On-Docker discussion, I've recently noticed a few more things that seem to help keep CPU usage down -

1. Run content shell instead of full Chromium. I just discovered this accidentally, but I'd love to learn more about content shell and it's differences from Chromium.
2. Start content shell or Chromium with the `--single-process` flag.

**Comment by sourcec0de** [comment]
@paambaati do you already have an example of using content shell? This sounds like exactly what I'm looking for. Chrome is a hog. 🤣

**Comment by paambaati** [comment]
@sourcec0de Simple; switch out the chrome binary with the content shell. You can download `content-shell.zip` from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/522446/, extract it and run the content_shell executable. Note that this isn't fully tested yet.

**Comment by aslushnikov** [comment]
> I will be developing and supporting this full time: adding server capacity, fixing bugs etc. I think I worked around some of the VM, memory and Docker issues. I'll do a writeup about this later.

@tnolet any chance the writeup is published somewhere?

**Comment by tnolet** [comment]
@aslushnikov sorry, I was off the work grid for a while. Expect it somewhere this week. I'll update here. The TL;DR is:
- separate launcher and runner in two Node processes.
- runner inside Docker.
- Hard timeout on runs.
- Running on Vultr with a bunch of memory.

In the mean time I welcome people to use [https://trypuppeteer.com](https://trypuppeteer.com ).

**Comment by tnolet** [comment]
@aslushnikov @ebidel @paambaati  writeup is published. I went a bit overboard and made it fancy. https://medium.com/@tim_nolet/running-untrusted-javascript-as-a-saas-is-hard-this-is-how-i-tamed-the-demons-973870f76e1c

**Comment by ebidel** [comment]
@tnolet nice writeup of the challenges. I don't suppose you'll be open sourcing it? :) The Docker files might be good pointers for others but I can understand if that's in the cards.

FWIW, dumb-init, but fixes in chromium 64/65 and puppeteer 1.0 have seemed to have solved most of try-puppeteer.appspot.com's issues I was seeing. And that's without https://github.com/GoogleChrome/puppeteer/issues/1834. I suspect we're handling zombie chrome processes better with less memory pressure causing instances to topple over.

**Comment by tnolet** [comment]
@ebidel some bits of the code I will not open source at this point mostly because it is still a bit of hack job really specific to what I'm doing. However the Dockerfile holds no secrets really. What would be a good location to share this? Also, I will change the name to https://puppeteersandbox.com pretty soon to not confuse things too much with your .appspot runner.

**Comment by ebidel** [comment]
Gist or here might be good.

**Comment by tnolet** [comment]
@ebidel https://gist.github.com/tnolet/60393c83d7083e1c39a5fb6f608124cb

This is the current Dockerfile / container running for https://trypuppeteer.com using the following flags for the Docker API when kicking of a container: 

```
HostConfig: {
   ShmSize: 1500000000,
   Binds: [`${tempDir}:${dockerMountDir}`],
   AutoRemove: true,
   Privileged: false,
   Tty: false
}
```

Not had any big issues with this running on a 1 CPU / 2Gig Vultr VM.
