### ISSUE TITLE
Add page.disableCache(boolean)

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1556]
Related to https://github.com/GoogleChrome/puppeteer/issues/1551, it would be useful to have an API call to disable the browser's disk cache. 

Use cases:
- A/B test server caching/config without having to relaunch chrome or use `userDataDir` to do multiple runs.
- Use a single browser instance to test the first load of every view of a SPA. Need to bypass the cache to ensure requests are always fresh for shared resources.

Ref: [`Network.setCacheDisabled`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCacheDisabled)

**Comment by aslushnikov** [comment]
Nice usecases, thanks

This should be easy to implement, similarly to the `setJavascriptEnabled`:

https://github.com/GoogleChrome/puppeteer/blob/a164524c72443920e0f008d62c5362c08a7794a0/lib/Page.js#L564-L566

**Comment by vonGameTheory** [comment]
Yes please.   Is there any approved way of disabling it currently?  The only thing I could come up with was using these at launch:

--media-cache-size=1 
--disk-cache-size=1

 (On linux it was suggested to set the cache directory to /dev/null, but on Windows?)

**Comment by ppatel221** [comment]
Hey, im part of an Open Source Development class at Seneca College and im looking to contribute to an open source project. Can i help with this feature?

**Comment by ebidel** [comment]
@ppatel221 feel free. We're not going to turn down a PR :)

**Comment by amprew** [comment]
I have added this in my open PR ^ (#1609). Although it does depend on your changed in #1601, @ebidel

**Comment by amprew** [comment]
Would be great to get a review on this and with new methods implemented https://github.com/GoogleChrome/puppeteer/pull/1609, thanks!
