### ISSUE TITLE
Add delay option to input methods

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#156]
For `mouse.click`, delay should specify the time between `mouse.down` and `mouse.up`.

For `keyboard.press` delay should specify the time between `keyboard.down` and `keyboard.up`.

For `keyboard.type` delay should specify both the time between each key is pressed, and the time between the `down` and `up`.

**Comment by aslushnikov** [comment]
Could you please explain a scenario where this is needed?

**Comment by JoelEinbinder** [comment]
It seems to be a standard feature of other automation libraries. Maybe you have a search that happens asynchronously as you type?
