### ISSUE TITLE
stack: Error: Protocol error (Page.reload): Target closed.

### ISSUE THREAD

**Issue by murilozilli** [puppeteer/puppeteer#1563]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13-alpha
* Platform / OS version: Ubuntu Debian
* URLs (if applicable): michaelkors.com

After a goto() tried to reload()

_Please include code that reproduces the issue._

```
await page.goto('https://michaelkors.com');
await page.reload();
```
**What is the expected result?**
Reloading the page sucessfully
**What happens instead?**
It freezes and after a while I get that

**Comment by burnpiro** [comment]
Could you show full test suite? Those two lines are correct but you either try to run it in `synch` mode or it's just problem with alpha. There is `^0.13.0` so you could try to upgrade. I've tried with your website and it works fine on Debian.

**Comment by aslushnikov** [comment]
Works fine for me as well; speculatively closing this.
