### ISSUE TITLE
Test Self Certified Local Urls 

### ISSUE THREAD

**Issue by shmdhussain** [puppeteer/puppeteer#1568]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12
* Platform / OS version:Mac OSX 10.10
* URLs (if applicable): Local Url

**What steps will reproduce the problem?**

Trying to automate the self certified my local staging server, but able to go to the page and not able to enter username and password, as my page is saying not secure.  PFA Screenshot

![screen shot 2017-12-10 at 22 55 34](https://user-images.githubusercontent.com/4039657/33821704-4b533fdc-de6e-11e7-9f57-45174c19ae6c.png)

How could I do the testing on self certified https:// sites like my staging server. how could I Override this behavior, any idea, Please share if you got this issue and how you overcome

**What is the expected result?**
able to enter username and password.

**What happens instead?**
Able to go to the page but not able to enter as this page is not secure.

**Comment by aslushnikov** [comment]
Did you try passing `ignoreHTTPSErrors` option for [`puppeteer.launch`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions)?

**Comment by shmdhussain** [comment]
@aslushnikov Thanks for the help. As you mentioned it is working, I should have read the APIbefore asking this , apologising for that.

```
const browser = await puppeteer.launch({

        headless: false,
        ignoreHTTPSErrors: true,
        executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
        args: ["--window-size=2400,1239"]


    });
```
