### ISSUE TITLE
Is browser.newPage() expensive?

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1569]
I'm trying to implement something which needs to handle fairly high rate of incoming requests.  To avoid having to open and close pages frequently, I've implemented a scheme in which I open e.g. 5 pages on setup, and re-use those 5 pages for the incoming requests, sending a new request to a promise chain associated with each page that is handled one-by-one by the page (something like [this](https://github.com/GoogleChrome/puppeteer/issues/486#issuecomment-324221441)).

But I'm wondering if this is really necessary or advisable.  Is there a big overhead in opening and closing a page?  Should I just open a new page for each new request, rather than bother with re-using pages?  I'm concerned now that I might need to account for a situation where one of my pre-prepared pages force-closes itself (crash or similar) and therefore I have to add in extra complexity to replace closed pages with a new page... is that necessary?

**Comment by Khady** [comment]
Pages will crash.
Browser will crash.

I don't know what pages you will open in chrome. But if you are not
controlling/owning all of them, there is a high probability that you will
encounter errors at some points.

I don't know the exact coast of opening a new tab but it seems pretty light
from my experience. Not like launching a new instance of chrome. I'm pretty
curious about an answer with numbers.

If you need a pool, you can get inspiration from
https://www.npmjs.com/package/puppeteer-pool. Not sure there is anything
handling errors tho.

**Comment by aslushnikov** [comment]
@drmrbrewer From my understanding, there should not be noticeable performance difference between "closing page and opening a new one" **vs.** "navigating the page".  At least when you navigate to a different origin.

However, you should avoid having too much open pages in the browser; they'll fight for resources and make things slow.

**Comment by drmrbrewer** [comment]
Thanks for the reply.

> Pages will crash

@Khady If a crash happens, is the page instance thereafter completely unusable, or does puppeteer somehow keep the page open (restart it?), so that you can e.g. navigate to a new url?  I'm not knowledgeable enough yet to know how this is handled internally.

> there should not be noticeable performance difference

@aslushnikov OK thanks.  I'll try a different approach, just opening a new page for each request and closing it when done.  If the page crashes, then it won't have an effect on the next request.

**Comment by drmrbrewer** [comment]
Also @Khady, regarding the `puppeteer-pool` package, sorry for the dumb question but why is it useful to open multiple `browser` instances... is it any different to opening a single `browser` and using that to open multiple `pages`?  Is there a performance benefit one way or the other?

**Comment by Khady** [comment]
@drmrbrewer 

> If a crash happens, is the page instance thereafter completely unusable, or does puppeteer somehow keep the page open (restart it?), so that you can e.g. navigate to a new url? I'm not knowledgeable enough yet to know how this is handled internally.

puppeteer doesn't do anything magical for you (and I think it's good, I don't want to load a page a second time if it crashed the first time and I want to control how many time a single page is loaded). When a tab crashes, you have to deal with it on your side. Catch the possible errors, close it (maybe, not always possible), open a new one.

> regarding the puppeteer-pool package, sorry for the dumb question but why is it useful to open multiple browser instances... is it any different to opening a single browser and using that to open multiple pages? Is there a performance benefit one way or the other?

I don't know what are the performances benefits of 5 browsers with 1 tab VS 1 browser with 5 tabs. I didn't benchmark this. And I guess it depends if you want lower memory usage, lower cpu usage, faster page loading, maximum number of pages per seconds...

I was mostly giving the link as a possible inspiration on how to manage a pool of tabs. It would require small changes over the library, but nothing crazy.

**Comment by Khady** [comment]
@drmrbrewer also the performances will be different for headful and headless modes.

**Comment by reothues** [comment]
according to this ：https://chromium.googlesource.com/chromium/src/+/lkgr/docs/threading_and_tasks.md

> 
> Threads
> Every Chrome process has
> 
> a main thread
> in the browser process: updates the UI
> in renderer processes: runs most of Blink
> an IO thread
> in the browser process: handles IPCs and network requests
> in renderer processes: handles IPCs
> a few more special-purpose threads
> and a pool of general-purpose threads

it seems there's only one thread for UI. and many more for the others.
So it makes sense to use 1 browser - 1 page pool for heavy UI and 1 browser - multiple pages pool for heavily something else. i find that it is quite expensive to open browser every time ( ~ 1000ms ). so i prefer not to work without pooling.

**Comment by reothues** [comment]
according to this ：https://chromium.googlesource.com/chromium/src/+/lkgr/docs/threading_and_tasks.md

> 
> Threads
> Every Chrome process has
> 
> a main thread
> in the browser process: updates the UI
> in renderer processes: runs most of Blink
> an IO thread
> in the browser process: handles IPCs and network requests
> in renderer processes: handles IPCs
> a few more special-purpose threads
> and a pool of general-purpose threads

it seems there's only one thread for UI. and many more for the others.
So it makes sense to use 1 browser - 1 page pool for heavy UI and 1 browser - multiple pages pool for heavily something else. i find that it is quite expensive to open browser every time ( ~ 1000ms ). so i prefer not to work without pooling.
