### ISSUE TITLE
response.headers should not be in lowercase

### ISSUE THREAD

**Issue by HanXHX** [puppeteer/puppeteer#1573]
**Tell us about your environment:**

* Puppeteer version: master branch

**What steps will reproduce the problem?**

`response.headers`: all headers keys are lower case

Ex: `response.headers.['content-type']` is not a valid HTTP1.1 header...

**What is the expected result?**

Can you provide an option to have "real" headers keys?

**Comment by ebidel** [comment]
Is that true? According to https://stackoverflow.com/a/41169947/274673, header names are case-insensitive in both http1.1 and h/2.

This was changed in https://github.com/GoogleChrome/puppeteer/commit/66912a7277a7baf99ff25d23a7531ee39521b1ea and the docs call out headers by all lower case.

**Comment by HanXHX** [comment]
Case-insensitive OK... Ty for the link.

But it should not force lowercase on all keys...

**Comment by aslushnikov** [comment]
@HanXHX header names are lower-case intentionally so that it's easy to query them.
