### ISSUE TITLE
Selecting context menu options

### ISSUE THREAD

**Issue by bittlingmayer** [puppeteer/puppeteer#1575]
It seems that context menu is a native element and outside of the document, and thus belongs in `Page`, similar to screenshot functionality and so on.

It can be hacked with keydown events and keyboard events or maybe even selectors, and that's how it is in Selenium, but that's not ideal.

**Comment by ebidel** [comment]
Indeed. This is similar to https://github.com/GoogleChrome/puppeteer/issues/1306. Context menus live outside the browser, at the OS level.

AFAIK, there's no way to interact with context menus from a page, other than the `contextmenu` event. We can't do much in the Puppeteer-space to make this work.

**Comment by bittlingmayer** [comment]
Chrome Extensions support adding and removing items to and from the context menu so it seems that the browser has some hooks.

**Comment by bittlingmayer** [comment]
Is there a recommended way to do this for now?

The context menu opens on right click but, at least on MacOS, `keyboard.press('ArrowDown')` does not work.  (If I actually press the down arrow it does work.)  Same for other ways to navigate the menu like typing letters.

**Comment by ebidel** [comment]
Right, all of those interactions are at the OS level. Meaning they live outside the browser/puppeteer space. There's no workaround AFAIK.

Do other automation frameworks support similar features?

**Comment by bittlingmayer** [comment]
> Do other automation frameworks support similar features?

No and yes.

Not in any first-class way.  You probably know better than I do.  With Selenium it's possible to navigate the opened context menu with the arrow keys (most common from what I see) or to type to effectively "find" by text (less brittle in my opinion).

(I'm more or less trying to port code I wrote in Python with Selenium to Node with Puppeteer, but right now it seems I will have to use Node with Selenium.)

But those that come to mind are third-party tools supporting multiple browsers (and multiple programming languages...), not an official tool living in a repo of one browser.

If supporting automated testing of Extensions is a goal then it seems natural to provide a bit more context menu support.

**Comment by ebidel** [comment]
> If supporting automated testing of Extensions is a goal then it seems natural to provide a bit more context menu support.

Headless chrome does not support extensions https://github.com/GoogleChrome/puppeteer/issues/1215#issuecomment-344836311

**Comment by aslushnikov** [comment]
Closing this since it seems there's not much interest in context menus. We can always revisit this later.

**Comment by VikramTiwari** [comment]
Hey @bittlingmayer were you able to make this work?

**Comment by bittlingmayer** [comment]
@VikramTiwari No, I dropped Puppeteer and just used Selenium, and did what I needed to do with flags to Chrome.

**Comment by avalanche1** [comment]
I'm developing an extension that uses context menus extensively. I would like puppeteer to support context menu testing.

**Comment by tommydamiano** [comment]
was this ever solved? having the same problem selecting from context menus on mac

**Comment by a-y-u-s-h** [comment]
Reopen this please.

**Comment by IgnacioYanjari** [comment]
@avalanche1 what is the extension's name? did u finish that extension? I really need a best approach instead of using only arrow keys to navigate through options

**Comment by avalanche1** [comment]
@IgnacioYanjari I'm not sure what you're asking. DM me on instagram @mister.kat.il.magnifico, I'll try to help

**Comment by verhovsky** [comment]
> It can be hacked with keydown events and keyboard events

Can it? I'm trying to implement "open in new tab" on macOS by doing just that

```js
    await page.click('a', { button: "right" }); // right click the first <a></a> element
    await page.waitForTimeout(1000);
    await page.keyboard.press('ArrowDown');  // move to the first item in the context menu
    await page.waitForTimeout(1000);
    await page.keyboard.press('Enter'); // open the first item
    await page.waitForTimeout(1000);
```

but it has same effect as left-clicking the link. It opens the link in the current tab instead of a new tab. I suspect `.click()` causes the element to be highlighted and then `.press('Enter')` presses Enter on the highlighted element. It doesn't select the first option in the context menu (which is normally "Open Link in New Tab" when right clicking on links) like I wanted.
