### ISSUE TITLE
Support setting 'prefs' and other experimental options

### ISSUE THREAD

**Issue by bittlingmayer** [puppeteer/puppeteer#1577]
Selenium Webdriver for Python's equivalent to option `args` is this:
```
    chrome_options.add_argument("--lang=yi")
    chrome_options.add_argument("--enable-accelerated-2d-canvas")
```
It also support an additional set of experimental options, which includes a very useful one for preferences.
```
    chrome_options.add_experimental_option('prefs', {
        "intl": {"accept_languages": tl}
    })
```
The alternative to this would be to find, parse and modify the actual preferences file on the device, and optionally remember to undo the changes after the test has finished.

Also, should Puppeteer really be referring users to peter.sh/experiments/chromium-command-line-switches/ for the list of Chromium flags?  Is there no more official Chromium or Chrome documentation of the flags?  (Possible values for `prefs` are not document there, and in the case of nested structures the string format is not trivial.)

**Comment by ebidel** [comment]
peter.sh/experiments/chromium-command-line-switches/ is has been the long-standing resource for many years. Official chromium.org docs reference it. Peter also works on the Chrome team :)

**Comment by bittlingmayer** [comment]
Any list that long that is not auto-generated is going to be burdensome to maintain.  I know he works on the team and that it's common to reference it since the early days of Chrome, but now billions of people depend on Chrome and it's not updated and it does not include everything.

For example, the experimental arguments like prefs.

**Comment by ebidel** [comment]
That list _is_ auto generated from chromium source.

**Comment by skyiea** [comment]
@aslushnikov Why was it closed? It's still unclear how to provide Chrome instance with `prefs`/`localState`. Using *ChromeDriver*'s `chromeOptions` (https://sites.google.com/a/chromium.org/chromedriver/capabilities) I could set something like this:
```js
prefs: {
    download: {
        prompt_for_download: false,
        default_directory: DOWNLOAD_PATH,
    }
},
localState: {
    browser: {
        "enabled_labs_experiments": [
            // All preferences can be found here: https://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/pref_names.cc?view=markup
            "enable-native-notifications@2",
        ],
    }
},
```
Is it possible to do the same with *puppeteer*? (I saw the workaround for setting download dir through `_client`, but the question is more general)
