### ISSUE TITLE
Demo: new search + scrape demo using protocol viewer

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1578]
We [removed](https://github.com/GoogleChrome/puppeteer/pull/1564) the google search demo b/c it was violating the TOS. Let's create a similar demo usinghttps://chromedevtools.github.io/devtools-protocol/  that shows similar features: typing, click, scrape results.

**Comment by schelkun** [comment]
Bad example with shadow-root. Choose another site.

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/pull/1586.

**Comment by schelkun** [comment]
Close issue?

**Comment by ebidel** [comment]
The PR is still open...
