### ISSUE TITLE
Touch input events

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#158]
Simulating touch events is difficult.

For tapping:
`Input.synthesizeTapGesture` appears to only work on android
`Input.dispatchTouchEvent` doesn't click events like normal tapping would
`Input.emulateTouchFromMouseEvent` fires mouse events, but only after an undefined delay.

The best way to emulate touch right now appears to be setting the device mode to iPhone, which sends `touchStart` and `touchEnd` along with every mouse press.

**Comment by LHoin** [comment]
Why not just provide API like touchScreen.touchStart/touchMove/touchEnd, so we can do Swipe by combining these methods ?

**Comment by zhgqthomas** [comment]
@LHoin I forked a version that add touch move/down/up in TouchScreen. But it using Emulation.setEmitTouchEventsForMouse which still in EXPERIMENTAL.

Check out this commit: https://github.com/zhgqthomas/puppeteer/commit/9f54be7bd5937c4224e10554b76270ce7357ef8a

**Comment by RainUUU** [comment]
> @LHoin I forked a version that add touch move/down/up in TouchScreen. But it using Emulation.setEmitTouchEventsForMouse which still in EXPERIMENTAL.
> 
> Check out this commit: [zhgqthomas@9f54be7](https://github.com/zhgqthomas/puppeteer/commit/9f54be7bd5937c4224e10554b76270ce7357ef8a)

Will event. isTrusted be true in the browser in this form of simulation?

**Comment by RainUUU** [comment]
> @LHoin I forked a version that add touch move/down/up in TouchScreen. But it using Emulation.setEmitTouchEventsForMouse which still in EXPERIMENTAL.
> 
> Check out this commit: [zhgqthomas@9f54be7](https://github.com/zhgqthomas/puppeteer/commit/9f54be7bd5937c4224e10554b76270ce7357ef8a)

I tried your code, called tap method, and the page scrolled, but the JS in the page could not  listen the touchmove event.

js code:
document.addEventListener("touchmove",function(e){
 	console.log("touchmove:");
    console.log(e);
},false);

**Comment by zhgqthomas** [comment]
@RainUUU I tested the codes. And the `touch start`, `touch move` and `touch end` event all get called. Maybe you can look into the codes again. And the tap method will not trigger the touchmove event

**Comment by danilogacevic** [comment]
@zhgqthomas So, you trigger `touch move` event with `mouse down` + `mouse move` ?
