### ISSUE TITLE
Add page.on('domcontentloaded', callback)

### ISSUE THREAD

**Issue by webnard** [puppeteer/puppeteer#1580]
The page object has the ability to .wait() for the [DOMContentLoaded event](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options). It also emits the ['load' event](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-load).

It'd be nice to have a way to listen for the DOMContentLoaded event on the main frame, whether through `page.on('domcontentloaded', ...)` or through `page.mainFrame().on('domcontentloaded', ...)`.

There are cases where I want to evaluate the DOM as soon as it's ready on every navigation, and injecting JavaScript to handle it or having to call certain methods after every `goto(url, {waitUntil: 'domcontentloaded'})` is cumbersome. Emitting the DOMContentLoaded would keep things consistent between the `goto()` wait options and what is currently offered by the page's event emitter.

**Comment by sradu** [comment]
+1
