### ISSUE TITLE
(docs proposal) add example tool: headless-chrome-crawler

### ISSUE THREAD

**Issue by yujiosaka** [puppeteer/puppeteer#1582]
I have made and have been maintaining a crawler called [headless-chrome-crawler](https://github.com/yujiosaka/headless-chrome-crawler) with the following features:

* Configure concurrency, delay and retry
* Pluggable cache such as [Redis](https://redis.io) to skip duplicate requests
* Pause and resume at any time
* Insert [jQuery](https://jquery.com) automatically
* Priority queue

It's based on Puppeteer, and I think it's a good example making a module using Puppeteer.
If you think it's worth adding to the examples' README, I'll make a small PR for that.

**Comment by ebidel** [comment]
Looks neat. You thinking under "Rendering and web scraping"?

**Comment by yujiosaka** [comment]
Yes, that's right!

**Comment by mboeser** [comment]
Nice work @yujiosaka!  @ebidel not sure if this is doc worthy yet but I was testing out Puppeteer for to simply gathering URL for the same site and found it to be rather simple with just a few lines of code. Feel free to take a look and use it for your own projects. Apologies for the spaghetti code... still adapting to es6 syntax. Very much enjoying using Puppeteer with node! [SimplePuppeteerCrawler](https://github.com/mboeser/SimplePuppeteerCrawler/blob/master/SimplePuppeteerCrawler.js)
