### ISSUE TITLE
Closing all browser windows clears service worker cache?

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1583]
Most of the examples in the docs (e.g. [this one](https://github.com/GoogleChrome/puppeteer#usage)) launch puppeteer, and then immediately open a new page.  I discovered that this actually leaves you with _two_ pages, so there must have been one to start with:

    (async () => {
      const browser = await puppeteer.launch();
      const page = await browser.newPage(); // now two pages
      const pages = await browser.pages();  
      console.log('page count:', pages.length); // confirms two pages
      await browser.close();
    })();

So I thought I'd be clever, and remove the unwanted page after launching, since I am opening / closing a page each time a new request comes in... no need for the first page:

    (async () => {
      const browser = await puppeteer.launch();
      var pages = await browser.pages();  
      await pages[0].close(); // close the initial page
      const page = await browser.newPage(); // add one of my own
      pages = await browser.pages();  
      console.log('page count:', pages.length); // confirms just one page
      await browser.close();
    })();

But what I was then finding was that, as my page count rises up from zero, then one, then two (as each request comes in and new pages are opened), then back down to one, then zero (as the pages finish rendering and are closed), the service worker cache no longer seemed to persist... so the next time I open a new page (page count goes to one), the resources are not fetched from service worker.

Is this expected?  i.e. when the page count hits zero, is the cache cleared?  Or is this a bug?  When I leave that initial page alone, so that the page count never drops below one, service worker caching works entirely as I would expect.

**Comment by ebidel** [comment]
Can you provide full puppeteer code and site (with the service worker that's caching resources) so we can take a look?

**Comment by drmrbrewer** [comment]
@ebidel Hmm, I created a demo but can no longer reproduce this... either in the demo or in my actual code :-(  If I can reproduce it in future I'll open another issue.  Thanks.

**Comment by drmrbrewer** [comment]
FWIW @ebidel, I think that the cause of the issue I was seeing above is actually that which I've now identified in this [new issue](https://github.com/GoogleChrome/puppeteer/issues/1596)... i.e. not the service worker cache being cleared unexpectedly by some trigger, but rather that I am prevented by some trigger (quota exceeded) from saving further stuff into the service worker cached  These both result in a network fetch for content even when I'd expect the service worker to have the content already from a previous fetch, but the cause is different.
