### ISSUE TITLE
Can't get image dimensions with naturalWidth and naturalHeight

### ISSUE THREAD

**Issue by damien-monni** [puppeteer/puppeteer#1588]
I am trying to get images dimensions using the $$eval function but I undefined is returned.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Ubuntu 16.04

**What steps will reproduce the problem?**

``` javascript
const images = await page.$$eval('img', img => img.naturalWidth);
console.log(images);
```

**What is the expected result?**
``` javascript
[1920, 1920, 1920]
```

**What happens instead?**
`undefined`

**Comment by vsemozhetbyt** [comment]
I think the function should be this one (as the first argument is an Array):
```js
const images = await page.$$eval('img', imgs => imgs.map(img => img.naturalWidth));
console.log(images);
```

**Comment by damien-monni** [comment]
I see, my bad! Thank you.
