### ISSUE TITLE
Handling of browser crash

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1589]
It's not clear to me the relationship between Puppeteer, the browser, and the Chromium instance (process).

It seems from the docs [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-puppeteer) that `puppeteer.launch()` launches a Chromium instance, which is associated with a `browser`.

And then for `browser.disconnect()` [the docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserdisconnect) say: 

> Disconnects Puppeteer from the browser, but leaves the Chromium process running. After calling disconnect, the browser object is considered disposed and cannot be used anymore.

Does the same happen when something causes the `browser` to crash?  Does the Chromium instance survive, but the `browser` is no longer valid, so that you can restore things by reconnecting to the Chromium instance?

In other words, is the following the correct way to recover from a `browser` crash, or should we use `puppeteer.launch()` again instead?  How do we tell if the Chromium instance is still working (so that we can reconnect to it)?

    const browser = await puppeteer.launch(launchOptions);
    this.browserWSEndpoint = browser.wsEndpoint(); // store for later

	var self = this;
    browser.on('disconnected', async () => {
        self.browser = await puppeteer.connect({browserWSEndpoint: self.browserWSEndpoint});
    });

The docs suggest to me that the above is correct for dealing with a browser crash, because [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-disconnected) it says that the `disconnected` event on the `browser` is emitted when the "browser closed or crashed".

**Comment by aslushnikov** [comment]
@drmrbrewer I'm sorry for the inconvenience; I clarified the docs.

The `disconnected` event is sent when the Chromium instance is crashed; reconnecting to a crashed instance won't work.

You can get a handle to the chrome process with the [`browser.process()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserprocess) method.

**Comment by drmrbrewer** [comment]
@aslushnikov so is the following a reasonable way of recovering from a crash?

    this.browser = await puppeteer.launch(launchOptions);
    var self = this;
    browser.on('disconnected', async () => {
        self.browser = await puppeteer.launch(launchOptions);
    });

**Comment by aslushnikov** [comment]
@drmrbrewer yes, looks reasonable

**Comment by Jaccccccccccccccccccccccccccccck** [comment]
@aslushnikov My code is like this, when browser crash, a new browser will open. But when the new browser crash, the third browser would not show up. How should i do if i want a endless browser that a new will show up when crash?
![image](https://user-images.githubusercontent.com/26106110/39342741-fbac0252-4a0b-11e8-8412-919d386e0518.png)

**Comment by aslushnikov** [comment]
@Jaccccccccccccccccccccccccccccck you should re-subscribe for the 'disconnected' event once you've re-started the browser.

**Comment by Jaccccccccccccccccccccccccccccck** [comment]
class PuppeteerService {
    
    constructor (){
        let createBrowser = async () => {
            console.log('Launching browser...');
            this.browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
            this.browser.on("disconnected", createBrowser);
            console.log('Init...Done');
        }

        (async () => {
            await createBrowser();
        })();
    }
}
const puppeteerService = new PuppeteerService();

@aslushnikov  this way, I can always  get a new browser use puppeteerService.browser. However，if crash, there will be a re-open time while which browser can not use.

**Comment by iROOT** [comment]
Faced a problem, if the computer is put into sleep mode, the connection is lost and the disconnected event is triggered, although the browser itself continues to work normally.
It turns out that you can kill the child process before starting a new one or reconnect to it (how?).
```javascript
let browser;

const puppeteerLaunch = async () => {
  browser = await puppeteer.launch({});
  browser.on('disconnected', () => {
    if (browser.process() != null) browser.process().kill('SIGINT');
    puppeteerLaunch();
  });
};
```

**Comment by tim-kozak** [comment]
My resource manager
```
const puppeteer = require('puppeteer')

const USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3239.108 Safari/537.36';

function ResourceManager() {
    let browser = null;

    this.init = async () => {
        browser = await runBrowser();
        browser.on('disconnected', async () => {
            console.log("BROWSER CRASH")
            await this.release();
            if (browser.process() != null) browser.process().kill('SIGINT');
            browser = await runBrowser();
        });
    };

    this.release = async  () => {
        if (browser) await browser.close();
    }

    this.createPage = async (url) => {
        return await createPage(browser,url);
    }

    async function runBrowser () {
        return puppeteer.launch({
            headless: true,
            devtools: false,
            ignoreHTTPSErrors: true,
            slowMo: 0,
            args: ['--disable-gpu','--no-sandbox','--disable-setuid-sandbox','--disable-dev-shm-usage']
        });
    }

    async function createPage (browser,url) {
        const page = await browser.newPage();
        await page.setViewport({
            width: 1920,
            height: 3000,
            deviceScaleFactor: 1,
            hasTouch: false,
            isLandscape: false,
            isMobile: false,
        });
        await page.setUserAgent(USER_AGENT);
        await page.setJavaScriptEnabled(true);
        await page.setDefaultNavigationTimeout(0);
        
       //skips css fonts and images for performance and efficiency
        await page.setRequestInterception(true);
        page.on('request', (req) => {
            if(req.resourceType() == 'stylesheet' || req.resourceType() == 'font' || req.resourceType() == 'image'){
                req.abort();
            }
            else {
                req.continue();
            }
        });

        await page.goto(url, {  waitUntil: 'networkidle2',timeout: 0});
        // await page.addScriptTag({url: 'https://code.jquery.com/jquery-3.2.1.min.js'});
        return page;
    }
}

module.exports = {ResourceManager}

```

**Comment by Big-al** [comment]
@tim-kozak 's example helped us a lot in understanding some browser options. For anyone else using typescript, i'd like offer up 
 my initial quick rewrite of Tim's example in ts.

```
Import puppeteer from 'puppeteer';
Import { LoggingService, LogLevel } from './LoggingService';
const Logger: LoggingService = LoggingService.getInstance();

export class Browser implements IBrowser {
    private browser: puppeteer.Browser;
    private readonly TIMEOUT: number;
    private readonly USER_AGENT = 'INSERT_USERAGENT';

    constructor(_timeout: number = 30000) {
        this.TIMEOUT = _timeout;
        
        // For debugging try these Puppeteer Params: 
        // headless: true
        // executablePath: PathToCustomChromiumInstall 
        // devtools: true
        // slowMo: 2000
        
        // Starting the async Init flow  
        (async () => {
            await this.Init();
        })();
    }

    public async GetBrowserInstance(): Promise<puppeteer.Browser> {
        return this.browser;
    }

    public async CreatePage(URL: string, options: puppeteer.DirectNavigationOptions = {waitUntil: 'load'}): Promise<puppeteer.Page> {
        const page = await this.browser.newPage();

        await page.setViewport({
            width: 1920,
            height: 1080,
            deviceScaleFactor: 1,
            hasTouch: false,
            isLandscape: false,
            isMobile: false,
        });

        await page.setUserAgent(this.USER_AGENT);
        await page.setJavaScriptEnabled(true);
        await page.setDefaultNavigationTimeout(this.TIMEOUT);
        
        //skips css fonts and images for performance and efficiency
        await page.setRequestInterception(true);
        page.on('request', (req) => {
            if(req.resourceType() == 'font' || req.resourceType() == 'image' || req.resourceType() == 'stylesheet' ){
                req.abort();
            }
            else {
                req.continue();
            }
        });

        try {
            await page.goto(URL, options);
        } catch (err) {
                await page.close();
                throw err;
        }

        return page;
    }

    private async Init(HeadLess: boolean = true, SlowDown: number = 0, DevTools: boolean = false) {
        Logger.Log("Puppeteer browser init. Timeout set to: " + this.TIMEOUT.toString(), LogLevel.Trace);
        this.browser = await this.StartBrowser(HeadLess, SlowDown, DevTools);

        // Listen to Disconnect event, and restart.
        this.browser.on('disconnected', async () => {
            Logger.Log("Puppeteer browser crashed, Restarting browser.", LogLevel.Error);
            await this.ReleaseBrowser();
            if (this.browser && this.browser.process() != null) this.browser.process().kill('SIGINT');
            await this.Init();
        });
    };

    private async ReleaseBrowser() {
        Logger.Log("Puppeteer browser releasing and closing.", LogLevel.Warning);
        if (this.browser) await this.browser.close();
    }

    private async StartBrowser(HeadLess: boolean, SlowDown: number, DevTools: boolean): Promise<puppeteer.Browser> {
        Logger.Log("Puppeteer browser starting up with slowdown set to: " + SlowDown, LogLevel.Trace);

        return await puppeteer.launch({
            headless: HeadLess,
            devtools: DevTools,
            ignoreHTTPSErrors: true,
            slowMo: SlowDown,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-accelerated-2d-canvas',
                '--no-first-run',
                '--no-zygote',
                '--disable-gpu'
                // '--single-process' 
                // '--user-data-dir=./'
            ]
        });
    }
}

export interface IBrowser {
    GetBrowserInstance(): Promise<puppeteer.Browser>;
    CreatePage(URL: string, options: puppeteer.DirectNavigationOptions): Promise<puppeteer.Page>;
}
```

**Comment by victornpb** [comment]
> this.init = async () => {
>         browser = await runBrowser();
>         browser.on('disconnected', async () => {
>             console.log("BROWSER CRASH")
>             await this.release();
>             if (browser.process() != null) browser.process().kill('SIGINT');
>             browser = await runBrowser();
>         });
>     };

IK this thread is old, but before someone uses this code, I don't think it is correct.

When it crashes, the onDisconected handler calls "runBrowser()" and replaces `browser` with a fresh instance, but it doesn't register a new `on('disconnected', fn)` event. So it will only recover a crash once.

The on('disconnected') needs to be inside runBrowser and not inside the init

**Comment by tim-kozak** [comment]
@victornpb Here is the latest version of my Resource Manager
I added a lot of things to bypass the captcha cases and make it more stable 

```
const puppeteer = require('puppeteer-extra')
const randomUseragent = require('random-useragent');
const StealthPlugin = require('puppeteer-extra-plugin-stealth')

const USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36';
puppeteer.use(StealthPlugin())

function ResourceManager(loadImages) {
    let browser = null;
    const _this = this;
    let retries = 0;
    let isReleased = false;

    this.init = async () => {
        isReleased = false;
        retries = 0;
        browser = await runBrowser();
    };

    this.release = async () => {
        isReleased = true;
        if (browser) await browser.close();
    }

    this.createPage = async (url) => {
        if (!browser) browser = await runBrowser();
        return await createPage(browser,url);
    }

    async function runBrowser () {
        const bw = await puppeteer.launch({
            headless: true,
            devtools: false,
            ignoreHTTPSErrors: true,
            slowMo: 0,
            args: ['--disable-gpu','--no-sandbox','--no-zygote','--disable-setuid-sandbox','--disable-accelerated-2d-canvas','--disable-dev-shm-usage', "--proxy-server='direct://'", "--proxy-bypass-list=*"]
        });

        bw.on('disconnected', async () => {
            if (isReleased) return;
            console.log("BROWSER CRASH");
            if (retries <= 3) {
                retries += 1;
                if (browser && browser.process() != null) browser.process().kill('SIGINT');
                await _this.init();
            } else {
                throw "===================== BROWSER crashed more than 3 times";
            }
        });

        return bw;
    }
    // userDataDir: '/tmp',

    async function createPage (browser,url) {
		const userAgent = randomUseragent.getRandom();
        const UA = userAgent || USER_AGENT;
        const page = await browser.newPage();
        await page.setViewport({
            width: 1920 + Math.floor(Math.random() * 100),
            height: 3000 + Math.floor(Math.random() * 100),
            deviceScaleFactor: 1,
            hasTouch: false,
            isLandscape: false,
            isMobile: false,
        });
        await page.setUserAgent(UA);
        await page.setJavaScriptEnabled(true);
        await page.setDefaultNavigationTimeout(0);
        if (!loadImages) {
            await page.setRequestInterception(true);
            //TODO: test
            page.on('request', (req) => {
                if(req.resourceType() == 'stylesheet' || req.resourceType() == 'font' || req.resourceType() == 'image'){
                    req.abort();
                } else {
                    req.continue();
                }
            });
        }

        await page.evaluateOnNewDocument(() => {
            Object.defineProperty(navigator, 'webdriver', {
                get: () => false,
            });
        });

        await page.evaluateOnNewDocument(() => {
            // We can mock this in as much depth as we need for the test.
            window.chrome = {
                runtime: {},
                // etc.
            };
        });

        await page.evaluateOnNewDocument(() => {
            const originalQuery = window.navigator.permissions.query;
            return window.navigator.permissions.query = (parameters) => (
                parameters.name === 'notifications' ?
                    Promise.resolve({ state: Notification.permission }) :
                    originalQuery(parameters)
            );
        });

        await page.evaluateOnNewDocument(() => {
            // Overwrite the `plugins` property to use a custom getter.
            Object.defineProperty(navigator, 'plugins', {
                // This just needs to have `length > 0` for the current test,
                // but we could mock the plugins too if necessary.
                get: () => [1, 2, 3, 4, 5],
            });
        });

        await page.evaluateOnNewDocument(() => {
            // Overwrite the `plugins` property to use a custom getter.
            Object.defineProperty(navigator, 'languages', {
                get: () => ['en-US', 'en'],
            });
        });

        await page.goto(url, { waitUntil: 'networkidle2',timeout: 0 } );
        return page;
    }
}

module.exports = {ResourceManager}

```

**Comment by adkuca** [comment]
> @victornpb Here is the latest version of my Resource Manager
> I added a lot of things to bypass the captcha cases and make it more stable
> 
> ```
>     ...
>     this.init = async () => {
>         isReleased = false;
>         retries = 0;
>         browser = await runBrowser();
>     };
> 
>     ....
>     async function runBrowser () {
>         const bw = await puppeteer.launch({
>             headless: true,
>             devtools: false,
>             ignoreHTTPSErrors: true,
>             slowMo: 0,
>             args: ['--disable-gpu','--no-sandbox','--no-zygote','--disable-setuid-sandbox','--disable-accelerated-2d-canvas','--disable-dev-shm-usage', "--proxy-server='direct://'", "--proxy-bypass-list=*"]
>         });
> 
>         bw.on('disconnected', async () => {
>             if (isReleased) return;
>             console.log("BROWSER CRASH");
>             if (retries <= 3) {
>                 retries += 1;
>                 if (browser && browser.process() != null) browser.process().kill('SIGINT');
>                 await _this.init();
>             } else {
>                 throw "===================== BROWSER crashed more than 3 times";
>             }
>         });
> 
>         return bw;
>     }

> ```
and here you're incrementing `release` whilst clearing it every time to 0

**Comment by noumanshahid12** [comment]
> @drmrbrewer yes, looks reasonable

How Can i take  dynamic value or data in table

**Comment by natsu90** [comment]
is there anyway i can know either the browser is crashed or closed from the `disconnected ` event? i only want to relaunch the browser when it is crashed, not when i called `browser.close()`

**Comment by Mike-Jagger** [comment]
@tim-kozak  The stuff you got is awesome!

Just adding 2 things on "properly closing" the test browsers on crash and close (aka killing the browser process completely). I noticed that the browser instances may still run in the background even after you close the browser using the logic found in the `runBrowser` and `release` methods [unless I am just not handling them properly.]

Here are the mods I made on mine:

``` js
async init() {
    ...
    this.browser = await this.runBrowser();
    this.browserWSEndpoint = this.browser.wsEndpoint();
    ...
}
```

``` js
async runBrowser() {
    ...
    bw.on('disconnected', async () => {
        if (this.isReleased) return;
        console.log("BROWSER CRASH");
        if (this.retries <= 3) {
        this.retries += 1;
        const browserToDisconnect = await puppeteer.connect({browserWSEndpoint: this.browserWSEndpoint});

        if (browserToDisconnect) await browserToDisconnect.close();
        if (browserToDisconnect && browserToDisconnect?.process() != null) browserToDisconnect.process().kill('SIGINT');
            await this.init();
        } else {
            throw "BROWSER crashed more than 3 times";
        }
    });
    ...
```

``` js
async release() {
    this.isReleased = true;
    if (this.browser) await this.browser.close();
    if (this.browser?.process() != null) await this.browser.process().kill('SIGTERM');
}
```
Let me know what to add or remove!
