### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.

### ISSUE THREAD

**Issue by philipp-winterle** [puppeteer/puppeteer#1591]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12/0.13
* Platform / OS version: Win 7 x64 / Ubuntu 14.04
* URLs (if applicable):

**What steps will reproduce the problem?**

Iam using [penthouse](https://github.com/pocketjoso/penthouse) and it's using puppeteer. I debugged the code and it came up that the problem is puppeteer related. 
The error happens around 95% in Windows and only to 10% on Unix. After reading some of the other issue reports it is maybe a chromium version problem? 

_Please include code that reproduces the issue._

1. start browser with url
2. crash

**What is the expected result?**
puppeteer returns the valid html to read out the styles.

**What happens instead?**
Error message: Error: Protocol error (Runtime.callFunctionOn): Execution context was destroyed. undefined

**Comment by xprudhomme** [comment]
Might be helpful if you shared your code with us, otherwise we won't know what's going on ..

**Comment by philipp-winterle** [comment]
You are absolutely right, but it is too much and its not related to my code. On the other hand Iam not allowed to share this code. More to the code of penthouse. For that I put the link in the description to have a look at the code. 

I can say that Iam using child processes to speed up what Iam doing and it happens not every time and not at the same time. 
Sorry that I can't help more. :(

**Comment by aslushnikov** [comment]
@hummal the issue arises when your script tries to evaluate code in a page that navigates away.
As a result, evaluation fails with the "execution context was destroyed" error: the execution context indeed got destroyed as the page navigated away.

This is not a chrome issue. Instead, script shouldn't try evaluating in a page that is navigating away. This, however, is not always possible; #823 might help with this to some extend.

**Comment by philipp-winterle** [comment]
As written here: https://github.com/GoogleChrome/puppeteer/issues/1325#issuecomment-357645094
I got the same problem and if I do the `page.waitFor(100)` the errors are gone. So correct me if Iam wrong but this can not be a problem with navigating away?
