### ISSUE TITLE
cannot get frame with args: ['--no-sandbox', '--disable-setuid-sandbox'] ? 

### ISSUE THREAD

**Issue by yasinAtlibra** [puppeteer/puppeteer#1592]
Using puppeteer for automating tests.

1) to  run on docker, chrome is lunched as follows.

       puppeteer.launch({  args: ['--no-sandbox', '--disable-setuid-sandbox'] })
or 
    
       puppeteer.launch()

But, I cannot get a frame by the following code.

      await this.page.waitForSelector( selectorOfStripe )
      const frames = this.page.frames();
      for(var i =0 ;i < frames.length; i++ )
      {
            console.log(`${i}-th frame has name: ${frames[i].name()}`)
            if(frames[i].name() === "stripe_checkout_app" )
            {
                this.stripeFrame = frames[i]
            }
      }
      if(!this.stripeFrame){
        console.log('###### stripe is null')
      }
      else{
        console.log('####### strike is Ok!')
      }

The log is like below.

      0-th frame has name: 
      1-th frame has name: 
      ###### stripe is null

2) However, if chrome is lunched as following.

    puppeteer.launch({  slowMo: 200, args: ['--no-sandbox', '--disable-setuid-sandbox'] })

then, I can get the frame, the log is as follows. 

    0-th frame has name: 
    1-th frame has name: stripe_checkout_app
    2-th frame has name: 
    3-th frame has name: 
    ####### stripe is Ok!

In the first case, sometimes it works, but most of the times, it fails to get the stripe.
In the second case, it always works.

What is the reason for such strange behavior?
How can I make it work in the first case?

**Comment by aslushnikov** [comment]
The culprit seems to be in the `slowMo` argument that slows down the puppeteer script and gives page enough time to reach desired state.

I'd use the `page.waitForSelector` / `page.waitForFunction` methods to make sure page is in desired state.
