### ISSUE TITLE
Quota Exceeded error

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1596]
I seem to be hitting a limit when putting new entries into an IndexedDB within a service worker in puppeteer: the error returned is "Quota exceeded".  The db is really quite small though, and I've not seen this outside of puppeteer.  Is there any way to increase or remove the quota?

**Comment by ebidel** [comment]
Please provide full code that repros the issue. By chance, are you launching chrome and reusing a `userDataDir`?

**Comment by drmrbrewer** [comment]
@ebidel I made (slightly) the wrong call.  I am actually putting stuff into IndexedDB *and* the service worker cache *at the same time*, in a Promise.all(), and I'm pretty sure now that the error from this parallel promise actually relates to the service worker operation and not the IndexedDB operation:

    var promise = Promise.all([
        cache.put(cacheKey, response),  // service worker cache
        idbKeyval.set(cacheKey, info)   // https://github.com/jakearchibald/idb-keyval
    ]);

    return promise.then(() => {
        // all is OK
        return Promise.resolve();
    }).catch(error => {
        // this is where the "quota exceeded" error is apparent
        return Promise.reject();
    });

I confirmed that the storage quota is indeed being reached, by using the following code snippet by Jeff Posnick from [here](https://developers.google.com/web/updates/2017/08/estimating-available-storage-space):

    if ('storage' in navigator && 'estimate' in navigator.storage) {
      navigator.storage.estimate().then(({usage, quota}) => {
        console.log(`Using ${usage} out of ${quota} bytes.`);
      });
    }

I'm running this in an IDE which does indeed have limited space (which I guess is a good thing for testing)... the above reports that the quota is around 30 000 000 bytes.  Thing is, it fills up pretty rapidly and I need to work out why... I'm not dealing with anywhere approaching 30MB of data with what I'm doing, let alone storing it all in the cache.  When loading my page in desktop Chrome, the storage usage is much more controlled, at around 1.5MB... so something is being cached in the node environment that isn't in the desktop environment.

BTW, yes I am setting `userDataDir` when I launch chrome... is that significant?  I find the same behaviour (same quota reported by Jeff's snippet above, same rapid filling up, and same consequence) even if I don't set a `userDataDir`.  I launch a browser once and re-use the same browser, with the following launch options:

    const userDataDir = path.join(__dirname, '.puppeteer');
    const launchOptions = {userDataDir: userDataDir, args: ['--no-sandbox', '--disable-setuid-sandbox']};
    const browser = await puppeteer.launch(launchOptions);

 And when the quota is reported as being filled up, manually deleting the content of the `userDataDir` *and* restarting the node app puts the "used" value back down to zero, and off we go again.

EDIT... another observation: when the usage is reported (by the above snippet) as being "33 MB out of 29 MB", i.e. the quota has been exceeded, the following is a `du` report on the actual space taken by the `userDataDir`:

	$ du -h .puppeteer/   
	32K     .puppeteer/Default/databases
	376K    .puppeteer/Default/IndexedDB/https_example.com_0.indexeddb.leveldb
	380K    .puppeteer/Default/IndexedDB
	36K     .puppeteer/Default/Service Worker/Database
	8.0K    .puppeteer/Default/Service Worker/ScriptCache/index-dir
	68K     .puppeteer/Default/Service Worker/ScriptCache
	8.0K    .puppeteer/Default/Service Worker/CacheStorage/c9feab23bc6b7c3dab992ee2e1d2ac540d113887/3c613f37-7c30-4049-99fc-914e74a8f703/index-dir
	36K     .puppeteer/Default/Service Worker/CacheStorage/c9feab23bc6b7c3dab992ee2e1d2ac540d113887/3c613f37-7c30-4049-99fc-914e74a8f703
	8.0K    .puppeteer/Default/Service Worker/CacheStorage/c9feab23bc6b7c3dab992ee2e1d2ac540d113887/0d5c7005-e31e-468e-ba1a-0e9463dbcb32/index-dir
	680K    .puppeteer/Default/Service Worker/CacheStorage/c9feab23bc6b7c3dab992ee2e1d2ac540d113887/0d5c7005-e31e-468e-ba1a-0e9463dbcb32
	724K    .puppeteer/Default/Service Worker/CacheStorage/c9feab23bc6b7c3dab992ee2e1d2ac540d113887
	728K    .puppeteer/Default/Service Worker/CacheStorage
	836K    .puppeteer/Default/Service Worker
	1.4M    .puppeteer/Default
	1.4M    .puppeteer/

Looks like the total space taken up by the `userDataDir` is only 1.4MB!  So what is the other 28MB of storage I'm apparently using?  The 1.4MB corresponds quite closely to what I mentioned above in relation to what is being reported by desktop Chrome (using Jeff's code) for the quota being used.

EDIT2: it's not clear to me what the reported quota relates to... as mentioned above, on my IDE (cloud 9) the quota is 30MB,  Since there is around 300MB of free space, I thought maybe that 10% was allocated to `userDataDir`.  But when I run this on heroku, the quota is reported as being around 25 GB... which I find difficult to understand as a heroku instance comes packaged in the 500MB container as I understand it... so I have no idea why puppeteer thinks it has 25 GB available!

**Comment by ebidel** [comment]
That's helpful thanks. Can you share the full puppeteer script that you're running to do all this? It could be a bug in headless Chrome and we'll need something reliable to run and repro.

**Comment by drmrbrewer** [comment]
@ebidel I'll try to pull a simple example together.  But I'm really struggling to find any consistency in the cache figures being reported.  I've now tried the same page on a different desktop Chrome version, and now the "storage used" value being reported is anywhere up to 65 MB!  On the other desktop Chrome it was between 1 and 4 MB.  There is no way on earth that I'm downloading 65 MB worth of resources... it's only a few scripts, a few svg symbols, some data to be plotted on a chart.  What bothers me is that one desktop Chrome says 2 MB, another says 65 MB, and headless Chrome somewhere in the middle.  

Plus the fact that I apparently have 25 GB worth of quota on heroku ... would be nice if true!

Do you have any hints as to how to inspect the cache with DevTools on desktop Chrome?  i.e. so that I can try and determine what that 65 MB is... maybe I've overlooked some resources?  I can see stuff under Cache > Cache Storage (looks like service worker cache).  And stuff under Storage > IndexedDB.  But nothing under Cache > Application Cache.  I can't see what that 65 MB might relate to.

Furthermore, in desktop Chrome when I click on Clear Site Data with the following settings (clear *everything*), the Cache Store remains stubbornly at around 65 MB (though sometimes if I hit the button enough times I can get it to reduce... sometimes it goes to 25 MB, sometimes 0 MB, but only after hitting F5).  I feel I'm missing some fundamental understanding of how Chrome does caching, without which I will continue to misunderstand how headless is doing it:

![capture1](https://user-images.githubusercontent.com/9009792/34015964-0af490c4-e118-11e7-9f14-3c40fb3fe068.PNG)

**Comment by ebidel** [comment]
There's `chrome://quota-internals/`. If you go over to the "Data" tab and click the "dump" button, you'll see some info. However, for me, those numbers align with the estimates you get from `navigator.storage.estimate()` :\ I just filed https://bugs.chromium.org/p/chromium/issues/detail?id=795134, which seems to be a related bug in the UI from your screenshot.

**Comment by drmrbrewer** [comment]
@ebidel this is still driving me mad.  It's not specific to puppeteer... I'm having the same (or similar) issues on normal Chrome.  I've posted a couple of comments on [your bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=795134) with a demo and steps to reproduce... but it's all so inconsistent that I'm not 100% you'll be able to reproduce it exactly... but at least I hope you can see the same types of behaviour that are leading to me "quota exceeded" errors in puppeteer.

**Comment by aslushnikov** [comment]
Looks like the discussion has moved over to [crbug.com/795134](https://bugs.chromium.org/p/chromium/issues/detail?id=795134).
