### ISSUE TITLE
Failed to download Chromium r515411

### ISSUE THREAD

**Issue by gp5251** [puppeteer/puppeteer#1597]
I came across an problem like below when i tried to run npm i puppeteer, is there any solution? 

puppeteer@0.13.0 install /Users/guipeng/Desktop/ldl/puppeteer/node_modules/puppeteer
node install.js

ERROR: Failed to download Chromium r515411! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ETIMEDOUT
    at _errnoException (util.js:1041:11)
    at TLSWrap.onread (net.js:606:25) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }
npm WARN enoent ENOENT: no such file or directory, open '/Users/guipeng/Desktop/ldl/puppeteer/package.json'

**Comment by paambaati** [comment]
@gp5251 This might just be an intermittent network issue. Does this happen consistently?

**Comment by ThinkRealize** [comment]
@paambaati I also encountered the same situation.

**Comment by vc1** [comment]
用 cnpm 安装，自动切换国内源

https://npm.taobao.org/

**Comment by gp5251** [comment]
@vc1 problem resolved, 3q.

**Comment by p0psicles** [comment]
We're using a private nexus repository. Could I interchange the googleapis.com url, with our own direct route? Are there any other request related attributes we need to take care off?

**Comment by aslushnikov** [comment]
@p0psicles there's [`PUPPETEER_DOWNLOAD_HOST`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables) that you can use to download from a mirror.

**Comment by p0psicles** [comment]
Yes I figured it out eventually. I do think it would help if this would be added to the documentation. Now you need to search through a number of issues or go through the code yourself.

**Comment by aslushnikov** [comment]
@p0psicles I'll be happy to review a PR!

**Comment by kiki882727** [comment]
I tried the above method, But it did not work
```
cnpm i puppeteer
ERROR: Failed to download Chromium r526987! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 404. URL: https://cdn.npm.taobao.org/dist/chromium-browser-snapshots/Mac/526987/chrome-mac.zip
    at response (/Users/mac/Desktop/node/learnNode/pupp/node_modules/_puppeteer@1.0.0@puppeteer/lib/Downloader.js:228:21)

cnpm config get registry
http://registry.npm.taobao.org/
```
```
npm i puppeteer
npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> puppeteer@1.0.0 install /Users/mac/Desktop/node/learnNode/pupp/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r526987! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ETIMEDOUT
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25) code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }

echo $PUPPETEER_DOWNLOAD_HOST
https://storage.googleapis.com.cnpmjs.org
```
How can I resolve it?
I tried to manually install It. But hen I run it I got the following error
```
const puppeteer = require('puppeteer');

(async () => {

    const executablePath = '/Applications/Chromium.app/Contents/MacOS/Chromium';
    const headless = true;
    const context = 'default';

    const browser = await puppeteer.launch({ executablePath, headless });
    const page = await browser.newPage({ context });
    await page.goto('https://example.com');
    await page.screenshot({path: 'example.png'});
    browser.close();

})();

(node:1980) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.getFrameTree): 'Page.getFrameTree' wasn't found undefined
(node:1980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I do not know if this error was caused by a manual installation。
Can anyone help me?

**Comment by aslushnikov** [comment]
> I tried the above method, But it did not work
> How can I resolve it?

It looks like there's a something that prevents pptr from network access. If there's a proxy, you can set it up with [env variables](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables).

> I do not know if this error was caused by a manual installation。
Can anyone help me?

@kiki882727 you're trying to run an old chromium. If you're using pptr 1.0.0, try running Chrome Canary instead.

**Comment by koutsenko** [comment]
Any progress?

**Comment by BrickCarvingArtist** [comment]
It doesn't work with any solutions on my mac.
Finally I solve with following steps:
1. `vi .npmrc`
2. type `puppeteer_download_host = https://npm.taobao.org/mirrors`
3. `yarn add puppeteer@1.0.0 -D`
After waiting for about 10mins, done!

**Comment by kiki882727** [comment]
@aslushnikov thanks for your help, I tried anther version of puppeter -- 0.13.0, It worked very well. I will upgrades it in the feature, But not now, thank you again for your help

**Comment by backspaces** [comment]
Same problem. Solved w/ 0.13.0 build.

**Comment by backspaces** [comment]
Tried it again with 1.0.0 and it *did* work. No idea why.

**Comment by crsj** [comment]
Error: Download failed: server returned code 407. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/526987/chrome-win32.zip

Downloaded the file from https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/526987/chrome-win32.zip

Made sure it is downloadale from below location from a local webserver
http://localhost:8666/chromium-browser-snapshots/Win_x64/526987/chrome-win32.zip

set this in .npmrc 
puppeteer_download_host=http://localhost:8666

Did the trick for me; a quick workaround if some one needs

**Comment by obihill** [comment]
```
sudo npm install puppeteer --unsafe-perm=true --allow-root
```

I had an issue installing puppeteer on Mac OS (10.10), and also a permissions issue with mkdir for some reason. This solved it.

**Comment by zhangtemplar** [comment]
it works @vc1

**Comment by Calvin92** [comment]
@vc1 Niubi, good job.

**Comment by racl101** [comment]
> @gp5251 This might just be an intermittent network issue. Does this happen consistently?

I think this was the case with me. I tried it a second time and it work. 

Running: node v8.11.2 and npm 5.6.0  at the time, if that matters.

**Comment by jbricenoz** [comment]
`sudo npm install puppeteer --unsafe-perm=true --allow-root`

works fine.

**Comment by i-sync** [comment]
> ```
> sudo npm install puppeteer --unsafe-perm=true --allow-root
> ```
> I had an issue installing puppeteer on Mac OS (10.10), and also a permissions issue with mkdir for some reason. This solved it.

Thanks, it's work.

**Comment by manashmandal** [comment]
> 使用国内Chromium源
> https://npm.taobao.org/mirrors
> 
> ```shell
> # // > https://npm.taobao.org/mirrors
> # // export PUPPETEER_DOWNLOAD_HOST=https://npm.taobao.org/mirrors
> # // set PUPPETEER_DOWNLOAD_HOST=https://npm.taobao.org/mirrors
> 
> npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
> npm i puppeteer
> ```
> 
> 或者用淘宝的[cnpm ](https://npm.taobao.org/)安装，自动使用国内源
> 
> ```shell
> npm install -g cnpm --registry=https://registry.npm.taobao.org
> cnpm i puppeteer
> ```
> 
> 还可以手动下载Chromium文件，解压后放在本地
> https://npm.taobao.org/mirrors/chromium-browser-snapshots/
> 
> * 放在模块的默认读取目录下
>   例如 `node_modules\puppeteer\.local-chromium\win64-526987(系统类型-版本号)\chrome-win32(下载的文件名)\`
>   版本号来自 puppeteer/package.json->puppeteer.chromium_revision，具体见[lib/Downloader.js](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Downloader.js)
> * 放在其他目录，运行时设置路径参数
>   [puppeteer.launch({executablePath:'ChromiumExePath'})](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions)
> 
> > [cnpm/cnpmjs.org#1246](https://github.com/cnpm/cnpmjs.org/issues/1246)
> > `storage.googleapis.com` 整站代理：https://storage.googleapis.com.cnpmjs.org
> > https://npm.taobao.org/mirrors
> > [cnpm/binary-mirror-config/package.json](https://github.com/cnpm/binary-mirror-config/blob/master/package.json#L43)

Thank you! Working!!

**Comment by JaapWeijland** [comment]
I had this issue as well when installing puppeteer on Cloud Functions for Firebase. This was the specific error:

```
Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nnode-pre-gyp WARN Using request for node-pre-gyp https download \nnode-pre-gyp WARN Using request for node-pre-gyp https download \nERROR: Failed to download Chromium r686378! 
Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\nError: end of central directory record signature not found\n    at /workspace/node_modules/yauzl/index.js:167:14\n    at /workspace/node_modules/yauzl/index.js:473:5\n    at /workspace/node_modules/fd-slicer/index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)\n  -- ASYNC --\n    at BrowserFetcher.<anonymous> (/workspace/node_modules/puppeteer/lib/helper.js:111:15)\n    at Object.<anonymous> (/workspace/node_modules/puppeteer/install.js:64:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppeteer@1.20.0 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! 
Failed at the puppeteer@1.20.0 install script.\nnpm ERR! 
This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-05-04T12_34_05_082Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "FFD91768"}}
```
I was using `puppeteer@^1.20.0`

I just retried it a couple of times and eventually it would install correctly. Not really a fix but it may indicate it was just trying to install it on a malfunctioning serverless instance or something.

**Comment by Trinhlvtq** [comment]
@JaapWeijland I'm getting the same error you are when installing puppeteer function Firebase Functions (
```
Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nERROR: Failed to download Chromium r722234! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\nError: end of central directory record signature not found\n    at /workspace/node_modules/yauzl/index.js:167:14\n    at /workspace/node_modules/yauzl/index.js:473:5\n    at /workspace/node_modules/fd-slicer/index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)\n  -- ASYNC --\n    at BrowserFetcher.<anonymous> (/workspace/node_modules/puppeteer/lib/helper.js:111:15)\n    at Object.<anonymous> (/workspace/node_modules/puppeteer/install.js:66:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppeteer@2.1.1 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the puppeteer@2.1.1 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-05-07T08_22_18_757Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "3F4C9440"}}
```

Sometime it's a other error
```
Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nERROR: Failed to download Chromium r722234! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\n{ Error: read ECONNRESET\n    at TLSWrap.onread (net.js:622:25)\n  -- ASYNC --\n    at BrowserFetcher.<anonymous> (/workspace/node_modules/puppeteer/lib/helper.js:111:15)\n    at Object.<anonymous> (/workspace/node_modules/puppeteer/install.js:66:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3 errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppeteer@2.1.1 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the puppeteer@2.1.1 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-05-07T08_22_17_043Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "198B66D6"}}
```

I was using  `"puppeteer": "^2.1.1"`
I just deploy one more time and it's deploy success. I dont know exact reason of error :(

**Comment by ruanye** [comment]
pm ERR! ERROR: Failed to set up Chrome r115.0.5790.170! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirrors/115.0.5790.170/mac-x64/chrome-mac-x64.zip
npm ERR!     at /Users/mac/Desktop/aa/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:102:31   这个怎么解决

**Comment by ruanye** [comment]
pm ERR! ERROR: Failed to set up Chrome r115.0.5790.170! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirrors/115.0.5790.170/mac-x64/chrome-mac-x64.zip
npm ERR!     at /Users/mac/Desktop/aa/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:102:31
