### ISSUE TITLE
Error while loading libatk-bridge-2.0.so.0

### ISSUE THREAD

**Issue by tleunen** [puppeteer/puppeteer#1598]
When running Puppeteer with Karma, I'm getting the following error on a CI. I don't have any issue locally on my Mac OS machine.

> /../node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
ERROR [launcher]: [39mChromeHeadless stdout: 
ERROR [launcher]: [39mChromeHeadless stderr: /../node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Linux

**What steps will reproduce the problem?**

I configured Karma with puppeteer as explained here https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer
But it doesn't work on the CI I'm using because libatk-bridge-2.0.so.0 cannot be found.

Any idea how to fix this?

**Comment by ebidel** [comment]
Have you seen https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch? It talks about missing Chrome deps.

**Comment by tleunen** [comment]
Thanks. It helped :)

**Comment by QingkaiLi** [comment]
@tleunen  i encountered the same issue on centOS, how did you fix your issue?

**Comment by tleunen** [comment]
@QingkaiLi I installed the missing dependencies as explained in the troubleshooting page

**Comment by qbss1221** [comment]
i encountered tje same issue on centOS6, how to install the missing dependencies

**Comment by shelagh-lewins-ucl** [comment]
The troubleshooting page wasn't much help because the dependencies are not all to be found under those names. The only way I could find and install the missing packages was to search for them and find their actual names:

`apt-cache search libatk-bridge`
This gave a list from which I could choose a version that existed:
`sudo apt-get install libatk-bridge2.0-0`

This process seems unnecessarily painful.

**Comment by impactcolor** [comment]
This package which it's asking for is not on the list of dependencies on the trouble shooting page:
libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by jcward** [comment]
FYI, I got the same error from Chrome headless in an ubuntu-based docker image. I needed to install:

```
sudo apt-get install -y libatk-bridge2.0-0 libgtk-3.0
```

And launch puppeteer with:

```
const browser = await puppeteer.launch({args: ['--disable-setuid-sandbox', '--no-sandbox']});
```

**Comment by Daryhez** [comment]
sudo pacman -S lib32-gtk2
Work for me!

**Comment by rinogo** [comment]
On a barebones install of CentOS 7 (on Amazon AWS EC2), I was able to get chrome headless running with the following:
`sudo yum install atk java-atk-wrapper at-spi2-atk gtk3 libXt`

**Comment by sameerbk** [comment]
> On a barebones install of CentOS 7 (on Amazon AWS EC2), I was able to get chrome headless running with the following:
> `sudo yum install atk java-atk-wrapper at-spi2-atk gtk3 libXt`

For our Azure CentOS 7 VM, we needed to install two more libraries
`libdrm mesa-libgbm`

command used:
`sudo yum install atk java-atk-wrapper at-spi2-atk gtk3 libXt libdrm mesa-libgbm`

**Comment by minimul** [comment]
For Ubuntu 20.04 the Debian dependency list on the [troubleshooting guide](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) is up-to-date.

**Comment by johnpc** [comment]
had to run `sudo apt-get install -y libatk-bridge2.0-0 libgtk-3.0 libasound2`

**Comment by TheToto** [comment]
On ArchLinux, you need `at-spi2-atk` package. `sudo pacman -S at-spi2-atk`

**Comment by ShivSoni5** [comment]
> On a barebones install of CentOS 7 (on Amazon AWS EC2), I was able to get chrome headless running with the following: `sudo yum install atk java-atk-wrapper at-spi2-atk gtk3 libXt`

Along with this you have to launch puppeteer with args like this:
`const browser = await puppeteer.launch({args: ['--disable-setuid-sandbox', '--no-sandbox']});`

**Comment by shtse8** [comment]
for ubuntu 22
```
sudo apt-get install -y libatk-bridge2.0-0 libgtk-3.0 libasound2 libgbm-dev
```

**Comment by danieljbk** [comment]
> On a barebones install of CentOS 7 (on Amazon AWS EC2), I was able to get chrome headless running with the following: `sudo yum install atk java-atk-wrapper at-spi2-atk gtk3 libXt`

my savior

**Comment by hellopik** [comment]
> On a barebones install of CentOS 7 (on Amazon AWS EC2), I was able to get chrome headless running with the following: `sudo yum install atk java-atk-wrapper at-spi2-atk gtk3 libXt`

Thank you good sir !

**Comment by Deni-H** [comment]
Is anyone have solution if you can't do sudo command?

**Comment by jabeztadesse** [comment]
> > Is anyone have solution if you can't don't have sudo command?
> 
> I am also looking for such a solution. Where you able to solve it? My application is running on a shared hosting platform, and they advised I should install it using `npm -i` but it does not make sense since the missing package is a system-level package.

Same here +1

**Comment by hasan-aftab** [comment]
> > Is anyone have solution if you can't don't have sudo command?
> 
> I am also looking for such a solution. Where you able to solve it? My application is running on a shared hosting platform, and they advised I should install it using `npm -i` but it does not make sense since the missing package is a system-level package.

Any success ?

**Comment by Deni-H** [comment]
> > Is anyone have solution if you can't don't have sudo command?
> 
> I am also looking for such a solution. Where you able to solve it? My application is running on a shared hosting platform, and they advised I should install it using `npm -i` but it does not make sense since the missing package is a system-level package.

I haven't worked on the project for a while. As far as I remember, I ended up renting a VPS where I can use sudo commands

**Comment by ayoub-khemissi** [comment]
This is what worked for me on Amazon Linux 2023:

general update:
sudo dnf update -y

missing libs for puppeteer:
sudo dnf install -y \
    atk \
    cups-libs \
    libdrm \
    at-spi2-core \
    libX11 \
    libXcomposite \
    libXdamage \
    libXext \
    libXfixes \
    libXrandr \
    mesa-libgbm \
    libxcb \
    libxkbcommon \
    pango \
    cairo \
    alsa-lib

The last missing lib:
sudo yum install -y at-spi2-atk

The error I had (node.js app):

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Tracker.findProduct (...)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 0)
    at async Tracker.processQueue (...)
    at async Tracker.startTrackChecking (...)
[2024-12-25 13:26:01.781][ERROR] ...
/home/ec2-user/.cache/puppeteer/chrome/linux-127.0.6533.88/chrome-linux64/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
