### ISSUE TITLE
 Request content was evicted from inspector cache ??

### ISSUE THREAD

**Issue by howesteve** [puppeteer/puppeteer#1599]
Hello,

I'm using Puppeteer to do an offline mirror of a site. Problem is, I can't save large files. The following code is a simplified version of the mirroring bot, and it fails on the .flv (larger) file. My actual target site contains similar flash players and flv files.

```javascript
const puppeteer = require('puppeteer');
const url = require('url');
const fs = require('fs');
const path = require('path');
const fse = require('fs-extra');

(async () => {
  const savePath = './site';
  const browser = await puppeteer.launch({
    args: [
      '--no-sandbox',
      '--ppapi-flash-version=28.0.0.126',
      '--ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so',
      '--user-data-dir=/home/howe/.config/chromium'
    ],
    headless: false,
  });
  const page = await browser.newPage();
  page.on('response', async (res) => {
    const parsed = url.parse(res.url);
    try {
      const fn = path.join(savePath, parsed.pathname);
      console.log(`Saving file ${fn}...`);
      await fse.ensureDir(path.dirname(fn));
      await fse.writeFile(fn, await res.buffer());
    }
    catch (e) {
      console.error('Error:', e)
    }
  });
  await page.goto('http://flash.flowplayer.org/demos/plugins/flash/viralvideos-extconfig.html', { waitUntil: 'networkidle2' });
  // browser.close();
})();
```
After downloading a few smaller files, it throws the following cryptic error:
```
Protocol error (Network.getResponseBody): Request content was evicted from inspector cache undefined
```
Any clues? Is this a bug? I have no idea why it works on smaller but not larger files.

Thanks,
Howe

**Comment by aslushnikov** [comment]
There's a limitation on the resource content size that devtools keep in memory. It's 10Mb for resource, and there's also a total of 100Mb limit to store all resources: [InspectorNetworkAgent.cpp](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/InspectorNetworkAgent.cpp?type=cs&sq=package:chromium&l=104-107)

There's experimental support in the protocol to amend these limits: [Network.enable](https://aslushnikov.github.io/vanilla-protocol-viewer/#Network.enable).

**Comment by howesteve** [comment]
Thanks for answering. Is there a way I can bypass that limit now on the current version?

**Comment by howesteve** [comment]
Ok, It seems this works (but I didn't test thoroughly):
```javascript
await page._client.send('Network.enable', {
      maxResourceBufferSize: 1024 * 1204 * 100,
      maxTotalBufferSize: 1024 * 1204 * 200,
    })
```
Hope that helps someone else.
Thanks @aslushnikov .

**Comment by gzlock** [comment]
@howesteve 
I use ubuntu desktop + chrome-stable v64, and use config
```
args: [
                '--no-sandbox',
                '--mute-audio',
                '--disable-gpu',
                '--disable-setuid-sandbox',
                '--ignore-certificate-errors',
                '--ignore-ssl-errors',
                '--ignore-certificate-errors-spki-list',
                '--ppapi-flash-version=28.0.0.161',
                '--ppapi-flash-path=/root/.config/google-chrome/PepperFlash/28.0.0.161/libpepflashplayer.so',
                '--user-data-dir=/tmp'
            ]
```
But can not display flash.
![1517654883505](https://user-images.githubusercontent.com/2311740/35766444-c6ba8f2a-0913-11e8-80a6-187d129f6423.png)
I think the problem is about the latest chrome version need enable flash plugin by manual?

**Comment by howesteve** [comment]
I believe flash will not work under headless mode. Try passing "headless: false" into your launch arguments.

Howe

**Comment by brentjanderson** [comment]
For future reference - the maximum limit appears to be the max byte value of a signed 32-bit integer: `2 ** 31 - 1` or `2147483647`.

**Comment by ghost** [comment]
Does anyone know the syntax to send this command with the new chrome devtools's experimental feature "protocol monitor" ?
I tried many ways...
![Screenshot 2021-12-01 at 17 09 58](https://user-images.githubusercontent.com/89975995/144275785-14742458-fa4e-453a-84f3-37136e2d6206.png)

Sorry, i know this is not a puppeteer issue 😓

**Comment by sapabg** [comment]
For me the problem was that return this.http.post<any>(this.url + '/file/uploaded', { **file** }) automatically changes the type of the request to image/file NOT json and because I recieve json from the backend it get evicted!
Added a 'string' type to the payload and it works now! Took me a while...damn
