### ISSUE TITLE
Tests don't work under Node 9

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1600]
Didn't spend time diving into puppeteer's customize test runner.

<img width="1265" alt="screen shot 2017-12-14 at 11 06 02 am" src="https://user-images.githubusercontent.com/238208/34009726-dcc567e0-e0be-11e7-8125-677eabac4fa2.png">

**Comment by aslushnikov** [comment]
This is a node.js crash, so it's a node9 bug at the very least.

`PNG.sync.read(actualBuffer);` causes the crash; i didn't look further into this.
https://github.com/GoogleChrome/puppeteer/blob/cb1cb695a5ec71e9d74b61f8a01777fa731acff6/test/golden-utils.js#L35-L49

**Comment by aslushnikov** [comment]
This is a pngjs issue: https://github.com/lukeapage/pngjs/issues/95

If it's not fixed soon we should probably migrate to a different solution to compare images for our tests.
