### ISSUE TITLE
Error message could have more context

### ISSUE THREAD

**Issue by sul4bh** [puppeteer/puppeteer#1604]
Is there a way to make error message more detailed than just 'Node is not visible'? Probably name of the selector?

Also, the stacktrace does not show the line number in my test code that caused the error.

```
    Node is not visible
      
      at ElementHandle._visibleCenter (node_modules/puppeteer/lib/ElementHandle.js:63:13)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Env**
node: 9.3.0
jest test runner: 21.2.1

**Comment by sul4bh** [comment]
Another example:
```
waiting failed: timeout 30000ms exceeded
      
      at WaitTask._timeoutTimer.setTimeout (node_modules/puppeteer/lib/FrameManager.js:668:58)
      at Timeout.callback (node_modules/jsdom/lib/jsdom/browser/Window.js:592:19)
```
Timeout while trying to do what? Why do I care about the `FrameManager`

Definitely not inspiring confidence here. How am I supposed to know what is wrong with the code without a useful stacktrace?

**Comment by sul4bh** [comment]
Example where error detail is to the point:
```
● should allow user to upload a video

    TypeError: page.$(...).uploadFile is not a function

      48 | 	await page.click('div.asset-photo');
      49 | 	await page.waitForSelector('input[type="file"].dz-hidden-input');
    > 50 | 	await page.$('input[type="file"].dz-hidden-input').uploadFile(videoFilePath);
      51 | 	return page.waitForSelector('asset-video-repeat');
      52 | }
      53 | 
```

**Comment by aslushnikov** [comment]
@sul4bh as of today, asynchronous execution has poor stacktraces and this is a node.js limitation. Hopefully it will be addressed some time in future by the platform itself.

Meanwhile, if you connect devtools to node, you'll get beautiful async stracktraces that will tell the whole story of code execution.

**Comment by andre-hh** [comment]
See https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27 for example.
