### ISSUE TITLE
Cannot access localStorage. Access is denied for this document.

### ISSUE THREAD

**Issue by yrshaikh** [puppeteer/puppeteer#1607]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^0.13.0
* Platform / OS version: Windows 10

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

`await(page.evaluate(() => {
        localStorage.clear();
        debug('localstorage cleared');
    }));`

**What is the expected result?**
Localstorage should be cleared.

**What happens instead?**
exception::Error: Evaluation failed: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

**Comment by vsemozhetbyt** [comment]
Can you provide the URL of the document?

**Comment by yrshaikh** [comment]
I was trying for https://en.wikipedia.org/wiki/Main_Page

**Comment by vsemozhetbyt** [comment]
Thank you. FWIW, I cannot reproduce the error on Windows 7 x64 with puppeteer v1.0.0-rc (Chromium r522446) and this code:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('https://en.wikipedia.org/wiki/Main_Page');

    await page.evaluate(() => { localStorage.clear(); });

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by ebidel** [comment]
@yrshaikh is it possible you're running into https://github.com/GoogleChrome/puppeteer/issues/1268? Can you give us your full puppeteer script that repros the issue?

**Comment by justindujardin** [comment]
@vsemozhetbyt your test case is __so__ close. The trick is to do the `page.evaluate` before the `page.goto`. Imagine you're setting custom values in localStorage before the page loads (because your app does something with it on page load)

```javascript
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
    try {
        const browser = await puppeteer.launch();
        const page = await browser.newPage();

        await page.evaluate(() => { localStorage.clear(); });

        await page.goto('https://en.wikipedia.org/wiki/Main_Page');

        await browser.close();
    } catch (err) {
        console.error(err);
    }
})();
```

FWIW: It reproduces for me on macOS Sierra (10.12.6):
```bash
$ node pup.js 
Error: Evaluation failed: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at <anonymous>:1:10
    at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:81:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by vsemozhetbyt** [comment]
@justindujardin `localStorage` is bound to the page [origin](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/origin). If you require `localStorage` before `page.goto()`, you try to get `localStorage` for `about:blank` URL, and this is forbidden. You can check this in the browser console:

![ab](https://user-images.githubusercontent.com/10393198/38761983-02f2b4f6-3f90-11e8-82a7-4c2333143c77.png)

**Comment by justindujardin** [comment]
@vsemozhetbyt Yeah, I'm not having a problem, just had information you guys were asking for. 👍

**Comment by vsemozhetbyt** [comment]
Yes, thank you, your example makes a possible cause of the issue clear.

**Comment by scottc-netflix** [comment]
@ebidel 
I think there needs to be a way to have the localStorage set when the page loads, this doesn't seem possible currently, is that correct? Setting it immediately after `page.goto` is not fast enough for my use case.

**Comment by javirln** [comment]
Any update on this ? :/

**Comment by LukaszGrela** [comment]
@scottc-netflix I had to do 2 calls to `page.goto` to be able to use it in my page, first so the url is set for the localStorage and second to load the page with localStorage data
```
      // open the url
      await page.goto('http://localhost:3000/Admin', { waitUntil: 'load' });
      // store in localstorage the token
      await page.evaluate(
        token => {
          localStorage.clear();
          localStorage.setItem('token', token);
        }, 'eyJh...9_8cw');
      // load the page again so it takes stored data
      await page.goto('http://localhost:3000/Admin', { waitUntil: 'load' });
```

It would be useful to have means to set all similar data on the browser before loading the page (or as a setup to the current;y loaded page?

```
// e.g.
await page.goto('some/url', {waitUntil: 'load', localStorage:{token:'abc'}});
```

**Comment by ebidel** [comment]
Does `evaluateOnNewDocument` work for this use case? The code you pass it will get injected into the page before other scripts run.

https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-pageevaluateonnewdocumentpagefunction-args

**Comment by LukaszGrela** [comment]
Hi @ebidel it seems to work:) like this
```
       // store in localstorage the token
      await page.evaluateOnNewDocument (
        token => {
          localStorage.clear();
          localStorage.setItem('token', token);
        }, 'eyJh...9_8cw');
      // open the url
      await page.goto('http://localhost:3000/Admin', { waitUntil: 'load' });
```

**Comment by IgorKurkov** [comment]
it does not work as should. just not setup any value to localStorage and produce no errors.
perhaps due to an issue in chromium with third-party blocking localStorage can be blocked by checkbox inside settings of chromium... and I can't uncheck it programmatically.
so I chose cookies to set the token.
this works for me:
```
  const token = {
    name: 'jwt-token',
    value: jwtToken, // <= hwew your token variable
    domain: 'localhost',
    path: '/',
    expires: 2147483647, // 2038 year
    size: 16,
    httpOnly: false,
    secure: true,
    session: false,
    sameSite: 'Lax',
  };
  await page.setCookie(token);
```
it works:)

**Comment by BranceLee** [comment]
Sometimes the pages index will be changed, so get localStorge or the sessionStorage could get the error for: ### Cannot access sessionStorage. Access is denied for this document.

I encountered the same related problem, finally I found the reason. Every time when you launch the browser, I create a new page instead of using the default page that created by the browser. Please try the snippets blow:

``` js
beforeAll(async () => {
    browser = await puppeteer.launch()
    // page = await browser.newPage()
    const pages = await browser.pages();
    const page = pages[0];
});
```

**Comment by maxime1992** [comment]
In case anyone else needs this, `evaluateOnNewDocument` isn't available anymore apparently but I was able to achieve the same with https://playwright.dev/docs/api/class-page#page-add-init-script

**Comment by indexeddb63** [comment]
> Hi [@ebidel](https://github.com/ebidel) it seems to work:) like this
> 
> ```
>        // store in localstorage the token
>       await page.evaluateOnNewDocument (
>         token => {
>           localStorage.clear();
>           localStorage.setItem('token', token);
>         }, 'eyJh...9_8cw');
>       // open the url
>       await page.goto('http://localhost:3000/Admin', { waitUntil: 'load' });
> ```





https://angularjs-ng-formnonpoli.github.io/typescript2876/
