### ISSUE TITLE
Access devtools protocol inside puppeteer

### ISSUE THREAD

**Issue by rogemus** [puppeteer/puppeteer#1616]
Hi,
I'm trying to get all styles for element on page and for that i want to use [devtools-protocol](https://chromedevtools.github.io/devtools-protocol/tot/CSS/#method-getMatchedStylesForNode), but i cannot find any way to access this function and many other. I would be very grateful for help :)

Windows 10
Chrome: 63.0.3239.84 (64b)
puppeteer: 0.13.0
node: 8.9.3

**Comment by Everettss** [comment]
Here is an explanation for your problem #31 .

**Comment by rogemus** [comment]
@Everettss thank you this is exactly what i've been looking for 😄  ❤️
