### ISSUE TITLE
Docker installation instructions miss required library (libgconf-2.so.4)

### ISSUE THREAD

**Issue by itsachen** [puppeteer/puppeteer#1627]
**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Docker, using [these configurations](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)

### Issue

We recently (12/7/17) began using puppeteer in our application that is run using Docker. We configured our `Dockerfile` according to [these instructions](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) to install the necessary shared library dependencies.

Our application was running smoothly with no issues until several days ago, when we began noticing these errors consistently whenever we attempted to run puppeteer:
```
Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

Investigating the recommended dependency installation instructions a bit more revealed that the suggested command was installing a version of `google-chrome-unstable` (65.0.3294.5-1) whose dependencies did not include `libgconf-2-4`. See the bottom of the issue for a list of dependencies that were installed instead.

Perhaps the version of Chrome required by puppeteer and the most recent version of `google-chrome-unstable` are misaligned? Our temporary fix is to install `google-chrome-beta`, which is currently versioned at 64.0.3282.24-1.

What would be the recommended long-term fix for users running puppeteer on Docker?

The following dependencies were installed for `google-chrome-unstable` 65.0.3294.5-1:
```
adwaita-icon-theme dconf-gsettings-backend dconf-service fontconfig
fontconfig-config fonts-liberation glib-networking glib-networking-common
glib-networking-services gsettings-desktop-schemas hicolor-icon-theme
libappindicator1 libasound2 libasound2-data libatk-bridge2.0-0 libatk1.0-0
libatk1.0-data libatspi2.0-0 libavahi-client3 libavahi-common-data
libavahi-common3 libcairo-gobject2 libcairo2 libcolord2 libcroco3 libcups2
libdatrie1 libdbus-1-3 libdbusmenu-glib4 libdbusmenu-gtk4 libdconf1
libexpat1 libfontconfig1 libfreetype6 libgdk-pixbuf2.0-0
libgdk-pixbuf2.0-common libglib2.0-0 libgraphite2-3 libgtk-3-0 libgtk-3-bin
libgtk-3-common libgtk2.0-0 libgtk2.0-common libharfbuzz0b libindicator7
libjasper1 libjbig0 libjpeg62-turbo libjson-glib-1.0-0
libjson-glib-1.0-common liblcms2-2 libnspr4 libnss3 libpango-1.0-0
libpangocairo-1.0-0 libpangoft2-1.0-0 libpixman-1-0 libpng12-0 libproxy1
libpython-stdlib libpython2.7-minimal libpython2.7-stdlib librest-0.7-0
librsvg2-2 librsvg2-common libsoup-gnome2.4-1 libsoup2.4-1 libsqlite3-0
libthai-data libthai0 libtiff5 libwayland-client0 libwayland-cursor0
libx11-6 libx11-data libx11-xcb1 libxau6 libxcb-render0 libxcb-shm0 libxcb1
libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6
libxinerama1 libxkbcommon0 libxml2 libxrandr2 libxrender1 libxss1 libxtst6
lsb-release mime-support python python-minimal python2.7 python2.7-minimal
shared-mime-info ucf x11-common xdg-utils xkb-data
```

**Comment by ebidel** [comment]
It looks like the chrome package was [updated recently](https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-unstable) and is missing that shared lib now. No idea why.

Add this to the top of the file, before installing chrome:

```
RUN apt-get update && apt-get install -yq libgconf-2-4
```

That fixes it for me.

**Comment by ebidel** [comment]
Ah: https://bugs.chromium.org/p/chromium/issues/detail?id=795759

To not confuse folks, we can add that line to the example file until Chrome fixes this. But it shouldn't be needed :)
