### ISSUE TITLE
ignoreHTTPSErrors should use Security.setIgnoreCertificateErrors from M65 onwards.

### ISSUE THREAD

**Issue by betasheet** [puppeteer/puppeteer#1634]
From M65, Security.setOverrideCertificateErrors is deprecated and replaced by Security.setIgnoreCertificateErrors: https://chromium-review.googlesource.com/c/chromium/src/+/817443

**Comment by aslushnikov** [comment]
Thanks! The `Security.setOverrideCertificateErrors` is deprecated but stable; we'll wait for the `Security.setIgnoreCertificateErrors` to reach stable state before adopting it.
