### ISSUE TITLE
Chromium resolving wrong DNS

### ISSUE THREAD

**Issue by lbeier** [puppeteer/puppeteer#1635]
When running my E2E tests, for some reason Chromium receives a 301 from two endpoints my application is using. I wasn't able to reproduce on Safari, Chrome or Firefox. I'm not sure if this is an issue related with the DNS since I wasn't able to reproduce the error in the other browsers.

When opening the application directly with `open node_modules/puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app`, it also works as expected, but when the application is open via Puppeteer, a 301 is received from some endpoints.

**Tell us about your environment:**
* Puppeteer version: 0.13.0
* Platform / OS version: MacOS
* URLs (if applicable):

**What is the expected result?**
Fetch data from `https://my.private.host/index.js`.

**What happens instead?**
Receives a 301 from `https://my.private.host/index.js` and then tries to fetch data from other host (which I don't recognize).

**Comment by aslushnikov** [comment]
@tutabeier could you please share a script that exhibits the issue so that I can reproduce the behavior? Also, could you please try installing puppeteer@next and see if the issue is reproducible there as well?

```
npm i --save puppeteer@next
```

(puppeteer@next is a tip-of-tree version of puppeteer continiously published on npm)
