### ISSUE TITLE
Clicking and waiting for navigation is flaky in 0.13

### ISSUE THREAD

**Issue by kdzwinel** [puppeteer/puppeteer#1637]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: macOS / 10.13.2
* Node: 8.9.0

**What steps will reproduce the problem?**

We replaced casperjs tests with jest+puppeteer and in multiple tests we use click+waitForNavigation combo. This worked fine in 0.12, but it seems to be broken in 0.13.

Minimal example:

```javascript
const puppeteer = require('puppeteer');

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  page.on('load', () => console.log('loaded!'));

  await page.goto('https://mdn.github.io/learning-area/html/forms/your-first-HTML-form/first-form-styled.html');
  await page.waitForSelector('form[action^="/my-handling-form-page"]');
  await page.type('input[name="user_mail"]', 'mati@mati.com');
  await page.type('input[name="user_name"]', 'mati');

  await page.click('button[type="submit"]');
  console.log('clicked');

  await page.waitForNavigation();

  console.log('done');
}

main();
```

**What is the expected result?**
Console should say (as it does every time in 0.12):

```
loaded!
clicked
loaded!
done
```

**What happens instead?**
Most of the time (not always!) console says:

```
loaded!
loaded!
clicked
(node:31100) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded:30000ms exceeded
```

----

Seems to be reproducible in try-puppeteer (although happens less often than on my machine)
<img width="1178" alt="screen shot 2017-12-20 at 23 44 55" src="https://user-images.githubusercontent.com/985504/34232269-d49d1c86-e5df-11e7-9708-c50b6b1dd2f6.png">

**Comment by ebidel** [comment]
This does appear to be a race. I'll note that adding `await page.waitFor(300);` right before the submit button click seems to always do the trick...although that shouldn't be needed.

When the script does error out, the context has been lost for some reason:
 
`env DEBUG="puppeteer:error,-puppeteer:protocol" node script.js`

<img width="1205" alt="screen shot 2017-12-20 at 3 57 25 pm" src="https://user-images.githubusercontent.com/238208/34234390-ae8bef94-e59f-11e7-936c-9c9dd6ad013f.png">

**Comment by jessica-norris** [comment]
I have a related / similar problem. When I do a page click, I'd like to be able to wait for any navigation that subsequently occurs. The page click does not usually trigger a navigation. If I handle the `framenavigated` Page event and subsequently do `waitForNavigation()`, the navigation appears to never complete, despite the frame lifecycle information being updated normally.

```
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.frameNavigated","params":{"frame":{"id":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","url":"file:///tmp/test_puppeteer/normalize.css","securityOrigin":"file://","mimeType":"text/css"}}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:page page.emit("framenavigated", Frame{"_url":"\"file:///tmp/test_puppeteer/normalize.css\"","_id":"\"(887CCF281A0B0D22AF1FF6C62ED9C981)\"","_loaderId":"\"42.4\""})
Fri, 22 Dec 2017 03:51:00 GMT html_puppeteer_marker Navigation is commited to file:///tmp/test_puppeteer/normalize.css with lifecycle Set { 'init' }
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":3,"origin":"file://","name":"","auxData":{"isDefault":true,"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)"}}}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Network.loadingFinished","params":{"requestId":"42.4","timestamp":95964.255444,"encodedDataLength":7973}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:page page.waitForNavigation({"timeout":"3000","waitUntil":"\"networkidle0\""})
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:page page.mainFrame()
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.loadEventFired","params":{"timestamp":95964.259524}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"load","timestamp":95964.259524}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.frameStoppedLoading","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)"}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.domContentEventFired","params":{"timestamp":95964.26787}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"DOMContentLoaded","timestamp":95964.26787}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"firstPaint","timestamp":95964.275532}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"firstContentfulPaint","timestamp":95964.275548}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"firstTextPaint","timestamp":95964.275549}}
Fri, 22 Dec 2017 03:51:00 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"firstMeaningfulPaintCandidate","timestamp":95964.275549}}
Fri, 22 Dec 2017 03:51:01 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"networkAlmostIdle","timestamp":95964.267908}}
Fri, 22 Dec 2017 03:51:01 GMT puppeteer:session ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(887CCF281A0B0D22AF1FF6C62ED9C981)","loaderId":"42.4","name":"networkIdle","timestamp":95964.267908}}
Fri, 22 Dec 2017 03:51:03 GMT puppeteer:page page.mainFrame()
Fri, 22 Dec 2017 03:51:03 GMT puppeteer:page page.mainFrame()
Fri, 22 Dec 2017 03:51:03 GMT html_puppeteer_marker Too long to load url file:///tmp/test_puppeteer/normalize.css. Frame children? [] Frame lifecycle? Set {
  'init',
  'load',
  'DOMContentLoaded',
  'firstPaint',
  'firstContentfulPaint',
  'firstTextPaint',
  'firstMeaningfulPaintCandidate',
  'networkAlmostIdle',
  'networkIdle' }
```

I think this is because the frame's `loaderId` has already been adjusted by the FrameManager handling the 'init' lifecycle event. As a result, the NavigatorWatcher is initialised with an `initialLoaderId` that matches the subsequent lifecycle events, and it rejects them all.

In my use-case I don't want to do 
```
Promise.all([
  waitForNavigation(),
  page.click(),    // or some other interaction that *might* cause a navigation
])
```
because if a navigation does not occur (the typical case) then I will be forced to time out.

**Comment by xprudhomme** [comment]
The best workaround I've found so far in similar cases is to replace the use of a waitForNavigation() step by a waitForSelector() one. 

Since we don't really know what's the best 'waitUntil' option to use, and since it's more likely that we want to wait for a specific element to exist/appear in the DOM, I found it is easier to use a waitForSelector step condition.

It requires us to know what HTML element to expect following the previous action, but it's not related to any navigation event, which is a good thing in many cases : )

**Comment by yujiosaka** [comment]
@kdzwinel 

The timeout seems to be occurred when `init` of `Page.lifecycleEvent` is called before `await page.waitForNavigation()` .
I can see the difference when I set a console log in `frame._onLifecycleEvent` as follows:

```js
  _onLifecycleEvent(loaderId, name) {
    console.log('_onLifecycleEvent', name); // Inserted here
    if (name === 'init') {
      this._loaderId = loaderId;
      this._lifecycleEvents.clear();
    }
    this._lifecycleEvents.add(name);
  }
```

**When fail**
```
_onLifecycleEvent commit
_onLifecycleEvent DOMContentLoaded
_onLifecycleEvent load
_onLifecycleEvent networkAlmostIdle
_onLifecycleEvent networkIdle
_onLifecycleEvent init
_onLifecycleEvent DOMContentLoaded
loaded!
_onLifecycleEvent load
_onLifecycleEvent firstPaint
_onLifecycleEvent firstContentfulPaint
_onLifecycleEvent firstTextPaint
_onLifecycleEvent firstMeaningfulPaintCandidate
_onLifecycleEvent init
_onLifecycleEvent init
clicked
loaded!
```

**When success**
```
_onLifecycleEvent commit
_onLifecycleEvent DOMContentLoaded
_onLifecycleEvent load
_onLifecycleEvent networkAlmostIdle
_onLifecycleEvent networkIdle
_onLifecycleEvent init
_onLifecycleEvent DOMContentLoaded
loaded!
_onLifecycleEvent load
_onLifecycleEvent firstPaint
_onLifecycleEvent firstContentfulPaint
_onLifecycleEvent firstTextPaint
_onLifecycleEvent firstMeaningfulPaintCandidate
_onLifecycleEvent init
clicked
_onLifecycleEvent init
loaded!
_onLifecycleEvent load
done
```

The reason why it keeps waiting for navigation is that `page.waitForNavigation()` has been changed dramatically from 0.12.0 to v0.13.0.
In 0.13.0, `navigationWatcher._lifecycleCompleteCallback()` needs to be resolved after calling `page.waitForNavigation()`.
However, since `init` of `Page.lifecycleEvent` is called already, it sticks here:

```js
  _checkLifecycleComplete() {
    // We expect navigation to commit.
    if (this._frame._loaderId === this._initialLoaderId) // It sticks here
      return;
    if (!checkLifecycle(this._frame, this._expectedLifecycle))
      return;
    this._lifecycleCompleteCallback();
```

It sticks because `frame._loaderId` and `navigationWatcher._initialLoaderId` are the same values.

**Comment by yujiosaka** [comment]
I was trying to solve this issue, but I started thinking this way:

1. We don't have to fix this behavior because click and navigation are in a race any way.
2. We should improve docs about using `page.waitForNavigation()` .

> We should improve docs about using `page.waitForNavigation()` .

Isn't it similar to this case?

```js
const puppeteer = require('puppeteer');

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://mdn.github.io/learning-area/html/forms/your-first-HTML-form/first-form-styled.html');
  await page.waitForNavigation(); // It sticks here
  console.log('done');
}

main();
```

We know it doesn't work because the navigation ended already when `page.waitForNavigation()` is called, but it's rather confusing.
It starts working when I modify the code like this:

```js
const puppeteer = require('puppeteer');

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await Promise.all([
    page.goto('https://mdn.github.io/learning-area/html/forms/your-first-HTML-form/first-form-styled.html'),
    page.waitForNavigation()
  ])
  console.log('done');
}

main();
```

This change can be applied to this form submit case like this:
```js
const puppeteer = require('puppeteer');

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('https://mdn.github.io/learning-area/html/forms/your-first-HTML-form/first-form-styled.html');
  await page.waitForSelector('form[action^="/my-handling-form-page"]');
  await page.type('input[name="user_mail"]', 'mati@mati.com');
  await page.type('input[name="user_name"]', 'mati');

  await Promise.all([
    page.click('button[type="submit"]'),
    page.waitForNavigation()
  ])
  console.log('done');
}

main();
```

Thus, my opinion is to write a doc to recommend users not to wait for `page.click()` before `page.waitForNavigation()`.

What do you guys think?

**Comment by yujiosaka** [comment]
**Note**

It starts here https://github.com/GoogleChrome/puppeteer/pull/1355

**Comment by aslushnikov** [comment]
@kdzwinel the `waitForNavigation` is in fact a `waitForNextNavigation`. Puppeteer lives out-of-process to chrome, so the "next navigation" is a racy concept.

If you're sure that page is not navigating somewhere and that click spawns a navigation,
I'd use the following pattern to click-and-wait-for-navigation:

```js
await Promise.all([
  page.click('button[type="submit"]'),
  page.waitForNavigation(),
]);
```

Generally, as @xprudhomme mentioned, the `waitForSelector` gives much better guarantees about page state then `waitForNavigation`.

**Comment by kdzwinel** [comment]
Thank you all for taking a look at this. I'll try to drop those `waitForNavigation`s and see how tests work only on `waitForSelector`s.

**Comment by mathurs** [comment]
We need a generic way to check the page url after a click event where the click may or may not navigate. Having to know beforehand is a bummer and in this case waitForSelector can't be used.

Is there anyway we can know if there are active network request or to check the readyState of the document. That would really help.

**Comment by nhhockeyplayer** [comment]
this remains an issue

cannot get past pages that require submit/click to render a table

and its been like this since 2017

this is terrible
cannot click on selectors
cannot wait for selectors
everythign just HANGS

**Comment by nhhockeyplayer** [comment]
i caught something

waiting for selector "table#ContentPlaceHolderDefault_mainContentResults" failed: timeout 30000ms exceeded
