### ISSUE TITLE
setContent doesn't work since 0.13.0

### ISSUE THREAD

**Issue by GautierT** [puppeteer/puppeteer#1638]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0 - latest
* Platform / OS version: OSX - 10.11.6 (15G1217)
* URLs (if applicable):

**What steps will reproduce the problem?**

```
  try {
    const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']})
    if (!browser) {
      throw new Error('No browser found...')
    }

    const page = await browser.newPage()

    if (!page) {
      throw new Error('No page found...')
    }

    await page.setContent('<html>hello world</html>')

    await page.waitForNavigation({waitUntil: 'networkidle0'})

    const pdf_buffer = await page.pdf(options)

    await page.close()

    return pdf_buffer
  }
  catch (ex) {
    debug('ex in generate_pdf_from_html : ', ex)
    throw ex
  }
```

_Please include code that reproduces the issue._

1. Execute the code above
2.
3.

**What is the expected result?**

A buffer is returned

**What happens instead?**

The browser seems to hang at `await page.setContent('<html>hello world</html>')`
It was working at a specific comit on 0.13.0 for exemple this one : github:GoogleChrome/puppeteer#d1f044e18ff6eeb80468e4f30dbd99618dc13f96
but it's not working for 0.13.0 (latest)

**Comment by ebidel** [comment]
Have you seen https://github.com/GoogleChrome/puppeteer/issues/728#issuecomment-334301491?

**Comment by GautierT** [comment]
No. Thanks a lot for pointing that to me.
Sorry for the duplicate. 😕
