### ISSUE TITLE
TypeError: request.resourceType is not a function

### ISSUE THREAD

**Issue by decomorreno** [puppeteer/puppeteer#1642]
I copied an example and want to run it on my pc

`const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch({headless: false});
const page = await browser.newPage();
await page.setRequestInterception(true);
page.on('request', request => {
  if (request.resourceType() == 'image')
    request.abort();
  else
    request.continue();
});
await page.goto('https://news.google.com/news/');
await page.screenshot({path: 'news.png', fullPage: true});

await browser.close();

})();`

And i get a bug:

> (node:8296) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: request.resourceType is not a function
(node:8296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
 with a non-zero exit code.

**Comment by yujiosaka** [comment]
@vickersx 
That's probably you are seeing master branch's doc. If you are using the version of 0.13.0 or less, see [here](https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/docs/api.md#requestresourcetype). In this version, resourceType is not a method but just a readonly property.

So, your code can be fixed as below:
```
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', request => {
    if (request.resourceType == 'image')
      request.abort();
    else
      request.continue();
  });
  await page.goto('https://news.google.com/news/');
  await page.screenshot({path: 'news.png', fullPage: true});
  await browser.close();
})();
```
