### ISSUE TITLE
Puppeteer use webpack packaged into a single file, the program running error

### ISSUE THREAD

**Issue by vc1** [puppeteer/puppeteer#1644]
* Puppeteer version: 1.0.0.0-rc

I want to wrap the code and library environment in a single file using webpack.
send the program to others to use, only need to install node after packing

https://github.com/GoogleChrome/puppeteer/blob/391d1abaa7743302cf36135ecaa82139a672c057/lib/Downloader.js#L53

However, the above code is running after the package error

```
\dist\main.js:31619
    return !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()).puppeteer.chromium_revision;

         ^

Error: Cannot find module "."
```

I read some article information , may be webpack can not load the path generated by dynamic variables.
require code can be changed to the relative path of string splicing?

(English translated by Google ...)

**Comment by aslushnikov** [comment]
Unfortunately, we don't know much about WebPack here; I'd rather ask on StackOverflow or on webpack's bugtracker.

**Comment by MaksJS** [comment]
https://github.com/GoogleChrome/puppeteer/issues/2245
