### ISSUE TITLE
spawn EACCES when trying to give executablePath

### ISSUE THREAD

**Issue by melkayam92** [puppeteer/puppeteer#1649]
* Puppeteer version: 0.13.0
* Platform / OS version: macOS 10.13.2

 const browser = await puppeteer.launch({
      executablePath:
        ".../Chromium.app",
      headless: false
  });

I get: 

 { Error: spawn EACCES
    at _errnoException (util.js:1031:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at Object.exports.spawn (child_process.js:499:9)
    at Function.launch (/Users/USER/Code/Test/node_modules/puppeteer/lib/Launcher.js:98:40)
    at <anonymous> errno: 'EACCES', code: 'EACCES', syscall: 'spawn' }

I check the Chromium.app and the permissions look fine.

** Checked on windows 10 and it's working **

Any idea how to make it work on mac?

**Comment by yujiosaka** [comment]
```
sudo chmod 755 .../Chromium
```
Any special thing you did on installation?

**Comment by yujiosaka** [comment]
@melkayam92 
```
sudo chmod 755 .../Chromium
```
Any special thing you did on installation?

**Comment by melkayam92** [comment]
@yujiosaka 

Tried that command, didn't work. the weird thing is that even when the executable path is the one that in the node_modules/puppeteer folder -  still got the same error. (If I don't put any executable path - it does work).

And it was regular installation.

**Comment by rustkt** [comment]
You should use the path below:
`/Applications/Chromium.app/Contents/MacOS/Chromium`

**Comment by melkayam92** [comment]
@indexmotion Thanks! its worked.

**Comment by rustkt** [comment]
My pleasure, it sometimes really puzzle people but "xxx.app" is just a folder on OS X essentially, not an executable. Now please close this issue, thanks!

**Comment by K-D-K** [comment]
> sudo chown -R username *
After executing this command it works for me.

**Comment by ggojedap** [comment]
> You should use the path below:
> `/Applications/Chromium.app/Contents/MacOS/Chromium`

great! thank you 👍

**Comment by stone1930** [comment]
> You should use the path below:
> `/Applications/Chromium.app/Contents/MacOS/Chromium`

Thanks! its worked.

**Comment by fudgi** [comment]
Worked for me

/Applications/Google Chrome.app/Contents/MacOS/Google Chrome

**Comment by mread1208** [comment]
@rustkt 4.5 years later and your comment is still saving people.  Thank you!  I did have to tweak as @fudgi mentioned above:

```
"executablePath": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
```

**Comment by gauravgandhi1315** [comment]
@mread1208 @rustkt I am seeing the same error for firefox but in Linux env. How would I fix it?


`    browser = await firefox.launch({ executablePath: './node_modules/playwright-firefox', headless: true });
`

**Comment by gauravgandhi1315** [comment]
```
browserType.launch: Failed to launch: Error: spawn ./node_modules/playwright-firefox EACCES
```


I tried to use this path as well `Firefox 100.0.2 (playwright build v1327) downloaded to /jenkins/.cache/ms-playwright/firefox-1327` but issue remains the same

**Comment by xgqfrms** [comment]
## for macOS

```js
  const browser = await puppeteer.launch({
    // headless: "new",
    headless: false,
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  });
```
