### ISSUE TITLE
browser.newPage() sometimes never resolves

### ISSUE THREAD

**Issue by pavsidhu** [puppeteer/puppeteer#1650]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: MacOS High Sierra 10.13.1
* URLs (if applicable): Any

**What steps will reproduce the problem?**

```
const browser = await puppeteer.launch({ headless: false })
const page = await browser.newPage()
await page.goto(`https://www.google.co.uk`, {
      waitUntil: 'domcontentloaded'
})
```

**What is the expected result?**
I expect the browser to open a new page and load the URL given every time

**What happens instead?**
The browser opens a new page with the URL being `about:blank` and the URL I expect to load never loads. However sometimes it works which is the confusing bit.

`page.goto()` never ends up running because the code sticks at `browser.newPage()`.

**Comment by benjamingr** [comment]
This happens (in my experience) when Puppeteer is pointed towards an incompatible version of Google Chrome.

There was an API breakage at some point and if you updated puppeteer without chromium (or vice versa) this can be caused.

Can you try removing the node_modules directory and reinstalling puppeteer and see if it reproduces? It might be something in how puppeteer updates.

**Comment by pavsidhu** [comment]
@benjamingr I tried doing what you said, updating puppeteer node_modules, and still no luck. It's strange because yesterday, it was working fine, `browser.newPage()` resolved and now today it isn't. I can't put my finger on what the issue is here.

**Comment by rustkt** [comment]
Which browser do you use? Chrome or Chromium? If Chrome, is that installed some 3rd-party plugins that will effect browser's working?

I use Chromium that downloaded from official site (not installed by Homebrew), everything goes well.

**Comment by aslushnikov** [comment]
@pavsidhu I can't reproduce this either. 

Some troubleshooting tips:
1. Try installing puppeteer@next and see if it works: `npm i --save puppeteer@next`. This is a tip-of-tree version of puppeteer published on every commit to the repository.
2. Try running the following snippet:
```js
const pptr = require('puppeteer');
(async () => {
  const browser = await pptr.launch();
  console.log(await browser.version());
  await browser.close();
})();
```
This outputs `HeadlessChrome/65.0.3298.0` for me on current tip-of-tree.

This seems to be an issue with your environment, and the symptoms are indeed similar to the ones of and old chrome. I'll close this for now, but feel free to write back if you think we can help somehow.

**Comment by laggingreflex** [comment]
I'm having this issue with puppeteer v1.4 and the above output `HeadlessChrome/68.0.3419.0`. 

But strangely it works when I set `headless: false`. 

* Puppeteer version: 1.4
* Platform / OS version: Win 10 

Edit: Opened an issue: https://github.com/GoogleChrome/puppeteer/issues/2538

**Comment by benjamingr** [comment]
@laggingreflex please open a new issue
