### ISSUE TITLE
how to find focused element

### ISSUE THREAD

**Issue by saknarak** [puppeteer/puppeteer#1651]
I want to check which element was focused.
for example,
- When page loaded, it should focus on username input
- When press Tab, it should focus on password input

Please advise!

**Comment by vsemozhetbyt** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement ?

**Comment by mykolavlasov** [comment]
`await page.evaluateHandle(() => document.activeElement);`
