### ISSUE TITLE
How to  disabled the welcome windows 10 page ?

### ISSUE THREAD

**Issue by blusoul** [puppeteer/puppeteer#1653]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^0.13.0
* Platform / OS version: windows 10
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. I have set chrome as the default browser
2. How to  disabled the welcome windows 10 page in Chromium?

**Comment by JoelEinbinder** [comment]
You can start Puppeteer with `about:blank` like so:
```js
puppeteer.launch({
  headless: false,
  args: ['about:blank']
});
```

**Comment by blusoul** [comment]
Thank you~
But，It‘s not perfect，there is still an extra blank page

**Comment by aslushnikov** [comment]
@blusoul you can use  `browser.pages()` to close an excessive tab.

**Comment by blusoul** [comment]
@aslushnikov Thank you. This is a good idea.  Although I can't find configurable parameters..

**Comment by aslushnikov** [comment]
> Although I can't find configurable parameters..

@blusoul what parameters are you looking for?

**Comment by blusoul** [comment]
@aslushnikov  Chromium did not provide the parameters to hide the default page , like args: ['about:blank'] , but your idea is very good, thanks~
