### ISSUE TITLE
`page.waitForFunction` should treat ElementHandle arguments as DOM elements

### ISSUE THREAD

**Issue by rustkt** [puppeteer/puppeteer#1654]
**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: OS X 10.12.5
* URLs (if applicable): <null>

**What steps will reproduce the problem?**

```typescript
import * as puppeteer from 'puppeteer';

puppeteer
  .launch({ executablePath: '/Applications/Chromium.app/Contents/MacOS/Chromium', headless: false })
  .then(async browser => {
    const page = await browser.newPage();
    await page.goto('http://cn.bing.com');
    await page.waitForSelector('div.hp_sw_logo');
    const logo = await page.$('div.hp_sw_logo');
    await page.waitForFunction((el: HTMLElement) => {
      return el.offsetWidth == 132;
    }, undefined, logo);
  });
```

**What is the expected result?**

The `el` argument should be the right DOM element that presents the ElementHandle passed in (`logo`). Just like the behaviors on invoking `page.evaluate` and `page.evaluateHandle`.

**What happens instead?**

`TypeError: Converting circular structure to JSON` raised.

**Comment by marco-pragliola** [comment]
Same problem here. Cannot pass elements to `waitForFunction()` because `ElementHandle` is not serializable.
