### ISSUE TITLE
--disable-extensions always added even if ignoreDefaultArgs is true

### ISSUE THREAD

**Issue by gpetrov** [puppeteer/puppeteer#1655]
When running Peppeteer with **ignoreDefaultArgs:true** Chrome always gets **--disable-extensions** as command line argument.

This is specially bad when trying to run Peppeteer with NWjs as it prevents the apps from starting
See https://github.com/nwjs/nw.js/issues/6350

**Comment by gpetrov** [comment]
Seems that this issue is addressed with https://github.com/GoogleChrome/puppeteer/commit/8a40cd5eef86fe8c3a4894775de8e1d269836857

@aslushnikov  or @JoelEinbinder please push new version to npm

**Comment by vsemozhetbyt** [comment]
FWIW, you can upgrade to the tip of the tree with:
`npm install https://github.com/GoogleChrome/puppeteer/`

**Comment by aslushnikov** [comment]
@gpetrov there's now `puppeteer@next` that is a bleeding edge version of puppeteer.

The 1.0.0 will be released shortly.
