### ISSUE TITLE
Performance issue page.screenshot

### ISSUE THREAD

**Issue by guillem-catala** [puppeteer/puppeteer#1656]
version    "puppeteer": "0.13.0"
docker container: node:9.2.0-slim

I am working on a project to generate many "simultaneous" screenshots in real time very fast. The problem is that sometimes the process hangs forever, not returning any error. I am reusing the same connection and page for each request.

```
...

const websocketDebuggerUrl = execSync(`echo '<html></html>' | node run/webSocketDebuggerUrl.js 127.0.0.1:9222`).toString().replace(/\n/g, '');
puppeteer.connect({ browserWSEndpoint: websocketDebuggerUrl }).then(async (browser) => {
  const page = await browser.newPage();
  page.on('error', msg => {
    console.log('error page closes')
  });
  app.locals.page = page;

  // Launch listening server
  app.listen(PORT, () => { });
}).catch((error) => {
  console.log(`Chrome instance not running: ${error}`);
});

let chain = Promise.resolve();
...

app.get('/screenshot', async (req, res) => {
    let page = app.locals.page;
    chain = chain.then(async () => {
      await page.goto(`${BASE_URL}/?${querystring.stringify(req.query)}`);
      await page.waitFor('#renderDone', { timeout: 10000 });
      const title = await page.$('#lienzo');
      const clip = await title.boundingBox();
      const screenshot = await page.screenshot({
        type: 'png',
        clip
      });
      res.writeHead(200, {
        'content-type': 'image/png'
      });
     res.end(screenshot, 'binary');
    }).catch((error) => {
      console.error(`Cannot open new page ${error}`);
      res.end('', 'binary');
      return false;
    });
});
```
In my use case the screenshots takes like 60-90 ms each. If I request like 10+ screenshots per second at some point it hangs.  Commenting the page.screenshot method it never hangs. So I suspect that is the problem.

Any ideas on how to proceed?  thanks :)

**Comment by guillem-catala** [comment]
I have found the bug. The problem is that I'm making screenshots so fast that sometimes the clip I pass as a parameter to the Page.screenshot method contains invalid values, like a bounding box of 0 height because the browser has not yet calculated the dimensions of the element.

> 1|Express  | Fri, 29 Dec 2017 14:54:14 GMT puppeteer:session SEND ► {"id":88,"method":"Page.captureScreenshot","params":{"format":"png","clip":{"x":8,"y":8,"width":784,"height":0,"scale":1}}}

I think this needs a fix in puppeeter maybe checking that values are greater than 0 here
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L662

Or maybe a deeper fix, but I don't know yet how screenshot works I suppose it is delegated to the client...?

**Comment by aslushnikov** [comment]
@zamzam I believe this is fixed on tip-of-tree puppeteer. Please let me know if its not.
