### ISSUE TITLE
setRequestInterception URL broken?

### ISSUE THREAD

**Issue by mboeser** [puppeteer/puppeteer#1657]
url on setRequestInterception object no longer references the Request URL.

console.log(interceptedRequest.url) will produce = "_setRequestInterception url() {return this._url;}_"

workaround is to use the underscore reference on the obj: console.log(interceptedRequest.**_url**) 

Anyone else able to reproduce this?

Puppeteer: Git Version #1633 
Node: 8.9.3
MacOS: 10.13.2

page.on('request', interceptedRequest => {

console.log(interceptedRequest.url) 

    if (interceptedRequest.url.endsWith('.png') || interceptedRequest.url.endsWith('.jpg'))
      interceptedRequest.abort();
    else
      interceptedRequest.continue();
  });

**Comment by yujiosaka** [comment]
@mboeser 
That's because request.url is no longer a property but is a function in the master branch.
Your code worked for 0.13.0 but no longer works.

In order to fix this, you have to call the method like this `console.log(interceptedRequest.url())`

**Comment by mboeser** [comment]
Thanks @yujiosaka, I can confirm that worked. Curious as to why the change, scalability perhaps... Is it safe to say url will no longer be a property moving forward? If so, the docs and examples will need some updating too.

**Comment by yujiosaka** [comment]
@mboeser 
The API changed [here](https://github.com/GoogleChrome/puppeteer/pull/1621). It seems that the docs and the examples are changed correctly at the same timing. The reason is written in the PR description btw.
It happens when you use master branch, and it's a good thing :)

**Comment by mboeser** [comment]
Thanks for pointing that out. I will now close this.
