### ISSUE TITLE
Possible race condition when simulating double click - dedicated API method needed

### ISSUE THREAD

**Issue by canonic-epicure** [puppeteer/puppeteer#1659]
It seems currently the only way to simulate double click is to call `mouse.down()/up/down/up". 

Every call will wait until previous one completes. And if the remote method call is performed using the network (like websocket) there's a possibility of arbitrary delay between the calls. 

If such delay will exceed the double click threshold - browser won't fire the "dblclick" event, only 2 regular clicks.

This is a potential race condition.

**Comment by aslushnikov** [comment]
@JoelEinbinder is there any way to simulate `dblclick` event? Will the [mouse.click](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#mouseclickx-y-options) with `clickCount` argument work?

**Comment by JoelEinbinder** [comment]
Yep! `dblclick` is fired by `clickCount`, not by the timeout. That way we can send clicks as fast as possible without triggering double click, or send double clicks with arbitrary delay in between each click.

```js
 const button = await page.$('button');
 await button.click();
 await new Promise(x => setTimeout(x, 1000));
 await button.click({ clickCount: 2 });
```

**Comment by canonic-epicure** [comment]
Good to know. This detail (setting `clickCount` for simulating double click) should be mentioned in docs for "click" method then..

**Comment by stoffeastrom** [comment]
This doesn't work for us. Using `ng-dblclick` in an old angular `1.5.8`. Tried setting different `delay` for the `click` without success. The only way I could get it to work was doing:

```
await page.goto('foo-url', { waitUntil: 'networkidle0' });
const from = await page.$('.foo-item');
const fromBox = await from.boundingBox();
const fromX = fromBox.x + fromBox.width / 2;
const fromY = fromBox.y + fromBox.height / 2;
await page.evaluate((e, clientX, clientY) => {
return e.dispatchEvent(new MouseEvent('dblclick', { bubbles: true, cancelable: true, clientX, clientY }));
    }, from, fromX, fromY);
await page.waitFor('.foo-something');
```

**Comment by JoelEinbinder** [comment]
@stoffeastrom can you share the puppeteer code that didn't work for you? The delay has no effect on whether or not a `dblclick` is sent. That is entirely decided by the `clickCount` field.

**Comment by stoffeastrom** [comment]
Tried getting the element and explicitly call click on that
Tried using the page to click

```
const foo = await page.$('.foo-item');
await = foo.click({ clickCount: 2 });
```
```
await page.$('.foo-item', { clickCount: 2 });
```

Looks like the `first` click is happening (I get a `hover` effect) but the next click is "missing" I don't know if it's because it's to slow or if it's something else. It might be the app since there is both `click` `dblclick` and `dnd` actions on that item


I've also noticed trying to drag and drop is not working ootb without explicitly adding some `waitFor` e.g

```
const from = await page.$('.foo');
const fromBox = await from.boundingBox();
const fromX = fromBox.x + fromBox.width / 2;
const fromY = fromBox.y + fromBox.height / 2;
const to = await page.$('.foo-something');
const toBox = await to.boundingBox();
const toX = toBox.x + toBox.width / 2;
const toY = toBox.y + toBox.height / 2;
await page.waitFor(400);
await page.mouse.move(fromX, fromY, { steps: 10 });
await page.waitFor(400);
await page.mouse.down();
await page.waitFor(400);
await page.mouse.move(toX, toY, { steps: 10 });
await page.waitFor(400);
await page.mouse.up();
```

It feels like it's "too fast" :) in the dnd case

**Comment by JoelEinbinder** [comment]
You still have to send both clicks, the second one just gets a clickCount of 2.

Does this work?
```js
const foo = await page.$('.foo-item');
await = foo.click();
await = foo.click({ clickCount: 2 });
```

**Comment by stoffeastrom** [comment]
Oh, missed that about the `clickCount`. Unfortunately it still doesn't work. I guess it has todo with the app so I'll try to find out the problem on my side.

Thanks for the help

**Comment by Kname80** [comment]
is there another solution for this ,  I tried all the suggestions nothing works
