### ISSUE TITLE
Try to introduce golden pdf tests

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#166]
The `page.pdf()` method is poorly tested.
To test it properly, we'd need to actually generate pdf's and to compare them against golden results, like we do with screenshots.

**Comment by JoelEinbinder** [comment]
The pdf file generated isn't deterministic. It has things like the date and chrome version embedded in it. My original plan was to generate the pdf, open the pdf in chrome, and take a screenshot of that. But I couldn't get the pdf viewer to work in headless.

Nightmare checks that the file exists and is above some filesize.
https://github.com/segmentio/nightmare/blob/e68d0f2ec7e32da9d2f353eb3ed19e86adce0f6d/test/index.js#L1493

Phantom tries to normalize the pdf, but mentions that the test doesn't work.
https://github.com/ariya/phantomjs/blob/5cb736d2f4782f725c6c66431407ff174c512ba1/test/module/webpage/renderBase64.js

**Comment by aslushnikov** [comment]
We have quite a bit of options in the `page.pdf()` method, and it definitely needs some testing. The nightmare's approach wouldn't work for us.

I looked into pdf normalizers but didn't find anything interesting.

One other interesting idea might be to use [pdf.js](https://github.com/mozilla/pdf.js) api to inspect the resulting pdf.

**Comment by JoelEinbinder** [comment]
We can do it on travis if we install imagemagick. See https://www.npmjs.com/package/pdf-image

It seems a bit overkill to require contributors to set that up in order to test though.

**Comment by aslushnikov** [comment]
Agreed, it would be really nice to have `npm install` be the only necessary step.
