### ISSUE TITLE
How to handle "site can't be reached"

### ISSUE THREAD

**Issue by decomorreno** [puppeteer/puppeteer#1660]
I simulate ddosed site on my localhost, so it often returns "site can't be reached" How can i automaticly reload page with puppeteer when site can't be reached?

In console i got such error:

> (node:1740) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: net::ERR_ADDRESS_IN_USE
(node:1740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.
js process with a non-zero exit code.

[photo](https://i.imgur.com/jrfJfMZ.png)

**Comment by aslushnikov** [comment]
It looks like this exception is thrown by `page.goto` method. You can catch the promise rejection there and reload the page if necessary.
