### ISSUE TITLE
Node is not visible

### ISSUE THREAD

**Issue by jydchanglong** [puppeteer/puppeteer#1662]
"version": "0.13.0"
code: await page.click('.s_btn');
This button is invisible which CSS attribute is 'display: none'.
So how can I trigger the button？

**Comment by aslushnikov** [comment]
@jydchanglong you can click it with javascript:

```js
await page.evaluate(() => {
  document.querySelector('.s_btn').click();
});
```

**Comment by dilipkumar2k6** [comment]
What will be equivalent of `document.querySelector('.s_btn').click()`  for `xpath`?

**Comment by KrustyC** [comment]
@aslushnikov  I have the same issue, but using the evaluate function doesn't work as the page is re-evaluated and I should re-do every single step...is there any way to select an element only if displayed?
