### ISSUE TITLE
load vs network-idle

### ISSUE THREAD

**Issue by namma-geniee** [puppeteer/puppeteer#1666]
Please help me differentiate "load" and "networkidle"!

Thank you!

**Comment by mboeser** [comment]
I believe it's when the browser fires the Load event. Curious to know if 'networkidle' is dependent on the load event first then listens to network activity.

https://developer.mozilla.org/en-US/docs/Web/Events/load

**Comment by aslushnikov** [comment]
I assume we're talking about the `waitUntil` argument of `page.goto` method and others.

The "load", "networkidle0" and "networkidle2" arguments tell puppeteer when to consider navigation
successful. In this regards, "load" and "networkidle" arguments are orthogonal:
-  `load` argument corresponds to the [`load`](https://developer.mozilla.org/en-US/docs/Web/Events/load) event in the page. In certain cases, it might not happen at all
- `networkidle0` argument considers navigation successful when page has no network activity for half a second. This might never happen if the page is constantly loading multiple resources.
- `networkidle2` argument considers navigation successful when page has no more then 2 network requests for half a second. This is useful if page runs a long polling in the background.

Different arguments work for different pages. When neither of them work, a good solution would be to navigate with `domcontentloaded` argument and then simply wait for the needed element to appear on page:

```js
await page.goto('http://example.com', {waitUntil: 'domcontentloaded'});
await page.waitForSelector('h1');
```

**Comment by YumaInaura** [comment]
i wonder networkidle0 or networkidle2 
which is strict 

which happens few "CSS unloaded" trouble

( on convert HTML to PDF )

**Comment by YumaInaura** [comment]
maybe
one way
load and waitUntil both specify

```
    await page.goto(html_url, {waitUntil: ['load', 'networkidle0']});
```


# ref

>How to use networkidle0 / networkidle2
>page.waitForNavigation () can only wait until the page finishes loading. In other words, CSS and JavaScript interpretation may not be finished at this timing. For pages that dynamically change HTML with JavaScript, you may want to use {waituntil: 'networkidle2} `, which waits 500ms after the last communication.

>However, if you just specify {waituntil: 'networkidle2} in the argument of page.waitForNavigation (), it may not work as expected. Especially on a weak machine (such as Raspberry Pi), HTML rendering may not finish even if communication is over.

>Assuming such a situation, the following way of writing seems to be correct.

```
await Promise.all ([[
  page.waitForNavigation ({waitUntil: ["load", "networkidle2"}),
  page.click ('a')
]);
```

>Even then, there is no guarantee that JavaScript has been interpreted, so depending on the situation, it may be necessary to wait for the appearance of specific elements.

[Puppeteerで次ページへの遷移を待つ - Qiita](https://qiita.com/hnw/items/a07e6b88d95d1656e02f)

**Comment by ecolss** [comment]
> I assume we're talking about the `waitUntil` argument of `page.goto` method and others.
> 
> The "load", "networkidle0" and "networkidle2" arguments tell puppeteer when to consider navigation
> successful. In this regards, "load" and "networkidle" arguments are orthogonal:
> 
> * `load` argument corresponds to the [`load`](https://developer.mozilla.org/en-US/docs/Web/Events/load) event in the page. In certain cases, it might not happen at all
> * `networkidle0` argument considers navigation successful when page has no network activity for half a second. This might never happen if the page is constantly loading multiple resources.
> * `networkidle2` argument considers navigation successful when page has no more then 2 network requests for half a second. This is useful if page runs a long polling in the background.
> 
> Different arguments work for different pages. When neither of them work, a good solution would be to navigate with `domcontentloaded` argument and then simply wait for the needed element to appear on page:
> 
> ```js
> await page.goto('http://example.com', {waitUntil: 'domcontentloaded'});
> await page.waitForSelector('h1');
> ```

I wonder if this great answer still holds in 2020 :-)?

**Comment by 3r8ydfow9fcdiujloj** [comment]
> I assume we're talking about the `waitUntil` argument of `page.goto` method and others.
> 
> The "load", "networkidle0" and "networkidle2" arguments tell puppeteer when to consider navigation successful. In this regards, "load" and "networkidle" arguments are orthogonal:
> 
> * `load` argument corresponds to the [`load`](https://developer.mozilla.org/en-US/docs/Web/Events/load) event in the page. In certain cases, it might not happen at all
> * `networkidle0` argument considers navigation successful when page has no network activity for half a second. This might never happen if the page is constantly loading multiple resources.
> * `networkidle2` argument considers navigation successful when page has no more then 2 network requests for half a second. This is useful if page runs a long polling in the background.
> 
> Different arguments work for different pages. When neither of them work, a good solution would be to navigate with `domcontentloaded` argument and then simply wait for the needed element to appear on page:
> 
> ```js
> await page.goto('http://example.com', {waitUntil: 'domcontentloaded'});
> await page.waitForSelector('h1');
> ```

I managed to fix LinkedIn profiles loading with this answer. Thank you!
