### ISSUE TITLE
page.click fails if webpage redefines window.Node

### ISSUE THREAD

**Issue by nylen** [puppeteer/puppeteer#1668]
If a webpage redefines `window.Node` (to a function, in my case), then calling `self.page.click( 'selector' )` will fail with the following error:

```
Error: Node is not of type HTMLElement
```

The error occurs here:  https://github.com/GoogleChrome/puppeteer/blob/v0.13.0/lib/ElementHandle.js#L47

`Node.ELEMENT_NODE` is `undefined` at this point.

**Comment by vipk31** [comment]
Ok

**Comment by aslushnikov** [comment]
Thanks for the heads-up. This has the same core issues as #609. Closing as dupe, please upvote to have it fixed and to influence our prioritization
