### ISSUE TITLE
Provide option to set dpi of generated screenshot

### ISSUE THREAD

**Issue by seekshiva** [puppeteer/puppeteer#1669]
### Steps to reproduce

* Puppeteer version: all?
* Platform / OS version: all?
* URLs (if applicable): -

**What steps will reproduce the problem?**

screenshot api doesn't allow setting dpi of target image

**What is the expected result?**

screenshot api allows setting dpi of target image

Sort of similar to #1057 (which is for setting dpi for pdf)

**Comment by aslushnikov** [comment]
You can use [`page.emulate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageemulateoptions) to setup a viewport with a different scale factor.

**Comment by seekshiva** [comment]
That doesn't work. When I do `setViewport()` with `{ height: 100, width: 100, deviceScaleFactor: 2 }`, and take screenshot with `clip: { top: 0, left: 0, width: 100, height: 100 }`: The screenshot image generated has 200x200 pixels and the file is at 72dpi. If I set deviceScaleFactor: 4, the resultant screenshot image is 400x400 pixels with 72dpi.

As you can see, changing deviceScaleFactor is only producing image with more pixels.

Also, I have a div with border: 1px and when I take the screenshot, the dashed border appears with 2px and 4px respectively. I want it to be at 1px only.

dpi of resultant image is always 72. I need to be able to configure dpi of resultant image, while the border still appears at 1px and not changing according to what device scale factor I set.

**Comment by seekshiva** [comment]
You can check the dpi setting on an image by opening it in Photoshop or a similar app.

**Comment by aslushnikov** [comment]
@seekshiva the dpi you refer to is not the property of the image; it's just the exif label. We don't write any exif metadata - the `72dpi` value reported by photoshop is a default value it uses.

**Comment by ispringer** [comment]
I am having the same issue described by @seekshiva, where the screenshot PNG has twice the specified width and height. 

I am doing:

```
await page.setViewport({
    width: 250,
    height: 250,
    deviceScaleFactor: 2
});
```

And then the PNG file that is output is 500x500:

```
$ pngcheck -v test.png
File: /tmp/test.png (48752 bytes)
  chunk IHDR at offset 0x0000c, length 13
    500 x 500 image, 32-bit RGB+alpha, non-interlaced
  chunk IDAT at offset 0x00025, length 8192
    zlib: deflated, 32K window, default compression
  chunk IDAT at offset 0x02031, length 8192
  chunk IDAT at offset 0x0403d, length 8192
  chunk IDAT at offset 0x06049, length 8192
  chunk IDAT at offset 0x08055, length 8192
  chunk IDAT at offset 0x0a061, length 7675
  chunk IEND at offset 0x0be68, length 0
No errors detected in /tmp/test1.png (8 chunks, 95.1% compression).
```

I am on Mac OS X and using Puppeteer 1.7.0.

**Comment by joelanman** [comment]
I'm having this problem.

If I use MacOS to take a screenshot, the DPI is recorded in the PNG (144) and the image looks correct in Preview.

If I use Puppeteer to take a screenshot, the DPI is not correct (72) and the image looks pixelly at 100% zoom in Preview.

Would it be possible to record the correct DPI as MacOS does?

Let me know if I can help with any more info.

**Comment by joelanman** [comment]
I've found a workaround using this library to set the png DPI:

https://github.com/daiiz/png-dpi-reader-writer

**Comment by sqcddzx** [comment]
Set the DPI with GraphicsMagick, `gm convert -quality 100 -density 300 input.jpg  output.jpg`

**Comment by sqcddzx** [comment]
Set the DPI with GraphicsMagick, `gm convert -quality 100 -density 300 input.jpg  output.jpg`

**Comment by cnicodeme** [comment]
I do wonder if a `deviceScaleFactor` set to two really creates an image with a DPI of 72,  or as @aslushnikov said, it's not the "real" value ?

In other terms, @sqcddzx , does passing the outputted image to GraphicsMagick changes the quality of the image, or just the EXIF metadata to 300 instead of 72 ?
