### ISSUE TITLE
Feature Request: Puppeteer in the devtools console

### ISSUE THREAD

**Issue by patrickeakin** [puppeteer/puppeteer#1670]
I am building a suite of automated tests using Puppeteer, Mochajs and Chaijs. While building the tests I rely heavily on the devtools console to find the right way to select elements, to traverse nodelists, to determine what to validate, basically to figure out what i need to do in my Puppeteer scripts. Though there is always a translation that needs to happen which involves experimenting with Puppeteer methods and running my scripts over and over till I get it right.

What I would love is the ability to control the browser step by step in the devtools, using Puppeteer. This would help me to experiment and ultimately determine what I need to use in my scripts without the need to run the scripts with every new step.

Thanks for all the hard work you have put into this tool.

**Comment by aslushnikov** [comment]
I'd love this as well. We'll see if we can allocate some time to implement this.

**Comment by skyiea** [comment]
@patrickeakin You can open `node` process in CLI and use `puppeteer` to control the browser command by command, step by step. This way you don't need to run your scripts over and over again. Is that what you meant?

**Comment by patrickeakin** [comment]
@skyiea That is exactly what I'm after. Thanks for pointing me in that direction.

**Comment by aslushnikov** [comment]
Ah, I've thought about something different. Closing this then.

**Comment by charliekump-wf** [comment]
@aslushnikov Is there another issue tracking more along the lines of what you were thinking as far as adding puppeteer to the DevTools console? I would like to see something along those lines as well.

**Comment by aslushnikov** [comment]
@charliekump-wf we don't have any plans on adding pptr api to devtools. Can you share your ideas and your usecases?

**Comment by charliekump-wf** [comment]
@aslushnikov May not be feasible, but I was thinking along the lines of being able to execute puppeteer API from DevTools console. Would help with troubleshooting being able to experiment while being connected right on the page. Bigger use case I was looking at was our application is for creating documents and I have scripted out generating documents and content using puppeteer and thought it would be cool if testers/devs/support could just execute similar scripts with the app already up in Chrome.

**Comment by aslushnikov** [comment]
cc @JoelEinbinder who was thinking along these lines

**Comment by dashmug** [comment]
I was looking for this as well.

**Comment by srepollock** [comment]
I was looking to use pptr to run my visual unit tests, but I would also like to use it and run commands in the dev tools of the pptr window or instance I'm running. Is there a way to do this in pptr currently?
