### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1)

### ISSUE THREAD

**Issue by kottackalaiswarya** [puppeteer/puppeteer#1676]
<!--

I was trying to run a CORDOVA Project . But after i install the SDKs required, i was getting errors while running the app.
**ERRORS**
```
kottackal@kottackal-aiswarya:~/Desktop/toptal$ cordova build android
Android Studio project detected
(node:15500) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
(node:15500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```
 Please help me in solving this issue so as to run the project.

**Comment by Cotspheer** [comment]
Saw your issue on bountysource.com today. Ensure that you have installed the latest version of all required plugins and node packages. Ensure that the version within package.json matches within the config.xml file from cordova. Remove the version flags (^, ~ etc.) to ensure that the specified version gets installed. 

After that, remove following directories: "platforms", "plugins", "node_modules". And remove the package-lock.json, it will be regenerated afterwards. Now run following commands:

1. npm remove cordova -g                _remove old version_
2. npm cache clean --force                _ensure cache is clean_
3. npm install cordova -g                  _install latest cordova version_
4. npm install                                    _run within project for a fresh installation_
5. cordova prepare                           _restore plugins and platform for an existing cordova project_

The fifth point on the bullet list should to the trick. Faced the same problem today on an ionic cordova project and this resolved the error.

**Comment by aslushnikov** [comment]
Issue description doesn't give enough information; hopefully @NightkingCH answer addresses the OP.

**Comment by foyer** [comment]
I had to remove phonegap and then I was able to successfully build in cordova. Had the same issue.
