### ISSUE TITLE
[Feature request] Mouse wheel API calls

### ISSUE THREAD

**Issue by canonic-epicure** [puppeteer/puppeteer#1679]
Sounds a bit old in our age of touch interfaces, but would be great to have native mouse wheel simulation (to use with existing code).

**Comment by schelkun** [comment]
We can use this:
```js
page.evaluate(`window.scrollBy(0, ${amount});`);
```

Wheel simulation is a cycle with evaluating this function, and `page.waitFor(time)`, right?

**Comment by JoelEinbinder** [comment]
Native mouse wheel is a bit different. You get 'wheel' events in addition to 'scroll' events, and there is some intricate behavior with passive vs blocking scroll listeners.

There is some protocol functionality to emulate wheel events, but we don't have a good way at the moment to detect when the page has finished scrolling in response to the wheel event.

**Comment by canonic-epicure** [comment]
> There is some protocol functionality to emulate wheel events, but we don't have a good way at the moment to detect when the page has finished scrolling in response to the wheel event.

Isn't that a DOM "scroll" event?

**Comment by ajinkyas** [comment]
Hi Joel, I would like to work on this one. Can I proceed with the implementation?

**Comment by jjjj222** [comment]
Hi, is this API available now?
I have some diagrams drawn by SVG and users can use the wheel to zoom in/out.
I try to find a way to simulate the mouse wheel scroll at a given location with Puppeteer, but can't find any.

**Comment by normanzb** [comment]
This event will be very useful for testing customised UI that handles wheel event differently, such as map apps or gallery apps that zoom in and out according to wheel delta.

Also it would be useful for application such as co-browsing. Without wheel support, that means programmer will have to call `window.scrollBy` and that in turn means that they will have to convert the delta into pixels used by `scrollBy()`, which is always awkward to do so because of device differences.

**Comment by kblok** [comment]
@JoelEinbinder Are you planning to support [type.mouseWheel](https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/browser_protocol.json#L6799) using [Input.dispatchMouseEvent](https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/browser_protocol.json#L6788)?

It should be just an `Input.dispatchMouseEvent` call as we do in, for instance, [mouse.up](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Input.js#L250)

**Comment by cpuy** [comment]
Hi there,

Is there any progress on this issue?

I'm desperately trying to test a react app with puppeteer and can't find a way to trigger a WheelEvent.
Please note that, like @jjjj222, I'm testing a zoom component so the scroll behavior is not important to me.

Has anyone a workaround to do that ?

Thx

**Comment by nagyzsolthun** [comment]
Hi Team, is there any update on this?

**Comment by kaykyr** [comment]
Hello! Any update about it?
