### ISSUE TITLE
Get network requests

### ISSUE THREAD

**Issue by ZaninAndrea** [puppeteer/puppeteer#1680]
Is it possible to get the network requests (as in the chrome dev tools network tab)? I checked Chrome DevTools Protocol and they offer APIs to do that, but puppeteer does not.
I was wondering whether there is a way to make this work in puppeteer or to get the Chrom DevTools Protocol instance and use its APIs.

**Comment by Everettss** [comment]
You should check [`page.tracing`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-tracing) methods. Results from `page.tracing` contains all data from network tab and much more. 

I wrote an article ["Test website performance with Puppeteer"](https://michaljanaszek.com/blog/test-website-performance-with-puppeteer#extractDataFromNetworkTrace) containing example how to extract request data from `page.tracing`.

**Comment by ebidel** [comment]
^ 👍  You can also intercept/collect network requests as they happen:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue

**Comment by tomsaleeba** [comment]
> You should check [`page.tracing`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-tracing) methods. Results from `page.tracing` contains all data from network tab and much more.
> 
> I wrote an article ["Test website performance with Puppeteer"](https://michaljanaszek.com/blog/test-website-performance-with-puppeteer#extractDataFromNetworkTrace) containing example how to extract request data from `page.tracing`.

Blog isn't loading for me, but it seems the relevant blog content is available here: https://github.com/Everettss/test-website-performance-with-puppeteer/blob/master/4/testPage.js#L9.
