### ISSUE TITLE
"'Page.getFrameTree' wasn't found undefined" when using chrome

### ISSUE THREAD

**Issue by avitavdi** [puppeteer/puppeteer#1681]
Trying to automate filling a form.
When trying to use chrome Im getting the following error:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.getFrameTree): 'Page.getFrameTree' wasn't found undefined

Same code works with the out of the box chromium packaged with puppeteer. but I get different type of captach when using chromium thats why Im trying chrome.
Canary does not give this error but have other issues which i have not got to the bottom of yet

* Puppeteer version: ^0.13.0
* Platform / OS version: windows 10
* node: v8.9.3

STR:
``` javascript
 const browser = await puppeteer.launch({executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', headless:false,slowMo:250});
```

**What is the expected result?**
Chrome to open and load desired page.

**What happens instead?**
Chrome opens does not load page. throws an error instead

**Comment by aslushnikov** [comment]
It looks like you're using old version of chrome. Try using Chrome Canary instead of Chrome Stable.

**Comment by gpetrov** [comment]
@aslushnikov Please add a simple check if Page.getFrameTree and Page.setLifecycleEventsEnabled are available before usage so it runs fine on Chrome 63 as well ...

If they are not available just use Page.getResourceTree instead of  Page.getFrameTree

**Comment by aslushnikov** [comment]
@gpetrov unfortunately there are more things that differ underneath. Once we fully transition to the stable parts of the protocol / stabilize more protocol, it will not be a problem any more.

As a workaround, you can use an old version of puppeteer.

**Comment by houseofkodai** [comment]
as suggested by @aslushnikov 

Alpine Linux Chrome 63 works with puppeteer@0.12.0 (v0.13.0 and v1.0.0 generate the Page.getFrameTree undefined error.)

**Comment by zhenruyan** [comment]
chrome 63 and  chromium 59.0.3071.104  It all happened.
