### ISSUE TITLE
mouse.click is invalid

### ISSUE THREAD

**Issue by riskers** [puppeteer/puppeteer#1682]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: mac OS 10.13.2
* URLs (if applicable): https://codepen.io/riskers/full/xpqPee/

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer')

;(async () => {

  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 20
  })

  const page = await browser.newPage()

  await page.goto('https://codepen.io/riskers/full/xpqPee/') // test page

  await page.waitFor(5000)

  await page.setViewport({
    width: 1400,
    height: 800
  })

  const m = page.mouse

  await m.click(554, 135)  // coordinate

  await page.waitFor(5000)

  await page.screenshot({path: 'test.png'});
  await browser.close();
})()
```

**What is the expected result?**

get image:

<img width="582" alt="screenshot 2017-12-29 00 39 36" src="https://user-images.githubusercontent.com/5653652/34416917-c5d710ce-ec30-11e7-9a2f-1fbdd6c7b23f.png">

**What happens instead?**

Nothing show on page, seems to mouse.click is invalid.

**Comment by yujiosaka** [comment]
It's working for me with the following environment:

- Puppeteer version: 0.13.0
- Platform / OS version: mac OS 10.0.5
- URLs (if applicable): http://7rfjqi.com1.z0.glb.clouddn.com/index.html

**Comment by riskers** [comment]
@yujiosaka  sorry  the page url is error. I updated..

**Comment by riskers** [comment]
@yujiosaka thx...

it's my fault.
