### ISSUE TITLE
Cannot take a screenshot using puppeteer, it dumps an empty image file

### ISSUE THREAD

**Issue by segmentationfaulter** [puppeteer/puppeteer#1689]
I am having a skeleton html file named `test.html`, and here is what it contains:

```html
<!doctype html>
<html>

  <head>
  </head>

  <body>
  </body>

</html>
```

then I have another file aimed at opening the above file in chrome headless, inject an image into its `body` and then take its screenshot, have a look:

```js
const puppeteer = require('puppeteer')
const fs = require('fs');

(async() => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto('file://test.html')
  await page.$eval('body', (body) => {
    const imgElement = new window.Image()
    imgElement.src = 'https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png'
    body.appendChild(imgElement)
  })
  await page.waitForSelector('img')
  fs.writeFileSync('output.html', await page.content())
  await page.screenshot({
    path: 'screenshot.jpg'
  })
  await browser.close()
})()
```

Upon running this code, I get an empty image as a screenshot, whereas I was expecting it containing an image. You can also note that I am dumping the contents of the page before taking a screenshot in an `output.html` file using this code:

```js
fs.writeFileSync('output.html', await page.content())
```

upon opening `output.html` in my browser, I get the right thing. What could be wrong with the above code that it is not behaving as expected. I have asked the same question [on stackoverflow](https://stackoverflow.com/questions/48008678/cannot-take-a-screenshot-using-puppeteer-it-dumps-an-empty-image-file), upon not getting an answer, I had to post it here. I am using following versions:

Node: 8.9.3
Puppeteer: 0.13.0
OS: Ubuntu 16.04

**Comment by Everettss** [comment]
This is due to that you didn't wait for the image to download. It is a race condition between image download and taking a screenshot. 
You should wait for image `onload` like this:

``` javascript
await page.$eval('body', async (body) => {
    const imgElement = new window.Image()
    imgElement.src = 'https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png'
    body.appendChild(imgElement)

    await new Promise(resolve => {
        imgElement.onload = resolve;
    });
});
```

**Comment by segmentationfaulter** [comment]
@Everettss Thanks man, it solved it.
