### ISSUE TITLE
Support for Node 5?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [puppeteer/puppeteer#1690]
I'd like to use this in the build step for a package that supports Node 5. README.md states at least version 6.4 is required - is there a reason?

**Comment by JoelEinbinder** [comment]
You could try to transpile puppeteer to work with node 5, but we don't run our tests on anything older than node 6. Puppeteer uses es6 features like rest and spread operators. We haven't had much demand for Node 5.

**Comment by JoshuaKGoldberg** [comment]
Would you be opposed to (me?) adding Babel to part of the release process? Either:
* Having the released .js files all be transpiled
* Having a separate transpiled version of the files?

**Comment by JoelEinbinder** [comment]
We can’t use Babel easily  because we use function.toString to send functions to Chrome. We have our own transpiler for node6 for this reason

**Comment by aslushnikov** [comment]
@JoshuaKGoldberg You might have success transpiling the node6-build puppeteer with babel, but we didn't try. We're not much interested in having node5 as a part of our core distribution unless there are really good and popular usecases (like Amazon Functions for Node6).

I'll close this for now, but please let me know if there are good reasons to have node5.
