### ISSUE TITLE
[Feature request] Ability to set instance prefs and localState in addition to args

### ISSUE THREAD

**Issue by skyiea** [puppeteer/puppeteer#1693]
I want to provide Chrome instance with `prefs`/`localState`. Using *ChromeDriver*'s `chromeOptions` (https://sites.google.com/a/chromium.org/chromedriver/capabilities) I could set something like this:
```js
prefs: {
    download: {
        prompt_for_download: false,
        default_directory: DOWNLOAD_PATH,
    }
},
localState: {
    browser: {
        "enabled_labs_experiments": [
            // All preferences can be found here: https://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/pref_names.cc?view=markup
            "enable-native-notifications@2",
        ],
    }
},
```
Is it possible to do the same with *puppeteer*? (I saw the workaround for setting download dir through `_client`, but the question is more general)

Here is related issue: https://github.com/GoogleChrome/puppeteer/issues/1577

**Comment by aslushnikov** [comment]
No, there's no such API for now, mostly because there's not much demand for it.
For the preferences, you can write prefs to the `userDataDir` by yourself similarly to how chromedriver does this. And setting downloads directory is not exposed since we're baking a proper support for downloads.

Out of curiosity, what's your usecase for this?

**Comment by skyiea** [comment]
@aslushnikov Yeah, I thought about starting messing with `userDataDir` directly, though I'm not sure if Chromium will dynamically sync prefs from the `userDataDir` if I will modify the latter. I assume _ChromeDriver_ constructs `userDataDir` before opening the instance. And I don't want to keep persistent `userDataDir`. So do you think something like this will work?
```js
await browser.launch();
await driver.browser.setPrefs({ ... }); // messing with /userDataDir via `fs`
// will browser automatically apply new prefs here? I guess not :\
```

ATM I have 2 use-cases, which I'm covering with `prefs` & `localState` when I use _Protractor_ / _Gemini_ / _Selenium_:
1. Downloads:
- default path
- disable prompt
2. Disable native OSX notifications (shipped in Chrome starting from v59), and use Chromium ones.

So I see _prefs_ / _localState_ as addition to _args_, which gives me more control over the functionality.
Here is complete list of what can be used: https://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/pref_names.cc?view=markup

**Comment by aslushnikov** [comment]
> So do you think something like this will work?

@skyiea no, this won't work: the prefs should be written before the browser is launched.

> So I see prefs / localState as addition to args, which gives me more control over the functionality.

This probably deserves a PR: you should be able to pass prefs as an argument to the `puppeteer.launch` option. Under the hood, the `puppeteer.launch` creates a temporary userDataDir. It can as well fill it with preferences.

Are you interested in working on this?

**Comment by skyiea** [comment]
@aslushnikov Yeah, will look into this next week.

**Comment by berstend** [comment]
@skyiea Did you manage to get `localState` settings working? It seems like the "local state" file has been deprecated in favor of the Preferences file but adding a `browser.enabled_labs_experiments` object to it doesn't do anything for me.

PS: I've made [this wrapper](https://github.com/berstend/puppeteer-extra) to set instance prefs as your PR won't be merged into puppeteer.

**Comment by skyiea** [comment]
@berstend As far as I recall I managed to shift `localState` by modifying `/Profile X/Local State` file (there was some cryptic notation, which I understood by analyzing existing props in `localState` file). I guess you are right, about the deprecation. In the recent Chrome version I can't find the file anymore.

PS: thanks for popping out extras, looks promising! I guess it resolves this feature request, and we can close it now.
