### ISSUE TITLE
Allow Chromium extension url pages and webviews to be recognized as regular pages

### ISSUE THREAD

**Issue by gpetrov** [puppeteer/puppeteer#1695]
Currently if you open pages with urls like:  chrome-extension://fjjllfpmlaejicjkpknbdicd...
Those get:

```
_targetInfo:
   { targetId: '(769AF8566CD3629647D0BC2EFBD10E1)',
     type: 'app',
```

so the type is **app** and target.page() doesn't work to obtain the target page, due to this check:

```javascript
if (this._targetInfo.type === 'page' && !this._pagePromise) {
```
at https://github.com/GoogleChrome/puppeteer/blob/master/lib/Browser.js#L194

The same is also valid for pages within a webview
```
 _targetInfo:
   { targetId: '(28682BC78076959FC22B67763A8251DD)',
     type: 'webview',
```

so the check should be changed to 
```javascript
if ((this._targetInfo.type === 'page' || this._targetInfo.type === 'app' || this._targetInfo.type === 'webview') && !this._pagePromise) {
```

**Comment by aslushnikov** [comment]
We're conservative in exposing target types since not all parts of API might work with certain types.

For the webview case, do you connect puppeteer to the chromium on android?

**Comment by gpetrov** [comment]
@aslushnikov  I'm trying to use Puppeteer with https://nwjs.io/ it will be really useful there for automated UI testing.
It works all really great with the changes above! 

The other thing that was missing the Page.getFrameTree and Page.setLifecycleEventsEnabled as described in https://github.com/GoogleChrome/puppeteer/issues/1681

But this was just because NWjs was one build behind and it will soon be at the latest Chrome 64 as it gets released.

You might want to add a simple check if Page.getFrameTree and Page.setLifecycleEventsEnabled are available before usage so it runs fine on Chrome 63 as well ...

**Comment by aslushnikov** [comment]
@gpetrov I'll close this for now since it doesn't look like there's a lot of interest from the community.

Feel free to send us a PR for this if/when you have time.

**Comment by GEMI** [comment]
Could you please fix this?
