### ISSUE TITLE
[Question] How to know that browser is opened with Puppeteer

### ISSUE THREAD

**Issue by skyiea** [puppeteer/puppeteer#1697]
Is there a way to know (from page's JS) that the browser is running with Puppeteer? I saw the tip to check for `headless` string in `userAgent`, but I'm running with `headless: false` (testing extension).
I'd like to switch some features if the extension is run in tests.

**Comment by yujiosaka** [comment]
@skyiea 
How about setting a user agent like 'puppeteer', so that you know from `window.navigator.userAgent` ?

**Comment by skyiea** [comment]
@yujiosaka It works. Though I would thought it shouldn't, because I'm testing chrome extension, which has `background.js`, which executes immediately on extension (browser) start (before I could change `userAgent`). But surprisingly it came out that `page.setUserAgent` is executed _before_ `background.js`.
The matter is closed. Thanks.

**Comment by skyiea** [comment]
I was wrong.
`background.js` is opened with default `userAgent`. After `page.setUserAgent` it seems to reload the page, that's why I've thought everything is cool.

**Comment by ebidel** [comment]
Extensions run in an isolated world from the page, but that's interesting that the UA isn't preserved when the background page fires up.
 
Maybe you could inject a variable (`window.PUPPETEER = true`) into the page and have your background page read it?

**Comment by skyiea** [comment]
@ebidel Extension _content scripts_ run in isolated scope from the web-page, not background/options/browser-action-popup. Anyway, don't think there is anything to do with isolated scope.

Setting global variable won't help, because:
1. Browser gets opened with an extension within (loaded through `--load-extension` arg).
2. Extension's `background.js` is executed. _<- here I need to know whether it is Puppeteer-driven Chrome_
3. Puppeteer runs: `newPage -> goto background url -> page.evaluate window.PUPPETEER = true`, but it is too late.

Why `setUserAgent` didn't work:
1, 2 - same as above
3. Puppeteer runs: `newPage -> goto background url -> page.setUserAgent`.
4. `background.js` gets reloaded(?) with new `userAgent`, and executed (with Puppeteer-driven context, but only from the second try)

**Comment by aslushnikov** [comment]
@skyiea you can launch chrome with a custom user agent:

```js
const puppeteer = require('puppeteer');

(async() => {

  const browser = await puppeteer.launch({
    args: ['--user-agent=hhh'],
  });
  const page = await browser.newPage();
  console.log(await page.evaluate(() => navigator.userAgent));
  await browser.close();
})();
```

Hope this helps

**Comment by ebidel** [comment]
@skyiea the UA isn't what you've set b/c the background page isn't fired up by your Puppeteer script. It's fired up by Chrome. Passing `--user-agent` in `puppeteer.launch()` is the best way to provide a custom UA and have it remain over the lifetime of the browser.

Alternatively, if you wanted to preserve the browser's UA string, you can get tricky:

1. create a blank page in Puppeteer
2. set its title to a custom name
3. detect the tab update in your background script. 

The downside is that this approach requires the `"tabs"` permission in manifest.json.

**puppeteer_script.js**:

```js
const puppeteer = require('puppeteer');

const CRX_PATH = '/path/to/crx/folder/';

puppeteer.launch({
  headless: false,
  args: [
    `--disable-extensions-except=${CRX_PATH}`,
    `--load-extension=${CRX_PATH}`,
  ]
}).then(async browser => {
  const page = await browser.newPage();
  await page.evaluate("document.title = 'PuppeteerAgent'");
  ...
});
```

Extension **background.js**:

```js
let LAUNCHED_BY_PUPPETEER = false;

chrome.tabs.onUpdated.addListener((tabId, info, tab) => {
  if (!LAUNCHED_BY_PUPPETEER && tab.title.includes('PuppeteerAgent')) {
    chrome.tabs.remove(tabId);
    LAUNCHED_BY_PUPPETEER = true; // rest of background script can use this var.
  }
});
```
  
  
 **Update**: posted this on SO: https://stackoverflow.com/questions/48089670/detect-and-test-chrome-extension-using-puppeteer

**Comment by skyiea** [comment]
@ebidel I'm content with `--user-agent` _arg_.
Thank you both.

**Comment by skyiea** [comment]
Setting user agent via `--user-agent` arg forces me to hard-code one. Is it possible to know it beforehand somehow? Don't want to update it manually each time I download new Chromium version. :/

**Comment by ebidel** [comment]
```js
async function getPuppeteerChromeUA() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const ua = await page.evaluate('navigator.userAgent');
  await browser.close();
  return ua;
}
```

**Comment by aslushnikov** [comment]
there's also `browser.userAgent()` method

```js
async function getPuppeteerChromeUA() {
  const browser = await puppeteer.launch();
  const ua = await browser.userAgent();
  await browser.close();
  return ua;
}
```
