### ISSUE TITLE
Needs to be republished to npm.

### ISSUE THREAD

**Issue by patrickeakin** [puppeteer/puppeteer#1698]
Looks like the code published to npm is 2 months old. I'd like to get the latest `xpath` goodness into my project via yarn. Is there a release scheduled soon?

**Comment by marco-pragliola** [comment]
Just specify the latest version explicitly.

Il 31 dic 2017 4:45 AM, "Patrick Eakin" <notifications@github.com> ha
scritto:

**Comment by marco-pragliola** [comment]
Just specify the latest version explicitly.

`npm i puppeteer@1.0.0-rc`

(Example with `npm`, just do the equivalent for `yarn`)

**Comment by patrickeakin** [comment]
Thanks @marco-pragliola

**Comment by ebidel** [comment]
I suspect we'll probably do a release early next year after the holidays. Until then you can pull from master.
