### ISSUE TITLE
Error: kill ESRCH on puppeteer.launch({}) on CircleCI

### ISSUE THREAD

**Issue by theoutlander** [puppeteer/puppeteer#1700]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Ubuntu on CircleCI
* Node.js version: 8.9.1

**What steps will reproduce the problem?**
Not sure how to repro this. Maybe try launching puppeteer on CircleCI via npm test? This works fine locally on OSX.

It fails on the following call: 
```  const browser = await puppeteer.launch({})```

**What is the expected result?**
Puppeteer launch call is successful

**What happens instead?**
```
[1] Setup Puppeteer Environment.
[1] Error: kill ESRCH
[1]     at Object._errnoException (util.js:1024:11)
[1]     at process.kill (internal/process.js:183:18)
[1]     at forceKillChrome (/home/circleci/repo/node_modules/puppeteer/lib/Launcher.js:162:19)
[1]     at killChrome (/home/circleci/repo/node_modules/puppeteer/lib/Launcher.js:147:9)
[1]     at Function.launch (/home/circleci/repo/node_modules/puppeteer/lib/Launcher.js:137:7)
[1]     at <anonymous>
[1]     at process._tickCallback (internal/process/next_tick.js:188:7)
[1] jest --config ./src/jest.config.js exited with code 1
```

**Comment by JoelEinbinder** [comment]
Looks like the chrome process is failing to launch. Can you try some of the workarounds posted in https://github.com/GoogleChrome/puppeteer/issues/290?

**Comment by theoutlander** [comment]
Thanks @JoelEinbinder. I'll look into the workaround this week.

**Comment by aslushnikov** [comment]
We use a bunch of things to run on travis:
- launching with --no-sandbox
- additionally installing `libnss3`: [.travis.yml](https://github.com/GoogleChrome/puppeteer/blob/master/.travis.yml)

But this looks more like a CircleCI environment issue. We don't use CircleCI for pptr tests and don't have much experience with it, their bugtracker should be a better place for the question. Please don't hesitate to open new issues here if you think we can help somehow.

**Comment by theoutlander** [comment]
Thanks @aslushnikov. Since you stated it was a CircleCI env issue, I dug deeper and realized that I was using a docker build for node that circle provided. Upon further investigation, I discovered that they have a browser build type called circleci/node:8.9.1-stretch-browsers. I tried that and it worked! Here are some details off their dockerhub page:

<img width="743" alt="screenshot 2018-01-03 20 04 48" src="https://user-images.githubusercontent.com/749084/34549957-b7cdc78a-f0c1-11e7-9ad2-c150afe1b92e.png">

**Comment by TrySound** [comment]
@theoutlander Still no luck. Which configuration do you use for puppeteer itself?
https://github.com/bvaughn/react-virtualized/pull/928

**Comment by theoutlander** [comment]
@TrySound here is my circle config: https://circleci.com/gh/theoutlander/testerbot/45#config/containers/0

You might be able to find more details from my project source @ https://github.com/theoutlander/testerbot/tree/master/src

I just noticed I passed in additional params as I was fiddling to solve this issue, so not sure if that worked in combination with the docker build.

    const browser = await puppeteer.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    })

**Comment by TrySound** [comment]
@theoutlander Awesome! It finally works. Thank you.

**Comment by EJTH** [comment]
Hi! Here is how I got it running under WSL:

install chromium browser through apt-get 

`$ sudo apt-get install chromium-browser`

then:

`const browser = await puppeteer.launch({executablePath:'/usr/bin/chromium-browser'});`
