### ISSUE TITLE
host-rules ignored

### ISSUE THREAD

**Issue by stephanreiter** [puppeteer/puppeteer#1701]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Debian Stretch 9.2
* Node.js version: 8.9.3

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');
async function run() {
  a = [
    "--host-rules='MAP * 127.0.0.1'",
    '--no-sandbox',
  ];
  const browser = await puppeteer.launch({args: a});
  const page = await browser.newPage();
  await page.goto('http://www.example.org');
  console.log(await page.content());
  browser.close();
}
run();
```

**What is the expected result?**
I expected 127.0.0.1 to be contacted for the web page and then an HTTP 404 error (I am not running a web server on localhost).

**What happens instead?**
Retrieves the web page from www.example.org and prints HTML on the console.

**Comment by JoelEinbinder** [comment]
Remove the quotes:
```js
  a = [
    "--host-rules=MAP * 127.0.0.1",
    '--no-sandbox',
  ];
```

**Comment by stephanreiter** [comment]
Doesn't work.

chrome process arguments are obviously wrong with this, i.e. ..... --hide-scrollbars --mute-audio --host-rules=MAP * 127.0.0.1 --no-sandbox  => "--host-rules=MAP" "*" "127.0.0.1" are three separate argvs.

**Comment by stephanreiter** [comment]
Nevermind that comment of mine about the process args. I used "ps aux | grep chrom" to check that and there's no way to tell from it whether there are three separate value or just one value passed to the executable.

Nevertheless, chrome contacts the host 93.184.216.34 instead of 127.0.0.1 (checked with tcpdump).

**Comment by JoelEinbinder** [comment]
Ah, I was running `headless: false` to see what is going on. The combination of both removing the quotes and headful mode made it work for me. But there also seems to be some caching going on so I'm not 100% sure.

**Comment by JoelEinbinder** [comment]
Looks like the `--host-rules` flag is not used by Chrome headless. Compare:

`chrome.exe --host-rules='MAP * 127.0.0.1' https://example.com`
and
`chrome.exe --host-rules='MAP * 127.0.0.1' --dump-dom --headless https://example.com`

**Comment by stephanreiter** [comment]
Thanks for your work to find out what's going on, Joel!!
I guess I should take this to the chromium developers. "--enable-quic" is another argument that is ignored in headless mode, and there's a defect about that registered already: https://bugs.chromium.org/p/chromium/issues/detail?id=739162

**Comment by stephanreiter** [comment]
Filed it here: https://bugs.chromium.org/p/chromium/issues/detail?id=798793&q=component%3AInternals%3EHeadless
