### ISSUE TITLE
.waitForFunction() should return a value

### ISSUE THREAD

**Issue by marco-pragliola** [puppeteer/puppeteer#1703]
It seems that as for now, `.waitForFunction()` just checks for the truthiness of the returned value in the frame context, which is then discarded. It is impossible to implement any functionality that waits for the function's Promise actually returning a value and using that value in the Node context.

One possible scenario would be using `.waitForFunction` to wait for a specific `<option>` tag with a specific _label_ and returning instead its _value_. 

I could simulate it with `.evaluate()` but I would lose the polling/timeout configuration options.

**Version:** `1.0.0-rc`
**Platform:** `Linux`
**NodeJS:**: `v9.x`

**Comment by marco-pragliola** [comment]
Btw, I implemented a sort of workaround by juggling with a `document._puppeteer` object in the page context in which I store a value, which is read _again_ with `page.evaluate()` and performes tasks from the node contexts based on the value.
 
But it is very ugly.

**Comment by yujiosaka** [comment]
> One possible scenario would be using .waitForFunction to wait for a specific <option> tag with a specific label and returning instead its value.

I don't know if it's what you exactly want, but it seems to me `page.waitForSelector` works perfectly fine for your case.
It should be something like this:

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.setContent(`
    <select class="gender">
      <option label="Male">Male</option>
      <option label="Female">Female</option>
      <option label="Other">Other</option>
    </select>
  `);
  await page.waitForSelector('.gender > [label=Male]');
  const element = await page.$('.gender > [label=Male]');
  const text = await (await element.getProperty('textContent')).jsonValue();
  console.log(text);
  await page.close();
  await browser.close();
});
```

**Comment by marco-pragliola** [comment]
@yujiosaka but your `label` attribute makes no sense, it should be `value`, with label I am referring to the `innerHTML` of the `option`. Which is impossible to check via selectors.

Practical example: a page is loaded with a `select` tag. The dropdown is filled via AJAX with some `option` tags like:

```
<option value="45">Foo</option>
<option value="66">Bar</option>
```

I have to intercept the option whose `innerHTML` is `Foo` and retrieve its value (`45`).
I'd expect to do something like:

```
const retrievedValue = await page.waitForFunction((arg1, arg2, ...) => {
     // fancy stuff here
     return value;
}, options, arg1, arg2, ...);
```

This would be super because I can pass arguments and specify polling type and timeout. But I have to do some serious hacks to retrieve that value.

This is only a particular case, anyway.

**Comment by yujiosaka** [comment]
@marco-pragliola 

gotcha! you are right!

`document.querySelector(page.$)` does not support `:contains` query which jQuery has, so my suggestion does not work.
my apologies.

however, i don't know if it's the right API design to return JSHandle or serializable by `page.waitForFunction()`.
it sounds a bit weird behavior to me considering the method name.

Another solution I came up with is to implement `waitForXpath` method, which goes like this:

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.setContent(`
    <select class="gender">
      <option value="0">Male</option>
      <option value="1">Female</option>
      <option value="2">Other</option>
    </select>
  `);
  await page.waitForXpath('//option[contains(text(), 'Male']');
  const element = await page.xpath('//option[contains(text(), 'Male']');
  const text = await (await element.getProperty('textContent')).jsonValue();
  console.log(text);
  await page.close();
  await browser.close();
});
```

Let's see what the chrome team says.

**Comment by marco-pragliola** [comment]
@yujiosaka Actually, `.waitForXPath` was the thing I was missing at the beginning. Then, trying some hacks and workarounds, I came up with this question. But yes, it could solve some scenarios.

It is very common to do tests or scraping based on the presence of some inner HTML and not a tag, class or id by itself.

**Comment by mrenzidev** [comment]
Im also struggling with waitForFunction.
I have an external variable evaluated when an ajax call return a variable, lets say 
`let ajaxTest = false;`

It is then evaluated to true when a get that particular ajax response

```
await page.on('response', async res => {
....
....
ajaxTest = true;
});
```

Then i'm using waitForfunction to test if it is set to true
```
await page.waitForFunction((args) => {

        try {
            console.log(args);


        } catch (e) {
            console.log(e.message);
        }
       
        console.log(args);
        return false;
    }, {},ajaxTest );
```
**I get always false**

But if i'm using something like
```
await page.waitFor(2000); 
console.log(ajaxTest) 
```
i can see **it became true;**

It is like inside waitForfunction the variable is not passed by reference.
Is that possible?

Thanks in advance

**Comment by cloydlau** [comment]
Struggling with waitForFunction too.
Yes the arguments is not passed by reference, only serializable arguments is accepable. 
Arguments which is not serializable like functions should be converted to string and recreated inside waitForFunction's callback.
Sounds complicated hah, yeah...
And returns of waitForFunction can be acquired in this ugly way:
```js
// example for boolean type

const res = await page.waitForFunction(() => {
  return result.toString()
})

console.log({
  'false': false,
  'true': true
}[res._remoteObject.value])
```
Very restricted too, not work with object type.
