### ISSUE TITLE
[Feature Request] Return All Nodes from XPath

### ISSUE THREAD

**Issue by alixaxel** [puppeteer/puppeteer#1705]
Right now, the [current `page.xpath()` implementation](https://github.com/GoogleChrome/puppeteer/blob/60ba8c3af9f18dbceb0ce93815d378bb423b658a/lib/ElementHandle.js#L204) only returns the first matched element.

I find this implementation somewhat restrictive, specially considering it's tied to `ElementHandle`.

For instance, if we wish to find all `ANY_*` XPath result type constants on the [MDN website](https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate):

```
id("wikiArticle")/table[@class="standard-table"]//td[1]/code[starts-with(., 'ANY_')]
```

The above XPath would do the job, but with the current implementation we are forced to either traverse the DOM using good old `page.evaluate()` or known how many elements would be matched beforehand and issue _n_ separate XPath queries in the form of `(expression)[1..n]`. Or just run XPath in `page.evaluate`:

```
await page.evaluate(() => {
  function $x(expression) {
    let result = [];
    let element = null;
    let elements = document.evaluate(expression, document, null, XPathResult.ANY_TYPE, null);

    while ((element = elements.iterateNext()) !== null) {
      result.push(element);
    }

    return result;
  }

  return $x('id("wikiArticle")/table[@class="standard-table"]//td[1]/code[starts-with(., "ANY_")]').map(
    (element) => {
      return element.textContent;
    }
  );
});

// ["ANY_TYPE", "ANY_UNORDERED_NODE_TYPE"]
```

It would be great to have more capable XPath querying abilities before PPTR 1.0.0 is released.

**Comment by aslushnikov** [comment]
@JoelEinbinder how about returning array of all matched elements from `page.xpath`?

**Comment by yujiosaka** [comment]
**FYI**

selenium-webdriver has both `getAttributeByXpath` and `getAttributesByXpath`.
the former returns a single element and the latter returns all.
