### ISSUE TITLE
Needs more information for `browser.version()`

### ISSUE THREAD

**Issue by yujiosaka** [puppeteer/puppeteer#1706]
According to Chrome DevTool protocol, [Browser.getVersion](https://chromedevtools.github.io/devtools-protocol/tot/Browser/) returns not only `product` but also other properties such as `userAgent`.

In my environment, the raw API returns the following object:

```
{ protocolVersion: '1.2',
  product: 'HeadlessChrome/64.0.3264.0',
  revision: '@7f3cdc3f76faecc6425814688e3b2b71bf1630a4',
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/64.0.3264.0 Safari/537.36',
  jsVersion: '6.4.265' }
```

However, the current `browser.version()` returns only `product` property. The code is [here](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Browser.js#L135).

I believe it's useful to return other properties. In my case, I need `userAgent` before actually requesting.

For me, another solution is to add a method like `browser.userAgent()`. But I feel listing all properties of `Browser.getVersion` is more useful and consistent to Chrome DevTool Protocol.

Actually the [API doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserversion) already says this:

```
**NOTE** the format of browser.version() might change with future releases of Chromium.
```

I can make a small PR if you want.

**Comment by aslushnikov** [comment]
> I believe it's useful to return other properties.

@yujiosaka We can expose them one-by-one as the need arises; I doubt anyone would ever need `jsVersion`.

> In my case, I need userAgent before actually requesting.

Actually, you can get one right now with `page.evaluate`:
```js
const ua = await page.evaluate(() => window.navigator.userAgent);
```

> For me, another solution is to add a method like browser.userAgent(). But I feel listing all properties of Browser.getVersion is more useful and consistent to Chrome DevTool Protocol.

I like the `browser.userAgent()` method since it exposes only the necessary things.
I'll be happy to review a PR!
