### ISSUE TITLE
waitForFunction should accept and ElementHandle in page function arguments

### ISSUE THREAD

**Issue by ivanvanderbyl** [puppeteer/puppeteer#1724]
Currently `waitForFunction` only accepts JSON serializable primitives as arguments to the page function. It would be very useful to be able to support ElementHandles as arguments.

Use case: I have an ElementHandle from `page.$()`, and I then want to wait for a specific state change on that element, such as becoming visible, or an attribute changing value, perhaps `disabled` which can only be implemented on the page.

It could be used like this:

```js
let element = await page.$('button')

await page.waitForFunction((element) => !element.hasAttribute('disabled'), {polling, timeout}, element)
```

Obviously, there's the question of whether this is actually possible with the DevTools protocol and the serialization of arguments in the specific case of the wait function. I know it's possible with `evaluate()`

**Other things to consider:**

- The element would have to be from the same execution context as `waitForFunction()` is called,
- The element handle could be disposed of before the waiter returns,
- The element could be removed from the DOM, which would need to be handled in the page function, possible by calling it with a `null` element.

**Comment by aslushnikov** [comment]
@ivanvanderbyl you're right on time: we've had a PR to address this that just got merged.
