### ISSUE TITLE
It's benefit to support ElementHandle.waitForSelector method

### ISSUE THREAD

**Issue by rustkt** [puppeteer/puppeteer#1726]
In browser, we can use querySelector method like this:

```javascript
const div = document.querySelector('div');  // lookup "div" globally
const span = div.querySelector('span');  // lookup "span" locally, that is bounded to div's scope
```

It's helpful to provide waitForSelector method on ElementHandle, thus we can wait for selector locally that is bounded to the ElementHandle instance.

**Comment by JoelEinbinder** [comment]
With 05b1aca21e5c2f221373d601d3b8ae6b2a984292 you should be able to do something like this.

Warning, untested code ahead:
```js
function waitForScopedSelector(selector, scopeElement) {
    return page.waitForFunction((selector, scopeElement) => scopeElement.querySelector(selector), {}, selector, scopeElement);
}
```

**Comment by rustkt** [comment]
Thanks for reply! Is that an efficient way to do that? I will try it, and hope puppeteer could offer a native method in the future.

**Comment by JoelEinbinder** [comment]
It's roughly identical to how the regular `waitForSelector` is implemented.

**Comment by aslushnikov** [comment]
We currently keep all out waitFor* funcitons on the page object only; I'd like to keep it as this for consistency.

Closing this for now; we might revisit this if there's a demand.

**Comment by tanvee38** [comment]
Great work by JoelEinbinder and aslushnikov. Eagerly waiting to see the ```waitFor*``` functions support to wait for ```elementHandle``` in the next Puppeteer release.

**Comment by raphaeloliveira-hotmart** [comment]
A use case would be querying a page's iframe.

I can `page.waitForSelector('iframe.myIframe')` but then all next queries I'd like to be inside that iframe. So I did try 

```
const iframe = page.waitForSelector('iframe.myIframe')
const iframeForm = iframe.waitForSelector('form.someForm')
```
Then I can test my form in my iframe with `iframeForm.$()` and typing on the fields, and then after submitting the form, `iframeForm.waitForSelector('div.someSucessMessageClass')`, considering the form submit is a XHR, so doesn't fit `page.waitForNavigation`.

**Comment by RaphaelDDL** [comment]
A use case would be querying a page's iframe.

I can `page.waitForSelector('iframe.myIframe')` but then all next queries I'd like to be inside that iframe. So I did try 

```
const iframe = page.waitForSelector('iframe.myIframe')
const iframeForm = iframe.waitForSelector('form.someForm')
```

but didn't work, which is how I found this issue.

If that worked, then I could test my form in my iframe with `iframeForm.$()` and typing on the fields, and then after clicking on the submit button, `iframeForm.waitForSelector('div.someSucessMessageClass')`, considering the form submit is a XHR, so doesn't fit `page.waitForNavigation` and I need to wait for the success div to show up after the XHR.

Right now I don't know how I would wait for the form XHR other than some `page.waitFor(SomeRandomMsNumberThatWillBeTooMuchOrNotCoverAllCases)`

--

Edit: 

So, while not exactly the same thing, in my iframe use case, while would be nice to have the form saved to be queried inside/waitedFor, I managed to do in another approach. Luckily my iframe had only one form.

```
        const pageframe = await page.waitForSelector('iframe.myIframe');
        const iframe = await pageframe.contentFrame()
```
And the `contentFrame` returns a `Frame` class which also have some methods like `page`, so I could have it scoped to the iframe contents only and having access to `iframe.$()`, `iframe.waitForSelector('selector')` and other useful things like type and click.

And having waitForSelector on the Frame, I could wait for the xhr form submit and confirm the success message showed. So, wasn't as specific as doing stuff based off the iframe's form, but was an ok approach.

**Comment by kevin940726** [comment]
I know this is an old issue, which is why I think this needs to be revisited.

> ```js
> function waitForScopedSelector(selector, scopeElement) {
>     return page.waitForFunction((selector, scopeElement) => scopeElement.querySelector(selector), {}, selector, scopeElement);
> }
> ```

This workaround will only work if we're using CSS selectors. But now that we have `aria` selector and also provide users to register their own query handler, the solution becomes outdated.

Playwright has support for this, and I think it's only natural for us to also support this as well.
