### ISSUE TITLE
page.goto returns a promise to null when intercepting request and modifying referer together

### ISSUE THREAD

**Issue by yujiosaka** [puppeteer/puppeteer#1729]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0 (but also occurs at puppeteer@next )
* Platform / OS version: Mac OS
* URLs (if applicable): *
* Node.js version: 8.9.1

**What steps will reproduce the problem?**

1. It works
```js
const URL = 'http://example.com/';
const REFERER = 'http://example.net/';
(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    // await page.setRequestInterception(true);
    // page.on('request', interceptedRequest => {
    //  interceptedRequest.continue();
    // });
    await page.setExtraHTTPHeaders({ 'referer': REFERER });
    const response = await page.goto(URL);
    try {
      const text = await response.text();
      console.log(text); // goes here
    } catch(error) {
      console.error(error);
    }
    await page.screenshot({path: 'example.png'});
    await page.close();
    await browser.close();
})();
```

2. It works
```js
const URL = 'http://example.com/';
const REFERER = 'http://example.net/';
(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    page.on('request', interceptedRequest => {
     interceptedRequest.continue();
    });
    // await page.setExtraHTTPHeaders({ 'referer': REFERER });
    const response = await page.goto(URL);
    try {
      const text = await response.text();
      console.log(text); // goes here
    } catch(error) {
      console.error(error);
    }
    await page.screenshot({path: 'example.png'});
    await page.close();
    await browser.close();
})();
```

3. but it catches the error
```js
const URL = 'http://example.com/';
const REFERER = 'http://example.net/';
(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    page.on('request', interceptedRequest => {
     interceptedRequest.continue();
    });
    await page.setExtraHTTPHeaders({ 'referer': REFERER });
    const response = await page.goto(URL);
    try {
      const text = await response.text();
      console.log(text);
    } catch(error) {
      console.error(error); // goes here
    }
    await page.screenshot({path: 'example.png'});
    await page.close();
    await browser.close();
})();
```

The most strange thing is that if I modify other headers than referer, it works.

4. it works
```js
await page.setExtraHTTPHeaders({ 'otherthanreferrer': REFERER });
```

Either way, the screenshots are taken ok, so it's not like failing to navigating to the next page.

**What is the expected result?**

`page.goto()` always returns a promise to response

**What happens instead?**

`page.goto()` returns a promise to `null`

```
TypeError: Cannot read property 'text' of null
```

**Comment by yujiosaka** [comment]
The response is `null` because the results of `generateRequestHash` are different between `_onRequestIntercepted` and `_onRequestWillBeSent`.

I put the console here:
```js
  _onRequestIntercepted(event) {
    console.log('_onRequestIntercepted', event.request.headers);
    if (event.authChallenge) {
    ...
  _onRequestWillBeSent(event) {
    console.log('_onRequestWillBeSent', event.request.headers);
    if (this._protocolRequestInterceptionEnabled) {
    ...
```
The output here:
```
_onRequestIntercepted { 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/64.0.3264.0 Safari/537.36',
  'X-DevTools-Emulate-Network-Conditions-Client-Id': '(4829DA1AE4FB5A21A90595F4FFA55DED)',
  referer: 'http://example.net/',
  'Upgrade-Insecure-Requests': '1',
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' }
_onRequestWillBeSent { 'Upgrade-Insecure-Requests': '1',
  Referer: 'http://example.net/',
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/64.0.3264.0 Safari/537.36' }
```

You see the capitalization of `referer` is different.

First I thought that was because I modify `referer` in my code.
However, switching my code to `Referer` does not make any change.

As you can see [here](https://github.com/GoogleChrome/puppeteer/blob/master/lib/NetworkManager.js#L575), `generateRequestHash` only considers `Referer` but not `referer`.
That eventually causes the problem that `page.goto` does not returns a promise to response.

I believe this behavior should be filed to chromium, but also it's safe to patch `generateRequestHash` to consider not-capitalized `referer` header also because headers should be case-insensitive.

**Comment by yujiosaka** [comment]
Reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=799556)

**Comment by koloritcm** [comment]
Do you think this fix will solve these issues perhaps:

https://github.com/GoogleChrome/puppeteer/issues/1391
https://github.com/GoogleChrome/puppeteer/issues/631

Both of them same symptom and seems related to `setRequestInterception`

**Comment by yujiosaka** [comment]
@gunnarblom 
Thanks for letting me know! It seems #631 has been solved, though it was not by me :)
