### ISSUE TITLE
Commit #1712 breaks my scripts with 'UnhandledPromiseRejectionWarning'

### ISSUE THREAD

**Issue by patrickeakin** [puppeteer/puppeteer#1737]
Currently I'm running my scripts on the latest master. Since https://github.com/GoogleChrome/puppeteer/pull/1712 was merged I get an "Unhandled Promise Rejection Warning" in my terminal and my scripts stop at this point. If i use the sha just before this commit all is well.

I'm a bit of novice when it comes to some things so forgive me if I'm missing something here.

```
(node:78444) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Runtime.callFunctionOn): Object couldn't be returned by value undefined
(node:78444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by JoelEinbinder** [comment]
Interesting. I imagine https://github.com/GoogleChrome/puppeteer/pull/1712/files#diff-16f3b9739b97830927de83812ac92d78R718 is throwing. I'll need to rethink how to implement that. Thanks for the report.

**Comment by aslushnikov** [comment]
@patrickeakin could you please check if the fix works for you?

**Comment by patrickeakin** [comment]
@aslushnikov @JoelEinbinder That did the trick. Thanks a ton!!

**Comment by jfrazzano** [comment]
Sorry if this is obvious q, but saw code that ran ‘new Function(args, ...funcbody)’... is this code being run in a node environment? My understanding was that node did not yet support the function constructor/prototype function.  

What run environments support new F for puppeteer?

**Comment by JoelEinbinder** [comment]
Good question. That code runs inside Chromium.
