### ISSUE TITLE
TypeSupported gived FALSE in puppeteer, true in chrome

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#1742]
Trying to run HLS.js in puppeteer:  Cannot because that test return false

`window.MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E,mp4a.40.2"')`

whereas in chrome gives true

Any idea ?

**Comment by ebidel** [comment]
They just added mp3/mp4 support to chromium but the apt feature detects
won't work until m65:
https://bugs.chromium.org/p/chromium/issues/detail?id=746579#c20

**Comment by qinyang912** [comment]
still won't work
