### ISSUE TITLE
'request' event never called on Chrome, works fine in chromium ?

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#1743]
This works fine for chromium: 

```
await page.setRequestInterception(true);
page.on('request', request => {
        console.log('request', request);
        request.continue();
        return;
}
```

But is never called when I do use Chrome instead 
puppeteer.launch({executablePath: "C:\\Users\\...

**Comment by JoelEinbinder** [comment]
What version of Chrome are you using? Puppeteer only supports the version it is bundled with. You could try Chrome canary for possibly better results.

**Comment by aslushnikov** [comment]
@yarekc it looks like chrome is too old. Either try using a newer version of chromium or an older version of puppeteer.
