### ISSUE TITLE
Can I use Junit/testNG with puppeteer

### ISSUE THREAD

**Issue by saritanzu** [puppeteer/puppeteer#1744]
We are considering using puppeteer as our main automation framework, does it support Junit/testNG? or anything similar?

**Comment by JoelEinbinder** [comment]
Puppeteer is a Node library, so you can use [Jasmine](https://jasmine.github.io/) or [Mocha](https://mochajs.org/).

**Comment by aslushnikov** [comment]
@saritanzu as Joel mentioned, pptr is a node library, not an automation framework. You can couple it with any test automation solution as you wish. Jasmine and Mocha are some of the options, but there are [dozens of them](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#JavaScript).
