### ISSUE TITLE
page -> frame1 -> frame2

### ISSUE THREAD

**Issue by StefanRoess** [puppeteer/puppeteer#1749]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v0.13.0
* Platform / OS version: Windows 10 Home
* URLs (if applicable):
* Node.js version:  node --version

**What steps will reproduce the problem?**
Is there a way to select a button in a Sub-Frame. I have a page, with a click at a button a new frame (modal window) will open. On this new modal window is a Delete Button. Via Puppeteer this Delete Button will be clicked and a new popup frame will open. Now I want to click the "ok" button via Puppeteer. But this last step don't work.  

Code snippet
    /* Navigation */
    const inputElement = await page.$('li#t_TreeNav_1');
    await inputElement.click();
    await page.waitForNavigation({waitUntil: 'networkidle2'});

    await page.click('tr:last-child > td > a[href^="javascript:apex.navigation.dialog"]');

    const frame = await page.frames()[1];
  
  // may be there must also be a networkidle2 for a frame
    const delete_button = await frame.$('#DELETE_BUTTON');
    await delete_button.click();
  
    // here we have a new popup window
    // how can i identify the id=button#apexConfirmBtn
    // it is not in "frame" but how can i identify the new popup window
    const ok_button = await frame.$('button#apexConfirmBtn');
    await ok_button.click();

    console.log("End of File");

**What is the expected result?**
The "Ok" button should be clicked, but puppeeter do not find the button-id.
The call is from page -> frame -> to a new frame

**What happens instead?**
Program hangs on line "const ok_button = await frame.$('button#apexConfirmBtn');"

**Comment by JoelEinbinder** [comment]
You can use https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-targetcreated to respond to pages being created. Use [`target.page()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-target).

**Comment by StefanRoess** [comment]
Hi Joel,
if i use for example 

    browser.on('targetcreated', async (target) => {
      console.log(`Created target type ${target.type()}`);
    });

I get this result: Created target type page url about:blank

When i use the following:
   frame.on('targetcreated', async (target) => {
      console.log(`Created target type ${target.type()}`);
    });
I get: TypeError: frame.on is not a function

Again, i have a button in a frame with a click at this button a popup window appears and in this new popup window there is again a button, which i want to identify and click.

Any futher code examples.

**Comment by aslushnikov** [comment]
There's been quite some discussion on handling pop-ups on the bugtracker; for example, please take a look at https://github.com/GoogleChrome/puppeteer/issues/1264
