### ISSUE TITLE
Allow functions registered via page.exposeFunction to receive JSHandles

### ISSUE THREAD

**Issue by rjktcby** [puppeteer/puppeteer#1750]
When traversing DOM tree to find elements for testing UI in order to better share code i try to register a bunch of helper functions via **page.exposeFunction**. Currently this api does not allow to pass JSHandles between these functions (or any other non-serializable object), which is a tough limitation. 

A small sample to reproduce what I'm trying to achieve:
```
const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.exposeFunction('arrayLength', (array) => { return array.length; });
await page.goto('https://google.com');
await new Promise(res => setTimeout(res, 1000));
const numberOfDivs = await page.evaluate(
    async(selector) => await window.arrayLength(
        Array.from(document.querySelectorAll(selector))),
    'div');
console.log('number of divs:', numberOfDivs);
await browser.close();
```

It fails on some web pages (like google.com) and works on others (like example.com), what depends on whether there are circular references in DOM tree or not, which seems like not good behavior at all.

**Comment by aslushnikov** [comment]
@rjktcby indeed, the `page.exposeFunction` is not integrated with JSHandles at the moment since there's been no need.

Do you really need the capability? In your example, it's not necessary to use the `page.exposeFunction` method; a better approach would be using [`page.evaluateOnNewDocument`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluateonnewdocumentpagefunction-args).

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();

// This will be evaluated as the page loads
await page.evaluateOnNewDocument(() => {
  // Define the window.arrayLength method
  window.arrayLength = array => array.length;
});
await page.goto('https://google.com');
// FYI: you can use `page.waitFor` with number as an argument to sleep to the given interval
await page.waitFor(1000);
const numberOfDivs = await page.evaluate(selector => {
  return window.arrayLength(Array.from(document.querySelectorAll(selector)));
}, 'div');
console.log('number of divs:', numberOfDivs);
await browser.close();
```

**Comment by rjktcby** [comment]
@aslushnikov my example is indeed trivial, i need this feature for more complex stuff. I'm writing UI testing and want to end up with generic reusable code to find elements in DOM tree by some euristics. 

For example, lets say I want to find a button with text 'Submit' in one of its childs, or an element which looks like a certain reference png image that I have. Or whatever condition that I cannot think of right now but will become necessary in future. My intent is to develop code base of helper functions and not care a lot about what kind of objects they can or can't receive as arguments. Some of them need to be executed inside browser page context - it would be handy to just expose them once and call whenever I need it. 

Here are some examples of such functions (these are used to traverse DOM tree and find elments by custom euristics):

```javascript
// finds distance to first traversed element that satisfies custom predicate
function distanceTo(element, predicate, traverser) {
    if (predicate(element)) {
    return 0;
    }
    traversedDistance = traverser(element, predicate);
    return traversedDistance != null ? traversedDistance + 1 : null;
}

// finds distance to first child that satisfies custom predicate
function distanceToChild(element, predicate) {
    return distanceTo(element, predicate, (element) => {
    const childDistances = Array.from(element.children)
                                .map(el => distanceToChild(el, predicate))
                                .filter(el => el != null);
    return childDistances.length > 0 ?
        Math.min.apply(null, childDistances) :
        null;
    });
}

// finds distance to first parent that satisfies custom predicate
function distanceToParent(element, predicate) {
    return distanceTo(element, predicate, (element) => {
    return element.parentElement != null ?
        distanceToParent(element.parentElement, predicate) :
        null;
    });
}
```

I want to be able to call them on different elements (usually queried by selector) and filter results as I need in each individual case. If I could pass JSHandles between exposed functions - I could just expose all the code I need and perform simple high-level evaluates for each case. Code would be readable and easy to understand.

As there is no such opportunity right now, I had to come up with a single generic and very complicated **page.evaluate** call, that takes a JSON of parameters on how to find elements, and also a function (which I had no option but to stringify and destringify back inside **page.evaluate**) that represents action to be taken if some element is found.

It looks like this:
```javascript
async function findElement(page, options, action) {
  console.debug(
     'Looking for element with options:', options, ' action:', action);

  return await page.evaluate(function(options, actionString) {
    /* 
     * All the helper functions and element finding logic defined here,
     * so that I can pass JSHandles between them
     * It results in lots of inlined code here (inside this evaluate)
     * that only gets bigger as I continue to develop it
     */

    if (element == null) {
      console.log(
          'could not find element with options:', JSON.stringify(options));
    }
    console.debug('element:', element);
    console.debug('actionString:', actionString);

    // ugly way to call custom function over found element
    return Function('return ' + actionString)()(element);
  }, options, action.toString());
}
```

It prevents code duplication, but this monstrous **page.evaluate** will sooner or later become impossible to maintain.

P.S.
I'm new to both Javascript and puppeteer and if there is a clean and simple way to achieve what I need that I'm missing - would be grateful for any advice.

**Comment by aslushnikov** [comment]
> As there is no such opportunity right now..

@rjktcby I think this is achievable, please point me to where I'm wrong.

>  My intent is to develop code base of helper functions and not care a lot about what kind of objects they can or can't receive as arguments. Some of them need to be executed inside browser page context - it would be handy to just expose them once and call whenever I need it.

You can define a set of helper functions in page context with a simple `page.evaluate`:

```js
await page.evaluate(() => {
    window.niceUtils = {
        // finds distance to first traversed element that satisfies custom predicate
        distanceTo: function(element, predicate, traverser) {
            if (predicate(element)) {
            return 0;
            }
            traversedDistance = traverser(element, predicate);
            return traversedDistance != null ? traversedDistance + 1 : null;
        },

        // finds distance to first child that satisfies custom predicate
        distanceToChild: function (element, predicate) {
            return distanceTo(element, predicate, (element) => {
            const childDistances = Array.from(element.children)
                                        .map(el => distanceToChild(el, predicate))
                                        .filter(el => el != null);
            return childDistances.length > 0 ?
                Math.min.apply(null, childDistances) :
                null;
            });
        },

        // finds distance to first parent that satisfies custom predicate
        distanceToParent: function(element, predicate) {
            return distanceTo(element, predicate, (element) => {
            return element.parentElement != null ?
                distanceToParent(element.parentElement, predicate) :
                null;
            });
        }
    };
});
```

> I want to be able to call them on different elements (usually queried by selector) and filter results as I need in each individual case. 

You can call these functions like this:

```js
page.$eval('.my-selector', (element, predicate) => niceUtils.distanceToChild(element, new Function(predicate)), predicate);
```

What's wrong with this approach?

**Comment by rjktcby** [comment]
Seems like in the early days of getting to know puppeteer i tried this way and also failed. Not so sure at the moment, will double check and update, thanks

**Comment by rjktcby** [comment]
@aslushnikov just tried proposed approach and seems to be working fine, thanks a lot for that. Closing the issue.

**Comment by ThaneshR** [comment]
@aslushnikov I spent quite a bit of time wondering why functions defined outside of page.evaluate can't be reference within it. Maybe I should have read the docs.

The approached you mentioned here (use page.evaluate to set the helper functions) is great. I think it should be part of the docs,

**Comment by trusktr** [comment]
I'm new here, but seems like it'd be neat to pass references between both sides. This would allow, for example, people to come up with alternatives to `Electron`, for example starting by doing `page.exposeFunction('require', ...)`.
