### ISSUE TITLE
Blank screenshot with headless true, else fine.

### ISSUE THREAD

**Issue by grantstephens** [puppeteer/puppeteer#1755]
* Puppeteer version: 0.1.13
* Platform / OS version: Ubuntu 17.04
* URLs (if applicable): http://eu.patagonia.com/gb/en/home/
* Node.js version: 9.2.0

When running the following:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: true});
  const page = await browser.newPage();
  let source = await page.goto('http://eu.patagonia.com/gb/en/home/');
  await page.screenshot({path: 'example.png', fullPage: false});
  await browser.close();
})();

```
The resulting screenshot is blank, however by setting headless to false the screenshot works perfectly.
I don't know if it is a site specific thing but I haven't seen it on any other site, but AFAIK it shouldn't make a difference if headless if true or false.

**Comment by eliseumds** [comment]
Same here v1.1.0, even with `headless: false`.

It's still a bit mysterious, but I was having this issue when taking screenshots of massively long pages (in height) and concatenating them at the end. It apparently came back to normal after I set the max height to 5000px, but I'm definitely not confident with that.

**Comment by ebidel** [comment]
Something is up with the site. I'm not able to `curl -v http://eu.patagonia.com/gb/en/home/` and get a response.

**Comment by grantstephens** [comment]
@ebidel That is weird- somehow it loads find in a normal browser window.

**Comment by aslushnikov** [comment]
Looks like website is detecting headless browser and decides not to respond. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by digitalhank** [comment]
@aslushnikov Any solution for this? Having similar issue with 1.5.0. Works perfect when headless is set to false but when it's true i receive an error:

**Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>**

The website is locally served. Curl works fine.

**Comment by aha7** [comment]
i always get blank screenshot if isMobile is true. i have tried all possible values of waitUntil page.goto(url, {waitUntil: ''} but it did not help. only option worked for me is sloMo.
puppeteer.launch({"slowMo" : 500});  but the value of slowMo is not predictable. sometime/some site will give non black screenshot even it is 250. 

is there any proper fix for it? 

i use puppeteer@1.8.0

**Comment by aslushnikov** [comment]
@aha7 can you please file a separate issue with reproducible script?

**Comment by iNeoO** [comment]
Up, did anyone find a solution ? (same pb with an other site using spip)

Edit: found a solution
```
      await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3738.0 Safari/537.36');
```
resolve pb

https://github.com/GoogleChrome/puppeteer/issues/665

**Comment by ashwinsingh2007** [comment]
> Up, did anyone find a solution ? (same pb with an other site using spip)
> 
> Edit: found a solution
> 
> ```
>       await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3738.0 Safari/537.36');
> ```
> 
> resolve pb
> 
> #665

Saved my day
