### ISSUE TITLE
page.evalute() does not work as described

### ISSUE THREAD

**Issue by MadHatter122312** [puppeteer/puppeteer#1756]
* Puppeteer version:
0.13.0
* Platform / OS version:
Sierra 10.12.6
* URLs (if applicable):
* Node.js version:
v8.9.0

I am trying to create reference to a DOM element with page.evalute() like so:

```
    const myElement = (await page.evaluate( () => {
        let overflowDiv = document.querySelectorAll('.overflow')[0];
        let buttonDiv = overflowDiv.children[1];
        let listsButton = buttonDiv.children[0]; 
        return listsButton;   
    }))();

    await page.click(myElement);
```

However, I get a TypeError that myElement is not a function.  According to the documentation it is supposed to resolve a promise.  What am I dong wrong?

**Comment by aslushnikov** [comment]
@IgorDraskovic there are two issues I can see with the code:
- you have excessive function call - you should just invoke `page.evaluate` and that's it
- once you have a handle, you should use `ElementHandle.click` to click

The following snippet should work just fine:

```js
    const myElement = await page.evaluate(() => {
        let overflowDiv = document.querySelectorAll('.overflow')[0];
        let buttonDiv = overflowDiv.children[1];
        let listsButton = buttonDiv.children[0]; 
        return listsButton;   
    });
    await myElement.click();
```

**Comment by MadHatter122312** [comment]
@aslushnikov 

It does not work.  Error is `Cannot read property 'click' of undefined` .  myElement is undefined.

**Comment by aslushnikov** [comment]
@IgorDraskovic ah sorry, you should use `page.evaluateHandle` instead of `page.evaluate`.

```js
    const myElement = await page.evaluateHandle(() => {
        let overflowDiv = document.querySelectorAll('.overflow')[0];
        let buttonDiv = overflowDiv.children[1];
        let listsButton = buttonDiv.children[0]; 
        return listsButton;   
    });
    await myElement.click();
```

**Comment by MadHatter122312** [comment]
This fixed the problem!  Thank you.

**Comment by proton1k** [comment]
@aslushnikov would you also consider using the `evaluateHandle` to imitate mouse scroll inside a div with fixed size ? I am trying to use it to set the `offsetTop` value, but does not work so far. I've tried also as described [here](https://github.com/GoogleChrome/puppeteer/issues/438#issuecomment-340675046) with `page.$`, but again does not work.

**Comment by mdrazahassan** [comment]
@aslushnikov  I am using puppeteer to take a screenshot. To load the required page however, a context needs to be set in the localStorage (of the browser page). I am not able to achieve that as of now. Any help would be highly appreciated!

**Comment by aslushnikov** [comment]
@mdrazahassan plz file a separate issue.
