### ISSUE TITLE
moar xpath!

### ISSUE THREAD

**Issue by fringd** [puppeteer/puppeteer#1757]
I love the addition of $x to query for xpath easily. In my code I've also added a waitForXpath function that roughly mirrors the waitForSelector method.

here's the snippet:
```
export const waitForXpath = async (context, xpath) => {
  const inputGetter = function (path) {
    return document.evaluate(path, document, null, XPathResult.ANY_TYPE, null).iterateNext();
  };
  const jsHandle = await context.waitForFunction(inputGetter, { polling: 50 }, xpath);
  return jsHandle.asElement();
};
```

this is much a bit simpler than the full waitForSelector, but a start.

I'd like to not have to write this function myself!

Any chance we could get a waitForXpath added to puppeteer? and maybe even detect xpath strings so I can just write `page.waitFor("//p[normalize-space(.)='hello world']")`

**Comment by aslushnikov** [comment]
@fringd thanks for reaching out! I don't see any problems with the suggested functionality; feel free to implement all the things you've mentioned here and send us PRs!

**Comment by fringd** [comment]
sure thing expect a pull request soon.

**Comment by fringd** [comment]
okay I added https://github.com/GoogleChrome/puppeteer/pull/1767 but i wasn't able to add you as a reviewer, maybe you can add yourself?

**Comment by fringd** [comment]
@aslushnikov  ^
