### ISSUE TITLE
[Feature request] Launching the browser in 'Full screen' mode

### ISSUE THREAD

**Issue by DoronBrayer** [puppeteer/puppeteer#1762]
* Puppeteer v0.13.0
* Windows 10 64-bit
* URL n/a
* Node.js v8.9.4

Please add the ability to launch the browser in 'Full screen' mode.

Thanks

**Comment by ebidel** [comment]
There's a Chrome flag for fullscreen:

```js
const browser = await puppeteer.launch({
  headless: false,
  args: ['--start-fullscreen']
});
```

full list: https://peter.sh/experiments/chromium-command-line-switches/

**Comment by DoronBrayer** [comment]
@ebidel Thanks.

**Comment by seyfer** [comment]
@ebidel that will maximize the screen, but not the viewport.
For setting the viewport
```
    await page.setViewport({width: 1920, height: 1080});
```

**Comment by Alhamou** [comment]
@ebidel Thanks.

i do also more like this:

` obj.setViewport = await obj.page.setViewport({"width": 0,"height": 0})`
