### ISSUE TITLE
Feature Request: Cannot Resize non-headless Chrome.

### ISSUE THREAD

**Issue by jGeorge437** [puppeteer/puppeteer#1764]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.6.0
* Platform / OS version: Windows 10
* Node.js version: v8.9.3
* Chrome version: {Beta} 64.0.3282.71

**What steps will reproduce the problem?**

Setting viewport for page only resizes that page within the chrome tab, but not the chrome window itself (which is intended)

Though according to the documentation.. 
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md
There doesn't appear to be any means to resize the chrome browser window on creation or while running.

#

**Comment by JoelEinbinder** [comment]
You can try using the command line flag: https://peter.sh/experiments/chromium-command-line-switches/#window-size

**Comment by jGeorge437** [comment]
That did the trick! I should've scrolled down further, thank you!
