### ISSUE TITLE
Removing infobars not working in Chromium or Chrome v64

### ISSUE THREAD

**Issue by jGeorge437** [puppeteer/puppeteer#1765]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.6.0
* Platform / OS version: Windows 10
* Node.js version: v8.9.3
* Chrome version: {Beta} 64.0.3282.71

**What steps will reproduce the problem?**

```
puppeteer.launch(options = {
     args: ['--disable-infobars']
});
// ^ Not working.
```

Setting viewport for page only resizes that page within the chrome tab, but not the chrome window itself (which is intended)

Though according to the documentation.. 
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md
^ Look at puppeteer launch options
^ notice the args section
^ takes you to --> https://peter.sh/experiments/chromium-command-line-switches/ 

which lists the argument as listed in the code above, yet is not working.

**Comment by ebidel** [comment]
This disables infobars for me on Mac. Launches the built in Chromium with 0.13.0:

```js
const browser = await puppeteer.launch({
      headless: false,
      args: ['--disable-infobars']
    });
```

5.6.0 isn't a release version of Puppeteer.

**Comment by JoelEinbinder** [comment]
This flag was removed in https://crrev.com/528386

**Comment by jGeorge437** [comment]
Turns out I had puppeteer's options separate from its launch declaration, which is why it wasn't caught.

also, you're right about the versioning. that was my npm. Rather embarrassing ^.^

**Comment by jacobjithin** [comment]
Is there way to disable the info-bars now since the command "--disable-infobars" has been removed. I Need to disable the info bar when Chrome is launched using selenium

**Comment by jeffhall-wk** [comment]
I have the same question as @jacobjithin

**Comment by suever** [comment]
Apparently it was [added back](https://bugs.chromium.org/p/chromium/issues/detail?id=820453#c6). In initial testing, I've also been able to get rid of the message by removing the `--enable-automation` option from puppeteer's default args.

**Comment by hemanth7787** [comment]
Is there anyway  to disable ?  it looks pretty ugly in --kiosk mode.

**Comment by ebidel** [comment]
This works for me on mac and removes the infobars:

```js
const browser = await puppeteer.launch({
  headless: false,
  args: [
    '--disable-infobars',
  ],
});
```

No need to remove `--enable-automation` either.

**Comment by derappelt** [comment]
It's not working again...

**Comment by flotwig** [comment]
@derappelt Chrome removed --disable-infobars in M76: https://support.google.com/chrome/a/answer/7679408?hl=en

**Comment by antonioiliev** [comment]
Hi all,
[--disable-infobars] is definitely not working in Version 77.0.3835.0 and later.
Did anyone come up with an alternative to this issue?

**Comment by jacobjithin** [comment]
@antonioiliev 
Here is the solution in C# to disable infobars
options.AddExcludedArgument("enable-automation");
options.AddAdditionalCapability("useAutomationExtension", false);

However after you add the above two lines , the "save password " prompt comes up.
So you can add the below lines to disable the save password "options.AddUserProfilePreference("credentials_enable_service", false);"

**Comment by Lugribossk** [comment]
Adding `ignoreDefaultArgs: ["--enable-automation"]` to the options in `puppeteer.launch({...})` will remove the "Chrome is being controlled by automated test software" infobar.

**Comment by antonioiliev** [comment]
Hi @jacobjithin 
Thank you for the reply. However,  I am using Puppeteer with Node.js

@Lugribossk - your solution works.

**Comment by debaosuidecl** [comment]
@Lugribossk 
You the man..
it works

**Comment by d4niloArantes** [comment]
Solution for ChromeDriver tested with Selenium WebDriver 
https://help.applitools.com/hc/en-us/articles/360007189411--Chrome-is-being-controlled-by-automated-test-software-notification

**Comment by moltar** [comment]
Disabling `--enable-automation` has too many other [side effects](https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#--enable-automation).

E.g. now there is "default browser" bar.

I think there needs to be a better solution for this.

**Comment by qo4on** [comment]
Have anybody managed to get rid of "default browser" bar which appears after disabling `--enable-automation`?

**Comment by yuzararyadi** [comment]
> Adding `ignoreDefaultArgs: ["--enable-automation"]` to the options in `puppeteer.launch({...})` will remove the "Chrome is being controlled by automated test software" infobar.

works for me, thanks @Lugribossk

**Comment by rinogo** [comment]
> Adding `ignoreDefaultArgs: ["--enable-automation"]` to the options in `puppeteer.launch({...})` will remove the "Chrome is being controlled by automated test software" infobar.

Seems to work in Playwright, too. Thanks!

**Comment by skygate2012** [comment]
For those who encounters into an extra infobars, just add `'--enable-blink-features=IdleDetection'` to `ignoreDefaultArgs`
