### ISSUE TITLE
Headless mode is not working

### ISSUE THREAD

**Issue by sepiropht** [puppeteer/puppeteer#1766]
Hello guy puppetter is awesome! However i have one small issue with one site where i cannot launch the browser in headless mode. I have to turn it to 'false' and then it work properly.
In headless a got this error:

(node:13169) UnhandledPromiseRejectionWarning: Error: waiting failed: timeout 30000ms exce
╰─➤                                                                                                                  1 ↵ │eded
                                                                                                                         │    at Timeout.WaitTask._timeoutTimer.setTimeout (/home/sepiropht/src/challenge/node_modul
                                                                                                                         │es/puppeteer/lib/FrameManager.js:593:58)
                                                                                                                         │    at ontimeout (timers.js:466:11)
                                                                                                                         │    at tryOnTimeout (timers.js:304:5)
                                                                                                                         │    at Timer.listOnTimeout (timers.js:264:5)
                                                                                                                         │(node:13169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error ori
                                                                                                                         │ginated either by throwing inside of an async function without a catch block, or by reject
                                                                                                                         │ing a promise which was not handled with .catch(). (rejection id: 1)
                                                                                                                         │(node:13169) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In
                                                                                                                         │ the future, promise rejections that are not handled will terminate the Node.js process wi
                                                                                                                         │th a non-zero exit code.

node version: 9.3.0
OS: ubuntu 16.04
puppetter version: 0.13.0
[Here](https://github.com/sepiropht/Frontend-Master-Downloader) the script
thanks!

**Comment by Nantris** [comment]
Having the same issue, No matter the timeout, headless mode fails. Page loads when set to false.

**Comment by trading-peter** [comment]
I had the same issue. I then added `await page.screenshot(...)` to see what's going on in headless mode. Turns out the page loaded a mobile version of the website and therefore my `page.waitForSelector` did time out because the selector was meant for the desktop version.

I resolved this by setting a desktop user agent with `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');`

Maybe that helps?

**Comment by sepiropht** [comment]
Ok thanks it work. Good to know that sometimes we get the mobile version by default.

**Comment by Nantris** [comment]
I am still forced to conclude headless mode is not working properly. I have tried the following code with 5 sites, probably more than a hundred times. I have succeeded in loading a page exactly once. On the other hand, I've had problems with `headless: false` exactly zero times.

```
browser = await puppeteer.launch({
  headless: true,
  slowMo: 200,
});
page = await browser.newPage();

await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');
await page.setViewport({width:960,height:768});

await page.goto('https://google.com/', {timeout: 40000, waitUntil: 'domcontentloaded'});

//  EXECUTION HAS ONLY MADE IT THIS FAR ONCE IN ~100 TIMES

await page.screenshot({ fullPage: true, path: 'screenshot.png' })

await page.addStyleTag({
    content: '.modal-backdrop.fade.in {display: none !important;} #disclaimer {display: none !important;} .modal-open {overflow: scroll !important;}'
})

await page.addScriptTag({
    url: 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js'
})

```

**Comment by ebidel** [comment]
@Slapbox That works for me without issue. Another thing you could also try is to race between the load event and dcl:

```js
page.goto('https://google.com/'); // async
  // wait for either of events to trigger
  await Promise.race([
    page.waitForNavigation({waitUntil: 'domcontentloaded'}),
    page.waitForNavigation({waitUntil: 'load'})
  ]);
```

Note there's no `await` before `page.goto`

**Comment by Nantris** [comment]
@ebidel thanks very much for your help! I will see if any of these changes make the difference.

**Comment by Nantris** [comment]
I tried these ideas as well as increasing my timeout to 75 seconds, and trying to add the `--deterministic-fetch` flag as mentioned in #1718. I strongly suspect the issue I'm experiencing has to do with extremely slow page loading not seen when running with `headless: false`

I was able to get Google.com to work, though even by the time it takes the screenshot around 40 seconds into load it's hardly loaded.

For any page that dynamically loads content after the initial DOM load, I can't get a populated page even at 75 seconds.

I tried a few pages and came up with these rough numbers:

**headless: true**
Average load time (including content loaded after DOM load): ~10 seconds

**headless: false**
Average load time (including content loaded after DOM load): ~240 seconds

Do you have any ideas on why this might be the case?

I'm using version `1.0.0` on Windows 7 x64.

Thanks very much for reading and for your great work!

**Comment by jyjohnson** [comment]
Having similar issues on Win 10 x64. No matter what I try, Chromium is launched in GUI mode, and I get this error:

(node:9120) UnhandledPromiseRejectionWarning: Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r526987
    at Timeout.onTimeout (C:\Users\xxxx\node_modules\puppeteer\lib\Launcher.js:237:14)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
(node:9120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bluermind** [comment]
Same for me here cannot load this site - https://coinmarketcap.com/
in headless mode. Works fine on headless false.

Edit: found a site that works --> https://purecss.io/

**Comment by Nantris** [comment]
@jyjohnson does running `npm install` (I think it is) help?

**Comment by jyjohnson** [comment]
npm install and then what?

I did try this on a fresh Windows 2016 Server and it worked correctly. When I installed puppeteer, the server did not have Chrome installed. After verifying puppeteer worked, I installed Chrome. Still everything works.

So it must be something related to Win 10 and/or just my machine (?)...I tried uninstalling Node from my machine, re-installing, etc. but still get same error....

**Comment by bluermind** [comment]
@Slapbox I can see that headless mode takes way longer to emulate chromium when you have a lot of requests mades to resources like images and scripts. Aborting requests that are not necessary like ads can reduce some time. It appears that it does load the site if you wait hell of  long time.

**Comment by Nantris** [comment]
@jyjohnson I used `Yarn` to install `Puppeteer`. Afterwards I believe I ran just `npm install` in the folder and it installed the associated version of Chromium automatically. I could be mistaken.

@bluermind this is my conclusion as well, although even 5 minutes is not long enough to consistently load sites that load in 4 seconds with `headless: false`

**Comment by Aankhen** [comment]
I’m also having trouble getting remote pages to load on Windows 7 x64. In headless mode they time out, whereas if I disable headless mode they load slowly. Local pages (`file:///` paths) load instantly as expected. In an Ubuntu VM run using Vagrant, the script doesn’t time out but it does work a little slowly. (Both are on Node v8.9.2.)

This may not be an issue with Puppeteer. I got the same timeouts with Chromy.

EDIT:
I upgraded to Windows 10 x64 in the interim and had no issues whatsoever with Puppeteer.

**Comment by bluermind** [comment]
@Slapbox So if you must be authenticated and perform a series of page navigating to get to a page and emulate interactions (eg. POST, PUT), unfortunately using puppeteer with headless false seems to be the best option. Otherwise if you know the link that lands on the page that you exactly want and you want to retireve some data from that page, i think using http-request to retrieve the html and parsing it accordingly will be the most optimal way.

**Comment by UltraDosaaf** [comment]
I have almost the same problem. Time between `chrome.launch()` and `page.goto(http://localhost:4000/)` callback:
1. `headless = false` -> 1.533s 
2. `headless = true` -> 21.242s 

Same results on Win 7 x64 and Win 10 x64 (different PCs, i7-7820 without any load and ~12-20GB of free ram)

**Comment by Nantris** [comment]
The issue with headless load time seems to be more or less resolved with `1.1.0`, at least in my case. I am now using headless without issue. There may be delays, but no where near the magnitude of what @UltraDosaaf is experiencing, although I had even worse load times than those with `1.0.0`

**Comment by taewookim** [comment]
@pkaske That worked. Awesome!

**Comment by sizzlorox** [comment]
@bluermind Thank you! None of the fixes above worked for me but changing the goto link from localhost directly to the login redirect link worked for me.

**Comment by avmgan** [comment]
For me worked this code with the latest version, the important window size for a headless mode.
```
public void GoTest()
        {
            ChromeOptions options = new ChromeOptions();
            options.AddArgument("--window-size=1920,1080");
            options.AddArgument("--disable-gpu");
            options.AddArgument("--disable-extensions");
            options.AddArgument("--proxy-server='direct://'");
            options.AddArgument("--proxy-bypass-list=*");
            options.AddArgument("--start-maximized");
            options.AddArgument("--headless");
            options.AddArgument("no-sandbox");

            var _driver = new ChromeDriver(options);
            _driver.Navigate().GoToUrl("https://www.google.com");
            object html = _driver.ExecuteScript("return document.body.parentElement.outerHTML");

            _driver.Close();
        }
```

**Comment by HengzheLi** [comment]
> I had the same issue. I then added `await page.screenshot(...)` to see what's going on in headless mode. Turns out the page loaded a mobile version of the website and therefore my `page.waitForSelector` did time out because the selector was meant for the desktop version.
> 
> I resolved this by setting a desktop user agent with `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');`
> 
> Maybe that helps?

Saved my life!!

**Comment by muratgu** [comment]
In my case, I found that if I set the userDataDir property to cache browser files in headless mode, it fails to launch and gets stuck at the launch call.

**Comment by anton-marchenko** [comment]
**Be careful with host address!**

I tried [that](https://github.com/puppeteer/puppeteer/issues/1766#issuecomment-357426931) and as result setUserAgent and setViewport did not help for me :=(

I used linuxmint-19.3-cinnamon-64bit.
I discovered that in my case the problem was in the host name.
When I started to use `http://localhost:3000` instead of `localhost:3000` it **became to work** totally fine!
Now I use this code:

`
const browser = await puppeteer.launch({headless: true});
page = await browser.newPage();
await page.goto('http://localhost:3000')
`
And it works.

Headless mode=true: 5.1sec
Headless mode=false: 10.7sec

**Comment by davizp** [comment]
I had this same issue and @ebidel  comments works for me. I found other solution by updating the puppeteer to a new version.

Ref: https://github.com/puppeteer/puppeteer/issues/1766#issuecomment-357544291

**Comment by HenrryEsposito** [comment]
> I had the same issue. I then added `await page.screenshot(...)` to see what's going on in headless mode. Turns out the page loaded a mobile version of the website and therefore my `page.waitForSelector` did time out because the selector was meant for the desktop version.
> 
> I resolved this by setting a desktop user agent with `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');`
> 
> Maybe that helps?

In case that someone steps on the same problem that I just got...
Puppetter in headless mode cause google to think that I was browsing whit a incompatible browser, on the console i was not getting any errors, my script runs just fine, but without returning the data that I was expecting to scrap from specific .divs on the search page. When using the page.screenshot() the image show up a google page whit the message "Oops! Your browse is not compatible, access google".
I'v tried a couple of diferent things but only got this fixed with trading-peter answer `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');`

**Comment by lucasmoreiradev** [comment]
> I had the same issue. I then added `await page.screenshot(...)` to see what's going on in headless mode. Turns out the page loaded a mobile version of the website and therefore my `page.waitForSelector` did time out because the selector was meant for the desktop version.
> 
> I resolved this by setting a desktop user agent with `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');`
> 
> Maybe that helps?

It worked for me. :+1:

**Comment by alex-drocks** [comment]
> --window-size=1920,1080

![image](https://user-images.githubusercontent.com/69808183/164912999-8f19808b-c693-423b-9f05-4ceb47a60de1.png)

For me, adding a window-size argument to the browser args was the only working answer. thanks @avmgan

**Comment by ItsKodas** [comment]
> For me, adding a window-size argument to the browser args was the only working answer.

I had to scroll a long bloody way to find a solution that helped my scenario!
Cheers 👍

**Comment by max-programming** [comment]
> In my case, I found that if I set the userDataDir property to cache browser files in headless mode, it fails to launch and gets stuck at the launch call.

I was still stuck to this. And remove `userDataDir` does finally something but it does not do what the **headfull** mode did

**Comment by NAIJULU** [comment]
For me, I change the headless parameter by `new`

`const browser = await puppeteer.launch({headless: 'new'});`

**Comment by OfficialDeepSaha** [comment]
> npm install and then what?
> 
> I did try this on a fresh Windows 2016 Server and it worked correctly. When I installed puppeteer, the server did not have Chrome installed. After verifying puppeteer worked, I installed Chrome. Still everything works.
> 
> So it must be something related to Win 10 and/or just my machine (?)...I tried uninstalling Node from my machine, re-installing, etc. but still get same error....

Hey where you deployed this puppeteer application , and how you configured this please guide me i tried headless: false to open a browser but its not opened in cloud but its working in the local machine...please help me.

**Comment by chriszrc** [comment]
Updating to "puppeteer": "^23.5.1" fixed it for me on mac os sequoia-
