### ISSUE TITLE
Feature Request: LCOV or Istanbul format code coverage

### ISSUE THREAD

**Issue by shannon** [puppeteer/puppeteer#1768]
It would be nice if the format of the code coverage report returned form the new page.coverage API was in a format that existing tools could use such as nyc.

I came across [v8-to-istanbul](https://github.com/bcoe/v8-to-istanbul) which converts the v8 format to istanbul but the new coverage API isn't returning the raw v8 format so I can't really leverage it.

**Comment by JoelEinbinder** [comment]
Our format is different because we wanted to share the CSS and JavaScript coverage format and because the scripts in Chromium don't necessarily match what is on disk. Converting to the Istanbul format shouldn't be too difficult, but I think it would work better as a separate project instead of coming built into Puppeteer.

**Comment by shannon** [comment]
Thanks @JoelEinbinder, that makes sense. Would it be possible expose the raw v8 result? It looks like there is some missing information in this format. This way any project like you have described would have everything they need.

**Comment by bcoe** [comment]
@shannon @JoelEinbinder I just spent a weekend hacking with some awesome developers at [HackIllinois](https://www.hackillinois.org/). @vkoves and @rjaltman helped pull together a library that outputs puppeteer's test coverage output in a format consumable by Istanbul:

https://github.com/istanbuljs/puppeteer-to-istanbul

this allows you to run a variety of detailed reports against your puppeteer coverage output \o/ 

would you accept an update to the documentation, outlining how to collect HTML coverage, etc., through puppeteer with Istanbul?

**Comment by aslushnikov** [comment]
@bcoe this looks great!

> would you accept an update to the documentation, outlining how to collect HTML coverage, etc., through puppeteer with Istanbul?

It will be very nice to have a reference here:
https://github.com/GoogleChrome/puppeteer/blob/master/examples/README.md

**Comment by bcoe** [comment]
@aslushnikov 👍 I will draft up an example application and update that README.

I think it might also be worth providing a link here:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-coverage
