### ISSUE TITLE
Click fails with "Node is not visible", but it is

### ISSUE THREAD

**Issue by Nantris** [puppeteer/puppeteer#1769]
I'm running puppeteer with `headless: false`

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Windows 7 x64
* URLs (if applicable): https://s3.amazonaws.com/yabapmatt/bottracker/bottracker.html
* Node.js version: 8.9.1

**What steps will reproduce the problem?**

Below is my code. `setTimeout` was an attempt to fix this issue if it was some sort of timing issue, but it has no effect on the outcome.
```
const puppeteer = require('puppeteer');

async function run() {
	const browser = await puppeteer.launch({
		headless: false
	});
	const page = await browser.newPage();
	page.setViewport({width:960,height:768});
	try {
		await page.goto('http://s3.amazonaws.com/yabapmatt/bottracker/bottracker.html', {waitUntil: 'load'});
	}
	catch (error) {
		console.log(error);
		browser.close();
	}

	await page.waitForSelector('#disclaimer', {visible: true})
	.then(() => {
		console.log("Found the button");
		setTimeout(() => {
			page.click('.modal-footer .btn.btn-default')
			.then(() => {
				console.log("Clicked!")
			})
		}, 5000);
	})
}

run();
```

**What is the expected result?** Button is clicked, modal closes

**What happens instead?** `Node is not visible`

Full messages printed to my terminal:

```
Found the button
(node:35320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Node is not visible
(node:35320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Image of button in question: **
![image](https://user-images.githubusercontent.com/6835891/34802653-bb1a2494-f63c-11e7-966f-b6eb00eb1471.png)

Any thoughts? Thanks very much for reading.

**Comment by Yura13** [comment]
I have the same error when trying to click on an element that placed on the bottom of the page:
     await page.click(selector);

Maybe the problem is related to place of the element (if need to scroll the current page to the element).
So it is the critical bug.

Environment:
- Puppeteer version: 1.0.0
- Node.js version: 8.9.4
- Platform / OS version: Windows 8.1 x64

**Comment by hakimmas** [comment]
I have the same error when using :
`page.click('.modal-footer .btn.btn-default')`

But i solve the problem using '#disclaimer > div > div > div.modal-footer > button' as selector.
`page.click('#disclaimer` > div > div > div.modal-footer > `button')`

- Puppeteer version: 1.0.0
- Node.js version : 9.2.0
- Platform/ OS version : Ubuntu 16.04

**Comment by Michaelknigth** [comment]
Medusa
<https://drive.google.com/file/d/1h9JUYUOnXMmXCPyZLZf_hiYIC64YvgKN/view?usp=drivesdk>

https://ashnrich.tumblr.com/post/170235205175

**Comment by Yura13** [comment]
@hakimmas thanks, but your solution not working for me.
I try to click inside svg, but have the same error.

```#id > div > div > div.class > svg > g```

**Comment by hakimmas** [comment]
Sorry i thought you want click on the "I Understand" button... 
So you want to click on what ?

**Comment by ToniDias** [comment]
I have the same problem with rect or circle svg elements.

for more informations:

My HTML code for test:

```
<!DOCTYPE html>
<html>
<body>

<div>
    <svg child_id="svg_test">
        <circle child_id="circle_test" cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red">
        </circle>
        <text child_id="test">
        </text>
    </svg>
</div>

</body>
</html>
```
My puppeteer tries:

- OK page.click('svg');
- **NOK page.click('svg circle');**
- OK page.click('svg text');
- OK page.click('[child_id="svg_test"]');
- **NOK page.click('[child_id="circle_test"]');**
- OK page.click('[child_id="test"]');

I also try await page.waitFor('circle',{visible:true}) before my page.click() but this don't works...

Do you have any ideas for select the circle? Do you know why I can't select the circle with this way? And why text works?

Thanks

**Comment by Yura13** [comment]
There is a problem with clicking on elements inside svg.

I found related issue #1247

**Comment by Yura13** [comment]
#1247

**Comment by yatki** [comment]
* Puppeteer version: 1.2.0
* Platform / OS version: Linux Mint 18 Cinnamon 64-bit
* URLs (if applicable): https://mehmet.yatki.com
* Node.js version: v8.9.4


I'm experiencing the same problem with the code below.

```javascript
import puppeteer from 'puppeteer';

const screenSize = {
  width: 1280,
  height: 768,
};
const puppeteerDefaultOptions = {
  headless: true,
  devtools: false,
  args: [
    `--window-size=${screenSize.width},${screenSize.height}`,
  ],
};

(async () => {
  const browser = await puppeteer.launch(puppeteerDefaultOptions);
  const pages = await browser.pages();
  const page = pages[0];
  await page.setViewport(screenSize);

  await page.goto('https://mehmet.yatki.com', {
    waitUntil: 'networkidle0',
  });
  await page.screenshot({path: 'example.png', fullPage: true});
  await page.evaluate(() => {
    // this code works fine.
    console.log('scrolling', document.body.scrollHeight);
    window.scrollTo(0, document.body.scrollHeight);
    return true;
  });
  await page.evaluate(() => {
    // this code works fine as well.
    const element = document.querySelector('.stack-share-toggle');
    console.log(element);
    // I can click on the button with the following line.
    // element.click(); 
    return true;
  });
  await page.waitForSelector('.stack-share-toggle');
  // await page.waitForSelector('.stack-share-toggle');
  console.log('waited');
  const button = await page.$('.stack-share-toggle');
  console.log('got button', button);
  await button.click();
  console.log('clicked');
  await page.waitForSelector('.expanded');
  await page.waitFor(100);
  await page.screenshot({path: 'example2.png'});
  await page.close();
  return true;
})().catch(err => console.error(err));
```
Weird things which are happening:
- I see my "Expand" button in the screenshot
- I see my "Expand" button in the dev console when i use `evaluate` method.
- Expand button works when i use: 
```javascript
await page.evaluate(() => {
    const element = document.querySelector('.stack-share-toggle');
    console.log(element);
    // element.click();
    return true;
  });
```

But when i use `page.click(selector)` or `page.$(selector).click()` I'm getting the error below:
```
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._assertBoundingBox (/home/...../node_modules/puppeteer/lib/ElementHandle.js:160:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Would be great if anyone could help. 
Cheers.

**Comment by aslushnikov** [comment]
@Yura13 I found your button on a different URL: https://steembottracker.com/. The issue happens because there are many buttons that satisfy the selector you provide. The following works fine for me:

```js
const puppeteer = require('puppeteer');

async function run() {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  page.setViewport({width:960,height:768});
  await page.goto('https://steembottracker.com/', {waitUntil: 'load'});

  await page.waitForSelector('#disclaimer > div > div > div.modal-footer > button', {visible: true})
  console.log("Found the button");
  await page.click('#disclaimer > div > div > div.modal-footer > button')
  console.log('clicked');
}

run();
```

@yatki similarly to the other case here, you have two buttons that match the `.stack-share-toggle` selector. The "expand" button corresponds to the second element matching this selector, so you should either use a better selector, e.g. `body > div > div.main-wrapper > section.hidden-xs.hidden-print > div:nth-child(4) > p > button`.

**Comment by yatki** [comment]
@aslushnikov Well, I can't believe I've missed this for all this time :D Thank you very very much and have a great day.

**Comment by maxthinkthink-tech** [comment]
use hover before click:
  `page.hover('selector');`
this works for me.

**Comment by oshliaer** [comment]
I catch `err.message == 'Node is either not visible or not an HTMLElement' ||
        err.message == 'Node is detached from document'`
```js
function wait(ms) {
  return new Promise(resolve => setTimeout(() => resolve(), ms));
}
```
```js
...
const page = await browser.newPage();

  // await page.setViewport({ width: 1366, height: 768 });

  await page.goto(url, { waitUntil: 'domcontentloaded' });
  await page.addScriptTag({ path: './qsProc.js' });
  let stop = false;
  let counter = 0;
  let attempts = 50;
  while (!stop) {
    try {
      console.log('loop', ++counter);
      await page.waitForSelector('div#result > button.show-more',
 { timeout: 5 * 1000, visible: true });
      await page.hover('#result > button.show-more');
      await page.click('#result > button.show-more');
      // await wait(9 * 100);
    } catch (err) {
      if ((err.message == 'Node is either not visible or not an HTMLElement' ||
        err.message == 'Node is detached from document') && attempts--) {
        await wait(2 * 1000);
      } else {
        stop = true;
      }
      console.log(Error(err), err.message, err.number);
    }
  }
```

**Comment by ratkorle** [comment]
It usually happens when the element is not visible or you need to drag it, sometimes the ads may cause this problem(I kinda solve this by refreshing the page) so we need to handle that problem.

My problem is that if the selector is on side and its not visible, need to drag, my code reads its value but it can't click it.

Here is my code:

> `  await page.waitForSelector(actions.params.selector, {visible: true});`
> `  basicSelectorPath = actions.params.selector;`
> `basicSelector = await page.$$(basicSelectorPath);`

`for (let i = 0; i < basicSelector.length; i++) {
                                let resultObject = [];
                                let clickPath = [];
                                let button1 = basicSelector[i];
                                await page.waitForSelector(basicSelectorPath);
                                button1.hover();
                                button1.click();
                                await page.waitFor(1000);
                                let button1Name = await page.evaluate(buttonName => buttonName.innerText, button1);
                             //   await page.waitForSelector(basicSelectorPath, {visible: true});
                                
                                for (let o = 0; o < otherSelectorsPath.length; o++) {
                                    let otherSelectorText;
                                    let otherSelector = otherSelectorsPath[o];
                                    if (await page.$(otherSelector) === null) { //check if selector exist on the page
                                        otherSelectorText = '';
                                    } else {
                                        otherSelectorText = await page.$eval(otherSelector, text => text.innerText);
                                    }
                                    clickPath.push(button1Name);
                                    resultObject.push(otherSelectorText);
                                }
                                result.push({path: clickPath, results: resultObject});
                            }`

OR CLICK_CLICK _FETCH
`for (let i = 0; i < basicSelector.length; i++) {
                                let resultObject = [];
                                let clickPath = [];
                                try {
                                    const button1 = basicSelector[i];
                                    await page.waitForSelector(basicSelectorPath);
                                    try {
                                        await button1.click();
                                        await page.waitFor(1000);
                                    } catch (e) {
                                        console.log('basicSelector CLICK error', e);
                                    }
                                    const button1Name = await page.evaluate(name => name.innerText, button1);

                                    for (let y = 0; y < secondBasicSelector.length; y++) {
                                        try {
                                            const button2 = secondBasicSelector[y];
                                            try {
                                                button2.click();
                                                await page.waitFor(1000);
                                            } catch (e) {
                                                console.log(e);
                                            }

                                            const button2Name = await page.evaluate(name => name.innerText, button2);
                                            clickPath.push(button1Name, button2Name);
                                            for (let o = 0; o < otherSelectorsPath.length; o++) {
                                                try {
                                                    let otherSelectorText;
                                                    let otherSelector = otherSelectorsPath[o];
                                                    if (await page.$(otherSelector) === null) { //check if selector exist on the page
                                                        otherSelectorText = '';
                                                    } else {
                                                        otherSelectorText = await page.$eval(otherSelector, text => text.innerText);
                                                    }
                                                    resultObject.push(otherSelectorText);
                                                } catch (e) {
                                                    console.log(e);
                                                }
                                            }
                                        } catch (e) {
                                            console.log(e);
                                        }
                                    }

                                    result.push({path: clickPath, results: resultObject});
                                } catch (e) {
                                    console.log(e);
                                }
                            }`

**Comment by alexbartfeld** [comment]
Some times it happens when there is nothing inside the element:
<div id='some-el'></div>

I solved a problem I had with hidden elements by doing this:
<div id='some-el'>What ever text here</div>

**Comment by dlsso** [comment]
For people who are getting this issue but not using an SVG, there is more help in #1805.

I used `page.$eval(selectorStr, elem => elem.click());`

**Comment by Minnu279** [comment]
I got it worked out using I.forceClick(selector);
