### ISSUE TITLE
Click event not firing the second time

### ISSUE THREAD

**Issue by brownbl1** [puppeteer/puppeteer#1771]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Windows 10
* URLs (if applicable): https://teams.microsoft.com, https://login.microsoftonline.com
* Node.js version: v8.9.1

**What steps will reproduce the problem?**

```js
const puppeteer = require('puppeteer')

const sleep = seconds =>
  new Promise(resolve => setTimeout(resolve, (seconds || 1) * 1000))

const run = (async () => {
  const browser = await puppeteer.launch({ headless: false })

  const page = await browser.newPage()
  await page.setViewport({ width: 1024, height: 768 })

  await page.goto('https://teams.microsoft.com', { waitUntil: 'networkidle2' })

  try {
    const btn = await page.$('#idSIButton9')
    const value = await btn.getProperty('innerText')
    console.log('value: ', await value.jsonValue())

    await page.type('input[type=email]', 'your_email@yourcompany.com')
    await btn.click()
    console.log('clicked 1')

    await page.type('input[type=password]', 'password')

    const btn2 = await page.$('#idSIButton9')
    console.log(btn2)

    const value2 = await btn2.getProperty('innerText')
    console.log('value2: ', await value2.jsonValue())

    await btn2.click()
    console.log('clicked 2')
  } catch (error) {
    console.log('error: ', error)
  }

  await browser.close()
  await sleep(5000)
})()
```

Navigating to the first URL redirects to the second, kicking off a typical OAuth flow with a sign in dialog. The script above attempts to first fill the username field, click next, then fill the password field and click sign in. 

Notice that the selector is the same for both the Next button and the Sign In button. That's not a mistake, and Microsoft seems to be using that same id for both `input[type=submit]` elements. Though only one exists on the page at a given time. So far, nothing I have tried has allowed me to get the Sign In button to be clicked, though it works just fine manually. 

I originally assumed I was just doing something wrong, but it's possible there's some sort of edge case here with reusing ids? Maybe Microsoft is doing something unconventional under the hood that is breaking this.

**Comment by aslushnikov** [comment]
Hey @itslittlejohn,

It looks like I can't register on the website to reproduce this.
Can you please try using the puppeteer@next and see if the issue reproduces there as well?
puppeteer@next is a tip-of-tree version of puppeteer, you can install it with

```
npm install --save puppeteer@next
```

Also, since the `page.goto('https://teams.microsoft.com', { waitUntil: 'networkidle2' })` will result in a subsequent javascript redirect, I'd use the `page.waitForSelector` to make sure that page reached the desired state.

On puppeteer@next, the `page.waitForSelector` will return you the elementHandle, so the following
will work:

```js
// Notice: no await 
page.goto('https://teams.microsoft.com', { waitUntil: 'networkidle2' });
const btn = await page.waitForSelector('#idSIButton9');
```

**Comment by brownbl1** [comment]
Thanks for the help, @aslushnikov. I'm using this new (trimmed down) script against `puppeteer@next`.

```js
const puppeteer = require('puppeteer')

const sleep = seconds =>
  new Promise(resolve => setTimeout(resolve, (seconds || 1) * 1000))

const run = (async () => {
  const browser = await puppeteer.launch({ headless: false })
  const page = await browser.newPage()
  page.goto('https://teams.microsoft.com')

  try {
    const btn = await page.waitForSelector('#idSIButton9')

    await page.type(
      'input[type=email]',
      'benbrown@bentleytest.microsoftonline.com'
    )
    await btn.click()

    await page.type('input[type=password]', 'somepassword')

    const btn2 = await page.$('#idSIButton9')
    await btn2.click()
  } catch (error) {
    console.error('error: ', error)
  }

  await sleep(10)
  await browser.close()
})()
```
I'm still having the same issue, but I've cleaned it up a bit to make it more reproducible for others. Instead of testing for login success, let's say we're testing for login failure. It's the same UI click issue. I've filled in a valid username, and a bogus password, and I would expect to see:
![right](https://user-images.githubusercontent.com/2136925/35064190-39ceea7c-fb97-11e7-8835-67e965d428a9.PNG)

But instead I just see:
![wrong](https://user-images.githubusercontent.com/2136925/35064202-4489ea48-fb97-11e7-8ae5-d238e7144e0d.PNG)

In effect, the Sign in button is still not being pressed. I've removed most of the code that I didn't think was having an effect. Any additional help confirming whether this is a bug would be great. And let me know if there's anything else you'd recommend I try as well. 

Thanks!

**Comment by benpolinsky** [comment]
Working with @itslittlejohn on this, and we have an update. We are able to get this 'passing' (able to see the "Your email or password is incorrect..." error in browser)  by calling sleep() before `waitForSelector`:

```js
    const sleep = seconds =>
        new Promise(resolve => setTimeout(resolve, (seconds || 1) * 1000))
    ...
    await sleep(1)
    const btn2 = await page.waitForSelector('input[type=submit]')
```

and also, separately without calling `sleep(1)`, by setting `slowMo: 1` in launch options.

**Comment by aslushnikov** [comment]
@brownbl1 this seems to be working fine for me on pptr 1.4.0:

```js
const puppeteer = require('.');

const sleep = seconds =>
  new Promise(resolve => setTimeout(resolve, (seconds || 1) * 1000))

const run = (async () => {
  const browser = await puppeteer.launch({ headless: false })
  const page = await browser.newPage()
  page.goto('https://teams.microsoft.com')

  try {
    const btn = await page.waitForSelector('#idSIButton9')

    await page.type(
      'input[type=email]',
      'benbrown@bentleytest.microsoftonline.com'
    )
    await btn.click()

    await page.type('input[type=password]', 'somepassword')

    const btn2 = await page.$('#idSIButton9')
    await btn2.click()
  } catch (error) {
    console.error('error: ', error)
  }

  await browser.close()
})()
```
