### ISSUE TITLE
Can't be used on zlinux (s390x)

### ISSUE THREAD

**Issue by hordemark** [puppeteer/puppeteer#1772]
when run npm install command, the puppeteer can be installed. But the chrome in puppeteer/.local-chromium/linux-508693/chrome-linux is not a execute binary file.
Because zlinux cpu architecture is different from x86.

Any suggestions?

Thanks

**Comment by JoelEinbinder** [comment]
It seems like you will have to compile Chromium yourself, or find a compiled version for your platform. Then you can specify a custom chrome path with the `executablePath` option: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions

**Comment by charIeszhao** [comment]
@hordemark Hi, I'm currently facing the same issue. Were you able to compile chromium on s390x? Any existing compiled version you found? Thanks!

**Comment by aaronbrownasp** [comment]
@charIeszhao Hi Charles, like you, I am also facing this issue. Were you able to find any exiting compiled version? Or were you able to compile it yourself? Thanks in advance
