### ISSUE TITLE
Keepalive for the devtools connection

### ISSUE THREAD

**Issue by pwnall** [puppeteer/puppeteer#1774]
I'm using puppeteer.connect to connect to a bunch of Chrome instances across the network. Everything works perfectly, as long as I can keep the instances busy all the time. However, if I have a long initialization phase (think tens of minutes) between connecting to the Chrome instances and issuing commands to them, the connection breaks down.

AFAIK, the WebSockets spec includes a ping mechanism and requires both sides to respond, so most WebSockets stacks have a built-in code for responding. If Chrome has this (let me know if you'd like me to check), it'd be nice if puppeteer's connection would issue keepalive pings at a configurable interval. The configurable aspect can also allow folks to keep pings disabled.

Is this something you'd consider implementing or accepting contributions for?

**Comment by aslushnikov** [comment]
> Is this something you'd consider implementing or accepting contributions for?

@pwnall this sounds very reasonable. I'd be happy to review a PR.

FYI: ws (our websockets library) had a discussion about pings: https://github.com/websockets/ws/issues/767

**Comment by wzalazar** [comment]
hey guys! this issue is still open or what is the current status?
