### ISSUE TITLE
puppeteer.connect() support for wss (TLS) options

### ISSUE THREAD

**Issue by pwnall** [puppeteer/puppeteer#1775]
It'd be nice if puppeteer.connect() supported using a custom CA for validation and/or a client key+certificate for TLS connections.

It appears that `ws` has this support as the `ca`, `key` and `cert` options. https://github.com/websockets/ws/blob/d03ada231a7961ebfbd797c1ea54632dc8078707/lib/websocket.js#L482

The difficult parts then are:

1) Deciding if this is risky -- all the serious HTTP / WS clients I've seen have TLS support in some form, I don't think this would tie `puppeteer` to `ws`.
2) Figuring out the desired API shape for puppeteer.
3) Tests 😄 

Would you be interested in implementing or accepting contributions for this?

**Comment by aslushnikov** [comment]
@pwnall can you please share your usecases for this?

**Comment by pwnall** [comment]
@aslushnikov I think this would be the easiest way to set up a puppeteer instance connecting to multiple Chrome instances running on separate servers (machines / VMs / containers).

I'd set up nginx with TLS termination on the Chrome servers. The custom CA makes it easy to secure the connections to the Chrome servers. The client key + certificate can be used to prevent unauthorized connections to the Chrome servers.

The main alternative I see, SSH tunnels, is a bit more complex to set up. Also, SSH is blocked by some network equipment, while HTTP(S) are probably the most commonly available ports.

Asides from my use case, you can imagine Chrome VMs as a service. I think supporting TLS WebSocket options would give the best developer experience in this use case, for the same reasons as above.
