### ISSUE TITLE
feature request: add option to generate TOC for pdf output

### ISSUE THREAD

**Issue by Ognian** [puppeteer/puppeteer#1778]
Since now headers and footers with page numbers work, I now desperately miss an option to generate a Table of Contents (TOC) out of the h1- h7 headers when generating a pdf file (i.e like wkhtmltopdf is doing this). The TOC should be at the start of the pdf and it should not only be clickable (jump to the page) but also generate the outline pdf element, so that the TOC is displayed in the contents view in any viewer. Although this may sound complicated if this functionality is implemented at the right place it is not that complicated (take a look on how wkhtmltopdf is implementing this).

Before posting here I tried a couple of workarounds to achieve this.
Some dead ends:
 - CSS3 target_counter() -> proposed a long time ago and only some specialised tools do it, to be honest I've given up to think that it will be implemented in chrome some day (reference issue is now: https://bugs.chromium.org/p/chromium/issues/detail?id=368053 )
 - Find a tool or tools to extract the table of contents from the generated pdf and generate a preface.pdf with the TOC witch to merge in-front of the original pdf ... With https://github.com/qpdf/qpdf I was able to generate a readable and searchable "pdf text-file" so that theoretically it was possible to find the header in the text file and via reverse search and the added comments find out on wich page it is etc. etc...

Any chance to get this soon?
Thanks
Ognian

**Comment by aslushnikov** [comment]
@Ognian will it work if the TOC will be generated inside the page before printing it?

**Comment by Ognian** [comment]
@aslushnikov short answer: **no**
long answer: 
The TOC consists of two parts:
1. A hierarchical list of all headers (h1, optionally h2-h6) in the order as they appear in the document AND the **page number**
2.  the **"document outline dictionary"** in the pdf file (see. 12.3.3 in http://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf) allowing: "that the conforming reader " (pdf viewer ) "may display on the screen, allowing the user to navigate interactively from one part of the document to another"

Generating the hierarchical list of the headers with js inside the page would be possible, even making every item of this a link to the corresponding header would work inside the pdf by jumping to the desired location in the pdf (and not opening a browser ...) (I did some rudimentary testing on this) so this part would be working BUT I have _no way_ to know the _page number_ to print it here; CSS3 target_conter function could be a solution but since it was never implemented in any actual browser I don't think that this will happen soon..
The printed page number is essential if you hold a printout in your hand an want to go to a specific chapter (and sadly this is happens in practice more often then developers like me could imagine)

Making the TOC work in every pdf viewer (2.)  is also essential: You do not want to scroll every time to the start of the pdf file to see the TOC and click on a different chapter where you may find the desired info... 

So in my opinion the only real solution for this is to generate the TOC when rendering the pdf, at this point I have all the needed information I know the page number AND if still have the HTML details...

I added this issue to puppeteer since this project would greatly benefit from this feature. Maybe you have a better overview where in all of the subprojects a change is needed to get this functionality...

Thanks
Ognian

**Comment by N-X-N** [comment]
Hi @Ognian  and @aslushnikov ,

I had a similar TOC problem in another context, and I solved it using tool [wkhtmltopdf](https://wkhtmltopdf.org/).
This tool implements a few good ideas, which you can get inspired from:

1.  Options `--outline`, `--no-outline` and `--outline-depth <level>` set the PDF *outline* (better called the *document outline dictionary*)
2.  The table of content can be inserted using the default stylesheet, or a user-provided one.
    I thought, this was unpractical, instead I used option `--dump-outline` to create an external file containing the headers page numbers, and converted it into a JSON object, which is then inserted into the HTML document on the next read (TOC is then created in JS). This requires generating the document twice to get the page numbers right, but I see no better algorithm.

Therefore, my first proposals for extending `page.pdf()`:
-   add option `outlineDepth`: defaults to **0** (meaning no outline in PDF), else a value like **4** includes all `<h1>` to `<h4>` into the PDF document outline;
-   eventually add option `outlineExcludeSelector`: if element matches selector, then it is not included into the generated outline.
    For example with value `'h3.no-pdf-outline'`, any `<h3 class="no-pdf-outline">...</h3>` would be excluded from the outline.

As for the table of contents with page numbers inside of the document : this is part of a more generic problem.
For example, users may want a table of figures, a table of tables, or a keywords index. And these different tables may be inserted at different places into the document : there are books with a table of contents at the end, or at beginning of each chapter. All of this depends on the editor, the cultural context, etc...

Therefore, I think that generating a list of page numbers for all the specified DOM elements, and putting it into an external object, is the best method : the web page designer can then read these lists, and programmatically insert all required tables of contents/tables/figures or keyword index, at any place they wish.

For `page.pdf()`, this means it needs a few options more to get the page numbers into the right places:
-   add option `numberingSelectors`: accepts either one selector string, for example `selectors:  'h1, h2, h3'`, or an array of selector strings, for example `numberingSelectors:  [  'h1,h2', 'figure.indexed > figcaption', 'table>caption' ]`.\
    For each input selector, an array element will be generated into output structure
-   add option `numberingName`: name of the output structure. For example: `numberingName: 'pageNumbers'`
-   `numberingPath`: file name for output
-   alternative (or combined) to `numberingPath`: `numberingStructure`: the output structure will be written as a property with name from `numberingName` into this object.

A call would look like this:
```js
  await page.pdf({
    //  ... other options, then:
    outlineDepth: 3,
    outlineExcludeSelector: 'h3.no-pdf-outline',
    numberingSelectors: [ 'h1, h2, h3' , 'figure.indexed > figcaption' ],
    numberingName: 'pageNumbers',
    numberingPath: 'elementPages.js'
  });
```

Output file `elementPages.js` would look like this:

```js
'use strict';
var pageNumbers = [
  {
    selector: 'h1, h2, h3',
    elements: [
      { page: 2, tag: 'h1', id: 'chapter-1', innerHTML: '1. Introduction' },
      { page: 4, tag: 'h2', id: 'section-1-1', innerHTML: '1.1 Prerequisites' },
      { page: 8, tag: 'h3', id: 'section-1-1-1', innerHTML: '1.1.1 Operating System' }
    ]
  },
  {
    selector: 'figure.indexed > figcaption',
    elements: [
      { page: 3, tag: 'figcaption', id: 'fig-environment', innerHTML: 'Figure 1: Environment' },
      { page: 5, tag: 'figcaption', id: 'fig-architect', innerHTML: 'Figure 2: Architecture' },
      { page: 7, tag: 'figcaption', id: 'fig-circuit', innerHTML: 'Figure 3: Circuit diagram' }
    ]
  }
];

if (typeof module === 'object') { // Export to node.js, if available
  module.exports = pageNumbers ;
}
```

If `outputObject` is set, then:

```js
  let someObj = {};
  await page.pdf({
    //  ... same options as previous call example, then:
      outputObject: docPages
    } 
  });
  // Access page numbers and IDs with:
  for ( let i=0 ; i<someObj.pageNumbers[0].length; i++ ) {
    let someReference = someObj.pageNumbers[0].elements[i];
    // ...
  }
```

I believe this design is flexible and covers all relevant cases.
Some remarks:
-   the proposed option names may be sub-optimal (English is not my mother tongue), change them as you wish. They can be grouped into a single logical options object too.
-   most web programmers already used selectors with document.querySelectorAll() (options `outlineExcludeSelector` and `numberingSelectors`), therefore the semantics should be straightforward
-   Thanks to the `selector` property in output, the user can fetch all elements from DOM again, therefore only the `page` property is really needed.
    I thought `id`  (if it exists) could be a useful addition.
    For `innerHTML`: it can be useful if you cannot access the DOM directly, but may have drawbacks, especially if the elements have a lot of content. So you can remove it if you wish.
-   When outputting to a local object with `outputObject`, if there is a page DOM reference, then you can directly put a reference to the elements themselves, and keep only `page` in the structure.

**Comment by mpseidel** [comment]
+1

At the moment this is the one blocker for me to try this as an alternative to wkhtml2pdf. Table of contents with page numbers and navigation in the rendered pdf is a must for my use case.

**Comment by j-manu** [comment]
Even if the ToC is non-configurable i.e it is generated using h1/h2/h3/h4 with a default depth of 4  (wkhtmltopdf defaults) it would be really helpful.

**Comment by lvmajor** [comment]
Is there an issue opened in upstream projects so that we could see if there is any progress on this ?

Thanks in advance! :)

**Comment by Ognian** [comment]
@aslushnikov can you help us by identifying the correct upstream projects?
Looks like I'm not the only one desperately waiting for this feature :-)
For me it looks like [this](https://github.com/google/skia/tree/master/src/pdf) is the upstream entry point,
but I'm not sure.
Please share your thoughts with us...
Thanks
Ognian

**Comment by aslushnikov** [comment]
> @aslushnikov can you help us by identifying the correct upstream projects?

@Ognian please file to the chromium repository at https://crbug.com/new and post the link to the bug here for the record.

**Comment by Ognian** [comment]
@aslushnikov Thanks, here it is https://bugs.chromium.org/p/chromium/issues/detail?id=840455

**Comment by Ognian** [comment]
For those listening only on this thread, the chromium bug was just updated:
```
Here's the status of this:  SkPDF [*] now lets you add this information to the PDF.  Chrome does not yet use this new API.

[*] https://skia.googlesource.com/skia/+/master/include/docs/SkPDFDocument.h
```

**Comment by wuno** [comment]
We also need a Table of Contents feature. We are currently building a work around but to have this as a feature would be extremely valuable to our team.

**Comment by suportecaso1** [comment]
@wuno 
> We also need a Table of Contents feature. We are currently building a work around but to have this as a feature would be extremely valuable to our team.

Can you share how you built it?

**Comment by plaffitt** [comment]
@suportecaso1 I found [this article](https://medium.com/@pofider/generate-pdf-with-toc-using-chrome-c3b44f924ff9) on medium that shows a workaround to generate a pdf with TOC using chrome (puppeteer is, of course, fine too). To summarize, you could generate the pdf with the TOC but without page numbers, parse the PDF to find out the page numbers, and then regenerate it with the page numbers.

I really need a table of content in my document so I'll go with this solution for the moment, but I think this feature is a must have in puppeteer. I hope someone will implement it soon.

**Comment by gigaga** [comment]
@paullaffitte 
I saw your article. I implemented the solution and it works like a charm!

Thanks a lot!

**Comment by damgot** [comment]
I'm also very interested on this feature (Toc with page number). So I comment to follow :)

**Comment by Ognian** [comment]
@damgot may you could also vote and follow the chromium bug too (https://bugs.chromium.org/p/chromium/issues/detail?id=840455). This is where it is stuck at the moment... And maybe someone from google could poke this too...

**Comment by Hideman85** [comment]
Any news on this feature? And about pdf internal links? because it would be a good start to generates toc without page number if the link is clickable and forward us to the actual part.

**Comment by isneezy** [comment]
Until we wait for a native solution, I've built this simple service https://github.com/isneezy/pdf-generator-service, it can generate TOC and the solution is based on [this helpful article](https://medium.com/@pofider/generate-pdf-with-toc-using-chrome-c3b44f924ff9).   

Hope you enjoy it.

**Comment by shaozj** [comment]
Any news on this feature? I look forward to this feature

**Comment by simonc** [comment]
If it can help anyone, I've been using [Paged.js](https://pagedjs.org/post/toc/) for this for a while now. It's pretty good.

It has a cost in terms of generation time (especially with large CSS) but it works well and brings additional benefits 🙂

**Comment by universemaster** [comment]
Hi  @simonc.  Thanks for posting the link to paged.js.  I've spent several hours trying to get paged.js to work without success.

(Also the link now goes to a 404).

Are you referring here to the TOC embedded in the PDF (also known as a "document outline dictionary")?

I wonder if you can upload an example on github, or offer a few hints?

**Comment by simonc** [comment]
Hey @universemaster, I can give you a watered down example of what we do in one of our master templates at PDFMonkey:

```html
<!-- HTML -->

<div class="page">
  <h2>Table of Content</h2>

  {% for section in sections %}
    {% assign sectionId = forloop.index %}
      
    <div class="flex items-center gap-4">
      <div>{{section.title}}</div>
      <div data-page-ref="#section-{{sectionId}}"></div>
    </div>
  {% endfor %}
</div>

<!-- later on… -->

{% for section in sections %}
  {% assign sectionId = forloop.index %}
  ...
  <h2 id="section-{{sectionId}}">{{section.title}}</h2>
  ...
{% endfor %}

<!-- towards the end… -->

<script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
```

```css
/* CSS */

[data-page-ref]::after {
  content: 'p. ' target-counter(attr(data-page-ref), page);
}
```

That's pretty much it actually 🙂 

Hope this can help.

**Comment by impworks** [comment]
I found a way to do this in just a few lines of pure HTML and JS.
This snippet is __not completely reliable__ and will likely break on edge cases, but it worked better than paged.js for my document.

First of all, my report is split into pages which look like this:

```html
<div class="page">
    <h3 class="toc-header" id="header1">Page Header</h3>
    <!-- page content here -->
</div>
```

Then, the following JS snippet iterates over the list of all pages, counting the numbers:

```js
window.addEventListener('beforeprint', () => {
    // style the template as needed
    // just keep .toc-link and .toc-page-number classes
    const template = '<div><a href="#" class="toc-link"></a>: <span class="toc-page-number></span></div>';

    let result = '';
    let pageNumber = 1;
    let pageHeight = 842; // A4 size at 72 dpi

    const pages = document.querySelectorAll('.page');
    for (let p of pages) {
        const currHeight = p.getBoundingClientRect().height;

        const header = p.querySelector('.toc-header');
        if (header) {
            const tempElem = document.createElement('div');
            tempElem.innerHTML = template;

            const pageElem = tempElem.querySelector('.toc-page-number');
            pageElem.innerText = pageNumber;

            const linkElem = tempElem.querySelector('.toc-link');
            linkElem.innerText = header.innerText;
            linkElem.href = '#' + header.id;

            result += tempElem.innerHTML;
        }

        pageNumber += Math.ceil(currHeight / pageHeight);
    }

    // append result to some designated TOC container
});
```

**Comment by simonc** [comment]
Hi @impworks, Thanks for this alternative solution! I think it can work great if you're able to split your content in pages 😊

Sadly for me it's not always the case and Paged.js remains the backup plan for those situations 😅

**Comment by impworks** [comment]
@simonc well, it does handle sections spanning multiple pages via `Math.ceil()`. The `page` wrapper is actually needed to account for empty space before an explicit page break. Depending on the document structure, there can be some slightly different strategy.

I still wish there was a canonical built-in way to do this though, like the page number classes in a footer.

**Comment by sikorjan** [comment]
@impworks just minor bug in your code (missing "): `class="toc-page-number` should be `class="toc-page-number"`

**Comment by SidAngular1996** [comment]
> ```js
> template
> ```

Can you share a working fiddle? Or repo @impworks

**Comment by impworks** [comment]
@SidAngular1996 unfortunately my example above did not work as expected. It produced nice results at first, but as we modified the contents of the page the calculation became wildly unpredictable, so I do not recommend doing it this way. I was not able to come up with anything more reliable and made a decision to avoid using page numbers altogether.

**Comment by SidAngular1996** [comment]
@impworks hey thank you for replying.
Any idea on how can I generate toc dynamically I'm using handlebars and node js.
As my pdf gets generated based on filled up forms it's highly dynamic. 
Can you suggest any package that can help me ?

Thanks in advance

**Comment by NigelCunningham** [comment]
Here's what I'm using (this is with pagedJS as well, running afterwards):

```
    function createToc(config) {
        const content = config.content;
        const tocElement = config.tocElement;
        const titleElements = config.titleElements;

        let tocElementDiv = content.querySelector(tocElement);

        // No location at which to add a Table of Contents.
        if (!tocElementDiv) {
            return;
        }
        let tocUl = document.createElement("ul");
        tocUl.id = "list-toc-generated";
        tocElementDiv.appendChild(tocUl);

        // Add class to all title elements.
        let tocElementNbr = 0;
        for (var i = 0; i < titleElements.length; i++) {

            let titleHierarchy = i + 1;
            let titleElement = content.querySelectorAll(titleElements[i]);


            titleElement.forEach(function (element) {

                // Add classes to the element.
                element.classList.add("title-element");
                element.setAttribute("data-title-level", titleHierarchy);

                // add id if doesn't exist
                tocElementNbr++;
                idElement = element.id;
                if (idElement == '') {
                    element.id = 'title-element-' + tocElementNbr;
                }
                let newIdElement = element.id;

            });

        }

        // Create toc list.
        let tocElements = content.querySelectorAll(".title-element");

        for (var i = 0; i < tocElements.length; i++) {
            let tocElement = tocElements[i];

            let tocNewLi = document.createElement("li");

            // Add class for the hierarcy of toc.
            tocNewLi.classList.add("toc-element");
            tocNewLi.classList.add("toc-element-level-" + tocElement.dataset.titleLevel);

            // Keep class of title elements except for page-break-before and -after.
            let classTocElement = tocElement.classList;
            let removedClasses = [ 'title-element', 'page-break-before', 'page-break-after' ];
            for (var n = 0; n < classTocElement.length; n++) {
                if (removedClasses.indexOf(classTocElement[n]) == -1) {
                    tocNewLi.classList.add(classTocElement[n]);
                }
            }

            // Create the element.
            tocNewLi.innerHTML = '<a href="#' + tocElement.id + '">' + tocElement.innerHTML + '</a>';
            tocUl.appendChild(tocNewLi);
        }
    }

    window.addEventListener('DOMContentLoaded', () => {
        class handlers extends Paged.Handler {
            constructor(chunker, polisher, caller) {
                super(chunker, polisher, caller);
            }

            beforeParsed(content) {
                createToc({
                    content: content,
                    tocElement: '#toc',
                    titleElements: ['.toc_entry'],
                });
            }
        }
...
```

**Comment by SidAngular1996** [comment]
@NigelCunningham can you please share a working repo where I can build a pdf from html or extract data from a pdf I'm using handlebars and nodejs?

**Comment by simplecommerce** [comment]
> Here's what I'm using (this is with pagedJS as well):
> 
> ```
>     function createToc(config) {
>         const content = config.content;
>         const tocElement = config.tocElement;
>         const titleElements = config.titleElements;
> 
>         let tocElementDiv = content.querySelector(tocElement);
> 
>         // No location at which to add a Table of Contents.
>         if (!tocElementDiv) {
>             return;
>         }
>         let tocUl = document.createElement("ul");
>         tocUl.id = "list-toc-generated";
>         tocElementDiv.appendChild(tocUl);
> 
>         // Add class to all title elements.
>         let tocElementNbr = 0;
>         for (var i = 0; i < titleElements.length; i++) {
> 
>             let titleHierarchy = i + 1;
>             let titleElement = content.querySelectorAll(titleElements[i]);
> 
> 
>             titleElement.forEach(function (element) {
> 
>                 // Add classes to the element.
>                 element.classList.add("title-element");
>                 element.setAttribute("data-title-level", titleHierarchy);
> 
>                 // add id if doesn't exist
>                 tocElementNbr++;
>                 idElement = element.id;
>                 if (idElement == '') {
>                     element.id = 'title-element-' + tocElementNbr;
>                 }
>                 let newIdElement = element.id;
> 
>             });
> 
>         }
> 
>         // Create toc list.
>         let tocElements = content.querySelectorAll(".title-element");
> 
>         for (var i = 0; i < tocElements.length; i++) {
>             let tocElement = tocElements[i];
> 
>             let tocNewLi = document.createElement("li");
> 
>             // Add class for the hierarcy of toc.
>             tocNewLi.classList.add("toc-element");
>             tocNewLi.classList.add("toc-element-level-" + tocElement.dataset.titleLevel);
> 
>             // Keep class of title elements except for page-break-before and -after.
>             let classTocElement = tocElement.classList;
>             let removedClasses = [ 'title-element', 'page-break-before', 'page-break-after' ];
>             for (var n = 0; n < classTocElement.length; n++) {
>                 if (removedClasses.indexOf(classTocElement[n]) == -1) {
>                     tocNewLi.classList.add(classTocElement[n]);
>                 }
>             }
> 
>             // Create the element.
>             tocNewLi.innerHTML = '<a href="#' + tocElement.id + '">' + tocElement.innerHTML + '</a>';
>             tocUl.appendChild(tocNewLi);
>         }
>     }
> 
>     window.addEventListener('DOMContentLoaded', () => {
>         class handlers extends Paged.Handler {
>             constructor(chunker, polisher, caller) {
>                 super(chunker, polisher, caller);
>             }
> 
>             beforeParsed(content) {
>                 createToc({
>                     content: content,
>                     tocElement: '#toc',
>                     titleElements: ['.toc_entry'],
>                 });
>             }
>         }
> ...
> ```

I know it has been a while but I was wondering if you would know why this approach doesn't work when trying to use it with bootstrap.

In my example html, I have latest bootstrap version with paged polyfill and for some reason it doesn't want to generate the PDF, it is always blank, if I remove either, it works.
