### ISSUE TITLE
Page Object Model with Puppeteer

### ISSUE THREAD

**Issue by MadHatter122312** [puppeteer/puppeteer#1782]
I recently started utilizing Puppeteer for e2e testing (I have some experience with Selenium Web Driver) and I could not find anything in the documentation discussing POM pattern.  Are there any examples available how to implement this correctly in node/ES7 within Puppeteer? 

Let us say I have a simple script that tests the login functionality of a page:

```
(async () => {
...

     await page.goto(url, {
        timeout: 5000
    });

    await page.waitFor('input[id=userId]');

    await page.type('input[id=userId]', 'John Doe');
    await page.type('input[id=password]', 'password1');
    await page.click('button[type="submit"]');
    await page.waitFor('p.success-msg');
...
}();

```
Typically, we would have a Page Object Model for the login page.  How would I create a basic POM for the above page and integrate it with my script?  I am just looking for a basic 'hello world' example.

**Comment by JoelEinbinder** [comment]
I am very new to Page Object Model. From what I understand, you can just have a helper file with functions that accept a page object. Something like:

`page.js`
```js
async function login(page, username, password) {
    await page.waitFor('input[id=userId]');
    await page.type('input[id=userId]', username);
    await page.type('input[id=password]', password);
    await page.click('button[type="submit"]');
    await page.waitFor('p.success-msg');
}
module.exports = { login }
```

`test.js`
```js
const {login} = require('./page');

async function test(page) {
     await page.goto(url, {
        timeout: 5000
    });
    await login(page, 'John Doe', 'password1');
}
```

**Comment by rob4629** [comment]
Hi, the above "answer" doesn't really answer the question. Yes, we can create separate functions and import those in to our tests, but having a POM would be much better.

I've successfully implemented a POM using both Cypress and TestCafe... but having some issues with Puppeteer. If anyone has made any progress since either this issue (or #2949) was closed, it would be appreciated.

**Comment by JoelEinbinder** [comment]
@rob4629 Can you file a new issue for exactly what functionality you are missing from Puppeteer? Asking for POM is too vague for me to be helpful.

**Comment by rob4629** [comment]
Sorry, that's a good point. I'll raise a new issue and try to add a better explanation.

**Comment by AutomatedOwl** [comment]
I made a basic example of POM using puppeteer: https://github.com/AutomatedOwl/puppeteer-pom-example

**Comment by ProMadGenius** [comment]
I made a example of using Page Object Pattern POM with Mocha and Puppeteer if you want to check: https://github.com/ProMadGenius/PuppeteerFramework.git
