### ISSUE TITLE
Events do not trigger from IDBOpenDBRequest after calling window.indexedDB.open.

### ISSUE THREAD

**Issue by LvChengbin** [puppeteer/puppeteer#1784]
* Puppeteer version: 0.13.0
* Platform / OS version: MacOS 10.13.2
* Node.js version: 8.9.3

~~~js
const request = window.indexedDB.open( 'dbname', 1 );

request.onsuccess = e => {
    console.log( e ); // not working
};

request.onerror = e => {
    console.log( e ); // not working
};

~~~

Both `onsuccess` and `onerror` are not working.

**Comment by aslushnikov** [comment]
@LvChengbin I can't reproduce this; the following script works fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  page.on('console', msg => console.log(msg.text()));
  await page.evaluate(() => {
    const request = window.indexedDB.open( 'dbname', 1 );

    request.onsuccess = e => {
        console.log('Success');
    };

    request.onerror = e => {
        console.log('Failure');
    };
  });
})();
```
We've had reports in the past from indexDB users, so I'd assume that there's a problem with your script.

Please don't hesitate to write us if you think we can help somehow.

**Comment by LvChengbin** [comment]
@aslushnikov I am so sorry to trouble you. I tested the code you provided in your comment, it is working well. And I cannot find anything really different between your code and mine, it's just calling the `open` method. But the main difference is that I am using `ChromeHeadless` in Karma by using the [karma-chrome-launcher](https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer) for testing my code, it is using another way for calling `Chrome` in `Headless` mode instead of using `puppeteer.launch()`. I am also using this way for running other test cases and they are running well except `indexedDB`.

**Comment by LvChengbin** [comment]
@aslushnikov I find out the reason that the `console.log` cannot print any messages. It's just because `karma` doesn't print the message to the terminal, I don't know why does only `Chrome Headless` have this problem, but after changing my code, I am sure the `events` of `indexedDB` are being triggered correctly. 

Thank you so much and apologize for wasting your time.

**Comment by aslushnikov** [comment]
> I find out the reason that the console.log cannot print any messages. It's just because karma doesn't print the message to the terminal

@LvChengbin Good to know! Thanks for sharing.
