### ISSUE TITLE
Chromium Page Crashes 

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#1785]
This is reported here: https://github.com/GoogleChrome/puppeteer/issues/1325#issuecomment-356964506

@dallashuggins to debug this further, can you please:
1. Launch chrome canary in non-headless (headful) mode and provoke the crash.
2. After that, open "chrome://crashes" tab in the Chrome Canary and find the most recent crash. It should be the one that just occured
3. Hit the "send now" button if the crash is not send yet; if the crash is sent and uploaded, share the crashId here in the issue.

A small code snippet to clarify the steps:
```js
const puppeteer = require('.');

(async() => {
  const browser = await puppeteer.launch({
    headless: false,
    executablePath: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
  });
  // here's the code that results in a crash
  const page = await browser.newPage();
  await page.goto('about:crash');

  // keep the browser open.
  // navigate to chrome://crashes and post the "crashId" here
})();
```

Hopefully this works out and will get us a crash stacktrace.

**Comment by dallashuggins** [comment]
Hi @aslushnikov - 

Thank you for sending those instructions. The Crash Report IDs I received were `930b35a1edda0f75` and `dd15c47fa368ee49 `.

**Comment by aslushnikov** [comment]
@dallashuggins Sorry for this taking so long. From the crash reports, it looks like the issues should be fixed already. Can you please check with pptr v1.3.0?

**Comment by fringd** [comment]
@dallashuggins ^^ I'm eager to know if your issues are fixed, I'm having some intermittent chromium crashes myself. EDIT ( with puppeteer 1.4 )
