### ISSUE TITLE
Support question -  always launch Chrome in new tab in existing window, if existing window exists

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#1788]
Hey all, will try to get straight to the point - I am planning to use Puppeteer to launch in `{headless: false}` mode.

(a) I am looking to launch Puppeteer as a new tab in an existing window, using some flag
(b) I'd like the ChromeDevTools view to open automatically, using some flag

I checked out SO for any existing questions on this, didn't see any:
https://stackoverflow.com/questions/tagged/puppeteer

So my question is - does Puppeteer provide us with flags that can force an existing window to be used instead of launching in a new window, and to force dev tools to open?

**Comment by ORESoftware** [comment]
I see my question is partially answered here:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions

So I would do:

```js
const puppeteer = require('puppeteer');
const b = await puppeteer.launch({
   devtools: true
});
```

**however, I don't see a command line flag that tells Chrome to have an affinity for an existing window, and to avoid opening a new window:**

https://peter.sh/experiments/chromium-command-line-switches/

_is there any such flag?_

**Comment by aslushnikov** [comment]
@ORESoftware do you want to connect puppeteer to already-running chrome?

This is possible with `puppeteer.connect`, but you'd need to know the websocket endpoint of the running browser. If the original browser was launched with puppeteer, you can get it with `browser.wsEndpoint()` method.

**Comment by the1mills** [comment]
Cool thanks...so how exactly can I use connect() to open a tab in an existing window?

I have a websocket client in a Chrome Extension, but not a websocket server

**Comment by aslushnikov** [comment]
@the1mills there's no way if the browser is not launched with `--remote-debugging-port` flag.

If your browser is launched with the `--remote-debugging-port` flag, it prints URL of a websocket server that the browser opens for automation purposes.

**Comment by the1mills** [comment]
Ok cool, so the wss in the browser speaks the Chrome protocol? Do you have a simple example of sending a request to the wss in the browser?

I think I need to call Target.create()?

**Comment by aslushnikov** [comment]
@the1mills we don't have it here; but there are many resources of the web.

Good places to start reading about Chrome DevTools Protocol are:
- [devtools protocol](https://chromedevtools.github.io/devtools-protocol/) documentation
- [chrome remote interface](https://github.com/cyrus-and/chrome-remote-interface) project

**Comment by the1mills** [comment]
Ok thanks - so I am guessing you can use the protocol to tell the wss in the existing window to open a new tab, just have to figure out the right calls, thx

**Comment by ORESoftware** [comment]
@aslushnikov ok homie, I am diggin' your style, but I now have some beef

I have this:

```js
const util = require('util');
const puppeteer = require('puppeteer');

(async () => {

  const b = await puppeteer.launch({
    headless: false,
    devtools: true, 
    args: ['--remote-debugging-port=9222']
  });

  const browser = await puppeteer.connect({
    browserWSEndpoint:   b._connection._url,   //`ws://${host}:${port}/devtools/browser/<id>`,
    ignoreHTTPSErrors: false
  });

})();
```

My question is, why do I need to use `b._connection._url` ... 2 properties with underscores. 

**Something is wrong**. Is there a better way to grab the connection url?

**Comment by aslushnikov** [comment]
> My question is, why do I need to use b._connection._url ... 2 properties with underscores.

@ORESoftware you don't need to. You can use [`browser.wsEndpoint()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserwsendpoint) instead.

**Comment by ORESoftware** [comment]
ah yes, thanks very much, one more question for you tonight - do you know the flag to enable Chrome extensions? I am not seeing it on the list of Chrome flags When I launch Chrome with puppeteer I don't see any Chrome extensions in the browser action section - I am developing a Chrome extension, that's why I care.

**Comment by ORESoftware** [comment]
Specifically, when I try calling this:

```js
await page.goto('chrome-extension://hfnplgaapcnjblpebnhibfcdfllkpaaf/dist/index.html');
```

I get this error:

> (node:40130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: net::ERR_BLOCKED_BY_CLIENT

I assume that means the client blocked the request to load the extension?

**Comment by aslushnikov** [comment]
@ORESoftware unfortunately, chrome extensions are not supported by chrome headless.

**Comment by ORESoftware** [comment]
well if I do `{headless: false}`? still no extensions?

**Comment by ORESoftware** [comment]
Chrome Launcher has an option to `enableExtensions`:

https://github.com/GoogleChrome/chrome-launcher#launch-options

do you think that puppeteer could do that too?

**Comment by aslushnikov** [comment]
@ORESoftware extensions will work just fine in headful mode. To launch in headful with extensions, you'll need to filter-out the `--disable-extensions` flag from default pptr flags:

```js
const args = puppeteer.defaultArgs().filter(arg => arg !== '--disable-extensions');
const browser = await puppeteer.launch({
  headless: false,
  ignoreDefaultArgs: true
  args,
});
```

**Comment by ORESoftware** [comment]
ok thanks, let me try that, but that's gnarly dude

why not have defaults, but override the defaults with what the user has passed to `launch()`?

**Comment by ORESoftware** [comment]
damn, I get
**TypeError: puppeteer.defaultArgs is not a function**

**Comment by aslushnikov** [comment]
> why not have defaults, but override the defaults with what the user has passed to launch()?

Because we have a lot of defaults that user will never pass by himself. 

> TypeError: puppeteer.defaultArgs is not a function

THe `puppeteer.defaultArgs()` is not available in v0.13.0; it's available since v1.0.0.

**Comment by ORESoftware** [comment]
I just installed puppeteer today, I have this version

`"puppeteer": "^0.13.0",`

how do I get 1.0.0?

**Comment by ORESoftware** [comment]
yeah I guess with arrays, it's not as easy to override defaults, I understand your methodology

**Comment by aslushnikov** [comment]
@ORESoftware 1.0.0 was published a few hours ago; try installing one more time

**Comment by ORESoftware** [comment]
Ok cool, I installed it with `npm install -S puppeteer@latest`

so I have this:

```js
const puppeteer = require('puppeteer');

(async () => {
  

  const args = puppeteer.defaultArgs().filter(arg => String(arg).toLowerCase() !== '--disable-extensions');

  const b = await puppeteer.launch({
    headless: false,
    devtools: true,
    ignoreDefaultArgs: true,
    args: args.concat(['--remote-debugging-port=9223'])
  });

  const browser = await puppeteer.connect({
    browserWSEndpoint:  b.wsEndpoint() ,   //`ws://${host}:${port}/devtools/browser/<id>`,
    ignoreHTTPSErrors: false
  });

  const page = await browser.newPage();
  await page.goto('chrome-extension://hfnplgaapcnjblpebnhibfcdfllkpaaf/dist/index.html');


})();
```

but I still can't launch the chrome extension, I get the same error:

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: net::ERR_BLOCKED_BY_CLIENT

there is no error if I do

`await page.goto('http://yahoo.com');`

so it has to do with attempting to load the extension, any ideas? thx
