### ISSUE TITLE
docker alpine with node js and chromium headless - puppeter - failed to launch chrome

### ISSUE THREAD

**Issue by lboc80** [puppeteer/puppeteer#1793]
I'm trying to run a custom node command from within an Alpine linux docker container.

Installed packages:

```
    alpine-baselayout
    alpine-keys
    libressl2.4-libcrypto
    libressl2.4-libssl
    apk-tools
    scanelf
    libc-utils
    glibc
    libgcc
    glibc-bin
    libbz2
    expat
    libffi
    gdbm
    xz-libs
    ncurses-terminfo-base
    ncurses-terminfo
    ncurses-libs
    readline
    sqlite-libs
    musl
    zlib
    libpng
    freetype
    pkgconf
    zlib-dev
    libpng-dev
    freetype-dev
    libstdc++
    binutils-libs
    binutils
    gmp
    isl
    libgomp
    libatomic
    mpfr3
    mpc1
    gcc
    musl-dev
    libc-dev
    g++
    ca-certificates
    libssh2
    libcurl
    pcre
    git
    libjpeg-turbo
    libjpeg-turbo-dev
    tiff
    tiff-dev
    lcms2
    lcms2-dev
    musl-utils
    libffi-dev
    libressl
    libressl2.4-libtls
    libressl-dev
    make
    db
    libsasl
    libldap
    libpq
    postgresql-libs
    postgresql-dev
    python2
    py-setuptools
    python3
    python3-dev
    libxau
    libbsd
    libxdmcp
    libxcb
    libx11
    gifsicle
    pngquant
    optipng
    libjpeg-turbo-utils
    busybox
    udev-init-scripts
    eudev-libs
    libuuid
    libblkid
    kmod
    eudev
    fontconfig
    libfontenc
    mkfontscale
    mkfontdir
    ttf-opensans
    libogg
    flac
    libxcomposite
    libxfixes
    libxrender
    libxcursor
    libxdamage
    libxext
    libxi
    libxrandr
    libxscrnsaver
    libxtst
    alsa-lib
    libintl
    libmount
    glib
    atk
    pixman
    cairo
    dbus-libs
    avahi-libs
    nettle
    libtasn1
    p11-kit
    libunistring
    gnutls
    cups-libs
    libxml2
    shared-mime-info
    hicolor-icon-theme
    gdk-pixbuf
    gtk-update-icon-cache
    libxinerama
    at-spi2-core
    at-spi2-atk
    cairo-gobject
    libepoxy
    graphite2
    harfbuzz
    libxft
    pango
    gtk+3.0
    minizip
    nspr
    nss
    snappy
    libwebp
    libgpg-error
    libgcrypt
    libxslt
    chromium
    .build-deps
    libwebp-dev
    c-ares
    libcrypto1.0
    http-parser
    libssl1.0
    libuv
    nodejs
    nodejs-npm
    libidl
    orbit2
    dbus-glib
    polkit
    gconf

```

node packages (`npm list --depth=0`):

```
    node-pdf-renderer@0.0.1 /var/www/my_proj/idf/static/js
    └── puppeteer@0.12.0
```

but I'm experiencing some errors:

```
    /var/www/my_proj/idf/static/js # node render.js uid=uid-param url=https://www.targethost.example token=tk-param out=/tmp/test.pdf
    
    (node:167) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
    /var/www/my_proj/idf/static/js/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome: /usr/lib/libasound.so.2: no version information available (required by /var/www/my_proj/idf/static/js/node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome)
    
    
    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    
    (node:167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
it seems that is not able to instantiate chromium.
I also tried to modify teh render.js script while it creates an instance of the browser to this:

```
    const browser = await puppeteer.launch({
            args: ['--no-sandbox'],
            headless: false
        });

```
but I got the same result. Any help on this?

**Comment by aslushnikov** [comment]
@lboc80 did you try [this comment](https://github.com/GoogleChrome/puppeteer/issues/379#issuecomment-334447389)? Overall, looks like a dupe of #379.

**Comment by clayrisser** [comment]
If you want to get puppeteer to work on alpine, try using an older version of puppeteer that works with an older version of Chrome. The newest version of Chrome supported on Alpine is 63, which was the version of Chrome used during the development of puppeteer version 0.11.0.

```sh
npm install --save puppeteer@0.11.0
```

This version of Chrome can only be found on Alpine edge. You can install it in older versions of Alpine by running the following.

```sh
ENV CHROME_BIN=/usr/bin/chromium-browser
RUN echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      nss@edge
```

Make sure you start puppeteer the with the following configuration

```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  executablePath: process.env.CHROME_BIN || null,
  args: ['--no-sandbox', '--headless', '--disable-gpu']
});
```

**Comment by clayrisser** [comment]
I forgot, make sure you also install `nss@edge`

**Comment by sohailalam2** [comment]
This worked for me

Use **Puppeteer v0.13.0**. As of writing this comment, the latest version of Puppeteer is not compatible with chromium in Alpine linux.

`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"` will skip downloading the default version of Chromium when installing Puppeteer. 

**Dockerfile:**

```Dockerfile
FROM node:11-alpine
    
    ENV CHROME_BIN="/usr/bin/chromium-browser"\
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
    
    RUN set -x \
      && apk update \
      && apk upgrade \
      # replacing default repositories with edge ones
      && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" > /etc/apk/repositories \
      && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
      && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
      \
      # Add the packages
      && apk add --no-cache dumb-init curl make gcc g++ python linux-headers binutils-gold gnupg libstdc++ nss chromium \
      \
      && npm install puppeteer@0.13.0 \
      \
      # Do some cleanup
      && apk del --no-cache make gcc g++ python binutils-gold gnupg libstdc++ \
      && rm -rf /usr/include \
      && rm -rf /var/cache/apk/* /root/.node-gyp /usr/share/man /tmp/* \
      && echo
    
    ENTRYPOINT ["/usr/bin/dumb-init"]
    
    CMD node
```

**NodeJs:**

You need to tell Puppeteer to use the installed Chromium version using the following config - `executablePath: '/usr/bin/chromium-browser'`

```js
const puppeteer = require('puppeteer');
    
    puppeteer
      .launch({
        executablePath: '/usr/bin/chromium-browser',
        args: ['--no-sandbox', '--disable-dev-shm-usage'],
      })
      .then(async (browser) => {
        // your code
      });
```

**Comment by ddehghan** [comment]
This works too:

```
FROM node:10.7.0-alpine AS base
ENV CHROME_BIN="/usr/bin/chromium-browser" \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    udev \
    ttf-freefont \
    chromium \
    && npm install puppeteer@1.10.0

```

```
          const browser = await puppeteer.launch({
                headless: true,
                executablePath: process.env.CHROME_BIN || null,
                args: ['--no-sandbox', '--headless', '--disable-gpu', '--disable-dev-shm-usage']
            });
```

**Comment by mikkeschiren** [comment]
There are now also a bare core version of puppeteer that does not download Chromium - so you could simplify a bit:

```
FROM node:11-alpine

ENV CHROME_BIN="/usr/bin/chromium-browser" \
    NODE_ENV="production"
RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    dumb-init \
    udev \
    ttf-freefont \
    chromium \
    && npm install puppeteer-core@1.10.0 --silent \
      \
      # Cleanup
      && apk del --no-cache make gcc g++ python binutils-gold gnupg libstdc++ \
      && rm -rf /usr/include \
      && rm -rf /var/cache/apk/* /root/.node-gyp /usr/share/man /tmp/* \
      && echo
COPY . /app
RUN cd /app && npm install --quiet
EXPOSE 3000
WORKDIR /app
ENTRYPOINT ["/usr/bin/dumb-init"]
CMD npm run start
```

**Comment by rossdeane** [comment]
Remember to change your import if using puppeteer-core as above.
`const puppeteer = require('puppeteer-core');`

See [puppeteer-vs-puppeteer-core](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core) in the docs.

**Comment by viotile** [comment]
> This works too:
> 
> ```
> FROM node:10.7.0-alpine AS base
> ENV CHROME_BIN="/usr/bin/chromium-browser" \
>     PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
> RUN set -x \
>     && apk update \
>     && apk upgrade \
>     && apk add --no-cache \
>     udev \
>     ttf-freefont \
>     chromium \
>     && npm install puppeteer@1.10.0
> ```
> 
> ```
>           const browser = await puppeteer.launch({
>                 headless: true,
>                 executablePath: process.env.CHROME_BIN || null,
>                 args: ['--no-sandbox', '--headless', '--disable-gpu', '--disable-dev-shm-usage']
>             });
> ```

this works for me

**Comment by stephancasas** [comment]
I got this working by writing a `.npmrc` file as part of my entrypoint script.

```
touch /var/www/html/bin/node/printpdf-js/.npmrc
echo "puppeteer_skip_chromium_download=true" > /var/www/html/bin/node/printpdf-js/.npmrc
```

Worked like a charm.

**Comment by ralyodio** [comment]
does anyone know how to actually exit puppeteer on alpine? My processes don't exit reliably and i get too many built up then server slows down.

**Comment by stephancasas** [comment]
> does anyone know how to actually exit puppeteer on alpine? My processes don't exit reliably and i get too many built up then server slows down.

How are you writing your function to control puppeteer? Ending with `browser.close()` (where `browser` is the object result of `puppeteer.launch()`), has always been sufficient in my projects.

**Comment by hemanthreddyk** [comment]
@chovy Try this out, it worked like charm in my case
If running Docker >= 1.13.0 use docker run's --init arg to reap zombie processes, otherwise
add the following lines to your dockerfile to have `dumb-init` as PID 1

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_x86_64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init
ENTRYPOINT ["dumb-init", "--"]

Reference: https://developers.google.com/web/tools/puppeteer/troubleshooting#running_puppeteer_in_docker

**Comment by vasania** [comment]
I have followed almost everything for running the puppeteer on JEnskins Pipeline through Docker Image - Alpline but getting the errors as 
libasound.so.2: no version information available 
Relink `/usr/lib/libbrotlidec.so.1' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `memmove'


Has anyone have faced this erros and able to solve it?

Thank you,

**Comment by MrRakhim** [comment]
Just pay attention to instructions by following [link](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine)
and run the container **--privileged**
