### ISSUE TITLE
DevTools location / placement - opening devtools on the bottom instead of side

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#1797]
I have this which works:

```js
 const browser = await puppeteer.launch({
    headless: false,
    devtools: true,
    ignoreDefaultArgs: true,
    args: args.concat([
        '--remote-debugging-port=9223',
        '--load-extension=/some/local/path/to/your/extension'
      ]
    )
  });
```

however this opens DevTools on the right hand side, instead of the bottom of the browser. See:

<img width="1202" alt="screenshot 2018-01-13 15 09 40" src="https://user-images.githubusercontent.com/11139560/34910940-cea8b1cc-f873-11e7-9c73-918205c6a4c6.png">

**Is there a flag we can use to tell Chrome to open DevTools on the bottom of the page?**

I looked through the issues and don't see a related question, thanks, sorry if it's a dumb question but was hard to find an answer with Google.

**Comment by aslushnikov** [comment]
This would be possible with #1693; there's a `devtools.currentDockState` preference that could be assigned to `'bottom'`.

**Comment by skyiea** [comment]
Here is the PR to track: https://github.com/GoogleChrome/puppeteer/pull/1806

**Comment by skyiea** [comment]
@aslushnikov Where did you get `devtools.currentDockState = 'bottom'`? Can't find such a pref in [the list](https://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/pref_names.cc?view=markup).

**Comment by dkokic** [comment]
> This would be possible with #1693; there's a `devtools.currentDockState` preference that could be assigned to `'bottom'`.

@aslushnikov Would you be so kind to post a code snippet showing how/where to place `devtools.currentDockState = 'bottom'` ?

**Comment by chriscalo** [comment]
Friendly bump. Where does one set `devtools.currentDockState = "bottom"`?

**Comment by zahhar** [comment]
@chriscalo I will leave it here in case someone is still looking how to launch Puppeteer with DevTools stacked to bottom:

```javascript
const puppeteer = require('puppeteer-extra');
const puppeteerPrefs = require('puppeteer-extra-plugin-user-preferences');

(async () => {

    puppeteer.use(puppeteerPrefs({
      userPrefs: {
        devtools: {
          preferences: {
            currentDockState: '"bottom"'
          },
        },
      },
    }));

    const browser = await puppeteer.launch({
        headless: false,
        devtools: true
    });

})();
```
