### ISSUE TITLE
Run arbitrary / dynamic script (RPC) in the browser given puppeteer connection

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#1798]
This is a cool question, I must say, lol.

Right now, I have a separate websocket connection in the browser, and it does this:

```js
  const socket = new WebSocket('ws://localhost:6969');

  socket.addEventListener('open', function (event) {
    console.log('client socket is opened');
  });

  socket.addEventListener('message', function (event) {
    socket.close();
    chrome.runtime.reload();     // >>>> here is the main thing I want to execute on front-end
  });
```

my question is, instead of creating my own Websocket connection, is there a way to re-use the puppeteer connection, in a way that's akin to a Remote Procedure Call. Something like this:

On the backend:

```js
  const c = await puppeteer.connect({
    browserWSEndpoint:  browser.wsEndpoint() ,
    ignoreHTTPSErrors: false
  });

  const result = await c.runScript('chrome.runtime.reload();');  // runScript is a made-up method
```

Hopefully the question makes sense. To restate the question, I am looking to run a script in the browser, which is passed to the browser from the puppeteer script.

In my case, the specific script is:

`'chrome.runtime.reload();'`

**Comment by aslushnikov** [comment]
You can use [`page.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args) to run scripts in the page. Please check out our documentation.
