### ISSUE TITLE
Can't find module install.js on install

### ISSUE THREAD

**Issue by thakyZ** [puppeteer/puppeteer#1800]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: Ubuntu 16.04.1
* URLs (if applicable): 
* Node.js version: 8.9.4

**What steps will reproduce the problem?**
Install `fast-cli`.

**What is the expected result?**
That fast-cli installs

**What happens instead?**
puppeteer fails to install

 **Notes:**
I have already successfully gotten it to install on my separate desktop environment via ndm.

**Crash Report**
```
root@mail:~# sudo npm install fast-cli@2.1.0 -g
/root/.npm-global/bin/fast -> /root/.npm-global/lib/node_modules/fast-cli/cli.js

> puppeteer@0.12.0 install /root/.npm-global/lib/node_modules/fast-cli/node_modules/puppeteer
> node install.js

module.js:540
    throw err;
    ^

Error: Cannot find module '/root/.npm-global/lib/node_modules/fast-cli/node_modules/puppeteer/install.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.12.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@0.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-14T02_05_29_910Z-debug.log
```

**Comment by aslushnikov** [comment]
The following command works fine for me with npm 5.5.1 and node 8.9.1:
```
npm install fast-cli@2.1.0
```

This doesn't look like a puppeteer issue; I'd try filing over to the `fast-cli` repository. 
If you think the problem is on our end and there's a good repro, please write back.
