### ISSUE TITLE
Clip option for page.pdf

### ISSUE THREAD

**Issue by kosaa** [puppeteer/puppeteer#1803]
What you mean about add clip option support for page.pdf?

**Comment by QuentinWangWJJ** [comment]
Same here, need do screenshot for a part of page based on html id element. And output as a pdf file use page.pdf.

**Comment by aslushnikov** [comment]
This will require some upstream chrome contributions; feel free to file bugs upstream to https://crbug.com/new

**Comment by joshferrell** [comment]
I've created a request for this feature in [chromium bugs](https://bugs.chromium.org/p/chromium/issues/detail?id=923417#c3)
