### ISSUE TITLE
Feature: Dispatch trusted events

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#1804]
We can dispatch events through the page javascript. `WheelEvent` for example:
```js
await page.evaluate((delta) => {
     const wheelEvent = new WheelEvent('mousewheel', {
           deltaY: delta
     });
     document.dispatchEvent(wheelEvent, document);
}, delta);
```
But any dispatched events will be not trusted. Can we make event trusted via puppeteer API?
It will be great! We will be able to test any event properly.

Also referenced to https://github.com/GoogleChrome/puppeteer/issues/1679

**Comment by vc1** [comment]
This can be used in the browser page
https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted

**Comment by aslushnikov** [comment]
Instead of "faking" trusted events, we try to do the real thing and go through all the browser layers.
This will be much more reliable way of testing input.

FYI: We're working on #1679, but there is no ETA.

**Comment by kresli** [comment]
I'm using puppeteer to listen for user action. For example on click I will pause the event do some stuff and then continue with event. Works ok for click but I cant do it on hover if css pseudo selector handles the display property. I need trusted event to do so. Please consider to implement this feature.
