### ISSUE TITLE
Use variable in page.type();

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#1808]
It is possible to make use of variables into page.type ();

```javascript
var myVar = "here my selector";
var name = "Frank";
await page.type(myVar,name); //it does not work

´´´

**Comment by aslushnikov** [comment]
@fran0254 this should just work; there's no difference between variable and literal from the point of view of `page.type`.

It looks like you have an issue somewhere else in the code. If you share a reproducible example, we'll be able to help further.
