### ISSUE TITLE
page.type() support overwriting

### ISSUE THREAD

**Issue by xzycn** [puppeteer/puppeteer#1810]
page.type() can only append something to a element like **input** tag, is it possible to support this? :)
I can't use page.$eval in some reasons.:(

**Comment by aslushnikov** [comment]
You can press "backspace" to delete characters in the focused input fields:

```js
await page.keyboard.press('Backspace');
```

Hope this helps.

**Comment by xzycn** [comment]
@aslushnikov Thanks for your reply, it maybe better to use *Delete* as the *focus* method put the cursor at the head of input field.
Your proposal is great, but I still think that overwriting would be good and graceful.
Just like this case: I want to clear the input field first,I must to get the length of the field value, and do a loop to delete them all. :)

**Comment by aslushnikov** [comment]
@xzycn for this case I'd suggest using `page.evaluate`/`page.$eval`. You mentioned it doesn't work for you – this is surprising. Do you have a repro for us to look at?

**Comment by xzycn** [comment]
@aslushnikov Actually,I'm building a automation to complete whole procedure for purchasing in walmart.com. The problem occured in the fill-address procedure:
when I changed the value of one input field,I can see the change in page,but when I click the field,it's value become to previous value.
I think it's influenced by some libraries,So I can't give you a repro.:(
