### ISSUE TITLE
page.waitForNavigation returns null when interceptors are enabled

### ISSUE THREAD

**Issue by hasangilak** [puppeteer/puppeteer#1811]
```
import puppeteer from "puppeteer";
import {pause, disableImage} from "../../helpers";
import parseUrl from "parse-url";
import env from './../../env';

let page;
let browser;


beforeAll(async () => {
    browser = await puppeteer.launch({
        slowMo: 80,
        args: [
            `--window-size=${env.width},${env.height}`,
            ...env.args,
        ]
    });
    page = await browser.newPage();
    await page.setRequestInterception(true);
    page.on('request', request => {
        // add stylesheet, font
        if (request.resourceType === 'image')
            request.abort();
        else
            request.continue();
    });
    await page.setViewport({width: env.width, height: env.height});
});


afterAll(() => {
    browser.close();
});


describe("failure-in-login", () => {
    test("should fail due to wrong user", async () => {
        await page.goto(env.host);
        await page.waitForSelector('input#user');
        await pause(100);
        await page.type('input#user', 'admiin');
        await page.type('input#password', env.admin.password);
        const [response] = await Promise.all([
            page.waitForNavigation(),
            page.click('#submit')
        ]);

        expect(parseUrl(response.url).query.user).toEqual('admiin');
    }, 10000 * env.time);
});
```
I have an error on expect(parseUrl(response.url).query.user).toEqual('admiin'); caused by response variable to be null. and if I only remove interceptor things work just fine.

**Comment by aslushnikov** [comment]
@hasangilak what's your pptr version?

**Comment by hasangilak** [comment]
thanks for your response. npm ls puppeteer gives me this: puppeteer@0.13.0

**Comment by aslushnikov** [comment]
@hasangilak we've fixed a few bugs related to this in 1.0.0. Please, try updating.

Beware: all getters in 0.13 became methods in 1.0. For example, `request.url` getter became `request.url()` method. Full list of changes could be found here: https://github.com/GoogleChrome/puppeteer/releases/tag/v1.0.0

**Comment by hasangilak** [comment]
yeah.thanks to you, after upgrading to version 1.0 and refactor some getter into methods, errors are gone. but I had this idea that by blocking images, font and css the overall test suits time would decrease. but in a surprise adding interceptor adds 1 second more. 
time consumed with an interceptor that blocks image, font, css : 10.484s
with no interceptor: 9.457s
is there any way to drastically reduce test time? I`m using jest alongside puppeteer.

**Comment by aslushnikov** [comment]
> is there any way to drastically reduce test time?

Not a general one; you can try caching the page or disabling javascript though.
