### ISSUE TITLE
navigation timed out error in new version

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1812]
Puppeteer version: 1.0.0
Platform / OS version: Win10
Node.js version: 9.4.0
Chromium Version: r526987

puppeteer@0.13.0 version works fine.
But in puppeteer@1.0.0 version, when you tried page.goto() function,
All requests give navigation timed out error.
(i removed all profile directories.)

**Comment by fran0254** [comment]
You can put a simple example of your code ?

**Comment by SWGFL** [comment]
Same issue here. page.goto() just times out.

Puppeteer version: 1.0.0
Platform / OS version: Win7
Node.js version: 7.10.0
Chromium Version: r526987

**Comment by wadjoh** [comment]
I'm running into this as well. I can't totally pinpoint what causes it though, as it doesn't happen 100% of the time. This code seems to always fail on https://try-puppeteer.appspot.com/
```javascript
const browser = await puppeteer.launch();

const page = await browser.newPage();

await page.goto('https://facebook.github.io/jest');
await page.goto('https://facebook.github.io/jest/#use');

await browser.close();
console.log(`All done!`);
```

I'm not sure if it's something to do with having a hash on the URL, or if it's navigating to the same page you're already on like in this example where I tell Puppeteer to to navigate to the same page with with an anchor tag.

Or maybe I'm just way off! 😄 

(I'm aware that the playground is on v0.13. Maybe I'm just experiencing a different issue, myself.)

**Comment by aslushnikov** [comment]
@OzqurYalcin @SWGFL can you guys provide us with a repro? This is hard to reason about without code.

@hooskers this seems to be related to #257 that makes it hard to navigate URLs with anchors.

**Comment by ghost** [comment]
i finally found the problem.

```js
await page.on('request', async(request) => {
console.log(request.url);
});
```
it prints 
> [Function: url]

So, when i try to parse url, it returns  
> The "url" argument must be of type string. Received type function

I could get the request url through the above code with puppeteer@0.13.0 version.
How can I get request url (string) on request with new version ?

**Comment by aslushnikov** [comment]
@OzqurYalcin all the getters were converted to functions. Take a look on the release notes, it should help migrating from 0.13 to 1.0: https://github.com/GoogleChrome/puppeteer/releases/tag/v1.0.0

**Comment by SWGFL** [comment]
Apologies guys, I need to play with it a bit more to see if it is an actual issue or my code needs updating. Will get back to you.

**Comment by SWGFL** [comment]
Ok, I am using the code from the example on the GitHub page:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('', {waitUntil: 'networkidle2'});
  await page.pdf({path: 'hn.pdf', format: 'A4'});

  await browser.close();
})();
```
That works, but when I change the site to something else like `https://swgfl.org.uk`, it fails with:

`(node 22696) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded.`

I haven't been able to nail down exactly why some websites work and others don't. But have tried changing the `timeout` option, and the `waitUntil` value without success.

Simlarly I have tried version 1.0.0, 0.13, 0.12, and 0.11, that website just won't work.

Interestingly when I use:

```javascript
const loaded = page.waitForNavigation({waitUntil: "load"});
await page.setContent(html);
await loaded;
```
That works in all but 1.0.0 (With the HTML I am putting in anyway), but in 1.0.0 it times out (Have tried upping the timeout here too). Works in 1.0.0 if I use:
```javascript
await page.goto(`data:text/html,${html}`, {waitUntil: "networkidle0"});
```

**Comment by putuoka** [comment]
i have exactly the same error even with newer version 1.2.0
it seem puppeteer can't read this character # in url so if we navigate goto to url that has # this error will occurs

> UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded

![image](https://user-images.githubusercontent.com/20880839/37559938-b019c688-2a69-11e8-8d7c-7164dab8b2f0.png)

Any idea how to make this work? i need to go to this url https://example.com/dashboard/#/ide/wksp-3cdn after login

My code:

```
...
await page.waitForNavigation({waitUntil: "networkidle0"});
await page.goto('https://example.com/dashboard/#/ide/wksp-3cdn');
await page.waitFor(2000);
...

```

**Comment by aslushnikov** [comment]
> That works, but when I change the site to something else like https://swgfl.org.uk, it fails 

@SWGFL the following works fine for me on current [tip-of-tree](https://github.com/GoogleChrome/puppeteer/commit/8c54f41552b7352032120c95240f18f7191b3b19):

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://swgfl.org.uk', {waitUntil: 'networkidle2'});
  await page.pdf({path: 'hn.pdf', format: 'A4'});

  await browser.close();
})();
```

> it seem puppeteer can't read this character # in url so if we navigate goto to url that has # this error will occurs

@putuoka this is a known issue: #257
