### ISSUE TITLE
Non-headless Chrome will not launch

### ISSUE THREAD

**Issue by bmay2** [puppeteer/puppeteer#1813]
Chrome will not launch when ```headless:false```. Not specifying the ```headless``` property (i.e. default of ```headless:true```) works.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: Ubuntu 16.04.2 LTS
* URLs (if applicable): N/A
* Node.js version: v8.9.0

**What steps will reproduce the problem?**

```
const browser = await puppeteer.launch({headless:false, args:['--no-sandbox', '--disable-setuid-sandbox']});
const page = await browser.newPage();
```

**What is the expected result?**

Chrome launches and opens a new page.

**What happens instead?**

After first attempt to launch Chrome:

```
(node:18427) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: kill ESRCH
(node:18427) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After second attempt to launch Chrome:

```
(node:18427) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Failed to launch chrome!
```

**Comment by ebidel** [comment]
This is an old version of Puppeteer. Can you try 1.0 and let us know?  Is this in Docker per chance?

**Comment by bmay2** [comment]
Thanks. I updated to 1.0.0, but it is still not working. And this is not in Docker.

**Comment by ebidel** [comment]
Could be missing [dep issues](https://github.com/GoogleChrome/puppeteer/issues/1700) or you're [installing puppeteer as root](https://github.com/GoogleChrome/puppeteer/issues/810#issuecomment-334980075).

**Comment by bmay2** [comment]
I ran ```npm i puppeteer```, then ```sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget```.

It is still not working.

**Comment by minhle2994** [comment]
I have exactly the same issue. Any update?

**Comment by SergeyShkredow** [comment]
I have the same problem on version 1.0 =>

**Comment by SergeyShkredow** [comment]
puppeteer

**Comment by sowmyav82** [comment]
We are also facing this issue

**Comment by npetr** [comment]
I can confirm a similar issue with non-headless Chrome (not Chromium).

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Windows 10
* Browser version: Chrome 67.0.3379.0 (official build) canary (64bit)
* Node.js version: v9.9.0

**What steps will reproduce the problem?**
```javascript
  const browser = await puppeteer.launch({ executablePath: 'chrome.exe', headless: false, args: [
      //'--headless',
      '--mute-audio',
      '--disable-gpu',
      '--hide-scrollbars'
    ] });
```

**What is the expected result?**
Non-headless mode works in Chrome as in Chromium (headless mode works well in both browsers).

**What happens instead?**
Non-headless mode does not work in Chrome.

```
C:\Users\npetr\AppData\Roaming\npm>node non-headless-chrome.js
ERROR: The process "123068" not found.
(node:121692) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[123068:130412:0326/015337.217:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: GCFUserDataDir
[123068:130412:0326/015337.217:ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: PasswordManagerAllowShowPasswords
[123068:130412:0326/015337.352:ERROR:gpu_process_transport_factory.cc(1010)] Lost UI shared context.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Launcher.js:246:14)
    at ChildProcess.helper.addEventListener (C:\Users\npetr\AppData\Roaming\npm\node_modules\puppeteer\lib\Launcher.js:236:60)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
(node:121692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:121692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by npetr** [comment]
**Workaround for:**
> @npetr: I can confirm a similar issue with non-headless Chrome (not Chromium).

Start non-headless puppeteer session in Windows 10 like this:
`taskkill.exe /f /im chrome.exe && node non-headless-chrome.js`

Another chrome.exe instances must not be running when starting puppeteer, otherwise:
`UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!`

**Comment by markosii** [comment]
I confirm, I have the same issue

I did :  `npm i --save puppeteer`

And then ` node test.js`

I have this error : 

```
(node:18063) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/root/node_modules/puppeteer/.local-chromium/linux-543305/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

```

**Comment by aslushnikov** [comment]
@bmay2 is this still broken for you for pptr 1.2.0? We successfully launch headful pptr on travis, so must be some issue with missing packages.

**Comment by tz5514** [comment]
same issue with puppeteer 1.3.0 . already install dependencies in https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by agis** [comment]
@aslushnikov why is this closed?

**Comment by crimsonsoccer55** [comment]
Also having this issue

**Comment by alexeymatveevp** [comment]
I've installed all libraries in 
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

and still i'm having

```
(node:35) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/Launcher.js:285:14)
    at ChildProcess.helper.addEventListener (/node_modules/puppeteer/lib/Launcher.js:275:60)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dcurletti** [comment]
anyone able to figure out what the missing packages are in the troubleshooting docs that prevent it from running headful in docker?

**Comment by aslushnikov** [comment]
Everybody: make sure you run headful using `xvfb`: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci

**Comment by kjr247** [comment]
I'd love to get it working in aws lambdas. However I'm seeing this error.

**Comment by pgupt** [comment]
I was facing same problem on Windows. I made asar as false and it got successful.

`"build": {
        "asar":false,
}`
