### ISSUE TITLE
page.pdf() captures application before end of resize animation

### ISSUE THREAD

**Issue by tibdex** [puppeteer/puppeteer#1815]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Fedora 27
* URLs (if applicable): 
* Node.js version: 6.5.0

**What steps will reproduce the problem?**

```javascript
'use strict';

const puppeteer = require('puppeteer');

const inIsolatedSession = ({action, dimensions, url}) =>
  puppeteer.launch().then(browser =>
    browser
      .newPage()
      .then(page =>
        Promise.resolve()
          .then(() => page.setViewport(dimensions))
          .then(() => page.goto(url, {waitUntil: ['networkidle0']}))
          .then(() => action(page))
      )
      .then(result => browser.close().then(() => result))
  );

const dimensions = {height: 800, width: 800};
const url = 'https://youtube.com';

[
  page =>
    page.pdf(
      Object.assign(
        {
          pageRanges: '1',
          path: 'test.pdf',
          printBackground: true,
        },
        dimensions
      )
    ),
  page => page.screenshot({path: 'test.png'}),
].forEach(action => {
  inIsolatedSession({
    action,
    dimensions,
    url,
  });
});
```

**What is the expected result?**

The PDF and PNG file content should _look the same_.

**What happens instead?**

Here is the PNG:

![PNG](https://user-images.githubusercontent.com/6574550/35011909-d6c5d6d2-fad5-11e7-9afc-a3e15ae24369.png)

And [here](https://github.com/GoogleChrome/puppeteer/files/1636769/test.pdf) is the PDF that looks like this:

![PDF](https://user-images.githubusercontent.com/6574550/35011948-fa70ff58-fad5-11e7-8542-394f97fabc24.png)

The PNG is what I expect: the application is centered in the middle of the screen.
In the PDF however, the application was captured in the middle of a resize animation, leading to a shifted content.

When enabling the debug output, I can see this:

```
puppeteer:session SEND ► {"id":13,"method":"Page.printToPDF","params":{"landscape":false,"displayHeaderFooter":false,"headerTemplate":"","footerTemplate":"","printBackground":true,"scale":1,"paperWidth":8.333333333333334,"paperHeight":8.333333333333334,"marginTop":0,"marginBottom":0,"marginLeft":0,"marginRight":0,"pageRanges":"1"}} +3ms
puppeteer:session ◀ RECV {"method":"Page.frameResized","params":{}} +319ms
puppeteer:session ◀ RECV {"method":"Page.frameResized","params":{}} +0ms
puppeteer:session ◀ RECV {"id":13,"result":{"data": ... PDF content ...
```

So, even though the viewport was already the right one (see call to `page.setViewport(dimensions)` above), the `Page.frameResized` event was still fired just before triggering the PDF export, probably not letting enough time to the application to finish its resize animation.

Is this a problem upstream in Chromium or can it be fixed in Puppeteer?

Thanks for your help!

**Comment by tibdex** [comment]
This issue is different than #1751 because here, even if I wait several seconds for the application to settle before calling `page.pdf()`, the method call will trigger a `Page.frameResized` event and grab a PDF quickly after it. I have no control on the delay between this resize event and the PDF generation. Thus, I cannot use `requestAnimationFrame` or `requestIdleCallback` as suggested in the other issue.

**Comment by RyM934** [comment]
I believe I'm seeing this issue as well. I have a debounce delay handler on window resize event for an expensive canvas redraw and exporting to pdf using puppeteer doesn't give any options for delaying creating of the pdf after the resize event that occurs in the pdf() method of page. Launching with a SloMo delay doesn't seem to have an effect in this instance either. Did you ever come up with a good workaround @tibdex?

**Comment by tibdex** [comment]
Not a *good* workaround but [I hardcode the width and height of `<body>`](https://github.com/activeviam/browser-based-export/blob/e5ce9e287367ed9773136fdc951c906d5e527fb8/packages/browser-based-export/src/export.js#L150-L161) so that the layout doesn't change when calling `page.pdf()`.

**Comment by RyM934** [comment]
Ah okay. I may try something similar. Thank you!

**Comment by charIeszhao** [comment]
So it's 2019 now, do we have a better solution rather than a "not so good workaround"? 
I'm having the same issue. I have a complex chart in the page and it will redraw the canvas whenever a window resize happens. No matter how I changed the PDF page format, the size of the chart in the export PDF is always fixed, as the PDF is generated before the canvas redraw completes.

**Comment by eldair** [comment]
No news on this?

**Comment by akamicah** [comment]
This is still definitely an issue in 10.1.0
