### ISSUE TITLE
Expose redirect chain for requests

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#1816]
The `request.redirectChain()` should return all the requests that are a part of the redirect chain for the `request`.

```js
const response = await page.goto('http://google.com');
const requests = response.request().redirectChain();
for (const request of requests)
  console.log(request.url());
```

This was requested a few times, e.g. https://github.com/GoogleChrome/puppeteer/issues/1708.

**Comment by amprew** [comment]
@aslushnikov - I think this would be interesting for me to work on. I guess a proposed solution would be to append to a public/private redirection chain variable on the request object each time a redirect is triggered. Then return it from `redirectChain()` or just make it accessible? Unless this redirectChain is available already via the devtools protocol API?
