### ISSUE TITLE
headerTemplate and footerTemplate doesn't work in pdf export

### ISSUE THREAD

**Issue by kosbr** [puppeteer/puppeteer#1822]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0 (npm)
* Platform / OS version: ubuntu
* URLs (if applicable):
* Node.js version: v7.9.0

**What steps will reproduce the problem?**
Open some page, for example google.com and export it to pdf like this:

    await page.pdf({
        path: outPath,
        format: 'A4',
        headerTemplate: '<b>Hello world<b/>',
        footerTemplate: '<b>Some text</b>'
     });

**What is the expected result?**
I expected pdf pages with 'Some Text' footer on every page and 'Hello world' in header on every page.

**What happens instead?**
I got pdf without header and footers. Like the were not footerTemplate and headerTemplate options.

**Comment by saboya** [comment]
Set `displayHeaderFooter: true`, as [per documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions).

**Comment by mjschranz** [comment]
@saboya  @aslushnikov 

I personally have that option and it doesn't work. The following code does not show my footer template (simplified vs what I am actually doing):

```javascript
      await page.goto('https://google.com', {waitUntil: 'networkidle0'});

      page.pdf({
        displayHeaderFooter: true,
        footerTemplate: `
          <b>Test</b>
        `,
      }).then((buffer) => {
        resolve(buffer);
      });
```

Edit: Upon further inspection it looks like this only works when providing a format like `A4` and the default of `Letter` doesn't work. This likely should be documented.

Thing is it still doesn't seem to want to generate my custom footer. When passing the following options I get nothing displayed on the page.

```
{
  displayHeaderFooter: true,
  footerTemplate: `
      <span class="pageNumber"></span>/<span class="totalPages"></span>
  `,
  format: 'A4'
}
```

**Comment by tongjun741** [comment]
@mjschranz You need set margin-top and margin-bottom. See https://github.com/GoogleChrome/puppeteer/issues/1853

**Comment by MJPA** [comment]
@mjschranz if it's what I've just experienced, the text is there, just that small you can barely see it...

**Comment by skhilliard** [comment]
I am using puppeteer 1.5.0 and am also experiencing issues with headers/footers not displaying for PDF generation.  Any suggestions?

`puppeteer.launch().then((browser) => {
	browser.newPage().then((page) => {
		page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' }).then(() => {
			page.pdf({
				margin: {
					top: '20px',
					bottom: '20px'
				},
				printBackground: true,
				displayHeaderFooter: true,
				headerTemplate: `<div style="font-family: 'Helvetica', sans-serif; font-size: 14px"><span>This is a test</span></div>`
			}).then((result) => {
				browser.close();
				resolve(result);
			})`

**Comment by skhilliard** [comment]
I am using puppeteer 1.5.0 and am also having problems getting headers/footers to work with PDF generation.  Here is an example:


`puppeteer.launch().then((browser) => {

	browser.newPage().then((page) => {

		page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' }).then(() => {

			page.pdf({

				margin: {

					top: '20px',

					bottom: '20px'

				},

				printBackground: true,

				displayHeaderFooter: true,

				headerTemplate: `<div style="font-family: 'Helvetica', sans-serif; font-size: 14px"><span>This is a test</span></div>`

			}).then((result) => {

				browser.close();

				resolve(result);

			})


`

**Comment by chinchang** [comment]
Confirmed, it renders the text with 0 `font-size` by default. Set it with CSS, and it works! Thanks @MJPA .

**Comment by danlaush** [comment]
@chinchang out of curiosity, how did you figure that out? I was having the same issue but wasn't sure how to troubleshoot, since you just have a PDF.

**Comment by HelloLangYaJun** [comment]
或者你应该设置margin?

**Comment by HelloLangYaJun** [comment]
maybe  you  should set margin?

**Comment by truesolarflame** [comment]
@danlaush You can open the PDF in a browser and right-click and inspect the header or footer to see the font-size and other CSS applied. 

I also found that, in addition to the font-size, the setting of top and bottom margins (as @mjschranz said and tongjun741 repeated) was a requirement to actually see headers and footers since they were covered up and could not be seen otherwise.

**Comment by nitin2711** [comment]
g

**Comment by daryllman** [comment]
> @saboya @aslushnikov
> 
> I personally have that option and it doesn't work. The following code does not show my footer template (simplified vs what I am actually doing):
> 
> ```js
>       await page.goto('https://google.com', {waitUntil: 'networkidle0'});
> 
>       page.pdf({
>         displayHeaderFooter: true,
>         footerTemplate: `
>           <b>Test</b>
>         `,
>       }).then((buffer) => {
>         resolve(buffer);
>       });
> ```
> 
> Edit: Upon further inspection it looks like this only works when providing a format like `A4` and the default of `Letter` doesn't work. This likely should be documented.
> 
> Thing is it still doesn't seem to want to generate my custom footer. When passing the following options I get nothing displayed on the page.
> 
> ```
> {
>   displayHeaderFooter: true,
>   footerTemplate: `
>       <span class="pageNumber"></span>/<span class="totalPages"></span>
>   `,
>   format: 'A4'
> }
> ```

Hey!! How did you fix this in the end? Can i see the part of the code where u manage to get the custom page number footer layout printed @mjschranz

**Comment by mauriciogracia** [comment]
This is how it worked for me:
-   DisplayHeaderFooter = **true**,
-   Use **inline css** for your header and footer
-   Specify **marginOptions**

Below is the .NET example but it can help you in your javascript/typescript side

        private static string cssHeaderStyle = "<style> h1 { font-size:20px; margin-left:50px;}</style>";

        private static PdfOptions pdfOptions = new PdfOptions {
            Format = PaperFormat.Letter, //PaperFormat.A4....
            PrintBackground = true,
            Landscape = false,
            DisplayHeaderFooter = true,
            HeaderTemplate = cssHeaderStyle + "<h1>This is a Header example</h1>",
            FooterTemplate = cssHeaderStyle + "<h1>This is a Footer example</h1>",
            MarginOptions = new MarginOptions { Top = "100px", Bottom = "200px", Right = "30px", Left = "30px" } 
        };

	using (browser = await PrepareHeadlessBrowser(true))
	using (var page = await browser.NewPageAsync())
	{
		WaitUntilNavigation[] waitUntilOptions = new WaitUntilNavigation[] { WaitUntilNavigation.DOMContentLoaded };


		if(customViewport)
		{
			await page.SetViewportAsync(new ViewPortOptions { Height = 2000, Width = 160, DeviceScaleFactor = 2 });
		}

		//Timeout = 0 disables the timeout setting
		await page.SetContentAsync(content, new NavigationOptions { WaitUntil = waitUntilOptions, Timeout = 0 });
		await page.PdfAsync(Path.Combine(outputDirectory, outputFileName), pdfOptions);
	}

**Comment by crobinson42** [comment]
Here's my solution - you must set the top and/or bottom margins for the footer to show.

```
// node.js

await page.pdf({
        displayHeaderFooter: true,
        footerTemplate: `
          <div style="color: lightgray; border-top: solid lightgray 1px; font-size: 10px; padding-top: 5px; text-align: center; width: 100%;">
            <span>This is a test message</span> - <span class="pageNumber"></span>
          </div>
        `,
        format: 'A4',
        margin: {
          bottom: 70, // minimum required for footer msg to display
          left: 25,
          right: 35,
          top: 30,
        },
        printBackground: true,
      })
```

**Comment by luc-anise** [comment]
This seems to be broken again in version 2.0.0. @crobinson42 Your solution is not working for me with A4 page size or letter.

```
const pdf = await page.pdf({
      displayHeaderFooter: true,
      footerTemplate: `
        <div style="color: lightgray; border-top: solid lightgray 1px; font-size: 10px; padding-top: 5px; text-align: center; width: 100%;">
          <span>This is a test message</span> - <span class="pageNumber"></span>
        </div>
      `,
      format: 'Letter',
      margin: {
        bottom: 70, // minimum required for footer msg to display
        left: 25,
        right: 35,
        top: 30
      },
      printBackground: true
    });

    browser.close();

    await fs.writeFileSync(filepath, pdf);
```

**Comment by crobinson42** [comment]
@z6tanker it's still working fine for me in puppeteer@2.0.0 - you must have something else going on?

**Comment by luc-anise** [comment]
@crobinson42 I managed to fix it. turns out if you set the page margins using `@page` in your css it will not show the page numbers. Hope this helps someone! Also `Format: letter` works now.

**Comment by pwuertz** [comment]
Another observation: When I try styling the header/footer font-size with `pt` units, regular header/footer text shows up fine, but the page numbers are blank. When using font-size `px` units, page numbers are working ^^.

I'm not seeing any dependency on the `@page` css or `format` setting on my system. Maybe the thing that triggers the page number bug varies from version to version...

**Comment by baldaniyamahesh** [comment]
pdf header how to set image in pdf services any one idea ??
 headerTemplate: `<span style="font-size: 30px; width: 200px; height: 200px; background-color: black; color: white; margin: 20px;"> <img src="' . base_url() . 'https://xyz/02.png" alt="not work"/></span>`,
it's not work for me

**Comment by GreatAuk** [comment]
> pdf header how to set image in pdf services any one idea ??
> headerTemplate: `<span style="font-size: 30px; width: 200px; height: 200px; background-color: black; color: white; margin: 20px;"> <img src="' . base_url() . 'https://xyz/02.png" alt="not work"/></span>`,
> it's not work for me

try base64

**Comment by hxlnt** [comment]
> Another observation: When I try styling the header/footer font-size with `pt` units, regular header/footer text shows up fine, but the page numbers are blank. When using font-size `px` units, page numbers are working ^^.

Just traced my bug down to this issue as well. An inline CSS declaration of `font-size: 1rem` was being rendered as `font-size: 1px`, so I was seemingly getting no text. Looks like regardless of what unit is specified, `px` units are used. :(

**Comment by marcvleeuwen** [comment]
# My Implementation
- Header: 2 columns
- Footer: 1 column with centred text

```TypeScript
// create a new page  
const page = await browser.newPage();

// set your html as the pages content
await page.setContent(html, {
    waitUntil: 'networkidle2' // waits until no more than 2 requests happen within 500ms
});
await page.evaluateHandle('document.fonts.ready');
await page.screenshot();

// create a PDF buffer
await page.pdf(
  {
    format: 'a4',
	displayHeaderFooter: true,
	headerTemplate: headerTemplate,
	footerTemplate: footerTemplate,
	margin: { top: 100, bottom: 60 }
  }
);
```

```TypeScript
const headerTemplate = `<div style="display: inline-block; width: 75%; margin: 0 2cm">
                            <img style="height: 50px;" src="${LogoBase64}" />  
                            <div style="float: right; font-size: 7pt; text-align: right;">${AddressInfo}</div>
                        </div>`
const footerTemplate = `<div style="margin: 0 2cm; width: 75%; font-size: 7px; text-align: center;">${Disclaimer}</div>`;
```

# FINDINGS
* Only use inline styles
* To get all elements to display on the same line use `display: inline-block`
* Position using `float: position`
* Apply `font-size` since the default is `0px`
* RECOMMENDED: minimum margin size is `60`
* RECOMMENDED: page format set to `a4`
* Margin size determines the amount of displayable space for the header and footer
	* NOTE: This does not position the elements
* NOTE: Margin is double the content size
	* image = 50px
	* margin = 100px
	* Not sure how this scales
* Don't use async data
	* image is encoded as base54 instead of the CDN link
* Use `margin` tag to apply additional margins for positioning
