### ISSUE TITLE
Documentation improvement: add foreign charset support to docker troubleshooting guide

### ISSUE THREAD

**Issue by Glennvd** [puppeteer/puppeteer#1824]
In the troubleshooting.md document we give some pointers on how to run puppeteer in docker on a debian image. This works great until you have to start working with foreign character sets. 

Installing 5 apt-get font packages can cover the majority of these issues, namely fonts-ipafont-gothic, fonts-wqy-zenhei, fonts-thai-tlwg, fonts-kacst, ttf-freefont. Installing these gives us support for Chinese, Japanese, Arabic, Hebrew, Thai and a few others.

Can we add this to the documentation somewhere? 

Supported character sets after installing these https://i.imgur.com/sH1Gkvz.jpg

**Comment by ebidel** [comment]
Yep, we should not this. 

Do you want to submit a PR that updates https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker? I think a commented out explanation + command would be great.
