### ISSUE TITLE
Lubutu + X2go + Puppeteer : When X2go is closed, puppeteer runs slowly

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#1827]
I am running some visual process with puppeteer on Lubuntu server.

When I have the x2go windows client opened to supervise it, process is quick.

When I do close my x2go windows client, proccesss still runs but it is like 20 times slower.

`    lxsession -s Lubuntu -e LXDE`

Maybe it is not Puppeteer related but more x2go. Any idea ?

**Comment by aslushnikov** [comment]
@yarekc symptoms feel like a process prioritization issue. I can't say more since I'm not familiar with x2go / lubuntu.

Closing this since it seems to be an environment issue rather then a pptr issue. Please let me know if you think we can be somehow helpful.
