### ISSUE TITLE
PrintToPDF is not implemented undefined

### ISSUE THREAD

**Issue by vermauv** [puppeteer/puppeteer#1829]
### Steps to reproduce

**Environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Mac OS v10.12.6
* Node.js version: v8.7.0

**What steps will reproduce the problem?**
```javascript
const puppeteer = require('puppeteer');
(async function() {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
    await page.setViewport({width: 1024, height: 880});
    await page.goto('https://www.google.com', {"waitUntil" :'networkidle2'}).catch(function() {
        console.log('Error while loading up the url.');
    });
    await page.pdf({path: './file.pdf', format: 'A4', printBackground: true});
    // .catch(function () {
    //
    //     console.log('Error creating pdf.');
    // });
    browser.close();
})();
```

**expected result:**
No errors, Pdf generated

**What happens instead?**
(node:65423) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.printToPDF): PrintToPDF is not implemented undefined

**Comment by vermauv** [comment]
Found a reply by the owner in #830, suggesting to change the headless to true for pdf generation, hence closing the issue.

**Comment by cornelius-dol** [comment]
Turning off headless mode is not a solution; (a) it prevents one from debugging your script, and (b) as of Chrome 83, it doesn't work.

**Comment by afshawnlotfi** [comment]
Loading extension only works when headless is set to false. And at the same time I need to set headless to true for PDF
