### ISSUE TITLE
keep track of opened popups and (maybe optionally) close them when page.close() is called

### ISSUE THREAD

**Issue by Janpot** [puppeteer/puppeteer#1830]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.0.0
* Platform / OS version: all
* URLs (if applicable):
* Node.js version: all

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. open a page that opens a popup
2. close the page through `page.close()`
3. observe the `browser.targets()`

**What is the expected result?**

No leftover targets created by the page, or at least a way of them closing automatically

**What happens instead?**

a target for the popup stays open

I'd suggest to keep track of all targets created by the page and closing them when `page.close()` is called. or maybe with a `page.close(closeChildPages)`.

**Comment by Janpot** [comment]
Ok, been experimenting a bit more:

```js
const browser = await puppeteer.launch({
  headless: true,
  ignoreDefaultArgs: true,
  args: puppeteer.defaultArgs().filter(arg => arg !== '--disable-popup-blocking')
});
```

This seems to only work when `headless: false`. So I'm assuming this is a bug in headless?

So I started looking into rolling my own popup blocker by using the `targetcreated` event but there doesn't seem to be any info about the opener of the target. Looking at the devtools protocol for [`TargetInfo`](https://chromedevtools.github.io/devtools-protocol/1-3/Target#type-TargetInfo) it seems that it has an `openerId` but that doesn't seem to be present on the `target._targetInfo` that is passed to that event handler.

Assuming this is a property from a future chromium version, maybe you can add a `.opener()` to the `Target` class which gives you the page that belongs to `openerId`?

A workaround that looks like it's going to work for my use case:

```js
browser.on('targetcreated', async target => {
  if (target.url() !== 'about:blank') {
    console.log(`closing popup: ${target.url()}`);
    try {
      const page = await target.page();
      await page.close();
    } catch (e) {}
  }
});
```

But this feels a bit like a hack, I'd rather like to do:

```js
browser.on('targetcreated', async target => {
  try {
    const opener = await target.opener();
    if (opener) {
      console.log(`closing popup: ${opener.url()}`);
      await opener.close();
    }
  } catch (e) {}
});
```

**Comment by Janpot** [comment]
Well, that didn't work 100%...

Version 2 of my _poor man's popup blocker_, in case anyone is stumbling on the same problem:

```js
const mainTargets = new Map();
browser.on('targetcreated', async target => {
  if (target.url() !== 'about:blank') {
    // we are sure this wasn't created by calling `newPage` so this can be closed
    try {
      const page = await target.page();
      await page.close();
    } catch (e) {}
    return;
  }

  // let's wait a moment and see if the target gets registered by the main program
  // If it's not registered, it means it's not create by the program
  setTimeout(async () => {
    if (mainTargets.has(target._targetId)) {
      return;
    }
    try {
      const page = await target.page();
      await page.close();
    } catch (e) {}
  }, 2000);
});

async function doSomething (url, something) {
  const page = await browser.newPage();
  // register the target
  const target = page.target();
  mainTargets.set(target._targetId, target);
  try {
    await page.goto(url);
    return await something(page);
  } finally {
    // unregister the target
    mainTargets.delete(target._targetId);
    await page.close();
  }
}

await doSomething('http://shady-website.com/', async page => {
  // do stuff with the page here
});
```

**Edit:**
🤦‍♂️ Or I could ofcourse do:
```js
await page.evaluateOnNewDocument(() => {
  window.open = () => null;
});
```

**Comment by aslushnikov** [comment]
> Assuming this is a property from a future chromium version, maybe you can add a .opener() to the Target class which gives you the page that belongs to openerId?

@Janpot makes perfect sense; please feel free to send a PR for this.
