### ISSUE TITLE
NFR: force IP on page.goto

### ISSUE THREAD

**Issue by HanXHX** [puppeteer/puppeteer#1831]
## New feature request: force IP on page.goto

In case of [blue/green deployment](http://searchitoperations.techtarget.com/definition/blue-green-deployment), I would like to test "mywebsite.com" on other IP (next future release is 2.2.2.2).

The dirty hack should edit `/etc/hosts`...

```
                  +-----------------+
                  |                 |
                  |  mywebsite.com  |
                  |                 |
                  +-----------------+
+-----------+        Production
| Puppeteer |        1.1.1.1
+-----+-----+
      |
      |           +-----------------+
      |           |                 |
      +---------> |  mywebsite.com  |
                  |                 |
                  +-----------------+
                   Future Production
                   2.2.2.2
```

Example:

```javascript
let res = await page.gogo("https://mywebsite.com", {ip: "2.2.2.2"});
```

**Comment by aslushnikov** [comment]
@HanXHX so there are a few options for this:
1. on the page level, you can enable [request interception](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue) and organize a per-page proxy
1. on the browser level, you can use [proxy](https://github.com/GoogleChrome/puppeteer/blob/master/examples/proxy.js) and forward requests to whatever ip you want
1. and yes, on the OS level, you can do `/etc/hosts`

I'd recommend (2) as the most reliable option.

**Comment by HanXHX** [comment]
Hi @aslushnikov,

1. Request interception doesn't work with all certificates (#1159)
2. I don't find any proxy/project who can help me in this case (works both on HTTP and HTTPS). Do you have any tip? (or a solution like https://curl.haxx.se/libcurl/c/CURLOPT_RESOLVE.html)
3. Dirty... (need root)

**Comment by jots** [comment]
This would be *super* handy for testing site migrations before making the dns change.  screenshot pages on the 2 servers and compare them.

Not sure how the proxy solution works, would we need to create a proxy server that knows how to map domains to new IPs?  Would be much easier to use the syntax @HanXHX proposes:
`page.gogo("https://mywebsite.com", {ip: "2.2.2.2"});`

**Comment by aslushnikov** [comment]
> 1. Request interception doesn't work with all certificates (#1159)

@HanXHX I'm sorry, this is indeed the case. It should be fixed as we complete refactoring of network stack on the chromium side. cc @caseq

> 2. I don't find any proxy/project who can help me in this case (works both on HTTP and HTTPS). Do you have any tip?

I'd try implementing it manually; we've implemented a [small HTTP server](https://github.com/GoogleChrome/puppeteer/blob/master/test/server/SimpleServer.js) for our tests and it wasn't very involved.

> 3. Dirty... (need root)

You can probably use some containerization solution to make this more manageable.

> Not sure how the proxy solution works, would we need to create a proxy server that knows how to map domains to new IPs?

@jots yes, there should be a manual configuration defining routing rules.

> Would be much easier to use the syntax @HanXHX proposes

The suggested API falls outside of the scope of the project; I'd suggest using third-party proxies for the task.

**Comment by benjaminpwarren** [comment]
The `host-rules` argument appears to solve this for me:

```  
const browser = await puppeteer.launch({
  args: [
    '--host-rules=MAP mysite.com.au 123.456.789.012,MAP mysite2.com.au 123.456.789.012'
  ],
  ignoreHTTPSErrors: true
})
```

**Comment by Alex-Bogdanov** [comment]
> '--host-rules=MAP mysite.com.au 123.456.789.012,MAP mysite2.com.au 123.456.789.012'

@benjaminpwarren God bless you! I've scoured all through the internet for that kind solution for 2 days. Just needed to specify some DNS mapping for Chromium in order to fake nonexistent host name in browser redirected to a server running on my localhost. But it seems it doesn't apply in the `headless` mode=(

**Comment by uncoseason** [comment]
[hosts-group](https://www.npmjs.com/package/hosts-group) 
maybe it helps.
