### ISSUE TITLE
Special Characters in CSS Selector - non-valid selector error

### ISSUE THREAD

**Issue by ashoon** [puppeteer/puppeteer#1832]
on the page I'm trying to produce a click event - when I use both Chrome and FF my CSS Selector is 

'#\38 02800740321'

I assume the \38 is a special character however Puppeteer throws this error DOMException: Failed to execute 'querySelector' on 'Document': '#&802800740321' is not a valid selector.

**Comment by vc1** [comment]
'#\\\38 02800740321'

---

'\38' == '\3' + '8'
'' == '\3'
```html
<div id="">
  x
</div>
```

```javascript
document.querySelector('#\3') // => DOMException
document.querySelector('#\\3') // => <div>...</div>
```

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

> To match ID or selectors that do not follow the CSS syntax (by using a colon or space inappropriately for example), you must escape the character with a back slash. As the backslash is an escape character in JavaScript, if you are entering a literal string, you must escape it twice (once for the JavaScript string, and another time for querySelector):
```
<div id="foo\bar"></div>
<div id="foo:bar"></div>

<script>
  console.log('#foo\bar');               // "#fooar" (\b is the backspace control character)
  document.querySelector('#foo\bar');    // Does not match anything

  console.log('#foo\\bar');              // "#foo\bar"
  console.log('#foo\\\\bar');            // "#foo\\bar"
  document.querySelector('#foo\\\\bar'); // Match the first div

  document.querySelector('#foo:bar');    // Does not match anything
  document.querySelector('#foo\\:bar');  // Match the second div
</script>
```
