### ISSUE TITLE
troubleshooting: document running on alpine

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#1835]
From @jamrizzi on https://github.com/GoogleChrome/puppeteer/issues/379#issuecomment-358215741, we should add notes to troubleshooting.md to help users.

## Running on Alpine 

The [newest Chromium package](https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium) of Chrome supported on Alpine is 63, which was the version of Chrome bundled with [Puppeteer v0.11.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v0.11.0).

Example Dockerfile:

```
FROM node:9-alpine

# Installs latest Chromium (63) package.
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      nss@edge

# Help prevent zombie chrome processes
ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init

COPY . /app/
WORKDIR app

# Install deps for server.
RUN yarn

# Skip downloading Chromium when installing puppeteer. We'll use the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Use Puppeteer 0.11.0 b/c it bundles Chromium 63.
RUN yarn add puppeteer@0.11.0

RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app

# Run user as non privileged.
USER pptruser

EXPOSE 8080

ENTRYPOINT ["dumb-init", "--"]
CMD ["yarn", "start"]
```

Launching Chrome: 

```js
const browser = await puppeteer.launch({
  executablePath: '/usr/bin/chromium-browser',
  args: ['--disable-dev-shm-usage']
});
```

**Comment by tuanh118** [comment]
How do you use the latest puppeteer@1.0.0?

I tried changing to 1.0.0 but it didn't work

**Comment by clayrisser** [comment]
The latest version of puppeteer is not supported by the latest version of chrome alpine supports. Sorry, it's just the way it is right now.

**Comment by CoreyCole** [comment]
@ebidel as of 3/13/18 it is now Chrome version 64.0.3282.168-r0

It looks like puppeteer [v0.13.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v0.13.0) was bundled with Chromium 64.0.3264.0 (r515411). I'm assuming this should work even though the versions don't exactly match, given that the apline version is higher than the bundled version? Going to try now

EDIT: nevermind, assumption confirmed in [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/de82b87cfa1c637787a09b90266318905ae16f42/docs/troubleshooting.md#running-on-alpine)

**Comment by fadc80** [comment]
What I think it's a bit weird here is we have to install Chrome twice. Why would we use Puppeteer if we cannot get its latest supported Chrome version? What about just sticking to the Chrome version installed via package manager? This way the test code could just assume chrome is installed.

**Comment by clayrisser** [comment]
@fadc80 chrome doesn't install twice if you use set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`
