### ISSUE TITLE
How to get text content on XPath expression

### ISSUE THREAD

**Issue by sonyarianto** [puppeteer/puppeteer#1838]
Hi,
I have like this.
```
var content = await page.$x("//span[@class='property-number']");
```
How to get text content inside that expression?

I already try with this, but not working.

```
var content = await page.evaluate(el => el.innerHTML, await page.$x("//span[@class='property-number']"));
```

Any help are appreciated.

**Comment by ashleyR94** [comment]
+1 Im also struggling to return text using a valid, console tested, xpath selector. 
Docs arent very in-depth about $x limitations

**Comment by ashleyR94** [comment]
This is the closest i have been able to get with my understanding
`const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('https://example.com/');

const title = await page.$x("//h1");
let text = await title[0].getProperty('textContent');
console.log(text)

await browser.close();`

**Comment by sonyarianto** [comment]
@ashleyR94 thanks, I will try your code on my code, will tell you again if it is works.

**Comment by sonyarianto** [comment]
@ashleyR94 
I tried your code but it return like this.

```
JSHandle {
  _context:
   ExecutionContext {
     _client:
      CDPSession {
        domain: null,
        _events: [Object],
        _eventsCount: 19,
        _maxListeners: undefined,
        _lastId: 19,
        _callbacks: Map {},
        _connection: [Connection],
        _targetId: '64903FF4A83F3EC4A81333C7BA3DB5C5',
        _sessionId: '64903FF4A83F3EC4A81333C7BA3DB5C5:1' },
     _contextId: 2,
     _frameId: '64903FF4A83F3EC4A81333C7BA3DB5C5',
     _isDefault: true,
     _objectHandleFactory: [Function: bound createJSHandle] },
  _client:
   CDPSession {
     domain: null,
     _events:
      { 'Page.frameAttached': [Function],
        'Page.frameNavigated': [Function],
        'Page.frameDetached': [Function],
        'Runtime.executionContextCreated': [Function],
        'Runtime.executionContextDestroyed': [Function],
        'Runtime.executionContextsCleared': [Function],
        'Page.lifecycleEvent': [Function],
        'Network.requestWillBeSent': [Function: bound _onRequestWillBeSent],
        'Network.requestIntercepted': [Function: bound _onRequestIntercepted],
        'Network.responseReceived': [Function: bound _onResponseReceived],
        'Network.loadingFinished': [Function: bound _onLoadingFinished],
        'Network.loadingFailed': [Function: bound _onLoadingFailed],
        'Page.loadEventFired': [Function],
        'Runtime.consoleAPICalled': [Function],
        'Page.javascriptDialogOpening': [Function],
        'Runtime.exceptionThrown': [Function],
        'Security.certificateError': [Function],
        'Inspector.targetCrashed': [Function],
        'Performance.metrics': [Function] },
     _eventsCount: 19,
     _maxListeners: undefined,
     _lastId: 19,
     _callbacks: Map {},
     _connection:
      Connection {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _url: 'ws://127.0.0.1:61750/devtools/browser/875ddf21-b116-44f3-8f3d-99e2b2c3b726',
        _lastId: 22,
        _callbacks: Map {},
        _delay: 0,
        _ws: [WebSocket],
        _sessions: [Map],
        _closeCallback: [Function] },
     _targetId: '64903FF4A83F3EC4A81333C7BA3DB5C5',
     _sessionId: '64903FF4A83F3EC4A81333C7BA3DB5C5:1' },
  _remoteObject: { type: 'string', value: '12.792' },
  _disposed: false }
```

I saw the value is there on the `_remoteObject` things. How to get that?

**Comment by aslushnikov** [comment]
@sonyarianto the following should work:

```js
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('https://example.com/');

const title = await page.$x("//h1");
let text = await page.evaluate(h1 => h1.textContent, title[0]);
console.log(text)

await browser.close();
```

**Comment by sonyarianto** [comment]
@aslushnikov ohhhh great, you save my life :) thank you!

**Comment by amirsikandar694** [comment]
> @ashleyR94
> I tried your code but it return like this.
> 
> ```
> JSHandle {
>   _context:
>    ExecutionContext {
>      _client:
>       CDPSession {
>         domain: null,
>         _events: [Object],
>         _eventsCount: 19,
>         _maxListeners: undefined,
>         _lastId: 19,
>         _callbacks: Map {},
>         _connection: [Connection],
>         _targetId: '64903FF4A83F3EC4A81333C7BA3DB5C5',
>         _sessionId: '64903FF4A83F3EC4A81333C7BA3DB5C5:1' },
>      _contextId: 2,
>      _frameId: '64903FF4A83F3EC4A81333C7BA3DB5C5',
>      _isDefault: true,
>      _objectHandleFactory: [Function: bound createJSHandle] },
>   _client:
>    CDPSession {
>      domain: null,
>      _events:
>       { 'Page.frameAttached': [Function],
>         'Page.frameNavigated': [Function],
>         'Page.frameDetached': [Function],
>         'Runtime.executionContextCreated': [Function],
>         'Runtime.executionContextDestroyed': [Function],
>         'Runtime.executionContextsCleared': [Function],
>         'Page.lifecycleEvent': [Function],
>         'Network.requestWillBeSent': [Function: bound _onRequestWillBeSent],
>         'Network.requestIntercepted': [Function: bound _onRequestIntercepted],
>         'Network.responseReceived': [Function: bound _onResponseReceived],
>         'Network.loadingFinished': [Function: bound _onLoadingFinished],
>         'Network.loadingFailed': [Function: bound _onLoadingFailed],
>         'Page.loadEventFired': [Function],
>         'Runtime.consoleAPICalled': [Function],
>         'Page.javascriptDialogOpening': [Function],
>         'Runtime.exceptionThrown': [Function],
>         'Security.certificateError': [Function],
>         'Inspector.targetCrashed': [Function],
>         'Performance.metrics': [Function] },
>      _eventsCount: 19,
>      _maxListeners: undefined,
>      _lastId: 19,
>      _callbacks: Map {},
>      _connection:
>       Connection {
>         domain: null,
>         _events: [Object],
>         _eventsCount: 3,
>         _maxListeners: undefined,
>         _url: 'ws://127.0.0.1:61750/devtools/browser/875ddf21-b116-44f3-8f3d-99e2b2c3b726',
>         _lastId: 22,
>         _callbacks: Map {},
>         _delay: 0,
>         _ws: [WebSocket],
>         _sessions: [Map],
>         _closeCallback: [Function] },
>      _targetId: '64903FF4A83F3EC4A81333C7BA3DB5C5',
>      _sessionId: '64903FF4A83F3EC4A81333C7BA3DB5C5:1' },
>   _remoteObject: { type: 'string', value: '12.792' },
>   _disposed: false }
> ```
> 
> I saw the value is there on the `_remoteObject` things. How to get that?

This can be used to fetch the value.
console.log(text._remoteObject.value)
