### ISSUE TITLE
Chrome on Windows 10 will not start like this -> chrome --headless --disable-gpu

### ISSUE THREAD

**Issue by voleynik** [puppeteer/puppeteer#1839]
Hello friends:
Based on examples on the web I am trying to start Chrome in headless mode like below:
chrome --headless --disable-gpu

No process started as a result.

However when I start Chrome like this: 

chrome --headless --disable-gpu --remote-debugging-port=9222

it starts OK. Same goes for both regular chrome.exe in folder 
"C:\Program Files (x86)\Google\Chrome\Application\" and Chromium in "D:\apps\chromium" which I specifically installed because Puppeteer uses by default.
 By nature of my project I does not need "Headless Chrome" to run in debug mode.

Here is the question:

I this a bug and a feature?

Any help would be greatly appreciated.
Regards,
Vladimir.
vladimir.oleynikATmailDOTcom

**Comment by aslushnikov** [comment]
>Based on examples on the web I am trying to start Chrome in headless mode like below:
>chrome --headless --disable-gpu
>
>No process started as a result.

@voleynik the process gets started and then exits. 
The remote debugging protocol is the official way to control headless browser; alternatively, you can specify certain headless flags like `--screenshot` to perform simple actions. More on this [here](https://developers.google.com/web/updates/2017/04/headless-chrome#screenshots).
