### ISSUE TITLE
page.goto never return response

### ISSUE THREAD

**Issue by ggirodda** [puppeteer/puppeteer#1841]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: windows 10
* URLs (if applicable):
* Node.js version: 8.9.3

**What steps will reproduce the problem?**
A simple page.goto, it never get response. When I try with `headless: false` I see the page correctly loaded, but it never return a response, it always catch a 30s timeout exceeded when the page actually take a few seconds to completely load

_Please include code that reproduces the issue._

```
try {
await page.goto('https://www.expedia.fr/')
  console.log('done')
  return true
} catch (e) {
  console.log(e)
  return false
}

```
I also use those options because the website actually use a certificate type that will be ban by chrome :
```
{
  ignoreHTTPSErrors: true,
  args: [
	'--ignore-certificate-errors'
  ],
  // dumpio: true
  // headless: false
}
```
**What is the expected result?**
'done'

**What happens instead?**
Navigation Timeout Exceeded: 30000ms exceeded

**Comment by ovheurdrive** [comment]
It seems like your website takes a long time to reach the load event (which is the default one if you don't specify the waitUntil option.)
With this code, i have the done event you were expecting: 
```Javascript
 try {
    await page.goto("https://www.expedia.fr/", { waitUntil: "networkidle0", timeout: 60000 });
    console.log("done");
    return true;
  } catch (e) {
    console.log(e);
    return false;
  }
```

**Comment by ggirodda** [comment]
Ok, thank you very much, this solved my problem
