### ISSUE TITLE
Error: DOMException: play() can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by barmaglot92** [puppeteer/puppeteer#1843]
Hi i try to play video:
const videoElem = await page.$('#video');  (<video/>)
await videoElem.click();

but error cought:
Error: DOMException: play() can only be initiated by a user gesture.

also i try videoElem.play() and have the same err.

**Comment by JoelEinbinder** [comment]
I am having trouble reproducing this. My website code:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Website</title>
</head>
<body>
<video width="480" controls>
  <source
    src="https://www.w3schools.com/html/mov_bbb.ogg"
    type="video/ogg">
  Your browser doesn't support HTML5 video tag.
</video>
    <script>
      var video = document.querySelector('video');
      video.addEventListener('click', event => {
        video.play();
      }, false);
      </script>
</body>
</html>
```

My puppeteer code

```js
const p = require('puppeteer');
p.launch({ headless: false }).then(async browser => {
  const page = (await browser.pages())[0];
  page.on('console', console.log);
  await page.goto('http://localhost/the_video_page');
  await page.click('video');
});
```

Trying with headless true also works, although I had to pass some custom arguments so that I could hear the audio playing.

Can you share your html file? Thanks!

**Comment by barmaglot92** [comment]
Sorry its my local problem, try to detect it. Thank you very much!

**Comment by Lange** [comment]
I'm having this issue as well. @barmaglot92, how did you end up resolving it?

**Comment by Lange** [comment]
Ah, I see. My element had some `<video>` elements within a ShadowDOM, all I needed to do was have call `.click()` on the element which contained that shadow root, and then I was able to play the video files without receiving this error.
