### ISSUE TITLE
Slow loading times with headless and inconsistant results between VM host and guest

### ISSUE THREAD

**Issue by forvais** [puppeteer/puppeteer#1846]
In attempt to reproduce a slow headless Puppeteer that I could hopefully come to a solution with, I ended up with results that leave me more confused than I already was. I've installed the same version of Puppeteer `1.0.0` and Node `7.6.0` on both my main computer and VM (installed on the main computer), both running `Windows 7 (x64)`.

My **objective** is to be able to have headless Puppeteer as an option.

I am having Puppeteer go to a simple express server that routes to a HTML page with a very minimal webpack bundle/chunk file. This process is repeated 10 times and gives an average load time as output:
```
const config = require('../config.js');
const { logger } = config;

(async () => {
    try {
        const headless = process.argv[2] === 'headless';
        const browser = await require('puppeteer').launch({ headless });
        const page = await browser.newPage();

        let timeTotal = 0;

        for (let i = 0; i < 10; i++) {
            const timeStart = (new Date()).getTime();
            await page.goto('http://192.168.1.31:3000');
            timeTotal += (new Date()).getTime() - timeStart;
        }

        logger.info(`Node ${process.version}`);
        logger.info('Puppeteer v1.0.0');
        logger.info(`Running Puppeteer ${headless ? 'Headless' : 'Full'}: ${timeTotal / 10}ms average load time.`)

        await browser.close();
    } catch (e) {
        logger.info(e);
    }
})()
```

**Results Main:**

Headless:
![khu0enuute6lfcmpdh8m5w](https://user-images.githubusercontent.com/1572440/35094974-d4c5c744-fbfb-11e7-9cc7-36e577092c22.png)

Full:
![P-knHwSKRkKp6SkvMeT-_w](https://image.prntscr.com/image/P-knHwSKRkKp6SkvMeT-_w.png)

**Results VM:**

Headless:
![F21xVgnxSTqRLu7xd4SZqA](https://image.prntscr.com/image/F21xVgnxSTqRLu7xd4SZqA.png)

Full:
![E80kH7JQQgGd-9VjuP00_g](https://image.prntscr.com/image/E80kH7JQQgGd-9VjuP00_g.png)

Upgrading Node on my Main, unfortunately, doesn't seem to do much either:

Headless:
![3cE0LnqATXKfIR54-y19Cw](https://image.prntscr.com/image/3cE0LnqATXKfIR54-y19Cw.png)

Full:
![YSJMBY3jR2SynCv9S4u4xQ](https://image.prntscr.com/image/YSJMBY3jR2SynCv9S4u4xQ.png)

Why is the VM guest able to connect and load a web page faster than the VM host with the exact same equipment/tools?

Setting up a different UA is a commonly suggested solution but it hasn't helped me.

Any input would be very much appreciated, as at this point, I am extremely lost.

**Comment by TheCloudlessSky** [comment]
Does [this](https://github.com/GoogleChrome/puppeteer/issues/2391#issuecomment-382055246) work for you?

```
const browser = await puppeteer.launch({
  headless: true,
  args: [
    '--proxy-server="direct://"',
    '--proxy-bypass-list=*'
  ]
});
```

**Comment by forvais** [comment]
Sorry, I won't be at home until until 23rd. I'll test it when I get back. Thanks for posting a possible fix/workaround though!

**Comment by forvais** [comment]
Reintroducing the bug:  #2048, I can confirm:
```javascript
const browser = await puppeteer.launch({
  args: [
    '--proxy-server="direct://"',
    '--proxy-bypass-list=*'
  ]
});
```
is a valid fix. I'm returning to normal expected results.

Opening https://www.google.ca/ in headless now only takes 120-130ms, whereas without the fix, would take ~10763ms

@TheCloudlessSky Thank you very much!

**Comment by stevenvachon** [comment]
Why do we need these options to avoid long runtimes? Shouldn't they be default, then?
