### ISSUE TITLE
Writing Memory Leak tests using page.metrics

### ISSUE THREAD

**Issue by mithung** [puppeteer/puppeteer#1847]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version: v8.9.1

I am trying to write memory leak tests using puppeteer. I am relying on **_page.metrics()_** 

Steps :
1. Open page.
2. Perform some operation multiple times.
 For ex : 

```

async function recordMetrics (){
    let pMetrics = await page.metrics();
    metricsJson.push(pMetrics);
}
//my test case
it("Open and close Property", async () => {
        await recordMetrics();
        for (var i = 0; i < 10; i++) {
            let searchText = await page.$x('//*[@id="pySearchText"]');
            searchText[0].focus();
            await searchText[0].type("old: MyProp");
            searchText[0].press('Enter');
            let linkEle = await page.$x('//a[text()="MyProp"]');
            await linkEle[0].click();
            let closeButton = await page.$x('//*[@id="close"]');
            closeButton[0].click();
            console.log("property closed for " + (i + 1) + " time");
        }
        await recordMetrics();
 });

```    
I am getting PageMetrics as below 

{ Timestamp: 12445.979016,
      Documents: 8,
      Frames: 5,
      JSEventListeners: 245,
      Nodes: 4972,
      LayoutCount: 38,
      RecalcStyleCount: 156,
      LayoutDuration: 0.271560000002864,
      RecalcStyleDuration: 0.36548399998901,
      ScriptDuration: 1.55862199999683,
      TaskDuration: 3.36384199999702,
      JSHeapUsedSize: 22439904,
      JSHeapTotalSize: 63836160 }

My idea is to take difference of _JSHeapUsedSize_ before and after performing operation multiple times. 

I see in the documentation, it is mentioned as just number.

**_`JSHeapUsedSize <number> Used JavaScript heap size.`_**

I want to know whether it is the number of Bytes ??

**Comment by aslushnikov** [comment]
> I want to know whether it is the number of Bytes ??

@mithung Yes.

> I am trying to write memory leak tests using puppeteer. 

Also check out [`page.queryObjects`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagequeryobjectsprototypehandle) api, it might come handy when dealing with memory leaks.
