### ISSUE TITLE
Text missing from screenshot

### ISSUE THREAD

**Issue by ebbishop** [puppeteer/puppeteer#1848]
I'm using puppeteer to save and download images from markup & css sent to an express app by the browser. Express compiles the template, just inserting the POSTed markup into an html shell & gets the css locally (mounted on a docker volume).  

When I render the html & css directly in chrome, all text and other elements display as expected. The screenshot that is saved, however, is missing the text. 

When I leave out our styles, the text renders the same way in both local chrome & the image saved by puppeteer. 

Are there styles set behind the scenes? Something else that could account for the difference?

### Steps to reproduce
* Puppeteer version: 0.12.0
* Platform / OS version: docker/ubuntu
* Node.js version: 8

**What steps will reproduce the problem?**
index.js:

    app.post('/img', function (req, res) {
      const puppeteer = require('puppeteer');
      let css = [];
      let stylesheets = [];
      // 
      // separate out local stylesheets and read contents of the files
      // 
      css = req.body.stylesheets.filter(sheet => {
        return sheet.indexOf('https') === -1 && sheet.indexOf('http') === -1;
      });
      css = css.map(sheet => {
        return fs.readFileSync(path.join(__dirname, sheet));
      });
      // 
      // separate out external stylesheets (bootstrap, etc)
      // 
      stylesheets = req.body.stylesheets.filter(sheet => {
        return sheet.indexOf('https') > -1 || sheet.indexOf('http') > -1;
      });
      //
      // compile template with html & styles
      //
      app.render('img', {
        stylesheets: stylesheets,
        content: req.body.content,
        css: css
      }, function (err, html) {
        console.log('html\n', html);
        (async() => {
          const browser = await puppeteer.launch({args: ['--no-sandbox']});
          const page = await browser.newPage();
          await page.setViewport({width: 1300, height: 1200});
          //
          // load html to chrome
          //
          try {
            const loaded = page.waitForNavigation({
              waitUntil: 'load'
            });
            await page.setContent(html);
            await loaded
          } catch(err) {
            console.log(err);
            res.status(err.status).send('There was an error loading the page.');
          }
          //
          // save image
          //
          const filename = `${req.body.title}.png`;
          const filepath = path.join(__dirname, 'img', filename);
          try {
            await page.screenshot({ path: filepath });
            console.log(`${filename} saved`);
          } catch(err) {
            console.log(err);
            res.status(err.status).send('There was a problem saving the image.');
          }
          res.status(201).send(filename);
        })();
      });
    });

img.html (template):

    <!DOCTYPE html>
    <html>
    <head>
      <title>{{title}}</title>
      {{#stylesheets}}
      <link rel="stylesheet" type="text/css" href="{{{.}}}">
      {{/stylesheets}}
      {{#css}}
      <style type="text/css">
        {{{.}}}
      </style>
      {{/css}}
    </head>
    <body>
      {{{content}}}
    </body>
    </html>

3.

**What is the expected result?**
Without local styles:
<img width="705" alt="chrome-no-styles" src="https://user-images.githubusercontent.com/8210523/35105089-c290de6e-fc38-11e7-8502-48054fe0f491.png">

With local styles:
<img width="722" alt="chrome-with-styles" src="https://user-images.githubusercontent.com/8210523/35105103-cb0b417e-fc38-11e7-9e43-4b584235e860.png">

**What happens instead?**
Without local styles is as expected.

With local styles:
<img width="641" alt="puppeteer-with-styles" src="https://user-images.githubusercontent.com/8210523/35105122-d732ee84-fc38-11e7-9184-681678e281fa.png">

**Comment by vc1** [comment]
Is the font reason?

```javascript
const page = await browser.newPage(); 
await page.setContent(html);
// url => 'about:blank' ; document.domain => '';
// Fonts set in CSS can not be loaded If you use a relative path
```
