### ISSUE TITLE
Disabling "Chromium stopped this site from taking you to"...

### ISSUE THREAD

**Issue by sradu** [puppeteer/puppeteer#1850]
I'm seeing the error below on a valid redirect. Can this feature be disabled via Puppeteer?

![image](https://i.imgur.com/1vlhpk8.png)

**Comment by ebidel** [comment]
Can you provide a code snippet that repros this?

**Comment by sradu** [comment]
I'm afraid I can't. It happens on hm.se after entering payment information and tapping the place order button. They are using a third party payment processor that wants to redirect back to pp.hm.se.

I can provide a video if it helps.

**Comment by sradu** [comment]
This was probably fixed.
