### ISSUE TITLE
Support question - adding custom header panel to a page

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#1851]
I have this question on SO

https://stackoverflow.com/questions/48272314/add-control-panel-to-any-chrome-page-using-chrome-extension

when we launch Chrome with Puppeteer ( or with Selenium ), we get a banner/panel at the top that says:

> chrome is being controlled by automated test software

for example like so:

<img width="1214" alt="screenshot 2018-01-18 13 41 46" src="https://user-images.githubusercontent.com/11139560/35123090-c669b0de-fc55-11e7-9ab6-830fadd53744.png">

my question is - how do you do that? I have a Chrome Extension, and I'd really like to be able to create a banner / panel like that using my Chrome Extension.

**Comment by ORESoftware** [comment]
I read that this feature might be called an "infobar", but it seems to be deprecated:
https://developer.chrome.com/extensions/infobars

**Comment by ebidel** [comment]
This gets added because Puppeteer launches chrome with the `--enable-automation` flag:
https://peter.sh/experiments/chromium-command-line-switches/#enable-automation. AFAIK, you can't customize it as it's part of the browser UI.  It isn't part of the page for security reasons.

But you could inject the CSS/HTML into the page that you want to recreate something similar.

**Comment by ORESoftware** [comment]
yeah i just have this right now:

```js
    const div = document.createElement('div');
    div.innerHTML = '<b>foooooo</b>';
    document.body.prepend(div);
```

but I was hoping to use the infobar thing because it's not part of the page, but part of the chrome window, but oh well - one good thing about using <body> is that this API is unlikely to change, whereas something like infobars is always likely to change :/ thx

**Comment by ORESoftware** [comment]
maybe I can use the shadow DOM to minimize interference with the page, idk

**Comment by ebidel** [comment]
Yes definitely. And custom elements: `<info-bar>` ftw!
