### ISSUE TITLE
blank screenshot with demo code

### ISSUE THREAD

**Issue by benhalverson** [puppeteer/puppeteer#1852]
I think this is related to #1828
When I used the demo code to take a screenshot. I am getting a white screen instead of the actual website. It happens both locally and with the below link.

* Puppeteer version: 1.0
* Platform / OS version: osx 10.12.6
* URLs (if applicable): https://community.adaptlearning.org/demo2/index.html and localhost:9001
* Node.js version: 8.9.4, 9.2.0

**What steps will reproduce the problem?**

node app.js

```
const puppeteer = require('puppeteer');

(async () => {
    try {
    const browser = await puppeteer.launch({dumpio: true, args: ['--no-sandbox']});
    const page = await browser.newPage();

        await page.goto('https://community.adaptlearning.org/demo2/index.html');
        await page.screenshot({path: 'adaptdemo.png'});
        await browser.close();
    }
    catch(e) {
        console.log(`Error, ${e}`);
    }

})();
```

**What is the expected result?**
Screenshot of website with no errors.

**What happens instead?**

empty screenshot
I also get this message in the console. 
`[0118/135248.386202:ERROR:gpu_process_transport_factory.cc(1043)] Lost UI shared context.`
`DevTools listening on ws://127.0.0.1:49257/devtools/browser/3bb02c70-ae6d-4509-950d-698bc469182f`

**Comment by aslushnikov** [comment]
@benhalverson this is a fancy website that loads its data with xhr's. Use `networkidle0` event to wait for it to load.

The following works just fine for me on pptr 1.4.0:

```js
const puppeteer = require('.');

(async () => {
    try {
    const browser = await puppeteer.launch({dumpio: true, args: ['--no-sandbox']});
    const page = await browser.newPage();

        await page.goto('https://community.adaptlearning.org/demo2/index.html', {waitUntil: 'networkidle0'});
        await page.screenshot({path: 'adaptdemo.png'});
        await browser.close();
    }
    catch(e) {
        console.log(`Error, ${e}`);
    }

})();

```
