### ISSUE TITLE
Browser hang while executing code to  retrieve uncompressed response size

### ISSUE THREAD

**Issue by vijeshv** [puppeteer/puppeteer#1856]
I have tried the work around to get uncompressed respose size. But found  page not loading after opening browser. a kind of browser hanging behaviour. 
pls find script below.	

const browser = await puppeteer.launch({ headless:false,slowMo:250});
	 const page = await browser.newPage();
	 
	const p=await browser.pages();
	
const resources = {};

page.client.on('Network.dataReceived', (event) => {
  const request = page.networkManager.requestIdToRequest.get(event.requestId);
  if (request && request.url().startsWith('data:')) {
    return;
  }

  // encodedDataLength is supposed to be the amount of data received
  // over the wire, but it's often 0, so just use dataLength for consistency.
  // https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-dataReceived
  // const length = event.encodedDataLength > 0 ?
  //     event.encodedDataLength : event.dataLength;
  const length = event.dataLength;
  if (url in resources) {
    resources[url] += length;
  } else {
    resources[url] = length;
  }
  console.log("length:"+length);
  	
const totalUncompressedBytes = Object.values(resources).reduce((a, n) => a + n);	
console.log("uncompressed byte :" + totalUncompressedBytes);
});

   await page.goto('https://www.nytimes.com/', { timeout: 50000 });
await browser.close();

**Comment by tomgallagher** [comment]
I've not tried the way you have been trying. But if I wanted the uncompressed size of the page I would do this:

```
var loadArray= [];
page.on('response', response => {
        response.buffer().then(buffer => {
                 loadArray.push(buffer.length);
        });
});
page.on('load', () => {
       var totalLoad = loadArray.reduce(function(a, b) { return a + b; }, 0);
       console.log(totalLoad);
});          
```

**Comment by timocov** [comment]
>        response.buffer().then(buffer => {
>                 loadArray.push(buffer.length);
>        });

Is there a way to retrieve buffer length without getting buffer itself?
