### ISSUE TITLE
Puppeteer runs locally, but not on Jenkins

### ISSUE THREAD

**Issue by MadHatter122312** [puppeteer/puppeteer#1857]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: 10.12.6
* URLs (if applicable): 
* Node.js version: 8.9.0

**What steps will reproduce the problem?**

I am attempting to run e2e test using Puppeteer & Chromium for my Angular 5 project. The script runs locally as expected, but when I run the Jenkins job the applications installs all of the dependencies and builds successfully, but when I tries to run the Chrome executable (after Puppeteer downloads Chromium) it errors out:

```
Error: Failed to launch chrome!
/.../node_modules/puppeteer/
.local-chromium/linux-515411/chrome-linux/chrome: 
error while loading shared libraries: 
libXss.so.1: cannot open shared object file: No such file or directory
```

I did some research and some people suggest installing  a package 
called libXScrnSaver, but when I try to `npm install libXScrnSaver` no such package exists.  I suppose this is an issue with the Jenkins vm but I need a way to include all of the dependencies Chromium handless requires to run.  

I am not sure what the correct approach is...

**Comment by katp4** [comment]
I had a similar issue and it solved when i installed all the dependencies mentioned here
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by MadHatter122312** [comment]
@katp4 Oh I see, I assumed it was dependency related, but I am not really sure what to do with this information...Are you expected to install each missing package?  How do I find out the correct name of the package for Sierra?  Is there an easier way?
It seems not running sandbox is discouraged...What do you suggest?

**Comment by katp4** [comment]
Yep you have to download all the dependencies in order for Puppetter to run. I'm using Ubuntu so i installed all the dependencies listed under Debian and it worked fine. 

Regarding the sandbox, that really depends on your use case. I personally use the no-sandbox argument as i'm not that bothered about it.

**Comment by MadHatter122312** [comment]
@katp4 Alright, so, now its matter of finding out what these packages are called for npm.  Any suggestions for that?  I guess I would have to look up each individual one.

**Comment by katp4** [comment]
They are not npm packages, they are system packages so you need every single one of them 100%. This is how i install them in my Dockerfile.

sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

and that's assuming you are running Debian

**Comment by ebidel** [comment]
The troubleshooting guide covers this.

**Comment by nibiru2O12** [comment]
how to install dependency on Red Hat 4.4.7 on manage hosting.. T_T

**Comment by glenuidev** [comment]
nibiru2012 I'm in the same boat...my issue is with jenkins host, I can't install dependencies there (it's centrally managed) so I'm thinking docker is the best option as my jenkins does run docker.

**Comment by snzmnrdn** [comment]
> ### Steps to reproduce
> **Tell us about your environment:**
> 
> * Puppeteer version: 0.13.0
> * Platform / OS version: 10.12.6
> * URLs (if applicable):
> * Node.js version: 8.9.0
> 
> **What steps will reproduce the problem?**
> 
> I am attempting to run e2e test using Puppeteer & Chromium for my Angular 5 project. The script runs locally as expected, but when I run the Jenkins job the applications installs all of the dependencies and builds successfully, but when I tries to run the Chrome executable (after Puppeteer downloads Chromium) it errors out:
> 
> ```
> Error: Failed to launch chrome!
> /.../node_modules/puppeteer/
> .local-chromium/linux-515411/chrome-linux/chrome: 
> error while loading shared libraries: 
> libXss.so.1: cannot open shared object file: No such file or directory
> ```
> I did some research and some people suggest installing a package
> called libXScrnSaver, but when I try to `npm install libXScrnSaver` no such package exists. I suppose this is an issue with the Jenkins vm but I need a way to include all of the dependencies Chromium handless requires to run.
> 
> I am not sure what the correct approach is...

you just need to run the installation again

`npm i puppeteer --save`

in the server. Make it as script.

**Comment by windyoung1990** [comment]
@glenuidev Hello, do you solve the problem by docker? Can you give me some guide? I don't know how to create a docker and how to connect a docker with jenkins.

**Comment by yandeu** [comment]
@windyoung1990 I have made a docker configuration that works. Take a [look at it](https://github.com/geckosio/jenkins-puppeteer-docker).

**Comment by IdanAdar** [comment]
```
FROM ubuntu:xenial
```

I'm getting: 
```
RUN apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
 ---> Running in 69dd000dc3e7
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package gconf-service
E: Unable to locate package libgconf-2-4
E: Unable to locate package libgtk-3-0
E: Unable to locate package libxss1
E: Unable to locate package fonts-liberation
E: Unable to locate package libappindicator1
E: Unable to locate package xdg-utils
The command '/bin/sh -c apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils' returned a non-zero code: 100
```

cc: @ebidel @katp4

**Comment by IdanAdar** [comment]
Update: I was able to install the required packages, but it's still failing...

```
node index.js **** ****
(node:427) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/jenkins/workspace/UI Consumption Check/****/ui-consumption-check/node_modules/puppeteer/lib/Launcher.js:348:14)
    at ChildProcess.helper.addEventListener (/home/jenkins/workspace/UI Consumption Check/****/ui-consumption-check/node_modules/puppeteer/lib/Launcher.js:338:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:427) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:427) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
const puppeteer = require('puppeteer');
const serviceInstance = "https://****";

(async () => {
    const browser = await puppeteer.launch({ dumpio: true, headless: false, args: ['--disable-setuid-sandbox', '--disable-gpu'] });
    const page = await browser.newPage();
    await page.goto(serviceInstance);
    await page.waitFor(3000);
    await page.type('#userid', process.argv[2]);
    await page.click('button[name="login"]');
    await page.waitFor(3000);
    await page.type('#password', process.argv[3]);
    await page.click('button[name="login"]');
    try {
        await page.waitForSelector('section#table-view')
    } catch (error) {
        process.exit(1);
    }
    //browser.close();
    process.exit(0);
})();
```

**Comment by quachvietcuong-laravel-php** [comment]
@IdanAdar IdanAdar how can u install it, could u teach me

**Comment by MarkyGitHub** [comment]
The only way to do this (without an RHEL subscription) is to do the following installs which work only when in this order:

yum install -y libXScrnSaver \
mesa-libgbm nss at-spi2-atk libX11-xcb \
ftp://ftp.redhat.com/pub/redhat/rhel/rhel-8-beta/appstream/x86_64/Packages/libxkbfile-1.0.9-9.el8.x86_64.rpm \
ftp://ftp.redhat.com/pub/redhat/rhel/rhel-8-beta/appstream/x86_64/Packages/xorg-x11-xkb-utils-7.7-26.el8.x86_64.rpm \
ftp://ftp.redhat.com/pub/redhat/rhel/rhel-8-beta/appstream/x86_64/Packages/xorg-x11-server-common-1.20.2-5.el8.x86_64.rpm \
ftp://ftp.redhat.com/pub/redhat/rhel/rhel-8-beta/appstream/x86_64/Packages/xorg-x11-xauth-1.0.9-12.el8.x86_64.rpm \
ftp://ftp.redhat.com/pub/redhat/rhel/rhel-8-beta/appstream/x86_64/Packages/libXdmcp-1.1.2-11.el8.x86_64.rpm \
ftp://ftp.redhat.com/pub/redhat/rhel/rhel-8-beta/appstream/x86_64/Packages/libXfont2-2.0.3-2.el8.x86_64.rpm \
ftp://ftp.redhat.com/pub/redhat/rhel/rhel-8-beta/appstream/x86_64/Packages/xorg-x11-server-Xvfb-1.20.2-5.el8.x86_64.rpm;

**Comment by yasserhussien** [comment]
I have the same issue
Error: EACCES: permission denied, open '/.config/puppeteerrc'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at #readConfiguration (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:76:39)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:44:63)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/.config/puppeteerrc'
}

### Puppeteer version

23.0.2

### Node version

20.15.0

### Package manager

npm

### Package manager version

10.8.2
