### ISSUE TITLE
problem to install on Debian

### ISSUE THREAD

**Issue by Threepwood77** [puppeteer/puppeteer#1858]
Hello,

I have trouble installing this Puppeteer system...
I'm trying to install it on a new Debian 9 installation  (I also tried it on an 8).
After installation by "npm i puppeteer", here's what I have:

> puppeteer@1.0.0 install /home/guybrush/node_modules/puppeteer
> node install.js

Downloading Chromium r526987 - 97.1 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/guybrush/node_modules/puppeteer/.local-chromium/linux-526987
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN guybrush No description
npm WARN guybrush No repository field.
npm WARN guybrush No license field.

+ puppeteer@1.0.0

if I go through yarn "yarn add puppeteer" , I have this:

info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 40 new dependencies.
â”œâ”€ agent-base@4.2.0
â”œâ”€ async-limiter@1.0.0
â”œâ”€ balanced-match@1.0.0
â”œâ”€ brace-expansion@1.1.8
â”œâ”€ concat-map@0.0.1
â”œâ”€ concat-stream@1.6.0
â”œâ”€ core-util-is@1.0.2
â”œâ”€ debug@2.6.9
â”œâ”€ es6-promise@4.2.2
â”œâ”€ es6-promisify@5.0.0
â”œâ”€ extract-zip@1.6.6
â”œâ”€ fd-slicer@1.0.1
â”œâ”€ fs.realpath@1.0.0
â”œâ”€ glob@7.1.2
â”œâ”€ https-proxy-agent@2.1.1
â”œâ”€ inflight@1.0.6
â”œâ”€ inherits@2.0.3
â”œâ”€ isarray@1.0.0
â”œâ”€ mime@1.6.0
â”œâ”€ minimatch@3.0.4
â”œâ”€ minimist@0.0.8
â”œâ”€ mkdirp@0.5.0
â”œâ”€ ms@2.0.0
â”œâ”€ once@1.4.0
â”œâ”€ path-is-absolute@1.0.1
â”œâ”€ pend@1.2.0
â”œâ”€ process-nextick-args@1.0.7
â”œâ”€ progress@2.0.0
â”œâ”€ proxy-from-env@1.0.0
â”œâ”€ puppeteer@1.0.0
â”œâ”€ readable-stream@2.3.3
â”œâ”€ rimraf@2.6.2
â”œâ”€ safe-buffer@5.1.1
â”œâ”€ string_decoder@1.0.3
â”œâ”€ typedarray@0.0.6
â”œâ”€ ultron@1.1.1
â”œâ”€ util-deprecate@1.0.2
â”œâ”€ wrappy@1.0.2
â”œâ”€ ws@3.3.3
â””â”€ yauzl@2.4.1
Done in 162.07s.

Sounds okay.

in both cases, if I then try to run chromium or chromium_sandbox:
/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux# 
I have this message:
bash: ./chrome_sandbox: cannot execute binary file: Exec format error

my version of nodejs: v9.4.0

:(
Can someone help me ?

thank you.

**Comment by aslushnikov** [comment]
This sounds like issues running on ARM. Check out #550 and maybe #290.

Also, there's [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) that might be helpful.
