### ISSUE TITLE
Ability to manage multiple tabs across multiple windows

### ISSUE THREAD

**Issue by callumlocke** [puppeteer/puppeteer#1859]
Thanks for making puppeteer, it's made my life a lot easier. I want to be able to control more features of the browser, so I can automate testing of a Chrome extension that reacts to tab/window state. It would be good to be able to do these things with puppeteer's API:

- open more than one Chrome window, but in the same browser context, i.e. sharing the same cookies etc. (and each window should be independently resizable)
- when doing `browser.newPage()`, the ability to choose which window the new tab will appear in
- reorder tabs within a window
- move a tab from one window to another
- click a Chrome extension's "browser action" or "page action" buttons

 Is there any chance these features will be added to puppeteer in future?

**Comment by aslushnikov** [comment]
> Is there any chance these features will be added to puppeteer in future?

@callumlocke we prioritize features based on developers demand (i.e. "likes"). Based on this metric, this is a low-pri for us, but still a valid request.

**Comment by aslushnikov** [comment]
Closing since there's no demand; we might come back to this later.

**Comment by daminebenz** [comment]
is it possible to get back to this issue now ?

**Comment by abnerh69** [comment]
Hey! Team!  Same request here, please!
