### ISSUE TITLE
Docs missing for page.waitForNavigation()

### ISSUE THREAD

**Issue by callumlocke** [puppeteer/puppeteer#1860]
The docs for [`page.waitForNavigation()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions) includes only an API outline. All other methods have at least one paragraph stating what the function does and why you might want to use it, but this one doesn't.

I can guess from the name that it waits for navigation, but it's not clear when it might be necessary to use this, since other methods like `.goto()` seem to do this anyway.

**Comment by dowsanjack** [comment]
Let's say you do an action on the page, maybe click on a button, that loads an image on the page or similar. You want the page to then complete that operation, that is where this can be used with options like waitUntil: 

`await page.waitForNavigation({waitUntil: "networkidle0"})`
