### ISSUE TITLE
Dynamic proxy chage in page

### ISSUE THREAD

**Issue by AlexBGD** [puppeteer/puppeteer#1861]
> I want to change proxy on every repuest without closing and Opening the browser again. First set proxy here:

  **const browser = await puppeteer.launch({
                args: ['--proxy-server='+proxy
        });**
----------------------------------------------------------------------------------------------------------------
So my goal is to change proxy on every request, not to have only one proxy per browser.
Thanks!

**Comment by shtefcs** [comment]
This is something we are thinking of to. Let's see how it goes.

**Comment by qingpengchen2011** [comment]
+1

**Comment by Nicolas-vrcc** [comment]
+1 plz halp

**Comment by ebidel** [comment]
Dupe oc https://github.com/GoogleChrome/puppeteer/issues/678

**Comment by paynoattn** [comment]
+1

**Comment by yi-ge** [comment]
+1

**Comment by waseemshahwan** [comment]
+1

**Comment by francima961** [comment]
+1

**Comment by adrian-chang-alcover** [comment]
+1

**Comment by xse** [comment]
You might be able to achieve that with an extension.

**Comment by shtefcs** [comment]
> You might be able to achieve that with an extension.

Can you use chrome extensions inside puppeteer ?

**Comment by xse** [comment]
> Can you use chrome extensions inside puppeteer ?

Yes [you can use extensions with puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions), given that extensions can be used to change proxy and that extensions can know about requests, i feel like this might be doable.
Like you might be able to proxy each requests from your own extension for example.

**Comment by xiyuan-fengyu** [comment]
try this [PuppeteerUtil.useProxy](https://github.com/xiyuan-fengyu/ppspider/blob/master/src/test/component/ProxyTest.ts)

**Comment by yi-ge** [comment]
@xiyuan-fengyu use `http-proxy-agent` to tackle `Puppeteer proxy`, this is a good idea! thank you.

**Comment by Cuadrix** [comment]
It's possible with [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy).
It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.

First install it:
```
npm i puppeteer-page-proxy
```
Then require it:
```js
const useProxy = require('puppeteer-page-proxy');
```
**Using it is easy;**
Set proxy for an entire page:
```js
await useProxy(page, 'http://127.0.0.1:8000');
```

If you want a different proxy for each request,then you can simply do this:
```js
await page.setRequestInterception(true);
page.on('request', req => {
    useProxy(req, 'socks5://127.0.0.1:9000');
});
```
Then if you want to be sure that your page's IP has changed, you can look it up;
```js
const data = await useProxy.lookup(page);
console.log(data.ip);
```
It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
```js
const proxy = 'http://login:pass@127.0.0.1:8000'
```

Repository:
https://github.com/Cuadrix/puppeteer-page-proxy

**Comment by dmitryshelomanov** [comment]
@Cuadrix is not working, "Provisional headers are shown" message + can't extract request cookies

**Comment by badman666** [comment]
> @Cuadrixне работает, сообщение «Показаны предварительные заголовки» + не удается извлечь файлы cookie запроса

+1

**Comment by makanSukros** [comment]
> It's possible with [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy). It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.
> 
> First install it:
> 
> ```
> npm i puppeteer-page-proxy
> ```
> 
> Then require it:
> 
> ```js
> const useProxy = require('puppeteer-page-proxy');
> ```
> 
> **Using it is easy;** Set proxy for an entire page:
> 
> ```js
> await useProxy(page, 'http://127.0.0.1:8000');
> ```
> 
> If you want a different proxy for each request,then you can simply do this:
> 
> ```js
> await page.setRequestInterception(true);
> page.on('request', req => {
>     useProxy(req, 'socks5://127.0.0.1:9000');
> });
> ```
> 
> Then if you want to be sure that your page's IP has changed, you can look it up;
> 
> ```js
> const data = await useProxy.lookup(page);
> console.log(data.ip);
> ```
> 
> It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
> 
> ```js
> const proxy = 'http://login:pass@127.0.0.1:8000'
> ```
> 
> Repository: https://github.com/Cuadrix/puppeteer-page-proxy

Invalid, Getting Error: net::ERR_FAILED

**Comment by ktmohammedsulaim** [comment]
> > It's possible with [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy). It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.
> > First install it:
> > ```
> > npm i puppeteer-page-proxy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then require it:
> > ```js
> > const useProxy = require('puppeteer-page-proxy');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Using it is easy;** Set proxy for an entire page:
> > ```js
> > await useProxy(page, 'http://127.0.0.1:8000');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you want a different proxy for each request,then you can simply do this:
> > ```js
> > await page.setRequestInterception(true);
> > page.on('request', req => {
> >     useProxy(req, 'socks5://127.0.0.1:9000');
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then if you want to be sure that your page's IP has changed, you can look it up;
> > ```js
> > const data = await useProxy.lookup(page);
> > console.log(data.ip);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
> > ```js
> > const proxy = 'http://login:pass@127.0.0.1:8000'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Repository: https://github.com/Cuadrix/puppeteer-page-proxy
> 
> Invalid, Getting Error: net::ERR_FAILED

Same here. Any update on the issue?

**Comment by JijaProGamer** [comment]
Thats a proxy issue. I use puppeteer-page-proxy daily and it works just fine. Use premium proxies if you want it to work.

**Comment by MuneerCloud007** [comment]
> Thats a proxy issue. I use puppeteer-page-proxy daily and it works just fine. Use premium proxies if you want it to work.

hii,
I am issue with puppeteer-page-proxy. i am getting this error 
TypeError: useProxyPer[target.constructor.name] is not a function
please help me out
