### ISSUE TITLE
Puppeteer, Concurrent Instances, Error Handling

### ISSUE THREAD

**Issue by tomgallagher** [puppeteer/puppeteer#1862]
Puppeteer 1.0.0
Cloud9 Workspace
Node Version 7.10.1

I've been running some tests using multiple Puppeteer instances in a [generic-pool](https://github.com/coopernurse/node-pool) and trying to operate at and beyond the limits of my Cloud9 workspace in order to provoke errors and write some good error handling. If I restrict the pool size to 2, everything runs very smoothly. If I set it at 5, for example, I start getting a few errors. This is the Puppeteer get page and error handling code:

```
async function getPage(targetURL, pageWidth, pageHeight, useragent) {
    
    //set the user agent
    const userAgent = useragent;
    //grab an instance of the Chrome headless browser
    const browser = await global.chromepool.acquire();
    debug(`GLOBAL CHROMEPOOL count after borrowing instance: ${global.chromepool.borrowed} for: ${targetURL}`);
    //create a new page / tab
    const page = await browser.newPage().catch(err => errHandler("newPage", err, targetURL, browser) );  
    //set the viewport to equal the size of the user's viewport so that resources are equivalent
    await page.setViewport({width: pageWidth, height: pageHeight}).catch(err => errHandler("setViewport", err, targetURL, browser) );  
    //set the user agent in the browser
    await page.setUserAgent(userAgent).catch(err => errHandler("setUserAgent", err, targetURL, browser) );  
    //call the get content promise and attach a global handler for errors at any point
    var content = await returnContent(targetURL, page, browser).catch(err => { throw `${err}`; });
    return content;
    
}

function errHandler(caller, error, targetURL, browser) {
    
    if (global.chromepool.isBorrowedResource(browser) == true) {
        global.chromepool.release(browser).then( () => { 
            debug(`GLOBAL CHROMEPOOL count after releasing instance: ${global.chromepool.borrowed}, on GENERAL ERROR: ${error.message.toUpperCase()}, in command: ${caller}, for: ${targetURL}`);
            throw `${error}`;
        });
    } else { throw `${error}`; }
    
}

function returnContent(targetURL, page, browser) {
    
    var returnedContent = null;
    return new Promise( (resolve, reject) => {
        
        page.on('error', (err) => {
            if (global.chromepool.isBorrowedResource(browser) == true) {
                global.chromepool.release(browser).then( () => { 
                    debug(`GLOBAL CHROMEPOOL count after releasing instance: ${global.chromepool.borrowed}, on PAGE ERROR: ${err.message.toUpperCase()}, for: ${targetURL}`);
                    reject(err);
                });
            } else { reject(err); }
        });
        
        page.goto(targetURL, {timeout: 25000, waitUntil: ["domcontentloaded", "load"]})
            .then( () => page.content() )
            .then(content => { returnedContent = content })
            .then( () => page.close() )
            .then( () => global.chromepool.release(browser) )
            .then( () => debug(`GLOBAL CHROMEPOOL count after releasing instance: ${global.chromepool.borrowed}, for: ${targetURL}`) )
            .then( () => { resolve({targetURL: targetURL, content: returnedContent}); })
            .catch(err => {
                if (global.chromepool.isBorrowedResource(browser) == true) {
                    global.chromepool.release(browser).then( () => { 
                        debug(`GLOBAL CHROMEPOOL count after releasing instance: ${global.chromepool.borrowed}, on CONTENT ERROR: ${err.message.toUpperCase()}, for: ${targetURL}`);
                        reject(err); 
                    });
                } else { reject(err); }
            });
    });
        
}
```

By and large this error handling works well. This is indicated by the occasional page crash message, like this

> CHROME-HANDLER GLOBAL CHROMEPOOL count after releasing instance: 4, on PAGE ERROR: PAGE CRASHED!, for: https://www.bbc.co.uk/ +0ms

and the occasional timeout message like this: 

> CHROME-HANDLER GLOBAL CHROMEPOOL count after releasing instance: 4, on CONTENT ERROR: NAVIGATION TIMEOUT EXCEEDED: 25000MS EXCEEDED, for: http://edition.cnn.com/ +0ms

However, when the system gets overloaded, one of the things that can go wrong is that the instance of Puppeteer cannot deliver a new page when it is asked for one. So I get this message logged as I would expect:

>  CHROME-HANDLER GLOBAL CHROMEPOOL count after releasing instance: 3, on GENERAL ERROR: NOT OPENED, in command: newPage, for: http://www.euronews.com/ +0ms

But I also get these messages, which I would not expect

> (node:26561) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: not opened

> (node:26561) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I realise that I can use a `process.on('unhandledRejection')` handler to handle this rejection, but I thought it was worth reporting. Probably just a catch statement needed somewhere in `browser.newPage()`.

**Comment by aslushnikov** [comment]
@tomgallagher interesting, it looks like chrome fails to open page when there's a shortage of resources. Thanks for reporting this.

**Comment by tglines** [comment]
@aslushnikov I've found the same issue.

`browser.newPage()` fails under resource constrained scenarios.  (In my case many pages spawned off of the same browser instance in a short amount of time)

**Comment by aslushnikov** [comment]
I don't think we can do much about this on the pptr-side or even chromium side; closing this.
