### ISSUE TITLE
Multiple authorized Pages with cookie in one instance of Browser

### ISSUE THREAD

**Issue by grebmeg** [puppeteer/puppeteer#1863]
Hello, everyone.

Could you help me with one problem? But I amn't sure my problem is bug or correct behavior.

I open multiple authorized pages  (to one site, every page in one tab) with cookie on one browser instance to get screenshots of all of them and some screenshots are made correctly, but part of them wrong (without authorization). This wrong part of pages is random.

```javascript
const puppeteer = require('puppeteer');
const pageURLs = [];

(async () => {
    const browser = await puppeteer.launch({
        dumpio: true,
        ignoreHTTPSErrors: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu', '--allow-insecure-localhost', '--disable-dev-shm-usage']
    });

    await Promise.all(pageURLs.map(async (url, i) => {
        const page = await browser.newPage();

        await page.setCookie(); // here I put cookie for site
        await page.goto(url, {
            waitUntil: 'load'
        });

        await page.screenshot({
            path: `saved/${i}-${Math.floor(Math.random() * 10000)}.png`,
            fullPage: true
        });

        await page.close();
    }));

    await browser.close();
})();
```

Why is it happening?

**Comment by aslushnikov** [comment]
It's hard to say what's going on here. This exact usecase is not runnable, and my local tests with cookies work just fine.

If you still experience issues with this, please re-file with a script I can run locally to reproduce the problem.

Thanks!
