### ISSUE TITLE
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED

### ISSUE THREAD

**Issue by mostend** [puppeteer/puppeteer#1870]
Tell us about your environment:
Puppeteer version: V1.0.0
Platform / OS version: windows10
URLs (if applicable):
Node.js version: 9.4.0

I request many urls from a web site. this is my code.
```
const browser = await puppeteer.launch({
        headless: false,
        slowMo: 100,
        ignoreHTTPSErrors: true,
    });
const page = await browser.newPage();
    await page.setViewport({
        width: 1366,
        height: 768,
    })
await page.goto(url, { waitUntil: 'networkidle2', timeout: 0, ignoreHTTPSErrors: true })
```
when headless status is true, It has the following error .
```
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
```
I change the headless to false, all going well.

**Comment by benjaminapetersen** [comment]
Also experiencing this, when navigating to a page that does an OAuth redirect.  Page has HTTPS.  When I flip `puppeteer.launch({ headless: false })` the error goes away.

```
Error: net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
    at navigate (~/smoke-test/node_modules/puppeteer/lib/Page.js:520:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by frale98** [comment]
I have  the same error, any interesting findings here?

**Comment by Paul-Pushkarov** [comment]
I am having the same error, I am not using puppeteer, just headless Chrome, when I am trying to access certain https hosts.

**Comment by benjaminapetersen** [comment]
Right.  This is pretty hard to work around since most use https these days.

**Comment by MartonEstok** [comment]
I see the same problem

**Comment by Paul-Pushkarov** [comment]
There is an issue for that in `Chromium` tracker. Unfortunately 8-month old, so it does not look like it has priority :(
https://bugs.chromium.org/p/chromium/issues/detail?id=757181
Please go there an vote.

This issue might be a duplicate of this https://github.com/GoogleChrome/puppeteer/issues/963

**Comment by aslushnikov** [comment]
Dupe of #963.

**Comment by Paul-Pushkarov** [comment]
Good news, it looks like the issue is fixed and someone told me that the bug is gone in chrome canary.
