### ISSUE TITLE
Puppeteer controlled browser has different locales depending on whether in headless mode or not

### ISSUE THREAD

**Issue by aknuds1** [puppeteer/puppeteer#1871]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: OS X 10.13.2
* URLs (if applicable):
* Node.js version: 9.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Download my [test repository](https://github.com/aknuds1/puppeteer-test)
2. Install: `npm i` (note that you will also need Python 2)
3. Run tests: `npm test`

**What is the expected result?**
I expect that Puppeteer's browser uses the same locale for formatting time in headless and non-headless modes, which is what my tests assert.

**What happens instead?**
The browser launched by Puppeteer in headless mode uses a different locale from Node.js, and the non-headless browser, which causes the test _Puppeteer shows correct time in headless mode_ to fail because time gets formatted differently as a result.

In my case, I get the following output from the tests:

```
✗ npm i && npm test
npm WARN puppeteer-test@1.0.0 No repository field.

up to date in 1.865s

> puppeteer-test@1.0.0 test /Users/arve/Projects/puppeteer-test
> ava


  1 passed
  1 failed

  Puppeteer shows correct time in headless mode

  /Users/arve/Projects/puppeteer-test/test.js:55

   54:
   55:   t.is(await page.$eval('#main', (elem) => {
   56:     return elem.innerText

  Difference:

  - 'The time is 9:00 AM'
  + 'The time is 09:00'
```

**Comment by ebidel** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=755338 could be related. 

I'm not familiar with luxon, but this produces the same thing for me in headless and non-headless:

```js
console.log(await page.evaluate('(new Date(2018, 1, 12, 8)).toLocaleString()'));
// 2/12/2018, 8:00:00 AM
```

What locale is your system set to?

**Comment by aknuds1** [comment]
@ebidel How do I determine my locale? When I query `navigator.language` in Chrome, I get `en-GB`.

I'm gonna guess you're not seeing any locale differences since your locale is en-US, which also the headless browser seems to use for me?

**Comment by ebidel** [comment]
Under chrome settings, there's lang prefs and under system, "language and region" settings (at least on mac).

Yea, `en-US` is probably the default. According to http://antoinevastel.github.io/bot%20detection/2018/01/17/detect-chrome-headless-v2.html, `navigator.language === ""` in headless. I suspect if that's not set, then you're getting `en-US` results by default for the Date methods.

**Comment by aknuds1** [comment]
@ebidel Sounds like Mr. Vastel put his finger on the problem! Do you think it's a bug in headless mode?

**Comment by ebidel** [comment]
Trying setting `lang` as a workaround:

```js
const browser = await puppeteer.launch({
  args: ['--lang=en-GB']
});
```

**Comment by aknuds1** [comment]
@ebidel Yeah thanks, I should've mentioned, but I already worked around it by standardizing on `en-US` via the `--lang` flag.

**Comment by ebidel** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=755338#c7

**Comment by aknuds1** [comment]
I figure we might as well close this issue then @ebidel, since it appears to be a Chromium bug. Thanks for your help!

**Comment by skyiea** [comment]
Looks like in "headful" mode `--lang` arg is ignored. Is it the same issue?

**Comment by nacimgoura** [comment]
@skyiea you can do this for change language too : 
```
await this.page.setExtraHTTPHeaders({
	'Accept-Language': 'en-US'
});
```

**Comment by yurist38** [comment]
Hello! I think would be nice to highlight here one more thing. I'm trying to get a month name translated in Puppeteer (headless) by `new Date().toLocaleString('nl-NL', { month: 'short' })` but it's not working and returns an English one. I can guess that some translation package is not included to headless chrome. So maybe someone can clarify the situation around it and possible ways to solve the issue? Thanks in advance.
