### ISSUE TITLE
Headless Chrome Doesn't Support Viewing PDFs?

### ISSUE THREAD

**Issue by thiscantbetaken** [puppeteer/puppeteer#1872]
I have a requirement to navigate to a PDF URL in Headless Chrome and then enter a search term, but for some reason the PDF never gets loaded or rendered with a screenshot.

Even attempting to use an external JavaScript library to embed a PDF doesn't work.

chrome --headless --disable-gpu --screenshot https://www.chromestatus.com/
 https://www.epa.gov/sites/production/files/2017-12/documents/lcr_federalism_consultation_letter.signed.12_14_17.pdf
chrome --headless --disable-gpu --screenshot https://mozilla.github.io/pdf.js/web/viewer.html

Are there any options via Selenium or perhaps with an external PDF viewer that can be used in conjunction with Headless Chrome, to open a PDF URL and then enter a search phrase?

**Comment by NagarjunPrasad1** [comment]
Any updates on this yet? I want the ability to just get the pdf but it's the same for me as well!

**Comment by f3l1x** [comment]
I would appreciate it too.

**Comment by lepinekong** [comment]
Me too

**Comment by thiscantbetaken** [comment]
It does, you just have to wait a minute or so before it renders for
whatever reason.

**Comment by sukhjinder-sdei** [comment]
I have same requirement to render a PDF in chrome headless. It is not working at all.

Please share any code example available if someone already has done this.

**Comment by aslushnikov** [comment]
> I have a requirement to navigate to a PDF URL in Headless Chrome and then enter a search term, but for some reason the PDF never gets loaded or rendered with a screenshot.

@thiscantbetaken Chrome Headless doesn't know what to do with PDFs. It'll try to download it, but downlaods are not supported yet - see #299.

> Even attempting to use an external JavaScript library to embed a PDF doesn't work.

this works just fine for me:

```js
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage()
  await page.goto('https://mozilla.github.io/pdf.js/web/viewer.html', {waitUntil: 'networkidle0'})
  await page.screenshot({path: 'screenshot.png' });
  await browser.close()
})
```

Summing up: yes, chrome headless doesn't support viewing PDFs and there are no plans to teach it to. If you absolutely need that capability, try using [pdf.js](https://mozilla.github.io/pdf.js/). Otherwise, consider subscribing to #299 to get updates on the downloads progress.

**Comment by azazrehman** [comment]
https://github.com/puppeteer/puppeteer/issues/299#issuecomment-643384602

**Comment by miaskadu** [comment]
Any update yet?

**Comment by miaskadu** [comment]
How to open PDF Files in chromeHeadless Mode... headLess Mode now supports downloads but opening PDF not yet... in firefoxHeadless mode, it opens PDF URL but not in chromeHeadless Mode

**Comment by michaeltranlong** [comment]
For files < 25 MB, one easy way to render PDF with chrome headless is to use Google Drive Viewer from https://gist.github.com/tzmartin/1cf85dc3d975f94cfddc04bc0dd399be

Something like this works for me: https://docs.google.com/viewer?url=http://infolab.stanford.edu/pub/papers/google.pdf

**Comment by xiabo0816** [comment]
Download pdf in headless chromedriver:

`chrome_options.add_experimental_option('prefs',  
            {
                'download.default_directory': "C:\Tmp", # windows
                "plugins.always_open_pdf_externally": True,
                "profile.default_content_settings.popups": 0,
            }
        )`

Name: selenium
Version: 4.6.1
