### ISSUE TITLE
Generate the pdf with empty content occasionally

### ISSUE THREAD

**Issue by TonyWuLihu** [puppeteer/puppeteer#1875]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.0.0
* Platform / OS version: Darwin64
* URLs (if applicable): https://dev.capitalpreferences.com/dashboard/setup/signin
* Node.js version:
v7
**What steps will reproduce the problem?**
While I tried to load the url and generate the pdf, it only has PDF with content generated first time. Always blank pdf for consecutively call. 
_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by TonyWuLihu** [comment]
Forgot to mention, it's an angular 4 page, and seems like it's a page loading timeout issue or something, I have added page.waitFor(xxxx),  it could generate the pdf pretty good. Any suggestion or a solution to always wait for the page fully displayed?  Sorry, I'm a backend guy, so dont know how to write the question clearly enough.

**Comment by vc1** [comment]
https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/docs/api.md#pagegotourl-options
https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/docs/api.md#pagewaitfornavigationoptions

```javascript
page.goto('http://xx', {
  waitUntil:['domcontentloaded', 'networkidle0']
})
// print pdf
```

**Comment by TonyWuLihu** [comment]
@vc1  thx, I'm currently using page.goto('http://xx', {
  waitUntil: 'networkidle2'
})

**Comment by PCS-Ismail** [comment]
Any update on this?

**Comment by phamcharles** [comment]
@PCS-Ismail im in the same boat where the pdf will return empty occasionally. I believe it only happens on heroku for me

**Comment by PCS-Ismail** [comment]
Happens on Kubernetes for me, either empty or the pdf is incomplete. I'll follow through on this

**Comment by armellarcier** [comment]
+1

**Comment by Faisalnwz01** [comment]
Thanks, @vc1 waiting for `domcontentloaded` worked for me!

**Comment by maxmax1992** [comment]
I had similair problem:
My button text and the text itself disappeared sometimes from pdf,
adding: 
`await page.waitFor('*')` ,
solved my problem.
this waits every element in the html of the page.

**Comment by xyzdata** [comment]
# same empty bugs

> empty content occasionally

**Comment by phattranky** [comment]
I'm using Angular Server Side Rendering also got the same problem. The `await page.waitFor('*') ` is not work at my side. I must set a static delay value before generating PDF to fix this problem. Look likes the issue come from the Angular SSR, it's re-render at Client Side after Server Side have responsed

Below code is waited for 5s before call PDF
```
 await page.waitFor(5000);

 await page.pdf({
      format: 'A4',
      printBackground: true,
      path: filePath1
 });
```
