### ISSUE TITLE
puppeteer.launch() doest launch chromium with headless = true in windows 7

### ISSUE THREAD

**Issue by pheolink** [puppeteer/puppeteer#1876]
Hi Guys,

I am trying to run the headless chrome in windows 7 with node 8+ with the following code

puppeteer.launch()
  .then(async browser => {
  ..../
});
the chromium is not launched with the default, I can see the process chrome.exe in the task manager
when I use 
puppeteer.launch({headless: false})
  .then(async browser => {
  ..../
});
Its working fine.
with  headless: false I am facing some scroll issues.
Any help....? and thanks in advance.

**Comment by aslushnikov** [comment]
@pheolink it's hard to say what's going on - too few cues. I'd try filing to the chromium bugtracker.

**Comment by caserffer** [comment]
I have the same issue
my code is:
const puppeteer = require('puppeteer');

(async () => {
    const browser = await (puppeteer.launch({
        executablePath: 'D:\\puppeteer\\chrome-win32\\chrome.exe',
        timeout: 15000,
        ignoreHTTPSErrors: true,
        headless: true
    }));
    const page = await browser.newPage();
    await page.goto('https://www.baidu.com/');
    await page.screenshot({
        path: 'baidu.png',
        type: 'png',
        fullPage: true,
    });
    browser.close();
})();
when set headless: false it works fine
but headless: true
it run with errors 
"C:\Program Files\JetBrains\WebStorm 2017.2.5\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\quanh\WebstormProjects\pupp-test\demo\ykt\get_home_page.js
(node:592) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0824/172231.812:FATAL:feature_list.cc(236)] Check failed: !g_initialized_from_accessor. 
Backtrace:
	ovly_debug_event [0x108FBE20+11772048]
	ovly_debug_event [0x108FB6BD+11770157]
	ovly_debug_event [0x10912580+11864048]
	ovly_debug_event [0x108FDE67+11780311]
	ovly_debug_event [0x103673D3+5920323]
	ovly_debug_event [0x1036BB57+5938631]
	GetHandleVerifier [0x112DF6B8+4180760]
	ovly_debug_event [0x108BAAB5+11504933]
	ovly_debug_event [0x108BB13F+11506607]
	ovly_debug_event [0x108BA84F+11504319]
	ovly_debug_event [0x108C3966+11541462]
	ovly_debug_event [0x108BAA4B+11504827]
	IsSandboxedProcess [0x10DF740B+1957747]
	IsSandboxedProcess [0x10DF747F+1957863]
	ovly_debug_event [0x108C2760+11536848]
	ovly_debug_event [0x108C27DE+11536974]
	ChromeMain [0x0FDC1173+247]
	Ordinal0 [0x00132D80+11648]
	Ordinal0 [0x0013145D+5213]
	GetHandleVerifier [0x001F16FA+544266]
	BaseThreadInitThunk [0x76A3343D+18]
	RtlInitializeExceptionChain [0x77A29832+99]
	RtlInitializeExceptionChain [0x77A29805+54]



TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\quanh\node_modules\puppeteer\lib\Launcher.js:299:14)
    at ChildProcess.helper.addEventListener (C:\Users\quanh\node_modules\puppeteer\lib\Launcher.js:289:60)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
(node:592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Process finished with exit code 0
