### ISSUE TITLE
Chromium does not display full page.

### ISSUE THREAD

**Issue by ivannluz** [puppeteer/puppeteer#1881]
I'm new with puppeteer and I want to know how can set my browser in order to display the full page because I set the size but does not matter how big I set the browser still display a big blank rectangle.
![image](https://user-images.githubusercontent.com/31895571/35286197-f295c0d0-0024-11e8-8b01-8804b54d9b0d.png)
 
I don't want that display that blank space.

**Comment by qianx1992** [comment]
Do you want to achieve full page screenshots? If the answer is yes,you need set the property "await page.screenshot({path: './img/1.png',fullPage:true});" or "await page.screenshot path: './img/music16.png',
        clip: {
            x: 0,
            y: 0,
            width: width,
            height: height
        }
    });"

**Comment by ebidel** [comment]
@ivannluz what you're seeing in the screenshot is that Puppeteer uses emulation to see a default viewport of 800x600. https://github.com/GoogleChrome/puppeteer#usage. 

If you want something bigger that that, use `page.setViewport()`.

For full page screenshots, you can use what @qianx1992 suggests.

**Comment by DerekTso** [comment]
@qianx1992 Hi, when I use `fullpage` option, it's not working, it only screenshots the top part of the webpage, not the full page(from top and bottom).

```
const puppeteer = require('puppeteer');
const VIEWPORT = { width: 1920, height: 1080 };

(async () => {
    const browser = await puppeteer.launch({
        executablePath: './chromium/chrome.exe',
        args: ["--ash-host-window-bounds=1920x1080", "--window-size=1920,1048", "--window-position=0,0"],
        headless: false
    });
    const page = await browser.newPage();
    await page.setViewport(VIEWPORT);
    await page.goto('http://music.163.com/');
    await page.screenshot({ path: "test.png", fullPage: true });
    await browser.close();
})();
```
