### ISSUE TITLE
Automatically fix JavaScript errors on pull requests

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#1882]
I run Stickler-CI which is a service aimed at improving code quality by simplifying code review by automating code feedback in pull requests. 

We just launched auto-fixing for JavaScript through pull request commits. As a JavaScript open source project, our service will save you time and brain power by automatically fixing style errors.

If you are interested in trying out our product, we can submit a pull request with the configuration file, but a maintainer will need to enable webhooks by logging into https://stickler-ci.com and enabling the webhook.

Thank you!

**Comment by ebidel** [comment]
Thanks @tgrundmanis. Curious how the service automatically fixes code? Does it need permissions to edit the PR contents?

FWIW, we're limited to what new services we can add to official Google repos. We also have Travis already setup to [run ESlint](https://github.com/GoogleChrome/puppeteer/blob/master/.travis.yml#L16) on new PRs.

**Comment by ghost** [comment]
Hello!

So it does not edit PR contents, it adds a commit with a correction to a PR.

And that’s ok, I hear Travis is pretty good :)

Tara
