### ISSUE TITLE
page.keyboard.press('F11') does not work

### ISSUE THREAD

**Issue by n0rv1n** [puppeteer/puppeteer#1883]
**environment:**

* Puppeteer version:V1.0.0
* Platform / OS version:Windows 10
* Node.js version:V9.3.0

**page.keyboard.press('F11') does not work**
I want to enable the fullscreen mode,but it's  not working

**Comment by jiladahe1997** [comment]
For enable the fullscreen mode.
Maybe this will work:#1762

**Comment by aslushnikov** [comment]
Toggling full screen mode with F11 is a chrome shortcut. Pptr doesn’t emulate browser shortcuts; instead, it dispatches events to the page.

You’ll have to trigger the full screen mode manually. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
