### ISSUE TITLE
Feature Request: Puppeteer chat on gitter

### ISSUE THREAD

**Issue by theoutlander** [puppeteer/puppeteer#1884]
I was wondering if there are plans for an official puppeteer chat channel? 

I've found one on https://gitter.im/puppeteer-chat/Lobby, but it appears to have just a handful of us hanging out occasionally. It would be nice to be able to help and ask for help in real-time for some of these puppeteer related questions.

Could we please create an official channel and list it in the readme? I'm happy to send a PR if we want https://gitter.im/puppeteer-chat/Lobby to be the destination.

**Comment by ebidel** [comment]
How about Slack? I created a channel with [link to join](https://join.slack.com/t/puppeteer/shared_invite/enQtMzAyOTU1MzQyOTQ1LTUzOTAxNjE5YWI0YzNmYmRkN2I4MDg2MzI4OGE3YWNhZDBlYWMyNTlmOTJlN2RhYzlmODI4ZDQxZGEyMGIwNDY).

**Comment by mkantautas** [comment]
This link is no longer valid

**Comment by aslushnikov** [comment]
@neorganic Here's an [updated link](https://join.slack.com/t/puppeteer/shared_invite/enQtMzU4MjIyMDA5NTM4LTM1OTdkNDhlM2Y4ZGUzZDdjYjM5ZWZlZGFiZjc4MTkyYTVlYzIzYjU5NDIyNzgyMmFiNDFjN2UzNWU0N2ZhZDc)

**Comment by ITmaze** [comment]
Is this still the way to discuss puppeteer? The link isn't valid any longer.
