### ISSUE TITLE
How do I capture page errors?

### ISSUE THREAD

**Issue by wcflmy** [puppeteer/puppeteer#1890]
My code is like this:
```
const puppeteer = require('puppeteer')

;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()

  page.on('error', (err) => {
    console.log('error: ', err)
  })
  page.on('pageerror', (err) => {
    console.log('pageerror: ', err)
  })
  page.on('console', msg => {
    for (let i = 0; i < msg.args.length; ++i)
      console.log(`${i}: ${msg.args[i]}`)
  })

  await page.goto('http://example.com/page-that-throws-an-error')
  browser.close()
  
})()
```
The page of `http://example.com/page-that-throws-an-error` would throw an error, which there is the code like this:
```
 console.log(notexsist)
```
But, actually, the `error` event and also `pageerror` event is not fired.
This issue #1030  is related to my confusion, but the answers can't help me.
So, How do I capture the errors occured in the page.

**Comment by tomgallagher** [comment]
Do you mean you want to pick up errors in the page itself or errors in Puppeteer's handling of the page?

The  `page.on('pageerror', (err) => {});` handler picks up errors in the page itself for me.

**Comment by wcflmy** [comment]
I want to pick up errors in the page itself, but it doesn't work for me.
Can you show me your code?

**Comment by iabai** [comment]
I have same problem error event and pageerror event is not fired when jacascript throw error.

**Comment by aslushnikov** [comment]
I'm still not sure what you mean here. Your snippet throws an error that you can catch with `.catch()` promise method.

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
      headless: false,
    });
    const [page] = await browser.pages();
    await page.goto('http://example.com/page-that-throws-an-error').catch(e => console.error(e));
    await browser.close();
})();
```

**Comment by tomgallagher** [comment]
I think he means that he wants to catch general Javascript errors in the page, as opposed to errors caused by Puppeteer. Lots of websites have errors in their Javascript, the ones you can listen to with
`window.onerror = function {};`
Although it's not that clear.

**Comment by towhare** [comment]
```javascript
page.on('console', (msg) => {
  const type = meg.type();
  if(type === 'error'){
    console.log(msg);
  }
});
page.evaluate(() => console.error('hello', 5, { foo: 'bar' }));
```

> Emitted when JavaScript within the page calls one of console API methods, e.g. console.log or console.dir. Also emitted if the page throws an error or a warning.

link [puppeteer docs page.on](https://pptr.dev/#?product=Puppeteer&version=v10.1.0&show=api-event-console)

**Comment by cezarlacatus** [comment]
Hi guys, is there any way to detect 504 error? Basically when the page prompts 504, detect that and perform a page refresh.

**Comment by raffareis** [comment]
> Hi guys, is there any way to detect 504 error? Basically when the page prompts 504, detect that and perform a page reload.

`
page.on('response', async (response) => {
                    if (response.status() > 400) {
                        setTimeout(async () => {
                            await page.reload()
                        }, 15000)
                    }
                  `
