### ISSUE TITLE
Document the behavior when the same header is present multiple times

### ISSUE THREAD

**Issue by Khady** [puppeteer/puppeteer#1893]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.0.0 and puppeteer@1.0.0-next.1516669982697
* Platform / OS version: debian
* URLs (if applicable): https://www.google.com.sg
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

Some pages return multiple time the same header when requested. `set-cookie` for example.

When requesting the same page using puppeteer, there is only one entry in the resulting headers object. And the value is a string, not an array. Both values for the header `set-cookie` are present in this string, separated by a `\n`.

It would be nice to document this properly. Or even better, to change the type of the headers object to something like this in typescript:

```typescript
interface headers {
  [header: string]: Array<{ key: string, value: string | boolean | number }>
}
```

Which is the same format used in some parts of aws:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html

> headers (read/write)
> 
> The headers in the request. The keys in the headers object are
> lowercase versions of the header names in the HTTP request. These
> lowercase keys give you case-insensitive access to the header
> values. Each header (for example, headers["accept"] or
> headers["host"]) is an array of key-value pairs, where key is the
> case-sensitive name of the header as it appears in an HTTP request and
> value is a header value. The number of elements in the array is the
> number of times that a header is repeated in an HTTP request.

Or a type like the one used in axios:

```typescript
interface headers {
  [header: string]: Array<string | boolean | number>
}
```

Also, I didn't test the behavior in request interception. I don't know if it is possible to give a header with a newline in the middle to `request.respond`. But it would be more natural to have a list rather than to rely on a trick like this.

Probably need to test the merge behavior of two headers with the same key except the case in request interception too.

```
$ curl -Is "https://www.google.com.sg" | grep set-cookie
set-cookie: 1P_JAR=2018-01-24-10; expires=Fri, 23-Feb-2018 10:14:01 GMT; path=/; domain=.google.com.sg
set-cookie: NID=122=rBdphBn29hBrav1r3Ns1rOk9gjnApqe_V6wVLjKcDlj1swr9K5iGy03Z3Ln1C_OpfYxZroMioPtL2gtMx1-eayjLKpEptNPpXGtLUNERQiC5EF7fNSHWNkSkZMajSDGM; expires=Thu, 26-Jul-2018 10:14:01 GMT; path=/; domain=.google.com.sg; HttpOnly
```

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const url = process.argv[2];
  console.log("url:", url);
  const args = [
    "--disable-gpu",
    "--disable-setuid-sandbox",
    "--force-device-scale-factor",
    "--ignore-certificate-errors",
    "--no-sandbox",
  ];
  const browser = await puppeteer.launch({args});
  const page = await browser.newPage();
  const res = await page.goto(url);
  console.log(res.headers());
  await browser.close();
})();
```

```
$ nodejs test.js "https://www.google.com.sg"
url: https://www.google.com.sg
{ date: 'Wed, 24 Jan 2018 10:15:26 GMT',
  'content-encoding': 'gzip',
  server: 'gws',
  'x-frame-options': 'SAMEORIGIN',
  p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
  status: '200',
  'set-cookie': '1P_JAR=2018-01-24-10; expires=Fri, 23-Feb-2018 10:15:26 GMT; path=/; domain=.google.com.sg\nNID=122=FhDGGMkfeOJVdtI8JF84F-19XiY5AhvrvVv1UirgehMcCCvqgWUFtuhMf0Ptc4HEWsqc4gJxsmLg6zXMywfKmOXFniS-ip7wuKJPT5fRyo5kbOh7BfGkwpIcDQlfwmMP; expires=Thu, 26-Jul-2018 10:15:26 GMT; path=/; domain=.google.com.sg; HttpOnly',
  'cache-control': 'private, max-age=0',
  'strict-transport-security': 'max-age=3600',
  'content-type': 'text/html; charset=UTF-8',
  'alt-svc': 'hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"',
  'x-xss-protection': '1; mode=block',
  expires: '-1' }
```

**Comment by connorjclark** [comment]
Just ran into this myself.

@aslushnikov [Which approach](https://github.com/GoogleChrome/puppeteer/issues/2534#issuecomment-389715369) would you prefer? I could take this on.

**Comment by adrianlyjak** [comment]
Running into this as well. I'm keeping a cache of requests, and responding early from the cache with `request.respond`. Encountered a `set-cookie` header with 2 values split by a `\n` delimiter, and chromium just hangs spinning waiting for the web page to load.

**Comment by adrianlyjak** [comment]
@aslushnikov any thoughts on #4915 as a non api-breaking fix?
