### ISSUE TITLE
"Error:node is not visible" when using ElementHandle.type which Element is in iframe

### ISSUE THREAD

**Issue by luopeizhen** [puppeteer/puppeteer#1894]
### Steps to reproduce

* Puppeteer version: v1.0.0

**What steps will reproduce the problem?**
I want to type some text into the input element, the input element is in the iframe of a page

_Please include code that reproduces the issue._

```
const frames = page.frames()
        let frame: any
        for (const f of frames) {
            if (f.name() == "frame1") {
                frame = f
                break
            }
        }

let e = await frame.$("#input1")
await e.type("abc")

```

**What is the expected result?**
it should make the input1's value to "abc"

**What happens instead?**
there is an Error

```
Error: Node is not visible
    at ElementHandle._visibleCenter (node_modules/puppeteer/lib/ElementHandle.js:63:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

```
** my solution  **
I simulate the type operations use this code:

```
let e = await frame.$("#input1")
await e.focus()
await page.keyboard.type("abc")
```

**Comment by aslushnikov** [comment]
This seems to be related to the broken `_scrollIntoViewIfNeeded` method we use internally; it was fixed in Puppeteer v1.6.0.
