### ISSUE TITLE
Access to body content of a 3XX response 

### ISSUE THREAD

**Issue by phackt** [puppeteer/puppeteer#1896]
Hello, i would like to access to the response.text() having a response status code in the 3XX range. 

The fact is that the response.text() Promise in this case will stay in a Pending state. Example for a request on ```https://google.com```, i would like to output:

```html
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.fr/?gfe_rd=cr&amp;dcr=0&amp;ei=jMJoWrHVI-_t8we8_67ICg">here</A>.
</BODY></HTML>
```

A part of the response:
```
...
_contentPromise: Promise { <pending> },
 _status: 302,
_url: 'https://google.com/',
...
```

but the following code will never trigger (and in my case will also exit the main process, that's the most annoying part):
```
response.text().then(
    function(result) {
        console.log('result: ' + result)
});
```

Do you have any idea of how i can access to the body content of this response (request is flagged as resource type ```document```).

Thanks in advance,

**Comment by aslushnikov** [comment]
@phackt Indeed, I found a bug in pptr regarding this. But there's still a fundamental issue in devtools protocol: we won't be able to fetch content of a redirect response. It will be even harder to do so in future with the network layer refactoring in chrome.

What's your usecase? I don't think browser users ever get to see the redirect response body.
