### ISSUE TITLE
How get information from tag use puppeteer ? 

### ISSUE THREAD

**Issue by tyt34** [puppeteer/puppeteer#1897]
Page source is different from page in browser. Therefore I need use puppeteer library or jsdom library.  

The page have tag "div" and many classes "bma-fly flying flying-won-team2 flying-past":
`<div class = "bma-fly flying flying-won-team2 flying-past"> `
How get  information from this tag???

I use code  [from](https://github.com/GoogleChrome/puppeteer/issues/489). (How to scrape an element #489)
If I use:   
`const text1 = await page.evaluate(() => document.querySelector("div.bma-fly.flying.flying-won-team2.flying-past").innerHTML);`
I get information only from first time this element is found. **How get other information where this tag and this class?** 

If not use `innerHTML` , I get: `{}` in console. _(I use Linux)._ 
If I save use `fs.writeFileSync("a07.txt" , text1); ` , I get `[object Object].` 
If I use `childNodes` I get `{ '0': {}, '1': {}, '2': {}, '3': {}, '4': {}, '5': {}, '6': {} }` in console. If I save this, I get: `[object Object]`.

Please, help me.

**Comment by vsemozhetbyt** [comment]
Can you add this information:
1. A small but complete code that you use to scrap the element, with page URL.
2. Example of expected data to get from the code.

**Comment by tyt34** [comment]
1) Code  which I use:
```

const puppeteer = require('puppeteer');
var fs = require('fs');

var link = "www. la la la . com";

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(link);
  const text2 = await page.evaluate(() => document.querySelector('.bma-fly.flying.flying-won-team2.flying-past').innerHTML);
  console.log(text2);
  fs.writeFileSync("a08.txt" , text2);
  browser.close();
})();
```
2) I want to get anything.
3) My link is secret information....

Бро, дай хоть какую нибудь наводку.... Пожалуйста.

**Comment by vsemozhetbyt** [comment]
Can you explain this:

> I get information only from first time this element is found. How get other information where this tag and this class?

What is missing? Do you miss some text or markup data? Or do you need data from other elements with this classes?

**Comment by tyt34** [comment]
On page:
```
<div class = "bma-fly flying flying-won-team2 flying-past"> la la la </div>
<div class = "bma-fly flying flying-won-team2 flying-past"> kyrlik kyrkik </div>
<div class = "bma-fly flying flying-won-team2 flying-past"> bo bo bo </div>
<div class = "bma-fly flying flying-won-team2 flying-past"> info </div>
<div class = "bma-fly flying flying-won-team2 flying-past"> privet chelovek </div>
```
Use 
 ` const text2 = await page.evaluate(() => document.querySelector('.bma-fly.flying.flying-won-team2.flying-past').innerText);`
I get:  **la la la** . 
How get info from div 2, div 3 etc ???

**Comment by Michaelknigth** [comment]
VPN Private!.txt
<https://drive.google.com/file/d/1sAv8RYyR8lDWo-Zuu_5lZMaOQuUj00o6/view?usp=drivesdk>

  http://www.bing.txt
<https://drive.google.com/file/d/1PQhsvjkko3mxbSEgMn2CaQz1duvU48On/view?usp=drivesdk>

**Comment by tyt34** [comment]
What is up????

**Comment by Michaelknigth** [comment]
¡Echa un vistazo!
<https://drive.google.com/file/d/1xCgGnKQZgwHGnLCLixZf_6yUa6XdruEb/view?usp=drivesdk>

**Comment by tyt34** [comment]
What is this???

**Comment by vsemozhetbyt** [comment]
I think this may be a spam)

**Comment by vsemozhetbyt** [comment]
Oh, I get it. Try this:
```js
    const texts = await page.evaluate(() => {
      return [...document.body.querySelectorAll('.bma-fly.flying.flying-won-team2.flying-past')]
               .map(element => element.innerText)
               .join('\n');
    });
```

**Comment by tyt34** [comment]
Yes. This is good. Огромное спасибо вам, который день пытаюсь эту проблему решить. Thankyou.
How this is work?

**Comment by vsemozhetbyt** [comment]
1. [`querySelectorAll()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) gets all the elements as a [`NodeList`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList).
2. `[... ]` makes this list a real array via [spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator).
3. `.map(element => element.innerText)` transforms this array of elements into an array of element's texts.
4. `.join('\n')` joins this array into a string with line breaks as delimiters.

**Comment by rustemkzk** [comment]
Is it possible to click on this text element? Really need to click on innertextElement.

Чел, как кликнуть на этот текст, для меня важно чтобы клик был именно на текст а не через селектор.

**Comment by vsemozhetbyt** [comment]
@rustemkzk Can you elaborate? (Не могли бы вы объяснить подробнее?)

**Comment by rustemkzk** [comment]
Здравствуйте, уже нашел как это решается. Необходимо было кликать через
текст а не через селектор, так как пишу бота для сайта на котором точно
буду знать название вещей, но их селекторы нет.
Строчка кода выглядит следующим образом:
await page.$$eval("a", as => as.find(a =>
a.innerText.includes("shop")).click());

**Comment by paulirish** [comment]
А, ну все, отлично! Пишите если нужна будет помощь!
