### ISSUE TITLE
page.on('console') no output in Kibana

### ISSUE THREAD

**Issue by MadHatter122312** [puppeteer/puppeteer#1898]
**Tell us about your environment:**

Puppeteer version: 0.13.0
Platform / OS version: 10.12.6
URLs (if applicable):
Node.js version: 8.9.0

**The issue:**

In my script I have added the line below to see logs in my terminal:

`page.on('console', (msg) => console.log('PAGE LOG:', msg.text));`

This works as intended on my local env and I see the output in terminal when I run the test.

However, when I deploy the Kibana log outputs this:

```
PAGE LOG: text() {
    return this._text;
  }
```

No exactly helpful...

Anyway to fix this?

**Comment by ohana54** [comment]
Looks like your CI environment is using puppeteer v1, the API for getting the text was changed from a property to a function.

**Comment by MadHatter122312** [comment]
@ohana54 Can you please clarify your answer for me.  What is the current proper way to generate a log in your cl?

**Comment by ohana54** [comment]
Use `msg.text()` instead, that's the new api from v1
