### ISSUE TITLE
Not all flags seem to work

### ISSUE THREAD

**Issue by Nantris** [puppeteer/puppeteer#1899]
I'm using Puppeteer 1.0.0.

I'm trying to enable `Javascript Harmony` in the browser, but none of the relevant flags seem to cause this to happen.

I've tried a number of things including:

```
  browser = await puppeteer.launch({
    headless: false,
    args: ['--js-flags="--harmony"', '--javascript-harmony']
  });
```

No luck though. The flag is always false in the browser and the features cannot be used. Other flags I've tried to ensure that flags were taking effect worked without issue, for example `--crash-test`. Any thoughts? Thanks for the fantastic project!

**Comment by aslushnikov** [comment]
Looks like all harmony features are enabled by default in Chrome 69 :)
