### ISSUE TITLE
Can't modify the request to spoof ip address

### ISSUE THREAD

**Issue by patrickpissurno** [puppeteer/puppeteer#1903]
I've read the docs, but cannot find a way to modify the loadPage request in a way that I can "force" an IP address. I know that it can be spoofed as back-end devs should not trust the header field containing the IP address. I need to spoof the IP, because I need to trick a server so that it "thinks" that I'm in Brazil and not in the US.

Is there any documented way to accomplish it?

**Comment by ntzm** [comment]
You can use the `--proxy-server=` argument when launching puppeteer, with a proxy server that is located in Brazil

**Comment by tomgallagher** [comment]
Puppeteer should really have the ability to modify the proxy used by an existing browser instance, rather than having to specify on launch.

**Comment by aslushnikov** [comment]
> Puppeteer should really have the ability to modify the proxy used by an existing browser instance, rather than having to specify on launch.

There's an issue for this: #678
