### ISSUE TITLE
Менеджер закладок ERROR

### ISSUE THREAD

**Issue by PVBKXWYUMYTJ** [puppeteer/puppeteer#1905]
Хром 64 (началось с 63), windows10 64 1709, в менеджере закладок не работают горячие клавиши(а функций в меню, заменяющих нет), очень редко они начинают работать (при открытии много любых вкладок все становится как прежде, после обновления до хром 64 первый день часто работали ), вирусов нет , удалил все программы результат тот же. WTF ?

> rum 64 (started with 63), windows10 64 1709, hotkeys do not work in the bookmark manager (and there are no functions on the menu that replace them), very rarely they start working (when you open many any tabs everything becomes as before, after upgrading to chrome 64 the first day often worked), no viruses, deleted all programs the same result. WTF?

**Comment by vsemozhetbyt** [comment]
Мне кажется, вы ошиблись репозиторием. Это репозиторий библиотеки для Node.js, управляющей Хромом в его невидимом (headless) режиме, а вы, похоже, сообщаете о проблемах в работе с самим браузером  в обычном пользовательском режиме.

"I think you made a mistake with the repository. This is a library repository for Node.js that controls Chrome in its invisible (headless) mode, and you seem to report problems with the browser itself in normal user mode."
