### ISSUE TITLE
Листинг вкладок ERROR*2

### ISSUE THREAD

**Issue by PVBKXWYUMYTJ** [puppeteer/puppeteer#1906]
1. При открытии 100-1000 вкладок (мой рекорд 5000 вкладок открытых, обычно 100-150), невозможно ими пользоваться , до того как пропадут значки сайтов   пусть появятся кнопки по бокам для пролистывания и дальше вкладки не уменьшаются.
2. При ctrl + tab листании , невозможно листать дальше при появлении всплывающего запроса местоположения и прочего из поисковой строки браузера , приходится кликать на браузер.

> If you open 100-1000 tabs (my record of 5000 tabs is open, usually 100-150), you can not use them, before the site icons disappear, let the buttons appear on the sides for scrolling and further the tabs do not decrease.
With ctrl + tab paging, it is impossible to scroll further when a pop-up request for a location appears and other things from the browser's search bar, you have to click on the browser.

**Comment by vsemozhetbyt** [comment]
Мне кажется, вы ошиблись репозиторием. Это репозиторий библиотеки для Node.js, управляющей Хромом в его невидимом (headless) режиме, а вы, похоже, сообщаете о проблемах в работе с самим браузером  в обычном пользовательском режиме.

**Comment by ebidel** [comment]
This sounds unrelated to the Puppeteer library.
