### ISSUE TITLE
The default "--disable-extensions" flag prevents puppeteer from working in some Windows environments

### ISSUE THREAD

**Issue by rhollman** [puppeteer/puppeteer#1907]
Not sure what changed within our Windows environment, but 3 different computers at work with functioning puppeteer-based testing tools stopped working.  

Upon running, would always get the 30s timeout that unable to connect despite using the included/local Chromium.  What was weird is that Chromium would open a window (despite headless:true) and have a "google api keys missing" message that hadn't seen before.

Took a lot trial and error, but if --disable-extensions is commented out in the source code, everything works as expected

* Puppeteer version: tested 0.13 and 1.0.0
* Platform / OS version: Windows 7 and Windows 10
* Node.js version: 8.94

**Comment by rhollman** [comment]
I've realized I can workaround this using existing API for now...

```
  const workingArgs = await PUPPETEER.defaultArgs().filter(flag => flag !== '--disable-extensions')
  const browser = await PUPPETEER.launch({
    ignoreDefaultArgs: true,
    args: workingArgs
  })
```

**Comment by hosseinalipour** [comment]
using v10.4.0 this worked:
```javascript
  const browser = await PUPPETEER.launch({
     ignoreDefaultArgs: ["--disable-extensions"]
  })
```

**Comment by icemonster** [comment]
Can someone provide some reasoning on why disable-extensions is passed by default? Would that make puppeteer less stable?

**Comment by shawnholmgren** [comment]
> I've realized I can workaround this using existing API for now...
> 
> ```
>   const workingArgs = await PUPPETEER.defaultArgs().filter(flag => flag !== '--disable-extensions')
>   const browser = await PUPPETEER.launch({
>     ignoreDefaultArgs: true,
>     args: workingArgs
>   })
> ```

thank you for this. it's the only solution that's worked after hours of researching the pesky popup.
