### ISSUE TITLE
The  webpage is saved as a PDF, i use "printBackground:'true'" ,the background is Incomplete.

### ISSUE THREAD

**Issue by 767994269** [puppeteer/puppeteer#1912]
Environment:

Puppeteer: 1.0.0
Platform / OS: windows x64
Node.js: 8.9.0
Chromium: 66.0.3335.0 (Developer Build) (64-bit)
What steps will reproduce the problem?

Running the following code several times.

const puppeteer = require('puppeteer');

(async () => {

  const browser = await puppeteer.launch({
        executablePath: './chromium/chrome.exe',
        headless: true
  });
  const page = await browser.newPage();
  await page.goto('xxx');
  await page.waitForSelector('xxx');
  await page.emulateMedia('print');
  await page.pdf({path:'hn.pdf', format: 'A4',printBackground:'true'});
  await browser.close();
})();
What is the expected result?

i expect the background is complete

What happens instead?

when i save as a PDF file , the background is incomplete

**Comment by joshribakoff** [comment]
You'd have to provide the real code, not with "xxx" as a placeholder. This depends on the page & options you're passing, which you've redacted.

That being said, it looks like you're not telling it to block until the page's assets load. Try this.
```js
await page.goto("http://hackernews.ycombinator.com", {
      waitUntil: "networkidle0"
    });
```

**Comment by 767994269** [comment]
@joshribakoff  I have found the reason, because the background picture is set to "no-repeat center center fixed", if I annotate "no-repeat center center fixed", all OK.

**Comment by 767994269** [comment]
@joshribakoff  by the way ,My test environment has a IP limit, and you can't access it,thanks.
