### ISSUE TITLE
Don't load images, CSS and JS

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#1913]
Hello,

I've searched on stackOverflow and I found nothing about this so this might be a request.
I'd like to load the HTML content of the page only. I've tried to input : 
`page.goto{url, {waitUntil: 'domcontentloaded'})`
But it waits for a full page load and takes too long...

**Comment by lazharichir** [comment]
@Nicolas-vrcc  you can do that (i think) by using view-source:https://theurl.com for example `page.goto{'view-source:https://google.com/', {waitUntil: 'networkidle2'})
 `

**Comment by lazharichir** [comment]
Oh no, my bad, this adds a bunch of html tags and css...

**Comment by Nicolas-vrcc** [comment]
@lazharichir Thank you but its not loading the page. It only shows the source code. I'd like the html code only to display

**Comment by labnol** [comment]
Enable request interception and abort requests for fonts, images, JavaScript, css, etc.

```
page = await browser.newPage();
await page.setRequestInterception(true);
page.on('request', (request) => {
    if (['image', 'stylesheet', 'font', 'script'].indexOf(request.resourceType()) !== -1) {
        request.abort();
    } else {
        request.continue();
    }
});
```

**Comment by Nicolas-vrcc** [comment]
@labnol Thank you very much for your answer, can you give an example of how to setup that for a given url, for example https://www.google.com ?

**Comment by Nicolas-vrcc** [comment]
@labnol Thank you it worked ! Do you know how to disable it for one page only and enable it again later in the code ?

**Comment by ebidel** [comment]
@Nicolas-vrcc try `page.once` ([docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-page)) or intercept the url you're interested in and ignore everything else. If you do the first option, make sure to call `page.setRequestInterception(false);` after you've seen the url.

**Comment by Tokenyet** [comment]
This should be notice that, @labnol 's method might cause a bunch of browser errors. It could affect the CPU usage to 100% because of pages keep spaming error log, and make your http request failed on high probability.

For someone who has same issue with this, you might have same sineriao with me. 

       page.on('request', (request) => {
            if (['image', 'stylesheet', 'font'].indexOf(request.resourceType()) !== -1) {
                request.abort();
            } else {
                request.continue();
            }
       });

Maybe this is a bad idea for communicating with site and disable other resources together?

**Comment by atsepkov** [comment]
Does anyone know how to suppress the warnings of `Failed to load resource: net::ERR_FAILED` I start seeing for every aborted request after adding the above logic to my code?

**Comment by piotrek132** [comment]
@atsepkov 
> Does anyone know how to suppress the warnings of `Failed to load resource: net::ERR_FAILED` I start seeing for every aborted request after adding the above logic to my code?
```
page.on('request', (request) => {
      request._interceptionHandled = false;
      if (['image', 'stylesheet', 'font'].includes(request.resourceType())) {
        request.respond({
          status: 200,
          body: "foo"
        })
      } else {
        request.continue();
      }
    });
```
remeber about 
```
await page.setRequestInterception(true);

```

**Comment by thearchitgarg** [comment]
Does it actually let it load the page with more speed? I tried it but the stats are quite same.

**Comment by ecolss** [comment]
> Enable request interception and abort requests for fonts, images, JavaScript, css, etc.
> 
> ```
> page = await browser.newPage();
> await page.setRequestInterception(true);
> page.on('request', (request) => {
>     if (['image', 'stylesheet', 'font', 'script'].indexOf(request.resourceType()) !== -1) {
>         request.abort();
>     } else {
>         request.continue();
>     }
> });
> ```

Great answer!!
However, if someone doesn't need to load the `js`, then why use puppeteer at the first place?
Because I think the reason why I use puppeteer is I need to load the `js` so that the html could be fully rendered, and then I could get the data I want.

**Comment by moeinrahimi** [comment]
```
   await page.setRequestInterception(true)
    page.on('request', (request) => {
      if (['image', 'stylesheet', 'font','other'].includes(request.resourceType())) {
        request.abort();
    } else {
        request.continue();
    }
    });
```
websites using tools like vuejs or react need js to parse web page, I found excluding the above types most useful to save time.

**Comment by manuelbiermann** [comment]
Has anyone encountered a problem where the interception only works on the first page loaded?

**Comment by aditodkar** [comment]
@labnol Instead of image can we just block jpeg and png images? I want to download webp images but block png and jpeg images. Can that be done? Any suggestions?
