### ISSUE TITLE
web whatsapp no work in headless mode

### ISSUE THREAD

**Issue by nicobytes** [puppeteer/puppeteer#1914]
when headless is true, not work why? is an issue from puppeteer?

I try run 'web.whatsapp.com' and take screenshot http://i.cubeupload.com/RmJXwC.png with headless mode

**Comment by ebidel** [comment]
Try changing the userAgent and/or adjusting the [viewport](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport) size. Most likely, they're detecting that you're on a "mobile device" or using an automated browser.

```js
await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36');
```

worked for me:

<img width="758" alt="screen shot 2018-01-29 at 8 27 35 am" src="https://user-images.githubusercontent.com/238208/35521324-4ce5e54e-04ce-11e8-89f8-202600249262.png">

**Comment by athiselvam** [comment]
Hi, I'm facing the same. I've tried setting user agent and viewport for chromedriver. but still, I'm getting the same error.

please help me to resolve.

Thanks in advance.

-- Aadhi

**Comment by iagopiimenta** [comment]
Same error here.

```js
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({
    executablePath: 'google-chrome-unstable',
  });

  const page = await browser.newPage();
  await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36');
  await page.setViewport({ width: 1000, height: 728 })

  // worked
  await page.goto('https://web.whatsapp.com/');
  await page.screenshot({ path: 'screenshot1.png' });
  // WhatsApp works with Google Chrome 36+
  await page.goto('https://web.whatsapp.com/');
  await page.screenshot({ path: 'screenshot2.png' });
})();
```

![image](https://user-images.githubusercontent.com/5642707/55677061-a7dc4180-58b7-11e9-9603-1508b677ee4f.png)

**Comment by odravison** [comment]
> Same error here.
> 
> ```js
> import puppeteer from 'puppeteer';
> 
> (async () => {
>   const browser = await puppeteer.launch({
>     executablePath: 'google-chrome-unstable',
>   });
> 
>   const page = await browser.newPage();
>   await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36');
>   await page.setViewport({ width: 1000, height: 728 })
> 
>   // worked
>   await page.goto('https://web.whatsapp.com/');
>   await page.screenshot({ path: 'screenshot1.png' });
>   // WhatsApp works with Google Chrome 36+
>   await page.goto('https://web.whatsapp.com/');
>   await page.screenshot({ path: 'screenshot2.png' });
> })();
> ```
> 
> ![image](https://user-images.githubusercontent.com/5642707/55677061-a7dc4180-58b7-11e9-9603-1508b677ee4f.png)

I'm with the same error. Trying to use this userAgent:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36`

**Comment by aviwad** [comment]
same issue

**Comment by odravison** [comment]
Hi, guys. I'm using this userAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3641.0 Safari/537.36` and works!

**Comment by alejandrogih** [comment]
Correct, it works changing the agent and thanks for the tip!

**Comment by firozzer** [comment]
Does someone know how to resuse a saved session in Headless mode? When I try to reuse nothing happens and i think the code gets stuck.

**Comment by LucasPonzo** [comment]
> Does someone know how to resuse a saved session in Headless mode? When I try to reuse nothing happens and i think the code gets stuck.

Save localStorage to json file then read it and write localStorage based on the saved file. It works for me:

async function restoreSession(page) {
    try {
        //
        const previousSession = fs.existsSync(localStoragePath)
        if (previousSession) {
            //
            const localStorageObj = JSON.parse(fs.readFileSync(localStoragePath, 'utf8'));
            const localStorageKeys = Object.keys(localStorageObj);
            //
            for (let i = 0; i < localStorageKeys.length; i++) {
                const localStorageKey = localStorageKeys[i];
                const localStorageVal = localStorageObj[localStorageKey]; 
                try {
                    await page.evaluate( (key, val) => {
                        localStorage.setItem(key, val);
                    }, localStorageKey, localStorageVal);
                }
                catch (ex) {
                    console.log('Error writing local storage', ex.message);
                }
            }
        }
    }
    catch(ex) {
        console.log('restoreSession()', ex.message);
    }
}

**Comment by LucasPonzo** [comment]
> Hi, guys. I'm using this userAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3641.0 Safari/537.36` and works!

Not working in Ubuntu 18 headless, same error as other posts. But it works on Windows Server.

**Comment by daniel-scatigno** [comment]
I have change the user agent and it works for me.
I also have these optional arguments:
   ```
   option.AddArgument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36");
      option.AddArgument("user-data-dir=" + Path.Combine(LibraryDir, ownerId.ToString()));
      option.AddArguments("start-maximized"); // https://stackoverflow.com/a/26283818/1689770
      option.AddArguments("enable-automation"); // https://stackoverflow.com/a/43840128/1689770
      option.AddArguments("--window-size=1360,765");
                                                //option.AddArguments("--headless"); // only if you are ACTUALLY running headless
      option.AddArguments("--no-sandbox"); //https://stackoverflow.com/a/50725918/1689770
      option.AddArguments("--disable-infobars"); //https://stackoverflow.com/a/43840128/1689770
      option.AddArguments("--disable-dev-shm-usage"); //https://stackoverflow.com/a/50725918/1689770
      option.AddArguments("--disable-browser-side-navigation"); //https://stackoverflow.com/a/49123152/1689770
      option.AddArguments("--disable-gpu");
```

**Comment by christianr11** [comment]
> Hi, guys. I'm using this userAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3641.0 Safari/537.36` and works!

This works for me

**Comment by AmilcarAppel** [comment]
> Hi, guys. I'm using this userAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3641.0 Safari/537.36` and works!

Fantastic, it saved my day!

**Comment by biplabmon** [comment]
> Hi, guys. I'm using this userAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3641.0 Safari/537.36` and works!

I'm using windows 11, but it was not working for me. Does anyone have any working solutions?

**Comment by Cyw00d** [comment]
english?
