### ISSUE TITLE
Puppeteer with Chrome Headless vs Chromium Headless

### ISSUE THREAD

**Issue by MadHatter122312** [puppeteer/puppeteer#1915]
I understand that is is possible to run this without the Chromium packaged with puppeteer.  But if you use the version of Chrome already installed on your machine like so:

`const browser = await puppeteer.launch({executablePath: '/path/to/Chrome'});`

How much trouble can I expect?  It seems that puppeteer relies heavily on a specific version of Chromium...Is this wise? 

I know I can get Chrome  to run on my RHEL 6.4, but I am having trouble with this packaged version of Chromium.

**Comment by ebidel** [comment]
You'll want to make sure that the version you run is Chrome is 65.  If that package isn't available on your platform, you could install an earlier version of Puppeteer (which would use an earlier version of Chromium). For example, the latest version on Alpine is Chromium 63, which corresponded to Puppeteer 0.11.0.
