### ISSUE TITLE
HAR details in file or jSON 

### ISSUE THREAD

**Issue by luckyhughes** [puppeteer/puppeteer#1916]
Hi,

I was spiking on the puppeter tool for performance metrics and automation from browser. overall satisfactory for navigation and ease to automate. I am looking to add performance analysis like time spent on dns, xhr calls, TTFB and javascript rendering etc. is there any way to generate HAR json or file by enabling any flag or any other way to capture the asked details.

Thank you.
--Sandeep

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by Everettss** [comment]
There is no HAR generator helper in Puppeteer. But you can use [`chrome-har`](https://www.npmjs.com/package/chrome-har) to generate HAR file.

```javascript
const fs = require('fs');
const { promisify } = require('util');

const puppeteer = require('puppeteer');
const { harFromMessages } = require('chrome-har');

// list of events for converting to HAR
const events = [];

// event types to observe
const observe = [
  'Page.loadEventFired',
  'Page.domContentEventFired',
  'Page.frameStartedLoading',
  'Page.frameAttached',
  'Network.requestWillBeSent',
  'Network.requestServedFromCache',
  'Network.dataReceived',
  'Network.responseReceived',
  'Network.resourceChangedPriority',
  'Network.loadingFinished',
  'Network.loadingFailed',
];

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // register events listeners
  const client = await page.target().createCDPSession();
  await client.send('Page.enable');
  await client.send('Network.enable');
  observe.forEach(method => {
    client.on(method, params => {
      events.push({ method, params });
    });
  });

  // perform tests
  await page.goto('https://en.wikipedia.org');
  page.click('#n-help > a');
  await page.waitForNavigation({ waitUntil: 'networkidle2' });
  await browser.close();

  // convert events to HAR file
  const har = harFromMessages(events);
  await promisify(fs.writeFile)('en.wikipedia.org.har', JSON.stringify(har));
})();
```
[Here](https://michaljanaszek.com/blog/generate-har-with-puppeteer) you can find an article about this solution.

**Comment by ebidel** [comment]
@Everettss amazing! Would be interested in contributing that to the examples dir? Happy to review a PR.

**Comment by DrNBG** [comment]
Just tried the above code. Did the trick!
Thanks for sharing the code.

**Comment by DrNBG** [comment]
Can we also capture screenshots along?

**Comment by Everettss** [comment]
@ebidel I am happy to make a PR with this example. But for now have a new simpler version:

```javascript
const puppeteer = require('puppeteer');
const PuppeteerHar = require('puppeteer-har');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    const har = new PuppeteerHar(page);
    await har.start({ path: 'results.har' });

    await page.goto('http://example.com');

    await har.stop();
    await browser.close();
})();
```

**Comment by ebidel** [comment]
Nice! In that case, let's stick a link to the npm project under https://github.com/GoogleChrome/puppeteer/tree/master/examples#other-resources?

**Comment by aslushnikov** [comment]
If anyone's interested, feel free to send a PR as @ebidel suggested.

**Comment by raviasheesh** [comment]
@Everettss : I tried the simple one, but all of the requests are not coming in har file. It seems puppeteer is running much faster. I added : await page.waitForNavigation({
       waitUntil: ['load', 'domcontentloaded'],
       waitLoad: true,
       waitNetworkIdle: true
    });
just before stopping har i.e. har.stop();
Id there any other way to try or add delay so that all the requests are captured and included in generated har file?

My Code:

**Comment by chen1-CN** [comment]
> @ebidel我很高兴通过此示例进行PR。但现在有一个新的更简单的版本：
> 
> ```js
> const  puppeteer  =  require （'puppeteer' ）; 
> const  PuppeteerHar  =  require （'puppeteer-har' ）;
> 
> （异步 （） =>  { 
>     const的 浏览器 =  AWAIT  木偶。发射（）; 
>     const的 页 =  AWAIT  浏览器。NEWPAGE （）;
> 
>     const  har  =  new  PuppeteerHar （页面）; 
>     等待 哈尔。开始（{  path：'results.har'  } ）;
> 
>     等待 页面。goto （'http://example.com' ）;
> 
>     等待 哈尔。停止（）; 
>     等待 浏览器。关闭（）; 
> } ）（）;
> ```

but why the response content is undifined in my har file,how can I get the response body ?
![image](https://user-images.githubusercontent.com/71018546/94411953-c91ba680-01ab-11eb-91b8-a5ad202292f5.png)
![image](https://user-images.githubusercontent.com/71018546/94412110-fd8f6280-01ab-11eb-8de2-8853d590efba.png)

**Comment by antibarbie** [comment]
Same behaviour here. Cannot save the response contents. Saw no snippets and the documentation is cryptic.

did someone managed to push that information into the .HAR file ?

**Comment by raknjarasoa** [comment]
@chen1-CN @antibarbie You can just use the below snippets:
```js
await har.start({ path: 'results.har', saveResponse: true, captureMimeTypes: ['image/jpeg', 'text/html'] });
```

**Comment by subject-21** [comment]
Hi I'm having a problem to fetch har while browser already open, thus the page events array like 'Page.loadEventFired' is empty and chrome-har returns nothing. anyone knows how to solve this?

**Comment by subject-21** [comment]
@ebidel @aslushnikov @Everettss @raviasheesh @luckyhughes
