### ISSUE TITLE
Feature request: URL or File blacklisting

### ISSUE THREAD

**Issue by joseramonc** [puppeteer/puppeteer#1917]
When I load a page, I don't want to download all the associated scripts and stylesheets. Instead, I'd like to blacklist some files.

**What is the expected result?**
Download the page HTML without the blacklisted files present in <script> or <style> tags.

**What happens instead?**
Download all the resources

**Comment by ebidel** [comment]
Does request interception not address the use case? Abort the request if the URL is in the blacklist.

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue

**Comment by joseramonc** [comment]
Sorry, yes, that completely satisfies what I'm trying to do. Thanks!
