### ISSUE TITLE
Strange characters - font issue ?

### ISSUE THREAD

**Issue by cruiser12** [puppeteer/puppeteer#1918]
* Puppeteer version:  latest
* Platform / OS version:  CentOS 7
* URLs (if applicable): https://de.baerkarrer.ch/ueber-uns/news/
* Node.js version: 8.9

Arial Font renders with strange characters on screenshot. Whole page is like that

![image](https://user-images.githubusercontent.com/133954/35545468-8638f92a-056f-11e8-9918-15e6c6a32d3d.png)

Anybody an Idea why this is happening. Other websites are fine so far.

Kind regards

Chris

**Comment by ebidel** [comment]
Is it possible you're missing font dependencies on your system? There's info in https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md.

**Comment by cruiser12** [comment]
```
yum -y install ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc
yum -y install liberation-mono-fonts  liberation-narrow-fonts liberation-sans-fonts  liberation-serif-fonts

```
now its fine. thx.

**Comment by codesmith55** [comment]
I can't seem to find corresponding homebrew packages to fix this problem for OSx, has anyone solved this?

**Comment by aakashkharche04** [comment]
I am facing the same problem in headers and footers when I am running in docker environment. The following statements mentioned in the documentation do not work in dockerfile while building an image locally. 

``
RUN apt-get update && apt-get install -y wget --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove -y curl \
    && rm -rf /src/*.deb
``

It gives the following error 
a) apt-get command not found.

I have tried using alpine as well, but that also gives the same error ``apk`` command not found

How can I get the font packages using ``yum``

**Comment by primetheus** [comment]
>I can't seem to find corresponding homebrew packages to fix this problem for OSx, has anyone solved this?

This would need to be installed on the X11 server, rather than the client. For me, this was the only thing required: `yum -y install xorg-x11-fonts-Type1`
