### ISSUE TITLE
Command Line Api: cannot not access

### ISSUE THREAD

**Issue by mydreambei-ai** [puppeteer/puppeteer#1919]
I got an all listenners of an element   via the following two methods, but  failed.
 1. 
  ```
    const getEvents =  await page.evaluateHandle(() => window.getEventListeners);
    console.log(await getEvents.jsonValue()); 
   // always undefined
  // I tried other command line api , all failed.
  ```

2. 
```
     const client = await page.target().createCDPSession();
      await page.$("#myBtn1").then(async ele=>{
            console.log(ele._remoteObject.objectId, typeof ele._remoteObject.objectId);
           await client.send('DOMDebugger.getEventListeners', {objectId:  ele._remoteObject.objectId}).catch(e=>{});
 })
    
 // ele._remoteObject like this:    
     { type: 'object',
     subtype: 'node',
     className: 'HTMLButtonElement',
     description: 'button#myBtn1',
     objectId: '{"injectedScriptId":2,"id":2}' }

puppeteer always report Error: Protocol error (DOMDebugger.getEventListeners): Could not find object with given id undefined, why?
  ```

Is there any other way to get all listenners?

**Comment by aslushnikov** [comment]
@lmyyao you cannot reuse object ids from different sessions. You'll need to fetch the remote object through the newly created cdp session.

**Comment by mcshaman** [comment]
I didn't the OP was given a sufficient enough information to their post before it was closed. I too have have been trying to find work out how to get access to the the window.getEventListeners. Being new to Puppeteer, having no previous experience with the Chrome DevTools Protocol and finding the documentation pretty thin I found it pretty arduous to work out the following solution.

``` javascript
(async () => {
	const browser = await puppeteer.launch()
	const page = await browser.newPage()
	await page.goto('https://example.com')
	const client = await page.target().createCDPSession()

	// Return object that you want to get event listeners from e.g. the window object or any other DOM element
	const {result} = await client.send('Runtime.evaluate', {expression: 'window'})
	const {listeners} = await client.send('DOMDebugger.getEventListeners', {objectId: result.objectId})
	console.log(listeners) // empty in this instance because there are no registered listeners
})
```

Hopefully this is useful to somebody and you don't have to spend as much time as I did trying to work this out.

BTW let me know if there is a better solution.

**Comment by sangiiii** [comment]
@mcshaman Thanks for that. It  was really very helpful. 
Is it possible to trace back to handler functions? I found in the [protocol viewer](https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger#type-EventListener) that the `EventListener` type actually has a property called `handler` .
The `DOMDebugger.getEventListeners` will return a array of EventListeners, But I don't see any `handler` property. It's optional BTW (as mentioned in the protocol viewer). Is there any other way we can find the handler function?

Just trying to figure out an equivalent solution like the below command line API
<img width="1680" alt="screen shot 2018-10-03 at 3 32 11 am" src="https://user-images.githubusercontent.com/6672359/46379615-f1579400-c6bc-11e8-940f-819a6b56a144.png">
Thoughts?

**Comment by Faberle** [comment]
It would be perfect if we could pass the parameter `includeCommandLineAPI` ([see doc](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate))  that is available in the DevTools protocol when we call `page.evaluate(func)` 
That allows us to run the same code in puppeteer and our normal browser console.

**Comment by aslushnikov** [comment]
@Faberle we use [`Runtime.callFunctionOn`](https://vanilla.aslushnikov.com/#Runtime.callFunctionOn) to run evaluations so that we can pass over JSHandles over. This doesn't have a command-line API plumbed in; feel free to send patches upstream to add it there; once done, it'd be easy to support this.

**Comment by bv-sumit** [comment]
@mcshaman the solution you have mentioned used to work in the older puppeteer version. It didnt work in the latest puppeteer version 19.
I think it is because the whole directory structure is changed. 

Any suggestions?

**Comment by bv-sumit** [comment]
> @mcshaman the solution you have mentioned used to work in the older puppeteer version. It didnt work in the latest puppeteer version 19. I think it is because the whole directory structure is changed.
> 
> Any suggestions?

https://stackoverflow.com/questions/75517220/geteventlistener-function-support-for-latest-puppeteer-versions/75581410#75581410
I have mentioned the solution in the above link. If anyone is facing the issue you can refer.
