### ISSUE TITLE
Setting timeout: 0 in waitForFunction does not remove default timeout condition

### ISSUE THREAD

**Issue by isaachinman** [puppeteer/puppeteer#1920]
**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

    await page.waitForFunction(
        () => document.querySelector('.loading-item').getAttribute('something') === 'takes a long time',
        { timeout: 0 })

**What is the expected result?**

That `waitForFunction` will continue waiting without limit

**What happens instead?**

I get the following error:

> Error: waiting failed: timeout 30000ms exceeded at Timeout.WaitTask._timeoutTimer.setTimeout

**Thoughts**

Maybe this is by design? Perhaps it is bad practice to query the page without a timeout in place, but my use case is file uploads, wherein I have no idea the network speed, so I cannot calculate a reasonable timeout.

Moreover, `page.waitForNavigation` has a [timeout override](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions).

Any other thoughts here?

**Comment by ebidel** [comment]
This has been fixed in https://github.com/GoogleChrome/puppeteer/pull/1964. Will be available in the next release.
