### ISSUE TITLE
Page throws timeout exception only in headless mode

### ISSUE THREAD

**Issue by marijanlekic** [puppeteer/puppeteer#1922]
**Tell us about your environment:**

* Puppeteer version: puppeteer@next (latest commit)
* Platform / OS version: macOS High Sierra 10.13.1
* URLs (if applicable): http://www.sanident.it
* Node.js version: v8.6.0

**What steps will reproduce the problem?**
```
  const browser = await puppeteer.launch({
    headless: true,
  });

  const page = await browser.newPage();
  await page.goto("http://www.sanident.it", {timeout: 10000});
  console.log(await page.content());
```

**What is the expected result?**

Promise does not throw "Navigation Timeout Exceeded" no matter if using headless or non-headless mode.

**What happens instead?**

Promise throws "Navigation Timeout Exceeded" ONLY in headless mode. In non-headless it works fine. This does not work also in v0.13.0 **BUT IT WORKS** in v0.12.0

**Comment by ebidel** [comment]
I can confirm that this timeouts in headless and not headful mode. Perhaps the site does some kind of headless/automation sniffing and something is blocking the page from finishing?

**Comment by zhanghuanchong** [comment]
I had same error, but navigation was caused by click event. Resolved according to the [API document](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageclickselector-options), with sample code snippet:
```js
const [response] = await Promise.all([
  page.waitForNavigation(waitOptions),
  page.click(selector, clickOptions),
]);
```

**Comment by nnn406** [comment]
@zhanghuanchong and what was your waitOptions?

**Comment by zhanghuanchong** [comment]
@nnnikolay I use nothing. This parameter is optional.

Some other people also recommend using:
```js
page.click(selector, clickOptions)
await page.waitForNavigation()
```

Which works for me too.

**Comment by nnn406** [comment]
@zhanghuanchong pretty sure that it works, but the question is what the options is in you `waitOptions` object?

**Comment by mcpwns** [comment]
@marijanlekic Were you able to resolve the issue?

**Comment by marijanlekic** [comment]
@mcpwns 

In this case {waitUntil: "networkidle2"} worked for me. I found out that this works for me the best in most situations.

**Comment by aslushnikov** [comment]
Works fine for me on tip-of-tree f8cba455ba5d1bc82721e89fda037e86213b02cb:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  await page.goto('http://www.sanident.it');
  console.log(page.url());
  await browser.close();
})();
```

**Comment by VincentCharpentier** [comment]
I ended up on this thread because I was doing `page.goto('localhost:3000')` instead of `page.goto('http://localhost:3000')`. The protocol seems mandatory in headless mode.
Hope this helps

**Comment by yyynnn** [comment]
This should be documented somewhere.

In headless mode browser cache is PRESERVED, so you can't catch all of your precious requests!
But in 'headful' mode cache somehow gets reset.
Just do this:

```javascript
const goto = async url => {
  const page = await browser.newPage()
  await page.setCacheEnabled(false) // <-- this one is a game changer
  await page.goto(url)
  return page
}

// somewhere
await goto('http://MY_URL:666') 
```

**Comment by wobsoriano** [comment]
Can confirm this with puppeteer 2.1.1 running in windows and mac.

```javascript
const puppeteer = require('puppeteer');
const url = 'https://www.youtube.com/channel/UCxhygwqQ1ZMoBGQM2yEcNug/videos';

async function run() {
  try {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    await page.goto(url, { waitUntil: 'networkidle2' });
    await page.waitForSelector('#items');
    const html = await page.evaluate(() => document.body.innerHTML);
    // Throws TimeoutError when headless is set to true
  } catch (e) {
    console.log(e);
  }
}

run();
```

**Comment by kirosc** [comment]
Some websites block headless useragent. You might try to change that.
```js
await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36');
await page.goto('http://www.sanident.it/');
```

**Comment by thiscompsciguy** [comment]
As a workaround:

`
    const browser = await puppeteer.launch({
        headless: false,
        args:['--headless']
    });
`

**Comment by Namanmittal0007** [comment]
Using puppeteer@10.4.0
@kirosc, have tried setting userAgent still no resolution. Facing the navigation timeout issue intermittently. Seems like issue is not with the userAgent.
```

        const browser = await puppeteer.launch({defaultViewport:null, headless:true})
        const page = await browser.newPage()
        await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36');
        await page.goto(RecLoginPageUrl)
        await page.type(loginPageUsernameSelector, RecUsername,{delay:100})
        await page.type(loginPagePasswordSelector, RecPassword,{delay:100})
        await utility.waitAndClick(page,loginPageSubmitBtnSelector)
        console.log("Clicked submit on Login page");
        
        await page.waitForNavigation({waitUntil:'load', timeout:60000})
        await page.click(mPowerSearchBtnSelector)
        console.log("Clicked mPower on Dashboard");
        
        await page.waitForNavigation({waitUntil:'load', timeout:60000})
        await utility.waitAndClick(page,v4SearchBtnSelector)
        console.log("Clciked Search btn on V4Search");
        
        await page.waitForNavigation({waitUntil:'networkidle0', timeout:60000})
        console.log("On V4 SRP");
        let loadtime =await page.evaluate(_=>{
            const {navigationStart, loadEventEnd} = performance.timing
            return Promise.resolve(loadEventEnd - navigationStart ) 
        })
        browser.close()
```

**Comment by fclebio** [comment]
In my case I forced the resolution I used in development and it worked normally

```
     const browser = await puppeteer. Launch({
                headless: true,
                defaultViewport: { width: 1280, height: 1600 },
                userDataDir: "./tmp",
        });

```

**Comment by john-doherty** [comment]
I can confirm, setting the `defaultViewPort` at launch solved my issue. Thanks @fclebio

**Comment by matieg** [comment]
> Algunos sitios web bloquean el agente de usuario sin interfaz gráfica. Podrías intentar cambiarlo.
> 
> await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36');
> await page.goto('http://www.sanident.it/');

Excellent, it worked for me.
