### ISSUE TITLE
Object handles in place of selectors?

### ISSUE THREAD

**Issue by dowsanjack** [puppeteer/puppeteer#1927]
So, I am looking to do something like this

```
let selectors = await page.$$('select')
for (const selector of selectors) {
  await page.select(selector, value)
}
```

I understand JSHandles was made to cover use cases like this, but its use is not very clear in the docs. Any Tips?

**Comment by yanivefraim** [comment]
@dowsanjack - what about:

```
await page.$$eval('select', elements => 
  elements.forEach(element => --do your thing with your element--)
);

**Comment by kidwm** [comment]
@yanivefraim please make `page.select` able to accept elementHandle, that would make changing select value more easier
