### ISSUE TITLE
 Navigation Timeout Exceeded only in pm2

### ISSUE THREAD

**Issue by githoniel** [puppeteer/puppeteer#1932]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Window Server 2016 x64 10.0.14393
* Node.js version: 8.9.3 

**What steps will reproduce the problem?**

I wrote a spider and publish in my server.
``` js
// part of task.js
const browser = await this._getPuppeteer()
const page = await browser.newPage()
await page.goto(this.constEntryPage)
await page.content()
```
url is a local netWork Address`http://10.10.33.18/hm`.

this code run well when use 'node task.js'

When i run it with PM2 use 'pm2 start pm2.config.js', I got Error
```bash
1|schedule | Error: Navigation Timeout Exceeded: 30000ms exceeded
1|schedule |     at Promise.then (C:\node\address-spider\node_modules\puppeteer\lib\NavigatorWatcher.js:71:21)
1|schedule |     at <anonymous>
```

It's OK to open the page if i use IE/Chrome to open the same url, even i use the Chromium in the node_modules folder.

I was working this problem for a week....just not understand why.

**What is the expected result?**

open the page normally

**What happens instead?**

Navigation Timeout Exceeded

**Comment by chenxsan** [comment]
Have you ever tried upgrade pm2? I saw a similar problem when running my node app with pm2, but after pm2 upgraded, the problem was gone.

**Comment by aslushnikov** [comment]
@githoniel there's been another pm2 issue on the bugtracker: https://github.com/GoogleChrome/puppeteer/issues/1760

Other than that, I don't think I can somehow help here. We don't have much experience with pm2. I'd recommend going to pm2 github repo.

**Comment by itsTeknas** [comment]
This is a problem I'm facing in my ubuntu server. I tried running the app with nodemon and that works fine. Is this a puppeteer issue or a pm2 issue ?
