### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by rustemkzk** [puppeteer/puppeteer#1935]
Is it possible to solve captcha manually? I want special window with captcha only, where i could solve captcha manually. So, all script will be written in headless chrome, but i want special window to solve captcha.

Добрый день. Хотел бы уточнить, возможно ли создание специального окна для вывода каптчи. То есть, весь скрипт будет написан в хедлесс хроме, но вывод каптчи осуществляется в специальном окне(где будет только капча, без остальной страницы). Возможно ли это сделать?

**Comment by vc1** [comment]
uiBrowser = await puppeteer.launch({ headless: false })
uiPage = ...
// open website , type captcha,  login
cookies = await uiPage.cookies(url)
// OR  cookies = (await page._client.send('Network.getAllCookies')).cookies

headlessBrowser = await puppeteer.launch({ headless: true })
headlessPage = ...
headlessPage.setCookies(cookies)
...

**Comment by vc1** [comment]
+1
I want to know what package can pop up the system dialog box, can display the picture, enter a string

this is window10 notice
![image](https://user-images.githubusercontent.com/9018903/35633015-33987a18-06e3-11e8-9036-f62ee7fea7d7.png)

These packages can not display pictures
https://github.com/bat-tomr/dialog-node
https://github.com/mikaelbr/node-notifier

**Comment by ebidel** [comment]
Dupe of https://github.com/GoogleChrome/puppeteer/issues/473

**Comment by KrisWu-188** [comment]
Has the problem been solved? I also want to know how to solve captcha by hand
