### ISSUE TITLE
When a frame fails to load due to a mixed content issue, the main Page is never considered loaded.

### ISSUE THREAD

**Issue by BenoitZugmeyer** [puppeteer/puppeteer#1936]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: ArchLinux (up to date)
* URLs (if applicable): https://pste.eu/p/awIC.html
* Node.js version: 9.4.0

**What steps will reproduce the problem?**

Try to load a HTTPS URL including an `iframe` with a HTTP `src` (normally blocked with a message like: `Mixed Content: The page at '...' was loaded over HTTPS, but requested an insecure resource '...'. This request has been blocked; the content must be served over HTTPS.`)

Check this example:
```js
"use strict";
const puppeteer = require("puppeteer");
const url = "https://pste.eu/p/awIC.html";

(async () => {
    const browser = await puppeteer.launch({
        args: [ "--no-sandbox", "--disable-gpu" ]
    });
    const page = await browser.newPage();
    await page.goto(url);
    await browser.close();
})();
```
<details>
  <summary>Content of https://pste.eu/p/awIC.html</summary>

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />
</head>
<body>
    <iframe src="http://github.com/"></iframe>
</body>
</html>
```

</details>

<br />

**What is the expected result?**

The page loads. `page.goto(...)` returns a resolved promise.

**What happens instead?**

The page never loads. `page.goto(...)` returns with a rejected promise after a 30 seconds timeout (`Error: Navigation Timeout Exceeded: 30000ms exceeded`).

### Notes

As far as I understand, this is because the `iframe` never triggers the `load` event, and the `NavigatorWatcher` iterates over all iframes to check if a `load` event occured before resolving the `navigationPromise`. This issue may need some devtools protocol additions to be fixed.

**Comment by BenoitZugmeyer** [comment]
Shower thought: on top of this, it would be great to have a `"requestfailed"` event triggered, in the same way loading a script with a mixed content issue fails.

**Comment by GregRos** [comment]
To be honest, I've found the promise returned by `goto` to be pretty unreliable in general. I've resorted to injecting some code that manually subscribes to events like `DOMContentLoaded` and `load`.

**Comment by iszmidt** [comment]
I'm having the same issue. You can try this workaround:

```javascript
"use strict";
const puppeteer = require("puppeteer");
const url = "https://pste.eu/p/awIC.html";

(async () => {
    const browser = await puppeteer.launch({
        args: [ "--no-sandbox", "--disable-gpu" ]
    });
    const page = await browser.newPage();
    await page.evaluate((url)=>{window.location = url}, url);
    await page.waitFor('body > iframe');
    console.log('working!');
    await browser.close();
})();
```

**Comment by distante** [comment]
> I'm having the same issue. You can try this workaround:
```
"use strict";
const puppeteer = require("puppeteer");
const url = "https://pste.eu/p/awIC.html";

(async () => {
    const browser = await puppeteer.launch({
        args: [ "--no-sandbox", "--disable-gpu" ]
    });
    const page = await browser.newPage();
    await page.evaluate((url)=>{window.location = url}, url);
    await page.waitFor('body > iframe');
    console.log('working!');
    await browser.close();
})();
```

This allow the page to load but there is no way to capture the error.

**Comment by panthony** [comment]
Same issue, tried `--allow-running-insecure-content` with no luck.

@GregRos Can you somewhat retrieve a response using this method? What was the status code, the HTTP headers, etc?

How do you navigate without goto? Do you use `evaluate(() => window.location = url)`?

**Edit:**

I tried something like this instead of using `goto`, does the work, probably not be bulletproof

```js
    return new Promise((resolve) => {
      let returnValue = null;

     page.on('response', (response) => {
        if (returnValue === null) {
          returnValue = response;
        }
      })

     page.on('domcontentloaded', () => {
        resolve(returnValue);
      })

      return page.evaluate((url) => window.location = url, url);
    });
```

**Comment by elainema** [comment]
> To be honest, I've found the promise returned by `goto` to be pretty unreliable in general. I've resorted to injecting some code that manually subscribes to events like `DOMContentLoaded` and `load`.

Could u pls share that ?
