### ISSUE TITLE
Downloading an Image

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#1937]
Hello there,

Is it possible to download an image ( not a screenshot, an actual image from a site ) and save it locally from puppeteer and how?
If not -> request feature ;)
thanks ?

**Comment by skyiea** [comment]
You can get image href and then simply GET it with `request` from Node.

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/299#issuecomment-328295644

**Comment by sonyarianto** [comment]
@Nicolas-vrcc how about this?
don't forget to require `fs`
```
var viewSource = await page.goto('http://bolawow.com/wp-content/uploads/2018/02/fcsm-bilbao-1.jpg');
fs.writeFile("./anu.jpg", await viewSource.buffer(), function(err) {
    if(err) {
        return console.log(err);
    }

    console.log("The file was saved!");
});
```

**Comment by zwhitchcox** [comment]
is there any way to do this download directly without navigating to a different page?

**Comment by tuananh** [comment]
@zwhitchcox new page , download then close?

Or using `request` like previous comment ?

**Comment by avrebarra** [comment]
I found [this link](https://intoli.com/blog/saving-images/) that probably would help. It makes use of the 'DevTools Protocol' available in puppeteer.

@Nicolas-vrcc

**Comment by zwhitchcox** [comment]
Thanks, @shrotavre, I didn't know about `element.screenshot`, and I was just screenshotting the image manually.

Unfortunately, security's really tight on this site (I'm not doing anything nefarious), so that's the only solution that works.

**Comment by pjanoh** [comment]
@sonyarianto , sometimes these images are webp/RIFF-images even if the url indicates '.jpg' and etc. But simple image conversion for the buffer can help:

```
const sharp = require('sharp');
...
let bufferJpg = sharp(await viewSource.buffer()).toFormat('jpg').toBuffer()
...
```

**Comment by d668** [comment]
doesn't work with bigger images though.
https://effigis.com/wp-content/uploads/2015/02/Airbus_Pleiades_50cm_8bit_RGB_Yogyakarta.jpg
`UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): Request content was evicted from inspector cache`

**Comment by d668** [comment]
and hangs on https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4

**Comment by EnixCoda** [comment]
> @Nicolas-vrcc how about this?
> don't forget to require `fs`
> 
> ```
> var viewSource = await page.goto('http://bolawow.com/wp-content/uploads/2018/02/fcsm-bilbao-1.jpg');
> fs.writeFile("./anu.jpg", await viewSource.buffer(), function(err) {
>     if(err) {
>         return console.log(err);
>     }
> 
>     console.log("The file was saved!");
> });
> ```

This is a good solution for most images! 👍

But when the response has the HTTP header `content-disposition`, Chrome would close the page before `response.buffer()` resolve and the file would not be emitted to file as expected.
