### ISSUE TITLE
How to control element in iframe in iframe and how to obtain full "iframe path" ?

### ISSUE THREAD

**Issue by jj999** [puppeteer/puppeteer#1940]
I'm having issues controling elements in nested iframes. Is there any documentation how to do it?

Also it would be good if full nested iframe "path" could be somehow copied from the inspect element - similarly as we have options for cURL or xPATH.

Thank you very much!

**Comment by yanivefraim** [comment]
@jj999 - not exactly the same but related to those:
https://github.com/GoogleChrome/puppeteer/issues/1413#issuecomment-361962809
 and https://github.com/GoogleChrome/puppeteer/issues/1361#issuecomment-343748051
