### ISSUE TITLE
type and focus: Dont seem to be working anymore

### ISSUE THREAD

**Issue by dmportella** [puppeteer/puppeteer#1943]
I had an puppeteer script that open a page and focus some input controls and typed some content into them. After upgrading puppeteer they all stopped working. I have used one fo the example below to demonstrate the problem.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Linux Ubuntu 17.10
* URLs (if applicable): 
* Node.js version: 8.4.9

**What steps will reproduce the problem?**

1. npm install puppeteer
2. create index.js file and place the contents of https://github.com/GoogleChrome/puppeteer/blob/master/examples/search.js into it.
3. change line `await page.goto('https://google.com', {waitUntil: 'networkidle`'}); to `await page.goto('https://google.com', {waitUntil: 'networkidle2'});` (examples need to be updated btw)
4. run example (node index.js)

**What is the expected result?**

Expected to print out all the h3 links on the console.

**What happens instead?**

Errors with `AssertionError [ERR_ASSERTION]: No node found for selector: puppeteer`

```console
(node:15036) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError [ERR_ASSERTION]: No node found for selector: puppeteer
(node:15036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Code run**

```js
'use strict';

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://google.com', {waitUntil: 'networkidle2'});
// Type our query into the search bar
await page.type('puppeteer');

await page.click('input[type="submit"]');

// Wait for the results to show up
await page.waitForSelector('h3 a');

// Extract the results from the page
const links = await page.evaluate(() => {
  const anchors = Array.from(document.querySelectorAll('h3 a'));
  return anchors.map(anchor => anchor.textContent);
});
console.log(links.join('\n'));
browser.close();

})();
```

**Comment by travch** [comment]
As indicated in the error message you see, `page.type('puppeteer')` is failing because it can't find a selector called `puppeteer`.

From the documentation: `page.type(selector, text[, options])`
page.type() is going to take 2 arguments, the first is a selector, the second is the text you want to type. The selector passed should be the selector you want to focus, in other words it is the selector for the element the text will be entered into.

Reference: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagetypeselector-text-options

**Comment by nammaianh** [comment]
@dmportella 

**It depends on the version of Puppeteer you are using.**

For v0.12.0 and later, `page.type()` has 3 parameter. The first param is the selector of the text field, the second is the content that you wanna type, the last is options. The first 2 params are required.

**Comment by JoelEinbinder** [comment]
Thanks nammaianh

**Comment by dmportella** [comment]
@travch thank I didnt realise the api changed. so regardless of focus now i have to select the element I want to type into not like it was on previous version?

**Comment by dmportella** [comment]
@JoelEinbinder The examples need to be updated to match the latest API version

**Comment by dmportella** [comment]
@JoelEinbinder which is has been ! cool I am glad
