### ISSUE TITLE
Console.log() from page.evaluate() not working

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#1944]
Hello,

I'm trying to console.log() in a page.evaluate() function and it's not working...
Any solutions ?

Thank you !

**Comment by Everettss** [comment]
It is working but it's not outputting to node environment console. Have a look at [`page.on('console', callback)`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-console). Here is an example from docs: 

```javascript
page.on('console', msg => {
  for (let i = 0; i < msg.args.length; ++i)
    console.log(`${i}: ${msg.args[i]}`);
});
page.evaluate(() => console.log('hello', 5, {foo: 'bar'}));
```

**Comment by yanivefraim** [comment]
Hi @Nicolas-vrcc,

Take a look here: https://github.com/GoogleChrome/puppeteer#debugging-tips

You can just:

```
page.on('console', msg => console.log('PAGE LOG:', msg.text()));
 
await page.evaluate(() => console.log(`url is ${location.href}`));
```

**Comment by c094728** [comment]
everything that is run inside the page.evaluate function is done in the context of the browser page.  The script is running in the browser not in node.js so if you log it will show in the browsers console which if you are running headless you will not see.  You also can't set a node breakpoint inside the function.

**Comment by ChristosChristofidis** [comment]
you can capture it with page.on('console' even in headless

**Comment by proton1k** [comment]
@Everettss  thanks for the example, but It does not seem to work with `evaluateHandle` though. And neither for `evaluate` method in my case. Could you please explain the current case how `page.on` carries `.log` call ? Or better to read the source code for `page.on` ?

**Comment by hungcao181** [comment]
Page.on('console', (msg) => {}) actually fired, but the example will not work because msg.args is undefined. Inside the callback, just console.log(msg) we will see what is inside.
Actually msg is of type ConsoleMessage, which provide 3 methods args(), text(), type()
We should call these 3 methods inside the callback instead of just access them as properties.
https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-class-consolemessage

**Comment by hungcao181** [comment]
Just one more thing, the page.on('console', callback) should be registered before any console.log statement can be called

**Comment by GuoZhaoHui628** [comment]
谢谢 @c094728  解答，如果还有问题，戳右边链接。[https://guozh.net/puppeteer-page-evaluate-consolelog-not-working/](https://guozh.net/puppeteer-page-evaluate-consolelog-not-working/)

**Comment by ghost** [comment]
For anyone looking at this issue now, in the latest version, you'll need to do this instead:

```
for (let i = 0; i < msg._args.length; ++i)
    console.log(`${i}: ${msg._args[i]}`);
```

**args** has been replaced with **_args**

**Comment by asamountain** [comment]
```
page.on('console', msg => {
for (let i = 0; i < msg._args.length; ++i)
    console.log(`${i}: ${msg._args[i]}`);
});
```

as referred,  @Ed-Ed @Everettss  above code does work! 
Thank you guys

**Comment by ezy** [comment]
For the full message logs this worked for me:

`page.on("console", msg => console.log("PAGE LOG:", msg));`

**Comment by iniatse** [comment]
this does not trigger for `console.log()` within the site which is loaded. It only triggers when using `page.evaluate()`

**Comment by nickofthyme** [comment]
Slight improvement to @ezy's solution. This will print the message type and the resolved message text from the console args.

```ts
page.on('console', (msg) => console[msg._type]('PAGE LOG:', msg._text));
```

**Comment by whoisjuan** [comment]
I don't know why this hasn't been mentioned here but simply setting `dumpio: true` when setting [puppeteer.launch](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions) options will pass up all the console logs inside all your `page.evaluate`.

**Comment by Hamisakim** [comment]
@whoisjuan Thanks!! 
 if anyone runs into this issue, this is the snippet needed 
```
  const browser = await puppeteer.launch({
    dumpio: true
  })
```

**Comment by uzair004** [comment]
Still can't see console.log in non-headless mode in nodejs console neither in browser console

**Comment by ManelGonzalez-ops** [comment]
This library's syntax is a fucking piece of crap. How retarded it is

**Comment by lgh06** [comment]
in 2023 Sep, I have to use   `page.on('console', (msg) => console[msg.type()]('PAGE LOG:', msg.text()));`

**Comment by cantonalex** [comment]
I'm also having this problem seems to have stopped working after `21.1.1`
