### ISSUE TITLE
Page Stats, Page.on('response'), response.buffer(), Memory and Garbage Collection

### ISSUE THREAD

**Issue by tomgallagher** [puppeteer/puppeteer#1949]
Puppeteer 1.0.0
Cloud9 Workspace
Node Version 7.10.1

I'm running two types of routine, one where I get the page html via `page.content()`, another where I'm collecting page stats via `Page.on('response'), response.buffer()`. When I run the second routine, I'm seeing much more memory usage than I would expect and I'm hoping that I'm doing something wrong.

Here's the code.

```
page.on('response', response => {
        
        const req = response.request();
        const responseType = req.resourceType();
        const headers = response.headers();
        const response_url = response.url();
        switch(responseType) {
             case "document":
                //here we check if there's a number to gather, if the number is greater than zero
                if (headers['content-length'] && Number(headers['content-length']) > 0) {
                    html_source_array.push(response_url);
                    html_load_array.push(Number(headers['content-length'] ) ); 
                } else {
                    //this is going to give us the unzipped size
                    response.buffer().then(buffer => {
                        html_source_array.push(response_url);
                        html_load_array.push(buffer.length);
                        bufferCalcCount ++;
                    });
                }
                break;
           case "stylesheet":
                //here we check if there's a number to gather, if the number is greater than zero
                if (headers['content-length'] && Number(headers['content-length']) > 0) { 
                    css_source_array.push(response_url);
                    css_load_array.push(Number(headers['content-length'] ) ); 
                } else {
                    //this is going to give us the unzipped size
                    response.buffer().then(buffer => {
                        css_source_array.push(response_url);
                        css_load_array.push(buffer.length);
                        bufferCalcCount ++;
                    });
                }
                break;
           default:
                //not much to do here
      }
    
});
```

Firstly, it would be a great enhancement if the response could somehow give the zipped size where the content length header was absent. For the time being I can work around that. It would also be useful to have a `response.resourceType()` method but again, it's workable as is.

However, more importantly, where there are a significant number of buffer operations required, the memory usage of Puppeteer balloons. I'm not sure why this would be. I would expect the buffer to be garbage collected after the event handling has finished but I'm guessing all the buffer objects are held in memory for as long as the page is open. Is that right? Would it be possible to add a `buffer.close() `method? Failing that, would setting the buffer to zero length at the end of each event handler achieve the same end?

**Comment by aslushnikov** [comment]
> Firstly, it would be a great enhancement if the response could somehow give the zipped size where the content length header was absent.

@tomgallagher  This sounds as #667.

>  It would also be useful to have a response.resourceType() method but again, it's workable as is.

Isn't it just `response.request().resourceType()`? 

> However, more importantly, where there are a significant number of buffer operations required, the memory usage of Puppeteer balloons. I'm not sure why this would be. I would expect the buffer to be garbage collected after the event handling has finished but I'm guessing all the buffer objects are held in memory for as long as the page is open. Is that right? Would it be possible to add a buffer.close()method? Failing that, would setting the buffer to zero length at the end of each event handler achieve the same end?

Looking at your code, I don't think you're doing anything wrong. I also just checked puppeteer - by the end of our extensive test suite, we don't have any Response objects in the heap, so there's nowhere we can retain the buffer.

I'd recommend running a heap shapshot on your code and checking the retaining chain for the buffers in question.
