### ISSUE TITLE
New page opens in a tiny div (?frame?) instead of full viewport.

### ISSUE THREAD

**Issue by qstyler** [puppeteer/puppeteer#1950]
### Steps to reproduce

* Puppeteer version: 1.0.0
* Platform / OS version: Mac OS Sierra 10.13.2 (17C205)
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

```
const  puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  page.goto('http://google.com');
})();
```

I expect the google page to be visible within a full viewframe, but instead it appears to be within a tiny... i don't know what. Because when I try to open devtoops everything goes back to normal.

I can't scroll the whole page, only when the mouse is within that frame.

![image](https://user-images.githubusercontent.com/5556580/35733102-4d922efc-081c-11e8-9402-39b55f087495.png)

**Comment by vsemozhetbyt** [comment]
[page.setViewport()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport) can help.

From [readme](https://github.com/GoogleChrome/puppeteer/blob/master/README.md#usage):

> Puppeteer sets an initial page size to 800px x 600px, which defines the screenshot size. The page size can be customized with Page.setViewport().
