### ISSUE TITLE
Headless - localStorage is empty on relaunch

### ISSUE THREAD

**Issue by fabianMendez** [puppeteer/puppeteer#1952]
Hey there I'm using puppeteer 1.0.0 on  windows 32bit with node v8.9.1

I'm testing a web application which save the authentication tokens in the local storage, when I was using the headfull version (for debugging...) everything was ok, but when I set the headless option to true, every time I re-launch the node application the localStorage is empty.

I tried removing the userDataDir but it didn't work

Any help is really appreciated, thanks

**Comment by ebidel** [comment]
I assume you're reusing a `userDataDir`? on subsequent runs?  Code would be helpful :)

Related: 
https://github.com/GoogleChrome/puppeteer/issues/1268
https://github.com/GoogleChrome/puppeteer/issues/921

**Comment by fabianMendez** [comment]
Well, #1268 is about reusing headfull userDataDir on headless and #921 is still open

I came up with a solution, if someone has the same problem:
```js
const { writeFileSync, readFileSync, existsSync, lstatSync } = require('fs');
const puppeteer = require('puppeteer');
// ...
class Server {
  // ...
  start = async () => {
    const localtStoragePath = './local_storage.json'

    // See https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions
    this.browser = await puppeteer.launch({headless: true, handleSIGINT: false})
    
    // Handle signint process signal to save localStorage
    process.once('SIGINT', async () => {
      let storage = await this._getStorage()
      writeFileSync(localtStoragePath, JSON.stringify(storage))
      
      await this.browser.close()
      process.exit()
    })

    this.page = (await this.browser.pages())[0] // use already open page
    await this.page.setUserAgent('Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36')
    await this.page.goto('...', {timeout: 0})

    // Restore storage from file (if valid)
    if (existsSync(localtStoragePath) && lstatSync(localtStoragePath).isFile()) {
      let storage = readFileSync(localtStoragePath, 'utf8')
      try {
        await this._setStorage(JSON.parse(storage))
        await this.page.reload()
      } catch (e) {
        console.error(`Error restoring localStorage: ${e.message}`)
      }
    }
  }
  // ...
  _setStorage = async (storage) => {
    await this.page.evaluate((storage) => {
      for (let key in storage) {
        localStorage.setItem(key, storage[key])
      }
    }, storage)
  }

   _getStorage = async () =>
    await this.page.evaluate(() => {
      let value, storage = {}
      for (let key in localStorage) {
        if (value = localStorage.getItem(key))
          storage[key] = value
      }

      return storage
    })
}
```

**Comment by ebidel** [comment]
> Well, #1268 is about reusing headfull userDataDir 

You mentioned testing in headful first. So I was assuming you tested storing in localStorage in headful, and it wasn't accessible when switching over to headless.

Have you tried reusing the user data dir? Restoring via a file is an option, but you shouldn't have to do that :)

**Comment by gzlock** [comment]
localStorage data has domain namespace.
Is possible to set up the localStorage data before open the url page?

**Comment by fabianMendez** [comment]
> Have you tried reusing the user data dir?

Actually this is what I did:
- Use puppeteer in headfull mode (for debugging) with a user data dir, everything works just fine when I restart the application
- I switched to headless mode, with the same user data dir used on headfull mode, it didn't work :(
- I readed in #1268 that the user data dir from headfull can't be used on headless, so I deleted that dir and started again the application but it didn't work either

I'm fine with restoring from file but it would be nicer to not have to do so

**Comment by ebidel** [comment]
This works for me. Run this a couple of times:

```js
const browser = await puppeteer.launch({
  userDataDir: './user-data-dir'
});

const page = await browser.newPage();
await page.goto('https://en.wikipedia.org/wiki/Main_Page');

// Uncomment and run script again if you want to start over.
// await page.evaluate(() => {
//   localStorage.clear();
//   console.log(JSON.stringify(Object.keys(localStorage)));
// });

const pptrVal = await page.evaluate(version => localStorage.getItem('pptrVal'));
console.log('reused val:', pptrVal);

if (!pptrVal) {
  const val = await page.evaluate(version => {
    localStorage.setItem('pptrVal', version);
    return version;
  }, await browser.version());
  console.log('new val set:', val);
}

await browser.close();
```

**Comment by fabianMendez** [comment]
The above example works fine as is, but if I comment the line `await browser.close();` and use ctrl-c to quit the program, it doesn't work

So the problem is on non-clean shutdowns

**Comment by aslushnikov** [comment]
> So the problem is on non-clean shutdowns

Looks like it's not a big deal. I wouldn't expect much of chromium when it's been force-terminated.
