### ISSUE TITLE
Is it possible to login in google chrome account?

### ISSUE THREAD

**Issue by rustemkzk** [puppeteer/puppeteer#1953]
Hello.

I need to login in google chrome account like in a headful chrome. It is helpful to bypass captcha just in one click.

**Comment by ebidel** [comment]
You can perform the form submission, but evading captchas is the challenging bit. If it were easy to programmatically solve a captcha, they wouldn't work very well as a security feature :)

See:
https://github.com/GoogleChrome/puppeteer/issues/473
https://github.com/GoogleChrome/puppeteer/issues/1935
