### ISSUE TITLE
uploading a file not working

### ISSUE THREAD

**Issue by stickyman2** [puppeteer/puppeteer#1957]
I need help with uploading a .mp3 file with puppeteer to this website: https://speech-to-text-demo.ng.bluemix.net/  but i dont get the text from the website back with the following code  Only if i upload the mp3 file manually i get a text back... 

const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
    headless: false,
});

    const page = await browser.newPage();
	    await page.setViewport({ width: 1920, height: 1080 });

	
                await page.goto('https://speech-to-text-demo.ng.bluemix.net/');
                await page.waitForSelector('div.tab-panels', { timeout: 4000 });
                await page.waitForSelector('#root > div > div.flex.setup', { timeout: 4000 });
                await page.waitForSelector('input[type="file"]', { timeout: 4000 });
                const fileEle = await page.$('input[type="file"]');
                await fileEle.uploadFile(__dirname+'C:\Users\Computer\Desktop\3audio.mp3');
                await page.waitFor(20000);
				
				await browser.close();

})();

**Comment by wurde** [comment]
This looks like a file path problem. What does __dirname+'C:\Users\Computer\Desktop\3audio.mp3' resolve to? Isn't C:\ the root directory, so what does prepending __dirname come out to?

I've been able to get uploadFile to work when uploading a single file.

**Comment by stickyman2** [comment]
the file path is ok because if i change the "3audio.mp3" to "3audio.txt" then i get a warning from the website "Sorry, that file does not appear to be compatible."

so can you give me a example how you get it to work pls?

**Comment by wurde** [comment]
I was able to get the method to work by applying the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) `...` to the files input argument. If you look at the source code for the `uploadFile` method (hint: you should always do this) you'll see why this works.

    let files = fs.readdirSync(path.join(dcim_path, photo_dir[i]))

    for (let j=0; j < files.length; j++) {
      files[j] = path.join(dcim_path, photo_dir[i], files[j])
    }

    await input.uploadFile(...files)

**Comment by narra-dev** [comment]
> I was able to get the method to work by applying the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) `...` to the files input argument. If you look at the source code for the `uploadFile` method (hint: you should always do this) you'll see why this works.
> 
> ```
> let files = fs.readdirSync(path.join(dcim_path, photo_dir[i]))
> 
> for (let j=0; j < files.length; j++) {
>   files[j] = path.join(dcim_path, photo_dir[i], files[j])
> }
> 
> await input.uploadFile(...files)
> ```
```
UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/Users/apple/Desktop/kwork/baza5000/telegram/app/image.jpg'
    at Object.fs.readdirSync (fs.js:904:18)
```

Error seems legit, .../image.jpg is actually a file, not a directory. How do I make it work?
