### ISSUE TITLE
how I can do screenshot in multiprocess?

### ISSUE THREAD

**Issue by harkue** [puppeteer/puppeteer#1959]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0 / 1.0.0
* Platform / OS version: CentOS 7.2
* URLs (if applicable):
* Node.js version: 8.9.4

script [screenshot.js]：
[code]
'use strict';

const puppeteer = require('puppeteer');

(async() => {
try{
	const browser = await puppeteer.launch({
			args:['--no-sandbox', '--disable-setuid-sandbox']
	}
	);
	const page = await browser.newPage();
	await page.goto('http://www.example.com');
	await page.screenshot({path: 'example.png'});
	await page.close();
	await browser.close();
}catch(err){
        console.log(err);
}
})();

[/code]

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. exec command 25times :

node screenshot.js &
node screenshot.js &
node screenshot.js &
node screenshot.js &
node screenshot.js &
node screenshot.js &
node screenshot.js &
node screenshot.js &
... (more)

2. error msg 

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
...  

3.   press enter key
[21]   Done                    node screenshot.js
[22]   Exit 1                  node screenshot.js
[23]   Exit 1                  node screenshot.js
[24]   Exit 1                  node screenshot.js
[25]-  Exit 1                  node screenshot.js

**What is the expected result?**
all screenshot success

**What happens instead?**
some process failed

how I can do screenshot in multiprocess?

**Comment by joelgriffith** [comment]
The way your script is setup you’re effectively starting Chrome 25 times (one for each invocation). My suspicion is that your machine can’t handle the load and later `launch` calls fail. Could be wrong though!

You could do two things:

1. Try and reuse the `browser` object and create a new page for each screenshot. This would be slightly more performance than launching 25 instances of Chrome.

2. The other option, if you need separate Chrome instances, is to use a library like queue and limit the amount of concurrent connections that can happen at one time. This process is a bit more involved, but may be required if your use case requires isolated instances of Chrome.

Given that I’d try #1 myself and see if that alleviates your issue.

**Comment by harkue** [comment]
@joelgriffith Thanks, joelgriffith.  You provided a good idea.  

I am wondering to use create a node http server using a global browser instance. This server receives a request to do screenshot in a new tab of the global browser instance. 

I am afraid whether it will trigger this error again when page is closing.


Error: read ECONNRESET
at _errnoException (util.js:1022:11)
at TCP.onread (net.js:615:25)

This error is triggered by a closed client connection. 
But I don't know what will cause this error~~~

**Comment by ebidel** [comment]
Questions like this do better on SO or the Slack channel. Let's move over there for discussion. Yea?
