### ISSUE TITLE
waitForSelector should accept 0 for timeout option

### ISSUE THREAD

**Issue by alixaxel** [puppeteer/puppeteer#1960]
Currently the `waitForSelector` is evaluating `timeout` like this: https://github.com/GoogleChrome/puppeteer/blob/189deb84c0ecf43f405961814aad840c1107ee85/lib/FrameManager.js#L640

For me, this is obscure behavior. I ran into the case where I had already waited for other preconditions that ensure the DOM is in the right state and I need to check if _either one of **two** possible elements_ exist on the page, immediately. It's a fair assumption that `timeout = 0` would mean immediately, but because of the fallback, it ends up spending 30 seconds looking for an element that is not there and won't be there.

**Comment by boogerlad** [comment]
Why don't you just use .$ or .$$ and check for null or [], respectively?

**Comment by alixaxel** [comment]
@boogerlad I didn't get you.

**Comment by ambalica** [comment]
I am still getting timeout errors while running a similar code. 

`try {
    await page.goto(inputURL);
    await page.waitFor(".websiteRanks-item.js-globalRank", {timeout : 0});`

I try updating the timeout values, same error. Is there anything I am doing wrong?

**Comment by aslushnikov** [comment]
@ambalica you're probably getting timeout from the initial `page.goto`. You should add timeout there as well.
