### ISSUE TITLE
Missing options preferCSSPageSize and ignoreInvalidPageRanges in Page.pdf()

### ISSUE THREAD

**Issue by N-X-N** [puppeteer/puppeteer#1963]
Chrome's DevTools version 1.3 (targets Chrome 64) accepts these options for [Page.printToPDF](https://chromedevtools.github.io/devtools-protocol/1-3/Page#method-printToPDF) :
- ignoreInvalidPageRanges
- preferCSSPageSize

I found no corresponding options in Page.pdf().

**Comment by CaelanStewart** [comment]
Are there any plans to add this option to Puppeteer?

I'm not familiar with Puppeteer's internals, but could this option be of help to [this issue](https://github.com/GoogleChrome/puppeteer/issues/2278)?
