### ISSUE TITLE
Can't resolve 'readline'

### ISSUE THREAD

**Issue by yasa83-jsm** [puppeteer/puppeteer#1965]
Hi,
I added the module as,

yarn add puppeteer

I am trying for a simple example to load google page with the code below.

const puppeteer = require('puppeteer');
const handleClick = () => {
    (async () => {
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      await page.goto('https://www.google.com');
      await page.screenshot({path: 'example.png'});
      console.log( page.content());
     
      await browser.close();
    })();
}

When I run the server. I am get the following error,

yarn start (react-scripts start)

Failed to compile.

./node_modules/puppeteer/lib/Launcher.js
Module not found: Can't resolve 'readline' in 'C:\Projects\xxxxxxx\node_modules\puppeteer\lib'

How do I fix this?

**Comment by ebidel** [comment]
Try updating your version of node. readline is a node core lib that's been around for a while.

**Comment by Djuki** [comment]
@ebidel I am using `create-react-app` and I added package `puppeteer` but I have the same error when  import puppeteer

`import puppeteer from 'puppeteer';`

```
./node_modules/puppeteer/lib/Launcher.js
Module not found: Can't resolve 'readline' in '/home/vagrant/code/xxx/node_modules/puppeteer/lib'
```

node version: v9.10.1
npm version: 5.8.0
yarn version: 1.3.2

**Comment by monkey1990** [comment]
I have the same problem.
./node_modules/puppeteer/lib/Launcher.js
Module not found: Can't resolve 'readline' in 'D:\WorkProject\XXXX\master\portal\node_modules\puppeteer\lib'

my node version:  v7.3.0
npm : v3.10.10

I can find the definition of readline in D:\WorkProject\XXXX\master\portal\node_modules\@types\node\index.d.ts
`declare module "readline" {
    import * as events from "events";
    import * as stream from "stream";

    export interface Key {
        sequence?: string;
        name?: string;
        ctrl?: boolean;
        meta?: boolean;
        shift?: boolean;
    }

    export interface ReadLine extends events.EventEmitter {`

**Comment by jorgemmsilva** [comment]
this fixed it for me:
`yarn add readline`

**Comment by Desintegrator** [comment]
same problem in my `create-react-app` guys. Any ideas how to fix it?

**Comment by DavidKozdra** [comment]
Was this ever fixed?

**Comment by jacty** [comment]
Try to check if readline exists in your node:
![image](https://user-images.githubusercontent.com/4190959/120939442-b26e1c00-c74a-11eb-82bb-43b62a1f22da.png)

**Comment by Yokool** [comment]
You can try running `npm install readline` inside your project folder. Worked for me.
[Source](https://stackoverflow.com/questions/56558127/module-not-found-cant-resolve-readline)

**Comment by simeon9696** [comment]
@Yokool installing or install ?

**Comment by Yokool** [comment]
My bad, `install`

**Comment by NamCao2610** [comment]
Why can't use puppeteer in create-react-app??
