### ISSUE TITLE
Scrape faster large amount of content with Puppeteer

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#1966]
Hello,

I'd like to know how to scrape data faster, I run a similar code in an async function and use a for loop to go through an array of over 10000 links with similar content to scrape but it takes ages even if I've disabled css, font and images load ... Is there a way to run multiple pages at once and if so can I get a snippet.

```
const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setRequestInterception(true)
    await page.goto('https://mypage.com')
    await page.evaluate(() =>{
...
})
```
Thanks a lot !

**Comment by ntzm** [comment]
You can open multiple pages per browser, and you can disable JavaScript! That might make it faster for you

**Comment by Nicolas-vrcc** [comment]
@ntzm Thanks ! Is there a way to loop through all the existing pages and divide the links to visit between them ?

**Comment by ebidel** [comment]
Questions like this are more appropriate on SO or the Slack channel.

**Comment by ralyodio** [comment]
I'm wondering the same time. I want to hit maybe 5 pages simultaneously.

**Comment by ralyodio** [comment]
```
const pMap = require('p-map');

async function getParallelAnalysis(sites) {
    return pMap(sites, getAnalysis, {concurrency: 5});
}

```

I still have problems in headless mode where it doesn't finish. Basically the process just hangs. If I turn off headless mode it works fine, just slower.
