### ISSUE TITLE
Re-using page requires page.goto('about:blank') ?

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1969]
I'm experimenting with re-using pages in a pool, rather than opening and closing each time.  I'm not yet convinced there will be a saving by using a pool, or whether I shouldn't bother... and just open/close as required.

Anyway, I'm finding that if I've used a page, i.e. done `page.goto(...)` and `page.screenshot(...)`, then before I call `goto()` on the page again (with a different URL) I need to first do `page.goto('about:blank')`.

Is this actually necessary, or is there a better way?

**Comment by ebidel** [comment]
Why are you finding that's necessary? Code snippet?

**Comment by drmrbrewer** [comment]
@ebidel I tried to make a repro for this but rather than reproduce this issue I managed to run into another one.  See [here](https://github.com/GoogleChrome/puppeteer/issues/1325#issuecomment-363473378)!  I'll carry on trying to reproduce the problem originally reported on this issue.

**Comment by drmrbrewer** [comment]
@ebidel on further reflection I think it might have been caused by `await`ing a `page.goto()` call and then awaiting a `page.waitForFunction()`.  After changing things to not await the `goto` and only the `waitForFunction`, it seems to be behaving better.

**Comment by drmrbrewer** [comment]
@ebidel I finally worked out what is causing this problem (it's not what I said above), though I have not yet worked out how to solve the problem (without the `about:blank` workaround).

Here is a repro script:

    const loadPage = function (i, page, url) {
        return new Promise(async (resolve, reject) => {
            page.on('pageerror', errorstring => {
                reject(new Error(errorstring));
            });
            page.on('error', error => {
                reject(new Error(error));
            });
            try {
                console.log('loading url', url);
                await page.setViewport({ width: 400, height: 200 });
                // await page.goto('about:blank');
                await page.evaluate(() => {
                    // reset watchdog flag before loading url
                    delete window.allDoneNow;
                });
                const watchDog = page.waitForFunction('window.allDoneNow == true', { polling: 250, timeout: 5000 });
                const ignoreThisPromiseAndAwaitWatchdogInstead = page.goto(url);
                await watchDog;
                await page.screenshot({ path: 'screenshot_' + i + '.png' });
                resolve();
            } catch (error) {
                reject(new Error(error));
            }
        });
    };
    (async () => {
        var browser, page;
        try {
            const baseUrl = 'https://cloud3squared.com/files/example.html';
            const max = 3;
            browser = await puppeteer.launch();
            page = await browser.newPage();
            for (var i = 0; i < max; i++) {
                await loadPage(i, page, baseUrl + '#stuff/after/the/hash/' + i);
            }
            res.sendStatus(200);
        } catch (error) {
            console.log('error:', error);
            res.sendStatus(500);
        } finally {
            await page.close();
            await browser.close();
        }
    })();

And here is the content of `example.html`:

    <html>
    
    <head>
        <title>
            A Very Basic HTML Document
        </title>
        <script type="text/javascript">
            document.addEventListener('DOMContentLoaded', function(event) {
                delete window.allDoneNow;
                setTimeout(function() {
                    document.getElementById("my_text").innerHTML = "Great!  You waited for the best bit!";
                    window.allDoneNow = true;
                }, 2500);
            });
        </script>
    </head>
    
    <body>
        <div id="my_text">This is boring... wait for the good bit!</div>
    </body>
    
    </html>

In the puppeteer script, with the `await page.goto('about:blank')` commented out, I get a *caught* `timeout 5000ms exceeded` error (corresponding to the `timeout` I set in the script) and an *uncaught* `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded`.  If I uncomment `await page.goto('about:blank')`, it all works fine.

First question is: how do I actually catch and handle the 30s timeout rejection?

I know *why* the timeouts happen now, and why the workaround to load a blank page works... it relates to the fact that the only part of the URL that changes each time is what comes *after* the `#`.  You can see this in Chrome desktop... if you load a URL ending in e.g. `example.html#abc` and then go into the address bar and change it to `example.html#xyz` and hit Enter, nothing happens... the page doesn't even *try* to reload.  But when you open a new tab, or load `about:blank` in the same tab, and enter a new URL with new `#` content, the reload happens.

And in the above context, if the page isn't actually loading anything with `page.goto()` (because only the hash content changed) then the watchdog flag is never going to be set, so it will be waiting forever (or until it times out).

Is there any way to force a fresh load with `page.goto()`... or is the `about:blank` workaround as good as it's going to get?

I guess a related "best practice" question is whether there's a better way to pass information into a web page... I am using `window.location.hash` in my html script to read in the information from the hash content... and it is *only* that content that changes with each new load.  Is there a better way to pass info to a page?

**Comment by ebidel** [comment]
Ah, this looks like a dupe of https://github.com/GoogleChrome/puppeteer/issues/257. Please reopen if you think otherwise.

Your `page.goto('about:blank')` workaround is seems fine to me. If you want, you could also set a very small timeout, catch the rejection and move on:

```js
await page.goto(url);
try {
  // Can use timeout: 0 when github.com/GoogleChrome/puppeteer/pull/1964 makes next release.
  await page.goto(`${url}#xyz`, {timeout: 1});
} catch (err) { /* noop */}

// use page.waitForSelector (or other) to make sure the new view is loaded.
```

**Comment by drmrbrewer** [comment]
@ebidel thanks.  Can I just clarify a couple of things with your alternative workaround...

What is the purpose of the `page.goto` with small timeout?  The problem seems to be to be in the following sequence:

    await page.goto(`${url}#abc`) // loads OK
    await page.goto(`${url}#xyz`)  // doesn't load (differs only in hash content)

My workaround is:

    await page.goto(`${url}#abc`) // loads OK
    await page.goto('about:blank') // load different location without cost (hopefully)
    await page.goto(`${url}#xyz`)  // loads OK

Where would your `page.goto` go in the above sequence, and what url would be used?  Do you think it would be more or less expensive than browsing to `about:blank`?

Also, you comment that:

> Can use timeout: 0 when github.com/GoogleChrome/puppeteer/pull/1964 makes next release

Wouldn't using a timeout of 0 result in *no timeout* (would wait forever) rather than an actual timeout of zero (would not wait at all before throwing)?

**Comment by ebidel** [comment]
> Wouldn't using a timeout of 0 result in no timeout (would wait forever) rather than an actual timeout of zero (would not wait at all before throwing)?

Yes. That's the point :) Due to the [bug I mentioned](https://github.com/GoogleChrome/puppeteer/issues/257#issue-250221390), puppeteer won't move on from the the second `page.goto()` because adding a `#` to the URL is not considered a page navigation. This needs to be fixed in the DT protocol.

In your example, You navigate away from the page before hitting the 2nd hash, so it's considered a navigation.

```js
await page.goto(`${url}#abc`) // loads OK
await page.goto('about:blank') // load different location without cost (hopefully)
await page.goto(`${url}#xyz`)  // loads OK
```

**Comment by drmrbrewer** [comment]
Sure, but I thought that your suggestion to "set a very small timeout, catch the rejection and move on" will somehow ensure that the page `${url}#xyz` is properly captured... but surely it will still result in no navigation occurring... it simply causes a timeout after 1ms, which is caught, but the page is still not being navigated to, and therefore will never load?

**Comment by ebidel** [comment]
You're correct that it's faking the navigation.  I'm assuming the page is SPA that handles `hashchange` events and updates its view accordingly. So in effect, you "navigate" to the new "page". 

Sorry if that was unclear.

```js

  const page = await browser.newPage();

  // Catch + "forward" hashchange events from page to pptr code.
  await page.exposeFunction('onHashChange', url => page.emit('hashchange', url));
  await page.evaluateOnNewDocument(() => {
    addEventListener('hashchange', e => onHashChange(location.href));
  });

  // Listen for hashchange events in pptr code.
  page.on('hashchange', async url => {
    console.log('hashchange:', (new URL(url)).hash);
  });

  await page.goto(url);
  try {
    // TODO: can use timeout: 0 when https://github.com/GoogleChrome/puppeteer/pull/1964 lands in release.
    await page.goto(`${url}#page2`, {timeout: 1}); // "Navigate" to SPA view 2.
  } catch (err) {}

  await page.waitForSelector('[data-page="#page2"]'); // wait for view to be "loaded".
```

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A Very Basic SPA</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * {
      box-sizing: border-box;
    }
    html, body {
      margin: 0;
      height: 100vh;
    }
    body {
      font-family: sans-serif;
      display: flex;
      flex-direction: column;
    }
    nav {
      height: 56px;
      padding: 16px;
    }
    main {
      position: relative;
      display: flex;
      justify-content: center;
      align-items: center;
      flex: 1;
    }
    .page {
      height: 500px;
      width: 500px;
      padding: 16px;
      background: #eee;
      border-radius: 5px;
      top: 0;
      left: 0;
      display: none;
    }
    :target {
      display: block;
    }
  </style>
</head>
<body>

<nav>
  <a href="#page1">Page 1</a>
  <a href="#page2">Page 2</a>
  <a href="#page3">Page 3</a>
</nav>

<main>
  <section id="page1" class="page">Page 1</section>
  <section id="page2" class="page">Page 2</section>
  <section id="page3" class="page">Page 3</section>
</main>

<script>
if (!location.hash) {
  location.hash = 'page1';
}

function updatePage() {
  document.querySelector('main').dataset.page = location.hash;
}

window.addEventListener('hashchange', updatePage);
updatePage(); // update on page load
</script>
</body>
</html>
```

**Comment by drmrbrewer** [comment]
Ah, OK gotcha.  Thanks.
