### ISSUE TITLE
integrate puppeteer in gitlab with gitlab-ci.yml

### ISSUE THREAD

**Issue by lenie56** [puppeteer/puppeteer#1974]
Im currently working on e2e test in Chrome Puppeteer. I am at the stage where it would be ideal to integrate my tests in the development process.

What I want to accomplish is the following: my tests run automated before every deploy to production. If they succeed deployment goes through, if they fail deployment is canceled.

I use a pipeline on gitlab to automate my deployment process. So my main question is how can I integrate my puppeteer tests into the gitlab-ci.yml file?

**Comment by ebidel** [comment]
SO is best for questions like this:

https://stackoverflow.com/questions/48638875/integrate-puppeteer-in-gitlab-with-gitlab-ci-yml

**Comment by lenie56** [comment]
The link you send me Is my question...
It just seems like im the first person ever who tries to implement
puppeteer tests in a development process.

**Comment by ThePeach** [comment]
@ebidel honest question: do you want a separate issue to add some documentation on [this page](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) regarding how to get it working on gitlab?

**Comment by aslushnikov** [comment]
@ThePeach feel free to send a PR
