### ISSUE TITLE
CentOS 6.9 is not supported?

### ISSUE THREAD

**Issue by rodickmini** [puppeteer/puppeteer#1975]
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.9 (Final)
Release:	6.9
Codename:	Final

I've got the following error:

```
node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: 
error while loading shared libraries: libatk-bridge-2.0.so.0: 
cannot open shared object file: No such file or directory
```

Any help? Am I have to upgrade to CentOS 7 ?

**Comment by DavidFricker** [comment]
Make sure you install all the depencies for Chrome. Here is a list I use on Ubuntu 
https://gist.github.com/DavidFricker/67319b82b822246f0a1f2c2e60b17b05

From the looks of it you're missing `libatk1.0-0`

**Comment by rodickmini** [comment]
@DavidFricker THX for replying，at last I upgraded to CentOS 7, installed the dependencies, and now it's running good.

**Comment by agamemnus** [comment]
Does anyone know the answer ... upgrading to centOS 7 may not be a choice.
