### ISSUE TITLE
ElementHost.click() options to allow x/y offsets from element center

### ISSUE THREAD

**Issue by mihailik** [puppeteer/puppeteer#1977]
Feature request: <a href="https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleclickoptions">ElementHandle.click()</a> to accept coordinates relative to the element's center.
Same should apply to <a href="https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageclickselector-options">page.click(selector)</a>

```javascript
await myCanvas.click({x: 80, y: -5}); // click 80 pixels to right, 5 pixels higher than element center
center
```

```javascript
await page.click('#myCanvas', {x: 243, y: 16}); // click 243 pixels to right, 16 pixels lower than element 
```

Compare to how you'd do it today:

```javascript
var myCanvas = await page.$("#myCanvas");
var myCanvas_box = await myCanvas.boundingBox();
await page.mouse.click(
  myCanvas_box .x + myCanvas_box .width/2 + 243,
  myCanvas_box .y + myCanvas_box .height/2 - 16);
```

Much more verbose! And for real tests involved complex UI test that quickly becomes a mess.

**Comment by aslushnikov** [comment]
@mihailik we didn't see much interest in the feature on the bugtracker. I'd recommend creating your own helper function for this.
