### ISSUE TITLE
Setting up on Ubuntu 16 LTS

### ISSUE THREAD

**Issue by DavidFricker** [puppeteer/puppeteer#1979]
Every time I set up puppeteer on a on new server with a fresh Ubuntu 16 install I have to install a few dependencies before Chrome will start, which I have listed in the following gist. Maybe these could be put in the trouble shooting or set-up instructions so others do not need to seek out the dependencies?

https://gist.github.com/DavidFricker/67319b82b822246f0a1f2c2e60b17b05

**Comment by ebidel** [comment]
I believe this are documented in https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
