### ISSUE TITLE
Proposal: rename `page.evaluate` into `page.eval`

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#198]
Justification:
- `page.evaluate` is actually doing `eval` in a page
- `page.evaluate` is probably *the* most used method, it's tiring to type the whole word every time

@paulirish @ebidel wdyt?

**Comment by paulirish** [comment]
sure, wfm.

**Comment by Garbee** [comment]
SGTM. Developers are already used to `eval` for JS. Let's keep consistent.

**Comment by ebidel** [comment]
Ship it!

**Comment by Garbee** [comment]
I'm disappointed in you @ebidel. :shipit: exists.

**Comment by aslushnikov** [comment]
On the 'cons' side:
- every other library has `evaluate`: [nighmare.js](https://github.com/segmentio/nightmare#evaluatefn-arg1-arg2), [phantom.js](http://phantomjs.org/api/webpage/method/evaluate.html),  [chromeless](https://github.com/graphcool/chromeless/blob/master/docs/api.md#api-evaluate), [chrominator](https://github.com/jesg/chrominator#evaluate), [chromy](https://github.com/OnetapInc/chromy#evaluatefuncsource),...
- it's easy to have a shortcut if needed:
```js
let page = await browser.newPage();
page.eval = page.evaluate;
```

I'm not convinced we need it, I'd rather not make it to minimize entropy.

**Comment by paulirish** [comment]
"evaluate" in long form then!  

"eval is evil" anyway, so it does feel a bit weird to make the evil name be our star of the show.

**Comment by JoelEinbinder** [comment]
We should add `page.evil` as a shortcut.
