### ISSUE TITLE
Chromium still open after unhandledRejection

### ISSUE THREAD

**Issue by floflock** [puppeteer/puppeteer#1980]
I have seen https://github.com/GoogleChrome/puppeteer/issues/1390#issuecomment-344506047.
@aslushnikov for me, it also looks like a bug. Not for the navigation timeout, but for some other cases. 😦

If i try to fetch an invalid url like `http://www.abc`, the unhandledRejection would be fetched and the code snippet below will be executed, but browser process is not closed correctly, it is still open and run up to 100% CPU...

What can I do? 🤔

```
/**
 * Handle strange promise failure, looks like a bug
 */
process.on("unhandledRejection", async (reason, p) => {
    res.json({
        success: false,
        message: reason.toString()
    });
    await page.close();
    await browser.close();
});
```

**Comment by aslushnikov** [comment]
@florianflock the following snippet exits just fine for me on v1.1.1:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  process.on("unhandledRejection", async () => {
    await page.close();
    await browser.close();
    console.log('All closed!');
  });
  await page.goto('https://www.abc');
})();
```
