### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1981]
I'm re-using a `page` to open multiple `urls` with the following function:

    const loadPage = function (i, page, url) {
        return new Promise(async (resolve, reject) => {
            page.on('pageerror', errorstring => {
                reject(new Error(errorstring));
            });
            page.on('error', error => {
                reject(new Error(error));
            });
            try {
                await page.setViewport({ width: 400, height: 200 });
                const watchDog = page.waitForFunction('window.allDoneNow == true', { polling: 250, timeout: 5000 });
                const ignoreThisPromiseAndAwaitWatchdogInstead = page.goto(url);
                await watchDog;
                await page.screenshot({ path: 'screenshot_' + i + '.png' });
                resolve();
            } catch (error) {
                reject(new Error(error));
            }
        });
    };

After a while of re-using the page, I get the following warnings:

    (node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pageerror listeners added. Use emitter.setMaxListeners() to increase limit
    (node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

I know that I'm adding listeners to the same page with every call, but this is necessary in order to be able to reject a call if there is an error on that particular page load... hence a bespoke handler is required for each call (unless I've misunderstood something).  I thought that setting a page listener for an event would simply overwrite any existing listener for the same event, rather than just creating duplicate listeners... but maybe that is not correct?

How do I avoid the `MaxListenersExceededWarning` messages?  Another observation is that these messages aren't generated for each and every call, by any means... i.e. it's not as if a listener limit is reached and then the warning generated for every subsequent `page.on(...)`.

**Comment by drmrbrewer** [comment]
OK so adding [`page.removeAllListeners()`](https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname) seems to have stopped the warnings:

            page.removeAllListeners('pageerror');
            page.on('pageerror', errorstring => {
                reject(new Error(errorstring));
            });
            page.removeAllListeners('error');
            page.on('error', error => {
                reject(new Error(error));
            });

The docs (linked above) state that "it is bad practice to remove listeners added elsewhere in the code"... maybe this doesn't apply here because I'm removing listeners added in the *same* part of the code (at an earlier time)?

Maybe there is a better solution?

**Comment by Edison-Hsu** [comment]
why you not use `page.close()`:
```
page.goto(url)
....
page.close()
```

I'm not sure this will fix you issue, but I think you can try it

**Comment by aslushnikov** [comment]
@drmrbrewer you keep adding listeners to the page without removing them:
```js
const loadPage = function (i, page, url) {
    return new Promise(async (resolve, reject) => {
        page.on('pageerror', errorstring => {
            reject(new Error(errorstring));
        });
       // .....
```

 If you re-use the page instance, you should remove the listeners if you've added them.

**Comment by drmrbrewer** [comment]
> you should remove the listeners if you've added them

@aslushnikov as per my comment just above?  Is `page.removeAllListeners('pageerror')` the correct way to do it?

**Comment by aslushnikov** [comment]
> @aslushnikov as per my comment just above? Is page.removeAllListeners('pageerror') the correct way to do it?

That's one way, yes. A cleaner way would be to use `page.removeListener` to remove only the listeners that this method install.

```js
page.on('pageerror', errorListener);
// ...
page.removeListener('pageerror', errorListener);
```

This has nothing to do with puppeteer per se, though – page is a regular node.js [event emitter](https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener).

**Comment by nissejokke** [comment]
This solved it for me.
```
page._networkManager.setMaxListeners(100);
page._frameManager.setMaxListeners(100);
```
page.setMaxListeners() should be provided which sets these internally.

**Comment by aslushnikov** [comment]
> page._networkManager.setMaxListeners(100);
> page._frameManager.setMaxListeners(100);

@nissejokke unless you add listeners manually to networkManager or frameManager, these should not be needed ever. What's your usecase?

**Comment by nissejokke** [comment]
I have a number of pages open and reusing them in kinda the sammer manner as described by the initiator of this issue but you are correct, I had a bug which caused a page to execute goto() multiple times when it was'nt finished.
