### ISSUE TITLE
setExtraHTTPHeaders caps and order

### ISSUE THREAD

**Issue by sradu** [puppeteer/puppeteer#1984]
At the moment setExtraHTTPHeaders doesn't obey caps and, as mentioned in the docs, doesn't provide the ability to set an order.

This means adding the Accept-Language header, which is missing between headless & non-headless, is impossible right now.

Are there any plans on improving this?

headless: false
````
GET / HTTP/1.1
Host: a-host
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
````

headless: true
````
GET / HTTP/1.1
Host: a-host
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
````

setExtraHTTPHeaders
````
GET / HTTP/1.1
Host: a-host
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
accept-language: en-US,en;q=0.9
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
````

Thank you.

**Comment by sradu** [comment]
--lang fixes the Accept-Language header. Unsure if I should keep the issue open since it relates to header caps/order.

**Comment by aslushnikov** [comment]
> This means adding the Accept-Language header, which is missing between headless & non-headless, is impossible right now.

@sradu Why so? The `setExtraHTTPHeaders` adds the header. The case is not important for HTTP headers.

**Comment by sradu** [comment]
@aslushnikov The large CDN providers accept or reject browsers based on the order and caps of headers. That's the first layer, though there are others.

It's hard to be whitelisted, and the only way they consider it secure enough is based on a custom order + an extra id header.

**Comment by aslushnikov** [comment]
> The large CDN providers accept or reject browsers based on the order and caps of headers. That's the first layer, though there are others.

@sradu fascinating, thanks for the insight. I'd love to read more on the topic if you have any links to share.

Regarding the issue, since the `--lang` fixes the discrepancy between headless/headful, I gonna close it for now. If there are other missing headers, we might end up adding other flags to the headless shell.

**Comment by sradu** [comment]
Yup, agreed. I don't have links but I'm always happy to grab coffee in SF.

**Comment by jsoverson** [comment]
Old thread but here is a link regarding detecting headless browsers via header order : https://blog.shapesecurity.com/2015/01/22/detecting-phantomjs-based-visitors/

I'm running into this now and the ability to manage header order and case is important to simulate legit traffic as closely as possible.
