### ISSUE TITLE
When I print the web page to PDF, I set the style to A4, and I can only print one page at a time.

### ISSUE THREAD

**Issue by 767994269** [puppeteer/puppeteer#1985]
Environment:

Puppeteer: 1.0.0
Platform / OS: windows x64
Node.js: 8.9.0
Chromium: 66.0.3335.0 (Developer Build) (64-bit)
What steps will reproduce the problem?

Running the following code several times.
```js
const puppeteer = require('puppeteer');

(async () => {

const browser = await puppeteer.launch({
executablePath: './chromium/chrome.exe',
headless: true
});
const page = await browser.newPage();
await page.goto('xxx');
await page.waitForSelector('xxx');
await page.emulateMedia('print');
await page.pdf({path:'hn.pdf', format: 'A4',printBackground:'true'});
await browser.close();
})();
```
What is the expected result?
When the height of a web page is large enough, a few pages can be printed.
What happens instead?
no matter what the actual height of the webpage is, how can I print only one 
what may be the reason for this?

**Comment by aslushnikov** [comment]
If I understand the question correctly, you can use `pageRanges` option to pass `'1'` - this will always print only the first page.

**Comment by Sanjay007** [comment]
Can i do Console.log(page) and it prints page html?

**Comment by PunkHaz4rd** [comment]
@aslushnikov No, he asked why it doesn't print all the pages in the PDF, but just the first one.
That issue is still ongoing.

**Comment by msarsha** [comment]
Same issue here, I have a content with height set to 8000px (for test purpose) but the generated pdf only include the content shown on the viewport.

I would expect it to be splitted to A4 size pages.

**Comment by colin-johnson** [comment]
@aslushnikov can you reopen this? This is still an ongoing problem, and Ive seen a few related issues

**Comment by mgibson91** [comment]
Experiencing this also, please reopen. Chrome print correctly shows multiple pages, puppeteer only prints first page.

**Comment by karolski** [comment]
For me the problem disappeared when scale was set to less than 0.6
