### ISSUE TITLE
Scope of each page in browser.pages() array

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#1986]
Context: a "central" chrome instance handling requests from multiple clients via puppeteer, with each client connecting a `browser` to the chrome instance via [`puppeteer.connect()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions) using a `browserWSEndpoint` identifying the chrome instance.

When a client calls [`browser.pages()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserpages) to get an array of open pages, if I set a property on a page in the array, e.g. `pages[i].myCustomProperty = 'cool'`, will that page property be visible subsequently to another client (or even the same client) when they subsequently get an array of open pages (including the still-open page on which the property was set)?

**Comment by aslushnikov** [comment]
> When a client calls browser.pages() to get an array of open pages, if I set a property on a page in the array, e.g. pages[i].myCustomProperty = 'cool', will that page property be visible subsequently to another client (or even the same client) when they subsequently get an array of open pages (including the still-open page on which the property was set)?

No. The `Page` object is local to your node.js context. If you want to set a properly on a page, you probably want to set it to page's window object:

```js
await page.evaluate(() => window.FOO = '12');
```
