### ISSUE TITLE
setViewport, Responsive Images, srcsets

### ISSUE THREAD

**Issue by tomgallagher** [puppeteer/puppeteer#1989]
Puppeteer 1.0.0
Cloud9 Workspace
Node Version 7.10.1

I'm not sure this qualifies as a bug, if it does then it probably lies upstream.

I have been testing the src of images on the page when changing the viewport size. On this site, [The Guardian](https://www.theguardian.com/uk), they make extensive use of picture elements, with nested source elements and a nested root image, that use srcsets to deliver responsive images.

I'm using the standard set `page.setViewport` code and then Cheerio to examine the src of the image.

The problem is that the Chrome operation of choosing the correct picture size from the srcset is not transparent to Cheerio as Chrome reports the content html in its original state i.e. before the srcset is analysed and put into effect - even when the image that is downloaded is not the one reflected in the src.

You can get the correct src, for future reference, with this code:

```
var images = await page.$$eval('img', images => {
  var imagesArray = [];
  for (var i = 0; i < images.length ; i++) { imagesArray.push(images[i].currentSrc); }
  return imagesArray;
}));
```

However, it seems that Chrome is performing an operation on the page that is equivalent to a Javascript alteration of the html, in this case image src properties, without that change being reflected in the HTML. This is a bit odd.

**Comment by JoelEinbinder** [comment]
currentSrc is a JavaScript property so it won’t appear in the html.
