### ISSUE TITLE
Is it possible to open headless chrome and after start a script

### ISSUE THREAD

**Issue by rustemkzk** [puppeteer/puppeteer#1990]
I have some code that opens page and then do some script(click buttons, type text etc). So, opening chrome and go to page is about 5 seconds and script is about 4 seconds.
Is it possible to open chrome and go to page
And only then start script at specific time?

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageaddscripttagoptions
