### ISSUE TITLE
Is there a way to make GUI for puppeteer code?

### ISSUE THREAD

**Issue by rustemkzk** [puppeteer/puppeteer#1991]
Is there a way to make GUI for puppeteer code?

**Comment by tnolet** [comment]
@rustemkzk I'm thinking about the same thing, or at least a wizard / code-generator that helps create common use cases. What would that look like in your opninion?

**Comment by rustemkzk** [comment]
@tnolet i saw electron , but i am not sure that this app supported puppeteer. Theoretically, you can paste your puppeteer code in main.js. but really dont understand exactly how it works

**Comment by Nantris** [comment]
You can use Electron for sure. If you want an easy way to get started with Electron, I recommend [Chentsulin's Electron-React-Boilerplate](https://github.com/chentsulin/electron-react-boilerplate)

**Comment by rustemkzk** [comment]
thank you

**Comment by mrgodhani** [comment]
I have made one using Puppeteer https://github.com/mrgodhani/uberrun. Only con is that chromium doesn't work in packaged app. So you need to point executablepath to chromium separately.

UPDATED: Even though you could try to package it using app.asar.unpacked or manually moving dependency. But you will find issue codesigning it.

**Comment by jonmadison** [comment]
I've done the same as mrgodhani. I let the user choose their chrome. Works fine on Mac, but executablePath seems to be ignored on Windows. Researching then filing a bug.

**Comment by davegariepy** [comment]
@jonmadison have you figured out how to do this on windows?

**Comment by jonmadison** [comment]
apologies --

it was related to https://github.com/GoogleChrome/puppeteer/issues/3013

and should be fixed, but turns out that it wasn't honoring the executablePath which i set up as a String template. I had to cast it, i.e.

executablePath: browserpath + "",

Based on the link i sent however, looks like this is fixed.

jon

**Comment by pleerock** [comment]
@mrgodhani from code in your repo I see you download chromium for puppeteer. Do you know is there any way to use electron's bundled chromium for puppeteer in electron packaged app?

**Comment by mrgodhani** [comment]
@pleerock In latest release I just removed downloading of chrome or bundling chromium. I instead use https://www.npmjs.com/package/chrome-launcher and hook that with puppeteer. That works out well as it looks for installed chrome in machine. Bundling chromium was making app bigger in size which is not needed. And I haven't tried with electron's chromium yet.

**Comment by aslushnikov** [comment]
Everybody: Please consider using [Carlo](https://github.com/GoogleChromeLabs/carlo) for the GUI.

**Comment by iamuddeshya** [comment]
> @pleerock In latest release I just removed downloading of chrome or bundling chromium. I instead use https://www.npmjs.com/package/chrome-launcher and hook that with puppeteer. That works out well as it looks for installed chrome in machine. Bundling chromium was making app bigger in size which is not needed. And I haven't tried with electron's chromium yet.

Can you explain how to do that in puppeteer?

**Comment by lobbin** [comment]
> > @pleerock In latest release I just removed downloading of chrome or bundling chromium. I instead use https://www.npmjs.com/package/chrome-launcher and hook that with puppeteer. That works out well as it looks for installed chrome in machine. Bundling chromium was making app bigger in size which is not needed. And I haven't tried with electron's chromium yet.
> 
> Can you explain how to do that in puppeteer?

Probably ChromeLauncher.getInstallations() in conjunction with executablePath in puppeteer.Launch()

**Comment by iamuddeshya** [comment]
Thankyou! I did it using a different way :D 
But thanks for the help! Cheers !

**Comment by Elvincth** [comment]
> Thankyou! I did it using a different way :D
> But thanks for the help! Cheers !

Can you share more? Thanks!

**Comment by basil2style** [comment]
> Carlo

Carlo is no longer maintained.

**Comment by 0xSnowmn** [comment]
After 2 days of searching on StackOverflow and GitHub issues, I found that no actual solutions to build the local chrome with the electron app the best solution was to set the executable path and use chrome installed on the pc but many answers said that You will do it manually but I found this better to do it using "chrome-path" npm package to set path of chrome auto in mac or Linux or Windows here it's my code background.js

```const puppeteer = require("puppeteer")
const chromePaths = require('chrome-paths');

//your electron init window

  const browser = await puppeteer.launch({
    executablePath:chromePaths.chrome,
    headless: false,
    defaultViewport: null,
    args: ['--no-sandbox', '--start-maximized' ],
    slowMo:25,
})
const page = await browser.newPage();
await page.goto("https://google.com")
await app(page)

**Comment by lobbin** [comment]
I ended up with something like this. When using `electron-builder --win zip --x64`, puppeteer will end up in app.asar.unpacked, not in app.asar with the rest of the code.

```
const getChromiumExecPath = () => {
    return puppeteer.executablePath().replace('app.asar', 'app.asar.unpacked');
}

if (!browser) {
  browser = await puppeteer.launch({
    headless: false,
    executablePath: getChromiumExecPath()
  })
}
