### ISSUE TITLE
New page not added to browser.pages() immediately

### ISSUE THREAD

**Issue by shen-my** [puppeteer/puppeteer#1992]
```
const link = await page.$('selector')
await link.click()    // at this time, a new page was successful opened in a new tab in chromium

// get all page
let pages = await browser.pages()
for (const page of pages) {
    console.log(page.url())   // new page not appear at here
}

// get all pages again
pages = await browser.pages()
for (const page of pages) {
    console.log(page.url())   // new page now appear!
}
```
Puppeteer version: 1.0.0
OS: Mac 10.13.2
Node.js version: 9.5.0

**Comment by vsemozhetbyt** [comment]
I think there may be a race condition in this case. Maybe listening for [`'targetcreated'`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-targetcreated) can help.

**Comment by shen-my** [comment]
thanks for @vsemozhetbyt's suggestion, I listened `targetcreated` event and find some oddly phenomenon.
My code procedure is:
1. Go to `www.sogou.com` and type `java` as search word and then press search button
2. When search results arrived, click each of them, every link was opened in a new tab in chromium as expected.

But I found only those links which under `sogou.com` could trigger a `targetcreated` event. the other link such as 
`http://www.runoob.com/java/java-tutorial.html` and
`http://www.51zxw.net/list.aspx?cid=380` 
could not, and not included in `browser.pages()`
When i call `browser.pages()` again, those links appears but `targetcreated` event  never triggered

**Comment by ThomasSimeroth** [comment]
I'm having a similar issue. I'm trying to wait for a popup to appear in a new window, and verify that the contents are correct. In my JavaScript, 
`const newPagePromise = new Promise(x => browser.on('targetCreated', target => x(target.page())));`
`await page.click("#bReport"); //Makes popup`
`await newPagePromise; //Hangs here`

In the website, the button is rigged to call 
`var report=window.open("","Schedule","menubar=0,scrollbars=1,resizable=1");`
before adding html via an AJAX call. 

Although I can see the popup when running in non-headless mode, the promise never resolves. Am I doing something wrong, or is this a bug?

**Comment by jonahaberle** [comment]
I believe I am also having this issue.

**Comment by aslushnikov** [comment]
Everybody: if you're having this issue, please upvote it. We heavily rely on issue likes when picking the next thing to work on.

**Comment by SilurianYang** [comment]
我也遇到了这样的问题，browser.pages()获取不到一些指定的page 比如说出现了隐私设置错误的界面时 他是不会被包含在pages对象里面的

**Comment by tli5** [comment]
encountering same issue. Click triggered pages not being captured by the browser instance.

**Comment by dcalsky** [comment]
A simple solution is: just wait 500ms.

```
    const timeout = ms => new Promise(resolve => setTimeout(resolve, ms));
    element.click()
    await Promise.race([
      await timeout(500),
      this.page.waitForNavigation({
        waitUntil: 'networkidle2',
      }),
    ]);
```

**Comment by dcalsky** [comment]
> 我也遇到了这样的问题，browser.pages()获取不到一些指定的page 比如说出现了隐私设置错误的界面时 他是不会被包含在pages对象里面的


You can disable the error of HTTPS.
```
    this.browser = puppeteer.launch({
      ignoreHTTPSErrors: true,
      ....
    });
```

**Comment by regmish** [comment]
One workaround is to have `waitForTarget`
```javascript
const link = await page.$('selector')
await link.click()    // at this time, a new page was successful opened in a new tab in chromium

const newPage = await browser.waitForTarget(target => target.ur() === link.textContent());

// get all pages
pages = await browser.pages()
for (const page of pages) {
    console.log(page.url())   // new page now appear!
}

**Comment by Dxig** [comment]
I have solved this issue like this.

`const link = await page.$('selector')` 
` await link.click()` 

` const newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.page())))` 
` const newPage = await newPagePromise` 

` const pages = await browser.pages()`

**Comment by undefine-man** [comment]
In 2024, this error still appear.
