### ISSUE TITLE
Launching multiple instances of a script makes it freeze

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#1993]
Hello,
I'm launching 5-10 instances of the same puppeteer script that scrapes webpages but after 10-15 min some of the instances of the script just stops looping through the pages and do nothing. I leaved the headless mode to false in order to check and the script would just stop to a page and do nothing...
How can I solve this / debug this ?

**Comment by JoelEinbinder** [comment]
This not the right place to ask this question. Please try stackoverflow.
