### ISSUE TITLE
Chrome download fails during install.js with custom host and certificate file

### ISSUE THREAD

**Issue by wishrd** [puppeteer/puppeteer#1994]
Installation fails due to SELF_SIGNED_CERT_IN_CHAIN. Proxy settings are not required. I read a related closed issue (https://github.com/GoogleChrome/puppeteer/issues/1735) but the solution not solves my problem.

.npmrc:
```
cafile=C:\workspace\config\cert.cer
puppeteer_download_host=https://examplehost.internal/tools/puppeteer
```

I tried with `ca` and `cert` npm setting too.

If i add the `TEST LINE` in the Downloader.js (now BrowserFetcher.js) file, chrome download works correctly:
```
function httpRequest(url, method, response) {
...
  const driver = options.protocol === 'https:' ? 'https' : 'http';

  // TEST LINE: read the cafile and send it
  options.ca = [fs.readFileSync(process.env.npm_config_cafile)];

  const request = require(driver).request(options, res => {
    if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location)
      httpRequest(res.headers.location, method, response);
    else
      response(res);
  });
...
}
```

Obviously, add this line is not a real solution, but maybe explain where is the problem. I had the same issue with `node-sass` and `phantom-prebuilt` and it works correctly if i set cafile and download url like i have mentioned earlier.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Windows 8.1 Enterprise
* Node.js version: 6.9.1
* NPM version: 5.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `npm install puppeteer@1.0.0`

**What is the expected result?**
Puppeteer gets installed and chrome gets downloaded.

**What happens instead?**
```
λ npm i puppeteer@1.0.0

> puppeteer@1.0.0 install C:\workspace\project\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r526987! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```

**Comment by inabramova** [comment]
setting NODE_EXTRA_CA_CERTS=my_cert_file.pem solved the issue for me and let me download chromium
https://stackoverflow.com/a/35510347/6316474

**Comment by wishrd** [comment]
Thank you @inabramova. NODE_EXTRA_CA_CERTS solve the problem, but this environment var require node 7+. I updated to node 8 few days ago and now it's working (some enterprise environments are difficult to update).

Puppeteer [require at least Node 6.4.0](https://github.com/GoogleChrome/puppeteer#usage) and NODE_EXTRA_CA_CERTS is not available in this version. If puppeteer's team doesn't expect to support node <7, the issue can be closed.

**Comment by aslushnikov** [comment]
> Puppeteer require at least Node 6.4.0 and NODE_EXTRA_CA_CERTS is not available in this version. If puppeteer's team doesn't expect to support node <7, the issue can be closed.

Node6 is becoming less and less used, so I don't think it makes sense to invest here.
