### ISSUE TITLE
Blank screenshots when taking multiple screenshots with clip

### ISSUE THREAD

**Issue by arti005sp** [puppeteer/puppeteer#1996]
We have some heavyweight page (it is our application, using dhtmlx) that we want to export to the  image. The page might be quite big depending on the data it shows.
Because of it the current limitation of exporting big images we open the page setting the viewport to show the whole page and then in a loop we take multiple screenshosts of that page setting the clip accordingly (like making some tile matrix) and then stitch them to one big image.

The problem is that some screenshots taken this way are blank.
When during that export I set 'headless' parameter to false and the chromium launched I observed, that while the screenshots where taken, the whole page seemed to be scrolled vertically and horizontally to be positioned for the screenshot.
I also observed that sometimes during the scrolling it is noticable that the page is blank for a 'short' time before it is rendered (as a reminder that page might be quite heavy in terms of rendering...).
I assume the screenshot is taken before it is rendered and that is why we get blank images.

If I understand the problem correctly, my question is: do we have any means to introduce some delay before the actual screenshot is taken? Or any other ideas of some workaround for the given problem?

Any suggestions are much appreciated as this is quite a problem for us at the moment.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: CentOS 7
* URLs (if applicable): N/A
* Node.js version: 8.9.4

**What steps will reproduce the problem?**
The problem described above.

**What is the expected result?**
All the screenshots should have some content.

**What happens instead?**
Some screenshots are blank.

The example of the image taken this way:
![image_with_blanks](https://user-images.githubusercontent.com/36269466/35979515-d5038b9e-0ce8-11e8-9c61-3a8e18116009.jpeg)

**Comment by grantstephens** [comment]
Think this is related to #1576

**Comment by farynam** [comment]
I experience the same problem.  I had added some code to wait for images completed but it didn't change anything. There are about 24 images total as the page is rather long. Clipping & scrolling correspondingly. I get the first five images perfect after which I get 4 white images, one half-white and the rest 13 images are pure white.  
I use 
node.js: 8.10.0
Linux: SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
puppeteer@1.2.0

Here is my code:
`const puppeteer = require('puppeteer');

(async () => {
  var baseFileName = "images";
  var baseFileExt = "png";
  var outputFile = "images.out"
  var viewPort = {
    width: 1280,
    height: 1024
  };

  process.on('unhandledRejection', (err) => { 
    console.error(err)
    process.exit(1)
  });


  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox', '--shm-size=1gb' ], headless: false});
  const page = await browser.newPage();
  page.setViewport(viewPort);


  page.setDefaultNavigationTimeout(30000000);

  page.on('console', msg => {
    for (let i = 0; i < msg.args().length; ++i)
      console.log(`${i}: ${msg.args()[i]}`);
    });
  

  var gotoOpt = {
    waitUntil : 'networkidle2'
  };

  await page.goto('http://onet.pl', gotoOpt);
  console.log("Page loaded");

  function isScrollable(page) {
    return page.evaluate(() => {
      var  total = document.body.scrollHeight || document.documentElement.scrollHeight;
      var scrollTop = (window.pageYOffset !== undefined) 
        ? window.pageYOffset : (document.documentElement || document.body.parentNode || document.body).scrollTop;
      return {
        total : total,
        scrollTop : scrollTop 
      };
    });
  }


  function pending_image(page) {
      return page.evaluate(() => {
      var images = document.images;
        for (var i = 0; i < images.length; i++) { 
          if (!images[i].complete) {
            return true;
          }
        }
        return false;
    });
 }

 async function waitForImage(page) {
  var isPending = false;
  do {
    isPending = await pending_image(page);      
  } while (isPending);
 }

async function waitForScroll(page, scrolled) {
  while (true) {
        var ret = await isScrollable(page);
        if (scrolled == ret.scrollTop) {
          return;
        }
  }  
}


 function capture_image(page, pageHeightOffset) {
    var path = getNextName();
    console.log("capturing:" + path);
    
    return page.screenshot({path: path, clip: {
      x: 0,
      y : pageHeightOffset,
      width : viewPortWidth,
      height : viewPortHeight
    }});
 }

 function getNextName() {
  return baseFileName + "/" + index++ + "." + baseFileExt;
 }

 function scroll(page, offset) {
    return page.evaluate( offset => {
      window.scrollBy(0, offset);



    }, offset);
 }

 var viewPortHeight = page.viewport().height;
 var viewPortWidth = page.viewport().width;
 var ret = null;
 var left = 0; 
 var pageHeight = null;
 var scrollOffset = 0;
 var index = 1;
 var scrollLeft =0;
 console.log("viewPortHeight:" + viewPortHeight);
 console.log("viewPortWidth:" + viewPortWidth);

//main
 do {
   scrollOffset += scrollLeft; 
   waitForImage(page);
   
   await capture_image(page, scrollOffset);

   {
    var scrollBy = Math.min(50, scrollLeft);
    var scrollRest = scrollLeft % scrollBy;
    var counter = Math.floor(scrollLeft / scrollBy);

    while (counter-- > 0) {
      await scroll(page, scrollBy);
      waitForImage(page);
    }

    await scroll(page, scrollRest);
    waitForScroll(page, scrollOffset);
    waitForImage(page);
  }

   ret = await isScrollable(page);
   scrollLeft = Math.min(viewPort.height, ret.total - ret.scrollTop);


   console.log("chunk:" + index + "/" + (ret.total / viewPort.height));
   console.log("ret1:", ret);
  } while (ret.total > scrollOffset);

   console.log("capturing finished");
   await browser.close();  
})();
`

**Comment by jiajunli** [comment]
me too, i have the same question.
now, do you have solution to resolve this question.

**Comment by RamakrishnaChilaka** [comment]
Any updates ?

**Comment by TimotheeJeannin** [comment]
Any updates on this ?

**Comment by SarthakSri98** [comment]
Any updates on this?

**Comment by ClannadBred** [comment]
Any updates ?

**Comment by KyRionY** [comment]
any updates?

**Comment by JeonYB** [comment]
동일한 문제를 해결하였습니다.
결론적으로 말씀드리면 뷰포트를 적절한 크기(전 모바일 환경에 적용하기 때문에 700 * 15000)로 잡고 스크롤 하며 클립 스크린샷을 하는 방법입니다.

페이지 스크린샷을 위해 viewport의 width,height 를 페이지 전체 사이즈를 잡은 경우,
스크린샷 시 해당 이슈처럼 중간 중간 빈이미지들이 나타나는 현상이 나타났습니다.
로컬환경인 MacOS 에서는 이미지가 비지 않았지만 AWS EC2(CentOS 7.x) 에선 빈 공간(blank)이 많이 나왔습니다. 
인스턴스 타입에 문제인지 싶어 C4.large -> g4dn.xlarge 로도 테스트해보았지만 역시 빈 공간이 캡쳐 되었습니다.

동료의 조언으로 viewport 사이즈를 조절해보았고,
퍼펫티어 낮은 버전에서는 스크롤 관련 코드 없이 정삭적으로 모든 페이지가 캡쳐되었지만..
현재 (5.x.x) 버전에서는 뷰포트를 벗어난 영역에서 빈 공간만 캡쳐되었습니다.
그래서 영역 스크린샷을 하며 스크롤까지 같이 해주는 방식으로 해당 이슈를 해결하였습니다. 

소스 일부를 첨부하겠습니다.


function getBodySize() {
	return page.evaluate(() => {
        var D = document;
		return {
			width : Math.max(D.body.scrollWidth, D.documentElement.scrollWidth,
                D.body.offsetWidth, D.documentElement.offsetWidth,
                D.body.clientWidth, D.documentElement.clientWidth),
			height : Math.max(D.body.scrollHeight, D.documentElement.scrollHeight,
                D.body.offsetHeight, D.documentElement.offsetHeight,
                D.body.clientHeight, D.documentElement.clientHeight)
		}
	});
}
const IMAGE_SLICE_HEIGHT = 15000;
let bodySize = getBodySize();
let y_offset = 0;
let height = 0;
let clip = {};
let viewportSize = {width : Math.ceil(bodySize.width), height : 1};
while(y_offset < bodySize.height) {
	if(y_offset+IMAGE_SLICE_HEIGHT  > bodySize.height) {
		height = bodySize.height - y_offset;
	} else {
		height = IMAGE_SLICE_HEIGHT;
	}
	viewportSize.height = height;
	// set viewport
	await page.setViewport(viewportSize);
	// scroll page for screenshot
	await page.evaluate((y) => {
		window.scrollTo(0,y);
		return y;
	},y_offset);
	clip = {
		x : 0,
		y : y_offset,
		width : bodySize.width,
		height : height};		
    buffer = await page.screenshot({type: opt.type,
           	clip : clip,
            quality : 100,
           	omitBackground : opt.omitBackground});			
	y_offset += height;
}

**Comment by karimabdelhakim** [comment]
workaround [here](https://github.com/puppeteer/puppeteer/issues/2423#issuecomment-590738707)
