### ISSUE TITLE
Preventing a script to stop by handling network errors

### ISSUE THREAD

**Issue by Nicolas-vrcc** [puppeteer/puppeteer#1997]
Hello,
How to handle network / proxy errors with Puppeteer ?
When there's a loading error on the first await I want the loop to stop and to wait until the first await return a success and not an error. Here is the code
```
for (let y = 0; y < mainLinks.length; y++) {
 await page.goto(mainLinks[y], { timwaitUntil: 'networkidle2' })
await page.evaluate(() =>{
return document.querySelector('h1')
})
}
```

**Comment by aslushnikov** [comment]
@Nicolas-vrcc this is a general javascript question and doesn't have anything to do with pptr. Please, ask on StackOverflow.
