### ISSUE TITLE
Refactor JavaScript dialogs API

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#2]
The phantom's approach to handling javascript dialogs is convenient and familiar: instead of firing `Alert`, `Prompt` and `Confirm` events, we should use `onAlert`, `onPrompt` and `onConfirm` callbacks. It would be also convenient to have a complimentary `Dialog` event which dispatches `dialog` class.

**Comment by aslushnikov** [comment]
@dgozman: the 'onAlert', 'onPrompt" and 'onConfirm' setters feel foreign to the rest of the API.
For example:

```javascript
var Browser = require('puppeteer').Browser;
var browser = new Browser();
browser.newPage().then(async page => {
    await page.setViewportSize({width: 1000, height: 1000});
    await page.navigate('http://example.com');
    page.onAlert = message => {
        console.log(message);
    };
    page.onConfirm = message => {
        console.log(message);
        return true;
    }
});
```
How about having `page.setAlertCallback` instead?
Will look like this:

```javascript
var Browser = require('puppeteer').Browser;
var browser = new Browser();
browser.newPage().then(async page => {
    await page.setViewportSize({width: 1000, height: 1000});
    await page.navigate('http://example.com');
    page.setAlertCallback(message => {
        console.log(message);
    });
    page.setConfirmCallback(message => {
        console.log(message);
        return true;
    });
});
```

I like `setAlertCallback` - it is simple and consistent with the rest of the api. What do you think?

**Comment by dgozman** [comment]
I think onFoo is a nice way to subscribe to events. We use it in our testing harnesses a lot.

```
page.onAlert(message => {
  console.log(message);
});
```

**Comment by aslushnikov** [comment]
So we've sat with @paulirish  and get a feeling of a few options here.

We don't like the following, cause it makes it hard to dismiss all the dialogs:
```javascript
page.on('alert', message => {
   console.log(message);
});
```

We don't like the phantom's way, 'cause it's weird:
```javascript
page.onPrompt = message => {
   return {
     text, success
   }
};
```

We don't like the dialog callback, 'cause it's too verbose:
```javascript
page.setDialogCallback(dialog => {
   dialog.accept()
   dialog.type()
   dialog.dismiss();
});
```

The thing which we liked most is the event with `dialog` class:
```javascript
page.on('dialog', dialog => {
   dialog.type // 'alert', 'confirm', 'prompt', 'beforeunload'
   dialog.accept(); // takes optional string
   dialog.dismiss();
});
````

How do you guys feel? @dgozman @ebidel

**Comment by ebidel** [comment]
I like it.

**Comment by aslushnikov** [comment]
For the record: dialog handling is currently suffering on headless due to the [crbug.com/718235](crbug.com/718235). This bug results in all the javascript dialogs being dismissed on headless.
