### ISSUE TITLE
Feature Request: Trigger Custom events

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#2000]
Add a .trigger method to trigger various mouse events. It can be added like `page.mouse.trigger` or `ElementHandle.trigger`.

Right now Mouse has .up, .down, .click and .move events, but there is no scope for custom events.

Sample code for MouseEvent:
```js
function triggerMouseEvent (node, eventType) {
    var clickEvent = document.createEvent ('MouseEvents');
    clickEvent.initEvent (eventType, true, true);
    node.dispatchEvent (clickEvent);
}
```

Possible variations:
```js
.trigger(eventName)
.trigger(eventName, position)
.trigger(eventName, options)
.trigger(eventName, x, y)
.trigger(eventName, position, options)
.trigger(eventName, x, y, options)
```

Example by other libraries:
 - On [CypressJS]( https://on.cypress.io/trigger), use `cy.get('.project-drop').trigger('dragover')` to trigger a dragover event.
 - On jQuery, `.trigger()` to trigger any custom event.
etc.

**Comment by JoelEinbinder** [comment]
You can totally use any of those libraries with Puppeteer!
```js
const elementHandle = await page.$('body');
// Have jQuery loaded on your page.
page.evaluate(element => $(element).trigger('something'), elementHandle);
```

**Comment by entrptaher** [comment]
- Yes I can use jQuery, but the page will have jQuery loaded and might effect the pages own jQuery or various native codes. 
- Having a .trigger() alongside the `page.mouse.up/down/move/click` seems it will extend puppeteers ability more. For example, Dragging and dropping elements and files onto various fields are pretty normal these days, how come we don't wanna automate them? :D

Let's see how it goes.

**Comment by JoelEinbinder** [comment]
Puppeteer's mouse events are much different from `document.createEvent`. We emulate the mouse moving in the browser, not just the event firing in JavaScript. Dragging and dropping elements is certainly something we want to do, but its quite complicated to get right.

**Comment by entrptaher** [comment]
Drag and drop or those are piece of cake once you have the `.trigger`. Right now puppeteer is using `Input.dispatchMouseEvent`, cannot we somehow make this more reusable?

I can always use something like the following as example, but it's not as readable as the trigger keyword.

```js
await this._client.send('Input.dispatchMouseEvent', {
      type: 'mousePressed',
      button: this._button,
      x: this._x,
      y: this._y,
      modifiers: this._keyboard._modifiers,
      clickCount: (options.clickCount || 1)
});
```

Anyway, let's see if someone or I can make some PR or something.

**Comment by schelkun** [comment]
You can also check: https://github.com/GoogleChrome/puppeteer/issues/1804

**Comment by aslushnikov** [comment]
> Drag and drop or those are piece of cake once you have the .trigger

This will be synthetic drag-and-drop and won't always work. However, you can easily implement it atop of current pptr api.

> Right now puppeteer is using Input.dispatchMouseEvent, cannot we somehow make this more reusable?

Where do you lack flexibility with the current API?

**Comment by entrptaher** [comment]
@aslushnikov, that's just not readable as much as the proposed api listed on the original post.

**Comment by aslushnikov** [comment]
@entrptaher I don't like adding puppeteer-level API for the WebPlatform's events. Puppeteer's clicks are way different to the WebPlatform's `document.createEvent`; having them as the only first-class API emphasizes that they're the recommended way to click things on the page. 

I'd recommend to use a set of helper methods to cover your needs.

**Comment by fritx** [comment]
Ref: #441 - How to set Value for a Input Element

```js
async function fillForm (page, form) {
  for (const k of Object.keys(form)) {
    // page.type but slow
    // await page.type(`[name=${k}]`, form[k])

    // or just set value and trigger input event
    await page.evaluate((nK, nForm) => {
      const input = document.body.querySelector(`[name=${nK}]`)
      input.value = nForm[nK]
      const event = new Event('input')
      input.dispatchEvent(event)
    }, k, form)
  }
}
```
