### ISSUE TITLE
puppeteer: Custom Header / Footer not working with Chromium 64.x version (current stable)

### ISSUE THREAD

**Issue by AmitMathur** [puppeteer/puppeteer#2001]
Hi:

I know puppeteer 1.0 is available with Chromium 65.* version, that includes Header and Footer changes.
But given that the stable version of Chromium (as of now) is 64.x, is there any chance we can merge and create a version of Puppeteer with Header and Footer changes for 64.x version?

Thanks,

**Comment by JoelEinbinder** [comment]
the header/footer code is in Chrome itself, so you will have to use 65+.

**Comment by AmitMathur** [comment]
Thanks for your reply... Given 65.x is developer version, I don't see 65 version as in planned to be released. I can see 66 coming in though.
