### ISSUE TITLE
Page stops working when using VPN with headless

### ISSUE THREAD

**Issue by pqvst** [puppeteer/puppeteer#2002]
I'm been trying to diagnose this issue for a while now, and I'd be grateful if anyone has any tips/advice on how to troubleshoot or debug the problem. 

Basically, I have a node app that automates a web form.
1. Fill out fields
2. Click submit button
3. Runs JavaScript and some AJAX requests
4. POSTs form

This all works perfectly fine in most cases, except when I have my VPN active and I'm running puppeteer in headless mode.

```
VPN=no    Headless=false   OK
VPN=no    Headless=true    OK
VPN=yes   Headless=false   OK
VPN=yes   Headless=true    Step 4 (final POST) does not occur...
```

I've tried:
- Logging browser error
- Logging page error, pageerror, console, request, requestfailed, requestfinished
- Saved screenshots

I really have no idea why it doesn't work when my VPN is active and using headless. At first I thought the site might be blocking my VPN service or something, but that doesn't make sense since it works when using Headless=false. Also, clearly headless does work since headless works without VPN. It's so strange...

Any ideas?

**Comment by liguoqinjim** [comment]
@pqvst do you find the solution?

**Comment by pqvst** [comment]
I'm pretty sure it was just a local issue on my end.

**Comment by liguoqinjim** [comment]
But I also have the problem.
VPN=yes   Headless=false   OK
VPN=yes   Headless=true    Very very slow
yeah,I will find whether it is a local issue on my end.Thank you.

**Comment by crackedbeefcake** [comment]
@liguoqinjim found it?

**Comment by pqvst** [comment]
@liguoqinjim, @FinnFrotscher 

Actually, one important thing to consider is that different headers are sent when in headless vs. not headless mode. Also, with regards to VPNs, some sites and CDNs will enforce different header rules depending on your location.

I've found success by always sending the following headers, in this EXACT order! Some endpoints will actually only accept the headers with correct casing and in the correct order.

* Accept
* Accept-Encoding
* Accept-Language

The best way to ensure this is to use the `--lang` argument when creating your puppeteer instance. Without this, puppeteer may not send the Accept-Language header in headless mode.

```
const browser = await puppeteer.launch({ 
  headless: true,
  args: ['--lang=en-GB'],
});
```

I would avoid using `page.setExtraHTTPHeaders` since it will add your extra headers out of order and may not work with some servers.

More info here: https://github.com/GoogleChrome/puppeteer/issues/1984
