### ISSUE TITLE
elementHandle.eval ?

### ISSUE THREAD

**Issue by Mehuge** [puppeteer/puppeteer#2004]
Few days into puppeteer, and it looks fantastic, however I have hit a bit of an issue, which maybe just something I am missing.

I have an `elementHandle` that I have just found using `page.$()` or `page.$x()` and I want to get some info about it, so would like to do for example (could be anything, textContent etc, hence using eval) something along the lines of

     const nodeName = await elementHandle.eval(el => el.nodeName)

I would rather not do `page.$eval(selector, el => el.nodeName)` as I have already found the element once, and in the case of an xpath selector, there isn't an xpath version of $eval

Use Case
--

My use case for this is a set of test scripts I have written in a custom language. It uses the concept of a current element selected using one of three types of selectors, css selector, xpath or test-id (special form of css selector) followed one or more tests or actions, so for example:

    select ".mybutton" tag button at 100,100 size 10,100 check "My Button" click

I am currently looking at re-implementing the language on top of puppeteer.  So select waits for and gets an `elementHandle`. Commands tag, at, size, and click all want to operate on the current `elementHandle` they are not interested by which means the `elementHandle` was obtained.

But there doesn't seem to be to do this currently without going back to the selector for some things, for example node name, textContent and in my case that means doing the following (using tag as the example)

    // get tag name for current element
    let nodeName;
    switch(this.state.type) {
    case "css": 
      await nodeName = this.state.page.$eval(this.state.selector, el => el.nodeName); 
      break;
    case "xpath": 
      await nodeName = this.state.page.$xeval(this.state.xpath, el => el.nodeName);
        // which doesn't even exist, so isn't possible
      break;
    case "test-id": 
      await nodeName = this.state.page.$eval(`*[test-id="${this.state.testId}"]`, el => el.nodeName); 
      break;
    }

Instead of just being able to do

    const nodeName = this.state.element.eval(el => el.nodeName);

**Comment by JoelEinbinder** [comment]
You can pass the ElementHandle as an argument into `page.evaluate`:
```js
const elementHandle = await page.$('body');
const nodeName = await page.evaluate(el => el.nodeName, elementHandle);
```

**Comment by Mehuge** [comment]
Thanks, I had missed that one.

**Comment by stickfigure** [comment]
Can this be reopened as a feature request? Using page.evaluate is an awkward syntax. `elementHandle.$eval(foo => foo.whatever)` makes much more sense. Or even `elementHandle.$eval(null, foo => foo.whatever)` or `elementHandle.$eval('', foo => foo.whatever)`

**Comment by mrckzgl** [comment]
I have stumbled across the same issue. It is quite quirky to use the page for this, as one always needs to pass that page reference across all calls. Therefore, would be much nicer if this is a method of the elementHandle ... but ... wait it actually is already: https://github.com/puppeteer/puppeteer/blob/864ebc86c9e472c5c12bf498f37783804a43cae3/packages/puppeteer-core/src/api/ElementHandle.ts#L251 Ironically, the `elementHandle.evaluate` is internally used by `$eval`: https://github.com/puppeteer/puppeteer/blob/864ebc86c9e472c5c12bf498f37783804a43cae3/packages/puppeteer-core/src/api/ElementHandle.ts#L414  

So why not just make it public?
