### ISSUE TITLE
evaluate function returns an empty object with CSS attribute selector

### ISSUE THREAD

**Issue by tskittles** [puppeteer/puppeteer#2008]
Puppeteer v1.0.0.
Node v8.9.1

I am new to Puppeteer, and have been trying to scrape a url using a CSS attribute selector.

While document.querySelector('a[href^="https://github.com/"]') selects the correct element in the Chrome console, it returns an empty object within Puppeteer's evaluate method. 

Am I approaching this correctly?

```javascript
const puppeteer = require('puppeteer');

(async () => {

  try {
    const browser = await puppeteer.launch();
    const coinPage = await browser.newPage();
    await coinPage.goto('https://coinmarketcap.com/currencies/bitcoin/');

    const githubURL = await coinPage.evaluate((sel) => {
      const element = document.querySelector(sel);
      return element.href ? element : null;
    }, 'a[href^="https://github.com/"]');

    // this should log 'https://github.com/bitcoin/'
    // but it actually is logging an empty object {}
    console.log(githubURL)

    await browser.close();

  } catch (err) {
    console.log('ERROR', err);
  }
})();
```

**Comment by vsemozhetbyt** [comment]
@tskittles 
```js
return element.href ? element : null;
```
returns the element itself which is [serialized](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description) to an empty object by `coinPage.evaluate()`. To get the URL, you need this:
```js
return element.href ? element.href : null; // or: return element.href || null;
```

**Comment by tskittles** [comment]
many thanks :)
