### ISSUE TITLE
In-Page Search for Puppeteer

### ISSUE THREAD

**Issue by rustemkzk** [puppeteer/puppeteer#2009]
Is it possible to find text in puppeteer? Like ctrl+f in google chrome, just typed some text and found it

**Comment by ebidel** [comment]
Please ask questions like this on stackoverflow or the slack channel.

`const found = (await page.content()).match(REGEX)` is a simple solution.

**Comment by rustemkzk** [comment]
@ebidel i have error - "Regex is not definied". Can you help me,please?

**Comment by rustemkzk** [comment]
i use this code 

`const found = (await page.content()).match(/thank/gi)`

works like a charm

**Comment by hadifarnoud** [comment]
I can't get this to work
```
                const phone = (await page.content()).match(/a[href^="tel:"]/gi)
                console.log("phone: ", phone.getAttribute("href"))
                phones.push(phone.getAttribute("href"));
```

what am I doing wrong? is there any documentation on how `.match` works in Puppeteer?

update: tried `const phone = (await page.content()).match(/^(09|\+989)\d{9}$/gi)` as well but no luck

**Comment by forzagreen** [comment]
You can use [evaluate](https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-pageevaluatepagefunction-args) with [window.find](https://developer.mozilla.org/en-US/docs/Web/API/Window/find) :
```js
const found = await page.evaluate(() => window.find("your_text"));
```

**Comment by JohnDotOwl** [comment]
> You can use [evaluate](https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-pageevaluatepagefunction-args) with [window.find](https://developer.mozilla.org/en-US/docs/Web/API/Window/find) :
> 
> ```js
> const found = await page.evaluate(() => window.find("your_text"));
> ```

This works pretty well. Thank you for your contribution. I appreciate it :)

**Comment by bhishp** [comment]
Just a note on window.find, it seems that it will work in the same way as the native browser implementation, so it will iterate through each instance of the search text, so can return false if window.find is called twice on the same page when there is only a single instance of the word.

**Comment by andrewpolemeni** [comment]
Okay so how would you do this if some pages have the Regex but others don't?

const how_many_in_stock = (await page.content()).match(/\d* \bin \bstock/g);

I don't want the function to time out if it is not there.

**Comment by brokenmold** [comment]
> const found = (await page.content()).match(/thank/gi)

If it's a super complex amount of data to sift through it may timeout before complete. Should return _null_ if not found. Use screenshot before function to make sure the data has even loaded.

You can set the default timeout:
`page.setDefaultNavigationTimeout(130000)`

You can add an individual timeout like after/before a function.
`await page.waitForTimeout(500)`
