### ISSUE TITLE
TypeError: page.waitForXPath is not function.

### ISSUE THREAD

**Issue by higeaaa** [puppeteer/puppeteer#2026]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Linux Ubuntu 16.04
* URLs (if applicable):
* Node.js version: 9.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. npm install puppeteer (or yarnpkg add puppeteer)
2. run this code.
```js
'use strict';

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://google.com', {waitUntil: 'networkidle2'});


// Wait for the results to show up
await page.waitForXPath('//input')
  .then(() => console.log('Hello!'))
  .catch(e => console.log(e))

browser.close();

})().catch(e => console.log(e))
```

**What is the expected result?**
Expect print 'Hello!' on the console.

**What happens instead?**
`TypeError: page.waitForXPath is not a function`

`waitForXPath` exist on [page.js](https://github.com/GoogleChrome/puppeteer/blob/4a53bca6b081643855e005c940d8cbc52404e99e/lib/Page.js#L882). But my `page.js` that download by npm or yarn does not exist `waitForXPath`.

Thanks.

**Comment by vsemozhetbyt** [comment]
For puppeteer version: 1.0.0 you need [v1.0.0 docs](https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/docs/api.md)

`page.waitForXPath()` is available from the v1.0.0-post ([main doc page](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md) is always for the master branch). 

You can upgrade with `npm install https://github.com/GoogleChrome/puppeteer/`.

**Comment by higeaaa** [comment]
@vsemozhetbyt Thank you for your answer, and I got '`waitForXPath`" by upgrading with `npm install https://github.com/GoogleChrome/puppeteer/`.
And I learned that the download target in npm is not always master-branch.

Thank you.

**Comment by ShubhojitBhattacharjee** [comment]
I am still getting

> TypeError: page.waitForXPath is not a function

error even after upgrading with `npm install https://github.com/GoogleChrome/puppeteer/`

**Comment by ShubhojitBhattacharjee** [comment]
And also while using `page.$x(xpathExpression)` I get error

> TypeError: page.$x is not a function

`const [compareButton] = await page.$x('//img[@src="productA.jpg"]/following-sibling::div[text()="Compare"]');`

I have already installed puppeteer-xpath, still it doesn't work.
