### ISSUE TITLE
bump chromium version to r536535

### ISSUE THREAD

**Issue by rjktcby** [puppeteer/puppeteer#2028]
this [patch](https://crrev.com/e1b855d4545dc4fff19cee500d7ce105126f3bd2) fixes important bug for automated UI testing using puppeteer: inconsistencies between font rendering in headless and desktop modes in the same OS (at least on linux)

**Comment by alixaxel** [comment]
@rjktcby Which revision is this?

**Comment by rjktcby** [comment]
@alixaxel I'm kind of new to chromium, could not identify revision number aka **rXXXXX** when submitting this issue

Here's commit in googlesource:
https://chromium.googlesource.com/chromium/src.git/+/e1b855d4545dc4fff19cee500d7ce105126f3bd2

Here's on github:
https://github.com/chromium/chromium/commit/e1b855d4545dc4fff19cee500d7ce105126f3bd2

it was tagged as **66.0.3347.2**

hope this helps

**Comment by alixaxel** [comment]
```
Commit: f7f31a153670f82f412944323992b1bef6f38dd0
Branch Base Commit: 3b9cfdda2eb80dab7457ec61e619dd910d194248
Branch Base Position: 536620
V8 Version: 6.6.239.0
V8 Position: 1
Skia Commit: f802e757646f424b563fdc1f5b5ee3c677659e98
```

I'm not sure if it's the **Branch Base Position** or not.

**Comment by rjktcby** [comment]
Maybe this one?
```
    Cr-Commit-Position: refs/heads/master@{#536535}
```

**Comment by rjktcby** [comment]
@alixaxel yeah, it should be **r536535**
https://crrev.com/536535 points to this same change

**Comment by alixaxel** [comment]
@rjktcby Closed by #2024?

**Comment by rjktcby** [comment]
@alixaxel I don't think so

#2024:
https://crrev.com/536395: Tue Feb 13 17:16:04 2018

but my patch was merged to chromium master a few hours later:
https://crrev.com/536535: Tue Feb 13 23:08:53 2018

**Comment by aslushnikov** [comment]
We'll be able to roll once https://chromium-review.googlesource.com/c/chromium/src/+/923007 gets landed.
