### ISSUE TITLE
`page.goto(url, {waitUntil: 'networkidle0'})` hangs until timeout

### ISSUE THREAD

**Issue by docteurklein** [puppeteer/puppeteer#2029]
Hi,

(Really sorry if that's a duplicate. I searched everywhere before opening this issue and didn't find anything related.)

I don't understand why this works:
```js
    page.goto(url);
    await page.reload({waitUntil: 'networkidle0'});
```

but this doesn't:
```js
    await page.goto(url, {waitUntil: 'networkidle0'});
```

It seems `page.goto` doesn't always detect the `networkidle0` event, or maybe the event is already triggered before it has time to observe it?

### Steps to reproduce

* Puppeteer version: 1.0.0
* Platform / OS version: Linux 4.14.15-1-ARCH x86_64 GNU/Linux
* URLs (if applicable): http://demo.akeneo.com/ (credentials: admin/admin)
* Node.js version: 9.4.0

**What is the expected result?**

I expect `page.goto(url, {waitUntil: 'networkidle0'});` to resolve when network is idle.

**What happens instead?**

 `page.goto(url, {waitUntil: 'networkidle0'});` never resolves even tho the network is idle.

Thanks for your time!

**Comment by jontro** [comment]
I've received the same error today. I used page.setContent as a workaround instead

**Comment by docteurklein** [comment]
Could you provide an example usage ? I'm not sure I follow how `setContent` would help navigation.
Thanks :)

**Comment by jontro** [comment]
@docteurklein Sorry about that. Ignore my last comment, anyways I got the same error while playing around yesterday.

**Comment by aslushnikov** [comment]
@docteurklein the following script works fine for me with pptr v1.1.0:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://demo.akeneo.com/user/login', {waitUntil: 'networkidle0'});
  await page.type('#prependedInput', 'admin');
  await page.type('#prependedInput2', 'admin');
  await Promise.all([
    page.click('button[type=submit]'),
    page.waitForNavigation({waitUntil: 'networkidle0'})
  ]);
  await browser.close();
})();
```

Hope this helps.

**Comment by Edd1525** [comment]
Thanks, @aslushnikov!!!

**Comment by wirtaw** [comment]
Thanks @aslushnikov
