### ISSUE TITLE
After setting a page viewport size some pages are not scrollable anymore

### ISSUE THREAD

**Issue by marijanlekic** [puppeteer/puppeteer#2034]
**Tell us about your environment:**

* Puppeteer version: latest commit
* Platform / OS version: MacOS High Sierra 10.13.3
* URLs (if applicable): http://www.aegambiente.com/link.html
* Node.js version: v8.6.0

**What steps will reproduce the problem?**
Open a page, navigate to "http://www.aegambiente.com/link.html".
Change the viewport size.
Try to scroll the page.

**What is the expected result?**

Im able to scroll the page normally. 

**What happens instead?**
No matter if a mode is headless or headfull, while scrolling manually (with mouse) or using a code (window/element scrollTo function), page is flickering and being scrolled on the top again. Most of the pages works correctly but there are some with this strange behavior. Without setting a viewport size, scroll works fine.

**Comment by aslushnikov** [comment]
@marijanlekic the `link.html` has a code that adds/removes certain CSS class on page scrolling; this makes the page jump for me when the viewport is emulated.

![image](https://user-images.githubusercontent.com/746130/36515716-9824ec9e-172f-11e8-99ee-bf3ead71cc93.png)
