### ISSUE TITLE
How to pass required module object to puppeteer page.evaluate

### ISSUE THREAD

**Issue by cyberz** [puppeteer/puppeteer#2039]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.9.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `npm install varname`
2. run code:
```
const puppeteer = require('puppeteer');
const varname = require('varname');
...
const page = await browser.newPage();
await page.goto(url);
let generalInfo = await page.evaluate(() => {
        let elements = Array.from(document.querySelectorAll('#order-details > table > tbody > tr'));
        let res = {};
        elements.map((tr) => {
            let split = tr.innerText.trim().split('\t');
            res[varname.camelback(split[0])] = split[1]; // Here is: ... Error: Evaluation failed: ReferenceError: varname is not defined
        });
        return res;
    }); 
...
await browser.close();
```
3.

**What is the expected result?**
Expected access to **varname** inside page.evaluate( ...

**What happens instead?**
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: ReferenceError: **varname is not defined**

[Question on stackoverflow](https://stackoverflow.com/questions/48815565/how-to-pass-required-module-function-to-puppeteer-page-evaluate)

**Comment by aslushnikov** [comment]
The question on SO was answered.
