### ISSUE TITLE
Is it normal to have an `about:blank` page after closing a page?

### ISSUE THREAD

**Issue by davidbielik** [puppeteer/puppeteer#2040]
Is it expected behavior to have 1 page `about:blank` when you create a browser, create a page, and close that single page?

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Mac OS 
* URLs (if applicable):
* Node.js version: 8.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```
(async () => {
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true,
        headless: true,
        timeout: 30e3,
        handleSIGINT: true,
        handleSIGTERM: true,
        handleSIGHUP: true
    });
    var page = await browser.newPage();
    await page.goto('http://example.com');

    await page.close();

    var pages = await browser.pages();
    // expect: pages.length === 0
    // actual: pages.length === 1
    pages.forEach(page => {
        console.log(page.url());
    });
})();
```
**What is the expected result?**

No pages should exist

**What happens instead?**

1 page exists, url = "about:blank"

**Comment by grantstephens** [comment]
Yes, I've seen this, the browser starts up with a single page open, just like it does on chrome.

**Comment by boogerlad** [comment]
change `var page = await browser.newPage();` to `var page = (await browser.pages())[0];`

**Comment by davidbielik** [comment]
@boogerlad good idea, that would be good for the first page, but when I open multiple pages within the same browser I'd need to manage that.

**Comment by boogerlad** [comment]
`(await browser.pages())` returns an array of pages. You can use that to access all the other pages you may create.

**Comment by JohnDotOwl** [comment]
@boogerlad  var page = await browser.newPage(); seems to be working fine for me now. Perhaps updated since it's been a year.

**Comment by Alfagun74** [comment]
> change `var page = await browser.newPage();` to `var page = (await browser.pages())[0];`

Watch out when you use the puppeteer-extra/recaptcha plugin and need to solve iframe captchas. It can not handle this in version 3.2.0. see https://github.com/berstend/puppeteer-extra/issues/369

**Comment by berstend** [comment]
@Alfagun74 This sounds a bit harsh 😄 

It's a conscious design decision to not attach to existing pages (there are pros & cons here).

Here's an easy workaround for users of `puppeteer-extra` that wish to make plugins aware of pre-existing pages:

```js
const puppeteer = require("puppeteer-extra")

const RecaptchaPlugin = require("puppeteer-extra-plugin-recaptcha")
const recaptcha = RecaptchaPlugin()
puppeteer.use(recaptcha)

puppeteer.launch({ headless: false }).then(async browser => {
  // Add recaptcha to existing pages
  const pages = await browser.pages()
  for (const page in pages) {
    await recaptcha.onPageCreated(page)
  }
  // do normal stuff here
  await browser.close()
})
```

**Comment by Alfagun74** [comment]
@berstend didn't mean to sound harsh bro ❤ just purely informative, so others don't "such den Wolf". :)

**Comment by berstend** [comment]
@Alfagun74 haha all good :-) thanks for clarifying 👍
