### ISSUE TITLE
Flag to prevent reinstallation of chromium

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#2044]
if puppeteer is a dependency, everytime I run `npm install` it will re-download and re-install Chromium. Is there some flag I can use to prevent doing this everytime I run `npm install`?

something like:

`PUPPET_INSTALL_CHROMIUM=false npm install`

**Comment by squarism** [comment]
@ORESoftware It's there I think.  `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables

**Comment by ORESoftware** [comment]
thank you *but*

`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=?`

what are the values for yes/no

I assume any string there means yes

`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=foobar # skip is true`

but if you people are using things programmatically, users may want to flip `foobar` so that it means _do not skip_.

**Comment by squarism** [comment]
If it's set to anything, that's `true`.  If it's not set at all that's `false`. Because of this code:
```
if (process.env.PUPPETEER_SKIP_CHROMIUM_DOWNLOAD) {
```

Don't set it to false, that's confusing.  The default is not to skip.  Set it to anything (true makes sense) to skip and override the default behavior.

**Comment by ORESoftware** [comment]
got it yeah that works thx
