### ISSUE TITLE
[Feature Request] Data extraction & interaction DSL

### ISSUE THREAD

**Issue by BernhardBehrendt** [puppeteer/puppeteer#2045]
Hey Puppeteer guys,

I really think you've made a great job so far and I'm imprerssed by all the posibillities you gave us developers now. Of course I know there are tools like selenium but puppeteer made this browser interaction accessible and accepted for me. While using pupeteer I've figured out that from my pov I'm using it mostly as a tool to extract data from one or a series of urls and connect these to user individual input or analytic purposes. After a while I've written a lib to "datafy" websites using a DSL that gets translated into pupeteer method calls. Since one week it's getting more and more stable and after integrating it in other puppeteer projects of colleagues I see endless possibilities having a DSL to do such things on websites like  a human could do in the same way.

So from an open source perspective I think the best place to have something realized like that is on the puppeteer level rather than having a separate lib to reduce the barriers using such a DSL. 
So I wanted to ask is if this is something you could imagine to have in puppeteer or if this is not alignable / too different with your scope.

I think to really close the gap in terms of "make websites analyzable/programmatically usable for the main internet user" would be, to have an understandable chrome extension that make DOM selectors accessible and build the DSL in background... But also aspects like job queuing and assertions would be possible more easy such a way.

Anyway...

I'd like to ask you if you could imagine to do something like this together.

_Build an additional DSL in puppeteer to grab data declarative from a website and navigate to others as well_ 

As mentioned above I've build a basic lib to do things explained above but I would also like to help getting something like this work in puppeteer directly.

You'll find the draft [here](https://www.npmjs.com/package/fetchbot) and [here](https://github.com/AOEpeople/puppeteer-fetchbot)

Thanks so far for reading and of course for your great work.

Bernhard

**Comment by BernhardBehrendt** [comment]
<img width="1500" alt="bildschirmfoto 2018-02-16 um 19 27 09" src="https://user-images.githubusercontent.com/1717382/36336187-e04e5fbc-1385-11e8-835f-1310bc501043.png">

**Comment by JoelEinbinder** [comment]
This is certainly interesting, but I think it’s outside the scope of Puppeteer. You can and should use external libraries in tandem with puppeteer, but in the core project we want to stick as close as possible to the web platform.
