### ISSUE TITLE
Using the dumpio setting throws an error in v1.1.0

### ISSUE THREAD

**Issue by datummm** [puppeteer/puppeteer#2046]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version: Ubuntu 16.04
* Node.js version: 6.13.0

**What steps will reproduce the problem?**
Running this code:
```
const puppeteer = require('puppeteer');

puppeteer.launch({
  dumpio: true
}).then(function (browser) {
  // irrelevant code here
});
```

**What is the expected result?**
This should not cause an error.

**What happens instead?**
There is a thrown error:
```
(node: 23455) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: input.on is not a function
```
And the program exits.

**More notes**
Version 1.0.0 seems not to have this issue.

**Comment by ebidel** [comment]
Confirmed. Thanks for reporting.

**Comment by yanivefraim** [comment]
What about changing:

`const stdio = options.dumpio ? ['inherit', 'inherit', 'inherit'] : ['pipe', 'pipe', 'pipe'];` 

to be:

```js
if (options.dumpio) {
  chromeProcess.stderr.pipe(process.stderr);
  chromeProcess.stdout.pipe(process.stdout);
}
```

I would be happy to add a PR for that...

**Comment by paulirish** [comment]
@yanivefraim that'd be great. can you also include a test?

**Comment by yanivefraim** [comment]
Sure, I'm on it
