### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [puppeteer/puppeteer#2047]
Hello! I would like to translate the project into Spanish! is it already translated?

**Comment by ebidel** [comment]
Related discussion: https://github.com/GoogleChrome/puppeteer/issues/608

Thanks for @dbucci24. At this time, we want to avoid translating the docs b/c things are still changing too much. You're welcome to translate the docs and host them in a wiki or fork. We'd entertain the idea of linking off to the Spanish version.

Just post here or open a new issue if you end up going forward.
