### ISSUE TITLE
Virtualbox causing slow navigation times

### ISSUE THREAD

**Issue by forvais** [puppeteer/puppeteer#2048]
**Tell us about your environment:**

* Puppeteer version: Puppeteer@1.0.0
* Platform / OS version: Windows 7 Ultimate SP1 64-bit 
* Node.js version: v9.4.0

**What steps will reproduce the problem?**

1. Install Oracle VM VirtualBox v5.2.6
2. Run this code

```
(async () => {
    try {
        const browser = await require('puppeteer').launch();
        const page = await browser.newPage();

        let timeTotal = 0;

        for (let i = 0; i < 10; i++) {
            const timeStart = (new Date()).getTime();
            await page.goto('http://google.ca');
            timeTotal += (new Date()).getTime() - timeStart;
        }

        console.log(`Running Puppeteer Headless: ${timeTotal / 10}ms average load time.`)

        await browser.close();
    } catch (e) {
        console.log(e);
    }
})();
```

**What is the expected result?**
`Running Puppeteer Headless: (number < 10000)ms average load time.`

**What happens instead?**
When using chromium headless: `Error: Navigation Timeout Exceeded: 30000ms exceeded`.
Normal expected result when using chromium full 

---
My previous tests suggested my specific problem with navigation times wasn't a hardware issue but more likely a software issue: #1846 

Uninstalling Virtualbox is a workaround but its obviously not ideal.

**Comment by aslushnikov** [comment]
@Forvana this looks like a problem in the environment. I'm not familiar with the setup and I won't be able to help here; feel free to ask in our slack channel.
