### ISSUE TITLE
Ability to take screenshot of a particular DOM node

### ISSUE THREAD

**Issue by sushant-j** [puppeteer/puppeteer#2051]
* Puppeteer version: 1.1.0
* Platform / OS version: Linux Ubuntu 14.04 LTS
* Node.js version: v7.10.1

Is there a way by which I can create a screenshot of a particular DOM node? 
E.g. The way Chrome DevTools allows node screenshots or the way webshot allows, specifying a _targetSelector_ attribute.

**Comment by nammaianh** [comment]
Here is your answer
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlescreenshotoptions

**Comment by sushant-j** [comment]
Thanks a lot! Closing this issue.
