### ISSUE TITLE
Allow Chromium process "detached" argument to be configurable?

### ISSUE THREAD

**Issue by marijanlekic** [puppeteer/puppeteer#2053]
Is there any special reason why Chromium process is spawned with "detached:true" argument? Can it be configurable? I have a situation on windows platform when i am creating child processes which are launching puppeteer instances. When i kill child processes, Chromium instances remain (on windows signal SIGTERM is not supported ... ). Is this a preferable solution or something else?

**Comment by aslushnikov** [comment]
> Is there any special reason why Chromium process is spawned with "detached:true" argument?

That's the prerequisite to close process subtrees on linux. I don't think this is necessary on windows though.

@marijanlekic on windows, i believe the only way to kill process subtree is to use `taskkill /T`. Is this the way you close your processes?

**Comment by marijanlekic** [comment]
At first i was killing Chromium instances in that way (taskkill) from the parent process because i did not find a way to do it in the child process (process.on('exit'), process.on('SIGTERM')... did not work on windows for the child process), but when i tried detached:false (changing it manually in Launcher.js) it worked (all chromium instances was killed once i killed child process). According to 
 Node official documentation:

>  "On Windows, setting options.detached to true makes it possible for the child process to continue running after the parent exits. The child will have its own console window. Once enabled for a child process, it cannot be disabled."

Does it makes sense to make it configurable or to set it on false if platform is windows?
