### ISSUE TITLE
Using setRequestInterception causing timeouts on some urls

### ISSUE THREAD

**Issue by SmithKevin** [puppeteer/puppeteer#2055]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version:  MacOS 10.13.2
* URLs (if applicable): 
* Node.js version: 8.4.0

**What steps will reproduce the problem?**
```
    const puppeteer = require('puppeteer');

    puppeteer.launch().then(browser => {
        return browser.newPage();
    }).then(async page => {
        await page.setRequestInterception(true);
        await page.goto('http://google.com');
    })
```
If you comment out the `await page.setRequestInterception(true);` or set it to false then the goto returns a 200 as expected.  buzzfeed and goodreads were other urls I found with the same issue.

**What is the expected result?**
Goto returns a 200 regardless of if setRequestInterception is turned on.

**What happens instead?**
`(node:42764) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded`

Version 1.0.0 seems to work as expected

**Comment by ebidel** [comment]
If you turn on request interception, you need to handle the request in a `page.on('request')` callback. Either by calling `request.continue()` or `request.abort()`.

**Comment by SmithKevin** [comment]
Thanks for the update.   Good to know that the page.on is required I assumed it just defaulted to continue.   The example I gave was just a super simplified version of the script I have been running fine on 1.0.0 but was starting to get more timeouts on 1.1.0.  I thought I got the root cause, but no.  Here is my new (not as simple) script that shows the issue that wasn't happening on 1.0.0.
```
    const puppeteer = require('puppeteer');

    puppeteer.launch(
       {ignoreHTTPSErrors: true }
    ).then(browser => {
        return browser.newPage();
    }).then(async page => {
        await page.setRequestInterception(true);
        page.on('request', request => {
                request.continue();
        });
        const resp = await page.goto('http://goodreads.com', {waitUntil: ['networkidle2']});
    });
```

It really looks like the `setRequestInterception` , `ignoreHTTPSErrors`, `networkidle2` and the site goodreads is required.   I have no clue how all those pieces work together, but if you remove one, the script seems to work.   I'm not sure what to do to debug it further, but just thought I'd share.

**Comment by ebidel** [comment]
It looks like that site times out when using `networkidle2`. There are resources being loaded that keep the network active. Try using `load` or `domcontentloaded`.

**Comment by runningabcd** [comment]
> load



> 看起来该网站在使用时超时了`networkidle2`。正在加载资源以保持网络活动。尝试使用`load`或`domcontentloaded`。



> It looks like that site times out when using `networkidle2`. There are resources being loaded that keep the network active. Try using `load` or `domcontentloaded`.

I had the same problem，The timeout problem persists after change waitUntil to load or domcontentloaded.

test url : https://ent.cmbc.com.cn/eweb/static/main_new.html?locale=zh_CN

If page.setRequestInterception(False) ，The program will not time out and will get real results。

This is Bug !!!!! Please test it !!!!!

Don't close it!!!!! 
Closing the issue does not solve the problem！！！！！！
