### ISSUE TITLE
External script appended to iframe doesn't get executed

### ISSUE THREAD

**Issue by Vasile-Peste** [puppeteer/puppeteer#2057]
Hi,

When I dynamically create an iframe and I append a script tag to it, the script doesnt get executed.

```javascript
const EMPTY_DOCUMENT = `
    <!DOCTYPE html>
    <html>
        <head></head>
        <body></body>
    </html>
`;
const browser = await puppeteer.launch({
    headless: true,
    args: [ "--disable-web-security", "--user-data-dir", "--no-sandbox" ]
});
const page = await browser.newPage();

await page.goto("www.example.com");
await this.page.evaluate((script, doc) => {
    return new Promise(resolve => {
        const frame = document.createElement("iframe");   
        frame.onload = () => resolve(this.contentWindow.document.documentElement.innerHTML);
        frame.src = "data:text/html;charset=utf-8," + encodeURI(doc.replace("</head>", script + "</head>"));
        document.body.appendChild(frame); 
    });
}, `<script src="http://upload.abstract-lang.com/iubenda-radar-inject-test.js"></script>`, EMPTY_DOCUMENT);

console.log(result);
/* The result should have a span tag in the body,
 * the span tag is appended by the external script.
 * The span tag is missing this means the script has not been executed.
*/

await browser.close();
```

**What is the expected result?**
The external script to get executed.

**What happens instead?**
The external script doesn't get executed.

**Comment by JoelEinbinder** [comment]
The script doesn't work for me. You use `this` in `frame.onload`, which would usually reference the frame but its in an arrow function so `this` is the example.com window. Then you try to access its document element, which will throw because example.com can't reach into a cross origin iframe. I do see the span appended by the script though.

**Comment by Vasile-Peste** [comment]
Hi, the span tag is appended only if the origin is abstract-lang.com because the javascript resource is on upload.abstract-lang.com. Is there a way to load the javascript resource in other origins for instance example.com and not abstract-lang.com?
