### ISSUE TITLE
Page.setDownloadBehavior crashes browser

### ISSUE THREAD

**Issue by gustavomanolo** [puppeteer/puppeteer#2058]
# Steps to reproduce
Tell us about your environment:

# Puppeteer version: 1.1.0
Platform / OS version: macOS High Sierra (10.13.3)
Node.js version: 8.9.1

# What steps will reproduce the problem?
Running this code:
```

const puppeteer = require('puppeteer');

const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page._client.send("Page.setDownloadBehavior", {
    behavior: "allow",
    downloadPath: "./"
  });

  await page.goto(
    "https://unsplash.com/photos/of0pMsWApZE",
    {
      waitUntil: "networkidle2"
    }
  );

  // Click download
  await page.click(
    '#app > div > div:nth-child(5) > div > div:nth-child(1) > div:nth-child(1) > header > div._3-6v7 > div._13Q-._27vvN._2iWc- > a > span > span'
  );

  await page.waitFor(2000); // 2 seconds (wait for crash)

  // Close browser
  await browser.close();
})();
```

# What is the expected result?
Download an image to the specified "downloadPath".

# What happens instead?
Downloads the image to the default "Downloads" folder and the browser crashes with the following details:

Process:               Chromium [23258]
Path:                  /Users/USER/Documents/*/Chromium.app/Contents/MacOS/Chromium
Identifier:            org.chromium.Chromium
Version:               66.0.3347.0 (3347.0)
Code Type:             X86-64 (Native)
Parent Process:        node [23257]
Responsible:           Hyper [1461]
User ID:               501

Date/Time:             2018-02-19 17:53:09.882 -0600
OS Version:            Mac OS X 10.13.3 (17D47)
Report Version:        12
Anonymous UUID:        69280D0C-96E0-D614-66CF-045F9809CE9E

Time Awake Since Boot: 14000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018

VM Regions Near 0x18:
--> 
    __TEXT                 000000010f742000-000000010f743000 [    4K] r-x/rwx SM=COW  /Users/USER/Documents/*/Chromium.app/Contents/MacOS/Chromium

**Comment by aslushnikov** [comment]
`Page.setDownloadBehavior` is experimental feature; we're working on a different approach to support downloads, see #299
