### ISSUE TITLE
Page.goto is locking the html file.  I am running puppeteer to run a local saved html file.  But when page.goto is operating, it is locking the html file and the next process has problem accessing it.  Please advise.  Is there a way to run the page.goto as just read-only?

### ISSUE THREAD

**Issue by StephenxKim** [puppeteer/puppeteer#2059]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by StephenxKim** [comment]
Page.goto is locking the html file. I am running puppeteer to run a local saved html file. But when page.goto is operating, it is locking the html file and the next process has problem accessing it. Please advise. Is there a way to run the page.goto as just read-only?

-version 1.3
-rhel 7.4
-n/a url
-latest Node.js

**Comment by aslushnikov** [comment]
@StephenxKim I believe chrome doesn't hold open file handles for the `file://` urls. At least I can easily navigate browser to the `file://` url and then access the file in my editor.
