### ISSUE TITLE
QuerySelector dont work with puppeteer but its works on Chrome Console

### ISSUE THREAD

**Issue by emontesg** [puppeteer/puppeteer#2060]
I have this selector in my code 
const NAME_SELECTOR = '#cmExtensionPoint-id > base-root > div > div.base-root-body._ngcontent-prw-1 > div.view-container._ngcontent-prw-1 > view-loader > campaign-view > tableview > div:nth-child(5) > ess-table > ess-particle-table > div.ess-table-constraint > div > div.ess-table-canvas.mouse-active.density-cozy.particle-table-noborder.hscroll > div:nth-child(2) > ess-cell.last-frozen-column > campaign-name > a';

When i run this selector with puppeteer don't work because not found, but when i run this on console chrome like this :
document.querySelector('#cmExtensionPoint-id > base-root > div > div.base-root-body._ngcontent-prw-1 > div.view-container._ngcontent-prw-1 > view-loader > campaign-view > tableview > div:nth-child(5) > ess-table > ess-particle-table > div.ess-table-constraint > div > div.ess-table-canvas.mouse-active.density-cozy.particle-table-noborder.hscroll > div:nth-child(2) > ess-cell.last-frozen-column > campaign-name > a')

Its works, i dont know why ?

**Comment by ebidel** [comment]
What's the page?  Does the selector match something when your window size is <= 800x600?

**Comment by JoelEinbinder** [comment]
Long query selectors aren't very robust. Elements might be in different places in the DOM because of JavaScript, which might depend on whether or not you are logged in, your screen size, your browser, how fast your computer is, today's opening stock market price, etc.
