### ISSUE TITLE
[PDF] different rendering according to emulateMedia (bootstrap)

### ISSUE THREAD

**Issue by MaximeMaillet** [puppeteer/puppeteer#2061]
Hi!

I use puppeteer 1.1.0 and I want print web page in PDF.
Node 8.9.1
CSS is used with bootstrap 4 (row + col, nothing extraordinary else).
I used page-break-after, page-break-inside for break part of section in @media print.

> page.pdf() generates a pdf of the page with print css media. To generate a pdf with screen media, call page.emulateMedia('screen') before calling page.pdf():

My break page does not work correctly.

![screen shot 2018-02-20 at 15 52 18](https://user-images.githubusercontent.com/14997660/36430678-1779e646-1656-11e8-8d3b-d7e2c5f79224.png)

When I add `await page.emulateMedia('print');`

![screen shot 2018-02-20 at 15 53 48](https://user-images.githubusercontent.com/14997660/36430783-4903cbfa-1656-11e8-8dab-8556f4946710.png)

Code which generate PDF with an url.

```javascript
  try {
    const path = `${variables.cv_directory}${uuidv1()}.pdf`;
    const browser = await puppeteer.launch({
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox'
      ]
    });

    const page = await browser.newPage();
    await page.setCacheEnabled(false);
    await page.goto(cv_url, {waitUntil: 'networkidle2'});
    await page.emulateMedia('print');
    await page.pdf({
      path,
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
    });

    browser.close();

    res.sendFile(path);
  } catch(err) {
    res.send(err);
  }
```

**Comment by JoelEinbinder** [comment]
I'm having trouble reproducing this. Do you have an html page that you can send me? Thanks.

If not, can you try replacing `await emulateMedia('print')` with `await new Promise(x => setTimeout(x, 1000))` to make sure we aren't dealing with a race?

**Comment by MaximeMaillet** [comment]
Same error.

This is page that I want print : http://www.twineeds.com/freelance/freelance-4-4
This site is in React.JS

When I want print this page (Chrome > cmd+P), I have this error.
When I put my rendering engine to print (with chrome > emulate css media) and I print > I have no errors.

I use Chrome 64 on my PC and Chrome 66 with NodeJS

**Comment by ciarans** [comment]
Im also having this problem; page-break-inside is not supported by webkit browsers.

**Comment by ciarans** [comment]
I managed to fix this with putting all the information in tables rows - Not ideal but it works.

**Comment by ctwoodwa** [comment]
I'm also having this issue where I cannot insert a page break in the generated PDF.
 a tag with style or class applying  "page-break-after: always" does not actually create the page break on the pdf.

**Comment by Jmille65** [comment]
I think this might have been fixed- I can't repro it with Puppeteer v1.8 on CentOS 7. Although unfortunately the bug is the behaviour that I need.

**Comment by MaximeMaillet** [comment]
I tested with puppeteer 1.8 and this bug is fixed.

**Comment by Maoravitan** [comment]
I have  Puppeteer v1.13.0 and not working 👎 , it seams like puppeteer cannot read the @media print

this is my code:

```
router.post("/", async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    let browser:any;
    try {
        console.log("get inside pdf services endpoint");
        const requestData: PDFCreationAttributes  = req.body;  
        browser = await launch({args: ['--no-sandbox'], ignoreHTTPSErrors: true});
        const page = await browser.newPage();
        await page.emulateMedia('print');
        console.log("url to pdf : " + requestData.urlWithToken);
        await page.goto( requestData.urlWithToken);
        await page.waitForSelector('#capturePreviewPage', {timeout: 70000});
        console.log("found id: #capturePreviewPage");
        const pdfFile = await page.pdf({format: 'A4', printBackground: true,displayHeaderFooter: true});    
        await browser.close();
        res.setHeader('Content-Type', 'application/pdf');
        res.send(pdfFile); 
    } catch (error) {
        console.log(error)
        if(browser){
            await browser.close();
        }
        next(error);
    }
});

```
```
this is the css:
@media print {
 .newPage {
    page-break-after: always;
    position: relative;
    -webkit-region-break-inside: avoid;
  }
}

```
any help??
