### ISSUE TITLE
Chrome Android: [page|browser].close() causes crashes

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#2067]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version: Mac OSX
* Node.js version: 9.5.0

**What steps will reproduce the problem?**

device_test.js:

```js
const request = require('request');
const util = require('util');
const puppeteer = require('puppeteer');

const PORT =  process.env.PORT || 9222;

(async() => {
  const resp = await util.promisify(request)(`http://localhost:${PORT}/json/version`);
  const {webSocketDebuggerUrl} = JSON.parse(resp.body);
  const browser = await puppeteer.connect({browserWSEndpoint: webSocketDebuggerUrl});

  const page = await browser.newPage();
  await page.goto('https://example.com');

  console.log(await browser.version());
  console.log(await page.title());

  await page.addStyleTag({content: '* {color: red;}'});

  try {
    // await page.close(); // causes page crash
    // await browser.close(); // causes exception 
  } catch (err) {
    console.error(err);
  }

  // process.exit(0); // only way to exit script.

})();
```

1. Use the task switcher to kill all instances of Chrome running on the device
3. Run `adb forward tcp:9222 localabstract:chrome_devtools_remote`
4. Run `node device_test.js`

**What is the expected result?**

Calling `page.close()` or `browser.close()` works on Chrome Andorid.

**What happens instead?**

Calling `browser.close()` causes an exception:

```
Chrome/66.0.3348.3
Example Domain
{ Error: Protocol error (Browser.close): 'Browser.close' wasn't found undefined
    at Promise (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Connection.js:86:56)
    at new Promise (<anonymous>)
    at Connection.send (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/C
onnection.js:85:12)
    at Browser.create (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/La
uncher.js:209:71)    at Browser.close (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Bro
wser.js:147:31)    at /Users/ericbidelman/projects/puppeteer/puppeteer-examples/device_testing.js:25:19    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)  message: 'Protocol error (Browser.close): \'Browser.close\' wasn\'t found undefined' }
```

Calling `page.close()` causes a page crash:

```
ericbidelman-macbookpro:puppeteer-examples ericbidelman$ node device_testing.jsChrome/66.0.3348.3
Example Domain
(node:15592) UnhandledPromiseRejectionWarning: Error: Page crashed!    at Page._onTargetCrashed (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer
/lib/Page.js:116:24)    at CDPSession.Page.client.on.event (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules
/puppeteer/lib/Page.js:104:56)    at CDPSession.emit (events.js:160:13)
    at CDPSession._onMessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Connection.js:215:12)
    at Connection._onMessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Connection.js:117:19)    at WebSocket.emit (events.js:160:13)
    at Receiver._receiver.onmessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/Rec
eiver.js:389:14)
    at Receiver.getData (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/Receive
r.js:330:12)
    at Receiver.startLoop (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/Receiver.js:165:16)
(node:15592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
We don't have a good story for testing on android. This's not a top priority for us.

**Comment by developit** [comment]
This crash doesn't seem to happen when using Puppeteer 1.2 + Canary (69) on Android.

**Comment by mu3** [comment]
Excuse me, how do you use Puppeteer on Android?

**Comment by wuyeguangming** [comment]
Excuse me, how do you use Puppeteer on Android? +1

**Comment by beshoo** [comment]
@developit how can we install android chromium with puppeteer in order to run headless android service?

**Comment by saikrishna321** [comment]
@beshoo Similar project using CRI - https://github.com/saikrishna321/taiko-android

You need to open chrome on android and port forward tcp to the device and the pass the host and port to puppeteer to launch

**Comment by beshoo** [comment]
@saikrishna321 and how can we call that a headless?

**Comment by saikrishna321** [comment]
U can't call it headless, it will always run head full in the android device.

**Comment by AlloryDante** [comment]
Hello, I found a way to run pupeteer in Android, but it's a bit tricky....

Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.

Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.

**Comment by x88x** [comment]
> Hello, I found a way to run pupeteer in Android, but it's a bit tricky....
> 
> Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.
> 
> Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.



> Hello, I found a way to run pupeteer in Android, but it's a bit tricky....
> 
> Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.
> 
> Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.

I succeeded

**Comment by theyough** [comment]
@x88x Could you give us more details ?
Thanks

**Comment by xeoshow** [comment]
> Hello, I found a way to run pupeteer in Android, but it's a bit tricky....
> 
> Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.
> 
> Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.

Hi @AlloryDante ,

Just would like to know : How to handle the  nodejs env ? You also installed the nodejs in "AnLinux"? Thanks.
