### ISSUE TITLE
unexpected request header when net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Janpot** [puppeteer/puppeteer#2068]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version: macOS 10.13.3
* URLs (if applicable):
* Node.js version: v9.5.0

**What steps will reproduce the problem?**

Run:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  try {
    const page = await browser.newPage();
    page.on('request', r => console.log(
      r.url(),
      r.headers()['x-devtools-emulate-network-conditions-client-id']
    ));
    await page.goto('http://foo.bar/');
    // await page.goto('http://example.com/');
  } catch (err) {
    console.log(err);
  } finally {
    await browser.close();
  }
})();
```

**What is the expected result?**

It prints
```
http://foo.bar/ undefined
```

**What happens instead?**

It prints

```
http://foo.bar/ 65A2864E19BC77D82EBC4B7F03E04F4F
```

Doing this with a url that resolves works as expected:

```
http://example.com/ undefined
```

**Comment by JoelEinbinder** [comment]
Seems like a bug. Thanks! @caseq can you take a look? I can reproduce in headful and headless.

**Comment by Janpot** [comment]
It's also on the raw protocol, so I assume it's chrome leaking some internals in the events.

**Comment by aslushnikov** [comment]
Filed upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=814568

**Comment by aamorozov** [comment]
+1, having the same issue in both modes when crawling a large number of pages(same env as author's).

**Comment by aslushnikov** [comment]
This works fine for me on tip-of-tree (v1.7.0-post: https://github.com/GoogleChrome/puppeteer/commit/e07567f26838faf08fff004466ad5153ceb55581)
