### ISSUE TITLE
Feature request - auto clip/crop

### ISSUE THREAD

**Issue by penx** [puppeteer/puppeteer#2069]
It would be great if you could call:

```
page.screenshot({clip: "auto"})
```

And have puppeteer remove any excess white space (or transparent space if called with `omitBackground: true`).

This would be useful when using puppeteer to generate images of components within a component library.

**Comment by penx** [comment]
This could potentially be done using `image.autocrop` from https://github.com/oliver-moran/jimp

**Comment by ebidel** [comment]
I'm not sure this fits without our guidelines for taking on new deps:
https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md#adding-new-dependencies

**Comment by JoelEinbinder** [comment]
I don't think this is within the scope of Puppeteer. As you mention, there are existing libraries for auto cropping so embedding one in Puppeteer doesn't provide any big wins.

**Comment by jorrit200** [comment]
I want to add the following comment to help people who landed on this issue, by googling for a solution, like me.

# Solution
ElementHandles do have bounding boxes! so we can do the following:

```csharp
/// <summary>
/// Convert html into an img 
/// </summary>
public async Task<Stream> GenerateImage(string html)
{
    await page.SetContentAsync(await HtmlWriter.Tagged(html, "div", [
        new("id", "content"),
        new("style", "padding: 1rem;"),
    ])); // Wrapping whatever html we got into a div, so we are sure we can select it all.
    
    var contentElement = await page.QuerySelectorAsync("#content")!; // Selecting the content as an ElementHandle
    var boundingBox = await contentElement!.BoundingBoxAsync()!; // This ElementHandle gives us a bounding box
    _defaultScreenshotOptions.Clip = new Clip { Width = boundingBox.Width , Height = boundingBox.Height }; // Clip the frame the bounding-box of the content element
    
    return await page.ScreenshotStreamAsync(_defaultScreenshotOptions);
}
```
forgive me for posting C# here, I took this straight from my own project. It's the concept that matters, and the API is very similar regardless.

Here I take a preloaded page and set its content to whatever was passed to the method, but wrapped in a div with some padding.
I then select that same div to extract its bounding box.
Finally I use that bounding box to clip the screenshot.

Some things to take into account:
- If the content is larger than the page itself, this will fail. (workaround might be just a really big page, or setting the page based on the content)
- This solution does not take scaling into account (I haven't used scaling anywhere, so I'm not even sure how that would affect things)

# Scope and such things
I think this is a fairly elegant solution, and should probably have been the original answer. (Although I'm sure its implementation could be better)
Puppeteer has the context of the spacing and sizing of the elements on the page. Surely using this is more efficient than scanning for the content on some rasterized data.
So I think defining where content starts and ends is very much within the scope of the project, as it is already done.
