### ISSUE TITLE
--disable-infobars arg not working

### ISSUE THREAD

**Issue by natew** [puppeteer/puppeteer#2070]
### Steps to reproduce

* Puppeteer version: 1.1.0
* Platform / OS version: High Sierra 10.13.2
* Node.js version: 9.2

**What steps will reproduce the problem?**

```
await puppeteer.launch({
      headless: false,
      args: ['--disable-infobars', `--window-size=${800},${680}`],
    })
```

`window-size` works as expected, but Chromium still shows the "this browser is being controlled by automated software" infobar at the top.

**What is the expected result?**

Not showing the infobar.

**What happens instead?**

Shows infobar.

**Comment by ebidel** [comment]
Dupe of https://github.com/GoogleChrome/puppeteer/issues/1765. They removed the flag.

**Comment by jacobjithin** [comment]
Is there way to disable the info-bars now since the command "--disable-infobars"  has been removed. I Need to disable the info bar when Chrome is launched using selenium

**Comment by haydenren** [comment]
I have the same question.

**Comment by jeffhall-wk** [comment]
I have the same question, also

**Comment by oligee80** [comment]
You can try these two options:
`     options.setExperimentalOption("useAutomationExtension", false);
        options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));`

**Comment by jacobjithin** [comment]
I used the below code
"var options = new ChromeOptions();
chromeOpts.setExperimentalOption("useAutomationExtension", false);"

But it is throwing below error
" 'ChromeOptions' does not contain a definition for 'setExperimentalOption'"

**Comment by oligee80** [comment]
Looks like you are using the javascript version of selenium, the code is for the java version. I don't knwo how to enable the experimental options for chromedriver in javascript.

**Comment by jacobjithin** [comment]
Selenium at my organization is coded in C#

**Comment by bezeklik** [comment]
I could hide infobar by using the `--no-startup-window` option as below.

```javascript
const puppeteer = require('puppeteer');
(async()=>{
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--no-startup-window']
  });
  const page = await browser.newPage();
  await page.goto('https://github.com/');
})();
```

**Comment by natew** [comment]
@bezeklik with the new version this no longer works well. It prevents Chromium for actually showing until you click it in the dock.

I'm sure there's some way we could "focus" it using maybe AppleScript, but that is pretty hacky.

**Comment by natew** [comment]
Actually, looks like `--disable-infobars` works again now.

**Comment by jacobjithin** [comment]
Yeah it is working now

**Comment by ThibaultJanBeyer** [comment]
no it does not, at least for me

**Comment by derappelt** [comment]
Any updates? I really need to hide the bar for an automated infoscreen.

**Comment by rikur** [comment]
This problem just came back

**Comment by packjiwuan** [comment]
Yes I'm still seeing "chrome is being controlled by automated software" even I am using "--disable-infobars". Happening in latest chrome ver 76

Solution works for me: --> options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));  thanks @oligee80

**Comment by flotwig** [comment]
@packjiwuan Chrome team removed `--disable-infobars` in Chrome 76: https://support.google.com/chrome/a/answer/7679408?hl=en

**Comment by DimensionBots** [comment]
Because of the latest Chrome update (v76), Chrome now also shows a 'Disable developer mode extensions' popup if you add any extensions through code. Is there any new way to hide this popup?

**Comment by affinage** [comment]
if anyone is needed, here's workaround: 

- remove `--disable-infobars` as now it does nothing 
- add `add_experimental_option('useAutomationExtension', False)`
- add `add_experimental_option('excludeSwitches', ['enable-automation'])`

p.s. it's a python syntax so adapt code for your needs.

**Comment by flotwig** [comment]
Note that removing `enable-automation` could have an undesirable impact on your automation:

https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#--enable-automation

> 
> ### `--enable-automation`
> Disable a few things considered not appropriate for automation. ([Original design doc](https://docs.google.com/a/google.com/document/d/1JYj9K61UyxIYavR8_HATYIglR9T_rDwAtLLsD3fbDQg/preview)) [codesearch](https://cs.chromium.org/search/?q=kEnableAutomation&type=cs)
> 
> * disables the password saving UI (which covers the usecase of the [removed](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1015) `--disable-save-password-bubble` flag)
> * disables infobar animations
> * disables dev mode extension bubbles (?), and doesn't show some other info bars
> * disables auto-reloading on network errors ([source](https://cs.chromium.org/chromium/src/chrome/renderer/net/net_error_helper_core.cc?l=917&rcl=6eaf0af71262eb876764c6237ee2fe021a3e7a18))
> * means the default browser check prompt isn't shown
> * avoids showing these 3 infobars: ShowBadFlagsPrompt, GoogleApiKeysInfoBarDelegate, ObsoleteSystemInfoBarDelegate
 
I really wish there was a workaround for this without using policy.

**Comment by MayurGujjul** [comment]
for java, following workaround is working for me...

options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
options.setExperimentalOption("useAutomationExtension", false);

any better code, pls do suggest!

**Comment by cciola** [comment]
Could not use `options.setExperimentalOption("useAutomationExtension", false);` syntax on C#, it  sets an error at `setExperimentalOption`.

Tried to use this instead: `options.AddAdditionalCapability("useAutomationExtension", false);`, but did not work.

EDIT: this solution worked for me: [https://stackoverflow.com/questions/57298901/unable-to-hide-chrome-is-being-controlled-by-automated-software-infobar-within](url)

**Comment by jacobjithin** [comment]
@CarolCiola : I am facing the same issue as you. And i need a workaround in C#. The link you mentioned in your post is unfortunately not accessible. So do you mind letting me know the solution

**Comment by cciola** [comment]
@jacobjithin the link is correct, but here is the solution:

`ChromeOptions options = new ChromeOptions();`
`options.AddArguments("--start-maximized");`
`//options.AddArguments("--disable-infobar"); //not working anymore`

Solution to Chrome version 76:
`options.AddExcludedArgument("enable-automation");`
`options.AddAdditionalCapability("useAutomationExtension", false);`

Had to disable browser's save password option too:
`options.AddUserProfilePreference("credentials_enable_service", false);`
`options.AddUserProfilePreference("profile.password_manager_enabled", false);`

**Comment by jacobjithin** [comment]
@CarolCiola : Thanks !
I tried the below two lines and the save browser password option was coming up.
options.AddExcludedArgument("enable-automation");
options.AddAdditionalCapability("useAutomationExtension", false);

And now your line of code of disable the save password "options.AddUserProfilePreference("credentials_enable_service", false);" worked for it. I believe only that one line is needed
Thank you again

**Comment by yadav26490** [comment]
For Java I did this:
disable password pop up:
HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
chromePrefs.put("credentials_enable_service", false);

ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("prefs", chromePrefs);

for infobars:
options.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
options.setExperimentalOption("useAutomationExtension", false);

**Comment by rikur** [comment]
Any solution for JavaScript?

**Comment by debaosuidecl** [comment]
Yes please, is there any javascript solution?

**Comment by jperl** [comment]
I don't know about puppeteer but for webdriverio this works for me

```
const chromeOptions = {
  // disable "Chrome is being controlled by automated software"
  // https://github.com/GoogleChrome/puppeteer/issues/2070#issuecomment-521313694
  excludeSwitches: ["enable-automation"],
  // from https://github.com/Codeception/CodeceptJS/issues/563#issuecomment-310688797
  prefs: { credentials_enable_service: false },
  useAutomationExtension: false
};

const browser = await remote({
  capabilities: {
    browserName: "chrome",
    "goog:chromeOptions": chromeOptions,
  },
  logLevel: "warn",
  port: CONFIG.seleniumPort
});
```

**Comment by debaosuidecl** [comment]
Adding the following to the options argument in puppeteer.launch solved the issue for me
`            ignoreDefaultArgs: ['--enable-automation'],
`

such as:
` const browser = await puppeteer.launch({
            headless: false,
            slowMo: 120,
            ignoreDefaultArgs: ['--enable-automation'],
            args: [
              `--proxy-server=${newproxy}`,
              `--no-sandbox`,
              '--disable-setuid-sandbox'
            ],
            slowMo: 20
          });`

apparently the enable-automation flag is a default argument that we have to ignore.
that removes the infobars.

hope this helps

**Comment by debaosuidecl** [comment]
Adding the following to the options argument in puppeteer.launch solved the issue for me
ignoreDefaultArgs: ['--enable-automation'],

such as:
const browser = await puppeteer.launch({ headless: false, slowMo: 120, ignoreDefaultArgs: ['--enable-automation'], args: [ --no-sandbox, '--disable-setuid-sandbox' ], slowMo: 20 });

apparently the enable-automation flag is a default argument that we have to ignore.
that removes the infobars.

hope this helps

**Comment by d4niloArantes** [comment]
Solution for ChromeDriver tested with Selenium WebDriver 
https://help.applitools.com/hc/en-us/articles/360007189411--Chrome-is-being-controlled-by-automated-test-software-notification

**Comment by Maysjtu** [comment]
This works for me 
`await puppeteer.launch({
    headless: false,
    args: [
        '--app=https://www.google.com/'
    ]
})`

**Comment by ameerahm** [comment]
@Maysjtu 
Not only removes the automation message but get rids of the url bar too. Thanks!

**Comment by soyuka** [comment]
```
--suppress-message-center-popups Hides all Message Center notification popups (toasts). Used for testing. ↪
```

source: https://peter.sh/experiments/chromium-command-line-switches/

**Comment by hasibdev** [comment]
How can I remove Set as Default infobar?

**Comment by moltar** [comment]
`--suppress-message-center-popups` isn't hiding the "Chrome is being controlled by automated test software" message.

**Comment by kstewart83** [comment]
`--no-default-browser-check` is needed if you get the default browser notification

```.js
const browser = await puppeteer.launch({
    headless: false,
    devtools: true,
    args: ["--no-default-browser-check"],
    ignoreDefaultArgs: ['--enable-automation'],
  });
```

**Comment by uzair004** [comment]
> Adding the following to the options argument in puppeteer.launch solved the issue for me ` ignoreDefaultArgs: ['--enable-automation'],`
> 
> such as: `const browser = await puppeteer.launch({ headless: false, slowMo: 120, ignoreDefaultArgs: ['--enable-automation'], args: [`--proxy-server=${newproxy}`, `--no-sandbox`, '--disable-setuid-sandbox' ], slowMo: 20 });`
> 
> apparently the enable-automation flag is a default argument that we have to ignore. that removes the infobars.
> 
> hope this helps

apparently this isn't working for me, still can see `Chrome is being controlled by automated script` info headers.

**Comment by uzair004** [comment]
> 

should we replace the url by the site URL we want to scrape?
