### ISSUE TITLE
Timeout for the static resources will block the script.

### ISSUE THREAD

**Issue by CommanderXL** [puppeteer/puppeteer#2074]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: mac OS
* URLs (if applicable): https://www.baidu.com
* Node.js version: 8.0.0

**What steps will reproduce the problem?**

Sometimes the static resources like `js`,`img`,`css` loaded **timeout**.The script executed unnormally.

```javascript
const puppeteer = require('puppeteer')

;(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    devtools: true
  });
  const page = await browser.newPage()
  page.on('requestfailed', (http) => {
    console.log('http failed')
  })
  await page.goto('https://www.baidu.com');
  await new Promise(resolve => setTimeout(resolve, 10000))
  await page.evaluate(() => {
    console.log(123)
  })
})()
```

The homepage of `https://www.baidu.com` will load the img `https://www.baidu.com/img/bd_logo1.png`. I use charles set the breakpoints of this url and didn't make the response.After 30000ms, puppeteer will throw the error: `Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded`.And the script

```javascript
await page.evaluate(() => {
   console.log(123)
})
```

didn't execute.

Well, I can use `process.on` to catch the unhandled rejection of promise:

```javascript
process.on('unhandledReject', (err) => {
    // do something 
})
```

But the script `await page.evaluate()` didn't execute as well.

I try disable the timeout:

```javascript
await page.setDefaultNavigationTimeout(0)
```

But the script `await page.evaluate()` didn't execute as well.

**What is the expected result?**

Well, in this situation that the static resources loaded timeout.I think it should not block the script.

Besides, is there any event could catch the error? I read the doc, I find the `requestfailed` will emit the request timeout. But I found that it has no effects for the static resources timeout, it is used for the http response code 503/504.

Well, the `process.on('unhandledReject')` will catch the error. But the error msg was `Error: Navigation Timeout Exceeded: 30000ms exceeded`.The error message is not clear.I don't think the static resources load belong to navigation?If there is some clear error class for this suitation?

**What happens instead?**

The script was blocked. And the error message confused me.

**Comment by marijanlekic** [comment]
You can catch this promise rejection with catch clause:

```
const page = await browser.newPage().catch((err) => {
// In your case, now err will be "Navigation Timeout Exceeded: 30000ms exceeded"
});

// Now this will be executed...
await new Promise(resolve => setTimeout(resolve, 10000))
await page.evaluate(() => {
    console.log(123)
})
```

There are probably many reasons why you have this kind of rejection, it depends on page that you load, waitUntil settings...

When i open "https://www.baidu.com" you can see that page is not loaded after 20-30sec, visually it looks like that DOM is loaded, but there are some pending network requests...

**Comment by CommanderXL** [comment]
@marijanlekic Thanks for your answer.

Well, the navigation timeout err is not thrown in the method of `newPage`, so:

```javascript
const page = await browser.newPage().catch(err => console.log(err))
```

this doesn't work.

And the script: 

```javascript
await new Promise(resolve => setTimeout(resolve, 10000))
await page.evaluate(() => {
    console.log(123)
})
```

wouldn't be executed.

> When i open "https://www.baidu.com" you can see that page is not loaded after 20-30sec, visually it looks like that DOM is loaded, but there are some pending network requests...

Did you use charles to make the breakpoint? If so, this is the situation I met.If not, maybe the cdn node of this page is far from you.

Well, it's confused me that timeout for the static resources will block the script.

**Comment by marijanlekic** [comment]
@CommanderXL 

Sorry, my mistake. You should put catch clause on goto method:

`
  await page.goto('https://www.baidu.com').catch((err) => {
console.log(err);
});
`

 Also you can use:
` await page.waitFor(10000);`

instead of:
`
await new Promise(resolve => setTimeout(resolve, 10000))`

Yesterday when i tried to go to that page it was clear that its not going to be loaded in certain time (spinner next to page title, bottom progress indicated "Waiting for..."). But now, i have just tried your script and it worked for me. It took like ~10sec to load (to resolve goto promise) the page and i did not have timeout exception.

**Comment by Charlemagne3** [comment]
Thanks, @marijanlekic this helped me handle timeouts with puppeteer better.
