### ISSUE TITLE
page.url() does not have page's url

### ISSUE THREAD

**Issue by nnn406** [puppeteer/puppeteer#2075]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
1.1.0
* Platform / OS version:
osx
* URLs (if applicable):
see the code below
* Node.js version:
9.5.0

**What steps will reproduce the problem?**
run this code

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    // slowMo: 750,
  });

  const page = await browser.newPage();

  page.setDefaultNavigationTimeout(20000);
  await page.setViewport({ width: 1280, height: 720 });
  await page.bringToFront();

  await page.goto('https://www.google.de/maps/search/USA+Hotel/@26.7450301,-152.4643366,3z?hl=en');

  const privacyReminder = 'button.widget-consent-button-later, button.ripple-container';
  await page.waitForSelector(privacyReminder, { visible: true });
  await page.click(privacyReminder);

  page.click('div[data-result-index]');

  await page.waitForSelector('h1.section-hero-header-title', { visible: true });
  // just a timeout because waitForNavigation does not work at all :(
  await Promise.all([new Promise((resolve) => setTimeout(resolve, 2000))]);

  console.log(page.mainFrame().url());

  await browser.close();
})();
```

**What is the expected result?**
I would expect the URL what I see in the browser address bar, but not the original

**What happens instead?**
I see in terminal the starting(original) URL

**Comment by aslushnikov** [comment]
This is a dupe of #257: we don't instrument history API atm.

**Comment by nnn406** [comment]
But in my case, it's no a hash navigation and there is a network activity, also in the example above `waitForNavigation` does not work :( It's clear that the original URL what I'm trying to read is an SPA and not regular website, nevertheless, nowadays it's quite obvious to build an SPA instead of old-school websites. Do you have any plans to support it?

Thanks.

**Comment by aaronzolla** [comment]
@nnnikolay You helped me so much with your answer. Thank you.
