### ISSUE TITLE
Expose more info on JSHandle

### ISSUE THREAD

**Issue by felixfbecker** [puppeteer/puppeteer#2083]
When inspecting `JSHandle` instances with a debugger, I can see quite a lot of useful underscored properties, like the type of the object (e.g. `error`).
I would like to forward `console.log`'ed objects to the Node console, but `jsonValue()` is not sufficient for that - for example, it won't include the `message` property of Errors (because it's not enumerable), which is the most important one. It also throws on circular objects.

I would write a recursive function that uses `getProperties()`, but I don't see any way to get the type of the value to know to stop on primitives (strings, numbers, booleans) so the recursion doesn't go on forever.

I would also like to use the same objects if the objects have circular references so Node can print `[Circular]` for these properties.

**Comment by maximedupre** [comment]
I agree, this kind of error is not very helpful:

    ConsoleMessage {
        _type: 'error',
        _text: 'ERROR JSHandle@object',
        _args: [ JSHandle {
            _context: [ExecutionContext],
            _client: [CDPSession],
            _remoteObject: [Object],
            _disposed: false },
        JSHandle {
            _context: [ExecutionContext],
            _client: [CDPSession],
            _remoteObject: [Object],
            _disposed: false }]}

**Comment by aslushnikov** [comment]
@felixfbecker you still can write a stringifier on a browser side: you have all the types there, and it's easy to do the `[Circular]` abbreviation back there.

I also don't mind exposing JSHandle's type if there's a good reason to.

**Comment by felixfbecker** [comment]
@aslushnikov that doesn't sound like a good option - if I want to test an application that might throw errors or `console.log()` them, how would I intercept that? Monkey-patch `console.log()` before loading any scripts?

**Comment by aslushnikov** [comment]
@felixfbecker I mean the following:

```js
function describe(jsHandle) {
  return jsHandle.executionContext().evaluate(obj => {
    // serialize |obj| however you want
    return 'beautiful object of type ' + (typeof obj);
  }, jsHandle);
}

page.on('console', async msg => {
  const args = await Promise.all(msg.args().map(arg => describe(arg)));
  console.log(msg.text(), ...args);
});

**Comment by bryanlarsen** [comment]
Propogating this info to https://github.com/GoogleChrome/puppeteer#debugging-tips would probably be super helpful.

**Comment by aslushnikov** [comment]
Closing this in favor of https://github.com/GoogleChrome/puppeteer/issues/2083#issuecomment-380287424.
