### ISSUE TITLE
"Mouse up" is performed where my cursor is

### ISSUE THREAD

**Issue by JBustin** [puppeteer/puppeteer#2085]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version: macos high sierra
* URLs (if applicable): not available
* Node.js version: 8.9.1

**What steps will reproduce the problem?**

Test
```
      const element = await page.$('div[video="video"]');
      const dropZone = await page.$('#content-editor');
      await dnd(page, element, dropZone, (elementBox, dropZoneBox) => ({
        element: {
          x: elementBox.x + elementBox.width / 2,
          y: elementBox.y + elementBox.height / 2,
        },
        dropZone: {
          x: dropZoneBox.x + 20,
          y: dropZoneBox.y + 20,
        },
      }));
      await page.waitForSelector('#content-editor article-media-node-video');
```

dnd function
```
module.exports.dnd = async (page, element, dropZone, processCoordinates) => {
  const elementBox = await element.boundingBox();
  const dropZoneBox = await dropZone.boundingBox();

  const coord = _.isFunction(processCoordinates)
    ? processCoordinates(elementBox, dropZoneBox)
    : {
        element: {
          x: elementBox.x + elementBox.width / 2,
          y: elementBox.y + elementBox.height / 2,
        },
        dropZone: {
          x: dropZoneBox.x + dropZoneBox.width / 2,
          y: dropZoneBox.y + dropZoneBox.height / 2,
        },
      };

  await page.mouse.move(coord.element.x, coord.element.y);
  await page.mouse.down();

  await page.mouse.move(coord.dropZone.x, coord.dropZone.y);
  await page.mouse.up();
};
```

1. I launch my test in "not headless" mode
2. Mouse down on a draggable div
3. Mouse move
4. Mouse up : this action is performed where my cursor is and not at the coordinates setted in parameters

**What is the expected result?**

An empty div "La vidéo sur Le Monde.fr" is loaded (selector: `div[video="video"]`)
I try to drag it to the div "My content" (selector: `#content-editor`).

![puppeteer](https://user-images.githubusercontent.com/2632709/36588874-c4677bf4-1889-11e8-900f-86ac179d6731.gif)

**What happens instead?**

The element is dropped where my cursor is...

**Comment by pferdone** [comment]
We have the same problem. We even tried the solution suggested by @aslushnikov in https://github.com/GoogleChrome/puppeteer/issues/423 but it doesn't work that way either.

**Comment by davidsun2016** [comment]
can we move up the priority? DnD is critical function to UI

**Comment by CyrilQuandalle** [comment]
Hi,
I am having the same issue.
Is there any news regarding this problem ?  Or any workaround ? @JoelEinbinder ?

**Comment by alexeymatveevp** [comment]
same here, cannot simulate mouse dnd, trying with delays, with slow-mo, with multiple mouse down / up in small time-periods - nothing helps

**Comment by dnovakovic15** [comment]
@davidluckystar @CyrilQuandalle @davidsun2016 @pferdone @JBustin 
If you are having issues dragging and dropping do the following:

await page.mouse.down();
await sleep(3000);
await page.mouse.move(0, 0);
await page.mouse.move(100, 100);
await page.mouse.down();

Basically, call page.mouse.down() twice. It fixed my issue. 

Edit: Won't work without the delay.

function sleep(duration) {
	return new Promise(resolve => {
		setTimeout(resolve, duration);
	});
}

**Comment by RichieAHB** [comment]
Also having this issue, not sure whether this is macOS specific but when I've Googled this it's seemed to largely been macOS as the OS. Have tried various workarounds but none seem to have worked.

**Comment by nicholaswmin** [comment]
+1 Same here

**Comment by Ratna33** [comment]
Same here.
Facing this dnd issue, tried using multiple mouse down/up , added delays, slo-Mo. Doesn't help.

**Comment by acittar** [comment]
Guys I had the same problem but finally I came to a solution! I was trying to drag a slider-button and it wasn't working because it was out of my viewport. Solved just scrolling the page before moving the mouse, like this:

		page.evaluate(_ => {
		  window.scrollBy(0, 400);
		});

		await page.mouse.move(startSliderWidth, startSliderHeight);
		const new_width = startSliderWidth + 80;
		await page.mouse.down();
		await page.mouse.move(new_width, startSliderHeight);			  
		await page.mouse.up(); 

Hope this helps!
Cheers

**Comment by jennyzzz** [comment]
same here.

**Comment by Bhav1907** [comment]
I am also facing issue with mouse up. Any solution to this ?

**Comment by Bhav1907** [comment]
Any solution on Mouse up . I cant perform dr
![backstop Quer on drag drop](https://user-images.githubusercontent.com/47148494/55857899-f85fd300-5b33-11e9-82bf-d2c3e75b1f56.gif)
ag and drop .

**Comment by nicholaswmin** [comment]
@Bhav1907 Please avoid commenting more than once. Everyone on this thread gets notifications for this.

**Comment by Bhav1907** [comment]
@dnovakovic15  Do you have any solution to this? Will really appreciate .

**Comment by ajaskolski** [comment]
@JoelEinbinder any plans for fixin' this issue? its top prio for many of us

**Comment by AnandGanesh-Reflektion** [comment]
This is critical for my e2e tests. Is this considered as top priority? When can we see the working solution for the same?

**Comment by a5g** [comment]
This is critical for my e2e tests. Is this considered as top priority? When can we see the working solution for the same?

**Comment by tomholub** [comment]
We're running into this too

**Comment by mvgiacomello** [comment]
Running into exact same issue. Both headless and non-headless I get the same behaviour where the mouse goes to the first position, press down and I can see it start moving (triggers my UI drag-and-drop functionality) but never moves to the second position as well as never release the button.
However... I can reproduce the described behaviour when running with the window where it releases wherever my pc mouse is.

Puppeteer version: `2.0.0`

```javascript
    console.log(`DnD x(${fromX}) y(${fromY}) to x(${toX}) y(${toY})`);
    // DnD x(712) y(308) to x(1552) y(115)
    await page.mouse.move(fromX, fromY);
    await page.mouse.down();
    await page.mouse.move(toX, toY);
    await page.mouse.up();
```

**Comment by FauzanAr** [comment]
Hi i have same problem using puppeteer 2.0.0, is there any references to fix this bug?

**Comment by wardnath** [comment]
Hey everyone, I found my issue was that simply performing mouse events was not sufficient. Instead I needed to trigger DragEvents https://developer.mozilla.org/en-US/docs/Web/API/DragEvent

for more info see my answer here: https://github.com/puppeteer/puppeteer/issues/1366#issuecomment-589828387

**Comment by SakisTsalk** [comment]
I have the same issue as well tried [https://puppeteer.github.io/puppeteer/docs/puppeteer.mouse.draganddrop](mouse.dragAndDrop()) as well but the same outcome as soon as it picks the item it uses the Mac's cursor.
