### ISSUE TITLE
Page.url() does not include path / query options

### ISSUE THREAD

**Issue by awshanks** [puppeteer/puppeteer#2086]
### Steps to reproduce

call page.url() for a website with a path returns the url without a path e.g. go to https://github.com/GoogleChrome/puppeteer/issues page.ulr() returns https://github.com/

**Tell us about your environment:**
* Puppeteer version: 1.0.0
* Platform / OS version: MAc
* URLs (if applicable):
* Node.js version: 8.9.4

**Comment by ebidel** [comment]
1.1.0 produces the correct url for me:

<img width="1184" alt="screen shot 2018-02-23 at 9 00 59 am" src="https://user-images.githubusercontent.com/238208/36606301-232e5a84-1878-11e8-95fa-4744cb41cf10.png">

Something else is going on in your setup

**Comment by awshanks** [comment]
Thank you.
