### ISSUE TITLE
Puppeteer not selecting checkboxes when more than 4 but no selector not found errors

### ISSUE THREAD

**Issue by voordev** [puppeteer/puppeteer#2087]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
current latest
* Platform / OS version:
osx
* URLs (if applicable):
none
* Node.js version:
8.0.5

**What steps will reproduce the problem?**
Selecting checkboxes in a page, 4 works, 5 do not.
I do not get error on invalid selector it just does not select more than 5.

**What is the expected result?**
Selecting all checkboxes

**What happens instead?**
It does not select all checkboxes when there are more than 5.

Is this a known issue with puppeteer somehow not being able to click all elements in a page when they are more than 4? Since I get no errors its very hard to debug. 

Is there some way to make sure a selector is clicked?

I select the checkboxes like so:
```
var selector_child  = "#child_checkbox_" + child;
console.log("child selector is: " + selector_child);
await page.click(selector_child);
```

**Comment by voordev** [comment]
I now added:

```
   var selector_child  = "#child_checkbox_" + child;
   console.log("child selector is: " + selector_child);

   page.waitForSelector(selector_child)
   wait page.click(selector_child);
   console.log('end single child');
```

**Comment by ebidel** [comment]
Please provide the url or a test page and your full script that repos the issue.

**Comment by voordev** [comment]
Hi @ebidel 

Its a closed intranet password/protected login I cannot share but I have provided you the full code we are using:

We have a html page with multiple checkboxes.
They have numbers like 11,12,13,21,22,23, etc 

Puppeteer is able to select a max of 8 checkboxes, with 9 checkboxes it fails with no error.
The selectors we print in terminal and are 1-1 match with those in the html page.
We are out of options on this perhaps its a bug or a bug in our code we would love to hear your feedback.

inside index.js:
```
const puppeteer         = require('./node_modules/puppeteer/lib/Puppeteer')
< generic stuff , log init etc > 

let generic_child       = require('./steps/child');

const browser = await puppeteer.launch({
        args: ['--no-sandbox','--disable-setuid-sandbox'],
        ignoreHTTPSErrors: true,
        headless: false
    });
    
    const page = await browser.newPage();
    page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7')

....
....
await page.waitFor(9000);
            await Promise.all(codesChildArray.map((value) => {
                var child = value;
                console.log('child code is: ' + child);
                return generic_child(browser, page, child);
            }));
            await page.waitFor(4000);
            await page.screenshot({ path: global.logRequestPath + '_selected_checkboxes.png', fullPage: true });
```

The /steps/child.js 
```
module.exports = async function generic_child(browser, page, child) {

   console.log('start single child');
   console.log('child: ' + child);
   await page.waitFor(1000);
   var selector_child  = "#child_checkbox_" + child;
   console.log("child selector is: " + selector_child);
   await page.click(selector_child);
   console.log('end single child');
}
```

Hope you expert advice us on why this happen, no error and valid selector feels like a chromium Bug or something timeout issue? ( we dont get any timeout issue ) out of options please help! much appreciated

**Comment by ebidel** [comment]
Thanks. Is there a reduced test case you can create?

 It's hard to say where the bug is unless we can reproduce the issue and can see the html page, etc. A reduced repro is the best way to get help fast :)

**Comment by voordev** [comment]
Hello Edibel,

I understand but its very hard to reproduce an example. 
Im now allowed to share the sources from the page im running puppeteer on.
If its a local issue with the code and not a bug in Puppeteer just a page with checkboxes 10 and trying to set them with the above code should result in the same outcome 

Its just a basic html in the end no catchy things like iframes.

**Comment by ebidel** [comment]
I understand. But if you can create that page and the pptr script that
shows the issue, post it here, it's helpful for maintainers.

**Comment by voordev** [comment]
@ebidel 
I cannot share it.. 
do you have in the meantime any suggestions what I could try to resolve this issue looking at my supplied code examples?  Is there a way to debug this? Im really lost on this issue and we need our puppeteer script like 3 weeks ago ;p anything I can look at ? I tested added more delays to the page but it doesn't matter. Since all the selectors are right I can only think of this is perhaps a bug.

**Comment by ebidel** [comment]
Here are two examples of a reduced test cases. Closing this issues, as both approaches work and check all the boxes:

```js
  const html = `<html>
  <input type="checkbox" id="child_checkbox_0">
  <input type="checkbox" id="child_checkbox_1">
  <input type="checkbox" id="child_checkbox_2">
  <input type="checkbox" id="child_checkbox_3">
  <input type="checkbox" id="child_checkbox_4">
  <input type="checkbox" id="child_checkbox_5">
  </html>`;
  await page.goto(`data:text/html,${html}`, {waitUntil: 'networkidle0'});

  for (let i = 0; i < 6; i++) {
    const selector_child  = `#child_checkbox_${i}`;
    console.log(`Clicking ${selector_child}`);
    const checkbox = await page.$(selector_child);
    await checkbox.click();
    const checked = await page.evaluate(checkbox => checkbox.checked, checkbox);
    console.log(`${selector_child} is checked`, checked);
  }
```

```js
  const html = `<html>
  <input type="checkbox" id="child_checkbox_0">
  <input type="checkbox" id="child_checkbox_1">
  <input type="checkbox" id="child_checkbox_2">
  <input type="checkbox" id="child_checkbox_3">
  <input type="checkbox" id="child_checkbox_4">
  <input type="checkbox" id="child_checkbox_5">
  </html>`;
  await page.goto(`data:text/html,${html}`, {waitUntil: 'networkidle0'});

  for (let i = 0; i < 6; i++) {
    const selector_child  = `#child_checkbox_${i}`;
    console.log(`Clicking ${selector_child}`);
    await page.click(selector_child);
    const checked = await page.evaluate(
        checkbox => checkbox.checked, await page.$(selector_child));
    console.log(`${selector_child} is checked`, checked);
  }
await browser.close();
```

**Comment by voordev** [comment]
@ebidel 
Your example seems to work, but does it work if you have say 10 checkboxes? I will test this.

I think I need to refactor the Promise out of my code,
I get a

```
#child_selector_99 is checked Promise { <pending> }
```

In the console using:
```
await Promise.all(codesChildArray.map((value) => {
                var child = value;
                console.log('GENERIC: child code is: ' + child);
                const selector_child  = "#child_selector_" + child;
                console.log(`Clicking ${selector_child}`);
                page.click(selector_child);
                const checked = page.evaluate(
                    checkbox => checkbox.checked, page.$(selector_child));
                console.log(`${selector_child} is checked`, checked);
            }));
```
So with promises at least it does still not select all checkboxes,
even with your page.evaluate method.

**Comment by voordev** [comment]
And refactoring it to a non promise don't let me use the 
```
await page.
``` 

Parent / Child is the same code block:

```
codesParentArray= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
            codesParentArray.forEach(function(value){
                const selector_parent  = "#selector_parent" + value;
                console.log('selector is:' + selector_parent)
                page.click(selector_parent);
                const checked = page.evaluate(
                    checkbox => checkbox.checked, page.$(selector_parent));
                console.log(`${selector_parent} is checked`, checked);
            });
```

Results int a:

```
#selector_parent_1 is checked Promise { <pending> }
until 
#selector_parent_11 is checked Promise { <pending> }
```

With nothing selected. 
Do you please have any thoughts?

**Comment by voordev** [comment]
@ebidel 
I managed to extract the sources from the private source and provide hereby an sample.js and sample.html to show that it still does *not* work with modifications so we can use an existing array instead of the integer increment you provided.

Could you please review and test this code and tell us why it still is not selecting all checkboxes? 
This definitely feels like a bug in puppeteer.  Your help in this regard is much appreciated. Thank you in advance.

**As you run the example you see it first seems to select all the correct checkboxes, then it deselects that last ones**

CODE:
https://gist.github.com/voordev/7f954d6d38c1332dac44f29adcf28bc1

**Comment by voordev** [comment]
Ok finally managed to resolve the issue with an extracted sample.
I try to implement it into existing codebase 
Thank you

**Comment by ebidel** [comment]
What was it?

**Comment by voordev** [comment]
I managed to combine several code blocks and documentation and some suggestions on your reply to a working solution.

But im implementing it in our existing codebase which still fails.
There must be something in the 'real environment' that causing issues.
I cannot sadly share a real world example, it does have a big javascript in the page maybe this is causing issues.

Mayor headache this
