### ISSUE TITLE
Ability to prevent header/footer on certain pages

### ISSUE THREAD

**Issue by mjschranz** [puppeteer/puppeteer#2089]
This is simply a feature request (or if it's available already, a question on how I can accomplish this).

I've gotten the header and footer templates working but I'd like to prevent them from displaying on a specific page (in this case, I have a cover page I use specifically for the PDF and having them there doesn't work with the design).

Is this possible or could it be added as a feature?

**Comment by aslushnikov** [comment]
@mjschranz you can issue `print` command multiple times with different page ranges, specifying the header/footer options differently for each range.

Would it work?

**Comment by mjschranz** [comment]
So you're suggesting running the `.pdf` call multiple times with different `pageRanges` values and then combine the buffer data of each one? I suppose that could work but I would need to give it a try.

On that note, how does one specify from "page 2 until the end". Is it just `2-`?

Thanks

EDIT:

Thusfar that idea works on paper but my script winds up hanging when trying to implement it in practice. The meat and potatoes.....

```javascript
generate(query) {
    return new Promise(async function(resolve, reject) {
      const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
      const page = await browser.newPage();
      const baseUrl = query.baseUrl;
      const url = query.portfolioUrl;
      const token = query.token;

      try {
        await page.goto(baseUrl, {waitUntil: 'domcontentloaded'});
      } catch(e) {
        reject('Failed on navigation to first page');
      }

      try {
        await page.evaluate((loginToken) => {
          localStorage.setItem('access_token', loginToken);
        }, token);
      } catch(e) {
        reject('Failed on localStorage step');
      }

      page.close();

      const finalPage = await browser.newPage();

      await finalPage.setExtraHTTPHeaders({
        'Authorization': `Bearer ${token}`
      });

      try {
        await finalPage.goto(url, {waitUntil: 'networkidle0'});
      } catch(e) {
        reject('Failed on navigation to second page');
      }

      const year = new Date().getFullYear();
      const date = new Date();

      const HEADER_TEMPLATE = `
        Actual content removed because work.
      `;

      const FOOTER_TEMPLATE = `
        Actual content removed because work.
      `;

      finalPage.pdf({
        format: 'A4',
        pageRanges: '1'
      }).then((bufferOne) => {

        finalPage.pdf({
          format: 'A4',
          printBackground: true,
          displayHeaderFooter: true,
          headerTemplate: HEADER_TEMPLATE,
          footerTemplate: FOOTER_TEMPLATE,
          margin: {
            top: '29mm',
            bottom: '20mm'
          },
          pageRanges: '2-'
        }).then((bufferTwo) => {
          let buffer = Buffer.concat([bufferOne, bufferTwo], bufferOne.length + bufferTwo.length);

          finalPage.evaluate(() => {
            localStorage.clear();
          }).then(() => {
            browser.close().then(() => {       
              resolve(buffer);
            });
          });
        }).catch((e) => {
          reject('Failed on generation of remaining pages');
        });
      }).catch((e) => {
        reject('Failed on PDF generation page one');
      });
    });
  }
```

**Comment by mjschranz** [comment]
Specifically the error I am having at this point with the following approach is that the second buffer seems to "overwrite" the first and I only have the results of the second.

**Comment by chrisjpatty** [comment]
I don't know this for sure, but I suspect you can't just combine PDFs by combining their buffers. I would assume that would just smush two pdf files together without properly encoding them into a single pdf. You might need to run some kind of tool that would combine them after they're generated.

**Comment by astefanutti** [comment]
Just in case that may help, I implemented PDF buffers merging from Puppeteer in https://github.com/astefanutti/decktape.

**Comment by chrisjpatty** [comment]
@astefanutti Oh nice! Where in your code might I find your specific implementation?

**Comment by astefanutti** [comment]
@chrisjpatty main loop is here: https://github.com/astefanutti/decktape/blob/1ee6449885daacc2a8167d7bb747e7c79efc9649/decktape.js#L298-L307.

It factorises duplicated images and consolidate font definitions, hence the complexity.

**Comment by pragyandas** [comment]
```
const firstPage = await page.pdf({
        format: 'A4',
        pageRanges: '1',
      });
      const restPages = await page.pdf({
        format: 'A4',
        headerTemplate: '<p></p>',
        footerTemplate:
          '<div class="footer" style="font-size: 10px;color: #000; margin: 10px auto;clear:both; position: relative;"><span class="pageNumber"></span></div>',
        displayHeaderFooter: true,
        pageRanges: '2-',
        margin: {
          bottom: '100px',
        },
      });
      const totalLength = firstPage.length + restPages.length;
      const result = Buffer.concat([firstPage, restPages], totalLength);
```

This works for me without any error but it chops off the 1st page. The generated PDF starts from page 2. 
Any pointers appreciated.

**Comment by Janpot** [comment]
@pragyandas You can't just append two binary blobs like this to concatenate pdfs. The resulting blob is not in the right format. You'd rather want to parse them first and concatenate the pages in a new file e.g. with [`hummus.js`](https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#basic-page-appending). Or use [a library](https://www.npmjs.com/package/pdf-merge) that does this for you if you don't mind writing to disk.

**Comment by mjschranz** [comment]
Yes as discovered we can't unfortunately. Libraries like the above mentioned do help. I wound up using `pdf-merge` but it would still be nice to have this feature baked in if possible.

**Comment by aslushnikov** [comment]
@mjschranz There's a technical possibility to evaluate js inside `headerTemplate` and `footerTemplate`. However, this requires engineering effort and spawns a lot of concerns that should be thought through.

Closing this since there's a workable solution for the issue. We can reconsider supporting script execution inside `headerTemplate` and `footerTemplate` if this is justified by other valid usecases and there's strong interest from the community.

**Comment by tradiff** [comment]
I hope this solution helps someone, even though it's super hacky.

I had a need to remove the header on page 1 (a cover letter).  The following puppeteer code solved my problem.  It adds a style tag which collapses the margin-top on the first page (effectively hiding the margin).  It then adds a margin-top to the body, to put a visible margin back into place.

```
await page.addStyleTag({
    content: "@page:first {margin-top: 0;} body {margin-top: 1cm;}"
});
```

That being said, I do think puppeteer should add the ability to execute javascript to manipulate header and footer templates.  There are a lot of use cases for this (alternating pages for binders would be another example).

**Comment by mjschranz** [comment]
I wound up using the `evaluate` method to execute JavaScript that would
toggle display on the pages/sections of my PDF.

**Comment by tradiff** [comment]
@mjschranz I've been trying to replicate your solution, and I'm having trouble manipulating the header with javascript.  Can you provide further details?

**Comment by mjschranz** [comment]
@TravisTX I basically would run code like the following to hide/show various HTML of the page I was making a PDF out of. For our use case, we explicitly always broke for specific sections/areas which made it easier for us.

```javascript
        await finalPage.evaluate(() => {
          document.querySelectorAll('.pdf-body').forEach((elem) => {
            elem.style.display = 'none';
          });
          document.getElementById('summary-block').style.display = 'none';
          document.getElementById('report-cover').style.display = 'block';
          document.getElementById('d-page').style.display = 'none';
        });
```

**Comment by aslushnikov** [comment]
For the reference: there's a designated issue about running js in `footerTemplate` and `headerTemplate`: #2167.

**Comment by Narigo** [comment]
I tried @TravisTX workaround which works okay in the sense of hiding the header on the first page. But having a second and third page, their bottom(!) margin *may* run into a `footerTemplate`. 😞 Looks like Chrome PDF export does not interpret the `margin-bottom` for other pages anymore after using the hack...

**Comment by ghost** [comment]
@Narigo  That's right, I'm having the same issue.

**Comment by SlashBin** [comment]
@Narigo @gostavee same... did either of you ever find a solution for that workaround? I can get the first page to work fine, but the footer doesn't appear on subsequent pages (other than the last page given that the content doesn't run 100% of the last page)

**Comment by Narigo** [comment]
Sorry @SlashBin I don't think I did find a proper workaround for that issue. I could come up with a different solution to my initial problem. (That means, I did not have to use multiple pages / templates at all, so I did not need to investigate any further...)

**Comment by SlashBin** [comment]
Thanks @Narigo for the followup. I'm actually looking into just generating two PDFs and merging. So far seems viable:
Just stumbled across this: https://stackoverflow.com/questions/55470714/trying-to-hide-first-footer-header-on-pdf-generated-with-puppeteer

**Comment by saurabh147sharma** [comment]
@pragyandas @mjschranz 
I'm using the following solution:
`await page.pdf({ format: 'A3', printBackground: true, pageRanges: '2-' })`
I'm getting following error: Protocol error (Page.printToPDF): Page range syntax error.
In my case, I needed to show the header and footer on the first page only not on the others.
I was able to create the first-page buffer successfully 
The above problem has occurred because there was only 1 page. Now problem is that how can I determine how many pages are there at runtime?

**Comment by matrunchyk** [comment]
@saurabh147sharma I had the same issue. I generate the first page, then use '2-' page ranges and then merge them into a single PDF using hummusJS. But when it's just one page, it was throwing the error you mentioned. I fixed that just using try/catch call.

**Comment by hanrok** [comment]
> I hope this solution helps someone, even though it's super hacky.
> 
> I had a need to remove the header on page 1 (a cover letter). The following puppeteer code solved my problem. It adds a style tag which collapses the margin-top on the first page (effectively hiding the margin). It then adds a margin-top to the body, to put a visible margin back into place.
> 
> ```
> await page.addStyleTag({
>     content: "@page:first {margin-top: 0;} body {margin-top: 1cm;}"
> });
> ```
> 
> That being said, I do think puppeteer should add the ability to execute javascript to manipulate header and footer templates. There are a lot of use cases for this (alternating pages for binders would be another example).

For any of you who tried this and had issues with the footer in other pages - try to add `margin-bottom`
```
await page.addStyleTag({
	content: "@page:first {margin-top: 0; margin-bottom: 150px;}"
});
```

**Comment by sriramgroot** [comment]
> I hope this solution helps someone, even though it's super hacky.
> 
> I had a need to remove the header on page 1 (a cover letter). The following puppeteer code solved my problem. It adds a style tag which collapses the margin-top on the first page (effectively hiding the margin). It then adds a margin-top to the body, to put a visible margin back into place.
> 
> ```
> await page.addStyleTag({
>     content: "@page:first {margin-top: 0;} body {margin-top: 1cm;}"
> });
> ```
> 
> That being said, I do think puppeteer should add the ability to execute javascript to manipulate header and footer templates. There are a lot of use cases for this (alternating pages for binders would be another example).

Hi @TravisTX
Thanks this solution solved my problem in generating PDF

**Comment by Venryx** [comment]
> `await page.addStyleTag({content: "@page:first {margin-top: 0; margin-bottom: 150px;}"});`

This worked for me. However, I had to change the `margin-bottom` to `100px`, otherwise it was creating too much padding at the bottom of all the pages (more than the original). So you may need to fiddle with the value to get the margins/paddings exactly as you want.

**Comment by andersonfurlantr** [comment]
> > I hope this solution helps someone, even though it's super hacky.
> > I had a need to remove the header on page 1 (a cover letter). The following puppeteer code solved my problem. It adds a style tag which collapses the margin-top on the first page (effectively hiding the margin). It then adds a margin-top to the body, to put a visible margin back into place.
> > ```
> > await page.addStyleTag({
> >     content: "@page:first {margin-top: 0;} body {margin-top: 1cm;}"
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That being said, I do think puppeteer should add the ability to execute javascript to manipulate header and footer templates. There are a lot of use cases for this (alternating pages for binders would be another example).
> 
> For any of you who tried this and had issues with the footer in other pages - try to add `margin-bottom`
> 
> ```
> await page.addStyleTag({
> 	content: "@page:first {margin-top: 0; margin-bottom: 150px;}"
> });
> ```

How to hide footer in the last page?

**Comment by sanderha** [comment]
To solve this problem we ended up generating multiple pdf's and merging them with https://www.npmjs.com/package/pdf-merger-js 

Would be nice to have some more options in Puppeteer though

**Comment by deepakageeru** [comment]
> ```
> const firstPage = await page.pdf({
>         format: 'A4',
>         pageRanges: '1',
>       });
>       const restPages = await page.pdf({
>         format: 'A4',
>         headerTemplate: '<p></p>',
>         footerTemplate:
>           '<div class="footer" style="font-size: 10px;color: #000; margin: 10px auto;clear:both; position: relative;"><span class="pageNumber"></span></div>',
>         displayHeaderFooter: true,
>         pageRanges: '2-',
>         margin: {
>           bottom: '100px',
>         },
>       });
>       const totalLength = firstPage.length + restPages.length;
>       const result = Buffer.concat([firstPage, restPages], totalLength);
> ```
> 
> This works for me without any error but it chops off the 1st page. The generated PDF starts from page 2. Any pointers appreciated.

I tried similar thing using C# package of puppeteer, merging two buffers may work for text files but not pdfs as the way pdfs are encoded is different.

**Comment by felegy-norbert** [comment]
So 4 years passed and no proper solution yet?

**Comment by Sambhav-Git** [comment]
This is really an important feature to have. When can we expect it?

**Comment by Sambhav-Git** [comment]
> @saurabh147sharma I had the same issue. I generate the first page, then use '2-' page ranges and then merge them into a single PDF using hummusJS. But when it's just one page, it was throwing the error you mentioned. I fixed that just using try/catch call.

Hi could you please provide a sample?

**Comment by spuy767** [comment]
Couldn't  the pageNumber injector be used to generate an element with a custom attribute like `data-page-number="1"` at which point we could just use something like:
```
.header:has([data-page-number="1"] {
    display: none;
}
```
Seems like it would be easy to implement and has about 0 chance of breaking anything.

**Comment by telmofcosta** [comment]
This really drives me nuts 🤯 

The pattern I see is that the page content must have always the same size. So, if we want to remove the header on the first page, the footer must include the removed header size. In other words, my css is:

```css
@page { margin-top: 1.5cm; margin-bottom: 1.5cm; }
@page:first { margin-top: 0.5cm; margin-bottom: 2.5cm; }
body { margin-top: 1.5cm; background-color: white; }
```
If the 0.5cm doesn't work for you, you can change it to 0 but then you need to update the bottom margin from 2.5cm to 3cm.

**Comment by wabiloo** [comment]
> @mjschranz you can issue `print` command multiple times with different page ranges, specifying the header/footer options differently for each range.
> 
> Would it work?

The problem with this approach is that if the first page contains links to other pages (for example a table of contents), all links break

**Comment by RahulDoshi099** [comment]
I wanted to remove footer on some pages like first and last how can i do it ? 
here is the code.
```

 async generatePdf(options) {
    const parsedHtml = await this.getOutputFromLiquidJs(options.htmlBaseContent, options.inputString);
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    await page.setContent(parsedHtml, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "letter",
      printBackground: true,
      displayHeaderFooter: true,
      footerTemplate: await generateFooterTemplate(),
    });
    return pdfBuffer;
  }
```

**Comment by Solovic2** [comment]
I had a problem like this -- removing only the header from the first page while keeping it on the other pages, without breaking the internal links. If we merge PDFs, the internal links get broken, so I solved it using `pdf-lib`.

After generating the full PDF using `page.pdf`, I load it with `pdf-lib`, go to the first page, generate a new first page without the header, and then replace the old one. This preserves the internal links.

This assumes that you have already calculated the `height` of the `header`.

```javascript
const fullPdfBytes = await page.pdf({
  format: "A4",
  printBackground: false,
  margin: margins,
  displayHeaderFooter: true,
  headerTemplate:  `YOUR HEADER HERE FOR ALL PAGES`,
  footerTemplate:  `YOUR FOOTER HERE FOR ALL PAGES`,
});

// Load it using pdf-lib
const pdfDoc = await PDFDocument.load(fullPdfBytes)
const pages = pdfDoc.getPages()

// Adjust the new margin for the first page as you want.
const adjustedTopMargin = 30` // should be marginTop - headerHeight

// Generate first page without header.
const firstPageOnlyBytes = await page.pdf({
  format: "A4",
  printBackground: false,
  margin: {
    ...margins,
    top: adjustedTopMargin,
  },
  displayHeaderFooter: true,
  headerTemplate: "<div></div>",
  footerTemplate:  `YOUR FOOTER HERE FOR ALL PAGES` ,
  pageRanges: "1",
});

// Replace the old first page, which contains the header, with the new first page that does not contain a header.
const firstPageDoc = await PDFDocument.load(firstPageOnlyBytes);
pdfDoc.removePage(0);
const [copiedPage] = await pdfDoc.copyPages(firstPageDoc, [0]);
pdfDoc.insertPage(0, copiedPage);
``` 
I think you can adjust what you want by making something like this e.g. remove footer, added on some pages and remove it from others.

**Comment by magedss** [comment]
> So 4 years passed and no proper solution yet?

Another 4 years passed and no proper solution yet.
