### ISSUE TITLE
Code coverage is not captured for service workers.

### ISSUE THREAD

**Issue by soldair** [puppeteer/puppeteer#2092]
### Steps to reproduce

enable js coverage
launch pupeteer on a page which activates a service worker
send request though to service worker
stop coverage and log

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version: linux
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

i have implemented this as a reduced test case here.
https://gist.github.com/soldair/b48a0022dbef999f241881f80d7575a9

you can run it with one command using the amazing npx from npm 5
```
npx git://gist.github.com/b48a0022dbef999f241881f80d7575a9
```

or clone it localy
```
git clone git@gist.github.com:b48a0022dbef999f241881f80d7575a9.git ./pupeteer-service-worker-coverage-test
cd pupeteer-service-worker-coverage-tes
npm install
node ./service-worker-test.js
```

**What is the expected result?**

it should have an entry for the service worker js loaded for this page
```
[
  {
    "url": "http://localhost:41109/",
    "ranges": [
      ...
    ],
    "text": "..."
  },
  {
    "url":"http://localhost:port/worker",
    ...
  }
]
```

**What happens instead?**
```
[
  {
    "url": "http://localhost:41109/",
    "ranges": [
      ...
    ],
    "text": "..."
  }
]
```

**Comment by aslushnikov** [comment]
Closing in favor of #2634.
