### ISSUE TITLE
TypeError: Cannot read property 'innerText' of null

### ISSUE THREAD

**Issue by RicoLiu** [puppeteer/puppeteer#2098]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: **1.0.0**
* Platform / OS version: **OS**
* URLs (if applicable):
* Node.js version: **8.9.1**

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.Error logs:
```javascript
(node:79739) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: TypeError: Cannot read property 'innerText' of null
    at <anonymous>:3:113
(node:79739) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
2.Here is code: [jsfiddle](https://jsfiddle.net/RicoLiu/0w9sd61t/4/)

**What is the expected result?**

How to fix this ?

**What happens instead?**

**Comment by RicoLiu** [comment]
<img width="1438" alt="wx20180224-145850 2x" src="https://user-images.githubusercontent.com/12722992/36626757-4b32bd9e-1973-11e8-951a-c1edeb223166.png">

I pasted code to chrome Dev tools console, and had this result.

**Comment by aslushnikov** [comment]
Looks like a problem with the code inside your `page.evaluate`: apparently, some of the elements you query for don't exist on a page.

**Comment by kapilkumar-github** [comment]
While I am querying in web developer console for a class, I am able to get results. However in puppeteer script its giving me empty HTML Collection array
<img width="405" alt="console" src="https://user-images.githubusercontent.com/50052501/68670818-d15afb00-0573-11ea-95f6-a0553665b237.PNG">
<img width="452" alt="script" src="https://user-images.githubusercontent.com/50052501/68670820-d1f39180-0573-11ea-8843-93773d695899.PNG">
