### ISSUE TITLE
Feature Request: Run puppeteer with particular user profile 

### ISSUE THREAD

**Issue by shmdhussain** [puppeteer/puppeteer#2099]
**Tell us about your environment:**

* Puppeteer version: Latest
* Platform / OS version: All
* URLs (if applicable):
* Node.js version: Latest

To run any test with particular user profile turned on like the below screenshot,

This is needed to test our website with ads and without ads, I have Adblock Plus Addon in my user profile, so that I could use and test it with my user profile on... I have other use cases also.

It would be helpful If we have this in puppeteer.

![chrome-profile-on](https://user-images.githubusercontent.com/4039657/36627327-a1a4183a-195a-11e8-9ac0-a1489dad84d9.png)

I tried with the following example, that is not opening automated chrome with particular user profile

![puppet-user-directory](https://user-images.githubusercontent.com/4039657/36627387-3e66b3a8-195b-11e8-9544-e6b49698c4aa.png)

**Comment by vsemozhetbyt** [comment]
Can you try `userDataDir` option for [`puppeteer.launch([options])`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions)?

**Comment by shmdhussain** [comment]
thanks @vsemozhetbyt  i tried as you mentioned, got the same results(not able to use automated chrome with my user profile turned on , so that I could test as real user with ad block plugin) see the screenshot of what I tried

![screen shot 2018-02-24 at 13 47 24](https://user-images.githubusercontent.com/4039657/36628885-1f1d91e4-1968-11e8-965e-bd5de06dacce.png)

**Comment by pablobb** [comment]
Try using full path, with drive letter, or fullpath on other OS.

In our case it looks something like this:
`config.rootDir   = path.resolve(__dirname);`
`config.chromeDir = config.rootDir + 'chromeFolder' `

**Comment by aslushnikov** [comment]
@shmdhussain you're passing path to the profile; try passing path to the userDataDir (the one that ends with `/Google/Chrome/`).

**Comment by shmdhussain** [comment]
Thanks @aslushnikov , Now it is working , I found that **userDatadir** is the **parent folder** of the **ProfilePath** which comes in chrome://version/ .

For example : /Users/Mohamed_Hussain_SH/Library/Application Support/Google/Chrome

**Comment by shmdhussain** [comment]
@aslushnikov Thanks it was working but now when i try to test any page with my profile open I am getting following error

![screen shot 2018-05-21 at 16 58 41](https://user-images.githubusercontent.com/4039657/40308332-f5f64796-5d16-11e8-9d3f-cccc7b673dbd.png)


Launch Code 

![screen shot 2018-05-21 at 17 03 20](https://user-images.githubusercontent.com/4039657/40308431-4f669fa6-5d17-11e8-866c-a4ab419241d6.png)

Could you know why this happens, when I run puppeteer , chrome is open with some other tabs, is this because of this? thanks for any help in advance.

**Comment by lincolnaleixo** [comment]
@aslushnikov this seems to use the default profile but how can I use a specific profile (for example profile 10) into puppeteer? thanks

**Comment by shinoshu** [comment]
```
(async () => {
  browser = await puppeteer.launch({
	headless: false,
	userDataDir: '/Users/shuma/Library/Application Support/Google/Chrome',
	args: ['--profile-directory=Profile\ 7']
  });
})();
```

**Comment by Cristy94** [comment]
Is this possible to do now? Select a specific user profile to open puppeteer with?

**Comment by saurabhkumar8112** [comment]
> [@aslushnikov](https://github.com/aslushnikov) this seems to use the default profile but how can I use a specific profile (for example profile 10) into puppeteer? thanks

You can use the flag "--profile-directory=profile" to launch with a specific profile
