### ISSUE TITLE
Feature Request: add support for `page.waitForSelectorAndEvaluate`

### ISSUE THREAD

**Issue by yanivefraim** [puppeteer/puppeteer#2101]
In many cases, we wait for an element to be loaded to screen, and right after that we use something like `page.$eval` to get hold of that element / do something with it.

I think that a method like `page.waitForSelectorAndEvaluate` (not sure about the name) might be very useful. Its signature might be similar to page.$eval:

#### page.waitForSelectorAndEvaluate(selector, pageFunction[, ...args])
- `selector` <[string]> A [selector] to query frame for
- `pageFunction` <[function]> Function to be evaluated in browser context
- `...args` <...[Serializable]|[JSHandle]> Arguments to pass to `pageFunction`
- returns: <[Promise]<[Serializable]>> Promise which resolves to the return value of `pageFunction`

**Comment by aslushnikov** [comment]
I didn't see many interest for the feature on the bugtracker, closing for now.
