### ISSUE TITLE
Puppeteer and Lighthouse for  page flow

### ISSUE THREAD

**Issue by rageshpayyan** [puppeteer/puppeteer#2105]
We are working to automate our product flow using Puppeteer and lighthouse. We would like to prepare performance report all the pages in our application.  
In our application we select product /product-details), add to cart (/add-to-cart), add customer details(/customer-details),  card-validation(/card-validation), checkout (/checkout).  We would like to validate individual page.  The challenge i am facing here in first page (product-details) i launch using Puppeteer and execute lighthouse and then  to get next page again call /add-cart page in Pupeteer and when i execute same page using lighthouse then i lost the data ( item selected in product-details page). then again next customer-detials page if fill using "page.type" and execute lighthouse it will not launch same page, it will start from product-details page. How this issue can be solved.

**Comment by rageshpayyan** [comment]
@ebidel , Can you pls help me. How to continue the same page filled using Puppeteer and execute the same page using lighthouse. Our product designed  yo cant go directly to add-cart page, you should follow some steps. I can reach add-cart page using Puppeteer, but when i execute lighthouse next it will consider as new page and start from page 1( /poduct-detials).

**Comment by ebidel** [comment]
We unfortunately do not have a great story there yet.  There are a couple of open bugs to discuss what  Puppeteer + Lighthouse would look like but we haven't made much progress on it. The challenge (as you've seen) is that Lighthouse reloads the page several times as it tests the page and there's no way to share state or pass a puppeteer-created page to LH.

https://github.com/GoogleChrome/lighthouse/issues/3837
https://github.com/GoogleChrome/lighthouse/issues/4403

Closing this in favor of those other issues.

**Comment by rageshpayyan** [comment]
@ebidel , Thanks for the help.  Is there is any other way to automate 'n' number of page flows using lighthouse without Puppeteer.

**Comment by ebidel** [comment]
Lighthouse isn't designed to do flows like this. You might be able to use another automation tool....

**Comment by rageshpayyan** [comment]
What you think this approach using puppeteer:https://michaljanaszek.com/blog/test-website-performance-with-puppeteer

**Comment by ebidel** [comment]
Looks like a lot of good stuff in there!

**Comment by vikramvi** [comment]
@rageshpayyan I checked blog but my understanding is that "lighthouse" is not used but just "puppeteer" which is not very clear to me.
