### ISSUE TITLE
ElementHandle.click should raise error if element behinds a modal layer

### ISSUE THREAD

**Issue by rustkt** [puppeteer/puppeteer#2107]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  v1.0.0
* Platform / OS version: OS X 10.3.3
* URLs (if applicable):
* Node.js version: v8.8.1

**What steps will reproduce the problem?**

`index.html`
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
    .modal {
      width: 320px;
      height: 240px;
      background-color: bisque;
      opacity: 0.5;
      position: fixed;
      top: 0;
      left: 0;
    }
  </style>
</head>

<body>
  <div class="modal"></div>
  <button onclick="alert('hello!');">click me</button>
</body>

</html>
```

`test.js`
```javascript
const puppeteer = require('puppeteer');
puppeteer.launch({
  executablePath: '/Applications/Chromium.app/Contents/MacOS/Chromium',
  headless: false
}).then(async b => {
  const p = await b.newPage();
  await p.goto('http://127.0.0.1:8000');
  const btn = await p.$('button');
  await btn.click();
  console.log('clicked.');
  await new Promise(resolve => {
    setTimeout(() => resolve(), 5000);
  });
  await b.close();
});
```

**What is the expected result?**
Click button will raises error since there's a modal layer in the front of button element, it is not clickable, just like Selenium does.

**What happens instead?**
No error raised, the program print "clicked" and exited.

**Comment by JoelEinbinder** [comment]
This seems reasonable. It isn't trivial because of [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) and scrollbars could obscure an element. But in theory it should be doable.

**Comment by ohana54** [comment]
@JoelEinbinder can we do what chrome driver does? I found [this piece of code](https://github.com/SeleniumHQ/selenium/blob/1721e627e3b5ab90a06e82df1b088a33a8d11c20/javascript/chrome-driver/atoms.js#L214), not sure it's the right one but looks like what we're after (found it by looking for the error message I know webdriver throws in those cases).

**Comment by focalism** [comment]
@JoelEinbinder 
I try this page with selenium in python:
```
#! coding:utf-8

from selenium import webdriver
from selenium.webdriver.common.by import By

def creat_webdrive():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument('window-size=1920,1080')
    drive = webdriver.Chrome(chrome_options=chrome_options)
    return drive

def login_tenant():
    drive.get('test.html')
    user = drive.find_element_by_css_selector('button')
    user.click()

if __name__ == '__main__':
    drive  = creat_webdrive()
    login_tenant()
```
I get this:
```
  File "C:\Program Files (x86)\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button onclick="alert('hello!');">...</button> is not clickable at point (40, 20). Other element would receive the click: <div class="modal"></div>
```
The reason is I can not click the `button` because the `modal` in front of it.

**Comment by yanivefraim** [comment]
@JoelEinbinder - can I somehow help here?

**Comment by aslushnikov** [comment]
@JoelEinbinder can we use [`elementFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementFromPoint) to figure if we're clicking the right element?

**Comment by yanivefraim** [comment]
@aslushnikov - this is exactly what selenium does (see [here](https://github.com/SeleniumHQ/selenium/blob/1721e627e3b5ab90a06e82df1b088a33a8d11c20/javascript/chrome-driver/atoms.js#L234))

I will be happy to help (:

**Comment by yanivefraim** [comment]
@aslushnikov, @JoelEinbinder - this feature is important to us (we have teams moving from selenium, and we want to be aligned with similar behavior).

I was thinking of testing that `elementFromPoint` returns the same element as the desired element, [here](https://github.com/GoogleChrome/puppeteer/blob/master/lib/ElementHandle.js#L113) (not sure if this is the best place)

WDYT?

**Comment by aslushnikov** [comment]
@JoelEinbinder I verified that `elementFromPoint` accounts for `pointer-events: none`. 

@yanivefraim this will probably work. So far the only tricky part seems to be shadow dom: element handles might come from-inside shadow trees, but `elementFromPoint` won't pierce inside.

I'll be happy to review a PR

**Comment by JoelEinbinder** [comment]
`elementFromPoint` also won't pierce iframes. We have a protocol method, `DOM.getNodeForLocation`, which would be perfect except it operates with nodeIds. It is also not trivial for us to determine if a node is a child of another node when dealing with iframes/shadow dom.

**Comment by ysmood** [comment]
Tested in [rod](https://github.com/go-rod/rod), it works fine even with nested iframes. Here's the clickable demo:

https://github.com/go-rod/rod/blob/6d9f7de0d20f14322a284133199174abcc7bc077/element_test.go#L27-L42

Here's the nested iframes demo:

https://github.com/go-rod/rod/blob/6d9f7de0d20f14322a284133199174abcc7bc077/query_test.go#L61-L66

There's one chrome bug we need to watch out: 

https://github.com/go-rod/rod/blob/6d9f7de0d20f14322a284133199174abcc7bc077/page.go#L699-L704

If you don't call `DOM.getDocument` before using `DOM.getNodeForLocation`, it will return 0 node id, no matter you enabled `Dom.enable` or not.
