### ISSUE TITLE
How to reuse browser gracefully

### ISSUE THREAD

**Issue by KimSeongIl** [puppeteer/puppeteer#2108]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: mac and docker container(based ubuntu:16.04)
* Node.js version: 8.9.3

_Please include code that reproduces the issue._

    const browser = await getBrowser();

    browser.on('disconnected', async () => {
        console.log('browser is disconnected.');
        await browser.close();
        await launchBrowser();
    });

    const page = await browser.newPage();

    page.on('error', (err) => {
        console.log(err);
        throw err;
    });

    await page.goto(url, { timeout, waitUntil: 'load' });

    const screenshot = await page.screenshot();

    await page.close();

**What is the expected result?**

   
I have created a browser object through puppeteer.launch at the start of nodejs and reuse it.
I want to know how to gracefully reuse the browser when page crashed errors occur.

**What happens instead?**

When the page crashed error occurs, the disconnected event is called. If i attempt to close the disconnected browser in the function, an error message is printed.

Error: read ECONNRESET
at _errnoException (util.js:1024:11)
at TCP.onread (net.js:615:25)

How do I kill a disconnected browser?
Thanks.

**Comment by JoelEinbinder** [comment]
If you recieved a 'disconnected' event, you don't have to/can't call browser.close(). The browser has probably already shut down, which is why you received the 'disconnected' event.

**Comment by KimSeongIl** [comment]
@JoelEinbinder 
It works well. Thank you!
