### ISSUE TITLE
Handle File Input selection dialog.

### ISSUE THREAD

**Issue by tracker1** [puppeteer/puppeteer#2114]
How would I handle the file selection on the `.click` the input element is created dynamically.  Should I add code handling to deal with a test injection?  Is there a way I can globally trap the file selection event and give it a file/files list?  There is more code in place for setting the input type filter, which it seems can only be set once.  

```
const uploadInput = document.createElement('input');
uploadInput.type = 'file';
uploadInput.addEventListener('change', evt => {
  ...
});
uploadInput.click();
```

**Comment by JoelEinbinder** [comment]
You can use `elementHandle.uploadFile` instead of clicking the input. The file dialog behavior is different across operating systems, so we have this more direct way of handling it.

**Comment by tracker1** [comment]
So, I have to write a custom if/trap in my code to handle the test case.  How should I go about that on a dynamically created element?  Do you have some examples?

In my case, this dynamic file input creation, and click happens as a result of a drag-drop event.  I'm presenting a file picker in the UI, so I don't have a disconnected file handle in the UI.

**Comment by parasvora** [comment]
@JoelEinbinder In my case, the `elementHandle.uploadFile` adds the path in the input box however, doesn't calls the services from backend. If I go in a human way, I have to click on a **Choose file** button post which, the file input selection dialog opens up. Once i navigate to the file & select it, the content of the file is read & displayed on the UI.
I am facing issues while replicating this in puppeteer. 
@tracker1 Did you find any solution/ workaround?

**Comment by tracker1** [comment]
@parasvora TBH, I don't remember specifically...  IIRC I added a reference to an object and used that to call the `.uploadFile` instead of the `click` event... I'm no longer working on, or have access to the source, or would be able to give more info.

**Comment by aslushnikov** [comment]
@parasvora can you please share a URL of the website so that we can take a look?
