### ISSUE TITLE
PostData not being used with using Page overrides during post

### ISSUE THREAD

**Issue by AmitMathur** [puppeteer/puppeteer#2115]
Hi All:

I am trying to do a POST to a URL, which need some Body parameters. 
I added Request Interceptor and it is getting called.

Here is the code
 `{`
`var headers = request.headers;`
`headers['content-type'] = 'application/x-www-form-urlencoded; charset=UTF-8';`
   `overrides.method = "POST"; `
    	`overrides.postData= "para1=val1&para2=val2";`
    	`overrides.headers = headers;`
    `}`
    `request.continue(overrides);`

But when `await page.goto` to the POST url, it is doing a post but the post data is not reaching there.

Can anyone help please on:
- Is the format of `overrides.postData` correct, or it needs to be something else?
- Or if I am doing something wrong.

**Comment by GuilloOme** [comment]
related to #2233 ?

**Comment by AmitMathur** [comment]
The way i finally got it working is as below:

>   var formData =
  { 'param a': 'value a',
    'param b': 'value b'
   };
await page.setRequestInterception(true);
  page.on('request', request => {
	var options = {};   
    if (<some condition>) {
    	options = { 
				  method: 'POST',
				  url: <URL>,
				  headers: 
				   { 'cache-control': 'no-cache',
					 'content-type': 'application/x-www-form-urlencoded' },
				  postData: qs.stringify(formData) };
    }
    request.continue(options);
  });

This worked for me and did a fine POST with all parameters.

**Comment by wesley-firewalla** [comment]
@AmitMathur  the solution doesn't work for me.

**Comment by AmitMathur** [comment]
@wenbinke can you post your request / script?

**Comment by wesley-firewalla** [comment]
@AmitMathur  
I just used your code. You can see when headless is false, in the chromium developer tools, it doesn't change the original headers or postData, method.  You can try your code again.
I am using the latest puppeteer version.

**Comment by AmitMathur** [comment]
are you running headless=false?
The above code still works for me. I am assuming you are adding all the missing values like url and including query string in your script.
