### ISSUE TITLE
page.goto with file:/// URI returns non-ok response

### ISSUE THREAD

**Issue by saschanaz** [puppeteer/puppeteer#2116]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 9.6.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer = require("puppeteer");

let src = `file://${process.cwd()}/examples/basic.built.html`; // can be a file or http url

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const response = await page.goto(src);
  console.log(response.ok(), response.status());
  console.log(await response.text());
  browser.close();
})();
```

**What is the expected result?**

`response.ok()` should be `true`.

**What happens instead?**

`response.ok()` is `false` even when it gets a valid response from file system.

**Comment by JoelEinbinder** [comment]
Good catch!
