### ISSUE TITLE
Chromium difference without script / with script

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#2118]
When I use the browser without launching puppeteer script, the web page works well and does not show me any security captcha. but when I do it with my puppeeter script, it sends me a captcha when entering the we. Should I configure something at the beginning of my scripts?

**Comment by ebidel** [comment]
Duplicates of https://github.com/GoogleChrome/puppeteer/issues?q=is%3Aissue+Captcha+is%3Aclosed
