### ISSUE TITLE
memory isn't released when browser is closed

### ISSUE THREAD

**Issue by rabbitLove520** [puppeteer/puppeteer#2125]
* Node.js version       8.9.4
* Docker  Version 17.12.0-ce
* Puppeteer version: 1.1.0

My code:
```
 try {
        browser = await puppeteer.launch({args: ['--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage']});
        const page = await browser.newPage();
        await page.setRequestInterception(true);
        await page.goto(url);
        // ...
        await bodyHandle.dispose();
        await browser.close();
    } catch(err) {
        if(bodyHandle) {
            await bodyHandle.dispose();
        }
        await browser.close();
        throw new Error('detect failed: ' + err.message);
    }
```
**I freed the resources after using puppeteer**, however I found memory grew larger and larger with invoking the method seveval times.
![image](https://user-images.githubusercontent.com/16663435/36825486-c02a9e46-1d42-11e8-915e-551a15e8c1a4.png)

![image](https://user-images.githubusercontent.com/16663435/36825473-ac5fde08-1d42-11e8-9b2b-461fb556f9af.png)

**Comment by leobudima** [comment]
Same on Lambda, v1.1.1...

**Comment by matthaywardwebdesign** [comment]
@salamander-mh How are you running Puppeteer under Docker? In particular is it being run with `dumb-init` to ensure zombie Chrome processes are killed?

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker
