### ISSUE TITLE
Is there a way to get the Frame that's calling function set by exposeFunction?

### ISSUE THREAD

**Issue by Madd0g** [puppeteer/puppeteer#2126]
I need to get the Frame object (in a synchronous way) in an exposed function, according to the docs `page.frames()` is sync, but things like `elementHandle.contentFrame()` and all the elementHandle stuff are async.

Is there a nice way of knowing which frame is calling my function without doing any async calls in the function itself?

Thanks!

**Comment by aslushnikov** [comment]
No, this is not possible atm. We technically can pass calling frame as the first argument to the binding, but that would be a breaking change.

I added this to the 2.0 "things to consider".
