### ISSUE TITLE
page.goto should reset page bindings

### ISSUE THREAD

**Issue by brikou** [puppeteer/puppeteer#2127]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

```js
await page.goto('http://foo.com/1');
await page.evaluate(()=> window.foo === undefined); // true
await page.exposeFunction('foo', foo);

await page.goto('http://foo.com/2');
await page.evaluate(()=> window.foo === undefined); // true as this is a new context
await page.exposeFunction('foo', foo); // throw an exception :/ because already in page._pageBindings map
```

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

thanks :+1:

**Comment by aslushnikov** [comment]
`page.exposeFunction` survives navigation by design. This is needed because it's unpredictable when page decides to navigate.

I can't reproduce your case though, here's what I've tried:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  const foo = () => {};
  await page.goto('http://example.com/1');
  console.log(await page.evaluate(()=> window.foo === undefined)); // logs "true"
  await page.exposeFunction('foo', foo);

  await page.goto('http://example.com/2');
  // The following logs "false" - exposeFunction survived navigation.
  console.log(await page.evaluate(()=> window.foo === undefined));
  await browser.close();
})();
```

If you have a repro case I can play, feel free to write back.
Hope this helps.
