### ISSUE TITLE
Scraping CSS Selector from a URL?

### ISSUE THREAD

**Issue by NagarjunPrasad1** [puppeteer/puppeteer#2128]
Since puppeteer is being widely used for web scraping is there any way to scrape the CSS Selector? Something like:
var selector = puppeteer.getSelector("div",".container.main-container");
page.click(selector);

**Comment by ashoon** [comment]
Am looking for something like this or similar - get CSS selector based on a text displayed in browser.

**Comment by aslushnikov** [comment]
@NagarjunPrasad1 I'm not sure what's "scrape a selector", but you can use element handles for the usecase you mention:

```js
const handle = await page.$('.contqiner.main-container');
await handle.click();
```
