### ISSUE TITLE
Bug with PDFs and Acrobat Reader

### ISSUE THREAD

**Issue by galvez** [puppeteer/puppeteer#2129]
So this is more of a heads up / tip: for those of you having issues with merged letters in PDFs when opening in Adobe Acrobat Reader, I was able to fix it by adding a zero-width non-breaking space character (0xFEFF) between every single letter of the page. This produced the exact same rendering when viewing a PDF in Chrome and viewing it in Adobe Acrobat.

**Comment by galvez** [comment]
Note: this "bug" only happens in Adobe Acrobat Reader for any *webfonts* used in a page.

**Comment by JoelEinbinder** [comment]
Does the same thing happen if you print to pdf from Chrome?

**Comment by galvez** [comment]
@JoelEinbinder yep!

**Comment by JoelEinbinder** [comment]
Thanks for the heads up. I'll close this as not a Puppeteer specific issue, but feel free to discuss workarounds here. If it's a Chromium bug, you can file an issue on crbug.com. If it's a problem with Adobe Acrobat I don't know where you file that.
