### ISSUE TITLE
Documentation for API comparisons

### ISSUE THREAD

**Issue by Garbee** [puppeteer/puppeteer#213]
There are more tools hitting the market like [Chromeless](https://github.com/graphcool/chromeless). Given this one also provides a [chain-style API](https://github.com/GoogleChrome/puppeteer/pull/212) it could be very useful to have direct comparison examples. This will help developers quickly assess which tool style they like best. Whether we include the chain API or not, these docs are still relevant.

Initially, I'd like to hit on porting the Chromeless examples into a doc. There are 3 highlighted examples and a few others in their folder. For the initial pass we'll just port in the highlighted ones and build a comparison with our current API. This is enough fodder to test page structure and see how things read/look. Once that is all in place the other examples can be copied in. And any of our examples that highlights different/unique functionality can be attempted in Chromeless for examples.

If we do land a chaining API, then our chain samples should be an extra sample added to each and clearly marked as such. That way people can compare the different internal styles to programming their scripts.

### Actions

* [ ] Initial doc page bringing in 3 primary Chromeless examples.
* [ ] Provide alternative fully functioning code using our API
* [ ] Look over our examples for what provides unique functionality and attempt it in Chromeless for example comparisons.

**Comment by ebidel** [comment]
Chromeless has definitely had some great initial pickup. That said, it's still relatively new. I wonder if waiting a bit on comparative examples would be better. My worry is about maintenance and how we prioritize other similar APIs surfaces like webdriver.io? Maybe examples could start from the community.

**Comment by Garbee** [comment]
Waiting on it for a bit SGTM. Chromeless is fairly fresh (only two or three weeks old being public iirc.) So adoption is mostly in the "still looking" phase. Which if we release before people get heavily vested in it, they may just use Puppeteer since it is a direct Chrome product. This was more of an advisory issue since I can instantly see people wanting a comparison to help them chose.

Unless someone else has a strong wish for this before launch happens we can close it on up. For now I'll leave it open for two days to let it get thought over a bit if anyone wants to. If no one raises a concern Thursday morning I'll close it on up with no action taken until we see a need for this kind of thing internally.

**Comment by aslushnikov** [comment]
Looks like no one has a strong wish for this, closing.
