### ISSUE TITLE
Cannot get correct utf-8 string if <meta charset="utf-8"> is not set in web page.

### ISSUE THREAD

**Issue by vinsonio** [puppeteer/puppeteer#2130]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.1
* Platform / OS version: Ubuntu 16.04 LTS
* URLs (if applicable): https://hk.appledaily.com/realtime/realtimenews/20180228/local
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

1. go to the web page
2. then get the first news title by
```
page.$eval(selector, el => el.innerText)
```
**What is the expected result?**
Correct UTF-8 string
```
【預算案】自願醫保可被拒保 陳茂波：第一步未必滿足所有人
```

**What happens instead?**

```
ã€é ç®—æ¡ˆã€‘è‡ªé¡˜é†«ä¿å¯è¢«æ‹’ä¿ é™³èŒ‚æ³¢ï¼šç¬¬ä¸€æ­¥æœªå¿…æ»¿è¶³æ‰€æœ‰äºº
```
Is there any option I can set the browser default character encoding to utf-8 in config?

**Comment by vsemozhetbyt** [comment]
It seems it would be possible if we could replace the `Content-Type` response header before page parsing. But I cannot find a way to do that in the docs. Maybe some counterpart of the
`page.setExtraHTTPHeaders(headers)` can be added for responses?

**Comment by vinsonio** [comment]
@vsemozhetbyt Still cannot get the correct title after adding
```
page.setExtraHTTPHeaders({
      'Accept-Charset': 'utf-8',
      'Content-Type': 'text/html; charset=utf-8',
    })
```

**Comment by vsemozhetbyt** [comment]
@vinsonyung Yes, this function adds request headers, not response headers. I just have asked the developers if this was a good idea to add some similar function for response headers substitution)

**Comment by vsemozhetbyt** [comment]
You can try something like this as a workaround:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    const response = await page.goto('https://hk.appledaily.com/realtime/realtimenews/20180228/local');

    await page.setContent((await response.buffer()).toString('utf8'));

    console.log(await page.$eval('div.text > a[href]', el => el.innerText));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by JoelEinbinder** [comment]
Without setting the meta utf8 header I see gibberish in Chrome, so I think this is working as intended. The page in question looks like it is meant to be loaded through AJAX into a contained with the proper meta tag. Closing this as not a Puppeteer bug.

**Comment by vinsonio** [comment]
@vsemozhetbyt Sorry for replying late. It works. Thank you very much.
