### ISSUE TITLE
How to catch page unresponsive (kill page / wait) error

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#2131]
Puppeteer version: 1.1.1
Platform / OS version: Win10
Node.js version: 9.4.0
Chromium Version: r536395

Some of web pages have infinite loop or hard scripts and crash google chrome.

For example:

```js
var puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        userDataDir: "profile",
        ignoreHTTPSErrors: true,
        dumpio: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu']
    });
    const page = await browser.newPage();
    await page.setCacheEnabled(false);
    await page.goto('http://syb.artvin.edu.tr/iletisim-354', {
            waitUntil: ['networkidle0', 'load', 'domcontentloaded'],
            timeout: 10000
        })
        .then(async () => {
            //something
        })
        .catch(async (error) => {
            console.log(error);
            await browser.close();
        });
    await browser.close();
})();
```

Above code returns 

> "Error: Navigation Timeout Exceeded: 10000ms exceeded"

How can i catch chrome "Page Unresponsive (Kill page / wait)" error before Navigation Timeout error ?
On headless mode, there is no problem.
But when you set headless:false, "Page Unresponsive" problem prevents browser close at the end of the script.

**Comment by paambaati** [comment]
@OzqurYalcin @aslushnikov This might be worth reopening, as it isn't fixed yet.

**Comment by josephrocca** [comment]
I'm not sure if this is the same or related to OP's particular issue, but I get an infinitely long pause when calling `await page.close();` on a page with an infinite loop in a script on the page. Solution for me was to kill the whole browser and restart.

I've noticed that when using Chrome I sometimes can't exit a tab with an infinite loop, and so I need to open Chrome's built-in task manager to kill the tab. I'm guessing that's related to what's happening here.

**Comment by lesleyxyz** [comment]
I can confirm, still an issue like previous replies.

Possible solutions are:
1) use `{ headless: true }`
2) `await browser.close()` instead of page
