### ISSUE TITLE
puppeteer format coverage is missing some information

### ISSUE THREAD

**Issue by bcoe** [puppeteer/puppeteer#2136]
Some of the folks working on Istanbul recently released the tool [puppeteer-to-istanbul](https://github.com/istanbuljs/puppeteer-to-istanbul), which converts from puppeteer coverage format to Istanbul format, allowing Istanbul reports to be run.

The tool works, but there does seem to be some information missing in puppeteer style output (this is discussed in #1768). Specifically:

* callCount is not reported  (it seems like there should probably be a flag to enable callCount).
* I noticed block level coverage is working for `if` statements, but not binary statements, e.g., `const foo = 99 || 103`.

**What steps will reproduce the problem?**

1. collect coverage for a file that executes a line multiple times (see: https://github.com/bcoe/puppeteer-to-istanbul-example, for setting up the test case). 
2. collect coverage for a file that has a binary operation, e.g., `const foo = 99 || 100`.

**What is the expected result?**

* call counts should be tracked.
* partial block level coverage should be collected (`[const foo = 99 ]|| 100`).

**What happens instead?**

* No callCount information is reported.
* the entire line `const foo = 99 || 100` is missing coverage.

----

It would be awesome to get all the fancy pants work that @schuay has done around block-level coverage outputting in reports collected through puppeteer.

CC: @aslushnikov, @shannon, @JoelEinbinder,  @vkoves and @rjaltman

**Comment by LarsDenBakker** [comment]
@jackfranklin would it be possible to expose the raw v8 test coverage data? There are some tools which expect this format. 

We could add a flag to the `stop` function to specify the format, or we could introduce a separate method. What do you think?

**Comment by TimvdLippe** [comment]
For additional context, I found this reference in the code that Lars is referring to: https://github.com/modernweb-dev/web/pull/174/files#diff-8365ecf94906ff774beccd6509eec588R88

**Comment by LarsDenBakker** [comment]
Indeed. I'm using https://github.com/istanbuljs/v8-to-istanbul/ which expects the raw v8 data format.
