### ISSUE TITLE
For .$x(expression), allow XPath variables to be bound

### ISSUE THREAD

**Issue by ujay68** [puppeteer/puppeteer#2137]
It would be convenient to bind XPath variables into expressions, eg with a map like this:

`page.$x("//button[normalize-space(.)=$text]", { "text": "The Button Text" /* , … more variables */ })`

Motivation: If you construct XPath expressions by concatenating strings like this:

`var text = "The Button Text"; // probably as a parameter from somewhere else`
`page.$x("//button[normalize-space(.)=' + text + ']")`

You'd have to be careful to properly escape the text, which is tedious and error-prone and maybe even subject to security-critical parameter injection. Passing the dynamic parameter as an XPath variable would be inherently safe.

**Comment by JoelEinbinder** [comment]
You can use template strings with a tag for this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by ujay68** [comment]
Template strings do not address the issue that the embedded text would have to be escaped, both for functional and for security reasons.

**Comment by JoelEinbinder** [comment]
You can write an escaping function as a tag: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates
