### ISSUE TITLE
How to insert envionment variables into the page ?

### ISSUE THREAD

**Issue by ycjcl868** [puppeteer/puppeteer#2138]
### Environment

* Puppeteer 1.1.1
* MacOS Sierra 10.12.6
* Node.js 8.9.0

### Problem
I'd like to insert some variable(eg. `window.xxx = 'abc'`) into `a.com` (the default variable `window.xxx = 'default'`, will read the variable)
this is my code ...
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
  });
  const page = await browser.newPage();
  await page.goto('https://a.com');
  const html = await page.evaluate(() => {
    return document.getElementById('root').innerHTML;
  })
  console.log(html);
  await browser.close();
})();

```

### Expected Result
the html content will be `this is abc` not `this is default` .

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/blob/v1.1.1/docs/api.md#pageevaluateonnewdocumentpagefunction-args

**Comment by rjhilgefort** [comment]
For future Googlers, I ended up making a helper function to make the process easier. I think It's a little less boiler-platey than what's in the docs for `page.evaluateOnNewDocument`.

```js
const puppeteer = require('puppeteer');

const windowSet = (page, name, value) =>
  page.evaluateOnNewDocument(`
    Object.defineProperty(window, '${name}', {
      get() {
        return '${value}'
      }
    })
  `)
);

const { foo } = process.env;

(async () => {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();

  await windowSet(page, 'foo', foo)

  await page.goto('https://a.com');
  const html = await page.evaluate(() => {
    window.foo // <---- Whatever was set on `process.env`
  });

  await browser.close();
})();
```

**Comment by lmiller1990** [comment]
Thanks for taht @rjhilgefort , very useful.

**Comment by jkenne000** [comment]
Is there a way to do this in Java? I'm using this as my guide: https://ksah.in/introduction-to-chrome-headless/
