### ISSUE TITLE
CPU keeps 100% indefinitely when `npm i puppeteer --save`.

### ISSUE THREAD

**Issue by cmal** [puppeteer/puppeteer#2139]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.1
* Platform / OS version: Darwin localhost 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
* URLs (if applicable):
* Node.js version: v8.9.4
* npm version: 5.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. npm i puppeteer --save
2. none
3. none

**What is the expected result?**

installed without error.

**What happens instead?**
```
⸨  ░░░░░░░░░░░░░░░░⸩ ⠹ loadDep:source-map: sill resolveWithNewModule puppeteer@1.1.1 checking installable status
```
and CPU keeps 100% indefinitely.

**Comment by deepakshrma** [comment]
I believe it related to the proxy issue. Please set proxies, if you are working in the enterprise environment.
Check: https://github.com/GoogleChrome/puppeteer/pull/455
