### ISSUE TITLE
response event can't get long pending time request 

### ISSUE THREAD

**Issue by WG-Com** [puppeteer/puppeteer#2140]
...
![image](https://user-images.githubusercontent.com/14095443/36964600-233d9496-2092-11e8-8b1f-882edc0de6e9.png)

i can wait , but it's never back , it's ok in chrome browser

**Comment by aslushnikov** [comment]
Looks like this is a bug about devtools rather then pptr. Please file upstream to https://crbug.com/new

**Comment by sheikalthaf** [comment]
@mathiasbynens I'm still facing this issue in puppeteer. Where can i track the issue about this?

**Comment by landaida** [comment]
The same error for me on many puppeteer releases
![image](https://user-images.githubusercontent.com/5694096/126531205-f7e58978-b4a3-4335-915c-661c7acf0a8c.png)
