### ISSUE TITLE
Puppeteer + Glitch

### ISSUE THREAD

**Issue by kaycebasques** [puppeteer/puppeteer#2143]
My hunch is that we can get it working with the right combo of flags and configs...

Any ideas on how to get past this `504 Gateway Timeout`?

https://glitch.com/edit/#!/puppeteer-example?path=server.js:22:3

**Comment by kaycebasques** [comment]
It was pilot error, some peeps on Glitch support helped me get it working: https://support.glitch.com/t/glitch-puppeteer/3091

**Comment by ebidel** [comment]
Seems to be working now :)

That's nice that glitch supports Chromium out of the box. Usually there's issues with shared deps missing on Linux.

BTW, you don't need to save the `.png` then `sendFile()`. Just send the buffer directly:
https://github.com/PaulKinlan/puppeteeraas.com/blob/master/server.js#L137-L138

```js
response.type('image/png').send(await page.screenshot({fullPage: true}));
```

**Comment by johnkpaul** [comment]
This no longer works. In trying to manually install puppeteer onto Glitch, I am getting no space left on disk errors. I don't think that Glitch supports puppeteer at the moment. 
<img width="1268" alt="screenshot 2018-05-19 13 56 31" src="https://user-images.githubusercontent.com/475621/40271545-77d27502-5b6c-11e8-9616-d61440c9385f.png">

**Comment by kaycebasques** [comment]
Hey @johnkpaul I noticed that too but think I've got a workaround for it.

**Logs** > **Console** > `rm -rf node_modules && refresh`

`refresh` is a special Glitch command that restarts the environment, or something.

Demo seems to be working again: https://puppeteer-example.glitch.me/
