### ISSUE TITLE
How to select all matched name(inner text) on page and then click on required price?

### ISSUE THREAD

**Issue by rustemkzk** [puppeteer/puppeteer#2144]
Hello. I have a web page with different items and different prices. So my task is: 
firstly, select all items with required innertext, like this 
`page.$$eval("a", as => as.find(a => a.innerText..includes("ITEMNAME"))`
secondly, to click on price of this item(not first matched, but it should be from selected items)
`page.$$eval("a", as => as.find(a => a.innerText..includes("colourNAME")).click();`

Item Name like this `<p> Hoodie</p>`. And price like this `<span class="_342BXW_" data-auto-id="productTilePrice">£18.00</span>`.  So i need to select all items that contain Hoodie(there are t-shirts,pants that costs 18£) and then click at that price(18£).

I think that new update of puppeteer($x method) have a lot to do with this.

**Comment by b26** [comment]
What issue are you experiencing with puppeteer? If there aren't issues and only questions, please post on stackoverflow or on the puppeteer slack channel. Cheers
