### ISSUE TITLE
How to copy text from browser clipboard

### ISSUE THREAD

**Issue by kushaljshah** [puppeteer/puppeteer#2147]
Is a there a way where I can copy content from browser clipboard. I am trying to copy content post the page is rendered. This is being achieved by the bellow code but unable to get the content.

```
await page.keyboard.down('ControlLeft');
await page.keyboard.press('KeyA');
await page.keyboard.up('ControlLeft');

await page.keyboard.down('ControlLeft');
await page.keyboard.press('KeyC');
await page.keyboard.up('ControlLeft');
```

**Comment by ebidel** [comment]
Why do you need the clipboard? e.g. Get the text from the page and save it to a file (back in node) or use something like https://www.npmjs.com/package/copy-paste.

As for the browser, Chrome has a new (better) clipboard API in the works. I believe it's in chrome 66:

A modern, asynchronous Clipboard API based on Promises.

Text-only APIs (clipboard.readText and clipboard.writeText):
* Behind a flag in M62
* Enabled by default in M66

Support for images and other data types is still under development.

https://www.chromestatus.com/feature/5861289330999296

You might be able to hack code that injects a listener but the API might require a user gesture/permission prompt, which we don't have control over. Upstream chrome bug: https://github.com/GoogleChrome/puppeteer/issues/846. Please star it and an your use case :)

There's also the older API but it's clunky to use:
https://www.chromestatus.com/feature/5223997243392000

Let us know if you get something working.

**Comment by JoelEinbinder** [comment]
The clipboard is actually the OS clipboard, not the browser clipboard. So you can use a node module like: https://github.com/sindresorhus/clipboardy

**Comment by kushaljshah** [comment]
@ebidel Thanks for the update on the clipboard api. Had tried capturing key event as well post copying, but it didn't work out. Didn't quite clearly get what is wrong here.
```
await page.evaluate(() => {
   window.addEventListener('keyup', () => {
       console.log('Event triggered');
    }, false);
});
```


My current use case is to get all the visible text on the rendered page.  This should be solved by the following piece of code without using clipboard. 
```
const documentHandle = await page.evaluateHandle('document');
const contents = await page.evaluate(document => document.body.innerText, documentHandle);
await documentHandle.dispose();
```

**Comment by kushaljshah** [comment]
@JoelEinbinder When I am launching puppeteer with headless:false mode, I am able to get content from OS clipboard. 

With headless:true mode, unable to get content from clipboard. So not entirely sure where is the content getting buffered. For my use case, I want to use in headless mode to avoid GUI overheads. Tried the following node utilities

https://github.com/sindresorhus/clipboardy
https://github.com/xavi-/node-copy-paste

**Comment by PatrickGeyer** [comment]
@engineerkushal, did you solve this issue? I am having the same problem in headless mode.

**Comment by Jazen1995** [comment]
same to me. how can i test copy paste operation ?

**Comment by inevity** [comment]
`
     await page.click('#ueditor_0');
    await page.keyboard.type(clipboardy.readSync());// the content is a web page including text and image.
`
Use the clipboardy to paste the data to the selector. But only got text,no image . 
How to paste the rich text?

**Comment by alanbright** [comment]
I try the "Copy from input box" usage part in below link
https://stackoverflow.com/questions/49131516/how-to-copy-text-from-browser-clipboard-using-puppeteer-in-nodejs
and I can copy input text field, in headless mode in my case

**Comment by h2grover** [comment]
> @JoelEinbinder When I am launching puppeteer with headless:false mode, I am able to get content from OS clipboard.
> 
> With headless:true mode, unable to get content from clipboard. So not entirely sure where is the content getting buffered. For my use case, I want to use in headless mode to avoid GUI overheads. Tried the following node utilities
> 
> https://github.com/sindresorhus/clipboardy
> https://github.com/xavi-/node-copy-paste

any luck in headless mode?

**Comment by pegiadise** [comment]
I was able to read from clipboard in headless mode of `puppeteer@3.0.2` with:

```js
const context = await browser.defaultBrowserContext()
await context.overridePermissions('https://example.com', ['clipboard-read'])
const copiedText = await page.evaluate(`(async () => await navigator.clipboard.readText())()`)
```

**Comment by codingedgar** [comment]
Why is this closed if it wasn't solved? Can it be reopened?

I'm trying to test if my app "copy to clipboard" button works, but after clicking the button with puppeteer when I use `await page.evaluate(async () => await navigator.clipboard.readText())` it returns the previous clipboard. (like if the button didn't work, but it does).

Reading the clipboard while headless works.
But the app button to "copy to clipboard" doesn't put anything in the clipboard.

**Comment by abraham** [comment]
In puppeteer v2.1 using `overridePermissions`

```js
await context.overridePermissions(origin, [
    'clipboard-write',
    'clipboard-read',
  ]);
```
would allow `writeText` to work in headless and headful mode.
```js
clipboard.writeText(window.location.href)
```
In v3.3 it only works in headful mode.

**Comment by codingedgar** [comment]
I’m on 3.1 and testing a clipboard copy button, and the `overridePermissions` As stated doesn’t work, I can only read the os clipboard but not write it (neither headless nor headful mode).

**Comment by chrisdavies** [comment]
Well, in my case, I was trying to test a rich text editor (never write one). Anyway, execCommand works for copy, but not for paste. I ended up mocking out the clipboard events, and it works fine:

```js
function execClipboardEvent(selector, name) {
  return page.evaluate((selector, name) => {
    const el = document.querySelector(selector);
    const e = new CustomEvent(name);
    window.puppeteerClipboard = window.puppeteerClipboard || new Map();
    e.clipboardData = {
      files: [],
      getData(k) {
        return puppeteerClipboard.get(k);
      },
      setData(k, v) {
        puppeteerClipboard.set(k, v);
      },
    };
    el.dispatchEvent(e);
  }, selector, name);
}

const clipboard = {
  copy: (selector) => execClipboardEvent(selector, 'copy'),
  cut: (selector) => execClipboardEvent(selector, 'cut'),
  paste: (selector) => execClipboardEvent(selector, 'paste'),
  clear: () => page.evaluate(() => (window.puppeteerClipboard = undefined)),
};
```
