### ISSUE TITLE
Tracing: stop() should return Promise<Buffer>

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#2148]
It would be convenient if `page.tracing.stop()` returned `Promise<Buffer>` so users could act ton the trace JSON without saving a file to disk. This would also be consistent with the screenshot API.

**Comment by JoelEinbinder** [comment]
Pull requests welcome :smile:

**Comment by ebidel** [comment]
Ping.

**Comment by kblok** [comment]
@ebidel, @aslushnikov I know I'm quite late here 😜but, Why would it need to return a buffer instead of just a simple string? We are [building a buffer based on a string](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Tracing.js#L82). Why not just returning that string to the client?

**Comment by aslushnikov** [comment]
@kblok iirc buffers are allowed to allocate more memory then strings.
