### ISSUE TITLE
Evaluation failed: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by francocorreasosa** [puppeteer/puppeteer#2149]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `v1.1.1`
* Platform / OS version: `Darwin 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64`
* Node.js version: `v8.9.4`

**What steps will reproduce the problem?**

```js
await page.evaluate(() => localStorage.getItem('access_token'))
```

**What is the expected result?**
`<access_token> value from localStorage`

**What happens instead?**
```
    Evaluation failed: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:75:13)
```

**Comment by mattmcguin** [comment]
@francocorreasosa Why was this closed?
