### ISSUE TITLE
Script runs only sometimes

### ISSUE THREAD

**Issue by apulidoc** [puppeteer/puppeteer#2150]
Here is my code:

`const puppeteer = require('puppeteer');

let scrape = async () => {
    const browser = await puppeteer.launch({ executablePath: 'C:\\Users\\Dridrazo\\AppData\\Local\\Google\\Chrome SxS\\Application\\chrome.exe', args: ['--disable-dev-shm-usage']});
    const page = await browser.newPage();

    await page.goto('https://mobile.bet365.com/#type=InPlay;key=;ip=1;lng=3', {waitUnil:'domcontentloaded'});
    await page.waitFor(1000);
    await page.waitForSelector('div.ipo-MarketSwitcher');

    const result = await page.evaluate(() => {
        let data = []; // Create an empty array that will store our data
        let elements = document.querySelectorAll('div.ipo-Classification'); // Get all sports

        for (var sport of sports){ 
            let title = element.textContent; // Select the title of the sport

            data.push({title}); // 
        }

        return data; // Return our data array
    });

    browser.close();
    return result; // Return the data
};

scrape().then((value) => {
    console.log(value); 
});`

Platform: Windows 10
Node: 8.9.4
Puppeteer: 1.1.1

Sorry for my english but my script runs as expected only a few times. 

I tried to execute with Chromium, Chrome and now with Chrome Canary.

(node:1124) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:1124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JoelEinbinder** [comment]
Your requests to the server are timing out. If you own the server you can investigate its CPU usage. If not, well you probably shouldn't be doing what you are doing.

**Comment by putuoka** [comment]
@apulidoc you have # symbol in url. puppetteer till the latest version can't handle this yet. try to shorting your url with goo.gl
