### ISSUE TITLE
"Navigation Timeout Exceeded" error when setting headless flag to true, works with false.

### ISSUE THREAD

**Issue by Syllinger** [puppeteer/puppeteer#2151]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.1
* Platform / OS version: Windows 7 SP 1
* URLs (if applicable): www.google.com
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

(async function test() {
  try {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
  
    await page.goto('https://www.google.com', { waitUntil: 'networkidle2' });
    await page.screenshot({ path: 'screenshots/google.jpg' });
  
    browser.close();
  } catch(error) {
    console.log('\n\nERROR:\n', error, '\n\n');
  }
})();
```

Setting ```{ headless: false }``` in ```puppeteer.launch``` options seems to work fine, but a browser instance is created, and this is not the desired result.

**What is the expected result?**
Chrome to run in headless mode and capture screenshot of Google landing page.

**What happens instead?**
Receive an error:

```
ERROR:
 Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\Users\DevUser1\Dev\HeadlessChromeTest\node_modules\puppeteer\lib\NavigatorWatcher.js:71:21)
    at <anonymous>
```

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with the puppeteer v1.1.1-post on Windows 7.

**Comment by luqimin** [comment]
I have the same problem with setting my windows as a wifi spot,
after turning off personal wifi, everything goes well

**Comment by jacobfike** [comment]
I am also seeing this problem.  Did not have issues yesterday, but today, every test times out.  With version 1.0.0 and 1.1.1.

**Comment by joshas** [comment]
Same issue on Windows 7 x64 with puppeteer 1.3.0, chromium version 67.0.3391.0, node v8.9.4 .

**Comment by aslushnikov** [comment]
I can't reproduce this. 

@jacobfike, @joshas: This issue seems to be too general. Please file a separate issue with a snippet that reproduces the issue for you.

**Comment by 0x1428571429** [comment]
me too

**Comment by hexad** [comment]
me too....

**Comment by dominicDeCoco-bravo** [comment]
me too...;(

**Comment by rostismal** [comment]
+1 same issue on pyppeteer 0.0.25(another repo, but result is same)

**Comment by den-cezar** [comment]
The same issue on puppeteer 1.11.0, maybe exist workaround ?

**Comment by ejames17** [comment]
me too same issue

**Comment by aslushnikov** [comment]
Everybody here: most likely when somethings works on headful, but doesn't work in headless, it means that the website you automate uses some bot evasion technique.

If you don't believe this is the case, please file separate issues with good reproduction scripts. We should be able to reproduce your problem locally to be able to debug and fix it.

Thanks!
