### ISSUE TITLE
Issue using waitforXPath Function

### ISSUE THREAD

**Issue by hisingla** [puppeteer/puppeteer#2153]
I am using page.waitForXPath function to wait for xpath to be loaded in the page. For some reason it is not working. Eg:
xpath : //*[@id="pt1:_UIScmil1u::icon"]
Function : page.waitForXPath('//*[@id="pt1:_UIScmil1u::icon"]');
Do we have some other method or function to handle or can we default the timeout.

**Comment by vsemozhetbyt** [comment]
@hisingla Should not this be `//*[@id="pt1:_UIScmil1u::icon"]` ?

**Comment by hisingla** [comment]
vsemozhetbyt even with //*[@id="pt1:_UIScmil1u::icon"] it doesn't work out. I am looking for a solution as soon as my xpath is available on the page, it should proceed further.

**Comment by vsemozhetbyt** [comment]
Can you provide a small complete code that reproduces the issue?

**Comment by UAVova** [comment]
Same issue. Function just immediately returns, even when XPath is not presisted on the page.
