### ISSUE TITLE
browser.on 'targetcreated' and page.waitForSelector() failure.

### ISSUE THREAD

**Issue by dhbahn** [puppeteer/puppeteer#2154]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.1.1
* Platform / OS version: macOS High Sierra v10.13.3
* URLs (if applicable):
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
(async() => {
    const browser = await puppeteer.launch({
        headless: false,
    });

    browser.on('targetcreated', async(target) => {
        console.log(`Created target type ${target.type()} url ${target.url()}`);
        if (target.type() !== 'page') {
            return;
        } else {
            var page = await target.page();
        }
        await page.waitForSelector('#SomeSelector');
    });
})();
```

**What is the expected result?**
Clicking a New Tab on a running Chromium browser will emit 'targetcreated' event, and I expect the normal page.waitForSelector() result like successful waiting or timeout, But ... 
 
**What happens instead?**
Created target type page url chrome://newtab/

(node:11194) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-Fl9ifwsOFaaBTg9WmeRGJRw8O0Xrn9qON++y9ixPeek=' 'sha256-KE4wd1GmLh7EIMfT+zNzX4kM3c6NNboIxfkXKPwbD90='".
    at new Function (<anonymous>)
    at waitForPredicatePageFunction (<anonymous>:2:21)
(node:11194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment]
This was fixed as a part of #1229; this will work as expected in the following version of pptr that will be released on April, 12.
