### ISSUE TITLE
Link in API Docs takes you to where you already are

### ISSUE THREAD

**Issue by jscottchapman** [puppeteer/puppeteer#2155]
### Steps to reproduce

Visit https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagexexpression

Then:

<img width="614" alt="puppeteerwheretoclick" src="https://user-images.githubusercontent.com/10002902/37102860-163ad1fa-21e6-11e8-9b8a-eef795d68e41.png">

**What is the expected result?**
We would go to the part of the page that has documentation about page.mainFrame().$x(expression).

**What happens instead?**
We go to the part of the page that we are already on:

<img width="1007" alt="puppeteerapilink" src="https://user-images.githubusercontent.com/10002902/37102869-1da27060-21e6-11e8-8214-7d0e65c0ea06.png">

**Comment by aslushnikov** [comment]
Seems to be working fine on current tip-of-tree.
