### ISSUE TITLE
Virtual keyboard overriding progressive web app

### ISSUE THREAD

**Issue by eeerrrttty** [puppeteer/puppeteer#2157]
Hello, i have a progressive web app in development, im using version 63.

When i open an input text field, my virtual keyboard push the DOM, resizing and making the size OK. 

When i open the PWA via home screen ícon and Go to an input text field, my virtual keyboard does not resize the DOM and hides the input, making the UI a mess

**Comment by JoelEinbinder** [comment]
Is this related to puppeteer?
