### ISSUE TITLE
Getting Errors when using Frame waitForSelector()

### ISSUE THREAD

**Issue by lems111** [puppeteer/puppeteer#2159]
* Puppeteer version: puppeteer@1.1.1-next.1520415469395
* Platform / OS version: 4.15.7-1-ARCH
* Bitbucket Repo: https://bitbucket.org/lems111/kshowscraperserver
* Node.js version: v9.5.0

**What steps will reproduce the problem?**

1. Run node server on local machine: pull source code from [repo](https://bitbucket.org/lems111/kshowscraperserver/src/8ad5d804897de354a4857bce548e57841c2b264f?at=master) and start node app (node server.js)
2. Run this URL in your local to call the API:
 http://localhost:3000/apis/kshow123/links?episode=http://kshow123.net/show/hyoris-bed-and-breakfast/episode-10.html&oneLink=true
3. You'll notice in logs that the process hangs with following error:
```
GetIframeData error:  Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/home/lems111/Dev/kshow-scraper-server/node_modules/puppeteer/lib/FrameManager.js:789:58)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

```
This is the selector that am using when it hangs in [streamer.js](https://bitbucket.org/lems111/kshowscraperserver/src/8ad5d804897de354a4857bce548e57841c2b264f/app/helpers/streamer.js?at=master&fileviewer=file-view-default#streamer.js-76):
```
urlElement = await iframeplayerFrame.waitForSelector(
            "#olvideo_html5_api[src]"
          );
```

**I'll be glad to provide more info to help resolve this error.**

**Comment by aslushnikov** [comment]
@lems111 that's a lot of code to go through; do you have a reduced test case?
