### ISSUE TITLE
How can i call custom js api which i defined in my target html

### ISSUE THREAD

**Issue by moreJs** [puppeteer/puppeteer#2160]
* Puppeteer version: 1.1.1 
* Platform / OS version: 
           ProductName:	Mac OS X
           ProductVersion:	10.13.1
           BuildVersion:	17B1003
* URLs (if applicable):
* Node.js version: v9.2.1

**What steps will reproduce the problem?**
1. i have a page, named 'www.xx.me/index.html' ,  this page looks like this :
```
  <html>
       <body>hello, puppeteer</body>
      <script>
            window.test = function() {
                  alert(123);
            }
     </script>
  </html>
  windo
```
2. when i use puppeteer, code looks like this:
```
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('www.xx.me/index.html');
    const executionContext = await page.mainFrame().executionContext();
    await executionContext.evaluate(
      () => {
        window.test();
      }
    );
```

**What is the expected result?**
alert(123) is excuted

**What happens instead?**
error: Cannot read property 'test' of undefined

**Comment by joelgriffith** [comment]
Have you attempted using just `page.evaluate(() => {...})` API? Globals should be accessible, and I’m wondering if the executionContext is being isolated from window

**Comment by moreJs** [comment]
@joelgriffith  it not work again.

**Comment by moreJs** [comment]
@joelgriffith  i am wondering if the pupputeer can not access custom js api in target page.

**Comment by g-plane** [comment]
I can't reproduce it.

![image](https://user-images.githubusercontent.com/17216317/37285997-a4e04a4e-263b-11e8-99c4-11a742d2c973.png)

```javascript
const puppeteer = require('puppeteer')

void (async () => {
  const browser = await puppeteer.launch({ headless: false })
  const page = await browser.newPage()
  await page.goto('http://localhost:8000/')
  const executionContext = await page.mainFrame().executionContext()
  await executionContext.evaluate(
    () => {
      window.test()
    }
  )
})()
```
