### ISSUE TITLE
Request interception not working in Chrome

### ISSUE THREAD

**Issue by Domysee** [puppeteer/puppeteer#2162]
### Steps to reproduce

Using the example code for intercepting requests, the request and response events are not fired if request interception is enabled. 

**Tell us about your environment:**

* Puppeteer version: 1.1.1 (also tested with @next)
* Platform / OS version: Windows 10 64 Bit
* URLs (if applicable): 
* Node.js version: 8.10.0 / 9.8.0
* Chrome version: 64.0.3282.186 64 Bit

**What steps will reproduce the problem?**

```
const PathToChrome = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe';
const Width = 1920;
const Height = 1080;
const LauchOptions = {
  executablePath: PathToChrome,
  headless: false,
  args: [`--window-size=${Width},${Height}`]
};
  const browser = await puppeteer.launch('localhost:3000');
  const page = await browser.newPage();
  page.setViewport({
    width: Width - 30,
    height: Height - 135
  });

  await page.setRequestInterception(true);
  page.on('request', request => {
    console.log('test');
  });
  page.on('response', response => {
    console.log('test');
  });
```

**What is the expected result?**

`test` should be printed to the console.

**What happens instead?**

Nothing. The events are not fired.

**Comment by vsemozhetbyt** [comment]
Without `executablePath` option the code seems to work. (`puppeteer.launch('localhost:3000')` should be `puppeteer.launch(LauchOptions)` though).

**Comment by Domysee** [comment]
Sorry, my bad, copy&paste error. I've actually had `puppeteer.launch(LauchOptions)`. 

You are right. Without `executablePath` it does work.  
The issue is that it doesn't work in Chrome, but it does in Chromium, which is the default as I understand it. Is it actually supposed to work in Chrome? I couldn't find any information on that.

**Comment by larryzhuo** [comment]
so, is there any solution, I need to use chrome to support video format, but chrome is not support puppeteer Request interception api

**Comment by larryzhuo** [comment]
It's work, if i set headless:true; so great

**Comment by Diokuz** [comment]
Have the same problem, and I cannot use Chromium, because (for reasons unknown) Chromium does not render any fonts (including devtools). So, I cannot use Chromium for debugging.

**Comment by aslushnikov** [comment]
@Domysee In every puppeteer release, we publish a version of chrome puppeteer is compatible with. For chrome 64, you can use [puppeteer@0.13.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v0.13.0).
