### ISSUE TITLE
Add FAQ for travis support

### ISSUE THREAD

**Issue by gauntface** [puppeteer/puppeteer#2164]
Add the puppeteer needs `puppeteer.launch({args: ['--no-sandbox']})`

**Comment by JoelEinbinder** [comment]
This is covered in the troubleshooting document:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues

**Comment by gauntface** [comment]
Looking at the PR - the term "Travis" isn't mentioned once.

Meanwhile you have:
- Heroku
- AWS Lambda
- Alpine
- Docker

**Comment by patrickhulce** [comment]
Travis is mentioned now can probably close this :)
