### ISSUE TITLE
Offset in screeenshot 

### ISSUE THREAD

**Issue by LutzStrobel** [puppeteer/puppeteer#2166]
* Puppeteer version:     "puppeteer": "^1.1.0",

* Platform / OS version: window 7
* URLs (if applicable):
* Node.js version: v8.9.3

**What steps will reproduce the problem?**
I have a simple express app using to experiment with gathering screenshot just like this:

```
app.get('/window', (req, res) => {
  let browser
  let page
  console.time('scrrenshot')
  puppeteer.launch({headless: false})
    .then((b) => {
      browser = b
      console.log('browser is', b.version())
      return b.newPage()
    }).then(p => {
      console.time('scrrenshot')
      page = p
      return page.goto('localhost:8080/anzeigeApp.html?device=ZA1_TYP5&nc=BRm', {waitUntil: 'load'})
    }).then((response) => {
      return page.waitForSelector('.anzeige', {visible: true})
        .then((element) => {
          return element.boundingBox()
        }).then((bbox) => {
          page.screenshot({
            clip: bbox,
            omitBackground: false
          }).then((buffer) => {
            console.timeEnd('scrrenshot')
            res.set('Content-Type', 'image/png')
            res.write(buffer, 'binary')
            res.end(null, 'binary')
            browser.close()
          })
        })
    })
})

````
**What is the expected result?**
I would expect an image which contains the selected element only.

**What happens instead?**
The created image contains the selected element but it has an offset in x ynd y  direction.
![image](https://user-images.githubusercontent.com/1766399/37169413-19995f38-2308-11e8-8142-9ec66d65c24f.png)

Whats wrong with my doing?
Can you help me?
Thanx
Lutz

**Comment by JoelEinbinder** [comment]
Can you try `element.screenshot()` and the `puppeteer@next` version? We recently changed the logic around element screenshots.

**Comment by LutzStrobel** [comment]
Sorry, but it didn´t changed anything. In between I have already updated the puppeteer version  to 1.1.1 and the change to element.screenshot didn´t changed anything.
The local chromium version from its manifest file is : 66.0.3347.0.

I will try if it is a "genuine" windows problem

**Comment by LutzStrobel** [comment]
I tried it on a linux machine. It seems to be a problem using puppeteer on windows 7.
Next try will be on windows 10.

**Comment by PavelZubkov** [comment]
hi, problem resolved?

**Comment by LutzStrobel** [comment]
Not sure.
Currently, i have the version 1.5.0 of puppeteer installed and I dont have that offset in the snapshot generated.
