### ISSUE TITLE
Does puppeteer support IPv6?

### ISSUE THREAD

**Issue by gauntface** [puppeteer/puppeteer#2169]
Just tried loading a page `http://[::]:<port>/` and page through the following error:

> /node_modules/puppeteer/lib/Page.js:520
>  Rejected promise returned by test. Reason:
>  Error {
>    message: 'net::ERR_ADDRESS_INVALID',
>  }

**Comment by JoelEinbinder** [comment]
Can you share you code? I couldn't reproduce with this code:
```js
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.goto('http://[::]:80/');
  await browser.close();
});
```
