### ISSUE TITLE
Request interception doesn't work with redirects

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#217]
The following script fails for me (since google.com redirects to www.google.com):

```js
(async() => {

const {Browser} = require('puppeteer');
const browser = new Browser();
const page = await browser.newPage();
await page.setRequestInterceptor(request => request.continue());
await page.navigate('https://google.com');
browser.close();

})();
```

**Comment by adam-s** [comment]
I still have this issue:
````
const puppeteer = require('puppeteer');

let cookies = [];

(async () => {
  const browser = await puppeteer.launch({
    devtools: true,
  });
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', async interceptedRequest => {
    // console.log(interceptedRequest.protoType);
    //await page.evaluate(`console.log(${interceptedRequest})`);
    // if (interceptedRequest.url().endsWith('.png') || interceptedRequest.url().endsWith('.jpg'))
    //   interceptedRequest.abort();
    // else
    //   interceptedRequest.continue();

    await interceptedRequest.continue();
  });
  await page.goto('http://localhost:4000', {waitUntil: 'networkidle2'});
  await page.type('#session_email', process.env.USER_NAME);
  await page.type('#session_password', process.env.PASSWORD);
  await Promise.all([
    page.click("[type=submit]"),
  ]);
  cookies = await page.cookies();
  console.log('cookies');
  // await browser.close();
})();
````

**Comment by l0nedigit** [comment]
@adam-s Did you ever find a solution for intercepting requests?

**Comment by adam-s** [comment]
Interesting my comment is from 2 years ago. Using page.on('request', () => {}) should work. https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-class-httprequest

What are you trying to accomplish?

**Comment by l0nedigit** [comment]
lol I know. Well, I have a scenario where a virtualhost on a
webserver doesn't resolve (on purpose).  The thought was to set the Host
header and just browse via IP (similar to python request
library/aiohttp/etc).  It works fine until I enter creds and hit enter.
After hitting enter the response is not caught, so the browser just sits
there hung.

Under the dev tools -> network tab, I see the redirect page as "pending".
I'll try your suggestion and keep trying if it doesn't work.
