### ISSUE TITLE
Can I get Remote Address with puppteer？

### ISSUE THREAD

**Issue by lexy0093** [puppeteer/puppeteer#2171]
Can I get Remote Address with puppteer？

**Comment by Cardoso222** [comment]
@lexy0093 can you give me one example of what you are trying to do?

**Comment by jamiepgs** [comment]
I think I'm looking for the same thing - When clicking on a request in the network tab in dev tools, under the Headers tab there is a Remote Address entry - which doesn't seem to be clearly exposed in the Response or Request classes.
