### ISSUE TITLE
Failed to download Chromium r536395! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by chiragbhansali** [puppeteer/puppeteer#2173]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: Not installed
* Platform / OS version: win10x64
* URLs (if applicable):
* Node.js version: 8.10.0

**What steps will reproduce the problem?**
I ran `npm install --save-dev puppeteer` and get a error message as follows:

```
ERROR: Failed to download Chromium r536395! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
npm WARN teamtreehouse@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**What is the expected result?**
Puppeteer gets installed

**What happens instead?**
It doesn't get installed and the error message appears

**Comment by vbeeb** [comment]
Getting the same issue on MacOS

**Comment by darkguy2008** [comment]
Same here. Unless I set the NODE_TLS_REJECT_UNAUTHORIZED variable as zero separately **before** running npm install, it won't work. Puppeteer's download system does not seem to honor strict-ssl or NODE_TLS_REJECT_UNAUTHORIZED in the .npmrc file, so my build system is stuck on this because there's no way for Node to set environment variables in a pre-install step for Puppeteer. Sucks big time.

**Comment by victor9000** [comment]
Same issue on Ubuntu

**Comment by zfisher91** [comment]
Same issue on Windows. Would be nice if Puppeteer respected strict-ssl options. Can't get out from behind our firewall. I've tried using a local install of chromium but then ran into issues with runaway processes.

edit: I can get everything to work locally if I use the release which Puppeteer tries to download. Go to https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/YOUR_RELEASE_HERE/chrome-win32.zip, replace your operating system with the correct one found on line 31 of https://github.com/GoogleChrome/puppeteer/blob/master/lib/BrowserFetcher.js and put it in your project root. Use the executablePath option in the API to point Puppeteer to the chrome executable in the files you just downloaded like so:
`const browser = await puppeteer.launch({executablePath: './chrome-win32/chrome.exe'});`

This gets around my problems with the UNABLE_TO_GET_ISSUER_CERT_LOCALLY flag being set by npm. I really think Puppeteer should respect the strict-ssl flag in .npmrc though.

**Comment by aslushnikov** [comment]
I will be happy to review a PR for this.

**Comment by MatejMecka** [comment]
Puppeter succesfully installed with the command in the issue
Node: v10.1.0
OS: Mac Os X High Sierra 10.13.3

Edit: Puppeter also succesfully installed itself on Ubuntu  4.10.0-42-generic using the above command
Node version: v9.3.0

**Comment by bardware** [comment]
I'm on Ubuntu bash on windows and try to install `glyphhanger`

```
root@PC-006:~# sudo npm install -g glyphhanger
/usr/bin/glyphhanger -> /usr/lib/node_modules/glyphhanger/cmd.js

> puppeteer@1.5.0 install /usr/lib/node_modules/glyphhanger/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/glyphhanger/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/glyphhanger/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-12T21_08_14_997Z-debug.log
```

**Comment by arisliang** [comment]
What is the domain the download goes to? Is it https://storage.googleapis.com? I may be able to try whitelist the domain to see whether it helps.

**Comment by aslushnikov** [comment]
@arisliang yes, the domain defaults to `https://storage.googleapis.com

https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-puppeteercreatebrowserfetcheroptions

**Comment by arisliang** [comment]
Yeah, confirmed it works after whitelist it.

**Comment by CyberLine** [comment]
same Problem as @bardware here:

```
/usr/bin/npm install --g penthouse

> puppeteer@1.5.0 install /usr/lib/node_modules/penthouse/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/penthouse/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/penthouse/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-18T08_58_27_069Z-debug.log
```

**Comment by naonak** [comment]
@aslushnikov How do you whitelist ?

**Comment by juanmonsalv3** [comment]
@arisliang can you provide any aditional info?

**Comment by arisliang** [comment]
@juanmonsalv3 Not much additional info other than after https://storage.googleapis.com is whitelisted by my network admin, it worked.

**Comment by xamgore** [comment]
```
sudo npm install -g puppeteer --unsafe-perm=true --allow-root
```

Solves the issue to me.

**Comment by juanmonsalv3** [comment]
@xamgore solution worked for me

**Comment by 1runningbird** [comment]
@xamgore solution worked for me

**Comment by AndrewHYi** [comment]
@xamgore solution worked, thanks!

**Comment by llccing** [comment]
same questions, i use `sudo cnpm install -g puppeteer --unsafe-perm=true --allow-root`

**Comment by celsobessa** [comment]
another one saved by @xamgore solution

**Comment by pcbimon** [comment]
@xamgore I used your command,but it's can't install show error ...
` sudo npm install -g puppeteer --unsafe-perm=true --allow-root`

`> puppeteer@1.14.0 install /usr/lib/node_modules/puppeteer`
`> node install.js`

`ERROR: Failed to download Chromium r641577! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.`

`{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/puppeteer/lib/helper.js:110:27)
    at Object.<anonymous> (/usr/lib/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  code: 'ECONNRESET',
  path: undefined,
  host: 'my-proxy.domain',
  port: 8080,
  localAddress: undefined }`
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.14.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.14.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by peterbowey** [comment]
Possibly "off topic" but worthy of a note:
It seems, for me, that using "**-unsafe-perm=true --allow-root**" works for a number of otherwise "broken"  NPM packages. I have likely lost count of the number of packages that show "Error: EACCES: permission denied". Anyway: Very true for Fedora 30 in this case attempting to install "puppeteer" = "chromium" with NPM 6.5.0

**Comment by zgyandy** [comment]
你可能使用了VPN，退出就好了。

**Comment by KBHE** [comment]
**For windows 10**
`export NODE_TLS_REJECT_UNAUTHORIZED=0 && npm install`
_it works for me_

**Comment by ponnuru** [comment]
Best Simplest Solution set the variable as true in local and proceed.
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn 
it works

**Comment by jhchill666** [comment]
FWIW, I had `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` set to `false`.  

As per this line https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L21, setting it to *anything* will prevent download of Chromium.

**Comment by tek-shiro** [comment]
Please try (on windows 10) on powershell
`$env:PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=0`
then run `npm install -g puppeteer --unsafe-perm=true --allow-root`

Your problem should get solved.

**Comment by mehramoh** [comment]
The best way is to export default env var `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`

`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn add puppeteer` or
`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install puppeteer`

**Comment by sfresta** [comment]
> ```
> sudo npm install -g puppeteer --unsafe-perm=true --allow-root
> ```
> 
> Solves the issue to me.

Works like a charm!

**Comment by blaggacao** [comment]
And what's the autorative solution to this issue? - no workarround.

**Comment by fireairforce** [comment]
I meet the same question,too

**Comment by marcioscf** [comment]
One way to resolve the problem, is to use firefox instead of chromium:
Install it with the command:
PUPPETEER_PRODUCT=firefox npm install puppeteer

And explicitly use the firefox browser when you want to use puppeteer:
puppeteer.launch(product: 'firefox');

**Comment by ThatAnonyG** [comment]
> ```
> sudo npm install -g puppeteer --unsafe-perm=true --allow-root
> ```
> 
> Solves the issue to me.
@xamgore
Absolute genius! Thanks man you were a life saver

**Comment by youranstray** [comment]
> Best Simplest Solution set the variable as true in local and proceed.
> PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn
> it works

Coooool！It worked for me!👏

**Comment by GMCoder** [comment]
> The best way is to export default env var `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`
> 
> `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn add puppeteer` or
> `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install puppeteer`

It worked for me, Thanks!

**Comment by richa18b** [comment]
> Best Simplest Solution set the variable as true in local and proceed.
> PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn
> it works

It works finally!
Thanks @ponnuru 👍

**Comment by afifalfiano** [comment]
> ```
> sudo npm install -g puppeteer --unsafe-perm=true --allow-root
> ```
> 
> Solves the issue to me.

Thanks, it works

**Comment by ya3ya6** [comment]
This command worked for me:
`$ export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=0 && export NODE_TLS_REJECT_UNAUTHORIZED=0 && npm i link-preview-generator --unsafe-perm=true`
(I used nodebash on windows)

**Comment by monkpit** [comment]
@aslushnikov this is closed but I am still encountering this 5 years later with latest versions of puppeteer (that are transitive dependencies, not even direct dependencies of my project).

It seems wrong to set puppeteer-specific environment vars in my project when I am not even using it.

Seems to me this should be reopened?
