### ISSUE TITLE
Is there any way to record video including audio?

### ISSUE THREAD

**Issue by awesomenkj** [puppeteer/puppeteer#2175]

**Comment by ebidel** [comment]
You can use the [screencast api[(https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast) in the raw devtools protocol, but that doesn't support audio.

This would probably be handled better by other software. I found https://www.npmjs.com/package/screencap, which looks like it might support desktop screen capture + audio using ffmpeg.

**Comment by purch-FE** [comment]
it is not allowing to generate a video from a headless chrome using a local html file is it ?

**Comment by aslushnikov** [comment]
Please follow/upvote #478 for the updates.

**Comment by Gummibeer** [comment]
I only found this gist, but haven't tested it: https://gist.github.com/muralikg/23cfed0b099b3df812bb2b27ba1be6a4

**Comment by Flam3rboy** [comment]
I've made a package for this https://www.npmjs.com/package/puppeteer-stream

**Comment by crisdosaygo** [comment]
The way I do it is run chrome headless on debian, then set up a pulseaudio daemon and then run parec to grab the audio stream from the default sink, then run lame to encode as an MP3.

**Comment by samuelscheit** [comment]
yeah but @i5ik solution can only record the whole window + audio and not only a certain tab

**Comment by crisdosaygo** [comment]
yes but @Flam3rboy it works with headless which https://github.com/Flam3rboy/puppeteer-stream does not

**Comment by guzzur** [comment]
> The way I do it is run chrome headless on debian, then set up a pulseaudio daemon and then run parec to grab the audio stream from the default sink, then run lame to encode as an MP3.

 Any chance you have a working example of this?

**Comment by crisdosaygo** [comment]
Yes @guzzur see [this search](https://github.com/i5ik/ViewFinder/search?q=lame) for an idea of some of the files touched by the audio code

and in general check out this repo: https://github.com/i5ik/ViewFinder

**Comment by goforbg** [comment]
> yes but @Flam3rboy it works with headless which https://github.com/Flam3rboy/puppeteer-stream does not

Thanks a lot this solved most of my problems.
