### ISSUE TITLE
Cannot use data attribute as selector.

### ISSUE THREAD

**Issue by lbeier** [puppeteer/puppeteer#2179]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.1
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version: 9.8.9

**What steps will reproduce the problem?**
Create an element with data attribute and uses puppeteer to find it within the page.

_Please include code that reproduces the issue._

**form.html**
```html
<form data-form="personal">
</form>
```

**form.spec.js**
```js
const formPersonal = await page.$('[data-form="personal"]');
console.log(formPersonal);
```

**What is the expected result?**
Puppeteer finds the element.

**What happens instead?**
Puppeteer returns `null`.

It's perfectly fine to use the `'[data-form="personal"]'` selector in the Chrome console:
<img width="441" alt="screen shot 2018-03-12 at 18 53 36" src="https://user-images.githubusercontent.com/607692/37300631-b846a3ae-2626-11e8-8b17-098c0bfdc2e1.png">

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with the `v1.1.1-post`: 
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.setContent('<form data-form="personal">test</form>');

    console.log(await page.evaluate(() => document.body.outerHTML));

    console.log(await page.evaluate(
      () => document.querySelector('[data-form="personal"]').innerText)
    );

    const elementHandle = await page.$('[data-form="personal"]');
    const jsHandle = await elementHandle.getProperty('innerText');
    const json = await jsHandle.jsonValue();
    console.log(json);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```console
<body><form data-form="personal">test</form></body>
test
test
```

**Comment by JoelEinbinder** [comment]
Are you sure that the form is in DOM and has the data attribute at the time your code runs? Maybe you want to use `waitForSelector`

**Comment by max-programming** [comment]
Interestingly, it doesn't work with the `page.$eval()` and `page.waitForSelector()` method but works with the `page.evaluate()` method when passed in to `querySelector()`
