### ISSUE TITLE
cannot add background color to Header/Footer

### ISSUE THREAD

**Issue by Guruhbk** [puppeteer/puppeteer#2182]
I'm trying to customize the header and footer. But I cannot add the background color to the footer. And footer size is not the same. 
This is what I'm trying to do. 
`page.pdf({
                        path: 'test.pdf',
                        format: 'a4',
                        landscape: '!data.isPortrait',
                        footerTemplate: '<div class="footer" style="height:75px;position: absolute;background-
                          color:red;top:auto;left:0px;right:0px;bottom:0px;">\
					</div>',
                        displayHeaderFooter: true,
                        margin: {
                            top: "75px",
                            bottom: "75px"
                        }
                    });`
* Puppeteer version:1.1.0
* Platform / OS version:ubuntu 16.04
* URLs (if applicable):
* Node.js version:8.9
**What is the expected result?**
Footer background color should be in red color.
**What happens instead?**
Footer background color is not changed.

**Comment by Guruhbk** [comment]
I found the solution. To add background-color to header/footer or to the entire page in Puppeteer, we need to add an additional css property,` -webkit-print-color-adjust: exact.` Now it works fine.

**Comment by mel-mouk** [comment]
If like it was for me, it's still not working for you, you have to add :
`await page.emulateMedia('screen');`
Before rendering your pdf

**Comment by atmortensen** [comment]
For people who find this from Google, you can also add `printBackground: true` https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions

**Comment by LastTribunal** [comment]
this page is misleading, because it gives the appearance that the best solution is at the top due to all the fanfare, but obviously the correct solution is from @arnemart which barely has any likes.  The OP should update his post with a pointer to it

**Comment by ngajhede** [comment]
> this page is misleading, because it gives the appearance that the best solution is at the top due to all the fanfare, but obviously the correct solution is from @arnemart which barely has any likes. The OP should update his post with a pointer to it

In some instances it doesn't work. For example, we use [https://github.com/spiritix/php-chrome-html2pdf](url) which utilizes Puppeteer. In our case, we had `printBackground: true` but to no luck, and it worked as soon as we applied the css rule that the top comment suggested.

**Comment by talski** [comment]
it appears that headerTemplate and footerTemplate do not follow page style, you need to explicitly set it,

```TS
await page.pdf({
      //...
      headerTemplate: `
        <style>
        html {
          -webkit-print-color-adjust: exact;
        }
        </style>
        <div style="background-color:red; font-size: 22px;">My Header</div>
    `,
      //...
});
...
```

**Comment by enoh-barbu** [comment]
> it appears that headerTemplate and footerTemplate do not follow page style, you need to explicitly set it,
> 
> ```ts
> await page.pdf({
>       //...
>       headerTemplate: `
>         <style>
>         html {
>           -webkit-print-color-adjust: exact;
>         }
>         </style>
>         <div style="background-color:red; font-size: 22px;">My Header</div>
>     `,
>       //...
> });
> ...
> ```

This is the only solution it worked for me
