### ISSUE TITLE
ReferenceError: $ is not defined; how to pass jquery $ object to javascript injector method?

### ISSUE THREAD

**Issue by voordev** [puppeteer/puppeteer#2183]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
Latest
* Platform / OS version:
OSX
* URLs (if applicable):
* Node.js version:
Latest

**What steps will reproduce the problem?**

```
 await page.addScriptTag({ content: `${functionToInject(codesChildArray)}`});
            var data =  await page.evaluate(function(codesChildArray){
            return functionToInject(codesChildArray);
            });
```

```
function functionToInject(codesChildArray){

    $( document ).ready(function() {
        console.log( "ready!" );
    });
    var myStringArray = ["Hello","World"];
    var arrayLength = myStringArray.length;
    for (var i = 0; i < arrayLength; i++) {
        console.log(myStringArray[i]);
    }

}
```

When Passing the ** codesChildArray** argument, it fails with an

> ReferenceError: $ is not defined

Without the argument it works fine as expected.
I need to Pass the array AND have jquery available true $
How can I make this work?

**Comment by voordev** [comment]
So Then there is a workaround I found posted in some of the comments:

```
            await page.evaluate(fs.readFileSync('injector.js', 'utf8'));
```

But now we have NO access to any variables defined in the nodejs application. 

Someone please tell me how I can have both , thus custom javascript injected and pass arguments to it!

**Comment by aslushnikov** [comment]
@voordev you should inject jquery separately into the page, then you'll be able to use it inside
functions you inject.

For example:
```js
await page.addScriptTag({url: 'https://code.jquery.com/jquery-3.3.1.slim.min.js'});
```

Hope this helps.

**Comment by uriya2** [comment]
hi @aslushnikov I was wondering how can I inject jquery using an alias different from $ or Jquery?
I've encountered situations when where injecting jquery but not not using an alias would mask failure of code. For example when jquery was removed a certain piece of code would still use work, a test would pass due to the injected jquery thus having tests pass when they should have failed.

**Comment by toygansevim** [comment]
@aslushnikov I am still getting $ not defined error even though I have used:
await
                    page.addScriptTag({url: 'https://code.jquery.com/jquery-3.2.1.min.js'});

**Comment by kevinashworth** [comment]
I've experienced a related issue with `lodash`. A `'_' is not defined` error happens immediately when I try to run my script from the CLI with `ndb` to try to debug it. But once I got the script working, `node script.js` will run it without errors. So it knows what `_` is sometimes, sometimes not.

**Comment by tim-kozak** [comment]
The best solution found so far, URL insertion may not work due to browser origin policies, so we insert local file contents instead of URL.

```
const fs = require('fs');
const path = require('path');

const addJQueryToPage = async (page) => {
    const file = fs.readFileSync(path.resolve(__dirname, 'jquery-file-in-same-directory.min.js'), 'utf8');
    await page.addScriptTag({ content: file });
    await page.evaluate(_ => {
        $.noConflict();
    });
}
```
