### ISSUE TITLE
waiting for googleads.g.doubleclick.net... This code worked perfectly up until a couple of hours ago. 

### ISSUE THREAD

**Issue by ramtinJ95** [puppeteer/puppeteer#2184]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
  **Latest**
* Platform / OS version:
  **macOS Sierra version 10.12.6**
* Node.js version:
 **Latest**

**What steps will reproduce the problem?**
I actually don't know,  this code has been working for 1 week but now all of a sudden it does not get the values any more. When I run it in headless mode: false, then I can see that it waits for:
 googleads.g.doubleclick.net...

**Code that reproduces the issue:**
```
const puppeteer = require('puppeteer');
var stockPrice, stockPriceResult;
var aktier = ["Saab B", "Volvo", "Hansa Medical", "Xspray Pharma", "Lyko Group A", "Kinnevik B", "Husqvarna B", "Boliden", "Holmen B"];

async function starter(){
   const browser = await puppeteer.launch({
    headless: false
  });
   const page = await browser.newPage();
  return page; 
}
async function run(searchString,page) {
 
  await page.goto('https://www.nordnet.se/mux/web/nordnet/index.html');
  
    await page.type('#searchQuery', searchString);
    await page.keyboard.press('Enter');
  
    const resultsSelector = '#search-results-container > div:nth-child(1) > span.last-price';
    await page.waitForSelector(resultsSelector);

    // Extract the results from the page.
    stockPrice = await page.evaluate((resultsSelector) => {
    const anchors = Array.from(document.querySelectorAll(resultsSelector));
    return anchors.map(anchor => {
      const title = anchor.textContent.split('|')[0].trim();
      return `${title} - ${anchor.href}`;
    });
     }, resultsSelector);
  
  return stockPrice.join('\n');
}
async function test(aktier){
	
  var returnArr = [];
  var page = await starter();
  for(var i = 0; i < aktier.length - 1; i++){
    var searchString = aktier[i]
    var x = await run(searchString, page);
    const decimal= /\d+\,\d+/;
    stockPriceResult = x.match(decimal);
   
    var tmp = {name: searchString, price: stockPriceResult[0]};
    returnArr.push(tmp);
  }
	return returnArr;
}
test(aktier);

 ```

**What is the expected result?**
The expected result is that it enters the searchstring in the given field takes out the number, then opens a new page of the new string and takes out the next number and so on. This has been working for over 1 week but all of a sudden this code broke :/  

**What happens instead?**
The code essentially just freezes and waits for this googleads.g.doubleclick.net thing and after some time it throws a navigation error.

**Comment by suever** [comment]
Google Ads had a global outage yesterday which is likely what caused your issues. It should be back online. Can you verify that your script is functioning again?

**Comment by ramtinJ95** [comment]
Just tested it again, it is indeed working! Just too be sure, is it possible that this happens again in the near future? Because I need this to work tomorrow when I demo this app! 

Also is there anything like puppeeter I can use that does not use google ads so I have a backup in the future in case it goes down? 

Thank you for all your help!

**Comment by suever** [comment]
You'd need to monitor their [status page](https://ads.google.com/status) to see if/when they are down.

Google Ads has nothing to do with puppeteer, and mainly has to do with the resources you are accessing. Maybe you could use puppeteer to `abort()` all requests to that domain using [request interception](https://github.com/GoogleChrome/puppeteer/blob/v1.1.1/docs/api.md#pagesetrequestinterceptionvalue)?

**Comment by ramtinJ95** [comment]
Yeh maybe I could do that, I'll look into it right away! Though I don't really know if it is possible since i am using chromium as my headless webbrowser.

But I guess this issue is dealt with so I'll close it now 👍
