### ISSUE TITLE
Splash screen with Web page

### ISSUE THREAD

**Issue by rageshpayyan** [puppeteer/puppeteer#2185]
This is the way our application is designed,  after login it will show splash page and application  in a new browser. The issue is when i use puppeteer to automate it uses splash screen instead of home (new browser page). If i close the splash page then our application close automatically. My Question is here , how to access the application page  using puppeteer instead of splash screen.

**Comment by rageshpayyan** [comment]
@ebidel Any help

**Comment by ebidel** [comment]
Sorry. This questions isn't appropriate for the issue tracker. Please ask a specific question on SO over the slack channel with code snippets.
