### ISSUE TITLE
Can't get the correct screenshot

### ISSUE THREAD

**Issue by KenFront** [puppeteer/puppeteer#2186]
* Puppeteer version: v1.1.1
* Platform / OS version: Homestead(Ubuntu 16.04.4)
* URLs (if applicable):  https://developer.mozilla.org/zh-TW/docs/Learn
* Node.js version:  v8.10.0

```javascript
const puppeteer = require('puppeteer')
    (async () => {
        const browser = await puppeteer.launch()
        const page = await browser.newPage()
        await page.goto('https://developer.mozilla.org/zh-TW/docs/Learn')
        await page.screenshot({ path: `resources/seller/e2e/result/test.png`})
        await browser.close()
    })()
```

The expected test.png as below
![2018-03-14 09 33 46](https://user-images.githubusercontent.com/21172279/37378753-7e045646-276b-11e8-9595-aad256640100.png)

But test.png display as below.
![test](https://user-images.githubusercontent.com/21172279/37379054-c5e369ec-276c-11e8-8702-91b0926598af.png)

It seems like the Unicode of Chromium isn't utf-8.

By the way,

I use mac to do same thing.
It works as expected.

* Puppeteer version: v1.1.1
* Platform / OS version: MacOS High Sierra 10.13.3
* URLs (if applicable):  https://developer.mozilla.org/zh-TW/docs/Learn
* Node.js version:  v8.10.0

**Comment by KenFront** [comment]
Sorry, it's my fault.
I do't install the font family in homestead.

**Comment by SidKwok** [comment]
@KenFront  I had the same issue. What font family did you install and how? Thx

**Comment by KenFront** [comment]
I  install Chinese language support.
This website show the  Asian language support.
I hope it will be helpful to you.
[Link](http://help.accusoft.com/PCC/v11.2/HTML/Installing%20Asian%20Fonts%20on%20Ubuntu%20and%20Debian.html)

**Comment by SidKwok** [comment]
It helps, thanks a lot!
