### ISSUE TITLE
page.waitForNavigation still not work

### ISSUE THREAD

**Issue by x-name** [puppeteer/puppeteer#2189]
* Puppeteer version: latest , github
* Platform / OS version: win 10, centos
* URLs (if applicable): doesn't matter, this also don't work for example on youtube.com
* Node.js version: 8.10, 8.4, 9.x

1. not working, stucking sometimes with infinity time
```
const loaded = page.waitForNavigation({
	timeout: 0,
	waitUntil: 'networkidle0',
});
mouse.click(...);
await loaded;
```
2. not working, stucking sometimes with infinity time
```
const loaded = page.waitForNavigation({
	timeout: 0,
	waitUntil: 'networkidle0',
});
await mouse.click(...);
await loaded;
```
3. not working, stucking sometimes with infinity time
```
mouse.click(...);
await page.waitForNavigation({
	timeout: 0,
	waitUntil: 'networkidle0',
})
```
4. Any other variant with Promise, etc also not working

If you set not null timeout, you give it works, but working only by ending timeout.

**Comment by AkliOnet** [comment]
I confirm. I Down't know why. 

Interception enabled.
Windows

**Comment by Zen0x7** [comment]
I've the same issue. did you fix that?

**Comment by aslushnikov** [comment]
Dupe of #257; feel free to star that issue to get updates.

**Comment by peteypivots** [comment]
have you tried increasing the timeout to like 30,000 ? (large number in milli) , also maybe do a waitForSelector command on the same identifier prior to doing the mouse click.

Headless chrome can be really finicky , ive found there are background sessions open still after terminating program which causes real problems at times. Anyway heres an example of how I do it.

	//wait for the class to load
	await mGlobalPage.waitForSelector('.Your__running___4321');  
	//once DOM is loaded run your query 
        await mGlobalPage.evaluateHandle((name)=>{
        
        document.querySelectorAll('.Your__running___4321')
        .forEach(function(e){
            
            e.childNodes.forEach(function(p){
            
              let your_name = p.firstChild.title;
              your_name = your_name.replace(/[0-9]/g, '').trim().replace(/'/g,'');
              if(your_name == name){
                   
                p.children[1].click();
                
                }
            });
        });
    },name);
