### ISSUE TITLE
How to check if “click” has finished in puppeteer ?

### ISSUE THREAD

**Issue by AnnaCICI** [puppeteer/puppeteer#2192]
I have an error during tab switch in puppeteer:

```
await page2.waitForSelector('#save');   
await page2.click('#save');  //for saving and closing the page
await page2.waitFor(4000);  // !!it will crash if I remove this line!!
const allPages = await browser.pages();
const page1 = await allPages[0];  
await page1.waitFor(5000);// change nothing even if I wait 10 seconds
await page1.waitForSelector("selector")//crash if I delete 3rd line 
```

When I run this code without the 3rd line, it triggers an error :

> error: Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed. at CDPSession.send(c:\path\node_modules\puppeteer\lib\Connection.js:172:29) at ExecutionContext.evaluateHandle (c:\path\node_modules\puppeteer\lib\ExecutionContext.js:56:77) at EventEmitter._document._documentPromise._contextPromise.then (c:\path\node_modules\puppeteer\lib\FrameManager.js:310:38)

And `page2.waitForNavigation` does not work for me, it freezes the page.

I wonder why it crashes if i not use the function : waitFor(4000) on page2 and if there is a way to automate the wait for not wasting time for nothing

Or maybe I should wait for page2 completely close after click a button?

**Comment by vivien7512** [comment]
what you want is to wait that a tab has closed before continue, isn't it?

**Comment by JoelEinbinder** [comment]
As you say clicking `#save` closes your page. But closing a page does not happen synchronously, so you have a race between when the page closes and when you find the page through `browser.pages()`. If the page has not closed yet, you are trying to work with the page that is about to close.

Instead of `waitFor(4000)`, you can use
```js
await new Promise(x => browser.on('targetdestroyed', target => target === page2.target() && x()))
```
