### ISSUE TITLE
browser.pages() recreates page objects and doesn't copy exposed functions

### ISSUE THREAD

**Issue by itaylor** [puppeteer/puppeteer#2197]
### Steps to reproduce

* Puppeteer version: 1.1.1
* Platform / OS version: Linux/Docker
* Node.js version: 8.10.0

**What steps will reproduce the problem?**

I'm using puppeteer in a white-box integration testing use case.  I'm using `page.exposeFunction` to add a function to the page that my app will call periodically when it's in test mode to pass data to the test runner to give the test runner more info about the app state.  This works great.

However, if I later have some other code that uses the `browser.pages()` to look up a page that I've previously used `page.exposeFunction` on, the instances of what are ostensibly the same page (but are actually new instances from the same target) are missing their `this._pageBindings` property.   From this point on, when the app tries to call the exposed function, `Page.js`s  line 415 `this._pageBindings[name](...args);` will throw an error because the page bindings don't exist for this new instance of the page.

I can try to find time to build a clean repro case if the above was difficult to understand.  

My thinking is that instead of having `browser.pages()` recreate the page objects when it's called, it would be a lot simpler if puppeteer just held an array/set of all the current pages and returned it, but that may be naive on my part.

**Comment by aslushnikov** [comment]
> My thinking is that instead of having browser.pages() recreate the page objects when it's called, it would be a lot simpler if puppeteer just held an array/set of all the current pages and returned it, but that may be naive on my part.

We already do this:
https://github.com/GoogleChrome/puppeteer/blob/5089d2ec2e6652a04f6d01a8beb813857dae35ca/lib/Target.js#L38-L44

Something's different should be going on in your case. I'll close this for now, feel free to re-open/re-file if there's a good repro we can play with.

**Comment by itaylor** [comment]
Fair enough, I'll make simple repro case and then reopen this ticket, because it's definitely a real bug that results in very unpredictable behavior. 

Additionally, I think my initial statement was misunderstood.  The code you highlighted above shows `target.page()` recreating the page each time.  That's exactly what I'm saying the problem is.

https://github.com/GoogleChrome/puppeteer/blob/5089d2ec2e6652a04f6d01a8beb813857dae35ca/lib/Browser.js#L132-L134

When you call `browser.pages()` it calls to `target.page()` for each target, which means you get back a new instance of `page` each time you call `browser.pages()`.    Those new instances of a page don't preserve all the internal state of the page object, especially the `this._pageBindings`

**Comment by aslushnikov** [comment]
> Additionally, I think my initial statement was misunderstood. The code you highlighted above shows target.page() recreating the page each time.

@itaylor on the contrary, the highlighted code caches the page. The caching is somewhat not obvious: instead of caching the actual page, we cache the promise that creates it, but that's a common pattern.

It's easy to check that `target.page()` doesn't recreate the page:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  const anotherPage = await page.target().page();
  // prints "true". It'd print "false" if target.page() recreated a page.
  console.log(page === anotherPage);
  await browser.close();
})();
```
