### ISSUE TITLE
Unable to get elements within iFrame

### ISSUE THREAD

**Issue by anandanguru** [puppeteer/puppeteer#2199]
I want to button click event for the selector which is actually inside iframe.Its always exceeds the timelimit means that the selector is not found...I am trying this one...

   await page.waitForSelector('#iFrameId',{visible:true,timeout:45000});
   await page.mainFrame().waitForSelector('#buttonId'); // I am getting the timelit error..

And so...Is there any way that which frame selected by page.mainFrame()??

**Comment by vsemozhetbyt** [comment]
@anandanguru 
Maybe instead of `page.mainFrame().waitForSelector()` you could find the needed frame by iterating over `page.mainFrame().childFrames()` and checking `frame.name()` or `frame.url()` and then use `foundFrame.waitForSelector()`.

**Comment by anandanguru** [comment]
I am getting null value while using frame.name()...I think its not setting  proper iframe may be...If I am using page.frames()..The selector id of iFrames is note there from the list..Any way to set Page.frames based on id???

Note : IFrame I am using which is actually in modal page..Is that any difference???

**Comment by vsemozhetbyt** [comment]
Can you provide a small code (with real page URL) which reproduces the issue?

**Comment by adrianopons** [comment]
Give a try on @schelkun solution at this post: https://github.com/GoogleChrome/puppeteer/issues/433#event-1490301931

**Comment by anandanguru** [comment]
Thanks @adrianopons ..The problem is frames are not loaded fully...#1361 solves me my solution...

**Comment by kardrean** [comment]
consegiu resolver o problema, estou tentando fazer a mesma coisa, tendo de um modal iframe.
![modal](https://user-images.githubusercontent.com/40957164/62797410-09a0f800-bab2-11e9-80fe-c2b30e87aff1.png)
![modal](https://user-images.githubusercontent.com/40957164/62797461-2e956b00-bab2-11e9-988b-cfd0ab235b0b.png)
