### ISSUE TITLE
page.waitForFunction does not support disable timeout

### ISSUE THREAD

**Issue by vc1** [puppeteer/puppeteer#2200]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.1

`page.goto`  support disable timeout. The usage of `timeout` is not the same
Need:  pass 0 to disable timeout  wait forerve

**Comment by yanivefraim** [comment]
I'll be happy to take this one (:

@aslushnikov @vc1

**Comment by aslushnikov** [comment]
@yanivefraim please go ahead!
