### ISSUE TITLE
[Issue] PDF Reverse Words

### ISSUE THREAD

**Issue by vinkla** [puppeteer/puppeteer#2206]
**Tell us about your environment:**

* Puppeteer version: v1.1.1
* Platform / OS version: macOS 10.13.3 (17D102)
* Node.js version: v9.8.0

I'm using Bootstrap 4.0.0 to create printable PDF templates in the browser. I'm using Puppeteer to generate the PDFs. It is working and looking great when I in the browser but when I copy text from the generated PDF file and paste it into my text editor all words are reversed.

<img width="1197" alt="screen shot 2018-03-15 at 4 52 25 pm" src="https://user-images.githubusercontent.com/499192/37474721-51af2e84-2871-11e8-8d7e-eef73e9a7185.png">

[I previously though this was an issue with Bootstrap.](https://github.com/twbs/bootstrap/issues/25861) Though, after som testing with in other browsers I narrowed it down to Google Chrome. It works fine in both Firefox and Safari.

Is this something that has come up before? Is this the expected behaviour?

**Comment by aslushnikov** [comment]
@vinkla no, I haven't seen this before. I'd recommend filing this upstream to the chromium repository: https://crbug.com/new

**Comment by vinkla** [comment]
@aslushnikov thanks for getting back. I'll check it out.

**Comment by daguej** [comment]
@vinkla Did you end up filing a Chrome issue?  I can't find one.

Also, having the same problem -- did you end up finding a fix or workaround?

**Comment by vinkla** [comment]
I didn't end up creating an issue. Didn't find a fix for it. It seems to still be an issue in the latest version of Puppeteer and Chrome.

**Comment by VitaliyR** [comment]
It's indeed an issue still, words are reversed and text selection box is below the actual text :(

Update:

It seems happens to me when using custom font.

**Comment by vinkla** [comment]
> It seems happens to me when using custom font.

Does with work with default system fonts?

**Comment by VitaliyR** [comment]
@vinkla Yes, and it also reproduces when printing to PDF via Chrome itself

**Comment by VitaliyR** [comment]
Ok, so it was an issue with my font. It looks fine when in the web, but, suddenly, somehow breaks when it's embed in the PDF. Should I provide it so it might help to fix the bug?

**Comment by justjake** [comment]
@VitaliyR I'm having the same issue and am interested in a test-case we can submit upstream to Chromium.

**Comment by VitaliyR** [comment]
@justjake I can search & provide these fonts here, which breaks pdf render, if you want.

**Comment by hichamnaimi** [comment]
I still have reversed words in generated PDF too

**Comment by d3skdev** [comment]
Same issue while using fonts with `woff` format.
using `ttf` font type, fixed the issue.

**Comment by cyounkins** [comment]
I encountered this while backing up a Wordpress site.

My workaround was this: `await page.addStyleTag({content: '* { font-family: sans-serif !important }'})`
