### ISSUE TITLE
Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!

### ISSUE THREAD

**Issue by KimSeongIl** [puppeteer/puppeteer#2207]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: ubuntu 16.04 (docker)
* URLs (if applicable):
* Node.js version: 8.9.4
chromium version: google-chrome-stable : 65.0.3325.162 

**What steps will reproduce the problem?**

I have the following code.
```
const options = { args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu', '--disable-dev-shm-usage'] };

await puppeteer.launch(options);
```

```
Fri Mar 16 2018 08:27:05 GMT+0000 (UTC) - error: [3]  Error: Failed to launch chrome!
[0316/082705.295375:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.
Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/kakao/service/htmltojpg/node_modules/puppeteer/lib/Launcher.js:246:14)
    at ChildProcess.helper.addEventListener (/kakao/service/htmltojpg/node_modules/puppeteer/lib/Launcher.js:236:60)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
W0316 17:26:20.877745 24163 logging.cpp:91] RAW: Received signal SIGTERM from process 2242 of user 0; exiting
```

What causes the above error?

**Comment by tsuna** [comment]
It's a glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=19329, I ran into it today using Puppeteer as well.

**Comment by tsabbay** [comment]
> It's a glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=19329, I ran into it today using Puppeteer as well.

Got it today, on node 12.7!

**Comment by Creepypoke** [comment]
> > It's a glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=19329, I ran into it today using Puppeteer as well.
> 
> Got it today, on node 12.7!

Same on node 10.16.0

**Comment by tsabbay** [comment]
> > > It's a glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=19329, I ran into it today using Puppeteer as well.
> > 
> > 
> > Got it today, on node 12.7!
> 
> Same on node 10.16.0

4yrs...same bug.....

**Comment by Creepypoke** [comment]
This bug manifests itself very randomly for me, and only in Jenkins on build process, but local all is fine. I guess it related with build platform resources, and add argument `'--disable-dev-shm-usage'` from [this page](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#tips) like this:

```new Puppeteer: { ..., args: ['--disable-dev-shm-usage'] }```

So far it works fine

**Comment by r-oldenburg** [comment]
Does not help here... Very annoying as this is happening quite often now on our CI system. Any other idea on how to fix / workaround this?

**Comment by josephrocca** [comment]
Been getting this error the past few days too. @aslushnikov should this one be re-opened? Or is it closed because it's upstream and nothing can be done?

**Comment by RyanBlundell** [comment]
I have also been getting this error recently. I have just updated ubuntu from 16.04 to 18.04, not sure if it is related

**Comment by tsabbay** [comment]
Thanks for your updated! we wanted to update as well but after reading...
you seem to save us some time.
Q: Are you using a lot of puppeteer launch?
We saw that it's happening when having a lot of launches, and we tried to
change to connect(and for few days we didn't see this error, I will update
in 2-3 weeks, as this comes and goes...

**Comment by RyanBlundell** [comment]
> Thanks for your updated! we wanted to update as well but after reading... you seem to save us some time. Q: Are you using a lot of puppeteer launch? We saw that it's happening when having a lot of launches, and we tried to change to connect(and for few days we didn't see this error, I will update in 2-3 weeks, as this comes and goes... .

Thanks for your update. I am also testing your theory by reducing the number of launch / browser closes in my loop.

Instead of running it for each page, I am running a launch / close for every 10 pages. Seems to have helped however I am still testing.

**Comment by RyanBlundell** [comment]
Just to follow up. Although reducing the frequency of calls to launch has reduced the number of times that I encounter this bug it still happens quite frequently (around 8-10 times a day)

**Comment by r-oldenburg** [comment]
This bug still occurs, at the moment *very* often. 

We are using backstop on docker and I tried already with the setting "--disable-dev-shm-usage" as advised here but that does not seem to help.

It does seem to help, when I reduce "asyncCaptureLimit" as this limits the number of concurrently running chrome instances. But that of course extremely slows the whole thing...

Very frustrating...

**Comment by r-oldenburg** [comment]
And why is this issue even closed?! It is not solved yet and the upstream bug exists for years now...!

**Comment by serzhb** [comment]
Same issue, puppeteer 1.20.0, node 10.
When I launch multiple chromium instances simultaneously, sometimes one of them fails:

````Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
at onClose (/home/pptruser/app/node_modules/puppeteer/lib/Launcher.js:348:14)
at ChildProcess.helper.addEventListener 
(/home/pptruser/app/node_modules/puppeteer/lib/Launcher.js:338:60)
at ChildProcess.emit (events.js:203:15)
at ChildProcess.EventEmitter.emit (domain.js:448:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)````

**Comment by tsabbay** [comment]
We thought we have resolved this by working with 1 instance, but after 5 weeks, this is back!
Single Instance used
5:31 +00:00: Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
15:31 +00:00: 
15:31 +00:00: 
15:31 +00:00: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
15:31 +00:00: 
15:31 +00:00:     at onClose (/opt/formtitan/docker-node-workflow/application/node_modules/puppeteer/lib/Launcher.js:349:14)
15:31 +00:00:     at ChildProcess.<anonymous> (/opt/formtitan/docker-node-workflow/application/node_modules/puppeteer/lib/Launcher.js:339:60)

**Comment by storenth** [comment]
> We thought we have resolved this by working with 1 instance, but after 5 weeks, this is back!
> Single Instance used
> 5:31 +00:00: Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
> 15:31 +00:00:
> 15:31 +00:00:
> 15:31 +00:00: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 15:31 +00:00:
> 15:31 +00:00: at onClose (/opt/formtitan/docker-node-workflow/application/node_modules/puppeteer/lib/Launcher.js:349:14)
> 15:31 +00:00: at ChildProcess. (/opt/formtitan/docker-node-workflow/application/node_modules/puppeteer/lib/Launcher.js:339:60)

same thing,
![chrome_inconsistency](https://user-images.githubusercontent.com/18244131/68465682-807e9600-0245-11ea-92dd-1077301d82e1.png)

**Comment by tsabbay** [comment]
Yes, same here, BUT at least its happening much less.
what we did was to add try/catch as a nice fallback.

**Comment by kowalk** [comment]
Same here :( it's failing randomly during CI build:
![Screenshot from 2019-12-16 14-48-53](https://user-images.githubusercontent.com/2781079/70912296-f085f600-2013-11ea-814e-f56d8f325251.jpg)

**Comment by peterschrott** [comment]
Same here: Error happens randomly. 

Docker base image node:13 (Debian 9, Node 13), Pptr 2.1.0

![image](https://user-images.githubusercontent.com/3984741/73437407-8f5c7c80-434c-11ea-8f12-00a357ef0193.png)

**Comment by Kikobeats** [comment]
I created a new issue, trying to collect information in order to determinate why this is happening https://github.com/puppeteer/puppeteer/issues/5476

**Comment by vazgen6** [comment]
`Failed to launch the browser process!
Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
`

Same happened to me today for the first time, I have puppeteer 3.0.0
Never seen this error locally, happened on Ubuntu 18.04 server.

**Comment by jribbens** [comment]
Why is this bug closed given it is still happening?

**Comment by The-Compiler** [comment]
@jribbens Because the bug is in glibc: https://sourceware.org/bugzilla/show_bug.cgi?id=19329

**Comment by jribbens** [comment]
@The-Compiler Given that the libc bug, going by the looks of that ticket, will never be fixed, isn't there some work-around that can be used on this side?

**Comment by The-Compiler** [comment]
@jribbens There's some recent activity there at least. I doubt there's any way around it - I see it without Puppeteer involved in my own project (qutebrowser, which is based on QtWebEngine, which is based on Chromium) as well.

**Comment by Truth1984** [comment]
same issue, seems like you have to upgrade `glibc` version, and maybe you need to upgrade your system: https://packages.ubuntu.com/search?keywords=libc6. Am running on bionic (with glibc-2.27, puppeteer-1.12.0),gonna wait few days to test it out.

**Comment by kyrylo-pshenychnyi** [comment]
@Truth1984 hi there. Did the new glibc version help you?

**Comment by Truth1984** [comment]
@kyrylo-pshenychnyi 
I found few solutions:
1. Move project to docker 
2. Download latest glibc library 
3. Use only one browser instance.
4. Use chrome instead of chromium.

**Comment by kyrylo-pshenychnyi** [comment]
@Truth1984 
Thank you!

**Comment by kyrylo-pshenychnyi** [comment]
@Truth1984 
Could you please tell the version of glibc where this has been fixed?

**Comment by Truth1984** [comment]
@kyrylo-pshenychnyi 
According to the first response.
glibc-2.30 fixed it.
(You can’t install that version with an old OS, so you can either upgrade your os or install necessary dependencies and hope it works)

**Comment by laurentdebricon** [comment]
Fresh default Ubuntu 20.04 server,
Ubuntu `GLIBC 2.31-0ubuntu9`

i have this crash regulary ... 2.31 > 2.30

**Comment by JorisVanEijden** [comment]
No, this issue has not been fixed in glibc and it is not likely it ever will be (from reading all the posts about it on the glibc development mailing list (libc-alpha) over the past 5 years).
It is a race condition occurring  when starting and stopping many threads/processes at the same time.
Even if this bug ever gets fixed there may be other temporary reasons for the spawning of a browser process to fail.

Since in this case there is not actually anything wrong with the process we're trying to start, a retry attempt may be successful.
This is what I have hacked together locally for my backstopjs testing purposes.
However, I am not a puppeteer, node or even javascript developer so I'd appreciate it if someone else could create a PR with an optional, configurable retry mechanism for starting browsers.

**Comment by sandeepthukral** [comment]
> No, this issue has not been fixed in glibc and it is not likely it ever will be (from reading all the posts about it on the glibc development mailing list (libc-alpha) over the past 5 years).
> It is a race condition occurring when starting and stopping many threads/processes at the same time.
> Even if this bug ever gets fixed there may be other temporary reasons for the spawning of a browser process to fail.
> 
> Since in this case there is not actually anything wrong with the process we're trying to start, a retry attempt may be successful.
> This is what I have hacked together locally for my backstopjs testing purposes.
> However, I am not a puppeteer, node or even javascript developer so I'd appreciate it if someone else could create a PR with an optional, configurable retry mechanism for starting browsers.

Can you please share how you implemented a 'retry' for backstop? In our pipelines this often fails. Do you retry the complete suite or the individual test for which error happens?

**Comment by pxlrbt** [comment]
Apparently this was fixed just a month ago: https://sourceware.org/bugzilla/show_bug.cgi?id=19329
~~Still need to try it out.~~ Release of glibc 2.34 should be released as a dev version [around August 1st 2021](https://www.gnu.org/software/libc/)

**Comment by aditodkar** [comment]
Facing same problem. I am using node -v 16.19.0 with 4GB RAM VPS node+PM2 server. Is this due to some memory issue? How can I debug to understand what exactly is happening? I am running 3 pages per chrome instance. Will increasing it to 5 or 8 help? Any suggestions?
