### ISSUE TITLE
Why is Puppeteer prepending "JSHandle:"?

### ISSUE THREAD

**Issue by kaycebasques** [puppeteer/puppeteer#2208]
1. Go to https://jshandle-why.glitch.me/PerformanceTiming
1. Look at results. Why is each prepended with `JSHandle:`?

```
app.get("/:interface", async (request, response) => {
  try {
    const browser = await puppeteer.launch({
      args: ['--no-sandbox']
    });
    const page = await browser.newPage();
    await page.goto(`https://developer.mozilla.org/en-US/docs/Web/API/${request.params.interface}`);
    const headers = await page.$$('#compat-desktop th');
    const browsers = [];
    for (let i = 0; i < headers.length; i++) {
      const header = await headers[i].getProperty('textContent');
      const name = await header.toString();
      browsers.push(name);
    }
    const string = browsers.concat(' ');
    response.send(string);
    await browser.close();
  } catch (error) {
    response.status(503).end(error.message);
  }
});
```

Code source: https://glitch.com/edit/#!/jshandle-why?path=server.js

**Comment by kaycebasques** [comment]
Looks like I need to do something like this:

```
      const content = await headers[i].getProperty('textContent');
      const value = await content.jsonValue();
      browsers.push(value);
```

That `jsonValue()` name is unintuitive. I overlooked it because I was expecting it to return a JSON object. I think a name like `toJsonSafeValue()` would reflect its purpose better...

**Comment by Swiffers** [comment]
@kaycebasques is right. `jsonValue()` name is unintuitive. I also overlooked it because I was expecting it to return a JSON object. 

**What is the reason** for `getProperty` to return something != then the value of the property?
```
const linkSelector = await mailFrame.waitForSelector('a[href*="example.com/foo"]');
const linkProperty = await linkSelector.getProperty('href');
const href = await linkProperty.jsonValue();
console.log(href);
```
**Result:** `http://example.com/foo?bar=1`

**Comment by aslushnikov** [comment]
> What is the reason for getProperty to return something != then the value of the property?

In general, properties might be non-serializable objects.
