### ISSUE TITLE
Resources required: puppeteer/chrome vs phantomjs

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#2211]
I've read a few reports (e.g. [this](https://hackernoon.com/benchmark-headless-chrome-vs-phantomjs-e7f44c6956c)) which suggest quite clearly that headless chrome uses less resources (CPU, RAM) and is quicker than phantomjs.

However, I'm finding the opposite.  I need to spin up roughly twice the resources (RAM and CPU) to process and render the same pages per sec for puppeteer/chrome as I do for phantomjs.  I haven't done any scientific comparison... I've just found that I need to deploy more server resources in order to keep up with the same request load.

I've tried using multiple chrome (browser) instances and processing pages in parallel, I've tried using multiple pages per browser, I've tried a combination of those, I've tried re-using pages (not closing/opening/closing/opening... just opening and then re-using).  But whatever I do, I find that chrome requires more resources.

I'm not doing anything particularly different to what is documented, i.e. `puppeteer.launch()` (or `puppeteer.connect()`), `browser.newPage()`, `page.goto()`, `page.screenshot()`... there isn't too much you can do differently.

Apart from the different rendering engine (chrome vs phantomjs), another thing I'm doing differently is how I send the result back to the client, and I'm wondering if that has an effect (and whether I'm doing it correctly).  With phantomjs I am saving the png to a file, and then doing `res.sendFile()`.

With puppeteer, I'm using a buffer... something like:

	const takeScreenshot = function (page, chartWidth, chartHeight) {
		const clip = { x: 0, y: 0, width: chartWidth, height: chartHeight };
		return page.screenshot({ omitBackground: true, clip: clip });
	};

	const sendResultsToClient = function (res, screenshotBuffer) {
		res.header('Content-Type', 'image/png');
		res.send(screenshotBuffer);
	};

	const screenshotBuffer = await takeScreenshot(page, chartWidth, chartHeight);
	sendResultsToClient(res, screenshotBuffer);
	await page.close();

Is there obviously anything flawed with the above approach?  Anyone else finding that chrome is needing more resources than phantomjs?

**Comment by michaeldrouin** [comment]
from my own independent testing, i've also found that headless chrome is using at least double the memory that phantomjs was to do the same tasks.

**Comment by drmrbrewer** [comment]
@michaeldrouin what about CPU?

**Comment by michaeldrouin** [comment]
@drmrbrewer  to be honest, i for some reason didn't measure CPU, so i'm not too sure. i ran the tests about 2 months ago.

**Comment by Llbe** [comment]
I'm generating PDFs with Phantomjs (2.1) and Puppeteer/Chrome (v1.6.0 with Node 10.6.0). From my data, Phantomjs is considerably faster with the same page. Of course this is only a single result but FWIW I get these results consistently:

  /tmp/pc:		User time (seconds): 0.29
  /tmp/pc:		User time (seconds): 0.39
  /tmp/pc:		User time (seconds): 0.41
  /tmp/pc:		User time (seconds): 0.44
  /tmp/pc:		User time (seconds): 0.42
  /tmp/pc:		User time (seconds): 0.38
  /tmp/pc:		User time (seconds): 0.42
  /tmp/pc:		User time (seconds): 0.47
  /tmp/pc:		User time (seconds): 0.37
  /tmp/pc:		User time (seconds): 0.38
  /tmp/pc:		User time (seconds): 0.37
  /tmp/pc:		User time (seconds): 0.45
  /tmp/pc:		User time (seconds): 0.40
  /tmp/phantom:		User time (seconds): 0.09
  /tmp/phantom:		User time (seconds): 0.15
  /tmp/phantom:		User time (seconds): 0.13
  /tmp/phantom:		User time (seconds): 0.14
  /tmp/phantom:		User time (seconds): 0.15
  /tmp/phantom:		User time (seconds): 0.14
  /tmp/phantom:		User time (seconds): 0.14
  /tmp/phantom:		User time (seconds): 0.12
  /tmp/phantom:		User time (seconds): 0.16
  /tmp/phantom:		User time (seconds): 0.14
  /tmp/phantom:		User time (seconds): 0.16
  /tmp/phantom:		User time (seconds): 0.12
  /tmp/phantom:		User time (seconds): 0.15
  /tmp/phantom:		User time (seconds): 0.12
  /tmp/pc:		System time (seconds): 0.09
  /tmp/pc:		System time (seconds): 0.13
  /tmp/pc:		System time (seconds): 0.08
  /tmp/pc:		System time (seconds): 0.08
  /tmp/pc:		System time (seconds): 0.09
  /tmp/pc:		System time (seconds): 0.07
  /tmp/pc:		System time (seconds): 0.11
  /tmp/pc:		System time (seconds): 0.08
  /tmp/pc:		System time (seconds): 0.08
  /tmp/pc:		System time (seconds): 0.10
  /tmp/phantom:		System time (seconds): 0.01
  /tmp/phantom:		System time (seconds): 0.02
  /tmp/phantom:		System time (seconds): 0.01
  /tmp/phantom:		System time (seconds): 0.03
  /tmp/phantom:		System time (seconds): 0.02
  /tmp/phantom:		System time (seconds): 0.01
  /tmp/phantom:		System time (seconds): 0.02
  /tmp/phantom:		System time (seconds): 0.01
  /tmp/phantom:		System time (seconds): 0.02
  /tmp/pc:		Percent of CPU this job got: 71%
  /tmp/pc:		Percent of CPU this job got: 62%
  /tmp/pc:		Percent of CPU this job got: 72%
  /tmp/pc:		Percent of CPU this job got: 73%
  /tmp/pc:		Percent of CPU this job got: 67%
  /tmp/pc:		Percent of CPU this job got: 74%
  /tmp/pc:		Percent of CPU this job got: 68%
  /tmp/pc:		Percent of CPU this job got: 76%
  /tmp/pc:		Percent of CPU this job got: 70%
  /tmp/pc:		Percent of CPU this job got: 64%
  /tmp/pc:		Percent of CPU this job got: 74%
  /tmp/phantom:		Percent of CPU this job got: 100%
  /tmp/phantom:		Percent of CPU this job got: 99%
  /tmp/phantom:		Percent of CPU this job got: 97%
  /tmp/phantom:		Percent of CPU this job got: 99%
  /tmp/phantom:		Percent of CPU this job got: 97%
  /tmp/phantom:		Percent of CPU this job got: 99%
  /tmp/phantom:		Percent of CPU this job got: 97%
  /tmp/phantom:		Percent of CPU this job got: 99%
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.54
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.83
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.69
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.70
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.73
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.62
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.74
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.72
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.69
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.85
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.61
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.63
  /tmp/pc:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.72
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.12
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.18
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.16
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.15
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.17
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.15
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.20
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.16
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.19
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.15
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.17
  /tmp/phantom:		Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.15
  /tmp/pc:		Maximum resident set size (kbytes): 72684
  /tmp/pc:		Maximum resident set size (kbytes): 71952
  /tmp/pc:		Maximum resident set size (kbytes): 72640
  /tmp/pc:		Maximum resident set size (kbytes): 74560
  /tmp/pc:		Maximum resident set size (kbytes): 71844
  /tmp/pc:		Maximum resident set size (kbytes): 69472
  /tmp/pc:		Maximum resident set size (kbytes): 71776
  /tmp/pc:		Maximum resident set size (kbytes): 72528
  /tmp/pc:		Maximum resident set size (kbytes): 71572
  /tmp/pc:		Maximum resident set size (kbytes): 72420
  /tmp/pc:		Maximum resident set size (kbytes): 72732
  /tmp/pc:		Maximum resident set size (kbytes): 70076
  /tmp/pc:		Maximum resident set size (kbytes): 69588
  /tmp/pc:		Maximum resident set size (kbytes): 70216
  /tmp/pc:		Maximum resident set size (kbytes): 69964
  /tmp/phantom:		Maximum resident set size (kbytes): 47924
  /tmp/phantom:		Maximum resident set size (kbytes): 47780
  /tmp/phantom:		Maximum resident set size (kbytes): 47804
  /tmp/phantom:		Maximum resident set size (kbytes): 47824
  /tmp/phantom:		Maximum resident set size (kbytes): 47552
  /tmp/phantom:		Maximum resident set size (kbytes): 47980
  /tmp/phantom:		Maximum resident set size (kbytes): 47836
  /tmp/phantom:		Maximum resident set size (kbytes): 47780
  /tmp/phantom:		Maximum resident set size (kbytes): 47736
  /tmp/phantom:		Maximum resident set size (kbytes): 47768
  /tmp/phantom:		Maximum resident set size (kbytes): 47536
  /tmp/phantom:		Maximum resident set size (kbytes): 47568
  /tmp/phantom:		Maximum resident set size (kbytes): 47896
  /tmp/phantom:		Maximum resident set size (kbytes): 47924
  /tmp/phantom:		Maximum resident set size (kbytes): 47728
  /tmp/phantom:		Maximum resident set size (kbytes): 47760
  /tmp/pc:		Major (requiring I/O) page faults: 1405
  /tmp/pc:		Minor (reclaiming a frame) page faults: 22168
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23528
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23554
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23589
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23551
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23478
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23491
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23527
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23571
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23529
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23576
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23467
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23534
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23472
  /tmp/pc:		Minor (reclaiming a frame) page faults: 23523
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3910
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3913
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3918
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3912
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3909
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3918
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3909
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3912
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3909
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3914
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3902
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3901
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3908
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3914
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3911
  /tmp/phantom:		Minor (reclaiming a frame) page faults: 3903
  /tmp/pc:		Voluntary context switches: 889
  /tmp/pc:		Voluntary context switches: 904
  /tmp/pc:		Voluntary context switches: 914
  /tmp/pc:		Voluntary context switches: 899
  /tmp/pc:		Voluntary context switches: 831
  /tmp/pc:		Voluntary context switches: 890
  /tmp/pc:		Voluntary context switches: 846
  /tmp/pc:		Voluntary context switches: 947
  /tmp/pc:		Voluntary context switches: 955
  /tmp/pc:		Voluntary context switches: 823
  /tmp/pc:		Voluntary context switches: 820
  /tmp/pc:		Voluntary context switches: 886
  /tmp/pc:		Voluntary context switches: 931
  /tmp/pc:		Voluntary context switches: 899
  /tmp/pc:		Voluntary context switches: 876
  /tmp/phantom:		Voluntary context switches: 60
  /tmp/phantom:		Voluntary context switches: 50
  /tmp/phantom:		Voluntary context switches: 47
  /tmp/phantom:		Voluntary context switches: 50
  /tmp/phantom:		Voluntary context switches: 59
  /tmp/phantom:		Voluntary context switches: 72
  /tmp/phantom:		Voluntary context switches: 59
  /tmp/phantom:		Voluntary context switches: 60
  /tmp/phantom:		Voluntary context switches: 58
  /tmp/phantom:		Voluntary context switches: 61
  /tmp/phantom:		Voluntary context switches: 42
  /tmp/phantom:		Voluntary context switches: 39
  /tmp/phantom:		Voluntary context switches: 58
  /tmp/phantom:		Voluntary context switches: 43
  /tmp/pc:		Involuntary context switches: 162
  /tmp/pc:		Involuntary context switches: 588
  /tmp/pc:		Involuntary context switches: 285
  /tmp/pc:		Involuntary context switches: 322
  /tmp/pc:		Involuntary context switches: 430
  /tmp/pc:		Involuntary context switches: 438
  /tmp/pc:		Involuntary context switches: 389
  /tmp/pc:		Involuntary context switches: 287
  /tmp/pc:		Involuntary context switches: 410
  /tmp/pc:		Involuntary context switches: 300
  /tmp/pc:		Involuntary context switches: 529
  /tmp/pc:		Involuntary context switches: 390
  /tmp/pc:		Involuntary context switches: 366
  /tmp/pc:		Involuntary context switches: 364
  /tmp/pc:		Involuntary context switches: 340
  /tmp/phantom:		Involuntary context switches: 37
  /tmp/phantom:		Involuntary context switches: 27
  /tmp/phantom:		Involuntary context switches: 29
  /tmp/phantom:		Involuntary context switches: 35
  /tmp/phantom:		Involuntary context switches: 41
  /tmp/phantom:		Involuntary context switches: 73
  /tmp/phantom:		Involuntary context switches: 34
  /tmp/phantom:		Involuntary context switches: 24
  /tmp/phantom:		Involuntary context switches: 48
  /tmp/phantom:		Involuntary context switches: 35
  /tmp/phantom:		Involuntary context switches: 84
  /tmp/phantom:		Involuntary context switches: 38
  /tmp/phantom:		Involuntary context switches: 71
  /tmp/phantom:		Involuntary context switches: 12
  /tmp/phantom:		Involuntary context switches: 26
  /tmp/phantom:		Involuntary context switches: 13
  /tmp/pc:		File system inputs: 11648

So Phantomjs uses 47 Mb while Chromium uses ~70 Mb. Phantomjs uses more CPU and is faster.

I measure with /usr/bin/time on Linux (not same as shell `time`).

**Comment by drmrbrewer** [comment]
@Llbe thanks for these comparisons.  It agrees roughly with what I see (though I haven't made any quantitative comparison like you).  This is what is holding me back from using headless chrome in place of phantomjs for now... I need far fewer resources (which translates to far fewer $$$ worth of cloud server) to do the same stuff with phantomjs, so I'm sticking with that for now.

**Comment by aslushnikov** [comment]
If anyone has a good comparison of PhantomJS vs Puppeteer on different workloads, please send us a link.
