### ISSUE TITLE
Service Worker caching broken in v1.2.0 (Chromium 67.0.3372.0)??

### ISSUE THREAD

**Issue by drmrbrewer** [puppeteer/puppeteer#2212]
When using the same cache folder between page loads (by passing the same `userDataDir`), loading the following node route the first time should say "fetched from network" and then on reloading (when stuff is cached in service worker), it should change to "retrieved from service worker cache".

You can see this behaviour in a normal chrome browser by loading the [URL used below](https://cloud3squared.com/files/sw-chromium-bug/index.html) and then hitting F5 a few times.

When screenshotting this page with puppeteer/chrome, it has been working exactly as explained above... but now when I try the chromium version that is shipping with puppeteer 1.2.0, it is no longer working... however many reloads still shows "fetched from network"... and the cache quota info also displayed on the page shows as zero.

	const routeHandler = async function (req, res) {
		// this demo works works when using the following version ...
		//    const browserVersion = '539001'; // xxx 66.0.3355.0
		// but not with the version shipped with puppeteer 1.2.0 ...
		const browserVersion = '543305'; // xxx 67.0.3372.0

		const browserFetcher = puppeteer.createBrowserFetcher();
		const revisionInfo = await browserFetcher.download(browserVersion);
		const userDataDir = path.join(__dirname, 'tmp', 'puppeteer');
		const launchOptions = { userDataDir: userDataDir, executablePath: revisionInfo.executablePath };
		const browser = await puppeteer.launch(launchOptions);
		const page = await browser.newPage();
		await page.goto('https://cloud3squared.com/files/sw-chromium-bug/index.html', { waitUntil: 'networkidle0' });
		const screenshotBuffer = await page.screenshot();
		await browser.close();
		res.header('Content-Type', 'image/png');
		res.send(screenshotBuffer);
	};

Any ideas?  @ebidel ?  @aslushnikov ?

**Comment by aslushnikov** [comment]
@drmrbrewer not looking into the website code, it looks like something happy is going on with SW here.

The following script starts reporting "retreived from service worker cache" for me for the last 4 runs:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  // initial run: wait for SW installation
  await Promise.all([
    page.goto('https://cloud3squared.com/files/sw-chromium-bug/index.html', {waitUntil: 'networkidle0'}),
    waitForMessage(page, 'service worker installing')
  ]);
  // second run: wait for SW activation
  await Promise.all([
    page.reload({waitUntil: 'networkidle0'}),
    waitForMessage(page, 'service worker active')
  ]);
  // other reloads
  console.log('HERE!');
  for (let i = 0; i < 5; ++i) {
    await page.reload({waitUntil: 'networkidle0'});
    console.log(await page.$eval('#message > b', e => e.textContent));
  }
  await browser.close();
})();

function waitForMessage(page, text) {
  return new Promise(resolve => {
    page.on('console', function listener(msg) {
      if (msg.text() !== text)
        return;
      page.removeListener('console', listener);
      resolve();
    });
  });
}
```

Overall, it looks like the script doesn't wait enough time for SW installation/activation. I'm not an expert on service workers though :) 

If you think there's a bug with SW, please file it upstream to Chromium on https://crbug.com/new
