### ISSUE TITLE
how to get current url ?

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#2215]
I need to store the url that I browse, does it exist in puppeteer any function that can get the url? through sun I can not, because the buttons are not links

**Comment by vsemozhetbyt** [comment]
[`page.url()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageurl)?

**Comment by ray-kim-12** [comment]
How can I get a dynamically created URL ?
For instance, I click a button, and the URL gets updated (without a refresh). So it goes from `home` to `home/imsaidomasd` 
It also gets copied into the clipboard, but I think the first way is a more straightforward solution

**Comment by GerryOnGithub** [comment]
what is page.url()? it is not a string

**Comment by vsemozhetbyt** [comment]
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    console.log(page.url());
    console.log(typeof page.url());

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
https://example.org/
string
```

**Comment by harrygreen** [comment]
Yep, can confirm [`page.url()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageurl) works fine for me in 2021

**Comment by samimhakimi** [comment]
`page.url()` Not working at the moment 23-FEB-2022, can you help me?

**Comment by vsemozhetbyt** [comment]
@samimhakimi Can you provide a small code fragment that reproduces your issue?

**Comment by samimhakimi** [comment]
@vsemozhetbyt Yes please check below code snippets. As in console, it shows blank.

```

(async () => {
  // The location

  const browser = await puppeteer.launch({
    headless: true,
  });

  const page = await browser.newPage();
  const url = await page.mainFrame().url();
  console.log(url);
  await page.goto(url, { waitUntil: "networkidle0" });

  await page.pdf({
    path: "page.pdf",
    format: "A4",
    printBackground: true,
    scale: 0.5,
    displayHeaderFooter: false,
    margin: { bottom: "50px" },
  });

  await browser.close();
})();

//

// Downloading PDF files
app.get("/downloadPDF", (req, res) => {
  // express.js
  res.download("./page.pdf");
});
//
```

**Comment by GerryOnGithub** [comment]
I do not work with Puppeteer anymore

**Comment by vsemozhetbyt** [comment]
@samimhakimi  Sorry, I cannot reproduce, I get `about:blank` in the console, it is the URL of a new empty page.

**Comment by samimhakimi** [comment]
@vsemozhetbyt  Yes, I am trying to get the URL of the new page when the user clicks the new page it should take the new page screenshots.

**Comment by Himly1** [comment]
> @samimhakimi Sorry, I cannot reproduce, I get `about:blank` in the console, it is the URL of a new empty page.

Same here
