### ISSUE TITLE
page.setRequestInterception(true); causes invalid SSL pages to hangup and timeout instead of triggering an error.

### ISSUE THREAD

**Issue by leem32** [puppeteer/puppeteer#2216]
I need to use `page.setRequestInterception` while taking a screenshot of webpages but notice that when I attempt to take a screenshot of a webpage which has a `wrong host` SSL certificate the script hangs up and times out.

If I remove `page.setRequestInterception` the script does not hang up and displays the error below.
`Error: net::ERR_CERT_COMMON_NAME_INVALID at https://wrong.host.badssl.com/`

Is this a bug? I need to use 'await page.setRequestInterception(true);' to abort some scripts. 

Simplified code to illustrate the issue: 
```javascript
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  await page.goto('https://wrong.host.badssl.com/', {timeout: 0, waitUntil: 'load'});
  await page.screenshot({path: 'screenshot/site.png'});
  await browser.close();
})();
```
If you comment out await 'page.setRequestInterception(true);' the script will run and display an error which is what I want.

EDIT: The hang is not specific to a wrong host error. Basically the script will hang up when using `setRequestInterception()` for any URL which contains an invalid or non-existant ssl certificate.

**Comment by leem32** [comment]
Just noticed my question is a dupe of [#1159](https://github.com/GoogleChrome/puppeteer/issues/1159#thread-subscription-status)

**Comment by aslushnikov** [comment]
Closing as a dupe.
