### ISSUE TITLE
Take screenshot of browser error pages

### ISSUE THREAD

**Issue by leem32** [puppeteer/puppeteer#2217]
Is it possible to take screenshots of browser error pages?

An example would be navigating to a website which is down or doesn't exist and the browser displays a 'This site can’t be reached' message.
Can I somehow take a screenshot of the displayed error message?

**Comment by rwinscot** [comment]
Errors that have standard HTTP status codes... should be no problem!

One approach is to capture 'console' messages ... which are typically emitted if the page throws an error or warning. Here is an example of taking a screenshot of a page that resolves with an HTTP Status of 404 ( not found ).


```javascript
const browser = await puppeteer.launch();	
const page = await browser.newPage();
	
page.on('console', msg => {

	if (msg.type() == 'error' && msg.text().indexOf('404') >= 0) {

		page.screenshot({path: './screenshot.png'});
	}
});

await page.goto('http://www.google.com/page_does_not_exist.html', {waitUntil: 'networkidle2'});				
await browser.close();

```

Please post additional details about what kind of error(s) you are working with if this approach doesn't work for you.

**Comment by sesesmith30** [comment]
you can take screenshots after every`waitFor` and return the last error screenshot in catch block
