### ISSUE TITLE
Load issue? Browser instance closed automatically when several client connect to it with headless mode

### ISSUE THREAD

**Issue by ShawnPanxiaoming** [puppeteer/puppeteer#2219]
Hi, I have a performance issue when using puppeteer to do a large amout of page navigation.

Environment:
CentOS7
Puppeteer 1.0
Google Chrome 65.0.3325.162

First, in order to save memory and reuse browser instance,I just launch browser with headless mode and then get browser wspoint('ws://127.0.0.1:35487/devtools/browser/c996362b-12a5-4928-aff7-ce43b1296c32') by calling browser.wsEndpoint();

Second, I created a 'app_content.js' file just like this:
```
const puppeteer = require('/usr/local/lib/node_modules/puppeteer');
var arguments = process.argv.splice(2);
const url = arguments[0];
(async () => {
      const browser = await puppeteer.connect({'browserWSEndpoint': 'ws://127.0.0.1:35487/devtools/browser/c996362b-12a5-4928-aff7-ce43b1296c32'});
const page = await browser.newPage();
page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36');
await page.goto(url);
console.log(await page.content());
browser.disconnect();
})();
```
the nodejs file works fine when you manually call it with url param

Finally,I have a java program which running in a multi-thread mode, thread is controlled by FixedThreadPool and each thread calls the 'app_content.js' independently. After ThreadPool finish successfully running about 10 thread, the browser is closed unexpectedly.

I have tried many times and the browser always closed in the final.I guess maybe google chrome is designed not support for multi-page navigation in the same time? or any performance limit for using puppeteer communication with chrome?

**Comment by katp4** [comment]
i don't know if it's related to your problem but both setUserAgent and browser.disconnect are promises and both should be run with the await keyword.
Also worth adding a try catch on both files to see if you can pinpoint the error.

**Comment by ShawnPanxiaoming** [comment]
Seems like it hausted all system memory and killed by centos.
Just close the issue,thanks~
