### ISSUE TITLE
add a code sample explaining how to handle a 404

### ISSUE THREAD

**Issue by kaycebasques** [puppeteer/puppeteer#2220]
I'm getting `UnhandledPromiseRejection` when navigating to a page that doesn't exist via `await page.goto()`, but I'm really at a loss as to how to handle this. I've tried to catch it in various ways, but none seem to work...

**Comment by ebidel** [comment]
try/catch or `.catch()` the promise:

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
try {
  await page.goto('https://example.com/404');
} catch (err)  {
  console.log('Error loading page:', err);
}
await browser.close();
```

**Comment by kaycebasques** [comment]
That's what I was doing. I think the issue is elsewhere, so maybe disregard this comment. Debugging from DevTools was misleading, but there's a lot I don't understand here, so it could be pilot error. I'll re-open with more concrete comments if I find anything helpful.

**Comment by mirismaili** [comment]
> try/catch or `.catch()` the promise:
> 
> ```js
> const browser = await puppeteer.launch();
> const page = await browser.newPage();
> try {
>   await page.goto('https://example.com/404');
> } catch (err)  {
>   console.log('Error loading page:', err);
> }
> await browser.close();
> ```

Doesn't work as I tested in Puppeteer v1.16.0. Nor `try/catch` nor `.catch()`.

**Comment by mirismaili** [comment]
> try/catch or `.catch()` the promise:
> 
> ```js
> const browser = await puppeteer.launch();
> const page = await browser.newPage();
> try {
>   await page.goto('https://example.com/404');
> } catch (err)  {
>   console.log('Error loading page:', err);
> }
> await browser.close();
> ```

@ebidel 

**Doesn't work as I tested against Puppeteer v1.16.0.** Neither `try/catch` nor `.catch()`.

**Comment by michaeloryl** [comment]
I agree.  This is just passing through with no error for me:

```
  const browser = await puppeteer.launch({headless: false, slowMo: 0, args: config.chromeArgsArray})
  const page = await browser.newPage()

    try { // get to login page
      await page.goto(config.inSight.baseUrl + '/healthcheckXXX')
    } catch (err) { // couldn't get to original site
      throw({message: 'Could not reach InSight HealthCheck URL.  Site appears to be down.'}) // rethrow after logging
    }
```
I'm running 1.17.0.

**Comment by aslushnikov** [comment]
The http error codes handling is covered in https://github.com/GoogleChrome/puppeteer/issues/4502.

**Comment by michaeloryl** [comment]
"This is a feature, not a bug."

https://github.com/GoogleChrome/puppeteer/issues/4502

The docs are not written clearly in regard to this, though.  I can certainly see the value in the way it actually works, allowing you to read 404 pages, but my gut also suggest that any 4xx or 5xx series HTTP response is an error, and would be handled as such.

**Comment by aslushnikov** [comment]
> The docs are not written clearly in regard to this, though. 

@michaeloryl fair. Would you mind contributing a PR to our docs that will clarify this?

**Comment by michaeloryl** [comment]
@aslushnikov I've got a pull request lined up, but I have been unable to determine from the code whether Puppeteer returns any 400 series status code as a valid page, or whether it is just 404.  I suspect that other 40x codes return valid pages.  Can you confirm one way or the other?  Thanks.

**Comment by aslushnikov** [comment]
@michaeloryl All HTTP Error codes are considered to be a successful HTTP transaction. Puppeteer throws an exception if the HTTP transaction fails for some reason, e.g. there's no internet connection.

**Comment by michaeloryl** [comment]
Thanks very much.  I'll reflect that in the docs.
