### ISSUE TITLE
Can't upload a file with an error "Node is either not visible or not an HTMLElement"

### ISSUE THREAD

**Issue by ryomasuda4611** [puppeteer/puppeteer#2225]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^1.1.1
* Platform / OS vers ion: macOS 10.13.3
* URLs (if applicable):
* Node.js version:v9.4.0

**What steps will reproduce the problem?**
I'm trying upload a image file which is in my local storage using "elementHandle.uploadFile".
But it failed with an error "Node is either not visible or not an HTMLElement".
How can I fix it and upload a file ?
_Please include code that reproduces the issue._

1.` const input = await page.$(".moxie-shim input");
      await input.uploadFile(`./images/${_id}.png`);`

2.`Error: Node is either not visible or not an HTMLElement
    at ElementHandle._assertBoundingBox (/Users/ryomasuda/projects/wordpress-automatic-post-tool/node_modules/puppeteer/lib/ElementHandle.js:160:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

**What is the expected result?**
File uploaded

**What happens instead?**
Error emitted.

**Comment by aslushnikov** [comment]
I can't repro this; please re-file with a code snippet that I'd be able to run locally and see the problem.
Thanks.
