### ISSUE TITLE
Set time out when start puppeteer by a project C#

### ISSUE THREAD

**Issue by AnnaCICI** [puppeteer/puppeteer#2227]
Hi, I have a project C# which launch puppeteer for opening 3 pages, one by one, and then saving them one by one. 

I want to set a time out for avoiding weird problem and making sure code works well. But I found if puppeteer is launched by C#, its **default time out 3000ms** does not work. And if I add a time out in C#, **chromium cannot close automatically**.

How can I set a time out global this puppeteer ? 

```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({})
  const page1 = await browser.newPage()

  try {
    await page1.goto('https://page1/', {waitUntil : 'load'});
    await page1.click(OpenPage2);

    const twoPage= browser.pages();
    const page2 = twoPage[1];
    await page2.click(OpenPage3);

    const threePage= browser.pages();
    const page3 = threePage[2];
    await page3.click(SavePage3);

    await page2.type('#mytextarea', 'Hello'); 
    await page2.click(SavePage2);

    await browser.close()
  } 

catch (ex) {
    await browser.close()
    console.error(ex.toString())
  }
})()
```

**Comment by aslushnikov** [comment]
> But I found if puppeteer is launched by C#, its default time out 3000ms does not work. 

@AnnaCICI This sounds really strange. Can you elaborate on this more?
