### ISSUE TITLE
invoking chrome extension using puppeteer

### ISSUE THREAD

**Issue by tomerb78** [puppeteer/puppeteer#2229]
**Use Case:**
connect puppeteer to a page that should work with chrome extension, and make the extension work on the page.
The extension is loaded as expected after setting `--load-extension` and `headless: false`

**Issue:**
Some chrome api like *chrome.tabCapture.capture* require the extension to be **invoked** in order to work (i.e user should click on the extension icon).

I could find a way to automate the extension invocation using puppeteer (or any other chromium startup arguments).

Please advise.

**Comment by aslushnikov** [comment]
dupe of #1215

**Comment by s16h** [comment]
What’s the status of this specific case? #1215 doesn’t seem to address it.

**Comment by s16h** [comment]
You can pass the `--whitelisted-extension-id=<extension-id>` flag to Puppeteer.

**Comment by mcassagnes** [comment]
@s16h How are you getting an extension id when using `--load-extension={PATH}`, like in OP's situation?
I'm guessing using the `key` property in `manifest.json`.

That doesn't really solve the requirement of the extension being **invoked**. How are you solving that part?

**Comment by aslushnikov** [comment]
The #1215 is indeed irrelevant, my bad. The #2486 seems to be a better fit.

**Comment by s16h** [comment]
@mcassagnes, you're right in that it doesn't actually *invoke* the extension. In my case, I just wanted to be able to use `chrome.tabCapture.capture` and whitelisting the extension is good enough for that; no invocation required.
