### ISSUE TITLE
Unable to use authenticated proxy:  Error: net::ERR_NO_SUPPORTED_PROXIES

### ISSUE THREAD

**Issue by suhailgupta03** [puppeteer/puppeteer#2234]
I am trying to connect to a web service using an HTTP proxy. Here is what I am doing:
`    const puppeteer = require('puppeteer');

    (async () => {
        const browser = await puppeteer.launch({
            headless: false,
             args: [
                 '--proxy-server=http://myusername:password@zproxy.luminati.io:22225'
             ]
        });
        const page = await browser.newPage();

        await page.goto('https://www.whatismyip.com/');
        await page.screenshot({ path: 'example.png' });

        //await browser.close();
    })();`

This does not work at all. I get an error saying:
` UnhandledPromiseRejectionWarning: Error: net::ERR_NO_SUPPORTED_PROXIES at https://www.whatismyip.com/`

I have verified that the proxy works using it with modules like `axios`, `requestjs`. Don't know the reason, why it fails here.

I even tried setting up a `.env` file with a variable named `HTTP_PROXY` as [given here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables), which placed in the project root looks like:
`HTTP_PROXY=http://myusername:password@zproxy.luminati.io:22225`

but the same result.

**Comment by tjmcewan** [comment]
`page.authenticate` works.  see: https://blog.apify.com/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212#5875

**Comment by roipaz** [comment]
you should add: 
await page.authenticate({ username: 'lum-customer-MyUserName' , password:'MyPassword' });
Luminati userName and password can be find at: https://luminati.io/cp/api_example

See full example:
const puppeteer = require('puppeteer');


(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--proxy-server=zproxy.lum-superproxy.io:22225']
  });
  
  const page = await browser.newPage();

  await page.authenticate({ username: 'lum-customer-MyUserName' , password:'MyPassword' });
  await page.goto('https://luminati.io');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();

**Comment by roipaz** [comment]
You should change to 
`args: ['--proxy-server=zproxy.lum-superproxy.io:22225'] `

Authenticate the newPage add: 
`await page.authenticate({ username: 'lum-customer-MyCustomerName+MyZoneName' , password:'MyPassword' });`

User name and password can be find at: https://luminati.io/cp/api_example 

See full example: 

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
    headless: false,
    args: ['--proxy-server=zproxy.lum-superproxy.io:22225']
  });
  
  const page = await browser.newPage();
  await page.authenticate({ 
      username: 'lum-customer-MyCustomerName+MyZoneName' , 
      password:'MyPassword' 
  });

  await page.goto('https://luminati.io');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();

```

**Comment by roipaz** [comment]
Please find a webinar record hosted on 'browser automation' at: https://youtu.be/pRRH61Gs7cE

Webinar agenda:
- Make your crawler be seen as a ‘real-user’ and not get blocked
- Select the right tools for browser automation
- Selenium vs. Puppeteer, pro and cons
- Setup Selenium and Puppeteer to work with proxy
- Proxy manipulation for an automated crawler
- Setup your Proxy Manager with Selenium and Puppeteer

**Comment by Anthony-Janin** [comment]
Hi,

@roipaz 

Nice, but have you got the same solution for playwright + (websocket) "chrome remote" please?

Best regards,
Anthony

**Comment by aillusions** [comment]
> Has anybody discovered solution?

```
            await page.authenticate({
                username: 'your squid user',
                password: 'your squid password'
            });
```
