### ISSUE TITLE
After upgrading to 1.2.0 all the app console.logs are being displayed - INFO:CONSOLE

### ISSUE THREAD

**Issue by x1c0** [puppeteer/puppeteer#2235]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Windows 7 64 bit
* Node.js version: 8.9.1

**What steps will reproduce the problem?**

1. I have an angular-cli project
2. updated puppeteer from 0.13.0 to 1.2.0
3. npm run e2e

**What is the expected result?**
On Mac OS all the tests run without any console.log messages

**What happens instead?**
On Windows all the console.log are being displayed like this:
[0320/130951.603:INFO:CONSOLE(107)] ...

This is not a bug i would say, it only occurs on Windows machines, I'm just wondering if there is a way to disable this logs.

Thank you!

ps. thanks for all the work on puppeteer!

**Comment by aslushnikov** [comment]
@x1c0 these logs look like chromium's stdout. Could it be that you're launching puppeteer browser with `dumpio: true` flag?

**Comment by x1c0** [comment]
@aslushnikov no, the only flags we are using are this ones: `'--headless', '--disable-gpu', '--window-size=1000,600'`

**Comment by aslushnikov** [comment]
@x1c0 so where do you see these logs? can you paste a code snippet you use so that I can try to reproduce?

**Comment by x1c0** [comment]
I see them directly on the terminal, and that only happens on windows machine, on OSX i don't have them :)

**Comment by analogrelay** [comment]
I'm also seeing this using `chromedriver` directly (and only on Windows). Maybe the issue lies there?

**Comment by aslushnikov** [comment]
@JoelEinbinder: do you experience this as well?

**Comment by aslushnikov** [comment]
So long story short, we're unaware what's going on. If you figure out something, please let us know.
