### ISSUE TITLE
Get framenavigated url on fail

### ISSUE THREAD

**Issue by leem32** [puppeteer/puppeteer#2237]
If I `goto` http://ivue.com in Puppeteer I get an `Error: net::ERR_TOO_MANY_REDIRECTS at http://ivue.com/` error (ivue.com seems to be in an infinite redirect loop).

But if I redirect to ivue.com with `window.location.href = "http://ivue.com";` it doesn't return an error and there's no way of knowing what happened or to get the last navigation attempted.
This is bad for me because I need to know if a client-side navigation redirection succeeded or not and get the URL if it succeeded or not.
I'm using `framenavigated` to get the client side navigation redirects and was hoping this would return the URL even if it failed.

Could a `frame.failedUrl` feature be added to `framenavigated`, which would simply hold the URL of the failed navigation URL?

Maybe something already exists to return the  Client navigation redirect on failure. If it does please let me know because I can't find it.

```javascript
var url = process.argv[2];

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: true, timeout: 30000, ignoreHTTPSErrors: true});
  const page = await browser.newPage();
      page.on('error', err => {
         console.log('Error: On Page: ' + err, '|', url);

         page.close();
         browser.close();
         process.exit(-1);
      });

      page.on('pageerror', pageerr => {
        console.log('Error: pageerror occurred: ' + pageerr, '|', url);
      });

  try {
    page.on('framenavigated', frame => {
     if(frame.parentFrame() === null) {
    console.log(frame._url);
    // console.log(frame);
    }
   });

  await page.goto(url, {timeout: 120000, waitUntil: 'networkidle2'});
  await page.close();
  await browser.close();

 } catch (err) {

    console.log("caught an exception", err);
    await page.close();
    await browser.close();
    }
})();
```

Thanks :)

EDIT: This is obviously a timing issue with `networkidle2`, but as I explained [here](https://github.com/GoogleChrome/puppeteer/issues/2238), `load` often causes URLS with hundreds of requests to time out.
If I could just exit the `load` if it's still running after x amount of time and just take the screenshot I think that would fix the issues I'm having. That way if `load` hasn't finished after 60 seconds I could still take a screenshot and exit the script.

EDIT2: I created an adblocker to block adsense, doubleclick.net ads and the slow loading pages such as newspaper websites load a fair bit faster now which allows me to use the `load` option for `goTo`. Errors such as `Error: net::ERR_TOO_MANY_REDIRECTS` are usually detected now and I can get the URL of the failed frame from `unreachableUrl` using the raw Devtools Protocol run with Puppeteer.

**Comment by aslushnikov** [comment]
> If I could just exit the load if it's still running after x amount of time and just take the screenshot I think that would fix the issues I'm having. That way if load hasn't finished after 60 seconds I could still take a screenshot and exit the script.

@leem32 you can use request interception to figure continious redirects. You'll be able to get redirect URL from there as well.

> EDIT2: I created an adblocker to block adsense, doubleclick.net ads and the slow loading pages such as newspaper websites load a fair bit faster now which allows me to use the load option for goTo. Errors such as Error: net::ERR_TOO_MANY_REDIRECTS are usually detected now and I can get the URL of the failed frame from unreachableUrl using the raw Devtools Protocol run with Puppeteer.

This sounds interesting. `unreachableUrl` indeed helps here.

**Comment by a10kiloham** [comment]
@leem32 would you mind sharing a Gist of how you workaround the TOO_MANY_REDIRECTS? This constantly gets thrown for me but I can't easily dissect it to figure out how to detect/prevent.
Thank you!
