### ISSUE TITLE
Add a waitUntilTime to GoTo

### ISSUE THREAD

**Issue by leem32** [puppeteer/puppeteer#2238]
Over the last couple of weeks, I've been heavily testing hundreds of URL's to take screenshots through Puppeteer, and I've realised that none of the ` waitUntil` options work all the time.

If I use `Load`, sites with hundreds of requests such as `http://dailymail.co.uk` take so long they often timeout before taking a screenshot. If I use `networkidle2` sites with hundreds of requests like dailymail.co.uk load much quicker along with a screenshot, but sites with client-side redirects often take a blank screenshot because `networkidle2` finishes before the redirects have finished. `DomContentLoaded` also has the same problem as `networkidle2`.

If there was an `waitUntilTime` option e.g `await page.goto(URL, {timeout: 60000, waitUntil: 'load, waitUntilTime: '60''});` or `await page.goto(URL, {timeout: 60000, waitUntil: '60'});` then we could just take a screenshot after a set amount of time whether the page `load` has triggered or not. This would be extremely useful IMO and would solve the issues I've stated above.

The first option i.e `await page.goto(url, {timeout: 60000, waitUntil: 'load, waitUntilTime: '60''});` is preferable as it could use `waitUntil: 'load'`, up till the `waitUntilTime: '60'` setting.

EDIT: I created an adblocker to block adsense, doubleclick.net ads and the slow loading pages such as newspaper websites load a fair bit faster now which allows me to use the `load` option for `goTo`. I would still like to have the ability to `waitUntil` x time though so the issue still stands.

**Comment by aslushnikov** [comment]
@leem32 you can easily polyfil the `waitUntilTime` like the following:

```js
await Promise.race([
  page.goto('http://example.com'),
  new Promise(x => setTimeout(x, 60 * 1000))
]);
// Here we either loaded page succesfully, or timeouted after 60 seconds of navigation.
await page.screenshot();
```

Hope this helps
