### ISSUE TITLE
Can't use the same methods as selenium to select an element.

### ISSUE THREAD

**Issue by yxs** [puppeteer/puppeteer#2239]
* Puppeteer version: 1.2.0
* Platform / OS version: CentOS 7.4.1708
* Node.js version: 8.10.0

Can't use the same methods as selenium to select an element.

* In selenium
I can use:
```
By.ID
By.NAME
By.CLASSNAME
By.TAG
By.CSS_SELECTOR
By.LINK_TEXT
By.PARTIAL_LINK_TEXT
By.XPATH
```
For example, When I want to select some text like `<a href=" "><i class=" "></i>some text</a>`

I can use 
```
By.LINK_TEXT, "some text"
By.CSS_SELECTOR, "body > div > div.wrap > div.aside > ul > li:nth-child(9) > a"
By.XPATH, "/html/body/div/div[2]/div[1]/ul/li[9]/a"
```
* In puppeteer
I can't find some similar way to click on the element.

`page.click` can only use `<input>` , `class` , `id`

**Comment by katp4** [comment]
page.click can take CSS selectors with whom you can get an element via ID, NAME, CLASSNAME, TAG, CSS SELECTOR (which the above 4 are part of), LINK_TEXT and PARTIAL_LINK_TEXT (you can use the text attribute in CSS or XPATH ).
https://www.w3schools.com/cssref/css_selectors.asp 

it can also take XPATH selectors which can do whatever CSS selectors can.
