### ISSUE TITLE
How to install OS specific version of chrome / puppeteer with package.json?

### ISSUE THREAD

**Issue by voordev** [puppeteer/puppeteer#2240]
Im running puppeteer on OSX but would like install chromium version of linux.
Since im going to run it on linux and need this OS version.

It is possible to specify the chromium version for linux with the package.json somehow?

```
    "puppeteer": "^0.13.0",
```

Installs only for current OS which is OSX

**Comment by katp4** [comment]
maybe you can use BrowserFetcher ?https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-browserfetcher

**Comment by ebidel** [comment]
@aslushnikov should we add a platform config option to BrowserFetcher?

**Comment by aslushnikov** [comment]
@ebidel: It's already possible create browser fetchers for different platforms, passing the "platform" option to [`puppeteer.createBrowserFetcher()`]( https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteercreatebrowserfetcheroptions).

Hope this helps!
