### ISSUE TITLE
How to get text with XPath expression?

### ISSUE THREAD

**Issue by norlover** [puppeteer/puppeteer#2243]
Hi, 

i use this ,but not working. 

var content = await page.$x("//*[@id="postmessage_30901"]/a]");
var content = await page.$x("//*[@id="aimg_DABZR"]");

Any help are appreciated.

I want full link to .m4a and .jpg  in source, do not use  (postmessage_30901 aimg_DABZR aimg_dW5J3 ) They may be variables

[1.zip](https://github.com/GoogleChrome/puppeteer/files/1837768/1.zip)

**Comment by katp4** [comment]
this is how we do it, hope it helps
``            
var xpathData = await page.$x(`xpathSelector`);
            var xpathTextContent = await xpathData[0].getProperty('textContent'),
                text = await xpathTextContent.jsonValue();
``

**Comment by vsemozhetbyt** [comment]
XPath expressions seem invalid. Try these:
`$x('//*[@id="postmessage_30901"]/a')`
and
`$x('//*[@id="aimg_DABZR"]')`

**Comment by norlover** [comment]
@vsemozhetbyt  

if i  use (postmessage_30901 aimg_DABZR aimg_dW5J3 )  it's variables

Other pages cannot take effect

**Comment by vsemozhetbyt** [comment]
If you need variable interpolation in XPath expression, you can try these:
`` $x(`//*[@id="${variable}"]/a`) ``
and
`` $x('//*[@id="${variable}"]') ``

**Comment by norlover** [comment]
@vsemozhetbyt 

	const t2 = await page.$x('//*[@id="${variable}"]/a');
	const t3 = await page.$x('//*[@id="${variable}"]');
	console.log(t2,t3);

D:\node>node index.js

[] []

**Comment by norlover** [comment]
@aslushnikov @ashleyR94   help!

**Comment by vsemozhetbyt** [comment]
@norlover It seems we do not understand each other enough)

I mean you should define `variable` for different pages if you can suggest `@id` value.

If you cannot suggest the `@id` value, you can try other, less specific XPaths, like these:

`$x('//*[contains(@id, "postmessage_")]/a')`
and
`$x('//*[contains(@id, "aimg_")][1]')`

So the code for needed data can be like this:

```js
const [linkHandle] = await page.$x('//*[contains(@id, "postmessage_")]/a');
const hrefHandle = await linkHandle.getProperty('href');
const hrefValue = await hrefHandle.jsonValue();

const [imgHandle] = await page.$x('//*[contains(@id, "aimg_")]');
const srcHandle = await imgHandle.getProperty('src');
const srcValue = await srcHandle.jsonValue();
```

**Comment by vsemozhetbyt** [comment]
Or you can make it this way:
```js
const hrefValue = await page.evaluate(
  () => document.querySelector('[id^="postmessage_"] > a').href
);

const srcValue = await page.evaluate(
  () => document.querySelector('[id^="aimg_"]').src
);
```

**Comment by norlover** [comment]
@vsemozhetbyt    ohhhh great!  it is work!

but 1.html has two pic , just show only one~! 


http://xxx.com/f.m4a  work
http://xxx.com/1.jpg   work
http://xxx.com/2.jpg   not work

**Comment by vsemozhetbyt** [comment]
If you need several values in arrays, try this:
```js
const linkHandlesArray = await page.$x('//*[contains(@id, "postmessage_")]/a');
const hrefHandlesArray = await Promise.all(linkHandlesArray.map(handle => handle.getProperty('href')));
const hrefValuesArray = await Promise.all(hrefHandlesArray.map(handle => handle.jsonValue()));

const imgHandlesArray = await page.$x('//*[contains(@id, "aimg_")]');
const srcHandlesArray = await Promise.all(imgHandlesArray.map(handle => handle.getProperty('src')));
const srcValuesArray = await Promise.all(srcHandlesArray.map(handle => handle.jsonValue()));

```

or simply this:

```js
const hrefValuesArray = await page.evaluate(
  () => [...document.querySelectorAll('[id^="postmessage_"] > a')].map(({ href }) => href)
);

const srcValuesArray = await page.evaluate(
  () => [...document.querySelectorAll('[id^="aimg_"]')].map(({ src }) => src)
);
```

**Comment by norlover** [comment]
@vsemozhetbyt Thank you

**Comment by dcr007** [comment]
I did something like this :
 ```
public async getVersionInfo() : Promise<string> {
        const pathData = await this.page.$x(this.loginSelectors.versionInfo); // your xpath 
         // getting value of attribute `textContent` from the first array element in pathData.
        const versionInfo = await this.page.evaluate(node => node.textContent, pathData[0]); 
        console.log(`<-------Release Info------->\n ${versionInfo}`);
        return versionInfo;
    }
```
Hope this helps :)
