### ISSUE TITLE
Resolve URLs from Coverage

### ISSUE THREAD

**Issue by abaksha-sc** [puppeteer/puppeteer#2244]
Can't resolve URLs in Coverage tool.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Desktop Win10 Pro (Chrome 65.0.3325.181)
* Node.js version: 9.8.0

**What steps will reproduce the problem?**

1. Open any page with script which includes script by relative path. For example, page http://localhost/some/folder/page.html with <script src="../../script.js"></script>
2. Get code Coverage.

**What is the expected result?**
Coverage should contains full URL, because it's impossible to resolve it from puppeteer:
```[
...
{
  text: "some js text...",
  url: "../../script.js", //as is
  resolvedUrl: "http://localhost/script.js" // resolved
  ranges: [...]
}
]
```

**What happens instead?**
Coverage contains URL as included in page (not full):
```[
...
{
  text: "some js text...",
  url: "../../script.js",
  ranges: [...]
}
]
```

P.S. Any ideas to get full URL?

**Comment by aslushnikov** [comment]
@abaksha-sc The reason we don't resolve URLs is to retain the sourceURL values.

You can resolve URLs against the page url on your side, e.g. using node's [`url.resolve`](https://nodejs.org/api/url.html#url_url_resolve_from_to). Will this work for you?

**Comment by abaksha-sc** [comment]
@aslushnikov It won't work, because i don't know from which point that relative URL starts. Scripts include another scripts in different folders.

**Comment by aslushnikov** [comment]
> Scripts include another scripts in different folders.

Are we talking about es6 modules here?

**Comment by abaksha-sc** [comment]
> Are we talking about es6 modules here?

No, script includes another script through appending ```<script src="../../someFile.js"></script>``` to head.
