### ISSUE TITLE
page.url() returns invalid value

### ISSUE THREAD

**Issue by sean-hill** [puppeteer/puppeteer#2248]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Mac
* URLs (if applicable): https://appleid.apple.com/#!&page=signin
* Node.js version: 8.2.1

**What steps will reproduce the problem?**

Using Puppeteer Sandbox paste this:

```js
const puppeteer = require('puppeteer')
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('https://appleid.apple.com/#!&page=signin')
console.log(await page.url())
await browser.close()
```

**What is the expected result?**

For `page.url()` to return `https://appleid.apple.com/#!&page=signin`

**What happens instead?**

`page.url()` returns `https://appleid.apple.com`

If you run `document.location.href`, `https://appleid.apple.com/#!&page=signin` is returned.

**Comment by aslushnikov** [comment]
Fixed with #257.
