### ISSUE TITLE
Option to change the download- and execution-path of chromium

### ISSUE THREAD

**Issue by cakebake** [puppeteer/puppeteer#2249]
**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: ARCH x86_64 GNU/Linux
* URLs (if applicable): [markdown-themeable-pdf](https://atom.io/packages/markdown-themeable-pdf) ([Currently under revision/Rewrite with Puppeteer](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite))
* Node.js version: Bundled with atom editor

**What steps will reproduce the problem?**

I would like to update the puppeteer dependency without downloading old revisions again.

**What is the expected result?**

To allow the users of my package to skip a large download (Chromium Update) and continue to use the old version.

To do that, I need a way to influence the download- and execution-path of chromium.

**What happens instead?**

When puppeteer dependency is updated, all downloaded chromium versions will be deleted.

---

Thank you for this good piece of software! :+1:

**Comment by davidsielert** [comment]
Puppeteer provides the executablePath as an option to launch .. 
e.g.
```  
const browser = await puppeteer.launch({
        executablePath: "/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary",
    });
```

**Comment by cakebake** [comment]
Thank you! But that would not solve the problem of defining the download directory.

Of course I can move the chromium directory to a different location after the download, but I think it would be better if it were configurable. Less error prone and cleanly resolved by the API.

**Comment by cakebake** [comment]
Oh! I missed the `path` option in puppeteer.createBrowserFetcher([options])! 

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteercreatebrowserfetcheroptions
