### ISSUE TITLE
Redirect a download as a stream

### ISSUE THREAD

**Issue by thom4parisot** [puppeteer/puppeteer#2250]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.1 / 1.2.0
* Platform / OS version: macOS
* URLs (if applicable): [dtc-innovation/credit-coop-statements:index.mjs](https://github.com/dtc-innovation/credit-coop-statements/blob/4b5b6d6af39360b0ad7e6dbdb593dd657032c37c/index.mjs)
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

Just direct a `goto` instruction to a page which triggers a download (in my case, OXF/CSV file from a bank).

**What is the expected result?**

```js
const [resp] = await Promise.all([
  page.waitForNavigation({ waitUntil: 'networkidle0' }),
  page.click('form[name="telechargementForm"] input[name="btConfirmer"]'),
]);

return resp.buffer();
```

I expect to be able to identify a download navigation to direct its buffer (or streamed content) to wherever.

**What happens instead?**

`resp` is `null`. When I launch the browser with `headless: false` option, download starts systematically but still, I cannot retrieve the download buffer/stream.

**Comment by thom4parisot** [comment]
A workaround I saw in another issue was to evaluate with `fetch()` to get cookies and such. It did the trick:

```js
  const result = await page.evaluate(async () => {
    const form = document.querySelector('form[name="telechargementForm"]');
    const data = new FormData(form);
    data.append('btConfirmer', 'Confirmer');


    return fetch(form.action, {
      method: 'POST',
      credentials: 'include',
      body: data,
    })
    .then(response => response.text());
  });


  // CSV data as plain text
  return result;
```

**Comment by aslushnikov** [comment]
Closing as dupe of #299.

**Comment by johnbalvin** [comment]
It doesn't work for pdfs
