### ISSUE TITLE
Not all cookies are retrieved by .cookies()

### ISSUE THREAD

**Issue by PierrickLozach** [puppeteer/puppeteer#2251]
Not sure who is responsible for this so I am creating the issue here.

When I call `var cookies = await page.cookies('https://www.google.com');`, it only retrieves 2 cookies instead of the 12 cookies that I can see the devtools in Chrome.

I searched for specific flags that could prevent cookies from being stored incorrectly but could not find anything useful.

Is Puppeteer the cause here? Should I open this issue in DevTools instead?

**Comment by vc1** [comment]
goole.com    the unlogged page is 2 cookies

```javascript
var cookies = await page.cookies()
```
No URL gets all of the cookies on this page

**Comment by PierrickLozach** [comment]
Makes sense. Thanks!
