### ISSUE TITLE
"Protocol error (Page.captureScreenshot): Target closed"

### ISSUE THREAD

**Issue by AntiBlueQuirk** [puppeteer/puppeteer#2255]
* Puppeteer version: 1.2.0
* Platform / OS version: Windows 10
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

1. Call page.screenshot() with very large values for clip.width and clip.height

**What happens?**

While developing an application, I accidentally ended up calling page.screenshot() with very large clip dimensions (around 20000x30000). It took me while to trace the error down, because I got this error:

    Protocol error (Page.captureScreenshot): Target closed.

By enabling dumpio, I was able to get this error from Chromium, which I was apparently crashing.

    ...INFO:SkBitmap.h(499)] ../../third_party/skia/include/core/SkBitmap.h(499): fatal error: "assert(this->tryAllocPixels(info, rowBytes))"

Other similar issues (#1790, #1385) mentioned that running out of memory might be a problem, however I was sure that wasn't the case, so I decided to check the clip values I was sending to the screenshot function, which is when I discovered the error. After changing the size to a more reasonable value, the function works fine.

**What is the expected result?**

page.screenshot() should either be changed to handle large clip sizes more gracefully, or throw an error about unreasonable/unsafe clip sizes, instead of crashing the underlying Chromium process.

**Comment by egorov** [comment]
After some investigation I resolved same error within my code. Page I load send multiple XHR requests and if I try to make screenshot until all responses received I've got same error.

This code sample execution doesn't throw the above error:

```javascript
  const puppeteer = require('puppeteer');
  const headers = {
    'accept-language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6,it;q=0.5',
    'accept-encoding': 'gzip, deflate, br',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
  };

  (async () => {

    const browser = await puppeteer.launch({
      args: [
        '--no-sandbox', 
        '--headless', 
        '--disable-gpu', 
        '--disable-dev-shm-usage'
      ]
    });

    const page = await browser.newPage();
    await page.setViewport({width: 1920, height: 1080});
    await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36');
    await page.setExtraHTTPHeaders(headers);
    await page.goto('https://example.com/', {waitUntil: 'domcontentloaded'});

    let count = 0;

    await page.on('response', async(response) => {

      console.log('response', count++);
      
    });
    
    await page.on('load', async(content) => {

      try {
        console.log('content type', typeof content);

        await page.screenshot({path: 'example-home.png'});
      }
      catch(error) {
        console.log('error', error.message);
      }
      finally {
        await browser.close();
      }
    });
  })();
```
