### ISSUE TITLE
Launch plan for 1.0 🚀

### ISSUE THREAD

**Issue by addyosmani** [puppeteer/puppeteer#226]
We'll aim to do this a little closer to October.

- [ ] **Decide where a Puppeteer landing page should go**. Options: 1) [Tools section](https://developers.google.com/web/tools/lighthouse/) on developers.google.com/web - This would place it alongside Lighthouse, DevTools and out other open-source tools. I would recommend we do this. 2) The other option is a GitHub pages. @paulirish @ebidel preferences?

- [ ]  **Setup landing page.** I suggest we take the README intro and FAQ copy (with some further helpful text about the project). It would be nice to be able to show something visual on there, like a screenshot of Puppeteer being used. Direct folks to the repo for everything else. **Proposed owner**: @kaycebasques or @ebidel? 

- [ ] **Decide if you would like branding/art/logo**. If the Puppeteer name is locked down, I can start a thread with @pavelfeldman, @paulirish @ebidel with the agency that did the Lighthouse logo to do a similar one for this project. Yay/nay?

- [ ] **Write the launch/announcement post for the project.** This should clearly set expectations like, what is Puppeteer trying to solve and what is it _not_. We can talk about how it has a smaller, focused scope compared to Phantom. Mention some of the [examples](https://github.com/GoogleChrome/puppeteer/tree/master/examples). Provide direction for feature requests that are out of scope etc. **Owner:** @ebidel 

- [ ] **Do a pre-launch repo review/tidy-up**. There a very minor things we can do, like ensure the README mentions and links up to the project license, mentions `npm` install instructions (folks like me are switching back from `yarn` to npm5), we're using the Releases page for notes etc. **Proposed owner:** @aslushnikov 

- [ ] **Pick launch date and prepare social posts for ChromiumDev** I might propose aiming to launch 2 weeks from now (Wednesday, August 23rd). If we need branding for launch, it'll push it out a week or two, but branding can also be added later on, similar to the Lighthouse launch. **Launch date owners:** @paulirish @pavelfeldman @ebidel

**Comment by ebidel** [comment]
Do we want 1 & 2 now or wait a bit? We talked about keeping the release low key: beef up the repo FAQ and README, add a project explainer, justification/comparison to existing tools, [add better examples](https://github.com/GoogleChrome/puppeteer/issues/178), etc. Might be too soon for resources on d.g.c. The project is alpha and still lots of iteration going on :)

Launch post sgtm. I can start that.

Think  [we're set on the name](https://github.com/GoogleChrome/puppeteer/issues/80#issuecomment-319503551), so starting logo/branding sgtm. Please loop in @paulirish and myself.

**Comment by aslushnikov** [comment]
> We talked about keeping the release low key: beef up the repo FAQ and README, add a project explainer, justification/comparison to existing tools, add better examples, etc. 

We want to start with discretely making the repo public. The motivation is to have more dogfooders checking out the API and filing bugs.

We probably don't need much for this, it still will be an alpha, and the API still will be in flux. We'll cut some of our features for now to make the api look consistent (such as touch support), more on this is here: #227

The suggested date is **Monday, Aug 14**.  @ebidel will it be enough time for the post?

**Comment by addyosmani** [comment]
After discussing this further in-person, sounds like we're doing a mostly repo-focused light launch. We'll follow this up later in the year with a proper full launch with the above items.

**Comment by Garbee** [comment]
I'm +1 to add the main doc site to the developer portal vs github pages. Even though I don't like the repo size entailed with contributing to that, it would keep as much of the documentation for these things centralized for viewing. Which is a big benefit for developers to only need to remember one place to go.
