### ISSUE TITLE
Page.pdf freezed

### ISSUE THREAD

**Issue by jeffguorg** [puppeteer/puppeteer#2260]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0, 1.2.0
* Platform / OS version: CentOS 7(inside docker. host kernel ver: 4.13.0-37-generic #42-Ubuntu)
* URLs (if applicable): https://mp.weixin.qq.com/s?__biz=MzA3MTYyODU3Ng==&mid=2649751241&idx=1&sn=68be53a4a4562fc32cee7b1f3a492dc5&chksm=8731fc86b04675902ff8557d06ed279d8f1b326546c84e45eac1a495446f2e1e4786e737c4c2&mpshare=1&scene=1&srcid=0320nLXUl37EcakhYdoVmXIi#rd
* Node.js version: nodejs 9.6.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
a piece of the worker: 
```
    await page.goto(address, { waitUntil: 'networkidle2' , timeout: timeout});

    let title = await page.title() || 'BlankTitle';
    //let filename = title.split(/[\/\\\:*?"><|\x00-\x1F\x7F]/g).join(" ") + '.pdf';
    let filename = 'test.pdf';

    log(5, "saving to pdf ", path.join(directory, filename));
    await page.pdf({path: path.join(directory, filename), format: size, scale: 2}); // stopped here and never goes forward
```

0. built an image containing the code, nodejs script running as a normal user inside the container. the script does the following:
1. start a browser instance in puppeteer
2. navigate to the web page
3. save to pdf
4. stopped here

**What is the expected result?**

there should be a pdf file

**What happens instead?**

stopped @ step 4

### Some other things

**debug**
set in docker-compose
- environment:
    DEBUG: "puppeteer:*"
docker-compose logs get this:
[urltopdf.log](https://github.com/GoogleChrome/puppeteer/files/1846234/urltopdf.log)

**some of my thoughts**
I firstly suspect that it is due to filename containing Chinese chars. but the problem exists after I name it test.pdf.
I then wondered if it's related to having viewport resized. but the problem still appears after i commented out the line.
then I found that the puppeteer debug message stops after a session message & 2 protocol message:
session SEND > { "id": 12, "method": "PAge.printToPDF", ... }
protocol SEND > { "id": 15, "method": "Target.sendMessageToTarget", ... }
protocol < RECV { "id": 15, "result": {} }
it should be related to the problem i met. 

and if i run the script locally, the problem disappears

**Comment by jeffguorg** [comment]
this problem occurs only inside a docker or a clean CentOS environment

**Comment by aslushnikov** [comment]
This looks like an issue with your environment. It might be that folks at chromium-dev google group have encountered this before, so I'd try writing there.

Closing this since this doesn't look like a pptr-related issue.
