### ISSUE TITLE
`page.setUserAgent()` is not working

### ISSUE THREAD

**Issue by SidKwok** [puppeteer/puppeteer#2261]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: macOS 10.13.3
* URLs (if applicable):
* Node.js version: 8.10.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox'
        ]
    });

const page = await browser.newPage();
await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/67.0.3372.0 Safari/537.36');
await page.goto('https://www.google.com');

console.log(await browser.userAgent());

await browser.close();
```

**What is the expected result?**
`userAgent` is set.

**What happens instead?**
`userAgent` is not set

**More**
[This demo](https://try-puppeteer.appspot.com/) is fine, but when put the code in my environment, `page.setUserAgent` is not working.

**Comment by hermano360** [comment]
Have you tried using the following useragent: 

Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1

That was the fix for me.

**Comment by JoelEinbinder** [comment]
`browser.userAgent` gives the default user agent, not the one you set for the page. You can use
```js
await page.evaluate('navigator.userAgent');
```
to see that your user agent was overridden successfully.
