### ISSUE TITLE
Problem with PUPPETEER_SKIP_CHROMIUM_DOWNLOAD

### ISSUE THREAD

**Issue by Tmin10** [puppeteer/puppeteer#2262]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: windows 10 x64
* URLs (if applicable): -
* Node.js version: 8.1.3 / NPM: 4.1.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Add `"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD": true` into package.json config section.
2. Add `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` to local .npmrc file.
3. Run `npm config set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true` to put property in global .npmrc file.
4. Run `npm i puppeteer` to install puppeteer.

**What is the expected result?**
Puppeteer won't download chromium.

**What happens instead?**
Puppeteer downloaded chromium. (-_-)

In [install.js](https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L19) we can see that puppeteer tries to read `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`, `NPM_CONFIG_PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` and `npm_config_puppeteer_skip_chromium_download` environment variables and didn't read any config. 

How it could work? Who should have to fill this variables if I would like to use only npm config without global envirements?

**Comment by jeffguorg** [comment]
try this:
```bash
env PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm i puppeteer
```
or just set it in your shell and run npm
```bash
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
npm i puppeteer
```
i'm not experienced in node.js, but if i'm right, process.env only reads environment variables from the parent of the process, which is your shell.

**Comment by alixaxel** [comment]
@Tmin10 Check the solution on #2270.

**Comment by kwkbtr** [comment]
I tried this by adding the following to `package.json` and it did not work:

```json
"config": {
  "puppeteer_skip_chromium_download": true
}
```

According to [npm documentation](https://docs.npmjs.com/files/package.json#config), the variable specified in `package.json` is prefixed by `npm_package_config_`, not `npm_config_`.
It would be useful if the [install.js](https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L23) checks the former one too.

(I thought that adding the variable to `package.json` would work when I read [the description about environment variables](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables) but now I realize that the description refers to `npm config`, not `config` variable in `package.json`)

**Comment by aslushnikov** [comment]
Dupe of #2270.

> It would be useful if the install.js checks the former one too.

@kwkbtr feel free to send a PR.

**Comment by sapanprajapati** [comment]
Simply do this.
**npm config set puppeteer_skip_chromium_download true -g**
working for me like charm :)

**Comment by icfantv** [comment]
To build on @sapanprajapati's answer above, please see my comment in #2270.  It appears you don't need this as a global setting, rather you can just make it at the project level.
