### ISSUE TITLE
Bug: element.screenshot() incorrect behaviour on 1.2.0

### ISSUE THREAD

**Issue by Glennvd** [puppeteer/puppeteer#2263]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: debian jessie
* URLs (if applicable): eg. https://uk.hotels.com/ho468055/?arrivalDate=29-03-2018&cur=SEK&departureDate=30-03-2018&destinationId=&hotelid=468055&previousDateful=false&roomno=1&rooms[0].numberOfAdults=2&tab=description&validate=false&view=prices
* Node.js version: 8.9.3

**What steps will reproduce the problem?**

This issue only occurs on certain dates on the link above, on puppeteer 1.2.0. If the element is longer than the viewport(?) or on puppeteer 1.1.1 the issue does not occur.

Go to hotels.com and take a screenshot of the #rooms-and-rates element

https://try-puppeteer.appspot.com/ code

```
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto('https://uk.hotels.com/ho468055/?arrivalDate=29-03-2018&cur=SEK&departureDate=30-03-2018&destinationId=&hotelid=468055&previousDateful=false&roomno=1&rooms[0].numberOfAdults=2&tab=description&validate=false&view=prices', {waitUntil: 'domcontentloaded'});
await page.waitForSelector('.current-price');
let element =  await page.$('#rooms-and-rates');

await element.screenshot({path: 'screenshot.png'});

await browser.close();
```

**What is the expected result?**
![Imgur](https://i.imgur.com/0u35O0n.png)
(Result on puppeteer 1.1.1)

**What happens instead?**
![Imgur](https://i.imgur.com/WHzbPrJ.png)
(Result on puppeteer 1.2.0)

Full page screenshots behave the same on 1.1.1 and 1.2.0

**Comment by yanivefraim** [comment]
I guess it is related to this [commit](https://github.com/GoogleChrome/puppeteer/commit/56a475f86bba60466299e05cf95ccf14b74fafd9#diff-4cd4f0d229de6644849d99ea455929beR161)
