### ISSUE TITLE
forceKillChrome() creates Core Dump Files

### ISSUE THREAD

**Issue by alixaxel** [puppeteer/puppeteer#2264]
It appears that the `forceKillChrome()` method in:

https://github.com/GoogleChrome/puppeteer/blob/47481967c5344dc0ca17ebaf4bd3d9650da771d0/lib/Launcher.js#L177-L195

Results in a core dump file (~16MB) being created on every shutdown, likely because of `SIGKILL`.

In environments like AWS Lambda where disk space is severely limited, this can become problematic.

It would be nice if Chromium would be closed gracefully, but I don't know if this is even an option.

**Comment by alixaxel** [comment]
This seems to affect only AWS Lambda environment. Related to https://github.com/GoogleChrome/puppeteer/issues/1825.

**Comment by Kikobeats** [comment]
@alixaxel do you know how to force kill the process, without using an external library? also, I'm interested in turn off core dump files since they are not useful on production scenarios.
