### ISSUE TITLE
How slowMo should work?

### ISSUE THREAD

**Issue by Diokuz** [puppeteer/puppeteer#2265]
Its not a bug, I guess...

The question is: how exactly `slowMo` should work?

For example, I set it to `slowMo: 15000`, and the only thing happens (in non-headless mode): chromium waits 15 seconds before load page. But no delays inside tests (I have many `waitForSelector`, `keyboard.press` and `type` instructions inside tests). So, tests are executed really fast, cant see anything.

I assumed, puppeteer will wait _every_ instruction for 15 seconds. Am I wrong?

I use `jest-puppeteer@2.2.0` which uses `puppeteer@1.2.0` which uses `Chromium r543305` or my `Chrome 65.0.3325.162`

Related https://github.com/smooth-code/jest-puppeteer/issues/20

**Comment by aslushnikov** [comment]
> But no delays inside tests (I have many waitForSelector, keyboard.press and type instructions inside tests). So, tests are executed really fast, cant see anything.

@Diokuz this doesn't sound right to me. Do you have a minimalistic pptr script that illustrates the issue?
The `slowMo` option just throttles connection between browser and puppeteer:

https://github.com/GoogleChrome/puppeteer/blob/fafd156d7bd9941131ab31f5af7cf047e728142c/lib/Connection.js#L100-L104

**Comment by aslushnikov** [comment]
Ah, looks like this has been fixed with https://github.com/smooth-code/jest-puppeteer/pull/24
