### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: text is not iterable

### ISSUE THREAD

**Issue by putuoka** [puppeteer/puppeteer#2266]
i tried to iterate "type" function to keep puppeteer typing into page

```
var guesses = 0;
var breakTheLoop = false;
while (guesses < 3) {
        await page.keyboard.type(guesses);
        await page.waitFor(2000);
        guesses = guesses + 1;
}
```
![image](https://user-images.githubusercontent.com/20880839/37945711-13cac438-31b4-11e8-9cb8-43a7bb0d4360.png)

**Comment by putuoka** [comment]
sorry my mistake. it should not pass integer into type function

**Comment by mauricionr** [comment]
the `type` method could call `toString` in this case or a better exception
