### ISSUE TITLE
Cannot `pkg` puppeteer app due to ExecutionContext.js - SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by nddipiazza** [puppeteer/puppeteer#2267]
pkg version: 4.3.0
node version: v9.8.0
puppeteer version: 1.2.0

Hi all. I am having an issue launching a nodejs packaged app with puppeteer. The app works fine when launched directly from nodejs. But fails from the `pkg`'d linux app.

Here is the simple puppeteer application:

**package.json:**

```
    {
      "name": "puppeteer-js-eval-tool",
      "version": "1.0",
      "bin": "puppeteer-js-eval.js",
      "dependencies": {
        "command-line-args": "5.0.2",
        "puppeteer": "1.2.0"
      }
    }
```

**puppeteer-js-eval.js**

```
    const puppeteer = require('puppeteer');
    const commandLineArgs = require('command-line-args')
    const optionDefinitions = [
      { name: 'chromeBinaryPath', type: String },
      { name: 'request', type: String, multiple: true },
      { name: 'requestCounterMaxWaitMs', type: Number },
      { name: 'headless', type: Boolean },
      { name: 'diagnosticMode', type: Boolean },
      { name: 'cookie', type: String, multiple: true }
    ]
    const options = commandLineArgs(optionDefinitions)
    var chromeBinaryPath = options['chromeBinaryPath']
    var requests = options['request'];
    var requestCounterMaxWaitMs = parseInt(options['requestCounterMaxWaitMs']);
    var diagnosticMode = options['diagnosticMode'];
    var headless = options['headless'] !== undefined ? options['headless'] : false;
    
    (async () => {
      const browser = await puppeteer.launch({executablePath: chromeBinaryPath, headless: headless, args:['--no-sandbox', '--disable-setuid-sandbox', '--mute-audio']});
      const promises=[];
      for (let i = 0; i < requests.length; i++ ) {
        promises.push(browser.newPage().then(
          async page => {
            await page.setRequestInterception(true);
            page.on("request", (request) => {
              if (request.resourceType() === "image" || request.resourceType() === "font" || request.resourceType() === "media") {
                //console.log("Request intercepted! ", request.url(), request.resourceType());
                request.abort();
              } else {
                request.continue();
              }
            });
            console.log("delay = ", requestCounterMaxWaitMs);
            var request = requests[i];
            try {
              await page.goto(request, { waitUntil: ['networkidle0', 'load'], timeout: requestCounterMaxWaitMs });
            } catch (e) {
              console.log("Timed out waiting for networkidle for ", request);
            }
            try {
              const html = await page.$eval('html', ev => ev.outerHTML);  
              //console.log('html:', html);
              console.log('Done loading! ', request);
            } catch (e) {
              console.log("Error when requesting  ", request, e);
            }
            
        }));
      }
      await Promise.all(promises)
      await browser.close();
    })();
```

**Installation:**

`sudo npm install puppeteer --unsafe-perm=true`
`sudo npm install command-line-args`

**Package command:** 

`pkg .`

Seems to work?

```
~/Desktop/puppeteer-eval $ pkg .
> pkg@4.3.0
> Targets not specified. Assuming:
  node9-linux-x64, node9-macos-x64, node9-win-x64
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules/puppeteer/.local-chromium
  path-to-executable/puppeteer
```

But launching the program fails at the end. 

**Program output:**

```
./puppeteer-js-eval-tool-linux --chromeBinaryPath /usr/bin/chromium-browser --requestCounterMaxWaitMs 2500 --request https://support.microsoft.com/sv-se/help/12407/microsoft-account-manage-aliases
delay =  2500
Timed out waiting for networkidle for  https://support.microsoft.com/sv-se/help/12407/microsoft-account-manage-aliases
Error when requesting   https://support.microsoft.com/sv-se/help/12407/microsoft-account-manage-aliases Error: Evaluation failed: SyntaxError: Unexpected identifier
    at ExecutionContext.evaluateHandle (/snapshot/Desktop/puppeteer-eval/node_modules/puppeteer/lib/ExecutionContext.js:79:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Works all the way down to this particular line:

`const html = await page.$eval('html', ev => ev.outerHTML);  `

then fails at

```
 SyntaxError: Unexpected identifier
    at ExecutionContext.evaluateHandle (/snapshot/Desktop/puppeteer-eval/node_modules/puppeteer/lib/ExecutionContext.js:79:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Does anyone know how to package a puppeteer app? Is this a bug, or am I just missing a step while packaging?

**Comment by MaksJS** [comment]
I had the same problem with NW.js and nwjc (a tool to protect javascript source code). Nwjc convert your javascript code to V8 snapshot (like pkg I guess). When you run in "ExecutionContext.evaluateHandle" function, the first parameter is "pageFunction". Then when you start the application with node.js, everything works, you get a function like (e, t) => ... But with packaged app, you get function { [native code] } because function is evaluated at runtime by the client instance (Runtime.callFunction in the code of Puppeteer)... That's you get a "SyntaxError: Unexpected identifier" error without any explanation. Got me hours to figure out why

**Comment by nddipiazza** [comment]
@MaksJS Hi thanks for the response. Are you saying you did get it to work? I played around with nw and came up with no solution from that. Please send me the set of steps you got the linux binary built with.

**Comment by MaksJS** [comment]
@nddipiazza Hi, yes I got it working with nw.js without any problem. You just can't use nwjc to compile to native code. 

To get a binary, you could just webpack your project and use nw-builder : https://github.com/nwjs-community/nw-builder

**Comment by nddipiazza** [comment]
@MaksJS i tried that. the result was HUGE. 200+ mb.  i'm going to probably stop using puppeteer and use chrome-remote-interface. too many issues with puppeteer. not worth it.

**Comment by MaksJS** [comment]
That's normal because nw executable weights about 200mb. You could use chromedriver with selenium, it's shipped with nw's sdk.

**Comment by paulirish** [comment]
I don't know much about pkg but it seems to be using babel? if so, i imagine the `pageFunction`s that you're passing to `$$eval` are getting mixed up. You can pass strings instead of real functions to the `*eval` methods, so.... if you did that, I imagine babel wouldn't fuck things up.

You could also try disabling babel when `pkg` runs?

**Comment by aslushnikov** [comment]
I don't think there's much else we can do here.

**Comment by entrptaher** [comment]
EDIT: I was wondering why I got downvoted many times, it's because of a 404 page and the solution I provided was not working anymore. This seems to have lots of side-effects. Check this for a working solution instead. https://github.com/zeit/pkg/issues/204#issuecomment-536323464

**Comment by frostyandy2k** [comment]
The above from @entrptaher throws the following error:

```
 >>>> pkg -t host --out-path dist index.js
> pkg@4.4.3
> Warning Cannot resolve '`process.cwd() + "/node_modules/puppeteer"`'
  /Users/andrei.miclaus@flywire.com/code/flywire/flystore/ui/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

On execution I get this error:
```
Error: Cannot find module '/Users/andrei.miclaus@flywire.com/code/flywire/flystore/ui/dist/node_modules/puppeteer'
Require stack:
- /snapshot/ui/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/snapshot/ui/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/ui/index.js' ]
}
```

I had to use this directory structure:

```
// ui is my root source folder
   |-node_modules
   |---puppeteer
   |-----lib
   |-puppeteer
   |---ui
   |-----dist
   |-------node_modules
   |---------puppeteer
   |-------------.local_chromium
   |-screenshots
```
Probably due to the dynamic require.
So basically 1 folder for node_modules content and another for Chromium.

I created a repo with a release here:
https://github.com/frostyandy2k/browser-screenshots/releases/tag/v0.1

Repo link with js code: https://github.com/frostyandy2k/browser-screenshots

**Comment by Alireza17224** [comment]
Same issue here
