### ISSUE TITLE
How can I download an exe file?

### ISSUE THREAD

**Issue by evgo2017** [puppeteer/puppeteer#2268]
I want to download an exe file, but when it finish, the Chromium will show save or abandon. I can't fix it. And I didn't find an suitable API  like "page.download(url)".

**Comment by vsemozhetbyt** [comment]
If you can predict this will be a downloadable file, maybe you can just try to use `curl` with `child_process` calls?

**Comment by evgo2017** [comment]
I find a library whose name is [download](https://www.npmjs.com/package/download) .
`download(url).pipe(fs.createWriteStream(data[i].name+'.exe'));`
I get the files ~
But I find if I change the way of writing what not change the filename, it won't work. 
So the question is still exist for me. 
I should study the `curl`.

Thanks your advice.

**Comment by aslushnikov** [comment]
Also, feel free to upvote #299 to get downloading in pptr.
