### ISSUE TITLE
Prepare for initial launch

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#227]
- [x] ~~remove touch support for now~~ **keeping this since @dgozman fixed the bug!**
- [x] implement the desired interception API with the client-side matching logic
- [x] merge @pavelfeldman's target domain migration
- [x] introduce browser.version() to the protocol and use it instead of JSON commands
- [x] fix protocol's mouse events to wait for the event to be dispatched (remove [doubleRaf](https://github.com/GoogleChrome/puppeteer/blob/29adc5dc80649ba062cf44c08391ae62a1a1d327/lib/Input.js#L139) hack)
- [x] split out [phantom shim](https://github.com/GoogleChrome/puppeteer/tree/34b0095c10e67a022a01cfdc22df61fbb56bb1fb/phantom_shim) into a separate repo? (@paulirish suggested to keep it in but release as a separate project)
- [x] `Runtime.evaluate` with `awaitPromise: true` should throw when parent context destroys (@ak239 has WIP upstream)

**Comment by aslushnikov** [comment]
@JoelEinbinder Do we still need to remove the touch support? If yes, could you please do this?

**Comment by JoelEinbinder** [comment]
We can wait for https://chromium-review.googlesource.com/c/609373 to land, and leave touch enabled.

**Comment by aslushnikov** [comment]
With a special README for phantom_shim in place, considering this to be fixed.
