### ISSUE TITLE
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD not respected in NPM Config

### ISSUE THREAD

**Issue by alixaxel** [puppeteer/puppeteer#2270]
**Environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Ubuntu 16.04 LTS
* Node.js version: 8.10.0 (NPM 5.6.0)

**What steps will reproduce the problem?**

1. Add `puppeteer` as a dependency in `package.json`.
2. In the same level as `package.json`, create a `.npmrc` file.
3. Set the content of `.npmrc` to `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"`.
4. Run `npm install`.

**What is the expected result?**

Puppeteer should skip Chromium download, according to:

https://github.com/GoogleChrome/puppeteer/blob/a363a733b7aa88be9a17190bcfa924b507d7b3da/install.js#L19-L26

**What happens instead?**

Chromium is downloaded regardless.

**Comment by AndreasZeiser** [comment]
You should use the lower cased version of `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` in `.npmrc`. `puppeteer_skip_chromium_download=true` works for me.

**Comment by alixaxel** [comment]
@AndreasZeiser Ah, it works! Thanks for this insight. :+1:

**Comment by steven-pribilinskiy** [comment]
@AndreasZeiser is there any explanation on why it should be lowercased?

**Comment by AndreasZeiser** [comment]
@pribilinskiy I can't remember exactly but I think it's because inside npm-scripts Node prefers the lowercase version. More info here: https://docs.npmjs.com/misc/config#environment-variables

**Comment by sapanprajapati** [comment]
Simply do this.
**npm config set puppeteer_skip_chromium_download true -g**
working for me like charm :)

**Comment by icfantv** [comment]
For anyone else coming here, by default, it appears that the default file for `npm config set ...` is `~/.npmrc`.  However, it also appears that if you put an `.npmrc` file in the root folder of your repo and put `puppeteer_skip_chromium_download=true` in that file, NPM sets it, and thus, the puppeteer install respects it.  From my `yarn install` log:

```
[5/5] Building fresh packages...
verbose 13.216 **INFO** Skipping Chromium download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" was set in npm config.
```

**Comment by raDiesle** [comment]
adding it to .npmrc has no effect when using 
`npm ci`
     but 
`npm install` works

this seems to be a bug.

environment:
Windows 10 
puppeteer v1.19.0

**Comment by DaveJarvis** [comment]
In other words:

``` bash
sudo su -
echo "puppeteer_skip_chromium_download=true" >> $HOME/.npmrc
exit
```

Then try running npm again.

**Comment by icfantv** [comment]
@DaveJarvis what's the context around using `sudo` and `exit`?  You shouldn't need that to edit a file in your own, home directory.  I.e., the `echo` command should suffice on its own.

**Comment by DaveJarvis** [comment]
@icfantv - When I added "puppeteer_skip_chromium_download=true" to `$HOME/.npmrc` as a regular user, the same error appeared. It was only when I added the line to `/root/.npmrc` did the problem get resolved. To be specific:

*Replicate - Failure*

1. Log in as normal user.
1. Edit `$HOME/.npmrc`
1. Append `puppeteer_skip_chromium_download=true`
1. Install a package (e.g., `npm install --global mermaid-filter`)

*Replicate - Success*

1. Log in as normal user
1. Change to `root` user (i.e., `sudo su -`)
1. Edit `$HOME/.npmrc`
1. Append `puppeteer_skip_chromium_download=true`
1. Log out of `root` user (i.e., `exit` from the `sudo`'d shell)
1. Install a package (e.g., `sudo npm install --global mermaid-filter`)

**Comment by icfantv** [comment]
If I'm being honest, something is very strange with your setup.  I'm not saying you didn't have to do what you did to get it to work for you.  But something is very, very strange.  When you do a `sudo su -` it logs you in as the `root` user.  According [to NodeJS' own documentation](https://docs.npmjs.com/files/npmrc), there is no mention of the `root` user needing to control an `.npmrc` file.

**Comment by ghost** [comment]
Here's how I addressed the issues. First, update .bashrc with:

``` bash
export NPM_GLOBAL_HOME=$HOME/.npm-global
export PATH="$PATH:${NPM_GLOBAL_HOME}/bin"
```

Then, after launching a new terminal:

``` bash
mkdir -p "${NPM_GLOBAL_HOME}"
npm config set prefix "${NPM_GLOBAL_HOME}"
npm config set registry http://registry.npmjs.org/  
```

At this point, running `npm install -g` or `npx install` worked as a regular user.

**Comment by usahai** [comment]
> For anyone else coming here, by default, it appears that the default file for `npm config set ...` is `~/.npmrc`. However, it also appears that if you put an `.npmrc` file in the root folder of your repo and put `puppeteer_skip_chromium_download=true` in that file, NPM sets it, and thus, the puppeteer install respects it. From my `yarn install` log:
> 
> ```
> [5/5] Building fresh packages...
> verbose 13.216 **INFO** Skipping Chromium download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" was set in npm config.
> ```

This worked for me.
