### ISSUE TITLE
How to download a file from a new window

### ISSUE THREAD

**Issue by Sharma-Rajat** [puppeteer/puppeteer#2271]
Hi Guys!

Here is my issue: When I click a `selector` to download some files a couple of windows are opened and they automatically downloaded files. All of these downloads are saved to my downloads directory on my mac instead of a directory in my node application. How can I make auto downloads in new windows opened one after the other download to a directory of my choosing?

I tried the below but obviously it only attaches to the page and not the poppup windows right?

```js
async function saveLocally(page, frame) {
  const RETRIEVE_SELECTOR = '#Form1 > table:nth-child(8) > tbody > tr > td:nth-child(2) > a:nth-child(1)';
  await page._client.send('Page.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath: '/build/tmp',
  });
  try {
    await page.click(RETRIEVE_SELECTOR);
  } catch (e) {
    Log.error(e);
    return {
      message: `❌󠀠 error: ${e}`,
    };
  }
}
```

thanks 👍 

EDIT:

I managed to get it working but the problem is now that it misses some of the popup windows. When i click retrieve selector it opens 3-4 windows at once. I only get two downloads in the correct directory. Any ideas?

```js
async function saveLocally(browser, page, frame) {
  const RETRIEVE_SELECTOR = '#Form1 > table:nth-child(8) > tbody > tr > td:nth-child(2) > a:nth-child(1)';
  await page.click(RETRIEVE_SELECTOR);
  await browser.on('targetcreated', async () => {
    const pageList = await browser.pages();
    pageList.forEach((page) => {
      page._client.send('Page.setDownloadBehavior', {
        behavior: 'allow',
        downloadPath: './tmp',
      });
    });
  });
}
````

**Comment by Sharma-Rajat** [comment]
any updates on this?

**Comment by Sharma-Rajat** [comment]
lmao? anyone..?

I changed it and got it working sort of.. Basically when I click a selector usually more than one page opens in new windows and start downloads automatically. I can catch 2-3 out of 5 of the downloads that occur with the code below... Any ideas on how to catch all of the downloads from all open windows as soon as they open?

```js
async function saveLocally(browser, page, frame) {
  const RETRIEVE_SELECTOR = '#Form1 > table:nth-child(8) > tbody > tr > td:nth-child(2) > a:nth-child(1)';
  await page.click(RETRIEVE_SELECTOR);
  await browser.on('targetcreated', async () => {
    const pageList = browser.pages();
    Log.info(pageList.length);
    pageList.forEach((page) => {
      page._client.send('Page.setDownloadBehavior', {
        behavior: 'allow',
        downloadPath: './tmp',
      });
    });
  });
}
```

**Comment by aslushnikov** [comment]
@Sharma-Rajat unfrotunately, we don't have a good downloads support ATM. We're working on a proper solution as a part of #299, but it takes longer than we've expected.

Please follow #299 for the updates.
