### ISSUE TITLE
Regex on click() selector

### ISSUE THREAD

**Issue by anthonyjdella** [puppeteer/puppeteer#2274]
For click("selector_here") method, my selector is changing values randomly. So I'm trying to click on a selector that contains xyz...

For example, one time it will be "#search-keyword-901131292" then it will change to something like "#search-keyword-123891237". It's a random number.

Can I use a regex or something to select selectors that contain "#search-keyword-"?

I've tried:

- page.click ("#search-keyword-*")
- page.click ("\b#search-keyword-\b")
- page.click ("/#search-keyword-/")
- page.click ("#search-keyword-".includes())

**Comment by vsemozhetbyt** [comment]
See https://drafts.csswg.org/selectors-4/#attribute-substrings

You need something like this:

```js
page.click('[id^="search-keyword-"]');
```

**Comment by anthonyjdella** [comment]
That fixed it. Thank you! @vsemozhetbyt
