### ISSUE TITLE
Add .browser() methods to page class

### ISSUE THREAD

**Issue by worudso** [puppeteer/puppeteer#2275]
I was writing ahelper function like
```typescript
async function waitForPopup(page: Page, name: string): Promise<Page> {
    // ...
}
```
which waits until popup with `name` as name and whose parent is `page` and return the popup.
But with current version of puppeteer. I have to add extra `browser` arg like below
```typescript
async function waitForPopup(browser: Browser, page: Page, name: string): Promise<Page> {
    // ...
}
```
because I can't get browser from `page`.
If `page.browser()` is there, I can omit that redundant `browser`.
```
`

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**


**What happens instead?**

**Comment by JoelEinbinder** [comment]
I'd rather add a proper `page.on('popup')` method.

**Comment by worudso** [comment]
@JoelEinbinder I agree that we need a better way to get the parent of a popup.
But the code above is just an example and I think there can be more usages of `.browser()` method.

**Comment by aslushnikov** [comment]
@worudso `.browser()` is reasonable; feel free to add.

**Comment by KBPratap** [comment]
I am getting an error when I try calling page.browser()

`UnhandledPromiseRejectionWarning: TypeError: page.browser is not a function
(node:66840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
`
Is this api broken?

**Comment by yanivefraim** [comment]
@KBPratap - this feature is not yet released. You can use `npm i --save puppeteer@next` (see [here](https://github.com/GoogleChrome/puppeteer#q-how-do-i-trytest-a-prerelease-version-of-puppeteer)) in order to use pre release version of puppeteer
