### ISSUE TITLE
wrong request.postData()

### ISSUE THREAD

**Issue by RuslanTT** [puppeteer/puppeteer#2277]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: ubuntu 16.04
* URLs (if applicable):
* Node.js version: 8.8.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
Hi guys, i am trying to intercept request and get raw request post data. I send 4 bytes as xhr, and wants to find them at request. But: 

```
var bytesToSend = [0xac, 0xed, 0x00, 0x05],
    bytesArray = new Uint8Array(bytesToSend);

    var xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://testsite.loc/tests/testserialized.php', false);
    xhr.setRequestHeader('Content-Type', 'application/octet-stream');
    xhr.send(bytesArray);
```
```
let text = request.postData();
                const fs = require('fs');
                let filename= __dirname + '/../tests/testserialize.txt';
                fs.writeFile(filename, text, function(err) {
                    if(err) {
                        return console.log(err);
                    }

                    console.log("The file was saved!");
                });
```
**What is the expected result?**
expected result to recieve 4 bytes as it was sended

**What happens instead?**
instead i recieve 8 bites at request.postData(); As i understand, this function convert post to 2 bytes per symbol string, can i get raw request post data?

**Comment by OrKoN** [comment]
Could you please re-test with the latest Puppeteer version?
