### ISSUE TITLE
Protocol error (Network.getResponseBody) on response.text() if the response body refresh the page

### ISSUE THREAD

**Issue by phackt** [puppeteer/puppeteer#2284]
### Steps to reproduce
  
**Tell us about your environment:**
* Puppeteer version: "1.2.0"
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable): https://www.mines.org
* Node.js version: v8.10.0
  
**What steps will reproduce the problem?**
Hello Folks,
Requesting this url: **https://www.mines.org**, a *Protocol error* is raised when the Promise response.text() try to be resolved. Important to note that the requested resource has the following code in its response body:
```
<script type="text/javascript">
        document.write('<META HTTP-EQUIV="Refresh" CONTENT="0;URL=\'gene/main.php?sizeup_=&sizeup2009=&referer2=&poste='+Na_i+'\'">');
</script>
``` 
  
I succeeded in reproducing the issue with the following example.js code:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // Capture all responses
  page.on('response', response => {
  	console.log(response.url())
  	response.text().then(
	    function(result) {
	    	console.log(result);
		});
  });


  await page.goto('https://www.mines.org');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```
  
Here is the console output:
```
$ node example.js
https://www.mines.org/
(node:1948) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getResponseBody): Target closed.
    at Promise (/tmp/test/node_modules/puppeteer/lib/Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/tmp/test/node_modules/puppeteer/lib/Connection.js:197:12)
    at _contentPromise._request._completePromise.then (/tmp/test/node_modules/puppeteer/lib/NetworkManager.js:584:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
  
Any idea about this ?
Thanks in advance,

**Comment by aslushnikov** [comment]
@phackt you have a race condition in your code:
- for every response, you kick off async process of getting its text
- in parallel, you're taking page screenshot and closing browser afterwards

When the browser is closed with the `response.text()` call in flight, you see this error.
To fix the error, you should either swallow all errors in `reponse.text()` or await all the inflight async operations before closing the browser.

Hope this helps!

**Comment by phackt** [comment]
Thanks @aslushnikov , finally i added a ```await page.waitForNavigation()``` just after the ```await page.goto(url)``` and things work fine.
Cheers,

**Comment by martijnvdbrug** [comment]
> Thanks @aslushnikov , finally i added a `await page.waitForNavigation()` just after the `await page.goto(url)` and things work fine.
> Cheers,

You could also do `page.goto('https://example.com', {waitUntil: 'networkidle2'})`

**Comment by y-nk** [comment]
@aslushnikov i'm bumping into the exact same error ; difference is that I don't close the browser (and leave the script hanging). any clue?

**Comment by KhalelAlbuquerque** [comment]
I had to change the module file

Path: node_modules/whatsapp-web.js/src/Client.js

Line 744: `await webCache.persist(await res.text());`

Change for:
`try{ await webCache.persist(await res.text()); }catch(err){ console.log(err.message) }`

Thx for @ting7777
