### ISSUE TITLE
[Feature Request] Monitor attribute change of an element.

### ISSUE THREAD

**Issue by NagarjunPrasad1** [puppeteer/puppeteer#2285]
A way to monitor attributes for a set element will be really helpful. For example many a time an element will be displayed due to addition of classes. So a way to monitor attribute changes like class addition or deletion would be helpful.

**Comment by ebidel** [comment]
Doesn't waitForSelector satisfy this use case?

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectorselector-options

**Comment by NagarjunPrasad1** [comment]
@ebidel I don't think that fits the case. For example in a page I am currently automating upon summiting a form a modal with a popup may come up (I say may because depending on the contents filled into the form the website sometimes sends in a popup and sometimes doesn't). Now what I want is a way to monitor this popup element, in my case the popup's "aria-hidden" attribute becomes false then I know that the popup had popped up. 

A way to monitor classes addition and deletion would also be helpful and would work similarly where if a class called say "display" gets added we can handle that change.

**Comment by aslushnikov** [comment]
> Now what I want is a way to monitor this popup element, in my case the popup's "aria-hidden" attribute becomes false then I know that the popup had popped up.

@NagarjunPrasad1  There are fancy CSS selectors that select based on node attribute value: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

In case of the popup, the following should do:
```js
const popupPromise = page.waitForSelector('.popup[aria-hidden=false]')
```

> A way to monitor classes addition and deletion would also be helpful and would work similarly where if a class called say "display" gets added we can handle that change.

Similar technique will do for class manipulations:
```js
const classPromise = page.waitForSelector('.my-element:has(.display)')
```

**Comment by ebidel** [comment]
`:has()` [isn't in browsers yet](https://caniuse.com/#feat=css-has), but you can definitely do similar to what @aslushnikov suggests and wait for the class to be added )and therefore, the selector to match):

```js
await page.waitForSelector('.my-element.display');
 ```

If it's already applied, you can wait for it to be removed:

```js
await page.waitForSelector('.my-element:not(.display)');
```

**Comment by ebidel** [comment]
Going to close. I think we covered all the scenarios :)
