### ISSUE TITLE
navigation timeout errors occurred after loaded page fully. 

### ISSUE THREAD

**Issue by awesomenkj** [puppeteer/puppeteer#2293]
`
	// click checkout button
	await page.click('aside.aside a[href="/checkout"]').then(() => {
		console.log('Going to Checkout Page')
	})
	.catch(err => {
		console.log(err)
	})

	 await page.waitForNavigation()
`

This is my code. 

It always makes navigation timeout error even though page is loaded already.

**Comment by vsemozhetbyt** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/1412
Especially https://github.com/GoogleChrome/puppeteer/issues/1412#issuecomment-345482273

**Comment by siggerzz** [comment]
@vsemozhetbyt From my experience this only works 50% of the time, for me.

```
await Promise.all([
  page.waitForNavigation() 
  page.click('a')
]);
```

It tends to work when navigating, however if you just want to click an element, and then wait for a network request to finish (with no navigation), it doesn't work. This only became an issue when updating from 0.13.0 > 1.2.0

**Comment by aslushnikov** [comment]
> It always makes navigation timeout error even though page is loaded already.

@xsmartweb in case of a same-document navigation (e.g. when only hash part of the URL changes, or when URL is modified by History API), follow updates on #257.

> It tends to work when navigating, however if you just want to click an element, and then wait for a network request to finish (with no navigation), it doesn't work. 

@siggerzz  "navigation" happens only whenever the URL of the page changes. Just sending requests doesn't trigger any navigation, thus "waitForNavigation" doesn't work.

Also, consider this comment for a workaround: https://github.com/GoogleChrome/puppeteer/issues/1412#issuecomment-379428743
