### ISSUE TITLE
Getting non-standard "global" variables defined on the window object.

### ISSUE THREAD

**Issue by motleycrew** [puppeteer/puppeteer#2294]
Hi there,

I am trying to get non-standard global variables defined in window objects set by different libraries for ex. Crypto mining etc..

For Example:. https://google.com
https://urlscan.io/result/0746f68b-e552-48b6-99d6-d6834a5184a4#behaviour

I am unable to do so. I have already tried slack channel but no response.

This is what have tried

```
const puppeteer = require('puppeteer');

async function fetchPage(srcUrl) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(srcUrl);
  const handle = await page.evaluateHandle(() => ({document}));
  const properties = await handle.getProperties();
  console.log(properties);
  await browser.close();
}
let args = process.argv.slice(2);
fetchPage(args[0]).then(
  () => {});
```

Any pointers will be great.

**Comment by vsemozhetbyt** [comment]
If you need to get all `window` properties as a list of strings, you can try this:

```js
console.log(await page.evaluate(() => Reflect.ownKeys(window)));
```

**Comment by motleycrew** [comment]
thanks this is useful but I am looking to just get variables unique to each page.  Another example

https://urlscan.io/result/3c174cb5-3464-48a8-893f-c0e6c85b106e#behaviour

iterating through all fields will be expensive (time wise)

**Comment by vsemozhetbyt** [comment]
Something like this then?
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');
    const commonProperties = await page.evaluate(() => Reflect.ownKeys(window));

    await page.goto('https://www.referyourchasecard.com/');
    const allProperties = await page.evaluate(() => Reflect.ownKeys(window));
    const customProperties =
      allProperties.filter(prop => !commonProperties.includes(prop));

    console.log(customProperties);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by motleycrew** [comment]
Thanks @vsemozhetbyt 

Interesting approach. This solution looks closer to what my use case. I can't fetch two pages every time I  scan a website. 

I need come up with  a way to filter commonly used variables without fetching another page.

**Comment by vsemozhetbyt** [comment]
@motleycrew Maybe you can cache `commonProperties` in a file?

**Comment by vsemozhetbyt** [comment]
BTW, beware https://github.com/GoogleChrome/puppeteer/issues/2295

If `window` contains Symbol keys, `Object.getOwnPropertyNames(window)` can be used instead of `Reflect.ownKeys(window)`

**Comment by aslushnikov** [comment]
The solution in https://github.com/GoogleChrome/puppeteer/issues/2294#issuecomment-377655549 looks very plausible, especially given the caching suggestion.
