### ISSUE TITLE
page.setViewport() throws and hangs if height parameter is not specified

### ISSUE THREAD

**Issue by YogeshSinghChouhan** [puppeteer/puppeteer#2298]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.2.0
* Platform / OS version:Windows 10
* URLs (if applicable):any
* Node.js version:8.9.4

**What steps will reproduce the problem?**

```node
'use strict';

const puppeteer = require('puppeteer');

(async() => {
  try{
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setViewport({width:1366}); //throws an error if height parameter is not specified
    await page.goto('https://www.google.co.in');
    await page.screenshot({path: 'example.png'});
    await browser.close();
  }
  catch(e)
  {
    console.error(e);
  }
  
})();

```
**What is the expected result?**
Screenshot with default height.

**What happens instead?**
```node
Error running your code. Error: Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters height: integer value expected
```

**Comment by aslushnikov** [comment]
> Screenshot with default height.

@YogeshSinghChouhan what's default height?

**Comment by YogeshSinghChouhan** [comment]
@aslushnikov 
If i take the screenshot without specifying viewport width and height ,screenshot will of dimension (800x**600**)

With this example i get screenshot of height 600px.

```node
'use strict';

const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://www.google.co.in');
    await page.screenshot({path: 'example.png'});
    await browser.close();
})();

```

So i am assuming **600px as default height**

My use case is, i want to take **full page screenshot** with **custom width**,like this 

```node
'use strict';

const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setViewport({width:1366}); //Custom Width
    await page.goto('https://www.google.co.in');
    await page.screenshot({path: 'example.png',fullPage:true});//Full Page Screenshot
    await browser.close();
})();

```
It is giving the error as stated above.

But i think if height is not specified, it should not halt the execution or neither say **Invalid parameters height: integer value expected**, instead it should set the default height itself.

**Comment by aslushnikov** [comment]
@YogeshSinghChouhan I see, thanks.

Current behavior is adequate wrt the method name. That would be the difference between `page.setViewport()` and `page.overrideViewport()`: the former has all rights to complain about wrong viewport properties, and the latter doesn't complain and just overrides given properties of the current viewport.

You can achieve desired behavior with the following:

```js
const override = Object.assign(page.viewport(), {width: 1366});
await page.setViewport(override);
```

**Comment by YogeshSinghChouhan** [comment]
@aslushnikov Thanks!!
