### ISSUE TITLE
Cookies broken into half

### ISSUE THREAD

**Issue by khmy2010** [puppeteer/puppeteer#2299]
I set cookies in one page using following code:
`       await this.page.setCookie({ name: 'session', value: session });`
        `await this.page.setCookie({ name: 'session.sig', value: sig });`
        `await console.log('before refresh: ', await this.page.cookies());`
      `  await this.page.goto(`${BASE_LINK}`, {
            timeout: 0
        }); //refresh`
      `  await this.page.waitFor('a[href="/discovery"]');`
      `  await console.log('after refresh: ', await this.page.cookies());`

When I console.log **before refresh: **
I had both cookies (session and session.sig)
considering the output below from the console.log
`      [ { name: 'session.sig',
          value: '5lwx-v91Tp0RrNtCMT-wBcWHE0c',
          domain: 'localhost',
          path: '/',
          expires: -1,
          size: 38,
          httpOnly: false,
          secure: false,
          session: true },
        { name: 'session',
          value: 'eyJwYXNzcG9ydCI6eyJ1c2VyIjoiNWFjMjJlNDk2YWViZTgwM2M1ZDdlMWZkIn19',
          domain: 'localhost',
          path: '/',
          expires: -1,
          size: 71,
          httpOnly: false,
          secure: false,
          session: true } ]`

The moment when I go to another link, I had only ONE and ONLY ONE cookie. (supposingly to be two)

Considering following output:
`      after refresh:  [ { name: 'session',
          value: 'eyJwYXNzcG9ydCI6eyJ1c2VyIjoiNWFjMjJlNDk2YWViZTgwM2M1ZDdlMWZkIn19',
          domain: 'localhost',
          path: '/',
          expires: -1,
          size: 71,
          httpOnly: false,
          secure: false,
          session: true } ]`

As you can see, the cookies "broken into half", my session.sig cookie lost but my session cookie is here.

Here is the most important part:
I uploaded THE SAME CODE to TravisCI, and TravisCI has no issue AT ALL. All test passed perfectly and the cookies issue didn't exist at all.

So my question is:
1. Why the cookies broke into half? As in, if I did something wrong in my code, I should screw up both cookies, but why only one?
2. Why CI don't have issue at all?

I can't find any solution in SO, so I am wondering is this a potential issue?

My environment:
1. Mac OSX
2. The application is a full stack node react application, the aforementioned codes are all in server side.

**Comment by aslushnikov** [comment]
@khmy2010 this sounds pretty magical. Here are the best answers I can think of:

> 1. Why the cookies broke into half? As in, if I did something wrong in my code, I should screw up both cookies, but why only one?

The only reason I can think of is the server code that kills one of the cookies. We aren't aware of any bugs on pptr side that would cause this kind of behavior.

> 2. Why CI don't have issue at all?

From our experience, CI differs pretty significantly from our local setup in two ways:
- CI might have different installed softward
- CI is much slower, which might cause/eliminate race conditions

I don't think we can help in any way here. Hope you'll figure this puzzle!
