### ISSUE TITLE
targetcreated not getting triggered in headless mode

### ISSUE THREAD

**Issue by NagarjunPrasad1** [puppeteer/puppeteer#2300]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13.0
* Platform / OS version: Ubuntu
* URLs (if applicable): cannot specifiy
* Node.js version: 9.4.0

**What steps will reproduce the problem?**
Clicking a button gives me a popup window. When I initiate the click with headless mode the targetcreated event gets triggered fine and I get the expected output. While doing the same in headless mode I am unable to get the popup window by listening to targetcreated event.

_Please include code that reproduces the issue._
```
let printButtons = await this.page.$$('#printNowButton');
for (var i = 0; i < printButtons.length; i++) {
    printButtons[i].click();
    const fileName = ('Document'+ i + '.pdf');
    browser.on('targetcreated', async target => {
        if (target.type() === 'page') {
            try {
                const newPage = await target.page():
                await newPage.pdf({
                    path: fileName,
                    format: 'A4'
                }).then(() => {
                    newPage.close();
                });
            } catch (e) {
                console.log('Error: ' + e);
            }
        }
    });
}
```

**What is the expected result?**
Expected multiple pdf's to be obtained.

**What happens instead?**
'targetcreated' event is not detected thus I don't obtain the pdf.

**Comment by JoelEinbinder** [comment]
It doesn't look like you are `await`ing your clicks. Additionally, the `browser.on('targetcreated')` listener needs to be set up before the click method is called, otherwise there is a race between when the listener is added and when the new target is created. I wouldn't be surprised if this code is very racy, and headless being a bit faster would have different results.

I'd try something like this:
```js
let printButtons = await this.page.$$('#printNowButton');

for (var i = 0; i < printButtons.length; i++) {
    const targetPromise = new Promise(resolve => browser.once('targetcreated', resolve));
    await printButtons[i].click();
    const target = await targetPromise;
    const fileName = ('Document'+ i + '.pdf');
    try {
      const newPage = await target.page();
      await newPage.pdf({
        path: fileName,
        format: 'A4'
      });
      await newPage.close();
    } catch (e) {
        console.log('Error: ' + e);
    }
}
```

**Comment by NagarjunPrasad1** [comment]
@JoelEinbinder I found out that this is may not be due to `targetcreated` being triggered but due to any new page of the type mentioned in #2313 not being detected in headless:true. I can confirm this as I couldn't obtain the pdf from 2 completely different websites with embedded pdf.

**Comment by aslushnikov** [comment]
@NagarjunPrasad1 yes, there's no pdf viewer in headless chrome. This has been raised a few times on the tracker already; I don't think this will change anytime soon.

**Comment by erkankarabulut** [comment]
> It doesn't look like you are `await`ing your clicks. Additionally, the `browser.on('targetcreated')` listener needs to be set up before the click method is called, otherwise there is a race between when the listener is added and when the new target is created. I wouldn't be surprised if this code is very racy, and headless being a bit faster would have different results.
> 
> I'd try something like this:
> 
> ```js
> let printButtons = await this.page.$$('#printNowButton');
> 
> for (var i = 0; i < printButtons.length; i++) {
>     const targetPromise = new Promise(resolve => browser.once('targetcreated', resolve));
>     await printButtons[i].click();
>     const target = await targetPromise;
>     const fileName = ('Document'+ i + '.pdf');
>     try {
>       const newPage = await target.page();
>       await newPage.pdf({
>         path: fileName,
>         format: 'A4'
>       });
>       await newPage.close();
>     } catch (e) {
>         console.log('Error: ' + e);
>     }
> }
> ```
@aslushnikov 
In my case, I have a link which openes a new tab, downloads a pdf and closes immediately after download. This listener can not detect my new tab in this situation. How can I get that pdf file and save in a folder of my choose?
