### ISSUE TITLE
window.crypto.subtle missing from bundled chrome version

### ISSUE THREAD

**Issue by soldair** [puppeteer/puppeteer#2301]
hey folks. its hard to say even from your instructions on opening issues where this should be so thank you very much to start with for your time.

for some reason window.crypto.subtle crypto is missing from the headless chromium installed with puppeteer. 

I believe this is an unintentional bug because the chromium version installed  >=67 should have shipped that api.

### Steps to reproduce
`console.log(window.crypto.subtle)`

* Puppeteer version: 1.2.0
* Platform / OS version: linux x64
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

console.log(typeof window.crypto.subtle)

**What is the expected result?**
"object"

**What happens instead?**
"undefined"

**Comment by soldair** [comment]
i feel very silly.this is because of the secure origins rule. 
it seems that browser.newPage() loads an insecure context

**Comment by mhart** [comment]
@soldair what did you do to solve this? I'm running into the same problem

**Comment by mhart** [comment]
Ok, I've managed to solve it by navigating to a `file://` url first, eg:

```js
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('file:///dev/null')
// OR
await page.goto(`file://${__dirname}`)
// OR simply
await page.goto('file:///')
```

Not sure if any of these are a recommended way to get to a secure origin for testing purposes – would love to hear from the Chrome/Puppeteer ppl on this.

**Comment by soldair** [comment]
Yeah that's what I did. I wrote a fixture empty html file to disk. Your's
is cooler
