### ISSUE TITLE
Page evaluate is throwing syntax error if I bundle the script with pkg

### ISSUE THREAD

**Issue by aanavaneeth** [puppeteer/puppeteer#2310]
When I use `page.evaluate` (puppeteer 1.12.0, chrome 65 installed in program files directory windows 7) in script, I was able to run it when I invoke script using `node src/app.js`. <br/>
But, When I package the script into an executable using `pkg` (https://github.com/zeit/pkg/), `page.evaluate` is throwing an error saying `syntax error in evaluatehandle line 79`. I had to build with pkg because my production environment doen't have node.js

Please help me with this.

**Environment:**
Node: 9.3
OS: windows 7
pkg: 4.3.1 
Executable Target: node9-win (pkg would built an exe for node9  & windows)
Chrome: 65 (installed on my pc; not from local chromium)

**Comment by aanavaneeth** [comment]
I was able to guess the reason. The issue is with `pkg`. While building the `exe`, it is compiling/transpiling code. This is causing issue. I have modified the parameter to evaluate from `function` to `string`. It simply worked!!

**Comment by neuhausi** [comment]
How did you get it to work?

I tried two different ways without any luck!

function myFunction(){
return true;
}

const result = await browser.page.evaluate(myFunction.toString());
2.
const result = await page.evaluate('(' + myFunction.toString() + ')();');

I get the following error:

Error: Evaluation failed: SyntaxError: Unexpected identifier
at ExecutionContext.evaluateHandle (/snapshot/node/node_modules/puppeteer/lib/ExecutionContext.js:80:15)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by aslushnikov** [comment]
@neuhausi the following works just fine for me with pptr 1.17.0:

```js
const puppeteer = require('puppeteer');

function myFunction(){
  return true;
}

(async function main() {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  await page.goto('https://aslushnikov.com');
  console.log(await page.evaluate(`(${myFunction.toString()})()`));
  await browser.close();
})();
```

**Comment by neuhausi** [comment]
Thank you for your reply. What about if I need to pass arguments. For example, suppose I need to pass an object as argument

```
const puppeteer = require('puppeteer');

const obj = {
  "foo" : true,
  "bar": false
}

function myFunction(obj){
  return obj.foo;
}

(async function main() {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  await page.goto('https://aslushnikov.com');
  console.log(await page.evaluate(`(${myFunction.toString()})()`));
  await browser.close();
})();
```

**Comment by aslushnikov** [comment]
> Thank you for your reply. What about if I need to pass arguments. For example, suppose I need to pass an object as argument

@neuhausi you can inline it as a part of the function call:

```js
const puppeteer = require('puppeteer');

const obj = {
  "foo" : true,
  "bar": false
}

function myFunction(obj){
  return obj.foo;
}

(async function main() {
  const browser = await puppeteer.launch();
  const [page] = await browser.pages();
  await page.goto('https://aslushnikov.com');
  console.log(await page.evaluate(`(${myFunction.toString()})(${JSON.stringify(obj)})`));
  await browser.close();
})();
```

**Comment by neuhausi** [comment]
Thank you that works! Now I have another problem but I will need to post it once I publish the code since I am getting an error when calling
```
await page.waitFor( () => typeof(CanvasXpress) !== undefined && CanvasXpress.ready );
```
(FYI CanvasXpress will be a property of the window once the document is loaded)

```
Error: Evaluation failed: SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:2:21)
    at ExecutionContext.evaluateHandle (/snapshot/node/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/snapshot/node/node_modules/puppeteer/lib/helper.js:110:27)
    at WaitTask.rerun (/snapshot/node/node_modules/puppeteer/lib/DOMWorld.js:582:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Do you have an example of calling page.waitFor with a function that is created in loaded page?

Thank you again!!!

**Comment by neuhausi** [comment]
I am still getting an error  on page.evaluate "Unexpected identifier". (It works perfect without pkg)

**### Here is a simplified version of part of the code that is giving the error**
```javascript
const func = (o) => {
  if (o.debug) {
    debugger;
  }
  var cxs = CanvasXpress.instances;
  for (var i = 0; i < cxs.length; i++) {
    var cx = cxs[i];
    var target = cx.target;			 	
    cx.print(false, target + '.png');
  }
}

const obj = {
  debug: false
}

await page._client.send('Page.setDownloadBehavior', {
  behavior: 'allow', 
  downloadPath: './'
});

await page.goto('https://canvasxpress.org/html/bar-3.html');

//await page.waitFor( () => typeof(CanvasXpress) !== undefined && CanvasXpress.ready );

await page.evaluate( `(${func.toString()})(${JSON.stringify(obj)})` );
```
**### And here is the error I get:**
```
Error: Evaluation failed: SyntaxError: Unexpected identifier
    at ExecutionContext.evaluateHandle (/snapshot/node/node_modules/puppeteer/lib/ExecutionContext.js:80:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/snapshot/node/node_modules/puppeteer/lib/helper.js:110:27)
    at ExecutionContext.evaluate (/snapshot/node/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/snapshot/node/node_modules/puppeteer/lib/helper.js:111:23)
    at DOMWorld.evaluate (/snapshot/node/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/snapshot/node/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.evaluate (/snapshot/node/node_modules/puppeteer/lib/Page.js:782:43)
    at Page.<anonymous> (/snapshot/node/node_modules/puppeteer/lib/helper.js:111:23)
    at module.exports (/snapshot/node/cmds/io.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by nihatyldz42** [comment]
I found the solution by extracting long and complex js codes from a file.
Here's my code.

....initilazition area
```
var LIB_DATA = ""
readFile(path.join(process.cwd(), "/jscodes.js"),"utf8",(err,libFile)=>{
    LIB_DATA = libFile;
})
```

....async func
await page.evaluate(LIB_DATA)

**Comment by nihatyldz42** [comment]
https://nr42technologies.blogspot.com/2021/01/page-evaluate-is-throwing-syntax-error.html
