### ISSUE TITLE
Page is not defined- nested function

### ISSUE THREAD

**Issue by dutchsparks** [puppeteer/puppeteer#2311]
**Tell us about your environment:**

* Puppeteer version: 5.7.1
* Platform / OS version: Sierra 10.12.4
* URLs (if applicable): https://google.com
* Node.js version: v8.9.4

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
async function getPic() {
  const browser = await puppeteer.launch( { headless: false});
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.evaluate( async () => {
    const imageslink = document.querySelector("a[data-pid='2']");
 if (imageslink.textContent === "Images") {
    imageslink.click();
    await page.screenshot({path: 'google.png'});
 }
  });

  await browser.close();
}

getPic();

````
**What is the expected result?**
I would expect the script to make a screenshot because the if condition is true.  And with page.evaluate being a nested function it should have access to the outer function's( getpic()'s) variables (in this case page), should it not ?

**What happens instead?**
 instead I get an error saying "page is not defined.

**note
 the only reason I'm trying to write this script is for practice purposes

**Comment by vsemozhetbyt** [comment]
`page.evaluate()` calls its callback in the browser context, where `page` (defined in the `puppeteer` (Node.js) context) is not available. You can return boolean value from this function, check it in the `puppeteer` context and call `page.screenshot()` there.

**Comment by aanavaneeth** [comment]
I know. My understanding is, callback given to `page.evaluate` will be sent to browser, and it resolves a promise to `puppeteer`. And, code I wrote is perfectly working fine, But, if I bundle that code with `pkg`, then its throwing syntax error. That too, all other puppeteer functions are working fine. Like 'waitFor', 'goto', etc. only `evaluate` is not . Just wondering if that is dependent on some node variable which is not shipped via pkg or some security issue, etc,. No clue :(

**Comment by dutchsparks** [comment]
ooh,that explains a lot, thank you.
Would you be willing to elaborate a little on how to check the Boolean value in the puppeteer context ?
I looked in the puppeteer documentation and there are no conditionals in there right ?

**Comment by vsemozhetbyt** [comment]
I mean something like this:
```js
const puppeteer = require('puppeteer');
async function getPic() {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://google.com');
  
  const found = await page.evaluate(() => {
    const imageslink = document.querySelector("a[data-pid='2']");
    if (imageslink.textContent === "Images") {
       return true;
    }
    return false;
  });
  
  if (found) await page.screenshot({ path: 'google.png' });

  await browser.close();
}

getPic();
```

**Comment by dutchsparks** [comment]
[deleted]

**Comment by vsemozhetbyt** [comment]
In the `page.evaluate()` parameter function you can use any JavaScript syntax and globals you usually use in the browser scripts. You can return any value that can be safely serialized/deserialized (primitives, simple data structures).
