### ISSUE TITLE
[Bug] Unable to use page.pdf with pages having embed tag of type application/pdf?

### ISSUE THREAD

**Issue by NagarjunPrasad1** [puppeteer/puppeteer#2313]
In a page I am automating upon clicking a button a new tab opens up inside which is the pdf I want to obtain. The problem is that in `headless:false` I am able to get the page easily but in `headless:true` it currently doesn't work.
The page I am trying to get the pdf from:
```
<body style="background-color: rgb(38,38,38); height: 100%; width: 100%; overflow: hidden; margin: 0">
    <embed width="100%" height="100%" name="plugin" id="plugin" src="https://checkin.si.amadeus.net/sscwuk/document.pdf?SITK=1FRF36PU7D00020MCNJGS5MP0002&SITK2=1FRF3GS2&actionprintDocument=Print" type="application/pdf" internalinstanceid="7" title="">
</body>
```

My current code to obtain the document:
```
browser.on('targetcreated',async() => {
	const allPages = await browser.pages();
	const newPage = allPages[allPages.length - 1];
	newPage.waitForNavigation({waitUntil:'load'});
	newPage.bringToFront();
	console.log("URL " + newPage.url());
	await newPage.pdf({
		path: 'docBP.pdf',
		format: 'A4'
	}).then(() => {
		console.log("Obtained the PDF");
	});
});
```
The bug here is that with the above code in `headless:true` the url is logged a blank and I get a blank pdf. While if I try this in `headless:false` (with the newPage.pdf commented out) I get the proper URL logged and I properly switch to the new tab created with the pdf. Can anyone help me out with this?

**Comment by aslushnikov** [comment]
unfortunately, headless chrome doesn't have PDF viewer; so every time you open a PDF, headless chrome tries to download the file.

Unfortunately, we don't support downloads yet; please follow #299 about this one.
