### ISSUE TITLE
Puppeteer in Bitbucket Pipelines timeout

### ISSUE THREAD

**Issue by Christilut** [puppeteer/puppeteer#2315]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* jest-puppeteer version: 2.2.3
* jest: 22.4.3
* Platform / OS version: Linux, docker: `timbru31/node-chrome`
* URLs (if applicable):
* Node.js version: 8.x

**What steps will reproduce the problem?**

So I'm using jest-puppeteer to run e2e tests in headless chrome. This works fine on my machine. The problem starts when running these tests in Bitbucket Pipelines. It runs the docker image specified above. I've tried that docker image locally and it works as expected.

Pipelines is giving me the following error:
`Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.`

By trial and error it is because of this line:
`await page.waitForSelector('.account-container')`

I've found out that `await page.evaluate()` has the same problem.

I've tried setting the timeout to something much higher, but that didn't change anything.

I've tried with these args:
```
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '-shm-size 1G'
    ]
```

I want to figure this out but I simply don't know what I can still try here.

Full test case code:
_Please include code that reproduces the issue._

```js
  it('should fill in valid credentials, press the login button and navigate to new pages', async () => {
    await page.goto(baseUrl)

    await expect(page).toFill(inputEmail, validEmail)
    await expect(page).toFill(inputPassword, validPassword)
    await expect(page).toClick('.button', { text: 'Log in' })

    await page.waitForSelector('.account-container') // this line freezes
  })
```
**What is the expected result?**
No timeout error. Test case should pass.

**What happens instead?**
`Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.`

**Comment by Christilut** [comment]
Okay figured out that it was because of an IP whitelist which did not include the Bitbucket IP's. Ajax calls were getting an error which wasn't visible in the test output.

**Comment by lanceheld** [comment]
@Christilut I'm experiencing the same thing, I believe. Where is the IP whitelist defined and what did you add to resolve this?
