### ISSUE TITLE
about:blank throws errors while using window.localStorage

### ISSUE THREAD

**Issue by matthewmueller** [puppeteer/puppeteer#2317]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: OSX

**What steps will reproduce the problem?**

(no code needed)

1. Go to `about:blank` in the browser
2. Open the console and type `window.localStorage`

**What is the expected result?**

```
Storage { }
```

**What happens instead?**

```
VM53:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at <anonymous>:1:8
```

---

For running browser unit tests, many times you just need a browser environment. It'd be great to have a chrome page that works entirely with the DOM.

**Comment by JoelEinbinder** [comment]
This is working as intended. You should probably be running a web server when running your unit tests. There are many differences between about:blank, a website on an insecure origin, and a website on a secure origin.

If you just want a blank page on an arbitrary url, you can set that up with request interception:
```js
const page = await browser.newPage();
await page.setRequestInterception(true);
page.on('request', request => {
	request.respond({
		status: 200,
		contentType: 'text/html',
		body: 'Fake Content'
	});
});
await page.goto('http://fakeurl');
```

**Comment by matthewmueller** [comment]
Ahh, that's brilliant. Thanks @JoelEinbinder!

**Comment by matthewmueller** [comment]
For anyone coming to this at a later time, this is what I ended up going with:

```js
await page.setRequestInterception(true)
page.on('request', request => {
  request.respond({ status: 200, contentType: 'text/html', body: '' })
})
await page.goto('http://127.0.0.1')
```

Going to `127.0.0.1` ended up being about 12x faster, dropping the overhead from 120ms to 10ms, I presume because it doesn't have to do any DNS. Thanks again!

**Comment by catalin-invisible** [comment]
Having the `body` empty in the response above, I get a timeout.

But adding any kind of content to `body`, works perfectly.
