### ISSUE TITLE
Headful and Headless mode have different tab indexes

### ISSUE THREAD

**Issue by gtaltemann** [puppeteer/puppeteer#2318]
When running Puppeteer on Headful mode, whenever I click something that opens a new tab I can use `const newPage = await browser.targets()[3].page()`. 

However, this doesn't work in headless mode, as `const postPage = await browser.targets()[3].page()` is actually my first page, and `const postPage = await browser.targets()[4].page()` becomes the new page.

Why am I getting this difference between headless/headful mode?

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

Click something that opens a new tab;
Its index will be different in headless and headful mode.

_Please include code that reproduces the issue._

1. Open new tab
2. Try to access that tab with the same index for headless and headful mode. 

**What is the expected result?**

Being able to work with the same code for both modes.

**What happens instead?**

Can't find correct page.

**Comment by yrshaikh** [comment]
Can you please post an example/sample code?

**Comment by gtaltemann** [comment]
Sure! Here it is:

```
// Clicks a button that opens a new tab
await page.click('#someButton')
await page.waitFor(1000)

// When running HEADFUL MODE, target is = 3
// When running HEADLESS MODE, target is = 4
const newPage = await browser.targets()[4].page()
await newPage.type('textarea[aria-label="Edit title"]', title)
```

**Comment by aslushnikov** [comment]
@gtaltemann there are many different targets other then `page`, e.g. extensions and workers. Extensions don't exist in headless mode but do exist in headful. So in your case, `browser.pages()` should work.

In any case, I'd refrain from using indexes to address pages in browser and instead find the right one based on the url.

Hope this helps.
