### ISSUE TITLE
page event when i click any of the link or change route

### ISSUE THREAD

**Issue by rageshpayyan** [puppeteer/puppeteer#2322]
@ebidel ,My application built in Angular, what is the page event when i click any of the link or change route? I tried using await page.on('framenavigated', frame => {...}); which is fired only at first time, after i clicked any of the links in page this event is not fired.

**Comment by aslushnikov** [comment]
@rageshpayyan this sounds like a same-document navigation that's not very-well supported atm. Please follow #257 for the updates.
