### ISSUE TITLE
Puppeteer operates underneath top layer div

### ISSUE THREAD

**Issue by dutchsparks** [puppeteer/puppeteer#2329]
Puppeteer version: 5.7.1
Platform / OS version: Sierra 10.12.4
Node.js version: v8.9.4

I use puppeteer to click on an HTML element. Which then makes a div appear, with more elements on it. I would like to select 1 of these elements but whatever I tried I could not select them because supposedly they did not exist according to terminal.
Then I realized that puppeteer was looking for the elements on the webpage underneath this div.
 I know this because I made the script press tab about your times and click a few coordinates after the top layer div appears, and I could see those actions taking place on the screen underneath the div (with headless false).
Even if I click a  coordinate of the page that the div is located on, puppeteer still clicks underneath the div.

This has nothing to do with the div not being loaded yet by the way, even if I give it plenty of time to load the same issue exists.

 Is there anyway I can make puppeteer somehow focus on this top layer div so I select its elements?

 I hope this story makes sense, feel free to ask for more clarification.

**Comment by aslushnikov** [comment]
> Even if I click a coordinate of the page that the div is located on, puppeteer still clicks underneath the div.

@dutchsparks something else should be happening. Puppeteer clicks the same way you'd click with your mouse, so the behavior shouldn't differ. Would you mind sharing an example so that we can reproduce it locally?
