### ISSUE TITLE
Feature Request: standard two-way communication pipe between puppeteer ←→ target

### ISSUE THREAD

**Issue by matthewmueller** [puppeteer/puppeteer#2331]
Hey folks, there's been quite a few times where I've been wanting a way to do 2-way communication between puppeteer and the page. 

Right now it's possible to do but seems quite ad-hoc, these are the ways I can think of:

**Puppeteer → Page**:

1. create a custom function on the page, then use puppeteer to evaluate it
2. use the low-level "sendMessageToTarget" method to send a custom command (untested)
3. add a JS script to the page.

**Puppeteer ← Page**:

1. have puppeteer intercept requests, make a custom request from the page
2. have puppeteer listen for console events and utilize console.log on the page

Maybe I'm missing a better way to set this up? Thanks!

**Comment by vsemozhetbyt** [comment]
As for **Puppeteer ← Page**, there is also [`page.exposeFunction()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction).

**Comment by aslushnikov** [comment]
Indeed, the recommended way to communicate is:
- Puppeteer → Page: [`page.evaluate()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args)
- Puppeteer ← Page: [`page.exposeFunction()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction)

**Comment by matthewmueller** [comment]
Got it, thanks for clarifying!
