### ISSUE TITLE
Taking screenshot before images finishing rendering

### ISSUE THREAD

**Issue by Earthsplitter** [puppeteer/puppeteer#2343]
I use 
```
await page.goto(`data:text/html,${html}`, {
                    waitUntil: 'load',
                    timeout: 5000
           })
```
to load html string. And then call `page.screenshot` to get the screenshot.

However, images in `style=`, like `<div class="photo-invite-card" style="background-image:url(https://placeimg.com/640/480/animals)">`, may not be rendered when the screenshot is taken.

I think the reason is that images specified in style= are not loaded until layout happens, but window.onload can fire *before* the first layout.

Using background-image is easy to position images and our team used it a lot.

Is there any workaround can help?

**Comment by vc1** [comment]
`waitUntil: ['load', 'networkidle0']`
