### ISSUE TITLE
Error: waiting failed: timeout 0ms exceeded

### ISSUE THREAD

**Issue by Swiffers** [puppeteer/puppeteer#2347]
hi,

The error is given by the following code: 

`await frame.waitForSelector('.selector', {timeout:0});`

But the [documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectorselector-options) mention that it's possible to do it: 

> timeout <number> maximum time to wait for in milliseconds. Defaults to 30000 (30 seconds). Pass 0 to disable timeout.

```
(node:39582) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: waiting failed: timeout 0ms exceeded
(node:39582) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
This was added in abb05e0 and hasn't been released yet; it will be part of a new version 1.3.0. We'll release it on April, 12.

**Comment by Swiffers** [comment]
How can I do this in the meanwhile? 

I'm uploading huge files, and it's usual to wait more then 10 minutes before the promise is 'returned'. 
Should I just use a big number?

**Comment by aslushnikov** [comment]
@Swiffers yes, any huge number would work. Note though: too big numbers, e.g. `Number.MAX_VALUE` or `Infinity` won't do, so I'd pass in something sane, e.g. `1000 * 60 * 60 * 24` (1 day).

**Comment by Swiffers** [comment]
@aslushnikov Sure, thanks
