### ISSUE TITLE
Is the API key meant to be in this repo?

### ISSUE THREAD

**Issue by F1LT3R** [puppeteer/puppeteer#2353]
https://github.com/GoogleChrome/puppeteer/blob/f8cba455ba5d1bc82721e89fda037e86213b02cb/.travis.yml#L31

**Comment by aslushnikov** [comment]
According to the docs here, it should: https://docs.travis-ci.com/user/deployment/npm/#NPM-auth-token

**Comment by ebidel** [comment]
@F1LT3R that's using encryption keys. https://docs.travis-ci.com/user/encryption-keys/#Detailed-Discussion has more info on `secure:`. Travis decrypts the value and replaces `secure: <something>` with `secure: <actual value>`.
