### ISSUE TITLE
Timeout occurs when reusing a page.

### ISSUE THREAD

**Issue by KimSeongIl** [puppeteer/puppeteer#2356]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2
* Platform / OS version: Ubuntu 16.04 (docker)
* URLs (if applicable):
* Node.js version: 8.x

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch();
const page = await browser.newPage();
let chain = Promise.resolve();

app.get('/convert', (req, res) => {
  chain = chain.then(async () => { 
    await page.goto('data:text/html, dkfehkf', { waitUntil: 'load' });
    const screenshot = await page.screenshot();
    res.send('success');
  });
});
```

**What is the expected result?**

**What happens instead?**

error: Navigation Timeout Exceeded: 30000ms exceeded.

I have to reuse page objects because of performance problems.

But sometimes a timeout occurs when reusing a page.
I used data uri, and the contents are almost empty, but timeout occurs.
As soon as the page receives the request, a 30000ms timeout error occurs.

Why do I get an error even though I have not exceeded 30000ms?

Is there a problem reusing page objects? I want to know how to fix it.

**Comment by yrshaikh** [comment]
Related - https://github.com/GoogleChrome/puppeteer/issues/486

**Comment by KimSeongIl** [comment]
@yrshaikh 
Thank you for answer.
I have seen the article before, but I have not found a solution to this problem.

**Comment by KimSeongIl** [comment]
Rendering the same data to the same page object seems to cause a timeout.

`await page.goto ('about:blank', {waitUntil: 'load'});`

Initializing the page data with the above code seems to be resolved.

Why is this happening?

If the puppeteer is rendering the same data on the same page, is it perceived as not being rendered because of the cache?

Is my solution the correct solution?
What is the best solution to this problem?

**Comment by aslushnikov** [comment]
> Is my solution the correct solution?
> What is the best solution to this problem?

@KimSeongIl you should definitely serialize your requests; otherwise, you race with yourself.
See https://github.com/GoogleChrome/puppeteer/issues/486#issuecomment-324221441

Hope this helps.
