### ISSUE TITLE
No way to determine native DPR of device

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#2358]
The following code doesn't allow someone to use the device's native DPR by setting `await page.setViewport({deviceScaleFactor: 0,...})`:

https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L729
https://github.com/GoogleChrome/puppeteer/blob/294f33b75c5a7c87d447816218438f56c2d56f0e/lib/EmulationManager.js

That makes it impossible to determine the real DPR of the device:

```js
await page.evaluate('window.devicePixelRatio'); 
```

**Comment by JoelEinbinder** [comment]
Easy fix, but why do you need the native DPR? It should be largely irrelevant in headless afaik.

**Comment by ebidel** [comment]
You want to know this information for taking  high quality screenshots. 

For my particular case, I'm running an app in both mac and linux. So I want to use the correct DPR per the device without hard coding numbers.

**Comment by JoelEinbinder** [comment]
Why would the dpr of the device affect the screenshot quality? The device doesn’t necessarily have a single dpr

**Comment by ebidel** [comment]
You need to emulate a viewport with `deviceScaleFactor: 2` to produce  crisp screenshots on a retina mac. On Linux, using that produces a screenshot that's  2x what you actually need...and it's buggy. See our pptr chat.

**Comment by aslushnikov** [comment]
Let's introduce a `viewport` option to the launcher as a part of #1183. One of the values could be `null` to disable viewport override altogether.
