### ISSUE TITLE
page.pdf error: "Page range exceeds page count undefined"

### ISSUE THREAD

**Issue by mpopv** [puppeteer/puppeteer#2359]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Ubuntu 16.04.4 LTS
* Node.js version: 8.9.3

**What steps will reproduce the problem?**

```js

process.on('unhandledRejection', r => console.log(r));

const puppeteer = require('puppeteer'),
      forever   = require('forever-monitor');

(async () => {

  const server = forever.start(
    [ 'http-server', './dist', '-p 9010' ],
    {
      max : 1,
      silent: true
    }
  );

  const browser = await puppeteer.launch();

  const page = await browser.newPage();

  await page.goto(
    'http://localhost:9010/states/california',
    {
      waitUntil: 'domcontentloaded',
      timeout: 60000
    }
  );

  await page.waitFor(5000);

  await page.pdf({
    pageRanges: '1,2',
    path: './dist/reports/california.pdf',
    format: 'A4',
    printBackground: true,
    scale: .54
  });

  await page.close();
  await browser.close();
  server.stop();

  return null;
})();

```

**What is the expected result?**

A two-page PDF is saved. The (web) page in question is definitely more than 1 (PDF) page long, as evidenced by a large image getting cut off in the middle, at the bottom of the page, when a 1-page PDF is printed.

**What happens instead?**

With `pageRanges: '1-2'`, or `pageRanges: ''`, or omitting `pageRanges`, only the 1st page out of 2 pages is printed.

With `pageRanges: '1,2'` or `pageRanges: '2'`, the following error occurs:

```bash
{ Error: Protocol error (Page.printToPDF): Page range exceeds page count undefined
    at Promise (/project-name/node_modules/puppeteer/lib/Connection.js:198:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/project-name/node_modules/puppeteer/lib/Connection.js:197:12)
    at Page.pdf (/project-name/node_modules/puppeteer/lib/Page.js:772:39)
    at __dirname (/project-name/lib/puppeteer-bug-demo.js:29:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Protocol error (Page.printToPDF): Page range exceeds page count undefined' }
```

**Comment by mpopv** [comment]
It looks like the error originates [here](https://github.com/chromium/chromium/blob/afc2328142d33cc05e71ee544e8ad77a334c151e/headless/lib/browser/headless_print_manager.cc#L262) in Chromium.

**Comment by yrshaikh** [comment]
The documentation says `Defaults to the empty string, which means print all pages.` I tried the below code and it worked fine.
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('https://en.wikipedia.org/wiki/Great_Britain_at_the_2018_Winter_Olympics');
    await page.pdf({
        path: 'output2.pdf',
        format: 'A4',
        printBackground: true,
        scale: .54
    });
    await browser.close();
})();
```
Can you try without the page range? Or do you specifically want the first 2 pages only.

**Comment by mpopv** [comment]
Sorry, I should have included that in the issue -- I also tried empty string and omitting `pageRanges`, and it printed only the first of two pages. I updated the issue.

Your code works fine for me as well. I think the underlying cause is that page count is being set to "undefined" in Chromium. It seems like perhaps some aspect of the document being captured is causing this... but I'm not sure what that could be.

**Comment by yrshaikh** [comment]
Could you check if the pages > 2 are rendered and loaded correctly using headless:false, do they load with a delay or something, like depends on an AJAX call?

**Comment by greg-benner-klick-sensei** [comment]
I had a slightly different error, it would be nice to add pageRanges 1,2,3,5,10 vs 1-3,5,10 
I think thats why my code is throwing and saying pagerange is out of bounds

**Comment by greg-benner-klick-sensei** [comment]
https://www.npmjs.com/package/multi-integer-range works well for anyone in the same boat.
``` 
const formattedPagesRange = new MultiRange();
filteredPages.map(pageNum => {
      formattedPagesRange.append(pageNum);
    });
toBePrintedPages = formattedPagesRange.toString();
```

**Comment by sarmadzaki** [comment]
any of you found any solution? i'm stuck in this. :/
