### ISSUE TITLE
Does puppeteer support '--use-file-for-fake-video-capture' or has any plan for it?

### ISSUE THREAD

**Issue by starcwl** [puppeteer/puppeteer#2363]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2
* Platform / OS version: mac 10.13.4
* URLs (if applicable):
* Node.js version: 8.11

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

below is my configs for puppeteer.

```
  const browser = await puppeteer.launch({
    args: [
      '--use-fake-ui-for-media-stream',
      '--use-file-for-fake-video-capture=./1.y4m'
    ],
  });
```

**What is the expected result?**

I want to replace local webcam for 1.y4m. But it seems the arg ''--use-file-for-fake-video-capture" not working. 
**What happens instead?**

**Comment by matthaywardwebdesign** [comment]
Try using both `--use-fake-device-for-media-stream` and  `--use-file-for-fake-video-capture`. When specifying the y4m file make sure you are using the absolute file path. It's also recommended that you close all Chrome instances first before using `fake-device` for the first time. 

Reference - [https://github.com/webrtc/samples/issues/616](https://github.com/webrtc/samples/issues/616)
