### ISSUE TITLE
Feature request: add 'uid' and 'gid' options to puppeteer.launch()

### ISSUE THREAD

**Issue by seeekr** [puppeteer/puppeteer#2365]
I would like to be able to specify `uid` and `gid`, i.e. which system user to use for launching the Chromium instance, when calling `puppeteer.launch()` -- just like if I were using `child_process.spawn()` directly.
(Or, instead, even just a system username, and puppeteer would resolve it to uid/gid itself.)

Thanks for making an awesome library!

**Comment by aslushnikov** [comment]
@seeekr this has been already discussed and there's a workaround, see https://github.com/GoogleChrome/puppeteer/issues/745

However, I don't mind if you add the `uid` and `gid` to the launcher since you're not the first here already. Feel free to send a PR!

**Comment by seeekr** [comment]
Thanks, will do if I should continue to feel that that's a useful thing in the future! Setup working just fine at the moment :)
