### ISSUE TITLE
Add explicit docs for postMessage

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [puppeteer/puppeteer#2366]
Following up on https://github.com/GoogleChrome/puppeteer/issues/573, https://github.com/GoogleChrome/puppeteer/blob/master/examples/custom-event.js is a good start but doesn't explicitly show how to get `postMessage` to work.

If and when I do I'll send a PR :).

**Comment by ebidel** [comment]
What are you trying to do? Maybe we can suggest a solution or add an example. But it's not clear from the description.

**Comment by JoshuaKGoldberg** [comment]
Sorry for the vagueness.

Within the page, there is code that posts messages to signal important actions, such as PageReady, UserClick, ActionFailure, etc. These can be used by a few consumers:
* Browser extensions, to listen to user events
* Developer tools, such as one that'll log to the console whenever an important event happens
* Tests, whcih want to verify events fire when they're supposed to (e.g. when an image is clicked, the ImageClick event should fire).

```javascript
async function main() {
    await setup();
    await moreSetup();

    window.postMessage({ appBuild: "abc123", type: "MainComplete" }, "*");
}
```

I'm running tests using [jest-puppeteer](https://facebook.github.io/jest/docs/en/puppeteer.html) and want to receive data from those post messages in the tests.

Mocking up a rough version the ImageClick one:

```javascript
describe("ImagePage", () => {
    it("fires an ImageClick event when the image is clicked", () => {
        // Arrange
        const { messages, page } = await navigatePageAndListenToMessages("/image-url");

        // Act
        await page.click(".my-image");

        // ...where these are the events sent via window.postMessage in the page
        // In actuality, there'd be an EventEmitter-like interface transmitting these
        const lastMessage = await messages.getLastMessage();

        // Assert
        expect(lastMessage).toEqual(jasmine.objectContaining({
            type: "ImageClick"
        }));
    });
});
```

Does that make sense?

**Comment by aslushnikov** [comment]
The `custom-events.js` is meant to be an example of the api. You can build all kind of API atop of pptr to help with your testing purposes.

If you don't need the actual message-passing, but rather is interested in page "events", you can use
`console.timeStamp` in page, and listen to these events in pptr through `page.on('metrics')` event. As a bonus, the `page.timeStamp` events are marked on the devtools timeline, if you record one.
