### ISSUE TITLE
Unique IDs for pages

### ISSUE THREAD

**Issue by snoopdouglas** [puppeteer/puppeteer#2368]
It'd be useful to be able to keep track of pages between calls to `browser.pages()` by assigning each open page a unique ID.

As far as I know, the DevTools protocol does indeed specify a UUID for each open page. Could this be exposed in Puppeteer too?

**Comment by snoopdouglas** [comment]
I've found that pages can be ID'd using `page.mainFrame()._id`, but am guessing the underscore implies that this is meant for internal use.

**Comment by aslushnikov** [comment]
@snoopdouglas the `_id` is indeed a private variable. You can keep track of pages by their identity: `browser.pages()` doesn't re-create pages if they were once created.

```js
const browser = await pptr.launch();
const [page1] = await browser.pages();
const [page2] = await browser.pages();
console.log(page1 === page2); // true
```
