### ISSUE TITLE
[Request] Pdf Element

### ISSUE THREAD

**Issue by btecu** [puppeteer/puppeteer#2369]
Can we get support for converting an element to pdf? Currently only the entire page is possible.

**Comment by ebidel** [comment]
You should already be able to do this by:

1. taking a [screenshot of the element](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlescreenshotoptions)
2. create a page with that image as its content
3. create a pdf from the page.

Here's an example that creates a pdf from a tweet card:
https://github.com/GoogleChromeLabs/puppeteer-examples/blob/master/element-to-pdf.js

<img width="1314" alt="screen shot 2018-04-13 at 4 36 12 pm" src="https://user-images.githubusercontent.com/238208/38761580-d10fcb9c-3f38-11e8-99fd-7f2eb84cff01.png">

**Comment by btecu** [comment]
@ebidel that creates a pdf but is a bit of a hack since it's just a png wrapped in a pdf. I'd like a real pdf where you can search text.

**Comment by ebidel** [comment]
Well construct a PDF from the portion of the page you're interested in. Clone its DOM and craft a new page from it.

**Comment by btecu** [comment]
Seems like a good idea. Is there a way to keep inherited styles?

**Comment by MrTreasure** [comment]
In browser u could use this lib ```html2canvas```

**Comment by ebidel** [comment]
@btecu you could also pull the `<style>` and stylesheets from the original page and inject them on the new page you're creating. I'd imagine that would work for 80% of the cases. Or maybe `page.setContent(entireOriginalPageHTML)` and then use DOM APIs to remove everything from the `<body>` except the element.

**Comment by btecu** [comment]
That was my initial thought, although I was thinking maybe `puppeteer` can do it.

I'll try this approach. Thanks @ebidel.

**Comment by ebidel** [comment]
@btecu added a `--searchable` flag to the example:
https://github.com/GoogleChromeLabs/puppeteer-examples/commit/cb0f34ebdd963fad160aa8bb1dc51d47f560cc30
