### ISSUE TITLE
Typo in Puppeteer 1.3 release notes

### ISSUE THREAD

**Issue by abargnesi** [puppeteer/puppeteer#2373]
The [Puppeteer 1.3](https://github.com/GoogleChrome/puppeteer/releases) release notes mentions that chromium `67.0.3391.0` is the supported version. When trying to build chromium for amazon linux I found that the `67.0.3391.0` tag doesn't exist in the chromium repo.

[This discussion](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/mt_YszC5kjM) with the chromium group points towards the actual tag being `67.0.3392.0`.

Can this be updated?

**Comment by szebrowski** [comment]
Running with headless=false and checking in About Page I get 67.0.3391.0 so maybe tag isn't correct?

**Comment by aslushnikov** [comment]
@abargnesi the `67.0.3391.0` is the version reported by bundled chromium. I don't think there's a tag for every chromium version.

When building your own chromium, you can checkout precise revision we publish. To get the SHA of the revision, go to the `http://crrev.com/<revision number>` (for pptr 1.3 the link would be http://crrev.com/549031).
