### ISSUE TITLE
feat: client-side commands 

### ISSUE THREAD

**Issue by pemrouz** [puppeteer/puppeteer#2380]
This is easy enough to hack outside puppeteer, but I was just wondering if there is an easy way (or if it could be added) to use commands from the client, i.e. something like:

```js
page.evaluate(() => {
  page.click('.foo')
})
```

**Comment by yanivefraim** [comment]
@pemrouz - not sure what exactly you meant in your example, but the correct way to use click is:

```
page.click(selector)
```

(no need for the evaluate here)
If you want to run code in browser context you can just run it using:

 `page.evaluate(() => code to run in browser)`

Can you explaign what exactly did you look for?

**Comment by matthaywardwebdesign** [comment]
@pemrouz Are you wanting to run Puppeteer scripts inside the browser itself, instead of running from Node?

**Comment by MrTreasure** [comment]
The browser and Puppeteer have different context. U can't run puppeteer's scripts in browser directly.But u could do like this
```javascript
const clicker = await page.$('.foo')
await clicker.click()
await page.evaluate(() => {}) // something happen after foo clicked
```
