### ISSUE TITLE
how can i change the browser's proxy?

### ISSUE THREAD

**Issue by tonggang** [puppeteer/puppeteer#2383]
how can i change the browser's proxy after i set during the launch stage?

**Comment by aslushnikov** [comment]
Please see https://github.com/GoogleChrome/puppeteer/blob/master/examples/proxy.js

**Comment by aslushnikov** [comment]
Oops, mis-read the issue description.

> how can i change the browser's proxy after i set during the launch stage?

There's no way to. However, since you already have a proxy, you can get one that allows dynamic configuration,

**Comment by Cuadrix** [comment]
It can be done with [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy).
It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.

First install it:
```
npm i puppeteer-page-proxy
```
Then require it:
```js
const useProxy = require('puppeteer-page-proxy');
```
**Using it is easy;**
Set proxy for an entire page:
```js
await useProxy(page, 'http://127.0.0.1:8000');
```

If you want a different proxy for each request,then you can simply do this:
```js
await page.setRequestInterception(true);
page.on('request', req => {
    useProxy(req, 'socks5://127.0.0.1:9000');
});
```
Then if you want to be sure that your page's IP has changed, you can look it up;
```js
const data = await useProxy.lookup(page);
console.log(data.ip);
```
It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
```js
const proxy = 'http://login:pass@127.0.0.1:8000'
```

Repository:
https://github.com/Cuadrix/puppeteer-page-proxy
