### ISSUE TITLE
Hi. How to make it work with dropbox links?

### ISSUE THREAD

**Issue by Daniyal83** [puppeteer/puppeteer#2384]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: last
* Platform / OS version: ubuntu 16.04
* URLs (if applicable): 
* Node.js version: 9

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
counted number of words

**What happens instead?**
nothing

**Comment by matthaywardwebdesign** [comment]
Are you able to provide some example code? Not really able to see what the issue is :)

**Comment by Daniyal83** [comment]
Actually i found the solution. Thanks. Because of using iframe on dropbox it was difficult to get correct html.
