### ISSUE TITLE
Web Speech Api save file

### ISSUE THREAD

**Issue by Oleg-Miniuk** [puppeteer/puppeteer#2385]
Is that possible to safe binary audio data to file using Web Speech Api or any other browser's public api

No matter chromium, or chrome like it was described [here](https://github.com/GoogleChrome/puppeteer/issues/2141).

Thanks

**Comment by ebidel** [comment]
Unfortunately no, the WSI doesn't have any way to get at the audio data it returns. It's a black box API.

Instead, I'd consider using the OS's native text2speech engine. On Mac, it's easy to create an audio file from the output: https://stackoverflow.com/questions/16501663/macs-say-command-to-mp3

**Comment by edwardyoon** [comment]
@ebidel it seems able to save audio file using secondary getMedia. but not working on mobile chrome. Is it blocked?
