### ISSUE TITLE
onbeforeunload not called when page.close() called

### ISSUE THREAD

**Issue by starcwl** [puppeteer/puppeteer#2386]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2
* Platform / OS version: Mac 10.13.2
* URLs (if applicable):
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I need to release some resources when page.close called.  Code below called when I close the tab manually.  But in puppet, after I invoke page.close(). It seems not get called at all.

```
window.onbeforeunload = function() {
  $log.debug('MainController onbeforeunload');
  rtc.disconnect();
};
```

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
We don't run `beforeunload` handlers when closing web contents, making `page.close()` always close the page.

We should optionally run beforeunload callbacks if users want to. This will require a protocol change.

**Comment by aslushnikov** [comment]
Upstream fix: https://chromium-review.googlesource.com/c/chromium/src/+/1014676
