### ISSUE TITLE
page.pdf headerTemplate and footerTemplate. Certain CSS styles not working.

### ISSUE THREAD

**Issue by DavidKisiel** [puppeteer/puppeteer#2388]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.3.0
* Platform / OS version: Windows 7 Enterprise. Service Pack 1
* URLs (if applicable):
* Node.js version: v8.11.1

**What steps will reproduce the problem?**

We are in the process of migrating from phantomJs 1.9.x to use Chrome headless browser. The existing headers and footers contain block elements, float styles and a img tag. None of these are working in puppeteer.
Are these not supported? The documentation states 'valid HTML markup'.
[https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions)

The example below contains h1 block element tags but they being displayed inline.
The html works fine in a standard html page displayed in chrome.

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

var header = "<h1>H1 tag</h1><h2>H2 tag</h2><hr style='border-bottom: 2px solid #8c8b8b;' />";

(async () => {
    var browser = await puppeteer.launch();
    var page = await browser.newPage();
    await page.goto('http://www.example.com/', { waitUntil: ['domcontentloaded', 'networkidle0'] });

    await page.pdf({
        path: 'sample.pdf',
        landscape: false,
        displayHeaderFooter: true,
        headerTemplate: header,
        margin: {
            top: '100px',
            bottom: '10px',
            right: '20px',
            left: '20px'
        }
    });

    await browser.close();
})();
```

**What is the expected result?**
The header renders in the same way as the Html does in a web page. The H1 and HR tags behave as block elements.

**What happens instead?**
All the elements appear in a single line as though they are inline elements.

I've attached a HTML page containing the sample.
[sample.zip](https://github.com/GoogleChrome/puppeteer/files/1915584/sample.zip)

Thanks,

**Comment by matthaywardwebdesign** [comment]
@DavidKisiel I'd imagine it is something to do with the following.

[https://www.w3.org/TR/WD-CSS2-971104/page.html#h-12.3.5](https://www.w3.org/TR/WD-CSS2-971104/page.html#h-12.3.5)

> The only difference is in their content: in headers and footers the content is limited to one line, and it may vary from page to page, since it can include variables. 

You might be better off placing the header and footer in the document itself and positioning using JS & CSS rather than using the headerTemplate functionality.

**Comment by DavidKisiel** [comment]
Thanks for the answer, that'll explain it.  
As PhantomJs did support the above example could this be a future feature. So the supporting of full HTML in the header and footer templates?

**Comment by ItsTarik** [comment]
any response to @DavidKisiel proposal before closing the issue ?
