### ISSUE TITLE
'npm install --save puppeteer' doesn't work on Ubuntu-Server 16.04

### ISSUE THREAD

**Issue by JumpinJ4ck** [puppeteer/puppeteer#2390]
### Steps to reproduce
`sudo npm install --save puppeteer`
Returns:
`&gt; puppeteer@1.3.0 install /home/ifm/NodeProjects/node_modules/puppeteer
&gt; node install.js

ERROR: Failed to download Chromium r549031! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/home/ifm/NodeProjects/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/ifm/NodeProjects/node_modules/puppeteer/.local-chromium' }
npm WARN enoent ENOENT: no such file or directory, open '/home/ifm/NodeProjects/package.json'
npm WARN NodeProjects No description
npm WARN NodeProjects No repository field.
npm WARN NodeProjects No README data
npm WARN NodeProjects No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.3.0 install: node install.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ifm/.npm/_logs/2018-04-16T14_08_27_047Z-debug.log`

**Tell us about your environment:**

* Puppeteer version:
1.3.0
* Platform / OS version:
Ubuntu-Server 16.04
* Node.js version:
v8.11.1

**What steps will reproduce the problem?**

`sudo npm install --save puppeteer`

**What is the expected result?**
For puppeteer to be installed and working

**What happens instead?**
The following error occurs:
`&gt; puppeteer@1.3.0 install /home/ifm/NodeProjects/node_modules/puppeteer
&gt; node install.js

ERROR: Failed to download Chromium r549031! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/home/ifm/NodeProjects/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/ifm/NodeProjects/node_modules/puppeteer/.local-chromium' }
npm WARN enoent ENOENT: no such file or directory, open '/home/ifm/NodeProjects/package.json'
npm WARN NodeProjects No description
npm WARN NodeProjects No repository field.
npm WARN NodeProjects No README data
npm WARN NodeProjects No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.3.0 install: node install.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ifm/.npm/_logs/2018-04-16T14_08_27_047Z-debug.log`

**Comment by aslushnikov** [comment]
Looks like NPM permissionsp roblem. This has been [discussed a lot](https://github.com/GoogleChrome/puppeteer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+EACCES+) on the bugtracker.
