### ISSUE TITLE
Headless mode on Windows 7 causes timeout, never completes

### ISSUE THREAD

**Issue by joshas** [puppeteer/puppeteer#2391]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Windows 7 x64
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

````
const puppeteer = require('puppeteer')
const devices = require('puppeteer/DeviceDescriptors')

const captureScreenshot = async () => {
  const browser = await puppeteer.launch({headless:true})
  const page = await browser.newPage()
  await page.goto('https://www.google.com/')
  await page.screenshot({path: 'screenshot.png', fullPage: true})
  await browser.close()
}

captureScreenshot()
````

1. npm install puppeteer
2. node index.js

**What is the expected result?**
Script runs and outputs screenshot.png into working directory.

**What happens instead?**
Script runs for a long time until it produces timeout warnings.
````
(node:4492) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:4492) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
````
If puppeteer.launch option "headless" is set to false, same script delivers expected result in about 5 seconds.

Capturing screenshot from http://info.cern.ch/ works in headless mode, so issue might be related to complexity of the page.

**Comment by vsemozhetbyt** [comment]
I cannot reproduce on Windows 7 x64 with the mentioned code and puppeteer 1.3.0-post (chromium_revision 549031)

**Comment by TheCloudlessSky** [comment]
Does this work?

```
const browser = await puppeteer.launch({
  headless: true,
  args: [
    '--proxy-server="direct://"',
    '--proxy-bypass-list=*'
  ]
});
```

**Comment by joshas** [comment]
@TheCloudlessSky Yes, adding proxy arguments works. Thank you. Is headless mode by default running through proxy?

**Comment by TheCloudlessSky** [comment]
@joshas It *shouldn't* be... but I've ran into serious problems with this too. I've added this comment to my code for those arguments:

```
    // Headless mode sometimes ignores the default OS proxy (by default none). This causes some
    // machines to take ~2 seconds per-request and significantly inflate the test suite run
    // time by more than 10x. This was also sometimes a problem when running PhantomJS. The
    // suggested workaround is to explicitly bypass all proxies:
    // https://github.com/Codeception/CodeceptJS/issues/561#issuecomment-373666779
    // https://peter.sh/experiments/chromium-command-line-switches/#proxy-server
    // https://peter.sh/experiments/chromium-command-line-switches/#proxy-bypass-list
```

**Comment by hbowden** [comment]
@TheCloudlessSky Why was this closed? While the work around works shouldn't the bug be fixed in puppeteer it's self so that Windows 7 users don't need a workaround?

**Comment by SmilingJoe** [comment]
I have spent a few days trying to track down why I wasn't getting any output generated from my headless:true, fullPage:true puppeteer script because of this issue. Finally found this thread after reproducing the problem using Puppeteer's basic example and having that throw an exception. Would really be nice to have this reopened - or at the very least update the documentation around the "fullPage:true" option to include a note for Windows 7 users to try this is they run into issues.

**Comment by SmilingJoe** [comment]
> 
> 
> @TheCloudlessSky Why was this closed? While the work around works shouldn't the bug be fixed in puppeteer it's self so that Windows 7 users don't need a workaround?

I have spent a few days trying to track down why I wasn't getting any output generated from my headless:true, fullPage:true puppeteer script because of this issue. Finally found this thread after reproducing the problem using Puppeteer's basic example and having that throw an exception. Would really be nice to have this reopened - or at the very least update the documentation around the "fullPage:true" option to include a note for Windows 7 users to try this is they run into issues.

**Comment by ukaeufe** [comment]
Have same issue with puppeteer@1.19.0 
The proxy workaround is fine. A bug fix is highly appreciated.

**Comment by linquize** [comment]
Still need this workaround on Win 7

**Comment by vipwan** [comment]
> 

Thank you so much! There is no problem with the development environment (win10), but there is a timeout problem when publishing to the server (2008R2) It didn't solve this problem until I found your reply!  😢

**Comment by JamieGrimwood** [comment]
Also getting a timeout on MacOS Sequoia 15.1 Beta, works fine in non headless and when I switch it starts giving timeouts left right and center.
