### ISSUE TITLE
 context.evaluate hangs if page.goto throws an error

### ISSUE THREAD

**Issue by sradu** [puppeteer/puppeteer#2395]
More of a question than an issue, I'm trying to debug why sometimes await of a page or frame .evaluate() just hangs. I have to end up killing the process.

When puppeteer runs evaluate() does it wait for an event to finish before executing the code?

**Comment by aslushnikov** [comment]
@sradu if the function passed to `page.evaluate` returns a promise, then the call won't return until the promise resolves. Could it be the case?

**Comment by sradu** [comment]
Unfortunately, no Promises are used. One evaluate body just iterates through forms to set a field, and does some internal existence checks.

And worse of all, it fails randomly. It's almost impossible to debug it.

**Comment by sradu** [comment]
I've isolated it to a tag manager, contents here: https://pastebin.com/hf2RnwGw. It seems to drop a lot of <script> tags, communicates over postMessage.

I can reproduce it once every 30-40 tries.

**Comment by sradu** [comment]
The script below hangs if localhost:2000 accepts the connection but doesn't respond.

````
const puppeteer = require('puppeteer');

args = [];
args.push('--no-sandbox');
args.push('--disable-setuid-sandbox');

(async () => {
  browser = await puppeteer.launch({
    headless: false,
    args,
  });

  page = await browser.newPage();

  await page.goto('about:blank', { waitUntil: 'load' });

  try {
    await page.goto('http://localhost:2000/sleep', { waitUntil: 'load', timeout: 2000 });
  } catch (err) {
    console.log(err);
  }

  await page.evaluate(() => {
    console.log('evaluating');
  });

  console.log('finished');
})();
````

and

````
def sleep
    sleep 40000
end
````

What it returns:
$ node bare.js 
````
Error: Navigation Timeout Exceeded: 2000ms exceeded
    at Promise.then (./code/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>
````

What I expect:
````
Error: Navigation Timeout Exceeded: 2000ms exceeded
    at Promise.then (./code/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>
evaluating
finished
````

**Comment by aslushnikov** [comment]
That's a good repro. We definitely shouldn't hang in this case in `page.evaluate`; instead, we probably need to reject right away since there's no execution context created.

**Comment by nokados** [comment]
The same issue. Is there any progress with this bug?
Is there a way to handle it?

**Comment by cmmartin** [comment]
@sradu @aslushnikov has anyone found a work around for this?

**Comment by infowifetch** [comment]
what have people done for this?
