### ISSUE TITLE
Support q: pipe html to Chrome

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#2398]
I have this question:
https://github.com/GoogleChrome/chrome-launcher/issues/106

This works for me for Firefox:

```bash
echo '<h1>hello, world</h1>' | /Applications/Firefox.app/Contents/MacOS/firefox /dev/fd/0
```

I am looking for a way to pipe html to Chrome instead of Firefox.

Is there a way to do that using this lib?

The biggest issue I have is actually locating the binaries on any platform. What puppeteer/chrome-launcher solve is getting the right binaries, at the very least.

**Comment by ORESoftware** [comment]
Still looking for answers to this one if anyone is out there, thx

**Comment by aslushnikov** [comment]
You can use `page.setContent`.

**Comment by ORESoftware** [comment]
nice that might work thank you
