### ISSUE TITLE
page.evaluate should implements timeout mechanism

### ISSUE THREAD

**Issue by rustkt** [puppeteer/puppeteer#2404]
> page.evaluate(pageFunction, ...args)
> returns: <Promise<Serializable>> Promise which resolves to the return value of pageFunction
> If the function passed to the page.evaluate returns a Promise, then page.evaluate would wait for the promise to resolve and return its value.

As the API documentation mentioned, if the page function passed into the page.evaluate returns a Promise, then page.evaluate would wait for the promise to resolve and return its value.

But how to abort if it took a long time? It's sensible to make page.evaluate receives a `timeout` argument, and implements it internally.

**Comment by Kalliser** [comment]
You can do the following tthings : 
```
Promise.race([
  page.evaluate(...),
  page.waitFor(5000)
]);
```

you can also check the [page.waitForFunction](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforfunctionpagefunction-options-args) method as there is a timeout argument

**Comment by rustkt** [comment]
Thank you for reply, it's a pretty convenient implementation, I will try it in my codes.

The reason I don't use `page.waitForFunction` is in my evaluate function it returns a Promise, which will be resolved by puppeteer, but `page.waitForFunction` needs the evaluate function returns a truthy value.

**Comment by Kalliser** [comment]
:)

But you can encapsulate page.waitForFunction into your own Promise so both way are possible.

**Comment by rustkt** [comment]
Okay, `Promise.race` can resolve my problem in a convenient way. Close this issue for the moment.
