### ISSUE TITLE
Localization of date in header/footer

### ISSUE THREAD

**Issue by Sjonnie2nd** [puppeteer/puppeteer#2408]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Windows 10
* URLs (if applicable): ..
* Node.js version: 9.11.1

**What steps will reproduce the problem?**
Using date in header/footer.

_Please include code that reproduces the issue._
`await page.pdf({`
`      //..`
`      displayHeaderFooter: true,`
`      headerTemplate: '<p></p>',`
`      footerTemplate: '<span class="date"></span>',`
`      margin: { bottom: '60px' }`
`});`

**What is the expected result?**
18-04-2018

**What happens instead?**
4/18/2018

Or simply put.. I'm located in The Netherlands where date's are normally formatted like dd-MM-yyyy.
Is it possible to get some kind of localization in the header/footer?

**Comment by yrshaikh** [comment]
Not sure if there is a support for localization or not. But you can always generate & format the date yourself and put it in the `footerTemplate` right?

**Comment by Sjonnie2nd** [comment]
@yrshaikh Hmm.. Strangely for a moment I was looking at the templates as being some static kind of thing in stead of being programmable. Sometimes you get blind for something and hold on to it.
Thanks for the input.
I'll close the issue.

**Comment by Pankajtanwarbanna** [comment]
{
format: "A4",
printBackground: true,
displayHeaderFooter: true,
headerTemplate: `<div style="font-size:7px;white-space:nowrap;margin-left:38px;">
                    ${new Date().toDateString()}
                    <span style="margin-left: 10px;">Generated PDF</span>
                </div>`,
margin: {
  top: '38px',
  right: '38px',
  bottom: '38px',
  left: '38px'
} }

**Comment by prsanjay** [comment]
@Pankajtanwarbanna The one which you added did not work for me. It prints ${new Date().toDateString() this as it is in pdf. Am I missing anything?

**Comment by Pankajtanwarbanna** [comment]
Later, I stored the value in a variable first, and then used ${print_this_date} instead of ${new Date().toDateString()}
