### ISSUE TITLE
When text flow overflow the fonticon at end be rendered to ellipsis fonticon.

### ISSUE THREAD

**Issue by luwuer** [puppeteer/puppeteer#2409]
### problem description
i find it at a select component.first time, i chosen a option and i found the fonticon was changed but never change back again when i chosen other options.
this problem just find in chrome now.

### basic info
**Puppeteer version: 65.0.3325.181**
**Platform / OS version: Windows 7 x64**

### problem reproduce
eg: [JsBin-demo](https://jsbin.com/qijixesuwu/1/edit?html,output)
you can open this eg to learn more details.

---
### modify 1
supplement the reproduce eg's description in the eg, you can click the 'change val' button to re-show this problem now.

**Comment by yrshaikh** [comment]
Sorry, it is not clear what you are asking here. Can you please elaborate more on the problem.

**Comment by luwuer** [comment]
@yrshaikh 
i re-code the demo above, you can find this problem by click the 'change val' button in the demo, hope it can show you my problem clearer.

Ps:  remove from the normal flow of the web page by `float | absolute` can avoid this problem, but i think  it is also a bug.

**Comment by aslushnikov** [comment]
I don't think this has anything to do with pptr per se; if you think it's a chrome bug, please file upstream to the https://crbug.com/new
