### ISSUE TITLE
Add keyboard.type

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#241]
We had `keyboard.type` in our plan for quite some time, but it seems to get lost.

**Comment by JoelEinbinder** [comment]
I keep internally debating the role of `page.type` and its relation to `keyboard.type`

**Comment by aslushnikov** [comment]
Can we have `page.type(selector, text, options)` and `keyboard.type(text, options)`? This would align with `page.click` and `mouse.click`
