### ISSUE TITLE
Puppeteer and AWS Lambda

### ISSUE THREAD

**Issue by sean-hill** [puppeteer/puppeteer#2413]
I would like to officially open an issue for 1st class support of running Puppeteer in AWS Lambda. I know in the [troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) doc it says it is not possible and that there are community work arounds. However, it would be especially awesome if as a community we could build support for AWS Lambda and Puppeteer right here in this repository. If this is not on the roadmap and never will be, feel free to close this issue. If not, than let's put our brains together and brainstorm!!!

You guys are the best.

**Comment by ebidel** [comment]
The linked resources are our recommendations, and created by the community. Anything wrong with those? IMO, Puppeteer shouldn't get into the business of compiling and vending Chrome binaries for different platforms.

**Comment by ratkorle** [comment]
I'm having a problem with clicking elements. Locally works perfect, but running on lambda says:
Node is not HTML Element or not visible. 
any Idea.>?
