### ISSUE TITLE
Execution Hangs Unexpectedly

### ISSUE THREAD

**Issue by mhaseebkhan** [puppeteer/puppeteer#2414]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: macOS 10.13.1 (17B1003)
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

This is a strange issue. I am trying to login to a site using puppeteer which works fine if I execute it in WebStorm using debug mode i.e. by applying break points and stepping through them. However, if I execute without breakpoints in WebStorm or from command-line, the control don't return after the following:

```javascript
// Launch puppeteer.
browser = await puppeteer.launch()

// Open a new page.
page = await browser.newPage()

// Set the default timeout to 0 for avoiding timeouts.
page.setDefaultNavigationTimeout(0)

await page.goto(url)

await page.click("#username")
await page.keyboard.type(userId)

await page.click("#password")
await page.keyboard.type(password)

// The culprit
await Promise.all([
  // Wait for navigation results.
  page.waitForNavigation({waitUntil: ['load', 'domcontentloaded', 'networkidle2']}),

  // Click the button to login.
  page.click("#signin"),
]);

// Get the redirected url.
redirected_url = await page.url()

console.log(redirected_url)
```
In the code above, `#signin` is a button. Another strange thing is that it is happening for a few sites, many others are working fine.

Thoughts?

**Comment by Kalliser** [comment]
Consider to add the [dumpio option](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) on puppeteer.launch() in order to watch if error are throws in background.

**Comment by hkhan-lumatax** [comment]
@Kalliser: Tried that. No error is thrown.

**Comment by aslushnikov** [comment]
@mhaseebkhan It's hard to say what's going on without being able to reproduce your script.

However, usually it means that the "signin" button is not there yet, or its event listeners are not installed yet. This way the "clicking" doesn't trigger the navigation you're awaiting; however, when you debug the script, there's enough time for the button to initialize.
