### ISSUE TITLE
Failed to run examples from README on Linux platform

### ISSUE THREAD

**Issue by qiuzhong** [puppeteer/puppeteer#2415]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Ubuntu 16.04.4
* URLs (if applicable): 
* Node.js version: 8.11.1
* Chromium downloaded during installing puppeteer: linux-549031 

**What steps will reproduce the problem?**
```
$ npm init -y
$ npm install puppeteer --save
$ node index.js
```
_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://github.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```

**What is the expected result?**
No error

**What happens instead?**
```
(node:22374) UnhandledPromiseRejectionWarning: Error: net::ERR_EMPTY_RESPONSE at https://github.com
    at navigate (/home/qiuzhong/Workspace/Programming/NodeJS/puppeteer_demo/node_modules/puppeteer/lib/Page.js:523:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:22374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22374) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
 **This issue was not reproduced on Windows 10**

**Comment by ebidel** [comment]
Please try a newer version of Puppeteer. 0.13.0 is very old.

**Comment by qiuzhong** [comment]
Sorry, it's actually the latest version: 1.3.0. I'll correct the typo and update the description.

**Comment by ebidel** [comment]
Can you through in the dumpio: true flag and see what it logs? Your code
looks fine.

**Comment by qiuzhong** [comment]
I got this error when I set the `dumpio` flag to be true:

```
[0420/131251.848052:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:39216/devtools/browser/c31b2d19-0db0-4f93-9dce-bcf715f7ab8e
(node:16676) UnhandledPromiseRejectionWarning: Error: net::ERR_EMPTY_RESPONSE at https://github.com
    at navigate (/home/qiuzhong/Workspace/Programming/NodeJS/puppeteer_demo/node_modules/puppeteer/lib/Page.js:523:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:16676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@qiuzhong for some reason chromium can't reach github.com. This is due to some environment issue; I'd try navigating to github from regular chrome, or running bundled pptr chromium manually and navigating there.

I'd also try answering the following questions for some self-diagnostics:
- Does `https://example.com` work?
- Does it work if you try navigating to locally-setup server?

Hope this helps.

**Comment by qiuzhong** [comment]
@aslushnikov , thanks for your suggestion. I tried both cases above, neither of them worked for me. The errors are still the same.

**Comment by qiuzhong** [comment]
Finally, I used an old version of chromium and specify the `executablePath` option in `launch()`. It worked for me. The old revision is `515411`  while the current chromium downloaded during installing puppeteer is `540931`.
