### ISSUE TITLE
How to speed up // parallelize puppeteer ?

### ISSUE THREAD

**Issue by laurentdebricon** [puppeteer/puppeteer#2416]
Hello,
how do you manage to render a lot html with chrome headless ?

Do people manage to do it with a gpu ?

Can someone share me his perf // running machine ? So far it's like i can only run two rendering at the same time on a intel i7 cpu. It takes 3 secondes each.

imagine I want to render 100 000 pages quickly ?

Best regards

**Comment by aslushnikov** [comment]
@laurentdebricon  There's been a lot of discussions on parallelizing pptr on the bugtracker. Try searching bugtracker for the `generic-pool` node module (there are success stories on using it together with pptr).
