### ISSUE TITLE
Pdf generated has a size lower than expected

### ISSUE THREAD

**Issue by vguerin533** [puppeteer/puppeteer#2417]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: MacOS High Sierra 10.13.3 
* URLs (if applicable):
* Node.js version: v9.4.0

**What steps will reproduce the problem?**

page.setViewport({width: 2400, height: 1600});
const viewport = page.viewport();
await page.pdf({
	path: 'export.pdf',
	printBackground: true,
	width: viewport.width,
	height: viewport.height
});

**What is the expected result?**

I expect the pdf to have a resolution of 2400 x 1600.

**What happens instead?**

The pdf file generated has a resolution of 1800 x 1200.

<img width="186" alt="capture d ecran 2018-04-19 a 14 59 52" src="https://user-images.githubusercontent.com/35684565/38992888-6183d76a-43e2-11e8-9bc8-36aeff3819cc.png">

**Comment by aslushnikov** [comment]
@vguerin533 Can you please file this upstream to the chromium repository? The Chromium PDF team will be happy to take care of this.
