### ISSUE TITLE
Evaluate returns undefined but chromium correctly has value inside evaluate

### ISSUE THREAD

**Issue by chrisabrams** [puppeteer/puppeteer#2418]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: OS X Sierra 10.12.6
* URLs (if applicable):
* Node.js version: 8.10.0

**What steps will reproduce the problem?**

You can run this gist here: https://gist.github.com/chrisabrams/a2a098d1b2d697f349f4e1ad1be98602

**What is the expected result?**
The expected result is that evaluate will return the list of nodes

**What happens instead?**
Instead, evaluate returns `undefined`

**Comment by vsemozhetbyt** [comment]
If I get this right, DevTools protocol cannot serialize an array of nodes and resolves it to `undefined`. If you make it an array of strings, this works:
```js
return nodes.map(({ innerText }) => innerText)
```

**Comment by vsemozhetbyt** [comment]
[See in the doc](https://github.com/GoogleChrome/puppeteer/blob/v1.3.0/docs/api.md#pageevaluatepagefunction-args):

> If the function passed to the `page.evaluate` returns a non-Serializable value, then `page.evaluate` resolves to `undefined`.

**Comment by yanivefraim** [comment]
How about throwing an error when evaluate returns a non-Serializable value? cc @aslushnikov

**Comment by chrisabrams** [comment]
Got it @vsemozhetbyt. I would concur on adding a error when the value being returned is not serializable.

**Comment by aslushnikov** [comment]
@yanivefraim @chrisabrams we were there at one moment, but had to change to `undefined` because there are many evaluations that happen for the sake of evaluation rather then return value.

```js
await page.evaluate(() => window.saveValue = document.body);
```

We consider returning a special value in this case instead to emphasize the difference.

**Comment by chrisabrams** [comment]
@aslushnikov I see what you're saying. In my case, I need to know the `saveValue` outside of the evaluation. I can make serialization work though.

**Comment by aslushnikov** [comment]
> In my case, I need to know the saveValue outside of the evaluation. I can make serialization work though.

@chrisabrams why don't you use the `page.evaluateHandle` then?
