### ISSUE TITLE
feature request: throw an error in case of page.evaluate returning non-Serializable value

### ISSUE THREAD

**Issue by yanivefraim** [puppeteer/puppeteer#2420]
follow-up for https://github.com/GoogleChrome/puppeteer/issues/2418:

Today, `page.evaluate` returns `undefined` in case of a non-Serializable returned object (see [docs](https://github.com/GoogleChrome/puppeteer/blob/v1.3.0/docs/api.md#pageevaluatepagefunction-args)). It could be nice to have an error for such case (it is not intuitive to have undefined returned here, IMO)

**Comment by aslushnikov** [comment]
Throwing an error would be a breaking change; let's consider it as a part of #2079 (I've updated the issue)
