### ISSUE TITLE
Status Code and Reason Phrase

### ISSUE THREAD

**Issue by mboeser** [puppeteer/puppeteer#2421]
Is Puppeteer able to read the Reason Phrase from the Status Code? I'm not able to find it in the raw response data. If not, possible new feature...?

_The Status-Code element is a 3-digit integer result code of the attempt to understand and satisfy the request. These codes are fully defined in section 10. The Reason-Phrase is intended to give a short textual description of the Status-Code. The Status-Code is intended for use by automata and the Reason-Phrase is intended for the human user. The client is not required to examine or display the Reason- Phrase._

https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1.1

**Comment by aslushnikov** [comment]
Dupe of #317
