### ISSUE TITLE
h264 not support under headless mode

### ISSUE THREAD

**Issue by starcwl** [puppeteer/puppeteer#2422]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.2
* Platform / OS version: mac 10.13.4
* URLs (if applicable):
* Node.js version: 8.11

**What steps will reproduce the problem?**

if I set headless to false,  when I use createOffer of webrtc. It works right with H264 in SDP. but when I set headless to true. there is no H264 in SDP anymore. 

**What is the expected result?**

**What happens instead?**

**Comment by yrshaikh** [comment]
Can you please share the sample code?

**Comment by benjamingr** [comment]
This is a known issue, you need to use Chrome and not Chromium for it to work.

**Comment by aslushnikov** [comment]
@starcwl the repro would be very helpful. If it works in non-headless and breaks in headless, it could be that we don't build h264 into the headless.

**Comment by benjamingr** [comment]
It doesn't work in Chromium, it works in Chrome - independent of whether or not it's headless

**Comment by aslushnikov** [comment]
Thanks @benjamingr, in this case it is indeed has been discussed quite a lot on the bugtracker.
