### ISSUE TITLE
elementHandle.screenshot() produces blank screenshots for elements outside of viewport

### ISSUE THREAD

**Issue by brianreese** [puppeteer/puppeteer#2423]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: OS X 10.12.6
* URLs (if applicable): N/A (Test script uses https://github.com but I've noticed the issue on other pages)
* Node.js version: 8.1.4

**What steps will reproduce the problem?**
Using elementHandle.screenshot in the following test script, capturing an element outside of the viewport results in a blank / empty screenshot.

_Please include code that reproduces the issue._

``` js

import puppeteer from 'puppeteer';

const VIEWPORT = {width: 1200, height: 900};
const URL = 'https://github.com/';
const TESTELEMENT = '.footer';

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.setViewport(VIEWPORT);
  await page.goto(URL, { waitUntil: 'networkidle0' });


  // Full page screenshot.
  await page.screenshot({
    path: 'tmp/testPage.png',
    fullPage: true
  });

  // Screenshot using element handle.
  const element = await page.$(TESTELEMENT);
  await page.waitFor(1000);
  await element.screenshot({
    path: 'tmp/testElement.png',
  });

  // Screenshot using the element's bounding box.
  const elementBounds = await element.boundingBox();
  await page.screenshot({
    path: 'tmp/testClip.png',
    clip: elementBounds,
  });

  await browser.close();
})()

```

**What is the expected result?**

The screenshot taken using the element handle should capture the footer for the url provided. The screenshot that supplies the element's bounding box should also capture the footer.

**What happens instead?**

The full page screenshot is fine, but the other two are blank (white). If I adjust the script and increase the viewport height to something really large, like 9999px, the footer is within the initial viewport and the problematic screenshot come out fine.

**Comment by VesterDe** [comment]
I'm having a similar issue with Puppeteer, but for me out-of-viewport elements otherwise work, but seem to fail if the distance (x/y) and/or size(w/h) of the element contain decimals.

A minimal script that replicates this can be found [here](https://gist.github.com/VesterDe/4daad7d758e74268f81293f1ab7a4201). Run that through https://try-puppeteer.appspot.com/ and it will log the bounding rectangles for both selectors.

**Comment by brianreese** [comment]
@VesterDe, I can confirm the element I attempted to capture also has a vertical offset containing decimals.

The issue also seems to begin with puppeteer v1.2. Both my test script and @VesterDe's script produce the expected results with version 1.1.1

**Comment by bclinkinbeard** [comment]
I'm seeing some weird coordinates issues with `elementHandle.screenshot()` in 1.3 as well. I have a script that captures the code blocks from all of my blog pages and for one specific page the coordinates are all off.

**One of many working pages:** https://benclinkinbeard.com/d3tips/utility-methods-with-d3-array/
**The only problem page:** https://benclinkinbeard.com/d3tips/a-reusable-function-for-creating-charts-with-axes/
**Relevant code from a set of utils I'm using:**

```javascript
async function initPuppeteer(options = { args: ['--no-sandbox'] }) {
  const browser = await puppeteer.launch(options)
  const page = await browser.newPage()
  return { browser, page }
}

async function getScreenshotBuffer(page, selector) {
  let buffers = []

  if (!selector) {
    buffers = [await page.screenshot()]
  } else {
    const targets = await page.$$(selector)
    const promises = targets.map(elHandle => elHandle.screenshot())
    buffers = await Promise.all(promises)
  }

  return buffers
}

async function getBuffersFromURL(
  url,
  width = 2000,
  height = 800,
  selector = 'div.highlight',
) {
  const { browser, page } = await initPuppeteer()
  page.setViewport({ width, height, deviceScaleFactor: 2 })
  await goToURL(page, url)
  const buffers = await getScreenshotBuffer(page, selector)
  await browser.close()
  return buffers
}
```

Instead of getting that very simple first code block I get this:

![image](https://user-images.githubusercontent.com/140343/39086436-3ce236c6-455f-11e8-9c8c-983ae0de350b.png)

**Comment by bclinkinbeard** [comment]
I'm also seeing weirdness that is not just coordinate offsets. It's hard to tell in the GitHub UI but there is a big white bar at the top of the below image where the opening tag should be.

![d3-day-3-building-a-real-bar-chart_01](https://user-images.githubusercontent.com/140343/39090183-e781cbd2-45a5-11e8-8624-6d0225adb08d.png)

**Comment by bclinkinbeard** [comment]
Related to #2263, #2357, and/or #2166 ?

**Comment by bclinkinbeard** [comment]
I solved my problem. Several concurrent calls to `elementHandle.screenshot()` is apparently not feasible, which makes sense when you slow it down and see how it works. I made the following change to grab screenshots serially instead of in parallel.

```javascript
const handles = await page.$$(selector)

// no more of this
// const promises = [targets[0]].map(elHandle => elHandle.screenshot())
// buffers = await Promise.all(promises)

// this instead
while (handles.length) {
  const handle = handles.shift()
  const buffer = await handle.screenshot()
  buffers.push(buffer)
}
```

**Comment by delesseps** [comment]
Experiencing same issue scrolling to capture elements outside the viewport, in my case floating tooltips.

I've noticed it only happens in headless mode, changing config to `headless: false` seems to resolve if that helps identifying the problem/finding a solution.

**Comment by seraphinmiranda** [comment]
I also had the same issue one hour ago ^^
I solved the problem by changing to a higher viewport.

**Comment by bluepeter** [comment]
Any update on this? It's even worse in later versions of Puppeteer/Chromium... before, we could at least `.hover()` or `.click()` the out-of-viewport element to bring it into view prior to `.screenshot()`... but now even this hacky solution is no longer working, and the screenshot is totally blank (though dimensionally correct).

**Comment by galenhuntington** [comment]
The third method above (getting the bounding box of the element and using it to clip in `page.screenshot`) is working for me now in 1.16.0.  That is, screenshotting the element still gives a blank image, but the bounding box method correctly gives an image of it.

**Comment by bluepeter** [comment]
To be clear, this code is now nicely working for us without (any yet discovered) issues:

```
        const screenshot = await chromePage.screenshot({
          clip: await targetElement.boundingBox(),
        });
```

**Comment by nesttle** [comment]
@bluepeter Well, isn't working for me

**Comment by davidtorroija** [comment]
> Experiencing same issue scrolling to capture elements outside the viewport, in my case floating tooltips.
> 
> I've noticed it only happens in headless mode, changing config to `headless: false` seems to resolve if that helps identifying the problem/finding a solution.

Same to me it works with headless false, but I need headless to run in a headless server after those tests

**Comment by bestis** [comment]
I'm seeing blank/gray even if I scrolled the element visible manually.

If I have small viewport some pictures over it will success, but if I have really long page the elements somewhere after 4000-5000 px height will just give gray, even if scrolled visible.

Only working solution I've found is to put the viewport height to something huge as 64k so that evertyhing will fit to it and then it works.

**Comment by nsourov** [comment]
I tried with 
```javascript
async function screenshotDOMElement(opts = {}) {
    const padding = "padding" in opts ? opts.padding : 0;
    const path = "path" in opts ? opts.path : null;
    const selector = opts.selector;

    if (!selector) throw Error("Please provide a selector.");

    const rect = await page.evaluate(selector => {
      const element = document.querySelector(selector);
      console.log({ element, selector });
      if (!element) return null;
      setTimeout(() => element.scrollIntoView({ block: "center" }), 1000);
      const { x, y, width, height } = element.getBoundingClientRect();
      return { left: x, top: y, width, height, id: element.id };
    }, selector);

    if (!rect)
      throw Error(`Could not find the element that matches selector: ${selector}.`);

    return await page.screenshot({
      path,
      clip: {
        x: rect.left - padding,
        y: rect.top - padding,
        width: rect.width + padding * 2,
        height: rect.height + padding * 2
      }
    });
  }
```
But that ^ function gives empty images when the div is out of viewport.

```javascript
const puppeteer = require("puppeteer");
(async () => {
  const browser = await puppeteer.launch({ headless: false, devtools: true });
  const page = await browser.newPage();
  // Adjustments particular to this page to ensure we hit desktop breakpoint.
  await page.goto("http://www.producepriceindex.com/", {
    waitUntil: "networkidle2"
  });
  const handle = await page.$("[id=\"block-block-1\"]");
  await handle.screenshot({
    path: "element.png"
  });
  await browser.close();
})();
```
But this worked for me.

Puppeteer version: 2.1.1
Platform / OS version: OS X 10.13
Node.js version: 12.15

**Comment by marcelotedeschi** [comment]
I managed to fix my issue by setting the `viewport` before taking the screenshots.
The important thing was to get the full `height` of the page where everything I wanted to screenshot was visible. In my case, everything was a child of a `.application-wrapper` div. So the code looks something like this:

```js
const VIEWPORT = { width: 1280, height: 720, deviceScaleFactor: 2 }; // Your default values
await page.goto(url, { waitUntil: 'networkidle0' });

const fullPage = await page.$('.application-wrapper');
const fullPageSize = await fullPage.boundingBox();
await page.setViewport(
  Object.assign({}, VIEWPORT, { height: fullPageSize.height })
);

// Element screenshot logic
const elements = await page.$$('.screenshot-element');

for (const [index, element] of elements.entries()) {
  await element.screenshot({ path: `/tmp/${index}.png` });
}
```

**Comment by kan0s** [comment]
> ```js
> await page.setViewport(
>   Object.assign({}, VIEWPORT, { height: fullPageSize.height })
> );
> ```
Thanks. It works for me with `height: parseInt(fullPageSize.height)`

**Comment by marcelotedeschi** [comment]
@kan0s cool! Probably using `parseInt` makes more sense as I read some people were having troubles with heights containing decimal points. In my case, all the elements have fixed heights, so I didn't have to worry about it.

**Comment by zeroN1** [comment]
@marcelotedeschi You are a savior; setting the viewport worked perfectly. Although I needed to use parseInt to convert height before getting the boundingBox for full page

**Comment by wassim-ben-amor** [comment]
Hello, what if there are some elements in the page that are using 'vh' as height ? for example `70vh`.
Setting the viewport to the fullPageSize height, will make this element take all the 70vh of the viewport.

**Comment by OrKoN** [comment]
I am not able to reproduce the issue with the latest version of Puppeteer, presumably fixed.
