### ISSUE TITLE
Operation without chrome

### ISSUE THREAD

**Issue by adriansikora344** [puppeteer/puppeteer#2424]
Hi!

How to parade a page without a chrome browser? Parasizing the page is over, but if I want to put it on an external server for the example of VPS, it is necessary for the page's JavaScript to be parsed so that the entire page content is loaded. If I disable the browser by:

```
        const browser = await puppeteer.launch({
            headless: true
        });

```

This page paring works only for pure HTML code, JavaScript does not run. What should I configure to make the puppeter work without running the browser?

**Comment by ebidel** [comment]
That snippet of code doesn't disable JavaScript. It launches chrome in headful mode.

Puppeteer is a tool for interacting with the browser. If you don't want to run it, I'm not sure it's the right tool for your job :)
