### ISSUE TITLE
Error: Protocol error (Page.setBypassCSP): 'Page.setBypassCSP' wasn't found undefined

### ISSUE THREAD

**Issue by chrisleekr** [puppeteer/puppeteer#2429]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):
* Node.js version: 8.11.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Upgrade puppeteer to v1.3.0
2. Added `page.setBypassCSP(true)`

Note that I am using Google Chrome from Google official website for puppeteer test.
```bash
$ wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
$ sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
$ apt-get update && apt-get install -y google-chrome-stable && ln -s /usr/bin/google-chrome-stable /usr/bin/chromium-browser
```

```javascript
browser = puppeteer.launch({
      headless: true, args: ['--no-sandbox', '--disable-web-security', '--disable-gpu'],
      // '--disable-dev-shm-usage'
      executablePath: '/usr/bin/chromium-browser',
});
page = browser.newPage();
page.setJavaScriptEnabled(true);
page.setBypassCSP(true); // Added this line
```

**What is the expected result?**

No error expected

**What happens instead?**
```
Error: Protocol error (Page.setBypassCSP): 'Page.setBypassCSP' wasn't found undefined
    at Promise (/srv/node_modules/puppeteer/lib/Connection.js:200:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/srv/node_modules/puppeteer/lib/Connection.js:199:12)
    at Page.setBypassCSP (/srv/node_modules/puppeteer/lib/Page.js:617:24)
```

**Comment by chrisleekr** [comment]
Once I change to use puppeteer Chromium instead of Chrome from Google offical website, it starts working. 

I close the issue.

**Comment by kusdavletov** [comment]
@chrisleekr Could you please share how did you use puppeteer Chromium?

**Comment by chrisleekr** [comment]
@kusdavletov Hi, I am just using latest version which is already fixed with above issue.

https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-pagesetbypasscspenabled

**Comment by kusdavletov** [comment]
@chrisleekr Hi, could you please share your Docker file? 😄
