### ISSUE TITLE
can not find window.gremlins  while using gremlins in puppeteer

### ISSUE THREAD

**Issue by sunnyYanan** [puppeteer/puppeteer#2432]
* Puppeteer version:1.3.0
* Platform / OS version:sierra 10.12.6
* URLs (if applicable):
* Node.js version:9.10.1
 
i want use gremlins -a monkey testing library  in puppeteer,   

`
await page.addScriptTag({
    url: 'https://rawgithub.com/marmelab/gremlins.js/master/gremlins.min.js'
  });
`

`
await page.evaluate(() => {
    window.gremlins.createHorde().unleash();
  });
`

but it can not work well because it can not find window.gremlins

**Comment by yrshaikh** [comment]
Can you try adding some wait time?

**Comment by yrshaikh** [comment]
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('https://google.com');
    await page.addScriptTag({ url: 'https://rawgithub.com/marmelab/gremlins.js/master/gremlins.min.js' });
    await page.evaluate(() => { window.gremlins.createHorde().unleash(); });    
})();
```

Worked for me.

**Comment by sunnyYanan** [comment]
could you give me a full example, with node environment?   it still didn't work for me

**Comment by sunnyYanan** [comment]
but if change the web to a different, such as 'https://www.baidu.com/' , it will fail.

**Comment by aslushnikov** [comment]
@sunnyYanan looks like gremlin.js fails to initialize on www.baidu.com; I'd file this upstream to https://github.com/marmelab/gremlins.js
