### ISSUE TITLE
Get more responses than expected

### ISSUE THREAD

**Issue by jiladahe1997** [puppeteer/puppeteer#2436]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.3.0
* Platform / OS version: Windows 7
* URLs (if applicable): 
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

I writed a simple code to show the problem:
``` javascript
var puppeteer =require('puppeteer')
var counter ={
    req:0,
    res:0
};


(async function () {
    var browser = await puppeteer.launch({
        headless:false,
        devtools:true,
    })
    var page = await browser.newPage();

    //listen on "request"
    page.on("request",async function (req){
        if(req.url().match("fanyi.baidu.com/v2transapi")) {
            counter.req ++
            console.log("req:",counter.req,"res",counter.res);
        }
    })
    //listenon "response"
    page.on("response",async function (res){
        if(res.url().match("fanyi.baidu.com/v2transapi")) {
            counter.res ++
            console.log("req:",counter.req,"res",counter.res ,"length", (await res.text()).length);
        }
    })

    await page.goto("https://fanyi.baidu.com/#en/zh/hello")
    //await browser.close()
})()





// expected result :                                       
   req :1 res : 0                                             
   req :1 res : 1  length 64411                   

//actully:
    req: 1 res 0
    (node:16084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 
    Protocol error (Network.getResponseBody): No resource with given identifier found undefined
    (node:16084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the 
    future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit 
    code.
    req: 2 res 1
    req: 2 res 2 length 64411
```
I want to catch the request whose URL contain "fanyi.baidu.com/v2transapi" . 

And I have catch it manually in my **Chrome Dev Tool**  (without using puppeteer) , There is only **one** request contain URL "fanyi.baidu.com/v2transapi"

However , when I use putteteer , I catch **two** request and  **two** response .

And I have tried other sites . Some of them have the same problem , and some sites even get this:
``` javascript
// some sites
  req :1 res : 0                                               
  req :1 res : 1 
  req :1 res : 2 // response is more than request!
```
<br>

-------------------------------------------------------------------------

I have noticed that in API document said:

> If request fails at some point, then instead of 'requestfinished' event (and possibly instead of 'response' event), the 'requestfailed' event is emitted.

I don't know the cause of my problem and if it's exactly the situation said in the document .  any response/help will be much appreciated.

--------------------------------------------------------------------------
**Thanks for reading !**

**Comment by jiladahe1997** [comment]
After reading the source code  and Chrome DevTools Protocol . I thought that is a problem caused by Chrome DevTools Protocol rather than puppeteer .  

But I'm not sure about that . any response/help will be much appreciated . Thanks

**Comment by aslushnikov** [comment]
> And I have catch it manually in my Chrome Dev Tool (without using puppeteer) , There is only one request contain URL "fanyi.baidu.com/v2transapi"
> 
> However , when I use putteteer , I catch two request and two response .

@jiladahe1997 it looks like the website reloads itself if it runs for the first time for the user. That's why there are two requests to the URL you mention. 

You can see this behavior with devtools:
1. Open chrome Incognito mode
2. Open devtools
3. In Network panel, click "preserve log" checkbox. This way the network panel will preserve requests/responses across navigations
4. navigate to the https://fanyi.baidu.com/#en/zh/hello

> And I have tried other sites . Some of them have the same problem , and some sites even get this:
> ... // response is more than request!

This is hard to judge; if you have a repro, please re-file a separate issue. We'll take a look.
