### ISSUE TITLE
Add target.evaluate and target.evaluateHandle

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#2438]
Related to https://github.com/GoogleChrome/puppeteer/issues/1215.

Lighthouse has [started testing](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-extension/test/extension-test.js#L63-L79) its chrome extension using pptr. They currently use`createCDPSession` to inject code into the extension and run methods:

```js
    const targets = await browser.targets();
    const extensionTarget = targets.find(({_targetInfo}) => {
      return _targetInfo.title === 'Lighthouse' && _targetInfo.type === 'background_page';
    });

    if (!extensionTarget) {
      return await browser.close();
    }

    const client = await extensionTarget.createCDPSession();
    const lighthouseResult = await client.send('Runtime.evaluate', {
      expression: `runLighthouseInExtension({
          restoreCleanState: true,
        }, ${JSON.stringify(lighthouseCategories)})`,
      awaitPromise: true,
      returnByValue: true,
    });
```

It would be nice to make this use case easier:

```js
const lighthouseResult = target.evaluate(cats => {
  return runLighthouseInExtension({restoreCleanState: true}, cats);
}, lighthouseCategories);
```

**Comment by aslushnikov** [comment]
It should be possible to create a `Page` out of extension's background page. So we should simply teach `target.page()` to work with `background_page`.
