### ISSUE TITLE
Target: pass through "background_page" types

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#2439]
Related to https://github.com/GoogleChrome/puppeteer/issues/2438.

The lighthouse chrome extension tests [check](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Target.js#L60) a private `target._targetInfo` property to verify the target is the LH background page:

```js
const targets = await browser.targets();
const extensionTarget = targets.find(({_targetInfo}) => {
  return _targetInfo.title === 'Lighthouse' && _targetInfo.type === 'background_page';
});
```

We should pass through this type through so `target.type()` works as expected. We currently mark it as "other":

https://github.com/GoogleChrome/puppeteer/blob/e9dc3ae74fc01a99d1d5b66ffe716b4de4aa39e8/lib/Target.js#L58-L63

**Comment by aslushnikov** [comment]
This is fixed by https://github.com/GoogleChrome/puppeteer/pull/2493.
