### ISSUE TITLE
Method to skip installing Chromium

### ISSUE THREAD

**Issue by Garbee** [puppeteer/puppeteer#244]
## Problem

As it is, every Puppeteer install will pull its own internal Chromium copy. Whether or not it is actually used. This can end up using a lot of extra space, at 92Mb per copy currently, on peoples drives. Primarily locally where you may have multiple projects all using the tool.

## Action

There should be some mechanism for skipping this download when installing dependencies if you intend to use an already existing copy of Chrome/Chromium.

**Comment by aslushnikov** [comment]
You can install puppeteer with `npm install --ignore-scripts`. It also skips install scripts for puppeteer dependencies, but it works fine for now.

**Comment by Garbee** [comment]
That's fine for messing with this repo itself. However, what about when people are requiring puppeteer in their projects and they have scripts they need to run after install to get things setup?

**Comment by JoelEinbinder** [comment]
If you try hard enough you can make it work. I don't think we should do much to encourage this. Right now Puppeteer is very tied to the version of Chromium it is bundled with. At the moment even a version from a few days earlier will be unusable.

**Comment by aslushnikov** [comment]
@Garbee was it a problem with phantomjs-prebuilt?

There's a way we can make this work. Currently, puppeteer uses its package folder to keep chromium revision. If instead we use a shared directory, e.g. `$HOME/.puppeteer-chromium-versions`, we won't have any duplication.

Today's puppeteer is too young of a project, we'd rather not do this unless there are real use cases and a strong demand.

**Comment by Garbee** [comment]
`$HOME` isn't exactly robust enough. Things may not be ran as a user with a home directory.

Ideally, I think we'd check for the environment on install. Then if a given variable exists and is the right value, don't pull the local version. Instead use the defined chromium path. Then in the system when calling chromium, you always use the path if this is set as well.

<details>
<summary>Skip download</summary>

```js
if (process.env.PUPPETEER_PREVENT_INTERNAL_CHROMIUM === 'yes') {
  console.log('Not installing internal Chromium. Expecting binary to be located at $CHROMIUM_PATH');
  process.exit(0);
}
```

</details>

Nothing with phantomjs stuff. I just noticed this is going to happen on every pull. It's thinking ahead to when we release and more projects are using it, there will inevitably loads of extra disk space used.

I understand that right now it is very much a bleeding edge thing and Chromium needs to keep getting updated. But at this stage, that's also acceptable. The issue was more focusing on a long-term issue so we can start assessing proper resolution strategies.

**Comment by vsemozhetbyt** [comment]
Maybe it is worth to use one  environment variable (like `PUPPETEER_EXECUTABLE_PATH`) for two goals: to prevent installing Chromium and to eliminate the need of setting `executablePath` in the `puppeteer.launch()` every time?

**Comment by sukrosono** [comment]
@vsemozhetbyt It's good idea, If `PUPPETEER_EXECUTABLE_PATH` is set, will use that path for launch and also skipping installing Chromium. When it's not set will Install and after it set the installation directory to `PUPPETEER_EXECUTABLE_PATH`.

**Comment by aslushnikov** [comment]
@brutalcrozt there's already a way to skip Chromium download with [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`](https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#environment-variables) env variable.

**Comment by shmdhussain** [comment]
@aslushnikov what is the value for the PUPPETEER_SKIP_CHROMIUM_DOWNLOAD?

do I need to set up in PATH variable?

**Comment by ebidel** [comment]
@shmdhussain you can set it to anything. It just needs to be defined in `env`. `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = true` for example

**Comment by shmdhussain** [comment]
Thanks ...I updated the same as you mentioned in bash.profile...now working good without installing chromium....testing screenshot comparison of element based on the example from Monica dinculescu

**Comment by T0T4R4** [comment]
That is what i did 
`echo "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install -g puppeteer" | sudo sh`

**Comment by aslushnikov** [comment]
As of v1.7.0 the recommended way to get Puppeteer without downloading Chromium instance is  [`puppeteer-core`](https://www.npmjs.com/package/puppeteer-core) - see details in [puppeteer vs puppeteer-core](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core).

**Comment by CarlosEduR** [comment]
I have a question: what If my puppeteer script only works 100% on its own chromium instance? I've tried with local chrome, local chromium, but at some point, doing hard work, the script brokes, not finding some classes on page.

**Comment by albanx** [comment]
Does any one knows a way to disable `export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`
I tried:
`export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false`
`npm config delete PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`
`unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`

But still `npm install puppeteer` will refuse to download chromium

**Comment by doenikoe** [comment]
use `unset` to disable env variables. eg: `unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`

**Comment by doot0** [comment]
@doenikoe - @albanx already mentioned that using `unset` did not work for them.

@albanx If you have a non-default shell (e.g. zsh) then try using `unset` after switching to `bash`.

**Comment by lockevn** [comment]
> As of v1.7.0 the recommended way to get Puppeteer without downloading Chromium instance is [`puppeteer-core`](https://www.npmjs.com/package/puppeteer-core) - see details in [puppeteer vs puppeteer-core](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core).

I have a helper (TypeScript) Library, which depends on `puppeteer`. 
People using that lib can use `let page = await Lib.NewPrivatePage(browser)`, and that browser is of type `puppeteer.Browser`

Is it possible to modify my Lib to work with both `puppeteer.Browser` and `puppeteer-core.Browser`? or I have to change to `NewPrivatePage(browser: any)`

**Comment by Garbee** [comment]
@lockevn That's a question for whomever maintains that typescript library. It should be possible though as they'd just need to do and "or" against the types. But, afaik the typescript library isn't maintained here.

**Comment by ORESoftware** [comment]
can't puppeteer just be smart enough to look in `node_modules/puppeteeer/chromeeeeeem` and then `mv` the file out, not reinstall it, and then `mv` it back?  Or something

By the time we forget to --ignore-scripts, it's already too late..puppeteer has to do this for it's users.

**Comment by leviethung2103** [comment]
The solution provided 

> You can install puppeteer with `npm install --ignore-scripts`. It also skips install scripts for puppeteer dependencies, but it works fine for now.

This solution worked for me.

**Comment by nazmulhasan21** [comment]
You can install puppeteer run this ''npm install --ignore-scripts puppeteer''  your cmd.

**Comment by jesben** [comment]
> Does any one knows a way to disable `export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` I tried: `export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false` `npm config delete PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` `unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`
> 
> But still `npm install puppeteer` will refuse to download chromium

If PUPPETEER_EXECUTABLE_PATH exists it will also skip download!
