### ISSUE TITLE
PDF file size is unexpectedly high

### ISSUE THREAD

**Issue by tradiff** [puppeteer/puppeteer#2440]
The pdf files generated by Puppeteer are quite a bit larger than the ones generated by PhantomJs.
(80 KB vs 36 KB for one page, and 1,019 KB vs 391 KB for another page).

These files are not image heavy at all.  The first one has no images at all.  I suspect embedded fonts might be the cause for the file size, based on Adobe Acrobat Pro's Space Audit.  We do not use web fonts, just Arial and Times New Roman.

Is there anything I can do to reduce the file size?  Perhaps some way to not embed fonts into the pdf?

puppeteer version: puppeteer@1.3.0 or puppeteer@1.3.0-next.1524503013067
Node.js version: 8.11.1
OS: Windows 10

**Comment by aslushnikov** [comment]
@TravisTX can you please file this issue upstream to the chromium repository? Chromium PDF team might be able to help here. See https://crbug.com/new

Also, make sure to include a small example website that generates a huge pdf for you. This will ease debugging for the chromium devs.

Thanks!

**Comment by tradiff** [comment]
Created an issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=838168
