### ISSUE TITLE
Is it possible to add image in header/footer when generating pdf?

### ISSUE THREAD

**Issue by LiCasey** [puppeteer/puppeteer#2443]
I am using puppeteer to generate pdf files from webpage of my own site, and I would like to add a logo to the header on every page of the pdf file. I've tried using <img /> tag in the headerTemplate option, but it seems that the image wasn't rendered correctly. I get a gray outline of the image instead.

<img width="426" alt="snipaste_2018-04-25_17-39-52" src="https://user-images.githubusercontent.com/13477500/39238119-01d50816-48b0-11e8-88a1-d9d5892769dc.png">

    headerTemplate: `
      <div style="display:flex;width:90%;font-size: 10px;padding: 5px 0;margin:auto;border-bottom: 0.5px solid black;">
        <div style="width:25%"><img src="/public/images/logo.png" style="width:30px;height:30px;"/></div>
        <div style="width:50%;text-align:center">Header</div>
        <div style="width:25%;text-align:right"></div>
      </div>`

Is it possible to use image in header/footer(by using img tag or css background-image property)? If possible, how should I config the image url?

**Tell us about your environment:**

* Puppeteer version:1.0.0
* Platform / OS version: win10 x64
* URLs (if applicable): 
* Node.js version:

**Comment by aslushnikov** [comment]
@LiCasey the base64-encoded image should work just fine.

**Comment by andy14312** [comment]
@aslushnikov isn't there any way to give an absolute image path in the template? should it always have to base-64 encoded?

**Comment by rajratnamaitry** [comment]
use image tag with base64 image in src
<img src="data:image/png;base64,..." width="100"/>

**use javascript to convert image url to base64**
function toDataUrl(url, callback) {
    var xhr = new XMLHttpRequest();
    xhr.onload = function() {
        var reader = new FileReader();
        reader.onloadend = function() {
            callback(reader.result);
        }
        reader.readAsDataURL(xhr.response);
    };
    xhr.open('GET', url);
    xhr.responseType = 'blob';
    xhr.send();
}
toDataUrl(imagepath, function(myBase64) {
    console.log(myBase64); // myBase64 is the base64 string
})

**Comment by mikalai-yankouski** [comment]
@aslushnikov, @andy14312
```
var fs = require('fs');
var path = require('path');
global.appRoot = path.resolve(__dirname);


function base64Encode(file) {
  return fs.readFileSync(file, {encoding: 'base64'});
}

function logo() {
  return '<img height="13" src="data:image/png;base64,' + base64Encode(appRoot + YOUR_FILE_PATH) + '"/>';
}

```

**Comment by milinfic** [comment]
It works if you convert img to base64

 return await fetch(url, { method: "GET" })
    .then(async (response) => {
      if (response.status === 200) {
        const imageBuffer = await response.buffer();
        const base64Image = imageBuffer.toString('base64');
        return 'data:image/png;base64,' + base64Image;
     }
});
