### ISSUE TITLE
[Feature Request] A way to know if there are any puppeteer browser instances running?

### ISSUE THREAD

**Issue by NagarjunPrasad1** [puppeteer/puppeteer#2444]
Is it possible to implement a feature where we can find out if any browsers launched from puppeteer are running? 
My Use case:
I have multiple puppeteer scripts and each script opened it's own browser instance. I wanted to make it so that each scripts runs in it's own page instead of running in it's own browser instance. To do that I wanted to implement a logic like so:
```
Browser.js:
if(puppeteer instance exists){
  return browser.wsEndpoint()
} else {
  browser = await puppeteer.launch();
  return browser.wsEndpoint();
}
```
Browser.js will be imported into each of my scripts and when it is called it returns the wsEndpoint of the already running instance of the browser and if a browser instance isn't running then it will create a new instance and return only the weEndpoint. I thought of using `puppeteer.connect(returned wsEndpoint)` to achieve this. But now I couldn't find anything that let's me find if there is an instance already running or any way to get its wsEndpoint.

**Comment by aslushnikov** [comment]
There's no reliable way to do that since browsers could be launched by many different means (e.g. via chrome-launcher or just manually).

You'll have to track the browsers you're interested in on your end, e.g. using `generic-pool` module (there are some resources regarding this on the bugtracer), or building something simple like this:

```js
// instance.js
const pptr = require('puppeteer');
let instance = null;
module.exports.getBrowserInstance = async function() {
  if (!instance)
    instance = await pptr.launch();
  return instance;
}
```

And later using it in all your scripts:

```js
const {getBrowserInstance} = require('./instance');

async function doWork() {
  // ....
  const browser = await getBrowserInstance(); // this will reuse single browser
  // ....
}
```

Hope this helps.
