### ISSUE TITLE
Linux-Chrome launch fails with Gtk-WARNING **: cannot open display:

### ISSUE THREAD

**Issue by SriGitHubSri** [puppeteer/puppeteer#2445]
Hi Team,

Trying to run **pa11y** program which uses **Puppeteer** as a dependency module

Have installed **linux-chrome 100002** and modified **Launcher.js in Puppeteer module** with
**let chromeExecutable = <Path to linux-chrome/chrome>**

When trying to run the **pa11y** program getting the following error

**Error: Failed to launch chrome!

(chrome:93006): Gtk-WARNING **: cannot open display:
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/bleshooting.md

    at onClose (/buildstore/TestScripts/node_modules/puppeteer/lib/Laun26:14)
    at ChildProcess.helper.addEventListener (/buildstore/TestScripts/nos/puppeteer/lib/Launcher.js:216:60)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_proces**

Could you please help in resolving this issue?

**Comment by aslushnikov** [comment]
It's hard to say for sure, but this looks like you're using incompatible chrome version. Pptr is guaranteed to work only with certain chrome versions; so please use a matching pptr/chrome combination.

We publish chrome versions in our releases: https://github.com/GoogleChrome/puppeteer/releases

![image](https://user-images.githubusercontent.com/746130/39317443-70885d64-4930-11e8-8849-ee4bbb25a06e.png)

**Comment by sojungko** [comment]
Getting the same error. I'm on `puppeteer` v.1.6.2. I let puppeteer to install Chromium for me. In my `./node_modules/puppeteer/.local_chrome` I see `linux-575458` and the number matches what's listed in `chromium_revision` in `puppeteer`'s `node_modules`.

**Comment by sojungko** [comment]
@SriGitHubSri Figured out what my issue was! I had to either add a `--headless` argument on the CLI or pass `headless: true` into the puppeteer options object when you `puppeteer.launch`!

**Comment by Nisthar** [comment]
@sojungko so it wont run in headful mode? why?

**Comment by pythme** [comment]
**check you browser setting.**

As follows
```
'headless': True,
'devtools': False, 
```
