### ISSUE TITLE
Return PDF to stdout

### ISSUE THREAD

**Issue by benjbdev** [puppeteer/puppeteer#2454]
Hello,

I'm on Debian in a Docker environnement.

node = v7.10.1
puppeteer = v1.3.0

I'm trying to read a stream then return the pdf to stdout with this command :

`echo "test text" | node rasterize.js pdf`

This is my rasterize.js file

````
const puppeteer = require('puppeteer');
const fs = require('fs');

let stdinBuffer = fs.readFileSync(0 /* STDIN_FILENO */, 'utf8');
let html = stdinBuffer.toString();

const args = process.argv;
const format = args[2];

(async () => {
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true,
        args: ["--no-sandbox"]
    });
    const page = await browser.newPage();

    // https://github.com/GoogleChrome/puppeteer/issues/728
    // await page.setContent(html);
    // await page.waitForNavigation({ waitUntil: 'networkidle0' });

    await page.goto('data:text/html,' + html, {waitUntil: 'networkidle0'});

    if (format == 'pdf') {
        await page.pdf({
            path: 1, // STDOUT_FILENO
            //path: '/var/www/web/test.pdf', // with a file it's working.
            format: 'A4',
            printBackground: true,
            margin: {top: '1cm', right: '1cm', bottom: '1cm', left: '1cm'}
        });
    } else {
        await page.screenshot({
            path: 1, // STDOUT_FILENO
            type: format,
            quality: 100,
        });
    }

    await browser.close();
})();
````

If i try to return the content in a PDF file everything is okay,
but if i set path:1 to return the pdf in stdout, i have this error 

````
(node:569) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ESPIPE: invalid seek, write
(node:569) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^Croot@462e64d4d418:/var/ww
````

the goal is to use a Symfony (php) bundle to process everything https://github.com/Padam87/RasterizeBundle and the author tells me it's working perfectly for him, so maybe it could be an issue with my environment or puppeteer ?

I can provide more informations if needed, thanks !

**Comment by robertlyall** [comment]
I've just had a read over [the code](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L762-L808) and it looks like if you don't provide a path option, it'll return a Buffer.

Perhaps you need to do something like this instead:

```js
const pdf = await page.pdf({
  format: 'A4',
  printBackground: true,
  margin: {top: '1cm', right: '1cm', bottom: '1cm', left: '1cm'}
});

process.stdout.write(pdf);
```

Also, if you wrap your call to `page.pdf` in a `try/catch` you should be able to get a more descriptive error message.

Hope that helps!

**Comment by benjbdev** [comment]
Wow.. it's working now..!! Thanks !
