### ISSUE TITLE
waitFor custom event feature request

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#2455]
There is no API at the moment to wait for a custom event in the node context, right?

Example: 

    await page.goto('gridwithimages.com', {waitUntil: 'grid-load'});
    await page.screenshot();

I only found [custom-event.js][1], which is quite verbose and doesn't `await` until the event is fired anyway.

[1]: https://github.com/GoogleChrome/puppeteer/blob/master/examples/custom-event.js

**Comment by aslushnikov** [comment]
@doplumi there's no such API for now because there seem to be too many similarly-useful scenarios that are too different. For example, one might want to wait on `console.timeStamp` events, someone might want to wait on a specific [CustomEvent] dispatched to a certain node.

I'd recommend using helpers for now that satisfy your particular user scenario. If at some point we converge on a certain best practice (e.g. using `console.timeStamp` to notify page lifecycle is appealing to me), we'll add the API.

Thanks.

**Comment by saeedkhan-github** [comment]
hi . i am writting a test in which i have to wait for user click on submit button.
first user have to fill form then click on submit button. 
kindly help me for waiting until the user click on submit button

**Comment by likethemammal** [comment]
This would be ideal for some of the browser apis, such as the Font Loading API to trigger events

**Comment by john-doherty** [comment]
I created a method to simplify this `await waitForEvent('app-ready', 10)`

```js
/**
 * Wait for the browser to fire an event (including custom events)
 * @param {string} eventName - Event name
 * @param {integer} seconds - number of seconds to wait.
 * @returns {Promise} resolves when event fires or timeout is reached
 */
async function waitForEvent(eventName, seconds) {

    seconds = seconds || 30;

    // use race to implement a timeout
    return Promise.race([

        // add event listener and wait for event to fire before returning
        page.evaluate(function(eventName) {
            return new Promise(function(resolve, reject) {
                document.addEventListener(eventName, function(e) {
                    resolve(); // resolves when the event fires
                });
            });
        }, eventName),

        // if the event does not fire within n seconds, exit
        page.waitFor(seconds * 1000)
    ]);
}
```

**Comment by vsemozhetbyt** [comment]
@john-doherty Maybe `once` option is worth adding to reduce memory:

```js
                document.addEventListener(eventName, function(e) {
                    resolve(); // resolves when the event fires
                }, { once: true });
```

And maybe it can be simplified a bit more as no resolved result is needed:

```js
                document.addEventListener(eventName, resolve, { once: true });
```

**Comment by joao-conde** [comment]
> 
> 
> I created a method to simplify this `await waitForEvent('app-ready', 10)`
> 
> ```js
> /**
>  * Wait for the browser to fire an event (including custom events)
>  * @param {string} eventName - Event name
>  * @param {integer} seconds - number of seconds to wait.
>  * @returns {Promise} resolves when event fires or timeout is reached
>  */
> async function waitForEvent(eventName, seconds) {
> 
>     seconds = seconds || 30;
> 
>     // use race to implement a timeout
>     return Promise.race([
>         page.evaluate(function(eventName) {
>             return new Promise(function(resolve, reject) {
>                 document.addEventListener(eventName, function(e) {
>                     resolve(); // resolves when the event fires
>                 });
>             });
>         }, eventName),
> 
>         page.waitFor(seconds * 1000)
>     ]);
> }
> ```

This is very useful, could this be made part of the Puppeteer API?

I refactored to this:

```js
async function waitForEvent(page, event, timeout = 5000) {
     return Promise.race([
         page.evaluate(
             event => new Promise(resolve => document.addEventListener(event, resolve, { once: true })),
             event
         ),
         page.waitForTimeout(timeout)
     ]);
}
```

**Comment by arminbashizade** [comment]
the proposed solutions here won't work in cases that you have to add an event listener, then take an action to trigger the event, then wait on the event.
e.g. let's say there are a few tabs with an indicator that is transitioned between the labels, such as the blue underline that is moved to the selected tab in [MUI tabs](https://mui.com/material-ui/react-tabs/#basic-tabs)
![image](https://github.com/puppeteer/puppeteer/assets/3442879/4c785e9e-d730-434e-8dc9-9c663c2f3a65)
assuming `waitForEvent` is updated to add the listener on a specific element, then neither of the cases below will work:
```ts
await waitForEvent(page, selectorForTabIndicator, 'transitionend'); // gets stuck here until times out
await page.click(tabLabelSelector);
```
```ts
await page.click(tabLabelSelector);
await waitForEvent(page, selectorForTabIndicator, 'transitionend'); // event listener might get added after the event is emitted
```

```ts
await Promise.all([
  page.click(tabLabelSelector),
  waitForEvent(page, selectorForTabIndicator, 'transitionend'); // better chances than previous case, but still event listener might get added after the event is emitted
]);
```

based on the response on the linked issue (https://github.com/prasanaworld/puppeteer-screen-recorder/issues/44), I've created this method, **but I wonder if there's a better way**. Issues I faced with other solutions that led me to this one:
- based [on docs](https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.page.evaluate.md#pageevaluate-method): "If the function passed to `page.evaluateHandle` returns a `Promise`, the function will wait for the promise to resolve and return its value." so trying to return a `Promise` from `page.evaluate` that calls resolve inside `addEventListener`'s listen function will result in the same issue as the first example above
- cannot pass a function from node context to browser context via `page.evaluate`, so it's not possible to create a `Promise` in node and pass its resolve function to `page.evaluate` to be called inside `addEventListener`'s listen function

one problem that I can see with this implementation is that `page.exposeFunction` might not have finished running before the event is triggered, but given that `setupPromise` and an action (such as click) has to finish before the event is triggered, I think the chances are slim to none.
```ts
/**
 * returns two `Promise`s, one of which will resolve the first time the requested `event` is dispatched on the `selector`
 * based on https://github.com/puppeteer/puppeteer/issues/2455
 * @example
 * wait for a tab transition to end
 * ```ts
 * const { setupPromise, eventPromise: waitForTabTransition } = setupWaitForEvent(page, '.MuiTabs-indicator', 'transitionend');
 * await setup;
 * await page.click('button.MuiTab-root#tab1');
 * await waitForTabTransition;
 * ```
 * @example
 * wait for a dialog to open, because the node matching the selector is added to the DOM milliseconds
 * before the event is dispatched, setting `config.onDocument` gives better results
 * ```ts
 * const { setupPromise, eventPromise: waitForBackdropTransition } = await setupWaitForEvent(
 *   page,
 *   '.MuiModal-backdrop',
 *   'transitionend',
 *   {
 *     onDocument: true
 *   });
 * await setupPromise;
 * await page.click(selectorForButtonThatOpensDialog);
 * await waitForBackdropTransition;
 * ```
 * @param page
 * @param selector decides where in the doc to listen for the event (does not support puppeteers P-selectors, e.g. ::-p-text(Some text))
 * @param event name of the event to listen for
 * @param config setting `config.onDocument` to true will add the listener on the document and look for selector on and under `event.target`
 * @returns an object with two `Promise`s, `setupPromise` must be resolved before completing an action that can trigger `event`, `eventPromise` will resolve the first time `event` is triggered or after `config.timeout` milliseconds
 */
export function setupWaitForEvent(page: Page, selector: string, event: string, config: { onDocument?: boolean, timeout?: number } = {}) {
  const fname = randomUUID();
  const { timeout = 5000 } = config;

  const eventPromise = new Promise((resolve) => {
    page.exposeFunction(fname,  (e) => {
      resolve(e);
    });
  });

  const setupPromise = page.evaluate(
    (selector, event, config, fname) => {
      const { onDocument = false } = config;
      if (onDocument) {
        const handleEvent = (e: Event) => {
          const target = e?.target as Element;
          if (window[fname] && (target?.matches(selector) || target?.querySelector(selector))) {
            window[fname]();
            delete window[fname];
            document.removeEventListener(event, handleEvent);
          }
        };
        document.addEventListener(event, handleEvent);
      }
      else {
        document.querySelector(selector)?.addEventListener(event,
          (e) => {
            if (window[fname]) {
              window[fname]();
              delete window[fname];
            }
          },
          { once: true }
        );
      }
    },
    selector, event, config, fname
  );

  return {
    setupPromise,
    eventPromise: Promise.race([new Promise(r => setTimeout(r, timeout)), eventPromise])
  };
}
```

**Comment by Kilowhisky** [comment]
> 
> I refactored to this:
> 
> ```js
> async function waitForEvent(page, event, timeout = 5000) {
>      return Promise.race([
>          page.evaluate(
>              event => new Promise(resolve => document.addEventListener(event, resolve, { once: true })),
>              event
>          ),
>          page.waitForTimeout(timeout)
>      ]);
> }
> ```

With `page.waitForFunction()` couldn't this be written as 
```js
async function waitForEvent(page: Page, event: string, timeout = 5000) {
    return page.waitForFunction(
        async event => {
            return new Promise(resolve => {
                document.addEventListener(event, resolve, { once: true })
            });
        },
        { timeout },
        event
    );
}
```
