### ISSUE TITLE
how to detect xdg-open event?

### ISSUE THREAD

**Issue by RuslanTT** [puppeteer/puppeteer#2457]
Good day, i`am trying to do some actions when page.on('load',...)  event is detected. But if i open page with xdg-open that event never detects. Is there option to detect and answer to xdg-open window?
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: ubuntu 16.04
* URLs (if applicable):
* Node.js version: v8.8.1

**What steps will reproduce the problem?**
headless: true with await page.setRequestInterception(true);
open page with such code "<script>window.location.replace('httk://google.com');</script>",
its not a typo "httk://google.com', when such redirect is presented, it tries xdg-open(in headless=false, or real browser). And i cant detect page.on('load',...) event.

**What is the expected result?**
i expect to get some event of xdg-open, or page.on('load',...)

**Comment by aslushnikov** [comment]
>  Is there option to detect and answer to xdg-open window?

@RuslanTT the xdg-open is the extension point for third-party apps to handle URL navigations. These are outside of WebPlatform, so this functionality is not exposed through pptr.

If you need this functionality for testing, the way to go would be to setup an environment with a custom xdg-open handler that will report requests to your testing framework.

Hope this helps.
