### ISSUE TITLE
Connection issues - crashes on Firebase Functions

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#246]
Trying to use puppeteer with [firebase functions](https://firebase.google.com/docs/functions/get-started) and running into issues. AFAICT, the issue seems to be connecting to the instance of chrome. The crash happens with the first call to a `browser` method.

The handler just logs the browser version:

```javascript
const functions = require('firebase-functions');
const {Browser} = require('puppeteer');

exports.getVersion = functions.https.onRequest(async (req, res) => {
  const browser = new Browser();
  const version = await browser.version(); // CRASH
  res.status(200).send(version);
  browser.close();
});
```

Unfortunately, debugging this stuff is pretty crappy. What I get back is:

```
{"error":{"code":500,"status":"INTERNAL","message":"function crashed","errors":["socket hang up"]}}
```
This one happens occasionally when I use `browser.stderr.pipe(process.stderr);` / `browser.stdout.pipe(process.stdout);`:
```
error: 
DevTools listening on ws://127.0.0.1:9229/devtools/browser/f179821d-7bda-4169-97aa-48bc78dd8d74
error: [0811/142640.945880:ERROR:devtools_http_handler.cc(244)] Error writing DevTools active port to file
```

Interesting observations:
- The code works when using`executablePath` to launch a local install of Chromium and Canary on my dev machine (`/Applications/Chromium.app/Contents/MacOS/Chromium` and `/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary`
- Works: running the functio with `node --inspect` doesn't cause the crash.

Any ideas, tips for debugging, or getting more information from Chrome?

**Comment by aslushnikov** [comment]
I copied your script, ran `npm i firebase-functions` and `npm i <puppeteer-path>`, and ran the script. It throws the `Cannot find module 'firebase-admin'` error, doesn't look like an expected outcome. 

How do i repro this?

**Comment by aslushnikov** [comment]
Speculating: it might be that you've updated the puppeteer repo but didn't run the `npm install`. 
Could you please try-catch the function body and see what kind of exception is thrown?

```js
const functions = require('firebase-functions');
const {Browser} = require('puppeteer');

exports.getVersion = functions.https.onRequest(async (req, res) => {
  try {
    const browser = new Browser();
    const version = await browser.version(); // CRASH
    res.status(200).send(version);
    browser.close();
  } catch (e) {
    console.error(e);
    res.status(500).send(e.message);
  }
});
```

**Comment by ebidel** [comment]
@aslushnikov tried that. It was still no help :( Unfortunately the firebase functions emulator doesn't hit the catch. We might be able to get more debugging info if we deploy to the production servers, but that requires that the puppeteer npm module is public. FB functions runs your project's `npm install` when you deploy.

To repro, download https://drive.google.com/open?id=0B05BKYSFJ-ZzSWpIYjk5bVVGUzQ and run:

- `npm install -g firebase-tools`
- `yarn`
- `yarn start`
- hit `http://localhost:5000/getVersion` (or whatever port it starts). Should print the headless version.

If you're on mac, you can also hit these to see that other versions of chrome work:
http://localhost:5000/fetchPage (uses puppeteer's bundled chromium)
http://localhost:5000/fetchPage?browser=canary (works: uses machine's install of canary)
http://localhost:5000/fetchPage?browser=chromium (works: uses /Applications/Chromium.app/Contents/MacOS/Chromium)

**Comment by ebidel** [comment]
After some extensive debugging, it looks like this an issue in the google cloud emulator and not puppeteer. Their [file watching code](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/893efc5b53c1cca9007e0813ca36959a41859ed0/src/supervisor/worker.js#L143-L155) causes the error. That code block also explains why `node --inspect` works.

https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/115 looks related.
