### ISSUE TITLE
Add option to page.goto() to retry on ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by melissachang** [puppeteer/puppeteer#2460]
I start servers and run Puppeteer tests at roughly the same time. When tests first attempt `page.goto()`, it fails with ERR_CONNECTION_REFUSED because server hasn't finished initializing. So I wrote [manual retries for `page.goto()`](https://github.com/DataBiosphere/data-explorer/blob/mc/e2e-circleci/ui/tests/e2e/test.js#L40).

It would be nice if there was an option to `page.goto()` to implement the retry logic itself. This would be the equivalent of hitting refresh in the browser, until page loads.

I would think this would be a common request, but it appears it's not. I'm interested to hear how people automate their deployment such that server initialization is guaranteed to be done before Puppeteer tests are run.

**Comment by benjamingr** [comment]
I don't think puppeteer needs to solve this general problem of retrying actions.

I recommend you use a library that does retries. 

Let's say you do the following which fails:

```js
await page.goto('http://returns-errors-sometimes.example.com');
```

Here is a simple `retry`, there are modules on npm that do this with exponential backoff or a maximal number of attempts:

```js
const retry = (fn) => fn().catch(retry.bind(fn));
```

Which would let you do the following instead which would retry `page.goto` until it succeeds:

```js
await retry(() => page.goto('http://returns-errors-sometimes.example.com'));
```

**Comment by melissachang** [comment]
Your minimal example isn't realistic because it doesn't sleep. But point taken, I'm sure there are npm packages that would let me do it in fewer lines of code.

There are two separates ideas.
1. Many users of puppeteer have a need to retry page.goto
1. Users of an API should implement retry themselves, vs the API doing it for them

I have no idea about 1.

Regarding 2, as a general software principle, if enough users need retry, I believe that implementing lower down in the stack (at API level) is better. Not everyone agrees with this.

**Edit:** I guess 2 is less relevant in this case. 2 is more for when a flaky error occurs. In this case, `page.goto()` is supposed to fail.

**Comment by curran** [comment]
Retying outside the Puppeteer API makes sense. Looks like not required as part of Puppeteer.

Here's the solution I'm using:

```
const retry = (fn, ms) => new Promise(resolve => { 
  fn()
    .then(resolve)
    .catch(() => {
      setTimeout(() => {
        console.log('retrying...');
        retry(fn, ms).then(resolve);
      }, ms);
    })
});
```

Here's the code that calls it (inspired by [UI testing with Puppeteer and Mocha](https://medium.com/@dpark/ui-testing-with-puppeteer-and-mocha-8a5c6feb3407)):

```js
it('should open page', async () => {
  browser = await puppeteer.launch({ headless: false });
  page = await browser.newPage();
  const response = await retry(() => page.goto('http://localhost:3000'), 1000);
  assert.equal(response.status(), 200);
});
```

This works well for waiting for the server to spin up. Just like I would do when manually testing. Refresh, refresh, refresh, boom!

**Comment by aslushnikov** [comment]
> It would be nice if there was an option to page.goto() to implement the retry logic itself. This would be the equivalent of hitting refresh in the browser, until page loads.

I don't think puppeteer should do any magic and run retries. Closing given there's no demand for this.

**Comment by endel** [comment]
Hey @benjamingr, do you mind sharing the NPM modules you've mentioned here?

> Here is a simple retry, there are modules on npm that do this with exponential backoff or a maximal number of attempts:

I've made a quick search on NPM and couldn't find them. Cheers!

**Comment by benjamingr** [comment]
@endel sure: https://www.npmjs.com/package/promise-retry for example.

It's essentially 

```js
const delay = util.promisify(setTimeout);
const retry = (fn, retryDelay = 100, numRetries = 3) => async (...args) => 
  for (let i = 0; i < numRetries; i++) {
    try {
      return await fn(...args); 
    } catch (e) {
      if (i === numRetries - 1) throw e;
      await delay(retryDelay);
      retryDelay = retryDelay * 2;
    }
  }
};
```

**Comment by Xample** [comment]
@curran nice snippet! for people trying to type it in TS:
```ts
// retry.ts
export const retry: <T>(fn: () => Promise<T>, ms: number) => Promise<T> = <T>(fn: () => Promise<T>, ms: number) => new Promise<T>((resolve) => {
    fn()
        .then(resolve)
        .catch(() => {
            setTimeout(() => {
                console.log('retrying...');
                retry(fn, ms).then(resolve);
            }, ms);
        });
});

```
Just because it was cumbersome to do it…

**Comment by DanielRuf** [comment]
It should be

```javascript
async (fn, retryDelay = 100, numRetries = 3) => {
  for (let i = 0; i < numRetries; i++) {
    try {
      return await fn()
    } catch (e) {
      if (i === numRetries - 1) throw e
      await delay(retryDelay)
      retryDelay = retryDelay * 2
    }
  }
}
```

**Comment by suntong** [comment]
Hi @DanielRuf, I don't know JS well enough to understand what improvement/advantages your code is better than the original one. Would you elaborate on that please? Thx.

**Comment by DanielRuf** [comment]
@suntong compared to which code snippet exactly? Mine uses pure async / await and is more readable.

**Comment by suntong** [comment]
Oh @DanielRuf, when you said _"It should be"_ I thought you were trying to improve on what benjamingr posted on Aug 31, 2018. I did a comparison between the two and noticed that the two pieces almost identical.
Since I have you @DanielRuf, If `fn()` needs arguments, how to change your code to make it work? thx

**Comment by DanielRuf** [comment]
You can simply pass them to fn like when you call it normally.

**Comment by 7aklhz** [comment]
Building on @curran  response, here is the solution with a retry logic 


```
let numRetry = 0
let maxRetry = 3
const retry = (fn) => new Promise((resolve, reject) => {
        fn()
            .then(resolve)
            .catch((error) => {
                numRetry++
                if (numRetry <= maxRetry) {
                    console.log('retrying (' + numRetry + ')');
                    retry(fn).then(resolve).catch(reject)
                } else {
                    reject(error)
                }

            })
    });
```

And 
`await retry(() => page.waitForSelector('.xxxxx')).catch(e => { throw e })`
