### ISSUE TITLE
Is there a way to query webSocketDebuggerUrl on browser window? 

### ISSUE THREAD

**Issue by KBPratap** [puppeteer/puppeteer#2461]
I want to use puppeteer for chromebook automation. 
Chromebook doesn't allow to launch multiple instances of browser and I need to connect to the existing instance of browser. 

Though Puppeteer.connect seems to be an option but I need to get the webSocketDebuggerUrl. Is there a way I can query for webSocketDebuggerUrl on browser?

Is there any other way to automate testing in chromebook?

**Comment by aslushnikov** [comment]
I don't have a ChromeOS device to play around, but here's some information I found on this:
- there's some discussion on this in this [google group](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/arQE-vrM2OA)
- telemetry [reads](https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/internal/backends/chrome/cros_browser_backend.py?rcl=dc970d3e1f7b3da5a2849de70ff253acdb70148f&l=35)  devtools active port from `/home/chronos/DevToolsActivePort`.

Let me know if you manage to make this work.

**Comment by KBPratap** [comment]
@aslushnikov 
Thanks for the input.
I was able to connect to the running instance of browser in chrome and rest of the automation was straightforward.
