### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by Astro36** [puppeteer/puppeteer#2462]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Ubuntu 16.04.3 LTS
* URLs (if applicable): https://github.com/Astro36/KoreanSchool/blob/master/lib/index.js#L238 (line:238)
* Node.js version: v9.6.0

I already install Ubuntu dependencies by below command.

`sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run `const browser = await puppeteer.launch();`
2. Error occured.

**What is the expected result?**

Launch the chrome.

**What happens instead?**

(node:9952) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/odroid/Programs/KoreanSchool-ScheduleBot/node_modules/korean-school/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: 1: /home/odroid/Programs/KoreanSchool-ScheduleBot/node_modules/korean-school/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: Syntax error: Unterminated quoted string

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/odroid/Programs/KoreanSchool-ScheduleBot/node_modules/korean-school/node_modules/puppeteer/lib/Launcher.js:255:14)
    at Interface.helper.addEventListener (/home/odroid/Programs/KoreanSchool-ScheduleBot/node_modules/korean-school/node_modules/puppeteer/lib/Launcher.js:244:50)
    at Interface.emit (events.js:130:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:130:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
(node:13165) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13165) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by KevinNovak** [comment]
+1 (Also having this issue)

Puppeteer version: 1.3.0
OS: Raspbian 9 (stretch)
```console
Error: Unhandled rejection. Error: Failed to launch chrome!
/home/pi/Documents/Code/Test/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: 1: /home/pi/Documents/Code/Test/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: Syntax error: Unterminated quoted string


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/pi/Documents/Code/Test/node_modules/puppeteer/lib/Launcher.js:255:14)
    at Interface.helper.addEventListener (/home/pi/Documents/Code/Test/node_modules/puppeteer/lib/Launcher.js:244:50)
    at Interface.emit (events.js:185:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**My interpretation**: seems like this specific build of chrome ("linux-549031"), somewhere down the line has an unterminated string.

**Comment by aslushnikov** [comment]
@Astro36 there’s some syntax error in the output provided. Can you run pptr’s chrome manually? Does it start?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aslushnikov** [comment]
@KevinNovak pptr doesn’t support ARM out of the box. You’ll have to compile chromium for arm on your own and point pptr to use it with `executablePath`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KevinNovak** [comment]
@aslushnikov Didn't realize that. I ended up doing what you mentioned with ```executablePath``` using the version of Chromium that comes with Raspbian. Thanks!

**Comment by deepak-mali** [comment]
Ran into same issue. I have Ubuntu 14.04.5 LTS server. Kindly help

**Comment by Kimeiga** [comment]
I'm also receiving this error when I try to run chrome without headless and without sandbox with the following command:

    const browser = await puppeteer.launch({
         headless: false,
         args: ['--no-sandbox', '--disable-setuid-sandbox']
      });

**Comment by sagardere** [comment]
I also get the same error But it solves in my case.

```
const browser = await puppeteer.launch({
    headless: true,
   executablePath:'/home/sagar/workplace/scraping-demo/node_modules/puppeteer/.local-chromium/linux-599821/chrome-linux/chrome',
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
```
When you are using **headless: true** options then also use the option **executablePath** give the accurate path of your chrome file in node_modules folder, like above. In my case I am putting whole path of my system, where my chrome file.

**Comment by mkurtipek** [comment]
> I also get the same issue But it solves in my case.
> 
> ```
> const browser = await puppeteer.launch({
>     headless: true,
>    executablePath:'/home/sagar/workplace/scraping-demo/node_modules/puppeteer/.local-chromium/linux-599821/chrome-linux/chrome',
>     args: ['--no-sandbox', '--disable-setuid-sandbox'],
>   });
> ```
> When you are using **headless: true** options then also use the option **executablePath** give the accurate path of your chrome file in node_modules folder, like above. In my case i am putting whole path of my system, where my chrome file.

Also worked for me!

**Comment by salemalem** [comment]
> 
> 
> > I also get the same issue But it solves in my case.
> > ```
> > const browser = await puppeteer.launch({
> >     headless: true,
> >    executablePath:'/home/sagar/workplace/scraping-demo/node_modules/puppeteer/.local-chromium/linux-599821/chrome-linux/chrome',
> >     args: ['--no-sandbox', '--disable-setuid-sandbox'],
> >   });
> > ```
> > 
> > 
> > When you are using **headless: true** options then also use the option **executablePath** give the accurate path of your chrome file in node_modules folder, like above. In my case i am putting whole path of my system, where my chrome file.
> 
> Also worked for me!

I love you man!

**Comment by joey2031** [comment]
Hi im having the same issue I tried everything and nothings working, im so confused. can someone please help. I ran npm install pupteer and put this in my main file bot.js 
const browser = puppeteer.launch({
    headless: true,
    executablePath: 'node_modules/puppeteer/.local-chromium/win64-686378/chrome-win/chrome',
    'args': ['--no-sandbox', '--disable-setuid-sandbox']
});
its still not working when I put it on Heroku, what can I do to fix it? Ps. If you need to see more code just let me know! Thanks!

**Comment by QasimWani** [comment]
> Hi im having the same issue I tried everything and nothings working, im so confused. can someone please help. I ran npm install pupteer and put this in my main file bot.js
> const browser = puppeteer.launch({
> headless: true,
> executablePath: 'node_modules/puppeteer/.local-chromium/win64-686378/chrome-win/chrome',
> 'args': ['--no-sandbox', '--disable-setuid-sandbox']
> });
> its still not working when I put it on Heroku, what can I do to fix it? Ps. If you need to see more code just let me know! Thanks!

Did you figure it out? I'm having the same issue. Thanks

**Comment by joey2031** [comment]
> > Hi im having the same issue I tried everything and nothings working, im so confused. can someone please help. I ran npm install pupteer and put this in my main file bot.js
> > const browser = puppeteer.launch({
> > headless: true,
> > executablePath: 'node_modules/puppeteer/.local-chromium/win64-686378/chrome-win/chrome',
> > 'args': ['--no-sandbox', '--disable-setuid-sandbox']
> > });
> > its still not working when I put it on Heroku, what can I do to fix it? Ps. If you need to see more code just let me know! Thanks!
> 
> Did you figure it out? I'm having the same issue. Thanks
Hey sorry for the late reply, ive been busy lately. No unfortunately I was never able to fix it.  I tried to run these commands:
heroku plugins:install heroku-repo
$ heroku repo:purge_cache -a appname
$ git commit --allow-empty -m "Purge cache"
$ git push heroku master
with no luck,
Then I tried this
$ heroku plugins:install https://github.com/heroku/heroku-repo.git
$ heroku repo:purge_cache -a appname
and still didn't work. 
TBH  I've just left this alone for a wile and started working on other things, however id love to figure this out. If you have any questions, you can DM me on Instagram @ joey2031 hopefully we can fix this one day. Good luck!

**Comment by cj13579** [comment]
> I'm also receiving this error when I try to run chrome without headless and without sandbox with the following command:
> 
> ```
> const browser = await puppeteer.launch({
>      headless: false,
>      args: ['--no-sandbox', '--disable-setuid-sandbox']
>   });
> ```

Not sure why but this didn't work for me. I am running `Ubuntu 18.04.3 LTS` on WSL2. I was however able to get it to work but adding the puppeteer version of Chrome to my `PATH` environment variable.

**Comment by QasimWani** [comment]
Yeah same issue. Works perfectly on local environment. but fails to deploy properly on production Ubuntu (Heroku). I followed the docs on how to launch to heroku from pupetteer but that's still not working. I think it has something to do with that interactive_test.exe file which I've pushed via Git LFS. but somehow all the contents within node_modules/pupetteer aren't being pushed properly from my local env.
lmk if you find a fix.
Cheers.

**Comment by joey2031** [comment]
UPDATE: I was never able to fix it, im just going to try and use jimp, can someone help me center text on the image?

**Comment by eridgway90** [comment]
In my situation, this error seemed to be occurring because the chrome file (located at nodejs/bin/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome) did not have the proper executable permissions set on it.  Once I made it executable, the error went away.

**Comment by joey2031** [comment]
How did you set the executable permissions? Also i'm on windows does that make a difference? This is my folder, am I looking at the right file? UPDATE: I am using git bash (a linux like terminal) and was able to acess the file, however whaich permissions should I set: chmod ??? Thank you so much! 
![image](https://user-images.githubusercontent.com/36198917/73109100-387c2080-3ed0-11ea-9913-0dc00aeb8ea8.png)

![image](https://user-images.githubusercontent.com/36198917/73108611-bdfed100-3ece-11ea-9aab-714b2830b27f.png)

**Comment by eridgway90** [comment]
Sorry, I only saw this error when working with the Linux distribution... I didn't have any trouble with the Windows distribution.  Windows doesn't use POSIX permissions, so using a Bash terminal on Windows to chmod the executable probably won't change anything.

The original error message for this thread is pretty generic and may have nothing to do with executable permissions in your situation. :/

**Comment by Skonce** [comment]
joey2031  try to launch the chrome.exe like a standalone application once before using it in a script.

**Comment by cfgs** [comment]
If you are running an ARM processor, e.g. Raspberry PI, as stated in the begning of this thread I solved the issue with the following:

Install Chromium by running:
`sudo apt install chromium-browser chromium-codecs-ffmpeg`

It usually installes Chromium in /usr/bin/ -folder. So then we change the executablePath to the below:
```
  const browser = await puppeteer.launch({
          headless: true,
          executablePath: '/usr/bin/chromium-browser',
          args: ['--no-sandbox', '--disable-setuid-sandbox']
  });

```
