### ISSUE TITLE
Do not kill Chrome with `kill -9`

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#2463]
(Reported [here](https://puppeteer.slack.com/archives/C8XEP1718/p1524815460000457) on our slack channel)

Since we terminate browser with `kill -9` in an attempt to exit as fast as possible, `browser.close()` causes puppeteer `child_process` to exit with non-zero code.

This has unfortunate consequences on AWS Lambda.
Quoting @alixaxel:

> On Lambda, it creates core dumps which if the function is kept warm, will eventually prevent it from starting due to no disk space (only 500MB on `/tmp`).

We should:
- enhance protocol's [`Browser.close()`](https://vanilla.aslushnikov.com/#Browser.close) to (optionally) ignore beforeunload handlers
- use `browser.close()` exclusively instead of `kill -9`.

**Comment by AndreaAdvanon** [comment]
Any plan for this?

**Comment by aslushnikov** [comment]
IIRC the `browser.close` now handles beforeunload handlers just fine. We should add some tests to validate that and than either:
- switch to closing browser exclusively over the protocol
- introduce a new `force` option to `browser.close()` that'll fast-kill browser process.
