### ISSUE TITLE
Selector click coordinates mismatch between browser and puppeter

### ISSUE THREAD

**Issue by roykolak** [puppeteer/puppeteer#2465]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: MacOS 
* URLs (if applicable):
* Node.js version: 8.6.0

I'm trying to write some acceptance testing for an PWA (service workers, web components, etc...) and My spec is failing about 1 in 5 times. 
```js
await page.goto('localhost:5000/settings?disable-sw-cache', {
  waitUntil: 'networkidle2'
});

// doesn't seem to help w/ stopping flakiness
await page.waitFor(2000); 

page.click("[data-puppeteer='reload-configuration-link']");
await page.waitForSelector('.mdc-snackbar.mdc-snackbar--active');

const message = await page.evaluate(
  selector => document.querySelector(selector).textContent,
  '.mdc-snackbar.mdc-snackbar--active'
);

expect(message).to.contain('Successfully reloaded device configuration');
```

The problem is that when `page.click` is fired, 1  in 5 times the wrong element is clicked. I debugged Puppeter and found a mismatch between the browser's `[x, y]` click coordinates and puppeteer's `[x, y]` click coordinates. For the record, Puppeteer is logging the correct coordinates. 

<img width="914" alt="screen shot 2018-04-27 at 3 44 45 pm" src="https://user-images.githubusercontent.com/9306/39384684-50a15376-4a33-11e8-94b2-8b0266d99b1d.png">

Any insights into why this is happen? I'm stumped.

**Comment by roykolak** [comment]
Well... I figured out what the problem was, but I don't have a clue as to why it would cause the behavior I documented above. I'm configuring my viewpoint to be a mobile device...

```js
page.setViewport({
  width: 411,
  height: 731,
  deviceScaleFactor: 2.6,
  isMobile: true,
  hasTouch: true,
  isLandscape: false
});
```

...I checked all these options individually and removing `isMobile` stopped the flaky behavior. Something fishy is going on w/ that setting...

**Comment by aslushnikov** [comment]
@roykolak This could be related to the recent flakiness we discovered with devtools protocol method for viewport emulation. There's an upstream patch that should fix this as it lands: https://chromium-review.googlesource.com/c/chromium/src/+/1011121

**Comment by aslushnikov** [comment]
@roykolak do you have any snippet I'll be able to run locally to reproduce your problem and validate the fix?

**Comment by roykolak** [comment]
this snippet is actually failing 100% percent of the time when `isMobile` is set to `true`...

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset=utf-8 />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#00838f">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <button>test</button>
    <div class="result"></div>
    <script>
      document.querySelector('button').addEventListener('click', ev => {
        document.querySelector('.result').textContent = 'worked';
        document.querySelector('.result').classList.add('updated');
      });
    </script>
  </body>
</html>
```

```js
var expect = require('chai').expect;
const puppeteer = require('puppeteer');

describe('isMobile testcase', function() {
  let browser;
  let page;

  let mobileConfig = {
    width: 411,
    height: 731,
    deviceScaleFactor: 2.6,
    hasTouch: true,
    isMobile: true,
    isLandscape: false
  };

  before(async () => {
    browser = await puppeteer.launch({
      headless: false,
      args: [`--window-size=${mobileConfig.width},${mobileConfig.height}`]
    });

    page = (await browser.pages())[0];
    page.setViewport(mobileConfig);
  });

  after(async () => {
    await browser.close();
  });

  it('works.. sometimes', async () => {
    await page.goto(`localhost:5000`, {
      waitUntil: 'networkidle2'
    });

    page.click('button');
    await page.waitForSelector('.result.updated');

    const message = await page.evaluate(
      selector => document.querySelector(selector).textContent,
      '.result.updated'
    );

    expect(message).to.contain('worked');
  });
});
```

**Comment by lihuihui-bj** [comment]
i got the same problem. And it seems the coordinates always be Integer, NOT float. Like (x:271, y:300) while mouse.click(271.23234, 300.34)
