### ISSUE TITLE
Puppeteer and ServiceWorkers offline mode

### ISSUE THREAD

**Issue by sashuk** [puppeteer/puppeteer#2469]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: CentOS 7 x64
* URLs (if applicable): -
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Initialise empty project with puppeteer
2. Create test file with following content

```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox']});
  const page = await browser.newPage();
  page.on('console', msg => console.log('PAGE LOG:', msg.text()));
  await page.goto('https://googlechrome.github.io/samples/service-worker/custom-offline-page/', { waitUntil: 'networkidle0' });
  console.log('Setting app offline');
  await page.setOfflineMode(true);
  await page.waitFor(1*2000);
  await page.reload();
  await page.waitFor(1*2000);
  await page.screenshot({path: 'test.png'});
});
```

3. Check the resulting screenshot, the page was reloaded but the ***offline mode was not applied***.

**What is the expected result?**

The resulting screenshot will contain offline page as in classic example https://googlechrome.github.io/samples/service-worker/custom-offline-page/

**What happens instead?**

Seems like the offline mode is not applied and the page is loaded regularly.

StackOverflow question for reference: [Service worker installation in Headless Chrome (via puppeteer)
](https://stackoverflow.com/questions/50073334/service-worker-installation-in-headless-chrome-via-puppeteer)

**Comment by ebidel** [comment]
Yea this is weird. I'd expect this example to work as you've outlined. 

The main page gets cached offline (expected) but it appears the SW isn't intercepting the network requests, and therefore, not serving the fallback content.

Slightly modified repro.

```js
const puppeteer = require('puppeteer');

const url = 'https://googlechrome.github.io/samples/service-worker/custom-offline-page/';

(async() => {
const browser = await puppeteer.launch({
  headless: false,
});

const page = await browser.newPage();
page.on('console', msg => console.log('PAGE LOG:', msg.text()));
await page.goto(url, {waitUntil: 'networkidle0'});
await page.evaluate('navigator.serviceWorker.ready');

console.log('Going offline');
await page.setOfflineMode(true);

 // Does === true for the main page but the fallback content isn't being served.
page.on('response', r => console.log(r.fromServiceWorker()));

await page.reload({waitUntil: 'networkidle0'});

// await browser.close();
})();
```

**Comment by ebidel** [comment]
cc @aslushnikov

**Comment by sashuk** [comment]
@ebidel The following code also does not work (actually it is almost the same as https://github.com/GoogleChrome/puppeteer/commit/a02347e3ef0b9cd4eac4f6e2e6c7fd42d089717a):

```
await page._client.send('Network.enable');
await page._client.on('Network.requestWillBeSent', event => {
    console.log('Network.requestWillBeSent', event.requestId, event.request.url);
});
await page._client.on('Network.loadingFinished', event => {
    console.log('Network.loadingFinished', event.requestId);
});

await page._client.send('Network.emulateNetworkConditions', {
    offline: true,
    latency: 100,
    downloadThroughput: 0,
    uploadThroughput: 0
});

await page.evaluate(`$.getJSON('https://jsonplaceholder.typicode.com/posts/1', function() {
    console.log("success");
}).done(function() {
    console.log("second success" );
}).fail(function() {
    console.log("error");
}).always(function() {
    console.log("complete");
});`);
```

Seems like the problem is not with the Service workers, but with the **DevTools Network interaction** - the Network is not reacting to commands through the `puppeteer` or raw DevTools requests (so, Service workers keep working regularly as the Network is still online). I've tried the default `puppeteer` Chrome installation and the custom Chrome 66 installation, still no luck.

**Comment by mdiblasio** [comment]
Is there any update on how to run offline tests that also disable the network for service workers?

**Comment by martinschierle** [comment]
Also interested on an update on this. There needs to be a good way to QA service workers for offline mode.

**Comment by patrickhulce** [comment]
Service workers are their own target (see https://github.com/ChromeDevTools/devtools-protocol/issues/102), so something like the below *should* work (but it doesn't see below).

```js
;(async () => {
  const puppeteer = require('puppeteer')
  const browser = await puppeteer.launch({headless: false})

  const page = await browser.newPage()
  await page.goto('https://googlechrome.github.io/samples/service-worker/custom-offline-page/', {
    waitUntil: 'networkidle0',
  })
  await page.evaluate('navigator.serviceWorker.ready')

  console.log('Going offline')
  await page.setOfflineMode(true)
  const targets = await browser.targets()
  console.log(targets.map((t) => [t.url(), t.type()]))
  const serviceWorker = targets.find((t) => t.type() === 'service_worker')
  const serviceWorkerConnection = await serviceWorker.createCDPSession()
  await serviceWorkerConnection.send('Network.enable')
  await serviceWorkerConnection.send('Network.emulateNetworkConditions', {
    offline: true,
    latency: 0,
    downloadThroughput: 0,
    uploadThroughput: 0,
  })

  await page.reload({waitUntil: 'networkidle0'})
  await browser.close()
})()
```

What's weird is that the `Network.emulateNetworkConditions` on the SW target fails with `Error: Protocol error (Network.emulateNetworkConditions): Not supported`.  In fact DevTools itself fails with this error now too. Seems like a Chromium bug.

![image](https://user-images.githubusercontent.com/2301202/80717277-599b7100-8abe-11ea-81b7-2a457663b38d.png)

**Comment by martinschierle** [comment]
Ha, that makes a lot of sense - we'll try that! Would probably still be good to have an easier high-level API for that though :-) Thanks a lot Patrick!

**Comment by mathiasbynens** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1068544 for the Chrome bug.

**Comment by patrickhulce** [comment]
Just to update folks on this thread, the script I posted *does* actually work with latest puppeteer even though Chromium is throwing. You'll just need to catch the command and trust it works :) 

```js
;(async () => {
  // ... same as example above

  await serviceWorkerConnection.send('Network.emulateNetworkConditions', {
    offline: true,
    latency: 0,
    downloadThroughput: 0,
    uploadThroughput: 0,
  }).catch(() => {}) // <-- this catch is new

  // ... same as example above
})()
```

**Comment by mathiasbynens** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/2199476 will remove the need for the `catch` eventually.

**Comment by martinschierle** [comment]
Amazing, thanks! Now Grygorii's and my dream can come true, to scan the web for the best offline page ever built :-D

**Comment by mathiasbynens** [comment]
Closing this since it's now resolved. Thanks everyone!

**Comment by RyanSchw** [comment]
Other types of web workers also fall under this same issue. Above code doesn't work since the other types of web workers are of type `other`.
Here's the console output from @patrickhulce 's fix:
```
[
  [ 'about:blank', 'page' ],
  [ '', 'browser' ],
  [ 'http://localhost:8080/', 'page' ],
  [ 'http://localhost:8080/service-worker.js', 'service_worker' ],
  [ 'http://localhost:8080/worker.js', 'other' ]
]
```
and here's the code that would get the service worker and [`Worker`](https://developer.mozilla.org/en-US/docs/Web/API/Worker) working
```js
const workers = targets.filter((t) => t.type() === 'service_worker' || t.type() === 'other');
for (const worker of workers) {
  const workerConnection = await worker.createCDPSession();
  await workerConnection.send('Network.enable');
  await workerConnection.send('Network.emulateNetworkConditions', {
    offline: true,
    latency: 0,
    downloadThroughput: 0,
    uploadThroughput: 0,
  }).catch(() => {});
}
```
Notice how I put the `catch` back in, as https://chromium-review.googlesource.com/c/chromium/src/+/2199476 did not remove the need for `catch` for the `other` type. Same error, `Protocol error (Network.emulateNetworkConditions): Not supported`.
