### ISSUE TITLE
is it possible to make the devtool status off when using Puppeteer?

### ISSUE THREAD

**Issue by zackijack** [puppeteer/puppeteer#2471]
is it possible to make the devtool status off when using Puppeteer?
because there are some websites that protect their pages from being inspected using devtool, so it can not be accessed using Puppeteer.

I opened this url https://jsbin.com/cecuzeb/edit?js,output to check devtool status

```javascript
  const browser = await puppeteer.launch({
    headless: false,
    devtools: false,
  });
  const page = await browser.newPage();
  await page.goto('https://jsbin.com/cecuzeb/edit?js,output');
```

is there any way to make its status off?

**Comment by aslushnikov** [comment]
please, ask at https://github.com/zswang/jdetects
