### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED with --proxy-server

### ISSUE THREAD

**Issue by Swiffers** [puppeteer/puppeteer#2472]
### Steps to reproduce

**The environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Ubuntu 16.04.4 LTS
* Node.js version: 8.11.1

**This code will reproduce the problem**

```
const browser = await puppeteer.launch({args:[ '--proxy-server=https://MyWorkingProxyIP:Port',], ignoreHTTPSErrors:true, headless:true});
const page = await browser.newPage();
await page.goto('https://example.com');
```

**Error:**

```
(node:13350) UnhandledPromiseRejectionWarning: Error: net::ERR_PROXY_CONNECTION_FAILED at https://example.com/
    at navigate (/home/ubuntu/sample/node_modules/puppeteer/lib/Page.js:523:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Details:**

1. No proxy are working using puppeteer with `--proxy-server`
2. But the proxy are working using `curl -x https://MyWorkingProxyIP:Port https://example.com`

**Comment by runewizard** [comment]
Had similar problem today.
Have you tried setting proxy like this '--proxy-server=https=MyWorkingProxyIP:Port' according to docs https://www.chromium.org/developers/design-documents/network-settings ?

**Comment by aslushnikov** [comment]
That's not enough information to figure out what's going on. Overall looks like an environemtn issue or an issue with the proxy.

**Comment by cnscorpions** [comment]
@runewizard thank you for saving my several days' work. 😂
