### ISSUE TITLE
Enable timeout to wait for commands

### ISSUE THREAD

**Issue by regevbr** [puppeteer/puppeteer#2473]
Im using a single instance of chromium and run on it lots of tests over time and concurrently using incognito tabs. After sometime, the calls to the web socket starts to hang and there is no way of knowing that, causing my flow to get stuck without a way out.
There is a need to implement a timeout mechanism for the requests as they happen in an async matter.
My suggestion would be to add In the Connection class a timeout after performing the send, which will reject the promise after the timeout...
Currently my solution is to perform a regular web socket new connection to chromium to make sure it is still responsive but that doesn't help if the tab itself gets stuck...

**Comment by aslushnikov** [comment]
@regevbr can you build a minimalistic example so that I can see the behavior for myself? It could be we have a nasty bug in the devtools protocol transport somewhere in chromium.

**Comment by regevbr** [comment]
@aslushnikov The issue seems to come from the chromium side and not from this library... How do you suggest handling non responsive tabs?
The issue only happens after a very long run in our very stressed production environment and as such it will be (in my opinion) very hard to reproduce

**Comment by aslushnikov** [comment]
@regevbr there are a bunch of folks running with high load, maybe they can shed some light onto this. +cc @alixaxel @joelgriffith @tnolet 

> The issue only happens after a very long run in our very stressed production environment and as such it will be (in my opinion) very hard to reproduce

Could it be that OS is very short on resources and you're not patient enough for it to give some CPU cycles to the tab?

**Comment by regevbr** [comment]
@aslushnikov I have many cpus and running a single instance of node and a single instance of chromium with at most 20 tabs open at a time but the tabs are being closed and opened very frequently while resuing the running chromium instance.
I forgot to mention 1 important thing - I'm using the "incognito" mode in the way I described here - [puppeteerIncognito.js](https://gist.github.com/regevbr/d78aee687b03d6eefde8f08c3746786c) for every tab I use.
It seems that the process was stuck in one of the commands used to create the session/target

**Comment by aslushnikov** [comment]
@regevbr that's an important details. There's been a recent fix to the browser contexts in headless: https://chromium-review.googlesource.com/c/chromium/src/+/1025402

Let us roll it in. After that, you'll be able to try it out and see if it accidentally resolves your issue.

**Comment by regevbr** [comment]
K sounds good! When can we expect the incognito support in puppeteer?

**Comment by aslushnikov** [comment]
The upstream implementation (https://crbug.com/836272) is mostly done, but there are still a few patches to be landed. Since they're not approved yet, there's no good ETA. Feel free to subscribe to #85 to get updates.

**Comment by aslushnikov** [comment]
@regevbr can you please update to v1.4.0 and report back if the issue is resolved?

**Comment by regevbr** [comment]
Hi,

We are currently facing some issues and I will not be able to test it out in the coming weeks but I will get back to you when I can

**Comment by aslushnikov** [comment]
Thanks for responding. I'll speculatively close this; feel free to write back when you'll have time.
