### ISSUE TITLE
requestfinished/requestfailed/response event isn't fired if XHR is in a Worker thread

### ISSUE THREAD

**Issue by takashiro** [puppeteer/puppeteer#2474]
### Steps to reproduce
1. Turn on request interception.
2. Create an XML HTTP Request in a Worker thread.
3. Attach event handlers to requestfailed / requestfinished / response event.
4. No event handler is called even after the request ends.

* Puppeteer version: 1.3.0
* Platform / OS version: Windows 10 Pro (x64)
* URLs (if applicable): http://test.takashiro.me/worker.html
* Node.js version: 8.11.1

**What steps will reproduce the problem?**
Here is an example.

These 3 requests are listed as below.
1. Normal request (200).
2. Aborted request (canceled).
3. Not Found (404).

The requests are made both outside and in a Worker thread.

```

const pageUrl = 'http://test.takashiro.me/worker.html';

const puppeteer = require('puppeteer');

console.log('Launch Chromium');
puppeteer
	.launch()
	.then(async browser => {
		console.log('Open a new tab.');
		let page = await browser.newPage();

		await page.setRequestInterception(true);

		page.on('request', request => {
			console.log('Request: ' + request.url());
			request.continue();
		});

		page.on('response', response => {
			let request = response.request();
			console.log('Response: ' + request.url());
		});

		page.on('requestfailed', request => {
			let failure = request.failure();
			console.log('Request Failed: ' + request.url() + ' Error: ' + failure.errorText);
		});

		page.on('requestfinished', request => {
			console.log('Request Finished: ' + request.url());
		});

		console.log('Go to test site.');
		await page.goto(pageUrl);
	});

```

**What is the expected result?**
> Launch Chromium
> Open a new tab.
> Go to test site.
> Request: http://test.takashiro.me/worker.html
> Response: http://test.takashiro.me/worker.html
> Request Finished: http://test.takashiro.me/worker.html
> Request: http://test.takashiro.me/worker.js
> Response: http://test.takashiro.me/worker.js
> Request: http://test.takashiro.me/test.json?abort=false
> Request: http://test.takashiro.me/test.json?abort=true
> Request: http://test.takashiro.me/404.json
> Request: http://test.takashiro.me/worker.js
> Request Finished: http://test.takashiro.me/worker.js
> Request Failed: http://test.takashiro.me/test.json?abort=true Error: net::ERR_ABORTED
> Request Failed: http://test.takashiro.me/404.json Error: net::ERR_ABORTED
> Response: http://test.takashiro.me/test.json?abort=false
> Response: http://test.takashiro.me/worker.js
> Request Finished: http://test.takashiro.me/worker.js
> Request Finished: http://test.takashiro.me/test.json?abort=false
> Request: http://test.takashiro.me/test.json?abort=false
> Request: http://test.takashiro.me/test.json?abort=true
> Request: http://test.takashiro.me/404.json
> Request Failed: http://test.takashiro.me/test.json?abort=true Error: net::ERR_ABORTED
> Request Failed: http://test.takashiro.me/404.json Error: net::ERR_ABORTED
> Request Finished: http://test.takashiro.me/test.json?abort=false

**What happens instead?**
The output is as follows. The logs ended with request event, without any following requestfailed / requestfinished / response event.

> Launch Chromium
> Open a new tab.
> Go to test site.
> Request: http://test.takashiro.me/worker.html
> Response: http://test.takashiro.me/worker.html
> Request Finished: http://test.takashiro.me/worker.html
> Request: http://test.takashiro.me/worker.js
> Response: http://test.takashiro.me/worker.js
> Request: http://test.takashiro.me/test.json?abort=false
> Request: http://test.takashiro.me/test.json?abort=true
> Request: http://test.takashiro.me/404.json
> Request: http://test.takashiro.me/worker.js
> Request Finished: http://test.takashiro.me/worker.js
> Request Failed: http://test.takashiro.me/test.json?abort=true Error: net::ERR_ABORTED
> Request Failed: http://test.takashiro.me/404.json Error: net::ERR_ABORTED
> Response: http://test.takashiro.me/test.json?abort=false
> Response: http://test.takashiro.me/worker.js
> Request Finished: http://test.takashiro.me/worker.js
> Request Finished: http://test.takashiro.me/test.json?abort=false
> Request: http://test.takashiro.me/test.json?abort=false
> Request: http://test.takashiro.me/test.json?abort=true
> Request: http://test.takashiro.me/404.json

**Comment by aslushnikov** [comment]
That's right. Workers should be exposed separately, please follow #2350 for the updates.
