### ISSUE TITLE
[PDF] Using different margin bottom on first page doesn't work 

### ISSUE THREAD

**Issue by spiritix** [puppeteer/puppeteer#2480]
### Steps to reproduce

**Environment:**
* Puppeteer version: 1.3.0
* Platform / OS version: Ubuntu 14.04
* Node.js version: 7.6.0

**Code:**
```
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://github.com/GoogleChrome/puppeteer', {waitUntil: 'networkidle2'});
await page.addStyleTag({
    content: '@page:first {margin-top:0px; margin-right:0px; margin-bottom:0px; margin-left:0px;}'
});
await page.pdf({
    path: 'test.pdf',
    format: 'A4',
    displayHeaderFooter: true,
    headerTemplate: '<div style="font-size:16px;width:100%;text-align:center;">HEADER</div>',
    footerTemplate: '<div style="font-size:16px;width:100%;text-align:center;">FOOTER</div>',
    margin: {top: '50px', right: '10px', bottom: '50px', left: '10px', }}
);
await browser.close();
```

**Expected result:**
The first page should have no margins (and therefore hide the header and footer), while all following pages should have the specified margin and display the header and footer.

**Actual result:**
The header is properly displayed on all pages except the first one. The footer, however, is only displayed on the last page. It seems that the margin bottom isn't applied properly.

**Comment by aslushnikov** [comment]
@spiritix does the same occur if you do "save as pdf" through headful chrome? Most likely, this is a chromium issue; please report upstream to the `https://crbug.com/new`.

**Comment by spiritix** [comment]
@aslushnikov I am not sure how to test this in headful mode since `page.pdf()` is only available in headless mode.

`Protocol error (Page.printToPDF): PrintToPDF is not implemented`

**Comment by hakimio** [comment]
@spiritix 
Try the following:
Print -> Destination: Save as PDF -> Margins: Custom

**Comment by spiritix** [comment]
@hakimio This does 'work', however, the CSS seems to have no effect at all, probably because manually set margins in Chromium PDF export aren't the same as CSS margins.

**Comment by hakimio** [comment]
@spiritix Maybe then you should add the margins for all the pages the same way? If you are using CSS for the first, use CSS for the rest. Honestly, I don't think those two options should be linked in any way.

**Comment by spiritix** [comment]
@hakimio This is what I tried first. It results in exactly the same (wrong) PDF. Therefore I assume, that the `margin` option of the `page.pdf()` internally produces CSS as well.

However, I just discovered something really interesting. Have a look at the following two PDF files:

No footer/header: https://drive.google.com/open?id=12jshVH0_hz3S-JK-wCqxxrs3h0IuDDDu
With footer/header: https://drive.google.com/open?id=1IcF2PQ1MC5jOr3WsVtj1KCQKt57Qriqt

As you can see, as soon as I set the `displayHeaderFooter` option to `true`, the `margin-bottom` gets ignored. This happens with both, using regular CSS as well as using the `margin` option of the `page.pdf()` method.

**Comment by garygreen** [comment]
Have you tried the [`preferCSSPageSize`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) ? This allows you to specify the margin's for page in the CSS and it will take priority:

```css
@page {
  size: A4 portait;
  margin: 0;
}
```

**Comment by spiritix** [comment]
@garygreen Has no effect, unfortunately. The result is exactly the same as with the initial configuration.

**Comment by destan** [comment]
I believe it's related to this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=355116

**Comment by Jan-Timon** [comment]
I also experience this bug (tried it with puppeteer version 1.14.0 and 1.17.0). 

In the HTML page I have: 

 `@page:first{margin:0;}@page:first {margin:4cm;}` 

It works as expected, as long as you do not set `displayHeaderFooter` to `true`. In that case the fist page gets no margins as expected, but the next pages have no margins on the right and bottom.

When trying to print this in the chrome browser you will not experience this problem, this makes sense because we do not get to set the `displayHeaderFooter` property.

HTML to reproduce this: [https://jsfiddle.net/prya18Lw/](url)

**Comment by hakimio** [comment]
This is [upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=835358).

**Comment by Jan-Timon** [comment]
But is it upstream? I have only been able to reproduce it with puppeteer, not just chromium. The linked upstream is about  'mix different page sizes and orientations (named pages)'. There is no issue with orientation or page sizes here.

**Comment by hakimio** [comment]
Original issue mentioned by @destan [355116](https://bugs.chromium.org/p/chromium/issues/detail?id=355116) got merged into that one.

**Comment by spiritix** [comment]
Any updates on this?

**Comment by AntonZaets** [comment]
Issue still exists, but it's in chromium. There is [actual bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1346874) related to the issue.
