### ISSUE TITLE
page.screenshot hangs if an alert() on page ready

### ISSUE THREAD

**Issue by BelaChtung** [puppeteer/puppeteer#2481]
I've run into an issue with page.screenshot() that occurs whenever an alert() dialog on the page happens after page ready.  The page.screenshot() hangs forever and if you end-task the node process, you get 

```
 UnhandledPromiseRejectionWarning: Error: Protocol error (Page.captureScreenshot): Target closed.
    at Promise (/var/www/html/puppeteer-bug/node_modules/puppeteer/lib/Connection.js:200:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/www/html/puppeteer-bug/node_modules/puppeteer/lib/Connection.js:199:12)
    at Page._screenshotTask (/var/www/html/puppeteer-bug/node_modules/puppeteer/lib/Page.js:738:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This is running puppeteer 1.3.0 under Ubuntu with Node 5.6.0 and the Chromium version that ships with Puppeteer.  Also replicated using full Chrome 65.

Basic Node app:

```
'use strict';
const puppeteer = require('puppeteer');

async function go(){
    const browser = await puppeteer.launch();
    console.log('opened browser');
    const page = await browser.newPage();
    console.log('created page');
    await page.goto('http://testing/puppeteer/', { timeout: 30000 });
    console.log('loaded page');
    await page.screenshot({
        path: './test.jpg'
    });
    console.log('took screenshot');
    await browser.close();
    console.log('closed browser');
}

go();
```

The html it's loading is:

```
<div style="position: absolute; background-color: #99dd99; top: 10px; left: 40px; width: 300px; height: 250px; padding: 5px 15px; border: 1px solid #444;">Stuff</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script>
	$(document).ready(function(){
		alert('test');
	});
</script>
```

If you comment out the alert, everything works.  With the alert in place, you get a console log for 'loaded page' and then everything hangs indefinitely.

A workaround is to use Promise.race:

```
    await Promise.race([
        page.screenshot({
            path: '/test.jpg'
        }),
        new Promise((resolve, reject) => setTimeout(function(){ reject('Screenshot timeout');}, 3000))
    ]);
```

The screenshot still doesn't complete, but at least it doesn't hang the app.

**Comment by aslushnikov** [comment]
Indeed, alerts hang screenshots. Can easily reproduce:

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.evaluate(() => alert(1));
    await page.screenshot(); // hangs..
    await browser.close();
    console.log('closed browser');
})();
```

This should be fixed upstream. 

@BelaChtung as a workaround, you can handle page's `dialog` event and accept/dismiss all the dialogs before taking screenshots.

**Comment by BelaChtung** [comment]
@aslushnikov Thanks for the workaround, works like a champ.

**Comment by tomahock** [comment]
@aslushnikov what if want to screenshot the dialog? How can I do it?

**Comment by aslushnikov** [comment]
> @aslushnikov what if want to screenshot the dialog? How can I do it?

@tomahock Dialogs aren't screenshottable; we can screenshot only web contents (dialog rendering is not part of it).

**Comment by Kikobeats** [comment]
could it be possible to overwrite `window` methods in order to avoid hanging the browser?

```js
await page.evaluate(async () => {
  window.alert = function() {}
  window.prompt = function() {}
  window.confirm = function() {}
  window.beforeunload = function() {}
});
```

The above code doesn't work, it looks like a window is available in a nonmutable way. Also, I tried to don't listen to page dialog events without successful.

Any suggestions in that direction could be very helpful.

**Comment by wiremanb** [comment]
> > @aslushnikov what if want to screenshot the dialog? How can I do it?
> 
> @tomahock Dialogs aren't screenshottable; we can screenshot only web contents (dialog rendering is not part of it).

Any changes to this? That would be an awesome feature.

**Comment by accamper** [comment]
This bug just caused me to waste an entire day. For me, it was `page.click` and `page.evaluate` that was hanging for the same underlying reason. Puppeteer should at least reject immediately in all functions if there is an active dialog

**Comment by sergtimosh** [comment]
Wasted a lot of time getting why my puppeteers tests refuse to fail. It's turned out that there is an alert that appears randomly in the application, which triggers automatic screenshot and that is what hangs everything. Real party breaker for testing purposes.

**Comment by hoperyy** [comment]
my solution:

```js
headlessPage.on('dialog', async (dialog) => {
     // "screenshot / evaluate" will go on by closing dialog
     await dialog.dismiss()
 })
```

**Comment by IonelaUdroiu** [comment]
Hi,
Is there any chance for this bug to be resolved? I'm using puppeteer 10 and page.screenshot() hangs forever when alert() dialog is showing up on the page.
