### ISSUE TITLE
UnhandledPromiseRejectionWarning on Navigation Timeout Exceeded

### ISSUE THREAD

**Issue by hkhan-lumatax** [puppeteer/puppeteer#2482]
### Steps to reproduce

**Environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: macOS 10.13.1
* Node.js version: 8.9.4

**Steps**

Below is the code producing this problem:

```javascript
try {
  ...
  await page.waitForNavigation({waitUntil: 'networkidle2'})
  ...
} catch (err) {
  // Throw an error.
  throwError(err, page, browser, res)
}

throwError = (async (err, page, browser, res) => {
    // Log the error.
    console.log(err)

    // Close the browser.
    await page.close()
    await browser.close()

    // Return an error response message.
    res.json({code: 'ERROR', message: 'An unexpected error has occurred.'})
})
```

When a request times out, I get the following error:

```
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>
(node:72563) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Runtime.callFunctionOn): Target closed.
(node:72563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What is the expected result?**

The page and browser should get closed without throwing an exception/error.

**What happens instead?**

`Error: Protocol error (Runtime.callFunctionOn): Target closed.` is displayed instead of the page and browser getting closed gracefully. Timeout Exceeded error is understandable and is correct.

I want to understand why `Error: Protocol error (Runtime.callFunctionOn): Target closed.` is being thrown and how we can avoid it?

**Comment by yusufilkeroguz** [comment]
same problem here.

node-v: 9.7.1

```javascript
goPage: async function (url) {
        let page = await this.page;

        await page.goto(url);
        await page.setViewport({width: 1366, height: 768});

        try {
            const waitNavigationPromise = page.waitForNavigation({timeout: 10000, waitUntil: "load"});

            await waitNavigationPromise;

            return await page;
        }
        catch(e) {
            this.catchError(e, page);

            return false;
        }
    },
```

```
Error: Navigation Timeout Exceeded: 10000ms exceeded
    at Promise.then (/var/www/crawler/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>

**Comment by aslushnikov** [comment]
@hkhan-lumatax can you please provide a reproducible example? It should be a script that I'll be able to run locally to see the issue.

We won't be able to help otherwise.

**Comment by aetheryx** [comment]
@aslushnikov I seem to have ran into the same issue. Here's a reproducible example:

```js
const puppeteer = require('puppeteer');

const getData = async () => {
  const browser = await puppeteer.launch({
    executablePath: '/usr/bin/chromium',
    headless: false
  });

  const page = await browser.newPage();
  page.goto('https://discordbots.org');

  await page.waitFor('.bot-list-section')

  const data = await page.$$eval('.bot-card', divs => Array.from(divs).map(bot => ({
    id: bot.querySelector('.info a').href.split('/').pop(),
    name: bot.querySelector('.bot-name').innerHTML,
    status: bot.querySelector('.status').innerHTML
  })))

  browser.close();
  return data;
};

getData()
  .then(data => {
    console.log(data.length);
  });
```

The browser opens, the result gets logged and the browser closes. The process idles for 30 seconds. The error gets logged, and then the process exits.  

The error does not occur if you `await` the `page.goto(...)` call. It should also be noted that the issue only occurs with websites that "load slowly" (referring to the spinner at the top of the tab), possibly because `browser.close()` is called before the promise from `page.goto(...)` resolves?

My environment information:
- Puppeteer version: 1.4.0
- Platform / OS version: Arch Linux 4.14.15-1
- Node.js version: 10.1.0

**Comment by aslushnikov** [comment]
@Aetheryx  Thanks, I see what's going on here. That's somewhat related to #1454; as a workaround, I'd recommend navigating until `domcontentloaded` event:

```js
await page.goto('https://discordbots.org', {waitUntil: 'domcontentloaded'});
```

**Comment by motsmanish** [comment]
'load' worked for me:

`await page.goto('http://example.com', {waitUntil: 'load'});`

**Comment by nhhockeyplayer** [comment]
thanks the domcontentloaded works beautiful

**Comment by nhhockeyplayer** [comment]
im seeing neither works
domcontentloaded relieves the exception but produces no query data
load produces query data and an exception
there is a race condition between the latter when data sometimes queries

**Comment by loomp** [comment]
I believe you were doing it the wrong way.

You shall call define waiter promise at first, call the URL change and then await waiter promise to complete.

`const waiter = page.waitForNavigation({
  waitUntil: 'networkidle0',
});

await page.goto(url);

await waiter;`

Of course, you can add `waitUntil` option into `goto` call directly as well.

**Comment by loomp** [comment]
> same problem here.
> 
> node-v: 9.7.1
> 
> ```js
> goPage: async function (url) {
>         let page = await this.page;
> 
>         await page.goto(url);
>         await page.setViewport({width: 1366, height: 768});
> 
>         try {
>             const waitNavigationPromise = page.waitForNavigation({timeout: 10000, waitUntil: "load"});
> 
>             await waitNavigationPromise;
> 
>             return await page;
>         }
>         catch(e) {
>             this.catchError(e, page);
> 
>             return false;
>         }
>     },
> ```
> 
> ```
> Error: Navigation Timeout Exceeded: 10000ms exceeded
>     at Promise.then (/var/www/crawler/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
>     at <anonymous>
> ```

I believe you were doing it the wrong way.

You shall define waiter promise at first, call the URL change and then await waiter promise to complete.

```
const waiter = page.waitForNavigation({
  waitUntil: 'networkidle0',
});

await page.goto(url);

await waiter;
```

Of course, you can add `waitUntil` option into `goto` call directly as well.
