### ISSUE TITLE
Usage of attributes in CSS selector

### ISSUE THREAD

**Issue by jorge-cbqa** [puppeteer/puppeteer#2483]
Hey guys, I'm trying to use attributes for selecting elements. Example:
            <button
              type='submit'
              className='btn btn-info'
              **data-tid="adddataset-create-btn"**>
              {this.props.buttonLabel}
            </button>

I need to be able to find and interact with that element using this CSS selector
**[data-tid="adddataset-create-button"]**

Is this possible? Because so far I haven't been able to do it :(

**Comment by vsemozhetbyt** [comment]
It would be helpful if you could provide the page URL and a small but complete code to reproduce the issue.

**Comment by jorge-cbqa** [comment]
Nevermind, I see what's the problem, the selector I was using was incorrect, thanks for answering anyway :)
