### ISSUE TITLE
Feature request: headerTemplate and footerTemplate as function

### ISSUE THREAD

**Issue by Ciantic** [puppeteer/puppeteer#2484]
In order to make various different kind of headers etc. it could be easier to have headerTemplate as a function e.g.

```javascript
await page.pdf({
    headerTemplate : ({ date, title, url, pageNumber, totalPages }) => {
      if (pageNumber == 0) {
        return "";
      }
      if (pageNumber > 1) {
        return "<div>My Fancy header</div>"
      }
    }
  });
```

I know that there are post-processing methods to do this e.g. mentioned in #2089 with combining PDF files. But I think having a function templates would tremendously make things easier. 

There must be some underlying issue in the Chromium itself that makes this hard, but this will *eventually* be fixed, as more people want to do their PDFs with HTML.

## custom blocks and pageDom idea

One step further from this idea is kind of like generic implementation which does not require footer or headers as a concept. Instead boxes in the sides of the document (that is, they do not require reflow jiggery, only cutting on the viewport at given page from the edges):

```javascript
await page.pdf({
  footerArea: {
    bottom: "8in",
    left: "2in",
    right: "2in",
    template: ({pageNumber, pageDom}) => {
      // pageDom should contain only elements on that page.

      // Get a first H1 elements on the current page
      // and show a footer based on that element

      if (pageDom.querySelectorAll("h1")[0].text == "References") {
        return "<div>Custom footer for page with References title<div>";
      }
    }
  },
  customArea: {
    top: "2in",
    left: 0,
    bottom: "2in",
    template: ({pageNumber}) => {
      return `<div>The custom sidebar {pageNumber}</div>`
    }
  }
});
```

Height could be also one of the options at the beginning, so that it's also required part of the options, because figuring out dynamic height could be difficult. Dynamic sizing could be solved further down the road.

**Comment by aslushnikov** [comment]
There's a similar feature request to run javascript inside the <script> tags of header/footer templates. I think it will satisfy your needs, see #2167.

**Comment by kromit** [comment]
I think fixing this issue would be a better solution to the common problem of #2167 and #2089. Plus it is easier to implement: just add `headerFunction` and `footerFunction` and put the result on the current  `headerTemplate` and `footerTemplate`.

This issue deserves to be reopened.

**Comment by Ciantic** [comment]
In short term perhaps functions are enough. But I agree this should be reopened.

In longer term this is one of those issues that needs a whole new approach in my opinion, e.g. my custom blocks idea, because page templating is difficult. Header template and footer template is not enough, there are many other cases such as:

What if someone wants a right center edge of the page be the "page number area" etc? How about generating page numbers based on DOM of that page, e.g. if the title with "Part I" is present, don't show page number?

This needs some serious thinking by the puppeteer team to solve in long term.

**Comment by kromit** [comment]
I am sure the provided longer term examples can be solved with functions and CSS. I am doing it right now with PhantomJS. The only thing that is not possible there is different header/footer sizes per page. So my preferred solution would look like this:

```
generateHeaderFooter: ({pageNumber, totalPages, ...other }) => {
    ...
    // generate/style/position your footer/header using any node
    // tech/lib you want since you are not limited to the page context
    ...
    return {
        headerMargin,   
        headerHtml,
        footerMargin,
        footerHtml,
        ...more   
    }
  });
```
This is a more powerful solution than scripting within the header/footer template (which also would be nice).

But I am not seeing this happening in the near future, so I would be already happy if puppeteer could at least provide the functionality that is there in PhantomJS for years so I could switch to headless chrome :)

**Comment by kromit** [comment]
It looks like devTools do not support functions for header/footer in first place:
https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF

So we have to open a ticke for dev tools first.

**Comment by aslushnikov** [comment]
> I think fixing this issue would be a better solution to the common problem of #2167 and #2089. Plus it is easier to implement: just add headerFunction and footerFunction and put the result on the current headerTemplate and footerTemplate.

Implementing this is the same complexity as implementing #2167 since both require manually spinning javascript loop while generating pdf layout.
