### ISSUE TITLE
browser.close() fails due to timeout and never returns

### ISSUE THREAD

**Issue by GlynnJKW** [puppeteer/puppeteer#2485]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.9
* Platform / OS version: Windows 10
* Node.js version: 

**What steps will reproduce the problem?**

Even just opening a browser with puppeteer.launch and then closing it with browser.close() results in this issue.

**What is the expected result?**
The browser process should close when I call browser.close()

**What happens instead?**
The promise times out and the browser fails to close

**Comment by aslushnikov** [comment]
We run `browser.close()` at least a few dozen times daily - both personally and on CI - and never had this issue. Most likely it has to do with your setup / environment.

The issue description is way too general; there's no way we can help. Please re-file with a good reproduction steps.

**Comment by h2non** [comment]
I'm experiencing the same issue on Docker using Chromium `71.0.3578.80`. Tried with puppeteer `v1.11` & `v1.9`.

The `browser.close()` promise is never resolved. I can't reproduce it outside of Docker.

**Comment by aslushnikov** [comment]
@h2non do you use dumb-init in docker? I remember there were issues with running chrome as PID=1 in docker since PID=1 processes get special treatment. 

Check out our [Docker image](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker).

**Comment by h2non** [comment]
Thanks! I'm not using that image or `dumb-init` but will consider it.

FWIW, the workaround for me was calling `browser.close()` several times by using the following approach: 
`await Promise.race([browser.close(), browser.close(), browser.close()])`. 

Apparently, from the second call and beyond puppeteer is capable of killing the main process properly and resolve the promise.

**Comment by oronMoonshot** [comment]
so
here are reproduction steps:
docker - with puppeteer:
^1.13.0

Dockerflle:
FROM node:8.9.3

RUN  apt-get update \
     # See https://crbug.com/795759
     && apt-get install -yq libgconf-2-4 \
     # Install latest chrome dev package, which installs the necessary libs to
     # make the bundled version of Chromium that Puppeteer installs work.
     && apt-get install -y wget --no-install-recommends \
     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
     && apt-get update \
     && apt-get install -y google-chrome-unstable --no-install-recommends \
     && rm -rf /var/lib/apt/lists/* \
     && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
     && chmod +x /usr/sbin/wait-for-it.sh

# Create app directory
WORKDIR /usr/src/app
ADD . /usr/src/app

RUN mv .env.prod .env

COPY .npmrc .npmrc

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./


RUN npm install

RUN rm -f .npmrc

RUN npm run-script build

# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 4300
CMD [ "npm", "run-script", "serve" ]


starting puppeteer:
const browser = await puppeteer.launch({headless: true, args: ["--no-sandbox"]});

this promise never resolves:
await browser.close();
