### ISSUE TITLE
Running multiple instances at once

### ISSUE THREAD

**Issue by jjason685** [puppeteer/puppeteer#2489]
Hey,

I'm developing something that requires me to run a LOT of instances of puppeteer at once (multiple browsers not pages.) I'm testing for a CSS selector and I was wondering if there was any way that I could make puppeteer more viable for this - right now I can only run 5 instances and I know someone who can run up to 40 with the same computer - apparently they changed something in the source code? How would I proceed to do this?

**Comment by aslushnikov** [comment]
> right now I can only run 5 instances and I know someone who can run up to 40 with the same computer - apparently they changed something in the source code?

I'd try asking them. Also, check out our [slack channel](https://join.slack.com/t/puppeteer/shared_invite/enQtMzAyOTU1MzQyOTQ1LTUzOTAxNjE5YWI0YzNmYmRkN2I4MDg2MzI4OGE3YWNhZDBlYWMyNTlmOTJlN2RhYzlmODI4ZDQxZGEyMGIwNDY) - someone might help there.
