### ISSUE TITLE
PUPPETEER_CHROMIUM_REVISION not used when launching chromium

### ISSUE THREAD

**Issue by benperiton** [puppeteer/puppeteer#2490]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: OSX 10.11.6
* URLs (if applicable):
* Node.js version: 10.0.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. export PUPPETEER_CHROMIUM_REVISION=526987 && npm install

**What is the expected result?**
When running puppeteer it should use the version specified in the ENV variable

**What happens instead?**
it tries to use the version specified in the package.json

**Comment by aslushnikov** [comment]
Closing this given the comment in the relevant pull request: https://github.com/GoogleChrome/puppeteer/pull/2491#issuecomment-386152557
