### ISSUE TITLE
Chrome becomes unresponsive when headless: false

### ISSUE THREAD

**Issue by itsachen** [puppeteer/puppeteer#2492]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `1.3.0`
* Platform / OS version: macOS 10.12.6
* Node.js version: 8.11.0

**What steps will reproduce the problem?**
```js
const Puppeteer = require('puppeteer');

async function run() {
  const url = 'https://www.nike.com/launch';

  const browser = await Puppeteer.launch({ headless: false });

  const page = await browser.newPage();

  await page.goto(url);
  await page.screenshot({fullPage: true, path: 'example.png'});

  return browser.close();
}

(async () => {
  await run();
})();
```

**What is the expected result?**
In the script above, puppeteer launch in non-headless mode, navigate to a URL, load the page and take a screenshot.

**What happens instead?**
When puppeteer navigates to a particular URL (`https://www.nike.com/launch`), it attempts to load the page but Chromium quickly becomes unresponsive. The method will time out and Chromium will exit as well.

[See verbose logs](https://gist.github.com/itsachen/ca859095a69e5aebc0dc550fbd26a471).

The strange thing is that the script completes successfully if `headless: true` is configured instead. I have also tested the script using my local Chrome (66.0.3359.139) and Chrome Canary (68.0.3417.0) and the issue still persists. I have also been able to run the bundled version of Chromium separately and navigate to the page successfully manually.

I have also tried setting the viewport and user agent of the request to mimic manual interact with the page, but this did not help:
```js
await page.setViewport({
  width: 1920,
  height: 1080
})

await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36');
```

I'm at a loss as to what could be happening. The only thing I have considered is that the webpage is loading a large number of assets (images), but the dev tools become unresponsive when this occurs so its difficult to debug.

**Comment by ebidel** [comment]
Hmm, not seeing the same. This script produces `example.png` for me:

```js
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch({headless: false});
const page = await browser.newPage();
await page.setViewport({width: 1920, height: 1080});
await page.goto('https://www.nike.com/launch');
await page.screenshot({fullPage: true, path: 'example.png'});
await browser.close();
})();
```

**Comment by itsachen** [comment]
Really strange, must be something on my end. I'll keep digging, thanks for the sanity check!

**Comment by aslushnikov** [comment]
This doesn't repro for me as well; speculatively closing.
