### ISSUE TITLE
why is status code not always defined?

### ISSUE THREAD

**Issue by patrickkettner** [puppeteer/puppeteer#2494]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Any
* URLs (if applicable): https://httpstat.us/404
* Node.js version: v9.9.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. git clone https://gist.github.com/patrickkettner/f29d25041d49438114b192c0b05ee009
2. cd f29d25041d49438114b192c0b05ee009
3. npm i
4. node index.js

**What is the expected result?**

script should not throw an error

**What happens instead?**

it throws an error because headers().status is not defined (but it is on many other sites)

**Comment by aslushnikov** [comment]
The httpstat.us itself doesn't return status response header for me; checked with CURL: 

```
$ curl -i https://httpstat.us/404
HTTP/1.1 404 Not Found
Cache-Control: private
Content-Length: 13
Content-Type: text/plain; charset=utf-8
Server: Microsoft-IIS/10.0
X-AspNetMvc-Version: 5.1
Access-Control-Allow-Origin: *
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=ddbcacbd50d0c4e3a7a72b87969a21a5cd465bc58f4e9855e496f5db50604b18;Path=/;HttpOnly;Domain=httpstat.us
Date: Thu, 03 May 2018 15:19:14 GMT
```

**Comment by patrickkettner** [comment]
thanks for looking @aslushnikov! I believe you are incorrect however.

The result is on the very first line of the response

![image](https://user-images.githubusercontent.com/465414/39600856-de323886-4ed4-11e8-81e2-366ba364532c.png)

You can use the `-L` flag to grab just the status code instead of the full set of headers.

```sh
curl -L  https://httpstat.us/404
404 Not Found
```

Also, If you try changing the url in my original test to the `google.com/404`, you will see a very similar result


```sh
$ curl -I https://google.com/404
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 1564
Date: Thu, 03 May 2018 20:14:55 GMT
Alt-Svc: hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35"

$ curl -L https://google.com/404
404 Not Found
```

But it does have a status code for puppeteer.

**Comment by aslushnikov** [comment]
> The result is on the very first line of the response

@patrickkettner ah, but that's not a header, that's a [status line](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Status_codes). You can get status code with [`response.status()`](https://github.com/GoogleChrome/puppeteer/blob/v1.3.0/docs/api.md#responsestatus). IF you care about status text as well, see #317.

**Comment by patrickkettner** [comment]
ah cheers

when googling "[puppeteer status code](https://www.google.com/search?q=puppeteer+status+code)", the first result is about that, and I missed response.status() when looking through the api docs

any idea why status is defined for some of the url headers but not others?

**Comment by aslushnikov** [comment]
> any idea why status is defined for some of the url headers but not others?

No idea
