### ISSUE TITLE
Not all nodes return from long list

### ISSUE THREAD

**Issue by alexdruk** [puppeteer/puppeteer#2496]
* Puppeteer version: 1.3.0
* Platform / OS version:  Mac OS 10.11.6
* Node.js version: 8.9.4

**What steps will reproduce the problem?**
When iterating on log list of children not all nodes are returned.
```js
logitems = await page.evaluate((sel) => {
        let element = document.querySelector(sel);
         return element.children.length;
     }, '#log > div > div.log.scroll');
console.log('got logitems:', logitems); // return 1000

const LOGITEM_SELECTOR = '#log > div > div.log.scroll > div:nth-child(INDEX) > span.message';
for(var i = 3; i <= logitems-3; i++)  {
        let logitem = LOGITEM_SELECTOR.replace("INDEX", i);
        console.log(logitem)
        let dat = await page.$eval(logitem, el => el.innerHTML).catch(e => {console.log(e);});
}
```
The code above stop on any i > 200 and produce an error:
`Error: failed to find element matching selector "#log > div > div.log.scroll > div:nth-child(215) > span.message"
`

This behaviour is very similar to what happens when inspection nodes in Chrome - when dealing with very long list inspector produce a dialog message "Show All nodes".
![screen shot 2018-05-03 at 11 36 46 am](https://user-images.githubusercontent.com/840087/39569764-7a11db94-4ec6-11e8-9f26-2dae1c26e23e.png)

**Comment by aslushnikov** [comment]
There's no code in pptr that would cause this kind of behavior. You either found a bug in webplatform/devtools protocol, or something fishy going on with your website. It's impossible to figure unless I'll be able to reproduce this.

Please refile with a decent repro.
