### ISSUE TITLE
Reuse cache between launches in headless mode

### ISSUE THREAD

**Issue by blackdeman** [puppeteer/puppeteer#2497]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Linux / CentOS 7.4.1708
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

1. Run the script  (userDataDir is expected to be empty)
```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    userDataDir: '/tmp/user-data-dir',
    headless: true,
    args: ['--no-sandbox'],
  });

  const page = await browser.newPage();
  const response = await page.goto('https://example.com/');
  console.log(response.fromCache());

  await browser.close();
})();
```
Console:
```
false
```
2. Run the script for the second time

**What is the expected result?**
```
true
```

**What happens instead?**
```
false
```

Puppeteer works as expected in headfull mode, though.

**Comment by andrewsezko** [comment]
@blackdeman If that case is critical for you, you can simply clear cache and cookies before opening the same page in a new browser instance.

**Comment by korya** [comment]
We are experiencing the same issue with `puppeteer@1.4.0`.

**Comment by JohnBruce** [comment]
fwiw, still seeing this on puppeteer@1.7.0

Its not the end of the world, but there are use cases where reusing/sharing a cache across multiple browser instances makes sense, so it would be cool if this could be addressed.

**Comment by yegor211** [comment]
so is this still not possible in headless?

**Comment by wtip** [comment]
This seems to be working on v1.14.0 based on my own tests. It wasn't working on 1.9.0

**Comment by aslushnikov** [comment]
Indeed; works for me on v1.14.0.

**Comment by Supamiu** [comment]
I managed to reproduce the issue with v1.16.0 using the following code:

```js
const puppeteer = require('puppeteer');

async function test() {
    const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox']});
    const page = await browser.newPage();
    const response = await page.goto('https://example.org');

    console.log(response.fromCache());

    await browser.close();
}

test();
```

- Puppeteer version: 1.16.0
- Platform / OS version: Windows 10 Pro v1803 - Build #17134.765
- Node.js version: 10.15.3

Edit: Same on v1.14.0.

**Comment by blackdeman** [comment]
The initial script works for me on v1.18.1. But it doesn't work when request interception is on.

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    userDataDir: '/tmp/user-data-dir',
    headless: true,
    args: ['--no-sandbox'],
  });

  const page = await browser.newPage();

  // enable request interception
  await page.setRequestInterception(true);
  page.on('request', request => {
    request.continue();
  });

  const response = await page.goto('https://example.com/');
  console.log(response.fromCache());

  await browser.close();
})();
```

I have found out that **page.setRequestInterception(true)** method disables cache. Indeed; there is a test in puppeteer (*page.spec.js*) which says that page cache *'should stay disabled when toggling request interception on/off'*. @aslushnikov, can you please explain the idea behind that test? Is it safe to manually enable cache when request interception is on?

```javascript
await page._client.send('Network.setCacheDisabled', {
  cacheDisabled: false
});
```

**Comment by blackdeman** [comment]
Similar questions are being asked in #4620
