### ISSUE TITLE
Why there is no maximize window function?

### ISSUE THREAD

**Issue by li-01** [puppeteer/puppeteer#2500]
Although i could use below code, there is still some part of the browser window being covered by the taskbar on Windows.

puppeteer.launch({headless: false, args: ['--start-maximized', '--window-size=1920,1080']}).then(async browser => {
  const page = await browser.newPage();
  await page.setViewport({width:1920, height:1080});

**Comment by ebidel** [comment]
Try `'--start-fullscreen'`.

**Comment by li-01** [comment]
@ebidel oh yes, I found this option. But my purpose is to simulate exact user interaction which is usually maximizing the window.

**Comment by wangmeijian** [comment]
The specified element does not work in full screen mode in headless mode, such as document.body.requestFullScreen ().

**Comment by aslushnikov** [comment]
> Why there is no maximize window function?

Making one doesn't make much sense unless there's a strong demand from the community.
Current workaround satisfy the majority of our customers.

**Comment by wanglyaaa** [comment]
Hi,have you solve it?

**Comment by li-01** [comment]
@wanglyaaa no, I had to manually set these size like below codes

const browser = await puppeteer.launch({ headless: true, args: ['--start-fullscreen', '--window-size=1920,1040'] });
const page = await browser.newPage();
await page.setViewport({ width: 1920, height: 1040 });

**Comment by AzySir** [comment]
@li-01  is your solution here still valid. Can't seem to find anything, really surprising as they don't/didn't offer this as a default setting

**Comment by li-01** [comment]
> 
> 
> @li-01 is your solution here still valid. Can't seem to find anything, really surprising as they don't/didn't offer this as a default setting

yes.
what do you mean can't find anything?

**Comment by AzySir** [comment]
@li-01 anything else - "Can't find any other examples". As in I thought doing this would be a simple one line code like selenium.

**Comment by bahodir-annaev** [comment]
@AzySir , this worked for me:
await puppeteer.launch({headless: false, defaultViewport: null, args: ['--start-maximized']})

**Comment by fahadshehzada** [comment]
> @AzySir , this worked for me:
> await puppeteer.launch({headless: false, defaultViewport: null, args: ['--start-maximized']})

but not working in case headless:true

**Comment by iniatse** [comment]
Yep does not work in `headless:true` mode

**Comment by totsteps** [comment]
@fahadshehzada, @iniatse `headless:true` means Chrome will be launched in `headless` mode, that is there won't be any GUI!

**Comment by cdmalcl** [comment]
Minimize the previous chrome first...

**Comment by sharutkarsh** [comment]
The below config works for chromium based browsers, like Google Chrome & MS Edge.

 'chromeOptions': {
            "args": [
                "--window-size=1920,1080"
            ]
        }
        
        Do you have any solution for Safri and Firefox?
