### ISSUE TITLE
do we have any method or attribute to indicate that page has closed?

### ISSUE THREAD

**Issue by Rvtea** [puppeteer/puppeteer#2501]
Searched issues and could not find any hints, so I opened this. If I missed a issue already has this, please close this. Thanks in advance.

I read the  api doc and see currently pptr only have 'close' event and found `_target._isClosedPromise` is a promise value which could not be used as a state indicator. Do we have any method or attribute to indicate that the page has been closed after invoke `page.close()` ?

Feel free to correct me if I misunderstand sth.

**Comment by aslushnikov** [comment]
@Rvtea once the `page.close()` returns control, the page is closed. Isn't that enough?

**Comment by Rvtea** [comment]
@aslushnikov 
In most cases, that's enough for usage. But currently i am working on a testing tool and in some scenario, `page` is kind of used in global scope and i need to judge the page is closed in a `afterAll` callback to see if i need to call `page.close()` again.

**Comment by aslushnikov** [comment]
@Rvtea I see. Feel free to add the method to send a PR.
