### ISSUE TITLE
Page.goto() always causes a Navigation Timeout - but i can get screenshot somehow

### ISSUE THREAD

**Issue by hexad** [puppeteer/puppeteer#2504]
### Steps to reproduce

* Puppeteer version: 1.2.0
* Platform / OS version: Windows 7 x64
* Node.js version: 8.11.1

**What steps will reproduce the problem?**
I am trying this code:

```js
// <-- add event on top of file
process.on("unhandledRejection", (reason, p) => {
        console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
        // browser.close(); // <-- no need to close the browser here
});

const puppeteer = require('puppeteer');
async function getPic() {
    try{ // <-- wrap the whole block in try catch
      const browser = await puppeteer.launch(/*{headless: false}*/);
      const page = await browser.newPage();
      await page.setViewport({width: 1000, height: 500}); // <-- add await here so it sets viewport after it creates the page


      //await page.goto('https://www.google.com');  //Old way of doing. It doesn't work for some reason...

      page.goto('https://www.google.com/'); // async


      // wait for either of events to trigger
      await Promise.race([
        page.waitForNavigation({waitUntil: 'domcontentloaded'}),
        page.waitForNavigation({waitUntil: 'load'})
      ]);


      await page.screenshot({path: 'pic.png'});
      await browser.close(); // <-- close browser after everything is done
    } catch (error) {
      console.log(error);
    }
}

getPic();
```

I request a pic from the page loaded for testing purposes.

With code as it is, i get pic and this error:

```
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\...\pupet test\node_modules\pupp
eteer\lib\NavigatorWatcher.js:71:21)
    at <anonymous> } reason: Error: Navigation Timeout Exceeded: 30000ms exceede
d
    at Promise.then (C:\...\pupet test\node_modules\pupp
eteer\lib\NavigatorWatcher.js:71:21)
    at <anonymous>
```

When i remove the process.on() code in the beginning, i get no pic and this error message:

```Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\...\pupet test\node_modules\puppeteer\lib\NavigatorWatcher.js:71:21)
    at <anonymous>
(node:5548) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded
: 30000ms exceeded
    at Promise.then (C:\...\pupet test\node_modules\puppeteer\lib\NavigatorWatcher.js:71:21)
    at <anonymous>
(node:5548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:5548) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```

When process.on() IS there but instead i use await

```js
page.goto('https://www.google.com');
```

 INSTEAD OF

```js
      page.goto('https://www.google.com/'); // async


      // wait for either of events to trigger
      await Promise.race([
        page.waitForNavigation({waitUntil: 'domcontentloaded'}),
        page.waitForNavigation({waitUntil: 'load'})
      ]);
```

i don't get the picture and i get this:

```
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\...\pupet test\node_modules\pupp
eteer\lib\NavigatorWatcher.js:71:21)
    at <anonymous>
```

Finally, when i remove process.on() and i use await

```js
page.goto('https://www.google.com');
```

 INSTEAD OF

```js
page.goto('https://www.google.com/'); // async


      // wait for either of events to trigger
      await Promise.race([
        page.waitForNavigation({waitUntil: 'domcontentloaded'}),
        page.waitForNavigation({waitUntil: 'load'})
      ]);
```
i don't get the picture and i get this:

```
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\...\pupet test\node_modules\pupp
eteer\lib\NavigatorWatcher.js:71:21)
    at <anonymous>
```

In conclusion, whenever i don't use process.on() i don't have my code executed.

But when i do use process.on() i get the screenshot but i still get the error. Now i know that the 'unhandledRejection' event is emitted whenever a Promise is rejected and no error handler is attached to the promise within a turn of the event loop.

Now, when i use :

```js
page.goto('https://www.google.com/').catch(error => console.log("this isn't handled by the try catch since you don't await it", error));
```

for troubleshooting purposes, i get:

```
this isn't handled by the try catch since you don't await it Error: Navigation T imeout Exceeded: 30000ms exceeded at Promise.then (C:\Users\User1\Desktop\fb proj\pupet test\node_modules\pupp eteer\lib\NavigatorWatcher.js:71:21) at <anonymous>
```

Which means page.goto() is the culprit. No matter what i try i cannot seem to make it work.
It appears to be completely illogical, how come it throws an error but still manages to get the pic?

If i try stuff like:

```js
const puppeteer = require('puppeteer');

async function getPic() {
	  try { // <-- wrap the whole block in try catch
	      const browser = await puppeteer.launch(/*{headless: false}*/);
	      const page = await browser.newPage();
	      await page.setViewport({width: 1000, height: 500}); // <-- add await here so it sets viewport after it creates the page
	      await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');
      	  await page.setExtraHTTPHeaders({
        		'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
      	  });
	      await page.goto('https://www.google.com/', {waitUntil: 'load'})
	      await page.screenshot({path: 'pic.png'});
	      await browser.close(); // <-- close browser after everything is done
   		} catch (error) {
      		console.log(error);
    	}
}

getPic();
```

Then i just get the error without any picture.

I should also add, that i was contacted by the guy who wrote the unhandledRejection for node and told me that i shouldn't put it in my code. But wihtout it.. it doesn't work at all!

**Comment by aslushnikov** [comment]
@hexad if I understand correctly, you're screenshotting the main page of google search.

In this case, the following code works just fine for me on pptr v1.4.0:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setViewport({width: 1000, height: 500});
  await page.goto('https://www.google.com/');
  await page.screenshot({path: 'pic.png'});
  await browser.close();
})();
```

If it doesn't for you, that's an issue that should be solved first, but it's most likely something to do with your environment.

**Comment by hexad** [comment]
I managed to solve this by providing proxy arguments to the launch function of puppeteer

**Comment by DerekTso** [comment]
@hexad could you advise how to set proxy? is it by `npm config set HTTP_PROXY=127.0.0.1:1080` ?

**Comment by knownasilya** [comment]
For anyone else having a similar issue, I solved it by adding a protocol (http://) to the url, otherwise it timesout when creating a pdf (but works with `headless: false`).

**Comment by jprivillaso** [comment]
I get the same error, using pptr 1.4.0, when I try to go to the URL `https://www.nytimes.com/`.
This is a constant error, in different pages. When I test with example.com it works.
This behaviour happens inside a docker environment at aws, inside my computer it works. 

Do you have any clues what can be different between running it in MacOs and Linux Centos ?

**Comment by markusha** [comment]
This https://github.com/GoogleChrome/puppeteer/issues/2504#issuecomment-389726596 does not work in my case.
pptr 1.8.0
node 10.11.0 x64
Win7 x64

However if headless mode is disabled the code works fine.

**Comment by flycatrix** [comment]
> 这[＃2504（评论）](https://github.com/puppeteer/puppeteer/issues/2504#issuecomment-389726596)不工作在我的情况。
> pptr 1.8.0
> 节点10.11.0 x64
> Win7 x64
> 
> 但是，如果禁用无头模式，则代码可以正常工作。

I have the same problem, have you resolve it?

**Comment by xco1a** [comment]
> This [#2504 (comment)](https://github.com/puppeteer/puppeteer/issues/2504#issuecomment-389726596) does not work in my case.
> pptr 1.8.0
> node 10.11.0 x64
> Win7 x64
> 
> However if headless mode is disabled the code works fine.

I have the same problem, have you resolve it?
