### ISSUE TITLE
200 status of respond checking in links with opening in new tab.

### ISSUE THREAD

**Issue by maximkoshelenko** [puppeteer/puppeteer#2505]
Hello team. A newbie question. Im trying to check status of redirection after clicking on links with opening in new tab options. Code is working for links without opening in new tab but with new tab it always  "Navigation Timeout Exceeded:". Help :)

* Platform / OS version: MacOS
* URLs (if applicable): http://www.endocrinologynetwork.com/
* NPM - v : 6.0.0

Code:

    await page.goto('http://www.endocrinologynetwork.com/', {waitUntil: "load" });
    await page.waitForSelector('.l-footer.wrap');

    const [response] = await Promise.all([
    page.waitForNavigation(),
        
    await page.$$eval("a", as => as.find(a =>
    a.innerText.includes("Advertiser Terms")).click())

    ]);
    expect(response._status).toBe(200);

Expected result:
With links without opening in a new tab (footer Editorial Board for example) it is possible to check respond status
Actual result:
With new tab links (footer Advertiser Terms for example) it i always "Navigation Timeout Exceeded:"

**Comment by aslushnikov** [comment]
The `page.waitForNavigation` waits for the current page to navigate; if the link opens a new page, then current page is not affected.

You probably want to check that all the opened pages are loaded - you can use browser targets to make sure pages do open. If you absolutely need to get the response of the new page, you can try getting the link's `href` and navigate a separate page to the URL. This way you'll get the main resource response.

Hope this helps.
