### ISSUE TITLE
i use page.type(selector, text[, options])  i want to input one element ,but actual input other element

### ISSUE THREAD

**Issue by yanguoyu** [puppeteer/puppeteer#2507]
code:
```js
const puppeteer = require('puppeteer');

puppeteer.launch().then(async function(browser) {
  const page = await browser.newPage();
  await page.goto("https://github.com/", { waitUntil : ['load', 'domcontentloaded']});
  await page.type(".js-chromeless-input-container .js-site-search-focus", "841185308");
  await page.screenshot({path: '2.png', fullPage: true});
})
```
**What is the expected result?**
![image](https://user-images.githubusercontent.com/12881040/39682733-42088dbc-51e4-11e8-8fa8-9e5b67ad0af0.png)

**What happens instead?**
![image](https://user-images.githubusercontent.com/12881040/39682751-55c7ca48-51e4-11e8-83ac-b499bd19303a.png)

**Comment by mboeser** [comment]
@yanguoyu try setting a larger viewport, it worked for me when I did

` await page.setViewport({width: 1200, height: 1500});`

**Comment by yanguoyu** [comment]
@mboeser  my problem is not viewport, it's the input location is wrong. 
you can try my code, it's a simple test
![image](https://user-images.githubusercontent.com/12881040/39859669-20fcd692-546d-11e8-8515-5b32dbb4c4db.png)

**Comment by arecvlohe** [comment]
@yanguoyu Maybe put a more specific selector?

`input.form-control.header-search-input.js-site-search-focus`

**Comment by mboeser** [comment]
I tried the more specific selector without setting a viewport and the value still appeared in the username field. Perhaps since search field is hidden when not setting a larger port size, puppeteer defaults to the next input tag. workaround could be to set a larger viewport so the search field is visible on the page or click the side menu to reveal the search field.

**Comment by yanguoyu** [comment]
@arecvlohe it's only a input
![image](https://user-images.githubusercontent.com/12881040/39902362-4450a734-5500-11e8-85da-267dadd291c7.png)

**Comment by yanguoyu** [comment]
i input the element is only one
![image](https://user-images.githubusercontent.com/12881040/39902527-f7efe41c-5500-11e8-9092-4555295b860d.png)

**Comment by aslushnikov** [comment]
The following works just fine for me:

```js
const puppeteer = require('puppeteer');

puppeteer.launch().then(async function(browser) {
  const page = await browser.newPage();
  await page.setViewport({
    width: 1600,
    height: 600
  });
  await page.goto("https://github.com/", { waitUntil : ['load', 'domcontentloaded']});
  const selector = 'input.form-control.header-search-input.js-site-search-focus';
  await page.waitForSelector(selector);
  await page.type(selector, "841185308");
})
```
