### ISSUE TITLE
request Environment variable for executablePath

### ISSUE THREAD

**Issue by latel** [puppeteer/puppeteer#2508]
We'd like to define it in the environment rather than specify it when we call it in the node scripts, as we are making a puppeteer environment shared between teams.

**Comment by aslushnikov** [comment]
@latel we specifically avoid env variables in the `lib/` code so that puppeteer can be used as a library one day. See #1809 

But you can wrap it on your side:

```js
const browser = await pptr.launch({
  executablePath: env.CHROME_PATH
});
```
