### ISSUE TITLE
page.on('dialog') does not trigger for save dialog

### ISSUE THREAD

**Issue by KBPratap** [puppeteer/puppeteer#2510]
Navigate to url chrome://policy/
click on 'Export to JSON' button
Save dialog shows up. the event handler `page.on('dialog', (dialog)=> { console.log(dialog.type()})` is not triggered.

Any idea what is wrong with this dialog or am I missing something?

**Comment by 7vv** [comment]
### dialog.accept() doesn't work in headless mode
```
page.on('dialog', (dialog)=> { 
  dialog.accept();
})
```

**Comment by aslushnikov** [comment]
You are not missing anything - these dialogs are not supported. Also, this specific dialog is triggered by a custom chrome binding that is available only for the Chrome WebUI pages (the ones under the `chrome://` scheme).

The only dialogs we support are `alert`, `confirm`, `beforeunload` and `prompt`. Supporting other usecases require upstream contributions to chromium that are possible but energy-consuming. If this has a strong demand from the community, we'll surely do. Closing for now.

**Comment by andrisi** [comment]
@aslushnikov would this still be too cumbersome to implement? You have waitForFileChooser for upload dialogs. That's an entirely different thing?
