### ISSUE TITLE
page.type() doesn't work in headless mode 

### ISSUE THREAD

**Issue by ashutosh-bhardwaj** [puppeteer/puppeteer#2512]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: ubuntu 14.04
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
```js
it('Should able to Login successfully', async () => {
    const emailSelector = 'input[name=email]';
    await page.waitForSelector(emailSelector);
    const email = 'example.com';
    await page.type(emailSelector, email);
    const passwordSelector = 'input[name=password]';
    await page.waitForSelector(passwordSelector);
    const password = '1234';
    await page.type(passwordSelector, password);
    const navigationPromise = page.waitForNavigation();
    const loginButtonSelector = '.auth0-lock-submit';
    await page.waitForSelector(loginButtonSelector);
    await page.click(loginButtonSelector);
    await navigationPromise;
    const productsSelector = '.Products';
    await page.waitForSelector(productsSelector);
    await page.waitFor(3000);
  }, WAIT_FOR);
```
**What is the expected result?**
Should able to type email and password into input fields, then hit login button.
**What happens instead?**
But, input fields remains blank(empty) and login button gets clicked

**Comment by mboeser** [comment]
Do you try hard coding the values in page.type() instead of referencing them? I curious if there's any issue there. Also, I sometimes add a catch to the await calls and see if it throws an error whenever I'm stuck. 

Example:
`await page.goto(www.example.com, {waitUntil:['networkidle2'],timeout:5000}).catch((e)=>{console.error(e)});`

**Comment by ashutosh-bhardwaj** [comment]
@mboeser  Thanks for your comment.
Although I don't think referencing the value inside `page.type()` is an issue.

for instance look at this snippet of code 

`it('Should able to Login successfully', async () => {
    await page.waitFor(2000);
    const emailSelector = '[name=email]';
    const { email, password } = USER;
    await page.type(emailSelector, email);
    const passwordSelector = '[name=password]';
    await page.type(passwordSelector, password);
    const navigationPromise = page.waitForNavigation();
    const loginButtonSelector = '.auth0-lock-submit';
    await page.click(loginButtonSelector);
    await navigationPromise;
    const productsSelector = '.Products';
    await page.waitForSelector(productsSelector);
    await page.screenshot({ path: `${screenshotsDirPath}${SCREENSHOT.products}` });
  }, WAIT_FOR);`

The above code works just fine.

> And I've just removed `page.waitForSelector()` and added `page.waitFor()` as first statement.
Is that something?

**Comment by aslushnikov** [comment]
Please re-file with a reproducible script I can play with. Otherwise, we won't be able to help.
