### ISSUE TITLE
Page.metrics() returns mutated data after refresh/redirect

### ISSUE THREAD

**Issue by mgolawski** [puppeteer/puppeteer#2513]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Mac
* Node.js version: v9.11

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. call page.metrics();
2. reload page
3. call page.metrics();

**What is the expected result?**
Values presented inside `page.metrics()` object are sums of all actions performed inside single page object. For example after reload, `page.metrics()` will return sum of LayoutCounts for initial page load, and LayoutCounts for page load after `reload`. In such case, every next redirect/reload will mutate performance data, and we can't gather performance data for different subdomains. We need to recreate page object, or calculate that manually. Is there any possibility to reset that values in performance data object?

**What happens instead?**
I would assume that after every redirect/refresh, performance object is cleared. Other trade-off is possibility to clear that object manually. What do you think about that?

**Comment by harpet06** [comment]
Anyone found any work arounds for this?
