### ISSUE TITLE
$eval can't find existing selector

### ISSUE THREAD

**Issue by samuelsh** [puppeteer/puppeteer#2516]
* Puppeteer version: 1.3
* Platform / OS version: MacOS Sierra
* URLs (if applicable): https://archive.kbb1.com/lessons
* Node.js version: 9.0.8

I'm attempting to clear two input fields that contain dates range.
Following code snippet clears first input field but fails to clear the second:
```javascript
            await page.$eval("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(1) > div > input[type=\"text\"]", (selector) => {
                selector.value = "";
            });
            await page.$eval("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input[type=\"text\"]", (selector) => {
                selector.value = "";
            });

``` 
Steps to reproduce:
```javascript
            await page.goto('https://archive.kbb1.com/lessons', {waitUntil: 'networkidle2'});
            // Clicking on Date filter
            // Click Apply and check if filter tag is created
            await Promise.all([
                await page.click(".ui.blue.large.pointing.secondary.index-filters.menu div a:nth-child(4)"),
                page.waitForSelector("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input")
            ]);

            await page.$eval("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(1) > div > input[type=\"text\"]", (selector) => {
                selector.value = "";
            });
            await page.$eval("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input[type=\"text\"]", (selector) => {
                selector.value = "";
            });

```
After executing following snippet, start date range field will be empty, but end date range field will still contain old date

**Comment by mboeser** [comment]
you can use page.evaluate() and manually call the function. I've done this before when running into issues with the $eval and $$ eval methods.

`page.evaluate(document.querySelector('div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input').value='')`

also have you tried using page.type() and setting the value that way?

**Comment by samuelsh** [comment]
Thanks @mboeser .
`page.evaluate` failed with error: "ReferenceError: document is not defined"
`page.type` indeed working, so I ended up with following dirty hack :)
```javascript
            await page.focus("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input[type=\"text\"]");
            for (let i = 0; i < 15; i++)
                await page.keyboard.press('Backspace');
            await page.type("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input[type=\"text\"]", "05/12/2010");
```

Of course it's not optimal, so waiting for $eval to be fixed :)

**Comment by mboeser** [comment]
might be a good idea to use `page.waitForSelector` since the element only appear once there's interaction within the page and then call the next command on that element to ensure it's available when executing that code. Lately I've been appending a catch to all my awaits when debugging. `await page.evaluate(document.querySelector('div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input').value='').catch((e)=>{console.error(e)});` Hope this helps.

**Comment by aslushnikov** [comment]
@samuelsh the following script is working just fine for me on pptr 1.4.0:

```js
const puppeteer = require('puppeteer');

;(async () => {
  const browser = await puppeteer.launch({headless: false})
  const page = await browser.newPage()
  await page.goto('https://archive.kbb1.com/lessons', {waitUntil: 'networkidle2'});
  // Clicking on Date filter
  // Click Apply and check if filter tag is created
  await Promise.all([
      await page.click(".ui.blue.large.pointing.secondary.index-filters.menu div a:nth-child(4)"),
      page.waitForSelector("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input")
  ]);

  await page.$eval("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(1) > div > input[type=\"text\"]", (selector) => {
      selector.value = "";
  });
  await page.$eval("div.five.wide.column > div.ui.grid > div:nth-child(2) > div:nth-child(2) > div > input[type=\"text\"]", (selector) => {
      selector.value = "";
  });
})()
```

I'll speculatively close this. If it still fails for you, please post here your repro and I'll look into it.

**Comment by zhaoqize** [comment]
I also encountered the same problem.
use `page.evaluate` print error `document is not defined`.
But I use `page.evaluateHandle` fixed it.
