### ISSUE TITLE
AddScriptTagOptions suggest support "nonce" attribute

### ISSUE THREAD

**Issue by skyyearxp** [puppeteer/puppeteer#2518]
some site use nonce attribute, if without this attribute, addscripttag will fail. chrome will show error in console.

now i insert by hand.
var jq = document.createElement('script');
jq.setAttribute('nonce',document.scripts[0].nonce);
jq.setAttribute('type','text/javascript');

**Comment by aslushnikov** [comment]
@skyyearxp there's a `page.setBypassCSP` that should help dealing with this usecase.
