### ISSUE TITLE
Linux Ubuntu 18.04 - Invalid file descriptor to ICU data received

### ISSUE THREAD

**Issue by rbuckland** [puppeteer/puppeteer#2519]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: 1.3.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable): 
* Node.js version: v8.10.0

**What steps will reproduce the problem?**
Fresh install, and running puppeteer to produce PDFs

**What is the expected result?**
Puppeteer runs and exports a PDF

**What happens instead?**
It errors with the following exception.

```
[0509/163819.806050:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
[0509/163819.806212:FATAL:content_main_delegate.cc(53)] Check failed: false. 
#0 0x56341d486b0c base::debug::StackTrace::StackTrace()
#1 0x56341d49f780 logging::LogMessage::~LogMessage()
#2 0x56341b828d23 content::ContentMainDelegate::TerminateForFatalInitializationError()
#3 0x56341d1c1deb content::ContentMainRunnerImpl::Initialize()
#4 0x56341d1cbb72 service_manager::Main()
#5 0x56341d1c0f14 content::ContentMain()
#6 0x5634212d09b9 headless::(anonymous namespace)::RunContentMain()
#7 0x5634212d0a42 headless::HeadlessBrowserMain()
#8 0x56341d1c8f9d headless::HeadlessShellMain()
#9 0x56341b8271ac ChromeMain
#10 0x7fc2dd77ab97 __libc_start_main
#11 0x56341b82702a _start
```

I have also resolved the issue - see the next comment.

**Comment by rbuckland** [comment]
The issue is permissions of the directories/files.

When puppeteer was installed, the permissions were default owner of `nobody:<usergroup>` but not all files had group or others bits set (i.e. 600 or 700)
Puppeteer was installed as `npm install -g puppeteer` and it is run as the local user.

The fix was to chmod the files to set the group and others bits to match the "users".

I left the ownership as what it was - `nobody:<usergroup>`

* 755 for directories
* 755 for executable files
* 644 for all other files

I am unsure if the `nobody:<usergroup>` ownership is a bad situation.

```
cd /usr/local/lib/node_modules/puppeteer/.local-chromium
find . -type d | xargs -L1 -Ixx sudo chmod 755 xx
find . -type f -perm /u+x | xargs -L1 -Ixx sudo chmod 755 xx
find . -type f -not -perm /u+x | xargs -L1 -Ixx sudo chmod 644 xx
```

**Comment by someguy9** [comment]
Just a heads up I had to use -perm on the commands above but this worked! thank you!!!

**Comment by rbuckland** [comment]
fixed @someguy9 thanks. (typed from memory)
