### ISSUE TITLE
Question：How to click a hidden element ？

### ISSUE THREAD

**Issue by dupingwei** [puppeteer/puppeteer#2525]
After ```page.hover``` triggers div display, calling ```page.click``` again prompts errors.

Error: Node is either not visible or not an HTMLElement

----

Or how to operate the attribute of the HTMLElement？

**Comment by vsemozhetbyt** [comment]
> Or how to operate the attribute of the HTMLElement？

See https://github.com/GoogleChrome/puppeteer/issues/2514
