### ISSUE TITLE
How do you click using page function?

### ISSUE THREAD

**Issue by finlay422** [puppeteer/puppeteer#2526]
I want to click this button

```<button class="_qv64e">Sign up</button>```

but the class is not unique.
In the browser console I can select using this 

```document.querySelectorAll('._qv64e')[1])```

can someone tell me how I can do something like this:
```await page.click(document.querySelectorAll('._qv64e')[1]);```

**Comment by vsemozhetbyt** [comment]
Try:
```js
await page.evaluate(() => { document.querySelector('._qv64e')[1].click(); });
```

**Comment by yanivefraim** [comment]
@vsemozhetbyt - I believe you meant: (using querySelectorAll, and not querySelector)

```js
await page.evaluate(() => { document.querySelectorAll('._qv64e')[1].click(); });
```

One more option (pretty much the same):

```js
await page.$$eval('._qv64e', elements => elements[1].click());
```

**Comment by finlay422** [comment]
Thanks so much guys, absolute legends.

**Comment by spanwair** [comment]
if you would like to you some variable selector 
`await page.evaluate((indexOfTimeFrom) => document.querySelectorAll('div.price button')[indexOfTimeFrom].click(), indexOfTimeFrom);`

**Comment by ecolss** [comment]
> @vsemozhetbyt - I believe you meant: (using querySelectorAll, and not querySelector)
> 
> ```js
> await page.evaluate(() => { document.querySelectorAll('._qv64e')[1].click(); });
> ```
> 
> One more option (pretty much the same):
> 
> ```js
> await page.$$eval('._qv64e', elements => elements[1].click());
> ```

Hey @yanivefraim, great thanks to your code example.

I've been always wondering, what's the difference between `evaluate` vs `$$eval`, seems either could replace the other.
Could you please give us some examples on the difference between the two?

**Comment by rohitnairtech** [comment]
> > @vsemozhetbyt - I believe you meant: (using querySelectorAll, and not querySelector)
> > ```js
> > await page.evaluate(() => { document.querySelectorAll('._qv64e')[1].click(); });
> > ```
> > 
> > 
> > One more option (pretty much the same):
> > ```js
> > await page.$$eval('._qv64e', elements => elements[1].click());
> > ```
> 
> Hey @yanivefraim, great thanks to your code example.
> 
> I've been always wondering, what's the difference between `evaluate` vs `$$eval`, seems either could replace the other.
> Could you please give us some examples on the difference between the two?

Hey @ecolss 

- `page.evaluate` is a raw method with a callback wherein you can specify what you want to do with the whole page, you could use `querySelectorAll` or `querySelector` basically takes the page context.

- `page.$eval` is a method which accepts the selector as one of the args, applies `querySelector` on it and picks up the first element that matches the selector.

- `page.$$eval` does the same things as `page.$eval` only that it applies `querySelectorAll` on the selector passed and returns an array of elements that match the selector.

This is the key differences, to the best of my knowledge.

Also, another way of doing this would be - 
```javascript
  const selectAll = await page.$$('._qv64e');
  await selectAll[2].click();
```

Happy automation!
