### ISSUE TITLE
page.setCacheEnable(false) not working.

### ISSUE THREAD

**Issue by lili21** [puppeteer/puppeteer#2527]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  1.4.0
* Platform / OS version: macOS 10.13.0
* URLs (if applicable): -
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

*source code*

```javascript
const puppeteer = require('puppeteer')

const NETWORK_PRESETS = require('./network-presets')

;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  const client = await page.target().createCDPSession()

  // emulate 3g network
  await client.send('Network.emulateNetworkConditions', NETWORK_PRESETS.Regular4G)
  // throttle cpu
  await client.send('Emulation.setCPUThrottlingRate', { rate: 4 })

  await page.setCacheEnabled(false)

  for (let i = 0;i < 10;i++) {
    await page.goto('https://google.com')

    const timing = JSON.parse(
      await page.evaluate(() => JSON.stringify(window.performance.timing))
    )

    console.log(timing.loadEventEnd - timing.navigationStart)
  }
  
  await browser.close()
})()
```

**What is the expected result?**

output timing should be more close to the first value which has no cache.

**What happens instead?**

![image](https://user-images.githubusercontent.com/4456380/39861426-1ec11838-5473-11e8-8c90-1d834e61e4d0.png)

looks like still have the cache.

**Comment by lili21** [comment]
I also tries `client.send('Network.setCacheDisabled', { cacheDisabled: true })` and `client.send('Network.clearBrowserCache')`.

**Comment by aslushnikov** [comment]
@lili21  I tried running the following script:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()

  await page.setCacheEnabled(false)

  let responses = [];
  page.on('response', r => responses.push(r));
  for (let i = 0;i < 10;i++) {
    responses = [];
    await page.goto('https://google.com')

    const timing = JSON.parse(
      await page.evaluate(() => JSON.stringify(window.performance.timing))
    )

    console.log(timing.loadEventEnd - timing.navigationStart)
    for (const r of responses) {
      if (r.fromCache())
        console.log('  CACHED: ' + r.url());
    }
  }

  await browser.close()
})()
```

Only base64 images are technically coming from cache - and that's expected.

Timing is indeed very different on first and subsequent calls. One of the reasons might be that initial navigation causes a process swap (the page is navigated to a different security origin), which contributes significantly to the timing discrepancy. There are also other factors, like initial memory allocation for the page.

Hope this helps.
