### ISSUE TITLE
Can't access a frame or framesets within a frame. 

### ISSUE THREAD

**Issue by davidawad** [puppeteer/puppeteer#2528]
* Puppeteer version:     "puppeteer": "^1.4.0"
* Platform / OS version: OSX : High Sierra
* URLs (if applicable): None 
* Node.js version: node --version v10.1.0

I need help navigating to a frame within a frame (potentially any number of levels of frames could be nested). 

There seem to be a lot of issues relating to accessing frames in a page and I can't find a clear answer to what feels like a straightforward use case.

I have a frame within a frameset within a frame within the dom. I need to fill out a form within that lower level frame. But I can't seem to access it or change the "page" context to that sub frame even though I can access the top level frame.

Ideally perhaps something like this : 
```js
const frame = page.frames()[1];
console.log(frame.frames()) // hangs pupeteer and fails? 
```

I can't change anything about the architecture of the pages right now, but my question is really that I want some more clarity about what pupeteer can and can't do. 

I would ideally like the ability to do what i described above. Just access the `frame` object as a subsequent `page` object. 

Is there some documentation I'm missing because this feels straightforward. I am however working with some old technology so i'm not expecting too much information to be out there. All I've been able to find is workarounds on the related issues and nothing particularly clear. 

Thanks in advance for any help! 

Related Issues and Questions : 
- [here](https://stackoverflow.com/questions/46529201/puppeteer-how-to-fill-form-that-is-inside-an-iframe?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
- [here](https://github.com/GoogleChrome/puppeteer/issues/684) #684
- [here](https://github.com/GoogleChrome/puppeteer/issues/440) #440

**Comment by ChristosChristofidis** [comment]
try this `const frame = (await page.frames())[1];`

`console.log(await frame.frames())`

**Comment by davidawad** [comment]
@ChristosChristofidis thanks for the help!  

So this doesn't seem to work the way i'm expecting it to. 

Here's an example of the frames i'm trying to get through. 

```
<!-- index.html--> 
<frameset framespacing="0" border="false" frameborder="0" cols="160,*">
  <frame name="menu" src="removed">

  <frameset framespacing="0" border="false" rows="*,250">
     <frame name="main" scrolling="no" src="removed">
     <frame name="logo" scrolling="no" src="/removed">
  </frameset>

```



So i'm trying to get through that with the following chrome headless script.

`tests.js`

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('removed');

  await page.waitFor(1000)

  await page.screenshot({path: 'screenshot_1.png'});

  const frame = (await page.frames())[1];

  console.log(frame['_name'])

  const frame2 = (await page.frames())[1];

  console.log(frame2['_name'])

  const frame3 = (await page.frames())[1];

  console.log(frame3['_name'])

  // do page login
  await page.focus('input[name="id"]')
  page.type('david')


  await page.screenshot({path: 'screenshot_2.png'});


  await browser.close();
})();

```


What I **expect** is that i can access the first sub frame with each successive call of `.frames()` but it doesn't seem like this is working with multiple nested `frameset` tags. 

instead what seems to happen is this: 

```
$ node tests.js 
menu
menu
menu

```

Hopefully it's clear what I mean here and thanks for any help you can give me.

**Comment by ChristosChristofidis** [comment]
of the top of my head im not sure what the exact snippet would be to get what you want but,

frame frame2 frame3 will always be the same frame, as nothing changes inbetween right?


(await page.frames())[0] this is the mainframe
(await page.frames())[1] this is the first frame of the mainframe
(await page.frames())[2] this is the second frame of the mainframe
(await (await page.frames()[1].**childFrames**())[0] would be the first frame of the first frame of the mainframe


https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-frame

**Comment by aslushnikov** [comment]
@davidawad frame structure is not flattened; frames have subframes, so you should query frame's children when you want to get them.

P.S. there's also a `frame.name()` that you can use instead of reaching out for a private `frame['name']`.

**Comment by davidawad** [comment]
doh. thank you guys. 

I thought that the frameset tag was what was throwing this off but it turns out i'm a fool. 

Thanks for the help .
