### ISSUE TITLE
headless:true and widevine component: How to make it work?

### ISSUE THREAD

**Issue by hmpmarketing** [puppeteer/puppeteer#2529]
I have been trying to load a page that requires widevine on headless mode, it does not work at all, page requests that component is present. If running headless:false, it works as expected. I am wondering if there are any chrome flags that needs to be enabled.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.30
* Platform / OS version: Mac OS - Chrome Canary
* Node.js version: 9.3

**What steps will reproduce the problem?**

Try to launch in headless mode and visit a page that needs widevine, page requests to enable plugin

_Please include code that reproduces the issue._

let options = {
  headless:true ,
  ignoreDefaultArgs:true,
}

puppeteer.launch(options).then(async browser => {
  const page = await browser.newPage();
  await page.goto('http://www.pagethatneedswidevine.com');

});

**What is the expected result?**

Audio should play

**What happens instead?**

Page requests that widevine component is installed

**Comment by aslushnikov** [comment]
@hmpmarketing I don't know anything about widevine; I'd try asking this question on chromium-dev google group.

**Comment by hmpmarketing** [comment]
Thanks, if possible update on the issue

**Comment by demian85** [comment]
Any news on this? I want to play audio and only `headless: false` makes it work.

**Comment by beaufortfrancois** [comment]
I've started a thread at https://groups.google.com/a/chromium.org/forum/#!topic/headless-dev/bI_YSrdUlV4 to discuss this. Please share your use cases over there.
