### ISSUE TITLE
`waitForNavigation` never resolves if a `click` opens a new page/tab

### ISSUE THREAD

**Issue by dominikwilkowski** [puppeteer/puppeteer#2533]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: macOS 10.12.6
* URLs (if applicable): https://stackoverflow.com/
* Node.js version: 8.9.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch({ headless: false });

	const page = await browser.newPage();
	await page.setExtraHTTPHeaders({ 'user-agent': 'thinkmill' });
	await page.setCacheEnabled( false );

	const url = 'https://stackoverflow.com/';

	await page.goto( url, { 'waitUntil' : 'networkidle0' } );

	await Promise.all([
		page.waitForNavigation({ waitUntil: 'networkidle0' }),
		page.click('a[href="https://stackexchange.com/legal/privacy-policy"]'),
	]);

	await browser.close();
})();
```

**What is the expected result?**
The script should resolve after the new tab has been created and all resources are loaded. I can see the script opening a new tab via the click and I can see the page completely loads.

**What happens instead?**
Script never resolves.

**Comment by marijanlekic** [comment]
This should be for the new page and not for the page where the link is:
`page.waitForNavigation({ waitUntil: 'networkidle0' }),`

Despite of that, you have got an exception because "page" is successfully loaded (navigation is finished) and after that you dont have any navigation on that page but you have this promise:
`await page.waitForNavigation({ waitUntil: 'networkidle0' }),`
You will get "Navigation Timeout Exceeded:" exception but i am not sure if its a desired behavior.

**Comment by dominikwilkowski** [comment]
Of course, that makes sense :) Thanks for that.
So simply changing my script to this made it work.

```js
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch({ headless: false });

	const page = await browser.newPage();
	await page.setExtraHTTPHeaders({ 'user-agent': 'thinkmill' });
	await page.setCacheEnabled( false );

	const url = 'https://stackoverflow.com/';

	await page.goto( url, { 'waitUntil' : 'networkidle0' } );
	await page.click('a[href="https://stackexchange.com/legal/privacy-policy"]');

	await browser.close();
})();
```
