### ISSUE TITLE
How do I get the CSS selector of <a> element when I known it's link?

### ISSUE THREAD

**Issue by cuongceopro** [puppeteer/puppeteer#2535]
**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: OS X El Capital 10.11.6

`<div>`
 `<ul>`
    `<li><a href="/test1">Test 1</a></li>`
    `<li><a href="/test2">Test 2</a></li>`
    `<li><a href="/test3">Test 3</a></li>`
    `<li><a href="/test4">Test 4</a></li>`
  `</ul>`
`</div>`

Can someone tell me how can I get the CSS selector of element which holds href "/test2" in above HTML?
Thanks.

**Comment by vsemozhetbyt** [comment]
Try:
```js
await page.evaluate(() => { const element = document.querySelector('a[href="/test2"]'); });
```
or:
```js
const elementHandle = await page.$('a[href="/test2"]');
```

**Comment by akhilaksaju** [comment]
Is there any API to find the css selector of a node if I know the node?

**Comment by vsemozhetbyt** [comment]
It seems there is no somple way: https://github.com/ChromeDevTools/devtools-protocol/issues/158
