### ISSUE TITLE
browser.newPage never resolves when using `userDataDir`

### ISSUE THREAD

**Issue by laggingreflex** [puppeteer/puppeteer#2538]
`browser.newPage()` never resolve when using `userDataDir` in launch options. 

Strangely, it only works when using `headless: false`. 

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: 10.0

**What steps will reproduce the problem?**

```js
  const browser = await puppeteer.launch({
    // headless: false, // un-commenting this makes it works
    userDataDir: 'test-profile-dir',
  });
  await browser.newPage();
  // Never reaches here
  console.log('If this logs, it worked!');
```

_Please include code that reproduces the issue._

https://github.com/laggingreflex/puppeteer-userDataDir-hang

**What is the expected result?**

`browser.newPage()` should resolve and above code should be able to reach `console.log` statement

**What happens instead?**

It doesn't

**Comment by vsemozhetbyt** [comment]
Can reproduce with Tip-Of-Tree (1.4.0-post, chromium_revision 557152) on Windows 7 x64.

**Comment by laggingreflex** [comment]
It also seems to work when full path is provided: `__dirname + '/test-profile-dir'`

**Comment by beaumartinez** [comment]
Still happens in latest version (`^1.7.0`).

**Comment by truchonh** [comment]
Happens to me too with version 1.12.1 on Windows with the chromium version that installs with it.

If I don't use the 'userDataDir' property OR start it with 'headless': false, everything works fine.

EDIT: Nevermind, using a absolute path for userDataDir solved my issue. Still wierd that setting headless: false makes it work with a relative path..

**Comment by derekyle** [comment]
Just for anyone's reference, this issue still presents itself in version 1.20.0. When headless = true, then you must provide a full path instead of a relative one for userDataDir. In the case of headless = false, it works fine with both full and relative paths.

**Comment by aldarund** [comment]
ye, full path is needed, but funny enough with relative path it still will create taht folder properly and put there crashreport on close

**Comment by nicolas-t** [comment]
Hello,

Still happenning with v3.0.
Luckily absolute path solves the issue. 
Maybe docs should explain the trick, it can be confusing since it works with `headless: false`


----

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.1
* Platform / OS version: win7
* Node.js version: v12.11.1

**What steps will reproduce the problem?**

Run this code : 

```js 
const puppeteer = require('puppeteer');
(async() => {
    console.log('a')
    const browser = await puppeteer.launch({
        userDataDir: 'userDataDir',
        headless: true,
    })
    console.log('b')
    await browser.newPage()
    console.log('c')
    await browser.close()
})();

```

**What is the expected result?**

```
a
b
c
```

**What happens instead?**

```
a
b
```
It never outputs `c`, browser freezes on new page creation.

If you remove `userDataDir: 'userDataDir'` it works as expected.   
If you set `userDataDir: __dirname + '/userDataDir'` it works as expected.   
If you set `headless: false` it works as expected.

**Comment by zNoobs** [comment]
I had the same problem, I think the problem is when you use "/" in the path when the headless = true.
Puppeteer 3.0.0 on Windows 7 64 bit, using the default Chromium, launching the browser with headless true:
```
let launchOptions = {};
launchOptions.headless = true;
launchOptions.userDataDir = "C:/test/temp"
let browser = await puppeteer.launch(launchOptions);
let page = await this.browser.newPage();//freezes here depending on the path
```
It works if userDataDir is: 
```
- launchOptions.userDataDir = "C:\\test\\temp"
- launchOptions.userDataDir = "C:\\test/temp"
- launchOptions.userDataDir = "C:\\test//temp"
```

It doesn't work with:
```
- launchOptions.userDataDir = "C:/test/temp"
- launchOptions.userDataDir = "C://test//temp"
```

With headless = false, all the paths work.
We should use 2 backslashes after the disk letter and the colon for an absolute path.

Edit:
Using path.normalize(yourPath) will return a correct absolute path for userDataDir:
```
const path = require('path');
launchOptions.userDataDir = path.normalize("C://test//temp");//returns a valid "C:\test\temp"
```

**Comment by voxsoftware** [comment]
I have same problem on windows 10, and path.normalize not solve the issue. 
Any ideas?

**Comment by innovaweb-dev** [comment]
Same problem

My environnement dev

 - WSL2 Debian Buster 
 - Node v12.18.1 
 - npm 7.5.4
 - Puppeteer 8.0.0

``` javascript
const browser = await puppeteer.launch();
console.log(await browser.version()); //HeadlessChrome/90.0.4427.0 
const page = await browser.newPage(); //after it does nothing
```

I tried with different configuration : 
```
userDataDir: './chrome' //no change
pipe : true //no change
args: ['--no-sandbox', '--disable-setuid-sandbox',] //no change
```

Here the debug (six last lines) :
```
  puppeteer:protocol:RECV ◀ {"id":4,"result":{"sessionId":"B3D2567E07203D4A096A495710466966"}} +0ms
  puppeteer:protocol:SEND ► {"sessionId":"B3D2567E07203D4A096A495710466966","method":"Page.enable","params":{},"id":5} +1ms
  puppeteer:protocol:SEND ► {"sessionId":"B3D2567E07203D4A096A495710466966","method":"Page.getFrameTree","params":{},"id":6} +1ms
  puppeteer:protocol:SEND ► {"sessionId":"B3D2567E07203D4A096A495710466966","method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":false,"flatten":true},"id
":7} +0ms
  puppeteer:protocol:SEND ► {"sessionId":"B3D2567E07203D4A096A495710466966","method":"Performance.enable","params":{},"id":8} +0ms
  puppeteer:protocol:SEND ► {"sessionId":"B3D2567E07203D4A096A495710466966","method":"Log.enable","params":{},"id":9} +0ms
```

**Comment by innovaweb-dev** [comment]
I have fix my issue 

```javascript
const browser = await puppeteer.launch({
    dumpio: true, // to display log
    args: ['--disable-gpu'] // to fix issue of .newPage()
});
```
https://github.com/puppeteer/puppeteer/issues/1543#issuecomment-349642975 
https://github.com/microsoft/playwright/issues/4761#issue-770834723

**Comment by lengband** [comment]
> I have fix my issue
> 
> ```js
> const browser = await puppeteer.launch({
>     dumpio: true, // to display log
>     args: ['--disable-gpu'] // to fix issue of .newPage()
> });
> ```
> 
> [#1543 (comment)](https://github.com/puppeteer/puppeteer/issues/1543#issuecomment-349642975) [microsoft/playwright#4761 (comment)](https://github.com/microsoft/playwright/issues/4761#issue-770834723)

Good Idea!
