### ISSUE TITLE
Why 'setCookie' not effect

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#2539]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: windows 10
* URLs (if applicable):
* Node.js version:8.9.3

**What steps will reproduce the problem?**
Hello guys, recently, i use puppeteer to set some cookie in some website,  and i watch the dev-tools in chromium with network panel, but i can't find the cookie data in request header. I don't know whether I have wrong coding or not. Please check.

1.

```
>  for (let item in newCookieGroup) {
>         if (newCookieGroup[item] instanceof Array) {
>             for (let nItem in newCookieGroup[item]) {
>                 cookieMap.push({
>                     name: item.toString(),
>                     value: '' + newCookieGroup[item][nItem],
>                     url: url,
>                 });
>             }
>             continue;
>         }
>         cookieMap.push({
>             name: item.toString(),
>             value: '' + newCookieGroup[item],
>             url: url
>         });
>     }
>  return cookieMap;
```

2. (cookieMap is param)

```
>  (async () => {
>         const browser = await puppeteer.launch({
>             ignoreHTTPSErrors: true,
>             devtools: true,
>             slowMo: 200,
>             args: ['--no-sandbox']
>         });
>         const page = await browser.newPage();
>         const client = await page.target().createCDPSession();
>         await client.send('Network.enable');
>         for (let item in cookieMap) {
>             const setCookie = await client.send('Network.setCookie', cookieMap[item]);
>             console.log("item:" + setCookie.success);
>         }
>    ......
> )
> 

```
**What is the expected result?**

the cookie can be set in request header.

**What happens instead?**

the cookie can't  be set in request header.

**Comment by aslushnikov** [comment]
> I don't know whether I have wrong coding or not. Please check.

Please, ask these kind of questions on [StackOverflow](https://stackoverflow.com/questions/tagged/puppeteer).
