### ISSUE TITLE
Latest versions of puppeteer do not work on Mac OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by ccampbell** [puppeteer/puppeteer#2542]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Mac OS X 10.9 Mavericks
* Node.js version: 10.1.0

**What steps will reproduce the problem?**

This is definitely not super pressing, but my MacBook Pro is in for service so I am stuck using my old MacBook Air which is still running Mavericks. Chromium support for Mac OS X 10.9 stopped with Chrome 66, which means the latest version of puppeteer does not work at all. I believe version 1.1.1 is the last version that works on Mavericks. 

I don’t know if there is anything that can even be done about this. Using an older Chromium build on a newer version of puppeteer could in theory have issues if the API has changed, and there is no way in package.json to specify to use a different version based on the OS that I know of to fix it on my end.

**Comment by aslushnikov** [comment]
Yeah, the way to go is to use pptr 1.1.1. I don't think there's anything we can do here; that's a lack of flexibility on the NPM side.
