### ISSUE TITLE
Method waitForSelector(); no found selector after instructions timeout: 0;

### ISSUE THREAD

**Issue by vrg-success** [puppeteer/puppeteer#2546]
Hello everyone 👋, I found a problem when I put a certain timeout on `page.waitForSelector();`  everything is fine, but when I put the infinite - timeout: 0;  it does not find the selector, what is the reason? very interesting.....

**Comment by 15531400827** [comment]
我也遇到这个问题，它卡在那里了，求解

**Comment by aslushnikov** [comment]
There's no codepath in pptr I'm aware of that can cause this behavior. Please, refile with a good repro so that we can take a look.
