### ISSUE TITLE
Annoying "Assertion failed" logs even when error is handled

### ISSUE THREAD

**Issue by felixfbecker** [puppeteer/puppeteer#2547]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Node.js version: 10.0.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Have a test that runs `page.click('.selector-that-does-not-exist')`

**What is the expected result?**

It should throw an Error that can be caught and not log anything to `console`

**What happens instead?**

`Assertion failed: No node found for selector:` is logged.

This is due to the use of `console.assert()` in the code: https://github.com/GoogleChrome/puppeteer/blob/3b03ff65c7b369debfcaa67a8673fba105a2d20d/lib/FrameManager.js#L594

In my case, I have to click a button that may or may not be there, so I would like to wrap the call to `click()` in a `try/catch` and ignore the `No node found` error. But even though the error is caught, this line is still logged. The logline doesn't expose any more information than the error. But it spams the test log with red herrings for tests that are passing:

```
      file tree
Assertion failed: No node found for selector: .toast__close-button
        ✓ does navigation on file click
Assertion failed: No node found for selector: .toast__close-button
        ✓ expands directory on row click (no navigation)
Assertion failed: No node found for selector: .toast__close-button
        ✓ does navigation on directory row click
Assertion failed: No node found for selector: .toast__close-button
```

Error handling should be in control of the caller of `click()`, which may chose to log the error (which any test framework would do for you if it is not caught).

**Comment by aslushnikov** [comment]
That's a good point. Also, Node 10 stopped thowing AssertionError when `console.assert` fails, so we should migrate to throwing errors explicitly (both in pptr and in our testrunner).
