### ISSUE TITLE
How to get the request initiator attribute with puppeteer?

### ISSUE THREAD

**Issue by phackt** [puppeteer/puppeteer#2549]
Hello guys, 
I can not find how to get the initiator attribute of a request.

Ex of information that we can find in Chrome:
![image](https://user-images.githubusercontent.com/19553457/40042923-3581dc16-5823-11e8-88a5-98a56f21549b.png)

Do you have any idea ?
Thanks in advance,

**Comment by aslushnikov** [comment]
Dupe of #1395.
