### ISSUE TITLE
the params of function exposed by exposeFunction cannot have function type

### ISSUE THREAD

**Issue by XHMM** [puppeteer/puppeteer#2551]
**Example is below :**
```js
await page.exposeFunction('test',function test(a,b){
    console.log(a, b); 
});
await page.evaluate(async ()=>{
  test(1, function a(){}); // will output  " 1 null "
})
```
puppeteer version : 1.4.0

So how should i do to pass a function as param to an exposedFunction ?

**Comment by vsemozhetbyt** [comment]
If I understand correctly, arguments are transferred via JSON, so we can only send code string and recreate the function from this string.

**Comment by XHMM** [comment]
I tried below , maybe you are correct.
```js
await page.evaluate(async ()=>{
  test(1,JSON.stringify( function a(){})); // output  is still " 1 null "
})
```
So , is there some ways to achieve passing function ?

**Comment by vsemozhetbyt** [comment]
Something like this?
```js
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.exposeFunction('test', function test(a, b){
      console.log(a, eval(`(${b})`));
    });

    await page.evaluate(async ()=>{
      test(1, (function a(){}).toString());
    })

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
1 [Function: a]
```

**Comment by aslushnikov** [comment]
Note: these values are crossing the process boundary, so there's no good way we can transfer a function with a closure scope.

**Comment by mkoo21** [comment]
I had some use cases where I wanted to be able to pass a closure to be executed within the page context. I was able to achieve this by using page.$$eval; how is it achieved there?
