### ISSUE TITLE
Different results for PDF generation (local[windows] vs live[centos])

### ISSUE THREAD

**Issue by shreyas14oct** [puppeteer/puppeteer#2554]
Hi,

I am using puppeteer to generate pdf, with following development environment:

**Local environment:**
* Puppeteer version: 1.3.0
* Platform / OS version: Windows 10
* Node.js version: v8.11.11

**Server environment:**
* Puppeteer version: 1.3.0
* Platform / OS version: CentOS Linux release 7.4.1708 (Core)
* Node.js version: v8.11.11

The issue i am facing is that the PDf generated from server is large in size and also font won't load.
The results are as below PDFs.
 
[fromlocal.pdf](https://github.com/GoogleChrome/puppeteer/files/2007966/fromlocal.pdf)
[fromserver.pdf](https://github.com/GoogleChrome/puppeteer/files/2007967/fromserver.pdf)

Please note the below HTML is being copied form the html file i am being using to create PDF (as URL).
[I am using URL for page.goto to generate PDF].

```
<html>
 <body>
 FOOOO <span style="font-family: Impact, Charcoal">impact</span>
 <span style="font-family: 'Courier New', Courier, monospace">courier</span>
 </body>
 </html>
```
I anything missing in the environment, i am kind of novice for Centos (if anything missing).
Please help, as i am unable to find out what is missing here.

**What is the expected result?**
The PDF created over local and server should be the same. Same font and size for the same code.

**What happens instead?**
The server PDf generated is larger than local and do not load PDF.

**Comment by CaelanStewart** [comment]
The fonts are potentially because it doesn't come preloaded with Courier and Impact, which I believe I Microsoft fonts and nonfree, and therefore would not be included with CentOS.

As for the file size different, I'm not sure. Purely speculative: the different is pretty small, add some images and other large stuff and see if you see the same ratio in size difference, my guess is the renderer itself is different platform to platform, and so you'll get some minor format differences internally in the PDF.

**Comment by aslushnikov** [comment]
@shreyas14oct you're trying to achieve a consistent cross-platform rendering - which is an uphill battle. Chrome uses underlying platform for some specific tasks, e.g. to resolve and render text, and different platforms do it differently. 

As a result, the PDFs are different.

**Comment by CaelanStewart** [comment]
@shreyas14oct, if you have not looked into it yet, I urge you to research Vagrant or an alternative if you really want to develop on Windows. You can run your app from within a VM running Linux, and build the app on the Windows side using shared folders/networks between the host and guest OS, therefore achieving local/prod env parity.
