### ISSUE TITLE
Excel File download triggered by a button click in headless mode not working

### ISSUE THREAD

**Issue by DrisyaNairJ** [puppeteer/puppeteer#2555]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Node.js version: 8.10.0

**What steps will reproduce the problem?**

I'm trying to do a file download(excel file) from my page, triggered by a button click, in 'headless : true' mode, using the below code,

await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: './downloadFolder'});

And its seems it didn't do anything, file is not getting downloaded. 

The same worked if i change that to 'headless : false' (downloads to chrome's download directory), also it works even without this code.

**Comment by aslushnikov** [comment]
There's no good way to download files atm; see #299.
