### ISSUE TITLE
No SVG rendering in PDF

### ISSUE THREAD

**Issue by actuallymentor** [puppeteer/puppeteer#2556]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.1.0
* Platform / OS version: Mac OSX
* URLs (if applicable): N/A
* Node.js version: v10.0.0

**What steps will reproduce the problem?**

1. Generate html with local jpg and svg images (not inline)
2. View in chrome: everything ok
3. html > pdf with puppeteer

Puppeteer pdf config: 

```js
{
	title: meta.title,
	printBackground: true,
	format: 'A4 landscape'
}
```

**What is the expected result?**

Expected result is a pdf with rendered SVG images. This happens when I manually save as PDF in chrome.

**What happens instead?**

SVG images are not rendered. Jpgs work fine though, so it doesn't appear to be a path issue.

**Comment by CaelanStewart** [comment]
I've been having the same problem, the issue was happening across multiple environments, local and staging.

Except I had one SVG that did render, and one that did not. All SVGs looked fine when viewing the page in Chrome, but didn't work when rendering to PDF using Puppeteer's API.

Looking at the differences, one was using CSS to style the SVG, and the other used presentation attributes.

I opened the problem SVG in Illustrator, and exported it as basic SVG 1.1, fonts outlined, presenation attributes, not responsive, and then it SVG worked.

I tried a few other permutations of the SVG export options, and of them worked, however, some only worked if a at least one explicit dimension was set on the SVG. And one, when set at 100% height was so rendered so large that only a part of the left corner of the SVG was visible in the rendered PDF, mainly whitespace was visible. So it may be that the original problem SVG was being rendered in a similar manner, either zero size, or rendered so large only whitespace on the corner of the SVG was actually within the bounds of the rendered page, looking as if it did not render.

I didn't have too much time to dig and narrow it down to a specific cause.

But I think just stripping back re-exporting the SVG using standard presentation attributes, non-responsive, and then displaying the SVG with explicit dimensions will give you the best chance.

**Comment by pockhiss** [comment]
Posting my issue in case it helps. My svg wasn't rendering in the pdf, it had been working in the past. I can also see it not rendering in Chrome print preview, so I figured it was not a chromium or puppeteer specific issue. Plus a little faster to troubleshoot with print preview. I was using object tag. I changed to img tag and it worked. My custom fonts now don't work. Visual Studio had a dropdown by the font in the svg editor to embed as base64. I did that, and now it all works.

**Comment by backflip** [comment]
I had to replace hex fill colors with named ones in order for SVGs to be rendered in PDFs.

Example with Github logo:

SVG not visible in PDF:
```
<svg height="32" version="1.1" viewbox="0 0 16 16" width="32">
  <path fill="#000" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
</svg>
```

SVG visible:
```
<svg height="32" version="1.1" viewbox="0 0 16 16" width="32">
  <path fill="black" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
</svg>
```

In more complex SVGs I had to remove masks, too.

**Comment by aslushnikov** [comment]
This is an upstream bug. Can you please file it to Chromium at https://crbug.com/new and cross-post the link here?

**Comment by rjayako** [comment]
Is there any other patches for this? What @backflip said works looks like it's an issue with hex color codes but what is a fix for an svg that gets dynamically created?

**Comment by carlbarrdahl** [comment]
@rjayako I did a temp fix by converting all hex colors into rgb in the html and pass it as data:text/html to puppeteer. Like this:

```ts
const html = renderTemplate({ data, template })
const replacedHTML = hexToRgb(html)

await page.goto(`data:text/html,${replacedHTML}`, { waitUntil: 'networkidle0' })
const pdf = await page.pdf({ format: 'A4' })

// https://github.com/sindresorhus/hex-rgb
import hexRgb from 'hex-rgb'
export function hexToRgb(str: string) {
  const hexTest = /#[a-f\d]{3,6}/gim
  return str.replace(hexTest, hexColor => {
    const { red, green, blue } = hexRgb(hexColor)
    return `rgb(${red}, ${green}, ${blue})`
  })
}
```

**Comment by AlexWayfer** [comment]
> This is an upstream bug. Can you please file it to Chromium at https://crbug.com/new and cross-post the link here?

Sadly that nobody created such one (I didn't find neither a link her nor an issue at Chromium bug tracker), so I've done this as well as I could: https://bugs.chromium.org/p/chromium/issues/detail?id=1116871

**Comment by AlexWayfer** [comment]
> > This is an upstream bug. Can you please file it to Chromium at https://crbug.com/new and cross-post the link here?
> 
> Sadly that nobody created such one (I didn't find neither a link her nor an issue at Chromium bug tracker), so I've done this as well as I could: https://bugs.chromium.org/p/chromium/issues/detail?id=1116871

As [was notified by Chromium project member](https://bugs.chromium.org/p/chromium/issues/detail?id=1116871#c5), the same issue also for regular browser mode (non-headless), I saw it, so I suggest to watch the root old (5 years) issue: https://bugs.chromium.org/p/chromium/issues/detail?id=470601

**Comment by bersling** [comment]
In my case, it was a missing "width" and "height" attribute on the svg. It was displayed in the browser, but not in the PDF. After adding width and height, it was displayed.

**Comment by AlexWayfer** [comment]
> In my case, it was a missing "width" and "height" attribute on the svg. It was displayed in the browser, but not in the PDF. After adding width and height, it was displayed.

I've changed the code to this:

```html
<svg class="icon icon-external-link" width="36" height="36">
  <use href="/images/icons/symbol-defs.svg?v=1608249992#icon-external-link"></use>
</svg>
```

and it didn't help.

**Comment by sergyc13** [comment]
I'm still experiencing the issue. Setting the width and height has helped in my case.

**Comment by sidvishnoi** [comment]
Inlining SVG and adding width/height worked in my case.
`<use xlink:href="file.svg#symbol-id">` didn't (even with width/height set).

**Comment by stemaDev** [comment]
Try adding "--disable-gpu" as a launch option argument for the browser. PDF export always worked for me but taking a screenshot from code was a hit and miss, sometimes it did it, sometimes it was just a blank image. With this switch I constantly getting good results.

**Comment by skarthik05** [comment]
Hi, has there been any progress on this issue? I’m experiencing something similar: when I open the HTML page, the SVG renders correctly, but when I convert to PDF using Puppeteer, the SVG isn’t completely filled. Is there a workaround or update on this?
