### ISSUE TITLE
What is the line of code needed in package.json to exclude chromium install during the installation of puppeteer

### ISSUE THREAD

**Issue by santoshbilla** [puppeteer/puppeteer#2557]
{
  "name": "my-puppeteer-web",
  "version": "1.0.0",
  "description": "Repository for the bundles.",
  "main": "index.js",
  "scripts": {
    "test": "./node_modules/.bin/jest"
  },
  "dependencies": {
    "jquery": "^3.3.1",
    "puppeteer": "^1.3.0",
    "react": "^16.3.0"
  },
  "repository": {
    "type": "git"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "jest": "^22.4.3"
  }
}

**Comment by aslushnikov** [comment]
There's none; there's some effort going on around `puppeteer-core` package, see #1809.
