### ISSUE TITLE
Is there a detailed example of how to run the screencast API in Chrome?

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#2561]
I've read alot of issues threads in this repo but it's not clear to me - is there a mechanism currently to capture screencast / css animation frames?

I tried using tracing but it saved only 5 screenshots. Tested on another page, it saved only 1 screenshot.

```
await page.tracing.start({path: 'trace.json', screenshots: true});
await page.goto('https://daneden.github.io/animate.css/');
await page.tracing.stop();
```

I'm happy with any solution at all, just as long as I can grab the animation frames somehow. - the more frames per second, the better.

thanks!

**Comment by joelgriffith** [comment]
Related to https://github.com/GoogleChrome/puppeteer/issues/478

**Comment by aslushnikov** [comment]
There's no recommended way ATM - only a few hacks here and there that might work from time to time. There are a lot of them on the tracker.

Will the screencast of the page satisfy you? If yes, then indeed #478 will be the way to go.
