### ISSUE TITLE
Allow base64 result in screenshot

### ISSUE THREAD

**Issue by yotamlaufer** [puppeteer/puppeteer#2566]
When grabbing a screenshot CDP will return base64 which is then encoded into a binary buffer by puppeteer. https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L761

This behaviour is favourable for most use cases, but I have a use case that benefits from skipping that stage and keeping the returned value as base64. Is it possible to add an option to skip encoding and return a base64 string as the result?

**Comment by italojs** [comment]
``` js
const base64 = await page.screenshot({ encoding: "base64" })
```
