### ISSUE TITLE
`BrowserFetcher` is unable to download stable (and other) revisions because they are missing from the download site

### ISSUE THREAD

**Issue by casey-speer** [puppeteer/puppeteer#2567]
The stable and other chromium snapshots often cannot be downloaded via puppeteer's `BrowserFetcher` because the snapshots for the relevant revision numbers are missing. This makes it very difficult to programmatically obtain up-to-date revision info and download those revisions without manual intervention. I would expect that stable revisions at least should always be available for download.

Is there an alternate source for these / can these revisions be published consistently? Otherwise is there an alternate data source to find revisions that are definitely available in the snapshots?

**Steps to reproduce**

1. Create a `BrowserFetcher` using `puppeteer.createBrowserFetcher`.
2. Use https://omahaproxy.appspot.com/all.json?os=mac to get the latest revision info for stable (or other channels)
3. Attempt to download stable (etc.) using `BrowserFetcher.download({STABLE_REVISION})`

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Mac OS 10.13.3
* URLs (if applicable): https://omahaproxy.appspot.com/all.json?os=mac, https://storage.googleapis.com/chromium-browser-snapshots
* Node.js version: 8.9.1

**What is the expected result?**
The specified stable (etc.) chrome revision is downloaded by `BrowserFetcher`.

**What happens instead?**

Download fails. The download URL provided by `BrowserFetcher.getRevisionInfo` 404s and visiting https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/ confirms that the revision is not available.

**Comment by iokill** [comment]
I encountered the same issue and I believe there is actually more to it: From what I understand, the revision numbers will just get you the base/snapshot versions of Chromium. So, even if there would be a working download for the current stable revision (e.g revision 540276 at this moment), you'll just get Chromium 66.0.3359.0 and not the actual stable version 66.0.3359.181.

This means a whole lot of bugfixes and more importantly security fixes will be missing. That's worth keeping in mind if you plan to load untrusted sites with that browser...

As for finding a revision where the snapshot exists, you'd probably be best off using the revision in the LAST_CHANGE file e.g https://storage.googleapis.com/chromium-browser-snapshots/Mac/LAST_CHANGE. It looks to me like this is what https://download-chromium.appspot.com/ uses.

**Comment by casey-speer** [comment]
For Linux the stable version with same revision id is available for download — why shouldn't this be available for mac os? I'm not convinced that the downloads for the stable version change. Perhaps for the consumer-facing downloads, but the snapshots on https://storage.googleapis.com/chromium-browser-snapshots seem to have fixed last modified dates.

For now I'm just manually maintaining the revision ids, but it would be great if the site recommended in the puppeteer docs, https://omahaproxy.appspot.com/all.json?os=mac, showed downloadable revisions.

**Comment by aslushnikov** [comment]
> Download fails. The download URL provided by BrowserFetcher.getRevisionInfo 404s and visiting https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/ confirms that the revision is not available.

@casey-speer Yes, chromium buildbots are not building every revision - this would take too long. And buildbots are not synchronized between each other since there's no big need.

To deal with this, we have a small script that helps us figure which revisions are downloadable: [`utils/check_availability.js`](https://github.com/GoogleChrome/puppeteer/blob/master/utils/check_availability.js). The script just goes through revision numbers and figures which platforms have a snapshot for the revision.

```
lushnikov:~/prog/puppeteer(master)$ ./utils/check_availability.js 563166 0
           linux   mac   win32  win64
  563166     +      +      -      +
  563165     +      -      +      -
  563164     -      -      -      -
  563163     -      -      -      -
  563162     +      +      +      +
  563161     -      -      -      -
  563160     +      -      -      -
  563159     -      -      -      -
  563158     -      -      -      -
  563157     +      +      +      +
  563156     -      -      -      -
  563155     -      -      -      -
  563154     +      -      -      +
  563153     -      +      +      -
  563152     -      -      -      -
^C
lushnikov:~/prog/puppeteer(master)$
```

Hope this helps.

**Comment by ispringer** [comment]
@aslushnikov, `check_availability.js` no longer exists at that URL. Is there a new home for it?

Thanks!
