### ISSUE TITLE
Worse headless performance when calling screenshot versus non-headless

### ISSUE THREAD

**Issue by Robula** [puppeteer/puppeteer#2568]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: macOS 10.13.4
* Node.js version: 8.10.0

**What steps will reproduce the problem?**

```
const renderPage = async (browser) => {
  const page = await browser.newPage();
  await page.setViewport({ width: 1920, height: 1080 });
  await page.setContent('<h1>Some really simple HTML</h1>');
  await page.screenshot(); 
  await page.close();
};

(async () => {
  const browser = await puppeteer.launch({
    headless: /* true/false */ ,
    args: ['--proxy-server="direct://"', '--proxy-bypass-list=*']
  });

  const iterations = 10;
  let totalTime = 0;
  for (let i = 0; i < iterations; i++) {
    const startTime = new Date().getTime();
    await renderPage(browser);
    const timeToRender = new Date().getTime() - startTime;
    totalTime += timeToRender;
  }

  console.log(`Took a total of ${totalTime}ms to run all ${iterations} iterations. AVG: ${totalTime / iterations}ms`);
})();
```
1. Launch browser with headless set to true|false.
2. Create a new page.
3. Call `setViewport` with width/height.
4. Call `setContent` with a basic HTML string. (Can be exchanged with `goto`)
5. Call `screenshot`, (we don't need to do anything with buffer for purpose of example) 
5. Close the page.
3. Record time took to complete response.

**What is the expected result?**
I expect that the performance of running headless be at least on par, if not better than running full windowed Chromium.  

**What happens instead?**
`headless: false`: Took a total of 4512ms to run all 10 iterations. AVG: 451.2ms
`headless: true`:  Took a total of 6475ms to run all 10 iterations. AVG: 647.5ms

**Comment by Robula** [comment]
This _may_ be related to https://github.com/GoogleChrome/puppeteer/issues/736 however I am seeing lesser headless performance regardless of image/viewport size.

**Comment by Robula** [comment]
I ran a trace for a single request for headless true/false. One thing that stood out in the headless trace was that `ScheduleBeginFrameDeadline` had a wall duration of 190ms whereas the same function in non-headless took 13ms.
```
"../../components/viz/service/display/display_scheduler.cc"
src_func | "ScheduleBeginFrameDeadline"
```

Headless: https://pastebin.com/5yRguizU
Non-headless: https://pastebin.com/zGHh2gBQ

**EDIT:** With `headless: true, dumpio: true` I get an error: `[0518/103309.052181:ERROR:gpu_process_transport_factory.cc(1012)] Lost UI shared context.` 

I also tested this on a Windows box and found that headless was actually faster, which means this issue may be specific to macOS. After trying headless mode with a Debian container I am extremely happy with the blistering speed!

**Comment by aslushnikov** [comment]
@Robula in fact, chrome headless on OS X is not a real headless; it's more like a "headful with hidden window". That's probably what causes this weird behavior and some others as well; more on this here - https://bugs.chromium.org/p/chromium/issues/detail?id=741689. (We mention this in our documentation for the `page.screenshot` method)

The linux implementation of headless mode is a real one and should be way, *way* faster.
