### ISSUE TITLE
Unable to take screenshot for lazy loaded webpages

### ISSUE THREAD

**Issue by grv190** [puppeteer/puppeteer#2569]
Hi, i have been trying to take `screenshot` of a lazyloaded page using puppeteer.No matter what I do im unable to get the screenshot.One or the other image is not getting loaded.

`
try {
      console.log("inside async");
      const target = differencify.init({ chain: false });
      await target.launch({ headless: false });

      const page = await target.newPage();
      await page.setViewport({
        width: 1280,
        height: 800
      });
      await page.goto(url, { waitUntil: "networkidle0" });

      await page.content();
      console.log("before evaluate");

      await printNumbers();

      await page.evaluate(
        `(async () => {
          console.log("inside evaluate");
          let selectors = Array.from(document.querySelectorAll("img"));
          await Promise.all(
            selectors.map(img => {
              if (img.complete) return;
              return new Promise((resolve, reject) => {
                img.addEventListener("load", resolve);
                img.addEventListener("error", reject);
              });
            })
          );
        })()`
      );
      console.log("after evaluate");
      const bodyHandle = await page.$("body");
      const { width, height } = await bodyHandle.boundingBox();
      console.log(width, height);
      const screenshot = await page.screenshot({
        clip: {
          x: 0,
          y: 0,
          width,
          height
        }
      });
      await fs.writeFileSync("pic_file.png", screenshot);
      console.log("Screenshot completed");
      const imag = await fs.readFileSync("ibhubs9.png");
      console.log("read the file");
      const result = await target.toMatchSnapshot(imag);
      console.log("After");
      await bodyHandle.dispose();

      await target.close();
      expect(result).toEqual(true);
      console.log(result);

      browser.close();
    } catch (error) {
      console.log(error);
    }
`

**Comment by tankalaharish** [comment]
The same happened with me , tried a lot many ways couldnt get the solution...hoping someone comes with the perfect solution ...thanks in advance !!!

**Comment by YogeshSinghChouhan** [comment]
Have you tried #338 solution i,e:-
```node 
    await page.evaluate(() => {
      window.scrollBy(0, window.innerHeight);
    })
    await timeout(5000)
```

**Comment by uriya2** [comment]
Anybody found a solution for this issue ?

**Comment by grv190** [comment]
async function not working in the page.evaluate method.

**Comment by YogeshSinghChouhan** [comment]
@grv190 was your problem solved?

**Comment by grv190** [comment]
@YogeshSinghChouhan It's resolved, i am closing the issue.

**Comment by uriya2** [comment]
@grv190 How did you solve this?

**Comment by grv190** [comment]
@uriya2 

`
const target = differencify.init({
          testName: "test name",
          chain: false
        })
        await target.launch({ headless: true })
        const page = await target.newPage()
        await page.setViewport({
          width: 1366,
          height: 766
        })
        await page.goto(key, { waitUntil: 'networkidle0' })
       // wait for the page to load
        await page.content()
       // checking the body tag is loaded
        const bodyHandle = await page.$('body')
        const { width, height } = await bodyHandle.boundingBox()
        const screenshot = await page.screenshot({
          clip: {
            x: 0,
            y: 0,
            width: 500,
            height: 500
          }
        })
        await console.log('write the file')
        const result = await target.toMatchSnapshot(screenshot)
        await bodyHandle.dispose()
        await expect(result).toEqual(true)
        await console.log(result)
        await target.close()
      } catch (error) {
        await console.log(error)
      }
`

**Comment by grv190** [comment]
@uriya2 
`

`
const target = differencify.init({
          testName: "test name",
          chain: false
        })
        await target.launch({ headless: true })
        const page = await target.newPage()
        await page.setViewport({
          width: 1366,
          height: 766
        })
        await page.goto(key, { waitUntil: 'networkidle0' })
       // wait for the page to load
        await page.content()
       // checking the body tag is loaded
        const bodyHandle = await page.$('body')
        const { width, height } = await bodyHandle.boundingBox()
        const screenshot = await page.screenshot({
          clip: {
            x: 0,
            y: 0,
            width: 500,
            height: 500
          }
        })
        await console.log('write the file')
        const result = await target.toMatchSnapshot(screenshot)
        await bodyHandle.dispose()
        await expect(result).toEqual(true)
        await console.log(result)
        await target.close()
      } catch (error) {
        await console.log(error)
      }
``

**Comment by xgz123** [comment]
@grv190 I solved this by set a large viewport and use[ this](https://github.com/GoogleChrome/puppeteer/issues/305)

**Comment by omeneses** [comment]
I solved this, editing the onReady.js file located at /engine_scripts/puppet/

The final .js file looks like this:

module.exports = async (page, scenario, vp)=>{
    function wait (ms) {
        return new Promise(resolve => setTimeout(() => resolve(), ms));
      }
      
      await page.goto(scenario.url, {waitUntil: 'load'});
      // Get the height of the rendered page
      const bodyHandle = await page.$('body');
      const { height } = await bodyHandle.boundingBox();
      await bodyHandle.dispose();
    
      // Scroll one viewport at a time, pausing to let content load
      const viewportHeight = page.viewport().height;
      let viewportIncr = 0;
      while (viewportIncr + viewportHeight < height) {
            await page.evaluate(_viewportHeight => {
                                                    window.scrollBy(0, _viewportHeight);
                                                   }, viewportHeight);
            await wait(2000);
            viewportIncr = viewportIncr + viewportHeight;
      }
    
      // Scroll back to top
      await page.evaluate(_ => {
        window.scrollTo(0, 0);
      });
    
      // Some extra delay to let images load
      await wait(2000);
};



This solution I found at https://www.screenshotbin.com/blog/handling-lazy-loaded-webpages-puppeteer .
