### ISSUE TITLE
Passing a raw cookie to puppeteer

### ISSUE THREAD

**Issue by hexad** [puppeteer/puppeteer#2573]
I am using a node application and i have access to my cookies.
I can view signed cookies using `var cookies = req.cookies;` and i get something like this:
`{ 'connect.sid': 's:qX4ZrttrjydtrjkgsdghsdghrewynZj4Ew2OUh.tTSILkcvgsegsegsegsr99gmW5
0XLcJefM' }`

Is there a way to pass this cookie to puppeteer?
I know puppeteer has the `page.setCookie()` function, but this function expects you to set each field of the cookie. Like this

`page.setCookie(...cookies)
...cookies <...Object>
name <string> required
value <string> required
url <string>
domain <string>
path <string>
expires <number> Unix time in seconds.
httpOnly <boolean>
secure <boolean>
sameSite <string> "Strict" or "Lax".
returns: <Promise>`

So i don't think i have the option of passing my signed cookie directly to puppeteer

**Comment by hexad** [comment]
Someone....??

**Comment by mikestaub** [comment]
I think the reason you cannot set the cookie directly is because puppeteer is using the Chrome DevTools Protocol which is expecting an object. See here: https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setCookie

**Comment by hexad** [comment]
Thanks a lot for answering! I search days about how to solve this. So is there a way to work around this, or maybe transform my cookie to an object, given the fact i know the session secret?

**Comment by mikestaub** [comment]
Yes you will have to transform it into an object. the object should look like this:

```
{
"name": "connect.sid",
"value": "s:qX4ZrttrjydtrjkgsdghsdghrewynZj4Ew2OUh.tTSILkcvgsegsegsegsr99gmW5 0XLcJefM"
}
```
