### ISSUE TITLE
Unable to run "it" blocks asynchronously inside "describe".

### ISSUE THREAD

**Issue by grv190** [puppeteer/puppeteer#2577]
Inside describe function, i want to run it blocks synchronously... (one "it" after another "it").
How can i achieve it?

`describe('test', async () => {
  it('homePage', async () => {
    await init(url, name, true) // function
  })

  it('ourteam', async () => {
    await init(url, name, true) //function
  })`

**Comment by aslushnikov** [comment]
This sounds like a testrunner question; please ask on StackOverflow.
