### ISSUE TITLE
Is it possible to access the JavaScript functions of a website with Puppeteer?

### ISSUE THREAD

**Issue by DrisyaNairJ** [puppeteer/puppeteer#2579]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  1.4.0
* Platform / OS version: 8.10.0

**Comment by vsemozhetbyt** [comment]
If I am not wrong, it is possible if the function is exposed in the global Window context.

**Comment by DrisyaNairJ** [comment]
Thank you! I tried the below code,
const windowHandle = await page.evaluateHandle(() => window);
Could you please suggest a sample/api method, so that i can refer that.

**Comment by vsemozhetbyt** [comment]
@DrisyaNairJ Here is a tiny example. I've created a simple page with a function: [source](https://github.com/vsemozhetbyt/vsemozhetbyt.github.io/blob/master/test/test.html) and [rendered](https://vsemozhetbyt.github.io/test/test.html). Here is the puppeteer script:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://vsemozhetbyt.github.io/test/test.html');

    console.log(await page.evaluate(() => test()));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Output:
```sh
42
```

**Comment by DrisyaNairJ** [comment]
Thankyou so much for your help! I tried the same, but i'm getting a Reference Error that the "'method-name' is not defined". Do we need an overloaded method in puppeteer class?

**Comment by vsemozhetbyt** [comment]
I use common puppeteer with just this script.
Maybe the page you process has more complicated function system.

**Comment by DivyaGuptaBrimma** [comment]
I have this function in my app
```
function getEditor() {
    console.log(window);
     return window;
}
```
When I run it from the console in the app, it works. 

But when I try this from puppeteer,
`console.log(await page.evaluate(() => getEditor()));`

It returns _undefined_ when I run it from puppeteer.  Can someone please help.

**Comment by vsemozhetbyt** [comment]
[`page.evaluate()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args) can transfer only serializable values, which is not the case for the `window` object, unfortunately.

**Comment by sahilpaudel** [comment]
Typescript is giving undefined function error 
```await page.evaluate(() => fLogon());```

**Comment by f1rstsurf** [comment]
what if there are two functions with the same name ? How does puppeteer will handle this ?

**Comment by vsemozhetbyt** [comment]
There cannot be two functions with the same name in the global window context.

**Comment by f1rstsurf** [comment]
But if you take a closer look to the source code for example of this page : 
https://fr.aliexpress.com/premium/foulard-soie.html?d=y&origin=y&catId=0&initiative_id=AS_20201126074147&SearchText=foulard%20soie

You'll notice the runParams() function is called two times, the first one return an empty result, while the second return a serialized result.

How do you proceed to get the result of the second occurence and not the first one ?

**Comment by vsemozhetbyt** [comment]
Sorry, I can only see `window.runParams` object, not function.

**Comment by f1rstsurf** [comment]
yes that true but using `await page.evaluate(() => runParams)` with this page : 
https://fr.aliexpress.com/item/4001253744819.html

Will search for window.runParams and return the datas, inside the brackets.
How should i proceed to do the same on the page mentioned yesterday, to get the value of the second occurence of window.runParams ?

```
<script type="text/javascript">
window.runParams = {};
window.runParams = {"resultCount":20021};
</script>
```

Thank you for your help !

**Comment by vsemozhetbyt** [comment]
As these two assignments run synchronously one after another, I think you will definitely get the second value (or nothing if you try to get the data before this script runs).

**Comment by f1rstsurf** [comment]
Thanks for the precision, indeed, the result is empty, i don't know what to do to retrieve the datas in the bracket.. I tried to await for the page to be loaded, but that does not seems to do the trick. thanks anyway.

**Comment by vsemozhetbyt** [comment]
But if you do need some check, you can use something like this:
```js
await page.waitForFunction('window.runParams && Object.keys(window.runParams).length !== 0');
```
Or:
```js
await page.waitForFunction('window.runParams && window.runParams.resultCount !== undefined');
```

**Comment by f1rstsurf** [comment]
wow, you're a killer, it now works, you're awesome, thank you !!

**Comment by harunoz** [comment]
How can I check whether the function is used in the web site? 

`await page.waitForFunction('test() !== 0');`

is not working in that case.

**Comment by vsemozhetbyt** [comment]
@harunoz
I think you can try:
```js
const functionIsDeclared = await page.evaluate('typeof test === "function"');
```

**Comment by harunoz** [comment]
Thank you for your answer, however also want to use to another functions. For example when I run this:

`const functionIsDeclared = await page.evaluate('typeof showOpenFilePicker === "function"');`

it always returns true since the showOpenFilePicker is a valid JS function. However I want to receive boolean value only if the analyzed website has showOpenFilePicker function.

Thank you again for your answer.

**Comment by vsemozhetbyt** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker , this function is always available as `window.showOpenFilePicker` (and as simply `showOpenFilePicker`) in all HTTPS pages in all supporting browsers.

**Comment by harunoz** [comment]
Yes but I need to check the running website has the `window.showOpenFilePicker` function. For example, while analyzing `google.com,` it should return false. How can I achieve this?

**Comment by vsemozhetbyt** [comment]
Do you need to detect if a website actually uses this function? I.e. if the website calls it?

**Comment by harunoz** [comment]
Yes exactly.

**Comment by vsemozhetbyt** [comment]
Well, this is a tough one) I can suggest using the [`page.evaluateOnNewDocument()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevaluateonnewdocumentpagefunction-args) to create a wrapper function at the early stage and check some variable later. This works for me:

```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({ headless: false, defaultViewport: null });

try {
  const [page] = await browser.pages();

  await page.evaluateOnNewDocument(() => {
    window.showOpenFilePickerIsCalled = false;

    const oldShowOpenFilePicker = window.showOpenFilePicker.bind(window);

    window.showOpenFilePicker = function (...args) {
      window.showOpenFilePickerIsCalled = true;
      return oldShowOpenFilePicker(...args);
    };
  });

  await page.goto('https://example.org/');

  const check1 = await page.evaluate(() => {
    return window.showOpenFilePickerIsCalled;
  });
  console.log(check1); // false

  const fileName = await page.evaluate(async () => {
    return (await window.showOpenFilePicker())[0].name;
  });
  console.log(fileName); // picked file name

  const check2 = await page.evaluate(() => {
    return window.showOpenFilePickerIsCalled;
  });
  console.log(check2);// true
} catch(err) { console.error(err); } finally { await browser.close(); }
```

**Comment by harunoz** [comment]
Thank for your help. Is it any way to generalize this code by adding hooking? What I mean is, when the user invoked the function showOpenFilePicker, I want to first run by own function. When the process of my function is finish, I want to continue to process of the website. I know it is kind a confusing, more simply basically I want to perform hooking to showOpenFilePicker function.

**Comment by vsemozhetbyt** [comment]
Well, you can add any code in the wrapper above, do anything instead of `window.showOpenFilePickerIsCalled = true;` part.

**Comment by vsemozhetbyt** [comment]
I.e. just use:
```js
  await page.evaluateOnNewDocument(() => {
    const oldShowOpenFilePicker = window.showOpenFilePicker.bind(window);

    window.showOpenFilePicker = function (...args) {
      // your code...
      // your code...
      // your code...

      return oldShowOpenFilePicker(...args);
    };
  });
```

**Comment by vsemozhetbyt** [comment]
Maybe see https://javascript.info/call-apply-decorators for some general examples.

**Comment by harunoz** [comment]
Hello, after a long time I am still having the same issue, I tried your code with inside of async function() as you see in below.
```
'use strict';

const puppeteer = require('puppeteer');


(async function main() {


    const browser = await puppeteer.launch({ headless: false, defaultViewport: null });
    
    try {
      const [page] = await browser.pages();
    
      await page.evaluateOnNewDocument(() => {
        window.showOpenFilePickerIsCalled = false;
    
        const oldShowOpenFilePicker = window.showOpenFilePicker.bind(window);
    
        window.showOpenFilePicker = function (...args) {
          window.showOpenFilePickerIsCalled = true;
          return oldShowOpenFilePicker(...args);
        };
      });
    
      await page.goto('https://example.org/');
    
      const check1 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check1); // false
    
      const fileName = await page.evaluate(async () => {
        return (await window.showOpenFilePicker())[0].name;
      });
      console.log(fileName); // picked file name
    
      const check2 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check2);// true
    } 
    catch(err) { console.error(err); } finally { await browser.close(); }
})();
```

However, I am getting false for every website and still getting an Evaluation Failed error as showed in below.
```
false
Error: Evaluation failed: [object Object]
    at ExecutionContext._evaluateInternal (/Users/harunoz/Desktop/hooking/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/harunoz/Desktop/hooking/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/harunoz/Desktop/hooking/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/harunoz/Desktop/hooking/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/harunoz/Desktop/hooking/node_modules/puppeteer/lib/Page.js:827:43)
    at Page.<anonymous> (/Users/harunoz/Desktop/hooking/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/Users/harunoz/Desktop/hooking/puppeteer.js:32:35)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```


Can you help me with this error? How can I solve this issue?

Thanks.

**Comment by vsemozhetbyt** [comment]
@harunoz Can there be that you try to use this code on HTTP sites? 

See [Window.showOpenFilePicker()](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker):

> This feature is available only in secure contexts (HTTPS)...
