### ISSUE TITLE
Request interception doesn't work for headless = false, Chrome Version 66.0.3359.181 (64-bit)

### ISSUE THREAD

**Issue by annfomenko** [puppeteer/puppeteer#2581]
It seems request interception doesn't work with chrome browser(66.0.3359.181 (64-bit)), headless = false. Actually it works fine in headless mode. Due to this issue - page.authenticate doesn't work also. 

**Tell us about your environment:**

* Google Chrome 66.0.3359.181 (Official Build) (64-bit)
* Puppeteer version: 1.4.0
* Platform / OS version: macOs Sierra 10.12.6 (16G1212)
* Node.js version: 9.8.0

**Comment by aslushnikov** [comment]
@annfomenko pptr 1.4 ships with Chromium 68.0.3419.0, but you run against a different chrome version - chrome 66. Does it work for you with bundled chrome? Also, can you share a minimalistic repro so that I can play with it?

**Comment by huozhi** [comment]
@aslushnikov same issue here. due to limited supports of video playing, I have to run puppeteer with local executable chrome on MacOS.

* chrome: 66.0.3359.181
* mac os: 10.12.6
* node: 8.9.4
* puppeteer: 1.5.0

you can play with `setRequestInterception` API to log all requests. and set `headless` option to false, `executablePath` to local chrome path

```
const browser = await puppeteer.launch({
    headless: false,
    ignoreHTTPSErrors: true,
    args: ['--no-sandbox'],
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  })
```

I think it is related to #2162

**Comment by huozhi** [comment]
Hi @aslushnikov 

you could try this snippet, there is nothing logged after `set interception`.

```js
const puppeteer = require('puppeteer')

async function main() {
  const browser = await puppeteer.launch({
    headless: false,
    ignoreHTTPSErrors: true,
    args: ['--no-sandbox'],
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  })
  const page = await browser.newPage()


  await page.setRequestInterception(true);
  console.log('set interception')
  page.on('request', interceptedRequest => {
    console.log('req:', interceptedRequest.url())
    interceptedRequest.continue()
  });

  await page.goto('https://github.com/', {timeout: 60 * 1000})
  await page.waitFor(300 * 1000)

  await browser.close()
}

main()
```

**Comment by aslushnikov** [comment]
@huozhi for chrome 66 you should use pptr v1.1.1

Hope it helps.

**Comment by huozhi** [comment]
@aslushnikov I tried chrome 67 with pptr 1.2, 1.3 and 1.4 on another laptop, but the problem still can be reproduced all the time.
