### ISSUE TITLE
page.pdf error - 18 page PDF

### ISSUE THREAD

**Issue by mtwhelan** [puppeteer/puppeteer#2583]
**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Ubuntu 16.04.4 LTS
* URLs (if applicable):
- http://snapper2.webcmstools.com/test 
- http://snapper2.webcmstools.com/pdf?url=http://pms.dasaproperties.com
- http://snapper2.webcmstools.com/pdf?url=http://pms.dasaproperties.com/test-owner-statement.html
- http://snapper2.webcmstools.com/simple-pdf?url=http://pms.dasaproperties.com
- http://snapper2.webcmstools.com/simple-pdf?url=http://pms.dasaproperties.com/test-owner-statement.html
* Node.js version: v8.11.2

This works fine for smaller PDFs / pages, but fails, pretty consistently, for an 18-page PDF (statement report). It is relatively small considering the amount of pages (about 88KB). I was able to get it to work once, but have not been able to replicate this success.

**What steps will reproduce the problem?**

Various versions of the following

/test
```
          const browser = await puppeteer.launch()
          const page = await browser.newPage()

          await page.goto('http://pms.dasaproperties.com/test-owner-statement.html', { waitUntil: 'networkidle2' })
          const doc = await page.pdf({path: '/tmp/random-page.pdf', landscape: false, format: 'letter', printBackground: true})

          await browser.close()
          return h.file('/tmp/random-page.pdf').vary('x-magic');
```

-or-

```
          const browser = await puppeteer.launch()
          const page = await browser.newPage()

          await page.goto('http://pms.dasaproperties.com/test-owner-statement.html', { waitUntil: 'networkidle2' })
          const doc = await page.pdf({landscape: false, format: 'letter', printBackground: true})

          await browser.close()
          return h.response(doc).type('application/pdf')
```

**What is the expected result?**

A resulting PDF. Like the following using PhantomJS: http://snapper.webcmstools.com/pdf?url=http://pms.dasaproperties.com/test-owner-statement.html

**What happens instead?**

The following errors:

May 21 21:11:59 snapper[14335]: { Error: Protocol error (Page.printToPDF): Target closed.
May 21 21:11:59 snapper[14335]:     at Promise (/srv/snapper/node_modules/puppeteer/lib/Connection.js:200:56)
May 21 21:11:59 snapper[14335]:     at new Promise (<anonymous>)
May 21 21:11:59 snapper[14335]:     at CDPSession.send (/srv/snapper/node_modules/puppeteer/lib/Connection.js:199:12)
May 21 21:11:59 snapper[14335]:     at Page.pdf (/srv/snapper/node_modules/puppeteer/lib/Page.js:798:39)
May 21 21:11:59 snapper[14335]:     at handler (/srv/snapper/src/screenshots.js:35:34)
May 21 21:11:59 snapper[14335]:     at <anonymous>
May 21 21:11:59 snapper[14335]:     at process._tickCallback (internal/process/next_tick.js:188:7) message: 'Protocol error (Page.printToPDF): Target closed.' }

**Comment by mtwhelan** [comment]
Simplified code example:

```
server.route({
    method: 'GET',
    path: '/simple-pdf',
    handler: async (request, h) => {
      try {
          const browser = await puppeteer.launch()
          const page = await browser.newPage()
          await page.goto(request.query.url, { waitUntil: 'networkidle2' })
          const doc = await page.pdf({landscape: false, format: 'letter', printBackground: true})

          await browser.close()
          return h.response(doc).type('application/pdf')
      } catch (err) {
        console.log('Failed to generate PDF')
        console.error(err)
        return boom.internal(err)
      }
    },
  })
```

Simple 1 Page Login Screen: http://snapper2.webcmstools.com/simple-pdf?url=http://pms.dasaproperties.com/ => Success

17-Page PDF Report: http://snapper2.webcmstools.com/simple-pdf?url=http://pms.dasaproperties.com/test-owner-statement.html => Failure

Error from Apache (Reverse Proxy):
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /simple-pdf.

Reason: Error reading from remote server

Error from Node:
May 22 01:37:12 snapper[31974]: Failed to generate PDF
May 22 01:37:12 snapper[31974]: { Error: Protocol error (Page.printToPDF): Target closed.
May 22 01:37:12 snapper[31974]:     at Promise (/srv/snapper/node_modules/puppeteer/lib/Connection.js:200:56)
May 22 01:37:12 snapper[31974]:     at new Promise (<anonymous>)
May 22 01:37:12 snapper[31974]:     at CDPSession.send (/srv/snapper/node_modules/puppeteer/lib/Connection.js:199:12)
May 22 01:37:12 snapper[31974]:     at Page.pdf (/srv/snapper/node_modules/puppeteer/lib/Page.js:798:39)
May 22 01:37:12 snapper[31974]:     at handler (/srv/snapper/src/screenshots.js:78:34)
May 22 01:37:12 snapper[31974]:     at <anonymous>
May 22 01:37:12 snapper[31974]:     at process._tickCallback (internal/process/next_tick.js:188:7) message: 'Protocol error (Page.printToPDF): Target closed.' }

The same document converts nearly instantaneously using PhantomJS: http://snapper.webcmstools.com/pdf?url=http://pms.dasaproperties.com/test-owner-statement.html

**Comment by mtwhelan** [comment]
Closing this. We figured out what was causing the problem, and it had nothing to do with the fact that the PDF was 18 pages long. I will open a new issue if necessary. Thanks!

**Comment by njriordan** [comment]
@mtwhelan do you have any more information? I'm experiencing the same issue.

**Comment by SupermanWY** [comment]
Has this issue been solved?

**Comment by SupermanWY** [comment]
@mtwhelan Is this issue solved?

**Comment by njriordan** [comment]
@SupermanWY for info, I never solved this problem. However, you can do a work around by looping over pages, e.g. in sets of 5, generating multiple PDFs, and then merging them at the end. It's not a nice solution, but it works.

**Comment by Ofat1958** [comment]
I had the same problem and it turned out that the site was using lazy loading and it caused this error so I used this package to load all images first: https://www.npmjs.com/package/puppeteer-autoscroll-down
