### ISSUE TITLE
Evaluating a function on a JS Handle

### ISSUE THREAD

**Issue by mathurs** [puppeteer/puppeteer#2585]
I am new to exploring this project and maybe there is already a way to do this in a better fashion. However, it seems currently, once in a JS handle context, we can only getProperty/getProperties on it. Would it make sense to evaluate an arbitrary function on it.

I need this because there are many use cases where selection of an element is done outside of $eval. Once a JSHandle is selected (among many returned by $$), its currently difficult to run arbitrary functions on it, like getting style values or such.

Something along the lines
`  /**
   * @param {string} propertyName
   * @return {!Promise<?JSHandle>}
   */
  async evaluateToProperty(propertyFunction, propertyName) {
    const objectHandle = await this._context.evaluateHandle((object, propertyFunction, propertyName) => {
      const result = {__proto__: null};
      const expression = new Function('e', propertyFunction);
      result[propertyName] = expression(object);
      return result;
    }, this, propertyFunction, propertyName);
    const properties = await objectHandle.getProperties();
    const result = properties.get(propertyName) || null;
    await objectHandle.dispose();
    return result;
  }
`
which can be used as
`await element.evaluateToProperty('return e.children.length', 'children')`

Thanks,
Saurabh

**Comment by aslushnikov** [comment]
> I am new to exploring this project and maybe there is already a way to do this in a better fashion. However, it seems currently, once in a JS handle context, we can only getProperty/getProperties on it. Would it make sense to evaluate an arbitrary function on it.

@mathurs you can do this:

```js
const aHandle = await page.evaluateHandle(() => document.body);
const resultHandle = await page.evaluateHandle(aHandle => {
  // .. do things with aHandle inside a page ..
}, aHandle);
```

Hope this helps.

**Comment by mathurs** [comment]
This worked. Thanks a lot!
