### ISSUE TITLE
Make function listenFor async in example custom-event

### ISSUE THREAD

**Issue by YogeshSinghChouhan** [puppeteer/puppeteer#2587]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.x.0
* Platform / OS version:Ubuntu 16.04.3 LTS / Windows 10
* URLs (if applicable):https://github.com/GoogleChrome/puppeteer/blob/master/examples/custom-event.js
* Node.js version:8.x.x

**What steps will reproduce the problem?**

[Here is the code](https://github.com/GoogleChrome/puppeteer/blob/master/examples/custom-event.js)

**What is the expected result?**
I think ```app-ready fired {}```  message should be displayed on the terminal 

**What happens instead?**
In Ubuntu sometimes  ```app-ready fired {}```  message is displayed on the terminal and sometimes not ,in windows  ```app-ready fired {}```  message is displayed when `headless:false`,but it is not displaying when `headless:true`.

I solved the problem by making `listenFor` function **async** in windows ,but in ubuntu there is some inconsistency with displaying message on console.

Is the solution valid , if not then  why isn't function `listenFor` is **async** when you are **awaiting** it.

Please correct me if i  didn't understood this example correctly.

**Comment by ebidel** [comment]
That function returns a promise so an extra async isn't needed and just extends the number of microtasks. See first example in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function for a similar example.

As for the inconsistency, it's possible that event isn't firing on the page for those cases. We should probably switch the example to networkidle0 so it waits for all network requests to be done before resolving. It might be that the page isn't done loading (and therefore fired the event) in those cases.

**Comment by YogeshSinghChouhan** [comment]
Thanks for the response.
 Are you suggesting to use `networkidle2` instead of  `networkidle0` ?
I tried it with  `networkidle0` and  it solved the inconsistency problem.

**Comment by YogeshSinghChouhan** [comment]
@ebidel  If it is correct can i create a PR?

**Comment by ebidel** [comment]
Correct. Yes please!

**Comment by greg-benner-klick-sensei** [comment]
is there a way to have a timeout on the event?
I've been trying everyting.
```
 function continueAfterEvent(a, b) {
    return Promise.race([a, b]);
  }

  const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
await continueAfterEvent(sleep(10000), listenFor("app-ready"))
```
seems to resolve instantly
