### ISSUE TITLE
Issue with margins when print to PDF

### ISSUE THREAD

**Issue by pantekx3** [puppeteer/puppeteer#2592]
I have a strange issue with page margins when printing to PDF. And it's most likely Chrome issue.

**What steps will reproduce the problem?**
Just build PDF via Puppeteer:
`await page.pdf({ path: pdfPath, format: 'A4' });`

This issue is also reproduced when you are in Chrome in Print Preview (Ctrl + P).

**Case 1:**
I have a CSS with these styles:
```
    @page { margin: 3cm 0 2cm; }
```
Some text is not shown because of margins, it's like under it (lines 13 and 14 missed).
![0](https://user-images.githubusercontent.com/6738443/40419215-4a661fdc-5e8d-11e8-87b8-fe264a7a4e5c.png)

**Case 2:**
But when I set margins to 0 everything is OK:
```
    @page { margin: 0; }
```
![1](https://user-images.githubusercontent.com/6738443/40419247-5fde655e-5e8d-11e8-84d9-946aefbc1f7c.png)

**Case 3**
When I'm in Chrome's Print Preview and set Custom Margins (the same 3cm at top and 2 cm at bottom) everything is OK and text is not cut.
![2](https://user-images.githubusercontent.com/6738443/40419286-84e104d8-5e8d-11e8-9d2d-6586b6bb0e9f.png)

**What is the expected result?**
Text should be moved to next page as in case 3.

**What happens instead?**
Text is not shown as it is under margins. (see case 1).

Please advise how to fix that.

**Comment by IpShot** [comment]
@pantekx3 Faced with the same problem. Let me know please if you find solution. I've been playing with different options like margins, footerTemplate to trick the problem out but have no luck for now.

**Comment by ctrl-shift** [comment]
There is `preferCSSPageSize` option which takes all page parameters (size, margins) from `@page`. It'll probably fix this but it's currently not available in puppeteer.
https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF

As a workaround for now you can try passing margins directly to `page.pdf` function (marginTop, marginBottom, ...) and remove them from `@page`.

**Comment by IpShot** [comment]
@ctrl-shift Thanks for your answer. I tried with inline margins in `page.pdf` but still have the same problem.

**Comment by IpShot** [comment]
@ctrl-shift And thanks for `preferCSSPageSize` hint. Will try to use that.

**Comment by IpShot** [comment]
Tried to play with `preferCSSPageSize`. It doesn't impact on the problem.

**Comment by pantekx3** [comment]
At last, I found out what is the cause of the issue in my case - it was margin-bottom for the first page:
```
@page:first {
    margin-bottom: 0; 
}
```

After removing it - everything is OK.
@IpShot hope it will also help you if you have similar margin styles :)
Thanks everybody!

**Comment by IpShot** [comment]
@pantekx3 Good catch! It works. I have `margin-top: 0` set for the first page. But unfortunately I need that one and can't just remove it :)
Thanks for the info!

**Comment by hdemirev** [comment]
@IpShot did you ever find a resolution for this? 

edit: following the recommendation to pass margins to the page.pdf function instead of defining them in the css resolves this for me.

**Comment by bmaupin** [comment]
In my case this added extra spacing in the middle of the document, only when printing and only with puppeteer/chromium:

```css
@page {
    margin: 1.6cm;
}
```

I tried defining the margins in page.pdf but that didn't work. The fix in the end was to change the bottom margin. I played with several values. In the end this worked but it required setting page breaks manually using `page-break-after: always;`

```css
@page {
    margin: 1.6cm 1.6cm -1.6cm;
}
```

**Comment by initialapps** [comment]
I struggled with this for awhile and finally got this to work by setting a smaller page size, while setting the margin to zero. 
`@page { 
        size:8in 10in;
        margin: 0; 
}`

**Comment by initialapps** [comment]
> I struggled with this for awhile and finally got this to work by setting a smaller page size, while setting the margin to zero.
> `@page { size:8in 10in; margin: 0; }`

Revisiting this a year and a half later... My prior answer was wrong.
I had a lot of competing CSS margins that were making things messy.  

After cleaning that up, I simply specified page size and margins in inches and it worked:

```
@page {
        size: 8.5in 11in; 
        margin: 0.5in;
}
```
