### ISSUE TITLE
Can't select or manipulate elements inside a iframe

### ISSUE THREAD

**Issue by WolfganG1st** [puppeteer/puppeteer#2593]
Steps to reproduce
Tell us about your environment:

Puppeteer version: 1.4.0
Platform / OS version: Windows 10 Pro
URLs (if applicable): https://www.seguroviagem.srv.br/payment/806440/to3ulroe
Node.js version: 8.11.2
What steps will reproduce the problem?

**What steps will reproduce the problem?**

const puppeteer = require("puppeteer"),
  fs = require("fs");

puppeteer
  .launch({
    headless: false,
    args: ['--disable-web-security']
  })
  .then(async browser => {
    // Configurations
    const config = {
      nome: "Jonata Carlos dos Santos",
      url: "https://www.seguroviagem.srv.br/payment/806440/to3ulroe"
    };
    // Load the page
    const page = await browser.newPage();
    await page.goto(config.url), {
      waitUntil: "domcontentloaded"
    };
    page.setViewport({
      width: 920,
      height: 950
    });

    // Click on the pay button
    const pagar = await page.$(
      "#conteudo > div.ng-scope > div > section:nth-child(6) > section > form > input"
    );
    await pagar.click();

    // Select the frame
    const frame = page.mainFrame().childFrames()[1];

    // Log the current frame
    console.log(frame);

    // await for the selector inside the iframe appear and then type

    await frame.waitForSelector('#pagarme-modal-box-buyer-name');
    await frame.type('#pagarme-modal-box-buyer-name', config.nome);

  });

**What is the expected result?**

I was expecting to insert a text in the selector inside the frame

obs: That iframe is locate in a different address so i guess that can be something related with Cross-Origin Resource Sharing - CORS

**What happens instead?**

i get an error instead: UnhandledPromiseRejectionWarning: Error: waitForFunction failed: frame got detached.

**Comment by xprudhomme** [comment]
@FelipeFernandesLeandro  you shoud not close this issue, but rather leave it opened, as I have met exactly the same issue you had, but it is no related to CORS.

**Comment by aslushnikov** [comment]
> i get an error instead: UnhandledPromiseRejectionWarning: Error: waitForFunction failed: frame got detached.

@FelipeFernandesLeandro This errors comes since the page detached the iframe you're manipulating. Once iframe detaches, its execution context gets destroyed, so no evaluations can be run inside of it.

> @FelipeFernandesLeandro you shoud not close this issue, but rather leave it opened, as I have met exactly the same issue you had, but it is no related to CORS.

@xprudhomme if you get the same error, than this is what it is: the iframe got detached, so you can't operate with it's internals any more.

**Comment by michalklym** [comment]
I had an issue with finding stripe elements. 
The reason for that is the following: 

> You can't access an <iframe> with different origin using JavaScript, it would be a huge security flaw if you could do it. For the same-origin policy browsers block scripts trying to access a frame with a different origin. [See more detailed answer here](https://stackoverflow.com/a/25098153/11974819)

Therefore when I tried to use puppeteer's methods:` Page.frames()` and `Page.mainFrame().`  `ElementHandle.contentFrame()` I did not return any iframe to me. The problem is that it was happening silently and I couldn't figure out why it couldn't find anything.

Adding these arguments to launch options solved the issue:
`
 '--disable-web-security',
'--disable-features=IsolateOrigins,site-per-process'
`

**Comment by Joovo** [comment]
> I had an issue with finding stripe elements.
> The reason for that is the following:
> 
> > You can't access an <iframe> with different origin using JavaScript, it would be a huge security flaw if you could do it. For the same-origin policy browsers block scripts trying to access a frame with a different origin. [See more detailed answer here](https://stackoverflow.com/a/25098153/11974819)
> 
> Therefore when I tried to use puppeteer's methods:` Page.frames()` and `Page.mainFrame().` `ElementHandle.contentFrame()` I did not return any iframe to me. The problem is that it was happening silently and I couldn't figure out why it couldn't find anything.
> 
> Adding these arguments to launch options solved the issue:
> `'--disable-web-security', '--disable-features=IsolateOrigins,site-per-process'`

It cannot resolve my problem, still .I want to know why and how it happend, is another way to avoid it happening?
