### ISSUE TITLE
the page appear elongated while capturing full page

### ISSUE THREAD

**Issue by hbakhtiyor** [puppeteer/puppeteer#2599]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: ubuntu 18.04
* URLs (if applicable): http://embertribe.com
* Node.js version: 10.1.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
'use strict';

const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({timeout: 0});
  const page = await browser.newPage();
  await page.goto('http://embertribe.com', {timeout: 0, waitUntil: 'networkidle2'});
  await page.screenshot({path: 'full.png', fullPage: true});
  await browser.close();
})();
```
**What is the expected result?**

**What happens instead?**

<details>
  <summary>result screenshot</summary>

![full](https://user-images.githubusercontent.com/3434496/40478237-f4676c14-5f61-11e8-93ab-d7f7d8bc49b5.png)

</details>

**Comment by aslushnikov** [comment]
Looks like a race in our device emulation logic. Should be fixed with the upstream patch: https://chromium-review.googlesource.com/c/chromium/src/+/1011121

**Comment by bv-deepak** [comment]
@aslushnikov Hi, can you please explain to me what is the issue and how should I solve this?. I am also facing the same issue.
