### ISSUE TITLE
Headless chrome running in docker does not wait for loading the images from URL.

### ISSUE THREAD

**Issue by saurabhghewari** [puppeteer/puppeteer#2601]
### Steps to reproduce

* Puppeteer version:1.4.0-post
* Platform / OS version: Ubuntu 16.04 64bit
* URLs (if applicable):
* Node.js version: 8

**What steps will reproduce the problem?** 
        
         async function start() {
           var browser = await puppeteer.launch({
                args: [
                    '--no-sandbox',
                    '--disable-setuid-sandbox'
                ],
                headless: true,
            });
            
            var page = await browser.newPage();
            await page.goto(`file:${path.join(__dirname, '../index.html')}`, { waitUntil: 'networkidle0' });

            page.on('console', msg => {
                for (let i = 0; i < msg.args().length; ++i)
                  console.log(`${i}: ${msg.args()[i]}`);
              });

            await page.evaluate((imagesArray) => {
                let division = document.createElement('div');
                division.setAttribute('style', 'visibility:hidden;');
                imagesArray.map((img) => {
                    let image = document.createElement("img");
                    image.src = img;
       
                    image.onload = function() { window.imageLoad = true };
                    image.onerror = function() { window.imageLoad = false };
                   document.getElementById('canvasEditorHolder').appendChild(division).appendChild(image);
                })
                
                return;
            }, imagesArray);
            const watchDoc = 
                             await page.waitForFunction('window.imageLoad === true');
            await watchDoc;
            await page.screenshot({path: filename});
            browser.close();
          }

**What is the expected result?**

It should Load all the images from the URL and then take screenshot when running without docker or in docker.

**What happens instead?**
It takes screenshot without loading the image when running in docker and throws an exception at 
**image.onerror** saying **Failed to evaluate the page: event**.

**Comment by aslushnikov** [comment]
I'm not sure what's going on here; your snippet is not runnable so I can't reproduce the issue either.

I'd guess that this is something related to the #338. Please re-file with a runnable snippet.

Thanks.
