### ISSUE TITLE
Logo in headerTemplate

### ISSUE THREAD

**Issue by muditjuneja** [puppeteer/puppeteer#2604]
Hi,
I have been trying hard to insert a logo in my header. I am passing the logo image as base64 string to the headerTemplate but I am unable to style the image to move it to right and of fixed size.

Even I want logos in my footer too. Is there any way to achieve this?

Headless chrome has been one of the most sophisticated tool for rendering html and converting into pdf. It's not like PhantomJS which didn't let me sleep some nights.

Has anyone achieved this using Puppeteer?

**Comment by kromit** [comment]
You need to add a `<style>` tag with additional CSS to your template. CSS file do not work.

**Comment by Narigo** [comment]
We got this working by using a style rule like `span.logo { content: url("data:image/png;base64,...")` and have a `<span class="logo"></span>` in our `headerTemplate` option.

**Comment by iamdanthedev** [comment]
also it is possible to embed an svg tag into the template

**Comment by rupl** [comment]
yes, directly embedding SVG markup is possible. There's no need to base64 encode the markup.

**Comment by toix** [comment]
Works with `<img>`-tag as well:
`<img class="logo" alt="title" src="data:image/png;base64,..." width="40"/>`

**Comment by MaMaRo123** [comment]
> Works with `<img>`-tag as well:
> `<img class="logo" alt="title" src="data:image/png;base64,..." width="40"/>`

doesn't work for me

**Comment by altjx** [comment]
Does the image absolutely have to be base64 encoded? It seems like using a URL to the image doesn't work

**Comment by CEOehis** [comment]
You can't have external resources in the pdf generated. What worked for me is I had the logo put in svg format and embedded the xml code of the svg in the header and footer template.

```
<span>
    <svg width="100%"  viewBox="0 0 253 34" xmlns="http://www.w3.org/2000/svg">
        ....
    </svg>
</span>
```

**Comment by feedonat** [comment]
@Narigo , can you please post your whole solution , I tried and it didn't work for me

**Comment by diamont1001** [comment]
May be you can load image from url and encode it into base64.
for example:

```js
import {encode, decode} from 'node-base64-image';
...
const image = await encode('https://example.com/test.jpg', options);
...
```

**Comment by dev-hardev** [comment]
I'm using spatie/browsershot which under the hood uses puppeteer, but my request fails when I tries to use base64 encoded images in header or footer. 
this is how I'm using it. 
``` 
$logo = 'data:image/png;base64,' . base64_encode(file_get_contents(file_path));

<img src="<?= $logo ?>"/>
```

the above code results:
![image](https://github.com/puppeteer/puppeteer/assets/61737394/ad5f89f2-3b79-4dae-a7df-08e2a48cee8b)

any idea how can I fix this?

**Comment by Seb33300** [comment]
> I'm using spatie/browsershot which under the hood uses puppeteer, but my request fails when I tries to use base64 encoded images in header or footer. this is how I'm using it.

@dev-hardev I am facing the exact same issue (also with spatie/browsershot on a windows system).
Did you find any workaround?

After many try I found that this error is caused by the size of the image/SVG. By using a smaller image/SVG, it works.
It looks like header and footer are very limited in the content size they can handle.

**Comment by dev-hardev** [comment]
Yes! I found solution for it. @Seb33300 

basically we can't pass all config when it is too long, but you can save long config in a file and then pass it to puppeeter by using `writeOptionsToFile` method.

what you can do is save all the config into a json file by turning on the same option, like i did in the code below:

```        
Browsershot::html("Your html code")
  ->noSandbox()
  ->newHeadless()
  ->showBackground()
  ->format('A4')
  ->showBrowserHeaderAndFooter()
  ->waitUntilNetworkIdle()
  ->writeOptionsToFile() // This is the method you need to call
  ->headerHtml($headerHtml)
  ->footerHtml($footerHtml)
  ->save($savedFilePath);
```

and this will make it work. Let me know if your issue is resolved with this.

**Comment by Seb33300** [comment]
Awesome, it works! Thanks @dev-hardev

**Comment by dev-hardev** [comment]
Great! Let me know if I can help you with anything else, Happy to help 😃

**Comment by martinpa13py** [comment]
> ->writeOptionsToFile()

Thank you so much, solve my problem

**Comment by Himanshu4833** [comment]
> Yes! I found solution for it. @Seb33300
> 
> basically we can't pass all config when it is too long, but you can save long config in a file and then pass it to puppeeter by using `writeOptionsToFile` method.
> 
> what you can do is save all the config into a json file by turning on the same option, like i did in the code below:
> 
> ```
> Browsershot::html("Your html code")
>   ->noSandbox()
>   ->newHeadless()
>   ->showBackground()
>   ->format('A4')
>   ->showBrowserHeaderAndFooter()
>   ->waitUntilNetworkIdle()
>   ->writeOptionsToFile() // This is the method you need to call
>   ->headerHtml($headerHtml)
>   ->footerHtml($footerHtml)
>   ->save($savedFilePath);
> ```
> 
> and this will make it work. Let me know if your issue is resolved with this.

Can above solution work for node js ?
