### ISSUE TITLE
browser.createIncognitoBrowserContext is not a function

### ISSUE THREAD

**Issue by coco9527** [puppeteer/puppeteer#2605]
* Puppeteer version: 1.4.0
* Platform / OS version: osx 10.13.4
* URLs (if applicable):
* Node.js version: 9.3.0

`const browser = await puppeteer.launch();
  // Create a new incognito browser context.
  const context = await browser.createIncognitoBrowserContext();
  // Create a new page in a pristine context.
  const page = await context.newPage();
  // Do stuff
  await page.goto('https://example.com');
  browser.close();`
This is my test code

**Comment by mariuszdev** [comment]
@coco9527 What was the reason?

Update: Ok, it hasn't been shipped to npm yet.

**Comment by joelgriffith** [comment]
There’s a docs link in the README that point to `master` that probably should point to the latest release docs instead. This is the 2nd or 3rd time this same issue has popped up.

I’ll get a PR pushed soon that points all docs link to latest
