### ISSUE TITLE
slowMo option is ignored when connecting via a browserWSEndpoint in headless=false

### ISSUE THREAD

**Issue by acgrama** [puppeteer/puppeteer#2606]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Ubuntu 17.10
* Node.js version: 8.9.3

**What steps will reproduce the problem?**
I have built two toy versions that illustrate the problem. The slowMo option seems to be ignored when connecting to a browser instance, using the wsEndpoint.

This works ok -- browser is started, the typing in the search field is reasonably slow:

> 
    (async () => {
      const browser = await puppeteer.launch({
        headless: false,
        slowMo: 100,
        args: ['--start-maximized']
      });
      const page = await browser.newPage();
      await page._client.send('Emulation.clearDeviceMetricsOverride');
      await page.goto('http://www.qwant.com/web', { waitUntil: 'networkidle2' });
      const input = await page.$$('input', input => input);
      await input[0].type('Testing slow motion in Puppeteer');
      // browser.close();
    })();

Compare with this version, where I connect to an existing browser instance and typing is very fast, despite the same slowMo option as above:
> 

    (async () => {
      const browser = await puppeteer.launch({
        headless: false,
        slowMo: 100,
        args: ['--start-maximized']
      });
      const browserWSEndpoint = browser.wsEndpoint();
      const secondbrowser = await puppeteer.connect({ browserWSEndpoint });
      const page = await secondbrowser.newPage();
      await page._client.send('Emulation.clearDeviceMetricsOverride');
      await page.goto('http://www.qwant.com/web', { waitUntil: 'networkidle2' });
      const input = await page.$$('input', input => input);
      await input[0].type('Testing slow motion in Puppeteer');
      // browser.close();
    })();

**What is the expected result?**
The slowMo option should not be ignored in headless=false mode, when connecting to an existing browser instance.

**Comment by benunternaehrer** [comment]
Got the same issue. @acgrama Did you find a solution for that?

**Comment by acgrama** [comment]
@benunternaehrer I had missed this bit in the API docs:
https://github.com/GoogleChrome/puppeteer/blob/v1.5.0/docs/api.md#puppeteerconnectoptions

So you can do this and it will work:
`await puppeteer.connect({ browserWSEndpoint, slowMo: 100 });`
