### ISSUE TITLE
Puppeteer wrongs render page

### ISSUE THREAD

**Issue by b-ponomarenko** [puppeteer/puppeteer#2607]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: MacOS 10.13.4
* URLs (if applicable):
* Node.js version: 8.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Download puppeteer
2. Write simple test, like:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
})();
```
3. run test

**What is the expected result?**
![image](https://user-images.githubusercontent.com/9141542/40560234-0c290122-6062-11e8-9e08-7027da375277.png)

**What happens instead?**
![image](https://user-images.githubusercontent.com/9141542/40560226-0229f870-6062-11e8-970b-1144acd636b4.png)

**Comment by vsemozhetbyt** [comment]
See:

> Puppeteer sets an initial page size to 800px x 600px, which defines the screenshot size. The page size can be customized with [`Page.setViewport()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport).

https://github.com/GoogleChrome/puppeteer/blob/master/README.md#usage

**Comment by b-ponomarenko** [comment]
Thanks!
