### ISSUE TITLE
page.$$eval and page.$eval don't return element values/handles

### ISSUE THREAD

**Issue by monkpit** [puppeteer/puppeteer#2609]
### Steps to reproduce

* Puppeteer version: 1.4.0
* Platform / OS version: Mac OSX High Sierra 10.13.4
* URLs (if applicable): any
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

This is a simple example, obviously in real code I do not need `function(x) {return x;}`, but something more complicated.

```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');
  const input = await page.$eval('input', function(x){return x;});
  console.dir(input);
  await input.type('testing');
})();
```

**What is the expected result?**
Expect an `ElementHandle` or `JSHandle` returned from `await page.$eval(...)`.

**What happens instead?**
`await page.$eval(...)` returns an empty object `{}`, causing `await input.type('testing')` to error.

If I change the code to `const input = await page.$eval('input', function(x){return ['a', 'b', 'c'];});`, then `input === ['a', 'b', 'c']` as one would expect.

**Comment by vsemozhetbyt** [comment]
As per the doc, `page.$eval()` does not return `ElementHandle` or `JSHandle`: it returns the value returned by the function in the second argument after serialization/deserialization process. As `x` in your example is an HTML element, it is not serializable, so the empty object is returned instead.

**Comment by alamothe** [comment]
Interesting... but TypeScript typings say it does return element handle. Is there any other function which returns element handle?

**Comment by aslushnikov** [comment]
> but TypeScript typings say it does return element handle.

This seems to be a bug in TypeScript typings. We'll appreciate if you submit a PR to fix this to DefinitelyTyped!

**Comment by rinogo** [comment]
@aslushnikov It might be helpful to add something like what you said to the [documentation for page.$$eval()](https://playwright.dev/docs/api/class-page/#pageevalselector-pagefunction-arg-1). For example:

> Note: Since objects of types `ElementHandle` and `JSHandle` are not serializable, they cannot be returned by `page.$$eval()`. If an object of one of these types is returned by `pageFunction()`, an empty object is returned instead.
