### ISSUE TITLE
blank screenshot if fullpage is set true

### ISSUE THREAD

**Issue by svarup** [puppeteer/puppeteer#2611]
### Steps to reproduce

**About my environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Linux Ubuntu 17.10
* URLs (if applicable):
* Node.js version: 8.11.1

**Code to reproduce the problem**

``const browser = await puppeteer.launch();``
`` const page = await browser.newPage();``
``await page.goto('http://françois.wiki.allmende.io/view/how-to-wiki');``
``await page.screenshot({path: 'example.png', fullPage: true});``
``await browser.close();``

**What is the expected result?**
it should return full page screenshot.

**What happens instead?**
It will return blank screenshot if i set fullpage to true, without fullpage to true or false it will work perfectly. You can use your [dome page](https://try-puppeteer.appspot.com/) with above code to reproduce the issue.

**Comment by aslushnikov** [comment]
This is a devtools bug; filed upstream as https://crbug.com/848161
