### ISSUE TITLE
Click button if present, else click a different button 

### ISSUE THREAD

**Issue by saadahmad03** [puppeteer/puppeteer#2613]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: MacOS 10.12.6
* URLs (if applicable):
* Node.js version: 8.9.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I am trying to set up an `if/else` statement in puppeteer to click on a button if it is present, else click on other button first, then click on the button I am trying to get to. I am doing something like this:

 ```
if ((await page.$('#buttonToClick')) !== null) {
    await page.click('#buttonToClick');
  } else {
    await page.waitForSelector('#otherButton');
    await page.click('#otherButton');

    await page.waitForSelector('#buttonToClick');
    await page.click('#buttonToClick');
  }

```

For some reason I keep falling into the `else` block even when I go to my Chrome console and do a `document.querySelector('#buttonToClick') !==null` on the desired page and it is showing as `true`

I also tried doing:

```
await page.waitForNavigation({ waitUntil: 'networkidle0' });
if (await page.$('#buttonToClick') !== null) {
    await page.click('#buttonToClick');
  } else {
    await page.waitForSelector('#otherButton');
    await page.click('#otherButton');

    await page.waitForSelector('#buttonToClick');
    await page.click('#buttonToClick');
  }
```

But that didn't work either. I also swapped out the above line: `await page.waitForNavigation({ waitUntil: 'networkidle0' });` for `await page.waitForNavigation({ waitUntil: 'domcontentloaded' });` and also tried `await page.waitForNavigation({ waitUntil: 'networkidle2' });` and none of those seemed to work.

The **ONLY** way I can get the expected result I am looking for is if I write the following code:

```
await page.waitFor(1000);

  if ((await page.$('#buttonToClick')) !== null) {
    await page.click('#buttonToClick');
  } else {
    await page.waitForSelector('#otherButton');
    await page.click('#otherButton');

    await page.waitForSelector('#buttonToClick');
    await page.click('#buttonToClick');
  }
```

But I don't necessarily like the idea of having to do a `page.waitFor()` for a fixed number of seconds...any ideas what could be going on? Any help is appreciated, thanks so much in advance!

**Comment by yanivefraim** [comment]
Did you try starting with:

`await page.waitForSelector('#buttonToClick');`

**Comment by saadahmad03** [comment]
@yanivefraim thanks for your response, the only problem with that is in the case that I do actually need to go into the else block (which is sometimes) then my test will fail waiting for #buttonToClick

**Comment by yanivefraim** [comment]
Sounds like you want to wait some time for your button to appear, and in case it does not appear, do some workaround. Right?

Not sure if this is a best practice (do what you are trying to do here), but if you want to go in that direction, the following solution might be nicer:

```

try {
  await page.waitForSelector('#buttonToClick', {timeout: 1000}); //this thing might be flaky. Not sure it is a good idea!!!
  await page.click('#buttonToClick');
} catch (e) {
  await page.waitForSelector('#otherButton');
  await page.click('#otherButton');

  await page.waitForSelector('#buttonToClick');
  await page.click('#buttonToClick');
}


```

**Again. I think this practice is a bad idea.**  

I dont know your application logic, but I would try to find a different solution by changing my application logic.

**Comment by saadahmad03** [comment]
@yanivefraim thanks so much for your answer! Your above code seems to have done the trick. Unfortunately, I am unable to change the application logic as I am just responsible for writing UI tests against it. I am new to this and a little confused on how the above code is working in comparison to what I had before...would you be able to shed a little light? Thanks so much again for all your help.

**Comment by yanivefraim** [comment]
The main difference is that instead of just having a timeout, you have a ‘waitForSelector’, with a timeout. In case this timeout passes, promise will be rejected (with a timeout error). You can catch this error and have your fallback - click another button. Does it makes sense for your case?

**Comment by saadahmad03** [comment]
@yanivefraim got it, makes sense. Thanks again so much for all the help :)

**Comment by flyingsky** [comment]
A better idea is `Promise.race` to make it faster, like

```
await Promise.race([
  page.waitForSelector('#buttonToClick');
  page.waitForSelector('#otherButton')
);

// Now you get one item, you can check its id to know which button is displayed.
```
