### ISSUE TITLE
Solution for finding unique selectors with chrome for puppeteer

### ISSUE THREAD

**Issue by serkankazak** [puppeteer/puppeteer#2614]
Hi,

While finding selector for puppeteer from chrome, most of the time I got selectors which resolves to multiple elements. (i.e. not unique selector)

With only one line of code change on chrome devtools it is possible to generate unique selector: https://github.com/ChromeDevTools/devtools-frontend/pull/77

An example for this situation:

On youtube, execute following in console:

`Array.from(document.querySelectorAll('*[id]')).map(x=>x.id).sort().filter(function(e,i,a){return a.indexOf(e,i+1)!=-1}).filter(function(e,i,a){return a.indexOf(e,i+1)==-1}).map(x=>document.querySelector("#"+x))`

Simply click one of the item from result of the above script to reveal this element in elements pane.

And if you right click and `copy > copy selector`, you will get non unique useless selector, at least for puppeteer.

What do you think?

By the way thank you very much for this great project.

**Comment by serkankazak** [comment]
Demo:

![](https://media.giphy.com/media/5wG3x19A3zxix74vxF/giphy.gif)

**Comment by aslushnikov** [comment]
This does make sense. I re-filled this upstream as a DevTools bug; please star https://crbug.com/848159
