### ISSUE TITLE
Wait for all xhr been resolved

### ISSUE THREAD

**Issue by b-ponomarenko** [puppeteer/puppeteer#2615]
Does puppeteer has API for handle case, when page send xhr response? Example
```html
<button id="btn" onclick="sendXHR()">Send</button>
```

`test.js`
```js
await page.click('#btn');
// some code which wait xhr response
```

As I understand, `page.waitForNavigation` api waits for redirect and not suitable for this case

**Comment by aslushnikov** [comment]
@b-ponomarenko you can subscribe to `'request'` events to sniff page's traffic. XHR's are distinguishable with their `rourceType()`:

```js
page.on('request', r => {
  if (r.resourceType() === 'xhr')
    console.log('XHR: ' + r.url());
});
```

Hope this helps.

**Comment by QuadTriangle** [comment]
for anyone here from google
https://github.com/jtassin/pending-xhr-puppeteer

**Comment by cr0cK** [comment]
Just some hints for future folks who will visite this page:

For initial loads, you can use:

```
await page.goto('http://example.com', {
  waitUntil: ['domcontentloaded', 'networkidle0']
})
```
