### ISSUE TITLE
Running async () code within a javascript function

### ISSUE THREAD

**Issue by rushix123** [puppeteer/puppeteer#2616]
I am using `electron` with `puppeteer`. When i run following code in my `main.js` It works perfectly.

Here is working code :

    `
    const puppeteer = require('puppeteer');

    (async () => 
    {
        const browser = await puppeteer.launch({ headless: false });

        const page = await browser.newPage();
        await page.setViewport({ width: 1366, height: 768});
    
        await page.goto('https://www.google.co.in', {waitUntil: 'networkidle2'});

    })();

`

But i want to open `Google Page` when i receive input from user in my app window. Then i am passing that input to `RunCommand` function, within which i want to open  `Google Page` as below :

### Steps to reproduce

    ```
    global.RunCommand = function(param)
    {
        const browser = await puppeteer.launch({ headless: false });
    
        const page = await browser.newPage();
        await page.setViewport({ width: 1366, height: 768});
    
        await page.goto('https://www.google.co.in', {waitUntil: 'networkidle2'});
 
  
        return 'Done : ' + param;
    }
```

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Mac Os
* URLs (if applicable):
* Node.js version: 10.2.0

**What is the expected result?**
When  `RunCommand` function is called then only i want to `launch`, `newPage`, `setViewport`, `goto` should happen and after completion; it should `return`

**What happens instead?**
Errors, warnings, exceptions

**Comment by aslushnikov** [comment]
YOu need to label your `RunCommand` function as `async`:

```js
global.RunCommand = async function(param) {
  // ...
}
```
