### ISSUE TITLE
Puppeteer doesn't capture some requests and JS errors

### ISSUE THREAD

**Issue by uriya2** [puppeteer/puppeteer#2617]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Ubuntu 16.04.4 LTS
* URLs (if applicable): https://nitzani1.wixsite.com/marketing-automation/3rd-page
* Node.js version: v8.11.1

**What steps will reproduce the problem?**
Running the code will reproduce the problem.

```
const puppeteer = require('puppeteer');

var  run = async () => {
    const browser = await puppeteer.launch({
        headless: false,
    });

    page = await browser.newPage();

    await page.on('error', err=> {
        console.log('err: '+err);
    });

    await page.on('pageerror', pageerr=> {
        console.log('pageerr: '+pageerr);
    });

    await page.on('requestfailed', rf => {
        console.log('requestfailed: '+rf);
    });

    await page.on('request', (request)=> {
        console.log(request.url());
    })
        await page.on('response', response => {
        const url = response.url();
        response.buffer().then(
            b => {
                if (response.status()!=200){
                    console.log(url+' : '+response.status())
                }
            },
            e => {
                console.log(url+' : '+response.status())
                console.log('response err');
            }
        );
    });

    await page.setViewport({ width: 1920, height: 1080 });
    await page.goto('https://nitzani1.wixsite.com/marketing-automation/3rd-page',
        {waitUntil: 'networkidle2', timeout: 120000});
};

run();
```
**What is the expected result?**
1. Catch request for https://api.fixer.io/1latest and the response of 404. Thought it will at least be visible by:
`    await page.on('request', (request)=> {
        console.log(request.url());
    })`
but it does not appear at the output at all.

2. Catch JS error: "Uncaught (in promise) Fetch did not succeed"
Used most of the page.on(someEvent) I could find in order to catch those errors, but could not.

Might I be listening to the wrong event? Maybe that request and error are executed by a worker and that's the reason I can't catch them? not sure at all, any help will be great

**Comment by aslushnikov** [comment]
The `https://api.fixer.io/1latest` is fetched from a service worker; we don't currently surface network traffic from service workers. This will be supported once we implement the ServiceWorker API, see #2634.

**Comment by uriya2** [comment]
thanks @aslushnikov , will wait for it
