### ISSUE TITLE
During loop there is no clicking on visible element of the page

### ISSUE THREAD

**Issue by maximkoshelenko** [puppeteer/puppeteer#2620]
Hello team. Please help me with current issue.
NPM version:
{ npm: '6.0.0',
  ares: '1.14.0',
  cldr: '33.0',
  http_parser: '2.8.0',
  icu: '61.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.29.0',
  node: '10.0.0',
  openssl: '1.1.0h',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.20.2',
  v8: '6.6.346.24-node.5',
  zlib: '1.2.11' }

Code:
```js
      await page.goto('http://www.practicalcardiology.com', { waitUntil: "load" });
      await page.waitForSelector('.expanded .menu');
      let numberOfFooterMenus = await page.$$('.expanded .menu');
      for (var a = 1; a <= numberOfFooterMenus.length; a++) {
        let numberOfLinksInMenu = await page.$$('.expanded:nth-of-type(' + a + ') a:not([target="_blank"])');
        for (var i = 1; i <= numberOfLinksInMenu.length; i++) {
          [response] = await Promise.all([
            page.waitForNavigation(),
            await closeFullScreenComm(),
            page.waitForSelector('.expanded:nth-of-type(' + a + ') li:nth-child(' + i + ') a:not([target="_blank"])'),
            page.click('.expanded:nth-of-type(' + a + ') li:nth-child(' + i + ') a:not([target="_blank"])')
          ]);
          expect(response._status).toBe(200);
          response = '';
          await page.goto(APP, { waitUntil: "load" });
        }
      }
```

If i run same test on http://www.endocrinologynetwork.com/ site,  clicking on all footer elements will work, but somehow on 'http://www.practicalcardiology.com' browser doesn't click on '.expanded:nth-of-type(4) li:nth-child(2) a:not([target="_blank"])' selector (but selector is visible on the page), and timeout is appear. 
<img width="1270" alt="2018-05-28 22 05 54" src="https://user-images.githubusercontent.com/35900275/40626769-63f02210-62c3-11e8-80f2-73800b779a4a.png">

**Comment by aslushnikov** [comment]
@maximkoshelenko there's a lot going on in your snippet; can you please re-file this issue with a snippet that I can actually run locally? This one has some weird `APP` variable and strange `closeFullScreenComm` function.
