### ISSUE TITLE
How to set header in puppeter just main page request not all request

### ISSUE THREAD

**Issue by mhf-ir** [puppeteer/puppeteer#2627]
* Puppeteer version: 1.4
* Platform / OS version: ubuntu
* URLs (if applicable): any
* Node.js version: 8.x

I want to just apply header in just opened page in puppeter not all inside page headers

  page.setExtraHTTPHeaders({
     'X-Just-Must-Be-Request-In-Main-Request': '1',
  })

will apply all pages request headers all css/js/images and etc...

i want to set just main request headers not all of pages requests.

no one cares:
https://stackoverflow.com/questions/50568054/how-to-set-header-in-puppeter-just-main-page-request-not-all-request

**Comment by aslushnikov** [comment]
@mhf-ir I've sent a PR to add a new method, `request.isNavigationRequest()`. Hopefully, it will be available in the next puppeteer release.

With this method, you'll be able to write the following:
```js
// enable request interception
await page.setRequestInterception(true);
// add header for the navigation requests
page.on('request', request => {
  // Do nothing in case of non-navigation requests.
  if (!request.isNavigationRequest()) {
    request.continue();
    return;
  }
  // Add a new header for navigation request.
  const headers = request.headers();
  headers['X-Just-Must-Be-Request-In-Main-Request'] = 1;
  request.continue({ headers });
});
// navigate to the website
await page.goto('https://example.com');
```

**Comment by Alex0007** [comment]
@aslushnikov Now it seems that the problem is

```js
        await page.setRequestInterception(true)

        page.on('request', (request) => {
            const headers = request.headers();
            headers['X-Just-Must-Be-Request-In-All-Requests'] = '1';
            request.continue({
                headers
            });
        });
```

With this snippet custom header is set only for main page request (but i need to set it for all requests)

**Comment by aslushnikov** [comment]
@Alex0007 worked fine for me; can you file a separate bug with a full script that we can run locally and see the issue?
