### ISSUE TITLE
Method to show if element is displayed

### ISSUE THREAD

**Issue by b-ponomarenko** [puppeteer/puppeteer#2629]
Does Puppeteer has API which help detect if element is visible (or displayed), analogue to Selenium (Webdriver) `.isDisplayed` method?

I found method [waitForSelector](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectorselector-options) method which has options `visible`, but I think if DOM node has `display: block;` and some parent component has style `overflow: hidden` and my element outside the parent this `waitForSelector` returns wrong

**Comment by ebidel** [comment]
Overflow "visibility" gets tricky. Using [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) would be more appropriate for this case. You can inject a snippet of IO code into the page and get the results using `page.evaluate`.

**Comment by aslushnikov** [comment]
> Using Intersection Observer would be more appropriate for this case.

@ebidel nice idea, we should use Intersection Observer for the `waitForSelector` implementation.

> Does Puppeteer has API which help detect if element is visible (or displayed), analogue to Selenium (Webdriver) .isDisplayed method?

Not yet, but it makes perfect sense to have `ElementHandle.isVisible()` that is aligned with `waitForSelector`'s implementation of visibility.

**Comment by yanivefraim** [comment]
@b-ponomarenko - can you help with a test case where `waitForSelector` with `visible` does not work for you?

**Comment by b-ponomarenko** [comment]
@yanivefraim yes, simple case is carousel, for example from all carousel items I want choose only visible, but waitForSelector with visible option returns all items.

**Comment by b-ponomarenko** [comment]
I try to inject script with IO:
‘’’js
 const isDisplayed = await page.evaluate(
        () => new Promise(resolve => {
          const callback = ([entry]) => resolve(entry.isIntersecting);
          const observer = new IntersectionObserver(callback, { root: null, rootMargin: '0px', threshold: 1.0 });

          observer.observe(document.querySelector('.ui-trading-main__product-title'));
          setTimeout(() => observer.unobserve(document.querySelector('.ui-trading-main__product-title')), 0)
        })
    );
‘’’
but have error stack trace
‘’’

Error: Protocol error (Runtime.callFunctionOn): Promise was collected undefined
    at Promise (/Users/b.ponomarenko/Desktop/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/b.ponomarenko/Desktop/puppeteer/lib/Connection.js:201:12)
    at ExecutionContext.evaluateHandle (/Users/b.ponomarenko/Desktop/puppeteer/lib/ExecutionContext.js:79:75)
    at ExecutionContext.evaluate (/Users/b.ponomarenko/Desktop/puppeteer/lib/ExecutionContext.js:46:31)
    at Frame.evaluate (/Users/b.ponomarenko/Desktop/puppeteer/lib/FrameManager.js:326:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
‘’’
what can be wrong?

**Comment by pavelbinar** [comment]
Hi guys, I am getting bit lost in the various discussions and implementation efforts regarding visibility gong on here :)

You was discussing the visibility in the viewport... I have slightly different problem.

I am trying to wait for the element which is present in the DOM, but is not visible from human point of view - it is overlaid by video.

Is there a way how to detect if the element is visible by human and clickable?
Even if that would be temporary workaround.

If I am posting it into wrong ticket, sorry for that and feel free to correct me.

Thanks!
