### ISSUE TITLE
The "page.cookies(...urls)" do not return httponly cookie

### ISSUE THREAD

**Issue by bluemind7788** [puppeteer/puppeteer#2630]
The function  "page.cookies(...urls)" only return some of the cookies. I hope to get all the cookies especially the httponly ones.
Is this a problem or an uncompleted feature?
Thanks~

**Comment by softmantk** [comment]
@bluemind7788 I too have the same problem. Does anybody have a solution?

**Comment by daijia** [comment]
You can use [CDPSession](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-cdpsession)  with method [Network.getAllCookies](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getAllCookies)
 the reason why does not return http only cookie, see [this](https://stackoverflow.com/questions/1022112/why-doesnt-document-cookie-show-all-the-cookie-for-the-site)

**Comment by aslushnikov** [comment]
@bluemind7788 @softmantk any script I can run locally to debug the issue?
