### ISSUE TITLE
Can we run puppeteer like a actual browser with all property which actual browser have?

### ISSUE THREAD

**Issue by RubiTTN** [puppeteer/puppeteer#2638]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
Yes, just pass `headless: false` in [`puppeteer.launch`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-puppeteerlaunchoptions)
