### ISSUE TITLE
Cann't evaluate ` element.childern[i]`

### ISSUE THREAD

**Issue by saltfish666** [puppeteer/puppeteer#2639]
## environment
* Puppeteer version: ^1.4.0
* Platform / OS version: macOS Sierra 10.12.6
* URLs (if applicable):  https://translate.google.com/#en/zh-CN/moon
* Node.js version: v8.7.0

## Google translate

<img width="1115" alt="screen shot 2018-05-31 at 6 14 04 pm" src="https://user-images.githubusercontent.com/37469825/40776797-6c301e0c-64fe-11e8-8ecc-acf66cf6bcec.png">

this is right dom operation

## puppeteer
I want get n-th child of an elementNodes
```
const puppeteer = require('puppeteer');

(async () =>{
   const browser = await puppeteer.launch({headless:false});
   let page = await browser.newPage();
   await page.goto(`https://translate.google.com/#en/zh-CN`);
   let task ={
      src:"moon",
      from:"en",
      to:"zh-CN"
   };
   await page.evaluate((task)=>{
      document.getElementById("source").value = task.src;
   },task);
   page.click("#gt-submit");
   let res = await page.evaluate(()=> {
      console.log(document.getElementById("result_box"));
      console.log(document.getElementById("result_box").children);
      console.log(document.getElementById("result_box").children[0]);
      console.log(document.getElementById("result_box").firstChild);
   });
   browser.close();
})();
```
but I can not get right result:
<img width="1181" alt="screen shot 2018-05-31 at 6 18 49 pm" src="https://user-images.githubusercontent.com/37469825/40777122-778a00aa-64ff-11e8-97d4-7d1cf48de2aa.png">

as you can see,puppeteer can not eval `document.getElementById("result_box").children[0]` even if it can get `document.getElementById("result_box").children`

and then:can not eval `document.getElementById("result_box").innerText`

**Comment by vsemozhetbyt** [comment]
Try this:
```js
  page.click("#gt-submit");
  await page.waitForSelector("#result_box > span");
```
