### ISSUE TITLE
console message from Webworker receives only first argument

### ISSUE THREAD

**Issue by yanivefraim** [puppeteer/puppeteer#2640]
When using `page.on('console'...` on a console from a WebWorker, only first argument is printed.

In the following example, only 'a' will be logged:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', message => console.log(message.text()));
  await page.setContent(`<!DOCTYPE html>
  <script id="worker1" type="javascript/worker">
    console.log('a', 'b'); //only 'a' will be logged
  </script>
  <script>
    const blob = new Blob([
      document.querySelector('#worker1').textContent
    ], { type: "text/javascript" })

    new Worker(window.URL.createObjectURL(blob));
  </script>`);
})()
```

**Comment by yanivefraim** [comment]
After a short debug, seems like [Log.entryAdded](https://chromedevtools.github.io/devtools-protocol/tot/Log#event-entryAdded) sends only first argument in case of a Webworker.

**Comment by JoelEinbinder** [comment]
It looks like Log.entryAdded doesn't work. Filed upstream as: https://bugs.chromium.org/p/chromium/issues/detail?id=848965

**Comment by aslushnikov** [comment]
@JoelEinbinder why do we listen to `Log.entryAdded`? We should use `Runtime.consoleAPICalled` event instead.

**Comment by newlifewj** [comment]
I see the message.type() is not consistent with Chrome dev console output, the warning message showing in Chrome dev-console as errors.
