### ISSUE TITLE
Self signed certificate error: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by budarin** [puppeteer/puppeteer#2642]
### Steps to reproduce
- create selfsigned certificate with CA
- imstall CA certificate into certificate storage for Root Trusted certificate
- open a page of you local dev server in Chrome
- add site to exceptions
- ensure the page is rendered normally
- try to open the page with puppeteer in jest test

**Tell us about your environment:**

* Puppeteer version: "^1.4.0"
* Platform / OS version: Windows Server 2008R2
* URLs (if applicable): https://github.com/budarin/react-bootstrap-project
* Node.js version: 10.1.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. run the test
```js
const timeout = 10000;

describe(
    '/ (Home Page)',
    () => {
        let page;
        beforeAll(async () => {
            page = await global.browser.newPage();
            await page.goto('https://localhost');
        }, timeout);

        it('should load without error', async () => {
            const text = await page.evaluate(() => document.body.textContent);
            expect(text).toContain('Hello World');
        });
    },
    timeout,
);
```
2. set ignoreHTTPSErrors to true
```js
        this.global.browser = await puppeteer.connect({
            browserWSEndpoint: wsEndpoint,
            ignoreHTTPSErrors: true,
        });
```

**What is the expected result?**
succesfull test

**What happens instead?**
test is faled with error  net::ERR_CONNECTION_REFUSED at https://localhost

**Comment by aslushnikov** [comment]
@budarin I failed to reproduce your issue. Can you come up with a minimal puppeteer script that I can run locally to reproduce your issue?

**Comment by budarin** [comment]
I can't create code simpler - I work on react project and try to integrate testing with puppeteer
also try to open chromium with the local page - there is no usual link on a page with adding the site to exceptions while Chrome has - so once adding the site to exceptions allow it render without error in a future - the problem is in security in chromium

**Comment by aslushnikov** [comment]
> I can't create code simpler

From what I see, this is something going on with your environment / techstack.

If you have any code that I can run locally and can give me a very detailed instruction on how to do so, I can try looking into it.

**Comment by budarin** [comment]
No, problem is not in my environment - the problem is in different security options in chrome and chromium.
I have self signed certificate and chrome takes it after manual adding to security exceptions but chromium does not have such option!
if I use chrome in tests instead chromium - there is no problems with it - it only requires once accept the site to exceptions

**Comment by aslushnikov** [comment]
@budarin oh wait, I think I didn't understand the usecase.

> I have self signed certificate and chrome takes it after manual adding to security exceptions but chromium does not have such option!

Can you talk about this more? Is this something related to #540?

**Comment by budarin** [comment]
I'm sorry :( - here is the magic - there is no any errors but it was and repeted steadly
So I close the issue.
Thanks a lot for the help!
