### ISSUE TITLE
calling addScriptTag returns Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: Event

### ISSUE THREAD

**Issue by chenweiLabri** [puppeteer/puppeteer#2644]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: "^1.4.0"
* Platform / OS version:  macOS 10.13.1
* URLs (if applicable):  https://github.com/webAutomaticTest/pageEvaluate
* Node.js version: v8.11.2
I download the **optimal-select.js** from  https://cdnjs.cloudflare.com/ajax/libs/optimal-select/4.0.1/optimal-select.js

**What steps will reproduce the problem?**
I want to do automatic test about web applications.
1. run to test with command:  
```
node index.js
```
the code in index.js:
```
const puppeteer = require('puppeteer');

test();

async function test(){
	const browser = await puppeteer.launch({headless: false, args:['--no-sandbox']});
	const page = await browser.newPage();
	await page.goto('https://twitter.com/');
	// await page.goto('https://apples-oranges.herokuapp.com/');
	await page.addScriptTag({path:'./optimal-select.js'});
	
	let candidateSelector = await page.evaluate(scanCandidateAction);
	console.log(candidateSelector);
}

function scanCandidateAction() {
	let actions = [];
	let computeCSSSelector = window['OptimalSelect'].select;
	let aElements = document.querySelectorAll('a');
	for (let i=0 ; i < aElements.length ; i++) {
		if (! isMailTo(aElements[i])) actions.push(computeCSSSelector(aElements[i]));
	}

	return actions;

	function isMailTo(element) {
		let href = element.href;
		return href && (href.toLowerCase().indexOf('mailto') > -1)		
	}
}
```

**What is the expected result?**
array of CSS Selector
**What happens instead?**
it faled with error:
 (node:83553) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Event
It stoped and filed in this line:
```
await page.addScriptTag({path:'./optimal-select.js'});
```

**Comment by chenweiLabri** [comment]
In the source code, 
If I change this following two line:
```
await page.goto('https://twitter.com/');
// await page.goto('https://apples-oranges.herokuapp.com/');
```
to:
```
//await page.goto('https://twitter.com/');
await page.goto('https://apples-oranges.herokuapp.com/');
```
It will works, I can get the array of css selector.

### it means that:
I can test web site https://apples-oranges.herokuapp.com/
But I can not test website https://twitter.com/ using **addScriptTag**

**Comment by chenweiLabri** [comment]
Is it the issue for pages with CSP: [#1229](https://github.com/GoogleChrome/puppeteer/issues/1229) ? or not ?

**Comment by aslushnikov** [comment]
@chenweiLabri yes, this is due to CSP. if you call `page.setBypassCSP(true)` before navigating, the issue goes away.

Our error is not very descriptive though; it should be possible to detect CSP violation using the [`Log.entryAdded`](https://vanilla.aslushnikov.com/#Log.LogEntry) protocol event. There's been an effort before but we didn't finish it: https://github.com/GoogleChrome/puppeteer/pull/1624

This would be nice to have though specifically for the `addScriptTag` and `addStyleTag` methods since they are hitting our users most.

**Comment by yanivefraim** [comment]
@aslushnikov - I want to help with this, just want to figure out exactly what you meant :

Do we want to have something like:

```js
this._client.on('Log.entryAdded', event => {
      if (event.entry.source === 'security')
        throw new Error(JSON.stringify(event));
});
```

Inside FrameManager's `addScriptTag` and `addStyleTag`?

**Comment by aslushnikov** [comment]
@yanivefraim yeah, along these lines. I'd also inspect log entry's stack and make sure it comes from our function

**Comment by yanivefraim** [comment]
@chenweiLabri  - why did you close this one?

**Comment by chenweiLabri** [comment]
@yanivefraim  for me, I call page.setBypassCSP(true) before navigating temporarily solve my problem.

**Comment by xD-saleem** [comment]
> @yanivefraim for me, I call page.setBypassCSP(true) before navigating temporarily solve my problem.

thanks a million!

**Comment by KevinG-Acc** [comment]
2022 : Using  page.setBypassCSP(true) still works. 

We are using pupetter and has to insert script into the evaluated page but some of the website we have to manage seems to refuse (Twitter, linkedin, reddit etc).

This line seems to works fine and allow us to perform the function we need.

Thanks a lot !
