### ISSUE TITLE
Puppeteer is not running inside windows docker container

### ISSUE THREAD

**Issue by mayukhgit** [puppeteer/puppeteer#2647]
As per https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker, I see there is some trick that we need to make the puppeteer to run inside Linux container. Is there a solution for Windows container as well?

**Tell us about your environment:**

* Puppeteer version: 1.4
* Platform / OS version: Windows Container hosted in Windows Server 2016
* URLs (if applicable):
* Node.js version: 8.11.2

**Comment by mayukhgit** [comment]
Turns out to be a simple solution. Windows containers are running under Hyper-V isolation and for some reason Puppeteer can not run under that environment with default settings (sandbox mode on). I have applied the following fix in my script https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues and now it is working as expected.

Seems there is no tricks required like Linux containers and its much more simple in Windows Container.

**Comment by jakejscott** [comment]
@mayukhgit Do you mind sharing your Dockerfile for Windows?

**Comment by Abrissirba** [comment]
@mayukhgit If possible I would like to see the Dockerfile aswell.

**Comment by isaac-s** [comment]
> Turns out to be a simple solution. Windows containers are running under Hyper-V isolation and for some reason Puppeteer can not run under that environment with default settings (sandbox mode on). I have applied the following fix in my script https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues and now it is working as expected.
> 
> Seems there is no tricks required like Linux containers and its much more simple in Windows Container.

The link is inaccurate as it refers to `master` that has since been changed.

Correct permalink: https://github.com/puppeteer/puppeteer/blob/de82b87cfa1c637787a09b90266318905ae16f42/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues
