### ISSUE TITLE
Can the error message be more specific?

### ISSUE THREAD

**Issue by li-01** [puppeteer/puppeteer#2653]
Error: waiting for selector "#closemsgboxbtn" failed: timeout 30000ms exceeded
      at Timeout.WaitTask._timeoutTimer.setTimeout (node_modules\puppeteer\lib\FrameManager.js:844:60)

I always got this kind of error msg, but I still need to spend a lot time finding which exact line in my js file throwing out the error.
Is there any option I can set up?

**Comment by aslushnikov** [comment]
@li-01 we can make stacktraces much more specific for the `page.waitForSelector` at least. For this, we'd need to capture a stacktrace in `waitForSelector` and save it later on in `WaitTask` class.

This is not very involved; I'd be happy to review a PR for this.
