### ISSUE TITLE
[macOS] Error: Protocol error (Page.captureScreenshot): Target closed.

### ISSUE THREAD

**Issue by ptkdev** [puppeteer/puppeteer#2655]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: macOS 10.13.4
* URLs (if applicable): [function screenshot](https://github.com/social-manager-tools/instagram-bot.js/blob/0.7.0/modules/utils.js)
* Node.js version: 8.X

**What steps will reproduce the problem?**
All time i received error `Protocol error (Page.captureScreenshot): Target closed.`, try-catch is ignored and browser crash (??? why with try-catch?).

I try any solution, any variants (clip instead of fullPage, without clip and fullPage, set size of browser to 800x600, jpg format, png format, with headless, without headless, etc...). Is impossible for me get screenshot on mac. Every time crash only on mac (windows and linux work). What is correct code for mac? 
```
        try {
            await page.screenshot({ fullPage:true, type:"png",  path: "./screenshot/test.png" });
        } catch (err) {
            console.log(err);
        }
```

**What is the expected result?**
Screenshot png in screenshot folder.

**What happens instead?**
`Error: Protocol error (Page.captureScreenshot): Target closed.`

**Comment by aslushnikov** [comment]
@ptkdev this has something to do with the environment; the `target closed` error usually happens when there's lack of memory or some other constraint. You can try running browser with `dumpio: true` and check Chrome's error log - it will hint towards the real thing that happens in the browser.
