### ISSUE TITLE
Can we remove browser focus when doing screenshot on non-headless mode?

### ISSUE THREAD

**Issue by fusionx1** [puppeteer/puppeteer#2656]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  1.4
* Platform / OS version: macOs
* URLs (if applicable):
* Node.js version: 8.10

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
'use strict';

const puppeteer = require('puppeteer');

  const browser = await puppeteer.launch({
    executablePath: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome",
    headless: false,
    timeout: 180000,
  });
  
  const page = await browser.newPage();
  await page.goto('http://example.com');
  await page.screenshot({path: 'example.png'});

  const page2 = await browser.newPage();
  await page2.goto('http://example2.com');
  await page2.screenshot({path: 'example2.png'});

  await browser.close();
})();
```

**What is the expected result?**
it shouldn't steal focus when in another application when its trying to do a screenshot

**What happens instead?**
It steals focus

**Comment by aslushnikov** [comment]
> What happens instead?
It steals focus

Unfortunately, this is not feasible. In headful mode, we *have* to activate tab before screenshotting it.

**Comment by avalanche1** [comment]
I've the same issue (focusing the browser) when Puppeteer opens a new tab.
Can it be avoided?
https://stackoverflow.com/questions/60321191/puppeteer-stop-bringing-chromium-to-front
