### ISSUE TITLE
Puppeteer: how to manage time like a fake timers in Jasmine do?

### ISSUE THREAD

**Issue by budarin** [puppeteer/puppeteer#2664]
I've asked on stackoverflow, but without an answer (
https://stackoverflow.com/questions/50626353/puppeteer-how-to-manage-time-like-a-fake-timers-in-jasmine-do

I need to manage time in browser with puppeteer.
I 've not found any suitable devtool protocol, so ask for help

**Comment by aslushnikov** [comment]
@budarin Puppeteer doesn't yet provide a native solution to control page timers. There are some chances it'll happen eventually, but its still unclear.

There are some user land solutions, e.g. https://github.com/sinonjs/lolex. I'd try using [`page.addScriptTag`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pageaddscripttagoptions) to add the library into the page and then use it from-inside the page with puppeteer's [`page.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pageevaluatepagefunction-args).

Hope this helps.

**Comment by budarin** [comment]
thanks!

**Comment by adrianschmidt** [comment]
It took me a good long while to figure out how to do this, so I'll post my solution here in case someone else needs it.

This answer on StackOverflow was quite helpful: https://stackoverflow.com/questions/50626353/puppeteer-how-to-manage-time-like-a-fake-timers-in-jasmine-do/51832367#51832367

But I had to change the url to point to the browser-compatible version of the library instead: 

```ts
await page.addScriptTag( {
    'url' : 'https://cdn.jsdelivr.net/npm/lolex@2.7.1/lolex.min.js'
});
await page.evaluate(() => {
    const clock = lolex.createClock();
    clock.setTimeout(() => {
        console.log('Hello, world!');
    }, 500);
    clock.tick(500);
});
```

Another issue I had was that `page.setContent()` seems to effectively reset the page, thus removing lolex from the page. At the moment, my solution looks something like this:

```ts
describe('blah blah', () => {
	beforeEach(async () => {
		page = await createPageWithFakeTimers(`
		    <my-custom-button label="Save"></my-custom-button>
		`);
	});

	…snip…

	describe('after 2 seconds', () => {
	    beforeEach(async () => {
	        await page.evaluate(() => {
	            window.clock.tick(2000);
	        });
	        await page.waitForChanges();
	    });
	    it('has done something', () => {
	    	…snip…
	    });
	});
});

async function createPageWithFakeTimers(content) {
    const page = await createPage(content);
    await page.addScriptTag({ content: lolex() });
    await page.evaluate(() => {
        window.clock = window.lolex.install();
    });
    return page;
}

async function createPage(content) {
    return newE2EPage({ html: content });
}

function lolex() {
    return '<the whole minified lolex-file as a string>';
}
```

**Comment by lehni** [comment]
For those who'd like to use the newer `@sinonjs/fake-timers` instead of `lolex` in a puppeteer context, here's how I managed to make it work. You just need to emulate enough of the `require()` and `exports` structures for it to work with this particular source file:

```js
  async useFakeTimers(page, date) {
    const FakeTimers = await fs.readFile(
      './node_modules/@sinonjs/fake-timers/src/fake-timers-src.js',
      'utf8'
    )
    await page.evaluateOnNewDocument(`
      const FakeTimers =(() => {
        const require = function(name) {
          switch (name) {
            case '@sinonjs/commons':
              return { global: this };
            default:
              return null;
          }
        };
        const exports = {};
        ${FakeTimers};
        return exports;
      })();
      FakeTimers.install({
        shouldAdvanceTime: true,
        now: ${date.getTime()},
      });
    `)
  }
```
