### ISSUE TITLE
when i use page.type() to input text in different input tag, it does not work.

### ISSUE THREAD

**Issue by luneice** [puppeteer/puppeteer#2667]
1. when i execute that
await page.type('input#loginName', 'text1', {delay: 300});
await page.type('input#loginPassword', 'text2', {delay: 100});
i find that text2 is inputed, text1 is not inputed.

2. when i execute that
await page.type('input#loginPassword', 'text2', {delay: 100});
await page.type('input#loginName', 'text1', {delay: 300});
i find that text1 is inputed, text2 is not inputed.

how can i fix this problem?

**Comment by aslushnikov** [comment]
@luneice can you help me reproducing this? I'd need a small puppeteer script that navigates to a certain URL and demonstrates the problem.

Once I can run it locally, I'd be able to fix this.
