### ISSUE TITLE
Launching multiple browser instances and manage events

### ISSUE THREAD

**Issue by mhaseebkhan** [puppeteer/puppeteer#2670]
I am working on a project which involves a multi-user scenario.

The use-case is such that multiple users can hit an end-point for information which involves launching puppeteer and browsing through various URLs.

In the implementation, if the puppeteer instance launched completes its end to end execution in one go for a single user, then, everything works great, however, if there is a puppeteer execution in process and another request comes in which tries to use the same codebase, then, everything breaks. Even the first request isn't completed.

My question is from a design and implementation perspective as what are the best practices recommended by the puppeteer community to tackle multi-user scenarios. Any examples will certainly be very helpful.

**Comment by mhaseebkhan** [comment]
I have tried using `BrowserContext` as well, using which, I can open multiple browser windows, however, as soon as the second browser window is opened, events for the first one are swallowed.

How can I launch multiple browser windows such that each window is responsible for handling and managing its respective events?

@aslushnikov: Your input in this regard will be highly appreciated.

**Comment by aslushnikov** [comment]
> if there is a puppeteer execution in process and another request comes in which tries to use the same codebase, then, everything breaks. Even the first request isn't completed.

@mhaseebkhan I don't quite follow this scenario. Can you come up with a small runnable script that illustrates the issue?

**Comment by hkhan-lumatax** [comment]
Sure, @aslushnikov. I will come up with something and share that here.

**Comment by mhaseebkhan** [comment]
@aslushnikov: [Here](https://drive.google.com/file/d/143neKzWTdGrZXvOnTexm6xh_WLwHzY48) is a test script containing a `README` with instructions.

Please have a look and suggest.

**Comment by zouhair94** [comment]
i face the same problem right now if there is any solution

**Comment by levelingup** [comment]
+1 would like to know.

**Comment by magnnus** [comment]
+1 would like to know.

**Comment by rajkumar3223** [comment]
+1
