### ISSUE TITLE
When the target element width is zero, elementHandle.screenshot does not work. 

### ISSUE THREAD

**Issue by boiawang** [puppeteer/puppeteer#2672]
**Tell us about your environment:**

* Puppeteer version: v1.4.0
* Platform / OS version: linux
* Node.js version: v8.11.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer = require('puppeteer');

const browser = await puppeteer.launch({
  args: ['--no-sandbox', '--disable-setuid-sandbox']
});
const page = await browser.newPage();
const SCREENSHOT_FILE = 'screenshot.png';

await page.goto('xxx.com');
await page.waitForSelector('div'); 
const areaContainer = await page.$('div');

await areaContainer.screenshot({
  path: SCREENSHOT_FILE
});
console.log('screenshot end');   // cannot execute to this line
await browser.close();
```

**What is the expected result?**

`console.log('screenshot end')` cannot execute when div has no width and height.

**What happens instead?**

I hope it shouldn't be blocked, Or throw a error?

**Comment by aslushnikov** [comment]
@boiawang I can't repro this with pptr v1.5.0 and with the following script:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent('<div style="width: 0; height: 0"></div>');
  const div = await page.$('div');

  await div.screenshot({
    path: 'screenshot.png'
  });
  console.log('screenshot end');   // cannot execute to this line
  await browser.close();
})();
```
We might've fixed this in puppeteer v1.5.0; speculatively closing this.
If you still experience this on pptr v1.5.0, feel free to write here or re-file another one with a good repro.

**Comment by pkra** [comment]
@aslushnikov The minimal example you had posted hangs for me using v1.7.0. Does it (still) work for you?

**Comment by pkra** [comment]
@aslushnikov for more background, I see this on Linux (Ubuntu 18.04), node v10.9.0, puppeteer v1.7.0, chromium r579032.

**Comment by aslushnikov** [comment]
@pkra: works nicely for me. I think we even have a test that makes sure this scenario is functioning.

**Comment by pkra** [comment]
@aslushnikov thanks for the response. This still consistently hangs for me on Linux (Ubuntu 18.04), node v10.9.0, chromium r588429.

Would you have ay advice on how to dig deeper into this?

**Comment by aslushnikov** [comment]
@pkra hmm I didn't find a test for this; I've added one - let's see how it performs on our trybots.

**Comment by aslushnikov** [comment]
Ah, linux is busted indeed.

**Comment by pkra** [comment]
Thanks so much for looking into it, @aslushnikov!
