### ISSUE TITLE
Suggestion: stable/tested Docker image provided by puppeteer team

### ISSUE THREAD

**Issue by stopsopa** [puppeteer/puppeteer#2676]
It would be nice if Puppeteer team would provide and maintain official Docker container with Puppeteer because lots of issues here are about problems with Docker container, and people (including me) have lots of different approaches to this subject but eventually they experiencing and describing similar problems with having stable and working image with Puppeteer and its generate lots of noise here in puppeteer Issue tracker.

Example - all below issues actually describe one issue (IMO) but it's hard to detect because it works fine on Mac (according to my extensive tests) but it appears on Linux which is usually production/target OS:

- [github repo issue 1464](https://github.com/GoogleChrome/puppeteer/issues/1464#issuecomment-349568640) 
- [github repo issue 1828](https://github.com/GoogleChrome/puppeteer/issues/1828)
- [1610](https://github.com/GoogleChrome/puppeteer/issues/1610)
- [1852](https://github.com/GoogleChrome/puppeteer/issues/1852)
- [stackoverflow heroku deployment](https://stackoverflow.com/questions/48542991/puppeteer-pdf-blank-on-heroku)
- [1925](https://github.com/GoogleChrome/puppeteer/issues/1925)
- [chromium issue 383314](https://bugs.chromium.org/p/chromium/issues/detail?id=383314)

**Comment by palmerj3** [comment]
It's not exactly what you're asking for. But I built a cloud builder (really just a docker container that has puppeteer and yarn as an entrypoint) which is capable of running puppeteer on CI for apps that use yarn (node). https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/yarn-puppeteer

Aside from the yarn part you could base a docker image largely off that and open source it. Mine was largely based off the puppeteer documentation.

**Comment by aslushnikov** [comment]
> It would be nice if Puppeteer team would provide and maintain official Docker container with Puppeteer 

@stopsopa To my knowledge, there are some successful projects that run puppeteer in docker (e.g. @joelgriffith's [browserless](https://github.com/joelgriffith/browserless)).

We still hope that Puppeteer community will converge on a single well-maintained docker container that will address most needs. We'll be glad to refer to it in our docs.

**Comment by ebidel** [comment]
@stopsopa what more would you like to see here? We have an official Dockerfile example in https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker. I'm not sure we need to maintain a container b/c it's easy enough to take that file and build the image yourself.

**Comment by stopsopa** [comment]
@ebidel I agree, and eventually I've used this example...
just would be nice to have official puppeteer docker image ready to pull, that's all
well... Issue is closed anyway, fair enough then.
