### ISSUE TITLE
Is the only way to communicate through console.debug? [Security]? (scoped exposed functions)

### ISSUE THREAD

**Issue by tolmasky** [puppeteer/puppeteer#2678]
So, this is kind of a two part question/bug-report(?). It all started when I was trying to find a way to expose an external function (ala exposeFunction), but *just* to the scope of a `page.evaluate()`. Through looking into this, I discovered some interesting ways for arbitrary pages to break puppeteer, if their goal was to for example prevent headless Chrome from visiting them potentially, or worse, to attempt to break out of headless Chrome and possibly do nefarious things on the puppeteer process.

So, as  mentioned, this all started with me wanting to do something like this:

```javascript
page.evaluate(puppeteerFunction => puppeteerFunction("called from client"), msg => console.log("properly scoped: " + msg));
```
In other words, I'd like to expose a function solely to my own custom evaluations within the page, rather than making them globally available for all scripts. I started poking around at the implementation of page.exposeFunction, and it seems that fundamentally the only way to get information "out" of the client and into puppeteer is through logging, as exposeFunction seems to log messages to be decoded through console listeners on the server end.

Even if there was a way to hide an exposed function from the global scope, such as this:

```javascript
await page.exposeFunction("exposedFunction", ...);
// In my tests this doesn't actually work:
await page.evaluate(function ()
{
     var scoped = window.exposedFunction;
     delete window.exposedFunction;
     // Now only we can use exposedFunction. Again, in my experiments this doesn't work,
     // not to mention the fact that there exists a window where window.exposedFunction is
     // usable to anyone.
})
```

Anyways, if this strategy *did* work, then an adverserial script on the page could still mess around with `console.debug` to spark evaluations on the server:

```javascript
console.debug("driver:page-binding", JSON.stringify({"name":"f","seq":1,"args":[]}))
```

In fact, a page could simply override `console.debug` to listen to whether they are in a puppeteer environment:

```javascript
var original = console.debug;
var knownFunc = "";
console.debug = function (...args)
{ 
   if (args[0] !== "driver:page-binding")
      return original(...args);

   knownFunc = JSON.parse(args[1])["name"];
   // now I can start sending it stuff.
}
```

Interestingly enough, if your only goal is to create havoc (vs. say, try to "break out" of the page), then you can just do `console.debug("driver:page-binding", "invalid_json")` to make puppeteer angry, regardless of whether any functions have been exposed. The resulting exception seems to be caught at some point though, and thus the flow of the puppeteer program will not be halted (not sure if this is a good thing or a bad thing).

Anyways, all this to say, it would be nice if there was a JSHandle-like system to go from server to client. Or, *perhaps* simpler, a message passing system that could be scoped to just the single evaluate (which would be cleared after the evaluate returns or when the evaluates Promise resolves/rejects to properly define lifecycle, so that more complex function systems could be built on top, much like the console.debug system currently in use is):

```javascript
page.evaluate(postMessage => postMessage("hello"), function receiveMessage(msg) { })
```

My only thoughts so far to make a tamper-proof / scoped system is to employ private/public key pairs and use the same console.debug strategy:

```javascript
evaluateWithPostMessage = async function (f, receiveMessage, ...args)
{
    const keys = generate_key_pair();
    page._client.on('Runtime.consoleAPICalled', function (msg)
    {
          if (event.type !== "debug") return;
          if (event.args[0] !== "private-message") return;
 
          const message = decrypt(event.args[1], keys.public);

          // Message not intended for us, or something weird going on.
          if (message.substr(0, "private-message:".length) !== "private-message:")
               return;
          
          // Actually call function...
          const result = receiveMessage(msg.substr("private-message:".length));

          // Do the work of passing a result back.
    });
    await page.evaluate(function (code, key, ...args)
    {
         var postMessage = msg => console.debug("private-message", encrypt("private-message:" + msg, key));
         var compiled = new Function("postMessage", `return ${code}([].slice.apply(arguments, 1))`);
 
         return compiled(postMessage, ...args);
    }, f + "", keys.private, ...args);
}
```

Anyways, I'm happy to do all this if it's the only way, but I feel like there must be a better or more official way of passing an external function into a script to evaluate and to limit its scope just to that. Separately, ideally such a system could be expanded to the normal exposeFunction to avoid the potential for arbitrary pages to crash puppeteer.

**Comment by aslushnikov** [comment]
Hey @tolmasky,

Sorry it took me so long to get to your bug report, this was an interesting read.

Indeed, we used to do `console.debug` for message-passing; this is no longer the case since we landed https://github.com/GoogleChrome/puppeteer/pull/2631. With this patch we now use protocol's [`Runtime.addBinding`](https://vanilla.aslushnikov.com/#Runtime.addBinding), so the attack you described here will be a little bit harder to perform. Still, it's very much doable.

> Or, perhaps simpler, a message passing system that could be scoped to just the single evaluate

You can now do this using protocol's `Runtime.addBinding` and subsequent `page.evaluate` that grabs the binding; you mentioned it didn't work for you, but I'm quite sure I had a code somewhere that was re-using this exact approach.

For your purposes I'd pass in `executionContextId` as one of parameters for `Runtime.addBinding`. This way you'll scope the binding to the particular frame and iirc the binding won't be re-installed after navigation.

Our of curiosity, what's the usecase that makes you organize this kind of communication?

**Comment by tolmasky** [comment]
Hi @aslushnikov,

Thanks for the response. Our use case is that we currently use Puppeteer for our integration tests (and we will probably be releasing our framework for doing so as open source at some point). We basically had two concerns that arose:

1. **Security**
This applies specifically to uses of addBinding. Our product (that is, the product we are TESTING with said framework) currently uses a number of third party resources (such as typekit for example), as I am sure is quite common. Thus, the code we're running isn't *just* code we're completely in control of. My concern level is heightened with regard to running tests automatically in a CI environment if we are ever pulling what essentially amounts to untrusted code in a non-sandboxed environment. Prior to installing any custom functions into Puppeteer, we can basically trust the browser's separation to provide said sandbox. However, every addBinding we choose to employ creates a potential escape hatch for hijacked third party resources to, on the low end denial of service our CI/deploy, and on the high end potentially break out (ala the Electron vulnerabilities we have seen).

2. **General encapsulation to not break stuff**
This part is more straight forward and doesn't have anything to do with addBinding, just adding any code at all. Some tests run in the browser's context. For example, our product is an API, so we want test that the callbacks are called correctly (pseudo-code provided below):

```javascript
// page.static is a method we created to load static html.
await page.static("<script src = "our-great-api.com"></script>")
await page.evaluate(() =>
{
     const callback = expect.mock.fn();
     ourAPI.doStuff(callback);
     expect(callback).toHaveBeenCalled();
});
```

So here the idea is that `expect` is defined globally (probably through `evaluateOnNewDocument`). We just don't want to have it available globally or polluting the global namespace so that 1) it can't be mutated by accident by someone, and also 2) doesn't potentially accidentally confuse third party scripts we include on the page (this is why simply scoping it to a single frame isn't sufficient). Again, the thing to remember is that our product (and many products) do include third party scripts and while we can correctly scope all our APIs, these "extra" testing functions can't.

Here are a few ideas we've played around with:

1. We could auto-wrap the evaluated code and include these special functions every time. Something like this:

```javascript
page.testEvaluate = function (f)
{
    this.evaluate(`(expect => ${f + ""}())(${expect_definition})`);
}
```
This seems unfortunate to rerun the entirety of the source code of every library we want to provide on each test.

2. Piggy-back off of import/request interception. Similar to before, only we have a "secret" URL that holds these libraries, like "https://us/0298748930985940", which we intercept and return the source code for. So something like:

```javascript
page.testEvaluate = function (f)
{
    this.evaluate(`import expect from "https://us/0298748930985940" ${f + ""}()`)
}
``` 

This has the benefit that we can theoretically also expose this to script tags for situations where we'd like to have a more declarative way of doing things first vs. having to always rely on `evaluateOnNewDocument`:

```javascript
await page.static(`
<script>
      import expect from "https://our-libraries/expect"
      didLoadCallback = expect.fn.mock();
</script>
<script src = "our-great-api.com" data-load-callback="didLoadCallback"></script>")
`);

await page.testEvaluate(() => expect(didLoadCallback).toHaveBeenCalled());
```

The problem here is of course now "https://our-libraries/expect" is once again available to third party scripts (and they get the object identical copy, so mutations are possible).

Hopefully this sheds a little light into what we are doing. Basically, we'd like a way to have an "testing context" with functions not available and changing the code being tested. We can accomplish something close with the import trick (we'd probably use the secret URL method since otherwise we're right back where we started with it being globally available).

I think that's as far as we can get by operating on top of the Puppeteer API, however, from inside Puppeteer it would be nice to have a more official way of creating an expanded context for "orchestrator" separate from the page that is being manipulated (similar to the way that the Console is expected to be used by the user, not the page itself). From an API perspective, what was originally requested with .evaluate(functionHandles => code, functions) that scopes those variables to just that one evaluation would be nice. Beyond that, you could imagine something like <script type = "puppeteer"> that has access to an expanded global environment, and for that script tag to only be allowed from the initial response HTML of something like page.static() (ala CSP, so that arbitrary scripts can't for example just add script tags), but this is definitely a more complex request and just allowing this with `evaluate()` would be great.

**Comment by aslushnikov** [comment]
@tolmasky security-wise, `addBinding` will never be secure enough to rely on it. Chromium itself operates under assumption that the renderer process is compromised, so any call to `addBinding` might be malicious.

Regarding the encapsulation bit, you can already "fake" encapsulation like this:

```js
const pptr = require('puppeteer');

(async () => {
  const browser = await pptr.launch();
  const page = await browser.newPage();
  const bindingName = Math.random().toString(36);
  await page.exposeFunction(bindingName, value => {
    console.log('Binding called! value: ' + value);
  });
  const bindingHandle = await page.evaluateHandle(bindingName => window[bindingName], bindingName);
  await page.evaluate(async binding => {
    await binding.call(null, 'yay!');
  }, bindingHandle);
  await browser.close();
})();
```

Would it work for you?
