### ISSUE TITLE
Open many new tabs with specific url

### ISSUE THREAD

**Issue by kakariko-village** [puppeteer/puppeteer#2683]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8

_Please include code that reproduces the issue._
```

async function testPage (page, browser, urls) {
    try {
        let testPage = await page.$eval(".error-block img", elem => elem.src);
        if(testPage.search('error')>0) {
            triggerEvent(page); //My function
            if(urls) {
                for (let url of urls) {
                    let newPage = browser.newPage();
                    newPage.goto('localhost/'+url);
                    testPage(newPage, browser)
                }
            }
        }
    }
    catch (e) {
        console.error('clear');
    }
}

```

**What is the expected result?**
My goal is check if the home page got error (identify by an image, check the code above), the page will open many new tabs with urls from an arrays name urls. In those new tabs, the function testPage  was triggered again but this time, only check error and does not open any new pages.

**What happens instead?**
It  only opens one single new blank tab when the code goes to if(urls) condition .

**Comment by JoelEinbinder** [comment]
You are not awaiting `browser.newPage()`, so it doesn't look like this code can work.
