### ISSUE TITLE
Slack invite link in readme doesn't work

### ISSUE THREAD

**Issue by callumlocke** [puppeteer/puppeteer#2684]
### Steps to reproduce

**What steps will reproduce the problem?**

1. Click the "slack channel" link at the bottom of the readme

**What is the expected result?**

You get invited to the Slack channel.

**What happens instead?**

![image](https://user-images.githubusercontent.com/250617/41030930-5a118e22-6977-11e8-9ca5-229d33ef9fc7.png)

**Comment by CoreyCole** [comment]
The link above the code is working, edited the readme with that link- this should fix https://github.com/GoogleChrome/puppeteer/pull/2690
