### ISSUE TITLE
Wait for function error: Promise was collected undefined

### ISSUE THREAD

**Issue by puncleV** [puppeteer/puppeteer#2686]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Linux 4.13.0-43-generic (Ubuntu 1703)
* Node.js version: 9.4.0
I am using '--disable-web-security' arg for launch. No headless mode.
**What steps will reproduce the problem?**

```
  waitLoading () {
    return this.page.waitForFunction(() => {
      const iframe = document.querySelector('#iframeId')

      if (iframe !== null) {
        const field = iframe.contentDocument.querySelector('.someSelector')

        return field !== null
      }

      return false
    })
  }
```
**What is the expected result?**
true or error by timeout

**What happens instead?**
Protocol error (Runtime.callFunctionOn): Promise was collected undefined

**Comment by aslushnikov** [comment]
@punkkk the following works just fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--no-sandbox','--disable-web-security','--disable-gpu', '--hide-scrollbars', '--disable-setuid-sandbox']
  });
  const page = await browser.newPage();
  await page.waitForFunction(() => {
    const iframe = document.querySelector('#iframeId');
    if (iframe !== null) {
      const field = iframe.contentDocument.querySelector('.someSelector');
      return field !== null;
    }
    return false;
  }, {timeout: 2000});
  await browser.close();
})();
```

We'll appreciate greatly if you provide us with **runnable** scripts so that we don't spend time guessing the code.

Feel free to re-file if you have a good runnable repro for us to play with.
