### ISSUE TITLE
0.9.0 Launch Todos

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#269]
* [x] (Tuesday) Draft the tweet [@ebidel & @paulirish]
* [x] (Tuesday) Review what's being published [@aslushnikov & @paulirish]
   - Add `description` field
* [x] (Tuesday) `yarn version` to 0.9.0 for proper git tag & github release. push. [@aslushnikov]
* [x] (Wed 8:30am) Publish 0.9.0 to NPM as `puppeteer` [@aslushnikov]
* [x] (Wed 9am) Open up Github repo private -> public [@paulirish]
* [x] (Wed 9am) Send @ChromeDevTools tweet [@paulirish]
* [x] (Wed 9am) Have @ChromiumDev retweet [@paulirish]
* [x] (Wed 9:30am) Send PR to google/puppeteer for readme update [@aslushnikov]
* [x] (Wednesday) Switch travis to public .org instance [@aslushnikov]
   - [x] travis-ci.org flipped on
   - [ ] travis-ci.com flipped off
   - [x] cancel travis subscription
   - [x] update travis badge link in readme

Anything else?

**Comment by paulirish** [comment]
> Review what's being published

@aslushnikov...

Running [`pkgfiles`](https://www.npmjs.com/package/pkgfiles) to see what'll be published says our publish size is 1.54MB which is a little bit. Putting `third_party/phantomjs/` in an .npmignore would reduce the size by ~900kb. Does that work for you, @aslushnikov? 

Also shall we exclude `phantom_shim` from the package?

**Comment by aslushnikov** [comment]
sg. We can also exclude `test/` folder i guess?

**Comment by ebidel** [comment]
Tweet ideas:

> Introducing Puppeteer: a small, modern Node library from the Chrome team for (headless) automated browser testing. https://github.com/GoogleChrome/puppeteer#readme

> Introducing Puppeteer: a small Node lib w/ a high-level API to control headless Chrome over the DevTools Protocol. https://github.com/GoogleChrome/puppeteer#readme

And attach a screenshot to the tweet.

**Comment by paulirish** [comment]
how about

> Introducing Puppeteer: a high-level automation API for headless Chrome. From the Chrome team.
https://github.com/GoogleChrome/puppeteer#readme 

excluding "node" because .. hey it's a library for dealing with browsers.. of course it's javascript.

**Comment by ebidel** [comment]
I think we should keep both "node" and "library". API by itself could be inferred that it's baked into chrome somehow. "node" is good because there are a lot of other testing libs out there in diff languages.

**Comment by paulirish** [comment]
k how about 

> Introducing Puppeteer: modern Node.js API for automating headless Chrome. From the Chrome team. https://github.com/googlechrome/puppeteer#readme

**Comment by paulirish** [comment]
current version:

> Introducing Puppeteer: A modern Node.js API for headless Chrome. Built with ❤️ by the Chrome team. https://github.com/GoogleChrome/puppeteer#readme


<img width="997" alt="screen shot 2017-08-15 at 3 37 23 pm" src="https://user-images.githubusercontent.com/238208/29340800-ba3415d4-81d5-11e7-9f09-b255c42d8d63.png">

**Comment by paulirish** [comment]
A few remaining items but generally we're good now.

**Comment by paulirish** [comment]
(We launched.)
https://twitter.com/ChromeDevTools/status/897844237902856197

**Comment by kensoh** [comment]
Just a note to say ***congratulations guys*** for the phenomenal launch! I think the project attracted about 6k stars in 24 hours. It really reflects the demand as well as the timely release of the project.

(no need reply, just wanted to feedback my excitement how Puppeteer is going to be the catalyst to start many interesting stuffs going in the larger space, and a huge blessing to the community)
