### ISSUE TITLE
How to handle unknown multiple redirections after form post? 

### ISSUE THREAD

**Issue by vivsriv19** [puppeteer/puppeteer#2696]
I am trying to open a page after a form post inside evaluate. There are 2 redirections after form post which can be any number and then I find a final page.

I tried to handled it by putting below (2 times for 2 redirections) after evaluate in which form post happened.

```
await page.waitForNavigation({'waitUntil':'domcontentloaded'});
await page.waitForNavigation({'waitUntil':'domcontentloaded'});
```

The above worked properly but I have to handle the situations when any number of redirections can happen.

I won't have any specific selector on DOM as page might be different many times.

* Puppeteer version: 1.4.0
* Platform / OS version: Linux
* URLs (if applicable): NA
* Node.js version: 8.10.0

The below is part of code which I am using :-  
....
```
const formPost = await page.evaluate((a) => {
	
	              var form = formBuilder("payment_post", "post", acsUrl);                
	              for (var i in a) {
	              	form.add(i, i, 'hidden', a[i]);
	              }
	              form.generate("pareqFormContainer");
	              form.submit();
	              return  document.querySelector('#pareqFormContainer').innerHTML;
	                                		  
	    		}, jsonData)
	    	.then(function () {
	            logger.info("form submitted with pareq and MD for txnId : " + jsonData.txnId)
	        });		    	  
	    	
	    	await page.waitForNavigation({'waitUntil':'domcontentloaded','timeout': waitTimeOut});
await page.waitForNavigation({'waitUntil':'domcontentloaded','timeout': waitTimeOut});
```
...

**Comment by aslushnikov** [comment]
@vivsriv19 what kind of redirects happen? If these are server-side redirects, than a single `waitForNavigation` should work just fine. You'll get the whole redirect chain through it's associated request:

```js
const response = await page.waitForNavigation({waituntil: 'domcontentloaded'});
const redirects = response.request().redirectChain();
```

If these are client-side redirects, than I'd just try waiting for `networkidle0` instead; once the page settles somewhere, it'll stop hitting network for more resources.

Hope this helps!

**Comment by srozzo** [comment]
> @vivsriv19 what kind of redirects happen? If these are server-side redirects, than a single `waitForNavigation` should work just fine. You'll get the whole redirect chain through it's associated request:
> 
> ```js
> const response = await page.waitForNavigation({waituntil: 'domcontentloaded'});
> const redirects = response.request().redirectChain();
> ```
> 
> If these are client-side redirects, than I'd just try waiting for `networkidle0` instead; once the page settles somewhere, it'll stop hitting network for more resources.
> 
> Hope this helps!

The above does not capture all forms of redirect. To ensure you get every change to the location 
of the browser:

```
    page.on('request', request => {
        // Capture any request that is a navigation requests that attempts to load a new document
        // This will capture HTTP Status 301, 302, 303, 307, 308, HTML, and Javascript redirects    
        if (request.isNavigationRequest() && request.resourceType() === 'document') {
           console.log(request.url())
        }
        request.continue()
    });
```
