### ISSUE TITLE
Target.getBrowserContexts' wasn't found undefined

### ISSUE THREAD

**Issue by adamgotterer** [puppeteer/puppeteer#2700]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Debian GNU/Linux 8 (jessie)
* URLs (if applicable):
* Node.js version: 8.11.2

**What steps will reproduce the problem?**
```javascript
    browser = await puppeteer.connect(
      {
        browserWSEndpoint: endpoint,
        ignoreHTTPSErrors: true
      }
    );
```

**What is the expected result?**

The connection was working fine on 1.4 and when I upgraded to 1.5 it stopped working.

**What happens instead?**

```
{ Error: Protocol error (Target.getBrowserContexts): 'Target.getBrowserContexts' wasn't found undefined at Promise (/app/node_modules/puppeteer/lib/Connection.js:86:56)
     at new Promise (<anonymous>)
     at Connection.send (/app/node_modules/puppeteer/lib/Connection.js:85:12)
     at Function.connect (/app/node_modules/puppeteer/lib/Launcher.js:257:50)
     at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
   message: 'Protocol error (Target.getBrowserContexts): \'Target.getBrowserContexts\' wasn\'t found undefined' }
```

**Comment by JoelEinbinder** [comment]
What version of chrome are you connecting to? Puppeteer is only guaranteed to work with the Chromium it is bundled with. If you want to connect to stable Chrome, you should stay on older versions of Puppeteer.

**Comment by felixfbecker** [comment]
I am meeting the same issue together with https://hub.docker.com/r/browserless/chrome. Running with the bundled Chrome version is not always possible unfortunately, see https://github.com/joelgriffith/browserless#motivations.

> Running Chrome on lambda is a fantastic idea but in practice is quite challenging. You're met with pretty tough upload limits, building Chrome yourself, and then dealing with odd invocation issues should everything else go ok. A lot of issues in various repositories are due to just challenges of getting Chrome running smoothly in AWS (see here). You can see for yourself by going to nearly any library and sorting issues by most commented.
> 
> Getting Chrome running well in docker is also a challenge as there's quiet a few packages you need in order to get Chrome running. Once that's done then there's still missing fonts, getting libraries to work with it, and having limitations on service reliability.

Since puppeteer has connecting to running Chrome instances part of its API, it would be nice if it was compatible with multiple versions to a certain degree.

**Comment by JoelEinbinder** [comment]
The majority of the work on Puppeteer happens on the Chromium side. If you need to connect to Chrome stable, use Puppeteer 1.1 or 1.2. Features of new versions of Puppeteer can't work in old Chrome, because they are only implemented in new Chrome.

**Comment by adamgotterer** [comment]
Running on the same chromium version fixed my issue. I thought puppeteer was lagging a little further behind. Thanks.

**Comment by felixfbecker** [comment]
I am just in the bad situation that I need a bug fix from 1.5 but browserless/chrome does not support 1.5. I don't need any feature of 1.5. The only thing that would have prevented this for me would have been a faster release cadence.

**Comment by starikan** [comment]
Hi. I run Chrome v.67.0.3396.79. With flag --remote-debugging-port=9000. Then go on page http://localhost:9000/json/version and get webSocketDebuggerUrl "ws://localhost:9000/devtools/browser/***". Set it in browserWSEndpoint in puppeteer.connect and get the same error "Error: Protocol error (Target.getBrowserContexts): 'Target.getBrowserContexts' wasn't found undefined"

Also I tried http://www.websocket.org/echo.html connect on ths WS addres. When I send messages like {"method":"Target.getBrowserContexts", "id": 1111000110, "params": {}} as it send in Connection.js I get an error RECEIVED: {"error":{"code":-32601,"message":"'Target.getBrowserContexts' wasn't found"},"id":1111000110}

**Comment by starikan** [comment]
Hm, there is no this method in http://localhost:9000/json/protocol. How can I attach puppeteer to the runung browser?

**Comment by JoelEinbinder** [comment]
Puppeteer 1.5 does not support Chrome 67. Use newer Chrome or older Puppeteer.

**Comment by joelgriffith** [comment]
There is a 1.5.0 build of browserless @felixfbecker. I’m working towards automating this, but haven’t gotten everything stable enough yet (hopefully that solved your issue).

**Comment by Niceplace** [comment]
@JoelEinbinder To stay in sync with the latest stable release of chrome, we should stick with 1.4.X and not upgrade to 1.5.0 ?

**Comment by developit** [comment]
I can't seem to find any combination of Chrome for Android and Puppeteer that works.

**Comment by huozhi** [comment]
our 2 DEVs are both in chrome 67.0.3396.99, with puppeteer@1.3.0. one is able to launch chrome, another is stuck at this error.

how can I check the difference between two same version chrome. no idea why it didn't work
