### ISSUE TITLE
Puppeter returns requestfailed event with net::ERR_ABORTED status for 206 Partial Content on Webm video

### ISSUE THREAD

**Issue by chrish42** [puppeteer/puppeteer#2701]
I have an animated GIF (well, as a Webm video) in one of the slides for my presentation. When running decktape on it, the PDF is fine, but I get spurious errors, which are a bit confusing:

Loading page http://christianhudon.name/talks/tour-of-ml-tech/slides.html ...
[object Object]

Unable to load resource from URL: http://christianhudon.name/talks/tour-of-ml-tech/img/Not_Hotdog.webm
```

That last message gets repeated multiple time (4 in total here, for me). However, the whole deck is correctly output, so puppeteer still worked fine. After investigation from @astefanutti in issue https://github.com/astefanutti/decktape/issues/153#issuecomment-395472245, it turns out that this is a problem with puppeteer. Qoting the bug report: "I can replicate that behaviour with Chrome directly that returns some 206 Partial Content multiple times. For some reasons, Puppeteer handles these by emitting the requestfailed event with the net::ERR_ABORTED failure message."

Here's the slide in question and the presentation: http://christianhudon.name/talks/tour-of-ml-tech/slides.html#2

I ran an npm install two days ago, so I assume I'm using the latest version. Anything else that you need to reproduce this? (I just don't know a whole lot about the npm world, so I may need a pointer or hint to help.) Thanks!

**Comment by aslushnikov** [comment]
@chrish42 I failed to reproduce this - any chance you can provide me with a puppeteer script that triggers the issue? The following naïve approach simply worked for me
```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  const response = await page.goto('http://christianhudon.name/talks/tour-of-ml-tech/img/Not_Hotdog.webm')
  console.log(response.status());
})();
```

**Comment by aslushnikov** [comment]
ERR_ABORTED might happen is website removed the video tag that was initiating the load. It looks like that's what we have here.

**Comment by g-yonchev** [comment]
Hello!

Seems I have the same issue. If I do 
```
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page._client.on('Network.loadingFailed', async event => {
    console.log(event);
  });
  await page.goto('https://www.mixedcontentexamples.com/Test/NonSecureAudio');
})();
```
the audio resource seems to fail with `net::ERR_ABORTED` but in chrome and chromium it's loaded with `206` Partial content.


<img width="1131" alt="Screen Shot 2020-07-17 at 15 57 26" src="https://user-images.githubusercontent.com/10466562/87794020-56ef2300-c846-11ea-8308-8444005ac5f8.png">
