### ISSUE TITLE
Running Puppeteer on Ubuntu 12.04

### ISSUE THREAD

**Issue by santochen** [puppeteer/puppeteer#2704]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Ubuntu 12.04.5 Server
* URLs (if applicable): 
* Node.js version: 6.14.2

**What steps will reproduce the problem?**
- Tried to install all the dependencies mentioned on the link below:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
- But server was throwing following errors:
![image](https://user-images.githubusercontent.com/11530279/41146474-139f0b16-6b36-11e8-9104-0bfbd3dbda9f.png)

**What is the expected result?**
Required shared libraries are installed. Invoking `node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome --help` should not complain any missing libraries.

**What happens instead?**
Currently returning an error: bash: chrome: cannot execute binary file

Thanks

**Comment by aslushnikov** [comment]
Well, yes - there are some libraries chromium depends on. Please see our [`troubleshooting.md`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) for details.
