### ISSUE TITLE
Website Access denied 

### ISSUE THREAD

**Issue by tripti825** [puppeteer/puppeteer#2705]
Here's a sample page from `quickr.com` : https://www.quikr.com/electronics-appliances/lg-1.5-ton-window-a-c-with-1-year-warranty-delivery-in-condition+mumbai+W0QQAdIdZ307788934

It shows access denied, when I have used all possible solutions to make it go away like slowmo, proxy, javascript enbaled, etc.

Does anyone have know a direction they can point me to?

***update*
I ran the same link with phantomjs and it loaded successully

**Comment by TomasHubelbauer** [comment]
Maybe they actively attempt to detect automated browsing.
You may want to check this: https://www.slideshare.net/SergeyShekyan/shekyan-zhang-owasp

**Comment by tripti825** [comment]
@TomasHubelbauer interesting, but that's the thing. They're able to detect puppeteer, but not something outdated as phantomjs :P

**Comment by TomasHubelbauer** [comment]
Puppeteer outs itself very easily by adding a string to user agent I think. I've had a site rate limit me to a crawl everytime I opened it using Puppeteer. I think you can change this somehow, but off the top of my head not sure. I saw an article similar to the one I posted recently on Hacker News and it showed how to alter the user agent, but I couldn't find the article when I was posting my initial comment.

**Comment by puncleV** [comment]
I can not access to it from my bowser at all.

But you can try to change user agent.

**Comment by tripti825** [comment]
yes changing the user agent DID solve the problem.
const browser = await puppeteer.launch({
		    args: ['--user-agent=<user_agent_string>',
		  });

**Comment by tripti825** [comment]
An update: it solved the problem but for only once; After that it is not opening again! and this time strangely redirecting to `distil_r_captcha.html?` . I am reopening this issue, pls let me know if a solution exists to the problem. Thanks

**Comment by TomasHubelbauer** [comment]
You won't find a solution to that problem in Puppeteer I don't think… The page is clearly trying to detect automated browsing and you will need to reverse engineering how it does it and counteract those measures. The fact that it is redirecting you to a captcha page probably means it has blacklisted your IP. You might want to try rotating a few VPNs, say every session, but beware of the fact that a dedicated site owner will keep trying to prevent you from scraping as long as it makes sense for them to. No silver bullet here.

**Comment by tripti825** [comment]
ohkk then I'll be closing this issue here. Thanks for all the help.

**Comment by klliks-com** [comment]
I can bypass it. you will need to grandscraperg at gmail dot com
