### ISSUE TITLE
$$eval call causes error if no elements found

### ISSUE THREAD

**Issue by zeicmann** [puppeteer/puppeteer#2708]
* Puppeteer version: 1.5.0
* Platform / OS version: Win 10.0.16299 Build 16299
* Node.js version: 8.7.0

1. Load any page. Could be even blank page;
2. Call $$eval() with any non-existing selector

var browser = await puppeteer.launch()
var page = await browser.newPage()
console.log(await page.$$eval('.notaclass', els => els.length))

**What is the expected result?**
0 is shown in console output;

**What happens instead?**
Error: failed to find element matching selector ".notaclass"

**Note:** This is only reproducible with v1.5.0 (1.4.0 works as expected)

**Comment by yanivefraim** [comment]
Thanks @zeicmann!

There was an inconsistency between $eval (which throws an error in case of empty result) and $$eval (which didn't throw an error in case of empty result). This was changed in version 1.5.0 when we introduced [elementHandle.$$eval](https://github.com/GoogleChrome/puppeteer/blob/master/lib/ElementHandle.js#L309) and started using it from [frameManager.$$eval](https://github.com/GoogleChrome/puppeteer/commit/1e07925e26783d586ab63a6eb88063ca51fb5647#diff-16f3b9739b97830927de83812ac92d78).

This is actually a breaking change (although it keeps consistent behaviour between $eval and $$eval).

Suggestions:

1. Remove the check for $$eval empty result from elementHandle.$$eval (which will also be a breaking change for this feature?). We can fix this later on V2.0.0.
2. Remove the usage of elementHandle.$$eval in [frameManager.$$eval](https://github.com/GoogleChrome/puppeteer/commit/1e07925e26783d586ab63a6eb88063ca51fb5647#diff-16f3b9739b97830927de83812ac92d78). This will undo the breaking change, leaving elementHandle.$$eval with the test for empty result.
3. Do nothing...

@aslushnikov WDYT? I will be happy to submit a PR...

**Comment by pschuegr** [comment]
Was this behavior reverted? I am still seeing it.
