### ISSUE TITLE
How to "run the .js file" like chrome add source and run it?

### ISSUE THREAD

**Issue by realdennis** [puppeteer/puppeteer#2713]
As title, I need to run some script and I wrote it in a .js file.
In Chrome, I could just paste script content or using CDN(create script tag) in Devtools' console or add file to snippet in Devtools' source and run it.
But, how could I do in puppeteer without CDN? Thanks.

**Comment by vsemozhetbyt** [comment]
Can [`page.addScriptTag()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageaddscripttagoptions) help?

**Comment by realdennis** [comment]
Hi there, I use that,` but it also limited by Content Security Policy`, not like Chrome Source snippet run.

**Comment by vsemozhetbyt** [comment]
Is `page.evaluate()` also affected?

**Comment by TomasHubelbauer** [comment]
Could you use `addScriptTag` in a combination with [`setBypassCsp`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetbypasscspenabled)?

**Comment by realdennis** [comment]
@TomasHubelbauer it works, thanks.
@vsemozhetbyt I do not know how to evaluate a .js file (not just string) by evaluate function.

**Comment by vsemozhetbyt** [comment]
@realdennis You can read it by any of the `fs` functions and get a string:
https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback
https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options
https://nodejs.org/api/fs.html#fs_filehandle_readfile_options
https://nodejs.org/api/fs.html#fs_fspromises_readfile_path_options

**Comment by realdennis** [comment]
@vsemozhetbyt I thought evaluate .js file behavior is like addScriptTag(after loading, it would run the script default, right? ), if `evaluate function` could receive a parameter like `addScriptTag's path`, it would be more convenience.
At all, thank you for answering me!
