### ISSUE TITLE
Ensure flags are uniques

### ISSUE THREAD

**Issue by Kikobeats** [puppeteer/puppeteer#2714]
Hello,

I noted puppeteer is adding flags by default:

https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L70

Although this is good, could be possible that the user provided a flag that is already present in the default collection of flags.

I suppose this case is not contemplated because is not necessary but looks a little confused when you are declaring more flags to use.

This could be easily addressed using a `Set` and then create an `Array` 

```js
const unique = [...new Set(myArray)]; 
```

What do you think?

**Comment by JoelEinbinder** [comment]
You can use `puppeteer.defaultArgs()` to get the arguments puppeteer will pass in. In combination with the `ignoreDefaultArgs` option, you can specify all arguments yourself.  It's not necessarily true that passing the same flag more than once is a mistake, so I wouldn't want to enforce that.

Consider if you wanted to launch Chrome with three google.com pages:
```js
puppeteer.launch({ args: ['https://www.google.com', 'https://www.google.com', 'https://www.google.com'] });
```
