### ISSUE TITLE
on 'error' does not work

### ISSUE THREAD

**Issue by leidegre** [puppeteer/puppeteer#2716]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.5.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.11.2

**What steps will reproduce the problem?**

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script>
    var txt
    setTimeout(() => {
      txt = "a";
      for (; ;) {
        txt = txt += "a";
      }
    }, 1000)
  </script>
</body>

</html>
```

```js
const puppeteer = require("puppeteer");
const path = require("path");
const panicHtmlFile = require.resolve("./test/panic.html");

async function main() {
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      "--disable-infobars", // hide "Chrome is being controlled by ..."
      "--no-first-run",
      "--incognito",
      process.env.NODE_ENV === "production" ? "--kiosk" : null
    ].filter(x => x)
  });

  const page = await browser.newPage();

  page.on("error", err => {
    console.error("error", err);
  });

  await page.goto(panicHtmlFile);

  try {
    for (;;) {
      console.log(`== ${Date.now()} ==`, "waitFor");

      await page.waitFor(3000);

      console.log(`== ${Date.now()} ==`, "...");
    }
  } catch (err) {
    console.error("error", err);
  }
}

main(); // go!
```

**What is the expected result?**

That the `error` event is raised when the page crashes.

**What happens instead?**

Puppeteer appears to have lost connection to devtools but it doesn't indicate failure and async operations just disappear and never complete.

**Comment by JoelEinbinder** [comment]
What error are you expecting to see here? It looks like you flood the main thread, which will indeed stop puppeteer from receiving messages.

**Comment by leidegre** [comment]
That first script was actually crashing devtools due to out of memory from spamming to many string length too long errors in the console. So, I tried with a different more lenient script, like this:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body style="background-color: blueviolet">
  <script>
    var n = 0;
    setInterval(() => {
      for (let k = 0; k < 1024; k++) {
        const i = n++
        for (let j = 0; j < 20; j++) {
          const txt = window[`__mem${i}`] || "a"
          window[`__mem${i}`] = txt + txt
        }
      }
    }, 1)
  </script>
</body>

</html>
```

...but the result is the same. I'm expecting the error event to be raised. I've managed to get this to work before but now I cannot get it signal that the page has crashed. I just want to now if the page has become unresponsive and needs to be reloaded (recover).

> Edit: been running this within a Raspberry Pi and due to various apps running in the page the page eventually runs of of memory, at that point I simply want to refresh/recover the page. However, puppeteer doesn't seem to detect that the page has died, I'm using a watch dog process as a work around that basically kills the page if it cannot query certain things within a certain amount of time.
