### ISSUE TITLE
 TypeError: browser.process is not a function

### ISSUE THREAD

**Issue by blackbinbinbinbin** [puppeteer/puppeteer#2719]
I want get the running browser's pid. In the document, i find the function "browser.process()".
in my test.js
`new Promise(async () => {
	const puppeteer = require('puppeteer');
	const browser = await puppeteer.launch({args: ['--no-sandbox',
    '--disable-setuid-sandbox']});
	console.log(browser.process());
	process.exit();
});`
but, when i try to run it, i find  a error: **UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: browser.process is not a function**
ps: I have run it on win and linux and return the same error message.

Am i use it wrong? Or is it just a bug?? please tell me....  Thank you very much

**Comment by vsemozhetbyt** [comment]
Make sure your version of the puppeteer and the version in the mentioned doc is the same.

**Comment by aslushnikov** [comment]
[`browser.process`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-browserprocess) was introduces in v1.0.0.
