### ISSUE TITLE
ERROR in ./node_modules/puppeteer/node_modules/mime/index.js Module not found: Error: Can't resolve './types/other' in '/node_modules/puppeteer/node_modules/mime'

### ISSUE THREAD

**Issue by sunnykreative** [puppeteer/puppeteer#2720]
ERROR in ./node_modules/puppeteer/node_modules/mime/index.js
Module not found: Error: Can't resolve './types/other' in '/node_modules/puppeteer/node_modules/mime'

**Comment by aslushnikov** [comment]
Looks like a dupe of https://github.com/GoogleChrome/puppeteer/issues/2754; I'd ask the author over there - looks like he figured the issue.
