### ISSUE TITLE
page.goto doesn't clear internal timeout when the browser is closed

### ISSUE THREAD

**Issue by alisey** [puppeteer/puppeteer#2721]
### Steps to reproduce

* Puppeteer version: 1.5.0
* Platform / OS version: macOS 10.13.3
* Node.js version: 10.2.1

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  page.on('console', () => browser.close());
  page.goto(`data:text/html,<script>console.log(1)</script>`, {timeout: 5000});
})();
```

**What is the expected result?**

The process should quit almost instantly.

**What happens instead?**

The timeout inside of `page.goto` keeps the process running for the duration of the timeout. The problem occurs more often in windowed mode than in headless.

**Comment by alisey** [comment]
`Connection` doesn't provide the ability to attach multiple event listeners to `transport.close` event. To clear the timeout in `NavigatorWatcher` the following would need to happen:
```
this._frameManager._client._connection._transport.on('close', () => {
    this._cleanup();
});
```
But of course without this chain of internal properties. Or maybe this is completely misguided. After all everything works in headless mode.

**Comment by JoelEinbinder** [comment]
Seems reasonable. We can race against page close in the navigation watcher. PRs welcome.

**Comment by cfellin1** [comment]
I can take this issue.

**Comment by cfellin1** [comment]
I have a PR out on this issue if anyone wants to take a look.
