### ISSUE TITLE
Pdf Download is not a PDF file but rather a string 

### ISSUE THREAD

**Issue by DanielViglione** [puppeteer/puppeteer#2722]
I have a web page where the pdf file is displayed inline, meaning that it is an html document that is sent from the server but it displays a pdf file. Here are the relevant Response HTTP Headers:

```
Response Headers
  Cache-Control: private
  content-disposition: inline; filename=MC_Docket.PDF
  Content-Length: 370643
  Content-Type: application/pdf
```
I am trying to download the pdf. I am using the Response callback. But the pdf file is not a pdf file. It is just a string:

  ```
          pdfPage.on('response', response => {
                const start = async () => {
                    if (response.url().startsWith('https://www.example.org/Web/PDF.aspx?page=')) {
                        const headers = response.headers()
                        const buffer = await response.buffer();

                        console.log(headers);

                        fs.writeFile(`${railsRootTaxLienPath}/${_case[1]}/${_case[0]}.pdf`, buffer, function(err) {
                            if(err) {
                                return console.log(err);
                            }

                            console.log("The file was saved!");
                        });
                    }
                }
                start();
            })
```
I console.log the headers and they are correct:

{ 'cache-control': 'private',
  'content-type': 'application/pdf',
  server: 'Microsoft-IIS/8.5',
  'content-disposition': 'inline; filename=MC_Docket.PDF',
  'x-aspnet-version': '4.0.30319',
  'x-powered-by': 'ASP.NET',
  'x-ua-compatible': 'IE=edge',
  date: 'Tue, 12 Jun 2018 20:05:33 GMT',
  'content-length': '535261' }

But when I look at the pdf file that is downloaded, it is just a string like this:

cd443a51-2e06-4ffb-8fb9-7dbbe17f8be1

Why does the buffer not contain the pdf bytes and how can I get the pdf data?

**Comment by aslushnikov** [comment]
Downloading is not supported atm; please follow #299 for details.
