### ISSUE TITLE
Scroll Jacking in Safari

### ISSUE THREAD

**Issue by deadcoder0904** [puppeteer/puppeteer#2728]
Website is Scroll Jacking in Safari 11.1.1 

I had posted same issue in another project

Maybe you find solution there 👉 https://github.com/callstack/react-native-paper/issues/330

**Comment by JoelEinbinder** [comment]
I'm not sure what this is about. We don't have a website here, but a tool that runs headless Chromium. If you are referring to the docs site, pptr.dev, please file an issue here: https://github.com/GoogleChromeLabs/pptr.dev/issues

**Comment by deadcoder0904** [comment]
Yeah its https://pptr.dev
