### ISSUE TITLE
screenShot (or evaluate) crashes page on MacOS sporadically. No errors

### ISSUE THREAD

**Issue by cantuket** [puppeteer/puppeteer#2729]
**Tell us about your environment:**
Puppeteer version: 1.4.0
Platform / OS version: MacOS High Sierra v10.13.2, MacBook Pro (Retina, 15-inch, Early 2013) Quad 2.7 GHz Intel Core i7
Node.js v8.11.2

**What steps will reproduce the problem?**
1. page.setContent()
2. Running 100 - 200 sequential evaluate('_some JS animation code_') then screenShot() functions (have tried many variations of this procedure. Details below) after the initial Puppeteer instantiation procedure. (very bottom of following comment for full code)

**What is the expected result?**
run procedure without crashing and/or consistently provide error on crash.

**What happens instead?**
Sporadic crashes without error every 1/4 to 3/4 attempts, depending on the implementation, which are listed below.

**Comment by cantuket** [comment]
Hi guys,

Thanks for the awesome software! I'm using you program slightly unconventionally, so if you think I have the wrong tool for the job then let me know. Obviously I would love a fix for my issue above, but also figured best to provide more context around the end goal in case someone can provide a more reliable and/or performant implementation, though I understand this is more getting into StackOverflow territory.

What I'm doing is converting js animations (in GSAP) into videos by using Puppeteer screenShot() to generate the individual video frames.  I've tried a few different implementations so far, but all of them seem to encounter sporadic crashes without any errors, leaving unresolved promises and open threads. These are the different implementations I've played with; some more reliable than others...

1. Async browser() Batching, Async evaluate() & screenShot()
    - 2-5 Async Puppeteer browser instances, each running async...
        a) evaluate functions (to invoke js animation at specified point-in-time), then 
        b) screenshot function to capture image, then 
        c) fs.write() to local temp directory.


2. Async browser() Batching, Synchronous evaluate() & screenShot()
    - 2-5 Async Puppeteer browser instances, each running synchronous...
        a) evaluate functions (to invoke js animation at specified point-in-time), then 
        b) screenshot function to capture image, then 
        c) fs.write() to local temp directory.


3. Synchronous browser() Batching, Synchronous evaluate() & screenShot()
    - 2-5 Synchronous Puppeteer browser instances, each running synchronous...
        a) evaluate functions (to invoke js animation at specified point-in-time), then
        b) screenshot function to capture image, then 
        c) fs.write() to local temp directory.


- I've found option 3 to be the most reliable (fails every 1/4 attempts), because seems to be least taxing on each browser() instance, but this is painfully slow and likely prohibitive given the volume we need to process.
- I've found option 1 to be least reliable, but how resources are allocated by the Chromium binary and create bottlenecks is well beyond my pay grade.

This a simplified version of the (a,b,c) procedure above...

```
async function captureAnimationFrame ({page, animationOffset, frameLength, framesTempDir}) {
    await page.evaluate(animationOffset => {
        animationTL.totalProgress(animationOffset); // sets js animation to PIT
        return true;
    }, animationOffset ).catch(err => console.log('captureAnimationFrame page.evaluate: ', err));

    let img = await page.screenshot({
        encoding:'base64', 
        type:'jpeg', 
        quality:100,
    }).catch(err => console.log(err))
    
    let frameTempFile = framesTempDir+'/'+ simpleID() +'.jpeg';
    
    let frameTempImage = await (function() {
        return new Promise(resolve => {
            fs.writeFile(framesTempFile, img, err => {
                console.log('wrote :', framesTempFile);
                if (err) console.log(err);
                resolve({
                    path: frameTempFile,
                    loop: frameLength
                })
            });
        })
    })()
    return frameTempImage;
}
```


4. Another option I haven't attempted yet, which seems like a more efficient use of resources and would be less taxing on each browser() instance is to run a single evaluate() for each batch, which then invokes a function in my node context that can set my js animations to the current PIT and then invokes a screenshot, but this seems fairly difficult to implement given that any functions passed in are stringified. Something like this (pseudo code, but hopefully give you an idea of what Im going for)... 
```
    // needs to be bound to browser() context to invoke animation
    function exec(currentFrame) {
        animationTL.totalProgress(currentFrame);  // sets js animation
        return done();
    }

    // needs to be bound to node context to invoke screenshot
    function done() {
        return await page.screenshot();
    }

    await page.evaluate((exec, done) => {
        exec(); // I understand this needs to be stringified and then rebuilt in browser() context.
    }, exec, done)

    let finishedFrames = [];
    let totalFrames = 100;
    for (let i = 0; i < frames; i++) {
        finishedFrames.push( exec( i/totalFrames ) );
    }
```

5. Final option would be to somehow take a all the screen shots manually (canvas drawImage()?) within the evaluate() function then just return an array of binary images when complete...
```
    let frameArray = Array(framesQuantity);
    let batchFrameImages = await page.evaluate(frameArray => {
        let finishedFrames = frameArray.map((frame,i) => {
            animationTL.totalProgress(i); // sets js animation
            let currentFrame = ????; // capture screen shot somehow
            return currentFrame;
        };
        return finishedFrames;
    }, frameArray);
```

Obviously I would like this procedure to be reliable as possible, but at the very least I would love a consistent error from evaluate() and/or screenShot() (not sure which is breaking as of now) so that I can retry the procedure. At this point the only reliable option I see would be doing some sort of polling mechanism, but this would be a very last resort.

As of now I'm handling errors with...
1.  page.on('error', error => { console.log('error puppeteer:', error) });, which works reliably for js runtime errors in the browser() context, but is never invoked for the evaluate()/screenShot() errors I'm experiencing.

2. Wrapping all of my Puppeteer functions in try/catches, but have yet to catch an error from them.

If I'm missing something in handling errors properly then please let me know.


And here is an example of the full Puppeteer procedure...
```
let browser = await puppeteer.launch().catch(err => console.log(err));      
let page = await browser.newPage().catch(err => console.log(err));
page.on('error', error => { console.log('error puppeteer:', error) });

await page.setViewport({
    width: Number(dimensions.width), 
    height: Number(dimensions.height),
    deviceScaleFactor: 3
}).catch(err => console.log(err));

await page.setContent(html).catch(err => console.log(err));

await page.addScriptTag({
    path: 'node_modules/jquery/dist/jquery.min.js',
}).catch(err => console.log(err));

await page.addScriptTag({
    path: 'node_modules/gsap/src/minified/TweenMax.min.js',
}).catch(err => console.log(err));

await page.addScriptTag({
    path: 'node_modules/gsap/src/minified/TimelineMax.min.js',
}).catch(err => console.log(err));

await page.addScriptTag({
    path: 'src/plugins/gsap/SplitText.min.js',
}).catch(err => console.log(err));

await page.addScriptTag({
    content: pageJs
 }).catch(err => console.log(err));

let finalFrameImages = [];
for (let i = framesFrom; i <= framesTo; i++ ) {
    let vigOffset = i / framesQuantity,
        newFrame;
    try {
        newFrame = await captureAnimationFrame({
            page,
            animationOffset,
            frameLength: (vigDuration / 1000) / framesQuantity,
            framesTempDir
        });
    } catch (err) {console.log('newFrame=: ', err)}
    finalFrameImages.push(newFrame);
} 

await browser.close().catch(err => console.log(err));
return finalFrameImages;
```

Any help would be greatly appreciated!

**Comment by frosty00** [comment]
I have the same error:

```
[D:pyppeteer.connection] SEND▶: {"id": 39, "method": "Target.sendMessageToTarget", "params": {"sessionId": "E034A4E9487AD64CB6F4D7D2C6DE470F:1", "message": "{\"id\": 36, \"method\": \"Page.captureScreenshot\", \"params\": {\"format\": \"png\", \"clip\": {\"x\": 65, \"y\": 136, \"width\": 130, \"height\": 130, \"scale\": 1}}}"}}
2018-06-21 14:46:02,675 client > Frame(fin=True, opcode=1, data=b'{"id": 39, "method": "Target.sendMessageToTarget", "params": {"sessionId": "E034A4E9487AD64CB6F4D7D2C6DE470F:1", "message": "{\\"id\\": 36, \\"method\\": \\"Page.captureScreenshot\\", \\"params\\": {\\"format\\": \\"png\\", \\"clip\\": {\\"x\\": 65, \\"y\\": 136, \\"width\\": 130, \\"height\\": 130, \\"scale\\": 1}}}"}}', rsv1=False, rsv2=False, rsv3=False)
2018-06-21 14:46:02,818 client < Frame(fin=True, opcode=1, data=b'{"id":39,"result":{}}', rsv1=False, rsv2=False, rsv3=False)
[D:pyppeteer.connection] ◀RECV: {"id":39,"result":{}}
2018-06-21 14:46:05,282 client - event = eof_received()
2018-06-21 14:46:05,283 client ! failing WebSocket connection: 1006 
2018-06-21 14:46:05,283 client - event = connection_lost(None)
2018-06-21 14:46:05,283 client - state = CLOSED
2018-06-21 14:46:05,283 client x code = 1006, reason = [empty]
[I:pyppeteer.connection] connection closed
```

browser crashes sometimes when taking a screenshot. Works normally in full screen mode.

**Comment by cantuket** [comment]
@frosty00  The only thing that solved the issue for me was running only single sequence of...
page.evaluate()
page.screenshot()

per 'browser' instance. Its pretty slow and involves a lot redundancy for our use case, but so far 100% 'crash free'.

**Comment by aslushnikov** [comment]
Hey @cantuket,

Thanks for writing us. 

> Obviously I would like this procedure to be reliable as possible, but at the very least I would love a consistent error from evaluate() and/or screenShot() 

Please follow #1454

> Its pretty slow and involves a lot redundancy for our use case, but so far 100% 'crash free'.

Crash is certainly a bug, but you'd probably want the real screencast instead: https://github.com/GoogleChrome/puppeteer/issues/478

**Comment by cantuket** [comment]
Thanks @aslushnikov! Very helpful.

I'll try to re-create  the crash with more robust error handling from [#1454](https://github.com/GoogleChrome/puppeteer/issues/1454).

#478 has a bunch of great possible solutions/improvements to my performance issues above, so I'm excited to see if any are a fit.

If I'm able to produce more informative error from the crash I'll report back, otherwise happy to close this out in favor of another issue or just write-off as Chromium bug.
