### ISSUE TITLE
How to make `waitUntil` configurable?

### ISSUE THREAD

**Issue by SidKwok** [puppeteer/puppeteer#2732]
**What is the expected result?**
I would like to set `waitUtil` like this:
```js
waitUntil: {
    event: 'networkidle',
    requests: 3,
    timeout: 400
}
```

I think it's a more customized to due with any cases.

**Comment by aslushnikov** [comment]
@SidKwok you can always implement your own `networkidle` event using the [`page.on('request')`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-event-request) and [`page.on('response')`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-event-response) events.

Hope this helps.
