### ISSUE TITLE
Load extensions on Windows 

### ISSUE THREAD

**Issue by ssut** [puppeteer/puppeteer#2733]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 9

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I needed to load a extension that a page requires, so I added `--disable-extensions-except` and `--load-extension` args but it doesn't load on windows. The full args I passed were:

```
[ '--enable-logging',
  '--v=1',
  'about:blank',
  '--disable-extensions-except="C:\\Users\\...\\chrome-extensions"',
  '--load-extension="C:\\Users\\...\\chrome-extensions"' ]
```

And the result was:

```
---------------------------
Error Loading Extension
---------------------------
Failed to load extension from:
C:\Users\...\...\...\node_modules\puppeteer\.local-chromium\win64-564778\chrome-win32\"C:\Users\...\chrome-extensions". Manifest file is missing or unreadable.
---------------------------
OK
---------------------------
```

**What is the expected result?**

Load extensions properly.

**What happens instead?**

```
---------------------------
Error Loading Extension
---------------------------
Failed to load extension from:
C:\Users\...\...\...\node_modules\puppeteer\.local-chromium\win64-564778\chrome-win32\"C:\Users\...\chrome-extensions". Manifest file is missing or unreadable.
---------------------------
OK
---------------------------
```

I think if I pass the extension path as a relative path it might be work but I also think that is so awful.

**Comment by ssut** [comment]
I temporary solved this issue by removing `--disable-extensions` from the default arguments.

**Comment by aslushnikov** [comment]
> I temporary solved this issue by removing --disable-extensions from the default arguments.

This is the way to go for now; we might do a nicer extensions support eventually.

**Comment by mayank2567** [comment]
> I temporary solved this issue by removing `--disable-extensions` from the default arguments.

but then it does not load any extentions

**Comment by xxclodxx** [comment]
I am also unable to load my extension, I am following the same commands but instead of puppeteer I am using puppeteer-core, I do get the error saying that loading extensions is disabled by admin and the extension will not any thoughts?

**Comment by sergtimosh** [comment]
Same issue with loading extension with puppeteer on windows.
Works fine on mac, though.

**Comment by Ajju2211** [comment]
Getting. Manifest file missing while loading extensions.I downloaded crx file of the extension then I converted it to zip file then its relative path added. Whats  wrong?

**Comment by mercertom** [comment]
I finally fixed this exact error/issue with ublock. I had originally made several errors. It now works.
1. I had a typo in my datadir declaration
2. ublock has nested directories with weird names (I'm not sure this mattered)

Here's the working code: 
```
	const ublock = '~/Documents/jsprojects/puppeteer-extensions/ublock/';
	const datadir = '~/Documents/jsprojects/chromeprofile/';
	const browser = await puppeteer.launch({
		headless: false,
		userDataDir: datadir,
		defaultViewport: { width:1000, height: 1080 },
		args:
		[
		`--disable-extensions-except=${ublock}`,
		`--load-extension=${ublock}`,
	});
```
In /puppeteer-extensions/, I changed /chromium.ublock0.152341/ or whatever to plain /ublock/, and deleted a nested sub-directory with an equally funky name. Within /ublock/ there is a manifest.json. Many extensions have multiple layers of weird-named directories. Change the dir names to something simple like /ublock/, and then make sure your line declaring the extension has that directory path typed perfectly in your code.

@Ajju2211 I think you should unzip the extension and absolute/relative path to the directory that contains manifest.json.

**Comment by Luckz** [comment]
How about having a Chrome Web Store (CWS) extension installed and just having that not removed and not disabled and such?

**Comment by dgtlmoon** [comment]
@danielehrhardt how did you come up with that JS? where did you find it works? can you give any more information? what version etc?
