### ISSUE TITLE
Error generating PDFs: Protocol error (Page.printToPDF): Target closed.

### ISSUE THREAD

**Issue by jontuk** [puppeteer/puppeteer#2735]
* Puppeteer version: puppeteer@1.5.0-next.1528948338383
* Chromium 66.0.3359.181 Built on Ubuntu , running on Ubuntu 17.10
* Node.js version: v9.11.2
* Fails on VirtualBox VM with plentiful resources (4cores, >8GB mem free)

Also an issue inside docker container with puppeteer 1.0.0, Ubuntu 18.04 and node v8.

**What steps will reproduce the problem?**

```
(async () => {
    const browser = await puppeteer.launch({
        executablePath: '/usr/bin/chromium-browser',
        args: ['--headless', '--disable-gpu', '--full-memory-crash-report', '--unlimited-storage',
               '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });
    const page = await browser.newPage();
    await page.goto(url, {waitUntil: 'networkidle0'});
    await page.pdf({path: outfile, format: 'A4'});
    await browser.close();
})().catch(error => {
    console.error(error);
    process.exit(1);
});
```

**What is the expected result?**

PDF file saved to `outfile`, exit code 0

**What happens instead?**

chromium-browser goes 100% CPU at `page.pdf()` and after 35s:

```
{ Error: Protocol error (Page.printToPDF): Target closed.
at Promise (/home/jon/dev/web-exporter/node_modules/puppeteer/lib/Connection.js:202:56)
at new Promise (<anonymous>)
at CDPSession.send (/home/jon/dev/web-exporter/node_modules/puppeteer/lib/Connection.js:201:12)
at Page.pdf (/home/jon/dev/web-exporter/node_modules/puppeteer/lib/Page.js:851:39)
at /home/jon/dev/web-exporter/web_exporter.js:40:20
at <anonymous> message: 'Protocol error (Page.printToPDF): Target closed.' }
```
Exit code of 1.

I've tried various different args for `chromium-browser` and `page.pdf`. This application has been working generating 100s of PDFs for 6 months. In the last few days however would fail with the output above on specific pages. 

The page being loaded is a react application with a 10s of small images (50-200 pixels square) embedded. The issue reproducibley fails on small number of 'bad' pages. Unfortunately the URL is not public.

I can open the url without issue in chrome and the same chromium-browser (non-headless), also the print to pdf works as expected.

Any help in tracking down this issue much appreciated. 

Jon

**Comment by psycura** [comment]
Have same issue,
on Windows 10 local server - works fine,
but on Ubuntu 16.04 server, same error happen

**Comment by aslushnikov** [comment]
The following works fine for me with pptr v1.8.0:
**BEWARE**: I see you use custom chrome instance; make sure it matches the puppeteer version.
```js
const puppeteer = require('.');
(async () => {
    const browser = await puppeteer.launch({
        args: ['--headless', '--disable-gpu', '--full-memory-crash-report', '--unlimited-storage',
               '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });
    const page = await browser.newPage();
    await page.goto('https://aslushnikov.com', {waitUntil: 'networkidle0'});
    await page.pdf({path: 'pdf.pdf', format: 'A4'});
    await browser.close();
})().catch(error => {
    console.error(error);
    process.exit(1);
});
```

**Comment by SupermanWY** [comment]
Have same issue,
on win10,
chrome 69 and chrmium 74,
puppeteer 1.12.2,

**Comment by UNDEADgtr** [comment]
Have the same issue,
on mac,
puppeteer 1.11.0,

**Comment by genevien** [comment]
Have the same issue,
on win10,
puppeteer 1.11.0/1.12.2
```
 args: ['--headless', '--disable-gpu', '--full-memory-crash-report', '--unlimited-storage',
               '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
```
setting these parameters didn't help

**Comment by slate71** [comment]
Was getting the same error on pptr v1.12.2 but was able to fix it by setting `pipe: true` when launching the browser.

```
 const browser = await puppeteer.launch({
        pipe: true,
        args: ['--headless', '--disable-gpu', '--full-memory-crash-report', '--unlimited-storage',
               '--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
    });
```

The issue starting popping up when trying to generate a PDF with approximately 100 various .jpgs. Using the default Websocket to connect to the browser would bail during encoding to base64. Using a pipe to connect to the browser instead seems to fix the issue of bailing during encoding.

> `pipe` <boolean> Connects to the browser over a pipe instead of a WebSocket. Defaults to false

**Comment by andersonfernandes** [comment]
The solution of @slate71 worked for me. I had the same problem with the images.
Thanks @slate71

**Comment by UNDEADgtr** [comment]
Thanks @slate71! The solution worked for me too, but an error regularly appears:

Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)

**Comment by justjake** [comment]
This issue should be re-opened as it is unresolved.

**Comment by justjake** [comment]
There is a related issue upstream in Chrome that results in extremely large PDF output for pages containing emoji. See this Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=921585

Printing these Emoji with Chromium on macOS and Linux both results in ~200MB PDFs:


> 😀 😁 😂 🤣 😃 😄 😅 😆 😉 😊 😋 😎 😍 😘 🥰 😗 😙 😚 ☺️ 🙂 🤗 🤩 🤔 🤨 😐 😑 😶 🙄 😏 😣 😥 😮 🤐 😯 😪 😫 😴 😌 😛 😜 😝 🤤 😒 😓 😔 😕 🙃 🤑 😲 ☹️ 🙁 😖 😞 😟 😤 😢 😭 😦 😧 😨 😩 🤯 😬 😰 😱 🥵 🥶 😳 🤪 😵 😡 😠 🤬 😷 🤒 🤕 🤢 🤮 🤧 😇 🤠 🤡 🥳 🥴 🥺 🤥 🤫 🤭 🧐 🤓 😈 👿 👹 👺 💀 👻 👽 🤖 💩 😺 😸 😹 😻 😼 😽 🙀 😿 😾
>
> 🐶 🐱 🐭 🐹 🐰 🦊 🦝 🐻 🐼 🦘 🦡 🐨 🐯 🦁 🐮 🐷 🐽 🐸 🐵 🙈 🙉 🙊 🐒 🐔 🐧 🐦 🐤 🐣 🐥 🦆 🦢 🦅 🦉 🦚 🦜 🦇 🐺 🐗 🐴 🦄 🐝 🐛 🦋 🐌 🐚 🐞 🐜 🦗 🕷 🕸 🦂 🦟 🦠 🐢 🐍 🦎 🦖 🦕 🐙 🦑 🦐 🦀 🐡 🐠 🐟 🐬 🐳 🐋 🦈 🐊 🐅 🐆 🦓 🦍 🐘 🦏 🦛 🐪 🐫 🦙 🦒 🐃 🐂 🐄 🐎 🐖 🐏 🐑 🐐 🦌 🐕 🐩 🐈 🐓 🦃 🕊 🐇 🐁 🐀 🐿 🦔 🐾 🐉 🐲 🌵 🎄 🌲 🌳 🌴 🌱 🌿 ☘️ 🍀 🎍 🎋 🍃 🍂 🍁 🍄 🌾 💐 🌷 🌹 🥀 🌺 🌸 🌼 🌻 🌞 🌝 🌛 🌜 🌚 🌕 🌖 🌗 🌘 🌑 🌒 🌓 🌔 🌙 🌎 🌍 🌏 💫 ⭐️ 🌟 ✨ ⚡️ ☄️ 💥 🔥 🌪 🌈 ☀️ 🌤 ⛅️ 🌥 ☁️ 🌦 🌧 ⛈ 🌩 🌨 ❄️ ☃️ ⛄️ 🌬 💨 💧 💦 ☔️ ☂️ 🌊 🌫
>
> 👶 👧 🧒 👦 👩 🧑 👨 👵 🧓 👴 👲 👳‍♀️ 👳‍♂️ 🧕 🧔 👱‍♂️ 👱‍♀️ 👨‍🦰 👩‍🦰 👨‍🦱 👩‍🦱 👨‍🦲 👩‍🦲 👨‍🦳 👩‍🦳 🦸‍♀️ 🦸‍♂️ 🦹‍♀️ 🦹‍♂️ 👮‍♀️ 👮‍♂️ 👷‍♀️ 👷‍♂️ 💂‍♀️ 💂‍♂️ 🕵️‍♀️ 🕵️‍♂️ 👩‍⚕️ 👨‍⚕️ 👩‍🌾 👨‍🌾 👩‍🍳 👨‍🍳 👩‍🎓 👨‍🎓 👩‍🎤 👨‍🎤 👩‍🏫 👨‍🏫 👩‍🏭 👨‍🏭 👩‍💻 👨‍💻 👩‍💼 👨‍💼 👩‍🔧 👨‍🔧 👩‍🔬 👨‍🔬 👩‍🎨 👨‍🎨 👩‍🚒 👨‍🚒 👩‍✈️ 👨‍✈️ 👩‍🚀 👨‍🚀 👩‍⚖️ 👨‍⚖️ 👰 🤵 👸 🤴 🤶 🎅 🧙‍♀️ 🧙‍♂️ 🧝‍♀️ 🧝‍♂️ 🧛‍♀️ 🧛‍♂️ 🧟‍♀️ 🧟‍♂️ 🧞‍♀️ 🧞‍♂️ 🧜‍♀️ 🧜‍♂️ 🧚‍♀️ 🧚‍♂️ 👼 🤰 🤱 🙇‍♀️ 🙇‍♂️ 💁‍♀️ 💁‍♂️ 🙅‍♀️ 🙅‍♂️ 🙆‍♀️ 🙆‍♂️ 🙋‍♀️ 🙋‍♂️ 🤦‍♀️ 🤦‍♂️ 🤷‍♀️ 🤷‍♂️ 🙎‍♀️ 🙎‍♂️ 🙍‍♀️ 🙍‍♂️ 💇‍♀️ 💇‍♂️ 💆‍♀️ 💆‍♂️ 🧖‍♀️ 🧖‍♂️ 💅 🤳 💃 🕺 👯‍♀️ 👯‍♂️ 🕴 🚶‍♀️ 🚶‍♂️ 🏃‍♀️ 🏃‍♂️ 👫 👭 👬 💑 👩‍❤️‍👩 👨‍❤️‍👨 💏 👩‍❤️‍💋‍👩 👨‍❤️‍💋‍👨 👪 👨‍👩‍👧 👨‍👩‍👧‍👦 👨‍👩‍👦‍👦 👨‍👩‍👧‍👧 👩‍👩‍👦 👩‍👩‍👧 👩‍👩‍👧‍👦 👩‍👩‍👦‍👦 👩‍👩‍👧‍👧 👨‍👨‍👦 👨‍👨‍👧 👨‍👨‍👧‍👦 👨‍👨‍👦‍👦 👨‍👨‍👧‍👧 👩‍👦 👩‍👧 👩‍👧‍👦 👩‍👦‍👦 👩‍👧‍👧 👨‍👦 👨‍👧 👨‍👧‍👦 👨‍👦‍👦 👨‍👧‍👧 🤲 👐 🙌 👏 🤝 👍 👎 👊 ✊ 🤛 🤜 🤞 ✌️ 🤟 🤘 👌 👈 👉 👆 👇 ☝️ ✋ 🤚 🖐 🖖 👋 🤙 💪 🦵 🦶 🖕 ✍️ 🙏 💍 💄 💋 👄 👅 👂 👃 👣 👁 👀 🧠 🦴 🦷 🗣 👤 👥

Here is a repo that demonstrates this problem:
https://github.com/justjake/chromium-color-emoji-printing-issue

**Comment by justjake** [comment]
> Error: write EPIPE
> at _errnoException (util.js:992:11)
> at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)

@UNDEADgtr The issue is that the PipeTransport does not install handlers for stream errors.
I opened https://github.com/GoogleChrome/puppeteer/issues/4374 to track the issue.

**Comment by danfoust** [comment]
I ran into this issue when trying to print pdfs with a company logo that had extremely large dimensions.

It was only 300kb, but it was 10,000x7000 pixels with lots of white-space

Resizing the logo to a reasonable size (ex 800x600) fixed the issue.

**Comment by Ofat1958** [comment]
I had the same problem and it turned out that the site was using lazy loading and it caused this error so I used this package to load all images first: https://www.npmjs.com/package/puppeteer-autoscroll-down

**Comment by insidewhy** [comment]
Tried all the suggestions in this issue (we don't have any big images but we embed a couple of fonts) and nothing works.

**Comment by Anukul14** [comment]
I tried to launch puppeteer using `pipe:true` , but the error still appeared.
Increasing the memorySize for my lambda function from 512 to 2024 helped.

**Comment by wdelmas** [comment]
"Target closed" usually means Chrome crashed mid-render due to resource exhaustion.

**Debugging steps:**

1. **Enable logging:** `dumpio: true` in launch options to see Chrome's stderr
2. **Check system resources:** Run `dmesg | grep -i killed` to see if OOM killer hit Chrome
3. **Reduce page complexity:** Large images, embedded fonts, and complex CSS all spike memory

**Code pattern that helped:**

```js
try {
  const pdf = await page.pdf({ timeout: 60000 })
} catch (e) {
  if (e.message.includes('Target closed')) {
    // Chrome crashed - likely OOM
    await browser.close()
    browser = await puppeteer.launch(/* ... */)
  }
}
```

For production workloads with unpredictable document sizes, I moved to an external PDF service that handles the resource management.
