### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long undefined

### ISSUE THREAD

**Issue by fenglai0802** [puppeteer/puppeteer#2746]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: macOS 10.13.4
* Node.js version: v9.3.0

**What steps will reproduce the problem?**

```
(async ()=> {
  const cssSelector = '.sidebar-group-items > li > a';
  // const url = 'demo';  // the url is an Intranet

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'load' });
  
  try {
    let links = await page.$$eval(cssSelector, links => {
      return links.map( a => {
        return {
          href: a.href.trim(),
          title: a.innerText
        }
      });
    });
    await browser.close();
    return links;
  } catch (error) {
    throw new Error(error);
  }
})()
```

**What is the expected result?**

I want to get the directory array of the page, it was working fine on Puppeteer 1.4 and when I upgraded to 1.5 it stopped working. But it seems to be working again in other web (cssSelector changed accordingly)

**What happens instead?**

```
UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long undefined
    at Promise (/Users/hedonghui/workspace/test/node_modules/_puppeteer@1.5.0@puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/hedonghui/workspace/test/node_modules/_puppeteer@1.5.0@puppeteer/lib/Connection.js:201:12)
    at JSHandle.jsonValue (/Users/hedonghui/workspace/test/node_modules/_puppeteer@1.5.0@puppeteer/lib/ExecutionContext.js:193:43)
    at ElementHandle.$$eval (/Users/hedonghui/workspace/test/node_modules/_puppeteer@1.5.0@puppeteer/lib/ElementHandle.js:309:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by pariola** [comment]
any solution yet?

**Comment by pariola** [comment]
had to revert to v`1.3.0`

**Comment by yanivefraim** [comment]
@pariola - I also saw this error in one of our projects, but I cannot reproduce it. Can you please add a link which we can run (add your url / test case which reproduces this issue)?

**Comment by yanivefraim** [comment]
Ok, I managed to reproduce this issue:

```js
const puppeteer = require("puppeteer");
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto("https://www.wix.com", { waitUntil: "load" });

  const result = await page.$$eval("div", divs => divs.map(div => div.innerText))
  console.log(result);
  await browser.close();
})();
```

It works with Puppeteer V1.4.0, and fails with V1.5.0:

`(Runtime.callFunctionOn): Object reference chain is too long undefined`

**Comment by yanivefraim** [comment]
So apparently this issue was caused by the following line:

https://github.com/GoogleChrome/puppeteer/blob/38f112f39546fc76a1ac3da7b42c02626fc581b1/lib/ElementHandle.js#L309
 
which was removed in a previous [commit](https://github.com/GoogleChrome/puppeteer/commit/9a650c818d79c95af47816a8d8bf1fd63cc8e6c6) already. 

In the meanwhile, you can use:

`npm i --save puppeteer@next`

@aslushnikov @joelEinbinder - fyi
