### ISSUE TITLE
page.screenshot API dimension is incorrect on retina screens

### ISSUE THREAD

**Issue by oliviertassinari** [puppeteer/puppeteer#2748]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: MacOs 10.13.5
* URLs (if applicable): https://www.google.com/
* Node.js version: 10.3.0

**What steps will reproduce the problem?**

```jsx
await page.goto('https://www.google.com/')
await page.screenshot({
  fullPage: true,
  path: path.join(__dirname, `google.png`),
})
```

**What is the expected result?**

1x
![google](https://user-images.githubusercontent.com/3165635/41467367-90cb91e8-70a6-11e8-9097-4c71346980b5.png)

**What happens instead?**

4x
![google](https://user-images.githubusercontent.com/3165635/41463795-1348c0f0-7098-11e8-916c-4803d021f578.png)

**Comment by aslushnikov** [comment]
@oliviertassinari can you paste exact script that reproduces this for you? The following worked just fine on my Macbook:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://www.google.com/')
  await page.screenshot({
    fullPage: true,
    path: `google.png`,
  });
  await browser.close();
})();

```

**Comment by oliviertassinari** [comment]
Hopefully, someone will provide a better reproduction.
