### ISSUE TITLE
Puppeteer tab reorder

### ISSUE THREAD

**Issue by avshyz** [puppeteer/puppeteer#2751]
Hi!
I manage to imitate concurency by opening multiple tabs to scrape different pages of a website.
I'd like to know if there's a way to use puppeteer's api to reorder these tabs.

**Comment by TomasHubelbauer** [comment]
I don't think this is possible with the current API. We only have [`Browser.newPage`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browsernewpage), [`Browser.pages`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserpages) and [`Page.close`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagecloseoptions) to manage the browser tabs. The `pages` array is a "read only" in the sense that it is a new instance created by the method, changes to which won't reflect back to anything.

**Comment by avshyz** [comment]
Understandably. Thanks for your response, mate!

**Comment by aslushnikov** [comment]
@avshyz also, check out [`BrowserContext`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-class-browsercontext) to drive even nicer parallelization.
