### ISSUE TITLE
How I can close browser after page throw some error?

### ISSUE THREAD

**Issue by bartmanskyi** [puppeteer/puppeteer#2752]
Hello. How I can close browser after page throw some error?

async function fnGoogle(page) {
  try {
  //some code here
  await page.goto('blablalba');
  } catch (e) {
    throw e
  }
}
How can chromium close itself after show me the error in console?
Thank you

**Comment by geraldchecka** [comment]
When you launch the puppeteer, you have access to the browser argument. Create a closure and do a
browser.close() inside the catch block.
