### ISSUE TITLE
headless = false, and still recognized by newegg how ?

### ISSUE THREAD

**Issue by yanivkalfa** [puppeteer/puppeteer#2753]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Windows 10 64bit
* URLs (if applicable):  https://secure.newegg.com/NewMyAccount/AccountLogin.aspx
* Node.js version: 8.9.3

Well going to the above address while headless = false would still be detected and a captcha pop..
doesnt headless = false supposed to behave just like a normal browser ?

Is there any way to avoid that ?

More on that, when i go to the same address on normal chrome the captcha wont appear (using the same IP).

**Comment by preflightech** [comment]
I don't think it's based on whether or not you use Puppeteer. I visited the page, and it gave me a captcha right away (latest Chrome on Windows 10).
