### ISSUE TITLE
Running with chrome rather than chromium

### ISSUE THREAD

**Issue by rlpham** [puppeteer/puppeteer#2757]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.5.0
* Platform / OS version: OS X El Capitan Version 10.11.6
* URLs (if applicable): 
* Node.js version: v10.2.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. const browser = await puppeteer.launch({ headless: false, executablePath: '/Applications/Chrome' });
2. const page = await browser.newPage();

**What is the expected result?**
Runs in chrome rather than chromium

**What happens instead?**
(node:36852) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! spawn /Applications/Chrome ENOENT

(node:36852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by benjamingr** [comment]
Chrome is saved under `/Applications/Google Chrome/` and not `/Applications/Chrome` - the error you're getting is indicating that Chrome isn't where you point it to.

Do people think the error could be clearer? 

(If so, I don't mind making a PR)

**Comment by rlpham** [comment]
Hello, thanks for assisting. Unfortunately it didn't work and I am still getting the same error.  

Error: Failed to launch chrome! spawn /Applications/Google Chrome/ ENOENT

**Comment by alisey** [comment]
`/Applications/Google Chrome.app` is just a directory, you need to provide a path to the executable inside of that directory:
```
const browser = await puppeteer.launch({
  headless: false,
  executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
});
```

**Comment by rlpham** [comment]
Thank YOU!

**Comment by raihanrazi** [comment]
@alisey thank you!

**Comment by pratik-joshi-cactus** [comment]
Not working :/ in Version 75.0.3770.100 (Official Build) (64-bit), It still opens up new instance of chrome and it has no history whatsoever, I had to open it along with my other chrome tabs.

	const puppeteer = require('puppeteer');
	const pptr = require('puppeteer-core');
	(async () => {

		const browser = await puppeteer.launch({
		  headless: false,
		  executablePath: '/usr/bin/google-chrome'
		});

	})(); 

Here I also tried puppeteer-core , means pptr variable await pptr.launch in above variable, still not working. The issues is not closed!
Please check : 
https://drive.google.com/file/d/1WKjgPeruK9-ABeHHsumhcjs_FTlzFH4S/view
