### ISSUE TITLE
Add type checking to CDPSession.send

### ISSUE THREAD

**Issue by FiloSottile** [puppeteer/puppeteer#2758]
`devtools-protocol` provides type definitions for the remote protocol commands.

GoogleChrome/lighthouse#4914 added support for type checking in their equivalent of `CDPSession.send`. It would be very useful to have the same for `CDPSession.send`.

**Comment by JoelEinbinder** [comment]
We have type checking for CDPSession.send in Puppeteer! Check out https://github.com/GoogleChrome/puppeteer/blob/master/utils/protocol-types-generator/index.js. 

We don't maintain the @types/puppeteer project, but you can find them here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/puppeteer.

**Comment by FiloSottile** [comment]
Hmm, interesting. I don't see them applied in VSCode with `@types/puppeteer` 1.3.4.

![image](https://user-images.githubusercontent.com/1225294/41683486-b6be36d4-74a8-11e8-984b-1287e0495393.png)

Should I move this to DefinitelyTyped?

**Comment by aslushnikov** [comment]
@FiloSottile looks like DefinitelyTyped just lacking some types; whoever wants to contribute them there, feel free to generate type descriptions using our generator that Joel referred to.
