### ISSUE TITLE
Node throws errors while trying execute more than two page.evaluate() functions in the same method

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#2760]
### Steps to reproduce
**What is wrong?**
I'm not able to execute three functions `page.evaluate()` in the same method due the errors. It's possible to execute one or two functions without problems, but node throws errors while I'm trying to execute three or more `page.evaluate()`.

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: MacOS
* Language: Typescript
* Node.js version: v9.4.0

**What steps will reproduce the problem?**
I have method `Init` being workaround for only synchronous constructors rule in Javascript. It gets values of properties of the object. Code:
```
    public async Init() {
        this.InstalmentsAmount = await this.api.evaluate(
            (selector) => document.querySelector(selector).children[0].children[0].children[0].textContent, this.selector)

        this.InstalmentsCost = await this.api.evaluate(
            (selector) => document.querySelector(selector).children[0].children[0].children[1].textContent, this.selector)

        this.InstalmentsInterest = await this.api.evaluate(
            (selector) => document.querySelector(selector).children[0].children[0].children[2].textContent, this.selector)
        }
    }
```

**What is the expected result?**
I should be able to execute three `page.evaluate()` in one method.

**What happens instead?**
I'm getting errors as below:
```
(node:10443) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
(node:10443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of anasync function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10443) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
(node:10443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of anasync function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10443) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
(node:10443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of anasync function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:10443) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
(node:10443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of anasync function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

It works perfectly fine when I'm executing only two functions

**Comment by aslushnikov** [comment]
@marek-siemieniuk this is not actionable without a script I can run locally to reproduce the problem. Feel free to re-open with a repro.

Also, please try updating to pptr v1.5.0 - we fixed a lot of bugs there, and maybe this one is fixed as well.

**Comment by jsdevtom** [comment]
I can confirm this error is still happening with v1.5.0.

**Comment by ghost** [comment]
@aslushnikov I'm not able to reproduce the issue in the same way as before because I've changed the code a lot, but now (puppeteer updated to v1.5.0) it's possible to execute three `page.evaluate()` methods in one function. 

cc: @jsdevtom
