### ISSUE TITLE
Web Worker errors are not collected by `page.on('pageerror'...`

### ISSUE THREAD

**Issue by yanivefraim** [puppeteer/puppeteer#2761]
When an error occures on a Web Worker, it is not collected by `page.on('pageerror'...` event. 

For example:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('pageerror', message => console.log(message));

  await page.setContent(`<!DOCTYPE html>
  <script id="worker1" type="javascript/worker">
    throw new Error('this is my error');
  </script>
  <script>
    const blob = new Blob([
      document.querySelector('#worker1').textContent
    ], { type: "text/javascript" })

    new Worker(window.URL.createObjectURL(blob));
  </script>`);
})()
```

**Comment by TomasHubelbauer** [comment]
I think this might be related to #1921 and in turn #2350, which was closed a month ago, but I am not sure if it was released yet.

**Comment by TomasHubelbauer** [comment]
However the `WebWorker` class doesn't seem to expose any events, you can only get it's URL and execution context and I am not sure if it is possible to catch errors thrown in execution contexts…

**Comment by yanivefraim** [comment]
@TomasHubelbauer - yes, exactly. So this issue was closed, although the requirement for:

>can issue requests, so worker.on('request') should be available as well

wasn't implemented. 

@aslushnikov - can we reopen #2350?

plus, is this supported by the CDP?

**Comment by aslushnikov** [comment]
> @aslushnikov - can we reopen #2350?

@yanivefraim there's a separate issue for network in workers: #2781

> plus, is this supported by the CDP?

Yes, we need to handle the [`Runtime.exceptionThrown`](https://vanilla.aslushnikov.com/#Runtime.exceptionThrown) event in WebWorkers.
