### ISSUE TITLE
Fullpage screenshot stretches or cuts off part of the page

### ISSUE THREAD

**Issue by grantstephens** [puppeteer/puppeteer#2762]
* Puppeteer version: 1.5
* Platform / OS version: Ubuntu 18 and 16
* URLs (if applicable): `https://shop.mango.com/gb` and `https://www.bershka.com/kr/women-c1010193132.html`
* Node.js version: 10.4.1

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://shop.mango.com/gb');
  await page.mouse.click(0, 0, {button:'right'})  // Gets rid of popover
  await page.screenshot({path: 'example.png', fullPage: true});
  await browser.close();
})();
```
Results in the following screenshot:

![image](https://user-images.githubusercontent.com/2863673/41544349-62586ba8-7310-11e8-81ac-7e5e42dfb052.png)

**Comment by morteza-fsh** [comment]
This package may help you:
https://github.com/averta-lab/puppeteer-full-page-screenshot

**Comment by entrptaher** [comment]
@morteza-fsh the repo is 404 :(

**Comment by 0wx** [comment]
@morteza-fsh please, do you update of it? I'm stuck with this issue.

**Comment by morteza-fsh** [comment]
@0wx, @entrptaher 
Yes, the repository address has been changed, also it's available on NPM too:
https://github.com/morteza-fsh/puppeteer-full-page-screenshot
