### ISSUE TITLE
Some URLs sequence makes next responses to be null

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#2764]
* Puppeteer version: 1.5.0-post (chromium_revision 567388)
* Platform / OS version: Windows 7 x64
* URLs (if applicable): see in the example
* Node.js version: 10.4.1

I have a script that validates links. Sometimes, after getting some URL, all next responses become `null`.

I've managed to reduce the issue to this case:

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    let response = await page.goto('https://twitter.com/');
    console.log(response ? response.status() : response);
    response = await page.goto('https://github.com/nodejs/node');
    console.log(response ? response.status() : response);
    response = await page.goto('https://github.com/GoogleChrome/puppeteer/');
    console.log(response ? response.status() : response);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**What is the expected result?**
```
200
200
200
```

**What happens instead?**
```
200
null
null
```

**Comment by mboeser** [comment]
I ran this in the web app [https://try-puppeteer.appspot.com](url)

`  const browser = await puppeteer.launch();
    const [page] = await browser.pages();
    let response = await page.goto('https://twitter.com/');
    console.log(response ? page.url()+response.status() : response);
    response = await page.goto('https://github.com/nodejs/node');
    console.log(response ? page.url()+response.status() : response);
    response = await page.goto('https://github.com/GoogleChrome/puppeteer/');
    console.log(response ? page.url()+response.status() : response);
    await browser.close();`

and saw expected results

`https://twitter.com/200
https://github.com/nodejs/node200
https://github.com/GoogleChrome/puppeteer/200`

**Comment by aslushnikov** [comment]
I can reproduce on puppeteer dcae6bcff49150bec2060667fef7bd7ab71db042.

**Comment by aslushnikov** [comment]
For the record: this happens because website uses History API in its `beforeunload` handler.

**Comment by florian-koenig** [comment]
It'd be great to mention this key hint by @aslushnikov in the API docs (e.g., [https://github.com/GoogleChrome/puppeteer/blob/v1.6.0/docs/api.md#pagegotourl-options](https://github.com/GoogleChrome/puppeteer/blob/v1.6.0/docs/api.md#pagegotourl-options)). I have noticed that single-page applications sometimes alter the browser history when a page is loaded, and the call to `.goto(...)` then returns `null`, even though the page has loaded properly.
