### ISSUE TITLE
Getting URLs that differs only in hashes make next responses to be null

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#2765]
* Puppeteer version: 1.5.0-post (chromium_revision 567388)
* Platform / OS version: Windows 7 x64
* URLs (if applicable): any?
* Node.js version: 10.4.1

**What steps will reproduce the problem?**

Not sure if this is intended behavior. If so, this needs to be documented or better fixed (as this breaks getting unpredictable URLs lists).

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    let response = await page.goto('https://example.org/#foo');
    console.log(response ? response.status() : response);
    response = await page.goto('https://example.org/#bar');
    console.log(response ? response.status() : response);
    response = await page.goto('https://example.org/#baz');
    console.log(response ? response.status() : response);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**What is the expected result?**
```
200
200
200
```

**What happens instead?**
```
200
null
null
```

**Comment by aslushnikov** [comment]
> Not sure if this is intended behavior. If so, this needs to be documented or better fixed (as this breaks getting unpredictable URLs lists).

@vsemozhetbyt Navigating to URL with a different hash part doesn't actually do any navigation, so `null` looks reasonable to me. If you want to always hit server, I'd open a new page and navigate it instead.

> If so, this needs to be documented

I'd be happy to review a PR.

**Comment by vsemozhetbyt** [comment]
@aslushnikov Would it be more efficient and safe to return the initial `response` rather than `null`?

**Comment by aslushnikov** [comment]
> Would it be more efficient and safe to return the initial response rather than null?

It is possible, but counter-intuitive and "magical" to me: I wouldn't expect `page.goto` to return a response, if my server wasn't actually hit.

**Comment by vsemozhetbyt** [comment]
Doc PR: https://github.com/GoogleChrome/puppeteer/pull/2787
