### ISSUE TITLE
`page.setCookie()` is werid in `expire`

### ISSUE THREAD

**Issue by SidKwok** [puppeteer/puppeteer#2768]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: macos 10.13.5
* URLs (if applicable): 
* Node.js version: 8.10.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.  set cookies
```js
...
page.setCookie({
    name: 'cookie',
    value: '123'
    expires: +new Date()
})
...
```
2.  open the devtools and see the `expires` field

**What is the expected result?**
`expires` looks like `2018-08-22T07:46:08.956Z`

**What happens instead?**
`expires` is actually `+050434-06-16T19:39:45.999Z`

**Comment by benjamingr** [comment]
You're passing milliseconds to a method that expects seconds. You're just missing `/ 1000`
