### ISSUE TITLE
Missing error reasons in Puppeteer defined in protocol spec

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [puppeteer/puppeteer#2772]
Puppeteer's Network Manager is missing a couple error reasons that are defined in the Chrome Developer Tools Protocol specifications:

https://chromedevtools.github.io/devtools-protocol/tot/Network#type-ErrorReason

I created at short PR: #2771 , that extends that dictionary to add the missing ones.

**Comment by aslushnikov** [comment]
Closing since that PR got successfully merged.
