### ISSUE TITLE
Add a post PDF hook

### ISSUE THREAD

**Issue by Drew-S** [puppeteer/puppeteer#2773]
Can we get a hook that we can attach to `page.pdf()` so when the pdf is finished being formatted we can manipulate the print formatted DOM? Get headers and footers not by template by each instance of them in an actual DOM before final print of PDF?

**Comment by aslushnikov** [comment]
@Drew-S DOM formatting is done in PDF library itself; IIRC it doesn't operate any standard terms, so exposing it via API doesn't make much sense.

**Comment by Ciantic** [comment]
I disagree with closing this, if you want to make a great PDF's, something radically different is required. Such as modifying the DOM.

There is no way the CSS alone will ever catch up with LaTeX, it needs a lot more.
