### ISSUE TITLE
Can't collect coverage of anonymous scripts

### ISSUE THREAD

**Issue by abaksha-sc** [puppeteer/puppeteer#2777]
Please, add option to enable covering of anonymous scripts.

https://github.com/GoogleChrome/puppeteer/blob/dcae6bcff49150bec2060667fef7bd7ab71db042/lib/Coverage.js#L111-L114

Change it to somethink like that:
``` 
    if (!event.url && this.ignoreAnonymousScripts)
      return;
```
where `this.ignoreAnonymousScripts` defines as `true` by default to do not break current behavior.

**Comment by aslushnikov** [comment]
PRs are welcome!
