### ISSUE TITLE
Getting what is already in an input

### ISSUE THREAD

**Issue by palejo333** [puppeteer/puppeteer#2780]
I want to get what is already in an input, 
```js
     let emailCreated = await page.$("#email");
      await page.goto("https://undefeated.com/account/login");
      log("Entering Website..".blue);
      await page.type("#first_name", uName);
      await page.type("#last_name", uLast);
      await page.type("#email", jigEmail);
      await page.type("#password", password,);
      log("Email: " + emailCreated);
      await page.click("#register-form > div.control-wrapper.last > button");
      log("Solve Captcha...".blue);
```
Whenever I run the code the email that I get is equal to null
![undf](https://user-images.githubusercontent.com/33075602/41679663-fdf4f512-749c-11e8-8f36-6247e05457a1.png)
Is there any method that can use for this purpose, I looked in the API documents but I couldn't find any

**Comment by vsemozhetbyt** [comment]
Can you provide more code? If it is possible, a small complete script that reproduces the issue.

**Comment by pomerantsev** [comment]
You can do it like so (given that `emailCreated` is the email input element handle):
`const emailValue = await page.evaluate(emailInput => emailInput.value, emailCreated);`
(see the last example in the `page.evaluate` docs: https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pageevaluatepagefunction-args)
