### ISSUE TITLE
Error: Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by xingyesh** [puppeteer/puppeteer#2783]
### Steps to reproduce
**Tell us about your environment:**
node, egg, puppeter
* Puppeteer version:
* Platform / OS version:  centos
* URLs (if applicable):
* Node.js version: 8.9

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

**What is the expected result?**

**What happens instead?**
Puppeteer is invoke on a node http server.  My environment is 4cpu, 8g memory, start 3 workers.
When I use 80 request per 1 second, persist 10s, total 100 requests. 
Occur error:  Error: Protocol error (Runtime.callFunctionOn): Target closed.
Note: I use one browser instance, await puppeteer.launch.
Resource monitor:
![image](https://user-images.githubusercontent.com/16128175/41703537-3ad18f58-7566-11e8-9691-0abbc8a15184.png)
and I found another question, why always 3898424 buff/cache? 
```
const url = this.ctx.request.query.url;
    if (!this.app.config.browser) {
      this.app.config.browser = await puppeteer.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu','--disable-dev-shm-usage'],
        dumpio: false //显示chrome log信息和错误信息，在调试阶段最好开着，能够知道出错原因,
        // , devtools: true
      });
    };
    const browser = this.app.config.browser;
    const page = await browser.newPage();
    await page.setViewport({ width: 320, height: 600, isMobile: true, deviceScaleFactor: 2 });
    await page.goto(url, {timeout: 500000, waitUntil: "networkidle0"});
    // await page.waitFor(10000);
    // await page.evaluate(() => {
    //   return Promise.resolve(window.scrollTo(0,document.body.scrollHeight));
    // });
    await page.waitFor(5000);
    const elements = await page.evaluate(() => {
      return[];
    });
    const path = `/public/temporary/${uuidv4()}.png`;
    await page.screenshot({ path: 'app' + path, fullPage: true });
    await page.close();
```

**Comment by aslushnikov** [comment]
@xingyesh this has something to do with your environment; I don't think we'll be able to help you here.

**Comment by xingyesh** [comment]
@aslushnikov thanks for your reply。I fixed it before and forget to close this issue, sorry

**Comment by zhoujingchao** [comment]
@xingyesh how to fix it

**Comment by ofarukcaki** [comment]
@xingyesh You can help others with telling how you solve it
