### ISSUE TITLE
VCR test for puppeter

### ISSUE THREAD

**Issue by rusikf** [puppeteer/puppeteer#2785]
Is it possible to write vcr tests for puppeter ? ( record all requests through puppeter to files, so on repeat run, tests are not making real requests)

**Comment by aslushnikov** [comment]
What's VCR?

**Comment by aslushnikov** [comment]
Puppeteer itself doesn't support this out-of-the-box, but it is possible to imlpement this using [request interception](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pagesetrequestinterceptionvalue) or [regular proxy](https://github.com/GoogleChrome/puppeteer/blob/master/examples/proxy.js).
