### ISSUE TITLE
[feature] Wait for network requests even if not navigating

### ISSUE THREAD

**Issue by furstenheim** [puppeteer/puppeteer#2786]
Hi, I'd be interested in knowing when network becomes idle.

When navigating to a new page that is possible with networkidle2 and similar.

However in my case I'm triggering events that launch requests. Is it possible to trigger those requests and then wait till network is idle again?

I've tried with waitForNavigation but doesn't seem to work if I stay in the same page

**Comment by aslushnikov** [comment]
Network requests are exposed as [`page.on('request')`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-event-request) event.

You can track network idleness on your own side, listening to `request`, `requestfinished` and `requestfailed` events.

Hope this helps.
