### ISSUE TITLE
API bikeshed: rename deviceScaleFactor to devicePixelRatio in public API

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#279]
If they're the same, then it'd be way easier on users to use the same term.

**Comment by JoelEinbinder** [comment]
Unfortunately they are different. [dpr](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) doesn't change when you pinch zoom on a mac for example.

**Comment by paulirish** [comment]
Gotcha. Can we add that distinction to the docs?
