### ISSUE TITLE
Connecting Puppeteer to a Chrome-Launcher instance.

### ISSUE THREAD

**Issue by rlpham** [puppeteer/puppeteer#2790]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.5.0
* Platform / OS version: Mac OS X El Capitan v10.11.6
* URLs (if applicable):
* Node.js version: v10.2.1

**What steps will reproduce the problem?**
1. 
const chromeLauncher = require('chrome-launcher');
const puppeteer = require('puppeteer');
const request = require('request');
const util = require('util');

(async() => {

const chrome = await chromeLauncher.launch({
  startingUrl: 'http://www.google.com'
});

const resp = await util.promisify(request)(`http://localhost:${chrome.port}/json/version`);
const {webSocketDebuggerUrl} = JSON.parse(resp.body);
const browser = await puppeteer.connect({
  browserWSEndpoint: webSocketDebuggerUrl
});
const page = browser.newPage();

})();

**What is the expected result?**
Puppeteer connects with the chrome launcher instance and creates a new page.

**What happens instead?**
Stays on starting url (google.com) unsure if it is actually connected to it or not.

**Comment by aslushnikov** [comment]
This should work. Make sure chrome launcher launches Chrome 69; otherwise, things won't work.

**Comment by MeetPatel5** [comment]
I am still not getting , how to connect puppeteer with chome instace ? give me live example with that open third-party website using browser instace (if possible !)

**Comment by ebidel** [comment]
There's an example on
https://github.com/GoogleChromeLabs/puppeteer-examples/blob/master/lighthouse/chromelauncher_puppeteer.js
.

I'd use page.goto() to navigate to the URL. IOW use chrome launcher to only
launch a new instance of chrome, use puppeteer for everything else.
