### ISSUE TITLE
Connecting to a chrome instance running in a docker container through puppeteer locally and opening a localhost page

### ISSUE THREAD

**Issue by meghs94** [puppeteer/puppeteer#2791]
I am running headless chrome in a docker container and accessing it through puppeteer by running it locally using browerWSEndpoint. This part works fine. Once I get the connection established I try to use the instance to go to a localhost:port which fails and I get the following error:

Error: net::ERR_CONNECTION_REFUSED at http://localhost:port/
    at navigate (path_to/node_app/puppet/node_modules/puppeteer/lib/Page.js:521:37)
    at anonymous
    at process._tickCallback (internal/process/next_tick.js:188:7) 

* Puppeteer version:^1.2
* Platform / OS version: My puppeteer is running on my local machine which is MacOS 10.13.4 and the docker container is linux.
* Node.js version: v8.11.2

1. I used the [following](https://github.com/skalfyfan/dockerized-puppeteer) for setting up headless chrome in my container. (Note: Didnot use the app folder but only chrome)
2. Used puppeteer to connect to this chrome instance.
3. Tried to open a localhost:<port>.

`await page.goto("http://localhost:<port>", {waitUntil: 'networkidle0'});`

Expected:
Connection established and docker container stopping. 

Actual:
Error: net::ERR_CONNECTION_REFUSED at http://localhost:port/
    at navigate (<path>/node_app/puppet/node_modules/puppeteer/lib/Page.js:521:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) 

Thank you.

**Comment by aslushnikov** [comment]
Looks like this has something to do with your Docker setup or your environment. I don't think we'll be able to help you here.

I'd try asking on our [slack channel](https://join.slack.com/t/puppeteer/shared_invite/enQtMzU4MjIyMDA5NTM4LTM1OTdkNDhlM2Y4ZGUzZDdjYjM5ZWZlZGFiZjc4MTkyYTVlYzIzYjU5NDIyNzgyMmFiNDFjN2UzNWU0N2ZhZDc) or [stackoverflow](https://stackoverflow.com/questions/tagged/puppeteer).

**Comment by meghs94** [comment]
@aslushnikov  I am able to access the chrome instance. That means that my dockerfile should be correct right? Also, from my puppeteer running locally I can open "www.google.com" and such while I can't open any localhost:port.

**Comment by meghs94** [comment]
Docker local isnt same as machine local. I used the hostname and it worked.

**Comment by morgs32** [comment]
@meghs94 I'm trying to something similar using `alpeware/chrome-headless-trunk`? But when I try to use it I get `[0527/165302.978466:ERROR:browser_process_sub_thread.cc(221)] Waited 1 ms for network service`. How are you pulling this off?

**Comment by daddydrac** [comment]
> Docker local isnt same as machine local. I used the hostname and it worked.
@meghs94 
Is it the hostname of the docker container or the host the containers are running on?
