### ISSUE TITLE
IP not being changed

### ISSUE THREAD

**Issue by developer239** [puppeteer/puppeteer#2792]
### Steps to reproduce

**Tell us about your environment:**

package.json
```
"puppeteer": "^1.5.0"
```
.nvmrc
```
v10.5.0
```

**What steps will reproduce the problem?**

Basically, any proxy server (for example from this website https://www.socks-proxy.net/) will not change my IP
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: ['--proxy-server=http=188.134.1.20:63756'],
    ignoreHTTPSErrors: true,
    headless: false
  })
  const page = await browser.newPage()
  await page.goto('https://www.purevpn.com/what-is-my-ip', { waitUntil: 'networkidle0' })
  // I can see my native IP on a screenshot
  await page.screenshot({ path: 'example.png' })

  await browser.close()
})()
```

**What is the expected result?**

I should have a new IP.

**What happens instead?**

IP is not changed.

**Comment by pomerantsev** [comment]
Seems like the issue is with the argument you're passing. You set a proxy server for HTTP only, but then you open a page using HTTPS - so naturally, you see your IP (since no proxy is set for HTTPS).
Changing the argument to `'--proxy-server=https=188.134.1.20:63756'` should solve the problem.

**Comment by iraqwarvet31** [comment]
Did you get it working?
