### ISSUE TITLE
Add non-resolved urls to the request/response

### ISSUE THREAD

**Issue by larsbs** [puppeteer/puppeteer#2793]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Mac OS X 10.3.5
* URLs (if applicable): 
* Node.js version:  10.0.0

**What steps will reproduce the problem?**

Inspecting requests or responses received from `page.on('response')` or `page.on('request')` doesn't show the original url anywhere. Basically, I'm trying to clone a website for offline usage and I need to replace every occurrence of the original URL by a local equivalent. Since it's possible to define urls like:
`my-styles.css` and that would be converted to `http://hostname/my-styles.css` it's impossible to do a simple search and replace right now.

**What is the expected result?**

Being able to access original url somehow like `response.url() => response.literalUrl()` or similar.

**What happens instead?**

Only the resolved url is accessible.

**Comment by aslushnikov** [comment]
We don't have "original URL" anywhere in DevTools protocol, and it will require a lot of engineering time to plumb it through chromium layers.

I don't think it's worth the effort.

Regarding of "bringing website offline", you might be interested in MHTML format that has an experimental implementation in Chrome.
