### ISSUE TITLE
net::ERR_ABORTED during headless testing 

### ISSUE THREAD

**Issue by maximkoshelenko** [puppeteer/puppeteer#2794]
Hello team. Need help with issue which only reproduce in headless mode. I have a test which is checked 200 and 206 result after clicking the footer links of site. But after adding PDF file as a footer link test crashed in headless mode (in debug mode it is working).  Please help solve this problem :). 

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version: Windows
* URLs (if applicable): http://marketing.advanstar.info/mediakits/TC_MK_2016.pdf
* Node.js version:
npm -v : 5.6.0
**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

      await page.goto('http://www.cancernetwork.com/', { waitUntil: "domcontentloaded" });
      await page.waitForSelector('.expanded .menu');
      let footerLinks = await page.evaluate(
        () => Array.from(document.body.querySelectorAll('.expanded a[href]'), ({ href }) => href)
      );
      for (var r = 0; r < footerLinks.length; r++) {
        let  [response] = await Promise.all([
            page.waitForNavigation(),
            await page.goto(footerLinks[r], { waitUntil: "load" }),
          ]);

        if (response._status == 206) {
          expect(response._status).toBe(206);
        } else {
          expect(response._status).toBe(200);
        }

        response = '';
        console.log('Footer link: ' + footerLinks[r] + ' was checked successfully');
      }

**What is the expected result?**
Going to http://marketing.advanstar.info/mediakits/TC_MK_2016.pdf page with 200 or 206 status
**What happens instead?**
Without headless mode code is working, but in headless there is an error
    
net::ERR_ABORTED at http://marketing.advanstar.info/mediakits/TC_MK_2016.pdf
at navigate (node_modules/puppeteer/lib/Page.js:592:37)

I have tried execute code at https://try-puppeteer.appspot.com/ site
Code: 
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('http://marketing.advanstar.info/mediakits/TC_MK_2016.pdf');
await browser.close();

Result:
Error running your code. Error: net::ERR_ABORTED at http://marketing.advanstar.info/mediakits/TC_MK_2016.pdf

**Comment by aslushnikov** [comment]
Hi @maximkoshelenko,

Contrary to Headful Chrome, Chrome Headless doesn't know how to navigate to PDFs. I think it'll issue a download instead, but downloads are not supported yet: #299

**Comment by maximkoshelenko** [comment]
Thanks. Hope downloads will be supported ASAP :)

**Comment by gsouf** [comment]
@aslushnikov are there any way to know that the ``net::ERR_ABORTED`` is issued because of a download when we catch the issue? 

We could use request interception and to look at content type, but ideally I want to be able to handle it in the catch

**Comment by matej2** [comment]
Why is this closed? My issue occurs when redirecting...

**Comment by ghost** [comment]
How can this error due to a pdf file be distinguished from other errors? I also hit this problem and could try-catch it, but I am afraid I will oversee other errors unrelated to pdfs.

**Comment by deansg** [comment]
@gsouf Can you expand on how to implement that? The content type isn't known until there is a response, and the resourceType() for pdf pages is simply "document"

**Comment by gsouf** [comment]
@deansg I'm doing something like this. I cannot share more because the rest is part of a more complex thing but this is the gist of it:

```js
const page = openSomePuppeteerPage();

async function pageOnResponseRequest(response) {
  if (response.frame() === page.mainFrame() && response.request().isNavigationRequest()) {
    const statusCode = response.status();
    const headers = response.headers();

    // At this point you have access to status code and headers which you can use to detect that it's an html document, an image, a downloadable document, etc...

  }
}

page.on('response', pageOnResponseRequest);
```

**Comment by deansg** [comment]
@aslushnikov Do you know which content types experience this behaviour? So that I can use gsouf's idea to filter them out

**Comment by gsouf** [comment]
@deansg everything that is a download.  I would say everything that is not a displayable text (html, maybe xml and json?) and images. Maybe video and audio too? Havent tested all of those

**Comment by deansg** [comment]
@gsouf My problem is that I faced websites that return javascript content type, and then continue loading until proper HTML is loaded. If I intercept the first response and immediately decide that the website isn't relevant because that content type isn't HTML bases, then I lose valuable information (I need only extract content only from websites that return html). I'm not sure whether it's better to build a blacklist of content types, or a whitelist.

**Comment by gsouf** [comment]
@deansg the solution I proposed filters only navigation requests for the main frame. What you want to do is to process the request only if content type (from response headers) is html

**Comment by gsouf** [comment]
@deansg I have never seen a website returning javascript content type and running properly. The browser wont process the javascript. I will just display it on screen as simple text

**Comment by deansg** [comment]
@gsouf when I try to navigate to the following website:
https://atelierhaussmann.de/en/
The 'response' event is called several times, and in several of the cases the content type is application/javascript

**Comment by gsouf** [comment]
@deansg you'll have to figure out what's wrong because it does not occur for me. Even with your website, I confirm it has content-type text/html

**Comment by pepsiamir** [comment]
I get the same error when I want to get the redirect chain of an url. any solution to exit the process after fetching the data?

Error: net::ERR_ABORTED at https://www.example.com/vip-dl/?filename=23309907.rar
    at navigate (C:\Users\noora\AppData\Roaming\npm\node_modules\puppeteer\lib\FrameManager.js:120:37)

**Comment by vaishnavravi33** [comment]
> I get the same error when I want to get the redirect chain of an url. any solution to exit the process after fetching the data?
> 
> Error: net::ERR_ABORTED at https://www.example.com/vip-dl/?filename=23309907.rar
> at navigate (C:\Users\noora\AppData\Roaming\npm\node_modules\puppeteer\lib\FrameManager.js:120:37)

A similar error I am also facing, Any help appreciated.

**Comment by arnasledev** [comment]
going over the same issue for the past few days, was working fine before, nothing has changed...

**Comment by chinmaey** [comment]
I need to test the download speed for video download. I face same issue.

**Comment by Rbrandao7** [comment]
That issue is related to a bad connection? I am face same issue, sometimes this error appear and others no.

**Comment by StoneCypher** [comment]
In my case, the reason for this was that I was trying to run several jobs in parallel with promises, and I hadn't noticed that they were all using the same page object.

**Comment by smashah** [comment]
Another reason you may be experiencing this error consistently is that your system is telling chrome to use `jemalloc`.

Turn off system-wide `jemalloc` to get rid of this error.

See: https://github.com/puppeteer/puppeteer/issues/8246#issuecomment-1356463832

**Comment by yunnysunny** [comment]
> Another reason you may be experiencing this error consistently is that your system is telling chrome to use `jemalloc`.
> 
> Turn off system-wide `jemalloc` to get rid of this error.
> 
> See: [#8246 (comment)](https://github.com/puppeteer/puppeteer/issues/8246#issuecomment-1356463832)

I use win10, have the same error.
