### ISSUE TITLE
Function as a string cannot pass in arguments.

### ISSUE THREAD

**Issue by kevupton** [puppeteer/puppeteer#2797]
## BUG / QUESTION:
How do I access arguments when the executed value is a string ?

```ts
page.evaluate(`function testFn(args) {
}`, args);
```

I have to use:

```ts
page.evaluate(`(function(args) {
})()`, args);
```

If the function is a string, it does not call the function. 
How do I execute the function with arguments when the function is a string?

**Comment by vsemozhetbyt** [comment]
Maybe this way?
```js
page.evaluate(`(function(args) {
})(${args})`);
```

**Comment by kevupton** [comment]
yeh nice, simple answer. I like it, been awake for too long :/
