### ISSUE TITLE
Puppeteer with Node 10.5.0 multi thread

### ISSUE THREAD

**Issue by pavel-sindelka** [puppeteer/puppeteer#2799]
Hello guys! Am I able to use multi thread with Puppeteer for parallel testing?

https://stackoverflow.com/questions/51020876/puppeteer-with-node-10-5-0-multi-thread

**Comment by yanivefraim** [comment]
I think you should take a look at [Jest](http://jestjs.io/en/):

> Jest parallelizes test runs across workers to maximize performance. Console messages are buffered and printed together with test results. Sandboxed test files and automatic global state resets for every test so no two tests conflict with each other.

There is also an easy setup for Jest with Puppeteer:
https://github.com/smooth-code/jest-puppeteer

**Comment by aslushnikov** [comment]
I'd agree with @yanivefraim's on using Jest.

Additionally to this, I don't see how node workers will help with speeding up typical end-to-end testing. Very little is going on in node.js context; most of the time is spent in the browser. The real speedup will come from sharding tests across multiple [browser contexts](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-class-browsercontext).
