### ISSUE TITLE
Node.parentElement is undefined inside evaluate

### ISSUE THREAD

**Issue by kevupton** [puppeteer/puppeteer#2800]
Parent element is undefined inside `page.evaluate`

```ts
return this._page.evaluate(`(() => {
      const query = ${JSON.stringify(query)};
      let item = document.querySelector(query);
      
     // THIS IS THE problem => item.parentElement === undefined
})()`);
```

**Tell us about your environment:**

* Puppeteer version: 1.4.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.9.1

**What steps will reproduce the problem?**
Running a page evalute script with the above format and item.parentElement will be undefined. 
The item is found but it doesnt not have access to parentElement or parentNode, even when the element is inside the body.

**What is the expected result?**
Expect `parentElement` to be defined

**What happens instead?**
`parentElement` is undefined.

**Comment by vsemozhetbyt** [comment]
How do you detect it is `undefined`? If you return it from the `page.evaluate()`, `undefined` is returned instead because DOM elements are not serializable.

**Comment by kevupton** [comment]
I was accessing the scrollTop property from inside a setTimeout which was inside a promise and was getting a cannot read scrollTop of undefined.

**Comment by vsemozhetbyt** [comment]
Could you provide a complete small script that reproduces the issue?

**Comment by kevupton** [comment]
I think it was specifically the `setTimeout` or the `Promise` that caused it.

This was my code that I was using.
```ts
return this._page.evaluate(`(() => {
      const query = ${JSON.stringify(query)};
      const item = document.querySelector(query);
      const parent = item.parentElement;
      
      return new Promise(res => {
        if (!item) {
          res({ error: 'No item found', scrolled: false });
          return;
        }
        
        const bounds = item.getBoundingClientRect();
        item.scrollIntoView({ block: 'start', behavior: 'smooth' });
        setTimeout(() => {
          if (bounds.top !== item.getBoundingClientRect().top) {
            try {
              res({ scrolled: true, scrollTop: item.parentElement.scrollTop }); // <--- THIS WOULD THROW 'cannot read scrollTop of undefined'
            }
            catch (e) {
              res({ scrolled: true, error: e + "", t });
            }
          }
          else {
            res({ scrolled: false, error: 'Already at bottom' });
          }
        }, 500);
      });
    })()`);
```

And this is now working, by declaring  the `parent` variable above, before using it:
```ts
return this._page.evaluate(`(() => {
      const query = ${JSON.stringify(query)};
      const item = document.querySelector(query);
      const parent = item.parentElement; // <--- THIS WORKS DECLARING IT ABOVE
      
      return new Promise(res => {
        if (!item) {
          res({ error: 'No item found', scrolled: false });
          return;
        }
        
        const bounds = item.getBoundingClientRect();
        item.scrollIntoView({ block: 'start', behavior: 'smooth' });
        setTimeout(() => {
          if (bounds.top !== item.getBoundingClientRect().top) {
            try {
              res({ scrolled: true, scrollTop: parent.scrollTop });
            }
            catch (e) {
              res({ scrolled: true, error: e + "", t });
            }
          }
          else {
            res({ scrolled: false, error: 'Already at bottom' });
          }
        }, 500);
      });
    })()`);
```

**Comment by guangzhou** [comment]
But，How can I get the parentElement inside evaluate ？

   const parents = await page.evaluate(() => {
        var contents = document.querySelectorAll('.next-select-arrow');
        var ids = []
        for (element in contents) { 
            var loutid = element.id
            var etmp = element.parentElement
            // while (loutid == '' || loutid == undefined) {
            //     etmp = element.parentNode;
            //     loutid = etmp.id;
            // }
            ids.push(etmp) 
        };
        return ids
    })
    await console.log(parents)

[ null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null ]
