### ISSUE TITLE
Corporate proxy - net::ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by minotaurrr** [puppeteer/puppeteer#2801]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

Running the code below
```
const path = require('path');
const puppeteer = require('puppeteer');
const AppRoot = path.resolve(__dirname);
(async () => {
    const browser = await puppeteer.launch({
        args: [
            --proxy-server: <proxy details>
        ],
    });
    const page = await browser.newPage();
    try {
        await page.goto('https://www.google.com' );
        console.log(page.title);
    } catch(err) {
        console.log(err.message);
    } finally {
        await browser.close();
    }
})();
```

**What is the expected result?**
Console prints page title

**What happens instead?**
I get this error - `net::ERR_TUNNEL_CONNECTION_FAILED`

Has anyone experienced similar? I've tried googling but haven't found any answer yet.

**Comment by minotaurrr** [comment]
solved it by doing the following
```
const proxyChain = require('proxy-chain');
const oldProxyUrl = '<proxy>:<port>';
const newProxyUrl = await proxyChain.anonymizeProxy(oldProxyUrl);
const browser = await puppeteer.launch({
        headless: true,
        args: [
            `--proxy-server=${newProxyUrl}`,
        ],
    });
```

**Comment by parmonov98** [comment]
> solved it by doing the following
> 
> ```
> const proxyChain = require('proxy-chain');
> const oldProxyUrl = '<proxy>:<port>';
> const newProxyUrl = await proxyChain.anonymizeProxy(oldProxyUrl);
> const browser = await puppeteer.launch({
>         headless: true,
>         args: [
>             `--proxy-server=${newProxyUrl}`,
>         ],
>     });
> ```

didn't work for me for https://konzinfobooking.mfa.gov.hu/ website! 
How can we get it working?

**Comment by bthmono** [comment]
The solution with `proxy-chain` did not work for us, but specifying the protocol within the `proxy-server` argument did. Take a look at [chromium's docs](https://www.chromium.org/developers/design-documents/network-settings/). 

You could try ``--proxy-server=https=${newProxyUrl}``

**Comment by grohiit** [comment]
> > solved it by doing the following
> > ```
> > const proxyChain = require('proxy-chain');
> > const oldProxyUrl = '<proxy>:<port>';
> > const newProxyUrl = await proxyChain.anonymizeProxy(oldProxyUrl);
> > const browser = await puppeteer.launch({
> >         headless: true,
> >         args: [
> >             `--proxy-server=${newProxyUrl}`,
> >         ],
> >     });
> > ```
> 
> didn't work for me for https://konzinfobooking.mfa.gov.hu/ website! How can we get it working?
> 
> bu it worked for google and other websites.

Were you able to figure out the issue? I'm having the same  issue for a differnet site.

**Comment by paulomartins01** [comment]
> > > solved it by doing the following
> > > ```
> > > const proxyChain = require('proxy-chain');
> > > const oldProxyUrl = '<proxy>:<port>';
> > > const newProxyUrl = await proxyChain.anonymizeProxy(oldProxyUrl);
> > > const browser = await puppeteer.launch({
> > >         headless: true,
> > >         args: [
> > >             `--proxy-server=${newProxyUrl}`,
> > >         ],
> > >     });
> > > ```
> > 
> > 
> > didn't work for me for https://konzinfobooking.mfa.gov.hu/ website! How can we get it working?
> > bu it worked for google and other websites.
> 
> Were you able to figure out the issue? I'm having the same issue for a differnet site.

Have you managed to solve this?
