### ISSUE TITLE
net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by minotaurrr** [puppeteer/puppeteer#2802]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**
```
const path = require('path');
const puppeteer = require('puppeteer');
const proxyChain = require('proxy-chain');
const url = 'https://www.google.com';
const AppRoot = path.resolve(__dirname);
(async () => {
    const oldProxyUrl = '<proxy>';
    const newProxyUrl = await proxyChain.anonymizeProxy(oldProxyUrl);
    const browser = await puppeteer.launch({
        headless: true,
        args: [
            `--proxy-server=${newProxyUrl}`,
        ],
        ignoreHTTPSErrors: true
    });
    const page = await browser.newPage();
    try {
        await page.goto(url);
        console.log(page.title);
    } catch(err) {
        console.log(err.message);
    } finally {
        await browser.close();
    }
})();
```

**What is the expected result?**
Can access page

**What happens instead?**
I get `net::ERR_SSL_PROTOCOL_ERROR`

**Comment by aslushnikov** [comment]
I don't think there's enough information for me to reproduce it locally. However, this certainly looks like a problem with your proxy chain; I'd file an issue to the `proxy-chain` project.
