### ISSUE TITLE
Ability to compare ElementHandle instances

### ISSUE THREAD

**Issue by ntzm** [puppeteer/puppeteer#2808]
My use case is for scraping sites with infinite scrolling, I want to do the following:

1. create an array of elements matching the selector
1. scroll to the bottom of the page (making it load new elements)
1. wait for new elements matching the selector
1. iterate through the new elements

However, it's quite difficult to determine what's a new element as there doesn't seem to be a way to determine if an ElementHandle is pointing to the same element as another instance of ElementHandle.

I hope this makes sense and fits in with your vision of what you want puppeteer to become!

**Comment by aslushnikov** [comment]
(I think I've already answered this on our Slack channel)

You can compare two element handles with `===` inside the page:

```js
const e1 = await page.$('.foo');
const e2 = await page.$('.bar');
const equal = await page.evaluate((e1, e2) => e1 === e2, e1, e2);
```

Hope this helps!

**Comment by ntzm** [comment]
Oh yes you did thanks, forgot to close. Thanks!
