### ISSUE TITLE
Page.Authenticate() does not work if using chrome instead of Chromium

### ISSUE THREAD

**Issue by ahm-3-d** [puppeteer/puppeteer#2809]
### Steps to reproduce

Puppeteer version: V1.5.0
Platform / OS version: Windows
Node.js version: 8.11.2

**What steps will reproduce the problem?**
```js
 this.browser = await puppeteer.launch({
       headless: this.options.headless,
      executablePath: findChrome(),
     args: [`--proxy-server=${iP}:${port}`]
});
 await this.page.authenticate({
     username: user,
     password: pass
})
```

**What is the expected result?**
Page opens, page.authentciate will auth the proxy and allow the browser to run on that proxy

**What happens instead?**
page.authenticate does not work, prompts user to enter information

**Comment by aslushnikov** [comment]
@AhmodK what's your chrome version?

**Comment by boxpositron** [comment]
68.0.3440.106 (Official Build) (64-bit)

**Comment by boxpositron** [comment]
Same issue here

**Comment by SBerkovic** [comment]
69.0.3497.81 (Official Build) (64-bit)

**Comment by phil-r** [comment]
Same issue, same version: `69.0.3497.100 (Official Build) (64-bit)`

**Comment by YungVDev** [comment]
I'm having the same issue with `70.0.3538.110` why is this closed?

**Comment by hynospt** [comment]
I am having the same problem .

Chrome Version : 71.0.3578.98 (Official Build) (64-bit)

If i change to chromium browser , the authentication works.
Please Help @aslushnikov

**Comment by aslushnikov** [comment]
@hynospt please file a separate issue with a good repro that we can run locally and debug what's going on. We won't be able to help if there's no repro.

**Comment by landaida** [comment]
someone found an alternative?

**Comment by ibrahimelement** [comment]
Same issue here

71.0.3578.98 (Official Build) (64-bit)
