### ISSUE TITLE
Headless mode does not load enabled browser extension

### ISSUE THREAD

**Issue by stefanbuck** [puppeteer/puppeteer#2819]
Running puppeteer with an enabled browser extension in headless mode does not invoke this browser extension. If I turn off the headless mode it works as expected. 

Since it's explicit listed with `headless: false` in the docs, it seems to be the correct behaviour, but also unexpected (at least for me). Would be interested why extensions are limited that way in puppeteer.

```
const browser = await puppeteer.launch({
  headless: false,
  args: [
    '--disable-extensions-except=/path/to/extension/',
    '--load-extension=/path/to/extension/',
  ]
});
```

**Comment by aslushnikov** [comment]
Unfortunately, chrome headless doesn't support extensions (this has been discussed for quite a while). We should highlight it somewhere in our docs, or better expand on the whole extensions support in Puppeteer (it's getting better and better, especially with #2812 on the horizon).

**Comment by aslushnikov** [comment]
For the record: filed https://github.com/GoogleChrome/puppeteer/issues/2823 for the docs.

**Comment by JackieGe** [comment]
how to load multiple extensions??

**Comment by connected-afaizkhademi** [comment]
@JackieGe you can load multiple extensions this way:
```
  const ex1 = 'path to ext1';
  const ex2 = 'path to ext2'
  const browser = await puppeteer.launch({
      headless: false,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '-disable-gpu', '--no-first-run', '--disable-notifications', `--disable-extensions-except=${ext1},${ext2}`, `--load-extension=${ext1}`, `--load-extension=${ext2}`]
  });
```

**Comment by connected-afaizkhademi** [comment]
> how to load multiple extensions??

@JackieGe you can load multiple extensions this way:

```
const ext1 = 'path to ext1';
const ext2 = 'path to ext2';
const browser = await puppeteer.launch({
      headless: false,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '-disable-gpu', '--no-first-run', '--disable-notifications', `--disable-extensions-except=${ext1},${ext2}`, `--load-extension=${ext1}`, `--load-extension=${ext2}`]
});
```

**Comment by wearhere** [comment]
Hey folks, thanks for updating the docs to note that Chrome Headless doesn't currently support extensions. I'm curious about that closing this issue—where is adding headless support for extensions tracked? Glad to file an issue somewhere if one doesn’t exist.

**Comment by wernerwernerwerner888** [comment]
anything new or planned here? or a workaround?
