### ISSUE TITLE
docs: Puppeteeer with Chrome Extensions

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#2823]
Puppeteer is organically getting better and better support for extensions.

We should expand in our docs on some common tasks to work with extensions and the limitations we have:
- use targets with `background_page` type to connect to background pages
- (once #2812 lands) explain how to access content scripts for a particular frame
- note that Chrome Headless doesn't support extensions; headful mode should be used.

**Comment by pomerantsev** [comment]
I can do it.
