### ISSUE TITLE
Api method for getting natural dimension of image in requestfinished event handler

### ISSUE THREAD

**Issue by kshyju** [puppeteer/puppeteer#2825]
Is it possible to get the natural dimension of an image downloaded as part of the a page inside the `requestfinished` event of the page ? I could not find any relevant properties on the response.

Here i can see the natural image size(400 *400) when i use the elements tab on dev tools.

![image](https://user-images.githubusercontent.com/144469/42119464-07e6f7c0-7bc1-11e8-89e7-8768bb04148d.png)

I am trying to get the same using puppeteer api. Does any of the api support this ?

**Comment by aslushnikov** [comment]
> Is it possible to get the natural dimension of an image downloaded as part of the a page inside the requestfinished event of the page?

@kshyju Unfortunately not; DevTools pull this information from image element itself, using `naturalWidth` and `naturalHeight` attributes.
