### ISSUE TITLE
(node:24898) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by khoi-thinh** [puppeteer/puppeteer#2834]
### Steps to reproduce
First of all, i couldn't install puppeteer as i was following the guide on github.
So i had to install with --unsafe-perm=true added

**npm install -g puppeteer --unsafe-perm=true**

> puppeteer@1.5.0 install /usr/lib/node_modules/puppeteer
> node install.js

Downloading Chromium r564778 - 100.9 Mb [====================] 100% 0.0s
Chromium downloaded to /usr/lib/node_modules/puppeteer/.local-chromium/linux-564778
+ puppeteer@1.5.0
updated 1 package in 8.098s

* Puppeteer version: 1.5.0
* Node.js version: 9.11.2
* Environment: CentOS 7 with apache 2.4.6 and php 7.2

**What steps will reproduce the problem?**
 After creating examples.js inside of this path /usr/lib/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome

```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```
Then execute` node examples.js`

**What is the expected result?**
saving a screenshot as example.png:

**What happens instead?**

```
(node:24898) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/usr/lib/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/puppeteer/lib/Launcher.js:285:14)
    at Interface.helper.addEventListener (/usr/lib/node_modules/puppeteer/lib/Launcher.js:274:50)
    at Interface.emit (events.js:185:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
(node:24898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Jiang-Xuan** [comment]
According to this article: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#troubleshooting

Install CentOS Dependencies:

```
pango.x86_64
libXcomposite.x86_64
libXcursor.x86_64
libXdamage.x86_64
libXext.x86_64
libXi.x86_64
libXtst.x86_64
cups-libs.x86_64
libXScrnSaver.x86_64
libXrandr.x86_64
GConf2.x86_64
alsa-lib.x86_64
atk.x86_64
gtk3.x86_64
ipa-gothic-fonts
xorg-x11-fonts-100dpi
xorg-x11-fonts-75dpi
xorg-x11-utils
xorg-x11-fonts-cyrillic
xorg-x11-fonts-Type1
xorg-x11-fonts-misc
```

then try again.

**Comment by madc0w** [comment]
installing various dependencies isn't really an option, since we run a hosted service.
so.... Puppeteer can't work unless we have root access to the server??
