### ISSUE TITLE
Chrome interferes with the process SIGINT event?

### ISSUE THREAD

**Issue by digitalnature** [puppeteer/puppeteer#2836]
When I use puppeteer, the SIGINT event doesn't work correctly anymore. It looks like puppeteer forces the process to close immediately, so if you have any code hooked in this event, it's not guaranteed to run...

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Ubuntu 14.04
* Node.js version: 10.2.1

**What steps will reproduce the problem?**

```

// some standard puppeteer launch code here

process.on('SIGINT', () => {
  setTimeout(function(){
     log('X');   // <- never reaches this point
     process.exit();
  }, 1000);

  console.log('Y');
});
```
This works fine without puppeteer.

**What is the expected result?**

For the event handler to handle the process exiting.

**What happens instead?**

process closes prematurely

**Comment by JoelEinbinder** [comment]
Puppeteer has an option for this! I am happy that someone will finally get to use it. `handleSIGINT`
https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-puppeteerlaunchoptions

**Comment by gcubeda** [comment]
for those clicking in JoelEinbinder link, in the url change v1.5.0 with v5.5.0 or whatever puppeteer version you're using
