### ISSUE TITLE
Giving timeout after evaluate in puppeteer is not working

### ISSUE THREAD

**Issue by Guruhbk** [puppeteer/puppeteer#2839]
I have a page which contains few visualizations. I have to evaluate and resize the charts. while evaluating, it takes few seconds to resize. Previously I did this using phantom. I use to give timeout in the callback function and it worked perfectly. I'm trying the same using puppeteer which is not working. Not working in the sense, the resizing did not happen even after the timeout. 

**sample phantom code(working)**
`page.evaluate(function(a, b) {
    return a + b;
     }, function(sum) {
    setTimeout(function() {
        console.log(sum);
    }, 2000)
    }, 1, 2);`
    

   
**sample puppeteer code(not working)**
`page.evaluate(function(a, b) {
    return a + b
    }, 1, 2).then(function(sum) {
    setTimeout(function() {
        console.log(sum);
    }, 2000);`

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with the last master version (1.5.0-post, Chromium r571375) on Windows 7 x64 using this code:

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    page.evaluate(function (a, b) { return a + b; }, 1, 2)
    .then(function (sum) { setTimeout(function () { console.log(sum); }, 2000); })
    .then(async function () { await browser.close(); });
  } catch (err) {
    console.error(err);
  }
})();
```
Output:
```sh
3
```

**Comment by Guruhbk** [comment]
Maybe I will explain it in a better way. I have a dashboard with several visualizations. I'm trying to resize each and every chart. when I tried that in chrome browser it took 2-3 seconds to come to exact size. I'm trying to give that few seconds time to the page before taking the pdf. Below is the code I used to do that. 
```
 page.evaluate(() => {
     for (var i = 0; i < $('.react-grid-item').length; i++) {
         $('.react-grid-item:eq(' + i + ')').css({
             position: 'absolute',
             height: '300px',
             width: '100%',
             top: (i * 300) + 'px',
             left: '0px'
         });
     }
    }).then(function() {
     setTimeout(function() {
         page.pdf({
             path: 'test.pdf',
             format: 'a4',
             margin: {
                 top: "75px",
                 bottom: "75px"
             }
         });
     }, 5000)
 });
```
I have also attached a sample pdf. In that u can see few chart are not in the right size which needsadditional time. 
**Note**: I have done the same kind of process in phantomjs. And it worked. 
[testWed Jul 04 2018 11:32:16 GMT+0530 (IST).pdf](https://github.com/GoogleChrome/puppeteer/files/2162001/testWed.Jul.04.2018.11.32.16.GMT.0530.IST.pdf)
@aslushnikov  can you help me out?

**Comment by Guruhbk** [comment]
As per I analyzed, the page waits only for 500ms to resize the charts, no matter how much timeouts I give.

**Comment by aslushnikov** [comment]
@Guruhbk it's hard to say for sure unless I have your page to play with. However, it's never a good idea to use timeout in node.js context to await page loading. You should use `page.waitForFunction` instead that
should await for char resizing.

Some pseudo-code might look like this:
```js
await page.waitForFunction(() => {
  const charts = $('.chart');
  for (const chart of charts) {
    if (chart.width > 200 || chart.height > 200)
      return false;
  }
  return true;
});
```

**Comment by Guruhbk** [comment]
@aslushnikov @ebidel  @vsemozhetbyt  I tried the above function. Still facing the same issue. The problem is when I load the URL, it loads fine. Then I'm evaluating the page and modifying the chart size. when I tried in chrome, It takes a few seconds for the charts to load on the exact position. In puppeteer no matter what function I use or give timeout after evaluate. The result is the same. I have attached the image comparison between visualization loaded in chrome vs puppeteer **(after applying the resizing code)**.  Hope it helps. Please let me know if you need any more details. 
![chromevspuppeteer](https://user-images.githubusercontent.com/22149594/42364539-1d02014c-8119-11e8-9171-8440016e43ff.png)

**Comment by Guruhbk** [comment]
I found the reason behind this issue. The height and width are given in the `page.setViewport()` should be equal to the height and width are given in `page.pdf()`. when it mismatches, I see the issue. In phantom, I didn't face such issues. Anyways, It is working now.
