### ISSUE TITLE
.setCustomHeaders doesn't always work

### ISSUE THREAD

**Issue by GregRos** [puppeteer/puppeteer#2842]
I'm calling `page.setCustomHeaders` to send a bunch of custom headers, but not all requests receive the headers I specify. The problem exists in Chromium r571375, but not r533271. Are there known limitations to the method? Should I activate it separately for all frames somehow?

Note that in 533271, I noticed that requests that open/are made by service workers don't receive the headers, but the problem in r571375 isn't related to service workers.

I can try to find a minimal working example, but it will take a bit of time. I'm hoping it's a known limitation.

**Comment by aslushnikov** [comment]
Hi @GregRos,

ServiceWorkers aren't affected by page's `setCustomHeaders` - they are a separate entity from page; we'll support them eventually - see #2634.

In a similar way, extension iframes operate out-of-process and we don't support them yet - see #2548.
Is this something you might be dealing with?

**Comment by GregRos** [comment]
No, no extensions are involved. And as I said, I'm not talking about the issue involving service workers. I'm talking about regular requests. It's specifically something that worked in r533271 but doesn't work in the latest version of Puppeteer (and some versions down the road) that use r571375.

I'll try to get a working example going.

**Comment by GregRos** [comment]
Okay, when I looked again the problem was gone. Even though I checked it a few days ago. Weird. Anyway, I'm going to close this until I figure it out.

I am going to report and reproduce another issue involving requests though, in another post.
