### ISSUE TITLE
Request interception fails if you emit a redirect, also headers don't seem to work

### ISSUE THREAD

**Issue by GregRos** [puppeteer/puppeteer#2848]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: 1.5.0
* Platform / OS version: Windows 10, x64
* URLs (if applicable): Any
* Node.js version: 8.11.0

**What steps will reproduce the problem?**
1. Set up request interception
2. In request interception, emit a redirect using `respond`. 
3. In most cases, the request caused by your redirect will not be intercepted.

You will need some kind of MITM proxy to see the requests. I use Fiddler and set up Chrome for that purpose. 

Here is code that will reproduce the issue:

```
const puppeteer = require("puppeteer");
const url = require("url");

(async() => {
    // You will need a MITM proxy set up to view the requests.
    let brow = await puppeteer.launch({
        args : [
            // set up the proxy
            `--proxy-server=http=localhost:8888;https=localhost:8888`
        ]
    });

    let page = await brow.newPage();
    // enable request interception
    await page.setRequestInterception(true);

    page.on("request", async rq => {
        let parsed = new url.URL(rq.url());
        let urls = rq.url();
        if (parsed.searchParams.has("request-hit")) {
            // Just log this
            console.log("Hit!", rq.url());

            // if the URL has this param, add another one and send the request on its way.
            parsed.searchParams.append("request-hit", "b");
            await rq.continue({
                url : parsed.toString(),
                headers : {
                    // This does not seem to work at all
                    "test-header" : "does-not-work?"
                }
            });
            return;
        }
        // if the request doesn't have this param, issue a redirect with this param
        parsed.searchParams.append("request-hit", "a");
        await rq.respond({
            status : 302,
            headers : {
                "location" : parsed.toString()
            }
        });
    });

    // Go to a random website:
    await page.goto("http://www.cnn.com");
})();
```

**What is the expected result?**
The redirected request should also be intercepted. In Fiddler, this should show up as lots of URLs having `request-hit=b` in their URL. It should also print logs to the console. Also, the header `test-header` should be present in the requests.

**What happens instead?**
After you emit the crafted 302 response, the following request is not intercepted, except in the case of the main page. The first request is a;ways intercepted and the first URL parameter is applied.

Also, the header `test-header` should appear in the request, but it doesn't appear anywhere at all.

**Note**
Requests after regular (not artificial) redirects are intercepted. If a server emits a redirect after your artificial redirect, the request following the natural redirect *will* be intercepted.

**Comment by tli5** [comment]
Issue persists on version ^1.9.0.
In our case the client side triggered redirected page got stuck but the request  was never intercepted (code never entered the page.on('request',...) callback block).

**Comment by aslushnikov** [comment]
Merging this all to a single umbrella bug - #3471. Please upvote to follow updates.
