### ISSUE TITLE
Puppeteer occasionally doesn't start on windows

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#285]
This seems to be a buffering issue: the stderr of the child_process is empty on windows unless the chromium is closed.

**Comment by aslushnikov** [comment]
A fix has landed upstream as [r494712](https://chromium-review.googlesource.com/c/616026), @JoelEinbinder has validated that it's working on r494715

**Comment by kensoh** [comment]
Thanks @aslushnikov and gang for rolling out Puppeteer! The issues looks like an early indication of synergies that can only happen when browser automation tool and browser dev team is one team :smile:
