### ISSUE TITLE
Not clicking hyperlink with long text

### ISSUE THREAD

**Issue by ziadali1** [puppeteer/puppeteer#2850]
When i try to click an hyperlink with a long text nothing happens.

```
await page.waitForSelector('#ct01');
await page.click('#ct01'); 
```

**Working:**
`<td><a id="ct01" href="javascript:window.open(URL,'RecoverPassword','width=700,height=450');">TEST</a></td>`

**Not Working:**
`<td><a id="ct01" href="javascript:window.open(URL,'RecoverPassword','width=700,height=450');">TTT - TTTTTTTTTT TTT TTTTTTTTT T TTTTTTTTTTTT TTTTTTTTTTT TTTTT</a></td>`

* Puppeteer version: puppeteer@1.4.0
* Platform / OS version: Windows 7
* Node.js version: 9.10.1

Anybody knows why? And a possible solution to this?

**Comment by suever** [comment]
It's possible that the visible center of the bounding box of the link doesn't fall on the text. Does the link wrap from one line to the next? If so, the visible center is actually *between* the two lines.

**Comment by ziadali1** [comment]
Yes. It looks like this: 

![tttt](https://user-images.githubusercontent.com/40897460/42391593-4a2494b6-8126-11e8-8aea-1c8058023db8.JPG)

How to click on a link looking like this?

**Comment by vsemozhetbyt** [comment]
Maybe `page.evaluate(() => document.querySelector('#ct01').click())`?

**Comment by ziadali1** [comment]
Yes, working now. Thank you!
One question tho..

Working:
`page.evaluate(() => document.querySelector('#ct01').click());`

Not working:
```
variable = "#ct101";
page.evaluate(() => document.querySelector(variable).click())
```

I'm using this way because "ct01" is not fixed. I get this selector out of a table depending on the results.
That's why i'm putting on a variable. 
When i was doing this: page.click(variable); it was working, just not with long texts..
How can i use document.querySelector with variable?

**Comment by vsemozhetbyt** [comment]
I can think of two ways, with an additional argument or with a template string:
```js
    let selector = 'a';
    page.evaluate((selector) => document.querySelector(selector).click(), selector);
```
or
```js
    let selector = 'a';
    page.evaluate(`document.querySelector('${selector}').click()`);

```

**Comment by aslushnikov** [comment]
@ziadali1 this is fixed on tip-of-tree puppeteer; try installing `puppeteer@next` and using `page.click` with this long link.

Closing as dupe of #2798.
