### ISSUE TITLE
Unable to find element matching selector in headless mode but able to run without errors in non-headless

### ISSUE THREAD

**Issue by imXuanhao** [puppeteer/puppeteer#2851]
I am currently using Puppeteer and Jest to test a react app. However, I faced a very weird issue. When running it in non-headless mode, everything works and all DOM element can be found. However when I tried running it in headless mode, Puppeteer throws the following error:
> Error: failed to find element matching selector "#def" at Frame.$eval(node_modules/puppeteer/lib/FrameManager.js:335:13)

Does anyone faced the same issue? Or may have an idea on what is going on? 

I am quite new to testing so pardon me if I am not making sense. Tried many ways to figure out what is wrong but have yet to find any solution. Without having any page.click() or page.type() in all of the switch statements, it will be able to find the selector in both headless and non-headless.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Windows 7
* URLs (if applicable): Unable to provide.
* Node.js version: 5.4.2

**What steps will reproduce the problem?**

Here are some parts of the code to give a better context of what is happening.

1. Code for the FlyOut container puppeteer is trying to interact with.
```
<div class="FlyOutContainer">
    <form>
        <div class="order-details">
            <div class="card">
                <div class="form-group">
                    <textarea name="orderdesc" id="abc" rows="3" type="textarea" class="form-control"></textarea>
                </div>
            </div>
        </div>
    </form>
</div>
```
2. React will render different DOM elements in ".form-group" depending on the clicked order link.
```
<textarea name="orderdesc" id="abc" rows="3" type="textarea" class="form-control"></textarea>
<textarea name="comments" id="def" rows="3" type="textarea" class="form-control"></textarea>
<textarea name="reviewdes" id="ghi" rows="3" type="textarea" class="form-control"></textarea>
```
3. Testing code with puppeteer API
```
// First iteration, orderStatus is 'pending'. Second iteration, orderStatus is 'complete'
if('Testing for...', async () => {
    for (let i = 1; i <= count; i++){
        const orderLink = `.order tr:nth-child(${i}) > td > .order-link`;
        await page.click(orderLink);
        
        switch(orderStatus) {
            case 'pending':
                const selector1 = '#abc';
                const attribute1 = await page.$eval(selector1, elem => elem.getAttribute('aria-descendant'));
                await page.click(selector1);
                await page.type(selector1), 'Pls expedite this order');
                break;
            case 'complete':
                const selector2 = '#def';
                // It probably hit the error on the following line
                const attribute2 = await page.$eval(selector2, elem => elem.getAttribute('aria-descendant'));
                await page.click(selector2);
                await page.type(selector2), 'Pls archive this order');
                break;
            default:
                break;
        }
    }
});
```

**What is the expected result?**
Expected it to finish running in both headless and non-headless mode.

**What happens instead?**
It can finish running in non-headless mode but is unable to find element matching selector in headless mode.

**Comment by aslushnikov** [comment]
@imXuanhao can you please try this with puppeteer v1.5.0?

Your code samples look legit to me and don't reveal much.
Can you come up with a minimized script that will illustrate the problem and that I can run locally?
