### ISSUE TITLE
Chrome fails to launch on Windows 10

### ISSUE THREAD

**Issue by PeterAronZentai** [puppeteer/puppeteer#2853]
### Steps to reproduce

* Puppeteer version: 1.5.0
* Platform / OS version: Windows 10 / 1803 / 17692.1004 (Enterprise Insider Preview)
* URLs (if applicable):
* Node.js version: 10.6.0

Repro code:
```javascript
const puppeteer = require('puppeteer')

async function doIt() {
    const browser = await puppeteer.launch()
}

doIt().then(console.log).catch(console.log)
```

The result is below error:
```
{ Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at Object.spawn (child_process.js:528:9)
    at Function.launch (c:\Users\z\source\repos\p\node_modules\puppeteer\lib\Launcher.js:116:40) errno: 'UNKNOWN', code: 'UNKNOWN', syscall: 'spawn' }
```

Windows Event Log contains below helpfull message:
![image](https://user-images.githubusercontent.com/1798835/42418726-4e88b84e-82a6-11e8-9f32-fceda893e6d9.png)

```
Activation context generation failed for "c:\Users\z\source\repos\p\node_modules\puppeteer\.local-chromium\win64-564778\chrome-win32\chrome.exe". 
Dependent Assembly 69.0.3452.0,language="&#x2a;",type="win32",version="69.0.3452.0" could not be found. Please use sxstrace.exe for detailed diagnosis.
```

Is this something that's related to the Windows 10 box being on an insider release?

**Comment by Johnley** [comment]
I'm having a similar issue, when I run headless: false, I see a frowny face chrome tab with the url set to "chrome://welcome-win10/?text=faster" but nothing in the viewport.

Windows 10 Pro version 1607

**Comment by Ringosystems** [comment]
Having the same error on several builds of Windows 10.  Mine is odd because Chrome works for a few days then won't run with this message.  Rinse/Repeat.  I know how to fix (reinstall) but I want to stop this from happening.

**Comment by aslushnikov** [comment]
This sounds like a general Chromium problem. Would you mind asking on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) and filing a Chromium bug on the [https://crbug.com/new](https://crbug.com/new)?

**Comment by piampri** [comment]
Alot of folks seem to be having issues with Windows 10 etc. would be nice if the issues were prioritized instead of tickets being closed

**Comment by vanguy765** [comment]
I run this program https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagetitle} (Windows 10 machine, fresh boot with no other Chrome instances started. Latest versions of Node and Puppeteer.)

The first time it runs fine, and maybe a second time. But afterwords I get this error:

(node:5152) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (C:\Users\........\node_modules\puppeteer\lib\Launcher.js:339:14)
    at ChildProcess.helper.addEventListener (C:\Users\........\node_modules\puppeteer\lib\Launcher.js:329:60)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
(node:5152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.
