### ISSUE TITLE
page.content is not correctly working

### ISSUE THREAD

**Issue by u609** [puppeteer/puppeteer#2856]
### Steps to reproduce

* Puppeteer version:1.5
* Platform / OS version:ubuntu 1604
* URLs (if applicable): http://alumni.shmtu.edu.cn/site/shmtu/xyh/index/
* Node.js version:8.11.3

**What steps will reproduce the problem?**
My code：
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('request', req => {
     console.log(req.url());
  });

  await page.goto('http://alumni.shmtu.edu.cn/site/shmtu/xyh/index/');
  await page.waitFor(15000);
  const content = await page.content();
  console.log('GOT content length: '+ content.length);
  await browser.close();
})();
```
**What is the expected result?**
GOT content length: 33930

**What happens instead?**
GOT content length: 614

thanks !

**Comment by TomasHubelbauer** [comment]
Did you check the actual content to make sure an error page wasn't returned (thus different content and different content length) because the server might be detecting Puppeteer and returning different responses for it on purpose?

**Comment by u609** [comment]
Thank you  @TomasHubelbauer.
The content is ：
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head>
  
<title>上海海事大学校友会</title>
<meta http-equiv="keywords" content="">
<meta http-equiv="description" content="">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">


<link href="../source/index_style.css" rel="stylesheet" type="text/css">
<link href="../source/common.css" rel="stylesheet" type="text/css">
<link href="../source/item.css" rel="stylesheet" type="text/css">

<script src="../source/jquery-1.6.2.min.js" type="text/javascript"></script></head></html>

There is not <body> in this html. 
In addition，the response header included "transfer-encoding":"chunked"，there was not content-length field， maybe this is reason，but I have no solution。

**Comment by pomerantsev** [comment]
This seems to be an upstream bug in Chromium.

In headless mode, an abbreviated response is indeed reported for the above website, although I wasn't able to reproduce the same response with curl (using all the headers that headless Chromium is sending).

**Comment by u609** [comment]
@pomerantsev thank you very much!
is it a bug? 
how can i do?

**Comment by WeihanLi** [comment]
I've met the same problem, `await page.content()` does not return the full html, it seems is was truncated

**Comment by WeihanLi** [comment]
any update on this? @aslushnikov @pomerantsev
