### ISSUE TITLE
Trying to use page.$$eval to interact with a specific element in returned array

### ISSUE THREAD

**Issue by saadahmad03** [puppeteer/puppeteer#2859]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Mac OS Sierra 10.12.6
* URLs (if applicable):
* Node.js version: 8.11.3

Hi I am still pretty new to this, but basically I am trying to interact (click/type) with a specific element that is returned from the array created by `await page.$$eval()` but can't figure out how to

Here is my code:

``` 
test(
    'should enter in title on second line',
    async () => {
      await page.$$eval('#title', el => el[1].type('test title'));
    },
    300000
  );
```
However this doesn't seem to interact with the element that is returned at the [1] index, as there are two elements with the same id of title on this specific page. 

I tried running `Array.from(document.querySelectorAll('#title'))` in my console and get the following back: 
<img width="1440" alt="screen shot 2018-07-09 at 3 46 35 pm" src="https://user-images.githubusercontent.com/23708739/42480004-4b6061cc-8390-11e8-9e20-d80d0707bbcf.png">

So I know the element is there to be interacted with, just not sure if I am interacting with it correctly.

Any help is appreciated, thanks so much!

**Comment by vsemozhetbyt** [comment]
If I understand correctly, the function argument in `page.$$eval()` is executed in the browser context, while `el[1].type()` needs puppeteer context. Try this:
```js
const element = (await page.$$('#title'))[1];
await element.type('test title');
```

**Comment by saadahmad03** [comment]
Thanks so much @vsemozhetbyt this worked beautifully!

**Comment by saadahmad03** [comment]
@vsemozhetbyt just for my own understanding, would you be able to explain why 

works:
```
const element = (await page.$$('#title'))[1];
await element.type('test title');
```

does not work:
```
const element = await page.$$('#title')[1];
await element.type('test title');
```
I understand that context is at play but trying to wrap my head around it

**Comment by vsemozhetbyt** [comment]
The difference is in the [operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence): `await` has lower precedence than `[]` (property accessor), so we need to use parentheses.
