### ISSUE TITLE
capture and trigger click events 

### ISSUE THREAD

**Issue by tigerfsh** [puppeteer/puppeteer#2862]
how to capture and trigger click events implemented as in the following examples:
~~~
<input id="demo" type="button" value="Click Me!" />
<script type="text/javascript">
document.getElementById("demo").onclick=function() {
    alert(this.getAttribute("type"));
}
</script>
~~~
Any ideas?

**Comment by vsemozhetbyt** [comment]
If I get this right, to trigger you can use [`elementHandle.click()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleclickoptions) and  to capture you can use [`page.exposeFunction()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction).
