### ISSUE TITLE
Selector not visible to frame.waitForSelector(selector), but is found with frame.$(selector)

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#2865]
### Steps to reproduce

I am using Puppeteer 1.5.0. NodeJS 6.1.0. Windows 10 Pro. I have a selector that I know to be valid. When I call `frame.$(selector)`, I get an elementHandle object back. This signifies to me that it successfully found the element. However, I immediately followed that function call with `frame.waitForSelector(selector)`. I got the following error:

"Error: Node is either not visible or not an HTMLElement
    at ElementHandle._assertBoundingBox (C:\some path)
    at process._tickCallback (internal/process/next_tick.js:68:7)"

I would copy the output from print the ElementHandle, but it is long. The following should reproduce it, I think. The error comes up on the very last time of code below.
```js
await page.goto('https://www.google.com/');

selector = 'html>body>div>div:nth-child(8)>form>div:nth-child(2)>div:nth-child(2)>div>div>div:nth-child(2)>div>div>div:nth-child(2)>div>input';
container = await getContainer(selector); //gets the appropriate frame for the element
await container.type(selector, `nam`);

await page.keyboard.press(keyDictionary[`\${KEY_ENTER}`]);

selector = 'html>body>div:nth-child(8)>div:nth-child(2)>div>div>div>div>div:nth-child(2)>div:nth-child(2)>ul>li:nth-child(3)>a';

container = await getContainer(selector);

console.log(await container.$(selector)); //works as expected
await container.click(selector); //somehow does not work
```

**Comment by ghost** [comment]
Also, when I do the following, click works. It just does not update the page when navigating to a new link: container.evaluate( (s) => { document.querySelector(s).click(); }, selector);

**Comment by aslushnikov** [comment]
@calakin looks like clicking sometimes doesn't work for you. Could you please try with Puppeteer v1.6.0? We did a lot of work to make clicking much more reliable.
