### ISSUE TITLE
Sporadic ERR_ABORTED request error

### ISSUE THREAD

**Issue by maximedupre** [puppeteer/puppeteer#2867]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `v1.5.0`
* Platform / OS version: macOS `v10.13.5`
* Node.js version: `v9.5.0`

**What steps will reproduce the problem?**

Unfortunately, I can't provide access to the code as it's closed off, so this ticket will be useful only to the extent that others have a similar problem and chime in with a reproducible demo.

This error only occurs sporadically in headless mode and by sporadically I mean 50% of the time. It also seems to occur after puppeteer has been launched (and closed) twice before in the same script.

The same request that causes an "ERR_ABORTED" error works fine before it does not.

A breakpoint right at the entrance of my server code shows that no connection is made with my REST API when the "ERR_ABORTED" error occurs.

The same task is executed every time the puppeteer script runs, which is what confuses me the most.

The only other ticket that I see could be related to mine is: https://github.com/GoogleChrome/puppeteer/issues/2701, although my issue has nothing to do with serving a video file.

**Comment by aslushnikov** [comment]
@maximedupre it's hard to say exactly what's going on. In general, requests can be aborted in many cases, e.g. if one attaches an iframe to DOM and then detaches it. In this case the request for the frame's main resource will be initiated and then aborted. The same happens to media resources and probably some other website assets.

I'm not sure how else I can help here; let me know if you have any further questions.
