### ISSUE TITLE
The images made by page.screenshot are Incomplete when deviceScaleFactor is set to a large num

### ISSUE THREAD

**Issue by shenhaofang** [puppeteer/puppeteer#2868]
### Steps to reproduce

* Puppeteer version: 1.1.1
* Platform / OS version: Mac OS X 10.13.5
* Node.js version:v8.9.4

**What steps will reproduce the problem?**
The images made by page.screenshot are Incomplete when deviceScaleFactor is set to a large num.
For Example:
```

const program = require('commander')
const puppeteer = require('puppeteer')

const url = 'http://static.vcg.com/html/gettyTrend/creativeTrend.html',
    width = 2200,
    height = 900,
    pagenum = 5,
    outputPath = './output'

;(async () => {
    try{
        const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']})
        const page = await browser.newPage()
        await page.setViewport({width: Math.ceil(width), height: Math.ceil(height), deviceScaleFactor:5})
        await page.emulateMedia('print')
        await page.goto(url, {waitUntil: 'load', timeout: 300000})
        await page.waitFor(5000)
        for(var cp = 1; cp <= pagenum; ++cp){
            await page.screenshot({
                path: outputPath+cp+'.jpg',
                type: 'jpeg',
                quality: 100,
                clip: {
                    width: width,
                    height: height,
                    x: 0,
                    y: (cp-1)*height
                }
            })
        }
        await page.close()
        await browser.close()
        console.log('success')
    }catch(e){
        console.log(e)
    }
})()

```

**What is the expected result?**
The images made by page.screenshot should be complete.

**What happens instead?**
The images made by page.screenshot are incomplete. The right-bottom corner of the image is missing. 
Like This:
![output1](https://user-images.githubusercontent.com/35650594/42550018-bbaa6906-8501-11e8-89cf-1e3dc9f09da2.jpg)
![output5](https://user-images.githubusercontent.com/35650594/42550039-d2de5542-8501-11e8-9847-7876d18558b2.jpg)

**Comment by TheDutchCoder** [comment]
We can confirm this issue, but in a slightly more basic context: it just happens on large enough output sizes.

For example we generate a 24000x12000 image from a (very) basic SVG file and the file will only be about half rendered, same as @shenhaofang 

We generate print files at 150DPI, so we run into fairly large images regularly and they all appear to have the same issue.
