### ISSUE TITLE
Install fails - Centos 7

### ISSUE THREAD

**Issue by thetravellor** [puppeteer/puppeteer#2870]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.5.0
* Platform / OS version: Centos OS 7.5.1804 (core)
* URLs (if applicable):
* Node.js version: V10.6.0 (installed from nodejs.org centos repo).

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. node install puppeteer
2.
3.

**What is the expected result?**

The module gets install (no idea what the out put should be since its failing)

**What happens instead?**
[root@server ~]# npm install puppeteer

> puppeteer@1.5.0 install /root/node_modules/puppeteer
> node install.js

Downloading Chromium r564778 - 100.9 Mb [====================] 100% 0.0s
Chromium downloaded to /root/node_modules/puppeteer/.local-chromium/linux-564778
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ puppeteer@1.5.0
updated 1 package and audited 682 packages in 15.535s
found 0 vulnerabilities

Debug log: https://pastebin.com/4mju4fLY

**Comment by aslushnikov** [comment]
Dupe of #2857
