### ISSUE TITLE
avoid changing target's url or jumping into a new page

### ISSUE THREAD

**Issue by tigerfsh** [puppeteer/puppeteer#2871]
I am working with a web crawler.I need to trigger all the click events, so how do I avoid changing target's url or jumping into a new page?

**Comment by aslushnikov** [comment]
> so how do I avoid changing target's url or jumping into a new page?

@tigerfsh 
- to prevent navigations, you can enable [request interception](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pagesetrequestinterceptionvalue) and abort all [navigation requests](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-requestisnavigationrequest).
- there's no good way to prevent opening new pages, but you can listen to [`targetcreated`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-event-targetcreated) event and close all the targets which have your page's target as [`opener`](https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-targetopener)

Hope this helps.

**Comment by ratkorle** [comment]
How to avoid : Protocol error (Runtime.callFunctionOn): Cannot find context with specified id' }
when selecting options from select>option. Where url is changing and I am reassigning all elementHandles I need ? ??
