### ISSUE TITLE
puppeteer + crawl +distant remote

### ISSUE THREAD

**Issue by Minyar2004** [puppeteer/puppeteer#2876]
**Tell us about your environment:**
* Puppeteer version: 1.5.0
* Platform / OS version: Cent OS
* Node.js version: v8.4.0

Hi,

I would like to use puppeteer to crawl some websites.

I have three questions :

1- How can I launch the crawl on two web sites lists in parallel

2- will there be a chromium process for each running crawl?

3- Is it possible to distant remote chromium process, Is there commands to distant remote process launched from puppeteer?

Thank you

**Comment by aslushnikov** [comment]
These questions seem to be related to particular crawler implementation rather then to puppeteer.

If you're looking for a boxed solution, I'd use some crawling library instead of managing pptr directly.
E.g. https://github.com/yujiosaka/headless-chrome-crawler

Hope this helps
