### ISSUE TITLE
Page Crashed

### ISSUE THREAD

**Issue by radiolondra** [puppeteer/puppeteer#2877]
I'm creating PNG frames files using the code below. I open 1 page only with a canvas element. Everything works fine but I discovered this error once I asked to render 13000 frames. 

* Puppeteer version: 1.5.0
* Platform / OS version: Ubuntu 16.04 AWS EC2 Micro 8Gb memory
* URLs (if applicable):
* Node.js version: 8.11.1

(async() => {

				const browser = await puppeteer.launch({headless: true});
				const page = await browser.newPage();
				
				const projectData = data.project; // the project sent
				const cw = data.wantedW; // video width
				const ch = data.wantedH; // video height
				const tf = data.totalFrames; // video total frames at framerate
				const fr = data.framesRate; // video framerate
				const fld = data.folder; // the working folder

		  		try {

		    		await page.goto('http://localhost/template');
		    		
		    		const ret = await page.evaluate((projectData, cw, ch, tf, fr) => {
		      			
		      			// gets the project and prepare everything
		      			prepareProcess(projectData, cw, ch, tf, fr);

		      			return 'All set!';
		    		}, projectData, cw, ch, tf, fr)
		    	
		    		console.log('ret:', ret); // returns "All set!"
		    		
		    		// Now creates the PNG for all frames
		    		
		    		console.log('Start rendering ' + tf + ' frames');
		    		
		    		for (var idx = 0; idx <= tf; idx++) {
					
						//var a = new Date().getTime();
						
		    			var dataFrame = await page.evaluate( (idx) => {
		    				
							return doJob(idx);
							
							//return document.getElementById("phantom_outdata").value;
						}, idx);
						
						//var b = new Date().getTime();
		        		//console.log('Took ' + (b - a) + ' ms');
					
						// Creates the PNG from dataFrame
						dataFrame = dataFrame.replace(/^data:image\/png;base64,/, "");
						
						var pad = "00000";
						var frameNum = (pad + '' + idx).slice(-pad.length);

						fs.writeFile(rootWorking + fld + '/frame-' + frameNum + '.png', dataFrame, 'base64', function(err, data) {
							if (err) {
							    console.log('err', err);
							}
							//console.log('>> frame-' + frameNum + '.png file has been saved!');
						});

						console.log("Frame:" + idx);
						
					}
					
					callback(true);
					
		  		} catch (err) {

		    		console.log('ERR:', err.message);
		    		callback(false);

		  		} finally {

		    		browser.close();

		  		}

			})(); // ASYNC
			

**What is the expected result?**
No errors

**What happens instead?**
0|slaveapp | Frame:12477
0|slaveapp | Frame:12478
0|slaveapp | Frame:12479
0|slaveapp | Frame:12480
0|slaveapp | Frame:12481
0|slaveapp | Frame:12482
0|slaveapp | Frame:12483
0|slaveapp | Frame:12484
0|slaveapp | Frame:12485
0|slaveapp | Frame:12486
0|slaveapp | Frame:12487
0|slaveapp | Frame:12488
0|slaveapp | Frame:12489
0|slaveapp | Frame:12490
0|slaveapp | Frame:12491
0|slaveapp | Frame:12492
0|slaveapp | Frame:12493
0|slaveapp | Frame:12494
0|slaveapp | Frame:12495
0|slaveapp | Frame:12496
0|slaveapp | Frame:12497
0|slaveapp | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|slaveapp | Error: Page crashed!
0|slaveapp |     at Page._onTargetCrashed (/home/ubuntu/aws-slave/node_modules/puppeteer/lib/Page.js:156:24)
0|slaveapp |     at CDPSession.Page.client.on.event (/home/ubuntu/aws-slave/node_modules/puppeteer/lib/Page.js:132:56)
0|slaveapp |     at emitOne (events.js:116:13)
0|slaveapp |     at CDPSession.emit (events.js:211:7)
0|slaveapp |     at CDPSession._onMessage (/home/ubuntu/aws-slave/node_modules/puppeteer/lib/Connection.js:232:12)
0|slaveapp |     at Connection._onMessage (/home/ubuntu/aws-slave/node_modules/puppeteer/lib/Connection.js:119:19)
0|slaveapp |     at emitOne (events.js:116:13)
0|slaveapp |     at WebSocket.emit (events.js:211:7)
0|slaveapp |     at Receiver.receiverOnMessage (/home/ubuntu/aws-slave/node_modules/puppeteer/node_modules/ws/lib/websocket.js:720:20)
0|slaveapp |     at emitOne (events.js:116:13)

**Comment by aslushnikov** [comment]
Well, yes, Chromium is sophisticated, bugs are inevitable and sometimes pages are crashing. We're yet to provide a nicer page crashing support, see #1454.

Regarding this particular situation, I'd update the code to handle crashes gracefully.

**Comment by xprudhomme** [comment]
@aslushnikov because we only got a very simple "Error; Page crashed" error message, and no Exception is raised at all at that moment, even surrounding the code with a try/catch block does not seem to do the job.

How do you suggest we handle page crashes ?

**Comment by misha-erm** [comment]
@xprudhomme if it's still the case for you, `page.on(`error`, (error) => console.error(error))` should handle those

**Comment by Asheboy** [comment]
@MikeYermolayev Even that doesn't seem to catch all `Page crashed` errors.
