### ISSUE TITLE
Access chrome object in Extensions API

### ISSUE THREAD

**Issue by ganuonglachanh** [puppeteer/puppeteer#2878]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.5.0
* Platform / OS version: windows
* URLs (if applicable):
* Node.js version: 8.10

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I'm trying to disable webRTC local IP leak by using: 

```
await page.evaluateOnNewDocument(() => {
chrome.privacy.network.webRTCIPHandlingPolicy.set({
                    value: "default_public_interface_only"
                });
});
```

https://developer.chrome.com/extensions/api_index

**What is the expected result?**
access to chrome object like extension background.js

**What happens instead?**
chrome object in **undefined**

**Comment by ebidel** [comment]
You're trying to evaluate that piece of code in the context of the page, but `chrome.*` aren't available in the context of the page due to how CRXs work.

In the next release, you'll be able to use `target.page()` to get a `background_page` Page object. From there, you can call `page.evaluate` and UI think your snippet should work.

upcoming docs:
https://pptr.dev/#?product=Puppeteer&version=master&show=api-targetpage

**Comment by alex-wilmer** [comment]
> and UI think your snippet should work

inconvenient typo?

> and I think your snippet should work

right? anyways.. I'm going in circles trying to implement this. Where does `chrome` get populated? My use case is to grab the `proxy.settings`, click some buttons then assert that the settings have changed.

**Comment by aslushnikov** [comment]
> Where does chrome get populated?

@alex-wilmer It's available in the background page. There are some fresh docs on working with extensions: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions

Hope this helps.

**Comment by s16h** [comment]
@ebidel, how would one access `chrome.storage` after getting hold of the background page? I don't seem to have access to it in `backgroundPage.evaluate`.

@alex-wilmer, did you have any luck with this?

**Comment by JCMais** [comment]
did you have any luck implementing this @s16h ? Or anyone else
