### ISSUE TITLE
Use of already installed Chrome

### ISSUE THREAD

**Issue by bricss** [puppeteer/puppeteer#288]
Ok then, but what if I don't want to download standalone Chromium and want to use already installed Chrome on my machine? Or have no internet access on build machine and like to install it on my own?

**Comment by ebidel** [comment]
There's a note on this in [the readme](https://github.com/GoogleChrome/puppeteer#default-runtime-settings). You can point to an existing install of chromium using `executablePath`:

```javascript
const browser = await puppeteer.launch({executablePath: '/path/to/Chrome'});
 ```

Just note that the Puppeteer API is not guaranteed to work if you use a diff version of chrome.

If you don't have an internet connection, then I'm not sure. It'll be hard to install the package in the first place :)

**Comment by ebidel** [comment]
See also https://github.com/GoogleChrome/puppeteer/issues/244

**Comment by pratik-joshi-cactus** [comment]
Not working :/ in Version 75.0.3770.100 (Official Build) (64-bit), It still opens up new instance of chrome and it has no history whatsoever, I had to open it along with my other chrome tabs.

	const puppeteer = require('puppeteer');
	const pptr = require('puppeteer-core');
	(async () => {

		const browser = await puppeteer.launch({
		  headless: false,
		  executablePath: '/usr/bin/google-chrome'
		});

	})(); 

Here I also tried puppeteer-core , means pptr variable await pptr.launch in above variable, still not working. The issues is not closed!
Please check : 
https://drive.google.com/file/d/1WKjgPeruK9-ABeHHsumhcjs_FTlzFH4S/view

**Comment by leoplct** [comment]
This works for me on Mac OSX

```
const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    headless: false ,
    executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" //Found at chrome://version
});
```

**Comment by Jazeb** [comment]
I found the path in Linux as:
`/usr/bin/chromium-browser`
