### ISSUE TITLE
Does puppeteer have any APIs to get performance data like GPU, FPS?

### ISSUE THREAD

**Issue by li-01** [puppeteer/puppeteer#2884]
Now we are manually logging these data by enabling the "FPS meter" option under "Rendering" tools.

**Comment by li-01** [comment]
Does anyone know this?
I got the trace.json file, but I don't know where to start...

**Comment by aslushnikov** [comment]
Nah, FPS is not exposed through DevTools protocol. However, you can inject a little script into the page to compute its fps, e.g. check out [this StackOverflow question](https://stackoverflow.com/questions/8279729/calculate-fps-in-canvas-using-requestanimationframe)

Hope this helps.

**Comment by jquinc30** [comment]
[For any interested people: it's now possible.]

I've tested this working example:
```const puppeteer = require('puppeteer');

(async () => {
    const args = await puppeteer.defaultArgs().filter(flag => flag !== '--enable-automation');
    const browser = await puppeteer.launch({
        headless: false,
        devtools: true,
        ignoreDefaultArgs: true,
        args
    });
    const page = await browser.newPage();
    const devtoolsProtocolClient = await page.target().createCDPSession();
    await devtoolsProtocolClient.send('Overlay.setShowFPSCounter', { show: true });
    await page.goto('https://pptr.dev');
    await page.screenshot({ path: './image.jpg', type: 'jpeg' });
    await page.close();
    await browser.close();
})();
```

from https://addyosmani.com/blog/puppeteer-recipes/#devtools-cdp-metrics
