### ISSUE TITLE
Cannot read property '_bodyLoadedPromiseFulfill' of null

### ISSUE THREAD

**Issue by adamgotterer** [puppeteer/puppeteer#2888]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.0
* Platform / OS version: Jessie
* URLs (if applicable):
* Node.js version: 8.11.2

**What steps will reproduce the problem?**

I can't figure out from the stacktrace what action in my code is causing it

```
TypeError node_modules/puppeteer/lib/NetworkManager.js:280

node_modules/puppeteer/lib/NetworkManager.js:280:23_onLoadingFinished	
events.js:116:13emitOne	
events.js:211:7emit	
node_modules/puppeteer/lib/Connection.js:232:12_onMessage	
node_modules/puppeteer/lib/Connection.js:119:19_onMessage	
events.js:116:13emitOne	
events.js:211:7emit	
node_modules/ws/lib/websocket.js:720:20receiverOnMessage	
events.js:116:13emitOne	
events.js:211:7emit	
node_modules/ws/lib/receiver.js:414:14dataMessage	
node_modules/ws/lib/receiver.js:346:17getData	
node_modules/ws/lib/receiver.js:133:22startLoop	
node_modules/ws/lib/receiver.js:69:10_write	
_stream_writable.js:397:12doWrite	
_stream_writable.js:383:5writeOrBuffer	
_stream_writable.js:290:11write	
node_modules/ws/lib/websocket.js:795:35socketOnData	
events.js:116:13emitOne	
events.js:211:7emit	
_stream_readable.js:263:12addChunk	
_stream_readable.js:250:11readableAddChunk	
_stream_readable.js:208:10push	
net.js:597:20onread
```

**Comment by aslushnikov** [comment]
@adamgotterer do you have request interception enabled? It will help a lot if you'll come up with any repro for this.

**Comment by adamgotterer** [comment]
edit: added some clarity and fixed a few typos

I've also seen this happen in 1.5.0.

I can't reliably reproduce this bug. We have the code running with a production workload and it happens what seems like randomly. I've tried URLs that failed on the same code a second time and it succeeds. We are using Puppeteer with an express server as a way to provide an endpoint that can render and extract data about a webpage. We have lots of debug logging and request ID attached to all our logs as a way to track a single request life cycle. 

When this exception occurs it has a request id but it has no debug information prior to the exception. What's odd about it is there is debug information that is supposed to be outputted before even connecting to puppeteer. I'm starting to wonder if something from a previous Puppeteer request is leaking into the current request.

It's going to require some more digging...

**Comment by ydennisy** [comment]
I am also seeing this issue, and the rejection is not handled in the code:
```
(node:48040) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_bodyLoadedPromiseFulfill' of null
    at NetworkManager._onLoadingFinished (/Users/dennisy/scrape/node_modules/puppeteer/lib/NetworkManager.js:280:23)
    at CDPSession.emit (events.js:180:13)
    at CDPSession._onMessage (/Users/dennisy/scrape/node_modules/puppeteer/lib/Connection.js:232:12)
    at Connection._onMessage (/Users/dennisy/scrape/node_modules/puppeteer/lib/Connection.js:119:19)
    at WebSocket.emit (events.js:180:13)
    at Receiver.receiverOnMessage (/Users/dennisy/scrape/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:180:13)
    at Receiver.dataMessage (/Users/dennisy/scrape/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/Users/dennisy/scrape/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/Users/dennisy/scrape/node_modules/ws/lib/receiver.js:133:22)
```

**Comment by mkotsur** [comment]
Seeing the same issue when running an integration test with puppeteer (v18.0):

```
    TypeError: Cannot read property '_bodyLoadedPromiseFulfill' of null

      at NetworkManager._onLoadingFinished (node_modules/puppeteer/lib/NetworkManager.js:252:23)
      at CDPSession._onMessage (node_modules/puppeteer/lib/Connection.js:233:12)
      at Connection._onMessage (node_modules/puppeteer/lib/Connection.js:119:19)
      at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:720:20)
      at Receiver.dataMessage (node_modules/ws/lib/receiver.js:414:14)
      at Receiver.getData (node_modules/ws/lib/receiver.js:346:17)
      at Receiver.startLoop (node_modules/ws/lib/receiver.js:133:22)
      at Receiver._write (node_modules/ws/lib/receiver.js:69:10)
      at Socket.socketOnData (node_modules/ws/lib/websocket.js:795:35)
```

**Comment by aslushnikov** [comment]
@mkotsur any chance you can give me some details so that I can repro this?

**Comment by mkotsur** [comment]
Hey @aslushnikov !
Well, I can... I can even tell what the fix is. And may be you can tell if there is a way to monkey-patch this, perhaps...

So, the code is (I can't promise it will be working for a long time, though):

```
import * as puppeteer from "puppeteer";

const launch: () => Promise<[puppeteer.Browser, puppeteer.Page]> = async () => {
  const browser = await puppeteer.launch({ 
    headless: false
    // , slowMo: 250 
  });
  const page = await browser.newPage();
  return [browser, page];
};

const shutDown = async (browser: puppeteer.Browser, page: puppeteer.Page) => Promise.all([page.close(), browser.close()])

// THE INTERESTING PART STARTS HERE
  try {
    await page.goto("https://vault.rosx.technology");
    await page.click("header button");
    await page.waitForSelector('input[name="pf.username"]');
    await page.type('input[name="pf.username"]', "ertbnm+6pbwenc1esl3s@sharklasers.com");
    await page.click("#els-continue");
    await page.waitForSelector('input[name="password"]');
    await page.type('input[name="password"]', "123qwe");
    await page.click('button[type="submit"].els-primaryBtn', {delay: 1000});
    await page.waitForNavigation();
    await page.waitForSelector("h1");
  } finally {
    console.log("Closing the page and the browser");
    await page.close();
    await browser.close();
  }
```

I can fix this behaviour by going to the method mentioned at the top of the stack trace and changing:  `if (!request)` into `if (!request || !request.response())`. After this everything works just fine.

Are you aware of any more or less clean way of monkey patching this method in my project?

**Comment by mkotsur** [comment]
@aslushnikov I don't know what the root cause is, though. There is a storm of requests happening when the button is clicked. Perhaps, puppeteer is getting a but confused by that.

**Comment by aslushnikov** [comment]
@mkotsur this is awesome, thanks. I can repro and I see what's going on; let me see if I can do a test that reproduces this.

**Comment by aslushnikov** [comment]
@mkotsur I filed upstream: https://crbug.com/883475, but wasn't able to reproduce this behavior in a test.

> Are you aware of any more or less clean way of monkey patching this method in my project?

Fix should be merged sometime soon; once it is, you can install the tip-of-tree version of puppeteer with the fix using the `puppeteer@next` tag:

```
npm i puppeteer@next
```
