### ISSUE TITLE
Accessing selected iFrames and ElementHandle improvements

### ISSUE THREAD

**Issue by DavidXanatos** [puppeteer/puppeteer#2889]
Hello,

I'm looking into using puppeteer for some of my projects as a replacement to a custom DevTools Protocol wrapper, and I have noticed there seam a few really useful things to be missing in puppeteer.

One, which is manageable, is that  ElementHandle does not seam to provide useful access to the elements, you can not get outerHTML or the elements attributes (like href for a a element).
I know this is doable with tricks like: "page.$$eval("#episode-list-entry-tbl a", hrefs => hrefs.map((a) => {return a.href}));" but for a object oriented approach not as pretty as when there would be

ElementHandle.getAttribute(name: String)
ElementHandle.getAttributeList()

DOM.describeNode() provides the attributes, so before returning ElementHandle first get the node described and cache the attributes in the ElementHandle object

But the most problematic issue for which I don't see a workable workaround is accessing particular iFrames.

With page.frames() I can get a list of all frames in the page, but it does not seem to provide any information where the frames are located in the parent's DOM tree.
Now when the frame always makes quickly some multiple redirects or even better gets its content written to by the parent there is no way to identify it, as the only thing we know about it is its url().

I would suggest to extend the have a function page.selectFrames(selector) which returns a array of Frame objects which are located in iFrames for which said selector is valud.

Now I know that is not exactly easy with the DevTools Protocol, but its doable, I do that like this:

First I create a map of all frames of a page by using frameAttached and frameDetached of page object of CDP
```
                Page.frameAttached((params)=>{
                    let frame = new ChromeFrame(this, params.frameId, params.parentFrameId)
                    this.frames.set(params.frameId, frame);
                    this.emitFrame(frame);
                });
                Page.frameDetached((params)=>{
                    this.frames.delete(params.frameId)
                });
```
here params.frameId is a unique identifier

Than when I want to select a particular frame I can access it by this ID, now how do I get that ID?
Its easy, DOM.describeNode() provides also a optional parameter "frameId" which is the id we need when the described node is an iFrame.

It would be great if puppeteer could implement that functionality.

Cheers
David X.

**Comment by aslushnikov** [comment]
> One, which is manageable, is that ElementHandle does not seam to provide useful access to the elements, you can not get outerHTML or the elements attributes (like href for a a element).

@DavidXanatos Element handles could be passed as arguments to `page.evaluate`. So I'd do this like this:

```js
const handle = await page.$('.foo');
const outerHTML = await page.evaluate(e => e.outerHTML, handle);
```

> DOM.describeNode() provides the attributes, so before returning ElementHandle first get the node described and cache the attributes in the ElementHandle object

We don't do this since the information fetched with describeNode is getting stale really quick. The way to go is to jump into the page context any time you want to know something about the node.

> I would suggest to extend the have a function page.selectFrames(selector) which returns a array of Frame objects which are located in iFrames for which said selector is valud.

I didn't get this one: do you want an element handle that corresponds to the `frame` object?

**Comment by dodas** [comment]
I need answer to second answer: how do I get `ElementHandle<HTMLIFrameElement>` for corresponding `Frame`?

We have way of doing opposite: getting `Frame` from `ElementHandle<HTMLIFrameElement>`, but not the other way around.

Would following be valid solution?
```ts
function frameToIframeHandle (frame: Frame) {
  const parentFrame = frame.parentFrame();

  if (!parentFrame) {
    throw new Error('frameToIframeHandle: iframe has no parent frame');
  }

  const $iframes = await parentFrame.$$('iframe');

  for (const $iframe of $iframes) {
    const f = await $iframe.contentFrame();
    if (f === frame) {
      return $iframe;
    }
  }

  throw new Error('frameToIframeHandle: iframe not found');
}
```

Thanks.

**Comment by aslushnikov** [comment]
> I need answer to second answer: how do I get ElementHandle<HTMLIFrameElement> for corresponding Frame?

@dodas Your solution is a bit hackish but plausible. We can provide a nice API for you that will be much more performant - would you mind filing a separate feature request for this?
