### ISSUE TITLE
Example doesn't work on Windows 7

### ISSUE THREAD

**Issue by genu** [puppeteer/puppeteer#2894]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.0
* Platform / OS version: Windows 7
* URLs (if applicable): N/A
* Node.js version: v9.11.1

**What steps will reproduce the problem?**
Following the example from the usage section in the `README.md`

````js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
````

**What is the expected result?**
Expectation is that Chromium would launch, navigate to the url, and save a screenshot.

**What happens instead?**
Chromium launches but nothing happens (See Screenshot). It stays open for some time, and there is eventually a timeout error in the terminal:

```bash
(node:20860) UnhandledPromiseRejectionWarning: Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome
 revision guaranteed to work is r571375
    at Timeout.onTimeout (C:\Users\EI2074\Desktop\scripts\puppeteer\node_modules\puppeteer\lib\Launcher.js:296:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
(node:20860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an
 async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that ar
e not handled will terminate the Node.js process with a non-zero exit code.
```
![chromiumerror](https://user-images.githubusercontent.com/928780/42759266-64b70dee-88d4-11e8-9458-c4f343650392.png)

**Comment by aslushnikov** [comment]
> Chromium launches but nothing happens (See Screenshot). It stays open for some time, and there is eventually a timeout error in the terminal

Are you sure're running the script that you pasted to the issue? The one pasted is supposed to run headless chrome; you wouldn't be able to take a screenshot of the browser.

**Comment by genu** [comment]
Yes, I am. Its bizarre. The behavior is very off.

**Comment by aslushnikov** [comment]
We'll get our windows machine in a month; I won't be able to check before that. However, we have quite a few happy win7 users, so this looks like something related to the environment.

Can you please try using different puppeteer or node versions?

**Comment by mixn** [comment]
I thought I’ll leave [this](https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-413835707) here since it’s the exact same error + also Windows (`10`). Although the created issue and failed download itself is likely related to [#299](https://github.com/GoogleChrome/puppeteer/issues/299), that particular comment seems to be related to this.

**Comment by aslushnikov** [comment]
Closing this since there are no more details from @genu
