### ISSUE TITLE
URLs with binary content

### ISSUE THREAD

**Issue by konstantinblaesi** [puppeteer/puppeteer#2895]
Can puppeteer handle pages returning binary content such as pdfs, videos, etc.? We're using it as part of a crawler and of course we don't know the content-type before we actually visit the page. Are we supposed to do a HEAD request to the URLs and only crawl pages returning text content with puppeteer? I was trying `response.buffer()`, but so far I've been getting traces like these:
```
Error: net::ERR_ABORTED at http://foo.bar/file.pdf
    at navigate ([...]\node_modules\puppeteer\lib\Page.js:598:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Looks like `page.goto(url)` is already failing.
I need to store the binary content encoded as base64 using some API.

**Comment by aslushnikov** [comment]
@konstantinblaesi "binary urls" result in a download that is yet to be supported. Please see #299

**Comment by Nerdion** [comment]
I am facing this issue even on a get URI 
Error: net::ERR_ABORTED at https://www.deepl.com/translator#en/fr/%20Pork%20cheek%20with%20chorizo%20and%20Porto%20
