### ISSUE TITLE
document.webkitFullscreenElement always undefined 

### ISSUE THREAD

**Issue by samuelsh** [puppeteer/puppeteer#2896]
* Puppeteer version: 1.4
* Platform / OS version: MacOS Sierra
* URLs (if applicable): https://kabbalahmedia.info/en/lessons/daily/latest?language=en
* Node.js version: 9.0.8

Following code won't work, `webkitFullscreenElement` is undefined even if Full Screen mode is set:
```javascript
isFullScreen: async function (page) {
        const executionContext = await page.mainFrame().executionContext();
        const fullscreenElement =  await executionContext.evaluate(() => {
            return document.webkitFullscreenElement
        });
        console.debug('isFullScreen: ' + fullscreenElement);
        return !!(fullscreenElement && fullscreenElement.nodeName === 'video');
    }
```

**Comment by aslushnikov** [comment]
@samuelsh You should use `evaluateHandle` instead of `evaluate`.

It's unfortunate that `page.evaluate` doesn't throw an error in this case; this will be fixed in the next major release: #2079
