### ISSUE TITLE
not working "page.click" if "setJavaScriptEnabled" is "false"

### ISSUE THREAD

**Issue by mam4dali** [puppeteer/puppeteer#2898]
* Puppeteer version: 1.6
* Platform / OS version: windows 10
* URLs (if applicable): all !
* Node.js version: v8.11.3

Hi guys!
I can not click when I set "JavascriptEnabled" to "false"!
This problem is solved only by changing "false" to "true"!
Is this a problem of the "puppeteer" is?

**What happens instead?**
When "click" does not work, no output will not happen and is not even an error

**Edit**:
This problem exists only in v1.6.0
I tested in v1.5.0 and worked fine

**Comment by aslushnikov** [comment]
@M0H4MM4D0UTIS thanks, this is now fixed on tip-of-tree. It will be available shortly at `puppeteer@next`.
