### ISSUE TITLE
`goto({waitUntil: 'networkidle2'})` sometimes behaves different between `launch({headless: false})`

### ISSUE THREAD

**Issue by SidKwok** [puppeteer/puppeteer#2901]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.0
* Platform / OS version: macOs 10.13
* URLs (if applicable):
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Follow the code:
```javascript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = await context.newPage();

    await page.goto('https://wapbaike.baidu.com/yili/chanyelian', {
        waitUntil: 'networkidle2' // or networkidle0
    });
    console.log('landing page success');
    await browser.close();
})();

```
`waitUntil` is not emitted.
2.  change `headless` to `true`
`waitUntil` is emitted.

**What is the expected result?**
`waitUntil` is emitted no matter `headless` is `true` or not

**What happens instead?**
only `headless: true` will emit the `waitUntil`.

**Comment by aslushnikov** [comment]
@SidKwok this worked for me 10 out of 10 times. Your script uses undefined `context` variable, so I used `browser` instead:

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = await browser.newPage();
    await page.goto('https://wapbaike.baidu.com/yili/chanyelian', {
        waitUntil: 'networkidle2'
    });
    console.log('landing page success');
    await browser.close();
})();
```

**Comment by SidKwok** [comment]
<img width="549" alt="00542742a2e2ed2b1cb1e5e66f778c44" src="https://user-images.githubusercontent.com/13268747/42922931-8f4671ac-8b55-11e8-95b3-628e01e0ec7f.png">

but it doesn't work on my machine and docker. is it related to os?

**Comment by aslushnikov** [comment]
Hmm I was able to reproduce this now.

I see there's some 3d graphics on the website; can you please try running the following to see if it works better for you?

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        // a trick to run headless with GPU enabled.
        headless: false,
        args: ['--headless']
    });
    const page = await browser.newPage();
    await page.goto('https://wapbaike.baidu.com/yili/chanyelian', {
        waitUntil: 'networkidle2'
    });
    console.log('landing page success');
    await browser.close();
})();

```

**Comment by SidKwok** [comment]
Wow, problem solved! Thanks a lot!
