### ISSUE TITLE
Could not connect to localhost on Windows.

### ISSUE THREAD

**Issue by YozhEzhi** [puppeteer/puppeteer#2902]
### Steps to reproduce

* Puppeteer version: 0.13.0
* Platform / OS version: Windows 7 x64
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

1. Fork https://github.com/eggheadio-projects/puppeteer-testing
2. npm i
3. Run tests

I see `Error: net::ERR_CONNECTION_REFUSED` using `await page.goto('http://localhost:3000/')`.
But test works great with `await page.goto('https://www.google.ru/');`.

**What is the expected result?**
Puppeteer able to connect to localhost.

**What happens instead?**
`Error: net::ERR_CONNECTION_REFUSED`.

**Comment by YozhEzhi** [comment]
Argh. My bad. There was a mistake with start app command.
Puppeteer deals perfect with `localhost`.

**Comment by bsurai** [comment]
@YozhEzhi What was your mistake?

**Comment by YozhEzhi** [comment]
@bsurai I don't remember.
Maybe port was `8080` or something like that.

**Comment by travisk-codes** [comment]
For others: I was unable to get puppeteer to connect to localhost:3000 (`net::ERR_ABORTED at localhost:3000` I think?).
Adding `http://` before `localhost:3000` in `page.goto` fixed the issue for me.

**Comment by t1a2l** [comment]
I am getting the same error, i use pupeeter 11.0.0 on windows and get the "Error: net::ERR_CONNECTION_REFUSED"
when using "await page.goto(`http://127.0.0.1:3030/app.html`);"

**Comment by GabrielDantasDs** [comment]
@travisk-codes thxxx, i was get the same problem
