### ISSUE TITLE
whats the difference between 1.6.0 and 1.5.0

### ISSUE THREAD

**Issue by UltramanZHY** [puppeteer/puppeteer#2903]
we are using puppeteer@1.5.0 for developing. after the npm install in the production environment, our version of puppeteer upgrade to 1.6.0 and some code cant work. is there some documents about the version change?

**Comment by aslushnikov** [comment]
All the changes are documented in our Release Notes: https://github.com/GoogleChrome/puppeteer/releases/tag/v1.6.0

There should be no breaking changes when migrating between v1.5.0 and v1.6.0. What exactly broke?
