### ISSUE TITLE
Referencing object property inside custom await page.waitFor()?

### ISSUE THREAD

**Issue by saadahmad03** [puppeteer/puppeteer#2906]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: macOS Sierra 10.12.6
* URLs (if applicable):
* Node.js version: 8.11.3

Hi I am trying to reference a property off of an object I created in a separate file inside a custom `await page.waitFor()` but it doesn't seem to work as expected. 

```
// selectors.js file

const loginSelectors = {
  email: '#email',
  password: '#password',
  loginButton: '.login-button'
};

module.exports = { loginSelectors };
```
----------------------------------------------
```
// tests.js file

const puppeteer = require('puppeteer');
const { loginSelectors } = require('./selectors');

await page.waitForSelector(loginSelectors.email);
await page.click(loginSelectors.email);
await page.type(loginSelectors.email, 'test@gmail.com');

await page.waitForSelector(loginSelectors.password);
await page.click(loginSelectors.password);
await page.type(loginSelectors.password, 'test123');

await page.waitForSelector(loginSelectors.loginButton);
await page.click(loginSelectors.loginButton);

// ** This is the line in question, wait for login button to be removed from DOM and then continue **
await page.waitFor(() => !document.querySelector(loginSelectors.loginButton));

```

**Works the way I want it to**:
```
await page.waitFor(() => !document.querySelector('.login-button'));
```
**Doesn't work (the way I currently have in my test)**:
```
await page.waitFor(() => !document.querySelector(loginSelectors.loginButton));
```
Any ideas why `loginSelectors.loginButton` used above wouldn't work when its value is the same as the case that works? Any insight appreciated, thanks so much!

**Comment by aslushnikov** [comment]
@saadahmad03 in puppeteer, certain functions are executed inside node.js, and certain are carried over and executed inside the page. The function that you pass as an argument to `page.waitFor` is executed inside a browser.

Now, you define login selectors in node.js and try to use them inside a function that's executed inside a browser - that won't work. For this to work, you'd need to pass selector explicitly:

```js
await page.waitFor(selector => !document.querySelector(selector), loginSelectors.loginButton);
```

In Puppeteer API, those functions that are executed inside the page are called `pageFunction`. Notice the argument name for the [`page.waitForFunction(pageFunction)`](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-pagewaitforfunctionpagefunction-options-args)

Hope this helps!

**Comment by saadahmad03** [comment]
@aslushnikov thanks so much for your answer! makes sense now. 

just for my knowledge, in the example you posted above:

`await page.waitFor(selector => !document.querySelector(selector), loginSelectors.loginButton);`

by passing `loginSelectors.loginButton` at the end like you did after `!document.querySelector(selector),`

does that set the `selector` value here: `await page.waitFor(selector =>` 

to be whatever the value is of `loginSelectors.loginButton`? sorry for clarification, still a little new to this :)

**Comment by aslushnikov** [comment]
> does that set the selector value here: await page.waitFor(selector => to be whatever the value is of loginSelectors.loginButton?

@saadahmad03 yes, exactly! that's how you pass objects from node.js context to browser context.

**Comment by saadahmad03** [comment]
@aslushnikov amazing. thanks so much for the help!!

**Comment by saadahmad03** [comment]
@aslushnikov I'm sorry to bother, using the above examples that you provided I was able to get my code to work just the same so thank you for that :) 

However, when I was trying to do this in a different part of my code:

```
await page.waitFor(
        selector => document.querySelector(selector).style.opacity === '1',
        myAppSelectors.continueButton
      );
```

It does not work as I expected, but this does:

```
 await page.waitFor(
        () => document.querySelector('.continue-button').style.opacity === '1'
      );
```
**Note:** Value of `myAppSelectors.continueButton` = `'.continue-button'`

Any ideas why?

**Comment by aslushnikov** [comment]
@saadahmad03 Oops my bad, you should pass an empty options object there before arguments.
The right way (notice the `{}` as the second parameter)
```js
await page.waitFor(selector => !document.querySelector(selector), {}, loginSelectors.loginButton);
```

I've expanded on this in docs, it should land soon: https://github.com/GoogleChrome/puppeteer/pull/2921

**Comment by saadahmad03** [comment]
@aslushnikov thanks so much! that seems to have resolved the problem. What was it about not including the `{}` as the second parameter that would cause it not to work for the particular example I posted above?

**Comment by aslushnikov** [comment]
@saadahmad03 by default, second parameter is considered to be an options object rather than an argument to be passed into the predicate.
