### ISSUE TITLE
Video Playback Fails

### ISSUE THREAD

**Issue by benjamingr** [puppeteer/puppeteer#291]
Video playback does not work with puppeteer.

Sample code:

```js
const browser = await puppeteer.launch({headless: false}); // reproduces with headless: true too
const page = await browser.newPage();
await page.goto('https://video-dev.github.io/hls.js/demo/');
```

Expected result: big buck bunny plays at `https://video-dev.github.io/hls.js/demo/`
Result: no video playback with the error: 

> your Browser does not support MediaSourceExtension / MP4 mediasource toggle playback controls

**Comment by Garbee** [comment]
I think is is because the MP4 codec is under a paid license fee. Which means it isn't distributed with Chromium but only within Google Chrome.

**Comment by aslushnikov** [comment]
mp4 is missing in chromium: https://www.chromium.org/audio-video

**Comment by Garbee** [comment]
https://www.quirksmode.org/html5/tests/video.html  as well to test. MP4 fails, but OGG Theora and WebM both play fine with Chromium.

**Comment by benjamingr** [comment]
Thanks for the amazingly fast response!

I'll resolve this by using Chrome instead as suggested in https://github.com/GoogleChrome/puppeteer/issues/288

**Comment by Garbee** [comment]
You'd need to be on Chrome Canary to get accurate enough runnings at this point. Puppeteer relies on some bleeding-edge changes on Chromium internally. Which have yet to get out to even Dev Channel. So while Chrome may work, it isn't currently guaranteed to work.

**Comment by benjamingr** [comment]
Thanks, that's probably something you're going to want to document.

**Comment by Garbee** [comment]
It's noted under the [installation section](https://github.com/GoogleChrome/puppeteer#installation) of the README.
