### ISSUE TITLE
New tab with Basic Authentication not added to browser.pages()

### ISSUE THREAD

**Issue by notan3xit** [puppeteer/puppeteer#2912]
I have the situation that the website under test opens a link in a new tab. This tab is protected by Basic Authentication. Thus, in the new tab, a browser dialogue appears and asks for username/password, before the page is loaded.

**Environment**

* Puppeteer version: 1.5.0

**What steps will reproduce the problem?**

```
await page.click('#my-button')
await page.waitFor(5000) // wait for the new tab to open

pages = await browser.pages()
page = pages[pages.length - 1]
console.log("Last opened page: " + page.url())

page.authenticate({ username: 'USER', password: 'pass' })
```

**What is the expected result?**

* `page` is the newly opened tab
* `page.authenticate()` performs the Basic Authentication in the new tab

**What happens instead?**

* `page` is the current page; the new tab is not added
* cannot use `authenticate()` on the new tab, because I have no way of obtaining the reference

**Comment by regmish** [comment]
+1

After opening new tab, browser.pages still doesn't update the last opened pages
```javascript
    searchBtn.click();
    page.waitFor(3000);
    const pages = await browser.pages();
    for (const p of pages) {
      console.log('p.url() :', await p.url());
    }

**Comment by regmish** [comment]
I found an workaround using `waitForTarget`
```javascript
const link = await page.$('selector')
await link.click()    // at this time, a new page was successful opened in a new tab in chromium
//waits until the target is available [see browser.targests]
const newPage = await browser.waitForTarget(target => target.ur() === link.textContent());

// get all pages
pages = await browser.pages()
for (const page of pages) {
    console.log(page.url())   // new page now appear!
}
