### ISSUE TITLE
black element background in the screenshots 

### ISSUE THREAD

**Issue by luo-jieming** [puppeteer/puppeteer#2914]
* Puppeteer version:1.6.0
* Platform / OS version:Centos 7
* Node.js version:10.6.0

I open the H5 games created by  the engine of Laya or Cocos  with puppeteer and screenshot them,always found that the png images rendered with black background.The engin possible have used webgl. 

Expected result:
![image](https://user-images.githubusercontent.com/7901464/42938225-20f497d6-8b84-11e8-9056-86c8ed535bb4.png)

Happened:
![image](https://user-images.githubusercontent.com/7901464/42938249-3a75b118-8b84-11e8-9483-dff80304ac0d.png)

**Comment by aslushnikov** [comment]
@shellar1990 can you please try installing `puppeteer@next` and see if it helps? We've just landed a patch that enables GPU in headless chrome on Linux.

**Comment by luo-jieming** [comment]
@aslushnikov 
then I got this:
![image](https://user-images.githubusercontent.com/7901464/42981441-b353ebe2-8c0e-11e8-8eb3-659a5c31b2d7.png)

It seems the same result.

**Comment by aslushnikov** [comment]
@shellar1990 it turned out our puppeteer@next is not up-to-date (see #2925). Instead, can you please try launching your browser like this:

```js
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      '--headless',
      '--hide-scrollbars',
      '--mute-audio'
    ]
  });
```

This will cause headless mode with GPU enabled.

**Comment by luo-jieming** [comment]
It doesn't work, too,I have to add the arg of '--no-sandbox',then I get the same result with the args:
```
{
    headless: false,
    args: [
      '--headless',
      '--hide-scrollbars',
      '--mute-audio',
      '--no-sandbox'
    ]
  }
```

**Comment by luo-jieming** [comment]
After upgrading Puppeteer to v1.6.1，the problem is solved.Thanks very much.
