### ISSUE TITLE
Send image without saving?

### ISSUE THREAD

**Issue by impulserevs** [puppeteer/puppeteer#2915]
Ok so im using puppeteer to get images from a site. Now with puppeteer im using discord.js which i use for discord bots. Now my question is that, it takes long time (around 3000ms) to get the image and sent to discord. With puppeteer is it possible for me to send the image directly instead of saving it first?

The code that send the image to discord is: `message.channel.send({files:["somefile.png"]})`

but instead of fetching the"somefile.png" from directory, possibly send it without saving it first?

* Puppeteer version: 1.6.0
* Platform / OS version: windows 10
* URLs (if applicable):
* Node.js version: 5.6.0

**Comment by aslushnikov** [comment]
@impulserevs do I understand correctly that you have an image on the website that you want to obtain in the node.js context?

**Comment by impulserevs** [comment]
I'm taking a screenshot of a html page which then is saved from node.js using the puppeteer lib. Its saved on the disk. What I'm trying to ask is that is there a way to take a screenshot and send the image right away (not saving to disk first) but to discord using the command I specified at the top. So the process is this. Take screenshot-> get screenshot-> send to discord right away without saving to disk first. This is mostly cause when a command for eg. !pic is executed in discord the current process of saving the image and then sending to discord is taking too long. And I want a fast command response. If there are other ways that would be great as well.

**Comment by aslushnikov** [comment]
@impulserevs [`page.screenshot`](https://pptr.dev/#?product=Puppeteer&version=v1.6.0&show=api-pagescreenshotoptions) returns a buffer that contains a screenshot. No need to save it to file.

**Comment by impulserevs** [comment]
Ah okay that will work great then. May I know how to improve speeds? Like taking the screenshot and getting results

**Comment by aslushnikov** [comment]
> May I know how to improve speeds?

I don't think there are any low-hanging fruits here. The `page.screenshot` does take some time and it's hard to make it faster. 

One opportunity might be in tweaking your environment. I see you use win 10 - I'd try switching to linux to see if it helps in any way. Especially given that we've just enabled GPU for linux headless - you can try the tip-of-tree version of Puppeteer by installing `puppeteer@next`.

Hope this helps
