### ISSUE TITLE
Support of full HTML headers and footers

### ISSUE THREAD

**Issue by olivierr91** [puppeteer/puppeteer#2916]
We are using Puppeteer as the middleware of jsreport rendering and Chrome, mainly for rendering reports. We are switching from PhantomPDF to Chrome, but unlike PhantomPDF, Puppeteer does not support HTML headers and footers, which is extremely limitating for using Puppteer as the rendering engine for reports, which is 99% of our use cases. We should be able to put basic HTML in the header and footer, basic as in more complex than a single line of text but enough to have things like a logo at the left, a title and some info on the right.

I do not have enough understanding of Puppeteer to know how it handles the header and footer rendering. Is it rendered by Chrome? Is it rendered by Puppeteer itself? The latter would explain the issues it is currently having. PDF composition or such could be used to compose the main content with the header and footer, while having everything rendered by Chrome.

Please see issues discussed here:

- https://github.com/GoogleChrome/puppeteer/issues/2388
- https://github.com/jsreport/jsreport-chrome-pdf/issues/15

**Comment by aslushnikov** [comment]
> I do not have enough understanding of Puppeteer to know how it handles the header and footer rendering. Is it rendered by Chrome? Is it rendered by Puppeteer itself?

@orobert91 All PDF handling is done in Chrome.

> Puppeteer does not support HTML headers and footers

There are some limitations in `headerTemplate` and `footerTemplate`:
- javascript is not executed (#2167)
- external resources aren't loaded

However, if you inline all styles with `<style>` and use base64 for images, it should work.
Can you share a simple pptr script that doesn't do what you want?

**Comment by olivierr91** [comment]
I am not sure what is a pptr script, I use jsreport, which under the hood probably generates a pptr script. But here is a sample simple header that does not work:

```
<html>
<head>
    <style>
        body {
            font-family: "Arial";
            font-size: 7px;
            font-weight: normal;
        }

        .page-header {
            color: blue;
        }

        .left {
            float: left;
        }

        .right {
            float: right;
        }
    </style>
</head>
<body>
    <div class="page-header">
        <div class="left">Left</div>
        <div class="right">Right</div>
    </div>
</body>
</html>
```

`color` works, `font-size` and `float` have no effect, whereas it is working in PhantomPDF and in Chrome browser http://jsfiddle.net/7m9bt5du/

**Comment by olivierr91** [comment]
Please note that the issue has also been filed in jsreport GitHub (https://github.com/jsreport/jsreport-chrome-pdf/issues/15) as I am not sure which framework the bug lies in.

**Comment by sujaykakkad** [comment]
Hi how can I load external fonts in pdf header without installing font.

**Comment by aledoroshenko** [comment]
As i understand, you are able to use only fonts installed in the system? Saying, i can load some google font in body of document, but in footers and headers i can use it only in style tag, and Chromium will try to get it from host system?

**Comment by millerick** [comment]
I don't understand why we are prevented from loading external resources for the header and footer when this was functionality supported by libraries built off of phantomjs.

**Comment by user14045** [comment]
@aslushnikov hello, I just use this lib. You said that "external resources aren't loaded", then what if I want to use google font for the footer? I've try to download locally and put the file in public folder, then import it but not working. Also have tried to put the online url in the src and still not working. Other styling is fine, such as color and font-weight. But, not for font-style. Please, any workaround or sample codes? Thank you in advance

**Comment by Peque** [comment]
I guess the OP could reopen this? (ping @olivierr91) :blush:
