### ISSUE TITLE
puppeteer.launch does not resolve with chrome app startup

### ISSUE THREAD

**Issue by tejohnso** [puppeteer/puppeteer#2919]
### Steps to reproduce

* Puppeteer version: 1.6.0
* Platform / OS version: Linux 4.17.6
* URLs (if applicable):
* Node.js version: 10.6.0

**What steps will reproduce the problem?**

1. Remove the --disable-extensions startup flag
2. Start with --app-id=[chrome app's appId]
3. Call puppeteer.launch

**What is the expected result?**
The returned promise resolves with a `browser` instance.

**What happens instead?**
The promise never resolves

**Comment by aslushnikov** [comment]
So where do I get app-id from? Can you please attach some dummy app-id that doesn't work for you?
