### ISSUE TITLE
Create a way to be able to link to the latest API docs

### ISSUE THREAD

**Issue by kaycebasques** [puppeteer/puppeteer#2920]
Just had a situation in the Lighthouse docs where I wanted to link to a specific section of the Puppeteer API reference docs.

The problem with the current setup is that it links me to a specific version of the API docs.

For example: https://github.com/GoogleChrome/puppeteer/blob/v1.6.0/docs/api.md#pagecoverage

Note the `v1.6.0` part of the URL. Ideally, we'd have some kind of alias to the latest docs, so that my links are always up-to-date.

**Comment by kaycebasques** [comment]
Oh right, just remembered about `master`. Replacing the version part with `master` links to tip-of-tree.

Ideally, we'd have a way to link the latest release, but this is probably good enough.

**Comment by aslushnikov** [comment]
@kaycebasques https://pptr.dev is also quite handy for links.

**Comment by kaycebasques** [comment]
That is nice. Forgot that you shipped that site. Thanks.
