### ISSUE TITLE
Error: Protocol error (Runtime.addBinding): 'Runtime.addBinding' wasn't found

### ISSUE THREAD

**Issue by james-maloney** [puppeteer/puppeteer#2922]
### Steps to reproduce

**Tell us about your environment:**

Running on Docker node:10.6.0

* Puppeteer version: 1.6.0
* Platform / OS version: MacOS
* URLs (if applicable):
* Node.js version: 10.6.0

**What steps will reproduce the problem?**

My application is fairly large, if this is not enough info I can try to write a reduced test case in a couple of days

This is where I think the error occurs in my code.

```
utils.listenFor = (name, page, es) => {
	// listen for stats
	page.exposeFunction(`on${name}`, (e) => {
		es.stat(e.detail);
	});

	page.evaluateOnNewDocument((n) => {
		document.addEventListener(n, (e) => { // eslint-disable-line
			window[`on${n}`]({ type: n, detail: e.detail });// eslint-disable-line
		});
	}, name);
};
```

**What is the expected result?**

Not to have an unhandled promise.

**What happens instead?**

```
UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.addBinding): 'Runtime.addBinding' wasn't found
     at Promise (/node_modules/puppeteer/lib/Connection.js:202:56)
     at new Promise (<anonymous>)
     at CDPSession.send (/node_modules/puppeteer/lib/Connection.js:201:12)
     at Page.exposeFunction (/node_modules/puppeteer/lib/Page.js:391:24)
```

This error does not occur in version 1.5.0

**Comment by aslushnikov** [comment]
@james-maloney do you use v1.6.0 with a custom chromium version?

**Comment by james-maloney** [comment]
I'm using stable Chrome.

**Comment by aslushnikov** [comment]
@james-maloney please use pptr v1.3.0 with current stable. 

Read our FAQ entry [Q: Why doesn’t Puppeteer v.XXX work with Chromium v.YYY?](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy) for details.

**Comment by james-maloney** [comment]
@aslushnikov thanks for the input and resource.
