### ISSUE TITLE
Linux: Error: Failed to launch chrome! (Syntax error: "|" unexpected)

### ISSUE THREAD

**Issue by adilu** [puppeteer/puppeteer#2924]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.6.0
* Platform / OS version: Linux (both on Raspberry Pi "Raspbian GNU/Linux 8" and on Synology "Debian GNU/Linux 8")
* Node.js version: v8.9.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `npm i puppeteer`

2. Run a node file containing only bare minimum, e.g.:
`const puppeteer = require('puppeteer');`
`puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});`

3. May be it's a dependency problem? However:
`ldd node_modules/puppeteer/.local-chromium/linux-571375/chrome-linux/chrome | grep not`
yields `not a dynamic executable`

**What is the expected result?**
Puppeteer should launch. Works without a problem on Windows.

**What happens instead?**
` Error: Failed to launch chrome!
node_modules/puppeteer/.local-chromium/linux-571375/chrome-linux/chrome: Syntax error: "|" unexpected`

**Comment by aslushnikov** [comment]
@adilu Did you try launching `node_modules/puppeteer/.local-chromium/linux-571375/chrome-linux/chrome` manually? Does it work for you?

**Comment by adilu** [comment]
Thank you for looking into my issue.

I tried launching Chrome manually. When I run...
`sudo ./chrome` or `sudo ./chrome --help` in the mentioned directory, I get the same error:
`./chrome: Syntax error: "|" unexpected`

I also made sure that all dependencies listed in #290 are installed and up to date.

**Comment by aslushnikov** [comment]
@adilu Do you try to run on Raspberry Pi? This one doesn't supported unfortunately - see #550.

**Comment by adilu** [comment]
@aslushnikov Thank you. No, the main target would have been a Synology Diskstation. However, the CPU architecture there is also ARMv7, so it is probably the same incompability as on a Raspberry Pi, as you mentioned.

**Comment by aslushnikov** [comment]
> so it is probably the same incompability as on a Raspberry Pi, as you mentioned.

Yeah that's right. We don't have arm build atm. Sorry for the inconvenience!

**Comment by mdimai666** [comment]
I was able to run on rpi4 raspbian lite
try: 
```bash
sudo apt install chromium-browser chromium-codecs-ffmpeg
```

```js
const browser = await puppeteer.launch({
          headless: true,
          executablePath: '/usr/bin/chromium-browser',
          args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
```
p.s. for future

**Comment by samleemc** [comment]
@mdimai666 's solution fix for my reabperry pi 4

**Comment by willmaraujo** [comment]
> I was able to run on rpi4 raspbian lite try:
> 
> ```shell
> sudo apt install chromium-browser chromium-codecs-ffmpeg
> ```
> 
> ```js
> const browser = await puppeteer.launch({
>           headless: true,
>           executablePath: '/usr/bin/chromium-browser',
>           args: ['--no-sandbox', '--disable-setuid-sandbox']
>   });
> ```
> 
> p.s. for future

it worked, thanks!

**Comment by nezort11** [comment]
In 2023 for Raspberry Pi 4 this worked:

```sh
sudo apt update
sudo apt install chromium
```

```js
const browser = await puppeteer.launch({
    headless: true,
    executablePath: '/usr/bin/chromium',
    args: ['--no-sandbox', '--disable-setuid-sandbox']
});
```

**Comment by tmkasun** [comment]
> ```shell
> sudo apt update
> ```

I'm using Ubuntu 20 and this didn't work. Got the following error 
```
E: Package 'chromium' has no installation candidate

```
