### ISSUE TITLE
puppeteer@next is not autoupdated

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#2925]
[Recent eslint hack](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes) caused all NPM keys to be invalidated. This broke our puppeteer@next self-deployment through travis-ci.

**Comment by aslushnikov** [comment]
Ok, this didn't work.

**Comment by aslushnikov** [comment]
no luck!

**Comment by aslushnikov** [comment]
It works!

**Comment by ntzm** [comment]
I think this is still a little broken, the latest commit d54c7edeae44800dabb87e52ae96180a16a149a1 isn't on next

**Comment by aslushnikov** [comment]
@ntzm crazy. Indeed.
