### ISSUE TITLE
Header and footer not showing on first page

### ISSUE THREAD

**Issue by pifragile** [puppeteer/puppeteer#2926]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: 1.6.0
* Platform / OS version: Ubuntu 16.04
* Node.js version: 9.9.0

**What steps will reproduce the problem?**
create a multi-page pdf with ```displayHeaderFooter: true```.

**What is the expected result?**
header and footer should be displayed on every page

**What happens instead?**
header and footer not displayed on the first page

any advise? is there some option to change this? thanks a lot!

**Comment by pifragile** [comment]
found the solution already, you dont only need page margins in the puppeteer options but also in the css of the page..

**Comment by HelloLangYaJun** [comment]
Could you be more specific?I just need your error example, I need the cover not to show the header and footer, but I can't.

**Comment by Superlukec** [comment]
You can fix this problem without options, you only need to use CSS rules for page:

```
@page {
  size: A4 portait;
  margin-left: 40px;
  margin-right: 40px;
  margin-top: 60px;
  margin-bottom: 60px;
}
```

The size of the margin-top and margin-bottom must be enough to fit header and footer inside. In my case I have footer and header with height 40px.
