### ISSUE TITLE
Bad font rendering on Linux

### ISSUE THREAD

**Issue by slyrz** [puppeteer/puppeteer#2927]
**Tell us about your environment:**

* Puppeteer version: 1.6.0
* Platform / OS version: Ubuntu 16.04 LTS

Just to let you know, 1.6.0 is pinned to a Chromium version with broken font rendering on Linux,
so screenshots for Linux users might look bad.

I think this was caused by a [fontconfig update](https://chromium.googlesource.com/chromium/src/+/a0c1584a2fade0146b7cd3380abe42feda02ad7c) and was eventually fixed in [this commit](https://chromium.googlesource.com/chromium/src.git/+/3ff47e60c5ce645973e57fc8dbe88b43d63edaf4). This should give you the timespan of "broken" Chromium builds.

For comparison:

- Revision 574897 (currently pinned)
![news ycombinator com_ 1](https://user-images.githubusercontent.com/6135391/42999787-5f2b5f1c-8c1f-11e8-9c30-b708706d427c.png)

- Revision 576827 (latest build)
![news ycombinator com_ 2](https://user-images.githubusercontent.com/6135391/42999788-5f487138-8c1f-11e8-999c-e90920e64e3f.png)

**Comment by MrTurnRight** [comment]
can i use 'npm update' to fix this bug?
i dont know how to fix it

**Comment by slyrz** [comment]
So far the published version hasn't changed. You can work around this by using the BrowserFetcher to run a different Chromium revision:

```javascript
const browserFetcher = puppeteer.createBrowserFetcher();
const revisionInfo = await browserFetcher.download('576827');
const browser = await puppeteer.launch({ executablePath: revisionInfo.executablePath })
```

**Comment by aslushnikov** [comment]
Thanks @slyrz for the workaround. We'll push an updated 1.6.1 shortly.

**Comment by aslushnikov** [comment]
For the record: upstream bug for this is https://crbug.com/857511

**Comment by aslushnikov** [comment]
Puppeteer v1.6.1 is live with an updated chromium revision to address this bug.

https://github.com/GoogleChrome/puppeteer/releases/tag/v1.6.1

**Comment by MrTurnRight** [comment]
![qq 20180726102048](https://user-images.githubusercontent.com/7369399/43238091-3b721152-90bf-11e8-8321-c01a510551a8.png) Chinese Rendering
i still got the wrong result with version "puppeteer": "^1.6.1", '.local-chromium/linux-575458/ '

**Comment by aslushnikov** [comment]
@MrTurnRight I don't think this is related; there are quite a few reports with various solutions regarding Chinese fonts: https://github.com/GoogleChrome/puppeteer/issues?q=is%3Aissue+Chinese+is%3Aclosed

**Comment by MrTurnRight** [comment]
thank you , i found the solution. im so sorry.

**Comment by Tusko** [comment]
@MrMitch how did you fix it?

**Comment by MrMitch** [comment]
@Tusko I think you meant to mention @MrTurnRight and not me ;)

**Comment by WeihanLi** [comment]
> thank you , i found the solution. im so sorry.

@MrTurnRight , could you please share your solution? Thanks
