### ISSUE TITLE
Screenshot cuts off footer of the page

### ISSUE THREAD

**Issue by petarthewizard** [puppeteer/puppeteer#2935]
### Steps to reproduce

install pupputeer-screenshots npm package and create file with this:

`require('puppeteer-screenshots').init();`

then run the following command:

`node puppeteer-screehots-init.js --url=http://bbc.com --mobile=true --userAgent="Mozilla/5.0%20(Linux;%20Android%205.1;%20XT1039%20Build/LPBS23.13-17.6-1)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/60.0.3112.116%20Mobile%20Safari/537.36"`

this will create a file image.png which a screenshot of the BBC website but the footer should cut off/not fully there. Any ideas?

* Puppeteer version: 1.6.0
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable): http://bbc.com
* Node.js version: 8.7.0

**What is the expected result?**
Full page screenshot

**What happens instead?**
Partial screenshot

**Comment by RamakrishnaChilaka** [comment]
Any update ?

**Comment by mathiasbynens** [comment]
Try Puppeteer v2.0.0: https://github.com/GoogleChrome/puppeteer/releases/tag/v2.0.0 Also see #5080.
