### ISSUE TITLE
Runtime.evaluate document.querySelector vs DOM.querySelector?

### ISSUE THREAD

**Issue by carloabelli** [puppeteer/puppeteer#2936]
Within puppeteer it seems for many requests, running local JavaScript through `Runtime.evaluate` is preferred to direct CDP requests. For instance, `ElementHandle.$` is implemented by running `document.querySelector` through `Runtime.evaluate` CDP requests rather than using the `DOM.querySelector` request directly. What was the rationale behind this decision? Wouldn't it make more sense to use the native CDP requests?

**Comment by aslushnikov** [comment]
> What was the rationale behind this decision? Wouldn't it make more sense to use the native CDP requests?

@carloabelli this is for performance reasons: `DOM` domain is quite heavy both computationally and memory wise, mainly because it was implemented to address debugging goals rather than automation goals.

Hope this helps.

**Comment by carloabelli** [comment]
Thanks!
