### ISSUE TITLE
Environment variable to choose chromium platform

### ISSUE THREAD

**Issue by farumi** [puppeteer/puppeteer#2947]
Hello,

Could you add an environment variable to choose the chromium platform to download at installation time?

In my case, our CI/CD machine runs under linux, but the artifacts that it generates are supposed to be deployed on windows machines. These artifacts contain puppeteer: Because puppeteer is installed under the linux machine, the chromium binary is linux, while the machine that is supposed to run it is windows. Then, when executing this artifact on the windows machine, it complains it cannot find the 'local' binary. We want to have a full running installation in a single zip file.

Could you simply add something like that in `install.js` file?

```diff
const downloadHost = process.env.PUPPETEER_DOWNLOAD_HOST || process.env.npm_config_puppeteer_download_host;

const puppeteer = require('./index');
- const browserFetcher = puppeteer.createBrowserFetcher({ host: downloadHost });
+ const browserFetcher = puppeteer.createBrowserFetcher({ host: downloadHost, platform: process.env.PUPPETEER_CHROMIUM_PLATFORM });

const revision = process.env.PUPPETEER_CHROMIUM_REVISION || process.env.npm_config_puppeteer_chromium_revision
  || require('./package.json').puppeteer.chromium_revision;

const revisionInfo = browserFetcher.revisionInfo(revision);
```
If the variable is not set, `BrowserFetcher` will take the local platform, as done until now.

FYI, currently I'm doing the following workaround

```bash
$ set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
$ npm install --production  # It will not install Chromium because PUPPETEER_SKIP_CHROMIUM_DOWNLOAD is set
$ unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
$ sed -i -- "s/host: downloadHost/host: downloadHost, platform: 'win64'/" node_modules/puppeteer/install.js
$ node node_modules/puppeteer/install.js # Chromium will be installed with platform 'win64'
```

**Comment by aslushnikov** [comment]
@farumi This was one of the main usecases for the [`BrowserFetcher`](https://pptr.dev/#?product=Puppeteer&version=v1.6.1&show=api-class-browserfetcher) API.

The suggested way is:
- use `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` to avoid puppeteer's download
- come up with a custom node script that would use [`BrowserFetcher`](https://pptr.dev/#?product=Puppeteer&version=v1.6.1&show=api-class-browserfetcher) to download the version you're interested in

Will this work for you?

**Comment by farumi** [comment]
@aslushnikov Thank you very much for your answer

Now that you say it, I remember saw this answer in another issue, but at the time I've found it a bit obscure. Now, after playing a bit with the code seems clearer for me.

But anyway, won't be easier to just define the environment variable I'm proposing? It is completely transparent for people not using it. It goes in the same direction of PUPPETEER_CHROMIUM_REVISION, where you can choose your revision. Why don't choose the platform, if you wish?

Thank you again for your comment, if you think doesn't worth to add it, I'll change my ugly workaround by some proper use of `BrowserFetcher`.

Regards,
Ferran

**Comment by aslushnikov** [comment]
> But anyway, won't be easier to just define the environment variable I'm proposing? It is completely transparent for people not using it. It goes in the same direction of PUPPETEER_CHROMIUM_REVISION, where you can choose your revision. Why don't choose the platform, if you wish?

@farumi we can't add every single thing to the library since it'll eventually become unmanageable. Instead, we add only highly demanded features.

This issue looks quite specific to the deployment process and there's a decent workaround, so I don't think it's worth adding another env variable to address this usecase.

Hope this helps!
