### ISSUE TITLE
Does Puppeteer support Page Object Model

### ISSUE THREAD

**Issue by MadHatter122312** [puppeteer/puppeteer#2949]
* Puppeteer version: 1.2.0
* Platform / OS version: macOS Sierra 10.12.6
* URLs (if applicable): N/A
* Node.js version: 8.9.4

I was reading though the documentation and looking at examples of various puppeteer scripts and it seems that everyone is creating a single script file for their e2e tests.  But, what is the correct approach (best practice) when writing scripts for large single page applications?  

With Protractor, for example, we use to implement Page Object Model, where we moved our element locators into different files and imported them into our main script.  A POM with locators would look something like this: 

```
`import { browser, $ , $$ , ElementFinder} from 'protractor';

export class BalancesPage {
    public pageTitle;
    public accountInput: ElementFinder;
    public submitButton: ElementFinder;
    /**
     * naviages to the input url passed and
     * sets the page object properties
     *
     */
    navigateTo (url: string, timeout?: number): any {
       return browser.get(url , timeout);
    }
    initPageProperties() {
        this.pageTitle = browser.getTitle();
        this.accountInput = $('input');
        this.submitButton = $('button');
    }
    /**
     * retuns the elementfinder balances
     */
    getBalances(): ElementFinder {
        return $('balances-summary');
    }
    /**
     * retuns the elementfinder balances-details
     */
    getBalancesDetails(): ElementFinder {
        return $('balances-details');
    }
}`
```

This Page object would be imported via `import` into the spec file, and then instantiated in the script. 

What is the proper way to do this in Puppeteer?  Is there any example of the proper implementation of POM in a single-page application that I can reference?

**Comment by aslushnikov** [comment]
> But, what is the correct approach (best practice) when writing scripts for large single page applications?

@MadHatter122312 I think you've already asked this question half a year ago: https://github.com/GoogleChrome/puppeteer/issues/1782
Does the answer help?

> Is there any example of the proper implementation of POM in a single-page application that I can reference?

Unfortunately, I'm not aware of any. However, there are many resources on the web regarding testing with Puppeteer.
