### ISSUE TITLE
Expose the Accessibility Tree for inspection

### ISSUE THREAD

**Issue by jessebeach** [puppeteer/puppeteer#295]
Chrome builds an Accessibility Tree that it exposes to platform accessibility APIs. 

chrome://accessibility/

Accessibility integration testing tools are compelled to use the DOM as a medium and to infer what the AX Tree *would* be in order to raise issues. 

If we had direct access to the AX Tree, we could right tests that are exact without the guesswork of how we expect Chrome to transform DOM into AX.

This would probably require an extension to [DOMSnaptshot](https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot/) or the introduction of **AXSnapshot** to the Devtools protocol.

**Comment by paulirish** [comment]
hey @jessebeach! [`Accessibility.getPartialAXTree`](https://chromedevtools.github.io/devtools-protocol/tot/Accessibility/#method-getPartialAXTree) is what's used under the hood by part of the new accessibility tools in the DevTools elements panel:
![image](https://user-images.githubusercontent.com/39191/29379342-fc33a2c8-8276-11e7-945a-0642353dd576.png)


This is buildable now against the raw protocol, using chrome-remote-interface. But you could experiment with a fork of puppeteer as well.

**Comment by aslushnikov** [comment]
@JoelEinbinder was also interested in exposing AX tree in puppeteer

**Comment by jessebeach** [comment]
@paulirish [Accessibility.getPartialAXTree](https://chromedevtools.github.io/devtools-protocol/tot/Accessibility/#method-getPartialAXTree) is probably exactly what I need. I hadn't noticed it in the protocol. Thank you for pointing it out!

In fact, I think we can close this ticket for now until I've determined what exactly would be needed in addition. It's a vague ask otherwise given that AXNodes are available through the protocol.

**Comment by Garbee** [comment]
Perhaps we should re-open this as a point of reference for a documentation improvement? This is incredibly useful feedback that isn't obvious up front. A solid example on getting the a11y tree would benefit anyone looking into this kind of tooling.

**Comment by paulirish** [comment]
@Garbee That would involve deciding how to represent a tree, and AXNodes, etc. It's possible there are higher-level questions which we'd implement as method instead of just handing off a large data structure.  I'd also prefer to keep the issue closed until we have a more clear feature request.

@jessebeach feel free to poke around the a11y domain. check out "Sniffing the protocol" on https://chromedevtools.github.io/devtools-protocol/ to see how devtools frontend is doing what it does.
