### ISSUE TITLE
multi-client session resets emulation after cross-process navigation

### ISSUE THREAD

**Issue by Janpot** [puppeteer/puppeteer#2952]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.1  
* Platform / OS version: macOS 10.13.6 
* URLs (if applicable): -
* Node.js version: 10.7.0

**What steps will reproduce the problem?**

```js
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');

function getViewportDimensions () {
  return {
    innerWidth: window.innerWidth,
    innerHeight: window.innerHeight,
    outerWidth: window.outerWidth,
    outerHeight: window.outerHeight,
    devicePixelRatio: window.devicePixelRatio
  };
}

(async () => {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();
  const device = devices['iPhone 6'];
  console.log(device);
  await page.emulate(device);
  await page.target().createCDPSession();
  await page.goto('https://www.google.com/');
  const dimensions = await page.evaluate(getViewportDimensions);
  console.log(dimensions);
  await browser.close();
})();
```

1. Run the above code
2. Remove the line `await page.target().createCDPSession();`
3. Run the code again
4. Add the line back and set `headless` to `false`
5. Run the code again
6. Set `headless` back to `true` and swap line ` await page.target().createCDPSession();` with line ` await page.emulate(device);`
7. Run the code again

**What is the expected result?**

Output is every time:

```js
{ innerWidth: 375,
  innerHeight: 667,
  outerWidth: 375,
  outerHeight: 667,
  devicePixelRatio: 2 }
```

**What happens instead?**

In step 1. output is

```js
{ innerWidth: 375,
  innerHeight: 667,
  outerWidth: 0,
  outerHeight: 0,
  devicePixelRatio: 1 }
```

**Comment by aslushnikov** [comment]
@Janpot This is a bug with our multiclient implementation:  `InspectorEmulationAgent` from the second session resets emulation in it's `Restore` method after cross-process navigation: https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/inspector/inspector_emulation_agent.cc?q=emulationagent+f:blink&dr=CSs&l=30

**Comment by mauricionr** [comment]
any news in this bug?

**Comment by gerathjen** [comment]
I receive an error message **UnhandledPromiseRejectionWarning: TypeError: page.target is not a function**. I followed the instructions in **Steps to reproduce**.

**Comment by Janpot** [comment]
@aslushnikov I can't seem to reproduce with `v1.13.0` anymore.
