### ISSUE TITLE
puppeteer bug fixes -> document.querySelector(selector) not working for date and span tags

### ISSUE THREAD

**Issue by Param-Trivedi** [puppeteer/puppeteer#2953]
### Steps to reproduce

* Puppeteer version: 1.6.0
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: 8.11.3

**What steps will reproduce the problem?**
page.evaluate(() => document.querySelector(selector).textContent) does not give the correct response 
in case of input[type=date] and <span> tags 

**What is the expected result?**
The expected result should be
1. '1986-10-01' for dates P.S.  : I know that .value will give the value for the date but "value" is not defined in puppeteer
  
2. "0 of 0"  

**What happens instead?**
This is the result I get 
1. undefined

2. [object Promise]

This is the error I get
![tempsnip](https://user-images.githubusercontent.com/10596504/43208486-911da098-8ff8-11e8-805d-d13f15bccb11.png)

**Comment by aslushnikov** [comment]
@Natsu009 can you please elaborate? How do I reproduce this?

**Comment by Param-Trivedi** [comment]
`   

    const puppeteer = require('puppeteer');
      (async () => {
          const browser = await puppeteer.launch({
        headless: false,
        slowMo: 250 // slow down by 250ms
      });
    const page = await browser.newPage();
    
    await page.goto('https://v4-alpha.getbootstrap.com/components/forms/');

    await page.click('#example-number-input');
    await page.type('#example-number-input', '43');

    await page.waitForSelector('#example-datetime-local-input');
    const date = page.evaluate(() => document.querySelector('#example-datetime-local- 
     input').innerHTML);

    console.log('The date is : "'+ date + '"');

    await browser.close();
})(); 

`

Try this example it will not give the value of date

**Comment by EstesE** [comment]
Would this work?

```
const date = await page.evaluate(() => document.querySelector('#example-datetime-local-input').value);

```

**Comment by vsemozhetbyt** [comment]
FWIW, if you run this in the browser console, you will also get an empty string, as the element has no children and so no inner HTML.
```
> document.querySelector('#example-datetime-local-input').innerHTML
< ""
> document.querySelector('#example-datetime-local-input').outerHTML
< "<input class="form-control" type="datetime-local" value="2011-08-19T13:45:00" id="example-datetime-local-input">"
```

**Comment by Param-Trivedi** [comment]
@Mithrilhall that actually worked. I don't know why it worked now but that it does and thanks everyone for the help

**Comment by EstesE** [comment]
@Natsu009 Could you close this issue?

**Comment by DJ-Glock** [comment]
> Would this work?
> 
> ```
> const date = await page.evaluate(() => document.querySelector('#example-datetime-local-input').value);
> ```

This approach works, but does not look fine from end user perspective.
For example it will not work if you have a text field (search field) and a search button that is disabled if there is no text was entered. Assigning value to .value attribute will not trigger respective events and search button will not be activated.
