### ISSUE TITLE
is it possible to run puppeteer in Android

### ISSUE THREAD

**Issue by yashwanth2804** [puppeteer/puppeteer#2957]

**Comment by oshliaer** [comment]
Android doesn't support
![screenshot_2018-07-26-15-57-13-859_com termux](https://user-images.githubusercontent.com/5027939/43263922-52555270-90ed-11e8-8eba-a925026c2c82.png)

**Comment by yashwanth2804** [comment]
Thank you, is there any way i can scrap using android just like in pc

**Comment by vsemozhetbyt** [comment]
Not sure, but you can try https://github.com/jsdom/jsdom

**Comment by yashwanth2804** [comment]
thanks it seems i need to rewrite entire logic

**Comment by oshliaer** [comment]
@vsemozhetbyt , thanks!

**Comment by mbande** [comment]
@yashwanth2804 @oshliaer did you find a solution to scrape using android?

**Comment by oshliaer** [comment]
@mbande unfortunately yet.

**Comment by stuartpb** [comment]
Shouldn't it be possible to download the binary for Linux and have it work on Android?

**Comment by beshoo** [comment]
@yashwanth2804 @oshliaer did you find a solution to scrape using android? beside jsdom which is not the complete solution!

**Comment by oshliaer** [comment]
@beshoo 

I gave up and started using the puppeteer on cloud functions.

**Comment by beshoo** [comment]
@oshliaer I just found this :
https://medium.com/@oriharel/how-to-run-javascript-code-in-a-background-service-on-android-8ec1a12ebe92 
what do you think!

**Comment by yashwanth2804** [comment]
@beshoo so in react native can this might be possible i guess

**Comment by AlloryDante** [comment]
Hello, I found a way to run pupeteer in Android, but it's a bit tricky....

Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.


Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.

**Comment by gokaybiz** [comment]
> Hello, I found a way to run pupeteer in Android, but it's a bit tricky....
> 
> Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.
> 
> Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.

 node main.js
(node:26375) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /root/awwm/puppetTest/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/awwm/puppetTest/node_modules/puppeteer/lib/Launcher.js615:20)
    at ChildProcess.<anonymous> (/root/awwm/puppetTest/node_modules/puppetee/lib/Launcher.js:607:71)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:27:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:26375) UnhandledPromiseRejectionWarning: Unhandled promise rejectin. This error originated either by throwing inside of an async function ithout a catch block, or by rejecting a promise which was not handled wih .catch(). To terminate the node process on unhandled pro

**Comment by dwh1121** [comment]
> Hello, I found a way to run pupeteer in Android, but it's a bit tricky....
> 
> Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.
> 
> Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.

Hello cezarlacatus,

Thank you very much for sharing. I want to ask you a few questions.

What version of Ubuntu did you install from AnLinux?
When you installed Pyppeteer, was the command "npm i puppeteer" or "npm i puppeteer-core"?

Looking forward to your reply. Thank you very much!

**Comment by rishabhrpg** [comment]
Hello, after a week of hit & trial I came with a solution to make it work on Android with Termux.
Follow up the  [gist](https://gist.github.com/rishabhrpg/4025ff5da4f0159af1850cb358279e57)
Starting point [repo](https://github.com/rishabhrpg/puppeteer-on-termux) takes a screenshot using puppeteer in termux.

**Comment by fahadali32** [comment]
How to install chromium in alpine i can't install i just run this cmd apk add chromium

**Comment by venky9885** [comment]
Hello, after a week of hit & trial I came with a solution to make it work on Android with Termux.
Follow up the gist
Starting point repo takes a screenshot using puppeteer in termux

[https://gist.github.com/rishabhrpg/4025ff5da4f0159af1850cb358279e57](url)
[https://github.com/rishabhrpg/puppeteer-on-termux](url)

**Comment by md-fahad-ali32** [comment]
> Hello, after a week of hit & trial I came with a solution to make it work on Android with Termux.
> Follow up the gist
> Starting point repo takes a screenshot using puppeteer in termux
> 
> [https://gist.github.com/rishabhrpg/4025ff5da4f0159af1850cb358279e57](url)
> [https://github.com/rishabhrpg/puppeteer-on-termux](url)

Where is gist...?

**Comment by rishabhrpg** [comment]
@sploit30 follow instructions from my repo https://github.com/rishabhrpg/puppeteer-on-termux
it will get you started with puppeteer in android.

**Comment by md-fahad-ali32** [comment]
> Hello, after a week of hit & trial I came with a solution to make it work on Android with Termux.
> Follow up the gist
> Starting point repo takes a screenshot using puppeteer in termux
> 
> [https://gist.github.com/rishabhrpg/4025ff5da4f0159af1850cb358279e57](url)
> [https://github.com/rishabhrpg/puppeteer-on-termux](url)

no chromium found i found this error in alpine linux

**Comment by richardrishabh** [comment]
> > Hello, after a week of hit & trial I came with a solution to make it work on Android with Termux.
> > Follow up the gist
> > Starting point repo takes a screenshot using puppeteer in termux
> > [https://gist.github.com/rishabhrpg/4025ff5da4f0159af1850cb358279e57](url)
> > [https://github.com/rishabhrpg/puppeteer-on-termux](url)
> 
> no chromium found i found this error in alpine linux

As long as you have a 64 bit processor it should work.

**Comment by Vaisakhkm2625** [comment]
Anyone got any solution to run puppeteer without using a container ....

or can we compile source code like that!?

I know it is crazy ....
But it could be really useful right..

Anyone have any thought on this..
or is there any exisisting android app there for web automation on android!?

**Comment by SunPodder** [comment]
I'm just asking why android platform is unsupported? I'm using selenium on Android though.

**Comment by khanyisodev** [comment]
Hi guys, I need someone to assist with automating tasks on Android and iOS, this is a paid gig, if you are interested, contact me at khanyiso@blacstudio.com, use the reference #AV001 on the subject

@AlloryDante @contributorpw
