### ISSUE TITLE
How can I  call the method by the name of method?

### ISSUE THREAD

**Issue by Roger535** [puppeteer/puppeteer#2958]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.6.1
* Platform / OS version: macOS 10.12.6
* URLs (if applicable):
* Node.js version: v8.5.0

**What steps will reproduce the problem?**

In my case，I want call the function by the name of method, but it throws UnhandledPromiseRejectionWarning
`var func = page["goto"] ;
  func(url);
`
or

`var func = page.goto;
  func(url);
`

```
(node:42051) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_networkManager' of undefined
(node:42051) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm a learner of  NODEJS，How can I make it like "page.goto(url)"，Thanks

**What is the expected result?**

I want it work like "page.goto(url)"

**What happens instead?**

(node:42051) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_networkManager' of undefined
(node:42051) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vsemozhetbyt** [comment]
It seems `page.goto()` needs its `this` preserved. You can use binding:
```js
var func = page["goto"].bind(page);
```
See:

[`Function.prototype.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)

[Pitfall: Losing this When Extracting a Method](http://speakingjs.com/es5/ch17.html#_pitfall_losing_this_when_extracting_a_method)
