### ISSUE TITLE
Some phantom tests are flaky on Travis

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#296]
> FAIL: should fail to load an HTTPS webpage with a self-signed certificate

got `assert_equals: expected ("string") "SSL handshake failed" but got ("undefined") undefined` on https://travis-ci.org/GoogleChrome/puppeteer/builds/265264278

> FAIL: can abort network requests
> FAIL: load a page with a downloadable font, once
> FAIL: load a page with a downloadable font, again

 all 3 timeout on https://travis-ci.org/GoogleChrome/puppeteer/builds/265216405

**Comment by aslushnikov** [comment]
Interestingly, didn't happen much on travis-ci.com
