### ISSUE TITLE
Request is never completed

### ISSUE THREAD

**Issue by Menighin** [puppeteer/puppeteer#2960]
### Steps to reproduce

Well, this one is kind harsh to reproduce because it requires authentication.
Basically I'm developing a crawler for the stock broker I use in Brazil.
I am able to login and everything and right now I am trying to get some info through the XHR requests the page is doing. Basically I want to get their response so I can build and use the data. 

The problem is, all of the requests that are useful to me never fire the `response` event. Here is a code as an example:

    const browser = await puppeteer.launch({ headless: true, devtools: false });
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 });
	
    page.on('request', request => {
        if (request.url() === 'https://www.rico.com.vc/api/finance/summary-position/') {
            console.log('request made');
        }
        request.continue();
    });

    page.on('requestfailed', request => {        
        if (request.url().indexOf('summary') !== -1) {
             console.log('request failed');
        }
    });

    page.on('requestfinished', request => {        
        if (request.url().indexOf('summary') !== -1) {
             console.log('request finished');
        }
    });

    page.on('response', response => {
	if (response.url().indexOf('summary') !== -1) {
            console.log('response!')
        }
    });
        
I can see the `request made` message. In fact here it is:

![image](https://user-images.githubusercontent.com/2742763/43289267-d0e249aa-9100-11e8-86a2-37cb41cd83ed.png)

And I also can see, if I run with `headless: false`, that the request is completed:

![image](https://user-images.githubusercontent.com/2742763/43289406-4bdccd60-9101-11e8-9e94-ff4d87784723.png)

But none of the other `console.log()` are fired. What am I missing?

**Tell us about your environment:**

* Puppeteer version: ^1.6.0
* Platform / OS version: Windows 10
* Node.js version: v8.11.2

**What is the expected result?**

Request to be completed so I can get the response.

**What happens instead?**

I can see the request is initiaded but it never completes or fails.

**Comment by aslushnikov** [comment]
@Menighin I wonder if this is related to the #2954. Can you please apply this PR locally and see if it helps?

**Comment by nei** [comment]
@aslushnikov yes #2954 fixes this issue. Thank you for that!
