### ISSUE TITLE
Option to detach chromium on Win32

### ISSUE THREAD

**Issue by oldrich-s** [puppeteer/puppeteer#2962]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Win64
* URLs (if applicable): 
* Node.js version: 10.4.0

**What steps will reproduce the problem?**

Start puppeteer. Close main NodeJS process.

**What is the expected result?**

Option to keep chromium running.

**What happens instead?**

No matter what, chromium closes together with the main process on Win32.

**Background**

I need to have a single chromium running on the server and it shall run independently of the main NodeJS server process. There are running certain tasks that must not be stopped when the main NodeJS server restarts.

When I start server I check if the chromium is already running and if so, I use `puppeteer.connect` to connect to the running chromium, if not I start a new chromium via `puppeteer.launch`. From there on, the chromium shall run independently no matter if NodeJS server restarts or not.

For now, this is not possible because of this line:

https://github.com/GoogleChrome/puppeteer/blob/23706188192ce1f616ae29b50010eb560ca29da9/lib/Launcher.js#L117

PS: I am aware of the fact that the only way to kill chromium will then be e.g. `task manager` but that is no problem ;).

**Comment by aslushnikov** [comment]
I'd recommend keeping both parent node.js process and chrome running in background together.

In other words: consider the node.js script that launches chromium part of the browser and don't close it.

Hope this helps.
