### ISSUE TITLE
Page throws timeout exception only in headless mode

### ISSUE THREAD

**Issue by yadue** [puppeteer/puppeteer#2963]
### Steps to reproduce
**Tell us about your environment:**

* Puppeteer version: puppeteer@1.6.1
* Platform / OS version: macOS High Sierra 10.13.5
* URLs (if applicable): https://www.michaelkors.eu/en_PL/cotton-polo-shirt/_/R-CU85FGVC93?color=2199
* Node.js version: v6.9.0

**What steps will reproduce the problem?**
```javascript
  const browser = await puppeteer.launch({
    headless: true,
  });

  const page = await browser.newPage();
  await page.goto("https://www.michaelkors.eu/en_PL/cotton-polo-shirt/_/R-CU85FGVC93?color=2199", {timeout: 30000});
  console.log(await page.content());
```

**What is the expected result?**
Promise does not throw "Navigation Timeout Exceeded" no matter if using headless or non-headless mode.

**What happens instead?**
That url throws Promise throws "Navigation Timeout Exceeded" but only in headless mode.

Similar to:
https://github.com/GoogleChrome/puppeteer/issues/1922

**Comment by aslushnikov** [comment]
If you run your script with `DEBUG=*session node a.js` (a.js is the name of the script), you'll see
that server decided not to respond for headless request.

P.S. 30seconds is not enough anyway - headful loads the page in 1 minute for me.

**Comment by Namanmittal0007** [comment]
@aslushnikov where to write `DEBUG=*session node a.js`? In powershell it is giving error
```
DEBUG=*session : The term 'DEBUG=*session' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ DEBUG=*session node a.js
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DEBUG=*session:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
using a Windows machine
