### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by imdoge** [puppeteer/puppeteer#2965]
platform: Windows
"puppeteer": "^1.6.1",
"puppeteer": {
    "chromium_revision": "575458"
 },

when close chromium not use browser.close(), just ctrl + c in cmd, it cause high cpu usage, and the chromium process is not close
in old version puppeteer and chromium there's no this problem

my old version: (thers's no problem above)
"puppeteer": "1.1.1",
"puppeteer": {
    "chromium_revision": "536395"
 },

**Comment by ghost** [comment]
Could you share your code? I can't reproduce the issue.
