### ISSUE TITLE
handle postback and popup window

### ISSUE THREAD

**Issue by bimubuceru** [puppeteer/puppeteer#2968]
### Steps to reproduce
I want to scrape some pdf URLs from an ASP website 
but those url's are not just available in source code
to get those first I have to fill a drop field & submit it then it will give me files name with anchor tag & when I click on it, a execute a javascript[which look like this :javascript:__doPostBack('btn','')] & this javascript opens a popup window & it contains the pdf URL 
**Tell us about your environment:**

* Puppeteer version: 1.6.1 (installed it yesterday with the latest node)
* Platform / OS version: Windows 10 (64 bit)
* URLs (if applicable): 
* Node.js version: v8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
this is my code, headerless is false because I am testing
this code is able to fill the form & click on the anchor tag I want but I am not sure how to get the URL of that window page.url() is not working 
```
const puppeteer = require('puppeteer');
puppeteer.launch({headless: false}).then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://www.website/page.aspx');
  await page.select('#id', '2') // they are using onchange so i dont have to submit it
await page.click('#abtn') //to open that PDF
```

**What is the expected result?**
I want to get the PDF URL

**What happens instead?**
the code get stuck somewhere with no error

**Comment by ziadali1** [comment]
After the click a new window is open?
If so:

```
const newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.page())));	
await page.click('#abtn');	
const popup = await newPagePromise;
console.log(popup.url());
```

**Comment by bimubuceru** [comment]
hey thanks, it worked but I ended up with another issue 
 Error: Node is detached from document
there are approx 300 anchor tags on which I have to click
all of them will open the URL in the same window if the window is not closed (which is not an issue since I already got the previous URL, thanks to ziadali1  )
I am using for loop for clicking on all those buttons 

so far my code looks like this 
```js
const puppeteer = require('puppeteer');

(async function main(){
try{
  const browser = await puppeteer.launch({headless:true});
  const page = await browser.newPage();
  await page.goto('https://www.website.com/page.aspx',{waitUntil: 'load'}); // wait untill page loade
  await page.select('#identify','2'); // its a select tag value,which have onchange function so i dont have to submit this input field
  console.log('its loaded');
  await page.waitFor(1000); // waiting in case all anchor tags are not recieved, the server is slow
  let linkhandle = await page.$$('.link');
  const linkcount = linkhandle.length;
  console.log(linkcount);
  for (let i = 0; i < linkcount ; i++) { 
    const newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.page())));
    await linkhandle[i].click();
    const popup = await newPagePromise;
    console.log(popup.url());
  }
  await browser.close();
  } catch(e) {
    console.log('error',e)
  }
})();
```

**Comment by ziadali1** [comment]
My guess is: you're oppening a new window, getting the url but not closing. Your actual page is the new window so there would be no link to click.

Put this:` popup.close();` after the `console.log(popup.url())`

**Comment by bimubuceru** [comment]
same error 
& I think the next anchor tag is not being clicked because of this error 

the full error is 

```
error Error: Node is detached from document
    at ElementHandle._scrollIntoViewIfNeeded (C:\Users\user\Desktop\doc\node_modules\puppeteer\lib\ElementHandle.js:75:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
do i have to again navigate or focus on the main tab ? which contain all the url ?

**Comment by aslushnikov** [comment]
@bimubuceru: apparently clicking some of the links removes some other link from DOM. It's hard to say anything more exact without a script that I can run and debug locally.

Hope this helps.

**Comment by robomantis98** [comment]
```
    await page.click('[service_name="facebook"]')
    const newPagePromise = new Promise(x => browser.once('targetcreated',  target => x(target.page())));
    const popup = await newPagePromise;
    await popup.waitForSelector('[name="__CONFIRM__"]')
    const confirm = await popup.$('[name="__CONFIRM__"]')
    await popup.click('[name="__CONFIRM__"]')

```
Worked for Me, clicked on the facebook popup
