### ISSUE TITLE
navigator.requestMIDIAccess() throws "DOMException: An attempt was made to break through the security policy of the user agent." in headless mode

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#2973]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.1
* Platform / OS version: Mac OS 10.11.6
* URLs (if applicable): about:blank
* Node.js version: 10.7.0

**What steps will reproduce the problem?**

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', console.log);
  page.evaluate(function(){
      navigator.requestMIDIAccess().then(console.log).catch(console.error);
  })
  // OR
  // page.goto("http://www.multiplayerpiano.com")
})();
```

**What is the expected result?**

The promise returned by requestMIDIAccess() should resolve with the midi/access object containing midi outputs etc

**What happens instead?**

It rejects with a "DOMException: An attempt was made to break through the security policy of the user agent."

How do I access MIDI devices in puppetteer??

**Comment by vsemozhetbyt** [comment]
FWIW, the same error I get if I run this code in the browser console of `about:blank` page:
```
> navigator.requestMIDIAccess().then(console.log).catch(console.error);
< Promise {<pending>}
DOMException: An attempt was made to break through the security policy of the user agent.
```

**Comment by ghost** [comment]
In not-headless mode, the requestMIDIAccess() in www.multiplayerpiano.com _works_ (while it throws that error in headless). But yeah, in about:blank it still doesn't work. 🤔

**Comment by ghost** [comment]
Ok so since i couldn't use page.evaluate() i put the code in an html file and have the browser go to it. Now I have the issue of navigator.requestMIDIAccess() throwing the DOMException in headless mode, but not when not in headless mode.

**Comment by aslushnikov** [comment]
@ledlamp two things here:
- you shouldn't try to access midi on `'about:blank'`. Use a real domain instead
- you should use just-released [`browserContext.overridePermissions`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-browsercontextoverridepermissionsorigin-permissions) to enable midi permissions in headless

the following works for me on pptr v1.8.0:
```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  await browser.defaultBrowserContext().overridePermissions('https://aslushnikov.com', ['midi']);
  const page = await browser.newPage();
  await page.goto('https://aslushnikov.com');
  page.on('console', async msg => {
    console.log(msg);
  });
  await page.evaluate(function(){
      return navigator.requestMIDIAccess().then(console.log).catch(console.error);
  })
  await browser.close();
})();
```

hope this helps

**Comment by VikramTiwari** [comment]
Hey, @aslushnikov Is there a way to override permissions for more than 1 website? Even better would be `*` for all. Thanks!

**Comment by aslushnikov** [comment]
@VikramTiwari not yet, but that's a fair request. Filed #3225.

**Comment by VikramTiwari** [comment]
Awesome! Thanks :)
