### ISSUE TITLE
Node is either not visible or not an HTMLElement for page.click() in Puppeteer 1.6

### ISSUE THREAD

**Issue by metalwarrior665** [puppeteer/puppeteer#2977]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.6.1 (worked fine on puppeteer@1.4)
* Platform / OS version: Windows 10 or Debian
* URLs (if applicable):
* Node.js version: v9.3.0

**What steps will reproduce the problem?**

```const browser = await puppeteer.launch({headless: false, dumpio:true, executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"})
    const page = await browser.newPage()
    await page.setViewport({width:1535, height:756})
    await page.goto('https://login.sales-i.com/account/login')
    await page.waitFor(2000)
    // ***** LOGIN *****
    await page.type('#username-input', username)
    await page.waitFor(2000)
    await page.type('#Password', password)
    await page.waitFor(2000)
    await page.click('#sign-in-btn')
    console.log('waiting for selector')
    await page.waitForSelector('.campaign-link.menu-item')
```

**What is the expected result?**

Button is clicked, we are logged in and waiting for new page. This worked on Puppeteer 1.4

**What happens instead?**

this part ```await page.click('#sign-in-btn')``` throws 
`Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (C:\Projects\Apify\Playground\node_modules\puppeteer\lib\ElementHandle.js:86:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

Problem is solved using 

```await page.evaluate(()=>document.querySelector('#sign-in-btn').click())```

**Comment by metalwarrior665** [comment]
BTW: The same thing happens when I try to click after login.

**Comment by MissREM** [comment]
**Exactly the same issue.** 
==================
it was working with no issues on: **v.1.5.0**
async function login(url, user, password){
    return new Promise(async(resolve, reject)=>{
      await navTo(page,url);
      await page.type('#username', user);
      await page.type('#password', password);
      await page.click("[type='submit']");
      await page.waitForSelector(".nav.navbar-nav.navbar-right",{timeout: 50000})
      .catch((reason)=>{
        err.log(`Error: Element ".nav.navbar-right" took too long to show up or it was not present`);
      });
   ....blah blah blah

**Error:**
(node:17534) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/home/trey/Dev/ttt/node_modules/puppeteer/lib/ElementHandle.js:86:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:17534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**H.E.L.P**

**Comment by MaksymMalin** [comment]
Same shit for me.
```
`#!/usr/bin/env node
/* category and filters that can be applied for the urls that is fetched from flagma categories
// categories and filters that get from sitemap
// parsing sitemap using npm module html parser
//
// the exact location is inserted by the html form that produce ajax post request
//
//
//
router.post('/send.json', function(req, res) {
    console.log(req);
    console.log('req received');
    res.redirect('/');
});
//
//
//
//
//
//
//
//
/parsing each url in list of urls that saved in to array that received from sitemap and stored into variable
*/
/* activation the exact  initializing express routes*/
/*the application that */
var express = require("express");
var app = express();
var path = require("path");
var fs = require('fs');
var path = require('path');
  var process = require("process");
const puppeteer = require('puppeteer');
var bodyParser = require('body-parser')
app.use( bodyParser.json() );       // to support JSON-encoded bodies
app.use(bodyParser.urlencoded({     // to support URL-encoded bodies
  extended: true
}));
/*the application that */
var port = 3000;
var tr = require( "tor-request" );
tr.TorControlPort.password = "giraffe"
/*creating data base object with data of urls sources and subtree of other resources*/
/* creating arrays of elements in loop of index elements*/
/*
var name=[name];
var phone=[number];
*/
app.use('/', express.static(path.join(__dirname, '/app')));

/*assigning the absolute path to every file that included in express*/
app.get('/', function (req, res) {

res.post(__dirname+'/app/index.html');
/*getting the json parametrs of the string url that are visited*/
console.log(req.params);console.log("hello from server");
});
app.get('/desks', function (req, res) {
});
app.listen(port, function(){
console.log("server is started");
});


/*routing application to the page url with link post data*/
app.post('/post-data', function(req, res) {


/*deferent routes fro different desks*/
var url=req.body.url;
console.log("form is submited to url"+url);
  (async () => {
    var url=req.body.url;
    const browser = await puppeteer.launch({args: ['--no-sandbox','--blink-settings=imagesEnabled=false','--proxy-server=socks5://127.0.0.1:9050' ] });
    const page = await browser.newPage();
    await page.goto('https://api.ipify.org', {waitUntil: 'domcontentloaded'});
    let body= await page.evaluate(() => document.documentElement.textContent);

console.log(body);

    await page.setViewport({width: 1000, height: 500});
await page.waitFor(100);
    await page.goto(url, {waitUntil: 'domcontentloaded'});
    console.log("third phase");

    /*wait until page is ready*/
    /*go to the certain url to grab urls list*/
   /*go to the certain page url in pagination list */
   /*get allnumber of pages*/
   /*for all number in pages start scicle*/
/*assuming that we have the error in appication that iterates with possibe error . In that case we may skip the single iteration an write error log or write error*/
let pages = parseInt(await page.evaluate(() =>  document.querySelector('.notactive span').textContent));
console.log(pages);
let numberofpages=parseInt(pages);
for (var i = 1; i < pages; i++) {

tr.setTorAddress('localhost', 9050);
tr.newTorSession( (err) =>
  {
      console.log (err);

      return;
  });
  await page.goto('https://api.ipify.org', {waitUntil: 'domcontentloaded'});
  let body= await page.evaluate(() => document.documentElement.textContent);
    console.log (body);
let  paginateurl='https://flagma.ua/nedvizhimost-o-'+i+'.html';
console.log(paginateurl);
  await page.goto(paginateurl, {waitUntil: 'domcontentloaded' } );
  /*do clicks on each hidden number*/
/*await page.goto(url, {waitUntil: 'domcontentloaded'});*/
/*change url of the page to the certain page number and go to it*/
await page.screenshot({path: './digg.png', fullPage: true});
await page.waitFor(500);
let links = await page.evaluate(() => {
let data = [];
let elements = document.querySelectorAll('.page-list-item-header a');
for (var element of elements)
data.push(element.href);
return data;console.log(data);
});console.log(links  );
const text = [];
console.log(links);
var total=links.length;
for (let i = 0; i < links.length; i++) {
  await browser.newPage();
console.log("third phase");
    /*begin entering the urls that we got from the list of the elements that attached to the page we decided to visit*/
  let url = links[i].toString();
    console.log(url);
    tr.setTorAddress('localhost', 9050);
    tr.newTorSession( (err) =>
      {
          console.log (err);

          return;
      });
      await page.goto('https://api.ipify.org', {waitUntil: 'domcontentloaded'});
      let body= await page.evaluate(() => document.documentElement.textContent);
        console.log (body);
      await page.goto(url, {waitUntil: 'domcontentloaded' }    );
await page.waitFor(500);


await page.waitForSelector("#contacts");
await page.waitFor("#contacts",{visible:true})
let contacts = await page.evaluate(() =>  document.querySelector("#contacts"));
if(contacts !== null && contacts !== 'undefined'){
  await page.waitFor(3000);
contacts = await page.evaluate(() =>  document.querySelector("#contacts ").click());

let a=await page.evaluate(() =>  document.querySelector("#contacts a"));
if(a !== null && a !== 'undefined'){
await  page.hover('#contacts a');
await  page.click('#contacts a');
await page.waitFor(500);

var file = await page.evaluate(() =>  document.querySelector("#contacts").textContent);



if (file !==null){
  console.log(file);
  text.push(file);
  var fs = require('fs');
  fs.writeFile("./texts/"+'base'+'.txt', text, function(err) {
      if(err) {
          return console.log(err);
      }
      console.log("The file was saved!");
  });
}
}
}
else{
  contacts='';console.log('no phone');var file='';
}
await page.waitFor(500);










      /*do clicks on each hidden number*/







  // create a promise with the search in the page








/*add phones to viber*/





  }
}
/*ContactID,Name,ABContact,SortName,Number,ViberContact,ClientName,DownloadID,EncryptedNumber,MID,VID,ContactFlags*/
  /*writing the total numbers of scrapped contact into the file. Will write also in Database in future reeases*/
  fs.writeFile("./texts/"+'summury'+'.txt', total, function(err) {
      if(err) {
          return console.log(err);
      }
      console.log("The file was saved!");
  });

  throw err;
  /*write each of the result of each page to the file*/
  /*for each element in innerText array push new element and finally alert array and save it to the file*/

/*end the iteration*/

/*writing the promise hanaling an elay question for browser lybrary to make the exact all necessary preperations in case of blocked code . Writing stuie express lybrary an ports  an patterns for app sctructuring. ading new contacts to .Viber folder file*/

/*  */

    /**/
    console.log(file);
  await browser.close();
  })();
/*end for cycle*/

});
/*end of async wait function that calling the main page of urls we are going to fetch*/
`
```

**Comment by aslushnikov** [comment]
@metalwarrior665 I wasn't able to reproduce this with `puppeteer@next` (current tip-of-tree).

Here's the script I ran:

```js
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('https://login.sales-i.com/account/login', {waitUntil: 'networkidle0'});
    const name = await page.waitForSelector('#username-input');
    await name.type('andrey')
    const pass = await page.waitForSelector('#Password');
    await pass.type('12345678')
    await page.click('#sign-in-btn')
    console.log('waiting for selector')
    await page.waitForSelector('.campaign-link.menu-item')
    await browser.close();
})();
```

@MissREM , @Dignity1988: do you guys have good reproes? A script that I'd be able to run locally to see what's going on will help a lot.

**Comment by MaksymMalin** [comment]
Run my script with changes for selectors and see node is either not or not exists visible error on 6 iteration. If your cannot replicate the issue - tell we what is going on with it?

**Comment by metalwarrior665** [comment]
@aslushnikov I'm sorry, your code works, I forgot to add that I was running Chrome. The error happens both on my local computer and in Debian container. Headless vs headfull doesn't matter.

Try this (of course with different path):
```
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({ headless: false, executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'});
    const page = await browser.newPage();
    await page.goto('https://login.sales-i.com/account/login', {waitUntil: 'networkidle0'});
    const name = await page.waitForSelector('#username-input');
    await name.type('sdfsf')
    const pass = await page.waitForSelector('#Password');
    await pass.type('sdf!')
    await page.click('#sign-in-btn')
    console.log('waiting for selector')
    await page.waitForSelector('.campaign-link.menu-item')
    await browser.close();
})();
```

**Comment by aslushnikov** [comment]
> Run my script with changes for selectors and see node is either not or not exists visible error on 6 iteration. If your cannot replicate the issue - tell we what is going on with it?

@Dignity1988 you have quite a program there, including proxy and other unrelated stuff. It'll help a lot if you can strip it down to the ~10 lines script that illustrates the problem.

> @aslushnikov I'm sorry, your code works, I forgot to add that I was running Chrome. 

@metalwarrior665 puppeteer v1.6+ won't work with current stable - it requires at least chrome 69. More on this in our FAQ: https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy

**Comment by metalwarrior665** [comment]
@aslushnikov Thanks for explaining this, I wasn't aware of it

**Comment by markusrempfer** [comment]
I have a similar issue.

I'm running node.js together with puppeteer on a Ubuntu 16.04 (32-bit).

Chromium
Version 68.0.3440.75 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (32-bit)
	
puppeteer: "^1.7.0"
node: v8.11.3	  

... and I'm getting an error when I do a click(); event:

	const puppeteer = require('puppeteer');
	
	(async function main() {
	  try {
	
	    const browser = await puppeteer.launch({ headless: false, executablePath: '/usr/bin/chromium-browser'})
	    const page = await browser.newPage();
	
	    await page.goto('https://experts.shopify.com/');
	    await page.waitForSelector('.section');
	    const sections = await page.$$('.section');
	
	    for (const section of sections) {
	      const button = await section.$('a.marketing-button');
	      button.click();
	    }
	
	    console.log('done');
	    await browser.close();
	
	  } catch (e) {
	    console.log('our error', e);
	  }
	
	})();

On a windows10 machine its working fine. The error is:

Error: (node:11163) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/home/user/Project/node_modules/puppeteer/lib/ElementHandle.js:91:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    
... I also tried "puppeteer": "^1.5.0" but still the same error:

Is it my chrome version? How to solve it?

**Comment by MaksymMalin** [comment]
I have tried several versions and got same error from time to time due to
the page await or script . It seems like error handling should be set
separately but try launch several streams of application for different
pages and you will see that it is not stable error. Different browser
version is not a solution but several attempts can be the solution. Also
check what are you get as page . Sometimes defense systems of the websites
are hiding content with pop-ups or redirects. However I didn't find the
exact answer and looking to the selenium framework or python and c#
brothers.

**Comment by MaksymMalin** [comment]
However seems like you have different error. Try Check each step outputting
your selector in console

**Comment by markusrempfer** [comment]
What worked in my case was also ...

    await page.evaluate(() => {
      document.querySelector('a.marketing-button').click();
    });

Source: https://github.com/GoogleChrome/puppeteer/issues/1662

**Comment by MaksymMalin** [comment]
Cool that you have find the solution.

**Comment by hmpmarketing** [comment]
I can confirm that 

```
await page.evaluate(() => {
  document.querySelector('a.marketing-button').click();
});
```

as per Capaman post works for me (Chrome 68)

**Comment by slava-lu** [comment]
I have the same error. Above solution  with click() does not work. I am testing PayPal express checkout button. Puppeteer can't find the login button on PayPal auth pop-up

**Comment by rostgoat** [comment]
why is an error returned when simulating a double click in the same manner as above

```
await page.evaluate(() => {
  document.querySelector('.some-selector').dbclick();
});
```


error: `TypeError: document.querySelector(...).dbclick is not a function`

**Comment by felipemullen** [comment]
> why is an error returned when simulating a double click in the same manner as above
> 
> ```
> await page.evaluate(() => {
>   document.querySelector('.some-selector').dbclick();
> });
> ```
> 
> error: `TypeError: document.querySelector(...).dbclick is not a function`

I'm not sure that there is such a function as `dbclick` as part of the browser api. I remember jQuery had one

https://api.jquery.com/dblclick/

**Comment by jstewhite** [comment]
noob here; ran into same problem.  but seems to work after I'd added a slowMo option.. const browser = await puppeteer.launch({headless: false, slowMo: 100});

**Comment by Kradirhamik** [comment]
`const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
    });

    const page = await browser.newPage();
    await page.goto('https://google.com');
    await page.type(".gLFyf.gsfi", "test");
    // await page.keyboard.press('Enter');
    await page.click(".gNO89b");
    // await page.click(".q.qs");

    await browser.close();
})();`

This results on "UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement"

Why?

**Comment by bernardoadc** [comment]
Useful library: https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer

**Comment by ecolss** [comment]
> What worked in my case was also ...
> 
> ```
> await page.evaluate(() => {
>   document.querySelector('a.marketing-button').click();
> });
> ```
> 
> Source: #1662

Any idea why `page.evaluate` could work, but `page.click` couldn't?

**Comment by oxfn** [comment]
If we'll look into the stack trace of this exception, we'll see

        if (!quads.length)
          throw new Error('Node is either not visible or not an HTMLElement');

where `quads` is the result of [DOM.getContentQuads](https://vanilla.aslushnikov.com/?DOM.getContentQuads) call. So, `.click()` call is failing likely because the pointed element actually has the 0x0 rectangle, which often happens when element is simply a wrapper.

In my case I've adjusted my selector to element with non-empty rectangle and it worked.

**Comment by MarceloMendes94** [comment]
thanks

**Comment by ptitjes** [comment]
I've also got myself some "Node is either not visible or not an HTMLElement" errors with `page.click(...)` too.

They only occur when not in headless mode (ChromeHeadless). And they disappear if I replace the `page.click(...)` calls with some `waitAndClick(...)` calls where `waitAndClick` is defined as follows:

```ts
  async function waitAndClick(selector: string) {
    await page.evaluate((selector) => document.querySelector(selector).click(), selector);
  }
```

This doesn't feel good at all. Is this a problem of Puppeteer, Chrome or my code ?

**Comment by drptbl** [comment]
@ptitjes Encountered same issue, it happened only inside docker container, worked fine without it. Running in head mode on both (no headless). I've already had my custom `waitAndClick`, but it looked this way:
```js
async function waitAndClick(selector, page) {
  await page.waitForFunction(
    `document.querySelector('${selector}') && document.querySelector('${selector}').clientHeight != 0`,
    { visible: true },
  );
  const element = await page.$(selector);
  await element.click();
}
```
The `waitForFunction` didn't seem to do the trick here which is quite weird as I'm waiting until element is visible before trying to click on it. Other than that, yours solution worked perfectly:
```js
async function waitAndClick(selector, page) {
  await page.waitForFunction(
    `document.querySelector('${selector}') && document.querySelector('${selector}').clientHeight != 0`,
    { visible: true },
  );
  await page.evaluate((selector) => document.querySelector(selector).click(), selector);
}
```

Thanks.

**Comment by alsoarpit** [comment]
it also work for me Thanks Bro

 await gPage.evaluate(() => {
                                    document.querySelector('[href="#collapse4"] .panel-title').click();
                                    //page.waitFor(1000);
                                    document.querySelector('#moreCategories').click()
 });

**Comment by Colton1070** [comment]
> > why is an error returned when simulating a double click in the same manner as above
> > ```
> > await page.evaluate(() => {
> >   document.querySelector('.some-selector').dbclick();
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > error: `TypeError: document.querySelector(...).dbclick is not a function`
> 
> I'm not sure that there is such a function as `dbclick` as part of the browser api. I remember jQuery had one
> 
> https://api.jquery.com/dblclick/

Still an issue and happened out of nowhere without any changes to the website or my code. Literally just started failing, this solution worked for me. Think it has to do with other programs/operating headroom of the computer. Idk - not reproducible in a controlled environment but I would bet it's the culprit.
