### ISSUE TITLE
Desktop sizes missing from DeviceDescriptors

### ISSUE THREAD

**Issue by njbmartin** [puppeteer/puppeteer#2980]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I'm using puppeteer to ensure the UI fits on every screen, so I'm running a test suite that emulates each of the devices and then takes a screenshot:

```js
import devices from 'puppeteer/DeviceDescriptors'

devices.map(device => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.emulate(device)
  await page.goto('http://localhost:4444/')
  page.screenshot(screenshotPath)
})
```

**What is the expected result?**

Desktop sizes should be emulated.

> Chrome DevTools allows you to enable `Laptop with MDPI screen` and `Laptop with HiDPI screen`

**What happens instead?**

Only mobile devices are included.

**Current workaround**

```js
const emulatedDevices = [
  {
    name: 'Desktop 1920x1080',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36',
    viewport: {
      width: 1920,
      height: 1080
    }
  },
  {
    name: 'Desktop 1024x768',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36',
    viewport: {
      width: 1024,
      height: 768
    }
  },
  devices['iPad'],
  devices['iPad landscape']
]
```

**Comment by njbmartin** [comment]
Note #2981

**Comment by aslushnikov** [comment]
@njbmartin the supposed way was to use `page.setViewport`. I've seen your comments in #2981; it doesn't look too involved to generate your own set of devices that includes Desktops.

**Comment by simeyla** [comment]
Speaking of DeviceDescriptors - this sample is broken : [`screenshot-fullpage.js`](https://try-puppeteer.appspot.com/)

> Error running your code. ReferenceError: require is not defined

**Comment by aslushnikov** [comment]
@simeyla try-puppeteer doesn't support "require"

**Comment by simeyla** [comment]
@asludhnikov I never said it did ;-)

Click on that link and select the full screen screenshot from the dropdown - and the sample (that includes require) doesn’t work 

That’s all I was saying. Not a big deal - I’m up and running just fine locally and wishing I’d automated my screenshots much sooner! Just wanted to point out that the sample in the browser is broken.

**Comment by aslushnikov** [comment]
@simeyla ah, I misunderstood you. I'd appreciate if you can file this against [try-puppeteer](https://github.com/ebidel/try-puppeteer) repo, maybe @ebidel has some time to work on it.
