### ISSUE TITLE
page.emulate userAgent should be optional?

### ISSUE THREAD

**Issue by njbmartin** [puppeteer/puppeteer#2981]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

If you want to emulate a desktop size, there is no need to change the `userAgent` from the default.

```js
const emulatedDevices = [
  {
    name: 'Desktop 1920x1080',
    viewport: {
      width: 1920,
      height: 1080
    }
  },
  {
    name: 'Desktop 1024x768',
    viewport: {
      width: 1024,
      height: 768
    }
  },
  {
    name: 'Laptop 1280x800',
    viewport: {
      width: 1280,
      height: 800
    }
  },
  devices['iPad'],
  devices['iPad landscape']
]
```

**What is the expected result?**

`page.emulate` will emulate a device even though the userAgent hasn't been provided, as it will just use the default `userAgent` string.

**What happens instead?**

`Protocol error (Network.setUserAgentOverride): Invalid parameters userAgent: string value expected`

**Comment by JoelEinbinder** [comment]
Can you just use `page.setViewport(device.viewport)`?

**Comment by njbmartin** [comment]
While `setViewport` would indeed help, `page.emulate()` allows you to set options and emulate a number of devices without additional logic. I think you should be able to add custom devices to `page.emulate()`, and it seems odd that userAgent is required given that there is a default:

```js

page.emulate({
  name: 'Desktop 1920x1080',
  viewport: {
    width: 1920,
    height: 1080
  }
});
```

As described in #2980, this would allow you to iterate over a list of devices, including custom ones.

Rather simplified example for some context:

```js
import devices from 'puppeteer/DeviceDescriptors'

devices.map(async device => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.emulate(device)
  await page.goto('http://localhost:4444/')
  page.screenshot('test.jpg')
})
```

And this is how I'm currently using it with `jest-puppeteer`:

```js

import puppeteer from 'puppeteer'
import devices from 'puppeteer/DeviceDescriptors'

let page
let browser

const emulatedDevices = [
  {
    name: 'Desktop 1920x1080',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36',
    viewport: {
      width: 1920,
      height: 1080
    }
  },
  {
    name: 'Desktop 1024x768',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36',
    viewport: {
      width: 1024,
      height: 768
    }
  },
  {
    name: 'Laptop 1280x800',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36',
    viewport: {
      width: 1280,
      height: 800
    }
  },
  devices['iPad'],
  devices['iPad landscape']
]

describe.each(emulatedDevices)('devices', (device) => {
  describe(device.name, () => {
    beforeAll(async () => {
      browser = await puppeteer.launch({
        headless: false
      })
      page = await browser.newPage()
      await page.emulate(device)
      await clearDirectory(testPage)
      navigationPromise = page.waitForNavigation()
      await page.goto('http://localhost:4444/')
    })

    afterAll(async () => {
      await browser.close()
    })

    it('expect the login page to be shown', async () => {
      await expect(new URL(page.url()).pathname).toEqual('/login')
      await page.waitForSelector('.login-component', { visible: true })
    })
  })
})
```

**Comment by aslushnikov** [comment]
You can use [`browser.userAgent()`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-browseruseragent) to pre-populate default user agent for you emulated devices.

Let's keep things as-is.
