### ISSUE TITLE
Error Target closed in page.click()

### ISSUE THREAD

**Issue by gvelasquez760** [puppeteer/puppeteer#2982]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.1
* Platform / OS version: Ubuntu 16
* URLs (if applicable):
* Node.js version: v9.10.1

**What steps will reproduce the problem?**

I have a page that show the results of a search done with the values inserted in a popup with a "Search Now" button, after a user click this button, the popup automatically closes.

```

    await popup.evaluate((INPUT_SELECTOR) => {
        return document.querySelector(INPUT_SELECTOR).value = 123;
      }, INPUT_SELECTOR);
      await popup.click(SEARCH_BUTTON_SELECTOR);

```
**What is the expected result?**

popup.click should execute the search en the page (parent is in another tab) then automatically close the popup.

**What happens instead?**

every seems to work fine the 30% of the time but sometimes i got this error in the popup.click() and the execution stops

{ Error: Protocol error (Input.dispatchMouseEvent): Target closed.
    at Promise (/blabla/node_modules/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/blabla/node_modules/puppeteer/lib/Connection.js:201:12)
    at Mouse.up (/blabla/node_modules/puppeteer/lib/Input.js:258:24)
    at Mouse.click (/blabla/node_modules/puppeteer/lib/Input.js:235:16)
    at ElementHandle.click (/blabla/node_modules/puppeteer/lib/ElementHandle.js:139:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  message: 'Protocol error (Input.dispatchMouseEvent): Target closed.' }

**Comment by JoelEinbinder** [comment]
This error looks like it is working as intended. The page closed before we got confirmation that the click was successful. Since you expect the page to close, you can just catch the error and everything should work:
```js
await popup.click(SEARCH_BUTTON_SELECTOR).catch(e => e);
```
