### ISSUE TITLE
Set Cookies not working

### ISSUE THREAD

**Issue by sindhushreem** [puppeteer/puppeteer#2994]
### Steps to reproduce

* Puppeteer version:1.6.0
* Platform / OS version:linux,windows
* URLs (if applicable):
* Node.js version:8.4.0

below is the code which is used to generate the pdf .

const puppeteer = require('puppeteer');

const pdfPrint = async function pdfPrint(params, cb) {
  let browser = null;

  try {
    browser = await puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();

    await page.goto(params.url, { waitUntil: 'networkidle2' });
    await page.type(params.user_selector, params.user);
    await page.type(params.pass_selector, params.pass);
    await page.click(params.submit_selector).then(() => {
      return page.waitForNavigation({
        waitUntil: 'load',
        timeout: params.delay * 1000
      });
    });
    await page.goto(params.url, { waitUntil: 'networkidle2' });
 const setCookie = await client.send('Network.setCookie', {value:'sindhu',expires:Date.now()/1000+10, name:'cook',domain:'ccc.v.com'});
page.setCookie(setCookie);//not working
    const error = await page.waitForSelector(params.css_selector, {
      visible: true,
      timeout: params.delay * 1000

    }).then(() => {
      return null;
    }).catch(err => {
      console.log('error ocuured while getting css selector');

      return err;
    });

    console.log(error);
    const buffer = await page.pdf({
      format: params.page_format
    });

    console.log(buffer);

    // await page.pdf({path: './output.pdf', format: 'A4'});

    await browser.close();

    // console.log(error);

    await cb(error, buffer);
  } catch (err) {
   await browser.close();
   await cb(err,null);
  }
};

module.exports.pdfPrint = pdfPrint;

**What is the expected result?**
cokkies hsould be set befor navigating to url.

**What happens instead?**

cokkie sis not set.

**Comment by imfht** [comment]
this works for me, have a try

```javascript
const puppeteer = require("puppeteer")

let rockIt = (async () => {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    var cookie = [ // cookie exported by google chrome plugin editthiscookie
        {
            "domain": "httpbin.org",
            "expirationDate": 1597288045,
            "hostOnly": false,
            "httpOnly": false,
            "name": "key",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "value!",
            "id": 1
        }
    ]
    await page.setCookie(...cookie)
    await page.goto("https://httpbin.org/headers")
    console.log(await page.content())
    await page.close()
    await browser.close()

});
rockIt()
```

**Comment by sindhushreem** [comment]
var cookie = [ 
        {
            "domain": "hpeswlab.net",
            "expirationDate": 1597288045,
            "hostOnly": false,
            "httpOnly": false,
            "name": "key",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": false,
            "session": false,
            "storeId": "2",
            "value": "value!",
            "id": 1
        },
        
        {
            "domain": "btpvm2216.hpeswlab.net",
            "expirationDate": 1597288045,
            "hostOnly": false,
            "httpOnly": false,
            "name": "key",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "value!",
            "id": 2
        }
    ]
    await page.setCookie(...cookie);


am not abe to add cookies with different domain .

**Comment by aslushnikov** [comment]
@sindhushreem can you please share a full script? I need to be able to run it locally to see what's going on.

**Comment by east-before-dawn** [comment]
like this
get the cookies from [EditThisCookie](http://www.editthiscookie.com/)
```js
[{
"domain": ".renren.com",
"expirationDate": 1626122968.576495,
"hostOnly": false,
"httpOnly": false,
"name": "_de",
"path": "/",
"sameSite": "unspecified",
"secure": false,
"session": false,
"storeId": "0",
"value": "xxxxxxxxx",
"id": 1
},
.........
{
"domain": "photo.renren.com",
"hostOnly": true,
"httpOnly": false,
"name": "JSESSIONID",
"path": "/",
"sameSite": "unspecified",
"secure": false,
"session": true,
"storeId": "0",
"value": "xxxxxxxxx",
"id": 17
}]
```
----
```js
const cookie = [
{
    "domain": ".renren.com",
    "expires": 1626122968.576495,
    "httpOnly": false,
    "name": "_de",
    "path": "/",
    "sameSite": "Lax",
    "secure": false,
    "value": "xxxxxxxxx",
},
.....
{
    "domain": "photo.renren.com",
    "httpOnly": false,
    "name": "JSESSIONID",
    "path": "/",
    "sameSite": "Lax",
    "secure": false,
    "value": "xxxxxxxxx",
}
const promise = await page.setCookie(...cookie);
```
