### ISSUE TITLE
Event 'requestfailed' can‘t be triggered when one of the requests return 404

### ISSUE THREAD

**Issue by qingranfjj** [puppeteer/puppeteer#2995]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.6.1
* Platform / OS version:iMac/OS X 10.11.6
* URLs (if applicable):https://h5.m.taobao.com
* Node.js version:v8.9.4

**What steps will reproduce the problem
_Please include code that reproduces the issue._

there is a url request fail,return 404,why the event 'requestfailed' can not hand it, i thought the failedRequest should be 1,but is 0
![default](https://user-images.githubusercontent.com/16664041/43444514-7d190e24-94d6-11e8-8c8d-4e2ee2794d4a.png)
![default](https://user-images.githubusercontent.com/16664041/43444564-a23ce194-94d6-11e8-9946-dcd5ceb89d73.png)

**What is the expected result?**
1

**What happens instead?**

0

**Comment by aslushnikov** [comment]
@qingranfjj the `requetsfailed` is dispatched for requests that were aborted. The 404 is a successful response - certain websites even serve a fancy 404 page.

Hope this helps.
