### ISSUE TITLE
Puppeteer should check platform compatibility when running

### ISSUE THREAD

**Issue by kingio** [puppeteer/puppeteer#2996]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.1
* Platform / OS version:  Ubuntu 14.04.1 LTS (i686)
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

1. `npm i puppeteer`
2. 
```js
const puppeteer = require('puppeteer');
const browser = await puppeteer.launch();
const page = await browser.newPage();
```

**What is the expected result?**

Working chrome

**What happens instead?**

`(node:14901) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/var/www/spiderman/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: 1: /var/www/spiderman/node_modules/puppeteer/.local-chromium/linux-575458/chrome-linux/chrome: Syntax error: word unexpected (expecting ")")
`

If i manually run that chrome, it says `cannot execute binary file: Exec format error`

**Comment by aslushnikov** [comment]
@kingio Chromium is compiled for x86_64, which I believe is not runnable on i686. 

We don't have any 32 bit builds, and there are no plans to add any.  Sorry for the inconvenience.

**Comment by kingio** [comment]
Shouldn't puppeteer do a requirement check before installing itself? You would avoid issues like this

**Comment by aslushnikov** [comment]
@kingio this would be nice to have; I'd be happy to review a PR.

**Comment by aslushnikov** [comment]
> Shouldn't puppeteer do a requirement check before installing itself?

Actually, we should rather do this in runtime on `pptr.launch` and only for the default binary: someone might specify custom executable path.

**Comment by mawesome4ever** [comment]
Oh wow... I've been trying to get this to work for hours... I kept thinking i had forgotten to place a parenthesis somewhere .-.

**Comment by bdurrani** [comment]
@aslushnikov Do you mind if I take a stab at this? can you give me some pointers on were would be a good place to start? Thanks

**Comment by bdurrani** [comment]
Looks like in node, `os.arch()` will return the architecture of the node process, not of the OS.[ See here](https://github.com/nodejs/node/issues/17036).

Would it be safe to assume that the 32bit version of node should not be able to launch Chromium?

Otherwise, I can basically do what [this library](https://github.com/feross/arch) does to detect the architecture of the OS.

**Comment by akgupta0777** [comment]
what happened here still no solutions ?
I like the solution of @bdurrani but I think it will not work on all architectures and the library should be maintained regularly on every new architecture.

**Comment by Gennttii** [comment]
I am having problems with launching browser too. Can puppeteer work with 32 bit chromium by changing the executablePath :
` executablePath: '/usr/bin/chromium-browser'`?

**Comment by Lightning00Blade** [comment]
Today this should be handled by the `@puppeteer/browsers` package and there is an open issue about this https://github.com/puppeteer/puppeteer/issues/12583, so closing this.
