### ISSUE TITLE
Get rid of chrome-remote-interface dependency

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#3]
The `chrome-remote-interface` dependency served us good. However, our usage of `chrome-remote-interface` is minimal: we use only `.send()` method and event subscription. This is not hard to implement (e.g. there's a lighthouse implementation: [connection.js](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/connections/connection.js)).

**Comment by paulirish** [comment]
true. half of the impl is actually in https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/connections/cri.js FWIW
