### ISSUE TITLE
Emit Page.Events.ResponseReceived in HAR format.

### ISSUE THREAD

**Issue by pavelfeldman** [puppeteer/puppeteer#30]

**Comment by paulirish** [comment]
https://github.com/cyrus-and/chrome-har-capturer is well used. He is also adding a mode to create HAR from provided events.

https://w3c.github.io/web-performance/specs/HAR/Overview.html

**Comment by aslushnikov** [comment]
As I'm reading through [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), it looks like it would be logical to use [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) object to report responses. This would be also consistent with #26, and this would nicely allow us to use Response as a return value for `page.navigate` (as discussed in #10).

The request/response events would look like this:
```js
page.on('request', request => console.log('>>' + request.url));
page.on('response', response => console.log('<<' + response.status + ' ' + response.url));
```

In this case, the "export as HAR" feature should be implemented separately.

@paulirish, @pavelfeldman - what do you guys think?

**Comment by paulirish** [comment]
Agree.

[HAR does have tooling](https://npms.io/search?q=har), but the spec is dated and doesn't have good ways to represent:

* dns-prefetch
* h2 push
* stalled time and other non-sequential timings
* data URIs
* header compression
* resource priority
* initiators
* streamid, ping packets, h2 connection settings, frame details

see also: 
* https://github.com/ahmadnassri/har-spec/blob/master/versions/1.3.md
* https://groups.google.com/forum/#!topic/http-archive-specification/0Nvyx65q3oI
* https://lists.w3.org/Archives/Public/public-web-perf/2013Feb/0009.html
* https://lists.w3.org/Archives/Public/public-web-perf/2017Apr/0011.html

As such, it looks like we need an investment in the entire HAR ecosystem for us to make it first-class here.

cc @allada

**Comment by aslushnikov** [comment]
Closing this since we're not going to invest into this in the near future.
