### ISSUE TITLE
My method sometimes returns JsHandle, sometimes Promise.

### ISSUE THREAD

**Issue by tech-a-go-go** [puppeteer/puppeteer#3006]
* Puppeteer version: 1.6.0
* Platform / OS version: Docker (node:10.7.0-slim) on CentOS 7
* Node.js version: 10.7.0

I'm not having a problem but a question.

My method (which is supposed to return a Promise object) in evaluate() below sometimes returns a JsHandle object as a then parameter, sometimes a Promise object.
```
await page.evaluate(() => {
  window.myMethod.process().then((res) => {
    // res is sometimes a JsHandle object, sometimes Promise.
  });
});
```
I'd like to know in what situation I would have a JsHandle object ??

and Should I check the type of the object like the following and do what I want ??
( I guess this is quite stupid ..)
```
await page.evaluate(() => {
  window.myMethod.process().then((res) => {
    if (typeof res === 'JsHandle) {
      // do something...
    } else if (typeof res === 'Promise') {
      // do something...
    } else {
      // ....
    }
  });
});
```

Cheers

**Comment by aslushnikov** [comment]
> I'd like to know in what situation I would have a JsHandle object ??

@tech-a-go-go Documentation on JSHandles is available in a class description, e.g. at [pptr.dev](https://pptr.dev/#?product=Puppeteer&version=v1.6.2&show=api-class-jshandle).

First thing to understand is that there are two execution contexts:
- node.js context where Puppeteer typically operates
- browser context which hosts all evaluations (e.g. functions that you pass as an argument to `page.evaluate`)

`JSHandle` classes are part of node.js context; they never appear anywhere inside the page.
So neither of your examples might have a JSHandle in there.

> Should I check the type of the object like the following and do what I want ??

No; there's never a JSHandle object inside browser context.

Hope this helps
