### ISSUE TITLE
Print to PDF call not working as expected in example?

### ISSUE THREAD

**Issue by campbecf** [puppeteer/puppeteer#301]
In the example:

```
await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle'});
await page.pdf({path: 'hn.pdf', format: 'A4'});
```

This output is generated (for me at least)

[hn.pdf](https://github.com/GoogleChrome/puppeteer/files/1229290/hn.pdf)

But below is what I get if I manually print from a Chrome browser on the same page.

[FromChrome.pdf](https://github.com/GoogleChrome/puppeteer/files/1229289/FromChrome.pdf)

Some other sites work as expected, maybe an issue with HN?

**Comment by Garbee** [comment]
Printing uses the print css defined in the stylesheet. Generating a PDF via puppeteer is grabbing the rendering as it is on the page. That explains the discrepancy.

A method could be added to trigger print style emulation to get the right effect.

**Comment by Garbee** [comment]
A `print` [property](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageemulateoptions) could be added to the `emulate` method for a page. This would trigger print styles for the rendering. So then you should get the same PDF output between a manual and automated run.

**Comment by campbecf** [comment]
This seems to be a little inconsistent though? 

For example this:

```
await page.goto('https://www.washingtonpost.com/sports/capitals/coming-home-cullen-picks-wild-for-21st-nhl-season/2017/08/16/5dfe7858-82b7-11e7-9e7a-20fa8d7a0db6_story.html', {waitUntil: 'networkidle'});
await page.screenshot({path: 'example.png'});
await page.pdf({path: 'test.pdf', format: 'Letter'});
```

generates  this screenshot

![example](https://user-images.githubusercontent.com/1759842/29381887-c4667f74-8298-11e7-8c8a-abbee685ce6d.png)

but this pdf?

[test.pdf](https://github.com/GoogleChrome/puppeteer/files/1229317/test.pdf)


Sometimes print style sheets seem to work.

**Comment by Garbee** [comment]
Maybe the `A4` vs `Letter` format triggers it?

EDIT: Not seeing in the Puppeteer code why this would be the case.

**Comment by aslushnikov** [comment]
@campbecf: there are different defaults. Puppeteer defaults [`printBackground`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) to `false`, whereas chrome has it set to `true` by default. 

There are also other defaults, like margins, which you can tweak to achieve the same results.

**Comment by campbecf** [comment]
@aslushnikov 

```
const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.setViewport({width: 1920, height: 1200})
await page.goto('https://news.ycombinator.com/', {waitUntil: 'networkidle'});
await page.screenshot({path: 'example.png'});
await page.pdf({path: 'test.pdf', format: 'A4', printBackground: true});

browser.close();
})();
```

From chrome: 
[FromChrome.pdf](https://github.com/GoogleChrome/puppeteer/files/1229444/FromChrome.pdf)

Puppeteer screenshot:
![example](https://user-images.githubusercontent.com/1759842/29384118-e8aa7216-82a0-11e7-8c9c-802cacfc49b2.png)

Puppeteer PDF with printBackground true:

[test.pdf](https://github.com/GoogleChrome/puppeteer/files/1229446/test.pdf)

Puppeteer PDF with printBackground false:

[test.pdf](https://github.com/GoogleChrome/puppeteer/files/1229448/test.pdf)


printBackground does not seem to make difference. 

At the very least you may want to switch the PDF example on the readme to a site that works closer to expectation ?

**Comment by aslushnikov** [comment]
Ahh, that's a bug! Thanks!

**Comment by aslushnikov** [comment]
Should work now. Feel free to write here or create another issue if `page.pdf()` is still broken for you.

**Comment by oliveiraethales** [comment]
Hi @aslushnikov!

I'm having an issue regarding the PDF printing which might or might not be related to this one. It might also be related to #312 or perhaps even related to this Chromium bug (https://bugs.chromium.org/p/chromium/issues/detail?id=749080).

Consider the following script:

```
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('http://example.com', {waitUntil: 'networkidle'});

  await page.emulateMedia('screen');
  await page.pdf({path: 'sample.pdf', format: 'A4', printBackground: true}
});
```
The expected output PDF would be something like:

[sample.pdf](https://github.com/GoogleChrome/puppeteer/files/1387492/sample.pdf)

But the actual output is:

[sample 2.pdf](https://github.com/GoogleChrome/puppeteer/files/1387497/sample.2.pdf)

This also happens when printing to PDF directly through Chrome/Chromium browser itself. It might be related to what @Garbee mentioned above:
`Maybe the A4 vs Letter format triggers it?`
What I've observed is a really strange behavior that by selecting Landscape as orientation _OR_ formats larger than A4 (A3, A2, etc), the problem is solved, both through Puppeteer or the browser itself. Maybe it's a parameter or config that I'm missing or it is indeed a Chromium bug.

Can you guys take a look? Much appreciated!

**Comment by aslushnikov** [comment]
@oliveiraethales that's because example.com has a media query css rule:

```css
    @media (max-width: 700px) {
        body {
            background-color: #fff;
        }
        div {
            width: auto;
            margin: 0 auto;
            border-radius: 0;
            padding: 1em;
        }
    }
```

**Comment by oliveiraethales** [comment]
@aslushnikov Indeed, I was so focused on finding the issue that I haven't considered the CSS rules themselves. Cheers!

**Comment by TheFox** [comment]
`printBackground: true` solved my problem. But why should I ever print a website without background? OK, maybe when I just want the text out of the website. But maybe this setting should be by default `true`.

**Comment by nullablebool** [comment]
> `printBackground: true` solved my problem. But why should I ever print a website without background? OK, maybe when I just want the text out of the website. But maybe this setting should be by default `true`.

Commonly it is defaulted to false, most browsers do not allow you to override it. Generally, you don't want to print the background of a page - consider an off-white #fdfdfd would you really want to print that?

It may not be intuitive but as PDF rendering is ultimately printing then it makes sense to keep defaulted as false.

**Comment by 2yk** [comment]
```printBackground: true``` worked for me as well.

Thanks

**Comment by Optimusbumble** [comment]
@campbecf how does your PDF has 2 pages split according to the content . Sorry for asking it in here .
Can you please help me here. I am successfully able to PDF a long pages of content but in a single page . I wanted to split it like your example pdf according to content.

**Comment by LonHon** [comment]
@Optimusbumble try this way:
``` html
<p style="page-break-after:always;width: 0; height: 0;"></p>
```
