### ISSUE TITLE
Is there any way to mimic Mobile devise.

### ISSUE THREAD

**Issue by vijeshv** [puppeteer/puppeteer#3015]
Hi,

is there any way to mimic Mobile devise ( i mean same as toggle devise option in devloper tools) from chromium?

Thanks,
vij

**Comment by ThomasSimeroth** [comment]
Yes, use the `page.emulate()` method. There's a lovely example in the API docs, located [here](https://github.com/GoogleChrome/puppeteer/blob/v1.6.2/docs/api.md#pageemulateoptions)

**Comment by vijeshv** [comment]
Thanks thomasi found it later posting question here.

Is there any possibility to emulate devise network?
Also any good tool or plugin which  record browser action and generate
puppeteer scrip.i fouund 'daydreamer' by googling.but it support only very
simple web applications.it crashes while recording rich &responsive web
applications.

Thanks
Vij

**Comment by aslushnikov** [comment]
@vijeshv for now, the best way to emulate network shaping is to use designated software.
