### ISSUE TITLE
Chrome Dev Tools statement does not work with puppeteer.

### ISSUE THREAD

**Issue by Neseke** [puppeteer/puppeteer#3016]
**Tell us about your environment:**

* Puppeteer version: 1.6.2
* Platform / OS version: Windows 10
* Node.js version: 8.11.3

**What I want to do.**
I can use following input in the chrome dev tools:
`const nodelist = document.querySelectorAll('select[name=registergericht] option');`
`Array.from(nodelist).map(option=> { return { value: option.value, text: option.text } })`

**Screenshot**
![image](https://user-images.githubusercontent.com/37878578/43588440-cd8ed6d0-966c-11e8-80ea-f51730382fb7.png)

**What steps will reproduce the problem?**
```javascript
const puppeteer = require('puppeteer');

const URL = 'https://www.handelsregister.de/rp_web/mask.do?Typ=e';
const SELECTOR = 'select[name=registergericht] option';

puppeteer.launch().then(async browser => {
	const page = await browser.newPage();
	await page.goto(URL);

	// [{ value: 'R2713' }, ..., { value: 'N1105' }];
	const options = await page.$$eval(SELECTOR, options =>
		options.map(option => {
			return {
				value: option.attributes[0].value,
				text: option.attributes[0].text
			};
		})
	);

	// [ ElementHandle, ..., ElementHandle ]
	const options2 = await page.$$(SELECTOR);

	// [{ value: 'R2713' }, ..., { value: 'N1105' }];
	const options3 = await page.evaluate(selector => {
		let regions = Array.from(document.querySelectorAll(selector));

		regions = regions.map(region => {
			return {
				value: region.attributes[0].value, // this works fine!
				text: region.attributes[0].text // this props is not even returned, it just disappears :(
			};
		});

		return regions;
	}, SELECTOR);

	await browser.close();
});

```
**What is the expected result?**
```javascript
[{ value: "R3101", text: "Aachen" }, ...,
{ value: "Y1201", text: "Altenburg" }]
```

**What happens instead?**
I don't get the ```text``` property, it just disappears. And I can't log the ```options``` property to see which properties I can get (e.g. ```options.innerHTML``` is not available, too). 

**Github Repo**
Feel free to clone [the repo](https://github.com/Neseke/pptr-issue.git).

**Comment by vsemozhetbyt** [comment]
In the browser console, you use `option.text`, while in the puppeteer script you use `option.attributes[0].text` or `region.attributes[0].text`. It seems this should be `option.text` or `region.text`.

**Comment by Neseke** [comment]
Gosh, that did work 👍
