### ISSUE TITLE
puppeteer page.click function not working after define executablePath= /usr/bin/chromium-browser

### ISSUE THREAD

**Issue by githubmaster1987** [puppeteer/puppeteer#3018]
* Puppeteer version: 1.6.2
* Platform / OS version: Ubuntu 16.04 or Docker
* URLs (if applicable): anything
* Node.js version: node 10.5

* Docker file case
```
FROM node:10-alpine

# Update apk repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# Install chromium
RUN apk update && apk upgrade && \
	echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
	echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
	apk -U --no-cache \
	--allow-untrusted add \
	zlib-dev \
	chromium@edge \
	nss@edge \

```

I installed puppeteer and I installed chromium-browser on Ubuntu.
If I define executablePath = /usr/bin/chromium-browser, await page.click function doesn't work.

**What is the expected result?**
click button/input text field

**What happens instead?**
Error: Node is either not visible or not an HTMLElement

**Comment by aslushnikov** [comment]
@githubmaster1987 please see our FAQ entry: https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy

**Comment by githubmaster1987** [comment]
Which version of chromium and puppeteer is working well?

if I don't define excutablePath on ubuntu, it's working well. maybe it is using same chromium browser.
