### ISSUE TITLE
add support for ElementHandle as an argument and a return value to evaluate

### ISSUE THREAD

**Issue by jesg** [puppeteer/puppeteer#302]
adding support for ElementHandle as both a valid argument and return value to evaluate will make the api more powerful for end users.

i'd expect both of the following to work.  (they are both broken)
```
const elem = await page.$('input')
const b = await page.evaluate((a) => { return a }, elem)
await b.click()
```

```
const b = await page.evaluate(() => { return document.querySelector('input') })
await b.click()
```

**Comment by ebidel** [comment]
Just ran into this myself writing some new examples. Bump for priority :)

**Comment by ivanvanderbyl** [comment]
Related #303

**Comment by pavelfeldman** [comment]
Closing in favor of #382.
