### ISSUE TITLE
Feature Request: waitFor({ waitUntil: 'networkidle0' });

### ISSUE THREAD

**Issue by intellix** [puppeteer/puppeteer#3025]
As spoke about in this issue: https://github.com/GoogleChrome/puppeteer/issues/1412#issuecomment-402514070

It would be great to expose an API to wait for `networkidle0` that doesn't rely on navigation to help SPAs take screenshots.

### Steps to reproduce

1) Have a button that loads some images without the need to navigate
2) Click that button programatically:
```ts
await page.click('button');
```
3) Take a screenshot after all of the images have loaded:
```ts
await page.waitFor({ waitUntil: 'networkidle0' });
await page.screenshot();
```

### Currently

You can achieve it by manually attaching to request and repeating the logic for networkidle0 as stated here: https://github.com/GoogleChrome/puppeteer/issues/1412#issuecomment-410552890

Typically it's not a problem for old-style non-SPA websites where everything is triggered by a navigation.

**Comment by sheerun** [comment]
It would be also useful when clicking on some element on page loads stuff dynamically but doesn't navigate to different url

**Comment by sheerun** [comment]
Here's my workaround:

```es6
  let inflight = 0

  page.on('request', request => {
    inflight += 1
    request.continue()
  })

  page.on('requestfinished', request => {
    inflight -= 1
  })

  page.on('requestfailed', request => {
    inflight -= 1
  })

  const sleep = (timeout) => new Promise(resolve => setTimeout(resolve, timeout))
  const wait = async ({ waitUntil }) => {
    const maxIdle = waitUntil === 'networkidle0' ? 0 : 2

    while (inflight > maxIdle) {
      await sleep(100)
    }
    await sleep(500)
    if (inflight > maxIdle) {
      await wait({ waitUntil })
    }
  }
```

then I can use it as so in tests:

```es6
    await page.click(elSelector)
    await wait({ waitUntil: 'networkidle0' })
```

It would be nice if such function was in core
