### ISSUE TITLE
RequestInterception: postData undefind for form with file input

### ISSUE THREAD

**Issue by paolocaminiti** [puppeteer/puppeteer#3030]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.2
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.11

**What steps will reproduce the problem?**

1. setup request interception to log postData
```
const page = await browser.newPage()
await page.setRequestInterception(true)

page.on('request', interceptedRequest => {
  // console.log('postData', interceptedRequest.postData())  
  interceptedRequest.continue()
})
```

2. set a file input and submit a form
```
const fileInput = await page.$('input[type="file"]')
await fileInput.uploadFile(filePath)
await page.click('input[type="submit"]')
```

3. look at the console

**What is the expected result?**
postData() should return the form data including the file provided to the file input

**What happens instead?**
postData() returns undefined

**Comment by Qianlitp** [comment]
+1 !!! same issue

**Comment by aslushnikov** [comment]
Merging this all to a single umbrella bug - #3471. Please upvote to follow updates.
