### ISSUE TITLE
Puppeteer page.goto("non existing url") even resolve for non existing url

### ISSUE THREAD

**Issue by VinayParasrampuria** [puppeteer/puppeteer#3031]
I am using puppeteer for HTMl to PDF generation . While it works good for any existing url it do not through errro for any non existing error but generated a 1kb bank pdf .  

page.goto("http://abc.com") resolves good though there is no abc.com page

Regards
Vinay

**Comment by aslushnikov** [comment]
`page.goto("http://abc.com")` resolves since there's a bunch of redirects that redirect to https://abc.go.com/. 

If you still think there's an issue, please re-file with a good repro so that I can reproduce.

**Comment by fatima-gloqal** [comment]
Hello, i think its an issue as it needs to show the url given , you can handle it like an error
