### ISSUE TITLE
problem with new tab

### ISSUE THREAD

**Issue by hamti2018** [puppeteer/puppeteer#3033]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version: windows
* URLs (if applicable):
* Node.js version: 8.11.3

I need to do several steps in this order:

1 open the tab go to the site - 1
2 open a new tab to go to the site - 2, close the tab
3 go to the tab 1 click the button and then execute other functions on the tab 1

I did this:

```
let page1 = await browser.newPage();
let page2 = await browser.newPage();

await one()
await two() // error: Session closed. Most likely the page has been closed.


async function one(page) {
  await page.bringToFront()
  //....
}

async function two(page) {
  await page.bringToFront()
  //....
}
```

How can I do it? Thank you

**Comment by aslushnikov** [comment]
@hamti2018 this should work just fine. Can you provide a small script that illustrates the issue and that I can run locally?

**Comment by hamti2018** [comment]
@aslushnikov 

const puppeteer = require('puppeteer')
const faker = require('faker');

```
(async () => {
  let browser = await puppeteer.launch({
    headless: false,
    handleSIGINT: false,
    handleSIGTERM: false,
  });

  let page1 = await browser.newPage();
  let page2 = await browser.newPage();
  let login = await getEmail(page1)
  await aiodexRegister(page2, login)
  await aiodexVote(page1, login)
})()

async function aiodexVote(page, login) {
  await page.bringToFront()

  while (true) {
    try {
      await page.click('a#lrefr')
      await page.waitForSelector('div#m1', { timeout: 1000 })
      break
    } catch (e) {
      console.log(e)
    }
  }

  await page.click('div#m1 > div > a')
  await page.waitForSelector('div#mailmillieu')
  await page.click('div#mailmillieu a')
  await page.waitForSelector('a[href=\'/login\']')
  await page.click('a[href=\'/login\']')
  await page.waitForSelector('input[placeholder=\'E-mail\']')
  await page.type('input[placeholder=\'E-mail\']', login.email)
  await page.type('input[type=\'password\']', login.password)
  await page.click('button[type=\'submit\']')
  await page.waitForSelector('a[href=\'/cpanel/profile\']')
  await page.evaluateHandle(() => {
    return document.querySelector('a[href="/vote/coin/5b5a5f481aaad360dc475330"]').nextSibling.nextSibling
  })
    .then((button) => {
      button.asElement()
    })
    .then((button) => {
      button.click()
    })

  await page.waitFor(3000)
}

async function aiodexRegister(page, login) {
  await page.bringToFront()
  await page.goto('https://aiodex.com/register')
  await page.waitForSelector('input[placeholder=\'First Name\']')
  await page.type('input[placeholder=\'First Name\']', faker.name.firstName());
  await page.type('input[placeholder=\'Last Name\']', faker.name.lastName());
  await page.type('input[placeholder=\'E-mail\']', login.email);
  await page.type('input[placeholder=\'Password\']', login.password);
  await page.click('button[type=\'submit\']');
  await page.waitForSelector('div.panel div.panel-body div h4', { visible: true });
}

async function getEmail(page) {
  await page.bringToFront()
  await page.goto(`http://www.yopmail.com/ru/email-generator.php`);
  await page.waitForSelector('input[type=\'submit\'][value=\'Проверить почту\']')
  await page.click('input[type=\'submit\'][value=\'Проверить почту\']')
  await page.waitForSelector('input#login')
  let email = await page.$('input#login')
    .then(message => {
      return message.getProperty('value')
    })
    .then(text => {
      return text.jsonValue()
    })

  return {
    email: email + '@yopmail.com',
    password: email
  }
}
```

(node:24712) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.bringToFront): Session closed. Most likely the page has been closed.
    at CDPSession.send (C:\Users\Admin\Desktop\aiodexBot\node_modules\puppeteer\lib\Connection.js:189:29)
    at Page.bringToFront (C:\Users\Admin\Desktop\aiodexBot\node_modules\puppeteer\lib\Page.js:700:24)
    at aiodexRegister (C:\Users\Admin\Desktop\aiodexBot\app\index.js:57:14)
    at C:\Users\Admin\Desktop\aiodexBot\app\index.js:16:9
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:24712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment]
@hamti2018 I don't see any error here; also, what does the script do?..

**Comment by hamti2018** [comment]
@aslushnikov  After the end of the function getEmail, an error occurs

**Comment by aslushnikov** [comment]
> After the end of the function getEmail, an error occurs

It doesn't for me. Do you see any of the pages close in chromium? Do they crash?
