### ISSUE TITLE
Web crawler results only correct when use 'slowMo'

### ISSUE THREAD

**Issue by codepileman** [puppeteer/puppeteer#3034]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.0
* Platform / OS version: Windows 10
* URLs (if applicable):https://www.beyondmenu.com/20624/duluth/china-taste-duluth-30096.aspx
* Node.js version: 8.9.4

**What steps will reproduce the problem?**
Run the code

_Please include code that reproduces the issue._
const pp = require('puppeteer');
 
(async function main() {
    try {
        const data = {};
        const browser = await pp.launch({ headless: true, args: ['--disable-dev-shm-usage'] });
        const page = await browser.newPage();
        await page.setViewport({width: 2000, height: 1000});
        page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/69.0.3477.0 Safari/537.36');
    
        const link = 'https://www.beyondmenu.com/20624/duluth/china-taste-duluth-30096.aspx';

        await page.goto(link, {waitUntil: 'load'});
        
        await page.waitForSelector('.restaurant_wrapper');

        const resInfo = await page.$eval('.restaurant_wrapper', h1 => h1.innerText);           
        data['name'] = resInfo.split('\n')[0];
        const addr = resInfo.split('\n')[1].slice(0,-18);

        await page.waitForSelector('.menu_categories');
        const menus = await page.$$('.menu_categories > a');
        console.log('This store has ', menus.length, 'menu(s)'); 
        data['menus']= [];
        for (let i=0; i< menus.length; i++){
            const menuObj = {};
            menuObj['mcs'] = [];

            await page.goto(link, {waitUntil: 'load'});
            await page.waitForSelector('.menu_categories');
            const menus = await page.$$('.menu_categories > a'); 
            const menu = menus[i];
            const buttonName = await page.evaluate(menu => menu.innerText, menu);
            console.log('menu button name:', buttonName);
            
            await page.waitForSelector('#contentDesktop_newMenuCtrl_lvMenuCats_hlCatName_' + i.toString());
            await page.click('#contentDesktop_newMenuCtrl_lvMenuCats_hlCatName_' + i.toString());
            console.log(page.url());

            await page.waitForSelector('.active_category_wrapper');
            menuCategories = await page.$$('.active_category_wrapper > tbody > tr > td.menu_items > div.groups_wrapper');
            menuItemGrps = await page.$$('.active_category_wrapper > tbody > tr > td.menu_items > div.items_wrapper');

            for (let k=0; k< menuCategories.length; k++){
                const mc = {};
                // await page.waitForNavigation({waitUntil: 'load'});
                const mcName = await menuCategories[k].$eval('h2', h2 => h2.innerText);
                console.log('menu category: ', mcName);
                mc['name'] = mcName;
                mc['description'] = '';
                mc['sortOrder'] = k + 1;
                mc['id'] = '0-' + k.toString();
                mc['mis'] = [];
                menuItems = await menuItemGrps[k].$$('a');
                console.log(menuItems.length, 'items');
                const miCount = 0;

                for(let j=0; j< menuItems.length; j++){

                    console.log('j: ', j);
                    const item = menuItems[j];
                    const mi = {}; 
                    
                    await page.waitForSelector('.active_category_wrapper');
                    const itemName = await item.$eval('h4', h4 => h4.innerText);
                    const price = await item.$eval('td.price', price => price.innerText);
                    console.log(itemName, price);
                    mi['name'] = itemName;
                    mi['category'] = '0-' + miCount.toString();
                    mi['sizeOptions'] = [];
                    
                    try{
                        const description = await item.$eval('p', p => p.innerText);
                        mi['description'] = description;
                    }catch(e){}   

                    item.click();

                    const pages = await browser.pages();
                    const popup = pages[pages.length - 1];

                    await page.waitForSelector('#contentDesktop_newMenuCtrl_MenuItemDetailsCtrl_rbtnlMenuItemSizes');
                    await page.waitForSelector('.sizes');
                    const sizeLabelText = await page.$eval('.sizes',allText => allText.innerText);
 
                    console.log('Size:');
                    console.log(sizeLabelText);

                    try{
                        await page.waitForSelector('#contentDesktop_newMenuCtrl_MenuItemDetailsCtrl_divChooseOption');
                        const optionText = await page.$eval('#contentDesktop_newMenuCtrl_MenuItemDetailsCtrl_divChooseOption', label => label.innerText);
                        console.log('Options:');
                        optionText.split('\n').map(ele => ele.split('\t').map(ele => console.log(ele)));  
                    }catch(e){}
                    
                    
                    await page.waitForSelector('input#contentDesktop_newMenuCtrl_MenuItemDetailsCtrl_btnCancel');
                    console.log('found the cancel button');
                    const cancelButton = await page.$('input#contentDesktop_newMenuCtrl_MenuItemDetailsCtrl_btnCancel');
                    await cancelButton.click();
                    console.log('button clicked');
                
                }
                console.log('\n');
            }
        }

        console.log('done');
        await browser.close();

    } catch(e){
        console.log('our error', e);
    }
})();

**What is the expected result?**
The result is supposed print details of each menu item (click on it).

**What happens instead?**
The details of all menu items are the same as the first menu item's. But if I add 'slowMo:100' in const browser = await pp.launch({ headless: true, args: ['--disable-dev-shm-usage'] }); it will print the correct result. But sometimes it will give errors:
our error Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (C:\Users\ni\Desktop\study\puppeteer\node_modules\puppeteer\lib\ElementHandle.js:86:13)
    at <anonymous>

Please help! Many Thanks

**Comment by aslushnikov** [comment]
This has been responded privately.
