### ISSUE TITLE
client-side server redirect with http-equiv="refresh"

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#3036]
**Description**
I get an error while using the response.text() function to get the response body. This happens only when I use the client-side server redirect with 'http-equiv="refresh" content=(>0)URL="https://example.com"'. The problem only occurs with a refresh content > 0, with 0 it's working.

**My environment:**
* Puppeteer version: "1.6.1"
* Platform / OS version: Windows 7
* URLs (if applicable): local
* Node.js version: v10.7.0

**What steps will reproduce the problem?**
1. create a html file (2. test02.html) with http-equiv="refresh" content=1URL="https://example.com"
2. create a nodejs app (app.js) with the following lines of code:

*app.js*

```
const puppeteer = require('puppeteer');
async function run() {
	try{
		let err = null;
		const url = 'https://example.com/test/test02.html';
		const browser = await puppeteer.launch({
			headless: true,
			ignoreHTTPSErrors : true,
			ignoreHTTPErrors : true
		});
		const page = await browser.newPage();
		page.on("error", error => {
			err = error;
		});
		page.on("pageerror", error => {
			err = error;
		});
		const response = await page.goto(url, {
			"timeout": 5000,
			"waitUntil": [ "load", "domcontentloaded", "networkidle0" ]
		});
		await page.waitFor(5000);
		if (!err)
		{
			let source = await response.text();
			console.log(source);
			browser.close();
		}
		else
		{
			console.log(err);
		}
	} catch (e) {
		console.log(e);
	}
}
```

*test02.html*:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Test file for meta refresh</title>
		<meta http-equiv="refresh"
        content="1;URL='https://example.com/test/test_02a.html'" />
	</head>
	<body>
		<h1>Test file for meta refresh</h1>
		<div id="testFileDescription">
			Test file that uses a meta-refresh with content set to 1.
		</div>
	</body>
</html>
```

**What is the expected result?**

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Test file for meta refresh</title>
	</head>
	<body>
		<h1>Test file for meta refresh</h1>
		<div id="testFileDescription">
			Destination file for a meta-refresh.
		</div>
	</body>
</html>
```

**What happens instead?**
{ Error: Protocol error (Network.getResponseBody): No resource with given identifier found
    at Promise (C:\Development\BugPuppeteer\node_modules\puppeteer\lib\Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Development\BugPuppeteer\node_modules\puppeteer\lib\Connection.js:201:12)
    at _contentPromise._bodyLoadedPromise.then (C:\Development\BugPuppeteer\node_modules\puppeteer\lib\NetworkManager.js:604:45)
  message:
   'Protocol error (Network.getResponseBody): No resource with given identifier found' }

**Comment by vitaliytv** [comment]
You can check if meta tag with >0 exist
`await page.$eval('meta[http-equiv=refresh]', a => a.content)`
and then open url
