### ISSUE TITLE
Not quite an issue just want to ask

### ISSUE THREAD

**Issue by Trother555** [puppeteer/puppeteer#3037]
Hello. I wanted to just try puppeteer in a simple use case. I wanted to go to example.com and fetch innerText from h1 tag. So I did:

```
h1 = (await page$x('//h1'))[0] //getting first h1 tag with xpath
console.log(h1.innerText)
```
I got undefined. I checked docs and it was said that $x returns an array of promisies for an ElementHandle. And also it was said that 'ElementHandle represents an in-page DOM element'. So if it is a DOM, why can't I just obtain its innerText property? Eventually I got it that a proper usage is like this:

```
h1 = (await page.$x('//h1'))[0]
const txt= await page.evaluate(hdl => hdl.innerText, h1)
console.log(txt)
```
And now I have only one question: why? I belive that there should be a good reason for this, but I couldn't figure it out just by skimming through the api docs and 'Getting Started' section.

**Comment by aslushnikov** [comment]
@Trother555 puppeteer lives out-of-process to chrome and drives it using Remote Debugging Protocol.
Puppeteer code is executed in node.js. Every time you write `page.evaluate`, Puppeteer uses protocol to go into the browser, execute your code there, and than take the value back to the node.js.

Now, node.js has no DOM, so Puppeteer provides `ElementHandle` objects - instances that live in node.js and point to the actual DOM nodes in browser. These handles could be "dereferenced" by passing them as arguments in `page.evaluate` - and that's what you did in your second example.

I hope it makes it more clear.
