### ISSUE TITLE
defaultViewport option does nothing

### ISSUE THREAD

**Issue by eedv** [puppeteer/puppeteer#3038]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.2
* Platform / OS version: Windows 7
* URLs (if applicable):
* Node.js version: 8.11.3

**What steps will reproduce the problem?**
Launch a browser with defaultViewport size option

_Please include code that reproduces the issue._
`browser = puppeteer.launch({
	headless: false,
	defaultViewport: {
		width: 600,
		height: 600
	}
});`

**What is the expected result?**
That the browser have the size configured in the options

**What happens instead?**
The browser viewport doesn't have the configured size

**Comment by vsemozhetbyt** [comment]
`defaultViewport` was [added recently](https://github.com/GoogleChrome/puppeteer/pull/3005) and 1.6.2 API does not support it: https://github.com/GoogleChrome/puppeteer/blob/v1.6.2/docs/api.md

**Comment by eedv** [comment]
Well, then, the documentation linked in the repository home is wrong. It's not pointing to 1.6.2 API

**Comment by aslushnikov** [comment]
> Well, then, the documentation linked in the repository home is wrong. It's not pointing to 1.6.2 API

Fair.

**Comment by ChrisRobston** [comment]
@vsemozhetbyt I am using 1.7.0 and it is not working

How to set viewport? So simple question have no answer.

**Comment by vsemozhetbyt** [comment]
Can you provide the details (code, screenshots)?

**Comment by ChrisRobston** [comment]
@vsemozhetbyt thanks for reaction. I noticed that the issue is window size. Viewport changes but window is not. I guess I need to set it separately?

**Comment by vsemozhetbyt** [comment]
Seems so)

**Comment by AionDev** [comment]
hey, any update on this?! I basically want to have a specific window size when it starts up.
