### ISSUE TITLE
Bot detection on some websites

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#3039]
If I normally browse the following websites, it doesn't throw any errors, however when I use the packed version with puppeteer, it throws following error,

![image](https://user-images.githubusercontent.com/8284972/43794753-15d43b46-9aa1-11e8-99d3-6f0fccc6eba0.png)

On the left, you see the provided version, on the right is the manually installed dev version. I tested several scripts on the website. I also tried browsing using `ignoreDefaultArgs: true`, manually and all available methods. 

I also changed IP few times between all tests, normal browser was successful every time, puppeteer failed every time if I used same IP twice. 

This might be an issue with the provided version or some flags that only this one uses. If it is leaving some footprint somehow, it might be a big issue for automation. 

This is a general issue and there have been issues related to this before (https://github.com/GoogleChrome/puppeteer/issues/927), however we have yet to find where it is actually leaking some data that it fails to run. 

Worth noting, when you open the page manually, first it loads this https://www.expertflyer.com/xprtflr.js, and checks for some predefined tests and then redirect based on response. Maybe we can extract some info from this. Like simple detection techniques.

PS: I am not trying to bypass bot detection, more like I am for finding what can be leaking that is preventing the puppeteer version. If this issue is duplicate, feel free to point me to original thread, I am sorry for not properly looking into that.

**Comment by grantstephens** [comment]
The header that is sent with puppeteer identifies it as headless chrome, which may be the reason it is blocked so easily. Try copying the headers from your non-headless browser.

**Comment by xprudhomme** [comment]
You might want to have a look at this:
https://intoli.com/blog/making-chrome-headless-undetectable/

**Comment by entrptaher** [comment]
@grantstephens @xprudhomme This happens only when using puppeteer. Look how I ignored default arguments provided by puppeteer and same happened. Probably something with puppeteer changes the behaviour and leaves some footprint even with it.

**Comment by entrptaher** [comment]
Closing this issue for now. Will reopen if faced problem in future or have better explanation.

**Comment by xprudhomme** [comment]
There might be something wrong with your script.

I did it successfully on the website you have provided (expertflyer.com), there is nothing wrong. Here is a screenshot taken directly from Puppeteer's rendered page:

![image](https://user-images.githubusercontent.com/329744/46571642-cd27db80-c978-11e8-8a9f-fde2d85ea3a1.png)

It would help if you show us your code. Mine is a simple as below:

```javascript
/* jshint node: true */
/* jshint globalstrict: true */
"use strict";

const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch({headless: false, ignoreHTTPSErrors: true});
    let page = await browser.newPage();
    

    let response = await page.goto('https://www.expertflyer.com/')
    .then((res)=>{
        console.log("Reached: load");
        return res;
    });

    console.log(` [Response] ${JSON.stringify(response.headers(), null, 2)}`);
    console.log(` [Response.status] ${response.status()}`);
})();
`

**Comment by entrptaher** [comment]
@xprudhomme I think there wasn;t anything wrong with my code, because I used same thing as you did above. Almost same code just going to the website. 

Maybe the version took care of the problem. My main mistake for this issue was not to provide version information clearly when needed.
