### ISSUE TITLE
Add memory heap snapshot API

### ISSUE THREAD

**Issue by robrbecker** [puppeteer/puppeteer#304]
# Problem
I see there is an API for starting and stoping a timeline recording `await page.tracing.start({path: 'trace.json'});` but I would like to request the ability to take a memory heap snapshot and the ability  to write expectations on the snapshot data.

My use case is roughly:
 - load a page
 - load a component & do stuff
 - remove the component
 - force a garbage collection (would love a method for this as well!)
 - take a heap snapshot
 - Verify that the component is not retained in memory somehow

This would be amazing to be able to have automated headless memory leak regression testing!

Maybe something like:
```
var heapsnap = await page.heap.snapshot('heap1.snapshot');
expect(!heapsnap.contains('SomeClassName'))
```

Bonus points for an API for the memory allocation timeline that you could query for the number of objects of a type added / removed during the timeline.

**Comment by aslushnikov** [comment]
@ak239 is claiming this!

**Comment by robbecker-wf** [comment]
![shocked](https://user-images.githubusercontent.com/6053699/31469722-1fd3c8f2-aea0-11e7-980f-a7a1c7f06553.gif)

**Comment by NicolasRannou** [comment]
Amazing - any snippet available to get quickly started on memory leak testing? So amazing I've been waiting for that for years!

**Comment by aslushnikov** [comment]
@NicolasRannou we have a small demo in the api docs: [`page.queryObjects`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagequeryobjectsprototypehandle)

**Comment by NicolasRannou** [comment]
Thanks a lot I missed that!

**Comment by georgelesica-wf** [comment]
I don't quite see how the referenced PR really resolved this issue. In order for the `page.queryObjects` method to be useful it seems I still need to know what I'm looking for. What I think this issue was asking for is an API to allow aggregation and possibly logging of *all* objects currently allocated, probably with metadata (prototype, and so on). Am I wrong?
