### ISSUE TITLE
Requests don't finish when request interception is enabled but there is no handler to call `request.continue`

### ISSUE THREAD

**Issue by dimfeld** [puppeteer/puppeteer#3040]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.2 
* Platform / OS version: OSX
* URLs (if applicable):
* Node.js version: 10.8

This also reproduces on the puppeteer playground at https://try-puppeteer.appspot.com/

**What steps will reproduce the problem?**

```
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.setRequestInterception(true);

try {
  await page.goto('https://example.com', { timeout: 5000 });
  console.log("Done!");
} catch(e) {
  console.log(e);
}

await browser.close();
```

**What is the expected result?**
The request finishes.

**What happens instead?**
The request stalls indefinitely. A simple handler like the following fixes it:

```
page.on('request', (req) => req.continue());
```

I encountered this when I enabled request interception and only used a `response` handler. Of course it's not a big deal to add a small request handler, so if this isn't easy to fix, then it would be great to get a line in the documentation mentioning that once request interception is enabled, a handler must call `req.continue()` for requests to finish.

**Comment by aslushnikov** [comment]
@dimfeld this is expected behavior; added a note to the docs.

**Comment by dimfeld** [comment]
Thanks!
