### ISSUE TITLE
Get the current url

### ISSUE THREAD

**Issue by KevinHe666** [puppeteer/puppeteer#3043]
I want get current url 
but PuppeteerApi page.url can't get the true url https://github.com/GoogleChrome/#puppeteer/issues/new==>https://github.com/GoogleChrome/

So I have a ideal:
`let checkUrl = await page.evaluate(() => location.href);`

**Comment by aslushnikov** [comment]
@KevinHe666 this should work just fine with puppeteer v1.6.2.
