### ISSUE TITLE
Need help : How to pass data from puppeteer page to React component while taking screenshot?

### ISSUE THREAD

**Issue by Gunner17** [puppeteer/puppeteer#3044]
I want to take a screenshot of a React component using puppeteer. I am using page.goto(host+":"+port+"/"+route_to_react_component) and page.content() to get the html content of the component. But I also want to pass some data from the server side to the component while taking the screenshot. Is there a complete example on how to pass data to my react component while taking screenshot using puppeteer and also how to access the passed data in the loaded page/react component? (I will use the passed data to populate some values in my component html)

**Comment by Janpot** [comment]
Maybe you can pass it through in the url? Like
```js
const { URL } = require('url');
const url = new URL(`${host}:${port}/${route_to_react_component}`);
url.searchParams.set('data', JSON.stringify(data));
page.goto(url.href)
```
and in the page
```js
const data = JSON.parse(new URL(location.href).searchParams.get('data'))
```
