### ISSUE TITLE
waitForSelector via XPath?

### ISSUE THREAD

**Issue by brandonros** [puppeteer/puppeteer#3046]
Is this possible? Should this be added?

**Comment by vsemozhetbyt** [comment]
What about [`page.waitForXPath(xpath[, options])`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforxpathxpath-options)?

**Comment by subrato29** [comment]
I tried to use the below code to for waitForXpath(), but it didn't work out. Can someone tell me what wrong I am doing and pls provide code for waitForXpath(), if it has
async function isExist(page,xpath) {
  const elements = await page.$x(xpath);
  await elements[0].waitForSelector()
}

**Comment by subrato29** [comment]
Tried with 
await page.waitForXpath("//input[@value='Finish']", { timeout: 8000 }), but getting the below issue 
TypeError: page.waitForXpath is not a function

**Comment by vsemozhetbyt** [comment]
@subrato29 Is it possible that you have an old puppeteer version without `page.waitForXPath()` support? Can you try to update?

**Comment by pdrArantes** [comment]
You typed it wrong, waitForXPath, not waitForXpath

**Comment by atul-gairola** [comment]
@subrato29 the 'p' in the Xpath has to be capital.
Change that to page.waitForXPath and it should work.
