### ISSUE TITLE
page.scroll()?

### ISSUE THREAD

**Issue by rcarmo** [puppeteer/puppeteer#305]
Hello there, 

In order to test image preloading, it is essential to be able to scroll the viewport somehow. Any plans for that?

**Comment by Garbee** [comment]
So if you query an element and [call hover](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlehover) on that it will scroll into view if needed. So IMO there should also be an API to simply scroll an element into view without triggering any other side effects.

**Comment by paulirish** [comment]
you can also 

```js
page.evaluate(_ => {
  window.scrollBy(0, window.innerHeight);
});
```

**Comment by rcarmo** [comment]
@garbee but right now I can't figure out how to iterate over all the images. see #303.
@paulirish thanks! I was currently messing with sending keyboard events, since I was aiming for a specific position... But it would be nice to be able to figure out how to iterate over DOM elements easily.

**Comment by JoelEinbinder** [comment]
We use [scrollIntoViewIfNeeded](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded). I think that this will solve your issue once we have `page.$$`

**Comment by jasan-s** [comment]
@JoelEinbinder can you elaborate what you mean by page.$$   is that integration of jquery?

**Comment by Garbee** [comment]
> can you elaborate what you mean by page.$$ is that integration of jquery?

We do nothing with jQuery internally. That is a page-level library. `page.$$` is one of the [public API](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector-1) methods puppeteer provides.

**Comment by rhinenoir** [comment]
```javasccipt
window.scrollBy(0, document.body.scrollHeight);
```
works better for me.

**Comment by visualxcode** [comment]
`const autoScroll = async (page) => {
  await page.evaluate(async () => {
      await new Promise((resolve, reject) => {
          var totalHeight = 0;
          var distance = 100;
          var timer = setInterval(() => {
              var scrollHeight = document.body.scrollHeight;
              window.scrollBy(0, distance);
              totalHeight += distance;

              if(totalHeight >= scrollHeight){
                  clearInterval(timer);
                  resolve();
              }
          }, 100);
      });
  });
}`

**Comment by visualxcode** [comment]
you can use it

```
const autoScroll = async (page) => {
  await page.evaluate(async () => {
    await new Promise((resolve, reject) => {
      let totalHeight = 0
      let distance = 100
      let timer = setInterval(() => {
        let scrollHeight = document.body.scrollHeight
        window.scrollBy(0, distance)
        totalHeight += distance
        if(totalHeight >= scrollHeight){
          clearInterval(timer)
          resolve()
        }
      }, 100)
    })
  })
}
```

**Comment by omeneses** [comment]
I solved this, editing the onReady.js file located at /engine_scripts/puppet/

The final .js file looks like this:

module.exports = async (page, scenario, vp)=>{
function wait (ms) {
return new Promise(resolve => setTimeout(() => resolve(), ms));
}

  await page.goto(scenario.url, {waitUntil: 'load'});
  // Get the height of the rendered page
  const bodyHandle = await page.$('body');
  const { height } = await bodyHandle.boundingBox();
  await bodyHandle.dispose();

  // Scroll one viewport at a time, pausing to let content load
  const viewportHeight = page.viewport().height;
  let viewportIncr = 0;
  while (viewportIncr + viewportHeight < height) {
        await page.evaluate(_viewportHeight => {
                                                window.scrollBy(0, _viewportHeight);
                                               }, viewportHeight);
        await wait(2000);
        viewportIncr = viewportIncr + viewportHeight;
  }

  // Scroll back to top
  await page.evaluate(_ => {
    window.scrollTo(0, 0);
  });

  // Some extra delay to let images load
  await wait(2000);
};

I found this solution at https://www.screenshotbin.com/blog/handling-lazy-loaded-webpages-puppeteer .

**Comment by chenxiaochun** [comment]
@visualxcode ,you got my code from here? https://github.com/chenxiaochun/blog/issues/38

**Comment by aadityataparia** [comment]
`page.$eval('#element', (el) => el.scrollIntoView())`

**Comment by pauloacosta** [comment]
Worked for me:

```
        let previousHeight;
        while (true) {
          try {
            previousHeight = await aliexpress.page.evaluate('document.body.scrollHeight')
            await aliexpress.page.evaluate('window.scrollTo(0, document.body.scrollHeight)')
            await aliexpress.page.waitForFunction(`document.body.scrollHeight > ${previousHeight}`)
          } catch (e) {
            console.log('Scroll End Page')
            break
          }
        }
```

**Comment by pauloacosta** [comment]
Worked for me:

```
        let previousHeight;
        while (true) {
          try {
            previousHeight = await page.evaluate('document.body.scrollHeight')
            await page.evaluate('window.scrollTo(0, document.body.scrollHeight)')
            await page.waitForFunction(`document.body.scrollHeight > ${previousHeight}`)
          } catch (e) {
            console.log('Scroll End Page')
            break
          }
        }
```
