### ISSUE TITLE
How to get text from a element ?

### ISSUE THREAD

**Issue by ArvindReddyC** [puppeteer/puppeteer#3051]
This might be a Obvious question but , Say i have  this element 
   `<span class="scrape">HelloPuppeteer</span>`
I use  
var  a  = page.$(".scrape");
Now , variable  a   holds a Element Handler returned from  page.$(".scrape");
My question  is how do i Now get this  text ("HelloPuppeteer" ) using    page.$(".scrape") is there any way  to Scrape the text  value of element using page.$(".scrape") ??

**Comment by vsemozhetbyt** [comment]
You can try this:
```js
    const element = await page.$(".scrape");
    const text = await page.evaluate(element => element.textContent, element);
```
or this:
```js
    const element = await page.$(".scrape");
    const text = await (await element.getProperty('textContent')).jsonValue();
```

**Comment by ArvindReddyC** [comment]
Now say I Have a  input element ,
`<input class="form-control" type="textbox" name="Month" value="6" id="april">`
how do I send/set a value to this Element  ? Using page.$("#april"); ?

**Comment by vsemozhetbyt** [comment]
Maybe this way:

For DOM element properties
```js
const element = await page.$("#april");
await page.evaluate(element => { element.value = 7; }, element);
```
For HTML attributes:
```js
const element = await page.$("#april");
await page.evaluate(element => { element.setAttribute('value', 7); }, element);
```

**Comment by flyingsky** [comment]
why not `page.type('#april', "7")`?

**Comment by vsemozhetbyt** [comment]
@flyingsky If only `value`needs to be changed, then why not) I meant a more general approach for any property or attribute.

**Comment by Hiroki111** [comment]
> const element = await page.$(".scrape"); 
> const text = await page.evaluate(element => element.textContent, element);

I'm not sure if this approach works. 
(I've actually tried it, but it doesn't)

A function prepended with `await` kerword returns a `Promise` object, doesn't it?
So, I think that the `text` variable above will be like...

    text.then((result) => { /* what you want to do */});

**Comment by rostyk-kanafotskyy** [comment]
> Now say I Have a input element ,
> `<input class="form-control" type="textbox" name="Month" value="6" id="april">`
> how do I send/set a value to this Element ? Using page.$("#april"); ?

Try this
``` js
await page.$eval("#april", el => el.value = '7');
```

**Comment by varund-active** [comment]
fdg

**Comment by StebanDev** [comment]
> You can try this:
> 
> ```js
>     const element = await page.$(".scrape");
>     const text = await page.evaluate(element => element.textContent, element);
> ```
> 
> or this:
> 
> ```js
>     const element = await page.$(".scrape");
>     const text = await (await element.getProperty('textContent')).jsonValue();
> ```

the shortest way for me:
```js
const element = await page.$eval('.scrape', el => el.textContent);
```

**Comment by prprprus** [comment]
```node
const elm = await page.$(".scrape");
const text = await page.evaluate(elm => elm.textContent, elm[0]);
console.log(text);
```

**Comment by dandv** [comment]
For a single DOM node, `.textContent` works fine, but how can I get the combined text contents of all children of the element, like [`.text()` in jQuery](https://api.jquery.com/text/)?
[ElementHandle](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-class-elementhandle) doesn't have a `.content()` method like `Page`.

**Comment by ozcanyarimdunya** [comment]
You can try this if you want inner text
```javascript
const element = await page.$(".scrape");
const text = await page.evaluate(element => element.innerText, element);
```

**Comment by tolumide-ng** [comment]
I can't be the only one unable to get `innerText` in 2020 right?

**Comment by CyberT33N** [comment]
Based on the answers from above here is a 1 liner:
```javascript
let videoDuration = await page.evaluate(element => element.textContent, await page.$(".ytp-time-duration") );
```

For more complex stuff you may use Puppeteer in combination with cheerio which is awesome for scrapping.. As example:

```javascript
let css = await page.evaluate(() => document.querySelector('body').outerHTML);
let $ = cheerio.load(css);
let videoDisslikes = $(css).find('#menu-container').find('#top-level-buttons > ytd-toggle-button-renderer:nth-child(2)').find('#text').text();
```

However with cheerio you always must get again new body when the website has changed text and stuff and this sucks in multiple cases, while puppeteer always directly gets the dom content live
