### ISSUE TITLE
Add option to set PDF metadata

### ISSUE THREAD

**Issue by akaleeroy** [puppeteer/puppeteer#3054]
This is an enhancement suggestion for adding the ability to **set PDF metadata when exporting** with [page.pdf()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions)

Something like what [PDFKit](https://github.com/foliojs/pdfkit/) does: [foliojs/pdfkit Getting started – Setting document metadata](https://github.com/foliojs/pdfkit/blob/master/docs/getting_started.coffee.md#setting-document-metadata)

**Comment by yashha** [comment]
While the chomium api doesn't support this yet, I would suggest to use the _exiftool_ to add the data.
https://github.com/Sobesednik/node-exiftool#readme

What do you think? Should we use this to implement an option for the pdf function?
e.g. meta {
 title: string,
 ...
}

**Comment by aslushnikov** [comment]
@akaleeroy Puppeteer doesn't bring much on itself around PDF generation; all we have comes from Headless Chromium project.

- if you want Chromium to generate PDF metadata firsthand, I'd recommend filing this feature request over to https://crbug.com/new
- meanwhile, using third-party solutions on top of Puppeteer seem to be a good workaround

Hope this helps

**Comment by yashha** [comment]
Ok thanks
https://bugs.chromium.org/p/chromium/issues/detail?id=907249

**Comment by TomasHubelbauer** [comment]
For anyone coming across this issue in hopes of seeing a way to set the values of the creation and modification date and time stamps in the PDFs so that the generated PDFs are deterministic given the same HTML, I have settled on patching the PDF buffer and zeroing those fields:

```
await page.goto('https://news.ycombinator.com', { waitUntil: 'networkidle0' });
await page.waitForFunction(() => [...document.images].every(i => i.complete));
const path = join(__dirname, 'news.ycombinator.com.pdf');
await page.pdf({ path });

// Wipe out date and time stamp ranges to make the PDFs deterministic
const buffer = await fs.readFile(path);
for (const offset of [97, 98, 99, 100, 132, 133, 134, 135]) {
  buffer[offset] = 0;
}

await fs.writeFile(path, buffer);
```

The rest of the PDF seems to be deterministic. It is possible the Chromium version also needs to be patched, it might get embedded in the PDF in a creator field, I have not checked that.
