### ISSUE TITLE
How to wait until all network activity on a particular page has stopped before continuing?

### ISSUE THREAD

**Issue by saadahmad03** [puppeteer/puppeteer#3063]
I was wondering if there is a way to wait until all network activity has become idle (without navigation, refreshing, or going to a new page) as the application I am writing tests for requires all API requests to complete first before some buttons become clickable etc.

I am currently doing stuff like `await page.waitFor(10000)` and so on but I don't think this is the best solution. 

Is there any way I can write code that would act something like this:

`await page.waitFor({ waitUntil: networkidle })`

Any insight would be appreciated, thanks so much in advance!

**Comment by rogervanwile** [comment]
Hi @saadahmad03 ,

there is a options argument by calling `page.goto`. In these options you can set `waitUntil` to `networkidle2`. 

`await page.goto(url, {waitUntil: 'networkidle2'});`

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

**Comment by saadahmad03** [comment]
Hi @rogervanwile, thank you for your response. I was actually wondering if there was an option to do 
`{ waitUntil: 'networkidle2 }` **without** having to go to a new page, and to perform this operation on the current page.

**Comment by aslushnikov** [comment]
@saadahmad03 thanks for the clarification. This has been requested for a while already; filed a designated bug report for it: #3083. Feel free to upvote.

**Comment by ralyodio** [comment]
can i do this with `    await page.mouse.click(pos.x+pos.width/2, pos.y+pos.height/2);`?
