### ISSUE TITLE
Document how to debug `Protocol error (Runtime.callFunctionOn): Target closed.`

### ISSUE THREAD

**Issue by stereobooster** [puppeteer/puppeteer#3064]
The issue: some JS code in the page causes crash of the page in the browser. `Target closed` is not enough information, is there some debug mode to see why page crashed?

Related: users of react-snap periodically get this error https://github.com/stereobooster/react-snap/issues/240

**Comment by AnthonyLzq** [comment]
Still a problem almost 4 years later.
