### ISSUE TITLE
Could it be possible to apply semver to exports?

### ISSUE THREAD

**Issue by nesk** [puppeteer/puppeteer#3067]
I'm maintaining [PuPHPeteer](https://github.com/nesk/puphpeteer), a bridge to use Puppeteer in PHP.

Sometimes I need to check if an object is an instance of `Browser` or `Page`. It works great but I had some issues in the past with some changements you made to your internal API, [here's an example](https://github.com/GoogleChrome/puppeteer/commit/2e0007669da4676bd9dd88e09e3a2eff8fcfdb30#diff-b1397100d3965ca1373667a75e2c5f94L1197):

```diff
- module.exports = Page;
+ module.exports = {Page};
```

Could it be possible to apply a semver treatment on those exports? I know this is not a public API but it really is limitating, currently my project can only handle a specific version of Puppeteer because the exports can break at any moment.

Thank you 🙂

**Comment by aslushnikov** [comment]
@nesk sorry for the long reply. Can you elaborate more on this - why would you need to check if object is Page or Browser?

**Comment by nesk** [comment]
Actually, I no longer need to check for the `Browser` objects. However, I check for `Page` objects to listen for `console` events, so I can pass them to the PHP logger.

Now that I'm thinking about it, if this is a real problem for you to apply semver to the exports, I may check the type of the objects by reading the `.constructor.name` property.

**Comment by aslushnikov** [comment]
> Now that I'm thinking about it, if this is a real problem for you to apply semver to the exports, I may check the type of the objects by reading the .constructor.name property.

`constructor.name` sounds good.

We might eventually introduce a nicer API for extensibility purposes that would help you:
```js
const {Page, Browser} = require('puppeteer/Classes');
Page.prototype.myMethod = () => {
  // ...
}
```

But that will probably happen after we drop node6 support.

**Comment by nesk** [comment]
Great, thank you for your help. 🙂
