### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by almostkareem** [puppeteer/puppeteer#3073]
Hello this is my code to watch for a redirection then get the URL from location.href, this works sometimes but crashes most of the time saying: 

**node:2644) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/var/scrappers/x/node_modules/puppeteer/lib/ExecutionContext.js:136:15)**

` const browser = await puppeteer.launch({ headless: true , args: ['--no-sandbox', '--disable-setuid-sandbox']});
    
    const page = await browser.newPage();
   
    await page.goto(url, {waitUntil: 'networkidle2'});
    await page.waitForNavigation({waitUntil: 'domcontentloaded'});
    await page.waitForFunction('document.title.length != 16');
 
    const result = await page.evaluate(() => {
        return window.location.href;
    });
    
    browser.close();

    return result;`

Thanks

**Comment by takahiro-saeki** [comment]
same here

**Comment by xprudhomme** [comment]
Looks like you forgot to add await before browser.close(), such as:
await browser.close(), otherwise there are great changes it gets executed before the script ends..
