### ISSUE TITLE
page.$$eval says evaluates in browser context, yet childNodes just shows empty hash

### ISSUE THREAD

**Issue by JohnMerlino2** [puppeteer/puppeteer#3074]
In browser, there is this:

 < span id = "lbl_party" style = "color:DarkBlue;" >
 < h4 >DEFENDANT< /h4 >
 TALLENT, RYAN WILLIAM
 < /span >

When I do this:

var defendant = await page.$$eval('#lbl_party', (span) => span[0].innerHTML );

It correctly gives me this:

< h4 >DEFENDANT< /h4 >
 TALLENT, RYAN WILLIAM

However, when I try to get the second Node:

var defendant = await page.$$eval('#lbl_party', (span) => span[0].childNodes[1] );

It gives me this:

{}

Why does it not give me the data in the second node of the span?

**Comment by vsemozhetbyt** [comment]
`page.$$eval()` resolves in only serializable values. In the first case, `innerHTML` is a string and is serializable. In the second case, `childNodes[1]` is a DOM node and is not serializable, so the function returns an empty object.
