### ISSUE TITLE
./chrome: /lib64/libnss3.so: version `NSS_3.22' not found (required by ./chrome)

### ISSUE THREAD

**Issue by MrTurnRight** [puppeteer/puppeteer#3080]
### Steps to reproduce

**Tell us about your environment:** 

* Puppeteer version: 1.6.0
* Platform / OS version: self-defined centos
* URLs (if applicable):
* Node.js version: 8.11

**What steps will reproduce the problem?**
cant launch chrome
_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
For some reason, we cant update NSS(nss-3.16.2.3-2.el7_0.x86_64)

**What happens instead?**
fail to launch chrome,
/lib64/libnss3.so: version `NSS_3.22' not found

**Comment by Tidyzq** [comment]
i have the same problem, how did you fix it?

**Comment by lefengyang** [comment]
same problem, had you fix?

**Comment by wumingli** [comment]
same problem, had you fix?

**Comment by wumingli** [comment]
same problem, how did you fix it?

**Comment by TimShilov** [comment]
Running `yum update nss` worked for me.

**Comment by phong-hp** [comment]
@TimShilov Thanks. yum update nss worked for me.

**Comment by chuans** [comment]
> Running `yum update nss` worked for me.

why，Prompt me to install successfully, but still invalid
centos7.2 
node 8.11.3
puppeteer  1.14.0
please help

**Comment by vipinpanwar** [comment]
> Running `yum update nss` worked for me.

Thanks , You make my day.

**Comment by vipinpanwar** [comment]
> Running `yum update nss` worked for me.

Thanks, You make my day.
