### ISSUE TITLE
Scraping  a Page

### ISSUE THREAD

**Issue by ArvindReddyC** [puppeteer/puppeteer#3082]
the page i want to Scrape has  "View Source" different than "Inspect Element"  , the page adds Dynamic html via javascript/jquery , now is there a way to get the page's html  which includes static html as well as dynamic html generated from jquery for Scraping ?? how do i Include an Option if Any , So i get the Dynamic Html too??

**Comment by CollegeFellow** [comment]
Did you try using the `waitFor` as shown in the [docs](https://github.com/GoogleChrome/puppeteer/blob/v1.7.0/docs/api.md#pagewaitforselectororfunctionortimeout-options-args)

**Comment by ArvindReddyC** [comment]
i Could try that , but then the Dynamic html is Generated Based on  a Click  , So Will `waitFor("#Some_Selector")`  Work ? I mean  Will `waitFor("#Some_Selector")` Process JavaScript and then Search For the Matching Selector ??

**Comment by xprudhomme** [comment]
To get the final HTML (with dynamic contents added), simply use page.content() once everything is fully loaded.

To get the initial static HTML, you can intercept the main page HTTP response, and get the response contents from there: 

```javascript
const responseHandler = async (response) => {

    const url = response.url();

    if(!/whatever_url_regex\.html/i.test(url)) {
        return;
    }

    console.log(` [responseHandler] Got response for: ${url}`);

    const htmldata = await response.text();
};

await page.on('response', responseHandler);
```

**Comment by Pmarouga** [comment]
I need the final HTML, with page.content() I get the initial HTML(contains js that I dont want to have). Any ideas why this is happening?
