### ISSUE TITLE
Fetching content seperated by br and store items in seperate variables

### ISSUE THREAD

**Issue by markusrempfer** [puppeteer/puppeteer#3087]
I'm using node.js and puppeteer to get some data. How can I save the content of an element (which is divided by line br) in two seperate variables?

That's the HTML I'm looking at:

	<table summary="">
		<tbody>
			<tr nowrap="nowrap" valign="top" align="left">
				<td nowrap="nowrap">2018-08-14<br>16:35:41</td>
			</tr>
		</tbody>
	</table>

I'm getting the content of the td like this (app.js):

	let tableCell04;
	let accepted;

	tableCell04 = await page.$( 'body div table tr td' );
	accepted = await page.evaluate( tableCell04 => tableCell04.innerText, tableCell04 );

	console.log('Accepted: '+accepted);

The output in console is:

	Accepted: 2018-08-14
	16:35:41
	
But what I would like to have is storing the content which is seperated by the <br> in seperate variables ... so I get sth like this:

	Accepted_date: 2018-08-14
	Accepted_time: 16:35:41
	
How can I accomplish this?

**Comment by vsemozhetbyt** [comment]
Maybe this way?
```js
let [date, time] = await page.evaluate(
  tableCell04 => tableCell04.innerText.split('\n'),
  tableCell04
);
```
