### ISSUE TITLE
Is there a way to measure page performance?

### ISSUE THREAD

**Issue by inikulin** [puppeteer/puppeteer#309]
Is there a way to get numbers for time before `DOMContentLoaded` and `load` events? First paint time would be nice as well. I see that there is `page.tracing` API, but it produces Chrome trace file. For my task I need only two numbers mentioned above and in format that I can easily parse (e.g. JSON) and without necessity for disk I/O. Something like `page.getMetrics() -> Promise<{DOMContentLoadedTime, loadTime}>`.

**Comment by ivanvanderbyl** [comment]
@inikulin You could use `evaluate` and call `window.performance.timing`.

**Comment by a1ph** [comment]
There is also [Performance.getMetrics](https://chromedevtools.github.io/devtools-protocol/tot/Performance/#method-getMetrics)

For now it is accessible with something like:
```javascript
await page._client.send('Performance.enable');
const response = await page._client.send('Performance.getMetrics');
```
There should be a more convenient API added later.

**Comment by inikulin** [comment]
Great, thank you for replies, that works for me. I guess I can keep it open as ticket for more convenient API that others can track?

**Comment by ebidel** [comment]
Not sure `Performance.getMetrics` gives you the metrics you're after, but @ivanvanderbyl is spot on. Then add firstpaint like this:

```js
const perf = await page.evaluate(_ => {
  return Object.assign({
    firstPaint: chrome.loadTimes().firstPaintTime * 1000 - performance.timing.navigationStart
  }, window.performance.timing); 
});
```

**Comment by pavelfeldman** [comment]
@a1ph is working on delivering runtime / performance / memory stats to the puppeteer. They will be more complete and more accurate than those available via performance.timing.

**Comment by inikulin** [comment]
Just in case if someone will encounter this problem as well: `chrome` object from https://github.com/GoogleChrome/puppeteer/issues/309#issuecomment-322943877 is not available in headless mode.

**Comment by daliborgogic** [comment]
If you need `chrome` set `headless` to `false` 
```javascript
const browser = await headless.launch({
  headless: false
})
```

**Comment by UnscientificMisaka** [comment]
@ebidel I cant' get `window.performance` in `page.evaluate`
```
await page.goto('xxx.com')  
const pref = await page.evaluate(() => {  
  return Object.assign({  
    firstPaint: chrome.loadTimes().firstPaintTime * 1000 - performance.timing.navigationStart  
  }, window.performance.timing)  
})

```
`pref` is an empty Object and when I console `window`, it does not  have a property called `performance`

**Comment by pavelfeldman** [comment]
Someone mean defined `window.performance.timing` as non-enumerable...

```js
const timing = await page.evaluate(() => {
  const result = {};
  for (const key of Object.keys(window.performance.timing.__proto__))
    result[key] = window.performance.timing[key];
  return result;
});
```

@ak239 could you look into straightening performance.timing API the way you fixed console?

**Comment by pavelfeldman** [comment]
@a1ph: let's make sure `chrome.loadTimes()` is not required for getting this kind of perf metrics.

**Comment by a1ph** [comment]
@pavelfeldman The plan is to add a wrapper into Page that invokes
```js
await this._client.send('Performance.enable');
await this._client.send('Performance.getMetrics');
```

**Comment by pavelfeldman** [comment]
@a1ph: I meant that there was a clash between the `chrome.loadTimes()` and `performance.timing` apis and I was hoping we could fix it. Exposing those times via Performance.* also sounds good, but we need both.

**Comment by surfmuggle** [comment]
I tried to get this script running on [try-puppeteer.appspot.com](https://try-puppeteer.appspot.com/) but get this _error Error running your code. 

 * Error: Evaluation failed: ReferenceError: chrome is not defined at _ (<anonymous>:3:17_).
 * after replacing _chrome_ with _browser_: Error running your code. Error: Evaluation failed: ReferenceError: browser is not defined at _ (<anonymous>:3:17)
 
```

const browser = await puppeteer.launch();

const page = await browser.newPage();
await page._client.send('Performance.enable');
// const response = await page._client.send('Performance.getMetrics');
await page.goto('http://www.pixelpiz.de/');

// is (_ => { still the recommended syntax? 
const perf = await page.evaluate(_ => {
  return Object.assign({
    firstPaint: chrome.loadTimes().firstPaintTime * 1000 - performance.timing.navigationStart
  }, window.performance.timing); 
});
// above i replaced chrome.loadTimes with browser.loadTimes as well but this gave the same error

console.log(perf);
console.log("  --- was perf");
console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();

```

 - How can i fix the error?
 - How can i use [feature #939](https://github.com/GoogleChrome/puppeteer/pull/939)  
 - Is #939 already part of try-puppeteer v0.13.0 version?

**Comment by ebidel** [comment]
@surfmuggle `page.metrics()` is the API call in 0.13.0: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagemetrics

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('http://www.pixelpiz.de/');
const perf = await page.metrics();
console.log(JSON.stringify(perf));
await browser.close();
``

Note: 
`chrome.loadTimes()` is being [deprecated in chrome 64](https://www.chromestatus.com/features/5637885046816768). It looks like it's not defined in headless mode.

**Comment by therazor** [comment]
`page.metrics()` returns a completely different set of metrics compared to `window.performance.timing` though.

Are they meant to be complementary?

**Comment by ebidel** [comment]
@therazor, `page.metrics()` has limited data atm. You can use `performance.timing` for everything else. https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated is a new article on how to migrate from `chrome.loadTimes()` to `performance.timing`. It also covers the new paint entry types in `PerformanceEntry`. 

Example of getting paint times:

```js
  const paints = await page.evaluate(_ => {
    const result = {};
    performance.getEntriesByType('paint').map(entry => {
      result[entry.name] = entry.startTime;
    });
    return result;
  });

  for (const [key, val] of Object.entries(paints)) {
    console.log(`${key}: ${Math.round(val)}ms`);
  }
```

**Comment by twistedpair** [comment]
Do these metrics include information like CPU consumption for the given tab?

**Comment by b4dnewz** [comment]
Does anyone know which is the simplest (maybe built-in) way to get **DomContentLoaded** and **Load** performance metrics?

![image](https://user-images.githubusercontent.com/29862596/40372247-934020ee-5de4-11e8-9869-5b2af7d2e0f6.png)

Actually I've tried these two methods, the first is obtaining **DomContentLoaded** by sum of `performance.timing` values.
```js
metrics.dnsTime = timing.domainLookupEnd - timing.domainLookupStart;
metrics.tcpTime = timing.connectEnd - timing.connectStart;
metrics.waitingTime = timing.responseStart - timing.requestStart;
metrics.contentTime = timing.responseEnd - timing.responseStart;
metrics.networkTime = (metrics.dnsTime + metrics.tcpTime + metrics.waitingTime + metrics.contentTime);
```
The other one is by listening at page events once and set a variable:

```js
const start = performance.now();
const loadTime = 0;
page.once('load', () => {
    loadTime = performance.now() - start;
});
await page.goto(url, {waitUntil: 'load'});
```

Shouldn't this values be included in the page metrics or have an API for getting them?
`Requests number, Bytes transferred, Total time to load, DOMContentLoad and Load time`

**Comment by liyunsheng** [comment]
@b4dnewz 
```
const perfEntries = JSON.parse(
    await page.evaluate(() => JSON.stringify(performance.getEntries()))
);
```
Then you can calculate time/size.
But faild request is not in the entryList, see #417

**Comment by jeroenvermeulen** [comment]
This is dumping all useful info I have found:
```js
const puppeteer = require('puppeteer');

async function run() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page._client.send('Performance.enable');
  await page.goto( "https://www.github.com/", { waitUntil: 'networkidle2' } );

  console.log("\n==== performance.getEntries() ====\n");
  console.log( await page.evaluate( () => JSON.stringify(performance.getEntries(), null, "  ") ) );

  console.log("\n==== performance.toJSON() ====\n");
  console.log( await page.evaluate( () => JSON.stringify(performance.toJSON(), null, "  ") ) );

  console.log("\n==== page.metrics() ====\n");
  const perf = await page.metrics();
  console.log( JSON.stringify(perf, null, "  ") );

  console.log("\n==== Devtools: Performance.getMetrics ====\n");
  let performanceMetrics = await page._client.send('Performance.getMetrics');
  console.log( performanceMetrics.metrics );

  browser.close();
}

run();
```

**Comment by lloydjatkinson** [comment]
Is it possible to get the TTFB?

**Comment by jeroenvermeulen** [comment]
I would advise to use `performance.toJSON()` from my example above.
From the this you can use `timing.responseStart`

**Comment by TCPPERFUSER** [comment]
Hi All,
    I've been playing around with capturing the performance metrics mentioned and recommendations from this ticket and I have one question. Does it have to be a page.goto to be able to get the metrics? how about with page.click() ?
    Per my observation it doesn't work with page.click()

**Comment by Moriphete** [comment]
So when it's pushed down or written over where d          oes the original end up, 


osi  andriod / i device iso

**Comment by Moriphete** [comment]
> I tried to get this script running on [try-puppeteer.appspot.com](https://try-puppeteer.appspot.com/) but get this _error Error running your code. 
> 
>  * Error: Evaluation failed: ReferenceError: chrome is not defined at _ (<anonymous>:3:17).
>  * after replacing chromewith browser: Error running your code. Error: Evaluation failed: ReferenceError: browser is not defined at (< unauthorized >:<3F7mRWoGf3jKXTCXutYC75fCm5FVXcYkxx>:<3:17)
>  
> ```
> 
> const browser = await puppeteer.launch();
> 
> const page = await browser.newPage();
> await page._client.send('Performance.enable');
> // const response = await page._client.send('Performance.getMetrics');
> await page.goto('http://www.pixelpiz.de/');
> 
> // is ( => { still the recommended syntax? 
> const perf = await page.evaluate(_ => {
>   return Object.assign({
>     firstPaint: chrome.loadTimes().firstPaintTime * 1000 - performance.timing.navigationStart
>   }, window.performance.timing); 
> })));}
> // above i replaced chrome.loadTimes with browser.loadTimes as well but this gave the same error
> 
> console.log(perf);
> console.log("  --- was perf");
> console.log(await page.content());
> await page.screenshot({path: 'screenshot.png'});
> 
> await browser.close();
> 
> ```
> 
>  - How can i fix the error? 
>  - How can i use [feature #939](https://github.com/GoogleChrome/puppeteer/pull/939)  
>  - Is #939 already part of try-puppeteer v0.13.0 version?


Placing an origin simple cartesian cordinates as for point of set located instead of anonymous.
Making sure all paths ( Bars brackets etc. ) are closed distinguished. Or it all
Including stepped on and over data still gets timed.
Use fall out 7
