### ISSUE TITLE
Referrer should be parameter, not extra header

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#3090]
If you look at this line, we trying to get referrer from `extraHTTPHeaders`:
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L565

So, at this code example I forced to clear extra headers for proper resources loading:
```js
await page.setExtraHTTPHeaders({
  referer: 'https://example.com/'
});

await page.goto('https://github.com/');

await page.setExtraHTTPHeaders({});
```

This is really bad way to set referrer, because **even in CDP** referrer is specified as a parameter, not header. This is not even funny!
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L601

While I'm trying to clear headers after navigation with empty object, page will load resources (like CSS and scripts, images) with a **wrong** referrer!

Try to set extra header `referer` on your page and load image, and you will see amazing wrong referer:

![ref](https://user-images.githubusercontent.com/31924884/44154647-e0e6e5f0-a0b3-11e8-9226-e6be3911ddce.png)

So wee need smth like this:
* referrer as a optional parameter at `goto`, in this case method will ignore headers `referer` check
* referrer as a parameter only (best way)

Now I'm forced to rewrite `goto` method a little, can we fix it?

**Comment by aslushnikov** [comment]
Fair. We should add referer to the navigation options and make it override the one
specified via extra http headers.

```js
await page.goto('https://google.com', {
  referer: 'https://example.com'
});
```
