### ISSUE TITLE
Error validating waiting for selector

### ISSUE THREAD

**Issue by AlonsoK28** [puppeteer/puppeteer#3091]
Puppeteer version: 5.6.0
Platform / OS version: Windows 10 Pro
Node.js version: v8.11.1

I'm trying to validate whether or not there is a selector through the loading time of a web using the function `"page.waitForSelector"`.

These are the steps I'm taking with the `"page.waitForSelector"` function.

```
var selector = { USUARIO_SELECTOR: ".usuario",
CONTRASEÑA_SELECTOR: ".pwd",
AR_ENTRAR: "#login" }

var constantes = {VINCULO:"localhost:8080/app",
USUARIO: "admin",
CONTRASEÑA: "12345"}

const page = await browser.newPage();

    iniciarSesion: function (page, selector, constantes){
        (async () => {
            console.log("INFO - Solicitando acceso a: " + constantes.VINCULO);
            await page.goto(constantes.VINCULO);
            console.log("INFO - Acceso a: " + constantes.VINCULO);
            await page.type(selector.USUARIO_SELECTOR, constantes.USUARIO);
            console.log("ACCION - Se capturo el usuario: " + constantes.USUARIO);
            await page.type(selector.CONTRASEÑA_SELECTOR, constantes.CONTRASEÑA);
            console.log("ACCION - Se capturo la contraseña: " + constantes.CONTRASEÑA);
            await page.waitForSelector(selector.INGRESAR_SELECTOR).then(() =>
                page.click(selector.AR_ENTRAR)
            );
            console.log("INFO - Inicio de sesion exitoso"); 
        })();
    }

iniciarSesion(page, selector, constantes);
```

How can I validate the result of the `"page.waitForSelector"` function, whether the selector exists or not when before the "timeout" is reached and then can an action be determined by the program?

I am receiving the following error message when the selector does not exist.

```
Error: waiting for selector "table # situations> tbody> tr: nth-last-child (2)> td: nth-child (3)> h3> a> b" failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (Z: \ Documents \ AR-puppeter \ node_modules \ puppeteer \ lib \ FrameManager.js: 845: 60)
    at ontimeout (timers.js: 482: 11)
    at tryOnTimeout (timers.js: 317: 5)
    at Timer.listOnTimeout (timers.js: 277: 5)
```

**Comment by Lotafak** [comment]
Hello!

If I understand your question correctly, you can use function `page.$eval` for example.
```
page.$eval(selector, el => /* check if element exists/is visible/whatever you want */)
```

In our project we implemented function named `visible`, which checks the visibility of an element (and if the element exists in the first place). It's implementation:
```
return this.evaluate((selector) => {
    const elem = document.querySelector(selector);
    return elem && (elem.offsetWidth > 0 && elem.offsetHeight > 0);
  }, selectorArg);
```

You can of course use `$eval` here as well

**Comment by aslushnikov** [comment]
Additionally, since puppeteer v1.7.0 you can check for Timeout error specifically, see [Error Handling](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-error-handling) section.

**Comment by nigzht** [comment]
I'd love to see more added to the error handling section, i will see if i can contribute!
