### ISSUE TITLE
 How to download, access and process a xml file and the content

### ISSUE THREAD

**Issue by markusrempfer** [puppeteer/puppeteer#3093]
Node.js puppeteer - How do I download, access and process a xml file and the content in puppeteer?

When clicking on a link like:

await page.evaluate(() => {
    document.querySelector('#datagrid > div > a:nth-child(2)').click();
});

... I can download a xml file looking like this:

XML file:

<table>
    <row>
        <column>Titel01</column>
        <column>Titel02</column>
        <column>Titel03</column>
        <column>Titel04</column>
        <column>Titel05</column>
        <column>Titel06</column>
        <column>Titel07</column>
        <column>Titel08</column>
        <column>Titel09</column>
        <column>Titel10</column>
        <column>Titel11</column>
        <column>Titel12</column>
        <column>Titel13</column>
        <column>Titel14</column>
        <column>Titel15</column>
        <column>Titel16</column>
    </row>
    <row>
        <column>Value01</column>
        <column/>
        <column>Value03</column>
        <column>Value04</column>
        <column>Value05</column>
        <column>Value06</column>
        <column>Value07</column>
        <column>Value08</column>
        <column>Value09</column>
        <column>Value10</column>
        <column>Value11</column>
        <column>Value12</column>
        <column>Value13</column>
        <column>Value14</column>
        <column>Value15</column>
        <column>Value16</column>
    </row>
    ... // starting possible more rows
    <row>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column/>
        <column>Value15B</column>
        <column>Value16B</column>
    </row>
    ... // possible 
</table>  

How can I access the values and store it in variables to further process it in puppeteer?

SO: https://stackoverflow.com/questions/51875386/node-js-puppeteer-downloading-accessing-a-xml-file-and-process-the-content

**Comment by aslushnikov** [comment]
The downloads are yet to be supported in Puppeteer API; see #299
