### ISSUE TITLE
Feature request: Add 'clear' option to the .type() function

### ISSUE THREAD

**Issue by HRK44** [puppeteer/puppeteer#3094]
Function concerned : ``.type`` - [api here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagetypeselector-text-options)

Basically, add a boolean ``clear`` into the options so we specify if we want to clear the field before typing.

`page.type('#myinput', 'toto', {clear: true})`

This would clear any existing input into ``#myinput`` then it would type ``toto``.

**Comment by aslushnikov** [comment]
As per discussion with @JoelEinbinder, we should allow to select elements with `page.setSelection`.

Once it's done, this will be addressed like this:
```js
await page.setSelection('#myinput');
await page.keyboard.type('toto')
```

We might come with a sugar for this
```js
await page.type('#myinput', 'toto', {preselect: true});
```

**Comment by HRK44** [comment]
@JoelEinbinder @aslushnikov ``setSelection`` might be interesting in some use cases, but what the user/dev wants in the end is to clear the field - if it's done through CTRL+backspace, CTRL+A (selection)+typing or direct modification of the HTML element, that's just implementation details.

I was thinking of something simple like in protractor : [.clear()](https://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.clear)

**Comment by aslushnikov** [comment]
@HRK44 `page.clear()` is reasonable, thanks.

**Comment by samfultonschool** [comment]
I just made my own little function. Pretty easy to use.
`
async function clear(page, selector) {
  await page.evaluate(selector => {
    document.querySelector(selector).value = "";
  }, selector);
}

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.type("input.search","hello");
  await clear(page,"input.search");

  await browser.close();
})();
`

**Comment by samfultonjr** [comment]
Made my own little function, pretty easy to use for those who are seeking this feature.
```
async function clear(page, selector) {
  await page.evaluate(selector => {
    document.querySelector(selector).value = "";
  }, selector);
}

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.type("input.search","hello");
  await clear(page,"input.search");

  await browser.close();
})();
```
OR you can add it to the page class to use page.clear(selector); like this,

```
clear = async function ( selector) {
  await this.evaluate(selector => {
    document.querySelector(selector).value = "";
  }, selector);
};


(async () => {
  const browser = await puppeteer.launch({headless:false});
  const page = await browser.newPage();
  page.clear = clear;
  await page.goto('https://www.w3schools.com/html/html_forms.asp');
  await page.type("input[value]","hello");
  await page.clear("input[value]");

  await browser.close();
})();
```

**Comment by samfultonschool** [comment]
`await page.type('#myinput', 'toto', {preselect: true});`

**Comment by hmmhmmhm** [comment]
@samfultonschool thanks! it's very useful!

**Comment by santaclauze** [comment]
Functionality is a good idea!

**Comment by nicoandmee** [comment]
Also love this!

**Comment by samfultonjr** [comment]
@nicoandmee Agreed, I would love to see this come standard with puppeteer. 
@aslushnikov Are there any plans for implementing ```page.clear()``` or ```page.clearInput()```?

**Comment by Crashdoom** [comment]
I'm baffled by how this hasn't been implemented.

Workaround that seems to work without requiring the use of evaluate:
```
// From https://evanhalley.dev/post/clearing-input-field-puppeteer/
await searchInput.click({clickCount: 3});
await searchInput.press('Backspace');
```

**Comment by bitwombat** [comment]
> I'm baffled by how this hasn't been implemented.

Probably because the volunteer maintainer(s) had something come up with a higher priority (maybe family, paid work, rest). Reference your PR with the fix here so they'll see it.

**Comment by HRK44** [comment]
@bitwombat this has been dismissed by the maintainers, see https://github.com/puppeteer/puppeteer/pull/3180#issuecomment-418204987

**Comment by Terkea** [comment]
```js
                // clear the input field
                await page.evaluate(selector => {
                    document.querySelector(selector).value = ""
                }, your_selector);

                await element.type(whatever);
```

**Comment by suraj-sonasoft** [comment]
> I'm baffled by how this hasn't been implemented.
> 
> Workaround that seems to work without requiring the use of evaluate:
> 
> ```
> // From https://evanhalley.dev/post/clearing-input-field-puppeteer/
> await searchInput.click({clickCount: 3});
> await searchInput.press('Backspace');
> ```
this works as I expected https://evanhalley.dev/post/clearing-input-field-puppeteer/  thanks so much @Crashdoom
