### ISSUE TITLE
Feature request: Expose the config

### ISSUE THREAD

**Issue by HRK44** [puppeteer/puppeteer#3095]
I think it would be great to have a function ``.getConfig()`` that gives the actual config ran by puppeteer.

That's useful to detect headless mode and execute different function based on that.

I posted this question on SO : https://stackoverflow.com/questions/51845207/how-do-i-get-actual-config-in-puppeteer and there is an answer but in my case (and I think a lot of people do it this way), I have multiple files for the tests, so having a function to retrieve the config would be useful.

**Comment by aslushnikov** [comment]
Why isn't `browser.process().spawnargs` enough?

**Comment by HRK44** [comment]
@aslushnikov ``browser.process()`` returns ``null`` in my case, since I'm using ``puppeteer.connect``, is there an other way to get it?

**Comment by aslushnikov** [comment]
@HRK44 ah, yes, I'd use raw protocol (see [`CDPSession`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-class-cdpsession)) and call [`Browser.getBrowserCommandLine`](https://vanilla.aslushnikov.com/#Browser.getBrowserCommandLine) method.

Is this good enough?

**Comment by HRK44** [comment]
@aslushnikov I managed to retrieve the config through the CDPSession, thanks for your help !

```javascript
const client = await page.target().createCDPSession();
const response = await client.send('Browser.getBrowserCommandLine');
page.headless = response.arguments.includes('--headless');
```

What do you think about adding a more 'streamlined' function ``.getConfig()`` or ``.getSpawnArgs()`` ?

**Comment by aslushnikov** [comment]
@HRK44 this looks like a very exotic scenario. Can you share your usecase? How come you don't know if the instance you connect to is headless or not?

**Comment by HRK44** [comment]
@aslushnikov I need this information in my test files, a simple example is :

> when I use the .type function, if it is running with headless: true, I don't want any delay. Else, add some { delay: 200 }.

Note that this is just for the 'headless' case but maybe other people would use other configurations params.

Also my connection is done is some other file than my test files (I found this file structure in some official docs if I recall correctly), so in my test file I'm not aware of the configuration used to connect - unless using the code in the previous comment via ``getBrowserCommandLine``.

**Comment by aslushnikov** [comment]
@HRK44 I'm still not sure I follow - aren't you in control how's the chrome browser is launched?

**Comment by HRK44** [comment]
@aslushnikov I am, I manually change the config passed to the ``.launch({headless: true})`` function before running some tests. But the ``.launch({headless: true})`` or ``.connect()`` are in some setup files and the tests in their own folder - which is the structure described in most of the docs/tutorials online.

I guess I could extract the config in a file and import it where I need it, but my first thought was to find an existing API retrieving me this config.

**Comment by aslushnikov** [comment]
> I guess I could extract the config in a file and import it where I need it, but my first thought was to find an existing API retrieving me this config.

@HRK44 I see, thanks for the explanation. This would be the right thing to do here; you might have many more properties in your config that are unrelated to the chrome headless/headful mode. 

I don't think we should add a designated top-level API to fetch browser command-line unless there's a more convincing usecase; the posted workaround using raw devtools protocol should satisfy most of the occasional needs here.
