### ISSUE TITLE
Chromium revision is not downloaded.

### ISSUE THREAD

**Issue by Minirock** [puppeteer/puppeteer#3097]
Hello there,

i'm trying to use critical who actually needs to use pupeeter. But I'm getting this error.

`critical https://critical.test.com/temp/test-critical/`

> Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
> at assert (/usr/local/lib/node_modules/critical/node_modules/puppeteer/lib/helper.js:282:11)
> at Function.launch (/usr/local/lib/node_modules/critical/node_modules/puppeteer/lib/Launcher.js:106:7)

More info:

`node -v`
v10.8.0

`npm -v`
6.2.0

The strange thing is: this folder ` /usr/local/lib/node_modules/critical/node_modules/puppeteer/.local-chromium` already exists. So I guess Chromium is already installed.

**Comment by aslushnikov** [comment]
@Minirock This looks like some issue with either critical or your local environment; I can't say much about either of these.

Let me know if you think I can be somehow helpful here.
