### ISSUE TITLE
Pdf width is smaller than it should be

### ISSUE THREAD

**Issue by jbprat** [puppeteer/puppeteer#3098]
### Steps to reproduce
There seems to be an issue with the way the function page.pdf interprets the width of the page. Eventually using the design of the media query below the current one and I can't seem to know what's going on here.

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Mac
* URLs (if applicable): http://stephencaver.com/
* Node.js version: 8.11.3

**What steps will reproduce the problem?**
To reproduce the issue, you can try a page.pdf with this page http://stephencaver.com/, with a width of 902 and an height of 2000 (height does not matter here).
You'll see that the design display a two rows website demo instead of three, which is the rule for the media-query below 900 pixels.

_Please include code that reproduces the issue._
```
import puppeteer from 'puppeteer';
import fs from 'fs';
import express from 'express';
import bodyParser from 'body-parser';
import { join } from 'path';
import mkdirp from 'mkdirp';

const port = '8800';

/**
 * Creates and returns a configured express server.
 */

function createExpressServer() {
  let app = express();
  app.use(bodyParser.json({ limit: '50mb' }));
  app.use(bodyParser.urlencoded({ limit: '50mb', extended: true }));

  const wait = (timer) => new Promise(resolve => setTimeout(() => resolve(), timer));

  app.post('/createPDF/', async (req, res) => {
    const startTime = Date.now();
    console.log("Received request to render page: %s", req.body.url);

    // Launch Puppeteer
    const uuid = uuidv4();

    await page.emulateMedia('screen');

    // Go to the page and wait for all the connection on the page to be resolved
    await page.goto(`${req.body.url}`, {waitUntil: 'networkidle0'});

    // Send the response
    switch(req.body.format) {
      case 'pdf':
        await page.pdf({
          path: join(__dirname, PDF_EVIDENCE_FD, `${uuid}.pdf`),
          height: pageHeight,
          width: pageWidth,
          printBackground: true
        });

        res.status(200).sendFile(`${uuid}.pdf`);
        break;

      default:
        res.status(501).send({ error: 'error'});
        break;
    }
  });

  app.on("listening", function() {
    console.log("Listening on port %d", app.port);
  });
  return app;
}

let appInstance = createExpressServer();

appInstance.listen(port);
```

**What is the expected result?**
A three row demo section.

**What happens instead?**
A one row below section.

**Comment by lbittner-pdftron** [comment]
+1

Experiencing exact same issue. Setting the width and height of page produces a PDF with much smaller dimensions.

```
   await page.pdf({
      path: `${outputFolder}/${outputName}.pdf`,
      printBackground: true,
      width: '612px',
      height: '792px',
    })
```

Produces a PDF with dimensions of 458 x 594

**Comment by ggevgg** [comment]
+1 The same for me. I set width 1800px, but in pdf width is only 1200px

**Comment by ghost** [comment]
> +1
> 
> Experiencing exact same issue. Setting the width and height of page produces a PDF with much smaller dimensions.
> 
> ```
>    await page.pdf({
>       path: `${outputFolder}/${outputName}.pdf`,
>       printBackground: true,
>       width: '612px',
>       height: '792px',
>     })
> ```
> 
> Produces a PDF with dimensions of 458 x 594

It is interesting to note that `612 * 3/4 = 459` , and `792 * 3/4 = 594` . I do not know if it just a coincidence .

I think in this [https://github.com/puppeteer/puppeteer/issues/666](url) is an explaination of the physical meaning 3/4.
