### ISSUE TITLE
page.evaluate: warn if resolved value can't make the round trip

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#310]
It's easy to run into cases where the return value of `page.evaluate` can't be returned to the calling page b/c it's not a basic JS type:

```javascript
const rect = await page.evaluate(async () => {
  const element = document.querySelector('#id');
  return element.getBoundingClientRect();
});
// rect === {}
```

For this example, one solution is to pick out values from the `ClientRect`:

```javascript
const rect = await page.evaluate(async () => {
  const element = document.querySelector('#id');
  const {x, y, width, height} = element.getBoundingClientRect();
  return {left: x, top: y, width, height};
});
// rect === { left: 0, top: 1282, width: 695, height: 22 }
```
However, it would be nice if `page.evaluate` warns for these cases. 

somewhat related: https://github.com/GoogleChrome/puppeteer/issues/302

**Comment by paulirish** [comment]
Aye. at the very least puppeteer should `console.warn()` in these cases. Alternatively it could just reject()

**Comment by JoelEinbinder** [comment]
I don't think we can warn accurately here. For comparison, JSON.stringify doesn't warn in this case.

**Comment by ebidel** [comment]
#376 is another example of this gotcha. For starters, what about warning if the serialized value is `{}`? That would also least give users a heads up.

**Comment by aslushnikov** [comment]
The problem might naturally go away with the introduction of object handles.

> what about warning if the serialized value is {}.

The `{}` is a valid value to return:
```js

const puppeteer = require('.');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  console.log(await page.evaluate(() => {
    return {};
  }));
  browser.close();
})();
```

Though I agree, we need to somehow inform users of the behavior.

**Comment by pavelfeldman** [comment]
Closing in favor of #382.
