### ISSUE TITLE
Scrape html elements without class

### ISSUE THREAD

**Issue by mruck** [puppeteer/puppeteer#3101]
This is probably a basic questions but...how can I scrape html elements without knowing the class name?
For example say I have an html page with a button and a href:
```
<button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
<a href="catalogue/soumission_998/index.html"><img src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg" alt="Soumission" class="thumbnail"></a>
```
How can I retrieve those elements? I tried the below but it returns an empty list.
```
    const selectors = await page.$$('href');
    selectors.forEach((element) => {
        console.log(element.href)
    })
```
Thank you!

**Comment by vsemozhetbyt** [comment]
It seems the selector should be `page.$$('a[href]')` here. See https://drafts.csswg.org/selectors-4/#attribute-selectors
