### ISSUE TITLE
Full page screenshot fails when defaultViewport is null

### ISSUE THREAD

**Issue by k3mayo** [puppeteer/puppeteer#3104]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7.0
* Platform / OS version: Windows 7
* URLs (if applicable):
* Node.js version: v9.10.1

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: false, defaultViewport: null });
    const page = await browser.newPage();
    await page.goto('https://www.google.com/');
    await page.screenshot({ path: 'example.png', fullPage: true });
    await browser.close();
})();
```

**What is the expected result?**
No error and screenshot is saved.

**What happens instead?**
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isMobile' of null`

**Comment by yanivefraim** [comment]
Trying this gave me a different error:

`fullPage screenshots do not work without first setting viewport.` ([source](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L861))

Is this still considered a bug?

**Comment by aslushnikov** [comment]
@yanivefraim yeah; viewport should not be necessary to do a full-page screenshot.
