### ISSUE TITLE
Calling a exposed function inside an evaluateOnNewDocument function does not work on Chrome 70

### ISSUE THREAD

**Issue by williamoliveira** [puppeteer/puppeteer#3106]
* Puppeteer version: 1.7.0
* Platform / OS version: Linux x64
* Node.js version: v10.0.0

This code works on Chorme/Chromium 69, "Hello from logExposedFunction1" and "Hello from logExposedFunction2" are logged to console, with Chrome 70 only  "Hello from logExposedFunction2" is logged.

I noticed logging `logExposedFunction1` logs `ƒ () { [native code] }` and `logExposedFunction2` logs a js code from `__puppeteer_evaluation_script__:2`

Was there an API change around this? I did not see anything at the change log 

```js
const puppeteer = require('puppeteer')

const start = async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });

  const page = await browser.newPage();

  await page.exposeFunction('logExposedFunction1', () => {
    console.log('Hello from logExposedFunction1')
  })
  await page.evaluateOnNewDocument(() => {
    logExposedFunction1()
  })

  await page.goto('https://example.com');

  await page.exposeFunction('logExposedFunction2', () => {
    console.log('Hello from logExposedFunction2')
  })
  await page.evaluate(() => {
    logExposedFunction2()
  })
}

start()
```

**Comment by williamoliveira** [comment]
Just noticed delaying execution of `logExposedFunction1()` works, so there must be a race condition going on

```js
 // ....
  await page.evaluateOnNewDocument(() => {
    setTimeout(() => {
      logExposedFunction1()
    }, 1)
  })
 // ....
```
I can move on with my life now but still would like to know If I am doing something wrong or is it a bug

**Comment by aslushnikov** [comment]
Thanks @williamoliveira,

That's a recent regression; the offender is https://crrev.com/578514
We'll have to fix this upstream.

**Comment by aslushnikov** [comment]
Upstream fix: https://chromium-review.googlesource.com/c/chromium/src/+/1180585

**Comment by williamoliveira** [comment]
Awesome! thanks for the rapid work
