### ISSUE TITLE
Need help installing puppeteer

### ISSUE THREAD

**Issue by danielhanbitlee** [puppeteer/puppeteer#3107]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: none (need help installing)
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 10.9.0
* npm version: 6.2.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `npm i puppeteer` causes an error

ERROR: Failed to download Chromium r579032! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1047:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:629:8) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
npm WARN Desktop@1.0.0 No description
npm WARN Desktop@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.7.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\short.DESKTOP-GAV8MA2\AppData\Roaming\npm-cache\_logs\2018-08-18T21_19_58_834Z-debug.log

I also tried npm i puppeteer on Windows Subsystem Ubuntu (version 16.04.4 LTS) and i get the same error. 

Any suggestions on how to resolve this?

**Comment by hasibsahibzada** [comment]
You can install it by setting `--unsafe-perm=true` parameter as:
`npm install puppeteer --unsafe-perm=true`

> Set to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.

According to [this](https://docs.npmjs.com/misc/config#unsafe-perm)

**Comment by danielhanbitlee** [comment]
I tried that but it didn't work. Still, thank you for the help. Also, I was able to figure out what I needed to figure out without installing puppeteer.

**Comment by BadWaka** [comment]
Help，please tell me how did work?

**Comment by danielhanbitlee** [comment]
@BadWaka I didn't figure out how to install puppeteer. I gave up on it. But I figured out a solution to my problem without installing puppeteer so I no longer need it. Sorry that I can't be much help regarding installing puppeteer.

**Comment by aixinalei** [comment]
if you are a chinese，try cnpm install puppeteer @BadWaka

**Comment by notaphplover** [comment]
I'm having the same problem, could this issue be reopened please? I think this issue should be reopened since the problem is not fixed

**Comment by aslushnikov** [comment]
@notaphplover this error means that puppeteer failed to download Chromium - most likely there's some proxy that needs to be configured on your machine.

To debug this, try downloading Chromium directly from `https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/588429/chrome-mac.zip` and see if it works.

**Comment by notaphplover** [comment]
@aslushnikov Thank you :). I was able to install puppeteer. It was completely my fault. Thank you for your time and sorry.

**Comment by k-C0D3** [comment]
cheng your ip

**Comment by k-C0D3** [comment]
> I tried that but it didn't work. Still, thank you for the help. Also, I was able to figure out what I needed to figure out without installing puppeteer.

cheng your ip

**Comment by condinoaljoseph** [comment]
I also have this error guyz. someone can help me?

`(node:28066) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/whatoplay/node/test/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/whatoplay/node/test/node_modules/puppeteer/lib/`

**Comment by shoaibahmaad** [comment]
i have the same issue...
did you find any solution??

**Comment by condinoaljoseph** [comment]
@shoaibahmaad  we just change from puppeeter to cheerio

**Comment by bbudd** [comment]
It's likely that the original error is because `node` is not in the `$PATH` so when puppeteer tries to run `node install.js` the command line says "uh, no `node`"

**Comment by arohithr8** [comment]
I fixed the issue by setting **PUPPETEER_SKIP_CHROMIUM_DOWNLOAD** variable to **true** as it shows in the first line of error.

_ERROR: Failed to download Chromium r579032! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download._

**set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true**
