### ISSUE TITLE
Is it clear what  <...Type> means in the docs?

### ISSUE THREAD

**Issue by mattzeunert** [puppeteer/puppeteer#3109]
It took me a while to figure out what this means, i.e. that you pass in a list of separate arguments of that type.

```
## page.setCookie(...cookies)
...cookies <...Object>

## page.select(selector, ...values)
...values <...string>
```

It kinda looks like you destructure the object/string, which doesn't make any sense here.

Maybe `...cookies <...Array<Object>>` would be more clear?

**Comment by aslushnikov** [comment]
@mattzeunert yeah I think we made up this type description. The technically correct thing to do would be:
```
## page.setCookie(...cookies)            // this aligns with javascript 
- `cookies` <[Array]<[Object]>>          // this aligns with tsc
```

However, I'd prefer to keep things as is until it hurts more.

It's a pity we don't have an example in the doc on how to use `page.setCookie` - I think it would help a lot to understand what's going on and probably would save you some time. What do you think?
