### ISSUE TITLE
bug on xhr request

### ISSUE THREAD

**Issue by RuslanTT** [puppeteer/puppeteer#3111]
* Puppeteer version: 1.7.0
* Platform / OS version: ubuntu 16.04
* URLs (if applicable): 
* Node.js version: 8.11.3

**What steps will reproduce the problem?**
make a script with such js:
```
    var bytesToSend = [0xac, 0xed, 0x00, 0x05],
    bytesArray = new Uint8Array(bytesToSend);

    var xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://testsite.loc/tests/testserialized.php', false);
    xhr.setRequestHeader('Content-Type', 'application/octet-stream');
    xhr.send(bytesArray);
```
 ```
page.on('request', request =>{
    console.log('on request:'+request.url());
})
```

if we have await page.setRequestInterception(true);
we cant catch that request.

**What is the expected result?**
it was worked in 1.6.2. and lower( not properly, but worked, https://github.com/GoogleChrome/puppeteer/issues/2277) . In 1.7 it doesnt work

if var bytesToSend = [0x31,0x31,0x31,0x31] looks like array of ascii symbols it works properly, we can intercept and get '1111' at request.postData()

**Comment by AllenZeng** [comment]
i have the same issue 😂😂

**Comment by tx4x** [comment]
same here, i can't get post data with compressed/encoded data correctly

**Comment by aslushnikov** [comment]
Please upvote the issue rather than posting "+1" comments. It'll help us to prioritize work.

**Comment by tx4x** [comment]
digging into the code, i figured that the ws package isn't returning a Buffer because of 2 missing leading bytes (this._opcode). Create a stack trace to find it (receiver.js or so)
