### ISSUE TITLE
Can't run puppeteer use await page.click

### ISSUE THREAD

**Issue by AreYouQQ** [puppeteer/puppeteer#3114]
1、This is my code
      
![putty_2018-08-21_16-31-08](https://user-images.githubusercontent.com/37007704/44390645-5ec1c200-a560-11e8-9168-196ad6e7ab95.jpg)

2、When I run it In Centos 7 server，I get this error 
     
![putty_2018-08-21_16-28-09](https://user-images.githubusercontent.com/37007704/44390489-f83ca400-a55f-11e8-9642-9cfde2b6d12d.jpg)

Thank You

**Comment by blacknbunny** [comment]
I really want to help you but im so lazy for it :P
