### ISSUE TITLE
@types/puppeteer errors

### ISSUE THREAD

**Issue by FlippieCoetser** [puppeteer/puppeteer#3116]
### Steps to reproduce
1. NPM Install
```
"@types/puppeteer": "^1.6.0"
"puppeteer": "^1.7.0",
```
2. Create Typescript File 
```typescript
import * as puppeteer from "puppeteer";
const opts = {
    headless: false,
    slowMo: 100,
    timeout: 10000,
  };

let browser: any = {};

before(async () => {
  browser = await puppeteer.launch(opts);
});

after( async() => {
  await browser.close();
});
```
3. Compile Typescript File produces the following errors:
![image](https://user-images.githubusercontent.com/3672126/44416845-5e332680-a574-11e8-8d68-e0b414a85fd6.png)

Here are the two lines of code the compiler is complaining about:
```typescript
export type WrapElementHandle<X> = X extends Element ? ElementHandle<X> : X;
export type UnwrapElementHandle<X> = X extends ElementHandle<infer E> ? E : X;
```

4. No errors are produced when ` "@types/puppeteer": "^1.6.0" ` are not installed. However, without the @types no intelliSense is available in visual studio code.

Typescript Version: 3.0.1

**Comment by Means88** [comment]
Issues about @types may be reported in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by FlippieCoetser** [comment]
@Means88 Although I agree it is a @type error, it is directly related to this library. I added the issue here since there are over 3786 @types with all using the same GitHub issues. The total issues in there are 2243 and increasing weekly. Surely the development of this library and @types should in in harmony with each other...

**Comment by aslushnikov** [comment]
@FlippieCoetser I hope community will help us here. Please, file over to DefinitelyTyped and/or send a PR to them to address the issue.
