### ISSUE TITLE
Using Chrome, not Chromium, with GCP's Cloud Functions

### ISSUE THREAD

**Issue by p8952** [puppeteer/puppeteer#3117]
Apologies if this is the wrong place to raise this issue, it might be more of a GCP/Cloud Functions issue.

As per #3021 and the announcement [here](https://cloud.google.com/blog/products/gcp/introducing-headless-chrome-support-in-cloud-functions-and-app-engine), running Chrome via Puppeteer with GCP's Cloud Functions seems to be supported.

For my use case I need to run Chrome [not Chromium as I need H.264 support](https://www.chromium.org/audio-video). Since the announcement mentions both Chrome and Chromium I am assuming this is possible.

Cloud Functions Settings:

Name: chromeNotChromium
Memory Allocated: 1GB
Trigger: HTTP
Runtime: Node.js 8 (Beta)
Function to Execute: chromeNotChromium

index.js:
```
const puppeteer = require("puppeteer");

async function getBrowserPage() {
  const browser = await puppeteer.launch({
    executablePath: "google-chrome",
    args: ["--no-sandbox"]
  });

  return browser.newPage();
}

exports.chromeNotChromium = async (request, response) => {
  const browserPage = await getBrowserPage();

  await browserPage.goto(`https://example.com`);

  const browserImage = await browserPage.screenshot();

  response.set("Content-Type", "image/png");
  response.status(200).send(browserImage);
};
```

package.json:
```
{ 
  "name": "chrome-not-chromium",
  "version": "0.0.1",
  "dependencies": { 
    "puppeteer": "^1.6.2" 
  }
}
```

I have tried setting `executablePath` to `chrome`, `google-chrome`, and `google-chrome-unstable`. All three seem to give me the same error:

```
{
 insertId:  "000000-d6c0bc7a-ce6f-4ef4-bcf0-62359b2e888f"  
 labels: {
  execution_id:  "p4lch9e6ktb9"   
 }
 logName:  "projects/drum-technologies-00000/logs/cloudfunctions.googleapis.com%2Fcloud-functions"  
 receiveTimestamp:  "2018-08-21T17:20:17.286406881Z"  
 resource: {
  labels: {
   function_name:  "chromeNotChromium"    
   project_id:  "drum-technologies-00000"    
   region:  "us-central1"    
  }
  type:  "cloud_function"   
 }
 severity:  "ERROR"  
 textPayload:  "Error: Failed to launch chrome! spawn google-chrome ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/srv/node_modules/puppeteer/lib/Launcher.js:299:14)
    at ChildProcess.helper.addEventListener.error (/srv/node_modules/puppeteer/lib/Launcher.js:290:64)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"  
 timestamp:  "2018-08-21T17:20:11.414Z"  
}
```

Is running Chrome supported on GCP's Cloud Functions? And if so what value should I be using for `executablePath`?

**Comment by ebidel** [comment]
AFAIK, you can't install custom software on GCP. I'd look into using App Engine Flex (Node) which you can setup with whatever you want via a Dockerfile. The try-puppeteer site is an example of doing that: https://github.com/ebidel/try-puppeteer/tree/master/backend

**Comment by p8952** [comment]
@ebidel I suppose that's my question. Is Chrome "custom software" or am I just looking for it in the wrong place? 😄

[The announcement](https://cloud.google.com/blog/products/gcp/introducing-headless-chrome-support-in-cloud-functions-and-app-engine) talks about using headless Chrome as well as using Puppeteer with Chromium.

> Node.js 8 runtimes have also been upgraded with the OS packages required to run headless Chrome.

> One way to use headless Chrome with Cloud Functions is with Puppeteer. Puppeteer is a Node.js library built by the Chrome DevTools team that provides a high-level API to control headless Chrome (or Chromium) over the DevTools Protocol. It also installs a recent version of Chromium alongside the library by default.

It could just be that the announcement uses Chrome/Chromium interchangeably, but I'd hate to put a lot of effort into building something custom with App Engine only to find out it is actually supported on GCP/Cloud Functions! 😩

**Comment by p8952** [comment]
It does appear that Chrome is not available in the GCP/Cloud Functions environment.

[files.txt](https://github.com/GoogleChrome/puppeteer/files/2309567/files.txt)

Thanks @ebidel for the pointer to App Engine, I'll look into using that instead.
