### ISSUE TITLE
'ignoreHTTPSErrors' option is not working well.

### ISSUE THREAD

**Issue by kbbmanse** [puppeteer/puppeteer#3119]
* Puppeteer version:1.7.0
* Platform / OS version:mac/sierra 10.12.6
* URLs (if applicable):
* Node.js version:8.9.0

**What steps will reproduce the problem?**
**test.js** 
```
const puppeteer = require("puppeteer");

async function test(browser) {
    const page = await browser.newPage();
    await page.setRequestInterception(true);

    page.on("request", request => {
        console.log("request - resource type: " + request.resourceType() + ", url: " + request.url() + ", nav: " + request.isNavigationRequest() + ", redir: " + request.redirectChain().length);
        request.continue();
    });

    page.on("response", response => {
        console.log("response - resource type: " + response.request().resourceType() + ", url: " + response.url() + ", from cache: " + response.fromCache());
    });

    try {
        await page.goto("https://inavi.com/CustCenter/Qna/Dtls/370615?catecd1=cate_00126", {waitUntil:"networkidle2"});
    } catch(e) {
        console.log(e.message);
    }
    finally {
        await page.close();
    }
}

puppeteer.launch({headless: true, dumpio: true, ignoreHTTPSErrors:false, args:['--ignore-certificate-errors', '--enable-feature=NetworkService']}).then(async browser=> {
    console.log("First Time - Set ignoreHTTPSErrors:false\n");
    await test(browser);
    const wsEndpoint = browser.wsEndpoint();
    browser.disconnect();

    console.log("\nSecond Time - Set ignoreHTTPSErrors:true\n");
    puppeteer.connect({browserWSEndpoint: wsEndpoint, ignoreHTTPSErrors:true, args:['--ignore-certificate-errors', '--enable-feature=NetworkService']}).then(async browser=> {
        await test(browser);
        browser.close();
    });
});
```

**Results**
```
DevTools listening on ws://127.0.0.1:51553/devtools/browser/03c1dc63-c2a5-4910-ba9c-11455c134224
First Time - Set ignoreHTTPSErrors:false

request - resource type: document, url: https://inavi.com/CustCenter/Qna/Dtls/370615?catecd1=cate_00126, nav: true, redir: 0
net::ERR_CERT_SYMANTEC_LEGACY at https://inavi.com/CustCenter/Qna/Dtls/370615?catecd1=cate_00126

Second Time - Set ignoreHTTPSErrors:true

request - resource type: document, url: https://inavi.com/CustCenter/Qna/Dtls/370615?catecd1=cate_00126, nav: true, redir: 0
Navigation Timeout Exceeded: 30000ms exceeded
```

**What is the expected result?**
There are several pages with the https certification problem.
I expected that the pages will be rendered well if I apply the option 'ignoreHTTPSErrors:true' when I invoke puppeteer.launch(). 

**What happens instead?**
As you can see in the above results, the option 'ignoreHTTPSErrors:true' was not effective at all.
The output shows that the request event has occurred, but the response event didn't occure.

**Comment by reverieline** [comment]
Same problem in headless mode. But if launch options ={
	headless: false,
	ignoreHTTPSErrors: true,
		args: ["--ignore-certificate-errors"],
}, everything work fine.

**Comment by kbbmanse** [comment]
@reverieline 
Thank you for your answer. But I usually use puppeteer on headless mode because it is executed on Linux servers. So this is still problem to me..

**Comment by junseok-oh-0** [comment]
I've been experiencing the same thing.
All I found was Security.certificateError, Security.handleCertificateError and Security.setOverrideCertificateErrors used to handle certificate errors are deprecated. Instead, it seems that the method Security.setIgnoreCertificateErrors has been added. I tried with this new method, but it still doesn't work.

**Comment by aslushnikov** [comment]
This is a dupe of #1159. It's fixed now on puppeteer@next.

**Comment by rn2web** [comment]
> Same problem in headless mode. But if launch options ={ headless: false, ignoreHTTPSErrors: true, args: ["--ignore-certificate-errors"], }, everything work fine.

This solution Works fine in 2021.
