### ISSUE TITLE
Add an option to generate PDF with the screen CSS media type

### ISSUE THREAD

**Issue by astefanutti** [puppeteer/puppeteer#312]
It seems the PDF generation activates the print CSS media type. While that makes sense in the majority of use cases, it would be very useful in some other use cases, like [Decktape](https://github.com/astefanutti/decktape) that exports HTML presentations for which it is preferable to retain the screen media type.

**Comment by hbakhtiyor** [comment]
Chrome has some issue with generating pdf with screen media type,

here are my post & issue:
https://groups.google.com/a/chromium.org/forum/#!topic/headless-dev/-GEgfCiVTtE
https://bugs.chromium.org/p/chromium/issues/detail?id=749080
