### ISSUE TITLE
Pupeteer fast in remote desktop, slow in SSH (headless: false)

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#3129]
Hi,
When I run visually pupeteer inside a remote desktop, everything works fine (I use headless:false)

When I run it in SSH, it is 20 times slower. 

> browser = await puppeteer.launch() 

takes more than 15 seconds in SSH and 1 second is remote desktop

when headless:true, it works fine both in remote desktop and ssh

Any clue ?

**Comment by ebidel** [comment]
Assume you're using X forwarding... [it's slow](https://superuser.com/questions/1217280/why-is-x11-forwarding-so-inefficient). Network can also have a big impact.

Running a puppeteer script w/ `ssh -X`, connecting to a machine under my desk  yields a ~5x slow down launching headless vs. headful chrome:

```
HEADLESS=true node pptr_x11.js 
-> launch headless: true: 1186.032ms
HEADLESS=false node pptr_x11.js 
-> launch headless: false: 5683.967ms
```

Running the same script directly on the machine:
```
HEADLESS=true node pptr_x11.js 
-> launch headless: true: 211ms
HEADLESS=false node pptr_x11.js 
-> launch headless: false: 864.ms
```

**Comment by ebidel** [comment]
Going to close since this isn't an issue related to the Puppeteer library itself.
