### ISSUE TITLE
Will you be exposing network traffic?

### ISSUE THREAD

**Issue by jasonwilliams** [puppeteer/puppeteer#313]
This looks like something we're up for using. 
I wonder if network traffic is exposed like how PhantomJS does it, so we can check XHR calls are happening after a button click for example.

Sorry is his feature is already available and I haven't checked properly

**Comment by aslushnikov** [comment]
Sure, network is already exposed. Page emits a bunch of network requests, check out [`request`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-request) event for example.

**Comment by ebidel** [comment]
Example:

```javascript
const page = await browser.newPage();
await page.setRequestInterceptionEnabled(true);

page.on('request', request => {
  request.continue(); // pass it through.
});

page.on('response', response => {
  const req = response.request();
  console.log(req.method, response.status, req.url);
});
```

Initiator is something we need to add. See https://github.com/GoogleChrome/puppeteer/issues/317.

**Comment by aslushnikov** [comment]
nit: there's no need to enable request interception

```js
const page = await browser.newPage();
page.on('response', response => {
  const req = response.request();
  console.log(req.method, response.status, req.url);
});
```

**Comment by Izhaki** [comment]
@ebidel 

You may want to edit your answer (`setRequestInterceptionEnabled ` > `setRequestInterception`) per [your comment](https://github.com/GoogleChrome/puppeteer/issues/1431#issuecomment-345784658).

**Comment by mathurs** [comment]
As per the API, method, status and url are all functions.

This worked for me:
console.log(req.method(), response.status(), req.url());

Thanks for this.

**Comment by khachornchit** [comment]
@ebidel 

Thanks. It worked !
But I use await page.setRequestInterception(true); 
instead of await page.setRequestInterceptionEnabled(true);
