### ISSUE TITLE
puppeteer screenshot time on linux

### ISSUE THREAD

**Issue by yuanx520** [puppeteer/puppeteer#3130]
Hi, I am using the following code snippets for partial rendering (by setting viewport) and screenshot on linux:
```
const options= {
  type: 'png',
  fullPage: false,
  encoding: 'base64' 
}
const page = await browser.newPage();
await page.goto(someurl);
await page.setViewport({
      width: 224,
      height: 224,
})
var t0 = Date.now();
await page.screenshot(options);
console.log("screenshot of puppeteer took:", Date.now() - t0);
```
The log shows that screenshot function took ~50ms. I wonder whether this is normal (seems too slow) or not? Do you any good suggestions for speeding this up? 
Thank you!

**Comment by aslushnikov** [comment]
@yuanx520 I've been debugging screenshot time sometime ago and didn't find any low-hanging fruits to speed up things. 50ms doesn't look very fast, but keep in mind that we encode screenshot into base64 to  transfer it over websocket, and then decode it back to buffer.

So I'd say it's pretty reasonable. 

Hope this helps!
