### ISSUE TITLE
how to byPass ERROR: ERR_CERT_SYMANTEC_LEGACY

### ISSUE THREAD

**Issue by tangyiming** [puppeteer/puppeteer#3132]
is there any way to ignore the error and reach to the website

```batch
goto url: https://job.chinaredstar.com/
(node:21200) UnhandledPromiseRejectionWarning: Error: Error: net::ERR_CERT_SYMANTEC_LEGACY at https://job.chinaredstar.com/
    at newPage.goto.catch.err (D:\工作\ScrapySPA\crawlsite.js:101:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by vsemozhetbyt** [comment]
You can try `ignoreHTTPSErrors` option in [`puppeteer.launch()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions).

**Comment by tangyiming** [comment]
@vsemozhetbyt thank you for your answer 👍 but
I've tried this option, and the script just exit after that line,
did'nt crawler other pages i want  

```
D:\工作\ScrapySPA>node crawlsite.js
https___job.chinaredstar.com_
OUT_DIR output/https___job.chinaredstar.com_
func mkdirSync: output/https___job.chinaredstar.com_
Loading: https://job.chinaredstar.com/
goto url: https://job.chinaredstar.com/
```
```
{
 "url": "https://job.chinaredstar.com/",
 "title": "xxxxx",
 "children": []
}
```

**Comment by shiquanwang** [comment]
@Tangyiming I've met the same error. Why did you close the issue? Did you find a way to solve the issue? Please post out.

**Comment by tangyiming** [comment]
@shiquanwang 关闭是因为我放弃了，没找到解决办法（i gave up, not solved）
