### ISSUE TITLE
not launch chrome when set headless: true on windows 7

### ISSUE THREAD

**Issue by caserffer** [puppeteer/puppeteer#3134]
when i set headless: false it works fine
but when i want to ues headless:true ,puppeteer can not launch chrome
my code is:
const puppeteer = require('puppeteer');

(async () => {
    const browser = await (puppeteer.launch({
        executablePath: 'D:\\puppeteer\\chrome-win32\\chrome.exe',
        timeout: 15000,
        ignoreHTTPSErrors: true,
        headless: true
    }));
    const page = await browser.newPage();
    await page.goto('https://www.baidu.com/');
    await page.screenshot({
        path: 'baidu.png',
        type: 'png',
        fullPage: true,
    });
    browser.close();
})();
my error is;
"C:\Program Files\JetBrains\WebStorm 2017.2.5\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\quanh\WebstormProjects\pupp-test\demo\ykt\get_home_page.js
(node:10296) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0824/180114.759:FATAL:feature_list.cc(236)] Check failed: !g_initialized_from_accessor. 
Backtrace:
	ovly_debug_event [0x1071BE20+11772048]
	ovly_debug_event [0x1071B6BD+11770157]
	ovly_debug_event [0x10732580+11864048]
	ovly_debug_event [0x1071DE67+11780311]
	ovly_debug_event [0x101873D3+5920323]
	ovly_debug_event [0x1018BB57+5938631]
	GetHandleVerifier [0x110FF6B8+4180760]
	ovly_debug_event [0x106DAAB5+11504933]
	ovly_debug_event [0x106DB13F+11506607]
	ovly_debug_event [0x106DA84F+11504319]
	ovly_debug_event [0x106E3966+11541462]
	ovly_debug_event [0x106DAA4B+11504827]
	IsSandboxedProcess [0x10C1740B+1957747]
	IsSandboxedProcess [0x10C1747F+1957863]
	ovly_debug_event [0x106E2760+11536848]
	ovly_debug_event [0x106E27DE+11536974]
	ChromeMain [0x0FBE1173+247]
	Ordinal0 [0x00E02D80+11648]
	Ordinal0 [0x00E0145D+5213]
	GetHandleVerifier [0x00EC16FA+544266]
	BaseThreadInitThunk [0x76A3343D+18]
	RtlInitializeExceptionChain [0x77A29832+99]
	RtlInitializeExceptionChain [0x77A29805+54]

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\quanh\node_modules\puppeteer\lib\Launcher.js:299:14)
    at ChildProcess.helper.addEventListener (C:\Users\quanh\node_modules\puppeteer\lib\Launcher.js:289:60)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
(node:10296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Process finished with exit code 0

**Comment by aslushnikov** [comment]
Looks like you're running your own version of chromium. This was broken on tip-of-tree and was just fixed; see https://crbug.com/878779.
