### ISSUE TITLE
Failed to launch chrome, ldd chrome | grep not not working

### ISSUE THREAD

**Issue by SeanFromPA** [puppeteer/puppeteer#3138]
Hi all, may be a 'newb' question so my apologies if this is my issue.

Installed puppeteer without issue.  Trying to run basic example code from
[here](https://medium.com/@e_mad_ehsan/getting-started-with-puppeteer-and-chrome-headless-for-web-scrapping-6bf5979dee3e) and get
"(node:5919) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/ftpuser/finmap/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory"
Assume I'm missing dependencies and follow guide here:
[troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)
that says "You can run ldd chrome | grep not on a Linux machine to check which dependencies are missing."
When I try to run "ldd chrome | grep not" I am told 
"ldd: ./chrome: No such file or directory"

Not too sure where to go from here.  Only looking to do very simple web scraping.  Thanks.

**Comment by samholmes** [comment]
Try `cd node_modules/puppeteer/.local-chromium/[linux-579032]/[chrome-linux]` but replace the bracketed directories with the directories available in your node_modules folder. There you should find the local installation of chrome and from there you can run `ldd chrome | grep not`.

**Comment by flftfqwxf** [comment]
I try cd to /var/project/Chinese-recipes/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux and run ldd chrome | grep not
result:not a dynamic executable
But "Error: Failed to launch chrome! " again

**Comment by coxato** [comment]
i have the same problem that @flftfqwxf  ldd chrome | grep not
result:not a dynamic executable 
help please

**Comment by badrelmers** [comment]
@coxato it gave this error because it is a bash script not an executable, i tested that with chromium
so open chrome/chromium with a text editor and see where is the executable then run it with ldd, it will work.
in debian with chromium it is in:
/usr/lib/chromium/chromium

while the ldd chromium uses : /usr/bin/chromium , that s why it says not a dynamic executable
so you have to use:
ldd /usr/lib/chromium/chromium

**Comment by rags2riches-prog** [comment]
> 
> 
> Try `cd node_modules/puppeteer/.local-chromium/[linux-579032]/[chrome-linux]` but replace the bracketed directories with the directories available in your node_modules folder. There you should find the local installation of chrome and from there you can run `ldd chrome | grep not`.

@samholmes 

I know this may seem like a solved issue, it isn't. Problem persists when running Puppeteer on WSL 2.0 (Windows 11) Ubuntu 20.4. Been scouring the web with not avail.

**Comment by cjbarth** [comment]
I had a similar problem when working on WSL. I was actually trying to run some Sinon tests. Anyway, the tip [here](https://github.com/puppeteer/puppeteer/issues/3138#issuecomment-416590723) got me started, but then I couldn't figure out how to install all the dependencies. I found that if I searched [here](https://www.masmasit.com/) for each dependency I needed, they had a line I could copy-paste to install it. That worked for all but one, which was resolved with help from this [comment](https://github.com/cypress-io/cypress/issues/4631#issuecomment-507717436): `sudo apt install libgtk-3-0`.

**Comment by kingakidi** [comment]
> Try `cd node_modules/puppeteer/.local-chromium/[linux-579032]/[chrome-linux]` but replace the bracketed directories with the directories available in your node_modules folder. There you should find the local installation of chrome and from there you can run `ldd chrome | grep not`.

You have just save my ass .....

**Comment by kingakidi** [comment]
> I had a similar problem when working on WSL. I was actually trying to run some Sinon tests. Anyway, the tip [here](https://github.com/puppeteer/puppeteer/issues/3138#issuecomment-416590723) got me started, but then I couldn't figure out how to install all the dependencies. I found that if I searched [here](https://www.masmasit.com/) for each dependency I needed, they had a line I could copy-paste to install it. That worked for all but one, which was resolved with help from this [comment](https://github.com/cypress-io/cypress/issues/4631#issuecomment-507717436): `sudo apt install libgtk-3-0`.

Your reference is a great help, kindly keep it up

**Comment by tokomeno** [comment]
![image](https://user-images.githubusercontent.com/34988363/206862492-085ca9a7-ecdc-49b7-a7a2-242113864b74.png)
I don't have the .local-chromium in node_modules any suggestions, please

**Comment by k-ta-yamada** [comment]
@tokomeno 
I found the following statement in [troubleshooting.md](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#could-not-find-expected-browser-locally).

> Starting from v19.0.0, Puppeteer will download browsers into ~/.cache/puppeteer using [os.homedir](https://nodejs.org/api/os.html#oshomedir ) for better caching between Puppeteer upgrades.

You may want to check your home directory first.
In my case it was `/root/.cache/puppeteer/chrome/linux-1083080/chrome-linux/`.

Hope this helps.

**Comment by rajashree23** [comment]
> Try `cd node_modules/puppeteer/.local-chromium/[linux-579032]/[chrome-linux]` but replace the bracketed directories with the directories available in your node_modules folder. There you should find the local installation of chrome and from there you can run `ldd chrome | grep not`.

I am trying ldd chrome | grep not 
but it is not returning anything
![image](https://github.com/puppeteer/puppeteer/assets/33730790/d48f0efa-a9eb-4f89-b7f8-5454bf994a6f)


can someone help me please?

**Comment by ProceduralMan** [comment]
> > Try `cd node_modules/puppeteer/.local-chromium/[linux-579032]/[chrome-linux]` but replace the bracketed directories with the directories available in your node_modules folder. There you should find the local installation of chrome and from there you can run `ldd chrome | grep not`.
> 
> I am trying ldd chrome | grep not but it is not returning anything ![image](https://user-images.githubusercontent.com/33730790/249156715-d48f0efa-a9eb-4f89-b7f8-5454bf994a6f.png)
> 
> can someone help me please?

As you surely know by now, that means your chrome loads with no missing libs.

Issuing just ldd chrome should give an output similar to this:

`        linux-vdso.so.1 (0x00007ffd803ab000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6cc365f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6cc365a000)
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f6cc35fa000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f6cb54c6000)
        libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007f6cb5399000)
        libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007f6cc35c6000)
        libsmime3.so => /lib/x86_64-linux-gnu/libsmime3.so (0x00007f6cc359c000)
        libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x00007f6cc355c000)
        libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f6cc3532000)
        libatk-bridge-2.0.so.0 => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007f6cc34fa000)
        libcups.so.2 => /lib/x86_64-linux-gnu/libcups.so.2 (0x00007f6cb52fb000)
        libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f6cb5122000)
        libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f6cc34e2000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f6cb50d4000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6cb50a3000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f6cb5079000)
        libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f6cb5032000)
        libatspi.so.0 => /lib/x86_64-linux-gnu/libatspi.so.0 (0x00007f6cb4ff8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6cb4f11000)
        libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6cb4dd1000)
        libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f6cc34db000)
        libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f6cc34d6000)
        libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f6cb4dbc000)
        libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f6cb4db2000)
        libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f6cb4da5000)
        libgbm.so.1 => /lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f6cb4d94000)
        libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f6cb4d2d000)
        libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f6cb4c05000)
        libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007f6cb4b02000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6cb4ae0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6cb4800000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6cc366d000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f6cb4ad3000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f6cb4a5d000)
        libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x00007f6cb4a56000)
        libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x00007f6cb4a51000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f6cb47ac000)
        libavahi-common.so.3 => /lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007f6cb4a41000)
        libavahi-client.so.3 => /lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007f6cb4a2d000)
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f6cb45c1000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6cb45a5000)
        libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f6cb459e000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f6cb455a000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f6cb452e000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f6cb4467000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f6cb4461000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f6cb4459000)
        libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007f6cb4445000)
        libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f6cb4438000)
        libwayland-server.so.0 => /lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f6cb4422000)
        libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f6cb4406000)
        libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007f6cb43fb000)
        libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f6cb432a000)
        libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f6cb427f000)
        libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f6cb4235000)
        libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f6cb416d000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f6cb4132000)
        libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f6cb412d000)
        libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f6cb411c000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f6cb4051000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f6cb4022000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f6cb401c000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f6cb400e000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f6cb3ed1000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f6cb3eb0000)
        libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f6cb3d06000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f6cb3cee000)
        libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007f6cb3ca8000)
        libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007f6cb3c60000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f6cb3bdc000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f6cb3ba5000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f6cb3b0e000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6cb3ae3000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f6cb3a14000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f6cb39f2000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f6cb39e7000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f6cb38a9000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f6cb3891000)
        libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f6cb3888000)
        libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f6cb385f000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f6cb3856000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f6cb3848000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f6cb3841000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f6cb382d000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f6cb3805000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007f6cb37f8000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f6cb37d5000)
`
