### ISSUE TITLE
PDF generated from Data Studio report is blank

### ISSUE THREAD

**Issue by marcospgp** [puppeteer/puppeteer#3139]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: "puppeteer": "^1.7.0",
* Platform / OS version: Windows 10
* URLs (if applicable): https://datastudio.google.com/u/0/reporting/1W0iFLly_vPsn-ni-kfEwPONfUYXjOun2/page/IGgQ
* Node.js version:  v8.9.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. const browser = await puppeteer.launch();
2. const page = await browser.newPage();
3. await page.goto(`<url included above>`, {waitUntil: ['networkidle0', 'domcontentloaded']});
4. await page.pdf({ path: './somepath.pdf' });

**What is the expected result?**

A PDF version of the report visible at https://datastudio.google.com/u/0/reporting/1W0iFLly_vPsn-ni-kfEwPONfUYXjOun2/page/IGgQ

**What happens instead?**

A blank PDF is generated.

**What else have I tried?**

* Generated PDF with `await page.emulateMedia('screen');` successfully.
* Generated screenshots successfully.
* Debugged without headless mode to make sure the page is loading.
* Tried using `displayHeaderFooter: true` and `printBackground: true`, which made some artifacts show up on the blank PDF (which also show up on the expected PDF, generated manually from my browser), but not the main content.

**Comment by marcospgp** [comment]
@aslushnikov @Javirln @JoelEinbinder Sorry to bother, do you have any ideas?

**Comment by nschubach** [comment]
I've been fighting with the PDF generation for the past week using the latest and have not been able to produce anything but a blank PDF of the size I requested from Amazon Lambda.  Sorry this post is not helping, but I wanted to keep an eye on this.

**Comment by aslushnikov** [comment]
@marcospgp it could be related to the `--disable-gpu` flag we pass over to chromium; can you try running without it? 

```js
const browser = await puppeteer.launch({
  ignoreDefaultArgs: ['--disable-gpu']
});
```

**Comment by marcospgp** [comment]
@aslushnikov That didn't work. [Screenshot looks like this](https://i.imgur.com/De9iHD0.png) while PDF is blank. 😢
