### ISSUE TITLE
using headless shell instead of bundle chrome for headless mode

### ISSUE THREAD

**Issue by hbakhtiyor** [puppeteer/puppeteer#3140]
what do you think about using headless shell? small size, removed ui lib dependencies

there are already build files, e.g. https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/583214/headless-shell.zip

**Comment by aslushnikov** [comment]
@hbakhtiyor headless_shell is definitely an option. Puppeteer by default comes with chromium to support the debugging story.

It would be nice to teach [`BrowserFetcher`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-class-browserfetcher) to download "headless_shell". This way anybody can use [`puppeteer-core`](https://github.com/GoogleChrome/puppeteer#puppeteer-core) and come up with a custom install script that downloads headless_shell.

**Comment by hbakhtiyor** [comment]
i downloaded the headless-shell and run in ubuntu 16.04, but got error

```
./headless_shell: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

why the tool require x11 dependency?

**Comment by Guruhbk** [comment]
i downloaded the headless-shell and run in ubuntu 16.04,  got a different error. 
```
(node:17176) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
    [0906/155318.398013:ERROR:icu_util.cc(172)] Invalid file descriptor to ICU data received.
    [0906/155318.398147:FATAL:content_main_delegate.cc(58)] Check failed: false. 
    #0 0x000002abf89c base::debug::StackTrace::StackTrace()
    #1 0x000002a45ca0 logging::LogMessage::~LogMessage()
    #2 0x0000029edc23 content::ContentMainDelegate::TerminateForFatalInitializationError()
    #3 0x0000029f5202 content::ContentMainRunnerImpl::Initialize()
    #4 0x000003d6b528 service_manager::Main()
    #5 0x0000029ee4a1 content::ContentMain()
    #6 0x000002ae077d headless::(anonymous namespace)::RunContentMain()
    #7 0x000002ae0808 headless::HeadlessBrowserMain()
    #8 0x000002a2e84a headless::HeadlessShellMain()
    #9 0x7f38923ac830 __libc_start_main
    #10 0x00000124f02a _start
```
I gave all the required permission for the puppeteer and the headless_shell. Still facing the issue.

**Comment by OrKoN** [comment]
Thanks for the request but I am closing this as it is not something we plan on doing any time soon.
