### ISSUE TITLE
"navigator.webdriver" can help detect using puppeteer

### ISSUE THREAD

**Issue by thkdog** [puppeteer/puppeteer#3141]
* Puppeteer version: 1.7.0
* Platform / OS version: Mac OS 10.13.6 (17G65)
* URLs (if applicable):
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. start a puppeteer program with the default version of Chromium

**What is the expected result?**
navigator.webdriver === undefined

**What happens instead?**
navigator.webdriver === true

This flag can detect if the program is running by puppeteer.
Before this, I have tried using puppeteer to fetch data from a website, but was always detected as robot although the request is exactly the same as I open it with a normal chrome.
So I figure out there must be something wired with the JS code.

**Comment by thkdog** [comment]
Here is the anti-robot js code:
[code](https://s0.meituan.net/mx/rohr/rohr.min.js)

**Comment by xprudhomme** [comment]
Not sure this can be classified as an issue, as it's more likely this has been done on purpose...

**Comment by thkdog** [comment]
@xprudhomme You are right, this is on purpose. But I think it should be much more better to be mentioned on the document. 
Here is an document mention about this issue: [IT IS *NOT* POSSIBLE TO DETECT AND BLOCK CHROME HEADLESS](https://intoli.com/blog/not-possible-to-block-chrome-headless/)

**Comment by aslushnikov** [comment]
>  But I think it should be much more better to be mentioned on the document.

@thkdog feel free to send us a pull request!

**Comment by rotimi-best** [comment]
so how is it possible to make it `navigator.webdriver === undefined` and not `
navigator.webdriver === true` ?

**Comment by thkdog** [comment]
try defineProperty? I haven’t try yet.

沈毅

在 2019年2月28日，22:54，Rotimi Best <notifications@github.com<mailto:notifications@github.com>> 写道：


so how is it possible to make it navigator.webdriver === undefined and not navigator.webdriver === true ?

**Comment by anblance** [comment]
> @xprudhomme You are right, this is on purpose. But I think it should be much more better to be mentioned on the document.
> Here is an document mention about this issue: [IT IS _NOT_ POSSIBLE TO DETECT AND BLOCK CHROME HEADLESS](https://intoli.com/blog/not-possible-to-block-chrome-headless/)

666
