### ISSUE TITLE
"All" XHR requests (such as those visible in the Chrome XHR tab)?

### ISSUE THREAD

**Issue by agamemnus** [puppeteer/puppeteer#3142]
Even with `setRequestInterception(true)`, I can't seem to get certain responses to requests, which, in `chrome://net-internals/#events` for example, are categorized as `HTTP_STREAM_JOB_CONTROLLER`.

And, per https://bugs.chromium.org/p/chromium/issues/detail?id=781660, `net-internals` isn't available in headless Chrome, which I need to be set to "true" for production.

So, I'm kind of stuck. I'm on Windows (the production server isn't Windows, though). Using Puppeteer 1.7.0. Using Node 10.7.0.

**Comment by agamemnus** [comment]
Turns out, I found a workaround, but it would still be fun to know!

**Comment by aslushnikov** [comment]
@agamemnus any chance you can share an example of the requests you don't get responses for? Also, what's your workaround?..

**Comment by agamemnus** [comment]
It's audio streaming. Chrome says it's XHR. The workaround was to examine
the code in more detail; well-tailored XHR requests got the data I needed
to reconstruct the audio requests, and therefore I didn't need to try to
capture the URLs anymore, or run through the whole audio stream, or use
Chrome instead of Chromium, etc.

**Comment by aslushnikov** [comment]
> It's audio streaming. 

This sounds like an endless request. I can see why you're not getting any response then 🤔
