### ISSUE TITLE
page.authenticate blank page

### ISSUE THREAD

**Issue by rasmusgadensgaard** [puppeteer/puppeteer#3143]
### Steps to reproduce
* Puppeteer version: 1.7.0
* Platform / OS version: Windows Server 2016 Standard
* URLs (if applicable):
* Node.js version: 8.11.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

My code looks like this:

    const url = "someurl";
    const browser = await puppeteer.launch( {slowMo: 300,headless: false});
    const page = await browser.newPage();
    page.setViewport({width:1684,height:1190});
    await page.authenticate({username:"user", password:"pwd"});
    await page.goto(url, {waitUntil: 'networkidle0'});

**What is the expected result?**
The page should open up with the user being authenticated via basic authentication

**What happens instead?**
Page is blank. If I remove the page.authenticate line, the browser displays the basic authentication form, and if I fill that out, the page is displayed correctly. There are no erros displayed in the console output of the page.

**Comment by javirln** [comment]
Is the console printing any error?

Also, just in case there are resources that by for any reason haven't been downloaded once the authentication is done, check to change the following:
`await page.goto(url, {waitUntil: 'networkidle0'});`
for
`await page.goto(url, {waitUntil: 'networkidle2'});`

**Comment by vsemozhetbyt** [comment]
FWIW, I cannot reproduce with a test page:
```js

'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const url = 'https://jigsaw.w3.org/HTTP/Basic/';
    const browser = await puppeteer.launch({ slowMo: 300, headless: false });
    const page = await browser.newPage();
    page.setViewport({ width: 1684, height: 1190 });
    await page.authenticate({ username: 'guest', password: 'guest' });
    await page.goto(url, { waitUntil: 'networkidle0' });
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by vroumvroum** [comment]
I was able to reproduce this bug.
Only occurs with mobile user-agent.

Ex : Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"

**Comment by BryanVillaDev** [comment]
Hello broterhs ,
My problem is that this page started to throw this window but they don't give me the credentials, but the solution is to click cancel, but I can't cancel this window in any way, I'm using puppeter
