### ISSUE TITLE
Error while loading shared libraries: libatk-bridge-2.0.so.0 on linux machines

### ISSUE THREAD

**Issue by dineshpvs** [puppeteer/puppeteer#3147]
node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory

We are using linux machine and not Ubuntu. I know there are articles or solution for Ubuntu but not for linux.  I tried for searching any package similar to libatk-bridge using "yum search", but did'nt find any package. Can anyone suggest how to resolve his on **LINUX** machine

**Comment by hasanzu** [comment]
hi @dineshpvs , i am having the same issue. Did you manage to resolve this?
Thanks in advance

**Comment by aslushnikov** [comment]
Please make sure to install [all dependencies](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix).

**Comment by PostAlmostAnything** [comment]
I am having this problem too.

**Comment by agguro** [comment]
same problem on Kali Linux (for Thunar) but years later :(
