### ISSUE TITLE
page.setRequestInterceptioI need to intercept the return content of this url

### ISSUE THREAD

**Issue by KevinHe666** [puppeteer/puppeteer#3151]
`await page.setRequestInterception(true);
 await page.on('request', request => {
                if (request.url === 'https://xxxxxxxxxxxx.do') {
                    console.log(request.url);
                    console.log("拦截到了这条url然后就该请求了");

                    request.abort();
                }
                else {
                    console.log("continue")
                    request.continue();
                }

            });`
I want to know the request's url content or response body

**Comment by donovan-graham** [comment]
Try `const url = request.url();` as a function.
