### ISSUE TITLE
Puppeteer with Headless_shell?

### ISSUE THREAD

**Issue by Guruhbk** [puppeteer/puppeteer#3155]
I'm trying to work on puppeteer with headless_shell to avoid library dependencies in Linux. When i tried `const browser = await puppeteer.launch({executablePath: 'out/Release/headless_shell'})` the browser is created. But When I tried, `const page = await browser.newPage();`, The process stopped right there without any errors. Any suggestions?

**Comment by vaibhav-kb** [comment]
Checkout this 
[https://github.com/GoogleChrome/puppeteer/issues/500#issuecomment-324483480](url)

**Comment by Guruhbk** [comment]
Hi. I tried that link, But unfortunately there was nothing on that page. It showed **_No results matched your search._**

**Comment by vaibhav-kb** [comment]
Checkout this thread 
https://github.com/GoogleChrome/puppeteer/issues/500

**Comment by Guruhbk** [comment]
It said that headless_shell works fine. But for me page doesn't opening.

**Comment by entrptaher** [comment]
The issue is permissions of the directories/files. 

When puppeteer was installed, the permissions were default owner of nobody:<usergroup> but not all files had group or others bits set (i.e. 600 or 700). Puppeteer was installed as `npm install -g puppeteer` and it is run as the local user. The fix was to chmod the files to set the group and others bits to match the "users".

```sh
cd out/Release/headless_shell #or wherever the file is
find . -type d | xargs -L1 -Ixx sudo chmod 755 xx
find . -type f -perm /u+x | xargs -L1 -Ixx sudo chmod 755 xx
find . -type f -not -perm /u+x | xargs -L1 -Ixx sudo chmod 644 xx
```

PS: The actual error is shown as `Invalid file descriptor to ICU data received`, and the issue https://github.com/GoogleChrome/puppeteer/issues/2519 discussed it in depth.

**Comment by Guruhbk** [comment]
@entrptaher Hi. I gave all the permissions as you suggested. And still facing the same error. 

```
(node:9576) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0918/113508.433915:ERROR:icu_util.cc(172)] Invalid file descriptor to ICU data received.
[0918/113508.433993:FATAL:content_main_delegate.cc(58)] Check failed: false. 
#0 0x000002abf89c base::debug::StackTrace::StackTrace()
#1 0x000002a45ca0 logging::LogMessage::~LogMessage()
#2 0x0000029edc23 content::ContentMainDelegate::TerminateForFatalInitializationError()
#3 0x0000029f5202 content::ContentMainRunnerImpl::Initialize()
#4 0x000003d6b528 service_manager::Main()
#5 0x0000029ee4a1 content::ContentMain()
#6 0x000002ae077d headless::(anonymous namespace)::RunContentMain()
#7 0x000002ae0808 headless::HeadlessBrowserMain()
#8 0x000002a2e84a headless::HeadlessShellMain()
#9 0x7fada634f830 __libc_start_main
#10 0x00000124f02a _start



TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/puppeteer_test/node_modules/puppeteer/lib/Launcher.js:291:14)
    at Interface.helper.addEventListener (/home/puppeteer_test/node_modules/puppeteer/lib/Launcher.js:280:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:9576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by entrptaher** [comment]
Still it seems a file permission error to different user group, see [here](https://stackoverflow.com/a/50174004/6161265).
