### ISSUE TITLE
Feature request: add an option to control all default timeouts in one place

### ISSUE THREAD

**Issue by yanivefraim** [puppeteer/puppeteer#3158]
Use case:

I want to debug my browser code, during a test, by adding `debugger` to my production code (see [Debugging tips, section 4](https://github.com/GoogleChrome/puppeteer#debugging-tips)). The problem is that I have all kind of `waitForXXX` functions in my tests, which fails for 30000ms (default) timeout. 

Looking at Puppeteer's waitForXXX functions (and all of its other goto / Launch timeouts), revealed that we have:

1. Hard coded 30000ms, written in many places, as default (for example,  FrameManager's `_waitForSelectorOrXPath`, `waitForFunction`, and Page's `_defaultNavigationTimeout`, `waitForRequest` and `waitForResponse`)
2. I do not have an option to define a new default timeout in one place, so it will affect all different places

Optional solutions: 

1. Have my own default timeout object, and pass it everywhere (as described [here](https://github.com/GoogleChrome/puppeteer/issues/1160#issuecomment-340858011))
2. Supply an api in Puppeteer to configure default timeout, which will affect all in places

**Comment by aslushnikov** [comment]
@yanivefraim yeah we've discussed this awhile ago, I'm surprised we didn't add it to the 2.0 changes. The plan is to have a single `puppeteer.setDefaultTimeout` instead of the `puppeteer.setDefaultNavigationTimeout` that will override all default timeouts in the API.

Will it work for you?

**Comment by yanivefraim** [comment]
@aslushnikov - yes, it will be great! I will be happy to help with that (if we're ready for V2.0)

**Comment by aslushnikov** [comment]
> I will be happy to help with that (if we're ready for V2.0)

@yanivefraim Thanks! We're almost ready; we plan to start working on 2.0 in a month

**Comment by yanivefraim** [comment]
@aslushnikov - supercool. I will be more than happy to assist!
