### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by maclover7** [puppeteer/puppeteer#316]
Per the [package.json file](https://github.com/GoogleChrome/puppeteer/blob/master/package.json), it looks like puppeteer only works on Node versions `>=7.10.0`. Would you be willing to maintain this package on the Node 6 release line, since it is the current LTS version?

**Comment by JoelEinbinder** [comment]
We don't have any plans to work with Node 6 at this point. Considering how much we rely on newer JavaScript features, supported Node 6 would be difficult for us to support. We don't want to take on the cost of a compile step or fracture our codebase.

**Comment by rwjblue** [comment]
Seems pretty surprising to specifically not support the current node LTS version.

**Comment by pavelfeldman** [comment]
Node 8 goes LTS in October 2017. It is likely that Puppeteer will go stable 1.0 right after that.

**Comment by waynerobinson** [comment]
Yeah, Node 6.10 support would help potentially being able to get this to work in AWS Lambda.

**Comment by mgcrea** [comment]
Encountering this as well, since our production services all run on LTS, risk is too high to start developing/testing on a different non-LTS version not matching production env.

Looks like it could easily be fixed with some babel plugins without changing anything, like [transform-async-to-generator](https://babeljs.io/docs/plugins/transform-async-to-generator) or a preset.

When 8.0 reaches LTS you could then consider deprecating legacy support, and dropping it a couple of months later?

**Comment by rfink** [comment]
Has anybody been able to actually get this working on lambda? The download size of puppeteer alone is larger than the max size allowed by lambda.

**Comment by brafdlog** [comment]
I was able to upload it to lambda after deleting a few of the locale files inside chrome but it would not run. Some issue with permissions. Haven't figured it out yet.

**Comment by alixaxel** [comment]
@rfink @brafdlog I managed to deploy a [compiled version of Chromeless](https://github.com/adieuadieu/serverless-chrome/blob/master/chrome/README.md) compressed with Brotli along with a trimmed down version of [iltorb](https://www.npmjs.com/package/iltorb) for decompressing it in under 34MiB ZIP package.

It also [decompresses faster](https://github.com/sambaiz/puppeteer-lambda-starter-kit/issues/2).

**Comment by bluepeter** [comment]
@alixaxel mind forking one of those repos, or making a new one, with your Chrome builds? ... particularly the one that clocks in at 34mb, as well as the "trimmed down" versions of related modules. or post the gist steps?

**Comment by sushant-j** [comment]
@mgcrea  - Looking to run it on 6.10, but getting `ReferenceError: regeneratorRuntime is not defined` error. Something I am doing wrong?

**Comment by JoelEinbinder** [comment]
@sushant-j You can't use async functions in `page.evaluate` or equivalent methods if you are using a transpiler like babel or regenerator.
