### ISSUE TITLE
Are unit tests failing ?

### ISSUE THREAD

**Issue by vaibhav-kb** [puppeteer/puppeteer#3161]
**My environment:**

* Puppeteer version: v1.7.0
* Platform / OS version: Windows 10
* Node.js version: v10.8.0

**Steps to reproduce the problem**

_Code that reproduces the issue._
 `npm run unit`

**Unit test results are as follows**

![screenshot 2](https://user-images.githubusercontent.com/23206976/44854057-3a16ca00-ac85-11e8-831d-4c503ef81445.png)
![screenshot 3](https://user-images.githubusercontent.com/23206976/44854059-3a16ca00-ac85-11e8-9c00-6ad50bebe7f9.png)
![screenshot 4](https://user-images.githubusercontent.com/23206976/44854060-3aaf6080-ac85-11e8-88a5-96a5eca5a407.png)

**Comment by aslushnikov** [comment]
> Are unit tests failing ?

@bvaibhav95 We have a few tests that are "flaky", meaning there are some race conditions somewhere.  I've never seen that many failures though; I wonder if it has anything to do with your environment. 

If you have time to investigate what's going on at least in some of the cases, or share  some details regarding the behavior, it will be very beneficial for Puppeteer.

**Comment by vaibhav-kb** [comment]
Sure, I will test in other environments and reply back

Thanks alot for replying

**Comment by vaibhav-kb** [comment]
@aslushnikov hey , all test are passing on the Ubuntu 18.04
I tried to understand why It was failing on windows 10, but couldn't get my head around. 
Can you throw some light on **why it was failing on Windows 10** ?

**Comment by aslushnikov** [comment]
> Can you throw some light on why it was failing on Windows 10 ?

@bvaibhav95 Sure. We know some of the css coverage tests are flaky on win (at least that's what we observe on appveyour). We didn't get time to explore the core issues though; probably something related to coverage implementation in chromium.

In your case however, something really tricky happened. The "procerss with PID cannot be terminated" messages you get while running tests are very unusual.

**Comment by vaibhav-kb** [comment]
Ok...got it!

**Comment by JoelEinbinder** [comment]
I'd suspect that you checked out the repo with the wrong line endings. All of your text file comparisons failed.

**Comment by aslushnikov** [comment]
> I'd suspect that you checked out the repo with the wrong line endings. All of your text file comparisons failed.

That's a very probable cause. I'll speculatively close this.
