### ISSUE TITLE
Display Server & Puppeteer

### ISSUE THREAD

**Issue by parvathi** [puppeteer/puppeteer#3162]
Hi,

We are trying to use the latest version of puppeteer which is using Chromium version 58. We are trying to install in cloud foundry but some x server files are missing and we are having to manually deploy this. It looks like Chrome 59 doesn't depend on display server. If we use Chrome version 59 with puppeteer instead of chromium that comes with it, is it guaranteed to work? Or is there a plan for Chromium to get away from display server?

thanks
Parvathi

**Comment by aslushnikov** [comment]
> We are trying to use the latest version of puppeteer which is using Chromium version 58

This doesn't look right: pptr v1.7.0 uses Chromium 70.

>  If we use Chrome version 59 with puppeteer instead of chromium that comes with it, is it guaranteed to work?

No it's not; see our [faq entry](https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy) on why.

> Or is there a plan for Chromium to get away from display server?

I'm not aware of such plans; but I'd rather ask this on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev)
