### ISSUE TITLE
Why can't Page.mouse successfully open select elements ?

### ISSUE THREAD

**Issue by harshayburadkar** [puppeteer/puppeteer#3164]
When I use mouse.down or mouse.click on a position where a select element is, it isn't successfully opening it. 
I want to emulate a 'robot' instead of using page.select. 

Isn't page.mouse emulating real mouse events?

**Comment by aslushnikov** [comment]
> Isn't page.mouse emulating a real mouse events?

Puppeteer's mouse is emulated at the low *browser* level. This is very real from the page's point of view, but not enough to open "select" because it's an OS-level widget.

Hope this helps!
