### ISSUE TITLE
Feature: add getEventListeners listeners API

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#3166]
DevTools cmd line has a great `getEventListeners` features for looking up the listeners on a node. I've found a couple of situations where it would be useful to know the event listeners attached to an element, `window`, and `document`:

- `elementHandle.getEventListeners` would be useful for custom elements. You could discover what custom events a web component responds to.
- be able to look at the top level `document` and `window` listeners on a page and assert my entire site (including 3rd party libs) are using passive event listeners, etc.

**Comment by mcshaman** [comment]
I posted a [solution to this problem](https://github.com/GoogleChrome/puppeteer/issues/1919)

**Comment by vdeturckheim** [comment]
FYI I have a quickfix here
```js
const { ElementHandle } = require('puppeteer/lib/ExecutionContext');
ElementHandle.prototype.getEventListeners = function () {
    return this._client.send('DOMDebugger.getEventListeners', { objectId: this._remoteObject.objectId });
};
```
I am not sure what is the process to PR this. If it is straightforward I'd be happy to do it but I feel this opens a pndora box for event(Listeners)-related features.

**Comment by ali-habibzadeh** [comment]
Any updates on this?

**Comment by davidpfahler** [comment]
Unfortunately, @vdeturckheim (no longer) works. Is there any possibility we can get this API into puppeteer? 

EDIT: [This method](https://github.com/puppeteer/puppeteer/issues/3618#issuecomment-469706603) currently works as a work around.

**Comment by bv-sumit** [comment]
The above solutions didnt work for latest version of puppeteer as the directory structure is changed.

https://stackoverflow.com/questions/75517220/geteventlistener-function-support-for-latest-puppeteer-versions/75581410#75581410
I have mentioned the solution in the above link. If anyone is facing the issue you can refer.
