### ISSUE TITLE
Puppeteer with Chrome instead of Chromium ( Zip vs Debian)

### ISSUE THREAD

**Issue by parvathi** [puppeteer/puppeteer#3167]
Hi,

We would like to use Chrome with Puppeteer instead of Chromium since Chromium requires display server client libraries. We can't deploy those libraries in cloud foundry due to security setup. We can't deploy Chrome debian package again due to same security setup as it will require Sudo and could be deploying libraries at OS level. It would help if we have a self contained Chrome zip file that we can deploy with puppeteer. So is there a Chrome Zip library version available? - Something similar to the Chromium one listed below?

https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/587164/

thanks
Parvathi

**Comment by aslushnikov** [comment]
> So is there a Chrome Zip library version available?

I'm not aware of any. I'd ask on chromium-dev google group, maybe folks over there would be able to help.
