### ISSUE TITLE
node GLib-CRITICAL

### ISSUE THREAD

**Issue by AnthoniG** [puppeteer/puppeteer#3168]
I am trying to run a simple test in puppeteer but I keep getting this error all the time. The full error is 

**(node:12326): GLib-CRITICAL **: Source ID 21 was not found when attempting to remove it**

I have tried to put try / catch in there hooping to eliminate to, to no avail. Tried googling but could not find anytthing about and now I am puzzled.

Any one any idea what's going on please ?

**Comment by aslushnikov** [comment]
I'm not sure we can be of any help here; this has something to do with your environment. I'd try asking at node's bugtracker.
