### ISSUE TITLE
White screenshots with deviceScaleFactor 2 

### ISSUE THREAD

**Issue by luminous8** [puppeteer/puppeteer#3169]
### Steps to reproduce
I can reproduce in try-puppeteer.appspot.com but it works locally as well.

**Tell us about your environment:**

* Puppeteer version: 1.7.0
* Platform / OS version: Linux
* URLs (if applicable): https://smooch.io/
* Node.js version: v8.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

With a basic example code on https://try-puppeteer.appspot.com/
`const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 })
await page.goto('https://smooch.io/');

console.log(await page.content());
await page.screenshot({path: 'screenshot.png', fullPage: true });

await browser.close();`

If I remove the deviceScaleFactor option or change it by 1, it works.
Also it works on Pptraas https://pptraas.com/screenshot?url=https://smooch.io/

I should notice that it doesn't do that on all website, but I got this issue with smooch.io

**What is the expected result?**
A screenshot of the page white page with the right height & width
_(the screenshot below is the result with deviceScaleFactor at 1, but the expected result is the same with dpi at 2)_
![0a12455c-e976-463d-9220-4a0778d94d2f](https://user-images.githubusercontent.com/17875165/44944889-0d76c580-addf-11e8-8c7a-2f6edf8c22d0.png)

**What happens instead?**
A white page with the right height & width

![163d0a0c-9013-4dfb-b6c5-d14664a78227](https://user-images.githubusercontent.com/17875165/44944885-fcc64f80-adde-11e8-9525-1dfc77412ac7.png)

**Comment by lusarz** [comment]
I investigated a bit and I've found that when `width > 767` - screenshot is white, for example:
      
    await page.setViewport({ width: 768, height: 900, deviceScaleFactor: 2 })

otherwise it works:

    await page.setViewport({ width: 767, height: 900, deviceScaleFactor: 2 })

I've also run this example in no-headless mode and with `env DEBUG="puppeteer:*`. I observed that browser page really become white for a while during screenshot operation.

**Comment by lusarz** [comment]
After more investigation I discovered that this issue is caused by [`jQuery.onFontResize`](https://gist.github.com/lusarz/2f9fb450ef37393fde708b7882a0593d) code from https://smooch.io/js/jquery.main.js (line 1386).

**Comment by luminous8** [comment]
@lusarz Wow, good catch! 
How do you find it?
Do you think that removing jquery just before taking the screenshot would work?

**Comment by lusarz** [comment]
@luminous8 
I downloaded page into localhost, and did experiments with html and js. I discovered that remove 
   
    <script type="text/javascript" src="/js/jquery.main.js"></script>
line cause fix of this problem, so I started to investigate inside this script.

I'm not sure if removing jquery just before taking screenshot would work - seems like `iframe.font-resize-helper` created by this script is main issue here. You can try to try to remove it, maybe something like that:

    await page.evaluate(() => {
        var element = document.querySelector('.font-resize-helper');
        element.parentNode.removeChild(element);
    })

I didn't tested it - just write from head. Let me know if it would not help - I can try to find better solution.

**Comment by luminous8** [comment]
Wow! thanks so much for taking the time to dig into this.
I wouldn't have found this by myself. (:

**Comment by lusarz** [comment]
You're welcome, I'm glad I was able to help :)
