### ISSUE TITLE
Response improvements

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#317]
For further parity with https://developer.mozilla.org/en-US/docs/Web/API/Response, these would be useful to add

- [x]  `Response.statusText `
- [x]  `Response.redirected `
- [x] `Request.type `

**Comment by aslushnikov** [comment]
We gave up on aligning with fetch api: #106 

So we'd rather not add anything to the api unless there's a real-world user scenario to prove the necessity.

**Comment by ebidel** [comment]
I filed this because I ended up wanting all 3 when trying out network interception apis for the first time. If I ran into it in < 5min I suspect others will want it to.

use cases:
- `Response.type` in particular is pretty handy to know the initiator of a request (xhr, script, parser).
- `statusText` is useful b/c people parse out custom messages from server responses. -
- `Response.redirected` is just nice to know.

**Comment by ebidel** [comment]
BTW, we should try to keep features requests open so people can find and subscribe to them more easily. Also helps us prioritize!

**Comment by aslushnikov** [comment]
> Response.type in particular is pretty handy to know the initiator of a request (xhr, script, parser). 

That's not what response.type is: https://developer.mozilla.org/en-US/docs/Web/API/Response/type
Do you mean [request.type](https://aslushnikov.github.io/vanilla-protocol-viewer/#Network.requestWillBeSent)?

The `response.redirected` is easy to polyfill:
```js
let redirected = 300 <= response.statusCode && response.statusCode <= 399;
```

> statusText is useful b/c people parse out custom messages from server responses.

Ahh, I see. We should plumb this from interception then.

> BTW, we should try to keep features requests open so people can find and subscribe to them more easily. Also helps us prioritize!

That's right, however we don't want to be buried under the unmanageable pile of issues. For this reason we aggressively close everything we don't feel like implementing. It's totally fine to comment or reopen to argue :)

**Comment by ebidel** [comment]
Yep, `request.type`.

**Comment by itaysabato** [comment]
`statusText` seems like a very basic (and easy) thing to expose. And I need it :)

**Comment by aslushnikov** [comment]
@itaysabato we don't have status text for the intercepted requests; however, we'll get it for free once a huge on-going refactoring of network layer in chromium completes. No good ETA on this though.
