### ISSUE TITLE
Non-standard HTML elements in head are moved to body

### ISSUE THREAD

**Issue by jodelamo** [puppeteer/puppeteer#3175]
Backstory: I have a web application that I intend to prerender, using [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin), which in turn uses Puppeteer.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `v1.7.0`
* Platform / OS version: macOS, Docker
* URLs (if applicable):
* Node.js version: `v8.10.0`

**What steps will reproduce the problem?**

Placing any non-standard HTML element in `head` will move them to `body`. This makes it difficult when using edge side includes (`esi:include` and `esi:vars` elements, for example).

Before:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, nofollow">
  <esi:include src="/head.html"></esi:include>
  <title>Test</title>
</head>
<body>
  <h1>Test</h1>
</body>
</html>
```

After:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, nofollow">
  <title>Test</title>
</head>
<body>
  <esi:include src="/head.html"></esi:include>
  <h1>Test</h1>
</body>
</html>
```

Can this behavior be disabled?

**What is the expected result?**

`esi:include` elements are unaffected.

**What happens instead?**

`esi:include` elements in `head` are moved to `body`.

**Comment by JoelEinbinder** [comment]
This is how Chrome parses your page. If I understand correctly, `esi` tags are supposed to be processed out by the webserver. It looks like something else has probably gone wrong in your situation.
