### ISSUE TITLE
Intermittent Timeouts on Linux (Docker)

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#3177]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7.0
* Platform / OS version: Docker node image (Debian Jessie 8.11)
* Node.js version: 9.11.2

**What steps will reproduce the problem?**

I've attached two Dockerfiles. `Dockerfile.current` is the one the latest image is build from. It contains more or less what your docs recommend. `Dockerfile.other` is the one I was using before that. I've noticed no difference in behavior between the two.

On osX, this works 100% of the time. On Linux it fails at least 50% of the time (by which I mean it times out):

```
/** 
* Locally (on osX), config.Puppeteer.browserOpts is {}
* In the Linux container, it's 
* {
*	"executablePath": "google-chrome-unstable",
*	"args": ["--disable-dev-shm-usage"]
* }
*/
const browser = await launch(config.Puppeteer.browserOpts),
        page = await browser.newPage();

await page.goto(config.loginPage);

// Enter credentials and submit form
await page.type('#username', credentials.username);
await page.type('#password', credentials.password);
await page.click('#submit');

// THIS IS WHERE THE TIMEOUT OCCURS, WHEN IT OCCURS
await page.waitForNavigation();

return { success: true }
```

**What is the expected result?**
I would hope that it either works or fails consistently. 

**What happens instead?**
It works maybe 30% of the time and fails the rest of the time.

[Dockerfile.current.txt](https://github.com/GoogleChrome/puppeteer/files/2343643/Dockerfile.current.txt)
[Dockerfile.other.txt](https://github.com/GoogleChrome/puppeteer/files/2343644/Dockerfile.other.txt)

**Comment by ebidel** [comment]
This looks like a classic race condition with hitting a submit button and waiting for the navigation to occur. Can't explain the difference between mac and linux, but the pattern we recommend for this is:

```
const [response] = await Promise.all([
  page.waitForNavigation(...),
  page.click('#submit'),
]);
```

https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-pageclickselector-options

**Comment by ghost** [comment]
@ebidel that does appear to mitigate the errors, but not squash them. It seems like pretty consistently I'll get a timeout the first time I try it, then success on each subsequent run. I'll keep messing with it though. Thanks for pointing me in the right direction 👌

**Comment by rostgoat** [comment]
seems like everytime I use the pattern metioned by @ebidel I get a 

```
 { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
        at Promise.then (/home/matthew/Work/madison-puppeteer/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21)
        at <anonymous>
      -- ASYNC --
        at Frame.<anonymous> (/home/matthew/Work/madison-puppeteer/node_modules/puppeteer/lib/helper.js:108:27)
        at Page.waitForNavigation (/home/matthew/Work/madison-puppeteer/node_modules/puppeteer/lib/Page.js:676:49)
        at Page.<anonymous> (/home/matthew/Work/madison-puppeteer/node_modules/puppeteer/lib/helper.js:109:23)
        at ClickMethods.waitForNavigation [as singleClickElement] (/home/matthew/Work/madison-puppeteer/test/e2e/methods/common/click.js:5:14)
        at SuperClientCreate.singleClickElement [as createSuperClient] (/home/matthew/Work/madison-puppeteer/test/e2e/methods/super/clients/add.method.js:16:17)
        at <anonymous> name: 'TimeoutError' }

```

I have my function abstracted in a separate class and looks like so

```
async singleClickElement(selector, page) {
    try {
      await Promise.all([
        page.waitForNavigation({
          waitUntil: 'networkidle2',
          // timeout: 0
        }),
        page.waitForSelector(selector),
        page.click(selector),
      ]);
    } catch (error) {
      console.error(error)
    }
  }
```

Originally I never used the "suggested" anti-race-condition pattern recommended in the docs. When I did so, my code ran fine locally but failed about 80% in docker (I assume due to various other race conditions). After implementing the suggested pattern I get the timeout error. Any idea why this might be happening?

**node** : v8.10.0
**npm** : 6.9.0
**puppeteer** : ^1.13.0

**Comment by xse** [comment]
@rostgoat hey, if puppeteer doesn't "navigate to a new URL or reloads" it won't resolve, waitForSelector might be more useful depending on what you're doing. 

Like for example clicking on a menu which generate a request which then displays another menu or something, waitForNavigation won't resolve if the url doesn't change.

**Comment by rostgoat** [comment]
thanks I'll keep that in mind
