### ISSUE TITLE
Errors when running Chrome through puppeteer

### ISSUE THREAD

**Issue by Janpot** [puppeteer/puppeteer#3178]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7
* Platform / OS version: MacOS 10.13.6
* URLs (if applicable): Any website built with Wix (using http://www.goodfeelinggoods.com/ as an example)
* Node.js version: 10.7.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.setUserAgent('bot');
  await page.goto('http://www.goodfeelinggoods.com/');
})();
```

1. Run the above code

**What is the expected result?**

The website is rendered in the browser window. No errors in the devtools console

**What happens instead?**

The page crashes, the window stays white and the console shows the error:

![screen shot 2018-09-03 at 16 20 26](https://user-images.githubusercontent.com/2109932/44991867-d4cd1c80-af95-11e8-9b61-7ae4d3581595.png)

It only happens when user agent string contains the word "bot". So it clearly means they return different content depending on the user-agent. Which is quickly verified by going to the page manually in Chrome. However, when overriding user agent in a chrome instance that is not controlled by `puppeteer`,  the page renders correctly, even when user-agent contains the word bot, as can be seen in the screenshot:

![screen shot 2018-09-03 at 16 20 12](https://user-images.githubusercontent.com/2109932/44991965-237ab680-af96-11e8-8698-d20ddc4474ff.png)

This was done on the exact same version of chrome (`Version 71.0.3541.0 (Official Build) canary (64-bit)`), except one is started and controlled with `puppeteer`, the other is started and controlled manually.
It looks as if when Chrome is being controlled with the devtools protocol, something in the prefetching logic behaves differently somehow.

**Comment by Janpot** [comment]
Ok, can confirm it's the `--enable-automation` flag that flips this behavior. Starting the browser with only this flag makes it error this way. Starting without works perfectly fine.
Any clue on where to look on what makes this website able to behave differently whether it's started with or without this flag? Are any extra headers being sent?

**Comment by aslushnikov** [comment]
@Janpot the most prominent thing `--enable-automation` does is injecting `navigator.webdriver` into every page, and I think this is what's giving up Puppeteer here.

In general, there are many other ways to detect headless. Both detections and evasions are collected here: https://github.com/paulirish/headless-cat-n-mouse
