### ISSUE TITLE
When I start the program, how do I cancel the text prompt above the browser?

### ISSUE THREAD

**Issue by aixinalei** [puppeteer/puppeteer#3182]
![image](https://user-images.githubusercontent.com/24827011/45015517-977b9400-b054-11e8-8bf4-84cf8f6867bf.png)

**Comment by aixinalei** [comment]
browser = await puppeteer.launch(
    {
      ignoreDefaultArgs:['--enable-automation']
    }
  );

**Comment by vsemozhetbyt** [comment]
About `--enable-automation` issues, see https://github.com/GoogleChrome/puppeteer/issues/3178
