### ISSUE TITLE
Custom Fonts not loaded when pdf generated

### ISSUE THREAD

**Issue by KrifaYounes** [puppeteer/puppeteer#3183]
I try to generate a PDF with custom font but it doesn't work when I inject fonts like this : 

```
import { injectGlobal } from 'styled-components'
import Book from './assets/fonts/718/sevenoneeight-medium.woff2';
import Book2 from './assets/fonts/718/sevenoneeight-medium.woff';

injectGlobal `
@font-face {
	font-family: "718book";
	src: url(${Book}) format("woff2"),
		url(${Book2}) format("woff");
}

body {
  font-family: '718book';
  -webkit-print-color-adjust: exact;
}
`;
```

Someone have an idea how to import fonts correclty ?
I need a solution that works with any url -> http://localhost:3000, http://xxxxx.com ....

It works when I generated a fonts folder in my build and I inject fonts like this : 
```

injectGlobal `
@font-face {
	font-family: "718book";
	src: url('http://localhost:3000/fonts/718/sevenoneeight-medium.woff2') format("woff2"),
		url('http://localhost:3000/fonts/718/sevenoneeight-medium.woff') format("woff");
}
`;
```

I convert my html to pdf like this : 

```
let convertHTMLToPDF = async (html, callback, options = null) => {
    if (typeof html !== 'string') {
        throw new Error('xxxx.');
    }
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setRequestInterception(true);

    page.once('request', request => {
        request.respond({ body: html });
        page.on('request', request => request.continue());
    });

    const response = await page.goto('https://google.com');
    await page.setContent((await response.buffer()).toString('utf8'));
    await page.evaluateHandle('document.fonts.ready');
    await page.pdf(options).then(callback, function(error) {
        console.log(error);
    });
    await browser.close();
};
```

**Comment by krokofant** [comment]
If you intend to use this only for pdf then maybe you could base64 encode the font and load it via url.

**Comment by AlaaHamoudah** [comment]
I ams still facing this issue, @aslushnikov do you have any suggestions?

**Comment by lovenick** [comment]
Not sure if you've seen #422 , but it might be relevant to your issue.

**Comment by shibli786** [comment]
I also facing the same issue. I have attached the PDf file generated from Puppeteer.
However, in my case I am using all my custom fonts base64 encoded.
 The page is rendered properly in chrome, chromium and also I tested headless: false, in all these case pages is rendered fine.
But in headless: true  all font is missing. 
[hn.pdf](https://github.com/GoogleChrome/puppeteer/files/3800603/hn.pdf)

@font-face
	{
                font-family:ffc; 
		src:url('data:application/font-woff;base64,d09....)format("woff");
      }

.ffc{font-family:ffc;line-height:1.589369;font-style:normal;
          		font-weight:normal;
			visibility:visible;
	}

**Comment by haan123** [comment]
Hi @shibli786,

I have found a work around, it seem like the font need to be rendered as lead one time, so i have create a dummy `div` right after `body` tag to render that font, e.g,
``` html
<body>
<div class="__dump ff36">_</div>
...
</body>
```

See my real code here:
``` javascript
const rfont = /@font-face.*font-family:([^;]+)/g;

function prepareContent(html) {
  const $ = cheerio.load(html);
  const $body = $('body');
  const $style = $('style');
  const fonts = [];

  $style.each((_, elem) => {
    const $this = $(elem);

    $this.html().replace(rfont, (_, font) => fonts.push(font));
  });

  fonts.forEach((font) => {
    $body.prepend(`<div class="__dump ${font}">_</div>`);
  });

  return $.html();
}

(async () => {
  html = prepareContent(html);

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  // await page.goto(`file:${path.join(__dirname, 'books/Computer Programming with C++/1 - Introduction.html')}`, {
  await page.setContent(html);
  await page.evaluateHandle('document.fonts.ready');
  await page.evaluate(() => {
    var dumps = document.querySelectorAll('.__dump');
    dumps.forEach((dump) => dump.parentNode.removeChild(dump));
})
  await page.pdf({path: 'hn.pdf', format: 'A4'});

  await browser.close();
})();
```

**Comment by sorkhemiri** [comment]
i had the same issue. i finally ended up using fonts served in directory on public URL as CDN and it works fine for me right now.

**Comment by elrumordelaluz** [comment]
I'll expose my tests in case is useful for anyone to continue debug or to find a better solution:

I am generating a [pdf](https://github.com/puppeteer/puppeteer/blob/v3.1.0/docs/api.md#pagepdfoptions) from an `html` string. Something like:

```js
await page.goto(`data:text/html,${htmlString)}`, { waitUntil: 'networkidle0' })
const pdf = await page.pdf()
```

Since the html string uses an external font I tried different options that I'll describe below. However only the last one works without differences on two environments.
I am testing in local using OSX and in an external server using Linux. 
Here are the different options I tried:

- Adding `@import url('https://fonts.googleapis.com/css2?family=…');` into a `<style>` tag of the html string passed
- Passing that `url` as [addStyleTag](https://github.com/puppeteer/puppeteer/blob/v3.1.0/docs/api.md#pageaddstyletagoptions) url
- Serving the web fonts and _stylesheet_ in the same server where `puppeteer` is working and passing a [addStyleTag](https://github.com/puppeteer/puppeteer/blob/v3.1.0/docs/api.md#pageaddstyletagoptions) path
- Also tried playing with `await page.evaluateHandle('document.fonts.ready')` and another `waitUntil` values.

In all those scenarios, the resulting `pdf` were generated with the wrong `font` and using different fallback, since are different operating systems.

The solution that works cross platform is to pass this `css` declaration inside the `html` string:

```css
@font-face {
      font-family: 'Inconsolata';
      src: url(data:application/font-woff2;charset=utf-8;base64,…),
         url(data:application/font-woff;charset=utf-8;base64,…);
      font-weight: normal;
      font-style: normal;
}
```

I hope there are better solutions since the base64 string for only one style of a font family is pretty big, and increases in cases where more styles or families are needed in the same page.

**Comment by billyvg** [comment]
@elrumordelaluz Have you tried the above with `page.setContent` instead of `page.goto`?

**Comment by 616b2f** [comment]
@elrumordelaluz @billyvg What worked for us is to wait till the font's are actually loaded, using this command:

```
await page.evaluateHandle('document.fonts.ready');
```

This seems the best solution so far. As you can use custom fonts that are registered system wide and do not need to load them as base64 strings.

All credits go to this post: https://github.com/puppeteer/puppeteer/issues/422#issuecomment-708142856

**Comment by thomasdvd** [comment]
I have tried some of the solutions above but none of them hold up when generating 30+ pdfs

so i ended up doing this

```javascript
try {
	await page.goto(url, { waitUntil: 'load', timeout: 5 * 1000 });
} catch {
	await page.goto(url, { waitUntil: 'networkidle2', timeout: 15 * 1000 });
}
```

giving puppetteer some room to breath between opening pages also seems to help , as I had very inconsistent results

**Comment by wakproductions** [comment]
None of the above solutions to fix the loading issues worked for me. I've done the base 64 encoding and the time delay hacks. The page and its custom fonts render fine through the web browser, but show up blank in the PDF. What worked for me what installing the font in the OS as a system font and then referencing it by name in the style sheet. For my Linux instance, and in Docker, copying the TTF file into `/usr/share/fonts/truetype` resolved the font anomalies in PDF generation.

**Comment by ahmafi** [comment]
I have the same issue currently, and It's probably not a network-related issue, because the fonts are loaded, I can see the correct fonts when I take a screenshot exactly before generating the PDF, but the fonts are not loaded in PDF for some reason.

For now, changing the puppeteer product to firefox fixed this issue.

**Comment by alexzimin-io** [comment]
We also noticed that custom fonts sometimes don't render in PDFs created with Puppeteer 14.3.0 and Node 12.22.8

**Comment by piyushk96** [comment]
you can try this https://github.com/alixaxel/chrome-aws-lambda/issues/246#issuecomment-1205412171

**Comment by stevecj** [comment]
> I have tried some of the solutions above but none of them hold up when generating 30+ pdfs
> 
> so i ended up doing this
> 
> ```js
> try {
> 	await page.goto(url, { waitUntil: 'load', timeout: 5 * 1000 });
> } catch {
> 	await page.goto(url, { waitUntil: 'networkidle2', timeout: 15 * 1000 });
> }
> ```
> 
> giving puppetteer some room to breath between opening pages also seems to help , as I had very inconsistent results

I don't know yet whether it will work in all cases, but this is the first thing that worked for me.

Can you say more about what this does? It looks to me like it does not actually add a time delay. It just waits for load instead of for networkidle2. Is that right? Since others have said this doesn't help them, would it help to add an actual sleep as well, and how should that be done?

**Comment by stevecj** [comment]
> > I have tried some of the solutions above but none of them hold up when generating 30+ pdfs
> > so i ended up doing this
> > ```js
> > try {
> > 	await page.goto(url, { waitUntil: 'load', timeout: 5 * 1000 });
> > } catch {
> > 	await page.goto(url, { waitUntil: 'networkidle2', timeout: 15 * 1000 });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > giving puppetteer some room to breath between opening pages also seems to help , as I had very inconsistent results
> 
> I don't know yet whether it will work in all cases, but this is the first thing that worked for me.
> 
> Can you say more about what this does? It looks to me like it does not actually add a time delay. It just waits for load instead of for networkidle2. Is that right? Since others have said this doesn't help them, would it help to add an actual sleep as well, and how should that be done?

It turns out that only worked for me on the first try. :(

**Comment by evmer** [comment]
In some cases this is a bug related to the Access-Control-Allow-Origin limitations.

If you trust the url source, adding `--disable-web-security` fixes the issue.

**Comment by aneuwald** [comment]
> In some cases this is a bug related to the Access-Control-Allow-Origin limitations.
> 
> If you trust the url source, adding `--disable-web-security` fixes the issue.

Worked like a charm! Thansk @evmer !

**Comment by kkarkos** [comment]
Try `await page.waitForFunction('document.fonts.ready');`

**Comment by skerit** [comment]
The only thing that worked for me was base64 inlining the fonts.

**Comment by mariusrak** [comment]
> Try `await page.waitForFunction('document.fonts.ready');`

I tried this and my webfonts do not appear. If I use `waitUntil: "networkidle0"` they work correctly. But it adds 500ms, which I don't like. So is there a way to make use of the `document.fonts.ready`?
Thanks.

**Comment by mariusrak** [comment]
I used ` waitUntil: "load"` and then `await page.waitForFunction('document.fonts.ready');` and it works correctly. But I shaved off only like 50ms :D

**Comment by gabrielmicko** [comment]
`await page.evaluateHandle('document.fonts.ready');` did the trick for me, thank you.

**Comment by luopeihai** [comment]
I run successfully, as follows
```diff
 const browser = await puppeteer.launch(
                {
                    headless: true,
                    args: [
                        '--no-sandbox',
                        '--disable-setuid-sandbox',
                        '--font-render-hinting=none',
+                        '--font-family=Microsoft YaHei'
                    ]
                }
            );
```
I do not recommend using base64 to write the font, so the generated pdf size will be very large, it is recommended to pass the system through the corresponding font way: https://medium.com/@ggluopeihai/best-practices-for-scraping-html-to-generate-pdf-with-puppeteer-0f6e13c84f0f
