### ISSUE TITLE
Win10 x64 always throws timeout

### ISSUE THREAD

**Issue by dnl1** [puppeteer/puppeteer#3186]
Hey guys, i'm stucked into a problem.

`const browser = await puppeteer.launch({ headless: false });`

Chromium open but, always throws timeout exception:

`TimeoutError: Timed out after 120000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r579032
    at Timeout.onTimeout (C:\git\view-render\node_modules\puppeteer\lib\Launcher.js:310:14)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)`

**Comment by piampri** [comment]
Is this problem gonna be addressed ? It is on-going it appears

**Comment by aslushnikov** [comment]
@dnl1 @piampri what's you pptr version? Can you paste the whole script you try to run? Is there any firewall/antivirus software that might prevent connecting to chromium's web socket?

**Comment by mu-yu** [comment]
Got the same error. Chromium is launched with blank page, and nothing happened until timeout error emitted after 30 seconds.And then, chromium will be auto closed.

node version: `v10.11.0`
pptr version: `1.8.0` / `1.9.0`
win10 version:  `1803 / 17134.167`

demo script:
```
(async () => {
  try {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.goto('https://www.google.com')

    await browser.close()
  } catch (e) {
    console.log(e)
  }
})()
```

error message:
```
{ TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r588429
    at Timeout.onTimeout (D:\code\path\to\projAddr\node_modules\puppeteer\lib\Launcher.js:344:14)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) name: 'TimeoutError' }
```

**Comment by shulamyt** [comment]
I have same problem..

**Comment by noamshay** [comment]
please fix this issue.. it's a pain for me as well

**Comment by mu-yu** [comment]
I have debug the launcher.js today, found that timeout was happened on `waitForWSEndpoint`,
```javascript
 const rl = readline.createInterface({ input: chromeProcess.stderr });
    let stderr = '';
    const listeners = [
      helper.addEventListener(rl, 'line', onLine),
      helper.addEventListener(rl, 'close', () => onClose()),
      helper.addEventListener(chromeProcess, 'exit', () => onClose()),
      helper.addEventListener(chromeProcess, 'error', error => onClose(error))
    ];
    const timeoutId = timeout ? setTimeout(onTimeout, timeout) : 0; // timeout here for onLine never called
```
Could you please deep check here why `onLine` is never called. @aslushnikov 

edit: 
seems that in the `readline.js` input(chromeProcess.stderr) doesn't emit `end` correct

`chromeProcess.connected` is false after spawn. Here is some doc from nodejs.org.

> The subprocess.connected property indicates whether it is still possible to send and receive messages from a child process. When subprocess.connected is false, it is no longer possible to send or receive messages.

**Comment by mattanbi** [comment]
+1 blocker for us as well

**Comment by adihemi** [comment]
+1 I'm also facing the same problem

**Comment by vovkind** [comment]
+1

**Comment by svorach** [comment]
+1

**Comment by mu-yu** [comment]
I found this issue today https://github.com/GoogleChrome/puppeteer/issues/3681 ,and it fixed the timeout issue.

here is my test code which works fine. I dont't know why but it just work.:
```javascript
const puppeteer = require('puppeteer')

;(async () => {
  try {
    const browser = await puppeteer.launch({
      ignoreDefaultArgs: ['--disable-extensions'], // this line makes pptr work
    })
    const page = await browser.newPage()
    await page.goto('https://www.baidu.com')
    await page.screenshot({ path: 'baidu.png' })

    await browser.close()
  } catch (e) {
    console.log(e.message)
  }
```

**Comment by mu-yu** [comment]
I found several similar issues for timeout on win10x64, maybe it should be written in `/docs/troubleshooting.md `

**Comment by ThomasMcGarry101** [comment]
Has this issue been resolved in the latest release? The same issue is still permitting for me. Thanks

**Comment by aslushnikov** [comment]
@ThomasMcGarry101 check out our [windows troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-windows).

**Comment by sparker-sagrad** [comment]
I have the same issue on Windows 10. 

Adding ignoreDefaultArgs: ['--disable-extensions'], from the link above does not solve the issue.

Node v10.16.3
Puppeteer v6.4.0
