### ISSUE TITLE
Run puppeteer with exist chrome instance, throw exception when I have chinese input

### ISSUE THREAD

**Issue by fish0185** [puppeteer/puppeteer#3199]
Here is the code throw exception, when I specify executablePath with pre-installed chrome path. page.type('#input', '微软') throw exception.
```javascript
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'
    });
    const page = await browser.newPage();
    await page.goto('http://localhost:8899/');
    // works
    await page.type('#input', 'google');
    // exception
    await page.type('#input', '微软');
})();
```

**Comment by aslushnikov** [comment]
Looks like you're running incompatible chrome version against Puppeteer. More on this [in our faq](https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

There's a mapping now between chromium versions and puppeteer versions in the very beginning of our documentation: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

So if you're running chrome 67, please use Puppeteer v1.3.0

Hope this helps.

**Comment by pratik-joshi-cactus** [comment]
Not working :/ in Version 75.0.3770.100 (Official Build) (64-bit), It still opens up new instance of chrome and it has no history whatsoever, I had to open it along with my other chrome tabs.

	const puppeteer = require('puppeteer');
	const pptr = require('puppeteer-core');
	(async () => {

		const browser = await puppeteer.launch({
		  headless: false,
		  executablePath: '/usr/bin/google-chrome'
		});

	})(); 

Here I also tried puppeteer-core , means pptr variable await pptr.launch in above variable, still not working. The issues is not closed!
Please check : 
https://drive.google.com/file/d/1WKjgPeruK9-ABeHHsumhcjs_FTlzFH4S/view

**Comment by wojciech-klonowski** [comment]
I found the source of the problem using google-chrome.

https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L359

At the chromium startup, on the stdout (console) displays the 
`DevTools line listening on ws: //0.0.0.0: 9222 / devtools / browser / 66993667-8118-4701-98df-ae22d1ba9e4e`

At the start of google-chrome this line is not print out so the puppeter does not connect to the browser
