### ISSUE TITLE
am not able to add cookies with different domain .

### ISSUE THREAD

**Issue by sindhushreem** [puppeteer/puppeteer#3200]
var cookie = [
{
"domain": "hpeswlab.net",
"expirationDate": 1597288045,
"hostOnly": false,
"httpOnly": false,
"name": "key",
"path": "/",
"sameSite": "no_restriction",
"secure": false,
"session": false,
"storeId": "2",
"value": "value!",
"id": 1
},

    {
        "domain": "btpvm2216.hpeswlab.net",
        "expirationDate": 1597288045,
        "hostOnly": false,
        "httpOnly": false,
        "name": "key",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "value!",
        "id": 2
    }
]
await page.setCookie(...cookie);

**Comment by aslushnikov** [comment]
@sindhushreem please re-file with the filled issue template. A lot of details are really important there:
- pptr version
- chrome version
- your actual script that exhibits the problem
