### ISSUE TITLE
Page.click unable to click on dropdown, popconfirms, etc

### ISSUE THREAD

**Issue by aliu145** [puppeteer/puppeteer#3203]
Examples:
![image](https://user-images.githubusercontent.com/11867181/45107383-48823d00-b0ee-11e8-82e2-827cd7e8f510.png)
![image](https://user-images.githubusercontent.com/11867181/45107388-4d46f100-b0ee-11e8-84d0-4f97f2b38f43.png)

`Page.click` gets error ` Error: No node found for selector` even though the selector for the dropdown, popconfirm, etc is able to be found on the page when inspecting

**Comment by aslushnikov** [comment]
@aliu145 can you please share a script so that I can reproduce, debug and eventually fix this?

**Comment by aliu145** [comment]
I am using puppeteer with BackstopJS, but essentially the script that is run is this:

`module.exports = function click(page, scenario) {
    const clickSelector = scenario.clickSelector;

    for (const clickSelectorIndex of [].concat(clickSelector)) {
        const selector = clickSelectorIndex.selector || clickSelectorIndex;
        const count = clickSelectorIndex.count || 1;

        for (let j = 0; j < count; j++) {
            page.waitFor(selector);
            page.click(selector);
        }
    }
};

The issue is reproducible using the url `https://ant.design/components/popconfirm/` and `clickSelector` as:

`[
                {"selector": ".code-box-demo .ant-btn"},
                {"selector": ".ant-popover-inner-content .ant-btn-primary"}
            ]`

The error it produces is: `Error: No node found for selector: .ant-popover-inner-content .ant-btn-primary`

Although the selector can be found on page, and element is visible on screenshot which is produced at runtime:

![image](https://user-images.githubusercontent.com/11867181/45110207-7a979d00-b0f6-11e8-9a9b-504ab9b770bd.png)

**Comment by nateevans** [comment]
I'm getting similar failures as well... We're testing an Ember app using Puppeteer 1.7.0 and Mocha. Started getting fails related to selectors at some point today, about 9/5/18 12:30pm EST. 

Mostly just making this comment to follow the issue... pretty heavy to pull our tests and put an example here. I'm going to keep digging on my end and see what I can find.

**Comment by nateevans** [comment]
Same code seems to work fine on:

Ubuntu 16.04.5
`headless: true`
Node v10.9.0

**Comment by JoelEinbinder** [comment]
Looks like you need to await your async methods:
```js
for (const clickSelectorIndex of [].concat(clickSelector)) {
    const selector = clickSelectorIndex.selector || clickSelectorIndex;
    const count = clickSelectorIndex.count || 1;

    for (let j = 0; j < count; j++) {
        await page.waitFor(selector);
        await page.click(selector);
    }
}
```

and then mark click as async:

```js
module.exports = async function click(page, scenario) {
 ```
