### ISSUE TITLE
Puppeteer crashes on abort

### ISSUE THREAD

**Issue by drwhorx** [puppeteer/puppeteer#3205]
So I have a program that downloads a file with headful chrome but the page it downloads from is one of those that closes its own tab, so I get a whole bunch of errors like "NET::ERR_ABORTED" but like it's supposed to do that and it's prohibiting me from doing the rest of my code. Is there any way to ignore the error?

Details:
OS: macOS Mojave
Node.js version: 8.11.3
Puppeteer version: 5.6.0

**Comment by aslushnikov** [comment]
I assume you get these errors from `page.goto` command. in this case you can simply catch them.

```js
// catch and do nothing
await page.goto(url).catch(e => {});
```

**Comment by drwhorx** [comment]
Wow I'm dumb, that worked, thanks!
