### ISSUE TITLE
document.querySelector not working with variable??

### ISSUE THREAD

**Issue by drwhorx** [puppeteer/puppeteer#3206]
So I'm having a new issue with using document.querySelector. Whenever I input a normal string like this: 

```javascript
var linkHtml = await page.evaluate(() => {
return document.querySelector('#site-modal > div > div > div > div.modal-body.bb-modal-body-tiled.pb-0 > div:nth-child(3) > div > section > div.bb-tile-content > div > div:nth-child(2) > div > div.collapse.toggleinfo > div:nth-child(5) > div.col-xs-6 > a').outerHTML
})
```

it works just fine, but when I substitute that long selector with a variable, I get `Error: Evaluation failed: ReferenceError: selector is not defined`. I'm positive that I have defined the variable but it only doesn't work when I introduce a variable. It is definitely a string, it is definitely defined, so it should work but for some reason it doesn't. Any ideas?

EDIT: selector is the name I chose for the variable

Details:
OS: macOS Mojave
Node.js version: 8.11.3
Puppeteer version: 5.6.0

**Comment by aslushnikov** [comment]
@drwhorx be sure to pass selector as the argument to page.evaluate

```js
const variableInNODEJS = 'div';
const html = await page.evaluate(variableInBROWSER => {
  return document.querySelector(variableInBROWSER).innerHTML;
}, variableInNODEJS);
```
