### ISSUE TITLE
The memory used is constantly rising

### ISSUE THREAD

**Issue by zdying** [puppeteer/puppeteer#3207]
Hi，
When I was using puppeteer, I found that the memory used was constantly rising.

My  code only launch Chrome once, and then create and close a new page per URL.

Let the puppeter keep running for a few days, the memory keeps rising. So, I have to restart Puppeteer every few days. Does anyone know how to solve this problem?

Thanks!

![image](https://user-images.githubusercontent.com/3665170/45136342-21069f80-b1d6-11e8-945c-f94f5267152d.png)

**Comment by aslushnikov** [comment]
@a1ph do you have any ideas regarding this? Any chance we can use your fancy memory profiler to figure what's going on?

**Comment by a1ph** [comment]
You can try taking native memory snapshots and file a bug on crbug.com attaching the profiles.
Just make sure you launched chrome with --sampling-heap-profiler flag. Something like this:
```js
const ppt = require('puppeteer');

(async function main() {
  const browser = await ppt.launch({args: ['--sampling-heap-profiler']});
  const page = await browser.newPage();
  await page.goto('http://theverge.com');
  
  // ...
  // Have your script run for few hours, then take the memory snapshots.

  // Renderer process:
  console.log(JSON.stringify(await page._client.send('Memory.getAllTimeSamplingProfile')));
  // Browser process:
  console.log(JSON.stringify(await page._client.send('Memory.getBrowserSamplingProfile')));
})();
```

**Comment by zdying** [comment]
@a1ph Thanks, i'll try that later. :)

**Comment by leemove** [comment]
> @a1ph Thanks, i'll try that later. :)

have you solved the problem? i have the same situation.

**Comment by a1ph** [comment]
I haven't got a profile yet.
A better way to get a profile is to have chrome running with --memlog=all flag, then open chrome://memory-internals in a separate tab and click Save dump button.

**Comment by Kiritow** [comment]
Using puppeteer with bundled chromium and meet the same problem here. All 16GB ram is consumed slowly.

**Comment by alvarotrigo** [comment]
@Kiritow found any solution at the end?
