### ISSUE TITLE
How to hide the fact that the browser is being manipulated by a software?

### ISSUE THREAD

**Issue by sinisterdev** [puppeteer/puppeteer#3220]
I don't want to get rid of the message, basically google recaptcha knows my browser is controlled by a software, and because of that I get hard captchas, while If I start chromium manually the captchas are not hard, any way to solve this?

**Comment by aslushnikov** [comment]
The whole point of Google Recaptcha is to figure that your browser is automated. There are dozens of sophisticated techniques to detect automation and to counteract detections; there's no silver bullet though.

**Comment by vsemozhetbyt** [comment]
See also https://github.com/paulirish/headless-cat-n-mouse

**Comment by sinisterdev** [comment]
Well the problem is 'm also trying with non-headless chrome

**Comment by ffantasy** [comment]
figure out：
https://intoli.com/blog/not-possible-to-block-chrome-headless/
webdriver is the key!
