### ISSUE TITLE
As for puppeteer to emulate the movement of the mouse while pressing?

### ISSUE THREAD

**Issue by StasToken** [puppeteer/puppeteer#3221]
* Puppeteer version:1.5.0
* Platform / OS version: Ubuntu
* Node.js version: v8.9.4
Hello everyone, using puppeteer to automate testing, the question Arose, does anyone know how to click on an item with the mouse (left mouse button ) and without releasing the left mouse button to move it to the right 50px? Here's how to click I know how to move the cursor, I also know, but how to make so that the left mouse button was pressed during the transfer of the mouse will not understand anyone faced with such a task? tell me how to do it?

**Comment by Akxe** [comment]
There is `Mouse` class, you can use `press(x,y)`, `move(x,y)`, `release(x,y)`. No idea how to get mouse thought, yet.

**Comment by aslushnikov** [comment]
@Akxe @StasToken you can get mouse with [`page.mouse`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-pagemouse) getter

```js
await page.mouse.move(100, 100);
await page.mouse.down();
await page.mouse.move(200, 200);
await page.mouse.up();
```

**Comment by StasToken** [comment]
Many thanks!
