### ISSUE TITLE
[feature] keep original request payload & response payload along with request / response object in puppeteer

### ISSUE THREAD

**Issue by Ivlyth** [puppeteer/puppeteer#3222]
currently puppeteer define a request / response class to present HTTP Request and Response.  

but i found that Request / Response structure that Chrome Dev Protocol provide is much more than puppeteer defined.

Request defined in puppeteer:  https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-class-request

Response defined in puppeteer:  https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-class-response

Request defined in CDP:  https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Request
Response defined in CDP:  https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Response . 

can we keep the structure like request._requestPayload, response._responsePayload.  
then i can use it do more: like update request headers from response.requestHeaders().

**Comment by aslushnikov** [comment]
> can we keep the structure like request._requestPayload, response._responsePayload.

@MythRen We don't expose devtools protocol right away; it's vast and low-level.  PPTR's goal is to provide a high-level api for browser automation. However, you can use raw devtools protocol directly with [`target.createCDPSession`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-targetcreatecdpsession) - it'll probably help you here.

Regarding the `response.requestHeaders` - that's actually an instrumentation issue in the devtools protocol that doesn't let us send all the applicable headers in the `requestWillBeSent` event. ideally, it should be fixed upstream in chromium.
