### ISSUE TITLE
Query selector cannot locate elements with square braces

### ISSUE THREAD

**Issue by karthigb** [puppeteer/puppeteer#3223]
I need to select elements with ids that contain square brackets.

i.e.

`#fruit[0]`

However, I keep getting:

> Error: failed to find element matching selector "fruit[0]"

I've escaped the element in the selector with \, but that doesn't work.
`page.select("#fruit\[0\]", "apples")`

Double backslash escapes don't work either. i.e.:
`page.select("#fruit\\[0\\]", "apples")`

```
<select id="fruit[0]">
  <option value="">Please make a selection</option>
  <option value>apples</option>
</select>
```

**NOTE**: I get the same error even when I try to use the page.waitFor method with the query above.

I've tried all the suggestions in the Stackoverflow question linked below:

[Stackoverflow](https://stackoverflow.com/questions/52251592/puppeteer-escape-square-brackets-in-selector/)

**Comment by vsemozhetbyt** [comment]
`await page.select("[id='fruit[0]']", "apples");` seems working.

**Comment by aslushnikov** [comment]
@vsemozhetbyt wow that's very cool. 

@karthigb the reason for such a special syntax is because "fruit[0]" is not a valid element id. The trick uses the attribute selector.

**Comment by karthigb** [comment]
@vsemozhetbyt  Thanks!
