### ISSUE TITLE
browser.newPage() not returning the new page

### ISSUE THREAD

**Issue by jonahaberle** [puppeteer/puppeteer#3224]
### Steps to reproduce

await page.click() on a selector which result in a new page being opened 
(await page.browser().newPage()).close()

For me, the page being closed is the one which is created by the click, not the one created and immediately closed.

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Arch Linux
* URLs (if applicable):
* Node.js version: 6.4.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by RebliNk17** [comment]
await / async are not compatible with Node.js version 6.4.1 I think.
Have you tried:
```
page.browser().newPage().then(function(page) {
page.close();
});
```
