### ISSUE TITLE
Page.select() can't select option which value is empty

### ISSUE THREAD

**Issue by humengchuan** [puppeteer/puppeteer#3226]
In some cases, select's options value is empty. they just have text. and I read the code.  `option.selected = values.includes(option.value);`  I want select options which has certain text. Those pages are implement by knockout. option's value is empty. so I cant't select by value.

**Comment by aslushnikov** [comment]
You can use the following workaround:

```js
async function selectWithText(selector, text) {
  await page.$eval(selector, (element, text) => {
    for (const option of Array.from(element.options)) {
      if (option.textContent.includes('is this my option to select?')) {
        option.selected = true;
        element.dispatchEvent(new Event('input', { 'bubbles': true }));
        element.dispatchEvent(new Event('change', { 'bubbles': true }));
        return true;
      }
    }
    return false;
  }, text);
}
```

This is modeled similarly to our implementation of [`page.select`](https://github.com/GoogleChrome/puppeteer/blob/6581ee974c6919a589f0ab5b9eab036b13bb0c22/lib/FrameManager.js#L641-L659).

Hope this helps.

**Comment by subrato29** [comment]
Is there any way to select a value(and text) from drop-down using "xpath"(not by CSS) as locator in Puppeteer. If yes, please share the exact code snippet. I was trying with below helper function, but getting error.

async function select(xpath, text) {
const elements = await page.$x(xpath);
await elements[0].select(text);
}
getting below error
TypeError: elements[0].select is not a function...any idea where I am doing mistake
Please share your code, that would be really helpful

**Comment by AzySir** [comment]
@subrato29 how did you go with this?
