### ISSUE TITLE
auto-open-devtools-for-tabs would never be added by defaultArgs

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#3228]
I'm reviewing the [Launcher.defaultArgs](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L238) function. 
According to the line 240 and the line 248, it seems that `devtools` will always be false so `--auto-open-devtools-for-tabs` will never be added as an argument.

Is that the expected behavior?

**Comment by aslushnikov** [comment]
That's a [default value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Default_values), it'll be assigned only if there's no value passed in options.

You can play with the following script to see how it works:

```js
const pptr = require('puppeteer');
console.log(pptr.defaultArgs({
  devtools: true
}));
```

**Comment by kblok** [comment]
That's true #facepalm. Thanks!
