### ISSUE TITLE
Why doesn't puppeteer use the stable Chromium version?

### ISSUE THREAD

**Issue by maximedupre** [puppeteer/puppeteer#3230]
puppeteer `v1.8.0` uses Chromium `v71.0.3542.0`, which I believe is part of the Canary channel. Why not keep puppeteer in sync with the latest stable version (`v69`)?

Am I wrongly assuming that since Chrome `v71` is part of the Canary channel, so is Chromium `v71`?

Cheers!

**Comment by aslushnikov** [comment]
> Why not keep puppeteer in sync with the latest stable version (v69)?

@maximedupre please read this FAQ entry, it should shed some light: [Why doesn’t Puppeteer v.XXX work with Chromium v.YYY?](https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

Long story short: we contribute to Chromium in order to make Puppeteer work, so latest versions of Puppeteer depend on latest versions of Chromium. You can use Stable channel with older versions of Puppeteer, see the compat table in https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by maximedupre** [comment]
Thanks for the fast reply!

So do you recommend using an older version of puppeteer for deployment in production? As of today, this would be puppeteer `v1.6.2`. Because doesn't using puppeteer with an "unstable" Chromium version also makes puppeteer unstable?

**Comment by aslushnikov** [comment]
> So do you recommend using an older version of puppeteer for deployment in production? As of today, this would be puppeteer v1.6.2. Because doesn't using puppeteer with an "unstable" Chromium version also makes puppeteer unstable?

Chromium builds passed all the chromium tests (which we have *a lot*), so they hit certain quality bar. Of course, if you need additional guarantees, I'd recommend using an older version of Puppeteer with stable channel.

**Comment by aslushnikov** [comment]
> Because doesn't using puppeteer with an "unstable" Chromium version also makes puppeteer unstable?

Also, most of the time you probably run Puppeteer with Chromium headless. I don't think headless gets any stability/security fixes merged to stable channel, so usually there's not that much of a win for this usecase.

**Comment by oldrich-s** [comment]
@aslushnikov 

> You can use Stable channel with older versions of Puppeteer, see the compat table in https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

The latest actual stable version is: `72.0.3626.96` but the page lists: `Chromium 72.0.3618.0 (r609904)`

That basically means that you never are on the stable channel - instead you land on an old dev channel.

I would really love to see a real stable channel instead ;).
