### ISSUE TITLE
Add documentation and examples for iframe API.

### ISSUE THREAD

**Issue by hbowden** [puppeteer/puppeteer#3232]
Could ya'll add some example code and more documentation on working with iframes with puppeteer? Currently there is no official examples of how to manipulate iframes or use the iframe API. There are a handful of SO questions and Issues in this bug tracker with examples but they are all different and do not work for me. Below is a handful of issues/questions where people had similar problems but each have a different solution.

https://stackoverflow.com/questions/47501887/scrape-text-from-iframe
https://github.com/GoogleChrome/puppeteer/issues/684
https://github.com/GoogleChrome/puppeteer/issues/618

**Comment by aslushnikov** [comment]
@hbowden we usually have an overview description in the related class, for example for frame we have an example at [Frame documentation](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-class-frame).

I'm adding another example on how to get an iframe and get some text from it. Hope it helps.
