### ISSUE TITLE
page.$x and page.waitForXpath doe not work

### ISSUE THREAD

**Issue by ShubhojitBhattacharjee** [puppeteer/puppeteer#3235]
I am still getting

> TypeError: page.waitForXPath is not a function

error even after upgrading with `npm install https://github.com/GoogleChrome/puppeteer/`

And also while using `page.$x(xpathExpression)` I get error

> TypeError: page.$x is not a function

For the following code:

`const [compareButton] = await page.$x('//img[@src="productA.jpg"]/following-sibling::div[text()="Compare"]');
`
I have already installed puppeteer-xpath, still it doesn't work.

**Comment by aslushnikov** [comment]
@ShubhojitBhattacharjee  Most likely you're using old pptr version, you can figure this by checking your `package.json` or just going to `node_modules/puppeteer/package.json` and checking the installed package version.

Also note: if you have puppeteer installed in your package.json, then `npm install https://github.com/GoogleChrome/puppeteer/` **does not** upgrade puppeteer. 

Hope this helps.

**Comment by ShubhojitBhattacharjee** [comment]
@aslushnikov My bad, I did not refer to package.json.
I changed the version to 1.8.0 on package.json. It is working fine now. Thanks.
