### ISSUE TITLE
Permissions: API access still not granted after calling overridePermissions

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#3241]
`overridePermissions` doesn't appear to be working correctly. According to the permission api, the APIs are granted access (e.g. `navigator.permissions.query({name: 'camera'})).state === 'granted'`), but trying to use the API prompts the user for permission or the API doesn't work altogether

PPTR version: 1.8.0

**Repro:**

1. Run the code below.

**Actual:** The scripts clicks the "Open camera" button for the user and Chrome prompts to allow camera access.
**Expected:** Chrome has already been granted `camera` permission through the API so the demo should just start working. There should be no permission dialog.

```js
const puppeteer = require('puppeteer');
const URL = require('url').URL;

const url = new URL('https://webrtc.github.io/samples/src/content/getusermedia/gum/');

const browser = await puppeteer.launch({headless: false});

const context = browser.defaultBrowserContext();
context.clearPermissionOverrides();
context.overridePermissions(url.origin, ['camera']);

const page = await context.newPage();
await page.goto(url.href);

const granted = await page.evaluate(async () => {
  return (await navigator.permissions.query({name: 'camera'})).state;
});
console.log('Granted:', granted);

await page.$eval('#showVideo', el => el.click()); // clicks the "open camera' button
```

**Comment by ebidel** [comment]
Another repro. This demo should use geolocation to show your location on the map. Instead it doesn't do anything, fails silently.

```js
const puppeteer = require('puppeteer');
const URL = require('url').URL;

const url = new URL(`https://google-developers.appspot.com/maps/documentation/javascript/examples/full/map-geolocation`);

const browser = await puppeteer.launch({headless: false});

const context = browser.defaultBrowserContext();
context.clearPermissionOverrides();
context.overridePermissions(url.origin, ['geolocation']);

const page = await context.newPage();
await page.goto(url.href);

const granted = await page.evaluate(async () => {
  return (await navigator.permissions.query({name: 'geolocation'})).state;
});
console.log('Granted:', granted);
```

**Comment by aslushnikov** [comment]
@ebidel For the first example, it looks like `getUserMedia` is using a different codepath wrt the one we instrumented :'( Mind filing an upstream bug(and assigning to me)?

For the second demo, Chromium doesn't have keys to use google's geolocation API to figure geolocation from your IP.  So you'd need to use `page.setGeolocation` to fake it:

```js
const puppeteer = require('puppeteer');
const URL = require('url').URL;

(async () => {
  const url = new URL(`https://google-developers.appspot.com/maps/documentation/javascript/examples/full/map-geolocation`);

  const browser = await puppeteer.launch({headless: false});

  const context = browser.defaultBrowserContext();
  context.clearPermissionOverrides();
  context.overridePermissions(url.origin, ['geolocation']);

  const page = await context.newPage();
  await page.setGeolocation({
    latitude: 51.5074,
    longitude: 0.1278
  });
  await page.goto(url.href);

  const granted = await page.evaluate(async () => {
    return (await navigator.permissions.query({name: 'geolocation'})).state;
  });
  console.log('Granted:', granted);
})();
```

**Comment by ebidel** [comment]
Thanks! I'll file that bug for `getUserMedia`.

For geolocation, can we mention that in the docs?

I also tried Canary but it still doesn't produce a result.

```js
const puppeteer = require('puppeteer');
const URL = require('url').URL;

const url = new URL(`https://google-developers.appspot.com/maps/documentation/javascript/examples/full/map-geolocation`);

(async() => {

const browser = await puppeteer.launch({
  headless: false,
  executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
});

const context = browser.defaultBrowserContext();
context.clearPermissionOverrides();
context.overridePermissions(url.origin, ['geolocation']);

const page = await context.newPage();

await page.goto(url.href, {waitUntil: 'networkidle0'});

const granted = await page.evaluate(async () => {
  return (await navigator.permissions.query({name: 'geolocation'})).state;
});
console.log('Granted:', granted);

const pos = await page.evaluate(() => {
  return new Promise(resolve => {
    navigator.geolocation.getCurrentPosition(position => {
      resolve({lat: pos.coords.latitude, lng: pos.coords.longitude});
    });
  });
});
console.log(pos); // never gets here.
})();
```

Even just running this in the console does nothing:
```js
navigator.geolocation.getCurrentPosition(success => {
  console.log(success);
}, failure => {
  console.log(failure, failure.message);
});
```

Is as if the API goes dead when you use `clearPermissionOverrides` / `overridePermissions`. If I remove those calls and run the snippet above using Canary, the demo works again.

**Comment by ebidel** [comment]
Another one that doesn't work is the `clipboard-read` API.

```js
async function readClipboard(page, text) {
  return page.evaluate(() => navigator.clipboard.readText());
}
...
context.overridePermissions(url.origin, ['clipboard-read']);
```

The API returns `undefined` from `readClipboard` so it may require a user gesture. Do we handle that case?

**Comment by inevity** [comment]
Any progress about the clipboard-read api?

**Comment by inevity** [comment]
@ebidel Have tried the clipboard-read API.  Be ok to readText(),no need user gesture or keydown. But only plaintext, no text/html.

**Comment by is0sceles** [comment]
So is it an acknowledged issue that geolocation doesn't work on Chrome right now?

Also, is the following a typo? when calling resolve, you have pos instead of position.
```
const pos = await page.evaluate(() => {
  return new Promise(resolve => {
    navigator.geolocation.getCurrentPosition(position => {
      resolve({lat: pos.coords.latitude, lng: pos.coords.longitude});
    });
  });
});
```

**Comment by Worie** [comment]
Is it possible for `puppeteer` to return the actual geolocation data, instead of mocking it via `page.setGeolocation`? 

I don't understand why if I create non-headless Chrome instance without `context.overridePermissions` and manually confirm permissions for geolocations, it returns my actual geo - and if I use `context.overridePermissions` to enable this automaticaly (still with `headless: false`), the `success` callback is never invoked. I'm on `1.20.0` currently, macOS Catalina.

Permissions are granted, but since the data has to be mocked does not really help in my case :(

**Comment by jjs-stripe** [comment]
> Thanks! I'll file that bug for `getUserMedia`.
> 
> For geolocation, can we mention that in the docs?
> 
> I also tried Canary but it still doesn't produce a result.
> 
> ```js
> const puppeteer = require('puppeteer');
> const URL = require('url').URL;
> 
> const url = new URL(`https://google-developers.appspot.com/maps/documentation/javascript/examples/full/map-geolocation`);
> 
> (async() => {
> 
> const browser = await puppeteer.launch({
>   headless: false,
>   executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
> });
> 
> const context = browser.defaultBrowserContext();
> context.clearPermissionOverrides();
> context.overridePermissions(url.origin, ['geolocation']);
> 
> const page = await context.newPage();
> 
> await page.goto(url.href, {waitUntil: 'networkidle0'});
> 
> const granted = await page.evaluate(async () => {
>   return (await navigator.permissions.query({name: 'geolocation'})).state;
> });
> console.log('Granted:', granted);
> 
> const pos = await page.evaluate(() => {
>   return new Promise(resolve => {
>     navigator.geolocation.getCurrentPosition(position => {
>       resolve({lat: pos.coords.latitude, lng: pos.coords.longitude});
>     });
>   });
> });
> console.log(pos); // never gets here.
> })();
> ```
> 
> Even just running this in the console does nothing:
> 
> ```js
> navigator.geolocation.getCurrentPosition(success => {
>   console.log(success);
> }, failure => {
>   console.log(failure, failure.message);
> });
> ```
> 
> Is as if the API goes dead when you use `clearPermissionOverrides` / `overridePermissions`. If I remove those calls and run the snippet above using Canary, the demo works again.



> `overridePermissions` doesn't appear to be working correctly. According to the permission api, the APIs are granted access (e.g. `navigator.permissions.query({name: 'camera'})).state === 'granted'`), but trying to use the API prompts the user for permission or the API doesn't work altogether
> 
> PPTR version: 1.8.0
> 
> **Repro:**
> 
> 1. Run the code below.
> 
> **Actual:** The scripts clicks the "Open camera" button for the user and Chrome prompts to allow camera access.
> **Expected:** Chrome has already been granted `camera` permission through the API so the demo should just start working. There should be no permission dialog.
> 
> ```js
> const puppeteer = require('puppeteer');
> const URL = require('url').URL;
> 
> const url = new URL('https://webrtc.github.io/samples/src/content/getusermedia/gum/');
> 
> const browser = await puppeteer.launch({headless: false});
> 
> const context = browser.defaultBrowserContext();
> context.clearPermissionOverrides();
> context.overridePermissions(url.origin, ['camera']);
> 
> const page = await context.newPage();
> await page.goto(url.href);
> 
> const granted = await page.evaluate(async () => {
>   return (await navigator.permissions.query({name: 'camera'})).state;
> });
> console.log('Granted:', granted);
> 
> await page.$eval('#showVideo', el => el.click()); // clicks the "open camera' button
> ```

I'm seeing the same thing above on Puppeteer 2.0.0
It seems like if you set `--use-fake-ui-for-media-stream` then you can access Webcam without setting permission override. If you don't use `--use-fake-ui-for-media-stream` then NO MATTER WHAT YOU DO, you cannot access the Webcam.
In @ebidel's example above, the WebRTC page fails with a DOMException if `--use-fake-ui-for-media-stream` is not set.

**Comment by hlawuleka** [comment]
> Another one that doesn't work is the `clipboard-read` API.
> 
> ```js
> async function readClipboard(page, text) {
>   return page.evaluate(() => navigator.clipboard.readText());
> }
> ...
> context.overridePermissions(url.origin, ['clipboard-read']);
> ```
> 
> The API returns `undefined` from `readClipboard` so it may require a user gesture. Do we handle that case?

This works now ,BTW

**Comment by craigmj** [comment]
Hi,
I'm having what looks like the same issue, trying to 'puppeteer' a jitsi session.

Here's my puppeteer script - it downloads the fake video and audio, and drops into https://meet.jit.si/test-puppeteer

It doesn't work in puppeteer, but when I use the chromium command the script writes to stdout, it works perfectly. I'm checking and apparently have camera access granted, so I'm at a loss to what the issue is.

Any help greatly appreciated. (node v14.1.0, puppeteer 3.0.2)

```js
const fs = require('fs');
const https = require('https');
const puppeteer = require('puppeteer');

let server = `https://meet.jit.si`;
let room = `test-puppeteer`;


(async () => {
    await download_file(
        'https://media.xiph.org/video/derf/y4m/akiyo_cif.y4m',
        `${__dirname}/video.y4m`);
    await download_file(
        'https://upload.wikimedia.org/wikipedia/commons/b/b6/Strauss_Blue_Danube.wav',
        `${__dirname}/audio.wav`);

    let args = [
        "--disable-gpu",
        "--use-fake-device-for-media-stream",
        "--use-fake-ui-for-media-stream",
        `--use-file-for-fake-video-capture="${__dirname}/video.y4m"`,
        `--use-file-for-fake-audio-capture="${__dirname}/audio.wav"`
    ];

    console.log("command line equivalent:");
    console.log(`chromium ${args.join(" ")} ${server}/${room}`);

	const browser = await puppeteer.launch({
		headless: false,
        defaultViewport: {
            width: 800,
            height: 600
        },
        args: args
	});
	
	const context = browser.defaultBrowserContext();
	await context.overridePermissions(server, ['camera','microphone']);
	const page = await browser.newPage();
	await page.goto(`${server}/${room}`);
	await sleep(8000);
	const granted = await page.evaluate(async () => {
		return (await navigator.permissions.query({name: 'camera'})).state;
	  });
	console.log('Granted:', granted);

    await page.screenshot({path: 'example.png'});
	console.log('closing');
	await browser.close();
})();

// check that a file exists, download it if it doesn't
async function download_file(url, filename) {
    if (await file_exists(filename)) {
        return true;
    }
    var file = fs.createWriteStream(filename);
    return new Promise(function(resolve) {
        https.get(url, function(response) {
            response.pipe(file);
            file.on('finish', function() {
                file.close(function(err) {
                    resolve(err);
                });  // close() is async, call cb after close completes.
            });
        }).on('error', function(err) { // Handle errors
            fs.unlink(filename); // Delete the file async. (But we don't check the result)
            resolve(err);
        });
    });
}

// async file_exists returns true if the file exists,
// false otherwise
async function file_exists(filename) {
    return new Promise(function(resolve) {
        fs.stat(filename, function(err, stats) {
            if (err) {
                resolve(false);
            } else {
                resolve(true);
            }
        });
    });
}

// simple sleep function
function sleep(ms) {
	return new Promise(function(resolve) {
		setTimeout(function() {
			resolve(true);
		}, ms);
	});
}
```

**Comment by mdshihabullah** [comment]
Hello @aslushnikov, @ebidel  , 

I am try get microphone access for the following website but apparently failing. After lot of trying still cannot figure out why!

**It disable all permission as soon as I log in.** 
**Puppeteer version: 5.1.0**

Can you help me please? Thanks in advance! <3 :)

```
const puppeteer = require("puppeteer");
const URL = require('url').URL;
const fs = require('fs');
const url = new URL('https://login.leaddesk.com/r82.0.1/?page=agent_call');
console.log(url);

async function main() {
    const browser = await puppeteer.launch({ headless: false });
    const context = browser.defaultBrowserContext();
    context.clearPermissionOverrides();
    context.overridePermissions(url.origin, ['microphone']);
    const page = await context.newPage();
    await page.goto('https://login.leaddesk.com/r82.0.1');

    await page.type('#username', 'blabla');
    await page.type('#password', 'blabla');

    await page.click('#login-button');

    await page.waitForNavigation(); 
    const granted = await page.evaluate(async () => {
        return (await navigator.permissions.query({ name: 'microphone' })).state;
    });
    console.log('Granted:', granted);
}

main();
```
After successful auto-login the page becomes not secure thus cant access microphone!

**Comment by dcgudeman** [comment]
Hi @aslushnikov, @ebidel 
I am also experiencing this issue with headless chrome puppeteer version 5.2.1 for geolocation api so the code:

```
const puppeteer = require('puppeteer');
const URL = require('url').URL;


const url = new URL(`https://google-developers.appspot.com/maps/documentation/javascript/examples/full/map-geolocation`);

const browser = await puppeteer.launch({
    headless: true,
    args: [
        '--no-sandbox',
        '--disable-gpu',
        '--disable-dev-shm-usage',
        '--disable-setuid-sandbox',
        '--no-first-run',
        '--no-zygote',
        '--single-process',
        "--proxy-server='direct://'",
        '--proxy-bypass-list=*'
      ],
    timeout: 0,
});

const context = browser.defaultBrowserContext();
context.clearPermissionOverrides();
context.overridePermissions(url.origin, ['geolocation']);

const page = await context.newPage();
await page.goto(url.href);

const granted = await page.evaluate(async () => {
  return (await navigator.permissions.query({name: 'geolocation'})).state;
});
console.log('Granted:', granted);
```

returns nothing.

I have searched all over but have not found a solution. Did this used to work for a previous version of puppeteer?? Any information to shed some light on this issue would be greatly appreciated!

**Comment by GProst** [comment]
When I try to grant `clipboard-write` permissions in headless mode it changes it to 'denied' instead (if I don't call it is it 'prompt'):
```js
context.overridePermissions(url.origin, ['clipboard-write'])

const page = await context.newPage()
await page.goto(url.origin)
const state = await page.evaluate(async () => {
  return (await navigator.permissions.query({name: 'clipboard-write'})).state;
});
console.log(state) // denied
```

macOS: 10.15.7
puppeteer: 5.4.1

**Comment by ericcornelissen** [comment]
> When I try to grant `clipboard-write` permissions in headless mode it changes it to 'denied' instead (if I don't call it is it 'prompt'):
> 
> ```js
> context.overridePermissions(url.origin, ['clipboard-write'])
> 
> const page = await context.newPage()
> await page.goto(url.origin)
> const state = await page.evaluate(async () => {
>   return (await navigator.permissions.query({name: 'clipboard-write'})).state;
> });
> console.log(state) // denied
> ```
> 
> macOS: 10.15.7
> puppeteer: 5.4.1

I'm not an expert in this regard, but at least when limiting the scope of this discussion to `clipboard-write` and `clipboard-read`, it seems to me that there is a bug/mistake in the [`overridePermissions()` method](https://github.com/puppeteer/puppeteer/blob/d901696e0d8901bcb23cf676a5e5ac562f821a0d/src/common/Browser.ts#L651). As per its documentation:

> An array of permissions to grant. All permissions that are not listed here will be automatically denied.

So, if you specify either `clipboard-write` and `clipboard-read` as permissions then both will be mapped to `clipboardReadWrite` which is the only permission that will be granted. By looking at [the Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#type-PermissionType) (which `overridePermissions()` uses to override permissions) I found that there are actually two permissions related to the clipboard: `clipboardSanitizedWrite` and `clipboardReadWrite`. When I mimicked `overridePermissions()`'s CDP call manually using `'clipboardSanitizedWrite'` as permissions I was able to use `navigator.clipboard.writeText` and your snipped returned _"granted"_ (instead of _"denied"_). More specifically, the following snippet should work:

```js
await context._connection.send('Browser.grantPermissions', {
  origin: url.origin,
  browserContextId: this._id || undefined,
  permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'],
});

const page = await context.newPage()
await page.goto(url.origin)
const state = await page.evaluate(async () => {
  return (await navigator.permissions.query({name: 'clipboard-write'})).state;
});
console.log(state) // granted
```

It's not pretty and should probably be fixed in `overridePermissions()`, but it gets the job done.

**Comment by miaulightouch** [comment]
> I'm seeing the same thing above on Puppeteer 2.0.0 It seems like if you set `--use-fake-ui-for-media-stream` then you can access Webcam without setting permission override. If you don't use `--use-fake-ui-for-media-stream` then NO MATTER WHAT YOU DO, you cannot access the Webcam. In @ebidel's example above, the WebRTC page fails with a DOMException if `--use-fake-ui-for-media-stream` is not set.

if you are using pptr on windows, it may be the upstream issue. try to launch chrome from cmd, you will not able to access webcam either. because you do launch chrome as the child process of any process, not launch it directly. I believe it cause some something from system to terminate the webcam access.

electron/electron#23281 may have same issue.

Did it worth to report to upstream?

**Comment by rmichnovicz-verkada** [comment]
Howdy y'all, in case you're looking for something to copy and paste to enable clipboard permissions, some code that worked to do what @ericcornelissen did, but in the latest version of Puppeteer, is to create a separate CDP session to grant yourself sanitized clipboard permissions. While someone should probably make a PR to expose the `clipboardSanitizedWrite` permissions to `overridePermissions()` this still gets the job done. Note that I couldn't find a way in which puppeteer exposes the `BrowserContextID`, so this only works for the default browser context.

```js
const client = await page.target().createCDPSession();
await client.send('Browser.grantPermissions', {
  origin: "https://command.verkada.com",
  permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'],
});
```

Alternatively, we can use the CDP API [`Browser.setPermission`](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setPermission). As a side note, it looks like this is the API you'd want to use for `panTiltZoom` cameras and `userVisibleOnly` push notifications.

```js
const client = await page.target().createCDPSession();
await client.send('Browser.setPermission', {
  origin: "https://command.verkada.com",
  permission: {
    name: 'clipboard-write',
    allowWithoutSanitization: true
  },
  setting: 'granted',
});

**Comment by AnmolBansalDEV** [comment]
> Howdy y'all, in case you're looking for something to copy and paste to enable clipboard permissions, some code that worked to do what @ericcornelissen did, but in the latest version of Puppeteer, is to create a separate CDP session to grant yourself sanitized clipboard permissions. While someone should probably make a PR to expose the `clipboardSanitizedWrite` permissions to `overridePermissions()` this still gets the job done. Note that I couldn't find a way in which puppeteer exposes the `BrowserContextID`, so this only works for the default browser context.
> 
> ```js
> const client = await page.target().createCDPSession();
> await client.send('Browser.grantPermissions', {
>   origin: "https://command.verkada.com",
>   permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'],
> });
> ```
> 
> Alternatively, we can use the CDP API [`Browser.setPermission`](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setPermission). As a side note, it looks like this is the API you'd want to use for `panTiltZoom` cameras and `userVisibleOnly` push notifications.
> 
> ```js
> const client = await page.target().createCDPSession();
> await client.send('Browser.setPermission', {
>   origin: "https://command.verkada.com",
>   permission: {
>     name: 'clipboard-write',
>     allowWithoutSanitization: true
>   },
>   setting: 'granted',
> });
> ```

thank you so much, I literally spent hours finding the reason. Please make a PR with the fix you're mentioning, I could probably make a PR myself, but I didn't completely understand what were you mentioning. And I'm just an intern right now, so I think it's a little too advanced for me.

**Comment by lemanschik** [comment]
@rmichnovicz-verkada i want to answer your question puppeteer exposes the context id under


[Browser.BrowserContextID](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#type-BrowserContextID)
Type: string

**Comment by OrKoN** [comment]
It looks like the original issue has been resolved in the latest versions.
