### ISSUE TITLE
can`t get href when use frame.$$eval

### ISSUE THREAD

**Issue by w25193** [puppeteer/puppeteer#3243]
![image](https://user-images.githubusercontent.com/29299286/45533782-6573ea00-b82b-11e8-9171-ef5ccdcf65d1.png)

when i`m trying use frame.$$eval to get the hrefs,i only can get href`s num

![image](https://user-images.githubusercontent.com/29299286/45533791-6dcc2500-b82b-11e8-91df-5ab34a7060fa.png)

**Comment by aslushnikov** [comment]
`frame.$$eval` calls page function with array of links rather then a single link.

```js
await frame.$$eval('.news-list a', links => links.map(link => link.href));
```

check out the example for [`frame.$$eval`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-frameevalselector-pagefunction-args).

**Comment by w25193** [comment]
i`m leaning this have this problem,so the example is wrong?😂
![image](https://user-images.githubusercontent.com/29299286/46132164-f5745380-c26f-11e8-8fe4-c7e303f74440.png)

**Comment by aslushnikov** [comment]
@w25193 I don't think example's wrong. Note though: there are two methods, `frame.$$eval` and `frame.$eval`. I suggested using the `frame.$$eval`

**Comment by w25193** [comment]
@aslushnikov sorry,i didn`t notice that.my fault😥
