### ISSUE TITLE
page onload will not be executed?

### ISSUE THREAD

**Issue by jcppython** [puppeteer/puppeteer#3247]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  1.1.0
* Platform / OS version: centos7
* URLs (if applicable): 
* Node.js version: v8.5.0

**What steps will reproduce the problem?**
```
await page.goto(url);
const search = await Help.waitForFrame(page, 'search');
await search.waitForSelector('#page-controller');
const power = await Help.waitForFrame(page, 'power');
await power.waitForSelector('#modal-page');
await page.close();
```

waitForFrame come from: https://github.com/GoogleChrome/puppeteer/issues/1361

About `url` page:
1. main frame (parent), and two child frames (name with 'search' and 'power')
2. main frame will trigger search frame
3. search frame will trigger power frame

as show following (code is contained in main frame):
```
<div class='frLeft'>
   <iframe id='search' frameborder='0'></iframe>
</div>
<div class='frRight'>
    <iframe id='power' frameborder='0'></iframe>
</div>

<script>
(function () {
    // is ok, will be triggered
    $('#search').attr('src', 'search?param=' + param);
})

$('#search').on('load', function () {
    // is bad, thus codes is not run.
    $('#power').attr('src', 'power?param=' + param);
});
</script>
```

**What is the expected result?**
search and power frame can be loaded

**What happens instead?**
search frame is ok, but the power frame is bad.
Server is not receiving the request about power frame.

**Comment by aslushnikov** [comment]
> Puppeteer version: 1.10

Is this 1.1.0? We haven't released 1.10 yet; we're at 1.8.0.

> search frame is ok, but the power frame is bad.
Server is not receiving the request about power frame.

Can you provide your script? There's not much to say without seeing your code / website.

**Comment by jcppython** [comment]
@aslushnikov sorry, I have updated version (1.1.0), and added some code snippet.

**Comment by aslushnikov** [comment]
I don't see how's this related to pptr; I think there's an issue with your website.

Your snippet doesn't work for me; however, the following loads just fine:

```html
<div class='frLeft'>
   <iframe id='search' frameborder='0'></iframe>
</div>
<div class='frRight'>
    <iframe id='power' frameborder='0'></iframe>
</div>
<script>
$ = document.querySelector.bind(document);
$('#search').setAttribute('src', 'https://aslushnikov.com?foo=bar');
$('#search').addEventListener('load', function() {
    $('#power').setAttribute('src', 'https://aslushnikov.com?foo=EEE');
});
</script>
```

**Comment by jcppython** [comment]
@aslushnikov 
It will work good when I replace a fast page for 'search' page.
so, the reason may be, the response of the 'search' page is very slow.
What's your opinion?

**Comment by aslushnikov** [comment]
Well, if search takes long time to load, then it'll naturally take long to navigate the `#power`. Also note: certain pages will never emit the `load` event, so I wouldn't rely on it.

Closing this since this has no relation to Puppeteer.
