### ISSUE TITLE
New Puppeteer Book will be on sale September 19th

### ISSUE THREAD

**Issue by misakikaoru2006** [puppeteer/puppeteer#3248]
Hi,

I'm an author and a programmer in Japan, and my book on Puppeteer will be on sale on September 19th!  The book is mainly for beginners, available in Japanese.

Kaoru Misaki, Author, Programmer

[amazon](https://www.amazon.co.jp/gp/product/4798055204/ie=UTF8&creativeASIN=4798055204&linkCode=as2&tag=futurelife0c-22)
![81qn5wk2c9l1](https://user-images.githubusercontent.com/11881920/45553230-45194f00-b86e-11e8-9732-a24e7269c7a1.jpg)

**Comment by aslushnikov** [comment]
Thank you Kaoru Misaki for letting us know, I've already preordered one :) I don't speak or read Japanese, but the cover page is gorgeous.

**Comment by misakikaoru2006** [comment]
Thank you aslushnikov!
This cover page is drawn by famous japanese illustrator Kenji Tsuruta.
I like this cover.
