### ISSUE TITLE
Debugging tips #3

### ISSUE THREAD

**Issue by bernardoadc** [puppeteer/puppeteer#3249]
### Steps to reproduce

* Puppeteer version: 1.7.0
* Platform / OS version: windows 10 version 1511 compilation 10586.1007
* Node.js version: v9.11.1

**What steps will reproduce the problem?**

https://github.com/GoogleChrome/puppeteer#debugging-tips 

```
beforeAll(async () => {
    browser = await createBrowser();
    page = await browser.newPage();
    await setViewport(page);
    page.on('console', msg => console.log('PAGE LOG:', msg.text()))
});
```

**What is the expected result?**

Pipe `console.log` from frontend to terminal

**What happens instead?**

It shows:
```
  console.log <filename and linenumber>
    PAGE LOG: The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```

**Comment by aslushnikov** [comment]
So what's the issue?

**Comment by bernardoadc** [comment]
It should show the log message.. or perhaps readme should be updated

**Comment by aslushnikov** [comment]
@khullah so it does show log in your example, there's a "PAGE LOG" entry.

Also, the following works just fine for me:

```js
const pptr = require('.');

(async() => {
  const browser = await pptr.launch();
  const page = await browser.newPage();
  page.on('console', msg => console.log('PAGE LOG: ' + msg.text()));
  await page.evaluate(() => console.log('Yo, I am inside page'));
  await browser.close();
})();
```

**Comment by bernardoadc** [comment]
Oh.. I thought that was a puppeteer msg, not a chrome one :palm_face:

Dumb me, sorry for taking your precious time!
