### ISSUE TITLE
The clipboard contains nothing when use command + c(copy)

### ISSUE THREAD

**Issue by trueFeeling** [puppeteer/puppeteer#3252]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version: 10.7.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. select the text in the webpage.
2.  type the following codes:
```javascript
await page.keyboard.down('Meta');
await page.keyboard.down('C');
await page.keyboard.up('Meta');
await page.keyboard.up('C');
```
3.  type the following codes:
```javascript
await page.keyboard.down('Meta');
await page.keyboard.down('V');
await page.keyboard.up('Meta');
await page.keyboard.up('V');
```

**What is the expected result?** 
In order to test whether our users can copy and paste successfully in our app 

**What happens instead?**
the clipboard contains nothing, which means my " command+c " operation failed.

**Comment by vsemozhetbyt** [comment]
Maybe you can try async clipboard API:

https://developers.google.com/web/updates/2018/03/clipboardapi
