### ISSUE TITLE
Problem with requests not starting with "http" or "https"

### ISSUE THREAD

**Issue by SzymonLisowiec** [puppeteer/puppeteer#3255]
### Steps to reproduce

**My environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Windows 10 Home (1803)
* URLs (if applicable): - 
* Node.js version: 8.11.2

**Steps to reproduce the problem:**

```javascript
...
let tab = await this.browser.newPage();

await tab.setRequestInterception(true);

tab.on('request', async request => {
    console.log(request.url());
});
```

1. Create webpage with ajax request to e.g. "myapp://hello"
2. Create listener for `request` event
3. Set Request Interception on true.
4. Run

**What is the expected result?**
Puppeteer should emit `request` event with intercepted request to "myapp://hello".

**What happens instead?**
Puppeter not emiting `request` event with intercepted request to "myapp://hello". If `Request Interception` is disabled, working fine but I can't use `request.respond()`,

**Comment by aslushnikov** [comment]
> Create webpage with ajax request to e.g. "myapp://hello"

@SzymonLisowiec how do I do this? Looks like I can't just `fetch('myapp://hello')`

**Comment by SzymonLisowiec** [comment]
That mobile app use this:
```javascript
let iframe = document.createElement('iframe');
iframe.src = 'myapp://hello';
document.body.appendChild(iframe);
```

**Comment by aslushnikov** [comment]
Thanks, I can reproduce this with the following script:

Expected: outputs "STARTED: myapp://hello"
Actual: doesn't output anything

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', request => {
    console.log('STARTED: ' + request.url());
    request.continue();
  });
  page.on('requestfinished', request => {
    console.log('FINISHED: ' + request.url());
  });
  page.on('requestfailed', request => {
    console.log('FAILED: ' + request.url());
  });
  page.on('response', response => {
    console.log(response.url());
  });
  await page.evaluate(() => {
    let iframe = document.createElement('iframe');
    iframe.src = 'myapp://hello';
    document.body.appendChild(iframe);
  });
})();
```

Seems to be an issue in DevTools protocol - for some reason interceptions are not dispatched.
