### ISSUE TITLE
Puppeteer unable to click on the cookie accept button

### ISSUE THREAD

**Issue by mehtaanirudh** [puppeteer/puppeteer#3257]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Windows 7 Enterprise
* URLs (if applicable):
* Node.js version: 8.11.4

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');

const url='https://ee.co.uk/';

const waitBeforeClosing = timeout => {
                          return new Promise((resolve) => {
                            setTimeout(resolve, timeout);
                          });
};

(async () => {  

try{ 
    const Browser = await puppeteer.launch({args: ['--no-sandbox'],
                                    headless:false,
                                    defaultViewport:{width:600,height:800}
                                    }); 
    
    const page = await Browser.newPage();

    page.on('load', () => console.log('Page loaded!: ' + page.url()));
    await page.goto(url, {
            waitUntil: ['load','domcontentloaded','networkidle0','networkidle2']
        });



    const cookieAcceptBtn = await page.$(".cookie-banner__btn-accept");

    await console.log('The element cookieAcceptBtn was resolved to: ' + cookieAcceptBtn);
    await cookieAcceptBtn.click();   

    await waitBeforeClosing(2000+Math.random()*832);
    await page.screenshot({path: 'EE.png'});

  
    await waitBeforeClosing(5000+Math.random()*832);
    
    await Browser.close();
} catch(err){
    console.log("Issue with the page " + err);
}
})();
```
_Please include code that reproduces the issue._

1. Open a website.
2. Look for the "Accept" button that pops up on the page to accept cookies.
3. Click on the button and carry on doing rest of the work.

**What is the expected result?**

The puppeteer should accept the "cookie Accept" button and carry on loading the homepage.

**What happens instead?**
1. I can see that the puppeteer is able to get the button element from the class name.
2. However for some reasons it can't click on the button. Instead I get an error message "Node is either not visible of not an HTMLElement".
3. I tried digging around but could not find anything substantial. If I view the page source I can see that there is only one button for this particular class so there is no issue around the query returning multiple buttons.

I wonder if there is something special in the dialog box that is preventing puppeteer from clicking on the element?

Edit:

I tried running this in the console and go the following:

 `document.querySelector(".cookie-banner__btn-accept").click()`

> clientlibs_cq.min.20180907-1500.js:189 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

I think it is something to do with Synchronous XMLHttpRequests. Can anyone help as I have very little knowledge of Synchronous XMLHttpRequests.

**Comment by k3mayo** [comment]
I just double checked the site, that selector seems to return two elements.
![image](https://user-images.githubusercontent.com/15950161/45627924-f7186d00-ba60-11e8-93da-530b02177ec5.png)

**Comment by aslushnikov** [comment]
@mehtaanirudh indeed, as @k3mayo mentioned, you need to click the second node that matches this selector.
