### ISSUE TITLE
Provide a simpler method of getting innerHTML and innerText

### ISSUE THREAD

**Issue by bitmvr** [puppeteer/puppeteer#3260]
Thank you so much for creating `Puppeteer`! It _is_ a fantastic product. While I know that Puppeteer's end goal isn't _necessarily_ to be a W3C Web Driver Protocol compliant product, I've seen many users asking for help in achieving what is such a simple task in similar products and it would make Puppeteer that much more friendly.

I'd love to see something similar to the following implemented in which end-users (developers) can create cleaner code in their puppeteer automations and reduce the need to query the internet for `how-to` articles.

**From**
```
await page.evaluate(() => document.querySelector('#my-sweet-id').innerText)
await page.evaluate(() => document.querySelector('#my-sweet-id').innerHTML)
```

**To**
```
await page.getText('#my-sweet-id')
await page.getText('#my-sweet-id')[0]
```

```
await page.getHTML('#my-sweet-id')
await page.getHTML('#my-sweet-id')[0]
```

**W3C Standard:**
https://www.w3.org/TR/webdriver1/#dfn-get-element-text

**Production Implementation Example (Ruby):**
https://www.rubydoc.info/gems/selenium-webdriver/0.0.28/Selenium%2FWebDriver%2FElement:text

Thank you for your time.

**Comment by aslushnikov** [comment]
Hey @bitmvr,

Instead of 
```js
await page.evaluate(() => document.querySelector('#my-sweet-id').innerText)
await page.evaluate(() => document.querySelector('#my-sweet-id').innerHTML)
```

You can use [`page.$eval`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-pageevalselector-pagefunction-args-1):
```js
await page.$eval('#my-sweet-id', e => e.innerText);
await page.$eval('#my-sweet-id', e => e.innerHTML);
```

We feel it's short and *very* flexible.
WDYT?

**Comment by bitmvr** [comment]
@aslushnikov,

Thank you for the example. While it is shorter, it doesn't feel very intuitive. I did just implement your example into in my current automation.

**Comment by aslushnikov** [comment]
Looks like this doesn't have much demand; let's stick with the workaround for now.

**Comment by maschad96** [comment]
This would be really useful for me. I do a lot of UI testing and commonly need to get HTML content

**Comment by briwoto** [comment]
This question is valid and indeed a very useful enhancement to have. Considering puppeteer to go with the likes of replacing Selenium, functions like these would help immensely

**Comment by kirkins** [comment]
I agree based on Puppeteer using the `$` I just assumed we could use the syntax mentioned by @bitmvr.

I was only able to fix my problem by finding this page and implementing what @aslushnikov suggested.

**Comment by arturz** [comment]
I wrote myself a helper util (createNativeFn.js):
```javascript
export default fn =>
  async element =>
    await element.executionContext().evaluate(fn, element)
```
So now I can easily create getters for every property and methods invokers from element, instead from page (eg. getInnerText.js):
```javascript
import createNativeFn from './createNativeFn.js'

export default createNativeFn(nativeElement =>
  nativeElement.innerText
)
```
and then in code:
```javascript
;(async () => {
  const element = await page.$('...')
  const child = element.$('...')
  const childText = await getInnerText(child)
  console.log(childText)
})()
```

**Comment by csalvato** [comment]
> Looks like this doesn't have much demand; let's stick with the workaround for now.

How are you gauging demand?

**Comment by briwoto** [comment]
@csalvato @xout @kirkins @aslushnikov 
I created a library to help deal with this issue. Basically, a wrapper around jest and puppeteer. Went ahead and created a few other functions as well. Basically, I have put all my selectors in a selector.js file and the created functions to click, select, type, wait for an element; irrespective of whether the selector is a css or an xpath. The link to the repo is this:
[https://github.com/briwoto/jesteer](https://github.com/briwoto/jesteer)

Take a look at the utils directory. It conatins the functions. The function to get the innerText or innerHTML is basically the get_attribute function in the utils directory > ui_utils.js

**Comment by mprinc** [comment]
Hi @aslushnikov , re:

> You can use [`page.$eval`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-pageevalselector-pagefunction-args-1):
> 
> ```js
> await page.$eval('#my-sweet-id', e => e.innerText);
> await page.$eval('#my-sweet-id', e => e.innerHTML);
> ```

If you do not have selector but, a node instead, than this works (TypeScript):

```ts
const innerHtml:any = await page.evaluate((aButton:HTMLButtonElement) => aButton.innerHTML, aButton);
```

**Comment by shukriadams** [comment]
`await page.$eval('#my-sweet-id', e => e.innerText)`

seems like such a long-winded way to 

`await page.querySelector('#my-sweet-id')`

**Comment by tolmasky** [comment]
It would be so much nicer to be able to do this:

```javascript
const text = await (await page.waitForSelector(selector)).innerText();
```

Than:

```javascript
await page.waitForSelector(selector)

const text = await page.evaluate(selector => document.querySelector(selector), selector).innerText();
```
