### ISSUE TITLE
[BUG] Wrong timezone when run puppeteer in Debian jessie

### ISSUE THREAD

**Issue by martin-liu** [puppeteer/puppeteer#3264]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Debian GNU/Linux 8 (jessie)
* URLs (if applicable): any url
* Node.js version: v8.9.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```javascript
const puppeteer = require('puppeteer');                                                                                                               
const url = 'https://www.google.com';
const options = {
    args: [
      '--no-sandbox'
    ]
};

(async () => {
  const browser = await puppeteer.launch(options);
  const page = await browser.newPage();
  await page.goto(url);
  const ret = await page.evaluate(() => new Date().toString());
  console.log(ret);
  await browser.close();
})();

```

**What is the expected result?**
Timezone should be the same as host server.
e.g. `Mon Sep 17 2018 12:27:16 GMT-0700 (PDT)`

**What happens instead?**
Wrong timezone.
e.g. `Tue Sep 18 2018 02:27:16 GMT+0700 (GMT+07:00)`

**Comment by DuBistKomisch** [comment]
:+1: Also seeing this on debian stretch armhf with chromium 67, set system timezone to `Australia/Melbourne`, but it gets picked up as `GMT+1000 (GMT+10:00)` (which it's not because of daylight savings time).

I'm guessing this is a debian packaging or underlying chromium bug rather than puppeteer, but a workaround is to set the `TZ` env var to override it as I just mentioned [in another issue](https://github.com/GoogleChrome/puppeteer/issues/3325#issuecomment-429685007).

**Comment by DuBistKomisch** [comment]
@aslushnikov is this fixed? or closing as not an issue in puppeeter?

**Comment by aslushnikov** [comment]
> is this fixed? or closing as not an issue in puppeeter?

@DuBistKomisch oops I've read your post as if you diagnosed this as a debian issue.

This definitely has nothing to do with Puppeteer - can you please file upstream to Chromium? https://crbug.com/new

**Comment by DuBistKomisch** [comment]
Alright, done: https://bugs.chromium.org/p/chromium/issues/detail?id=905582

Hopefully gets fixed faster than my other Chromium bugs!

**Comment by jungshik** [comment]
When Chrome is run "inside" (?) puppeteer, can it access the file system (e.g.  can it access /usr/share/zoneinfo and /etc/localtime) ?

**Comment by mathiasbynens** [comment]
Puppeteer just spawns a Chrome process. So, it depends: if the Node.js script that uses Puppeteer has access to `/usr/share/zoneinfo` then so does the Chrome process spawned by it.
