### ISSUE TITLE
Browserfetcher on Win10_x64 is unable to download chrome in revision 310958

### ISSUE THREAD

**Issue by staabm** [puppeteer/puppeteer#3268]
I try to use a script from @ebidel to install chrome41 on Win10_x64 for seo testing purposes with this GIST https://gist.github.com/ebidel/b946392bec509502256843d0d3949c61

it doesnt work for me on Win10_x64 though, because the Browser is not able to fetch the download for revision `310958`.

for all details see this twitter thread: https://twitter.com/markusstaab/status/1040501957297876992

### Steps to reproduce

**Tell us about your environment:**
(Reproduced on 2 different Win10x64 PCs)

* Puppeteer version: 1.8.0
* Platform / OS version: Win10x64 with all updates
* URLs (if applicable): https://twitter.com/markusstaab/status/1040501957297876992
* Node.js version: 8.2.1 or 8.12.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

- download https://gist.github.com/ebidel/b946392bec509502256843d0d3949c61 and put it into a locale file, e.g. `download_chrome41.js`
- make sure puppeteer is installed/available to node
- run `node download_chrome41.js`

**What is the expected result?**
chrome41 will be downloaded and can be used

**What happens instead?**
at first I get this "meaningless" error:
https://twitter.com/markusstaab/status/1040663745943482369

after removing an `assert` from the script, I get a better error message:
Download failed error, see screenshot in https://twitter.com/markusstaab/status/1040859000106045440

**Comment by ebidel** [comment]
There's probably not a Win10_x64 build for this particular revision. I guess we just need to find the last revision of chrome 41 for windows, and possibly other platforms.

**Comment by staabm** [comment]
any progress on this? anything I can do to get this fixed?

**Comment by aslushnikov** [comment]
@staabm it looks like we didn't do win64 builds back in the days. I poked into this a bit - the earliest I found is somewhere around 389996.

Note: there's a helper script in [`/utils/check_availability.js`](https://github.com/GoogleChrome/puppeteer/blob/master/utils/check_availability.js) that we use to see which revisions are available.

```sh
$ ./utils/check_availability.js 390000 0
```
![image](https://user-images.githubusercontent.com/746130/46450201-ecd6be00-c744-11e8-94b8-10e245c148f2.png)

Hope this helps.

**Comment by ebidel** [comment]
@staabm so in that case, you're not going to be able to use my script on win64. 389996 maps to Chrome 52, which is much later than m41 (what search is using).

**Comment by staabm** [comment]
Thank you guys for getting back to that. Its a pity but I see that noone could forsee that.

@ebidel maybe it would make sense to mention this caveat in your script via a comment
