### ISSUE TITLE
How can I get the parentElement inside evaluate method

### ISSUE THREAD

**Issue by guangzhou** [puppeteer/puppeteer#3269]
But，How can I get the parentElement inside evaluate ？

```js
const parents = await page.evaluate(() => {
  var contents = document.querySelectorAll('.next-select-arrow');
  var ids = []
  for (element in contents) {
    var loutid = element.id
    var etmp = element.parentElement
    // while (loutid == '' || loutid == undefined) {
    // etmp = element.parentNode;
    // loutid = etmp.id;
    // }
    ids.push(etmp)
  };
  return ids
});
await console.log(parents)
```

**What is the expected result?**
the array of the parentElememts

**What happens instead?**
[ null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null ]

**Comment by vsemozhetbyt** [comment]
1. `for...in` loop iterates over object keys, it seems you need `for...of` loop.
2. Elements are not serializable, so you may not get an array of them from the browser context to puppeteer context via `.evaluate()`. You can process the array inside the same `.evaluate()` or try [`page.evaluateHandle()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatehandlepagefunction-args) function.
