### ISSUE TITLE
Elements with a background-image: url() style sometimes render slightly differently

### ISSUE THREAD

**Issue by theblang** [puppeteer/puppeteer#3270]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `1.7.0`
* Platform / OS version: Using `Docker` with `Debian GNU/Linux 9`
* URLs (if applicable): N/A
* Node.js version: `8.x`

**What steps will reproduce the problem?**

Navigating between SPA routes that contain elements with a `background-image: url()` style.

_Please include code that reproduces the issue._

It's hard to produce a full code sample since we are seeing this when using Puppeteer to do screenshot testing in my company's product.

Here are the additional flags, on top of the defaults, that we are passing to Puppeteer:

```
let args = puppeteer.defaultArgs();
args.push('--disable-gpu');
args.push('--ignore-certificate-errors');
args.push('--disable-web-security');
args.push('--no-sandbox');
args.push('--disable-setuid-sandbox');
args.push('--no-zygote');
args.push('--enable-font-antialiasing');
args.push('--incognito');
args.push('--disable-dev-shm-usage');
```

We are doing the following to issue navigations within our SPA framework AngularJS using its [$location](https://docs.angularjs.org/guide/$location) service:

```
await page.evaluate((relativeUrl) => {
    $('[ng-controller]').injector().get('$location').url(relativeUrl);
    $('[ng-controller]').injector().get('safeApply')($('[ng-controller]').injector().get('$rootScope'));
}, relativeUrl);

await page.waitForSelector(waitForSelector);
```

Note that we are using `waitForSelector` after the navigation. I also tried using `waitForNavigation` and `waitUntil: networkidle0` to see if that helped anything, but it didn't. I verified that AngularJS's `$location` service does use [the History API](https://developer.mozilla.org/en-US/docs/Web/API/History) when the application is in `HTML 5 mode`, which ours is.

**What is the expected result?**

Consistent images will be produced.

**What happens instead?**

Images sometimes render slightly differently between multiple runs of a screenshot test in which we navigate to a UI and use `screenshot` to capture it. You can't tell with the naked eye, but they show up in our screenshot test failure diffs. Here are some examples, with a diff output shown in the middle using [pixelmatch](https://github.com/mapbox/pixelmatch) via [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot#jest-image-snapshot). Note that these are just three examples of many that we have come across, and in **all** cases it is due to an element with a `background-image: url()` style.

1. See the two hexagons on the right:

![background-image url rendering diff example](https://user-images.githubusercontent.com/1845257/45715057-e8ad7c80-bb58-11e8-86c5-57c3db2bee0b.png)

2. See the yellow icon at the top:

![background-image url rendering diff example 2](https://user-images.githubusercontent.com/1845257/45715187-33c78f80-bb59-11e8-8461-cc37c9878926.png)

3. See the avatar circle:

![background-image url rendering diff example 3](https://user-images.githubusercontent.com/1845257/45715207-4215ab80-bb59-11e8-8fab-748e1c274bd3.png)

**Comment by booleanbetrayal** [comment]
Wondering if this could be some sort of Chromium compositing optimization that isn't properly disabled or something along those lines.
