### ISSUE TITLE
setinterception doesn't capture all outgoing requests generated by the page

### ISSUE THREAD

**Issue by ramanbhati** [puppeteer/puppeteer#3271]
### Steps to reproduce
I am using jest-puppeteer and jest-preset.
**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: mac OS high sierra
* URLs (if applicable): www.nike.com
* Node.js version: v8.11.0

**What steps will reproduce the problem?**
1) Visit Nike's website using: page.goto('https://nike.com', {waitUntil: 'networkidle2'});
2) Look for network requests generated by the page using: 
await page.setRequestInterception(true);
    let url = [];
    page.on('request', interceptedRequest => {
      url.push(interceptedRequest.url());
      console.log('requests checkpoint 1', url);
      interceptedRequest.continue();
    });

_Please include code that reproduces the issue._

1.    page.goto('https://nike.com', {waitUntil: 'networkidle2'});
2.    
    await page.setRequestInterception(true);
    let url = [];
    page.on('request', interceptedRequest => {
      url.push(interceptedRequest.url());
      console.log('requests checkpoint 1', url);
      interceptedRequest.continue();
    });

3.

**What is the expected result?**
I am hoping to get a list of all the request urls made by nike.com page.

**What happens instead?**
Sometimes I get empty list (0 request urls), other times I get 2-3 request urls instead of 30 urls.

**Comment by aslushnikov** [comment]
The following gives me 100+ requests reliably. Maybe you don't await the `page.goto` command?

```js
const pptr = require('puppeteer');

(async() => {
  const browser = await pptr.launch();
  const page = await browser.newPage();
  const urls = [];
  await page.setRequestInterception(true);
  page.on('request', request => {
    urls.push(request.url());
    request.continue();
  });
  await page.goto('https://nike.com', {waitUntil: 'networkidle2'});
  console.log(urls.length);
  await browser.close();
})();
```

**Comment by ramanbhati** [comment]
@aslushnikov thanks. It works. :) :)
