### ISSUE TITLE
Aborting long-hanging req.continue() when interception is enabled

### ISSUE THREAD

**Issue by bluepeter** [puppeteer/puppeteer#3272]
Is there any way to abort an already `continue()`d request? It's obviously not possible to use `abort()` or `respond()` as we get an error `Request is already handled!`.

We are seeing various blocking Javascript just simply "not respond" at all when we have interception enabled. How can we interrupt and kill these attempts?

**Comment by aslushnikov** [comment]
>  How can we interrupt and kill these attempts?

@bluepeter I don't think it's possible atm.

> We are seeing various blocking Javascript just simply "not respond" at all when we have interception enabled.

This sounds like a bug. Can you please shed some more light on this?

**Comment by bluepeter** [comment]
> This sounds like a bug. Can you please shed some more light on this?

Unfortunately I don't think it is a bug with Puppeteer 😃But I would appreciate any guidance, as it is possibly a bug w/ Chrome or our build process. Everything works perfectly when we use the Chrome build that bundles w/ Puppeteer and we run locally on Linux or MacOS.

But we run in PROD on AWS Lambda. As such, we build a vanilla headless 71.0.3542.0 Chrome binary for Linux (via a [script almost identical to this](https://github.com/adieuadieu/serverless-chrome/blob/master/packages/lambda/builds/chromium/build/build.sh)) and use `executablePath`.

When using the headless Chrome we built, either locally or on Lambda, we get timeouts on some rare sites when seemingly either trying to load or execute "bulky" Javascript (example [site 1](https://www.crediteurope.ch) and [site 2](https://www.live.melbourne/about/) both have this issue... the latter with some crazy emoji js they are trying to load/do something with).

When we use 69.0.3494.0 built in the exact same way, we don't have these issues! We thought this might be related to https://github.com/GoogleChrome/puppeteer/issues/2377 but we get this regardless of whether we are using interception or not. There are other binaries floating around out there for later versions of Puppeteer... we have tried them, and they exhibit the same issues.

So... any hints as to what other rabbit holes we can look down?? Much appreciated!

**Comment by aslushnikov** [comment]
@bluepeter What's the pptr version you're using?

**Comment by bluepeter** [comment]
@aslushnikov 1.8.0! We just tried w/ pptr 1.7 using the 71.0.3542.0 build (which we know is a no-no) and we got NO errors. So this does appear to be a problem w/ 1.8?

**Comment by bluepeter** [comment]
1.8.0! We just tried w/ pptr 1.7 using our 71.0.3542.0 build (which we know is a no-no) and we got the same errors (sorry for earlier post which suggested 1.7 fixed things).

**Comment by aslushnikov** [comment]
@bluepeter which revision of chromium do you compile (not version, but revision, e.g. pptr 1.8.0 ships with r588429)?

**Comment by bluepeter** [comment]
[588439](https://chromium.googlesource.com/chromium/src.git/+/71.0.3542.0)

![screenshot-chromium googlesource com-2018 09 20-15-44-13](https://user-images.githubusercontent.com/2158187/45850747-20006280-bcec-11e8-8572-2fa58719ec51.png)
![screenshot-omahaproxy appspot com-2018 09 20-15-44-39](https://user-images.githubusercontent.com/2158187/45850748-20006280-bcec-11e8-9c6c-c52200ed2dbd.png)

**Comment by aslushnikov** [comment]
So it looks like 588429 is working fine, whereas 588439 doesn't. Can you try compiling 588429? Also, there's a pre-build headless_shell for 588429; would it work for you?

**Comment by bluepeter** [comment]
> So it looks like 588429 is working fine, whereas 588439 doesn't. Can you try compiling 588429?

Yep, on it.

> Also, there's a pre-build headless_shell for 588429; would it work for you?

You mean the [one that installs w/ Puppeteer](https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/588429/chrome-linux.zip)? Or something else? We tried uploading the one w/ Puppeteer but its not solely headless (Lambda size limits) and, after bypassing size limits via CloudFormation, still requires a bunch of shared libraries not on Lambda (e.g., `./build/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`)

**Comment by aslushnikov** [comment]
> You mean the one that installs w/ Puppeteer? Or something else?

There's a prebuilt binary of headless shell, see here: 
http://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/588429/

**Comment by bluepeter** [comment]
Thanks! That looks promising. Trying...

**Comment by bluepeter** [comment]
Thanks @aslushnikov for your help.

The prebuilt binary works when running locally without the issues we experienced.

Putting it on Lambda is messy as we need to also include various missing shared libraries. In the process of doing that, we discovered what looks to be the solution to our original problem. (We'd prefer to build our own Chrome anyway to avoid a tricky ["5th invocation error"](https://github.com/adieuadieu/serverless-chrome/blob/master/packages/lambda/builds/chromium/build/build.sh#L73-L78) unique to Lambda.)

Adding `swiftshader/` and its two shared object files to our Lambda deployment in the same directory as headless-shell was the solution to avoid the issues we were having. No idea why.

**Comment by aslushnikov** [comment]
@bluepeter probably running with `--disable-gpu` might help as well

**Comment by phuang0619** [comment]
I've re-installed puppeteer a few times yesterday so I supposed I got the rolled back version of Chromium. ~/node_modules/puppeteer/.local-chromium/mac-588429 under version 71.0.3542.0
Yet, the piece of code still always hangs on htpps://example/j_spring_security_check
on my Mac machine with puppeteer 1.8.0 

        browser = await puppeteer.launch();
	    page = await browser.newPage();	    
        await page.setRequestInterception(true);
        page.on('request', request => {
        	console.log(request.url())
           	request.continue();
        });

I've also tried --ignore-certificate-errors or --enable-features=NetworkService, but not much luck here.
Rolling back to 1.6.2 w/ earlier verison of chromium works, but then the fix to set pdf window size in 1.8.0 will not be included.
Any response is appreciated.

**Comment by aslushnikov** [comment]
@phuang0619 try `puppeteer.launch({ignoreHTTPErrors: true})`.

**Comment by seth100** [comment]
I have the same error!
Getting the following error:
```
(node:134901) UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at Object.exports.assert (./myProject/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at HTTPRequest.abort (./myProject/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:317:21)
    at ./myProject/src/genScraper.js:74:29
    at ./myProject/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (./myProject/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Page.emit (./myProject/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at ./myProject/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:143:100
    at ./myProject/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:134901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:134901) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

after running some simple code like:

```js
let page = await browser.newPage();

await page.setRequestInterception(true);
page.on('request', request => {
    try {
        request.abort();
    } catch (error) {
        console.error(error);
    }
});

await page.goto(link);
```
