### ISSUE TITLE
how to wait for js variable can be used?

### ISSUE THREAD

**Issue by jcppython** [puppeteer/puppeteer#3274]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: centos7
* URLs (if applicable): 
* Node.js version: v8.5.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. page.goto(url);
2. await page.waitForSelector('#modal-page');
3. const gObject = await page.evaluate(() => gObject);

About my page of url.
1. page.html
```
<head>
<script src="/test.js?v=1536818560"></script>
</head>
<body>
    <div id="modal-page"></div>
</body>
<script src="/main.js?v=1536818560"></script>
```

2.  test.js
```
// some codes takes a long time to run
var gObject = new Object();
```

3. main.js
```
$(document).ready(function () {
    $('#modal-page').append('<div id="load-final">nihao</div>')
});
```

**What is the expected result?**
```
expect(gObject).toBeDefined();
```

**What happens instead?**

```
Evaluation failed: ReferenceError: gObject is not defined
```

**Comment by jcppython** [comment]
> await page.waitForSelector('#load-final');
change to
```
await page.waitForSelector('#load-final');
```

The result will be nice. but I have to add thus element in main.js.

**Comment by vsemozhetbyt** [comment]
You can try:
```js
await page.waitForFunction(() => 'gObject' in window);
```
or:
```js
await page.waitForFunction(() => typeof gObject === 'object');
```
