### ISSUE TITLE
launch chrome bug

### ISSUE THREAD

**Issue by xgqfrms** [puppeteer/puppeteer#3278]
# launch chrome bug

> missing lib: libatk-bridge-2.0.so.0

OS: CentOS 6

![image](https://user-images.githubusercontent.com/7291672/45803923-5b4f6100-bced-11e8-9edf-0d78ffa732fa.png)

```sh
Error: Failed to launch chrome!

/usr/local/apache2/webapps/url-to-pdf/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
```

# TROUBLESHOOTING: 

> libatk-bridge-2.0.so.0

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by xgqfrms** [comment]
# bug

![image](https://user-images.githubusercontent.com/7291672/45803783-001d6e80-bced-11e8-89de-dc3c3f2848e1.png)


![image](https://user-images.githubusercontent.com/7291672/45803799-0ad80380-bced-11e8-85e3-ecb22e9184ab.png)

**Comment by aslushnikov** [comment]
@xgqfrms  Looks like libatk-bridge2.0 is missing - you should install it on your host machine.

**Comment by xgqfrms** [comment]
@aslushnikov 

Hi, how to install it?

I just confused with that where should I install it? (what I mean is the install path of that lib)

puppeteer path ?

**Comment by aslushnikov** [comment]
@xgqfrms Usually you should use `apt-get` or some other packet manager available on your system.
Check out https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md for details and try searching the bugtracker - this has been discussed multiple times before, e.g. at #290.
