### ISSUE TITLE
overridePermissions has no influence on Notification.permission property

### ISSUE THREAD

**Issue by velichkin** [puppeteer/puppeteer#3279]
### Steps to reproduce

* Puppeteer version: 1.8.0
* Platform / OS version: macOS 10.3.6
* Node.js version: 8.12.0

**What steps will reproduce the problem?**

I'm trying to allow push notifications in headless chrome with puppeteer. It was implemented in #846
After I call `overridePermissions` the `Notification.requestPermission();` call returns me desired result - 'granted'. But `Notification.permission` still returns 'denied', but it should be 'granted' too.

Here is the code:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const context = browser.defaultBrowserContext();

  const page = await browser.newPage();

  await page.goto('https://serviceworke.rs/push-simple_demo.html');
  console.log(await page.evaluate(function(){return Notification.requestPermission();}));
  console.log(await page.evaluate(function(){return Notification.permission;}));

  await context.overridePermissions('https://serviceworke.rs', ['notifications']);

  await page.goto('https://serviceworke.rs/push-simple_demo.html');
  console.log(await page.evaluate(function(){return Notification.requestPermission();}));
  console.log(await page.evaluate(function(){return Notification.permission;}));

  await browser.close();
})();

```

**What is the expected result?**
default
denied
granted
granted

**What happens instead?**
default
denied
granted
denied

**Comment by velichkin** [comment]
Are there any news on this?

**Comment by rahul-khanna-forensiq** [comment]
Been a bit stuck on this myself, if you pass in {"headless" : false}, the `overridePermissions` function works as expected, however in headless mode `Notification.permission` is always denied. Anyone know what's going on here?

**Comment by nglj93** [comment]
Having same issue. Is there any fix out there?

**Comment by jnystrom** [comment]
i am also looking for this.  Even better would to be able to know when an actual Notification is shown.

**Comment by nglj93** [comment]
> Having same issue. Is there any fix out there?

Only found out run no issue without headless

**Comment by kylewill** [comment]
@aslushnikov Having the same issue as above. Running without headless the `Notification.permission` call returns "default", with headless it returns "denied".

This is despite overridePermissions being called earlier.

**Comment by neilw23** [comment]
I need this also, my notifications setting is getting set to denied by default now

**Comment by neilw23** [comment]
@aslushnikov

**Comment by sjchmiela** [comment]
FWIW it is possible that the ~successor~ alternative to Puppeteer may solve this issue — [`microsoft/playwright`](https://github.com/microsoft/playwright/). 🙂

**Comment by mathiasbynens** [comment]
@sjchmiela Playwright is not the "successor" to Puppeteer. It's a Puppeteer fork with a different approach w.r.t. cross-browser support.

**Comment by sjchmiela** [comment]
Sorry for causing misinformation then (and disturbing fellow issue participants)! 🙂 I misunderstood

> All the changes and improvements above would require breaking changes to the Puppeteer API, so we chose to start with a clean slate instead. ([source](https://github.com/microsoft/playwright/#q-how-does-playwright-relate-to-puppeteer))

as something along the lines of

> it would have been Puppeteer v3, but the amount of breaking changes would be too big.

but I guess "fork" is indeed a better single word to describe the relationship between projects, given that Puppeteer will remain active and maintained.

I will rephrase my original comment too.

**Comment by VictorLeP** [comment]
I have a feeling the issue lies deeper, with Chrome itself not properly treating the permission override. 

I'm using the lower-level Chrome DevTools Protocol itself, and a call to `Browser.grantPermissions` results in `Notification.requestPermission()` properly returning `granted`, but `Notification.permission` still returning `denied`.

https://github.com/puppeteer/puppeteer/blob/511dcf9d32638c8b6166dad90b11d432e79f2dd2/lib/Browser.js#L330-L356 
Puppeteer's `overridePermissions` is basically just passing along its parameters to `Browser.grantPermissions`, so an issue within Chrome would explain Puppeteer's behavior as well (and show that the bug does not lie with Puppeteer).

@sjchmiela Have you actually tested whether Playwright has the correct behavior? From https://github.com/microsoft/playwright/blob/a56712359664c3ab13599af04c6dd95a81146e17/src/chromium/crBrowser.ts#L117-L143 it seems they also just call `Browser.grantPermissions`, so I would find it strange if it works in Playwright but not using the Chrome DevTools Protocol directly.

**Comment by sjchmiela** [comment]
No, I didn’t. 😕 A sane workaround I settled on is disabling the notifications tests when running in headless mode.

**Comment by VictorLeP** [comment]
I submitted a [Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1052332) concerning the issue.

**Comment by hrustbb2** [comment]
Отстой

**Comment by RezaErfani67** [comment]
the same issue

**Comment by RezaErfani67** [comment]
any update?

**Comment by JCMais** [comment]
did anyone find a workaround for this?

**Comment by RezaErfani67** [comment]
@mathiasbynens
