### ISSUE TITLE
Page dimensions do not match generated PDF 

### ISSUE THREAD

**Issue by rcarmo** [puppeteer/puppeteer#328]
I'm trying to generate a single-page PDF that is the same height as the page itself, but when I generate the PDF, the page height is always different from the reported height. 

I've tried a number of strategies, and the end result is always the same: I get two "tall" pages in the generated PDF, with the second containing a very small percentage of page content.

The approach I'm taking is this:
```javascript
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.setViewport({width: 1280, height: 1024, deviceScaleFactor: 1});
await page.goto('https://theverge.com', {waitUntil: 'networkidle'});
var innerHeight = await page.evaluate(_ => {return window.innerHeight}),
    height = await page.evaluate(_ => {return document.body.clientHeight});
console.log(height);
console.log("Scrolling");
for(i=0; i<(height/innerHeight); i++) {
    page.evaluate(_ => {
        window.scrollBy(0, window.innerHeight);
    });
    await sleep(200);
    console.log(i);
}
console.log("Waiting for transfers");
await page.waitForNavigation({networkIdleTimeout: 15000, waitUntil: 'networkidle'});
console.log("Done.");
//try grabbing the height again, because loaded content will change it
var height = await page.evaluate(() => {return document.body.clientHeight});
console.log(height);
await page.pdf({path: 'theverge.pdf', width: "1280px", height: height + "px", printBackground: true});
browser.close();
```

I think the difference is due to Chrome activating print CSS (which then changes content size subtly). Is there any way to avoid this happening (either by disabling the print CSS like in #312 - which would be OK by me - or by extending the `.pdf()` method to have a single-page option)?

**Comment by pavelfeldman** [comment]
Closing in favor of #312.

**Comment by hbakhtiyor** [comment]
still not match, even with emulating screen media type
