### ISSUE TITLE
No node found error

### ISSUE THREAD

**Issue by fibag21** [puppeteer/puppeteer#3280]
Error: No node found for selector: body > section > div.g12 > div > div.ui-tabs-panel.ui-widget-content.ui-corner-bottom > div.Manager.angular-form.importsManagerForm.ng-scope > div > div > form > div > div > section:nth-of-type(2) > div:nth-of-type(2) > input

Selector as written above produces results when typed in the Chrome dev console. Error comes when trying to automate against web page https://app.c2atom.com/home#/imports-manager

### Steps to reproduce
run index.js after renaming from index.txt

See also page in html form
[imports-manager.txt](https://github.com/GoogleChrome/puppeteer/files/2401950/imports-manager.txt)
.
[index.txt](https://github.com/GoogleChrome/puppeteer/files/2401942/index.txt)

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version: Windows 10-1709-64 bits
* URLs (if applicable): https://app.c2atom.com/home#/imports-manager
* Node.js version: 8.12.0

**What steps will reproduce the problem?**
running index.js

**What is the expected result?**
selecting the item and being able to type in some text.

**What happens instead?**
Error

**Comment by k3mayo** [comment]
@fibag21, this seems like a synchronization issue where your puppeteer script is faster than what's happening in the application. You can play around with the waitUntil options in `page.goto()` or use the `page.waitForSelector() `before any of the click, type, or select calls. Also, improving some of the css selectors might help. (i.e. BUTTON_SELECTOR='button[type='submit']' can be used instead)

**Comment by fibag21** [comment]
Thanks k3mayo for the quick reply. page.waitForSelector() did the trick. I do not have any influence on improving the CSS.
Issue SOLVED
