### ISSUE TITLE
Input in Windows file upload

### ISSUE THREAD

**Issue by fibag21** [puppeteer/puppeteer#3281]
### Steps to reproduce
I click on a button selector which opens a Window file upload popup (vs specific browser popup) which allows me to chose a file. Shoudl then type in the file name and click on 'open' for coming back to previous page and going further in site. 

How should I handle this ?

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version: Windows 10-1709-64 bits
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

**Comment by aslushnikov** [comment]
if there's an input of type "file", you can use [`elementHandle.uploadFile`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-elementhandleuploadfilefilepaths) method. If the `input` is created dynamically, then there's no good solution atm; please read a discussion in #2946.

**Comment by fibag21** [comment]
Hi,

Thanks. This is an input of type "file", so the elementHandle.uploadFile
should work.

**Comment by Keerthivasanmohan** [comment]
Hi Team,
The above solution works partially, the file is uploaded but the content of the file is not update any input on this please help me, following was the image
![image](https://user-images.githubusercontent.com/46280162/50757150-6de1ac00-1284-11e9-97b8-4c207e31d32b.png)
my selector: 
 var findelement = await bs.page.$("#upload-used-car-photo > span > div.ant-upload.ant-upload-drag > span >input[type='file']");
          await findelement.uploadFile(absoultepath);
