### ISSUE TITLE
elementHandle.uploadFile with form containing multiple input(type=file) fields

### ISSUE THREAD

**Issue by fibag21** [puppeteer/puppeteer#3283]
### Steps to reproduce
I want to automate a form (no control on its contents) that contains several fields of type=file but for which the type of contents depends on which button is selected.

Any idea on how to handle this ?
![imports](https://user-images.githubusercontent.com/11194381/45843694-43c4a800-bcee-11e8-9d13-17b75238ac91.PNG)

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
@fibag21 what do you mean by "content depends on which button is selected"? Do you have a URL I can look at?

**Comment by fibag21** [comment]
Hi,

You can use this URL:
https://app.c2atom.com/home?lang=en-US#/imports-manager. You have to log in
to reach this page, and therefore you can use my email and "puppet33r" as
pwd.

Depending on the button you click, you can either validate or actually
import customers or CIs from a CSV file, but the format of the file depends
on the fact it's for customers or CIs.

Thanks for your help.

**Comment by aslushnikov** [comment]
@fibag21 hmm, so I'm not sure what's the issue. The following should work just fine:

```js
// Client validation button
const validateClient = await page.$(`section:nth-child(6) > div.span3 > div:nth-child(1) > div > div > input[type="file"]`);
await validateClient.uploadFile('/path/to/file.csv');
```

**Comment by fibag21** [comment]
Maybe just my lack of knowledge :-)

Thanks

**Comment by aslushnikov** [comment]
Good, hope it helped :)
