### ISSUE TITLE
Only getting single page PDF

### ISSUE THREAD

**Issue by 767994269** [puppeteer/puppeteer#3285]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version:
  1.8.0
* Platform / OS version:
  win10+64
* Node.js version:
 8.9.4
**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
'use strict';
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch({
        timeout:0,
        args: ['--disable-gpu', '--no-sandbox', '--disable-setuid-sandbox'],
        executablePath: './chromium/chrome.exe',
        headless: true,
  });
  const page = await browser.newPage();
  await page.goto('http://192.168.0.165:80', {waitUntil: 'networkidle0'});
  page.emulateMedia('screen');
  await page.pdf({
    path: 'hn.pdf',
    format: 'A4',
    printBackground: true,
  });
  await browser.close();
})();
```
**What is the expected result?**
multiple pages

**What happens instead?**
single page ,content lost

No matter how high the  height , I can only print one pdf,the contents behind it are all lost. It should be multiple pages. Is it related to CSS print?

**Comment by aslushnikov** [comment]
Can you share your website?

**Comment by 767994269** [comment]
> Can you share your website?

I found it because my website body's height  is 0 .

**Comment by 767994269** [comment]
Can you share your website?
 I found it because my website body's height is 0 .

**Comment by 767994269** [comment]
> Can you share your website?

The website can not be accessed outside the internal network，

**Comment by 767994269** [comment]
> Can you share your website?
> I found it because my website body's height is 0 .

**Comment by colin-johnson** [comment]
Was there a solution found for this? Dealing with the same thing

**Comment by februaryInk** [comment]
I also had this issue. It turned out that the `html` and `body` heights were being restricted by `height: 100%`. Using `min-height` instead seems to have resolved it.

**Comment by sharvy** [comment]
@page `size` and `height` should be `auto`

`await page.addStyleTag({ content: '@page { size: auto; }' })`

**Comment by eugeneblinn** [comment]
Had the same issue, I fixed it by changing the outside wrapping div in the source URL from position: absolute to position: relative.

I think it has to do with an issue in how Puppeteer acknowledges position: absolute elements with overflow

**Comment by brandonros** [comment]
> @page `size` and `height` should be `auto`
> 
> `await page.addStyleTag({ content: '@page { size: auto; }' })`

Should this be used with `await page.emulateMediaType('screen')` or `await page.emulateMediaType('print')`?

**Comment by ghost** [comment]
If you put this code in your css and it prints multiple pages, you know you have a problem with something having the height set too small:

``` css
* {
    height: auto !important;
}
```

Putting this CSS in made my page look bad but proved that it was indeed an element that had 100% height set on it.  I didn't remember because it was set by the CSS library I was using.  Hope that helps someone.
