### ISSUE TITLE
Get IP Address used by proxy

### ISSUE THREAD

**Issue by danhastings** [puppeteer/puppeteer#3287]
I am using an authenticated proxy to scrape web pages. For debugging purposes, I would like to be able to write the IP address of the proxy we are connecting through to a log. If we see a bunch of errors and they are all the same IP we can count it down to bad IP with the proxy and not a bug. 

If I navigate to a page via a proxy, is there a way for me to get the IP address that the proxy used to connect to the remote web server?

**Comment by aslushnikov** [comment]
@danhastings I assume you specify the proxy when launching browser using the command-line flag. In this case, don't you know the proxy already?

**Comment by danhastings** [comment]
@aslushnikov I specify the proxy server domain. All requests I make route through this domain and will be assigned a random IP. If i hit a website like whatsmyip.org, the IP address given to me will be different every time. I want to be able to find out what this is.

**Comment by aslushnikov** [comment]
@danhastings We don't have this information in our network instrumentation; I don't see any better solution than hitting some external service to get an IP.

**Comment by brauliobo** [comment]
`curl ifconfig.co` might inspire you to do the same in js
