### ISSUE TITLE
forOf with page.evaluate

### ISSUE THREAD

**Issue by classy-giraffe** [puppeteer/puppeteer#3288]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Ubuntu 18.10
* URLs (if applicable): https://marconi-pr.registroelettronico.com/mastercom/register_manager.php?_dc=1537450418307&id_materia=xxxxxxx&action=get_assignments_subject&page=1&start=0&limit=25 (where xxxxxxx can be a value indicating my school subject)
* Node.js version: 10.10.0

i'm trying to using for-Of looping method to iterate an array of urls and use them with page.evaluate function. i will post a snippet of my code (single url version) so one person here can explain me better how to loop that.

Code:
```js
const puppeteer = require('puppeteer');

let scrape = async () => {
  const browser = await puppeteer.launch({headless: true});
  const page = await browser.newPage();
  await page.goto('https://marconi-pr.registroelettronico.com/quaderno/'); //go to login page
  await page.waitFor(2000);
  await page.click('#ext-container-6 > div.x-size-monitors.scroll'); //skip some ads
  await page.waitFor(2000);
  await page.type('#ext-element-21', 'user'); //user field
  await page.waitFor(1000);
  await page.type('#ext-element-27', 'password'); //pwd field
  await page.click('#btnAccedi'); //login button
  await page.waitFor(5000);
  await page.goto('https://marconi-pr.registroelettronico.com/mastercom/register_manager.php?_dc=1537450418307&id_materia=1000188&action=get_assignments_subject&page=1&start=0&limit=25'); //after login i want to access this 
  const html = await page.evaluate(el => el.innerHTML, await page.$('pre')); //copying some things
  await browser.close();
  return html;
};

scrape().then((html) => {
  html = JSON.parse(html); //parsing as json
  console.log(html); // Success!
});

```

**Comment by aslushnikov** [comment]
> i'm trying to using for-Of looping method to iterate an array of urls and use them with page.evaluate function.

@XxXTommyXxX so what's the problem? I don't see any for-of in the snippet you posted.

**Comment by classy-giraffe** [comment]
i'm asking how to use for-of, i tried but all my attempts went wrong

**Comment by vsemozhetbyt** [comment]
Can you provide the minimal code with for-of loop and quote any errors or fails from that attempt?

**Comment by classy-giraffe** [comment]
sure
```
const URLs = ['url1', 'url2'];
const subjects = [ ];

for (const url in URLs) {
    await page.goto(url);
    subject.push();
}
```

**Comment by vsemozhetbyt** [comment]
And what went wrong exactly?

**Comment by classy-giraffe** [comment]
i get ERR:CERT:AUTORITY:INVALID in console

**Comment by aslushnikov** [comment]
@XxXTommyXxX try launching with [`ignoreHTTPSErrors: true`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-puppeteerlaunchoptions)

**Comment by JoelEinbinder** [comment]
Thats a `for in` loop not a `for of` loop.
