### ISSUE TITLE
Examples for major feature areas

### ISSUE THREAD

**Issue by LasaleFamine** [puppeteer/puppeteer#329]
Hello and thank you for this official API.

I'm wondering if would be nice to have the complete list of examples within the `examples` directory in order to achieve the feature you listed on the README:

- [x] **Generate screenshots and PDFs of pages.**
- [x] **Crawl a SPA and generate pre-rendered content (i.e. "SSR").** ([examples/README](https://github.com/GoogleChrome/puppeteer/blob/master/examples/README.md))
- [x] **Scrape content from websites.**
- [x] **Automate form submission, UI testing, keyboard input, etc.** ***[partially covered]***
- [x] **Create an up-to-date, automated testing environment. Run your tests directly in the latest version of Chrome using the latest JavaScript and browser features.** ***[dunno if there are some examples for this point]*** ([examples/README](https://github.com/GoogleChrome/puppeteer/blob/master/examples/README.md))
 - [x] **Capture a timeline trace of your site to help diagnose performance issues.**

Of course some of these points could be achieved reading the API docs, but I'm thinking also about best practices.  
For example, if I want to crawl a **SPA** (or better, a **PWA**), do I just need:

```js
...
// Is this what I'm looking for?
const content = await page.evaluate(() => document.documentElement.innerHTML)

```

I wanted to make a PR to add some other examples, but I really want to know if I'm thinking in the right way.
Thanks!

**UPDATE:**
Added an ([examples/README](https://github.com/GoogleChrome/puppeteer/blob/master/examples/README.md)) for new resources.

**Comment by ebidel** [comment]
Yea, it would be nice to have full examples for all of these. 

For "scrape content from websites", what more would you want to see than the [google search example](https://github.com/GoogleChrome/puppeteer/blob/master/examples/search.js)? 

The 5th bullet might be fairly involved to show a full example. I think we can offload that to a developer guide later on that shows how to use puppeteer in a CI env.

**Comment by LasaleFamine** [comment]
> For "scrape content from websites", what more would you want to see than the google search example?

This is correct, my oversight. I have updated the issue.
What about the 2nd bullet? Is it the same?

> The 5th bullet might be fairly involved to show a full example. I think we can offload that to a developer guide later on that shows how to use puppeteer in a CI env.

Understandable 👍

**Comment by ebidel** [comment]
Showing how to discover ("crawl") all pages of a SPA might be a useful example.

For "SSR rendering a SPA", check out https://github.com/samuelli/bot-render/. It's an interesting project from a member of the Polymer team that uses headless Chrome in docker to serve up rendered pages to a search crawler.

**Comment by LasaleFamine** [comment]
Thanks for the hint, but I'm already using the bot-render by samuelli for my Polymer applications, I was just thinking how to use pupeeteer for this purpose!

**Comment by cb109** [comment]
Are there any examples yet on how to use puppeteer as an e2e testing tool? Like, adding assertions/BDD expects and running that with mocha or something like that? If not, please consider this a humble request for point no. 5 :)

**Comment by aslushnikov** [comment]
Looks like most of the examples are there.

**Comment by LasaleFamine** [comment]
Uhm, 'there' where?  By the way, "the most" are not "all" as listed in the issue... Anyway, no prob if you want to close the issue.

**Comment by ebidel** [comment]
Let's keep this open a bit longer so I remember to create samples and/or write articles on the topics.

**Comment by jblotus** [comment]
Would love to hear if anyone is running jasmine on top of this - right now at work we are using karma to run phantom js and run unit tests via jasmine. Is puppeteer suitable to replace this setup?

Looks like some folks are messing with it:

https://github.com/Quramy/angular-puppeteer-demo

**Comment by ebidel** [comment]
Project that uses puppeteer with mocha:
https://www.npmjs.com/package/mocha-headless-chrome

**Comment by LasaleFamine** [comment]
And here is a project that uses puppeteer as renderer: https://github.com/cheeaun/puppetron

**Comment by aslushnikov** [comment]
There are three examples that are not covered yet:

> [ ] Crawl a SPA and generate pre-rendered content (i.e. "SSR").
 
This is too massive for an example and worth a separate project. [Puppetron](https://github.com/cheeaun/puppetron) in this sense looks legit

> [ ] Create an up-to-date, automated testing environment. Run your tests directly in the latest version of Chrome using the latest JavaScript and browser features. [dunno if there are some examples for this point]

Testing is a broad subject. Puppeteer itself [uses jasmine](https://github.com/GoogleChrome/puppeteer/blob/master/test/test.js) to test its functionality, this might be a good example.

> [ ] Capture a timeline trace of your site to help diagnose performance issues.

Out documentation has a code snippet: [Tracing](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-tracing)

@LasaleFamine is there anything else you'd like to see here?

**Comment by LasaleFamine** [comment]
Hi @aslushnikov, well, now I have found some examples around, but maybe it's worth mentioning these projects within the Puppeteer doc (or somewhere).
Anyway, if @ebidel doesn't need this issue opened still, we can close. Maybe I will update the main message with the new examples.

**Comment by ebidel** [comment]
Until we have a better place, we could put a readme in the examples/ folder and reference some of these.

**Comment by LasaleFamine** [comment]
A little proposal:

File: `examples/RESOURCES.md`

# Resources and examples

> Useful tools or projects as example of main Puppeteer features.

## Web scraping
- [Puppetron](https://github.com/cheeaun/puppetron) - Non-production (Headless Chrome Node API)-based rendering solution.
 - [Thal](https://github.com/emadehsan/thal) - Getting started with Puppeteer and Chrome Headless for Web Scraping.

## Testing
- [angular-puppeteer-demo](https://github.com/Quramy/angular-puppeteer-demo) - A demonstration repository explains how to replace from Karma to Puppeteer.
- [mocha-headless-chrome](https://github.com/direct-adv-interfaces/mocha-headless-chrome) - Tool which runs client-side **mocha** tests in the command line through headless Chrome.

**Comment by LasaleFamine** [comment]
Updated the issue. I think we can close this.

**Comment by ebidel** [comment]
Indeed :)
