### ISSUE TITLE
Clarify "Chrome Headless fails due to sandbox issues" section

### ISSUE THREAD

**Issue by l0b0** [puppeteer/puppeteer#3296]
The "Chrome Headless fails due to sandbox issues" section in docs/troubleshooting.md mentions "Make sure kernel version is up-to-date." Without more information this is pretty much meaningless. I *assume* that what you mean is you only test Puppeteer with recent versions of the kernel, and therefore nobody should expect it to work with currently unsupported kernels. Is that the case?

Also, the linked document says at the beginning that "[t]his page is mostly out-of-date", so that basically leaves only a single option (disabling the sandbox, which I really don't want to do) and no way to debug or fix the actual problem.

**Comment by aslushnikov** [comment]
[Linux Sandboxing](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) section was recently updated - it's good now.
