### ISSUE TITLE
background-repeat on pdf print not working for each page

### ISSUE THREAD

**Issue by Acr0most** [puppeteer/puppeteer#3297]
### Steps to reproduce

* Puppeteer version: 1.8.0
* Platform / OS version: MacOS High Sierra
* Node.js version: 8.12.0

**What steps will reproduce the problem?**

1. create a div (width: 21cm, height: > 29cm) (A4 dimensions)
2. add following css rules

```
background: url(https://www.w3.org/2008/site/images/logo-w3c-screen-lg); // just for testing
background-repeat: repeat-y;
background-size: 21cm 29cm;
background-position: 0cm 0cm;
```

3. print via API or print in chrome (PDF)

**What is the expected result?**

Each page should have the background-image from css-style.

**What happens instead?**

The background image shown only on first page. 

If you decrease background-size to sth. like 21cm 10cm you can see that the background will repeat but is cutted after first page.

**Comment by santhoshmanikandan** [comment]
Was this fixed? My requirement is to print an image on every page while printing.

**Comment by Acr0most** [comment]
It was my fault. I added the main wrapper with a fixed height smaller than the height of rendered content. So the background was ok, but the wrapper div not height enough to show it correct.

You could check this example if you maybe have the same problem.

```
 <style>
        .wrapper {
            background: url(https://www.w3.org/2008/site/images/logo-w3c-screen-lg); // just for testing
            background-repeat: repeat-y;
            background-size: 21cm 29cm;
            background-position: 0cm 0cm;
            width: 21cm;
            height: 50cm;        
        }
        </style>
        <div class="wrapper"></div>
```
Here the background should be rendered through the first page and a little bit more than half of the second page.

**Comment by santhoshmanikandan** [comment]
That's working fine. I also see a distortion in the at the end of each page. 

Is it possible to achieve the same without setting the height in background-size property? Like I have a logo which will be printed in the center or top right in all the pages?

**Comment by santhoshmanikandan** [comment]
That's working fine. I also see a distortion in the at the end of each page. 

Is it possible to achieve the same without setting the height in background-size property? Like I have a logo which will be printed in the center or top right in all the pages?

**Comment by Acr0most** [comment]
I think the easiest way is to create your image in format 21cm x 29cm and add your logo where you want. Then you can load this image on every page.
Another benefit: If you wanna change your background or logo, you can only replace the image at your endpoint. Otherwise you have to take changes in your code.

**Comment by santhoshmanikandan** [comment]
How about achieving it without setting the height of the wrapper beforehand in-case of an dynamic content? 

>  <style>
        .wrapper {
            background: url(https://www.w3.org/2008/site/images/logo-w3c-screen-lg); // just for testing
           -webkit-print-color-adjust: exact;
            background-repeat: repeat-y;
            background-size: 21cm 29.7cm;
            background-position: 0cm 0cm;
            width: 21cm;
            height:100vh;
        }
        </style>
        <div class="wrapper">
		HTML content on page one ...

			<div style='page-break-after:always'></div>

		HTML content on page two ...
              <p style=" display: block;"></p>
          </div>

This prints the image only in the first page.

**Comment by Acr0most** [comment]
sure, you could use it also this way. 

In my application im using another absolute div next to the main content to insert a background image div for each page, because the content is very dynamically.
