### ISSUE TITLE
Doesn't read the page. An error: 

### ISSUE THREAD

**Issue by kselax** [puppeteer/puppeteer#3299]
I've run the code
const puppeteer = require('puppeteer');

```
var screenshot = 'cyberforum.png';
(async () => {
  const browser = await puppeteer.launch({
    headless:false
  })
  const page = await browser.newPage()
  await page.goto('http://cyberforum.ru')
  await page.screenshot({path: screenshot})
  console.log('See screenshot: ' + screenshot)

  await browser.close();
})()
```

And have the error:
**(node:24064) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/home/neo/node.js/test-puppeteer/node_modules/puppeteer/lib/NavigatorWatcher.js:94:21)
    at <anonymous>
(node:24064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

Some pages like http://kselax.ru works properly, but like this one doesn't.
How to fix this?

**Comment by lusarz** [comment]
Is this issue repeatable ? I've just tried on my computer, and also tried:

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('http://cyberforum.ru');
    await page.screenshot({path:  'cyberforum.png'});
    await browser.close();

code at: https://try-puppeteer.appspot.com/ and everything was ok - I've got screenshot.

**Comment by sunmynet** [comment]
I access the site 'http://jin115.com/', but get the same error when using a mobile agent. 

```
  const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-web-security', `--user-data-dir=data`] })

const page = await browser.newPage();
 await page.setUserAgent('Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Mobile Safari/537.36');
  await page.setViewport({width: 600, height: 5000, isMobile: true});

await page.goto('http://jin115.com/');

console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();
```

**Comment by kselax** [comment]
there was some javascript scripts didn't finish execution. I intersect execution after timeout exceeded by  using this code 
```
const response = await Promise.race([
    page.goto(url).catch(e => void e),
    new Promise(x => setTimeout(x, 20 * 1000))
  ]);
```
from the answer https://github.com/GoogleChrome/puppeteer/issues/2316#issuecomment-379962185

**Comment by aslushnikov** [comment]
@kselax the snippet you posted doesn't reproduce for me either. The navigation timeout you get would happen naturally if page takes too long to load - you should either bump the timeout option in `page.goto`, or ignore the error and proceed. You can also speedup loading by aborting image requests using request interception.

Hope this helps!
