### ISSUE TITLE
websocket endpoint is only accessible from localhost

### ISSUE THREAD

**Issue by mrbar42** [puppeteer/puppeteer#330]
at the moment it seems that the websocket endpoint is listening on `127.0.0.1` which makes it impossible to connect remotely from a different docker container for example.

obviously this introduces a security risk and therefore the default should stay as is, but it would be nice to allow passing bind address to the launch method

**EXAMPLE**
```js
puppeteer.launch({bindAddress: '0.0.0.0'})
```

**Comment by Garbee** [comment]
You should be able to provide `--remote-debugging-address` as an argument option. Does that not work?

For example:

```javascript
puppeteer.launch({
  args: [
    '--remote-debugging-address=0.0.0.0',
  ]
});
```

EDIT: And remember the default port is `0` to get a random port assigned. So, you'll still need to either manually define a port with `--remote-debugging-port` with the address or get the dynamically generated port later for access.

**Comment by mohyeid** [comment]
I am facing the same issue in a linux machine, but my issue is that chrome is opening at 127.0.0.1 where karma is looking for localhost. Any idea how can I force chrome to open on localhost? I used 

```--remote-debugging-address=0.0.0.0```
but this give an error 

```headless_shell.cc(705)] Invalid devtools server address```
