### ISSUE TITLE
Puppeteer - request interception returns empty post data / form data

### ISSUE THREAD

**Issue by sookinoby** [puppeteer/puppeteer#3302]
When using google's puppeteer with request interception
```js
//sample code
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.setRequestInterception(true);

//'some website with uses a tracker and post to backend using application/x-www-form-urlencoded the statistics of the website'
await page.goto('https://www.maple-af.com/');

page.on('request', (request) => {
console.log('REQUEST RECEIVED');
console.log(request.url);
// none of these work (it prints either undefined or empty value)
console.log(request.postData)
console.log(request.formData)
console.log(request.formData())
console.log(request.formData())
})
```
I inspected the whole request object in console and it shows empty.

However when I use chrome in headful (headless set to false) and manually inspect the request in dev tools, it form data is available.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8 
* Platform / OS version: mac os 
* URLs (if applicable):  https://www.maple-af.com/ (but any url that use form data .ie. contentype set to application/x-www-form-urlencoded )
* Node.js version: v8.9.4

**What is the expected result?**
The form data should be available.

**What happens instead?**
The form data is empty.
However when I use chrome in headful (headless set to false) and manually inspect the request in dev tools, it form data is available.

**Comment by aslushnikov** [comment]
@sookinoby the `request` variable you get in the `request` event doesn't have formData methods/getters. It's api is available here: [`class: Request`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-class-request). 

The postdata is accessible using [`request.postData()`](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-requestpostdata) method.

Hope this helps.

**Comment by sookinoby2** [comment]
@aslushnikov Sorry even console.log(request.postData) is empty.

**Comment by mucavv** [comment]
When you execute 

await page.goto('https://www.maple-af.com/')

you are accomplishing a GET request and not a sending post data.

**Comment by sookinoby2** [comment]
@mucavv . The page  https://www.maple-af.com/ has a tracker (similar to google analytics) which sends out a post data before the on load event
