### ISSUE TITLE
docs: Add an example of chrome extension testing on CI

### ISSUE THREAD

**Issue by mshustov** [puppeteer/puppeteer#3303]
Cases:
1 Run tests locally. There is a good example already https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions
2 Run test on CI. That part is not covered, as extension testing cannot be run in headless mode. I’ve spent a couple of hours to manage to run puppeteer on TravisCI and then found and adopted your setup https://github.com/GoogleChrome/puppeteer/blob/master/.travis.yml 
Is that a recommended way to run puppeteer in headful mode? Should we add it to the docs?

**Comment by aslushnikov** [comment]
> Is that a recommended way to run puppeteer in headful mode? 

@restrry If you're talking about xvfb - than yes, that's the default solution to run x server applications in headless environment.

> Should we add it to the docs?

I'd appreciate a PR for this. We have a travis CI section in our [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci)
