### ISSUE TITLE
headless chrome  whether to support --disable-webrtc-encryption mode?  Very urgent? thx!!

### ISSUE THREAD

**Issue by chenwdong** [puppeteer/puppeteer#3304]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
I see there's code to support it, so I guess it should work.

https://cs.chromium.org/chromium/src/content/renderer/media/webrtc/peer_connection_dependency_factory.cc?type=cs&sq=package:chromium&g=0&l=338
