### ISSUE TITLE
Is there a way to wait for network to idle for X seconds?

### ISSUE THREAD

**Issue by mranosa** [puppeteer/puppeteer#3305]
I am playing around with puppeteer and am trying to find a way for me to capture a users experience for a youtube video. I am able to make things work already, but if an ad video shows up before the video itself, my whole code gets broken.

My theory is that if I can increase the wait for network idle for X more seconds my code would work. Any workaround for this is also highly appreciated.

Thanks a lot! :smile:

**Comment by vsemozhetbyt** [comment]
Maybe something like this?
```js
const idleSpan = 60000;
let lastRequest = Date.now();

await page.setRequestInterception(true);
page.on('request', registerRequest);

while (Date.now() - lastRequest < idleSpan) await page.waitFor(1000);

page.removeListener('request', registerRequest);
await page.setRequestInterception(false);

function registerRequest(request) {
  request.continue();
  lastRequest = Date.now();
}
```

**Comment by markedmiston** [comment]
#3083 is working on exposing `networkidle0` and `networkidle2` but you can emulate it with the code from https://github.com/GoogleChrome/puppeteer/issues/1353#issuecomment-356561654. In your case you can adjust the timeout by replacing X in `waitForNetworkIdle(page, X, 0)`

**Comment by mranosa** [comment]
awesome! thanks a lot!
