### ISSUE TITLE
improve puppeteer ssr performance

### ISSUE THREAD

**Issue by wutianSweet** [puppeteer/puppeteer#3307]
Dear support

Im using  puppeteer to convert my react site to ssr. I had ignored link, xhr and other unuseless script request. int the same time, i use the same browser instanse to recive more request. but it cost 300ms - 400ms to render my page. How about Node ssr ? in the same page, ReactDOMServer.renderToString  just cost 10ms, convert Javascript to static markup. Can you  provice a light browser or api, just conver Javascript to Html string?

**Comment by aslushnikov** [comment]
> How about Node ssr ? in the same page, ReactDOMServer.renderToString just cost 10ms, convert Javascript to static markup.

If `ReactDOMServer.renderToString` works for you, you should use it. 

> Can you provice a light browser or api, just conver Javascript to Html string?

Unfortunately there's no "light browser" that will reliably render all internet. The lightest is a full-blown browser that we already have.
