### ISSUE TITLE
Any method to access full html content?

### ISSUE THREAD

**Issue by huozhi** [puppeteer/puppeteer#331]
Hi, I'm trying to do SEO pre-render for SPA by puppeteer. But I only found `page.plainText()` to get text content.
So I tried to use interception for responses. It didn't work. 😢 

```
let page = await browser.newPage()
await page.setRequestInterceptionEnabled(true)
page.on('response', response => {
  response.text().then(text => {
    console.log('response', text)
  })
})
page.goto(...)
```
Is there any method for accessing full html content correctly? Thanks.

**Comment by JoelEinbinder** [comment]
```js
let bodyHTML = await page.evaluate(() => document.body.innerHTML);
```

**Comment by Kikobeats** [comment]
@JoelEinbinder thanks for the clarification!

one question, how to specify wait until dom is ready?

**Comment by CodeBrauer** [comment]
`document.documentElement.outerHTML` will return the whole document instead only the body (but without the DOCTYPE).
@Kikobeats - It already waits till the document is loaded. You can also specify elements to wait for with `await page.waitFor('.wait-for-me');`

**Comment by Kikobeats** [comment]
Thanks!

**Comment by huozhi** [comment]
Thanks @JoelEinbinder . So I thought that puppeteer cannot do SEO stuff right ? It's a little bit wired generating html content by evaluate javascript code. 🤣

**Comment by Garbee** [comment]
> It's a little bit wired generating html content by evaluate javascript code.

If it gives you the same result, what does it matter if a method is provided in the library API or whether you evaluate the script directly?

**Comment by huozhi** [comment]
@Garbee Thanks! I'll try it!

**Comment by huozhi** [comment]
@CodeBrauer 

~~document.doctype + document.documentElement.outerHTML~~ will generate full html content with DOCTYPE

**Comment by CodeBrauer** [comment]
Oh thanks, didn't new that property.

**Comment by ebidel** [comment]
Protip: if you don't want to write any code at all, you can also dump `body.innerHTML` directly from the cmd line by running the headless chrome executable with `--dump-dom`. https://developers.google.com/web/updates/2017/04/headless-chrome#printing_the_dom_dom

**Comment by huozhi** [comment]
@ebidel that's awesome ! For my case I'd like our website been crawled by crawlers through a SEO server. Just like what [seoserver](https://github.com/thomasdavis/seoserver) do. `<head />` info are important for us.

So I'm looking for some way to setup a server by puppeteer. Thanks for your tip. 👍

**Comment by ebidel** [comment]
Just want to point out that https://github.com/GoogleChrome/puppeteer/issues/331#issuecomment-323080143 won't work. `document.doctype` serializes to `[object DocumentType]`.

**Comment by huozhi** [comment]
One solution for `document.doctype` serialize issue.

https://github.com/GoogleChrome/puppeteer/issues/406#issuecomment-323555639

**Comment by huozhi** [comment]
![image](https://user-images.githubusercontent.com/4800338/29496974-2dcde814-8611-11e7-967f-f1cb8f46d4e6.png)

Sorry for that wrong solution given above. I though it was a string before logging out the type.

**Comment by CodeBrauer** [comment]
As mentioned [here](https://stackoverflow.com/a/27838954/1990745) and also here https://github.com/GoogleChrome/puppeteer/issues/406#issuecomment-323555639:
```js
new XMLSerializer().serializeToString(document.doctype) + document.documentElement.outerHTML;
```
will do the job.

**Comment by jpbalarini** [comment]
**For future reference**
Since https://github.com/GoogleChrome/puppeteer/pull/419 you can use:
```
const html = await page.content();
```

**Comment by benag** [comment]
this doesnt work on angular web sites. you only get the bare bone html.

**Comment by CodeBrauer** [comment]
> **For future reference**
> Since #419 you can use:
> 
> ```
> const html = await page.content();
> ```

Does this return the server html (equivalent of right click » show source) response or the rendered DOM (equivalent of the DOM shown in the devtools)?

**Comment by transitive-bullshit** [comment]
> Does this return the server html (equivalent of right click » show source) response or the rendered DOM (equivalent of the DOM shown in the devtools)?

it appears to return the current contents of the DOM as opposed to the server HTML. See [here](https://github.com/puppeteer/puppeteer/pull/419/files#diff-b1397100d3965ca1373667a75e2c5f94R272) for where it's doing this.

**Comment by manthankool** [comment]
> ```js
> let bodyHTML = await page.evaluate(() => document.body.innerHTML);
> ```

It only provides the data inside the body tag. What about the title tag above that. I mean the head tag. How to get that too.

**Comment by chrismytton** [comment]
@manthankool Use `page.content()`

```js
let bodyHTML = await page.content();
```

**Comment by ralyodio** [comment]
nobody given me a straight answer. does `page.content()` give you rendered dom (ie: js dom) or just server side html?

**Comment by chrismytton** [comment]
@chovy it's the JS rendered DOM, yep.

**Comment by chan-dev** [comment]
@chrismytton how do i unwrap the actual DOM object out? In my case, i need the entire Document object including the doctype

**Comment by chrismytton** [comment]
@chan-dev I'm afraid I don't know what you mean by "unwrap the actual DOM object out", can you elaborate?

To get a string of the DOM-rendered page, including the doctype, you can use `await page.content()`.

**Comment by sivelswhy** [comment]
> ```js
> let bodyHTML = await page.evaluate(() => document.body.innerHTML);
> ```

Is it possible to remove the html tags ?

**Comment by dereckmezquita** [comment]
Is there any way to get the `HTML` but excluding the `JS`/`CSS` or other superflous things? I tried intercepting but that didn't work for me.
