### ISSUE TITLE
async inside evaluate function is not working

### ISSUE THREAD

**Issue by imkimchi** [puppeteer/puppeteer#3312]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: macOS Mojave / 10.14
* URLs (if applicable): 
* Node.js version: v10.5.0

**What is the expected result?**
to run

**What happens instead?**

I get the error below when I run this code, I have no idea why its not working.

```
await page.evaluate(async () => {
    await new Promise((resolve, reject) => {
      resolve('res')
    })
  })
```

```
UnhandledPromiseRejectionWarning:Error: Evaluation failed: ReferenceError: fn is not defined
    at __puppeteer_evaluation_script__:1:109
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:1:58
    at ExecutionContext.evaluateHandle (/core/node_modules/puppeteer/lib/ExecutionContext.js:106:13)
```

**Comment by lusarz** [comment]
Hello @imkimchi, could you paste whole script here ? I've just tried to run this code:

    const browser = await puppeteer.launch();

    const page = await browser.newPage();
    await page.goto('https://example.com');

    await page.evaluate(async () => {
      const color = await new Promise((resolve, reject) => {
        resolve('blue');
      })
      document.body.style.background = color;
    });
    await page.screenshot({path: 'screenshot.png', fullPage: true});

    await browser.close();

on https://try-puppeteer.appspot.com/, and I've got expected result.

**Comment by tracker1** [comment]
Are you using babel?  if so, it may be translating your async functions in an incompatible way.

**Comment by aslushnikov** [comment]
I can't repro this either.

If transpilation is involved, please check out workaround in [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#code-transpilation-issues)

**Comment by rohitsg** [comment]
> Hello @imkimchi, could you paste whole script here ? I've just tried to run this code:
> 
> ```
> const browser = await puppeteer.launch();
> 
> const page = await browser.newPage();
> await page.goto('https://example.com');
> 
> await page.evaluate(async () => {
>   const color = await new Promise((resolve, reject) => {
>     resolve('blue');
>   })
>   document.body.style.background = color;
> });
> await page.screenshot({path: 'screenshot.png', fullPage: true});
> 
> await browser.close();
> ```
> 
> on https://try-puppeteer.appspot.com/, and I've got expected result.

giving same referenceError. Modifiying compilerOptions in tsConfig.json solved the issue - https://github.com/puppeteer/puppeteer/issues/1665#issuecomment-429356629
