### ISSUE TITLE
Any idea for how to run puppeteer with cookies on installed Chrome in my computer?

### ISSUE THREAD

**Issue by ace53thntu** [puppeteer/puppeteer#3313]
- Some websites, they have google reptcha v2. So, I want to run puppeteer with cookies on Chrome in my computer, not with Chromnium. Any idea for this?

**Comment by lusarz** [comment]
What about using `executablePath` property:

    await puppeteer.launch({ headless: false, executablePath: '/usr/bin/google-chrome' })

**Comment by lusarz** [comment]
Although `executablePath` is not enough, because puppeteer overrides [user-data-dir](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/user_data_dir.md) argument here:
https://github.com/GoogleChrome/puppeteer/blob/4e48dfc7a195331ab1ff987d98290a6ab060a353/lib/Launcher.js#L105

Unfortunately solution like:

    await puppeteer.launch({
      headless: false,
      executablePath: '/usr/bin/google-chrome',
      args: ['--user-data-dir=/home/lukasz/.config/google-chrome']
    });

ended with `UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!` for me - I'll try to investigate a bit more why.

Maybe also [my answer from stackoverflow to another thread](https://stackoverflow.com/a/52576048/4097673) may be helpful to create workaround here

**Comment by ace53thntu** [comment]
Yes, I tried with `executablePath` and `user-data-dir`. It's ok. But need first login for save the cookies. Thank you!

**Comment by aslushnikov** [comment]
> Unfortunately solution like: ended with UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! for me - I'll try to investigate a bit more why.

Weird, this should work just fine - as far as you use [proper puppeteer version](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-api-tip-of-tree).

I'm glad it worked for @ace53thntu

**Comment by ace53thntu** [comment]
> > Unfortunately solution like: ended with UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! for me - I'll try to investigate a bit more why.
> 
> Weird, this should work just fine - as far as you use [proper puppeteer version](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-api-tip-of-tree).
> 
> I'm glad it worked for @ace53thntu

Thanks @aslushnikov . It's worked

**Comment by ace53thntu** [comment]
So, one more question. Do you know how to implement Puppeteer in Chrome Extension? I wrote code for create a Chrome Extension with React. I want to use Puppeteer in it. I search on google but now not yet found any solution. @aslushnikov

**Comment by pleerock** [comment]
@aslushnikov there is definitely an issue when you run `executablePath` + `userDataDir` + `headless: false`, at least on macos. There is report by @lusarz and [opened question on SO](https://stackoverflow.com/questions/51865092/make-puppeteer-use-local-profiles-cookies).

I also failed to use Chrome's cookies. User data dir and executablePath are okay, it opens site in my google chrome (but I can't see it visually with headless disables because of above issue), it just ignores cookies when opens the site. Any help is appreciated, maybe there is hidden specifics or something that runs this site in my chrome with my profile, but it still in some sandbox or there is some restrictions on cookies reading or something.

**Comment by vsemozhetbyt** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/921

**Comment by RadiumZone** [comment]
> @aslushnikov there is definitely an issue when you run `executablePath` + `userDataDir` + `headless: false`, at least on macos. There is report by @lusarz and [opened question on SO](https://stackoverflow.com/questions/51865092/make-puppeteer-use-local-profiles-cookies).
> 
> I also failed to use Chrome's cookies. User data dir and executablePath are okay, it opens site in my google chrome (but I can't see it visually with headless disables because of above issue), it just ignores cookies when opens the site. Any help is appreciated, maybe there is hidden specifics or something that runs this site in my chrome with my profile, but it still in some sandbox or there is some restrictions on cookies reading or something.

@pleerock I was having this issue as well on MacOS. Here is my solution.

Install Chrome Canary. Copy your /Users/<Username>/Library/Application Support/Google/Chrome/Default folder to /Users/<Username>/Library/Application Support/Google/Chrome Canary/Default

Run the following code:
   'const browser = await puppeteer.launch({
          headless: false, 
          executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
          userDataDir: '/Users/radium/Library/Application\ Support/Google/Chrome\ Canary/',
    });'


I'm sorry for the poor formatting. I'm new to posting on github and i can't get indentation to work for some reason.

**Comment by Alevale** [comment]
> > @aslushnikov there is definitely an issue when you run `executablePath` + `userDataDir` + `headless: false`, at least on macos. There is report by @lusarz and [opened question on SO](https://stackoverflow.com/questions/51865092/make-puppeteer-use-local-profiles-cookies).
> > I also failed to use Chrome's cookies. User data dir and executablePath are okay, it opens site in my google chrome (but I can't see it visually with headless disables because of above issue), it just ignores cookies when opens the site. Any help is appreciated, maybe there is hidden specifics or something that runs this site in my chrome with my profile, but it still in some sandbox or there is some restrictions on cookies reading or something.
> 
> @pleerock I was having this issue as well on MacOS. Here is my solution.
> 
> Install Chrome Canary. Copy your `/Users/YOURUSERNAME/Library/Application Support/Google/Chrome/Default` folder to `/Users/YOURUSERNAME/Library/Application Support/Google/Chrome Canary/Default`
> 
> Run the following code:
> ```
> const browser = await puppeteer.launch({
>  headless: false,
>  executablePath: '/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary',
>  userDataDir: '/Users/YOURUSERNAME/Library/Application\ Support/Google/Chrome\ Canary/',
> });'
> ````
> I'm sorry for the poor formatting. I'm new to posting on github and i can't get indentation to work for some reason.

@RadiumZone Formatted :)

**Comment by rubengmurray** [comment]
I'm adding this for reference as a few people have mentioned macOS in this thread: I've been able to use cookies for a couple of years without issue in puppeteer using the chrome-cookies-secure npm package.

**Comment by FEYeh** [comment]
```js
const chrome = require('chrome-cookies-secure');
const puppeteer = require('puppeteer');

const url = 'https://www.yourUrl.com';

const getCookies = (callback) => {
    chrome.getCookies(url, 'puppeteer', function(err, cookies) {
        if (err) {
            console.log(err, 'error');
            return
        }
        console.log(cookies, 'cookies');
        callback(cookies);
    }) 
}

getCookies(async (cookies) => {
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = await browser.newPage();

    await page.setCookie(...cookies);
    await page.goto(url);
    await page.waitFor(1000);
    browser.close()
});
```

**Comment by orihpt** [comment]
I get this error with macOS:

```undefined:0


[Error: SQLITE_CANTOPEN: unable to open database file
Emitted 'error' event on Database instance at:
] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}```
