### ISSUE TITLE
system memory usage increase surprisingly with headless chrome

### ISSUE THREAD

**Issue by lexy0093** [puppeteer/puppeteer#3314]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.6.1
* Platform / OS version: Linux/CentOS 7.5.1804
* Node.js version: v8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.launch 16 chromes
2.160 node processes connect 16 chromes randomly, so, 10 node process connect/ per chrome
3.every node process:
```js
(async() => {
    const browser = await puppeteer.connect({
        browserWSEndpoint: browseradd,
        ignoreHTTPSErrors: true,
    });
    const page = await browser.newPage();
    await page.goto(url,{timeout: 12000}).then( (value) => {
    }).catch( (error) => {
    });
    rlt['content'] = await page.content();
    console.log(JSON.stringify(rlt));
    page.close();
   process.exit();
})();
```

system memory usage increase surprisingly with time goes by. Only kill the main process can solve the problem

**Comment by aslushnikov** [comment]
@lexy0093 Two things:
1. await `page.close` so that you have a fine control on the amount of opened pages
2. try using browser context per new page.

**Comment by lexy0093** [comment]
> @lexy0093 Two things:
> 
> 1. await `page.close` so that you have a fine control on the amount of opened pages
> 2. try using browser context per new page.

@aslushnikov you mean reuse the same page? or how to use browser context per new page?

**Comment by aslushnikov** [comment]
> @aslushnikov you mean reuse the same page? or how to use browser context per new page?

 I mean - you don't await your `page.close` call - this might result in a huge pile of pages being used.

**Comment by Tamal** [comment]
@aslushnikov Are you suggesting to reuse browser object to save memory? This piece of code is running in a RabbitMQ consumer. Launching & closing browser for each use could be demanding, imo.
```
....
const browser = await puppeteer.launch({
  args: [
    // Required for Docker version of Puppeteer
    '--no-sandbox',
    '--disable-setuid-sandbox',
    // This will write shared memory files into /tmp instead of /dev/shm,
    // because Docker’s default for /dev/shm is 64MB
    '--disable-dev-shm-usage'
  ]
});
const page = await browser.newPage();
await page.setViewport(VIEWPORT);
console.log('going to', myUrl);

await page.goto(myUrl, { waitUntil: 'networkidle0', timeout: 60000, });
const buffer = await page.screenshot({ fullPage: true });
await browser.close();

// Play with buffer...
    
```

**Comment by aslushnikov** [comment]
> Are you suggesting to reuse browser object to save memory?

Definitely. Three thigns:
- Browser instance should be re-used
- Browser contexts should be re-created
- Total amount of simultaneous browser contexts should be constrained with some reasonable number
