### ISSUE TITLE
Protocol error (Page.printToPDF): The previous printing job hasn't finished

### ISSUE THREAD

**Issue by n-sharvarish** [puppeteer/puppeteer#3315]
UnhandledPromiseRejectionWarning: Error: Protocol error (Page.printToPDF): The previous printing job hasn't finished

Windows 10
Puppeteer 1.7.0
Google Chrome 69.0.3497.100
Node 10.9.0

`async function main() {

    const browser = await puppeteer.launch({
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
        ignoreHTTPSErrors: true,
        headless: true,
        devtools: false,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const page = await browser.newPage();

    await page.goto(fullUrl, {
        waitUntil: 'networkidle2'
    });

    await page.type('#username', 'admin');
    await page.type('#password', 'password');
    await page.click('#Login_Button');

    await page.exposeFunction('callback', async data => {

        logInfo('Rendering the PDF... ');

        var promise = page.pdf({
            path: outputFileName,
            displayHeaderFooter: true,
            headerTemplate: '',
            footerTemplate: '<span class="pageNumber"></span>',
            printBackground: true,
            format: 'A4'
        });

        promise.then(async value => {
		
            console.log('Got resolve');
            await browser.close();
            await process.exit();
        });

        logInfo('Finished rendering the PDF... ');
    });
}

main();`

`DEBUG: console: ##############Callback finished
(node:12548) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.printToPDF): The previous printing job hasn't finished
    at Promise (C:\Users\test\node_modules\puppeteer\lib\Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\test\node_modules\puppeteer\lib\Connection.js:201:12)
    at Page.pdf (C:\Users\test\node_modules\puppeteer\lib\Page.js:897:39)
    at page.exposeFunction (C:\Users\test\Downloads\puppeteer\create_pdf.js:101:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Got resolve`

**Comment by aslushnikov** [comment]
@n-sharvarish your `callback` returns before the PDF printing is finished; you should await your `promise`. 

```js
await page.exposeFunction('callback', async data => {

    logInfo('Rendering the PDF... ');

    const value = await page.pdf({
        path: outputFileName,
        displayHeaderFooter: true,
        headerTemplate: '',
        footerTemplate: '<span class="pageNumber"></span>',
        printBackground: true,
        format: 'A4'
    });

    console.log('Got resolve');
    await browser.close();
    await process.exit();
    logInfo('Finished rendering the PDF... ');
});
```

**Comment by seyfer** [comment]
Why doing `await process.exit();` ? isn't `await browser.close();` enought?
