### ISSUE TITLE
How to click on an element everytime it shows in the page?

### ISSUE THREAD

**Issue by mranosa** [puppeteer/puppeteer#3316]
My use case is that I am trying to capture a users youtube video experience from start to end, and would like to capture the video only. I was hoping that every-time I see a skip ad button, i'll click it right away.

Is this currently possible? Or is there a work around for this?

Cheers!

**Comment by vsemozhetbyt** [comment]
Maybe you can use [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) in a page context via [`page.evaluate()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args)?

**Comment by mranosa** [comment]
thanks a lot!
