### ISSUE TITLE
Problems with element finding on frames without name or id

### ISSUE THREAD

**Issue by eduard-lind** [puppeteer/puppeteer#3317]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:v1.8.0
* Platform / OS version: Windows 10
* URLs (if applicable): not possible, internal.
* Node.js version: 8.11.2

**What steps will reproduce the problem?**
```js
    const frame = await page.frames();
    const result = await frame.every(f => f.waitForXPath('eegdfgdfggdfg', { timeout: 10000 }));
    console.log(result);
```
When I lunch this code on the page, which contain iFrame without name or ID, as result I receive "true". Same happens when XPath is valid, but doesn't exist on page. 

**What is the expected result?**
false, because XPath is wrong  

**What happens instead?**
I receive true.

**Comment by lusarz** [comment]
The `true` result is valid because `Array.prototype.every` method returns `true` for empty array:

    [].every(item => false) === true

**Comment by eduard-lind** [comment]
But array of frames is not empty, I have at least one iFrame on page and when I output frame array, I see data there.

**Comment by lusarz** [comment]
I think that

    frame.every(f => f.waitForXPath('eegdfgdfggdfg', { timeout: 10000 }))

doesn't return promise, so `await` before is irrelevant. On the other hand

    f.waitForXPath('eegdfgdfggdfg', { timeout: 10000 })

returns Promise object, which is treated as truthy value.


Consider simplified statement:

    [1, 2, 3].every(f => Promise.resolve(false))

It is also calculated to `true`.
