### ISSUE TITLE
Implement setDefaultWaitTimeout or setDefaultTimeouts

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#3319]
Right now we have `page.setDefaultNavigationTimeout(timeout)` which is very useful. If we want to take things forward, we can implement the following,

## setDefaultWaitTimeout(timeout)
This will help set a default timeout for `waitFor` function or similar to those. There are obviously more `waitFor` use cases than `goto`. 

## setDefaultTimeouts({ navigation: timeout, waitFor: timeout })
Same like above, this will let one update all timeouts at once or just the one they want. Will remove the need for `setDefaultNavigationTimeout` or `setDefaultWaitTimeout` if happens and window for more useful api

PS: I have a project where I have at least thousands of waitFor cases for some reason and hundreds of navigation calls, this feels really promising in that sense where people have lots of test cases.

**Comment by aslushnikov** [comment]
I like the `setDefaultTimeouts` thing - thanks for suggesting!

**Comment by alexbepple** [comment]
@aslushnikov #2079 lists `setDefaultTimeout` as a breaking change. What does it break? It seems to only add. 

What is your thinking on `setDefaultTimeouts({ navigation: timeout, waitFor: timeout })` as suggested here vs `setDefaultTimeouts(timeout)` as suggested in #3158?

And finally, do you mind if I take a stab at this?

**Comment by SimonSchick** [comment]
I'd very much like to see this as well, if @alexbepple is already working on this I will wait, otherwise I might create a PR if I get around to do it.

**Comment by aslushnikov** [comment]
@SimonSchick @alexbepple please go ahead and submit a PR!

**Comment by SimonSchick** [comment]
I'd rather discuss this a little, do we want more fine grained control over timeouts?

Current idea:
```
page.setTimeouts({
  element: <number>,
  navigation: <number>,
  target: <number>,
  network: <number>, // request and responses
})
```

where as all property should be optional so you can set individual timeouts without settings all ther others.

**Comment by alexbepple** [comment]
@SimonSchick I am in favor of `setDefaultTimeouts` over `setTimeouts`. Not only does this fit in more nicely with the existing `setDefaultNavigationTimeout`, but also communicates intent more clearly.

I am wondering whether anybody has a use case for such a fine-grained timeout control? Personally, I favor simpler solutions. So I would have been happy with an all-encompassing `setDefaultTimeout(int)`. But the already implemented `setDefaultNavigationTimeout` shows in a different direction. The simplest thing without making this a breaking change would be to use binary categorization: navigation and everything else ('waitFor'). @SimonSchick Do you have a particular reason to distinguish between _element,_ _target_ and _network?_ Also another problem arises: in which category does `waitForFunction` belong?

Even with a more differentiating approach, I would like to see an all-encompassing `setDefaultTimeouts(int)`.

**Comment by entrptaher** [comment]
@alexbepple, Yes there are fine needs for such.

> I have a project where I have at least thousands of waitFor cases for some reason and hundreds of navigation calls, this feels really promising in that sense where people have lots of test cases.

Sounds really ambiguous, but, either you make another wrapper on top of puppeteer for your specific case, or implement the function directly to avoid overhead.

Ie,
- You need 60 seconds timeout for a page to load.
- However, some sample waitFor task should take 120 seconds by default.

I did not have any use case for target, network and such yet, but I think once we have basic version like navigation and waitFor, we can extend it in future, and have more control over the execution.

Simplest reason would be `setDefaultNavigationTimeout` being there but not a default `waitFor` timeout.

**Comment by aslushnikov** [comment]
We've discussed this with @JoelEinbinder and really liked the following approach.

1. For now, let's keep it simple and introduce a single `page.setDefaultTimeout(number)` method.
This overrides all timeouts we use for navigations and waitFor* methods.

```js
page.setDefaultNavigationTimeout(10000);
// Set all timeouts everywhere for 5 seconds.
// However, the navigation will still default to 10 seconds.
page.setDefaultTimeout(5000);
```

2. **If the need emerges**, we can always be fancy and teach `page.setDefaultTimeout` to accept an object with a set of per-method configuration methods:
```js
page.setDefaultTimeout({
  navigation: 10000, // equal to page.setDefaultNavigationTimeout(1000),
  waitForSelector: 12000, // set default timeout for page.waitForSelector
});
```

Let me know what you think.

**Comment by batpurev** [comment]
Hi Gurus,

Have this been implemented? I tried to use this setting but getting this error message. 
![image](https://user-images.githubusercontent.com/3252495/124218806-908b6d80-db2d-11eb-9f4e-577ddc69eaf6.png)
