### ISSUE TITLE
evaluateOnNewDocument on all new pages

### ISSUE THREAD

**Issue by Vasile-Peste** [puppeteer/puppeteer#3324]
Hello I am using the following piece of code to prevent websites from detecting puppeteer.

```javascript
const page = await browser.newPage();

page.evaluateOnNewDocument(readFileSync("puppeteer-detection-bypass.js"));
```

The problem is that when I click on a link with the "target" attribute set to "_blank". The browser opens a new tab and puppeteer is detected because the evaluateOnNewDocument is not set for this new page.

How can I handle the creation of new pages in order to set the evaluateOnNewDocument for all of them? Is there an event to listen?
Is there a way to set evaluateOnNewDocument for all new pages?

**Comment by vsemozhetbyt** [comment]
Maybe these two can help:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-targetcreated
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#targetpage

**Comment by etscript** [comment]
@Vasile-Peste Hey！ 
This problem also bothers me！

Do you have a solution now？
I would really appreciate it!

**Comment by etscript** [comment]
@Vasile-Peste The sincerity anticipates your reply !

**Comment by Vasile-Peste** [comment]
Hi @etscript, there are many solutions to this problem. One of them is to create a wrapper function which creates a new page for you, then doing some operations before returning it.

1.
```javascript
async function openNewPage (browser) {
    const page = await browser.newPage();
    
    await page.evaluateOnNewDocument(readFileSync("puppeteer-detection-bypass.js"));

    return page;
}
```

This means that everytime you want to open a new page you must call this function.

2. This is the version I am using in one of my projects.
```javascript
import puppeteer from "puppeteer";

export default class Puppeteer {
    constructor (userAgent = Puppeteer.USER_AGENT) {
        this.browser = null;
        this.userAgent = userAgent;
    }
    
    async open (options = {}, parameters = []) {
        options.args = parameters;
        this.browser = await puppeteer.launch(options);
        
        await this.closePages();
        
        return this.browser;
    }
    
    async openPage () {
        const page = await this.browser.newPage();
        
        await page.setViewport({ width: 1440, height: 900, });
        await page.setUserAgent(this.userAgent);
        await page.evaluateOnNewDocument(readFileSync("puppeteer-detection-bypass.js"));
        
        return page;
    }
    
    async getPages () {
        return await this.browser.pages();
    }
    
    async closePages () {
        const pages = await this.getPages();
        await Promise.all(pages.map(page => page.close()));
    }
    
    async close () {
        await this.closePages();
        await this.browser.close();
    }
    
    static get USER_AGENT () {
        return "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36";
    }
}
```

There are better solutions to this problem, those are my personal approaches without having spent much time. Best regards, Vasile.

**Comment by aslushnikov** [comment]
@Vasile-Peste given that you re-opened this issue.. Is there anything we (puppeteer team) can help you with?

**Comment by gokaybiz** [comment]
up

**Comment by thivagarS** [comment]
@Vasile-Peste @etscript  Facing the same issue. Do we have any solution for this. ?
