### ISSUE TITLE
Setup or change browser timezone

### ISSUE THREAD

**Issue by angrykoala** [puppeteer/puppeteer#3325]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8
* Platform / OS version: linux
* URLs (if applicable):
* Node.js version: 8.12.0

I need to use Puppeteer with different timezones for testing purposes. Would it be possible to set the browser default timezone?

**Comment by DuBistKomisch** [comment]
You can override the timezone in chromium by setting the TZ env var. One way to do this is via `env` in the `launch` arguments, e.g.:

```
puppeteer.launch({
  env: {
    TZ: 'Australia/Melbourne',
    ...process.env
  }
});
```

**Comment by angrykoala** [comment]
Thanks @DuBistKomisch I'll try that

**Comment by jcserracampos** [comment]
It's not working for me.

**Comment by doingweb** [comment]
In case anyone else coming across this also has the follow-up question:

> What are valid values for the `TZ` environment variable?

It's the list of [tz database timezone names](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by hym1884603** [comment]
> In case anyone else coming across this also has the follow-up question:
> 
> > What are valid values for the `TZ` environment variable?
> 
> It's the list of [tz database timezone names](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

It's not working for me too.

**Comment by khanh-dtp-vn** [comment]
It's not working for me too.

**Comment by DuBistKomisch** [comment]
still working for me... post some details if you expect any help

**Comment by crobinson42** [comment]
Does anyone know a way to change the timezone on the fly?

**Comment by DuBistKomisch** [comment]
@crobinson42 I don't think it's possible to change the env var without restarting the process, the only way to change it dynamically would be to change the actual system timezone and not use an env var at all.

**Comment by mathiasbynens** [comment]
#4949

**Comment by crobinson42** [comment]
### Solution

This was added in the above mentioned PR:

```
const page = await browser.newPage()

await page.emulateTimezone(timezone)
```

**Comment by RahulDoshi099** [comment]
How can i remove the date and time showing in top of the pdf page while using puppeteer ? here is the code

async generatePdf(options) {
    const parsedHtml = await this.getOutputFromLiquidJs(options.htmlBaseContent, options.inputString);
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    await page.setContent(parsedHtml, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "letter",
      printBackground: true,
      displayHeaderFooter: true,
      footerTemplate: await generateFooterTemplate(),
    });

    return pdfBuffer;
  }
