### ISSUE TITLE
Feature request: evaluateOnNewDocument has access to raw response content

### ISSUE THREAD

**Issue by gwillem** [puppeteer/puppeteer#3326]
### Steps to reproduce

* Puppeteer version: 1.8.09
* Platform / OS version: Ubuntu 16.04 x86_64
* URLs (if applicable): n/a
* Node.js version: v10.11.0

How to prepend body elements before any scripts are run? `page.evaluateOnNewDocument` seems the right stage, but document.body isn't constructed yet. I can add a DOMContentLoaded event, but it will run after inline scripts. There is a solution [here](https://stackoverflow.com/questions/48577053/how-to-manipulate-the-dom-before-in-page-scripts-are-executed?rq=1), but it involves duplicate `page.goto()` calls. 

Ideally, I could modify the raw request content in evaluateOnNewDocument. I can solve it now by using a (transforming) HTTP proxy, but that gives quite a lot of complexity overhead.

**Comment by aslushnikov** [comment]
@gwillem this will be possible with response interception: #1191. Please upvote to get it sooner :)
