### ISSUE TITLE
Set page content as String and load relative resources

### ISSUE THREAD

**Issue by tzieleniewski** [puppeteer/puppeteer#3329]
Hi Team,

I would like to set page content from the provided string.
```
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    ..
    page.setContent(htmlAsString);
```
Afterwards I would like to 'load' the page by getting also the referenced resources like CSS and images located under specific base URL.

Is such scenario possible with the usage of Puppeteer?

Godspeed
TKZ

**Comment by aslushnikov** [comment]
There's #728 that will handle this (please upvote to get it fixed sooner).

There's also a nice workaround you can employ: https://github.com/GoogleChrome/puppeteer/issues/728#issuecomment-334301491

**Comment by tzieleniewski** [comment]
@aslushnikov thx for the feedback

Unfortunatelly the workaround doesn't seem to work as resources are not loaded at all.
When I activate requests interception before the 

> page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' }); 

invocation, there is only one request and URL resolves to the `data:text/html,${html}`.

Can you share a hint what could be wrong, please.
