### ISSUE TITLE
Navigation Timeout Exceeded with page.setRequestInterception(true)

### ISSUE THREAD

**Issue by phuang0619** [puppeteer/puppeteer#3330]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: MacOS 10.13.4 High Sierra
* URLs (if applicable):
* Node.js version: 7.6.0
* Chromium. ~/node_modules/puppeteer/.local-chromium/mac-588429 under version 71.0.3542.0

**What steps will reproduce the problem?**
```
const puppeteer = require("puppeteer");

(async() => {   
	browser = await puppeteer.launch();
	page = await browser.newPage();	    
	await page.setRequestInterception(true);
	page.on("request", request => {
		console.log(request.url());
   		request.continue();	
	});

	await page.goto("https://example.url", { timeout: 0, waitUntil: "networkidle0" });
})();     
```

**What is the expected result?**
Requests continues successfully.

**What happens instead?**
https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjxAwWyWtFCc.ttf
https://fonts.gstatic.com/s/lato/v14/S6u9w4BMUTPHh50XSwaPHA3q5d0.ttf
https://fonts.gstatic.com/s/lato/v14/S6u9w4BMUTPHh6UVSwaPHA3q5d0.ttf
https://example.url/j_spring_security_check

(node:85615) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

(node:85615) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

==
I've re-installed puppeteer a few times yesterday so I supposed I got the rolled back version of Chromium.
I've also tried --ignore-certificate-errors or --enable-features=NetworkService, but not much luck here.
Rolling back to 1.6.2 w/ earlier verison of chromium works, but then the fix to set pdf window size in 1.8.0 will not be included.

**Comment by aslushnikov** [comment]
@phuang0619 the *ttf urls result in a download that's not yet supported - see #299. 

The security check url works if you pass `ignoreHTTPErrors: true`:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({ignoreHTTPSErrors: true});
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on("request", request => {
    console.log(request.url());
    request.continue();
  });

  await page.goto("https://example.url", { timeout: 0, waitUntil: "networkidle0" });
  await browser.close();
})();
```

Does this address your issue?

**Comment by junseok-oh-0** [comment]
@aslushnikov 
Hello, I'm experiencing the same issue at 1.8.0.
It seems puppeteer processes all (most?) requests/responses quite well, but domcontentloaded or load event is not fired.
Please, try these URLs with the code above.

http://m.todayhumor.co.kr/view.php?table=total&no=9408788
http://footsell.co.kr/product/detail.html?product_no=32952&cate_no=415&display_group=1
http://m.typemoon.net/plugin/mobile/board.php?bo_table=forum_neta&wr_id=3329

**Comment by phuang0619** [comment]
Hi @aslushnikov ,
thanks for replying.
With the suggested "ignoredHTTPSErrors: true" setting,
I'm still encountering hanging issue on.

https://example/j_spring_security_check
(node:52170) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
(node:52170) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could it be related to mac OS?

**Comment by phuang0619** [comment]
Hi @aslushnikov ,
after trying 1.10 , I think I found whats keeping us from reaching to the same page.
Thats is, the full script was not included in the ticket, 
The skipped part, which I thought was irrelevant, I removed to keep it clean,
turned out could actually be the root cause of the stall.

Here is the full script:
```
const puppeteer = require("puppeteer");
 
(async() => {   
  const browser = await puppeteer.launch({ignoreHTTPSErrors: true});
  const page = await browser.newPage();  
  await page.setRequestInterception(true);
  page.on("request", request => {
    console.log(request.url());
    request.continue();
  });
    	await page.goto("https://example.url", { timeout: 0, waitUntil: "networkidle0" });
	await page.type("#j_username", "-");
	await page.type("#j_password", "-");
	await Promise.all([
    	page.click("#button"),
    	console.log("clicked to login"),
    	page.waitForNavigation({ waitUntil: "networkidle0" })
    ]);
})(); 
```

The code stuck and time out after the click event,
which triggers a login service call "j_spring_security_check" and gets stuck
```
clicked to login
https://example/j_spring_security_check
(node:6202) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
(node:6202) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I managed to try a different case with service call when a login was not required, and got it through.
So I think the root cause was either spring security check or the service call triggered by click.

Hope to hear back from you.
Thanks.

**Comment by Alex0007** [comment]
I'm having same issue on `1.10.0`

adding this snippet gives navigationTimeout error on some pages, for example on this page:

https://www.freepeople.com/shop/vintage-1960s-handmade-sweater/
Resource that blocks page from loading: https://www.freepeople.com/orchestration/js/navigation/


```
page.setRequestInterception(true)
page.on("request", r => r.continue())
```

Downgrading to `1.6.2` helped.

**Comment by proton1k** [comment]
Related: https://github.com/GoogleChrome/puppeteer/issues/782#issuecomment-498712477
My question: how do you handle cases when a page requests multiple images to load for example and only one does not return response thus leading to 504 timeout?

**Comment by aslushnikov** [comment]
> Please, try these URLs with the code above.
>  http://m.todayhumor.co.kr/view.php?table=total&no=9408788
> http://footsell.co.kr/product/detail.html?product_no=32952&cate_no=415&display_group=1
> http://m.typemoon.net/plugin/mobile/board.php?bo_table=forum_neta&wr_id=3329

@batt842 all these URLs work with Puppeteer 1.17.0.

Everybody: request interception is getting better and better in recent Puppeteer versions. So please, give it chance! 

If request interception still doesn't work for you in the latest Puppeteer version,  please file a new issue with a good repro we can play with!!
