### ISSUE TITLE
Is there any way to send response in page event listener?

### ISSUE THREAD

**Issue by imkimchi** [puppeteer/puppeteer#3332]
I'm trying to return response when I get dialog on the page but seems like It returns nothing with the code below, anyone knows how to do it?

    const router = ctx => {
      page.on('dialog', () => {
         ctx.body = { "success": "false"}
      })
    }

**Comment by aslushnikov** [comment]
Hmm, I'm not sure what's router and what's ctx. Can you please re-file with proper explanation of what you're dealing with?

Thanks.
