### ISSUE TITLE
Change UNMASKED_VENDOR_WEBGL and UNMASKED_RENDERER_WEBGL

### ISSUE THREAD

**Issue by r1si** [puppeteer/puppeteer#3333]
There is some method to change (mask) the UNMASKED_VENDOR_WEBGL  and UNMASKED_RENDERER_WEBGL ? 
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info

**Comment by Kingy62** [comment]
Were you able to solve the issue?

**Comment by TheGP** [comment]
Why its closed?
