### ISSUE TITLE
Puppeteer on OpenVZ kernel 2.6.32

### ISSUE THREAD

**Issue by davidebaldini** [puppeteer/puppeteer#3334]
**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Debian, OpenVZ kernel 2.6.32, i686
* Node.js version: 8.11.2

Running `puppeteer.launch(...)` produces 

```
(node:18358) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! spawn /home/davide/crawler/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome ENOENT
```

A quick inspection of the chrome binary:

```
$ file crawler/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome
node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped

$ ldd crawler/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome
not a dynamic executable
```

The entire directory tree under `node_modules/` was created with `npm i puppeteer`.

**Comment by hlr1983** [comment]
Is it the same as #2996?

**Comment by davidebaldini** [comment]
Correct me, it appears my hardware is x86_64 with a 32 bit userspace?

```
$ grep flags /proc/cpuinfo | head -n1
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf cpuid_faulting pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt

$ uname -a
Linux hwcharts 2.6.32-042stab120.11 #1 SMP Wed Nov 16 12:05:45 MSK 2016 i686 GNU/Linux
```

**Comment by hlr1983** [comment]
I think so, as said in #2996, you should try it in a x86_64 environment: 

> Chromium is compiled for x86_64, which I believe is not runnable on i686.
>
>We don't have any 32 bit builds, and there are no plans to add any. Sorry for the inconvenience.

**Comment by aslushnikov** [comment]
@davidebaldini  try launching the downloaded chromium manually; if it doesn't launch, then the chromium we download is not compatible with your environment.

In this case, two things would help:
- install chromium on your machine from some other source; e.g. using native package manager. Or compile it yourself (this is computationally intensive).
- use [`puppeteer-core`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core) - it wouldn't download useless binary on your machine. You can specify your chromium binary using `executablePath` option in the `puppeteer.launch` method.
