### ISSUE TITLE
setRequestInterception causes 304 to be returned when cache is disabled

### ISSUE THREAD

**Issue by bondom** [puppeteer/puppeteer#3335]
### Steps to reproduce
When `requestInterception` is turned on and cache is disabled(`setCacheEnabled(false)`), 
then cached request is called, status of response is 304.

When `requestInterception` is turned off - everything works fine.
There is [repository](https://github.com/bondom/setCacheEnabled) with this bug.

**What is the expected result?**
When `requestInterception` is turned on and cache is disabled, status of response should be 200.

**What happens instead?**
Status of response is 304

Also it seems that documentation in [this place](https://github.com/GoogleChrome/puppeteer/blob/v1.8.0/docs/api.md#pagesetrequestinterceptionvalue) is wrong:
> NOTE Enabling request interception disables page caching.

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Windows 10
* URLs (if applicable): https://github.com/bondom/setCacheEnabled
* Node.js version: 8.9.3

**Comment by bondom** [comment]
I am not sure, but more likely issue is related to devtools-protocol

**Comment by andrekristanto1798** [comment]
You can try use this snippet to cache manually

```
// cache globally to improve 304 and load speed
const cache = {};
const withCacheReq = async (request) => {
  const url = request.url();
  if (cache[url] && cache[url].expires > Date.now()) {
    // mocking the respond with URL
    await request.respond(cache[url]);
    return true;
  }
  return false;
};

const withCacheResp = async (response) => {
  const url = response.url();
  const headers = response.headers();
  const cacheControl = headers['cache-control'] || '';
  const maxAgeMatch = cacheControl.match(/max-age=(\d+)/);
  const maxAge =
    maxAgeMatch && maxAgeMatch.length > 1 ? parseInt(maxAgeMatch[1], 10) : 0;
  if (maxAge) {
    if (cache[url] && cache[url].expires < Date.now()) return;
    let buffer;
    try {
      buffer = await response.buffer();
    } catch (error) {
      // some responses do not contain buffer and do not need to be catched
      return;
    }
    cache[url] = {
      status: response.status(),
      headers: response.headers(),
      body: buffer,
      expires: Date.now() + maxAge * 1000,
    };
  }
};
```
