### ISSUE TITLE
page.evaluate not really waiting 

### ISSUE THREAD

**Issue by gvelasquez760** [puppeteer/puppeteer#3336]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  1.8.0
* Platform / OS version: Ubuntu 16
* URLs (if applicable):
* Node.js version: 8.9.3

**What steps will reproduce the problem?**

Try to set a select component value using page.evaluate, sometimes puppeter doesn't wait until element attribute has a value.

_Please include code that reproduces the issue._

  await page.evaluate(() => {
    return document.querySelector('.select-class').value = '44';
  });

**What is the expected result?**

select value to be 44

**What happens instead?**

sometimes select value is null

Is there any way to make sure that the element has a value? , why page.evalue is not always waiting?

Thanks!

**Comment by aslushnikov** [comment]
@gvelasquez760 the evaluate is *always* waiting; something else is going on here.

Please re-file with more details; especially with a good script that reproduces the problem and that I can run locally.
Thanks!
