### ISSUE TITLE
page.waitForNavigation never resolves

### ISSUE THREAD

**Issue by thetutlage** [puppeteer/puppeteer#3338]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: MacOSX High Sierra
* URLs (if applicable): 
* Node.js version: 10.0.0

**What steps will reproduce the problem?**

```js
const http = require('http')
const puppeteer = require('puppeteer')
const PORT = 3000

/**
 * Dummy HTTP Server
 */
http.createServer((req, res) => {
  if (req.url === '/there') {
  	console.log('Responded')
    res.writeHead(200, { 'content-type': 'text/plain' })
    res.end('reached there')
  } else {
    res.writeHead(200, { 'content-type': 'text/html' })
    res.end(`
      <a href="/there"> Redirect </a>
    `)
  }
}).listen(PORT)

/**
 * Puppeteer script
 */
async function run () {
	const browser = await puppeteer.launch()
	const page = await browser.newPage()
	await page.goto('http://localhost:3000')
	await page.click('a')
	await page.waitForNavigation()

	const text = await page.evaluate(() => document.body.innerText)
	console.log(text)
}

run().then(console.log).catch(console.log)
```

**What is the expected result?**
To see the `text` on console

**What happens instead?**
`page.waitForNavigation` is stuck and then times out after 30 seconds

**Comment by ntzm** [comment]
You're experiencing a race condition. Try using the example code instead:

```js
const navigationPromise = page.waitForNavigation();
await page.click('a.my-link'); // Clicking the link will indirectly cause a navigation
await navigationPromise; // The navigationPromise resolves after navigation has finished
```

**Comment by vsemozhetbyt** [comment]
Or you can use this way:
```js
await Promise.all([page.click('a'), page.waitForNavigation()]);
```

**Comment by thetutlage** [comment]
Thanks, and that does work

Is there any better way to avoid this race condition, without wrapping all calls with redirection inside `Promise.all`?

Also I believe, the race condition will be true for other `waitFor` functions as-well? For example: `page.waitForSelector`

**Comment by aslushnikov** [comment]
> Also I believe, the race condition will be true for other waitFor functions as-well? For example: page.waitForSelector

The `waitForSelector` is about page's state rather then some page events, so there's no race condition there.

The reason `waitForNavigation` is racy is because there's no direct connection between `page.click` and the navigation it causes.

> Is there any better way to avoid this race condition, without wrapping all calls with redirection inside Promise.all?

This race condition is inherent to the scenario; the `Promise.all` approach is just a nice trick to handle this kind of race conditions. You can avoid using `Promise.all` and `waitForNavigation` using `waitForSelector`.

Hope this helps.

**Comment by techsin** [comment]
how is there a race condition. would love some explanation.

**Comment by techsin** [comment]
nvm https://github.com/GoogleChrome/puppeteer/issues/1412#issuecomment-345482273

**Comment by sheerun** [comment]
What to do if it's unknown whether click will result in navigation? If I call waitForNavigation and there's no navigation event then test hangs infinitely. Ideally any started network requests would be detected and if there are none waitForNavigation would return immediately

**Comment by techsin** [comment]
not saying this is ideal solution but you could wrap await in try and catch and if your code is in catch that's running meaning it timed out so you can take steps from there.

**Comment by nhhockeyplayer** [comment]
I cannot get this to work

```
            await Promise.all([thePage.click(searchButton), thePage.waitForNavigation()])
            // await thePage.waitForNavigation({ waitUntil: 'load' })
            // thePage.click(searchButton)
            // await navigationPromise
```

going to try waitForSelector

**Comment by techsin** [comment]
do this
```
let wait = thePage.waitForNavigation();
await thePage.click(searchButton);
await wait;
```

**Comment by jacobmesu** [comment]
@vsemozhetbyt Unfortunately that code also results in race conditions. Promise.all does not guaranty that the order of the array of promises is also the order of execution. So the waitForNavigation can be executed after the click and still result in a timeout. Learned it the hard way. :)

**Comment by lu4** [comment]
In my specific case I didn't get to resolve the issue using solution suggested in this thread. However I have came up with another approach that worked well for my case:

```JavaScript
// First of all we are listening for requests issued by page permanently increasing the counter when request is issued and reducing it when it is completed

let requests = 0;
let timestamp = Date.now();

await page.setRequestInterception(true);

page.on('request', (event) => {
  event.continue();

  requests++;
});

page.on('requestfinished', (event) => {
  requests--;
  timestamp = Date.now();
});

page.on('requestfailed', (event) => {
  requests--;
  timestamp = Date.now();
});

// I haven't tested `requestservedfromcache` event below, more investigation is required if it is fired together with `requestfinished` event or not. We don't want to reduce number of requests twice.
page.on('requestservedfromcache', (event) => {
  requests--;
  timestamp = Date.now();
});

// We are waiting for `maxDelay` after last request completion. If it happened more than `maxDelay` ago, then we wait for additional 250ms. Such logic is handy in case your requests are throttled.
async function allRequestsToComplete(minDelay = 250, maxDelay = 500) {
  do {
    await new Promise(resolve => setTimeout(resolve, Math.max(minDelay, maxDelay - (Date.now() - timestamp))));
  } while (0 < requests);
}

await yourElement.click();
await allRequestsToComplete(); // Works like a charm

**Comment by Maksim-Lipenka** [comment]
@lu4 thanks for sharing this! As you said works like a charm

**Comment by GordonHPepBoys** [comment]
> > Also I believe, the race condition will be true for other waitFor functions as-well? For example: page.waitForSelector
> 
> The `waitForSelector` is about page's state rather then some page events, so there's no race condition there.
> 
> The reason `waitForNavigation` is racy is because there's no direct connection between `page.click` and the navigation it causes.
> 
> > Is there any better way to avoid this race condition, without wrapping all calls with redirection inside Promise.all?
> 
> This race condition is inherent to the scenario; the `Promise.all` approach is just a nice trick to handle this kind of race conditions. You can avoid using `Promise.all` and `waitForNavigation` using `waitForSelector`.
> 
> Hope this helps.

I have the similar issue here. The purpose of the code is to generate pdf file from html by either passing html or url.

 export const html2pdf = async (html = '', url = '', format = 'Legal') => {
  let myBrowser = await getBrowser();
  const page = await myBrowser.newPage();
  const loaded = page.waitForNavigation({
    waitUntil: 'load'
  });

  if (html) {
    await page.setContent(html, { waitUntil: 'networkidle0' });
  } else if (url) {
    await page.goto(url, { waitUntil: 'networkidle0' });
  }
  // await page.setViewport({ isMobile: true, width: 375, height: 667 });
  await loaded;

  const pdf = await page.pdf({ format: format });
  await page.close();
  await myBrowser.close();
  return pdf;
};
Is there a race condition? how do you resolve it if there is?
Thanks
