### ISSUE TITLE
Does --filter=SomeTest do anything when running npm run unit

### ISSUE THREAD

**Issue by mpsommer** [puppeteer/puppeteer#3340]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version: Mac OS 10.13.6
* URLs (if applicable): https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md
* Node.js version: v9.4.0

Hello friends,

In the [Writing Tests](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md#writing-tests) section of the [CONTRIBUTING guide](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md), there is this blurb about filtering tests: 

---
- To filter tests by name:

```bash
npm run unit --filter=waitFor
```
---

**What is the expected result?**
Not exactly sure what the expected result is.  My first thought was that only tests that equal `waitFor` for would be run, so a subset of the 492 tests.  This is not the case.

**What happens instead?**

What happens is that all 492 tests are run, which is the same as behavior as:
```bash
npm run unit
```

***My question is: what does the `--filter` arg do when running tests? Anything? Does this belong in the documentation?***

Thanks!! 
P.S. I really dig Puppeteer

**Comment by aslushnikov** [comment]
@mpsommer sorry for the confusion, that's a left-over. We removed the filtering part since we never actually used it; instead, we always "focus" tests with "fit" and "fdescribe".
