### ISSUE TITLE
Trying to install puppeteer inside React app

### ISSUE THREAD

**Issue by prasadmadv** [puppeteer/puppeteer#3343]
ERROR in ./node_modules/puppeteer/node6/lib/FrameManager.js
Module not found: Error: Can't resolve 'fs' in 'D:\xampp\htdocs\repos\easyshopify\node_modules\puppeteer\node6\lib'
@ ./node_modules/puppeteer/node6/lib/FrameManager.js 17:11-24
@ ./node_modules/puppeteer/node6/lib/Page.js
@ ./node_modules/puppeteer/node6/lib/Target.js
@ ./node_modules/puppeteer/node6/lib/Browser.js
@ ./node_modules/puppeteer/node6/lib/Launcher.js
@ ./node_modules/puppeteer/node6/lib/Puppeteer.js
@ ./node_modules/puppeteer/index.js
@ ./resources/assets/js/components/Example.js
@ ./resources/assets/js/app.js
@ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

Cant resolve 'fs' where fs module is already installed.

**Comment by aslushnikov** [comment]
@prasadmadv What's "Puppeteer inside react app"?

**Comment by prasadmadv** [comment]
I am trying to install puppeteer using webpack to React.js. When i use npm install puppeteer, its installed successfully. But throws errors while compiling assets. I think it might be some issue with the path. That webpack is not able to resolve the path to node_modules folder but not sure.

Pls refer to this for "What I am trying to do with react + laravel "https://tighten.co/blog/adding-react-components-to-a-laravel-app"
But i need puppeteer to add to this application.

**Comment by prasadmadv** [comment]
Puppeteer requires "fs" to work.
And when i got to node_modules/fs i find this:

Readme.md:
# Security holding package
This package name is not currently in use, but was formerly occupied
by another package. To avoid malicious use, npm is hanging on to the
package name, but loosely, and we'll probably give it to you if you
want it.
You may adopt this package by contacting support@npmjs.com and
requesting the name.

And
package.json:
{
  "name": "fs",
  "version": "0.0.1-security",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/npm/security-holder.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/npm/security-holder/issues"
  },
  "homepage": "https://github.com/npm/security-holder#readme"
}


BUT there is not index.js file or any other files. I am novice to node & puppeteer, pls if you can help me. Thanks for showing interest in my issue friend. :)

**Comment by aslushnikov** [comment]
@prasadmadv so it looks like you're trying to bundle puppeteer to use in a web application.

Tip-of-tree Puppeteer is much more bundling-friendly and includes the `browser` field in its package.json that should help with bundling:

https://github.com/GoogleChrome/puppeteer/blob/5ebfe1a0dc89f88d3c784e546c34cae42cf9906c/package.json#L62-L70

This will be released later today as Puppeteer v1.9.0

**Comment by prasadmadv** [comment]
Hi, @aslushnikov : this fixed these errors I was getting before. But I am getting other errors now:
2 errors with MIME module abd one with WS module.

ERROR in ./node_modules/puppeteer/node_modules/mime/index.js
Module not found: Error: Can't resolve './types/other' in 'D:\xampp\htdocs\repos\easyshopify\node_modules\puppeteer\node_modules\mime'
 @ ./node_modules/puppeteer/node_modules/mime/index.js 4:55-79
 @ ./node_modules/puppeteer/lib/Page.js
 @ ./node_modules/puppeteer/lib/Target.js
 @ ./node_modules/puppeteer/lib/Browser.js
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer/index.js
 @ ./resources/assets/js/components/Example.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/puppeteer/node_modules/mime/index.js
Module not found: Error: Can't resolve './types/standard' in 'D:\xampp\htdocs\repos\easyshopify\node_modules\puppeteer\node_modules\mime'
 @ ./node_modules/puppeteer/node_modules/mime/index.js 4:26-53
 @ ./node_modules/puppeteer/lib/Page.js
 @ ./node_modules/puppeteer/lib/Target.js
 @ ./node_modules/puppeteer/lib/Browser.js
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer/index.js
 @ ./resources/assets/js/components/Example.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./node_modules/puppeteer/lib/Connection.js
Module not found: Error: Can't resolve 'ws' in 'D:\xampp\htdocs\repos\easyshopify\node_modules\puppeteer\lib'
 @ ./node_modules/puppeteer/lib/Connection.js 21:18-31
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer/index.js
 @ ./resources/assets/js/components/Example.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

Pls if you can assist me on this fix.

**Comment by prasadmadv** [comment]
Hi @aslushnikov the above patch resolved all errors while compilation. Thanks so much for you help.

But I my component file when I call puppeteer launch, it shows this error: 

Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

**Comment by aslushnikov** [comment]
@prasadmadv oh you can't call `puppeteer.launch` from-inside bundled puppeteer; it runs in the browser context and you can't launch browser from-inside browser.

You should launch browser separately and connect to it using `puppeteer.connect`.

Hope this helps!

**Comment by prasadmadv** [comment]
Hi @aslushnikov  Thanks for helping me understand this. But I still wonder about how to achieve this: "You should launch browser separately and connect to it using puppeteer.connect".

*Can I access currently running Chrome browser instance and open new page as tab?*

I am complete novice. pls help me understand this. Thanks. 👍

**Comment by aslushnikov** [comment]
> Can I access currently running Chrome browser instance and open new page as tab?

Yes, you can. You need to launch a browser instance somehow and obtain its remote debugging capability.You can do so locally using the following node.js script:

```js
const pptr = require('puppeteer');
(async () => {
  const browser = await pptr.launch();
  console.log(browser.wsEndpoint());
})();
```
This will log some URL that you can use in your bundled version of Puppeteer, using `puppeteer.connect`.

```js
const browser = await bundledPuppeteer.connect({browserWSEndpoint: "<my-ws-endpoint>"});
const page = await browser.newPage();
// ... drive automation ...
```

Instead of running browser instances locally, you can use @joelgriffith's [Browserless.io](https://www.browserless.io/) - I guess bundled Puppeteer is something that comes handy for his usecase.

**Comment by prasadmadv** [comment]
Hi @aslushnikov 
I tried to run puppeteer on node.js server directly. I get following error:  **error while loading shared libraries: libXss.so.1:**

(node:2633631) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/ecomsnip/public_html/dropshipsellingacademy.com/login/server/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/ecomsnip/public_html/dropshipsellingacademy.com/login/server/node_modules/puppeteer/lib/Launcher.js:339:14)
    at Interface.helper.addEventListener (/home/ecomsnip/public_html/dropshipsellingacademy.com/login/server/node_modules/puppeteer/lib/Launcher.js:328:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:2633631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2633631) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Please help me understand this.

**Comment by aslushnikov** [comment]
@prasadmadv you should install all the missing dependencies on your server to be able to run chrome there, see https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by prasadmadv** [comment]
Thanks man. You really helped me fix all issues. Everything works like charm now. You are a genius bro.

**Comment by lukio3** [comment]
Hi @aslushnikov 

I have created a WS endpoint from which I can connect to headless chrome and manipulate the DOM.

This works fine, executing functions through terminal. 

I wish to be able to use these functions in my app.js (compiled with webpack).

I have v.1.9.0 of puppeteer which included the browser field in my package.json. I am **not** using the non-chromium bundled puppeteer-core.

However, my webpack build still fails with the same error as @prasadmadv as soon as it sees:

`const puppeteer = require('puppeteer');`

Error:

```
This dependency was not found:

* ws in ./node_modules/puppeteer/lib/WebSocketTransport.js

To install it, you can run: npm install --save ws

These relative modules were not found:

* ./types/other in ./node_modules/puppeteer/node_modules/mime/index.js
* ./types/standard in ./node_modules/puppeteer/node_modules/mime/index.js
```

Am I missing something here @prasadmadv & @aslushnikov ?

**Comment by ketysek** [comment]
I'm also unable to compile my app:

```
Failed to compile.
./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Can't resolve 'ws' in '/frontend/node_modules/puppeteer/lib'
```

**Comment by rmlzy** [comment]
I had the same error:
```
ERROR in ./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Error: Can't resolve 'ws' in '/Users/zhiyuanliu/Work/op-static/node_modules/puppeteer/lib'
 @ ./node_modules/puppeteer/lib/WebSocketTransport.js 16:18-31
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer/index.js
 @ ./src/modules/Login/index.test.js
 @ ./src/modules lazy ^\.\/.*$ namespace object
 @ ./src/routes.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8088 ./src/index.js
```

I tried install ws, but it didn't work.
```
yarn add ws -D
```

Can someone help me?

**Comment by theo-splunk** [comment]
```
$ node_modules/.bin/jest tests --config=jest.visual.config.js
 FAIL  tests/visual.test.js
  ● Test suite failed to run

    Cannot find module 'ws' from 'WebSocketTransport.js'

    However, Jest was able to find:
    	'./WebSocketTransport.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./Launcher.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./Puppeteer.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'lib/api.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:203:17)
      at Object.<anonymous> (../../node_modules/@xxx/dashboard-build-tools/node_modules/puppeteer/lib/WebSocketTransport.js:16:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        8.317s
Ran all test suites matching /tests/i.
```
I also have a failure with respect to `ws`. For me it happens when running a jest visual test with jest-image-snapshot.

node_modules/@xxx/dashboard-build-tools/node_modules/puppeteer/lib/WebSocketTransport.js seems to fail at line 16:
`const WebSocket = require('ws');`

Oddly, I do see that `ws` is indeed included in puppeteer's package.json

@aslushnikov  any insight as to why requiring `ws` keeps failing?

**Comment by nrawat151290** [comment]
> @prasadmadv so it looks like you're trying to bundle puppeteer to use in a web application.
> 
> Tip-of-tree Puppeteer is much more bundling-friendly and includes the `browser` field in its package.json that should help with bundling:
> 
> [puppeteer/package.json](https://github.com/GoogleChrome/puppeteer/blob/5ebfe1a0dc89f88d3c784e546c34cae42cf9906c/package.json#L62-L70)
> 
> Lines 62 to 70 in [5ebfe1a](/GoogleChrome/puppeteer/commit/5ebfe1a0dc89f88d3c784e546c34cae42cf9906c)
> 
>  "browser": { 
>    "./lib/BrowserFetcher.js": false, 
>    "./node6/lib/Puppeteer": false, 
>    "ws": "./utils/browser/WebSocket", 
>    "fs": false, 
>    "child_process": false, 
>    "rimraf": false, 
>    "readline": false 
>  } 
> This will be released later today as Puppeteer v1.9.0

Below config is present in package.json of puppeteer for me:
"browser": {
    "./lib/BrowserFetcher.js": false,
    "./node6/lib/Puppeteer": false,
    "ws": "./utils/browser/WebSocket",
    "fs": false,
    "child_process": false,
    "rimraf": false,
    "readline": false
  },

But still getting below errors while bundling:

ERROR in ./~/puppeteer/lib/WebSocketTransport.js
Module not found: Error: Can't resolve 'ws' in 'C:\peerinsights\ui\home_admin\node_modules\puppeteer\lib'
 @ ./~/puppeteer/lib/WebSocketTransport.js 16:18-31
 @ ./~/puppeteer/lib/Launcher.js
 @ ./~/puppeteer/lib/Puppeteer.js
 @ ./~/puppeteer/index.js
 @ ../AppModules/VOC/Admin/js/VOCContainer.jsx
 @ ../routes/Admin/app-routes.jsx
 @ ../Common/components/Admin/adminEntry.jsx

ERROR in ./~/mime/mime.js
Module not found: Error: Can't resolve 'fs' in 'C:\peerinsights\ui\home_admin\node_modules\mime'
 @ ./~/mime/mime.js 2:9-22
 @ ./~/puppeteer/lib/Page.js
 @ ./~/puppeteer/lib/api.js
 @ ./~/puppeteer/index.js
 @ ../AppModules/VOC/Admin/js/VOCContainer.jsx
 @ ../routes/Admin/app-routes.jsx
 @ ../Common/components/Admin/adminEntry.jsx

Any help is much appreciated.

**Comment by sunnyYanan** [comment]
> @prasadmadv so it looks like you're trying to bundle puppeteer to use in a web application.
> 
> Tip-of-tree Puppeteer is much more bundling-friendly and includes the `browser` field in its package.json that should help with bundling:
> 
> [puppeteer/package.json](https://github.com/GoogleChrome/puppeteer/blob/5ebfe1a0dc89f88d3c784e546c34cae42cf9906c/package.json#L62-L70)
> 
> Lines 62 to 70 in [5ebfe1a](/GoogleChrome/puppeteer/commit/5ebfe1a0dc89f88d3c784e546c34cae42cf9906c)
> 
>  "browser": { 
>    "./lib/BrowserFetcher.js": false, 
>    "./node6/lib/Puppeteer": false, 
>    "ws": "./utils/browser/WebSocket", 
>    "fs": false, 
>    "child_process": false, 
>    "rimraf": false, 
>    "readline": false 
>  } 
> This will be released later today as Puppeteer v1.9.0

why I can't find util folder for the ws setting in the package.json? when i remove it locally, it's okay

**Comment by manicolas2** [comment]
I'm still having this error. Can someone help me?

![Screenshot from 2019-04-10 16-48-16](https://user-images.githubusercontent.com/35553960/55865223-81b4eb00-5bb0-11e9-8c3d-c1490c5f0687.png)

**Comment by ryantoussaint** [comment]
I was able to resolve this by adding `externals: ["puppeteer"]` to my `webpack.config.js`

**Comment by chelseaohara** [comment]
> 
> 
> I was able to resolve this by adding `externals: ["puppeteer"]` to my `webpack.config.js`

@ryantoussaint where did you add this to your webpack.config.js? I am either getting compile errors or no difference in the same ws error mentioned above

**Comment by ryantoussaint** [comment]
top level of the config - https://webpack.js.org/configuration/externals/

**Comment by MarchWorks** [comment]
any news on how to solve this
```
Failed to compile.
./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Can't resolve 'ws' in '/frontend/node_modules/puppeteer/lib'
```

**Comment by Zaraf11** [comment]
change line 16 in WebSocketTransport.js to
 const WebSocket = require('../node_modules/ws');
Hopefullt it will fix the error

**Comment by boblamceo** [comment]
I don't have webpack.config.js

**Comment by boblamceo** [comment]
I also don't have WebSocketTransport.js

**Comment by ariel262626** [comment]
Same issue here 
Module not found: Can't resolve '../node_modules/ws' in ..../node_modules/puppeteer/lib'

**Comment by macorifice** [comment]
Same issue here
Module not found: Can't resolve 'ws' in '/Users/..../puppeteer/lib'

**Comment by alphoenix-fx** [comment]
How I fixed it. You need to create server.js for your puppeteer code and read your results in the client/react-app.
https://stackoverflow.com/questions/55031823/how-to-make-puppeteer-work-with-a-reactjs-application-on-the-client-side
