### ISSUE TITLE
Puppetter  fails due to node modules error on travis CI build

### ISSUE THREAD

**Issue by PendliKranthi** [puppeteer/puppeteer#3345]
My tests are working fine on my local machine but  when i want to merge my branch it's failing on Travis CI build.
> puppeteer@1.8.0 install /www/vhosts//node_modules/puppeteer
> node install.js
/www/vhosts/node_modules/puppeteer/install.js:61
    .then(() => browserFetcher.localRevisions())
           ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! puppeteer@1.8.0 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the puppeteer@1.8.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

* Puppeteer version:1.8.0
* Platform / OS version: Mac  > High Sierra
* Node.js version: v8.12.0
*npm : 6.4.1

**Comment by aslushnikov** [comment]
> /www/vhosts/node_modules/puppeteer/install.js:61

Do you do any changes to our install.js?

**Comment by PendliKranthi** [comment]
No

**Comment by PendliKranthi** [comment]
i found some similar issues like this but i didn't find any solution

https://github.com/GoogleChrome/puppeteer/issues/833

https://api.travis-ci.com/v3/job/124937719/log.txt

https://travis-ci.com/BME-MIT-IET/Hmmm-iet-2018/jobs/124938746

**Comment by PendliKranthi** [comment]
i am using typescript as language for my tests, does it relate to this issue.

**Comment by aslushnikov** [comment]
@PendliKranthi it's unclear what's going on in your case; if you can share your repository it would help.

**Comment by PendliKranthi** [comment]
I can provide my all test files but can't provide an access to the repo it's restricted

**Comment by PendliKranthi** [comment]
the repository that i am running my tests are PHP based it isn't configured node on travis.yml file do i need to include that node version in order to run the build on travis

**Comment by PendliKranthi** [comment]
![screen shot 2018-10-05 at 10 56 07 am](https://user-images.githubusercontent.com/34037164/46542794-4ea23f80-c88d-11e8-8f71-ce795bbb0daf.png)

**Comment by PendliKranthi** [comment]
The node version that is running on travis is
node v0.10.42
npm  v3.8.2
i think the issue is because of this.

**Comment by PendliKranthi** [comment]
i found the solution it's node version that is running on travis causes build failure.
