### ISSUE TITLE
handler property not available on EventListener object returned from DOMDebugger.getEventListeners

### ISSUE THREAD

**Issue by sangiiii** [puppeteer/puppeteer#3349]
While fetching the [EventListeners](https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger#type-EventListener) of a object, the handler property is not available. 

Example script:
```
client.send('DOMDebugger.getEventListeners', { objectId: <objId> ,includeCommandLineAPI: true, generatePreview: true});
```

returned object:
```
{ type: 'load',
  useCapture: false,
  passive: false,
  once: false,
  scriptId: '59',
  lineNumber: 49,
  columnNumber: 98 }
```

As per [dev-tools protocol ](https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger#type-EventListener)  , the `handler` property is optional. 
But, while executing getEventListeners on chrome dev console, the listener (handler) object is available.
<img width="1680" alt="screen shot 2018-10-03 at 3 32 11 am" src="https://user-images.githubusercontent.com/6672359/46503813-a15a0800-c849-11e8-874e-3d150bbef200.png">

**Comment by aslushnikov** [comment]
@sangiiii it all depends on the specifics of the call and its arguments. If there's a handler that DevTools protocol can fetch, i'll return it for you. Otherwise, it'll be missing.

It's hard to say for sure what's going on here unless you provide us with a good script to look at. I'll speculatively close this for now, but feel free to post here any further details if you think we can help.

**Comment by bmeck** [comment]
@sangiiii it appears to only work if you add the node to an object group (release it manually eventually):

```html
<!-- index.html -->
<div id="foo"></div>
<script>foo.addEventListener('click', console.log);</script>
```

```mjs
(async () => {
  const browser = await require('puppeteer').launch();
  const [ page ] = await browser.pages();
  await page.goto('http://127.0.0.1:8080/index.html');
  const cdp = await page.target().createCDPSession();
  const INCLUDE_FN = true;
  const { result: {objectId} } = await cdp.send('Runtime.evaluate', {
    expression: 'foo',
    objectGroup: INCLUDE_FN ?
      'provided' : // will include fn
      '' // wont include fn
  });
  const listeners = await cdp.send('DOMDebugger.getEventListeners', { objectId });
  console.dir(listeners, { depth: null });
  // ... release objectGroup eventually
})();
```

**Comment by bv-sumit** [comment]
The above solutions didnt work for latest version of puppeteer as the directory structure is changed.

https://stackoverflow.com/questions/75517220/geteventlistener-function-support-for-latest-puppeteer-versions/75581410#75581410
I have mentioned the solution in the above link. If anyone is facing the issue you can refer.
