### ISSUE TITLE
Suggestion: Launch Chrome headless in "daemon" mode

### ISSUE THREAD

**Issue by robertrossmann** [puppeteer/puppeteer#335]
It would seem from looking at the source code in _Launcher.js_ that each request is made in a separate process (correct me if I am wrong):

https://github.com/GoogleChrome/puppeteer/blob/e7356bf61199cfc0b50c991e9d876699e5a62cb6/lib/Launcher.js#L73

It would be absolutely awesome if Chrome was able to start in kind of a "daemon"/background mode, waiting for requests to render some content, without needing to start a new process for each page render.

### Why?

It could be used for server-side rendering or React-based applications. Spawning a new process for each page load request could be quite costly, but having Chrome already running and just sending a render request to it could improve performance of such setup drastically.

I am uncertain if such possbility currently even exists in Chrome, but since puppeteer is maintained by  the Chrome team I am raising the suggestion here.

Thanks!

**Comment by Garbee** [comment]
I believe some work is already going into letting you specify an already running instance. But the default and recommended setting will continue to be individual processes.

**Comment by aslushnikov** [comment]
You can connect to already-running chromium instance with the [`puppeteer.connect`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions) method.

You can start chrome in the "daemon" mode from node if you [unref child process](https://nodejs.org/api/child_process.html#child_process_options_detached).

Does this satisfy your needs?

**Comment by HugoHeneault** [comment]
Some easy-to-use setup with just some options to allow the daemon to keep running could be awesome!

Like: 
```
const browser = await puppeteer.launch({
   daemonID: 'someID',
   restartDaemonAfter: 3600
});

```

To create one (or more) instance of chromium and keep using it for a while

**Comment by Garbee** [comment]
`puppeteer.launch` is for a transnational occurrence, as in it is intended to die at some point. The `connect` method is intended to connect to an externally launched daemon to work against. It feels very strange to me if we were to introduce non-transnational needs into the `launch` method.

**Comment by aslushnikov** [comment]
Closing this, since `puppeteer.connect` addresses this.

**Comment by robertrossmann** [comment]
Indeed, thanks! it would seem that using [rendertron](https://github.com/GoogleChrome/rendertron) together with `puppeteer.connect()` would be the best fit for the described use case.
