### ISSUE TITLE
How can I implement Puppeteer in Chrome Extension with React?

### ISSUE THREAD

**Issue by ace53thntu** [puppeteer/puppeteer#3355]
I have create a Chrome Extension with React. I want to control chrome tab (e.x: click button, go to new url, wait for element visible,...) by Puppeteer. Anyone know how to do this?

**Comment by usefksa** [comment]
Hello
did u find anyway to use react with puppeteer?

**Comment by aslushnikov** [comment]
Everybody: running in Chrome Extension is a bit of a journey. I'd recommend starting [here](https://github.com/GoogleChrome/puppeteer/tree/master/utils/browser#bundling-for-web-browsers) to get a browser bundled version of Puppeteer.

**Comment by tchan** [comment]
For those revisiting this, the link above has been deleted but can be viewed from a past [commit](https://github.com/puppeteer/puppeteer/tree/6522e4f524bdbc1f1b9d040772acf862517ed507/utils/browser)

Here's the [pull request](https://github.com/puppeteer/puppeteer/pull/5750) for the reasoning.
