### ISSUE TITLE
Page.pdf does not honor width and height parameters and is missing content

### ISSUE THREAD

**Issue by alexpreynolds** [puppeteer/puppeteer#3357]
* Puppeteer version: 1.9
* Platform / OS version: ubuntu-xenial-16.04-amd64-server-20180627
* Node.js version: 6.4.1

**What steps will reproduce the problem?**

Here is code that uses `Page.pdf()` and `Page.screenshot()` to capture a single-page web application and write the browser window contents to PDF- and PNG-formatted files for comparison:

```
'use strict';

const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        args: [
            '--no-sandbox',
            '--start-maximized'
        ],
        timeout: 10000
    });
    var page = await browser.newPage();
    await page.setViewport({
        width: 1024,
        height: 1280,
        deviceScaleFactor: 1
    });
    await page.emulateMedia('screen');

    const url = 'http://higlass.io/app';
    await page.goto(url, {
        waitUntil: ['load', 'domcontentloaded', 'networkidle2', 'networkidle0']
    });

    await page.pdf({
        path: 'localPuppeteerTest.pdf',
        width: '1024px',
        height: '1280px',
        pageRanges: '1-1'
    });

    await page.screenshot({path: 'localPuppeteerTest.png', fullPage: true});

    await browser.close();
})();
```

**What is the expected result?**

The expected result is what is shown in the PNG screenshot:

![localpuppeteertestcorrect](https://user-images.githubusercontent.com/33584/46557203-fd4e7c00-c89d-11e8-8c26-41ecba80e262.png)

**What happens instead?**

While the PNG is rendered correctly, the PDF rendering appears to ignore the specified page viewport dimensions and is missing content:

![localpuppeteertestincorrect](https://user-images.githubusercontent.com/33584/46557219-08a1a780-c89e-11e8-9bad-a99a4a28002e.png)

The PNG renderer appears to respect the page viewport dimensions, and contains all content (such as the element to the right of the "HiGlass" title). 

Ideally, the PDF output should match the PNG output in respect to specified dimensions and content.

**Comment by lbittner-pdftron** [comment]
I am experiencing a similar issue.

```
    await page.pdf({
      path: `${outputFolder}/${outputName}.pdf`,
      printBackground: true,
      width: 612,
      height: 792
    })
```
produces a PDF with dimensions 458 x 594. 

Settings the size via `@page` css produces the same result. Setting the viewport to 612 x 792 also does not fix the issue.

To me it feels like the `width`, `height` and `defaultViewport` options are completely ignored.

**Comment by phuang0619** [comment]
same issue, really hope to hear a fix, a workaround or anything to this soon.

**Comment by ronalb** [comment]
i'm facing the same issue.

**Comment by plaurent** [comment]
The answer appears to be to pass the width and height to Page.pdf() command itself.

e.g.,

```
await page.pdf({ path: 'hn.pdf', printBackground: true, width: '1920px', height: '1080px'});
```

https://github.com/GoogleChrome/puppeteer/issues/570#issuecomment-326144861

**Comment by jonnypickett** [comment]
@plaurent the original post is passing the width and height to page.pdf() without passing a value for `format`. The person who submitted the issue you are referring to was passing 'A4' as the `format` and width and height values. `format` overrides width and height.

**Comment by alexpreynolds** [comment]
I suggest running the code, as described.

**Comment by pravari1** [comment]
I am facing the same issue, height and width doesn't work as though with viewport

**Comment by mksztv** [comment]
Same issue. Does anybody found a solution?

**Comment by wellingfine** [comment]
Same to me. Set width but the ouput pdf file does not fix to that width

**Comment by 0x15f** [comment]
Having the same issue.

**Comment by rjconrad** [comment]
This seems to be an issue for me as well. If there's no bandwidth to fix it, could there be a warning in the API docs to let people know that this feature may not work as advertised?

**Comment by senluchen2015** [comment]
Seems like a DPI of `96` is assumed in the conversion from px to inches here: https://github.com/puppeteer/puppeteer/blob/9923e56b3ed05cde014c0047a4f65fef7749ebb0/lib/Page.js#L1267

Whereas some machines may default to a DPI of `72` when calling the `Page.printToPDF` method here: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF. 
Perhaps a workaround for now is to scale it up before printing:

```
const pdf = await page.pdf({
    height: height / 0.75,
    width: width / 0.75,
    scale: 1 / 0.75,
    printBackground: true,
 });
```

**Comment by phuang0619** [comment]
@senluchen2015  makes so much sense and thanks for sharing this info. 
I had the same scaling to get the pixels right too, but never knew why till seeing your response.

**Comment by senlyu** [comment]
I had the same issue before, and I tried @senluchen2015 his code and solved this.

However, suddenly it no longer worked
My env is: 
docker: node-10-slim(debian 9)
puppeteer: 5.50(latest)
chrome: 87.0.4280.66-1(latest)

All I know is that this related to chrome version, I tried an older version of chrome, eg: '81.0.4044.113-1'. Then it worked.

**Comment by norahmaria** [comment]
> Seems like a DPI of `96` is assumed in the conversion from px to inches here:
> 
> https://github.com/puppeteer/puppeteer/blob/9923e56b3ed05cde014c0047a4f65fef7749ebb0/lib/Page.js#L1267
> 
> Whereas some machines may default to a DPI of `72` when calling the `Page.printToPDF` method here: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF. Perhaps a workaround for now is to scale it up before printing:
> 
> ```
> const pdf = await page.pdf({
>     height: height / 0.75,
>     width: width / 0.75,
>     scale: 1 / 0.75,
>     printBackground: true,
>  });
> ```

@senluchen2015 what is the `0.75` referring to in this case? For me the PDF turns out as expected when I set it to `0.65`, and I assume it depends on the DPI, but wondering the math used to _find_ this number? Or is it just something you need to eyeball? ☺️

**Comment by techsavvyash** [comment]
> > Seems like a DPI of `96` is assumed in the conversion from px to inches here:
> > https://github.com/puppeteer/puppeteer/blob/9923e56b3ed05cde014c0047a4f65fef7749ebb0/lib/Page.js#L1267
> > 
> > Whereas some machines may default to a DPI of `72` when calling the `Page.printToPDF` method here: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF. Perhaps a workaround for now is to scale it up before printing:
> > ```
> > const pdf = await page.pdf({
> >     height: height / 0.75,
> >     width: width / 0.75,
> >     scale: 1 / 0.75,
> >     printBackground: true,
> >  });
> > ```
> 
> @senluchen2015 what is the `0.75` referring to in this case? For me the PDF turns out as expected when I set it to `0.65`, and I assume it depends on the DPI, but wondering the math used to _find_ this number? Or is it just something you need to eyeball? relaxed

I believe `0.75` comes from `72/96` which is the intended DPI divided by the one assumed in the code.

**Comment by rotimi-best** [comment]
For me I had to remove the format key and leave the width and height

```js
await page.pdf({
  // format: 'A4', // Removed this and it worked.
  width: '1123px',
  height: '794px',
});
```
