### ISSUE TITLE
Finding frames

### ISSUE THREAD

**Issue by kiorq** [puppeteer/puppeteer#3358]
I created a function that will wait for a frame to appear on the page before trying to get it and return it.
But for some reason, about 1/8 times the function returns undefined. How is this possible? since the waitFor would have blown up if it didn't find anything.

```js
const _find_frame = async (page, { frame_name }) => {
    await page.waitFor("frame[name=" + frame_name + "]", { timeout: 30000 });
    const frames = await page.frames();
    return frames.find(f => f.name() === frame_name);
};
```

Thank you.

**Comment by vsemozhetbyt** [comment]
[frame.name()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#framename):
> NOTE This value is calculated once when the frame is created, and will not update if the attribute is changed later.

Could there be a race condition? Say, a frame empty name is caught in creation, then it changes dynamically before or after `page.waitFor()` starts polling, and we have a discrepancy.

**Comment by kiorq** [comment]
It could be, i saw the note, but i thought this would happen after the first time calling the page.frames(), which i thought wouldn't be a problem if the waitfor succeeded.
But that's okay I'll use a promise race, as an alternative, with doing a waitfor in each of the frames.

**Comment by aslushnikov** [comment]
> It could be, i saw the note, but i thought this would happen after the first time calling the page.frames(), which i thought wouldn't be a problem if the waitfor succeeded.

The value is computed by Chromium internally and has nothing to do with the `page.frames()` call.

> But that's okay I'll use a promise race, as an alternative, with doing a waitfor in each of the frames.

I'd just rely on the `waitFor` call - if it succeeds, than you have the right frame in hands.
