### ISSUE TITLE
Feature: Allow class methods or actions

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#3359]
## Origin
NightmareJS has a very good [action](https://github.com/segmentio/nightmare#nightmareactionname-electronactionelectronnamespace-actionnamespace) and [plugin](https://github.com/segmentio/nightmare#useplugin) system which allows anyone to extend the nightmare instance and provide additional actions. 

Example of `action`:
```js
Nightmare.action('clearCache', /* rest of the code to use and modify the child actions */)

// later on the code
nightmare.clearCache().goto()
```

## How it can help with puppeteer
Consider these issues where people asked for synthetic suger for various custom actions.
- https://github.com/GoogleChrome/puppeteer/issues/3260, Provide a simpler method of getting innerHTML and innerText
- https://github.com/GoogleChrome/puppeteer/issues/2854, Feature Request: clearer UX for waitForSelector inverse.
- https://github.com/GoogleChrome/puppeteer/issues/1757, Better Xpath.
- https://github.com/GoogleChrome/puppeteer/issues/1394, page.collectGarbage()

And so on.

## Proposal

Either of following should be a good starting point, 
- Expose a method to extend the classes like `Page`, `Frame`, `Browser`. 
- Expose the classes themselves somehow, just like `puppeteer-core`

## Workaround
Right now I am experimenting a silly hack for the prototype which works perfectly well for now. If you can show me right direction, I can do the PR. But I need to know if this is a good idea or not. 

The following way also makes sure we can use `page` as this and no need to pass `page` to the function, so code can be moduler and easier to maintain.

```js
const puppeteer = require("puppeteer");

// Simple hack to add methods to the constructor prototype
// Allows multiple functions to be included
async function addMethods(targetClass, functionList) {
  for (oneFunction of functionList) {
    if (["undefined", "anonymous"].includes(oneFunction.name)) {
      throw new Error("Nameless functions are not supported");
    }
    targetClass.prototype[oneFunction.name] = oneFunction;
  }
  return targetClass;
}

// Our extra methods that has access to the page instance
const extraFunctions = [
  // just some simple functions to get title and url
  async function data() {
    return { title: await this.title(), url: await this.url() };
  },

  // synthetic suger for innerText as asked
  async function innerText(selector) {
    return this.$eval(selector, e => e.innerText);
  },

  // synthetic suger for innerHTML as asked
  async function innerHTML(selector) {
    return this.$eval(selector, e => e.innerHTML);
  },

  // More examples
  async function outerHTML(selector) {
    return this.$eval(selector, e => e.outerHTML);
  }
];

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  addMethods(page.constructor, extraFunctions); // Add new methods to Page class, it's available to modify at this point

  await page.goto("http://example.com");

  // Use our new method
  console.log({
    collectedData: await page.data(),
    innerText: await page.innerText("h1"),
    innerHTML: await page.innerHTML("h1"),
    outerHTML: await page.outerHTML("h1"),
  });
  /**
   * Result:
   * { collectedData: { title: 'Example Domain', url: 'http://example.com/' },
   * innerText: 'Example Domain',
   * innerHTML: 'Example Domain',
   * outerHTML: '<h1>Example Domain</h1>' }
   */
  await browser.close();
});
```

That's all for now.

**Comment by aslushnikov** [comment]
@entrptaher the easiest way to extend `Page`, `Browser` and others is like this:

```js
const {Page} = require('puppeteer/lib/Page');
Page.prototype.fooMethod = function() {
  // ... do stuff with "this" ...
}
```

An alternative and safer way to create convenience methods for Puppeteer is through helper functions, e.g.

```js
function fooMethod(page) {
  // ... do stuff with "page" ....
}
```

So far these approaches satisfy all our clients interested in extensibility story. We might come up with something more organized / official once there's more demand.

Hope this helps!

**Comment by lai32290** [comment]
Is the `Page.prototype` method a good practice to do?
