### ISSUE TITLE
What about proxy usage?

### ISSUE THREAD

**Issue by Insolita** [puppeteer/puppeteer#336]
Is it possible to setup proxy for request or for user_profile

**Comment by Garbee** [comment]
You'd provide the proxy as an argument when [launching](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) the instance.

```js
let instance = puppeteer.launch({
  args: [
   '--proxy-server=127.0.0.1:9876', // Or whatever the address is 
  ]
});
```

**Comment by entrptaher** [comment]
This should be added on the docs. 

EDIT: 
This should be added on docs with basic proxy usage and proxy with authentication too.
Normally, one can auth using `webRequest.onAuthRequired` event.
Better if there is a better api to do this in puppeteer.

**Comment by aslushnikov** [comment]
Indeed, puppeteer lacks support for http auth. We should add it!

**Comment by entrptaher** [comment]
On nightmareJS. You can auth using 
```
.authentication(user, password)
```

On CasperJS, you can use, 
```
{
    proxy: "127.0.0.1:1234",
    proxy-auth: "userx:passx",
    proxy-type: "meh"
}
```

If puppeteer adds easier and proper proxy handling (+multithreading etc etc features, but it's not the issue for that), im sure it can easily beat chromeless, nightmarejs and others.

We should look into this matter.

**Comment by aslushnikov** [comment]
> This should be added on the docs.

Addressing in https://github.com/GoogleChrome/puppeteer/pull/427

Authentication will be handled with #426

**Comment by blairanderson** [comment]
how about with a proxy user/password? I do not see documentation for that

**Comment by entrptaher** [comment]
@blairanderson check this, https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageauthenticatecredentials

**Comment by Garbee** [comment]
@blairanderson For a proxy gateway to the internet, you would add the username and password just like any other URI. `user:pass@127.0.0.1:9090` for example. Nothing special to Puppeteer about it, just a normal URI.

**Comment by ptandDev** [comment]
Hi, can you help me? I do not have any sites open if I use a proxy. Code:
let browser = await puppeteer.launch ({
                 headless: false,
                 // executablePath: 'C: \\ Program Files (x86) \\ Google \\ Chrome \\ Application \\ chrome.exe',
                 args: ['--proxy-server = 85.26.146.169: 80']
             });
Without a proxy, everything works fine. What am I doing wrong?

**Comment by Garbee** [comment]
> Without a proxy, everything works fine. What am I doing wrong?

Sounds like something is wrong with your proxy then.

**Comment by ptandDev** [comment]
I tried different proxy from the list http://free-proxy.cz/en/proxylist/country/ru/all/ping/all Are there any restrictions? Protocol, for example, or where can I read about it? I definitely do not understand something.

**Comment by blairanderson** [comment]
i was able to get a proxy working with:

```javascript
  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true,
    args: [
      "--proxy-server=proxy.example.com:8010",
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ]
  });
```

**Comment by ptandDev** [comment]
Thanks, but it did not help.

**Comment by blairanderson** [comment]
Keep trying. Good luck. 👍🍀

**Comment by ptandDev** [comment]
Well guys, I figured this out works "--proxy-server = socks4: //85.142.251.28: 1080", maybe someone will help.

**Comment by softmantk** [comment]
I have a similar issue. I am using puppeeter for a social media automation. I have to store the sessionId, csrf, mid . So that next time I open the website I don't have to log in again. So, the logic works perfectly without proxy. But When I use puppeteer with a proxy, it doesn't seem to be working. It is redirecting to the login page. I think it is not an issue with the proxy I am using.

**Comment by blairanderson** [comment]
Sorry, github is not the place for your request comment.

**Comment by softmantk** [comment]
@blairanderson , Sorry i didn't get you. What is wrong with my comment?

**Comment by blairanderson** [comment]
Because its specifically for the development of the project code-base.

You're better off asking
https://stackoverflow.com/questions/tagged/puppeteer

**Comment by softmantk** [comment]
oh ok. Sorry about my comments. 😟

**Comment by FranklinYu** [comment]
@aslushnikov Would it be welcomed as PR if I add an option to `puppeteer.launch()` for proxy configuration? As @entrptaher said, proxy deserves a better API.

**Comment by Un1xMida** [comment]
> args: [ '--proxy-server=127.0.0.1:9876', // Or whatever the address is ]

i tried this 
const puppeteer = require('puppeteer');

(async () => {
    try {

        const browser = await puppeteer.launch({ headless: false });
        const page = await browser.newPage();
        await page.goto('http://whoer.net/', {
            args: [
                '--proxy-server=76.185.16.94:54079',
               ]
        });
    } catch (e) {
        console.log(e)
    }
})();

but it didnt work :(

**Comment by FranklinYu** [comment]
@Un1xMida The `args` is for `launch()` not for `goto()`.

**Comment by princePeterHansen** [comment]
I found it easy to use API proxy services because you don't have to search, setup and maintain list of proxy servers.

The basic example will look like this:

```javascript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const url = 'https://proxybot.io/api/......?url=https://example.com';

  await page.goto(url);
})();
```

Every page will be opened through random proxy 😉

**Comment by Cuadrix** [comment]
I made a module that does this. It's called [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy).
It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.

First install it:
```
npm i puppeteer-page-proxy
```
Then require it:
```js
const useProxy = require('puppeteer-page-proxy');
```
**Using it is easy;**
Set proxy for an entire page:
```js
await useProxy(page, 'http://127.0.0.1:8000');
```

If you want a different proxy for each request,then you can simply do this:
```js
await page.setRequestInterception(true);
page.on('request', req => {
    useProxy(req, 'socks5://127.0.0.1:9000');
});
```
Then if you want to be sure that your page's IP has changed, you can look it up;
```js
const data = await useProxy.lookup(page);
console.log(data.ip);
```
It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
```js
const proxy = 'http://login:pass@127.0.0.1:8000'
```

Repository:
https://github.com/Cuadrix/puppeteer-page-proxy
