### ISSUE TITLE
Detect finished downloads on "Page.setDownloadBehavior

### ISSUE THREAD

**Issue by marianvlad** [puppeteer/puppeteer#3360]
There is a way to detect when files are downloaded?

I use 
```js
await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: `${this.basePath}/temp/files/`});
await page.goto('http://website.com/file.mp4');
```

The problem is with page.goto. it waits until timeout and return an Exception and I don't want to wait 30 seconds every time..

Thanks!

**Comment by aslushnikov** [comment]
This'll be part of #299
