### ISSUE TITLE
Map nodelist works, but filter dosen't

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#3361]
const puppeteer = require('puppeteer');

async function run() {
	const browser = await puppeteer.launch(),
		page = await browser.newPage();
    await page.goto('https://example.com/');
	const mapped = await page.$$eval('p', nodes => nodes.map(n => n.innerText)); //works
	const filtered = await page.$$eval('p', nodes => nodes.filter(n => true)); //don't work
	console.log(mapped[1]);
	console.log(filtered[1]);
	browser.close();
}
run();

**Comment by nicoandmee** [comment]
And you can run this in devtools without any issue? What is the expected output? You are filtering WebElement handles (right...?) and trying to filter on a non-existent property.

**Comment by ghun** [comment]
This works in devtools:

Array.from(document.querySelectorAll('p')).filter(n => true)   //(2) [p, p]

**Comment by ghost** [comment]
This works in devtools:
Array.from(document.querySelectorAll('p')).filter(n => true)  //(2) [p, p]

I was expecting page.$$eval to do the same thing. I am using 'true' to return everything for now.

**Comment by vsemozhetbyt** [comment]
The cause seems to be this: in the first case, the function returns an array of strings which is serializable; in the second case,  the function returns an array of HTML elements which is not serializable.

**Comment by ghost** [comment]
Ok, got it. Can you point me in the right direction how to select and filter HTML elements? Because page.$$(selector) which returns <Promise<Array<ElementHandle>>> does not accept a function. Or would that be a good pull request?

**Comment by vsemozhetbyt** [comment]
Maybe you can try [`page.evaluateHandle()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatehandlepagefunction-args) to save a handle for filtered arrray of elements:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const linksHandle = await page.evaluateHandle(
      () => [...document.querySelectorAll('*')].filter(({ href }) => href)
    );
    const hrefs = await page.evaluate(
      links => links.map(({ href }) => href), linksHandle
    );
    console.log(hrefs);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
[ 'http://www.iana.org/domains/example' ]
```

**Comment by ghost** [comment]
Ok, will do for now. Thanks.
