### ISSUE TITLE
I can't manage to get document object!

### ISSUE THREAD

**Issue by TheOnlyArtz** [puppeteer/puppeteer#3362]
I got this code 
```js
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch()
	const page = await browser.newPage();
	await page.goto('https://mysite/login');
	const input = await page.evaluate(() => {return document});
	console.log(input)
	await browser.close();
})()
```
input returns undefined

**Comment by nicoandmee** [comment]
i guess...
`new XMLSerializer().serializeToString(document.doctype) + document.documentElement.outerHTML;
`

**Comment by vsemozhetbyt** [comment]
It seems this is [the cause](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args):

> If the function passed to the `page.evaluate` returns a non-[Serializable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description) value, then `page.evaluate` resolves to `undefined`.

**Comment by ghost** [comment]
Okay so do you get the document object?
