### ISSUE TITLE
Cannot open chromium in application mode

### ISSUE THREAD

**Issue by zlfnhmd** [puppeteer/puppeteer#3366]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-core:1.8.0
* Platform / OS version: WinX64
* URLs (if applicable):
* Node.js version: 8.12.0

**What steps will reproduce the problem?**
launching puppeteer with option args:['--app'] does not open a headfull browser in application mode.
_Please include code that reproduces the issue._

const browser = await puppeteer.launch({
        args:['--app'],
        executablePath: chromePath,
        headless: false,
        defaultViewport: null
    });

**What is the expected result?**

Open a headfull browser in application mode

**What happens instead?**
Open a headfull browser but in normal mode.

**Comment by aslushnikov** [comment]
@zlfnhmd Somehow [carlo](https://github.com/GoogleChromeLabs/carlo) successfully does it - i'd recommend checking their code for the reference.

**Comment by calebeby** [comment]
In case it is helpful for anyone, [here](https://github.com/GoogleChromeLabs/carlo/blob/3e883bcb3d1ad73e18ce8dd1621e53013b9e3a52/lib/carlo.js#L607) is how carlo handled it
