### ISSUE TITLE
screenshot spend too much time

### ISSUE THREAD

**Issue by milu2003** [puppeteer/puppeteer#3367]
**Tell us about your environment:**

* Puppeteer version:1.7.0
* Platform / OS version: mac
* URLs (if applicable): 
* Node.js version:8.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
console.time('screenshot');
page.screenshot({path: 'news.png', fullPage: true});		
console.timeEnd('screenshot');
page.close()
```

The size of the generated image is about 3.4 MB

**What is the expected result?**

Faster speed

**What happens instead?**

Spend time:18286.718ms

**Comment by ChristianDavis** [comment]
Puppeteer calls the devtools-protocol for the screenshot, https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot . Seems like this is very dependent on your machine specs and how large the page is. If you are running with chromium and think it's an issue with the library, I think you should probably file an issue with chromium https://github.com/chromium/chromium

**Comment by milu2003** [comment]
@ChristianDavis ok
