### ISSUE TITLE
Puppeteer prevents the process from exiting gracefully via SIGINT handler

### ISSUE THREAD

**Issue by VioletGiraffe** [puppeteer/puppeteer#3368]
I'm not even sure what Puppeteer does to cause this. All the following tests are run on Windows 10 x64.
Here's the simple implementation of graceful exit that I devised, along with a sample test function.

```
const puppeteer = require("puppeteer");

var terminate = false;
var terminated = false;

async function sleep (timeout) {
	return new Promise((resolve) => {
	  setTimeout(() => {
		  console.log("Timeout! " + timeout + " ms");
		  resolve();
		}, timeout)
	})
}

process.on('SIGINT', async function () {
	console.log('Got SIGINT');
	terminate = true;
	while (!terminated) {
		console.log('Waiting another 50 ms for the main function to exit...');
		await sleep(50);
	}
	console.log('Terminated.');
});

(async () => {
       //const browserInstance = await puppeteer.launch();
	while(!terminate) {
		await sleep(500);
	}

	console.log("Exiting gracefully.")
	terminated = true;
})();
```

It works: I run `node test.js` and I see it looping through the main loop, then I press Ctrl+C and I see the main function exiting gracefully:
```
Looping...
Got SIGINT
Waiting for another 333 ms for the main function to exit...
Timeout! 333 ms
Waiting for another 333 ms for the main function to exit...
Timeout! 1000 ms
All done, exiting gracefully.
Timeout! 333 ms
Main function exited gracefully.
Process exited gracefully.
```

But if I un-comment creation of the browser instance, it no longer works:

```
Looping...
Got SIGINT
Waiting for another 333 ms for the main function to exit...
<application exists abruptly>
```

So, it means I cannot exit my application gracefully, and that's bad because I'm writing to database and risk corrupting data. Any advice on how to fix the problem or work around it?

**Environment**:
Windows 10 x64
Puppeteer v 1.9.0, Chromium: bundled
Node v8.11.4

**Comment by VioletGiraffe** [comment]
Not a bug. This can be negated by using the `handleSIGINT` puppeteer launch option as per [the docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions).

**Comment by kobyzskyi** [comment]
New link to [documentation](https://pptr.dev/api/puppeteer.launchoptions.handlesigint)
