### ISSUE TITLE
Xvfb + puppeteer (linux 16.04)

### ISSUE THREAD

**Issue by mranosa** [puppeteer/puppeteer#3370]
Hello! Has anyone worked with running chrome (non headless, not chromium) and Xvfb on ubuntu 16.04?

I cant seem to make mine work, and am having a hard time figuring out why.

cocmand that I do in console is this `xvfb-run -a --server-args=":44 -listen tcp -ac -screen 0 1920x1080x24" node index.js`. code inside index.js has ffmpeg command to record the whole user browser experience (automated via puppeteer).

But from the error I am getting `(node:9246) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!` looks like its not even reaching the ffmpeg command and puppeteer is not launching google-chrome.

Thanks in advance to anyone who can point me in the right direction for this problem. Cheers!

Sorry I am about to lose all my hair aha

**Comment by mranosa** [comment]
done :dancing_men:

**Comment by MrZaghar** [comment]
> done 👯‍♂️

how ?
