### ISSUE TITLE
Resize event is triggered during elementHandle.screenshot

### ISSUE THREAD

**Issue by aczekajski** [puppeteer/puppeteer#3371]
### Steps to reproduce

**Environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: Windows 10 Pro
* Node.js version: 8.9.3

**Steps:**

Puppeteer script is a very simple one. Important thing is that I'm taking screenshot of an element, not page:
```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
// following is to see what is logged inside chromium
page.on('console', (msg) => {
   for (let i = 0; i < msg.args().length; ++i) {
      const line = msg.args()[i];
      console.log(`Log ${i}: ${line}`);
   }
});
// actual scenario
await page.goto('http://localhost:8080/');
const el = await page.$('#foo');
await el.screenshot({ path: 's1.png' });
await page.waitFor(1000);
await el.screenshot({ path: 's2.png' });
```

The page that is being served at the given address contains the folowing:
* element with `id="foo"` which is very tall (eg. 3000px of height)
* script which logs the resizes: `window.addEventListener('resize', () => { console.log('RESIZED'); });`

**What is the expected result?**

Puppeteer script should take two identical screenshots of an element as it was loaded. No resize should be triggered.

**What happens instead?**

With every `.screenshot()`, the `resize` event is being triggered and the `RESIZED` string is being logged to the console.

In my original scenario, the resize event caused some nested element to disappear and perform css fade-in animation to avoid visual glitches. In result, on all screenshots, regardless of how many I've taken and regardless of `page.waitFor`, the element was invisible or captured in the middle of fade-in animation. There is no possibility to wait for anything since the resize is triggered during the `elementHandle.screenshot` method.

**Known workaround**
If I set the arbitrarily big height using `page.setViewPort` so the viewport is taller than the `#foo` element, the resize is not being triggered during `elementHandle.screenshot` execution.

**Comment by songxiaocheng** [comment]
I have the same problem in `page.screenshot` for puppeteer version 8.0.0 on macOS. For me, it happens most of the time but not all.

**Comment by yatch999** [comment]
Me too, same puppeteer version 8.0.0 on macOS.  Both page and elementHandle made Reload with .screenshot.  I try to make any ideas (Stop reload, Loading Cache, use boundingBox...) but I cannot get expected screenshots.
