### ISSUE TITLE
Running multiple instances of puppeteer while having both user-data-directory and profile-directory defined

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#3373]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.6.2
* Platform / OS version: MacOS High Sierra 10.13.6
* URLs (if applicable): n/a
* Node.js version: v8.2.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

// payload.settings.chromeProfile = `default` || `Profile 1`
// payload.settings.chromeDir = `/Users/userName/Library/Application Support/Google/Chrome/`

let appConfig = {
  width: 960,
  height: 900,
  deviceScaleFactor: 1
};

let args = {
  args: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-infobars',
    '--window-position=0,0',
    '--ignore-certifcate-errors',
    '--ignore-certifcate-errors-spki-list'
  ]
};

let userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36';

args.headless = false;

// assign chrome profile path
// enable sync with account
let specialArgs = [`--profile-directory=${payload.settings.chromeProfile}`, '--enable-sync'];

// ignore default flags
args.ignoreDefaultArgs = [
  '--password-store=basic',
  '--enable-automation',
  '--disable-sync',
  '--safebrowsing-disable-auto-update',
  '--disable-background-networking'
];
args.args.push(...specialArgs);

args.executablePath = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
args.userDataDir = payload.settings.chromeDir ? payload.settings.chromeDir : null;

(async () => {
  try {
    const browser = await puppeteer.launch(args);
    const page = await browser.newPage();
    await page.setViewport(appConfig);
    await page.setUserAgent(userAgent);
    
    await page.goto('https://www.google.com/', {
      waitUntil: 'networkidle2'
    });

   // run actions...
  } catch (error) {
    console.log(error);
    await browser.close();
  }
}

```

**What is the expected result?**

I should be able to launch each new instance of a browser with it's defined profile intact and have it execute its defined actions without messing up the other browser instances.

**What happens instead?**

The following ends up happening:

1. Execute the first instance of puppeteer with a profile defined.
2. While the first instance is running, I execute another instance with either the same or new profile.
3. The second browser pops up with the correct profile, but only opens a new blank page and stops running any additional actions.
4. Once the new blank page opens on the second browser, the first browser re-runs the actions again.

I've tested this without setting any profile-directory path and it works correctly.

**Comment by connorjclark** [comment]
@xerxesj Why did you close this - did you find a solution? I'm coming across the same issue now.

**Comment by nigzht** [comment]
same here. can someone point me to where i can experiment with this? is this an upstream chrome issue?

**Comment by m1m6** [comment]
Same here

**Comment by ssut** [comment]
same here.

**Comment by ghost** [comment]
same here @xerxesj

**Comment by benjimin** [comment]
Is this related to the chrome launcher returning immediately (opening an extra tab rather than starting a separate window) when the account already has a session open?

**Comment by rinogo** [comment]
Ditto. Why was this closed? Any ideas from the community? I'm think it might have something to do with using tabs vs. windows. I think we might only be able to actively process the active tab. My code seems to be opening separate tabs which may be part of the problem...

**Comment by rinogo** [comment]
Actually, I think the solution might be to use [`launchServer()` and `.wsEndpoint()`](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=browsertypelaunchserveroptions) to get the endpoint, then connect to it from the other process using `browser.connect()`. Example from the docs:

```
const { chromium } = require('playwright');  // Or 'webkit' or 'firefox'.

(async () => {
  const browserServer = await chromium.launchServer();
  const wsEndpoint = browserServer.wsEndpoint();
  // Use web socket endpoint later to establish a connection.
  const browser = await chromium.connect({ wsEndpoint });
  // Close browser instance.
  await browserServer.close();
})();
```

**Comment by rinogo** [comment]
Hmm. Not sure if that helps because `.wsEndpoint()` is only available on `browserServer`, not `browser`.

Related: https://github.com/microsoft/playwright/issues/2995

**Comment by Coinners** [comment]
Same here, please reopen this issue!

**Comment by harimayco** [comment]
Same here with latest version of puppeteer, still can’t find the right solution for this. 😌
