### ISSUE TITLE
Where can we obtain headless builds conforming to a Puppeteer release?

### ISSUE THREAD

**Issue by JohnTJohnston** [puppeteer/puppeteer#3375]
Posting this after running into Issue #3230.

We are aware of commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/xxxxx/.

We extracted and tried a couple of these on AWS, but they would not run due to dependencies on libs associated with GUI.

Does Puppeteer (or anyone else) maintain paired true headless builds?

Thanks in advance for your assistance!

**Comment by aslushnikov** [comment]
@JohnTJohnston there's a [headless shell](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md) which is basically chrome without headful mode, but I'd guess it still requires some of the dependencies installed. The "headless shell" still can be downloaded from the commondatastorage.googleapis.com.

We personally don't run any Chrome Headless instances on AWS so we don't have much experience here, but I've seen quite a few folks on the internet that do it successfully.

Hope it helps
