### ISSUE TITLE
PDF generation creating links for website names

### ISSUE THREAD

**Issue by n-sharvarish** [puppeteer/puppeteer#3378]
* Puppeteer version: 1.8.0
* Platform / OS version: Windows/ Cent OS
* URLs (if applicable): N/A
* Node.js version: 10.11.0

**steps will reproduce the problem**
```
<html>
<head>Head Title</head>
<body>
<br/>
<span>www.totallystupid.com</span>
</body>
</html>
```

```
'use strict';
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'});
  const page = await browser.newPage();
  await page.goto('file:///C:/Users/test/Downloads/test.html', {waitUntil: 'networkidle2'});
  
  // page.pdf() is currently supported only in headless mode.
  // @see https://bugs.chromium.org/p/chromium/issues/detail?id=753118
  
  await page.pdf({
    path: 'test.html.pdf',
    format: 'letter'
  });

  await browser.close();
})();
```

**What is the expected result?**
It should not links for www.totallystupid.com when a PDF is created.

**What happens instead?**
It creates links for www.totallystupid.com when a PDF is created.

**Comment by aslushnikov** [comment]
This automatic linkification is an upstream feature; I agree it'd be nice to disable it.
Please file an upstream bug to https://crbug.com/new so that this is fixed in Chromium.

**Comment by tkdchamp** [comment]
This is not a Chromium bug, but a "feature" of your PDF reader.

Find it in Adobe by going to Edit->Preferences->General and you'll see the 2nd option is "Create links from URLs"

If you switch that off, then you'll no longer see the links being "generated".
