### ISSUE TITLE
How to wait until all images completed loading?

### ISSUE THREAD

**Issue by petehouston** [puppeteer/puppeteer#338]
I'm trying to take a full-page screenshot for a website, that contains lots of images. I write below scripts:

```js
const puppeteer = require('puppeteer');

(async() => {
	const browser = await puppeteer.launch();

	const page = await browser.newPage();

	await page.goto('https://blog.petehouston.com', {
		waitUntil: 'networkidle'
	});

	await page.waitForSelector('img');

	await page.screenshot({
		path: 'capture.jpg',
		fullPage: true
	});

	browser.close();
})();
```

However, the result screenshot `capture.jpg` shows that puppeteer hasn't completed loading all images on the site.

Is there any way to wait for all images `img` completed loading?

**Comment by Garbee** [comment]
They are downloaded. But they are lazily shown as the viewport is scrolled into position. So you'd need to scroll the page (ref #305 for that information) to get the images to get shown by the page itself.

You can turn headless off (headless property on the options for `launch()`) to see what is happening and turn off the browser close to keep it open for manual inspection.

**Comment by ks07** [comment]
As the title stands I agree that this is a feature request. However, surely this is a bug in the full page screenshot functionality if it captures elements before they have been rendered by the browser?

**Comment by Garbee** [comment]
> However, surely this is a bug in the full page screenshot functionality if it captures elements before they have been rendered by the browser?

There is no "bug". The browser is doing exactly what it is told to do by the page. Then the screenshot is being taken without taking into account lazy loading. Since the page is looking for a *scroll* of the images into view before rendering them. So, if you don't scroll before taking the screenshot, they don't render.

IMO this is actually working exactly as intended since it is taking a screenshot of the page in its current state as requested.

**Comment by linpekka** [comment]
I also ran into this, adding a scroll evalution as suggested in #305 did not help at all. Im open for other ideas, but it seems like an event when lazy render is done would be sweet, or even better, an option on screenshot to w8 for lazy render.

´page.evaluate(_ => {
  window.scrollBy(0, window.innerHeight);
});
´

**Comment by Sinequanonh** [comment]
Some lazy contents only appear after a few seconds with no scroll down. It'd be nice to have an option to wait for x seconds before taking the screenshot

**Comment by jwillingham789** [comment]
@Sinequanonh 

```
const puppeteer = require('puppeteer');

async function timeout(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('url');
    await timeout(5000);
    await page.screenshot({
	path: 'example.jpg',
	fullPage: true
    });
    browser.close();
})();
```

You can add a timeout just after going to the page if you want to wait a set amount of time before taking the screenshot

**Comment by shunwen** [comment]
I apply both `scroll` and `timeout` to solve my problem; otherwise, my lengthy pages are still not captured correctly:

````
    await page.evaluate(() => {
      window.scrollBy(0, window.innerHeight);
    })
    await timeout(5000)
````

**Comment by jacobACN** [comment]
Is there no way of doing this without a set timeout? If it takes 1 s to display the image, then this takes 4 s longer than necessary.

**Comment by Worie** [comment]
I'm struggling with it for few days, too. 
I manually set the html content, css and js and I didn't find a good way to capture the moment when all assets are loaded - `page.waitForNavigation` seems to be working only for real navigating between pages. The only thing that somehow works is `await page.waitFor(10000);` which is far from optimal :/

**Comment by jacobACN** [comment]
I ended up with the following:
```
const html = <html> All the html here </html>
const page: Page = await browser.newPage();
await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' });
await page.addStyleTag({ path: stylesheet });
await page.evaluate(() => { window.scrollBy(0, window.innerHeight); })
const result = await page.pdf({ format: 'A4' });
```

This is because I have my HTML as a string variable. I still use goto() because otherwise I can't wait for the network to be idle. I also scroll to the bottom of the page to load all content.

**Comment by Worie** [comment]
Big thanks @jacobACN , I haven't thought of this!

**Comment by hanvyj** [comment]
Great solution! I'm also loading things from a string. Seems like setting the content should behave the same way to me. I just assumed networkidle0 was broken.

**Comment by omeneses** [comment]
I solved this, editing the onReady.js file located at /engine_scripts/puppet/

The final .js file looks like this:

module.exports = async (page, scenario, vp)=>{
function wait (ms) {
return new Promise(resolve => setTimeout(() => resolve(), ms));
}

  await page.goto(scenario.url, {waitUntil: 'load'});
  // Get the height of the rendered page
  const bodyHandle = await page.$('body');
  const { height } = await bodyHandle.boundingBox();
  await bodyHandle.dispose();

  // Scroll one viewport at a time, pausing to let content load
  const viewportHeight = page.viewport().height;
  let viewportIncr = 0;
  while (viewportIncr + viewportHeight < height) {
        await page.evaluate(_viewportHeight => {
                                                window.scrollBy(0, _viewportHeight);
                                               }, viewportHeight);
        await wait(2000);
        viewportIncr = viewportIncr + viewportHeight;
  }

  // Scroll back to top
  await page.evaluate(_ => {
    window.scrollTo(0, 0);
  });

  // Some extra delay to let images load
  await wait(2000);
};

I found this solution here:  https://www.screenshotbin.com/blog/handling-lazy-loaded-webpages-puppeteer .

**Comment by chenxiaochun** [comment]
This is my solution, you can try it: https://github.com/chenxiaochun/blog/issues/35

**Comment by aslushnikov** [comment]
The key take-aways from the discussion above:
- looks like [`page.goto`](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-pagegotourl-options) with `networkidle0` does the trick
- you can use `page.goto` to navigate to HTML content [using data URLs](https://github.com/GoogleChrome/puppeteer/issues/728#issuecomment-334301491). This is the workaround for https://github.com/GoogleChrome/puppeteer/issues/728
- you'd need to have some logic to scroll page and initiate lazy content loading if there's any

Hope this helps.

**Comment by jacksonkr** [comment]
> I ended up with the following:
> 
> ```
> const html = <html> All the html here </html>
> const page: Page = await browser.newPage();
> await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' });
> await page.addStyleTag({ path: stylesheet });
> await page.evaluate(() => { window.scrollBy(0, window.innerHeight); })
> const result = await page.pdf({ format: 'A4' });
> ```
> 
> This is because I have my HTML as a string variable. I still use goto() because otherwise I can't wait for the network to be idle. I also scroll to the bottom of the page to load all content.

the `{ waitUntil: 'networkidle0' }` is key, especially for a SPA situation like mine. Make note that the `domcontentloaded` option may also be a very viable (and marginally quicker) option for some of you. The reason I mention it is because you may be needing to run this inside of a `beforeEach` and you can trim down a significant amount of test-run-time with the correct option for your situation.

**Comment by locvfx** [comment]
You can use a package called Autoscroll : https://www.npmjs.com/package/puppeteer-autoscroll-down

const { scrollPageToBottom } = require('puppeteer-autoscroll-down')

//Simulate scrolling down
  let lastPosition = await scrollPageToBottom(page, {
      size: 300,
      delay: 200
  }) 
    await page.waitForTimeout(5000); //wait 5 seconds
