### ISSUE TITLE
net::ERR_BLOCKED_BY_CLIENT with chrome extension running inside Docker 

### ISSUE THREAD

**Issue by klaaz0r** [puppeteer/puppeteer#3380]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7.0
* Platform / OS version: OSX 
* URLs (if applicable):  chrome-extension://extension_id/popup/popup.html
* Node.js version: 8.11.4

**What steps will reproduce the problem?**

```
    const browser = await puppeteer.launch({
      headless: false,
      slowMo: 100,
      ignoreHTTPSErrors: true,
      ignoreDefaultArgs: true,
      dumpio: true,
      args: [
        `--disable-extensions-except=${extensionPath}`,
        `--load-extension=${extensionPath}`,
        '--no-sandbox',
        '--disable-setuid-sandbox',
      ],
    });
```
```
  spawnargs:
            [ '/app/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome',
              '--remote-debugging-port=0',
              '--user-data-dir=/tmp/puppeteer_dev_profile-4CiXr1',
              '--disable-extensions-except=/app/dist',
              '--load-extension=/app/dist',
              '--no-sandbox',
              '--disable-setuid-sandbox' ],
```
```
FROM node:8

RUN apt-get update && apt-get install -y curl xvfb libpangocairo-1.0-0 \
    libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 \
    libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0

WORKDIR /app

COPY package.json /app
RUN yarn install

COPY . /app

ENV DISPLAY :99

CMD Xvfb :99 -screen 0 640x480x8 -nolisten tcp & yarn test 
``` 

**What is the expected result?**
The chrome extension should be loaded and tested, this works fine on OSX but not on debian/docker

**What happens instead?**

```
    net::ERR_BLOCKED_BY_CLIENT at chrome-extension://extension_id/popup/popup.html
```
Running puppeteer with xvfb and visiting other pages seems to work fine.

**Comment by xingyu-he** [comment]
I also have problem that can't load chrome extension in docker, how can it work out

**Comment by klaaz0r** [comment]
@xingyu-he what I noticed is that it gets blocked only on linux distros, will be looking into that and might need to setup proper permissions in the dockerfile to make it work

**Comment by xingyu-he** [comment]
what permissions do I need to setup? how to setup it in the dockerfile?

**Comment by ervlh** [comment]
Dockerfile
`
FROM node:10.16.0-slim
RUN  apt-get update \
     # Install latest chrome dev package, which installs the necessary libs to
     # make the bundled version of Chromium that Puppeteer installs work.
     && apt-get install -y wget --no-install-recommends \
     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
     && apt-get update \
     && apt-get install -y google-chrome-unstable --no-install-recommends \
     && rm -rf /var/lib/apt/lists/* \
     && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
     && chmod +x /usr/sbin/wait-for-it.sh

RUN npm i puppeteer \
    # Add user so we don't need --no-sandbox.
    # same layer as npm install to keep re-chowned files from using up several hundred MBs more space
    && groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /node_modules


# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# If you are building your code for production
RUN npm install 

# Bundle app source
COPY . .

# Run everything after as non-privileged user.
USER pptruser

CMD ["google-chrome-unstable"]

`

**Comment by nleib** [comment]
Hey,
is there any solution for this?

**Comment by xingyu-he** [comment]
@nleib in docker images need install xvfb and start it. you can use VNC Viewer to connect it 
`RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    software-properties-common \
    unzip \
    vim \
    xvfb \
    xauth \
    x11vnc \
    x11-utils \
    x11-xserver-utils  `

`export DISPLAY=:99
Xvfb :99 -screen 0 1366x768x16 &
x11vnc -passwd password -display :99 -N -forever &`

**Comment by al1y** [comment]
Hey, did anyone find a solution for this?

**Comment by OrKoN** [comment]
Does it still reproduce in the latest version? could you try this Dockerfile https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile
