### ISSUE TITLE
Type Error: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by mazlano27** [puppeteer/puppeteer#3381]
Hi, i'm trying to get headless chrome up and running on my node server and I get the following Type Error.

`TypeError: Cannot convert a Symbol value to a string 
at Connection.<anonymous> (/Users/Azlan_Mac/Desktop/OM_CLI/OM-CLI/node_modules/zone.js/dist/zone-node.js:1688:52)
    at new Browser (/Users/Azlan_Mac/Desktop/OM_CLI/OM-CLI/node_modules/puppeteer/lib/Browser.js:49:22)
    at Function.create (/Users/Azlan_Mac/Desktop/OM_CLI/OM-CLI/node_modules/puppeteer/lib/Browser.js:103:21)
    at Launcher.launch (/Users/Azlan_Mac/Desktop/OM_CLI/OM-CLI/node_modules/puppeteer/lib/Launcher.js:170:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I have tried running it in a new project and it works fine. However I need to use it in this project.

### Steps to reproduce

**About my environment:**
* Puppeteer version: 1.9.0
* Node.js version: 10.11.0
* SSR Angular Application served by my node server.

Initiation of puppeteer creates Type Error.

`const puppeteer = require('puppeteer');
const x = async () => {
try {
    const browser = await puppeteer.launch({
      headless: true
    });
  } catch (e) {
    console.log(e);
  }
};
x();`

My package JSON:
`
"dependencies": {
    "@angular/animations": "^6.1.9",
    "@angular/cdk": "^6.4.7",
    "@angular/cli": "^6.2.4",
    "@angular/common": "^6.1.9",
    "@angular/compiler": "^6.1.9",
    "@angular/compiler-cli": "^6.1.9",
    "@angular/core": "^6.1.9",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "^6.1.9",
    "@angular/http": "^6.1.9",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.9",
    "@angular/platform-browser-dynamic": "^6.1.9",
    "@angular/platform-server": "^6.1.9",
    "@angular/pwa": "^0.8.4",
    "@angular/router": "^6.1.9",
    "@angular/service-worker": "^6.1.9",
    "@nguniversal/module-map-ngfactory-loader": "^6.1.0",
    "@types/google.analytics": "0.0.39",
    "async": "^2.6.1",
    "bcrypt-nodejs": "0.0.3",
    "bluebird": "^3.5.2",
    "body-parser": "^1.18.3",
    "compression": "^1.7.3",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.5.4",
    "cors": "^2.8.4",
    "ejs": "^2.6.1",
    "express": "^4.16.3",
    "express-session": "^1.15.6",
    "firebase-admin": "^6.0.0",
    "firebase-tools": "^5.0.1",
    "googleapis": "^34.0.0",
    "hammerjs": "^2.0.8",
    "jsonwebtoken": "^8.3.0",
    "mongoose": "^5.3.2",
    "morgan": "^1.9.1",
    "node-schedule": "^1.3.0",
    "nodemailer": "^4.6.8",
    "path": "^0.12.7",
    "puppeteer": "^1.9.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "serve-favicon": "^2.5.0",
    "ts-loader": "^5.2.1",
    "ts-node": "^7.0.1",
    "twilio": "^3.22.0",
    "typescript": "^2.9.2",
    "webp-hero": "0.0.0-dev.12",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.8.4",
    "@angular/language-service": "^6.1.9",
    "@types/jasmine": "^2.8.9",
    "@types/jasminewd2": "^2.0.5",
    "@types/node": "^10.11.5",
    "codelyzer": "^4.5.0",
    "jasmine-core": "^3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.3.1",
    "protractor": "^5.4.1",
    "tslint": "^5.11.0",
    "webpack-cli": "^3.1.2"
  }
`

**Comment by aslushnikov** [comment]
@mazlano27 From what I see, this has nothing to do with Puppeteer per se - it's just something's going wrong between puppeteer, your server, and the angular application. There's not much else information I can use.

I don't think I can help here; if you think I still can be somehow valuable, please let me know.

**Comment by ValentinFunk** [comment]
Getting the same - not sure what the issue could be

**Comment by adrianbenjuya** [comment]
Same here. Only happens to me when NODE_ENV is set to 'production'

**Comment by ValentinFunk** [comment]
For me it happened because of Zone.js, it's trying to concatenate a symbol with a string. This fixed it for me (do this before including zone.js):

```ts
(global as any)['__Zone_disable_EventEmitter'] = true; 
```

this will disable zone for EventEmitters which is where the problem lies. I was looking into a way to prevent it without disabling all EventEmitters from zone, there is a way to blacklist them but it's kind of impossible to do it since it uses the blacklist when you include it. But you need to include it to access the blacklist (because it's stored on the Zone global). So you can't set Zone[Zone.\__symbol\__('BLACK_LISTED_EVENTS')]. To illustrate

```ts
// Require zone without EventEmitter patch
(global as any)['__Zone_disable_EventEmitter'] = true; 
require('zone.js/dist/zone-node');

// Black list puppeteer event from EventEmitter patch
const Zone = (global as any)['Zone'] as any;
Zone[Zone.__symbol__('BLACK_LISTED_EVENTS')] = [
  ...( Zone[Zone.__symbol__('BLACK_LISTED_EVENTS')] || [] ),
  require('puppeteer/lib/Connection').Connection.Events.Disconnected
];

// Now apply the patch: Sadly this isn't included in dist
(global as any)['__Zone_disable_EventEmitter'] = false; 
require('zone.js/dist/lib/node/events')
```

**Comment by ValentinFunk** [comment]
It seems you can just do this before including zone to set the blacklist:

```
global['__zone_symbol__BLACK_LISTED_EVENTS'] = [require('puppeteer/lib/Connection').Connection.Events.Disconnected]
```

**Comment by aslushnikov** [comment]
@Kamshak can you please share the code that reproduces the error? I don't quite understand how's Zone.js related to the error in this issue.
