### ISSUE TITLE
Start page numbering with a number other than 1

### ISSUE THREAD

**Issue by user9179380** [puppeteer/puppeteer#3383]
I'm working with a document set, and my first document starts for example with "Page 1" and ends on "Page 52." I want the first page in the second document in the set to start with "Page 53" because it's the next consecutive number. *Can I achieve this somehow?*

**My environment:**
* Google Chrome: 69.0 in headless mode
* Platform / OS version: Win10
* Node.js version: v8.11.3

**What I have tried:**

I'm using Headless Chrome to print out PDF files by using the printToPDF CDP method. I've tried to modify the content of `<span class="pageNumber"></span>` in a header or footer template. The [Puppeteer API documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) note that `headerTemplate` and `footerTemplate` markup have the following limitations:

1.  Script tags inside templates are not evaluated.
2.  Page styles are not visible inside templates.

However, a [GitHub comment](https://github.com/GoogleChrome/puppeteer/issues/2167#issuecomment-425448926) mentioned that we can modify template content without any `<script>` tag as the following:
```
<div style="font-size: 10px;">
  <div id="test">header test</div>
  <img src='http://www.chromium.org/_/rsrc/1438879449147/config/customLogo.gif?revision=3' onload='document.getElementById("test").style.color = "green";this.parentNode.removeChild(this);'/>
</div>
```
I was not able to get a working example of this code. For my problem, I've tried to following:
```
<img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" alt="tmpimg" 
onload="var x = document.getElementById('pn').innerHTML; var y = 10; document.getElementById('pn').innerHTML = parseInt(x) + y; this.parentNode.removeChild(this);"/>
<span id="pn" class="pageNumber"></span>
```

**What I've have expected:**

I've expected that my page number on my first page will show 10, and 11 on the second, etc.

**What happens instead:**

The JavaScript code doesn't run at all. @yale8848 mentioned in a [comment](https://github.com/GoogleChrome/puppeteer/issues/2167#issuecomment-428426715) that he has tried to use the value of `pageNumber` with JavaScript, but he has got an empty value.

I've also posted a [StackOverflow question](https://stackoverflow.com/q/52729615) about the problem. *Any ideas are welcome to resolve this issue.*

**Comment by mafredri** [comment]
This method doesn't allow you to execute JavaScript, but it does allow you to start page numbering from a different offset and should fit your use case:

The CSS:

```css
.empty-page { page-break-after: always; visibility: hidden; }
```

The JS (e.g. via eval):

```javascript
window.pageStart = {{pageCount}};
const emptyPages = Array.from({length: window.pageStart}).map(() => {
	const emptyPage = document.createElement('div');
	emptyPage.className = "empty-page";
	emptyPage.textContent = "empty";
	return emptyPage;
});
document.body.prepend(...emptyPages);
```

You'd replace `{{pageCount}}` with how many pages came before, so if you want page numbering to start at 53, pageCount = 52.

When creating the PDF, you can provide the range to skip the empty pages: `setPageRanges: (totalPageCount+1) + "-"`.

**Comment by user9179380** [comment]
@mafredri Thank you for your answer. I was also thinking about a solution like yours. My problem is that I have a large document set, and even though, the individual documents are just around 10 pages long, I have to go above 50000 with the page counter. With this solution, the browser has to render ten thousands of divs, what could cause problems. This is a lot of calculation. I test the solution to see what happens with high number of pages, and I also wait for a better workaround. 

**Edit.** I have tested this solution. It has two problems.

1. Chrome can print out PDF files only in the page range '1-32358'. It is not documented as I know, but I get this result experimentally. So the maximal value for the first page is 32358, what is not enough for me.
2. The bigger problem is that the quality of pages get worse, as the number of pages increase. It would be good to know why is it happening. I've opened [another issue](https://github.com/GoogleChrome/puppeteer/issues/3408) for this phenomenon.

**Comment by odykyi** [comment]
Hey!

use attribute **footerTemplate** with **displayHeaderFooter** for show pages originally using puppeteer API


```
await page.pdf({
  path: 'hacks.pdf',
  format: 'A4',
  displayHeaderFooter: true,
  footerTemplate: '<div><div class='pageNumber'></div> <div>/</div><div class='totalPages'></div></div>'
});
```

https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagepdfoptions

// **footerTemplate** <string> HTML template for the print footer.
// Should be valid HTML markup with following **CSS classes** used to inject printing values into them:
//  - **date** formatted print date
//  - **title** document title
//  - **url** document location
//  - **pageNumber** current page number
//  - **totalPages** total pages in the document

**Comment by dhruvarora93** [comment]
Is window.pageStart even a valid property ?
