### ISSUE TITLE
page.goto() with a certain URL throws TimeoutException when request interception is enabled, even if no request is aborted

### ISSUE THREAD

**Issue by VioletGiraffe** [puppeteer/puppeteer#3384]
I've been using this code for a while and it worked flawlessly, until today I found an URL which always fails to load with TimeoutException. Here's the test function code:

```
const puppeteer = require("puppeteer");

(async () => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.setDefaultNavigationTimeout(120000);
	await page.setRequestInterception(true);
	page.on("request", request => {
		request.continue();
	});

	try {
		const response = await page.goto("http://curious.astro.cornell.edu/the-universe/cosmology-and-the-big-bang/104-the-universe/cosmology-and-the-big-bang/expansion-of-the-universe/616-is-the-universe-expanding-faster-than-the-speed-of-light-intermediate");
		console.log("Response code: " + response.status() + (response.ok() ? " (OK)" : " (ERROR)"));
	} catch(exc) {
		console.log("Response: empty.");
	}

	await browser.close();
})();
```

When I Initially discovered this bug(?), I was using request interception to filter out images, but then I found out one does not have to abort any requests at all in order for the problem to appear. This `page.goto()` will always time out, as you can see, I even upped the timeout to 2 minutes and it made no difference. But as soon as you comment out the request interception part, it loads no problem in 7-8 seconds and reports status "200 (OK)".

**Environment**:
Windows 10 x64
Puppeteer v 1.9.0, Chromium: bundled
Node v8.11.4

**Comment by jlcd** [comment]
Same issue...
If I `await page.setRequestInterception(false);` right before some calls, it works fine, but if I leave request interception on, it doesn't load at all.
I've seen a few open issues (#3118 ; #2055 ...) regardind this exact problem and on #1159 someone said it would be fixed on 1.8.0, but I'm using 1.9.0 and this issue still persists.

`'--enable-features=NetworkService'` doesn't help at all.

**Comment by Demven** [comment]
I have the same issue with 1.9.0

**Comment by aslushnikov** [comment]
Thanks, I can reproduce.

This happens because there's currently no good way for us to match [`Network.requestIntercepted`](https://vanilla.aslushnikov.com/#Network.requestIntercepted) events with corresponding [`Network.requestWillBeSent`](https://vanilla.aslushnikov.com/#Network.requestWillBeSent) events. Currently, we use a [bunch of heuristics](https://github.com/GoogleChrome/puppeteer/blob/81edbbb58e5b572a9317928b9ca90efd8259f87a/lib/NetworkManager.js#L640-L672) to match them up, but they don't hold in this and other cases.

Once NetworkService is there, we might be able to come up with some way to straighten DevTools protocol.

**Comment by VioletGiraffe** [comment]
@aslushnikov : is there any other way than `setRequestInterception` to prevent images from loading? I mean from being downloaded, not just from being displayed (for the sake of bandwidth conservation).

**Comment by SimonSchick** [comment]
@aslushnikov can we assume that `setRequestInterception` is currently unstable and effectively unusable?

**Comment by jlcd** [comment]
@SimonSchick is it unstable? yes. is it unusable? IMO no.
Depending on what you aim to do with it, it sort of works. I had to add a couple `setRequestInterception(false)` followed by a `setRequestInterception(true)` to control whether to intercept requests I know will result in an infinite loop.
But for my main objective, reducing bandwidth by blocking images and other media, it gets the job done.

**Comment by aslushnikov** [comment]
Merging this to #3471 that's dedicated to fixing request interception once and for all. Please upvote to follow updates.
