### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch Chrome

### ISSUE THREAD

**Issue by krishpal** [puppeteer/puppeteer#3388]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: PCF
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox']});
or 
const browser = await puppeteer.launch();

**What happens instead?**
 [ERR] (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
[ERR] /home/vcap/app/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

**Comment by aslushnikov** [comment]
What's PCF?.. Other than that, it looks like you're missing required dependencies. Please take a look at [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) for the complete list.
