### ISSUE TITLE
Question: how do you build the docs at pptr.dev ?

### ISSUE THREAD

**Issue by jasonswearingen** [puppeteer/puppeteer#3389]
I really like the https://pptr.dev docs, especially how you handle versioning.  Could you please tell me how these were generated?   I would love to be able to leverage this tooling for my typescript OSS project.

I see an entry at https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md#writing-documentation explaining *how* to write docs, but not how the doc system works/building docs.

**Comment by JoelEinbinder** [comment]
The `pptr.dev` repo has the answers you want: https://github.com/GoogleChromeLabs/pptr.dev/

**Comment by jasonswearingen** [comment]
perfect, thank you.
