### ISSUE TITLE
Provide sample configurations to replicate standard browsers

### ISSUE THREAD

**Issue by ithinkihaveacat** [puppeteer/puppeteer#339]
I'm having trouble replicating, e.g., Chrome on a Pixel. I tried

```js
await page.setViewport({
  width: 1080,
  height: 1920,
  isMobile: true,
  hasTouch: true,
  deviceScaleFactor: 2
});
```

but this doesn't replicate what I actually see on a Pixel. (User agent also needs to be set.)

**Comment by ebidel** [comment]
I think this would be really handy! I usually spend 1/2 the day hunting down all these values :)

**Comment by JoelEinbinder** [comment]
If you know the values, a PR to update https://github.com/GoogleChrome/puppeteer/blob/master/DeviceDescriptors.js would be greatly appreciated.

**Comment by aslushnikov** [comment]
For the record, we have [a bunch of devices](https://github.com/GoogleChrome/puppeteer/blob/master/DeviceDescriptors.js) ready for emulation:

```js
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');
const iPhone = devices['iPhone 6'];

(async() => {
  const browser = await puppeteer.launch();
  let page = await browser.newPage();
  await page.emulate(iPhone);
  await page.goto('https://www.nytimes.com/');
  await page.screenshot({path: 'full.png', fullPage: true});
  browser.close();
})();
```

**Comment by ithinkihaveacat** [comment]
@aslushnikov Ah! I didn't notice that, that's perfect.
