### ISSUE TITLE
Feature request: REPL in puppeteer

### ISSUE THREAD

**Issue by VasylMedvid77** [puppeteer/puppeteer#3391]
Hello,

My name is Vasily and I am a beginner in test automation using puppeteer.

I suggest that puppeteer may be significantly improved by adding some kind of REPL interface which will allow much more faster and convenient way to develop and debug puppeteer tests.

**Problem:**
From the very begging I'm struggling with impossibility to quickly realize if the code is actually works against the web page under test.
It's very frustrating to run whole script again and again just to verify that you finally figured out working selector on line 155 of the script.._.And even if selectors may be tested other tools, the correct working of such things as page.screenshot() can be verified only in actual script_

**Possible solution**
It would be great to run node console, run non-headless browser from it and then feed something like 

`await page.type('[name="email"]',login)`

into and see what happens :)

I guess the whole community will benefit from ability to have quick feedback during test script development.

P.S. It cannot be only me who needs this - such project as codecept.io suggests REPL as one of three of its killer features.

**Comment by JoelEinbinder** [comment]
You can use [Chrome DevTools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27) for this. Run `node --inspect`, and debug it in Chrome. Then in the console you can do:

`let puppeteer = require('puppeteer');`
`let browser = await puppeteer.launch();`
`let page = await browser.newPage();`
etc

**Comment by aslushnikov** [comment]
Some more options:
1. Just use node's REPL to play around: type `node` in terminal, and then..
```js
pptr = require('puppeteer');
pptr.launch().then(b => global.browser = b); // to assign to global variable
browser.newPage().then(p => global.page = p);
// ... 
```
2. You can use try-puppeteer.appspot.com to play with Puppeteer.
3. (somewhat unrelated) there's [puppeteer-recorder](https://github.com/checkly/puppeteer-recorder) that helps generating puppeteer scripts; you might find it convenient.
