### ISSUE TITLE
Stream Image

### ISSUE THREAD

**Issue by j** [puppeteer/puppeteer#3392]
Is it possible to stream the screenshot directly instead of being put on the filesystem?

**Comment by JoelEinbinder** [comment]
Yes. Don't specify a path, and it will return a `Buffer`.

**Comment by j** [comment]
@JoelEinbinder yes, that's a buffer which is the current best option.  I'm wondering if I can stream the image to free up memory.  I'm planning on doing large (ish) screenshots and sending them right down and would prefer to chunk the screenshot from Chromium to the user's browser.  Other people have posted about large picture workarounds by clipping the viewport and screenshotting multiple times, and that's sort of a solution if I chunked that to the browser.  I don't want to hold 2-4 mb's in memory for a single picture.

**Comment by aslushnikov** [comment]
> Is it possible to stream the screenshot directly instead of being put on the filesystem?

@j no, there's no support in DevTools protocol to stream screenshots ATM. 

> I don't want to hold 2-4 mb's in memory for a single picture.

That's fair; but unless there's more demand for this, we won't be able to prioritize this high enough to actually carve some time for this. I'll close this for now; we can revisit if/when necessary.
