### ISSUE TITLE
slowMo disables or interferes with page.click()'s scroll-into-view behavior

### ISSUE THREAD

**Issue by kriskhaira** [puppeteer/puppeteer#3398]
### Steps to reproduce

* Puppeteer version: 1.9.0
* Platform / OS version: macOS Mojave 10.14
* Node.js version: v8.12.0

**What steps will reproduce the problem?**

Set slowMo to at least 50.

``` js
// jest-puppeteer.config.js
module.exports = {
  launch: {
    slowMo: 50
  }
}
```

Use page.click(). In my example, I also had page.hover(). I'm not sure if it's related—I had to use it to reveal the div in which the click target is located.

``` js
await page.hover('.product-details .dropdown:nth-child(4)');
await page.click('.product-details #widget3 a[data-value="AT&T"]');
```

**What is the expected result?**

`page.click()` scrolls element into view

**What happens instead?**

I had several instances of those page.click() calls, and when I disabled headless mode, I noticed that the ones which were below the fold of the page in headless had this error:

```
Node is either not visible or not an HTMLElement
```

**Comment by JoelEinbinder** [comment]
It looks like your page has some delayed behavior that you aren't properly awaiting.

**Comment by kriskhaira** [comment]
@JoelEinbinder If that's the case, why would there be issues when slowMo is enabled but not when it's disabled? I'm assuming with slowMo enabled, any delayed behaviour on the page is less of a problem. Unless slowMo actually lengthens any existing delay?

**Comment by aslushnikov** [comment]
@kriskhaira it might be because with slow mo, page is given more time to do its operation; it looks like there's some logic in the page that removes the `.product-details #widget3 a[data-value="AT&T"]` element from the page. 

It's hard to say anything more exact without having the website and script we can experiment with.
