### ISSUE TITLE
Troubles during the install - Ubuntu 16

### ISSUE THREAD

**Issue by c610** [puppeteer/puppeteer#3402]
Hi,

I have some troubles when installing Puppeteer. Maybe you will know what's the problem.
To give it a try I used Ubuntu 16 (32bit):

root@chrome:~# uname -a ; cat /etc/issue
Linux chrome 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 10:19:08 UTC 2018 i686 i686 i686 GNU/Linux
Ubuntu 16.04.5 LTS \n \l

Node and npm versions:

root@chrome:~# npm -v ; node -v
3.5.2
v4.2.6
root@chrome:~#

'history' output after the fresh install was ready:

root@chrome:~# history
    1  apt-get install vim
    2  apt install nodejs
    3  apt-get install npm
    4  node -v
    5  apt install nodejs-legacy
    6  node -v
    7  npm -v
    8  ls
    9  vim http_server.js
   10  sudo node http_server.js
   11  ls
   12  vim http_server.js
   13  ls
   14  sudo node http_server.js
   15  ls
   16  apt search chrome browser
   17  apt search chrome-browser
   18  apt-cache search chrome | grep browser
   19  apt install chromium-browser
   20  npm i puppeteer
   21  npm i puppeteer-core
   22  node install
   23  ls
   24  cd node_modules/
   25  ls
   26  cd ../
   27  ls
   28  less npm-debug.log
   29  npm install -g
   30  npm install -g puppeteer
   31  history
root@chrome:~#

To run the install I used 2 'tutorials':
https://websiteforstudents.com/install-the-latest-node-js-and-nmp-packages-on-ubuntu-16-04-18-04-lts/
https://github.com/GoogleChrome/puppeteer

Error log is attached below.

Thank you for your time.

[npm-debug.log](https://github.com/GoogleChrome/puppeteer/files/2475208/npm-debug.log)

**Comment by ebidel** [comment]
The log says it all.
"Make sure you have the latest version of node.js and npm installed."

Try updating to node 10. You're running node 4.

**Comment by c610** [comment]
Ok, thank you for a fast reply. After I found this case https://github.com/nodesource/distributions/issues/714 I decided to switch to Ubuntu 64bit. Still no luck. 

root@chrome64:~# node -v ; nodejs -v ; npm -v; uname -a; cat /etc/issue
v10.12.0
v10.12.0
6.4.1
Linux chrome64 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04.1 LTS \n \l
root@chrome64:~#

Below you'll find the log file generated for:
npm install -g puppeteer

[root--.npm--_logs--2018-10-14T11_10_06_780Z-debug.log](https://github.com/GoogleChrome/puppeteer/files/2476314/root--.npm--_logs--2018-10-14T11_10_06_780Z-debug.log)

Thank you.

**Comment by aslushnikov** [comment]
@c610 you're trying to install Puppeteer globally - I don't think there's much sense for it. Puppeteer is a library, not a framework / runner. I think this causes some permission issues for you.

Hope this helps.
