### ISSUE TITLE
remove cache-control: no-cache and pragma: no-cache when use puppeteer

### ISSUE THREAD

**Issue by masnampi** [puppeteer/puppeteer#3403]
hi @aslushnikov  . . . i have problem

when i use puppeter to login on a page, chromium that used by puppeteer alwas including cache-control: no-cache and pragma: no-cache on header

but when i use normal chrome / Google Chrome, the header not including cache-control: no-cache and pragma: no-cache

it make me can't login to a website

is there a way to solve my problem ? help

**Comment by rqueraud** [comment]
Same thing here, except that it only occurs when I override at least one header.
Any way of removing those http headers ? The "overrides" parameter of request.continue() seems to only allow adding fields but not removing them.

**Comment by aslushnikov** [comment]
@rqueraud you should be able to remove headers using request interception; please see the https://github.com/GoogleChrome/puppeteer/pull/3475

**Comment by aslushnikov** [comment]
> when i use puppeter to login on a page, chromium that used by puppeteer alwas including cache-control: no-cache and pragma: no-cache on header

@masnampi are we talking about headless / headful chrome here, or the sheer fact of driving browser by puppeteer changes the header behavior?

**Comment by rqueraud** [comment]
@aslushnikov I can't manage to remove headers with request interception.

```
page.on('request', request => {
        const headers = Object.assign({}, request.headers(), {
            foo: 'bar', // set "foo" header
            pragma: undefined, // remove "pragma" header
        });
        console.log(headers);
        request.continue({headers});
    });
```
This example follows the new header overrides example written in the doc.
Doing a get request to my local nodejs express gives me the following headers 

```
{"host":"localhost:3001","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache","foo":"bar","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/71.0.3542.0 Safari/537.36","accept-encoding":"gzip, deflate, br","accept-language":"en-us,en"}
```

Still got the `pragma: no-cache` header. I'm using headless chrome.

**Comment by alexdpoon** [comment]
I noticed the same thing. Puppeteer seems to add the pragma and cache-control headers and there doesn't seem to be a way to remove them, even when using request interception.

**Comment by fastjien** [comment]
Have you solved it?

**Comment by masnampi** [comment]
sorry . . . i just check all your response :)

in my case

the solution is :

don't use await page.setRequestInterception(true);

leave it false

and then after you login, you can set setRequestInterception to true

i don't know why, but it work for me . . .

i think . . . -every enginer behind you target website have their own way to block puppeteer, you should find your way :)
