### ISSUE TITLE
API Function for Emulate Domain calls

### ISSUE THREAD

**Issue by meldron** [puppeteer/puppeteer#341]
Offer a public API Function to send Emulation Domain calls (https://chromedevtools.github.io/devtools-protocol/tot/Emulation/) to the headless chrome instance.

E.g. for taking transparent backgrounds I had to send `this._client.send('Emulation.setDefaultBackgroundColorOverride', {color: {r: 0, g: 0, b: 0, a: 0}})` to the browser instance.

**Comment by ebidel** [comment]
Related https://github.com/GoogleChrome/puppeteer/issues/31

**Comment by meldron** [comment]
Nice to see my problem solved with 127f3966, but imo a general way to interact with the [devtools-protocol](https://chromedevtools.github.io/devtools-protocol/tot/) should be available.

**Comment by aslushnikov** [comment]
> but imo a general way to interact with the devtools-protocol should be available.

@meldron please upvote #31, it's exactly about it

**Comment by meldron** [comment]
@aslushnikov thanks, will do!
