### ISSUE TITLE
Headless Experimental

### ISSUE THREAD

**Issue by positlabs** [puppeteer/puppeteer#3411]
I'm attempting to use the HeadlessExperimental domain via Puppeteer, but I'm having a hard time getting it to work. I've seen a lot of threads about rendering video from Puppeteer, so I'm sure others will be interested in this.

[[headless/devtools] Add BeginFrameControl via DevTools](https://chromium-review.googlesource.com/c/chromium/src/+/612061/16)

I realize it's a new feature, not yet supported by Puppeteer, but I'd like to start working with it now.

The stable release of Puppeteer (1.9.0) is running chromium revision 594312, but it looks like the HeadlessExperimental wasn't patched in until 612061, which isn't included in any of the current chromium releases. I'll have to try using a later revision, but I doubt that will completely solve the issue.

It looks like I would need to be able to set options when I call `browser.newPage()` in order to enable `BeginFrameControl` (as indicated by the error message below). Also, there is a note in the patch that says it needs to be set at creation time.

>Currently, the BeginFrameControl is only supported in headless mode
and can only be enabled at target creation time.

My request is to include options in the call to `browser.newPage()`, in order to create a page that supports using the headless experimental domain. Of course I can submit a PR, but I need to understand how the internals for that would work. Any advice will be much appreciated.

I'm guessing the change would end up on [Browser.js#L174](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Browser.js#L174), but I'm unclear on what the format would be.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: debian:jessie-slim
* Node.js version: 8

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

        const browser = await puppeteer.launch({...})
        const page = await browser.newPage()
        await cdp.send('HeadlessExperimental.enable')
        const frameData = await cdp.send('HeadlessExperimental.beginFrame', {screenshot: {}})

**What is the expected result?**

Get some frame data back

**What happens instead?**

Borks on `HeadlessExperimental.beginFrame`

```
content-generator-api-0  | Error: Protocol error (HeadlessExperimental.beginFrame): 
Command is only supported if BeginFrameControl is enabled.
```

--------------

For visibility, I've also posted on StackOverflow: https://stackoverflow.com/questions/52806059/headlessexperimental-in-puppeteer

**Comment by JoelEinbinder** [comment]
You might want to move this to the DevTools protocol repo: https://github.com/ChromeDevTools/devtools-protocol

You can send whatever cdp commands you want with `target.createCDPSession()`
```js
const session = await browser.target().createCDPSession();
await session.send('Target.createTarget', {/*whatever options you want*/});
```

That being said, it is called `HeadlessExperimental` for a reason. It is almost certainly a waste of time trying to use it before it is finished.

**Comment by positlabs** [comment]
Well, when it becomes stable, I'd like to have an integration with Puppeteer beyond using cdp session to send arbitrary commands. I know it's early for that, but wanted to tinker with it.

**Comment by aslushnikov** [comment]
@positlabs The `beginframecontrol` API is very far from getting out of experiment; it's also very hard to use properly without looking into the chromium codebase to understand what is what.

I don't think we'll want this in pptr in any foreseeable future - there are no plans to implement this in headful, so there's no debugging story around it. The right thing to do would be to create another library for this instead of getting this into Puppeteer.

**Comment by pashkasan** [comment]
well, in pupy 5.3 you can do this, just by passing args to lauch, my config with chrome stable (not chromium - havnt cheked this, but should work also)
this improved perfomance by 170% for me on pages with video content with different chrome profiles on one server run in parallel

                        '--enable-begin-frame-control'; <--- no need to pass enable frame control on create.target
                        '--enable-surface-synchronization';
                        '--run-all-compositor-stages-before-draw';
                        '--disable-threaded-animation';
                        '--disable-threaded-scrolling';
                        '--disable-checker-imaging';
                        '--disable-gpu';
                        '--disable-gpu-compositing';
                        '--disable-gpu-shader-disk-cache';
                        '--enable-widevine-cdm';

function to render frames on demand from node script

async function renderSingleFrame(client) {
    var timer_start = await performance.now();
    var timer_end ;


    let renderFrameResult;
    try {

        renderFrameResult = await client.send('HeadlessExperimental.beginFrame', {
            interval: 60, // read docs on this 
            noDisplayUpdates: false
        });

        timer_end = await performance.now();

        log('renderSingleFrame succcess ' + ((timer_end - timer_start) / 1000).toFixed(2) + " seconds.");

    } catch (e) {

        timer_end = await performance.now();
        log('renderSingleFrame error ' + ((timer_end - timer_start) / 1000).toFixed(2) + " seconds.");

    }


    //log('end rendering frame');

    return true;

}

call it on demand like below , it will render screen and process js events

renderSingleFrame(client)

where client is 
const client = await page.target().createCDPSession(); //you define after creating page

BUT you have to deal with page.mouse and page.click functions, write custom code cause they dont work and crazy lag with native functions
smth like with
//fps implementation
async function fps_move_mouse ( x, y, page ) {

    log (`fps_move_mouse x:${x} y ${y}`);
    let t_start, t_end, t_total;
    let _x = page.mouse._x;
    let _y = page.mouse._y;
    let steps = await getRandomInt(1, 6);
    let _keyboard = page._keyboard;

    log (`current x=${_x} y=${y} target x=${x} y=${y} steps=${steps}`);
    const fromX = _x, fromY = _y;

    for (let i = 1; i <= steps; i++) {
        t_start = await performance.now();
//key stuff
       await Promise.race([
            Promise.all([
                page._client.send('Input.dispatchMouseEvent', {
                    type: 'mouseMoved',
                    button: 'none',
                    x: fromX + (x - fromX) * (i / steps),
                    y: fromY + (y - fromY) * (i / steps),
                    modifiers: _keyboard._modifiers,
                }),
                renderSingleFrame(page._client)

            ]),
           Promise.delay(2000, 'failed')
        ]);

        t_end = await performance.now();
        t_total = await ((t_end - t_start) / 1000).toFixed(2);
        log(`mouse move: step ${i} takes ${t_total}`);

    }
    return true;

}

**Comment by alexey-pelykh** [comment]
Since it's till experimental, had to wrap it up into a plugin: https://github.com/alexey-pelykh/puppeteer-capture
