### ISSUE TITLE
chrome.storage undefined with extension content-script

### ISSUE THREAD

**Issue by tnolet** [puppeteer/puppeteer#3415]
* Puppeteer version: 1.7.0
* Platform / OS version: MacOS 10.12.6 
* Node.js version: v8.11.3

We're running tests using Puppeteer for a chrome extension. All works fine, except that the content-script (the one injected into the user's page) cannot access the `chrome.storage.local` global when running under Puppeteer. We use the pre-package Chromium version. The global is available when just running Chromium and the extension by hand.

Reproducing is easy, as it is already part of a test.
1. Clone this PR branch https://github.com/checkly/puppeteer-recorder/pull/33

```
git clone https://github.com/checkly/puppeteer-recorder.git
cd puppeteer-recorder
git checkout -b petrogad-data-id master
git pull https://github.com/petrogad/puppeteer-recorder.git data-id
```
2. Run the jest suite for the content script. 
```
jest src/content-scripts/__tests__/forms.spec.js
```
Puppeteer is started with the following options:

```
export const launchPuppeteerWithExtension = function (puppeteer) {
  const options = {
    headless: false,
    ignoreHTTPSErrors: true,
    devtools: true,
    args: [
      `--disable-extensions-except=${extensionPath}`,
      `--load-extension=${extensionPath}`,
      '--no-sandbox',
      '--disable-setuid-sandbox'
    ]
  }
  return puppeteer.launch(options)
}
```

I expect the tests to pass. They pass on the master and development branch.

**What happens instead?**

Instead, the call to `chrome.storage.local` fails and breaks execution. We call the storage to get some configuration options.

```
  start () {
    chrome.storage.local.get(['options'], ({ options }) => {
      const {dataAttribute} = options ? options.code : {}
      if (dataAttribute) {
        this.dataAttribute = dataAttribute
      }
...
```

**Comment by aslushnikov** [comment]
@tnolet This might be related to some permission issues, but I haven't seen anything like this. Requires future investigation.

P.S. I see this is not blocking you; good! I'll try to look into this maybe some time later when I do a second pass through bug tracker.
