### ISSUE TITLE
 problem with pdf file size

### ISSUE THREAD

**Issue by Zmoroz** [puppeteer/puppeteer#3416]
`await page.pdf({

	path       : pdfPath,
	width      : '94mm',
	height     : '54mm',
	pageRanges : '1',
	margin     : {
		top     : 0,
		right   : 0,
		bottom  : 0,
		left    : 0,
	},
	printBackground: true
});`

I open the document in adobe acrobat pro dc. I get the size of 93.8mm x 54mm. WHY?

**Comment by bruceCzK** [comment]
I think it is because pdf actually uses px as unit, there's loss when unit convert back and forth.

**Comment by aslushnikov** [comment]
PDF actually uses inches as units, so yeah, I think this is the rounding errors with inches/mm.
