### ISSUE TITLE
Connect chrome without GUID

### ISSUE THREAD

**Issue by ja8zyjits** [puppeteer/puppeteer#3420]
### Steps to reproduce
While connecting remote chromium headless instances behind Loadbalancer(lb) puppeteer needs proper guid to connect.
I know there is a way through service discovery `/json` but since i would be having few chromium running behind my lb. I would like the lb to redirect dynamically without worrying about GUID matching issues.

**Tell us about your environment:**

* Puppeteer version: 1.9.0-post
* Platform / OS version: Chromium 69.0.3497.81 Built on Ubuntu , running on Ubuntu 16.04
* Node.js version:10.12.0

_Please include code that reproduces the issue._

```javascript
const puppeteer = require('puppeteer');

(async () => {
    try {
        const browser = await puppeteer.connect({ browserWSEndpoint: 'ws://load-balancer-url:9222' });
        const page = await browser.newPage();
        await page.goto('https://google.co.in');
        let content = await page.content();
        console.log(content.length);
        await page.close();
        await browser.disconnect();
    }
    catch (exception){
        console.error(exception);
    }
})();
```
**What is the expected result?**

It should connect dynamically and print the content length.

**What happens instead?**

It fails with some unrelated error

```shell
(node:7520) UnhandledPromiseRejectionWarning: #<ErrorEvent>
(node:7520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Possible Solution**

This issue is somewhat related to #940 
A friend of mine made some changes to the core puppeteer library and gave it to me and it seems working. I would like to know if it is the right approach.
Check this out.
https://github.com/GoogleChrome/puppeteer/compare/master...uniquerockrz:master

**Comment by aslushnikov** [comment]
@ja8zyjits what are you load balancing - chrome instances, browser contexts or pages? Given the patch your friend did, it looks like you're actually dealing with Pages - is this the case?

**Comment by ja8zyjits** [comment]
@aslushnikov Iam trying to load balance chromium instance running machines. I am running 1 chromium instance per machine. 
Basically I wanted to perform a selenium-grid kind of distribution of chromium running machines.

**Comment by aslushnikov** [comment]
@ja8zyjits I see. Once you launch a chromium, you can get its endpoint using [`browser.wsEndpoint`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-browserwsendpoint). So every machine would launch a browser instance and report the endpoint to the master node - would this work?

The [puppeteer-cluster](https://github.com/thomasdondorf/puppeteer-cluster) is doing something similar.

**Comment by ja8zyjits** [comment]
@aslushnikov really appreciate your support but Iam not sure if [puppeteer-cluster](https://github.com/thomasdondorf/puppeteer-cluster) does something similar.

It runs chromium in same system concurrently and not in a distributed manner.

### What I would like to do?

I am certainly aware distributed chromium handling is not the main objective of puppteer project, yet I would like to know if there is any way to connect to chromium via a single request.

Presently an HTTP request is sent 1st and later a websocket request is sent based on the details returned(response) from the 1st request.

This makes it difficult to run behind a load balancer.

**Comment by aslushnikov** [comment]
> It runs chromium in same system concurrently and not in a distributed manner.

@ja8zyjits that's right; I was referring to the way it targets chromium instances and gets their remote debugging websockets.

> Presently an HTTP request is sent 1st and later a websocket request is sent based on the details returned(response) from the 1st request.

I don't think I follow this. Why do you need an HTTP request?
- If you launch chrome instances with puppeteer, you have their websocket URLs with `browser.wsEndpoint()`.
- If you launch instances manually, you can read the websocket URL from chrome's stdout.

Can you explain more on how you manage chromium instances?

**Comment by ja8zyjits** [comment]
> I don't think I follow this. Why do you need an HTTP request?

Well when you call `pupeteer.connect()` this is how it happens. I checked my haproxy log.

> If you launch instances manually, you can read the websocket URL from chrome's stdout.

This can work locally. But not in case of remote connection. 

In remote connections we would initiate the chromium instance with supervisor and keep it running and restarting if it crashes.

I was trying to send the request without the guid information `await puppeteer.connect({ browserWSEndpoint: 'ws://load-balancer-url:9222' });`

**Comment by aslushnikov** [comment]
> Well when you call pupeteer.connect() this is how it happens. I checked my haproxy log.

@ja8zyjits This is one is a [WebSocket handshake](https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake), isn't it? You can't avoid it unless you use [`pipe`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-puppeteerlaunchoptions) option and organize your own transport between load balancer and controlled chromium instances.

> I was trying to send the request without the guid information await puppeteer.connect({ browserWSEndpoint: 'ws://load-balancer-url:9222' });

This won't work auto-magically; you can load-balance websocket connections, but you'll still need to get the URL of an open websocket of the controlled chromium instance. That's the only way to connect to chromium.

**Comment by ja8zyjits** [comment]
@aslushnikov ok I understand. Thanks for your time.

**Comment by adamsafr** [comment]
@ja8zyjits hello! Could you please say how you resolved this issue? I faced with the same problem, but use several chrome instances in Kubernetes

**Comment by junedkhatri31** [comment]
For exactly this use case I made - https://github.com/peedief/browserd
browserd container runs a lightweight go server that resolves that json/version. and proxy websocket to chromium.
Run browserd behind load balancer and connect puppeteer to the load balancer.
