### ISSUE TITLE
Access Denied redirect 

### ISSUE THREAD

**Issue by sean-hill** [puppeteer/puppeteer#3428]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: Mac Mojave
* URLs (if applicable): https://www.cabelas.com/user/login.jsp
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

```js
const browser = await puppeteer.launch({ headless: false })
const page = await browser.newPage()
await page.goto('https://www.cabelas.com/user/login.jsp')
await page.waitFor('#userName')
await page.type('#userName', 'test')
await page.type('#password', 'test')
await page.click('#logInBtn')
await page.waitFor(5000)
await page.screenshot({ path: 'failed.png' })

await browser.close()
```

**What is the expected result?**

For an error message to pop on the screen that my credentials are incorrect, as in a normal browser.

**What happens instead?**

The page is redirected to an Access Denied page.

![image](https://user-images.githubusercontent.com/1205866/47175274-97171f80-d2c7-11e8-8edb-4cf4b18edb46.png)

**Comment by entrptaher** [comment]
Interesting, it fails on puppeteer 1.7.0 sandbox too.

![image](https://user-images.githubusercontent.com/8284972/47415495-62a6d600-d795-11e8-8b49-6a28414bad05.png)

**Comment by aslushnikov** [comment]
@sean-hill looks like the webpage/webserver is running some checks to prevent automation scripts; I don't think I can help somehow here.

**Comment by entrptaher** [comment]
Bot detection has been reported and discussed previously with almost no good result lol.

- https://github.com/GoogleChrome/puppeteer/issues/927
- https://github.com/GoogleChrome/puppeteer/issues/3039
- https://github.com/GoogleChrome/puppeteer/issues/3428

I am going to keep track of them so I can figure a way how to prevent this from happening if possible.

**Comment by rotimi-best** [comment]
> @sean-hill looks like the webpage/webserver is running some checks to prevent automation scripts; I don't think I can help somehow here.

How is it possible to identify this if supposedly puppeteer is supposed to work just as the usual chrome does?

**Comment by agustin94** [comment]
try:

await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36')

**Comment by titivermeesch** [comment]
> try:
> 
> await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36')

This can indeed be a solution. Another way is to pass the --user-agent arg when you launch puppeteer. It fixed some of my issues.

**Comment by iraqwarvet31** [comment]
You can pass the user-agent test with the below:
// Get around client test
const preparePageForTests = async (page) => {
  // Pass the User-Agent Test.
  const userAgent = 'Mozilla/5.0 (X11; Linux x86_64)' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.39 Safari/537.36';
  await page.setUserAgent(userAgent);
}

**Comment by tim-kozak** [comment]
Try to use 
const random_ua = require('modern-random-ua'); //generates UA
const StealthPlugin = require('puppeteer-extra-plugin-stealth'); //hides all headles info

**Comment by binadiegha** [comment]
you have to set the userAgent to one that emulates a real browser 

example:

```
  const userAgent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0';
  page.setUserAgent(userAgent);
```

**Comment by sushilsaksoft** [comment]
hi Guys I am getting same issue can anyone help me 
![2022-06-06](https://user-images.githubusercontent.com/96607317/172164720-2382accc-2fce-4b8e-b7d2-5f17cb7e724d.png)
const puppeteer = require('puppeteer')
const cheerio = require('cheerio')

const {
  errors,
  constants: {
    locations: {
      USStates
    }
  }
} = require('by-lib')

const {
  randomWait,
  navigateToPage,
} = require('~/utils')

const SITE_ROOT_URL = 'http://whitepages.com.au'

async function search (ctx, data) {
  const browser = await puppeteer.launch({ headless: false }) // default is true userDataDir: '/tmp/my-profile-directory'
  const page = await browser.newPage()
  await page.setDefaultNavigationTimeout(0);
  await navSearchPage(page, data.privateInfo)
  // const cookies = [{'__Host_Secure_Token': 'nx5dPmzmCCeBDOKeJDvLheIgYdP0EFLUUhzH%2BV93BZ8%3D'}]
  // await page.setCookie(...cookies);
  await randomWait()
  const records = await extractRecords(page)

  return {
    message: '',
    records
  }
}

// --------------------------------------------------------------
//  Layers
// --------------------------------------------------------------

async function navSearchPage (page, {firstName, lastName, city, state }) {
  const link = `${SITE_ROOT_URL}/residential/results?name=${firstName}${lastName}&location=${city},%20${state}`
  console.log(link)
  await page.goto(SITE_ROOT_URL, { waitUntil: 'networkidle2' })
  return await navigateToPage(page, { link }, { waitUntil: 'networkidle2', referrer: SITE_ROOT_URL })
}

async function extractRecords (page) {
  await page.waitForSelector('.search-result-list', { visible: true }).catch(() => {
    throw new errors.NoMatchingRecords()
  })

  const content = await page.$eval('.residential', element => element.innerHTML)
  const $ = cheerio.load(content)
  console.log($, '$$$$$$$$$***************************************************')
  const rows = $('div > [data-v-27be1699]')
  console.log(rows, 'rowsrowsrowsrowsrowsrowsrowsrowsrowsrowsrows***************************************************')
  const records = []
  for (let i = 0; i < rows.length; i++) {
      const row = rows.eq(i)
      console.log(row, '***************************************************')
      records.push({
      index: i,
      // fullName: $(row).find('ul li:first-child a:first-child').text().trim(),
      // addresses: addresses.length > 0 ? arrayClean(addresses) : ['available'],
      // phoneNumbers:  ['available'],
      // emailAddresses: ['available'],
      link: SITE_ROOT_URL + $(row).find('a').attr('href')
    })
  }
  console.log('sushil records>>>>>>>>>>>>>>>>>>>>', records)
  return records
}
module.exports = search
module.exports.extractRecords = extractRecords
module.exports.navSearchPage = navSearchPage
module.exports.SITE_ROOT_URL = SITE_ROOT_URL

const ctx = { page: { _client: {}, keyboard: {}, response: {} } }
const privacyInfo = { privateInfo: { firstName: 'John', lastName: 'ston', city: 'Western', state: 'Australia' } }

search(ctx, privacyInfo)
