### ISSUE TITLE
Chrome closes itself after a few seconds

### ISSUE THREAD

**Issue by Bux42** [puppeteer/puppeteer#3429]
### Steps to reproduce

OS:

> Distributor ID: Debian
> Description:    Debian GNU/Linux 9.5 (stretch)
> Release:        9.5
> Codename:       stretch

Node Version:

> 10.11.0

Puppeteer Version:

> 1.9.0

The code:

```
const puppeteer = require('puppeteer');
const delay = require('delay');

(async() => {
        const browser = await puppeteer.launch({
                args: ['--no-sandbox']
        });
        const page = await browser.newPage();
        await page.goto('https://google.com');
        await page.tracing.start({
                screenshots: true, path: './yes.json'
        });
        await delay(10000);
        await page.tracing.stop();

        await page.close();
        await browser.close();
})();
```
I think the only reason it worked in my previous test was that the script finished before chrome closes itself

But chrome closes itself after a few seconds no matter what

The server I'm running this on has enough ressources to run chrome, I'm not using docker or anything just running it the way it is

Am I doing something wrong?

**Comment by aslushnikov** [comment]
> But chrome closes itself after a few seconds no matter what

@Bux42 Usually this means that chrome crashes. Can you please try running chrome with `dumpio` and see what's the output?

```js
const browser = await puppeteer.launch({
  dumpio: true, // <== output chrome logs to STDOUT
  args: ['--no-sandbox']
});
```
