### ISSUE TITLE
Question: possible to simulate drag and drop?

### ISSUE THREAD

**Issue by patrick-webs** [puppeteer/puppeteer#343]
Can puppeteer perform drag and drop operations similar to the capabilities provided by [WebDriver/Selenium's Actions class](https://stackoverflow.com/a/14222645/631628)?

**Comment by JoelEinbinder** [comment]
It depends how faithfully you want it to work. You can use `page.mouse` to do a series of down -> move -> up. Drop events will be buggy where they cross into some OS behavior. It is on my list of things to fix.

**Comment by patrick-webs** [comment]
thanks :)

**Comment by nov-liluo** [comment]
I meet the same problem，I use page.mouse move to canvas, but the canvas.ondrop() event did't work.

**Comment by TNT-Likely** [comment]
@JoelEinbinder down->move->up not work for me

**Comment by TNT-Likely** [comment]
![image](https://user-images.githubusercontent.com/9278923/47691847-96b74680-dc2e-11e8-9a43-64e757bdfae4.png)
