### ISSUE TITLE
UI is loaded, but doesn't load the data(UI test automation) --page.reload()

### ISSUE THREAD

**Issue by nargiza2018** [puppeteer/puppeteer#3431]
* Puppeteer version:v1.8.0
* Platform / OS version: Windows 10
* URLs (if applicable): localhost
* Node.js version: 10.12.0

**What steps will reproduce the problem?**

 code that reproduces the issue._

puppeteer.launch({ headless: false}).then(async browser => {
            // Create a new incognito browser context.
           // const context = await browser.createIncognitoBrowserContext();
            // Create a new page in a pristine context.
            const page = await browser.pages()[0];
            //Automatic passwordless login
            var host = "http://loacalhost:1000"
            await page.goto(host);
            await page.waitForNavigation();
           // await page.waitForSelector("#loginPage"); 
            await page.waitFor(1300);
            await page.type("#loginPage", "loginpage@live.com");
            await page.keyboard.press('Enter');
            await page.waitForNavigation();
            await page.waitFor(5000);
 //going to a page where I create a new form
            var addNewForm= "http://localhost:1000/#/newform"
            await page.goto(addNewForm);
            await page.reload(); 
            await page.waitForNavigation(); 

**What is the expected result?**
It supposed to load the page with all the data from the server, so I could evaluate the date and pass the test. 
**What happens instead?** 
It loads the UI page but doesn't load the data. I have to manually refresh the page again to load the data, how to repeat that action for the UI automation.

**Comment by aleksdjelic** [comment]
var host = "http://loacalhost:1000"
