### ISSUE TITLE
Notifications not available in headless mode

### ISSUE THREAD

**Issue by pk992** [puppeteer/puppeteer#3432]
* Puppeteer version: 1.8.0
* Platform / OS version: Windows 8.1
* Node.js version: v10.11.0

**What steps will reproduce the problem?**
Assuming there is a registered serviceworker and a notification:

```
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        headless: true
    });

    const context = browser.defaultBrowserContext();
    const page = await context.newPage();

    await page.goto('https://notificationDomain.com', {
        waitUntil: "networkidle2"
    });

    const notifications = await page.evaluate(() => {
        return navigator.serviceWorker.ready.then(function(registration) {
            return registration.getNotifications().then(function(notifications) {
                return notifications;
            })
        })
    });

    console.log(notifications.length + ' Notifications');
    await browser.close();
})();
```

**What is the expected result?**
The notifications array should contain the notification like it does when using the non-headless mode.

**What happens instead?**
The notifications array is empty although there is a notification.

**Comment by pk992** [comment]
Is this expected behavior? Any help is appreciated.

**Comment by aslushnikov** [comment]
@paul-kl can you please try enabling "notifications" using [`browserContext.overridePermissions`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-browsercontextoverridepermissionsorigin-permissions)?

**Comment by pk992** [comment]
@aslushnikov I'm sorry, forgot that in my example but used it in my code. I hope this helps:
```
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
        headless: false
    });

    const domain = 'https://puush.pw'
    const context = browser.defaultBrowserContext();
    const page = await context.newPage();

    await context.overridePermissions(domain, ['notifications']);

    try {
       await context.overridePermissions(domain, ['push']);
    } catch (e) {
       // workaround because 'push' throws unknown permisson type but works anyways
    }

    await page.goto('https://puush.pw', {
        waitUntil: "networkidle2"
    });

    // Wait for the SW
    await page.waitFor(1*5000);

    const sw = await page.evaluate(() => {
      return navigator.serviceWorker.getRegistrations().then(registrations => {
        return registrations && registrations.length > 0 ? true : false;
      })
    })

    // Give me time to send the push notification
    await page.waitFor(1*15000);
    console.log('Push check...');

    if(sw){
      const notifications = await page.evaluate(() => {
          return navigator.serviceWorker.ready.then(function(registration) {
              return registration.getNotifications().then(function(notifications) {
                  return notifications;
              })
          })
      });

      console.log(notifications.length + ' Notifications');
    } else {
      console.log('SW not registered!');
    }

    await browser.close();
})();
```
Output non-headless:
```
Push check...
0 Notifications
```
or when I did send one (onesignal.com service running on the domain)
```
Push check...
1 Notifications
```
Output headless:
```
Push check...
SW not registered!
```
The serviceworker won't register. If I register it non-headless and try to get push notifications headless, they won't show up. There is something strange about the 'push' permission but once I added it, I was able to recive push notifications, not just normal ones.

**Comment by tg2dex** [comment]
Hi, you can click on the notification or get data from the onclick method?

**Comment by pk992** [comment]
I think my previous results aren't accurate because I wasn't able to receive notifications again with the 'push' permission (I've also upgraded to 1.10.0). I did some more testing:

Normal notifications and overridePermissions 'notifications' work fine.
If push notifications are requested and overridePermissions 'push' is set, the 'Allow'/'Deny' dialog pops up, so it isn't working. If I press 'Allow' by hand, close the browser and run the profile again, I'm able to receive push notifications.

Headless won't take the headful profile where push was accepted (or any profile at all, nothing happens) so I couldn't test the profile in headless.

If I use a headless instace without a profile I can't get any service worker output while I'm able to get servicer worker output in headful (without hitting 'Allow', like in my example above). 

@reznikGit in headful mode you can dump the notification data. Not sure about handling the onclick method.

**Comment by pk992** [comment]
@aslushnikov do you think you could add push and (better?) SW coverage in the near future? If not, is it possible to handle the push notifications with the dev protocol?

**Comment by pk992** [comment]
"is it possible to handle the push notifications with the dev protocol?" 🤔

**Comment by pinturic** [comment]
Is there any plan to go on working on this?

**Comment by dbagia** [comment]
I am facing the exact same issue as posted by @paul-kl today. It will be great if this can be fixed

**Comment by pinturic** [comment]
I am still facing the same problem.

**Comment by OrKoN** [comment]
The issue got resolved in the latest versions using the new default headless mode:

```
