### ISSUE TITLE
I can't run a unit test from QUnit 

### ISSUE THREAD

**Issue by villander** [puppeteer/puppeteer#3437]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version:
* URLs (if applicable):
* Node.js version: 8.11.4

I have a external function that get a element

```js
export const $ = (selector) => {
  return document.querySelector(selector);
};
```

but when I try to run it in the browser using puppeteer, it just returns me an empty object.

```js
const puppetter = require('puppeteer');
const QUnit = require('qunit');
const path = require('path');
const fixturePath = path.resolve(__dirname, './fixtures');

const { module: testModule, test } = QUnit;
import { $ } from '../src/helpers/dollar';

testModule('$ - dollar DOM', function (hooks) {

    hooks.before(async function() {
      this.browser = await puppetter.launch();
    });
    
    hooks.after(async function () {
      await this.browser.close();
    });

    test('application loads and shows number of online users', async function (assert) {
      const page = await this.browser.newPage();
      await page.goto(`file:${fixturePath}/index.html`, { waitUntil: 'load' });

      const foo = await page.evaluate($, 'body');
      console.log(foo.toString())
      assert.equal(foo, 'Hello World!'); // foo is {} empty object

      await page.close();
    });
});
```

should not it be possible to do unit tests of functions that deal with the DOM? Should I be able to do everything I do in the browser by running puppeteer?

If i run $ like this function, all works. But I can be able to write unit test too: 

```js
export const $ = (selector) => {
  return document.querySelector(selector).innertText;
};
```

**Comment by villander** [comment]
cc : @aslushnikov @entrptaher

**Comment by entrptaher** [comment]
1. The $ function has a typo. You are using `.innertText` not `.innerText`.

2. Did you transpile the module before using it in the browser? Most likely the browser still doesn't support module import/export, right? Did you try this way of exporting,

```js
// dollar.js
const $ = selector => document.querySelector(selector).innerText;
module.exports = $;
```

The file below worked perfectly fine for me with the above setup (module.exports).
```js
// index.js
const puppeteer = require('puppeteer');

const QUnit = require('qunit');
const $ = require('./dollar');

const { module: testModule, test } = QUnit;

testModule('$ - dollar DOM', (hooks) => {
  hooks.before(async function() {
    this.browser = await puppeteer.launch();
  });

  hooks.after(async function() {
    await this.browser.close();
  });

  test('Matches the big header', async function(assert) {
    const page = await this.browser.newPage();
    await page.goto('https://example.com');
    const title = await page.evaluate($, 'h1');
    assert.equal(title, 'Example Domain');
  });
});

```

**Comment by villander** [comment]
@entrptaher even using this solution

```js
const $ = selector => document.querySelector(selector);
module.exports = $;
```
if I put innerText inside the function works, but my original function is this, it returns only the element.

the `title` continue returning a empty object, the problem is not es5 or es6. The problem is with puppeteer way

```js
test('Matches the big header', async function(assert) {
    const page = await this.browser.newPage();
    await page.goto('https://example.com');
    const title = await page.evaluate($, 'h1');
    assert.equal(title.innerText, 'Example Domain'); // title - {}
  });
```

**Comment by entrptaher** [comment]
That's not a bug, nor an issue. 

`.evaluate` returns a Promise, which is not a HTML Node. So calling `.innerText` on that will not work. If you want to use that data, you have to do it inside `.eval` or `.evaluate` or similar.

btw, here is a [stackoverflow answer](https://stackoverflow.com/a/52932621/6161265) I wrote 2 days ago related to your question.

**Comment by villander** [comment]
@entrptaher following your [stackoverflow aswer](https://stackoverflow.com/questions/52931814/puppeteer-log-html-dom-object-in-evaluate/52932621#52932621) the problem persist. 

I'm sorry, but this still seems like an issue, look at this scenario. the result will return - `ReferenceError: _dollar is not defined`

```js
const $ = selector => document.querySelector(selector);
module.exports = $;
```

```js
const puppeteer = require('puppeteer');

const QUnit = require('qunit');
const $ = require('./dollar');

const { module: testModule, test } = QUnit;

testModule('$ - dollar DOM', (hooks) => {
  hooks.before(async function() {
    this.browser = await puppeteer.launch();
  });

  hooks.after(async function() {
    await this.browser.close();
  });

  test('sould return the dom element if exist', async function (assert) {
      const page = await this.browser.newPage();
      await page.goto(`file:${fixturePath}/index.html`);

      await page.addScriptTag({ url: 'https://www.unpkg.com/domjson' });

      const bodyEl = await page.evaluate(() => {
        return domJSON.toJSON($('body'));
      });
      console.log(JSON.stringify(bodyEl, true, 2)); // return ReferenceError: _dollar is not defined
      assert.ok(bodyEl);

      await page.close();
    });
});
```

Trying the evaluate script the `.evaluate` will return a {}

```js
test('sould return the dom element if exist', async function (assert) {
      const page = await this.browser.newPage();
      await page.goto(`file:${fixturePath}/index.html`);

      await page.addScriptTag({ url: 'https://www.unpkg.com/domjson' });

      const bodyEl = await page.evaluate(`
          // Now I'm inside BROWSER environment
          () => {
            return domJSON.toJSON($('body'));
          }
      `);
      console.log(JSON.stringify(bodyEl, true, 2)); // {}
      assert.ok(bodyEl);

      await page.close();
    });
```

**Comment by entrptaher** [comment]
1. Are you using babel/webpack?
2. You are importing `$` on nodeJS but using it inside the `browser`?

**Comment by villander** [comment]
1. babel
2. yes, importing on `test.js` file but using puppeteer as headless to these tests that need of browser environment/user interaction.

**Comment by aslushnikov** [comment]
@villander try using `page.evaluateHandle` instead of `page.evaluate`. This way you'll get an [`ElementHandle`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-class-elementhandle) as a result.

The [`page.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-pageevaluatepagefunction-args) won't return you any DOM node since it's not serializable and can't pass the process boundary.

Hope this helps.

P.S. note, that your `page.evaluateHande($, 'body')` is the same as `await page.$('body')`. See [`page.$`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-pageselector) for details.

**Comment by villander** [comment]
@aslushnikov I don't want to replace my function with `page.$`. I need test my function/modules on browser with Qunit + Puppeteer. I need to ensure that they will work in the browser at levels of unit testing, integration and acceptance

**Comment by aslushnikov** [comment]
> I need test my function/modules on browser with Qunit + Puppeteer.

I'm not sure I follow - how's `page.$` contradicting this statement?

**Comment by entrptaher** [comment]
@villander you are trying to `assert` the DOM on node environment, but testing on `browser` environment, which is a contradiction. You cannot use **dom elements** on node environment. 

So you have to do whatever I suggested above https://github.com/GoogleChrome/puppeteer/issues/3437#issuecomment-432506267 or do the assert on the browser environment. That's how it will work and if you see the hundreds of tests written on the puppeteer repo, they all have same method.

Again:
- Assert the data on node.
- Never assert the dom on node.
- Assert the dom on browser if need.

**Comment by villander** [comment]
@entrptaher  come on the puppetter is not a headleess pro chrome? because when I do assert in evaluate I'm not in the browser?

So you mean there's no way I can do DOM assert on the puppetter, is that what you're telling me?

This comment https://github.com/GoogleChrome/puppeteer/issues/3437#issuecomment-432506267 you are using the same flow, doing `assert` after call `.evaluate` function.

Could you please send me a demo of this working in my scenario?

**Comment by villander** [comment]
@aslushnikov the `page.$` is a function from puppetter, i want to test my function. 

I have private functions that deal with the DOM, I'm not using jquery. `$` Is a private implementation

**Comment by entrptaher** [comment]
**Puppeteer** is a Headless Chrome Node API, not a testing library. 

When you want to assert in evaluate, you are inside the browser. But The browser does not know what assert is. You cannot do that without exposing assert first, also mocha won't handle things inside the browser, it will only handle outside the browser.

In the example, I am doing whatever I want to do with my functions. And then asserting them on the **node**. You will see at least hundred people are doing the same thing same way right now. Either using this way, or using [JSDOM](https://github.com/jsdom/jsdom).

You just have to change your way of testing them. You can return a DOM element, but whenever it comes on the node context, it won't be a dom element anymore but a controller/handle for that DOM element. You can learn more about **[JSHandle](https://github.com/GoogleChrome/puppeteer/blob/v1.9.0/docs/api.md#class-jshandle)** and **[ElementHandle](https://github.com/GoogleChrome/puppeteer/blob/v1.9.0/docs/api.md#class-elementhandle)**.

Check the following resources:

- Mocha:
  - https://mochajs.org/#running-mocha-in-the-browser
- Jasmine:
  - https://github.com/jasmine/gulp-jasmine-browser
- Jest:
  - https://github.com/facebook/jest/issues/848#issuecomment-340225198
  - https://jestjs.io/docs/en/puppeteer
  - https://github.com/smooth-code/jest-puppeteer
  - https://github.com/reid47/jest-browser

This is a headache of discussion that's been going around in all kind of testing libraries. All of them has this exact discussion, they want to run tests inside the browser, hopefully someone will manage to figure it out without pain.

Peace.
