### ISSUE TITLE
page.goto opens same url everytime

### ISSUE THREAD

**Issue by InvincibleDRT** [puppeteer/puppeteer#3439]
`   puppeteer.launch({
        headless: false
    }).then(async browser => {
        isSuccess = false;

        urlList= JSON.parse(urlListJson);
        const promises = [];

        for (var element in urlList) {
            console.log(element);
            url = new URL(baseUrl);
            url.searchParams.append(guid, urlList[element].guid);
            console.log(url.toString());

            promises.push(browser.newPage().then(async page => {
                await page.goto(url);
                console.log('url loaded');
                page.goto('about:blank');
            }));
            
        }
        await Promise.all(promises);`
urlList contains json array of guids which I am looping through and appending to base url and opening a page for every guid. but all the pages are having same url. excuse me if I did anything silly!

**Comment by vsemozhetbyt** [comment]
Try:
```js
const url = new URL(baseUrl);
```
In your code, `url` is a global variable, so when all the `.then()` functions are executed, they possibly have the same `url` value.

**Comment by InvincibleDRT** [comment]
ahhh...thought it was something silly...thanks :)
