### ISSUE TITLE
Screenshots are captured with a white background

### ISSUE THREAD

**Issue by maxschmeling** [puppeteer/puppeteer#344]
I am attempting to capture a screenshot of a page with a transparent background, but the screenshot always has a white background.

I found [Chromium issue #689349](https://bugs.chromium.org/p/chromium/issues/detail?id=689349) and tried launching with `--default-background-color=0` and also `--default-background-color=00000000` but both failed to launch.

**Comment by maxschmeling** [comment]
Since `puppeteer` is using the [--remote-debugging-port option](https://github.com/GoogleChrome/puppeteer/blob/3ce173c16bb9e8ae27ef148507c1bc2e1979645d/lib/Launcher.js#L40), it's probably getting the same error mentioned in [Comment#19](https://bugs.chromium.org/p/chromium/issues/detail?id=689349#c19) on that Chromium issue.
```
Setting default background color is disabled when remote debugging is enabled.
```

[Comment#20](https://bugs.chromium.org/p/chromium/issues/detail?id=689349#c20) says this: 
```
If you use --remote-debugging-port, you'll have to set the color override yourself via your devtools client, using the DevTools command below. (The headless_shell can't do it for you, since there's only one simultaneous DevTools client connecion allowed.)

https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDefaultBackgroundColorOverride
```

**Comment by maxschmeling** [comment]
Looks like @meldron arrived at this conclusion in #341 a little while ago.

**Comment by maxschmeling** [comment]
I verified that the `setDefaultBackgroundColorOverride` method works using this code:
```
const page = await browser.newPage();
page._emulationManager._client.send(
  'Emulation.setDefaultBackgroundColorOverride',
  { color: { r: 0, g: 0, b: 0, a: 0 } }
);
```

**Comment by meldron** [comment]
Glad it solved your problem!

But I am not incorrect that there is now public Emulation API?

**Comment by maxschmeling** [comment]
There isn't a public Emulation API that I see. There is just `lib/EmulationManager.js` which is used internally by `setViewport` right now.

**Comment by maxschmeling** [comment]
In my code sample above, `page._emulationManager._client` could just be `page._client`.

**Comment by meldron** [comment]
In 127f396 omitBackground can only be set for `page.screenshot`, so it will be sent every time you take a screenshot. Shouldn't it be possible to set it for page (`browser.newPage()`) or browser (`puppeteer.launch`) to avoid redundant calls?

**Comment by TheSnowGuru** [comment]
Try here: [Website Screenshot & Color Palette Bot](https://apify.com/finderr/puppeteer-website-screenshot-color-palette-bot)
