### ISSUE TITLE
Can't launch more than one puppeteer instance when using userDataDirectory

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#3440]
* Puppeteer version: v1.9.0

Tested with multiple OSes and other setup. As soon as I use a `userDataDirectory` while launching a browser, I get this error:
<img width="954" alt="screen shot 2018-10-24 at 1 03 22 pm" src="https://user-images.githubusercontent.com/1330677/47467331-bcfe6180-d7aa-11e8-914c-435000758ee7.png">

I am using `await puppeteer.launch()` to launch a new browser instance.

**Comment by aslushnikov** [comment]
You should not launch multiple browsers simultaneously with the same `userDataDir`; they'll fight each other.

Please, use separate folders.

**Comment by VikramTiwari** [comment]
Hey @aslushnikov I don't understand why they would. I can launch multiple chrome instances from a single user data directory and I can do the same for chromium too. Why is this any different when its in headless mode?

I have seen various instances of trying to reuse `BrowserContext` to parallelize multiple puppeteer scripts but that seems like not a great approach for simple tasks where browser size is a variable.

**Comment by aslushnikov** [comment]
>  I can launch multiple chrome instances from a single user data directory and I can do the same for chromium too.

@VikramTiwari are you sure you launch multiple chrome instances, not chrome windows?

> I have seen various instances of trying to reuse BrowserContext to parallelize multiple puppeteer scripts but that seems like not a great approach for simple tasks where browser size is a variable.

Why don't you like Browser Contexts for parallelization?

**Comment by VikramTiwari** [comment]
@aslushnikov Ah! I understand that. It's multiple chrome windows, not instances.

My understanding was that if there's something that relates to browser size then while using a single BrowserContext I might get the desired size of window itself. Another one would be to make sure that cookies or localstorage doesn't conflict.

**Comment by aslushnikov** [comment]
> Another one would be to make sure that cookies or localstorage doesn't conflict.

These won't conflict in different browser contexts. The window size.. well, it depends on emulation properties you pick, such things as [`defaultViewport`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-puppeteerlaunchoptions) and [`page.setViewport`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-pagesetviewportviewport)
