### ISSUE TITLE
For pages with long pages, the captured images have only black background.

### ISSUE THREAD

**Issue by jiajunli** [puppeteer/puppeteer#3441]
<!--
STEP 1: Are you in the right place?
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**
For pages with long pages, the captured images have only black background.     

**What is the expected result?**
    I hope screenshot page normal
**What happens instead?**
   example: https://mp.weixin.qq.com/s?src=11&timestamp=1540450838&ver=1203&signature=C43EL-z6Xg68yh2jDzcRkXsw1X3D8l8-CPChxHetNHXPIf7--gpBP78U1vzAEBr5E6YUUzn9-quVYNkpM0oif64YgNqkFdk-lCrzJzANJsnysPHGkv0hJ9LM1YgVKQGe&new=1

**Comment by jiajunli** [comment]
For pages with long pages, the captured images have only black background.

**Comment by aslushnikov** [comment]
I guess this is similar to our other screenshot bugs, e.g. #3170
