### ISSUE TITLE
Chromium is locking website folders

### ISSUE THREAD

**Issue by InvincibleDRT** [puppeteer/puppeteer#3444]
We are running puppeteer using aspnet.nodeservices. Chromium is locking folders from where the node.js is invoked using nodeservices. so we are not able to deploy our code anymore (this tries to purge everything before update). is there any failsafe that I can put when launching puppeteer to not to do that?

**Comment by aslushnikov** [comment]
@InvincibleDRT what do you mean by "locking folders"?

**Comment by InvincibleDRT** [comment]
I'm unable to delete that folder. And I see some orphaned chrome instances running. I think my js script errored out and browser.close didn't smoothly finish off.

**Comment by aslushnikov** [comment]
@InvincibleDRT I see. In this case, the folder is indeed opened since Chrome is holding a handle onto it.

I'm not quite familiar with `aspnet.nodeservices` and it's node script lifecycle; you probably need to install some hooks to terminate the running browser.

Hope this helps.

**Comment by InvincibleDRT** [comment]
I have added a failsafe browser close in the js script, Ive yet to test that out. Have a feeling that will work. Thanks!
