### ISSUE TITLE
Add Api for intercepting/cancelling DOM mutation

### ISSUE THREAD

**Issue by LucasPonzo** [puppeteer/puppeteer#3445]
### Steps to reproduce

* Puppeteer version: 1.9.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 10.12.0

-------------
It would be nice to have some kind of pupObserver, a simple Api call to register/unregister DOM mutation observer in puppeteer, wich would receive a callback (running on the Node js context) for calling uppon mutations, and sending an object to that callback with the events details.

**Comment by vsemozhetbyt** [comment]
Do [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) as a listener + [`page.exposeFunction()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction) as a callback suffice?

**Comment by aslushnikov** [comment]
@vsemozhetbyt suggested a very reasonable approach. This will also play very nice with #2829; feel free to thumb it up to follow updates.
