### ISSUE TITLE
Atempt to open a page with `headless: true` and userDataDir relative path hangs with high CPU load

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#3453]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0-post (chromium_revision 599821)
* Platform / OS version: Windows 7 x64
* URLs (if applicable): any?
* Node.js version: 11.0.0 (or 12.0.0-v8-canary)

**What steps will reproduce the problem?**

This script is OK:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: true,
    });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    console.log(await page.evaluate(() => document.title));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

This hangs with high CPU load and no error messages:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: true,
      userDataDir: 'test-profile-dir',
    });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    console.log(await page.evaluate(() => document.title));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by vsemozhetbyt** [comment]
Notes:
1. It seems any URL will do (including https://example.org/).
2. With `headless: false` the issue is gone.
3. The content of the newly created profile dir after the process aborted:
```
Crashpad/reports
Crashpad/settings.dat
CrashpadMetrics-active.pma
```
P.S.
4. Absolute path for `userDataDir` is OK.

**Comment by kanxue660** [comment]
I have the same problem when i set userDataDir,Very high CPU consumption

**Comment by jasonswearingen** [comment]
@vsemozhetbyt  I tried your example on pptr 1.9.0 win10x64 and was not able to reproduce high cpu/hang.

curiously, I am also able to specify an invalid userDataDir with no ill effects, which is surprising

edit:  I'm on node 8.11 lts.   perhaps you can try on that

**Comment by vsemozhetbyt** [comment]
@jasonswearingen Unfortunately, I have the same issue with 11.0.0, 10.12.0, and 08.12.0. Did you test with the same chromium_revision (599821)?

P.S. The same issue with 8.11.0

**Comment by jasonswearingen** [comment]
you are right, looking at my node_modules ppuppeteer package.json file, I'm using ```"chromium_revision": "594312"```

if you can tell me what version to upgrade my puppeteer npm module to, I can give that a try.  I"m on ```1.9.0```

**Comment by vsemozhetbyt** [comment]
You can install from the master, it currently has this revision:
```
npm install https://github.com/GoogleChrome/puppeteer
```

**Comment by jasonswearingen** [comment]
@vsemozhetbyt I did that npm install (now on 599821) and still have no problems using ```C:\\tmp\\pptr``` as a (valid) userDataDir, or using an invalid userDataDir   (no hangs/highcpu)

**Comment by jasonswearingen** [comment]
in case it matters, here's the code I ran to try reproing your issue:

```javascript
( async function main() {
	try {
		const browser = await puppeteer.launch( {
			headless: true,
			userDataDir: 'c:\\tmp\\pptr',
		} );
		const [ page ] = await browser.pages();

		console.log( "about to page.goto()" );

		await page.goto( 'https://example.org/' );
		console.log( "done to page.goto()" );

		console.log( await page.evaluate( () => document.title ) );

		await browser.close();
	} catch ( err ) {
		console.error( err );
	}
} )();
```

**Comment by jasonswearingen** [comment]
fyi, i even tried specifying a temp dir that the exe didn't have access to, in case it was a permissions problem.    Still had no problems.  

however, I'm not very versed in puppeteer diagnostics, so maybe someone else can try helping out......

**Comment by vsemozhetbyt** [comment]
@jasonswearingen Thank you! It seems the cause is the path: try to use not absolute, but a relative path, i.e not `'c:\\tmp\\pptr'` but just `'pptr'`.

**Comment by jasonswearingen** [comment]
ok, with a relative dir I have the same issue you describe.

using the following code:
``` javascript
( async function main() {
	try {

		console.log( "about to pptr.launch()" );

		const browser = await puppeteer.launch( {
			headless: true,
			userDataDir: '..\\somedir',
		} );

		console.log( "done launch, about to obtain pages()" );

		const [ page ] = await browser.pages();

		console.log( "about to create new context+page" );

		console.log( "about to page.goto()" );

		await page.goto( 'https://example.org/' );
		console.log( "done to page.goto()" );

		console.log( await page.evaluate( () => document.title ) );

		await browser.close();
	} catch ( err ) {
		console.error( err );
	}
} )();
```
pptr hangs with max cpu at the ```await browser.pages();``` call.

**Comment by aslushnikov** [comment]
@vsemozhetbyt this is a chromium bug, can you please report upstream?

**Comment by vsemozhetbyt** [comment]
Done: https://bugs.chromium.org/p/chromium/issues/detail?id=900952

**Comment by vsemozhetbyt** [comment]
Additional note: on Windows, `/` delimiter in the absolute user data dir path still causes this issue, only `\\` delimiter is OK.

**Comment by vogler** [comment]
Can't `launch` just call `resolve` on `userDataDir`?
Just wondered why my script that ran under macOS didn't do anything under Windows... Disabled headless and it worked. Then found this.
Hangs on navigation: `{ userDataDir: 'user_data', headless: true }`.
Workaround: `{ userDataDir: resolve('user_data'), headless: true }`.

**Comment by canghai118** [comment]
same problem here,  test both on  ubuntu 18.04 and macos catalina.  use path.resolve to convert to absolute path works well

**Comment by rohitsg** [comment]
> Can't `launch` just call `resolve` on `userDataDir`?
> Just wondered why my script that ran under macOS didn't do anything under Windows... Disabled headless and it worked. Then found this.
> Hangs on navigation: `{ userDataDir: 'user_data', headless: true }`.
> Workaround: `{ userDataDir: resolve('user_data'), headless: true }`.

Workaround: { userDataDir: resolve('user_data'), headless: true }. - working fine, otherwise was facing cpu load issue.

**Comment by vcfvct** [comment]
> Can't `launch` just call `resolve` on `userDataDir`?
> Just wondered why my script that ran under macOS didn't do anything under Windows... Disabled headless and it worked. Then found this.
> Hangs on navigation: `{ userDataDir: 'user_data', headless: true }`.
> Workaround: `{ userDataDir: resolve('user_data'), headless: true }`.

@vogler , you the **MAN**. I was banging my head against the wall on why my script works on headful but not headless mode... Thank you so much for pointing it out. 
So just wondering how did you find out this out, I saw you mentioned.
> Hangs on navigation: { userDataDir: 'user_data', headless: true }.

**Comment by vogler** [comment]
> So just wondering how did you find out this out, I saw you mentioned.

It worked under macOS, so I assumed it must be the path.

---

The Chromium people can't reproduce.
Why not just fix it by calling `resolve` on `userDataDir` internally? Should be no issue since the function is idempotent.

**Comment by Luckz** [comment]
As per https://github.com/puppeteer/puppeteer/pull/6506#issuecomment-707704351 this should be closed nowadays, no?
