### ISSUE TITLE
Cannot log "page" events in v1.9.0

### ISSUE THREAD

**Issue by patrickeakin** [puppeteer/puppeteer#3454]
Puppeteer: 1.9.0
macOS: 10.14
Node: 8.12.0

**Code that reproduces the issue:**
```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```

**Steps:**
1. Install Puppeteer v1.8.0
2. Run a puppeteer script with `DEBUG='puppeteer:page'`
3. In the terminal you'll see all the `page` events logged.
4. Install Puppeteer v1.9.0
5. Run the script the same way with `DEBUG='puppeteer:page'`
6. No logs are shown in the terminal

**Note:** If you run with `DEBUG='puppeteer:*'` you will get logs for `session` and `protocol` but nothing else.

**Expected:** I should be able to get logs of all the `page` events.

**Actual:** I can only get logs for `session` and `protocol`.

**Comment by aslushnikov** [comment]
@patrickeakin we dropped the Public API logging in 1.9.0 since we've never used it to debug issues; on the contrary, it was yielding overly verbose logs. Why do you need it?

**Comment by patrickeakin** [comment]
@aslushnikov Thanks for getting back to me 😄.  I'm using Puppeteer and Ava to write integration and UI tests for a large web application. As I write the tests I used the logging to see exactly on what step the script is timing out. These timeouts normally indicate things like a transition not accounted for, a selector that needs to be changed, etc. Essentially the logging pointed to the exact place in my test suites where a problem lies. It's been indispensable in my ability to debug the scripts as i develop them.

I'd appreciate in giant heaping amounts to at least be able to log the `page` and `elementHandle` events. Or if you can suggest another avenue I might try to see the steps as they occur I'd be a happy dude.

Thanks a ton for all your work and this awesome tool.

**Comment by jasonswearingen** [comment]
I do my own debug logging by hooking all the ```page.on``` events and ```.catch(err,fcn)``` promise api callbacks.  @patrickeakin does the ```DEBUG=``` provide you more details than that?     Or something the ```trace``` api doesn't provide?  (I haven't used ```DEBUG=``` or ```trace```, just curious)

**Comment by patrickeakin** [comment]
@jasonswearingen Thanks for the suggestion. I'll try that out and let you know if that does what I need.

**Comment by patrickeakin** [comment]
@jasonswearingen Thought you'd like to see an example of what I get when I log out page events in the way I described. Below is the output of a script where I go to Google, search for 'sup' and take a screenshot.

Output like this is really helpful when a before hook or something in my tests takes a 💩and I want to see where the hang up happened. 

```javascript
$ DEBUG='puppeteer:page' node puppeteerTest.js
  puppeteer:page page.setViewport({"width":"800","height":"600"}) +0ms
  puppeteer:page page.goto("https://google.com") +252ms
  puppeteer:page page.waitForSelector("input[aria-label=\"Search\"]") +876ms
  puppeteer:page page.mainFrame() +0ms
  puppeteer:page page.type("input[aria-label=\"Search\"]", "sup") +508ms
  puppeteer:page page.mainFrame() +1ms
  puppeteer:page page.click("input[value=\"Google Search\"]") +3s
  puppeteer:page page.mainFrame() +0ms
  puppeteer:page page.waitForSelector("#hdtb-msb") +1s
  puppeteer:page page.mainFrame() +0ms
  puppeteer:page page.screenshot({"path":"\"example.png\""}) +735ms
```

**Comment by patrickeakin** [comment]
@aslushnikov 

Using the `page.on` events doesn't appear to get me what I was getting by logging out `puppeteer:page`.

Here is some extra context.

Often the values I pass to puppeteer functions are variables. Some of these variables are functions that build the values dynamically depending on the specifics of the test. Much of this is stored in objects that are iterated over. Also, Puppeteer scripts are mostly broken out into reusable functions. The debug is valuable because I can see the value of these variables in sequence on any given run.

**Comment by aslushnikov** [comment]
@patrickeakin I see how this might be valuable for your case. The actual code that was doing this is not that involved, please see the f0beabd22a3908a7405b22b8e24e3c9295e1455b that was removing it.

In fact, you can run the same code on your side; it's actually quite easy:
1. Get our [`helper.js`](https://github.com/GoogleChrome/puppeteer/blob/d929f7e2137d2df6c1aa6d61e567f5e0fc0a578c/lib/helper.js) right before we dropped the public API logging (I linked the right one; just copy it). You can clean it up to drop everything but the `tracePublicAPI` method
2. In the very beginning of your scripts, proactively "trace" classes you care about:

```js
const helper = require('./myhelper'); // this is the helper from (1)
const {Page} = require('puppeteer/lib/Page.js'); // this is Puppeteer's Page
helper.tracePublicAPI(Page); // this will bring back the public API logging for you
```

I don't think we should resurrect this feature and ship it to everybody, but this should help for your case.
Let me know what you think.

**Comment by patrickeakin** [comment]
@aslushnikov That does the trick. Thanks a ton for your help. I really appreciate it.
