### ISSUE TITLE
No errors are thrown on asyncawait check.

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#3455]
**Origin of problem:** `puppeteer-web` on chrome extension.
**Source:** https://github.com/GoogleChrome/puppeteer/blob/master/index.js#L21
**Relevent Stackoverflow Question:** https://stackoverflow.com/q/53001009/6161265

The bundled version shows anonymous function, figuring out the problem wasn't smooth.

![image](https://user-images.githubusercontent.com/8284972/47606941-dcf88400-da3b-11e8-9b49-25c6e0f75896.png)

**Possible solutions:**
- It should notify the user somehow. Either by an argument or so in the browser.
- Let the user know about possible gimmicks of trying this inside chrome extension, which is to let `unsafe-eval` on content_security_policy of their `manifest.json` file.

```js
"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
```

**Comment by aslushnikov** [comment]
Thanks for letting us know. The lines you pointed to belong to our Node6 infrastructure. They will be removed once we [drop Node6 support](https://github.com/GoogleChrome/puppeteer/issues/3476), and thus the necessity of unsafe-eval will go away as well.

As another workaround, you can build a custom version for `puppeteer-web` that doesn't pull in the `index.js` with this bifurcation for node6/node7.

**Comment by sigleane** [comment]
Hey guys, im having this error..
Someone knows how to solve it?

npm run bundle
npm ERR! missing script: bundle
npm ERR!
npm ERR! Did you mean this?
npm ERR!     build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users[...]

**Comment by jackyzhang69** [comment]
> Hey guys, im having this error.. Someone knows how to solve it?
> 
> npm run bundle npm ERR! missing script: bundle npm ERR! npm ERR! Did you mean this? npm ERR! build
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users[...]

I have same issue. It seems that puppteer is not so popular in chrome extension. too less resources.

**Comment by yarekc** [comment]
Same issue: 

```
npm run bundle
npm ERR! missing script: bundle
npm ERR!
npm ERR! Did you mean this?
npm ERR!     build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-17T11_20_31_280Z-debug.log
```

**Comment by LuisMerinoP** [comment]
same error here.
I tried with [this](https://unpkg.com/puppeteer-web) puppeteer-web script from [this](https://stackoverflow.com/questions/54647694/how-to-run-puppeteer-code-in-any-web-browser) resurce but get this error:

`WebSocket connection to 'ws://0.0.0.0:8080/' failed: 
(anonymous) @ puppeteer-web:13354`

Is it possible then to run puppeteer on the browser?

**Comment by entrptaher** [comment]
puppeteer has updated their ways of running and there are better alternatives. Just running the script won't get you far. Let me find another way and update my old answers. :D

**Comment by LuisMerinoP** [comment]
Thanks for your comment! I was talking regarding the `npm run bundle` command error concretely (not running the script).  
As I could not have that done I tried this:

```
<script>
  const browser = await puppeteer.connect({
    browserWSEndpoint: `ws://0.0.0.0:8080, // <-- connect to a server running somewhere
    ignoreHTTPSErrors: true
  });

  const pagesCount = (await browser.pages()).length;
  const browserWSEndpoint = await browser.wsEndpoint();
  console.log({ browserWSEndpoint, pagesCount });
</script>
```

Previously setting a server like this:

```
const httpProxy = require("http-proxy");
const host = "0.0.0.0";
const port = 8080;

async function createServer(WSEndPoint, host, port) {
  await httpProxy
    .createServer({
      target: WSEndPoint, // where we are connecting
      ws: true,
      localAddress: host // where to bind the proxy
    })
    .listen(port); // which port the proxy should listen to
  return `ws://${host}:${port}`; // ie: ws://123.123.123.123:8080
}

const puppeteer = require("puppeteer");

puppeteer.launch().then(async browser=>{
  const pagesCount = (await browser.pages()).length; // just to make sure we have the same stuff on both place
  const browserWSEndpoint = await browser.wsEndpoint();
  const customWSEndpoint = await createServer(browserWSEndpoint, host, port); // create the server here
  console.log({ browserWSEndpoint, customWSEndpoint, pagesCount });
})
```

But did not succeed due to this error:

```
WebSocket connection to 'ws://0.0.0.0:8080/' failed: 
(anonymous) @ puppeteer-web:13354
```

I realize now that the answer where I got this code from in SO is also yours lol. I'll be thankful in case you have any comment to make this work :)
