### ISSUE TITLE
How does puppeteer resolve a domain

### ISSUE THREAD

**Issue by walkonthemarz** [puppeteer/puppeteer#3456]
I'm using puppeteer in an internal network, 
Puppeteer  connects to a remote chromium instance via a public ip：
```
....
const browser = puppeteer.connect({browserWSEndpoint:"ws://my.public.ip:9222/xxx"});
....
```
I'm trying to create a pdf of a page which is inside my internal network like this:
```
await page.goto('http://internal.example.com');
```
**http://internal.example.com** is not accessible for the chromium instance, 
will the script above works?

**Comment by walkonthemarz** [comment]
oh, it's not working.
It seems http://internal.example.co must be accessible for chromium

**Comment by JoelEinbinder** [comment]
No. The url is resolved on the Chromium side. Anything that can't be accessed by Chromium can't be accessed by Chromium.
