### ISSUE TITLE
Distinguishing between full page reloads and SPA hash navigations?

### ISSUE THREAD

**Issue by Madd0g** [puppeteer/puppeteer#3459]
I want to hook up to only real navigations (getting a whole new DOM).

The `framenavigated` event is triggered for hash changes (from /#/foo to /#/bar) now. I just upgraded to version 1.9.0 from an older version, I don't think it fired before.

Is there a way to distinguish between a full navigation and a hash navigation? I found [something about navigating within a document](https://github.com/GoogleChrome/puppeteer/blob/c237947b324338ece670b4f4e879880265ec6965/lib/FrameManager.js#L251) in the code and it seems like the answer is no.

I tried using this event, but it never fired:

```js
page.on('framenavigatedwithindocument', (frame) => {
});
```

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: macos 10.11.6
* URLs (if applicable):
* Node.js version: 9.8.0

**What steps will reproduce the problem?**

1. Attach handler to `framenavigated` but want to exclude hash navigations
2. Can't figure out how to do it

Is it possible to have a non-hash-navigation event? Or have some metadata about the event in `framenavigated`? 

Thank you

**Comment by aslushnikov** [comment]
@Madd0g for every network navigation you'll have a [`'request'`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-event-request) event that'll be marked as [`isNavigationRequest`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-requestisnavigationrequest); the navigation will be committed once the related [`response`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-event-response) event is emitted.

```js
page.on('response', async response => {
  if (response.request().isNavigationRequest() && response.ok()) {
    // Navigation is committed. Fetch body
    const body = await response.text();
    // ...
  }
});
```

Will it help for your usecase?

**Comment by Madd0g** [comment]
Yes, seems like it should be possible to replace my `framenavigated` logic with this, I'll try. Thanks.

For my test I need to do some cleanup when switching from a real page to a real page, but not when navigating inside the page using client-side routing.

Looking at network events for this type of thing feels a bit weird, I feel like having a way to distinguish these 2 types of navigation using the page events would be better.

Thanks

**Comment by aslushnikov** [comment]
> Looking at network events for this type of thing feels a bit weird, I feel like having a way to distinguish these 2 types of navigation using the page events would be better.

@Madd0g yeah it does feel a bit awkward, but that's essentially what's going on inside browser.

If there's more demand for this, we can introduce `frame.navigationHistory()` that'll hold an array of "navigations", each with a URL and a navigation type it was generated.

I'll close this for now; let me know if I can help with anything else.
