### ISSUE TITLE
[Feature request] quality for page.screenshot() should not throw error

### ISSUE THREAD

**Issue by cossssmin** [puppeteer/puppeteer#3460]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: Windows 10, OSX Mojave
* URLs (if applicable): -
* Node.js version: v8.9.4

In my setup, [I send a call to Puppeteer](https://github.com/ThemeMountain/maizzle/blob/master/tasks/js/screenshot.js#L68-L121) based on a user [config](https://github.com/ThemeMountain/maizzle/blob/fix-screenshots/config.php#L139-L146).

The config looks like this:

```php
'screenshots' => [
    'devices' => [
        'iPad Mini',
        'iPhone 6',
    ],
    'type' => 'png',
    'quality' => 100,
],
```

Because Puppeteer throws an error when you set the `quality` while using `png`, I can't rely on config to create screenshots. So I can't have something automated like this:

```js
// screenshots object is the array above

await page.screenshot({
  path: 'my/path/to/file.' + screenshots.type
),
quality: screenshots.type.match(/jpe?g/) ? screenshots.quality : false, // or undefined or null or whatever instead of false
fullPage: true
});
```

Instead, I have to do a [silly workaround](https://github.com/ThemeMountain/maizzle/blob/master/tasks/js/screenshot.js#L86-L119) where I check what they set `type` to, and do an if-else based on that.

**Would it be possible for Puppeteer to simply discard/not take into consideration at all the `quality` option if `type` is `png`, instead of throwing an error?**

P.S.: apologies if this this impacts something else and I should have known better - I tried searching the docs and issues, but couldn't find anything.

P.P.S: I totally understand I could not provide the `quality` option and default to `png`, and then documenting the `quality` option as 'to be used only with `jpg`' - just that in this case, it would have to default to whatever JPG `quality` is if you don't set it in `page.screenshot()` (undocumented?)... If the maintainers think my request is not possible or a bad idea, I guess this is what I'll have to start doing... :)

Thanks!

**Comment by aslushnikov** [comment]
> Because Puppeteer throws an error when you set the quality while using png, I can't rely on config to create screenshots. So I can't have something automated like this:

@hellocosmin You should be able to pass `undefined` for quality in case of `png` images; the following works fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://example.com');
  await page.screenshot({
    path: 'example.png',
    quality: undefined,
  });
  await browser.close();
})();
```

Let me know if it doesn't!

**Comment by cossssmin** [comment]
Doesn't work for me, I get this when setting `quality` to be  `undefined`:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Unsupported screenshot mime type: null
(node:14704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

... and the process doesn't exit.

**Comment by aslushnikov** [comment]
@hellocosmin hmm, what's not working for you - the script I posted or something else that tries to reuse this technique?
