### ISSUE TITLE
Can't run puppeteer in headless mode when I set ignoreDefaultArgs as true

### ISSUE THREAD

**Issue by tmkaio** [puppeteer/puppeteer#3462]
Platform / OS version: Windows 10
Node.js version: v8.11.3

I am using the code below, but when I set ignoreDefaultArgs as true, then it opens the chrome in non headless mode even if headless is true. If I set ignoreDefaultArgs as false, then it works fine on headless mode.

`puppeteer.launch({
    ignoreDefaultArgs: true,
    headless: true
})
.then((browser) => {
    browser.newPage()
        .then((page) => {
            page.goto('https://www.google.com');
        });
    }); 
});`

**Comment by JoelEinbinder** [comment]
If you set `ignoreDefaultArgs` to true, it ignores the args that would setup headless mode. You need to build your own array of arguments and pass them into the `args` option. See https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-puppeteerdefaultargsoptions
