### ISSUE TITLE
//select country, ajax call   await page.waitForSelector('input[data-short="my"]')   await page.click('input[data-short="my"]')    await page.waitForResponse()    //no effect here? I'm sure my selector is correct   await page.click('#sku_number')   await page.keyboard.type('123')

### ISSUE THREAD

**Issue by thian4** [puppeteer/puppeteer#3465]
//select country, ajax call
  await page.waitForSelector('input[data-short="usa"]')
  await page.click('input[data-short="usa"]')

  await page.waitForResponse()

  //no effect here? I'm sure my selector is correct
  await page.click('#sku_number')
  await page.keyboard.type('123')

**What is the expected result?**
I expect `waitForResponse()` can check after the ajax call is finished. I tried also`waitForSelector('#sku_number')`, nothing worked. I also tried await page.waitFor(1000) but `'input[data-short="usa"]'` is not getting clicked.

**What happens instead?**
#sku_number is not clicked

**Comment by nicoandmee** [comment]
what do you expect to happen? examining each statement-
`waitFor(1000)` - you sit idle on the on the page for a full second.
`waitForSelector()` - you should consider using a timeout here to be safe, and specifying visibility. Or find a better way (such as by intercepting the postback over the network) to determine when the ajax call is finished. 

Here is a handy method/wrapper I use to 'select' options from dropdowns, hope it helps you.

`  async $select(q, opt) {
    if (!opt) return false;

    const elementHandle = await this.page.$(q);
    await this.clickElementHandle(elementHandle);
    await wait(1500);
    await this.page.keyboard.type(opt, { delay: 20 + (Math.random() * (5)) });
    await this.page.keyboard.press('Enter');
    return true;
  }
`

**Comment by aslushnikov** [comment]
> I expect waitForResponse() can check after the ajax call is finished.

@thian4 `waitForResponse` awaits response *in future*, so if the response has already happened - then the method will wait forever.

I can't say anything else regarding this. Please, re-file with a good repro steps so that we can reproduce the problem locally and see what's going on.
