### ISSUE TITLE
./chrome: /usr/lib/x86_64-linux-gnu/libnss3.so: version `NSS_3.22' not found (required by ./chrome)

### ISSUE THREAD

**Issue by xiaoyuhen** [puppeteer/puppeteer#3467]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version:  Debian GNU/Linux 8
* Node.js version:  8.9.1

**What steps will reproduce the problem?**

1. Create this test file
```
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch({userDataDir: 'some/path', args: ['--no-sandbox', '--disable-setuid-sandbox']});
const page = await browser.newPage();
await page.goto('https://example.com');
await page.screenshot({path: 'example.png'});
browser.close();
})();
```
2. run ldd chrome | grep not on a Linux machine to check which dependencies are missing
```
ldd chrome | grep no
```
```
./chrome: /usr/lib/x86_64-linux-gnu/libnss3.so: version `NSS_3.22' not found (required by ./chrome)
```

3. try install NSS.3.22 and not work
```
apt-get install libnss3
```
4. Try to run it inside the container
```
node test.js
```

**What is the expected result?**
I expect normal execution

**What happens instead?**
```
Determining test suites to run...
Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/data/apps/consultation/node_modules/puppeteer/lib/Launcher.js:339:14)
    at ChildProcess.helper.addEventListener (/data/apps/consultation/node_modules/puppeteer/lib/Launcher.js:329:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by aslushnikov** [comment]
It's hard to say what's going on here for sure - environment issues are always tricky. A few things that
might help:
- We had similar issues with Travis, and installing `libnss3` helped us - see our [`.travis.yml`](https://github.com/GoogleChrome/puppeteer/blob/master/.travis.yml).
- If you're running docker, here's a [Dockerfile](https://github.com/GoogleChrome/puppeteer/blob/master/.ci/node8/Dockerfile.linux) that we use to run builds on Cirrus Ci; it installs `libnss3` as well and then works fine.
- Also, there's a list of dependencies in our [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) - this might help as well.
