### ISSUE TITLE
Issue with negative top(absolute element) when generate PDF

### ISSUE THREAD

**Issue by hejinjun** [puppeteer/puppeteer#3468]
### Steps to reproduce

* Puppeteer version: 1.9.0
* Platform / OS version: OSX Mojave
* Node.js version: v8.12.0

**What steps will reproduce the problem?**
1. create a html file
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    @page {
      size: 794px 1123px;
      margin: 0;
      overflow: hidden;
    }

    @media print {
      .page {
        page-break-after: always;
      }
    }

    .page {
      width: 794px;
      height: 1120px;
      position: relative;
      overflow: hidden;
    }

    .page>div {
      width: 200px;
      height: 200px;
      font-size: 160px;
      position: absolute;
      top: 0;
      left: 0;
    }

    .page .negative-top {
      top: -120px;
    }

    .page .ok {
      background: greenyellow;
    }

    .page .problem {
      background: red;
      color: #ffffff;
    }

  </style>
</head>

<body>
  <div class="page">
    <div class="negative-top ok">1</div>
  </div>
  <div class="page">
    <div class="negative-top problem">2</div>
  </div>
  <div class="page">
    <div class="negative-top problem">3</div>
  </div>
</body>

</html>

```
2. generate a PDF file
```js
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('html file url', { waitUntil: 'networkidle0' })
await page.pdf({
    path: 'test.pdf',
    printBackground: true,
    preferCSSPageSize: true,
})
await browser.close()
```

3. open the test.pdf  then find the difference between pdf and html in page 2 & 3, page one is render correct.

**What is the expected result?**
PDF file should render the absolute element  same as the chrome browser 

**What happens instead?**
page one render same as the browser, start from the page 2, absolute element's children is render not correct

**Browser output**
![browser render](https://user-images.githubusercontent.com/2560843/47726294-2b548f80-dc95-11e8-8e4b-fdb44ac0f530.png)

***

**PDF output**
![puppeteer pdf  render](https://user-images.githubusercontent.com/2560843/47726279-1d067380-dc95-11e8-94a1-605626fc71fe.png)

**Comment by hejinjun** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=900825&can=2&start=0&num=100&q=print%20preview&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20OS%20Area%20Feature%20Status%20Owner%20Summary

**Comment by aslushnikov** [comment]
@hejinjun thanks for filing upstream!

**Comment by aslushnikov** [comment]
Closing this in favor of upstream bug.
