### ISSUE TITLE
 page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: './tmp/order'}) causing error

### ISSUE THREAD

**Issue by emclab** [puppeteer/puppeteer#3473]
I can `download` the file to the default subdir which is the `download` by. 

    await page.goto('https://www.mysite-com/admin/order?_export_=page%3A1');

However when I specified the download subdir with the following code,  the file is still downloaded to the default subdir and with error:

    await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: './tmp/order'});

The error is:

    Error: net::ERR_ABORTED at https://www.mysite-com/admin/order?_export_=page%3A1
    <     at navigate (C:\code\js\wbot\node_modules\puppeteer\lib\FrameManager.js:103:37)
    <     at <anonymous>
    <     at process._tickCallback (internal/process/next_tick.js:189:7)

 Puppeteer is `1.9.0`. Is it bug?

**Comment by aslushnikov** [comment]
@emclab two things here:
- the `page.setDownloadBehavior` is an experimental [DevTools Protocol method](https://vanilla.aslushnikov.com/#Page.setDownloadBehavior); it's not well supported.
- the error you get is the default error Chrome Headless returns when you it's navigated to a downloadable resource; we'll straighten this up as part of #299.

We'll move to the proper downloads using [response interception](https://vanilla.aslushnikov.com/#Network.getResponseBodyForInterception) once #3471 is fixed; please follow #299 for the updates.

Sorry for the inconvenience!

**Comment by spadkins** [comment]
You might try using an absolute path instead of a relative path.

Also, I am running on Windows from a MinGW64 bash command line, but because the path was going to be passed to an instance of Chrome for Windows, I took care to pass an absolute path that looked right for Windows (e.g. "C:\dev\downloads" or whatever).

(Using process.cwd() along with the "path" npm module took care of the details for me.)
let dir = path.join(process.cwd(), "path", "to", "download", "dir");

**Comment by azazrehman** [comment]
If there is error on file which you want to download then try this one:

const myDownloadPath = path.resolve(${Directory Where you want to download})
mkdirp(myDownloadPath)
await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: myDownloadPath });

imported: 
const mkdirp = require('mkdirp')
const path = require('path')
