### ISSUE TITLE
Drop Node6

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#3476]
When we were releasing in 2017, Node 6 was used by default on AWS and Google Cloud.
Node6 support doesn't come for free:
- Since Puppeteer operates in two contexts - browser and node.js - common transpilers cannot handle Puppeteer transpilation. We implemented [a custom one](https://github.com/GoogleChrome/puppeteer/tree/master/utils/node6-transform) and maintain it occasionally.
- Since our code is so different for Node6 wrt Node8, we have to maintain a separate CI for it
- We ship both transpiled and non-transpiled versions of Puppeteer code to npm - more than doubling package size
- There are occasional issues with Node6 here and there, e.g. https://github.com/GoogleChrome/puppeteer/issues/3455. 
- Certain features like ["async stacks"](https://github.com/GoogleChrome/puppeteer/commit/0b9d8a62717ddf5d77a0ca6d6bacf8d734054853) don't work with Node6 at all.

Nowadays, both AWS and Google Cloud support Node 8, so Node 6 doesn't look like a must for us.

Node6 is getting end-of-lifed in [April 2019](https://nodejs.org/en/blog/release/v6.9.0/), but I'm starting this thread to see if we can drop Node6 support earlier to cut on our overall complexity. Feel free to jump in and let us know what you think.

**Comment by aslushnikov** [comment]
@ebidel, @JoelEinbinder: let me know what you guys think.

**Comment by jasonswearingen** [comment]
Since node moved to 10.x as LTS, I think supporting the last two LTS's is "enough".  Maybe just make a note on the troubleshooting page as to what the last version supporting node 6.x was.

**Comment by ebidel** [comment]
I'm fine with dropping node 6 given most of the big providers offer node 8 options.

Good idea @jasonswearingen.

**Comment by JoelEinbinder** [comment]
I’m fine with dropping it at 2.0.

**Comment by ebidel** [comment]
+1. This should be part of 2.0.
