### ISSUE TITLE
Error on install weird error 8

### ISSUE THREAD

**Issue by impactcolor** [puppeteer/puppeteer#3479]
I'm currently running node v 0.10.48 
I then run npm i puppeteer

This is the error I get:
> puppeteer@1.9.0 install /home/citylocs255/public_html/preview/node_modules/puppeteer
> node install.js

/home/citylocs255/public_html/preview/node_modules/puppeteer/install.js:61
    .then(() => browserFetcher.localRevisions())
           ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! weird error 8
npm ERR! not ok code 0

Any help will be greatly appreciated!

**Comment by aslushnikov** [comment]
Node 0.10.48 is very old; you should use at least node 6 for puppeteer (or better node 8). Check out the requirements in our [readme](https://github.com/GoogleChrome/puppeteer#usage).

**Comment by syslogic** [comment]
Actually, version `0.10.48` is NodeJS 10, which is newer than NodeJS 6 and 8.

```
D:\>npm install -g puppeteer
npm WARN engine puppeteer@1.20.0: wanted: {"node":">=6.4.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine https-proxy-agent@2.2.2: wanted: {"node":">= 4.5.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine mime@2.4.4: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
npm WARN engine agent-base@4.3.0: wanted: {"node":">= 4.0.0"} (current: {"node":"0.10.33","npm":"1.4.28"})
```

This can be easily reproduced on any Windows machine with freshly installed NodeJS `10.16.3`.

Downgrading to [NodeJS 8](https://nodejs.org/dist/latest-v8.x/) circumvents the issue.
