### ISSUE TITLE
How to click on an element by name?

### ISSUE THREAD

**Issue by zolaahihi** [puppeteer/puppeteer#3484]
Hello,

How can I click on a element by name, for example

<button data="success"></button>
<button run="no"></button>

I want to click on button with data="success"

Thanks,

**Comment by vsemozhetbyt** [comment]
You can use [Attribute selectors](https://drafts.csswg.org/selectors-4/#attribute-selectors), like `[data="success"]`. Example with clicking on a link:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const element = await page.$('[href="http://www.iana.org/domains/example"]');
    await element.click();
  } catch (err) {
    console.error(err);
  }
})();
```
