### ISSUE TITLE
The "click" method triggers the opening of the new page, the browser window sometimes pops up.

### ISSUE THREAD

**Issue by aixinalei** [puppeteer/puppeteer#3485]
Minimize browser window，When the "click" method triggers the opening of the new page, the browser window sometimes pops up.How should I stop them？

**Comment by aslushnikov** [comment]
@aixinalei our solution to this kind of problems is headless mode, so I'd recommend running headless as much as possible. In cases when it doesn't work for you (e.g. testing extensions), I'd recommend using 
 [`xvfb`](https://en.wikipedia.org/wiki/Xvfb).

Hope this helps.
