### ISSUE TITLE
Concatenated string is not working in the selector

### ISSUE THREAD

**Issue by Hemanthvinayac** [puppeteer/puppeteer#3486]
Concatenated string is not working in the selector,
await page.evaluate(() => document.evaluate('//*[@id="domainControl_membersTable_1539794192@aquera.com"]/td[1]/input', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.click());
above thing works fine but,
await page.evaluate(variable_2,(variable_2) => document.evaluate(variable_2, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.click()); is not working

can someone help

**Comment by vsemozhetbyt** [comment]
`variable_2` should be the second parameter in the `page.evaluate()`, not the first. See [`page.evaluate()` signature](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args).

**Comment by Hemanthvinayac** [comment]
I tried got below error
 TypeError: Cannot read property 'click' of null

**Comment by vsemozhetbyt** [comment]
I cannot reproduce the issue with this code:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const xpath = '//*[@href="http://www.iana.org/domains/example"]';
    await page.evaluate(
      (xpath) => {
        document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null)
                .singleNodeValue.click();
      },
      xpath
    );

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
The link is successfully clicked.

**Comment by Hemanthvinayac** [comment]
Works fine, thank you
