### ISSUE TITLE
Problem with WebSocketTransport.js

### ISSUE THREAD

**Issue by varave** [puppeteer/puppeteer#3487]
* Puppeteer version: v1.10.0
* Platform / OS version: Windows 7 (x64)
* Node.js version: v10.13.0

1. install a puppeteer in the project
2. try to run a project (npm run serve)
3. an error:
```
This dependency was not found:
* ws in ./node_modules/puppeteer/lib/WebSocketTransport.js
To install it, you can run: npm install --save ws
```
**in fact, this dependence is established.**

![default](https://user-images.githubusercontent.com/16765830/47923283-101e9580-deca-11e8-9004-bfd141ef1bce.JPG)

**Comment by aslushnikov** [comment]
weird; try removing `node_modules` and running install another time? I don't see any reason why `ws` is not installed.

**Comment by PeterKnight** [comment]
I'm having the same problem, did you find a way through this @inweid?

**Comment by varave** [comment]
@PeterKnight, update the node js version, I don’t remember, but it seems it helped me

**Comment by gustavojmarrero** [comment]
> @PeterKnight, update the node js version, I don’t remember, but it seems it helped me
Hello, I had the same problem and i resolved  excuted npm install --save ws and changed the path in the file WebSocketTransport.js
const WebSocket = require('../node_modules/ws');

**Comment by RonchettiAssociati** [comment]
I think I have the same issue here. Trying to use puppeteer-core with a vuejs/quasar app.

I have updated node, npm, etc to the latest versions.  package.json says:
    "puppeteer-core": "^1.13.0",
    "ws": "^6.2.0"

My directories are     
  erp2/node-modules/puppeteer-core  
  erp2/node_modules/ws

but I get 
  This dependency was not found:
  * ws in ./node_modules/puppeteer-core/lib/WebSocketTransport.js

**Comment by sunnyYanan** [comment]
I still have the same problem, can u pls reopen it?

> weird; try removing `node_modules` and running install another time? I don't see any reason why `ws` is not installed.

**Comment by bobbybobby** [comment]
I have the same issue. I run `jest __integration__/my.spec.js` with the dummy test file below : 

**my.spec.js**

```js
const puppeteer = require('puppeteer');

describe('H1 Text', () => {
  test('h1 loads correctly', () => {
    expect(1).toEqual(1);
  });
});
```

The result is : 

```
 FAIL  __integration__/my.spec.js
  ● Test suite failed to run

    Cannot find module 'ws' from 'WebSocketTransport.js'

    However, Jest was able to find:
    	'./WebSocketTransport.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./Launcher.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./Puppeteer.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'lib/api.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:202:17)
      at Object.<anonymous> (../../node_modules/puppeteer/lib/WebSocketTransport.js:16:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.269s
Ran all test suites matching /__integration__\/my.spec.js/i.

```

Looking at the file `node_modules/puppeteer/package.json`, I see there is a `"browser"` entry, as below : 

```json

{
  "name": "puppeteer",
  "version": "1.13.0",
  "description": "A high-level API to control headless Chrome over the DevTools Protocol",
  "main": "index.js",
  "repository": "github:GoogleChrome/puppeteer",
  "engines": {
    "node": ">=6.4.0"
  },
  "puppeteer": {
    "chromium_revision": "637110"
  },
  "scripts": {
    [...]
  },
  "author": "The Chromium Authors",
  "license": "Apache-2.0",
  "dependencies": {
    [...]
    "ws": "^6.1.0"
  },
  "devDependencies": {
    [...]
  },
  "browser": {
    "./lib/BrowserFetcher.js": false,
    "./node6/lib/Puppeteer": false,
    "ws": "./utils/browser/WebSocket",
    "fs": false,
    "child_process": false,
    "rimraf": false,
    "readline": false
  }
}
```

Two observations from that : 

- Getting rid of the `"browser"` entry, (or just of the `"ws"` entry within it), makes the import work. However I have no idea why this influence node `require()` behavior. As I understand it, this field should only be used by bundlers, like Webpack, when targetting a browser environment.
- I don't understand the path `"./utils/browser/WebSocket"`  provided as a replacement for `ws` in case of a browser environment, since there is no such file in the puppeteer package. 

As a temporary solution, I reverted to version `~1.8.0` of puppeteer, before the introduction of that `"browser"` field.

**Comment by aslushnikov** [comment]
> I don't understand the path "./utils/browser/WebSocket" provided as a replacement for ws in case of a browser environment, since there is no such file in the puppeteer package.

@bobbybobby Please read [utils/browser/README.md](https://github.com/GoogleChrome/puppeteer/tree/master/utils/browser/README.md).

**Comment by sunchenggit** [comment]
正常使用puppeteer是完全没有问题的，但是当我在使用vue-cli3创建的项目中使用puppeteer的时候，就会提示这个错误。我同样运行了npm install --save ws 这个命令，但是依旧不起作用。

**Comment by 1254859753** [comment]
@sunchenggit 请问你有没有解决这个问题呢

**Comment by Anahkiasen** [comment]
Having this issue as well, I don't understand the `ws` path either

**Comment by KingGanZeng** [comment]
- Puppeteer version: v1.18.1
- Platform / OS version: Mac OS 10.14
- Node.js version: v8.9.0
- vue cli3

I have the same issue. I have tried the following solutions, but they have not taken effect.
-[x]  delete node_modules and reload, stiil has error
-[x]  `npm install ws`, still has error
-[x]  try higher node version, not work

dose any one has a really useful solution?

**Comment by he5310** [comment]
the problem is  puppeteer and vue-cli has conficts in ws version
1. rm -rf ws in node_modules
2.yarn add ws@6.1.4 (or npm install ws@6.1.4 --save)

**Comment by KingGanZeng** [comment]
@he5310 it doesn't work.

**Comment by KingGanZeng** [comment]
> @sunchenggit 请问你有没有解决这个问题呢

@1254859753 使用npm正常安装好ws依赖之后，删除node_modules/puppeteer/package.json中的这一行就可以正常运行了
```
...
"browser": {
...
    "ws": "./utils/browser/WebSocket",
...
```

**Comment by clinyong** [comment]
> I have the same issue. I run `jest __integration__/my.spec.js` with the dummy test file below :
> 
> **my.spec.js**
> 
> ```js
> const puppeteer = require('puppeteer');
> 
> describe('H1 Text', () => {
>   test('h1 loads correctly', () => {
>     expect(1).toEqual(1);
>   });
> });
> ```
> 
> The result is :
> 
> ```
>  FAIL  __integration__/my.spec.js
>   ● Test suite failed to run
> 
>     Cannot find module 'ws' from 'WebSocketTransport.js'
> 
>     However, Jest was able to find:
>     	'./WebSocketTransport.js'
> 
>     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
> 
>     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
> 
>     However, Jest was able to find:
>     	'./Launcher.js'
> 
>     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
> 
>     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
> 
>     However, Jest was able to find:
>     	'./Puppeteer.js'
> 
>     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
> 
>     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
> 
>     However, Jest was able to find:
>     	'lib/api.js'
> 
>     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
> 
>     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
> 
>       at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:202:17)
>       at Object.<anonymous> (../../node_modules/puppeteer/lib/WebSocketTransport.js:16:19)
> 
> Test Suites: 1 failed, 1 total
> Tests:       0 total
> Snapshots:   0 total
> Time:        1.269s
> Ran all test suites matching /__integration__\/my.spec.js/i.
> ```
> 
> Looking at the file `node_modules/puppeteer/package.json`, I see there is a `"browser"` entry, as below :
> 
> ```json
> {
>   "name": "puppeteer",
>   "version": "1.13.0",
>   "description": "A high-level API to control headless Chrome over the DevTools Protocol",
>   "main": "index.js",
>   "repository": "github:GoogleChrome/puppeteer",
>   "engines": {
>     "node": ">=6.4.0"
>   },
>   "puppeteer": {
>     "chromium_revision": "637110"
>   },
>   "scripts": {
>     [...]
>   },
>   "author": "The Chromium Authors",
>   "license": "Apache-2.0",
>   "dependencies": {
>     [...]
>     "ws": "^6.1.0"
>   },
>   "devDependencies": {
>     [...]
>   },
>   "browser": {
>     "./lib/BrowserFetcher.js": false,
>     "./node6/lib/Puppeteer": false,
>     "ws": "./utils/browser/WebSocket",
>     "fs": false,
>     "child_process": false,
>     "rimraf": false,
>     "readline": false
>   }
> }
> ```
> 
> Two observations from that :
> 
> * Getting rid of the `"browser"` entry, (or just of the `"ws"` entry within it), makes the import work. However I have no idea why this influence node `require()` behavior. As I understand it, this field should only be used by bundlers, like Webpack, when targetting a browser environment.
> * I don't understand the path `"./utils/browser/WebSocket"`  provided as a replacement for `ws` in case of a browser environment, since there is no such file in the puppeteer package.
> 
> As a temporary solution, I reverted to version `~1.8.0` of puppeteer, before the introduction of that `"browser"` field.

I am running jest and have the same problem. You can try changing the jest [browser](https://jestjs.io/docs/en/configuration#browser-boolean) field to `false`.

**Comment by chenzhtbb** [comment]
I'm having the same problem, and it was fixed.
Create a new file './node_modules/puppeteer/utils/browser/WebSocket.js'
```javascript
module.exports = window.WebSocket;
```

**Comment by anyishxyi** [comment]
it doesn't really work. that will launch the application but the module concerned will not load. And I have this error

```
such module. (Possibly not yet loaded)
    at Object.push../node_modules/node-libs-browser/mock/process.js.exports.binding (process.js:17)
```

**Comment by itwaze** [comment]
inside your project `node_modules/puppeteer/lib/WebSocketTransport.js` need to change:
from `const WebSocket = require('ws');`
to `const WebSocket = require('../node_modules/ws/index');`

**Comment by oussama-taoufiq** [comment]
I'm having the same problem.
inside my project node_modules/puppeteer/lib/WebSocketTransport.js I change:
const WebSocket = require('ws');
to const WebSocket = require('../node_modules/ws/index');
but now I have another error : 
    TypeError: BrowserFetcher is not a constructor
      at resolveExecutablePath (node_modules/puppeteer/lib/Launcher.js:688:28)
      at ChromeLauncher.launch (node_modules/puppeteer/lib/Launcher.js:198:53)

**Comment by Micheltpd** [comment]
I have the same problemn.

**Comment by simple-YoungBadBoy** [comment]
> 我有同样的问题。
> 在我的项目node_modules / puppeteer / lib / WebSocketTransport.js中，我更改了：
> const WebSocket = require（'ws'）;
> 到const WebSocket = require（'../ node_modules / ws / index'）;
> 但现在我又 遇到一个错误：
> TypeError：BrowserFetcher不是
> ChromeLauncher.launch（node_modules /
> puppeteer / lib / Launcher.js：198：53）上resolveExecutablePath（node_modules / puppeteer / lib / Launcher.js：688：28）的构造函数

me too,If you solve it, please let me know

**Comment by JakubDylag** [comment]
inside node_modules/lib/cjs/common/WebSocketTransport.js
the original line is: `const ws_1 = __importDefault(require("ws"));`
changing this to: `const ws_1 = require("../node_modules/ws/index.js");`
does not solve the problem

**Comment by Jayboy75** [comment]
Same issue here.

**Comment by Naresh-Khatri** [comment]
Did anyone find a solution to this?

**Comment by danniel-isiah-libor** [comment]
any fix for this?

**Comment by batyr-qhan** [comment]
> > @PeterKnight, update the node js version, I don’t remember, but it seems it helped me
> > Hello, I had the same problem and i resolved  excuted npm install --save ws and changed the path in the file WebSocketTransport.js
> > const WebSocket = require('../node_modules/ws');

this helped sooo much. So simple and took so much time.

**Comment by bogdan19981305** [comment]
> I'm having the same problem.
> inside my project node_modules/puppeteer/lib/WebSocketTransport.js I change:
> const WebSocket = require('ws');
> to const WebSocket = require('../node_modules/ws/index');
> but now I have another error :
> TypeError: BrowserFetcher is not a constructor
> at resolveExecutablePath (node_modules/puppeteer/lib/Launcher.js:688:28)
> at ChromeLauncher.launch (node_modules/puppeteer/lib/Launcher.js:198:53)

it worked for me thnx!!!👌
