### ISSUE TITLE
Does not seem to work with headless mode

### ISSUE THREAD

**Issue by sarfraznawaz2005** [puppeteer/puppeteer#3490]
This is related to issue #921 which is now closed, however I am still experiencing this problem. In headless mode, it still does not seem to work.

* Puppeteer version: 1.10.0
* Platform / OS version: Windows 10 x64
* Node.js version: 8.9.1

Here is the entire code:

```javascript
const puppeteer = require('puppeteer');

(async function main() {

    const browser = await puppeteer.launch({
        headless: true,
        userDataDir: "./tmp",
        args: [
            '--disable-infobars',
            '--window-position=0,0',
            '--ignore-certificate-errors',
            '--ignore-certificate-errors-spki-list'
        ]
    });

    console.log("going to page");

    const page = await browser.newPage();

    console.log("created new page");

    page.goto('https://web.whatsapp.com/', {
        waitUntil: 'networkidle2',
        timeout: 0
    }).then(async function (response) {

        console.log("opened site");

        await page.waitFor(30000);

        console.log(await page.content());

        await page.screenshot({
            path: 'test.png'
        });

        await browser.close();
    })

})();
```

This works fine, site loads fine and I can do everything fine. The `tmp` user directory is also filled with stuff after running above code with `headless` set to `false`. But as soon as I set `headless` to `true` while keeping `tmp` directory intact with previous session, it just loads blank page, seems like nothing gets called after statement `const page = await browser.newPage()` because last message I see on screen is just `going to page`.

Came to know about using absolute path so I tried using `userDataDir: "C:\\Dev\\tmp"` too but in this case, response is `<html><head></head><body></body></html>` and screen generated is white empty one. The expected result is to see whatsapp web scan qrcode page.

Thanks

**Comment by wildlyinaccurate** [comment]
I have this issue regardless of headless mode or not. It seems like the first `.goto()` call is ignored (Chromium stays on about:blank) but making a second `.goto()` call with the same parameters begins navigation as expected.

Puppeteer version: 1.10.0
Platform / OS version: Ubuntu Linux 18.10 / 4.18.0-10-generic
Node.js version: 10.6.0
Chromium version: 72.0.3582.0 (linux-599821)

**Comment by sarfraznawaz2005** [comment]
@wildlyinaccurate For me on Win10 x64, even that doesn't work. I can make it pass beyond new page by specifying absolute url but then it does not go to actual url and yields empty page.

**Comment by aslushnikov** [comment]
While #921 got fixed, there's still no 100% interop between headless and headful profiles:
- #1268 - Headless can't read LocalStorage written from Headful
- #1270 - Headless can't read indexedDB written from Headful and vice versa

I'd expect certain things to be falling apart while these things aren't fixed. Also, It might be that whatsapp has some headless checks in place to prevent automation - these fall outside of the scope of the project.

Closing this in favor of #1268 and #1270 - please upvote those to stay in the loop.
