### ISSUE TITLE
Enabling CDP CSS debugging gets stuck in non-headless mode

### ISSUE THREAD

**Issue by Madd0g** [puppeteer/puppeteer#3494]
CDP `client.send('CSS.enable')` gets stuck in non-headless mode. If I press Enter in the browser window, then it comes to life and the code continues to run.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: OSX 10.11.6
* URLs (if applicable):
* Node.js version: 9.8.0

**What steps will reproduce the problem?**

```js
// Creating non-headless browser
let browser = await puppeteer.launch({
    headless: false, // removing this solves the problem
});
let page = await browser.newPage();
let client = await page.target().createCDPSession();
await client.send('DOM.enable');
await client.send('CSS.enable'); // <--- gets stuck
```

**What is the expected result?**
The promise should resolve.

**What happens instead?**
It gets stuck forever or until Enter is pressed in the chromium address bar.

**Comment by aslushnikov** [comment]
I can't reproduce this on v1.11.0, the following works just fine for me on OSX:

```js
const puppeteer = require('puppeteer');

(async() => {
    // Creating non-headless browser
  let browser = await puppeteer.launch({
      headless: false, // removing this solves the problem
  });
  let page = await browser.newPage();
  let client = await page.target().createCDPSession();
  await client.send('DOM.enable');
  console.log('before');
  await client.send('CSS.enable'); // <--- does not get stuck
  console.log('after'); // <--- gets printed out
})();
```

**Comment by pyatyispyatil** [comment]
I have the same problem, but `CSS.enable` is also stuck in headless mode. And because of this I can not write CSS coverage.
