### ISSUE TITLE
ElementHandle click method get Error: Node is detached from document

### ISSUE THREAD

**Issue by jeudesprits** [puppeteer/puppeteer#3496]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: Ubuntu 18.04.1 LTS
* URLs (if applicable): -
* Node.js version: v11.0.0

**What steps will reproduce the problem?**

 _Launch Code_:
```ts
(async () => {
  const browser = await puppeteer.launch({
    userDataDir: `${__dirname}/../chromium`,
    args: [
      '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36'
    ],
    defaultViewport: {
      width: 1680,
      height: 1050,
    },
  });

  ...
```

_Main Code_:
```ts
export async function followersFollow(page: puppeteer.Page, counter: IFollowersLimit) {
  if (!( await page.$(selectors.profileFollowersButton))) {
    return;
  }

  await page.click(selectors.profileFollowersButton);
  await timeout(2000);

  const internalCounter: IFollowersLimit = { limit: 5 };
  await page.waitForSelector(selectors.profileFollowersWindow);
  await page.evaluate(() => {
    document!.querySelector('div.isgrP')!.scrollTop = document!.querySelector('div.isgrP')!.scrollHeight;
    document!.querySelector('div.isgrP')!.scrollTop = 0;
  })
  await timeout(2000);

  const profileFollowers = await page.$$(selectors.profileFollowersList);
  console.log('Count   : ', profileFollowers.length);
  for (const follower of profileFollowers) {
    if (!internalCounter.limit) {
      break;
    }

    const isFollowed: boolean = await page.evaluate(
      ($follower) => $follower.querySelector('button').textContent !== 'Follow',
      follower,
    );
    if (isFollowed) {
      continue;
    }


    const isFollowBack: boolean = await page.evaluate(
      ($follower) => $follower.querySelector('button').textContent === 'Follow Back',
      follower,
    );
    if (isFollowBack) {
      continue;
    }

    const content: string = await page.evaluate(
      ($follower) => $follower.querySelector('button').textContent,
      follower,
    );
    console.log(content);
    const button = await follower.$('button');
    if (!button) {
      continue;
    }
    const href: string = await page.evaluate(
     ($follower) => $follower.querySelector('a').href,
     follower
    );
    console.log('          ', href);
    await button.click(); // <==== THIS METHOD THROW ERROR
    await button.dispose();
    await timeout(2000);
    console.log('👍');
    await addUser(href);
    --internalCounter.limit;
    --counter.limit;
    await follower.dispose();
  }
```

**What is the expected result?**

Going through all the elements in the array of ElementHandle`s, for each of which need to find the button inside the element and click.

**What happens instead?**

Sometimes the whole cycle succeeds, sometimes I get an error: 
```
Error: Node is detached from document
    at ElementHandle._scrollIntoViewIfNeeded (.../node_modules/puppeteer/lib/ExecutionContext.js:338:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (.../node_modules/puppeteer/lib/helper.js:144:27)
    at Object.followersFollow (.../dist/actions/follow.js:55:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by aslushnikov** [comment]
@jeudesprits so what's the website?

**Comment by jeudesprits** [comment]
@aslushnikov 
> @jeudesprits so what's the website?

<img width="1773" alt="screen shot 2018-11-06 at 02 05 12" src="https://user-images.githubusercontent.com/36597778/48026888-2b5b0080-e169-11e8-9fc8-f4bc02e8799b.png">

**Comment by aslushnikov** [comment]
@jeudesprits turns out instagram infinite list is pretty complicated - it re-builds itself at some time as you start scrolling it. At this point, it removes all old DOM nodes and creates a new ones; so your element handles start pointing to detached nodes.

To sum up - not a bug.

**Comment by tarikbellamine** [comment]
I've encountered this problem too on a different site. The click method has a built in function that enables puppeteer to scroll to reach the element you've designated needs clicking. I believe it's that scrolling that triggers the DOM element removal and thus the "Node is detached from document" error.

Putting the node selection and clicking it in same document context, which can be done in a variety of ways such as page.evaluate or page.$eval, appears to have resolved the issue for me.

**Comment by atefBB** [comment]
@tarikbellamine I have the same issue, how did you solve it? (show me example code if you can 'cause I didn't understand your description)

**Comment by eduardoewgo** [comment]
@tarikbellamine 

Hey, could you elaborate a little bit more? 

Thanks.

**Comment by cristighr1995** [comment]
For me it worked to do this: `await page.$eval(selectorString, elem => (elem as HTMLElement).click());`

**Comment by mahirhiro** [comment]
@cristighr1995 Hey, do you mind sharing the file for a bit more context :)

Thanks

**Comment by GiorgioRemindme** [comment]
elem as HTMLElement ?

Thas no valid js im i right?

**Comment by SamJarmanPP** [comment]
@GiorgioRemindme no its not, but their typescript compiler is smart enough to turn it it in `elem.click()`

**Comment by chaitanya2903** [comment]
Hello, I am facing a similar problem in pyppeteer but when I used the above solution following error occurs
`pyppeteer.errors.ElementHandleError: Evaluation failed: SyntaxError: Unexpected
token <`
Pyppeteer is similar with a different syntax it would be a huge help if anyone can take a look at the following issue and help me out.[https://github.com/pyppeteer/pyppeteer/issues/162](url)

**Comment by dartandrevinsky** [comment]
> elem as HTMLElement ?
> 
> Thas no valid js im i right?

TypeScript

**Comment by hrqmonteiro** [comment]
> elem as HTMLElement ?
> 
> Thas no valid js im i right?

Oh my god...

**Comment by bob-lee** [comment]
With full `puppeteer`, below used to worked:
```js
await page.click(MY_BUTTON_SELECTOR)
```
but with `puppeteer-core@22.6.0` and `@sparticuz/chromium@122.0.0`, it started complaining with `Node is detached from document` error, so instead tried `@eval` as recommended above which worked ok:
```js
await page.$eval(MY_BUTTON_SELECTOR, elem => elem.click())
```

It seems that `@eval()` is more reliable than `click()` especially when the page is long and needs some scrolling.

**Comment by Ectsang** [comment]
> With full `puppeteer`, below used to worked:
> 
> ```js
> await page.click(MY_BUTTON_SELECTOR)
> ```
> 
> but with `puppeteer-core@22.6.0` and `@sparticuz/chromium@122.0.0`, it started complaining with `Node is detached from document` error, so instead tried `@eval` as recommended above which worked ok:
> 
> ```js
> await page.$eval(MY_BUTTON_SELECTOR, elem => elem.click())
> ```
> 
> It seems that `@eval()` is more reliable than `click()` especially when the page is long and needs some scrolling.

Do you recall when it "used to work" for you? I'm having a similar issue but my last working code (using .click) was just last week (Apr 24).

**Comment by Ectsang** [comment]
FWIW, I was able to "click" by using `"puppeteer": "^22.6.5"`:
```
const link = await page.$(selectorName) as ElementHandle<Element>;
await link.click();
```

**Comment by ryaneclpse** [comment]
I was having the same issue after upgrading from 21.7.0 to 22.7.1. Based on the messages, it seemed like the page might be rebuilding between the time the elementHandle is found and the click function was being run on the found previously found elementHandle. It was very sporadic. I ended up just creating a for loop to wait a second if click errored out and attempted a second time after a 1 second wait. That seems to have worked for me. It is occasionally throwing an error on attempt 1 but attempt 2 is picking up the slack.
