### ISSUE TITLE
Connect with already opened window.

### ISSUE THREAD

**Issue by siva201010sivakumar** [puppeteer/puppeteer#3498]
Is there a way to connect already opened chrom window( example: with selenium webdriver js) and get the HAR report.

**Comment by aslushnikov** [comment]
If you know browser's `wsEndpoint`, you can use [`pptr.connect`](https://pptr.dev/#?product=Puppeteer&version=v1.9.0&show=api-puppeteerconnectoptions).

For HAR generation, there's a [puppeteer-har](https://github.com/Everettss/puppeteer-har) that addresses this.

Hope this helps

**Comment by rageshpayyan** [comment]
@siva201010sivakumar is it worked
