### ISSUE TITLE
How to get chrome memory usage by chrome://system in headless mode?

### ISSUE THREAD

**Issue by tzbo** [puppeteer/puppeteer#3500]
I can get chrome memory usage by chrome://system in none headless mode, but in headless mode there is nothing. What should I do?

**Comment by aslushnikov** [comment]
@tzbo  the `chrome://system` is not implemented in headless chrome. The way to go would be to get `pid` using [`browser.process()`](https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-browserprocess) and then fallback to native tools, e.g. [ps or valgrind on linux](https://stackoverflow.com/questions/131303/how-to-measure-actual-memory-usage-of-an-application-or-process). 

Hope this helps.

**Comment by tzbo** [comment]
ok, ths.
