### ISSUE TITLE
navigator.webdriver cannot modify

### ISSUE THREAD

**Issue by xiaoyuhen** [puppeteer/puppeteer#3501]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version:  macOS High Sierra
* URLs (if applicable):
* Node.js version: 10.0.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.create a new page
```
const page = await browser.newPage()
```
2.modify navigator webfriver value
```
const modifyWebdriver = () => {
    Object.defineProperty(navigator, 'webdriver', {
      get: function() {
        return false
      },
    })
  }

await page.evaluate(modifyWebdriver)
```
3.console .log(navigator.webdriver)
```
console.log(await page.evaluate('navigator.webdriver'))  // false
```
4.goto a website
```
await page.goto('https://www.google.com', {
    waitUntil: 'networkidle2',
    timeout: 3000000,
  })
```
5.console.log(navigator.webdrive)
```
console.log(await page.evaluate('navigator.webdriver'))  // true
```
**What is the expected result?**
console.log(await page.evaluate('navigator.webdriver'))  // false

**What happens instead?**
console.log(await page.evaluate('navigator.webdriver'))  // true

**Comment by tzbo** [comment]
```
await this.page.evaluateOnNewDocument(() => {
         Object.defineProperty(navigator, 'webdriver', {
         get: () => undefined,
    });
 }
```

**Comment by xiaoyuhen** [comment]
@tzbo thank you so much

**Comment by rockswang** [comment]
Simpler approch:
const browser = await puppeteer.launch({ignoreDefaultArgs: ["--enable-automation"]});

**Comment by dfang** [comment]
not works on latest version of puppeteer, all of them

**Comment by Logic-01001010** [comment]
``` Javascript
 await page.evaluateOnNewDocument(() => {
      Object.defineProperty(navigator, 'webdriver', {
      get: () => false,
  });
  });
```
Thank you! @[tzbo](https://github.com/tzbo)
