### ISSUE TITLE
uploadFile works not everytime.

### ISSUE THREAD

**Issue by TomasKavaliauskas** [puppeteer/puppeteer#3503]
I am trying to upload video to youporn.com with Puppeteer.
My upload function looks like this:

```
async function uploadVideo(video, categories)
{
    
    youPornPage.on('console', consoleObj => console.log(consoleObj.text()));
    await youPornPage.setExtraHTTPHeaders({Referer: 'https://youporn.com'});
    await youPornPage.goto('https://youporn.com/upload/', {
        waitUntil: ['networkidle2'] 
    });      
    await youPornPage.waitFor(20000);
    let fileInput = await youPornPage.$(fileSelector);
    await fileInput.uploadFile(BASE_PATH+'/Videos/'+video.filename);
    await youPornPage.waitFor(3000);   
    let options2 = {
        path: 'after.png',
        fullPage: true
    }    
    await youPornPage.screenshot(options2);  
}
```
Browser configuration
```puppeteer.launch({headless: true, args:['--no-sandbox', '--disable-setuid-sandbox'], ignoreHTTPSErrors: true, dumpio: false }).then(async browser => {```
When I fill input file field with data, youporn then loads additional **div** where I can fill other information about video. The problem is, that this code works only once per 10-20 tries. I am sure that additional **div** is loaded when input file field's change event is triggered. I tested and saw that uploadFile() function actually triggers that event, so I am guessing that there might be a problem with Javascript? Maybe some script is not loaded, but then I added 20sec waiting after page is loaded to make sure that javascript is loaded, and get the same results.

I tried to console log everything that I get when go to this webpage, and here are results:

> Failed to load resource: the server responded with a status of 404 ()
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> ServiceWorker scope:  https://www.youporn.com/  Expected version: 2e48ca520f95d921bc2d7049a7e7c18a0e58d661
> The resource https://fs.ypncdn.com/cb/assets/fonts/gothic.woff2?v=2e48ca520f95d921bc2d7049a7e7c18a0e58d661 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
> The resource https://fs.ypncdn.com/cb/assets/fonts/yp.woff2?v=2e48ca520f95d921bc2d7049a7e7c18a0e58d661 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

This is console log of the use case, when this code actually works correctly:

> Failed to load resource: the server responded with a status of 404 ()
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
> A preload for 'https://fs.ypncdn.com/cb/assets/fonts/yp.woff2?v=2e48ca520f95d921bc2d7049a7e7c18a0e58d661' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
> Failed to load resource: net::ERR_FAILED
> ServiceWorker scope:  https://www.youporn.com/  Expected version: 2e48ca520f95d921bc2d7049a7e7c18a0e58d661
> The resource https://fs.ypncdn.com/cb/assets/fonts/gothic.woff2?v=2e48ca520f95d921bc2d7049a7e7c18a0e58d661 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
> The resource https://fs.ypncdn.com/cb/assets/fonts/yp.woff2?v=2e48ca520f95d921bc2d7049a7e7c18a0e58d661 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME

Only difference I see is additional 
> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
at the end.

Maybe someone could help me out, I am new to puppeteer, I guess that I missed some configuration but not sure where to look for. I have been trying to make this code consistent for two days.

**Comment by depsypher** [comment]
I'm seeing similar problems with uploadFile(). We're scripting uploading an image, then waiting for a selector for when that image gets placed on the page, but that never happens.

Code that works fine on 1.9.0 is failing on 1.10.0. We reverted back to 1.9.0 for now.

**Comment by TomasKavaliauskas** [comment]
I added this code:
```
        process.on('unhandledRejection', error => {
            // Will print "unhandledRejection err is not defined"
            console.log('unhandledRejection', error.message);
          });   
```

And noticed, that when uploading does not work, these messages are printed out in the console:

> unhandledRejection ReferenceError: jQuery is not defined
>     at https://cdn1d-static-shared.phncdn.com/jquery-ui-1.10.3.js:5:4316
> unhandledRejection ReferenceError: jQuery is not defined
>     at https://cdn1d-static-shared.phncdn.com/jquery/jquery.tokeninput-1.6.2.js:1:15115
> unhandledRejection ReferenceError: jQuery is not defined
>     at https://fs.ypncdn.com/cb/assets/js/mobile/upload.js?v=9e15a9238a529a21f2b5c130655bcbe8d7e53a60:1:7916

So for some reason sometimes jQuery is not loaded correctly, and other scripts, that relay on jQuery crashes, that way uploading does not work. I wonder what can cause this problem? Because when I visit this page in my chrome, it works everytime. Also, is it possible to somehow load jQuery inside website while loading, so other scripts won't crash?

**Comment by aslushnikov** [comment]
@dudeperfect95 a few things I noticed here:
- your code doesn't wait for the actual upload to happen; you might want to wait for the progress bar to fill?
- instead of [`page.$`](https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-pageselector) I'd recommend using [`page.waitForSelector`](https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-pagewaitforselectorselector-options) - to await appearing of `input` and the `div` you're interested in.

I can't infer more from what I have; if you can share the whole script to play with I can check and see where and why it breaks.

@depsypher same here: if you can share your script so that I can play and debug it locally, it'd help *a lot*.

**Comment by depsypher** [comment]
Thanks, it's tough for me to share the whole script in my case (relies on login cookies I'm getting out of band, and even then you must have an account at the site I'm scripting). The relevant bit looks like this though:

	console.log(`${new Date()} [${url}] uploading file`);
	const input = await select('input[id=fileElem]');
	await input.uploadFile(file);

	console.log(`${new Date()} [${url}] finding image on page`);
	await page.waitForSelector('image[data-contentType="Upload"]', {timeout: 60_000});  // uploaded image is placed on the page

We were running our node service originally using puppeteer v1.7.0 and never needed a timeout on that waitForSelector (the default 30 seconds was fine)... then I upgraded to 1.10.0 and tried timeouts as high as 2min but it always times out looking for the selector. Not entirely sure if the problem is with uploadFile() or elsewhere, and haven't done exhaustive tests to see if it ever succeeds (OP was saying it does succeed 1 in 10 or 20 tries, which is too high a failure rate anyway for us).

Anyhow, the waitForSelector does seem to always timeout under 1.10.0 and not under 1.9.0. Taking a screenshot after a timeout of a minute or more shows that the image indeed hasn't been placed on the page where expected.

I hope that helps. If not maybe I can try finding an easier site to create a test against, but it's possible that it's something subtle with the site I'm scripting.

**Comment by aslushnikov** [comment]
@depsypher the main difference between 1.9.0 and 1.10.0 is the Chromium version. The 1.10.0 bundles Chromium M72, whereas 1.9.0 comes with Chromium M71.

I'd speculate that:
- the website doesn't work on Chromium 72?
- the website serves a different content for Chromium 72, resulting in a new selector

Can you please try running Chromium 72 (e.g. Canary would suffice) and see if the website behaves as expected?

**Comment by depsypher** [comment]
@aslushnikov Thanks for the suggestions.

I tried canary (72.0.3603.0) and the site seems to work on it navigating manually.

Looks like puppeteer 1.10.0 downloads r599821 (72.0.3582.0) so there are some revisions in between that and canary.

So I tried npm installing 1.10.0 and then running the chromium version it installs on my mac with `open ./node_modules/puppeteer/.local-chromium/mac-599821/chrome-mac/Chromium.app`

That also worked fine when navigating the site manually in the headful browser. Seems like it's narrowing down to something in puppeteer, but it may still be hard to pinpoint. If I find myself with some free time I'll see if I can come up with a reproducible test case.

**Comment by aslushnikov** [comment]
> If I find myself with some free time I'll see if I can come up with a reproducible test case.

@depsypher This would be absolutely wonderful.

**Comment by TomasKavaliauskas** [comment]
@aslushnikov Thank you for offering me some help. This code is not actually uploading anything yet, I am just trying to submit file, because only after this action, youporn.com show additional div with other form fields. But as I mentioned before, it does work only once in 10 script runs. Usually something does not work well, and I noticed those jQuery not defined errors, but not sure what is wrong.
 Here is my code:
```
// Dependencies
const puppeteer = require('puppeteer');
const fileSystem = require('fs');

// Constants
const BASE_PATH = '/var/www/bot/';

// Global variables
let youPornPage = null;

// Credentials
let loginUsername = 'username';
let loginPassword = 'password';

// Selectors
const headerLoginSelector = '#header_login';
const loginUsernameSelector = '#login_username';
const loginPasswordSelector = '#login_password';
const profileSelector = '.js_userAvatar';
const fileSelector = '#fileUploadField';

puppeteer.launch({headless: true, args:['--no-sandbox'] }).then(async browser => {
    console.log("START");
    await createYouPornTab(browser);
    process.on('unhandledRejection', error => {
        console.log('unhandledRejection', error.message);
    });        
    await login();             
    await uploadVideo();
	await browser.close();
	console.log("END OF THE SCRIPT");
	process.exit();

});

async function uploadFile()
{
    return new Promise (async (resolve, reject) => {
        let fileInput = await youPornPage.$(fileSelector);
        await fileInput.uploadFile(BASE_PATH+'/Videos/video.mp4');
        resolve();        
	});	  
}

async function uploadVideo()
{

	return new Promise (async (resolve, reject) => {
        console.log(currentVideo);
        await goToUploadPage();
        await uploadFile();
        try {
        await youPornPage.waitForSelector('.uploadItem');
        }catch(error) {
            console.log("ERROR");
        }
        let options2 = {
            path: 'loginAgain.png',
            fullPage: true
        }
        await youPornPage.screenshot(options2);
        resolve();        
	});	    
  
}

async function login()
{
    
	return new Promise (async (resolve, reject) => {
        await goToLoginPage();
        await submitLoginForm();  
        resolve();
	});	       
      
 
}

async function goToUploadPage()
{
	return new Promise (async (resolve, reject) => {
        try {  
            await youPornPage.setExtraHTTPHeaders({Referer: 'https://youporn.com'});  
            await youPornPage.on('domcontentloaded', function(document) {
                youPornPage.addScriptTag({path: BASE_PATH+"/vortex-simple-1.0.0.js"});
                youPornPage.addScriptTag({path: BASE_PATH+"/jquery-2.1.1.js"});
            });  
            await youPornPage.goto('https://youporn.com/upload', {
                waitUntil: ['load','domcontentloaded','networkidle0', 'networkidle2']
            });     
            youPornPage.waitForNavigation({ waitUntil: ['load','domcontentloaded','networkidle0', 'networkidle2'] });
            await youPornPage.waitForSelector('.js_userAvatar');
            resolve();
        }catch(error) {
            reject();
        } 
	});	        
}

async function submitLoginForm()
{
	return new Promise (async (resolve, reject) => {
        let usernameInput = await youPornPage.$(loginUsernameSelector);
        await usernameInput.type(loginUsername);     
        let passwordInput = await youPornPage.$(loginPasswordSelector);
        await passwordInput.type(loginPassword); 
        await youPornPage.click('.btnLogin');
        
        try {
            youPornPage.waitForNavigation({ waitUntil: 'networkidle0' });
            await youPornPage.waitForSelector('.js_userAvatar');
            resolve();
        }catch(error) {
            reject();   
        }
	});	        
}

async function goToLoginPage()
{
	return new Promise (async (resolve, reject) => {
        try {
            await youPornPage.setExtraHTTPHeaders({Referer: 'https://youporn.com'});    
            await youPornPage.goto('https://youporn.com/login', {
                waitUntil: ['load','domcontentloaded','networkidle0', 'networkidle2']
            });        
            await youPornPage.waitForSelector('#networkbar ul li'); 
            resolve();
        }catch(error) {
            reject();
        }
	});	        
}

async function createYouPornTab(browser)
{
	youPornPage = await browser.newPage();
    await youPornPage.setViewport({ width: 1920, height: 1080});
    await youPornPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36');
}
```


Also, to be able to access /upload page, you have to be logged in, so you must have an account for testing.

Thank you again for any help.

**Comment by TomasKavaliauskas** [comment]
I guess I managed to fix this by adding this code:
```
        await youPornPage.setRequestInterception(true);
        youPornPage.once('request', request => {
          youPornPage.on('request', request => request.continue());
        });        
```
Am I right that this code above waits for all requests to finish. That way making sure page is fully loaded?
But now, sometimes timeout exception is thrown when I go to the page with this code:
```
        await youPornPage.goto('https://youporn.com/upload', {
            waitUntil: ['load','domcontentloaded','networkidle0','networkidle2'] //'load','domcontentloaded','networkidle0',
        });    
``` 

> { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
>     at Promise.then (/var/www/survego-development/bot/node_modules/puppeteer/lib/FrameManager.js:1230:21)
>   -- ASYNC --
>     at Frame.<anonymous> (/var/www/survego-development/bot/node_modules/puppeteer/lib/helper.js:144:27)
>     at Page.goto (/var/www/survego-development/bot/node_modules/puppeteer/lib/Page.js:587:49)
>     at Page.<anonymous> (/var/www/survego-development/bot/node_modules/puppeteer/lib/helper.js:145:23)
>     at uploadVideo (/var/www/survego-development/bot/Uploaders/youporn.js:164:27)
>     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

I wonder, can I do something about this, or just increasing timeout would fix the problem?

**Comment by depsypher** [comment]
@aslushnikov In my case, I'm pretty sure my issue is actually caused by issue #3463, not uploadFile(). Just FYI.

**Comment by paullewis** [comment]
Since #3463 is closed, and since we updated `uploadFile` to be more as expected (as of 532ae573d29063ffd081ed9ee340d71b25320dec) I'm going to close this issue, but please let us know if it's not fixed.
