### ISSUE TITLE
addScriptTag fails with type=module

### ISSUE THREAD

**Issue by tschaub** [puppeteer/puppeteer#3505]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: macOS 10.14
* Node.js version: 10.10.0

**What steps will reproduce the problem?**

1. create a `test.js` script with the content below and run `node test.js`

```js
const http = require('http');
const puppeteer = require('puppeteer');

function serve(port) {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      res.end('console.log("Hello World")');
    });

    server.listen(port, err => {
      if (err) {
        reject(err);
        return;
      }
      resolve(() => {
        server.close();
      });
    });
  });
}

async function main() {
  const port = 3000;
  const done = await serve(port);

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setBypassCSP(true); // setting this to false or omitting it has the same result

  page.on('console', msg => {
    for (const arg of msg.args()) {
      process.stdout.write(`${arg}\n`);
    }
  });

  try {
    await page.addScriptTag({
      url: `http://localhost:${port}/`,
      type: 'module' // things work if this is not set to 'module'
    });
  } finally {
    await browser.close();
  }

  done();
}

if (require.main === module) {
  main().catch(err => process.stderr.write(`${err.stack}\n`, () => process.exit(1)));
}
```

**What is the expected result?**

`JSHandle:Hello World`

**What happens instead?**

```bash
Error: Loading script from http://localhost:3000/ failed
    at Frame.addScriptTag (/path/to/node_modules/puppeteer/lib/FrameManager.js:579:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/path/to/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.addScriptTag (/path/to/node_modules/puppeteer/lib/Page.js:395:29)
    at Page.<anonymous> (/path/to/node_modules/puppeteer/lib/helper.js:145:23)
    at main (/path/to/test.js:37:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I remove `type: 'module'` from `page.addScriptTag()`, then I get the expected result: the script is loaded and logs "Hello World" to the console.

With `type: 'module'`, the script fails to load.  The `exceptionDetails` in [`ExecutionContext.js`](https://github.com/GoogleChrome/puppeteer/blob/v1.10.0/lib/ExecutionContext.js#L123-L124) is `Event`.

I assumed initially that the script failed to load due to CORS issues.  But I get the same result when calling `page.setBypassCSP(true)` (or the same with `false`).

**Comment by aslushnikov** [comment]
@tschaub quick guess: you can't load module scripts to the `about:blank` page. Try navigating the page first to some reasonable URL?

**Comment by aslushnikov** [comment]
Yep; reproduced it locally. Adding module scripts to `about:blank` is not supported. In fact, `about:blank` is a special kind of page in many ways, so I'd recommend navigating off it right away before doing anything else. 

Hope this helps.
