### ISSUE TITLE
page.frames() doesn not show new iframe that has been recently attached to DOM

### ISSUE THREAD

**Issue by justnpT** [puppeteer/puppeteer#3506]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8
* Platform / OS version: windows 10
* URLs (if applicable): not available in the US, but we can talk about this later
* Node.js version: v8.11.4

**What steps will reproduce the problem?**

        await page.waitForSelector('#paymentSuccessCart', {visible: true});
        await page.waitForSelector(".button-go-to-scratch", {visible: true});
        await page.click(".button-go-to-scratch");
        await page.waitForSelector(".owl-item:nth-of-type(2) .my-scratch-carousel-item-bottom-play", {visible: true});
        await page.click(".owl-item:nth-of-type(2) .my-scratch-carousel-item-bottom-play");
        const tryItFrame = page.frames().find(f => f.id === 'game-iframe');

MOST informative piece: The attached movie (2 min. long) 
https://vimeo.com/299402370
PLEASE SEE THE ATTACHED MOVIE AND Tell Me How Can I provide you with more information !

I will think about providing some mock staging test environment where the issue can be further investigated, after seeing your response. Because perhaps you will know what's happening right away.

So please see the movie where I carefully and efficiently described the issue LIVE

**What is the expected result?**

Expepected:
The method page.frames() should return four frames:
- main frame
- tidio code iframe
- tidio chat iframe
- game iframe

**What happens instead?**
The method page.frames() returns three frames:
- main frame
- tidio code iframe
- tidio chat iframe

**Comment by aslushnikov** [comment]
@justnpT hmm, I don't think the movie is available. Can you re-upload it?

**Comment by justnpT** [comment]
@aslushnikov  sure, I updated the link with: https://vimeo.com/299402370

**Comment by aslushnikov** [comment]
@justnpT Thank you for the video! This looks like a pptr or CDP bug. Any chance I can somehow get to the website to further debug this locally?

**Comment by justnpT** [comment]
Alright, @aslushnikov I can prepare a test account for you to send you through private message so that you can follow the steps on our stage env, and I will add some virtual money to that account because that's required to reproduce the issue. Can you connect through German / Irish VPN ? This will be required as our gambling platform has no legal permissions in every country yet. Can we communicate the private part through e-mails, mine is michal.nowierski@gmail.com please send me a message, I will respond with test account credentials and detailed user-level steps to reproduce the problem. Sorry for the delay in response as I had to consult allowing your investigation with my managers.

**Comment by aslushnikov** [comment]
@justnpT sent you an e-mail

**Comment by justnpT** [comment]
@aslushnikov  thanks, responded

**Comment by martinth** [comment]
@justnpT We had a very similar issue which I suspect to have the underlying root cause: The results of `.frames()` seems to be cached on some level. We have an SPA (like you seem to have) and we dynamically create frames. 

We worked around the issues this by adding an `async` function that uses `waitForFunction`. The inner function then uses `document.querySelector` and `getComputedStyle(frame).height` to assert that all the expected frames are present and only _then_ call `.frames()`.

**Comment by chrisvoo** [comment]
> We worked around the issues this by adding an `async` function that uses `waitForFunction`

@martinth I tried with this approach but it doesn't work for me:

```javascript
  async waitForFrame() {
    return this.page.waitForFunction(() => {
      var iframeSel = document.querySelector("#braintree-hosted-field-number");
      return (iframeSel) ? getComputedStyle(iframeSel).height === "41px" : false
    }, {
      polling: 500,
      timeout: 30000,
    })
  }

  await this.waitForFrame()
  dumpFrameTree(this.page.mainFrame())
```

When `waitForFrame` returns true and then I dump the frames from the page ([the same function used here](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-class-frame)) I still cannot see any iframe but the mainFrame. Braintree uses an iframe for every text field in the payment form [as described here](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2), where there's also a demo.

**Comment by tokland** [comment]
This worked for me: https://github.com/puppeteer/puppeteer/issues/5123#issuecomment-559158303

**Comment by Microanswer** [comment]
遇到了同样的问题。
same issue.
