### ISSUE TITLE
Accessibility Object Model

### ISSUE THREAD

**Issue by NickColley** [puppeteer/puppeteer#3507]
Hello!

I'm interested in using Puppeteer to check the [Accessibility Object Model](https://tink.uk/playing-with-the-accessibility-object-model-aom/)

It look like you can turn this on with a flag on Chrome Canary but I'm not sure what build Puppeteer uses.

`chrome.exe --enable-blink-features=AccessibilityObjectModel`

Is this something that is possible?

**Comment by NickColley** [comment]
Probably a duplicate of https://github.com/WICG/aom/issues/122#issue-336174575

**Comment by aslushnikov** [comment]
@nickcolley we expose AOM in a way of [Accessibility API](https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-class-accessibility). Available since version v1.10.0.
