### ISSUE TITLE
site login malfunction under puppeteer that does not occur running the underlying Chrome directly

### ISSUE THREAD

**Issue by Stewart8** [puppeteer/puppeteer#3508]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: Win 10 Pro 1803
* URLs (if applicable): https://online.citi.com/
* Node.js version: v10.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
puppeteer.launch({headless: false});
```
1. Run script, Chrome window opens.
2. Enter https://online.citi.com in address bar, home page opens showing Sign On section.
3. Enter 'aaa' in User ID field and 'aaaaaa' in Password field (without the quotes), click Sign On button.
 
**What is the expected result?**
The page shows a login failure.  Error message in red begins "Trouble signing on?"
The expected result does occur if instead of the script, the underlying Chromium 72.0.3582.0 (node_modules\puppeteer\\.local-chromium\win64-599821\chrome-win\chrome.exe) is run by double-clicking the .exe file, clearing all cookies and other History, then entering the URL.

**What happens instead?**
A redirect to https://online.citi.com/ServerError.html occurs.

**Comments**
Under this puppeteer setup, I am able to log into several other banking sites with no issue.

Comparing console debug output, the failing case does submit the login form with correct request headers and all the form fields are present.  Unfortunately, there are many hidden fields that differ, but they are opaque and partly based on random data from the server, so I have no idea how to track down what's going wrong.  The server responds to the failing POST with an immediate 302 redirect to ServerError.html, with no information about the problem.

Does puppeteer remove some items from the 'environment' that could be causing this trouble?

Any suggestions on how to track it down?

Thanks,

Stewart

**Comment by Stewart8** [comment]
It appears that the issue is unrelated to Windows; I was able to duplicate it with a Cloud Function. index.js contains:
```
const puppeteer = require('puppeteer');
let page;

async function getBrowserPage() {
  // Launch headless Chrome. Turn off sandbox so Chrome can run under root.
  const browser = await puppeteer.launch({args: ['--no-sandbox']});
  return browser.newPage();
}

exports.screenshot = async (req, res) => {
  const url = 'https://online.citi.com';
  if (!page) {
    page = await getBrowserPage();
  }
  await page.setViewport({ width: 1366, height: 1024});
  await page.goto(url, {timeout: 120000});
  await page.type( '#password', 'aaaaaa', {delay: 200} );
  await page.keyboard.down('Shift');
  await page.keyboard.press('Tab');
  await page.keyboard.up('Shift');
  await page.keyboard.type( 'aaa', {delay: 200} );
  await page.click( '#signInBtn' );
  await page.waitForNavigation({timeout: 120000});
  
  const imageBuffer = await page.screenshot();
  res.set('Content-Type', 'image/png');
  res.send(imageBuffer);
};
```
All other parameters are the same as in https://cloud.google.com/blog/products/gcp/introducing-headless-chrome-support-in-cloud-functions-and-app-engine 
The failing result is the same as under Windows.

**Comment by Stewart8** [comment]
The problem is related to the default --enable-automation flag passed to Chromium.
Launching with:
```
const browser = await puppeteer.launch({headless: false, ignoreDefaultArgs: ['--enable-automation']});
```
results in proper operation.  I'm guessing that the Citi login page detects 'unauthorized modification' and submits data that causes the login to be rejected.

Is there some way that the warning can be presented but not be detectable by the page code?

**Comment by aslushnikov** [comment]
@Stewart8 the `--enable-automation` flag exposes a `navigator.webdriver` property in every page so that pages can detect automation and behave accordingly.

Overall, there are [many different ways](https://github.com/paulirish/headless-cat-n-mouse) that websites might employ to avoid automation, but this all falls outside of the scope of the project. 

Hope this helps.
