### ISSUE TITLE
Include target platform configuration on installation script

### ISSUE THREAD

**Issue by ralphg6** [puppeteer/puppeteer#3510]
Include was the ability to inform with the destination platform where the process will be deployed.

For cases where the build process of package to be deployed runs on a different platform from which it will be run.

**Comment by aslushnikov** [comment]
@ralphg6 I don't think this is a very common usecase. Can you use `puppeteer-core` instead and roll your own `install.js` script that downloads Chromium that you'd like? We exposed the [`BrowserFetcher`](https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-class-browserfetcher) api for this.

**Comment by aslushnikov** [comment]
I'll close this for now - feel free to write back if you think we can be somehow helpful.

**Comment by ralphg6** [comment]
Maybe it really is not very common ... But here in the company we have several developers ... We are using the puppeteer in the standard way. Each one can upload the system directly from your machine to the server, however each one has a different OS and the server is Linux ... So we opened this ticket ...
