### ISSUE TITLE
Page#setViewport required options

### ISSUE THREAD

**Issue by SheetJSDev** [puppeteer/puppeteer#3517]
```js
	await page.setViewport({width: WIDTH});
```

with no `height`, puppeteer rejects with the error message:

```
Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters width: integer value expected
```

However, the documentation https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-pagesetviewportviewport does not indicate that both height and width are required.

IMHO setting just the width should change the width while leaving the height untouched (default being the current width/height).  However, if the current behavior is desirable, the docs should be updated to reflect that.  Other functions like page#setCookie explicitly mark fields as required in bold, and the same thing should probably happen here.

**Comment by aslushnikov** [comment]
> However, if the current behavior is desirable, the docs should be updated to reflect that. 

I'd appreciate a PR.

**Comment by Nazanin1369** [comment]
I'd love to take this
