### ISSUE TITLE
Target: pass through "iframe" types

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#3518]
Currently `iframe` target types are passed inside `other` type even when the actual information has the type 'iframe'. One sample is while opening anything on google drive, a target for OAuth can be seen with sample data in there:

`targetId: "58521E586E76B7086CEA5F0A92B2378E", type: "iframe", title: "https://accounts.google.com/o/oauth2/postmessageR...`

<img width="900" alt="screen shot 2018-11-08 at 11 07 09 am" src="https://user-images.githubusercontent.com/1330677/48221259-767e3a80-e346-11e8-81f4-fa664f370ded.png">

Any reason to not pass it as `iframe` type?

**Comment by aslushnikov** [comment]
> Any reason to not pass it as iframe type?

@VikramTiwari out-of-process iframes is a browser implementation detail and should be encapsulated inside the Puppeteer API. We don't want to expose any `iframe` targets; out-of-process iframes should be merged into the page frame tree.

Currently, we disable OOPIF as much as can, but certain origins are still pushed into OOPIF. There's an outstanding bug #2548 regarding this; please upvote to follow updates on that one.

Hope this helps,
Andrey
