### ISSUE TITLE
Target: Extension loads should be of 'background_page' or 'page' type

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#3519]
Currently extensions are set as type `other` when they open as a pop-up. Unless the extension was a devtools extension shouldn't it be type `page` or `background_page`?

<img width="803" alt="screen shot 2018-11-08 at 11 16 47 am" src="https://user-images.githubusercontent.com/1330677/48221936-361fbc00-e348-11e8-9ead-6bb910913eff.png">

**Comment by aslushnikov** [comment]
@VikramTiwari can you give an example of such an extension? It'll save us a ton of time to reproduce & debug.
