### ISSUE TITLE
how to move the cursor at end of text-area for puppeteer

### ISSUE THREAD

**Issue by knightjacky** [puppeteer/puppeteer#3520]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.10.0
* Platform / OS version:macbook pro
* URLs (if applicable):any input textfield with long paragraph
* Node.js version:10.4.0

**What steps will reproduce the problem?**
my goal is trying to clear the text area.
trying to using code 
`  const lengths = await page.$eval(
    element,
    el => el.value.length || el.innerText.length,
  );
  for (let i = 0; i < lengths; i++) {
    await page.keyboard.press('Backspace');
  }`
however, the sursor is not at end of paragraph. I find it out that any paragraph having Multiple enter such as (/n/n/n/n), the curcor will be end of enter(/n/n/n/n). it is not at end of paragraph.  it could not clear all the text in input field. 
please help me how to move the cursor to end of paragraph. thanks.

**Comment by vsemozhetbyt** [comment]
Maybe just this, without keyboard:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.evaluate(function create() {
      const input = document.body.appendChild(document.createElement('textarea'));
      input.cols = 40;
      input.rows = 20;
      input.value = '123\n\n\n\n456\n\n\n\n789\n\n\n\n';
    });

    await page.waitFor(3000);

    await page.evaluate(function clean() {
      const input = document.querySelector('textarea');
      input.value = '';
    });

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Or do you need keyboard involved for some test case?
