### ISSUE TITLE
page.viewport() returns wrong value

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#3521]
I can keep changing my window size but the `await page.viewport()` doesn't return a value other than default value. Confused about what does it actually return?

**Comment by JoelEinbinder** [comment]
Puppeteer emulates a viewport for consistency across different computers. `page.viewport()` (no await needed), returns the emulated viewport dimensions. Notice that when you resize the window, the web page inside it doesn't actually change its size. You can set the viewport to something explicitly with page.setViewport, or disable the viewport emulation by launching puppeteer with `defaultViewport: null`.

If you want to get the window size after disabling viewport emulation, use `page.evaluate` and return `window.innerHeight` or whatever values you need.
