### ISSUE TITLE
send cookies etc?

### ISSUE THREAD

**Issue by Pomax** [puppeteer/puppeteer#353]
I'm trying to use puppeteer to log into a page and then continue navigation based on having been authenticated, but while login "succeeds", a subsequent `page.goto('http://blah/myaccount')` then does not send the information that was just negotiated for that domain, leading to a `page.screenshot()` showing a "you need to log in to see this page" page rather than the expected page. Is there a way to say something akin to `page.goto(url, { preserveSession: true });`?

**Comment by JoelEinbinder** [comment]
Do you have a small test case to reproduce this?

**Comment by Pomax** [comment]
In trying to clean up the code, it turns out that the problem is with how I'm trying to make navigation happen - I use `await page.click('input[type=submit]')` but this does not "wait" for whatever JS kicks in to run through a typical oauth url redirect chaing, so I end up calling `page.goto()` way too soon.

Is there a way to say "and now wait for a sequence of pageloads to happen until we're on url XYZ"? (like `page.waitForURL('https://example.com/oauth2/callback')`?) Or would this be a matter of rolling something like:

```js
await page.waitForFunction( 'window.location.toString() === "https://example.com/oauth2/callback"');
```

**Comment by JoelEinbinder** [comment]
You can do waitForFunction like you have, or listen for the 'framenavigated' or 'load' events that fire as the page changes urls.

**Comment by Pomax** [comment]
Perfect. Thanks for the help and sorry for filing too early. It might be an interesting idea to add an example that shows off using puppeteer with a login flow like this, where it's used to fill in user/pass creds, clicks through, and then waits for the page to have the correct url before doing "something".

**Comment by Partysun** [comment]
@Pomax Could you show some example for OAuth test?
