### ISSUE TITLE
Networkidle0 times out but I don't see any active requests 

### ISSUE THREAD

**Issue by InvincibleDRT** [puppeteer/puppeteer#3532]
I'm trying to take a screenshot and close the browser. When loading the content, Networkidle0 is timing out even thogh there no requests in pipeline. No active pings also.also another weird thing, When I launch chromium with headless false, page.Goto loads the content and sits there without doing anything. If I hit f12(dev tools) to see what's going on, it instantly takes the screenshot and closes browser. I couldn't understand what's going on when I launch dev tools.

**Comment by aslushnikov** [comment]
@InvincibleDRT If you use request interception, the `networkidle0` issues might be related to #3471. The chromium thing is weird though - any chance you can share your script?

**Comment by InvincibleDRT** [comment]
Sure. Its a simple load and capture code
`             const page = await browser.newPage();
			   
                await page.goto(url.toString() , 
                    { timeout: 100000, waitUntil: waitType });//NetworkIdle0
                
                selector = 'iframe';
                
                const rect = await page.evaluate(selector => {
                    const element = document.querySelector(selector);
                    if (!element)
                        return null;
                    const { x, y, width, height } = element.getBoundingClientRect();
                    return { left: x, top: y, width, height, id: element.id };
                }, selector);

                await page.screenshot({
                    path: imgPath,
                    clip: {
                        x: rect.left,
                        y: rect.top,
                        width: rect.width,
                        height: rect.height
                    }
                });`

**Comment by aslushnikov** [comment]
@InvincibleDRT any chance you can share the URL as well so that I can try it locally?

**Comment by InvincibleDRT** [comment]
unfortunately its an internal url. you wont be able to access it from outside network

**Comment by aslushnikov** [comment]
@InvincibleDRT I don't think I can help much without being able to reproduce this. Can you try building tiny reproduction website that reproduces the issue?

**Comment by aslushnikov** [comment]
@InvincibleDRT I'll close this for now; feel free to re-file once you have a good reproduction case for us to play with.

Thanks
