### ISSUE TITLE
await page.title() is too slow

### ISSUE THREAD

**Issue by AtuboDad** [puppeteer/puppeteer#3533]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.10.0
* Platform / OS version:Centos7.4
* URLs (if applicable):https://blog.csdn.net/wk313753744/article/details/50458360
* Node.js version:v8.11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.await page.title() is too slow

**What is the expected result?**
TimeoutError: Navigation Timeout Exceeded: 90000ms exceeded

**What happens instead?**

**Comment by aslushnikov** [comment]
- The website in question is quite slow to load, but there's nothing else I can tell about it.
- The error you posted is unrelated to the `page.title()` method

This is not actionable; please re-file with a script that doesn't work for you and that we can run locally and debug.

**Comment by AtuboDad** [comment]
> * The website in question is quite slow to load, but there's nothing else I can tell about it.
> * The error you posted is unrelated to the `page.title()` method
> 
> This is not actionable; please re-file with a script that doesn't work for you and that we can run locally and debug.

ok, I see. I solved it by html selector instead. Thinks so much.^ ^.
