### ISSUE TITLE
allow functions as arguments to evaluate

### ISSUE THREAD

**Issue by Janpot** [puppeteer/puppeteer#3534]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: MacOS 10.14.1 (18B75)
* URLs (if applicable):
* Node.js version: v11.1.0

**What steps will reproduce the problem?**

```js
function inner () {
  return 'hello from inner'
}

page.evaluate(inner => {
  return inner();
}, inner)
```

**What is the expected result?**

```
hello from inner
```

**What happens instead?**

```
Error: Evaluation failed: TypeError: inner is not a function
```

It can be done by patching `evaluate` to create handles for function arguments first

```js
async function newEvaluate (page, fn, ...rawArgs) {
  const args = await Promise.all(rawArgs.map(arg => {
    return typeof arg === 'function'
      ? page.evaluateHandle(`(${arg.toString()})`)
      : arg;
  }));
  return page.evaluate(fn, ...args);
}

function inner () {
  return 'hello from inner'
}

const result = await newEvaluate(page, inner => {
  return inner();
}, inner);
```

**Comment by aslushnikov** [comment]
@Janpot I'm not sure if serialization is a natural behavior for function passing: it'll align with what we do, but some clients might expect us to pass an RPC wrapper instead of a real function. (kinda like `exposeFunction`)

I also wonder what's your usecase for this - is this pressing?

**Comment by Janpot** [comment]
@aslushnikov But I'm passing an RPC wrapper in my example (that's what `page.evaluateHandle` creates right?), The argument I'm passing in `evaluate` is a handle, not a stringified function.

The usecase is not really pressing.

**Comment by aslushnikov** [comment]
@Janpot I'd defer this to the RPC implementation; for example, [Carlo](https://github.com/GoogleChromeLabs/carlo) now has an RPC capable of doing this.
