### ISSUE TITLE
Docs: waitForSelector "hidden" option is ambiguous

### ISSUE THREAD

**Issue by jacobweber** [puppeteer/puppeteer#3540]
### Steps to reproduce

[waitForSelector API docs](https://github.com/GoogleChrome/puppeteer/blob/v1.10.0/docs/api.md#pagewaitforselectorselector-options) include the following:

    hidden <boolean> wait for element to not be found in the DOM or to be hidden, i.e. have display: none or visibility: hidden CSS properties. Defaults to false.

**What is the expected result?**

Being "not found in the DOM" is not the same as having "display: none". It's not clear whether this waits for an element to be removed, or to be hidden via styles.

If it's the latter, should change it to something like "wait for element to be found in the DOM and be hidden, i.e. etc.".

And maybe add something indicating whether it's checking the ancestors for visibility or not, e.g. "have display: none or visibility: hidden CSS properties on the element itself or any of its ancestors".

(It would be useful to have an option to wait until a match is not found, which is what I originally thought this did. It looks like that was suggested in #705 but not implemented.)

**Comment by aslushnikov** [comment]
@jacobweber we welcome all PRs that make our documentation more clear and understandable; please go ahead!
