### ISSUE TITLE
Chrome in headless mode

### ISSUE THREAD

**Issue by nicobytes** [puppeteer/puppeteer#3541]
I try create a crawl for whatsapp with puppeteer in headless mode but whatsapp only support Chrome. (Chrome not work in headless mode).

![screen shot 2018-11-14 at 5 36 08 am](https://user-images.githubusercontent.com/7611944/48474875-e15dc480-e7d1-11e8-9729-6a63f7e8bf49.png)

**Comment by aslushnikov** [comment]
@nicobytes 
- if you think WhatsApp should support Chromium, I'd reach out to them right away :)
- if the question is "how do I run puppeteer with stable chrome", I've just answered similar question [here](https://github.com/GoogleChrome/puppeteer/issues/3543#issuecomment-438835878)

**Comment by nicobytes** [comment]
haha @aslushnikov  ok I get it, thanks a lot. =)

**Comment by saade** [comment]
@nicobytes did you manage to make it work? I'm having this problem only in headless mode. (i need to do it in headless)
