### ISSUE TITLE
why Array.from(document.querySelectorAll('body>div>div>div')) length is not euqal page.$$'s le

### ISSUE THREAD

**Issue by yanguoyu** [puppeteer/puppeteer#3542]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.goto('https://www.baidu.com');
  const handlers = await page.$$('body>div>div>div');
  console.log(handlers.length);
  await browser.close();
});
2. open https://www.baidu.com
const length = Array.from(document.querySelectorAll('body>div>div>div'))

**What is the expected result?**
handlers.length === length

**What happens instead?**
handlers.length = 4
length = 10

**Comment by vsemozhetbyt** [comment]
I get 4 in the console:
![b](https://user-images.githubusercontent.com/10393198/48496599-49d89000-e82a-11e8-9a2b-a922259ae939.png)
Could it be that you get 10 as a registered user?

**Comment by yanguoyu** [comment]
yes, register
.sorry.
