### ISSUE TITLE
I would like to use puppeteer with my current chrome (keeping my credentials)

### ISSUE THREAD

**Issue by lucasteisseire** [puppeteer/puppeteer#3543]
i'm actually trying to use puppeteer for scraping and i need to use my current chrome to keep all my credentials and use it instead of relogin and type password each time which is a really time lose ! 

is there a way to connect it ? how to do that ?
i'm actually using node v11.1.0
and puppeteer 1.10.0

    let scrape = async () => {
        const browser = await log()
        const page = await browser.newPage()           
        const delayScroll = 200
    // Login 
    await page.goto('somesite.com');
    await page.type('#login-email', '*******);
    await page.type('#login-password', "******");
    await page.click('#login-submit');
    // Wait to login
    await page.waitFor(1000);
}
and now it will be perfect if i do not need to use that and go on page (headless, i dont wan't to see the page opening i'm just using the info scraping in node) but with my current chrome who does not need to login to have information i need. (because at the end i want to use it as an extension of chrome)

thx in advance if someone knows how to do that

**Comment by aslushnikov** [comment]
@lucasteisseire in order to run puppeteer against stable chrome, you should do the following:
1. Figure the version of your stable chrome installation (in your stable chrome, navigate to `about:version`)
2. Figure out matching Puppeteer version in our [`api.md`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md)
3. Install [`puppeteer-core`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core)
4. Use `puppeteer-core` to launch the stable chrome, passing the `executablePath` option:

```js
const pptr = require('puppeteer-core');
(async () => {
  const browser = await pptr.launch({
    executablePath: '<path-to-my-chrome-exec>'
  });
  // ... go on...
})();
```

Hope this helps.

**Comment by pratik-joshi-cactus** [comment]
Not working :/ in Version 75.0.3770.100 (Official Build) (64-bit), It still opens up new instance of chrome and it has no history whatsoever, I had to open it along with my other chrome tabs.

	const puppeteer = require('puppeteer');
	const pptr = require('puppeteer-core');
	(async () => {

		const browser = await puppeteer.launch({
		  headless: false,
		  executablePath: '/usr/bin/google-chrome'
		});

	})(); 

Here I also tried puppeteer-core , means pptr variable await pptr.launch in above variable, still not working. The issues is not closed!
Please check : 
https://drive.google.com/file/d/1WKjgPeruK9-ABeHHsumhcjs_FTlzFH4S/view

**Comment by mcarneiro** [comment]
Maybe this post might help:

https://medium.com/@jaredpotter1/connecting-puppeteer-to-existing-chrome-window-8a10828149e0

**Comment by alex2844** [comment]
> @lucasteisseire in order to run puppeteer against stable chrome, you should do the following:
> 
> 1. Figure the version of your stable chrome installation (in your stable chrome, navigate to `about:version`)
> 2. Figure out matching Puppeteer version in our [`api.md`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md)
> 3. Install [`puppeteer-core`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core)
> 4. Use `puppeteer-core` to launch the stable chrome, passing the `executablePath` option:
> 
> ```js
> const pptr = require('puppeteer-core');
> (async () => {
>   const browser = await pptr.launch({
>     executablePath: '<path-to-my-chrome-exec>'
>   });
>   // ... go on...
> })();
> ```
> 
> Hope this helps.

not working
```js
        var browser, page;
        browser = await puppeteer.launch({
            executablePath: '/usr/bin/chromium', 
            userDataDir: '/tmp/browser'                                                                                                                
        });
        page = await browser.newPage();
        await page.goto('https://gmail.com/');
        await browser.close();
        browser = await puppeteer.launch({
            headless: false,
            executablePath: '/usr/bin/chromium',
            userDataDir: '/tmp/browser'
        });
        page = await browser.newPage();
        await page.goto('chrome://history/'); // history empty
```

**Comment by urosran** [comment]
The instructions above launch headless chrome

from chrome//about : 
Google Chrome | 77.0.3865.90 (Official Build) (64-bit) (cohort: Stable)
Chromium 77.0.3803.0  should be Puppeteer v1.19.0 (per github link above)
npm list
+-- puppeteer@1.19.0
+-- puppeteer-core@1.19.0

code: 
``
const pptr = require('puppeteer-core');
(async () => {
  const browser = await pptr.launch({
    executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
  });

  const page = await browser.newPage();
await page.goto('https://www.airbnb.com/');
console.log(page.url())
})();

``

runs in console and logs the correct url

**Comment by Ramanth** [comment]
what is the minimum version of chrome required? 
i have to automate a chrome v61 which is opened already in remote-debugging-mode?

**Comment by ashminbhandari** [comment]
Hey guys, I found a solution to this problem. So you can input the path to your userDataDir as part of the puppeteer launch parameters. Look for profile path by executing `chrome://version` in your browser. Doing this, puppeteer executed itself in the same chrome window that I am currently using.  

```
pptr.launch({headless: false,
  executablePath: '[insert executable path here]',
  userDataDir: '[insert profile path or user directory path here]'}).then(async browser => {
});
```

**Comment by ORESoftware** [comment]
@ashminbhandari  puppeteer-core or puppeteer?

**Comment by ashminbhandari** [comment]
@ORESoftware OOF, I believe it was puppeteer-core but I am not 100%

**Comment by ORESoftware** [comment]
@ashminbhandari  yeah I am looking for an answer to https://github.com/puppeteer/puppeteer/issues/5756

**Comment by eduardoewgo** [comment]
Any progress on this, @ORESoftware ? 

I've been trying to use my installed version for a while now :/.. 

The idea is to keep all my browser information/credentials while running puppeteer.

**Comment by ashminbhandari** [comment]
@ORESoftware Are you in a position to use something else? I switched to Selenium when I ran into this problem. And I believe it is suggested that you instead copy your profile directory and provide the path to that instead because running two instances on the same profile directory causes problems.

**Comment by matheuscch** [comment]
I'm using something like that.

My idea is to make the puppteer open in a url window, to be inserted into a page at run time

No answer so far

**Comment by eduardoewgo** [comment]
@matheuscch 

Try this

1. create a new chrome shortcut on your desktop and add `--remote-debugging-port=9222` to the target.
2. open it using the just created shortcut and go to http://127.0.0.1:9222/json/version

This json should give you the `webSocketDebuggerUrl`, which you case use to connect to the instance. If I'm not wrong it should be something like

`await puppeteer.connect({browserWSEndpoint: webSocketDebuggerUrl})`

**Comment by imvetri** [comment]
> Hey guys, I found a solution to this problem. So you can input the path to your userDataDir as part of the puppeteer launch parameters. Look for profile path by executing `chrome://version` in your browser. Doing this, puppeteer executed itself in the same chrome window that I am currently using.
> 
> ```
> pptr.launch({headless: false,
>   executablePath: '[insert executable path here]',
>   userDataDir: '[insert profile path or user directory path here]'}).then(async browser => {
> });
> ```

Executable path and userDataDir can be found here
chrome://version/

**Comment by D210000** [comment]
> > @matheuscch
> > 
> > Try this
> > 
> > 1. create a new chrome shortcut on your desktop and add `--remote-debugging-port=9222` to the target.
> > 2. open it using the just created shortcut and go to http://127.0.0.1:9222/json/version
> > 
> > This json should give you the `webSocketDebuggerUrl`, which you case use to connect to the instance. If I'm not wrong it should be something like
> > 
> > `await puppeteer.connect({browserWSEndpoint: webSocketDebuggerUrl})`
> 
> If anyone ever gets here, this still works but you need to replace `localhost` with `127.0.0.1` in `webSocketDebuggerUrl`  when using newer versions of node.js. Reference this https://github.com/puppeteer/puppeteer/issues/8873

Hey I still not able to connect webSocketdebugger cause site not open at all
