### ISSUE TITLE
Complete and partially blank screenshots on endless/infinite scroll sites.

### ISSUE THREAD

**Issue by lolknicksT-T** [puppeteer/puppeteer#3544]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: Mac OS X 10_13_6
* URLs (if applicable): https://twitter.com/github
* Node.js version: 10.13.0

**What steps will reproduce the problem?**
Go to a twitter account and find a tweet and consecutive tweets. If the tweet is after a infinite scroll load or multiple, the tweet screenshots completely or partially blank.
Able to reproduce on endless scroll sites like Twitter and mobile Tumblr. Desktop Tumblr with endless scroll had no issues getting screenshots.
Code for Twitter below.

    const tweetId = '#stream-item-tweet-1060233780114288640' // OK
    const tweetId = '#stream-item-tweet-1060166985693216768' // partially blank
    const tweetId = '#stream-item-tweet-1060199208953597952' // completely blank

    const browser = await puppeteer.launch({
        headless: false,
    })

    const page = await browser.newPage()
    await page.goto('https://twitter.com/github', { waitUntil: 'networkidle2' })
    await page.click('#signin-link > span.caret')
    let tweet = await page.$(tweetId)
    const viewPortHeight = await page.viewport().height
    // scroll with some delay until tweet is found
    while (!tweet) {
        await page.evaluate(_viewPortHeight => {
            window.scrollBy(0, _viewPortHeight)
        }, viewPortHeight)
        await page.waitFor(500)
        tweet = await page.$(tweetId)
    }

    await page.waitFor(1000)
    await tweet.screenshot({
        path: `${tweetId}.jpg`,
    })

    await browser.close()

**What is the expected result?**
Consistently correct screenshots.

**What happens instead?**
Partial and blank screenshots.

#stream-item-tweet-1060233780114288640
![stream-item-tweet-1060233780114288640](https://user-images.githubusercontent.com/33289275/48498372-24d12680-e804-11e8-834e-f9c07823df29.jpg)
#stream-item-tweet-1060166985693216768
![stream-item-tweet-1060166985693216768](https://user-images.githubusercontent.com/33289275/48498383-28fd4400-e804-11e8-837d-4f01d78cb9c0.jpg)
#stream-item-tweet-1060199208953597952
![stream-item-tweet-1060199208953597952](https://user-images.githubusercontent.com/33289275/48498385-2a2e7100-e804-11e8-8f37-18311f3cfa1d.jpg)

**Comment by rhoml** [comment]
This issue may be related to what we are seeing on https://github.com/dtjohnson/aws-azure-login/issues/35
