### ISSUE TITLE
Frame | Action is ignored when targeting multiple iframes sequentially 

### ISSUE THREAD

**Issue by aamorozov** [puppeteer/puppeteer#3545]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10
* Platform / OS version: MacOS High Sierra 
* URLs (if applicable): private project, cannot disclose unfortunately. 
* Node.js version: 11.1

**What steps will reproduce the problem?**

```
      const frames = await page.frames();
      const validFrames = await frames.filter(frame => frame.name().includes('needed data'));
      const firstFrame = validFrames[0];
      const secondFrame = validFrames[1];
      const thirdFrame = validFrames[2];
      const forthFrame = validFrames[3];

      await firstFrame.click('input');
      await firstFrame.type('input', 'data', {delay: 100});
      await secondFrame.click('input');
      await secondFrame.type('input', 'data', {delay: 100});
      await thirdFrame.click('input');
      await thirdFrame.type('input', 'data', {delay: 100});
      await forthFrame.click('input');
      await forthFrame.type('input', 'data', {delay: 100});

```

**What is the expected result?**
All steps should be completed 

**What happens instead?**
The first frame is targeted correctly and the data is written but then the process exists without any errors and with code 0.

**Comment by aslushnikov** [comment]
@aamorozov I cannot run your script locally; I'd need at least the URL of the website in question. Any chance you can share it?

**Comment by aamorozov** [comment]
@aslushnikov I was actually able to resolve it - I was targeting the wrong elements within the iframes 2,3, and 4 🤦‍♂️
