### ISSUE TITLE
puppeteer not capturing websocket ajax request

### ISSUE THREAD

**Issue by jainrish** [puppeteer/puppeteer#3547]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: MacOS 10.14
* URLs (if applicable): https://pro.coinbase.com/trade/BTC-USDC
* Node.js version: 8.11.4

**What steps will reproduce the problem?**
I have below code which intercept all the ajax requests on opening a URL. But it does not give the requests which are websockets. 

_Please include code that reproduces the issue._
```
var logXHRRequestURL = async function (url) {
    const browser = await puppeteer.launch({headless: true});
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    var count = 0;
    page.on('request', (request) => {
        console.log(request.url());
        request.continue();
    });
    await page.goto(url, {waitUntil: 'networkidle0'});
    await browser.close();
    return;
}
```

**What is the expected result?**
If I run this function for this URL: "https://pro.coinbase.com/trade/BTC-USDC", I should get "wss://ws-feed.pro.coinbase.com/" in the log, but that is not the case.

**What happens instead?**
The websocket URL does not get logged.

**Comment by triplevoid** [comment]
@jainrish should you use webSocketFrameSent & handleWebSocketFrameReceived event for this?

**Comment by tcc0lin** [comment]
@coder77 hi how to use webSocketFrameSent & handleWebSocketFrameReceived event, i can't find a way to solve this problem

**Comment by triplevoid** [comment]
@hanqiulun 你好

Here's how I capture web socket by Puppeteer and CDP.
```
      browser = await puppeteer.launch(config);
      page = (await browser.pages())[0];
//...
      f12 = await page.target().createCDPSession();
      await f12.send('Network.enable');
      await f12.send('Page.enable');
//...
      f12.on('Network.webSocketFrameReceived', handleWebSocketFrameReceived);
//...
      const handleWebSocketFrameReceived = (params) => {
        const payload = params.response.payloadData;
      }      
```

Hope it's help you.

**Comment by aslushnikov** [comment]
@coder77 workaround would work.

otherwise, that's a dupe of #2974.
