### ISSUE TITLE
Не работает в chrome os

### ISSUE THREAD

**Issue by alex2844** [puppeteer/puppeteer#3551]
При запуске получаю

```
(node:10747) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
../node_modules/puppeteer/.local-chromium/linux-599821/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

а если с
executablePath: '/opt/google/chrome/chrome'
то тогда получаю

```
(node:10747) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/opt/google/chrome/chrome: symbol lookup error: /opt/google/chrome/chrome: undefined symbol: gbm_bo_get_num_planes
```

chromeos: 69.0.3497.120
node: v10.12.0
puppeteer: 1.10.0
chromium_revision: 599821

**Comment by TrySound** [comment]
@alex2844 English please.

**Comment by aslushnikov** [comment]
@alex2844 please re-file in English: our issue tracker is an important source of information, let's keep it accessible for the community.

**Comment by alex2844** [comment]
https://github.com/GoogleChrome/puppeteer/issues/3554
