### ISSUE TITLE
Can I use puppeteer with IBM Bluemix?

### ISSUE THREAD

**Issue by kyung415** [puppeteer/puppeteer#3552]
I see tutorials on how to use puppeteer with Google Cloud and AWS but are there dependencies that Bluemix does not have. I am currently getting the "Error: Failed to launch chrome!" error.

**Comment by aslushnikov** [comment]
@kyung415 can you run `ldd` against the Chromium that's downloaded by Puppeteer? It's located somewhere under `node_modules/.local-chromium/linux-XXXXXX/chrome-linux/chrome`:

```bash
cd <myapp>
ldd node_modules/.local-chromium/linux-XXXXXX/chrome-linux/chrome | grep not
```
This should give you a list of missing dependencies for Chrome.

P.S. A minute ago I had no idea what "IBM Bluemix" is - I think you're the first to mention it on our bugtracker. Nice!

**Comment by kyung415** [comment]
is .local-chromium added when I npm install puppeteer? I current do not have it in my node-modules.

**Comment by aslushnikov** [comment]
> is .local-chromium added when I npm install puppeteer?

Yes

**Comment by kyung415** [comment]
Would there be a reason why the .local-chromium would not be installed? In node-modules, every directory is there except the .local-chromium. Could it be too big of a folder? My local has it but when I deploy to the server, it is not there.

**Comment by aslushnikov** [comment]
@kyung415 There are a few reasons it might happen:
- we don't have a compiled chromium binary compatible with your host environment
- the online storage we download builds from is not accessible, e.g. due to proxy / firewall
- there's not enough disk space on your host environment

Can you get a log from your server? There should be an error that explains why chromium isn't downloaded.

**Comment by kyung415** [comment]
2018-11-15T14:45:11.08-0800 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
   2018-11-15T14:45:11.08-0800 [APP/PROC/WEB/0] ERR     at emitNone (events.js:111:20)
   2018-11-15T14:45:11.08-0800 [APP/PROC/WEB/0] ERR     at Interface.emit (events.js:208:7)
   2018-11-15T14:45:11.08-0800 [APP/PROC/WEB/0] ERR     at Socket.onend (readline.js:147:10)

**Comment by kyung415** [comment]
Would there be a way to possibly run chromium through google cloud and remotely access that instance from another server?

**Comment by aslushnikov** [comment]
@kyung415 I think you can deploy Puppeteer to any cloud provider and access it remotely.

FWIW, there's a [browserless](https://www.browserless.io/) project that does all of this for you. +cc @joelgriffith

I'll close this for now. If you think we can be somehow useful with your case - please let us know.
Thanks!

**Comment by ChabaJosa** [comment]
Hello there! Has anyone tried using the NPM Puppeteer package on IBM i OS.? We have a power 9 and we're trying to implement a pdf solution very similar to [this](https://www.freecodecamp.org/news/how-to-generate-an-html-table-and-a-pdf-with-node-google-puppeteer-32f94d9e39f6/)  but get an error saying 'Unsupported platform: aix '. We have node installed and running but can't seem to get puppeteer to work, we would greatly appreciate any feedback.
