### ISSUE TITLE
headless option doesn't override --headless arg when launching

### ISSUE THREAD

**Issue by craigglennie** [puppeteer/puppeteer#3553]
A [change to `Launcher.defaultArgs()`](https://github.com/GoogleChrome/puppeteer/blame/03d87462606e585318e33cc135fd9bea5e116446/lib/Launcher.js#L245) made in 1.7.0 means that `--headless` is now returned by that call, whereas it previously wasn't. With `--headless` in `args` the `{headless: false}` option is ignored when calling `puppeteer.launch`. 

This might be intentional, and might not be a bug, but if nothing else it's a little confusing. If it's not a bug I think it would be good to emit a warning that `--headless` in `args` overrides `{headless: false}` in `options`, if both are present.

*Edit*: Our use case for this is some custom `args` we want to send to Chromium. We take the defaultArgs and merge our own into it. We now need to explicitly remove `--headless`, which isn't that big of a deal. I understand that the change I referred to above adds support for an `options` argument, so we could also use that to override the new `--headless` behaviour.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.2 (working) and 1.7.0 (not working)
* Platform / OS version: MacOS
* URLs (if applicable): N/A
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

Switch between version 1.6.2 and 1.7.0 to see the behaviour of this code change. In 1.6.2 it launches a browser window, in >= 1.7.0 it runs headless

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({args: puppeteer.defaultArgs(), headless: false});
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```

**What is the expected result?**

`{headless: false}` in options overrides `--headless` in `args` (but maybe this is not the right expectation)

**What happens instead?**

The option is ignored.

**Comment by aslushnikov** [comment]
>  Our use case for this is some custom args we want to send to Chromium. We take the defaultArgs and merge our own into it. We now need to explicitly remove --headless, which isn't that big of a deal.

At least in pptr v1.11.0, the `puppeteer.defaultArgs()` accepts arguments similar to `puppeteer.launch()`. So you can get the desired behavior by passing `headless: false` to the `puppeteer.defaultArgs()` method as well:

```js
const puppeteer = require('puppeteer');

(async () => {
  const options = {headless: false};
  const browser = await puppeteer.launch({...options, args: puppeteer.defaultArgs(options)});
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```

Hope this makes your life easier!
