### ISSUE TITLE
inconsistencies controlling combobox

### ISSUE THREAD

**Issue by JohnTJohnston** [puppeteer/puppeteer#3559]
Not sure if this post belongs here or in stackoverflow.

I'm working with a page that has a combobox element that allows the user to type input or select from dropdown.  This style of dropdown does not appear to be supported by puppeteer (see dropdown element below).  Using page.type() is inconsistent, sometimes works and other times not (missing characters and/or not triggering listener).  Clicking on the dropdown and then using page.evaluate to locate resulting dynamic element is also inconsistent (I think its not always triggering listener).  Dispatching a change event does nothing (as does page.evaluate(element.click()). The most effective method I have identified is to set the value using page.evaluate, and then use page.keyboard.type("Tab").  However, this too is not 100%.

Is this sort of thing a common problem with Puppeteer?  And can anybody offer a suggestion?

Thanks in advance.

typeable element:

`<input role="combobox" aria-labelledby="Employee_EMPLOYEE_ADMIN1_Custom21_label_cell" aria-required="true" class="x-form-text x-form-field x-form-focus" style="width: 142px;" onchange="Employee_onChangeHandler(this, 'Employee' )" id="Employee_EMPLOYEE_ADMIN1_Custom21Name" tabindex="0" value="" type="TEXT" maxlength="48" size="20">`

dropdown element:

`<a class="x-form-trigger x-form-arrow-trigger" id="ext-gen8"></a>`

**Comment by aslushnikov** [comment]
@JohnTJohnston  can you please share a website and a script that you run? I'd love to run it locally to debug what's going on.

**Comment by JohnTJohnston** [comment]
@aslushnikov the website www.concursolutions.com, but unfortunately I can't share requisite logon credentials.

I should have mentioned that it appears to be more robust running locally than running headless on AWS.  Does this make sense?

**Comment by aslushnikov** [comment]
> I should have mentioned that it appears to be more robust running locally than running headless on AWS. Does this make sense?

@JohnTJohnston I'd imaging AWS is much more constrained environment than your local setup, so there are higher chances it exposes certain types of races
