### ISSUE TITLE
Better error message for TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by bgschiller** [puppeteer/puppeteer#3562]
I was trying to use `page.evaluateHandle` and kept getting an error: `TypeError: Converting circular structure to JSON`. Everything I was sending was either Serializable or a JSHandle. Eventually, between reading the source and stepping through in the debugger, I discovered my error. I was passing a JSHandle _inside_ an object as an argument: `{ scope: JSHandle }`.

Would you be open to a patch that caught and re-raised that error, but also logged a warning about "Nesting JSHandles inside objects is not supported"? I would be happy to write it if you think this would be a worthwhile change.

**Comment by aslushnikov** [comment]
> Would you be open to a patch that caught and re-raised that error, but also logged a warning about "Nesting JSHandles inside objects is not supported"? I would be happy to write it if you think this would be a worthwhile change.

@bgschiller Yeah that would be nice. Please go for it!
