### ISSUE TITLE
Evaluate return empty obj

### ISSUE THREAD

**Issue by tg2dex** [puppeteer/puppeteer#3563]
* Puppeteer version: 1.10
* Platform / OS version: win10 64
* Node.js version: 10.13

```
        const notifications = await page.evaluate(async () => {
            const registration = await navigator.serviceWorker.ready;
            const notifications = await registration.getNotifications();
            debugger;
            return notifications;
        });

```

In browser console before return => https://ibb.co/hWJzUf
but after return I have empty obj => [{}]

**Comment by vsemozhetbyt** [comment]
Usually `page.evaluate()` returns empty object if value is not serializable. Check if `notifications` contains functions, circular references, other JSON-incompatible values.

**Comment by tg2dex** [comment]
> 
> 
> Usually `page.evaluate()` returns empty object if value is not serializable. Check if `notifications` contains functions, circular references, other JSON-incompatible values.

Thanks, and what do you say about **overridePermissions**? How I can allow notification by default?

**Comment by vsemozhetbyt** [comment]
Sorry, I do not know(
Maybe if you provide a small complete script code to reproduce the issue, somebody will be able to help more.
