### ISSUE TITLE
copiying puppeteer on another directory causing error

### ISSUE THREAD

**Issue by Hretic** [puppeteer/puppeteer#3564]
in my php website admin can create a puppeteer server  ... so basically i installed puppeteer with npm on the server , compressed it to zip  ... so when admin creates a new server i just unzip the file in a directory 

my zip file contains

node_modules
package.json
package-lock.json
script.js (my code) 

here is the problem , when i download package.json with npm it works fine ... but when i unzip the same package in another directory when i try to run it i get this error 

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/domains/site.com/laravel/robots/robot3/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

am i missing something ? 
my other option is to run ssh commands in php and install puppeteer on fly ... that would be plan b

**Comment by jeremy21212121** [comment]
The EACCES error suggests insufficient permissions to execute the bundled version of chrome that comes with puppeteer.

The user that node is running as needs to be able to execute /home/domains/site.com/laravel/robots/robot3/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome

If you do `ls -l` in that directory, you will probably see that file (the chrome binary) is owned by a user from the system you copied it from. So it might be best to change ownership to the relevant user on the destination system to avoid running into further file permission issues.
