### ISSUE TITLE
Question: smart auto-update

### ISSUE THREAD

**Issue by ab35** [puppeteer/puppeteer#3567]
**Issue:** Chromium has a disk and bandwidth [cost](https://developers.google.com/web/tools/puppeteer/get-started): (~170MB Mac, ~282MB Linux, ~280MB Win) and apparently one can only update the whole chromium package because updates do not come by little patches on top of the existing installation.

**Proposal:** It would be cool if the current installation was able to update just the least amount of bytes by fetching only the required diff instead of having to download the whole package each time.

**Use-Case:** This would be particularly useful in the case of [Carlo applications](https://github.com/GoogleChromeLabs/carlo/issues/92) when shipping them to production.

**Request:** Can chromium [auto-update feature](https://www.chromium.org/chromium-os/chromiumos-design-docs/autoupdate-details) using "_filesystem updates with file-level binary diffs_" be made programmatically available in puppeteer-core ?

**Comment by aslushnikov** [comment]
> his would be particularly useful in the case of Carlo applications when shipping them to production.

@ab35 I though Carlo primarily targets stable chrome which already has auto-update. Am I missing anything?

> Can chromium auto-update feature using "filesystem updates with file-level binary diffs" be made programmatically available in puppeteer-core ?

I had an impression that auto-update doesn't work for Chromium, or at least there's no infrastructure to support this. I might be wrong though.

**Comment by ab35** [comment]
@aslushnikov, targeting stable chrome is a great feature of Carlo, as it allows to quickly jump into development without thinking about downloading anything nor waiting for it: it works out of the box...

But for production applications built with Carlo, it sounds more reasonable to use the built-in channel capability of using chromium instead, because not every user has Chrome installed on their computer...

> I had an impression that auto-update doesn't work for Chromium, or at least there's no infrastructure to support this.

I do not really know... in fact I do not really know either how is Chrome updating itself, if it patches only files or if it downloads a whole new chrome version at each release. For millions of users, it should be quite a huge demand on the network !

**Comment by ab35** [comment]
Chromium's infrastructure seems to be quite old: the website looks like directly coming from the 90's. :smile:

One dreams of an architecture ala git, where one can download chromium/chrome and then, further updates only fetch the strict minimum of bytes for updating already installed files in place...

Now one remembers to have read some [github comment ](https://github.com/cyrus-and/chrome-remote-interface/issues/10#issuecomment-146032907)in the past where @paulirish was talking about how they had to be careful in shipping the remote debugging protocol json file because it would make the chrome package too big for shipping...

**Comment by aslushnikov** [comment]
@ab35 I see there's a downstream issue in Carlo; let's shift all discussion there.

Closing this in favor of https://github.com/GoogleChromeLabs/carlo/issues/92
