### ISSUE TITLE
JSHandles can be evaluated only in the context they were created

### ISSUE THREAD

**Issue by ratkorle** [puppeteer/puppeteer#3568]
I am selecting options from select -> option and each time I select for example country, page reloads with new information, first when I click the dropdown I collect all elementHandles as navigationData, then forEach elementHandle:

`const optionValue = await page.evaluate(value => value.value, navigationData[i]);`
`await page.select(actions.path, optionValue);`

or it doesn't matter, maybe click and other actions.

 I want to go through all of them. I can only select the first one and then I get this error: JSHandles can be evaluated only in the context they were created!.

Can anyone help me with this one please?
Thanks

**Comment by aslushnikov** [comment]
@ratkorle when the page navigates, all javascript objects from the previous page are dropped - there's no way we can keep them since their execution context got destroyed due to navigation. So you'll need to re-fetch `jshandle` object after every navigation.

Hope this helps

**Comment by ratkorle** [comment]
So I am trying to **recreate** ElementHandles each time page reloads. I have this code:

**Function 1:**

```
case:click
try {
   await page.evaluate((el) => {
   return el.click()
   }, 'select'); //dropdown
   await page.waitFor(1500);
} catch (e) {
   console.log(e);
}
break;

case: getNavigation
let navigation = await page.$$('select > option'); //all options from dropdown
break;

case: doActions
let i = 0;
for (elements in navigation) { //for each element of 1st navigation data 
  let result = await function2(commands, i, page); //call this function
  i++;
}
break;
```
Then Function 2:

```
async function function2(commands, i, inPage){
let page = inPage;
if (!page) {
const browser = await puppeteerLambda.getBrowser({ headless: true, slowMo: 100,  args: ['--no-sandbox', '--disable-setuid-sandbox', '--single-process', '--start-fullscreen', '--window-size=1413,749']}); //TODO: setup Proxy
        console.log('opening new page');
        page = await browser.newPage();
....
}
let navigation;
case: click
try {
await page.evaluate((el) => {
return el.click()
}, 'select'); // click again on the dropdown so elements are visible
await page.waitFor(1500);
} catch (e) {
console.log(e);
}
case: getNavigation
navigation = await page.$$('select > option'); //recreating elementHandle array

case: selectOption
const optionValue = await page.evaluate(value => value.value, navigation[i]); assign navigation handle with index that follows
await page.select('select', optionValue); // select option
case: extract // do other actions
......
```
Again I get to **select options 2 times** and then I get this error:

> Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id

When option is selected and page reloads, I am resigning all **elementHandles** to **navigation**. Then I want to select option again with **different index** of **navigation array**. Maybe I am doing this wrong. I expect your advise. @aslushnikov 
Thanks.

**Comment by impactcolor** [comment]
@aslushnikov but what if they are in the same page?

**Comment by theArina** [comment]
From my experience, this may happen if you're trying to do something like this:
```
const element = await page.$(selector);
await page.evaluate(fun, element);
```
