### ISSUE TITLE
Coverage: collect possible suspend points

### ISSUE THREAD

**Issue by mihailik** [puppeteer/puppeteer#3569]
### Steps to reproduce

**Environment**

* Puppeteer version: 1.9.0
* Platform / OS version: win32
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

Collect coverage with `page.coverage.startJSCoverage()`/`page.coverage.stopJSCoverage()`. The resulting data includes:

* url
* text
* ranges:
  * start
  * end

This includes ranges that were RUN, but does not include all RUNNABLE ranges.

**What is the expected result?**

Include in the output the ranges (or even just char positions!) that could run. DevTools clearly shows where it can put breakpoints — even in presence of sourcemaps and 'foreign' languages. That information would be useful.

Without that it requires complex secondary processing to calculate code coverage per line or per file: things like empty whitespace lines, comments or anything else that isn't runnable needs to be excluded SOMEHOW.

Re-parsing the source code to find that information can be done for some cases, but very hard to solve in generic case. If the code was compiled into JS, that coverage post-processing requires non-trivial language-specific logic.

If the suspend points were reported from DevTools back to the `puppeteer` coverage API, none of that complex post-processing would be needed. The information is already there, but needs to be passed through.

**What happens instead?**

Only ranges that were executed are included.

**Comment by aslushnikov** [comment]
> If the suspend points were reported from DevTools back to the puppeteer coverage API, none of that complex post-processing would be needed. The information is already there, but needs to be passed through.

@mihailik I don't think we have anything in protocol to help with this. IIRC from discussions with @ak239, there's no easy way to get this information from V8 either - devtools currently "guesses" the breakpoint location, and gets its factual location sometime later as the breakpoint actually "resolves" to some point in script.

This requires some engineering work upstream in V8/node.js and there's clearly not enough interest from Puppeteer community to justify it. I'll close this for now, but we can revisit this later if the necessity emerges.

**Comment by mihailik** [comment]
Fair point.

@ak239 would you know where roughly in DevTools source that logic lives? I wonder if a variant of that can be used for puppeteer+coverage+sourcemap resolution.

Many thanks!
