### ISSUE TITLE
Suggestion: R package

### ISSUE THREAD

**Issue by mrchypark** [puppeteer/puppeteer#357]
R also need headless browser control function.
Do you have any plan to make R puppeteer packege?
Or is there a way to use the node package in R?

**Comment by paulirish** [comment]
There are other projects that providing bindings to the protocol, but i'm unaware of libraries in R right now: https://github.com/ChromeDevTools/awesome-chrome-devtools

**Comment by mrchypark** [comment]
@paulirish  Thank you for your answer. Could you bundle puppeteer package into a usable state in your web browser? Maybe there is a way to use it. Thank you in advance.

**Comment by Garbee** [comment]
Puppeteer is a node package for your desktop. Not for use within a web browser context.
