### ISSUE TITLE
[V8 API changes.pdf](https://github.com/GoogleChrome/puppeteer/files/2596256/V8.API.changes.pdf)

### ISSUE THREAD

**Issue by cabugsa** [puppeteer/puppeteer#3572]
_Originally posted by @cabugsa in https://github.com/GoogleChrome/puppeteer/issue_comments#issuecomment-439963809_

**Comment by aslushnikov** [comment]
@cabugsa the link is broken (and the whole description looks suspicious). Please re-file with more details.
