### ISSUE TITLE
overridePermissions - allow notifications

### ISSUE THREAD

**Issue by tg2dex** [puppeteer/puppeteer#3573]
* Puppeteer version: 1.10
* Platform / OS version: win10 64
* Node.js version: 10.13

`await context.overridePermissions("https://puush.pw:443", ["notifications"]);`

or

`await context.overridePermissions("https://puush.pw", ["notifications"]);`

Why don`t allow page notification? I must allow by myself => https://ibb.co/hExF20

**Comment by pk992** [comment]
"notifications" is for normal notifications it seems while the "push" permission is for push notifications: https://pptr.dev/#?product=Puppeteer&version=v1.10.0&show=api-browsercontextoverridepermissionsorigin-permissions

But it's not working - related to #3432

**Comment by ivoilic** [comment]
I have the same issue. Even though 'push' appears as an overidePermissions option in the puppeteer docs it throws this error for me. `Protocol error (Browser.grantPermissions): Unknown permission type: push`

**Comment by vsemozhetbyt** [comment]
Not sure why, but the lists of permissions in [`browserContext.overridePermissions(origin, permissions)`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browsercontextoverridepermissionsorigin-permissions) and [Chrome DevTools Protocol `PermissionType`](https://chromedevtools.github.io/devtools-protocol/tot/Browser#type-PermissionType) now differ. The latter does not include `push`. It seems this is still an experimental part that recently has been changed.

**Comment by alamothe** [comment]
Under Chrome's settings I don't see anything that would correspond to `push`:

![Screen Shot 2019-07-26 at 2 10 09 PM](https://user-images.githubusercontent.com/2679255/61930017-2831ca00-afaf-11e9-98ea-f5467bb4968f.png)

Then click on "site settings".

In my case, I was able to enable notifications properly by changing the domain name from `https://facebook.com` to `https://www.facebook.com`

**Comment by govinda-s** [comment]
@aslushnikov 

I think, The puppeteer docs need to be updated wrt https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-browsercontextoverridepermissionsorigin-permissions

As per chrome devtools protocol, the list of permissions has changed. https://chromedevtools.github.io/devtools-protocol/tot/Browser#type-PermissionType

I have tried,
```
await context.overridePermissions(pageUrl, ['notifications']);
```
and found that for overriding push notifications, u need to override `notifications`

**Comment by iqasim-com** [comment]
You just have to pass args
like this

`const browser = await puppeteer.launch({
        headless: false,
        args: [
            "--disable-notifications"
        ]
    });`

**Comment by neekey** [comment]
@mqasim1990 it does not work with headless

**Comment by iqasim-com** [comment]
@neekey, It works for me

**Comment by iqasim-com** [comment]
@neekey can you share your code here?

**Comment by RezaErfani67** [comment]
@iqasim-com 
can you please share your code?

**Comment by tg2dex** [comment]
@aslushnikov

**Comment by pinturic** [comment]
It does not work in headless mode for me either. Is there any fix / workaround for that?

**Comment by alamothe** [comment]
bump

**Comment by RezaErfani67** [comment]
bump

**Comment by OrKoN** [comment]
It looks like notifications are covering push notifications. The following works in the latest versions.

```
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch();

    const domain = 'https://simple-push-demo.vercel.app/'
    const context = browser.defaultBrowserContext();
    const page = await context.newPage();

    await context.overridePermissions(domain, ['notifications']);

    await page.goto('https://simple-push-demo.vercel.app/', {
        waitUntil: "networkidle2"
    });

    await new Promise(resolve => setTimeout(resolve, 1000));

    await page.locator('.c-toggle').click()
    await new Promise(resolve => setTimeout(resolve, 1000));
    await page.locator('#push-payload').fill('test');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await page.locator('.js-send-push-button').click()

    setInterval(async () => {
        const notifications = await page.evaluate(() => {
            return navigator.serviceWorker.ready.then(function(registration) {
                return registration.getNotifications().then(function(notifications) {
                    return notifications;
                })
            })
        });
  
        console.log(notifications.length + ' Notifications');
    }, 5000)
})();
```
