### ISSUE TITLE
[Feature request] need to save page as mhtml

### ISSUE THREAD

**Issue by ashokkumarsand** [puppeteer/puppeteer#3575]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.x
* Platform / OS version: mac
* URLs (if applicable):
* Node.js version: 8.x

**What steps will reproduce the problem?**
Unable to save page as mhtml

**What is the expected result?**
need to save page as mthml or .mht exetension

**What happens instead?**

noting

**Comment by aslushnikov** [comment]
@psybuzz owns the MHTML story in DevTools.

**Comment by viswa18** [comment]
I am also expecting the HTML/URL to .mhtml or .mht conversion.

**Comment by aslushnikov** [comment]
@ashokkumarsand capturing MHTML could be done in the following way with DevTools protocol and its [`page.captureSnapshot`](https://vanilla.aslushnikov.com/#Page.captureSnapshot) method:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  const session = await page.target().createCDPSession();
  await session.send('Page.enable');
  const {data} = await session.send('Page.captureSnapshot');
  console.log(data);
  await browser.close();
})();
```

Hope this helps.
