### ISSUE TITLE
dependency issue while installing

### ISSUE THREAD

**Issue by ehzawad** [puppeteer/puppeteer#358]
```bash
npm install rimraf

I need to install this first manually ! :(

**Comment by ehzawad** [comment]
It is not caching, everytime it is installing chromium

**Comment by ebidel** [comment]
Can you provide repro steps? 

rimraf is [included as a dependency](https://github.com/GoogleChrome/puppeteer/blob/master/package.json#L28), so you should not need to install it manually.

Regarding chromium...a local bundle of chromium is downloaded when you install Puppeteer. See https://github.com/GoogleChrome/puppeteer#q-which-chromium-version-does-puppeteer-use.

**Comment by ehzawad** [comment]
Now it is working fine.. Thank you @ebidel
