### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by Mashpy** [puppeteer/puppeteer#3588]
* Platform / OS version: Ubuntu 16.04 (aws ec2)
* Node.js version: v8.12.0
* NPM: 6.4.1

I have added [browsershot](https://github.com/spatie/browsershot) on my laravel project.  Pupperteer is required for browsershot.

**Using ssh** I have run this command -
sudo npm install --global --unsafe-perm puppeteer

```
> puppeteer@1.10.0 install /usr/lib/node_modules/puppeteer
> node install.js

**INFO** Skipping Chromium download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" was set in npm config.
+ puppeteer@1.10.0
updated 1 package in 1.724s

```

and successfully installed puppeteer. 

But when trying to reload **the website** I am getting this error

```
ProcessFailedException
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/home/ubuntu/websites/onlinebooksreview_production/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/home\/ubuntu\/websites\/example.com\/public\/uploads\/videos\/temp_data\/template_1\/temp_design.html","action":"screenshot","options":{"type":"png","path":"\/home\/ubuntu\/websites\/onlinebooksreview_production\/public\/uploads\/videos\/temp_data\/template_1\/image00001.png","args":[],"viewport":{"width":1280,"height":720}}}'" failed.

Exit Code: 1(General error)

Working directory: /home/ubuntu/websites/exmple_site/public

Output:
================


Error Output:
================

┌──────────────────────────────────────────────────────┐
│ npm update check failed │
│ Try running with sudo or get access │
│ to the local update config store via │
│ sudo chown -R $USER:$(id -gn $USER) /var/www/.config │
└──────────────────────────────────────────────────────┘
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
at Launcher.launch (/usr/lib/node_modules/puppeteer/lib/Launcher.js:115:15)
at <anonymous>
```
On the website how can i solve this problem?

Note: I know this is very common problem and I tried to implement all the solutions. But failed to solve.

**Comment by aslushnikov** [comment]
@Mashpy I see that the Chromium download was skipped due to the PUPPETEER_SKIP_CHROMIUM_DOWNLOAD flag set in npm config. This seems to be the problem in your case.

**Comment by gombosg** [comment]
Same issue here after upgrading to Puppeteer 1.11 with Yarn (we are not using NPM, and it's not a global installation). Interestingly, Chromium is present in the `.local-chromium` directory.
Issue persists after deleting `node_modules` and doing a `yarn install`.
I tried manually removing and reinstalling the package, same issue.

`install.js` also sees the Chromium revision downloaded, so it does nothing and just exits.

Looking into the runtime exception, it is looking for a `.local-chromium` dir with the wrong number. E.g.
`Error: ENOENT: no such file or directory, stat '....../node_modules/puppeteer/.local-chromium/linux-599821'` but the directory has number `609904`.

Going up the stack trace, I found that class Launcher gets a bad `preferredRevision` value, which is read from `index.js` which reads from Puppeteer's `package.json`. And there the number is not matching the folder's name.

Interestingly, downgrading to 1.10 then upgrading back to 1.11 solved the issue and regenerated the right number in `package.json`.

It's like chasing a ghost. Sorry for not being able to zero in on the issue.

**Comment by aslushnikov** [comment]
@gombosg `install.js` uses a bunch of env variables to pick the revision to download (check out line 41):

https://github.com/GoogleChrome/puppeteer/blob/45c4477e9fc80a159d8cbfe13cbe1aa5544a53c1/install.js#L39-L44

If you were to have some of these env variables or npm configs set, it'd explain the behavior you describe here.

It might also be related to some aggressive caching - this would explain why downgrading/upgrading helped.

I don't think there's anything we can do on Puppeteer-side regarding this, let me know if I'm wrong.
Closing this for now.

**Comment by ghost** [comment]
Why not try to switch the mirrors of puppeteer_download_host? It is a bit more simple, just do something like the following configuration option in `~/.npmrc` configuration file.
`puppeteer_download_host=https://npm.taobao.org/mirrors`

**Comment by ThisIsRoy1** [comment]
**I solved it like this**:

`  const browser = await puppeteer.launch({  executablePath: "./node_modules/puppeteer/.local-chromium/win64-656675/chrome-win/chrome.exe"});`

note the **win64-656675** in the path, if you're on a different operating system you will need to point to the appropriate folder.

puppeteer version: 1.16.0

**Comment by RanjithaBaskaran** [comment]
@aslushnikov I am facing the same issue . I have tried browserFetcher but it's giving the below error.

> Error: connect ETIMEDOUT 172.217.167.176:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  -- ASYNC --
    at BrowserFetcher.<anonymous>

**Comment by samg0rd** [comment]
@ThisIsRoy1 ThisIsRoy1 where did you put that line of code that fixed the issue ?

**Comment by AlessandroAnnini** [comment]
I used 
```js
const executablePath =  './../node_modules/puppeteer/.local-chromium/mac-609904/chrome-mac/Chromium.app';
```
but the problem is not changing
`puppeteer-core version: 1.11.0`
`puppeteer version: 1.11.0`

**Comment by sameersemna** [comment]
> PUPPETEER_CHROMIUM_REVISION

Instead edit the node_modules/puppeteer/package.json, and set the following
`
  "puppeteer": {
    "chromium_revision": "699988"
  },
`
and just run:
`PUPPETEER_CHROMIUM_REVISION=699988 npm install`

**Comment by manibharathytu** [comment]
I had installed puppeteer with old node js (8.0) so there was no chromium download during puppeteer install. After updating to latest (12.0), doing "npm i puppeteer" downloaded chromium.

**Comment by kieranmakes** [comment]
==========================================================================================
                                                      
### WORKING SOLUTION 

run:
**$ npm config set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD false**
**$ npm config set ignore-scripts false** 
then:
**$ npm config set ignore-scripts true** 
change the flag for the ignore-scripts back as it poses a security threat if left false

==========================================================================================

**Comment by hshoja** [comment]
After couple of hours googling and reading many comments and discussions, trying several approach finally I resolved the problem with this solution.
`
OS: Windows 10
node: 14.16.1
puppeteer: 7.0.1
`
I saw in the node_modules/puppeteer/ folder and found that there isn't any .local-chromium folder so I created this path manually
```
node_modules/puppeteer/.local-chromium/win64-<your_chrome_version>/chrome-win
```
Then I downloaded the chromium browser from[ this link](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html) (your_chrome_version) and so copied it to the path so that you need to see the *chrome.exe* in this *url*
```
node_modules/puppeteer/.local-chromium/win64-<your_chrome_version>/chrome-win/chrome.exe
```
That's it. it worked for me.

**Comment by mosesegboh** [comment]
> After couple of hours googling and reading many comments and discussions, trying several approach finally I resolved the problem with this solution.
> `OS: Windows 10 node: 14.16.1 puppeteer: 7.0.1`
> I saw in the node_modules/puppeteer/ folder and found that there isn't any .local-chromium folder so I created this path manually
> 
> ```
> node_modules/puppeteer/.local-chromium/win64-<your_chrome_version>/chrome-win
> ```
> 
> Then I downloaded the chromium browser from[ this link](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html) (your_chrome_version) and so copied it to the path so that you need to see the _chrome.exe_ in this _url_
> 
> ```
> node_modules/puppeteer/.local-chromium/win64-<your_chrome_version>/chrome-win/chrome.exe
> ```
> 
> That's it. it worked for me.

@hshoja thanks you very much man, your solution worked nicely for me, kudos man.
