### ISSUE TITLE
Puppeteer : How to use puppeteer on EC2 server.

### ISSUE THREAD

**Issue by vinayakmali** [puppeteer/puppeteer#3590]
hi everyone,
I am a newbie, trying a few things with the puppeteer, So currently what I have done is
I using node js, Nginx server on my local machine, and I have created a web app which creates the instance of the puppeteer, opens an instance of chromium and I can scrap data from that chromium instance. This works fine for me locally.
Now I am wondering how can I deploy this as a web app where I want it should create the instance per client and scrap data for every client

So I have the following questions::
1. if I have this setup running on the server, will it be creating chromium instance per client and client can access this instance like the local browser on their machine
2. or will I have to ask every client to install puppeteer on their local machine and my code and access puppeteer on client machine.

Please help.

**Comment by bahattincinic** [comment]
I think this question isn't related to puppeteer. 

if your customer wants to connect your chromium server, they want to use the following method;

```javascript
const browser = await puppeteer.launch();
await puppeteer.connect({ browserWSEndpoint: 'ws://<yourServer>:3000' });
```

I didn't try but you can manage chrome process with the following project;

https://github.com/joelgriffith/browserless

if this answer doesn't cover your problem, please give a detailed explanation.
