### ISSUE TITLE
How to learn Pupeteer Chromium Port and Host?

### ISSUE THREAD

**Issue by caglartufan** [puppeteer/puppeteer#3592]
How can I learn Chromium works on ports and host? Host is 127.0.0.1 ok, but what is port?

**Comment by aslushnikov** [comment]
@n3pixowe you can either specify port explicitly using the `--remote-debugging-port` Chromium flag, or let Chrome pick a random one by using `--remote-debugging-port=0`.

In the latter case, the WS endpoint will be dumped into Chrome's stdout.
It looks like this.

```bash
DevTools listening on ws://127.0.0.1:46639/devtools/browser/4d24feff-97ac-42a0-acd7-721b75a1a644  
```
