### ISSUE TITLE
Xpath does not work with RSS

### ISSUE THREAD

**Issue by liquidcms** [puppeteer/puppeteer#3594]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: no idea, latest
* Platform / OS version: Win10
* URLs (if applicable): https://ottawa.ca/en/news.rss
* Node.js version: 10.13.0

**What steps will reproduce the problem?**
  I.amOnPage('https://ottawa.ca/en/news.rss');
  I.seeElement("//item");

**What is the expected result?**
test should pass

**What happens instead?**
expected visible elements '[]' not to be empty

At first i assumed this was a codecept issue but I think the seeElement() method is part of Puppeteer; so possibly the problem is that Puppeteer does not properly parse RSS. I tried an online Xpath tester with sample RSS code and the xpath selector works as expected.

**Comment by aslushnikov** [comment]
@liquidcms the reason this doesn't work for you is because browser doesn't know what to do with RSS - it treats it as just an XML file which it nicely renders as-is to the user, using HTML.

Generally, you don't need browser to handle RSS. You can use any HTTP library to fetch RSS, and then any XML parser to parse and traverse it. Using browser for this is definitely an overkill.

Hope this helps.

**Comment by liquidcms** [comment]
This might explain the issue; but what I am trying to do is test an RSS feed. It seems like i should be able to user CodeceptJS and Puppeteer to simply check if items exist on the feed. But no luck. I am guessing your answer is stating that Puppeteer doesn't know how to handle RSS feeds, correct?

**Comment by vsemozhetbyt** [comment]
I do not know about test frameworks integration, but a simple test can be done this way:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://ottawa.ca/en'); // To avoid CORS error.

    const nodeIsInFeed = await page.evaluate(async () => {
      const response = await fetch('https://ottawa.ca/en/news.rss');
      const xmlSource = await response.text();
      const xmlDoc = (new DOMParser()).parseFromString(xmlSource, 'application/xml');

      return xmlDoc.evaluate(
        '//title', xmlDoc, null, XPathResult.ANY_UNORDERED_NODE_TYPE, null
      ).singleNodeValue !== null;
    });

    console.log(nodeIsInFeed);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Maybe there are simpler ways.
