### ISSUE TITLE
Flag to enable Hide network messages

### ISSUE THREAD

**Issue by Annihil** [puppeteer/puppeteer#3595]
Would it be possible to add a flag to toggle **Hide network messages** in Chrome at puppeteer's launch?

In Chrome, this is how to toggle it:
DevTools -> Settings -> General -> Console -> Hide network messages

Thanks in advance!

**Comment by aslushnikov** [comment]
@Annihil what do you mean by "hide network messages"? Puppeteer doesn't print any messages anywhere.

**Comment by Annihil** [comment]
Right, puppeteer itself does not, but I'm redirecting chrome's console logs using
```
page.on('console', consoleMessage => console.log(consoleMessage.text()));
```
and each time chrome sends an XHR and there is a failure, it outputs
```
Failed to load resource: the server responded with a status of XXX (Reason)
```

**Comment by aslushnikov** [comment]
> Right, puppeteer itself does not, but I'm redirecting chrome's console logs using

I'd filter out these message from your `page.on('console')` callback; this should work quite well for your usecase.
