### ISSUE TITLE
page.content(): shows wrong / not latest content

### ISSUE THREAD

**Issue by BennerGe** [puppeteer/puppeteer#3597]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.10.0
* Platform / OS version: Ubuntu 18.04
* Node.js version: v8.10.0

**What steps will reproduce the problem?**

```javascript
const puppeteer = require('puppeteer');
const fs = require('fs');
(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://shop.polymer-project.org/', {waitUntil: 'networkidle0'});
  await page.screenshot({path: 'example.png'});
  const html = await page.content();
  fs.writeFile('page.html', html, _ => console.log('HTML saved'));
  await browser.close();
})();
```

**What is the expected result?**
Screenshot and saved HTML should be the same. 

**What happens instead?**
Screenshot is correct, as it's shown when you load [Polymer Shop](https://shop.polymer-project.org/)
page.content() delivers page from a very early stage of loading.

**Comment by aslushnikov** [comment]
@BennerGe why do you think that saved HTML is not the right one? It works fine for me - after the HTML is saved, I can successfully load it again into the page:

```js
const puppeteer = require('puppeteer');
const fs = require('fs');
(async() => {
  const browser = await puppeteer.launch({ 
    headless: false,
  });
  const page = await browser.newPage();
  await page.goto('https://shop.polymer-project.org/', {waitUntil: 'networkidle0'});
  await page.setContent(fs.readFileSync('page.html', 'utf8'));
})();
```

Note though: the HTML you save depends on other resources in the `https://shop.polymer-project.org/` website, so you can't just load the HTML as-is in Chrome.

**Comment by BennerGe** [comment]
I have tried it again with the following code: 

Save .html:
```javascript
const puppeteer = require('puppeteer');
const fs = require('fs');
(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://shop.polymer-project.org/', {waitUntil: 'networkidle0'});
  await page.screenshot({path: 'example.png'});
  const html = await page.content();
  fs.writeFile('page.html', html, _ => console.log('HTML saved'));
  await browser.close();
})();
```

Load .html:
```javascript
const puppeteer = require('puppeteer');
const fs = require('fs');
(async() => {
  const browser = await puppeteer.launch({ 
    headless: false,
  });
  const page = await browser.newPage();
  await page.setContent(fs.readFileSync('page.html', 'utf8'));
})();
```

This leads to the following output
![polymer_shop](https://user-images.githubusercontent.com/26544180/49306975-0fcae780-f4d4-11e8-88ca-314a09d339b5.png)


But you are right, that might come from the missing dependencies.
My idea behind this was to load the sites from my SPA with a raspberry and load it to my webspace frequently, to have pre-rendered sites for search engine bots. I think running puppeteer directly doesn't work because it's not vServer, but only a webspace. But I dont know if this can work.

**Comment by aslushnikov** [comment]
> My idea behind this was to load the sites from my SPA with a raspberry and load it to my webspace frequently, to have pre-rendered sites for search engine bots.

For this usecase, the `page.content()` might be good enough: search engines mostly care about markup and will be quite satisfied if there are good keywords in there.

Please check out a relevant article about Puppeteer and SSR: https://developers.google.com/web/tools/puppeteer/articles/ssr

**Comment by Antimatterr** [comment]
> > My idea behind this was to load the sites from my SPA with a raspberry and load it to my webspace frequently, to have pre-rendered sites for search engine bots.
> 
> For this usecase, the `page.content()` might be good enough: search engines mostly care about markup and will be quite satisfied if there are good keywords in there.
> 
> Please check out a relevant article about Puppeteer and SSR: https://developers.google.com/web/tools/puppeteer/articles/ssr

I am trying to get HTML content from a website but it does not load all the content.
for example there are 180 list items but it only loads 130 and doesn't load any item after that.
