### ISSUE TITLE
pdf width and height scales differently as snapshot

### ISSUE THREAD

**Issue by phuang0619** [puppeteer/puppeteer#3600]
* Puppeteer version: 1.10.0
* Platform / OS version: mac HighSierra 10.13.4
* URLs (if applicable):
* Node.js version: v7.6.0

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');
const args = process.argv;
var browser;
var page;

(async() => {
	try{
	    pageWidth = 800;
	    pageHeight = 990;
	    
	    browser = await puppeteer.launch({timeout:0,args: ['--no-sandbox', '--disable-setuid-sandbox','-disable-web-security']});
	    page = await browser.newPage();					    
	    await page.setViewport({width:pageWidth, height:pageHeight});
	    await page.goto("file:" + args[3], { timeout: 0, waitUntil: 'networkidle0' });
						
	    await page.screenshot({path: '_/test.png'});
	    await page.pdf({path: args[4], printBackground: true, width: pageWidth, height:pageHeight});
	}catch(err){
		console.log(err);
	}finally{
		process.exit();
	}
})();`
```

**What is the expected result?**
The pdf is having page break the same way as the snapshot did, meaning no cutting off of the chart

**What happens instead?**
The width and height of the pdf's included range seemed to be scaled differently as the snapshot.
I was expecting 800 and 990 is about right for a chart to fit in a page, but turns out 
800 and 990 means more in pdf than it does in snapshot.
The parameter of width and height pass in page.pdf does make a difference, just that there seems to be a scale comparing to how snapshot reacts to viewport size.
![test](https://user-images.githubusercontent.com/43661970/49125244-5d8bf800-f2fa-11e8-8a60-50551813717f.png)
[test.pdf](https://github.com/GoogleChrome/puppeteer/files/2622616/test.pdf)

**Comment by phuang0619** [comment]
Looks like width and height were scaled to 3/2 times of its passed parameter.
In my case In order to get 600 x 440, 
I have to actually put in width 400 (400 = 600 x 2/3)
and height 294  (293.3333 = 440 x 2/3) to get it.

Hopefully, this helps

**Comment by poppinlp** [comment]
I got this issue too with diff scale. The output pdf size is 750 * 750 when i pass 1000 * 1000 to puppeteer `pdf` method.

**Comment by mehunk** [comment]
Yes, this problem happened to me as well.
