### ISSUE TITLE
when page.goto set  'domcontentloaded',it will not follow the 302 redirect

### ISSUE THREAD

**Issue by secreter** [puppeteer/puppeteer#3601]
### Steps to reproduce

**Tell us about your environment:**
In docker node:8

* Puppeteer version: 1.10
* Platform / OS version:Linux centos7
* URLs (if applicable): https://s.weibo.com/weibo?q=&xsort=hot&Refer=SWeibo_box
* Node.js version: 8

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```javascript
let url='https://s.weibo.com/weibo?q=&xsort=hot&Refer=SWeibo_box'
const response = await spider.page.goto(url, {
      waitUntil: 'domcontentloaded',
      timeout: 30000
});
```

**What is the expected result?**
This url response a 302 redirect,I would like puppeteer follows the redirect,go to the new page.

**What happens instead?**
This url response a 302 redirect,and then looks like does not trigger the event domcontentloaded,
cause timeout.
Instead, in my local environment,windows OS,this bug won`t happen.

**Comment by aslushnikov** [comment]
@secreter the following works just fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://s.weibo.com/weibo?q=&xsort=hot&Refer=SWeibo_box', {waitUntil: 'domcontentloaded'});

  await browser.close();
})();
```

But I see you use some `spider`. It could be, that you also use request interception - in this case it might be related to https://github.com/GoogleChrome/puppeteer/issues/3471.

> This url response a 302 redirect,and then looks like does not trigger the event domcontentloaded,
cause timeout. Instead, in my local environment,windows OS,this bug won`t happen.

This sounds like it has something to do with your environment 🤔 I don't think we'll be able to help in this case. I'd try filing downstream to whatever "spider" you use.

**Comment by secreter** [comment]
Spider is ```const spider = await puppeteer.launch();```It is my fault.
