### ISSUE TITLE
event: 'dialog' does not trigger for 'Sign in'

### ISSUE THREAD

**Issue by rasmusgadensgaard** [puppeteer/puppeteer#3604]
* Puppeteer version: 1.10.0
* Platform / OS version: Windows Server 2016 Standard
* Node.js version: 8.12.0

I'm trying to make the following work:

page.on('dialog', async dialog => {
		console.log("Got the login dialog, authenticating....");
		await page.authenticate({username:"xxx", password:"xxx",waitUntil: 'networkidle0'});
	});

**What is the expected result?**
If a login dialog appears, login. If not run remaining code.

**What happens instead?**
Code execution stops when recieving the login prompt. 

I'm trying to achieve mainting a session between browser open and close. I store a cookie as a json file, and load that in the beginning of my script. If the cookie has become invalid, the webpage will make the authentication prompt. If this happens, puppeteer should just login again, however it seems the login dialog is not part of the event type "dialog".

**Comment by aslushnikov** [comment]
>  If the cookie has become invalid, the webpage will make the authentication prompt. If this happens, puppeteer should just login again, however it seems the login dialog is not part of the event type "dialog".

It's hard to say what's going on without having a script and URL in question. 

The "login" dialog seems to be a page-initiated dialog, probably rendered with WebPlatform. The [`'dialog'`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-event-dialog) event is only fired for javascript-initiated dialogs, such as `alert`, `prompt` and `confirm`. I wouldn't expect it to fire for login dialogs.

So I'd suggest automating this dialog using [`page.type`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagetypeselector-text-options) and [`page.click`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageclickselector-options) - the same way you automate the rest of the web site.

Feel free to re-file with more details (reproduction scripts and urls) - that's as much as I could infer from the information given here.

**Comment by ISNIT0** [comment]
@aslushnikov I've an example page here: https://www.ussu.co.uk/getinvolved/clubs

Seems to trigger an HTTP login, but dismissing is fine for my purposes. How can we detect/cancel these logins?

**Comment by sbergot** [comment]
@ISNIT0  I got it to work by detecting the conditions of the prompt in the request event:

https://blog.stevensanderson.com/2008/08/25/using-the-browsers-native-login-prompt/ 

What I do is listen to the response page event and check for the following conditions:
- status is 401
- www-authenticate header exists
