### ISSUE TITLE
 Standard Consistency - Align major version of puppeteer to chromium

### ISSUE THREAD

**Issue by ptkdev** [puppeteer/puppeteer#3609]
I love consistency. Currently puppeters use their numbering to establish the version, it would be more correct to align it with chromium.

## Now
| puppeteer version | chromium version |
|--------------------------|-------------------------|
| v1.8.0                    | v71.0.3542            |
| v1.9.0                    | v71.0.3563            |
| v1.10                     | v72.0.3582            |

## After
| puppeteer version | chromium version |
|--------------------------|-------------------------|
| v71.0.3542            | v71.0.3542            |
| v71.0.3563            | v71.0.3563            |
| v72.0.3582            | v72.0.3582            |

## Other case study
`Google Remote Desktop` is a project that is closely related to chromium and follows these version specifications, example: Google Remote Desktop v71 work with Chromium v71

**Comment by aslushnikov** [comment]
Hey @ptkdev, thanks for the suggestion.

I like our current approach more: we're committed to [semver](https://semver.org/) format so our clients know what to expect when they update. Also, the suggested approach is quite foreign to the npm ecosystem and wouldn't play nice with various NPM auditing tools.
