### ISSUE TITLE
It doesn't appear to be honoring /etc/hosts?

### ISSUE THREAD

**Issue by taf2** [puppeteer/puppeteer#361]
Host names added in /etc/hosts don't appear to be working when running on OSX.

**Comment by aslushnikov** [comment]
I'm running Sierra 10.12.6, and the following worked for me:
1. Added `somehost` to `/etc/hosts` which points to google
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
172.217.7.46	somehost
```
2. Ran the following command (I'm not exactly sure what it's doing, copied it from the internet):
```
dscacheutil -flushcache; sudo killall -HUP mDNSResponder
```
3. Ran the following script:
```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://somehost/', {waitUntil: 'networkidle'});
  await page.screenshot({ path: 'test.png' });
  browser.close();
})();
```
4. Which gave me the following screenshot:
![test](https://user-images.githubusercontent.com/746130/29443443-e6c2e8b0-838c-11e7-9162-704bdf78f7ea.png)

**Comment by pavelfeldman** [comment]
Closing for now, please follow up if you have a question.

**Comment by taf2** [comment]
The issue here is actually with validation of hostnames... for example, if you use an invalid TLD it fails...

e.g.
cat /etc/hosts
127.0.0.1    fake-domain-with-invalid-tld.dev

<script src="//fake-domain-with-invalid-tld.dev/script.js"></script>

fails

page.on('requestfinished', (req) => {
  console.log(req.method, req.url);
});
page.on('requestfailed', (req) => {
  console.log('FAILED:', req.url, req);
});
await page.goto('http://fake-domain-with-invalid-tld.dev/fake.html', {waitUntil: 'networkidle', networkIdleTimeout: 3000});

@pavelfeldman ^^

**Comment by Tactless7** [comment]
It doesn't work either with docker. Hosts can't be resolved : 
Error : Failed to navigate: http://domain-in-hosts.dev:some-port/url

**Comment by knownasilya** [comment]
I ended up changing from .dev to .test, the only issue is that I cannot test Google Oauth any more, because they don't allow any non-real TLDs, like .test

![screen shot 2017-10-26 at 1 15 30 pm](https://user-images.githubusercontent.com/34726/32067045-c448a2c6-ba4f-11e7-883a-0bb0cac6a5ef.png)

**Comment by Garbee** [comment]
`.dev` is a registered TLD. Which also now is HSTS for the entire domain built into Chrome. So, that should not be used anyways. You should be using a reserved TLD such as `.localhost` to do local domain routing.

**Comment by knownasilya** [comment]
Unfortunately `.localhost` doesn't work with OAuth redirect either. Any suggestions on that end?

**Comment by krishnaguragain** [comment]
+1
