### ISSUE TITLE
How to input rich text to editor in an iframe?

### ISSUE THREAD

**Issue by inevity** [puppeteer/puppeteer#3611]
Have open the page,which have the iframe
```
<iframe id="ueditor_0" allowtransparency="true" width="100%" height="100%" frameborder="0" src="javascript:void(function(){document.open();document.write(&quot;<!DOCTYPE html><html xmlns='http://www.w3.org/1999/xhtml' ><head><style type='text/css'>body{font-family:sans-serif;}</style><link rel='stylesheet' type='text/css' href='https://res.wx.qq.com/mpres/zh_CN/htmledition/comm_htmledition/style/widget/ueditor_new/themes/iframe3f3927.css'/></head><body class='view' lang='en' ></body><script type='text/javascript'  id='_initialScript'>setTimeout(function(){window.parent.UE.instants['ueditorInstant0']._setup(document);},0);var _tmpScript = document.getElementById('_initialScript');_tmpScript.parentNode.removeChild(_tmpScript);</script></html>&quot;);document.close();}())" style="height: 400px;"></iframe>
```

  now  once open the web page , I run 
```
await page.click('#ueditor_0');
await page.focus('#ueditor_0');
await page.keyboard.type(clipboardy.readSync());// read from clipboard content which is from one copied page( markdown html page including image)
```
which only paste the text,no formated text and image .

   How do paste the rich text to  the editor in iframe?
I also   tried the keyboard combo ctrl + v (on macos), but get nothing
  
```
await page.keyboard.down('Meta');
await page.keyboard.press('KeyV');
await page.keyboard.up('Meta');
```
Notes: it is ok to use the ctrl +A  by the puppeteer keyboard to select all in the editor

**Comment by opt9** [comment]
In my case, iframe does not have a ID or Name. 

`<iframe src="" style="width: 100%; height: 100%;" class="cke_wysiwyg_frame cke_reset" title="Rich Text Editor1" aria-describedby="cke_79" tabindex="0" allowtransparency="true" frameborder="0">... blah blah blah...</iframe>`

How can I select and insert a text.

**Comment by inevity** [comment]
You could use page.frames() to find the frame by style attr.

**Comment by opt9** [comment]
@inevity
Could you please show me some example codes to do it?

**Comment by inevity** [comment]
```
const editFrame = await page.frames().find(f => f.name() === 'ueditor_0');
const inputb = await editFrame.$('#html'); 
```
// replace f.name()===  as frame api  or use eval to use raw html api.

**Comment by superleemo** [comment]
how to insert an image?

**Comment by inevity** [comment]
Now the clipboard async api got support on chrome, So maybe we can paste image @fxxku
