### ISSUE TITLE
Unable to Compile Headless Chromium r609904

### ISSUE THREAD

**Issue by alixaxel** [puppeteer/puppeteer#3616]
Since version 1.11.0, I no longer seem to be able to compile the bundled headless Chromium in AWS.

Would be great to get some guidance on what changed, if anything.

### Steps to Reproduce

**Tell us about your environment:**

* Puppeteer: 1.11.0 (Chromium 72.0.3618.0 - r609904)
* Platform / OS: Amazon Linux AMI 2017.09.0.20170930 x86_64 HVM GP2

**What steps will reproduce the problem?**

When using the Ansible playbook available [here](https://github.com/alixaxel/chrome-aws-lambda/tree/master/_/ansible), that replicates the official [Linux build instructions](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#Install-additional-build-dependencies), and compiles headless Chromium statically (for compatibility with AWS Lambda), the [_Compiling Headless Chromium_](https://github.com/alixaxel/chrome-aws-lambda/blob/f6069ae644102948c47523e1699eaaa926af714c/_/ansible/plays/chromium.yml#L239) step fails (but only for `r609904`, previous revisions compile just fine).

For reference, the following GN arguments are set:

```yaml
    - name: Creating Headless Chromium Configuration
      copy:
        content: |
          import("//build/args/headless.gn")
          enable_nacl = false
          is_component_build = false
          is_debug = false
          remove_webcore_debug_symbols = true
          symbol_level = 0
        dest: /srv/source/chromium/src/out/Headless/args.gn
```

And then ninja is called like so:

```yaml
    - name: Compiling Headless Chromium
      shell: |
        autoninja -C out/Headless headless_shell
      args:
        chdir: /srv/source/chromium/src
```

**What is the expected result?**

Compilation should succeed.

**What happens instead?**

Compilation fails with the following error:

```
# autoninja -C out/Headless headless_shell
/srv/source/depot_tools/ninja -C out/Headless headless_shell
ninja: Entering directory `out/Headless'
[95/22176] ACTION //mojo/public/js:bindings_lite(//build/toolchain/linux:clang_x64)
FAILED: gen/mojo/public/js/mojo_bindings_lite.js 
python ../../third_party/closure_compiler/js_binary.py --compiler ../../third_party/closure_compiler/compiler/compiler.jar --output gen/mojo/public/js/mojo_bindings_lite.js --deps gen/mojo/public/js/bindings_lite_sources.js_library gen/mojo/public/js/control_message_bindings_lite.js_library --sources ../../mojo/public/js/bindings_lite.js --flags compilation_level=ADVANCED_OPTIMIZATIONS generate_exports --externs ../../third_party/closure_compiler/externs/chrome.js ../../third_party/closure_compiler/externs/polymer-1.0.js ../../third_party/closure_compiler/externs/mojo_core.js ../../third_party/closure_compiler/externs/pending.js
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

[132/22176] CXX obj/services/audio/public/mojom/constants/constants.mojom.o
ninja: build stopped: subcommand failed.
```

**Comment by alixaxel** [comment]
I noticed that r609904 points to commit [99a174b7b1d13e53dbb2cd3aab84ba589c862d86](https://crrev.com/609904).

Assuming the file on [chrome/VERSION](https://chromium.googlesource.com/chromium/src/+/99a174b7b1d13e53dbb2cd3aab84ba589c862d86/chrome/VERSION) is correct, it should be version 72.0.3617.0 and not 72.0.3618.0?

**Comment by alixaxel** [comment]
Solved.

**Comment by h2non** [comment]
> it should be version 72.0.3617.0 and not 72.0.3618.0? 

I noticed the same. Build number does not correlate with the Chromium version specified in the release notes.

**Comment by pwagener** [comment]
For anyone finding this later, the original issue described above ("... Unsupported major.minor version 52.0")  is because the Amazon Linux AMI defaults to Java 1.7, and the Chromium build tools pick that up as a part of the build process.  They'll even install Java 1.7 as a part of the process if it isn't there.  But the build won't work with 1.7.

You can change the default by using `update-alternatives`:

```
$ sudo update-alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
   1           /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java
   2           /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
*+ 3           /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java

Enter to keep the current selection[+], or type selection number: 2       
$
```
