### ISSUE TITLE
Docker Alpine Puppeteer setup crashing on Ubuntu/Arch Linux while working on macOS 

### ISSUE THREAD

**Issue by RinFuramingo** [puppeteer/puppeteer#3617]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: macOS Mojave (10.14), Ubuntu Server 18.04, ArchLinux
* URLs (if applicable):
* Node.js version: latest

**What steps will reproduce the problem?**

`Dockerfile`
```Dockerfile
FROM node:10-alpine as build

WORKDIR /app
COPY . /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN yarn
RUN yarn build

FROM node:10-alpine

# Installs latest Chromium (68) package.
RUN apk update && apk upgrade && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
  apk add --no-cache \
  chromium@edge \
  nss@edge

WORKDIR /app
COPY --from=build /app /app

# Add user so we don't need --no-sandbox.
RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
  && mkdir -p /home/pptruser/Downloads \
  && chown -R pptruser:pptruser /home/pptruser \
  && chown -R pptruser:pptruser /app

# Run everything after as non-privileged user.
USER pptruser

EXPOSE 4000

CMD node build
```

`docker-compose.yml`
```yaml
  service:
   ...
    cap_add:
      - SYS_ADMIN
```

`index.js`
```JavaScript
const browser = await puppeteer.launch({
  executablePath: '/usr/bin/chromium-browser'
});
```

**What is the expected result?**

It should either crash on all platforms or just work fine, but it doesn't.

**What happens instead?**

On macOS, the whole thing works seamlessly, but on purely Linux-based systems it crashes using the exact same setup. I'm not sure if this is due to some kind of kernel thing but it's pretty strange.

**Comment by gidztech** [comment]
My understanding is that Puppeteer is only guaranteed to work with the Chromium binary it's shipped with. It looks like the [latest musl libc build for Alpine](https://pkgs.alpinelinux.org/packages?name=chromium) is not compatible with Puppeteer 1.11.0. The current build is 68.0.3440.106 but the version shipped with Puppeteer is 72.0.3617.0.

You'll want to use Puppeteer 1.4.0 according to [Running on alpine documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine). The alternative is to use a different base like node slim, and pull in the relevant dependencies.

I personally use [chrome-headless-trunk](https://hub.docker.com/r/alpeware/chrome-headless-trunk/) pre-built Docker images, and I fetch the supported image version referenced in Puppeteer's `package.json`. That way, I know it will definitely be compatible. It does use Ubuntu as a base, which is a bit heavier though.

**Comment by RinFuramingo** [comment]
@gidztech that sounds very logical, however I'm wondering why that problem would only occur on one machine or rather one operating system and not all? It's kind of strange that the exact setup _will_ work on macOS while it's breaking on every other platform 🤔 Maybe there's some other reason for that, like something about in-depth kernel stuff or Docker configuration I have misunderstood. I will investigate into this further 👍

**Comment by aslushnikov** [comment]
@RinFuramingo I agree with @gidztech's diagnose. You'll need to use an older version of Puppeteer if you have an old chromium.

> I'm wondering why that problem would only occur on one machine or rather one operating system and not all? 

Not really sure why; I'll close this for now, feel free to update the issue with information if you find anything interesting.
