### ISSUE TITLE
Cannot use `getEvenetListeners` in page.evaluate() 

### ISSUE THREAD

**Issue by realdennis** [puppeteer/puppeteer#3618]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.10.0
* Platform / OS version:MacOS
* URLs (if applicable):
* Node.js version:11.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Using **getEventListeners** in `page.evaluate`
2. I get this error message `(node:53503) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getEventListeners is not defined`
3. I thought getEventListeners is not the window / document property, could I enable something ( maybe DOMDebugger option? ) to make this property work?
4. Or ... Is there another way to debug document if elements attach some unexpected event type / event listener?

**What is the expected result?**

Get event listeners array.

**What happens instead?**

error message `Error: Evaluation failed: ReferenceError: getEventListeners is not defined`

related issue:
https://github.com/GoogleChrome/puppeteer/issues/3349
https://github.com/GoogleChrome/puppeteer/issues/3166
https://github.com/GoogleChrome/puppeteer/issues/1919

**Comment by matthaywardwebdesign** [comment]
Have you tried the solution here? [https://github.com/GoogleChrome/puppeteer/issues/3166#issuecomment-438422581](https://github.com/GoogleChrome/puppeteer/issues/3166#issuecomment-438422581)

**Comment by realdennis** [comment]
@matthaywardwebdesign 
I tried, using `getEventListeners` in `page.evaluate` still  not work.

Below is error message:
`UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getEventListeners is not defined`

**Comment by matthaywardwebdesign** [comment]
@realdennis Have you tried this?

```javascript
const { ElementHandle } = require('puppeteer/lib/ExecutionContext');
ElementHandle.prototype.getEventListeners = function () {
    return this._client.send('DOMDebugger.getEventListeners', { objectId: this._remoteObject.objectId });
};
```

**Comment by realdennis** [comment]
@matthaywardwebdesign 

Yes, like I just said, I tried this before and it didn't work, did this `quickfix` work for you?

Even if the `quickfix` does work, I thought this feature might be added in Puppeteer, and be native usage, after all.

**Comment by aslushnikov** [comment]
@realdennis the [`getEventListeners`](https://vanilla.aslushnikov.com/#DOMDebugger.getEventListeners) is a method of Chrome DevTools Protocol. 

You can access Chrome DevTools protocol using [`target.createCDPSession()`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-targetcreatecdpsession) and using the session to issue devtools protocol commands.

More information on DevTools protocol:
- official [DevTools Protocol viewer](https://chromedevtools.github.io/devtools-protocol/)
- [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface)

Hope this helps.

**Comment by aslushnikov** [comment]
@realdennis btw [this comment](https://github.com/GoogleChrome/puppeteer/issues/3618#issuecomment-445607495) is exactly what you need. 

You can use it later on like this:
```js
const elementHandle = await page.$('div');
const eventListeners = await elementHandle.getEventListeners();
```

**Comment by realdennis** [comment]
In puppeteer@1.13, we could not import (require) `ElementHandle` from `ExecutionContext`,  I just replace `ElementHandle` with `JSHandle`, I am not sure this a good alternative solution.

Workaround for who need this method in the latest version.

```javascript
  const { JSHandle } = require('puppeteer/lib/JSHandle');
  JSHandle.prototype.getEventListeners = function() {
    return this._client.send('DOMDebugger.getEventListeners', {
      objectId: this._remoteObject.objectId
    });
  };
```

**Comment by aslushnikov** [comment]
For the hackers out there: you can get classes now from [`puppeteer/lib/api`](https://github.com/GoogleChrome/puppeteer/blob/master/lib/api.js):

```js
const {JSHandle} = require('puppeteer/lib/api');
```

**Comment by bv-sumit** [comment]
The above solutions didnt work for latest version of puppeteer as the directory structure is changed.

https://stackoverflow.com/questions/75517220/geteventlistener-function-support-for-latest-puppeteer-versions/75581410#75581410
I have mentioned the solution in the above link. If anyone is facing the issue you can refer.
