### ISSUE TITLE
How to set the apiKey of a remote chrome WS connection

### ISSUE THREAD

**Issue by Maxwell2022** [puppeteer/puppeteer#3619]
[I have deployed chrome in lambda](https://github.com/prisma-archive/chromeless/tree/master/serverless#setup) and use AWS IoT to perform websocket connection.  [This is working great](https://github.com/prisma-archive/chromeless/tree/master/serverless#full-example) using `chromeless` package directly to handle the connection.

```
    const chromeless = new Chromeless({
      remote: {
        endpointUrl:
          'https://xxxxxxxxx.execute-api.us-west-2.amazonaws.com/production',
        apiKey: 'xxxxxxxxxxxx',
      },
    });
```

After looking at the documentation of puppeteer, I've noticed that I could install `puppeteer-core` instead of `puppeteer`, so I did so. Then I had to dig in the the issues of `puppeteer` to find out that I need to use `puppeteer.connect()` in order to connect to the websocket url.

```
    const browser = await puppeteer.connect({
      browserWSEndpoint:
        'https://xxxxxxx.execute-api.us-west-2.amazonaws.com/production',
    });
```

now, I get a 403 while attempting to connect to the same websocket because I have no idea how to pass the `apiKey` to the connection. [I cannot see any `options` in the documentation](https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-puppeteerconnectoptions) of `puppeteer.connect([options])`

I'm using the latest version of `puppeteer-core: "^1.11.0"`

**Comment by aslushnikov** [comment]
@Maxwell2022 Puppeteer is a general-purpose library for browser automation; unlike Chromeless, it doesn't aim to provide a boxed solution to run in serverless environments.

There are a lot of articles and community resources that help running in the cloud. For example, check out our [`troubleshooting.md`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-aws-lambda) on running on AWS Lambda.

Hope this helps.

**Comment by Maxwell2022** [comment]
I have chromeless running, I just wanted to connect to my instance through websocket. However it looks like `puppeteer.connect()` does not support sending auth header out of the box.

**Comment by aslushnikov** [comment]
>  However it looks like puppeteer.connect() does not support sending auth header out of the box.

Yeah that's the case.
