### ISSUE TITLE
Puppeteer just hangs with default Chrome installation

### ISSUE THREAD

**Issue by lumenier1** [puppeteer/puppeteer#3620]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: **1.11.0**
* Platform / OS version: **Linux Ubuntu 14.04 x86_64**
* URLs (if applicable):
* Node.js version: **10.14.1**

**What steps will reproduce the problem?**

    const puppeteer = require('puppeteer');
    (async() => {
       const browser = await puppeteer.launch();
       const page = await browser.newPage();
       await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');
       await page.setViewport({width:960,height:768});
       await page.goto('https://google.com/', {timeout: 40000, waitUntil: 'domcontentloaded'});
       await page.screenshot({ fullPage: true, path: 'screenshot.jpg' });
       await browser.close();
    })();

1. Install `puppeteer` with **`npm i puppeteer`** command .
2. Run this code sample with **`node make-screenshot.js`** command to make a screenshot of webpage.

**What is the expected result?**
Puppeteer should save screenshot as expected.

**What happens instead?**
Puppeteer just hangs, timeout doesn't work.

**How to fix it now?**
I solved it by installing `chromium-browser` separately:
**`sudo apt update`**
**`sudo apt install -y chromium-browser`**
**`chromium-browser --version`**

And then we have to change executable path in the code example to make it work:

    const puppeteer = require('puppeteer');
    (async() => {
       const browser = await puppeteer.launch({executablePath: 'chromium-browser'}); // <- set path for chromium browser
       const page = await browser.newPage();
       await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');
       await page.setViewport({width:960,height:768});
       await page.goto('https://google.com/', {timeout: 40000, waitUntil: 'domcontentloaded'});
       await page.screenshot({ fullPage: true, path: 'screenshot.jpg' });
       await browser.close();
    })();

Now it works fine for me.

So that `puppeteer-core` and `chromium-browser` should be installed insted of just `puppeteer`.

**Comment by Tamal** [comment]
I was facing this problem in v1.10, then downgraded to v1.9.0 and things were smooth.

**Comment by aslushnikov** [comment]
@lumenier1 @Tamal You should pick the right Puppeteer version to drive Chromium. Please see our compatibility table at https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md.

**Comment by antun** [comment]
@aslushnikov that doesn't seem right. Chromium is packaged with Puppeteer, we don't control the version of Chromium separately. When we do an npm install, Puppeteer automatically chooses the Chromium version it wants via a script. Puppeteer v1.10.0 specifies to use Chromium revision 599821:

https://github.com/GoogleChrome/puppeteer/blob/v1.10.0/package.json#L11

Shouldn't Puppeteer specify a version of Chromium it's compatible with?

**Comment by aslushnikov** [comment]
> Shouldn't Puppeteer specify a version of Chromium it's compatible with?

@antun this is the case for chromium; in the original report, author was driving a separate pre-installed version of Chrome browser. In this case, one should pick a compatible pptr version - see our [faq entry](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy).

**Comment by gumuruhsspj** [comment]
> ### Steps to reproduce
> **Tell us about your environment:**
> 
> * Puppeteer version: **1.11.0**
> * Platform / OS version: **Linux Ubuntu 14.04 x86_64**
> * URLs (if applicable):
> * Node.js version: **10.14.1**
> 
> **What steps will reproduce the problem?**
> 
> ```
> const puppeteer = require('puppeteer');
> (async() => {
>    const browser = await puppeteer.launch();
>    const page = await browser.newPage();
>    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');
>    await page.setViewport({width:960,height:768});
>    await page.goto('https://google.com/', {timeout: 40000, waitUntil: 'domcontentloaded'});
>    await page.screenshot({ fullPage: true, path: 'screenshot.jpg' });
>    await browser.close();
> })();
> ```
> 
> 1. Install `puppeteer` with **`npm i puppeteer`** command .
> 2. Run this code sample with **`node make-screenshot.js`** command to make a screenshot of webpage.
> 
> **What is the expected result?**
> Puppeteer should save screenshot as expected.
> 
> **What happens instead?**
> Puppeteer just hangs, timeout doesn't work.
> 
> **How to fix it now?**
> I solved it by installing `chromium-browser` separately:
> **`sudo apt update`**
> **`sudo apt install -y chromium-browser`**
> **`chromium-browser --version`**
> 
> And then we have to change executable path in the code example to make it work:
> 
> ```
> const puppeteer = require('puppeteer');
> (async() => {
>    const browser = await puppeteer.launch({executablePath: 'chromium-browser'}); // <- set path for chromium browser
>    const page = await browser.newPage();
>    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36');
>    await page.setViewport({width:960,height:768});
>    await page.goto('https://google.com/', {timeout: 40000, waitUntil: 'domcontentloaded'});
>    await page.screenshot({ fullPage: true, path: 'screenshot.jpg' });
>    await browser.close();
> })();
> ```
> 
> Now it works fine for me.
> 
> So that `puppeteer-core` and `chromium-browser` should be installed insted of just `puppeteer`.

where the puppet-core usage anyway?
