### ISSUE TITLE
Value of page.cookies() is different from the one displayed in devtools.

### ISSUE THREAD

**Issue by TestQA123456** [puppeteer/puppeteer#3621]
{ name: 'AS',
    value: 'v=1&s=1CVzyK3Z',
    domain: '.login.yahoo.com',
    path: '/',
    expires: -1,
    size: 16,
    httpOnly: true,
    secure: true,
    session: true }

Go the above on running through puppeteer. Whereas chrome inspect element displayed;
![image](https://user-images.githubusercontent.com/45561494/49372148-b951e900-f71f-11e8-9ef8-05552718bc59.png)

**Comment by gidztech** [comment]
I'm unable to reproduce this issue in v1.11.0. Just to confirm, you are inspecting the cookies from launched Chromium instance and not a different browser instance?

**Comment by TestQA123456** [comment]
No, I tried inspecting on normal chrome and compare it with the cookie from chromium

**Comment by gidztech** [comment]
That explains your problem. That cookie is generated with a unique value the first time the browser visits the page. Chrome and Chromium are different browsers, so they don’t share storage. You’ll get a different unique cookie for each.

**Comment by TestQA123456** [comment]
I get that. But I meant the size of the cookie. Always chromium gives a cookie with size 12 whereas the one in chrome is long. Also trying to make the next request with the cookie obtained from chromium is not getting through!

**Comment by gidztech** [comment]
Using the following code, I get the same cookie size:

```javascript

const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
    await page.goto('https://login.yahoo.com');
    console.log(await page.cookies());
})();
```

**Puppeteer output:**

![Puppeteer output](https://i.imgur.com/mIvGzck.png)

**Chromium DevTools:**

![Chromium DevTools](https://i.imgur.com/8AaV1qP.png)

**Comment by TestQA123456** [comment]
I'm able to get the complete cookie for 'login.yahoo.com', but the same doesn't happen when the url is 'https://login.yahoo.com/account/create'

**Comment by gidztech** [comment]
I tried 'https://login.yahoo.com/account/create' URL and I get a smaller cookie, but it's still consistent with the DevTools output. Both are `size: 16`.

**Comment by aslushnikov** [comment]
I can't reproduce this either.
