### ISSUE TITLE
Puppeteer on Openshift Cloud

### ISSUE THREAD

**Issue by thecodersing** [puppeteer/puppeteer#3624]
* Puppeteer version: 1.11.0
* Platform / OS version: Linux / RHEL 7.6 (Maipo) on **Openshift Cloud**
* URLs (if applicable): OpenShift Cloud
* Node.js version: 10.13.0

**Expected:**
My code is running in local windows machine. I expect the similar behavior in Openshift.

**Actual:**
I am running nodejs on openshift cloud. While running i get the below error:

puppeteer error: Error: Failed to launch chrome!
/opt/app-root/src/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

I don't have access to terminal. It automatically build and deploy from GitHub code base. How to proceed with? Is the there any way i can specify to install dependencies through package.json scrpit? I am stuck here.

**Note:** Nowhere I have seen any document related to using puppeteer on openshift.

**Comment by matthaywardwebdesign** [comment]
I'd recommend running under a Docker image under OpenShift Cloud. That way you can follow the instructions here: [https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) which will install the correct dependencies required to run Puppeteer.
