### ISSUE TITLE
Can puppeteer generate PDF with bookmarks?

### ISSUE THREAD

**Issue by Pingze-github** [puppeteer/puppeteer#3625]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: Windows 10
* URLs (if applicable): any html
* Node.js version: 8.9.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Create a HTML file
2. Use puppeeteer to transform it into a PDF doc
3. Open the PDF doc, find that no bookmarks

**What is the expected result?**

By using some kind of HTML tags, puppteer can create PDF doc with bookmarks.

**What happens instead?**

I tried `href="#id"` and others method, but no bookmarks were created.

Can puppeteer do it? Or can it be a feature?

**Comment by matthaywardwebdesign** [comment]
Unfortunately at the moment Chromium doesn't have support for PDF bookmarks. Please see this related Chromium issue: [https://bugs.chromium.org/p/chromium/issues/detail?id=781797](https://bugs.chromium.org/p/chromium/issues/detail?id=781797)

**Comment by aslushnikov** [comment]
Closing this in favor of upstream bug; we might revisit this later on once/if chromium gets this implemented.
