### ISSUE TITLE
Feature Request: page.waitForNetwork

### ISSUE THREAD

**Issue by phawxby** [puppeteer/puppeteer#3627]
In some cases clicking something may trigger a number of network requests, for example it triggers an AJAX load which then adds images to the DOM.

It would be useful to be able to reapply the `waitUntil` concept of `page.goto` or `page.waitForNavigation`, allowing us to wait until everything has finished loading before going any further.

**Comment by matthaywardwebdesign** [comment]
@phawxby Would the waitForRequest API solve this use case for you? It allows the use of a predicate function to await a network request. In theory you could leverage this to continue waiting for network requests until a time period has passed, however this is a little hacky. Alternatively you could use the 'request' event and debounce it. I do agree however that a helper function to do this would be quite beneficial.

**Comment by phawxby** [comment]
Yeah, I toyed with that idea but haven't got around to writing anything to do it yet. I think if/when I get time I'll write a core feature and PR it through.

**Comment by TimotheeJeannin** [comment]
Any news on this feature? It would be super useful! :)

**Comment by phawxby** [comment]
Nothing from me, just too damn busy at the moment

**Comment by ojaswa1942** [comment]
Any update on this? Also, I was wondering if this issue is still relevant to solving #3323 ? 
I can't wait for a specific selector in my case unless, ofcourse, something like `page.waitForSelector("body")` solves this, which I cannot verify since the issue arises randomly on navigation for the same sites.

**Comment by IngyuTae** [comment]
``` js
const waitForNetwork0 = async (page, timeout = 500) => {
  await new Promise((resolve) => {
    let timer;
    page.on('response', () => {
      clearTimeout(timer);
      timer = setTimeout(resolve, timeout);
    });
  });
};
```

**Comment by rudolfbyker** [comment]
Here's my take on it (using Typescript and NodeJS – this can be adapted for plain browser JS easily):

## First a utility function:

```ts
import { Page, Request } from "puppeteer";
import EventEmitter from "events";

export function createFunctionWaitForIdleNetwork(
  page: Page
): (idleTimeout: number, failTimeout: number) => Promise<void> {
  class Emitter extends EventEmitter {}

  let pendingRequests: Request[] = [];
  const emitter = new Emitter();

  function pushRequest(request: Request) {
    pendingRequests.push(request);
    emitter.emit("active");
  }

  function popRequest(request: Request) {
    pendingRequests = pendingRequests.filter((r) => r !== request);
    if (pendingRequests.length === 0) {
      emitter.emit("idle");
    }
  }

  page.on("request", pushRequest);
  page.on("requestfinished", popRequest);
  page.on("requestfailed", popRequest);

  /**
   * Return a promise that will resolve when the network is idle.
   *
   * @param idleTimeout
   *   The minimum amount of time that the network must be idle before the promise will resolve.
   *
   * @param failTimeout
   *   The maximum amount of time to wait for the network to become idle before rejecting.
   */
  async function waitForIdleNetwork(
    idleTimeout: number,
    failTimeout: number
  ): Promise<void> {
    let failTimer: NodeJS.Timeout;
    let idleTimer: NodeJS.Timeout;

    return new Promise((resolve, reject) => {
      function fail() {
        reject(
          new Error(
            `After ${failTimeout}ms, there are still ${pendingRequests.length} pending network requests.`
          )
        );
      }

      function succeed() {
        clearTimeout(failTimer);
        resolve();
      }

      // Start failure time immediately.
      failTimer = setTimeout(fail, failTimeout);

      // Handle edge case where neither active nor idle is emitted during the lifetime of this promise.
      if (pendingRequests.length === 0) {
        idleTimer = setTimeout(succeed, idleTimeout);
      }

      // Play a game of whack-a-mole with the idle and active events.
      emitter.on("idle", () => {
        idleTimer = setTimeout(succeed, idleTimeout);
      });
      emitter.on("active", () => {
        clearTimeout(idleTimer);
      });
    });
  }

  return waitForIdleNetwork;
}
```

## Example usage:

```js
// page = ...
waitForIdleNetwork = createFunctionWaitForIdleNetwork(page);
await waitForIdleNetwork(100, 1000);
```

This will resolve if the network becomes idle for more than 100ms, but if that does not happen within 1000ms, it will reject. "Idle" is defined as: There are no requests that are waiting for responses.

## How it works

- When a request starts,
  - it is added to a list
  - an event is emitted to say that the network is active
- When a request completes (successfully or unsuccessfully),
  - it is removed from the list
  - if the list is empty after removing it, an event is emitted to say that the network has become idle
- When waitForIdleNetwork is called,
  - a failure timer is started immediately. If this runs out, the promise rejects.
  - when the idle event is detected, a success timer is started. When it runs out, the failure timer is cleared and the promise is resolved.
  - when the active event is detected, the success timer is cleared. So then we need to wait for the next idle event to restart the success timer.

## How I actually use it

I run a bunch of Jest tests in the same puppeteer instance. I have a `page.goto` call in the `beforeEach` hook. When a test performs an action which causes a network request (e.g. displaying some text which causes a font to start loading asynchronously) just before the end of the test, that network request might be terminated if the test completes before the response is returned. I also have it set up so that failed requests fail the test. So we need to wait for all requests to finish in every test, instead of terminating them.

```js
describe("Contribute view", () => {
  let page;
  let waitForIdleNetwork;

  beforeAll(async () => {
    // This creates our puppeteer instance, opens the page, etc.
    page = await setupPage(...);
    waitForIdleNetwork = createFunctionWaitForIdleNetwork(page);
  });

  beforeEach(async () => {
    // The reason why I need this is not relevant to this thread.
    await page.goto(...);

    // Wait for some specific page elements to become available...
    await page.waitForSelector(...);
  });

  afterEach(async () => {
    // Make sure we don't kill any requests when a test completes before all reponses are returned.
    await waitForIdleNetwork(100, 1000);
  });
```

**Comment by webaddicto** [comment]
> ```js
> const waitForNetwork0 = async (page, timeout = 500) => {
>   await new Promise((resolve) => {
>     let timer;
>     page.on('response', () => {
>       clearTimeout(timer);
>       timer = setTimeout(resolve, timeout);
>     });
>   });
> };
> ```

@IngyuTae

Your code above works, but with some URLs somehow it gets stuck forever like in a loop.

Is there a way to set a timeout so after say 30 seconds it will "stop"?

Tried with `await waitForNetwork0(page).timeout(30000);` but seems it "nullifies" waitForNetwork0 functionality.

Thanks for any help!

@rudolfbyker

How can I use/test your functions on a .js script like this:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
  const page = await browser.newPage();
  await page.goto('https://www.yahoo.de');
  await page.screenshot({path: './screenshot.png'});
  await browser.close();
})();
```

Sorry I'm a newbie with NodeJs.

Using Nodejs & Puppeteeer latest version.

Thank you.

I need to wait until network idle / page fully loaded before take screenshot.

**Comment by rudolfbyker** [comment]
> How can I use/test your functions on a .js script like this:
> 
> ```
> const puppeteer = require('puppeteer');
> 
> (async () => {
>   const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
>   const page = await browser.newPage();
>   await page.goto('https://www.yahoo.de');
>   await page.screenshot({path: './screenshot.png'});
>   await browser.close();
> })();
> ```
  
> I need to wait until network idle / page fully loaded before take screenshot.

Try this:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
  const page = await browser.newPage();
  waitForIdleNetwork = createFunctionWaitForIdleNetwork(page);

  await page.goto('https://www.yahoo.de');
  await waitForIdleNetwork(100, 1000);
  await page.screenshot({path: './screenshot.png'});
  await browser.close();
})();
```

**Comment by matthew-plusprogramming** [comment]
> ```js
> const waitForNetwork0 = async (page, timeout = 500) => {
>   await new Promise((resolve) => {
>     let timer;
>     page.on('response', () => {
>       clearTimeout(timer);
>       timer = setTimeout(resolve, timeout);
>     });
>   });
> };
> ```
@webaddicto try this
```
const waitForNetwork0 = async (page, timeout = 500) => {
  await new Promise((resolve) => {
    let timer;
    page.on('response', () => {
      clearTimeout(timer);
      timer = setTimeout(resolve, timeout);
    });
  });
};

**Comment by matthew-plusprogramming** [comment]
> > ```js
> > const waitForNetwork0 = async (page, timeout = 500) => {
> >   await new Promise((resolve) => {
> >     let timer;
> >     page.on('response', () => {
> >       clearTimeout(timer);
> >       timer = setTimeout(resolve, timeout);
> >     });
> >   });
> > };
> > ```
> 
> @IngyuTae
> 
> Your code above works, but with some URLs somehow it gets stuck forever like in a loop.
> 
> Is there a way to set a timeout so after say 30 seconds it will "stop"?
> 
> Tried with `await waitForNetwork0(page).timeout(30000);` but seems it "nullifies" waitForNetwork0 functionality.
> 
> Thanks for any help!
> 
> @rudolfbyker
> 
> How can I use/test your functions on a .js script like this:
> 
> ```
> const puppeteer = require('puppeteer');
> 
> (async () => {
>   const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
>   const page = await browser.newPage();
>   await page.goto('https://www.yahoo.de');
>   await page.screenshot({path: './screenshot.png'});
>   await browser.close();
> })();
> ```
> 
> Sorry I'm a newbie with NodeJs.
> 
> Using Nodejs & Puppeteeer latest version.
> 
> Thank you.
> 
> I need to wait until network idle / page fully loaded before take screenshot.

@webaddicto try this
```js
const waitForNetworkIdle = (page, requestDebounceTimeout = 500, timeout = 30000) => {
  return new Promise(async (resolve) => {
    const onEnd = (): void => {
      clearTimeout(networkTimer);
      clearTimeout(timeoutTimer);
      resolve();
    };
    let networkTimer;
    const timeoutTimer = setTimeout(onEnd, timeout);
    page.on('response', () => {
      clearTimeout(networkTimer);
      networkTimer = setTimeout(onEnd, requestDebounceTimeout);
    });
  });
};
```

**Comment by ghost** [comment]
https://pptr.dev/#?product=Puppeteer&version=v14.2.1&show=api-pagewaitfornetworkidleoptions
