### ISSUE TITLE
Unsupported screenshot mime type: null

### ISSUE THREAD

**Issue by zhangzs000** [puppeteer/puppeteer#3629]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.11.0
* Platform / OS version: Mac
* URLs (if applicable): 
* Node.js version: v10.4.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

const puppeteer = require('puppeteer');
(async () => {   
 const browser = await puppeteer.launch({  headless: true  })
 const page = await browser.newPage() 
 await page.goto('http://www.baidu.com') 
 await page.screenshot({ path: '/Users/bosszhang/Documents/temp/puppeteer'})
})()

**What is the expected result?**

screenshot

**What happens instead?**

bosszhang@bossZhangdeMacBook-Pro puppeteer $ node start.js
(node:99961) UnhandledPromiseRejectionWarning: Error: Unsupported screenshot mime type: null
    at assert (/Users/bosszhang/Documents/temp/puppeteer/node_modules/puppeteer/lib/helper.js:278:11)
    at Page.screenshot (/Users/bosszhang/Documents/temp/puppeteer/node_modules/puppeteer/lib/Page.js:813:7)
    at Page.<anonymous> (/Users/bosszhang/Documents/temp/puppeteer/node_modules/puppeteer/lib/helper.js:145:23)
    at /Users/bosszhang/Documents/temp/puppeteer/start.js:6:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:99961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:99961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zhangzs000** [comment]
path error

**Comment by papiro** [comment]
How did you fix this?
