### ISSUE TITLE
program that runs a bundled version of chromium can not stop

### ISSUE THREAD

**Issue by jushjuhx** [puppeteer/puppeteer#363]
Here is my code. 
```
const puppeteer = require('puppeteer');


(async() => {

const browser = await puppeteer.launch({executablePath:'chrome.exe'});
const page = await browser.newPage();
await page.setViewport({width:1024,height:768});
await page.goto('https://www.google.com' ,{waitUntil: 'networkidle'});
await page.screenshot({path: 'jd.png',fullPage:true});

browser.close();
})();
````
The path of "chrome.exe" has been added to system environment variables. When I run it use the command "node test.js", it gives no output and just blocked . What's the problem?

**Comment by JoelEinbinder** [comment]
Puppeteer currently only works with very recent Chromium versions. It might work with a Canary version of Chrome. I'd expect to get this behavior if you try to run with a version of Chrome that is too old for Puppeteer.

What version does `chrome.exe` point to?

**Comment by pavelfeldman** [comment]
Let's check the version and add a user-friendly message explaining the failure. Marking as M1 bug.
