### ISSUE TITLE
puppeteer.launch() never returns when using --no-startup-window

### ISSUE THREAD

**Issue by Mehuge** [puppeteer/puppeteer#3630]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: MacOS Mojave 10.14
* URLs (if applicable):
* Node.js version: v10.11.0

**What steps will reproduce the problem?**

  await puppeteer.launch({ headless: false, sloMo: 0, args: [ 
    '--window-size=400,714',
    '--unlimited-storage',
    '--no-startup-window',
    '--disable-dev-shm-usage',
    '--disable-crash-reporter',
    '--disable-breakpad' 
  ]});

**What is the expected result?**

Chromium to launch, and puppeteer.launch() return.

**What happens instead?**

The dock icon for puppeteer appears, but puppeteer.launch() never returns.

I added a console.log to puppeteer/lib/Launcher.js to output the full command line being run, in case that helps.

/Users/adf/Projects/dalang/node_modules/puppeteer/.local-chromium/mac-609904/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain about:blank --window-size=400,714 --unlimited-storage --no-startup-window --disable-dev-shm-usage --disable-crash-reporter --disable-breakpad --remote-debugging-port=0 --user-data-dir=/var/folders/7r/_3bt2vjs2lb7ql4tg98983x00000gn/T/puppeteer_dev_profile-l9JwIX

If I click on the dock icon that appeared for chromium, puppeteer.launch() then returns.

If I set executablePath to point at my normal Chrome executable (`/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`), puppeteer.launch() works as expected.

**Comment by Mehuge** [comment]
Been trying a few things to get to try to get to the bottom of what is going, so I downgraded to puppeteer 1.3.0 (the version I was originally successfully using) and that works.

1.3.0 ok
1.4.0 ok
1.6.2 puppeteer.launch() hangs (until click dock icon)
1.4.0 ok

**Comment by Mehuge** [comment]
It's blocking on:- `await initialPagePromise;` in `ensureInitialPage` in Launcher.js

After calling Browser.create, before waiting for the initialPagePromise

  puppeteer:protocol SEND ► {"id":1,"method":"Target.setDiscoverTargets","params":{"discover":true}} +0ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"9606E8989A3213A624AB71E9AD5CD75A","type":"background_page","title":"CryptoTokenExtension","url":"chrome-extension://kmendfapggjehodndflmmgagdbamhnfd/_generated_background_page.html","attached":false,"browserContextId":"2D5F7FD876DC28A3F99652FB095AA448"}}} +11ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"b9b8f636-2f8e-4714-bc0b-dfd3443171ff","type":"browser","title":"","url":"","attached":true}}} +1ms
  puppeteer:protocol ◀ RECV {"id":1,"result":{}} +1ms


After calling await initialPagePromise:-

  puppeteer:protocol ◀ RECV {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"9606E8989A3213A624AB71E9AD5CD75A","type":"background_page","title":"CryptoTokenExtension","url":"chrome-extension://kmendfapggjehodndflmmgagdbamhnfd/_generated_background_page.html","attached":false,"browserContextId":"2D5F7FD876DC28A3F99652FB095AA448"}}} +123ms

Then after a short delay

  puppeteer:protocol ◀ RECV {"method":"Target.targetDestroyed","params":{"targetId":"9606E8989A3213A624AB71E9AD5CD75A"}} +15s

**Comment by JoelEinbinder** [comment]
Puppeteer expects and waits for a page on startup. Passing `--no-startup-window` doesn't create the page. Why do you want to use this argument?

**Comment by Mehuge** [comment]
The way my code works is (in 1.3.0 and 1.4.0)

It calls `puppeteer.launch()` with `--no-startup-window` which means that `browser.getPages()` returns an empty list. So I then do `if (pages.length === 0) pages.push(await browser.newPage())` which gives me a page I can then `pages[0].goto(url);` to navigate.

```
const browser = puppeteer.launch({ headless: false, args: [ '--no-startup-widnow' ] });
const pages = browser.pages();
if (pages.length === 0) pages.push(await browser.newPage());
pages[0].goto('http://www.google.com/');
```

All perfectly reasonable, I thought.  But that code does not work since 1.6.2 because `puppeteer.launch()` blocks.

The error I am seeing if I don't add `--no-startup-window` is in the code below:

```
const connection = browser._connection;
const { targetInfos: [{ targetId }] } = await connection.send('Target.getTargets');
const { windowId } = await connection.send('Browser.getWindowForTarget', { targetId });
await connection.send('Browser.setWindowBounds', { bounds: { width, height }, windowId });
```

The issue is that the order of the two pages (targets) that is returned by `Target.getTargets` is different without `--no-startup-window`, the above code made the assumption (based on using `--no-startup-window`) of the order of the targets returned.

I can ofc fix my code to remove that assumption, but the real question is, is the first example considered code that should work? Because it certainly used to.

**Comment by Mehuge** [comment]
Some other oddities when not using `--no-startup-window` that I am observing:-

Both with and without `--no-startup-window` window.innerHeight shows the frame height (including chrome) not the inner content area height.

There is now an annoying infobar telling me what I already know, further reducing the available content area.

![image](https://user-images.githubusercontent.com/99895/49811351-01de5780-fd5b-11e8-896e-2a9b31402410.png)

Problems I am going to need to find separate solutions for, if I can't use `--no-startup-window`.

**Comment by aslushnikov** [comment]
@Mehuge so what is the motivation to pass `--no-startup-window` flag? If you want to avoid creating second page and reuse the one that gets opened by default, you can get it like this:

```js
const browser = await pptr.launch();
const [page] = await browser.pages();
```

**Comment by Mehuge** [comment]
That is essentially what my code is now doing.

https://github.com/redskyit/dalang/blob/master/dalang.js#L127

The motivation was indeed to avoid the second tab (in headless: false mode).

**Comment by aslushnikov** [comment]
> The motivation was indeed to avoid the second tab (in headless: false mode).

Looks like this is [solved](https://github.com/GoogleChrome/puppeteer/issues/3630#issuecomment-447166598) then :-)
