### ISSUE TITLE
Page promises do not complete if Page is closed

### ISSUE THREAD

**Issue by aaronmefford** [puppeteer/puppeteer#3631]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: AWS Linux
* URLs (if applicable):
* Node.js version: 8.12.0
**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer = require('puppeteer');

(async() => {
    let browser, page;
    try{
        let options = {
            executablePath: '/opt/chrome/headless_shell'
        };
        browser = await puppeteer.launch(options);

        page = await browser.newPage();
        await page.setViewport({width:1280, height:1024});

        let url = 'https://www.yahoo.com/';
        console.log("Browsing to:",url);
        let browsePromise = page.goto(url,{waitUntil: 'load',timeout: 0})
            .catch((err)=>{
                console.error("Goto Error:",err);
            });
        console.log("Closing Page");
        await page.close();
        await browsePromise;
        console.log("Await Browse");
        console.log("GoTo Complete");
    } catch (e) {
        console.error("Any Error occurred Shutting down.");
    }
    finally{
        console.log("Closing Browser");
        await browser.close();
    }
})();
```

**What is the expected result?**
The code will exit after the page and browser are closed

**What happens instead?**
Hangs indefinitely

There seems to be an issue with the Page object wait* promises that can result in node not shutting down.  It looks like if the Page is closed before the promise completes, the promise never completes.  I have tested with both the networkidle2 option and load.  If a Timeout value is set then the timer will fire and shut things down, but Node will stay open until that timer event completes.

While it makes sense, that this occurs, and some might beg the question of why do you want to close the browser before the load completes, I think it also makes sense to insure that any outstanding promises including timeouts are terminated one way or another when the page is closed.  That may be via an exception or maybe they are just resolved, either seems reasonable.  However, I should not be forced to wait for a timer to expire that I have no ability to cancel.

In my case I have a url that results in a JavaScript redirect.  I need to get the URL destination of that redirect.  So I have code that does that, and as soon as I have that URL, I need to close the tab and move on.  Right now I cannot do that.

I realize that my versions are out of date and apologize if this issue has been resolved in current versions.  Unfortunately I do not have the time to test further, I am in an employment transition and have a lot to cover before I switch.

I did search for similar issues, and while there are many that may well be related, they were all far to specific and perhaps missing the core of the problem, which seemed to be leading to out right dismissal, or stalling.  In many cases a work around was found, without ever understanding what may have been the core issue.  I am hoping that the test case above is simple enough, and that the issue is clear enough to allow you to resolve this problem which seems to have affected many.

**Comment by aslushnikov** [comment]
@aaronmefford I recall we were fixing this sometime ago; this is working fine for me with Puppeteer v1.11.0.
