### ISSUE TITLE
PUPPETEER_DOWNLOAD_HOST poorly named & documented

### ISSUE THREAD

**Issue by abentley** [puppeteer/puppeteer#3635]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**
PUPPETEER_DOWNLOAD_HOST is not a hostname, rather it is a URL prefix.  Hostnames do not include protocol, nor do they indicate path prefix.  This name makes the variable less discoverable for users who need to override protocol and / or path.

The documentation:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables
"overwrite host part of URL that is used to download Chromium"

Again, this makes it seem like the PUPPETEER_DOWNLOAD_HOST cannot override the protocol or path prefix, when in fact, it can.  It may also lead to an incorrect value being supplied, e.g. "my-mirror.com" rather than "http://my-mirror.com".

At one point in the discussion of issue #951, PUPPETEER_DOWNLOAD_CHROMIUM_URL_PREFIX was considered as the name.  This is verbose, but far more descriptive of how the variable actually functions.

_Please include code that reproduces the issue._

N/A

**What is the expected result?**
N/A

**What happens instead?**
N/A

**Comment by aslushnikov** [comment]
@abentley These are all fair concerns. I don't think changing name worth it at this point; we can do a better job documenting the behavior though.
