### ISSUE TITLE
Cannot enable GPU acceleration

### ISSUE THREAD

**Issue by giokara** [puppeteer/puppeteer#3637]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.9.0
* Platform / OS version: Linux version 4.15.0-39-generic (buildd@lgw01-amd64-054) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3))
* Node.js version: v10.10.0

**What steps will reproduce the problem?**

1. Run code given below that opens `chrome://gpu` page + takes screenshot
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ args: ['--headless'] });
    const page = await browser.newPage();
    await page
        .goto('chrome://gpu', { waitUntil: 'networkidle0', timeout: 20 * 60 * 1000 })
        .catch(e => console.log(e));
    await page.screenshot({
        path: 'gpu_stats.png'
    });
    await browser.close();
})();
```
2. View resulting `gpu_stats.png` screenshot

**What is the expected result?**

Same result as in Chrome browser, in my case:

![gpu_stats_local](https://user-images.githubusercontent.com/12547760/49636935-4fc62900-fa04-11e8-9d65-37c8aa1cc9ae.png)

**What happens instead?**

This is the resulting screenshot:

![gpu_stats](https://user-images.githubusercontent.com/12547760/49637126-cebb6180-fa04-11e8-9c2b-d479bc2f879a.png)

I'm mainly concerned with the `WebGL: Software only, hardware acceleration unavailable` vs. `WebGL: Hardware accelerated but at reduced performance`, as I would like GPU acceleration for OpenGL rendering.

**Comment by aleksdjelic** [comment]
there is --disable-gpu flag in default launch options, try to remove that

**Comment by giokara-oqton** [comment]
@djelica I expected this `await puppeteer.launch({ args: ['--headless'] });` to use only the `--headless` flag, could you explain how to remove the flag otherwise?

**Comment by giokara** [comment]
@djelica I though using `await puppeteer.launch({ args: ['--headless'] });` was already doing that?

**Comment by aleksdjelic** [comment]
that just appends one more (--headless) flag to launch options which is there by default, apart from --headless there is several more launch flags, check `console.log(puppeteer.defaultArgs());` to get the idea, there you will find --disable-gpu flag which you want to get rid of.

**Comment by giokara** [comment]
Could you explain how to run puppeteer without the `--disable-gpu` flag?
[According to this](https://bugs.chromium.org/p/chromium/issues/detail?id=765284#c19), it seems that headless Chromium does not support GPU acceleration yet.

**Comment by aleksdjelic** [comment]
Please refer to api documentation or other issues related to disable specific launch flags, im sure there are examples around since i remember i went through that in the past. And as you have found running headless might be impossible with no gpu disabled, but i cant confirm that one.

**Comment by aslushnikov** [comment]
@giokara Chrome headless currently relies on software WebGL by default. You can override this using the `--use-gl=desktop` flag; for example, the following works for me:

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--use-gl=desktop'],
    });
    const page = await browser.newPage();
    await page
        .goto('chrome://gpu', { waitUntil: 'networkidle0', timeout: 20 * 60 * 1000 })
        .catch(e => console.log(e));
    await page.screenshot({
        path: 'gpu_stats.png'
    });
    await browser.close();
})();
```

More on the `--use-gl` flag could be found in Chromium sources: https://cs.chromium.org/chromium/src/ui/gl/gl_switches.cc?type=cs&q=kUseGL&sq=package:chromium&g=0&l=69

Hope this helps.

**Comment by giokara** [comment]
I can verify that the following gives the same output from `chrome://gpu`:

```
const puppeteer = require('puppeteer');

(async () => {
    const args = puppeteer.defaultArgs().filter(arg => arg !== '--disable-gpu');
    args.push('--use-gl=desktop');
    console.log(`args: ${args}`);
    const browser = await puppeteer.launch({ headless: true, ignoreDefaultArgs: true, args });
    const page = await browser.newPage();
    await page
        .goto('chrome://gpu', { waitUntil: 'networkidle0', timeout: 20 * 60 * 1000 })
        .catch(e => console.log(e));
    await page.screenshot({
        path: 'gpu_stats.png'
    });
    await browser.close();
})();
```

However it is clear from the rendering that the hardware acceleration is not working. From some testing, it still is 100x faster to run the same in a non-headless instance of Chrome.

**Comment by goofiva** [comment]
Not sure if anyone still has issues... but this worked for me.
```js
  const browser = await puppeteer.launch({
    headless: true,
    args: [
        '--use-gl=egl'
    ]
  });
```

**Comment by goofiva** [comment]
**--use-gl=desktop** didn't work for me. This did.
```js
  const browser = await puppeteer.launch({
    headless: true,
    args: [
        '--use-gl=egl'
    ]
  });
```

**Comment by FishBlanche** [comment]
> 
which puppeteer did u use? i have same problem here

**Comment by avachasov-rendmate** [comment]
Same problem after puppeeter update. v15.5.0 worked fine but v19.9.0 does not.

**Comment by harveylee** [comment]
Hardware acceleration in headless mode (with `--use-gl=egl`) stopped working for me from v19.8.0 (works on v19.7.5). 

Using Debian testing with Mesa 22.3.6 on Windows 11 WSL2.

**Comment by jasonmayes** [comment]
Also in need of as solution here - trying to run Web ML models on the server to automate a testing process that need GPU to execute in timely fashion using the new headless Chrome as shown here: https://developer.chrome.com/articles/new-headless/

However GPU is software only  when running via puppeteer and not using the actual NVIDIA GPU attached to my Linux instance. Any fix for this would help all of us folk working in the Web ML space (Machine Learning in JavaScript)
See this screenshot from headless chrome://gpu 

![unnamed](https://github.com/puppeteer/puppeteer/assets/4972997/60b0e895-7994-4c88-b371-7911b5c0b16c)

We essentially need WebGL / WebGL2 and WebGPU to be hardware supported (WebGPU Is now in Chrome stable as of 114 and new headless Chrome is Chrome itself now vs a separate thing in the past

**Comment by snnn** [comment]
[jasonmayes](https://github.com/jasonmayes) , I made it work: https://github.com/microsoft/onnxruntime/discussions/16983

**Comment by bilalmughal** [comment]
I was able to make it work on AWS Nvidia featuring GPU instance.

**Comment by sanschaise** [comment]
@bilalmughal wondering if you could tell us how you made this work? we are still struggling with this.

**Comment by snnn** [comment]
Great article!

**Comment by bilalmughal** [comment]
Thank you @snnn for posting the link as well, i am glad it helped you and i am hopeful it will help others like me and you 🙏

**Comment by jasonmayes** [comment]
I have followed the tutorial on @sanschaise post, though i still get following output:

Thu Nov 30 07:33:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+


But chrome refuses to use GPU:

Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Canvas out-of-process rasterization: Disabled
Direct Rendering Display Compositor: Disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Disabled
OpenGL: Unavailable
Rasterization: Unavailable
Raw Draw: Disabled
Skia Graphite: Disabled
Video Decode: Unavailable
Video Encode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Unavailable
WebGL2: Unavailable
WebGPU: Disabled


Anyone who has successfully got this working able to maybe jump on a meeting sometime to sanity check what I am doing?

**Comment by jasonmayes** [comment]
No worries. Got it working. Had to use the following:

!google-chrome-stable --no-sandbox --headless --timeout=15000 --enable-logging=stderr --log-level=2 --run-all-compositor-stages-before-draw --disable-search-engine-choice-screen --ash-no-nudges --no-first-run --disable-features=Translate --no-default-browser-check --use-gl=angle --enable-unsafe-webgpu --use-angle=gl-egl --use-cmd-decoder=passthrough --ignore-gpu-blocklist --screenshot=/home/ai.png https://elemental-bronzed-chips.glitch.me/

Also need to start dbus before running Chrome:

!/etc/init.d/dbus start

**Comment by jasonmayes** [comment]
Full write up can be found in this repo that has example code to automate too incase this is useful to folk:

https://github.com/jasonmayes/headless-chrome-nvidia-t4-gpu-support/tree/main
