### ISSUE TITLE
PDF Image rendering leaves blank bands

### ISSUE THREAD

**Issue by redevill** [puppeteer/puppeteer#3640]
### Steps to reproduce
Create a PDF from an HTML page as follows:
`
  private async generateReport(page: any, searchID: number,  path: string) {
      await page.setViewport({ width: 1280, height: 2000 });
      console.log('Navigate to Report with URL=' + navUrl);
      //Navigate to the reports, wait for the page to load, and save as pdf
      await page.goto(navUrl, {waitUntil: 'networkidle0'})
        .catch( (err: any) => { throw new Error('could not navigate to reports page; ' + err.message); });
      console.log('convert html to PDF and save to ' + path);
      await page.pdf({path: path, format: 'Letter'
        , preferCSSPageSize: true
        , margin: { top: 20, left: 10, right: 10, bottom: 10 }
        , landscape: true}).catch( () => { throw new Error('pdf generator failed'); });
  }`

The Html page template is produced by angular. The general structure is as follows:
(git - Won't let me put html as code sub curly braces)
`{table}
   {thead}myHeader Definition{/thead}
   {tfoot}myFoot Definitions{/tfoot}
   {tbody}
      {div *ngFor="Iterate over row content div style set to display:block}
         {tr}{td}
            {angular-custom-contentTemplate-directive/}
         {/td}{/tr}
      {/div}
   {/tbody}
 {/table}
 {div}
    {google map(agm)}
 {div}`

The map image comes out with a blank band.
![image](https://user-images.githubusercontent.com/8999255/49663725-cb2bd880-fa0c-11e8-8a3b-f33152c10360.png)

**Tell us about your environment:**

* Puppeteer version:  "_id": "puppeteer@1.9.0",
* Platform / OS version: mac 10.13.6
* Node.js version: 10.12.0

**What is the expected result?**
Expect to get more wisiwig output of the html rendered page.

**What happens instead?**
Get odd blank spots in the report, despite setting the page break avoid for the {div display:block}
Particularly disturbing is the band on the last image.

**Comment by aslushnikov** [comment]
Puppeteer PDF rendering fully relies on Chromium's "Save As PDF" functionality. Can you please file this upstream to `https://crbug.com/new` - Chromium's PDF team might be able to help.

Closing this since it falls outside of Puppeteer project (but feel free to post a link to upstream bug if you raise it there).

**Comment by redevill** [comment]
Filed issue = https://bugs.chromium.org/p/chromium/issues/detail?id=915389
