### ISSUE TITLE
page.exposeFunction should allow JSHandles arguments

### ISSUE THREAD

**Issue by RedHatter** [puppeteer/puppeteer#3642]
Currently `page.exposeFunction` only allows serialization values to to be passed in as arguments, it should also allow JSHandles.

As a simple example.

```
const filepath =  'element.png';
page.exposeFunction('doScreenshot', element => {
  element.screenshot({ path: filepath })
});
```
```
window.doScreenshot(document.querySelector('#myElement'));
```

I can't use `evaluateHandle` because I need the script on the page's side to initiate the action and I can't create a function using `page.evaluateOnNewDocument` because I need access node and puppeteer APIs.

**Comment by OrKoN** [comment]
Actually, this works for some time already:

```
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.exposeFunction("screenshot", async (el) => {
    await el.screenshot({
      path: 'el.png '
    })
  });
  await page.goto("https://example.com");
  await page.evaluate("screenshot(document.body)"); // Works
})();
```
