### ISSUE TITLE
XPATH contains not working with page.$x

### ISSUE THREAD

**Issue by demon-user** [puppeteer/puppeteer#3643]
I am using latest puppeteer version and trying to click on ```span``` element with text, but returns `undefined`.

`const setting = await page.$x('//span[contains(text(), "Settings")]'); // setting is undefined and setting.click() don't work`

However, I can get all `span` element with following
`const setting = await page.$x('//span'); // returns array of span  elements`

I am still trying to iterate over span elements to find exact span with correct textContent but still i get is undefined.
`const setting = spans.filter(span => span.textContent === 'Settings');` // still undefined.

Is there any easy way to find/click element with text content
Same things perfectly works on selenium. Is this issue in puppeteer ?

**Comment by vsemozhetbyt** [comment]
Can you provide a small script with the URL that reproduces the issue?

**Comment by demon-user** [comment]
This is a general issue, 

I can not simply select any element with xpath selector `page.$x`. always returns undefined.
I was trying to migrate from selenium same xpath selector used to work for selenium.

```javascript
const [settings] = await page.$x("//span[text()='Settings']"); // undefined
settings ? settings.click() : throw new Error('Element not found')

// after setting is clicked, now click Logout
const [logout] = await page.$x("//span[text()='Log out']"); // this is undefined
logout ? logout.click() : throw new Error('Element not found')
```
I get undefined, but I have those elements clearly visible.

**Comment by vsemozhetbyt** [comment]
I cannot reproduce:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const [element] = await page.$x("//a[text()='More information...']");

    console.log(await (await element.getProperty('href')).jsonValue());

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
http://www.iana.org/domains/example
```

**Comment by vsemozhetbyt** [comment]
Are you sure that element text is exactly `Settings` or `Log out`? No white spaces included?

**Comment by regmish** [comment]
I think it is always better to `waitFor` element to be visible in DOM before trying to click/accessing it.
```javascript
await page.waitForXPath('//span[contains(text(), "Settings")]', 5000);
const [setting] = await page.$x('//span[contains(text(), "Settings")]');
if(setting) setting.click();
```

**Comment by demon-user** [comment]
@shankarregmi 
My bad I was trying to click on the settings before it was completely loaded into DOM,
your solution perfectly works for me. Thanks.
