### ISSUE TITLE
I want to connect the puppeteer android divices to remote.

### ISSUE THREAD

**Issue by kimsangsoo** [puppeteer/puppeteer#3644]
How do I launch my browser after connecting android?

const browser = await puppeteer.launch({ headless: false }); ???

const browser = await puppeteer.connect({
    browserWSEndpoint: 'ws://localhost:9222/devtools/browser',
    ignoreHTTPSErrors: true
  }); ???

**Comment by aslushnikov** [comment]
@kimsangsoo why would you want to do this?
