### ISSUE TITLE
Polling: 'mutation' in shadow dom

### ISSUE THREAD

**Issue by AutoSponge** [puppeteer/puppeteer#3647]
### Steps to reproduce

* Puppeteer version: 1.11
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version: 10

**What steps will reproduce the problem?**

1. Execute a `waitForFunction()` that digs into shadow (e.g....

```js
waitForFunction(`document.querySelector('my-component') 
  && document.querySelector('my-component').shadowRoot 
  && document.querySelector('my-component').shadowRoot.querySelector('*')`, 
{polling: 'mutation'})
``` 

2. Use dynamic/lazy loading to create race condition where `my-component` guts aren't hydrated when `waitForFunction` runs.
3. Observe that `waitForFunction` will never resolve.

**What is the expected result?**

`waitForFunction` should resolve as soon as the `my-component` guts get hydrated, triggering mutation.

**What happens instead?**

The mutation observer implementation could benefit from `{pierce: true}` option which could recursively create observers in (open) shadow.

**Comment by aslushnikov** [comment]
@AutoSponge this has been considered in the WebPlatform before: https://github.com/w3c/webcomponents/issues/204

I'd recommend using `polling: 'raf'` instead when dealing with shadow dom atm as a workaround. I don't think throwing in polyfills that will attach mutation observers to every shadow root worth it.
