### ISSUE TITLE
where to inject code into one new page just after this page instance created by window.open(), before url loadding?

### ISSUE THREAD

**Issue by yanlusu** [puppeteer/puppeteer#3648]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: Darwin MacBookPro 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
* URLs (if applicable):
* Node.js version: v8.11.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. open a page
```javscript
    const page = await browser.newPage();
    // I can inject some code before loading url;
    await preparePageForTests(page);
   // and now goto url;
    await page.goto(testUrl);
```

```javascript
    // preparePageForTests
const preparePageForTests = async(page) => {
    // Pass the User-Agent Test.
    const userAgent = 'Mozilla/5.0 (X11; Linux x86_64)' +
        'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.39 Safari/537.36';
    await page.setUserAgent(userAgent);

    // Pass the Webdriver Test.
    await page.evaluateOnNewDocument(() => {
        Object.defineProperty(navigator, 'webdriver', {
            get: () => false,
        });
    });

    // Pass the Chrome Test.
    await page.evaluateOnNewDocument(() => {
        // We can mock this in as much depth as we need for the test.
        window.navigator.chrome = {
            runtime: {},
            // etc.
        };
    });
}
```
2. but when I clicked a link on one page, a new page(tab) is created automatically and url is loaded,
    where to inject `await preparePageForTest(newPage)?

**What is the expected result?**
I want to inject code when the clicked new Page instance is created, before url loadding.

**What happens instead?**
I can't do that.
I tried event `target changed`,  not worked.

**Comment by aslushnikov** [comment]
This is somewhat similar to #1378. The general issue both here and there is that we connect too late to the page. Instead, we need some API like `browserContext.setTargetInterception` that will allow to attach to any target and set it up before resuming its operation.

**Comment by aslushnikov** [comment]
Closing in favor of #3667.

**Comment by yanlusu** [comment]
@aslushnikov , that's great! thank you!
