### ISSUE TITLE
Wait for Network request before continuing process

### ISSUE THREAD

**Issue by Tim-bridgement** [puppeteer/puppeteer#3649]
Hi i am trying to create an automated testing program using puppeteer however I have come across an issue where i need to wait for a particular network call before continuing the testing. Is it possible to wait for a particular network call and access the information that is received in the network response? 

I have tried looking at possible solutions using
```javascript
 page.on("response", () => {
// check for particular response and return json value
}
```
This does not seem to work the way I expected and i am under the impression that I am misunderstanding how the event works. I was hoping for something similar to this:
```javascript
await page.waitForNetworkResponse("Call_name or URL");
await page.click("button[type = submit]")
```
and 
```javascript
let resp = await page.on("response", resp => {
    if(resp.name === "desire call name"))
        return resp.json;
});

```

Any insight would be greatly appreciated thank you in advance.

**Comment by meniRoy** [comment]
try this function :
```javascript
const waitForResponse = (page, url) => {
    return new Promise(resolve => {
        page.on("response", function callback(response){
            if (response.url() === url) {
                resolve(response);
                page.removeListener("response",callback)
            }
        })
    })
};
```
you can call the function like this :
```javascript
    const res = await waitForResponse(page,"url of the request you want to wait for");
```

**Comment by aslushnikov** [comment]
@Tim-bridgement the [`page.waitForResponse`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagewaitforresponseurlorpredicate-options) method should be helpful

For example, waiting for a response to the image request:
```js
await page.waitForResponse(response => {
  return response.request().resourceType() === 'image';
});
```

**Comment by Tim-bridgement** [comment]
Thank you this worked perfectly
