### ISSUE TITLE
Inconsistency between headless and non-headless browser

### ISSUE THREAD

**Issue by burnpiro** [puppeteer/puppeteer#3650]
### Steps to reproduce

* Puppeteer version: 1.11.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable): google.com
* Node.js version: 10.11.0

**What steps will reproduce the problem?**

Then running that code
```
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setViewport({width: 1920, height: 1080})
    await page.goto('https://www.google.com', { waitUntil: 'networkidle0' })
    await page.type('input[title="Search"]', 'Hello', { delay: 100 })
```

I'm getting error `No node found for selector: input[title="Search"]` which doesn't happen in i try to run it with
```
    const browser = await puppeteer.launch({headless: false})
```

**What is the expected result?**
Being able to enter data into input field in headless mode.

**What happens instead?**
I'm getting error:
`No node found for selector: input[title="Search"]`
```
      at assert (node_modules/puppeteer/lib/helper.js:278:11)
      at Frame.type (node_modules/puppeteer/lib/FrameManager.js:803:5)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:144:27)
      at Page.type (node_modules/puppeteer/lib/Page.js:1012:29)
      at Object.type (examples/google.test.js:31:16)
```

**Comment by aslushnikov** [comment]
@burnpiro the following works fine for me:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: true});
  const page = await browser.newPage();
  await page.setViewport({width: 1920, height: 1080});
  await page.goto('https://google.com');
  await page.type('input[title="Search"]', 'Hello', { delay: 100 });
  await page.screenshot({path: 'test.png'});
  await browser.close();
})();
```

there are many reasons you might observe this behavior:
- you've been served a different versions of website, getting into different buckets of A/B testing
- website suspects suspicious activity and takes measures to prevent

Both fall outside of the project; closing this.

**Comment by hoangdangduy** [comment]
I have same problem.

My enviroment:

- Puppeteer version: 1.20.0
- Platform / OS version: Ubuntu 18.04.3 LTS
- Node.js version: 8.10.0
- Chrome/78.0.3882.0

This error content was printed in terminal:

> (node:15455) UnhandledPromiseRejectionWarning: Error: No node found for selector: #identifierNext
>     at assert (/home/hoangdd3/node_modules/puppeteer/lib/helper.js:279:11)
>     at DOMWorld.click (/home/hoangdd3/node_modules/puppeteer/lib/DOMWorld.js:366:5)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>   -- ASYNC --
>     at Frame.<anonymous> (/home/hoangdd3/node_modules/puppeteer/lib/helper.js:111:15)
>     at Page.click (/home/hoangdd3/node_modules/puppeteer/lib/Page.js:1037:29)
>     at puppeteer.launch.then (/home/hoangdd3/pupperteer/example.js:14:16)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:15455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:15455) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This my code.

```
const puppeteer = require('puppeteer');

puppeteer.launch({
    headless: true
}).then(async browser => {
    const page = await browser.newPage();
    await page.setViewport({width: 1920, height: 1080});
    await page.goto('https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&flowEntry=ServiceLogin',  {"waitUntil" : "networkidle0"});

    await page.waitFor(2000);

    await page.click('input[type=email]');
    await page.keyboard.sendCharacter('buichicong1889@gmail.com');
    await page.click('#identifierNext');

    await page.waitFor(2000);

    await page.evaluate(() => document.querySelector('#password > div > div > div > input').click());
    await page.keyboard.sendCharacter('test');
    await page.evaluate(() => document.querySelector('#passwordNext').click());

    await page.screenshot({path: 'example.png'});

    await browser.close();
});
```

**Comment by ShubhiNigam29** [comment]
Facing same issue. Did anyone find solution to this?
