### ISSUE TITLE
Puppeteer for Firefox should be notified on Page events (load, console, domcontentloaded...)

### ISSUE THREAD

**Issue by ggrossetie** [puppeteer/puppeteer#3652]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.4.2 (`puppeteer-firefox`)
* Platform / OS version: Ubuntu 18.04.1 LTS
* Node.js version: v10.14.1

**What steps will reproduce the problem?**

1. Create a file named `main.js` with the following content:

**main.js**
```js
const b = process.env.PUPPETEER_BROWSER || 'chrome'
const puppeteer = b === 'firefox' ?
  require('puppeteer-firefox') :
  require('puppeteer')

const path = require('path')

;(async function () {
  const browser = await puppeteer.launch();
  const page = await browser.newPage()
  page.on('load', () => console.log('load'))
  page.on('domcontentloaded', () => console.log('domcontentloaded'))
  page.on('console', () => console.log('console'))
  page.on('pageerror', () => console.log('pageerror'))
  await page.goto('file://' + path.join(__dirname, 'index.html'))
  await page.close();
  await browser.close();
})()
```
2. Create a file named `index.html` with the following content:

**index.html**

```html
<!DOCTYPE html>
<html>
<head>
  <title>Hello</title>
  <meta charset="utf-8"/>
</head>
<body>
<script>console.log('hello')</script>
</body>
</html>
```
3. Run the script `main.js` against Chrome:

```
node main.js 
```
```
console
load
domcontentloaded
```
All good with `puppeteer` Chrome.

4. Run the script `main.js` against Firefox
```
PUPPETEER_BROWSER=firefox node main.js
```
```
(empty)
```

**What is the expected result?**

First of all thanks for this amazing project! :heart_eyes: :clap: 
Puppeteer for Firefox should trigger the following events and/or the `Page` should be notified:

* `console`
* `load`
* `domcontentloaded`

I'm aware that Puppeteer for Firefox is experimental but the documentation page does list these events as "Supported API": https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox#readme

**What happens instead?**

No event was triggered :neutral_face:

**Comment by ggrossetie** [comment]
I took a look at the [tests suite](https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox/test) and it's working fine with the `http:` protocol or `about:blank` but not with `file:` protocol.

**Comment by aslushnikov** [comment]
@Mogztter ah, first puppeteer-firefox bug! ♥️ Thanks for filing this!

**Comment by ggrossetie** [comment]
Hehe you're welcome :wink: 
By the way I'm trying to run Puppeteer for Firefox on Travis (both on `trusty` and `xenial`) but I always get the following error:

```
Unable to run tests using Puppeteer Error: Failed to launch Firefox!
    at onClose (/home/travis/build/Mogztter/puppeteer-firefox-travis/node_modules/puppeteer-firefox/lib/firefox/Launcher.js:174:14)
    at Interface.helper.addEventListener (/home/travis/build/Mogztter/puppeteer-firefox-travis/node_modules/puppeteer-firefox/lib/firefox/Launcher.js:163:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I tried various configuration but still no luck, should I ask on stackoverflow or should I open a new issue ? Since Travis is a popular option, I think it could be nice to explain how to setup Puppeeteer for Firefox on Travis if a "special" configuration is needed.
On Appveyor (Windows) it's running fine :nerd_face:

**Comment by msofyanqusyairi** [comment]
> Hehe you're welcome 😉
> By the way I'm trying to run Puppeteer for Firefox on Travis (both on `trusty` and `xenial`) but I always get the following error:
> 
> ```
> Unable to run tests using Puppeteer Error: Failed to launch Firefox!
>     at onClose (/home/travis/build/Mogztter/puppeteer-firefox-travis/node_modules/puppeteer-firefox/lib/firefox/Launcher.js:174:14)
>     at Interface.helper.addEventListener (/home/travis/build/Mogztter/puppeteer-firefox-travis/node_modules/puppeteer-firefox/lib/firefox/Launcher.js:163:50)
>     at Interface.emit (events.js:187:15)
>     at Interface.close (readline.js:379:8)
>     at Socket.onend (readline.js:157:10)
>     at Socket.emit (events.js:187:15)
>     at endReadableNT (_stream_readable.js:1094:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> ```
> I tried various configuration but still no luck, should I ask on stackoverflow or should I open a new issue ? Since Travis is a popular option, I think it could be nice to explain how to setup Puppeeteer for Firefox on Travis if a "special" configuration is needed.
> On Appveyor (Windows) it's running fine 🤓

have you fixed this issue? i have similar problem

**Comment by ggrossetie** [comment]
@msofyanqusyairi Yes, it's documented here: https://github.com/GoogleChrome/puppeteer/pull/3657

**Comment by mjzffr** [comment]
This should work now with `puppeteer` + Firefox Nightly. If it's still not working, feel free to reopen.
