### ISSUE TITLE
Apostrophe / quote / ' is breaking page.goto html content

### ISSUE THREAD

**Issue by chris-erickson** [puppeteer/puppeteer#3659]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0 (works to revert to 1.10.0)
* Platform / OS version: Mac/Linux
* Node.js version: LTS

**What steps will reproduce the problem?**

```javascript
html = "This is the part where it clips => ' <= This text is gone"
await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' });
```

**What is the expected result?**
Html should look like `This is the part where it clips => ' <= This text is gone` (apostrophe in html in this case is likely `&#39;`, which is the prepared html I see being sent).

**What happens instead?**
Html renders as `This is the part where it clips => &`

Whatever is being sent over the wire is dropping everything after the `&` in the html encoded `'`.

**Comment by emilsedgh** [comment]
I had the same issue as I use the same method (data uri's) to set the content.

I changed this:

`await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' });`

to this:

`await page.goto(`data:text/html,encodeURIComponent(${html})`, { waitUntil: 'networkidle0' });`

And the issue is resolved.

I'm assuming maybe a new release of Chrome had a small behavior change that caused this?

**Comment by aslushnikov** [comment]
@chris-erickson on 1.11.0, you can finally use `page.setContent` instead:

```js
html = "This is the part where it clips => ' <= This text is gone"
await page.setContent(html, { waitUntil: 'networkidle0' });
```

From now on, the `page.setContent` is _the_ way to set HTML to the page, so data URL navigation
hack is no longer needed.

Other than this, it looks like @emilsedgh's workaround might be helpful.

Hope this helps.

**Comment by emilsedgh** [comment]
@aslushnikov I personally use this method because page.setContent and relying on window load events doesn't guarantee web fonts being loaded.

But, if im understanding correctly, i can now use `page.setContent` with `networkidle0`. That covers my usecase as well right?

**Comment by emilsedgh** [comment]
Oh that's the primary change in 11.0! Thank you pptr is great.
