### ISSUE TITLE
cosmetic update - tone of logo surface from light source

### ISSUE THREAD

**Issue by kensoh** [puppeteer/puppeteer#366]
This is a minor cosmetic update on Puppeteer's logo. The rectangle surface at lower left corner seems to have the wrong shade, base on the scene's light source. Below are the original and the updated ones. Of course, if the designer intentionally wants to make the design asymmetric then this is irrelevant.

**original -**
![original_logo](https://user-images.githubusercontent.com/10379601/29446475-fc349fda-841e-11e7-9d75-e6526dfc3ec1.png)

**updated -**
![updated_logo](https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png)
 
Logo in readme is based on GitHub resource, thus posting here before sending PR for consideration.

**Comment by kensoh** [comment]
Seems like after public release the forked repo keeps showing this. Not sure if anyone else is experiencing this. In any case, if the above suggestion is considered I guess anyone can submit the PR or update readme to new image URL. Not sure what's with the private repo and how to fix it.

![screen shot 2017-08-18 at 2 24 03 pm](https://user-images.githubusercontent.com/10379601/29446830-edf477e0-8420-11e7-8221-5bbc1814be8c.png)

PS: The updated image is made using GIMP and saved as .png. The image quality matches, but image size is double original to ~15kb. Can't figure out why after trying all file-saving options. I think is related to RGB (to retain original quality) / index-color (quality changes). The original logo creator will be able to generate another new one appropriately if needed. Also, do close the issue if it's simply irrelevant.

**Comment by aslushnikov** [comment]
@kensoh I had the same issue with the private fork. I "fixed" it by deleting the fork and re-forking one more time.

I'm not sure who's the actual author of the logo, it's either @paulirish or @ebidel. They probably know if the shades are intentional or just random :)

**Comment by kensoh** [comment]
Thanks @aslushnikov that works for me! Sent PR https://github.com/GoogleChrome/puppeteer/pull/369 pls ignore the issue / PR if it's intentional.

I happen to notice the color when browsing on mobile, so thought to check with you guys :smile:

**Comment by joelgriffith** [comment]
Can we fix the aliasing/jagginess issues in the "strings"?

**Comment by Garbee** [comment]
It's just a demo logo until an actual designer gets their hands onto doing one.
