### ISSUE TITLE
Firefox: Loading extension ignored

### ISSUE THREAD

**Issue by denar90** [puppeteer/puppeteer#3660]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: MacOS
* Node.js version:v9.5.0

**What steps will reproduce the problem?**

Using example from [docs](https://github.com/GoogleChrome/puppeteer/blob/v1.10.0/docs/api.md#working-with-chrome-extensions) and any extension from store, just downloading and unpack it for FF and Chrome.

**What is the expected result?**

If put breakpoint on `await browser.close();` and look at Chrome browser, installation process can be seen. 

**What happens instead?**

In FF case, just empty page no matter how long to wait.

I suppose FF has different mechanism for addons and installing them. Probably it's just docs issue and missed some flag or something bigger and related to security stuff...

**Comment by aslushnikov** [comment]
> Using example from docs and any extension from store, just downloading and unpack it for FF and Chrome.

@denar90 The documentation at [`//docs/api.md`](https://github.com/GoogleChrome/puppeteer/blob/v1.10.0/docs/api.md#working-with-chrome-extensions) covers Chromium Puppeteer. we'll come up with a similar write-up for Puppeteer-Firefox later on as the project matures.

**Comment by denar90** [comment]
Thanks :)
