### ISSUE TITLE
login into/Authenticate SAML or SSO base site

### ISSUE THREAD

**Issue by Kunal912** [puppeteer/puppeteer#3663]
Hi Support,

I am using puppeteer for site scraping in Node js.But the site uses SAML/SSO Authentication mechanism.
I don't know how to use puppeteer for these type of sites.Everytime i try to login into site using basic puppeteer approach,it says access denied.

Please help me out.

Thanks

**Comment by aslushnikov** [comment]
Hey @Kunal912,

It's hard to say for sure what's going on; if you can share an example of the website where login doesn't work, we (or someone else) might be able to help. Feel free to re-file with something we can work with.

**Comment by Kunal912** [comment]
Hey @aslushnikov,

Here are the websites where login is not working

1. https://www.gebiz.gov.sg/ptn/login/loginCorpPass.xhtml
2. https://service.ariba.com/Supplier.aw/128483075/aw?awh=r&awssk=kkQ3AQ.4&dard=1&ancdc=1

Also i have tried the code samples from github puppeteer but nothing is working in my case.
It will be helpful if you can provide me the sample code for SSO and SAML authentication based sites.

Thanks

**Comment by aslushnikov** [comment]
@Kunal912 any chance you can provide me with some login credentials that I can use to play around and debug?

**Comment by Kunal912** [comment]
@aslushnikov Sorry i can't do that but you can use other sites that uses SAML/SSO authentications.
you can look into the below link.
http://saml.xml.org/wiki/list-of-organizations-using-saml

**Comment by parkervandyk** [comment]
What was the resolution of this issue? I'm running into the same thing.

**Comment by cujarrett** [comment]
Any update?

**Comment by Kunal912** [comment]
Hi @parkervandyk / @cujarrett 

Here is the approach i tried and it worked for me.

`myfunction: function () {`
    `return new Promise(function (resolve, reject) {`
        `(async function main() {`
                `var browser = await puppeteer.launch({ headless: true, timeout: 30000, ignoreHTTPSErrors: true });`
               ` let page = await browser.newPage();`
                `await page.goto('https://service.ariba.com/Supplier.aw/125007078/aw?awh=r&awssk=Cd19ecPv&dard=1');//Login page URL`
                `await page.waitFor(2000);`
                `await page.type('.w-txt-dsize', 'my-website-username'); //.w-txt-dsize - its the classname for username html element field`
                `await page.type('#Password', 'my-website-password'); // #Password  -its the ID for password html element field`
                `await page.keyboard.press('Enter');`
                `await page.waitFor(5000);`
               ` await page.goto("https://service.ariba.com/Discovery.aw/ad/aodSsoLogin"); //URL of page to redirect after Login`
                `await page.waitFor(10000);`
       ` })()`
    `})`
`}`



Thanks
