### ISSUE TITLE
Headless Chrome Puppeteer generated PDF does not show some Unicode fonts on Acrobat

### ISSUE THREAD

**Issue by alirazib** [puppeteer/puppeteer#3668]
### Steps to reproduce
1. Use the HTML with Headless Chrome to generate a PDF.
2. Open the PDF using Acrobat Reader, and notice that there's a dialog box shown for missing fonts. Note that on different Windows systems, the PDF output is different (e.g, the PDF that I attached was generated on my system, and it shows some fonts missing, while on another Windows system, some other fonts were missing.) It seems that Headless embeds fonts differently than what Acrobat is expecting.

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: Win10
* URLs (if applicable):
* Node.js version: 10.13.0

**What steps will reproduce the problem?**
Use the code below to render the HTML file to generate a PDF.

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
const path = require('path');
async function createHeadlessChromeInstance() {

    browser = await puppeteer.launch(
        {
            ignoreHTTPSErrors: false
        }
    );

    const page = await browser.newPage();

    // Set viewport to a fixed size. 
    await page.setViewport({width: 750, height: 600});

    return page;
}

async function generatePdf() {
    // create page instance
    let page;
    let navigationTimeout = 60000;  // 1 min
    let response;
    try {
        page = await createHeadlessChromeInstance();

        response = await page.goto("file://" + 'c:\\testdata_font.htm', {
            timeout: navigationTimeout,
            waitUntil: ['load', 'networkidle2']
        });

        await page.waitFor(500);
    }
    catch (error) {
        throw error;
    }

    // generate pdf for the current page
	pdfProperties = {};
    pdfProperties.path = 'output.pdf';
    pdfProperties.margin = '1in';
    pdfProperties.displayHeaderFooter = false;
    pdfProperties.printBackground = true;

    pdfProperties.width = '8.27in';
    pdfProperties.height = '11.7in';
    await page.pdf(pdfProperties);

    await browser.close();
}


async function main() {
        try {
            await generatePdf();
        } catch(e) {
            return process.exit(1);
        }
		console.log("pdf conversion completed successfully.");
        return process.exit(0);
}
main();
```

The HTML is:

```
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>
<h1 style="font-family:Aldhabi;">This is a Aldhabi  الخطوط العربية النصي</h1>
<h1 style="font-family:Arabic Typesetting;">Arabic Typesetting   الخطوط العربية النصي</h1>
<h1 style="font-family:Shonar Bangla;">This is a Bangla Supplemental Fonts:</h1>
<h1 style="font-family:Shonar Bangla;">This is a বাংলায় টেক্সট</h1>
<h1 style="font-family:DengXian	;">This is a DengXian  中文文本</h1>
<h1 style="font-family:KaiTi;">This is a KaiTi 中文文本</h1>
<h1 style="font-family:DFKai-SB;">This is a DFKai-SB  中文文本</h1>
<h1 style="font-family:Aparajita;">This is a Aparajita तेक्स्त इन देवनगरी</h1>
<h1 style="font-family:Sanskrit Text;">This is a Sanskrit Text तेक्स्त इन देवनगरी</h1>
<h1 style="font-family:FrankRuehl;">This is a FrankRuehl    טקסט בעברית</h1>
<h1 style="font-family:Meiryo;">This is a Meiryo テキストは日本語です</h1>
<h1 style="font-family:Tunga;">This is a Tunga ಪಠ್ಯವು ಕನ್ನಡದಲ್ಲಿದೆ</h1>
<h1 style="font-family:Batang;">This is a Batang 텍스트는 한국에있다</h1>
<h1 style="font-family:Karthika;">This is a Karthika ടെക്സ്റ്റ് മലയാളത്തിലാണ്</h1>
<h1 style="font-family:Gautami;">This is a Gautami, టెక్స్ట్ టెలోగిలో ఉంది</h1>
<h1 style="font-family:DilleniaUPC;">This is a DilleniaUPC ข้อความเป็นภาษาไทย</h1>
<h1 style="font-family:Latha;">This is a Latha  தமிழ் மொழியில் உள்ளது</h1>

</body>
</html>
```

**What is the expected result?**
A PDF file which is shown correctly on Acrobat Reader.

**What happens instead?**
The PDF is shown incorrectly on Acrobat Reader. If I open the PDF with Chrome browser or some other PDF reader, then the fonts are shown. 
[output.pdf](https://github.com/GoogleChrome/puppeteer/files/2677747/output.pdf)
The screenshot of Adobe error:
<img width="480" alt="headless_font_not_showing" src="https://user-images.githubusercontent.com/8452126/49969466-93ce9780-fef6-11e8-9498-00f516037fef.png">

**Comment by aslushnikov** [comment]
> The PDF is shown incorrectly on Acrobat Reader. If I open the PDF with Chrome browser or some other PDF reader, then the fonts are shown.

@alirazib Could it be an Acrobat Reader bug then?

**Comment by alirazib** [comment]
@aslushnikov  Thanks for replying. Yes that was my first impression too, but when I tried to open the HTML on Chrome browser, and then print it to PDF, the resulting PDF opens fine on Acrobat. 

Also, if I open output.pdf with Chrome browser (the fonts show fine) and copy all contents to clipboard, then pasting it in some other text processor results in missing text as well. So it appears that the PDF contains those Unicode fonts in a way that are not portable across products.

Is there a way that I could manipulate fonts in the HTML before PDF is generated via Headless? For example, is the Puppeteer functionality available to identify certain fonts and re-direct the render function to use another set of available fonts?

P.S. I updated my original post to include a screenshot of the issue.

**Comment by aslushnikov** [comment]
> Is there a way that I could manipulate fonts in the HTML before PDF is generated via Headless? For example, is the Puppeteer functionality available to identify certain fonts and re-direct the render function to use another set of available fonts?

@alirazib You can try using DevTools protocol's [`CSS.getPlatformFontsForNode`](https://vanilla.aslushnikov.com/#CSS.getPlatformFontsForNode), but that's quite involved.

Puppeteer's PDF generating functionality is fully driven by Chromium's "Save as PDF".
I'd recommend posting on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) or submitting a bug to Chromium right away at https://crbug.com/new - Chromium's PDF team might be able to help.

If you initiate any of these, please post a link here for the future reference. I'll close this since it falls outside the Puppeteer project.

Hope this helps.

**Comment by alirazib** [comment]
Opened a bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=915012

Thanks @aslushnikov  for prompt responses!

**Comment by tommymarshall** [comment]
~Thanks a bunch. We're running into this bug as well, but our's is displaying all characters as bullets, not just unicode fonts.~

Upgrading to **version 1.11.0** did the trick for us.

**Comment by cbratschi** [comment]
We are getting similar issues with the strong HTML element and puppeteer 1.19. One PDF with a different German texts inside the strong works fine whereas the French version is not shown at all. The French text does not contain any special characters where the German version has an Umlaut.

Also tried to use the same German text in the French PDF but this did not help. The complete string is missing in the PDF.

Very strange.

This issue should be re-opened because it's puppeteer related. On standalone Chrome the PDFs are fine in the print preview and afterwards (on macOS).

**Comment by Abdullahbutt3434** [comment]
I am also facing the same issue  I am using browshot spatie which use  puppeteer. I am using centos and install all depndencies require for puppeteer. headless chromium is working fine download pdf for me and working perfectly fine for english but for other language it was not working then I found solution
you need to install fonts in your linux system manually i download fonts from below site you can download your one then it work fine
https://installati.one/centos/7/lohit-gujarati-fonts/
