### ISSUE TITLE
Download failed: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium' + puppeteer@0.9.0

### ISSUE THREAD

**Issue by unclehking** [puppeteer/puppeteer#367]
npm install puppeteer

Download failed: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium'

CentOS  6

**Comment by codenoid** [comment]
did you try with `sudo` ?

**Comment by meldron** [comment]
What is your `npm.prefix`?

Check it with: `npm prefix -g`

If the directory is located somewhere were a normal user has no write access you will have to `sudo npm install puppeteer` or install it in some project (`npm init`)

**Comment by umpox** [comment]
I have the same problem, I'm using it as a dependency on a project I'm working on. If I try to install my project globally using `sudo npm install myProject -g` I get this same error message

**Comment by Garbee** [comment]
Also ref #375

**Comment by ebidel** [comment]
Shall we mark this as a dupe of https://github.com/GoogleChrome/puppeteer/issues/375?

**Comment by aslushnikov** [comment]
Dupe of #375 :)

**Comment by kauecastro** [comment]
Have already you fixed this problem ? Could you show me the solution ? :)

**Comment by antsfee** [comment]
init project i use yarn 
I have the same problem. 
then I remove all dependency
 , use npm  reinstall package ,
 ok .
 hope it's usefully

**Comment by sryze** [comment]
How come this fails to install even if using sudo? I'm trying to install [critical](https://github.com/addyosmani/critical) using `sudo npm install -g critical` but it gives me this error.

**Comment by proyb6** [comment]
@sryze It has the do with Nodejs 8, have you tried using Nodejs 6 or 7?

**Comment by tyt34** [comment]
guys, don't use SUDO when you install this module. Вот.

**Comment by laguiz** [comment]
Workaround : https://github.com/GoogleChrome/puppeteer/issues/1303#issuecomment-350815938 (works from Dockefile)

**Comment by hopeseekr** [comment]
After hunting around the Internet, I found a solution:

`sudo npm install -g puppeteer --unsafe-perm=true`

**Comment by muhammedbasilsk** [comment]
@hopeseekr you rock !!!

**Comment by Liberateur** [comment]
`sudo npm install -g puppeteer --unsafe-perm=true` works and really thanks ! But I really wanted to understand why I had this error.

For me :
`npm init && npm i puppeteer` -> does not work
`npm init && sudo npm i puppeteer` -> does not work
`sudo npm init && sudo npm i puppeteer` -> works

**Comment by naqashse102** [comment]
@hopeseekr you saved my day

**Comment by 76765357** [comment]
don't use nvm
