### ISSUE TITLE
Navigation after click not working regardless of actions I take

### ISSUE THREAD

**Issue by thamerla** [puppeteer/puppeteer#3670]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11
* Platform / OS version: WSL (openSUSE on Windows)
* URLs (if applicable): -
* Node.js version: 10

**What steps will reproduce the problem?**

So in pure text what I am trying:
1. Click a button.
2. Wait until navigation loads. Or simply put - link changes.
3. Fetch url.
4. In different incognito browser go to the link and do other actions.

Unfortunately, because I need to fetch the link I can't use waitForSelector. So I am stuck with navigation and the headache all of that causes. Url is a casual link with dynamically generated ID that I can't access otherwise.

Code:
```
await helpers.click(mainUserPage, '#RematchButton');
await mainUserPage.waitForNavigation({waitUntil: "networkidle0"});
 let gameUri = mainUserPage.url();
    await weakerUserPage.goto(gameUri, {
        waitUntil: ['load']
    });
```

helpers.click:
```
async function click(page, button) {
   try {
     await page.waitForSelector(button, {visible: true});
     await page.click(button);
   } catch (e) {
     console.log(e);
   }
 }
```

I tried Promise.all([]) - didn't help at all. So really I don't know what to do with that. I am sure navigation causes the headache as without the line button is clicked and navigation is done, just wrong url is fetched.

**What is the expected result?**
Navigation

**What happens instead?**
Blockage

**Comment by thamerla** [comment]
Overall puppeteer is a great library but page.click is one huge headache. Even the method itself sometimes works, sometimes it doesn't... really weird thing.

**Comment by aslushnikov** [comment]
@nonyy can you share an example that I can try locally? E.g. your code snippet and the original URL that holds the link that you try to click.

**Comment by thamerla** [comment]
@aslushnikov I don't think so as the code and link itself is hidden behind login. Ironically the navigation part doesn't work now somewhere else. It's a well known issue documented at many places so I don't think my usecase is specific. 

Examples:
https://github.com/GoogleChrome/puppeteer/issues/1637

The easiest workaround is to use page.waitForSelector() but unfortunately I can't use it so I am stuck with navigation.

**Comment by thamerla** [comment]
@aslushnikov Basically here's my problem:
https://github.com/GoogleChrome/puppeteer/issues/2293
more specifically:
https://github.com/GoogleChrome/puppeteer/issues/2293#issuecomment-378228077

**Comment by thamerla** [comment]
Alright another update. After changing navigation lines to:
```
 async function nativeClick(page, button) {
   await page.evaluate((button) => {
     document.querySelector(button).click();
   }, button);
 }
```
and using it instead of built-in click method surprisingly the code works 100% and never stops at navigation. Otherwise when there's a conflict between click redirect & navigation there are ALWAYS problems.

**Comment by aslushnikov** [comment]
>  Otherwise when there's a conflict between click redirect & navigation there are ALWAYS problems.

@nonyy Can you elaborate on this one? Maybe I'd be able to build a repro to help debug this.

**Comment by thamerla** [comment]
@aslushnikov 
https://github.com/GoogleChrome/puppeteer/issues/2293#issuecomment-378228077

elaborate? this ->
> @vsemozhetbyt From my experience this only works 50% of the time, for me.
> 
> await Promise.all([
>   page.waitForNavigation() 
>   page.click('a')
> ]);
> 

Basically, clicking + navigation == troubles. For example:
1) Enter data into login form
2) Submit login
3) Navigation
4) Sadly, race between navigation and clicking causes everything to stop and throws Navigation error.

And what's even more funny is that this race isn't always triggered. Sometimes it causes error, sometimes it doesn't. I don't know what's happening but in my case nativeClick solved it.

**Comment by thamerla** [comment]
@aslushnikov any update on this?

**Comment by aslushnikov** [comment]
> any update on this?

@nonyy I see your symptoms, but I don't think this is something actionable until there's something I can run locally that reproduces this behavior and that we can debug. Can you share a repro script together with the URL that illustrates the problem?

**Comment by thamerla** [comment]
@aslushnikov Sadly it happens randomly as someone before me stated above.

**Comment by mk0x9** [comment]
@aslushnikov I think I'm stumbled on a case with wonky behaviour.

```javascript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: false, devtools: true });

    const page = await browser.newPage();

    await page.goto(
        'https://formular.berlin.de/jfs/findform?shortname=OTVBerlin&formtecid=4&areashortname=LABO&termin=1&dienstleister=327437&anliegen[]=324659&herkunft=1'
    );
    await andWait(page, page.click('#txtLinkEnglisch'));
    await andWait(page, page.click('[name="btnTerminBuchen"]'));
    await andWait(page, page.select('[name="cobStaat"]', '160'));
    await andWait(page, page.select('[name="cobFamAngInBerlin"]', 'No'));
    await andWait(page, page.select('[name="cobAnliegen"]', '324659'));
    await page.click('[name="cbZurKenntnis"]');
    await andWait(page, page.click('#labNextpage'));
    await andWait(
        page,
        page.select('[name="cobGenehmigungBereitsVorhanden"]', 'No')
    );
    await page.type('[name="tfFirstName"]', 'John');
    await page.type('[name="tfLastName"]', 'Doe');
    await page.type('[name="tfGebDatumJahr"]', '1980');
    await page.select('[name="cobVPers"]', '2');
    await page.type('[name="tfMail"]', 'john.doe@gmail.com');
    await browser.close();

    async function andWait(page, promise) {
        const [result] = await Promise.all([page.waitForNavigation(), promise]);

        return result;
    }
})();
```

It will break on `await andWait(page, page.click('#labNextpage'));`. Yet if I replace this call with `await page.click(); await page.waitForNavigation();` everything works. Clicking on button itself calls `form.submit();` without yielding javascript thread back to browser so it shouldn't

**Comment by mrmign** [comment]
```javascript
const puppeteer = require('puppeteer');

const GITHUB_USER = 'your user name';
const GITHUB_PWD = 'your password';

(async () => {
    const browser = await puppeteer.launch({args:['--no-sandbox']})
    const page = await browser.newPage();
    await page.goto('https://github.com/login');
    await page.type('#login_field', GITHUB_USER)
    await page.type('#password', GITHUB_PWD)
    await page.click('[name="commit"]')
    await page.waitForNavigation()
    await page.screenshot({ path: "github.png" })
    browser.close()
})();
```
Here is my code. I always have Navigation Timeout error. The error msg is as following
```
(node:32594) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/root/js/github/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
  -- ASYNC --
    at Frame.<anonymous> (/root/js/github/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForNavigation (/root/js/github/node_modules/puppeteer/lib/Page.js:649:49)
    at Page.<anonymous> (/root/js/github/node_modules/puppeteer/lib/helper.js:112:23)
    at /root/js/github/github.js:17:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```
Anyone how to use the Navigate function?

**Comment by geminiyellow** [comment]
still not working.

**Comment by nhhockeyplayer** [comment]
having similar problem
no form just a button
click

no post happens

im wondering what kind of headers or things need to be replicated in the intercept for the post to occur or if we need to setup an intercept to augment the POST

**Comment by aslushnikov** [comment]
@mrmign you should use `Promise.all` trick to combine action an watchdog.

The following works for me:

```js
const puppeteer = require('puppeteer');

const GITHUB_USER = 'username';
const GITHUB_PWD = 'pass';

(async () => {
    const browser = await puppeteer.launch({args:['--no-sandbox'], headless: false})
    const page = await browser.newPage();
    await page.goto('https://github.com/login');
    await page.type('#login_field', GITHUB_USER)
    await page.type('#password', GITHUB_PWD)
    await Promise.all([
      page.click('[name="commit"]'),
      page.waitForNavigation(),
    ]);
    await page.screenshot({ path: "github.png" })
    browser.close()
})();
```

@mk0x9 your script throws a "failed to find element with selector" error. I guess it got outdated - please, file a new issue if the problem doesn't go away. 

I'll close this issue for now since it's too general. If you experience this issue, please file a new one with a good repro instead of commenting here.

Thanks!
