### ISSUE TITLE
Default margins for header and footer are already added

### ISSUE THREAD

**Issue by supriyapethkar** [puppeteer/puppeteer#3672]
* Puppeteer version: 1.11
* Platform / OS version: MacOS Mojave
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
Below is my to code to generate the PDF:

`
await page.pdf({format: 'A4', displayHeaderFooter: true, headerTemplate: "<p class='header' style='font-size:12px; margin-top: 0px'>Hello Header</p>", footerTemplate: "<p class='footer' style='font-size:12px'>Hello Footer</p>", margin: {top: '100px', bottom: '100px'}});
`
I am basically trying to set the the top margin for the headerTemplate to 0. But it seems this style is not picked. 

<img width="1122" alt="screen shot 2018-12-14 at 10 27 02 am" src="https://user-images.githubusercontent.com/38549150/49983810-da6dd180-ff8a-11e8-9c9d-ac80e824bf48.png">

If I am giving margin-top value as some negative value, then the header seems to move upwards but it also applies the same margin value to it's left. Weird! ( I have applied the negative value to be -15px)

<img width="1162" alt="screen shot 2018-12-14 at 10 28 00 am" src="https://user-images.githubusercontent.com/38549150/49983835-01c49e80-ff8b-11e8-939f-d8d366527c9f.png">

**What is the expected result?**
Header should be placed just below the start of page without any margins when I provide margin-top value as 0px. Also, if I give some negative value to margin-top, it should not apply the same value to margin-left, right and bottom.

**What happens instead?**
Header has some default margins even if we provide inline margins. Is it that Puppeteer internally adds some default margins to headerTemplate and  footerTemplate ?

**Comment by SoerenWeber** [comment]
This is related to #4132 . Chromium sets a default padding for header and footer. You can override it by selecting `#header` and `#footer` in your CSS.
