### ISSUE TITLE
Don't support thai langulage

### ISSUE THREAD

**Issue by 3fuyu** [puppeteer/puppeteer#3675]
### Don't support thai langulage

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: CentOS7
* URLs (if applicable): 
* Node.js version: 8.4.0

** What steps will reproduce the problem? **

I already checked Troubleshooting.
And install many fonts package, just like "fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont" and "https://www.ezylinux.com/add-fonts-thai-%E0%B9%83%E0%B8%99-linux-%E0%B8%81%E0%B8%B1%E0%B8%99/".

When I screenshot some html, the thai langulage show not good :(

![image](https://user-images.githubusercontent.com/9128418/50009250-729ea180-fff1-11e8-9ae5-9e023cfab7cf.png)

**What is the expected result?**

![image](https://user-images.githubusercontent.com/9128418/50009285-8fd37000-fff1-11e8-86b0-7a931a22a0f9.png)

**Comment by aslushnikov** [comment]
@3fuyu Generally, all font problems should be resolvable by installing the right font package. What's your page URL?

**Comment by 3fuyu** [comment]
@aslushnikov My page is normal which include thai langulage, I also think it's a font problem. But I already install packages from Troubleshooting and yum groupinstall thai-support also useless. Can you give me some ideas for solve this problem? Thanks very much :)

**Comment by aslushnikov** [comment]
> My page is normal which include thai langulage

@3fuyu Would you mind sharing the page? I might be able to try something myself and see what works.

> Can you give me some ideas for solve this problem?

Not really - I haven't had any experience with Thai fonts.

**Comment by 3fuyu** [comment]
@aslushnikov Any include thai langulage page was failed. Just like 
http://www.thai-language.com/default.aspx?nav=control

**My engine result**

![image](https://user-images.githubusercontent.com/9128418/50039776-d2895c80-0072-11e9-9360-cbd5b9c24c00.png)

**Comment by 3fuyu** [comment]
The Troubleshooting's dependents is not enough. I install many ttf fonts and solve this problem. It's close, thanks.

**Comment by thepors** [comment]
@3fuyu I'm facing this problem. I want to change default Thai font to other beautiful Thai font. Can you suggestion a solution please?

**Comment by samymassoud** [comment]
Just install the following fonts and it should fix it
`sudo apt-get install -y fonts-thai-tlwg-ttf`
