### ISSUE TITLE
Unable to install puppeteer in yarn

### ISSUE THREAD

**Issue by 0xdeafcafe** [puppeteer/puppeteer#3677]
### Steps to reproduce
* Puppeteer version: ^1.11.0
* Platform / OS version: macOS Mojave
* URLs (if applicable): n/a
* Node.js version: v10.9.0

**What steps will reproduce the problem?**
1. Run the command `yarn add puppeteer`

**What is the expected result?**
`puppeteer` is added to my package.json and installed perfectly.

**What happens instead?**
```
➜  service-auth git:(master) ✗ yarn add puppeteer
yarn add v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I assume this is because of the `event-stream` sh*t show, but can't see anybody else running into this issue. I've tried clearing my yarn cache, node modules, etc and can't fix anything.

**Comment by gidztech** [comment]
Puppeteer has no dependency on `event-stream`. I suspect it's actually a problem with another dependency in your `yarn.lock` file. 

The easiest fix would be to remove the `yarn.lock` file as well as `node_modules`, then run `yarn` and `yarn add puppeteer` again to rebuild it. 

This may introduce new versions of dependencies into your code base, which may not always be desirable, so the alternative would be to look at your dependency tree and update only the packages affected by the dodgy `event-stream` version.

**Comment by 0xdeafcafe** [comment]
Yep.. That worked, very embarrassing that I didn't try and remove the yarn lock 🙄. Thanks @gidztech, very much appreciated!

**Comment by km4dlpx** [comment]
Received malformed response from registry for "typescript". The registry may be down. 
What about this error, I always got this when trying to do yarn
