### ISSUE TITLE
How can I enable plain INFO level logging?

### ISSUE THREAD

**Issue by ahmedmohiduet** [puppeteer/puppeteer#3678]
So, trying `env DEBUG="puppeteer:*" node script.js` with my puppeteer which giving me tons of logs, but in fact what I'm looking to have is logs regarding for example navigating url, navigated, redirected successfully, waiting on selector, selector-found, launching/closing etc. my `env INFO="puppeteer:*" node script.js` at the moment not appears to be working. My testing scripts getting now full of 'Navigating, done, waiting on selector... console.logs
Any workaround?

**Comment by aslushnikov** [comment]
@ahmedmohiduet I'm not sure what's INFO logging is, but it looks like you want the public API logging we used to have. Please see [this comment](https://github.com/GoogleChrome/puppeteer/issues/3454#issuecomment-434951602) on how to get it back.

Hope this helps

**Comment by ahmedmohiduet** [comment]
> @ahmedmohiduet I'm not sure what's INFO logging is, but it looks like you want the public API logging we used to have. Please see [this comment](https://github.com/GoogleChrome/puppeteer/issues/3454#issuecomment-434951602) on how to get it back.
> 
> Hope this helps

Thank you aslushnikov! Looking into it

**Comment by koresar** [comment]
@aslushnikov Hi mate. The suggestion does not work any more (puppeteer 2.1.1).
Any quick alternatives?
