### ISSUE TITLE
Failed to launch Chromium, troubleshooting step doen't work?

### ISSUE THREAD

**Issue by SuperHenkie** [puppeteer/puppeteer#3679]
I installed Puppeteer on a newly installed Ubuntu 18.04 server from scratch (including latest nodejs and npm). Upon running the example.js I get this, apparently due to missing libraries:

> Error: Failed to launch chrome!

The [Troubleshooting section](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) suggests to run `ldd chrome | grep not` but that obviously doesn't work as there is no `chrome` directory. It says:

> ldd: ./chrome: No such file or directory

And same for `chromium` instead of `chrome`. Is there a correct way to find out which packages or libraries are missing for this version of Chromium (the one that comes installed along with Puppeteer by default) so I can install those?

**Comment by Megagyger** [comment]
You need to go the puppeteer package and find chrome inside there.
then run ldd chrome | grep not 
That will give you the dependencies you need to install

**Comment by tanjunchen** [comment]
@Megagyger Thanks

**Comment by Mutale85** [comment]
You need to go the puppeteer package and find chrome inside there.
then run ldd chrome | grep not
That will give you the dependencies you need to install ... 
I did this, but can't find chrome inside. 
Any ideas what I can do?

**Comment by MahbbRah** [comment]
I've created a video to help you walk through the steps, how you can install those missing dependencies in order to get chromium working
Here: https://youtu.be/h70iB_9pCMo
