### ISSUE TITLE
Add an option to not absolutise relative URLs when exporting a PDF

### ISSUE THREAD

**Issue by brendon** [puppeteer/puppeteer#3682]
Currently relative URLs are made absolute when exporting a PDF. Would you be open to the idea of allowing this to be an option that can be turned off? Relative URLs are valid in PDF's and Adobe Acrobat will open files (with a warning) that are linked relative to the PDF file.

In my use case I'm exporting a document and also zipping up relative assets together into a bundle. When the user unzips the package the PDFs URL's should point at these local assets.

**Comment by aslushnikov** [comment]
@brendon Puppeteer's PDF rendering is 100% driven by Chromium's "save as PDF". If this is supported by Chromium, we'll be happy to provide the option.

So please file this over to https://crbug.com/new - Chromium PDF team should be able to assist on this.
I'd appreciate if you cross-post the link to the bug here for the future reference.

I'll close this for now - we can revisit once upstream work is done. Thanks!

**Comment by brendon** [comment]
Thanks @aslushnikov :) I've filed a ticked over there :)

**Comment by bryceschober** [comment]
FYI the Chromium bug is https://bugs.chromium.org/p/chromium/issues/detail?id=931511. I ended up filing a new bug that got resolved as a duplicate.

@aslushnikov It sure would be nice if someone could help promote this issue from the Puppeteer side. I've now run into this problem with at least two different VS Code extensions that are using Puppeteer.

**Comment by matteoulissi** [comment]
Bumping up the issue, like @bryceschober said, maybe someone from the Puppeteer side needs to promote the issue on the Chromium bug ticket.

I had to abandon puppeteer and pass to another library to generate pdf with relative links :(

**Comment by geral-victor** [comment]
@matteoulissi I ran into the same problem: see [this SO question](https://stackoverflow.com/questions/77751317/relative-link-to-local-file-not-clickable-when-generating-pdf-with-puppeteer). 
What library did you use to be able to use relative local links properly?
