### ISSUE TITLE
Puppeteer issue with application supports only Commonjs modules

### ISSUE THREAD

**Issue by SenthilkumarRasan** [puppeteer/puppeteer#3685]
I am trying to use puppeteer in one of my tools which supports only Commonjs formatted modules. I am getting error in loading/accessing puppeteer within the tool. Does puppeteer build in Commonjs format? if not so we have any other option to use it in tools restricted to use commonjs formatted modules? Thanks

**Comment by aslushnikov** [comment]
@SenthilkumarRasan Puppeteer uses commonjs exclusively, so it should be require'able - check out all our [examples](https://github.com/GoogleChrome/puppeteer/tree/master/examples). If it doesn't work for you, then it looks like an issue with your host environment.
