### ISSUE TITLE
Fail to launch chromium, is there a troubleshooting for Red Hat Enterprise Linux Server

### ISSUE THREAD

**Issue by jackieh00** [puppeteer/puppeteer#3686]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.12.0
* Platform / OS version: 
Red Hat Enterprise Linux Server release 6.10 (Santiago)
* URLs (if applicable):
* Node.js version: v8.14.0

**What steps will reproduce the problem?**
1.  install puppeteer
2. run example, get error
(node:15335) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
./node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

_Please include code that reproduces the issue._

1. npm install puppeteer
2. node example
(example.js - 
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
)

3. ldd ./node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome | grep not

./node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux/chrome)
00:07:28   	libXss.so.1 => not found
00:07:28   	libgtk-3.so.0 => not found
00:07:28   	libgdk-3.so.0 => not found

**What is the expected result?**
What are the dependency package to install the missing share files for Redhat linux 

**What happens instead?**
Can't launch chromium

**Comment by matthaywardwebdesign** [comment]
Try installing Google Chrome first - this should install the required dependencies. I found some instructions here [https://www.tecmint.com/install-google-chrome-on-redhat-centos-fedora-linux/](https://www.tecmint.com/install-google-chrome-on-redhat-centos-fedora-linux/)

**Comment by jackieh00** [comment]
@matthaywardwebdesign - Thanks.  The link above mention that Google Chrome browser doesn't support Rhel 6.   I have Red Hat Enterprise Linux Server release 6.10  and it doesn't work for me.
Is there any work around for rhel6?

**Comment by aslushnikov** [comment]
> Is there any work around for rhel6?

@jackieh00 I'd ask this question on some rhel forum instead - there should be more knowledge downstream on how to run chromium there.
