### ISSUE TITLE
ERROR:cert_verify_proc_nss.cc(974)] CERT_PKIXVerifyCert for xxx.com failed err=-8172

### ISSUE THREAD

**Issue by HassyMasa** [puppeteer/puppeteer#3687]
CENTOS7

$ node -v
v11.4.0

$ npm -v
6.5.0

puppeteer@1.11.0

Chromium r609904

`$ npm install -g puppeteer --unsafe-perm=true --allow-root
`

```
browser = await puppeteer.launch(
{
  dumpio: true,
  ignoreHTTPSErrors: true,
  args :[
   '--ignore-certificate-errors',
   '--enable-features=NetworkService',
   '--no-sandbox',
   '--disable-setuid-sandbox',
   '-–disable-dev-shm-usage',
   '--lang=ja,en-US;q=0.9,en;q=0.8',
   '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36',
  ]
}
page = await browser.newPage();
await page.goto( _req.query.url_, { waitUntil : 'domcontentloaded', timeout : COMTIMEOUT });
await page.setViewport({width: 1280, height: 1080});
await page.screenshot({ path : 'img.png',type :'png' });

:
:

```
I can get a screenshot, but always this error occurs more than

`[1218/153346.283096:ERROR:cert_verify_proc_nss.cc(974)] CERT_PKIXVerifyCert for communityserver.org failed err=-8172`

**Comment by aslushnikov** [comment]
@HassyMasa I'm not sure why this error happens, but if it doesn't break your script I'd disregard it. If you're very concerned about chrome's stderr log, I'd try asking on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) or checking Chromium source at https://cs.chromium.org.

**Comment by HassyMasa** [comment]
@aslushnikov Okey, thank you for your cooperation.
I will be watching carefully to this phenomenon .

Thank U.
