### ISSUE TITLE
use onclick of an element to jump on next page

### ISSUE THREAD

**Issue by Kunal912** [puppeteer/puppeteer#3689]
Hi Support,

I am using puppeteer for scraping website.The problem i am having with Page.evaluate function.It is not working in my application.Apart from evaluate function i tried to use onclick attribute of <a> tag to jump onto next page.
Note : I can't use id and classname since it is common/dynamically generated for all elements and the url does not change at all so no unique attribute, the only attribute left is "onclick"
headerDataTable[i].attribs.onclick

Page.click() for onclick attribute is also not working
```js
page.content().then(function (pageData) {
var headerDataTable = $('.commandLink_TITLE-BLUE', pageData);
console.log(headerDataTable);
for (let index = 0; index < 1; index++) {
	page.click(headerDataTable[i].attribs.onclick).then(function 
	 (content) {
		console.log(content);
		var filePath = "screenshot/" + 'screenshot_2' + index +'.jpg';
		page.screenshot({ path: filePath, type: 'jpeg', quality: 
		   80,fullPage: false }).then(function () {
			console.log('Image saved');
			page.content().then(function (newDtata) {
				console.log(newDtata)
			})
		})
	})
```

**Comment by aslushnikov** [comment]
Hey @Kunal912,

When you say that something's not working, it's important for us to know what exactly is not working. Specifically, we need a script that we can run locally that reproduces the wrong behavior - this way we can see what's going on, determine if there's a problem on Puppeteer/Chromium side and fix it.

Please, re-file with details on what's going wrong and proper reproduction steps.

-- Your Support.
