### ISSUE TITLE
not a valid query Selector in page.click()

### ISSUE THREAD

**Issue by Kunal912** [puppeteer/puppeteer#3690]
Hi Support,

I am trying to pass id on Page.click.But it keep saying "not a valid query Selector"
The same id is working in case of page.evaluate as i am using document.getElementbyId in it.
My id is of type
"contentForm:j_idt1690:j_id25:j_id30_commandLink-HIDDEN-BUTTON"

Please help me out.

Thanks

**Comment by vsemozhetbyt** [comment]
Try this id selector: `'*[id="contentForm:j_idt1690:j_id25:j_id30_commandLink-HIDDEN-BUTTON"]'`.

**Comment by Anders3510** [comment]
`page.click()` utilizes a full CSS selector, unlike `document.getElementById()`. have you tried simply adding # to the beginning of the selector string?
It is also possible you would need to escape the : characters in your selector string, as it might be thinking that ":js_idt1690..etc." is referring to a pseudo-class, such as `:hover`.
