### ISSUE TITLE
waitForSelector detecting invisible element

### ISSUE THREAD

**Issue by thamerla** [puppeteer/puppeteer#3696]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11
* Platform / OS version: openSUSE on Windows
* URLs (if applicable): -
* Node.js version: 10.14

**What steps will reproduce the problem?**

So the following button is marked as visible even with visible flag:
![button](https://user-images.githubusercontent.com/18537226/50263574-be4cb300-0416-11e9-8beb-5e5bde07b910.jpg)

Left one, join game. That's the one I want to click.

**What is the expected result?**

Button is marked as invisible and error is thrown.

**What happens instead?**

Button is marked as visible and script proceeds.

**Comment by thamerla** [comment]
[button.log](https://github.com/GoogleChrome/puppeteer/files/2697450/button.log)
here's property list

**Comment by ChristianDavis** [comment]
Can you provide the puppeteer code?

**Comment by thamerla** [comment]
@ChristianDavis site author put custom disabled class in place so I used waitForFunction to workaround this.
