### ISSUE TITLE
set a limit on pages number per browser

### ISSUE THREAD

**Issue by Minyar2004** [puppeteer/puppeteer#3697]
Hi, 

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Centos 7
* URLs (if applicable):
* Node.js version: v10.14.2

Is there a way to en n pages in a browser and limit the page number by a maxNbrePage parameter.

I have a long list of url to open, and I would like to open them but with maximum of 3 pages at the same time. and repace finished or loaded page by a new page in the list.

I tested with this code, it works, but without a limit on the pages number at time.

```
'use strict';

const puppeteer = require('puppeteer');

async function processPage(browser, url) {
	console.log("processPage start:", url);
	const page = await browser.newPage();
    const response = await page.goto(url, {
                timeout: 3000000
            });
	await page.close();
	console.log("processPage end:", url);
	return {page:response};
}

(async function main() {
	
	
  try {
    const browser = await puppeteer.launch({
		headless: true,
		args: ['--no-sandbox'],
		userDataDir: `${__dirname}/profile-dir`
    });
	
	var requests = ['http://example.org/', 'https://www.example.com/', 'http://www.example.com/', 'http://www.example.org/','http://www.example.org/', 'http://www.example.com/', 'http://www.example.com/', 'http://www.example.org/'];	
	
	var response_promises = [];
	
	requests.forEach(function(request) {
		response_promises.push(processPage(browser, request));
	});
	
	var responses = await Promise.all(response_promises);
	
    await browser.close();

  } catch (err) {
    console.error(err);
  }
})();
```
Thanks

**Comment by zebulonzh** [comment]
Try a queue filled with target urls, then make n promisees as workers which just get one url from the queue once and do something about it and repeat doing this stuff once and once again until the queue is empty. The symbol n means the count of pages which you wanna keep limited.

**Comment by markosii** [comment]
I have the same basic need

Can you give a code allowing to do this?

**Comment by Minyar2004** [comment]
I used the p-limit module to resolve this :)

**Comment by saqib-ahmed** [comment]
If it helps anyone, you can use the example from the accepted answer in the following StackOverflow post to limit the number of pages per browser:
https://stackoverflow.com/questions/50557418/puppeteer-opening-chrome-instance-for-each-file-at-once

**Comment by VirtumartOz** [comment]
'use strict';

const puppeteer = require('puppeteer');

async function processPage(browser, url) {
	console.log("processPage start:", url);
	const page = await browser.newPage();
    const response = await page.goto(url, {
                timeout: 3000000
            });
	await page.close();
	console.log("processPage end:", url);
	return {page:response};
}

(async function main() {
	
	
  try {
    const browser = await puppeteer.launch({
		headless: true,
		args: ['--no-sandbox'],
		userDataDir: `${__dirname}/profile-dir`
    });
	
	var requests = ['http://example.org/', 'https://www.example.com/', 'http://www.example.com/', 'http://www.example.org/','http://www.example.org/', 'http://www.example.com/', 'http://www.example.com/', 'http://www.example.org/'];	
	
	var response_promises = [];
	for(let i = 0; i < requests.length; i ++){
	      if( i > 0 && (i % 3 == 0 || (i == requests.length - 1)) {
            var responses = await Promise.all(response_promises);
            responses_promises = [];
         }
         response_promises.push(processPage(browser, requests[i]));
	}
    await Promise.all(response_promises); // for the last unprocessed item
    await browser.close();

  } catch (err) {
    console.error(err);
  }
})();

**Comment by algo7** [comment]
@VirtumartOz Thanks. This helped me a lot.
