### ISSUE TITLE
Error: Failed to connect to chrome! ['--no-sandbox'] does not fix my issue

### ISSUE THREAD

**Issue by icarusmiles** [puppeteer/puppeteer#370]
I am getting the same error as issue #290, however `{args: ['--no-sandbox']}` does nothing to fix my issue.

Error:
```
(node:17264) UnhandledPromiseRejectionWarning: Unhandled promise rejection 
(rejection id: 1): Error: Failed to connect to chrome!
(node:17264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've installed the dependency list, from issue #290. I've done many re-installations. I also upgraded to the latest version of Node. No luck.

**Operating System** 
Ubuntu ->  _Linux valor 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux_

**Node Version**  
v8.4.0 (Also tried 7.10)

**User**
Not running as root, being ran as a sudo user.

**Comment by icarusmiles** [comment]
Okay, so I figured it out.

I had to change the ownership from my root to my local account. After it was able to be ran without `sudo`, however if you do use `sudo` the `--no-sandbox` does fix it (assuming you have ownership).

Is this good practice?

**Comment by joelgriffith** [comment]
https://www.google.com/googlebooks/chrome/med_26.html

**Comment by Garbee** [comment]
Running as root is not a good practice. You should never run as root unless you need to.

**Comment by kirillgroshkov** [comment]
Unless in Docker, where running from root is ok and default

**Comment by Garbee** [comment]
Docker would fall under the "need to" situation, yes.
