### ISSUE TITLE
document.hidden 在无头模式下无效

### ISSUE THREAD

**Issue by SilurianYang** [puppeteer/puppeteer#3700]
* Puppeteer版本 :   1.8.0
* 平台/操作系统版本 :     win7
* Node.js版本 :    9.11.1

重现问题的代码:_

        let pages = await browser.pages();
        for (let i = 0; i < pages.length; i++) {
            let body = await pages[i].$$('body');
            let status = true;
            if (body != null) {
                pages[i].on('console', message => console.log(message.text()));
                status = await pages[i].evaluate(() => {
                    console.log(document.hidden)
                    return document.hidden
                }).catch((err) => {
                    console.log(err)
                })
            }
            if (status == false) {
                pages[i].setDefaultNavigationTimeout(15000);
                return pages[i]

            }
        }

我在使用puppeteer时，想根据可视tab来获取page对象，发现在无头浏览器下document.hidden 均返回false   非无头浏览器下正常使用，这个怎么破？获取是说有没有什么好的方法可以获取到可视tab的page对象的？

**Comment by aslushnikov** [comment]
Please re-file in english; this way this will be searchable on our bugtracker and will benefit community.
