### ISSUE TITLE
can't install puppeteer issue

### ISSUE THREAD

**Issue by yokaso** [puppeteer/puppeteer#3705]
i am trying to install puppeteer, but without success.
i use windows 7
i created an empty directory 'pupeter' and type this command "npm i puppeteer" and got this error message:

D:\pupeter>npm i puppeteer
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "puppeteer" under a package
npm ERR! also called "puppeteer". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-alg
orithm>

**Comment by bWhirring** [comment]
your package.json name shouldn't be equal to you dependencies

moh <notifications@github.com> 于2018年12月23日周日 下午11:03写道：

**Comment by winddddd** [comment]
rename the name of package.json
