### ISSUE TITLE
I am having a problem

### ISSUE THREAD

**Issue by mituso89** [puppeteer/puppeteer#3706]
I am installing puppeteer on linux.
sh: node: command not found
npm WARN crawlpuppeteerv4@1.0.0 No description
npm WARN crawlpuppeteerv4@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! puppeteer@1.6.2 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the puppeteer@1.6.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-24T02_29_59_358Z-debug.log
[root@ip-172-31-43-27 crawler_costco]# node -v
v8.11.3
[root@ip-172-31-43-27 crawler_costco]#

Please help

**Comment by storenth** [comment]
Provide any additional info based on what command do you use to install puppeteer? What OS build?
Since I have Ubuntu 18.04LT I successfully install Puppeteer with:
```
apt update
apt upgrade
apt install npm
npm install npm -g
npm install -g puppeteer
```

**Comment by mituso89** [comment]
Thank you very much!
