### ISSUE TITLE
How to use puppeteer with nw application?

### ISSUE THREAD

**Issue by ItzhakIsraeli** [puppeteer/puppeteer#3710]
I'm try to do testing with puppeteer in NW(node webkit) application.
and i need to get page to use it in puppeteer.
When i try to use with puppeteer 1.4 version and chromium 71:
```
const puppeteer = require('puppeteer');

(async () => { 
	const browser = await puppeteer.launch({
		headless:false,
		executablePath:"my\\folder\\nw.exe",
		ignoreDefaultArgs:true
});
	
const pages = await browser.pages();
console.log(pages);
```
**The appliaction launch and the result is: [] - empty array.**

But when I'm use in  puppeteer 1.9 version and chromium 71:
**the launch never stop and not returning nothing !**

So how can I use in puppeteer with NW app???

**Comment by ItzhakIsraeli** [comment]
@google-admin 
@googlebot 
@aslushnikov

**Comment by aslushnikov** [comment]
@WinSpeiNe I'm not familiar with NW and it's hard to say how different they are from Chromium. I'd try filing this over to their repository - they're "downstream" wrt Puppeteer, so they should have a better perspective on how to drive testing and if they can use Puppeteer / CDP.

I'd appreciate if you post a link to the downstream issue if/when you file it.
