### ISSUE TITLE
Multiple elements with same class name

### ISSUE THREAD

**Issue by Kunal912** [puppeteer/puppeteer#3713]
Hi Support,

I need to pick all 3 onclick events of these elements and loop through them and get the response / html which it returns using puppeteer. It does AJAX.

All these have same class name but different onclick event data.

**Below is the page html-**

```
<a type="link" href="#" class="commandLink_TITLE-BLUE" onclick="loadingScreen_Show('contentForm:j_idt1690:j_id77:j_id82');commandLink_ClickHiddenButton(event, 'contentForm:j_idt1690:j_id77:j_id82_commandLink-HIDDEN-BUTTON');">A</a>
<a type="link" href="#" class="commandLink_TITLE-BLUE" onclick="loadingScreen_Show('contentForm:j_idt1691:j_id77:j_id81');commandLink_ClickHiddenButton(event, 'contentForm:j_idt1690:j_id77:j_id82_commandLink-HIDDEN-BUTTON');">B</a>
<a type="link" href="#" class="commandLink_TITLE-BLUE" onclick="loadingScreen_Show('contentForm:j_idt1692:j_id77:j_id89');commandLink_ClickHiddenButton(event, 'contentForm:j_idt1690:j_id77:j_id82_commandLink-HIDDEN-BUTTON');">C</a> 
```
Please help me out.

Thanks

**Comment by aslushnikov** [comment]
@Kunal912 clicking all of them is quite easy:

```js
const handles = await page.$$('.commandLink_TITLE-BLUE');
for (const handle of handles)
  await handle.click();
```

You should also install a listener on [`'response'`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-event-response) event to track the responses for these AJAX requests:

```js
page.on('response', response => console.log(await response.text()));
```

Hope this helps

**Comment by parmonov98** [comment]
> ```js
> page.on('response', response => console.log(await response.text()));
> ```

`page.on('response', async (response) => console.log(await response.text()));`
You missed async keyword.
