### ISSUE TITLE
Puppeteer for Firefox doesn't return a Response

### ISSUE THREAD

**Issue by saschanaz** [puppeteer/puppeteer#3716]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.4.2 for Firefox
* Platform / OS version: Windows 10
* URLs (if applicable): https://example.com
* Node.js version: 11.6.0

**What steps will reproduce the problem?**

```js
const puppeteer = require("puppeteer-firefox");
const browser = await puppeteer.launch();
const page = await browser.newPage();
const response = await page.goto('https://example.com');
console.log(response.ok());
```

**What is the expected result?** `true`

**What happens instead?** `TypeError: Cannot read property 'ok' of undefined`

**Comment by aslushnikov** [comment]
@saschanaz yeah Puppeteer-Firefox doesn't implement network inspection yet; we state this in its [API Status](https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox#api-status).

Our main goal now is to integrate it into our codebase and feature-complete the API.

I'll close this for now; this will be addressed eventually as the project matures. We'll have an announcement
