### ISSUE TITLE
Click event is not firing

### ISSUE THREAD

**Issue by longnull** [puppeteer/puppeteer#372]
Sorry for my bad English.
I have a problem with authentication on... pornhub. 🙂
The login page have an auth form with #submit button, the button have a click event which makes an AJAX request to /front/authenticate, but the event is not firing and the browser navigates to /login?[params] (the form does not have "action" and "method" attributes).
The submit button works normally If I click it manually (in non-headless mode).
Also, I can't access internal variables (for example, $j or loginAjax() (script below)) inside page.evaluate().

My script:
```javascript
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({
    headless: false
});
const page = await browser.newPage();
await page.setViewport({width: 1024, height: 768});
await page.goto('https://www.pornhub.com/login');
await page.evaluate(() => {
    document.getElementById('username').value = 'user';
    document.getElementById('password').value = 'pass';
    document.getElementById('submit').click();
});
// does not help
// await page.click('#submit');
})();
```
Internal auth script:
```javascript
function loginAjax() {
    return $j.ajax({
        type: "POST",
        url: "/front/authenticate",
        cache: !1,
        dataType: "json",
        data: $j(".js-loginForm").serialize(),
        success: function(n) {
            "0" == n.premium_redirect_cookie ? n.redirect ? document.location.assign(n.redirect) : $j(".signinError").show().text(n.message) : $j.ajax({
                url: premiumRedirectCookieURL,
                cache: !1,
                crossDomain: !0,
                xhrFields: {
                    withCredentials: !0
                },
                success: function() {
                    n.redirect ? document.location.assign(n.redirect) : $j(".signinError").show().text(n.message)
                }
            })
        }
    }), !1
}
head.ready(document, function() {
    var n = !1;
    $j(".js-loginSubmit").on("click", function(n) {
        n.preventDefault(), loginAjax()
    }), $j("input.js-signinUsername, input.js-signinPassword").on("keydown", function(i) {
        n || (13 == i.which && loginAjax(), n = !0)
    }), $j("input.js-signinUsername, input.js-signinPassword").on("keyup", function(i) {
        n && (n = !1)
    })
});
```

**Comment by JoelEinbinder** [comment]
It sounds like not all of the JavaScript is done loading by the time you try to click the button.

**Comment by aslushnikov** [comment]
The following works for me. Note the 'networkidle' argument for `page.goto`.
Also, the delay in typing is just for the ease of debugging.

```js
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch({
    headless: false
});
const page = await browser.newPage();
await page.setViewport({width: 1024, height: 768});
await page.goto('https://www.pornhub.com/login', {waitUntil: 'networkidle'});
await page.focus('#username');
await page.type('user', {delay: 100});
await page.focus('#password');
await page.type('pass', {delay: 100});
await page.click('#submit');
})();
```

**Comment by longnull** [comment]
@JoelEinbinder & @aslushnikov thanks, guys! Now it works. 👍

**Comment by longnull** [comment]
It usually works, but sometimes it does not.😕
Is there another way to know that the scripts are 100% loaded and not rely on setTimeout?🤔

Tested with this script and get 0-3 "Bad".
```javascript
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch();
const page = await browser.newPage();
for(let i = 1; i <= 20; i++) {
    await page.goto('https://www.pornhub.com/login', {waitUntil: 'networkidle'});
    await page.evaluate(() => {
        document.getElementById('username').value = 'user';
        document.getElementById('password').value = 'pass';
    });
    await page.click('#submit');
    await page.waitForNavigation({waitUntil: 'networkidle'});
    let url = page.url();
    if (url.indexOf('loginPage') == -1) {
        console.log(i + ' : Good');
    } else {
        console.log(i + ' : Bad');
    }
}
browser.close();
})();
```

**Comment by rohmanhm** [comment]
I've got user and pass in the same field.
instead of getting user on field username and pass on field password.
I got userpass on field username and empty text on field password.
```javascript
await page.focus('#username');
await page.type('user', {delay: 100});
await page.focus('#password');
await page.type('pass', {delay: 100});
await page.click('#submit');
```

**Comment by vibou** [comment]
I had similar issue where click was working half the time. I figured out that moving first the mouse then trigger the click is 100% working: 
```javascript
const mouse = page.mouse
await mouse.move(parseFloat(x), parseFloat(y));
await mouse.click(parseFloat(x), parseFloat(y), {
            "button": "left",
            "clickCount": 1,
            "delay": 0
        });
```

**Comment by longnull** [comment]
My problem is that the scripts do not load on time and onclick event is not firing. :/

**Comment by androidfanatic** [comment]
Each website is built uniquely. Use inspector and dev tools!  
In this case, you may use `page.waitFor` to wait for js-loginSubmit class.

    await page.goto('https://www.pornhub.com/login', { waitUntil: 'networkidle' });
    await page.focus("#username");
    await page.type('user', { delay: 300 * Math.random() });
    await page.focus("#password");
    await page.type('pass', { delay: 300 * Math.random() });
    await page.waitFor(".js-loginSubmit");
    await page.click(".js-loginSubmit");

Note: I do not have a valid user/pass to test against.

**Comment by yankouskia** [comment]
Have the same issue. Scripts are loaded.

**Comment by aslushnikov** [comment]
@longnull it looks like pornhub doesn't initialize immediately after loading all scripts. There's no general way to solve this problem, you'll need to either figure how the website works or throw in a bunch of timeouts.

**Comment by bitliner** [comment]
I've found another really weird case, on 0.13.0:

The following does not work:

```
for (let element of elements) {
      await element.click()
    }
```

The following works: 

```
for (let element of elements) {
      await page.evaluate((el) => {
        return el.click()
      }, element);
    }
```

**Comment by JoelEinbinder** [comment]
@bitliner Puppeteer's `.click` is very different from `HTMLElement.click`. The latter just fakes a "click" event. We tell Chrome that the mouse moved over the center of the element and was pressed, which triggers hover effects, clicks deep into the element, will be blocked by overlay elements, etc.

If Puppeteer's click doesn't work for you, there is a very good chance that clicking is not working on your site. Make sure the element is actually onscreen and clickable when you are trying to click it.

**Comment by bitliner** [comment]
@JoelEinbinder with onscreen do you mean that I should scroll to it in order to make it visible in the viewport?

**Comment by bitliner** [comment]
@JoelEinbinder I found already the second website for which 

```
await page.evaluate((el) => {
        return el.click()
      }, element);
```

works 

while `element.click()` does not.

To be sure I understood your comment, is `element.click()` useful only for triggering the mouse-hover event and move the mouse on the element?

**Comment by JoelEinbinder** [comment]
Consider this website: https://jsfiddle.net/3zes4tkp/

If you run HTMLElement.click, on the page, you can trigger on the onclick listener. But the div isn't actually clickable, because it is being covered by something else. Puppeteer's click will fail to trigger the onclick. This is intended, because that is what would happen if the user tried to click the element.

**Comment by radhouen** [comment]
```
const puppeteer = require('puppeteer');
    (async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    for(let i = 1; i <= 20; i++) {
    await page.goto('https://www.pornhub.com/login', {waitUntil: 'networkidle'});
    await page.evaluate(() => {
    await page.$('#username').then(async (user) => {
    user.type('user', {delay: 100}); //type slower like user
    [}await](url) page.$('#password').then(async (password) => {
    password.type('password', {delay: 100}); //type slower like user
    } });
    await page.click('#submit');
    await page.waitForNavigation({waitUntil: 'networkidle'});
    let url = page.url();
    if (url.indexOf('loginPage') == -1) {
    console.log(i + ' : Good');
    } else {
    console.log(i + ' : Bad');
    }
    }
    browser.close();
    })();

```

**Comment by lstellway** [comment]
The documentation for [`page.goto`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options) specifies four options for `waitUntil`. I had to wait for all four, like so:
```
const puppeteer = require('puppeteer');

(async() => {
    puppeteer.launch().then(async browser => {
        const page = await browser.newPage();
        await page.goto('https://example.com/login', {
            waitUntil: ['load','domcontentloaded','networkidle0','networkidle2']
        });
        // now try here ...
        // await page.focus('#username');
        // await page.type('user');
        // await page.focus('#password');
        // await page.type('pass');
        // await page.click('#submit');
    });
});
```

**Comment by garygreen** [comment]
In my case it was because the button I was trying to run click on wasn't added to the DOM. Seems it needs to be added to the DOM e.g. via `appendChild` otherwise the submit event doesn't fire

**Comment by allenhwkim** [comment]
`el.click()` did not work.
I use the following for my click and click text functions
Hope this is useful who has issue that I had, which click not happening 
```
  async click(selector, within='') {
    const cssSelector = within ? `${within} ${selector}`: selector;
    const element = await page.waitForSelector(cssSelector, {visible: true});
    return await page.evaluate(el => el.click(), element);  // <---- this
  }

  async clickText(text, selector) {
    const element = await page.waitForFunction(iSeeText, {}, text, selector);
    return await page.evaluate(el => el.click(), element); // <---- this
  }
```

**Comment by osmenia** [comment]
Can somebody tell me how to solve a click problem. 
await page.click("#yw1 > li.next > a"); 
does not work. 

Tnx

async function scrapeListings(page) {
  await page.goto(
    "https://www.podbean.com/podcast-detail/nth28-2ef41/99%25-Invisible-Podcast",
    { waitUntil: "networkidle2" }
  );

  const html = await page.content();
  const $ = cheerio.load(html);

  let moreResults = true;

  while (moreResults) {
    console.log(moreResults);
    try {
      await sleep(1000);
      await page.click("#yw1 > li.next > a");
    } catch (error) {
      moreResults = false;
    }
  }
}

async function sleep(miliseconds) {
  return new Promise(resolve => setTimeout(resolve, miliseconds));
}

**Comment by ezy** [comment]
from https://stackoverflow.com/questions/56226990/puppeteers-page-click-is-working-on-some-links-but-not-others/56227068

Try using `ignoreHTTPSErrors` option set to true:

`puppeteer.launch({ ignoreHTTPSErrors: true, headless: false })`

**Comment by Spixmaster** [comment]
There is another reason why the click event may not effect the website.
Take the **send button** of **web.telegram.org** for **example**. The button listens for the event "mousedown".
I assume that **"onclick"** and **"onmousedown"** are different so that clicking will only trigger the event "onclick". This made me headaches for two days. Do it better.

```js
const send = document.querySelector("button[class='btn btn-md im_submit im_submit_send']");
//Does not work.
send.click()
//Works!
const ev = new Event("mousedown");
send.dispatchEvent(ev);
```
