### ISSUE TITLE
Cannot return blob or arrayBuffer from page.evaluate

### ISSUE THREAD

**Issue by sbmthakur** [puppeteer/puppeteer#3722]
I am not sure if this is an issue with Puppeteer but I looked around and could not find a proper answer to my question. So I am asking it here.

* Puppeteer version: 1.3.0
* Platform / OS version: Windows 10
* Node.js version: 8.9.4

I'm trying to download a PDF by making a POST request(using fetch). The following is the code:
```
const puppeteer = require('puppeteer');
const fse = require('fs-extra');

(async () => {
	const browser = await puppeteer.launch({ headless: false, devtools: true });
	const page = await browser.newPage();

	await page.goto('http://jeffe.cs.illinois.edu/');
    // This is just an example. Actual PDFs can't be accessed with a URL or opened in the PDF viewer.
	let url = 'http://jeffe.cs.illinois.edu/teaching/algorithms/book/!!-preface.pdf';
     
	console.log("Initiating download...");
	const pdfData = await getPdf();
	console.log("PDF data: ", pdfData);
	fse.writeFileSync('./file.pdf', pdfData);
	async function getPdf() {
		return page.evaluate(url => {
			return window.fetch(url)
				.then(response => response.blob())
				.then(data => {
					debugger;  // Here data is Blob(204711) {size: 204711, type: "application/pdf"}
					return data;
				})
				.catch(err => {
					debugger;
				});
		}, url);
	}
})();

```

The `pdfData` in this case is `{}`. Even if I use `response.arrayBuffer` instead of `response.blob`, `pdfData` is still `{}`. To circumvent this issue, I am converting the blob to a string before returning it from page.evaluate in the following way:
```
	async function getPdf() {
		return page.evaluate(url => {
			return new Promise(async resolve => {
				const reader = new FileReader();
				const response = await window.fetch(url)
				const data = await response.blob();
				debugger;
				reader.readAsBinaryString(data);
				reader.onload = () => resolve(reader.result);
				reader.onerror = () => reject('Error occurred while reading binary string');
			});
		}, url);
	}
    const pdfString = await getPdf();
    const pdfData = Buffer.from(pdfString, 'binary');
	fse.writeFileSync('./file.pdf', pdfData);
```
Although I've a solution to my problem, I am unable to comprehend why we can't return a `Blob` from Chromium to Node's context. Is this an issue with Blob's serializability or it has something to do with Chrome dev tools protocol's handling of Blobs?

**Comment by aslushnikov** [comment]
> Is this an issue with Blob's serializability or it has something to do with Chrome dev tools protocol's handling of Blobs?

@sbmthakur Exactly; this happens because there's only a set of types that DevTools protocol can reliably transfer over the wire; blobs and array buffers are not the ones. Your solution is the way to go.

**Comment by cancerberoSgx** [comment]
Just in case other's have problems with TextEncoder or just want to use Buffer in both sides, checkout https://github.com/GoogleChrome/puppeteer/issues/2427#issuecomment-536002538

**Comment by cancerberoSgx** [comment]
> I am unable to comprehend why we can't return a `Blob` from Chromium to Node's context. Is this an issue with Blob's serializability or it has something to do with Chrome dev tools protocol's handling of Blobs?

I don't think Blob would be the correct type for passing binary data since they are not supported in Node.js (only supported in DOM). But I agree that some mechanism to pass binary data that doesn't imply encoding to supported types (aka string) would be necessary and is IMO a common use case. If not possible to share the memory, then at least some API to copy an ArrayBuffer / View as a whole (and not byte per byte) should alleviate this a lot. My two cents. thanks

**Comment by eezdev** [comment]
@sbmthakur thanks for the workaround ! I spend days looking how to download files in headless... your post made my day and finally i understand why response.blob() was always empty... 

@aslushnikov this can be considered as a solution to download files issue in headless mode, it deserves to be spread over the ones who are waiting for the download feature in headless mode

**Comment by diepthanh94** [comment]
Puppeteer return respone file from page.evalute():

```
const response = await page.evaluate(() => new Promise((resolve, reject) => {
// convert to .doc file
          const html = "<html xmlns:o='urn:schemas-microsoft-com: office:office"
            + " xmlns:w='urn:schemas-microsoft-com: office:word' xmlns='http://www.w3.org/TR/REC-html40'>"
            + "<head><meta charset='utf-8'><title>Export HTML To Doc</title></head><style></style><div id="content">xxxxxxxxxxxxxxxxxxxxxx</div><body></body></html>";
       
          const blob = new Blob(['\ufeff', html], {
            type: 'application/msword'
          });

          const reader = new FileReader();
          reader.readAsBinaryString(blob);
          reader.onload = () => resolve(reader.result);
          reader.onerror = () => reject('Error occurred while reading binary string');
        }));

        const file = Buffer.from(response , 'binary');
        return file;
```

**Comment by alexandru-gaidei** [comment]
@sbmthakur, thank you!

**Comment by danroot** [comment]
@conma 's answer helped me.  Previous guidance was to use setDownloadBehavior to download files, but that has quit working in newer puppeteer.  I took @conma 's answer and refactored to a more general solution:

  ```
page.downloadFile = async function(url, destinationPath) {
    var binaryString =  await page.evaluate(async (url) =>
    {
        var response = await fetch(url, { method: 'GET', credentials: 'include'});
        var blob = await response.blob();
        var result = new Promise((resolve, reject) => {
          var reader = new FileReader();          
          reader.onloadend = () => resolve(reader.result);
          reader.onerror = reject;
          reader.readAsBinaryString(blob);
        });
        return result;
    },url);
    var fileBlob =  Buffer.from(binaryString , 'binary');
    await fsPromises.writeFile(destinationPath, fileBlob);
  };
```

Usage:

```
await page.downloadFile('http://jeffe.cs.illinois.edu/teaching/algorithms/book/!!-preface.pdf','./some/path/preface.pdf')
```

The main downsides I see are:

* translating to string then back to file can't be ideal, but as best I can tell is only way to marshal from page context to node context.
* you have to know the url.  In some cases where the page generates a url on the fly on a button click, this may be difficult to obtain.
* you have to know the file name.  In some cases where the server generates the filename, this may be difficult.

But it works for my purposes and I hope it helps others.
