### ISSUE TITLE
page.waitForFunction fails because of whitespace

### ISSUE THREAD

**Issue by fringd** [puppeteer/puppeteer#3723]
### Steps to reproduce
```
await page.waitForFunction(`
  (() => true)()`);
```
never returns, but

```
await page.waitForFunction(`(() => true)()`);
```
does. I expect them both to return immediately.

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: MacOS
* URLs (if applicable):
* Node.js version: 8.9.1

**Comment by vsemozhetbyt** [comment]
It seems this is due to automatic semicolon insertion (i.e. `undefined` is returned) in this fragment:

https://github.com/GoogleChrome/puppeteer/blob/3d82465f667f0585ae8cb3dbb45ebe76bbc80ec7/lib/FrameManager.js#L980

cc @aslushnikov

**Comment by fringd** [comment]
this behavior is different than page.evaluate, which was rather suprising.

**Comment by fringd** [comment]
Maybe just adding parentheses would fix it? like this:
``` 
this._predicateBody = helper.isString(predicateBody) ? 'return (' + predicateBody + ')': 'return (' + predicateBody + ')(...args)'; 
```

**Comment by fringd** [comment]
sorry didn't mean to close.
