### ISSUE TITLE
Dialog triggered by 'beforeunload' does not return correct message

### ISSUE THREAD

**Issue by cuki** [puppeteer/puppeteer#3725]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.10.0
* Platform / OS version: macOS High Sierra 10.13.6
* Node.js version: 10.14.2

**What steps will reproduce the problem?**

1. Open a page with Puppeteer which has either one of the following event listeners
```js
window.addEventListener('beforeunload', function(event) {
  event.returnValue = 'Are you sure you want to leave?';
});
```
```js
window.addEventListener('beforeunload', function(event) {
  return 'Are you sure you want to leave?';
});
```

2. Attach an event listener for `'dialog'`
```js
page.on('dialog', async dialog => {
  console.log(dialog.message()); // outputs: ''
  await dialog.dismiss();
  await browser.close();
});
```

3. Close page to trigger dialog
```js
await page.close({ runBeforeUnload: true });
```

**What is the expected result?**
[`dialog.message()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#dialogmessage) should be the specified return value in `beforeunload` event handler.

**What happens instead?**
It always returns an empty string (obtained from `event.message`), it seems that `Page` does not respect `event.returnValue` when [constructing new `Dialog` instance](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/lib/Page.js#L592).

**Comment by aslushnikov** [comment]
@cuki I don't think Chromium itself respects the value; at least I don't see chromium's beforeunload dialog to contain the text from `returnValue`.

Looks like Puppeteer works as expected here.

**Comment by cuki** [comment]
@aslushnikov Did some research and it turns out that event passed by `Page.javascriptDialogOpening` does not respect the `returnValue`.
As it always returns an empty string by looking at the [source for 72.0.3618.0](https://chromium.googlesource.com/chromium/src/+/72.0.3618.0/content/browser/devtools/protocol/page_handler.cc#338):
```c
void PageHandler::DidRunBeforeUnloadConfirm(const GURL& url,
                                            bool has_non_devtools_handlers,
                                            JavaScriptDialogCallback callback) {
  if (!enabled_)
    return;
  DCHECK(pending_dialog_.is_null());
  pending_dialog_ = std::move(callback);
  frontend_->JavascriptDialogOpening(url.spec(), std::string(), // <-  always empty string
                                     Page::DialogTypeEnum::Beforeunload,
                                     has_non_devtools_handlers, std::string());
}
```

So yes, Puppeteer is working as expected, Chromium unfortunately is not.

Thanks for looking into this!

**Comment by vrqq** [comment]
The problem is related to chrome, see also: [chrome-51-deprecations](https://developers.google.com/web/updates/2016/04/chrome-51-deprecations?hl=en#remove_custom_messages_in_onbeforeunload_dialogs)

The chrome remove the custom message on beforeunload triggered by javascript, but IE support it.
Reference: [https://www.w3schools.com/jsref/event_onbeforeunload.asp](https://www.w3schools.com/jsref/event_onbeforeunload.asp)
