### ISSUE TITLE
Memory heap : best use of page "newPage" and urls "goto"

### ISSUE THREAD

**Issue by Minyar2004** [puppeteer/puppeteer#3733]
**Tell us about your environment:**

* Puppeteer version: puppeteer@1.11.0
* Platform / OS version: Centos 7
* URLs (if applicable): 500000 urls crawled one by one
* Node.js version: v10.14.2

I'm using puppeteer to crawl web pages.
Should I create only one page to go to all urls (url by url)?
or should I create a new page for each url and close it once the page is loaded (always url by url, one after the other).

The problem with the first solution (creating only one page) is the high memory use. 
The memory used by the page is constantly increasing. This error is :
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`
This occurs when 1.5 GB of memory is reached.

The problem with the second solution (creation one page for each url) could be the creation/closing of 500000 pages (one page per url). Is it optimized,? Is it the the best practice?

Thanks

**Comment by aslushnikov** [comment]
> Should I create only one page to go to all urls (url by url)?

@Devhercule the way I'd do this is creating a pool of [browser contexts](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-class-browsercontext) with a page inside. Once the URL is crawled, I'd close the browser context and create another one. I'd limit the total number of simultaneously opened browser contexts to some reasonable number, defined by your host environment.

> The problem with the first solution (creating only one page) is the high memory use.
The memory used by the page is constantly increasing. 

This is interesting. I'm not sure why js heap keeps growing when navigating to separate URLs; I'd ask on chromium-dev google group. Closing and re-creating the page should re-create renderer process, so this won't be a problem.

> The problem with the second solution (creation one page for each url) could be the creation/closing of 500000 pages (one page per url). Is it optimized,? Is it the the best practice?

Having a lot of pages simultaneously will be very expensive; it should be fine if the amount of simultaneously-opened pages is constrained with something.

Hope this helps!

**Comment by Minyar2004** [comment]
@aslushnikov thank you for your reply

Ok I will test the "browser contexts". But how can limit the total number of simultaneously opened browser contexts to some reasonable number?

just to clarify a detail, in the second solution, I opena new page for each url, but not simultaneously, I open a page, I goto the url, I close it and after I open another page.

Here is a consumed memory size comparison between opening only one page for all urls (RED) and opening a new page for each url (closing a page and then opening another one) (BLUE).

![memory](https://user-images.githubusercontent.com/29538843/50959434-3e6cb280-14c3-11e9-80ff-d94e585ffd36.png)


PS: In both cases, I have only one open page at a time.

**Comment by aslushnikov** [comment]
> But how can limit the total number of simultaneously opened browser contexts to some reasonable number?

@Devhercule You should use [pool](https://en.wikipedia.org/wiki/Pool_(computer_science)) for this.

> Here is a consumed memory size comparison between opening only one page for all urls (RED) and opening a new page for each url (closing a page and then opening another one) (BLUE).

This chart is peculiar. Can you please share your observation on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev)? This might be a nasty chromium bug.

**Comment by Minyar2004** [comment]
I'm running in headless mode, ca.n't have chromium-dev

the memory i used in the chart is : process.memoryUsage().rss

**Comment by aslushnikov** [comment]
> I'm running in headless mode, ca.n't have chromium-dev

@Devhercule chromium-dev is covering the development of everything that lives in Chromium source tree; headless is part of it.

**Comment by Minyar2004** [comment]
done!
I misunderstood your request :(
thanks

**Comment by Minyar2004** [comment]
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/qwirZaQ27E4

**Comment by mikeyoon** [comment]
It's been over two years, but I've run into a similar (same?) issue and found a workaround that isn't too tough to implement. The leak seems to happen in the `Browser` object or something related, so disconnecting and reconnecting it worked pretty well in my case. After reconnecting, you will need to reassign your `Page` references.

```
const browser = await puppeteer.launch(/* options */);
const endpoint = browser.wsEndpoint();

while (true) {
  // do your page load, etc
  browser.disconnect();
  browser = await puppeteer.connect({
    browserWSEndpoint: endpoint,
    defaultViewport: null,
  });
  page = (await browser.pages())[0];
}
```

With this, I could reload the url using the same page indefinitely, whereas before it would run out of memory in about 2 days.
