### ISSUE TITLE
Hash symbol breaks pdf output

### ISSUE THREAD

**Issue by markitosgv** [puppeteer/puppeteer#3736]
When you try to print a PDF with some '#' symbol it breaks.

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Centos 7
* URLs (if applicable):
* Node.js version: 8.5

**What steps will reproduce the problem?**

```js
const puppeteer = require('puppeteer');
const fs = require('fs');

let stdinBuffer = fs.readFileSync(0 /* STDIN_FILENO */, 'utf8');
let html = stdinBuffer.toString();

const args = process.argv;
const format = args[2];

(async () => {
    const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    ignoreHTTPSErrors: true
});
const page = await browser.newPage();

await page.goto('data:text/html,' + html, { waitUntil: 'networkidle0' });

let result = '';
if (format === 'pdf') {
    await page.emulateMedia('screen');
    result = await page.pdf({
        format: 'A4',
        printBackground: true
    });
} else {
    result = await page.screenshot({
        path: 1, // STDOUT_FILENO
        type: format,
        quality: 100,
    });
}

process.stdout.write(result);
await browser.close();
})();
```
In puppeteer 1.10 it works OK.

**What is the expected result?**

Entire PDF

**What happens instead?**

PDF breaks on first '#' symbol.

**Comment by aslushnikov** [comment]
@markitosgv so what's your HTML that has a `#` in there? Can you please share the one that reproduces the issue?

**Comment by markitosgv** [comment]
Of course,

This is the html code

```html
        <div class="row">
            <div class="col-8">
                <h1>Invoice</h1>
                <span class="h3 text-muted">#A12345</span>
            </div>
        </div>
```

**Comment by aslushnikov** [comment]
@markitosgv ah, looks like you should use `page.setContent` instead to avoid URL issues

```js
await page.setContent(html, {waitUntil: 'networkidle0'});
```

**Note:** puppeteer v1.11.0 supports awaiting resources using `waitUntil` option, so the dataURL navigation hack is no longer needed.

**Comment by aslushnikov** [comment]
Works for me with `page.setContent`.
