### ISSUE TITLE
puppeter open always a blank page

### ISSUE THREAD

**Issue by multivoltage** [puppeteer/puppeteer#3739]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:       1.11.0
* Platform / OS version:   windows 10
* URLs (if applicable):  
* Node.js version:     8.10.0 / 10.13.0

**What steps will reproduce the problem?**

1. install puppeter with npm
2. use simple code like:
`(async () => {
  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
  const page = await browser.newPage();
  await page.goto('https://www.chromestatus.com', { waitUntil: 'networkidle2' });
  await page.pdf({ path: 'page.pdf', format: 'A4' });

  await browser.close();
})();
`
3. run with node

**What is the expected result?**
Visit url and take a pdf

**What happens instead?**
Open blank page. The scenari is alsways the same. I tried different options with .launch. Everty time chromium will open in blank page and it stay there.
I noticed also that if a run in cmd "chrome --headless ...." the result is the same

**Comment by aslushnikov** [comment]
@multivoltage it looks like you have some issue with your environment. The following works just fine for me:


```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://www.chromestatus.com', { waitUntil: 'networkidle0' });
  await page.pdf({ path: 'page.pdf', format: 'A4' });

  await browser.close();
})();
```

It's hard to say for sure what's wrong with the limited information here. But given that `chrome --headless` doesn't work for you as well, it looks like there's something with the dependencies on your host env?

That's the best I can tell.

**Comment by multivoltage** [comment]
It is possible. I try today again maybe uninstall and install chrome.
