### ISSUE TITLE
show cursor on headless: false

### ISSUE THREAD

**Issue by simone-sanfratello** [puppeteer/puppeteer#374]
Hi,
is there a way to show cursor running puppeteer with `{headless: false}`?

thank you

**Comment by Garbee** [comment]
The cursor is never used. Everything is emulated via well crafted series of javascript events. In order for the cursor to be used, the program would need to take over your actual OS cursor. Which means you can't get other things done while the scripts run.

**Comment by JoelEinbinder** [comment]
In our tests, we use a script to paint where the virtual cursor is. You can use it or write your own. Inject it into the target page.

https://github.com/GoogleChrome/puppeteer/blob/master/test/assets/input/mouse-helper.js
