### ISSUE TITLE
Docs should explain what core methods do

### ISSUE THREAD

**Issue by thamerla** [puppeteer/puppeteer#3745]
Docs should explain what can be expected from core methods like element.click or page.waitForSelector.

Examples:
1) Difference between native element.click() or element.trigger('click') and puppeteer's click
Here's a well-written reverse engineered solution I found: https://stackoverflow.com/a/50032302
2) What does 'visibility' mean in puppeteer's context?
3) Generally when I should use native methods instead of puppeteer's ones.

Just like navigation is explained here in the FAQ section:

> Q: What’s considered a “Navigation”?
> 
> From Puppeteer’s standpoint, “navigation” is anything that changes a page’s URL. Aside from regular navigation where the browser hits the network to fetch a new document from the web server, this includes anchor navigations and History API usage

.

**Comment by aslushnikov** [comment]
> 1. Difference between native element.click() or element.trigger('click') and puppeteer's click

There's a write up on clicking - [Automating Clicks in Chromium](https://medium.com/@aslushnikov/automating-clicks-in-chromium-a50e7f01d3fb)

> 2. What does 'visibility' mean in puppeteer's context?

I believe it's explained in the documentation for [`page.waitForSelector`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagewaitforselectorselector-options)

> 3. Generally when I should use native methods instead of puppeteer's ones.

What's "native" methods? Do you mean WebPlatform ones?
