### ISSUE TITLE
Error: spawn */chrome-linux/chrome EAGAIN on puppeteer launch

### ISSUE THREAD

**Issue by evilbs** [puppeteer/puppeteer#3749]
## Issue description: 
An error occurred in my production environment and then my program exist ^_^, the error stack is as follows:

**Error 1:** 
```javascript
TypeError: input.on is not a function
    at new Interface (readline.js:174:11)
    at Object.createInterface (readline.js:64:10)
    at Promise (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:327:25)
    at Promise (<anonymous>)
    at waitForWSEndpoint (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:326:10)
    at Launcher.launch (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:166:41)
    at module.exports.launch (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Puppeteer.js:36:27)
    at runScript (/users/hacker/fb/mimi/mimi/scripts/index.js:61:37)
    at keepaliveDefaultStratery (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:218:22)
    at joinCore (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:180:20)
    at main (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:117:28)
    at <anonymous>
```

**Error 2：** by process.nextTick 
```javascript
Error: spawn /users/hacker/fb/mimi/mimi/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome EAGAIN
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
## Error analysis:  
1. An EAGAIN error occurred when lunch puppeteer, It will be return and does not execute the following code, such as setting stderr for child_process object (chromeProcess object). [code](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L361)
2. waitForWSEndpoint method will use the stderr property. At this time, The stderr property is undefined but will call stderr.on method, So the error 1 will be occurred. [code](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L329)
3. child_process.js will trigger an error by process.nextTick, Puppeteer does not listening error event because Error 1. So the error didn't catch. Program exist. [code](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L355)

 

## Solution 
Set the listen error event before chromeProcess.stderr. Allowing chromeProcess to handle error events.

```javascript
const exitListenerId = helper.addEventListener(chromeProcess, 'exit', () => onClose());
const errorListenerId = helper.addEventListener(chromeProcess, 'error', error => onClose(error))
const rl = readline.createInterface({ input: chromeProcess.stderr });
let stderr = '';
const listeners = [
  helper.addEventListener(rl, 'line', onLine),
  helper.addEventListener(rl, 'close', () => onClose()),
  exitListenerId,
  errorListenerId
];
const timeoutId = timeout ? setTimeout(onTimeout, timeout) : 0;
```

**Comment by aslushnikov** [comment]
@gzhappysky so do I understand it correctly, that `chromeProcess` is not spawned properly, and thus `stderr` is not defined?

**Comment by evilbs** [comment]
@aslushnikov yes, you are right, that chromeProcess object is created, but stderr of chromeProcess is not defined. thus access chromeProcess.stderr.on method that will throw an error.

**Comment by jpbalarini** [comment]
I am having the same error on macOS

**Comment by evilbs** [comment]
@jpbalarini you can [change source code](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L346) of puppeteer in 'node_modules/puppeteer/lib/Launcher.js' file. 

This is my modified code.
``` javascript 
const exitListenerId = helper.addEventListener(chromeProcess, 'exit', () => onClose());
const errorListenerId = helper.addEventListener(chromeProcess, 'error', error => onClose(error))
const rl = readline.createInterface({ input: chromeProcess.stderr });
let stderr = '';
const listeners = [
  helper.addEventListener(rl, 'line', onLine),
  helper.addEventListener(rl, 'close', () => onClose()),
  exitListenerId,
  errorListenerId
];
const timeoutId = timeout ? setTimeout(onTimeout, timeout) : 0;
```

**Comment by aslushnikov** [comment]
@gzhappysky @jpbalarini what do you guys do to cause this? Anything special in your setup that I can recreate locally?

**Comment by nicoandmee** [comment]
Also experiencing this issue, my setup includes many linux instances on aws ec2 that regularly check npm for latest version of my package (which uses the puppeteer) , rm -rf, npm update/cache clean. What I have observed is as time goes on, the occurrences of the error mentioned above increase steadily (which I am guessing is due to the same cause).

I am further convinced this is the case because when changing the revision of chromium being used (set as an env variable), the error will drop back to zero, then start climbing again.

**Comment by aslushnikov** [comment]
@nicoandmee this error might happen when Puppeteer fails to launch Chrome. It might be because the host env runs out of file handles limit or maybe something else - I'm not sure yet, but it'd be nice to re-create this locally to see what's going on.

**Comment by evilbs** [comment]
@aslushnikov  sorry, I did not found a method to recreate locally, It is appears in my production environment.

Yes, The reason for my puppeteer fails is the host env runs out of file handles limit, So I first to solve the problem by increase file handles limit of system or maybe something else.
But i hope the puppeteer can handle this failure more graceful. Lanuch puppeteer fails can catch by  try-catch block, Dont't be handled by process.on('unhandledrejection').



// for example.
``` javascript
const puppeteer = require('puppeteer');
process.on('unhandledrejection',()=>{
  /* Error2, The stack:
      Error: spawn /users/hacker/fb/mimi/mimi/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome EAGAIN
        at _errnoException (util.js:1041:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
        at onErrorNT (internal/child_process.js:374:16)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  */

})

(async () => {
  try {
    // lanuch fails, because spawn chrome failed, the error is "spawn */chrome-linux/chrome EAGAIN"
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await page.screenshot({ path: 'example.png' });
    await browser.close();
  } catch (e) {
    /**
     * Error1, The stack:
     * TypeError: input.on is not a function
        at new Interface (readline.js:174:11)
        at Object.createInterface (readline.js:64:10)
        at Promise (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:327:25)
        at Promise (<anonymous>)
        at waitForWSEndpoint (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:326:10)
        at Launcher.launch (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:166:41)
        at module.exports.launch (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Puppeteer.js:36:27)
        at runScript (/users/hacker/fb/mimi/mimi/scripts/index.js:61:37)
        at keepaliveDefaultStratery (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:218:22)
        at joinCore (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:180:20)
        at main (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:117:28)
        at <anonymous>
     */
  }
})(); 
```

**Comment by chrisdel101** [comment]
I have this error on Heroku with Node. I am unsure how to solve it. Has a solution been found?

**Comment by mohini-memane** [comment]
> ## Issue description:
> An error occurred in my production environment and then my program exist ^_^, the error stack is as follows:
> 
> **Error 1:**
> 
> ```js
> TypeError: input.on is not a function
>     at new Interface (readline.js:174:11)
>     at Object.createInterface (readline.js:64:10)
>     at Promise (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:327:25)
>     at Promise (<anonymous>)
>     at waitForWSEndpoint (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:326:10)
>     at Launcher.launch (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Launcher.js:166:41)
>     at module.exports.launch (/users/hacker/fb/mimi/mimi/node_modules/puppeteer/lib/Puppeteer.js:36:27)
>     at runScript (/users/hacker/fb/mimi/mimi/scripts/index.js:61:37)
>     at keepaliveDefaultStratery (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:218:22)
>     at joinCore (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:180:20)
>     at main (/users/hacker/fb/mimi/mimi/beat/keepAliveSchedule.js:117:28)
>     at <anonymous>
> ```
> 
> **Error 2：** by process.nextTick
> 
> ```js
> Error: spawn /users/hacker/fb/mimi/mimi/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome EAGAIN
>     at _errnoException (util.js:1041:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
>     at onErrorNT (internal/child_process.js:374:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
> ```
> 
> ## Error analysis:
> 1. An EAGAIN error occurred when lunch puppeteer, It will be return and does not execute the following code, such as setting stderr for child_process object (chromeProcess object). [code](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L361)
> 2. waitForWSEndpoint method will use the stderr property. At this time, The stderr property is undefined but will call stderr.on method, So the error 1 will be occurred. [code](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L329)
> 3. child_process.js will trigger an error by process.nextTick, Puppeteer does not listening error event because Error 1. So the error didn't catch. Program exist. [code](https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L355)
> 
> ## Solution
> Set the listen error event before chromeProcess.stderr. Allowing chromeProcess to handle error events.
> 
> ```js
> const exitListenerId = helper.addEventListener(chromeProcess, 'exit', () => onClose());
> const errorListenerId = helper.addEventListener(chromeProcess, 'error', error => onClose(error))
> const rl = readline.createInterface({ input: chromeProcess.stderr });
> let stderr = '';
> const listeners = [
>   helper.addEventListener(rl, 'line', onLine),
>   helper.addEventListener(rl, 'close', () => onClose()),
>   exitListenerId,
>   errorListenerId
> ];
> const timeoutId = timeout ? setTimeout(onTimeout, timeout) : 0;
> ```

M facing the error `TypeError: input.on is not a function`  in red hat 7.8 and have made the changes as suggested in waitForWSEndpoint 
Still facing the same issue

`Error: input.on is not a function\n    at new Interface (readline.js:207:11)\n    at Object.createInterface (readline.js:75:10)\n    at Promise (/apps/cbqpms/credence/microservices/reporting-server/node_modules/puppeteer/lib/Launcher.js:329:27)\n    at new Promise (<anonymous>)\n    at waitForWSEndpoint (/apps/cbqpms/credence/microservices/reporting-server/node_modules/puppeteer/lib/Launcher.js:326:12)\n    at Launcher.launch (/apps/cbqpms/credence/microservices/reporting-server/node_modules/puppeteer/lib/Launcher.js:170:41)
`
