### ISSUE TITLE
How to target and interact with Polymer tags using Puppeteer?

### ISSUE THREAD

**Issue by Anders3510** [puppeteer/puppeteer#3750]
**Tell us about your environment:**

* Puppeteer version: Current latest
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 11.6.0

(This link is possibly region blocked, I don't know for sure)
https://tinyurl.com/yd6qv9ok

I am attempting to interact with the pdf viewer for the above document, but the element that I am attempting to target is, and is nested inside of, a custom-built tag created using Polymer.
How do I target, and click on, an element such as <viewer-pdf-toolbar>?

In the site's own console window, these elements can be targeted like one would expect, by calling `document.querySelector` with a selector such as 'viewer-pdf-toolbar', and it can even access the insides of shadow roots using /deep/.

This functionality does not appear to be supported by Puppeteer, is it related to the version of Chromium it is running? Would reverting to a version of Puppeteer that uses a version of Chromium prior to 63, (where /deep/ was removed. See [this](https://developers.google.com/web/updates/2017/10/remove-shadow-piercing) for details) allow the use of /deep/?

__I have tried:__
* Calling `await page.$('viewer-pdf-toolbar')`, resolves to null because it cannot find the element
* Calling `await page.$$('viewer-pdf-toolbar`, resolves to an empty array for the same reason
* Using `page.waitForSelector('viewer-pdf-toolbar')`, times out after 30 seconds, due to not finding the element
* Targeting the element by querying the dom-module tag, which is the outermost container for every Polymer module
* Attempting to find a method to access the `document` object directly, to then call `document.querySelector`, like in the console window

### What is my use case for this?
My goal is to use Puppeteer to access the pdf viewer, and click on the download button to download the pdf document. If there are better, more elegant solutions to this problem, I am completely open to suggestions.

**Comment by aslushnikov** [comment]
@Anders3510 what you want is to query nodes within shadow dom. This has been discussed in https://github.com/GoogleChrome/puppeteer/issues/858.

The solution we converged on for this is explained [here](https://github.com/GoogleChrome/puppeteer/issues/858#issuecomment-438540596). Long story short - use ["Copy JS Path"](https://umaar.com/dev-tips/185-copy-js-path/) in Chrome DevTools to get a javascript one-liner that queries a node inside shadow DOM.

Hope this helps

**Comment by Anders3510** [comment]
That feature doesn't appear to exist. The option isn't there in the context menu, and I have the most recent version of Chrome.
As I've already said, I've tried a perfectly reasonable selector, that I know functions just fine in the website's console window using `document.querySelector`, but it doesn't work with Puppeteer. Since `page.$(selector)` is supposedly the same as `document.querySelector`, how come this doesn't work? Does Puppeteer not understand /deep/?

Edit: Is it maybe possible for me to access the `document` object directly, in way, so that I can run document.querySelector outright?

**Comment by aslushnikov** [comment]
> That feature doesn't appear to exist. The option isn't there in the context menu, and I have the most recent version of Chrome.

Please use Chrome Canary.

> Does Puppeteer not understand /deep/?

The `/deep/` combinator was removed a while ago from WebPlatform in general and Chromium specifically. 

>  Is it maybe possible for me to access the document object directly, in way, so that I can run document.querySelector outright?

You can use [`page.evaluateHandle`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageevaluatehandlepagefunction-args) to run code inside the page:

```js
const elementHandle = await page.evaluateHandle(() => document.querySelector('.foo'));
```

**Comment by Anders3510** [comment]
I'm really not understanding the last part at all, and the docs are no help, are you _sure_ that this functions on Polymer html imports and shadow roots?
    const result = await popup.evaluateHandle(() => document.querySelector('viewer-pdf-toolbar#toolbar'))
This returns _something_ into the `result` variable but I can't seem to make use of it at all. `result.asElement()` and `result.jsonValue()` both return null, and `result.getProperty()` gives a promise rejection with "Cannot read property x of null".
I'm 1000% lost here, the same selector functions just fine in the page's own console window.

**Comment by aslushnikov** [comment]
@Anders3510 can you please post your website and the selector you try to use?

**Comment by Anders3510** [comment]
This link is possibly region blocked, I don't know for sure.
https://tinyurl.com/yd6qv9ok
I'm trying to call `document.querySelector('viewer-pdf-toolbar#toolbar')` inside `page.evaluateHandle()` and return a JSHandle to get properties of the selected element.

**Comment by aslushnikov** [comment]
@Anders3510 yes, this link doesn't open for me - I'm getting "blocked!" response. Can you build a tiny repro or reproduce this issue with any of polymer demos?

**Comment by kerrijones** [comment]
reply@reply.github.com

**Comment by Anders3510** [comment]
What I'm targeting is a part of Chrome's own pdf viewer, so opening any PDF with chrome would do, they all have the same structure. My end goal is to click the download button and download the pdf.

**Comment by aslushnikov** [comment]
@Anders3510 if your end goal is to download the PDF, why don't you just fetch it from URL?

**Comment by Anders3510** [comment]
> @Anders3510 if your end goal is to download the PDF, why don't you just fetch it from URL?

I don't believe it's a viable solution as the pdf comes from a site I have no jurisdiction over and is updated regularly, which means the urls change drastically.
