### ISSUE TITLE
Using Autocomplete in Puppeteer

### ISSUE THREAD

**Issue by AlonsoK28** [puppeteer/puppeteer#3757]
Is possible to use `Autocomplete` ([Google Chrome autofill feature][2]) in `Puppeteer`?

This feature is not mentioned in the official `Puppeteer` [documentation][1]

  [1]: https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=outline
  [2]: https://support.google.com/chrome/answer/142893?co=GENIE.Platform%3DDesktop&hl=en

**Comment by aslushnikov** [comment]
> Is possible to use Autocomplete (Google Chrome autofill feature) in Puppeteer?

@AlonsoK28 there's no special api to drive Autocomplete. What's your usecase?

**Comment by AlonsoK28** [comment]
Is it possible to enter the data from the "localstorage" using the "automplete" chrome function to fill out a form?

This would be an example of the object in "local storage"
data:{
 name: "john doe",
 amount: "500"
 key1: 12345
 key2: 7890
}

And this would be the structure to fill in the data (matches the structure of the object in "localstorage")

<input id="name" name="name">
<input id="amount" name="amount">
<input id="key1" name="key1">
<input id="key2" name="key2">

**The result is that chrome can automatically fill the data in this form (as seen in the image)**

![puppeteer1](https://user-images.githubusercontent.com/37458700/51212169-57b79980-18dd-11e9-91fe-803cb43b083f.png)

**Comment by aslushnikov** [comment]
@AlonsoK28 you can drive form filling yourself using [`page.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageevaluatepagefunction-args), but this won't engage with Chrome's Autocomplete functionality.

What's your end goal?

**Comment by AlonsoK28** [comment]
> @AlonsoK28 you can drive form filling yourself using [`page.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageevaluatepagefunction-args), but this won't engage with Chrome's Autocomplete functionality.

There is the possibility of make an example of how to use **`page.eval()`** in this escenario?

> 
> What's your end goal?

What I intend is to be able to fill a input fields in the form in a faster way
