### ISSUE TITLE
Expose getUserMedia() to allow for audio/video capture

### ISSUE THREAD

**Issue by LukeTOBrien** [puppeteer/puppeteer#3761]
Hello there,

I'm working on a project where I want to capture the browser view and save the stream to a NodeJS [Writable stream](https://nodejs.org/api/stream.html#stream_class_stream_writable).  
I have looked at the issues https://github.com/GoogleChrome/puppeteer/issues/2175 and https://github.com/GoogleChrome/puppeteer/issues/478 but it seems the **getDisplayMedia()** method is what I need.  
*As in [this article](https://addpipe.com/blog/screen-capture-in-chrome-70-with-getdisplaymedia/)*

The thing is that if I do **page.evaluate** I am no longer inside a NodeJS context.

Would it be possible to expose the page's display media from within Node? 
Something like a new method on the [Page class](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#class-page) called getDisplayMedia()?

Do you understand what I am getting at and do you think it would be possible?

Luke

*Ref*:  
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia 
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaDevices

**Comment by aslushnikov** [comment]
@LukeTOBrien I think `getUserMedia` technically works (at least there's a [nice demo](https://github.com/GoogleChromeLabs/carlo/tree/master/examples/photobooth) in [GoogleChromeLabs/carlo](https://github.com/GoogleChromeLabs/carlo) that uses it). It should not be hard to transfer data from page to the node side using something like [`page.exposeFunction`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageexposefunctionname-puppeteerfunction).

Alternatively to `getUserMedia`, you can use Chrome Extensions capture API (there's a [demo repository](https://github.com/GoogleChrome/puppeteer/issues/3651#issuecomment-453242481) that does this).

Both these approaches are purely user-land and don't require any additional API on Puppeteer side. The API we're aiming to in Puppeteer is covered by #478 and requires mostly upstream work.
