### ISSUE TITLE
uploadFile in puppeteer-firefox

### ISSUE THREAD

**Issue by fran0254** [puppeteer/puppeteer#3762]
Is it possible to upload files with the puppeteer-firefox library? It's not working for me, I'm adding code

```javascript
const pptrFirefox = require('puppeteer-firefox');

  (async () => {

       const browser = await pptrFirefox.launch( {headless: false });
       const page = await browser.newPage();   

    await page.goto('https://www.webejemplo.com', {timeout: 0});
    await page.waitForSelector('input[type=file]', {timeout: 0 });
            
            var fileUploaders = await page.$("input[type=file]");                   
                       
            await fileUploaders.uploadFile('foto_0.jpg');        
                   
            await page.waitFor(3000);

})();
```

**Comment by matheuschimelli** [comment]
Hey, take a look at https://aslushnikov.github.io/ispuppeteerfirefoxready/ . It looks like not working yet

**Comment by vovanluan** [comment]
I am facing error ` err Error: Protocol error (DOM.setFileInputFiles): DOM.setFileInputFiles RemoteAgentError@chrome://remote/content/Error.jsm:25:5` when uploadFile in firefox too. Is this feature available in puppeteer firefox?

**Comment by skipjack** [comment]
Seeing the same error as @vovanluan when using [puppetry][1]. I see this [merged pr][2] (referenced above), @aslushnikov based on that should we expect this to be fixed?

[1]: https://github.com/dsheiko/puppetry
[2]: https://github.com/puppeteer/puppeteer/pull/4058

**Comment by skipjack** [comment]
Tried with [FireFox Beta][1] as well, still no luck.

[1]: https://www.mozilla.org/en-US/firefox/channel/desktop/

**Comment by nihirv** [comment]
This is still an issue
