### ISSUE TITLE
Domain https://pptr.dev/ is inaccessible

### ISSUE THREAD

**Issue by fakiolinho** [puppeteer/puppeteer#3763]
I cannot access domain `https://pptr.dev/`:

![image](https://user-images.githubusercontent.com/2962687/51089060-9e878100-176f-11e9-8f1c-46a0c9fd6196.png)

**Comment by vsemozhetbyt** [comment]
For me, it is OK now.

**Comment by aslushnikov** [comment]
Thanks for letting us know; looks like it recovered indeed.

If these incidents start to plague us, we'll have to invest more and switch away from github pages.

**Comment by R1ZEN** [comment]
Cannot access to `https://pptr.dev/`, think issue should be reopened.
