### ISSUE TITLE
[Feature request/Question] Endlessly listen to page events or AJAX requests

### ISSUE THREAD

**Issue by abriginets** [puppeteer/puppeteer#3776]
Hello. I tried searching for my issue but it seems that I'm not getting any answer for my question at StackOverflow in the nearest time so I decided to create an issue. Sorry if there's already a solution for my problem. 

Basically, I have a website which has a single `setInterval` making an AJAX call. After AJAX call is in `done` state JavaScript generates an event `$(document).trigger('new_post')`. What I need is to open a page and listen to it endlessly gathering every AJAX call or catching every `new_post` trigger to retrieve new data. I already looked into [this example](https://github.com/GoogleChrome/puppeteer/blob/master/examples/custom-event.js), but it seems to be working only if an event was triggered before `networkidle` or `load`. In my case, AJAX call repeats after `document.ready` periodically (usually it's 10-15 seconds). Is there any possible solution for this case?

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: 10.15.0

**Comment by aslushnikov** [comment]
@JamesJGoodwin so you have a few options here:

1. Use [`'requestfinished'`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-event-requestfinished) event to listen for the AJAX requests. You can use [`request.resourceType()`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-requestresourcetype) to filter for XHRs.
2. Use [`page.evaluateOnNewDocument`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageevaluateonnewdocumentpagefunction-args) to inject a [mutation observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) that will communicate back to node.js using [`page.exposeFunction`](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageexposefunctionname-puppeteerfunction)
