### ISSUE TITLE
Running on WSL

### ISSUE THREAD

**Issue by thamerla** [puppeteer/puppeteer#3783]
Is there an official guide on running it under Windows Subsystem for Linux and those different distros - ubuntu, SUSE etc?

**Comment by aslushnikov** [comment]
Check out discussion at https://github.com/GoogleChrome/puppeteer/issues/1837

**Comment by thamerla** [comment]
@aslushnikov already did. Was wondering if there's something official out there. I noticed so far that it works out of the box with provided chromium from the package, but... it doesn't work with system chromium.

**Comment by aslushnikov** [comment]
@nonyy ah I see; no, there's no official guide regarding WSL atm.
