### ISSUE TITLE
Using proxy on Windows chrome

### ISSUE THREAD

**Issue by thamerla** [puppeteer/puppeteer#3784]
Is there any interface/API that allows me to use proxy on Windows just like linux --proxy-server arg?
I am trying argument --proxy-server on windows chrome but it doesn't work...

**Comment by aslushnikov** [comment]
`--proxy-server` should work just fine - it's a chromium feature, not Puppeteer's. If it doesn't for you, I'd ask on the [chromium-dev](https://groups.google.com/a/chromium.org/d/forum/chromium-dev)
