### ISSUE TITLE
How can I get element attribute without evaluate function

### ISSUE THREAD

**Issue by JaLe29** [puppeteer/puppeteer#3786]
Hi puppeteer folks!

I am using `evaluate` function for getting an attribute of web element.

Is there any way how to get attribute without `evaluate`?

For example for these attributes:

countdown
innerText

My code with evaluate function:

```
const xpath = ....
const await this.activePage.$x(xpath)

const attributeValue =  await this.activePage.evaluate((obj, attr) => {
				const single = obj[attr]
				if (!single) return obj.getAttribute(attr)
				return single
			}, webElement, 'countdown')
```

I don`t want to use evaluate.

Thank you for any help!

**Comment by vsemozhetbyt** [comment]
If the attributes have property counterparts, you can use something like this:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const [elementHandle] = await page.$x('.//a');
    const propertyHandle = await elementHandle.getProperty('innerText');
    const propertyValue = await propertyHandle.jsonValue();

    console.log(propertyValue);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
More information...
```

**Comment by JaLe29** [comment]
@vsemozhetbyt Thank you for your fast reply! But it returns `undefined` for elements like this:

![image](https://user-images.githubusercontent.com/22296816/51274230-e9eb9a80-19ce-11e9-97f3-2ee689712ade.png)

```
 const propertyHandle = await elementHandle.getProperty('perc'); // elementHandle really exist
 const propertyValue = await propertyHandle.jsonValue();
// propertyValue is undefined
```

**Comment by vsemozhetbyt** [comment]
@JaLe29 Yes, this may be because `'perc'` attribute is not doubled as an element property. I am afraid I cannot think of any other way to retrieve such attributes except `page.evaluate()` + `element.getAttribute()`.

**Comment by vsemozhetbyt** [comment]
You can try to get `'outerHTML'` property and parse the HTML code string for the attribute, but this way seems difficult and unreliable.

**Comment by vsemozhetbyt** [comment]
Sorry, I missed out we can retrieve jsHandle for just [an attribute](https://developer.mozilla.org/en-US/docs/Web/API/Attr) via XPath. Try this:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const [elementHandle] = await page.$x('.//a/@href');
    const propertyHandle = await elementHandle.getProperty('value');
    const propertyValue = await propertyHandle.jsonValue();

    console.log(propertyValue);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
http://www.iana.org/domains/example
```

**Comment by vsemozhetbyt** [comment]
I.e.  you can use an XPath like `'.//div/@perc'` this way.

**Comment by JaLe29** [comment]
Sounds good!

Perfect!

Thx

**Comment by iiinnniii** [comment]
Why do not all attributes have property counterparts?

**Comment by TomasHubelbauer** [comment]
@gernotpokorny That's a general JS thing not a Puppeteer thing. It's discussed here: https://javascript.info/dom-attributes-and-properties

**Comment by akash8663** [comment]
In my scenario, i am trying to get attribute values of 10 elements which my xpath is returning. But when i am trying to get that using foreach i am getting target closed and other errors. I am sure that my xpath is not incorrect. 
`navs = await frame.$x("//nav[@id='_nav']/ul/li/a/dl/@data-cehid"),
                    console.log(navs.length),
                    navs.forEach(async (el) => {
                        const propertyHandle = await el.getProperty('value')
                        const propertyValue = await propertyHandle.jsonValue();
                        console.log(propertyValue)
                    })`

**Comment by vsemozhetbyt** [comment]
`forEach()` is not async, it runs all the functions at once and does not wait for them. Try `for...of` loop for the same.
