### ISSUE TITLE
How to get load time of multiple redirect links request ?

### ISSUE THREAD

**Issue by vietdotnetcourses** [puppeteer/puppeteer#3788]
Hi, im building a small tool to crawl web data with puppeteer. 
What i expect is the tool will request to a affiliate urls. then, the request will go through all the redirect urls to touch the target . I want to recored all the redirect links and loading time for each of them. 
Is it possible to do it?

Thanks in advance!

**Comment by vsemozhetbyt** [comment]
Maybe [`request.redirectChain()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#requestredirectchain) can help with redirect recording.

**Comment by aslushnikov** [comment]
@yenntsmartosc looks like you actually want https://github.com/GoogleChrome/puppeteer/issues/1434. Please upvote to follow progress and bump priority

**Comment by vietdotnetcourses** [comment]
Hi, thanks for your quick support. I had another issue on the way of implementation. I'm using a proxy (Luminati) to crawl the web data. Let say i have a chain of redirect urls : ur1 - url2 -url3-url4-etc. My issue is puppeteer can pass through first url1 with code as below

`  const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--proxy-server=zproxy.lum-superproxy.io:22225'
    ]
  });
 const page = await browser.newPage();
  await page.authenticate({ username : 'myUsername', password : 'myPassword'});
 const response = await page.goto(url1);

  
  const chain = response.request().redirectChain();
  console.log(chain);

  await browser.close();

`
but it will fail when meet url2 and seems like the puppeteer no longer authenticate Proxy. 

Please advise. Thanks!
