### ISSUE TITLE
Validate multiple selectors in DOM

### ISSUE THREAD

**Issue by AlonsoK28** [puppeteer/puppeteer#3791]
Related to [question ](https://github.com/GoogleChrome/puppeteer/issues/709)

Is it possible to validate with **`Puppeteer v1.11.0`** (or other approach) what is the first selector in appears of a group of selectors **and know which one it was** to perform an action?

```
selector1 = `#user`;
selector2 = `#search`;
selector3 = `#error`;

waitForSelector(selector1 OR selector2 OR selector3)

if(selector1){
 //do something
}else if(selector2){
 //do other something
}else if(selector3){
 //do other other something 
}else{
 //finally do...
}
```

**Comment by vsemozhetbyt** [comment]
Something like this?
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const selectors = ['h1', 'p', 'a'];

    const jsHandle = await page.waitForFunction((selectors) => {
      for (const selector of selectors) {
        if (document.querySelector(selector) !== null) {
          return selector;
        }
      }
      return false;
    }, {}, selectors);

    const selector = await jsHandle.jsonValue();

    if (selector === selectors[0]) {
      console.log(`The first selector is '${selectors[0]}'.`);
    } else if (selector === selectors[1]) {
      console.log(`The first selector is '${selectors[1]}'.`);
    } else if (selector === selectors[2]) {
      console.log(`The first selector is '${selectors[2]}'.`);
    } else {
      console.log('Something strange happens.');
    }

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
The first selector is 'h1'.
```

**Comment by AlonsoK28** [comment]
> Something like this?
> 
> ```js
> 'use strict';
> 
> const puppeteer = require('puppeteer');
> 
> (async function main() {
>   try {
>     const browser = await puppeteer.launch();
>     const [page] = await browser.pages();
> 
>     await page.goto('https://example.org/');
> 
>     const selectors = ['h1', 'p', 'a'];
> 
>     const jsHandle = await page.waitForFunction((selectors) => {
>       for (const selector of selectors) {
>         if (document.querySelector(selector) !== null) {
>           return selector;
>         }
>       }
>       return false;
>     }, {}, selectors);
> 
>     const selector = await jsHandle.jsonValue();
> 
>     if (selector === selectors[0]) {
>       console.log(`The first selector is '${selectors[0]}'.`);
>     } else if (selector === selectors[1]) {
>       console.log(`The first selector is '${selectors[1]}'.`);
>     } else if (selector === selectors[2]) {
>       console.log(`The first selector is '${selectors[2]}'.`);
>     } else {
>       console.log('Something strange happens.');
>     }
> 
>     await browser.close();
>   } catch (err) {
>     console.error(err);
>   }
> })();
> ```
> 
> ```
> The first selector is 'h1'.
> ```

**Comment by AlonsoK28** [comment]
@vsemozhetbyt Is possible do these validation using [xPath](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagewaitforxpathxpath-options) ?

**Comment by vsemozhetbyt** [comment]
I think it is possible:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const xPaths = ['.//h1', './/p', './/a'];

    const jsHandle = await page.waitForFunction((xPaths) => {
      for (const xPath of xPaths) {
        const element = document.evaluate(
          xPath, document.body, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null
        ).singleNodeValue;
        if (element !== null) {
          return xPath;
        }
      }
      return false;
    }, {}, xPaths);

    const xPath = await jsHandle.jsonValue();

    if (xPath === xPaths[0]) {
      console.log(`The first xPath is '${xPaths[0]}'.`);
    } else if (xPath === xPaths[1]) {
      console.log(`The first xPath is '${xPaths[1]}'.`);
    } else if (xPath === xPaths[2]) {
      console.log(`The first xPath is '${xPaths[2]}'.`);
    } else {
      console.log('Something strange happens.');
    }

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
The first xPath is './/h1'.
```

**Comment by AlonsoK28** [comment]
> I think it is possible:
> 
> ```js
> 'use strict';
> 
> const puppeteer = require('puppeteer');
> 
> (async function main() {
>   try {
>     const browser = await puppeteer.launch();
>     const [page] = await browser.pages();
> 
>     await page.goto('https://example.org/');
> 
>     const xPaths = ['.//h1', './/p', './/a'];
> 
>     const jsHandle = await page.waitForFunction((xPaths) => {
>       for (const xPath of xPaths) {
>         const element = document.evaluate(
>           xPath, document.body, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null
>         ).singleNodeValue;
>         if (element !== null) {
>           return xPath;
>         }
>       }
>       return false;
>     }, {}, xPaths);
> 
>     const xPath = await jsHandle.jsonValue();
> 
>     if (xPath === xPaths[0]) {
>       console.log(`The first xPath is '${xPaths[0]}'.`);
>     } else if (xPath === xPaths[1]) {
>       console.log(`The first xPath is '${xPaths[1]}'.`);
>     } else if (xPath === xPaths[2]) {
>       console.log(`The first xPath is '${xPaths[2]}'.`);
>     } else {
>       console.log('Something strange happens.');
>     }
> 
>     await browser.close();
>   } catch (err) {
>     console.error(err);
>   }
> })();
> ```
> 
> ```
> The first xPath is './/h1'.
> ```

I´am getting following error  :(

```
Error: Evaluation failed: TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.    at eval (eval at waitForPredicatePageFunction (:2:21), <anonymous>:5:38)    at eval (eval at waitForPredicatePageFunction (:2:21), <anonymous>:13:11)
    at onRaf (__puppeteer_evaluation_script__:56:33)
    at pollRaf (__puppeteer_evaluation_script__:48:5)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:18)
```
Using this xPath

```xPaths = [`//*[@id="lblmsg"]/p`, `//*[@id="ctl00_ContentPlaceHolder1_txtBusqueda"]`];```

**Comment by AlonsoK28** [comment]
> Something like this?
> 
> ```js
> 'use strict';
> 
> const puppeteer = require('puppeteer');
> 
> (async function main() {
>   try {
>     const browser = await puppeteer.launch();
>     const [page] = await browser.pages();
> 
>     await page.goto('https://example.org/');
> 
>     const selectors = ['h1', 'p', 'a'];
> 
>     const jsHandle = await page.waitForFunction((selectors) => {
>       for (const selector of selectors) {
>         if (document.querySelector(selector) !== null) {
>           return selector;
>         }
>       }
>       return false;
>     }, {}, selectors);
> 
>     const selector = await jsHandle.jsonValue();
> 
>     if (selector === selectors[0]) {
>       console.log(`The first selector is '${selectors[0]}'.`);
>     } else if (selector === selectors[1]) {
>       console.log(`The first selector is '${selectors[1]}'.`);
>     } else if (selector === selectors[2]) {
>       console.log(`The first selector is '${selectors[2]}'.`);
>     } else {
>       console.log('Something strange happens.');
>     }
> 
>     await browser.close();
>   } catch (err) {
>     console.error(err);
>   }
> })();
> ```
> 
> ```
> The first selector is 'h1'.
> ```

Is possible set `timeout` and `visible` attribute to this function like embedded [waitFor()](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagewaitforselectorselector-options) ?

💯

**Comment by vsemozhetbyt** [comment]
Could you post your `page.waitForFunction()` function?

**Comment by AlonsoK28** [comment]
> Could you post your `page.waitForFunction()` function?

Is the same that you coded in your example 👍

**Comment by vsemozhetbyt** [comment]
Can you provide a full script to reproduce the error?

**Comment by dcr007** [comment]
how about using `Promise.race()` something like this : 
`await Promise.race([await this.page.$(selector1), await this.page.$(selector2)]);`

**Comment by lifeisgooddev** [comment]
Hello, AlonsoK28.
***Error: Evaluation failed: TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.***
I also have this error.
How did you solve this error?
thanks.

**Comment by vsemozhetbyt** [comment]
@lifeisgooddev How exactly do you call `document.evaluate()`?
