### ISSUE TITLE
Implementing parallelization? 

### ISSUE THREAD

**Issue by icarusmiles** [puppeteer/puppeteer#380]
Currently I am doing Chromeless via AWS Lambda, it's very slow and if possible I'd like to do the processing my self. 

Is there anyway to implement parallelization? If I try to spawn multiple browsers some may go through over time, but pretty much it times out. The reason for doing this is because the application I want relies on user input and I don't want to have a queue per-say.

Any ideas or is this something that's not possible?

**Comment by aslushnikov** [comment]
What kind of parallelization are you interested in?
- You can create multiple pages via [`page.newPage`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browsernewpage) method
- You can attach to a running browser instance with [`puppeteer.connect`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions)
- We also plan to add browser contexts in future: #85

**Comment by icarusmiles** [comment]
Thanks for the response @aslushnikov! 

Both forms of parallelization, I got the `page.newPage` down. 
I want an entirely new instance spawned, so if two users are using the tool/script at the same time they wont have to wait and/or it wont time out. So if I use `puppeteer.connect` it would hookup to an existing chrome if it's running?

**Comment by aslushnikov** [comment]
Right, the `puppeteer.connect` would do that. You might also need the #85 to be implemented if you want users to be completely isolated from one another.

**Comment by icarusmiles** [comment]
Wow, that's perfect. I have some work to do and I'll watch that!

**Comment by mhaseebkhan** [comment]
@miles-collier: Can you please share a sample?

I am trying to do a similar thing here for which I have created #2670, but, haven't heard anything on it.

I have a Node Express app which uses puppeteer and launches a browser window with a pre-configured URL and perform some tasks on it. Everything works great when there is juts one window opened. As soon as a second window is opened, the events of the first one are swallowed and both the browser windows are left in orphan state.

Any ideas what I should do to resolve this problem?

CC: @aslushnikov
