### ISSUE TITLE
Unable to pass page object to a function in another file.

### ISSUE THREAD

**Issue by iznomau5** [puppeteer/puppeteer#3800]
I have a file index.js where i have initialized the browser as below :

```js
(async () => {
    const browser = await _driver.launch
    (
        {
            headless: false,
            args: ['--start-maximized']
        }
    );
    var page = await browser.newPage();
    await page.setViewport({'width': 1366, 'height': 768 });    
    await page.goto('https://www.example.com/');
})();
```

Now i have another file homepage.js which contains the methods for manipulations on the homepage. This file used the page object initialized in index.js file. Im trying to pass the page object to the function of homepage.js bt it gives me UnhandledPromiseejectionWarning.

**Comment by SlootSantos** [comment]
Are you returning this function to the `homepage.js`?
If so than keep in mind that `async function` return a promise themselves.

**Comment by iznomau5** [comment]
@SlootSantos can you please give me a basic example of how to do it ? i'm new to puppeteer. 
just tell me how can i do the following :
I have a async browser and a await page object in the index.js file and i want to pass the page object to a file homepage.js which needs to click on some elements and then the focus shifts back to index.js and some other function is called.

**Comment by vsemozhetbyt** [comment]
Something like this?
`index.js`:
```js
'use strict';

const _driver = require('puppeteer');

module.exports = async () => {
  const browser = await _driver.launch({
    headless: false,
    args: ['--start-maximized']
  });
  var page = await browser.newPage();
  await page.setViewport({ 'width': 1366, 'height': 768 });
  await page.goto('https://www.example.com/');
  return page;
};
```
`homepage.js`:
```js
'use strict';

const getPage = require('./index.js');

(async function main() {
  try {
    const page = await getPage();
    console.log(await page.evaluate(() => document.title));
  } catch (err) {
    console.error(err);
  }
})();
```
Output:
```
Example Domain
```

**Comment by iznomau5** [comment]
@vsemozhetbyt Thank you man. One last question, if im running the script with "npm start" and it executed index.js how can i call the main function from homepage.js ?
I want index.js to be my main file and all the other files as support/helper files. can we do that ?

**Comment by vsemozhetbyt** [comment]
Maybe you need to swap the logic then? Create `page` in the `index.js` and transfer it as an argument to various imported functions from ` homepage.js` etc.

**Comment by iznomau5** [comment]
@vsemozhetbyt  can you do this in the example above ?

**Comment by vsemozhetbyt** [comment]
`index.js`:

```js
'use strict';

const puppeteer = require('puppeteer');
const pUtils = require('./puppeteer-utils.js');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    console.log(await pUtils.getLocation(page));
    console.log(await pUtils.getTitle(page));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

`puppeteer-utils.js`:

```js
'use strict';

async function getLocation(page) {
  const location = await page.evaluate(() => document.location.href);
  return `Document location is "${location}".`;
}

async function getTitle(page) {
  const title = await page.evaluate(() => document.title);
  return `Document title is "${title}".`;
}

module.exports = {
  getLocation,
  getTitle,
};
```

Output:

```
Document location is "https://example.org/".
Document title is "Example Domain".
```

**Comment by iznomau5** [comment]
@vsemozhetbyt  Thank you so much man and thank you for handling my stupidity.

**Comment by vsemozhetbyt** [comment]
Happy coding)

**Comment by iznomau5** [comment]
@vsemozhetbyt  is it possible to contact you for my future queries without raising a issue here. If yes then how can i contact you.

**Comment by vsemozhetbyt** [comment]
You can try to email me with the address in the GitHub profile. But I am not experienced developer so mostly I will not be of much help. You are welcome though)

**Comment by jlanssie** [comment]
I have this issue too. The solution in previous comment does not work for me, but throws error: 

error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at /mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at ExecutionContext._evaluateInternal (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/mypath/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: ''
}

I got this while trying the following: 

main.js

```
'use strict';
const {puppeteer, URL, fs, variables} = require('./modules.js');
const {login, cookies, test} = require('./scenarios/scenarios.js');
(async() => {
  const browser = await puppeteer.launch({
    headless: false, 
    defaultViewport: null,
  });
  let page = await browser.newPage();
  try {
    test.test(page)
  } catch (err) {
    console.log(err)
  }
  await browser.close();
})();
```

.scenarios/test.js 

```
'use strict';
const {puppeteer, URL, fs, variables} = require('../modules.js');
async function test(page) {
    await page.goto(https://www.example.com, {waitUntil: 'load', timeout: 0});
}
module.exports.test = test
```

**Comment by vsemozhetbyt** [comment]
@jlanssie Try `await test.test(page)` — otherwise there is a race condition, the `await browser.close();` may be called before the `await page.goto()`.

**Comment by jlanssie** [comment]
Yep, found out before your comment. But can confirm that is the solution. :-)
