### ISSUE TITLE
pptr-ff: Unable to build juggler on MacOS 10.14

### ISSUE THREAD

**Issue by SlootSantos** [puppeteer/puppeteer#3802]
@aslushnikov I just started checking out `juggler` and ran into issues when building FF on my machine which is a MacBook Pro 2017 running **MacOS 10.14 (Mojave)**.

I could verify this being an issue with this specific MacOS version on the mozilla IRC server.

This bug has been discussed already at [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1487552).

I already opened a [PR](https://github.com/GoogleChrome/puppeteer/pull/3801) to add this information to the docs of juggler.

**Comment by aslushnikov** [comment]
Thanks @SlootSantos; https://github.com/GoogleChrome/puppeteer/pull/3801 is merged.
