### ISSUE TITLE
Simple example browser.page hangs if using terminal inside VSCode only!

### ISSUE THREAD

**Issue by Coder2012** [puppeteer/puppeteer#3805]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Windows 10 x64
* URLs (if applicable): 
* Node.js version: 11.2.0

**What steps will reproduce the problem?**

Running the following code in VSCode using any terminal on windows (CMD, Powershell or git bash); It does actually work using any of those terminals outside of VSCode.

_Please include code that reproduces the issue._

`const puppeteer = require ('puppeteer');`

`(async () => {`
   `const browser = await puppeteer.launch();`
    `const page = await browser.newPage();`
   ` console.log('hanging around?');`
`})();`

**What is the expected result?**

The page variable should be resolved.

**What happens instead?**

It never resolves and just hangs!

**Comment by aslushnikov** [comment]
Symptoms point to the issue with VSCode's terminal. Can you please file this over to vscode?

**Comment by tageecc** [comment]
any updates?

**Comment by mountainguan** [comment]
so, how to fix this problem ??? I meet the same issue over the latest version.

**Comment by rnorton45** [comment]
Me too...
