### ISSUE TITLE
Support for <video> elements with mp4 files / use of proprietary codecs

### ISSUE THREAD

**Issue by joakimgrr** [puppeteer/puppeteer#381]
Pardon my possible ignorance on the matter, just discovered this today. As far as I know, chromium doesn't support mp4 out of the box. So a embedded <video>element with a mp4 file (according to my testings) is not working. Workaround for this is to use proprietary codecs. 

My question is, are those proprietary codecs already included in the chromium executable that puppeteer uses and if not, can they be added somehow?

**Comment by Garbee** [comment]
Only in Chrome. Which if you're using that we recommend Canary currently as Puppeteer relies on new modifications landing now. Which aren't in Beta/Stable channel builds yet.

Ref #291

**Comment by joakimgrr** [comment]
@Garbee Ah, tried going trough the issues before writing one, but didn't notice that one. Thank you for your fast response!

Apparently Canary is not available on linux (i would be running this in a Ubuntu Docker container). What would be the best approach in this situation? Dev / beta release channel of chrome perhaps?

**Comment by Garbee** [comment]
Canary -> Dev -> Beta -> Stable

So Dev is the best bet but things still may be quirky right now.

Beyond that, there is nothing you really can do. It's a codec problem and unless the MPEG group allows open and free re-use, Chromium can't include it.

**Comment by joakimgrr** [comment]
Totally understandable. I'll go with the dev route and hopefully get good enough results! Thank you!

**Comment by ebidel** [comment]
Marking this as resolved, but we'll keep it open for a bit so users can find it.

**Comment by pavelfeldman** [comment]
So you need to wait for fresh enough chrome to get to the Dev (takes a week or so).
