### ISSUE TITLE
pptr-ff: Black screen when building FF

### ISSUE THREAD

**Issue by SlootSantos** [puppeteer/puppeteer#3812]
@aslushnikov Yesterday I reported in #3802 that the firefox build failed due to changed behavior of the `xcode-select --install` command. 
I could actually workaround the issue and added the tipp to the readme.

Turns out FF has a known issue running the browser built with `MacOSX SDK 10.14`. 
Described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1493330.

A couple of days ago Mike Shal from the mozilla team added a [check to the build process looking for the used SDK](https://bugzilla.mozilla.org/show_bug.cgi?id=1500504). 

The guys over at mozilla helped me figuring out how to build it on Mojave. 
In my opinion this is actually quite tricky to figure out on your own.
Hence I will add yet another PR to adapt the documentation!

Sorry for the confusion about how to actually build FF on Mojave!

**Comment by SlootSantos** [comment]
Added PR: #3813

**Comment by aslushnikov** [comment]
@SlootSantos thank you for figuring this out!
