### ISSUE TITLE
Converting a website into a single page HTML file

### ISSUE THREAD

**Issue by markusmobius** [puppeteer/puppeteer#3815]
I needed code that creates single-file HTML archives from websites on a server (so ideally using headless Chrome through Puppeteer). The best single-file converter I found was the SavePageWE Chrome extension. Extensions don't run on headless Chrome - however, the code was easy to adapt for Node.js/Puppeteer.

Here is the repo with the code:

https://github.com/markusmobius/nodeSavePageWE

I hope others find it useful. Would also love to know if there are related projects (I searched far and wide and couldn't find anything for Puppeteer). There is inliner (https://github.com/remy/inliner ) but that didn't work for many news sites that I was interested in archiving.

**Comment by kiavashi** [comment]
if MHTML would work, you can use the [Page.captureSnapshot](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-captureSnapshot) command in the devtools protocol (accessed in puppeteer using [`page.target().createCDPSession()`](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#class-cdpsession)

**Comment by aslushnikov** [comment]
For the record - Previous discussion on MHTML: https://github.com/GoogleChrome/puppeteer/issues/3658
