### ISSUE TITLE
Function 'type' doesn't work on node version smaller than 11

### ISSUE THREAD

**Issue by JaLe29** [puppeteer/puppeteer#3818]
I implemented function `sendKeys  `using `activePage.keyboard.type(value)`.

I am using `"puppeteer": "^1.11.0"` (I tested on 1.10.0, 1.9.0 too - same behaviors).

My problem is that I am using node smaller then version 11 (node 10, node 8) type doesn't work - only the first letter is written into input.

See image (I try to write the word 'luck' - and only first letter l is written):

![image](https://user-images.githubusercontent.com/22296816/51443645-6e4e5e00-1cec-11e9-9b51-510cc7462bee.png)

What is wrong in my code? 

A code is working only when I am using node version 11. But in my project, I need to use node version 10.

Windows 10, 64b.

Thank you for any help.

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with this test script and puppeteer tip-of-tree version on Windows 7 x64:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.evaluate(() => {
      document.body.appendChild(document.createElement('textarea')).focus();
    });

    await page.keyboard.type(process.versions.node);
  } catch (err) {
    console.error(err);
  }
})();

```
![8](https://user-images.githubusercontent.com/10393198/51444731-220f1800-1d04-11e9-99d5-af7ea0d1302f.png)
![10](https://user-images.githubusercontent.com/10393198/51444732-220f1800-1d04-11e9-8827-24459ff61eb9.png)
![11](https://user-images.githubusercontent.com/10393198/51444734-22a7ae80-1d04-11e9-9da9-bfe9b93f9059.png)
