### ISSUE TITLE
page.click is not firing

### ISSUE THREAD

**Issue by imadyaici** [puppeteer/puppeteer#3819]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: MacOS Mojave
* URLs (if applicable):
* Node.js version: 11.4.0

I'm trying to scrap some data for this page https://weather.com/fr-DZ/temps/10jours/l/AGXX0383:1:AG , there is a table where I have to click on each row to fetch some additional day data and display it

![image](https://user-images.githubusercontent.com/7004223/51445632-dd857b80-1d07-11e9-9d00-f59905470a1e.png)

so I wrote this code 

```
await page.goto(https://weather.com/fr-DZ/temps/10jours/l/AGXX0383:1:AG, {
        timeout: 0,
        waitUntil: ["domcontentloaded", "networkidle0"]
    });
await page.waitFor('#twc-scrollabe > table > tbody > tr:nth-child(1)')
await page.click('#twc-scrollabe > table > tbody > tr:nth-child(1)')
await page.waitFor('tr:nth-child(3) > td.sunrise > div > span:nth-child(2)')
```

MOST OF THE TIME, when checking this with {headless: false} I see that the click doesn't happen, and I see that the browser is continuously fetching content, but if I click manually on that row the scripts continue execution normally as expected. There is other clicks under this code but once this first click happens the others fire normally.

here is all the code here https://github.com/imadyaici/weather_scraper in scraper.js

**Comment by Niceplace** [comment]
Does your click event fire any navigation / request of some sort ? I had the same kind of behavior with another internal website I was automating and when I changed my approach, it worked well. Puppeteer's docs document example of this as well: https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pageclickselector-options

Here's what I did it's in TS and it's my first draft but I guess you could adapt it to your needs :) !: 
```
export const clickNavigate = async (
  selector: string,
  selectorType: 'xpath' | 'css' = 'css',
  page: Page,
  navOptions: NavigationOptions,
  clickOptions: ClickOptions,
) =>
  Promise.all([
    waitAndClick(selector, page, selectorType, { click: clickOptions }),
    page.waitForNavigation(navOptions),
  ]);
```

Edit: oops, forgot to add my other helper, waitAndClick:

```
export const waitAndClick = async (
  selector: string,
  pageInstance: Page,
  selectorType: 'xpath' | 'css' = 'css',
  options?: {
    wait?: WaitOptions;
    click?: ClickOptions;
  },
) => {
  try {
    let elementHandle: ElementHandle;
    if (selectorType === 'xpath') {
      elementHandle = await pageInstance.waitForXPath(
        selector,
        getWaitOptions(options && options.wait),
      );
    } else {
      console.log(`About to click on ${selector} by ${selectorType}`);
      elementHandle = await pageInstance.waitForSelector(
        selector,
        getWaitOptions(options && options.wait),
      );
    }
    await elementHandle.click(options && options.click);
    console.log(`Clicked on ${selector} of ${selectorType} type`);
  } catch (error) {
    console.error(
      `[ERROR:waitAndClick]: Selector: ${selector}. Options: ${JSON.stringify(
        options,
      )}. Error: ${error}.`,
    );
    throw error;
  }
};
```

Cheers !

**Comment by imadyaici** [comment]
@Niceplace Thank you! I got the idea from your code (I didn't copy it all)
so what I did is just yo get the promise for the waitFor and apply the click on it

```
let el = await page.waitForSelector('#twc-scrollabe > table > tbody > tr:nth-child(1)', { visible: true })
await el.click('#twc-scrollabe > table > tbody > tr:nth-child(1)');
```
well, it worked fine for few times then it stopped

**Comment by Niceplace** [comment]
That's a way to do it as well, however once you get the reference to the element you can just call 'click' on it, not sure why the selector is specified. ! Are you sure the click doesn't trigger a navigation / network request of some sort ? How does this turn out:

```
let el = await page.waitForSelector('#twc-scrollabe > table > tbody > tr:nth-child(1)', { visible: true })
Promise.all([
  el.click(),
  page.waitForNavigation({ waitUntil: 'load' }),
]);
```

**Comment by imadyaici** [comment]
@Niceplace already tried this and didn't work
the solution for me was to do a while "not_clicked" loop, I had to try clicking many times until it opens and returns true, and it happens exactly like this when trying it manually.
