### ISSUE TITLE
Implement object handles

### ISSUE THREAD

**Issue by pavelfeldman** [puppeteer/puppeteer#382]
- Add `page.object(func)` that returns a new `ObjectHandle` type.
- Expose `ObjectHandle.json()` that would return result similar to present `page.evaluate`. That will allow access to the raw object handlers for non-trivial operations.
- Inherit `ElementHandle` from `ObjectHandle` if possible
- Allow object handles to be disposed, expose `evaluateOn` on the objects
- Provide support for object groups (arenas) for bulk dispose

**Comment by aslushnikov** [comment]
The `ObjectHandle` may have a `objectHandle.property('foo')` method that returns value of the property named `foo`. This will address #438.

**Comment by gajus** [comment]
> The ObjectHandle may have a objectHandle.property('foo') method that returns value of the property named foo. This will address #438.

How does one obtain the property value from the JSHandle?

```js
const totalCostElement = await page.$('.review-payment__cost-breakdown strong');

const totalCostElementTextContent = await totalCostElement.getProperty('textContent');

```

This returns `JSHandle` object.

**Comment by gajus** [comment]
Turns out you simply need to use `toString`.

This API is rather odd. Whats the reason for JSHandle abstraction in the first place?

**Comment by pavelfeldman** [comment]
@aslushnikov let's remove toString before it is misused broadly. I don't remember reviewing it btw, I remember renaming old `toString` into `jsonString`, but that was it...

**Comment by gajus** [comment]
> @aslushnikov let's remove toString before it is misused broadly. I don't remember reviewing it btw, I remember renaming old toString into jsonString, but that was it...

Whats the correct way to get the property value?

**Comment by aslushnikov** [comment]
@gajus it's [`JSHandle.jsonValue`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#jshandlejsonvalue)

**Comment by gajus** [comment]
> Returns a JSON representation of the object. The JSON is generated by running JSON.stringify on the object in page and consequent JSON.parse in puppeteer.

This description makes it in no way clear that `jsonValue` returns the value of a property.

**Comment by aslushnikov** [comment]
@gajus `jsonValue` returns a value of the object.

If you want a value of particular object property, you'd need to use both `getProperty()` and `jsonValue()`:

```js
const navigatorHandle = await page.evaluateHandle(() => window.navigator);
const uaHandle = await navigatorHandle.getProperty('navigator');
const ua = await uaHandle.jsonValue();
```

Alternatively, you can use the evaluate method:

```js
const navigatorHandle = await page.evaluateHandle(() => window.navigator);
const ua = await page.evaluate(obj => obj.userAgent, navigatorHandle);
```

**Comment by AgainPsychoX** [comment]
When do I need to call `dispose` of the handles?
