### ISSUE TITLE
Global timeout

### ISSUE THREAD

**Issue by thamerla** [puppeteer/puppeteer#3821]
Is it yet implemented? For example AWS lambda offers pay-as-you-go model and it would be cool to use it there as it is.

**Comment by aslushnikov** [comment]
Looks like a dupe of #3319 - not implemented yet.

**Comment by thamerla** [comment]
@aslushnikov any plans to implement it?

**Comment by aslushnikov** [comment]
@nonyy yep, just implemented - will be shipped in our next release on Jan, 31
