### ISSUE TITLE
While generating pdf, landscape option doesn't work

### ISSUE THREAD

**Issue by krishnakode** [puppeteer/puppeteer#3834]
### Steps to reproduce

**Tell us about your environment:**
 We are trying to generate pdf using puppeteer. Previously we had the landscape option working on Puppeteer 1.5.0 and node 8.9.4. But, after we moved around the code and updated the node and puppeteer versions to 8.15.0 and 1.11.1 respectively, the landscape option tends to generate a portrait instead of a landscape.  

* Puppeteer version: 1.11.1
* Platform / OS version: ubuntu
* URLs (if applicable):
* Node.js version: 8.15.0

_Please include code that reproduces the issue._

function generatePDF(html, options) { // options has landscape param set to true or false
      browser = await puppeteer.launch({ args: this.puppeteerArgs });
      page = await browser.newPage();
      const session = await page.target().createCDPSession();
    
      await session.send('DOM.enable');
      await session.send('CSS.enable');
      await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle2' });

      this.logger.debug('generatePDF - creating pdf buffer..');
      const buffer = await page.pdf(options);
      await page.close();
      await browser.close();
      return buffer;
}
**What is the expected result?**
generates a landscape view

**What happens instead?**
generates a portrait view

**Comment by toix** [comment]
Have you tried altering the CSS rule `@page`?
```
@page {
    size: auto;
}
```

Edit: You can use the CSS rule only for Puppeteer: 
```
page.addStyleTag(
    {'content': '@page {size: auto}'}
)
```

**Comment by OliverColeman** [comment]
I'm having the same issue. I've tried suggestions here and in #4505 and many variations and combinations thereof. Even tried explicitly setting width and height options. I cannot get puppeteer to render a PDF in landscape format. 

Puppeteer v1.17.0
Node v8.11.4

Simplest code is below, but please note that I did try the suggestions suggested by @toix and in #4505 
```javascript
      ...
      page = await this.createPage(url, { timeout, waitUntil, cookies });
      const opts = {
        landscape: true,
      };
      const buffer = await page.pdf(opts);
```

**Comment by ciupicri** [comment]
I'm having the same issue with:
 * Puppeteer version: 1.19.0 
 * Platform / OS version: Linux (Fedora 30)
 * Node.js version: 10.16.0

Even if I set the `landscape` option to true, [`page.pdf`][1] still generates a portrait oriented PDF.

[1]: https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-pagepdfoptions

**Comment by markovicboban** [comment]
The same problem here, `landscape: true` is not working...

**Comment by anx-mwutte** [comment]
+1 same here... `landscape: true` not working...

**Comment by yairvillarp** [comment]
+1 same here, landscape not working.

**Comment by mick0n** [comment]
+1 same issue for me. A workaround that works for me right now is to omit the **landscape** parameter entirely and just set width and height. Only then can I get a landscape orientation to work.

**Comment by JandosKh** [comment]
I'm using PuppeteerSharp v1.20.0. I confirm that landscape option doesn't work. Explicitly setting page width & height didn't work also. However,  using page.addStyleTag worked for me. You can try
page.addStyleTag(
    {'content': '@page { size: A4 landscape; }'}
)

**Comment by guigusman** [comment]
Thanks @JandosKh! This worked for me.

Just to complement the solution, in case someone run into the same issue, at first it was not working for me because I was running the command before loading the page. Make sure you run the addStyleTag command after loading it.

Thanks

**Comment by ghost** [comment]
We had that issue today, but we got it working by calling `await page.emulateMedia('screen');` before generating the PDF. After that, `landscape : true` was working.

**Comment by StevenVerheyen** [comment]
Seems to be working fine for me. The code that I used:
```
const browser = await puppeteer.launch();
const page = await browser.newPage();
const options = {
  path: 'pdf/filename.pdf',
  format: 'A0',
  printBackground: true,
  landscape: true,
};

await page.goto('https://somewebsite.com', { waitUntil: 'networkidle2' });
await page.pdf(options);
await browser.close();
```

This generates a landscape oriented PDF for me. If I leave out the `landscape: true` in the options const, I get a portrait oriented PDF.

What I noticed is, that if you provide `width` and `height` in the options, the landscape is not taken into account. However, when using `format`, the orientation is working just fine :)

Versions:
- Puppeteer: 5.2.1
- Node: 13.7.0 (express back-end)
- Node Express: 4.16.1
- Platform: macOS Catalina (10.15.5)

**Comment by whapply** [comment]
什么时候fixed it ??????

**Comment by secretpray** [comment]
_tested - working method:_

def to_pdf
  url = request.url.remove("/to_pdf.pdf")
  Grover.new(url, format: 'A3', **emulate_media: 'screen', landscape: true** ).to_pdf
end

**Comment by B1ackDrag0n** [comment]
Good morning, everyone

**CSS**
```
@page {
    size: A4 landscape !important;
}
```

**Node.js**
```
const browser = await Puppeteer.launch({ headless: 'new' });
const page = await browser.newPage();
await page.setContent(HTML, { waitUntil: 'domcontentloaded' });
await page.emulateMediaType('screen');
const pdf = await page.pdf({
    path: pdf_filename,
    margin: { top: '0px', right: '0px', bottom: '0px', left: '0px' },
    printBackground: true,
    format: 'A4',
    landscape: true
});
await browser.close();
```

I hope this helps.

**Comment by node-schedule-approximat** [comment]
> Have you tried altering the CSS rule `@page`?
> 
> ```
> @page {
>     size: auto;
> }
> ```
> 
> Edit: You can use the CSS rule only for Puppeteer:
> 
> ```
> page.addStyleTag(
>     {'content': '@page {size: auto}'}
> )
> ```





https://reactdev.space/questions/what-is-the-best-way-to-create-and-save-a-pdf-using-this-data
