### ISSUE TITLE
[Feature request] Get cursor image for current mouse position

### ISSUE THREAD

**Issue by FremyCompany** [puppeteer/puppeteer#3838]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.11.0
* Platform / OS version: any
* URLs (if applicable): n/a
* Node.js version: 11.5

**What steps will reproduce the problem?**

1. page.mouse().move(x, y)
2. // how do I verify that the cursor at this location was properly changed to a "hand pointer" cursor?

**What is the expected result?**

I would like to be able to assert that the OS cursor would be changed to a hand cursor at the current mouse location (or some other custom cursor)

**What happens instead?**

It's not possible to detect that in the general case, because getComputedStyle doesn't verify that the image you specified was actually decoded (it might have 404ed) and furthermore getComputedStyle only works within the context of a single frame and you might hover content from another frame at that mouse position.

**Comment by aslushnikov** [comment]
> Get cursor image for current mouse position

@FremyCompany Cursor rendering is done by OS; OS doesn't have a chance to render cursor in Chrome Headless (and in headless environments in general).

> How do I verify that the cursor at this location was properly changed to a "hand pointer" cursor?

The best I can suggest is:
- use [`'mouseover'`](https://developer.mozilla.org/en-US/docs/Web/Events/mouseover) event for the element to track if it was hovered
- use [CDP Protocol](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-class-cdpsession) and its [CSS domain](https://vanilla.aslushnikov.com/#CSS) to inspect the applied CSS.

But IMO this is too involved and doesn't worth the hassle.

Technically, we can plumb information about current cursor style from-inside the guts of Blink rendering engine, but this effort requires strong justification, e.g. in a form of community demand. I'll close this for now; will be happy to reopen if it gets popular.
