### ISSUE TITLE
How to wait for jQuery page reload?

### ISSUE THREAD

**Issue by AlonsoK28** [puppeteer/puppeteer#3843]
This is my script

```
(async () => {
          const puppeteer = require('puppeteer');
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          await page.type("#input1", "Hi");
          await page.type("#input2", "there");
          await page.select("#body > select", "1"); //this line cause a page kind Post (see image) and page  
reloads
          //I can´t reach this point because an error
});
```

The behavior of the page is that a html `<select>` element triggers a **"kind of reload" (possibly using jquery reload or jquery $post)** on the page and which I can not wait since I get the following error

`Error: Protocol error (Runtime.callFunctionOn): Can not find context with specified id`

**I tried this but doesn't work**
```
            await page.select("#body > select", "1").then(()=>{
              page.waitForSelector("#body > select", "1");
              console.log("Now is safe to continue");
            });
```
```
const [response] = await Promise.all([
              await page.waitForNavigation(),
              await page.click("#body > select", "1"),
              console.log("Now is safe to continue");
```
In the devtools console I see something like this in the `response/request` when element is selected

![image](https://user-images.githubusercontent.com/37458700/51774297-652c0b00-20b7-11e9-9ab0-ca31f8965d41.png)

How can I wait with `Puppeteer` until the page is in a `safe/stable` state  up to page request is ended?

Could you suggest a strategy to follow?

**Comment by Mpsrolim** [comment]
how did you solve it?
