### ISSUE TITLE
Pdf generation was too slow.

### ISSUE THREAD

**Issue by samuelrego** [puppeteer/puppeteer#3847]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:   "puppeteer": "^1.11.0",
* Platform / OS version: windows 10  or docker (latest version) (tried in both)
* URLs (if applicable):
* Node.js version: 10.15

**What steps will reproduce the problem?**

I am genrating PDF by giving some html content. when i start my  service for first time it takes 14 seconds to generate pdf. then next time onwords it takes 8 seconds. it was very slow. is there any solution to boost up the pdf genartion process . 

_Please include code that reproduces the issue._

  
    const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
    const page = await browser.newPage();
    await page.setContent(getReactHtml(req), { waitUntil: 'networkidle0' });
    await page.emulateMedia('screen');
    const data = await page.pdf({
      format: 'Letter',
     printBackground: true
    });
    browser.close();
    return data;

**What is the expected result?**
  i want pdf to be generated with 3 to 4 seconds. it takes so much time

**What happens instead?**
 it taking too much time to generate the pdf

**Comment by aslushnikov** [comment]
@samuelrego are you sure the whole time is spent in pdf generation? It could be that `page.setContent` takes quite some time - certain websites get a lot of time to load all the resources.

Other than that, there are many factors that define PDF rendering time. I'd speculate that PDF total size affects drastically the total time, as well as the overall speed of host environment.

It's hard to infer anything else from your description. I'd try:
- measure time for `page.setContent` and `page.pdf` separately and see who's the outlier
- compare `page.pdf` time to the `save as pdf..` dialog time in chrome
- check how slow/fast is the host environment; maybe just bumping specs will help

If indeed PDF generation takes significant time, I'd file this as a bug upstream to https://crbug.com/new - Chromium PDF team might be able to help. 

Hope this helps.

**Comment by 1-2-3** [comment]
I try this:
`const page2 = await browser.newPage();
      page2.setContent(`<html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Document</title>
      </head>
      <body>
        <div>Simple Test</div>
      </body>
    </html>`);
      logger.info("Rendering pdf2 ..");
      data = await page2.pdf(opts.pdf);
      logger.info("Rendering pdf2 done");`

Output:
2019-07-20T02:08:34.187Z - info: [render-core.js] Rendering pdf2 ..
2019-07-20T02:08:41.608Z - info: [render-core.js] Rendering pdf2 done

Rendering pdf takes 7 sec!!

**Comment by 1-2-3** [comment]
I try this:
const page2 = await browser.newPage();
      page2.setContent(`<html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Document</title>
      </head>
      <body>
        <div>Simple Test</div>
      </body>
    </html>`);
      logger.info("Rendering pdf2 ..");
      data = await page2.pdf(opts.pdf);
      logger.info("Rendering pdf2 done");

Output:
2019-07-20T02:08:34.187Z - info: [render-core.js] Rendering pdf2 ..
2019-07-20T02:08:41.608Z - info: [render-core.js] Rendering pdf2 done

Rendering pdf takes 7 sec!!

**Comment by louis123562** [comment]
I can confirm that executing the page.pdf() takes up to 7 Seconds.

![grafik](https://user-images.githubusercontent.com/36068395/65600292-292bab80-dfa0-11e9-8f76-0d11c8f23e20.png)

The content i set is pure HTML and is about 15 Pages.

**Comment by 1-2-3** [comment]
I do more test, chrome 77 take 7 sec, but chrome 76 less than 1 sec!!!

**Comment by louis123562** [comment]
Do you mean chromium? Mine is at 3.5.2

**Comment by 1-2-3** [comment]
> Do you mean chromium? Mine is at 3.5.2

used chrome by "executablePath" param

**Comment by milczarekIT** [comment]
Has this problem been resolved? I am still facing problem with slow pdf generation

**Comment by louis123562** [comment]
What CPU are you using? We moved to a new server and generating a large PDF (20 Pages) is like 250 to 500ms only.

I also refactored my code like the following; adding an timeout of 1 second for finishing rendering of FA-Icons. Of course the whole progress then takes like 1250 to 1500ms.

```
const fs = require('fs')
const path_to_node = __dirname;
const puppeteer = require('puppeteer');

let html_filename = process.argv[2];
let css_filename = process.argv[3];
let filepath_with_name = process.argv[4];

async function timeout(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

(async () => {

    const browser = await puppeteer.launch()
    const page = await browser.newPage()

    const html = fs.readFileSync(path_to_node + "/temp/" + html_filename, 'utf8')
    const css = fs.readFileSync(path_to_node + "/temp/" + css_filename, 'utf8')

    await page.setContent(html)
    await page.addStyleTag({ path: path_to_node + "/css/style.css" })
    await page.addStyleTag({ content: css })
    await page.addScriptTag({ path: path_to_node + "/js/all.min.js" })

    //Wait for Font-Awesome Icon rendering
    await timeout(1000)
    await page.pdf({
        path: filepath_with_name,
        format: 'A4',
        landscape: true,
        printBackground: true
    })

    await browser.close()
})()
```

Probably you can give it a try on another / faster machine?

**Comment by milczarekIT** [comment]
@louis123562  thank you for your answer. For 20 pages it works really smooth. I need to generate a pdf report with 2000 pages.

**Comment by louis123562** [comment]
mmh... you should have a good machine for that too, because the rendering is done by CPU only. I guess enough RAM is needed as well.

Did you try to generate in parts, like 100 pages per PDF and combine thos after it with FPDI maybe?

**Comment by milczarekIT** [comment]
`pageRanges` did not resolve the problem. Looks like generating pdf with 500+ pages with pageRanges ('1-4') and with default config take the same amount of time.

I am not able to split html before rendering, because my data is dynamic with a lot of entries of data, so I am not able to predict where is the `page break`

**Comment by luciomr** [comment]
1-2-3 commented that using Chrome 76 he went [from 7 seconds to 1 second](https://github.com/puppeteer/puppeteer/issues/3847#issuecomment-535762288) in the response. 

I tested that locally and it didn't dramatically speed up the call to page.pdf()  (html of about 1 MB generating 58 pages in my case). 
It went from 7.5 secs to 6.5 - 7 secs. Not the 1-second delay promised. 

Here's how I tested it: 

- I got the [equivalent versioning from the page of the related package chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda#versioning)
- I installed  puppeteer 1.17.0 which downloaded Chromium 76.0.3803.0 (r662092).

**Comment by kmr-pawan** [comment]
> @louis123562 thank you for your answer. For 20 pages it works really smooth. I need to generate a pdf report with 2000 pages.

@milczarekIT you got any alternate solution, i also facing the same issue, need to generate 2000 pdf pages from html, but taking more time using puppeteer

**Comment by haoxi911** [comment]
Actually `wkhtmltopdf` is faster than `puppeteer` on converting HTML to PDF. I need to create 1000 labels in one single PDF file, `wkhtmltopdf` took about 7 seconds, while `puppeteer` took 30 seconds.

**Comment by daviatorstorm** [comment]
I saw a new startup came up called Pritset. It generates  PDF from DOCX. Maybe that could be helpful
