### ISSUE TITLE
Documentation site pptr.dev not keyboard accessible

### ISSUE THREAD

**Issue by dandv** [puppeteer/puppeteer#3849]
While perusing the documentation at https://pptr.dev in Chrome, I've noticed that almost any keyboard interaction focuses the search input. This is handy, but also breaks PgUp/PgDn, which have no reason to give the focus to a one-line search box.

Also, up/down arrow keys don't scroll, and Space only scrolls if you first click outside the content div.

As a result, one can't use the keyboard to simply scroll through the documentation.

**Comment by aslushnikov** [comment]
@dandv thanks for the bugreport; fixed in v0.3.5 of pptr.dev - it'll deploy shortly.
