### ISSUE TITLE
Issue with disable web security in Chromium and Chrome in Mac

### ISSUE THREAD

**Issue by abhishekgahlot** [puppeteer/puppeteer#3852]
I am using puppeteer to open an iframe in browser which has allowed only same origin. So if i open chrome with flag `--disable-web-security`, The embedding of iframe works.
But here is the problem, If i use chrome instance of my Mac with params

This works 

 ```
 const browser = await puppeteer.launch({
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    ignoreDefaultArgs: true,
    args: [
      "--disable-web-security",
      "--user-data-dir",
      "--enable-usermedia-screen-capturing",
      "--allow-http-screen-capture",
      "--start-fullscreen",
      "--kiosk",
      "--disable-infobars"
    ],
    headless: false,
  });
```

This doesn't because it uses Chromium. 

```
  const browser = await puppeteer.launch({
    ignoreDefaultArgs: true,
    args: [
      "--disable-web-security",
      "--user-data-dir",
      "--enable-usermedia-screen-capturing",
      "--allow-http-screen-capture",
      "--start-fullscreen",
      "--kiosk",
      "--disable-infobars"
    ],
    headless: false,
  });
```

Even If i change the first part of using chrome with different dir it doesn't work. 
For eg this doens't work either
```
const browser = await puppeteer.launch({
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    ignoreDefaultArgs: true,
    args: [
      "--disable-web-security",
      "--user-data-dir=/tmp/crm",
      "--enable-usermedia-screen-capturing",
      "--allow-http-screen-capture",
      "--start-fullscreen",
      "--kiosk",
      "--disable-infobars"
    ],
    headless: false,
  });
```

I tried running chromium that comes with puppeteer directly using command:
`./Chromium --disable-web-security --user-data-dir`

and opened the page manually which has iframe from different origin. I still got an error:
`Refused to display 'url' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

Wondering why disable web security is not working with pupeeteer. I am using

* Puppeteer version: 1.11.0
* Platform / OS version: Mac OS Mojave
* Node.js version: 10.6.0

**Comment by kanesharan** [comment]
same here :(

**Comment by speeddragon** [comment]
Any idea why it works differently on Chromium with Puppeteer ? Using the command bellow works.

```
open -n -a /usr/local/lib/node_modules/puppeteer/.local-chromium/mac-662092/chrome-mac/Chromium.app --args --user-data-dir="/tmp/chrome_dev_test" --allow-file-access-from-file
```

**Comment by jeffreyclu** [comment]
any update?

**Comment by Nerdion** [comment]
Yeah. Well, you can set a cookie called SameSite:none;
[Cookie Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite)

This will enable to completely disable security using,
page.SetCookie method
[Pupeteer Docs Here](https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-pagesetcookiecookies)

**Comment by xgqfrms** [comment]
# `--disable-web-security` flag

**Comment by LeeSwagger** [comment]
Hi, this works for me:

```
const browser = await puppeteer.launch({
  args: [
     '--disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure'
  ]
})
```

**Comment by grigoriy-didorenko** [comment]
Same happens for me

**Comment by OrKoN** [comment]
I wonder if it's still an issue in the latest version?
