### ISSUE TITLE
How to use --disk-cache-dir

### ISSUE THREAD

**Issue by NathanLi** [puppeteer/puppeteer#3864]
I want my disk cache dir. But don't work:

```javascript
const browser = await puppeteer.launch({
    args: [
        '--no-sandbox', '--disable-setuid-sandbox',
        '--disk-cache-dir=/Temp/browser-cache-disk'
    ],
});
```

**Comment by kblok** [comment]
@NathanLi it might be some permissions issue. `./Temp/browser-cache-disk` works for me.

**Comment by NathanLi** [comment]
@kblok It has nothing to do with permissions。I close headless, it is work now.

```javascript
browser = await puppeteer.launch({
    headless: false,
     args: [
        '--no-sandbox', '--disable-setuid-sandbox',
        '--disk-cache-dir=./Temp/browser-cache-disk',
    ],
});
```
I used `./Temp/browser-cache-disk`, but if don't `headless: false`, it still doesn't work.

My os is `macOS 10.14`.

**Comment by mjschranz** [comment]
@NathanLi @kblok I use the same settings but when I try the follow to check if the responses are loaded from cache, it's always returning false. Seems like something is broken?
```
      page.on("response", (response) => {
        const prefix = response._fromDiskCache ? "[disk] " : "[network] ";
        console.log(`${prefix}${response.url()}`);
      });
```

**Comment by KristofferBerg** [comment]
It seems to be ignoring cache if interception is defined (at least on requests as this link suggest: )
https://github.com/puppeteer/puppeteer/issues/2497
