### ISSUE TITLE
Site rendering problem

### ISSUE THREAD

**Issue by MadGhigno** [puppeteer/puppeteer#3868]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.11.0
* Platform / OS version: GNU/Linux Mint 19 Cinnamon
* URLs (if applicable):
* Node.js version: v10.10.0

Trying to open this link https://www.ituran.com/ituranfront/en/about-ituran/investor-relations/press-releases/ returns a completely different code than opening the page in Chrome desktop. The same happens trying to open the page with Chrome in headless mode:

/opt/google/chrome/chrome --headless --disable-gpu --dump-dom https://www.ituran.com/ituranfront/en/about-ituran/investor-relations/press-releases/ > index.html

**What is the expected result?**
I expect to get the same html code from both puppeteer and Chrome

**What happens instead?**
The code is different, the html code returned by puppeteer doesn't show the expected page content

**Comment by aslushnikov** [comment]
@MadGhigno this website is doing automation detection; counteracting detections fall outside of the scope of the project.
