### ISSUE TITLE
PDF Blank 

### ISSUE THREAD

**Issue by chasen-bettinger** [puppeteer/puppeteer#3869]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: AWS EC2 (CentOS)
* Node.js version: 6.14.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```
Promise.resolve().bind @
... create browser, generate html, etc.
.then (html_template)->	
	page.goto "data:text/html,#{html_template}", { waitUntil: ['domcontentloaded', 'networkidle2'] }
.then ->
	page.emulateMedia 'screen'
.then ->
	page.waitFor('*')
.then ->
	page.pdf options
.then (pdf_buffer)->
        // upload pdf_buffer
```
**What is the expected result?**

The PDF is the HTML content. 

**What happens instead?**

The PDF is blank. I have entered the string that page.goto uses in its first argument into my browser and it looks correct. However, when I use this code, the uploaded pdf is blank. https://i.imgur.com/dbc1znU.png

**Comment by chasen-bettinger** [comment]
Changing goto to setContent and instead of including the data:text/html part and only including the html_template resolved this issue. I'm not exactly sure why at this moment in time.

**Comment by mathiasgheno** [comment]
I'm using axios in my front-end and I forget set the responseType. 

Maybe this help somebody. 

```js
axios('https://url', { responseType: 'blob' }).then(...)

**Comment by mikilukasik** [comment]
this helped me: https://github.com/puppeteer/puppeteer/issues/3659
