### ISSUE TITLE
Why is it necessary to download two javascript interpreters for one javascript library?

### ISSUE THREAD

**Issue by v217** [puppeteer/puppeteer#387]
It would be more aesthetically pleasing, if the builtin javascript interpreter would be enough to run puppeteer. Just a thought. Of course nodejs has just a few MBs.

**Comment by benjamingr** [comment]
There is no reasonable way to reuse V8 from Chrome in Node or vice versa - it would introduce a lot of maintenance problems. In addition if you'd like to pursue this anyway - you can open an issue at Node or Chromium (puppeteer is just a control API for Chromium based browsers).

**Comment by Garbee** [comment]
Built in JS interpreter is coming from where?

**Comment by v217** [comment]
@Garbee chromium. The point is: pupeteer is chromium headless specific. In order to use it you have to get familiar with nodejs, how to install packages etc...  Not to mention you have to update two software projects nodejs and chromium. The only reason, why I installed nodejs is to use an easy to use api for chromium headless.

**Comment by v217** [comment]
Right now pupeteer is the only user friendly/easy and well documented official api to chromium headless. So it should work out of the box without installing extra software. Just an opinion.

**Comment by Garbee** [comment]
It can't work "out of the box" since the library is built as node library. It technically isn't feasible to do it any other way.

**Comment by v217** [comment]
@Garbee Ok, Thanks I am not familiar with the technical restrictions. Probably most users of headless also use nodejs.
