### ISSUE TITLE
How to stop error UnhandledPromiseRejectionWarning Timeout Exceeded?

### ISSUE THREAD

**Issue by orlandobloom19** [puppeteer/puppeteer#3870]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 10.15.0

**What steps will reproduce the problem?**

_This is my code._

----------------------------------------------------
const puppeteer = require('puppeteer');
(async() => {
    const browser = await puppeteer.launch({ headless: false, args: ['--no-sandbox', '--disable-setuid-sandbox']});
    const page = await browser.newPage();
	await page.setViewport({ width: 1024, height: 400 });
    await page.goto('http://abc.com', { timeout: 30 });

    const articles = await page.evaluate(() => {
        let titleLinks = document.querySelectorAll('h3.knswli-title > a');
        titleLinks = [...titleLinks];
        let articles = titleLinks.map(link => ({
            title: link.getAttribute('title'),
            url: link.getAttribute('href')
        }));
        return articles;
    });

    await browser.close();
	module.exports = articles;
})();

----------------------------------

**What is the expected result?**
I wish the code can run completely (from first line to the last line) even if the timeout error is found.

**What happens instead?**
Once the timeout is reached, it shows the error: "UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30ms exceeded...."   and my app is stopped. Then I must Ctrl + C and type command "node app.js"  again

**Comment by vsemozhetbyt** [comment]
You need to add error catching:
```js
'use strict';

const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({ headless: false, args: ['--no-sandbox', '--disable-setuid-sandbox']});
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1024, height: 400 });
    await page.goto('http://abc.com', { timeout: 30 });

    const articles = await page.evaluate(() => {
      let titleLinks = document.querySelectorAll('h3.knswli-title > a');
      titleLinks = [...titleLinks];
      let articles = titleLinks.map(link => ({
        title: link.getAttribute('title'),
        url: link.getAttribute('href')
      }));
      return articles;
    });

    module.exports = articles;
  } catch (err) {
    console.error(err.message);
  } finally {
    await browser.close();
  }
})();
```

**Comment by orlandobloom19** [comment]
Thanks a lot vsemozhetbyt, you're a hero.
