### ISSUE TITLE
TS: `waitForSelector` should only resolve `null` when called with `hidden: true

### ISSUE THREAD

**Issue by SimonSchick** [puppeteer/puppeteer#3877]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12
* Platform / OS version: MacOS
* URLs (if applicable):
* Node.js version: 11.5

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
`const el = await page.waitForSelector(`some-selector`);`

2.
`console.log(el.getProperty('somewhat'))`

3.
**What is the expected result?**

No error

**What happens instead?**

`error TS2531: Object is possibly 'null'`.

Ideally an overload should be added specifically checking if `hidden: true`, otherwise we have to add annoying null assertions where none are needed.

**Comment by SimonSchick** [comment]
Worth noting that the official types are somewhat inferior to the DT ones, see uses of `Object` etc.

**Comment by SimonSchick** [comment]
Closing in favour of https://github.com/GoogleChrome/puppeteer/issues/3878

**Comment by jemunk** [comment]
What is the status of this? The year is 2024 and we still need to test if the result of waitForSelector returns null. 
It could be so nice, that the hidden: true option, was refactored into its own method, like waitForHiddenSelector, and only let this one return null.

**Comment by alamothe** [comment]
This can be resolved easily with overloading:
```tsx
    waitForSelector<Selector extends string>(selector: Selector, options?: {
        visible?: boolean;
        hidden?: false;
        timeout?: number;
    }): Promise<ElementHandle<NodeFor<Selector>>>;
    waitForSelector<Selector extends string>(selector: Selector, options?: {
        visible?: boolean;
        hidden: true;
        timeout?: number;
    }): Promise<ElementHandle<NodeFor<Selector>> | null>;
