### ISSUE TITLE
TS: New typings inferior to former @types ones

### ISSUE THREAD

**Issue by SimonSchick** [puppeteer/puppeteer#3878]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12
* Platform / OS version: Irrelevant
* URLs (if applicable):
* Node.js version: Irrelevant

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
Update `puppeteer`
2.
Check typings.
3.
They are worse.

**What is the expected result?**

Typings should be at least at DT quality.

**What happens instead?**

- Various types have become `Function`
  -  Callbacks in `waitFor/evaluate`-ish functions.
 - Various types have come `Object`
   - Often incorrect such as `jsonValue` or `json` (should be 'unknown' instead)
   - Used instead of more precise dictonary object when used for `headers` and `waitFor` options.
- Various specific overloads are missing that make requires less type assertions.
  - See #3877

Both types should not be used as they are extremely broad.

FYI I consider this a breaking change as I cannot easily revert to DT typings without explicitly downgrading puppeteer, it also broke our builds.

**Comment by aslushnikov** [comment]
@SimonSchick thank you for letting us know and sorry for breaking you. We'll push a 1.12.1 without d.ts file shortly

**Comment by SimonSchick** [comment]
Obviously: I *really* appreciate you adding those, it's great they we don't need to maintain them separately anymore, but they need some fine tuning :)

Also worth noting is that typings for 

![image](https://user-images.githubusercontent.com/3259089/52141052-6609f300-2609-11e9-95cf-71d4a2abe20b.png)

would also be nice :)

**Comment by SimonSchick** [comment]
You might want to include https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer/puppeteer-tests.ts as some sort of test baseline.

**Comment by JoelEinbinder** [comment]
They are included and all passed at at https://github.com/GoogleChrome/puppeteer/blob/master/utils/doclint/generate_types/test/test.ts

Seems like there is some untested functionality though. If you could sending a PR adding failing code to that file (just leave it commented out) it would be super helpful!

**Comment by SimonSchick** [comment]
Ah yea, I didn't see it there, and yea the tests are far from complete, I will see if I get around to it.

**Comment by aslushnikov** [comment]
1.12.1 is out now with removed `index.d.ts` file. I'll keep this issue open to track progress on making our generated `index.d.ts` better and maybe eventually ship them again.

**Comment by SimonSchick** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32723, I added a few extra tests, should help you a bit.

Also, it seems your generated generated some interfaces multiple times, see `PageMetricsPayload`

**Comment by SimonSchick** [comment]
Going to be devils advocate: at this point I think it would be easiest to just port puppeteer to TS than invest further work into the types generator for adding overloads and such.

In the end every contributor needs to know TS to write the doctags anyways.

**Comment by JoelEinbinder** [comment]
I don't see how switching to TypeScript helps to solve any of these problems. TypeScript's generated d.ts file is not going to be higher quality than the one I'm generating.

**Comment by SimonSchick** [comment]
@JoelEinbinder the main pain point I see here will be specifying overloads for `waitFor`, especially for conditional return types.

I've tried to find out how to specify those via JSDoc but haven't found a way to make this work.

**Comment by pocesar** [comment]
weak typings generates errors in builds, that's the whole point of the compiler barking at your loose code. if puppeteer code doesn't account for strict parameters, it will indeed generate just-as-weak typings, even if the codebase is converted to TS.
non-generics (any, unknown, never) should be seldomly used in a consumable library with such a big API surface. the point of well-thought-out interfaces is that, if it compiles, it'll most likely work, but being typed, by itself, guarantees nothing (ahem, Java)
