### ISSUE TITLE
Is Safari experimental planned given the recent FF announcement?

### ISSUE THREAD

**Issue by AndreasGalster** [puppeteer/puppeteer#3879]
It would be great to clarify whether there is a chance that the Puppeteer API is also going to be introduced for testing via Safari, given that Firefox experimental was recently announced? 

Knowledge about the Puppeteer roadmap would help in making decisions for considering it for cross browser testing in the future. Is this something under consideration?

**Comment by aslushnikov** [comment]
> It would be great to clarify whether there is a chance that the Puppeteer API is also going to be introduced for testing via Safari, given that Firefox experimental was recently announced?

@AndreasGalster we're interested in supporting WebKit and looking into it.

**Comment by jperl** [comment]
In case anyone has not seen yet, Playwright has WebKit support https://github.com/microsoft/playwright 🔥🔥🔥
