### ISSUE TITLE
puppeteer stops working with some https URLs

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#3880]
* Puppeteer version: 1.12.0-post (chromium_revision 624487)
* Platform / OS version: Windows 7 x64
* URLs (if applicable): https://example.org/, https://example.net/, https://example.com/
* Node.js version: 11.9.0

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');
  } catch (err) {
    console.error(err);
  }
})();
```
```
Error: net::ERR_CONNECTION_CLOSED at https://example.org/
    at navigate (puppeteer\lib\FrameManager.js:101:37)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  -- ASYNC --
    at Frame.<anonymous> (puppeteer\lib\helper.js:108:27)
    at Page.goto (puppeteer\lib\Page.js:662:49)
    at Page.<anonymous> (puppeteer\lib\helper.js:109:23)
    at main (test.js:12:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```
Error page in the browser window: `ERR_CONNECTION_CLOSED`.

The same URLs in the desktop browser are OK. Other URLs (google, Github etc) in the puppeteer browser are also OK.

Can anybody reproduce?

**Comment by vsemozhetbyt** [comment]
`http` protocol pages are also OK.

**Comment by orlandobloom19** [comment]
I am not sure , I guess it's because of httpS

**Comment by aslushnikov** [comment]
@vsemozhetbyt fancy, I can repro on OSX.

**Comment by vsemozhetbyt** [comment]
See also: https://github.com/GoogleChrome/puppeteer/issues/3893

**Comment by bdrtsky** [comment]
I can confirm and reproduce this. Not sure what is happening here?

**Comment by pietmichal** [comment]
The version of Chromium used in the current version of puppeteer reports that the page is fetched using "http/1.0" or "http/1.1" instead of "h2" protocol. In my case, the connection reset happens when opening a localhost website that uses http/2 served through node v8. Local page using node v9 is  reported as "http/1.0".

**Comment by redders6600** [comment]
Can repro on linux.

**Comment by vsemozhetbyt** [comment]
This seems fixed in https://github.com/GoogleChrome/puppeteer/pull/3909

**Comment by aslushnikov** [comment]
@vsemozhetbyt thanks! Pushed v1.12.2 to address this.

**Comment by mikaelgramont** [comment]
Thanks for the fix (which I confirm as well), much appreciated.

**Comment by gselsidi** [comment]
Anybody know how to handle this error? I'm still noticing it in some of my tests I can't reproduce it but I would like the test to fail, but it seems puppeteer just waits and waits until it gets a response! Which sometimes takes upwards to 10 minutes!!

**Comment by arcesino** [comment]
Same here. I have a bunch of tests that opens HTTP URLs and some of them are randomly failing. Any chance this could be related with the number of browser instances being run at the same time?  I use a browser instance per test and my tests run concurrently which means that I commonly have from 10 to 20 browser instances running at the same time

**Comment by avalarh** [comment]
The issue is present for me in the latest version

**Comment by JaiRai0304** [comment]
The issue is  present in 19.7.5 version of Puppeteer as well.
