### ISSUE TITLE
I only need to crawl the DOM, so should I use:   waitUntil: 'domcontentloaded'  ?

### ISSUE THREAD

**Issue by orlandobloom19** [puppeteer/puppeteer#3881]
I only need to crawl the DOM, so should I use:   waitUntil: 'domcontentloaded'  ?
Is there any other similar options ?
waitUntil: 'domcontentloaded' seems to have : Timeout: 30000ms , so sometimes I get error of Timeout Exceeded.

**Comment by aslushnikov** [comment]
> I only need to crawl the DOM, so should I use: waitUntil: 'domcontentloaded' ?

@orlandobloom19 yeah that's the right one to use.

> so sometimes I get error of Timeout Exceeded.

This might happen if server didn't stop sending document body.
