### ISSUE TITLE
In memory executable path

### ISSUE THREAD

**Issue by thamerla** [puppeteer/puppeteer#3884]
I would like to read executable from AWS s3 and then use it in puppeteer. Is it possible to use it from memory or do I have to write the exe to /tmp filesystem (which is quite a nonsense)?

**Comment by aslushnikov** [comment]
> Is it possible to use it from memory or do I have to write the exe to /tmp filesystem (which is quite a nonsense)?

@nonyy this sounds more like a linux / aws question to me. I'm not aware of any way to run binary right away from memory, but I'd probably ask on StackOverflow.
