### ISSUE TITLE
Allow installing Chrome instead of Chromium

### ISSUE THREAD

**Issue by benjamingr** [puppeteer/puppeteer#389]
A big selling point of puppeteer is how easy it is to use it - it requires no installations of Chromium to be present beforehand or configuring a path.

It would be great if we could get the same ease of use for Chrome itself (rather than chromium) optionally. Right now while Chromium installation is automatic but Chrome has to be manual and each user would have to repeat the code of downloading and installing it every single time.

I realize that there might be some people who object to this (since Chrome itself isn't open source but Chromium is) but I'm definitely willing to pay the price to opt-into automatic Chrome installation. 

I think the option would be great for all of us who want to test Chrome (what our users are actually using) or need a feature Chrome has but Chromium doesn't (like video playback ;) )

**Comment by Garbee** [comment]
Automatic installation can't be done since it requires adminstration privileges.

You can use Chrome just fine, once support lands in builds. Right now puppeteer is dogfooding some of the latest API additions and changes.

Remember, the project isn't yet stable. You are playing with pre release software. Part of the price currently is a little bit of inconvenience.

**Comment by benjamingr** [comment]
> Remember, the project isn't yet stable. You are playing with pre release software. Part of the price currently is a little bit of inconvenience.

I'm perfectly aware of that, I was trying to make a suggestion that can help people once it becomes stable :) 

I'm fine with requiring `sudo npm install -g` as I'm running this in a container/vm anyway in this case.

----

Random question: if I find a bug that causes a page crash in Chrome with Puppeteer (Version 62.0.3190.0 (Official Build) canary (64-bit)) - where do I report it? (Chrome? Here?)

In particular, this question is about a feature that does not exist in Chromium but does in Chrome.

**Comment by Garbee** [comment]
Ref #244 for reducing the number of Chromium downloads on systems with many projects using the library.

As far as "where to report", I can't answer based off the information you've provided. There is no context with that question and information. I will say though, report it here and if it needs to get back to Chromium internally either we'll ask you to report it there or someone on the team will file an issue on your behalf there.

**Comment by Garbee** [comment]
General rule of thumb though, if it is a problem *in Chrome or Chromium* report it upstream. If it is a problem with using this library and how it functions, report here.

**Comment by benjamingr** [comment]
@Garbee I just realized it's not really possible to install Chrome Canary in a docker container since apparently there is no Canary linux release channel.

Is there anything I can do about it or does that mean Puppeteer is off limits for the next few months until stable catches up?


(is  "https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb" good enough?)

**Comment by Garbee** [comment]
Dev channel may be good enough. But this is still dogfooding and driving API modifications. So even if Dev works now updates may cause it not to work. Dev typically is updated once or twice a week. But, depending on how badly you need something somewhat stable that could be a problem.

**Comment by joakimgrr** [comment]
@benjamingr I'm currently running Chrome Dev (62.0.3178.0) with puppeteer successfully. 

My use case is pretty simple though (basically just creating a browser with multiple tabs and using the page.waitForFunction method) so hard to say how well it works all-around, but at least on this level everything seems ok :)

**Comment by benjamingr** [comment]
Yes, thanks, we got it working with the dev channel on linux under docker. This was more about:

 - Puppeteer is about ease of access, an easier way to use chrome would be really helpful as Chromium doesn't work out of the box with many websites.  
 - I was not sure the dev channel is good enough (and indeed, Garbee told me it's not) - so at the moment it looks like using Chrome is not officially supported at all until the API stabilizes.

**Comment by aslushnikov** [comment]
You can point to existing chrome, but we can't install it automatically.

**Comment by benjamingr** [comment]
@aslushnikov why?

**Comment by Garbee** [comment]
@benjamingr That would require root privileges during the install process which we don't want to ask for. Will a node post install script even prompt for user input or just eat it and try to move on when the script is paused?

Installing Chrome as a system package is not something this package should concern itself with. That is an implementation detail that is up to users to decide if they want to go that route.

**Comment by aslushnikov** [comment]
@benjamingr Chrome requires users to sign a license prior to download.

**Comment by monkpit** [comment]
@Garbee Why can protractor download chromedriver binary with their `webdriver-manager update` command?
