### ISSUE TITLE
Launch option handleSIGHUP doesn't work for child processes (chromium instances)

### ISSUE THREAD

**Issue by matheusb-comp** [puppeteer/puppeteer#3895]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Linux Mint 19 (Ubuntu 18.04 LTS)
* Node.js version: 11.9.0

**What steps will reproduce the problem?**

1. Make a script that launches `puppeteer` with the `handleSIGHUP: false` [option](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-puppeteerlaunchoptions)
1.1 The script will spawn some chrome processes
![screenshot from 2019-02-02 19-56-25](https://user-images.githubusercontent.com/1227961/52169761-d9545780-2724-11e9-8a52-d15797a6d957.png)
2. Send the signal to the script with `kill -s SIGHUP 31249`
2.2 The browser process (PID 31260) won't close, as said in the docs
3. Send the signal directly to the browser with `kill -s SIGHUP 31260`
3.3 The browser closes, while the script remains open

**What is the expected result?**
I expected all the chromium processes to ignore `SIGHUP` with the `handleSIGHUP` option.
Maybe I misunderstood the docs, or how much control Puppeteer has over the browser.

**What happens instead?**
Since the browser closes when the signal is sent directly to the process, features like nodemon's [graceful reloading](https://github.com/remy/nodemon#gracefully-reloading-down-your-script) don't work, since the browser closes instantly when the signal is sent to [all the processes in the tree](https://github.com/remy/nodemon/blob/dd0b96a9438f9c068c85f4ed88a5dc6709577855/lib/monitor/run.js#L315).

Is it possible to configure the chrome instances spawned from the script to also ignore `SIGHUP`?

**Comment by aslushnikov** [comment]
> Is it possible to configure the chrome instances spawned from the script to also ignore SIGHUP?

@matheusb-comp No, I don't think this is possible. We only have control on the SIGHUP handling for node.js process.

> Since the browser closes when the signal is sent directly to the process, features like nodemon's graceful reloading don't work, since the browser closes instantly when the signal is sent to all the processes in the tree.

Any chance nodemon can be configured to send sighup to the root process only? It's weird it tries to bring down the whole process subtree - children might not and should not know about nodemon existance.

**Comment by matheusb-comp** [comment]
> Any chance nodemon can be configured to send sighup to the root process only?

Not that I know of, and I believe it can't be done, by what I looked at the code.

Anyway, thanks for the answer. Closing since this is not a bug.
