### ISSUE TITLE
Try Puppeteer - ReferenceError: require is not defined

### ISSUE THREAD

**Issue by jashsayani** [puppeteer/puppeteer#3897]
The examples on https://try-puppeteer.appspot.com/ (Try Puppeteer website) that use `require` do not work. Log: `Error running your code. ReferenceError: require is not defined`

Steps:
1. Visit https://try-puppeteer.appspot.com
2. Select `screenshot-fullpage.js` in example drop down
3. Run

**Comment by vsemozhetbyt** [comment]
There is also message in the console: `Failed to load resource: the server responded with a status of 500 (): https://backend-dot-try-puppeteer.appspot.com/run`

**Comment by ebidel** [comment]
The missing require is a known issue. That particular sample can't be run as is because we've blocked require usage in in the sandbox.
