### ISSUE TITLE
Improve documentation on testing extensions

### ISSUE THREAD

**Issue by SimplGy** [puppeteer/puppeteer#3898]
I am new to this project and looking to use Puppeteer to test a Chrome extension.

I read [working-with-chrome-extensions](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions). I also browsed #2229 / #3303.

I haven't been able to meaningfully test my extension. Specifically, I was not able to figure out from the docs:

1. What exactly can I do with `const backgroundPage = await backgroundPageTarget.page()`? When I run `backgroundPage.evaluate()` I don't see the symbols I have added in my extension's background.js script. If the documentation had an example that does something with the background page it would help.
2. #2486 says I can't test extensions with an action button. This is a big gotchya! Can we roll this up to the front page? Is there a workaround ("execution contexts"?)
3. Can I run my extension's action-triggered code using some hacky process where I side-load by parsing manifest.json and injecting the scripts? What would that look like?

Could we expand more on the docs? I can do the PR if I figure out the answers.

**Comment by SimplGy** [comment]
> 3. Can I run my extension's action-triggered code using some hacky process where I side-load by parsing manifest.json and injecting the scripts? What would that look like?

Actually, this works pretty well: [relevant commit](https://github.com/SimplGy/chrome-gimme-md/commit/6c2a2955df9f98bf0d95a2c1736419a183382884#diff-8f3fdda482f04148478ba51bd3616314R82)

Steps:

1. Redefine the list of scripts that are usually injected by `chrome.browserAction.onClicked` -> `chrome.tabs.executeScript`
2. Inject them instead using puppeteer's `page.addScriptTag`
3. Proceed this way, using manual dom intervention (`page.evaluate`) instead of chrome.runtime messages.

I don't know how bad/hacky/naiive this is, but it does seem to work ok. Is this an approach we should document/recommend? If so I'm happy to add those docs.

**Comment by aslushnikov** [comment]
@SimplGy  Chrome extension support is (somewhat) tracked by #1215, please upvote :-) 

> Could we expand more on the docs? I can do the PR if I figure out the answers.

PR would be awesome! I'll close this for now, but please don't hesitate to contribute to our docs :-)
