### ISSUE TITLE
1.12.1 can't newPage() with Chrome/68.0.3440.106

### ISSUE THREAD

**Issue by zhengweijia** [puppeteer/puppeteer#3899]
puppeteer npm version 1.12.1
chromium-browser version : HeadlessChrome/68.0.3440.106

``` javascript
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://www.google.com');
  await browser.close();
})();
```
the `await browser.newPage();` cant resolve forever.

otherwise `npm install --save puppeteer@1.6.2 --ignore-scripts`, my program is well

**Comment by amazd** [comment]
Seeing the same issue. using it in a aws lambda

**Comment by JoelEinbinder** [comment]
https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy
