### ISSUE TITLE
Bikeshed the API

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#39]
Lots of things I think could be simpler

"override" "set" "get" ...

**Comment by aslushnikov** [comment]
Related to this: how do we figure what's a method and what's a getter? For example, `page.mainFrame()` could have being a property, not a method.

Today, everything's a method (except the Featch API's `Request` and `Response` classes, which use properties).

**Comment by aslushnikov** [comment]
@Paulirish `page.navigate` has an option `waitFor` clashes with `page.waitFor` method:
```js
await page.navigate('http://example.com', {waitFor: 'networkidle'});
await page.waitFor('#my-form');
```

Let's rename the `waitFor` options into `finish`?
```js
await page.navigate('http://example.com', {finish: 'networkidle'});
await page.waitFor('#my-form');
```

**Comment by paulirish** [comment]
> Let's rename the `waitFor` options into `finish`?

I'm not into `finish`.  What's coming to mind is `resolveAt`, but that seems too technical. A not-entirely-bad alternative: `waitUntil`.

**Comment by aslushnikov** [comment]
@paulirish I'd like to rename [page.printToPDF()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageprinttopdffilepath-options) into `page.pdf()`, and make it similar to `page.screenshot`:

```js
page.pdf({
  path: 'site.pdf',
  format: 'a4',
});
```

I don't like having `pdf` as a part of `page.screenshot` because `page.pdf()` has a lot of pdf-specific options.

What do you think?

**Comment by paulirish** [comment]
@aslushnikov great idea.

**Comment by aslushnikov** [comment]
Another proposal: rename Page ['consolemessage'](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-consolemessage) event into just `'console'`. 

The reasoning is:
- this event is triggered for every console API call
- `'console'` is shorter :)

@paulirish how do you feel?

**Comment by paulirish** [comment]
definitely. 👍

**Comment by aslushnikov** [comment]
I believe the majority of bikeshedding has already happened. Closing this.
