### ISSUE TITLE
Feature: pass patterns in setRequestInterception

### ISSUE THREAD

**Issue by Schniz** [puppeteer/puppeteer#3900]
### Current Behavior

Today, `page.setRequestInterception` gets a boolean which refers to whether intercept the requests or not:

https://github.com/GoogleChrome/puppeteer/blob/62da2366c65b335751896afbb0206f23c61436f1/lib/NetworkManager.js#L128-L132

### Expected behavior

To be able to provide an array of patterns myself, therefore not intercepting unwanted requests. For example, I would like to only intercept analytics calls.

It can still be backward compatible:

```js
// both can be equal:
page.setRequestInterception(true);
page.setRequestInterception([{ urlPattern: '*' }]);

// both can be equal:
page.setRequestInterception(false);
page.setRequestInterception([]);
```

### Context

We are trying to track transfer size, and for some reason, `encodedDataLength` is `0` for every intercepted request. It'd be nice to be able to choose which request pattern will be intercepted by Puppeteer.

**Comment by SimonSchick** [comment]
This seems to be a workaround, any reason the `encodedDataLength` issue couldn't be fixed instead?

**Comment by Schniz** [comment]
You are right, but the `encodedDataLength` being `0` is chrome devtools protocol thingy. I believe they are both should be addressed. 

This is not a bug report, but asking for making this opinionated method and adding more flexibility for advanced uses

**Comment by aslushnikov** [comment]
@Schniz I don't think adding patterns is much valuable to the end users - the same behavior could be implemented on a client-side using Puppeteer's default request interception. Cost of request interception is negligible, so I don't think patterns save us much here as well.

The `encodedDataLength` bit is unrelated to this FR and we don't expose it in pptr. Can you please submit a bug towards DevTools protocol at https://crbug.com/new?
