### ISSUE TITLE
Boot timeout : failed to bind to $PORT within 60 seconds

### ISSUE THREAD

**Issue by asromain** [puppeteer/puppeteer#3901]
I'm struggling on this error below, my application correctly runs, but crashes after 60 seconds.

```Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch```

Purpose of my app : Stay connected at a certain time of a day (example stay logged in between 1pm and 2pm on a website). 

The app is correctly deployed on Heroku (Build succeeded), with two buildpacks : ```heroku/nodejs``` and ```https://github.com/jontewks/puppeteer-heroku-buildpack```.

Chromium correctly launches, I can see that I am logged in the website. But everytime, after 60 seconds, the app crashes. I don't know what I'm doing wrong. 

**My environment:**

* Puppeteer version: 1.12.1
* Platform / OS version: Heroku (linux)
* Node.js version: 10.15.0

**Comment by asromain** [comment]
I don't know if this issue is normal with Puppeteer, I've created a simple server to fix this issue temporarily.

**Comment by rishalshah** [comment]
Could you explain how you created a simple server to fix this issue or did you find any other workaround?
