### ISSUE TITLE
ECONNRESET when launch on windows host with docker and mounted /tmp to linux container

### ISSUE THREAD

**Issue by pofider** [puppeteer/puppeteer#3902]
Puppeteer version: 1.12.1
Platform / OS version: Windows 10 with docker / Ubuntu xenial

Puppeteer launch throws ECONNRESET in these specific conditions.
- The host computer runs windows 10 with docker
- Puppeteer runs inside Ubuntu container
- And the docker mounts volume from the windows host to the container /tmp 

I reproduced the issue in this repository.
https://github.com/pofider/test

```
docker build . -t test

# this then works
docker run test

# this throws error ECONNRESET
docker run -v /c/temp:/tmp test
```

I see the puppeteer creates the "dev_profile" in the c:\temp and also normal node fs calls works.. 

I tried to use '--user-data-dir=/mytemp' arg to force puppeteer using a directory inside the container. I see the arg is applied and the /mytemp contains some port number text file. However it crashes as well.

**Comment by aslushnikov** [comment]
@pofider It looks like Chromium simply doesn't launch in your environment. A few things I can recommend:
- try building and running your container on linux and see if it work
- try launching chromium manually from-inside container and see if it works

Other than that, I don't think we can help much here - running Chromium in different environments falls outside of the scope of the project, and we're not very experienced with this. I'd try asking on StackOverflow or on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev).
