### ISSUE TITLE
executablePath() should return path to downloaded version

### ISSUE THREAD

**Issue by falsyvalues** [puppeteer/puppeteer#3903]
Hi ✋ 

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.6.0 its also valid for 1.9.0 I guess
* Platform / OS version: macOS 10.13.6 (17G3025)
* URLs (if applicable): - 
* Node.js version: v10.14.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `.npmrc` contains `puppeteer_chromium_revision=594312`
2. puppeteer downloads correct revision 594312 (71.0.3563.0)
3. call `require("puppeteer").executablePath()`
4. I'm not using `PUPPETEER_CHROMIUM_REVISION`

**What is the expected result?**
`executablePath()` should return path to previously downloaded version.

**What happens instead?**
`executablePath()` returns path to different version `/node_modules/puppeteer/.local-chromium/mac-555668/chrome-mac/Chromium.app/Contents/MacOS/Chromium`

**Comment by JoelEinbinder** [comment]
@aslushnikov Should .npmrc change the preferred chromium revision, or just which is downloaded on install?

**Comment by falsyvalues** [comment]
Hi @aslushnikov,  @JoelEinbinder Is there any change get this fixed or any API that will work as expected?
