### ISSUE TITLE
Cannot get values from table

### ISSUE THREAD

**Issue by ilfei** [puppeteer/puppeteer#3908]
### Steps to reproduce

**Tell us about your environment:**

Hi all,

I want to extract table information (such as number of replies) from this forum
(for example, the number of 3rd posts in the forum on the first page)
 
https://forums.ni.com/t5/LabVIEW/bd-p/170

This is my code

const puppeteer = require('puppeteer');
const POST_REPLIES = '#grid_2 > tbody > tr:nth-child(3) > td:nth-child(3) > div > span';
async function run() {
const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();  
  await page.goto('https://forums.ni.com/t5/LabVIEW/bd-p/170');
  let Replies = await page.evaluate((sel) => {
	document.querySelector(sel).innerText;
  }, POST_REPLIES);
  console.log('Replies:', Replies);
  browser.close();
}
run();

Everytime I run this code, it tells me cannot read the property of undefined. It looks like a simple issue but i got stuck here. 

Any help is appreciated.

**Comment by vsemozhetbyt** [comment]
1. You have a small typo in the selector: `tbody` is not an immediate child of `'#grid_2` but a descendant.
2. You need not `{}` in arrow function if you just need to return an expression, otherwise `undefined` is returned.

Try this (comments `// !` mark changed lines):
```js
const puppeteer = require('puppeteer');
const POST_REPLIES = '#grid_2 tbody > tr:nth-child(3) > td:nth-child(3) > div > span'; // !
async function run() {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://forums.ni.com/t5/LabVIEW/bd-p/170');
  let Replies = await page.evaluate(sel =>                                           // !
    document.querySelector(sel).innerText
  , POST_REPLIES);                                                                     // !
  console.log('Replies:', Replies);
  browser.close();
}
run();
```

**Comment by ilfei** [comment]
> 1. You have a small typo in the selector: `tbody` is not an immediate child of `'#grid_2` but a descendant.
> 2. You need not `{}` in arrow function if you just need to return an expression, otherwise `undefined` is returned.
> 
> Try this (comments `// !` mark changed lines):
> 
> ```js
> const puppeteer = require('puppeteer');
> const POST_REPLIES = '#grid_2 tbody > tr:nth-child(3) > td:nth-child(3) > div > span'; // !
> async function run() {
>   const browser = await puppeteer.launch({headless: false});
>   const page = await browser.newPage();
>   await page.goto('https://forums.ni.com/t5/LabVIEW/bd-p/170');
>   let Replies = await page.evaluate((sel) =>                                           // !
>     document.querySelector(sel).innerText
>   , POST_REPLIES);                                                                     // !
>   console.log('Replies:', Replies);
>   browser.close();
> }
> run();
> ```


It works! Thanks at first!

Could you please explain a little more about the usage  about {}?

**Comment by vsemozhetbyt** [comment]
Briefly, there are two forms of arrow functions with different body format.

Contracted form, without `{}` and `return`, when you just need to return an expression:
```js
() => 'foo'
```

And full form, with `{}` and `return`, when you need some statements before the returned value:
```js
() => {
  // some lines of code
  return 'foo';
}
```

For more details, see [Arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) on MDN.
