### ISSUE TITLE
Graph using Charts JS is blurry when using puppeteer

### ISSUE THREAD

**Issue by jonmsherman** [puppeteer/puppeteer#3910]
**Tell us about your environment:**

* Puppeteer version: 1.12.1
* Platform / OS version: MAC OS X Mojave
* Node.js version: v10.13.0

**What steps will reproduce the problem?**

Hi, I'm creating a report that uses charts from charts js. When I'm testing my html file in chrome and I do the print -> save as PDF, the chart renders pretty clear. However, when I try and do it in puppeteer, the chart is blurry, I'm not sure if there's some sort of setting?

code: 
```
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  console.log(path.resolve(__dirname, "../report/report.html"));

  await page.goto(
    `file:///Users/jonathansherman/Developer/report/report.html`,
    { waitUntil: "networkidle0" }
  );


  await page.pdf({ path: "report.pdf", format: "A4" });

  await browser.close();
})();

```

**Comment by aslushnikov** [comment]
@jonmsherman try launching browser with default viewport null:

```js
const browser = await puppeteer.launch({defaultViewport: null});
```

Other than that, I'd appreciate if you can share something so that we can reproduce it locally.

**Comment by tiholic** [comment]
@jonmsherman  setting `deviceScaleFactor` in page.emulate worked for me. as height and width were mandatory, I had to pass them.

I'm using Puppeteer with python [pyppeteer](https://github.com/miyakogi/pyppeteer) and here is my code:

```python
        browser = await launch(
            handleSIGINT=False,
            handleSIGTERM=False,
            handleSIGHUP=False
        )
        page = await browser.newPage()
        await page.emulate({
            'viewport': {
                'height': 768,
                'width': 768,
                'deviceScaleFactor': 6.0,    #IMPORTANT PIECE
            }
        })
        await page.emulateMedia("screen")
        await page.goto(f'data:text/html,{html}', waitUntil='networkidle0')
        pdf = await page.pdf(printBackground=True, format="A4", margins={
            "top": "0.4in",
            "right": "0.4in",
            "bottom": "0.4in",
            "left": "0.4in",
        })
        await browser.close()
        return pdf
```

**Comment by mattbold** [comment]
@tiholic 4 years later I stumbled on this issue and your tip was perfect. Thanks for that!
