### ISSUE TITLE
execution context was destroyed

### ISSUE THREAD

**Issue by DoheeKang** [puppeteer/puppeteer#3923]
I want to change url in for loop and go to that url and crawl information.
The first link is well done, but second link has error that 'execution context was destroyed'
what can I do?
![image](https://user-images.githubusercontent.com/42891424/52323438-541cbb80-2a20-11e9-9736-7af2214f78e8.png)

**Comment by vsemozhetbyt** [comment]
Please, post the code as text, not as an image — it is hard to work with it this way)

You are trying to use element list of the first page while navigating the same page to other documents. This does not work as the elements are not in the page after the navigation. You can fix this in either way:

* Collect not elements, but just URLs as strings and iterate over the list of strings.
or
* Navigate to the next documents in a new page.
