### ISSUE TITLE
page.pdf First page not complete when too big and second page not print at all

### ISSUE THREAD

**Issue by hhanquez** [puppeteer/puppeteer#3926]
### Steps to reproduce

* Puppeteer version: 1.11.0
* Platform / OS version: Windows 10, same on https://try-puppeteer.appspot.com/
* Node.js version: 10.9.0

**What steps will reproduce the problem?**

Here is the code that uses `page.pdf()`

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://certificate-demo.bcdiploma.com/dev/index.html#/pdf/0CE409BCD5360E6BD2DDD1DBA0AF9D0E6B40658F8745870007EF027114F41BF0qEFaPHixFa8RTaL9zI4weB6%252F5aEK2RAOGgeo81ZJ3REeAOXR');
    await page.waitFor(() => document.querySelector('.certificat-face--front'), {timeout:10000}) ;
    await page.evaluate(() => {
            var buttons = document.getElementsByClassName('certificat-sticky-buttons');
            for (var i = 0; i < buttons.length; i++) {     buttons[i].style.display = "none";        }
            buttons = document.getElementsByClassName('certificat-button-wrapper');
            for (var i = 0; i < buttons.length; i++) {          buttons[i].style.display = "none";        }
            buttons = document.getElementsByClassName('ignorePDF');
            for (var i = 0; i < buttons.length; i++) {          buttons[i].style.display = "none";        }
            buttons = document.getElementsByClassName('click');
            for (var i = 0; i < buttons.length; i++) {          buttons[i].style.display = "none";        }
            buttons = document.getElementsByTagName('button');
            for (var i = 0; i < buttons.length; i++) {          buttons[i].style.display = "none";        }
          });
    await page.addStyleTag(        {'content': '@page {size: auto}'}      );
    await page.emulateMedia('screen');
    await page.pdf({path: 'screenshot.pdf',format: 'A4', landscape: true, printBackground: true, scale: 0.7});
    await browser.close();

**What is the expected result?**

In the target url, I have two divs with the `'page-break-after: always;'` style, which are supposed to be displayed on each pages.
I expect to get a PDF file with two pages, one for each div section.

**What happens instead?**

I only got one page, the second one is not print at all, although it is displayed correctly in chromium.

When the first div is too big, it is truncated in the pdf file. This is normal when the option `format: 'A4'` is set, but it is happening even when it it not.

**Comment by PunkHaz4rd** [comment]
Same

**Comment by colin-johnson** [comment]
Anybody figure out a solve with this one?

**Comment by tiffoknee** [comment]
I've come looking for page breaks, too..

**Comment by tiffoknee** [comment]
OK, this is the solution that worked for me..

```
@media print {
    .page {
        page-break-after: always;
        width: 100%;
        margin: 0;
    }
  }
```

```
<div class="page">
all the stuff on the page la la la
</div>

<div class="page">
another page
</div>
```

There's some madness with how the print layout is interpreted by headless chromium, so far as I can tell.
