### ISSUE TITLE
await page.setContent(html, { waitUntil: 'load' }) doesnt wait in docker.

### ISSUE THREAD

**Issue by t42merli** [puppeteer/puppeteer#3929]
* Puppeteer version:
latest
* Platform / OS version:
docker node:10.15.1-alpine
* Node.js version:
10.15.1
**What steps will reproduce the problem?**

create a pdf with the page.setContent() method

_Please include code that reproduces the issue._

```
  const option = {
    format: 'A4',
    path: 'response.pdf',
  };

const html =
    '<img src="myImageLink" >'; 

const browser = await puppeteer.launch({
    headless: true,
    executablePath: process.env.CHROME_BIN || null, /* the path is right */
    args: [
      '--disable-setuid-sandbox',
      '--no-sandbox',
      '--headless',
      '--disable-gpu',
      '--disable-dev-shm-usage',
    ],
  });
await page.setContent(html, { waitUntil: 'load' });
const pdf = await page.pdf(option);
```

**What is the expected result?**

the page.setContent should wait for everything to be loaded

expected file (the result I actually get running my code not in docker):
[response.pdf](https://github.com/GoogleChrome/puppeteer/files/2836926/response.pdf)

**What happens instead?**

it doesn't wait.
Even if I use 
`waitUntil: 'networkidle0'` it doesn't wait the 500ms. 
so my images on my pdf are not loaded 

actual pdf in Docker container:
[response.pdf](https://github.com/GoogleChrome/puppeteer/files/2836896/response.pdf)

**Comment by t42merli** [comment]
I managed to make it work in a ubuntu docker image. But still it's weird.

**Comment by aslushnikov** [comment]
What's you puppeteer and chrome version? Waiting in setContent is supported only from Puppeteer 1.11.0 (and chromium 72): [release notes](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-release-notes).

**Comment by t42merli** [comment]
I'm using pupppeteer 1.11.0 and I installed chrome like this in my dockerFile : 
```
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      harfbuzz@edge \
      nss@edge
```
because it wasn't working with the default chromium download from the puppeteer install.
thats why i used : 
```executablePath: process.env.CHROME_BIN```
So maybe it was coming from here.
Thanks for your answer.

**Comment by vkill** [comment]
Hi, you should use 1.12.2, because chromium version is 73 in alpine edge repo.
