### ISSUE TITLE
PDF margins doesn't seem to be respected

### ISSUE THREAD

**Issue by HugoHeneault** [puppeteer/puppeteer#393]
I'm trying to create an A4 PDF with multiple page. 

But I'm still having margins even with margins set to 0... 

```

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto(url, {waitUntil: 'networkidle'});
    await page.pdf({path: filepath, format: 'A4', landscape: true, printBackground: true, margin: {top: 0, left: 0, right: 0, bottom: 0}});
    browser.close();
})();
```

Any ideas?

**Comment by HugoHeneault** [comment]
I got my margins respected (they had to fight hard) by using

```
@page
{
  size: A4 landscape;
  margin: 0;
}
```

So dunno if it's a bug or not. 🤔

**Comment by aslushnikov** [comment]
@HugoHeneault can you share the URL you try to load so that I can reproduce this issue?

**Comment by HugoHeneault** [comment]
@aslushnikov Sure I can ; but now it's fixed with the margin + @page size. 

You can see it live here: https://stationdetrail.com/fr/stations/chartreuse/parcours/atelier-cote-6.pdf?type=openCycle&phantom
You'll be prompted to login : use `test@ownweb.fr` and  `testtest` 

If you remove the @page you'll have no more margins ;)

**Comment by nynevi** [comment]
@HugoHeneault your page code helped solve my case, thank you for fighting against margins on behalf of us.

In my case it was:

`@page
{
  size: A4 portrait;
  margin: 0;
}`

**Comment by KimSchneider** [comment]
I have kind of a similar issue. I have tested my script on five different systems.

`return page.pdf({
                path: out,
                format: 'A4',
                margin: {
                    left: '2cm',
                    top: '4cm',
                    right: '1cm',
                    bottom: '2.5cm'
                }
            }).then(function () {
                logger.info('saved pdf');
                return browser;
            });`

On my windows mashine and my ubuntu 14.05. vm the margins are respected and everything looks finde. 
On our three production mashines (ubuntu 14.05 all updates installed) the margins are disrespected. There seems to be a default margin of about 0.5cm on each side. In addition to that, none of the svg charts of the page are shown and font types are not showing up, too.

Does anyone know a similar behaviour?

**Comment by SystemParadox** [comment]
It seems that the CSS `@page { margin: }` rules always take precedence. I can't find any way to have the margins specified to `page.pdf({ margin: })` override the CSS margins.

This is a real pain - some of our documents have different margin and footer size requirements, but I can't figure out how to do this in puppeteer. This is the last hurdle before I can finally replace phantomJS!

**Comment by garygreen** [comment]
Have you tried the [`preferCSSPageSize`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) ? This allows you to specify the margin's for page in the CSS and it will take priority:

```css
@page {
  size: A4 portait;
  margin: 0;
}
```

**Comment by SystemParadox** [comment]
`preferCSSPageSize` appears to have been added in 1.7.0. Interestingly, the default is `false`, which is what I want.

However, I tried it with 1.8.0 and even when specifically passing `preferCSSPageSize: false`, the CSS `@page` size and margin still takes precedence.

It seems that `preferCSSPageSize` doesn't actually do anything at the moment? I tried everything I could think of and I couldn't find any difference between `preferCSSPageSize: false` and `preferCSSPageSize: true`. Is this feature broken?

**Comment by edwin-walker** [comment]
I have observed the same. If you set the page size to be tiny in CSS, Puppeteer generates a PDF with the default page size. I have `preferCSSPageSize: true` in my options.

It does seem to obey margins, but not using separate margins for the first page. For example this removes the bottom margin on all pages:
```css
@page {
  margin-bottom: 50%;
}

@page :first {
  margin-bottom: 0;
}
```

The Chrome print preview appears to respect the `:first` rule.

**Comment by zaiddabaeen** [comment]
The state of this today with puppeteer 9.1.1 is still that margin argument is not respected, and you must modify the CSS to indicate the margins needed.

**Comment by nolimitdev** [comment]
For me margin option works well on windows and linux debian too. Puppeteer version 13.3.2.

**Comment by dansp89** [comment]
Working, but headers and footers are included, I'll go deeper to work with current CSS LIBS.

```js
await page.addStyleTag({
  content: `
    @page {
      margin: 1in;
    }
    body {
      margin: 0;
    }
  `,
});

```

**Comment by rdev32** [comment]
I solved this issue with these settings

```js
    await page.pdf({ 
      path: 'cv.pdf', 
      printBackground: true,
      format: 'A4',
      preferCSSPageSize: true,
      margin: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0
      },
    });
```
hope this helps you

**Comment by villegas97** [comment]
> I got my margins respected (they had to fight hard) by using
> 
> ```
> @page
> {
>   size: A4 landscape;
>   margin: 0;
> }
> ```
> 
> So dunno if it's a bug or not. 🤔

This worked for me, I was using width and height in the page options and setting margins to 0 without success, I had to add the size in the CSS of the document and the margin too.
