### ISSUE TITLE
Chromium binary in release v1.12.2 vs v1.12.1

### ISSUE THREAD

**Issue by 3p3r** [puppeteer/puppeteer#3933]
I am sorry if this is not the right place to ask this question but I am confused about what actually changed in the Chromium version used across release v1.12.2 vs. v1.12.1

v1.12.2 says it ships with revision `r624492`, however v1.12.1 ships with `r624487`. What confuses me is that both of these use the same exact Chromium version which is 73.0.3679.0 ?

What's the difference between Chromium revision and Chromium version? I previously thought version (e.g. 73.0.3679.0) is interchangeable with revision (r624492).

How would you actually clone a Chromium revision? I can clone a Chromium version with `git clone <chromium git> -b <version number>`. Are revisions the same as tags?

I would appreciate it if you could resolve my confusion.

**Comment by aslushnikov** [comment]
> I am sorry if this is not the right place to ask this question but I am confused about what actually changed in the Chromium version used across release v1.12.2 vs. v1.12.1

That's the perfect place to ask these kind of questions :-)

> What's the difference between Chromium revision and Chromium version?

Versions are not 1:1 to revisions - there's usually a range of revisions that gets shipped into some version. 

Puppeteer pins Chromium revision; the version we put in release notes is the "first Chromium version the revision is shipped with". We get this through https://omahaproxy.appspot.com/ - there's a "find release" box in the bottom of the page.

> How would you actually clone a Chromium revision?

Once you have a chromium checkout, the easiest would be:

1. goto `https://crrev.com/<REVISION>` to get the SHA of the commit (note: <REVISION> should be without "r")
2. checkout the SHA in the chromium repo

Does it make things clearer?

**Comment by 3p3r** [comment]
That makes perfect sense now, thanks for taking the time to answer my questions.
