### ISSUE TITLE
Click botton over Boostrap modal and jQueryUI 

### ISSUE THREAD

**Issue by AlonsoK28** [puppeteer/puppeteer#3934]
[Puppeteer v1.12.2]
I am triying click in a button over a JQuery but Puppeteer gets following error

**The same error applies for Bootstrap "modal" and jQuery UI "dialog"**

```
await page.click("boostrap-modal > button"); //this button is inside a modal boostrap

Error: Node is either not visible or not an HTMLElement
```

**Comment by aslushnikov** [comment]
@AlonsoK28 anything we can run locally to see it misbehaving? A small script would help a lot.

**Comment by lue93** [comment]
Hi @aslushnikov and @AlonsoK28  ,

I have a doubt about it too, 
How can to work with modals in pupeteer ?

code example https://jsfiddle.net/kumarmuthaliar/GG9Sa/1/

Thanks
