### ISSUE TITLE
Inconsistency between headless and headful browser

### ISSUE THREAD

**Issue by JulianAnthes** [puppeteer/puppeteer#3940]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: macOS 10.14.2
* URLs (if applicable):
* Node.js version: v10.15.1

**What steps will reproduce the problem?**

When navigating to localhost in `headful mode`, the page renders as expected. But that's not the case when running in `headless mode`. I'm aware of the fact that the scheme has to be defined, but it's still an inconsistency where people may get stuck like me.

### Code example

```js
const puppeteer = require('puppeteer')

const start = async () => {
    const browser = await puppeteer.launch({ headless: true })
    const page = await browser.newPage()
    await page.setViewport({width: 1920, height: 1080})
    await page.goto('localhost:8081', { waitUntil: 'networkidle0' })
    await page.screenshot({path: 'screenshot.png'});
    await page.close()
    await browser.close()
}

start();
```

**What is the expected result?**
I'd expect the same result in both modes.

**What happens instead?**
When running in `headful mode`, the page renders, but in  `headless mode` nothing happens at all.

I'd suggest having some sort of check if a scheme was provided resulting in an error message when the scheme was not provided.

I tested the same with `www.google.com` as URL and got an error:
```sh
(node:20784) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
````

Would be awesome to see the same error thrown for `localhost`.

**Comment by aslushnikov** [comment]
Technically, Chromium Headless is a *whole new different browser*, so I wouldn't expect things to align everywhere. The error is pretty self-descriptive, so I don't think anything's very lacking here in terms of Developer Experience.
