### ISSUE TITLE
TypeError: page.emulateMedia is not a function

### ISSUE THREAD

**Issue by HugoHeneault** [puppeteer/puppeteer#395]
Hi there, 

I'm trying to save a PDF with screen media mode enabled. 

But I have this issue : 
```
(node:18806) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: page.emulateMedia is not a function
```

Here is my conf: 
```
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto(url, {waitUntil: 'networkidle'});
    await page.emulateMedia('screen');
```

**Comment by ebidel** [comment]
Hi @HugoHeneault, `page.emulateMedia` was added yesterday in https://github.com/GoogleChrome/puppeteer/commit/6cc274135c9b68001d4febab11aaec3a7c72b820. It'll be available in the next release. Until then you can install from master:

```
yarn add https://github.com/GoogleChrome/puppeteer
# npm i --save https://github.com/GoogleChrome/puppeteer
```

**Comment by HugoHeneault** [comment]
Aww! Really nice! 👍 
Doc is coming faster than releases! 😂 
Thank you guys!

**Comment by NightMachinery** [comment]
It's now renamed to `page.emulateMediaType`.

**Comment by aqueeb** [comment]
> It's now renamed to `page.emulateMediaType`.

Thanks a lot @NightMachinary ! You saved me a bunch of time. I should have checked the version for the documentation markdown. I was looking at the wrong one. 🤦‍♂️
