### ISSUE TITLE
Not working with js dynamic height like revolution slider 

### ISSUE THREAD

**Issue by baptistebisson** [puppeteer/puppeteer#3950]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable): https://the7.io/main/
* Node.js version: 10.8.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	page.setViewport({
		width: 0,
		height: 0,
	});
	await page.goto('https://the7.io/main/', {"waitUntil" : "networkidle0"});
	
	await page._client.send('Animation.setPlaybackRate', { playbackRate: 2 });
	
	await page.evaluate(() => {
		window.scrollBy(0, window.innerHeight);
	});
	
	await page.waitFor(1000);
	
	await page.screenshot({
		path: 'example.png',
		fullPage: true
	});
	
	await browser.close();
})();
```
**What is the expected result?**
A full screenshot of the page with the main slider and the content bellow

**What happens instead?**
The slider is full height so we don't see anything else. We can see in the console that if we resize, a JS method update the height of the main slider. When using revolution slider for Wordpress we can use full height.
Here is the screenshot : https://i.imgur.com/6cTPneY.jpg

**Comment by aslushnikov** [comment]
@baptistebisson I'm not sure I follow - what's a main slider?

**Comment by baptistebisson** [comment]
> @baptistebisson I'm not sure I follow - what's a main slider?

The main slider is the first slider on the home page (what you see on the screenshot)

**Comment by aslushnikov** [comment]
@baptistebisson ah I see now. Indeed, full page screenshot changes window size in a page-observable way, so resize listeners are getting triggered.

However, you can pause javascript execution in the page so that resize is not executed.
The following works just fine for me:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.setViewport({
    width: 0,
    height: 0,
  });
  await page.goto('https://the7.io/main/', {"waitUntil" : "networkidle0"});

  await page._client.send('Animation.setPlaybackRate', { playbackRate: 2 });

  await page.evaluate(() => {
    window.scrollBy(0, window.innerHeight);
  });

  await page.waitFor(1000);

  // Enable debugger
  await page._client.send('Debugger.enable');
  // Pause debugger and wait for it to be paused
  page.evaluate(() => {
    debugger;
  }).catch(e => {});
  await new Promise(x => page._client.once('Debugger.paused', x));

  await page.screenshot({
    path: 'example.png',
    fullPage: true
  });

  await browser.close();
})();
```

Hope this helps.
