### ISSUE TITLE
loading full html page not working anymore!!

### ISSUE THREAD

**Issue by marcelluswalace** [puppeteer/puppeteer#3957]
Hello,
I've been issing pupperteer for a year now loading html page from string using this below code
await page.GoToAsync($"data:text/html,{html}", new NavigationOptions
{
WaitUntil = new[] { WaitUntilNavigation.Networkidle0,
WaitUntilNavigation.Networkidle2, WaitUntilNavigation.DOMContentLoaded, WaitUntilNavigation.Load }
});
It was working fine loading full html content with no issue. Yesterday I ran my app in Visual studio and it is not working any more. puppeteer is removing my script and style tag from html content. And also notice that it is pre-adding header and body tag. Eg if you add like

dum
puppeteer will set the content as
dum
. So when I try to load a full html content anything I put in the body of my html is dropped for no reason. Can anybody help me out there?

**Comment by marcelluswalace** [comment]
Here is the html I am trying to load 


<html>
<head>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/highcharts/4.2.7/highcharts.src.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/highcharts/4.2.7/modules/series-label.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/highcharts/4.2.7/modules/exporting.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/highcharts/4.2.7/modules/data.js'></script>
    <meta charset='utf-8' />
    <title>High Chart Body!</title>
</head>
<body>
    <style type='text/css'>
        #container {
            min-width: 310px;
            max-width: 800px;
            height: 400px;
            margin: 0 auto
        }
    </style>

    <div id='container'></div>
    <script type='text/javascript'>
       
        var chart = Highcharts.chart('container', {

            title: {
                text: 'Patate'
            },
            series: [
  {
    "color": null,
    "data": [
      {
        "color": "#8B8A8A",
        "id": null,
        "lat": null,
        "lon": null,
        "name": null,
        "x": null,
        "y": 21,
        "z": null
      },
      {
        "color": "#E23939",
        "id": null,
        "lat": null,
        "lon": null,
        "name": null,
        "x": null,
        "y": 18,
        "z": null
      },
      {
        "color": "#007DC5",
        "id": null,
        "lat": null,
        "lon": null,
        "name": null,
        "x": null,
        "y": 17,
        "z": null
      },
      {
        "color": null,
        "id": null,
        "lat": null,
        "lon": null,
        "name": null,
        "x": null,
        "y": 16,
        "z": null
      }
    ],
    "id": null,
    "name": null,
    "type": null,
    "xAxis": 0,
    "yAxis": 0
  }
],
            xAxis: [
  {
    "categories": [
      "SpaceX",
      "NASA",
      "Blue Origin",
      "Marie"
    ],
    "min": null,
    "tickPositions": null,
    "title": {
      "text": null
    },
    "type": null,
    "visible": true
  }
],
            yAxis: [
  {
    "categories": null,
    "min": null,
    "tickPositions": null,
    "title": {
      "text": "Patate"
    },
    "type": null,
    "visible": true
  }
]

        });
        var div = document.createElement('div');
        div.id = 'chartImgId';
        var element = document.getElementsByTagName("body");
        element[0].appendChild(div);
    </script>
</body>
</html>

**Comment by marcelluswalace** [comment]
why doesnt puppeteer just take what its being given? And by the way it was working before....

**Comment by marcelluswalace** [comment]
await page.GoToAsync($"data:text/html,<script>alert('hi');</script>", new NavigationOptions
            {
                WaitUntil = new[] { WaitUntilNavigation.Networkidle0,
                            WaitUntilNavigation.Networkidle2, WaitUntilNavigation.DOMContentLoaded, WaitUntilNavigation.Load }
            });

Just discovered that this is not working at all timeout exceed exception. because of scripts tag?

**Comment by aslushnikov** [comment]
Not sure what's `page.GoToAsync` - are you using C# port?

In any way, please use [`page.setContent`](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-pagesetcontenthtml-options) to set page's HTML.
