### ISSUE TITLE
exposeFunction remains in memory?

### ISSUE THREAD

**Issue by jaykumarthaker** [puppeteer/puppeteer#3961]
Well, this will be just a simple question. **If the page is closed, then does exposeFunction defined before remains in memory?** I mean, do I have to worry about memory leak or something? (as the promise may never get resolved..) I am pretty novice with this Promise things, please bear with me :)
page.exposeFunction(name, puppeteerFunction)

um, my code is like this:

    const page = await browser.newPage();

    var promiseExposeFunction = new Promise(async (resolve, reject) =>{
        await page.exposeFunction('NotifyPuppeteer', (async data => {
        if(data == "page_loaded")
        {
            console.log("exposeFunction resolved it..");
            return resolve();
        }
        }));

        // if page is closed, then let's return if we haven't yet
        page.on('close', () => {
            return reject('page is closed');
        });
    });

    var promiseGoto = new Promise(async (resolve, reject) =>{
        await page.goto('http://google.ca', { waitUntil: 'networkidle0', timeout: 120000})
        .then(() => {
            resolve();
        })
        .catch((err) => {
            console.log("Failed to load the page: " + err); // mostly timeout error
            const{name} = err;
            
            // only resolve if the page timeout and it's still open
            if(name == "TimeoutError" && page.isClosed() == false)
                return resolve();
            else
                return reject(err);
        });

        // if page is closed, then let's return if we haven't yet
        page.on('close', () => {
            return reject('page is closed!');
        });
    });

    let return_value = await Promise.race([promiseExposeFunction, promiseGoto]).then(async function() {

        var new_pdf_path = 'page.pdf';
        await page.pdf({path: new_pdf_path});
        await page.close();

        return new_pdf_path;
    });

    console.log("pdf created, get it at: ", return_value);

This way we allow the page to notify puppeteer when it has loaded completely so that we can do our rest of the things like generating pdf, screenshot etc. i have been facing weired issue with networkidle0 such that it takes [forever](https://bugs.chromium.org/p/chromium/issues/detail?id=909616) to complete await page.goto (only with headless: true, works fine with false), hence I am following this approach by manually timing-out or allowing page itself to notify puppeteer. Hence whichever Promise finish first  will complete the Race condition.
This code work fine, though I am not sure that **this is the correct way of handling the situation?**

Though, I must say thank you so much for this amazing library guys.. I really appreciate your hardwork.

**Comment by aslushnikov** [comment]
>  If the page is closed, then does exposeFunction defined before remains in memory?

@jaykumarthaker no memory leak here

>  this is the correct way of handling the situation?

You can race two things, but I'd expose function first before running any navigation so that there's no unwanted race condition in your code.
