### ISSUE TITLE
How to send message from page to Puppeteer?

### ISSUE THREAD

**Issue by lai32290** [puppeteer/puppeteer#3971]
My goes is to create a configuration page what I can set some variables and a button to Start/Pause/Stop the Puppeteer actions, so I created a local HTML to be the config page then I'm loading it into a new tab on Puppeteer.

Question: How can I send the configured value from that page to the Node-side/Puppetter side?

**Comment by vsemozhetbyt** [comment]
You can try [`page.exposeFunction()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction).

**Comment by lai32290** [comment]
That's great! it seems work to me, I'll test it, thank you so much!

**Comment by lai32290** [comment]
It works! thank you very very much!

**Comment by vsemozhetbyt** [comment]
Happy coding)
