### ISSUE TITLE
Page loading stucks on header manipulation if page give 302 status code

### ISSUE THREAD

**Issue by khizarsonu** [puppeteer/puppeteer#3973]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.12.2
* Platform / OS version: MAC / UBUNTU
* URLs (if applicable):
* Node.js version: 8.11.4
* chromium command line: ~/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process,TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_profile-ria4kq --flag-switches-begin --flag-switches-end --file-url-path-alias=/gen=/home/khizar/solutions2/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/gen about:blank
--

**What steps will reproduce the problem?**

_below code can reproduce this error._

```
const puppeteer = require('puppeteer');
const URL=require('url').URL;
(async () => {
  let browser = await puppeteer.launch({
    headless:false,
    isMobile:true,
    hasTouch:true,
    args:[
    ]});
  let whiteDomain=['is.gd'];
  let page = await browser.newPage();

  //manipulation of header starts
  await page.setRequestInterception(true);
  await page.setExtraHTTPHeaders(['header1:value2','header2:value2']);
	page.on('request', request => {    
	  // Override headers
    let url=request.url();
    let urlObj=new URL(url);
	  const headers = Object.assign({}, request.headers(), {
	    foo: 'bar', // set "foo" header

	  });
    if(whiteDomain.includes(urlObj.hostname))
    {
      console.log("adding header");
      request.continue({headers});
    }
    else
    {
      request.continue();
    }
    console.log("continue should be called by now");
	});
  //manipulation of header ends;
  await page.goto('http://google.com');
})();
```

**What is the expected result?**
header should be manipulated and redirected to other page if page response status code is 302

**What happens instead?**
page loading forever in pending status

**Comment by vsemozhetbyt** [comment]
Minimum reproducible case: if `foo: 'bar'` line is commented out, all is OK. If it is uncommented, redirection hangs.
```js
'use strict';

const puppeteer = require('puppeteer');
(async () => {
  try {
    let browser = await puppeteer.launch({ headless: false });
    let [page] = await browser.pages();

    await page.setRequestInterception(true);

    page.on('request', request => {
      const headers = Object.assign({}, request.headers(), {
        // foo: 'bar'
      });
      request.continue({ headers });
    });

    await page.goto('https://is.gd/OwycZW');
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by ashishnetworks** [comment]
this is a really annoying bug, did somebody find any workaround or solution for it?

**Comment by khizarsonu** [comment]
hi @aslushnikov 
can you please look into this bug?

**Comment by aslushnikov** [comment]
This is a chromium bug; filed upstream as https://crbug.com/937719

Thanks for reporting this!

**Comment by drsromero** [comment]
I get the same result when I send POST data and the page give 302 status code.
