### ISSUE TITLE
characters &# are not permitted in the title

### ISSUE THREAD

**Issue by santochen** [puppeteer/puppeteer#3974]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 8.15.0

**What steps will reproduce the problem?**
Having characters combination `&#` on the title will render blank pdf file

_Please include code that reproduces the issue._
```js
const puppeteer = require('puppeteer');
const fs = require('fs');
const html = 
'<html><head><title>Test&#s</title></head><body>Test</body></html>';


(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox' ]});
  page = await browser.newPage();
  const session = await page.target().createCDPSession();
  await page.goto(`data:text/html, ${html}`, { waitUntil: 'networkidle0'});
  await page.pdf({
    path: 'test.pdf',
    format: 'A4'
  });
  await browser.close();
})();
```

**What is the expected result?**
pdf content should contain at least `Test` word ignoring the title.

**What happens instead?**
Rendered pdf content was empty.

**Comment by vsemozhetbyt** [comment]
If you use `#` character in URI, it is parsed as a start of the hash part and all the HTML is aborted after it (you can see it with `headless: false` option and without PDF creation). You can try this:
```js
const html = encodeURIComponent(
  '<html><head><title>Test&#s</title></head><body>Test</body></html>');
```

**Comment by santochen** [comment]
@vsemozhetbyt , should this be part of URI? as that content is actually inside title.

**Comment by vsemozhetbyt** [comment]
Escaping is exactly the hint that this is a part of the URI that should be parsed into HTML, not the start of a hash, You will see the same if you try to open this URL (`data:text/html,<html><head><title>Test&#s</title></head><body>Test</body></html>`) in a common browser and look in the HTML source of the empty page: it is cut at this unescaped symbol. And then compare with the escaped variant: `data:text/html,%3Chtml%3E%3Chead%3E%3Ctitle%3ETest%26%23s%3C%2Ftitle%3E%3C%2Fhead%3E%3Cbody%3ETest%3C%2Fbody%3E%3C%2Fhtml%3E`

**Comment by santochen** [comment]
Awesome! It works. Thanks for your help @vsemozhetbyt
