### ISSUE TITLE
Structure testing tool not working 

### ISSUE THREAD

**Issue by Easyschools** [puppeteer/puppeteer#3975]
I have an application that is build with Angular 6. I am using puppeteer headless browser to render my pages. after I changed my website, i can't find any of my structure data in google search console. however when i try the structure data testing tool it gives me "The URL timed out. Make sure it is responding in a timely fashion to requests from Google.". If i try again for second time it works and get me all the microdata i am implementing. I don't have problem with my page speed as i already score +90 in the testing tool. I still can't figure what is the problem why structure data don't validate my page from first time and why it's not extracting the data. I already implement the structure data 5 weeks ago so i guess google should validate it. 

here is the sample page which have issue: https://www.easyschools.org/en/schoolProfile/qaitbay-international-school

if anyone had this issue before please advice me. Thank you

**Comment by aslushnikov** [comment]
@Easyschools this doesn't look like it has something to do with Puppeteer per se. I'd try asking somewhere else (e.g. stackoverflow?)
