### ISSUE TITLE
getting null node in expect whereas page.evaluate gives correct node

### ISSUE THREAD

**Issue by cr33dx** [puppeteer/puppeteer#3979]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.12.0
* Platform / OS version:windows/10
* URLs (if applicable):
* Node.js version:10.15.0

**What steps will reproduce the problem?**
When using jest-dom with puppeteer expect says that cannot read property children of null
whereas I can get that same node inside page.evaluate

_Please include code that reproduces the issue._

```js
test('Check For Company Name', async (done)=>{
        await addClear('companyName')
        await page.waitFor(2000)
        flag = await page.evaluate(()=>{
            let x = 0
            if(document.querySelector('div.mdc-form').children[2]!=null)x = 1 //This gives the correct node
            return x
        })
        //expect(flag).toBe(1)
        expect(document.querySelector('div.mdc-form').children[2]).tobeVisible //This gives error saying cannot read property children of null
         done()
    })
```

**What is the expected result?**
To get the node inside expect

**What happens instead?**

gives an error saying cannot get property children of null

**Comment by aslushnikov** [comment]
@cr33dx Looks like this has something to do with jest-dom rather then with pptr; please file over to their repo.
