### ISSUE TITLE
Debugger breakpoint doesn't work inside async function in readme example

### ISSUE THREAD

**Issue by smoll** [puppeteer/puppeteer#398]
Hello, thanks for the awesome project! I was unsure of how to set a breakpoint before the browser closes in the [readme example](https://github.com/GoogleChrome/puppeteer#usage), so I can take a look at the DOM at that moment in time.

When I place a `debugger` statement inside the async function and run the file, it seems to ignore it. Excuse my ignorance if this more of an async/ES2016 question rather than a Puppeteer question, but I appreciate any guidance you can provide.

**Comment by ebidel** [comment]
**General**
To debug a node script using Chrome/Devtools:

1. run your script with `node --inspect-brk debug.js`
2. open `chrome:inspect` in a running chrome browser,
3. click "inspect" for your remote target:

<img width="835" alt="screen shot 2017-08-19 at 2 51 34 pm" src="https://user-images.githubusercontent.com/238208/29490338-ec9feffa-84ed-11e7-8151-ca8a5d7148b8.png">

That'll open devtools where you can set breakpoints and step through code. https://nodejs.org/en/docs/inspector/#inspector-tools-clients lists other options if you don't want to use DevTools for debugging.

---
**Examine the state of the page**

Right now, what you want to do is a bit tricky. Puppeteer runs in another process to the browser. IOW, breakpoints won't work for code that's run outside of puppeteer/Node. For example, when using `evaluate`:

```js
 debugger; // will trigger
 await page.evaluate(() => {
    debugger; // won't trigger. Execution context is in the browser
  });
```

What I've been doing is running with `node --inspect-break` as described above, but launch chrome with `headless: false` and add a `debugger` right before I want to examine the page. In the launched browser window, open the devtools and poke around as usual.

```js
const browser = await puppeteer.launch({headless: false});
const page = await browser.newPage();
await page.goto('https://www.google.com');
//... do other stuff....
debugger;
browser.close();
```

**Comment by smoll** [comment]
Thanks for the link and detailed explanation! It looks like `node inspect myfile.js` is what I was looking for, which I think is the successor to `node debug`.

To set things up as they are in the evaluate, I can copy & paste the code I want eval'd into the Dev Console, or as you suggest, simply set `debugger` immediately after the evaluate call. 😁 

Edit: also, need to type `repl` to get into the proper context (where vars are defined, etc.)

**Comment by tokland** [comment]
@ebidel, when the script is stopped (by using breakpoints or`debugger` statements), how do you get the response of functions that return a promise?

**Comment by tokland** [comment]
@ebidel, when the script is stopped (by using breakpoints or`debugger` statements), do you know how to get the response of functions you execute in the console and return a promise?

**Comment by melissachang** [comment]
I have the same question as @tokland . My test file has:
```
    let input = await page.waitForSelector("input.gLFyf");
    debugger;
```
Using [Eric's instructions](https://github.com/GoogleChrome/puppeteer/issues/398#issuecomment-323551586) I can stop on the `debugger;` and view `input` in devtools console:

![1](https://user-images.githubusercontent.com/10929390/56698924-77aee400-66a8-11e9-921f-52e421976a72.png)

But if I run `await` in console, I can't view the results:

![2](https://user-images.githubusercontent.com/10929390/56698969-98773980-66a8-11e9-9935-a34ae6365b1e.png)

Is there any way to get this to work? Should I file a Chrome devtools bug?

**Comment by melissachang** [comment]
Hmm, looks like https://bugs.chromium.org/p/chromium/issues/detail?id=833928
