### ISSUE TITLE
chrome dev console result and puppeteer result is different

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#3981]
when i was scrapping innerHTML using puppeteer, first test using chrome dev console

`document.querySelector("div#c_food_tab1 div#mCSB_4_container").innerHTML;` 

is return good result so copy & paste this code to my src and run code

result is Error

(node:4895) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null

so i decided to fix my code that HTML element select all course of target

`const profRestaurant = await page.evaluate(
    () =>
      document.querySelector("div#c_food_tab1 div#mCSB_5 div#mCSB_5_container")
        .innerHTML
  );`

then code is working 

i wondering about why their(chrome dev console, puppeteer) return different result

**Comment by vsemozhetbyt** [comment]
It is hard to understand the issue without the URL and the full script. Can you provide a small but complete script that demonstrates the error?

**Comment by ghost** [comment]
@vsemozhetbyt okay, 
this is URL : https://portal.dankook.ac.kr/web/portal (my college web site)

`const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto("https://portal.dankook.ac.kr/web/portal");

  const profRestaurant = await page.evaluate(() =>
      document.querySelector("div#c_food_tab1 div#mCSB_4_container")
        .innerHTML
  );

  console.log(profRestaurant);

  console.log(movieRank);
  await browser.close();
})();`

this code throw error that
(node:1156) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null

i think puppeteer can't find innerHTML without all element course like chain
but google chrome dev tool is working when i use upper querySelector 

`document.querySelector("div#c_food_tab1 div#mCSB_4_container")`
this code is working

`const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto("https://portal.dankook.ac.kr/web/portal");

  const profRestaurant = await page.evaluate(() =>
      document.querySelector("div#c_food_tab1 div#mCSB_5 div#mCSB_5_container") //working
      .innerHTML
  );

  console.log(profRestaurant);

  console.log(movieRank);
  await browser.close();
})();`

is this enough information about error?

**Comment by vsemozhetbyt** [comment]
The layout and DOM structure of the page depends on the viewport size.  When you test on the common browser, the viewport is wide and the page has `"div#c_food_tab1 div#mCSB_4_container"` selector. Puppeteer sets an initial viewport size to 800px x 600px, so with puppeteer script the viewport is narrow and the page has `"div#c_food_tab1 div#mCSB_5 div#mCSB_5_container"` instead of `"div#c_food_tab1 div#mCSB_4_container"`. If you add this line in your first script, it will work properly (you can set any other wide size):

```js
  await page.setViewport({ width: 1280, height: 720 });
  await page.goto("https://portal.dankook.ac.kr/web/portal");
```

**Comment by ghost** [comment]
@vsemozhetbyt  Oh, viewport! wonderful thanks to your help!

**Comment by salmansrabon** [comment]
Still, I found this error:

Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at __puppeteer_evaluation_script__:3:17

**Comment by ghost** [comment]
> Still, I found this error:
> 
> Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
> at **puppeteer_evaluation_script**:3:17

Can you provide to me your code?

**Comment by salmansrabon** [comment]
const puppeteer = require('puppeteer');
const { reporters } = require('mocha');
const { expect } = require('chai');
it("Login to portal", async () => {
        const browser = await puppeteer.launch(
            {
                headless: false,
                slowMo: 10,
                defaultViewport: null,
                devtools: false,
                args: ['--start-maximized']
            })
        const page = await browser.newPage();
        await page.goto('https://member.dev.clubswan.com/');

        //await page.type('[name=emailAddress]', email)
        await page.type('[name=emailAddress]', 'testuser+365@testmail.com')
        await page.type('[name=password]', 'P@ssword123')
        const btnSubmit = await page.$x(
"//button[@class='ui fluid primary button']");
        await btnSubmit[0].click();
        await page.waitFor(3000)

        const element = await page.$x(
"//span[contains(text(),'DO THIS LATER')]");
        const text = await page.evaluate(element => element.textContent,
element);
        console.log(text)
        assert.equal(text, "DO THIS LATER")
        await browser.close();

    });

*Error:*

*assert is not defined. *Although I have import chai.

Best Regards,

*K. M Salman Rahman*

Cell: +8801686 606 909
Skype ID: salman.srabon1

**Comment by ghost** [comment]
Your code only import chai.expect using `const {expect} = require('chai')`

if you want to use assert fix the code like `const {expect, assert} = require('chai')`

**Comment by ghost** [comment]
And i fix your test code
```
const puppeteer = require("puppeteer");
const { reporters } = require("mocha");
const { expect, assert } = require("chai");
it("Login to portal", async () => {
    const browser = await puppeteer.launch({
        headless: false,
        slowMo: 10,
        defaultViewport: null,
        devtools: false,
        args: ["--start-maximized"],
    });
    const page = await browser.newPage();
    await page.goto("https://member.dev.clubswan.com/");

    //await page.type('[name=emailAddress]', email)
    await page.type("[name=emailAddress]", "testuser+365@testmail.com");
    await page.type("[name=password]", "P@ssword123");
    const btnSubmit = await page.$x(
        "//button[@Class='ui fluid primary button']"
    );
    await btnSubmit[0].click();
    await page.waitFor(7000);

    const handler = await page.evaluateHandle(() => {
        const element = document.querySelectorAll(".MuiButton-label")[0];
        return element;
    });
    const text = await page.evaluate((element) => element.textContent, handler);
    assert.equal(text, "DO THIS LATER");
    console.log(text);
    await browser.close();
});
```
