### ISSUE TITLE
Including # (for colours) in style tags in document results in incorrect HTML in page content

### ISSUE THREAD

**Issue by tphbrok** [puppeteer/puppeteer#3982]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Windows 10
* Node.js version: v10.14.1

**What steps will reproduce the problem?**

```const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox"]
  });
  const page = await browser.newPage();
  const html = `<html><head><style>*{margin:0};body{background-color:#000;}</style></head><body>test</body></html>`;
  await page.goto(`data:text/html,${html}`);
  console.log(await page.content());
  await browser.close();
})();
```
**What is the expected result?**
The logging of `page.content()` is expected to be equal to the input string of HTML data.

**What happens instead?**
The logging displays the HTML document style up until the \#-character, after which other content is not loaded in the page:

`<html><head><style>*{margin:0};body{background-color:</style></head><body></body></html>`

Additionally, body content is also not loaded.

**Comment by tphbrok** [comment]
Workaround (replacing '#' with its ASCII-code equivalent): `html = html.replace(/#/g, "%23");`

**Comment by vsemozhetbyt** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/3974
