### ISSUE TITLE
Timeout error when it's waiting for selector

### ISSUE THREAD

**Issue by airda2895** [puppeteer/puppeteer#3983]
[Puppeteer version: 1.12.2]
[Node.js version: 10.15.1]

I'm trying to scrape this [website](https://www.marriott.com/hotels/travel/reumd-le-meridien-ra-beach-hotel-and-spa/) because I need to get the prices of this hotel -> This can be done by clicking on "Reserve now". However, I keep getting a timeout error when waitingforselector. Even, I have used the extension Puppeteer recorder for Google Chrome and still I get this error.

Code:
```
const puppeteer = require('puppeteer');
void (async () => {
	try {
		const browser = await puppeteer.launch()
		const page = await browser.newPage()		  
		const navigationPromise = page.waitForNavigation()
		await page.goto('https://www.marriott.com/hotels/travel/reumd-le-meridien-ra-beach-hotel-and-spa/')
		await page.setViewport({ width: 1920, height: 938 })
		await page.waitForSelector('.tile-hws-site-maps > .mi-scroll-nav > .l-drawer-container > .l-navbar-container > .l-navbar-content')
		await page.click('.tile-hws-site-maps > .mi-scroll-nav > .l-drawer-container > .l-navbar-container > .l-navbar-content')
		await page.waitForSelector('.m-hotel-info > .l-container > .l-header-section > .l-m-col-2 > .m-button')
		await page.click('.m-hotel-info > .l-container > .l-header-section > .l-m-col-2 > .m-button')
		await page.waitForSelector('#edit-search-panel > #YSS92XQY_edit-your-search-form-ministores > .m-field-wrap > .l-xs-col-4 > .analytics-click')
		await page.click('#edit-search-panel > #YSS92XQY_edit-your-search-form-ministores > .m-field-wrap > .l-xs-col-4 > .analytics-click')
		await page.waitForSelector('.mfp-wrap > .mfp-container > .mfp-content > .tile-unsuccessful-sell-overlay > .mfp-close')
		await page.click('.mfp-wrap > .mfp-container > .mfp-content > .tile-unsuccessful-sell-overlay > .mfp-close')
		await navigationPromise
		await page.screenshot({
			path: '../screenshots/page1.png'
		})
		await page.pdf({path: '../pdfs/page1.pdf'})
		await browser.close()
	} catch (error) {
		console.log(error)
	}
})()
```

Error: 
![image](https://user-images.githubusercontent.com/45570407/52559245-18556d80-2df5-11e9-83eb-b62b39288987.png)

What am I doing wrong?

Thank you in advance

**Comment by airda2895** [comment]
Fixed!

Apparently, the extension seems to not generate appropriate code, I have tried to go through the DOM elements until the button and it worked!

Puppeteer recorder needs to be fixed apparently.

**Comment by zivtamary** [comment]
> Fixed!
> 
> Apparently, the extension seems to not generate appropriate code, I have tried to go through the DOM elements until the button and it worked!
> 
> Puppeteer recorder needs to be fixed apparently.

How exactly did you fix it? I'm having the same issue, please respond :)

**Comment by carlkentor** [comment]
me as well :(

**Comment by RedhwanAhmed** [comment]
Same here.

I run multiple tests parallel in separate browsers which cause this error to occur even though it doesn't when i run that particular tests alone.
