### ISSUE TITLE
where should I put the folder 'chrome-win'? I have downloaded it manually.

### ISSUE THREAD

**Issue by onrea** [puppeteer/puppeteer#3984]
Because of some Google restriction on our IPs, it does not allow us to fetch something from its services. So `yarn add puppeteer` was not able to download the chromium:

    Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/624492/chrome-win.zip

I have downloaded _chrome-win.zip_ directly (behind a proxy. Now, where should I put the extracted file to be accessible by puppeteer-core?

* Puppeteer-Core version: v1.13.0
* Platform / OS version: Windows 10
* URLs (if applicable): Local, in the range of 172.*.*.*
* Node.js version: 10 (LTS)

+ The Google Chrome version 71.0.3578.98 (Official Build) (64-bit) is installed previously.

**Comment by cr33dx** [comment]
![screenshot 4](https://user-images.githubusercontent.com/8844755/52584479-2dafb380-2e58-11e9-87cf-b517b43f4ef3.png)
