### ISSUE TITLE
Cannot get javascript variable in by evaluate function

### ISSUE THREAD

**Issue by AonzVongsunthorn** [puppeteer/puppeteer#3986]
Hi Everyone.
I got a problem when using evaluate to get some javascipt variable in window scope.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: OSX
* URLs (if applicable): 
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

puppeteer.launch({headless: false, devtools: true}).then(async browser => {

    const page = await browser.newPage();
    let url = 'https://www. h k     b n . n e t / p e r s o n a l / m o b i l e / e n / p h o n e / iP h o ne-8-Plus'.replace(/ /g, '');
    await page.goto(url, {'waitUntil': 'networkidle0', 'timeout': 0}).catch(e => {

        console.log(e.toString());

    });

    // await page.waitForFunction(() => 'ga' in window);

    console.log('ga variable problem', await page.evaluate(() => ga)); // Got undefined but it's should be show google analytics information
    console.log('----------------');

    await page.goto('https://akoant.com', {'waitUntil': 'networkidle0', 'timeout': 0}).catch(e => {

        console.log(e.toString());

    });

    console.log('ga variable correct', await page.evaluate(() => ga.getAll())); // work fine ....

    await browser.close();

});

```

**What is the expected result?**
I should return google analytics object like i input javascript command into developer tools.

<img width="551" alt="screen shot 2562-02-12 at 17 56 36" src="https://user-images.githubusercontent.com/21377813/52631287-fe995080-2ef0-11e9-98b4-6881b71c1ba7.png">

**What happens instead?**
Got wrong result.
<img width="694" alt="screen shot 2562-02-12 at 18 04 07" src="https://user-images.githubusercontent.com/21377813/52631276-f50fe880-2ef0-11e9-9ae0-fbd7de9c7de6.png">

Thank you.

**Comment by vsemozhetbyt** [comment]
From `page.evaluate()`, you can only transfer serializable values (values that can be serialized via `JSON.stringify()`). Functions cannot be serialized and `undefined` is returned instead. In your second case `page.evaluate()` returns serializable object and it works properly. If you try this line:
```js
console.log('ga variable problem', await page.evaluate(() => ga.toString()));
```
you will see that the function is defined:
```
ga variable problem function(a){J(1);Z.D.apply(Z,[arguments])}
```

**Comment by AonzVongsunthorn** [comment]
> From `page.evaluate()`, you can only transfer serializable values (values that can be serialized via `JSON.stringify()`). Functions cannot be serialized and `undefined` is returned instead. In your second case `page.evaluate()` returns serializable object and it works properly. If you try this line:
> 
> ```js
> console.log('ga variable problem', await page.evaluate(() => ga.toString()));
> ```
> 
> you will see that the function is defined:
> 
> ```
> ga variable problem function(a){J(1);Z.D.apply(Z,[arguments])}
> ```

Thanks, It's save a lot of my time.
