### ISSUE TITLE
doc: Body class remainders

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#399]
At the end of the [`class: Request`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-request) description, there is a remainder of the [deleted Body class](https://github.com/GoogleChrome/puppeteer/commit/ba37a4f82d8e8fc23cb13b24a73d5d7ebb8ea7b9):

>  Request implements Body mixin, which in case of HTTP POST requests allows clients to call request.json() or request.text() to get different representations of request's body.

In the [`class: Response`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-request) description, there is also a remainder of the deleted Body class:

> Response implements Body mixin, which allows clients to call response.json() or response.text() to get different representations of response body.

Sorry, I am not sure how these fragments should be cleaned.

**Comment by Riskoff** [comment]
I'm not sure how it should be cleaned
