### ISSUE TITLE
Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome ENOENT

### ISSUE THREAD

**Issue by AdamBD** [puppeteer/puppeteer#3994]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: MAC 10.14.3
* URLs (if applicable):
* Node.js version: v8.9.4

I have been trying to get my Node application, using Puppeteer as the testing framework to run via docker. It works perfectly well when running locally on my. However when running via container I keep running into the same issue.

I have tried almost every boiler-plate Dockerfile I have seen from other users online but none of them can address the issue Im seeing.

`Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome ENOENT`

When I see other people with this issue they all seem to show different linux versions and not the specific one I am seeing after download: linux-609904. What is the best way to audit whats wrong with this version?

**Comment by ryantsangai** [comment]
I have meet the same error when using prerender-spa-plugin inside docker

`Failed to launch chrome! spawn /web/node_modules/prerender-spa-plugin/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome ENOENT`

And here is the result of `/web/node_modules/prerender-spa-plugin/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux`

MEIPreload/             icudtl.dat              locales/                natives_blob.bin        xdg-mime
chrome-wrapper          libEGL.so               nacl_helper             product_logo_48.png     xdg-settings
chrome_100_percent.pak  libGLESv2.so            nacl_helper_bootstrap   resources/              
chrome_200_percent.pak  libclearkeycdm.so       nacl_irt_x86_64.nexe    resources.pak

**Comment by andrerpena** [comment]
I'm having this problem running Puppeteer inside Digital Ocean Ubuntu

**Comment by matthewhardern** [comment]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md should help, I installed the ubuntu packages and this was then solved

**Comment by aslushnikov** [comment]
> Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome ENOENT

@AdamBD the `ENOENT` error means there's no executable file on your file system; you probably skipped or aborted chromium download.

> I have tried almost every boiler-plate Dockerfile I have seen from other users online but none of them can address the issue Im seeing.

Have you tried our [docker container](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)? We run our own tests in a docker container and they work just fine.

Hope this helps

**Comment by ben-turner** [comment]
I'm running puppeteer on `node:12-alpine`. After building the container, I've been shelling into it with `docker run -ti [container] /bin/sh`. I can then see that there is indeed a binary at `/home/node/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome`, but if I try to run it, I get the error `/bin/sh: ./chrome: not found`, which matches up with the ENOENT error that I get from puppeteer. I'll follow up here if I find a solution, but I just wanted to point out that it might not be a failed download in case anyone else comes across this.

**Comment by arapocket** [comment]
> I'm running puppeteer on `node:12-alpine`. After building the container, I've been shelling into it with `docker run -ti [container] /bin/sh`. I can then see that there is indeed a binary at `/home/node/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome`, but if I try to run it, I get the error `/bin/sh: ./chrome: not found`, which matches up with the ENOENT error that I get from puppeteer. I'll follow up here if I find a solution, but I just wanted to point out that it might not be a failed download in case anyone else comes across this.

I shelled into docker to try that and I got the same issue as well.
EDIT: I'm on node:10-alpine for reference

**Comment by ben-turner** [comment]
@arapocket Thanks for commenting—I forgot to follow up after I found a solution. It's been a couple of weeks so I don't remember exactly which change fixed it, but here's the configuration I'm running:

In my Dockerfile I have
```
RUN apk add --nocache udev ttf-freefont chromium git
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser

// npm install, etc.
```

And then to launch the browser

```
puppeteer.launch({
  executablePath: process.env.CHROMIUM_PATH,
  args: ['--no-sandbox'], // This was important. Can't remember why
});
```

I also locked puppeteer to 1.17.0 in my package.json. I think that was to make the chromium and puppeteer versions match.

**Comment by Shigugu** [comment]
@ben-turner Thank you very much,

I had exactly the same issue, getting a:  
`Error: Failed to launch chrome! spawn /builds/dev/ui/frontend/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome ENOENT`
when trying to run integration tests via Puppeteer in a Docker container (node:12-alpine) for my project's CI (on Gitlab).

Running chromium from `/usr/bin/chromium-browser` instead of using Puppeteer's chromium installation path solved it !

**Comment by ashkanRmk** [comment]
> @ben-turner Thank you very much,
> 
> I had exactly the same issue, getting a:
> `Error: Failed to launch chrome! spawn /builds/dev/ui/frontend/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome ENOENT`
> when trying to run integration tests via Puppeteer in a Docker container (node:12-alpine) for my project's CI (on Gitlab).
> 
> Running chromium from `/usr/bin/chromium-browser` instead of using Puppeteer's chromium installation path solved it !

I have the same issues, but hasn't resolved yet with this solution :(

**Comment by razinj** [comment]
Hey everyone, I had the same issue today in my Node JS app running inside `node:12.16.3-alpine` image.
I tried @ben-turner solution and I just wanted to point out that instead of `--nocache` consider using `--no-cache` since it gave me an error pointing it out.
Context: In the `apk add --no-cache`

**Comment by prototypicalpro** [comment]
Hello all, I had this same issue as well on Travis CI. The solution I was able to implement was switching from Node.JS 14 to Node.JS 12 as per [this documentation]( https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-is-downloaded-but-fails-to-launch-on-nodejs-14).

**Comment by SaveYourTime** [comment]
> @arapocket Thanks for commenting—I forgot to follow up after I found a solution. It's been a couple of weeks so I don't remember exactly which change fixed it, but here's the configuration I'm running:
> 
> In my Dockerfile I have
> 
> ```
> RUN apk add --nocache udev ttf-freefont chromium git
> ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
> ENV CHROMIUM_PATH /usr/bin/chromium-browser
> 
> // npm install, etc.
> ```
> 
> And then to launch the browser
> 
> ```
> puppeteer.launch({
>   executablePath: process.env.CHROMIUM_PATH,
>   args: ['--no-sandbox'], // This was important. Can't remember why
> });
> ```
> 
> I also locked puppeteer to 1.17.0 in my package.json. I think that was to make the chromium and puppeteer versions match.

Thanks, this really helps a lot!
Now, I can run puppeteer on my aws eb.

The only thing that needs to be fixed is to set the RUN options with `--no-cache`, instead of `--nocache`.

I have no idea why do we need these packages `udev ttf-freefont git`, so I remove them and only install the `chromium`.
It works fine anyway.

**Comment by udhayamoorthys** [comment]
@ben-turner and @arapocket , I'm using local html (string content) to generate PDF. how to initialize the puppeteer module
Ref: https://www.npmjs.com/package/pdf-puppeteer

```
let html = '<html><body>hello</body></html>';
convertHTMLToPDF(html, callback, options, puppeteerArgs, remoteContent);
```

**Comment by ben-turner** [comment]
@udhayamoorthys Create a new issue. That doesn't really have anything to do with this issue from a year and a half ago unless you're seeing the same error.

Also, read the docs and try some things. Try to figure it out on your own before you start pinging random people.

**Comment by 0xtinkle** [comment]
I used to have problem for CI/CD of headful chrome extension testing and finally resolved with this package
https://github.com/mujo-code/puppeteer-headful
It also has docker file of headful setup process and this link would be helpful.

**Comment by knapo** [comment]
I'm using puppeteer and grover on alpine and was also getting:

```
Grover::JavaScript::Error:
Failed to launch the browser process! spawn [FILTERED]/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome ENOENT
```

Installing chromium from alpine packages and custom `executablePath` (also `executable_path` option in grover) solved the issue.

Instead `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD ` env var, I used `puppeteer-core` package.

Thanks for the hints!

**Comment by bboydflo** [comment]
At the moment I am trying to use latest puppeteer (5.5.0) which should use chrome 88 (see docs: https://github.com/puppeteer/puppeteer/blob/main/versions.js).

The whole point of using the chrome version that comes with puppeteer (in my case I locked the puppeteer version) was to be more predictible about which version of chrome I use. I am using puppeteer for image snapshots testing and in theory it might be possible that two different chromium versions might render different snapshots of the same page.

So the question still remains: does anyone have a sample dockerfile that uses node:alpine with puppeteer that actually uses the chromium version that ships with puppeteer?

PS: I also found this project https://github.com/Zenika/alpine-chrome and used that base image (unfortunately was not able to understand it very well) without having to change puppeteer's config (executablePath). So I hope I actually use the version of chromium that comes with puppeteer.

**Comment by knapo** [comment]
@bboydflo I use puppeteer with ruby and unoconv on apline. Here is Dockerfile I use: https://gist.github.com/knapo/3c146ff45da43822edabd6f46bfd3f39. If you don't need ruby you can probably use pure alpine as a base.

Additionally, I have `executablePath` (puppeteer's config) set to `/usr/bin/chromium-browser`

**Comment by joereg4** [comment]
Used Homebrew to install Chromium on a Mac and the executable path was `/usr/local/bin/chromium` which works as the path for the Browser preview Chrome Executable in VS Code.

**Comment by bauti-defi** [comment]
> @arapocket Thanks for commenting—I forgot to follow up after I found a solution. It's been a couple of weeks so I don't remember exactly which change fixed it, but here's the configuration I'm running:
> 
> In my Dockerfile I have
> 
> ```
> RUN apk add --nocache udev ttf-freefont chromium git
> ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
> ENV CHROMIUM_PATH /usr/bin/chromium-browser
> 
> // npm install, etc.
> ```
> 
> And then to launch the browser
> 
> ```
> puppeteer.launch({
>   executablePath: process.env.CHROMIUM_PATH,
>   args: ['--no-sandbox'], // This was important. Can't remember why
> });
> ```
> 
> I also locked puppeteer to 1.17.0 in my package.json. I think that was to make the chromium and puppeteer versions match.

This worked for me on latest puppeteer with venom-bot (2.2.4) 

My Dockerfile is the following.

```
FROM node:14.15.5-alpine

WORKDIR /usr/src/app/

COPY package.json /usr/src/app

RUN apk add --no-cache udev ttf-freefont chromium git
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser

RUN npm install 

COPY src/ /usr/src/app

CMD [ "node", "server.js" ]
```

Used the following puppeteer options inside the venom-bot create config.

`puppeteerOptions:{args:['--no-sandbox'], executablePath: process.env.CHROMIUM_PATH}`

Thank you for your help!!!

**Comment by nvuillam** [comment]
For those who do not have access to puppeteer options (like when using a package where puppeteer is a dependency), you can use the following solution with variable **PUPPETEER_EXECUTABLE_PATH**

```dockerfile
RUN apk add --update --no-cache \
            chromium \
            nodejs \
            npm

# Do not use puppeteer embedded chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
ENV CHROMIUM_PATH="/usr/bin/chromium-browser"
ENV PUPPETEER_EXECUTABLE_PATH="${CHROMIUM_PATH}"

# Npm install...
```

Working example here: https://github.com/hardisgroupcom/sfdx-hardis/blob/main/Dockerfile

**Comment by artur79** [comment]
> I'm using puppeteer and grover on alpine and was also getting:
> 
> Instead `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD ` env var, I used `puppeteer-core` package.
> 
> Thanks for the hints!

@knapo how did you overcome this warning when using puppeteer-core instead puppeteer ? ```Grover::DependencyError (Cannot find module 'puppeteer'. You need to add it to '/app/package.json' and run 'npm install')```
I also try to run Grover on Docker

**Comment by knapo** [comment]
@artur79 Sorry for the confusion, eventually I didn't, because grover does not support overriding the package name and it's required based on puppeteer's doc: `const puppeteer = require('puppeteer-core');`. 
So I ended up setting `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` env var + using `chromium` alpine package + passing `executable_path: '/usr/bin/chromium-browser'` to grover config and it worked well for me.

**Comment by artur79** [comment]
@knapo right, tried the same and works straight away from Grover. I also have in Dockerfile ```ENV GROVER_NO_SANDBOX true``` but not sure if required

**Comment by andreyluiz** [comment]
Late to the party, but Puppeteer has a section in the docs on how to run on Alpine docker.

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine
