### ISSUE TITLE
Amazon Connect login page never finishes loading using puppeteer

### ISSUE THREAD

**Issue by theccalderon** [puppeteer/puppeteer#3995]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: macOS Mojave 10.14.3
* URLs (if applicable): https://ccalderon-reinvent.awsapps.com/connect/ccp#/
* Node.js version: 8.11.1

**What steps will reproduce the problem?**

```
const browser = await puppeteer.launch();

const page = await browser.newPage();
const url = ' https://ccalderon-reinvent.awsapps.com/connect/ccp#/';

await page.goto(url, {waitUntil: 'domcontentloaded'});

console.log(await page.content());

await browser.close();
```

1. Execute the code above

**What is the expected result?**
The content of the page should be logged to the console.

**What happens instead?**
The request times out.

**Comment by vsemozhetbyt** [comment]
I am not sure what is going on here, maybe some race condition with redirects. But this is a brittle way that solves this issue on my machine:
```js
await page.goto(url, { waitUntil: 'domcontentloaded' });
await page.waitFor(5000);
console.log(await page.content());
```
No other ways like `page.waitForSelector('div.LoginForm');`, or `await page.goto(url, { waitUntil: 'networkidle0' });`, or , or `page.waitForNavigation({ waitUntil: 'networkidle0' });`  fix it for me: always the same `Error: Execution context was destroyed, most likely because of a navigation.` happens.

**Comment by ccalderon911217** [comment]
I copied and pasted your code in https://try-puppeteer.appspot.com/ but still facing the same error. Also tested on my Mac and same.

**Comment by theccalderon** [comment]
Yeah that kind of works but I'm trying to log in after that using something like this:
 
```
console.log('waiting for username input');
await page.waitForSelector('#wdc_username');
console.log('filling login form...');
await page.type('input[type="username"]', CCP_USERNAME);
await page.focus('input[type="password"]');
await page.keyboard.type(CCP_PASSWORD);
await page.keyboard.press('Enter');
console.log('Submitted login form');
```

and that never finishes loading. I can confirm there is a selector called #wdc_username.

**Comment by vsemozhetbyt** [comment]
Sorry, I cannot test this. I am not registered, but at least I have failed log-in page after successful form sending with random user/password pair.

**Comment by theccalderon** [comment]
you do @ccalderon911217 ??? Can you please share your code? I can't get that.

**Comment by vsemozhetbyt** [comment]
I've just used your code:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });

    const page = await browser.newPage();
    const url = ' https://ccalderon-reinvent.awsapps.com/connect/ccp#/';

    await page.goto(url, { waitUntil: 'domcontentloaded' });
    await page.waitFor(5000);
    console.log(await page.content());

    console.log('waiting for username input');
    await page.waitForSelector('#wdc_username');

    console.log('filling login form...');
    await page.type('input[type="username"]', 'CCP_USERNAME');
    await page.focus('input[type="password"]');
    await page.keyboard.type('CCP_PASSWORD');
    await page.keyboard.press('Enter');

    console.log('Submitted login form');

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

![1](https://user-images.githubusercontent.com/10393198/52813397-5dea9280-30a2-11e9-91eb-c6f62d242a42.png)

**Comment by theccalderon** [comment]
I'll keep researching but I'm still getting a timeout...

**Comment by theccalderon** [comment]
Please refer to [https://stackoverflow.com/questions/54657355/how-to-use-puppeteer-to-automante-amazon-connect-ccp-login](url).

This seems to be a bug with chromium version 73.x as it's currently working fine for version 72.

cc: @vsemozhetbyt

**Comment by aslushnikov** [comment]
@ccalderon911217 so does this repro with Puppeteer v1.13.0?

**Comment by theccalderon** [comment]
@aslushnikov what version of chromium comes with puppeteer 1.13? I haven't tested myself.

**Comment by aslushnikov** [comment]
@ccalderon911217 pptr v1.13.0 comes with Chromium 74.0.3723.0 (r637110)
