### ISSUE TITLE
Puppeteer API to block (3rd party) cookies

### ISSUE THREAD

**Issue by martinschierle** [puppeteer/puppeteer#3998]
Many browsers today have cookie-blocking capabilities (notably Safari's ITP) and it would be great to be able to simulate this with Puppeteer for testing.
For this it would be great to:

- Block all cookies in general
- and/or: block only 3rd party cookies

Right now it's easy to delete all cookies via Puppeteer API (which is a bit different to blocking), or a bit more cumbersome to block cookies via Chromre's [RDP](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDocumentCookieDisabled). For the second one a higher level API would be great, but in general it would also be great to have this just for 3rd party cookies. As a workaround I could probably interject all requests, and delete cookie header fields from 3rd party requests.

**Comment by aslushnikov** [comment]
Hey @martinschierle, thanks for raising this topic.

For the [`Emulation.setDocumentCookieDisabled`](https://vanilla.aslushnikov.com/#Emulation.setDocumentCookieDisabled) API - let's keep it as-is for now. It's easy to access it through CDP - shouldn't be a problem for power users.

Regarding the 3rd party cookies - I'd hold off implementing any strategy here as a part of Puppeteer. As you mentioned, Safari-like cookie blocking can be done with request interception, and this is probably the way to go for now. Probably it'll be enough for the foreseeable future. 

If/when we have a clear story and demand around 3rd party cookies, we can think about it again.

**Comment by pkieltyka** [comment]
any suggestions on how to block 3rd party cookies in puppeteer? it would help a lot when writing tests as most browsers are moving in this direction

**Comment by jzaefferer** [comment]
This seems to work, though not in headless mode:
```
await page.goto('chrome://settings/cookies');
await page.evaluate(() =>
    document
        .querySelector('settings-ui')
        .shadowRoot.querySelector('settings-main')
        .shadowRoot.querySelector('settings-basic-page')
        .shadowRoot.querySelector('settings-section settings-privacy-page')
        .shadowRoot.querySelector('settings-cookies-page')
        .shadowRoot.querySelector('#blockThirdParty')
        .shadowRoot.querySelector('#label')
        .click()
);
```
