### ISSUE TITLE
Page break within iFrame

### ISSUE THREAD

**Issue by real-ashwin** [puppeteer/puppeteer#4004]
Is there a way to do page breaks for saveAsPdf for content that is inside iFrames ?

I tried the `page-break-after` and `page-break-before` property but it looks like they don't work when used with iFrame.

Is there any way to force content to move to a new page?

**Comment by aslushnikov** [comment]
Puppeteer exposes chromium's PDF capabilities, so the question falls outside of our scope here. I'd ask this on Stackoverflow instead, or maybe somewhere on PDFium google group?
