### ISSUE TITLE
response.remoteAddress() when use proxy

### ISSUE THREAD

**Issue by dolima** [puppeteer/puppeteer#4012]
* Puppeteer version: 1.12.2
* Platform / OS version: Debian 9.6 stretch
* Node.js version: 10.14.0

**The code below uses to get all IP of servers requested when the webpage loading**

```
const puppeteer	  = require('puppeteer');

(async () => {

const browser = await puppeteer.launch({
    args: ['--proxy-server=XXX.YYY.X.ZZ:5002']
   });

const page = await browser.newPage();

page.on('response', async(response) => {
    console.log(response.remoteAddress().ip);
   });

await page.goto('https://github.com/');

await browser.close();

})();
```
Instead of servers IP list, there just proxy IP shown in all requests.
When proxy not used, everything is ok. But what should to do, if proxy needed?
Please, help

**Comment by aslushnikov** [comment]
@dolima I don't think there's much we can do regarding this; it's up to a proxy to provide you with a real IP address you're contacting.
