### ISSUE TITLE
not loaded all attributes

### ISSUE THREAD

**Issue by Trahtenberg** [puppeteer/puppeteer#4020]
Hello everybody!
I have some problems loading image attributes.  Some elements not have src. He does not have time to loaded. I tried experimenting with waitUntil (domcontentloaded, networkidle0 etc) and waitForNavigation... nothing helped. But page.screenshot({path: 'results.png', fullPage: true}); it worked for me.
Which parameter must be specified in order not to take a screenshot, but to load all attributes of the elements?

**Comment by vsemozhetbyt** [comment]
Can you provide a small complete script that reproduces the issue?

**Comment by Trahtenberg** [comment]
yes of course sorry for not doing it right away

```
const puppeteer = require('puppeteer');

const browser = await puppeteer.launch({
	headless: true,
});
const page = await browser.newPage();
await page.setViewport ({
	width: 1349,
	height: 657,
});
await page.goto(Url,{waitUntil:['domcontentloaded']});

//await page.screenshot({path: 'results.png', fullPage: true});

const html = await page.$('html');

const result = await page.evaluate((pag,options) => {
var items = pag.querySelectorAll(options.container);
//then I transfer to the Array.from(items).map(prod => {

```

**Comment by vsemozhetbyt** [comment]
Sorry for not being clear, I've meant a real script with the real URL that can be tested by others locally to understand what is going on)

**Comment by Trahtenberg** [comment]
sent you by email

**Comment by vsemozhetbyt** [comment]
If I understand correctly, some page elements are lazy-loaded: images have their src in `data-src` first and this attribute is copied to `src` when the element is scrolled into view (i.e. is visible in the viewport). You can copy the attribute from the `data-src` or apply this solution: in a cycle, scroll each element into view, wait some time and then get the `src` data:

```js
const result = await page.evaluate(async () => {
  const data = [];
  const prods = document.querySelectorAll('...');

  for (const prod of prods) {
    prod.scrollIntoView();
    await new Promise(r => setTimeout(r, 100));

    data.push({
      name: prod.querySelector('...').getAttribute('title'),
      img: prod.querySelector('...').getAttribute('src'),
      // ...
    });
  }

  return data;
});
```

**Comment by Trahtenberg** [comment]
It works!
Fun decision, thanks very much!
