### ISSUE TITLE
Error: Page.enable wasn't found  (Raspberry Pi 3B+, Raspbian Stretch, Chromium 65)

### ISSUE THREAD

**Issue by 37wh5r** [puppeteer/puppeteer#4025]
When executing the example.js from the Puppeteer documentation (modified to use headless=false and executablePath='/usr/bin/chromium-browser'), the new page opens, but then no navigation happens. Starting with env DEBUG="puppeteer:*" reveals the error mentioned in the title. Any idea what could cause this?

`  puppeteer:protocol SEND ► {"method":"Target.setDiscoverTargets","params":{"discover":true},"id":1} +0ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"4a2cfeb6-b78a-4859-8088-98637d9e0122","type":"browser","title":"","url":"","attached":false}}} +11ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"FBD991858BC33D22C8F76D37BDF20268","type":"page","title":"","url":"about:blank","attached":false}}} +3ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"caef2086-c5c0-4ac9-9ca1-2b0ca81df814","type":"browser","title":"","url":"","attached":true}}} +1ms
  puppeteer:protocol ◀ RECV {"id":1,"result":{}} +1ms
  puppeteer:protocol SEND ► {"method":"Target.createTarget","params":{"url":"about:blank"},"id":2} +5ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"F388D2F9EB49EBD9B5E91C116136DBC9","type":"page","title":"","url":"","attached":false}}} +6ms
  puppeteer:protocol ◀ RECV {"id":2,"result":{"targetId":"F388D2F9EB49EBD9B5E91C116136DBC9"}} +4ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"F388D2F9EB49EBD9B5E91C116136DBC9","type":"page","title":"about:blank","url":"about:blank","attached":false}}} +113ms
  puppeteer:protocol SEND ► {"method":"Target.attachToTarget","params":{"targetId":"F388D2F9EB49EBD9B5E91C116136DBC9","flatten":true},"id":3} +4ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"FBD991858BC33D22C8F76D37BDF20268","type":"page","title":"about:blank","url":"about:blank","attached":false}}} +2ms
  puppeteer:protocol ◀ RECV {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"F388D2F9EB49EBD9B5E91C116136DBC9","type":"page","title":"about:blank","url":"about:blank","attached":true}}} +1ms
  puppeteer:protocol ◀ RECV {"method":"Target.attachedToTarget","params":{"sessionId":"F388D2F9EB49EBD9B5E91C116136DBC9:1","targetInfo":{"targetId":"F388D2F9EB49EBD9B5E91C116136DBC9","type":"page","title":"about:blank","url":"about:blank","attached":true},"waitingForDebugger":false}} +1ms
  puppeteer:protocol ◀ RECV {"id":3,"result":{"sessionId":"F388D2F9EB49EBD9B5E91C116136DBC9:1"}} +2ms
  puppeteer:protocol SEND ► {"sessionId":"F388D2F9EB49EBD9B5E91C116136DBC9:1","method":"Page.enable","params":{},"id":4} +4ms
  puppeteer:protocol ◀ RECV {"error":{"code":-32601,"message":"'Page.enable' wasn't found"},"id":4} +4ms`

**Comment by 37wh5r** [comment]
Using Puppeteer 1.12.1. Is it too new, or is Chromium too old?

**Comment by aslushnikov** [comment]
@37wh5r you're running old Chromium with new Puppeteer - this won't work. (see our [faq entry](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy) if you're curious why).

For Chrome 65 you need Puppeteer v1.0.0; the compatability table is available at the beginning of https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md and on https://pptr.dev in a Puppeteer version selector.

Hope this helps.
