### ISSUE TITLE
page.pdf dose not support -webkit-mask-image?

### ISSUE THREAD

**Issue by minzojian** [puppeteer/puppeteer#4026]
try to use page.pdf to generate a pdf like this
https://jsfiddle.net/minzojian/e9y7ajk0/

view the html content in headless off mode, looks normal,
![image](https://user-images.githubusercontent.com/361781/52908105-94dec500-32a9-11e9-820e-a546bf494d94.png)

 however, the generated pdf  lost the clip features

![image](https://user-images.githubusercontent.com/361781/52908077-30236a80-32a9-11e9-8ebd-2c221aba2a9e.png)

is that a bug or something?

PS: the default font does not look the same either

**Comment by aslushnikov** [comment]
Hey @minzojian,

First of all, what a lovely dog. :heart: 

On a serious note though, I tried printing this using Chromium's "Save as PDF..." and it indeed doesn't support mask image. That's a Chromium issue, so if you report it over to https://crbug.com/new than Chromium PDF team will be happy to assist :-)

If you do end up reporting it upstream, please post a link here to the upstream bug to help future generations. Thanks!
