### ISSUE TITLE
Puppeteer High Cpu Usage

### ISSUE THREAD

**Issue by talha0324** [puppeteer/puppeteer#4027]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version:  Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-1037-azure x86_64)
* URLs (if applicable):
* Node.js version: v10.12.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run the provided code, and give it some time. The CPU usage goes upto 100% after few hours
code : 
`
         
        // @ts-ignore-file
        import * as cheerio from "cheerio";
        import * as request from "request";
        import * as fs from "fs";
        import * as shell from "shelljs";
        import pup = require("puppeteer")

        class App {
            //@ts-ignore
            public browser:pup.Browser ;
            public appendToFile(file:string, content:string): Promise<string>{
                return new Promise<string>((resolve, reject) => {
                    try {
                    fs.appendFileSync(file, content)
                    resolve("DONE")
                    } catch(e) {
                        reject(e)
                    }
                });
            }
            public loadPage(url: string): Promise<any> {
                return new Promise<any>((resolve, reject) => {
                    request.get(url, async (err, res, html) => {
                        if(!err && res.statusCode == 200) {
                            resolve(html)
                        }
                        else {
                            if(err)
                                reject(err);
                            else
                                reject(res);
                        }
                    });
                });
            }    
            public step1(url: string): Promise<string> {
                return new Promise<string>(async (resolve, reject) => {
                    let page !: pup.Page; // | undefined;
                    try {
                    let next=false;
                    let urlLink = url.split('::')[0];
                    let pageCount = parseInt(url.split('::')[1]);
                    let first = true;
                    let header = "unknown";
                    let f = urlLink.split('/');
                    let folder = f[f.length-3];
                    folder = folder || header;
                    let path = "data/"+folder; 
                    shell.mkdir('-p', path);
                    page = await this.browser.newPage();
                    console.log("opened a tab")

                    await page.goto(urlLink, {timeout:0});
                    let countt = 1;
                    let x ;
                    if(pageCount) {
                    x = await page.evaluate((C)=>{
                            //@ts-ignore
                            for(i=1;i<C;i++){
                            //@ts-ignore
                            var next_page = current_page+1;
                            //@ts-ignore
                            current_page = next_page;
                            //@ts-ignore
                            current_start = current_start + count;
                            //@ts-ignore
                            current_end = current_end + count;
                            }
                            return {
                                //@ts-ignore
                                "current_page":current_page,
                            };
                        }, pageCount);
                        countt =  pageCount;
                    }
                    console.log("-->" + JSON.stringify(x))
                    // await this.delay(60*1000)
                    
                    do{
                        next = false;
                        console.log('ev 1')
                        let res= await page.evaluate(()=>{
                            let e = document.querySelectorAll('.ch-product-view-list-container.list-view li ul > li > h6 > a');
                            let  p: string[] = [];
                            e.forEach((v) =>{
                                p.push(("https://www.link.com") + (v.getAttribute("href") as string));
                            })
                            return p;
                        })
                        console.log('ev 1 done')

                        let c =1;
                        console.log('going in 8 count scrap')
                        for(const d of res) {
                            try {
                                await this.step2(d,folder, c.toString())
                            } catch(_e) {
                                console.log(_e)
                                fs.appendFileSync("./error-2.txt" , urlLink + " ### " + d + "\n");
                            }
                            c++;
                        }
                        console.log('going in 8 count scrap _- DOne')
                        // let p=[];
                        // let c =1;
                        // console.log('pushing promises')
                        // for(const d of res) {
                        //     p.push(await this.step2(d,folder, c.toString()).catch((_e)=>{
                        //         console.log(_e)
                        //         fs.appendFileSync("./error-2.txt" , urlLink + " ### " + d + "\n");
                        //         return "done";
                        //     }))
                        //     c++;
                        // }
                        // console.log('pushing promises done + awaiting')
                        // await Promise.all(p);
                        // console.log('awating done')

                        await this.appendToFile('./processed.txt', urlLink + "::" + countt.toString() + "\n").catch(e=>e);
                        console.log(urlLink+"::"+countt)
                        countt++;
                        console.log('ev 2')
                        let e = await page.evaluate(()=>{
                            let ele = document.querySelector('#pagination-next') as Element;
                            let r =ele.getAttribute('style');
                            return r || "";
                        })
                        console.log('ev 2 done + clicking')
                        if(e == "") {
                            next = true;
                            await page.click('#pagination-next');
                            // @ts-ignore
                            // await page.evaluate(()=>{document.querySelector('#pagination-next')[1].click()})
                            await this.delay(300)
                        }
                        console.log(' clicking done')
                    } while(next)
                        resolve("page all scrapped");
                    } catch(errrr) {
                        reject(errrr)
                    } finally {
                        console.log('in finally')
                        try {
                        await page.close();
                        console.log("tab closed")
                        }  catch (e) {
                            console.log("tab not closed");
                        }
                    }
                });
            }    
            public step2(url: string, folder:string, file:string): Promise<string> {
                return new Promise<string>(async(resolve, reject) => {
                    try {
                        console.log('requesting page')
                        let html = await this.loadPage(url);
                        console.log('requesting page Done')
                        let $ = cheerio.load(html);
                        let ress:any = {}
                        let t =$(".qal_title_heading").text();
                        if(t) {
                            ress.header = t.replace(/"/g,"'").replace(/\n|\r|\t/g,"");
                        }
                        let d = $("div.ch_formatted_text.qal_thread-content_text.asker").html();
                        if(d){
                            ress.body = d.replace(/"/g,"'").replace(/\n|\r|\t/g,"");
                        }
                        // let sprit = "-------------------------------";
                        let filename =  "data"+file+".json"//((t.replace(/[^\w\s]/gi, "")).substring(0,250)+".txt")
                        let data = JSON.stringify(ress)//t +sprit + d + "\n---end---\n";
                        await this.appendToFile("./data/"+ folder + "/" +filename, data+",\n")
                        resolve("done");
                    } catch (err) {
                        reject(err)
                    }
                });
            }
            public delay(ms: number): Promise<string> {
                return new Promise<string>((resolve) => {
                    setTimeout(() => {
                        resolve("done")
                    }, ms);
                })
            }
        }
        async function main(){
            process.on('SIGTERM', ()=>{
                console.log("SigTerm received");
                process.exit(1);
            });
            process.on('SIGINT',  ()=>{
                console.log("SigInt received");
                process.exit(1);
            });
            let path = "data/unknown"
            shell.mkdir('-p', path);
            let c = new App();
            let list: string[] = [];
            console.log(process.argv[2])
            require('fs').readFileSync(process.argv[2], 'utf-8').split(/\r?\n/).forEach((line: string) =>{
                list.push(line)
            })
            console.log('total links->' + list.length)
            
            c.browser =  await pup.launch({headless: false,timeout:0, });
            for(const l of list){
                await c.step1(l).then(e=>{
                    fs.appendFileSync("./processedLinks.txt" , l);
                }).catch(e=>{
                    console.log(e)
                    fs.appendFileSync("./error.txt", l);
                });
            }
        }
        main();

`

**What is the expected result?**
Smooth execution.

**What happens instead?**
High Cpu usage of puppeteer chrome and every other process goes to starve.

**Comment by aslushnikov** [comment]
@talha0324 any chance you can reduce your snippet from 200 lines of TS to 20 lines of JS? It'll *drastically* help us to help you.

**Comment by talha0324** [comment]
you can just look at step2() function.
it's only function that is running.
let me know if you need me to do something else.

**Comment by aslushnikov** [comment]
@talha0324 the `step2` doesn't do anything related to headless chromium; I see that all the work is happenning in `step1`. 

There are some loops and other code, but I'm not sure what exactly contributes to high CPU usage.
What makes you think it's Chromium and not the parent node.js process?
