### ISSUE TITLE
Misplaced screenshot due to hover

### ISSUE THREAD

**Issue by manteb** [puppeteer/puppeteer#4031]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: OSX 10.13.6
* URLs (if applicable): https://www.vrt.be/vrtnws/nl/services/rechtzettingen/
* Node.js version: 10.15.0

**What steps will reproduce the problem?**
The attached zip-file contains the full test, which can be run to reproduce the issue. In short: I open the above URL, hover over one of the elements in the footer and take a screenshot of the full footer.

_Please include code that reproduces the issue._

                footerSelector = "footer.vrt-site-footer";
                const rect = await page.evaluate(footerSelector => {
                    const element = document.querySelector(footerSelector);
                    const {x, y, width, height} = element.getBoundingClientRect();
                    return {x, y, width, height};
                }, footerSelector);
                
                await page.hover(cssSelector);
                const image =  await page.screenshot({  clip: {x: rect.x, y: rect.y, 
                                                            width: rect.width ,
                                                            height: rect.height}
                                                    });
                expect(image).toMatchImageSnapshot();

**What is the expected result?**
The screenshots are identical, except for the hover over the elements.

**What happens instead?**
On one of the screenshots the footer is not captured completely; a small part of the left side is missing. 
On the first screenshot below (with the word 'deontologie' is highlighted), the whole footer is shown in the picture). 
The second screenshot is missing a part of the left side of the footer. In the second screenshot the rss icon (next to the icons of youtube, twitter,..) is highlighted. 

It seems that when I hover over items on the right side of the footer, the screenshot is always missing the left side of the footer. If I leave out the line of code with the hover, the whole footer is always captured.

![tmp-js-hover-test-test-hover-2-snap](https://user-images.githubusercontent.com/47781242/53015500-8e884e80-344b-11e9-9a1c-1ae9aceb4980.png)
---------
![tmp-js-hover-test-test-hover-1-snap](https://user-images.githubusercontent.com/47781242/53015497-8defb800-344b-11e9-8354-e0767b1632fa.png)
[tmp.js.zip](https://github.com/GoogleChrome/puppeteer/files/2879975/tmp.js.zip)

**Comment by vsemozhetbyt** [comment]
It seems this is because `.hover()` functions try to center the element in viewport:

https://github.com/GoogleChrome/puppeteer/blob/62da2366c65b335751896afbb0206f23c61436f1/lib/JSHandle.js#L170

And `deontologie` element cannot be centered, so horizontal scrolling is not applied, while rss icon can be centered, so the page is scrolled horizontally. Maybe try to add `args: ['--no-sandbox', '--start-maximized']` to reduce scrolling space?

**Comment by manteb** [comment]
Thanks for the info @vsemozhetbyt 
The `--start-maximized` arg doesn't seem the help a lot.
If this behaviour is intended, the issue may be closed. (but maybe it is also good to mention this in the documentation)

**Comment by vsemozhetbyt** [comment]
Maybe try to increase the width in the `page.setViewport()` till no scrolling happens?

**Comment by manteb** [comment]
That helps a bit :) thanks
