### ISSUE TITLE
waitForNavigation Error: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by jordyvandomselaar** [puppeteer/puppeteer#4038]
I have the following test:

```
 it("Should not have to open Knhb when logging in again whilst still being logged in in SSO", async () => {
        await page.goto("http://localhost:3000");
        await expect(await page.evaluate(() => {
            localStorage.clear();
            return localStorage.getItem("id_token");
        })).toBe(null);
        await Promise.all([
            page.waitForNavigation(),
            page.goto("http://localhost:3000/matches")
        ]);
        await expect(await page.title()).toBe("Digitaal Wedstrijd Formulier");
    });
```

It opens a page which redirects a few times, after all the redirects are done it should continue. Instead of waiting it throws the following error:

```
Error: Execution context was destroyed, most likely because of a navigation.
```

**Comment by aslushnikov** [comment]
@jordyvandomselaar what's your puppeteer version? Also, how do I reproduce this locally?

**Comment by jordyvandomselaar** [comment]
You would reproduce it using
```
await Promise.all([
            page.waitForNavigation(),
            page.goto("http://localhost:3000/matches")
        ]);
```

The goto should contain any url that would redirect you somewhere.

**Comment by aslushnikov** [comment]
@jordyvandomselaar what kind of redirects are these? We have tests for this exact scenario with regular HTTP redirects and things are working just fine.

**Comment by stoplion** [comment]
Having the same problem. Just started to use this lib and totally stuck..

**Comment by aslushnikov** [comment]
@stoplion please file a separate issue with details so that we can repro this. I'll close this since it's not actionable.

**Comment by ghost** [comment]
@aslushnikov I also have this issue. Should I create new topic?

**Comment by aslushnikov** [comment]
@best-coupon-codes please do, but make sure to include a good reproduction script so that we can reproduce it locally. Otherwise it would not be actionable.
