### ISSUE TITLE
puppeteer not working on Ubuntu 16.04 but works on 14.04

### ISSUE THREAD

**Issue by ageorgios** [puppeteer/puppeteer#404]
I have the same nodejs project running on 16.04 and 14.04
on 16.04 fails with:
```
Error: Failed to connect to chrome!
    at Function.launch (/home/ageorgios/c9/projects/scrapi/node_modules/puppeteer/lib/Launcher.js:96:13)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```
Please help.

**Comment by ebidel** [comment]
Please include your node version and code that repros the issue.

**Comment by alex88** [comment]
@ebidel brand new ubuntu 16.04 VM on GCE, fully updated, nodejs 8 installed from nodesource/distributions

```
ubuntu@rend:~/test⟫ node -v
v8.4.0
ubuntu@rend:~/test⟫ npm -v
5.3.0
ubuntu@rend:~/test⟫ npm install --save puppeteer

> puppeteer@0.9.0 install /home/ubuntu/test/node_modules/puppeteer
> node install.js

Downloading Chromium r494755 - 92.1 Mb [====================] 100% 0.0s
npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ puppeteer@0.9.0
added 36 packages in 13.051s
ubuntu@rend:~/test⟫ node -e "(async () => { try { browser = await require('puppeteer').launch(); } catch (e) { console.error(e); } })();"
Error: Failed to connect to chrome!
    at Function.launch (/home/ubuntu/test/node_modules/puppeteer/lib/Launcher.js:96:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Update**: same with node 7.10.1 installed from nodesource/distributions
**Update 2**: might be wrong but trying to run chrome gives: `error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory`
**Update 3**: solved by installing `sudo apt-get install libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0`

@ageorgios above command works, however it's plenty of stuff to install

**Comment by ageorgios** [comment]
@alex88 
That was it thank you!!

**Comment by nsuhanshetty** [comment]
Started working after I updated the node version (used [nvm](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04) to do that).
