### ISSUE TITLE
deviceScaleFactor ignored for pdf()

### ISSUE THREAD

**Issue by malifai** [puppeteer/puppeteer#4043]
I'm trying to set (increase) the DPI of the generated PDF file (like explained here: https://github.com/GoogleChrome/puppeteer/issues/1057), which I create from generated HTML on the fly. It seems that the `deviceScaleFactor` passed to `setViewport` is completely ignored (no change in file size / quality)

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: v10.15.1

**What steps will reproduce the problem?**

    const A4_LONG_SIDE_WIDTH = 1122;
    const A4_SHORT_SIDE_WIDTH = 793;

    const DEFAULT_OPTIONS = {
	format: 'A4',
	printBackground: true,
	landscape: false
    };

    let browser;

    const create = async (template, data, callback, options) => {
        const html = templateer.create(template, data);
	    const pdfOptions = Object.assign(DEFAULT_OPTIONS, options || {});

        fs.writeFile(path.join(process.cwd(), 'output.html'), html, 'utf-8', () => {}); // DEBUGGING HTML

	    try {
		if (!browser) {
			console.log('launching puppeteer');
			browser = await puppeteer.launch();
		}

		const page = await browser.newPage();

		await page.setViewport({
			width: !pdfOptions.landscape ? A4_SHORT_SIDE_WIDTH : A4_LONG_SIDE_WIDTH,
			height: !pdfOptions.landscape ? A4_LONG_SIDE_WIDTH : A4_SHORT_SIDE_WIDTH,
			deviceScaleFactor: 3
		});

		// await page.setContent(html, { waitUntil: 'networkidle0' });
		await page.setContent(html);
		await page.emulateMedia('screen');

		const buffer = await page.pdf(pdfOptions);
		console.log('done');

		callback(null, buffer);
	    } catch (err) {
		callback(err, null);
	    }
    };

**What is the expected result?**

I expect the DPI and therefore the size of the generated PDF to change.

**What happens instead?**

No difference can be seen. The whole `setViewport` call makes no difference. I tried leaving the `emulateMedia` out but without any success.

**Comment by bbugh** [comment]
I noticed that you have `await page.emulateMedia('screen')` which may be an issue (or might become one later). I recommend to try changing that to `'print'` media, I was having similar scaling issues with `screen` when I first set puppeteer up.

**Comment by ivangusev** [comment]
I confirmed that deviceScaleFactor is ignored, tried in win64-122.0.6261.111 chrome
