### ISSUE TITLE
Puppeteer-firefox tracing and metrics?

### ISSUE THREAD

**Issue by krystian50** [puppeteer/puppeteer#4044]
As in the title, will you support tracing and metrics in puppeteer-firefox? The metrics were grayed out on the coverage list, but now they are just failing. Tracing is still grayed out.

Also, are there any more detailed puppeteer-firefox docs or changelog?

**Comment by aslushnikov** [comment]
> will you support tracing and metrics in puppeteer-firefox?

@krystian50 Tracing is plausible - there's one in Firefox, but It'll be different from Chromium's. We might expose it under a different name to avoid confusion, but we haven't though about this yet. Is there tooling to analyze firefox traces?

Metrics are probably possible as well, but we haven't looked into this one yet.

> The metrics were grayed out on the coverage list, but now they are just failing.

Interesting, I don't remember excluding them from the list. In any case, we crossed out a few API methods to narrow the scope for the first "milestone". The goal is to have the whole API implemented eventually.

> Also, are there any more detailed puppeteer-firefox docs or changelog?

The documentation is our `api.md`; we might enrich it later on with some Puppeteer-Firefox specifics. Things like "getting started", "best practices" and "faq" will come later on - as the project matures.

There's no changelog atm - there'll be one once we move Puppeteer-Firefox out of experiment. The best I can suggest now is the status page and commits:
- Status: [Is Puppeteer-Firefox ready?](https://aslushnikov.github.io/ispuppeteerfirefoxready/)
- [Juggler commits](https://github.com/puppeteer/juggler/commits/master)
- [Puppeteer-Firefox commits](https://github.com/GoogleChrome/puppeteer/commits/master/experimental/puppeteer-firefox)

**Comment by krystian50** [comment]
@aslushnikov do you know any tooling to analyze chrome traces? I'm looking for something intresting.

I'm using tracing to analyze performance of frontend apps, mostly SPA. It's part of my master thesis. Puppeteer is exactly what I need. I combine it with Jest doing some tests automation. And I compare traces, by loading in chrome.

It would be nice to have it working with firefox 💯

**Comment by bbandla** [comment]
@aslushnikov 
I am trying to get puppeteer-fx to work, code below is launching the firefox browser, but i get the  TypeError: scope.context.currentPage.click is not a function.
Looks like its not including puppeteer with puppeteer-fx? Any suggestions please?


const b = process.env.PUPPETEER_BROWSER || 'chrome';
const puppeteer = b === 'firefox' ?
require('puppeteer-fx') : require('puppeteer')

const World = function() {
    scope.driver = puppeteer;
    scope.context = {};
};

await scope.context.currentPage.goto(CREDS.url);
await scope.context.currentPage.click(loginpage.loginfields.USERNAME_SELECTOR);

**Comment by aslushnikov** [comment]
> do you know any tooling to analyze chrome traces? I'm looking for something intresting

@krystian50 I'm quite far from trace post-processing; +@paulirish who might be able to recommend something here.

> It would be nice to have it working with firefox

👌Probably doable; I haven't seen any roadblocks there. I'll keep this open until we either expose tracing in Puppeteer-Firefox or find out that it's impossible.
