### ISSUE TITLE
waitForFunction only called once

### ISSUE THREAD

**Issue by staab** [puppeteer/puppeteer#4045]
The quick summary is that whether I use `raf`, or set `polling` to a number, `waitForFunction` only ever runs once.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: macOS Mojave 10.14.3
* URLs (if applicable): example.com
* Node.js version: v8.15.0

**What steps will reproduce the problem?**

The following puppeteer script is saved as `pup.js`:

```js
const puppeteer = require('puppeteer')

puppeteer.launch().then(async browser => {
  const [page] = await browser.pages()

  let result = false

  page.exposeFunction('getResult', () => {
    console.log('here', result)

    const thisResult = result

    result = true

    return thisResult
  })

  await page.goto('http://example.com')
  await page.waitForFunction('getResult()')
  await page.close()
  await browser.close()
})
```

My command to run it is `node pup.js`.

**What is the expected result?**

I expect the following output:

```
here false
here true
```

and a clean exit.

**What happens instead?**

I get the following:

```
here false
(node:64382) UnhandledPromiseRejectionWarning: TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/Users/jstaab/Desktop/cc/client/node_modules/puppeteer/lib/DOMWorld.js:554:28)
    at DOMWorld.waitForFunction (/Users/jstaab/Desktop/cc/client/node_modules/puppeteer/lib/DOMWorld.js:459:12)
    at Frame.waitForFunction (/Users/jstaab/Desktop/cc/client/node_modules/puppeteer/lib/FrameManager.js:636:28)
    at Page.waitForFunction (/Users/jstaab/Desktop/cc/client/node_modules/puppeteer/lib/Page.js:1098:29)
    at puppeteer.launch.then (/Users/jstaab/Desktop/cc/client/pup.js:19:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:64382) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64382) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And it fails to exit (because I never get to `page.close()`).

**Comment by vsemozhetbyt** [comment]
An exposed function always returns Promise. And it seems `page.waitForFunction()` polling hangs when its function returns promise even resolved to truthy value. Simplified example:

```js
'use strict';

const puppeteer = require('puppeteer');

puppeteer.launch({ headless: false, devtools: true }).then(async browser => {
  const [page] = await browser.pages();

  await page.waitForFunction(async () => console.log(Date.now()), true);
  // or page.waitForFunction('console.log(Date.now()), Promise.resolve(true)');

  console.log('not logged');

  await browser.close()
});
```

Browser console has date message, while Node.js console hangs and then throws timeout error.

**Comment by aslushnikov** [comment]
@staab @vsemozhetbyt thank you, `waitForFunction` indeed doesn't play well with async functions. It should though.

**Comment by staab** [comment]
For anyone else running into this, here's my current workaround:

```
  page.hackyWaitForFunction = (predicate, opts = {}) => {
    const start = new Date()
    const {timeout = 10000, polling = 10} = opts

    return new Promise((resolve, reject) => {
      const check = async () => {
        const result = await predicate()

        if (result) {
          resolve(result)
        } else if (new Date() - start > timeout) {
          reject('Function timed out')
        } else {
          setTimeout(check, polling)
        }
      }

      setTimeout(check, polling)
    })
  }
```

This of course doesn't support function strings, and runs functions in node's context, not the page, but it's been good enough for what I need.

**Comment by paperbackdragon** [comment]
I'm running into something that might be related to this. We use a lot of async/await in our test suites. I have a use of `waitForFunction` that doesn't use async code itself (it's just a simple call to `document.querySelector()`), but most of the rest of the test is filled with async/await statements. After a lot of testing, I'm fairly sure that after the first time the inner function is tested/validated against the browser context, control is somehow given back to the test suite, because the afterEach hook started to be called in the middle of the test, which cleaned up state and made the rest of the test fail.

EDIT: I might have spoke too soon -- I started using `waitForSelector` instead, and I'm hitting the same issue. Something else is causing my `afterEach` method to be called too early.
