### ISSUE TITLE
Tracing stops after 450 screenshots.

### ISSUE THREAD

**Issue by weworkwithzoh** [puppeteer/puppeteer#4049]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: macOS 10.13.6
* Node.js version: 10.15.0
* Jest-Puppeteer version: 4.0.0
* Jest version: 24.1.0

**What steps will reproduce the problem?**

Starting a trace on a long-running test (Several minutes).

**What is the expected result?**

Expect trace representing the entire duration of the test.

**What happens instead?**

Trace appears to cut off after 450 screenshots worth of data.

**Comment by weworkwithzoh** [comment]
Did some digging, looks like this is a hard-coded fixed limit in DevTools/Chromium.
https://cs.chromium.org/chromium/src/content/browser/devtools/devtools_frame_trace_recorder.h?l=31&rcl=8a7a011299b9d7c375b0974249d941e06dfc48bf

Since this isn't something that can be fixed here, I'm not sure there's much that we can do.
Perhaps Puppeteer needs its own tracing feature that can handle longer traces for UI tests, or some sort of auto-concatenation of multiple traces within Puppeteer?

**Comment by aslushnikov** [comment]
@weworkwithzoh there's a long-standing bug somewhat related to this: https://bugs.chromium.org/p/chromium/issues/detail?id=739759

Folks from lighthouse have a patch that throttles screenshot rate; for long-running tasks you probably don't need too many screenshots, so it might help: https://chromium-review.googlesource.com/c/chromium/src/+/1414150

Also, if you don't need traces per se, you can get frames through protocol's [screencasting](https://vanilla.aslushnikov.com/#Page.startScreencast).

I'll close this in favor of upstream chromium bug, it'll probably be a better place for discussion.

**Comment by weworkwithzoh** [comment]
Thanks so much!
