### ISSUE TITLE
How to get a Cross-domain iframe?

### ISSUE THREAD

**Issue by kinglf** [puppeteer/puppeteer#4053]
eg.
Website domain:  https://pub.alimama.com
inner iframe domain:   https://login.taobao.com

Use page.frames() can't find the Cross-domain iframe.

How to get a Cross-domain iframe?

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with this code:

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();

    const [page] = await browser.pages();
    page.setDefaultTimeout(0);

    await page.goto('https://pub.alimama.com/');
    await page.waitForSelector('iframe[name="taobaoLoginIfr"]');

    const frame = page.frames().find(frame => frame.name() === 'taobaoLoginIfr');
    console.log(frame.url());

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Output:
```
https://login.taobao.com/member/login.jhtml?...
```

**Comment by kinglf** [comment]
> I cannot reproduce with this code:
> 
> ```js
> 'use strict';
> 
> const puppeteer = require('puppeteer');
> 
> (async function main() {
>   try {
>     const browser = await puppeteer.launch();
> 
>     const [page] = await browser.pages();
>     page.setDefaultTimeout(0);
> 
>     await page.goto('https://pub.alimama.com/');
>     await page.waitForSelector('iframe[name="taobaoLoginIfr"]');
> 
>     const frame = page.frames().find(frame => frame.name() === 'taobaoLoginIfr');
>     console.log(frame.url());
> 
>     await browser.close();
>   } catch (err) {
>     console.error(err);
>   }
> })();
> ```
> 
> Output:
> 
> ```
> https://login.taobao.com/member/login.jhtml?...
> ```


3ks,I get it use your code
 const frame = **await** page.frames().find(frame => frame.name() === 'taobaoLoginIfr');

**Comment by vsemozhetbyt** [comment]
@kinglf It seems neither [`page.frames()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageframes) nor [`Array.prototype.find()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) return promises, so `await` is redundant here, though it does not any harm)

**Comment by kinglf** [comment]
@vsemozhetbyt 
I don't know what happened. I haven't changed any environment or code, but sometimes I can't find the frame.


I'm sure it's loaded. But they don't have the frame in frames().
Whether or not the code contains **await**

**Comment by vsemozhetbyt** [comment]
I have the same random issue. Maybe some flaky issues on the iframe site?

**Comment by kinglf** [comment]
@vsemozhetbyt 
I think it might be the timing of code execution.
When I use setTimeout,Problem solved. 
Maybe you can try to be like me :)

**Comment by kinglf** [comment]
@vsemozhetbyt 
I can't get element in frame....
Here is my code

==============

'use strict';
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch(
        {
            headless:false,
            args:['--disable-infobars ','--disable-web-security'],
        }
    );

    const [page] = await browser.pages();
    page.setDefaultTimeout(0);

    await page.goto('https://pub.alimama.com/');
    await page.waitForSelector('iframe[name="taobaoLoginIfr"]');

    await setTimeout(function(){
        const frame = page.frames().find(frame => frame.name() === 'taobaoLoginIfr');
        console.log(frame.url());
        var pass=frame.$('#TPL_password_1'); //can't get the element.
    },5000);

  

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();

**Comment by vsemozhetbyt** [comment]
1. You can use `page.waitFor(5000);` instead of `setTimeout()` to get consistent flow.
2. `frame.$()` returns Promise, so we need `await`:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless:false,
      args:['--disable-infobars ','--disable-web-security'],
    });

    const [page] = await browser.pages();
    page.setDefaultTimeout(0);

    await page.goto('https://pub.alimama.com/');
    await page.waitForSelector('iframe[name="taobaoLoginIfr"]');

    await page.waitFor(5000);

    const frame = page.frames().find(frame => frame.name() === 'taobaoLoginIfr');
    console.log(frame.url());
    const pass = await frame.$('#TPL_password_1');
    console.log(pass.toString());

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Output:
```
https://login.taobao.com/member/login.jhtml?...
JSHandle@node
```

**Comment by kinglf** [comment]
@vsemozhetbyt  thank you very much :) :)

**Comment by rajat-np** [comment]
I am unable to find iframe for stripe elements. I am using react-stripe-elements.  
```javascript
const frame = page.frames().find(frame => frame.name() === '__privateStripeFrame5');
``` 
frame value is undefined. 
The iFrame element 
```JSX
<iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-16127e5319b69f955ff88ee115ec5ae4.html#style[base][color]=%23525f7f&amp;style[base][fontFamily]=Camphor%2C+Segoe+UI%2C+Open+Sans%2C+sans-serif&amp;style[base][fontSize]=18px&amp;style[base][letterSpacing]=0.025em&amp;style[base][::placeholder][color]=%23bbb&amp;style[base][::placeholder][fontSize]=18px&amp;style[invalid][color]=%23c23d4b&amp;componentName=cardNumber&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;apiKey=pk_test_UynUDrFmbBmFVgJXd9EZCvBj00QAVpdwPv&amp;origin=http%3A%2F%2Flocalhost%3A3003&amp;referrer=http%3A%2F%2Flocalhost%3A3003%2Fregister&amp;controllerId=__privateStripeController1" title="Secure payment input frame">
</iframe>
```
Although it waits for this selector without throwing error. 
``` javascript
 await page.waitForSelector('iframe[name="__privateStripeFrame5"]');
```

**Comment by KeenSting0712** [comment]
I got a similar problem, and haven't solved it till now.

step 1:  I write  scripts to  execute a series of page operations automatically
step 2:  the scripts  invoke an JS function witch generate a new iframe (i am sure it's appear in my page)
step 3: i use "await page.frames()" can only get one frame, the main page frame.
step 4: cause the new iframe have no name , just with id, so i can not find it by the code like this:

        const frame = page.frames().find(frame => frame.name() === 'taobaoLoginIfr');

so i am trying to get the new iframe from "page.mainFrame().childFrames()",   but get empty result，the result lenth is 0.

i am  puzzled by this problem for some days, and really get tired. can anyone help me，teach me how to solve it, thanks!


and i can find the iframe in selenium!!!!

**Comment by yannickschuchmann** [comment]
This really took me a while.

I always ended up with a detached frame with a content like:
```
<html><head></head><body></body></html>
```

Turned out that it was only a security issue for me. Normally Chromium is set up to isolate sites. 
So every process only handles exactly one site. Meaning that a page with iframes is handled by multiple process - one for each frame - and a process is unable to access a site from a different process. 
See [https://peter.sh/experiments/chromium-command-line-switches/#site-per-process](https://peter.sh/experiments/chromium-command-line-switches/#site-per-process).

This is also mentioned at [Chromium.org - Known Issues](https://www.chromium.org/Home/chromium-security/site-isolation#TOC-Known-Issues).

---

**Solution:**

Passing the following args did the trick:
```javascript
const args = [
      '--disable-web-security',
      '--disable-features=IsolateOrigins,site-per-process'
]
const browser = puppeteer.launch({ headless: false, args });
// ... 
```

or for those who use jest-puppeteer (like I do):
```javascript
// jest-puppeteer.config.js

module.exports = {
  launch: {
    headless: process.env.HEADLESS !== 'false',
    args: [
      '--disable-web-security',
      '--disable-features=IsolateOrigins,site-per-process'
    ]
  }
}
```

Hope this helps you as well. 👋

**Comment by huyulinhome** [comment]
I have a try with two version.The 1.19.0 is ok but the 2.0.0 is fault.Someone may encounter the same problem

**Comment by danielcardeenas** [comment]
Thanks so much @yannickschuchmann !

**Comment by michalklym** [comment]
I had an issue with finding stripe elements too. 
The reason for that is the following: 

> You can't access an <iframe> with different origin using JavaScript, it would be a huge security flaw if you could do it. For the same-origin policy browsers block scripts trying to access a frame with a different origin. [See more detailed answer here](https://stackoverflow.com/a/25098153/11974819)

Therefore when I tried to use puppeteer's methods:` Page.frames()` and `Page.mainFrame().`  `ElementHandle.contentFrame()` I did not return any iframe to me. The problem is that it was happening silently and I couldn't figure out why it couldn't find anything.

As @jyannickschuchmann mentioned adding these arguments to launch options solved the issue:
`
 '--disable-web-security',
'--disable-features=IsolateOrigins,site-per-process'
`

**Comment by Stehos** [comment]
Hi guys are there any special versions of puppeteer or others required? It's not working with private vimeo embed. 

For me await page.browser().version() returns:
Chrome/85.0.4182.0

Thank you.

**Comment by lioshi** [comment]
Hi,

I have the same issue with Vimeo embed iframe. I think because this cookie has httpOnly to false
```json
{
    "sameSite": "None",
    "name": "vuid",
    "value": "pl415954987.44482382",
    "domain": ".vimeo.com",
    "path": "/",
    "expires": 1679860706,
    "httpOnly": false,
    "secure": true
}
```
But it works (i'll get this cookie) in local env :(
It fails in a cloud env...

**Comment by lioshi** [comment]
Hi,
I know why Vimeo iframe embed cookies is not scraped... :(
Screenshot in human navigation :
![image](https://user-images.githubusercontent.com/1125136/112714530-f89d3880-8eda-11eb-86e2-453069d0777d.png)
Screenshot with Puppetter...
![image](https://user-images.githubusercontent.com/1125136/112714534-05ba2780-8edb-11eb-8642-94cf17302db2.png)
