### ISSUE TITLE
Puppeteer fails to launch on Windows

### ISSUE THREAD

**Issue by szmarczak** [puppeteer/puppeteer#4054]
### Steps to reproduce

* Puppeteer version: 1.12.2
* Platform / OS version: Windows 10 / 1809
* Node.js version: v11.6.0

1. `await puppeteer.launch()`

```
  Error {
    code: 'UNKNOWN',
    errno: 'UNKNOWN',
    syscall: 'spawn',
    message: 'spawn UNKNOWN',
  }
```

2. Running `chrome.exe` manually

> The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

### I'm not sure this is a Puppeteer/Chromium bug

![2](https://user-images.githubusercontent.com/36894700/53239022-2d56ba00-369b-11e9-909c-1b7a4c7229a1.gif)

*click the GIF to zoom*

Make sure to watch the whole GIF till the end.

Sometimes if I copy `chrome-win` manually into `node_modules\puppeteer\.local-chromium\win64-624492` I get that error too. So I believe its Windows fault, just not sure what to do with such information... This occurs **randomly**.

**Comment by szmarczak** [comment]
If someone wonders if my SSD is broken, the answer is no.

**Comment by szmarczak** [comment]
Indeed a Windows bug. Running `md5sum *` will show identical sums.

**Comment by szmarczak** [comment]
If you extract it and compress it again, it will show even different sums! :O Not sure what is happening.

**Comment by meotimdihia** [comment]
![explorer_2019-03-04_13-34-21](https://user-images.githubusercontent.com/300961/53714777-453ff200-3e82-11e9-8008-5392dd87e699.png)

It always happen for me.

**Comment by szmarczak** [comment]
@meotimdihia Can you please try downloading chromium from https://download-chromium.appspot.com/ and extract it directly at `.local-chromium/win64-n/chrome-win`? (remember to rename the old chrome-win before)

**Comment by aslushnikov** [comment]
Let keep this closed - there's nothing we can do regarding this on Puppeteer-side.

Feel free to keep discussion going though.

**Comment by meotimdihia** [comment]
@szmarczak I downloaded your link, run it and the same alert appear.

**Comment by szmarczak** [comment]
@meotimdiha Did you try unpacking it on desktop?

**Comment by meotimdihia** [comment]
@szmarczak my mistake, I just try to unzip and run chrome.exe, and chromium is work with no problem.

![explorer_2019-03-06_08-51-15](https://user-images.githubusercontent.com/300961/53850225-0f6b4c80-3fed-11e9-82db-2dc58c882950.png)

I replace `.local-chromium/win64-n/chrome-win` and run my code: everything is work too.

**Comment by meotimdihia** [comment]
![explorer_2019-03-06_09-18-58](https://user-images.githubusercontent.com/300961/53851393-26ac3900-3ff1-11e9-8eba-676c5fcffa11.png)

**Comment by Volune** [comment]
Don't know if it's related to the initial issue or not, but having the same problem (same error from chrome.exe), I realized in my case it is caused by the project folder having the *case sensitive* attribute enabled.

Fixed it by running `fsutil.exe file setCaseSensitiveInfo . disable` in the project folder, then reinstalling dependencies

**Comment by szmarczak** [comment]
I'll let you know in a few days if that works for me. Not at home ATM.

**Comment by szmarczak** [comment]
@Volune Indeed, your fix works! Thank you very much :heart:

@aslushnikov Can you reopen this issue as it can be fixed on Puppeteer side? Just run the command on the `node_modules/pupeteer` folder before Chromium installation.

**Comment by Nicofisi** [comment]
@Volune that did the trick, thank you!

Just make sure to remove the entire node_modules folder first (or run the command inside that folder I guess). I tried only running `yarn remove puppeteer`, then the command, then `yarn add puppeteer` and it didn't work, probably because the attribute was still set on node_modules. 

Would be lovely to do something with this automatically though.
