### ISSUE TITLE
page.setRequestInterception(true) adds cache-control and pragma headers that cannot be removed

### ISSUE THREAD

**Issue by outlabeau** [puppeteer/puppeteer#4055]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Linux / Mac
* Node.js version: 10.13.0
* Browsers: both Chrome and Chromium

**What steps will reproduce the problem?**
Setting page.setRequestInterception(true) causes the **cache-control** and **pragma** headers to be set to **no-cache**.  While this kind of makes sense (the documentation states that request interception disables caching), we should be able to manually remove those request headers by setting them to **undefined**, as per the [documentation](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-requestcontinueoverrides).

_Please include code that reproduces the issue._
```
await page.setRequestInterception(true);
page.on('request', request => {
  // Override headers
  const headers = Object.assign({}, request.headers(), {
    'cache-control': undefined,  // remove "cache-control" header
    pragma: undefined            // remove "pragma" header
  });
  request.continue({headers});
});
```

**What is the expected result?**
Request headers should not include **cache-control** and **pragma**.

**What happens instead?**
Request headers have **cache-control** and **pragma** headers set to **no-cache**.

**Comment by fastjien** [comment]
me too, have you solved it?

**Comment by fastjien** [comment]
@aslushnikov

**Comment by larry80808** [comment]
I have the same problem. Setting cache-control and pragma to undefined do not work to remove these headers when request interception is turned on.

**Comment by outlabeau** [comment]
I don't know if this is a Chromium issue or a Puppeteer issue, but seems like it should be fixed.

**Comment by outlabeau** [comment]
I just posted a $50 bounty for this on [BountyHub](https://bountyhub.co/bounty/5d5da0140dac4e230c8ccf5d).
