### ISSUE TITLE
FR: Chrome dev tools "Force state"

### ISSUE THREAD

**Issue by privatenumber** [puppeteer/puppeteer#4057]
In the Elements tab of Chrome dev tools, you can right-click an element and force a state on it (eg. `:hover`, `:active` states). I'd like to file a feature request to force elements to have a certain state.

My use case is regression testing UI components. Currently, I'd have to hover over elements and take a screenshot respectively and compare them. With this feature, I can set all the elements to be hovered and take one screenshot and compare two screenshots.

**Comment by vsemozhetbyt** [comment]
Currently, you can use raw CDP for this (see [`'CSS.forcePseudoState'`](https://chromedevtools.github.io/devtools-protocol/tot/CSS#method-forcePseudoState)):
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://github.com/GoogleChrome/puppeteer');
    const cdp = await page.target().createCDPSession();

    const docNodeId = (await cdp.send('DOM.getDocument')).root.nodeId;
    const nodeIds = (await cdp.send('DOM.querySelectorAll', {
      nodeId: docNodeId,
      selector: 'a[href]',
    })).nodeIds;

    await cdp.send('CSS.enable');
    for (const nodeId of nodeIds) {
      await cdp.send('CSS.forcePseudoState', {
        nodeId: nodeId,
        forcedPseudoClasses: ['focus'],
      });
    }

    console.log('Forced.');

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by privatenumber** [comment]
Beautiful! Thank you so much @vsemozhetbyt

**Comment by aslushnikov** [comment]
Thanks @vsemozhetbyt! The workaround should be good for now; we can add this later on if there's some demand.
