### ISSUE TITLE
Request: page.html()

### ISSUE THREAD

**Issue by RobertCorey** [puppeteer/puppeteer#406]
Return the html of the current page. Is there an easy way to do this I'm not seeing?

**Comment by RobertCorey** [comment]
I see how to do it now https://github.com/GoogleChrome/puppeteer/blob/master/examples/search.js . I will write an example and submit a pr for the readme.

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/331#issuecomment-323010213

**Comment by alex88** [comment]
If you want a more complete html, including doctype and html tag (which I think is the real page html, not the innerhtml) you can use

```
const renderedContent = await page.evaluate(() => new XMLSerializer().serializeToString(document));
```

**Comment by ebidel** [comment]
If you want to minimize the alterations added by XMLSerializer:

```js
const html = await page.evaluate('new XMLSerializer().serializeToString(document.doctype) + document.documentElement.outerHTML');
```

**Comment by hasibsahibzada** [comment]
Simple just use 
```javascript
const html = await page.content();
```
