### ISSUE TITLE
Run Peppeteer with pre-defined HTML instead of fetching a URL

### ISSUE THREAD

**Issue by lansana** [puppeteer/puppeteer#4062]
First of all, thanks for making this package. It's extremely helpful in lieu of the deprecated (and buggy) PhantomJS.

I'm wondering if there's a way to use HTML for puppeteer instead of providing a URL to work against.

This is important for me because it allows me to cache SSR pages before launching to a production environment. Since I'm using Go in my backend, I would prefer not being forced to also run Node.js in production.

----

For example, here's my current script:

```javascript
var puppeteer = require('puppeteer');

module.exports.ssr = async (url) => {
    const start = Date.now();

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    try {
        await page.goto(url, {waitUntil: 'networkidle0'});
    } catch (err) {
        console.error(err);
        throw new Error('page.goto/waitForSelector timed out.');
    }

    const html = await page.content(); // serialized HTML of page DOM.
    console.log(html);
    await browser.close();

    const ttRenderMs = Date.now() - start;
    console.info(`Headless rendered page in: ${ttRenderMs}ms`);
};
```

I run it like this after doing a build locally, with my backend servers and UI development server running so that Puppeteer can successfully run:

```bash
node -e 'require("./src/ssr").ssr("http://localhost:5000")'
```

This works great. But how can I do this instead?:

```bash
node -e 'require("./src/ssr").ssr("<html>...</html>")'
```

I want to just pass the `ssr` function the ready-to-go index.html that I get from running an `ng build`.

Is this possible? I can't find such a function anywhere in the [API docs](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-puppeteerlaunchoptions).

**Comment by vsemozhetbyt** [comment]
Can [`page.setContent()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetcontenthtml-options) help?

**Comment by lansana** [comment]
That works for me, thanks.
