### ISSUE TITLE
puppeteer margins:none  equivalence of chrome print

### ISSUE THREAD

**Issue by rpdiss** [puppeteer/puppeteer#4069]
Even when i set margins 0 all. I am keep getting default margins my 
`@page{
  margin: 0 !important;
  padding: 0 !important;
}`
i was searching long time for this and did found nothing that would help.

^1.9.0 puppeteer
ubuntu 18.04
10.15.1 node

```ts
this.browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
const page = await this.browser.newPage();
// @ts-ignore
await page._emulationManager._client.send('Emulation.setDefaultBackgroundColorOverride', {
  color: {
    r: 0,
    g: 0,
    b: 0,
    a: 0
  }
});

await page.goto(
  'https://google.com',
  {
    waitUntil: 'networkidle0'
  }
);
await page.pdf({
  path: '/home/pdf.pdf',
  printBackground: true,
  displayHeaderFooter: true,
  format: 'A4',
  preferCSSPageSize: true,
  headerTemplate: '<span></span>',
  footerTemplate: '<span></span>',
  margin: {
    left: '0',
    right: '0',
    top: '0',
    bottom: '0'
  };
});```

**Comment by aslushnikov** [comment]
@rpdiss I tried your code snippet and don't see any margins that come from pdf printing. There **are** margins, but they are inherent to the layout of google.com.

So what exactly went wrong?

**Comment by rpdiss** [comment]
@aslushnikov i want to achieve this effect 
![image](https://user-images.githubusercontent.com/9515082/53727187-e3768c80-3e6f-11e9-9978-d63e9ab941e2.png)

**Comment by aslushnikov** [comment]
@rpdiss the following worked for me and produced the same PDF as "Save as PDF..." in Chromium with "margins: none".

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://github.com/GoogleChrome/puppeteer/issues/4069');
  await page.pdf({
    path: 'gh.pdf',
    margin: {
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
  });

  await browser.close();
})();
```

**Comment by rpdiss** [comment]
@aslushnikov Hmm so why it does not work with mine code maybe header and footer are glitching it?

**Comment by GlennVin** [comment]
Can confirm this bug. Breaks my PDFs too. When running Chromium as a browser and manually printing the same HTML and manually setting the margins to 0, it works. When using puppeteer, margins left: 0, right: 0, bottom: 0 are respected to, just not top: 0.

**Comment by nflorentin** [comment]
For me, this css did the trick:
```
@page {
  size: A4 portrait;
  margin: 0;
}
```

**Comment by Denhell** [comment]
use
```
body {
    margin: 0;
}
```

**Comment by dkaripidescp** [comment]
> ```
> body {
>     margin: 0;
> }
> ```

I know the issue is closed but in case it helps this turned out to fix an issue I was having. Margins in the @page css and puppeteer pdf option worked but there was always a very small margin remaining.
