### ISSUE TITLE
page.waitForSelector timeout & ExecutionContext.evaluateHandle hanging

### ISSUE THREAD

**Issue by nfwyst** [puppeteer/puppeteer#4072]
* Puppeteer version: 1.11.0
* Platform / OS version: 10.14.3
* Node.js version: 11.6.0

### when it appear

I have some operations like pagination retrieval that take a long time, page.waitForSelector will throw "timeout error" event if there is  element on the page, it seem like the session is closed or connection is closed but no any reject error tell.

### What is the expected result?

Here is an example:

```javascript
async function click(selector, page) {
    try {
      await page.waitForSelector(selector , {
        timeout: 1000
      })
      await page.click(selector)
    } catch (err) {
      throw err
    }
}

async function recordPrice(id, page) {
  try {
    await click(`.search_Table .bgcolor:nth-child(${id + 1}) .link`, page)
   await Promise.all([
    page.waitForSelector('.aui_state_focus', {
      timeout: 6000
    }),
    page.waitForSelector('.aui_dialog .table_list tbody tr:nth-child(2)', {
      timeout: 6000
    })
   ])
  } catch (err) {
    if (err.message.includes('No node found for selector') || err.message.includes('.search_Table')) {
      return false
    }
    throw err
  }
}

// ...
 let prices = [];
 for (let id = 0; id < feeLength; id++) {
      prices.push(await recordPrice(id, page))
 }
// ...
```

the click function inside recordPrice should not throw any error

### What happens instead?

after recordPrice called multiple times, page.waitForSelector(`.search_Table .bgcolor:nth-child(${id + 1}) .link`) will throw timeout error, but I can get response from the console of headless chrome, so the element is exists actually. 

another, if i comment this lines of click function:

```javascript
  await page.waitForSelector(selector , {
        timeout: 1000
  })
```

the browser pages will be hanging and not end, its confused for me. so, how to fix this so i don't have to restart pages again ? thanks!

**Comment by matheusb-comp** [comment]
In the `TimeoutError` catch, did you try `waitFor` again with other selectors?

I was having a problem like this with Puppeteer v1.12.0, after some `page.goto` (5~15), all `waitFor` calls would stop responding (and eventually timeout).
I tried following the source code to understand what was happening, and for some reason the `waitTasks` are not being `rerun` in the [`_setContext`](https://github.com/GoogleChrome/puppeteer/blob/master/lib/DOMWorld.js#L59) function after the navigation breaks all currently listening `waiFor` calls.

For now I'm using v1.11.0, and this hasn't happened again.

**Comment by albertcarrete** [comment]
> I was having a problem like this with Puppeteer v1.12.0, after some `page.goto` (5~15), all `waitFor` calls would stop responding (and eventually timeout).

You actually saved from a huge headache I was having on v1.12.2. On every 12th or 13th run of page.goto Puppeteer would simple stop responding and timeout any waitForSelector call. Using v1.11.0 fixed this issue as far as I can tell.

**Comment by nfwyst** [comment]
> In the `TimeoutError` catch, did you try `waitFor` again with other selectors?
> 
> I was having a problem like this with Puppeteer v1.12.0, after some `page.goto` (5~15), all `waitFor` calls would stop responding (and eventually timeout).
> I tried following the source code to understand what was happening, and for some reason the `waitTasks` are not being `rerun` in the [`_setContext`](https://github.com/GoogleChrome/puppeteer/blob/master/lib/DOMWorld.js#L59) function after the navigation breaks all currently listening `waiFor` calls.
> 
> For now I'm using v1.11.0, and this hasn't happened again.

Yes, i did, but there is the same error

**Comment by nfwyst** [comment]
> In the `TimeoutError` catch, did you try `waitFor` again with other selectors?

Yes, i did, but there is the same error.

**Comment by nfwyst** [comment]
> I tried following the source code to understand what was happening, and for some reason the `waitTasks` are not being `rerun` in the [`_setContext`](https://github.com/GoogleChrome/puppeteer/blob/master/lib/DOMWorld.js#L59) function after the navigation breaks all currently listening `waiFor` calls.

So waitForSelector will not work  if there are too much navigations.
I'm using v1.11.0 too, but the problem still exists.

**Comment by nfwyst** [comment]
> > I tried following the source code to understand what was happening, and for some reason the `waitTasks` are not being `rerun` in the [`_setContext`](https://github.com/GoogleChrome/puppeteer/blob/master/lib/DOMWorld.js#L59) function after the navigation breaks all currently listening `waiFor` calls.
> 
> So waitForSelector will not work if there are multiple navigations.
> I'm using v1.11.0 too, but the problem still exists.

**Comment by SimonSchick** [comment]
Running into this as well, issue is occurring in a semi-predictable manner.

**Comment by matheusb-comp** [comment]
> I'm using v1.11.0 too, but the problem still exists.

Strange, I did not see this happen again in v1.11.0.

Related older issue: #4011

**Comment by nfwyst** [comment]
It is because `_setContext`  never be called with `context` again after the last waitTask has been init,  then the waitTask throw timeout error.

**Comment by nfwyst** [comment]
I dont know why the context is missing

**Comment by aslushnikov** [comment]
@nfwyst this is a nasty bug. Any way I can repro locally? Looks like we don't force-create execution contexts in certain cases in Chromium.

**Comment by aslushnikov** [comment]
Ah, this is a dupe of #4011

**Comment by Tandoori-Momos** [comment]
a

**Comment by nhhockeyplayer** [comment]
seeing same onlatest

**Comment by hack-tramp** [comment]
same problem on latest version

**Comment by Kradirhamik** [comment]
Any news on this one please? We're reproducing on the latest version

**Comment by BorisBosnar** [comment]
+1

**Comment by daftclaud** [comment]
+1

**Comment by jnd0** [comment]
Still the same problem is happening in v5.x

**Comment by talkl** [comment]
also experiencing the same on v3.3.0 with the waitForFunction. This is a serious bug and our company relies on it.

**Comment by Kradirhamik** [comment]
Seems like this works ok in Playwright

**Comment by talkl** [comment]
> Playwright

what is playwright?

**Comment by Gwen-M** [comment]
same problem on latest version

**Comment by MetaMmodern** [comment]
same on latest version

**Comment by eezdev** [comment]
+1

**Comment by dmanexe** [comment]
+1, but also seems that waitFor randomly works and then does not work.
