### ISSUE TITLE
Access chrome://webrtc-internals with puppeteer

### ISSUE THREAD

**Issue by dtel** [puppeteer/puppeteer#4074]
How can one access chrome://webrtc-internals with puppeteer?

**Comment by aslushnikov** [comment]
@dtel it'll work just fine in headful chrome; headless doesn't support the chrome:// urls.

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('chrome://webrtc-internals');
})();

```

**Comment by DanielVilaFalcon** [comment]
@aslushnikov  Someone knows how to access to chrome://webrtc-internals from a headless browser?
Thanks.
