### ISSUE TITLE
puppeteer screenshot running on aws lambda crashes when encountering large image on site

### ISSUE THREAD

**Issue by amazd** [puppeteer/puppeteer#4075]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: aws lambda
* URLs (if applicable):
* Node.js version: 8.10
* Lambda memory size: 3gb (with 30 sec timeout)

**What steps will reproduce the problem?**

```
const chromium = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-core');

const SCREENSHOT_WIDTH = 1200;
const SCREENSHOT_HEIGHT = 808;

exports.handler = async (event, context, callback) => {
  let url = '';
  let tokenHash = '';

  if (event.queryStringParameters) {
    if (event.queryStringParameters.url) {
      url = event.queryStringParameters.url;
    }

    if (event.queryStringParameters.t) {
      tokenHash = event.queryStringParameters.t;
    }
  }

  let browser = null;
  let rawScreenshot = null;
  try {

    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
    });
    
    const page = await browser.newPage();
    await page.setViewport({ width: SCREENSHOT_WIDTH, height: SCREENSHOT_HEIGHT });
    await page.goto(url, {});
  
    rawScreenshot = await page.screenshot({});
    await page.close();

  } catch (e) {
    console.log('token hash: ' + tokenHash);
    console.log(e);

    callback(null, {
      statusCode: 500,
      body: e.message,
      headers: {
        'Content-Type': 'text/plain',
      },
    });
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  callback(null, {
    statusCode: 200,
    isBase64Encoded: true,
    body: rawScreenshot.toString('base64'),
    headers: {
      'Content-Type': 'image/png',
    },
  });
};
```

1. I deploy my function to AWS lambda and I invoke it with the url param
2. sample site I'm using https://bluelitephotography.myportfolio.com

**What is the expected result?**
A screenshot being returned

**What happens instead?**
I consistently get the following error:

> Protocol error (Page.captureScreenshot): Target closed.

Notice the 4.5 mb image being loaded on that page. The same code return screenshot successfully with most other websites.

**Comment by amazd** [comment]
Full stack trace is this btw:

```
{ Error: Protocol error (Page.captureScreenshot): Target closed.
at Promise (/var/task/node_modules/puppeteer-core/lib/Connection.js:183:56)
at new Promise (<anonymous>)
at CDPSession.send (/var/task/node_modules/puppeteer-core/lib/Connection.js:182:12)
at Page._screenshotTask (/var/task/node_modules/puppeteer-core/lib/Page.js:903:39)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
-- ASYNC --
at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:108:27)
at exports.handler (/var/task/index.js:73:32)
at <anonymous>
message: 'Protocol error (Page.captureScreenshot): Target closed.' }
```

**Comment by aslushnikov** [comment]
@amazd Tab crashes, most likely running out of memory. I don't think we can do much about it on the puppeteer side; running chrome in a constrained environment is an art by itself.

I'd start with https://github.com/alixaxel/chrome-aws-lambda - a well-maintained and actually used by folks in production. There are also many more articles on the Web that might be helpful.

Hope this helps.

**Comment by elainema** [comment]
> args: chromium.args,
>       executablePath: await chromium.executablePath,
>       headless: chromium.headless,

For my case, the size of puppeteer is more than 306MB, which exceeded the maximum limit of the lambda package, how did you upload to lambda? if u can share that, grateful

**Comment by amazd** [comment]
I uploaded the package using the serverless command (sls deploy). Still not sure why, but when you upload the package through serverless to aws, that size limit is not enforced (I think it does some S3 uploading in the background) but if you try to upload manually, it will complain. Hope that helps

**Comment by Petah** [comment]
So there is nothing we can do about this? Even setting Lambda to the max memory, 3008MB, it still  doesn't work.

**Comment by carlosvini** [comment]
I have the same problem, does anyone have a solution?

**Comment by bendadaniel** [comment]
@amazd Hi did you solve this problem please?

**Comment by Petah** [comment]
@bendada3 Not OP but I didn't, even tried rendering multiple smaller screenshots and stitching them together, but that still didn't work. I switch to running it on an Ubuntu box and it worked fine.

**Comment by Petah** [comment]
@aslushnikov Also the comment "most likely running out of memory" doesn't really hold true, as my Ubuntu box only has 2GB of ram vs the lambda function has 3GB.

**Comment by amazd** [comment]
OP here, I was never able to fix the issue. In our case we came up with a hack, since we had access to the sites we were taking a screenshot of, we just made the photos load in lower resolution when the site detected puppeteer was taking a screenshot :)

Was hoping this was something the puppeteer team could look more into

**Comment by sjl2** [comment]
We've been using `chrome-aws-lambda` as well. We've also been running into a similar issue to what's described here and in https://github.com/alixaxel/chrome-aws-lambda/issues/61. Has anyone had any luck that wasn't moving off of Lambda?

**Comment by sjl2** [comment]
To add more information:
We've been running Puppeteer on Lambda (Node 10.x runtime) using `chrome-aws-lambda` with the default settings (and others while debugging, nothing worked).

When rendering HTML with an image with the following information, the browser process dies.
![image](https://user-images.githubusercontent.com/8300986/76566169-6bbb4480-6469-11ea-8414-25f014d0c5a1.png)

With `dumpio: true`, we get:

```
[0311/213822.151939:FATAL:memory.cc(22)] Out of memory. size=155545600
```

What's odd is the Lambda is configured to the maximum 3008MB. The ~155MB mentioned above is significantly less than that, and I don't believe our Node service is using up the rest of it. 

Any ideas of limits that may be not allowing Chromium to use all of the Lambda memory?

**Comment by simonc** [comment]
Hi there. Facing the exact same issue. As soon as an image gets larger than ~1.5MB the lambda timeouts. I don't understand where it comes from and I find it hard to profile. I'd be thankful for any help ❤️

**Comment by mezuky04** [comment]
Hi. We have the same problem. For some links we get `Out of memory. size=9334784` and no idea how to solve it. Running it in an EC2 instance solves the problem. The Lambda function has the maximum memory set.

**Comment by bjornbos** [comment]
We are experiencing the same problem. Puppeteer is not behaving correctly when loading images of a few MB's (not sure what the exact threshold is). Did anyone find a solution?

**Comment by Petah** [comment]
Seemed to run better running in docker/ubuntu on lambda.
