### ISSUE TITLE
Upstream chrome development version 73 bug

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#4079]
Puppeteer 1.12.2 installs chromium development version 73, which has some bugs people shared on stackoverflow ([here](https://stackoverflow.com/questions/54836746/puppeteer-fails-in-docker-container-browser-has-disconnected/54896451#54896451) and [here](https://stackoverflow.com/questions/54657355/how-to-use-puppeteer-to-automante-amazon-connect-ccp-login/54837726#54837726)). 

Specific bugs:
- Puppeteer fails in docker container: “browser has disconnected!”
- Fails to load specific URL: https://ccalderon-reinvent.awsapps.com/connect/ccp#/

The previous stable chromium version 72 works perfectly on the provided cases.

**Comment by aslushnikov** [comment]
@entrptaher Thanks for letting us know!

> Puppeteer fails in docker container: “browser has disconnected!”

I built the container from [this SO question](https://stackoverflow.com/questions/54836746/puppeteer-fails-in-docker-container-browser-has-disconnected/54896451#54896451) and it worked just fine for me. However, the `scrape.js` was missing the `request.continue()` call so navigation just hangs.

> https://ccalderon-reinvent.awsapps.com/connect/ccp#/

This seems to be working fine on tip-of-tree Puppeteer; hopefully new release will fix the issue.

Again, thanks for reaching out!
