### ISSUE TITLE
Puppeteer vs Lighthouse Chrome Launcher

### ISSUE THREAD

**Issue by stramel** [puppeteer/puppeteer#408]
The lighthouse team has published a pretty nice Chrome Launcher but noticed that you guys aren't using it. Is there a benefit to maintaining a separate Launcher? 

https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher
https://www.npmjs.com/package/chrome-launcher

Related issue over there: https://github.com/GoogleChrome/lighthouse/issues/3058

**Comment by aslushnikov** [comment]
We were considering using chrome launcher: https://github.com/GoogleChrome/puppeteer/pull/23

Chrome Launcher solves a broad problem: finding an installed chrome instance and launching it with remote debugging. Chrome could be of any version - which adds to the complexity.

Puppeteer's launcher runs a specific revision of chromium from a known location. It's a much simpler task to solve, so for now we don't mind maintaining our own tiny launcher.

**Comment by ORESoftware** [comment]
@aslushnikov -using puppeteer looks like you can enable debugging by setting `devTools` to `true`. Is there a way to do something similar using chrome-launcher?

**Comment by aslushnikov** [comment]
@ORESoftware sure, the options just passes a chrome flag, so you can do the same with chrome launcher:

https://github.com/GoogleChrome/puppeteer/blob/ab9b34cd5dad54e170be916016a4e9b4097231ed/lib/Launcher.js#L78-L81

**Comment by ORESoftware** [comment]
yeah so question for you - when I launch with `devTools:true` with chrome-launcher, it opens dev tools in the browser but when the browser runs, it doesn't actually pause at the breakpoints/debugger statements.

**Comment by aslushnikov** [comment]
@ORESoftware that sounds like a bug; worth filing over to chrome launcher.
