### ISSUE TITLE
Viewport behaviour is different for test run and manual launch

### ISSUE THREAD

**Issue by defusioner** [puppeteer/puppeteer#4080]
In my application I have a fixed footer that reacts on some data changes and then is displayed using these styles:
```
position: fixed;
  z-index: 1;
  bottom: 0;
  left: 0;
  right: 0;
  padding-left: $sidePadding;
  padding-right: $sidePadding;
  height: 64 / 16 + 0em;
  background: #e6e8e9;
```

Aswell, this footer is using some 'intelligent' logic to hide itself when the page is not ready. I'm using react and in the component I make:
```
<div className={classNames('workflow-footer', { hidden: reallyHidden })}>
...
```
and style: 
```
.workflow-footer {
  transition: all 300ms ease;

  &.hidden {
    visibility: hidden;
    opacity: 0;
  }
}
```

Surprisingly, when I remove the hidden conditional, the footer is displayed (but my app logic is broken).

It is displayed in chromium itself, but not during the test run. I've reproduced the full workflow of the test with `headless: false` and the behaviour is different.

### Steps to reproduce
**Tell us about your environment:**
* Chromium: Version 73.0.3679.0 (Developer Build) (64-bit)
* Puppeteer version: 1.12.2
* Platform / OS version: MacOS 10.14.3

**What steps will reproduce the problem?**

My setup script:

```
import puppeteer from 'puppeteer'

const width = 1920
const height = 1080

let browser, page

beforeAll(async () => {
  browser = await puppeteer.launch({
    headless: false,
    args: [`--window-size=${width},${height}`]
  })
  page = await browser.newPage()
  await page.setViewport({ width, height })

  await login() // proceeds to login page and logs to the app
})
})();

```
**What is the expected result?**
The footer should be visible during test run

**Comment by defusioner** [comment]
Digging deeply I found that it's the viewport bug.

If I set a larger window and a smaller viewport, my fixed footer is displayed well:

```
import puppeteer from 'puppeteer'

const width = 1920
const height = 1080

let browser, page

beforeAll(async () => {
  browser = await puppeteer.launch({
    headless: false,
    args: [`--window-size=${width},${height}`]
  })
  page = await browser.newPage()
  await page.setViewport({ width: 1024, height: 768 })

  await login()
})
```

Anyway, should not it be strange?

**Comment by aslushnikov** [comment]
@roundtheworld yeah this looks like a bug in Chromium's viewport emulation. Would you mind creating a simple demo page that illustrates this behavior so that we can debug it locally?
