### ISSUE TITLE
Is there a way to close file selecting dialog?

### ISSUE THREAD

**Issue by bexoss** [puppeteer/puppeteer#4083]
`<input type="file" id="input_file">`

Imagine if that input clicked by puppeteer, It will show up file selecting dialog. 

Can you close it using puppeteer? That's all I want. Thanks.

**Comment by SimonSchick** [comment]
`page.on('dialog', dia => dia.dismiss())` iirc

**Comment by aslushnikov** [comment]
@bexoss unfortunately file selection dialogs are not closable atm. We'll need a better file picker support eventually; closing this in favor of #2946.

**Comment by Nerlin** [comment]
To anyone who is looking for a solution here's the link to puppeteer docs with a new FileChooser API:
https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-class-filechooser
