### ISSUE TITLE
Receiving a lot ERR_NETWORK_CHANGED when proxy changes a lot

### ISSUE THREAD

**Issue by sesigl** [puppeteer/puppeteer#4084]
I do some web scraping and change the proxy frequently. Due to that I get very often the error on page.goto 

ERR_NETWORK_CHANGED. 

Is it possible to avoid / ignore this error case ?

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: linux
* URLs (if applicable):
* Node.js version: 10

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. lunch puppeteer with a proxy
2. open a page
3. close puppeteer
4. launch puppeteer with another proxy
5. repeat 2 - 4

**What is the expected result?**
Pages should just open. It looks like that puppeteer caches some url information and that it gets confused when changing the proxy happens very often.

**What happens instead?**
I receive the error code ERR_NETWORK_CHANGED and the page did not load successfully.

**Comment by aslushnikov** [comment]
@Journerist You can catch it using the `try-catch` syntax and handle appropriately:

```js
try {
  await page.goto(url);
} catch (e) {
  // handle navigation error
}
```

Hope this helps

**Comment by sesigl** [comment]
Thanks for the hint but that is what I already do. But where comes the root cause from? I want to avoid the error at all!

**Comment by andre-hh** [comment]
@Journerist did you find something or even a workaround?

**Comment by sesigl** [comment]
Unfortunately not... I just retry it until it works. Bandwidth and time was a concern of mine. I handle it by keeping the requested page payload to a minimum and I speed up the retry process. You can abort loading additional resources like images, scripts, xhr...

Good luck :)

**Comment by liorazi** [comment]
any news on this one? Happens to me too (every few days)

**Comment by playground** [comment]
This happens from time to time, any update?

**Comment by daniel-hartmann** [comment]
> @Journerist You can catch it using the `try-catch` syntax and handle appropriately:
> 
> ```js
> try {
>   await page.goto(url);
> } catch (e) {
>   // handle navigation error
> }
> ```
> 
> Hope this helps

this is not really a solution...

**Comment by Redskinsjo** [comment]
I had the same error with puppeteer. Removing node_modules clears your cache, I did it then reinstalled it and it worked.

**Comment by philosofonusus** [comment]
A big issue for me it can't be a solution

> ```js
> try {
>   await page.goto(url);
> } catch (e) {
>   // handle navigation error
> }
> ```

**Comment by philosofonusus** [comment]
> @Journerist You can catch it using the `try-catch` syntax and handle appropriately:
> 
> ```js
> try {
>   await page.goto(url);
> } catch (e) {
>   // handle navigation error
> }
> ```
> 
> Hope this helps

A big issue for me it can't be a solution

**Comment by philosofonusus** [comment]
also I don't use proxies in my case
