### ISSUE TITLE
Can't take screenshot with emoji on Firebase Cloud Functions

### ISSUE THREAD

**Issue by msmyk3** [puppeteer/puppeteer#4086]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version:  Firebase
* URLs (if applicable):
* Node.js version: 8

**What steps will reproduce the problem?**
`
    import * as functions from 'firebase-functions';
    import * as admin from 'firebase-admin';
    admin.initializeApp();
    const storage = admin.storage();
    const puppeteer = require('puppeteer');

    function screenshot() {
        (async () => {
          const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
          const page = await browser.newPage();
          await page.goto("https://getemoji.com/"); //go to emoji page
          await page.screenshot({
            path: '/tmp/screenshot.png',
            omitBackground: true,
          })
          .then(() => {
            // upload screenshot to firebase storage
            storage.bucket('bucketName').upload('/tmp/screenshot.png')
            .then(() => {
              console.log("success");
            })
            .catch(error => {
              console.log(error);
            });
          })
          .catch(e => {
            console.log(e);
          });
        })();
    }
`
1. create HTTP Cloud Function
2. call the screenshot function inside of the HTTP function

**What is the expected result?**
screenshot.png is uploaded to storage, and can see emoji clearly in the image

**What happens instead?**
screenshot.png is uploaded to storage, but can't see emoji in the image.

here is the result screenshot of "https://getemoji.com/":
![screenshot](https://user-images.githubusercontent.com/35797359/53566773-872a1900-3ba0-11e9-8908-acd43181a6ca.png)

**Comment by aslushnikov** [comment]
Looks like fonts are missing? Maybe @steren might be able to suggest something here?

**Comment by steren** [comment]
Would you mind identifying which font we'd need to install? 
And opening a feature request for Cloud Functions at https://cloud.google.com/support/docs/issue-trackers ?

**Comment by aslushnikov** [comment]
@steren surprisingly, I don't have permissions to create new issue.

But the font identifies itself as "Noto Emoji" for me on Linux. I'd guess installing both https://github.com/googlei18n/noto-emoji and https://github.com/googlei18n/noto-fonts should cover all the needs.

**Comment by flauc** [comment]
It looks like when running in firebase language specific characters are missing as well. I think it's related to this issue.

**Comment by shprink** [comment]
I have the same problem. 

I ended up using the emojis in base64 as a workaround. I only had 3 emojis to display. Can't imagine doing the same for all of them.

Anyone found a solution ?

**Comment by dakom** [comment]
if it's using web fonts, perhaps adding a `waitUntil`, e.g. `await page.goto(url, { waitUntil: "networkidle0" });` could help?

**Comment by C0retek** [comment]
I had the same issue Puppeteer/headless Chrome rendering emojis as □□□□

For those that are looking for a workaround, here is what worked for me, copy the font file in the local fonts folder:

```
sudo su

#check if font is installed
fc-match "Noto Color Emoji"

#if not installed install with following line
apt-get install fonts-noto-color-emoji -y

#font will be in shared folder but puppeteer looks into local folder so copy the font there

#create folder and copy file
mkdir -p /usr/local/share/fonts
cp /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf /usr/local/share/fonts/
chmod 644 /usr/local/share/fonts/NotoColorEmoji.ttf

#clear font cache
fc-cache -fv
```

Hope this helps if anybody has the same issue

**Comment by VincentCtr** [comment]
Hi Guys,

Fixed it using this small line of code. Hope it will help.

`                await chromium.font('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf');
`

**Comment by peterpeterparker** [comment]
@VincentCtr sounds interesting 👍

what's `chromium`? an import? a local variable?

**Comment by VincentCtr** [comment]
You can use puppeteer like this : 

```
import * as functions from 'firebase-functions';
import * as puppeteerCore from 'puppeteer-core';
import * as puppeteer from 'puppeteer';
import * as chromium from 'chrome-aws-lambda';
const cors = require('cors')({ origin: true });

async function getBrowser() {
    try {
        console.log('Starting puppeteer on GCP chromium');

        return await puppeteerCore.launch({
            args: [...chromium.args, '--disable-web-security'],
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath
        });
    } catch (e) {
        console.log('Failed to start gcp pupeteer , starting regular pupeteer');
        return puppeteer.launch({ args: ['--no-sandbox'] });
    }
}

export const yourFunction = functions
    .runWith({
        memory: '2GB',
        timeoutSeconds: 300
    })
    .https.onRequest((req, res) => {
        return cors(req, res, async () => {
                const browser = await getBrowser();
                await chromium.font('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf');
                // do what you want here to get your pdf
})
```

The bad side to this is that the PDF will be much heavier (I guess that it is because of the size of the font).

Edit: I use this to get PDF but I guess that it will also work for screenshots

**Comment by peterpeterparker** [comment]
Thx @VincentCtr now I understand, your solution works with `chrome-aws-lambda`. Have to think about it ;)

**Comment by vojkny** [comment]
> You can use puppeteer like this :
> 
> ```
> import * as functions from 'firebase-functions';
> import * as puppeteerCore from 'puppeteer-core';
> import * as puppeteer from 'puppeteer';
> import * as chromium from 'chrome-aws-lambda';
> const cors = require('cors')({ origin: true });
> 
> async function getBrowser() {
>     try {
>         console.log('Starting puppeteer on GCP chromium');
> 
>         return await puppeteerCore.launch({
>             args: [...chromium.args, '--disable-web-security'],
>             defaultViewport: chromium.defaultViewport,
>             executablePath: await chromium.executablePath
>         });
>     } catch (e) {
>         console.log('Failed to start gcp pupeteer , starting regular pupeteer');
>         return puppeteer.launch({ args: ['--no-sandbox'] });
>     }
> }
> 
> export const yourFunction = functions
>     .runWith({
>         memory: '2GB',
>         timeoutSeconds: 300
>     })
>     .https.onRequest((req, res) => {
>         return cors(req, res, async () => {
>                 const browser = await getBrowser();
>                 await chromium.font('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf');
>                 // do what you want here to get your pdf
> })
> ```
> 
> The bad side to this is that the PDF will be much heavier (I guess that it is because of the size of the font).
> 
> Edit: I use this to get PDF but I guess that it will also work for screenshots

How would you avoid using the chromium import from `aws-lambda` in case of google cloud functions?

**Comment by cimox** [comment]
I tried replacing all emojis on the page with Twemojis and it works fine

```
await page.goto('https://localhost/');
await page.addScriptTag({ url: 'https://twemoji.maxcdn.com/v/latest/twemoji.min.js' });
await page.waitForTimeout(500); // A bit tricky, there might be a better way to wait for twemoji dep to load
await page.evaluate(() => {
   // eslint-disable-next-line @typescript-eslint/ban-ts-comment
   // @ts-ignore
  twemoji.parse(document.body, { className: 'h-4 w-4 mx-1' });
});
```

**Comment by fiftin** [comment]
Issue not solved.
