### ISSUE TITLE
puppeteer-fx TypeError on Click

### ISSUE THREAD

**Issue by bbandla** [puppeteer/puppeteer#4087]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.12.2
* Platform / OS version: mac
* URLs (if applicable):
* Node.js version:v11.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I am trying to get puppeteer-fx to work, code below is launching the firefox browser, but i get the TypeError: scope.context.currentPage.click is not a function. Works in Chrome, no issues.
Looks like its not including puppeteer with puppeteer-fx during the runtime? Any suggestions please?

const b = process.env.PUPPETEER_BROWSER || 'chrome';
const puppeteer = b === 'firefox' ?
require('puppeteer-fx') : require('puppeteer')

const World = function() {
scope.driver = puppeteer;
scope.context = {};
};

await scope.context.currentPage.goto(CREDS.url);
await scope.context.currentPage.click(loginpage.loginfields.USERNAME_SELECTOR);

**What is the expected result?**
works in chrome, does not work when run on puppeteer-fx

**What happens instead?**
TypeError: scope.context.currentPage.click is not a function.

**Comment by aslushnikov** [comment]
Hey @bbandla,

We have no relation to [`puppeteer-fx`](https://github.com/autonome/puppeteer-fx) project; I'd recommend filing over to their repository.

P.S. we have an experimental Firefox support via [`puppeteer-firefox`](https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox), please give it a try.
