### ISSUE TITLE
puppeteer-firefox - TypeError: page.exposeFunction is not a function

### ISSUE THREAD

**Issue by brandon-bethke-timu** [puppeteer/puppeteer#4088]
### Overview

puppeteer-firefox
The site https://aslushnikov.github.io/ispuppeteerfirefoxready implies that `page.exposeFunction` is supported. However we get an error that demonstrates `page.exposeFunction` is not supported.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-firefox
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version: v11.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const pptrFirefox = require('puppeteer-firefox');

(async () => {
  const browser = await pptrFirefox.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.exposeFunction("mycallback", (data)=>{
      console.log(data)
  })
  await browser.close();
})();
```

**What is the expected result?**
exposeFunction is supported as implied by https://aslushnikov.github.io/ispuppeteerfirefoxready

**What happens instead?**
`TypeError: page.exposeFunction is not a function`

**Comment by aslushnikov** [comment]
@brandon-bethke-neudesic the dashboard is a tip-of-tree status for the puppeteer-firefox. We've just published Puppeteer-Firefox 0.5.0 with all the new stuff. Please give it another try!
