### ISSUE TITLE
puppeteer-firefox proxy connection failure

### ISSUE THREAD

**Issue by bbandla** [puppeteer/puppeteer#4093]
In Below code, i am trying to connect to Nightly(Firefox Browser) with proxy server, I get Login failure due to this issue.Any suggestions please?
No Issues on Chromium with same code.

scope.browser = await scope.driver.launch({
        headless: false,
        args: [
            '--proxy-server=testproxy:6787'
            '--window-size=1920,1040',
             '--proxy-bypass-list=*reportingportal-nonprod.collegeboard.org'
        ]

    });
    scope.context.currentPage = await scope.browser.newPage();

    await scope.context.currentPage.goto(CREDS.url);

**Comment by aslushnikov** [comment]
Puppeteer-Firefox requires proxy settings to be defined in preferences; IIRC there are no flags for proxy.
See https://support.mozilla.org/en-US/kb/connection-settings-firefox

**Comment by bbandla** [comment]
puppeteer-firefox(Nightly)  resets back to default proxy settings when it opens new browser everytime from the test-runner.

 PUPPETEER_BROWSER=firefox node_modules/.bin/cucumber-js
