### ISSUE TITLE
Not response when i set headless:true

### ISSUE THREAD

**Issue by mituso89** [puppeteer/puppeteer#4094]
help! i use puppeteer 1.6.2 and 1.12
 let proxy = proxyList[Math.floor(Math.random() * proxyList.length)]
    let proxyServer = '--proxy-server=' + proxy.proxyIp + ''
    /* let proxyServer ='--proxy-server=34.215.165.17:3128'  */
    const browser = await puppeteer.launch({
      headless: true,
      args: [
        proxyServer
      /*   '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage', */
      ],
      ignoreHTTPSErrors: true,
    });
    const page = await browser.newPage();
    let username = proxy.proxyName;
    let password = proxy.proxyPass;
    await page.authenticate({ username, password });
   
    await page.goto(url);

 await page.goto(url) not response.
if I set headless:false. It worked.

**Comment by aslushnikov** [comment]
@mituso89 looks like server is detecting Chrome Headless and refuses to respond. Headless detection falls outside of the scope of the project.

**Comment by mattxgreen** [comment]
I just experienced a similar issue and I cannot explain why, but adding a visit to a site via `http` before visiting an `https` URI resolved it for me:

```
await page.authenticate({username, password});
await page.goto('http://www.google.com')
await page.goto('https://www.whatsmyip.org/',{ waitUntil: 'networkidle2' })
```
Perhaps that will help

**Comment by mituso89** [comment]
Thanks @mattxgreen. I tried your plan. But I still get the same error. I think they detect headless chrome.
@aslushnikov Can you help me with another idea.
