### ISSUE TITLE
heroku : libX11-xcb.so.1: cannot open shared object file: No such file or directory :  "env" in launch[Options] should be marked as a dangerous config field, remind to not override.

### ISSUE THREAD

**Issue by swang2019** [puppeteer/puppeteer#4098]
Please refer to my 3rd post.

**Comment by swang2019** [comment]
(node:4) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! 
Mar 02 01:34:58 march2 app/worker.1: /app/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

**Comment by swang2019** [comment]
Just wasted FOUR hours debugging this, the issue is **not** Chromium version

The issue is because  I used " env: " in launchOptions to set a timezone, the doc says it defaults to process.env, but I override it, cause puppeteer cannnot find the path. 

use 

```
        const env = process.env || {};
        env.TZ = xxx;

```

instead of directly override 

`env : {TZ : xxx}
`

then use env into launchOptions to launch chromium, so you added values does not override the original values comes with process.env .

fixed the issue

**Comment by aslushnikov** [comment]
> Just wasted FOUR hours debugging this

@swang2019 sorry to hear this! :( But I'm happy you figured it out.

If you think we can do a better job with documentation somewhere, please feel free to submit a PR.

**Comment by kelseygasser** [comment]
Having the same "$ react-snap
Error: Failed to launch chrome!
/tmp/build_53c404e90d717f6d700d6eb26d17d426/client/node_modules/puppeteer/.local-chromium/linux-641577/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory" 

How did you fix this? What .env variable needs to be set for chromium to run correctly? 

Thanks for your help.

**Comment by swang2019** [comment]
Where you tried to deploy Chrome ?

**Comment by kelseygasser** [comment]
I tried to deploy a react/node/express app on heroku with react-snap. I think inadvertently it added chrome. I tried adding react-snap and puppeteer config items to my package.json

**Comment by swang2019** [comment]
Did you using “env:” when launching the browser ?

**Comment by kelseygasser** [comment]
I am not launching the browser. I believe react-snap is. So I am not sure where to place this "env"

**Comment by swang2019** [comment]
OK, Do you add the puppeteer build packs into your heroku project?

**Comment by kelseygasser** [comment]
Yes, I have done that

**Comment by swang2019** [comment]
Then sorry, I don’t know what’s your issue..

**Comment by kelseygasser** [comment]
Thanks for responding anyway!

**Comment by wubigo** [comment]
sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils

**Comment by meadlai** [comment]
@wubigo Do you know how to install lib in CentOS? thank you.

**Comment by ding-js** [comment]
> @wubigo Do you know how to install lib in CentOS? thank you.

https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by dancherb** [comment]
> 
> 
> sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils

What about with the Heroku deployment issue, would this help?

**Comment by TarunK151** [comment]
sdfsfd

**Comment by jcward** [comment]
> sudo apt install -y ...

FYI, to avoid an interactive debconf setup of tzdata ([screenshot](https://user-images.githubusercontent.com/2192439/229017393-9c2dfd78-b491-4300-94eb-82ebde62d62d.png)) stalling my CI server, I had to prefix the above command with (per [this answer](https://serverfault.com/a/992421)):

```
DEBIAN_FRONTEND=noninteractive TZ="America/New_York" sudo apt install -y ...
```
