### ISSUE TITLE
using image/js cache but no session data

### ISSUE THREAD

**Issue by yegor211** [puppeteer/puppeteer#4101]
Hi there.

Using "userDataDir" will make Puppeteer use cache from that folder, but it will also store cookie/session data. Is it possible to make multiple browser instances use same cache for images/js (in order to reduce network load) but use different (or none) cache for cookie/session data?

Also, from https://github.com/GoogleChrome/puppeteer/issues/1316, looks like page doesn't use cache to load from in headless mode (with userDataDir set)? Is it still true? Makes no sense to act like that...

**Comment by aslushnikov** [comment]
> Is it possible to make multiple browser instances use same cache for images/js (in order to reduce network load) but use different (or none) cache for cookie/session data?

@yegor211 I don't think it is possible.

> Also, from #1316, looks like page doesn't use cache to load from in headless mode (with userDataDir set)? Is it still true? Makes no sense to act like that...

I didn't get to read the long'ish discussion in #1316. There are some problems with cache reuse between headless and headful profiles, but that's a little exotic usecase.

If you don't switch browser modes (and usually that's not needed in production), profile cache is used just fine. E.g. this script loads most resources from cache on the second and subsequent runs:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    userDataDir: './profile'
  });

  const [page] = await browser.pages();
  page.on('response', r => {
    console.log(r.request().method(), r.url(), r.fromCache() ? '<CACHE>' : '<NETWORK>');
  });
  await page.goto('https://news.ycombinator.com');
  await browser.close();
})()
```

Hope this helps.

**Comment by yegor211** [comment]
> > Is it possible to make multiple browser instances use same cache for images/js (in order to reduce network load) but use different (or none) cache for cookie/session data?
> 
> @yegor211 I don't think it is possible.
> 
> > Also, from #1316, looks like page doesn't use cache to load from in headless mode (with userDataDir set)? Is it still true? Makes no sense to act like that...
> 
> I didn't get to read the long'ish discussion in #1316. There are some problems with cache reuse between headless and headful profiles, but that's a little exotic usecase.
> 
> If you don't switch browser modes (and usually that's not needed in production), profile cache is used just fine. E.g. this script loads most resources from cache on the second and subsequent runs:
> 
> ```js
> const puppeteer = require('puppeteer');
> 
> (async () => {
>   const browser = await puppeteer.launch({
>     userDataDir: './profile'
>   });
> 
>   const [page] = await browser.pages();
>   page.on('response', r => {
>     console.log(r.request().method(), r.url(), r.fromCache() ? '<CACHE>' : '<NETWORK>');
>   });
>   await page.goto('https://news.ycombinator.com');
>   await browser.close();
> })()
> ```
> 
> Hope this helps.

Thanks for the answer mate.

So, I see (from your words) that cache reuse is working just fine in headless mode now. That is great.

Your initial answer for my first question was "no", but can I clarify some points with following questions?

Am I able to delete all cookies that were set for the page before I close page/browser instance?
Can I do that on browser level (like delete ALL cookies for EVERY domain)?
Can I remove cookies for the page that was opened not directly by me via "page" and its methods, but for the page that was opened after triggering some actions on my "page"? If I can get to that page through some iteration, then I should be able to remove cookies, right? (if we are able to remove them on page-browser levels)

Thanks in advance, sorry if I'm not the best explanator but hope you will understand everything.

**Comment by aslushnikov** [comment]
Answering the state-management questions: the only bullet-proof method to cleanup cookies/localStorage/etc is to use [browser contexts](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-class-browsercontext) - these will purge everything once they're closed. Browser contexts, however, won't reuse cache.

**Comment by yegor211** [comment]
> Answering the state-management questions: the only bullet-proof method to cleanup cookies/localStorage/etc is to use [browser contexts](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-class-browsercontext) - these will purge everything once they're closed. Browser contexts, however, won't reuse cache.

Got it. But am I actually able to clear/remove cookies? At least in some cases? Or it aint possible by any means?

**Comment by aslushnikov** [comment]
@yegor211 yeah you can get all cookies with protocol's [`Network.getAllCookies`](https://vanilla.aslushnikov.com/#Network.getAllCookies) and then delete them using protocol's [`Network.deleteCookies`](https://vanilla.aslushnikov.com/#Network.deleteCookies).

**Comment by yegor211** [comment]
> [`Network.getAllCookies`](https://vanilla.aslushnikov.com/#Network.getAllCookies)

Can you please show me an example of "Network.something" usage?

**Comment by aslushnikov** [comment]
We have a pretty decent example in [`CDPSession`](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-class-cdpsession) description; let me know if this is not enough.

**Comment by yegor211** [comment]
> We have a pretty decent example in [`CDPSession`](https://pptr.dev/#?product=Puppeteer&version=v1.12.2&show=api-class-cdpsession) description; let me know if this is not enough.

Thank you again! Sorry if I'm bothering you with questions, just having a big interest.
Can you tell me if there is a difference with this:
`await page._client.send('Animation.enable')`
And this?
`const client = await page.target().createCDPSession();
await client.send('Animation.enable');`

Both will work? But what is the prior one and why should we use it?

**Comment by aslushnikov** [comment]
>  Sorry if I'm bothering you with questions, just having a big interest.

@yegor211 No worries, that's what we're here for

> Can you tell me if there is a difference with this: <...>

Chrome sessions are *stateful* - there are agents that can be enabled and disabled and that hold some state. The `page._client` is an instance of CDPSession that's used internally by Puppeteer to drive page interaction. `page._client` has certain domains enabled (e.g. `Page`, `Runtime` and so on), and Puppeteer holds an assumption that its the only one who talks over the session.

I'd highly recommend to create a designated CDPSession for your needs.

**Comment by SashaDesigN** [comment]
I use this to remove all cookies:

```
	async clearBrowser () {
		// clear cookies
		const client = await this.page.target().createCDPSession()		
		await await client.send('Network.clearBrowserCookies')
	}
```
