### ISSUE TITLE
Firefox macOS installation fails

### ISSUE THREAD

**Issue by janbiedermann** [puppeteer/puppeteer#4102]
### Steps to reproduce

* Puppeteer version: puppeteer-firebox 0.5.0
* Platform / OS version: macOS 10.14.3, /dev/disk1s1 on / (apfs, local, journaled)
* URLs (if applicable):
* Node.js version: 11.10.1

**What steps will reproduce the problem?**
`yarn add  puppeteer-firefox`

**What is the expected result?**
success

**What happens instead?**
```
error /Users/jan/workspace/isomorfeus-puppetmaster/ruby/node_modules/puppeteer-firefox: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/jan/workspace/isomorfeus-puppetmaster/ruby/node_modules/puppeteer-firefox
Output:
ERROR: Failed to download Firefox r2f959d575a3d61f5dda12e4e2dca1f46a92ab569!
{ Error: ENOENT: no such file or directory, chmod '/Users/jan/workspace/isomorfeus-puppetmaster/ruby/node_modules/puppeteer-firefox/.local-browser/firefox-mac-2f959d575a3d61f5dda12e4e2dca1f46a92ab569/firefox/Nightly.app/Contents/MacOS/Firefox'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/Users/jan/workspace/isomorfeus-puppetmaster/ruby/node_modules/puppeteer-firefox/lib/helper.js:31:27)
    at Object.<anonymous> (/Users/jan/workspace/isomorfeus-puppetmaster/ruby/node_modules/puppeteer-firefox/install.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path:
   '/Users/jan/workspace/isomorfeus-puppetmaster/ruby/node_modules/puppeteer-firefox/.local-browser/firefox-mac-2f959d575a3d61f5dda12e4e2dca1f46a92ab569/firefox/Nightly.app/Contents/MacOS/Firefox' }
```

It appears the actual file name is:
'/Users/jan/workspace/isomorfeus-puppetmaster/ruby/node_modules/puppeteer-firefox/.local-browser/firefox-mac-2f959d575a3d61f5dda12e4e2dca1f46a92ab569/firefox/Nightly.app/Contents/MacOS/firefox'

a lower case 'firefox' instead of the requested upper case one.

**Comment by aslushnikov** [comment]
@janbiedermann Thanks for reporting this. We weren't ready to case-sensetive fs on os x; fix'll land soon.

**Comment by echo-bravo-yahoo** [comment]
Hey! I'm still seeing this on `npm install puppeteer-firefox`. Is the npm version stale (reports as puppeteer-firefox@0.5.0)? I would add it to package.json as username/repo#branch, but there doesn't appear to be a dedicated branch for puppeteer-firefox. Any insight on how I can use this on a case-sensitive OS X drive?

**Comment by michaelsalexander83** [comment]
Same problem.
Please is there a solution?

**Comment by michaelsalexander83** [comment]
Is there a way to manually complete the installation?
