### ISSUE TITLE
page.close() does not complete

### ISSUE THREAD

**Issue by limenote135** [puppeteer/puppeteer#4104]
### Steps to reproduce

It seems the same issue at #3631, but it still happens on Puppeteer 1.12.2.

**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Google Cloud Functions
* URLs (if applicable):
* Node.js version: node 8 (Probably 8.15.0)

**What steps will reproduce the problem?**

```
const puppeteer = require("puppeteer");

exports.TestFunc = async (req, res) => {
    const browser = await puppeteer.launch({
        slowMo: 10,
        args: ["--no-sandbox"]
    });

    for (let i = 0; i < 5; i++) {
        const newPage = await browser.newPage();
        await newPage.goto("https://www.google.com");
        await newPage.waitFor(3000);

        console.log("start close");
        await newPage.close(); // wait until timeout
        console.log("complete");
    }
    await browser.close();
}
```

**Comment by aslushnikov** [comment]
@limenote135 your script works just fine for me locally. We also do `page.close()` in almost all of our 600 tests - so I don't believe there's any trouble here.

You might be hitting a [1 minute time limit](https://cloud.google.com/functions/docs/concepts/exec) for cloud function; this'd explain this behavior. (cc @steren)

I speculatively close this since it doesn't look like there's something we can do regarding this on the Puppeteer side.

**Comment by limenote135** [comment]
@

**Comment by limenote135** [comment]
@aslushnikov Thank you for your investigating.

As you said, it works properly on my local (on Windows), but not on cloud function even if setting the time limit to 300s.
I don't know what differences cause this. Do you have any ideas?
I can attach the archive to deploy this function if you need.

**Comment by aslushnikov** [comment]
@limenote135 I unfortunately don't have *any* experience with Cloud Functions, so I won't be very useful here. Would you mind filing over to Google Cloud Functions team? https://cloud.google.com/functions/docs/getting-support#get_support_from_the_community

**Comment by steren** [comment]
Can you increase the Cloud Functions timeout to its maximum (9min) and check again?

Processing in Cloud Functions is likely to be slower than on your machine.

How long does your script take to execute locally?

**Comment by limenote135** [comment]
I set the timeout to 540s with 2GB memory, but it doesn't work. It takes about 20s on my local.
![timeout](https://user-images.githubusercontent.com/17950108/53735324-e3a37600-3ec9-11e9-88bc-4f3918433646.jpg)

**Comment by maximedupre** [comment]
Same thing occurs on my CircleCI build
