### ISSUE TITLE
Introduce --user-data-dir as part of launcher options

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#411]
Use case: periodically getting some data from a site that requires authorization. A user can login once and then just use the cookies automatically.

**Comment by kensoh** [comment]
Hi @vsemozhetbyt this looks like active work-in-progress here - https://github.com/GoogleChrome/puppeteer/issues/53

**Comment by vsemozhetbyt** [comment]
Thank you. This would be a good detailed API, but I mean something much simpler for a user side: not even thinking about processing cookies.

**Comment by ORESoftware** [comment]
I want to puppeteer to use an existing chrome session and open a tab in that session. Can someone document how? I would be happy to write an article about it on Medium.com or whatever.
