### ISSUE TITLE
Cookies aren't always restored on Windows

### ISSUE THREAD

**Issue by JoelEinbinder** [puppeteer/puppeteer#4111]
Our userDataDir + cookies test has been flaky on AppVeyor for months. I have been unable to reproduce it locally though.

**Comment by kblok** [comment]
I had to do this in Puppeteer-Sharp.

```cs
internal static async Task WaitForCookieInChromiumFileAsync(string path, string valueToCheck)
{
    var attempts = 0;
    const int maxAttempts = 10;
    var cookiesFile = Path.Combine(path, "Default", "Cookies");

    while (true)
    {
        attempts++;

        try
        {
            if (File.Exists(cookiesFile) && File.ReadAllText(cookiesFile).Contains(valueToCheck))
            {
                return;
            }
        }
        catch (IOException)
        {
            if (attempts == maxAttempts)
            {
                break;
            }
        }
        await Task.Delay(100);
    }
}
```

It seems that by the time we load the second browser, the cookies file hadn't been saved yet.

**Comment by aslushnikov** [comment]
@kblok oh wow, interesting. Do you have a way to reproduce this locally? We tried many different things but none worked, so we see this happening only on Appveyour.

**Comment by kblok** [comment]
Same here. I was getting random failures in AppVeyor.

I got that error locally a few time on my Mac while running the entire test suite (not just that test). I considered that a possible issue was some IO race. Checked that the Cookies file was plain text(ish) and it solved the issue by waiting for the content to be updated.

I was trying to replicate this on windows and what's interesting is that I'm getting this in a `chrome_debug.log` file
>[0305/154238.569:WARNING:sqlite_persistent_cookie_store.cc(1612)] Failed to post task from Close@../../net/extras/sqlite/sqlite_persistent_cookie_store.cc:1490 to background_task_runner_.

Rings a bell?

**Comment by aslushnikov** [comment]
> I was trying to replicate this on windows and what's interesting is that I'm getting this in a chrome_debug.log file

Yeah might be related, but it's hard to tackle this unless there's a repro. Cookies work pretty reliable in Chrome, so must be something finicky with our shutdown sequence.

**Comment by kblok** [comment]
Could you try running this on Windows @aslushnikov ?

```js
(async () => {
  await TestServer.create(assetsPath, port);
  for(var x = 0; x < 100; x++) {
    console.log(x);
    const userDataDir = await mkdtempAsync(TMP_FOLDER);
    const options = Object.assign({userDataDir}, {headless: true});
    const browser = await puppeteer.launch(options);
    const page = await browser.newPage();
    await page.goto(`http://localhost:${port}/empty.html`);
    await page.evaluate(() => document.cookie = 'doSomethingOnlyOnce=true; expires=Fri, 31 Dec 9999 23:59:59 GMT');
    await browser.close();
    console.log(userDataDir);
    const browser2 = await puppeteer.launch(options);
    const page2 = await browser2.newPage();
    await page2.goto(`http://localhost:${port}/empty.html`);
    const cookie = await page2.evaluate(() => document.cookie);
    console.log(cookie);
    if(!cookie.includes('doSomethingOnlyOnce'))
    {
      console.log("UPS");
      return;
    }
    await browser2.close();
    // This might throw. See https://github.com/GoogleChrome/puppeteer/issues/2778
    await rmAsync(userDataDir).catch(e => {});
  }
})();
```

**Comment by aslushnikov** [comment]
@kblok Worked like a charm:

![image](https://user-images.githubusercontent.com/746130/53838024-f741f180-3f48-11e9-8743-3a55101b8f3f.png)

**Comment by whimboo** [comment]
@jschfflr maybe this is a test that can be re-enabled now given that AppVeyor is no longer used?

**Comment by whimboo** [comment]
@OrKoN mind checking my last comment if we could maybe re-enable the test? Thanks.
