### ISSUE TITLE
How can I get href property from span tag?

### ISSUE THREAD

**Issue by tntdev21** [puppeteer/puppeteer#4116]
I have this `span` tag.
```
<span class="mySpan" href="https://www.axample.com/123/" role="button" tabindex="0">text</span>
```

Using `page.$('span.mySpan')`, I can get `span` ElementHandle. Then, I try to get the `href` property  by calling [elementHandle.getProperty(propertyName)](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#elementhandlegetpropertypropertyname) method. Finally I get the text by calling [jsHandle.jsonValue()](https://github.com/GoogleChrome/puppeteer/blob/v1.11.0/docs/api.md#jshandlejsonvalue) method.

I use the same approach with `<a>` tag and got the link, but no luck with `<span>` tag.

How can I get `href` property from `<span>` tag?

**Comment by aslushnikov** [comment]
@CQBinh how about this:

```js
const spanHref = await page.$eval('span.mySpan', span => span.getAttribute('href'));
const spanText = await page.$eval('span.mySpan', span => span.textContent);
```

Or, if you have a handle in hands:

```js
const handle = await page.$('span.mySpan');
const spanText = await page.evaluate(span => span.textContent, handle);
const spanHref = await page.evaluate(span => span.getAttribute('href'), handle);
```

hope this helps.

**Comment by tntdev21** [comment]
@aslushnikov thank you very much. It works like a charm 👍
