### ISSUE TITLE
dispatchMouseEvent.type mouseWheel support

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#4119]
I think we can implement a `mouse.wheel` function, which would call [dispatchMouseEvent](https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/browser_protocol.json#L6871) with type [mouseWheel](https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/browser_protocol.json#L6882)

```js
  async wheel(options = {}) {
    await this._client.send('Input.dispatchMouseEvent', {
      type: 'mouseWheel',
      deltaX: options.deltaX,
      deltaY: options.deltaY
    });
  }
```

**Comment by aslushnikov** [comment]
@kblok If I recall correctly, we wanted to figure out a way to wait for scrolling to end after the mouse wheel event so that `page.wheel()` will return after scrolling is complete. This might not be that important though - do you have any usecase in mind?

cc @JoelEinbinder how had some thoughts regarding this

**Comment by kblok** [comment]
It was requested by a pptr# contributor. Though it's already implemented on our side, for me is important to be close to the implemented we have (or going to have) here.

He suggested checking the scrolling completed in this way:

```js
page.waitForFunction(
    (x, y) => document.body.scrollLeft === x && document.body.scrollTop === y,
    {},
    x,
    y);
```

**Comment by JoelEinbinder** [comment]
It isn't enough for us to check the body scroll position. Internal elements could scroll. Scrolls could be captured. They could land in shadow dom or iframes. Trying to figure out when a scroll has finished from JavaScript is going to require many layers of hacks, if it is doable at all.

There have been some patches related to this landing in Chromium. I need to find some cycles to move dispatchMouseEvent to a better code path for wheel events, but right now it's unfortunately not a high priority for me.

**Comment by jeroenvisser101** [comment]
> If I recall correctly, we wanted to figure out a way to wait for scrolling to end after the mouse wheel event so that `page.wheel()` will return after scrolling is complete. This might not be that important though - do you have any usecase in mind?

Couldn't we make it similar to how clicking and waiting for navigation works? That would allow all sorts of customisability. I could imagine that anything else we come up with might break for some use-cases, think scroll events that are captured inside a canvas for games, not to mention the iframe/shadow dom issues @JoelEinbinder mentioned.

Then, when a better way of confirming the scroll event is available, we could just introduce it as a separate function (`waitForScroll(...)`).

**Comment by timocov** [comment]
Is this feature available to being implemented by outside contributors?

**Comment by mathiasbynens** [comment]
It is, and in fact it was contributed recently: #6141 🎉
