### ISSUE TITLE
Page evaluate click() throws error but it works normally in the browser

### ISSUE THREAD

**Issue by stemie** [puppeteer/puppeteer#4120]
If run the following code manually in the browser it works as expected (clicks the link and loads the next page

	var fixture = 'fixture_0'

	var num = fixture.split('_')[1]

	var buttonClick = document.getElementById(fixture)

	buttonClick.click()

	var dropdowns = document.querySelectorAll('tr td:first-child div.dropdown')

	var button = document.querySelector('div.dropdown #'+fixture)

	var fieldsLink = dropdowns[num].querySelectorAll('a')[2]
        
    console.log(fieldsLink)

    fieldsLink.click()

However, if I run the same code inside `await page.evaluate( () => {})` using puppeteer I get `UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'click' of null`

Why is it throwing this error when it runs fine if I run the code manually in the browser? I can see that `fieldsLink` has selected the right element.

**Comment by aslushnikov** [comment]
@stemie hard to say unless you can share your exact puppeteer script that we can run locally

**Comment by stemie** [comment]
I was doing a for loop in `browser.newPage` (eg. `for (const fixture of fixtures) {})`) and forgot to open new pages for each item in the loop. I couldn't make sense of the error message initially, problem solved.
