### ISSUE TITLE
Copy content  from Puppeteer generated PDF and paste to MS word, some characters are missing

### ISSUE THREAD

**Issue by MarkMai-Loftware** [puppeteer/puppeteer#4125]
### Steps to reproduce
1. Use the HTML with Headless Chrome to generate a PDF.
2. If the font is Calibri and the content includes 'ft'. It displays correctly in PDF, but the 'ft' will miss when copy the content from the PDF.
e.g. :
The PDF includes the content 'I am leaving the day after tomorrow.'
I expected the content to be pasted as 'I am leaving the day after tomorrow.' 
But in MS word, it displayed 'I am leaving the day aer tomorrow.'
The 'ft' is missing for the word 'after'

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: Win10
* URLs (if applicable):
* Node.js version: 8.11.3

**What steps will reproduce the problem?**
Copy the content from the PDF and paste it.

_Please include code that reproduces the issue._

The puppeteer.js is :
const puppeteer = require('puppeteer');
const path = require('path');
async function createHeadlessChromeInstance() {

browser = await puppeteer.launch(
    {
        ignoreHTTPSErrors: false
    }
);
const page = await browser.newPage();
// Set viewport to a fixed size. 
await page.setViewport({width: 750, height: 600});
    return page;
}
async function generatePdf() {
    // create page instance
    let page;
    let navigationTimeout = 60000;  // 1 min
    let response;
    try {
        page = await createHeadlessChromeInstance();
        response = await page.goto("file://" + 'D:\\test\\testdata_font.html', {
            timeout: navigationTimeout,
            waitUntil: ['load', 'networkidle2']
        });
        await page.waitFor(500);
    }catch (error) {
        throw error;
    }

// generate pdf for the current page
pdfProperties = {};
pdfProperties.path = 'output.pdf';
pdfProperties.margin = '1in';
pdfProperties.displayHeaderFooter = false;
pdfProperties.printBackground = true;

pdfProperties.width = '8.27in';
pdfProperties.height = '11.7in';
await page.pdf(pdfProperties);
await browser.close();
}

async function main() {
        try {
            await generatePdf();
        } catch(e) {
            return process.exit(1);
        }
		console.log("pdf conversion completed successfully.");
        return process.exit(0);
}
main();

The HTML is:
< !DOCTYPE html >
< html >
< head >
< title >Page Title</ title >
</ head >
< body >

< h1 >This is a test page</ h1 >
< h1 style="font-family:Calibri;">I am leaving the day after tomorrow.</ h1 >
</ body >
</ html >

**What is the expected result?**
The content display correctly when copy from the PDF

**What happens instead?**
The 'ft' is missing for 'after' that uses Calibri font
Here is PDF that was generated by Puppeteer :
[output.pdf](https://github.com/GoogleChrome/puppeteer/files/2934796/output.pdf)

**Comment by adhokshaja** [comment]
Noticed a similar issue with the word "fish" when using 'Lato' font from google fonts . The "fi" from fish seem to be rendered as a single character.
The font likely considers "fi" "ft" and the like as font-ligatures and renders them differently.
This may not be a puppeteer issue, but an issue with the font family. Other font font ligatures to try would be fa, fe, fo, fr, fs, ft, fb, fh, fu, fy. 

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet"
        type="text/css">
    <title>Puppeteer Test</title>
</head>
<body style="font-family: 'Lato', sans-serif">
    <h1>Just letters</h1>
    <ul>
        <li>fi </li>
        <li>fl </li>
        <li>fa </li>
        <li>fe </li>
        <li>fo </li>
        <li>fr </li>
        <li>fs </li>
        <li>ft </li>
        <li>fb </li>
        <li>fh </li>
        <li>fu </li>
        <li>fy </li>
    </ul>
<h1>In words</h1>
    <ul>
        <li>fish </li>
        <li>float </li>
        <li>farm </li>
        <li>feel </li>
        <li>foul </li>
        <li>france </li>
        <li>fstop </li>
        <li>after </li>
        <li>fbook </li>
        <li>offhand </li>
        <li>snafu </li>
        <li>stuffy</li>
    </ul>

</body>
</html>
```

**Comment by manojchandrashekar** [comment]
In case somebody is looking for a solution to this, a possible workaround is to disable ligatures from CSS:

`font-variant-ligatures: none;`

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

**Comment by kjeske** [comment]
Thanks @manojchandrashekar, works like a charm. How did you get to that?

**Comment by manojchandrashekar** [comment]
:) I don’t remember too well, but it was related to rendering a PDF that was generated using a font that supported ligatures vs a font which did not.
