### ISSUE TITLE
Page.addScriptToEvaluateOnNewDocument doesn't work as expected

### ISSUE THREAD

**Issue by levkochetkov** [puppeteer/puppeteer#4126]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: MacOS 10.12.4
* URLs (if applicable):
* Node.js version: 11.9.0

**What steps will reproduce the problem?**

1. Put the following to `run.js`:
```
#!/usr/bin/env node

const http = require('http');
const puppeteer = require('puppeteer');

async function main() {
    let server = createServer();
    await server.listen();
    const port = server.address().port;
    puppeteer.launch().then(async (browser) => {
        let page = await browser.newPage();
        await page.exposeFunction('ping', () => {
            return 'pong';
        });
        await page.goto(`http://localhost:${port}/`);
        await page.evaluate(() => {
            let f = document.createElement('iframe');
            f.srcdoc = '';
            document.body.appendChild(f);
            f.contentDocument.open();
            f.contentDocument.close();
        });
        for (let frame of page.mainFrame().childFrames()) {
            let result = await frame.evaluate(() => {
                try {
                    return ping();
                } catch (e) {
                    return e.toString();
                }
            });
            console.log(result);
        }
        await browser.close();
        await server.close();
    });
}

function createServer() {
    return http.createServer((req, res) => {
        res.setHeader('Content-Type', 'text/html');
        let content = '<html><head></head><body></body></html>';
        res.end(content);
    });
}

main();
```
2. `chmod +x run.js`
3. `./run.js`

**What is the expected result?**
The expected result is `pong` (in the console output).

**What happens instead?**
Instead of the expected result you will see `Invalid arguments: should be exactly one string.`. The reason is that the scripts that was added using [Page.addScriptToEvaluateOnNewDocument](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-addScriptToEvaluateOnNewDocument) won't be added to the iframes that are created such way (using srcdoc and document.open).

**Comment by stevenvachon** [comment]
Syntax highlighting would be nice.
