### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT appears when using version 1.13

### ISSUE THREAD

**Issue by mycrl** [puppeteer/puppeteer#4127]
* Puppeteer version: 1.13.0
* Platform / OS version: Windows 10
* Node.js version: 10.15.2
* Chrome version: 72.0.3626.121

When I connect to the chrome instance using the ``1.13`` version, the ``ERR_BLOCKED_BY_CLIENT`` error message appears when using ``request.continue({ url: xxxx })``. When I roll back puppeteer ``1.12.2``, the problem no longer occurs.

Also includes an additional question, Chrome has let the tips for automatic test software control disappear.

These problems occur when I connect to a local chrome instance using ``puppeteer.connect``.

**Comment by aslushnikov** [comment]
> When I connect to the chrome instance using the 1.13 version, the ERR_BLOCKED_BY_CLIENT error message appears when using request.continue({ url: xxxx }). When I roll back puppeteer 1.12.2, the problem no longer occurs.

@xivistudios any script I can try locally to repro this?

**Comment by mycrl** [comment]
> > When I connect to the chrome instance using the 1.13 version, the ERR_BLOCKED_BY_CLIENT error message appears when using request.continue({ url: xxxx }). When I roll back puppeteer 1.12.2, the problem no longer occurs.
> 
> @xivistudios any script I can try locally to repro this?

easy

First download and install chrome.
use ``puppeteer.connect(options)`` function connect Chrome Instance.
open any webpage.
bind ``page.on('request')``.
use ``request.continue({ url: xxx })`` Overwrite request.

**Comment by mycrl** [comment]
this is my configure.
```toml
[reptile.browser]
path = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
host = "localhost"
port = 9222
width = 1920
height = 1080
```
next, start local chrome child process.
```js
let debuggers = `--remote-debugging-port=${port}`
let chrome = childProcess.spawn(path, [ debuggers ])
```
I use axis to get debug information for chrome instances.
```js
let template = "http://%s:%s/json/version"
let path = util.format(template, host, port)
let { data } = await axios.get(path)
let WSPath = data.webSocketDebuggerUrl
```
Connection chrome instance.
```js
let path = util.format("http://%s:%s", host, port)
await puppeteer.connect({
    defaultViewport: { width, height },
    browserWSEndpoint: WSPath,
    executablePath: path
  })
```
When I proxy the request.
```js
 .on("request", req => {
    req.continue({
       url: "xxx"
    })
  })
```
Chrome jump error: ``ERR_BLOCKED_BY_CLIENT``.

This problem occurs when I try to rewrite a download request to a different address.

This is my current usage. I use ``puppeteer.connect`` to connect to the local chrone instance that starts the debugging protocol. This is done to keep the persistence of the cookie.

**Comment by aslushnikov** [comment]
@xivistudios are you sure v1.12.2 doesn't have this problem? v1.13.0 didn't touch network handling. This might happen if your Chrome instance auto-updated behind your back.

**Comment by mycrl** [comment]
> @xivistudios are you sure v1.12.2 doesn't have this problem? v1.13.0 didn't touch network handling. This might happen if your Chrome instance auto-updated behind your back.

I am sure.
I have not changed any code, just roll back the version to 1.12.2, this problem no longer appears.

**Comment by aslushnikov** [comment]
@xivistudios ok, so when and where does the `ERR_BLOCKED_BY_CLIENT` appear? Can you give me a small script that I can run locally to reproduce this?

**Comment by mycrl** [comment]
@aslushnikov Sorry, I can't reproduce this question.

Today I tried to create a script and then reproduce the problem, but I found that the problem no longer appeared. I tried to upgrade yesterday's wrong project to 1.13.0. Again, I found that this problem did not happen. God proved that I had this problem yesterday.

My test script:
```js
const puppeteer = require("puppeteer")
const childProcess = require("child_process")
const axios = require("axios")
const util = require("util")

const DOWN_PROXY = /http:\/\/download.redis.io\/(.*).tar.gz/

const CHROME_PATH = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
const CHROME_HOST = "localhost"
const CHROME_PORT = 9222
const CHROME_WIDTH = 1920
const CHROME_HEIGHT = 1080

void (async function () {
  let debuggers = `--remote-debugging-port=${CHROME_PORT}`
  let chrome = childProcess.spawn(CHROME_PATH, [ debuggers ])
  let template = "http://%s:%s/json/version"
  let LocalPath = util.format(template, CHROME_HOST, CHROME_PORT)
  let { data } = await axios.get(LocalPath)
  let WSPath = data.webSocketDebuggerUrl
  
  let handle = await puppeteer.connect({
    defaultViewport: { width: CHROME_WIDTH, height: CHROME_HEIGHT },
    browserWSEndpoint: WSPath,
    executablePath: LocalPath
  })
  
  let context = await handle.newPage()
  
  void await context.setRequestInterception(true)
  context.on("request", req => {
    console.log("==============>>", req.url())
    DOWN_PROXY.test(req.url()) ? req.continue({
      url: "http://download.redis.io/releases/redis-5.0.3.tar.gz"
    }) : req.continue()
  })
  
  void await context.goto("https://redis.io", {
    timeout: 120000
  })
  
  process.on("SIGINT", _ => {
    chrome.kill()
    process.exit()
  })
})()
```

Let me recall, I installed the windows10 system yesterday, then installed chrome, logged into the Google account, pulled out the project from github, and then installed the dependencies through npm i, including puppeter, I did not lock the version, so the installation version is 1.13 .0, when I tried to continue working, I found that there was a problem with the rewrite request. I am trying to solve the problem. I first discovered the version number upgrade issue. I tried to roll back to 1.12.2 and then restart the project for testing. The problem no longer occurs. When I returned to 1.13.0, the problem reappeared. I tried to install the latest Chrome instance and then started it in the same way. The same problem reappears. I am trying to use ppupeteer.launch to launch the built-in chrome instance. No problem, it makes me confused.

During this process, I restarted the computer and updated the Windows system. When I try to reproduce it again today, the problem no longer appears.

Sorry, this may be a problem that doesn't exist or is difficult to trigger. I am sorry for delaying your time.
