### ISSUE TITLE
add :contains(text) and others advanced selectors

### ISSUE THREAD

**Issue by Skadabr** [puppeteer/puppeteer#4128]
made quick solution to be able to use advanced css selectors like ":contains(text)"
it's formed now as library, but what if consider adding this feature to puppeteer itself?

https://github.com/Skadabr/puppeteer-selector
example
```javascript
const puppeteer = require('puppeteer');
const select = require ('puppeteer-select');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  
  await select(page).assertElementPresent('div.Tag:contains(Events) > button');
  const element = await select(page).getElement('div.Tag:contains(Events) > button');
  await element.click()

  await browser.close();
})();
```

this lib is using "sizzle"
all available selectors are here https://github.com/jquery/sizzle/wiki#selectors

if authors like the idea I'll make PullRequest

**Comment by aslushnikov** [comment]
@Skadabr let's keep this as a third-party library for now. Once there's a wide adoption and enough demand, we'll add it in. 

Thanks!
