### ISSUE TITLE
A request is not being sent in headless mode.

### ISSUE THREAD

**Issue by charlie632** [puppeteer/puppeteer#4129]
I have a script running in headful and works just fine. When I try to run it in headless mode, some content is not rendering, thus, making the script to crash.

I tracked down the issue and it is a single request not being triggered. 

I traced the request using the _Network Tab_ in Chrome Dev Tools and is the following:

![network request](https://user-images.githubusercontent.com/8704336/53901162-e0aca080-4003-11e9-9ae3-9d66197ec9d3.png)

There is a gear icon in the request's name, indicates that that request is being fired by a Service Working, based on this [StackOverflow answer](https://stackoverflow.com/questions/48336926/name-with-gear-icon-in-chrome-network-requests-table).

![URL of the SW](https://user-images.githubusercontent.com/8704336/53901301-4f89f980-4004-11e9-9dc1-a057d1b4c1a6.png)

Now, inspecting the sources, indeed, there is a ServiceWorker

![ServiceWorker in sources](https://user-images.githubusercontent.com/8704336/53902955-0340b880-4008-11e9-913d-d1d62f4a3fbb.png)

### Puppeteer script

What I did is to initialize my instance like this

```javascript
puppeteer
  .launch({
    headless: false,
    args: ["--disable-setuid-sandbox", "--no-sandbox", "--enable-features=NetworkService"],
    ignoreHTTPSErrors: true
  })
  .then(async browser => { 
   // Code here
  })
```

And, to monitor each request I add a _request_ listener like this:

```javascript
page.on("request", r => {
      console.log(r.url());
    });
```

Now, if I run my execution _headful_, i get this result:

![URL](https://user-images.githubusercontent.com/8704336/53901102-b8bd3d00-4003-11e9-83d2-74b19a3befc0.png)

The request is fullfilled and the page loads correctly.

Now, if I run it in _headless_ mode, this request, and others that depends on it, do not appear, making some content to not render.

### Solutions tried

- I tried with different combinations or ***args*** and keep getting same result.

- changing puppeteer version

- Using local Chrome with _executablePath_

- Different machine (also Windows)

- Changing the SuperAgent like this
```javascript
await page.setUserAgent(
      "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
    );
```

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Windows 10 Enterprise Edition
* URLs (if applicable): N/A
* Node.js version: 11.10.0 and 10.0.0

**What is the expected result?**

Page loads correctly. 
Requests are sent successfully.

**What happens instead?**

_blob: https://_ is not firing in headless mode. Thus, content is not loading.

Maybe is something with ServiceWorkers?

**Comment by tmarcote** [comment]
Any news on this? Im experiencing something similar.
I've got a form that's being submited properly on "headless: false".
When using "headless: true", the request is never sent.
Thanks

**Comment by alfrejivi** [comment]
Any update on this?

**Comment by MadisonFromVrume** [comment]
I'm running in to the same issue, any updates?

**Comment by austin-carnahan** [comment]
I was having a similar issue with interceptors failing to pickup requests and also noticed the gear icon indicating service worker requests. 
Setting the browser to bypass service workers resolved the issue for me:
`page._client.send('Network.setBypassServiceWorker', {bypass: true})`

There's some good documentation that dives into the details here:
[puppeteer issue #4041](https://github.com/puppeteer/puppeteer/issues/4041)

**Comment by shaneosullivan** [comment]
I'm seeing the same thing.  The service worker appears to have been installed just fine, however it is not firing its requests, and therefore the page is not being correctly rendered as it depends on the result of this request.  It all works just fine with `headless: false`, and does not work with `headless: true`.

I tried the suggested `page._client.send('Network.setBypassServiceWorker', {bypass: true})` code, and it did not help

**Comment by kopax-polyconseil** [comment]
Hello, we want to test also our service worker update using puppeteer, did you succed ? Can we reopen this ?
