### ISSUE TITLE
connection IP addresss

### ISSUE THREAD

**Issue by blue-cp** [puppeteer/puppeteer#413]
Is there a way to get connection IP address?

**Comment by pavelfeldman** [comment]
Could you elaborate? Which connection?

**Comment by blue-cp** [comment]
I am trying go get IP of the host  (A Record for the domain)

Thanks

**Comment by pavelfeldman** [comment]
I.e. you want to see what IP host name you pass into puppeteer resolves to? This seems to be outside of the scope for puppeteer.

**Comment by Stancobridge** [comment]
How do I get the IP address used for a request in puppeteer, I am sending request with different IP address in my network, I want to verify that puppeteer is using this address to send the request

**Comment by Poyoman39** [comment]
For those coming to this thread. Have a look to page events. ( https://pptr.dev/api/puppeteer.pageeventobject.requestfinished ) You can retrieve IP in HTTPResponse
