### ISSUE TITLE
Puppeteer Freezes when i put chromium on background , when i get it back to foreground script execution continues

### ISSUE THREAD

**Issue by ArvindReddyC** [puppeteer/puppeteer#4131]
* Puppeteer version: 1.13.0
* Platform / OS version: Mac / 10.14.2
* URLs (if applicable):
* Node.js version: 5.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');


let nau = async () =>{
const browser = await puppeteer.launch({timeout:300000,headless:false});
const page = await browser.newPage();
var g =    await page.goto('https://my.naukri.com/Profile/edit?id=&altresid',{timeout:300000});
var there  = await page.$("#usernameField");

//var there2 = await page.$("#emailTxt");
if(there != null)
{
   await page.click("#usernameField");
   await page.keyboard.type("aravindreddy.net@gmail.com");

   await page.click("#passwordField");
   await page.keyboard.type("9019444140@qQ");

   await page.keyboard.press('Enter');
   await page.waitForNavigation()
    for(var i=0 ; i< 40 ; i++)
    {
    var test = await page.$("#root");
    var h = await test.$(".resumeHeadline");
    var j = await h.$(".widgetHead");
    var k = await j.$(".widgetTitle + span")
    await k.click();
  //  page.waitFor()
    console.log("hello")
    
    await page.keyboard.press('Tab');
    await page.keyboard.type(".");
    await page.keyboard.press('Tab');
    await page.keyboard.press('Tab');
    await page.keyboard.press('Enter')
    console.log("Job Done" + i);
   await page.waitFor((60000*3));
    }
}
else{
    await page.click("#emailTxt");
   await page.keyboard.type("arvindchandrashekar@hotmail.com");

   await page.click("#pwd1");
   await page.keyboard.type("9019444140");

   await page.keyboard.type('Enter');

}



}
nau();
```

**What is the expected result?**
When i run the above script and have chromium in foreground , the script does its intended work , i expect the script to do the same when  I put chromium in background.

**What happens instead?**
when i put chromium in background the script flow kind of freezes , until i get chromium in foreground again.

**Comment by vsemozhetbyt** [comment]
[Could this be related?](https://developers.google.com/web/updates/2017/03/background_tabs)

Can `--disable-background-timer-throttling` flag help?

**Comment by aslushnikov** [comment]
> Can --disable-background-timer-throttling flag help?

@vsemozhetbyt we pass it already by default

@ArvindReddyC Your script works for me when a put Chromium in a background; what do I do wrong?

**Comment by pedroapfilho** [comment]
It happens sometimes with me too (not always), but only when I use it with headless:false

**Comment by david-littlefield** [comment]
### [Solution]:

Add the following values to the array you assign to the args property in the options object. Now, you should be able to run Puppeteer while your window is in the foreground, background, or minimized. 

```
const chromeArgs = [
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-renderer-backgrounding'
];
```
Solution and explanation available in an article written by **Rohit Kumar**, @rkr090 at Big Binary:

[Debugging failing tests in puppeteer because of background tab](https://blog.bigbinary.com/2018/08/15/debugging-failing-tests-in-background-tab-in-puppeteer.html)

**Comment by szilardx** [comment]
For me the previous solution did not worked (Win 10).
My hacky workaround is to normalize the Chromium window if it is accidently minimized, then use alt+tab to put it in the background.

I send the windowState: 'normal' command through CDPSession, as found here:
https://github.com/GoogleChrome/puppeteer/issues/4513#issuecomment-500195352

**Comment by pedroapfilho** [comment]
I just checked and it's happening to me only when I'm using a proxy. Idk how it's related..

**Comment by miakh** [comment]
@szilardx Setting windowState to 'normal' is only thing that worked. How did you manage alt+tab to get working? Also using Puppeteer?

**Comment by leadscloud** [comment]
> ### [Solution]:
> Add the following values to the array you assign to the args property in the options object. Now, you should be able to run Puppeteer while your window is in the foreground, background, or minimized.
> 
> ```
> const chromeArgs = [
>   '--disable-background-timer-throttling',
>   '--disable-backgrounding-occluded-windows',
>   '--disable-renderer-backgrounding'
> ];
> ```
> 
> Solution and explanation available in an article written by **Rohit Kumar**, @rkr090 at Big Binary:
> 
> [Debugging failing tests in puppeteer because of background tab](https://blog.bigbinary.com/2018/08/15/debugging-failing-tests-in-background-tab-in-puppeteer.html)

when minimize window, that also not working. must max the window.

**Comment by dminovski0** [comment]
This worked by @maxktz:
https://github.com/puppeteer/puppeteer/issues/3339#issuecomment-2293340307

> # SOLUTION
> Since chrome has built in feature to emulate a focused page, I am just activating it using CSP session.
> 
> Works fine:
> 
> ```js
> const session = await page.createCDPSession();
> await session.send(`Emulation.setFocusEmulationEnabled`, { enabled: true });
> ```
>

**Comment by Vu7mau** [comment]
Hi, I’d like to reopen this issue.

On Windows 10, when the Chrome window is minimized (to taskbar), all Puppeteer actions such as page.click(), page.type(), page.waitForSelector() are frozen — they do not throw errors or time out, but simply stop executing until the Chrome window is restored.

I have already tried the recommended flags:

diff
Sao chép
Chỉnh sửa
--disable-backgrounding-occluded-windows  
--disable-renderer-backgrounding  
--disable-background-timer-throttling  
--disable-features=CalculateOcclusion  
…but they do not help when the window is minimized (not just occluded). Chrome completely pauses the DOM and JS runtime.

**Comment by Asicosilomu** [comment]
> Hi, I’d like to reopen this issue.
> 
> On Windows 10, when the Chrome window is minimized (to taskbar), all Puppeteer actions such as page.click(), page.type(), page.waitForSelector() are frozen — they do not throw errors or time out, but simply stop executing until the Chrome window is restored.
> 
> I have already tried the recommended flags:
> 
> diff Sao chép Chỉnh sửa --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --disable-background-timer-throttling --disable-features=CalculateOcclusion …but they do not help when the window is minimized (not just occluded). Chrome completely pauses the DOM and JS runtime.

Excuse the bump, but I'm also having a very similar issue. When using multiple tabs in a headful browser, operations on every tab except the active one freeze in the same way; hang forever until either the tab is selected, or it's hovered over until the preview loads. This completely breaks my script as it just hangs forever, I've implemented code to cycle through all tabs every second but it's not an acceptable workaround. I'm using Puppeteer 25.1.0 on Linux and Node.js v22.22.2

Edit: Forgot to mention, but I had added all three of '--disable-background-timer-throttling', '--disable-backgrounding-occluded-windows', '--disable-renderer-backgrounding' to my launch arguments. It makes no difference.
