### ISSUE TITLE
Page.pdf freezed on page with frameset and frame tags

### ISSUE THREAD

**Issue by cirdes** [puppeteer/puppeteer#4136]
* Puppeteer version: 1.12.2
* Platform / OS version: MacOS 10.14.3
* URLs (if applicable): https://www.dividaativa.pge.sp.gov.br/da-ic-web/
* Node.js version: v8.11.1

**What steps will reproduce the problem?**

```
'use strict';

const puppeteer = require('puppeteer');
const URL = 'https://www.dividaativa.pge.sp.gov.br/da-ic-web/';

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: true,
      ignoreHTTPSErrors: true,
    });
    const page = await browser.newPage();
    await page.goto(URL, {
      waitUntil: ['domcontentloaded', 'networkidle0'],
    });
    await page.pdf({path: '/tmp/file.pdf'});
  } catch (err) {
    console.error(err);
  }
})();
```

**What is the expected result?**
Expected the PDF to be generated

**What happens instead?**
The PDF call freezes the execution. Using puppeteer version 1.11.0 the pdf is generated.

Can anybody reproduce?

**Comment by vsemozhetbyt** [comment]
With Tip-Of-Tree (1.13.0-post) PDF is generated on Windows 7 x64.

**Comment by cirdes** [comment]
I found this on my application running in Google Cloud Function and reproduce locally on mac.

**Comment by aslushnikov** [comment]
@cirdes works like a charm for me on v1.13.0 and mac os x.

One thing though: I added a "browser.close" call right after PDF generation. It might be this tricked you into believing that script "hangs".

```js
const puppeteer = require('puppeteer');
const URL = 'https://www.dividaativa.pge.sp.gov.br/da-ic-web/';

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: true,
      ignoreHTTPSErrors: true,
    });
    const page = await browser.newPage();
    await page.goto(URL, {
      waitUntil: ['domcontentloaded', 'networkidle0'],
    });
    await page.pdf({path: '/tmp/file.pdf'});
    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

(speculatively) closing this.

**Comment by cirdes** [comment]
@aslushnikov, on version 1.12.2 was not working here but after update to 1.13.0 is now working like a charm!

Thanks for the wonderful job on Puppeteer
