### ISSUE TITLE
I cannot launch puppeteer in Dex Linux (Samsung GalaxyNote 9(

### ISSUE THREAD

**Issue by gogo9th** [puppeteer/puppeteer#4145]
Hi,

I'm trying to run Puppeteer from  Linux on Dex (Ubuntu 16.04) running on Galaxy Note 9. However, when I launch Puppeteer I get the following error message:

> chrome-experiment-result$ sudo node myPuppeteer.js https://google.com out
> (node:27841) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
> /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 18: /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 1: /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: ?Udmv~�����������: not found�
> @8
>   @,*@@@hh���,+r,+r0r0r0r: not found
> 
> /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 19: /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: Syntax error: ")" unexpected
> /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 1: /home/dextop/Desktop/expose_runner/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: ELF: not found
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 
>     at onClose (/home/dextop/Desktop/expose_runner/node_modules/puppeteer/lib/Launcher.js:342:14)
>     at Interface.helper.addEventListener (/home/dextop/Desktop/expose_runner/node_modules/puppeteer/lib/Launcher.js:331:50)
>     at emitNone (events.js:111:20)
>     at Interface.emit (events.js:208:7)
>     at Interface.close (readline.js:368:8)
>     at Socket.onend (readline.js:147:10)
>     at emitNone (events.js:111:20)
>     at Socket.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:139:11)
> (node:27841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:27841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Some letters above are broken for some reason... 

Also, if I launch chromium-browser from the command line, I get the following error message:

> Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
> Trace/breakpoint trap

However, if I run chromium-browser as a root without sandbox, it runs fine:

> sudo chromium-browser https://google.com --no-sandbox

How could I successsfully run Puppeteer from Linux on Dex?

**Comment by aslushnikov** [comment]
> However, when I launch Puppeteer I get the following error message:

@gogo9th I haven't heard about Linux Dex before. From what I briefly read, it's a Linux running on Samsung Galaxy device. I assume Galaxy is an ARM, and we currently don't have ARM builds. That'll explain your error.

> Also, if I launch chromium-browser from the command line, I get the following error message:

This happens due to lack of sandbox setup. Check out our [sandbox troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)

> How could I successsfully run Puppeteer from Linux on Dex?

You can run the pre-installed Chromium browser, but make sure to pick the right version of Chromium - [our faq](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

I hope this helps.
