### ISSUE TITLE
How to get the "Network -> Media -> Request URL -> Value/Path" using Puppeteer

### ISSUE THREAD

**Issue by menjilx** [puppeteer/puppeteer#4146]
Hi everyone,

How should I traverse the page and get the Network Request URL and get the Value using puppeteer? Here's the screenshot and the value that I want to grab.

![image](https://user-images.githubusercontent.com/14908836/54072507-a4ed3180-42b6-11e9-9e16-72c6c3af58b6.png)

Thank you so much!

**Comment by vsemozhetbyt** [comment]
Something like this?
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://openload.co/embed/OzEFf-v-Axs/SampleVideo_1280x720_20mb.mp4');

    page.setRequestInterception(true);
    page.on('request', (request) => {
      if (request.resourceType() === 'media') {
        console.log(request.url());
      }
      request.continue();
    });

    await page.click('body');
    await page.waitFor(3000);
    await page.click('body');

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by menjilx** [comment]
> Something like this?
> 
> ```js
> 'use strict';
> 
> const puppeteer = require('puppeteer');
> 
> (async function main() {
>   try {
>     const browser = await puppeteer.launch({ headless: false });
>     const [page] = await browser.pages();
> 
>     await page.goto('https://openload.co/embed/OzEFf-v-Axs/SampleVideo_1280x720_20mb.mp4');
> 
>     page.setRequestInterception(true);
>     page.on('request', (request) => {
>       if (request.resourceType() === 'media') {
>         console.log(request.url());
>       }
>       request.continue();
>     });
> 
>     await page.click('body');
>     await page.waitFor(3000);
>     await page.click('body');
> 
>     // await browser.close();
>   } catch (err) {
>     console.error(err);
>   }
> })();
> ```

I tried this one and it's weird cause I got several results, I expected to get one url only :)
-
![image](https://user-images.githubusercontent.com/14908836/54073062-bede4280-42bd-11e9-8fcc-51588b76d0be.png)

But nevertheless, it works! Thank you so much!

**Comment by vsemozhetbyt** [comment]
Maybe the rest URLs are produced by the second click, I was not sure if it is needed. You can delete it if it is redundant for you case.

**Comment by menjilx** [comment]
> Maybe the rest URLs are produced by the second click, I was not sure if it is needed. You can delete it if it is redundant for you case.

Thank you so much, will play around with this code.
