### ISSUE TITLE
Click issue on map > area element

### ISSUE THREAD

**Issue by hlr1983** [puppeteer/puppeteer#4147]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Linux henrique-Latitude-5480 4.15.0-46-generic #⁠49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* URLs (if applicable): 
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

I want to click on selector `area[alt="OK"]`, wich on Elements tab is shown as (right clicked on the "OK" displayed in browser and click on "Inspect" to see it)

```
<map name="Map">
  <area shape="RECT" target="_self" alt="OK" coords="200,14,279,40" href="javascript: submitform();">
</map>
```
The code I ran is

```
(async () => {

    try {
        const puppeteer = await require('puppeteer');

        const browser = await puppeteer.launch({
                        //headless: false, 
                    });
        const incognito = await browser.createIncognitoBrowserContext();
        const page = await incognito.newPage();
        
        await page.goto('file://' + process.cwd() + '/test2/Login-DPRF.html',{waitUntil: 'load'});
        
        const _closeDialog = async function _closeDialog(dialog) {
            await console.log(`DIALOG "${dialog.type()}": "${dialog.message()}"`);
            await dialog.dismiss();
        }

        await page.on('dialog', _closeDialog);
        
        //await console.log('page.evaluate 1');
        //await page.evaluate(() => submitform());
        //await console.log('page.evaluate 2');
        //await page.evaluate(() => document.querySelector('area[alt="OK"]').click());

        await console.log('page.click');
        await page.click('area[alt="OK"]');
        
        await browser.close();

    } catch (e) {
        await console.log(e);
        await process.exit(1);
    };
})()
```

**What is the expected result?**
Clicks and runs submitform(). Acctually, I edited it on a local file to shown an alert.

**What happens instead?**
Throws Error: Node is either not visible or not an HTMLElement .

The element doesn't seems to be visible in Chrome, despite it was shown when clicked on Inspect:

![image](https://user-images.githubusercontent.com/19354250/54073394-4f3c6900-4265-11e9-99c6-034ffd20ce4a.png)

But on Firefox it does:

![image](https://user-images.githubusercontent.com/19354250/54073411-8448bb80-4265-11e9-8e8e-12d19aad016b.png)

Sorry for the black stripes, I had to add them because the screen potentially shows private data. Running `await page.evaluate(() => document.querySelector('area[alt="OK"]').click())` or `await page.evaluate(() => submitform())` works.

Is this the expected behavior of Chrome and/or Puppeteer? Or is an issue with the page I'm scraping?

I could send local files that reproduces this issue, if wanted.

Thanks.

**Comment by vsemozhetbyt** [comment]
If I understand correctly, `map`  elements are not rendered (their `clientHeight` or `clientWidth` are `0` in Chrome) and so they are not clickable, they just store the information about clickable areas on the image.

**Comment by hlr1983** [comment]
@vsemozhetbyt, I think it's what is happening. Even in firefox, the element `area[alt="OK"]` is all the image, not only the area in map > area. I already have the workarounds for my case, but it might be useful for the Puppeteer's developers or other people, so I opened this issue.

![image](https://user-images.githubusercontent.com/19354250/54075488-b6b2e280-427e-11e9-8071-f3d95c6399d8.png) area where clicking works in normal user browsing

![image](https://user-images.githubusercontent.com/19354250/54075538-7738c600-427f-11e9-8b84-133a890ecb42.png) full image

**Comment by aslushnikov** [comment]
>  I already have the workarounds for my case, but it might be useful for the Puppeteer's developers or other people, so I opened this issue.

@hlr1983 thanks for opening his! This will probably save someone's time.

> Is this the expected behavior of Chrome and/or Puppeteer? Or is an issue with the page I'm scraping?

As @vsemozhetbyt suggested, the core issue here in the `<area>` element having 0x0 size in Chrome. Fake-clicking through `page.evaluate` is a good workaround for this thing; alternatively, one can parse area's coordinates and use `page.mouse` to click in the center.

>  Even in firefox, the element area[alt="OK"] is all the image, not only the area in map > area

Well, looks like this'd work in `puppeteer-firefox` then.
