### ISSUE TITLE
page.evaluate not waiting

### ISSUE THREAD

**Issue by SeongwoonHong** [puppeteer/puppeteer#4148]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Mac oS 10.13.6
* URLs (if applicable):
* Node.js version: 11.2.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```
const crawler = async () => {
  try {
    const browser = await puppeteer.launch({
      headless: process.env.NODE_ENV === 'production'
    });
    const page = await browser.newPage();
    const url = 'http://www.example.com';

    await page.goto(url);
    const text = await page.evaluate(async () => {
      console.log('11')
      const result = document.querySelector('.something');
      if (result) {
        return result;
      }
    });

    if (text) {
      console.log(text);
    } else {
      console.log('no result');
    }
    await page.close();
    await browser.close();
   } catch (e) {
     console.error(e);
     await page.close();
     await browser.close();
   }
}
```

**What is the expected result?**

1 should be printed in console first.

**What happens instead?**

no result is printed in console

**Comment by vsemozhetbyt** [comment]
You use `console.log()` inside `page.evaluate()` function, so it outputs in the browser console, not in the system shell (Node.js console). You can see the output if you delete `await page.close(); await browser.close();` lines and open DevTools console in the browser.

**Comment by SeongwoonHong** [comment]
@vsemozhetbyt Thank you! It works like a charm
