### ISSUE TITLE
Using request interception to forward requests from each page to the correct proxy

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4151]
Hi, I've been trying to work out how I can use a different proxy for each page within puppeteer. I've seen this problem referenced in a couple of issues. However, I'm struggling to find a solution that works for me. In one of the larger threads this was suggested as a solution.

You can use request interception to forward requests from each page to the correct proxy.

_Originally posted by @JoelEinbinder in https://github.com/GoogleChrome/puppeteer/issues/678#issuecomment-327031269_

Is anybody able to give me some direction of how to do this? Any help would be appreciated, thanks.

**Comment by zebulonzh** [comment]
Guess [this case](https://github.com/GoogleChrome/puppeteer/issues/678#issuecomment-361957234) can help you.

**Comment by Cuadrix** [comment]
I made a module that does this. It's called [**puppeteer-page-proxy**](https://github.com/Cuadrix/puppeteer-page-proxy).
It supports setting a proxy for an entire page, or if you like, it can set a different proxy for each request.

First install it:
```
npm i puppeteer-page-proxy
```
Then require it:
```js
const useProxy = require('puppeteer-page-proxy');
```
**Using it is easy;**
Set proxy for an entire page:
```js
await useProxy(page, 'http://127.0.0.1:8000');
```

If you want a different proxy for each request,then you can simply do this:
```js
await page.setRequestInterception(true);
page.on('request', req => {
    useProxy(req, 'socks5://127.0.0.1:9000');
});
```
Then if you want to be sure that your page's IP has changed, you can look it up;
```js
const data = await useProxy.lookup(page);
console.log(data.ip);
```
It supports **http**, **https**, **socks4** and **socks5** proxies, and it also supports authentication if that is needed:
```js
const proxy = 'http://login:pass@127.0.0.1:8000'
```

Repository:
https://github.com/Cuadrix/puppeteer-page-proxy
