### ISSUE TITLE
Puppeteer saved PNG is NOT transparent

### ISSUE THREAD

**Issue by weilinzung** [puppeteer/puppeteer#4152]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version:  macOS Mojave
* URLs (if applicable):
* Node.js version: v8.4.0

**What steps will reproduce the problem?**

I am using Puppeteer to screen capture an HTML element with ID name.

The HTML element is with `border-radius: 50px` and I set Puppeteer with `omitBackground: true`.

```
<body> // bacgrkound normal defult white
  <div id="element" style="width: 200px; height: 400px; overflow: hidden; background:red; border-radius: 50px; border:1px solid black">
  <p style="color: white">I am the element!!!</p>
  </div>
</body>
```

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://localhost:3000', {"waitUntil" : "networkidle0"});
  const elements = await page.$('#element');
  await elements.screenshot({path: 'example.png', omitBackground: true});

  await browser.close();
})();
```

**What is the expected result?**

Transparent Rounded PNG

**What happens instead?**

The Saved PNG result gave me is a WHITE background, looks like it captured the BODY default WHITE background.

Thanks!

**Comment by weilinzung** [comment]
**update:**

ADDING `page.evaluate` before screenshot could work, but how about just have one `STRING` feature to turn it ON & OFF.

```
await page.evaluate(() => document.body.style.background = 'transparent');
await elements.screenshot({path: 'example.png', omitBackground: true});
```

credit to Thomas Dondorf: https://stackoverflow.com/questions/55105958/puppeteer-saved-png-is-not-transparent/#answer-55107065

**Comment by aslushnikov** [comment]
@weilinzung It's hard to determine what's an element's background: it might be some other element that casts wrong color.

The `omitBackground` option omits default *browser* background rather than the background of the "element" - so this works as expected.

**Comment by lsdsjy** [comment]
In my case, it's bootstrap specifying background of body to be white, so `omitBackground` didn't work.

**Comment by Hopding** [comment]
I could only get my background to be transparent by using the `!important` override in my css:
```css
body {
  background: transparent !important;
}
```

Once I'd done this, I just captured a screenshot with:
```js
await elements.screenshot({ path: 'example.png', omitBackground: true });
```
