### ISSUE TITLE
Context is not available in detached frame

### ISSUE THREAD

**Issue by strarsis** [puppeteer/puppeteer#4153]
@aslushnikov, @JoelEinbinder, @ebidel:

### Steps to reproduce
Page containing a hidden iframe which is displayed using JavaScript when a link is clicked.

* Puppeteer version: 1.12.2
* Platform / OS version: WSL (Bash on Windows)
* Node.js version: v8.14.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```js
const puppeteer = require('puppeteer');
var chromiumBinPath = '/usr/bin/chromium-browser';

(async () => {
    const browser = await puppeteer.launch({
        executablePath: chromiumBinPath,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const page = await browser.newPage();
    await page.goto('example-page');


    // workaround for frames caching issue
    // (https://github.com/GoogleChrome/puppeteer/issues/3506#issuecomment-448137289)
    const frames = await page.frames();


    // click link to open/display the iframe
    const linkHandlers = await page.$x("//a[contains(text(), 'Open the iframe')]");

    if (linkHandlers.length === 0)
        throw new Error('Link element not found by text');

    await linkHandlers[0].click();


    // wait for iframe becoming visible
    const iframeSelector = 'iframe.some-unique-class';
    await page.waitForSelector(iframeSelector, {
       visible: true, 
    });

   // find frame instance of iframe by its url (don't know any better way for this yet)
   var theIframe = false;
    for(var frame of frames) {
        if(frame.url().includes('some-unique-url-part')) {
            theIframe = frame;
            break;
        }
    }
    if(!theIframe)
        throw new Error('Iframe frame instance not found by URL');

    // Wait for a specific element inside the iframe to appear
    await theIframe.waitForSelector('.element-inside-the-iframe'); // fails here


    await page.screenshot({path: './screenshot.png'});

    await browser.close();
})();
````

**What is the expected result?**
An usable frame instance of the iframe which can be further used for waiting of elements it contains.

**What happens instead?**
Error:
````
UnhandledPromiseRejectionWarning: Error: Execution Context is not available in detached frame "[...]some-unique-url-part[...]" (are you trying to evaluate?) 
````

When the workaround for frames caching is not used, the frame disappears from the `frames()` list after they are displayed on the page (when the link is clicked). How to get this 'detached' frame for further querying its content?

Additional questions:
Can the frame instance be retrieved from an ElementHandler from querySelector(All)?
Can the ElementHandler be retrieved from a frame instance?

**Comment by aslushnikov** [comment]
> An usable frame instance of the iframe which can be further used for waiting of elements it contains.

@strarsis When iframe gets detached, its execution context gets destroyed. It's not Puppeteer's logic - that's how Chromium manages detached iframes.

> When the workaround for frames caching is not used, the frame disappears from the frames() list after they are displayed on the page (when the link is clicked).

Since detached iframe doesn't have any useful execution context, it gets' removed from the list of iframes.

> How to get this 'detached' frame for further querying its content?

You can use your workaround to cache it at some moment.

> Can the frame instance be retrieved from an ElementHandler from querySelector(All)?
> Can the ElementHandler be retrieved from a frame instance?

These I'm not sure I follow, but there's a [ElementHandle.contentFrame](https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-elementhandlecontentframe) method to jump from ElementHandle to Frame.

Does this help?

**Comment by royeradames** [comment]
https://stackoverflow.com/questions/66378493/why-does-frame-selection-breaks-after-page-reloads
