### ISSUE TITLE
 Error: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by stoplion** [puppeteer/puppeteer#4154]
**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: OSX 10.14
* Node.js version: v9.10.0

```
const puppeteer = require('puppeteer');

const jsonReturn = [];

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    devtools: true
  });

  const page = await browser.newPage();
  await page.evaluate(() => {
    debugger;
  });
  const response = await page.goto('https://myurl.com');

  console.log('served from cache?', response.fromCache());

  // debugger;
  await page.waitForSelector('.featured-shows-featured-show');

  const featuredShows = await page.$$('.featured-shows-featured-show');

  for (const featuredShow of featuredShows) {
    debugger;
    const link = await featuredShow.$('a');
    link.click();

    await page.waitForSelector('.show-title');

    debugger;

    const showTitle = page.$('.show-title')
    const showDates = page.$('.show-dates')
    const showLocation = page.$('.show-location')
    const showGallery = page.$('.entity-link')
    const showDetail = page.$('.show-press-release')

    jsonReturn.push({
      showTitle,
      showDates,
      showLocation,
      showGallery,
      showDetail,
    });


    await page.goBack();
  }

  console.log(jsonReturn);


  await browser.close();
})();
```

Getting Error:
`UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.`

**Comment by vsemozhetbyt** [comment]
If I understand correctly, `jsonReturn` contains ElementHanldles that cannot be used after `page.goBack()` navigation.

**Comment by JoelEinbinder** [comment]
Yep. showTitle, showDates, etc, are promises to ElementHandles that have not been resolved yet. They fail to resolve because the page navigates (`page.goBack`) before they can.

ElementHandles cannot be used after the element they reference is destroyed. This happens when the page navigates.

**Comment by stoplion** [comment]
ok thanks that fixed, closing

**Comment by Partom** [comment]
I am also facing same issue and working on same scenario. @stoplion Can you please share that how do you fixed this issue ? 

Thanks in Advance :+1:

**Comment by moxiaobei** [comment]
@stoplion I am also facing same issue and working on same scenario. Can you please share that how do you fixed this issue ?

**Comment by ycjcl868** [comment]
+1

**Comment by jameskip** [comment]
I'm having a similar issue. I would like to cycle through a list then `goBack` click another link and cycle through that list as well. However, it is losing the handle when I navigate back.

```javascript
for (let i = 0; i < categories.length; i++) {
    it(`should display categories: ${categories[i]}`, async (done) => {
      await page.goto(`${environment.production}/categories/${categories[i]}`)
      const cards = await page.$$('a')

      for (const card of cards) {
        await card.click()
        await page.waitForNavigation()
        await page.goBack()
        await page.waitForNavigation()
      }

      done()
    })
  }
```
