### ISSUE TITLE
Problem with escaping quotes in style attributes

### ISSUE THREAD

**Issue by sethwilsonUS** [puppeteer/puppeteer#4157]
I'm attempting to read a local HTML file with Puppeteer, perform some operations on it, and then output the new version. Everything's working fine, except quotes are being handled strangely in `style` attributes. Specifically, single quotes are converted to double quotes (throughout the document, which is fine), but in the `style` attributes existing double quotes are then escaped as `&quot;`.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Mac OSX Mojave
* URLs (if applicable): N/A
* Node.js version: 11.11.0

**What steps will reproduce the problem?**

```
async function fixHTML(filePath) {

  const browser = await puppeteer.launch({
    'args': [ '--disable-web-security' ]
  });

  const page = await browser.newPage();
  const contentHtml = fs.readFileSync(filePath, {encoding: 'utf8'});
  await page.setContent(contentHtml);

  const result = await page.evaluate(async threshold => {
  . . .
  }

  fixedHTML = await page.content();
  fs.writeFileSync(`${fileDir}/${fileBase}.fixed.html`, fixedHTML, {encoding: 'utf8'});
}
```

**What is the expected result?**

Style attributes in my original HTML look like this:

`style='font-size:11.0pt;font-family:"Arial",sans-serif;color:#D99594'`

**What happens instead?**

But in my output they're rendered as:

`style="font-size:11.0pt;font-family:&quot;Arial&quot;,sans-serif;color:#D99594"`

Suggestions? Thank you!

**Comment by vsemozhetbyt** [comment]
This behavior seems valid. If you add `style='font-size:11.0pt;font-family:"Arial",sans-serif;color:#D99594'` to an element in the DevTools DOM tree tab and then copy outerHTML via menu, you wil get `&quot;Arial&quot;` as well.

**Comment by aslushnikov** [comment]
@sethwilsonUS in fact, that's what WebPlatform's element.outerHTML returns with such a style. Where do you get this HTML from?
