### ISSUE TITLE
setExtraHTTPHeaders remains after going to other pages?

### ISSUE THREAD

**Issue by TomasKavaliauskas** [puppeteer/puppeteer#4161]
I have a general question, couldn't find the answer to it in the docs.

If I create a new page:

`page = await browser.newPage();`

and then set headers with:

`await page.setExtraHTTPHeaders();`

then I go to some website:

`await page.goto('http://google.com');`

I guess HTTP headers then are sent with the request, but what after going to google.com I want then go to some other website:

`await page.goto('otherwebsite.com');`

Do I need to call:

`await page.setExtraHTTPHeaders();`

again before calling goto() ? Or do I need to call await page.setExtraHTTPHeaders(); only once and it will remain the same no matter how many times I change page?

Thanks.

**Comment by vsemozhetbyt** [comment]
I think this doc fragment means you need to call just once:

> The extra HTTP headers will be sent **with every request** the page initiates.

Quick test:

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.setExtraHTTPHeaders({ 'foo': 'bar' })

    console.log((await page.goto('https://example.org/')).request().headers().foo);
    console.log((await page.goto('https://example.com/')).request().headers().foo);
    console.log((await page.goto('https://example.net/')).request().headers().foo);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Output:
```
bar
bar
bar
```
