### ISSUE TITLE
Failed to launch chrome (Could not bind NETLINK socket)

### ISSUE THREAD

**Issue by donhcd** [puppeteer/puppeteer#4164]
### Steps to reproduce

Google Cloud Functions (runtime nodejs8)

* Puppeteer version: 1.12.2
* Platform / OS version: Google Cloud Functions (HTTP)
* URLs (if applicable):
* Node.js version: nodejs8

**What steps will reproduce the problem?**

This error seems to happen nondeterministically, but I think this is the code snippet that is triggering the error:

```
    const browser = await puppeteer.launch({
      headless: true,
      defaultViewport: { width: 1600, height: 6211 },
      // --no-sandbox is required when running in cloud functions
      args: ['--no-sandbox']
    });
    page = await browser.newPage();
```

**What is the expected result?**
no errors

**What happens instead?**

I get this error:
```
Error: Failed to launch chrome! [0314/100013.398590:ERROR:address_tracker_linux.cc(177)] Could not bind NETLINK socket: Permission denied (13) shared memfd open() failed: Function not implemented Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed! TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md at onClose (/srv/node_modules/puppeteer/lib/Launcher.js:360:14) at ChildProcess.helper.addEventListener (/srv/node_modules/puppeteer/lib/Launcher.js:350:60) at emitTwo (events.js:131:20) at ChildProcess.emit (events.js:214:7) at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by aslushnikov** [comment]
@donhcd can you please file this [upstream](https://cloud.google.com/support/docs/issue-trackers) to GCF? 

(cc @steren)

**Comment by JaapWeijland** [comment]
I have this issue as well!

`
Error: Failed to launch chrome!
[0107/170046.897062:ERROR:address_tracker_linux.cc(171)] Could not bind NETLINK socket: Permission denied (13)
[0107/170046.898940:ERROR:file_path_watcher_linux.cc(71)] Failed to read /proc/sys/fs/inotify/max_user_watches
Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
`

**Comment by leoplct** [comment]
+1

**Comment by ricardograca** [comment]
Was this ever filed upstream as mentioned?

Does anyone know if there is a workaround until a fix is ready?
