### ISSUE TITLE
page.sources()?

### ISSUE THREAD

**Issue by rcarmo** [puppeteer/puppeteer#417]
I'm trying to obtain a list of all the assets/URLs a page has loaded (or not). In essence, I'm looking for the equivalent of the "Sources" view in Chrome Inspector, which might be represented (naïvely) with a URI key pointing to a Response() object.

Should I grab the 'requestfinished'/'requestfailed' events and build by own convenience function to assemble that list, or is this something you might consider adding to the API?

**Comment by vsemozhetbyt** [comment]
Maybe [this example](https://github.com/GoogleChrome/puppeteer/blob/master/examples/block-images.js) can help?

**Comment by vsemozhetbyt** [comment]
Something like:
```js
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterceptionEnabled(true);

  const URLs = new Set();

  page.on('request', request => {
    URLs.add(request.url);
    request.continue();
  });
  await page.goto('https://github.com/GoogleChrome/puppeteer');

  console.log([...URLs].join('\n'));

  browser.close();
})();
```

**Comment by vsemozhetbyt** [comment]
But API would also be helpful.

**Comment by rcarmo** [comment]
@vsemozhetbyt yeah, that's what I am doing, of sorts. I'm also interested in the responses, for testing purposes.

**Comment by benjamingr** [comment]
@vsemozhetbyt you can use the performance timing API:

```js
await page.evaluate(`performance.getEntries()`);
```

**Comment by rcarmo** [comment]
@benjamingr the timing API does not yield URIs or response codes, which makes it unsuitable for my purposes.

**Comment by vsemozhetbyt** [comment]
@benjamingr I was trying this
```js
  await page.goto('https://github.com/GoogleChrome/puppeteer',
                  {waitUntil: 'networkidle'});

  const URLs =
    (await page.evaluate('performance.getEntries()'))
    .filter(entry => entry.entryType === 'resource')
    .map(entry => entry.name)
    .sort()
    .join('\n');
```
but I get empty string.
This code:
```js
(await page.evaluate('performance.getEntries()')).map(entry => Reflect.ownKeys(entry))
```
gives this:
```js
[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ]
```
Why does puppeteer return empty objects for `PerformanceEntry`s?

**Comment by vsemozhetbyt** [comment]
@rcarmo `PerformanceEntrys` has URI in `name` key.

**Comment by ebidel** [comment]
@vsemozhetbyt That's because `PerformanceResourcesTiming` is not JSON serializable. If you do the filtering in the page, it'll work:

```js
 const urls = await page.evaluate(() => {
    return performance.getEntries()
        .filter(e => e.entryType === 'resource')
        .map(e => e.name);
  });
```

Related: https://github.com/GoogleChrome/puppeteer/issues/310
Fix: https://github.com/GoogleChrome/puppeteer/issues/382

**Comment by rcarmo** [comment]
@vsemozhetbyt well, it actually depends on the timing entry (there are navigation and resource entries), but the resource entries do not have result codes, or any of the response headers, which I need (Chrome 60):

```javascript
JSON.stringify(performance.getEntries()[1], null, '  ')
"{
  "name": "https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,500italic,700,700italic|Roboto+Mono:400,500,700|Material+Icons",
  "entryType": "resource",
  "startTime": 1108.065,
  "duration": 411.69500000000016,
  "initiatorType": "link",
  "workerStart": 0,
  "redirectStart": 0,
  "redirectEnd": 0,
  "fetchStart": 1108.065,
  "domainLookupStart": 1147.17,
  "domainLookupEnd": 1386.68,
  "connectStart": 1386.68,
  "connectEnd": 1447.3700000000001,
  "secureConnectionStart": 1402.155,
  "requestStart": 1447.8500000000001,
  "responseStart": 1504.685,
  "responseEnd": 1519.7600000000002,
  "transferSize": 982,
  "encodedBodySize": 747,
  "decodedBodySize": 3074
}"
```

It does tell me if it was a redirect (which is also useful for testing certain scenarios), but the approach of passing that on to `page.evaluate()` also means that something on the page can itself call `clearResourceTimings()` - I'd rather have something that cannot be broken by third-party scripts.

**Comment by pavelfeldman** [comment]
> Should I grab the 'requestfinished'/'requestfailed' events and build by own convenience function to assemble that list, or is this something you might consider adding to the API?

@rcarmo You should listen to these events and build a convenience function, it should be very straightforward. You could also just listen to the `response` and it might have all the information you need.

@vsemozhetbyt `await page.setRequestInterceptionEnabled(true);` was not necessary in your snippet. In fact it is slowing down page load significantly - browser goes to puppeteer for every request it intends to issue.
