### ISSUE TITLE
Ajax/Css etc content with relative links

### ISSUE THREAD

**Issue by zabakala** [puppeteer/puppeteer#4172]
Hi. I would like a push in the right direction. I have an express app running on port say **3002** This app runs _goto_ on www.example.com. The resultant page content is saved into a string. Whenever I try to use this string to display as a page, all relative links (css, xhr...) are resolved to a wrong destination, ie. **www.example.com:3002/api/foo** instead of **www.example.com/api/foo**. How could it be resolved to a proper destination?

**Comment by vsemozhetbyt** [comment]
Can adding the [`base`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element to the `head` help with this?

**Comment by aslushnikov** [comment]
Closing this since the question doesn't have anything to do with Puppeteer.
