### ISSUE TITLE
Error net::ERR_NAME_NOT_RESOLVED is being thrown while trying to redirect to the mailgun generated URL

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4173]
### Steps to reproduce
**Tell us about your environment:**
* Puppeteer version: 1.12.2
* Platform / OS version: macOS
* Node.js version: v11.10.0

**What steps will reproduce the problem?**
1. Write a simple script that would try to navigate (`page.goto()`) to given URL:
```
http://email.mailgun.internal.company.path.systems=/c/eJx9ULtuhDAQ_BrosPATXFAQOCSUe0SXNKmQMQacnA0BU9zfx0gXRWkibbMzs7O702WE4jbU=GYohjzFMIEeIJgACRg9JjipYwooVJU8DEhuhb8NmwerEoO0ArJjB56I67ZQcwXpfnTJrOGa4TXq=EcUoYFD3jfUtFJ3sosGxjnioZ3rLRuXkNcB6gytfDMJrFfQNmsqqbwHzzhLJuuQe4kpPt9WKE05=MNcMkTxiiMk05CGgvIBEwZSkmPUEwgkX2A2OZMI4WZhR72ieMlf2kOp7w-NsXlXNXXU_5WX87N8=3vxI56s8-u89u2an1_zYufz44M1_svNeFLtITzAddoWqTyohQ2X7GMafTZGuxF8iQA9wYTRPbbf=iORkQpf98ff9P7eFRq2rGFRdZgFCXFKCqJIRTRmOSJqiiLdtHEkuGel6KRJIvewbJv6QAg
```
2. Execute the script

**What is the expected result?**
Puppeteer should navigate to the given URL without throwing errors

**What happens instead?**
An exception 
```
Error: net::ERR_NAME_NOT_RESOLVED at http://email.mailgun.internal.company.path.systems=/c/eJx9ULtuhDAQ_BrosPATXFAQOCSUe0SXNKmQMQacnA0BU9zfx0gXRWkibbMzs7O702WE4jbU=GYohjzFMIEeIJgACRg9JjipYwooVJU8DEhuhb8NmwerEoO0ArJjB56I67ZQcwXpfnTJrOGa4TXq=EcUoYFD3jfUtFJ3sosGxjnioZ3rLRuXkNcB6gytfDMJrFfQNmsqqbwHzzhLJuuQe4kpPt9WKE05=MNcMkTxiiMk05CGgvIBEwZSkmPUEwgkX2A2OZMI4WZhR72ieMlf2kOp7w-NsXlXNXXU_5WX87N8=3vxI56s8-u89u2an1_zYufz44M1_svNeFLtITzAddoWqTyohQ2X7GMafTZGuxF8iQA9wYTRPbbf=iORkQpf98ff9P7eFRq2rGFRdZgFCXFKCqJIRTRmOSJqiiLdtHEkuGel6KRJIvewbJv6QAg
```
is being thrown.

**Comment by vsemozhetbyt** [comment]
I cannot open this URL in a simple Chrome.

**Comment by ghost** [comment]
@vsemozhetbyt it's true that Chrome by default tries to search the given URL instead to redirect to. But when you paste it to searching bar, you will see there are two options:
![](https://i.imgur.com/nJv5wos.png)
And the second one is the redirecting, visiting the page.

I can assure you that in my code I'm trying to navigate to a valid, not corrupted link. Of course for reporting bug purposes I modified given URL.
