### ISSUE TITLE
Font width is different when printing using Desktop Chrome UI vs puppeteer

### ISSUE THREAD

**Issue by boris-ananyevsky** [puppeteer/puppeteer#4177]
### Steps to reproduce
**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: Ubuntu 18.04.1 LTS
* URLs (if applicable): ...
* Node.js version: 8.11.3
* Manual print Chrome version: 73.0.3683.75

**What steps will reproduce the problem?**

1. Open HTML listed below in Chrome UI and print it manually (print options: Letter, no margins, portrait, scale: 100, background graphics enabled)
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
    <title></title>
    <style>
        body {
            font-family: 'Roboto Mono', monospace;
            margin: 10px 0 0 0;
        }

        text {
            position: absolute;
            top: 10px;
        }

        .verticalLine {
            border-left: thick solid red;
            position: absolute;
            left: 748px;
            top: 10px;
            height: 30px;
        }

        .note {
            color: red;
            font-size: 14px;
            position: absolute;
            left: 625px;
            top: 40px;
        }
    </style>
</head>

<body>

<div class="text">abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz</div>
<div class="verticalLine"></div>
<div class="note">text should stop here</div>

</body>

</html>
```
2. Print the same HTML file using puppeteer:
```javascript
const puppeteer = require('puppeteer');
const fs = require('fs');

(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    const html = fs.readFileSync('./test.html').toString();
    await page.setContent(html, {waitUntil: 'networkidle0'});

    const pdfBuffer = await page.pdf({
        printBackground: true,
        format: 'Letter',
    });

    await browser.close();

    const fd = fs.openSync(process.argv[2] || "./result.pdf", 'w+');
    fs.writeSync(fd, pdfBuffer);
})();
```
3. Compare resulting PDF files

**What is the expected result?**

Files should look identical

**What happens instead?**

Fonts in PDF generated using puppeteer are wider. Results may vary depending on which font you use. With some fonts text is wider, with others narrower.

*Chrome UI result:*

![chrome-ui-print](https://user-images.githubusercontent.com/35644642/54533905-f1f69500-4993-11e9-9959-a37c7e273033.png)

*puppeteer result:*

![puppeteer-print](https://user-images.githubusercontent.com/35644642/54533935-fd49c080-4993-11e9-8e8b-f3c55721a6d1.png)

[chrome-ui-print.pdf](https://github.com/GoogleChrome/puppeteer/files/2978365/chrome-ui-print.pdf)
[puppeteer-print.pdf](https://github.com/GoogleChrome/puppeteer/files/2978366/puppeteer-print.pdf)

---

- When running on Windows 10 it works as expected
- When I convert to PDF using AWS Lambda I get same results as on Ubuntu (font width is different from manual print)
- You can clone and run this project to reproduce the issue - https://github.com/boris-ananyevsky/puppeteer-convert-to-pdf-test.git
- If it matters I run Ubuntu under VirtualBox - Windows 10 host, Ubuntu guest

**Comment by ksyke** [comment]
+1 I'm having the same issue, have you found a workaround / fix for this? @boris-ananyevsky

**Comment by boris-ananyevsky** [comment]
@ksyke I've tried to launch Chrome with different flags - same result. It works well on Windows though, if it's an option for you. Unfortunately I have to run it on AWS Lambda, which uses Linux.

**Comment by ljacho** [comment]
In my case even font height is different - despite that, I set font-size and line-height in CSS.

**Comment by ksyke** [comment]
> @ksyke I've tried to launch Chrome with different flags - same result. It works well on Windows though, if it's an option for you. Unfortunately I have to run it on AWS Lambda, which uses Linux.

@boris-ananyevsky yea I'm also having the same problem, im running it on AWS Lambda. Can't really find a better alternative at the moment

**Comment by aslushnikov** [comment]
@boris-ananyevsky @ksyke @ladislavjacho  Do I understand correctly that PDFs are different when printed locally on Windows and when generated with AWS Lambda?

If this is the case, than this is because font stack resolution works very differently on different operating systems. The only way to get reliably consistent results is to run Puppeteer inside the same Docker image.

**Comment by ksyke** [comment]
@aslushnikov On my case I'm rendering a canvas. Yes I agree that some fonts are rendered differently on different OS based on my outputs which uses multiple fonts per canvas. My fix however isn't related to puppeteer, I tweaked my JS code on the page itself for it to work and output an acceptable render.

**Comment by ljacho** [comment]
@boris-ananyevsky in my case, it was related to particular font and I am running puppeteer on Mojave - can't confirm or exclude a dependency

**Comment by aslushnikov** [comment]
I'm still not sure if there's a bug here. Let me re-iterate.

There are 3 components that define font rendering:
- operating system & host environment
- browser version
- HTML content

Now, there are two options:

1. if any of these three change, there's no guarantee that font rendering will be the same. In other words, you shouldn't expect PDFs to be the same on your local machine and on AWS Lambda.
2. However, if you don't change OS, Browser or content, every subsequent rendering should result in the same font resolution. If this does not happen - **this is a bug**.

So what is this issue about? Is this (1) or (2)?

**Comment by aslushnikov** [comment]
Ah, I re-read the original description.

@boris-ananyevsky: you should pass the `'--font-render-hinting=medium'` flag to Chromium to have consistent rendering between headless and headful.

This is actually a dupe of https://github.com/GoogleChrome/puppeteer/issues/2410
