### ISSUE TITLE
Yet another Windows Puppeteer Installation Issue

### ISSUE THREAD

**Issue by kjackey1** [puppeteer/puppeteer#4184]
### Steps to reproduce:

Attempt to execute npm i puppeteer-core from Windows Administrator Command Window

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Windows Server 2016
* Node.js version: 10.15.3

**What steps will reproduce the problem?**
Attempt to execute npm i puppeteer-core from Windows Administrator Command Window

**What is the expected result?**
Puppeteer installs correctly without installing chromium

**What happens instead?**
Get the following:
C:\Users\Administrator>npm i puppeteer-core
'CALL "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" -g' is not recognized as an internal or external command,
operable program or batch file.

> puppeteer-core@1.13.0 install C:\Users\Administrator\node_modules\puppeteer-core
> node install.js

npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No license field.

npm ERR! file C:\Windows\system32\cmd.exe;E:\chromedriver_win32\chromedriver.exe
npm ERR! path C:\Windows\system32\cmd.exe;E:\chromedriver_win32\chromedriver.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;E:\chromedriver_win32\chromedriver.exe
npm ERR! puppeteer-core@1.13.0 install: `node install.js`
npm ERR! spawn C:\Windows\system32\cmd.exe;E:\chromedriver_win32\chromedriver.exe ENOENT
npm ERR!
npm ERR! Failed at the puppeteer-core@1.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-03-19T17_18_32_401Z-debug.log

**Comment by aslushnikov** [comment]
@kjackey1 this has nothing to do with Puppeteer, your terminal doesn't recognize node.js installation.

Quick googling gave me [this promising link](https://stackoverflow.com/questions/23412938/node-is-not-recognized-as-an-internal-or-an-external-command-operable-program) - please check it out.
