### ISSUE TITLE
WaitForSelector and waitForXpath timesout inside iframe

### ISSUE THREAD

**Issue by mayankchincholkar** [puppeteer/puppeteer#4186]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13 puppeteer-core
* Platform / OS version: Windows10
* URLs (if applicable):
* Node.js version: 10.14

**What steps will reproduce the problem?**

The iframe do not have any name so I find it using
page.mainFrame().childFrames().find(frame => frame.name() === '')
 When  I try to type inside the element in iframe, I do

frame.type('#selector',string) and this works
When I try to wait for the xpath/selector inside the iframe for the same selector it timeout
await frame.waitForSelector('#selector');

I tried putting in options {visible:true,timeout:10000} but no luck.

**Comment by aslushnikov** [comment]
@mayankchincholkar can you give us a script so that we can run it locally and see what's going on?

**Comment by mayankchincholkar** [comment]
Hey @aslushnikov 

I tried this using below script and it seems to work. 

const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();

    await page.setContent(
        '<a href="whatever.."><iframe src="https://www.google.com/maps/embed/v1/place?q=TEST&zoom=12&key=" height="1200px" width="1200px"></iframe></a>');
    const frame = await page.mainFrame().childFrames().find(frame => frame.name() === '');
    await frame.waitForXPath('//*[@id="mapDiv"]/div/div/div[9]/div/div/div/div[1]/div[1]');
    await browser.close();
})();

However, the exact same thing doesn't seem to work on the application I am working on in my organisation.

The only difference is the iframe opens as a pop up when clicked on a button instead of the same page. Also, when I do 
const frame=page.mainFrame().childFrames().find(frame => frame.name() === '');
frame.url(); // gives null and _url is not set

Any help will be appreciated. 
Is there any other way which I can use to wait for an element to be ready on screen.
Like waitForFunction and use Page.eval to get document object to find the element.

I tried also dumping the HTML using below command of the frame and can see the dom with elements I am waiting for using waitForSelector/waitForXPath, but still, the command is timing out.

const frame=page.mainFrame().childFrames().find(frame => frame.name() === '')
let bodyHTML = await frame.evaluate(() => document.body.innerHTML);

Can you please suggest some troubleshooting steps?

Thanks
Mayank

**Comment by divyamvn** [comment]
Same thing is happening for me too.

```
const frame = page.frames();
await frame[0].$( selector ); //THIS WORKS
await frame[0].waitForSelector(selector); //THIS TIMES OUT
```

**Comment by turegit** [comment]
Me too.

await frame.waitForSelector('[ng-controller="CopySetupCtrl"]', {visible: true});  // THIS TIMES OUT
await frame.$('[ng-controller="CopySetupCtrl"]', {visible: true});  // THIS WORKS

My frame is a bit unusual because the name is a big JSON string.  form.name() does not work either, not sure if that's related.  form.name() returns ''.  I am finding my form w/ form.url(), which works.

node v10.17.0
puppeteer v2.0.0

**Comment by ryan9018** [comment]
I am also experiencing this issue. Has there been any updates on this?

**Comment by srashevskyi** [comment]
also experiencing this

Used this instead 
`await page.$( iFrameSelector )`

**Comment by lolyinseo** [comment]
The same. Looks like nothing changed

**Comment by clouedoc** [comment]
I found this recently: https://stackoverflow.com/a/59999976/4564097

Not tested, I'm still searching for a cleaner option.

EDIT: `--disable-features=site-per-process`.
