### ISSUE TITLE
Is it possible to connect to remote webdriver by Selenium session id?

### ISSUE THREAD

**Issue by VicGrygorchyk** [puppeteer/puppeteer#4188]
Hello.
Is is possible to connect  `puppeteer` instance to the running remote chrome driver via session id? This `session id` is just session for `Selenium`, is it possible to fetch any data for `puppeteer` connect() function?
It might be a feature request, but I would appreciate if it's already available in `puppeteer`. 
I am aware, that `puppeteer` can connect to already running browser via websocket.

##When it can be useful?
When you use Selenium Grid / Selenoid or any other so called "Selenium" load balancer with nodes / containers, you might have a case, when your code is running on one machine and your code has remote connection to the load balancer, which redirects your request to the specific node with running chrome driver on it.
In such case, it's impossible to connect via websocket (paraphrasing it, its 'quite hard).

**Comment by aslushnikov** [comment]
> Hello. Is is possible to connect puppeteer instance to the running remote chrome driver via session id?

@VicGrygorchyk No, I don't think it's possible (unless it somehow suddently works accidentally - but I doubt it).

> In such case, it's impossible to connect via websocket (paraphrasing it, its 'quite hard).

Why is it impossible / hard? There's a [browserless.io](https://www.browserless.io) that gives you many browsers available to connect with websocket. Seems to be very doable to me.
