### ISSUE TITLE
puppeteer's click event different from mouseEvent on browser ？

### ISSUE THREAD

**Issue by OhShin2009** [puppeteer/puppeteer#4190]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.13.0
* Platform / OS version:Windows10
* URLs (if applicable): https://trade.mql5.com/trade?callback&amp;switch_platform=1&amp;border=0&amp;startup_version=5&amp;demo_all_servers=1&amp;user_token=0&amp;startup_mode=create_demo
* Node.js version:v 10.15.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.accrss URL ,run mouse.click(x,y) by puppeteer and set headless: false make a breakpoint when click mouse.
2.access URL ,make breakpoint  when click the mouse.
3.  step 2,resolve event in core.js first. but step 1 resolve mouseEvent  in mt4.zh.js first.

i have no idea why it is happened.

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
@syg-ohshin I don't follow - what's a "set a breakpoint"? What do I do to reproduce the problem?

**Comment by OhShin2009** [comment]
@aslushnikov Use developer Tool and add Event Listen Breakpoints with mouse click listener.
mouse.click(x,y) 's click event if different from real click in this page https://trade.mql5.com/trade?callback&amp;switch_platform=1&amp;border=0&amp;startup_version=5&amp;demo_all_servers=1&amp;user_token=0&amp;startup_mode=create_demo
