### ISSUE TITLE
Copy paste large text to text area

### ISSUE THREAD

**Issue by laksh1010** [puppeteer/puppeteer#4192]
as an exmaple lets say there is a text that has 1000+ lines that i need to set it a text area. even typing (page.type / page.keyboard.type etc) without any delay, takes considerable time to finish it.

is there anyway to simply set the text instantly (as we normally do copy and paste etc) to the textareas using the selector or similar, rather than page.type / page.keyboard.type function.

any solutions?

**Comment by laksh1010** [comment]
found possible solution.

> async function setSelectVal(sel, val) {
    page.evaluate((data) => {
        return document.querySelector(data.sel).value = data.val
    }, {sel, val})
}

`await setSelectVal('#select_id', 'newValue')`

**Comment by valoricDe** [comment]
Thx for sharing 👍
