### ISSUE TITLE
page.waitForNavigation always results in timeout

### ISSUE THREAD

**Issue by mehdyh** [puppeteer/puppeteer#4195]
* Puppeteer version: 1.13.0 and older
* Platform / OS version: CentOS 7 and Windows 
* URLs (if applicable):
* Node.js version: 10.15.3

`async function TestBrowser(req, resp) {
    const browser = await puppeteer.launch({
        headless: true,
        args: [
            '--disable-accelerated-2d-canvas',
            '--disable-gpu',
            '--window-size=1920x1080'
        ]
    });
    const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();    
    await page.goto("https://api.ipify.org/")
    waitforNav = page.waitForNavigation({ waitUntil: 'networkidle0' ,timeout: 10000});
    var html = await page.evaluate(() => document && document.body && document.body.innerHTML);
    await browser.close();
    return resp.send(html)    
}`

above snippent always results in timeout.
however if I use
` const waitforNav = page.waitForNavigation({ waitUntil: 'networkidle0' ,timeout: 5000});
    await page.goto("https://api.ipify.org/");
    await waitforNav;` 
it works!

**Comment by Lumen27** [comment]
You forgot to await the `waitforNav` and forgot `const` before it.
So you want `const waitforNav = await page.waitForNavigation({ waitUntil: 'networkidle0' ,timeout: 5000});`
