### ISSUE TITLE
How do you grab content from a site that takes a while to load with ajax?

### ISSUE THREAD

**Issue by majestique** [puppeteer/puppeteer#4198]
For example, there are sites with load times that can vary greatly,  like: https://cportal.lendingqb.com/Onlineapp2/GetRate.aspx?siteid=9f4ab128-33f9-4d14-9b11-18c96aef1fb3&sLPurposeT=0&aOccT=0&sProdSpT=0&sLAmtCalc=400000&sPurchPrice=300000&sSpZip=92708&sSpState=CA&sSpCounty=Orange&sProdImpound=1&sRLckdDays=45&sCreditScoreType1=760

Will something like Pending XHR https://github.com/jtassin/pending-xhr-puppeteer work with this? Or is there another method that's already built in without specifying certain tags to be loaded? Is there a method where Puppeteer will wait for everything to load?

**Comment by vsemozhetbyt** [comment]
You can try [`page.goto(url, { waitUntil: 'networkidle0' });`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options)
