### ISSUE TITLE
How to disable Chromium PDF 

### ISSUE THREAD

**Issue by TomasKavaliauskas** [puppeteer/puppeteer#4199]
According to https://amiunique.org/fp

Puppeteer uses plugins:
Chromium PDF Viewer
Chromium PDF Plugin

I do not need these anyway, is there any way to disable them? So it wont affect browser fingerprint? I was looking for extensions directory in node_modules but couldn't find any.

![LeakReport](https://user-images.githubusercontent.com/13218137/54865998-6146fd00-4d77-11e9-8c47-36f6ebf5b389.jpg)

**Comment by aslushnikov** [comment]
@dudeperfect95 This is a question worth asking on [chromium-dev](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev) google group. You might be able to compile without them, or maybe there are some other tricks.
