### ISSUE TITLE
Can I go to a url of the a site after I logged in? 

### ISSUE THREAD

**Issue by astronomyf** [puppeteer/puppeteer#4201]
I'm scraping a site which requires login and then, to get certain values, I have to click on many different buttons that goes to specific pages. Can I go to a new url without loosing the login session?

**Comment by maicss** [comment]
you should read about what is `cookie`, `session` and `localstorage`, to know why a web knows you is you.

to your problem, you should not worried about this, the web server or your browser remember you have logged in, and keep the session.

just do not create another `browser` instance after logged is, create `page` instance.

**Comment by xse** [comment]
I think by default puppeteer starts up a completely new browser each time you launch it, you can save sessions and so on by setting `--user-data-dir=`
Be aware that if the session has a timer it'll end at one point and you'll have to log again, what i usually do is i look for an element that is there only when i have to log in and from there i either do things or login and do things.

**Comment by aslushnikov** [comment]
> Can I go to a new url without loosing the login session?

You can - you should re-use the `userDataDir` to stay logged in.
