### ISSUE TITLE
page.evaluate get the undefined variable

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4202]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.12.2
* Platform / OS version:macOS Mojave
* URLs (if applicable):
* Node.js version:v11.10.1

**What steps will reproduce the problem?**
_Please include code that reproduces the issue._
I write a common function to click buttons. 
```
async function clickButton(number){
    await page.evaluate(() => document.querySelector(`tbody>tr:nth-child(${number})>[data-name="select"]>div>input`).click()); //not work
   // await page.$eval(`tbody>tr:nth-child(${number})>[data-name="select"]>div>input`,el => el.click());//work
}
```

**What is the expected result?**
they all work

**What happens instead?**
when I call this function : 
- page.evaluate doesn't work,The error is : `Evaluation failed: ReferenceError: number is not defined`.
- page.$eval works.
- if I replace it with below code, it also works.
```
async function clickButton(number){
    await page.evaluate((num) => document.querySelector(`tbody>tr:nth-child(${num})>[data-name="select"]>div>input`).click(),number);
}
```
**I just want to know why page.evaluate can't get the variable `number`，but page.$eval can get it. Is it because of SCOPE? I can't understand this situation.
Thanks!**

**Comment by vsemozhetbyt** [comment]
With `page.evaluate()`, puppeteer sends function code to the browser as a string and browser compiles it and execute in the browser context, without access to the puppeteer context, so you need to transfer the argument `number` explicitly.

`page.$eval()` creates its argument in the puppeteer context with access to the `number` variable.

**Comment by ghost** [comment]
@vsemozhetbyt thank you very much for your reply!!
