### ISSUE TITLE
Can we add PUPPETEER_SKIP_CHROMIUM_DOWNLOAD for Firefox install.js

### ISSUE THREAD

**Issue by muthukumarse** [puppeteer/puppeteer#4206]
We have a project where we keep the puppeteer available to extracted by developer due to proxy restriction. 

So we do set `npm config set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true` 

now we added firefox too, but Firefox doesn't respect that variable. I checked install.js doesn't have step to skip download. can we add that?

Can I send PR?

**Comment by justnpT** [comment]
or should firefox puppeteer be a separate npm lib 

because puppeteer is chromium-related product by default,
making it firefox or chrome is extending its functionality

this request might be related to high-level business decision of puppeteer product owners

**Comment by aslushnikov** [comment]
> or should firefox puppeteer be a separate npm lib

It is a separate NPM lib.

> now we added firefox too, but Firefox doesn't respect that variable.

ATM puppeteer-firefox puts a specific set of preferences next to Firefox executable once it downloads it - which makes it more complicated to run with a custom `executablePath`. We might need to discuss this with folks from Mozilla - maybe they'll be open to add a flag that loads preferences from a custom place.

**Comment by aslushnikov** [comment]
I'll close this for now. We might have a `puppeteer-firefox-core` some time later instead of the env variable -should be enough for all the usecases.
