### ISSUE TITLE
Puppeteer Doesn't Render Javascript Pages From External Resources (Works only for localhost URLs)

### ISSUE THREAD

**Issue by PHPBeginnerStudent** [puppeteer/puppeteer#4209]
Hi Team!

I am trying to configure puppeteer to render SPA sites. 
I am using Puppeteer for this purpose and when I provide any external URL (not localhost pages), Puppeteer fetches only the source code of the URL, without rendering the entire DOM.
When I try to SSR any localhost URL (a page generated by the same node js server on my local host) Javascript page all works fine. 

Please advise whether I am missing something or I need to try another approach.

**Comment by vsemozhetbyt** [comment]
[This answer](https://stackoverflow.com/a/55362495/2625560) seems to mention most usual suspects of the issue.
