### ISSUE TITLE
load-images option

### ISSUE THREAD

**Issue by rodrigogs** [puppeteer/puppeteer#421]
I couldn't find a PhantomJS `load-images` relative option for puppeteer. Is there a way to say you don't want to load images?

**Comment by ebidel** [comment]
Can you elaborate on what "`load-images` relative option" is?

The [block-images.js example](https://github.com/GoogleChrome/puppeteer/blob/master/examples/block-images.js) shows how to interception image requests. You can either modify or abort them. Does that help?

**Comment by rodrigogs** [comment]
It helps. Thanks!
