### ISSUE TITLE
How to correctly screenshot this type of website

### ISSUE THREAD

**Issue by Rana-xD** [puppeteer/puppeteer#4211]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Mac
* URLs (if applicable): https://www.jackall.co.jp/rooster/
* Node.js version: v10.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. I write normal screenshot function to screenshot the webpage. For static website, It worked perfectly fine. But, when I try to screenshot this website ( https://www.jackall.co.jp/rooster/), it didn't screenshot correctly. How to deal with this kind of website? 

Here are the code : 
`let browser = await puppeteer.launch({executablePath: process.env.EXECUTABLE_PATH});`
            `let page = await browser.newPage();`
            `const override = Object.assign(page.viewport(), {width: width});`
           ` if(isAuthenticated){`
                `await page.authenticate({username:body.authentication.username, password:body.authentication.password});`
            `}`
            `await page.goto(url, {waitUntil: 'load',timeout: 0});`
            `await page.setViewport(override);`
            `await page.screenshot({ path: `./${fileName}`,fullPage: true });`
            `await page.close();`
            `await browser.close();`

**What is the expected result?**

https://pu-ai-bc-ruby.s3.ap-southeast-1.amazonaws.com/designs/jackallrgm%5Btest%5D-00250/04ec906b1eaf12ead6b8ac961bd0b5fc/1360/41a55f7a5dcd6ca5c928749997999bab26feb82c5cfac774.png

**What happens instead?**
https://pu-ai-bc-ruby.s3.ap-southeast-1.amazonaws.com/screenshots/a003eac153b830c35895df406c60169a/04ec906b1eaf12ead6b8ac961bd0b5fc/1360/103a21e452f05c2f39080967a95.png

**Comment by jsoverson** [comment]
This happens because Puppeteer overrides the device metrics to be the height of the scrollable content but the site was not built to handle that. You can see the effect (which is similar to your result) by emulating a device in devtools and setting the height to the maximum (9999).

<details>

![Screen Shot 2019-03-27 at 3 22 31 PM](https://user-images.githubusercontent.com/842798/55106040-5906fe80-50a4-11e9-87dd-a0061cbfb557.png)

</details>

If [Page.js:892](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L892) is commented out then the following script produces something better.

<details>

```js
const puppeteer = require('puppeteer');

(async function(){
  let browser = await puppeteer.launch({headless:false, defaultViewport:null});
  let page = await browser.newPage();
  await page.goto('https://www.jackall.co.jp/rooster/');
  await page.evaluate(_ => {
    while (document.body.scrollHeight < (window.scrollY + window.innerHeight)) {
      window.scrollBy(0, window.innerHeight);
    }
  });
  await page.screenshot({ path: 'issue-4211.png', fullPage: true });
  await browser.close();
}())
```

![issue-4211](https://user-images.githubusercontent.com/842798/55106270-e6e2e980-50a4-11e9-9f3d-80886349f56c.jpg)

</details>

It's not uncommon to see sites break at extreme aspect ratios so the emulation should probably be an option that can be disabled.

**Comment by Rana-xD** [comment]
@jsoverson Thank you for you help. For clarification, I need to comment this code
`await this._client.send('Emulation.setDeviceMetricsOverride', { mobile: isMobile, width, height, deviceScaleFactor, screenOrientation });` in `node_modules/puppeteer/lib/Page.js ` first 
before I can try your script, right?

**Comment by Rana-xD** [comment]
@jsoverson Are there any other ways to do that one beside commenting that code `await this._client.send('Emulation.setDeviceMetricsOverride', { mobile: isMobile, width, height, deviceScaleFactor, screenOrientation });` .

**Comment by jsoverson** [comment]
It looks like you can get the same effect without worrying about that line by manually setting the clip dimensions to the size of the content:

```js
const puppeteer = require('puppeteer');

(async function(){
  let browser = await puppeteer.launch({
    headless:false,
    defaultViewport: {
      width:1900,
      height:1080
    }
  });
  let page = await browser.newPage();
  await page.goto('https://www.jackall.co.jp/rooster/');
  const height = await page.evaluate(_ => {
    return document.body.scrollHeight;
  });
  await page.screenshot({ path: 'issue-4211.png', clip : { x: 0, y: 0, width:1900, height, scale: 1 }});
  await browser.close();
}())
```

**Comment by Rana-xD** [comment]
@jsoverson Thanks you. 
I have another question that is not related to this topic. Can we install puppeteer-core and chrome browser in two separate servers and connect it together? I plan to put puppeteer-core function code in AWS Lambda. So, I need to install chrome browser in EC2 server.

**Comment by aslushnikov** [comment]
Looks like original question is addressed, so I'll close this.

> I have another question that is not related to this topic. Can we install puppeteer-core and chrome browser in two separate servers and connect it together?

Yes you can; this is not the best place to ask about installing Chrome on AWS though - I'd search around or ask on StackOverflow.

**Comment by massan0314** [comment]
Edit:
maybe also related to: [Bug #959](https://github.com/GoogleChrome/puppeteer/issues/959)

I got two similar websites or lets say results.. I have still problems to capture them:
[page 1](http://www.utsumi-kikai.co.jp/)
[page 2](https://dragonflies.school/)

(Normal long websites seem to be incomplete with the method from above and ~40% of the bottom of the image is white)

When I observe the behavior on my screen with headless false, the website looks like it should, but when the screenshot method goes in action the top image/mp4 background becomes very large on the screen

Thats the maximum I can get out of it

[Page 1 result](https://user-images.githubusercontent.com/52655745/60875782-8784a000-a275-11e9-8d00-3ced3f8aa940.png)
[Page 2 result](https://user-images.githubusercontent.com/52655745/60875759-7dfb3800-a275-11e9-9c74-89a92c658fbf.jpg)
