### ISSUE TITLE
getting sourceof GoogleDrive video file -- GOogle (possibly) not recognizing puppeteer request

### ISSUE THREAD

**Issue by yaakovyitzchak** [puppeteer/puppeteer#4213]
I'm trying to use [Puppeteer][1] to attempt to get the direct link for a google drive video. To do that, I first navigate to the drive embed-video URL, then click on the play button (There are many of them), then wait for the iframe containing a video element to appear, then get the video element in the iframe, then I'm trying to get the source of the video, but it appears to be null, so I tried getting the outerHTML, and this is what I got in the console:

    <video tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" style="width: 800px; height: 450px; left: 0px; top: 75px;"></video>

Seemingly it hasn't been loaded yet, but I'm not sure what event to wait for, I waited for a timeout of 15 seconds but still got the same result, here's my code:

    var puppeteer = require("puppeteer");
    
        (async() => {
            var browser = await puppeteer.launch();
            console.log("Got browser", browser);
            var page = await browser.newPage();
            console.log(page,"got page");
         
            await page.goto("https://docs.google.com/file/d/1Cyuh41yNfYZU_zL-MHLf_EPJCYnlT7oJ/preview?enablejsapi=1&playerapiid=player4");
            console.log("went to page..");
            
          
          
            var clickEl = ".ndfHFb-c4YZDc-aTv5jf-bVEB4e-RJLb9c";
            var newClickID = ".ndfHFb-c4YZDc-aTv5jf-NziyQe-LgbsSe";
            var clicker = await page.waitForSelector(newClickID);
            console.log(clicker,"got clicker");
        
            await page.click(clickEl);
            console.log("clicked")
        
            var frame = await page.waitForSelector("iframe[id=drive-viewer-video-player-object-0]");
            console.log(frame, "got video frame");
            
            
        
            
            var cf = await frame.contentFrame();
            console.log(cf, "got content frame");
            await cf.waitFor(15000);
            var video = await cf.$("video");
            var src = await cf.evaluate(
                v => v.outerHTML,
                video
            );
            console.log("$$###VIDEO SOURCE::", src);
            await browser.close();
        })();

Any ideas, am I doing something wrong? why is the "src" attribute not showing up on the video element?

I **suspect** that when a normal user clicks on the play div in their browser, google looks for what kind of browser you're accessing it from and then possibly gets a video link specific to that browser, but if it recognizes puppeteer then maybe it (purposefully) doesn't, since its not a supported browser for viewing videos (maybe)

so is there some kind of puppeteer setting to make it seem like a specific browser? Or is there another issue?

**Comment by aslushnikov** [comment]
@yaakovyitzchak if you launch your browser in headful mode, you'll see that after a click you get a "this video format is not supported". 

You'd need to use Chrome Stable to be able to play all videos; see [here](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy) on running with Chrome Stable.
