### ISSUE TITLE
Puppeteer launch with Chrome (not with Chromium)

### ISSUE THREAD

**Issue by anialamo** [puppeteer/puppeteer#4215]
Hi!
In relation with this issue [Puppeteer chromium login and inmediately disconnect](https://github.com/GoogleChrome/puppeteer/issues/4214 ) I see was the error in this case... the webpage I tried to do Login (https://www.dia.es/compra-online/login/singlelogin) with Puppeteer it works! but....  2 seconds later... the supermarket logout me! in some traces... I see something like this... Your browser is not compatible, please use Chrome or Firefox.
If I open and try to login this website directly without Puppeteer and Javascript... only using Chromium browser I see also this error... I do Login... I see I'm connected as webpage user, but after 2 seconds... I see I am disconnected also... because the page executed Logout for my user.

I tested this page with Chrome... directly... and the login works fine!!!! I used Puppeteer with  Javascript ... And this page also ...works fine!!! 
But my testing was made using this code (my testing is in Windows 10 PC):

```
const browser = await puppeteer.launch({
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
        headless: true,
        args: [
            '--auto-open-devtools-for-tabs',
            '--disable-dev-shm-usage'
        ]
    });
```
How can I configure this in my Linux server? It's an Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-36-generic x86_64)
Thanks!

**Comment by dege88** [comment]
Maybe you can just use the user-agent of chrome instead of the default one from puppeteer.
you can change the user-agent with https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-pagesetuseragentuseragent
You can get your current user-agent from a website like https://www.whatsmyua.info/

**Comment by aslushnikov** [comment]
> How can I configure this in my Linux server?

@anialamo similarly to the windows setup, you'll need to provide an `executablePath` that points to the Chrome on your Linux machine. You can get the location of your stable chrome on linux using

```
which google-chrome-stable
```

Hope it helps.

**Comment by pratik-joshi-cactus** [comment]
Not working :/ in Version 75.0.3770.100 (Official Build) (64-bit), It still opens up new instance of chrome and it has no history whatsoever, I had to open it along with my other chrome tabs.

	const puppeteer = require('puppeteer');
	const pptr = require('puppeteer-core');
	(async () => {

		const browser = await puppeteer.launch({
		  headless: false,
		  executablePath: '/usr/bin/google-chrome'
		});

	})(); 

Here I also tried puppeteer-core , means pptr variable await pptr.launch in above variable, still not working. The issues is not closed!
