### ISSUE TITLE
Screenshot awaits forever in headful mode in linux environment.

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4218]
### Steps to reproduce
**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: ubuntu 16.0.4.4
* URLs (if applicable): https://ambicion.co.jp/en/technology/nkt.html
* Node.js version: v11.2.0

**What steps will reproduce the problem?**

The problem occurs only  in headful mode AND in linux environment.

```
const puppeteer = require('puppeteer');
 
(async ()=>{
const browser = await puppeteer.launch({'headless':false});
  const page = await browser.newPage();
  await page.goto('https://ambicion.co.jp/en/technology/nkt.html');
  await page.screenshot({'path': 'a.png'});
  console.log('done');
  await page.close()
  await browser.close()
})();

```

_Please include code that reproduces the issue._

1. `await page.goto('https://ambicion.co.jp/en/technology/nkt.html');` never gets resolved. Awaits forever.

**What is the expected result?**
screenshot taken and saved to disk

**What happens instead?**
screenshot never gets resolved. awaits forever.

**Comment by aslushnikov** [comment]
@ahteniv works for me on Linux with Puppeteer v1.14.0 

I'll speculatively close this.
