### ISSUE TITLE
Tabs being throttled in parallel - how to give them all equal share of resources?

### ISSUE THREAD

**Issue by mnmkng** [puppeteer/puppeteer#4219]
Hello, there doesn't seem to be a way to disable resource load scheduling in Puppeteer, or we're doing it wrong. For our purposes, which entail a lot of pages being open in parallel, with no particular priority, we want to allocate an equal amount of resources to each page. We found that there should be a flag called

```
--enable-resource-load-scheduler=false
```

that would disable the throttling features of Chromium that were introduced recently. It doesn't seem to have an effect, unfortunately.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13
* Platform / OS version: Mac OS 10.14.3 / various Linuxes in Docker
* Node.js version: 10 LTS

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');

(async function main() {
    const browser = await puppeteer.launch({
        args:['--enable-resource-load-scheduler=false'],
        headless: true,
    });

    const start = Date.now();
    const promises = Array(10).fill(null).map(async () => {
        const page = await browser.newPage();
        await page.goto('https://www.booking.com');
        console.log(`Page took ${Date.now() - start}ms to load.`);
    });
    await Promise.all(promises);
    console.log(`Opening of 10 pages took ${Date.now() - start}ms.`);
    await browser.close();
})();
```

**What is the expected result?**
With the code above, I expect the 10 pages to load in very similar times (using booking.com because it's quite a complex website that requires CPU power).

**What happens instead?**
Pages load one after the other, the last one taking almost twice as much time as first one.

```
Page took 4520ms to load.
Page took 5151ms to load.
Page took 5346ms to load.
Page took 6411ms to load.
Page took 6733ms to load.
Page took 7451ms to load.
Page took 7498ms to load.
Page took 7570ms to load.
Page took 8187ms to load.
Page took 8755ms to load.
Opening of 10 pages took 8755ms.
```

The `enable-resource-load-scheduler=false` might not even be the way to go, but do you have any tips on how to achieve equal power to all tabs?

Thanks.

**Comment by mnmkng** [comment]
cc @jancurn

**Comment by aslushnikov** [comment]
@mnmkng I didn't know about resource load scheduler before. Why do you think it's the culprit? 

FWIW, creating pages in separate browser contexts seems to be working fine:

```js
const puppeteer = require('puppeteer');

(async function main() {
  const browser = await puppeteer.launch({
    args:['--enable-resource-load-scheduler=false'],
    headless: true,
  });

  const start = Date.now();
  const promises = Array(10).fill(null).map(async () => {
    const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();
    await page.goto('https://www.booking.com');
    console.log(`Page took ${Date.now() - start}ms to load.`);
  });
  await Promise.all(promises);
  console.log(`Opening of 10 pages took ${Date.now() - start}ms.`);
  await browser.close();
})();
```

**Comment by mnmkng** [comment]
@aslushnikov I think it's the culprit because we started seeing warning messages in our logs about this feature about the same time we started noticing this issue. But it could be a pure coincidence.

We added a dirty workaround that focuses the oldest tab in the browser every time a new tab is spawned, so we at least get some FIFO going to combat this and it helped a lot with parallel performance.

Thank you for the idea with browser contexts. Would creating a context per page, when there are hundreds of pages opened and closed, affect performance? Are there any other considerations for this approach? (besides the obvious - context not being shared)

**Comment by aslushnikov** [comment]
>  Would creating a context per page, when there are hundreds of pages opened and closed, affect performance? Are there any other considerations for this approach? 

Context creation is very fast - ~1ms including the roundtrip over the Chrome DevTools protocol. There should be no performance regressions.

As a bonus: if page opens some other pages, browser contexts make it easy to clean the mess up (closing context closes all pages that belong to it).

**Comment by mnmkng** [comment]
Thank you @aslushnikov, I'm gonna close this since using contexts seems to provide a workable solution.

**Comment by JuanmaMenendez** [comment]
What about the RAM and CPU performance when there are several context / windows created? Won't it suffer enough for example with 10 windows opened?

Would we have a similar performance having: 

1 window with 10 tabs **vs** 10 windows with 1 tab each one?

**Comment by alexanderkjeldaas** [comment]
Not sure incognito contexts solves the issue reported here.  Incognito isolates cookies/session etc.  It might not be convenient to use that setup.

I've seen that CPU seems to be more evenly distributed with multiple windows, but `newPage()` opens a tab.  Maybe opening multiple windows is a better approach than incognito context.  Is this possible?

**Comment by jancurn** [comment]
Leaving this here for a reference: https://bugs.chromium.org/p/chromium/issues/detail?id=723233
