### ISSUE TITLE
Is browser/browserContext.page(index) acceptable sugar?

### ISSUE THREAD

**Issue by jsoverson** [puppeteer/puppeteer#4220]
I'd like to submit a PR that adds a `browser.page(index)` method to retrieve the page by index but am not sure if it's an acceptable amount of sugar.

> Avoid adding "sugar" API (API that is trivially implementable in user-space) unless they're very demanded.

`browser.page(index)` is one of those API methods that surprises people that it doesn't exist in the first place.

Current:

```
page = (await browser.pages())[0];
// or
[ page ] = await browser.pages()
```

Desired:

```
page = await browser.page(0);
```

This comes up for me frequently when instructing people on how to use puppeteer. I use `browser.newPage()` in examples because it's an easier line of code to digest. When people start on their own I am asked "how do I grab the default tab instead of opening a new one" which then leads to `(await browser.pages())[0]`. With a nearly 100% reproduce rate this is first written as `(await browser.pages()[0])`. I generally stay away from destructuring in workshops because it leads to a different set of problems. If this happens frequently in workshops then I expect it happens frequently for novice users all over.

**Comment by weworkwithzoh** [comment]
I for one would welcome this syntactic sugar.

**Comment by JoelEinbinder** [comment]
I agree that we should have a better api for` (await browser.pages())[0]`. However `browser.page(index)`  implies to me that the index should match the order of the tabs in headful chrome. This won't be accurate when a page is removed.

I think that something like `browser.launchedPage()` would behave in a more predictable way. Not sure about the name though.

**Comment by aslushnikov** [comment]
> I'd like to submit a PR that adds a browser.page(index) method to retrieve the page by index but am not sure if it's an acceptable amount of sugar.

@jsoverson The `page = await browser.page(index);` would require a matching `browser.pageCount()` call - I don't like it much.

> I generally stay away from destructuring in workshops because it leads to a different set of problems.

I personally like destructuring in this usecase. I suppose the problems you mention are not related to PPTR api?

**Comment by jsoverson** [comment]
Yeah, I get the concern. I stay away from destructuring because it requires additional explanation and anything but the most basic destructuring turns into extra issues for attendees that I need to then troubleshoot live.

**Comment by aslushnikov** [comment]
>  I stay away from destructuring because it requires additional explanation and anything but the most basic destructuring turns into extra issues for attendees that I need to then troubleshoot live.

Fair enough, modern JavaScript might be overwhelming. I personally defer to `browser.newPage()` when I explain Puppeteer to somebody.

To sum up: let's keep the "language familiarity" concern separate from the API and not add this sugar.
