### ISSUE TITLE
Using serialized function in evaluate

### ISSUE THREAD

**Issue by angrykoala** [puppeteer/puppeteer#4221]
Due to differences on how a string and a function are handled on `evaluate`, a serialized js function is not being executed as expected. I would like to be able to use a serialized function to avoid having to use `eval` as, to my understanding, the function would be serialized anyway at https://github.com/GoogleChrome/puppeteer/blob/v1.13.0/lib/ExecutionContext.js#L87

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: 8.15.1

**What steps will reproduce the problem?**

```js
function myFunction(){
    return true;
}


const result = await browser.page.evaluate(myFunction.toString());
console.log(result);
```

**What is the expected result?**

`true`

**What happens instead?**
The following error is thrown
```
 Error: Evaluation failed: SyntaxError: Unexpected token (
```

**Comment by JoelEinbinder** [comment]
When you pass puppeteer a string, we try to evaluate it as an expression not a function definition. Easy fix:
```js
const result = await browser.page.evaluate('(' + myFunction.toString() + ')();');
```

**Comment by angrykoala** [comment]
I guess the other behavior is not intended to be included then right? Thanks for your answer @JoelEinbinder I'll do that

**Comment by neuhausi** [comment]
How can you pass parameters?

**Comment by angrykoala** [comment]
@JoelEinbinder I may be missing something, but being an expression how could I get the callback parameters?

```js
const result = await browser.page.evaluate((number)=>{
    console.log(number);
}, 5);
```

**Comment by JoelEinbinder** [comment]
Embed them directly into the string, using json.stringify

**Comment by ghuser** [comment]
So I guess one way to register an api (that exists inside your node code) to the browser is:

```js
const registerApi = ()=>
  window.$myPageApi = {
          filterFunc: el=>!el.innerText.includes('X')?true:(console.log('skipping X entry'),false),
          filter2Func: el=>true
  };

...
await page.evaluate('('+registerApi.toString()+')()');
```

**Comment by LWD8** [comment]
pkg package.json --targets node18-macos --public。the --public means that : speed up and disclose the sources of top-level project.
