### ISSUE TITLE
why i can't open chrome://version page use headless mode,code page.goto("chrome://version"); and screenshot is white page?

### ISSUE THREAD

**Issue by renzhichaos** [puppeteer/puppeteer#4223]
my environment:**

* Puppeteer version:1.13.0
* Platform / OS version: window10 and centos7.4 with chrome 73.0.3683.75 --headless --no-sandbox
* Node.js version:10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.await page.goto('chrome://version')
2.page.screenshot({path: 'version.png'})
3.version.png is nothing and white 

but when i use 'headless: false', it can view chrome://version page and  screenshot is right page.

**Comment by JoelEinbinder** [comment]
Headless Chrome is actually a separate browser from Chrome. It doesn't contain many features, such as a UI, Chrome Extensions, and apparently `chrome://version`.
