### ISSUE TITLE
Pages aren't active in headless mode

### ISSUE THREAD

**Issue by thangtv611** [puppeteer/puppeteer#4230]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13
* Platform / OS version: Ubutu 18.04.1 LTS
* URLs (if applicable): vietjetair.com
* Node.js version: v8.15.1 LTS

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Set headless = true
2. Create a browsers with 10 pages.
3. Run the code

**What is the expected result?**
All the pages is run and return result (I was crawling data from this page)

**What happens instead?**
Timeout error.

I think this issue is the pages aren't activated. Because in headless mode is false, when the pages are opened, they are still not active after I click on the tab bar.

**Comment by aslushnikov** [comment]
@thangtv611 the more pages you create, the more they fight for resources between each other. They might require significantly more time to load.

What makes you think they don't load at all?

**Comment by thangtv611** [comment]
Hi @aslushnikov. I didn't say they didn't load at all. I though they didn't activate the page

**Comment by thangtv611** [comment]
When the page is activated. My script start running. That why I think my script alway return TimeoutError because they never run

**Comment by aslushnikov** [comment]
> When the page is activated. My script start running. That why I think my script alway return TimeoutError because they never run

@thangtv611 can you illustrate this with a small script? What kind of scripts don't run?
