### ISSUE TITLE
Sending 'Enter' key does not work with 'await'

### ISSUE THREAD

**Issue by kevinforrestconnors** [puppeteer/puppeteer#4231]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^1.13.0
* Platform / OS version: macOS Mojave 10.14.3 (18D109)
* URLs (if applicable): proprietary :/
* Node.js version: 6.9.0

_Please include code that reproduces the issue._

```js

describe("Test search_customer", function () {
  describe("autocompletes the input", function() {
    it("allowing users to quickly find the desired customer", async function() {

            this.retries(3);
            this.timeout(60000);

            const browser = await puppeteer.launch(puppeteer_opts);
            const page = await browser.newPage();
            await page.goto(`${get_test_url()}index.php`);
            await page.addScriptTag({path: require.resolve('jquery')});

            await page.type("#js_search_customers", "ACS");

            let autocompleted_value = await page.evaluate(() => {
                return $("#cust_id :selected").text();
            });

            expect(autocompleted_value).to.be.equal("ACS - Xerox Government Systems");

            await page.keyboard.press('Enter');

            let input_value = await page.evaluate(() => {
                return $("#js_search_customers").val();
            });

            expect(input_value).to.be.equal("ACS - Xerox Government Systems");

            await page.type("#js_search_customers", ":");

            ({ autocompleted_value, input_value } = await page.evaluate(() => {
                return {
                    autocompleted_value: $("#cust_id :selected").text(),
                    input_value: $("#js_search_customers").val()
                }
            }));

            expect(autocompleted_value).to.be.equal("ACS - Xerox Government Systems:FH Cloud Portal");
            expect(input_value).to.be.equal("ACS - Xerox Government Systems:");

            await page.type("#js_search_customers", "W");
            await page.keyboard.press('Enter');

            ({ autocompleted_value, input_value } = await page.evaluate(() => {
                return {
                    autocompleted_value: $("#cust_id :selected").text(),
                    input_value: $("#js_search_customers").val()
                }
            }));

            browser.close();

            expect(autocompleted_value).to.be.equal("ACS - Xerox Government Systems:Web development");
            expect(input_value).to.be.equal("ACS - Xerox Government Systems:Web development");
        });
```

**What steps will reproduce the problem?**

1. Run the test with default puppeteer options, it will fail
2. Run the test with slowMo: 200, it will pass
3. It also passes in headless: false - and you can see it work just fine.  This is clearly a timing issue.

**What is the expected result?**

The test hits enter to autocomplete the text, and it autocompletes and then checks against that value.

**What happens instead?**

The test finishes before the input can be made to the page, despite the 'await' statements

**Comment by aslushnikov** [comment]
@kevinforrestconnors this looks like a race condition to me. 

> The test finishes before the input can be made to the page

It looks like page takes some time to load before it is interactive. E.g. it might attach event listeners after certain timeout, e.g. when a deferred script gets to load.

I'd try to use `page.goto(url, {waitUntil: 'networkidle0'})` to make sure everything loads. If it doesn't help, you'd need to look into some markers on the page to figure if it's loaded or not.

Let me know if we can somehow help more here.

**Comment by kevinforrestconnors** [comment]
Thanks, I will try that.  My solution was to use page.waitFor(200), but
your solution seems better.
