### ISSUE TITLE
different PDF graph in different AWS account

### ISSUE THREAD

**Issue by AnkitLakhani** [puppeteer/puppeteer#4236]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.11.0
* Platform / OS version: Ubantu 
* URLs (if applicable): 
* Node.js version: 8.11.4

i generate PDF using pupeteer. it shows perfect graph in one AWS account with same configuration,code  and version i have different AWS account but **very rarely** pupeteer generate blank graph. is there any kind of hint to solve this issue.

**Comment by aslushnikov** [comment]
@AnkitLakhani what's a PDF graph?

**Comment by AnkitLakhani** [comment]
graph which i render in PDF using chart.js library in canvas.

**Comment by aslushnikov** [comment]
>  but very rarely pupeteer generate blank graph. is there any kind of hint to solve this issue.

I don't think there's any secret sauce here - looks more like an issue on the website side than on Puppeteer's. It's hard to say for sure unless there's a repro that illustrates the problem.
