### ISSUE TITLE
How save proxy in puppeteer after following link?

### ISSUE THREAD

**Issue by andriikov** [puppeteer/puppeteer#4242]
OS Ubuntu 18.04
puppeteer 1.14.0

My code is

const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        args: ['--proxy-server=http=XX.XX.XX.XX:8080'] 
      });
  const page = await browser.newPage();
  await page.goto('example.com');
  const element = await page.$('a');
  await element.click();
  await page.screenshot({path: 'example.png'});
})();
When I'm on example.com proxy works (checked on https://whatismyipaddress.com/)

But if I'll press "a", and follow link. (from example.com link to https://whatismyipaddress.com/) on whatismyipaddress displays my IP addr(not proxy)

How can I save proxy after follow link?

**Comment by xse** [comment]
Hey, i'm pretty sure you shouldn't use `--proxy-server=http=`
The following code works with http or socks5 proxies, outputing twice the same ip, before and after clicking on a link:
```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      //'--proxy-server=socks5://127.0.0.1:9050']
      '--proxy-server=76.185.16.94:54079']
  });
  const page = (await browser.pages())[0];
  await page.goto('https://check.torproject.org/', {waitUntil: 'networkidle0'});
  let ip = await page.evaluate(() => document.querySelector('.content > p:nth-child(3) > strong:nth-child(1)').innerText);
  console.log(ip);
  await page.evaluate(() => document.querySelector('#donate').href = "https://ifconfig.me/");
  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click('#donate'),
  ]);
  ip = await page.evaluate(() => document.querySelector('#ip_address').innerText);
  console.log(ip);
})();
```
