### ISSUE TITLE
Is raspberry pi 3 b+ compatible?  Failed to launch.

### ISSUE THREAD

**Issue by SeongwoonHong** [puppeteer/puppeteer#4249]
**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: raspberry pi 3 b+, ubuntu mate
* URLs (if applicable):
* Node.js version: 8.10.0

**What steps will reproduce the problem?**
```
const browser = await puppeteer.launch({
   headless: true,
   args: ['--no-sandbox', '--disable-setuid-sandbox']
});
```
this gives me error message 
```
Error: Failed to launch chrome!
/home/xxxx/.../node_modules/puppeteer/.local-chromium/liniux-641577/chrome-linux/chrome: Syntax error: word unexpected (expecting ") "
```
So i tried adding executablePath, for instance (not sure if this is valid though)
```
const browser = await puppeteer.launch({
   headless: true,
   executablePath: '/home/xxxx/.../node_modules/puppeteer/.local-chromium/liniux-641577/chrome-linux/chrome',
   args: ['--no-sandbox', '--disable-setuid-sandbox']
});
```

 but it gave me
```
Error: Failed to launch chrome! spawn 
/home/xxxx/.../node_modules/puppeteer/.local-chromium/liniux-641577/chrome-linux/chrome ENOENT
```

and if i do ```chromium-browser --version``` it says
```
Chromium 73.0.3683.75 Built on Ubuntu, running on Ubuntu 18.04
```
Thank you guys.

**Comment by SeongwoonHong** [comment]
solved.

**Comment by dovepa** [comment]
Hello,

How have you solve this ?

**Comment by lefuturiste** [comment]
Same problem here, How hava you solve this ???

**Comment by bdotsamir** [comment]
@SeongwoonHong I'm having this issue too. Please tell us how to solve this!

**Comment by ablears** [comment]
Try using your chromium-browser, rather than Puppeteer's chrome which might not work on the PI's ARM architecture.

` const browser = await puppeteer.launch({
        executablePath: 'chromium-browser'
  });  `

I had to do this on a PI 4.

**Comment by ibrcic** [comment]
For anyone for whom the above mentioned solution doesn't work, make sure that you have chromium installed on your RPI or install it using.

`sudo apt-get install chromium-browser --yes`
