### ISSUE TITLE
Emojis from Facebook are not colored in PDF

### ISSUE THREAD

**Issue by ateufel** [puppeteer/puppeteer#4252]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Windows 10 Pro
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

I´ve got a Facebook App that lists recent Posts of a Facebook Page. Even with Emojis, this works well in any Browser. I am Using Puppeteer to generate a PDF from the exakt same page that is shown in the App itself. The problem: All Emojis show up black instead of colored in the resulting PDF.

Settings:
```
const browser = await puppeteer.launch({headless: true, ignoreHTTPSErrors: true, args: ['--no-sandbox', '--disable-setuid-sandbox']});
const page = await browser.newPage();
await page.setViewport({width: 1400, height: 794, isLandscape: true});
await page.emulateMedia('screen');
```

**What is the expected result?**
Emojis should show up with color in the PDF:

![app_correct](https://user-images.githubusercontent.com/2619527/55714308-bd09bb00-59f2-11e9-80b9-c3dc7fcff649.png)

**What happens instead?**
All Emojis show up black:

![pdf_wrong](https://user-images.githubusercontent.com/2619527/55714185-7320d500-59f2-11e9-9888-f77ba0aef900.png)

**Comment by aslushnikov** [comment]
@ateufel this looks like a font resolution issue to me. Does it work for you if you just hit "Save as PDF" in chrome?

**Comment by ateufel** [comment]
No, same problem, it shows up black/white in the print preview. Tried with different fonts with the same result. We will try to replace Emojis with images instead.

**Comment by aslushnikov** [comment]
@ateufel can you please file this upstream to https://crbug.com/new? Chromium PDF team will be happy to help.

**Comment by ateufel** [comment]
Yeah, i guess this is not related to Puppeteer, but only to Chromium. Thanx for helping!

**Comment by aslushnikov** [comment]
@ateufel if you ended up submitting a bug to Chromium, can you please cross-post a link here?

**Comment by jelordreygulle** [comment]
Do you have solution to this now ? I am also having this kind of issue . Thanks
