### ISSUE TITLE
Ubuntu - TimeoutError: Timed out after 30000 ms while trying to connect to Chrome!

### ISSUE THREAD

**Issue by GhostvOne** [puppeteer/puppeteer#4253]
**Tell us about your environment:** Ubuntu 16.04.6 LTS

* Puppeteer version:  puppeteer@1.14.0 
* Node.js version: v11.13.0

**What steps will reproduce the problem?** I'm just running a simple script for go to a webpage with puppeteer.

**Please include code that reproduces the issue.**

> const puppeteer = require('puppeteer');
>
>const browser = await puppeteer.launch({
>	headless: false,
>	args: [ '--no-sandbox',
>		'--disable-setuid-sandbox',
>		'--disable-webgl',
>		'--disable-accelerated-2d-canvas',
>		'--disable-gpu',
>		'--mute-audio',
>	]
>});
>
>const page = await browser.newPage();
>
>console.log('Init Request Page')
>const response = await page.goto('https://api.ipify.org?format=json');
>
>console.log(page.content());

**What is the expected result?**
showing me the source code of the page. Works on my windows dev environement, but not on my prod ubuntu server

**What happens instead?**

(node:2855) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r641577
    at Timeout.onTimeout (/home/nodejs/Proxies/node_modules/puppeteer/lib/Launcher.js:353:14)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
(node:2855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment]
> but not on my prod ubuntu server

@Ghostaunt Are you sure you can run non-headless on your prod environment? I'd try running there with `headless: true`.

**Comment by GhostvOne** [comment]
Hello thanks for your answer.
With headless true now i have this error

>  UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
>
>
>TROUBLESHOOTING: >https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
>
>    at onClose (/home/nodejs/Proxies/node_modules/puppeteer/lib/Launcher.js:342:14)
>    at ChildProcess.helper.addEventListener (/home/nodejs/Proxies/node_modules/puppeteer/lib/Launcher.js:332:60)
>    at ChildProcess.emit (events.js:198:15)
>    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
>(node:2716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated >either by throwing inside of an async function without a catch block, or by rejecting a promise which >was not handled with .catch(). (rejection id: 1)
>(node:2716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the >future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit >code.


Dependencies are installed

**Comment by GhostvOne** [comment]
And if I run node myscriot.js as root i have same error as my first message

**Comment by aslushnikov** [comment]
>Dependencies are installed

Does Chromium launch manually for you in your prod environment?

**Comment by GhostvOne** [comment]
How can i try that ? I'm using ubuntu server

**Comment by aslushnikov** [comment]
in your project directory, there should be a `node_modules/puppeteer/.local-chromium/` folder. Inside of it there's a single folder with a chromium binary - try running it manually.

**Comment by GhostvOne** [comment]
Is this  the good way to do that ? https://i.imgur.com/wfjVbWO.png

**Comment by aslushnikov** [comment]
@Ghostaunt you need to do `./chrome --headless` instead of just `chrome`

**Comment by GhostvOne** [comment]
Ok, no error, seems to works https://i.imgur.com/6lsOhJQ.png

**Comment by aslushnikov** [comment]
@Ghostaunt let's make the command a little more complicated.

1. Try running this:

```sh
./chrome --headless --screenshot https://google.com
```

2. If it works, let's try running the following Puppeteer script without any of the flags you pass in and with a 'dumpio' flag:

script:
```js
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch({dumpio: true});
  const page = await browser.newPage();
  await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle2'});
  await browser.close();
})();
```

Launch it with a "DEBUG" env variable:
```js
$ DEBUG=puppeteer:* node script.js
```

If this works - great! If it's not, can you please paste the log that's yielded here?

**Comment by GhostvOne** [comment]
Hello thanks for you answer.
Screenshot works very well.

With dumpio it works too. Thanks now everyting works :o

**Comment by knandraina** [comment]
Hello!

I have the exact same error when I deploy the code on Cloud Function. I tried to replicate what you have written above, but it does not work. Do you have any idea how I could manage that? ON my computer it works well!

`async function main_screenshot(project_id) {
  try {
    const browser =  await puppeteer.launch({
        headless: true,
        args: ["--window-size=1440,1000", "--no-sandbox", "--disable-setuid-sandbox", "--disable-gpu"]
      });

    const page = await browser.newPage()
    page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36')
    page.setViewport({ width: 1440, height: 721 })
    console.log('entering in screenshot zone')
    page.setDefaultNavigationTimeout(30000)
    await page.goto('s')
    await page.waitFor(3000)
    await page.type('#email', process.env.SLACK_EMAIL)
    await page.type('#password', process.env.SLACK_PWD)
    await page.waitFor(3000)
    await page.click('#signin_btn')
    console.log('credentials done')
    await page.waitFor(3000)
    console.log('so?')
    await page.goto('')
    await page.waitFor(3000)
    console.log('connected to the right environment')
    const div = await page.$$('.c-message.c-message--light')
    var number_loop= 0
    for (var i = div.length ; i > 0; i--) {
      var text = await (await div[i - 1].getProperty('textContent')).jsonValue();
      
      if(text.includes(project_id)) {
        number_loop = i
        break
      }
    }
    // const text = await (await div.getProperty('textContent')).jsonValue();
    
    
     const shotResult = await div[number_loop-1].screenshot();
    console.log(shotResult)
    cloudinaryOptions = {
      public_id: `${project_id}`
    }

    const results = await uploadToCloudinary(shotResult, cloudinaryOptions)
    console.log(results)
    browser.close()
    return results
  } catch (e) {
    console.log(e)
  }
}
`

**Comment by knandraina** [comment]
> Hello!
> 
> I have the exact same error when I deploy the code on Cloud Function. I tried to replicate what you have written above, but it does not work. Do you have any idea how I could manage that? ON my computer it works well!
> 
> `
> async function main_screenshot(project_id) {
> try {
> const browser = await puppeteer.launch({
> headless: true,
> args: ["--window-size=1440,1000", "--no-sandbox", "--disable-setuid-sandbox", "--disable-gpu"]
> });
> // const browser = await puppeteer.launch({dumpio: true});
> const page = await browser.newPage()
> page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36')
> page.setViewport({ width: 1440, height: 721 })
> console.log('entering in screenshot zone')
> page.setDefaultNavigationTimeout(30000)
> await page.goto(link)
> await page.waitFor(3000)
> await page.type('#email', process.env.SLACK_EMAIL)
> await page.type('#password', process.env.SLACK_PWD)
> await page.waitFor(3000)
> await page.click('#signin_btn')
> console.log('credentials done')
> await page.waitFor(3000)
> console.log('so?')
> await page.goto('link')
> await page.waitFor(3000)
> console.log('connected to the right environment')
> const div = await page.$$('.c-message.c-message--light')
> var number_loop= 0
> for (var i = div.length ; i > 0; i--) {
> var text = await (await div[i - 1].getProperty('textContent')).jsonValue();
> 
> 
>   if(text.includes(project_id)) {
>     number_loop = i
>     break
>   }
> }
> // const text = await (await div.getProperty('textContent')).jsonValue();
> 
> 
>  const shotResult = await div[number_loop-1].screenshot();
> console.log(shotResult)
> cloudinaryOptions = {
>   public_id: `${project_id}`
> }
> 
> const results = await uploadToCloudinary(shotResult, cloudinaryOptions)
> console.log(results)
> browser.close()
> return results
> 
> 
> } catch (e) {
> console.log(e)
> }
> `
