### ISSUE TITLE
Full CSS Style support in header and footer html and Loading external Resources

### ISSUE THREAD

**Issue by aswiinraviprakash** [puppeteer/puppeteer#4254]
Is there any update for all CSS properties support in header and footer HTML and loading of external resources ?

**Comment by aslushnikov** [comment]
> Is there any update for all CSS properties support in header and footer HTML and loading of external resources ?

@AswiinR I think I'm missing the context. What are we talking about here? Is it PDF printing or something else?

**Comment by aswiinraviprakash** [comment]
@aslushnikov It is for **PDF Printing** using page.pdf()

**Comment by aslushnikov** [comment]
@AswiinR so what properties are missing? Are we talking about `@page` css properties or something else? Is it about page's content, or the `footerTemplate` and `headerTemplate` pieces you pass as arguments to `page.pdf()`?

**Comment by aswiinraviprakash** [comment]
@aslushnikov Yes we need **@page properties support for page content** and loading of **external resources such as image in header and footer template**

**Comment by aswiinraviprakash** [comment]
@aslushnikov any update regarding this ?

**Comment by millerick** [comment]
@aslushnikov , I'm also interested in the ability to load external stylesheets and images in the header and footer.

**Comment by abhij89** [comment]
this is still open. unable to use stylesheets, images in the header & footer templates
