### ISSUE TITLE
Implement HTTP Authentication API

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#426]
HTTP Authentication could look like this (similar to [Nightmare.js](https://github.com/segmentio/nightmare#authenticationuser-password)):
```js
await page.authenticate(user, pass);
```

**Comment by entrptaher** [comment]
![image](https://user-images.githubusercontent.com/8284972/29506330-ea2ad732-866c-11e7-9529-c6f45ca50c8c.png)

The basic auth and basic header does not work with proxies. Or at least on my part. Notifying this before you implement this feature. Proxy auth and normal auth might be two different things.

**Comment by zqsd** [comment]
That's right proxy and website authentification are two different things.  Proxy has a different http header, "Proxy-Authorization".

I just tried the example at https://github.com/GoogleChrome/puppeteer/issues/418#issuecomment-323582270 by changing "Authorization" to "Proxy-Authorization" and it worked.
EDIT: It worked in HTTP, but in HTTPS it doesn't.
In the case of https proxy the browser has to make a tunnel "connect" before sending the request to the website. After analyzing the traffic I noticed "Proxy-Authorization" wasn't part of the connect request headers even though I use setExtraHTTPHeaders.

**Comment by nigeon** [comment]
Didn't work for me :(

**Comment by PeKoehler** [comment]
[Edited:] method needs its parameters als object literals, i.e. name:value pairs

```javascript
const puppeteer = require('puppeteer');
async function run() {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.authenticate({username:"postman", password:"password"});
  await page.goto('https://postman-echo.com/basic-auth');
}
run()
```

**Comment by Khady** [comment]
I think that `authenticate` doesn't wait for two arguments but one object
with `username` and `password` fields.

**Comment by Glennvd** [comment]
page.authenticate doesn't work for my proxy configuration. The auth window comes on a different tab that I can't access, other than the browser.newPage(). Any workarounds for this?

**Comment by aslushnikov** [comment]
@Glennvd this sounds like a bug. Would you mind creating a new issue and describing what's your setup? It would be very helpful if we would be able to re-create your setup locally and reproduce the issue.

**Comment by itrade24** [comment]
@aslushnikov what about a normal proxy server authorization. Current approach do not allow to normally proxy HTTPS traffic.

**Comment by aslushnikov** [comment]
> what about a normal proxy server authorization.

@itrade24 I'm not sure I understand. What is this?

**Comment by itrade24** [comment]
@aslushnikov Thanks for reply

Normal proxy authorization involves the use of 'Proxy-Authorization' header for HTTP requests. Smth likes:

```javascript
const headers = {'Proxy-Authorization' : 'Basic ...'};
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.setExtraHTTPHeaders(headers);
await page.goto('https://example.com');
```

It works... But for HTTP only. HTTPS proxy with CONNECT request and tunnel does not work.

In PhantomJS:

--proxy=address:port
--proxy-type=[http|socks5|none]
--proxy-auth=username:password

What about Puppeteer ?

**Comment by adarmanto** [comment]
@itrade24 I got it is working with HTTPS proxy by passing the`--proxy-server="https=address:port"` to `args` option (with double quotes), it is mentioned on `man google-chrome`:

>It is also possible to specify a separate proxy server for different URL  types,  by  prefixing
>the proxy server specifier with a URL specifier:
>
>Example:
>
>--proxy-server="https=proxy1:80;http=socks4://baz:1080"
>    Load https://* URLs using the HTTP proxy "proxy1:80". And load http://*
>    URLs using the SOCKS v4 proxy "baz:1080".

**Comment by ikebo** [comment]
does not work for socks proxy ?
if i want to auth a socks proxy, what would i do ？

**Comment by aslushnikov** [comment]
@itrade24 @ikebo I filed a separate issue for SOCKS proxy authentication - #4170. Please upvote / subscribe.

**Comment by Pechi77** [comment]
May I know how can we cancel the authentication, in my use case, we request to every domain in our pool, if some page requires authentication, need to click on cancel so that it will redirects to invalid page, we will be able to extract the invalid html.
image

![image](https://github.com/puppeteer/puppeteer/assets/16059874/a5d5b600-16b2-4b47-9392-478f852762ce)
