### ISSUE TITLE
Different screenshots.

### ISSUE THREAD

**Issue by om3** [puppeteer/puppeteer#4262]
Hi, I'm getting different screenshots using puppeteer in my desktop and Amazon cloud.
I need to get the latest videos in public Facebook page.

Take look, desktop screenshot:
https://ibb.co/56Yrnrq

EC2 Cloud(It not listed the videos):
https://ibb.co/cYfN8Ks

**Comment by aslushnikov** [comment]
@om3 the website serves different content to you - that's not Puppeteer's fault. You should either fake your location, or be prepared to the content differences.

Hope this helps.
