### ISSUE TITLE
page.queryObjects has crashed the browser since version 1.12.0

### ISSUE THREAD

**Issue by kelvinau** [puppeteer/puppeteer#4263]
* Puppeteer version: 1.14.0
* Platform / OS version: Ubuntu 16.04.6 LTS
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**
Simply running the example:

```js
const browser = await puppeteer.launch();
const page = await browser.newPage(); 
await page.goto('https://google.com');

// Create a Map object
await page.evaluate(() => window.map = new Map());
// Get a handle to the Map object prototype
const mapPrototype = await page.evaluateHandle(() => Map.prototype);
// Query all map instances into an array
const mapInstances = await page.queryObjects(mapPrototype);
// Count amount of map objects in heap
const count = await page.evaluate(maps => maps.length, mapInstances);
await mapInstances.dispose();
await mapPrototype.dispose();
```
It crashes at `page.queryObjects`, when going to a url. If the page doesn't navigate to any page, it works.
This also works on 1.11.0.

I believe the error is thrown from here:
https://github.com/GoogleChrome/puppeteer/blob/2a7c3fe3e68aac3dbca130065a67a8f0aa7db621/lib/ExecutionContext.js#L173-L175

**What is the expected result?**

Code runs through without any error.

**What happens instead?**

Browser crashed with error:
```
    Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Error: Page crashed!)

      at Page._onTargetCrashed (node_modules/puppeteer/lib/Page.js:185:10)
```

**Comment by aslushnikov** [comment]
@kelvinau the following works fine for me with Puppeteer v1.14.0:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  // Create a Map object
  await page.evaluate(() => window.map = new Map());
  // Get a handle to the Map object prototype
  const mapPrototype = await page.evaluateHandle(() => Map.prototype);
  // Query all map instances into an array
  const mapInstances = await page.queryObjects(mapPrototype);
  // Count amount of map objects in heap
  const count = await page.evaluate(maps => maps.length, mapInstances);
  console.log(count);
  await mapInstances.dispose();
  await mapPrototype.dispose();
  await browser.close();
})();
```

Can you please verity it crashes for you?

**Comment by kelvinau** [comment]
@aslushnikov your code works, but I forgot to mention one more key point.
It crashes only after going to any url. I edited the initial post.

**Comment by aslushnikov** [comment]
@kelvinau that's a DevTools protocol bug; reported upstream at https://crbug.com/952057

Thanks for reporting!
