### ISSUE TITLE
Blacklist URLs

### ISSUE THREAD

**Issue by mlucool** [puppeteer/puppeteer#4267]
Hi,

There appears to be no way to pass the [URLBlacklist/URLWhitelist](https://www.chromium.org/administrators/policy-list-3#URLBlacklist) to puppeteer. I do not see the flag listed [here](https://peter.sh/experiments/chromium-command-line-switches/) and any attempt to pass something that I would expect to the flag to be is not honored (as expected). Is it possible to add in a way to force all pages to honor this flag? [pagesetrequestinterceptionvalue](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionvalue) is in the right direction, but somewhat painful to use for all pages.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Linux RHEL7
* Node.js version: 10.x

**What steps will reproduce the problem?**
```
    const browser = await puppeteer.launch({args: ['--url-blacklist=*']});
    const page = await browser.newPage();
    await page.goto('https://google.com');
    await page.screenshot({path: 'screenshot.png'}); // This should NOT work

    await browser.close();
```

**What is the expected result?**
Page.goto should throw

**What happens instead?**
The flag does not exist, so it renders.

**Comment by aslushnikov** [comment]
> but somewhat painful to use for all pages.

@mlucool Why's it painful?

**Comment by mlucool** [comment]
I need to manage the settings for a group of applications.  Looking more into this, would it be possible to have support for policies be honored? This would solve this and similar problems.

**Comment by aslushnikov** [comment]
> Looking more into this, would it be possible to have support for policies be honored? This would solve this and similar problems.

@mlucool Isn't it working out-of-the box? Did you try following [chromium policies setup](https://www.chromium.org/administrators/linux-quick-start)?

**Comment by mlucool** [comment]
@aslushnikov I have tried following above. I set both chrome/chromium policies to be sure I wasn't missing something. I also choose managed to ensure I didn't accidental override it. I used a screenshot to verify that code really did run as well.

```
$ cat /etc/chromium/policies/managed/block.json 
{
  "URLBlacklist": ["*"]
}
$ cat /etc/opt/chrome/policies/managed/block.json 
{
  "URLBlacklist": ["*"]
}
$ cat example.js
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
        executablePath: '/path/to/node_modules-v10/lib/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome',
            args:
        [ '--disable-setuid-sandbox',
            '--no-sandbox']
    });
    const page = await browser.newPage();
    await page.goto('https://google.com');
    // await page.screenshot({path: 'example.png'});

    const bodyHTML = await page.evaluate(() => document.location.href);
    console.log(bodyHTML);

    await browser.close();
})();
$ node example.js
https://www.google.com/
```

**Comment by mlucool** [comment]
@aslushnikov were you able to reproduce this issue?

**Comment by koenrh** [comment]
@mlucool I have been running into the same issue. I spent quite some time debugging it, but no matter what I tried, `chrome` never even (attempted) to read the policy file from disk.

It turns out that policies do not seem to be supported in headless Chromium. See [this thread](https://bugs.chromium.org/p/chromium/issues/detail?id=698629).

**Comment by aslushnikov** [comment]
@koenrh yes, policies are only working in headful - sorry for not mentioning it early on.

**Comment by mlucool** [comment]
Given this, what do you suggest we do @aslushnikov? Is the only suggestion here, containerize it?

**Comment by aslushnikov** [comment]
I'd suggest using xvfb + headful mode with policies. Or just go with request interception :-)

**Comment by mlucool** [comment]
Headful mode appears to be a non-starter for how we run puppeteer (e.g. rendering internal sites on cluster hosts for things like testing and screenshots). Any accidental headless mode would also make it too easy to silently ignore policies. Page interception would add a layer on top of puppeteer and be hard to inject in applications that use puppeteer under the hood (most allow for us to pass in settings, this fix would not be a setting).

I think the only solution then is containerization if puppeteer is not willing to give a way to support policies in headless.

**Comment by aslushnikov** [comment]
> if puppeteer is not willing to give a way to support policies in headless.

Strictly speaking it's not part of Puppeteer but Headless Chrome - but yes, I don't think it's coming in any near future.

Sorry we can't be helpful here!

**Comment by sputnick-dev** [comment]
What about this code?

```
page.on('request', (request) => {
  const url = request.url();
  if (blacklist.some((domain) => url.includes(domain))) {
    request.abort();
  } else {
    request.continue();
  }
});
```

**Comment by arogonov** [comment]
@sputnick-dev This is a good way, but it doesn't work for Webosket connections. They are invisible in `page.on('request', (request) => {`
