### ISSUE TITLE
How to silence 'Navigation failed because browser has disconnected'

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4275]
How to I silence this error `(node:12171) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!`

```javascript
page.goto('https://example.com/')
await page.waitFor('body')
const body = await page.evaluate(() => document.querySelector('body').textContent)
console.log(body)

await this.page.close()
await browser.close()
```

I can get body element successfully but because the browser closes before the page.goto has finished I get disconnected error which I want to silence. (not sure if this specific example works, this is pseudo code I haven't tested)

**Comment by ghost** [comment]
I think this might have fixed my problem

```javascript
await Promise.race([
  this.page.goto('https://example.com/'),
  this.page.waitFor('body')
])
```

**Comment by aslushnikov** [comment]
>  this might have fixed my problem

It's a good hygiene to try awaiting all promises.

**Comment by ghost** [comment]
I'm actually still getting a problem that I don't get how to solve. It seems that no matter how many try catch I put it doesn't catch the error and stops my program. It's hard to debug cause it only happens every few hours and not sure what causes it but it only happens when I use page.waitFor

```javascript
try {
  try {
    try {
      try {
        const timeout = 180 * 1000
        await Promise.race([
          page.goto('https://example.com/', {timeout}),
          page.waitFor('body', {timeout})
        ])
      }
      catch (e) {}
    }
    catch (e) {}
  }
  catch (e) {}
}
catch (e) {}
```

```
(node:75313) UnhandledPromiseRejectionWarning: TimeoutError: waiting for target failed: timeout 30000ms exceeded
    at Function.waitWithTimeout (/node_modules/puppeteer/lib/helper.js:214:26)
    at Browser.waitForTarget (/node_modules/puppeteer/lib/Browser.js:214:27)
    at Browser.<anonymous> (/node_modules/puppeteer/lib/helper.js:111:23)
    at Launcher.launch (/node_modules/puppeteer/lib/Launcher.js:178:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:75313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75313) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@dave-dm you should use `Promise.all` instead of `Promise.race`:

```js
await Promise.all([
  page.goto('https://example.com/', {timeout}),
  page.waitFor('body', {timeout})
])
```

**Comment by ghost** [comment]
I don't want to wait for both, I want to wait for only the first to resolve. That might work if I put the `page.goto` timeout to `1` or something, haven't tested.

**Comment by aslushnikov** [comment]
> I don't want to wait for both, I want to wait for only the first to resolve. 

@dave-dm in this case, make sure to add `.catch` for every promise to avoid `UnhandledPromiseRejection`.

```js
await Promise.race([
  page.goto('https://example.com/', {timeout}).catch(() => {}),
  page.waitFor('body', {timeout}).catch(() => {}),
])
```
