### ISSUE TITLE
.click() hangs forever when adjusting scale of page using CDP client

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4285]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
`cdpClient.send("Emulation.setDeviceMetricsOverride", { mobile: false, height:1024, width: 768, scale: .5, deviceScaleFactor: 1 });`

**What is the expected result?**
page.click("#mySelector") should work. I believe this is happening because I'm using the CDP client to change the scale of the page. Click calculates the coordinates wrong, never hears back after the click and thus hangs forever. It is NOT possible to adjust the scale of the page with the current puppeteer APIs. deviceScaleFactor is something different. 

**What happens instead?**
page.click("#mySelector") hangs indefinitely

**Comment by aslushnikov** [comment]
@curiouslybrown why would you want to adjust scale?

**Comment by ghost** [comment]
I'm automating a website with puppeteer and seeing the details on the page is not too important, so it'd be helpful just to have a little thumbnail type view next to my text editor.

**Comment by aslushnikov** [comment]
@curiouslybrown 2 things:
1. can you please try with puppeteer@next? There was recently a CL that was fixing a similar issue: https://crrev.com/648424
2. If it still doesn't work on puppeteer@next, can you please come up with a small puppeteer script that reproduces the issue for you?

**Comment by aslushnikov** [comment]
I'll speculatively close; please yell here if it shouldn't be.
