### ISSUE TITLE
Failed to launch chrome! Reason: image not found Mac OS X

### ISSUE THREAD

**Issue by stereobooster** [puppeteer/puppeteer#4286]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Mac OS X 10.11.6
* URLs (if applicable): 
* Node.js version: v10.11.0
* yarn: 1.9.4

**What steps will reproduce the problem?**

```
git clone https://github.com/stereobooster/reactSnapshotTest.git
cd reactSnapshotTest
yarn
yarn build
$ react-snap
Error: Failed to launch chrome!
dlopen node_modules/puppeteer/.local-chromium/mac-641577/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3738.0/Chromium Framework.framework/Chromium Framework: dlopen(node_modules/puppeteer/.local-chromium/mac-641577/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3738.0/Chromium Framework.framework/Chromium Framework, 261): Library not loaded: /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
  Referenced from: node_modules/puppeteer/.local-chromium/mac-641577/chrome-mac/Chromium.app/Contents/Versions/75.0.3738.0/Chromium Framework.framework/Versions/A/Chromium Framework
  Reason: image not found


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:187:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
```

**What is the expected result?**

**What happens instead?**

**Comment by lukaszfiszer** [comment]
I have the same issue on Mac OS X 10.10.5. 

Downgrading to puppeteer 1.13 (chromium rev mac-637110) fixes it.

**Comment by originative** [comment]
I have this exact same problem as well on 10.11.6.

The MediaPlayer framework doesn't exist on my machine, does anyone know if was included in later versions of OS X?

Chrome Canary version 75.0.3761.0 works fine without this framework so it doesn't seem like the latest versions of Chrome will require this framework. That's actually a workaround for now, install Canary and set executablePath to point to it.

**Comment by aslushnikov** [comment]
> That's actually a workaround for now, install Canary and set executablePath to point to it.

@originative Can you please check if installing `puppeteer@next` fixes the issue?

**Comment by tzohpilotl** [comment]
@aslushnikov I installed `puppeteer@next` and I'm getting the same error while trying to test using Jest + Puppeteer:

```
Error: Failed to launch chrome!
dlopen /Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/.local-chromium/mac-650583/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3765.0/Chromium Framework.framework/Chromium Framework: dlopen(/Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/.local-chromium/mac-650583/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3765.0/Chromium Framework.framework/Chromium Framework, 261): no suitable image found.  Did find:
	/Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/.local-chromium/mac-650583/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3765.0/Chromium Framework.framework/Chromium Framework: mmap() errno=5 at address=0x10D3BE000, size=0x0813D000 segment=__TEXT in Segment::map() mapping /Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/.local-chromium/mac-650583/chrome-mac/Chromium.app/Contents/MacOS/../Versions/75.0.3765.0/Chromium Framework.framework/Chromium Framework
	/Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/.local-chromium/mac-650583/chrome-mac/Chromium.app/Contents/Versions/75.0.3765.0/Chromium Framework.framework/Versions/A/Chromium Framework: mmap() errno=5 at address=0x115E4E000, size=0x0813D000 segment=__TEXT in Segment::map() mapping /Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/.local-chromium/mac-650583/chrome-mac/Chromium.app/Contents/Versions/75.0.3765.0/Chromium Framework.framework/Versions/A/Chromium Framework


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md


    at onClose (/Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/Users/mariogil/Developer/designers-in-vietnam/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:202:15)
    at Interface.close (readline.js:395:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1132:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by Prestaul** [comment]
I'm still having this problem with puppeteer at version 1.18.1. 

Is there a plan to provide a fix?

**Comment by Aidin12** [comment]
> I have the same issue on Mac OS X 10.10.5.
> 
> Downgrading to puppeteer 1.13 (chromium rev mac-637110) fixes it.

thank u! it worked! I had the same problem with Yosemite

**Comment by roseline124** [comment]
I am still undergoing this problem. is there anyone can help? 😂

Puppeteer version: 2.1.1
MacOS: BigSur 
Node: 16.4.2 

```
Failed to launch chrome!
    dlopen /Users/whoami/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: dlopen(/Users/whoami/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework, 261): no suitable image found.  Did find:
/Users/whomai/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: open() failed with errno=1
        /Users/whomai/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: stat() failed with errno=1
        /Users/whomai/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: open() failed with errno=1
```

**Comment by roseline124** [comment]
> I am still undergoing this problem. is there anyone can help? 😂
> 
> Puppeteer version: 2.1.1
> MacOS: BigSur
> Node: 16.4.2
> 
> ```
> Failed to launch chrome!
>     dlopen /Users/whoami/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: dlopen(/Users/whoami/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework, 261): no suitable image found.  Did find:
> /Users/whomai/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: open() failed with errno=1
>         /Users/whomai/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: stat() failed with errno=1
>         /Users/whomai/git/secretRepo/node_modules/puppeteer/.local-chromium/mac-706915/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/80.0.3987.0/Chromium Framework: open() failed with errno=1
> ```

I solved this problem like below:

1. use `chrome` browser instead of 'chromium'.
2. how? you can find your tchrome app path
  - input url `chrome://version/` in chrome browser and find executable path. 
  - copy that
2. set executablePath with the chrome path in launchOption
