### ISSUE TITLE
Sometimes click is not triggered

### ISSUE THREAD

**Issue by Kalliser** [puppeteer/puppeteer#4289]
Hello I found what seems another issue, the click on on the targetet element seems nerver be triggered. It works fine if I connect to remote chrome with dev tools, but not if clicking by code.

## Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: next
* Platform / OS version: Debian (Dockerized in node:10-stretch-slim)
* URLs (if applicable): https://www.kusmitea.com/vente-the/the-mate.html
* Node.js version: v10.15.1

**What steps will reproduce the problem?**

Open the website
Emulate a mobile environnment
Click on `button.addToCart.btn[data-sku="DETO125"]`
Wait for the ajax request `ajax/cart/addToCart` to be triggered after clicking the button

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch();

const page = await browser.newPage();
                await page.emulate({viewport: { width: 360, height:  640, deviceScaleFactor: 3, isMobile: true, hasTouch: true, isLandscape: false }, userAgent: 'Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3679.0 Mobile Safari/537.36'});

                await page.goto('https://www.kusmitea.com/vente-the/the-vert.html', {waitUntil: ['networkidle0', 'load', 'domcontentloaded'], timeout: 30000});
                console.log(await page.url());


                const element = await page.$('button.addToCart.btn[data-sku="DETO125"]');
                await element.screenshot({path: 'button.png'});
                await page.screenshot({path: 'screenshot.png'});

                await Promise.all([
                    element.click(),
                    page.waitForRequest(request => {
                        const test = /ajax\/cart\/addToCart/;
                        return test.test(request.url());
                    })
                ]).catch(error => {
                    console.log(error);
                });

                console.log(await page.url());

```

**What is the expected result?**
The ajax request `ajax/cart/addToCart` should be run

**What happens instead?**
Nothing happens and the wait for request ends with a timeout error 

> TimeoutError: Timeout exceeded while waiting for event

**Comment by Kalliser** [comment]
Here are some info after some try it seems react when using element.tap instead of element.click

It's definitively not a bug from puppeteer, but maybe you can consider to use throw tap events when use click method in a touch context.

**Comment by aslushnikov** [comment]
> It's definitively not a bug from puppeteer, but maybe you can consider to use throw tap events when use click method in a touch context.

@Kalliser in fact, click events are very much legit in a touch context. One can connect a mouse to an android, and certain accessibility tools might emit clicks in touch contexts - so in general websites *should* react on clicks even when opened on touch-enabled screens.

Puppeteer works as expected; the website doesn't :-)  Thanks for reaching out and filing bugs!
