### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by jnyheim** [puppeteer/puppeteer#4291]
* Puppeteer version: 1.14.0
* Platform / OS version: Windows 10
* URLs (if applicable): https://kongsberg.komune.no
* Node.js version: 11.4.0

**What steps will reproduce the problem?**
goto page with subdomain

_Please include code that reproduces the issue._

`
    (async() => {

        // Launch the puppet.
        const browser = await puppet.launch({});

        // Await new page.
        const page = await browser.newPage();

        // Goto desired domain, defined in query.
        await page.goto(query, {waitUntil : 'networkidle2' });  in error log =>(c_sniffer.js:32:20)

        // Await cookies
        let response = await page._client.send('Network.getAllCookies');

        // Send response.
        res.json(await response);

        // Log event.
        console.log(`[PIG - INFO] - [server] responded to request from IP (${ip}) on destination (${query})`)
      
    })();`

**What is the expected result?**
JSON data containing cookies, works on non sub domains

**What happens instead?**
(node:78004) UnhandledPromiseRejectionWarning: Error: net::ERR_NAME_NOT_RESOLVED at https://kongsberg.komune.no
    at navigate (C:\Users\HIDDEN\node_modules\puppeteer\lib\FrameManager.js:101:37)    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\HIDDEN\node_modules\puppeteer\lib\helper.js:110:27)
    at Page.goto (C:\Users\HIDDEN\node_modules\puppeteer\lib\Page.js:656:49)
    at Page.<anonymous> (C:\Users\HIDDEN\node_modules\puppeteer\lib\helper.js:111:23)
    at C:\Users\HIDDEN\lib\c_sniffer.js:32:20
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:78004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment]
@jnyheim The error you get here is because navigation to https://kongsberg.komune.no fails. This happens because the website is indeed fails to load for me in browser - so I don't see any problems with this.

**Comment by fouad-j** [comment]
`await page.goto(query, {waitUntil : 'networkidle2' }).catch(e => void 0);`

this will fix your issue

**Comment by JavaScriptDude** [comment]
I hit this same issue and it definitely was an issue with the website not working in chrome and not Puppeteer. I my case, it was loading `https://example.org` which loads fine in Firefox, my default browser, but it strangely does not load in chrome.

I get the error: `net::ERR_NAME_NOT_RESOLVED at https://example.org`

**Comment by tears-catcher** [comment]
> `await page.goto(query, {waitUntil : 'networkidle2' }).catch(e => void 0);`
> 
> this will fix your issue

You are my man .. cool bro
