### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by okeul** [puppeteer/puppeteer#4293]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: 10.13.6
* Node.js version: 11.0.0

**What steps will reproduce the problem?**

```js
const main = async url => {
  let browser;
  let results;
  let page;
  let handle;

  // Setup Puppeteer
  browser = await puppeteer.launch({
    args: [
      '--no-sandbox',
      '--headless',
      '--disable-gpu',
      '--window-size=1920x1080'
    ]
  });

  // Get new page
  page = await browser.newPage();

  // To handle a promise rejection
  process.on('unhandledRejection', (reason, p) => {
    console.error('Unhandled Rejection at: Promise', p, 'reason:', reason);
    browser.close();
  });

  await page.goto(url, {
    timeout: 0
    waitUntil: 'networkidle0'
  });

  // Destroy the handle & return results.
  await handle.dispose();

  await browser.close();
  return results;
};

main(url).then(result => {
  // stuff
});
```
**What is the expected result?**

No errors.

**What happens instead?**

```
net::ERR_CONNECTION_TIMED_OUT
```

**Comment by aslushnikov** [comment]
@okeul your website is not reachable - so you get the `ERR_CONNECTION_TMIED_OUT` error. Try navigating to the URL manually and see if it works. If not - make sure your host environment is connected to the internet. 

Hope this helps.

**Comment by okeul** [comment]
Yes it works manually so I don't understand why I get this error.

**Comment by aslushnikov** [comment]
@okeul if you share a URL we'd be able to look more into that. But again, in almost all cases like these the issue happens due to the host environment problems that can't access the URL.

**Comment by okeul** [comment]
@aslushnikov Thanks you, it was a proxy issue.

**Comment by Emanoel-Alves** [comment]
> @aslushnikov Obrigado, foi um problema de proxy.

Como voce corrigiu?
