### ISSUE TITLE
Page.evaluate does not transfer RexEx

### ISSUE THREAD

**Issue by manishrc** [puppeteer/puppeteer#4296]
### Steps to reproduce
When a Regular expression is passed as an argument to Page.evaluate, it is ignored - while strings, nested objects work just fine.

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: macOS Mojave 10.14.4
* Node.js version: v11.13.0

**What steps will reproduce the problem?**

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
  });
  const page = await browser.newPage();

  const test_object = {hello: 'World!'};
  console.log(
    `\nExpected:`, test_object,
    `\nReceived:`, await page.evaluate(a => a, test_object) // { hello: 'World!' }
  );

  const test_regex = /[0-1a-f]/gi
  console.log(
    `\nExpected:`, test_regex,
    `\nReceived:`, await page.evaluate(a => a, test_regex) // {}
  );

  await browser.close();
})();

```

**What is the expected result?**
Expected RegEx to be transferred to the function.

**What happens instead?**
Function receives an empty object instead.

### Context
- We are building a web scraper that has special rules for each websites
- These rules are passed to Page.evaluate 
- As part of the rules, there are regular expressions too
- This part does not seem to be working.
- As an alternative, we'll have to store RegEx an array of as escaped strings and flags and then convert to regex within the page

**Comment by manishrc** [comment]
Closing issue as it is already mentioned in the docs that the arguments need to be Serializable: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args

**Comment by marsrobertson** [comment]
KNOWN ISSUE

I wrote such a cool use case for you!

```
const puppeteer = require('puppeteer');
const URL  = 'file:///Users/.../www.html';

start();

async function start() {
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 10,
    devtools: true
  });
  page = await browser.newPage();

  await page.goto(URL);
  console.log('Page URL:', page.url());

  // Following instructions: https://github.com/puppeteer/puppeteer/issues/523
  const ret1 = await page.evaluate(() => {
     return window.innerHeight; 
  });
  console.log(ret1);

  const ret2 = await page.evaluate(() => {
    var el = document.querySelector('select');
    var dimensions = el.getBoundingClientRect();
    console.log(dimensions); // will be displayed in the Chromium dev tools
    return dimensions;
  });
  console.log(ret2); // but not in the node console

  const ret3 = await page.evaluate(() => {
    var el = document.querySelector('select');
    var dimensions = el.getBoundingClientRect();
    console.log(JSON.stringify(dimensions));
    return JSON.stringify(dimensions);
  });

  console.log(JSON.parse(ret3));
}
```
