### ISSUE TITLE
Unable to run coverage report on actual website

### ISSUE THREAD

**Issue by SwetlinaSatpathy** [puppeteer/puppeteer#4297]
Hi,

I have recently started using puppeteer for my frontend project.
Want to run coverage report. Tried using the example in https://github.com/bcoe/puppeteer-to-istanbul-example
But this solution works for static js file as in example.
When I replace the URL with some website URL, it doesn't work.

code -

```js
const path = require('path')
const pti = require('puppeteer-to-istanbul')

;(async () => {
  const puppeteer = require('puppeteer')
  const browser = await puppeteer.launch()
  const page = await browser.newPage()

  // Enable both JavaScript and CSS coverage
  await Promise.all([
    page.coverage.startJSCoverage(),
    page.coverage.startCSSCoverage()
  ])

  // Navigate to page
  let url = 'file:///' + path.resolve('./index.html')  
  // await page.goto(url);
  await page.goto('https://www.google.com');

  // Disable JavaScript coverage
  const jsCoverage = await page.coverage.stopJSCoverage()
  pti.write(jsCoverage)
  await browser.close()
})()
```
I get the below error -

(node:132032) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\Puppeteer\puppeteer-code-coverage-on-google.nyc_output\js\m=sb_wiz,aa,abd,async,dvl,foot,ifl,lu,m,mu,sf,spch,wft,xz7cCd,fEVMic?xjs=s1.js'

image
image

My repo link - https://github.com/SwetlinaSatpathy/puppeteer-code-coverage-on-google

**Comment by aslushnikov** [comment]
@SwetlinaSatpathy your code works flawlessly for me on Linux, but given your error it looks there are some issues with Windows paths.

I'd speculate that [these lines in puppeteer-to-istanbul source](https://github.com/istanbuljs/puppeteer-to-istanbul/blob/ff6de40249b1391b66d12efb1f38faa3757bfb6f/lib/puppeteer-to-istanbul.js#L31-L32) look suspicious to me and probably need to be updated to support windows. 

I see you filed it downstream as https://github.com/istanbuljs/puppeteer-to-istanbul/issues/27 - closing this in favor of that bug.
