### ISSUE TITLE
Proxy Server not detected using Puppeteer

### ISSUE THREAD

**Issue by agussetyar** [puppeteer/puppeteer#4301]
Hi, I'm using proxy server and trying to check if proxy already successfully connect or not.

This is my code

```
browser = await puppeteer.launch({
            headless: false,
            ignoreHTTPSErrors: true,
            args: [
                `--proxy-server=**https**=IP_PROXY:PORT`,
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--media-cache-size=0', 
                '--disk-cache-size=0',  
            ]
        });
```
i had change to other protocol like http, https, socks4, socks5. While testing and opened that page, its not detected using proxy.

Whats the problem?

**Comment by xse** [comment]
Hey, you're not supposed to use `--proxy-server=**https**=IP_PROXY:PORT`,` i mean the "= =" thingy.
Have a look at #4242.
Have a good day!

**Comment by aslushnikov** [comment]
I believe @xse spotted the issue correctly.
