### ISSUE TITLE
Evaluation failed: ReferenceError: axe is not defined

### ISSUE THREAD

**Issue by spencerpowell** [puppeteer/puppeteer#4302]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 
* Platform / OS version: macOS 10.14.1
* URLs (if applicable):
* Node.js version: v8.9.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `const axe = require('axe-core');
     global.checkAccessibility = async (populatedPage) => {
    const { violations } = await populatedPage.evaluate(() => axe.run());`
2. `it('navigates to event selector', async () => {
            try {
                await checkAccessibility(page);
            }
       });`
3.

**What is the expected result?**
Should run 

**What happens instead?**
Get `Evaluation failed: ReferenceError: axe is not defined`

**Comment by aslushnikov** [comment]
@spencerpowell there's some confusion related to execution contexts.

When we talk about puppeteer and javascript execution, we usually consider 2 contexts: 
- one is **node.js context**. Here you have all your node.js world with Puppeteer library and requires.
- another one is **page context**. You get there using [`page.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-pageevaluatepagefunction-args) and similar methods from Puppeteer API. Functions you pass to these methods are stringified, passed over the wire to the browser, and then executed there.

In you example, you require `axe` in node.js context, but expect it to be defined in page's context. This won't happen automatically: if you want to have something defined in page,  you'd need to inject it there somehow.

Hope this helps!

**Comment by spencerpowell** [comment]
@aslushnikov Thanks for the info.  However, I'm still seeing an issue.  I changed the code to the following per your suggestion:
`const { violations } = await populatedPage.evaluate((axeVar) => axeVar.run(), axe);`

Now I see the error: 
TypeError: Converting circular structure to JSON Are you passing a nested JSHandle?
        at JSON.stringify (<anonymous>)

      26 | const axe = require('axe-core');
      27 | global.checkAccessibility = async (populatedPage) => {
    > 28 |     const { violations } = await populatedPage.evaluate((axeVar) => axeVar.run(), axe);

I have tried with `evaluateHandle` as well, but get the same error

**Comment by aslushnikov** [comment]
@spencerpowell ah, the `axe` is not serializable - that's a requirement for the values passed with [`page.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-pageevaluatepagefunction-args)

Instead, you should include it in the page using [`page.addScriptTag`](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-pageaddscripttagoptions)

**Comment by spencerpowell** [comment]
@aslushnikov Thanks that did the trick!  I appreciate the helpful responses you gave me
