### ISSUE TITLE
Question: What is missing for content script testing? 

### ISSUE THREAD

**Issue by pyrho** [puppeteer/puppeteer#4306]
The API documentation states
> NOTE It is not yet possible to test extension popups or content scripts.

I would like to know what is missing for this to work? Is it missing API in puppeteer? Or missing API on Chromium's part?

From what I gathered, when loading an extension, the content script is properly injected on pages, but it seems like the `chrome.runtime.connect` API is not exposed by the browser.

Thank you!

**Comment by aslushnikov** [comment]
> I would like to know what is missing for this to work? Is it missing API in puppeteer? Or missing API on Chromium's part?

@pyrho we'd like to add a Puppeteer API that surfaces extensions for different browser contexts.
Things that are missing:
- support `extensionId` -> `extensionName` matching. In general, DevTools protocol lacks inspections for extensions.
- support clicking on extension action buttons - #2486. This should be added to CDP as well.
- surface content script execution contexts - #1215. This doesn't require anything from CDP, and it'll be probably fixed together with #2671.

Hope this answers your questions!
