### ISSUE TITLE
ElementHandle.Type types with the different speed time in v1.12.2

### ISSUE THREAD

**Issue by andrewkhoroshev** [puppeteer/puppeteer#4308]
Hello, everyone, I really hope that someone will be able to help me with this issue:

Well, I'm having troubles with elementHandle.type because it types string variables in Input sides all the time with the diffrent speed and I'm really do not know why it works like this. The text can be typed into the input as fast as it only could be, but then text typed into this input one character by one character and it lasts for 3-4 seconds.

I'm using this code:
`await page.type(inputSelector, text);`

There is no slowMo, there is no global delay, so I'm realy confused about this.

**Comment by aslushnikov** [comment]
@anDDDy we'd need to debug this locally to see what's going on. Can you share a small script that reproduces the issue?

**Comment by JoelEinbinder** [comment]
If you are typing a large amount of text, like a few kilobytes, it could take that amount of time.

If you don't care about actual key presses, you can use `page.keyboard.sendCharacter(text)` to do something akin to pasting in the text. That will be almost instantaneous.

**Comment by olizh** [comment]
> If you are typing a large amount of text, like a few kilobytes, it could take that amount of time.
> 
> If you don't care about actual key presses, you can use `page.keyboard.sendCharacter(text)` to do something akin to pasting in the text. That will be almost instantaneous.

Thanks a lot! That is exactly what I'm looking for. You are a hero!
