### ISSUE TITLE
Unable to send POST request, always sending GET request.

### ISSUE THREAD

**Issue by PratsBhatt** [puppeteer/puppeteer#4309]
### Steps to reproduce
```
await page.setRequestInterception(true);
 page.on('request', request => {
const overrides = {
        method: 'POST',
        postData: 'testurlid=5'
};
request.continue(overrides);
});
return page.goto(BASE_URL + '/testURL');
```
**Tell us about your environment:**

* Puppeteer version: "puppeteer": "^1.14.0-next.1555141000741"
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**
Normally updating the GET request to POST doesn't work.
_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
Expected result is that Puppeteer does a post request successfully.

**What happens instead?**
It sends a GET request.

**Comment by JoelEinbinder** [comment]
Did this work for you with a previous version of puppeteer?

**Comment by aslushnikov** [comment]
@PratsBhatt seems to be working for me - just added a test that does exactly this and passes all bots.
If you have a good repro, we'd be happy to look into this.

Speculatively closing for now.

**Comment by PratsBhatt** [comment]
@JoelEinbinder Yes it didn't work for me with the previous version.

@aslushnikov, I would try to create a repo. But It doesn't work for me. I get always GET request, even when I print the request after the .continue method.

**Comment by aslushnikov** [comment]
>  I would try to create a repo. But It doesn't work for me. I get always GET request, even when I print the request after the .continue method.

@PratsBhatt The `request.method()` doesn't get updated when you override the method with `request.continue({method: 'POST'})` call. However, the server does receive a POST request.

**Comment by Charles-Goodwin** [comment]
I don't think this issue should be closed
I'm adopting screen scraping to collect data by trying to emulate a search request to various web sites
This invariably means performing a post request using form data fields as my search criteria
However Puppeteer doesn't provide a conventional way of pragmatically sending POST requests
As a workaround, you can utilise the request interruption which at best works 8/10 times when interrogating third party website that you have no control over.
You are also rendered blind when debugging Puppeteer POST network traffic using Chrome devtools as POSTs are recognised as Request Method:GETs with the form data hidden - not nice!
I'm currently entertaining two alternative workarounds:
Simply navigate to the search page using puppeteer, automate populating the form fields and emulate clicking the search button
Drawback - Causes a double hit to the third party website
Or
Build a scaled down version of the HTML search page on the fly using puppeteer with just the bear essential form data fields and emulate clicking the search button
Drawback - What a faff - but at least the debugging should work fine!

**Comment by nhhockeyplayer** [comment]
I am limited too hitting brick wall...

cannot penetrate API
need to refab req body, do intercept
graphQL is messy
and click search button just isnt rendering off of JSON api's

they need to produce some more real world formidable api examples requiring post or redesign the whole interface
