### ISSUE TITLE
exposeFunction very slow with large object argument 

### ISSUE THREAD

**Issue by AlexVestin** [puppeteer/puppeteer#4311]
### Steps to reproduce
Call exposeFunction with large object

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.14.0/Prebuild version 5.1.2
* Platform / OS version: 18.04.2 LTS
* URLs (if applicable): 
* Node.js version: v8.10.0

_Please include code that reproduces the issue._

pup.js
```JavaScript
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.exposeFunction('__addImageData', data => { });
    await page.goto('file:///path/to/index.html');
    await page.evaluate(() => {        
        for(var i = 0; i < 600; i++) {
            console.log(i);
            window.__draw();
        }
    })
    await browser.close();
  })();
```
index.html
```html
<!doctype html>
<html>
<head></head>
<body>
    <script>
        window.__draw = function() {
            var data = new Uint8Array(1280*720*4);
            window.__addImageData(data);
        }
    </script>
</body>
</html>
```
**What is the expected result?**
Relatively fast running code
**What happens instead?**
Each call to window.__addImageData takes ~1 second. Calling the function without 
the data is near instant. 

Is there another way to pass large objects to exposed functions?

**Comment by JoelEinbinder** [comment]
Right now data is passed between Puppeteer and Chromium via JSON.stringify, actually more than one JSON.stringify. It is usually pretty fast, but as you have seen with a large amount of data it can be slow. If you have to pass a large amount of data quickly between puppeteer and the page, you could link into setting up a parallel WebSocket connection between the page and Node. That will allow you to send binary data.

We are looking into removing those JSON.stringifys in puppeteer, but it will be a long time before they all go away. And even then, this use case might not be as fast as setting up your own connection in parallel.

**Comment by AlexVestin** [comment]
The websocket implementation is a good idea, however it was a bit too slow for what I am going for.
I poked around a bit in the source code,  is there a way for the chrome process to write back a `Uint8Array buffer` instead of a string? 

I'll close this as it is out of the scope for Puppeteer and more related to the chrome DevTools Protocol
