### ISSUE TITLE
Chromium  won't launch

### ISSUE THREAD

**Issue by imadyaici** [puppeteer/puppeteer#4313]
**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: Debian GNU/Linux 9.8 (stretch)
* Node.js version: 11.14.0

I installed the dependencies and the missing packages for debian, but when I lau
nch the script it gives me this error

**`(node:25816) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/opt/weather.com_scraper/node_modules/puppeteer/.local-chromium/linux-641577/chrome-linux/chrome: 1: /opt/weather.com_scraper/node_modules/puppeteer/.local-chromium/linux-641577/chrome-linux/chrome: Syntax error: word unexpected (expecting ")")

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/opt/weather.com_scraper/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/opt/weather.com_scraper/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:198:15)
    at Interface.close (readline.js:394:8)
    at Socket.onend (readline.js:172:10)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:25816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`**

**Comment by aslushnikov** [comment]
@imadyaici so what is your script?

**Comment by imadyaici** [comment]
@aslushnikov I fixed the problem by removing the '--no-sandbox' flag
