### ISSUE TITLE
Make golden tests ignore new lines differences

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#4315]
I have a few tests throwing errors because Chrome is returning `\r\n` instead of `\n` on windows.

How about changing `toBeGolden` to strip out new lines?

```
2) Chromium Browser Page Response.text should work (network.spec.js:159:5)
  Message:
    expect.toBe failed: {"foo": "bar"}
 == {"foo": "bar"}

  Stack:
    Error: expect.toBe failed: {"foo": "bar"}
     == {"foo": "bar"}

        at applyMatcher (C:\source\open-source\puppeteer\utils\testrunner\Matchers.js:48:15)
        at it (C:\source\open-source\puppeteer\test\network.spec.js:161:37)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

3) Chromium Browser Page Response.text should return uncompressed text (network.spec.js:163:5)
  Message:
    expect.toBe failed: {"foo": "bar"}
 == {"foo": "bar"}

  Stack:
    Error: expect.toBe failed: {"foo": "bar"}
     == {"foo": "bar"}

        at applyMatcher (C:\source\open-source\puppeteer\utils\testrunner\Matchers.js:48:15)
        at it (C:\source\open-source\puppeteer\test\network.spec.js:167:37)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

4) Chromium Browser Page JSCoverage should work with conditionals (coverage.spec.js:90:5)
  Message:
    expect.toBeGolden failed: jscoverage-involved.txt mismatch! Output is saved in "output-chromium" directory
  Stack:
    Error: expect.toBeGolden failed: jscoverage-involved.txt mismatch! Output is saved in "output-chromium" directory
        at applyMatcher (C:\source\open-source\puppeteer\utils\testrunner\Matchers.js:48:15)
        at C:\source\open-source\puppeteer        at C:\source\open-source\puppeteer        at C:\source\open-source\puppeteer\test\coverage.spec.js:94:82
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

5) Chromium Browser Page CSSCoverage should work with complicated usecases (coverage.spec.js:169:5)
  Message:
    expect.toBeGolden failed: csscoverage-involved.txt mismatch! Output is saved in "output-chromium" directory
  Stack:
    Error: expect.toBeGolden failed: csscoverage-involved.txt mismatch! Output is saved in "output-chromium" directory
        at applyMatcher (C:\source\open-source\puppeteer\utils\testrunner\Matchers.js:48:15)
        at C:\source\open-source\puppeteer        at C:\source\open-source\puppeteer        at C:\source\open-source\puppeteer\test\coverage.spec.js:173:82
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by aslushnikov** [comment]
> I have a few tests throwing errors because Chrome is returning \r\n instead of \n on windows.

@kblok Interesting. We do run tests on Appveyour - and they run just fine. How can it be?

**Comment by kblok** [comment]
It turns out that I have [core.autocrlf](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) in true. What seems to be the default in Windows.
AppVeyor is setting that to input explicitly. [see](https://www.appveyor.com/docs/windows-images-software/#version-control-systems).

Long story short it will turn `\n` into `\r\n` get I read text from git and will work the other way around when I push code to GitHub. This is great, but as Chrome returns `\n` as new lines, tests are failing.

From now on it's up to you 😛 
 * We could say, whatever Dario, change that setting.
 * We could document the need of setting that value right in the contributing file.
 * We could improve `toBeGolden` to support these differences.

**Comment by aslushnikov** [comment]
> We could improve toBeGolden to support these differences.

This would loosen the assertions, making it more "magical" - I don't like it

> We could document the need of setting that value right in the contributing file.

This sounds good! It'll also embrace a similar setup for all our contributors.

Would you mind sending a PR? You might have a good idea on what to say in CONTRIBUTING.MD since you're going through this right now.

**Comment by kblok** [comment]
Will do!
