### ISSUE TITLE
Puppetter instalation fails on CentOS 7.6

### ISSUE THREAD

**Issue by yami12376** [puppeteer/puppeteer#4316]
While doing steps from: https://jsreport.net/learn/centos
i have problem with puppeter.

* Puppeteer version: 1.14.0
* Platform / OS version: CentOS 7.6.1810
* Node.js version: v8.11.3 (npm 5.6.0)

`node -v`

> v8.11.3

` npm install puppeteer jsreport-chrome-pdf`

> 
> > puppeteer@1.14.0 install /opt/jsreportapp/node_modules/puppeteer
> > node install.js
> 
> sh: node: command not found
> npm WARN jsreport-server@ No description
> npm WARN jsreport-server@ No repository field.
> npm WARN jsreport-server@ No license field.
> 
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! puppeteer@1.14.0 install: `node install.js`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the puppeteer@1.14.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 

Info from log:

1013 warn jsreport-server@ No description
1014 warn jsreport-server@ No repository field.
1015 warn jsreport-server@ No license field.
1016 verbose stack Error: puppeteer@1.14.0 install: `node install.js`
1016 verbose stack spawn ENOENT
1016 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
1016 verbose stack     at emitTwo (events.js:126:13)
1016 verbose stack     at ChildProcess.emit (events.js:214:7)
1016 verbose stack     at maybeClose (internal/child_process.js:925:16)
1016 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1017 verbose pkgid puppeteer@1.14.0
1018 verbose cwd /opt/jsreportapp
1019 verbose Linux 3.10.0-957.el7.x86_64
1020 verbose argv "/root/.nvm/versions/node/v8.11.3/bin/node" "/root/.nvm/versions/node/v8.11.3/bin/npm" "install" "puppeteer"
1021 verbose node v8.11.3
1022 verbose npm  v5.6.0
1023 error file sh
1024 error code ELIFECYCLE
1025 error errno ENOENT
1026 error syscall spawn
1027 error puppeteer@1.14.0 install: `node install.js`
1027 error spawn ENOENT
1028 error Failed at the puppeteer@1.14.0 install script.
1028 error This is probably not a problem with npm. There is likely additional logging output above.
1029 verbose exit [ 1, true ]

**Comment by aslushnikov** [comment]
@yami12376 can you please file this over to https://github.com/jsreport/jsreport-chrome-pdf?

**Comment by yami12376** [comment]
But it is puppeter error,

Ansible steps:

`---
- hosts: localhost
  vars:
    node_version: 8.11.3
    nvm_version: 0.33.11

  tasks:

    - name: install wget
      yum:
        name: wget
        state: latest

    - name: download nvm
      get_url:
        url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
        dest: /opt/nvm-install.sh

    - name: Changing perm of "/opt/nvm-install.sh", adding "+x"
      file:
        dest: /opt/nvm-install.sh
        mode: "a+x"

    - name: Execute the script
      command: /opt/nvm-install.sh
      args:
        creates: ~/.nvm/nvm.sh

    - name: Changing perm of "~/.nvm/nvm.sh", adding "+x"
      file:
        dest: ~/.nvm/nvm.sh
        mode: "a+x"

    - name: install node
      shell: |
        . ~/.nvm/nvm.sh
        nvm install {{ node_version }}
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}"

    - name: install jsreport-cli
      shell: |
        . ~/.nvm/nvm.sh
        npm install jsreport-cli -g
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}/lib/node_modules/jsreport-cli"
        
    - name: install puppeteer 
      shell: |
        . ~/.nvm/nvm.sh
        npm install puppeteer  -g
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}/lib/node_modules/puppeteer "        
        
    - name: install jsreport-chrome-pdf
      shell: |
        . ~/.nvm/nvm.sh
        npm install jsreport-chrome-pdf -g
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}/lib/node_modules/jsreport-chrome-pdf"            

    - name: create jsreportapp directory
      file:
        path: ./jsreportapp
        state: directory

    - name: init jsreportapp directory
      shell: |
        . ~/.nvm/nvm.sh
        jsreport init
      args:
        chdir: ./jsreportapp
        creates: ./package-lock.json`

Starting playbook with sudo.
I get an error on step 

> install puppeteer

> 

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ". ~/.nvm/nvm.sh\n npm install puppeteer -g", "delta": "0:00:04.038035", "end": "2019-04-23 11:29:56.050625", "msg": "non-zero return code", "rc": 1, "start": "2019-04-23 11:29:52.012590", "stderr": "sh: node: command not found\nnpm ERR! file sh\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno ENOENT\nnpm ERR! syscall spawn\nnpm ERR! puppeteer@1.14.0 install: `node install.js`\nnpm ERR! spawn ENOENT\nnpm ERR! \nnpm ERR! Failed at the puppeteer@1.14.0 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2019-04-23T09_29_56_035Z-debug.log", "stderr_lines": ["sh: node: command not found", "npm ERR! file sh", "npm ERR! code ELIFECYCLE", "npm ERR! errno ENOENT", "npm ERR! syscall spawn", "npm ERR! puppeteer@1.14.0 install: `node install.js`", "npm ERR! spawn ENOENT", "npm ERR! ", "npm ERR! Failed at the puppeteer@1.14.0 install script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /root/.npm/_logs/2019-04-23T09_29_56_035Z-debug.log"], "stdout": "\n> puppeteer@1.14.0 install /root/.nvm/versions/node/v8.11.3/lib/node_modules/puppeteer\n> node install.js", "stdout_lines": ["", "> puppeteer@1.14.0 install /root/.nvm/versions/node/v8.11.3/lib/node_modules/puppeteer", "> node install.js"]}
