### ISSUE TITLE
update the api doc for uploadFile

### ISSUE THREAD

**Issue by nbwsc** [puppeteer/puppeteer#432]
the `uploadFile` api is in the `Page`/`FrameManager` class instead of `ElementHandle`
and the param is `(selector, ...filePaths)` instead of `(...filePaths)`,
which made me confused.

**Comment by aslushnikov** [comment]
Currently, the documentation refers to tip-of-tree.

The 0.9.0 documentation could be found at: https://github.com/GoogleChrome/puppeteer/blob/v0.9.0/docs/api.md

**Comment by nbwsc** [comment]
:+1:
