### ISSUE TITLE
Option to not kill Chromium instance

### ISSUE THREAD

**Issue by molant** [puppeteer/puppeteer#4322]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Windows 10
* URLs (if applicable): N/A
* Node.js version: 10.15.3

**Some context**

We are creating a [`connector-chromium` on webhint using puppeteer](https://github.com/webhintio/hint/issues/2200).
One of the issues I've found is that as soon as the process is finished, the chromium instance gets closed immediately. This is a problem for our testing suite:

- We use ava so multiple tests are run in parallel
- We reuse chromium instances to use less processes

After some testing it looks like the problem is that `detached` is `false` only on Windows. That was changed in https://github.com/GoogleChrome/puppeteer/pull/2081 which means that even if I change the `handleSIGXXX` properties to`false`, the browser is always going to get closed.

I see that right after there are quite a few listeners to close chromium instances so maybe this exception to the Windows platform is not needed any more?

Also, from the [node docs](https://nodejs.org/api/child_process.html#child_process_options_detached):

> On Windows, setting `options.detached` to `true` makes it possible for the child process to continue running after the parent exits. The child will have its own console window. Once enabled for a child process, it cannot be disabled.

**What steps will reproduce the problem?**

Run the following on a Windows machine:

```js
const pup = require('puppeteer-core');

const startPup = async () => {
    const browser = await pup.launch({
        handleSIGHUP: false,
        handleSIGINT: false,
        handleSIGTERM: false,
        headless: false
    });

    const page = await browser.newPage();
};

startPup();
```

And once the browser has 2 tabs opened press Ctrl+C in the terminal so the node process ends.

**What is the expected result?**

The browser to remain opened (this is what happens on macOS for example).

**What happens instead?**

The browser gets closed 😢

**Comment by aslushnikov** [comment]
@molant Puppeteer takes ownership over the chromium instance it launches; as a Puppeteer user, you'd expect that Chromium instance doesn't outlive the node.js script. This detaching is one of the measures we do to ensure this; signal handling is orthogonal to this.

Can you please explain one more time what do you do with ava and why do you want Chromium to outlive it's parent node.js process?

**Comment by molant** [comment]
> you'd expect that Chromium instance doesn't outlive the node.js script.

Right now Chromium can outlive in one platform with the right configuration (macOS and I suspect LInux too) and not the other (Windows). If it were the same behavior in all platforms I'd look for a workaround  but that's not the case so that's the reason I opened the issue 😊

> Can you please explain one more time what do you do with ava and why do you want Chromium to outlive it's parent node.js process?

Sure! We have a few hundred tests in our project. Each one spawns a lighweight server and a browser to connect to it, download the content and do some validations. Right now we connect to the test server using the debugging protocol and jsdom. We would like to migrate the debugging protocol to puppeteer because it allows us to do some things more easily.

Going back to our particular scenario, to speed up the testing, [`ava`](https://github.com/avajs/ava) runs tests in parallel in different processes. Calling `pupeteer.launch()` on each test is not viable because it slows down things a lot and computer fans start spinning really fast... Switching to run tests serially also will take a lot of time.

What we are doing with the debugging protocol right now (and what we would like to duplicate with puppeteer) is to have some logic that checks if there's a valid process already running and then connect to it (and if not open a new browser). Instead of creating a new Chromium instance it just creates a new tab which is a lot faster and requires less resources.

Hope this makes sense!

**Comment by aslushnikov** [comment]
> Right now Chromium can outlive in one platform with the right configuration (macOS and I suspect LInux too) and not the other (Windows). If it were the same behavior in all platforms I'd look for a workaround but that's not the case so that's the reason I opened the issue 😊

@molant ah! Fair. Sorry I didn't get it from the description. Long story short: we ended up with "detached: false" on windows after many attempts to fix runaway Chromium instances. This seemed to be the only way to handle many scenarios, e.g. closing terminal window while puppeteer script was running.

> What we are doing with the debugging protocol right now (and what we would like to duplicate with puppeteer) is to have some logic that checks if there's a valid process already running and then connect to it (and if not open a new browser). Instead of creating a new Chromium instance it just creates a new tab which is a lot faster and requires less resources.

Instead of launching a chromium process, can you run a small node.js process that runs Chromium for you?

```js
const pptr = require('puppeteer');
(async () => {
  const browser = await pptr.launch();
  console.log(browser.wsEndpoint()); // log ws endpoint to stdout
})()
```

**Comment by molant** [comment]
> Instead of launching a chromium process, can you run a small node.js process that runs Chromium for you?

I was thinking to switch to `chrome-launcher` which doesn't have this problem so I don't have to launch another process. In any case this would be a workaround just for an specific platform and I still will have to close Chromium properly when all the tests have finished so there's that extra complexity.

What about having the default as it is right now but if a user sets the `handleSIG***` to `false` on Windows then `detached` is `true`? I think that will be a strong enough signal that the user knows what they are doing and it will still preserve the right behavior you want for more scenarios in Windows. Would that seem reasonable? The other option would be to make it configurable and default to what it is right now. Happy to contribute with a PR by the way with either approach.

**Comment by molant** [comment]
So after a bit more testing Chromium wasn't getting killed if I pressed `Ctrl+C` in the process but if I run `process.exit()` then I gets closed because of [`killChrome()`](https://github.com/GoogleChrome/puppeteer/blob/06fdcaeeecac0d137ee34c7da715ca4105ff1771/lib/Launcher.js#L203). So now my request has changed to have an option to make Chromium `outlive` (or a better name) the process that should be `false` by default.

When set to `true` it will:
* Change to `detached: true` for `win32` platforms
* Not run the following code in `killChrome`

```js
if (chromeProcess.pid && !chromeProcess.killed && !chromeClosed && !outlive) {
  // Force kill chrome.
  try {
    if (process.platform === 'win32')
      childProcess.execSync(`taskkill /pid ${chromeProcess.pid} /T /F`);
    else
      process.kill(-chromeProcess.pid, 'SIGKILL');
  } catch (e) {
    // the process might have already stopped
  }
}
```

@aslushnikov thoughts about this?

**Comment by EricTetz** [comment]
> Can you please explain one more time what do you do with ava and why do you want Chromium to outlive it's parent node.js process?

I'm not the OP, but this is an important feature for our use case: iterative script development.

We have a huge and complicated SPA application (EMR ported from desktop). Our workflows require a lot of steps. Let's say it takes 30 clicks to get to a particular place in the app that I want to script.  I don't want to have to relaunch the browser and re-run all preceding 30 steps every time I add a few new lines of code. I want to write a few lines of code, running them against the existing browser, without resetting its state, get that code working correctly, then wash, rinse, repeat, iteratively building up a large and complicated script.

We do this today in Selenium but are evaluating Puppeteer because Selenium has speed and reliability issues.

**Comment by EricTetz** [comment]
> why do you want Chromium to outlive it's parent node.js process?

I'm not the OP, but this is an important feature for our use case: iterative script development. We do this today in Selenium but are evaluating Puppeteer because Selenium has speed and reliability issues.

We have a huge and complicated SPA application (EMR ported from desktop). The unpacked build takes a long time to load and our test cases require a lot of steps. We can develop scripts much faster with a tight, REPL-like workflow against an open browser session, where we get the app in the state we want, write a few lines of code, run that code against the open browser without resetting it, write the next few lines of code, run them against the open browser, etc. We can iteratively build up complicated scripts without re-executing all the preceding steps every time we add a few lines.

**Comment by arturohernandez10** [comment]
@molant Is this still an issue? Could you share more of your code. I think this is useful for our case. The legacy app we have takes a long time to JIT the source code.

**Comment by molant** [comment]
Haven't tested in the latest versions but I think this is still an issue. The gist of what I did is to spawn a process that:

- Creates a puppeteer process if none is available and writes down on a file how to connect to the new puppeteer instance via WS
- Connects to a puppeteer process if the information to connect to one is found and it actually works

The implementation is in https://github.com/webhintio/hint/blob/master/packages/connector-puppeteer/src/lib/lifecycle.ts
It exports 2 methods: `launch` (where most of the magic happens) and `close`. Hope it helps!

**Comment by devxpy** [comment]
For pyppeteer users, the `autoClose` option can be used -
```python
browser = await launch(autoClose=False)
```

**Comment by arifali123** [comment]
Can this really be merged I want this feature in my app too thanks
