### ISSUE TITLE
Can waitForResponse take a promise instead of function or url?

### ISSUE THREAD

**Issue by techsin** [puppeteer/puppeteer#4323]
**Tell us about your environment:**

* Puppeteer version: 1.14
* Platform / OS version:  Windows
* Node.js version: 10

**What steps will reproduce the problem?**
try to pass a promise to `await page.waitForResponse(response => condition)`  instead of `urlOrPredicate`.

**What is the expected result?**
expect async function to work

**What happens instead?**
no waiting as promise gets eval to truthy. 

response object has text method which is a promise to use that i need callback to be promise as well.. but if i make callback to be promise it breaks the waitForResponse function

**Comment by aslushnikov** [comment]
@techsin why do you need to return a promise? Can you share an example?

**Comment by techsin** [comment]
i wanted to do response.text() which returns a promise. I wanted to return true or false based on what's inside text(). can't wait for promise to be resolved if original function isn't promise based.

eventually had to go with page.on('response'....

```
        await (new Promise(function (resolve, reject) {
            let listener = async (response) => {
                let url = 'https://www.example.com/';
                if (url == response.url()) {
                    try {
                        let json = JSON.parse(await response.text());
                        if (json.data.abc) {
                            ...
                            page.removeListener('response', listener);
                            resolve();
                        }
                    } catch (error) {
                        console.log(error);
                    }
                }
            };
            page.on('response', listener);
        }));

```

**Comment by techsin** [comment]
there is no way to do this for example

```
await page.waitForResponse(response => await response.text());
```

**Comment by aslushnikov** [comment]
@techsin Well, that's very fair!

**Comment by rodoabad** [comment]
Any update on this?

What about...

```
await page.waitForResponse('/user', () => customBody);
```

@aslushnikov

**Comment by jamesgeorge007** [comment]
@aslushnikov I would love to give it a try :clap: would be great if you could point me to the right files to work with.

**Comment by jamesgeorge007** [comment]
@aslushnikov I would love to give this one a try. It would be great if you could guide me (files to work upon) as I'm new to the code-base.

**Comment by sourabhmozark** [comment]
Hello Everyone,
If you are an Appium tester and want to showcase your skills, here is an amazing opportunity for you! MOZARK’s online global app testing contest- [QAppathon ]( https://aquamark.mozark.ai/QAppAssure/ )is now live!
The contest is free to register, all you need to do is:
• Sign up to MOZARK QAppAssure
• Write an Appium script to measure the Home page load time of your app.
• Run the script on at least 10 devices across the QAppAssure device cloud.
• Ensure a minimum of 50 test runs.
• Send in the logs and a brief description of your test methodology to aquamark-support@mozark.ai
The first 10 testers to successfully complete the challenge will get an Amazon gift voucher worth INR 5k and MOZARK cloud vouchers worth INR 10k!

[Register ](https://aquamark.mozark.ai/QAppAssure/)Now and be a MOZARK certified Appium tester
