### ISSUE TITLE
CSS Coverage not working for @font-face

### ISSUE THREAD

**Issue by anuragphadke** [puppeteer/puppeteer#4324]
**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Mac
* URLs (if applicable): https://webfast.co/pure-amp/build-automation/taggartmediagroup-com/pup.pre.html
1. Visit the above website.
2. Tools -> Coverage -> CSS Coverage (or equivalent via UI)
3. Reload the page

**What is the expected result?**
CSS Coverage should correctly detect that @font-face style tags are used from the https://webfast.co/pure-amp/build-automation/taggartmediagroup-com/_before_pup.css file

**What happens instead?**
None of the @font-face tags are detected as being used.
I also tried running by disabling web-security, same issue, all the @font-face tags show `red` aka unused:

```
const browser = await puppeteer.launch({
  args: [
    '--disable-web-security',
  ],
  headless: false,
});
```

![image](https://user-images.githubusercontent.com/349486/56555979-6b614480-654b-11e9-8214-216e088c23df.png)

**Comment by thalisvilela** [comment]
I'm having the same issue. And for my surprise, i'm trying to use the same font! Bebas Neue. :D
Tried on Linux with no success, but got it working on Windows 7 after i installed the font in the system. Maybe you should try that.

**Comment by anuragphadke** [comment]
any update on this?

**Comment by ivictbor** [comment]
Same for me for the other front (base64 inlined in css font). Causes wrong results in lighthouse
