### ISSUE TITLE
I am seeing the following error when launching puppeteer with chromium in the latest version of chromium

### ISSUE THREAD

**Issue by BrandonCopley** [puppeteer/puppeteer#4328]
Failed to launch chrome! Error relocating /usr/lib/chromium/chrome: FT_Get_Color_Glyph_Layer: symbol not found Error relocating /usr/lib/chromium/chrome: FT_Palette_Select: symbol not found

**Comment by BrandonCopley** [comment]
Alpine Linux

**Comment by BrandonCopley** [comment]
This is how I'm installing dependencies, is there a better way to do this so that I can download a specific version of Chromium?

# Install Puppeteer dependencies
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      harfbuzz@edge \
      nss@edge
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

**Comment by BrandonCopley** [comment]
New install code, not sure when this was updated, but I missed this update.

# Install Puppeteer dependencies
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      nss@edge \
      freetype@edge \
      harfbuzz@edge \
      ttf-freefont@edge
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

**Comment by csaden** [comment]
Ran into the same problem.

Chromium version 73 was the culprit.
https://bugs.archlinux.org/task/62026

Fixed by using alpine-3.9 image and `apk add --no-cache chromium` (not `chromium@edge`)

**Comment by BrandonCopley** [comment]
Did you try updating the install script? or installing the missing packages?

**Comment by pxlrbt** [comment]
Just found this thread after I ran into the same issue trying to get puppeteer to work under an existing alpine-3.8 image.

`apk add --no-cache chromium` - which installs Chromium 68.0.3440.75 - and
`npm i puppeteer@1.4` - which was released for Chromium 68 - did the trick.

**Comment by tahv0** [comment]
> npm i puppeteer@1.4

puppeteer@1.4 have 1 high severity vulnerability

https://npmjs.com/advisories/824
