### ISSUE TITLE
Some requests are not intercepted

### ISSUE THREAD

**Issue by farynam** [puppeteer/puppeteer#4329]
Hello, I'm trying to capture urls from amazon website however  css url interception is troublesome: 

### Steps to reproduce

```js
/**
 * Created by marcin on 16/11/18.
 */
const puppeteer = require('puppeteer');

(async () => {
    const url  = "https://www.amazon.co.uk";
    const browser = await puppeteer.launch(
        {
            headless: false,
            devtools: true,
            args: ['--disable-web-security', '--no-sandbox'],
            defaultViewport: {
                width: 1280,
                height: 839,
                deviceScaleFactor: 1,
                isMobile: false,
                hasTouch: false,
                isLandscape: true
            }
        });
    const page = await browser.newPage();
    page.setViewport({width: 1280, height: 852});

    let initialRequest = true;
    await page.setRequestInterception(true);
    page.on('request', request => {
        //cancel any navigation requests after the initial page.goto
        if (request.isNavigationRequest() && !initialRequest) {
            return request.abort();
        }
        if (request.url().indexOf("css") >= 0) {
            console.log("Req:" +request.url());
        }
        initialRequest = false;
        request.continue();
    });

    await page.goto(url);
})();
```

**Tell us about your environment:**
* Puppeteer version:
puppeteer@1.14.0
* Platform / OS version:
Linux debian9 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64
* URLs (if applicable):
https://images-eu.ssl-images-amazon.com/images/I/41SCCkd-QFL._RC|51giv2WPknL.css,01evdoiemkL.css,01K+Ps1DeEL.css,31bAdTWQ3tL.css,01tgK36lpGL.css,11UGC+GXOPL.css,21LK7jaicML.css,11L58Qpo0GL.css,21EuGTxgpoL.css,01Xl9KigtzL.css,01YhS3Cs-hL.css,21GwE3cR-yL.css,019SHZnt8RL.css,01wAWQRgXzL.css,21bWcRJYNIL.css,11WgRxUdJRL.css,01dU8+SPlFL.css,11ocrgKoE-L.css,01SHjPML6tL.css,111-D2qRjiL.css,01QrWuRrZ-L.css,310Imb6LqFL.css,11Z1a0FxSIL.css,01cbS3UK11L.css,21mOLw+nYYL.css,01L8Y-JFEhL.css_.css?AUIClients/AmazonUI#gb.not-trident

* Node.js version:
v10.15.3
**What steps will reproduce the problem?**
Try to run and check output for mentioned url which is attached to amazon page via link tag. 

**What is the expected result?**
Css url visible on console.

**What happens instead?**
Request is skipped or absent.

**Comment by imbxl** [comment]
Same here. My site load 6 JS files and on('request') method only intercept 3

**Comment by aslushnikov** [comment]
@farynam works for me on Puppeteer 1.17.0. In Puppeteer 1.15.0 we fixed  a [major request interception problem](https://github.com/GoogleChrome/puppeteer/issues/3471) - so I'd expect things to work properly now.

@imbxl please file a separate issue if you see this behavior on latest-and-greatest Puppeteer.
