### ISSUE TITLE
No way to associate Frame object with the <iframe> element it represents

### ISSUE THREAD

**Issue by twalpole** [puppeteer/puppeteer#433]
While attempting to convert Poltergeist from using PhantomJS to Puppeteer I need to select a `Frame` object (returned from `childFrames`) based on the `<iframe>` element which encapsulates it.  Looking through the Puppeteer code I don't see any link between them, or way to generate a link.  Am I missing something, or is this not possible with the functionality provided by the Dev Tools Protocol?

**Comment by pavelfeldman** [comment]
Which way do you need to go?
(a) You traverse the DOM and given the `<iframe>` node you want to evaluate in its context?
(b) You listen to frame added event and would like to get an `<iframe>` node that contains the frame?
(c) both?

**Comment by twalpole** [comment]
@pavelfeldman I need the first (a)

**Comment by aslushnikov** [comment]
For the record: the upstream patch [has landed](https://chromium.googlesource.com/chromium/src/+/b2949a65405c5548c378e4f382f59e00fee9d5ef). This will work out nicely as #382 is done.

**Comment by Madd0g** [comment]
I'm interested in this as well, with regards to the script injection/evaluation capabilities.

Right now there's `evaluateOnNewDocument` and `exposeFunction`, both work on all frames(?), but is there a way of knowing which frame it's working on?

**Comment by aslushnikov** [comment]
> Right now there's evaluateOnNewDocument and exposeFunction, both work on all frames(?), but is there a way of knowing which frame it's working on?

#382 with object handles, you'll be able to pass in the owner document while calling `exposeFunction`.

**Comment by elisherer** [comment]
@aslushnikov, do you have any progress on this matter? 
And if not, would you like me to assist in any way? 
As I understand, the upstream work have been done and is available on the current chromium version?

EDIT: I was able to construct a naive implementation of finding the containing iframe in the parent frame by doing the following (inside ElementHandle.js):
```js
  /**
   * @return {!Promise<ElementHandle>}
   */
  async ownerFrame() {
    if (!this._frame._parentFrame)
      throw new Error('No parent frame');

    const rootElementHandle = await this._frame.$('*');
    const rootElementDescriptionHandle = await this._client.send('DOM.describeNode', { objectId: rootElementHandle._remoteObject.objectId });

    const parentsIframes = await this._frame._parentFrame.$$('iframe');
    if (!parentsIframes.length)
      throw new Error('No iframe elements found in parent');

    return parentsIframes.find(async parentsIframe => {
      const iframeDescription = await this._client.send('DOM.describeNode', { objectId: parentsIframe._remoteObject.objectId, pierce: true, depth: 2 });
      const iframesRootDescription = iframeDescription.node.contentDocument.children[0];
      return iframesRootDescription.backendNodeId === rootElementDescriptionHandle.node.backendNodeId;
    });
  }
```

WDYT?

**Comment by scottweinert** [comment]
Is there a code example answering how to get a frame by selector?

**Comment by pulento** [comment]
+1

**Comment by ohana54** [comment]
I'm interested in the second option:
"(b) You listen to frame added event and would like to get an <iframe> node that contains the frame?"

In my case, I get the frame from `page.frames()`, and at a later stage in code I want to get an attribute from the `<iframe>` tag itself.

**Comment by schelkun** [comment]
I think this is the solution.

ElementHandle method:
```js
  /**
   * @return {!Promise<?Puppeteer.Frame>}
   */
  async getFrame() {
    const nodeInfo = await this._client.send('DOM.describeNode', {
      objectId: this._remoteObject.objectId
    }).catch(error => void debugError(error));

    if (typeof nodeInfo.node.frameId === 'string') {
      for (const frame of this._page.frames()) {
        if (nodeInfo.node.frameId === frame._id)
          return frame;
      }

      return null;
    } else {
      return null;
    }
  }
```

Test script:
```js
const puppeteer = require('puppeteer');

(async() => {
    try {
        const browser = await puppeteer.launch({
            headless: false,
            timeout: 10000
        });

        const page = await browser.newPage();

        await page.setViewport({
            width: 1280,
            height: 800
        });

        await page.goto('https://schelkun.github.io/padding-link/frame.html');

        const frameElement = await page.$('iframe');

        const frame = await frameElement.getFrame();

        const deepElement = await frame.$('iframe');

        const deepFrame = await deepElement.getFrame();

        deepFrame.evaluate(() => {
            document.body.innerHTML = '<span style="color: green;">Done!</span>';
        });

    } catch (e) {
        console.log(e);
    }
})();
```

**Comment by ohana54** [comment]
@schelkun this looks great, thank you! I hope the PR CLA issue will get attention and it will get merged. If you see that it's not progressing, I can try to create a PR as well, with your permission of course.

**Comment by schelkun** [comment]
@ohana54 sure

**Comment by schelkun** [comment]
**UPDATE**

@ohana54 no special PR is required

With https://github.com/GoogleChrome/puppeteer/pull/1972 we can use `elementHandle.executionContext().frame()`. Look at example code:

```js
const puppeteer = require('puppeteer');

(async() => {
    try {
        const browser = await puppeteer.launch({
            headless: false,
            timeout: 10000
        });

        const page = await browser.newPage();

        await page.setViewport({
            width: 1280,
            height: 800
        });

        await page.goto('https://schelkun.github.io/padding-link/frame.html');

        const frameElement = await page.$('iframe');

        const frame = frameElement.executionContext().frame();

        const deepElement = await frame.$('iframe');

        const deepFrame = deepElement.executionContext().frame();

        deepFrame.evaluate(() => {
            document.body.innerHTML = '<span style="color: green;">Done!</span>';
        });

    } catch (e) {
        console.log(e);
    }
})();
```

@aslushnikov with your PR now we have the way to associate `iframe` element with frame, so you can close this.

**Comment by adrianopons** [comment]
Thank you @schelkun, it worked perfectly.

**Comment by ohana54** [comment]
@aslushnikov Thanks!! Can't wait to use it.

**Comment by Madd0g** [comment]
that's an awesome feature. When is the release due?

@aslushnikov - I've haven't tried `exposeFunction` with frames yet. Can you please give me an example of what you mean by:

> #382 with object handles, you'll be able to pass in the owner document while calling exposeFunction.

**Comment by mayankchincholkar** [comment]
Is this released? I am on latest puppeteer-core version 1.13 and cannot see this in.

**Comment by sudofox** [comment]
Hey, I'm pretty new with Puppeteer (and nodejs in general) and am trying to use this to access the contents of an iFrame. It doesn't seem that getFrame is included in the ElementHandle yet on version 1.13, as I get "getFrame is not a function", but I need to get this done soon, so how can I manually add in the function? I've required it and placed it inside a module.exports and tried assigning it to page.getFrame after instantiating the page, but it's not really working too well.

**Comment by vctormb** [comment]
> ```js
> getFrame
> ```

How can I inject the ``getFrame()`` function in frameElement?

**Comment by vctormb** [comment]
@schelkun How can I inject the ``getFrame()`` function in frameElement?

**Comment by sfsr12** [comment]
@vctormb - You don't need to inject it.  It was just implemented as: contentFrame()
```js
const iframeElement = await page.$('#iframe');
const iframe = await iframeElement.contentFrame();
```

**Comment by stephenjesus** [comment]
You can use the elementHandle.contentFrame() function to return a frame from an element handle.

Quote from the docs:

Resolves to the content frame for element handles referencing iframe nodes, or null otherwise

Example:

`const iframeElement = await page.$('#iframe');

const iframe = await iframeElement.contentFrame();`
