### ISSUE TITLE
exposeFunction fails to serialize arguments correctly when toJSON is overridden

### ISSUE THREAD

**Issue by mnmkng** [puppeteer/puppeteer#4334]
Hello,

today I encountered an interesting issue where a specific website would cause `page.exposeFunction()` to stop working properly. The issue lies in arguments being incorrectly serialized or deserialized. See the code examples below.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: MacOS, Linux
* URL: http://erasmus-databaze.naep.cz/modules/erasmus/index.php?page=1
* Node.js version: LTS/Dubnium

**What steps will reproduce the problem?**
```js
const puppeteer = require('puppeteer');

(async function main() {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    await page.exposeFunction('myFunction', async (...args) => {
        console.log(...args);
        for (arg of args) {
            console.log(typeof arg);
        }
    });
    await page.goto('http://erasmus-databaze.naep.cz/modules/erasmus/index.php?page=1');
    await page.evaluate(async () => {
        await myFunction({ x: 1 })
    });

    await browser.close();
})();
```

**What is the expected result?**
```
{ x: 1 }
object
```

**What happens instead?**
```
[ { " x " :   1 } ]
string
string
string
string
string
string
string
string
string
string
```

**Further findings**
It seems that some environment change in the website itself causes the parameters to be incorrectly serialized. It can be seen in the `event.data` variable in `WebSocketTransport`.

```
{"method":"Runtime.bindingCalled","params":{"name":"myFunction","payload":"{\"name\":\"myFunction\",\"seq\":1,\"args\":\"[{\\\"x\\\": 1}]\"}","executionContextId":3}, "sessionId": "D74A031C993D759D5EA29C38C002400F"}
```
The `args` are a `string`, but it should be an `Array`.

When the code above is called for `http://example.com` or mostly any other website, it runs fine.

**Conclusion**
I assume that the problem is caused by the website itself, but I'd expect Puppeteer not to rely on the website's environment to do serialization. I'll try to dig more into how serialization is done in Puppeteer the meantime.

Thank you for your time.

**Comment by mnmkng** [comment]
Ok, quick update. It's most probably due to the `Object.toJSON` function that's in the page's environment. **Deobfuscated** using `jsnice.org`

```js
/**
 * @param {!Object} b
 * @return {?}
 */
function K(b) {
  /** @type {string} */
  var type = typeof b;
  switch(type) {
    case "undefined":
    case "function":
    case "unknown":
      return;
    case "boolean":
      return b.toString();
  }
  if (b === null) {
    return "null";
  }
  if (b.toJSON) {
    return b.toJSON();
  }
  if (H(b)) {
    return;
  }
  /** @type {!Array} */
  var cache = [];
  var prop;
  for (prop in b) {
    var A = K(b[prop]);
    if (!E(A)) {
      cache.push(prop.toJSON() + ": " + A);
    }
  }
  return "{" + cache.join(", ") + "}";
}
;
```

**Comment by mnmkng** [comment]
Perhaps just an omission from https://github.com/GoogleChrome/puppeteer/pull/1098 ?

**Comment by kblok** [comment]
I think this is a problem on the Chromium side.
Checking values on `_onBindingCalled`, we are getting a pure JSON array when we send simple objects. 
```ts 
"{"name":"compute","seq":1,"args":[3,5]}"
```

But when we send a complex object. The arguments are being stringified.
```
"{"name":"myFunction","seq":1,"args":"[{\"x\": 1}]"}"
```

**Comment by kblok** [comment]
We could also do something like this on `_onBindingCalled`

```ts
    let {name, seq, args} = JSON.parse(event.payload);
    let expression = null;

    if (helper.isString(args))
      args = JSON.parse(args);

    try {
      const result = await this._pageBindings.get(name)(...args);
      expression = helper.evaluationString(deliverResult, name, seq, result);
    } catch (error) {
      if (error instanceof Error)
        expression = helper.evaluationString(deliverError, name, seq, error.message, error.stack);
      else
        expression = helper.evaluationString(deliverErrorValue, name, seq, error);
    }
```

**Comment by mnmkng** [comment]
@kblok Thanks for looking into this.

I don't necessarily think that the whole serialization process is wrong, because it works fine for other websites. Here, for `example.com`, serializing nested objects produces correct results:

```js
const puppeteer = require('puppeteer');

(async function main() {
    const browser = await puppeteer.launch({headless: true});
    const page = await browser.newPage();
    await page.exposeFunction('myFunction', async (...args) => {
        console.log(...args);
        for (arg of args) {
            console.log(typeof arg);
        }
    });
    await page.goto('http://example.com');
    await page.evaluate(async () => {
        await myFunction(1, 'string', {
            one: 1,
            obj: {
                nested: 'str',
                arr: [
                    1,
                    2,
                    {hello: 'world'}
                ]
            }
        })
    });

    await browser.close();
})();
```

```
1 'string' { one: 1, obj: { nested: 'str', arr: [ 1, 2, [Object] ] } }
number
string
object
```

**Comment by mnmkng** [comment]
@aslushnikov Any update on this please? I just tested with 1.16 and the issue still persists. I understand that it's an edge case, I just want to know if we should be looking for workarounds on our side because this will not land anytime soon. Thanks.

**Comment by aslushnikov** [comment]
>  I just want to know if we should be looking for workarounds on our side because this will not land anytime soon

@mnmkng this won't land any time soon.

**Comment by mnmkng** [comment]
@aslushnikov Thank you.

**Comment by tszyszko** [comment]
This is certainly still an issue in puppeteer 21.1.0
