### ISSUE TITLE
Feature Request: header/footer template page number literal string injection

### ISSUE THREAD

**Issue by chrisjpatty** [puppeteer/puppeteer#4335]
There are currently several issues related to displaying headers and footers that are different between pages. Here's a non-exhaustive list of related tickets:

#2167
#2089 
[#3383](https://github.com/GoogleChrome/puppeteer/issues/3383)
#2961
#2916 
#2089 
#2484

Many of these issues stem from the lack of JS support in the header and footer templates as discussed in one of my previous issues: #2167. Looking at this list of issues, one of the common use-cases seems to be wanting to display headers or footers differently between pages. I wanted to propose a solution that would alleviate this main use-case while full script interpretation in the templates is still pending.

Currently the header and footer templates allow you to use class names to inject the page number into the html as referenced [here](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-pagepdfoptions). The current CSS spec does not provide a way to select elements based on content, but you can select elements based on _attributes_. My proposal is this: can the templates provide a way to inject the page number as a _literal_ string in the html, and not through a class name. For example, a syntax like this:
```html
<div>
    <h1 data-page="{{pageNumber}}">I only render on the first page</h1>
</div>
``` 
Which would be parsed as:
```html
<div>
    <h1 data-page="1">I only render on the first page</h1>
</div>
``` 
Then using an inline style block, the page could be styled based on this data attribute like so:
```html
<div>
    <style>
        h1{
            display: none;
        }
        h1[data-page="1"]{
            display: block;
        }
    </style>
    <h1 data-page="1">I only render on the first page</h1>
</div>
``` 
If this form of page number injection were possible it would likely alleviate this common use-case. Thanks for everyone's hard work on this product!

**Comment by RockNHawk** [comment]
any solution about this issue?

**Comment by chrisjpatty** [comment]
I've found [in the Chromium source](https://source.chromium.org/chromium/chromium/src/+/master:components/printing/resources/print_header_footer_template_page.html?originalUrl=https:%2F%2Fcs.chromium.org%2Fchromium%2Fsrc%2Fcomponents%2Fprinting%2Fresources%2Fprint_header_footer_template_page.html) where these templates are handled. If I were to put in a PR adding this functionality to Chromium would it have a chance of being approved?

@aslushnikov Pinging you here since you've been involved in the discussion on my related issue about parsing Javscript in header/footer templates - #2167

**Comment by RockNHawk** [comment]
I resolved by generate PDF **twice**:
first time: generate full PDF then get the `pageCount`;
second time:gen the PDF page one by one and add a `request` parameter `pageNumber=x` then the page handle the `request` parameter to determine which page is current generating.

Last, megre all the PDF page into one PDF.

**Comment by injune1123** [comment]
> I resolved by generate PDF **twice**:
> first time: generate full PDF then get the `pageCount`;
> second time:gen the PDF page one by one and add a `request` parameter `pageNumber=x` then the page handle the `request` parameter to determine which page is current generating.
> 
> Last, megre all the PDF page into one PDF.

Hi @RockNHawk , thanks for sharing your solution. Would you mind also share some sudo code about how you did that? Thanks.

**Comment by RedFish** [comment]
> first time: generate full PDF then get the `pageCount`;

Great solution!
I manage to implement it, I did it with `pdf-parse`but is there a way to get `pageCount` from puppeteer directly ?
