### ISSUE TITLE
hover() not working

### ISSUE THREAD

**Issue by melissachang** [puppeteer/puppeteer#4336]
**Tell us about your environment:**

* Puppeteer version: 1.12.2
* Platform / OS version: 4.19.16-1rodete1-amd64 #1 SMP Debian 4.19.16-1rodete1 (2019-01-18 > 2018) x86_64 GNU/Linux
* URLs (if applicable):
* Node.js version: `node --version` gives v9.5.0

**What steps will reproduce the problem?**

First I'll show you steps on a live page. This is what the puppeteer test does.
- Go to [https://test-data-explorer.appspot.com](https://test-data-explorer.appspot.com), type `pat` into search box, select second result.
- Now hover over Relationship header; you'll see `1` change to `X`:
    ![1](https://user-images.githubusercontent.com/10929390/56701255-f1e46600-66b2-11e9-9705-4b190afccb39.png)
- Finally, click the `X`

In the puppeteer test, `hover()` isn't working (hence the `1` doesn't change to `x`).

- git clone https://github.com/DataBiosphere/data-explorer.git
- git checkout puppeteer-bug
- cd ui
- docker-compose up --build -t 0 -V
- In another terminal: `npm install`
- Observe test fails: `npm test`
- Now run with `node --inspect-brk` so we can stop at `debugger;`.
  - In `jest-puppeteer.config.js`, uncomment `headless: false`
  - `node --inspect-brk node_modules/.bin/jest tests`
  - Go to `chrome://inspect/#devices` and click `inspect`
  - In the window that pops up, press `F8` to resume script execution
  - Now you will hit this [debugger](https://github.com/DataBiosphere/data-explorer/blob/mc/puppeteer-bug/ui/tests/e2e/test.js#L48)
  - Step over the next couple lines. When you step over `await header.hover()`, you expect the `1` to turn into `X`. It does not. (Sometimes it does and I'm not sure why.)
  - `header._remoteObject.description` is `div.FacetHeader-facetHeader-137`.
  - Go to test window devtools console. `$("div.FacetHeader-facetHeader-137")` is the correct element:
![2](https://user-images.githubusercontent.com/10929390/56701565-987d3680-66b4-11e9-87d6-67656396a9a8.png)
    So `await header.hover()` should have worked.

**Comment by kblok** [comment]
Notice that HTML changes on hover. This should world
```ts 
await page.hover(".jss208");
await page.click(".jss209");
```

**Comment by melissachang** [comment]
classnames like `jss208` don't appear in local runs. I tried this and this doesn't work:
```
await page.hover(".FacetHeader-facetName-138");
```
You're welcome to try things out yourself.

**Comment by kblok** [comment]
@melissachang check what's the class for the DIV containing the number. Then check what's the class when the number turns into an X. The try to hover the first and click the second one.

**Comment by melissachang** [comment]
I tried that and it doesn't work. I'm aware of how hover is supposed to work. The whole point of this bug is that hover isn't working like it's supposed to. If you follow my repro steps, you can see for yourself.

**Comment by JoelEinbinder** [comment]
Can you create a simpler repro case? Given the complexity here, I suspect that there is something else going on unrelated to hovering. Like the elements have different names, different positions, or the page is not fully loaded in your test.

**Comment by melissachang** [comment]
I tried a simple case and unfortunately wasn't able to reproduce the problem.

elements have different names
- Last 2 repro steps address this

different positions
- Last 2 repro steps address this

page is not fully loaded in your test
- I'm in debugger, page has had plenty of time to load. 

Shouldn't take more than 5-10 mins to follow my steps.

**Comment by JoelEinbinder** [comment]
Your repro gave me a bunch of react errors.

Try injecting this code into your page. It will show you where javascript thinks the mouse cursor is.
```js
// This injects a box into the page that moves with the mouse;
// Useful for debugging
(function(){
  const box = document.createElement('div');
  box.classList.add('mouse-helper');
  const styleElement = document.createElement('style');
  styleElement.innerHTML = `
  .mouse-helper {
    pointer-events: none;
    position: absolute;
    top: 0;
    left: 0;
    width: 20px;
    height: 20px;
    background: rgba(0,0,0,.4);
    border: 1px solid white;
    border-radius: 10px;
    margin-left: -10px;
    margin-top: -10px;
    transition: background .2s, border-radius .2s, border-color .2s;
  }
  .mouse-helper.button-1 {
    transition: none;
    background: rgba(0,0,0,0.9);
  }
  .mouse-helper.button-2 {
    transition: none;
    border-color: rgba(0,0,255,0.9);
  }
  .mouse-helper.button-3 {
    transition: none;
    border-radius: 4px;
  }
  .mouse-helper.button-4 {
    transition: none;
    border-color: rgba(255,0,0,0.9);
  }
  .mouse-helper.button-5 {
    transition: none;
    border-color: rgba(0,255,0,0.9);
  }
  `;
  document.head.appendChild(styleElement);
  document.body.appendChild(box);
  document.addEventListener('mousemove', event => {
    box.style.left = event.pageX + 'px';
    box.style.top = event.pageY + 'px';
    updateButtons(event.buttons);
  }, true);
  document.addEventListener('mousedown', event => {
    updateButtons(event.buttons);
    box.classList.add('button-' + event.which);
  }, true);
  document.addEventListener('mouseup', event => {
    updateButtons(event.buttons);
    box.classList.remove('button-' + event.which);
  }, true);
  function updateButtons(buttons) {
    for (let i = 0; i < 5; i++)
      box.classList.toggle('button-' + i, buttons & (1 << i));
  }
})();
```

I noticed you are using onMouseEnter and onMouseLeave in order to detect a hover state. You should note that onMouseEnter does not fire when an element is created under the mouse. That, combined with react recreating your elements at will, is a recipe for disaster. I'd highly recommend using a :hover selector and revealing your close button with `display:none` / `display:block`.

**Comment by melissachang** [comment]
Thanks! `onMouseEnter` was indeed the problem. The mouse cursor was already over the facet header, so `onMouseEnter` didn't trigger. I changed to CSS hover and test works now.

The injected code was helpful. Hopefully this will help others with the same problem.

**Comment by jasonswearingen** [comment]
@JoelEinbinder thank you for posting this snippet.  The code of it isn't super important, but somehow I had a cognitive barrier regarding using the browser's capabilities to debug/improve pptr scripts.
