### ISSUE TITLE
Request Interception issue with base href

### ISSUE THREAD

**Issue by ps-mariotacke** [puppeteer/puppeteer#4337]
Request interception appears to be faulty and results in a navigation error.

### Environment
* Puppeteer version: `1.14.0-next.1556048038195`, tested 10.11 until `next`
* Chromium version: `r641577`
* Platform / OS version: `macOS 10.14.3 Mojave`
* Node.js version: `8.15.1`, tested up until `10.15.3`

### Steps to reproduce
1. Clone https://github.com/ps-mariotacke/puppeteer-intercept-issue a stripped down sample
2. Run `npm install`
3. Run `npm start`

**What is the expected result?**
Chromium spawns and takes a screenshot. It should have `setRequestInterception` enabled on the page.

**What happens instead?**
Chromium gets stuck and errors with a navigation error.

### Additional information
- I included a `broken.html` and `working.html` payload which can be switched in the `index.js` at the top. The only difference between these two payloads is that the broken payload specifies a `<base href="...">` in `<head>`. The working payload does not include the base href and instead specifies the fully qualified url in the script tag.
- https://github.com/ps-mariotacke/puppeteer-intercept-issue

Related to #3471

**Comment by ps-mariotacke** [comment]
Still broken in `1.15.0-next.1556265138389`.

**Comment by aslushnikov** [comment]
@ps-mariotacke This is super cool, thank you for the beautiful repro! Looks like a peculiar corner case somewhere in blink.

I'll try to further reduce this to narrow the scope.

**Comment by aslushnikov** [comment]
The upstream fix is out for review: https://chromium-review.googlesource.com/c/chromium/src/+/1586346

**Comment by aslushnikov** [comment]
@ps-mariotacke The fix is merged now. The https://github.com/ps-mariotacke/puppeteer-intercept-issue now works with puppeteer@next, specifically with `puppeteer@1.15.0-next.1556508387804`.

Please give it a try!

**Comment by ps-mariotacke** [comment]
Confirmed working in `puppeteer@1.15.0-next.1556508387804`. Thank you very much for the quick turn-around @aslushnikov. :fire:
