### ISSUE TITLE
Centos : TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r641577

### ISSUE THREAD

**Issue by dongjiang1989** [puppeteer/puppeteer#4342]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.14.0
* Platform / OS version:Cenos 7.4
* URLs (if applicable): 
* Node.js version: v10.13.0

**What steps will reproduce the problem?**

```
 retrying... { TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r641577
        at onTimeout (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/puppeteer/lib/Launcher.js:353:14)
        at Timeout.callback (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }
```

**Comment by WingMrL** [comment]
I also got this error but not everytime.

**Comment by gebin** [comment]
https://xbuba.com/questions/55273313

maybe chrome not kill

**Comment by aslushnikov** [comment]
For centos-related issues, please see #391. There are many folks who managed to run on CentOS.

**Comment by xiaoqiao112** [comment]
> ### Steps to reproduce
> **Tell us about your environment:**
> 
> * Puppeteer version: 0.14.0
> * Platform / OS version:Cenos 7.4
> * URLs (if applicable):
> * Node.js version: v10.13.0
> 
> **What steps will reproduce the problem?**
> 
> ```
>  retrying... { TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r641577
>         at onTimeout (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/puppeteer/lib/Launcher.js:353:14)
>         at Timeout.callback (/var/lib/docker/dongjiang/source/lfdl-landscape/node_modules/interactive-landscape/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)
>         at ontimeout (timers.js:436:11)
>         at tryOnTimeout (timers.js:300:5)
>         at listOnTimeout (timers.js:263:5)
>         at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }
> ```

How do you handle it？
