### ISSUE TITLE
Question: what should I use now?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [puppeteer/puppeteer#4343]
Hallo guys,

Our admins installed `headless "google-chrome-stable"` in custom docker, that we use for frontend apps.

Than I found `"puppeteer"` Project and this is another solution for headless testing.

What should I use now? `"google-chrome-stable"` or `"chrome/ium"` from `"puppeteer"`? Can I replace `"chrome/ium"` with `"google-chrome-stable"` and with `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`?

**Comment by g-konst** [comment]
[[WIKI](https://github.com/GoogleChrome/puppeteer#default-runtime-settings)] You can use [`puppeteer-core`](https://www.npmjs.com/package/puppeteer-core), and set launch option to : 
```javascript
const browser = await puppeteer.launch({executablePath: '/path/to/Chrome'});
```
