### ISSUE TITLE
How to handle object event?

### ISSUE THREAD

**Issue by jewway** [puppeteer/puppeteer#4344]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: windows 10
* URLs (if applicable): 
* Node.js version: v10.15.3

**What is the expected result?**
![image](https://user-images.githubusercontent.com/3501899/56743803-de67f680-67a9-11e9-8778-0ae830aced01.png)

I want to get chart's base64 information when chart event has finished
How can i get it or any suggestions for that?
thank you

**Comment by kblok** [comment]
@jewway check this answer in SO https://stackoverflow.com/questions/55811428/resolve-page-evaluate-in-puppeteer-after-user-triggered-event/55811966#55811966

**Comment by jewway** [comment]
Hi @kblok ,
Thank you for the information , it really works !!

**Comment by JoelEinbinder** [comment]
`page.evaluate` supports returning a promise.
```js
const result = await page.evaluate(() => {
    return new Promise(resolve => {
        // your code
        // your code
        something.on('finished', () => resolve(chart.getDataUrl());
    });
}
```
