### ISSUE TITLE
Incognito browser context shares the same cookies

### ISSUE THREAD

**Issue by jjason685** [puppeteer/puppeteer#4354]
`async function newPageWithNewContext(browser) {
    const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();
    return page
}`

Currently I'm using the above function to create multiple contexts under one browser. However, I've noticed that these pages share the same cookies (where in the API docs it was mentioned that the cookies/sessions are different). Is there any way I could fix this, or is there any way to run instances of Puppeteer without using as much RAM/CPU usage?

**Comment by aslushnikov** [comment]
>  However, I've noticed that these pages share the same cookies (where in the API docs it was mentioned that the cookies/sessions are different)

@jjason685 Browser contexts do not share any cookies - unless there's a bug. Do you have a repro? We'd love to debug.

**Comment by YungVDev** [comment]
I'm having the same issue

**Comment by jjason685** [comment]
I'm having an issue replicating the issue for some reason now. Earlier, it would open tabs inside a single browser instance. Now, it opens different windows instead.

**Comment by jjason685** [comment]
Actually, I've found a way to replicate this issue.

My server file: https://gist.github.com/jjason685/20d83ab49bff9a40d1d9d41427145bbd
My test file: https://gist.github.com/jjason685/79bf37acba80a2c1f0af4f6c7a1cdf37

After running the server file, I run the test file. Upon running, this logs out:

No cookie, sending.
Received cookie from instance

indicating that the second page used the same cookies as the original instance.

**Comment by YungVDev** [comment]
I’m also using puppeteer-extra, could it be the issue? Did you try without the plugin?

**Comment by jjason685** [comment]
@val92130 I just tested with default puppeteer and it seems to be working fine. I tested without the plugin and still had the cookie sharing issue. I believe this isn't an issue with default puppeteer itself so  I'll open an issue in https://github.com/berstend/puppeteer-extra#readme
