### ISSUE TITLE
@dxinteractive yes, if the `page.evaluate` causes a navigation, than the execution context where the evaluation is happenning will self-destruct, and `page.evaluate` call will throw an error.

### ISSUE THREAD

**Issue by david-littlefield** [puppeteer/puppeteer#4360]

**Comment by captaindavepdx** [comment]
Hello! I'm a new developer, and you're the second GitHub account I've posted an issue in. I want to be a good member, so if I've made a mistake - posted in wrong place, format, etc. - please let me know.

I've read through all of your posts about the "Context with specified id" issue." I found this problem and solution mentioned. Except, the solution is a little vague, and I don't quite understand it.

Could you, or someone who knows, please help explain what, and how to do that?

My code is logging into a social network, which triggers a redirect after clicking the submit button. It runs perfectly in regular Chrome, but it crashes in headless, or doesn't move on to the next page.

I can only write code inside of "page.evaluate," so all of my code must be in plain javascript.

Could you please help?
