### ISSUE TITLE
Installing puppeteer on android device.

### ISSUE THREAD

**Issue by beshoo** [puppeteer/puppeteer#4362]
Dear support.
I am planning to include puppeteer with my APK application. 
Well, i installed NodeJs on my android device, and i can connect to it Via React Native.
Now i want to install puppeteer to the Node on my Android but i got this error message while installing :
```

> puppeteer@1.15.0 install /data/data/io.tempage.dorynode/app_HOME/node_modules/puppeteer
> node install.js

/data/data/io.tempage.dorynode/app_HOME/node_modules/puppeteer/node6/lib/helper.js:283
    throw new Error(message);
    ^

Error: Unsupported platform: android
    at assert (/data/data/io.tempage.dorynode/app_HOME/node_modules/puppeteer/node6/lib/helper.js:283:11)
    at new BrowserFetcher (/data/data/io.tempage.dorynode/app_HOME/node_modules/puppeteer/node6/lib/BrowserFetcher.js:96:7)
    at createBrowserFetcher (/data/data/io.tempage.dorynode/app_HOME/node_modules/puppeteer/node6/lib/Puppeteer.js:82:12)
    at Object.<anonymous> (/data/data/io.tempage.dorynode/app_HOME/node_modules/puppeteer/install.js:39:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm WARN enoent ENOENT: no such file or directory, open '/data/data/io.tempage.dorynode/app_HOME/package.json'
npm WARN app_HOME No description
npm WARN app_HOME No repository field.
npm WARN app_HOME No README data
npm WARN app_HOME No license field.
npm ERR! Linux 3.18.71-14409750
npm ERR! argv "/data/data/io.tempage.dorynode/files/bin/node" "/data/user/0/io.tempage.dorynode/files/bin/npm" "i" "puppeteer"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@1.15.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.15.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/data/io.tempage.dorynode/app_HOME/npm-debug.log
1|c7ltechn:/data/user/0/io.tempage.dorynode/app_HOME $
```

Well, i know that chromium is available for Android and it supports headless. 
Please advice.

**Comment by JoelEinbinder** [comment]
Unfortunately we don't have android Chromium builds for you in the same place that we have mac/win/linux builds. You should try using [puppeteer-core](https://www.npmjs.com/package/puppeteer-core) and connecting to a Chrome instance you launched yourself.

If you get it working please report back. I am interested!

**Comment by beshoo** [comment]
Can we use this?

https://github.com/kiwibrowser/android/tree/master/headless

Im not sure how to. Please advice

**Comment by beshoo** [comment]
@JoelEinbinder , Please let me understand this correctly.
I want to run this as a background service on Android. Well, you said:
>> and connecting to a Chrome instance you launched yourself. 
So i have to launch Chrome? which will not be a headless anymore.

Regarding 
 >> Unfortunately we don't have android Chromium builds.
How can we arrange for that?
Will this help : 
https://www.bromite.org/chromium

Please advice!

**Comment by beshoo** [comment]
and how someone installs "puppeteer" on android
https://github.com/GoogleChrome/puppeteer/issues/2067 

Please advice

**Comment by AlloryDante** [comment]
Hello, I found a way to run pupeteer in Android, but it's a bit tricky....

Well I was thinking: Pupeteer works on ubuntu, right? So why don't I just install ubuntu on android.

Search on google play for "AnLinux" it requires no root whatsoever.Its the perfect ubuntu emulator,and guess what: No problems.I have no problems running headless chrome in android.Please if you have any recomandations about how to install this as a package for an app, I am here.

**Comment by MrJH** [comment]
@cezarlacatus can you give us more info?
I've tried it with AnLinux and Termux but cannot manage to start neither with headless chrome nor with normal chrome.
It always get stuck on browser.newPage() - the only way to get out is to restart termux completely.

**Comment by frank-dspeed** [comment]
The problem here is the formart of chrome it is not a executable anymore on Android so it does not work like that while puppeteer-core still should be able to detect running instances.

**Comment by rishabhrpg** [comment]
Hello, after a week of hit & trial I came with a solution to make it work on Android with Termux.
Follow up the  [gist](https://gist.github.com/rishabhrpg/4025ff5da4f0159af1850cb358279e57)
Starting point [repo](https://github.com/rishabhrpg/puppeteer-on-termux) takes a screenshot using puppeteer in termux.

**Comment by rodsotdia** [comment]
I have the same issue when installing the puppeteer package using Termux in Android `Error: Unsupported platform: android`. I'm using version `19.7.2`. Is there a workaround for this?

**Comment by Mark-Erena** [comment]
Same here, I'm trying to run whatapp-web.js on termux but it uses puppeteer and it throws the same error.

**Comment by AlloryDante** [comment]
> Same here, I'm trying to run whatapp-web.js on termux but it uses puppeteer and it throws the same error.

There was a thing where you can install xvfb in Termux and use it to simulate a virtual dextop then you pass that to puppeteer. 

pkg install -y tur-repo x11-repo python python-tkinter
pkg install -y chromium xorg-server-xvfb

Then follow this https://stackoverflow.com/questions/51883055/running-puppeteer-with-xfvb-headless-false

**Comment by weskerty** [comment]
npm install puppeteer --ignore-scripts --force on termux

It works fine if you use proot-distro debian on termux, but it will fail on chromium because pupetter doesn't have a precompiled binary.
Simply on proot-debian use apt install chromium and set the path to the module that requires it
