### ISSUE TITLE
page.select() does not pick from option text with no value, contrary to W3 specification

### ISSUE THREAD

**Issue by sudofox** [puppeteer/puppeteer#4363]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option (and all versions of the `<option>` spec) specify that, in absence of a defined `value` attribute, an `<option>` value will resolve to the contents of the text node it contains.

However, when I attempt to call select() with Puppeteer on an element with no value attribute, it is unable to select it based upon the value contained within the text node.

### Steps to reproduce

* Puppeteer version: puppeteer@1.14.0
* Platform / OS version: Arch Linux
* URLs (if applicable): n/app (internal/confidential URLs)
* Node.js version: v11.13.0

**What steps will reproduce the problem?**

HTML
```html
<select id="example">
  <option>Apples</option>
  <option>Bananas</option>
  <option>Coconuts</option>
</select>
```

Node

```js
await page.select('select#example', 'Coconuts'); 
```

**What is the expected result?**

**Coconuts** becomes selected

**What happens instead?**

The select remains on the default/initial option

**Comment by aslushnikov** [comment]
@sudofox your example works for me; what do I do wrong?

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.setContent(`
    <select id="example">
      <option>Apples</option>
      <option>Bananas</option>
      <option>Coconuts</option>
    </select>
  `);
  console.log(await page.select('select#example', 'Coconuts'));
})();

```

**Comment by FarhanFaqir** [comment]
Try this
let optionValue = await page.$$eval('#example', options => options.find(o => o.innerText === "Coconuts)")?.value)
await page.select('select#idOfSelect', optionValue);

**Comment by favourwright** [comment]
made @FarhanFaqir's answer into a function + minor mod
this works perfectly for asynchronously loaded options

```
  async function selectOptionFromHTMLSelectElement(selector, option){
    await page.waitForSelector(`${selector} option[value]`); // wait for options to load (PS - these are for options with value attribute. if your option doesn't have this attribute, feel free to remove it)
    let optionValue = await page.$$eval(`${selector} > option`, (node, option) => {
      return node.find(o=>o.innerText.toLocaleLowerCase().includes(option))?.value
    }, option)
    await page.select(selector, optionValue);
  }
  await selectOptionFromHTMLSelectElement('select#example', 'Coconuts');
```
