### ISSUE TITLE
frame.content() hangs on certain iframes

### ISSUE THREAD

**Issue by eric-zeng** [puppeteer/puppeteer#4367]
Calling `await frame.content()` on an iframe will sometimes hang indefinitely. Unfortunately, I can't figure out why, or what specific properties of the iframe or page will cause this issue. 

I'm encountering this when trying to extract the HTML of a page, and the HTML of its iframes (i.e. the HTML of its ads), for sites such as nytimes.com. Some, but not all of the ads that appear on nytimes.com will cause frame.content(). The only clues I have are that the problem iframes are usually ads by Google, and that the problem iframe usually does not specify a `src` attribute.

I traced the call in Node's debugger, and it appears that it gets stuck waiting for the frame's ExecutionContext. When I encounter the issue the call stack looks like this:

executionContext() - DOMWorld.js 92:17
`return this._contextPromise;`
evaluate - DOMWorld.js 111.32
`const context = await this.executionContext();`
content - DOMWorld.js 185:23
`return await this.evaluate(() => {...});`
content - FrameManager.js 491:33
`return this._secondaryWorld.content();`
example.js
`const result = await frame.content()`

Confusingly, I can call the semi-equivalent code `await frame.evaluate(() => document.documentElement.outerHTML)` from my puppeteer script without it blocking on await. 

I originally mentioned my problem in #4011. This was not an issue in puppeteer 1.11.0, I thought 1.14.0 fixed it but it didn't, and I'm still encountering it in 1.15.0.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.15.0
* Platform / OS version: MacOS 10.14.4
* URLs (if applicable): https://www.nytimes.com
* Node.js version: v11.13.0

**What steps will reproduce the problem?**
Unfortunately, I don't have a controlled reproduction environment, because I can't identify what property of the iframes is causing the problem. I'm encountering the issue primarily in the wild, on iframes for Google ads. 

The following code can usually produce this issue. This script opens nytimes.com, and attempts to extract the content of ad iframes. 
```javascript
const puppeteer = require('puppeteer');

(async () => {
  // Running in headful mode - to make sure content renders properly
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://www.nytimes.com');
  console.log('Page loaded');

  // Known ids for ads on nytimes, these are selectors for divs.
  let adSelectors = [
    '[id="dfp-ad-top"]',
    '[id="dfp-ad-mid1"]',
    '[id="dfp-ad-mid2"]',
    '[id="dfp-ad-mid3"]',
    '[id="dfp-ad-bottom"]'];

  for (let adSelector of adSelectors) {
    try {
      console.log('Getting elementHandle for ' + adSelector);
      let ad = await page.$(adSelector);
      if (!ad) {
        continue;
      }

      // Scroll to ad and wait, to give it time to render
      console.log('Got handle, scrolling to it and waiting');
      await page.evaluate((e) => {
        return new Promise((resolve, reject) => {
          try {
            e.scrollIntoView();
            setTimeout(resolve, 3000);
          } catch(e) {
            reject(e);
          }
        });
      }, ad);

      console.log('Done waiting, getting ad\'s child iframe');
      let iframe = await ad.$('iframe');
      if (!iframe) {
        continue;
      }
      console.log('Got handle to iframe, getting it\'s contentFrame');

      // Get the iframe's puppeteer.Frame
      let frame = await iframe.contentFrame();

      console.log('await frame.content()');
      // Issue is HERE: this call will hang on some of the ads
      let content = await frame.content();
      // But if you replace the above line with this line, the issue doesn't occur!
      // let content = await frame.evaluate(() => document.documentElement.outerHTML);
      console.log(content);
    } catch(e) {
      console.log(e);
      continue;
    }
  }
  await browser.close();
})();
```
**What is the expected result?**
Script prints out the HTML of the selected iframes.

**What happens instead?**
Script hangs on line 51, on some ads/iframes.

**Comment by usamaejaz** [comment]
I am also getting the same issue in 1.17.0

**Comment by aslushnikov** [comment]
From @eric-zeng investigation, it looks like we sometimes fail to force-create execution context for certain iframes. That'll be a chromium issue, but in order to debug and fix it, we'd need a repro.

@usamaejaz any chance you have a good repro for us to play?

**Comment by usamaejaz** [comment]
I had this behavior while navigating to http://www.eirinika.gr/

I start processing Frames starting from the root frame (page.mainFrame()). I do that specifically for detecting advertisement iframes. That is where it freezes.

**Comment by chandra-pratap-singh** [comment]
I am facing the same issue when I am trying to automate the send push process of DUO notification.
