### ISSUE TITLE
page.pdf() do not respect @page properties

### ISSUE THREAD

**Issue by bruceCzK** [puppeteer/puppeteer#437]
When set page size in css using `@page` like
```
  @page {
    size: 50mm 50mm;
  }
```
 page.pdf still output default A4 size pdf

**Comment by aslushnikov** [comment]
Turned out to be a Chrome Headless bug: [crbug.com/724160](https://bugs.chromium.org/p/chromium/issues/detail?id=724160)

**Comment by TheKnightCoder** [comment]
Was this fixed? I have the same problem

**Comment by bruceCzK** [comment]
Just tested with 1.5.0, and it has not.

**Comment by bruceCzK** [comment]
It seems the problem has been solved in 1.7.0 which added an options called `preferCSSPageSize`. 

https://pptr.dev/#?product=Puppeteer&version=v1.7.0&show=api-pagepdfoptions
