### ISSUE TITLE
Proxy server don't get UA that was set with page.setUserAgent

### ISSUE THREAD

**Issue by Alex0007** [puppeteer/puppeteer#4370]
### Steps to reproduce
```typescript
import * as puppeteer from 'puppeteer';
import * as proxyChain from 'proxy-chain';
import * as http from 'http';

const proxyServer = new proxyChain.Server({
    port: 8000,
    prepareRequestFunction: ({ request }: { request: http.IncomingMessage; }) => {
        console.log('headers on proxy', request.headers);

        // no proxy
        return {
            upstreamProxyUrl: undefined
        };
    }
});


const main = async () => {
    proxyServer.listen()
    console.log('listening');

    const browser = await puppeteer.launch({
        args: ['--proxy-server=http://localhost:8000']
    })
    const page = await browser.newPage()
    await page.setUserAgent('test user agent')
    await page.setRequestInterception(true)
    page.on('request', req => {
        console.log('request headers', req.headers());
        req.continue()
    });
    await page.goto('https://www.whatsmyua.info/api/v1/ua?ua')
    const pageContent = await page.evaluate(() => {
        return document.body.textContent
    }).then(JSON.parse)
    console.log({ result: pageContent[0].ua.rawUa });
}

main();

// 1.13.0
// request headers { 'upgrade-insecure-requests': '1', 'user-agent': 'test user agent' }
// headers on proxy {
//   host: 'www.whatsmyua.info:443',
//   'proxy-connection': 'keep-alive',
//   'user-agent': 'test user agent'
// }
// { result: 'test user agent' }

// 1.15.0
// request headers { 'upgrade-insecure-requests': '1', 'user-agent': 'test user agent' }
// headers on proxy {
//   host: 'www.whatsmyua.info:443',
//   'proxy-connection': 'keep-alive',
//   'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
//     '(KHTML, like Gecko) HeadlessChrome/75.0.3765.0 Safari/537.36'
// }
// { result: 'test user agent' }
```
**Tell us about your environment:**

* Puppeteer version: 1.13.0 - OK, 1.15.0 - NOT OK
* Platform / OS version: Windows 10
* Node.js version: 12

**What is the expected result?**
Proxy server should get user-agent assigned to page, instead it gets default puppeteer user-agent

**Comment by janlycn** [comment]
I also found this problem

**Comment by sovanyio** [comment]
I am also seeing this with POST requests on a login simulation, provisional request looks right in dev tools, but complete request (through service worker) has default UA.

**Comment by sovanyio** [comment]
In my case there was a ServiceWorker on the page, using the following to bypass during the puppeteer run solved my issue:

`await page._client.send('Network.setBypassServiceWorker', {bypass: true});`

**Comment by xuelliu** [comment]
I also found this problem at puppeteer@1.14.0 version.

**Comment by janlycn** [comment]
@aslushnikov

**Comment by jozsi** [comment]
I can confirm, as well the following [comment](https://github.com/GoogleChrome/puppeteer/issues/678#issuecomment-489385265), that it works on 1.13.0 but not on newer versions.

**Comment by HoldMyBeer1111** [comment]
Any news?

**Comment by HoldMyBeer1111** [comment]
I noticed that 1.18 works with google chrome 73.0.3642, and doesn't work with 77.0.3833.

**Comment by josebalius** [comment]
Any updates on this or workarounds?

**Comment by MeiK2333** [comment]
https://www.chromestatus.com/feature/4931699095896064
I think this issue is related to this feature. The https proxy needs to send `connect`, but it was limited.

**Comment by olixis** [comment]
Issue still exists in puppeteer:^10.2.0
