### ISSUE TITLE
How to get the actual chrome window pid (to minimize window using xdotool)

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4372]
I'm trying to get the chrome pid to minimize the window using xdotool. The pid returned by browser.process().pid is not the pid of the chrome window.

Here's my code:

```javascript
const browser = await puppeteer.launch({headless: false})
const pid = browser.process().pid
execSync(`xdotool minimizewindow ${pid}`, {stdio: 'inherit'})
```
Problem is it's not the actual pid of the chrome window. Is there a way to get this pid? Or maybe a way I can identify the correct pid somehow in a shell? I need to run chrome headfull but minimized.

**Comment by xse** [comment]
Hey, there are several methods you could use, for example you can get a tree of window using `xwininfo -tree -root` and from there you can find your window, and use `xprop -id YOURWINDOWID`, which will give you the window's pid.
```
_NET_WM_PID(CARDINAL) = 1129
```

There are other ways to do so like you could just get a list of every PID associated with chrome with `pgrep -f chromium` and send that command to all of those, it'll work.

I always start puppeteer in it's own xorg server, that's easier.

**Comment by TedTimbrell** [comment]
I'm sorry I don't have an answer yet but I too would love this functionality. I'm trying to associate the spawned window with the sink-input in PulseAudio
