### ISSUE TITLE
Sudden Breakage on AWS Lambda with page.goto & request intercepting.

### ISSUE THREAD

**Issue by j** [puppeteer/puppeteer#4375]
We deployed a full lambda stack without changing our screenshot code, and now `page.goto('http://domain')` hangs when we use `page.setRequestInterception(true)`.  All the interceptor does is serve files from the local file system to never really hit the open web.  We can't use setContent.

Any reason this would suddenly stop working in a Lambda environment?

**Comment by rustyconover** [comment]
Have you tried enabling debugging with `env DEBUG="puppeteer:*` and looking at the request processing lines?

**Comment by j** [comment]
We were all in a huge panic mode last night trying to fix our chrome / puppeteer image generator.  Our patch was to move local files to a CDN and not use request intercepting.  This adds 0.5 - 1.5 seconds to each request which we'd like to avoid.  I wish I could debug this locally, but it's working on OSX.

I'll look into it again and see if debugging lambda can be done and make a simplified replicable environment without all of our privates in it.

**Comment by Royshell** [comment]
As far as I understand, the Chromium version supplied by puppeteer is not compatible with ` page.setRequestInterception(true)`
