### ISSUE TITLE
screenshot with full page size can lead to out of memory conditions, request to have a size limit.

### ISSUE THREAD

**Issue by rustyconover** [puppeteer/puppeteer#4377]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.15.0
* Platform / OS version: Mac OS X
* URLs (if applicable): https://pastebin.com/XcHLqyNC
* Node.js version: v11.14.0

**What steps will reproduce the problem?**

Navigate to the HTML at the specified pastebin in Puppeteer, then attempt to take a full page screenshot like this:

```js
 await page.screenshot({
                            path: '/tmp/foobar.png',
                            fullPage: true,
                        });
```

The layout metrics from Puppeteer (from protocol debugging):
```json
{
  "id": 43,
  "result": {
    "layoutViewport": {
      "pageX": 0,
      "pageY": 0,
      "clientWidth": 3312,
      "clientHeight": 7168
    },
    "visualViewport": {
      "offsetX": 0,
      "offsetY": 0,
      "pageX": 0,
      "pageY": 0,
      "clientWidth": 828,
      "clientHeight": 1792,
      "scale": 1,
      "zoom": 1
    },
    "contentSize": {
      "x": 0,
      "y": 0,
      "width": 998096,
      "height": 1605439
    }
  },
  "sessionId": "AF24C989D34AB7204476A94676ED0CCA"
}
```

Clearly rendering a screenshot of 998096x1605439 is unreasonable as that is 1.4 tera-pixels.  

There should be some protection against this type of thing in:

https://github.com/GoogleChrome/puppeteer/blob/e2e6b8893481ab771c307d413e6d66d8bf05ec6b/lib/Page.js#L847

Calling:

```
                    // Get the "viewport" of the page, as reported by the page.
                    const dimensions = await page.evaluate(() => {
                        return {
                            width: document.documentElement.clientWidth,
                            height: document.documentElement.clientHeight,
                            deviceScaleFactor: window.devicePixelRatio,
                        };
                    });
```

Returns normal looking values for this content.

**What is the expected result?**

Have a size limit able to be specified, if the page is larger than that size do not screenshot as the memory allocation for the creation of the png or jpeg will fail and eventually crash the Chromium process.

**What happens instead?**

Chromium crashes and when it runs the system out of memory.

**Comment by NikolaiT** [comment]
I have the same problem.

**Comment by numerized** [comment]
I have same problem it's accumulating disk cache, and I do the following it's still not freeing disk cache

```
browser.process().kill('SIGINT')
browser.close()
```
