### ISSUE TITLE
Is there a way to show mouse pointer in puppeteer?

### ISSUE THREAD

**Issue by bexoss** [puppeteer/puppeteer#4378]
I have to see the movement of mouse pointer that running by puppeteer for debugging. I red this document : https://github.com/GoogleChrome/puppeteer/issues/374 

But the problem is, the test website is not mine, it is other's website like google, github website. So I dont know how to implement above code to client page. When puppeteer launch the browser, I opend developer console and and paste above code and enter it, it doesn't work. Maybe it is removed when page reloaded or redirected. 

Is there a way to show mouse cursor permanently during puppeteer running?

**Comment by xse** [comment]
Hey, 
I don't have a way to test that right now but you can inject scripts in page context using [page.evaluateOnNewDocument](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluateonnewdocumentpagefunction-args) or page.evaluate and so on which will inject a script on any page.
From there you can easily add any script that displays an image or a colored dot where the mouse is.
This should be "permanently" displayed unless puppeteer actually "moves the mouse outside the page" when it's not used. 

If you're still having issues i'll try to get an example working, have a good day!

**Comment by DanielRuf** [comment]
> i'll try to get an example working, have a good day!

This would be really helpful.

**Comment by aslushnikov** [comment]
I extracted the mouse helper we use in Puppeteer tests and a little bit enhanced it.

Check it out: [`install-mouse-helper.js`](https://gist.github.com/aslushnikov/94108a4094532c7752135c42e12a00eb)

This function will inject an element to the page's DOM that will track mouse position. This should be good-enough for a majority of use cases.

Here's what it takes to use the helper. Consider the helper is saved to the file `install-mouse-helper.js`:

```js
const puppeteer = require('.');
const {installMouseHelper} = require('./install-mouse-helper');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  // Installs the helper to the page. Mouse will be visible in the subsequent navigation.
  await installMouseHelper(page);
  // Here's the navigation. From now on we'll have a mouse cursor on the page.
  await page.goto('https://example.com');
  await page.mouse.move(135, 173);
  await page.mouse.down();
  await page.mouse.move(400, 225);
  await page.screenshot({path: 'screenshot.png'});
  await browser.close();
})();
```

The screenshot now has the mouse position and looks like this:

![screenshot](https://user-images.githubusercontent.com/746130/59075903-f7bf9080-8887-11e9-828a-1b7fae1dadba.png)

@bexoss is this good enough for you?

**Comment by MelMacaluso** [comment]
> ```js
>  await page.mouse.move(135, 173);
>   await page.mouse.down();
>   await page.mouse.move(400, 225);
> ```

Hi @aslushnikov , thanks! It does not work for me, do you think is not compatible with puppeteer latest?

@aslushnikov Ignore me, my linter removed the `;` from the css inline styles 😂

**Comment by 0x446f6d** [comment]
How could you get this working with something like a modal? Right now, the grey circle hides behind the modal and isn't visible in front of modals that pop up.

**Comment by ccpu** [comment]
@dominuslabs set [higher  z-index](https://stackoverflow.com/a/1120068/1103757) on `mousemove`

**Comment by 0x446f6d** [comment]
I set the z-index to the maximum z-index allowed (2,147,483,647) and it still didn't work. Maybe its because the modal is in an iframe?

**Comment by ccpu** [comment]
@dominuslabs difficult to say, as you have mentioned it could be the iframe, im using higher z-index in my [code](https://github.com/ccpu/storybook-addon-playwright/blob/76d492c852ec5fe3caedb08eac8db699818811d4/src/api/server/utils/install-mouse-helper.ts#L13)  with playwright, haven't noticed any problem yet.

**Comment by nathalizator** [comment]
> I extracted the mouse helper we use in Puppeteer tests and a little bit enhanced it.
> 
> Check it out: [`install-mouse-helper.js`](https://gist.github.com/aslushnikov/94108a4094532c7752135c42e12a00eb)
> 
> This function will inject an element to the page's DOM that will track mouse position. This should be good-enough for a majority of use cases.
> 
> Here's what it takes to use the helper. Consider the helper is saved to the file `install-mouse-helper.js`:
> 
> ```js
> const puppeteer = require('.');
> const {installMouseHelper} = require('./install-mouse-helper');
> 
> (async() => {
>   const browser = await puppeteer.launch();
>   const page = await browser.newPage();
>   // Installs the helper to the page. Mouse will be visible in the subsequent navigation.
>   await installMouseHelper(page);
>   // Here's the navigation. From now on we'll have a mouse cursor on the page.
>   await page.goto('https://example.com');
>   await page.mouse.move(135, 173);
>   await page.mouse.down();
>   await page.mouse.move(400, 225);
>   await page.screenshot({path: 'screenshot.png'});
>   await browser.close();
> })();
> ```
> 
> The screenshot now has the mouse position and looks like this:
> 
> ![screenshot](https://user-images.githubusercontent.com/746130/59075903-f7bf9080-8887-11e9-828a-1b7fae1dadba.png)
> 
> @bexoss is this good enough for you?

Hello ! I try to make it form but i get an error 
`Error: Cannot find module '.'`
- I have creat a file name test-mouse-help.js
- I have added your file "install-mouse-helper" in the same directory 

Can you help me define what's wrong ?

**Comment by DanielRuf** [comment]
> ```js
> const puppeteer = require('.');
> ```

try this:

> ```js
> const puppeteer = require('puppeteer');
> ```

**Comment by njelich** [comment]
I'm having issues running this. While the cursor does show up in screenshots, it isn't visible when running the browser in headless: false mode. Is this intended?

**Comment by Rem0ld** [comment]
I'm using this helper to see where the mouse is on the webpage, but I've found something, not sure if it's a bug or if I'm doing something wrong.
This is automated test, I'm giving list of events that puppeteer will go through.
At first there is no problem but when scrolling down, but at some point the cursor disappear (basically it's pretty much when scrollY > screenY) and it only shows up when scrolling is back up. 
I expecting to keep seeing the cursor at any scrollY position.
So my question is, is it normal behavior, is it a bug?

**Comment by chaffeqa** [comment]
I thought it may be useful to note that we solved this using this [click hijacking hack](https://fdossena.com/?p=html5cool/clickfx/i.frag).

Works great!

**Comment by ghost** [comment]
It should also be possible to use `Overlay.highlightQuad` to draw a cursor anywhere on the page (should work with iframes and any zIndex and doesn't require injecting scripts): https://chromedevtools.github.io/devtools-protocol/tot/Overlay/#method-highlightQuad
```
await Main.MainImpl.sendOverProtocol('Overlay.highlightQuad', {
 quad: [1, 1, 100, 1, 1, 10, 1, 1], color: {r: 100, g: 200, b: 200}
});
```

**Comment by dword-design** [comment]
> Check it out: install-mouse-helper.js

@nathalizator You want to put the mouse helper into an npm package? Otherwise I can do it.

**Comment by Mecanik** [comment]
> 

Drawing is one thing, moving it is another thing...

And for the record...

```
const cdp = await page.target().createCDPSession();

await cdp.send('DOM.enable');
await cdp.send('Overlay.enable');

const data = await cdp.send('Overlay.highlightQuad', {
      quad: [1, 1, 100, 1, 1, 10, 1, 1], 
	  color: {r: 100, g: 200, b: 200},
    });
console.log(data);
```

**Comment by cenfun** [comment]
> > Check it out: install-mouse-helper.js
> 
> @nathalizator You want to put the mouse helper into an npm package? Otherwise I can do it.

here is https://www.npmjs.com/package/mouse-helper

**Comment by obfuscated-loop** [comment]
For those using JavaScript, the solution I have found is this:
```js
import { createCursor, getRandomPagePoint  } from 'ghost-cursor';
import installMouseHelper from 'ghost-cursor'
// the rest of your code
const page = await browser.newPage();
await installMouseHelper.installMouseHelper(page)
```

**Comment by storenth** [comment]
Guys, just use simplest event listeners to track click like events @aslushnikov you talking about: https://github.com/puppeteer/puppeteer/issues/4378#issuecomment-499726973
I suggest to close the issue.

**Comment by jrandolf** [comment]
Showing the mouse pointer wouldn't really belong to Puppeteer/Chromium as it's an OS artifact. We recommend using the workarounds listed in this thread.

**Comment by bvandercar-vt** [comment]
Recommend using the package [Ghost-Cursor](https://github.com/Xetera/ghost-cursor)
