### ISSUE TITLE
Enable a way to access an Element properties with ElementHandle

### ISSUE THREAD

**Issue by batiste** [puppeteer/puppeteer#438]
I would like for example to do

```
   let input = await page.$('input')
   assert.equal(input.value, 'some text')
```

It could be input.getAttribute('value') or/and getProperty('value'). Or anything else that could make sense.

**Comment by aslushnikov** [comment]
This will work out nicely with #382.

**Comment by batiste** [comment]
@aslushnikov I see. I didn't realise this PR was solving this problem. ElementHandle would inherit from ObjectHandle and you could do input .property('foo')

This would be very nice because ATM testing the value of an input is quite awkward.

**Comment by jsnanigans** [comment]
I came up with this temporary solution.

```javascript
async function getValue(selector) {
  let value = await page.evaluate((sel) => {
    return document.querySelector(sel).value
  }, selector)
  return value
}

assert.equal(await getValue('input'), 'some text')
```

**Comment by emadehsan** [comment]
Temporarily, you can use a DOM manipulator like [JSDOM](https://github.com/tmpvar/jsdom) to get value (if you also want to navigate through DOM)
```
let content  = await page.content();
let dom = new JSDOM(content);
let value = dom.window.document.querySelector(selector).value;
```
The `page.content()` method is pushed to master branch a few hours ago.
To be able to use it, you would have to install the puppeteer via GitHub (only until update via npm is available)
`npm i --save https://github.com/GoogleChrome/puppeteer`

**Comment by aslushnikov** [comment]
JSHandles have landed; now the following is possible:

```js
let input = await page.$('input');
let valueHandle = await input.getProperty('value');
assert.equal(await valueHandle.jsonValue(), 'some text')
```

**Comment by yaakovyitzchak** [comment]
Hi it doesn't seem to get all of the properties, for example how do I get source of an Iframe, doing this code: 
```

var puppeteer = require("puppeteer");

(async() => {
    var browser = await puppeteer.launch();
    console.log("Got browser", browser);
    var page = await browser.newPage();
    console.log(page,"got page");
    await page.goto("https://docs.google.com/file/d/1Cyuh41yNfYZU_zL-MHLf_EPJCYnlT7oJ/preview?enablejsapi=1&playerapiid=player4");
    console.log("went to page..");
    
  
    var clickEl = ".ndfHFb-c4YZDc-aTv5jf-bVEB4e-RJLb9c";
    await page.click(clickEl);
    console.log("clicked")
    var frame = await page.waitForSelector("iframe[id=drive-viewer-video-player-object-0]");
    var props = await frame.getProperties();
    console.log(frame, "got video frame, props: ", props);
)();
```
 only prints: `'got video frame, props: ' Map {}` even though I know there are tons of more DOM properties like src ??

**Comment by evandrocoan** [comment]
> @yaakovyitzchak it doesn't seem to get all of the properties, for example how do I get source of an Iframe, doing this code:

Related to: https://github.com/puppeteer/puppeteer/issues/4995 - elementHandle.getProperties() returns an empty map - which i think is a bug

1. https://github.com/puppeteer/puppeteer/issues/3786 - How can I get element attribute without evaluate function
1. https://github.com/puppeteer/puppeteer/issues/628 - Collect element attributes from selector

**Comment by Rupeshiya** [comment]
Hey can anyone answer this plz ?
https://stackoverflow.com/questions/66541493/how-to-check-the-disabled-property-on-an-element-handle-in-puppeteer
