### ISSUE TITLE
Target URL different from page URL

### ISSUE THREAD

**Issue by gilles-yvetot** [puppeteer/puppeteer#4382]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.14
* Platform / OS version: macOS Mojave
* URLs (if applicable): https://store.google.com/?utm_source=hp_header&utm_medium=google_oo&utm_campaign=GS100042
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

Open google.com then command+click on the "store" link on the top left corner

_Please include code that reproduces the issue._

```javascript
async function handleBrowserTargetCreated(target) {
  const page = await target.page()
  console.log(page.url(), target.url(), target.type())
}
browser.on('targetcreated', await handleBrowserTargetCreated)
```

**What is the expected result?**
`target.url()` to be the same than `page.url()`

**What happens instead?**
target url is: `https://store.google.com/?utm_source=hp_header&utm_medium=google_oo&utm_campaign=GS100042`
page url is: `:`
target type is `page`

**Comment by ll350** [comment]
Running into this when navigating, particularly redirects, status 302 responses. Checking in my debugger (after the browser is redirected) I'm seeing page.url() has the old url, while page.target()._targetInfo.url will have the current url that is in the browser.

**Comment by vaibhavtripathi** [comment]
@aslushnikov Any word on this?

**Comment by gilles-yvetot** [comment]
@mathiasbynens any word on this?
