### ISSUE TITLE
Page timeout due to script loading error/timeout

### ISSUE THREAD

**Issue by rudiedirkx** [puppeteer/puppeteer#4390]
* Puppeteer version: 1.13 and 1.15
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable): https://www.echt-susteren.nl/ and https://www.noordwijk.nl/
* Node.js version: v8.16.0

I use Puppeteer to check 360 sites for cookies. 358 of them work with a 9s timeout. 2 of them don't work at all, not even with a 90s timeout. 

Script:

```
const browser = await puppeteer.launch(/*{executablePath: '/usr/bin/chromium-browser'}*/);
const page = await browser.newPage();

try {
	await page.goto(url, {timeout: 90000});
}
catch (ex) {
	console.log(ex.constructor.name + ': ' + ex.message);
	process.exit();
}
```

Only for those 2 URLs, it keeps crashing with `TimeoutError: Navigation Timeout Exceeded: 90000ms exceeded`.

A separately installed chromium (via `executablePath`) (`73.0.3683.86`) doesn't change anything.

I can't see why it times out. Only that it times out. Can't it connect? Is it loading too much? They work fine in my real (Windows) Chrome browser. The other 358 sites work fine too. Is there a more debug mode? A Network panel?

**Comment by rudiedirkx** [comment]
https://try-puppeteer.appspot.com/ doesn't work either, for either URL. Same timeout (but after the default 30s).

**Comment by rudiedirkx** [comment]
It might be because a single JS resource can't be loaded. The normal browser gives up after X seconds, and keeps going with the rest of the page. Puppeteer gives up completely. Can I set single resource timeout to something lower? I want to wait for the 'load' event, unless a resource times out. Just like the real browser, right?

**Comment by gdoron** [comment]
Though it would probably be best if puppeteer could support it out of the box.
But you can wait for `domcontentloaded` in your `goto` function, afterward, wait for the native js `load` function.

**Comment by rudiedirkx** [comment]
How do I "wait for the native js `load` function"? I do need to wait for `load`, `domcontentloaded` is too soon for my use. Will the "native js `load`" be executed like in the real browser?, after a certain timeout.

**Comment by gdoron** [comment]
Do you have an example page for me to reproduce?

**Comment by rudiedirkx** [comment]
Of course:

> URLs (if applicable): https://www.echt-susteren.nl/ and https://www.noordwijk.nl/

Times out after ~20 sec in real Chrome. Breaks Puppeteer after 30 sec (by default).

**Comment by clockworked247** [comment]
Just curious, of the 360, are those two your only sites using https?

**Comment by rudiedirkx** [comment]
No, about 350 are https. The problem is the single JS resource that doesn't load, which makes the onload event not trigger, which hangs the headless browser, but not the real browser. I still have no good fix for this. Only an external timeout works (process A with timeout that calls process B that calls Puppeteer), since Puppeteer doesn't seem to have a timeout setting for this.

**Comment by aslushnikov** [comment]
@rudiedirkx The https://www.noordwijk.nl doesn't load for me in a desktop browser either, so puppeteer's timeout is a fair error. Why do you think it's wrong/bad?

**Comment by aslushnikov** [comment]
Actually, chrome has a 1 minute timeout for pending requests, so the following works fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch({
      headless: false,
    });
    const [page] = await browser.pages();
    await page.goto('https://www.noordwijk.nl/', {
      timeout: 90000,
    });
    await browser.close();
})();

```

**Comment by rudiedirkx** [comment]
That's not what I see. Neither. 

The real/desktop browser times out resources after 20 sec, and then the page `load` event triggers. Not so in Puppeteer.

My Puppeteer keeps waiting, minutes and minutes, not 1 minute, for unloadable resources. With `{headless: true}` of course, because headless is the point.

It still seems headless Puppeteer does resource timeout differently than the real/desktop browser. Automatic 20 sec timeout in desktop. No timeout at all in Puppeteer.

**Comment by rudiedirkx** [comment]
The automatic 20 (21?) sec timeout in the real browser:

![image](https://user-images.githubusercontent.com/168024/61210692-98159a00-a6fd-11e9-957f-a6efa3b7396e.png)

**Comment by rudiedirkx** [comment]
If I try on https://try-puppeteer.appspot.com/

```
const browser = await puppeteer.launch(); // same with {headless: false}, if that works there

const page = await browser.newPage();
await page.goto('https://www.noordwijk.nl/', {timeout: 90000});

console.log(await page.content());
await page.screenshot({path: 'screenshot.png'});

await browser.close();
```

it errors after a while:

> Error running your code. TimeoutError: Navigation Timeout Exceeded: 90000ms exceeded

because the entire page times out, instead of the 1 broken resource, so this entire page is unloadable. Not so in the real browser.

**Comment by rudiedirkx** [comment]
Soooo? Anyway to avoid this resource timeout with Puppeteer? Seems to me like kind of a big issue. Am I doing something wrong? Is there a better event to wait for? Or a workaround? Or update or patch something?

**Comment by harrisoncramer** [comment]
I'm also having this issue on Ubuntu 18.04 with Puppeteer. It runs fine in head-ful mode but as soon as you try to run it headless it times out.

**Comment by wobsoriano** [comment]
Can confirm this with puppeteer 2.1.1 running in windows and mac.

```javascript
const puppeteer = require('puppeteer');
const url = 'https://www.youtube.com/channel/UCxhygwqQ1ZMoBGQM2yEcNug/videos';

async function run() {
  try {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    await page.goto(url, { waitUntil: 'networkidle2' });
    await page.waitForSelector('#items');
    // Throws TimeoutError when headless is set to true
  } catch (e) {
    console.log(e);
  }
}

run();
```

**Comment by bboydflo** [comment]
I have a similar issue. In my case I discovered that on the page I `goto` there is a script that redirects and I don't know how to fix it. but when I remove the page from the script seems to work!

**Comment by dealeros** [comment]
Hi, I have the same problem, when I'm trying to get channel /videos page. When Puppeteer is set to headless: true the page is just not loading the content.  Im using also this plugin https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth
Do you think that they somehow recognize headless browser?
 
![screenshot](https://user-images.githubusercontent.com/32581286/75829868-9f360900-5daf-11ea-86a9-b9c69ac7a185.jpg)

**Comment by wobsoriano** [comment]
> Hi, I have the same problem, when I'm trying to get channel /videos page. When Puppeteer is set to headless: true the page is just not loading the content. Im using also this plugin https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth
> Do you think that they somehow recognize headless browser?
> 
> ![screenshot](https://user-images.githubusercontent.com/32581286/75829868-9f360900-5daf-11ea-86a9-b9c69ac7a185.jpg)

Yes, looks like they recognize the headless browser already. It's a way to keep users use their API instead.

**Comment by wobsoriano** [comment]
I tried different options and different plugins, modules but none of them work.

I guess the only way to make this work is to keep headless option to false and just save the data to a json file or db and do a cron job.

**Comment by rudiedirkx** [comment]
@dealeros @sorxrob That's a different issue. If you can make a screenshot, there's no script timeout.

**Comment by dealeros** [comment]
@rudiedirkx My screenshot was taken before page.waitFor(element). After that is timeout.

```
        await page.waitFor(5000);
        await page.screenshot({
            path: './images/screenshot.jpg',
            type: 'jpeg',
            quality: 70
        })
        await page.waitFor('#metadata-line .style-scope.ytd-grid-video-renderer');
```

**Comment by bboydflo** [comment]
My issue was related to macos and getting a certificate issue. Try to search in issues for codesign. That issue explains how to fix certificate issues on macos. I hope it helps

**Comment by dealeros** [comment]
@sorxrob I found the solution. Just add to launch args - --enable-blink-features=HTMLImports

```
browser = await puppeteer.launch({
            //headless: false,
            'args': [
                '--enable-blink-features=HTMLImports'
            ]
        });
```

https://magpcss.org/ceforum/viewtopic.php?f=6&t=17412

**Comment by rudiedirkx** [comment]
@dealeros This issue isn't about `page.waitFor(element)`. It's about `page.goto(url)` timing out due to a website script not loading. The real browser handles that (it just quits after 20 secs), but headless breaks.

**Comment by kingiw** [comment]
I am facing the same issue on my laptop.
I cannot access to some websites with puppeteer, but I can access them in a normal chrome instance.
However, when I am trying the same script on my virtual machine it works perfectly.

My scripts:
```javascript
const puppeteer = require('puppeteer');
const utils = require('./utils');
const url = "https://google.com";

(async () => {
  const browser = await puppeteer.launch({
      headless: false
  });
  const page = await browser.newPage();
  await page.goto(url, {
      waitUntil: 'domcontentloaded',
      timeout: 100000
    });
  await utils.sleep(3000);
  await browser.close();
})();
```

My laptop environment:
OS: Windows 1089
puppeteer version: 2.1.1

My VM environment:
OS: Microsoft Windows Server 2019 (Windows 1089)
puppeteer version: 2.1.1

BTW, it takes an extremely long time to load the page completely when I am using headless chrome to access specific URLs on my laptop.

**Comment by dealeros** [comment]
@kingiw use this code to generate console logs to cmd:

```
page
        .on('console', message =>
        console.log(`${message.type().substr(0, 3).toUpperCase()} ${message.text()}`))
        .on('pageerror', ({ message }) => console.log(message))
        .on('response', response =>
        console.log(`${response.status()} ${response.url()}`))
        .on('requestfailed', request =>
        console.log(`${request.failure().errorText} ${request.url()}`));
```

It should help you to find the problem. Just compare logs when headless and not.

**Comment by kingiw** [comment]
@dealeros Thanks for your quick response.

The log shows a 200 status code to load an image:
```
200 data:image/png;base64,iVBORw0KGgoAAAANSUhE...
```

The full error messages are:
```
net::ERR_TIMED_OUT [MY_URL]
(node:3308) UnhandledPromiseRejectionWarning: Error: net::ERR_TIMED_OUT at [MY_URL]
    at navigate (D:\work\sysuthesis\bot\node_modules\puppeteer\lib\FrameManager.js:120:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (D:\work\sysuthesis\bot\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\work\sysuthesis\bot\node_modules\puppeteer\lib\Page.js:672:49)
    at Page.<anonymous> (D:\work\sysuthesis\bot\node_modules\puppeteer\lib\helper.js:112:23)
    at D:\work\sysuthesis\bot\example.js:25:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
200 data:image/png;base64,iVBORw0KGgoAAAANSUhEU...
```

**Comment by dealeros** [comment]
@kingiw I can't reproduce your issue. On my machine it just work ok. Have you tried run this with proxy VPN? Maybe you are banned. The log should be longer. 

```
200 https://www.google.com/images/searchbox/desktop_searchbox_sprites302_hr.webp
200 https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
200 https://www.google.com/xjs/_/js/k=xjs.s.pl.nOBV0DuCEwY.O/ck=xjs.s.ofAvoXrQJ80.L.W.O/m=Fkg7bd,HcFEGb,IvlUe,MC8mtf,OF7gzc,RMhBfe,T4BAC,TJw5qb,TbaHGc,Y33vzc,cdos,cr,hsm,iDPoPb,jsa,mvYTse,tg8oTe,uz938c,vWNDde,ws9Tlc,yQ43ff,d,csi/am=AAAAAEsAdt0BAP43ARAA2DEAACBAmGBjgTBIKAhArJoABAI/d=1/dg=2/ct=zgms/rs=ACT90oEalR9CJZXl8zSGPMqdX4dMWrsj9A
200 https://ssl.gstatic.com/gb/images/i1_1967ca6a.png
200 https://www.gstatic.com/images/branding/googlemic/2x/googlemic_color_24dp.png
200 https://www.gstatic.com/inputtools/images/tia.png
204 https://www.google.com/gen_204?s=webhp&t=aft&atyp=csi&ei=5RhiXsmSDcakad3FoDA&rt=wsrt.462,aft.206,prt.185&bl=ED6e&ima=1&imad=0&imn=2
200 https://www.google.com/images/nav_logo299.webp
204 https://www.google.com/gen_204?atyp=csi&ei=5RhiXsmSDcakad3FoDA&s=jsa&jsi=s,t.0,et.focus,n.iDPoPb,cn.1&zx=1583487207037
200 https://www.google.com/xjs/_/js/k=xjs.s.pl.nOBV0DuCEwY.O/ck=xjs.s.ofAvoXrQJ80.L.W.O/am=AAAAAEsAdt0BAP43ARAA2DEAACBAmGBjgTBIKAhArJoABAI/d=1/exm=Fkg7bd,HcFEGb,IvlUe,MC8mtf,OF7gzc,RMhBfe,T4BAC,TJw5qb,TbaHGc,Y33vzc,cdos,cr,csi,d,hsm,iDPoPb,jsa,mvYTse,tg8oTe,uz938c,vWNDde,ws9Tlc,yQ43ff/ed=1/dg=2/ct=zgms/rs=ACT90oEalR9CJZXl8zSGPMqdX4dMWrsj9A/m=RqxLvf,aa,abd,async,dvl,fEVMic,foot,lu,m,mUpTid,mu,sb_wiz,sf,spch,xz7cCd?xjs=s1
200 https://www.gstatic.com/og/_/js/k=og.og2.en_US.ojePM5yvxrU.O/rt=j/m=def,aswid/exm=in,fot/d=1/ed=1/rs=AA2YrTtRGH9zpODrmC5Dv5OxrtsJsy1ZsQ
200 https://www.google.com/xjs/_/js/k=xjs.s.pl.nOBV0DuCEwY.O/ck=xjs.s.ofAvoXrQJ80.L.W.O/am=AAAAAEsAdt0BAP43ARAA2DEAACBAmGBjgTBIKAhArJoABAI/d=1/exm=Fkg7bd,HcFEGb,IvlUe,MC8mtf,OF7gzc,RMhBfe,RqxLvf,T4BAC,TJw5qb,TbaHGc,Y33vzc,aa,abd,async,cdos,cr,csi,d,dvl,fEVMic,foot,hsm,iDPoPb,jsa,lu,m,mUpTid,mu,mvYTse,sb_wiz,sf,spch,tg8oTe,uz938c,vWNDde,ws9Tlc,xz7cCd,yQ43ff/ed=1/dg=2/ct=zgms/rs=ACT90oEalR9CJZXl8zSGPMqdX4dMWrsj9A/m=OG6ZHd,T7XTS,URQPYc,eN4qad,o02Jie,pB6Zqd,zbML3c?xjs=s2
204 https://www.google.com/gen_204?atyp=i&zx=1583487207327&ogsr=1&ei=5RhiXqf_DaqclwSrs5qADA&ct=6&cad=i&id=19016262&loc=webhp&prid=1&ogd=com&ogprm=up&ic=1
200 https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.OfYsKuVZ3qI.O/m=gapi_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/rs=AHpOoo8UDq_6isr1vipw5cUlPTPPdx3_0A/cb=gapi.loaded_0
200 https://ogs.google.com/widget/app/so?hl=pl&origin=https%3A%2F%2Fwww.google.com&pid=1&spid=1&gm&usegapi=1
204 https://www.google.com/gen_204?atyp=csi&ei=5RhiXsmSDcakad3FoDA&s=webhp&t=all&bl=ED6e&imn=2&adh=&conn=onchange&ima=1&imad=0&ime=1&imex=1&imeh=1&imea=0&imeb=0&wh=600&scp=0&rt=xjsls.173,iml.206,prt.185,aft.206,dcl.187,xjses.327,xjsee.374,xjs.374,ol.999,wsrt.462,cst.116,dnst.1,rqst.284,rspt.158,sslt.67,rqstt.336,unt.217,cstt.219,dit.648&zx=1583487207656
204 https://adservice.google.com/adsid/google/ui
```

You can try also this https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth to imitate headfull Chrome. The implementation is just:

```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());
```

**Comment by kingiw** [comment]
@dealeros Yep, and that's why the problem is tricky. 
I simply ran into this problem on my personal laptop with puppeteer.
I can access the page with a real chrome instance without any proxy on my personal laptop.
I can also run the script on my virtual machine, with totally the same version of node/puppeteer/etc.

**Comment by rudiedirkx** [comment]
In my case the `goto` timeout happens because of a forever-loading blocking resource (js or css). That'll never trigger the page's `load` or `domcontentloaded`. A bug in Puppeteer IMO, but whatever.

My fix (FINALLY!) is to do what [Lighthouse does in its `Driver`](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L945): a `Promise.race()` for a custom 'timeout'-ish. The shorter version I used:

```
const LOAD_FAIL = Math.random();
const sleep = options => new Promise(resolve => {
	options.timer = setTimeout(resolve, options.ms, options.result === undefined ? true : options.result);
});

const sleepOptions = {ms: TIMEOUT - 1000, result: LOAD_FAIL};
const response = await Promise.race([
	sleep(sleepOptions),
	page.goto(url, {timeout: TIMEOUT + 1000}),
]);
clearTimeout(sleepOptions.timer);
const success = response !== LOAD_FAIL;
```

The `sleep()` and `page.goto()` race. If it's the timeout, the result is clearly a fail (LOAD_FAIL). Otherwise it's whatever `page.goto()` returns. Like this, it doesn't throw a `TimeoutException`, and the page is still queryable.

That was my issue. I don't know all your semi-related issues.

**Comment by Paul-DS** [comment]
Is the normal behavior of puppeteer not supposed to be the same as a "normal" browser ?
In this case I think this issue should be reopen.

**Comment by blue-int** [comment]
> I am facing the same issue on my laptop.
> I cannot access to some websites with puppeteer, but I can access them in a normal chrome instance.
> However, when I am trying the same script on my virtual machine it works perfectly.
> 
> My scripts:
> 
> ```js
> const puppeteer = require('puppeteer');
> const utils = require('./utils');
> const url = "https://google.com";
> 
> (async () => {
>   const browser = await puppeteer.launch({
>       headless: false
>   });
>   const page = await browser.newPage();
>   await page.goto(url, {
>       waitUntil: 'domcontentloaded',
>       timeout: 100000
>     });
>   await utils.sleep(3000);
>   await browser.close();
> })();
> ```
> 
> My laptop environment:
> OS: Windows 1089
> puppeteer version: 2.1.1
> 
> My VM environment:
> OS: Microsoft Windows Server 2019 (Windows 1089)
> puppeteer version: 2.1.1
> 
> BTW, it takes an extremely long time to load the page completely when I am using headless chrome to access specific URLs on my laptop.

@kingiw I am having the exact same issue as you, except that my laptop environment uses OSX and VM environment uses Centos 7.4, and puppeteer 1.9.0 on both of them. Could you let me know how did you solve the problem / figure out the reason why? Thanks!

**Comment by yxiong20** [comment]
> In my case the `goto` timeout happens because of a forever-loading blocking resource (js or css). That'll never trigger the page's `load` or `domcontentloaded`. A bug in Puppeteer IMO, but whatever.
> 
> My fix (FINALLY!) is to do what [Lighthouse does in its `Driver`](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L945): a `Promise.race()` for a custom 'timeout'-ish. The shorter version I used:
> 
> ```
> const LOAD_FAIL = Math.random();
> const sleep = options => new Promise(resolve => {
> 	options.timer = setTimeout(resolve, options.ms, options.result === undefined ? true : options.result);
> });
> 
> const sleepOptions = {ms: TIMEOUT - 1000, result: LOAD_FAIL};
> const response = await Promise.race([
> 	sleep(sleepOptions),
> 	page.goto(url, {timeout: TIMEOUT + 1000}),
> ]);
> clearTimeout(sleepOptions.timer);
> const success = response !== LOAD_FAIL;
> ```
> 
> The `sleep()` and `page.goto()` race. If it's the timeout, the result is clearly a fail (LOAD_FAIL). Otherwise it's whatever `page.goto()` returns. Like this, it doesn't throw a `TimeoutException`, and the page is still queryable.
> 
> That was my issue. I don't know all your semi-related issues.

Does this actually solve any problem at all? I have an exact problem as you right now, site with custom code block failed to load in Puppeteer headless mode.

My understanding of your above code is just to allow it timeout more gracefully, but it does not solve the screenshot problem, it will still not able to do a screenshot.
