### ISSUE TITLE
Using existing userDataDir causes unknown failure with open tabs

### ISSUE THREAD

**Issue by alexr17** [puppeteer/puppeteer#4394]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: MacOS 10.13.6 and Chrome 74
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

I'm running this very basic code below and attempting to run puppeteer using my own chrome profile with `userDataDir`. 
```
const puppeteer = require('puppeteer');
(async () => {
    try {
        const browser = await puppeteer.launch({
            executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            headless: false,
            userDataDir: '/Users/xxxx/Library/Application Support/Google/Chrome'
        });
        const page = await browser.newPage();
        page.on('console', msg => console.log('PAGE LOG:', msg.text()));
        await page.goto('https://google.com');
        await page.waitFor(10000);
        await browser.close();
    }
    catch (e)
    {
        console.log(e)
    }
})();
```

**What is the expected result?**
Opening a new tab in my already open browser with my user profile.

**What happens instead?**

It fails *silently* (without any error message). An about:blank page does open as normal, but the other tab (google.com) does not.

```
$ node index.js
Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/Users/xxxx/.../node_modules/puppeteer/lib/Launcher.js:342:14)
    at ChildProcess.helper.addEventListener (/Users/xxxx/.../node_modules/puppeteer/lib/Launcher.js:332:60)
    at ChildProcess.emit (events.js:194:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

Weirdly however, it does work somewhat when chrome is quit completely. It opens a new chrome with the correct, unsynced, profile. It also works when headless is set to `true`. It seems to be similar to [issue 2099](2099#issuecomment-390645257).

**Comment by jiahao-c** [comment]
I am having the same problem. The following code opens a new `about:blank` page in my current Chrome window, but stops there and never goes to google.com.

```
const CHROME_PATH = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const PROFILE_PATH = '/Users/<myusername>/Library/Application Support/Google/Chrome';

const pptr = require('puppeteer-core');
(async () => {
    const browser = await pptr.launch({
        headless: false,
        executablePath: CHROME_PATH,
        userDataDir: PROFILE_PATH
    });
    const page = await browser.newPage();
    await page.goto('https://google.com');
})();
```
If I run it without `userDataDir: PROFILE_PATH`, everything works. If I include `userDataDir: PROFILE_PATH`, it throws the same error
```
(node:12434) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/Users/jh/node_modules/puppeteer-core/lib/Launcher.js:340:14)
    at ChildProcess.<anonymous> (/Users/jh/node_modules/puppeteer-core/lib/Launcher.js:330:60)
    at ChildProcess.emit (events.js:205:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

Tell us about your environment:

Puppeteer version: 1.18.1
Platform / OS version: MacOS 10.14.5 and Chrome 75.0.3770
Node.js version: 12.4.0



UPDATE:
I changed puppeteer version to 1.15.0 to match my Chrome version (75.0.3770). But the error still reproduce.

UPDATE 2:
The code will not produce error when Chrome is quitted. However, Chrome would lose all logged in sessions. Puppeteer seems somehow destroyed Chrome user data

**Comment by aslushnikov** [comment]
Folks, please don't run two browser instances that point to the same chromium profile. This will result in undefined behavior.

**Comment by TomasHubelbauer** [comment]
Okay, running normal Chrome and Puppeteer-controlled Chrome both pointed at the same profile is not supported - fair.

But is it okay to copy the user profile to a new directory and point Puppeteer at the cloned profile? Or is that also likely to result in undefined behavior?

Intuitively I think this should work unless there is some sort of locking mechanism in place where Chrome would need to be closed first so that we know we aren't cloning a profile directory which is in a some sort of a mid-state.

Do you see any problems with this approach, @aslushnikov?

**Comment by HairMachine** [comment]
Did you have any luck with this @TomasHubelbauer ? I have a similar issue - I have tried copying the chrome profile but got the same error as using Default, just wondering if you managed to get it working.

**Comment by TomasHubelbauer** [comment]
I don't remember trying it out, so I most likely haven't. It's unfortunate to hear it didn't work for you, I really thought it might be a solution.

**Comment by zhiqinx** [comment]
> Did you have any luck with this @TomasHubelbauer ? I have a similar issue - I have tried copying the chrome profile but got the same error as using Default, just wondering if you managed to get it working.

I had the same issue, it was fixed by the following 2 steps.


1.  run service in Safari(or any other browser except chrome)

2. set the userDataDir to "/Users/YOURNAME/Library/Application\ Support/Google/Chrome/" beware the directory "default" was removed

**Comment by HairMachine** [comment]
Thanks. Yes we came to a similar solution (in our case we used Chromium and copied the Chrome profile across to there).

**Comment by sukrosono** [comment]
A me too, my node is 17.2 pup 10.4 and the lastest chrome on arch linux.
Sadly I want to try use `connect` but also face difficulties there when getting the ws address.
Now I have 2 broken ways

**Comment by maurijnvd** [comment]
> > Did you have any luck with this @TomasHubelbauer ? I have a similar issue - I have tried copying the chrome profile but got the same error as using Default, just wondering if you managed to get it working.
> 
> I had the same issue, it was fixed by the following 2 steps.
> 
> 1. run service in Safari(or any other browser except chrome)
> 2. set the userDataDir to "/Users/YOURNAME/Library/Application\ Support/Google/Chrome/" beware the directory "default" was removed

Hi @zhiqinx  what do you mean by 'run service in safari'? What do i have to run in safari. I didn't really get that.
