### ISSUE TITLE
Minor bug: bad screenshot path says "Unsupported screenshot mime type: null"

### ISSUE THREAD

**Issue by StoneCypher** [puppeteer/puppeteer#4395]
Puppeteer gives a bizarre error message when the path to which you try to write a screenshot is bad: `Unsupported screenshot mime type: null`

The file path is not a mime type issue.

This was previously reported as #3629, but the original reporter closed the report following self diagnosis.

I believe that this is because the file's extension is being used to auto-detect the desired mime type, and I had not set the extension initially.

**Comment by Yokutto** [comment]
Your file path needs to terminate with a image mime-type
Example: /path/to/screenshot **.png**

screenshot.png will be the name of screenshot ;)

**Comment by StoneCypher** [comment]
yes, thanks, that's what i said in my issue

> I believe that this is because the file's extension is being used to auto-detect the desired mime type, and I had not set the extension initially.

that's actually not correct behavior.  mime types are not inferred from file extensions.

also, this error message is badly wrong

**Comment by Lonniebiz** [comment]
In my case, an attempted filename contained a special character not supported by the file system, while the entire attempted filename did indeed end with '.png'. The issue had nothing to do with mime type.

I post here to confirm that this error message can indeed be misleading.

**Comment by StoneCypher** [comment]
This issue is still good.

Stale bot is a terrible practice

**Comment by StoneCypher** [comment]
This issue is still good.

Stale bot is a terrible practice.

**Comment by StoneCypher** [comment]
God damn I hate keeping 3-4 tickets open a day because their authors make
the mistake of running stalebot

**Comment by Lonniebiz** [comment]
I agree with @StoneCypher . Configuring a github project to auto-close issues due to **neglect** is a poor choice that can only lead to additional neglect. Let issues stay open until a human processes them.

However, let's not use the Good Lord's name in vain to emphasize our frustration. You can communicate the same message, just as strong, without being a fucking jackass. For example, I could have said this instead: "You can communicate the same message just as strong, without using profanity".

**Comment by StoneCypher** [comment]
Did I just get religiously shamed on GitHub by someone who feels confident calling strangers "fucking jackass?"

That sure is the way to get moral authority about being polite 😂

**Comment by StoneCypher** [comment]
Oh my, someone who just called me "a fucking jackass" in public also wants me to not use profanity.

And they want me not to use their religion's god's name in vain.  

I wish religious folks would try to keep their abusive behaviors, and their demands for strangers to follow their religious beliefs, out of professional spaces.  ***This is disgraceful.***

You cannot achieve moral authority, Lonnie, by demanding other people not do the thing you yourself are doing.

Please keep your religion to yourself, in the future.  It's not interesting to me if you take moral tips from a bronze age book, and I have no interest in being scolded by a stranger who can't follow their own rules.

No, Lonnie, you don't agree with me.  My position does not support publicly abusing strangers, swearing at them, or making demands that they honor my personal religion.

![image](https://user-images.githubusercontent.com/77482/187729249-5ad95c53-921d-430d-b95c-446bc7f4b332.png)

**Comment by Choco-milk-for-u** [comment]
isnt it already fixed?

**Comment by vhscom** [comment]
> Your file path needs to terminate with a image mime-type
> Example: /path/to/screenshot .png
>
> screenshot.png will be the name of screenshot ;)

Thanks! Works for Playwright too, which has a [`page.screenshot`](https://playwright.dev/docs/screenshots) feature which can also throw `mime type: null`.

**Comment by OrKoN** [comment]
Not reproducible in the latest versions.
