### ISSUE TITLE
Deterministic  PDF creation from same html every time 

### ISSUE THREAD

**Issue by AbilashPais** [puppeteer/puppeteer#4396]
Hi,
wanted to know if there is an option to create same pdf (hash or buffer)  every time by  passing the  same html, if not present can we add an feature to achieve  the same,
Thanks 
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  "puppeteer": "^1.15.0"
* Platform / OS version: ubuntu/windows10
* URLs (if applicable):
* Node.js version: v10.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

`var puppeteer = require('puppeteer');`
`var crypto = require('crypto');`
`
async function genratePDF(htmlString) {`
  `const browser = await puppeteer.launch({ headless: true });`
  `const page = await browser.newPage();`
  `page.setContent(htmlString)`
  `page.emulateMedia('screen');`
  `const pdf = await page.pdf({`
    `format: 'A4'`
  `});`
  `await browser.close();`
  `return pdf`
`}`

`async function compareHashOrBuffer() {`
  `var htmlString = "<h1> Hi, Puppeteer's </h1>";`
  `var buffer1 = genratePDF(htmlString);`
  `var buffer2 = genratePDF(htmlString);`
`
  /*
  expected output buffer1 === buffer2
  */`
`}`

`compareHashOrBuffer()
`
**What is the expected result?**
expecting the buffers to be same
**What happens instead?**
Getting different buffers

**Comment by yotamlaufer** [comment]
Try this:

```
var puppeteer = require('puppeteer');
var crypto = require('crypto');
async function genratePDF(htmlString) {
const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
await page.setContent(htmlString)
await page.emulateMedia('screen');
const pdf = await page.pdf({
format: 'A4'
});
await browser.close();
return pdf
}

async function compareHashOrBuffer() {
var htmlString = "<h1> Hi, Puppeteer's </h1>";
var buffer1 = await genratePDF(htmlString);
var buffer2 = await genratePDF(htmlString);
/* expected output buffer1 === buffer2 */
}

compareHashOrBuffer() 
```

**Comment by AbilashPais** [comment]
Buffer's did not match, gave few seconds gap in generation of buffer.
![image](https://user-images.githubusercontent.com/37572269/57677434-6ff9b400-7644-11e9-960a-86476bf2bfba.png)
