### ISSUE TITLE
How to switch between frame?

### ISSUE THREAD

**Issue by rohmanhm** [puppeteer/puppeteer#440]
Any example to switch between frame? I aim to do something with a certain element on the iframe.

![screen shot 2017-08-21 at 2 40 55 pm](https://user-images.githubusercontent.com/7524911/29508451-d258488a-867e-11e7-8895-90acb19b8a99.png)

**Comment by JoelEinbinder** [comment]
You can use https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageframes to access the frames on the page. Then use `frame.$` to get an element from the frame.

**Comment by rohmanhm** [comment]
@JoelEinbinder ah yeah. Thanks.
I don't see that.

**Comment by rohmanhm** [comment]
@JoelEinbinder Would you give some examples?

**Comment by aslushnikov** [comment]
An example of using frames:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.setContent('<iframe></iframe>');

  // the page.frames()[0] is always a main frame.
  const iframe = page.frames()[1];
  // fetch the body element of the iframe
  const body = await iframe.$('body');
  // ...
  // do something with `body`..
  // ...
  browser.close();
})();
```

Hope it helps.

**Comment by TimeInvestor** [comment]
Hi @aslushnikov,
I followed the example for my page (https://www.zopim.com/landing/simulate?accountId=501LqzN9QKsmkwRNN3eFGZ2TMytZmQnO&subdomain=v2), but I could not do anything with the body. For example, if I use body.focus(), it throws TypeError: body.focus is not a function.
Any advice? 
Thanks.

**Comment by akash8663** [comment]
hi @aslushnikov 
I am migrating my tests from selenium to Puppeteer. My test application is an intranet app, so i won't be able to share much details. We have 2 iframes. I used to write this code in selenium to switch between iframes `driver.switchTo().frame("iframe1");` 
Now coming to puppeteer i am seeing the frame functions are a little sketchy. I have tried 2 codes i found so far to get to my one of the iframes, but wasn't successful. 
```
//Try1
main = page.mainFrame();
console.log('main = '+ main.url());
children = main.childFrames();
```
//OR 
```
//Try2
children = page.frames();`
```
```
//THEN - this to retrieve the url so i can verify i got the right ones
children.forEach(frame => 
console.log('child = '+frame.url());
});
```
The responses i get are:
```
//For Try1
console.log tests/persona.js:98
**main** = https://myApp.com/frameset/v1_0/
console.log tests/persona.js:102
**child** = about:blank
```
```
//For Try2
console.log tests/persona.js:102
**child** = https://myApp.com/frameset/v1_0/
console.log tests/persona.js:102
**child** = about:blank
```
Here are result in chrome console and in chroPath extension of 2 iFrames which i am expecting to get from puppeteer queries:
![iFrameIssue](https://user-images.githubusercontent.com/28462526/69261085-f280a480-0b8e-11ea-9a08-b3198fe77c8d.png)
