### ISSUE TITLE
Incognito mode launches second window

### ISSUE THREAD

**Issue by AlexandreGarino** [puppeteer/puppeteer#4400]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.15
* Platform / OS version: MacOS
* Node.js version: 11.14

**What steps will reproduce the problem?**

I use the `--incognito` flag so the main window is running in incognito mode.

```js
const browser = await puppeteer.launch({ 
    headless: false,
    args: [
          "--incognito"
    ]
});
```

If I create a new page it launches a second chrome window but this window is not in incognito mode.

```js
const page = await browser.newPage();
```

or

```js
const context = await browser.defaultBrowserContext();
const page = await context.newPage();
```

If a create a new Incognito context, it launches a second window in incognito mode.

```js
const context = await browser.createIncognitoBrowserContext();
const page = await context.newPage();
```

Is there a way to create a new page within the main incognito window?

**What is the expected result?**

Open a new page within the main incognito window.

**What happens instead?**

1. Open a new page in a new non-incognito window.
1. Open a new page in a new incognito window.

**References**
* #454 Incognito mode launches second window

**Comment by nigzht** [comment]
@aslushnikov how can we go about fixing this? this is an issue for me as well!

**Comment by aslushnikov** [comment]
> Is there a way to create a new page within the main incognito window?

@AlexandreGarino No, there's no way - that's fundamental limitation on the Chromium side to make sure that sessions don't clash visually.

> how can we go about fixing this? this is an issue for me as well!

@nigzht Unfortunately there are no plans to change this. We mostly focus on browser automation and rely on headful mode for debugging purposes. This behavior doesn't compromise debugging experience - so we'd leave it as-is.

**Comment by stephenjesus** [comment]
**const browser = await puppeteer.launch();**

**const context = await browser.createIncognitoBrowserContext();**

**const page = await context.newPage();**

await page.goto('https://placementmaster.in/');


[PlacementMaster](https://placementmaster.in/)

[Online Dev Tools](https://onlinedevtools.in/)

**Comment by dev-bot-team** [comment]
It doesnt work at all !
try using external browser like Brave browser.
also if using STEALTH plugin it may be the issue but sure nobody cares seems like
