### ISSUE TITLE
ERR_PROXY_CONNECTION_FAILED on Google Search

### ISSUE THREAD

**Issue by bobrain008** [puppeteer/puppeteer#4406]
### Steps to reproduce

* Puppeteer version: **1.15.0**
* Platform / OS version: **CentOS 7.6.1810**
* URLs (if applicable): https://www.google.com/search?q=synology+rs819&source=lnms&tbm=isch&tbs=itp:photo
* Node.js version: **v9.11.2**

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox', '--proxy-server=xx.xx.xx.xxx:3128'] });
  const page = await browser.newPage();
  await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36');
  
  await page.goto('https://www.google.com/search?q=synology+rs819&source=lnms&tbm=isch&tbs=itp:photo', {waitUntil: 'networkidle0', timeout: 60000});
  const html = await page.content();
  //save our html in a file
 fs.writeFile('page.html', html, _ => console.log('HTML saved'));
  await browser.close();
})();
```

**What is the expected result?**
Regularly read/save the related HTML page.

**What happens instead?**
**ERR_PROXY_CONNECTION_FAILED**

```
(node:9890) UnhandledPromiseRejectionWarning: Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.google.com/search?q=synology+rs819&source=lnms&tbm=isch&tbs=itp:photo
    at navigate (/home/myuser/public_html/tmp/pjs/node_modules/puppeteer/lib/FrameManager.js:121:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  -- ASYNC --
    at Frame.<anonymous> (/home/myuser/public_html/tmp/pjs/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/home/myuser/public_html/tmp/pjs/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/home/myuser/public_html/tmp/pjs/node_modules/puppeteer/lib/helper.js:111:23)
    at /home/myuser/public_html/tmp/pjs/usermg.js:10:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:9890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9890) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by theraw** [comment]
![image](https://user-images.githubusercontent.com/32969774/57652722-7c442980-75d0-11e9-9403-4bf1b48acfd3.png)
connection problems are not related to this project when it comes to network because it will just launch chromium browser without you seeing the GUI 

easy words your proxy is dead.

**Comment by bobrain008** [comment]
no, sorry, you need to test by the same settings on CentOS 7
eg. on command line `node myfile.js`

where myfile.js content is the `const puppeteer = require`... and so on...
the proxy works as usual with other web sites, it's running good...so it's not a proxy issue
thanks

**Comment by theraw** [comment]
https://streamable.com/m6bin

"ERR_PROXY_CONNECTION_FAILED" is a browser error which means that your proxy is dead or has limited bandwidth or is very far away from your location and takes too long to connect. nothing related to project..

**Comment by bobrain008** [comment]
in theory you are right, I changed my home proxy IP and it worked.
The weird is in that case, all other web sites worked and that page didn't work...I was thinking about a kind of cache?
The issue was there...every time the web address was that I got the same error while I didn't get it on other pages
so, what's the issue here?
