### ISSUE TITLE
frame.name() empty since release 1.12.0

### ISSUE THREAD

**Issue by intms** [puppeteer/puppeteer#4407]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.15.0
* Platform / OS version: all
* URLs (if applicable):
* Node.js version: 10.10.0

**What steps will reproduce the problem?**
<iframe id="frame-1" src="javascript:''" title="Frame 1 title"></iframe>
<iframe id="frame-2" src="javascript:''" title="Frame 2 title"></iframe>

    const frames = await page.frames();
    console.log('Available frames', frames.map((frame) => frame.name()));

**What is the expected result?**
"frame-1"
"frame-2"

**What happens instead?**
With version 1.11.0:
"frame-1"
"frame-2"

With version 1.12.0 to 1.15.0:
""
""

**Comment by Yokutto** [comment]
Your code run fine for me. However, You can try a different method to do this with this code: 
```javascript
for(let frame of await page.$$('iframe')){
    let Reimu = await frame.contentFrame()
    console.log(Reimu.name())
}
```

**Comment by intms** [comment]
> Your code run fine for me. However, You can try a different method to do this with this code:
> 
> ```js
> for(let frame of await page.$$('iframe')){
>     let Reimu = await frame.contentFrame()
>     console.log(Reimu.name())
> }
> ```

You run with version higher then 1.11.0?

I run your code with version 1.15.0 and Reimu.name() is empty again!

**Comment by Yokutto** [comment]
Yes i'm using Puppeteer higher than 1.11, to be exactly i'm using 1.14, and I think it's not working with your iFrame code because it don't load anything. I tested with this HTML code https://pste.eu/p/14CD.html using this code: 
```javascript 
const puppeteer = require(`puppeteer`);

(async () => {
    const browser = await puppeteer.launch({
      slowMo: 250
    });
    const page = await browser.newPage();
    await page.goto('https://pste.eu/p/14CD.html');

    await page.waitForSelector('iframe', {timeout:5000});
    for(let frame of await page.$$('iframe')){
    let Reimu = await frame.contentFrame();
    console.log(await Reimu.name());
    }

    await browser.close();
})();
```

It's works fine, even with puppeteer 1.11 and 1.15

**Comment by Yokutto** [comment]
If you really needs to get a "Frame name" from this iFrame code, you can use `page.evaluate` instead

example:
```javascript
var j = await page.evaluate(() => {
    var p = [];
    for (let frame of document.querySelectorAll('iframe')) {
        if (frame.getAttribute('name') != null) {
            p.push(frame.getAttribute('name'))
        } else {
            p.push(frame.getAttribute('id'))
        }
    }
    return p;
});
console.log(j)
```

It will return an array of "Frame names" with the selector "iframe", similar what puppeteer does with frame.name()

**Comment by intms** [comment]
> If you really needs to get a "Frame name" from this iFrame code, you can use `page.evaluate` instead
> 
> example:
> 
> ```js
> var j = await page.evaluate(() => {
>     var p = [];
>     for (let frame of document.querySelectorAll('iframe')) {
>         if (frame.getAttribute('name') != null) {
>             p.push(frame.getAttribute('name'))
>         } else {
>             p.push(frame.getAttribute('id'))
>         }
>     }
>     return p;
> });
> console.log(j)
> ```
> 
> It will return an array of "Frame names" with the selector "iframe", similar what puppeteer does with frame.name()

Oh, great, I have all iframe ID with this code!

Thanks.


I also find the problem in my way, if the iframe have a src with javascript (**src="javascript:''"**) the name() return empty!!!  If I remove the javascript in the src all works.

**Comment by aslushnikov** [comment]
Awesome, thanks @Yokutto for helping!

**Comment by tolmasky** [comment]
Did this ever get figured out? As far as I can tell this bug just provides a workaround, not explanation or fix to the issue of the puppeteer API not retuning anything for name.
