### ISSUE TITLE
"Accept" header appears to be overridden using setExtraHTTPHeaders, but isn't

### ISSUE THREAD

**Issue by ha17** [puppeteer/puppeteer#4410]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Laravel Homestead/Ubuntu 4.4.0-66-generic #87
* URLs (if applicable):
* Node.js version: v11.13.0

**What steps will reproduce the problem?**

```js
await eloquaPage.setExtraHTTPHeaders(
        {
            'Accept': 'application/json' // also tried 'accept', accept, Accept, "accept", "Accept"
        });
// let thisResponse = await page.goto(<url>);
// console.log(thisResponse.request().headers()); <= shows the overridden header, as expected
```

**What is the expected result?**
Accept => javascript/json

**What happens instead?** (as logged in a php built-in test server)
[accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3 

I am able to overwrite other headers, and add new headers. If I am doing something wrong, please let me know. I see https://github.com/GoogleChrome/puppeteer/issues/3638 but it was closed without a resolution that I can see.

**Comment by alxgmpr** [comment]
I'm also experiencing this issue with the `accept` header key. 

Running Puppeteer v1.17.0 on OSX 10.14.4 with Node v8.16.0.

Similar to above, I am setting the header but my proxy logs show that it is being set back to `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3` for some reason.

**Comment by nicoandmee** [comment]
` await page.setExtraHTTPHeaders({
      'Accept-Language': 'en-US,en;q=0.9',
      'Accept-Encoding': 'gzip, deflate, br',
    });`

**Comment by alxgmpr** [comment]
@nicoandmee we are trying to set `Accept` not `Accept-Language` or `Accept-Encoding`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

**Comment by mkirkland4874** [comment]
I get the same error. This is how I got around it:

```
await page.setRequestInterception(true);
page.on('request', request => {
  const headers = Object.assign({}, request.headers(), {
    accept: 'application/json',
  });
  request.continue({headers}); // Works
});

const headers = { 'accept': 'application/json' };
await page.setExtraHTTPHeaders(headers); // Does not work
```

**Comment by panthony** [comment]
Not sure if related or not but is that the reason why `accept`, `accept-language` and `accept-encoding` do not appears when you call `request.headers()`?

I'd like to know which headers where sent but the return of this methods seems incomplete...

**Comment by gajus** [comment]
> Not sure if related or not but is that the reason why accept, accept-language and accept-encoding do not appears when you call request.headers()?

I have raised an issue https://github.com/puppeteer/puppeteer/issues/5364

**Comment by kyrylo** [comment]
This is still an issue for me with Puppeteer v17.1.3.

**Comment by esimakov68** [comment]
Faced this problem with Puppeteer v19.4.0
