### ISSUE TITLE
Handle cookies in request interceptor when cors request was happened

### ISSUE THREAD

**Issue by lavcraft** [puppeteer/puppeteer#4413]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.15.0
* Platform / OS version: OSX 10.14.4
* Node.js version: 10.4.1

**What steps will reproduce the problem?**
Try run next code:
```javascript
        await page.goto('http://localhost:3000');
        await page.setRequestInterception(true);

        await page.setCookie({name: 'userId', value: 'my-user-id'});

        page.on('request', interceptedRequest => {
            if (interceptedRequest.url().endsWith('/some-api')) { //send cors request to localhost:8080/some-api
                const cookie = interceptedRequest.headers()['Cookie']; //undefined
                expect(cookie).toContain('userId'); //wrong, because cookie header is undefined
                interceptedRequest.continue();
            }
        });
```

With next puppeteer configuration:
```
    launch: {
        dumpio: process.env.HEADLESS === 'false',
        headless: process.env.HEADLESS !== 'false',
        slowMo: 20,
        args: [
            '--disable-web-security',
            '--disable-features=IsolateOrigins,site-per-process',
            '--disable-site-isolation-trials'
        ]
    }
```
1. Run code above
2. Cookie is always empty

**What is the expected result?**
Expect that cookie should contain in request headers

**What happens instead?**
Cookie header is undefined

**Comment by evanrolfe** [comment]
This is happening for me as well.

**Comment by evanrolfe** [comment]
@lavcraft I'm currently using a work-around for this bug by storing the cookies from the page in a variable like this:
```js
const cookies = page.cookies().map((cookie) => { return `${cookie.name}=${cookie.value}`; }).join('; ');
```
You can then use them in with the intercepted request i.e.
```js
page.on('request', interceptedRequest => {
  const headers = interceptedRequest.headers();
  headers.cookie = cookies;
  
  console.log(headers);

  interceptedRequest.continue();
});
```

**Comment by osmenia** [comment]
> @lavcraft I'm currently using a work-around for this bug by storing the cookies from the page in a variable like this:
> 
> ```js
> const cookies = page.cookies().map((cookie) => { return `${cookie.name}=${cookie.value}`; }).join('; ');
> ```
> 
> You can then use them in with the intercepted request i.e.
> 
> ```js
> page.on('request', interceptedRequest => {
>   const headers = interceptedRequest.headers();
>   headers.cookie = cookies;
>   
>   console.log(headers);
> 
>   interceptedRequest.continue();
> });
> ```

Hi, 
can you pls tell me why does not work for me. 

const cookies = page.cookies().map((cookie) => { return `${cookie.name}=${cookie.value}`; }).join('; ');

Error: UnhandledPromiseRejectionWarning: TypeError: page.cookies(...).map is not a function

**Comment by merapi** [comment]
> > @lavcraft I'm currently using a work-around for this bug by storing the cookies from the page in a variable like this:
> > ```js
> > const cookies = page.cookies().map((cookie) => { return `${cookie.name}=${cookie.value}`; }).join('; ');
> > ```
> > 
> > 
> > You can then use them in with the intercepted request i.e.
> > ```js
> > page.on('request', interceptedRequest => {
> >   const headers = interceptedRequest.headers();
> >   headers.cookie = cookies;
> >   
> >   console.log(headers);
> > 
> >   interceptedRequest.continue();
> > });
> > ```
> 
> Hi,
> can you pls tell me why does not work for me.
> 
> const cookies = page.cookies().map((cookie) => { return `${cookie.name}=${cookie.value}`; }).join('; ');
> 
> Error: UnhandledPromiseRejectionWarning: TypeError: page.cookies(...).map is not a function

You need to await for the cookies part:

```js
const cookies = (await page.cookies()).map((cookie) => { return `${cookie.name}=${cookie.value}`; }).join('; ');
```

**Comment by linthertoss** [comment]
Can't seem to get cookies from ` interceptedRequest.headers();`
But if you want to get all cookies from page, So you can:
<pre>page._client.send('Network.getAllCookies')</pre>
It return all cookies from your page
