### ISSUE TITLE
No way to inspect content of request with FormData payload

### ISSUE THREAD

**Issue by WattyRev** [puppeteer/puppeteer#4414]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: macOSX Mojave
* URLs (if applicable):
* Node.js version: v8.15.0

**What steps will reproduce the problem?**

I have a process in React that looks something like this:

```javascript
handleButtonClick() {
  const payload = new FormData();
  payload.append('foo', someFileBlobContent);
  payload.append('notes', 'Some notes');
  axios.post('/my-api/', payload);
}
```
When a button is clicked, some data is compiled as FormData, then sent as the payload in a POST request to an API.

In my Jest/Puppeteer tests, I'm trying to confirm that the request contains the data that it should:
```javascript
page.click('.my-button');

await page.waitForRequest(request => {
  if (request.url().match(/my-api/) && request.method() === 'POST') {
    expect(request.postData()).toBeDefined();
    expect(JSON.parse(request.postData()).notes).toEqual('Some notes');
    return true;
  }
});
```

In this scenario `request.postData()` is undefined. 
When running the process in Chrome, I can see the FormData displayed in the network requests via Chrome devtools, so I know the data is being sent, but I'd like to assert it.

**What is the expected result?**
For `postData()` or some other method to provide the request's form data that is visible in the dev tools.

**What happens instead?**
`postData()` returns `undefined` and no other methods are available that would provide this information.

**Comment by centaur54dev** [comment]
Bump.

**Comment by ChristianUlbrich** [comment]
I have the same problem and the use case does not seem to so far-fetched. Not, that I'd be keen on parsing multi-part-form-data myself; but as an alternative could we get access to the raw req.body?
