### ISSUE TITLE
[Feature request] Make it possible to control the zoom level via the API

### ISSUE THREAD

**Issue by 36degrees** [puppeteer/puppeteer#4419]
### Steps to reproduce

It would be great if you could control the [zoom level](https://support.google.com/chrome/answer/96810?hl=en-GB) via the API. Perhaps as part of `setViewport` or with a new function call.

**What is the expected result?**

You should be able to control the zoom level via the API.

**What happens instead?**

You cannot control the zoom level 😁

**Comment by aslushnikov** [comment]
@36degrees what's the usecase for zoom?

**Comment by 36degrees** [comment]
In our specific use case, we want to ensure that we're meeting [Web Content Accessibility Guidelines 2.1 1.4.10 - Reflow] – which basically means that the content on the page is still legible when the browser is zoomed to 400%.

Being able to automate this using Puppeteer (e.g. as part of a visual regression suite, though at the minute I just want to automate ad-hoc screenshots) would be really handy.

**Comment by JoelEinbinder** [comment]
Zoom is exposed to the web platform as window.devicePixelRatio. You can already set this with `page.setViewport`

**Comment by 36degrees** [comment]
That doesn't appear to do the same thing as zooming the page – specifically, in my testing at least, it didn't appear to trigger breakpoints.

**Comment by aslushnikov** [comment]
@JoelEinbinder the `zoom` discussed here is what we call `"scale"` in chromium-land.

@36degrees since there's not much demand for this, I'd recommend you falling back to the raw devtools protocol for this.

There's a method [`Emulation.setPageScaleFactor`](https://vanilla.aslushnikov.com/?Emulation.setPageScaleFactor) that let's you do what you want. 

> **BEWARE!** [`Emulation.setPageScaleFactor`](https://vanilla.aslushnikov.com/?Emulation.setPageScaleFactor) is an experimental method, so it might change/go away in some future Chromium releases.

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://vanilla.aslushnikov.com');
  const session = await page.target().createCDPSession();
  await session.send('Emulation.setPageScaleFactor', {
    pageScaleFactor: 4, // 400%
  });
})();
```

If there's more demand in future, we can actually expose the method to Puppeteer and commit to its support.

Hope this helps.

**Comment by latentstops** [comment]
`await session.send('Emulation.setPageScaleFactor', {
    pageScaleFactor: 0.75
});`
I tried to set `pageScaleFactor` to `0.75` but nothing happened.  
Is there a way to set scale to 75%?

**Comment by soend** [comment]
Also tried this workaround with `await session.send('Emulation.setPageScaleFactor', { pageScaleFactor: 4, // 400% });` but it seems to not work anymore.

**Comment by dohyung97022** [comment]
2020/12/09
zooming in is possible, but I am not sure how to zoom out, as latentstops says.

**Comment by Yakov-Shechter** [comment]
@soend @latentstops @36degrees 
You can add the args: _"--force-device-scale-factor=1.5"_ - which equal to 150% zoom in.

**Comment by ssaadh** [comment]
@yanivefraim most people are asking for zooming out, not zooming in.

**Comment by Yakov-Shechter** [comment]
> @yanivefraim most people are asking for zooming out, not zooming in.

@inoicouldalwaysturn2u - I guess you replied to me (and not to @yanivefraim since he is not exists in this thread).
Did you checked that "--force-device-scale-factor="**0.x**" is not giving you the zooming out result?

**Comment by GavinJoyce** [comment]
I managed to get zooming out working using both the `--force-device-scale-factor` flag and:

```
await page.setViewport({
  width: 1920,
  height: 1080,
  deviceScaleFactor: 0.75
});
```

**Comment by mtekman** [comment]
const desiredWidth = 1920;
    const desiredHeight = 1080;
    const sf = 0.75;

    await page.setViewport({
        width: parseInt(desiredWidth / sf),
        height: parseInt(desiredHeight / sf),
        deviceScaleFactor: sf,
    });

For anyone wishing to preserve the dimensions whilst scaling
