### ISSUE TITLE
puppeteer from html to pdf arabic fonts are not showing

### ISSUE THREAD

**Issue by syednoor6208** [puppeteer/puppeteer#4424]
delete all npm modules and packagelock.json then do npm install arabic text is showing junk values.
![Screenshot 2019-05-14 at 4 35 49 PM](https://user-images.githubusercontent.com/30065880/57693237-5bc6ae80-7666-11e9-8ad7-562c3946dec9.png)

**Comment by DvdGiessen** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/4364#issuecomment-488156148. Seems this was caused by 27c9f754b17045571e049a6bd48009f8f6908e0f.

A minimal testcase:

```js
const fs = require('fs');
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent('😃');
    fs.writeFileSync('out.png', await page.screenshot());
    await browser.close();
})();
```

When run using 1.15, this correctly outputs:
![out_1_15](https://user-images.githubusercontent.com/954385/57694089-2791c480-764b-11e9-91a2-81257ce05bec.png)

When run using 1.16, which includes mentioned commit, this incorrectly outputs:
![out_1_16](https://user-images.githubusercontent.com/954385/57694099-29f41e80-764b-11e9-9ed1-c1b1fbad5f4f.png)

@aslushnikov

**Comment by zeeshanaligold** [comment]
Hi @syednoor6208 
     Having same issue with me! did you fix?

**Comment by syednoor6208** [comment]
> Hi @syednoor6208
> Having same issue with me! did you fix?

Not yet...

**Comment by syednoor6208** [comment]
Hi @zeeshanaligold i have old "puppeteer" node_modules which is working fine...
file is very big i can share via wetransfer, if required share ur email id.

**Comment by zeeshanaligold** [comment]
Hi @syednoor6208 
     Yea, i know puppeteer v(1.15) is working perfect. Just issue in v1.16. 
Thanks,

**Comment by kzkn** [comment]
I have same issue.

> Yea, i know puppeteer v(1.15) is working perfect. Just issue in v1.16.

It's also same.

**Comment by semoal** [comment]
Same issue here with Spanish accents.

**Comment by semoal** [comment]
I got a fix, i'll post a pull request in a while!

**Comment by SWGFL** [comment]
Same issue here, v1.15.0 arabic and UTF-8 characters exported as a PDF come out correctly, v1.16.0 it is all messed up.

**Comment by Kenshinhu** [comment]
Same issue here @v1.16

**Comment by saintego** [comment]
It's broken again in 1.20. In 1.19 works fine

**Comment by bartlomiejzuber** [comment]
Same issue here @v.1.20

**Comment by codingedgar** [comment]
Right now I'm trying to do `await page.type(' \u0000 ');` but when I get the value of the element:
```ts
 return page
    .$(selector)
    .then(el => {
      return el?.evaluate(el => {
          return (el as HTMLTextAreaElement).value;
```
I only get the spaces.

To be more accurate, I type : [32, 0 ,32] chars but I get [32, 32] , the 0 is missing, not sure why.
