### ISSUE TITLE
Charset problem

### ISSUE THREAD

**Issue by dusanmarsa** [puppeteer/puppeteer#4425]
```javascript
        const puppeteerBrowser = await puppeteer.launch({ args: ['--no-sandbox'] })
        const puppeteerPage = await puppeteerBrowser.newPage()
        await puppeteerPage.setContent(html, { waitUntil: 'networkidle0' })
        const pdfstring = await puppeteerPage.pdf({
            displayHeaderFooter: false,
            printBackground: true,
            format: 'A3'
        })

        res.setHeader('Content-disposition', `attachment; filename=${page}.pdf`);
        res.setHeader('Content-type', 'aplication/pdf');
        res.end(pdfstring)

        await puppeteerBrowser.close()
```

If i generate PDF using code above, than wrong charset is used. In html code is specificly added meta tag `<meta charset="utf-8"/>` and I can`t find any option in puppeteer to specify otherwise.

**Comment by dusanmarsa** [comment]
I updated code and still not working. HTML is fine and it break at `.setContent()` method. Can anyone please help here? :)

viz. img broken text
![image](https://user-images.githubusercontent.com/20325057/57768171-5bccba00-770b-11e9-9672-a113ff1e16ab.png)
EXPECTED: "VZDĚLÁNÍ"

---
```javascript
await puppeteerPage.setExtraHTTPHeaders({
   'accept-language': 'cs-CZ,cs;q=0.8'
});
```
----
```javascript
puppeteer.launch({ args: ['--no-sandbox', '--lang=cs-CZ,cs'] })
```

nothing, works.

**Comment by DvdGiessen** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/4424#issuecomment-492196710. For the time being, installing the previous version ([v1.15.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v1.15.0)) does seem to resolve the issue.

**Comment by semoal** [comment]
Duplicated issue mate, close it please. https://github.com/GoogleChrome/puppeteer/issues/4424

**Comment by dusanmarsa** [comment]
@DvdGiessen, @semoal,

Perfect guys. I must be dumb. :) 

### PROBLEM SOLVED

**Comment by puneetkansal04** [comment]
@dusanmarsa How have you resolved it
