### ISSUE TITLE
"WebSocket is not open: readyState 3" when calling Browser.newPage() on long-running browser instance

### ISSUE THREAD

**Issue by hjdarnel** [puppeteer/puppeteer#4428]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Docker image buildkite/docker-puppeteer@1.8.0 (which uses a Node base image node:10.9.0-slim@sha256:b269112ab0cd9dc8760ff406a07cf91f508257b3473031b414817e0c152c0744)
* Node.js version: Node 10

I have a service that executes `puppeteer.launch({})` with args on setup, and then continues to use the returned instance of the Browser to load HTML on requests using `browser.newPage()`. Then I use `page.pdf()` to render a PDF of the page, and then `page.close()`. The same instance of the Browser is used throughout the life of the service instance.

Recently we've been noticing `WebSocket is not open: readyState 3` error logs when calling `browser.newPage()`. This seems to happen after thousands of requests have succeeded before. Once it springs up, it seems to consistently fail to create a `newPage`, as in that browser instance is "no good' anymore.

What's the best way to detect that the Browser is prepared for a newPage call? Or would it be better to create the browser instance, and then on subsequent requests connect to it, do my work, and then disconnect, with error handling to relaunch the browser if the `connect()` call fails? I know we have access to the browser process, but I'm not sure how to determine whether it's "good" or not.

I can provide a simplified version of our code if needed. In the interim I'm going to upgrade to a more recent version.

Thanks!

**Comment by caijw** [comment]
I also encountered this problem.

**Comment by aslushnikov** [comment]
> Recently we've been noticing WebSocket is not open: readyState 3 error logs when calling browser.newPage(). This seems to happen after thousands of requests have succeeded before. Once it springs up, it seems to consistently fail to create a newPage, as in that browser instance is "no good' anymore.

@hjdarnel This likely means that the browser has crashed and thus socket got closed. In this case, you should've received the [`browser.on('disconnected')`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-event-disconnected) event - do you subscribe to it?

> What's the best way to detect that the Browser is prepared for a newPage call?

I'd say to subscribe to the `"disconnecteed"` event and handle it appropriately - with re-starting the shared browser you use.

Hope this helps!

**Comment by hjdarnel** [comment]
Thank you, Andrey! Yes, we've fixed this by subscribing to that event. Below is our setup function which calls itself on disconnection (for others that run into this):

```js
const setup = async () => {
    browser = await puppeteer.launch({
        args: ['--disable-gpu', '--no-sandbox', '--disable-dev-shm-usage']
    });

    browser.on('disconnected', setup);

    logger.info(`Started Puppeteer with pid ${browser.process().pid}`);
};
```


This has worked well at production load for a few weeks now.
