### ISSUE TITLE
Unable to install puppeteer in windows 7

### ISSUE THREAD

**Issue by amjadalibb** [puppeteer/puppeteer#4429]
I am getting below error when I am trying to install puppeteer on windows 7 using windows powers shell.

Node version: v12.2.0

PS D:\repositories\STME-6300-sme-travels-tests\sme-ui-regression-tests\e2e-tests> npm install puppeteer
npm ERR! Unexpected end of JSON input while parsing near '...npmjs.org/ws/-/ws-2.2'

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\619435\AppData\Roaming\npm-cache\_logs\2019-05-14T23_17_28_235Z-debug.log

Below is the log:
[2019-05-14T23_17_28_235Z-debug.log](https://github.com/GoogleChrome/puppeteer/files/3180253/2019-05-14T23_17_28_235Z-debug.log)

**Comment by semoal** [comment]
Thy this and reinstall ```npm cache clean --force```
This package it's used in hundred of environments and i'm sure if Windows users had issues installing it would be a bigger issue.

So, please check your local environment that looks it's the main cause here.
