### ISSUE TITLE
Request: browser.currentPage() or similar way to access Pages

### ISSUE THREAD

**Issue by karelrochelt** [puppeteer/puppeteer#443]
I was playing around with Puppeteer today and I found out that there is no way (that I know of) to run script like this:
```
const puppeteer = require('puppeteer');

puppeteer.connect({browserWSEndpoint: <endpoint>}).then(async browser => {
  const page = await browser.currentPage();
  // other actions that would manipulate the current page
  browser.close();
});
```

The only way to get a Page instance seems to be browser.newPage() which is rather inconvenient if I want to run several test scripts that all connect to one browser instance.

**Comment by JoelEinbinder** [comment]
This is related to #386

I was thinking we should fire an event when the first tab is created in the browser, or have browser.pages() return all pages.

**Comment by karelrochelt** [comment]
browser.pages() would be great!

**Comment by PsychoXIVI** [comment]
Still there is no function to get current page, or at least check is active?

**Comment by AgainPsychoX** [comment]
To find current page (still no official function, someone can push it):

```js
	browser.currentPage = async function () {
		let targets = await this.targets();
		for (let i = 0, I = targets.length; i < I; ++i) {
			target = targets[i];
			let page = await target.page();
			if (page) {
				return page;
			}
		}
		return null;
	}
```

**Comment by mkolinichenko** [comment]
So, is there a way to access the current page (i.e. page on active browser tab)? 
Right now I'm using something like this:
```javascript
    async function getActivePage(browser, timeout) {
        var start = new Date().getTime();
        while(new Date().getTime() - start < timeout) {
            var pages = await browser.pages();
            var arr = [];
            for (const p of pages) {
                if(await p.evaluate(() => { return document.visibilityState == 'visible' })) {
                    arr.push(p);
                }
            }
            if(arr.length == 1) return arr[0];
        }
        throw "Unable to get active page";
    }
```
But it doesn't seem very robust.

**Comment by aslushnikov** [comment]
@mkolinichenko What's your usecase? IIRC headless considers all pages to be active.

**Comment by mkolinichenko** [comment]
@aslushnikov, thanks for the response. I'm running headfull, trying to combine user interaction with some automation. User switches tabs manually and at some point my app needs to know which tab/page/at least url we're currently on.

**Comment by aslushnikov** [comment]
@mkolinichenko I see, thanks.

We don't have this signal in [DevTools protocol](https://vanilla.aslushnikov.com/) atm. You can file a new issue here, and If there is enough demand we'll add it.

If you don't want to wait, you can add a missing event to DevTools protocol, this will require contributing  upstream to Chromium. Once we have an event, we can expose it through Puppeteer.

**Comment by mkolinichenko** [comment]
Ok, thanks for the clarification. I'll look into Chromium sources.

**Comment by MehbubRashid** [comment]
I have figured out a solution.It will work for the latest page(tab) you open.

```javascript
var page = await browser.targets()[browser.targets().length-1].page();
console.log(page.url());
//or page.anyfunction();
```

By using this code,everytime you navigate to another url using **page.goto()** function,you will be able to see the url of that current page.

**Comment by allenhwkim** [comment]
To get the first page of the current browser
```
const page = (await browser.pages())[0];
```

**Comment by mgrybyk** [comment]
Using [document.hidden](https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden)
```js
const pages = await browser.pages()
let page
for (let i = 0; i < pages.length && !page; i++) {
    const isHidden = await pages[i].evaluate(() => document.hidden)
    if (!isHidden) {
        page = pages[i]
    }
}
```

**Comment by yegor211** [comment]
> Using [document.hidden](https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden)
> 
> ```js
> const pages = await browser.pages()
> let page
> for (let i = 0; i < pages.length && !page; i++) {
>     const isHidden = await pages[i].evaluate(() => document.hidden)
>     if (!isHidden) {
>         page = pages[i]
>     }
> }
> ```

would this work if there will be two windows opened?

**Comment by mgrybyk** [comment]
It works, try it

**Comment by yegor211** [comment]
> It works, try it

Thanks, I'm gonna try this later when I'll set my app up and will get back with results.

**Comment by NewSense21** [comment]
> @aslushnikov, thanks for the response. I'm running headfull, trying to combine user interaction with some automation. User switches tabs manually and at some point my app needs to know which tab/page/at least url we're currently on.

I have a similar use case wherein I have connected puppeteer to existing chrome window via --remote-debugging-port=9222
I open multiple tabs with different URLs manually and now I want to know the URL of the current active tab.

https://github.com/puppeteer/puppeteer/issues/443#issuecomment-437689144 -> won't be helpful as this returns the last tab url, not the current active one. This will break if the tab in which the latest url is visited is not the last one.
Other listed solutions are flaky.

Are there any other possible solutions to solve this?

**Comment by NewSense21** [comment]
The following solution works for [this usecase](https://github.com/puppeteer/puppeteer/issues/443#issuecomment-816161784). This helps to get the URL using puppeteer in case whenever URL is updated.

1. Emitted when a new target is created inside the browser context - `targetcreated`
2. Emitted when a frame within the page is navigated to a new URL - `framenavigated`
```js
browser.addListener('targetcreated', async function (event) {
  let page = await event.page();
  page.on('framenavigated', async function (frame) {
    const url = await frame.url();
    // validate URL and do something
  });
});
```

**Comment by hunterxxx** [comment]
Do you mean accessing the first page, especially when it's first loaded?
`const page = (await browser.pages())[0];`

**Comment by QGB** [comment]
pyppeteer

**Comment by alexsunday** [comment]
> It works, try it

if opened two windows, it cannot be work.

**Comment by tanhh326** [comment]
https://chromedevtools.github.io/devtools-protocol/

const browser = await puppeteer.launch({
            headless: false
 });
const url = new URL(browser.wsEndpoint());
const host = url.hostname;
const port = url.port;

fetch `http://${host}:${port}/json`, The first item in the list is the current tab.

**Comment by pirate** [comment]
I have opened a new chromium bug tracker issue to add a CDP command to chrome that will allow querying for active/foreground targetId as well as other things supported by `chrome.tabs.query(...)`. The intention is for libraries like `chrome-devtools-mcp`, `puppeteer`, `playwright`, `stagehand`, `browser-use`, etc. to be able to use this to properly track foreground tab state, tab order, tab groups, etc. without resorting to hacks like trying to traack `document.onfocus`.

Please upvote/comment over there if you want this feature added! We need it implemented at the CDP layer in order for the driver libraries to be able to provide accurate focus tracking.

- https://issues.chromium.org/issues/497896141
- https://github.com/puppeteer/puppeteer/issues/14493
- https://github.com/ChromeDevTools/chrome-devtools-mcp/issues/933

<img width="1031" height="497" alt="Image" src="https://github.com/user-attachments/assets/7f559cdf-370e-4538-9255-3d5616b559f9" />

<img width="404" height="154" alt="Image" src="https://github.com/user-attachments/assets/7f8352e4-05ab-47b6-ad3c-79e4871c7736" />
