### ISSUE TITLE
Question - how to differentiate between tabs

### ISSUE THREAD

**Issue by therepo90** [puppeteer/puppeteer#4434]
Hello there thanks for this awesome tool.
How Do chrome maintain connections between tabs ? I want to differentiate between tabs connection when using proxies. So I want to know when first tabs is doing request and when second tab is doing other requests. Problem is because one page may contain multiple resources but for given tab

**Comment by meivinay** [comment]
Hey , did you got the solution? I am also having similiar problem.. hardly any satisfying solution is found

**Comment by therepo90** [comment]
Going with pupeteer-cluster or just using one tab and running whole browser with one proxy was my solution to this
