### ISSUE TITLE
Improve puppeteer code by ordering methods.

### ISSUE THREAD

**Issue by UrielCh** [puppeteer/puppeteer#4435]
Hi,

I'm currently upgrading puppeteer Typescript typing, So I had to read all the code source of the project.

puppeteer have a lot of proxy function ie: `$eval`, `$$eval` `$`, `$$`, `$x`... that are present in a lot of classes (for those functions: `DOMWorld`, `Frame`, `JSHandle`, `ElementHandle`, `Page`)

but in each file those function are declared within a different order.

ex:
in `DOMWorld.js`
```javascript
  /**
   * @param {Function|string} pageFunction
   * @param {!Array<*>} args
   * @return {!Promise<!Puppeteer.JSHandle>}
   */
  async evaluateHandle(pageFunction, ...args) {
  //...
  }
  /**
   * @param {Function|string} pageFunction
   * @param {!Array<*>} args
   * @return {!Promise<*>}
   */
  async evaluate(pageFunction, ...args) {
  // ...
  }
```

in file `ExecutionContext.js`

```javascript
  /**
   * @param {Function|string} pageFunction
   * @param {...*} args
   * @return {!Promise<(!Object|undefined)>}
   */
  async evaluate(pageFunction, ...args) {
  // ...
  }

  /**
   * @param {Function|string} pageFunction
   * @param {...*} args
   * @return {!Promise<!JSHandle>}
   */
  async evaluateHandle(pageFunction, ...args) {
  //...
  }
```

can you please order them so they will be all the time in the same order ?
PS: Alphabetic order is the easiest 😀

thx.

**Comment by semoal** [comment]
Feel free to do this changes, and submit a pull request.

**Comment by UrielCh** [comment]
That can be done with a linter, but that change will break all the current PR.
[eslint-plugin-sort-class-members](https://www.npmjs.com/package/eslint-plugin-sort-class-members)
So, first I'm asking.

**Comment by aslushnikov** [comment]
@UrielCh how would the ordering help you with what you're doing?

> PS: Alphabetic order is the easiest 😀

Let's not do alphabetic ordering - it's not very logical when it comes to reading code.
