### ISSUE TITLE
Different font render result on Windows10 vs Lambda-puppeteer

### ISSUE THREAD

**Issue by ksyke** [puppeteer/puppeteer#4437]
Good day,

Sorry if this might be a bit confusing.
Basically I wanna use puppeteer to open a page that generates an image from a canvas in the page, but I have some inconsistencies with the font rendering. Are fonts rendered differently when launched in serverless-chrome-lambda(puppeteer) compared to chrome launched locally (Windows10)?
Note that puppeteer isn't used on local test only during the execution of lambda function.

* Puppeteer version: 1.11.0
* Platform / OS version: AWS Lambda
* Node.js version: 8.10

These are samples of images generated from the same page.
**What is the expected result?**
**Generated from local test (Windows10)**
![localtest](https://user-images.githubusercontent.com/50691802/57842111-7469cc80-77fe-11e9-97ec-37bab3e2fd4c.png)

**What happens instead?**
**Generated from Lambda function**
![lambdatest](https://user-images.githubusercontent.com/50691802/57842120-7895ea00-77fe-11e9-8aac-17346d45c816.png)

As you can see on the images, position and width calculation are different.

**Comment by boris-ananyevsky** [comment]
Could be related to #4177

**Comment by aslushnikov** [comment]
Font rendering *is* different on different platforms. That's not a bug.

The only way to have a consistent font rendering across environments is to run Puppeteer in a docker container.

**Comment by elainema** [comment]
how did you deploy on AWS ?  deployment package size(unzipped) easily go's above 250 mb because When you install Puppeteer, it downloads a recent version of Chromium (~170MB Mac, ~282MB Linux, ~280MB Win) that is guaranteed to work with the API.

**Comment by ksyke** [comment]
@elainema 
I used this template: https://github.com/serverless/examples/tree/master/aws-node-puppeteer
It uses the plugin `serverless-plugin-chrome`, worked well for me. Try testing with that one

**Comment by elainema** [comment]
> @elainema
> I used this template: https://github.com/serverless/examples/tree/master/aws-node-puppeteer
> It uses the plugin `serverless-plugin-chrome`, worked well for me. Try testing with that one

did u use proxy  with serverless-plugin-chrome ?

**Comment by ghost** [comment]
@elainema
you can use `chrome-aws-lambda` & `puppeteer-core` to limit the size on AWS
