### ISSUE TITLE
UTF-8 characters are not resolved in Puppeteer 1.16.0

### ISSUE THREAD

**Issue by ecattez** [puppeteer/puppeteer#4439]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.16.0
* Platform / OS version: MacOSX
* URLs (if applicable): nope :/
* Node.js version: 11.6.0

**What steps will reproduce the problem?**

I recently upgrade my local puppeteer version from 1.14 to the latest release.

Based on the template below, UTF-8 characters are not resolved. It seems that the page is in ASCII.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Some title</title>
</head>
<body>
    àé
</body>
</html>
```

**What is the expected result?**

I should get a page with the content `àé`.

**What happens instead?**

I get a page with the content `Ã Ã©` instead.

**Comment by robertosousa1** [comment]
I have the same problem

**Comment by semoal** [comment]
https://github.com/GoogleChrome/puppeteer/issues/4424
Duplicated please close this issue, and post in the other.
