### ISSUE TITLE
page.evaluate() not called 2nd time

### ISSUE THREAD

**Issue by ryanVincent** [puppeteer/puppeteer#444]
If I:

1. evaluate a page
```await page.evaluate(() => {});```
2. click a button which causes the browser to redirect to a new url.
```await page.click('submit_button_selector');```
3. wait for a selector to appear
```await page.waitForSelector('selector_on_next_page');```
4. try and evaluate the page again
```await page.evaluate(() => {});```

The callback supplied to the 2nd page.evaluate function is never executed.

**Comment by vsemozhetbyt** [comment]
@ryanVincent 
Maybe you need to `page.waitForSelector()` for `submit_button_selector` as well? Can you provide a code? I cannot reproduce with this one:
```js
'use strict';

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.goto('http://example.com/');
console.log(await page.evaluate(() => location.href));

await page.click('a[href]');

await page.waitForSelector('#logo');
console.log(await page.evaluate(() => location.href));

browser.close();

})();
```
```console
http://example.com/
https://www.iana.org/domains/reserved
```

**Comment by pavelfeldman** [comment]
Could you confirm that `submit_button_selector` in your sample takes you to another page on another host? It might be due to cross-process navigation.

**Comment by jsnanigans** [comment]
perhaps the `waitForSelector` on point 3 never fires, try to put a console.log after to test it.

**Comment by vsemozhetbyt** [comment]
@jsnanigans You can also try `puppeteer.launch({ headless: false })` to see what actually happens.

**Comment by ryanVincent** [comment]
The issue was not with `page.evaluate`. I was trying to `console.log`within the callback and it was getting swallowed somewhere.
