### ISSUE TITLE
page.evaluate hangs on Args key has unicode char

### ISSUE THREAD

**Issue by leexr** [puppeteer/puppeteer#4443]
### Steps to reproduce
Calling await page.evaluate() hangs on Args key has unicode char
**Tell us about your environment:**

* Puppeteer version: 1.16.0
* Platform / OS version: windows10 1809
* URLs (if applicable):
* Node.js version: 8.16.0

**What steps will reproduce the problem?**
```js
const puppeteer = require("puppeteer");

(async () => {
    const browser = await puppeteer.launch()
    try {
        const page = await browser.newPage();
        console.log("wait evaluate");
        await page.evaluate(() => { }, {"中文字符": 1 })
    } finally {
        browser.close();
    }
})()
```

**What is the expected result?**
 `await page.evaluate(() => { }, {"中文字符": 1 })` should resolve quickly !

**What happens instead?**
Script hangs on line 8

**Comment by JoelEinbinder** [comment]
Does it hang forever? Or just take a really long time?

**Comment by JoelEinbinder** [comment]
Looks like a Chromium bug with devtools protocol. @caseq

**Comment by powdercloud** [comment]
I have a fix for it. Will need to roll it into Chromium / V8.
https://chromium-review.googlesource.com/c/deps/inspector_protocol/+/1618460

**Comment by powdercloud** [comment]
The rolls have completed so this is fixed in the most recent code.
https://chromium.googlesource.com/chromium/src/+/4d6ba8d56dcc5633a792b1776cf58fcc628f5997
https://chromium.googlesource.com/v8/v8/+/889b4ded6e441b672cc39ff3e766bda8c3abc059

**Comment by JoelEinbinder** [comment]
Awesome! Thanks

**Comment by aslushnikov** [comment]
> Looks like a Chromium bug with devtools protocol.

This is indeed regressed with CBOR patch: https://crrev.com/646503

> I have a fix for it. Will need to roll it into Chromium / V8.
> https://chromium-review.googlesource.com/c/deps/inspector_protocol/+/1618460

@powdercloud Unfortunately, the fix didn't help (I tried r661151). Let me add a failing test for this so that it's easier to verify for you.

**Comment by powdercloud** [comment]
I think it's because v8 hasn't rolled into Chromium yet, so if you just checkout Chromium it won't have the fix for v8. However, you can checkout Chromium, change into it's src/v8, and in there, checkout master, run git pull - building headless_shell with that should do the trick.
Thanks a lot for adding a puppeteer test. I'll play with it on Monday (by then, v8 inside Chromium should be up to date).

**Comment by aslushnikov** [comment]
@powdercloud indeed, you were right!
