### ISSUE TITLE
goto takes an increasing amount of time.

### ISSUE THREAD

**Issue by knokknok** [puppeteer/puppeteer#4449]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.16.0
* Platform / OS version: macOS 10.14.4
* URLs (if applicable):
* Node.js version: v12.1.0

**What steps will reproduce the problem?**

```const path = require('path');
const puppeteer = require('puppeteer');
var fs = require('fs');
fs.writeFileSync("/tmp/test.html", '<!DOCTYPE HTML>\n<HTML>\n<HEAD></HEAD>\n<BODY>\n<p>Hello World</p>\n</BODY>\n</HTML>\n');

var time=Date.now();
(async () => {
    const browser = await puppeteer.launch();
    page = await browser.newPage();
    for(var i=1; i<10000000; ++i) {
        if (i%1000==0) {
            console.log((Date.now()-time)/1000);
            time=Date.now();
        }
        await page.goto('file:///tmp/test.html');
    }
    await page.close();
    await browser.close();
})()
```

**What is the expected result?**

Time to process the page should remain stable

**What happens instead?**

Duration increases and it eventually times out:
```
10.509
10.128
12.785
14.21
13.737
21.081
12.523
17.11
15.367
19.972
21.461
15.278
28.165
23.606
26.269
29.514
26.32
35.897
45.951
(node:57740) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
```

**Comment by JoelEinbinder** [comment]
Awesome repro! Thanks!

@aslushnikov it looks like this is being caused by the addScriptToEvaluate on new document to ensure the secondary dom world exists. At first I thought we might be adding a new script every page load, but we only send the command once. However it takes longer to evaluate every run.

**Comment by aslushnikov** [comment]
Upstream fix is out for review: https://chromium-review.googlesource.com/c/chromium/src/+/1634416

**Comment by knokknok** [comment]
Awesome! Thanks!
