### ISSUE TITLE
Intercepted requests won't return with some status codes

### ISSUE THREAD

**Issue by angrykoala** [puppeteer/puppeteer#4454]
In Puppeteer 1.16.0 and 1.15.0, trying to make a fake response with the interceptor will not behave properly with some status codes (e.g. 422)

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.16.0
* Platform / OS version: Linux
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

Having the following webpage being served at `http://localhost:3000/requests.html`:

```html
<html>

<body>
    <button class="btn" onclick="doRequest()">click me</button>
    <script>
        function doRequest() {
            fetch("/api").then((res) => {
                console.log("AFTER REQUEST", res.status)
            }).catch((err)=>{
                console.log("ERR",err)
            })
        }
    </script>
</body>
</html>
```

And the following code with puppeteer:

```js
const puppeteer=require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on("console", (log)=>{
    console.log(log.text());
  });

  page.on('request', interceptedRequest => {
      console.log(interceptedRequest.url());
      if(interceptedRequest.url().endsWith('/api')){
          interceptedRequest.respond({
              status: 422,
              body: "FAKE"
          })
      } else interceptedRequest.continue();
    });
  await page.goto('http://localhost:3000/requests.html');
  await page.waitFor(".btn");
  await page.click(".btn")
  setTimeout(()=>{
      browser.close();

  },300);
})();

```

**What is the expected result?**

The following log should appear
```
http://localhost:3000/requests.html
http://localhost:3000/api
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
AFTER REQUEST 422
```

(behaves as expected with Puppeteer 1.14.0)

**What happens instead?**

The request is never completed:
```
http://localhost:3000/requests.html
http://localhost:3000/api
```

If changing the status code to 400 the request behaves as expected:

```
http://localhost:3000/requests.html
http://localhost:3000/api
Failed to load resource: the server responded with a status of 400 (Bad Request)
AFTER REQUEST 400
```

This appear to be happening with status codes from 421 to 451

The same behavior seems to be happening with non-valid status codes (e.g. 309). All this cases are working as expected on 1.14.0

**Comment by aslushnikov** [comment]
@angrykoala sorry for this regression. This happens because we don't have default status codes for non-standard HTTP status codes.

When #4554 lands, you'll be able specify both `status` and `statusText`, and things will work as expected.

```js
interceptedRequest.respond({
  status: 422,
  statusText: 'fake',
  body: "FAKE"
})
```

**Comment by angrykoala** [comment]
In which Puppeteer version is this expected to be released?

**Comment by aslushnikov** [comment]
@angrykoala 1.18 - it'll be on June, 21st
