### ISSUE TITLE
Mouse location is wrong when device descriptors use scaling.

### ISSUE THREAD

**Issue by dawnmist** [puppeteer/puppeteer#4456]
I've just spent the last 2 hours debugging why we were getting some odd issues in screenshots (particularly forms showing a list of items to select singly, and having multiple items show as highlighted).

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0 & 1.16.0 (retested on newest after identifying what the problem was)
* Platform / OS version: Debian Testing, Centos 7, Ubuntu 16.04
* Node.js version: 10.15.3

**What steps will reproduce the problem?**
* Use a device descriptor that requires scaling when taking the screenshot (both 'iPad' and 'iPhone6' show the issue).
* Use either page.click() or page.hover() to move the mouse to a particular element in the page.
* Take a screenshot.

**What is the expected result?**
The mouse location should be scaled in the same way that the page has been scaled when taking the screenshot so that the screenshot has the mouse located over the specified element.

**What happens instead?**
The mouse remains in the original unscaled (x,y) location prior to scaling, which means it is no longer located over the particular element that had been selected in the page.click() or page.hover() functions.

This means that for device descriptors that use scaling page.hover() cannot be used at all (the mouse is _never_ located over the specified element when the screenshot is actually taken), and that if the page.click() item is in a long list of items it is essential to use page.move() to move the mouse into a location outside of where the scaled list will be located (otherwise it will hover over another element in the list, likely breaking the purpose of the screenshot and causing confusion when it appears that multiple items were 'selected').

**Comment by JoelEinbinder** [comment]
If I understand correctly, you are doing this

```js
await page.hover('my element');
await page.emulate(devices['Fancy Device']);
await page.screenshot();
```
And the page.emulate call is causing the page to move under the mouse, messing up your screenshot.

Assuming I didn't get it wrong, is there any reason you cant do this?

```js
await page.emulate(devices['Fancy Device']);
await page.hover('my element');
await page.screenshot();
```

I don't think there is a right answer for what to do with the mouse after the viewport has been scaled. Your elements are probably in different positions. Some might be offscreen.

**Comment by dawnmist** [comment]
You have misunderstood. I am already setting up the device viewport at the beginning prior to moving/taking a screenshot (navigating around the site taking a sequence of screenshots - I've pulled out the specific bits of code that demonstrate where the issue occurs).

```js
import * as path from 'path';
import * as puppeteer from 'puppeteer';
import * as devices from 'puppeteer/DeviceDescriptors';

const iPhone = devices['iPhone 6'];
const iPad = devices.iPad;
const outDir = path.resolve(__dirname, 'screenshots');
const pageLoadOptions: Partial<puppeteer.NavigationOptions> = { waitUntil: ['load', 'networkidle2'] };
const DEBUG_SCREENSHOTS = process.env.DEBUG_SCREENSHOTS;

const puppeteerLaunchOptions: puppeteer.LaunchOptions = {};
if (DEBUG_SCREENSHOTS) {
  puppeteerLaunchOptions.headless = false;
}

const takeScreenshots = async (viewport: puppeteer.Viewport, subdir: string) => {
  const browser = await puppeteer.launch(puppeteerLaunchOptions);
  const page = await browser.newPage();
  try {
    page.on('console', (msg) => console.log('PAGE LOG:', msg.text()));
    await page.setViewport(viewport);

    await page.goto('https://some-site.com', pageLoadOptions);

    await page.waitForSelector('#addBid');
    await page.click('#addBid');
    await page.waitForSelector('#reqFlight');
    await page.hover('#reqFlight');
    // This screenshot does NOT show the '#reqFlight' option as hovered - the mouse is over the list
    // header instead of over the list item requested.
    await page.screenshot({
      path: path.resolve(outDir, subDir, `FlightRequest.png`),
      type: 'png',
      fullPage: false
    });

    await page.click('#reqFlight');
    await page.waitForSelector('#CPT');
    await page.click('#CPT');
    // I have to add a page.mouse.move(0,0) here, or an option starting with "A" in the list is hovered 
    // when the screenshot is taken, despite having explicitly requested that the mouse should be over
    // the '#CPT' option.
    await page.screenshot({
      path: path.resolve(outDir, subDir, `FlightDestinations.png`),
      type: 'png',
      fullPage: false
    });

  } catch (e) {
    console.log(e);
    throw e;
  }
  await page.close();
  await browser.close();
};

if (!DEBUG_SCREENSHOTS) {
  Promise.all([takeScreenshots(iPad.viewport, 'iPad'), takeScreenshots(iPhone.viewport, 'iPhone6')]).catch((err) =>
    process.exit(-1)
  );
}
else {
  takeScreenshots(iPad.viewport, 'iPad')
    .then(() => takeScreenshots(iPhone.viewport, 'iPhone6'))
    .catch((err) => {
      process.exit(-1);
    });
}
```

What I expected to see from the first screenshot is the option labelled "Flight Request" to be highlighted as the mouse hovering over it. What I actually see in the screenshot is some other element in the heading section of the page has the mouse hovering over it.

What I expected to see from the second screenshot is the option labelled "CPT" to be set to "active". What I actually see from the second screenshot is the option labelled "CPT" is set to active AND one of the other options starting with "A" highlighted as the mouse hovering over it.

The only "change" to the screen after hovering/clicking on an item are those done internally by puppeteer itself when I request the screenshot to be taken.

**Comment by JoelEinbinder** [comment]
I see, thanks for the code. It certainly sounds like a bug. Does it happen the same with headless set to true/false?

**Comment by dawnmist** [comment]
Yes. It was only after setting headless to true, and adding a 30 second delay prior to the screenshot, that I finally saw that the screen itself was being set up correctly but the screenshot would leave the mouse where it had originally been set rather than scaling it with the scaling of the screenshot view resulting in the wrong elements being hovered. It also occurs regardless of whether the screenshots for iphone/ipad are taken sequentially (as per the DEBUG_SCREENSHOTS option being specified above) or in parallel (as done when not using DEBUG_SCREENSHOTS).

**Comment by derrekyoung** [comment]
We're seeing some strange behavior in my scripts. We want to simulate mouse movement and have that be shown in the script. We're using some math to create the cursor tracking between 2 sets of X/Y coordinates.

When emulating a mobile device, the coordinates become more and more "off", especially when scrolling is involved.
