### ISSUE TITLE
Webpage is not loading with puppeteer, Navigation Timeout Exceeded

### ISSUE THREAD

**Issue by RebliNk17** [puppeteer/puppeteer#4457]
STEP 1: Are you in the right place?
Yes, I am...

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0, 1.12.*, 1.16.0, also occurs in puppeteer-firefox
* Platform / OS version: Windows 10 pro and linux on docker
* URLs (if applicable): in the code above
* Node.js version: tried both 8.11.0 and 10.15.3

**What steps will reproduce the problem?**
Run this code: 
```javascript
let url = 'http://svyaznoy.ru';
  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--ignore-certificate-errors',
    ]
  });
  const page = await browser.newPage();
  await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36');
  let res = await page.goto(url, {waitUntil: [
      'load',
      'domcontentloaded',
    ]});

  await page.screenshot({path: 'example.png'});

  await browser.close();
```

* Can occur in few more sites I have.
* There is no redirect... 

**What is the expected result?**
Page will load and not stuck in what i believe resource loading

**What happens instead?**
Timeout, even if you give it 1h...

Hope someone has a solution for that issue... 
I'm straggling with it for a while...

**Comment by aslushnikov** [comment]
Your script works just fine in **headful** mode, so it looks like the website uses one of techniques to detect headless.

This works fine as far as Puppeteer project is concerned.
