### ISSUE TITLE
Is there a way to clean HTTP cache and app data?

### ISSUE THREAD

**Issue by inikulin** [puppeteer/puppeteer#446]
Is there a convenient way to clean HTTP cache and application data like service workers, cookies, etc.? I couldn't find anything related in the docs.

**Comment by aslushnikov** [comment]
Every browser launch starts with clean HTTP cache and without any cookies. Is it enough?

```js
let browser = await puppeteer.launch(); // no cache, no cookies!
```

Note: the 0.9.0 version has a bug that might result in browser launches re-using the old cache. This should be fixed on tip-of-tree.

**Comment by inikulin** [comment]
> Every browser launch starts with clean HTTP cache and without any cookies. Is it enough?

Not really. Consider I would like to measure performance of 1000 pages with cold cache,  restarting browser for each of them wouldn't be nice.

**Comment by inikulin** [comment]
Hmm, from my experimenting it's seems like browser has cold cache on each `page.goto`. Is this intended behaviour?

**Comment by aslushnikov** [comment]
> Not really. Consider I would like to measure performance of 1000 pages with cold cache, restarting browser for each of them wouldn't be nice.

That's a good one, thanks. This might be solvable with #85.

> Hmm, from my experimenting it's seems like browser has cold cache on each page.goto. Is this intended behaviour?

@inikulin nope, definitely not. How do you check this?

**Comment by inikulin** [comment]
@aslushnikov 
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();


  page.once('load', async () => {
        console.log('load');
        page.on('response', r => console.log(r.status));
        await page.goto('https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md');
        browser.close();
  });

  await page.goto('https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md');

})();
```
This code gives me a bunch of 200/204s, but there should be at least few 304s. When I first ran this code today it worked as intended, but on second run it gives only 200s.

**Comment by aslushnikov** [comment]
@inikulin Awesome, thanks. I can reliably reproduce this, filed #487.

Would the #85 solve the cache-busting needs?

**Comment by inikulin** [comment]
@aslushnikov Regarding #85: as far as I understand I'll just need to create new pages with some unique context ID to achieve desired behaviour. Does creation of new page has any significant performance overhead comparing to `page.goto`?

**Comment by inikulin** [comment]
@aslushnikov BTW
> Every browser launch starts with clean HTTP cache and without any cookies. Is it enough?

Does this mean that if I run two instances simultaneously they will not share browser cache?

**Comment by aslushnikov** [comment]
> Does creation of new page has any significant performance overhead comparing to page.goto?

What kind of overhead are you interested in? It does take some time to open a new tab, but it should be blazingly fast most of the time.

> Does this mean that if I run two instances simultaneously they will not share browser cache?

Right, they will not share browser cache.

**Comment by inikulin** [comment]
@aslushnikov 
>  It does take some time to open a new tab, but it should be blazingly fast most of the time.

That is what I was interested in. At the first glance, #85 should work for me.

**Comment by bogdan0083** [comment]
@aslushnikov
> Every browser launch starts with clean HTTP cache and without any cookies. Is it enough?

I'm sorry for a little off-topic here, but how can i actually preserve cache and cookies on every browser relaunch? I wasn't able to found any information in docs regarding this.

Thanks!

**Comment by aslushnikov** [comment]
@bogdan0083 if you're using tip-of-tree chromium, try passing `userDataDir` to the [`puppeteer.launch()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions):

```js
const browser = await puppeteer.launch({
  userDataDir: '/tmp/my-profile-directory'
});
```

**Comment by ashubham** [comment]
@aslushnikov I tired passing `userDataDir` but still across launch(es) the cache is not used. I do see that the directory is populated with some artifacts.

I am on latest v11.0-alpha of `puppeteer`.

**Comment by aslushnikov** [comment]
@ashubham chrome headless currently doesn't save session properly; there's upstream work for this. 

Closing issue in favor of browser contexts issue.

**Comment by bluepeter** [comment]
One option may be to start headless Chrome and set cache to 0 so it's effectively never used? `--disk-cache-size=0` may do the trick...

**Comment by gvelasquez760** [comment]
I have a similar problem, when i click a button in my page it opens a new tab with a pdf, is possible to download this pdf as a file?

maybe i can write the buffer from the page in a file, but how i can get the buffer from the new tab?

Thanks

**Comment by tsufiev** [comment]
@aslushnikov regarding the issue that @ashubham [mentioned](https://github.com/GoogleChrome/puppeteer/issues/446#issuecomment-329656030), could please provide a reference for the upstream work? I'm facing the same issue.
