### ISSUE TITLE
(node:96814) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by Herodotuslee** [puppeteer/puppeteer#4463]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: 10.14
* URLs (if applicable): www.example.com
* Node.js version: v.10.1.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();

```

**What is the expected result?**

run the "goto" and get the screenshot

**What happens instead?**

When I run the node examplex 2nd time, I got this error

(node:96814) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

**Comment by aslushnikov** [comment]
@Herodotuslee Your script works perfectly for me - issue is somewhere in the host environment. What's your platform? How do I experience this locally?

**Comment by natiOTW** [comment]
`await page.goto('https://example.com', {waitUntil: 'domcontentloaded'});`
