### ISSUE TITLE
Q: What is the recommend way to access a content script's execution context?

### ISSUE THREAD

**Issue by pyrho** [puppeteer/puppeteer#4465]
Hey !

I stumbled upon [this PR](https://github.com/GoogleChrome/puppeteer/pull/2812/files) which enables accessing the execution context of content scripts (injected by extensions). It's great, I cherry pick that commit into my fork of master and I'm now able to call `myContentScriptExecutionContext.evaluate` and access globally exposed
functions from there.
But you decided to revert that ([via this PR](https://github.com/GoogleChrome/puppeteer/pull/3058)).

So my question is, is there an official way of doing this as of now?

Thanks again for your hard work on puppeteer.

**Comment by pyrho** [comment]
If anyone else is wondering how to do this, you can look at [this forked branch](https://github.com/pyrho/puppeteer/tree/feat/expose-execution-context). I've been using this for my project (direct reference to that branch in my package.json) and it works fine for my needs.

The following snippet allows accessing data from the content script's execution context: 

```javascript

        let contentScriptExecutionHandler = (() => Array.from(page.executionContexts().values()).find(ec => ec.name() === 'MY_EXTENSION_NAME'))();
        const dataFromContentScript = await contentScriptExecutionHandler.evaluate(() => window.my_content_script_variable); // set in the content script

```

**Comment by aslushnikov** [comment]
> I stumbled upon this PR which enables accessing the execution context of content scripts (injected by extensions). It's great, I cherry pick that commit into my fork of master and I'm now able to call myContentScriptExecutionContext.evaluate and access globally exposed
functions from there.

@pyrho nice archeology! :-) 

> So my question is, is there an official way of doing this as of now?

Not yet. Extension content scripts will be exposed by #1215, and we track the general DOMWorld management with #2671.

#1215 has good chances to land soon'ish.
