### ISSUE TITLE
[Feature Request] Option to block ip addresses or urls

### ISSUE THREAD

**Issue by yadue** [puppeteer/puppeteer#4469]
**Tell us about your environment:**

* Puppeteer version: 1.7.0 
* Platform / OS version: AWS Linux
* URLs (if applicable):
* Node.js version: v8.11.4

**What steps will reproduce the problem?**

We created a service hosted on aws to make website screenshots and AWS has special address which should be only accessible by aws servers (for communication). When accessed from outside ip it didnt show anything, but when running puppeteer on that server it has access to that url and is able to get secret data from it. 

Currently there is no way we could block ip or addresses in puppeteer just to avoid security issues like this. 

**What is the expected result?**
To provide additional configuration param which takes addresses or urls to block. Chrome/chromium won't be able to access them.

**Comment by Yokutto** [comment]
Hi @yadue,
There's already an option to do that with [request interception](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-pagesetrequestinterceptionvalue).

You can take this code as example
```javascript
const puppeteer = require('puppeteer')


const domains_in_blacklist = [
  "google.com", //Block google.com, www.google.com is allowed
  "satellite.mokyun.net", //Block mokyun.net from loading assets from satellite subdomain
  "portquiz.net:8080", //Block portquiz.net from using 8080 port
  "www.github.com" //Block only www.github.com, github.com or gist.github.com is allowed
]

const requests_blocked = []

puppeteer.launch().then(async browser => {
  const page = await browser.newPage()

  await page.setRequestInterception(true)

  page.on('request', interceptedRequest => {
    if (domains_in_blacklist.includes(new URL(interceptedRequest.url()).host)) {
      requests_blocked.push(interceptedRequest.url())
      interceptedRequest.abort()
    } else {
      interceptedRequest.continue()
    }
  })

  await page.goto('http://mokyun.net')

  console.log(`Blocked ${requests_blocked.length} requests. Requests blocked: ${JSON.stringify(requests_blocked)}`)
  await browser.close()
})
```

I get a bit confused when you say "block IP Addresses". If you are wanting to block server IP (IPv4/IPv6 of the website that trying to load something) I think it's not possible yet, but it is a interesting idea. If you want to block x website from loading asses from direct IP address, you can use the same logic as well, for this one I recommend using regex to match IPv6, IPv4, domains, etc...

**Comment by yadue** [comment]
@Yokutto It doesn't work unfortunately if the request there is a redirection in between.

In example when you want to block IP address but the request points to the domain.

**Comment by aslushnikov** [comment]
@yadue This will be possible with response interception - #1191. You'll be able to intercept responses before they hit the renderer, inspect their [`response.remoteAddress()`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-responseremoteaddress) and fail them if the IP is in the black list. 

Today, you can probably use one of the chromium policies to block certain URLs: https://www.chromium.org/administrators/url-blacklist-filter-format

Hope this helps. Closing this feature request as a dupe of #1191.

**Comment by gumuruhsspj** [comment]
> ```js
>  if (domains_in_blacklist.includes(new URL(interceptedRequest.url()).host)) {
> ```

great i think this interception request filtering technique is match for general purposes
