### ISSUE TITLE
Page evaluate security

### ISSUE THREAD

**Issue by steida** [puppeteer/puppeteer#4472]
Can scrapped page read page evaluate function via toString somehow? 

Thank you.

**Comment by aslushnikov** [comment]
> Can scrapped page read page evaluate function via toString somehow?

@steida i don't think there's a way to read the evaluation function per se - at least none I'm aware of.

But I wouldn't rely on this for anything serious. There's an attack surface that might allow automated page to mess with its automation, e.g. page can override certain native constructors and do nasty things.

A much better boundary will be provided with #2671.

Hope this helps!
