### ISSUE TITLE
net::ERR_CONNECTION_RESET error

### ISSUE THREAD

**Issue by se8820726** [puppeteer/puppeteer#4476]
I want to load below url and process its content
_https://www.sanarate.ir/Default.aspx_

my code:
```
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://www.sanarate.ir/Default.aspx', { waitUntil: 'networkidle0' });

    const data = await page.evaluate(
      () =>  Array.from(document.querySelectorAll('#MainContent_ViewCashChequeRates_divTimely')).map(elem => elem.tagName)
    );

    console.log(data);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

but shows me this error:
```
Error: net::ERR_CONNECTION_RESET at https://www.sanarate.ir/Default.aspx  
at navigate (\node\node_modules\puppeteer\lib\FrameManager.js:121:37) 
at process._tickCallback (internal/process/next_tick.js:68:7) 
-- ASYNC --  
at Frame. (\node\node_modules\puppeteer\lib\helper.js:110:27) 
at Page.goto (\node\node_modules\puppeteer\lib\Page.js:629:49) 
at Page. (\node\node_modules\puppeteer\lib\helper.js:111:23)
at main (\node\b.js:8:16)
at process._tickCallback (internal/process/next_tick.js:68:7)
--
```

can you give me any solution ?

**Comment by aslushnikov** [comment]
@se8820726 the website uses some techniques to detect headless chrome and evade automation.

**Comment by ElibarikiJ** [comment]
> @se8820726 the website uses some techniques to detect headless chrome and evade automation.

what is solution to by pass server that blocing headless browser?

**Comment by SwimSwag10** [comment]
> > @se8820726 the website uses some techniques to detect headless chrome and evade automation.
> 
> what is solution to by pass server that blocing headless browser?

I'm trying to figure out the same thing. I believe it would be to either create your own server to sort-of mask yourself as a real person not an automation, or create a new proxy every time you connect to the endpoint.
