### ISSUE TITLE
`node install.js` fails inside enterprise proxy

### ISSUE THREAD

**Issue by phawxby** [puppeteer/puppeteer#448]
```
> puppeteer@0.9.0 install C:\Users\Z269CJBB\Documents\GitHub\xerox-framework\node_modules\puppeteer
> node install.js

Download failed: connect ETIMEDOUT 216.58.213.112:443
```

Looking at the docs it appears that `https` does not natively make use of proxy environmental variables, as a result it fails during the install phase. This appears to be the culprit.
https://github.com/GoogleChrome/puppeteer/blob/master/utils/ChromiumDownloader.js#L187

**Comment by jsnanigans** [comment]
are you sure you have node 7.10 or higher ?

**Comment by phawxby** [comment]
Node 8

**Comment by Garbee** [comment]
Pr #455 aims to address this
