### ISSUE TITLE
Running multiple instances of puppeteer at once with different session for each

### ISSUE THREAD

**Issue by m1m6** [puppeteer/puppeteer#4481]
Hello Guys, i'm new to puppeteer, i'm struggling in running multiple instances at once,
here's an example of what i'm doing
```
initialize: async () => {
    site.browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"]
    });

    site.page = await site.browser.newPage({context: `${Math.random()}`});
},
```

it will run multiple instances, but only one of them will be working at a time, can any one help in this?

**Comment by aslushnikov** [comment]
Hi @m1m6,

> it will run multiple instances, but only one of them will be working at a time, can any one help in this?

You can actually run many of these instances in parallel. Like this:

```js
await Promise.all([
  initialize(),
  initialize(),
]);
```

Hope this helps!

**Comment by FelipeDeveloperFullStack** [comment]
> Hi @m1m6,
> 
> > it will run multiple instances, but only one of them will be working at a time, can any one help in this?
> 
> You can actually run many of these instances in parallel. Like this:
> 
> ```js
> await Promise.all([
>   initialize(),
>   initialize(),
> ]);
> ```
> 
> Hope this helps!

Thanks man!
