### ISSUE TITLE
page.on('load') not firing

### ISSUE THREAD

**Issue by Yokutto** [puppeteer/puppeteer#4484]
### Steps to reproduce

**Environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Ubuntu 16.04
* Node.js version: v11.15.0

**Description:**
I'm facing a problem with `page.on('load')` which never fire/activate when the page load for the first time.

To reproduce this, just run this few lines below
```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');

  async function c(e) {
    console.log('loaded :)')
    return e
  }

  page.on('load', await c)

  console.log('a')

  await browser.close();
})();
```

Also, I discovered when you have this code
```javascript
await page.goto('https://example.com', {waitUntil:'domcontentloaded'});
```
the event `page.on('domcontentloaded')` will never fire, because dom already loaded

However, if the page navigate to another page without "waitForNavigation" or "goto", the events works properly

**Expected results:**
I'm expecting that `page.on('load')` will fire when the page loads for the first time and console the message "loaded :)"

**Feature request (if applicable):**
Is possible to create a function to check if the page is "stable" (not having requests)?
For example:
`await page.check_for('networkidle2') // Result: Idle or Busy with n requests`
or check if dom loaded
`await page.check_for('domcontentloaded') // Boolean: true or false`
This function will tell if the page is busy with requests, I think it will really useful for those "SPA" websites that requests various requests when the user interact with the page

**Comment by molant** [comment]
Have you tried subscribing to the events before navigating?

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  async function c(e) {
    console.log('loaded :)')
    return e
  }

  page.on('load', await c)

  console.log('a')

  await page.goto('https://example.com');
})();
``` 

Notice I've removed `await browser.close();`. You might want to do this when you receive the `loaded` event.

**Comment by Yokutto** [comment]
Subscribing to event before it `page.goto` solves, I forgot that, thx
 
Ops, I just forgot to add it because I was closing with Ctrl + C command.
