### ISSUE TITLE
Cannot `yarn "install` inside container because of protocal-types-generator 

### ISSUE THREAD

**Issue by pyrho** [puppeteer/puppeteer#4485]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: master (084cf021195dbe125d26496796f590a4300fb844)
* Platform / OS version: Docker container running `node:8`
* Node.js version: 8.16

**What steps will reproduce the problem?**

1. `git clone https://github.com/GoogleChrome/puppeteer.git`
2. `yarn` (`npm` fails the same way)

**What is the expected result?**
Puppeteer is installed.

**What happens instead?**
Installation fails when running the install script `node install.js` because the protocol-types-generation tries to launch chrome without the `--no-sandbox` argument.

Here is the output:
```
root@494abee07b90:/app# yarn
yarn install v1.15.2
info No lockfile found.
[1/4] Resolving packages...
warning parcel > htmlnano > uncss > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⢀ waiting...
[4/4] ⢀ parcel
[3/4] ⢀ puppeteer
error /app/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /app/node_modules/puppeteer
Output:
Chromium downloaded to /app/node_modules/puppeteer/.local-chromium/linux-641577
ERROR: Failed to download Chromium r641577! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Failed to launch chrome!
[0528/160658.820235:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
```

The "Fail to launch Chrome" error is misleading as the `.catch` handler ([here](https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L67) also catches error from function invocation in the `onSuccess` handler.
The error is actually thrown by `onSuccess > generateProtocolTypesIfNecessary > utils/protocol-types-generator/index.js`; because it launches chrome without the `--no-sandbox` argument and this fails within a container because of root shenanigans.

note: I've also tried using the [recommended Dockerfile](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker), but it yields the same results.

**Comment by aslushnikov** [comment]
@pyrho The `--no-sandbox` seems to be quite safe in this particular usecase, but I wonder why isn't it working for you in the first place? The docker image we have is actually used on our CI - and seems to be working fine for us

**Comment by JoelEinbinder** [comment]
Also if the docker container is generating protocol types, than the docker container is broken. It shouldn't install dev dependencies or have our utils folder.

**Comment by aslushnikov** [comment]
> Also if the docker container is generating protocol types, than the docker container is broken. It shouldn't install dev dependencies or have our utils folder.

@JoelEinbinder I think @pyrho uses docker container for development.

**Comment by aslushnikov** [comment]
@pyrho we actually test in [this docker container](https://github.com/GoogleChrome/puppeteer/blob/master/.ci/node8/Dockerfile.linux) and everything works there.

So if you want to develop puppeteer in a docker, I'd recommend using ours - it does work.

Hope this helps!

**Comment by pyrho** [comment]
My Dockerfile looks like this for reference:

```
FROM node:8

# Install dependencies
RUN apt-get update &&\
apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget \
xvfb x11vnc x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps vim

# Cd into /app
WORKDIR /app

# Copy package.json into app folder
COPY package.json /app

# Install dependencies
RUN yarn install
COPY . /app

# Start server on port 3000∂
EXPOSE 3000:3001
ENV PORT=3001

# Creating Display
ENV DISPLAY :99

# Start script on Xvfb
CMD Xvfb :99 -screen 0 1920x1024x16 & npm run all
```

And `npm run all` is `mocha ./specs/**test.js`.

My use case is the following, I want to test my extension's content script, including how it communicates with the background page.
The Dockerfile above is used by our CI to run tests and validate our content script. Developers can also run this locally to help debugging issues reported by CI.

The CI plan just does `docker build -t tests . && docker run --rm tests` (which will call `npm run all` within the container).

I believe my use case is valid.

Have a nice day!

**Comment by aslushnikov** [comment]
@pyrho based on [this your comment](https://github.com/GoogleChrome/puppeteer/pull/4486#discussion_r290395604) and your description here, do I understand it correctly that you install Puppeteer from github rather than from npm?

**Comment by pyrho** [comment]
> @pyrho based on this your comment and your description here, do I understand it correctly that you install Puppeteer from github rather than from npm?

~~No puppeteer is installed via yarn (I guess yarn/npm doesn't make a difference here but I may be wrong).
You can see that it's installed via the npm registry in the Dockerfile I pasted above.~~
Wrong.

I think I understand what the issue is now, I've been using my ["fork"](https://github.com/pyrho/puppeteer/commit/27bc6663e5b72b1acb0c30c8856fdb39a56e433b) (while #1215 is pending) referenced in my package.json like so: `"puppeteer": "https://github.com/pyrho/puppeteer#27bc6663e5b72b1acb0c30c8856fdb39a56e433b"`, so that's why it's trying to generate the protocol types I guess, because I'm not pulling the prebuilt package from the NPM registry.

Sorry for the noise, and thank you for your patience and your hard work on puppeteer!
