### ISSUE TITLE
I use puppeteer to get chrome transferred protocol, The correct result is QUIC，but i get TLS 1.2

### ISSUE THREAD

**Issue by caserffer** [puppeteer/puppeteer#4488]
this is my code :
let response = await page.goto('https://caddy.olplan.com/movie/10.mp4');
    // console.log(cookies);
    console.log(response.securityDetails().protocol());
the result is :TLS 1.2

expect result is: QUIC

Is there something wrong？

**Comment by aslushnikov** [comment]
@caserffer the link doesn't open for me - server responds with 503. 

Do you have another link for me to look into this?
