### ISSUE TITLE
DeprecationWarning for OutgoingMessage.prototype._headers is deprecated on page.goto

### ISSUE THREAD

**Issue by rg-wood** [puppeteer/puppeteer#4489]
Getting DeprecationWarning for OutgoingMessage.prototype._headers when I call `page.goto`:

```js
await page.goto('http://localhost:8080', { waitUntil: 'networkidle0' })
```

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: macOS 10.14.5
* Node.js version: 12.3.1

**What steps will reproduce the problem?**

The following code reproduces this error:

```js
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  })
  
  const page = await browser.newPage()
  await page.goto('http://localhost:8080', { waitUntil: 'networkidle0' })
```

**What is the expected result?**

No deprecation warning.

**What happens instead?**

Get a deprecation warning

**Comment by aslushnikov** [comment]
@rg-wood How do I reproduce this? Runs perfectly smooth for me.

Additionally: the DEP0066 is about accessing the `outgoingMessage._headers` private variable from node's HTTP module. We never do this in Puppeteer.

**Comment by rgladwell** [comment]
Apologies, looks like this was an issue with another piece of software:

https://github.com/indexzero/http-server/issues/537

Please close
