### ISSUE TITLE
how to build and run docker puppeteer and mocha

### ISSUE THREAD

**Issue by JPilarr** [puppeteer/puppeteer#4490]
I i have problem with build and run puppeteer in mocha like docker

i tried decsriprion in in troubleshooting  section with name - Running Puppeteer in Docker but it doesnt work. can You help me somebody?

https://stackoverflow.com/questions/tagged/puppeteer

`sudo docker run -i --init --rm --cap-add=SYS_ADMIN --name puppeteer-chrome puppeteer-chrome-linux node -e "`mocha /home/honza/projects/trendaro-qset/test/ --timeout 50000`"`

```
[eval]:3
  visual tests
         ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at evalScript (internal/bootstrap/node.js:589:27)
    at startup (internal/bootstrap/node.js:265:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```

```
#Dockerfile
FROM node:10-slim

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# If running Docker >= 1.13.0 use docker run's --init arg to reap zombie processes, otherwise
# uncomment the following lines to have `dumb-init` as PID 1
# ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
# RUN chmod +x /usr/local/bin/dumb-init
# ENTRYPOINT ["dumb-init", "--"]

# Uncomment to skip the chromium download when installing puppeteer. If you do,
# you'll need to launch puppeteer with:
#     browser.launch({executablePath: 'google-chrome-unstable'})
# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
RUN npm install -g mocha

WORKDIR /data
# Install puppeteer so it's available in the container.
RUN npm i puppeteer fs chai polyserve path \
    # Add user so we don't need --no-sandbox.
    # same layer as npm install to keep re-chowned files from using up several hundred MBs more space
    && groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /node_modules

# Run everything after as non-privileged user.
USER pptruser

CMD ["google-chrome-unstable"]
`
```

**Comment by aslushnikov** [comment]
@JPilarr so what exactly are you trying to achieve? Do you want to run both Puppeteer and mocha tests in a docker container?

The `mocha` test runner you try to run doesn't exist in the docker unless you actually mount it in there.

**Comment by JPilarr** [comment]
Yes , i tied run Puppeteer and mocha tests in a docker container. i used 
sudo docker run -i --init --rm --cap-add=SYS_ADMIN  --name puppeteer-chrome puppeteer-chrome-linux node -e "`mocha test/ --timeout 50000`"
it is working but it evaluate all in stdout .

[eval]:4
    ✓ widget-buttons.json (13184ms)
    ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at evalScript (internal/process/execution.js:60:25)
    at internal/main/eval_string.js:16:1

**Comment by aslushnikov** [comment]
@JPilarr ah, ok - this definitely falls outside of the scope of the project and is reaching the limits of our knowledge.

I don't think we can be helpful here. I'd recommend asking this question on Stackoverflow.
