### ISSUE TITLE
puppeteer get 400 Error

### ISSUE THREAD

**Issue by xctest** [puppeteer/puppeteer#4496]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.14.0
* Platform / OS version:Win10-64bit
* URLs (if applicable):https://www.creditchina.gov.cn/xinyongfuwu/?navPage=5
* Node.js version:v10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

    let launchArgs = []
    launchArgs.push('--no-sandbox')
    launchArgs.push('--disable-setuid-sandbox')
    launchArgs.push('--disable-accelerated-2d-canvas')
    launchArgs.push('--disable-gpu')
    //
    let my_browser = await puppeteer.launch({
        headless: false,
        devtools: true,
        args: launchArgs
    })
    let my_page = await my_browser.newPage()
    //
    let url = 'https://www.creditchina.gov.cn/xinyongfuwu/?navPage=5'
    // Want to open the page
    await my_page.goto(url, {
            timeout: 0,
            waitUntil: 'networkidle2'
        }).then((response) => {
            const status = response.status()
            if ((status >= 300) && (status <= 399)) {
                console.log('Redirect from', response.url() + ' to ' + response.headers()['location'])
            }
            if (status === 400) {
                console.log('Bad Request,Headers:\r\n', response.headers)
            }
            if (status === 504) {
                console.log('GateWay Time Out')
            }
            if (status === 200) {
                console.log('Page Opened......')
            }
        }).catch((e) => {
            console.log('Open Err:', e)
        })
       await my_page.close()
       await my_browser.close()

**What is the expected result?**
I want to use puppeteer to open the page  which url is 'https://www.creditchina.gov.cn/xinyongfuwu/?navPage=5'

**What happens instead?**
the response gives me a 400 error , but when I use Chrome to open the url, everyting is fine.
so is something wrong with the Server or my code has bugs ?

**Comment by aslushnikov** [comment]
@xctest your code doesn't have any bugs. Instead, the website uses some technique to avoid automation.

**Comment by zhangbeiwjl** [comment]
前辈，您好，我碰到了和你一样的问题，您解决了吗？

**Comment by zenonux** [comment]
> 前辈，您好，我碰到了和你一样的问题，您解决了吗？

可以参考我的解决过程[puppeteer爬虫400，412错误](https://www.urcloud.co/archives/172/)

**Comment by maliang-git** [comment]
@zenonux 您好！我现在遇到了这个问题 想请教一下您，可以留个联系方式 或加我vx吗： 362842809

**Comment by zenonux** [comment]
> @zenonux 您好！我现在遇到了这个问题 想请教一下您，可以留个联系方式 或加我vx吗： 362842809

已更新，很久没碰了。

**Comment by maliang-git** [comment]
@zenonux 感谢大佬！ 成功了，哈哈！ 搞了两天时间都没解决，用你这个伪装代码居然真的成功了！这些伪装代码我之前也看到过也试过，但都没成功。这次全部采用你这个来试一下居然成功了，最后定位原因是因为我之前设置的userAgent版本过高了，肯定是目标网站那边做了限制。 非常感谢！哈哈
