### ISSUE TITLE
Full page screenshot issue in headful mode

### ISSUE THREAD

**Issue by h2grover** [puppeteer/puppeteer#4500]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.17.0
* Platform / OS version: Ubuntu 18.04.1 LTS and OSx 10.14
* URLs:
  - https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md
  - https://pastebin.com/XcHLqyNC
* Node.js version: 8.15

**What steps will reproduce the problem?**

Run this code
```
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.setViewport({
    width: 1920,
    height: 1080
  });

  await page.goto(
    "https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md",
    {
      waitUntil: "networkidle0",
      timeout: 0
    }
  );

  await page.screenshot({
    path: "check-this-screenshot.png",
    fullPage: true
  });

  await browser.close();
})();

```
**What is the expected result?**
One should get a full page screenshot in both the scenario:
1. `headless: true`
1. `headless: false`

**What happens instead?**
1. `headless: true`: getting the correct full page screenshot
1. `headless: false`: getting the blank screenshot/No screenshot

**Comment by aslushnikov** [comment]
Looks like we're hitting GPU limit on headful easily. Chrome DevTools limit max content height to 2^14 - we should probably do this as well.

**Comment by h2grover** [comment]
@aslushnikov any update on this?

**Comment by BrianHung** [comment]
Is the limit for Chrome DevTools `1 << 14` or `2 << 14`? I'm looking at the code for DevTools, and there's `1 << 14` hard-coded in for the content height; there's also this [post](https://github.com/GoogleChrome/puppeteer/issues/933).

**Comment by cris691** [comment]
@BrianHung 2^14 == 1<<14 (because 2^1 == 1<<1).

I've noticed what I think is this issue as well. Sometimes screenshots and other things seem to fail in headful. I don't know enough about this difference to fully bisect these issues right now, tho.

**Comment by BrianHung** [comment]
@cris691 Here's the direct line: https://github.com/ChromeDevTools/devtools-frontend/blob/f5d825ac1bb6eca13782947e30e5c5c78b9de1f0/front_end/emulation/DeviceModeModel.js#L728
