### ISSUE TITLE
File download failed

### ISSUE THREAD

**Issue by sErgiumocAn666** [puppeteer/puppeteer#4501]
**Env:**
* Puppeteer version: 1.11.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 10.15.3
___
**Issue:**
When I set "userDataDir" parameter and try to download a file by clicking on a link the file download fails. So without setting this parameter the file download succeeds.
___
**Code:**

`appSettings.userDataDir = "path to the user data directory";`

`browser = await puppeteer.launch({
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage"
    ],
    userDataDir: appSettings.userDataDir,
    headless: false,
    ignoreHTTPSErrors: true,
    slowMo: 100
  });`
___
**Expected result?**
The file download should succeed.

**What happens instead?**
The files download fails.

**Comment by aslushnikov** [comment]
@sErgiumocAn666 hmm, works for me. What's you `userDataDir` value?

**Comment by sErgiumocAn666** [comment]
> @sErgiumocAn666 hmm, works for me. What's you `userDataDir` value?

It's "C:/........../_userData" in which are all the files/directories copied from the real User Data.

**Comment by sErgiumocAn666** [comment]
@aslushnikov could you please give me a scheme about how this --userDataDir param should be used, please?! :)

**Comment by sErgiumocAn666** [comment]
Oh sh...t!
It was my fault. The problem was that I changed the download path within Preferences so that it uses "/" as directory delimiter instead of "\\".
So the second option is the right way to do it. :/
