### ISSUE TITLE
page.goto() does not throw an error on 404

### ISSUE THREAD

**Issue by michaeloryl** [puppeteer/puppeteer#4502]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: MacOS 10.14.5
* URLs (if applicable):
* Node.js version: 10.15.1

**What steps will reproduce the problem?**

Have `page.goto()` call any URL that returns a 404.  It will not throw an error.

_Please include code that reproduces the issue._
```
const puppeteer = require('puppeteer')

let main = async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  let result

  try { 
    result = await page.goto('http://www.example.com/ThisPageReturns404')
    console.info('No error thrown')

    if (result.status() === 404) {
      console.error('404 status code found in result')
    }
  } catch (err) { 
    console.error('Error thrown')
  }
}

main()
```

**What is the expected result?**

An error should be thrown.

**What happens instead?**

No error is thrown, the code just continues as if the page loaded correctly.  You can find the status code of the request if you save the result, though.  A call to `result.status()` will indicate 404 above.

**Comment by TimotheeJeannin** [comment]
Why would you want puppeteer to throw an error? If you go to a page that responds 404 in your browser, you can still see the 404 page and interact with it. There might be links on the page and a user could click on on some "back to homepage" button for example. Puppeteer is used to write integration tests quite often. What if some integration tests are checking that an unknown URL displays a 404 page where the user can interact? I don't think puppeteer should have a "special behavior" other than what Chrome does already.

**Comment by aslushnikov** [comment]
@michaeloryl 404 pages are real pages - just with a different HTTP status code. `page.goto` should successfully navigate onto them - so that you can test custom beautiful 404's [like this](https://github.com/notexistingpage).

**Comment by michaeloryl** [comment]
Thanks for the clarification.
