### ISSUE TITLE
unable to install browser extension 

### ISSUE THREAD

**Issue by gupta77** [puppeteer/puppeteer#4503]
I am  currently looking for a tool to automate one of the product (browser extension )
 I need to Install chrome extension through one of the URL  which have download button to Download extension and when user click on it chrome web store open  then through normal process install chrome extension 

###  Main problem I am facing are mentioned below 
1. I am not able to read page "chrome://extensions/" page to assert extension installed 
2. Not able to read or click on elements appear in chrome webstore 
3. suppose I am able to install chrome extension. I am not able to click on Browser action button 
4. how can read or log all network(web service) events in chrome/chrome webstore window

**Comment by aslushnikov** [comment]
@gupta77 The main thing when it comes to extensions is to use non-headless mode:

```js
const browser = await puppeteer.launch({headless: false});
```

Also, check out our docs on [working with extensions](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions).


With this, let me answer your questions:

> I am not able to read page "chrome://extensions/" page to assert extension instaled

In non-headless mode you can just navigate to `chrome://extensions` safely.

> Not able to read or click on elements appear in chrome webstore

These would work, but you won't be able to click installation dialogs. 

> I am not able to click on Browser action button

This is covered by #2486 

> how can read or log all network(web service) events in chrome/chrome webstore window

Once you navigate to chrome webstore, you can just use regular pptr APIs such as [`'request'`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-event-request) and [`'response'`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-requestresponse) events.

Hope this helps!
