### ISSUE TITLE
preferCSSPageSize not working

### ISSUE THREAD

**Issue by mixman68** [puppeteer/puppeteer#4505]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Debian Stretch
* URLs (if applicable): N/A
* Node.js version: 8.16

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
I try to generate a PDF with a page with a @page css element,
```
@page {
     size: a3 !default;
}
```
otpions transferred to puppeteer are : 
```
{ path: 'output.pdf',
  margin: { top: '1cm', bottom: '1cm', left: '1cm', right: '1cm' },
  format: 'A4',
  landscape: true,
  preferCSSPageSize: false,
  printBackground: true }
```

**What is the expected result?**
I except to get a A4 landscape PDF

**What happens instead?**
I get an A4 portrait PDF.

if i modify the webpage CSS to
```
@page {
  size: auto;
}
```
i have the correct behaviour, so the preferCSSPageSize option is ignored and @page css is forced

**Comment by L3au** [comment]
the same issue, seems `@page` CSS is with the highest priority. for now, I just remove `@pages` CSS and only use the puppeteer options to control print style.
