### ISSUE TITLE
Override command line based on chrome://version/

### ISSUE THREAD

**Issue by hynospt** [puppeteer/puppeteer#4509]
Hello, i am trying to dupplicate the google chrome config in puppeteer based on my chrome version.

I am using the reference of #872
is disableDefaultArgs might not work ?

* Puppeteer version: 1.7.0
* Platform / OS version: Ubuntu 18.04.2 LTS
* URLs (if applicable): chrome://version/
* Node.js version: v8.10.0

My Script :

`(async () => {
	
	const puppeteer = require('puppeteer');
	const browser = await puppeteer.launch({
		userDataDir: '/home/${USER}/.config/google-chrome/Default',
		disableDefaultArgs: true,
		headless : false,
		executablePath : "/usr/bin/google-chrome-stable",
		args : [
			'--flag-switches-begin',
			'--flag-switches-end'
		]
	});
})();`

Here is the comparation of chrome version on browser [chrome://version/](url)
Original Google Chrome Browser : chrome://version/

`/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end`

Puppeteer Google Chrome Browser : chrome://version/

`Command Line	/usr/bin/google-chrome-stable --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_profile-GXN5QE --flag-switches-begin --flag-switches-end about:blank`

Thank you so much.

**Comment by aslushnikov** [comment]
@hynospt there's no `disableDefaultArgs` - instead, there's [`ignoreDefaultArgs`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-puppeteerlaunchoptions). This should help.
