### ISSUE TITLE
execute puppeteer script on new pages within using javascript

### ISSUE THREAD

**Issue by hynospt** [puppeteer/puppeteer#4510]
Hello everybody , i have a problem that i need to solve.

I want to make a page is undetectable using javascript window.open function.
The problem is when i define the page that using window.open , is undefined.

Is anyone has a better solution for this ?
I dont know why using page.newTab() is detected by website. It was complicated.

* Puppeteer version: 1.7.0
* Platform / OS version: Linux / ubuntu
* Node.js version: v8.10

I want to make a puppeteer work on pages[1] with javascript.
So here is the code:

```
const pages = await browser.pages();
const page = pages[0];
await page.evaluate(() => window.open('https://www.example.com', '_blank'))
const page2 = pages[1];
console.log('Pages_1 : ' + pages[0]);
console.log('Pages_2 : ' + pages[1]);
```

Result : 
```
Pages_1 : Page {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _closed: false,
  _client: 
   CDPSession {
     domain: null,
     _events: 
      { 'Network.requestWillBeSent ...
Pages_2 :  undefined
```

Thank you so much

**Comment by vsemozhetbyt** [comment]
Maybe `browser.pages()` result is not updated after the `window.open()` is processed. Try this order:

1. Subscribe to [`'targetcreated'`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-targetcreated) event (you can use [`events.once()`](https://nodejs.org/api/events.html#events_events_once_emitter_name) to get Promise if you can upgrade to Node.js 10 or 12).
2. Call `await page.evaluate(() => window.open('https://www.example.com', '_blank'))`.
3. After the event is fired, re-get new pages array or use Target argument of the event (see [`target.page()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#targetpage)).
