### ISSUE TITLE
Firefox Launch timeout puppeteer-firefox

### ISSUE THREAD

**Issue by hynospt** [puppeteer/puppeteer#4511]
### Steps to reproduce
test.js
```
const puppeteer = require('puppeteer-firefox');
const browser = await puppeteer.launch({
	headless : false,
	executablePath : "/usr/bin/firefox",
});
```

**Tell us about your environment:**

* Puppeteer-firefox version : 0.4.2
* Puppeteer version: 1.7.0
* Firefox Version : 66.0.2 (64-bit)
* Platform / OS version: Ubuntu 18.04.2 LTS
* Node.js version: v10.16.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```node test.js```

**What is the expected result?**
```Firefox launched without error```

**What happens instead?**

**Firefox was Opened but after 30 seconds , it timeout.**

```
(node:4527) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to Firefox!
    at Timeout.onTimeout (/home/workspace/node_modules/puppeteer-firefox/lib/firefox/Launcher.js:183:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:4527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4527) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@hynospt you're trying to run a non-bundled version of firefox. Today, `puppeteer-firefox` uses a [custom firefox version](https://github.com/puppeteer/juggler) that has a necessary remote debugging protocol.

Once the protocol lands upstream, you'll be able to run your preinstalled firefox. At this point of time, `puppeteer-firefox` will graduate from experimental state. 

Hope this helps and sorry for the confusion!

**Comment by xiejy** [comment]
hi, @aslushnikov， do you know the schedule for the upstream? Or could you give us some advise, we want to run puppeteer-firefox on firefox 68.0(or later), however, currently puppeteer-firefox only support the bundled version(65.0) firefox nightly? How can we do if we want to build the firefox(68.0 or later) with juggler? Thank you very much.
