### ISSUE TITLE
Navigation Timeout Exceeded when trying to load a http resource that is probably blocked by provider

### ISSUE THREAD

**Issue by OBrown92** [puppeteer/puppeteer#4517]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.16.0
* Platform / OS version: macOS 10.14.5
* URLs (if applicable): 
* Node.js version: 11.9.0

**What steps will reproduce the problem?**
```node
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('http://www.alitalia.com/etc/designs/alitalia/clientlibs-1/images/logo.png');
const pdf = await page.pdf({
    format: 'A4',
    margin: {
        top: '1cm',
        bottom: '1cm',
        left: '1cm',
        right: '1cm'
    }
});
await browser.close();
```
**What is the expected result?**
A Pdf from the logo or a clearer error message.

**What happens instead?**
```batch
{ TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/Users/leon/Documents/Lambus/mail-test/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
  -- ASYNC --
    at Frame.<anonymous> (/Users/leon/Documents/Lambus/mail-test/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/Users/leon/Documents/Lambus/mail-test/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/Users/leon/Documents/Lambus/mail-test/node_modules/puppeteer/lib/helper.js:111:23)
    at Promise (/Users/leon/Documents/Lambus/mail-test/test/test.js:21:24)
    at processTicksAndRejections (internal/process/next_tick.js:81:5) name: 'TimeoutError' }
```

**Additional informations**
I discovered this error because I tried to load a resource from alitalia, for example the logo. If this resource is included via http, puppeteer runs into a timeout. If I include the resource via https, there is no timeout, but the logo is not printed.
Also this issue seems only happening in headless mode.

**Comment by OBrown92** [comment]
I have found a solution for this case, if the User Agent is changed, the page allows a request to be made. But it would still be good if puppeteer would display another error message and the http(s) thing is also still strang.

**Comment by aslushnikov** [comment]
> But it would still be good if puppeteer would display another error message

@OBrown92 it looks like the website is using some technique to avoid automation (and thus the User 
Agent trick helped you). In Puppeteer, we don't try to interpret errors - we just display things as-is, so I don't think we can do any better than this.

> the http(s) thing is also still strang.

Does this also happen in headful (non-headless) chrome?

**Comment by deepak-mali** [comment]
Do we have any solution for this? I am also facing this issue and my scripts are failing. 
@OBrown92 I have a static User-Agent defined in my scripts but still this does not work also URLs that I'm trying to goto are https.

Here is the stack trace:
```"stack":"TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded\n    at Promise.then (/home/node/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)\n  -- ASYNC --\n    at Frame.<anonymous> (/home/node/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/home/node/app/node_modules/puppeteer/lib/Page.js:674:49)\n    at Page.<anonymous> (/home/node/app/node_modules/puppeteer/lib/helper.js:112:23)"```

I have observed this in Headless mode only.

**Comment by OBrown92** [comment]
Hi @deepak-420,
I've tried many ways to get my sites running, but some seems to block the headless mode in some way. As mentioned in the previous post, puppeteer just display the error, so I solved my problem catching the error and resuming the script. 
```js
try {
   await page.setContent(html, {
      timeout: 5000
   });
} catch (error) {
   logger.error('SetContent timed out, try to load site anyway', error);
}
```
I mentioned that most of the sites, where the `SetContent timed out`, loaded normally.

**Comment by Abolfazl2647** [comment]
i have react snap and in beta there is no issue but as soon as i merge beta into master for production build i'm getting this error
```
$ react-snap
 ️️️💬  console.log at /: This script won't run on localhost
 🔥  error at / TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
     at /app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
   -- ASYNC --
     at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
     at Page.goto (/app/node_modules/puppeteer/lib/Page.js:674:49)
     at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
     at fetchPage (/app/node_modules/react-snap/src/puppeteer_utils.js:232:22)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
 error Command failed with exit code 1.
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 The command '/bin/sh -c yarn build' returned a non-zero code: 1
Running after_script
00:01
Uploading artifacts for failed job
00:01
 ERROR: Job failed: exit code 1
```

beta and production have same environment

**Comment by JohannHospice** [comment]
With react-snap v1.23 and my windows environment it works fine.
But on my ubunbu virtual machine i encounter the same problem.

```
🔥  error at / TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /home/runner/work/copilote/copilote/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/home/runner/work/copilote/copilote/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/runner/work/copilote/copilote/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/runner/work/copilote/copilote/node_modules/puppeteer/lib/helper.js:112:23)
    at fetchPage (/home/runner/work/copilote/copilote/node_modules/react-snap/src/puppeteer_utils.js:232:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
