### ISSUE TITLE
window.open is not doing anything in headless mode for a URL that is a PDF.

### ISSUE THREAD

**Issue by originative** [puppeteer/puppeteer#4518]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Mac OS X 10.11.6
* URLs (if applicable):
* Node.js version: 12.1.0

**What steps will reproduce the problem?**

Run the following code snippet.

```Javascript
const puppeteer = require("puppeteer");

async function test() {
  const browser = await puppeteer.launch({
    headless: true
  });

  const page = await browser.newPage();

  await page.goto(
    "about:blank"
  );

  await browser.once("targetcreated", async () => {
    console.log("targetcreated");
  });

  await page.evaluate(() =>
    window.open(
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
    )
  );

  browser.close();
}
```
**What is the expected result?**
Should output "targetcreated"

**What happens instead?**
Window is not opened.

If the URL is changed to https://google.com then the window is opened as expected. It also opens as expected if headless is false.

**Comment by aslushnikov** [comment]
@originative the window is not getting opened for you because Chrome Headless doesn't have a PDF viewer (and there are no plans to add one). When Chrome Headless navigates to a PDF file, it tries to download it instead.

Chrome headful, however, does have a PDF viewer - so it opens the window for you. That's why things work when you change URL to a google.com.

I hope this helps!

**Comment by originative** [comment]
This issue is that this makes it difficult to download a file if the website displays it in a new page. I’m trying to use Puppeteer to download bank statements etc. and quite a lot of these sites open the PDF in a new page.

Since the targetcreated event doesn’t fire it isn’t possible to set Page.setDownloadBehaviour on the new page to make the file download in headless mode.

Could window.open create a new window before trying to load the URL into it so that the targetcreated event fires first before loading the URL? If there’s no viewer could it then just throw an error?

**Comment by originative** [comment]
Actually I have an alternative idea. Could the DownloadBehaviour be set as a default for all pages in the browser context?

**Comment by aslushnikov** [comment]
> Since the targetcreated event doesn’t fire it isn’t possible to set Page.setDownloadBehaviour on the new page to make the file download in headless mode.

@originative that's a good observation, thanks for sharing! We'll need to support this usecase in #299. 

> Actually I have an alternative idea. Could the DownloadBehaviour be set as a default for all pages in the browser context?

The download behavior method is a workaround and has many shortcomings - we are not investing into it. We're exploring alternatives.
