### ISSUE TITLE
How to continue execution even if a download is in progress?

### ISSUE THREAD

**Issue by charlie632** [puppeteer/puppeteer#4520]
I'm doing a process that needs to download several files from different pages. What happens is that the execution is completely paused when a download is in progress, thus, I cannot advance with other instructions. Is there a way to keep the downloads in the background and let the script to continue?

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 10.1

**What steps will reproduce the problem?**
```javascrippt
await page._client.send('Page.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath: path.resolve(baseDir),
  })
await page.click(`#download`)

// other instructions

```

Tried removing the await on the click and the behavior is the same. 

**What is the expected result?**
Downloads continue in background

**What happens instead?**
Puppeteer waits for all downloads to finish to continue.

**Comment by aslushnikov** [comment]
@charlie632 something else is probably going on here - downloads already happen off-the-main-thread, so they don't block anything.

Can you share the actual script that doesn't work for you so that we can debug this behavior locally?
