### ISSUE TITLE
when multi request listeners added, request.continue() works in a confusing way

### ISSUE THREAD

**Issue by xiyuan-fengyu** [puppeteer/puppeteer#4524]
following code shows my question:
```typescript
import {launch, Request} from "puppeteer";

(async () => {
    const browser = await launch({
        headless: false,
        devtools: true
    });
    const page = await browser.newPage();
    await page.setViewport({width: 1920, height: 1080});
    await page.setRequestInterception(true);
    page.on("request", async (req: Request) => {
        await req.continue();
    });
    page.on("request", async (req: Request) => {
        await req.respond({
            status: 200,
            body: "test"
        });
    });
    await page.goto("https://www.baidu.com/");
    console.log();
})();
```
req.respond won't work in the second request listener and just throw an error.  
If multi request listeners added, how to decide whether request.continue should be called is confusing.  
  
In my way, I solve it as following  
```typescript
import {launch, Request} from "puppeteer";

(async () => {
    const browser = await launch({
        headless: false,
        devtools: true
    });
    const page = await browser.newPage();
    await page.setViewport({width: 1920, height: 1080});
    await page.setRequestInterception(true);

    page.on("request", (req: Request) => {
        const oldContinue = req.continue;
        let continueNum = 0;
        // override request.continue
        req.continue = (override?: any) => {
            if (override) {
                return oldContinue.call(req, override);
            }
            else {
                continueNum++;
                if (continueNum == page.listeners("request").length) {
                    return oldContinue.call(req);
                }
            }
        };
        return req.continue();
    });

    page.on("request", async (req: Request) => {
        await req.continue();
    });
    page.on("request", async (req: Request) => {
        await req.respond({
            status: 200,
            body: "test"
        });
    });
    await page.goto("https://www.baidu.com/");
    console.log();
})();
```

Is there a more elegant way to solve it?

**Comment by aslushnikov** [comment]
@xiyuan-fengyu in general, you should have only one place in code where you decide on request handling. Why do have multiple request event handlers?

**Comment by xiyuan-fengyu** [comment]
In my crawler framework，I need to supply some method to help user to disable image load, or proxy request for each page, or record request, and so on, all those need request interception.   
[PuppeteerUtil.setImgLoad PuppeteerUtil.useProxy](https://github.com/xiyuan-fengyu/ppspider/blob/master/src/puppeteer/PuppeteerUtil.ts)  
[NetworkTracing](https://github.com/xiyuan-fengyu/ppspider/blob/master/src/puppeteer/NetworkTracing.ts)

**Comment by aslushnikov** [comment]
@xiyuan-fengyu I see. Every request should be handled **exactly once**. This is not an artificial constraint: we cannot simultaneously "continue" request and "abort" it.

> If multi request listeners added, how to decide whether request.continue should be called is confusing.

Your framework has to do some arbitration on it's side to decide what it wants to do with every request. A good rule of a thumb is to have only one "request" listener that carries all the logic to decide request's fate.

Hope this helps.
