### ISSUE TITLE
interception does not work with page.setContent() and relative URLs

### ISSUE THREAD

**Issue by FranckFreiburger** [puppeteer/puppeteer#4526]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Windows 7
* URLs (if applicable):
* Node.js version: 11.11.0

**What steps will reproduce the problem?**

```javascript
import puppeteer from 'puppeteer'

;(async() => {

	const browser = await puppeteer.launch();
	const page = await browser.newPage();

	await page.setRequestInterception(true);

	page.on('request', interceptedRequest => {

		console.log( 'interceptedRequest:', interceptedRequest.url() )
		interceptedRequest.continue();
	});

	await page.setContent(`
	<html>
	<body>
		<img src="./foo.png">
		<img src="http://localhost/foo.png">
	</body>
	</html>
	`, { waitUntil: ['load'] });

	await browser.close();
})();
```

**What is the expected result?**

The output should show that `./foo.png` and `http://localhost/foo.png` are intercepted

**What happens instead?**

Only `http://localhost/foo.png` request is intercepted

**Comment by aslushnikov** [comment]
@FranckFreiburger This happens because the default page is opened on 'about:blank' url. This is a special URL - relative paths are not getting resolved against it, so the first image is not even attempted to be loaded.

If, before doing `page.setContent`, you do `await page.goto('https://example.com')`, you'll see both requests in your request interception. 

Hope this helps.

**Comment by marcusstenbeck** [comment]
@FranckFreiburger Right now I'm polyfilling `fetch()` to turn relative URLs into absolute for `about:blank`.

```js
  const browser = await puppeteer.launch(LAUNCH_OPTIONS);
  const page = await browser.newPage();

  // Polyfill fetch so it handles relative URLs in `about:blank`
  await page.evaluate(() => {
    const originalFetch = window.fetch;
    window.fetch = (inputResource, init) => {
      let resource = inputResource;

      // https://regexper.com/#%5E%5C%2F%28%3F!%5C%2F%29.*
      if (
        typeof resource === 'string' &&
        (resource.match(/^\/(?!\/).*/) || resource === '')
      ) {
        resource = `https://self.local${resource}`;
      }

      return originalFetch(resource, init);
    };
  });
```

@aslushnikov Is there a better way if I don't want to `page.goto()` but still want to intercept relative URLs?

**Comment by aslushnikov** [comment]
> Is there a better way if I don't want to page.goto() but still want to intercept relative URLs?

Maybe you can use `<base>` tag - but I'm not really sure. 🤷‍♂️

**Comment by marcusstenbeck** [comment]
@aslushnikov I realized that I avoid a lot of headaches by just doing a

```js
page.goto('file://path/to/empty.html')
```

and using that as a starting point. There is a lot of functionality that's limited in that `about:blank` page.

**Comment by casesolved-co-uk** [comment]
> > Is there a better way if I don't want to page.goto() but still want to intercept relative URLs?
> 
> Maybe you can use `<base>` tag - but I'm not really sure. 🤷‍♂️

Can anyone confirm if this works please?

**Comment by semtselishev** [comment]
I can confirm that `<base>` solves the problem
