### ISSUE TITLE
CPU borders on full capacity with a simple scraping process

### ISSUE THREAD

**Issue by beeirl** [puppeteer/puppeteer#4527]
**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: CentOS Linux 7 (Core)
* Node.js version: 12.3.1

**What steps will reproduce the problem?**

I use Puppeteer to set up a quite simple scraper which has the task to scrape meta data (OpenGraph properties or Schema.org properties) of about 500,000 URLs.
I process the URLs in parallel in up to 10 sets of 200 URLs each spread over up to 10 `browserContexts` with one `Page` each in a single Chromium instance.

I create a `browserContext` for each set, scrape the URLs and then close the `browserContext`. This procedure is repeated until all URLs have been processed.

The creation process of one `browserContext` looks like this:
(I manage all contexts in one instance variable, so I can easily reuse them when needed)
```
const contextName = 'browserContextId'
const context = await browser.createIncognitoBrowserContext()

const pageName = 'pageId'
const page = await context.newPage()
await page.emulate({
	name: 'default',
	userAgent: `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/0;) Safari/537.36`,
	viewport: {
		width: 1366,
		height: 768,
		deviceScaleFactor: 1,
		isMobile: false,
		hasTouch: false,
		isLandscape: true
	}
})

this.contexts[contextName] = context
this.contexts[contextName].pages[pageName] = page
```

The scraping process for each URL looks like this:
```
const page = browser.contexts[contextName].pages[pageName]
await page.goto(url)


await page.evaluate(() => {
    let date, description

    let schemaOrg = document.querySelector('script[type="application/ld+json"]')

    if (schemaOrg) {
        schemaOrg = JSON.parse(JSON.stringify(schemaOrg.innerHTML))
        date = schemaOrg.datePublished || schemaOrg.dateModified || schemaOrg.dateCreated
        description = schemaOrg.description
    }

    if (!date) {
        date = document.querySelector('meta[property="article:published_date"]')
        date = date ? date.getAttribute('content') : null
    }

    if (!description) {
        description = document.querySelector('meta[property="og:description"]')
        description = description ? description.getAttribute('content') : null
    }

    return {
        ...(date && { date }),
        ...(description && { description })
    }
})
```

After the URL set has been processed, I close the `browserContext` and start again from the beginning
```
await browser.contexts[contextName].close()
delete browser.contexts[contextName]
```

**What is the expected result?**

A resource-saving and performant scraping. 

Above all, I no longer know how to optimize my code, especially since I have already tried to
- split the scraping between several instances of Chromium,
- split the scraping on several `Pages` in one Chromium instance,
- and split the scraping between several `browserContexts` in one Chromium instance

**What happens instead?**

I already reach full CPU usage after a few hundred URLs (with an 8-core system)

> Please note: The above code does not represent my implementation 1:1. I have specifically tried to make my implementation as simple and comprehensible as possible. I therefore ask for your indulgence for any inconsistencies or minor errors.

**Comment by Druux** [comment]
Oh, it seems like `page.emulate()` and` page.setUserAgent()` in general slow things down immensely. Did I miss something?

**Comment by aslushnikov** [comment]
> I already reach full CPU usage after a few hundred URLs (with an 8-core system)

Hey @Druux, do I understand correctly that the resource consumption grows over time? If there's no bug in the code, can you please setup process CPU/memory watchers to get an idea which part of chrome actually consumes your system resources?

**Comment by beeirl** [comment]
@aslushnikov Yeah you are right, it seems like that the resource consumptions grows over time.
Sure I can do that. Do you have any suggestions regarding the CPU/memory watcher - I have no experience in monitoring a headless chrome process in specific. Or should I just monitor the pid with `ps` for instance?

**Comment by aslushnikov** [comment]
@Druux if you can monitor the whole tree that roots at chrome's process - that would be ideal.

The chrome process pid can be retrieved with javascript:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  console.log(browser.process().pid);
  await browser.close();
})();
```

**Comment by drmrbrewer** [comment]
I am also finding that CPU usage with puppeteer is a lot higher than it is using phantomjs, for an equivalent workload, and this is the only thing holding me back from using puppeteer... server costs are far less using phantomjs!

**Comment by drmrbrewer** [comment]
Using the launch options from [this post](https://stackoverflow.com/a/58589026/4070848) has made a HUUGE difference for me!  @aslushnikov why are these launch options never mentioned on here as being something to try, when people have in the past (e.g. [here](https://github.com/puppeteer/puppeteer/issues/4027) and [here](https://github.com/puppeteer/puppeteer/issues/2965) and [here](https://github.com/puppeteer/puppeteer/issues/2211)) have observed that CPU usage appears to be higher than expected?  Are there any other launch options that would be useful to add, to minimise CPU usage?

**Comment by kunle** [comment]
Also this a list of all the options so you are not blindly copying and pasting and hoping there is magic.
https://peter.sh/experiments/chromium-command-line-switches/
