### ISSUE TITLE
Evaluating code in different JavaScript Context of a page

### ISSUE THREAD

**Issue by MehdiRaash** [puppeteer/puppeteer#4529]
In my case, there is page with 2 iframes inside each other from different origins.
I can not access to their ExecutionContext due to security reason.(I also put --disable-web-security)

Now I just want to access the inner Iframe's DOM. 

my question's I can access the desired DOM through web Console and changing the JS context, but How can I achieve it through pupputeer.

**Comment by aslushnikov** [comment]
@MehdiRaash you can reach out to the iframe you want with [`page.frames()`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-pageframes) method. After you find the iframe you want, you can use [`frame.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-frameevaluatepagefunction-args) to evaluate inside frame's context.

```js
// find the iframe we care about
const iframe = page.frames().find(iframe => iframe.url().includes('localhost'));
// evaluate inside a particular iframe
await iframe.evaluate(() => console.log('Look! I am inside iframe!'));
```

Hope this helps!

**Comment by MehdiRaash** [comment]
Dear Contributor, My problem is first when I use this code `page.frames().find(iframe => iframe.url().includes('localhost'));` I just get one Object.

but when I use `page.$$('iframe')` I got 3 object.
My actual iframe is not discoverable by the first code but the second.

If I could change JS context in pupputeer just l like I do in console, my problem would solve.
