### ISSUE TITLE
BrowserFetch:  Download failed: server returned code 404

### ISSUE THREAD

**Issue by mazlano27** [puppeteer/puppeteer#4531]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-core: "^1.17.0",
* Platform / OS version: Mac OS
* Node.js version: 12.3.1

**What steps will reproduce the problem?**

1. Get Chromium Rev Version From https://omahaproxy.appspot.com/all.json?os=mac

2. Use Browser Fetch To Download Chromium (Stable)

3. Download Fails

**What is the expected result?**

Chromium browser should download.

**What happens instead?**

 It was working fine until last night - since this morning, the download has failed. 

`Error: Download failed: server returned code 404. URL: https://storage.googleapis.com/chromium-browser-snapshots/Mac/652427/chrome-mac.zip`

<img width="995" alt="Screenshot 2019-06-06 at 3 38 52 PM" src="https://user-images.githubusercontent.com/29986983/59015678-1dda3600-8872-11e9-8864-0f1697574746.png">

When I navigate to the URL in browser:

<img width="827" alt="Screenshot 2019-06-06 at 3 38 17 PM" src="https://user-images.githubusercontent.com/29986983/59015252-22eab580-8871-11e9-9dc7-6b016ce771c8.png">

**Comment by vasani-arpit** [comment]
In my case, Beta and Dev channel is not working as well.

**Comment by mazlano27** [comment]
After some testing, i've found that the branch_base_position listed in omahaproxy.appspot.com are not working. On Mac - only the canary build downloads.

**Comment by vasani-arpit** [comment]
@mazlano27. Every channel used to work. This happened recently. Not sure why.

**Comment by aslushnikov** [comment]
@mazlano27 Unfortunately, **not every revision** of chromium is downloadable. Chromium CI builds only some revisions, and builders on different platforms operate at different speeds.

To see which revisions are available, we have a small script to helps us see what is downloadable and what is not: [`//utils/check_availability.js`](https://github.com/GoogleChrome/puppeteer/blob/master/utils/check_availability.js). 

You can run it from your terminal and will check which revisions for which platforms are downloadable:

![image](https://user-images.githubusercontent.com/746130/59055906-cd4fe200-884b-11e9-985e-a41a97fba0cd.png)

The script accepts a few arguments - you can learn more about it with `./utils/check_availability.js --help`.

Hope this helps!

**Comment by mazlano27** [comment]
@aslushnikov Thank you for your explanation and for sharing the check_availability.js utility - it makes it easy to find the versions of chromium which are downloadable. I'd like to filter out the stable builds to use in my project - am I correct in assuming the builds shown in the utility are not only for stable builds, but for also dev, canary etc?

**Comment by vasani-arpit** [comment]
@aslushnikov Thanks for the clarification.

In may case
I am querying https://omahaproxy.appspot.com/all.json?os=[win/mac/linux] for the versions infos
Doesn't it provide all the downloadable versions for that particular OS?
here is my logic

https://github.com/vasani-arpit/WBOT/blob/master/src/detectRev.js

Problem is if I use the number provided by getRevNumber function in **puppeteer's browserFetcher.download** method I am getting 404 error.

**Comment by mazlano27** [comment]
@vasani-arpit Based on my research and testing, the way the Chromium version is build is also important for browserFetcher. Chromium may be built as an Archive, Installer, Portable or Package.

For a Mac, the latest Chromium revision (652427) is only built as an Installer (For now) - I believe the browserFetcher API requires an Archive - thus the download fails. 

For Windows, the latest Chromium revision (652427) is built as an Archive, Installer and Portable - I suspect the download succeeds? I am unable to test it.

This is just my working understanding at the moment, and I may be completely wrong.

**Comment by vasani-arpit** [comment]
You are right but I can't put the value 652427 or 652427 hard-coded in the app(because tomorrow that might be different as new version comes out). I need do determine latest revision at the time of execution.  That's what I tried to do with https://omahaproxy.appspot.com/all.json?os=mac

**Comment by mazlano27** [comment]
@vasani-arpit I was thinking about your requirement and have found an automated solution for your needs.

**If your app works with any release of Chromium:**
(Based on code from //utils/check_availability.js)
1) Get Chromium Rev Version From https://omahaproxy.appspot.com/all.json
2) Use browserFetcher.canDownload(rev) to test if it can be downloaded.
3) If it cannot be downloaded, -1 from the rev version and try again.
4) Repeat until download succeeds.

**If your app works with stable release of Chromium:**
1) Get Chromium Rev Version From https://omahaproxy.appspot.com/all.json?channel=stable
2) Use browserFetcher.canDownload(rev) to test if it can be downloaded.
3) If it cannot be downloaded, get the previous_version from  https://omahaproxy.appspot.com/all.json?channel=stable (Should be in the format of Major.Minor.Branch.Patch)
4) Get Rev Version of previous_version using https://omahaproxy.appspot.com/deps.json?version=[major.minor.branch.patch]
5) Download Chromium using Rev Version of previous stable release

**Comment by vasani-arpit** [comment]
That's a good analogy. Let me try that. Thanks @mazlano27

**Comment by aslushnikov** [comment]
> am I correct in assuming the builds shown in the utility are not only for stable builds, but for also dev, canary etc?

@mazlano27 `BrowserFetcher` downloads *Chromium* builds - not *Chrome*.  The "stable", "dev" and "canary" channels are *Chrome* channels and a separate set of builds.

Unfortunately, we can't auto-download Chrome for CLA-related reasons. 

> In may case
> I am querying https://omahaproxy.appspot.com/all.json?os=[win/mac/linux] for the versions infos
> Doesn't it provide all the downloadable versions for that particular OS?

@vasani-arpit it doesn't - Chromium builders are independent from Chrome builders. So the `//utils/check_availability.js` uses omahaproxy revision numbers only as a baseline.

**Comment by vasani-arpit** [comment]
Thank you @aslushnikov for the explanation. 👍👍
