### ISSUE TITLE
Failed to launch chrome: Received signal 11 SEGV_MAPERR 000000000000 after update to 1.17.0

### ISSUE THREAD

**Issue by walter-db** [puppeteer/puppeteer#4533]
Puppeteer version: 1.17.0
Macos: 10.14.3
Node.js: v12.1.0

After updating Puppeteer from version 1.16.0 to 1.17.0, our scrips are failing with following errors:

     Error: Failed to launch chrome!
Received signal 11 SEGV_MAPERR 000000000000
 [0x0001123190a9]
 [0x000112261ba3]
 [0x000112318fd1]
 [0x7fff57f53b3d]
 [0x000000000030]
 [0x000113c9710c]
 [0x0001100c0d69]
 [0x000110941e5c]
 [0x000110941fb7]
 [0x00011011d8b0]
 [0x000112c59a95]
 [0x000112c59b86]
 [0x0001122c12c0]
 [0x0001122d04b0]
 [0x0001122d09a9]
 [0x00011227fff3]
 [0x0001122737ca]
 [0x00011227f95f]
 [0x7fff2ab34395]
 [0x7fff2ab3433b]
 [0x7fff2ab17dd1]
 [0x7fff2ab1737a]
 [0x7fff2ab16c64]
 [0x7fff2ce7d4aa]
 [0x000112280671]
 [0x00011227f328]
 [0x0001122d0d98]
 [0x0001122a4687]
 [0x0001122ee4a4]
 [0x000112322037]
 [0x7fff57f5c305]
 [0x7fff57f5f26f]
 [0x7fff57f5b415]
[end of stack trace]

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

      at onClose (/Users/Shared/Jenkins/slave/workspace/Onda-Web-Test-Automation/node_modules/puppeteer/lib/Launcher.js:342:14)
      at ChildProcess.<anonymous> (/Users/Shared/Jenkins/slave/workspace/Onda-Web-Test-Automation/node_modules/puppeteer/lib/Launcher.js:332:60)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)

Roll back to Puppeteer 1.16.0 does remove the error.

**What is the expected result?**
Expected Chrome headless to be started, and test ran properly.

**What happens instead?**

Chrome launched and immediately crashing.

**Comment by aslushnikov** [comment]
@walterngti do you run in a docker? If yes, can you share your dockerfile? Can you run `ldd` against chrome binary and see if there are any dependencies missing?

**Comment by walter-db** [comment]
We are running this in a bash shell on MacOs, not in a docker container.
When having puppeteer 1.17.0 installed, otool shows following:
```
node_modules/puppeteer/.local-chromium/mac-662092/chrome-mac/Chromium.app/Contents/MacOS/Chromium:
	/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1452.23.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.51.6)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.50.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

With puppeteer 1.16.0:
```
otool -L node_modules/puppeteer/.local-chromium/mac-656675/chrome-mac/Chromium.app/Contents/MacOS/Chromium
node_modules/puppeteer/.local-chromium/mac-656675/chrome-mac/Chromium.app/Contents/MacOS/Chromium:
	/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1452.23.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.51.6)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.50.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
mac-jenkins03:nodejs jenkins$ 
```

**Comment by aslushnikov** [comment]
@walterngti interesting. Can you try installing `puppeteer@next` and see if it works for you?

**Comment by walter-db** [comment]
Same issue when running witgh puppeteer@next..

**Comment by joeyvandijk** [comment]
I can confirm that removing the `--disable-gpu` solved the error for me. I ran Chromium 77.0.3851.0 on OSX 10.14.5 with puppeteer 1.18.1. The same `signal 11` error happened at https://github.com/GoogleChrome/puppeteer/issues/4040 with another error, but wanted to check if the `--disable-gpu` had anything to do with the hickup.

**Comment by sunilrebel** [comment]
For me, I was including a `.bin` compiled file of `.js` while doing development. Switching from `.bin` to correct `.js` file solved the issue.

**Comment by seyfer** [comment]
I have this error when I am trying to use footer HTML with a link inside to an external CSS file.

**Comment by uladzimirdev** [comment]
I have the same error at github actions, no idea what's the reason, but chrome can't start
