### ISSUE TITLE
before 'disconnection' hook in puppeteer-core

### ISSUE THREAD

**Issue by MehdiRaash** [puppeteer/puppeteer#4534]
Actually it's become an issue for me and maybe others.

In my case I set some MutationObserver and intervals and I need to clear them before pressing  `Ctrl + C` on my windows. I'm using puppeteer-core, and the browser page should remain **open**.

How can I attach some functions before 'disconnection'?

**Comment by aslushnikov** [comment]
> How can I attach some functions before 'disconnection'?

@MehdiRaash There's no pre-disconnection hook - we don't know when browser will disconnect, we can only notify about this event.

However, since you say that you abort your program with `Ctrl + C`, you can subscribe to the nodejs `process.on('SIGINT')` event and do the cleanup there. Will it work?

**Comment by MehdiRaash** [comment]
Yeah, pretty good, in my case, Thanks.
