### ISSUE TITLE
Ways to notify puppeteer of the browser

### ISSUE THREAD

**Issue by MehdiRaash** [puppeteer/puppeteer#4538]
In a lot of cases I saw this piece of code to notify puppeteer aware of browser actions.

 

>   page.on('console', msg => {
>          if(msg.text() === "someThing happened In the Browser"){
>            //let's do something
>          }
>   }); 

I also saw `exposeFunction` which is good in some other ways.

**But what's the appropriate way to do so?**

Let's say you wanna listen for a DOM mutation and then you wanna notify puppeteer in a event-based fashion, I saw the first case practical but not nice.

**Comment by ryo-hisano** [comment]
Does this issue serve as a reference?

Monitor for text change in an element · Issue #2945 · GoogleChrome/puppeteer
https://github.com/GoogleChrome/puppeteer/issues/2945

**Comment by aslushnikov** [comment]
> But what's the appropriate way to do so?

@MehdiRaash both [`page.exposeFunction`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-pageexposefunctionname-puppeteerfunction) and [`page.on('console')`](https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-event-console) will serve well for page-to-node.js communication. They're roughly equal functionally, but depending on your usecase one might work better than the other.

> Let's say you wanna listen for a DOM mutation and then you wanna notify puppeteer in a event-based fashion, I saw the first case practical but not nice.

The #2945 is a very good reference indeed.
