### ISSUE TITLE
Incognito mode launches second window

### ISSUE THREAD

**Issue by matthiasthomas** [puppeteer/puppeteer#454]
I tried using the --incognito flags of chromium. Though it doesn't work as expected, it launches a second chrome window in incognito mode but executes the rest of the instructions in the other non-incognito window.

```
puppeteer.launch({
    args: ['--incognito']
})
```

**Comment by aslushnikov** [comment]
The incognito mode is a special case of browser contexts which are yet to be implemented: #85. Feel free to star that issue to get updates.

**Comment by Mahanchello** [comment]
Guys, has that issue been  resolved? I have the same situation.
