### ISSUE TITLE
page.setRequestInterception(true); always throw exception " UnhandledPromiseRejectionWarning: Error: Protocol error (Fetch.enable): 'Fetch.enable' wasn't found"

### ISSUE THREAD

**Issue by faiyazshk** [puppeteer/puppeteer#4542]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
1.17.0

* Platform / OS version:
Windows 7 Enterprise 64
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

* Node.js version:
v12.1.0

**What steps will reproduce the problem?**
While using local Chrome with path specified not able to intercept request and it throws error as 

(node:56332) UnhandledPromiseRejectionWarning: Error: Protocol error (Fetch.enable): 'Fetch.enable' wasn't found
    at ..\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (..\node_modules\puppeteer\lib\Connection.js:182:12)
    at NetworkManager._updateProtocolRequestInterception (..\node_modules\puppeteer\lib\NetworkManager.js:145:22)
    at NetworkManager.setRequestInterception (..\node_modules\puppeteer\lib\NetworkManager.js:134:16)
    at Page.setRequestInterception (..\node_modules\puppeteer\lib\Page.js:244:48)
    at Page.<anonymous> ..\node_modules\puppeteer\lib\helper.js:111:23)
    
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:56332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:56332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have removed local path reference from above trace but that is the error

_Please include code that reproduces the issue._
configuration for browser
        headless: true,
        executablePath: 'chrome.exe',
        devtools: true,
        ignoreHTTPSErrors: true,        
        args: ['--enable-features=NetworkService']

**What is the expected result?**
To intercept the request which works on Chromium properly

**What happens instead?**
It throws this error and the script stops.

**Comment by aslushnikov** [comment]
@faiyazshk if you use custom chrome executable, please use version of Puppeteer that matches chromium version. 

Please check out our FAQ Entry: [Q: Why doesn’t Puppeteer v.XXX work with Chromium v.YYY?](https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

**Comment by faiyazshk** [comment]
I went back to the version for chrome 71 
    "puppeteer-core": {
      "version": "1.9.0",
      "resolved": "https://registry.npmjs.org/puppeteer-core/-/puppeteer-core-1.9.0.tgz"

but still I am not able to intercept the request only response interception works when used in isolation but if used alongwith with request interception that also fails.

**Comment by aslushnikov** [comment]
@faiyazshk at least the "Protocol error (Fetch.enable): 'Fetch.enable' wasn't found" shouldn't happen any more. For the other problem you have, please file a separate issue with a repro script that we can use to debug your problem.

**Comment by faiyazshk** [comment]
fetch.enable is still an issue I found out it goes away when I disable devtools. The real problem is request interception it just does not work with chrome 71 with devtools enable it give fetch.enable error and without it, it goes straight without doing anything.

**Comment by aslushnikov** [comment]
Puppeteer 1.9.0 doesn't use fetch domain at all. I'm not sure what errors are you seeing there.

Do you have a script that I can try running and reproduce it locally?

**Comment by faiyazshk** [comment]
Here is the script 

const puppeteer = require('puppeteer-core');

async function main() {
    const browser = await puppeteer.launch({
        headless: false,
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
        devtools: false,        
    });
    const page = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36');    
    await page.goto('https://www.google.com',{'networkIdleTimeout0': 5000, waitUntil: 'networkidle0', timeout: 3000000});
    await page.waitForSelector('#tsf');    
    await page.type('input[name=q]', "Quantum Mechanics", {delay: 20});  
    
    //await page.setRequestInterception(true);
    /*page.on('request', async request => {
        console.log('INTERCEPTED Request: ' + request.url());
        console.log(await response.method());        
    });*/
    page.on('response', async response => {
        console.log('INTERCEPTED Response: ' + response.url());
        console.log(await response.status());        
    });
    await page.click('input[name=btnK]');             
}
main()

1) Run as is and see response
2) Run uncommenting just line 15 
3) Run uncommenting everything.

**Comment by NickStefan** [comment]
I'm getting this exact same error with puppeteer 1.20.0 with 69.0.3497.81. I found that the error goes away if I stick with puppeteer 1.8.0 with 69.0.3497.81.

Seems like a regression?

```
const makePage = async (_browser, pageHTML, width, height) => {
    const page = await _browser.newPage();
    await page.setViewport({ width, height });

    await page.setRequestInterception(true);
    page.once('request', (request) => {
        request.respond({
            body: pageHTML.toString('utf8'),
            contentType: 'text/html; charset=utf-8',
        });
        page.on('request', (_request) => _request.continue());
    });
    return page;
};
```
```
{ Error: Protocol error (Fetch.enable): 'Fetch.enable' wasn't found
    at Promise (/var/task/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/task/node_modules/puppeteer/lib/Connection.js:182:12)
    at NetworkManager._updateProtocolRequestInterception (/var/task/node_modules/puppeteer/lib/NetworkManager.js:139:22)
    at NetworkManager.setRequestInterception (/var/task/node_modules/puppeteer/lib/NetworkManager.js:128:16)
    at Page.setRequestInterception (/var/task/node_modules/puppeteer/lib/Page.js:289:48)
    at Page.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:112:23)
    at makePage (/var/task/robots/capture.js:29:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Protocol error (Fetch.enable): \'Fetch.enable\' wasn\'t found' }
```

**Comment by leblancmeneses** [comment]
interceptors work fine locally for me but when executing under docker I get the protocol error mentioned in the bug.

The referenced doc that closed this bug basically says to use the chromium downloaded in ```node_modules/puppeteer/.local-chromium/linux-xxxxxx/chrome-linux/chrome```

https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy

However, the alpine docs https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine
say to use the distribution chromium.  These instructions cause the exception.


I moved my docker image to use:
https://github.com/GoogleChrome/puppeteer/blob/a582c11b1befb2e0059bcfad7488ff84761c78f5/.ci/node12/Dockerfile.linux
and the problems went away.
