### ISSUE TITLE
Save an embedded pdf file

### ISSUE THREAD

**Issue by dimkar121** [puppeteer/puppeteer#4544]
Hallo,
I am trying to save an embedded pdf file (the url that appears is the same as the opener tab). There is a link that opens a new tab where the pdf file appears. Although the whole process is fine when it comes to saving the pdf  it seems to be quite hard.

thanks in advance,
Dimitrios

**Comment by deepak-mali** [comment]
I am also facing the same issue.

**Comment by k19810703** [comment]
Me too

**Comment by ogomez92** [comment]
Did you guys fix this?

**Comment by dimkar121** [comment]
No not at all

Στις Παρ, 21 Φεβ 2020 στις 12:45 μ.μ., ο/η ogomez92 <
notifications@github.com> έγραψε:

**Comment by drdrej** [comment]
need a fix also ) 
dont work...

to retry: just open a page with embedded pfd and try to save it

**Comment by OrKoN** [comment]
Could someone provide a repro script for this? Could you intercept the target URL and use it to download the file using Node?
