### ISSUE TITLE
Provide option to set screenshots' default directory

### ISSUE THREAD

**Issue by Flyrell** [puppeteer/puppeteer#4552]
Screenshots are saved to the `path` provided in the `options` object of the [screenshot](https://github.com/GoogleChrome/puppeteer/blob/v1.17.0/docs/api.md#pagescreenshotoptions) function. If the `path` is not provided, the screenshot is being saved to [`process.cwd()`](https://nodejs.org/api/process.html#process_process_cwd).

```javascript
await page.screenshot({
    path: `../screenshots/${screenshotName}.png` // saved in provided path
    // or 
    path: undefined  // saved in `process.cwd()`
});
``` 

When I want to have a centralized directory where I store my screenshots (as I do some post-processing, email sending, etc.) it's a little bit annoying to write the same path over and over again when calling `screenshot` function. So, I always end up writing my own wrapper of it, which is not a problem, but I believe it'd be more elegant when it's an integrated option. Anyway, it would be nice to have the screenshots in a separate directory, outside of the code and config files.

My proposal would be to add `screenshotsDir` path where the screenshots would be saved. This can probably be a part of [`puppeteer.launch`](https://github.com/GoogleChrome/puppeteer/blob/v1.17.0/docs/api.md#puppeteerlaunchoptions) options and I think the correct behavior would be:

1. If `path` **IS** set while calling screenshot, it will be appended to the `screenshotsDir`
2. If `path` **IS NOT** set while calling screenshot and `screenshotsDir` exists, `screenshotsDir` will be used

In any other situation puppeteer would behave as it does now. What do you think? I would probably be able to make a PR later this week.

**Comment by bvandrc** [comment]
> We are closing this issue. If the issue still persists in the latest version of Puppeteer, please reopen the issue

This is not a bug, it is a feature request.
