### ISSUE TITLE
get stuck while doing page.setContent  

### ISSUE THREAD

**Issue by ZenkyuJo** [puppeteer/puppeteer#4555]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.1
* Platform / OS version: Windows 10
* Node.js version: v10.15.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

<pre>

const htmlContent = "&lt;html&gt;\n" +
    "&lt;body style='margin:0'&gt;\n" +
    "    &lt;div&gt;\n" +
    // "    &lt;img src='https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg' id='shouldBeRemoved' /&gt;\n" +
    "        &lt;table style='width:100%;' class='entryTable'&gt;\n" +
    "            &lt;colgroup&gt;\n" +
    "                &lt;col style='width:35.539215%;'&gt;\n" +
    "                    &lt;col style='width:24.509804%;'&gt;\n" +
    "                        &lt;col style='width:24.509804%;'&gt;\n" +
    "                            &lt;col style='width:15.441176%;'&gt;\n" +
    "            &lt;/colgroup&gt;\n" +
    "            &lt;tr&gt;\n" +
    "                &lt;td style='font-size:13px;padding:0 12px 0 0;text-align:right;color:#888888;background:#F5F5F5;line-height: 150%;;overflow: hidden;word-break: break-word;;height:16px;' class='dfMode '&gt;ID&lt;/td&gt;\n" +
    "                &lt;td style='font-size:13px;padding:3px;line-height: 150%;;overflow: hidden;word-break: break-word;;;' class='dfMode '&gt;00002&lt;/td&gt;\n" +
    "            &lt;/tr&gt;\n" +
    "            &lt;tr&gt;&lt;/tr&gt;\n" +
    "            &lt;td&gt;&amp;nbsp;&lt;/td&gt;\n" +
    "            &lt;tr&gt;\n" +
    "                &lt;td style='font-size:13px;padding:0 12px 0 0;text-align:right;color:#888888;background:#F5F5F5;line-height: 150%;;overflow: hidden;word-break: break-word;;height:16px;' class='dfMode '&gt;Signature&lt;/td&gt;\n" +
    "                &lt;td style='font-size:13px;padding:3px;line-height: 150%;;overflow: hidden;word-break: break-word;;;' class='dfMode ' colspan='3'&gt;&lt;img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAXWklEQVR4Xu2dfch9S1XHvxZ26YUs7VqWWYEUUna1yH+0TP/I3iwFM8vIQoUiwQz7wyBuhVRkoAVRUGRBdYWKa5YgllhoYRH2ovQighplIpV17fZipfHx2Uvnzm/vs2fvM/vsmbO/Gx6e8zxn9uyZ75r57rXWrFlzP/kyAkbACHSCwP06aaebaQSMgBGQCcuDwAgYgW4QMGF1Iyo31AgYAROWx4ARMALdIGDC6kZUbqgRMAImLI8BI2AEukHAhNWNqNxQI2AETFgeA0bACHSDgAmrG1G5oUbACJiwPAaMgBHoBgETVjeickONgBEwYXkMGAEj0A0CJqxuROWGGgEjYMLyGDACRqAbBExY3YjKDTUCRsCE5TFgBIxANwiYsLoRlRtqBIyACctjwAgYgW4QMGF1Iyo31AgYAROWx4ARMALdIGDC6kZUbqgRMALXTliPknSHpM+V9CmDuPn8lcPnJ0j6cw8DI2AE+kDgWgnrOyT9hKTbZ8TwAkkv60NUbqURMALXSFi/JOlZM6L9N0m/L+l7Jb3Tw8AIGIE+ELg2woKEHj8C/b2SfkHSKyX9q83APganW2kEcgSuhbDwT71eEj6r/PqApC+wJuXBbwT6R+BaCAvHOc71/HqXpKdYo+p/oLoHRgAEroGwMPO+cUScfzCQFSagLyNgBK4Agd4Ji9XAl0+QVYQuXIGY3AUjYAR617DwW73PmpUHshE4DgI9a1hjpiBmoDWr44xf9/RgCPRKWDjS785khYOdVUL7rA42iN3d4yDQK2FBSg/IxPRorwYeZ+C6p8dEoEfCyiPZiVpH4yJo1JcRMAJXjEBvhDW2KsgGZpPVFQ9Sd80IBAI9ERb+qTdJum1ovDUrj2MjcDAEeiEsyAonO6lhuN4t6evsszrYaHV3D49AD4QFWbFPMPJZEbqAaegsC4cfvgbgaAi0TljEVEFWcRG6wP9MVkcbqe6vEWh8LyErf2y7Cc3qL4bVQJOVh64ROCgCrWpYJNZ7aaZZOevCQQepu20EWl4l/CFJdyYiQrPCDHQEu8etETg4Aq1pWHlQqMnq4APU3TcCKQItEVauWXkjs8eqETAC90GgFcLKyeqnhgMiLC4jYASMwEcQaIGw8swLPnrLA9QIGIFRBPYmLJzpRLBH6ILJatuByk4B0kkTjPskSW+W9DzHtW0Lumuvh8CehMXkISg0ttuYrOrJNa2JlwHnNLI7YOxUIZvf2+DuWjdAYE/CeqOkxw59MlnVFy7k9Pwh2DY0WJ7y1uHYs/sPj/xOSazO+jICzSOwF2Gl4Qs/Ken7m0eqnwYSdItGlWpTbGl6maQHSvrBpCu/NRBaP71zSw+NwB6Ela4I/vJgqhxaCGd2Hj8gP5x4neazJ/0Oee8hKs5tzHPg+xi0M4G/wO1oxsiVhSl+uMj/hjwPeV2asNIEfLzd+dsR7MuGHj6/ICcGcWruURM+qSAosOV79mTGgKfMvZIed+SBvwzyi5VGK/6c4cXD57EDVQ7tPrkkYaUrgt7IXD4H0rcsGMYiRdSAufcKSa8ZybzKvazC5gP/hyWh6fraFwFIKTSoudOe0JjJrIvJf9gEAJcirHRFEOARzmHV2oI5Aj4RfjA2kDHnMPEYwFM4QlaswuYrg4d+Qxdgv3WRWLWFePKXT/7sMOtD1oe3Ri5FWLwRUHXDBncO9vsOzXjTQk6p6RalYuCCG4N3buAyEdCsTFZb0095/ciWBY8nnrgltCjkfOplVP7UKyt5CcJKnb02RW4G0JwfijJoUUFQS7TRPENrDFlrVvtMXmRNqqSxF1G0CH8uK+fMFV8nENiasLwieAM+b1c0zCdL+tIJUwC/XrxZ1w7cPEOryWq/6Y/pB1GxsDR1QVTMkSUvpP161MCTtySsdI8gk3EsyroBCKo3gTfqHQNJ8XnqzZoSFEQ1Z+bNNXTsCDTuearf3HPQVf0eoiJgFx9VvoIbD7pnKOOA3YXQb0VYqVlSIw87gkd7uF3S2yRRZysrJbQrCIp+n3Kk3iXptYV+qCWizDO0cq8XN5YgWKcsAbtoTKfGAG4RYuPOfUHVaXFntWxBWJDLnw1CO/fsQMgg9sHl0KJGI3iCTy95pQTF56m3aLQJtR8Tr8RZvqYfeWoe6nDYyBok19/DOMD8O2VFME6RVSsv2vW93fHOLQgrdbKf4+jNI7OnYOJNxUAgYHKLa0msTGg2sQy9FUlFP18i6YVZp73dZotRMF5nqUPdfqpKMqlNWKlpck4WAHw6BNQtud4v6eck/eiZ6nZKUHye06BSkgpNakm715Yd06zAnP/b3FiLatl9EUsF1lPjA7cFfkWH8JRhWlSqJmGlfqtz9qnx1nrHSOv53z9I+r3hu4dK+ipJD8vK/rukNwym4ntOoPBBSR8zfI9KT/u/RtJtRcjdmF1BUJde5clz39NkZ10oFNyZxRgnbHWaMv9wg/DitkP9TKDHbq9JWExanM8IDGGutdW5Fx9Ya1ftVb21/cvJCry/R9Kvrq3Q9xUjAFGdClOwQ70YynUFaxFWap7UWEYP8lvXqzp3oSXSjoiNasHMyv165y5q1EHq+mtBA4esplb/8Bseeo/fpYZADcJKNaJz/FZ5nxkc1B2hAvH7AZXA+VBy8jUTH40QcvpNSW9p0A80Rla87dcGmVaC8eqrIaZqyleF1g1R2U91oWFQg7BCG7pkcGjuDMfxGalUUk3o4ZJeLOnTBzxfLenbhs8taEylYh5bMX20I6RL4VtVbirTBZXxgiOkxhkvVkG7/qZzCQuh8QY612+1vgdld6Z+n7+V9NVn+NjKnlivVGAcNTogtB62UzVN7cekvM2/7fGffMI5hJUKtYcVqjRmCe2KNrduTuXbbVgqZ6vPpVcldxyiF380L2BeEvnlMIWLi+LWB55DWGEK9pTmOF9hw/+wVcDpueLNNzK3rsWe29+978cEvHPiAF+v/u0tneH5awkrVgUv6beqBVnuD2ox5Q3a6x9J+vih095qU0v64/WMpZGmJCvFvNSs0W6Lf3HtawgrTEHu7TFzKIMTTYuMnnFBYoRjtHDl5zVyLBdpadbGtbXQp5bbMOavQpv1CmyDUltDWLFt5px9gntDAWnRDwJd44LE8GvteUFWBM3Gdg/e8Ewck9U2UsEfSHxVur0GFwdaVU+ryNug02CtSwnrmZJ+ZVgpOZVBscGu3tIkyAHSitTNFKgZR7YUg1yzshm4FMFl5fOUPODNy8Hm3zIcL1p6CWHFhGKv3iMv2srtHoY5AGmlwah7rHimKXnorVcDt5N57q+KQ2bHVga3a4VrXoVAKWGlQXTXFrCYhw5gClzysMr8dBvHWa0aykU35YdzOKaqCLZ2CpUSVqwK7mkybYlaHpyJzwhivoQfI1+1vLYXwpZyW1I3Lgx2PXyhV/+WwNZW2RLCinggVGdMqEtM4kujtJcTPvejoNl5X1p96fNCInPteyX97ERgaP2nusbqCJQQVgSIXvtkwlygr6k/q0bmiSmh5YGhPa+6Vh+YlSpMFzJs/lUCdc9q5ggr/Dssr88dpb1nP2o9e8yfhYlWO6wgj/25VlO7llzW1BOydEK9Neg1es8cYYV2taWm0Ro0+fYdTDS0y1pXviL4h5IeV6ty1/PhmCpiq/BZef/flQ2IU4QVea54Q5XkNb8WaMb8WeSK/+5KHUzz1TvWqhKoQzWM2buHRHuYgGhZ1+hzrYtaR7WdIqxYOTviKSxj8Vk1fHip9ubNzHUnCuTEUVu8cOwPrIttM7VNERZC/ytJD5H0A5J+rJkWX64huT8LP9bnnfH4/JSbI5nZZ8BWdGtg65TRRXD1W2iKsNJj5mtoFr0ixBL4dyWNX0syKZ5U12KGiB5llKaE8e6AHiW4sM1ThBWmy9H8V2PwoVnFfsM1q3n5huae8octHE4XLx7j1L7Ai0O/zwOnCCsm6RH9V7kk0ij4pWSTrwj2mD9sn5F5+qnpVjEwJeTGzvUWJVW5TWOExWB43/Acmy7SayQ9acCDE3WetkAGKdmhraJteWItAHCkaLr30i/U87Ds7u4xwkpPXjZhSX8s6TGDZH9R0rMLpZwfCHtkX2AhZLPF0rAF562ahev6CsxpWG+U9OXX1+1FPUoPdV2Seia9z8S/CPLRwixcELbAC9V4no9nlzVM+bDek5zld2TNIDWPEXApFummZvutzp8ahJj8iKTPHrLC4mz3dUAEpgjrFZK+ecCj9taUnmDOY6c+tcAHhQbwJ5JuHzpK7FbtvYg9YXhuW8MPeK+kr3c2i3Ph7Pv+KcJK/Vj0kImLGn6kK8/3XbpCmEaz/7ikFx0JtMp9jVxhTl9cGdheqzu1NSffBIw/i+C835XEALrW3NeYgRy6+pxMqCWaUupoJ8MFpOdVweWzI81m4YM4luN3tXecIqyxQxpyIDAXMXf4YWLyM2b+sKQf37cygekfAaH85ocLsoJk4m/+t2S7R+poXxsVf7WDrbBj6Z5Ahy0UgnaUYnPpZXjToZanJ8vUwOZfJP3dUNEYgUEc/D+yRDxQ0sdJYjGA/8X30ZYgmCDF+D9/f+zgT+LeeNYXSfq0go68X9I3FPpNUkd7qflY0ITDFMkPh1iyInsYkI7e0TnCCnyYjPzUJq6W8V+SoZLJ9o6BSJ2FYblU0/gq7wlcjl/NOxjLHDL8CZLuas2lUUpYqSbD4OKH7RD8TlMKTwHHIEy1nw8M2SDQjE7l2gqN6P7Dc94+UT6tY0xjQ8v658T8g3g/KAkNKsxZ2h7mLf67JSt7aUS7Y4SWTZ90Y7j9Vcuwq10aWTD2Y05jBTWlpCwlrDGAIIsx4gl/Vis+q9rCTUk8Tmu+5oM6tsAv9VexsZzV6GsfL1vgWKPOPKNI1FkSylPj+UV11CCsogddcaE0VsvaVbmg0wmyJgtG+ZNccg6BKbLivqY4oqnGzKHa6PdoBKjQaFfp6mKjzW2iWWnYgslqX5HkB6KkrWlul4YJ67zBkr6ZrF2VYelsC2U4XaJUfuo4z/wfSfiMuZp7mZiwzhsW6YESTdn653Vr07sjXY/9fZvCXFR5fuJ5flNzp5CbsIrkOloo3b7kuKsyHNPDY79C0hvKbnOpDRB4xhC2kFbN6j3xjlxNBu2asNaPhPTt1NybaH23Nr0z9gaa4DeFuajydw+HzEThlKz+SdKXLQztKXrouYVMWOsQxPbHIfmwVt9E67q1+V2xQFGapmfzBh30AadMQQKf0YSb3Ctswlo3YlNn+5Ml/c66ag53V+y1/FNJ32eTcBf555lY0kY0H7hrwlo3ZsLZ7lCGZfiFSRh3gSOR1ZiIvuojEPtuqfmTJeG6YOUv351CGnBSISGfpi8T1nLxpClkvEF3GX55nvu4G1ORycIPb3lHuy/DldKQ0+OzbXOntr3FE35d0tOXP26fO0xYy3FPtQSHMizH75mSfmZmDyr7ODEf87RF+Fdiv+fyJ1/PHRAR/lM0Jkw8fE78rLm+RRIZhru4TFjLxOQThZbhNVWaCcc+wnMygOQpitLN9XmaoZJWl2gjqeb3j5L+Ozm6LU2HlGqOfE7vSz9/kqTPkMRvrodL+s8s9RHfRTnKfL6kTyzpUEGZ35D0TQXlmiliwlominTfYEkG0mW1H7M0ZiLkxUJGU5kBZsRBWMBnNioyQhQgvjdL+svB1H6upG9N2ttl4K4Jq3zEpTmv8LOsVcHLn3i8kmiwkb6I3qdZQEKD4TcHfOA4Jl4osoXwf8qXpDvKkY2MuJFSKP8dWlL8n2f935AcEu0Hjechkj6UVIy29AhJD5b0UEm4D2pftOG9Qy42gnBffWLlNUJKog0vkER4Q1eXCatcXGlGUac/Lsdtz5JpJto4dTtMslOO/SBByC9SaENItyV/pytwW/aRU9jR5v5X0psk/U3i3yvN2ZZnY+h2dduEVT7UGByYLN0Ku7yrhygJ4aDNsbIWn+N3LQD+azgT4D8k3TNoQ5APF+Pp7wctMSXRqXMRzmlTfqBMl9oVAJiwyoZBugeuW2GXdfUqS0FMdwwEFWbnXCqgyJILsXAmIqYdZwvg9A4neQ4WrgJiy1jhjFXOvQFNXRm0pesXrgmrbDjFGwpfR5gWZXe61CURiJOQeME8UtKDCnyNbLGKMApIJvxTXzIsBEB2YyuITPwgp/h9yb6WPosFjZcnhbuOHTRhzYvdWRnmMbpkiTDb0Jjic2hNp9oBwUBMQS5BUtwTQZf4eiC7Me0rCIr743i7S/Z77bPSuMHuF4tMWPPDwKEM8xhtWSL8THHoyZwphxaMpsRyPsv6QVJ5G6mH02GoF6LKL+phsvdGUHk/0rMyuw/FMWHNT7VwtjeZH2i++d2VgEBwhAdBnQroDK0nNelOrZxBfpAUBMXn/ELGQVBNZitYIc2Ic6Nfze8VnOufCes0Qj3tG2QSpmbOnOxb+B4ywrSLrSXpKdx5+/A1QSJhjvG75Eq1qFw7o84gqO4ncwkYvZcxYZ2WYDjbW15ZYRK+NDFrWk4mGKt1KUFNSSBW3IJQSudaHAQa/qhcQwstCoIqjWMqfbbLbYyACes0wBEd3OoBEwSz3pmtYrUW1ApJPWsg1FP+p7+W9NrEb7Rk6Ic/ihWx3NRDi0p9UUvqddnGEDBhTQskjQ5u0VmZ55bCScxWCxYJ9r5KSQoyQYvlZ2lKGeQT5l5KhGjDKUEtrXdv7Pz8EwiYsKbBCXOwtbPZvnhIy5xOUpKyQVZ7mjhhiqH1jTm0A+kgqaUmGf3FGY8WFfs4I91MGg+1JwYmm40RMGFNAxyrgy0F2uVBgGgTEMSeDmPI6fmDyTe1ogexhCZVuvoGQbFp+NlD3iec8xGykBKUNaiNSaKl6k1Y49JIg0VbSNIHERCtnMYL/bakb19hStUYf7QHv9TzhhxOU3Xi4IaoThFqRKenQaD0EzImjortMGHirclzVaO/rqMRBExY44KIU0VaiL0aO0p8r0UAyAVtCq1u6oJowC/1S6Xpe+nPVGR6uhcPLcraUyNE0UozTFjjkojo4L1X3HITkNbuYaJCMqxGjkWEB4IcJAFJRXxUON4jADRHOsgpDfpsZV64HY0iYMK6VTBoA+Qg2jsjY352HP4bCKM0YLLWkDt1hh0aKKEIvzY42tMg0Nyf5SDNWhI5cD0mrFuFH1oNK2+nTJ+thg0TnUBQ2hHXXodbpml1oi1k+XzrkMeJrJqfNWQAzfGgzbEdBB+UzbutRsyB6jVh3Srsn5b0HElfu4M2g2/n7iwsAM0E8ipdXas5fPPEb3N1x4bhOLJrrry/NwKLEDBh3QoXebmZeCWnqCwCe6YwZPX6LLUJfh7MwL20k2dIumuk3ZEDHRLl9JpXNZSwrqZMXFdjCJiw7iuQvcxBNLqfz8YGJilR63uRVTQnTxt8aR9aY1PGzdkTARPWfdGP7S6X2kA8Fl+F9oLvDHPMlxEwAgkCJqyPghHBopfaijNmArI6+cSd/FWeGEageQRMWB8VUSzfX+KQibEsC4QI8H/vhWt+2riBeyFgwrpBPj1ZZEtMxkxAnk/kOoS5t79qr3Ho5xqBIgS2nJxFDWikUBySumXs1VjIAv4qHP17bl5uRARuhhGYR8CEdYNRbMXZytk+tgpIyAJkZRNwfpy6hBH4MAImrBvSIBPCFkcgjUWtgzt+sjVJ6zxsjcChETBh3ZhjZK7cYlNxnhWUY8ofa63q0HPOnT8DAROWRGQ7V828V2POdcIl4mSbM0TmW43AcRE4OmHF5t6asVdjZEXmB8hqj/2Axx3d7vnVIWDCutm/V8N/Ffmf8Iml+xD3yrRwdYPVHTICRyesOCiV+CdOxlkaB0WoAqmCnzukWRkbUU/YIeuDR7YRuEoEjk5YCDXOHsRcI6xh7jp1Bl56755pYeb64O+NQJcImLCkF0p6ySA9SIsMCWyTSS98XRwxhR/q1BFW9wwpYuYOXuhysLjRRmBvBExYNxIYS1QX5uGpvFiRVROie52kt6wwK/ceA36+EegGgf8Hw+2M0zh8visAAAAASUVORK5CYII=' /&gt;&lt;/td&gt;\n" +
    "            &lt;/tr&gt;\n" +
    "        &lt;/table&gt;\n" +
    "    &lt;/div&gt;\n" +
    "&lt;/body&gt;\n" +
    "\n" +
    "&lt;/html&gt;";

const browserOptions = {
    'headless':true,
    'ignoreHTTPSErrors':true
};

(async () => {
    console.log('trying to init page...');

    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch(browserOptions);
    const page = await browser.newPage();

    console.log('trying to setContent...');

    await page.setContent(htmlContent, {waitUntil: 'networkidle0'});

    console.log('trying to making pdf...');

    await page.pdf({
        'path': 'C:\\Test\\test.pdf',
        'format': 'A4',
        'scale': 1,
        'margin': {
            'left':'0.39in',
            'right':'0.39in',
            'top':'0.39in',
            'bottom':'0.39in'
        },
        'printBackground': true,
        'landscape':true
    });

    console.log('trying to close browser...');

    await page.close();
    await browser.close();

})()
</pre>

**What is the expected result?**
Have a pdf file.

**What happens instead?**
It would get Stuck on "setContent" step , but if I add img#shouldBeRemoved back, it would work 
normally.

**Comment by aslushnikov** [comment]
@ZenkyuJo your script works perfectly for me with Puppeteer 1.17.0 - I think the bug has been fixed since than. Please update to a new version.
