### ISSUE TITLE
Too large write data is pending: size=725124416, max_buffer_size=268435456

### ISSUE THREAD

**Issue by vadnala** [puppeteer/puppeteer#4563]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2.0
* Platform / OS version: Windows Server 2008
* URLs (if applicable):
* Node.js version: 8.9.1

**What steps will reproduce the problem?**
When printing web pages that contains hundreds of images.
Even tried the "pipe" mode but no avail. If this is a limitation, is there a way to find the size of the write data as it is obviously printing the following statement on the console window

**[0609/223146.069:ERROR:http_connection.cc(112)] Too large write data is pending: size=725124416, max_buffer_size=268435456**

Tried **Network.dataReceived** option to read the data lengths to get to the overall size but the data size does not match. In my case, I got the data as 521 MB but the write data says 691 MB. 

Attached a picture of the **Network** tab on the devTools. It says 521 MB resources which is correctly matching my reading. However, it says **252 MB** transferred. How do I get this reading? Either way, how do I get the write data size?
<img width="529" alt="Screen Shot 2019-06-10 at 9 01 44 AM" src="https://user-images.githubusercontent.com/3056474/59198349-86bafa00-8b61-11e9-9969-fea6e705ebaf.png">

**What is the expected result?**
Successfully generate the PDF irrespective of the size of the write data. Else, way to know the size of the write data so that we can document the known limitations.

**What happens instead?**
Fails to generate the PDF when the page contains of hundreds of images. In other words, when the write data is too large.

**Comment by aslushnikov** [comment]
@vadnala You're hitting the limit on Chrome DevTools WebSocket: https://cs.chromium.org/chromium/src/content/browser/devtools/devtools_http_handler.cc?sq=package:chromium&g=0&l=83-84 

In other words, DevTools protocol messages are limited to 256Mb in DevTools->Clients direction.

The limit will go away once we teach Chromium to return PDFs as streams: https://crbug.com/748956

**Comment by vadnala** [comment]
@aslushnikov Thanks for the reply and pointers. For time being (workaround), I am looking for an answer to either of these three 

1. Is there a way to find the size of the write data so that I can split the prints accordingly.

2. I was able to get the resources size capturing the "dataLength" from **Network.dataReceived** but how do I capture the **data transferred** so that I can sum up to get the size of the write data

3. Is there a way to capture the below error message

**[0609/223146.069:ERROR:http_connection.cc(112)] Too large write data is pending: size=725124416, max_buffer_size=268435456**

**Comment by aslushnikov** [comment]
@vadnala the fix is already landing in chromium: https://chromium-review.googlesource.com/c/chromium/src/+/1652155

We'll have it in Puppeteer shortly (in a few days) and it will be available right away on npm as `puppeteer@next`.

**Comment by vadnala** [comment]
@aslushnikov That's great news and many thanks for the update.

We have a customer issue and thus looking for a quick workaround.
Any option to get the size of the "write data" one or the other way?
Thanks in advance.

**Comment by aslushnikov** [comment]
> Any option to get the size of the "write data" one or the other way?
Thanks in advance.

Unfortunately I can't think of any good way to handle this. The best you can rely upon is parsing the `stdout`/`stderr` of the chrome process itself.

**Comment by vadnala** [comment]
Any sample/example on how we can parse/capture "chrome" stdout / stderr from puppeteer? TIA
