### ISSUE TITLE
Can I inject script after body tag use addScriptTag function

### ISSUE THREAD

**Issue by microwin168** [puppeteer/puppeteer#4564]
When I inject a script use addScriptTag function. It injected between head tag.
In my project I want inject a script file after  close body tag. How can I do?

**Comment by aslushnikov** [comment]
> In my project I want inject a script file after close body tag. How can I do?

@microwin168 you'll have to resort to manual `page.evaluate` call:

```js
const scriptToInject = `console.log("yo");`;
await page.evaluate(scriptText => {
  const el = document.createElement('script');
  el.type = 'text/javascript';
  el.textContent = scriptText;
  document.body.parentElement.appendChild(el);
}, scriptToInject);
```
