### ISSUE TITLE
Multiple tabs generating PDF crashing the chrome

### ISSUE THREAD

**Issue by mayank** [puppeteer/puppeteer#4565]
If I open 10 tabs simultaneously in same browser and try to create pdf, chrome closes instantly.

### Steps to reproduce
1. Create instance of chrome
```javascript
let browser = await chrome.launch({
                headless: true,
                args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-translate',
                '--disable-extensions',
                '--disable-sync',             
            ],
            defaultViewport: {
                width: 1024,
                height: 768,
            }
});
```
2. Launch multiple instances of chrome to generate PDF.
```javascript
let promises = [];
for(let i=0;i<10;i++) {
    await browser.newPage();
    await browser.setContent('<html><body><h1>Hello World</h1></body></html>');
    await browser.pdf();
}
await Promises.all(promises);
```

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: MacOS Mojave
* URLs (if applicable):
* Node.js version: 10.x

**What happens instead?**
Crashes giving `TargetClosed` Error.

**Comment by aslushnikov** [comment]
@mayank Looks like you're running out of memory on your host machine - and browsers crash. Running less PDF generation jobs in parallel should help.
