### ISSUE TITLE
A3 paper size is incorrect

### ISSUE THREAD

**Issue by swordman1205** [puppeteer/puppeteer#4568]
I was trying to generate PDF using this library. However, I noticed the size of A3 format is incorrect. The correct size should be **297mm** x **420mm**, but the generated PDF size is **297mm** x **419mm**.

### Steps to reproduce
Call `pdf` function with param `{ format: 'A3' }`.

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Mac OS High Sierra / Linux
* URLs (if applicable): 
* Node.js version: 10.x

**What is the expected result?**
The A3 format size should be **297mm** x **420mm**.

**Comment by swordman1205** [comment]
![Screen Shot 2019-06-11 at 4 04 41 AM](https://user-images.githubusercontent.com/15131704/59238363-1dd58f80-8bfe-11e9-97f6-e77dbd7dc962.png)

**Comment by swordman1205** [comment]
So @sapics @aslushnikov can you please release a new version for this update so that I can integrate this change?

**Comment by aslushnikov** [comment]
@swordman1205 there's a `puppeteer@next` for the tip-of-tree version of puppeteer:

```js
npm i puppeteer@next
```

Our next release is scheduled for June, 21. Will the `puppeteer@next` work for you in the meantime?
