### ISSUE TITLE
highlight text/element selection and visually response to selection API when double clicked

### ISSUE THREAD

**Issue by futurist** [puppeteer/puppeteer#4570]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `1.17.0`
* Platform / OS version: `macOS 10.14.4`
* URLs (if applicable): `http://bennadel.github.io/JavaScript-Demos/demos/selection-range-rects/`
* Node.js version: `12.4.0`

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
// simulate dblclick on text
async function init () {
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null
  })
  const page = (await browser.pages())[0]
  await page.goto('http://bennadel.github.io/JavaScript-Demos/demos/selection-range-rects/')
  await page.mouse.move(573, 199)
  await page.waitFor(50)
  // simulate dblclick
  await page.mouse.down()
  await page.waitFor(50)
  await page.mouse.up()
  await page.waitFor(50)
  await page.mouse.down()
  await page.waitFor(50)
  await page.mouse.up()
  await page.waitFor(50)
}
init()
```

**What is the expected result?**
Should like normal browser, double click on text should highlight the word.

**What happens instead?**
No selection highlight happened on word, and the text selection is collapsed.

**Comment by futurist** [comment]
I've monitored the page again, and find the above `double click` way actually only triggered 2 `click` events, no `dblclick`, is this intentional or a bug?

**Comment by Meir017** [comment]
@futurist this might be helpful - this is how they implement the dblclick https://github.com/microsoft/playwright/blob/v0.11.1/src/input.ts#L248
