### ISSUE TITLE
Use Puppeteer with Ungoogled Chromium + How to debug not working dev tool connect

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4572]
I'm trying to use puppeteer with this specific version of chrome https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/65.0.3325.181-1

It launches but it doesn't do anything or print anything, it just stalls after opening. How can I debug what's not working in that version of chrome? I'm on centos 7

Here's the code i'm using:

```
const puppeteer = require('puppeteer')

async function helloWorld() {
  const args = [
    '--no-sandbox'
  ]

  const browser = await puppeteer.launch({
    headless: false, 
    executablePath: `/headless/Desktop/chrome/chrome`, 
    args})
  const page = await browser.newPage()

  await page.goto('https://en.wikipedia.org/wiki/%22Hello,_World!%22_program')

  const firstPar = await page.$eval('#mw-content-text p', el => el.innerText)

  console.log(firstPar) // A "Hello, World!" program is a computer program that outputs ...

  await browser.close()
}

helloWorld()
```

**Comment by aslushnikov** [comment]
>  How can I debug what's not working in that version of chrome? I'm on centos 7

@dave-dm you can run your Puppeteer script with `DEBUG=*` env variable.

```bash
$ DEBUG=* node script.js
```

> I'm trying to use puppeteer with this specific version of chrome https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/65.0.3325.181-1

This might be if you use [incompatible Puppeteer version](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy). For Chrome 65 it would be v1.0.0.
