### ISSUE TITLE
Puppeteer how to save/set download path when download starts from different tab not the current one

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4573]
Hello
In my code i am trying to download file. When puppeteer clicks on a tag it triggers download but also opens new tab for 2-3sec where this download is held (i think). SO i thinkl i need to set download behaviour to that tab but problme is it flashes and browers.pages() also did not catch it. SO how can i set different folder for this download?
**Tell us about your environment:**

* Puppeteer version: 1,17.0
* Platform / OS version: Windows 10
* URLs (if applicable): no
* Node.js version: Fresh instalation

****What steps will reproduce the problem?****

`   const client = await page.target().createCDPSession();
  await client.send("Page.setDownloadBehavior", {
    behavior: "allow",
    downloadPath: path.resolve(__dirname, "reports/asd")
  });`
  

**_Please include code that reproduces the issue._**

```
async function main() {
      const browser = await puppeteer.launch({ headless: false });
      const page = await browser.newPage();
      await page.setViewport({ width: 1366, height: 800 });
      await page.goto(endpoint, { waitUntil: "networkidle2", timeout: 0 });
      await page.waitFor(3000);

      await page.type("#username", login);
      await page.type("#password", pass);
      // click and wait for navigation

      await page.click("#login"),
        await page.waitForNavigation({ waitUntil: "networkidle2" });
      await page.waitFor(2000);

       const client = await page.target().createCDPSession();
  await client.send("Page.setDownloadBehavior", {
    behavior: "allow",
    downloadPath: path.resolve(__dirname, "reports/asd")
  });

      await page.waitForXPath('//*[@id="ctl00_ctl00_masterMain_cphMain_repViewable_ctl01_thisItemLink"]');

      const [setting] = await page.$x('//*[@id="ctl00_ctl00_masterMain_cphMain_repViewable_ctl01_thisItemLink"]');
      if (setting) setting.click();

      await page.waitFor(3000);

      let pages = await browser.pages();

      await page.waitFor(2000);

      await pages[2].waitForXPath('/html/body/table/tbody/tr[17]/td[6]/a');
      const [newVID] = await pages[2].$x('/html/body/table/tbody/tr[17]/td[6]/a');
      if (newVID) newVID.click();

     await pages[2].waitFor(3000)

     await pages[2].close()

     await pages[2].waitFor(5000)

     await pages[2].waitForXPath('//*[@id="freeze"]/table/tbody/tr[2]/td/table/tbody/tr[3]/td/a');
     const [neww] = await pages[2].$x('//*[@id="freeze"]/table/tbody/tr[2]/td/table/tbody/tr[3]/td/a');
     if (neww) neww.click();

    await pages[2].waitFor(4000)

    await pages[2].waitFor(4000)

    await pages[2].waitForXPath('/html/body/div/table/tbody/tr[3]/td/a');
    const [fin] = await pages[2].$x('/html/body/div/table/tbody/tr[3]/td/a');
    if (fin) fin.click();

    }

    main() 
```

**What is the expected result?**

to download file to folder set in code not to default downloads

**What happens instead?**

file is save to downloads

**Comment by derekyle** [comment]
I wasn't able to figure out a way to set a default downloads folder (why this isn't a setting on the browser object is beyond me). So what I did was use page.exposeFunction() to override the window.open function on the page that will try to open the new tab. Then in the callback, I used page.goto() to go to the download URL within the same tab instead of opening a new one. It had to be enclosed in a try/catch because it throws ERR_ABORTED when the file being browsed to is a download.

```
await page.exposeFunction('open', async (open) => {
            console.log(open);
            try {
                await page.goto('https://www.myURL.com' + open);
            } catch (err) {
                console.log(err);
            } finally {
                console.log('done')
            }
        });
```

**Comment by 410Gone** [comment]
Hi, same proble here. unable to specify the download directory using :

```
            const gotElementLink = await page.$x(elementPdfDl)
            let urlFile = await page.evaluate(el => el.textContent, gotElementLink[0]);
            console.log(urlFile);

            (async () => {


                page.on('request', req => {
                    if (req.url() === urlFile) {
                        const file = fs.createWriteStream('./file.pdf');
                        https.get(req.url(), response => response.pipe(file));
                    }
                });
                await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: 'E:/projets/factures/'});
                await page.goto(urlFile);
            })();
```
If i comment the line : 
`await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: 'E:/projets/factures/'});`
i got this error but the file correctly download (in the defaut download directory)

> (node:42860) UnhandledPromiseRejectionWarning: ReferenceError: https is not defined

(if i do not specify the s in http i've an other error ...)
and this second error (but i download successfully

> UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:42860) UnhandledPromiseRejectionWarning: Error: net::ERR_ABORTED at https://www.ovh.com/cgi-bin/order/bill.pdf

**Comment by Fritzsierra** [comment]
Using Puppeteer Extra you can configure the folder where you want to download:

`const puppeteer = require("puppeteer-extra");

var dir = process.cwd ()
puppeteer.use(require('puppeteer-extra-plugin-user-preferences')
(
{userPrefs: {
    download: {
      prompt_for_download: false,
      open_pdf_in_system_reader: true,
      default_directory:dir,
   },
   plugins: {
     always_open_pdf_externally: true
   },
 }}));`

**Comment by openspaceranger** [comment]
It doesn't look like that this issue was actually resolved.

**Comment by Lovely-Ruby** [comment]
but this issue is not resolved...
