### ISSUE TITLE
login into gmail fails for some unknown reason 

### ISSUE THREAD

**Issue by Hretic** [puppeteer/puppeteer#4577]
im trying to login into my gmail with puppeteer 

here is my code

```

        await page.goto('https://accounts.google.com/AccountChooser?service=mail&amp;continue=https://mail.google.com/mail/', {timeout: 60000})
            .catch(function (error) {
                throw new Error('TimeoutBrows');
            });

        await page.waitForSelector('#identifierId' , { visible: true });
        await page.type('#identifierId' , 'myemail');
        await Promise.all([
            page.click('#identifierNext') ,
            page.waitForSelector('.whsOnd' , { visible: true })
        ])
        await page.type('#password .whsOnd' ,  "mypassword");
        await page.click('#passwordNext');
        await  page.waitFor(5000);

```
but i always end up with this message in the picture below 

https://i.stack.imgur.com/txZzA.png
 

i even tried to just open the login window with puppeteer and fill the login form manually myself ... but even that failed 

am i missing something ? 

when i look into console there is failed ajax request fired just after login  

```
    Request URL: https://accounts.google.com/_/signin/challenge?hl=en&TL=APDPHBCG5lPol53JDSKUY2mO1RzSwOE3ZgC39xH0VCaq_WHrJXHS6LHyTJklSkxd&_reqid=464883&rt=j
    Request Method: POST
    Status Code: 401 
    Remote Address: 216.58.213.13:443
    Referrer Policy: no-referrer-when-downgrade
    

    )]}'
    
    [[["er",null,null,null,null,401,null,null,null,16]
    ,["e",2,null,null,81]
    ]]

**Comment by ryo-hisano** [comment]
Hi! @Hretic .

Well,
```page.waitForSelector('.whsOnd' , { visible: true })```
As for '.whsOnd' exists in two places,
```page.waitForSelector('#password .whsOnd', { visible: true })```
Should be

Also why
```await page.click('#passwordNext');```
If the problem does not work, there is a similar problem below,

Page.click() does not work with an input selector · Issue #3347 · GoogleChrome/puppeteer
https://github.com/GoogleChrome/puppeteer/issues/3347

```javascript
await page.evaluate(() => {
    document.querySelector('#passwordNext').click();
});
```

Do you like

```javascript
await page.waitFor(5000);
await page.click('#passwordNext');
```

It seems to work well by doing like.
Please give it a try.
