### ISSUE TITLE
Cannot connect to existing Chrome Page

### ISSUE THREAD

**Issue by LarryEitel** [puppeteer/puppeteer#4579]
When trying to connect to a Chrome (Version 75.0.3770.80 (Official Build) (64-bit)) Page using the following. I get:
`Error: Protocol error (Target.getBrowserContexts): Not allowed
    at Promise `

```
const puppeteer = require('puppeteer-core');

(async () => {
  const browserWSEndpoint = 'ws://127.0.0.1:9222/devtools/page/500056D65CF0AEE17C01DF068E34B21E';

  try {
    const browser = await puppeteer.connect({browserWSEndpoint, ignoreHTTPSErrors: true});
  } catch (error) {
    console.error(error);
  }
  console.log('hello')
})();
```

Thank You

**Comment by mannharleen** [comment]
Getting the same error. Any ideas?

**Comment by aslushnikov** [comment]
Puppeteer can connect only to a browser target - so yes, this won't work.
I'd recomment connecting to browser target and then fetching proper page via `browser.pages()`.

**Comment by dheerajbhaskar** [comment]
For anyone else who encounters this, you need to go to the following url to get the browserWSEndpoint:

```
http://127.0.0.1:<debugging port>/json/version
```

**Comment by DanStos** [comment]
@dheerajbhaskar Thank you so much! I was cracking my head down trying to understand what was wrong!

**Comment by one10** [comment]
It seems like this has changed in some point in history because I have some code based on Puppeteer 1.4.0 where you can connect to a page just fine. Breaks for me after upgrading to anything after 1.10.0. Just saying. If you're struggling with an older code base, this may be why.
