### ISSUE TITLE
page.click not working

### ISSUE THREAD

**Issue by elpupi** [puppeteer/puppeteer#4583]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: v11.10.0

wait page.click('#link') works most of the time. But for some mysterious reason, sometimes it is not. The worst is that the program is doing exactly the same, but just on a different page with the exactly same layout.

But await page.$eval('#link', elem => elem.click()); works really well.

```
  await page.hover('#link');
  page.click(''#link'); // --> not always working
  page.$eval('#link', elem => elem.click()); // --> always works
```

**What is the expected result?**
`page.click(''#link')` and `page.$eval('#link', elem => elem.click())` should work the same way.

It is hard for me to give you a code reproducing the issue because it is happening on an online web service needing credentials to log in.

**Comment by vigneshveeran-ad** [comment]
I am facing the same issue :( dont understand why. i had to use waitforSelector with a click after. `page.$eval(cssQuery('action', 'someting'), el => el.click()); `

**Comment by neptot** [comment]
same issue happened to me, still not working after all suggestion.
however,it worked when running in node debug mode
node --inspect index.js

don't know why,but hope it helps to fix this issue.

**Comment by mrhaha80** [comment]
I have the same issue. still cannot find the solution :"(

**Comment by mrhaha80** [comment]
Not sure my issue is same with yours. but just share with you.
my steps:
1. Login (await page.click('#loginButton'))
2. Enter Username to perform a search (#txt_UserName)

but the step 1 not always working. and i use the code below seem like it working.

`await page.click('#loginButton')
    try {
      await page.waitForSelector("#txt_UserName" , {
        timeout: 1000
      })      
    } catch (err) {
        await page.click('#loginButton')
    }`

**Comment by gumuruhsspj** [comment]
> ### Steps to reproduce
> **Tell us about your environment:**
> 
> * Puppeteer version: 1.17.0
> * Platform / OS version: Ubuntu 18.04
> * URLs (if applicable):
> * Node.js version: v11.10.0
> 
> wait page.click('#link') works most of the time. But for some mysterious reason, sometimes it is not. The worst is that the program is doing exactly the same, but just on a different page with the exactly same layout.
> 
> But await page.$eval('#link', elem => elem.click()); works really well.
> 
> ```
>   await page.hover('#link');
>   page.click(''#link'); // --> not always working
>   page.$eval('#link', elem => elem.click()); // --> always works
> ```
> 
> **What is the expected result?**
> `page.click(''#link')` and `page.$eval('#link', elem => elem.click())` should work the same way.
> 
> It is hard for me to give you a code reproducing the issue because it is happening on an online web service needing credentials to log in.

seems weird for me. but that's true... why is that happening? is that because of the cached of the browser still same / puppeteer main issue?

**Comment by syamdanda** [comment]
Facing same issue, and the mentioned solution was working fine.  Why is this happening?

**Comment by NiekBeijloos** [comment]
Still occurring, I experienced this on a Ubuntu 20.04.2 LTS, not within Windows 10. 'Work-around' helped for me as well.

**Comment by ctq123** [comment]
i ran into the same thing...

**Comment by ctq123** [comment]
i was facing the same thing...
but throw  Error: Node is either not visible or not an HTMLElement

**Comment by framerate** [comment]
>   page.click(''#link'); // --> not always working
  page.$eval('#link', elem => elem.click()); // --> always works
  
  I'm seeing this, too...
  
  To add: spamming page.click works, so seems like a race condition?
