### ISSUE TITLE
not triggering OPTIONS http requests 

### ISSUE THREAD

**Issue by musikele** [puppeteer/puppeteer#4589]
It seems that with Puppeteer 1.17 puppeteer (or google chrome) is not triggering OPTIONS http requests. 

I accidentally discovered on a company's project that I cannot show here, so I wrote this little script that will navigate to a page where it's 100% sure I will get an OPTIONS call to paypal logger api (you can check by navigating with a regular browser this address: http://binario1.coworkingsa.it/coworkingApp-client/ )

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Ubuntu 19.04
* URLs (if applicable): 
* Node.js version: v11.10.0 

**What steps will reproduce the problem?**

launch this script: 

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.on('request', req => {
        if (req.method() === 'OPTIONS') {
            console.log(`${req.method()} - ${req.url()}`);
        }
    });
    await page.goto('http://binario1.coworkingsa.it/coworkingApp-client/');
    //await page.waitFor(10000);
    await browser.close();
})();
```

it should log an OPTIONS call to paypal api logger. 

**What is the expected result?**

I expect to log this:
```
OPTIONS - https://www.paypal.com/xoplatform/logger/api/logger
```

**What happens instead?**
no console.log is shown.

**Comment by aslushnikov** [comment]
@musikele If I open this website on Chrome Canary, than I don't see the OPTIONS request in the network panel.

I can confirm that we do report OPTIONS requests over the devtools protocol - option requests I generate [on this site](https://www.test-cors.org/#?client_method=OPTIONS&client_credentials=false&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) are shown in DevTools on Chrome Canary.

So I suspect this website is doing something fancy and doesn't always send the request. If there's a better repro, I'd be happy to look into it; i'll speculatively close this now.
