### ISSUE TITLE
Failed to connecto to chrome!

### ISSUE THREAD

**Issue by dhurba87** [puppeteer/puppeteer#459]
Got the following error when I tried to launch browser using command ` const browser = await puppeteer.launch();`
```
Error: Failed to connect to chrome!
    at Function.launch (/root/chrome-headless-async-screenshot/node_modules/puppeteer/lib/Launcher.js:96:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by aslushnikov** [comment]
Are you on Debian? Check out [Troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md) for possible solutions.

**Comment by dhurba87** [comment]
@aslushnikov 
`const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});` fixed the problem. Thanks :+1:
