### ISSUE TITLE
Globals in puppeteer jest custom test environment loses context in test 

### ISSUE THREAD

**Issue by Galileo1** [puppeteer/puppeteer#4592]
I'm writing a npm module to reduce the boiler code in my test project and this module will be added as a dev dependency in the test project. I'm using prototype inheritance to extend an existing class(Page) of puppeteer library as well in this npm module.

> GLOBALSETUP in npm module

`const browser = await puppeteer.launch(await puppeteer.launch({some config});`

> CUSTOM TEST ENVIRONMENT in npm module

```
this.global __BROWSER__ = await puppeteer.connect({
        browserWSEndpoint: wsEndpoint,
});
```

> Extended PAGE class in npm module

```
const Page = require('puppeteer/lib/Page').Page;

Page.prototype.sendText = async (selector, text) => {
    let element = await this.waitForSelector(selector, {visible : true});
    await element.type(text);
}
```
When I create a global browser in custom test environment and use it to create page instance in the test. The Page class loses reference to all properties I have added to it using prototypal inheritance. And it throws error **_page.sendText is not a function_**

> Test in test project after locally installing the npm module

```
describe('awesome test', () => {
    it('something will be ok', async () => {
      const context = global.__BROWSER__.defaultBrowserContext();
      page = await context.newPage(); 
      await page.goto('https://google.com/')
      await page.sendText('#search', "puppeteer")
      await page.screenshot({path: 'google.png', fullPage: true})
    })
});
```

But when I create the browser instance in the test. I am able to use the properties I have added to Page class.

```
describe('awesome test', () => {
    it('something will be ok', async () => {
      const browser= await puppeteer.launch({});
      const context = await browser.defaultBrowserContext();
      const page = await context.newPage(); 
      await page.goto('https://google.com/')
      await page.sendText('#search', "puppeteer")
      await page.screenshot({path: 'google.png', fullPage: true})
    })
});
```

Not sure what's happening here?

**Comment by aslushnikov** [comment]
@Galileo1 from Puppeteer standpoint, you do everything correctly.

The issue seems to do coming from Jest's environment. Unfortunately, we're not Jest experts here - I'd recommend filing this issue to Jest's repository.
