### ISSUE TITLE
in docker v1.17.0 hang

### ISSUE THREAD

**Issue by fengqilin** [puppeteer/puppeteer#4596]
I try many version ,start v1.10.0, in docker , the method browser.newPage() will wait ,do not go to next  ,this code will not print 2222
(async () => {
  const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
  console.log(11111)
  const page = await browser.newPage();
   console.log(2222)
  await page.goto('https://example.com');
  console.log(33333)
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();

**Comment by aslushnikov** [comment]
Not sure what this might be - and there's not enough information to debug.

One docker container that works for sure is this: https://github.com/GoogleChrome/puppeteer/blob/master/.ci/node8/Dockerfile.linux

We use it daily to run all puppeteer tests. Please try it out.
