### ISSUE TITLE
Application Error when Clicking or Sending [Enter] to Link

### ISSUE THREAD

**Issue by StephanusRex** [puppeteer/puppeteer#4597]
**Third party software:** Cornerstone On-Demand (CSOD)
**Task:** Log in, do a people search, select person, click "Feedback" link, click "Give a badge" 'button', select button from carousel, then click the [Post] 'button' (which is actually an anchor tag [see below]):

`<a role="button" ct="Button" rel="tooltip" title="Post" aria-label="Please Select Post" data-toggle="cso-button" id="____bq" class="cso-btn cso-btn cso-action cso-corner cso-btn-primary     " href="javascript:void(0)" data-ctl-options="{&quot;actiontype&quot;:&quot;ACTION&quot;,&quot;value&quot;:&quot;Click&quot;}" style="display: inline-block;">Post</a>`

Everything works great until it is time to click this link. Regardless of whether I use `.click()` or send an [Enter] key via `page.keyboard.press('Enter')`, the application (CSOD) pops up an application error (which I did not include it because it's (a) very generic and (b) specific to this third-party and would therefore provide no additional helpful context).

While I do not expect anyone to know the inner workings of CSOD to explain this behavior, I am asking if anyone has ran into similar situations with other applications. It's a long-shot, but I'm stumped and there's clearly something regarding the way Puppeteer interacts with the browser that's causing this.

I'm fairly certain of this because if I issue, say, `document.querySelector('#____bq').click()` in the Chromium debugger, the action successfully executes and the badge is created. Therefore, why would this work but not the two methods I've tried with Puppeteer?

Finally, is there an alternate method I could use, e.g., could I perhaps execute something directly on the DOM and bypass Puppeteer altogether at this step, i.e., could I pass a JQuery or JavaScript script and have it run instead?

Thanks in advance.

**Comment by aslushnikov** [comment]
> Therefore, why would this work but not the two methods I've tried with Puppeteer?

@StephanusRex These are very different things to the `document.querySelector('#____bq').click()` you used. Take a look on [this slide](https://docs.google.com/presentation/d/1jxk151ub6NpTUbwT71hK53CoPnOSa7Me7Y6ULik4Xbg/edit?pli=1#slide=id.g576644694b_1_325) from one of the talks we gave on Puppeteer:

![image](https://user-images.githubusercontent.com/746130/59908062-5ecd6100-93c1-11e9-9cfa-053414449ebc.png)

So Puppeteer's input emulation is exactly the same as real-used input. Whereas triggering input using WebAPI's is very limited.

it's hard to say why `page.click` or `page.keyboard` didn't work for you - this might be a bug.  I'm very interested to debug these locally if there's any way I can reproduce it locally - please let me know! 

> Finally, is there an alternate method I could use, e.g., could I perhaps execute something directly on the DOM and bypass Puppeteer altogether at this step, i.e., could I pass a JQuery or JavaScript script and have it run instead?

You can use [`page.evaluate`](https://pptr.dev/#?product=Puppeteer&version=v1.18.0&show=api-pageevaluatepagefunction-args) to do things inside the page:

```js
await page.evaluate(() => {
  document.querySelector('#____bq').click();
});
```

**Comment by hrina** [comment]
I am facing the same issue with the hyperlink  `href="javascript:void(0)"` . I tried using the page.$eval too. It is able to get  the textContent correctly  but when it clicks the page is not redirected but just does a refresh.

**Comment by bayaza** [comment]
Please I need a solution and it is display the page according to the choice of categories from button next


<section id="main" class="clearfix ad-post-page">
		<div class="container">

			<div class="breadcrumb-section">
				
				<ol class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li>Ad Post</li>
				</ol>						
				<h2 class="title">Post Free Ad</h2>
			</div>

				
				
			<div id="ad-post">
				<div class="row category-tab">	
					<div class="col-lg-4 col-md-6">
						<div class="section cat-option select-category post-option">
							<h4>Select a subcategory</h4>
							<ul role="tablist" class="nav nav-tabs">
								<li><a href="#cat1" aria-controls="cat1" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/1.png" alt="Images" class="img-">
									</span>
									Cars & Vehicles
								</a></li>

								<li class="active link-active"><a href="#cat2" aria-controls="cat2" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/2.png" alt="Images" class="img-fluid">
									</span>
									Electronics & Gedgets
								</a></li>
								
								<li><a href="#cat3" aria-controls="cat3" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/3.png" alt="Images" class="img-fluid">
									</span>
									Real Estate
								</a></li>
								
								<li><a href="#cat4" aria-controls="cat4" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/4.png" alt="Images" class="img-fluid">
									</span>
									Sports & responsive
								</a></li>
								
								<li><a href="#cat5" aria-controls="cat5" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/5.png" alt="Images" class="img-fluid">
									</span>
									Fshion & Beauty
								</a></li>
								
								<li><a href="#cat6" aria-controls="cat6" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/6.png" alt="Images" class="img-fluid">
									</span>
									Pets & Animals
								</a></li>
								
								<li><a href="#cat7" aria-controls="cat7" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/7.png" alt="Images" class="img-fluid">
									</span>
									Job Openings
								</a></li>
								
								<li><a href="#cat8" aria-controls="cat8" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/9.png" alt="Images" class="img-fluid">
									</span>
									Home Appliances
								</a></li>
								
								<li><a href="#cat9" aria-controls="cat9" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/10.png" alt="Images" class="img-fluid">
									</span>
									Matrimony Services
								</a></li>
								
								<li><a href="#cat10" aria-controls="home10" role="tab" data-toggle="tab">
									<span class="select">
										<img src="images/icon/11.png" alt="Images" class="img-fluid">
									</span>
									
									Books & Magazines
								</a></li>
							</ul>
						</div>
					</div>
					
					
					<div class="col-lg-4 col-md-6">
						<div class="section tab-content subcategory post-option">
							<h4>Select a subcategory</h4>
							<div role="tabpanel" class="tab-pane" id="cat1">
								<ul>
									<li><a href="javascript:void(0)">Cars & Buses</a></li>
									<li><a href="javascript:void(0)">Motorbikes & Scooters</a></li>
									<li><a href="javascript:void(0)">Bicycles and Three Wheelers</a></li>
									<li><a href="javascript:void(0)">Three Wheelers</a></li>
									<li><a href="javascript:void(0)">Trucks, Vans & Buses</a></li>
									<li><a href="javascript:void(0)">Tractors & Heavy-Duty</a></li>
									<li><a href="javascript:void(0)">Auto Parts & Accessories</a></li>
								</ul>	
							</div>
							<div role="tabpanel" class="tab-pane active show" id="cat2">
								<ul>
									<li><a href="javascript:void(0)">Laptop & Computer</a></li>
									<li><a href="javascript:void(0)">Mobile Phones</a></li>
									<li><a href="javascript:void(0)">Phablet & Tablets</a></li>
									<li><a href="javascript:void(0)">Audio & MP</a></li>
									<li><a href="javascript:void(0)">Accessories</a></li>
									<li><a href="javascript:void(0)">Cameras</a></li>
									<li><a href="javascript:void(0)">Mobile Accessories</a></li>
									<li><a href="javascript:void(0)">TV & Video</a></li>
									<li><a href="javascript:void(0)">Other Electronics</a></li>
									<li><a href="javascript:void(0)">TV & Video Accessories</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat3">
								<ul>
									<li><a href="javascript:void(0)">Houses & Plots</a></li>
									<li><a href="javascript:void(0)">Lands & property</a></li>
									<li><a href="javascript:void(0)">Plots & Lands</a></li>
									<li><a href="javascript:void(0)">Apartment</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat4">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat5">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat6">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat7">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat8">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat9">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat10">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
							<div role="tabpanel" class="tab-pane" id="cat11">
								<ul>
									<li><a href="javascript:void(0)">Sub Category Item</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="section next-stap post-option">
							<h2>Post an Ad in just <span>30 seconds</span></h2>
							<p>Please DO NOT post multiple ads for the same items or service. All duplicate, spam and wrongly categorized ads will be deleted.</p>
							<div id="my-buttons">
								<button class="select-tab">Next</button>
								<button class="select-tab">Previous</button>
								</div>
						</div>
					</div
