### ISSUE TITLE
Cannot set "content-length" header when modifying intercepted request

### ISSUE THREAD

**Issue by jason-medeiros** [puppeteer/puppeteer#4599]
edit: Looks like content-length is set automatically and can't be overridden when setting post data.

Hi, I'm using puppeteer to control chromium, and noticed that I can set custom headers mostly fine.  I can set "content-type" header without issue, I can set "arbitraryvaluehere" header without any issues, however, when I try to set the "content-length" header, puppeteer responds with:

Error: net::ERR_INVALID_ARGUMENT at http://127.0.0.1/test/?fudge=blah
    at navigate (/code_path_here/node_modules/puppeteer/lib/FrameManager.js:121:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/code_path_here/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.goto (/code_path_here/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/code_path_here/node_modules/puppeteer/lib/helper.js:111:23)
    at PuppeteerClient.sendDataToPage (/code_path_here/PuppeteerClient.class.js:900:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

The request callback I'm using is as follows, again, everything works perfectly without any issue **EXCEPT** if I set the content-length header:
`

        // override request handler to post data directly
        new_page.on('request', function(request)
        {

            if(new_page.isClosed() === true)
                return;

            // inner async function so we can use await pattern
            var inner_async = async function(request)
            {
                
                // never load images or fonts
                if(['image', 'font'].indexOf(request.resourceType()) !== -1)
                {
                    request.abort();
                    return;
                }

                // attempt to decode
                var decoded = decodeURIComponent(request.url());

                // process post override
                const overrides = {};

                // process url matching
                if (request.url() === url_to_navigate_to || decoded === url_to_navigate_to) 
                if(request.isNavigationRequest() === true)
                {

                    if(data_has_been_posted === false)
                    {

                        // set data marker
                        data_has_been_posted = true;

                        // gather headers
                        var request_headers = request.headers();

                        // set custom headers if we have any
                        if(custom_utils.isEmpty(custom_headers) === false)
                        {

                            // add headers
                            headers = Object.assign({}, request_headers, custom_headers);

                        }

                        // set post method if required
                        if(request_method === "POST")
                        {

                            post_data_string = "checkbox_test=on&inject2=inject2";
                            overrides.method = 'POST';
                            overrides.postData = post_data_string;

                            
                            // override headers
                            if(headers !== null)
                            {
                                headers['Content-Type'] = "application/x-www-form-urlencode";
                                headers['Content-Length'] = post_data_string.length.toString();
                                overrides.headers = headers;
                            }
                            else
                            {
                                headers = {};
                                headers['Content-Type'] = "application/x-www-form-urlencode";
                                headers['Content-Length'] = post_data_string.length.toString();
                                overrides.headers = headers;
                            }

                            await request.continue(overrides);
                            return;
                        }

                        // set any other method type
                        if(custom_utils.isEmpty(request_method) === false)
                        {
                            overrides.method = request_method;
                            if(custom_utils.isEmpty(post_data_string) === false)
                                overrides.postData = post_data_string;

                            // override headers
                            if(headers !== null)
                                overrides.headers = headers;

                            await request.continue(overrides);
                            return;
                        }

                        await request.continue();
                        return;
                    }

                }

                // standard continue
                request.continue();
                
            }

            // run inner async function
            inner_async(request).then(function(){});

        });

`

**Comment by automousSpace** [comment]
Facing same error, How to fix?
