### ISSUE TITLE
Metatags do not display correct after render

### ISSUE THREAD

**Issue by Make-o-Rama** [puppeteer/puppeteer#4600]
Hi there,

I have the following scenario:
My angular based Webapp does work quite nice with puppeteer. If you call the URL in a browser you can see the meta tags incl. title, og-tags etc.  

If you share a deeplink in e. g. Discord or somewhere else, i can only see the default/fallback metadata. 

I don‘t understand how this is possible or what i‘m doing wrong. 

Hopefully you can help me with this. 

With best wishes
Nathalie

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.8.0
* Platform / OS version: Linux
* URLs (if applicable): https://makeorama.de/products/colorfabb_pla
* Node.js version: 9.10

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
The open graph tags should be displayed correctly in the Page header.

**What happens instead?**
The tags are set correctly but will not affect if you share the link. (See below)

**Comment by aslushnikov** [comment]
> My angular based Webapp does work quite nice with puppeteer. If you call the URL in a browser you can see the meta tags incl. title, og-tags etc.

@Evil-Me What do you mean by "works quite nice with puppeteer"? Do you mean you run tests with puppeteer to make sure these tags are there?

> If you share a deeplink in e. g. Discord or somewhere else, i can only see the default/fallback metadata.

I'm not sure I understand how this and the previous setups are related. Is there anything I can look at / debug locally so that I understand what's going on?

**Comment by Make-o-Rama** [comment]
Hi @aslushnikov,

sorry for the late reply. If you go to https://makeorama.de/products/colorfabb_pla and take a look into the markup header. There you can see clearly the OpenGraph Tags are set correctly. If you check them e. g. on https://opengraphcheck.com you will get the result that the default open graph tags are displayed. So Angular is setting the metatags correctly.

Regards

**Comment by aslushnikov** [comment]
@Evil-Me I'm sorry but I still don't understand - how's Puppeteer related to this?
