### ISSUE TITLE
> Running `yum update nss` worked for me.

### ISSUE THREAD

**Issue by chuans** [puppeteer/puppeteer#4601]
> Running `yum update nss` worked for me.

why，Prompt me to install successfully, but still invalid
centos7.2 
node 8.11.3
puppeteer  1.14.0
please help

_Originally posted by @chuans in https://github.com/GoogleChrome/puppeteer/issues/3080#issuecomment-503472035_

**Comment by aslushnikov** [comment]
There's been a lot of discussion on CentOS on the bugtracker:
- https://github.com/GoogleChrome/puppeteer/issues/391
- [Chrome headless doesn't launch on UNIX
](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)

Please check out these topics; this looks like some kind of local env problem you're fighting.
