### ISSUE TITLE
Q: Does puppeteer track the pages I am navigating between?

### ISSUE THREAD

**Issue by reZach** [puppeteer/puppeteer#4603]
My overly-anxious brain is concerned that while the library is great at doing what it does, are our actions being tracked (and sent over to Google)? Can someone from the developer / contributor team confirm that the pages and actions we perform while using puppeteer are not being tracked and sent as data?

I'm building open source software and I want to ensure the integrity of this tool, to not compromise on privacy.

(This of course doesn't apply to puppeteer going to risky sites and performing questionable actions there; this is concerned about navigating between pages and clicking buttons, filling out inputs, etc.)

**Comment by aslushnikov** [comment]
> Can someone from the developer / contributor team confirm that the pages and actions we perform while using puppeteer are not being tracked and sent as data?

@reZach Sure! Puppeteer doesn't send anything to anywhere.

We also do our best to disable various browser reporting subsystems, such as [crash reporting](https://github.com/GoogleChrome/puppeteer/blob/411347cd7bb03edacf0854760712d32b0d9ba68f/lib/Launcher.js#L43), [sync](https://github.com/GoogleChrome/puppeteer/blob/411347cd7bb03edacf0854760712d32b0d9ba68f/lib/Launcher.js#L56), and [metrics reporting](https://github.com/GoogleChrome/puppeteer/blob/411347cd7bb03edacf0854760712d32b0d9ba68f/lib/Launcher.js#L58).

Hope this helps!

**Comment by reZach** [comment]
Thanks for clarifying this for me @aslushnikov! Thank you for the extra details (line numbers) in the code.
