### ISSUE TITLE
typescript think $$eval always return Element[]

### ISSUE THREAD

**Issue by theGABS** [puppeteer/puppeteer#4607]
### Steps to reproduce

**Tell us about your environment:**

```
      System Version: macOS 10.14.1 (18B75)
      Kernel Version: Darwin 18.2.0
      Boot Volume: SSD
      Boot Mode: Normal
      Computer Name: Max’s iMac
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 12 days 9:50
```
* "puppeteer": "1.17.0"
* Node.js version: v8.15.1.
* Command to launch: `"getSEO": "ts-node -O \"{\\\"module\\\": \\\"commonjs\\\"}\" buildSEO.ts"`

**What steps will reproduce the problem?**

1. use typescript
2. write something like page.$$eval('a', (as: HTMLAnchorElement[]) => as.map(a => a.href))

**What is the expected result?**
compile successful

**What happens instead?**
```
Argument of type '(as: HTMLAnchorElement[]) => string[]' is not assignable to parameter of type '(elements: Element[]) => string[] | Promise<string[]>'.
  Types of parameters 'as' and 'elements' are incompatible.
    Type 'Element[]' is not assignable to type 'HTMLAnchorElement[]'.
      Type 'Element' is missing the following properties from type 'HTMLAnchorElement': charset, coords, download, hreflang, and 135 more.
```

When I look at type definetion I saw next

```
  $$eval<R>(
    selector: string,
    pageFunction: (elements: Element[]) => R | Promise<R>,
  ): Promise<WrapElementHandle<R>>;
```
So, it is always Element, maybe better way use some generic, like 
```
  $$eval<R, T>(
    selector: string,
    pageFunction: (elements: T[]) => R | Promise<R>,
  ): Promise<WrapElementHandle<R>>;
```

**Comment by aslushnikov** [comment]
@theGABS the typescript definitions for Puppeteer are not, in fact, part of Puppeteer project. They are hosted on https://github.com/DefinitelyTyped/DefinitelyTyped and maintained by community.

Can you please submit a PR for the DefinitelyTyped with your suggestions?

(+cc @JoelEinbinder how was working on auto-generating typescript types for puppeteer)
