### ISSUE TITLE
v1.18.0 Page.pdf - Protocol error (IO.read): Invalid parameters handle: string value expected

### ISSUE THREAD

**Issue by akbortoli** [puppeteer/puppeteer#4609]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `1.18.0`
* Platform / OS version: `AWS Lambda / Amazon Linux`
* Node.js version: `8.10`

**What steps will reproduce the problem?**

```javascript
await page.setContent(HTML);

await page.pdf({
    path: "/tmp/filename.html",
    format: "A4",
    margin: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0
    },
    preferCSSPageSize: true,
    printBackground: true
});
```

**Stack Trace:**

```JSON
{
    "errorMessage": "Protocol error (IO.read): Invalid parameters handle: string value expected",
    "errorType": "Error",
    "stackTrace": [
        "Promise (/var/task/node_modules/puppeteer-core/lib/Connection.js:183:56)",
        "new Promise (<anonymous>)",
        "CDPSession.send (/var/task/node_modules/puppeteer-core/lib/Connection.js:182:12)",
        "Function.readProtocolStream (/var/task/node_modules/puppeteer-core/lib/helper.js:238:37)",
        "<anonymous>",
        "  -- ASYNC --",
        "Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:111:15)",
        "convert (/var/task/convert.js:74:27)",
        "<anonymous>",
        "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
    ]
}
```

`"convert (/var/task/convert.js:74:27)"` is where `await page.pdf(...);` call is.

1. Lunch `await puppeteer.launch();`
2. Browser new page `await browser.newPage();`
3. Page set content `await page.setContent(HTML)`
4. Page pdf `await page.pdf(...);`

**What is the expected result?**
PDF saved to `/tmp/filename.pdf`

**What happens instead?**
Error: `Protocol error (IO.read): Invalid parameters handle: string value expected`

**Comment by yhatt** [comment]
I've reproduced in puppeteer-core v1.18.0 and stable Chrome 75 too. Perhaps we should use the bundled Chromium (77.0.3827.0) or Chrome Canary.

What he says was correct: https://github.com/GoogleChrome/puppeteer/pull/4587#pullrequestreview-250174763

**Comment by aslushnikov** [comment]
> Perhaps we should use the bundled Chromium (77.0.3827.0) or Chrome Canary.

@yhatt Either this or use a [matching versions of chrome and puppeteer-core](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

**Comment by thecrypticace** [comment]
I spent several hours trying to figure this one out. Several google searches for the error didn't bring up this issue, oddly. Didn't realize I had accidentally upgraded puppeteer. ¯\\_(ツ)_/¯

Perhaps a message could be output to the console noting that the version of puppeteer and the version of chrome it has connected to are potentially not compatible? That'd probably be a decent quality improvement for tracking down issues like this when one sees unexpected and not-easily-explained behavior.

**Comment by philipgreat** [comment]
I have the same issue when using it to generate pdf

tell us about your environment:

Puppeteer version: 1.18.0
Platform / OS version:Ubuntu Linux 18.04LTS
Node.js version: 8.10

Code is

```

const puppeteer = require('puppeteer');
  
(async() => {
  const browser = await puppeteer.launch({executablePath:'/usr/bin/chromium-browser'});
  const page = await browser.newPage();
  await page.goto('https://www.chromestatus.com', {waitUntil: 'networkidle2'});
  await page.pdf({path: 'page.pdf', format: 'A4'});

  await browser.close();
})();

```


Error
```
(node:12845) UnhandledPromiseRejectionWarning: Error: Protocol error (IO.read): Invalid parameters handle: string value expected
    at Promise (/home/philip/githome/termsys-biz-suite/bizui/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/philip/githome/termsys-biz-suite/bizui/node_modules/puppeteer/lib/Connection.js:182:12)
    at Function.readProtocolStream (/home/philip/githome/termsys-biz-suite/bizui/node_modules/puppeteer/lib/helper.js:238:37)
    at <anonymous>
  -- ASYNC --
    at Page.<anonymous> (/home/philip/githome/termsys-biz-suite/bizui/node_modules/puppeteer/lib/helper.js:111:15)
    at /home/philip/githome/termsys-biz-suite/bizui/pdf.js:7:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:12845) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12845) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stevez86** [comment]
@aslushnikov I think there's a bug here. I get this error only on 1.18 and 1.19 using [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda#versioning). 1.17 and earlier seem to be working fine. According to that link, the correct versions of chrome are downloading.

**Comment by nobleach** [comment]
I too am following these instructions closely: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine I'm using version 77 of Chromium, and using puppeteer@1.19.0. Yet I'm getting this error.

**Comment by Ilshidur** [comment]
I encountered the same issue. Turns out I had `Chromium 72.0.3626.121` instead of `Chromium 77.0.3865.120` with `"puppeteer": "1.19.0"` ... because I was using the `node:12-alpine` image in my Dockerfile instead of `node:13-alpine`.

**Comment by nobleach** [comment]
Thank you! That works!

**Comment by Lucien-X** [comment]
I encountered the same issue , 
while using Aliyun Functional Compute Service, 
which is using **nodejs v10**.

Higher version of puppeteer is incompatable with that.
**So I downgrade my puppeteer-core to v1.16.0** . Works like magic ~ 🎉
