### ISSUE TITLE
Getting elements with a certain class/ID

### ISSUE THREAD

**Issue by Mohamed3on** [puppeteer/puppeteer#461]
Hello, is there a function to get all elements that have a certain class name? I'm used to BeautifulSoup in Python, maybe it's done differently here? can I do `'.class'.forEach()`?

**Comment by JoelEinbinder** [comment]
You can use `page.evaluate` to execute JavaScript on the page.
```js
let texts = await page.evaluate(() => {
    let data = [];
    let elements = document.getElementsByClassName('myclass');
    for (var element of elements)
        data.push(element.textContent);
    return data;
});
```

**Comment by Mohamed3on** [comment]
Thanks! 
What if I want to get a `span`, or an `img`, within that element?

**Comment by JoelEinbinder** [comment]
Look into https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

**Comment by ashvini-maurya** [comment]
@JoelEinbinder I am able to load only few DOM elements with your first approach.

**Comment by sorb999** [comment]
@JoelEinbinder I am not able to return entire element.
Is it possible to do it??
```

let texts = await page.evaluate(() => {
    let elements = document.getElementsByClassName('myclass');
    return elements;
});
```

It returns empty object (may be it lost the reference).

**Comment by aslushnikov** [comment]
@sorb999 you can get `ElementHandle` instances on the puppeteer-side:

```js
let handles = await page.$$('.myclass');
```

**Comment by mkschaller** [comment]
@JoelEinbinder THANK YOU. This is the answer I have been struggling to find for days. I've been trying to get the classList of an element and did not realize that I could easily do so by wrapping what I was trying to do within a page.evaluate().

**Comment by ghost** [comment]
@Mohamed3on  
```js

    const results_div = await puppeteerPage.evaluate(()=>{
        let e = document.getElementsByClassName("u class") // your class
        e_a = [...e] 
        arr = []
        e_a.map(e => {
             arr.push(e.innerText)
          })
          return arr
    })
```

**Comment by letrung412** [comment]
> 

map return new array. const arr = e_a.map(e => e.innerText). map not push

**Comment by victorbraga8** [comment]
> 
Hello dear partner !!! 

In my case, when i got ElementHandle on return, how can i see what is inside this object ? 

Best Regards
