### ISSUE TITLE
Puppeteer test in alpine container fails but works on windows platform

### ISSUE THREAD

**Issue by Galileo1** [puppeteer/puppeteer#4612]
I am running couple of puppeteer test. On windows platform they run well but when I dockerize them in an alpine container they start failing. Launching chrome is not the issue but they fail half way through the completion. 

Puppeteer@1.17 supports Chromium@662092

Docker file I am using is given below 

```
FROM node:10-alpine
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge=~73.0.3683.103 \
      nss@edge \
      freetype@edge \
      harfbuzz@edge \
      ttf-freefont@edge

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads /app \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app
USER pptruser
```

Other problem is test in the container are very slow. Like extremely slow.

**Comment by dagcosta** [comment]
Having issues putting it to work also, all good in node:10-slim, but on node:10-alpine, having trouble making it work following the given instructions.

**Comment by aslushnikov** [comment]
It's hard to say why things are slow. Can it be that you run in a very constrained environment?

Overall, I think these have to do with the environments rather than with Puppeteer itself.
