### ISSUE TITLE
puppeteer-firefox - waitUntil - networkIdle0

### ISSUE THREAD

**Issue by rodoabad** [puppeteer/puppeteer#4613]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: "puppeteer-firefox": "^0.5.0"
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version: 8

**What steps will reproduce the problem?**
```js
await Promise.all([
  page.goto(`${process.env.URL_TO_TEST}`),
  page.waitForNavigation({
    waitUntil: 'networkidle0'
  })
]);

```

**What is the expected result?**

Workflow continues and waits for navigation.

**What happens instead?**

```
Unknown waitUntil condition: networkidle0
```

```
(node:7615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'emit' of undefined
    at Browser._onTargetDestroyed (/node_modules/puppeteer-firefox/lib/Browser.js:195:28)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection._onMessage (node_modules/puppeteer-firefox/lib/Connection.js:124:12)
    at <anonymous>
(node:7615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by twitwi** [comment]
I observe the same error (`Error: Unknown waitUntil condition: networkidle0`) with the same puppeteer-firefox version 0.5.0, under linux mint 19, when trying to run decktape.js with puppeteer-firefox.

**Comment by buhion** [comment]
Similar error for puppeteer-firefox@0.5.0 (`Error: Unknown waitUntil condition: networkidle2`) in MacOS

**Comment by aslushnikov** [comment]
`networkidle` is not yet supported in pptr-firefox. But stay tuned!

**Comment by rodoabad** [comment]
@aslushnikov can you add the firefox label?

**Comment by mjzffr** [comment]
Thanks for the report. I'm closing this issue since the experimental `puppeteer-firefox` package is no longer maintained. A replacement will be available
later this year. You can learn more about Mozilla's work on this at https://wiki.mozilla.org/Remote

See also https://github.com/puppeteer/puppeteer/pull/5137

**Comment by ali-habibzadeh** [comment]
This is still an issue. It just times out
