### ISSUE TITLE
Failed to launch chrome! when headless is set to false

### ISSUE THREAD

**Issue by mperodin** [puppeteer/puppeteer#4614]
This code works when headless: true , however I want this code to run when headless :false , but instead when set to false I get error "failed to launch chrome".  I have been debugging for days and reading all previous post nothing seems to fix.  both true and false work when running locally but when uploading to Google App Engine on a live server headless:false doesnt work.

I event tried to use an executable path for chrome.exe and still nothing when set to false
            executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'

please dont think I made this code up, I copied this from https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/3bb14ef7c23305613bbfe04f03d3b83f6a120e1a/appengine/headless-chrome/app.js

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.0
* Platform / OS version: Windows 10
* URLs (if applicable): https://tdws-244419.appspot.com/?url=https://facebook.com
* Node.js version: v8.12.0

**What steps will reproduce the problem?**
### package.json
         {
         "name": "gcloud",
         "engines": {
         "node": ">=8.0.0"
          },
         "version": "1.0.0",
         "description": "",
         "main": "app.js",
         "scripts": {
         "start": "node app.js",
         "test": "echo \"Error: no test specified\" && exit 1"
          },
          "author": "",
          "license": "ISC",
         "dependencies": {
         "express": "^4.16.3",
          "puppeteer": "^1.18.0"
          }
          }

### app.js

        const express = require('express');
        const puppeteer = require('puppeteer');
        const app = express();

        app.use(async (req, res) => {
          try {
            const url = req.query.url;

           if (!url) {
            return res.send('Please provide URL as GET parameter, for example: <a href="/? 
           url=https://example.com">?url=https://example.com</a>');
           }

        const browser = await puppeteer.launch({
            args: ['--no-sandbox',
                '--disable-setuid-sandbox'],
            headless: false
        });
        const page = await browser.newPage();
        await page.goto(url);
        const imageBuffer = await page.screenshot();
        browser.close();

        res.set('Content-Type', 'image/png');
        res.send(imageBuffer);
        } catch (e) {
        res.send("the errror is " + e)
       }
       });

      const server = app.listen(process.env.PORT || 8080, err => {
        if (err) return console.error(err);
         const port = server.address().port;
          console.info(`App listening on port ${port}`);
        });

### app.yaml

        runtime: nodejs10
        instance_class: F4_1G

_Please include code that reproduces the issue._

1. copy and paste the code 
2. launch puppeteer
3. or you can view the live website https://tdws-244419.appspot.com/?url=https://facebook.com

**What is the expected result?**
I want chrome/chromium to launch

**What happens instead?**

I get the error the errror 

Error: Failed to launch chrome! [63:68:0622/163912.743502:ERROR:file_path_watcher_linux.cc(71)] Failed to read /proc/sys/fs/inotify/max_user_watches (chrome:63): Gtk-WARNING **: 16:39:12.758: cannot open display: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

@aslushnikov

**Comment by aslushnikov** [comment]
I'm not sure you can easily run headless: false in a cloud - unless you use something like xvfb.

I'd recommend asking folks on the Stackoverflow - we are unfortunately not a cloud wizards here ourselves.

**Comment by babyrusa** [comment]
hey have u found the answer for ur issue? @mperodin
