### ISSUE TITLE
chrome: symbol lookup error: /usr/lib64/libcairo-gobject.so.2: undefined symbol: cairo_region_destroy

### ISSUE THREAD

**Issue by AEDavis5** [puppeteer/puppeteer#4615]
I've spent a lot of time collecting all needed dependencies, to run Puppeteer/Chrome on my Linux server.
```
CentOS 6
Linux 64-bit
```

However, I keep running into one issue after the next.

I did run the popularly mentioned command:
`curl https://intoli.com/install-google-chrome.sh | bash`

Though I kept running into this error for quite some time:
```
/tmp/google-chrome-installation/patchelf-0.9 /tmp/google-chrome-installation ~
bash: line 239: ./bootstrap.sh: Permission denied
bash: line 240: ./configure: No such file or directory
make: *** No targets specified and no makefile found. Stop.
...
Attempted experimental patching of Chrome to use a relocated glibc version.
Installation has failed.
```

Until I allowed "/tmp" folder to run executables:
`mount -o remount,exec /tmp`

Which seemed to fix the issue, and the patch was successful.

However, now I'm still stuck at this point:
```
node puppeteer/example.js

(node:5589) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/root/node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux/chrome: symbol lookup error: /usr/lib64/libcairo-gobject.so.2: undefined symbol: cairo_region_destroy
```

Initially, I couldn't find a missing "libcairo-gobject", so I got it from installing Firefox.
The error persisted, so I removed Firefox, returning the "missing dependency" error.

I tried to find the most relevant/recent version of "libcairo-gobject2", using this in the end:
```
wget http://widehat.opensuse.org/opensuse/distribution/leap/15.0/repo/oss/x86_64/libcairo-gobject2-1.15.10-lp150.2.2.x86_64.rpm

yum --nogpgcheck localinstall libcairo-gobject2-1.15.10-lp150.2.2.x86_64.rpm
```

So now, I have again "libcairo-gobject2",
I have no missing chrome dependancies, when I check with:
```
cd node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux
ldd chrome | grep not
```

Yet still each time I attempt to run chrome using the example file from the basic tutorial, I keep getting this error:
```
node puppeteer/example.js

(node:5589) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/root/node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux/chrome: symbol **lookup error: /usr/lib64/libcairo-gobject.so.2: undefined symbol: cairo_region_destroy**
```

Any guidance would be appreciated.
Or, if there is a correct version of the "libcairo-gobject.so.2" file that would fix the error, could someone link me to this corrected file?

Thank you,
Andrew

**Comment by aslushnikov** [comment]
Hi @AEDavis5,

Did you try following the [troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)? It usually installs all the necessary dependencies.

Other than that, I'm not sure we can suggest anything regarding licairo-gobject library issues.

**Comment by json-Li** [comment]
> I've spent a lot of time collecting all needed dependencies, to run Puppeteer/Chrome on my Linux server.
> 
> ```
> CentOS 6
> Linux 64-bit
> ```
> 
> However, I keep running into one issue after the next.
> 
> I did run the popularly mentioned command:
> `curl https://intoli.com/install-google-chrome.sh | bash`
> 
> Though I kept running into this error for quite some time:
> 
> ```
> /tmp/google-chrome-installation/patchelf-0.9 /tmp/google-chrome-installation ~
> bash: line 239: ./bootstrap.sh: Permission denied
> bash: line 240: ./configure: No such file or directory
> make: *** No targets specified and no makefile found. Stop.
> ...
> Attempted experimental patching of Chrome to use a relocated glibc version.
> Installation has failed.
> ```
> 
> Until I allowed "/tmp" folder to run executables:
> `mount -o remount,exec /tmp`
> 
> Which seemed to fix the issue, and the patch was successful.
> 
> However, now I'm still stuck at this point:
> 
> ```
> node puppeteer/example.js
> 
> (node:5589) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
> /root/node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux/chrome: symbol lookup error: /usr/lib64/libcairo-gobject.so.2: undefined symbol: cairo_region_destroy
> ```
> 
> Initially, I couldn't find a missing "libcairo-gobject", so I got it from installing Firefox.
> The error persisted, so I removed Firefox, returning the "missing dependency" error.
> 
> I tried to find the most relevant/recent version of "libcairo-gobject2", using this in the end:
> 
> ```
> wget http://widehat.opensuse.org/opensuse/distribution/leap/15.0/repo/oss/x86_64/libcairo-gobject2-1.15.10-lp150.2.2.x86_64.rpm
> 
> yum --nogpgcheck localinstall libcairo-gobject2-1.15.10-lp150.2.2.x86_64.rpm
> ```
> 
> So now, I have again "libcairo-gobject2",
> I have no missing chrome dependancies, when I check with:
> 
> ```
> cd node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux
> ldd chrome | grep not
> ```
> 
> Yet still each time I attempt to run chrome using the example file from the basic tutorial, I keep getting this error:
> 
> ```
> node puppeteer/example.js
> 
> (node:5589) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
> /root/node_modules/puppeteer/.local-chromium/linux-669486/chrome-linux/chrome: symbol **lookup error: /usr/lib64/libcairo-gobject.so.2: undefined symbol: cairo_region_destroy**
> ```
> 
> Any guidance would be appreciated.
> Or, if there is a correct version of the "libcairo-gobject.so.2" file that would fix the error, could someone link me to this corrected file?
> 
> Thank you,
> Andrew

have you solved this problem ,i faced this issue too
