### ISSUE TITLE
How to render JS to generate fingerprint for cookie?

### ISSUE THREAD

**Issue by northtree** [puppeteer/puppeteer#4616]
This URL uses JS to set cookie.
https://www.realestate.com.au/auction-results/nsw

I had tried `puppeteer` to mock as browser, however it still returns 429 and 404 error.

The requests from Chrome were captured as following,

- request nsw (status 429)
- request three JS
- request fingerprint XHR which will return new key for the cookie
- request nsw again (status 200)

My question is how to run `fingerprint` JS in puppeteer similar to Chrome to set the cookie.

<img width="765" alt="Screen Shot 2019-06-20 at 12 04 41 pm" src="https://user-images.githubusercontent.com/419509/59973056-2a35f100-95dd-11e9-9354-4d9ae4bd483c.png">

**Comment by aslushnikov** [comment]
Looks like the website uses some anti-automation techniques to prevent your script from running.

**Comment by northtree** [comment]
@aslushnikov However, Google/Bing Cache could fetch and render this URL.

> https://webcache.googleusercontent.com/search?q=cache:https://www.realestate.com.au/auction-results/nsw

> http://cc.bingj.com/cache.aspx?d=4604696519377405&w=l1afuSRus1gt-RpyEw8vaw-uhm07sY14
