### ISSUE TITLE
puppeteer.launch launch chromium but doesn't resolve promise

### ISSUE THREAD

**Issue by idanf** [puppeteer/puppeteer#4617]
* Puppeteer version: 1.18.0
* Platform / OS version: win 10 64-bit
* Node.js version: v10.16.0

**What steps will reproduce the problem?**
run the code:

_Please include code that reproduces the issue._
const puppeteer = require('puppeteer');
(async () => {
const browser = await puppeteer.launch();
console.log("got here");
const page = await browser.newPage();	
})();
**What is the expected result?**
see "got here"  on the console

**What happens instead?**
chromium screen is opened but the promise doesn't resolve.

**Comment by mperodin** [comment]
const puppeteer = require('puppeteer');
(async () => {

try{
const browser = await puppeteer.launch();
console.log("got here");
const page = await browser.newPage();
} catch(e){
console.log(e) ; 
}
})();

**Comment by idanf** [comment]
Timeout error: (the chrome version is Version 77.0.3827.0)

{ TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r669486
    at Timeout.onTimeout (C:\Users\Idan.f\node_modules\puppeteer\lib\Launcher.js:351:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }

**Comment by idanf** [comment]
After some digging this issue solved everything
[https://github.com/GoogleChrome/puppeteer/issues/3681](url)

**Comment by rakshithrai77** [comment]
Hi idanf, 
Could you tell how did you resolve this issue? 
Thanks

**Comment by idanf** [comment]
hi @rakshithrai77 , 
the original link is indeed dead :\ .
the new link is at https://github.com/puppeteer/puppeteer/issues/3681

The answer from that thread is:
"
I found the culprit. --disable-extensions is forbidden in my corporate environment. That was stupid (the extensions it mandates are not security sensitive or protective or enforcing anything).
puppeteer.launch({ignoreDefaultArgs: ['--disable-extensions']}) fixes it, until the next error...
"

**Comment by cage1618** [comment]
I have the same promble and I don't want to ignore the `--disable-extensions` args.

Is this a bug? Is there other better solution?

**Comment by idanftx** [comment]
hi, not that i was able to find (it is still working to this day on high scale production)
Probably a bug so minor they wont fix
