### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by angleneo** [puppeteer/puppeteer#4618]
rt
![image](https://user-images.githubusercontent.com/20380882/59985276-264cb200-9663-11e9-8584-42f95bd2897c.png)

![image](https://user-images.githubusercontent.com/20380882/59985291-441a1700-9663-11e9-93ca-4492f7351e26.png)

![image](https://user-images.githubusercontent.com/20380882/59985342-a115cd00-9663-11e9-8d57-4afc06e1cc85.png)

 
Normal installation according to demo use, call error, it is difficult to check, where is the problem?

**Comment by angleneo** [comment]
![image](https://user-images.githubusercontent.com/20380882/59985371-d02c3e80-9663-11e9-964e-0a4a05f387aa.png)

**Comment by aslushnikov** [comment]
I'm not sure I follow what's going on here. Can you please re-file with a clear code snippet that I can copy-paste and run locally to see and debug your issue?

**Comment by MoSofi** [comment]
@angleneo Did you find a solution for this problem?

**Comment by angleneo** [comment]
> @angleneo Did you find a solution for this problem?

I use another support svg screenshot plug - in to solve this problem is saveSvgAsPng
