### ISSUE TITLE
Modified the system time and then the login prompt "Error: No node found for selector"

### ISSUE THREAD

**Issue by Orocker** [puppeteer/puppeteer#4619]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Windows10 / Centos
* URLs (if applicable):
* Node.js version: v10.16.0

**What steps will reproduce the problem?**
If I modify the system time (windows or centos) then log in.
If time is OK, It don't have this problem.
```

async function login(page, url, account, password, waitMs) {
    log("log in to [" + url + "]");
    await page.goto(url);
    await page.waitFor(1000);
  231.   await page.type('#name', account, {delay: 100}); #  # this line get an error 
   await page.type('[type="password"]', password, {delay: 100});
    await page.click('.btn-submit');
    await page.waitFor(waitMs);
}

This is my form dom:


<div class="login-content">
--
   <form id="_form" method="POST" action="/login">
   <ul>
   <li>
  <input id="name" class="form-control" type="text" name="name" value="" placeholder="Username" maxlength="50" required autofocus>
   </li>
   <li>
  <input type="password" name="password" placeholder="Password" maxlength="50" required>
   </li>
   <li>
  <div class="login-btn">
<div class="error-tips">
  </div>
 <div class="btn-submit">
 <a href="javascript:void(0)" onclick="document.getElementById('_form').submit();">LOGIN</a>
 </div>
  </div>
  </li>
  </ul>
   </form>
</div>


```

**What is the expected result?**
Can log in 

**What happens instead?**

Get an error :

(node:16580) UnhandledPromiseRejectionWarning: Error: No node found for selector: #name
    at assert (D:\php\www\reportico\node_modules\_puppeteer@1.17.0@puppeteer\lib\helper.js:231:11)
    at DOMWorld.type (D:\php\www\reportico\node_modules\_puppeteer@1.17.0@puppeteer\lib\DOMWorld.js:433:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (D:\php\www\reportico\node_modules\_puppeteer@1.17.0@puppeteer\lib\helper.js:110:27)
    at Page.type (D:\php\www\reportico\node_modules\_puppeteer@1.17.0@puppeteer\lib\Page.js:1027:29)
    at login (D:\php\www\reportico\app\Scripts\clipNavigationPupp.js:325:16)
(node:16580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not han
dled with .catch(). (rejection id: 1)
(node:16580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment]
I don't think it has something to do with Puppeteer - it might be website itself that messes with you and serves a different markup.
