### ISSUE TITLE
Block scripts

### ISSUE THREAD

**Issue by loilo** [puppeteer/puppeteer#462]
Easy question: Is there a reliable way to block execution of any JavaScript on a `Page`?

I've not found anything on this in the docs, but I'm curious if it's possible at all?

**Comment by JoelEinbinder** [comment]
What is your use case for this?

**Comment by loilo** [comment]
I'm fiddling around with scraping webpages using headless Chromium and want to offer some options for blocking scripts, styles, images.

For styles and images, this is mainly to save some bandwidth, so just checking the `Accept` request header suffices for my use case (read: blocking things like inline `<style>` blocks is not my focus there).

However scripts are a bit of another story since they may alter page contents, so I want to try and block them entirely.

Of course, as soon as I disable JavaScript execution, I could just use a simple HTTP-based web scraper for the job, but if there's an option in Chromium then using the same technology stack as for the rest of the scraper would be preferrable.
