### ISSUE TITLE
Validate setCacheEnable and setRequestInterception usage

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#4620]
I got a question on Puppeteer-Sharp saying something like:

>I want to enable cache, to cache images, but I need to intercept my xhr request. When I set `setRequestInterception`, cache stop working.

So I ended up reading some changes made on #4260. Here [_updateProtocolCacheDisabled](https://github.com/GoogleChrome/puppeteer/pull/4260/files#diff-d2ac7cb061b0c51644d0a5d6140e3a32R148) to be more specific.

So, I have two questions regarding this piece of code:

```js
cacheDisabled: this._userCacheDisabled || this._protocolRequestInterceptionEnabled
````

1. Do we need to disable the cache there, when the user explicitly opted to enable it?
2. If so, as those are two explicit actions made by the user (`setCacheEnable` and `setRequestInterception`), Shouldn't we assert there saying something like `Cannot user setCacheEnable and setRequestInterception at the same time`?

**Comment by jonasgroendahl** [comment]
Any solution to this? Or is it just always better to have the cache option enabled to lower bandwidth?

**Comment by liweixi100** [comment]
Our test showed: when interception and caching were enabled at the same time, many websites will fail to load: https://github.com/puppeteer/puppeteer/issues/5176#issuecomment-554815586 

If the website of your interest happens to work, good for you. 

But I guess there was a reason why the API was coded that way, based on our tests at least.

**Comment by Androbin** [comment]
The issue described by @liweixi100 is described in #7038 and solved by #7060.

**Comment by kblok** [comment]
@Androbin, did #7060 solve this? can I close it?

**Comment by Androbin** [comment]
@kblok #7060 solved the issue underlying the need the disable the cache.
If we implement this fix in PuppeteerSharp, we can simplify write:

```
_cacheDisabled(): boolean {
  return this._userCacheDisabled;
}
```

**Comment by Androbin** [comment]
See #1765

**Comment by Androbin** [comment]
See https://github.com/hardkoded/puppeteer-sharp/pull/1765
