### ISSUE TITLE
puppeteer for react-native

### ISSUE THREAD

**Issue by Santu1245** [puppeteer/puppeteer#4621]
How can I use puppeteer for react-native?

**Comment by charlie632** [comment]
I don't think you can. Unless you are running a web app using react-native-web, but not for a native app.

**Comment by davidsharp** [comment]
I believe you could hook into the remote debugging session using `puppeteer.connect`, but I don't know if you'd be able to do anything useful with the worker it runs in. It should also be possible to do something similar to connect to `react-devtools`, but again, I'm not sure how useful that would be.

**Comment by aslushnikov** [comment]
> How can I use puppeteer for react-native?

I don't think there's any sensible way to do that.

**Comment by SassanKermani** [comment]
is there a non-sensible way to do it, It would be magic to do web scraping from a phone

**Comment by giosyrianos** [comment]
Any updates on that??
