### ISSUE TITLE
Selecting value from drop-down does not work with 'xpath'

### ISSUE THREAD

**Issue by subrato29** [puppeteer/puppeteer#4622]
Is there any way to write a helper function in Puppeteer to select a value from drop-down using "xpath"(not CSS) as locator. If yes, please share the exact code snippet. I tried with below helper function.
async function select(xpath, value) {
  const elements = await page.$x(xpath);
  await elements[0].select(value);
}
getting below error
TypeError: elements[0].select is not a function...any idea where I am doing mistake

**Comment by aslushnikov** [comment]
Yeah, well, I don't really think it's possible.

@JoelEinbinder wdyt about adding `elementHandle.select()`? I remember you had some naming concerns, but given that we already have `page.select()` forever with us, I think `elementHandle.select()` is nice to have for these kind of usecases.

**Comment by AzySir** [comment]
@aslushnikov @JoelEinbinder  

How did we go here? I'm also facing a similar issue the html is as below. Am I required to use eval here? 

```
<select title="Number of dependants" class="">
  <option>0</option>
  <option>1</option>
  <option>2</option>
  <option>3</option>
  <option>4</option>
  <option>5+</option>
</select>
```
