### ISSUE TITLE
redirection chain is not working properly..

### ISSUE THREAD

**Issue by saiprashanth24** [puppeteer/puppeteer#4625]
for some redirection urls,puppeteer treats them as normal urls..
request.redirectchain() returns nothing..

eg:https://www.zoho.com/sa/invoice/tour/time-tracking/ is redirected to https://www.zoho.com/sa/invoice/time-tracking/   but puppeteer doesnot treat is as redirected url..

steps to reproduce..
version 1.18.0

**Comment by aslushnikov** [comment]
@saiprashanth24 I can't repro with Puppeteer 1.18.1 and the following script:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const response = await page.goto('https://www.zoho.com/sa/invoice/tour/time-tracking/');
  for (const r of response.request().redirectChain())
    console.log(r.method() + ' ' + r.response().status() + ' ' + r.url());
  await browser.close();
})();
```

This outputs for me:
```
GET 301 https://www.zoho.com/sa/invoice/tour/time-tracking/
```

What's your script?

**Comment by saiprashanth24** [comment]
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    const response = await page.goto('https://www.zoho.com/sa/invoice/tour/time-tracking/');
    console.log(response.request().redirectChain().length);
    for (const r of response.request().redirectChain())
        console.log(r.method() + ' ' + r.response().status() + ' ' + r.url());
    await browser.close();
})();

```
this outputs 
`0`

**Comment by aslushnikov** [comment]
@saiprashanth24 interesting, so the same script doesn't work for you. Let's dig further: what does the following print?

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('request', r => {
    if (r.resourceType() === 'document')
      console.log('=> ' + r.method() + ' ' + r.url());
  });
  page.on('response', r => {
    if (r.request().resourceType() === 'document')
      console.log('<= ' + r.status() + ' ' + r.url());
  });
  await page.goto('https://www.zoho.com/sa/invoice/tour/time-tracking/');
  await browser.close();
})();
```

**Comment by saiprashanth24** [comment]
![image](https://user-images.githubusercontent.com/42546847/60256311-e8fc5480-98ee-11e9-9602-088bf112976c.png)
 In redirect chain it prints nothing,but in response ,it returns the correct redirected url.
 Is it expected behaviour ?

**Comment by saiprashanth24** [comment]
actually my code will be like this 
```

    await page.setRequestInterception(true);
    page.on('request', request => {
      if (request.resourceType() === "xhr" || request.resourceType() === "script" || request.resourceType() === "image" || request.resourceType() === "stylesheet") {
        request.abort();
      } else {
        request.continue();
      }
    });


    const response = await page.goto(url, { timeout: 50000, waitUntil: 'networkidle0' });
    const chain = response.request().redirectChain();
```

**Comment by aslushnikov** [comment]
> actually my code will be like this

@saiprashanth24 I still can't repro.

Let me re-iterate: you ran the code from [this comment](https://github.com/GoogleChrome/puppeteer/issues/4625#issuecomment-506146528) as-is, without changing anything, and it prints nothing for you. Is this correct?

If _yes_, than a few questions:
- do you run with the bundled chromium instance?
- do you have env variable `PUPPETEER_EXECUTABLE_PATH` defined?
- what's your OS version?

**Comment by saiprashanth24** [comment]
yes,

- yes ,i run with bundled chromium instance only..

- no i have not defined the PUPPETEER_EXECUTABLE_PATH..

- ubuntu 16.04

**Comment by aslushnikov** [comment]
@saiprashanth24 Can you please run that script with DEBUG=* and post the log here?

**Comment by saiprashanth24** [comment]
https://docs.google.com/document/d/1U7Het-Xcg5gmWsW9dmyv_1poGliSZ9sgF5Vwnz4AxVY/edit?usp=sharing

I have attached logs in the above link

**Comment by aslushnikov** [comment]
@saiprashanth24 Oh ok, I understand now.

After looking closer to [your screenshot](https://github.com/GoogleChrome/puppeteer/issues/4625#issuecomment-506277182), I see there's another document request to the https://www.zoho.com/in/invoice/time-tracking/. Looking into your logs, I see that this request is initiated by javascript.

So what happens is that somewhere during its navigation, page's javascript runs and decides to navigate you to the https://www.zoho.com/in/invoice/time-tracking/. Now, this is not an HTTP redirect - rather a JavaScript redirect, so this is not part of the `request.redirectChain()`. This is expected behavior.

The reason this behavior does not reproduce for me is because the page doesn't redirect me to the https://www.zoho.com/in/invoice/time-tracking/ - I'd guess that it relies on IP or something else to drive the decision.

Hope this clears the confusion!

**Comment by saiprashanth24** [comment]
yeah thank you so much

**Comment by handrei-lupu** [comment]
For this URL
https://www.askgamblers.com/visit/bonus/fortune-clock-casino-50percent-match-deposit-bonus-visit

response.request().redirectChain().length returns 0
And the last URL is returned as just the hostname, without all the query params
Any idea ?
Also, I have seen websites that have IMG elements with an onerror attribute that sets the SRC attribute again, resulting in infinite loops trying to download the image and blocking the browser, if downloading of images were disabled
