### ISSUE TITLE
Timeout when calling page.setContent

### ISSUE THREAD

**Issue by longboardcat** [puppeteer/puppeteer#4627]
I'm running into timeouts when calling `page.setContent` in a Node.js 8 Google Cloud function. Locally, I've run everything and it works almost instantaneously.

Here's the HTML:

```html
<td class="choice face negative"><a id="question-negative" href="https://account.squareupstaging.com/response/tar2eFaKX7CLxMPO6VdjQ8luvMF/-1"><div><img alt="Negative" title="Negative" width="64" height="64" border="0" src="https://images.squareupstaging.com/ADal-ADH4XDyicSksxNu2e7v8NI=/128x128/filters:fill(546476,true):format(png)/https://djsijjdm01rhs.cloudfront.net/receipts/assets/feedback-negative-0ca99b85bb431c7cbd5c68e1e7276ad6.png"></div></a></td>
```

Here's what I'm executing using Puppeteer:

```js
const browser = await require('puppeteer').launch({
  args: ['--no-sandbox'],
  headless: true,
});

const page = await browser.newPage();

if (html) {
  await page.setContent(html, { waitUntil: 'networkidle0' });
} else if (url) {
  await page.goto(url, { waitUntil: 'networkidle0' });
}
```

It seems like there's network activity that isn't resolving. I added `await page.setRequestInterception(true);` and aborted requests for pngs, which fixed the timeout at the cost of my image. I am lost as to whether this is an issue with my HTML above or a Puppeteer / Google Cloud issue (maybe a Base64 issue?). I don't think it's a networking issue inside of the Google Cloud environment, because I can render URLs to PDFs just fine.

**Comment by MikePryn** [comment]
Hi @longboardcat! What was the issue? How did you fix it? Thanks

**Comment by longboardcat** [comment]
Thanks for getting back to me! We ended up realizing it was a networking issue instead unrelated to puppeteer. Everything is working ok now!

**Comment by major7x** [comment]
Hey @longboardcat, what was the network issue and how did you resolve the network issue? Thanks
