### ISSUE TITLE
canvas drawImage‘s difference

### ISSUE THREAD

**Issue by fandongjiqi** [puppeteer/puppeteer#4632]
I have a strange problem.

When I was using the canvas's drawImage method, I got a different display.

I am in mac os, if use {headless:false},can see the generated graph normally.

![1561623707024](https://user-images.githubusercontent.com/6702031/60252144-5662b200-98fc-11e9-931f-bf077458bd15.jpg)

but use {headless:true}，The generated canvas is not working properly.

![1561621963425](https://user-images.githubusercontent.com/6702031/60252320-9d50a780-98fc-11e9-829c-5dc671810ca1.jpg)

I use headless:false+xvfb or headless:true in centos7, and the canvas is inaccurate.

![1561609244946](https://user-images.githubusercontent.com/6702031/60252576-0d5f2d80-98fd-11e9-9307-212b1b81357d.jpg)

![1561609211884](https://user-images.githubusercontent.com/6702031/60252680-3bdd0880-98fd-11e9-9977-ef8ef664bd45.jpg)

The feeling is that the extremely thin lines caused by anti-aliasing are doped with transparency. I tried to use --disable-canvas-aa, but the problem still exists.

After zooming in on the part, I found that the border of the line is different. The figure below is normal and 2 is abnormal.

![1561626431838](https://user-images.githubusercontent.com/6702031/60253159-3af8a680-98fe-11e9-9078-71848033a6bb.jpg)

Please also help me to check the reason, where is the problem, thank you!

**Comment by aslushnikov** [comment]
@fandongjiqi Any script that I can run locally to see the problem?

**Comment by fandongjiqi** [comment]
@aslushnikov,  thank you!

[test_puppeteer.zip](https://github.com/GoogleChrome/puppeteer/files/3395628/test_puppeteer.zip)

This is Simple example.

 I use a canvas drawing engine croquis to draw by instruction. After the drawing is finished, the process of generating a drawing using the puppeter on the server, the problem now is that the generated image has a problem. On my mac, using the headless:false image is correct, the headless:true image will look very light, as shown in the image in question.

Example use:

Npm install
Http-server -p 8080
Node test.js

Modify headless to see different

**Comment by jtoy** [comment]
unsolved?
