### ISSUE TITLE
page.pdf error: Alpine docker image fails on pdf()

### ISSUE THREAD

**Issue by semoal** [puppeteer/puppeteer#4637]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.0 || 1.18.1
* Platform / OS version: Alpine Linux Docker image
* URLs (if applicable):
* Node.js version: 10/11

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Just try to generate a pdf in a alpine linux image

**What is the expected result?**
Generate pdf

**What happens instead?**

Returns an error, i guess it's related to chrome version. On npm pupppetter is using 77, but alpine it's still on 73.

```(node:123) UnhandledPromiseRejectionWarning: Error: Protocol error (IO.read): Invalid parameters handle: string value expected\n    at Promise (/app/node_modules/puppeteer/lib/Connection.js:183:56)\n    at new Promise (<anonymous>)\n    at CDPSession.send (/app/node_modules/puppeteer/lib/Connection.js:182:12)\n    at Function.readProtocolStream (/app/node_modules/puppeteer/lib/helper.js:238:37)\n    at Page.pdf (/app/node_modules/puppeteer/lib/Page.js:943:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n```

Probably it's related to this: https://github.com/GoogleChrome/puppeteer/pull/4587

I'm using 1.17 meanwhile.

**Comment by aslushnikov** [comment]
Please use a matching chromium version: https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy
