### ISSUE TITLE
Hide scrollbars

### ISSUE THREAD

**Issue by j0tunn** [puppeteer/puppeteer#4641]
Hi! There is a [Emulation.setScrollbarsHidden](https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setScrollbarsHidden) method in devtools protocol. Is there any chance that `puppeteer` will support it?
I need to hide scrollbars (not in headless mode) before taking screenshots. Guys from chromium dev team suggested to use this method.

**Comment by j0tunn** [comment]
Ok. I've found it: [createCDPSession](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#targetcreatecdpsession) + [send](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#cdpsessionsendmethod-params)

**Comment by soukron** [comment]
@j0tunn For documenting purposes can you write a snippet about the resulting code you wrote?

I'm struggling with the same issue: screenshots taken in headless mode are different than the ones taken in not headless mode due to the bars.

**Comment by j0tunn** [comment]
@soukron HI. You can find working code here: https://github.com/gemini-testing/hermione-hide-scrollbars/blob/master/dev-tools.js

**Comment by soukron** [comment]
Thanks @j0tunn. I managed to remove the scroll bars but the screenshots are still different, not sure why.
