### ISSUE TITLE
Error: Protocol error (Target.attachToTarget): No target with given id found

### ISSUE THREAD

**Issue by futurist** [puppeteer/puppeteer#4645]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: macOS 10.14.5
* URLs (if applicable): 
* Node.js version: 12.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run below code in `headless: false` mode:

```js
browser.on('targetcreated', async target => {
    if (target.type() === 'page') {
	    const page = await target.page()
		await page.target().createCDPSession()
	}
})
```

2. Press `Cmd+T` to open new tab, and `Cmd+W` to close it quickly.

**What is the expected result?**

Should not throw error.

**What happens instead?**

Sometimes throw below error:

```
Error: Protocol error (Target.attachToTarget): No target with given id found
```

**Comment by aslushnikov** [comment]
This works as expected.

Your repro steps causing a race condition: when the tab is closed,the target is destroyed, so there's nothing to attach to. That's the reason for the error and exactly what it tells.

**Comment by k96white** [comment]
I am facing this issue .
I am doing this steps
```
await page.close();
page = await this.session.browserInstance.newPage();
await page.goto(loginUrl, { waitUntil: 'domcontentloaded' }).catch(err => {
   this.session.logger.error('we are getting error');
});
await Promise.all([page.waitForSelector(Shared.htmlElement.username), page.waitForSelector(Shared.htmlElement.password)]);
await page.type(Shared.htmlElement.username, username, { delay: 30 });
await page.type(Shared.htmlElement.password, password, { delay: 30 });
```


later on it fails with same error. Can someone help
