### ISSUE TITLE
Puppeteer PDF renders but missing content 

### ISSUE THREAD

**Issue by wuno** [puppeteer/puppeteer#4647]
### Steps to reproduce

Install Puppeteer and render a PDF as a URL from Mac OS Mojave 10.14.5. When the PDF is rendered it is missing data from what the page looks like when rendered normally in a browser.

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: 10.14.5
* Node.js version: 12.2.0 && 12.5.0

This problem does not exist when we test the same app on a Ubuntu 18.0.4 system. 

**What steps will reproduce the problem?**
 
Install Puppeteer and create a PDF from an Node.js Express API endpoint.

_Please include code that reproduces the issue._

  ```
  await page.goto(url);
    if (data.waitFor) {
        try {
            await page.waitFor(data.waitFor)
        } catch(error) {
            throw new Error(error);
        }
    }

    const pdfBuffer = await page.pdf({
      format: 'A4',
      margin: {
        top: '20px',
        left: '20px',
        right: '20px',
        bottom: '20px',
      }
    });

    await browser.close();
```

**What is the expected result?**

The PDF should render and have all the same data on the page that shows when rendered in a browser. 

**What happens instead?**

The PDF is rendered but text is  missing. Even text from the same table shows in some columns but not in others.

**Comment by wufeng87** [comment]
@wuno How you solve this problem? Thanks.

**Comment by rrazi** [comment]
I'm facing this issue currently. Can we please know how this was resolved?

**Comment by ofiratt** [comment]
same issue here...

**Comment by joneslloyd** [comment]
Same here

**Comment by wuno** [comment]
It has been a long time but I want to help! 

I think it was this that solved the issue for us, 

```
await page.goto(url, {
      waitUntil: data.waitUntil ? data.waitUntil : ['domcontentloaded'],
    });
```

If not, here is everything, hope this helps... 

```
try {
    let args = ['--no-sandbox', '--disable-setuid-sandbox'];

    if (data['font-render-hinting']) {
      args.push(`--font-render-hinting=${data['font-render-hinting']}`);
    }

    const browser = await puppeteer.launch({
      args,
      ignoreHTTPSErrors: true,
      dumpio: false,
    });

    const page = await browser.newPage();

    await page.evaluateOnNewDocument(data => {
      window.requestData = {};
      window.requestData = data;
    }, data);

    await page.goto(url, {
      waitUntil: data.waitUntil ? data.waitUntil : ['domcontentloaded'],
    });

    if (data.emulateMedia) {
      await page.emulateMedia(data.emulateMedia);
    }

    if (data.waitFor) {
      try {
        await page.waitFor(data.waitFor);
      } catch (error) {
        throw new Error(error);
      }
    }

    const pdfBuffer = await page.pdf({
      format: 'A4',
      margin: {
        top: '20px',
        left: '20px',
        right: '20px',
        bottom: '20px',
      },
      ...pdfOptions,
    });

    await browser.close();

    console.log(`PDF Generated: ${pdfBuffer.length} Bytes, Name: ${filename}`);

    res.writeHead(200, {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `inline; name="${filename}"; filename="${filename}.pdf"`,
      'Content-Length': pdfBuffer.length,
    });

    res.end(pdfBuffer);
  } catch (err) {
    await browser.close();
    console.log(` ${err}`);
    res.json({
      status: 'Failed',
      message: 'Something went wrong ',
      error: err,
    });
  }
```

**Comment by gituserjava** [comment]
@wuno , what is below line? It is not getting resolved for us. Please advise

```window.requestData```

**Comment by wuno** [comment]
We are injecting JS into the DOM as we render the page in Puppeteer. That is us injecting to the window.requestData object. You can ignore that unless you need to inject content into the DOM with JavaScript.

**Comment by gituserjava** [comment]
@wuno , as of now we are don't require to inject JS. I removed all the code and using only the below line from you code, however it is not working. It is not waiting for the Angular UI page to load and hence generating a blank page. Please advise.

```
await page.goto(url, {
      waitUntil: ['domcontentloaded'],
    });
```

Instead of this if we use page.waitFor() it is working but we don't want to use that as sometimes it is generating a PDF of partial page.

**Comment by wuno** [comment]
Try adjusting the value passed in based on the docs - 

https://github.com/puppeteer/puppeteer/blob/main/docs/api.md

> waitUntil <"load"|"domcontentloaded"|"networkidle0"|"networkidle2"|Array> When to consider navigation succeeded, defaults to load. Given an array of event strings, navigation is considered to be successful after all events have been fired. Events can be either:
> load - consider navigation to be finished when the load event is fired.
> domcontentloaded - consider navigation to be finished when the DOMContentLoaded event is fired.
> networkidle0 - consider navigation to be finished when there are no more than 0 network connections for at least 500 ms.
> networkidle2 - consider navigation to be finished when there are no more than 2 network connections for at least 500 ms.

**Comment by gituserjava** [comment]
@wuno , i used various combinations of waitUtil, but it did not work. It is always generating PDF with partial content.

**Comment by jandppw** [comment]
I'm seeing the same issue. I am not sure (came here for an answer), but I have an hypothesis.

In my case, I am using web fonts, and I explicitly chose `https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Roboto:ital,wght@1,400&display=block`, meaning I get font faces like

```
@font-face {
  font-family: 'Roboto';
  font-style: italic;
  font-weight: 400;
  font-display: block;
  src: url(https://fonts.gstatic.com/s/roboto/v29/KFOkCnqEu92Fr1Mu51xEIzIXKMnyrYk.woff2) format('woff2');
  unicode-range: U+1F00-1FFF;
}
```

Using `font-display: block`. See [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display).

Also, there is no fall-back font:

```
body {
  …
  font-family: Roboto;
  …
}
```

I really want that font, consistently, and not some fall-back.

`font-display: block` ["Gives the font face a short block period and an infinite swap period."](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display).

> Font block period
>
> If the font face is not loaded, any element attempting to use it must 
> render an _**invisible fallback font face**_. If the font face
> successfully loads during this period, it is used normally.

So, the hypothesis is that, sometimes the web font loads in time, and sometimes it does not. When it does not, the invisible font is used.

I added ttf fonts to my lambda, in the hope this would force their use, as they are always available, avoiding this timing issue. But, that doesn't work.

Next, I'll try to remove the web fonts from the CSS. Will that force using the TTF fonts?

(See also [SOF](https://stackoverflow.com/questions/68724724/puppeteer-not-rendering-content-on-pdf-invisible-text/71728932#71728932).)

**Comment by gllrm-andres** [comment]
I have separate files for the template and the styles.

everything works perfect until I needed to set the font and it wouldn't take it using `page.addStyleTag` 

```
<style>
@import url('https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,400;0,700;1,400&display=swap');
body { font-family: 'Nunito', sans-serif; }
</style>
```

```
  async generatePdf(): Promise<Buffer> {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    const content = await this.getHtmlContent();
    await page.setContent(content, { waitUntil: 'networkidle2' });
    await page.addStyleTag({ path: this.stylesPath });
    const pdf = await page.pdf({
      printBackground: true,
      format: 'letter',
    });
    await browser.close();
    return pdf;
  }
```
