### ISSUE TITLE
page.pdf become very slow after 1.18.1

### ISSUE THREAD

**Issue by charlie0228** [puppeteer/puppeteer#4649]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Windows 7
* URLs (if applicable):
* Node.js version: v10.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I was using page.pdf() to export pdf file with HTML page filled with Highcharts charts, and it took me 42059ms to export for 3 pages pdf file with puppeteer 1.18.1.
After that, I roll back to the previous version (1.17.0), the problem disappeared! It only took me 342ms to export the same pdf file.

Is the problem related to #4587 ?

**Comment by aslushnikov** [comment]
@charlie0228 interesting! I wonder if this is actually the case. We are not aware of streams to be *that slower*.

Any simple repro script?

**Comment by charlie0228** [comment]
Sure! I will provide the script ASAP!

**Comment by charlie0228** [comment]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0 & 1.18.1
* Platform / OS version: Windows 7
* URLs (if applicable): 
* Node.js version: v10.15.0

Demo code with demo site:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://kylab-spo2.herokuapp.com/xenon2.ym.edu.tw/00E00040/2017-06-28', {waitUntil: 'networkidle2'});
  console.time('Export time');
  await page.pdf({path: 'hn.pdf', format: 'A4'});
  console.timeEnd('Export time');
  await browser.close();
})();
```
and the result is:
1.17.0: **Export time: 367.414ms**
1.18.1: **Export time: 3273.207ms**

**Comment by aslushnikov** [comment]
@charlie0228 Thank you for the script. I do see a little bit of a slowdown on Mac OS: `185ms` for 1.17.0 vs `220ms` for 1.18.1, but this is far from the 10x slowdown you report here on Windows.

I don't have windows yet available at my disposal, but I expect it to arrive shortly. Meanwhile, can you please run your script with `DEBUG=*` and paste the log here?

**Comment by charlie0228** [comment]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0 & 1.18.1
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: v10.16.0

I use different Windows version and the problem is still.

The debug log file links are below:
[1_17_0.log](https://github.com/GoogleChrome/puppeteer/files/3420519/1_17_0.log)
[1_18_1.log](https://github.com/GoogleChrome/puppeteer/files/3420520/1_18_1.log)

**Comment by lampnick** [comment]
I also met the question.Using V1.19.0.

**Comment by GuoRuiLv** [comment]
met the same problem with  1.18.1 1.19

**Comment by sqcddzx** [comment]
I had the same problem, I tried it, what's the probability that the **cache mechanism** has changed?
I tried this idea and removed the custom font from my page, which was really fast.
Guess there was a cache file when the browser was not closed after the page was opened. Now you just skip the page and the cache is gone

**Comment by dubeg** [comment]
Same thing happened with me. 
I couldn't figure out why puppeteer took much more time exporting as pdf a document with french text, about twice as long as when exporting the same document with english text. 

Its styles set the font-family to Arial Unicode MS. Setting the font-family to a another font such as Segoe UI or Arial fixed the time difference. The Arial Unicode MS file is about 22mb.

Thanks @sqcddzx, I was about to snap.

EDIT: 
I was testing on a Windows Server 2008 R2, with the font Arial Unicode MS installed.

**Comment by vae1970** [comment]
i also met the same problem when using v1.20.0

**Comment by sqcddzx** [comment]
### **After testing, it seems to be Chromium version problem**

My package.json file "puppeteer": "^1.11.0"
`npm install` and then **puppeteer version 1.20**,
**Chromium version is 78.0.3882.0**
Then generating PDF is super slow

Then I delete the puppeteer,
 install the specified version `npm install puppeteer@1.11.0`
**puppeteer version is 1.11.0**
**Chromium version is 72.0.3617.0**
Eventually the speed is normal

Before  Elapsed Time
![before](https://user-images.githubusercontent.com/6456329/65406650-c5c04300-de12-11e9-8ae7-d788709095a4.png)

After Elapsed Time
![after](https://user-images.githubusercontent.com/6456329/65406913-729ac000-de13-11e9-90b4-9226d8c2198a.png)
@aslushnikov @charlie0228 @dubeg  I don't know if it is helpful to you. If I disturb you, I'm sorry

**Comment by Sidd27** [comment]
Any Updates on this it's even slower in 2.0.0

**Comment by whatl3y** [comment]
@aslushnikov is there a way to return a [read stream](https://nodejs.org/api/stream.html#stream_readable_streams) via `page.pdf` or another method? If not, are there plans to do this so we can pipe this stream to a write stream instead of having the entire buffer in memory first (especially for larger PDFs)?

**Comment by AuthorProxy** [comment]
still super slow at 2.0.0v ..

**Comment by trickeyone** [comment]
I ran into this when updating from 1.17 to 1.18 (or higher) as well. The entire process just hangs after the page is loaded and no other actions occur. I've let it set for more than 30 seconds and the PDF still hasn't been generated. There's nothing majorly complex about the page, either. No no-latin fonts, etc. Sticking with 1.17 allows for a quick generation, but was hoping to upgrade to, at least, 1.20 since we're using Chromium 78.0.3904.108.

**Comment by tafandi** [comment]
Just wondering if this issue is fixed?
Also I tried to downgrade using "npm install puppeteer@1.17.0" but seems like still slow too... Do I need to do anything else?
