### ISSUE TITLE
Setting "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env var to a falsy value skips chromium installation

### ISSUE THREAD

**Issue by youhyunkim** [puppeteer/puppeteer#4650]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: 1.18.1
* Platform / OS version: Ubuntu 16.04
* URLs (if applicable):
* Node.js version: 10.16.0
But this issue occurs for most environments as this is an issue with the installation step.

**What steps will reproduce the problem?**
1.) Set environment variable "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" to a falsy value (0, false, etc). In my example, I've set it to 0.
so from command line, run 
```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=0
```
2.) install puppeteer
```
yarn install puppeteer
```

**What is the expected result?**
Install chromium as part of the puppeteer library installation since "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" is set to false.

**What happens instead?**
Chromium installation gets skipped because the environment variable is set and does not care about the value assigned to the environment variable.

This makes it hard (or not pretty) to write scripts or Dockerfiles for controlling the installation of chromium as part of puppeteer. I think it would be great if the "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env var were to be properly translated to a boolean value (so that it supports 0, "false", empty string, etc).

This is the related line of code:
https://github.com/GoogleChrome/puppeteer/blob/c6c32491ec0a0209ab651c098e955d15c9305ab9/install.js#L23

**Comment by aslushnikov** [comment]
> I think it would be great if the "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env var were to be properly translated to a boolean value (so that it supports 0, "false", empty string, etc).

@youhyunkim Is this a common practice though? I was under impression that common practice is to treat set env variable as truthy and unset as falsy.

**Comment by Hypnosphi** [comment]
Empty string seems to work:

```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=
```

**Comment by youhyunkim** [comment]
Thanks @Hypnosphi for the tip
