### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by bdotsamir** [puppeteer/puppeteer#4652]
### Steps to reproduce

**Tell us about your environment:**
Raspberry Pi 3B+ running Ubuntu Mate 18.04
`uname -a` says: `Linux raspberrypi 4.15.0-1038-raspi2 #40-Ubuntu SMP PREEMPT Thu Jun 6 07:33:02 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux`

* Puppeteer version: 1.18.1
* Platform / OS version: Raspberry Pi 3B+, Ubuntu Mate 18.04
* URLs (if applicable):
* Node.js version: v10.16.0

**What steps will reproduce the problem?**
1. Try to start an instance of puppeteer.
2. Observe

_Please include code that reproduces the issue._
```js
puppeteer.launch();
```

**What is the expected result?**
It launches.

**What happens instead?**
This:
![image](https://user-images.githubusercontent.com/26691026/60459058-23773180-9c0e-11e9-87b8-1a90d1825775.png)

Potentially related issue: https://github.com/GoogleChrome/puppeteer/issues/4249

**Comment by aslushnikov** [comment]
@jennasisis We don't have Chromium binaries built for Raspberry Pi - you'll need to get chrome binary somewhere separately, and then use a proper version of puppeteer-core to run it.

See https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy on running matching versions of chrome and pptr-core.

**Comment by davibe** [comment]
bummer.

I am using puppeteer as a dependency of my project. I am not sure how to use puppeteer or puppeteer-core conditionally when I am on a raspberry. Any idea ? Thanks
