### ISSUE TITLE
Not able make a webrtc call with headless enabled 

### ISSUE THREAD

**Issue by kpkulkarni8** [puppeteer/puppeteer#4659]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by kpkulkarni8** [comment]
Following are the arguments that i am passing while launching the WebRTC call

const browser = await puppeteer.launch({
  headless: true,
  args: [ '--no-sandbox',
        '--disable-setuid-sandbox',
        '--allow-hidden-media-playback',
        '--use-fake-ui-for-media-stream=1',
        '--use-fake-device-for-media-stream=1'
        
        ]
});

**Comment by chrisl8888** [comment]
Duplicates: #4662 #4663

Please close those maintainers :)

**Comment by aslushnikov** [comment]
@kpkulkarni8 well, it looks like Headless does not support WebRTC - but I haven't tried really. Feel free to ask on chromium-dev google group - they might know better.
