### ISSUE TITLE
How to upload file in base64 without saving locally?

### ISSUE THREAD

**Issue by xesjkeee** [puppeteer/puppeteer#4665]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.16.0
* Platform / OS version: MacOS
* URLs (if applicable): –
* Node.js version:10.15.3

**There are the steps that I did in order to solve the problem, but didn’t solve it yet**

```js
// Here im uploading file locally
await page.type('input[name="pageNum"]', `${DATA.authorizationDocument.pageNum}`);
const filePath = path.relative(process.cwd(), __dirname + '/files/doc.pdf');
await input.uploadFile(filePath);
```

**What is the expected result?**

Im expecting my code to talk to the http-server where is my puppeter is located and will return the file which will be transformed into encode base64

**What happens instead?**

Now i only can read file locally but nothing happends (it doesnt talk to the server)

**Comment by aslushnikov** [comment]
I don't understand - what's wrong? Did you click 'submit' after setting the upload file?

**Comment by paullewis** [comment]
Going to close this as it should be WAI. `uploadFile` passes the data to the input element, but you will still need to trigger the submit or XHR yourself.

**Comment by jonathan-h-james** [comment]
I'm wondering if the OP was asking how to upload a file WITHOUT saving it locally first. I would also like to know this.
