### ISSUE TITLE
How to get reponse.status() from a button that doesn't imply navigation?

### ISSUE THREAD

**Issue by pablofaust** [puppeteer/puppeteer#4666]
Hi,

I'm looking for a way to get the response.status() when I click a specific button.

I found https://github.com/GoogleChrome/puppeteer/issues/1205 where the solution given would be:
`const [response] = await Promise.all([
  page.waitForNavigation(),
  page.click('a')
]);`

But in the case of the Instagram Follow button, waitForNavigation get stucks for ever, though I know it sends a 500 status when an error occurs. How could I get this error code?

Thanks!

**Comment by vsemozhetbyt** [comment]
Maybe [`page.waitForResponse()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforresponseurlorpredicate-options) can help?
