### ISSUE TITLE
How to set header and footer in all pages

### ISSUE THREAD

**Issue by blacktrue** [puppeteer/puppeteer#4668]
Hi

I need a help for set header and footer in all pages but without overlaps with content

**Comment by aslushnikov** [comment]
Not sure we can help here given how little information is shared.

**Comment by nikhila-darisa** [comment]
![Image](https://github.com/user-attachments/assets/99f551b3-d248-4046-9f67-d04dab05086b)

      const pdf = await page?.pdf({
        format: "A4",
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: "<div/>",
        timeout: 0,
        footerTemplate: getPdfFooterTemplate(footerParams),
        margin: {
          top: "60px", // Adjust header space
          bottom: "60px", // Reserve space for footer
        },
        preferCSSPageSize: true,
      });

this is my footer 
export function getPdfFooterTemplate(footerParams) {
  const { patientId, defaultLayoutFriendlyName, barcodeData } = footerParams;
  const currentDate = () => {
    const d = new Date();
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    const year = d.getFullYear();
    return `${month}/${day}/${year}`;
  };

  const barcode = generateBarcode(barcodeData);
  return `
  <style>
   @page {  
   margin-bottom: 100px !important;
   }

   .footer-div{
   font-size: 8px;
    width: 100%;
   height: 90px
   }

  .barcodeWrapper {
    display: flex;
    flex-direction: row-reverse;
    margin-bottom: 12px;
  }

  .barcode {
    height: 16px;
    width: 100px;
  }

  .line {
    border-top: 1px solid #000;
    width: 100%;
    margin-bottom: 8px;
  }

  .content {
    display: flex;
    justify-content: space-between;
  }
</style>
<footer class="footer-div">
  <div class="barcodeWrapper">
    <img class="barcode" src="${barcode}" alt="barcode" />
  </div>

  <div class="line"></div>

  <div class="content">
    <div>${defaultLayoutFriendlyName} , Patient Id: ${patientId},</div>

    <div>
      <span>${currentDate()}</span>, Page
      <span class="pageNumber"></span> of <span class="totalPages"></span>
    </div>
  </div>
</footer>`;
}

the footer is overlapping withh content margin is effected but content is overlapping, please check the attached screenshot
