### ISSUE TITLE
Can't access tab opened after installing an extension

### ISSUE THREAD

**Issue by thiagocardoso1988** [puppeteer/puppeteer#4669]
Hi, I've opened this thread in [Github](https://stackoverflow.com/q/56873689/3781650), but this seems to be an issue really.

What happens is that I have an extension, where there is an event listener for the `onInstalled` event. There I opened a new tab to congratulate the user. Despite running it with `headless: false` and seeing the tab is opened, I can't access it.

I've tried to get it with `browser.pages` and `browser.target`, but with no success. I dunno if the page is opened in a separate thread (maybe) or something, because even if I add some sleep, just in case the process was too fast for it to be recognized, it still doesn't work.

**Comment by aslushnikov** [comment]
@thiagocardoso1988 can you create a github repo or something that reproduces this issue? It might be a bug in chromium.
