### ISSUE TITLE
convert argument to strings for page.type()

### ISSUE THREAD

**Issue by softwarezhu** [puppeteer/puppeteer#467]
If I pass an integer to `page.type()`, there will be an error: `TypeError: text[Symbol.iterator] is not a function`.
I think it's better to cast the argument to strings in `page.type()`

**Comment by aslushnikov** [comment]
Hey @softwarezhu, thanks for suggestion!

We'd rather not introduce polymorphic methods unless strictly necessary. Having strict types now might give us more flexibility to enhance API in future.
