### ISSUE TITLE
How to handle randomly occurring popup

### ISSUE THREAD

**Issue by michael-ziedalski** [puppeteer/puppeteer#4670]
**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Mac OS El Capitan (10.11.6)
* URLs (if applicable): https://www.glassdoor.com/Reviews/Microsoft-Reviews-E1651.htm
* Node.js version: 8.10.49

**What steps will reproduce the problem?**
Trying to scrape glassdoor company reviews, I realized that, if one is not logged in, and scrolls down to the bottom of the first review page and attempts to press the "next" button, an in-site popup will eventually appear stopping you and notifying you to log in.

What I would ideally like to do is create a function that

1. Reacts to the popup's `DOM` elements appearing, and interrupts the current action of the script
2. Performs some actions (such as logging in)
3. Returns back to the main body of the script, when it is done

`page.on` can [seemingly create](https://chercher.tech/puppeteer/alerts-puppeteer) functions that only "trigger" if the page throws something at the user. But how could I extend this to new DOM elements appearing?

**What is the expected result?**

The script will simply print some elements, proceed to press the "next button" found on the bottom of the page, wait a bit, and then print the next page's elements, and repeat the process a few times.

**What happens instead?**

The first page's elements get printed, the next button is pressed, but I start seeing "possible "EventEmitter memory leak detected", and my script halts/crashes as soon as the login popup appear.

Any guidance in helping me figure this out would be appreciated.

```
const puppeteer = require("puppeteer");
const cheerio = require('cheerio');


// puppeteer usage as normal
puppeteer.launch({ headless: false }).then(async browser => {

  const page = await browser.newPage();

  const navigationPromise = page.waitForNavigation();

  await page.setViewport({ width: 1440, height: 794 });

  var data = [];

  await page.goto('https://www.glassdoor.com/Reviews/Microsoft-Reviews-E1651.htm');

  // Trying to create loop that will, after scraping the current page,
  // go to the next page, scrape it, and repeat the process 10 times.
  for (let i = 0; i < 10; i++) {

    const html = await page.content();
    const $ = cheerio.load(html);

    // Iterating over all the reviews.
    $(".hreview").each(function( index ) {

      console.log("\nMain scraping function happening.");

      console.log($(this).find("span.summary").text());
      console.log($(this).find("time.date").text());
      console.log($(this).find("span.authorJobTitle.middle.reviewer").text());


      // Trying to press next button on botton of page, and wait for page to
      // fully load before proceeding with next set of scraping.
      Promise.all([
        page.waitForNavigation({ waitUntil: 'networkidle2' }),
        // page.click('#some-link')
        page.$eval('.pagination__ArrowStyle__nextArrow  ', elem => elem.click()),
        page.waitFor(5000)
        
        ]);


      });
  }

  await browser.close();

})
```

**Comment by LeMoussel** [comment]
I do not understand why you use cherio. Is not it possible to do it with Puppeteer APIs?

**Comment by michael-ziedalski** [comment]
Using cheerio was only a stylistic choice, before I learned puppeteer had jquery implemented so well, I could change easily. However, how could I still deal with randomly generated popups, and prepare actions for them?

**Comment by aslushnikov** [comment]
@michael-ziedalski you can use a combination of [`page.exposeFunction`](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-pageexposefunctionname-puppeteerfunction), [`page.evaluateOnNewDocument`](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-pageevaluateonnewdocumentpagefunction-args) and [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to build your own node.js events for appearing DOM dialogs.

As a shortcut, you can just use a [`page.waitForSelector`](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-pagewaitforselectorselector-options) method with infinite timeout to wait for the dialog to appear. Once it is there, you can proactively respond to it:


```js
page.waitForSelector('dialog-selector-whatever-it-is', {timeout: 0}).then(dialogHandle => {
  // click dialog?
  const ok = await dialogHandle.$('ok-selector');
  await ok.click();
});
```

Hope this helps.
