### ISSUE TITLE
puppeteer-core on lambda

### ISSUE THREAD

**Issue by elainema** [puppeteer/puppeteer#4672]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: "puppeteer-core": "^1.17.0"

* Platform / OS version:aws lambda
* URLs (if applicable):
* Node.js version:Nodejs 8.10

**What steps will reproduce the problem?**
npm install puppeteer-core

_Please include code that reproduces the issue._

```js
 const puppeteer = require('puppeteer-core');
const browserFetcher = puppeteer.createBrowserFetcher({path:'/tmp/'});
const revisionInfo = await browserFetcher.download('672088'); //the version is corresponding to puppeteer-core
const browser = await puppeteer.launch({
  ignoreHTTPSErrors: true,
  headless: true,
  devtools: false,
  args: ['--no-sandbox','--single-process'],
  executablePath: revisionInfo.executablePath //revisionInfo.executablePath
}).catch((e) => {
});
```
**What is the expected result?**
ge the the right browser 

**What happens instead?**
got null on aws lambda, works fine locally and on linux machine

It's quite grateful if somebody can help this, first i tried puppeteer , but the package is exceend the max limit of lambda(50MB),

**Comment by aslushnikov** [comment]
For AWS Lambda, please use [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda). That's maintained by Puppeteer community.

**Comment by dashmug** [comment]
@elainema Are you using a puppeteer Lambda layer with `puppeteer-core`?
