### ISSUE TITLE
Taking multiple screenshots in a for loop not working as expected

### ISSUE THREAD

**Issue by jbures** [puppeteer/puppeteer#4673]
Hi there, im having this weird issue with puppeteer...

I'm using it on the server side with nodejs, and calling and endpoint from the frontend to take a screenshot with a certain config...

The thing is, i define steps to take more than one screenshot over the same page, for example:

1 - Go to www.url.com
2 - Hover an element
3 - Take screenshoot
4 - Click on a button on the element
5 - Take screenshoot

I send this steps as an object with info like:
```
{
 0: { action: "hover", value: "element_class" }
 1: { action: "screenshot", value: "" }
}
```

Everything seems to work up to the point of getting two screenshots, but the thing is that the two screenshots only have the result of the final step, like it takes too long for some reason to get them and it kinda looks like the code is ignoring my await orders to take the screenshot...

So the loop where i take the screenshots look like this:

```
    if (Object.keys(config.steps).length) {
        Object.keys(config.steps).forEach(async (step) => {
            const action = config.steps[step].action;
            const value = config.steps[step].value;

            if (action === "HOVER") {
                await page.hover(`.${value}`);
                await page.waitFor(500);
            } else if (action === "CLICK") {
                await page.click(`.${value}`);
                await page.waitFor(500);
            } else if (action === "SCREENSHOT") {
                await page.screenshot(screenshotConfig);
            }
        })
    }
```

Can anyone help me get what's the problem here? I'm truly puzzled.

Thanks and kind regards.

**Comment by jbures** [comment]
Bump?

I can't figure out this... it's kind of random also, sometimes it works and gives me two screenshots and sometimes i always get the final state after all the steps in all screenshots :/

Ideas? any flags i can pass to the launcher to make it run slower or something?

I'm clueless...

**Comment by jbures** [comment]
If anyone finds this, the solution to my problem was changing forEach for a for...of 😅

**Comment by jonathancs** [comment]
boy,
sorry,
i don't know the answer.

but have you found some other way ?
