### ISSUE TITLE
Puppeteer in docker text rendering is different from puppeteer in local

### ISSUE THREAD

**Issue by manibharathytu** [puppeteer/puppeteer#4675]
I'm trying to measure the width of an HTML element. I'm getting different values in local puppeteer/chrome_headless and dockerized  puppeteer/chrome_headless.

Steps to reproduce :

1) Open chrome console and paste the below code. It will give the width of the element.

    var elem = document.createElement('span')
    document.body.appendChild(elem)
    elem.innerHTML="text to be measured for width"
    elem.style.fontSize="20px"
    elem.style.fontFamily="serif"
    console.log(a.getBoundingClientRect().width)

2) Run the following command to run headless chrome in docker.

docker run -it --rm -p=0.0.0.0:9222:9222  --name=chrome-headless -v /tmp/chromedata/:/data alpeware/chrome-headless-trunk

3) Access headless chrome running in docker through any browser at localhost:9222. Click the link shown. Now paste the same code in the console. The width it is giving is different.

I need the headless browser in docker to give the same result as the local chrome.

**Comment by aslushnikov** [comment]
> I need the headless browser in docker to give the same result as the local chrome.

Font rendering is very much OS-defined.  The only way to get pixel-perfect results when things include fonts is to run in the same docker container.

**Comment by manibharathytu** [comment]
@aslushnikov The OS is same (Ubuntu 16.04) in both cases (puppeteer in docker and puppeteer without docker). So I guess OS is not an issue

**Comment by raDiesle** [comment]
Sam issue here, using same docker container for chromium-puppeteer running from windows and running from ubuntu.

**Comment by raDiesle** [comment]
probably fonts are missing to copy to the image

**Comment by blinkcat** [comment]
> @aslushnikov The OS is same (Ubuntu 16.04) in both cases (puppeteer in docker and puppeteer without docker). So I guess OS is not an issue

I got same problem, any workaround?

**Comment by Pverma96** [comment]
@aslushnikov I am also encountering the same problem. Were you able to find a solution?

**Comment by shawnholmgren** [comment]
having the same issue. seems like some fonts don't ship with dockerized puppeteer using chromium
