### ISSUE TITLE
setDownloadBehavior issue

### ISSUE THREAD

**Issue by lumenier1** [puppeteer/puppeteer#4676]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^1.18.1
* Platform / OS version: Win 10
* Node.js version: v8.12.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run script
2. It fails

**Code:**

    const puppeteer = require('puppeteer');

    (async () => {
       const browser = await puppeteer.launch({
          executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
          defaultViewport: {
              width: 1920,
              height: 1080
          },
          headless: false,
          userDataDir: "./user_data"
       });

       const page = await browser.newPage();

       await page.goto(
         'https://example.com/page-with-the-file-link',
          { waitUntil: 'domcontentloaded' },
       );

       await page._client.send('Page.setDownloadBehavior', {
             behavior: 'allow',
             downloadPath: 'C:/Users/Me/Downloads/custom/folder/'
       });

       console.log('Start downloading');

       await page.click('a.download-btn');

       await page.waitFor(5000);

       console.log('Complete');
       await browser.close();
    })();

**What is the expected result?**

Catch "download complete" event and to make it work correctly.
Also I want to handle downloading status and monitor downloading proccess.

**What happens instead?**

    Start downloading
    Complete
    (node:51016) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
        at WebSocket.send (C:\Users\Me\Downloads\puppeteer\node_modules\ws\lib\websocket.js:329:19)
        at WebSocketTransport.send (C:\Users\Me\Downloads\puppeteer\node_modules\puppeteer\lib\WebSocketTransport.js:60:14)
        at Connection._rawSend (C:\Users\Me\Downloads\puppeteer\node_modules\puppeteer\lib\Connection.js:86:21)
        at Connection.send (C:\Users\Me\Downloads\puppeteer\node_modules\puppeteer\lib\Connection.js:72:21)
        at gracefullyCloseChrome (C:\Users\Me\Downloads\puppeteer\node_modules\puppeteer\lib\Launcher.js:194:20)
        at Browser.close (C:\Users\Me\Downloads\puppeteer\node_modules\puppeteer\lib\Browser.js:255:31)
        at Browser.<anonymous> (C:\Users\Me\Downloads\puppeteer\node_modules\puppeteer\lib\helper.js:112:23)
        at C:\Users\Me\Downloads\puppeteer\test-download-file.js:97:18
        at <anonymous>
    (node:51016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
    (node:51016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Script does not work properly during the execution. It exits right after clicking download link on the page  w/o waiting for 5 seconds and chrome puts downloaded file into default `'Downloads'` folder instead of defined `'downloadPath'` in the script.

**Comment by lumenier1** [comment]
### **How to get around this with crutches**

<a href="https://ibb.co/TMKJydq"><img src="https://i.ibb.co/HTNRZ3p/puppeteer-crutches.jpg" alt="puppeteer-crutches" border="0"></a>

**1) We should catch/wait for file which will appear in default `'Downloads'` directory**

    function checkExistsWithTimeout(filePath, timeout) {
        return new Promise(function (resolve, reject) {

            var timer = setTimeout(function () {
                watcher.close();
                reject(new Error('File did not exists and was not created during the timeout.'));
            }, timeout);

            fs.access(filePath, fs.constants.R_OK, function (err) {
                if (!err) {
                    clearTimeout(timer);
                    watcher.close();
                    resolve();
                }
            });

            var dir = path.dirname(filePath);
            var basename = path.basename(filePath);
            var watcher = fs.watch(dir, function (eventType, filename) {
                if (eventType === 'rename' && filename === basename) {
                    clearTimeout(timer);
                    watcher.close();
                    resolve();
                }
            });
        });
    }

**Check file just in case (optionally)**

    function checkFile(path) {
        return new Promise(function (resolve, reject) {
            fs.access(path, fs.F_OK, (err) => {
                if (err) {
                    reject(new Error(err));
                }
        
                //file exists
                console.log('File exists');
                resolve();
            });
        });
    }

**Move file wherever we need after download complete (optionally)**

    function moveFile(fromPath, toPath) {
        return new Promise(function (resolve, reject) {
            fs.rename(fromPath, toPath, function (err) {
                if (err) {
                    reject(new Error('File did not move.'));
                    throw err;
                } else {
                    console.log('File moved');
                    resolve();
                }
            });
        });
    }

**Example**

    const fileName = await page.evaluate(() => {
       return document.querySelector('.download-file-btn').textContent.trim();
    });
    await page.click('.download-file-btn');
    await checkExistsWithTimeout('C:/Users/Me/Downloads/'+fileName, 10000);
    await moveFile('C:/Users/Me/Downloads/'+fileName, 'C:/Users/me/Desktop/Videos/'+fileName);

**2) Donwload file from url using `'request'` package**

    function download(uri, filename, callback) {
        return new Promise(function (resolve, reject) {
            request.head(uri, function (err, res, body) {
                if (!err && res.statusCode == 200) {
                    console.log('content-type:', res.headers['content-type']);
                    console.log('content-length:', res.headers['content-length']);

                    request(uri)
                    .pipe(fs.createWriteStream(filename))
                    .on('error', function(response) {
                        console.log(err);
                        reject(new Error(err));
                    })
                    .on('close', function() {
                        callback();
                        resolve();
                    });
                } else {
                    reject(new Error(err));
                }
            });
        });
    }

**Example**

    const videoSrc = await page.evaluate(() => {
         return document.querySelector('video.vjs-tech').src;
    });

    await download(videoSrc, "C:/Users/Me/Downloads/Videos/video.mp4", function() {
       console.log('downloaded');
    });

--------

It works for me without `'setDownloadBehavior'` option, othervise it fails.
Now I can click download button or download file directly from some URL, just by manipulating with filesystem with node little bit.

Hope it will help somebody.

**Comment by aslushnikov** [comment]
> How to get around this with crutches

@lumenier1 Loved the logo.

Overall, this is another workaround for a long-awaited #299. Closing as a dupe.

**Comment by azazrehman** [comment]
If there is error on file which you want to download then try this one:

const myDownloadPath = path.resolve(${Directory Where you want to download})
mkdirp(myDownloadPath)
await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: myDownloadPath });

imported:
const mkdirp = require('mkdirp')
const path = require('path')

**Comment by vaknin** [comment]
March 2020 update: the error is still happening, even after using the solution @azazrehman proposed or using anything from #299

**Comment by SacDin** [comment]
Still same, download is not being triggered

**Comment by char101** [comment]
When chromium is downloading a file, it creates two files, `<filename>`, and `<filename>.crdownload`. It is not enough to just check for `<filename>`, you also need to check that `<filename>.crdownload` has been removed.

```javascript
await page._client.send('Page.setDownloadBehavior', {behavior: 'allow', downloadPath: tempDownloadDir});

// make sure tempDownloadDir is an empty directory
async function waitForDownload(tempDownloadDir, downloadDir) {
  let filename;
  while (!filename || filename.endsWith('.crdownload')) {
    filename = fs.readdirSync(tempDownloadDir)[0];
    await new Promise(resolve => setTimeout(resolve, 500));
  }
  if (filename !== undefined) {
    fs.renameSync(path.join(tempDownloadDir, filename), path.join(downloadDir, filename));
  }
  return filename;
};
```

**Comment by toyssamurai** [comment]
**Page.setDownloadBehavior** no longer works for me (07/21/2020). To work around, use **createCDPSession** to get a CDP Session, then do a **Browser.setDownloadBehavior**: 

```
const cdpsession = await page.target().createCDPSession();
cdpsession.send ("Browser.setDownloadBehavior", {behavior:"allow", downloadPath: " ... download path ..." });
```

I believe that it may have to do with **Page.setDownloadBehavior** being deprecated.

**Comment by KingRial** [comment]
> **Page.setDownloadBehavior** no longer works for me (07/21/2020). To work around, use **createCDPSession** to get a CDP Session, then do a **Browser.setDownloadBehavior**:
> 
> ```
> const cdpsession = await page.target().createCDPSession();
> cdpsession.send ("Browser.setDownloadBehavior", {behavior:"allow", downloadPath: " ... download path ..." });
> ```
> 
> I believe that it may have to do with **Page.setDownloadBehavior** being deprecated.

I can confirm the problem.
Seems puppeteer 5.2.1 is no more working even with "CDP Session" solution (Every time I try to launch the download, it fails)

**Comment by amunim** [comment]
I'm also getting download error, is there any way to download files by clicking?

I've tried both, `Broswer.set...` and `Page.set...` none of them gets the job done.

**EDIT: ** to save someone's hour, the problem is that on windows you have to use path like this "D:\\my\\folder" instead of "./savepath"

**Comment by AgainPsychoX** [comment]
Can confirm, here my usage:
```js
import { win32 } from 'node:path';
//...
const options = { output: './output' };
//...
const cdpSession = await page.target().createCDPSession();
cdpSession.send('Browser.setDownloadBehavior', {
    behavior: 'allow', 
    downloadPath: win32.resolve(win32.normalize(options.output))
});
//cdpSession.detach(); // later?

```
