### ISSUE TITLE
I get a 404 error when I am connecting to the page

### ISSUE THREAD

**Issue by edkazcarlson** [puppeteer/puppeteer#4680]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Windows 10
* URLs (if applicable): any pixiv illustration page, https://www.pixiv.net/member_illust.php?mode=medium&illust_id=xxxxxxx
* Node.js version: 10.16.0

**What steps will reproduce the problem?**
Whenever I try to access an illustration page on pixiv I get a
Failed to load resource: the server responded with a status of 404 ()
faild
message even though when I do 	
```js
let result = await page.goto(imgPageURL);
	console.log("result: " + result.status());
```
it says that I have a 200 error code
_Please include code that reproduces the issue._
```js
async function logIn(browser, page){
	if (fs.existsSync(cookiesFilePath)) {
	} else {
		fs.writeFile(cookiesFilePath, '', function (err) {
			if (err) throw err;
				console.log('File is created successfully.');
			});  
	}
	let firstTime = true;
	loginCookies = fs.existsSync(cookiesFilePath);
	if (loginCookies){
		const content = fs.readFileSync(cookiesFilePath);
		const cookiesArr = JSON.parse(content);
		if (cookiesArr.length !== 0) {
			for (let cookie of cookiesArr) {
				await page.setCookie(cookie);
		}
		}
	}
	await page.goto(loginUrl);
	//await page.waitForNavigation();
	while (page.url() != pixivUrl){ //while not logged in
		if (!firstTime){
			console.log("Failed to log in");
		}
		firstTime = false;
		let username = readline.question("What is your username?");
		let logPass = readline.question("What is your password?");
		const usernameField = await page.$x(usernameXpath);
		await usernameField[0].type(username);
		const passwordField = await page.$x(passwordXpath);
		await passwordField[0].type(logPass);
		page.evaluate(() => { document.querySelector("#LoginComponent > form > button").click(); });
		await page.waitForNavigation({ waitUntil: 'networkidle0' });
	} 
	console.log("Logged in");

	// Write Cookies
	const cookiesObject = await page.cookies();
	fs.writeFileSync(cookiesFilePath, JSON.stringify(cookiesObject));
	console.log('Session has been saved to ' + cookiesFilePath);
}

async function checkImage(browser, page, filter, imgPageURL, fArgs){
	console.log("entered checkImage");
	await page.waitFor(1000);
	let result = await page.goto(imgPageURL);
	console.log("result: " + result.status());
}

async function biggerThanFilter(browser, page, isSingle, xReq, yReq){}

(async() => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await logIn(browser, page);
	page.on('console', consoleObj => console.log(consoleObj.text()));
	await page.screenshot({path: 'new.png', fullPage: true});
	await checkImage(browser, page, biggerThanFilter, "https://www.pixiv.net/member_illust.php?mode=medium&illust_id=75457374", [1,1] );
	console.log("end");
	await browser.close();
})();
```

**What is the expected result?**
That I do not get a 404 error and have the page still load

**What happens instead?**
I get a 404 error but the page still loads

**Comment by aslushnikov** [comment]
This seems to be a problem with the way you automate the site - not with Puppeteer per se.
If you do believe this is a problem with Puppeteer, please file a new issue with a small reproduction script that we can safely run locally.

Thanks!

**Comment by atorrese** [comment]
this code , the  errors 404``
``
const puppeteer = require('puppeteer');
const fs = require('fs'); 

(async ()=>{
    const browser = await puppeteer.launch({ headless: false, args: ['--start-maximized'] });
    const page = await browser.newPage();
    
    await page.setDefaultNavigationTimeout(0);
    await page.setViewport({ width: 1296, height: 800 });
    await page.goto('https://www.fybeca.com/FybecaWeb/pages/home.jsf');
    await page.waitForSelector('[id="container-result"]');

    const categorias = await page.evaluate(()=>{
        const elements = document.querySelectorAll('li.dd');
        const c = document.querySelector('li.dd > div.dd-menu > div.row-fluid ,ul.nav-list ').querySelectorAll('div.span4 , div.span3 , div.span6, li.more-category');
        for (let [index,element] of elements.entries()){
            if(index!=1){
                console.log(element.firstElementChild.innerText); //name
                console.log(element.lastElementChild.firstElementChild.firstElementChild.firstElementChild);
                //console.log(element);
            }
        }
    });


})();
