### ISSUE TITLE
Is it possible to launch puppeteer from within a browser?

### ISSUE THREAD

**Issue by celynjacobs** [puppeteer/puppeteer#4682]
Puppeteer version: Latest
Platform / OS version:  Windows 10
Node.js version: 10.16.0

Hello! I'm working on a web application which scrapes a website using puppeteer and cheerio. I have the local version running fine, but when I bundle the app and use it as the "src" in the HTML for a local server, it throws errors pointing me to the "puppeteer.launch" call. I can go into more detail, but I suspect the issue is that I am trying to launch puppeteer from within an existing browser. 

Is that something that I am able to do with puppeteer? I discovered puppeteer.connect in my research, but it doesn't seem like that would fit my needs for an automatic scraping application which scrapes a website for certain data based on the user's input. 

I apologize for asking a question which may not be an issue with puppeteer itself, but there isn't an appropriate place for me to ask on stackoverflow (my question was marked as off-topic there), and I can't find the answer anywhere else. 

Thank you for any suggestions you have! Again, sorry for the bother. <3

**Comment by aslushnikov** [comment]
> Is that something that I am able to do with puppeteer?

@celynjacobs No, you can't launch a browser from-within a browser. This would be a huge security vulnerability, making the whole web a very unsafe thing :-) 

So please stick to the node.js if you want to launch browsers! 

> I apologize for asking a question which may not be an issue with puppeteer itself, but there isn't an appropriate place for me to ask on stackoverflow (my question was marked as off-topic there), and I can't find the answer anywhere else.

No worries, this is a right place to ask questions!

Cheers!

**Comment by celynjacobs** [comment]
@aslushnikov thanks for letting me know! Is there any way then to make a web app in Javascript that can automatically click a button on a website (as opposed to simply scraping the html) when a user inputs the target URL? Again, sorry to bother you!

**Comment by radiantone** [comment]
> > Is that something that I am able to do with puppeteer?
> 
> @celynjacobs No, you can't launch a browser from-within a browser. This would be a huge security vulnerability, making the whole web a very unsafe thing :-)
> 
> So please stick to the node.js if you want to launch browsers!
> 
> > I apologize for asking a question which may not be an issue with puppeteer itself, but there isn't an appropriate place for me to ask on stackoverflow (my question was marked as off-topic there), and I can't find the answer anywhere else.
> 
> No worries, this is a right place to ask questions!
> 
> Cheers!

Not to revive an ancient ticket, but I was also looking into this and I think you completely missed the intention here. The need is not to "launch a browser from within a browser". The need is for a "high level" javascript API to control a web app or web page "as a user would". We can already do this with javascript of course from a different iframe (same origin) but its not easy, its not high level and why re-invent the wheel?

If puppeteer could be installed via npm and bundled into a webapp (e.g. as an instrumented test automation version for example), where it can auto-pilot the webapp or web pages, that would be a very useful thing in line with what puppeteer is 98% already doing.
