### ISSUE TITLE
Should convert selectors to string via `toString`

### ISSUE THREAD

**Issue by futpib** [puppeteer/puppeteer#4683]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Arch Linux	
* URLs (if applicable):
* Node.js version: v8.16.0

**What steps will reproduce the problem?**

```js
const puppeteer = require('puppeteer');

class Selector {
	constructor(parts = []) {
		this.parts = parts;
	}

	toString() {
		return this.parts.join(' > ');
	}
}

const searchSelector = new Selector(['#search-input', 'input']);

(async () => {
	const browser = await puppeteer.launch({ args: [ '--no-sandbox', '--disable-setuid-sandbox'] });
	const page = await browser.newPage();
	await page.goto('https://www.wikipedia.org/');

	await page.type(searchSelector, 'puppeteer'); // '[object Object]' is not a valid selector.
})();
```

1. Paste the code above into a `node` shell
2. Witness the error

**What is the expected result?**

Selector is coerced to string before executing it, for example via `String(selector)`.

Alternatively, puppeteer could support a custom `toSelectorString` (or similar) method for the objects convertible to selectors.

**What happens instead?**

Selector is send to the browser as an object which results in an error.

**Comment by aslushnikov** [comment]
Hey @futpib, thanks for filing!

> Selector is coerced to string before executing it, for example via String(selector).

IMO implicit conversions make it harder to follow the code unless there's before-hand knowledge of library internals. I'd rather not do this.

> Alternatively, puppeteer could support a custom toSelectorString (or similar) method for the objects convertible to selectors.

I don't think we should bring any of these conventions unless they solve some big problems. In this case, clients could've simply called a method on the selector class:

```js
await page.type(searchSelector.get(), 'puppeteer');
```
