### ISSUE TITLE
Can't upload file via .uploadFile(filepath)

### ISSUE THREAD

**Issue by Somberor** [puppeteer/puppeteer#4685]
**Tell us about your environment:**

* Puppeteer version:  Latest
* Platform / OS version: Windows 10
* URLs (if applicable): instagram.com
* Node.js version: v8.11.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. let filePath = 'test.png';
        let fileInput = await this.page.$('.Q9en_ input');
        await fileInput.uploadFile(filePath);
(the file test.png is in the same directory as the js file , I also tried full path and the result is the same)

**What is the expected result?**

Upload the image to the hidden form on the website.

**What happens instead?**

The page was refreshed back to homepage and the file was not uploaded

Please help me guys

**Comment by aslushnikov** [comment]
We're not automating any particular websites here - Puppeteer issues host discussions regarding Puppeteer misbehaviors.
