### ISSUE TITLE
Feature Request: ignore/blackout region while taking a screenshot

### ISSUE THREAD

**Issue by zgudlin** [puppeteer/puppeteer#4686]
Are there any plans to include a way to ignore or blackout a region before taking a screenshot? For example, if there is a UI I am building and I want to use some sort of image comparison tool, but do not want to concern myself with with the ticking clock on the page, it would be helpful to be able to select that element or region to be ignored or blacked out before the screenshot is saved, instead of having to manipulate it afterward. I know there is a way to [clip a region of the page ](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-pagescreenshotoptions) to be saved as a screenshot, but I am essentially looking for the reverse of that feature: clipping a section to be _ignored_ in the screenshot. I appreciate any responses/suggestions for a workaround. It would be nice not to have to use an additional tool outside of my Puppeteer test to edit the screenshots I take. Thank you!

**Comment by zgudlin** [comment]
I was looking at [Cypress](https://docs.cypress.io/api/commands/screenshot.html#Arguments) and how they take screenshots. One of the options they provide is to black out a region in addition to clipping. I think it would be nice to able to do this in Puppeteer as it has some other strengths over Cypress.

**Comment by aslushnikov** [comment]
>  if there is a UI I am building and I want to use some sort of image comparison tool, but do not want to concern myself with with the ticking clock on the page, it would be helpful to be able to select that element or region to be ignored or blacked out before the screenshot is saved

A few things come to mind:
- you can set `visibility: hidden` css property for the element you don't like
- you can put big black absolutely positioned `<div>` elements atop of the areas of the page you don't want to see. This is an identical functionality to "blackout a region" feature request you ask for.

> One of the options they provide is to black out a region in addition to clipping.

This is nice to know, thank you! This makes a lot of sense for a testing-oriented framework. In Puppeteer, this is quite easy to polyfill, so I think this functionality should live in an external module.

**Comment by zgudlin** [comment]
@aslushnikov Thank you for the response. Are you saying I should set the visibility in the css file itself, or is there a way to access the css properties and set them via a Puppeteer function? I have not been able to find anything that speaks to that.  The goal is not to have to manipulate the file, rather just "temporarily" change the visibility within the Puppeteer test case, removing the need to modify external files and keep changing them for other test cases those areas to remain visible.

**Comment by aslushnikov** [comment]
> Are you saying I should set the visibility in the css file itself, or is there a way to access the css properties and set them via a Puppeteer function? 

@zgudlin I'd suggest using something like this:

```js
// Consider the element to hide is `.watch`
await page.$eval('.watch', watchElement => watchElement.style.setProperty('visibility', 'hidden'));
```

**Comment by zgudlin** [comment]
@aslushnikov Thank you, that worked great!
