### ISSUE TITLE
"npm install puppeteer" hangs indefinitely with no error

### ISSUE THREAD

**Issue by Gaibhne** [puppeteer/puppeteer#4688]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
(latest)

* Platform / OS version:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

* Node.js version:
v10.16.0

**What steps will reproduce the problem?**
npm install puppeteer

_Please include code that reproduces the issue._

1. npm install puppeteer

**What is the expected result?**
Puppeteer being installed

**What happens instead?**
Nothing. The install continues this far, and then hangs there forever:

    npm sill doSerial global-link 10
    npm sill doParallel update-linked 0
    npm sill doSerial install 10
    npm sill install puppeteer@1.18.1
    npm info lifecycle puppeteer@1.18.1~install: puppeteer@1.18.1

    > puppeteer@1.18.1 install /directory/node_modules/puppeteer
    > node install.js

    Downloading Chromium r672088 - 112.1 Mb [====================] 99% 0.0s

**Comment by aslushnikov** [comment]
@Gaibhne Are you sure it hangs? Did you try attaching `strace` and see where it actually hangs?

**Comment by Gaibhne** [comment]
I left it on over night (~14 hours) so I'm quite confident that it did indeed hang. I did not try that, since I don't know that tool or how to use it. I'll see if I can work it out with Google and report back if I can make anything of the result.

**Comment by aslushnikov** [comment]
> I left it on over night (~14 hours) 

That's a long night :-) 

I wonder if there's an exception somewhere (OOM?) that resulted in installation termination. 

> I'll see if I can work it out with Google and report back if I can make anything of the result.

Thanks!

**Comment by Gaibhne** [comment]
I'm afraid that whatever caused this issue has gone away. Whether it was a change to my VM or something to do with the server hosting the files I can't say.

Unfortunately I did a lot more debugging in the hopes of getting it to work and something somewhere fixed it, but as I was at the time testing something else (the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` flag did not work in older `npm` versions) I didn't notice at the time. Attempts at restoring the state where it bugs out were unsuccessful.

Should I manage to find a way to reproduce the problem, I will reopen this issue with more details. Sorry :(
