### ISSUE TITLE
how to check if embeds are finished rendering

### ISSUE THREAD

**Issue by ericmulder** [puppeteer/puppeteer#4689]
I'm running a visual compare before and after a plugin update to see if the update messes the site up. Problem is that currently taking a screenshot several times produces different screenshot for embeds from youtube and twitter. I'm not sure if this is due to not unfinished rendering loading  of the iframe / javascript inserted html embed (twitter), or that the embeds are sometimes rendering differently.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Mac os X
* URLs (if applicable): https://nllabe-pricedale.savviihq.com
* Node.js version: node v10.16.0 (npm v6.9.0)

**What steps will reproduce the problem?**

1.  Take a screenshot
2. Take another screenshot
3. Compare both screenshots

```js
describe('👀 screenshots are correct', function () {
    let browser, page;

    // This is ran before every test. It's where you start a clean browser.
    // --no-sandbox for ubuntu
    // --disable-features=site-per-process to fully load iframes?
    beforeEach(async function () {
        browser = await puppeteer.launch({
            args: ['--no-sandbox --disable-features=site-per-process'],
            headless: true
        });
        page = await browser.newPage();


    });

    // This is ran after every test; clean up after your browser.
    afterEach(() => browser.close());

    //lets run this 100 times! use mocha --bail
    for (let t = 0; t <= 100; t++) {
        describe("screens attempt " + t, function () {
            this.timeout(10000) // all tests in this suite get 10 seconds before timeout
            this.bail = true;
            it("takes a screenshot (no " + t + ") - " + (t % 2), async function () {
                // page.setViewport(viewport);
                width = 320;
                height = 680;
                await page.setViewport({width: width, height: height});

                return takeAndCompareScreenshot(page, t);
            });
        });
    }

});

// - page is a reference to the Puppeteer page.
// - route is the path you're loading, which I'm using to name the file.
async function takeAndCompareScreenshot(page, t) {
    // If you didn't specify a file, use the name of the route.
    let fileName = (t % 2 != 0) ? 'other-screenshot' : 'that-screenshot';

    // Start the browser, go to that page, and take a screenshot.
    await page.goto("https://nllabe-pricedale.savviihq.com", {
        waitUntil: 'networkidle0'
    });

    await page.screenshot({path: `${fileName}.png`, fullPage: true});
    if (t % 2 != 0) {
        // Test to see if it's right.
        return compareScreenshots(fileName);
    } else {
        return;
    }
}
```

**What is the expected result?**

No pixel differences

**What happens instead?**

Small differences in embeds. (see screenshots)

[first screenshot](https://user-images.githubusercontent.com/1086002/60948927-5b5c3400-a2f4-11e9-936a-1941d8f40c33.png)

[second screenshot](https://user-images.githubusercontent.com/1086002/60948930-5bf4ca80-a2f4-11e9-804f-29f4a902ca42.png)

[diff](https://user-images.githubusercontent.com/1086002/60948928-5bf4ca80-a2f4-11e9-891b-3233ac29c0cc.png)

**Comment by aslushnikov** [comment]
>  I'm not sure if this is due to not unfinished rendering loading of the iframe / javascript inserted html embed (twitter), or that the embeds are sometimes rendering differently.

@ericmulder I believe in your particular case the difference is due to progressive loading techniques that Twitter uses to load/decode images. I'm not aware how these things work under the hood in Twitter - so I don't think I can help much. One thing that you might try doing is to use [request interception](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-pagesetrequestinterceptionvalue) to abort requests to twitter embed.

In general, there's no silver bullet - webpages behave unpredictable and might change in any moment. Pixel-perfect screenshots are only possible in a fully deterministic environments - which is not the case for you here since you rely on many third-parties.

**Comment by ericmulder** [comment]
Thanks! I was also thinking about injecting some css to overlay those embed area's so it won't affect the view height.
