### ISSUE TITLE
Request headers missing after page.setRequestInterceptionEnabled(true)

### ISSUE THREAD

**Issue by jose-brandao** [puppeteer/puppeteer#469]
If I set `page.setRequestInterceptionEnabled(true);` some request headers disappear.
Consider the following code:

``` javascript
(async() => {

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.emulate(devices['iPhone 6']);

    //await page.setRequestInterceptionEnabled(true);
    page.on('request', request => {
        //request.continue();
        console.log("URL: " + request.url);
        console.log("METHOD: " + request.method);
        console.log("HEADERS:" + JSON.stringify([...request.headers]) + "\n");
    });

    await page.goto('https://github.com/GoogleChrome/puppeteer', {waitUntil: 'networkidle'});
    browser.close();
})();
```

As sample, the first POST request catched :
```
URL: https://www.google-analytics.com/r/collect
METHOD: POST
HEADERS:[
    ["Cache-Control","max-age=0"],
    ["Origin","https://github.com"],
    ["Referer","https://github.com/GoogleChrome/puppeteer"],
    ["User-Agent","Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"],
    ["Content-Type","text/plain;charset=UTF-8"]
]
```

If I uncomment `await page.setRequestInterceptionEnabled(true);` and `request.continue();` the same request misses **Referer** header:

```
URL: https://www.google-analytics.com/r/collect
METHOD: POST
HEADERS:[
    ["Cache-Control","max-age=0"],
    ["Origin","https://github.com"],
    ["User-Agent","Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"],
    ["Content-Type","text/plain;charset=UTF-8"],["Accept","*/*"]
]
```

This also happens for all the other requests. That I have notice only referer is missing. 
Is this supposed to happen ?

**Comment by aslushnikov** [comment]
That's right. Requests are created from different payloads depending whether the interception is enabled:
- Without interception, we emit requests based on renderer notifications. Renderer doesn't know about "Referer".
- With interception, we emit requests based on browser notifications. Browser is the one who injects the "Referer" header, so it has the "referer" header.

Does this bite you somewhere?

**Comment by twalpole** [comment]
@aslushnikov This prevents proper testing of apps, since if you want to block/allow specific requests (Poltergeist whitelist/blacklist for instance) then the 'Referer' header is lost, preventing normal app behavior (redirect back, etc)

Note: The 'Referer' header disappears when interception is turned on - you specified it the other way in your description.

**Comment by jose-brandao** [comment]
I agree with @twalpole. If you want to block some requests that doesn't matter, you end up losing information about the ones that are important. 

Also, by the documentation I tought that requests content would only change if I overwrite something.

**Comment by andrewlinfoot** [comment]
I think this might be related. I have a site I am trying to scrape that uses a redirect on their authentication route. It sends a POST request with the credentials, checks them and then does a 302 redirect with the set-cookie header containing the new session cookie.

With setRequestInterceptionEnabled the cookie is never set. Therefore when the scraper is redirected to the internal page of the app, it fails the cookie validation and is redirected back to the login page. This makes it impossible to scrape the site.

**Comment by iEricKoh** [comment]
@andrewlinfoot I have the same issue with you. Unfortunately, the site still redirect me to their login page even I disable the setRequestInterceptionEnabled. 
It works totally fine during my local development, but after I try to run the scraping script on a server, we always got redirect, seems like a IP related issues  : (

**Comment by aslushnikov** [comment]
@andrewlinfoot would you mind filing an new issue that has your script and the URL you try to scrape?

The `setRequestInterceptionEnabled` should not affect cookies.

**Comment by sdeprez** [comment]
+1. I have the same issue, the Referer header is stripped when the request interception is turned on. That prevents the analysis of certain websites whose server relies on the presence of this Referer. At the very least, it should be documented because right now that's really a confusing behavior. Also, since I guess it's probably a Chromium bug, I filed this bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=777392

**Comment by twalpole** [comment]
Note that `page.authenticate` behind the scenes enables request interception.  So if you ever set `page.authenticate` and don't reset it to null, request interception will be enabled (even if the user calls `page.setRequestInterceptionEnabled(false)`) and the Referer header will be stripped

**Comment by vhain** [comment]
+1 to @twalpole comment.
I was using `page.authenticate` to provide proxy authentication credentials but this was stripping out some crucial headers such as `Referer`, `Accept-Encoding` and so on.

I updated my code to set `page.authenticate` back to `null` after proxy authentication like below:
```javascript
...

const browser = await puppeteer.launch({
  args: ['--proxy-server=proxy.com:8080']
});

const page = await browser.newPage();

// proxy authenticate (will enable request interception)
await page.authenticate({ username: 'foo', password: 'bar' });

// trigger proxy authentication
await page.goto('https://www.google.com');

// reset authenticate to null (disable request interception)
await page.authenticate(null);

...
```

**Comment by Glennvd** [comment]
@andrewlinfoot could it be that your issue is more related to https://github.com/GoogleChrome/puppeteer/issues/1664? I'm not sure if the 2 issues originate from the same problem or are just similar, but both of them are blocking issues for me right now. Is there anything I can do to help and get the ball rolling?

**Comment by Glennvd** [comment]
Fixed in the master upstream yesterday (https://bugs.chromium.org/p/chromium/issues/detail?id=777392)

**Comment by Ndragomirov** [comment]
Cookie header is also missing if setRequestInterception is enabled

```js
var puppeteer = require('puppeteer');

(async() => {

    const browser = await puppeteer.launch({headless: true});
    const page = await browser.newPage();

    await page.setRequestInterception(true);
    page.on('request', request => {
        console.log('cookie', request.headers().cookie);
        request.continue();
    });

    await page.goto('https://github.com/GoogleChrome/puppeteer', {waitUntil: 'networkidle2'});

    await page.evaluate(()=>{
        var date = new Date(new Date().getTime() + 60 * 1000);
        document.cookie = "foo=bar; path=/; expires=" + date.toUTCString();
    })
    await page.reload({waitUntil: 'networkidle2'});

    browser.close();
})();
```
Outputs: 
```
cookie undefined
cookie undefined
cookie undefined
cookie undefined
cookie undefined
cookie undefined
cookie undefined
cookie undefined
```

**Comment by aslushnikov** [comment]
Referer is no longer stripped from headers with request interception.

@Ndragomirov i can't see any change with your script with/without request interception. I'll close this for now; feel free to file another issue if you think there's a problem.

**Comment by vinay-jtc** [comment]
I am enabled to access the Cookie in request header if `await page.setRequestInterception(true)`. 
@Ndragomirov @aslushnikov @andrewlinfoot   Can you help me with this?

var puppeteer = require('puppeteer');

(async() => {

   ```
const browser = await puppeteer.launch({ slowMo: 20,
    args: ['--enable-features=NetworkService','--disable-setuid-sandbox','--no-sandbox',],
    headless: false,
  });
  let page = await browser.newPage();

  await page.goto('https://example.com/);
  await page.waitForSelector("input[name='username']");
  await page.type("input[name='username']",'tok_sandbox_knkjdq',);
  await page.keyboard.press('Tab');
  await page.type("input[name='password']",'tok_sandbox_so,ldmkdw',);

  await page.setRequestInterception(true);

  page.on('request', async (interceptedRequest) => {
      const tunnelingAgent = tunnel.httpsOverHttp({vgs outbound tunnel});

      const options = {
        uri: interceptedRequest.url(),
        method: interceptedRequest.method(),
        headers: interceptedRequest.headers(),
        agent: tunnelingAgent,
        body: interceptedRequest.postData(),
      };

      console.log(interceptedRequest.headers().cookie); // Not able to  access cookie in request header
  
      const res = await request(options, function (err, resp, body) {
        if (err) {console.log(err);}
        interceptedRequest.respond({
          contentType: resp.headers['content-type'],
          headers: resp.headers,
          body: body,
        });
      });
    }else {interceptedRequest.continue();}
  });
  await page.keyboard.press('Enter');

```
})();
