### ISSUE TITLE
Page.mouse.move() doesn't work in headless mode?

### ISSUE THREAD

**Issue by xcurveballx** [puppeteer/puppeteer#4690]
* Puppeteer version: 1.18.1
* Platform / OS version: Win64
* URLs (if applicable): -
* Node.js version: 8.11.2

**What steps will reproduce the problem?**

I am testing a tooltip plugin for webpages. In one of the cases the tooltip should follow the cursor/mouse moves along x-axis. My plugin tracks the mouse moves and then moves the tooltip accordingly. It works with `headless: false`, I see all that in action. But when I switch to headless mode it seems that moves don't happen and the tooltip position remains the same.

```js
        await page.goto(url);
        await page.waitForSelector(".example5 a"); // it's the element around which the tooltip will appear
        await page.hover(".example5 a");

        let initialTtPosLeft = parseFloat(await page.evaluate(() => document.querySelector(".example5 span.js-tooltiper").style.left)); // I take initial tooltip left pos.

        let link = await page.$('.example5 a'); // I take element's coords to use them to move the mouse later
        let linkPos = await page.evaluate((link) => {
            const {top, left} = link.getBoundingClientRect();
            return {top, left};
        }, link);

        await page.mouse.move(linkPos.left + 5, linkPos.top + 5); // I move the mouse over the element. +5 just to not go beyond element's limits.

        let finalTtPosLeft = parseFloat(await page.evaluate(() => document.querySelector(".example5 span.js-tooltiper").style.left)); // I take again tooltip's left pos

        assert.notEqual(initialTtPosLeft, finalTtPosLeft); // In headless mode they are equal as if mouse.move didn't happen
```

**What is the expected result?**

The mouse moves and triggers the tooltip moving.

**What happens instead?**

Seems that in headless mode it doesn't happen since the tooltip position remains the same.

**Comment by aslushnikov** [comment]
> Page.mouse.move() doesn't work in headless mode?

@xcurveballx mouse *does* work in headless mode. I think the behavior you describe here is somehow related to your plugin code rather than chrome headless. Maybe you have some race conditions there? 

Can you build a small script that demonstrates the problem on the puppeteer side rather than in your plugin code?

**Comment by derrekyoung** [comment]
We're seeing some strange behavior in my scripts. We want to simulate mouse movement and have that be shown in the script. We're using some math to create the cursor tracking between 2 sets of X/Y coordinates.

When emulating a mobile device, the coordinates become more and more "off", especially when scrolling is involved.

**Comment by haochenli** [comment]
I encounter the same problem that I  simulate a drag event with page.mouse.down() and page.mouse.move() and page.mouse.up(). It's work in {headless: false} mode but not in the {headless: true} mode......
I spent the whole day and figure out that add ```page.setViewport({ width: xxx, height:  xxx });``` before simulating the mouse event will solve my problem.

**Comment by gtsigner** [comment]
I encounter the same problem that I simulate a drag event with page.mouse.down() and page.mouse.move() and page.mouse.up(). It's work in {headless: false} mode but not in the {headless: true} mode

**Comment by devolegua** [comment]
I have the same problem.
I tried to move google map to trigger data update (on my web app). It worked well when `{headless: false}` but didn't work when `{headless: true}`.

**Comment by olehdevua** [comment]
I have the same problem.
I tried to move google map to trigger data update (on web app). It worked well when `{headless: false}` but didn't work when `{headless: true}`.

**Comment by haochenli** [comment]
Guys, have you `page.setViewport({ width: xxx, height: xxx }); ` in headless mode ?

**Comment by roeniss** [comment]
@haochenli  this saved me! even in headless mode, it worked well.

one another thing: I was confused with *coordinates*. I mean:
`await page.mouse.click(38, 710);` - when this not worked,
`await page.mouse.click(710, 38);` - this worked.

So, check coordinates be right.
