### ISSUE TITLE
Why no  execute  console.log in callback of the $$eval()

### ISSUE THREAD

**Issue by junjie-lean** [puppeteer/puppeteer#4693]
Why no  execute  console.log in callback of the $$eval()?
为什么在$$eval的回调函数中，不能console.log呢？

**Comment by JoelEinbinder** [comment]
the callback of $$eval is executed in your page in Chromium. The console logs appear there. You can listen for them and forward them to node with [`page.on('console')`](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-event-console)
