### ISSUE TITLE
page.content() missing

### ISSUE THREAD

**Issue by jeandat** [puppeteer/puppeteer#470]
In the current documentation we can find [page.content()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagecontent) but it is not available in 0.9 release.

Did I missed it ?

**Comment by vsemozhetbyt** [comment]
@jdat82 The docs are in sync with the master branch status quo. You can install this tip-of-tree in this way:
```
npm install https://github.com/GoogleChrome/puppeteer/
```

**Comment by jeandat** [comment]
Ok, my bad, good to know. Thanks.
