### ISSUE TITLE
request.continue does not work - causes a timeout

### ISSUE THREAD

**Issue by TomasHubelbauer** [puppeteer/puppeteer#4702]
* Puppeteer version: 1.18.1
* Platform / OS version: Windows 10
* URLs (if applicable): https://bazos.cz
* Node.js version: 11.3.0

I have a repository where adding these lines causes the script to go from working to timing out:

```js
await page.setRequestInterception(true);
page.on('request', request => {
  console.log(request.url());
  request.continue();
});
```

The repro is here: https://github.com/TomasHubelbauer/bazos-puppeteer-scraper

I would like to remove advertisements at network level (see my comment in #4584) because removing them as the elements show up causes a jump in the content which is visually disturbing.

The interception doesn't work though. No URLs appear in the console and the page times out.

**Comment by aslushnikov** [comment]
@TomasHubelbauer so the following works fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', request => {
    console.log(request.url());
    request.continue();
  });
  await page.goto('https://bazos.cz');
  await browser.close();
})();
```

Can you please show a similarly-minimalistic script that reproduces the problem?

**Comment by TomasHubelbauer** [comment]
It stopped happening by itself without any changes. Maybe I was getting throttled by Bazos.
