### ISSUE TITLE
Struggling with parallel pages

### ISSUE THREAD

**Issue by icarusmiles** [puppeteer/puppeteer#471]
I first I thought I had this functioning, but after making some more complex requests I noticed the pages are not being ran in parallel, rather queued in order.

I am unsure if Puppeteer will allow parallel processing, where clicks/typing, etc. can all be done concurrently. (3-6 sites at once).

This is a test I am working with, I've tried multiple things. However cannot get this to run in parallel. 

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  for(let i = 0; i < 10; i++){
    console.log('Page ID Spawned', i)
    const page = await browser.newPage();
    await page.goto('https://www.example.com/');
    await page.screenshot({path: '../images/result' + i + '.png'})
  }

  browser.close();
});
```

**Comment by icarusmiles** [comment]
So, another one of my examples is using `Promises.all`, which seems to spawn all the page processes at the same time. However only performs 1 and returns a 30,000 ms exceed error, is that internal issue or if I threw better specs at my server would I be able to do that process concurrently?

**Comment by twalpole** [comment]
By using async/await the way you do in your first attempt you are making all your actions synchronous, so each `page` is waiting for the previous to finish.  To run them in parallel you need each page to return its own promise and then wait for each of those.  Something along the lines of (untested code)

```
   const puppeteer = require('puppeteer');

    puppeteer.launch().then(async browser => {
      const promises=[];
      for(let i = 0; i < 10; i++){
        console.log('Page ID Spawned', i)
        promises.push(browser.newPage().then(async page => {
          await page.goto('https://www.example.com/');
          await page.screenshot({path: '../images/result' + i + '.png'});
        }))
      }
      await Promise.all(promises)
      browser.close();
    });
```

**Comment by icarusmiles** [comment]
@twalpole - Yeah that's about what I have now. However I am unsure if it's my cheapo VPS or an internal issue, but doing this causes `Page crashed!` errors. They are being spawned concurrently, but seem to be conflicting or too much resources.

**Comment by icarusmiles** [comment]
Yeah, it was due to the lack of memory.

**Comment by Hagalas** [comment]
> By using async/await the way you do in your first attempt you are making all your actions synchronous, so each `page` is waiting for the previous to finish. To run them in parallel you need each page to return its own promise and then wait for each of those. Something along the lines of (untested code)
> 
> ```
>    const puppeteer = require('puppeteer');
> 
>     puppeteer.launch().then(async browser => {
>       const promises=[];
>       for(let i = 0; i < 10; i++){
>         console.log('Page ID Spawned', i)
>         promises.push(browser.newPage().then(async page => {
>           await page.goto('https://www.example.com/');
>           await page.screenshot({path: '../images/result' + i + '.png'});
>         }))
>       }
>       await Promise.all(promises)
>       browser.close();
>     });
> ```
I copied your example but instead of screenshot I used _click_ method and it doesn't work. I think it's because __scrollIntoViewIfNeeded_ method in the _ExecutionContext.js_ file but don't know the exact reason. Any ideas?

**Comment by nOji** [comment]
I've been dealing with the same issue and before changing my async...await code into then...catch chains, I gave each task a separate browser instance, instead of separate pages on the same browser and this problem went away!

So I'm pretty sure this has nothing to do with async...await and has something to do with the way puppeteer allows operations only in sequence for pages in the same context and not in parallel.
