### ISSUE TITLE
startCoverage never finish when request interception is enabled

### ISSUE THREAD

**Issue by pirosikick** [puppeteer/puppeteer#4710]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: macOS Mojave 10.14.5
* URLs (if applicable):
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. 
```js
// run.js
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on("request", request => {
    request.continue();
  });

  console.log("run startCoverage");
  await page.coverage.startJSCoverage();
  await page.coverage.startCSSCoverage();
  console.log("finished startCoverage");

  await page.goto("https://google.com");
  console.log(await page.title());

  const coverage = [
    ...(await page.coverage.stopJSCoverage()),
    ...(await page.coverage.stopCSSCoverage())
  ];
  console.log("coverage", coverage);

  await browser.close();
})();
```
2. `node run.js`

Above example code is pushed to the following repository:
https://github.com/pirosikick/puppeteer-collect-coverage-with-request-initerception

**What is the expected result?**
The script displays logs and outputs coverage informations the script collected.

**What happens instead?**
`startCSSCoverage` didn't finish.

**Comment by zhujun24** [comment]
Any updates ?

**Comment by zhujun24** [comment]
@aslushnikov @JoelEinbinder

**Comment by ryhinchey** [comment]
@zhujun24 I was able to reproduce this.  Funny enough moving `await page.setRequestInterception(true);` to below the start coverage calls gets puppeteer to successfully run.

``` 
await page.coverage.startJSCoverage();
await page.coverage.startCSSCoverage();

await page.setRequestInterception(true);
```

Here's a fork of your example code that will run:
https://github.com/ryhinchey/puppeteer-collect-coverage-with-request-initerception/blob/master/run.js#L16

**Comment by whalderman** [comment]
> ...moving `await page.setRequestInterception(true);` to below the start coverage calls gets puppeteer to successfully run.

This workaround still causes trouble for me unfortunately. Any subsequent navigations from the page hang, and I'm having a lot of difficulty finding the cause...
