### ISSUE TITLE
pdf do not show video thumbnails

### ISSUE THREAD

**Issue by Shailjakant12** [puppeteer/puppeteer#4712]
I'm trying to take pdf of a youtube video but pdf doesn't capture the thumbnail of the video.
A similar issue is discussed here(#1256) with taking a screenshot but I didn't come to any conclusion after reading the thread. Why exactly this is happening or feature itself is like this?

Steps to reproduce
1. Trying to take screenshot "await page.goto(url, {waitUntil: 'networkidle0'});"
2. Here url: "https://www.youtube.com/watch?v=tjQeYo60Wls"

About your environment:

* Puppeteer version: 1.8.1
* Platform / OS version: macOS High Sierra 10.13.6
* URLs (if applicable): https://www.youtube.com/watch?v=tjQeYo60Wls
* Node.js version: v12.5.0
* Chrome version: HeadlessChrome/77.0.3835.0

**What is the expected result?**
youtubeonly12.pdf should contain thumbnail of the video ie. youtubeonly12.pdf should look like the below image.
<img width="1104" alt="Screen Shot 2019-07-16 at 2 23 30 PM" src="https://user-images.githubusercontent.com/40485403/61280571-b8b12300-a7d5-11e9-8a53-36da369a7cf6.png">

**What happens instead?**
youtubeonly12.pdf doesn't contain the thumbnail of the video.
[youtubeonly12.pdf](https://github.com/GoogleChrome/puppeteer/files/3396183/youtubeonly12.pdf)

**Comment by Shailjakant12** [comment]
Is there any update on this?

**Comment by gmariammal** [comment]
Is this issue resolved?
I am facing this issue.
