### ISSUE TITLE
Interceptor breaks the puppeteer

### ISSUE THREAD

**Issue by stychu** [puppeteer/puppeteer#4715]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: OSX Mojave
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require("puppeteer-core");
const findChrome = require('chrome-finder');

const createBrowser  = () => puppeteer.launch({
  executablePath: findChrome(),
  headless: false
});

async function cdaScrapper(url) {
  const browser = await createBrowser();

  try {
    const page = await browser.newPage();

    await page.setRequestInterception(true);

    page.on('request', request => {
      request.continue()
    });

    await page.goto(url);

    await browser.close();

  } catch (e) {
    browser.close();
    throw e;
  }
}


cdaScrapper('http://ebd.cda.pl/620x368/233665500')
  .then(console.log)
  .catch(e => console.log(e.message));
```

**What is the expected result?**
When an interceptor is added it should forward all requests and page should load the same as without the interceptor.

**What happens instead?**
Whenever interceptor code is added the page load hangs in the middle and stays white
```
    await page.setRequestInterception(true);

    page.on('request', request => {
       request.continue()
    });
```

**Comment by aslushnikov** [comment]
It looks like you pick arbitrary Chrome version and try to drive it with latest Puppeteer. [This will not work](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy), please use a matching chromium version.
