### ISSUE TITLE
Clipping always grabs the upper left corner instead of the specified coords.

### ISSUE THREAD

**Issue by jbures** [puppeteer/puppeteer#4725]
So im trying to click on an element, and take a screenshot of ONLY the element before and after this happens, to see some difference in styles.

My problem is that i use the boundBox stuff to find the coordinates and size of said element, which are calculated just fine.

But when i use the clip values on the `.screenshot` function, it completely ignores the X and Y coords and just grabs the upper left corner of the screen :/

Here's a sample of the code:

```
if (config.steps.length) {
        let lastAction = "";

        for (step of config.steps) {
            const action = step.action;
            const value = step.value;

            if (action !== "SCREENSHOT" || action !== "WAIT") {
                lastAction = `_${action.toLowerCase()}`
            }

            if (action === "HOVER") {
                await page.hover(`.${value}`);
            } else if (action === "CLICK") {
                await page.click(`.${value}`);
            } else if (action === "WAIT") {
                await page.waitFor(parseInt(value));
            } else if (action === "SCREENSHOT") {
                const ssConfig = {
                    path: `./public/${config.imageName}${lastAction}.png`,
                    fullPage: config.fullPageChecked
                };

                if (step.clip) {
                    const element = await page.$(`.${step.clipElement}`);
                    const bBox = await element.boundingBox();

                    ssConfig.clip = bBox;
                }

                await page.screenshot(ssConfig);
            }
        }
    }
```

Does anyone see anything wrong with my approach?

The clipping size is perfect but the place on the view is wrong always...

Thanks and regards

**Comment by JoelEinbinder** [comment]
fullpage + clip doesn't really make sense to me.

**Comment by jbures** [comment]
> fullpage + clip doesn't really make sense to me.

@JoelEinbinder yes i know, even the api yells at me if i put both together, but even if it's not so obvious from the code, the option is configurable, so it can be false (which is most of the time)

**Comment by jbures** [comment]
Turns out it doesn't work on certain pages depending on which kind of elements are present there 🙄 no idea how to work around this for now but it works in "Static" pages
