### ISSUE TITLE
Global timeout isuue

### ISSUE THREAD

**Issue by densub** [puppeteer/puppeteer#4730]
This is an issue that was created a long time ago and was advised that it's being worked out. https://github.com/GoogleChrome/puppeteer/issues/1514

Is ```page.setDefaultNavigationTimeout``` now available to use ?

If this is something that exists in the new version, Please discard and close it!

**Comment by barclayd** [comment]
Yes this method now exists - you can call it in your test setup file to set the default timeout

**Comment by evandrocoan** [comment]
You have to set both `setDefaultTimeout` and `setDefaultNavigationTimeout` to properly timeout everything: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagesetdefaultnavigationtimeouttimeout

Related to: 
1. https://github.com/puppeteer/puppeteer/issues/4160 - disable timeouts still timing out
1. https://github.com/puppeteer/puppeteer/issues/1004 - Set timeout to 0 doesn't disable the timeout
