### ISSUE TITLE
Documentation about puppeteer in Docker only works on x86_64

### ISSUE THREAD

**Issue by mvanaltvorst** [puppeteer/puppeteer#4731]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: none
* Platform / OS version: yes.
* URLs (if applicable): https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker
* Node.js version: all of them

**What steps will reproduce the problem?**
Visit https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker, notice the following line:

```
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
```
in particular, notice this:
```
sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
```

This does not work on ARM (`[arch=amd64]`), though this is mentioned nowhere in the documentation. 

**What is the expected result?**
The documentation makes clear that this only works on x86_64, or, even better, the documentation gives instructions for puppeteer in docker on ARM.

**What happens instead?**
The documentation is incomplete.

**Comment by mvanaltvorst** [comment]
ARMv6 will have to be excluded since Chromium won't compile on there, though I think supporting ARMv7 shouldn't be any problem.

**Comment by FezVrasta** [comment]
What's the situation now that Apple switched to ARM? Any chance we'll be able to run Puppeteer on a Docker container on Apple Silicon?

**Comment by davidbielik** [comment]
@FezVrasta were you ever able to get puppeteer running in Docker on Apple Silicon M1?

I can't and waiting to see if https://github.com/puppeteer/puppeteer/pull/7546 is related

**Comment by ReDrUm** [comment]
I would expect something like `deb [arch=$TARGETARCH]` although it's legitimately not available for that arch
