### ISSUE TITLE
Login to Google account on Google Cloud Platform - denied

### ISSUE THREAD

**Issue by alamothe** [puppeteer/puppeteer#4732]
Hello,
I'm trying to log into a Google account with `puppeteer` for automation purpose. 

Everything works great when I try locally on my Mac. However, on Google Cloud Platform, I get the following message from Google:

![login_getaround_2019_07_17__03_21_08_pm__277__22__a5619f0149dda7174e9e667285671e11_1 (1)](https://user-images.githubusercontent.com/2679255/61575047-0396a780-ab02-11e9-840b-aa17b0d175a9.png)

I tried both standard environment and flexible environment with Docker — it's the same.

I am pretty clueless, does anyone have any ideas? 

The weird thing is that on my Mac everything works, regardless of Chromium, headless mode etc. (I do not try to fool Google with any techniques). What could be the reason for this?

**Comment by srmrco** [comment]
I also see this when trying to login to Gmail

**Comment by aslushnikov** [comment]
This is not Puppeteer's fault. Some websites don't want to be automated and employ certain methods to prevent this kind of automation - we can't help here.

**Comment by weworkwithzoh** [comment]
I know this is closed, but my team also suddenly started seeing this in the last week or two after not encountering it for months.

It appears something has changed somewhere on Google Login's backend that is detecting Puppeteer in CI as an invalid configuration/browser.

**Comment by weworkwithzoh** [comment]
(I'm assuming it's a Chrome/Docker combination or something)

**Comment by alamothe** [comment]
Same here. I tried standard and flexible environment (Docker), no luck. 

Weirdly, it works on my Mac even in headless. Same version of Chromium. I have no idea what triggers it, but it's likely related to the cloud environment. Let me know if you find anything!

**Comment by weworkwithzoh** [comment]
Same. No problems locally at all.
I’ll keep you posted :)

**Comment by weworkwithzoh** [comment]
So I tried this running in a local docker container on my Mac, hits the same issue.
It appears that the Google login page is checking if you're running inside of a container of sorts. (lxc/docker, etc.)

Right now, we've no way around this, and this makes automation completely useless for us right now.

**Comment by weworkwithzoh** [comment]
As a heads-up for anyone else hitting this that's coming here for the same issue looking for a solution, I appear to have resolved this issue by configuring Puppeteer to run non-headless, and without overriding the `userAgent`

Headless will fail, overriding the default `userAgent` will fail. (It appears that both of these things appear to trigger some form of automation detection within the page.)

**Comment by Geanik** [comment]
@weworkwithzoh 
where exactly are you deploying your container?
i encounter the same problem when i deploy it to google app-engine

when i run the container locally everything works
but in the app-engine i get that `Couldn't sign you in` error

i use `non-headless` mode and don't set the `userAgent`
```javascript
await puppeteer.launch({
        headless: false,
        ....
}
```

any idea?

**Comment by weworkwithzoh** [comment]
We are deploying to CircleCI, but the issue reproduced locally as well inside of a local docker container.

Interesting that you’re hitting it with this config. Might be something else app-engine is doing?

**Comment by canvas104** [comment]
I run in aws ec2 with ubuntu 14 OS, also have same problem with headless mod.
And, I failed to  lunch pupetteer in non-headless mod, so I can not test if non-headless can solve the problem.

**Comment by ozshabat** [comment]
Has anyone managed to solve this?? still encountering this strange problem

**Comment by weworkwithzoh** [comment]
I have solved this as mentioned previously. 

- Zoh

**Comment by tmm1** [comment]
Similar issue reported in #4871

**Comment by alamothe** [comment]
I started seeing this again after upgrading from `1.18.1` to `1.20.0`. 

Previously I was able to solve it with non-headless mode.

Reverting to `1.18.1` solves it.

**Comment by urosran** [comment]
@alamothe  I just tried your solution and hit the same problem although I do have 2-factor auth enabled
EDIT: even with 2-factor disabled it does not work

**Comment by LeTruong91** [comment]
I also see this when trying to login to Gmail hix

**Comment by osfunapps** [comment]
Does anyone managed to solve this problem??

**Comment by osfunapps** [comment]
I managed to solve the issue.

Try to change the user agent like so:
```
const browser = await require('puppeteer').launch({
    headless: false,
});

const page = await browser.newPage();
await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136");
```

**Comment by jbpkruppa** [comment]
None of hints above solved here. Tryed to change UserAgent, tryed to use without headless, tryed to use chrome and edge with executablePath in config...
Any other hint?

**Comment by fjaeger** [comment]
We worked around this issue by using a different site to log into a Google account via OAuth2. For example, you could use https://stackoverflow.com/users/login . Google does not seem to have such strict checks during their OAuth2 process.

**Comment by taltultc** [comment]
I solved it!!
With headless: true on AppEngine.....
Basically the idea is to save the cookies to a file after you logged in to google or any site with google login, and then you should load the cookie file at the beginning of the script and then you will skip on the google login screen because google think that you already logged in...
You need to save only one time the cookies, then just load it.
to create the cookie file: (i created the file on my local machine with headless:false)
```     
      const cookiesObj = await page.cookies()
      jsonfile.writeFile('cookiesFile.json', cookiesObj, { spaces: 1 },
        function(err) { 
          if (err) {
           console.log('The file could not be written.', err)
          }
          console.log('Session has been successfully saved')
       })
```
to load the cookie file:
```
let cookiesFilePath = 'cookiesFile.json'
const previousSession = fs.existsSync(cookiesFilePath)
if (previousSession) {
  let rawdata = fs.readFileSync(cookiesFilePath);
   let cookiesArr = JSON.parse(rawdata);
  if (cookiesArr.length !== 0) {
    for (let cookie of cookiesArr) {
      await page.setCookie(cookie)
    }
    console.log('Session has been loaded in the browser!')
    
  }
}
```

**Comment by dadmand** [comment]
> I solved it!!
> With headless: true on AppEngine.....
> Basically the idea is to save the cookies to a file after you logged in to google or any site with google login, and then you should load the cookie file at the beginning of the script and then you will skip on the google login screen because google think that you already logged in...
> You need to save only one time the cookies, then just load it.
> to create the cookie file: (i created the file on my local machine with headless:false)
> 
> ```
>       const cookiesObj = await page.cookies()
>       jsonfile.writeFile('cookiesFile.json', cookiesObj, { spaces: 1 },
>         function(err) { 
>           if (err) {
>            console.log('The file could not be written.', err)
>           }
>           console.log('Session has been successfully saved')
>        })
> ```
> 
> to load the cookie file:
> 
> ```
> let cookiesFilePath = 'cookiesFile.json'
> const previousSession = fs.existsSync(cookiesFilePath)
> if (previousSession) {
>   let rawdata = fs.readFileSync(cookiesFilePath);
>    let cookiesArr = JSON.parse(rawdata);
>   if (cookiesArr.length !== 0) {
>     for (let cookie of cookiesArr) {
>       await page.setCookie(cookie)
>     }
>     console.log('Session has been loaded in the browser!')
>     
>   }
> }
> ```

Worked at once , Account  blocked.
requests cookies and parameters different and you can not use one for all

**Comment by taltultc** [comment]
@dadmand every time you enter the site you should save the new cookies and load it on the next time.

**Comment by dadmand** [comment]
> @dadmand every time you enter the site you should save the new cookies and load it on the next time.

That`s true, I saved cookies in databases and load it with user agents, used dedicated IP for login and account blocked 

cookies load in browser before `await page.goto...`

**Comment by taltultc** [comment]
After the `await page.goto...` you need to overwrite your cookies on your DB with the new cookies you got from the site. (remember to overwrite the cookies only after you logged in to the website)
every time you enter the google sites you get new cookies, and if you are not use the latest cookies you will be blocked.
is this what you are doing?

**Comment by dadmand** [comment]
> After the `await page.goto...` you need to overwrite your cookies on your DB with the new cookies you got from the site. (remember to overwrite the cookies only after you logged in to the website)
> every time you enter the google sites you get new cookies, and if you are not use the latest cookies you will be blocked.
> is this what you are doing?

Yes, after login on page load saved cookies.
usage : 
- defined puppeteer with puppeteer-extra,puppeteer-extra-plugin-stealth,chrome-launcher
- saved cookies and agent after login 
- close browser 
- start app with load user agent and saved user cookies

just worked for 1 day

**Comment by taltultc** [comment]
you just need to save the new cookies from the app
- start app with load user agent and saved user cookies
- **save the new cookies**
- close the app

it should work for one month until you need to do login again.
also make sure that the google account is dedicated for the puppeteer.

**Comment by dadmand** [comment]
solution : used "userDataDir"

- first login manualy
- load user data from profile and auto login

```
const puppeteer = require("puppeteer");
const chromeLauncher = require("chrome-launcher");
const axios = require("axios");

const CHROME_LAUNCHER_PARAM = {
  userDataDir: "path of app data ... \\AppData\\Local\\Google\\Chrome\\User Data\\Profile 1",
};

async function ChromeLauncher() {
  const chrome = await chromeLauncher.launch(CHROME_LAUNCHER_PARAM);
  const response = await axios.get(`http://localhost:${chrome.port}/json/version`);
  const { webSocketDebuggerUrl } = response.data;
  const page = await browser.newPage();
 await page.setRequestInterception(true);
  page.on("request", (request) => {
    if (!request.isNavigationRequest()) {
      request.continue();
      return;
    }
    const headers = request.headers();
    request.continue({ headers });
  });
  ...
  goto and login ...
  ...
  return browser; 
}

ChromeLauncher()
  .then(() => console.log("[Done]"))
  .catch((err) => console.log(err));

```
