### ISSUE TITLE
page.waitForRequest() and .waitForResponse() not aborted by browser.close()

### ISSUE THREAD

**Issue by davecardwell** [puppeteer/puppeteer#4733]
If you call `browser.close()` while `page.waitForFunction()`, `page.waitForNavigation()`, etc. are pending then the `Promise` is immediately rejected.

`page.waitForRequest()` and `page.waitForResponse()`, however, hang around until they time out.

My use case is that I want to use `Promise.race()` on a `page.waitForSelector()` and `page.waitForResponse()` to trigger when either an element is made visible in the `page`, or the `page` is redirected to a specific URL. If `waitForSelector` is resolved first I call `browser.close()` and expect my process to then exit, but it waits until the timeout for `waitForResponse` has passed.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: macOS 10.14.5
* URLs (if applicable): N/A
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

```js
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  page.setDefaultTimeout(5000);

  const tests = [
    ["waitForFunction", "false"],
    ["waitForNavigation"],
    ["waitForSelector", "#test"],
    ["waitForXPath", "/test"],
    ["waitForRequest", "https://example.com/"],
    ["waitForResponse", "https://example.com/"]
  ];

  let seconds = 0;
  const interval = setInterval(
    () => console.log(`${++seconds} Mississippi`),
    1000
  );

  await Promise.all([
    ...tests.map(([method, ...args]) =>
      page[method](...args).then(
        () => console.log(`${method} resolved`),
        () => console.log(`${method} rejected`)
      )
    ),

    browser.close()
  ]);

  clearInterval(interval);
})();
```

**What is the expected result?**

```
waitForFunction rejected
waitForNavigation rejected
waitForSelector rejected
waitForXPath rejected
waitForRequest rejected
waitForResponse rejected
```

**What happens instead?**

```
waitForFunction rejected
waitForNavigation rejected
waitForSelector rejected
waitForXPath rejected
1 Mississippi
2 Mississippi
3 Mississippi
4 Mississippi
waitForRequest rejected
waitForResponse rejected
```

**Comment by davecardwell** [comment]
@yury-s @aslushnikov Thank you!

**Comment by alamothe** [comment]
Not sure how much this behavior makes sense — it will always cause `UnhandledPromiseRejectionWarning` and it is very difficult to avoid it (short of giving up on these primitives and simply using `page.on`). 

I'd argue that, if browser/page is closed, then the user is not awaiting on these promises. If they were to await it, then they wouldn't close the browser.

I am certain that a great proportion of user-reported `UnhandledPromiseRejectionWarning` and `Target closed` etc. on StackOverflow are due to this behavior.
