### ISSUE TITLE
Cannot control devtools window size

### ISSUE THREAD

**Issue by breathe** [puppeteer/puppeteer#4735]
I want to control the size of the devtools window so that its half the width of the application window.

I'm using the {devools: true} flag which opens the devtools on launch as desired -- but its driving me absolutely crazy to have to adjust the size of the devools window everytime the browser is restarted and everytime the page is reloaded ...

Devtools is opening with unnecessarily small width docked on the right edge of the page --

![image](https://user-images.githubusercontent.com/434034/61586333-38b8ef00-ab2e-11e9-9415-7ae7322bbe3b.png)

Can't really see in the screenshot I guess buts its about 1/5 or 1/6 the width of the browser application window.  I desperately want to make it 1/2 the application window size ...

I am passing `--window-size=` to puppeteer.launch and setting the viewPort width to half the value I pass to window-size ...

**Comment by vsemozhetbyt** [comment]
If it is appropriate for you to use the `userDataDir` option, the DevTools window size and position are preserved between launches in this case.

**Comment by breathe** [comment]
Ahhhhh -- that will work for me -- thank you very much!!!
