### ISSUE TITLE
I want to download pdf automatically in chromium/disable chromium pdf

### ISSUE THREAD

**Issue by sovang5** [puppeteer/puppeteer#4736]
I was trying to download a pdf whenever I visit a url.  The flag 'AlwaysOpenPdfExternally' is set to false in chromium. I can manually set it to true by visiting chromium settings tab. The problem is whenever I run the code puppeteer will launch a new user session and by default, the flag is set to false. I visited this link for different flags in chromium: https://peter.sh/experiments/chromium-command-line-switches/#cloud-print-file-type
I am not sure which flag I need to set. Please, help.
Thanks

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: mac 10.13.6
* URLs (if applicable):
* Node.js version: 8.15

**Comment by cpatrickalves** [comment]
I've managed to make it work using the following approach:

Install these packages:

```
npm install puppeteer-extra
npm install puppeteer-extra-plugin-user-data-dir
npm install puppeteer-extra-plugin-user-preferences
```

Then, in your code use:

```
const puppeteerExtra = require('puppeteer-extra');
puppeteer = puppeteerExtra;
puppeteer.use(require('puppeteer-extra-plugin-user-preferences')({
                    userPrefs: {
                        download: {
                            prompt_for_download: false,
                            directory_upgrade: true,
                            default_directory:  path.join(`${process.cwd()}`, 'downloadFolder'),
                            extensions_to_open: "applications/pdf",
                        },
                        plugins: {
                            always_open_pdf_externally: true,
                            plugins_disabled: ["Chrome PDF Viewer"],
                        },
                    }
                }));
```

**Comment by amarinediary** [comment]
@cpatrickalves Just want to say thanks for this out of the box thinking !

**Comment by fitransyahrusman** [comment]
I try to find the solution for this problem everywhere, but only on this post give real way out.
Thanks @cpatrickalves for the solution
and thank @sovang5 to pointing out this topic

**Comment by yoannLya** [comment]
This does work in `headless:false`, but not in `headless:true`. Would anyone know why ?

**Comment by yoannLya** [comment]
> I've managed to make it work using the following approach:
> 
> Install these packages:
> 
> ```
> npm install puppeteer-extra
> npm install puppeteer-extra-plugin-user-data-dir
> npm install puppeteer-extra-plugin-user-preferences
> ```
> 
> Then, in your code use:
> 
> ```
> const puppeteerExtra = require('puppeteer-extra');
> puppeteer = puppeteerExtra;
> puppeteer.use(require('puppeteer-extra-plugin-user-preferences')({
>                     userPrefs: {
>                         download: {
>                             prompt_for_download: false,
>                             directory_upgrade: true,
>                             default_directory:  path.join(`${process.cwd()}`, 'downloadFolder'),
>                             extensions_to_open: "applications/pdf",
>                         },
>                         plugins: {
>                             always_open_pdf_externally: true,
>                             plugins_disabled: ["Chrome PDF Viewer"],
>                         },
>                     }
>                 }));
> ```

What is the purpose of `npm install puppeteer-extra-plugin-user-data-dir` in your answer ? I don't see it used in the snippet given underneath.
