### ISSUE TITLE
When output to pdf, header and footer cannot be seen

### ISSUE THREAD

**Issue by baihuibo** [puppeteer/puppeteer#4738]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  ^1.18.1
* Platform / OS version: Mac 10.14.5
* URLs (if applicable):  https://github.com/
* Node.js version: v12.5.0

**What steps will reproduce the problem?**
The following code accesses the page and then outputs it to PDF

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('https://github.com/');

    await page.pdf({
        path: 'test.pdf',
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: `
            <div style="font-size: 12px; color: #000;">hi header</div> 
        `,
        footerTemplate: `
            <div style="font-size: 12px; color: #000;">hi footer</div>
        `
    });

    await browser.close();
})();
```

**What is the expected result?**
The resulting PDF should exist `header`、`footer`

**What happens instead?**
The `header`、`footer` that should exist seems transparent. You can select it, but you can't see it.

**Comment by abirtley** [comment]
@baihuibo did you find a solution to this? I'm having the same problem.

Edit: my solution was to add a top and bottom margin in the `pdf` options. Otherwise, the 'white' background of the main page was obscuring the header. So you have to set the margin to be the size of your header/footer.

**Comment by baihuibo** [comment]
@abirtley 
My solution is to set up a large enough margin so that the header and footer can be displayed.

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.goto('https://github.com/');

    await page.pdf({
        path: 'test.pdf',
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        margin:{ top : '1cm' , bottom : '1cm' }, // must be set
        headerTemplate: `
            <div style="font-size: 12px; color: #000;">hi header</div> 
        `,
        footerTemplate: `
            <div style="font-size: 12px; color: #000;">hi footer</div>
        `
    });

    await browser.close();
})();
```
