### ISSUE TITLE
 TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by ArjitRout** [puppeteer/puppeteer#4741]
TypeError: Cannot read property 'get' of undefined

      110 |  
      111 |     //const handles = await age.getAllElements('selectors');
    > 112 |     const handles = this.selectors.get('retailerImages');
          |                                    ^
      113 |     for (let i = 0; i < handles.length; i++) {
      114 |       const retailerImage = await handles[i].getProperty('src');
      115 |       retailersImageArray[i] = await retailerImage.jsonValue();

**Comment by aslushnikov** [comment]
I'm not sure what is this code snippet - it doesn't resemble anything we have in Puppeteer!
