### ISSUE TITLE
Is there any way to capture user behavior?🙇🙇🙏

### ISSUE THREAD

**Issue by huangzongzhao** [puppeteer/puppeteer#4742]
- Puppeteer version: v1.18.1
- Platform / OS version: macOS 10.14.5
- Node.js version: v11.14.0

---

Is there any way to capture user behavior?

E.g:

```html
<div id="x"></div>
```

1. I clicked on the element above.
2. `puppeteer` returns `{'elementName': 'div', 'event': 'click'}`.

Can `puppeteer` do it now?

---

I found #2862 and [page.exposeFunction()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction), but it needs to be explicit bound, and it seems Can't get `elementName`.

---

I really need your help, thank you very much. 🙇🙇🙏

**Comment by aslushnikov** [comment]
> but it needs to be explicit bound, and it seems Can't get elementName.

@fakecowboy hmm, the following works for me!

```js
const pptr = require('puppeteer');

(async () => {
  // 1. Launch browser in headful mode so that we can click around and see how
  // script works.
  const browser = await pptr.launch({
    headless: false,
  });
  const page = await browser.newPage();
  // 2. Add a |window.reportEvent| function in the page that will simply log
  // passed object to Node.js console.
  await page.exposeFunction('reportEvent', info => console.log(info));
  // 3. Hook document with capturing event listeners that sniff all the important
  // information from the event and report it back to Node.js
  await page.evaluateOnNewDocument(() => {
    document.addEventListener('click', e => reportEvent({targetName: e.target.tagName, eventType: 'click'}), true /* capture */);
  });
  // 4. Navigate the page; try clicking around the website.
  await page.goto('https://example.com');
})();
```

**Comment by huangzongzhao** [comment]
Thank God！
