### ISSUE TITLE
Headless mode should not force --hide-scrollbars

### ISSUE THREAD

**Issue by giuseppeg** [puppeteer/puppeteer#4747]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: macOS / CI (linux)
* Node.js version: 10.16.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Create a page with a block level element and measure its width
2. Increase the element height so the page shows the scrollbars
3. Measure the element's width again

**What is the expected result?**

The element's width differs because the scrollbar makes it shrink

**What happens instead?**

The element's width doesn't change. This is because Puppeteer in `headless` modes hides the scrollbars. https://github.com/GoogleChrome/puppeteer/blob/f5bb333cd0c42306f47e7767e5cb8b78af557c27/lib/Launcher.js#L85

AFAIK at the moment there is no way to override this behavior.

**Comment by karl** [comment]
With a bit of Googling I found out you can override the default behaviour so you do see scrollbars in headless mode. Just add `ignoreDefaultArgs: ["--hide-scrollbars"]` to your puppeteer configuration:

```javascript
this.browser = await puppeteer.launch({
  // Existing config goes here...
  ignoreDefaultArgs: ["--hide-scrollbars"]
});
```

Code copied from here: https://github.com/GoogleChrome/puppeteer/issues/2999#issuecomment-490854398

**Comment by amoshydra** [comment]
Additional use case to support this request: 

### For visual regression test

Screenshot generated from `headless` mode and none `headless` mode should be identical.
However, the default hiding of scrollbar in headless mode will cause the generated screenshot to be different between the 2 modes.

**Comment by soukron** [comment]
This is important, please, there's no way to get the same screenshots from headless and non-headless not even hiding the scrollbars as described in https://github.com/GoogleChrome/puppeteer/issues/4747#issuecomment-517202672

**Comment by soukron** [comment]
Probably related with this issue.

I'm running next code and I get different screenshots for headless and non-headless mode and I'm not sure if this is the expected behavior or not.

```
const puppeteer = require('puppeteer');

(async () => {
  //const browser = await puppeteer.launch({headless: true, ignoreDefaultArgs: ['--hide-scrollbars'],});
  const browser = await puppeteer.launch({headless: false),});

  console.log('Opening browser ...');
  const page = await browser.newPage();
  await page.setViewport({
        width: 1280,
        height: 720
    });
  await page.goto('http://www.google.com');
  await page.screenshot({
    path: 'test-screenshot.png',
    fullScreen: true,
  });

  await browser.close();
})()
```

With `headless: false`, this is what I get:
![test-screenshot-non-headless](https://user-images.githubusercontent.com/243988/68155162-714bcf80-ff49-11e9-8c70-8ed62792052e.png)



On the other hand, with `headless: true`, I get something slightly different:
![test-screenshot-headless](https://user-images.githubusercontent.com/243988/68155215-888abd00-ff49-11e9-9d5c-3ffb8251e60e.png)

As said, I'm not sure if this is the expected or not, but as @amoshydra said, I'd expected them to be identical moreover after disabling the scrollbar in headless mode.

**Comment by ThibaultJanBeyer** [comment]
+1 the default set-up should be the same as a non-headless mode = i.e. either display the scrollbars or hide the scrollbars on both. But currently, `headless: true,` will hide scrollbars while `headless: false` will show scrollbars. Giving different test results based on wether it's headless or not.

**Comment by khylerlin** [comment]
I have done exactly @karl suggested while the scrollbar does not show up. Any thoughts?

**Comment by soukron** [comment]
Please consider accepting this RFE/bug. Don't allow it to stale...
