### ISSUE TITLE
Possibility to have full height PDF

### ISSUE THREAD

**Issue by gitinthehole** [puppeteer/puppeteer#475]
Can we output a PDF that is the full height of the webpage? In other words, don't break up a screenshot into multiple pages. I have a use case where I would like to see the entire webpage on a single PDF page.

P.S. Thank you for this awesome project!

**Comment by aslushnikov** [comment]
You can set a custom PDF height - would it work for you?
```js
page.pdf({path: 'my.pdf', height: '10000px'});
```

**Comment by gitinthehole** [comment]
Saw that but pages vary in height and in this application, many pages will be screenshot at the same time. It will be less than optimal if all pages in the pdf are the same height.

**Comment by aslushnikov** [comment]
You can query the document height first and then use it as an argument to `page.pdf`
```js
let height = await page.evaluate(() => document.documentElement.offsetHeight);
await page.pdf({path: 'my.pdf', height: height + 'px'});
```

**Comment by gitinthehole** [comment]
Ah yes, I'll try that. I tried with Headless Chrome previously and it was slow since it seemed to pull the page twice. If this can be done without pulling the page twice, this will be awesome.

**Comment by gitinthehole** [comment]
Nice, I just tried it. It looks like it works and it seems like only one roundtrip for the page. Thank you!

**Comment by nithinkashyapn** [comment]
Hey,

I am trying the same approach to get a full page PDF, The height of the page increases but the height of the content stays the same.

My code is like this

```
const puppeteer = require("puppeteer");

function sleep(ms) {
	return new Promise(resolve => {
		setTimeout(resolve, ms);
	});
}

(async () => {
	const browser = await puppeteer.launch({
		headless: true
	});

	const page = await browser.newPage();

	await page.goto("http://localhost:3000/longpage", {
		waitUntil: "networkidle2"
	});

	let height = await page.evaluate(
		() => document.documentElement.offsetHeight
	);

	console.log("Height", height);

	await page.pdf({
		path: "hni.pdf",
		printBackground: true,
		margin: "none",
		height: height + "px"
	});

	await browser.close();
})();

```

Thanks,
\- Nithin

**Comment by 2yk** [comment]
I managed to print full page pdf with the following code. 

```
const height = await page.evaluate(() => document.documentElement.offsetHeight);
await page.pdf({ path: 'my.pdf', height: `${height + 1} px`, printBackground: true });
```

I added 1 px in page height and it removed the blank page. I know it may not an elegant solution but seems to work for me.

Adding 1px remove the blank page issue referred in issue #589

**Comment by Thieund** [comment]
How can I evaluate the height if a custom width is used for PdfOptions ?

**Comment by GeekEast** [comment]
- don't use `format` in `page.pdf()`, it will override the `height` and `width` option
- [official doc](https://pptr.dev/#?product=Puppeteer&version=v3.0.1&show=api-pagepdfoptions)

**Comment by zhongnansu** [comment]
I am using headless mode and I tried the same way to get a full page pdf, which I assume will be one page. Instead I got several pages, and the document height is always `600 `for different urls and pages.
I get the document height by this `const height = await page.evaluate(() => document.documentElement.offsetHeight);`

**Comment by namanisupriya55** [comment]
@nithinkashyapn 
How did you solve the issue ? I am getting the same issue. Able to get the height of the PDF but the content is missing.

**Comment by NelsonFrancisco** [comment]
> I am using headless mode and I tried the same way to get a full page pdf, which I assume will be one page. Instead I got several pages, and the document height is always `600 `for different urls and pages.
> I get the document height by this `const height = await page.evaluate(() => document.documentElement.offsetHeight);`

Experiencing the same

**Comment by alvin** [comment]
@zhongnansu @NelsonFrancisco 

I just ran into the same issue and found that using document.documentElement.**scrollHeight** instead of document.documentElement.**offsetHeight** did the trick for my setup.

```
let height = await page.evaluate(() => document.documentElement.scrollHeight);
await page.pdf({path: 'my.pdf', height: height + 'px'});
```

**Comment by sindhujabanka** [comment]
> You can query the document height first and then use it as an argument to `page.pdf`
> 
> ```js
> let height = await page.evaluate(() => document.documentElement.offsetHeight);
> await page.pdf({path: 'my.pdf', height: height + 'px'});
> ```

I am getting the offsetHeight as '0' to my page.
How do I solve it?
I have used scrollHeight instead of offsetHeight as well. But I could get only "610px" whereas the length of my entire page is "15000px"

**Comment by Lesnock** [comment]
There is a solution to this?
I'm having the same problem

**Comment by miranquil** [comment]
> There is a solution to this?
> I'm having the same problem

It is unbelievable that Chrome has no perfect solution to such a SIMPLE problem.

I tried Safari's export to PDF and it directly generated a SINGLE PAGE.

**Comment by phollaki** [comment]
@Lesnock  Had the same problem. I found a solution to get the content height in this thread: https://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript.

```javascript
// height of content
const pageHeight = await page.evaluate(() = >{
  let height = 0;
  function findHighestNode(nodesList: any) {
    // eslint-disable-next-line no-plusplus
    for (let i = nodesList.length - 1; i >= 0; i--) {
      if (nodesList[i].scrollHeight && nodesList[i].clientHeight) {
        const elHeight = Math.max(nodesList[i].scrollHeight, nodesList[i].clientHeight);
        height = Math.max(elHeight, height);
      }
      if (nodesList[i].childNodes.length) findHighestNode(nodesList[i].childNodes);
    }
  }
  findHighestNode(document.documentElement.childNodes);
  return height;
});
// width of device
const pageWidth = await page.evaluate(() = >document.documentElement.offsetWidth);
// pdf
const pdf = await page.pdf({
  height: pageHeight + 'px',
  width: pageWidth + 'px',
});
```

**Comment by rlueder** [comment]
For anyone looking for a solution, none of the options above worked for me, this is what in the end worked for my needs:

```
    const page = await browser.newPage();
    await page.setContent(html);

    const height = await page.evaluate(() => document.documentElement.offsetHeight);
    const width = await page.evaluate(() => document.documentElement.offsetWidth);

    await page.addStyleTag({
      content: `@page { size:${width}px ${height}px; }`,
    });

    await page.emulateMediaType('screen');

    /**
     * @see {@link https://pptr.dev/api/puppeteer.pdfoptions}
     */

    const pdfOptions: PDFOptions = {
      pageRanges: '1', // <-- limit range to 1
      preferCSSPageSize: true, // <-- make sure @page is taken into account
      printBackground: true,
    };

    const pdf = await page.pdf(pdfOptions);

```

[Credit to this SO comment from Nithin](https://stackoverflow.com/questions/55610614/full-page-pdf-in-puppeteer/#comment97966461_55618237)

**Comment by m2001said** [comment]
thanks for all of you.

for me, my html content has a lot of sections and every section width is 595px and height is 842px .. and with this code :

` await page.pdf({
    height: `842px`,
    width: "595px",
    printBackground: true,
    landscape: false,
  });
`
it works well, and every section in one page of pdf and toke the same width and height
