### ISSUE TITLE
Screenshot on unload or beforeunload event fails

### ISSUE THREAD

**Issue by pravinnayak** [puppeteer/puppeteer#4750]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by pravinnayak** [comment]
hey, i am trying to take a screenshot of the page when it navigates to a different page, for that i am using an event listeners on beforeunload but the page navigates so quickly that it is not possible to take a screenshot

**Comment by Gdocal** [comment]
If you control navigation, just make screenshots before naviagtion happens.
