### ISSUE TITLE
Select item on a <select> Tag

### ISSUE THREAD

**Issue by Gustavobezerraneto** [puppeteer/puppeteer#4751]
How to use puppeteer to paginate the list on this page: 
https://cnae.ibge.gov.br/?view=classe&tipo=cnae&versao=10&classe=03221

When i try to choose the select item on dom using: 

document.getElementsByName("tbResult_length")[0].selectedIndex = 4

It doesn't change the result, keeping only ten results in the page instead of 35 results.

**Comment by kblok** [comment]
That table is a jQuery widget. You can trigger the `change` event after selecting the item:

```js
jQuery("#tbResult_wrapper SELECT").change();
```
