### ISSUE TITLE
why chrome get_cookies() not get all cookies when I seen in dev tools

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4753]
the function get_cookies() return cookeis items are 23,but when I open network logs in chrome, it's 39 items.So,I want to why the function not get all cookeis?

**Comment by nicoandmee** [comment]
```
async getRequestCookieJar(page) {
    const jar = request.jar();

    jar._jar = toughCookie.CookieJar.fromJSON({
      looseMode: true,
      // eslint-disable-next-line no-underscore-dangle
      cookies: (await page._client.send('Network.getAllCookies')).cookies.map(c => ({
        key: c.name,
        value: c.value,
        expires: c.session ? undefined : (new Date(c.expires * 1000).toISOString()),
        domain: c.domain.replace(/^\./, ''),
        path: c.path,
        secure: c.secure,
        httpOnly: c.httpOnly,
      })),
    });
    return jar;
  }
```

**Comment by Waha-Liu88** [comment]
> ```
> async getRequestCookieJar(page) {
>     const jar = request.jar();
> 
>     jar._jar = toughCookie.CookieJar.fromJSON({
>       looseMode: true,
>       // eslint-disable-next-line no-underscore-dangle
>       cookies: (await page._client.send('Network.getAllCookies')).cookies.map(c => ({
>         key: c.name,
>         value: c.value,
>         expires: c.session ? undefined : (new Date(c.expires * 1000).toISOString()),
>         domain: c.domain.replace(/^\./, ''),
>         path: c.path,
>         secure: c.secure,
>         httpOnly: c.httpOnly,
>       })),
>     });
>     return jar;
>   }
> ```

thanks.

**Comment by ghost** [comment]
> ```
> async getRequestCookieJar(page) {
>     const jar = request.jar();
> 
>     jar._jar = toughCookie.CookieJar.fromJSON({
>       looseMode: true,
>       // eslint-disable-next-line no-underscore-dangle
>       cookies: (await page._client.send('Network.getAllCookies')).cookies.map(c => ({
>         key: c.name,
>         value: c.value,
>         expires: c.session ? undefined : (new Date(c.expires * 1000).toISOString()),
>         domain: c.domain.replace(/^\./, ''),
>         path: c.path,
>         secure: c.secure,
>         httpOnly: c.httpOnly,
>       })),
>     });
>     return jar;
>   }
> ```

thanks.
