### ISSUE TITLE
Error: spawn ENOMEM when launching with empty "env" object

### ISSUE THREAD

**Issue by leo020588** [puppeteer/puppeteer#4755]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.19.0
* Platform / OS version: Win64
* URLs (if applicable):
* Node.js version: 12.7.0

**What steps will reproduce the problem?**

```javascript
    const puppeteer = require('puppeteer');

    (async () => {
    	const env = {};
    	const browser = await puppeteer.launch({"env": env});
    	await browser.close();
    })();
```

**What is the expected result?**

Terminate execution without erros.

**What happens instead?**

    (node:11928) UnhandledPromiseRejectionWarning: Error: spawn ENOMEM
      at ChildProcess.spawn (internal/child_process.js:394:11)
      at Object.spawn (child_process.js:540:9)
      at Launcher.launch (XXX\node_modules\puppeteer\lib\Launcher.js:133:40)
      at async XXX\lib\puppeter-example.js:5:18

**Comment by drwpow** [comment]
Was googling the error because I’m getting the exact same, except I’m running tests on CircleCI and pretty sure my `env` isn’t `{}`. But I’m curious to see what the problem is here to see if it’s a similar root cause (on mine: Node 10 and 12, Puppeteer `1.17.0`).
