### ISSUE TITLE
Target type "worker" appears as "other"

### ISSUE THREAD

**Issue by thomassuckow** [puppeteer/puppeteer#4756]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer 1.19
* Platform / OS version: Windows 7
* Node.js version: 12

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Visit http://mdn.github.io/simple-shared-worker/
2. Close tab
3. Visit http://mdn.github.io/simple-shared-worker/
4. Notice how "shared_worker" isn't triggered again, but there are a bunch of "other" type targets

**What is the expected result?**

The "other" type targets should be type "worker" and the `Target.worker()` method should return said worker.

**What happens instead?**

Type is other for the real worker target and `worker()` resolves to `null`.

**Comment by cherdy** [comment]
Any updates ?

**Comment by OrKoN** [comment]
Do you have a script to reproduce this? I wonder if it's still an issue as I am unable to repro:

```
const puppeteer = require("puppeteer");

(async () => {
    const browser = await puppeteer.launch({headless: true});
    const page1 = await browser.newPage();
    await page1.goto('http://mdn.github.io/simple-shared-worker/');
    console.log(browser.targets().map(t => t.type()))
    await page1.close();
    const page2 = await browser.newPage();
    await page2.goto('http://mdn.github.io/simple-shared-worker/');
    console.log(browser.targets().map(t => t.type()))
    await browser.close();
})()
    .catch(err => console.error(err))
```

outputs 

```
node sharedWorker.js
[ 'browser', 'page', 'page', 'shared_worker' ]
[ 'browser', 'page', 'shared_worker', 'page' ]
```

**Comment by OrKoN** [comment]
Please feel free to reopen with a repro script!
