### ISSUE TITLE
Puppeteer don´t run with cronjobs

### ISSUE THREAD

**Issue by efeferrari** [puppeteer/puppeteer#4759]
I want to run node.js process as a cron job, but process are not running well.

My javascript code is just the first puppeteer example available in docs (https://pptr.dev/):

```javascript
const puppeteer = require('puppeteer'),
      process   = require('process')
;

(async () => {

    console.log( 'process owner: ' + process.env.USER );
    
    console.log('browser launch');
    const browser = await puppeteer.launch();
    
    console.log('browser launched, open new page');
    const page = await browser.newPage();
    
    console.log('Go to example.com');
    await page.goto('https://example.com');
    await page.screenshot({path: process.env.USER + '_example.png'});

    await browser.close();
})();
```
I've added username to validate the user that's running the script and cron job is this:

```
01 * * * * /usr/local/nvm/versions/node/v10.16.0/bin/node /var/node/pupp_test/init.js > /var/node/pupp_test/output.txt
```
So, if I run manually the script:
```
process owner: efeferrari
browser launch
browser launched, open new page
Go to example.com
```
But, when script runs with cronjob, output file is just:
```
process owner: efeferrari
browser launch
```
I don't understand why Puppeteer has this problem if the process owner is the same with bash and cron

I have node.js installed with NVM and configured Puppeteer with [setup setuid sandbox][2], so I can run node and puppeteer with all users in the machine.

Searching about my problem, I've find in StackOverflow a topic talking about [executing Puppeteer from PHP][1] and I've already try with ```setfacl``` in ```node_modules/puppeter/.local-chromium/``` and in ```/usr/local/sbin/chrome-devel-sandbox```, but does not resolve my issue

 - OS is Centos 7
 - Node version is 10.16.0
 - Puppeteer version is 1.19.0

  [1]: https://stackoverflow.com/a/50174004/2287350
  [2]: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#alternative-setup-setuid-sandbox

**Comment by Rafostar** [comment]
@efeferrari 
Try setting your DISPLAY env in crontab job. Like this:
```
* * * * * DISPLAY=:0 /path/to/node /path/to/script.js
```

**Comment by efeferrari** [comment]
@Rafostar thanks for your answer.

I try it, but doesn't work. The ```output.txt``` file has the same log:

```
process owner: efeferrari
browser launch
```

**Comment by Rafostar** [comment]
You are not outputting errors to log file. Use `2> output.txt` instead in the cron job.

**Comment by efeferrari** [comment]
Hello, @Rafostar  thanks again for your answer and support.

I set my cronjob like this:

```* * * * * DISPLAY=:0 /path/to/node /path/to/script.js > /path/to/output.txt```

But ```output.txt``` it's still:
```
process owner: efeferrari
browser launch
```
instead of
```
process owner: efeferrari
browser launch
browser launched, open new page
Go to example.com
```

**Comment by Rafostar** [comment]
Like I said, use `2>` to get errors.
```
* * * * * DISPLAY=:0 /path/to/node /path/to/script.js 2> /path/to/output.txt
```

**Comment by efeferrari** [comment]
@Rafostar thanks for clarifyng!

I try that and get ```No usable sandbox! Update your kernel``` error. This is weird, because I can run script with all users.

**Comment by Rafostar** [comment]
There's a detailed manual on setting up sandbox in [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox).

**Comment by efeferrari** [comment]
As I said in first post:

> I have node.js installed with NVM and configured Puppeteer with [setup setuid sandbox][1], so I can run node and puppeteer with all users in the machine.

After all, I was forced to use [Cron][2] to solve my problem.

[1]: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#alternative-setup-setuid-sandbox
[2]: https://www.npmjs.com/package/cron

**Comment by mooocer** [comment]
I am getting the same error. Were you able to find any solution @efeferrari ?
Here's my stacktrace:

```
Error: Failed to launch the browser process!
[4287:4287:0505/183802.139136:ERROR:browser_main_loop.cc(1485)] Unable to open X display.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/vaibhav/projects/myproject/node_modules/puppeteer/lib/Launcher.js:615:20)
    at ChildProcess.<anonymous> (/home/vaibhav/projects/myproject/node_modules/puppeteer/lib/Launcher.js:606:67)
    at ChildProcess.emit (events.js:215:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by efeferrari** [comment]
@mishuvs I don't. Just _"fixed"_ with [Cron][1]

> I was forced to use [Cron][1] to solve my problem.

Besides, I no longer work on that project, so I can't even try more solutions.

[1]: https://www.npmjs.com/package/cron

**Comment by exwyezed** [comment]
I have the same issue and finally I decided to use [PM2](https://pm2.keymetrics.io/docs/usage/quick-start/)

One command and you're set:
```sh
pm2 start index.js --log app.log --time --cron "* * * * *" && pm2 save
```
And you would need to run this one too to execute PM2 on startup:
```sh
pm2 startup
```

I hope PM2 doesn't overload my Raspberry Pi, that's why I really wanted to use `crontab` initially :)

**Comment by mandeepm91** [comment]
@alfonmga Thanks!

I spent half a day troubleshooting why my cron wasn't working. Ended up using pm2. So far so good.

**Comment by softwaredeveloptam** [comment]
**Original Post** 
Before using PM2, I'm still looking for a particular solution for this. If I find it, I'll post it here.

**Edit 1** 
Found an answer for myself that worked with crontab, will post it in a bit

**Edit 2**
After installing all the additional items to get Chromium and Puppeteer working together.
I set up my cronjob as `root` user and I had to specific a couple of things within the `crontab -e`

`SHELL` and `PATH` need to be specify to get the proper environment variables as the crontab has it's own environmental variables that differ from your host machine.
- `echo $PATH`
- Then whichever $PATH that was here, I inserted it below.
- `PATH=/root/bin` (yours should be different or more lengthy, you can choose which ones are necessary. Between each `:` is a path to where your environment variables are) 
- `SHELL=/bin/bash` so it would have access to bash

Resources used:
- [Setup Puppeteer on Centos 7](https://frugalisminds.com/how-to-setup-puppeteer-in-centos-7/)
- [Reasons why cron won't execute my node script](https://stackoverflow.com/questions/26316237/why-wont-cron-execute-my-node-js-script/27823675#27823675)
- [How to run a cronjob with existing environmental variables](https://unix.stackexchange.com/questions/27289/how-can-i-run-a-cron-command-with-existing-environmental-variables)
- [Execute a node script within a crontab](https://stackoverflow.com/questions/5849402/how-can-you-execute-a-node-js-script-via-a-cron-job/5849463)

**Comment by efeferrari** [comment]
I going to close the issue because I'm working with another technologies so I don't even have a way to test anything again. Besides, I opened it in 2019, so if someone faces to this problem, then have to open a new ticket.
