### ISSUE TITLE
Is there a way to outline fonts?

### ISSUE THREAD

**Issue by dagumak** [puppeteer/puppeteer#4762]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^1.8.0
* Platform / OS version: Mac OSX 10.14.5
* URLs (if applicable):
* Node.js version: 10.15.3
 
**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Opening a PDF generated by that framework in Adobe Illustrator (https://github.com/RelaxedJS/ReLaXed-examples/tree/master/examples/book/)
2. The fonts aren't outlined

This is relevant to: https://github.com/RelaxedJS/ReLaXed/issues/139

ReLaXed is using Puppeteer to create PDFs. 
> If I print an HTML with Chrome and save as a pdf, it outlines the fonts so then rendering it in something lie Adobe Illustrator then it doesn't need a font. This would also allow print shops to easily print PDFs. Is there a way to outline the fonts using this library?

A member of that repository suggested this might be a Puppeteer issue.
> Outlining is converting the fonts to (vector) shapes.
> Embedding is different.
> 
> I see no option for this in Puppeteer: https://github.com/GoogleChrome/puppeteer/blob/v1.19.0/docs/api.md#pagepdfoptions
> 
> I guess it depends a bit on PostScript support and other things.
> This is probably an issue in Puppeteer / Chromium.

**What is the expected result?**
I expect the fonts to be outlined the same way Chrome generates PDFs. This way, sending PDFs to print shops have less risk of unexpected outcomes.

**What happens instead?**
It's not outlined; I am assuming the font family is embedded as suggested by this comment: https://github.com/RelaxedJS/ReLaXed/issues/139#issuecomment-515101110

**Comment by Kodiakkb** [comment]
I'm struggling with the opposite issue with puppeteer ^2.0.0: Illustrator force vectorizes the texts of PDF generated by Puppeteer. I need to be able to edit them in the PDF.
As the OP, I don't reproduce this issue when opening a PDF generated directly by Chrome.
Opening both PDF with a text editor, I can't spot any difference in the declaration of the font/fontDescriptor, it could be in the binary embedding of the font...

**Comment by turboz747** [comment]
We hope the puppeteer provides an option to outline fonts or not. It's very useful.

**Comment by rambo-panda** [comment]
As of now (2023/08/10), I have done tests on whether secondary development is possible.

* Y : no outline &lt;can reporduce&gt;
* N: outline &lt;can't reporduce&gt;


  |   |  
-- | -- | --
  | chrome(Directly) | puppeteer
window | N | Y
mac | system font N. [Web fonts](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts) Y | Y
linux | Y(by puppeteer executablePath) | Y
