### ISSUE TITLE
SetBypassCSP on new tab in Puppeteer

### ISSUE THREAD

**Issue by angrykoala** [puppeteer/puppeteer#4764]
> This question was originally posted in [stackOverflow](https://stackoverflow.com/questions/57173133/setbypasscsp-on-new-tab-in-puppeteer). Given the lack of answers I assume that either it is not possible at the moment or not documented how to do this.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.19.0
* Platform / OS version: Linux
* URLs (if applicable):
* Node.js version: 10.16.0

**What steps will reproduce the problem?**

I'm opening the following html page in Puppeteer:
```html
<!-- head -->

<body>
    <a class="btn-tab" href="html_simple.html" target="_blank">new tab</a>
</body>

<!-- more web -->
```

Clicking on the button will open a new tab. 

In my javascript code I have the following:

```javascript
const context = page.browserContext();


context.on('targetcreated', async (target) => {
    const newPage = await target.page();
    if (newPage) {
        await newPage.setBypassCSP(true);
    }
});
```

**What is the expected result?**
bypassCSP to be set to true in the new page

**What happens instead?**

When opening the new page, the CSP bypass is still disabled (throws a content security error when loading some scripts). I assume that this is because the `targetcreated` event is thrown after the new page navigation, and, as the Puppeteer docs states:

> NOTE CSP bypassing happens at the moment of CSP initialization rather then evaluation. Usually this means that page.setBypassCSP should be called before navigating to the domain.

Which seems to be the case, as executing `page.reload()` and `setBypassCSP` before loading these scripts seems to work.

My question is how to set bypassCSP to true on a tab opened by a web? Is there an event before loading content or global setup in Puppeteer that allows me to do it?

**Comment by aslushnikov** [comment]
> Is there an event before loading content or global setup in Puppeteer that allows me to do it?

@angrykoala There's nothing like this at the moment. What is your usecase?

**Comment by angrykoala** [comment]
Hi @aslushnikov 
In order to test my webpages, I'm loading some utilities scripts with `addScriptTag` after each page load (things like jquery helpers and stuff).

I'm testing a webpage (similar to the html I posted), the server is configured with strict CSP and I had no problems testing it until I tried opening a new tab, even with bypassCSP set, on the new tab the custom scripts cannot be loaded.

Currently I'm simply reloading the tab so the bypass can do its magic, and I'll consider moving my `addScriptTag` helpers to simple evaluates that (afaik) are not checked by the CSP. However I still feel that this (having bypassCSP on a newly opened tab) should be something doable at some point (no idea if chromium/devtools itself have some limitation on this)

**Comment by aslushnikov** [comment]
@angrykoala thanks for the explanation!

> Currently I'm simply reloading the tab so the bypass can do its magic, and I'll consider moving my addScriptTag helpers to simple evaluates that (afaik) are not checked by the CSP

Yeah, you should have no problems with evals.

> However I still feel that this (having bypassCSP on a newly opened tab) should be something doable at some point (no idea if chromium/devtools itself have some limitation on this)

This is technically possible, but requires work in Chromium. I'd rather hold on this unless there's a strong demand - there are more things to do, and we have limited resources.

I'll close this for now - we can reopen later on if there's demand.

**Comment by gilles-yvetot** [comment]
@aslushnikov I am interested by this feature as well. We have a very similar use case than @angrykoala
