### ISSUE TITLE
Chrome/Chromium failing launch periodically when using --no-sandbox

### ISSUE THREAD

**Issue by jredl-va** [puppeteer/puppeteer#4765]
* Puppeteer version: 1.19.0
* Platform / OS version: ubuntu:latest running within Google Cloud k8s
* URLs (if applicable):
* Node.js version: 10.15.3

We are running puppeteer within a kubernetes cluster on google cloud (100 node daemonset so its equivalent to 100 instances). We are periodically seeing errors in the logs where puppeteer is not able to start chrome. Note, this is happening both with Chrome & Chromium that is bundled with puppeteer. 

The error returned reads: 

> [0727/185924.644612:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!
> Most likely you need to configure your SUID sandbox correctly

Here is a snippet that launches the browser:

```const browser = await puppeteer.launch({
        executablePath: 'google-chrome',
        args: [
            '--no-first-run',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--ignore-certificate-errors',
            '--ignore-urlfetcher-cert-requests',
            '--proxy-server=http://our-proxy'],
        ignoreHTTPSErrors: true,
        headless: false,
        userDataDir: process.env.TMP_PROFILE_DIR,
        defaultViewport: null
    });

    const page = await browser.newPage();
    page.setDefaultTimeout(120000);
    page.setDefaultNavigationTimeout(120000);
```

Our containers entry point looks like:
```
#!/bin/bash

/etc/init.d/dbus start
sleep 1s

export DISPLAY=:1
export TMP_PROFILE_DIR=$(mktemp -d -t puppeteer.XXXXXXXXXX)

Xvfb :1 -screen 0 1440x900x24 &
sleep 3s

node app.js
```

Anyone have any debugging tips to figure out what is going on? Why would only some requests fail to start the browser?

**Comment by jredl-va** [comment]
Scratch that, going to close and discuss at stackoverlow

**Comment by wilforlan** [comment]
@jredl-va please did you get a solution to this?
Maybe you could share a link to the Stackoverflow discussion.
Thanks
