### ISSUE TITLE
Export credential (feat)

### ISSUE THREAD

**Issue by nicoandmee** [puppeteer/puppeteer#4766]
- Currently, there is no reliable way to clone a browser (all session data/cookies/user data dir structure). I find it necessary often to use this functionality (basically, cloning a browsers state, and then later turning it on again).

- Proposing adding functions to puppeteer to serve this purpose: `exportCredential()`, `importCredential(str)`. Export simply returns a base64-encoded string that can be imported/parsed to setup session/cookies/userDataDir.

- I am using node-tar to gzip the userDataDir, the implementation looks something like this:

```
const stream = await tar.x({
      cwd: browser.userDataDir,
      gzip: true,
    });
    stream.end(Buffer.isBuffer(this.parsedCredential.chromeUserData) ? this.parsedCredential.chromeUserData : Buffer.from(this.parsedCredential.chromeUserData, 'base64'));

```

Import function looks like:
```
async importCredential(zbuf) {
    await new Promise((resolve, reject) => {
      zlib.gunzip(Buffer.from(zbuf, 'base64'), (err, buf) => {
        if (err) return reject(err);
        this.parsedCredential = JSON.parse(buf.toString());
        return resolve();
      });
    });

    await this.loadCredentials();
  }
```
parsedCredential is composed of:
- puppeteerCookies: from `._client.send('Network.getAllCookies')`
- cookies: from `page.cookies()`
- chromeUserData: from:
```

async function streamToBuffer(stream) {
  return new Promise((resolve, reject) => {
    const buffers = [];
    stream.on('error', reject);
    stream.on('data', data => buffers.push(data));
    stream.on('end', () => resolve(Buffer.concat(buffers)));
  });
}

 const buf = await streamToBuffer(await tar.c({
        gzip: true,
        cwd: this.userDataDir,
        filter(path) {
          if (/BrowserMetrics-active\.pma$/i.test(path)) return false;
          if (/\/Favicons(-journal)?$/.test(path)) return false;
          if (/\/History(-journal)?$/.test(path)) return false;
          if (/\/Top Sites(-journal)?$/.test(path)) return false;
          if (/\/Last Session$/.test(path)) return false;
          if (/\/Last Tabs$/.test(path)) return false;
          if (/\/Visited Links$/.test(path)) return false;
          if (/\/ShaderCache\//.test(path)) return false;
          if (/\/ShaderCache$/.test(path)) return false;
          if (/\/GPUCache\//.test(path)) return false;
          if (/\/GPUCache$/.test(path)) return false;
          return true;
        },
      }, ['.']));
```

Is this something that would be appropriate to add to the project itself or should it just be a utility lib? The use-case seems so common...

**Comment by aslushnikov** [comment]
> Currently, there is no reliable way to clone a browser (all session data/cookies/user data dir structure). I find it necessary often to use this functionality (basically, cloning a browsers state, and then later turning it on again).

@nicoandmee I'd expect `userDataDir` to be sufficient to "clone a browser". The only thing to keep in mind that you should clone the directory that is not used by any currently-running browser instance.

Why is this not enough?

**Comment by nicoandmee** [comment]
@aslushnikov This is quite a late reply but actually no, just cloning the user-data-dir isn't sufficient to keep all the session data at least in my experience- still need to set the cookies. I just see a lot of people looking for an easy solution whereby they can replicate the whole browser state (session, cookies, all of it) and it seems as if something like this, where you can just export a base64 string and import it seamlessly was appealing.

**Comment by nicoandmee** [comment]
Additionally, correct me if I am wrong, but by default `page.cookies()` does not return third party cookies- so this captures that as well.
