### ISSUE TITLE
Border-width not respected below 1px on PDF export

### ISSUE THREAD

**Issue by bouchoua2u** [puppeteer/puppeteer#4768]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
 puppeteer-core@1.8.0
* Chrome version:
Version 73.0.3683.103 (Official Build) (64-bit)
* Platform / OS version:
CentOS Linux 7
* URLs (if applicable):
* Node.js version:
v8.11.4

**What steps will reproduce the problem?**

Create an HTML page with div or table having border width that are under 1px width (I want here to specify in point) and export as PDF.

My HTML page:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta name="Description" content=""/>
	<meta name="Keywords" lang="en" content=""/>
	<meta name="Identifier-URL" content=""/>
	<meta name="Reply-to" content=""/>
	<meta name="Copyright" content="copyright"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<style>
		@page {
			size: A4;
		}

		body {
			width:21cm;
			height: 29.7cm;
		}
		table {
			border-collapse: collapse;
		}

		table td {
			border-top: solid .25pt black;
		}

		div.divTest1 {
			width: 2cm;
			margin-top: 2cm;
			border-top: solid 1pt black;
			min-height: 1cm;
		}

		div.divTest2 {
			width: 2cm;
			margin-top: 2cm;
			border-top: solid 2pt black;
			min-height: 1cm;
		}

		div.divTest3 {
			width: 2cm;
			margin-top: 2cm;
			border-top: solid 3pt black;
			min-height: 1cm;
		}

		div.divTest0-5px {
			width: 2cm;
			margin-top: 2cm;
			border-top: solid 0.5px black;
			min-height: 1cm;
		}

		div.divTest1px {
			width: 2cm;
			margin-top: 2cm;
			border-top: solid 1px black;
			min-height: 1cm;
		}

		div.divTest2px {
			width: 2cm;
			margin-top: 2cm;
			border-top: solid 2px black;
			min-height: 1cm;
		}

		div.divTest3px {
			width: 2cm;
			margin-top: 2cm;
			border-top: solid 3px black;
			min-height: 1cm;
		}

	</style>
</head>
<body>

<div class="page">
	<table>
		<tr>
			<td>cell1</td>
			<td>cell2</td>
			<td>cell3</td>
			<td>cell4</td>
		</tr>

	</table>

	<div class="divTest1">1pt</div>
	<div class="divTest2">2pt</div>
	<div class="divTest3">3pt</div>
	<br>
	<div class="divTest0-5px">0.5px</div>
	<div class="divTest1px">1px</div>
	<div class="divTest2px">2px</div>
	<div class="divTest3px">3px</div>
</div>


</body>
</html>
```

My puppeteer code to export as PDF: 

```
const puppeteer = require('puppeteer-core');

(async () => {
  
  let fileoutput = process.argv[2];
  let uri = process.argv[3];
  const browser = await puppeteer.launch({ignoreHTTPSErrors: true,executablePath: '/opt/google/chrome/google-chrome',args: ['--no-sandbox','--disable-dev-shm-usage']});
  const page = await browser.newPage();
  await page.goto(uri,{ waitUntil: ['domcontentloaded', 'networkidle2'] });
  await page.pdf({path: fileoutput, format: 'A4',scale: 1,preferCSSPageSize:true, 'printBackground' : true});

  browser.close();
})();

```

**What is the expected result?**

We expect to have border width respected as specified in the CSS rules on the PDF export.
I want a border width of 0.25pt for my client document print.

**What happens instead?**
The border width specified in "pt" and below 1px are not respected in the PDF.
Editing/inspecting the PDF with a vectorial editor (Inkscape for example), we can see that border width of 1px or higher are approximatively respected but under that, there are not.
For example, the div width a border-width of 0.5px is approximatively 1px on the resulting PDF.

[Pdf_result.pdf](https://github.com/GoogleChrome/puppeteer/files/3441101/Pdf_result.pdf)
![screenshot1](https://user-images.githubusercontent.com/3789163/62034604-9c0de580-b1ee-11e9-8411-14c355fb86ac.png)
![Screenshot2](https://user-images.githubusercontent.com/3789163/62034605-9c0de580-b1ee-11e9-8047-e57b7c1e8d8a.png)
![Screenshot3](https://user-images.githubusercontent.com/3789163/62034606-9c0de580-b1ee-11e9-8a9b-4910a6d3621f.png)
![Screenshot4](https://user-images.githubusercontent.com/3789163/62034608-9c0de580-b1ee-11e9-96bf-243803b39556.png)
![Screenshot5](https://user-images.githubusercontent.com/3789163/62034609-9ca67c00-b1ee-11e9-90c9-6b014c94c229.png)
![Screenshot6](https://user-images.githubusercontent.com/3789163/62034610-9ca67c00-b1ee-11e9-9d73-b19058a052c3.png)
![Screenshot7](https://user-images.githubusercontent.com/3789163/62034611-9ca67c00-b1ee-11e9-9d17-be9d94ba9113.png)

**Comment by atomheartother** [comment]
We're also encountering this behavior, any fix yet?

**Comment by droid51** [comment]
whould ne "nice" ! :-)

**Comment by Gaibe** [comment]
Erff I had the same issue here 😫
Any fix in sight ?

**Comment by bjarketrux** [comment]
Anyone found a workaround for this issue? Like scaling the page or some DPI setting?

**Comment by FrEaKmAn** [comment]
One solution is to use box-shadow

```
| border: 1px solid red | box-shadow: inset 0 0 0 -1px red |
| border-top: 1px solid red | box-shadow: inset 0 1px 0 0 red |
| border-right: 1px solid red | box-shadow: inset -1px 0 0 red |
| border-bottom: 1px solid red | box-shadow: inset 0 -1px 0 0 red |
| border-left: 1px solid red | box-shadow: inset 1px 0 0 red |
```

If I change 1px to lower value, it renders nicely.

This works nicely for other elements than table. There, extra border was added. To solve that, you can specify it as background image

```
background-image: linear-gradient(to bottom, #000, #000 60%, #FFF 60% 100%);
background-position: 0 100%;
background-repeat: no-repeat;
background-size: 100% 1px;
```

**Comment by combdn** [comment]
The same issue here. 
puppeteer@18.0.5

**Comment by kleenerStern** [comment]
I've got a similar issue where borders between td's are rendered in the printed version even though they are set to none and are not showing up in fireforx / chrome.

**Comment by fyfirman** [comment]
That's also happen on element. For example I want to give a line:

```
h2:after {
  content: '';
  display: inline-block;
  height: 0.5px; // ❌ not working
}
```

The solution of pseodo line would be like these 
```
h2:after {
  content: '';
  display: inline-block;
  height: 1px; 
  transform: scaleY(0.5); // ✅
}
```

**Comment by m-blank** [comment]
Same issue here.

**Comment by kkocdko** [comment]
This seems a chrome's issue, not puppeteer's.
