### ISSUE TITLE
Error: File chooser handling does not work with multiple connections to the same page

### ISSUE THREAD

**Issue by erm100** [puppeteer/puppeteer#4783]

**Comment by hanjeahwan** [comment]
same issue with puppeteer.connect

**Comment by MarceDiazCorcoran** [comment]
I'm facing exactly the same issue: 
_Error: File chooser handling does not work with multiple connections to the same page_

But only happens in docker. It's working fine on Mac and Windows machines.

**Comment by erm100** [comment]
occur

**Comment by benmcderm** [comment]
Yeah, I'm seeing the same issue when running locally on Mac, are there specific configuration changes that eliminate this issue?

**Comment by erm100** [comment]
[Q: Why doesn’t Puppeteer v.XXX work with Chromium v.YYY?](https://github.com/GoogleChrome/puppeteer/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy)

**Comment by benmcderm** [comment]
@Ermolaev-Nikolay thanks!  Using Chromium worked for me as well - would be nice to have the functionality within both though.
