### ISSUE TITLE
is it possible to use many instances independently ?? 

### ISSUE THREAD

**Issue by zouhair94** [puppeteer/puppeteer#4790]
i try to make a express.js web app that scrap and render data from a website i devided my puppeteer instance to 3 functions one screenshot capthca one login and render a combo box third retrieve data  my project is working when i have only one user when i have many users only last user get control of his browser . it's seems i cant get each browser independent to one session

**Comment by Gdocal** [comment]
Just run 3 instance of puppeteer with 3 different 'userDataDir'

**Comment by zouhair94** [comment]
how i can run 3 dir from expresss js for each page i can have even more
