### ISSUE TITLE
Puppeteer-core Page.pdf - Protocol error (IO.read): I nvalid parameters handle: string value expected

### ISSUE THREAD

**Issue by DekleDave** [puppeteer/puppeteer#4791]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  Not sure
* Platform / OS version:  Windows Server 2012 R2 Standard
* URLs (if applicable):
* Node.js version:  v11.9.0

**What steps will reproduce the problem?**
Running a .bat file which calls a .js to open a web page, create a pdf, and write it to a file folder.  It works on one server, but not another.
_Please include code that reproduces the issue._

1. Next line is the .js file
2.const puppeteer = require('puppeteer-core');(async () => {const browser = await puppeteer.launch({headless: true, executablePath: 'C:\\\\Program Files (x86)\\\\Google\\\\Chrome\\\\Application\\\\Chrome.exe'});const page = await browser.newPage();await page.goto('https://www.google.com');await page.waitFor(4000);await page.pdf({path: 'D:\\\\PDFGen\\\\FORMS\\\\F-2790_RequestforAgreement.PDF'});await browser.close();})();
3.Next is the .bat file

cd /d d:\\nodejs\\node_modules\\npm\\node_modules & node FORMS_PrintPageToPDF_F-2790.js & EXIT
**What is the expected result?**
A PDF file of the desired screen will be created and written to the desired drive.

**What happens instead?**
D:\PDFGen\FORMS>cd /d d:\\nodejs\\node_modules\\npm\\node_modules   & node FORMS
_PrintPageToPDF_F-2790.js   & EXIT
(node:7780) UnhandledPromiseRejectionWarning: Error: Protocol error (IO.read): I
nvalid parameters handle: string value expected
    at Promise (d:\nodejs\node_modules\npm\node_modules\puppeteer-core\lib\Conne
ction.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (d:\nodejs\node_modules\npm\node_modules\puppeteer-core\l
ib\Connection.js:182:12)
    at Function.readProtocolStream (d:\nodejs\node_modules\npm\node_modules\pupp
eteer-core\lib\helper.js:241:37)
  -- ASYNC --
    at Page.<anonymous> (d:\nodejs\node_modules\npm\node_modules\puppeteer-core\
lib\helper.js:111:15)
    at d:\nodejs\node_modules\npm\node_modules\FORMS_PrintPageToPDF_F-2790.js:1:
387
(node:7780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:7780) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by DekleDave** [comment]
Any help is appreciated.

**Comment by kblok** [comment]
@DekleDave I bet it's a Chrome version issue.
You could take a look at [this doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#next-release-aug-15-2019) to check which version of chromium you should use based on the version of puppeteer you are using.

**Comment by DekleDave** [comment]
After more research, I installed puppeteer and used it instead of puppeteer-core and all is now working on all my servers.
