### ISSUE TITLE
Double click with mouseDown,mouseUp,mouseDown,mouseUp  

### ISSUE THREAD

**Issue by Gdocal** [puppeteer/puppeteer#4792]
What is the reason that Puppeteer doesn't recognize this 4 commands as a double click?
I don't want to use ClickCount as I want to have control over delay between these 4 events.

The same issue for Triple click ( to select whole node text).

I think it will be useful if Puppeteer mouse have the same behavior as a real mouse have.

**Comment by JoelEinbinder** [comment]
ClickCount doesn't send multiple clicks, it sets the "count" for each individual click. To do a double click you'd do

```js
await page.mouse.down({clickCount: 1});
// wait however long you want here
await page.mouse.down({clickCount: 2});
```
