### ISSUE TITLE
Can't use page.close() with headless

### ISSUE THREAD

**Issue by z0om** [puppeteer/puppeteer#4798]
Hello,

When I use headless option with true value for puppeteer.launch, I can't use page.close() without having this error :
`Protocol error (Runtime.callFunctionOn): Target closed`

Worse, the only way to work with is devtools: true, like this 
`const browser = await puppeteer.launch({ headless: false, devtools: true});`

* Puppeteer version: 1.18.1
* Platform / OS version: Windows 10 Pro / 18362.267
* Node.js version: 10.16.0

**Comment by kblok** [comment]
@z0om do you have an example to share?
This code works as expected
```js
(async () => {

    const browser = await puppeteer.launch({ headless: false});
    const page = await browser.newPage();
    const response = await page.goto("https://www.google.com/");
    console.log(response.url());
    await page.close();
    await browser.close();
})();

```

**Comment by z0om** [comment]
I try to explicite my example ASAP.

**Comment by z0om** [comment]
I have tried to give you a simple example and I found my mistake : page.evaluate returns a Promise. So, I just put 'await' before it and page.close works fine.

Sorry !
