### ISSUE TITLE
Puppeteer double encodes url

### ISSUE THREAD

**Issue by Choongkyu** [puppeteer/puppeteer#4801]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14
* Platform / OS version: macOS 10.14.5
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

1. run code below
2. observe described issue

_Please include code that reproduces the issue._
```
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.goto("http://localhost:8080/foo bar");
  await page.waitFor(30000);
  await page.close();
  await browser.close();
})();
```
**What is the expected result?**
Browser should go to
`http://localhost:3000/foo%20bar`

**What happens instead?**
Browser goes to
`http://localhost:3000/foo%2520bar`

**Comment by kblok** [comment]
I'm getting `%20` using your code:

![image](https://user-images.githubusercontent.com/2198466/62464299-a128e280-b762-11e9-95df-4e28caafbc18.png)


Same result in headless.

**Comment by z0om** [comment]
Like @kblok !
