### ISSUE TITLE
Ads are blocked in Google Cloud Function

### ISSUE THREAD

**Issue by Jiiieeef** [puppeteer/puppeteer#4802]
Hello,

I am writing a script which go on website to take a pictures of the iframe present on the page. 
This script is planned to be running on a Google Cloud Function when a form is filled in a web app.

* Puppeteer version: 1.19.0
* Platform: Google Cloud Functions
* Node.js version: 8

**What steps will reproduce the problem?**

The script present in the cloud function:
```
import puppeteer from 'puppeteer';

const randomNumber = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
const takeScreenshot = async () => {
  const browser = await puppeteer.launch({
    args: ['--no-sandbox'],
    headless: true
  });

  const page = await browser.newPage();
  await page.goto('https://www.lemonde.fr', {
    waitUntil: 'domcontentloaded',
  });
  await page.waitFor(5000);

  const iframes = await page.$$('iframe');
  console.log(`${iframes.length} iframes`);

  const screenShootdelay = randomNumber(5, 15);
  await page.waitFor(screenShootdelay * 1000);

  const screenshotName = new Date().getTime();
  await page.screenshot({path: `${screenshotName}.png`, fullPage: true});
  console.log(`take screenshot ${screenshotName}`);
};

takeScreenshot();
```

**What is the expected result?**
Well, if you don't know the site lemonde.fr, it's *full* of ads but in the screenshot, there is none, like if the chrome use by puppeteer use a adblocker. Is there a way to display ads ?

**Comment by sunmasters** [comment]
May be GCF is blocking adsense ads or its related urls.( I didn't check).

> setup a proxy and useragent.
