### ISSUE TITLE
Queued request hangs on some pages

### ISSUE THREAD

**Issue by farynam** [puppeteer/puppeteer#4812]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Linux debian9 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux 
* URLs (if applicable): https://tvn.pl
* Node.js version: v10.15.3

**What steps will reproduce the problem?**
When I try to queue requests at some point I don't receive requests or response related events. 
_Please include code that reproduces the issue._

`
const puppeteer = require('puppeteer');

export class RequestQueue2 {

    constructor() {
        this.queue = [];
        this.paused = false;
        this.inputCounter =  0;
        this.outputCounter = 0;
    }

    onRequestArrived(requestFn) {
        this.inputCounter++;
        if (this.paused) {
            this.queue.push(requestFn);
        } else {
            this.paused = true;
            requestFn();
        }
    }

    onRequestFinished(request) {
        console.log(`request finished:${request.url()}`);

        this.outputCounter++;
        if (this.queue.length > 0) {
            this.queue.shift()();
        } else {
            this.paused = false;
        }
    }

    get openRequestCount() {
        return this.inputCounter - this.outputCounter;
    }
}

(async () => {
    const browser = await puppeteer.launch(
        {
            headless: false,
            devtools: true,
            args: ['--disable-web-security', '--no-sandbox'],//TODO because of iframe
            defaultViewport: {
                width: 1280,
                height: 839,
                deviceScaleFactor: 1,
                isMobile: false,
                hasTouch: false,
                isLandscape: true
            }
        });
    const page = await browser.newPage();
    page.setViewport({width: 1280, height: 852});
    await page.setRequestInterception(true);

    const requestQueue = new RequestQueue2();

    page.on('request', (request) => {
        requestQueue.onRequestArrived(() => {
            console.log(`continue request :${request.url()}`);
            request.continue();
        });
    });

    page.on('requestfinished', (request) => {
        console.log(`request finished:${request.url()}`);
        requestQueue.onRequestFinished(request);
    });

    page.on('requestfailed', (request)=>{
        console.log(`request failed:${request.url()}`);
        requestQueue.onRequestFinished(request);
    });

    await page.goto('https://tvn.pl', { timeout : 60000});
})();
`

**What is the expected result?**

Code should progress further through all the requests. Instead chrome requests queue keeps getting bigger. There is no such issue for example with https://onet.pl

**What happens instead?**
Code hangs on last resumed (continued) request.

**Comment by pironside44** [comment]
Did you ever find a solution to this by chance? I'm having the same problem
