### ISSUE TITLE
Is it possible to use 2 proxies or to change the proxy after chrome has launched?

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4814]
I'm looking for a way to use a different proxy depending on which request is intercepted. Is that supported by DevTools Protocol? I know you can launch with a proxy and use it throughout but I can't find any information about changing it once launched.

**Comment by salcc** [comment]
See #678.

**Comment by gajus** [comment]
You can use https://github.com/gajus/puppeteer-proxy to switch proxies on the fly, e.g.

```
import puppeteer from 'puppeteer';
import {
  createPageProxy,
} from 'puppeteer-proxy';

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const pageProxy = createPageProxy({
    page,
    proxyUrl: 'http://127.0.0.1:3000',
  });

  await page.setRequestInterception(true);

  page.once('request', async (request) => {
    await pageProxy.proxyRequest(request);
  });

  await page.goto('https://example.com');
})();

```

Requests will be proxied only when you call `pageProxy.proxyRequest`.
