### ISSUE TITLE
What's the deal with cookies?

### ISSUE THREAD

**Issue by dylanwilder** [puppeteer/puppeteer#482]
Getting an error from a page for not having cookies enabled.  I don't see any mention of cookies in this repository.

**Comment by Garbee** [comment]
Cookies are supported. Without knowing the page you're trying to work with there is no context for debugging the problem. Sounds like a site issue and not something with Puppeteer. Can you please provide a site where the problem reproduces for you?

**Comment by dylanwilder** [comment]
Looks like this was a red herring.
