### ISSUE TITLE
Can we rename the file that is being downloaded using puppeteer?

### ISSUE THREAD

**Issue by sayyamk** [puppeteer/puppeteer#4822]
* Puppeteer version: 1.19.0
* Platform / OS version:  Ubuntu 18.04.2 LTS
* Node.js version: 8.10.0

I am downloading a file through puppeteer into my directory. I need to upload this file to an s3 bucket so I need to pick up the file name. But the problem is, this file name has a time stamp that changes every time so I can't keep a hard coded name. So is there a way around this to get a constant name every time (even if the old file is replaced), or how to rename the file being downloaded?

**Comment by osmenia** [comment]
i am trying also to download file with headless: true, for me does not work. Can you pls paste you example code. tnx a lot

**Comment by DaveGeneral** [comment]
hey, I have the similar situation, existing examples usually change the file name after download operation using fs module, but I want to change it before the download start, have you solved it?

**Comment by DaveGeneral** [comment]
这是来自QQ邮箱的假期自动回复邮件。已收到，-_-

**Comment by DaveGeneral** [comment]
这是来自QQ邮箱的假期自动回复邮件。已收到，-_-
