### ISSUE TITLE
Installation fails on docker alpine since couple of days

### ISSUE THREAD

**Issue by BorntraegerMarc** [puppeteer/puppeteer#4823]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: -
* Platform / OS version: Alpine Linux
* URLs (if applicable):
* Node.js version: 8 & 10

**What steps will reproduce the problem?**

```
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge=~73.0.3683.103 \
      nss@edge \
      freetype@edge \
      freetype-dev@edge \
      harfbuzz@edge \
      ttf-freefont@edge
```

**What is the expected result?**

No error when installing with official command

**What happens instead?**

Error:
```
Step 3/12 : RUN apk update && apk upgrade &&     echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories &&     echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories &&     apk add --no-cache     chromium@edge=~73.0.3683.103     nss@edge     freetype@edge     freetype-dev@edge     harfbuzz@edge     ttf-freefont@edge
 ---> Running in 51bacf0c8993
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
v3.8.4-146-ga7c5a8cafa [http://dl-cdn.alpinelinux.org/alpine/v3.8/main]
v3.8.4-140-g6c6ec81281 [http://dl-cdn.alpinelinux.org/alpine/v3.8/community]
OK: 9570 distinct packages available
(1/7) Upgrading musl (1.1.19-r10 -> 1.1.19-r11)
(2/7) Upgrading busybox (1.28.4-r1 -> 1.28.4-r3)
Executing busybox-1.28.4-r3.post-upgrade
(3/7) Upgrading libressl2.7-libcrypto (2.7.4-r0 -> 2.7.5-r0)
(4/7) Upgrading libressl2.7-libssl (2.7.4-r0 -> 2.7.5-r0)
(5/7) Upgrading libressl2.7-libtls (2.7.4-r0 -> 2.7.5-r0)
(6/7) Upgrading ssl_client (1.28.4-r1 -> 1.28.4-r3)
(7/7) Upgrading musl-utils (1.1.19-r10 -> 1.1.19-r11)
Executing busybox-1.28.4-r3.trigger
OK: 6 MiB in 15 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  chromium-68.0.3440.75-r0:
    breaks: world[chromium~73.0.3683.103]
```

**Comment by BorntraegerMarc** [comment]
Changing the command to 
```
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge=~76.0.3809.87 \
      nss@edge \
      freetype@edge \
      freetype-dev@edge \
      harfbuzz@edge \
      ttf-freefont@edge
```

fixes the issue. I think it's because 2 days ago a new version was published on edge: https://pkgs.alpinelinux.org/packages?name=chromium&branch=edge&repo=community

The install command in the docs should be adapted: https://github.com/GoogleChrome/puppeteer/blob/656fe4604737bde07b2b8b2da4d63bd9fb4c152d/docs/troubleshooting.md#running-on-alpine

**Comment by BorntraegerMarc** [comment]
Fixed by using install command 
```
apk update && apk upgrade && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/community >> /etc/apk/repositories && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/main >> /etc/apk/repositories && \
    apk add --no-cache \
    chromium@3.10=~73.0.3683.103 \
    nss@3.10 \
    freetype@3.10 \
    freetype-dev@3.10 \
    harfbuzz@3.10 \
    ttf-freefont@3.10
```

if one wants to stay on chromium 73

**Comment by lulalachen** [comment]
Thanks for posting the solution.

**Comment by AndrejHafner** [comment]
Which version of Puppeteer did you use to get it working?

**Comment by BorntraegerMarc** [comment]
I'm using the latest one

**Comment by andrewboni** [comment]
This resolved it for me. Thanks @BorntraegerMarc

**Comment by kilgarenone** [comment]
Thank you for sharing your solution @BorntraegerMarc 

Btw, I still have to stick to Puppeteer@1.12.2 with this https://github.com/GoogleChrome/puppeteer/issues/4823#issuecomment-519911236

**Comment by AndrejHafner** [comment]
I tried using the code from @BorntraegerMarc with Puppeteer v1.19.0, but I get the following error: 
```
·[0m·[91mERROR: unsatisfiable constraints: 
·[0m  chromium-57.0.2987.133-r0: 
    breaks: world[chromium=76.0.3809.87] 
```

Docker image i'm using is node:8.9-alpine.

**Comment by BorntraegerMarc** [comment]
> I tried using the code from @BorntraegerMarc with Puppeteer v1.19.0, but I get the following error:

@AndrejHafner looks like you're trying to use an older version of chromium. I suggest you update puppeteer and use the install command from here: https://github.com/GoogleChrome/puppeteer/issues/4823#issuecomment-519911236

Or you search yourself in the linux alpine apk repo which version to install for chromium 57: https://pkgs.alpinelinux.org/packages

**Comment by nuragic** [comment]
Hi! Thanks for the tips... I think the docs should be edited to have a pinned version as well (i.e. the latest stable), the edge one is not reliable to work against a specific puppeteer version.

**Comment by nuragic** [comment]
⚠️ 🔥 🚒 🚨 

cc @BorntraegerMarc 

>Fixed by using install command
>apk update && apk upgrade && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/community >> /etc/apk/repositories && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/main >> /etc/apk/repositories && \
    apk add --no-cache \
    chromium@3.10=~73.0.3683.103 \
    nss@3.10 \
    freetype@3.10 \
    freetype-dev@3.10 \
    harfbuzz@3.10 \
    ttf-freefont@3.10
>if one wants to stay on chromium 73

Well this worked until Friday afternoon. **The real problem here is that Alpine deletes the old packages**. More info here: https://medium.com/@stschindler/the-problem-with-docker-and-alpines-package-pinning-18346593e891

This is the 3rd (and _last_ time ~I hope~) I'm forced to fix the build because of this... solution? Either setup an own mirror or stop using Alpine. I'll propose an update to the docs eventually.

**Comment by nuragic** [comment]
FYI Just opened https://gitlab.alpinelinux.org/alpine/apk-tools/issues/10661

If anyone knows about any official alpine mirror that doesn't delete the old packages it would be really welcome! 🙏

**Comment by mcarans** [comment]
If anyone comes across this issue, please go to https://gitlab.alpinelinux.org/alpine/apk-tools/issues/10661 and add your vote for the issue.
