### ISSUE TITLE
Puppeteer and Alpine Linux currently unstable

### ISSUE THREAD

**Issue by BrandonCopley** [puppeteer/puppeteer#4824]
It appears that Puppeteer 1.17.0 and Alpine Linux 3.10 work together nicely, however the latest version of Edge Linux's Chromium build of 76.0.3809.87-r0 is not compatible with any version of Puppeteer, 1.17.0, 1.18.0, or 1.19.0

Is there any chance we can get a new stable guide for running Puppeteer on Alpine Linux? and possibly a version 1.20 or 1.18.1, etc. that updates the chromium version?

**Comment by AndrejHafner** [comment]
Did you find any compatible versions?

**Comment by BrandonCopley** [comment]
Not for this version of Alpine

**Comment by abrantes01** [comment]
@BrandonCopley on which node-alpine version did you manage to fix this ?

**Comment by BrandonCopley** [comment]
This is how I'm able to run it. Would be great if we had an update as to if there are newer versions we can tie to.

    FROM keymetrics/pm2:10-alpine
    RUN apk add --no-cache git

    RUN apk update && apk upgrade && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/community >> /etc/apk/repositories && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@3.10=~73.0.3683.103 \
      nss@3.10 \
      freetype@3.10 \
      harfbuzz@3.10 \
      ttf-freefont@3.10
    ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

**Comment by abrantes01** [comment]
Ok ! I'll try your solution. :) 
But according to https://github.com/GoogleChrome/puppeteer/issues/4823#issuecomment-544396929, the old chromium package has been removed.

**Comment by nuragic** [comment]
👋 In my case I've solved it by ditching alpine for now in favor of the official node image (docs update here https://github.com/GoogleChrome/puppeteer/pull/5060). It was the quickest way for me, as I also don't need to manually install puppeteer from the Dockerfile.

**Comment by BrandonCopley** [comment]
Can you show us the docker image/how you're doing that setup?
-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by nuragic** [comment]
@BrandonCopley I added the Dockerfile in #5060 :)

**Comment by BorntraegerMarc** [comment]
I also have to say that I think currently it's not really well documented how to install puppeteer on alpine linux. The only thing the docs show is how to install the newest version of puppeteer with edge alpine linux.

But in our case in production we don't want to use alpine edge. We are using node v12 which depends on alpine linux v3.9

So it would be nice to have an install command for "long term production" use on alpine linux v3.9.

Also I don't know whether the support packages like:
```
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
```

are actually needed on alpine v3.9

**Comment by BrandonCopley** [comment]
Don't use Alpine linux, Alpine has a HUGE problem since they remove
outdated packages without warning.

It's not that much more work to use regular linux unfortunately.

-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by abrantes01** [comment]
I've also end up dropping Alpine for now :/
