### ISSUE TITLE
Protocol error (Page.captureScreenshot): Internal error

### ISSUE THREAD

**Issue by voxsoftware** [puppeteer/puppeteer#4829]
#3282 # Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.19.0
* Platform / OS version: GNU/Linux Ubuntu 18.04
* Node.js version: 10.15.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I am opening a web page and taking screenshot. After make some evaluates constantly on the same opened page, and when I try to take screenshots, shows me that error 

**What is the expected result?**
No error, get the screenshot

**What happens instead?**
```
Error: Protocol error (Page.captureScreenshot): Internal error at Promise (/root/.kawi/npm-inst/puppeteer@1.19.0/lib/Connection.js:183:56) at new Promise (<anonymous>:null:null) at CDPSession.send (/root/.kawi/npm-inst/puppeteer@1.19.0/lib/Connection.js:182:12) at Page._screenshotTask (/root/.kawi/npm-inst/puppeteer@1.19.0/lib/Page.js:915:39) at process._tickCallback (internal/process/next_tick.js:68:7) -- ASYNC -- at Page.<anonymous> (/root/.kawi/npm-inst/puppeteer@1.19.0/lib/helper.js:111:15) at _callee$ (/root/.kawi/gen/be5909676b83abd9977b0d6058ce9424.folder/app/functions/x/_screenshot.coffee:56:25) at tryCatch (/root/Kawix/core.0.6.4/crossplatform/src/runtime.js:46:40) at Generator.invoke [as _invoke] (/root/Kawix/core.0.6.4/crossplatform/src/runtime.js:272:22) at Generator.prototype.(anonymous function) [as next] (/root/Kawix/core.0.6.4/crossplatform/src/runtime.js:98:21) at asyncGeneratorStep (/root/.kawi/gen/be5909676b83abd9977b0d6058ce9424.folder/app/functions/x/_screenshot.coffee:8:103) at _next (/root/.kawi/gen/be5909676b83abd9977b0d6058ce9424.folder/app/functions/x/_screenshot.coffee:10:194) at process._tickCallback (internal/process/next_tick.js:68:7)
``` 

I want ask, what can be the reason to receive that error

**Comment by AutoSponge** [comment]
I'm using the CDP and, with the latest version of Chrome (76.0.3809.100 Mac 64-bit), getting strange errors as well. In my case, I see "Devtools was disconnected from the page..." If this is happening to you but Puppeteer swallows the message, it's possible the result is a protocol error.
