### ISSUE TITLE
Add warning for non-existent methods in latest release

### ISSUE THREAD

**Issue by tejashah88** [puppeteer/puppeteer#483]
It would be nice to add a note for the methods that are not part of the latest release, so that people won't be confused as to why `xyz` method doesn't exist, such as in #470.

While the temporary solution is to simply install from the github repository (`npm install https://github.com/GoogleChrome/puppeteer/`), it's not obvious in the [currrent documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md).

Here's a possible example for how to fix this:

**Disclaimer**: This version of the documentation refers to the tip-of-tree version of this library. If you are receiving an error such as `page.xyz is not a function`, this means that it is not part of the latest release. To download the tip-of-tree version, run `npm install https://github.com/GoogleChrome/puppeteer/`.

#### page.content() [not part of latest release (link to disclaimer)]
- returns: <[Promise]<[String]>>

Gets the full HTML contents of the page, including the doctype.

Obviously not perfect but better than nothing.

**Comment by Garbee** [comment]
I think it would be best for us to look into doing some form of continuous deployment of new versions when code changes that affects end users. Instead of maintaining little warnings in the docs that will need to be constantly updated/removed.

**Comment by ebidel** [comment]
What if we point the readme "API" docs link to the latest release instead of master?

"[API (v0.9)](https://github.com/GoogleChrome/puppeteer/blob/v0.9.0/docs/api.md)"

....but there are many entry points into the docs.

Maybe we should start thinking about publishing API docs per release to gh-pages and link everything to that.

**Comment by SirZorg** [comment]
I ran npm install https://github.com/GoogleChrome/puppeteer/ because I want to access page.content

How do I specify which module I am referencing with puppeteer =  require('puppeteer'), as currently this doesn't give me page.content

**Comment by tejashah88** [comment]
The code should work exactly the same. Try deleting your `node_modules` folder and reinstalling the dependencies again.

**Comment by aslushnikov** [comment]
We bumped the package version and added a reference to the released api in the very beginning of [api documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md). It should be less confusing now.

![image](https://user-images.githubusercontent.com/746130/29639162-a67a7166-880e-11e7-9bef-ef3c723f6f7b.png)
