### ISSUE TITLE
Wait until spinning wheel on chrome stops ?

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#4833]
Is there an event to detect when the tab's loading spinning wheel on chrome stops ? I tried:

`networkidle0, networkidle2, domcontentloaded`

with no success

ex of page when I need to wait until it is loaded: https://www.translatetheweb.com/?from=&to=fr&ref=SERP&refd=www.bing.com&dl=fr&rr=UC&a=https%3a%2f%2fwww.247freepoker.com%2f

For now I use a 30 seconds waitFor

Regards

**Comment by kblok** [comment]
I think #1361 might help. I answered your question on SO https://stackoverflow.com/questions/57459275/how-to-wait-until-loading-chrome-tabs-spinning-wheel-stops
