### ISSUE TITLE
Weird bug where page is not fully loaded after `load` event

### ISSUE THREAD

**Issue by Fenntasy** [puppeteer/puppeteer#4845]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Linux in a docker container
* URLs (if applicable): -
* Node.js version: 12.2

**What steps will reproduce the problem?**

I can't really reproduce the problem as it does not occur reliably and it seems linked to one of the page I'm working on but we don't seem to be able to make it reproducible.

But here is the gist of it:

```js
Promise.all([
    page.waitForNavigation(),
    page.click(".some-link"),
    page.waitFor(5000)
  ]).then(() => page.type("input[type=email]", email, { delay: 50 }))
```
(I know the `page.waitFor(5000)` is not necessary but it's in a generic `clickAndWait` function because we have to deal with several redirects in other parts of our tests. This is not the case here but I let it for completeness sake)
Sometimes the `type` works, other times it doesn't because the page is not fully loaded.
Here is what I attempted to troubleshoot the problem:

```js
Promise.all([
  page.waitForNavigation(),
  page.click(".some-link"),
  page.waitFor(5000)
]).then(() => page.$("input[type=email]"))
.then(input => {
  if (input === null) {
    return page.content().then(console.log)
  }
).then(() => page.type("input[type=email]", email, { delay: 50 }))
```

And here is the weird part, the `console.log` of the HTML was not consistent, we had either the full page loaded correctly or a shell of page with the `<head>` that was correct and the first two lines of the `<body>` but in both cases, the `input` was not found so I assume that the partially loaded page is the culprit.
Keep in mind that there was times where there was no problem and the `input` was typed into correctly. I don't have a reliable percentage of occurrences but it failed roughly 30 to 50% of the time.

I assume that we sometimes have the full page because `page.content` is asynchronous and sometimes the page had the time to load between the `page.$` and the `page.content`. 

**What is the expected result?**

`page.waitForNavigation` by default wait for the `load` event which means that the whole page should have loaded.

**What happens instead?**

In some cases, it seems to load before the whole page has loaded.

---

We ended up adding 

```js
  page.waitForSelector('input[type=email]', { visible: true, timeout: 0 })
```

before calling `page.type` which seems to work for now but it seems weird to do more waiting. The page should be loaded in those 5 seconds.

I'm really sorry to not have a reproducible error but I would be glad if somebody had ideas as to what happens and what to do.

**Comment by kblok** [comment]
If the page has some animation. It would be possible that the input is not ready on load.
I tend to use `waitForSelector` in these scenarios. There is nothing wrong with that.

**Comment by Fenntasy** [comment]
Thanks for the input.

Yes that would be a scenario where I would find that normal too. But this is a plain web page, served by an elixir app without anything fancy. There is no lazy loading, no client javascript (no react/angular/vue or the like). The page is sent plain and simple.
