### ISSUE TITLE
How to close browser after Navigation Timeout?

### ISSUE THREAD

**Issue by micilini** [puppeteer/puppeteer#4847]
I have this code below made with nodejs + puppeteer, whose goal is to take a screenshot of the user's site:

```
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('http://MY_WEBSITE/try/slowURL',{timeout: 30000, waitUntil: 'networkidle0' });//timeout 30 seconds
await page.setViewport({width: 1920, height: 1080});
await page.screenshot({path: pathUpload});
await browser.close();
```

Its operation is quite simple, but to test the timeout I created a page (`http://MY_WEBSITE/try/slowURL`) that takes 200 seconds to load.

According to the puppeteer timeout (`timeout: 30000`), there is a 100% chance of a **Navigation Timeout Exceeded: 30000ms exceeded** error happening, especially because I'm forcing it.

**THE PROBLEM**

Through the htop command (used in linux), even after the system crashes and shows **"TimeoutError"**, I can see that the browser has not been closed.

And if the browser is not closed, as scans were done, there is a good chance that the server will run out of memory, and I don't want that.

How can I solve this problem?

**Comment by hlr1983** [comment]
I think try...catch...finally statement (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) should work.

```javascript
try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('http://MY_WEBSITE/try/slowURL',{timeout: 30000, waitUntil: 'networkidle0' });//timeout 30 seconds
    await page.setViewport({width: 1920, height: 1080});
    await page.screenshot({path: pathUpload});
} finally {
    await browser.close();
};
```

OR

```javascript
try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('http://MY_WEBSITE/try/slowURL',{timeout: 30000, waitUntil: 'networkidle0' });//timeout 30 seconds
    await page.setViewport({width: 1920, height: 1080});
    await page.screenshot({path: pathUpload});
} catch (e) {
    if (e instanceof TimeoutError)
        await browser.close();
};
```

**Comment by sunmasters** [comment]
Well,
Your browser not closing because your page is still yet be loaded,
and
`browser.close();`
won't run if it has timeout error.
And
You wanted take screenshot of the page which has 200 secs to load, its too much.
