### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by SalgadoDoce** [puppeteer/puppeteer#4848]
const puppeteer = require('puppeteer');
      Emitter = require('events');
      path = require('path')

module.exports = class HaxballHost extends Emitter{
    constructor(opt = {}) {
        super()
        this.userDataDir = opt.userDataDir || path.join(__dirname, '..', 'user-data-dir');
        this.userDataDir = path.resolve(process.cwd(), this.userDataDir);

    }
    async openRoom(obj = {}) {
        this.browser = await puppeteer.launch({headless: obj.headless,
            devtools: obj.devtools,
            userDataDir: this.userDataDir,
            args: [
              `--remote-debugging-port=3066`,
              `--no-sandbox=false`
            ]
          });
        this.page = await this.browser.newPage();
        await this.page.setViewport({ width: 500, height: 400 });
        await this.page.goto('https://haxball.com/headless', {waitUntil: 'networkidle2'});
        await this.page.addScriptTag({path: obj.room});
        this.browser = await puppeteer.connect({
            browserURL: `http://localhost:3066`
          });
        return this.browser
    }
}

error:

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/mythicalBot/node_modules/puppeteer/lib/Launcher.js:349:14)
    at Interface.<anonymous> (/root/mythicalBot/node_modules/puppeteer/lib/Launcher.js:338:50)
    at Interface.emit (events.js:208:15)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:557) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:557) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kjr247** [comment]
I'm seeing the exact same issue.

version "puppeteer": "1.19.0",
OS windows 10
Example of the breaking code:
https://github.com/crespowang/serverless-lambda-puppeteer

Article for code:
https://medium.com/swlh/how-to-create-pdf-in-lambda-using-puppeteer-6355348b8a82

**Comment by kjr247** [comment]
Are you on windows or mac? I was on windows trying to follow a mac guide. The fix for me was to just not set the executablePath to the mac version of the puppeteer package, and use puppeteer instead of puppeteer-core.
