### ISSUE TITLE
 ​ ​​​​Multiple ​process​ , ​more than 900 ​​request in same time ​, how can i handle ?

### ISSUE THREAD

**Issue by historylife** [puppeteer/puppeteer#485]
Dear support .
I am new to this project , so please excuse my naive information.
let's say we have a 900 request to a different websites , which it has to run in same time .
`Request mean : open page and do some stuff within the page / clicks / etc.
`
But each request  will start by a different node command , well it will be send form php script.
`shell_exec('node script.js');`

So what is the best way to maintain stability , some one advice me to open  Multiple Tabs , but i don't know how can i start main Chrome process and each time i need to send a new request , the script will ask chrome to open a new tab. not open a new browser !

i am not sure what is the best way to do this approach !

Please Advice

**Comment by aslushnikov** [comment]
> So what is the best way to maintain stability , some one advice me to open Multiple Tabs , but i don't know how can i start main Chrome process and each time i need to send a new request , the script will ask chrome to open a new tab. not open a new browser !

You can connect to a running chromium instance via [`puppeteer.connect`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions) method. 

I would not recommend opening a lot of tabs in a single browser. It might be better to have a request queue and process it with some finite amount of browser tabs (e.g. 4).

**Comment by paambaati** [comment]
@aslushnikov I have a similar use-case, and I've built a farm of instances - each running 1 Chrome window, and each request opening in a new tab. I've noticed that this works for 2-3 days, before Chrome segfaults. Each Chrome window has opened and closed roughly 2k tabs by that time

Are there some tunables that we can tweak to avoid/reduce the crashes? Would sharing core dumps help?

**Comment by aslushnikov** [comment]
@paambaati this sounds like a chromium bug! If you can file it at [crbug.com/new](https://crbug.com/new) and attach the crash dumps / stack traces, that would be really valuable.

You can also post a link to the chromium bug here to speedup bug triage.

**Comment by rohmanhm** [comment]
Hi, @aslushnikov would you give us some examples using `connect()`?
I can't make it work somehow.

**Comment by pawurb** [comment]
@rohmanhm I know it's a big late but here's a code I use for reusing connection:

```
const puppeteer = require('puppeteer');

const createBrowser = async() => {
  let browser;
  let browserWSEndpoint;
  try {
    browser = await puppeteer.launch({
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox'
      ]
    }).then(async browser => {
      browserWSEndpoint = browser.wsEndpoint();
    })
  } catch (err) {
    console.log(err)
  } finally {
    console.log(browserWSEndpoint)
  }
 };

createBrowser()
```

```
const browser = await puppeteer.connect({
   browserWSEndpoint: browserEndpoint,
   ignoreHTTPSErrors: true
 });
```

`browserWSEndpoint` values is passed between scripts with Ruby I am using to call the scripts so it's not relevant.

I use https://github.com/foreverjs/forever to keep the browser instance running as a daemon:

`forever start node/createBrowser.js`

Hope that helps.

I am still working on how to make process of reusing browser instances running smoothly so any tips on that would be great.

**Comment by taewookim** [comment]
@pawurb What do you do in case the browser crashes?

**Comment by tanys123** [comment]
Hi @aslushnikov 

> I would not recommend opening a lot of tabs in a single browser. It might be better to have a request queue and process it with some finite amount of browser tabs (e.g. 4).

May you explain the downside of opening many tabs in single browser? We want to optimize the performance and this is the way I tested to perform well. We do close tab after a request is complete.
