### ISSUE TITLE
Unable to get element childNodes/children

### ISSUE THREAD

**Issue by noahbetzen-wk** [puppeteer/puppeteer#4852]
```
var listSelector = "#list"
var listElement = await page.$(listSelector);
var listChildren = await page.evaluateHandle(e => e.children, listElement);
// listChildren is null here
```

I've tried dozens of other ways, including using [`elementHandle.getProperties` as described here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlegetproperties), and I can't get a list of children.

My end goal is to get a list, iterate through all the children, and then click on one of the children based on its text. I can do the text clicking part, but I'm having a heck of a time getting node children.

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with the simplified test:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const selector = 'body div';
    const element = await page.$(selector);
    const children = await page.evaluateHandle(e => e.children, element);

    console.log(children.toString());

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
Output:
```
JSHandle@array
```
Maybe it is worth to provide a small but complete script to reproduce your issue.

**Comment by sunmasters** [comment]
If You know JQUERY,
use it.  
```
const childrn= await page.eval(()=>{
//jquery code and css selector
});
```

**Comment by noahbetzen-wk** [comment]
@vsemozhetbyt I can do that and get the `JSHandle`, but I'm unable to access any of the children.

Looking at the [API documentation for JSHandle](https://github.com/GoogleChrome/puppeteer/blob/v1.19.0/docs/api.md#class-jshandle), I'm not sure how to actually access the array.

**Comment by vsemozhetbyt** [comment]
To iterate over children, you have at least 2 options: 1) transfer all the iteration logic to the browser context and get the final data; 2) get an array of JSHandles to iterate over it:
```js
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    // Way 1.
    const childrenNames = await page.evaluate((selector) => {
      const names = [];
      for (element of document.querySelector(selector).children) {
        names.push(element.tagName);
      }
      return names;
    }, 'body div');
    console.log(childrenNames);

    // Way 2.
    const elements = await page.$$('body div > *');
    const names = [];
    for (const element of elements) {
      names.push(await (await element.getProperty('tagName')).jsonValue());
    }
    console.log(names);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by noahbetzen-wk** [comment]
What I ended up doing is something like:

```
const elementChildren = await page.evaluateHandle(e => {
    const children = e.childNodes;
    const list = [];
    for (let i = 0; i < children.length; i++) {
        const child = children[i];
        if (child.getAttribute("something") === "value") {
            list.push(child);
        }
    }
    return list;
}, rootElement);

... then ...

const childrenAsElements = [];
const rootProperties = await elementChildren.getProperties();
for (const item of rootProperties.values()) {
    const element = item.asElement();
    if (element) {
        childrenAsElements.push(element);
    }
}
```

And then iterating over it like:

```
await asyncForEachArray(childrenAsElements, async (item) => {
    const text = await page.evaluate(e => e.textContent, item);
    if (text === textToClick) {
        await item.click()
    }
});

... which is a helper function ...

async function asyncForEachArray(array, callback) {
    for (let index = 0; index < array.length; index++) {
        await callback(array[index]);
    }
};
```

**Comment by aaronpeterson** [comment]
Is there really no way to traverse/find within an ElementHandle? @maheshjukanti referred to page level selection which is unrelated to the question.  @noahbetzen-wk I am sorry you had to type so much code to accomplish something so common and basic that is absolutely absurd.  How is this accomplished with css selectors similar to jquery's find() etc?

**Comment by willy2dg** [comment]
A bit late, but just in case it's still useful or someone comes here from Google. You can use the ':scope' selector.

```
let $parent = await page.$('#parent')
let $childs = await $parent.$$(':scope > *')
```

**Comment by williamyorkl** [comment]
> A bit late, but just in case it's still useful or someone comes here from Google. You can use the ':scope' selector.
> 
> ```
> let $parent = await page.$('#parent')
> let $childs = await $parent.$$(':scope > *')
> ```

superb！！！

**Comment by EduardoHidalgo** [comment]
@willy2dg yo, it worked! Let me give you a hug <3
