### ISSUE TITLE
page.setContent not referencing a local file through <link href=""> tag

### ISSUE THREAD

**Issue by ziyaaktas** [puppeteer/puppeteer#4853]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.19.0
* Platform / OS version: MacOS 10.13.6 / Ubuntu 16
* URLs (if applicable):
* Node.js version: 8.12.0

**What steps will reproduce the problem?**

Use setContent method with a locally referenced css file in the content.

_Please include code that reproduces the issue._

```
const const htmlContent = `
<html>
<head><link href="./tmp/xxx.css" rel="stylesheet"></head>
</html>`
await page.setContent(htmlContent, { waitUntil: 'networkidle0' })
```

1.  
2.
3.

**What is the expected result?**

Css file is used by puppeteer.

**What happens instead?**

Css file doesn't seem to be located.  I am actually not sure if this is possible or what the rule here is as I just can't find any documentation about this.

**Comment by ziyaaktas** [comment]
I came up with the solution of inserting inline code or base64 conversions, and it works fine, but I still would like to know if this pattern is supported or not.

**Comment by corte** [comment]
Why is this closed? I have the same problem!

Care to share your solution?

**Comment by ziyaaktas** [comment]
@corte Because of security issues, actually this behavior is not supported.  For images you can do base64 or whatever.  For css, you can post your css on a cdn and pull it from there.

**Comment by weoreference** [comment]
The solution has not been explained or referenced in the documentation, nor has an example been offered. Please consider reopening this concern, thank you

**Comment by pguardiario** [comment]
Today you can `await page.addStyleTag({path})`

**Comment by unvaru** [comment]
> The solution has not been explained or referenced in the documentation, nor has an example been offered. Please consider reopening this concern, thank you
> 
> Specifically, why won't local CSS files work even when doing
> 
> ```
> await page.addStyleTag({ path: './local-file.css' }) 
> 
> await page.setContent({ '<h1 class="sample">Hello</h1>}) ```
> 
> In this example, the CSS fails to style the markup
> ```

Try moving the `addStyleTag` line after the `setContent`. This worked for me.
