### ISSUE TITLE
Login credentials for puppeteer running on docker in headless mode

### ISSUE THREAD

**Issue by edward-charny** [puppeteer/puppeteer#4855]
I am running puppeteer on a docker container in headless mode to test our website. The first page is the login page. The puppeteer script and docker files are stored in an internal git repo. What is a good way of securely storing the login credentials?

Obviously not as a file in the git repo. Docker secrets is an option, what are some other options? I need puppeteer to be able to read them and enter them without any user intervention.

**Comment by matthaywardwebdesign** [comment]
Docker secrets are probably your best bet. Alternatively using environment variables through the use of an .env file (that isn't committed). 

[https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)
