### ISSUE TITLE
MediaRecorder doesn't work

### ISSUE THREAD

**Issue by LawlietRyuzaki** [puppeteer/puppeteer#4858]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.19.0
* Platform / OS version: Win10 x64
* URLs (if applicable): -
* Node.js version: 10.16.0

**What steps will reproduce the problem?**

I use puppeteer to accept and send back user's media stream (video + audio), it works, user can see his stream returned from server.
I want to record user stream inside puppeteer:

```javascript
const mediaRecorder = new MediaRecorder(<user's stream from RTCPeerConnection>);
mediaRecorder.start(100);
mediaRecorder.addEventListener('dataavailable', ev => {
  console.log(ev.data.size);
});

// in another place I call mediaRecorder.stop();
```

**What is the expected result?**
I expected that dataavailable event will be fired every 100ms with of stream and after I call stop()
`ev.data.size` shouldn't be zero

**What happens instead?**
dataavailable event was fired once(on stop()) and ev.data.size is 0 (ev.data.type is some right codec)

The same code for user's local stream works fine in browser (Chrome 76.0.3809.100)

**Comment by LawlietRyuzaki** [comment]
Update:

Idk why, but if I add `video` tag to the document with this stream as `srcObject` - all works `¯\_(ツ)_/¯`

This is how it should work? Can I do something to not add elements to the document?

**Comment by demesm** [comment]
> Update:
> 
> Idk why, but if I add `video` tag to the document with this stream as `srcObject` - all works `¯\_(ツ)_/¯`
> 
> This is how it should work? Can I do something to not add elements to the document?

Can you tell me how you went about this in puppeteer? I'm trying to record a canvas and data size is always 0.

**Comment by igormarga** [comment]
Any solutions?

**Comment by tiger2380** [comment]
did anyone figure out how to resolve this issue?
