### ISSUE TITLE
Why promisse all instead of two awaits on navigation

### ISSUE THREAD

**Issue by adrianog3** [puppeteer/puppeteer#4859]
I'm using pupperteer v1.19.0 and i had problems while navigating between pages.

I was trying use waitForNavigation after click, both with await, but it didn't work.

Example:

```javascript
await page.click('#my-button');
await page.waitForNavigation({ waitUntil: 'networkidle0' });
```

However, i used this following code and it worked.

```javascript
await Promise.all([
    page.click('#my-button'),
    page.waitForNavigation({ waitUntil: 'networkidle0' })
]);
```

The problem happened when i tried use the following code:

```javascript
const text = await page.evaluate(() => {
    return document.querySelector('#my-div').innerHTML;
});
```

The return of that function null is.

Why it works the second way, but not in the first?

**Comment by hlr1983** [comment]
I think the code below should work
```javascript
await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click('#my-button'),
]);
await page.waitForSelector('#my-div');
const text = await page.evaluate(() => {
    return document.querySelector('#my-div').innerHTML;
});
```

First, use click and waitForNavigation as the doc says:
> Bear in mind that if click() triggers a navigation event and there's a separate page.waitForNavigation() promise to be resolved, you may end up with a race condition that yields unexpected results. The correct pattern for click and wait for navigation is the following:
> 
> ```javascript
> const [response] = await Promise.all([
>   page.waitForNavigation(waitOptions),
>   page.click(selector, clickOptions),
> ]);
> ```
> https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-pageclickselector-options

Then you should waitForSelector #my-div before your evaluate. You might avoid the waitForSelector if you use options like load or domcontentloaded in waitForNavigation, but it depends on how your page works (for example, see https://github.com/GoogleChrome/puppeteer/issues/598).

**Comment by adrianog3** [comment]
I hadn't found this documentation. Now I understand, thanks for the answer!
