### ISSUE TITLE
The profile appears to be in use by another Chromium process on another computer

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4860]
I'm getting this pop up prompt on launch when I add data dir:

> The profile appears to be in use by another Chromium process (11913) on another computer (5af43e7dde40). Chromium has locked the profile so that it doesn't get corrupted. If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chromium.

If I click "unlock" it works perfectly. It there any way to suppress that error or click unlock automatically? I am on ubuntu and not using the chromium that comes with puppeteer.

I tried googling it and people say to run this but it doesn't seem to fix it.
```
execSync('rm -rf ~/.config/chromium/Singleton*', {stdio: 'inherit'})
```

**Comment by ghost** [comment]
I was able to fix it by using:
```
execSync(`rm -rf ${profilePath}/Singleton*`, {stdio: 'inherit'})
```

**Comment by itsKV** [comment]
@dave-dm 
How to use this? and where? 
plz. That will be helpful. non-IT guy here.

I am using chromium window in KIOSK mode on RaspberryPI 3b+. Pi is configured on DHCP. Every reboot, I am getting the same error and I have to manually click on Relaunch button to start KIOSK. (Raspbian)

**Comment by ghost** [comment]
I've been using this function
```javascript
const path = require('path')
const fs = require('fs')

const deleteSingletonFiles = (absoluteProfilePath) => {
  try {
    const files = fs.readdirSync(absoluteProfilePath)
    for (const file of files) {
      if (file.match('Singleton')) {
        const filePath = path.join(absoluteProfilePath, file)
        console.log(`deleting ${filePath}`)
        fs.unlinkSync(filePath)
      }
    }
  }
  catch (e) {}
}
```

**Comment by itsKV** [comment]
Thanks for reply. 

`rm -rf ~/.config/chromium/Singleton*`
executing this command solved my problem.

**Comment by d0zingcat** [comment]
> Thanks for reply.
> 
> `rm -rf ~/.config/chromium/Singleton*` executing this command solved my problem.

If you want to keep your cookie or history data or anything else, you just need to remove `xxx/SingletonLock` file.

**Comment by LouisLanganay** [comment]
``rm -rf ~/.config/chromium`` and ``rm -rf ~/.config/google-chrome-stable`` works for me

**Comment by TrungAzieL** [comment]
for me is `rm -rf ~/.config/google-chrome`. Or you can check `~/.config` folder and delete every relevant to chrome.

**Comment by archenroot** [comment]
On my Ubuntu 22.04.3 system I installed chromium via snap:
```
 zangetsu  HP-Z840  ~/.config  locate Singleton |grep chromium
/home/zangetsu/snap/chromium/common/chromium/SingletonCookie
/home/zangetsu/snap/chromium/common/chromium/SingletonLock
/home/zangetsu/snap/chromium/common/chromium/SingletonSocket
```

so had to delete above files and it started working

**Comment by NkwaTambe** [comment]
To fix issue on ubuntu 22.04.1 , use the command  "sudo rm -rf ~/.config/google-chrome"

or better still navigate to the ~/.config directory( cd ~/.config ) and remove anything related to chrome.

**Comment by westerj** [comment]
Found 3 broken symlinks in ~user/.config/google-chrome named SingletonCookie, SingletonLock and SingletonSocket.  Deleted those and google-chrome would start properly.

**Comment by Wheaties466** [comment]
Is there no way to unlock the profile in the command line other than deleting the files?

**Comment by KAVIN-KJ** [comment]
> Is there no way to unlock the profile in the command line other than deleting the files?

Deleting the Singleton lock file alone worked out for me. All I did was just navigate to my profile
.config/google-chrome/(my profile folder) and delete the Lock File

**Comment by devodii** [comment]
> for me is `rm -rf ~/.config/google-chrome`. Or you can check `~/.config` folder and delete everything relevant to chrome.

thanks, this solved the problem.

**Comment by Cap0n3** [comment]
> > Thanks for reply.
> > `rm -rf ~/.config/chromium/Singleton*` executing this command solved my problem.
> 
> If you want to keep your cookie or history data or anything else, you just need to remove `xxx/SingletonLock` file.

Same error here. This solution worked for me.
