### ISSUE TITLE
Get Response HEADERS OF specified url?

### ISSUE THREAD

**Issue by sunmasters** [puppeteer/puppeteer#4861]
Someone can help me?
I want to get a response header of a url in iframe tag?
`<iframe src="**url**">`
How can i achieve this?

**Comment by vsemozhetbyt** [comment]
Maybe [page.waitForResponse()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforresponseurlorpredicate-options) + [response.headers()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#responseheaders) can help?

**Comment by sunmasters** [comment]
@vsemozhetbyt Thanks for your suggestion. But It did't not work for me, because 

> `<iframe> is under another iframe tag and url is loaded before Iam get the URL values with javascript.`


- I added MY Custom method to networkmanager.js file under puppeteer.
- It is working now. 
Any New Suggestions? add here.
