### ISSUE TITLE
page.waitForXPath, {visible:true} on a second element after a first instance inside a hidden element times out

### ISSUE THREAD

**Issue by michaelrommel** [puppeteer/puppeteer#4867]
* Puppeteer version: 1.19.0
* Platform / OS version: Ubuntu 18.04
* Node.js version: 12.7.0

The following HTML page (called /success1):
```
<html>
<head>
  <style>
    .ng-hide{display: none !important;}
    .nohide{display: flex;} 
    .success{color: rbg(255,0,0);}
  </style>
</head>
<body>
  <my-notification class="ng-hide" aria-hidden="true">
    <div class="success">Success</div>
  </my-notification>
  <my-notification class="nohide" aria-hidden="false">
    <div class="success">Success</div>
  </my-notification>
</body>
</html>
```

The following last test for the XPath with the visible my-notification element 
```
it('should display a success message', async () => {
    await page.goto('http://localhost:3000/', {
      waitUntil: 'networkidle0'
    })
    let eh = await page.waitForXPath('//a[contains(text(),"Success1")]',
      { visible: true })
    await expect(eh).toBeDefined()
    await eh.click()

    eh = await page.waitForXPath('//my-notification/div[@class="success"]',
      { visible: true })
    await expect(eh).toBeDefined()
  }, 3000)
```
does timeout. It does not find the second visible my-notification/div.

As soon as I make the first notification visible or swap both instances in the html, it works,

Update: Further tests show, that if there are multiple elements matched by the XPath, and the first one is there, but invisible, the second one is not evaluated anymore.

**Comment by TayyabSalman** [comment]
Did you find the solution @michaelrommel ?

**Comment by michaelrommel** [comment]
Unfortunately I did not find a solution. Only after I made the XPath so specific, that it only ever matches exactly one element, it worked. Bummer...
