### ISSUE TITLE
Execution ~300x Slower when page backgrounding take a place (headful mode)

### ISSUE THREAD

**Issue by Gdocal** [puppeteer/puppeteer#4868]
* Puppeteer version: 1.19.0
* Platform / OS version: Windows 10
* Node.js version: doesn't matter

Here is a simple test which shows the problem.  In the test we measure the time of the mouse movement, when the page is visible execution of the test is almost instant, but as soon as we minimize chrome, everything gets incredibly slow. But actually the problem is not in minimization, it is just the fastest way to reproduce the issue, in production I noticed the same behavior even when the page is maximized but not visible because another maximized windows is on top, also the same behavior detected when we open new tab in chrome and make it active.
Even more when the page goes to this 'slow' mode, some js function just stops to work, for example IntersectionObserver callback never called in this mode (https://github.com/GoogleChrome/puppeteer/issues/3156#issuecomment-522600282). This object is used by a puppeteer in click function, and as result Click doesn't work.

In the test, I used mouse movement from (1,1) to (100,100) and back x25 times.
I tried to change the distance from (1,1) to (10,10) but the execution time is not changed it doesn't depend on distance. But as far I removed one of two calls of mouse movent inside cycle and changed it to move to i, execution time reduced twice:
```js
for(var i=0;i<25;i++){
   await page.mouse.move(1, 1);
   await page.mouse.move(100, 100);
}
```
changed to =>>>>
```js 
for(var i=0;i<25;i++){
    await page.mouse.move(1, i);
}
```
Also I recorder timeline of page buy using provided api 'page.tracing.start' and here is files:
[trace_ok.json.log](https://github.com/GoogleChrome/puppeteer/files/3521410/trace_ok.json.log)
[trace_slow.json.log](https://github.com/GoogleChrome/puppeteer/files/3521411/trace_slow.json.log)
Files can be viewed via https://chromedevtools.github.io/timeline-viewer/

As we can see events executes only every 5 seconds. 
We should have a way to disable this behavior in chrome and do not throttle execution.
I tried to use these command-line switches but no result:
"--disable-background-timer-throttling",
"--disable-backgrounding-occluded-windows"

Code to reproduce issue:
```js
const puppeteer = require('puppeteer');

(async () => {
    var baseTime=Date.now();

  const browser = await puppeteer.launch({
    headless: false,
//    executablePath :"C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
  });
  const page = await browser.newPage();
  await page.goto('https://github.com/',{waitUntil:'load'});

 
  console.log('Start test#1');
  await page.tracing.start({path: 'trace_ok.json'});
  var hrstart = process.hrtime()
  for(var i=0;i<25;i++){
      await page.mouse.move(1, 1);
      await page.mouse.move(100, 100);
  }
  await page.tracing.stop();
  hrend = process.hrtime(hrstart)
  console.info('Execution time normal mode: %ds %dms', hrend[0], hrend[1] / 1000000)
  
  console.log('Please minimize chrome now');
  process.stdout.write('\x07');
  console.log('Wait for user  to minimize chrome');
  await sleep(5000);

  console.log('Start test#2');
  hrstart = process.hrtime()
  await page.tracing.start({path: 'trace_slow.json'});
  for(var i=0;i<25;i++){
      await page.mouse.move(1, 1);
      await page.mouse.move(100, 100);
  }
  await page.tracing.stop();
  hrend = process.hrtime(hrstart)
  console.info('Execution time throttled mode: %ds %dms', hrend[0], hrend[1] / 1000000)
  
  function sleep(ms){
    return new Promise(resolve=>{
        setTimeout(resolve,ms)
    })
}
})();

```
output:

> Start test#1
> Execution time normal mode: 0s 823.829ms
> Please minimize chrome now
> Wait for user  to minimize chrome
> Start test#2
> Execution time throttled mode: 250s 121.6708ms

**What is the expected result?**
Execution time should be similar whenever the application is minimized or in a normal state when devtools is active.

**What happens instead?**
When page window is minimized, execution performance 1000x slower, and some js features doesn't work.

**Comment by Gdocal** [comment]
Update:

- When a DevTools window is open and the page is in the background - performance is **NOT (!!!!) throttled**

- if tab playing sound - performance still **throttled**, even 

> Applications playing audio are considered foreground and aren’t throttled. https://developers.google.com/web/updates/2017/03/background_tabs

- Tried to use Google Chrome Policy to disable this throttling by setting the parameter '**Enables or disables tab lifecycles**' to **Disabled** - performance still **throttled**

- Also tried to disable next features: **ExpensiveBackgroundTimerThrottling, RenderingPipelineThrottling, TimerThrottlingForHiddenFrames** with command line '--disable-features=....' - performance still **throttled**


so why when devtools window is open everything works fine, but when we connect to devtools protocol nothing works as expected?

**Comment by Gdocal** [comment]
Update:
Quick and dirty fix for this bug is to use Devtools protocol and to send 2 next commands:
DOM.enable
Overlay.enable

**Comment by this-is-jassa** [comment]
> Overlay.enable

It worked, but how?

**Comment by AndriusCTR** [comment]
> > > Update: Quick and dirty fix for this bug is to use Devtools protocol and to send 2 next commands: DOM.enable Overlay.enable
> > 
> > 
> > At what point during script lifecycle I should send them again? If at all? Lets say background window becomes foreground and then later becomes background. Should I send those commands again? Or just send them once when / after puppeteer connects and that's it? Thanks
> 
> I just had to run it once per "session". After that it... doesn't matter if I put the window in foreground or background. It's just working as expected.

Thanks. Do you have a small sample code to show how exactly you run it for your 'session'? You mean after puppeteer connect?

**Comment by AndriusCTR** [comment]
> > > > > Update: Quick and dirty fix for this bug is to use Devtools protocol and to send 2 next commands: DOM.enable Overlay.enable
> > > > 
> > > > 
> > > > At what point during script lifecycle I should send them again? If at all? Lets say background window becomes foreground and then later becomes background. Should I send those commands again? Or just send them once when / after puppeteer connects and that's it? Thanks
> > > 
> > > 
> > > I just had to run it once per "session". After that it... doesn't matter if I put the window in foreground or background. It's just working as expected.
> > 
> > 
> > Thanks. Do you have a small sample code to show how exactly you run it for your 'session'? You mean after puppeteer connect?
> 
> I run it once per page.

Sorry, trying to understand. So you run once per session or per page? html page or browser page instance? 

Like this?


```
    const client = await page.target().createCDPSession();

    await client.send('DOM.enable');
    await client.send('Overlay.enable');

    await client.detach();
```
