### ISSUE TITLE
page.waitForResponse cannot capture response when response code is 403

### ISSUE THREAD

**Issue by z1988hf** [puppeteer/puppeteer#4870]
I used below code to capture response. it works fine when response code is 200. However, it cannot capture the response if response code is 403.

loginResponsePromise = page.waitForResponse(response => {
                return response.request().url().startsWith('https://ww.contoso.com/login');
            });

**What is the expected result?**
Whatever the response code is, the response should be captured. 

**What happens instead?**
response is not captured. The promise got rejected after 30000ms saying "waiting for event timed out"

puppeteer version: 1.18.1

**Comment by kblok** [comment]
This test is working for me

```js
it('should work with 403 error', async({page, server}) => {
  server.setRoute('/empty.html', (req, res) => {
    res.statusCode = 403;
    res.end();
  });
  const [response] = await Promise.all([
    page.waitForResponse(response => {
      return response.request().url().startsWith(server.PREFIX + '/empty.html')}),
    page.goto(server.PREFIX + '/empty.html')
  ]);
  expect(response.status()).toBe(403);
});
```

**Comment by theArina** [comment]
That means your request failed and did not receive any response. You can catch it with the [event-requestfailed](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#event-requestfailed) or increase timeout with the [pagesetdefaulttimeouttimeout](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#pagesetdefaulttimeouttimeout)
