### ISSUE TITLE
Error Cannot display! Run Puppeteer with headless: false and TimeZone environment variable on Ubuntu 18

### ISSUE THREAD

**Issue by vitalii7777** [puppeteer/puppeteer#4876]
On Ubuntu 18 when trying to run with **env**:

`const browser = await puppeteer.launch({
    headless: false,
    env: {
          TZ: 'America/New_York',
    },});`
**every time got error:
(node:25380) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
(chrome:25394): Gtk-WARNING: 04:46:28.183: cannot open display:**

* The same code but without: 
`env: {
          TZ: 'America/New_York',
},`  
and ` headless: false` - starts well.

* The same code  with: 
`env: {
          TZ: 'America/New_York',
},` 
and `headless: true` works too.

But I need to start with particular timezone and with a browser window (headless: false)

Installed all dependencies and tried different versions of puppeteer nothing helped

**Comment by piapip** [comment]
I have the same problem, adding `DISPLAY: process.env.DISPLAY` to the `env` object will solve this problem but it's still very weird.
