### ISSUE TITLE
Chromium user data is not saved correctly on Linux

### ISSUE THREAD

**Issue by nabedesu** [puppeteer/puppeteer#4878]
Chromium user data is not saved correctly in the following cases:

1. puppeteer.launch(),
2. browser.close(),
3. change "--user-data-dir",
4. puppeteer.launch() again.
   At that time, the following  non-blocking dialog appears same as issues # 839:
     "Restore pages? Chromium didn't shut down correctly."

[Environment]
  CentOS Linux release 7.6.1810
  node.js v10.16.0
  puppeteer@1.19.0

I tried many things. I modified Launcher.js based on issues#839, and chromium user data was saved correctly. (There is no non-blocking dialog. user-data-dir switches correctly)

```
--- node_modules.org/puppeteer/lib/Launcher.js    2019-08-24 21:20:11.790660765 +0900
+++ node_modules/puppeteer/lib/Launcher.js    2019-08-25 13:50:15.615506988 +0900
@@ -215,7 +215,7 @@ class Launcher {
           if (process.platform === 'win32')
             childProcess.execSync(`taskkill /pid ${chromeProcess.pid} /T /F`);
           else
-            process.kill(-chromeProcess.pid, 'SIGKILL');
+            process.kill(-chromeProcess.pid, 'SIGTERM');
         } catch (e) {
           // the process might have already stopped
         }
```

Is correct my update SIGKILL to SIGTERM when Linux?

**Comment by OlegRomanenko** [comment]
Confirm. I had issue with save cookies after browser.close(). But when I have change SIGKILL to SIGTERM issue gone.

**Comment by nabedesu** [comment]
Thanks, Oleg.
I learned that Windows has the same problem. So I will repost the patch.

    diff -uprN node_modules.org/puppeteer/lib/Launcher.js node_modules/puppeteer/lib/Launcher.js
    --- node_modules.org/puppeteer/lib/Launcher.js	2019-08-24 21:20:11.790660765 +0900
    +++ node_modules/puppeteer/lib/Launcher.js	2019-08-31 19:59:15.948246331 +0900
    @@ -213,9 +213,9 @@ class Launcher {
             // Force kill chrome.
             try {
               if (process.platform === 'win32')
    -            childProcess.execSync(`taskkill /pid ${chromeProcess.pid} /T /F`);
    +            childProcess.execSync(`taskkill /pid ${chromeProcess.pid} /T >nul 2>&1`);
               else
    -            process.kill(-chromeProcess.pid, 'SIGKILL');
    +            process.kill(-chromeProcess.pid, 'SIGTERM');
             } catch (e) {
               // the process might have already stopped
             }

I don't know much about GitHub. Who can commit this patch?



Best regards,
Masami Watanabe
