### ISSUE TITLE
Puppeteer: Creating full element screenshot

### ISSUE THREAD

**Issue by DJ-Glock** [puppeteer/puppeteer#4883]
Hello.
I'm trying to create a screenshot of an HTML element that is pretty large and does not fit any screen. Html element is a list and can be selected with selector: nav > ul > div:nth-child(1)

Here is an example:
https://i.stack.imgur.com/9ksjI.png

The issue is: Puppeteer takes a huge screenshot, but with only visible sub-elements. Other elements are greyed out. Here is the Puppeteer's screenshot: https://i.stack.imgur.com/pV197.png

Code for taking a screenshot below:
```
public static async createPageElementScreenshotWithname(selector: string, fileName: string) {
  const element = await page.$(selector);
  if (!element) {
    return;
  }
  
  const rootDir = path.normalize(path.join(__dirname, '../'));
  const screenshotsDir = path.join(rootDir, 'test-screenshots');
  
  const screenshotPath = path.format({
    dir: screenshotsDir,
    name: fileName,
    ext: '.png',
  });
  
  fs.mkdirSync(screenshotsDir, { recursive: true });
  if (element) {
    Generic.logToConsole(`Creating screenshot into path ${screenshotPath}`);
    try {
    await element.screenshot({ path: screenshotPath });
    } catch (e) {
    Generic.logToConsole(`Could not take a screenshot with name ${fileName} cause: ${e}`);
    }
  }
}
```
I tried to use option fullPage = true for screenshot method, but id did not help.

Is there any possibility to create a screenshot for element with not visible sub-elements?

[Same question on SO, no answers so far.](https://stackoverflow.com/questions/57569590/puppeteer-creating-full-element-screenshot)

**Comment by Truth1984** [comment]
change css, and make them visible?

**Comment by DJ-Glock** [comment]
@Truth1984 I am not sure what should I do. Elements are not visible for my eye, because out of screen. But they exists ans have the same properties as visible elements.

**Comment by Truth1984** [comment]
try eval
`$(target).css("visibility","visible")`

**Comment by DJ-Glock** [comment]
@Truth1984 it gives me an error 
Property 'css' does not exist on type 'ElementHandle<Element>'.ts(2339)

**Comment by Truth1984** [comment]
eval simply referred to as `eval()` on the webpage. 
like so `page.evaluate('$(target).css("visibility","visible")')`
and of course, you need `jquery` dependency.
