### ISSUE TITLE
is Safari experimental support on the team roadmap?

### ISSUE THREAD

**Issue by adamchenwei** [puppeteer/puppeteer#4887]
I saw the ticket https://github.com/GoogleChrome/puppeteer/issues/3879 got closed by reveal an "interest". Wonder if there is a solid estimate or a road map entry for this work at all for the team? As puppeteer can really be cross-browser testing tool that can surpass selenium if it also support a major browser like safari. that is very very exciting path. 

Thanks!

**Comment by lukasPan** [comment]
Hello,
it's been a 2 months this issue was posted and more than half of year the ticket https://github.com/GoogleChrome/puppeteer/issues/3879 was revealed. Is there any update about supporting Safari/WebKit?

Thank you.

**Comment by stevenvachon** [comment]
…

**Comment by bitforcesrl** [comment]
>>>>????

**Comment by arthurlomakin11** [comment]
Any updates? Puppeteer is gone? Switching to Playwright?
