### ISSUE TITLE
CORS fail after setExtraHTTPHeaders

### ISSUE THREAD

**Issue by luxflow** [puppeteer/puppeteer#4889]
CORS fail after setExtraHTTPHeaders
if you disable OOR-CORS(out-of-blink-cors) using below code, same code works
puppeteer.launch({headless:false, launch: {args:["--flag-switches-begin", "--disable-features=OutOfBlinkCors",  "--flag-switches-end"]}});

any ideas?

### Steps to reproduce
**Tell us about your environment:**

* Puppeteer version: 1.19.0
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: v12.9.1

**What steps will reproduce the problem?**

```javascript
/* node --experimental-repl-await */
const puppeteer = require('puppeteer')
const browser = await puppeteer.launch({headless:false})
const page = await browser.newPage()
await page.setExtraHTTPHeaders({'test':'aa'})
await page.goto('https://youtube.com')
/* F12 developer mode */
```

**What is the expected result?**
CORS success regardless setExtraHTTPHeaders

**What happens instead?**
CORS fail

**Comment by allenh** [comment]
Confirming that this happens to me as well (v1.19.0) and setting
```
{ args: ['--flag-switches-begin', '--disable-features=OutOfBlinkCors', '--flag-switches-end'] }
```
will skip CORS so circumvent the issue.

**Comment by sdeprez** [comment]
Also confirming that and just to mention it, it looks like `--flag-switches-(begin|end)` are not required.

**Comment by cythrawll** [comment]
I ran into this also recently with 5.3.0.  What I did troubleshoot is that intercepting the request or changing the request that needs a cors preflight, actually ends up sending the request before the preflight comes back.  So preflight is being sent out, but only after the cross origin requests are sent out and fail.

**Comment by vkyt** [comment]
Ran into the issue on 5.4.1 again and the `'--disable-features=OutOfBlinkCors'` workaround no longer mitigates the issue.

**Comment by cnicodeme** [comment]
I agree with @vkyt, trying to set `--disable-features=OutOfBlinkCors` does not change anything.
Trying to intercept requests does not appear to work neither ...

**Comment by rickdavis927** [comment]
Facing the same issue. Adding extra HTTP headers creates Options request (CORS preflight request) which is failing.
Disabling web security is working for me. 

However what is the recommended approach?

**Comment by pan-alexey** [comment]
same issue

**Comment by WinstonN** [comment]
I just ran into this issue, and adding `--disable-web-security` to the `args[]` does resolve the issue for me. Thanks to @lteague for pointing that out
