### ISSUE TITLE
Add a proxy and remove it on the fly

### ISSUE THREAD

**Issue by gdoron** [puppeteer/puppeteer#4890]
Hi,

Often times when I scape the web I don't need a proxy, but then I see something very suspicious on the page, I want to add a proxy to know what's gonna happen if I'll click on an element on the page.

If everything is legit, I'll remove the proxy and continue to scrape and crawl as usual without the proxy.

The problem is, currently there is no way of doing it without using some sort of Man-In-the-Middle. Or is it?

Related but not quite a duplicate of: #678

Thanks,
Doron

**Comment by gajus** [comment]
You can use https://github.com/gajus/puppeteer-proxy to add proxy conditionally. The proxy will be used only when you call `proxyRequest`.
