### ISSUE TITLE
Relative paths in user directory slow down page.goto()

### ISSUE THREAD

**Issue by Manoj46kumaar** [puppeteer/puppeteer#4893]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

Passing relative path as user data directory in arguments for puppeteer.lauch causes execution to be abnormally high
_Please include code that reproduces the issue._

1. --user-data-dir = ../data/tmp/chrome takes about 11 secs compared to --user-data-dir = fullpath/data/tmp/chrome which only takes 3 secs

Im converting the page in pdf by await page.pdf

The problem only seems to occur for page.goto ( most affected timewise) others seems to run normally in both cases

**What is the expected result?**
Expected to generate pdf by 3 secs

**What happens instead?**

Takes 11 secs because page.goto takes all of it

**Comment by vsemozhetbyt** [comment]
See also: https://github.com/GoogleChrome/puppeteer/issues/3453
