### ISSUE TITLE
setCookie doesn't set session cookie of a limited lifetime

### ISSUE THREAD

**Issue by tankakatan** [puppeteer/puppeteer#4894]
### Steps to reproduce

* Puppeteer version: 1.19.0
* Platform / OS version: OS X macOS Mojave 10.14.6
* Node.js version: 9.11.2

~Please consider a test case at [the following link](https://gist.github.com/tankakatan/6e123fd05ff5ee05d8834d5ea1fd2f5c).~

**What is the expected result?**
~Cookies set correctly, test passes.~

**What happens instead?**
~Test fails with error: `AssertionError: expected [] to deeply equal [ Array(25) ]`~

**UPDATE**: the above test case is erroneous since according the [documentation](https://github.com/GoogleChrome/puppeteer/blob/v2.0.0/docs/api.md#pagecookiesurls) `Page.prototype.cookies` called with no arguments returns cookies for a currently loaded page that in my case is `about:blank`.

Below is an updated test and an updated issue.

[https://gist.github.com/tankakatan/2f2cbceba65b877e37c36f437fd1f271](https://gist.github.com/tankakatan/2f2cbceba65b877e37c36f437fd1f271)

**What is the expected result?**
Session cookie with a defined expiration date is set correctly, test passes.

**What happens instead?**
Session cookie with a defined expiration date is not set, test fails.

**Comment by kblok** [comment]
I think that [should not set a cookie on a blank page](https://github.com/GoogleChrome/puppeteer/blob/1de9906260269491c9011fcab33a58e280603fd3/test/cookies.spec.js#L247) test applies here.

**Comment by tankakatan** [comment]
@kblok thanks for the reply. In my case i need to set up a website cookies **before** i navigate to that site. So i expect puppeteer to emulate a real browser behaviour, as if it was storing cookies in some database. Of course i don't need to use a real database for that, just being able to set cookies before visiting a site (as i do in the test example) would cover all my needs.

**Comment by tankakatan** [comment]
@kblok also i believe the test case you have mentioned verifies that cookies missing the required `url` and `domain` attributes should not be set. I guess it is not about a blank page. Am i wrong?

**Comment by kblok** [comment]
Did you try using the `url` property?
See [should set a cookie on a different domain](https://github.com/GoogleChrome/puppeteer/blob/1de9906260269491c9011fcab33a58e280603fd3/test/cookies.spec.js#L304)

**Comment by tankakatan** [comment]
@kblok i did. I also have studied all issues about `setCookies`, and tried probably all the solutions ever proposed there – including the one with `domain` to `url` changing. Also if you try to set the same `domain` and / or `url` in every cookie object used in my test, its result will still be the same. I also have already played with `expires` and `session` attributes but it didn't help either.

**Comment by jamlfy** [comment]
I have the same problem. I use
```
const domain =  "internal.hotel";
await page.setCookie({
    domain,
    hostOnly: true,
    httpOnly: true,
    name: "nameCookie",
    path: "/",
    secure: true,
    session: true,
    value:   "test"
});
await page.cookies("http://" + domain + "/me"); // => []
```



Note: Please!!! Use in a generator random names, domains!!1

**Comment by tankakatan** [comment]
Hi everyone. I have improved the initial test case by making it more straightforward and unambiguous (sorry for not making it so right away), and as a result i have found it erroneous, fixed it and got the problem localized.

The issue title therefore should now be changed, since in general `setCookies` does work correctly, albeit with some caveats described below.

Here's [a new test](https://gist.github.com/tankakatan/2f2cbceba65b877e37c36f437fd1f271) containing two cases the second of which fails, illustrating the following problem:

`Page.prototype.setCookie` does not set _session_ cookie if it `expires` on a defined date in the future (i.e. is not eternal). I'm not sure this behaviour is expected and/or it needs to be clarified. Anyway it requires special handling in my app logic.

@alejonext, looks like your test illustrates exactly the same problem, only in your case you do not set the `expires` value at all.
