### ISSUE TITLE
Record a headless screen (video) during test execution.

### ISSUE THREAD

**Issue by jayeshd7** [puppeteer/puppeteer#4896]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**
staring of hook means before class we have to start recording and stop in after hook (class).

**What happens instead?**

**Comment by mathiasbynens** [comment]
Prior art: #881
