### ISSUE TITLE
Page.keyboard & mouse doesn't work with right click option

### ISSUE THREAD

**Issue by Truth1984** [puppeteer/puppeteer#4898]
### Steps to reproduce

1. Let use COPY as an example. Go to a website.

```
await page.click(selector, { button: "right" });
await page.keyboard.press("ArrowRight");
await page.keyboard.press("ArrowDown"); // 6 times ?
...
await page.keyboard.press("Enter");
```

2. mouse doesn't work either

```
await page.click(selector, { button: "right" });
await page.mouse.click(x, y); //location of COPY
```

3. keyboard should support both keycode and name string ?

* Puppeteer version: 1.19.0
* Platform / OS version: MacOS
* Node.js version: 11.12.0

**What is the expected result?**

COPY the content

**What happens instead?**

Nothing

**Comment by Truth1984** [comment]
(Page.setDownloadBehavior only worked once.) Not sure, but this might be the best solution:

![image](https://user-images.githubusercontent.com/36292372/64132925-99ae3500-ce05-11e9-8f87-fad838c3b8ec.png)

**Comment by kblok** [comment]
`keyboard` actions will be executed on the page. I don't think it should work over the context menu.

**Comment by iopanio** [comment]
Mine does not work too.
```
const plugin = await page.$('video');
await plugin.click({ button: 'right' });
await page.keyboard.type('s');
```
