### ISSUE TITLE
page.content() not returning content and reporting no error

### ISSUE THREAD

**Issue by tomgallagher** [puppeteer/puppeteer#4899]
Puppeteer 1.19.0
Node v8.15.1

I've got a strange bug with a single URL, code succeeds with hundreds of other urls, with the following simplified code:

```
page.goto('https://www.laposte.fr/', { timeout: 30000, waitUntil: ['domcontentloaded'] } )
    .then( () => page.content() )
    .then( content => console.log(content))
    .catch( err => console.log(err)); 
```

I am getting no html string and no error message. The alias `page.mainFrame().content()` also does not work. The page is open with the boolean check. All the page resources are loading fine. The page itself has become unresponsive to certain calls. I've tried wrapping the `page.content()` call in a `page.on('load')` event handler but that event does not fire. 

If I change the waitUntil event to 'load', the code succeeds on this particular URL.

I am listening to page events elsewhere, maybe I've hit a max number of listeners? I'm at a bit of a loss as to why this URL alone is failing.

Any help gratefully received.

Tom

**Comment by kblok** [comment]
This is working for me

```ts
(async() => {
    const browser =  await puppeteer.launch({ headless: true});
    const page = await browser.newPage();
    await page.goto('https://www.laposte.fr/', { timeout: 30000, waitUntil: ['domcontentloaded'] } );
    console.log(await page.content());
})();
```

**Comment by tomgallagher** [comment]
Thanks for getting back and the confirm that it works on your machine. I think it's a resources problem, in the sense that when there's a lot going on post-domcontentloaded but pre-load, if the system resources are near their limits then page.content() just does not respond.

**Comment by tomgallagher** [comment]
Running Node with the following params has fixed this particular issue

`node --optimize_for_size --max_old_space_size=460 --gc_interval=100 index.js`
