### ISSUE TITLE
`attributes` are not being parsed

### ISSUE THREAD

**Issue by chulanovskyi** [puppeteer/puppeteer#4901]
### Steps to reproduce

1. Navigate to [try puppeteer site](https://try-puppeteer.appspot.com/).
2. Paste this example:

```
const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.goto('http://example.org/', { waitUntil: ['domcontentloaded'] } );

const link = await page.$('a');
const attrs = await link.getProperty('attributes');
const value = await attrs.jsonValue();
console.log(JSON.stringify(value));

// eval approach
const href = await page.$eval('a', link => link.attributes);
console.log(JSON.stringify(href));

await browser.close();
```

3. Try to run it and see the output in *Log* section, at the right. 

**What is the expected result?**
Expected to have a NamedNodeMap

---
![image](https://user-images.githubusercontent.com/13966263/64190064-36acb480-ce7e-11e9-913b-9a6d07a73f73.png)

**What happens instead?**
The results are empty objects
```
{"0":{}}
{"0":{}}
```

**Comment by vsemozhetbyt** [comment]
These functions can transfer only stringifiable objects. If you select the element and run `JSON.stringify($0.attributes)` in the browser console you will get the same result.

**Comment by chulanovskyi** [comment]
@vsemozhetbyt, right, so the direct property access will work:
```
const href = await page.$eval('a', link => link.href);
```
Thanks
