### ISSUE TITLE
The function page.screenshot  can't capture a full web page which height is more than 4500(approximately)

### ISSUE THREAD

**Issue by himaozi** [puppeteer/puppeteer#4903]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.12.2+  (the previous version is ok)
* Platform / OS version: OS X macOS Mojave 10.14.6
* URLs (if applicable):
* Node.js version: 10.15.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.Find a page which height is more than 5000.(Just suppose its height is 10000)
2.page.goto(url)
3.page.screenshot({ path: 'example.png', clip: { x: 0, y: 0, width: 750, height: 10000 } });

**What is the expected result?**
The example.png should be  the correct screenshot of the full  page.
(In the previous version of 1.12.2, it is)
![image](https://user-images.githubusercontent.com/17868988/64222486-d14ed700-cf02-11e9-9c96-57d9121774ab.png)

**What happens instead?**
The example.png is not entire.The part over 4500(approximately) shows blank.
![image](https://user-images.githubusercontent.com/17868988/64222492-d7dd4e80-cf02-11e9-82f8-1eb8dc0e6a42.png)

**Comment by guowenfh** [comment]
I met the same problem

**Comment by liees** [comment]
+1
