### ISSUE TITLE
How to find an element by its class and attribute?

### ISSUE THREAD

**Issue by JaimeRamos99** [puppeteer/puppeteer#4904]
I have been scrapping a web page but now i am stuck because i need to find only the table tags that match the following requirements:  class ="datadisplaytable" and summary="Esta tabla lista los horarios de reunión calendarizados y los instructores asignados para esta clase.."
and example of a table i want to get:<table class="datadisplaytable" "summary="Esta tabla lista los horarios de reunión calendarizados y los instructores asignados para esta clase.."></table>

**Comment by vsemozhetbyt** [comment]
You can try a selector like `table.datadisplaytable[summary="Esta tabla lista los horarios de reunión calendarizados y los instructores asignados para esta clase.."]`.

**Comment by mathiasbynens** [comment]
@vsemozhetbyt's answer is correct!

Closing since this is not a Puppeteer-specific question, but rather a question about CSS selectors in general.
