### ISSUE TITLE
feat: emulate prefers-color-scheme 

### ISSUE THREAD

**Issue by manucorporat** [puppeteer/puppeteer#4906]
It would be interesting to simulate different values of `prefers-color-scheme`, so developers could write visual tests for light and dark mode.

Possible API:
```
page.emulate({
  viewport: {
     colorScheme: 'dark'
  }
});
```

There is an article of how this could be achieved: https://www.bram.us/2019/09/04/take-both-light-and-dark-mode-screenshots-with-puppeteer/

But seems rather hacky and unperformant, since it needs to boot up two completely different chrome instances.

**Comment by tomayac** [comment]
Heya, @tomayac here, author of the "hacky" and "unperformant" solution https://github.com/tomayac/dark-mode-screenshot. I would very much +1 a *native* way in Puppeteer, as typically the flags that my approach uses at the moment tend to be rather ephemeral. 

Different than the proposal above, I would, however, vouch for a more generic approach that allows for testing all current and potential future [User Preference Media Features](https://drafts.csswg.org/mediaqueries-5/#mf-user-preferences), like `prefers-reduced-motion`, `prefers-contrast` etc.

My idea would be to have a field where one can shove the different media features à la

```js
{
  …
  userPreferences: {
    "prefers-color-scheme": 'dark',
    "prefers-reduced-motion": 'reduce',
  }
  …
}
```

I'm not that familiar with the Puppeteer API, so would leave it to the authors to decide where such a field would live best.

**Comment by manucorporat** [comment]
@tomayac sorry for the adjectives haha it was very inspiring though! 

Should not "userPreferences" be an object?
```
userPreferences: {
 'prefers-color-scheme': 'dark',
 'prefers-reduced-motion': true
}
```

i like so much the API! 

At Stencil as part of our e2e API, we have a way to run the tests under different simulated devices, it would be great to configure this user preferences as well!

**Comment by tomayac** [comment]
> [S]orry for the [adjectives]

No offense taken, no worries. 

> Should not "userPreferences" be an object?

🙈 Of course, updated my comment. Thanks!

**Comment by mathiasbynens** [comment]
Puppeteer already has [a `page.emulateMedia` API](https://github.com/GoogleChrome/puppeteer/blob/v1.19.0/docs/api.md#pageemulatemediamediatype), although it currently only supports `'screen'` and `'print'`. One idea would be to extend it to support newer user preference media types as Chrome adds support for them:

```js
await page.emulateMedia('prefers-color-scheme: dark');
await page.emulateMedia('prefers-reduced-motion: true');
```

We _could_ overload the API and accept objects as well, to enable setting multiple values in one go:

```js
await page.emulateMedia({
  'prefers-color-scheme': 'dark',
  'prefers-reduced-motion': true,
});
```

But, it seems better to match `<link rel="stylesheet" media="...">` and just continue accepting a single string value instead. Parentheses and `,` can be used for multiple preferences:

```js
await page.emulateMedia('(prefers-color-scheme: dark), (prefers-reduced-motion: true)');
```

**Comment by mathiasbynens** [comment]
One problem with the abovementioned "single unified API" approach is that it's unclear what should happen for more complicated media query expression inputs, e.g.

```js
await page.emulateMedia('(min-width: 200px) or (prefers-color-scheme: dark)');
```

While it's clear what it means to emulate `prefers-color-scheme: dark`, what should happen for `min-width: 200px`? Would it be silently ignored? Would it resize the window?

To avoid this confusion, we can introducing two distinct APIs after all:

- `emulateMediaType(type)` with `type` being an enum of `'print', 'screen'`
- `emulateMediaFeature(feature, value)` with `feature` being an enum of `'prefers-color-scheme', 'prefers-reduced-motion'`

Note that `emulateMediaType` is essentially what the current `emulateMedia` API does, although IMHO it would make sense to rename it + deprecate the old alias if we go this route.

**Comment by tomayac** [comment]
> `emulateMediaFeature(feature, value)`

One idea to simplify things could be to limit this to just [user preference media features](https://drafts.csswg.org/mediaqueries-5/#mf-user-preferences) and future potential additions.

**Comment by mathiasbynens** [comment]
> One idea to simplify things could be to limit this to just user preference media features and future potential additions.

Agreed. This would be enforced through the enum checks anyhow, but the way you describe it is definitely how it would be documented. :+1:

**Comment by manucorporat** [comment]
Seems like this issue was shipped with `page.emulateMedia()`!

**Comment by sovetski** [comment]
I found the solution

```js
await page.emulateMediaFeatures([
 { name: "prefers-color-scheme", value: "dark" },
]);
```
