### ISSUE TITLE
SOCKS5 proxy, different ones for different instances

### ISSUE THREAD

**Issue by GildedHonour** [puppeteer/puppeteer#4908]
How can I specify different SOCKS5 proxies for different instances of puppeteer? Namely, each instance of puppeteer should use its own SOCKS5 proxy.

**Comment by atefBB** [comment]
@GildedHonour Did you found any solution to this issue?!

**Comment by avimar** [comment]
do you mean each tab or each instance?

Launching with this arg worked: `--proxy-server=socks5://localhost:8080`

**Comment by atefBB** [comment]
@avimar thank you
