### ISSUE TITLE
Not able to select by attribute/class

### ISSUE THREAD

**Issue by carefulcomputer** [puppeteer/puppeteer#4909]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.19.0
* Platform / OS version:MacOS
* Node.js version:v10.4.1

Trying to select this

`<a class="KxR2cf-za" title="Click Here">Click Here</a>`

and using this code

```
const elementHandle = await page.$('a[class="KxR2cf-za"]');
console.log(elementHandle);

```
however console is printing null even though chromium shows the node in UI. What am i doing wrong ?

**Comment by vsemozhetbyt** [comment]
Maybe you can try [`page.waitForSelector()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectorselector-options) first in case the element is inserted a bit later after the `page.$()` call?

**Comment by carefulcomputer** [comment]
```
    await page.waitForSelector('a[class="KxR2cf-za"]');
    const elementHandle = await page.$('a[class="KxR2cf-za"]');
```

times out after 30 seconds.

**Comment by vsemozhetbyt** [comment]
Do you test in Chromium with the same viewport? Sometimes in a smaller viewport some elements are absent. Did you try to launch the Puppeteer headfull to see if the element was present during the timeout?

**Comment by carefulcomputer** [comment]
that is the puzzling part. i used headful chromium and I can see the element in viewport. I also  opened dev tools to confirm that element was there. Do i need to escape "-" or modify my selector ?

**Comment by vsemozhetbyt** [comment]
@qwertangel Can it be that the element is inside an `iframe`?

**Comment by carefulcomputer** [comment]
@vsemozhetbyt .. that was it !! I was looking for element in main frame, but element was in an iframe. after fetching right iframe, it worked perfectly. Thank you !
