### ISSUE TITLE
Error page.$$ is not a function

### ISSUE THREAD

**Issue by lerayj** [puppeteer/puppeteer#492]
Using `page.$$` does not work for me. Although `page.$` seems to work. 
Any explanations? 
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({  
    headless: false,
    slowMo: 250});
  const page = await browser.newPage();
  await page.goto('https://www.amazon.fr/s/ref=sr_nr_n_0?fst=as%3Aoff&rh=n%3A11961521031%2Cp_76%3A437878031%7C437879031%2Cn%3A%2111961522031%2Cn%3A12422072031&bbn=11961522031&ie=UTF8&qid=1503488233&rnid=11961522031');
  
  var elems = await page.$('#leftNavContainer ul');
  console.log(elems);

  elems = await page.$$('#leftNavContainer ul');
  console.log(elems);

  browser.close();
})();
```

Output:
ElementHandle {
  _client:
   Session {
     domain: null,
     _events:
      { 'Page.frameAttached': [Function],
        'Page.frameNavigated': [Function],
        'Page.frameDetached': [Function],
        'Runtime.executionContextCreated': [Function],
        'Network.requestWillBeSent': [Function: bound _onRequestWillBeSent],
        'Network.requestIntercepted': [Function: bound _onRequestIntercepted],
        'Network.responseReceived': [Function: bound _onResponseReceived],
        'Network.loadingFinished': [Function: bound _onLoadingFinished],
        'Network.loadingFailed': [Function: bound _onLoadingFailed],
        'Page.loadEventFired': [Function],
        'Runtime.consoleAPICalled': [Function],
        'Page.javascriptDialogOpening': [Function],
        'Runtime.exceptionThrown': [Function],
        'Security.certificateError': [Function],
        'Inspector.targetCrashed': [Function] },
     _eventsCount: 15,
     _maxListeners: undefined,
     _lastId: 9,
     _callbacks: Map {},
     _connection:
      Connection {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _url: 'ws://127.0.0.1:50825/devtools/browser/05c66f54-a6ed-4210-9932-111216f14ad8',
        _lastId: 11,
        _callbacks: Map {},
        _delay: 250,
        _ws: [Object],
        _sessions: [Object] },
     _targetId: '0cb1e1e4-fb6e-41e6-b7fc-e92a0399f810',
     _sessionId: '0cb1e1e4-fb6e-41e6-b7fc-e92a0399f810:1' },
  _remoteObject:
   { type: 'object',
     subtype: 'node',
     className: 'HTMLUListElement',
     description: 'ul.a-unordered-list.a-nostyle.a-vertical.a-spacing-base',
     objectId: '{"injectedScriptId":3,"id":1}' },
  _mouse:
   Mouse {
     _client:
      Session {
        domain: null,
        _events: [Object],
        _eventsCount: 15,
        _maxListeners: undefined,
        _lastId: 9,
        _callbacks: Map {},
        _connection: [Object],
        _targetId: '0cb1e1e4-fb6e-41e6-b7fc-e92a0399f810',
        _sessionId: '0cb1e1e4-fb6e-41e6-b7fc-e92a0399f810:1' },
     _keyboard: Keyboard { _client: [Object], _modifiers: 0, _pressedKeys: Set {} },
     _x: 0,
     _y: 0,
     _button: 'none' },
  _disposed: false }
(node:22729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: page.$$ is not a function
(node:22729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by elisherer** [comment]
How are you using it? it wasn't released yet...

**Comment by lerayj** [comment]
@elisherer What do you mean?
I copied how I use it.
Looking at the doc, it should have been released: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector

**Comment by Garbee** [comment]
A new version isn't tagged. So unless you install from github directly you won't have `$$` through NPM yet.

**Comment by lerayj** [comment]
@Garbee Ok get it thanks. Do you know when it will be on npm? Is there a date?

**Comment by vsemozhetbyt** [comment]
@lerayj See https://github.com/GoogleChrome/puppeteer/issues/483
You can install the tip-of-tree in this way:
```
npm install https://github.com/GoogleChrome/puppeteer/
```

**Comment by lukewlms** [comment]
You can also just set this in package.json then yarn install, to always fetch the master branch from GitHub.

    "puppeteer": "GoogleChrome/puppeteer",

Confusingly the documentation indicates it's available in the release, but it's not.

**Comment by lerayj** [comment]
Ok thanks guys @vsemozhetbyt @lukecwilliams.
And yes it's a bit confusing...
