### ISSUE TITLE
Error: Passed function is not well-serializable!

### ISSUE THREAD

**Issue by alex2844** [puppeteer/puppeteer#4921]
[orig]
Если просто запустить браузер, перейти на страницу и закрыть браузер - то всё ок.
Но если выполнить любой js, например: `await page.evaluate(() => []);`
то получаю ошибку `Error: Passed function is not well-serializable!`
Ошибка только после упаковки через pkg

[en]
If you just launch the browser, go to the page and close the browser - ok.
If you execute JS, then an error - `Error: Passed function is not well-serializable!`
An error only after packing through pkg

**Comment by alex2844** [comment]
Проблема в pkg, например код
`console.log((() => {}).toString());`
до упаковки `() => {}`
а после `function () { [native code] }`

**Comment by bandey** [comment]
Решение в комментарии по ссылке:
[Solution here](https://github.com/zeit/pkg/issues/204#issuecomment-378929002)

**Comment by Jav3k** [comment]
@alex2844, Hi. How did you solve this problem? I am using pkg and puppeteer too

**Comment by bandey** [comment]
> How did you solve this problem?

I used [this solution](https://github.com/zeit/pkg/issues/204#issuecomment-378929002)

**Comment by alex2844** [comment]
@Jav3k 
> @alex2844, Hi. How did you solve this problem? I am using pkg and puppeteer too

Yes, here is the solution
```
async aval = (page, pageFunction, ...args) => {
    var context = await page._frameManager.mainFrame().executionContext(),
        suffix = `//# sourceURL=VM30`;
    var res = await context._client.send('Runtime.callFunctionOn', {
        functionDeclaration: pageFunction.toString()+'\n'+suffix+'\n',
        executionContextId: context._contextId,
        arguments: args.map(arg => ({value: arg})),
        returnByValue: true,
        awaitPromise: true,
        userGesture: true
    });
    if (res.exceptionDetails)
        throw new Error(res.exceptionDetails.exception.description);
    else if (res.result.value)
        return res.result.value;
}
await eval(page, `() => (document.body.innerHTML = 'test')`);
```

**Comment by guan3083** [comment]
[orig]
对不起，我是新手，看了你的代码还是不知道如何解决？你能详细讲讲吗

[en]
Sorry, I am a rookie, I read your code and still don't know how to solve it?Can you elaborate on that
