### ISSUE TITLE
Getting an Error when i try to use target.page() to control the new opened popup window through a click.

### ISSUE THREAD

**Issue by Arabyan** [puppeteer/puppeteer#4922]
### Steps to reproduce

**Tell us about your environment:**

* Chrome version: Chromium 77.0.3844.0
* Puppeteer version: Latest stable version
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: Latest version

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
`const puppeteer = require('puppeteer-core');

async function login() {
    function wait(ms){
   var start = new Date().getTime();
   var end = start;
   while(end < start + ms) {
     end = new Date().getTime();
  }
}
    const wsChromeEndpointurl = "ws://localhost:9222/devtools/page/81413C0EFDF5D145E457B9415ED9E5F0";
    const browser = await puppeteer.connect({
    headless: false,
    args: ["--disable-notifications"],
    browserURL: 'http://127.0.0.1:9222'});

    const page = await browser.newPage();
    // Focus input
    await page.goto('https://www.facebook.com');
    wait(1000);
    await page.click('#email');
    wait(1000);
    await page.keyboard.type('grigor@tcf.team');
    wait(2000);
    // Focus password
    await page.click('#pass');
    wait(1000);
    await page.keyboard.type('grigorgrigor');
    // Get login button and submit it
    wait(1000);
    const loginButton = await page.$('#loginbutton input');
    wait(1000);
    await loginButton.click();

    wait(5000);
    const kickstarter_page = await browser.newPage();
    await kickstarter_page.setViewport({width: 1366, height: 768});
    await kickstarter_page.goto('https://www.kickstarter.com/projects/beehivebooks/artemisia-the-original-painter-of-women-in-power?ref=section-homepage-featured-project');

    console.log("after clicking");
    wait(5000);

    await kickstarter_page.click('#react-project-header > div > div > div.grid-row.grid-row.mb5-lg.mb0-md.order-0-md.order-2-lg > div.grid-col-12.grid-col-4-md.hide.block-lg > div.py0.pb2 > div > div.basis50p.block-sm.flex.grow-1.items-center.justify-center.react_share_icons.w100p > div > div > div.inline-block.mx4 > a > svg');

    console.log("after clicking");
    const newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.kickstarter_page())));
    console.log("after clicking2");
//    await link.click();
    console.log("after clicking3");
     wait(3000);
    const share_link = await newPagePromise;
     wait(3000);
    console.log("after clicking4");
     wait(3000);
    await share_link.close();
     wait(3000);
    console.log("after clicking5");

//    browser.close();
  }
login();
`

**What is the expected result?**
My code enters into facebook account , then in another tab opens a kickstarter page , and it is clicking on facebook icon to share that "campaign" on facebook , and it opens a popup window where you can click on button and share the campaign, so i am trying to control that popup window, trying to close it fore example( in this case) , or to click some buttons on it in future.

**What happens instead?**
Instead i get an Error which says 
(node:18549) UnhandledPromiseRejectionWarning: TypeError: target.kickstarter_page is not a function 
To solve this problems i have followed some links(below) , and i am using the same code, but it does not solve the problem ,PLease.
https://pocketadmin.tech/en/puppeteer-popup-window/
https://github.com/GoogleChrome/puppeteer/issues/3667
https://github.com/GoogleChrome/puppeteer/issues/1553
https://github.com/GoogleChrome/puppeteer/issues/2968  This Link especially

**Comment by kblok** [comment]
Isn't that a typo? shouldn't it be?

```js
const newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.page())));
```

**Comment by Arabyan** [comment]
@kblok  Yes it has worked ,  instead of kickstarter_page i wrote page.   Thank you a lot . It is honor for me to get a help from you my friend.

**Comment by kblok** [comment]
@Arabyan if it's working now. I would close this issue ;)
