### ISSUE TITLE
Can't get property 'readonly' of node

### ISSUE THREAD

**Issue by sambragg** [puppeteer/puppeteer#4926]
> Hello team,
> 
> Unsure if the following is a bug, or user-error on my part (most likely the latter!)
> 
> Thanks in advance for the help and thanks for building such an awesome tool!

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: **1.19.0**
* Platform / OS version: macOS **10.12.6** 
* Node.js version: **12.6**

**What steps will reproduce the problem?**

_test.html:_
```
<!DOCTYPE html>
<html>
<head>
  <title>test</title>
</head>
<body>
  <input type="text" name="test" id="test" readonly="readonly">
</body>
</html>
```
_index.js:_
```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({ headless: false })
  const page = await browser.newPage()
  
  const node = await page.$('#test')

  const name = await node.getProperty('name')
  console.log(name._remoteObject)
  // { type: 'string', value: 'test' }

  const readonly = await node.getProperty('readonly')
  console.log(readonly._remoteObject)
  // { type: 'undefined' }

  await browser.close();
})();
```

**What is the expected result?**
```
console.log(readonly._remoteObject)
// { type: 'string', value: 'readonly' }
```

**What happens instead?**
```
console.log(readonly._remoteObject)
// { type: 'undefined' }
```

**Comment by mathiasbynens** [comment]
The IDL attribute name is `readOnly` (with capital `O`), not `readonly`, per <https://html.spec.whatwg.org/multipage/input.html#dom-input-readonly>. This fixes it:

```diff
-  const readonly = await node.getProperty('readonly')
+  const readonly = await node.getProperty('readOnly')
```
