### ISSUE TITLE
How to wait for any one of the two element to appear on the screen?

### ISSUE THREAD

**Issue by vyomsrivastava** [puppeteer/puppeteer#4932]
Right now I am using 
 await page.waitForSelector('.gux-warning-message-text', {timeout : 0});

but there is one more class which can take place of the above selector that is .custom-table

How can I make the puppeteer wait for anyone of them? I have kept timeout 0 because it'll take a lot of waiting time.

**Comment by mathiasbynens** [comment]
Have you tried using `,`?

```js
await page.waitForSelector('.gux-warning-message-text, .custom-table');
```

**Comment by shirshak55** [comment]
or you can use promise race also.

**Comment by mccoolaustinm** [comment]
I use a function that wraps the built in Promise.race() to add the ability to determine WHICH promise completed first, for the exact use-case you're describing of creating multiple waitFor_X promises and checking which one completes.

```TSX
async function racePromises(promises: Promise<any>[]): Promise<number> {
    const wrappedPromises = [];
    promises.map((promise, index) => {
        wrappedPromises.push(
            new Promise<number>((resolve) => {
                promise.then(() => {
                    resolve(index);
                })
            })
        )
    })
    return Promise.race(wrappedPromises);
}
```

Then I use it as such:
```TSX
const navigationOutcome = await racePromises([
                page.waitForSelector('#example-selector-scenario-A'),
                page.waitForSelector('#example-selector-scenario-B')
            ]);
            if (navigationOutcome === 1) { 
                //. . .do something...
```

The rest of the promises just time-out harmlessly. Disabling timeout could cause a garbage buildup issue, as I don't know of any way to cancel Puppeteer's wait functions once they've started aside from letting them time out.

**Comment by akshaychauhan7737** [comment]
```
const watchDog2 = [
                page.waitForSelector('.twofa-form .error'),
                page.waitForNavigation({ waitUntil: 'networkidle2' })
];
await continueButton.evaluate(continueButton => continueButton.click())
await await Promise.race(watchDog2);
```

First create Object then wait for race.

**Comment by TomasHubelbauer** [comment]
This GitHub issue comes up for the Google search for "playwright wait for one of two selectors" and I believe as of Playwright 1.33 the best practice for that is this:

```
await expect(locatorA.or(locatorB)).toBeVisible();
if (await locatorA.isVisible()) {
  // Take path
}
else {
  // Take alternative path
}
```

This is useful for stuff like using existing test item (like profile creation, file upload etc.) if prior test ones have created one or creating one if not. This can sometimes be useful when the page being tested lives in an environment where data persistence is enabled and allowed for read-only tests (such that they don't muddy the environment's state). It is a form of a cache.

Source: https://stackoverflow.com/a/77288539/2715716

**Comment by Gotterbild** [comment]
The issue is `page.waitForSelector(selector)` returns the first found element. And in my case I have two identical selectors (`[data-testid="some-name"]`), the first is hidden and the second is visible. And `page.waitForSelector(selector)` fails.
