### ISSUE TITLE
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4_mRKS3_: symbol not found

### ISSUE THREAD

**Issue by lintu** [puppeteer/puppeteer#4933]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7.0
* Platform / OS version: Alpine 10
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

1. Build docker image with chromium
2. I was using the below commands to install chromium
`RUN apk update && apk upgrade && \
      echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
      echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
      apk add --no-cache \
      chromium@edge \
      nss@edge \
      freetype@edge \
      freetype-dev@edge \
      ca-certificates@edge \
      harfbuzz@edge \
      ttf-freefont@edge`

**What is the expected result?**
Should launch a chrome instance

**What happens instead?**
Throws the error 
`Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4_mRKS3_: symbol not found`

This happened with the new version of chromium(chromium-76.0.3809.132-r0.apk) I believe. cz it was working fine before the update. 

Any ideas...

**Comment by rockettomatooo** [comment]
@lintu what base image are you using?
I'm using `node:8-alpine` and it works. Its alpine version is `3.9.4`. (according to `cat /etc/alpine-version`)
If I'm using `node:8.9.4-alpine` which runs alpine version `3.6.2`, I get the same error as you do. 

I took the time to setup a quick reproduction repo: https://github.com/Rockettomatoo/puppeteer_error_reproduction

**Comment by lintu** [comment]
@Rockettomatoo thanks. I am not sure. I wasn't using the base image directly. I ended up using 
`node:10-slim`  as shown in the example [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)
