### ISSUE TITLE
Disable --user-data-dir

### ISSUE THREAD

**Issue by mtrucc** [puppeteer/puppeteer#4936]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.19.0
* Platform / OS version: win10 x64 1809
* URLs (if applicable):
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require("puppeteer-core");
(async () => {
  const browser = await puppeteer.launch({
    executablePath:
      "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    height: false,
    devtools: true,
    ignoreDefaultArgs:true
  });
  const page = await browser.newPage();
})();
```

**What is the expected result?**
I found that the puppeter is always loaded with the ‘`--user-data-dir`’ parameter. How do I disable it?

**What happens instead?**
Because I expect to open Google Chrome normally, some websites have added this parameter ‘--user-data-dir’, which causes the website to load abnormally (cannot load some js normally, which leads to being recognized as a robot)

**Comment by mogmet** [comment]
I could disable like this.
```
  const browser = await puppeteer.launch({
    args: [
      '--user-data-dir'
    ]
  )}
```
