### ISSUE TITLE
Remote access on android

### ISSUE THREAD

**Issue by arenevier** [puppeteer/puppeteer#4937]
I am trying to use puppeteer remotely on some Android device.

I am forwarding port 9222 with 
**$ adb forward tcp:9222 localabstract:chrome_devtools_remote**

I am able to connect to the browser with 

`
  const browser = await puppeteer.connect({
    browserWSEndpoint: 'ws://127.0.0.1:9222/devtools/browser',
  });
`

But when trying to get the available pages with  `const pages = await browser.pages();` or create a new one with `const page = await browser.newPage();`, the script stalls, and the promise is never resolved.

I notice something weird when I try to list the browser targets with `console.log(browser.targets())`: each loaded page appears twice in the list. For example, if the remote browser has one tab with google.com, I will see two page targets with the following TargetInfo:

  `{
      targetId: 'ECB167EEA4CEBC8DCCF2A8C9D14E4207',
      type: 'page',
      title: 'Google',
      url: 'https://www.google.com/',
      attached: false,
      browserContextId: '5E3E44DA3AE8CB75491B17CBD5BC5D80'
    }`

 `{
      targetId: '2968',
      type: 'page',
      title: 'Google',
      url: 'https://www.google.com/',
      attached: false
    }`

I am on macosx, and installed puppeteer with **nmp install puppeteer**. Node version is v12.10.0

**Comment by SirPepe** [comment]
Can confirm the exact same problem with Ubuntu Linux 18.04.4.

**Comment by Niek** [comment]
Same issue here, the `newPage()` promise is never resolved.

@arenevier @SirPepe did you find any workaround?

**Comment by SirPepe** [comment]
@Niek I did not! If I remember correctly, I concluded that mobile chrome just does not speak puppeteer's protocol correctly. So this is not really a bug in pptr, but rather a problem mobile chrome. My takeaway is that if you want to remote-control _anything_ but the bundled chromium and can't risk your program breaking in the future, you're better off using web driver.

**Comment by napkinbrown** [comment]
It looks like driving mobile chrome this way worked up until about Puppeteer 1.12. 
Last time I checked, 1.11 is able to control mobile chrome remotely.

Based on comments like this, I doubt it'll get fixed in future versions:
> We don't have a good story for testing on android. This's not a top priority for us.
> https://github.com/puppeteer/puppeteer/issues/2067

**Comment by UrielCh** [comment]
```
const browser = await puppeteer.connect({ browserWSEndpoint: 'ws://127.0.0.1:9222/devtools/browser', });
const pages = await browser.pages();
```

With puppeteer-core@13.7.0 my browser zoom to the page and freeze
With puppeteer-core@15.2.0 my browser zoom to the page and freeze

tested with chrome mobile 102.0.5005.125

for now, I can connect to it with 'chrome-remote-interface' by setting { local: true } during connection.

**Comment by OrKoN** [comment]
Please try with the latest Puppeteer version and please re-open the issue if it still happens. There have been target management improvements landed in Puppeteer recently that should help with this issue.
