### ISSUE TITLE
`page.goto` timeouts in headless mode for localhost pages if protocol is not specified

### ISSUE THREAD

**Issue by inikulin** [puppeteer/puppeteer#494]
The problem can be reproduced with the following code:
```js
const puppeteer = require('puppeteer');
const http = require('http');

const server = http.createServer((req, res) => res.end('Hi'))
    .listen(1337, async () => {
        const browser = await puppeteer.launch({ headless: true });
        const page = await browser.newPage();


        try {
            await page.goto('localhost:1337');
        } catch (err) {
            console.log(err);
        }

        console.log('Done');
        browser.close();
        server.close();
    });
```

If you set `headless` to `false` or specify any other domain program will print "Done" and exit, but for `localhost` without protocol it timeouts.  It works well for `http://localhost:1337` though. My wild guess is that `localhost` without a protocol is handled by omnibox or other component that is disabled in headless mode. I guess it's worth at least to be documented.

**Comment by pavelfeldman** [comment]
URL is url and unless client provides the protocol to connect over, there is little Puppeteer can do.

**Comment by inikulin** [comment]
@pavelfeldman Fair enough, but it works well for `google.com` for example. So, it can be a bit confusing.

**Comment by nrogap** [comment]
@inikulin Did you try `await page.goto('http://localhost:1337');` ?

**Comment by defusioner** [comment]
Oh man, spent 2 days to understand this! I'm using `jest-puppeteer` and in headfull mode it's ok, not in headless. I thought it was a problem in jest, jest-puppeteer, somewhere, updated the whole project just to know probably there is some incompatibility between the deps. No. Use `http://localhost`, the next one who reads this.

**Comment by AkatQuas** [comment]
I faced a problem with the `localhost` issue.

`await page.goto('http://localhost:8080')` would throw an `ERR_ECONNREFUSED` error.

However, `await page.goto('http://192.168.3.11:8080')` goes well. 

How come the differences when visiting page using `ip` and `localhost` ?

**Comment by elbotho** [comment]
Maybe it's helpful for somebody:
I had timeouts on localhost because of a hotreload script that kept the connection alive and I used
``` js
await page.goto(url, { waitUntil: 'networkidle0' })
```
… well 🤦.
