### ISSUE TITLE
puppeteer@1.20.0 fails to download chromium_revision: 686378

### ISSUE THREAD

**Issue by ferdi-k** [puppeteer/puppeteer#4943]
### Steps to reproduce

**Tell us about your environment:**
Win64

* Puppeteer version: 1.20.0
* Platform / OS version: win64
* URLs (if applicable):
* Node.js version: 8.9.4

**What steps will reproduce the problem?**
With the current puppeter version (1.20.0), the chromium_revision is set to 686378. But if i check which version is actually downloaded, i discover that 674921 is downloaded. So when chrome is trying to be started with ...\node_modules\puppeteer\.local-chromium\win64-686378\chrome-win\chrome.exe ..., there is nothing to be found so an error is shown (the .local-chromium folder contains chrome revision 674921).

_Please include code that reproduces the issue._
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-spec-reporter": "^0.0.32",
    "puppeteer": "^1.19.0",

**What is the expected result?**
karma tests are run successfully with no error stating that chrome headless could not be started.

**What happens instead?**
Error message is shown starting chrome headless could not be started
Launching browser ChromeHeadless with unlimited concurrency
Starting browser ChromeHeadless
Creating temp dir at ...\AppData\Local\Temp\karma-96064520
[...]\node_modules\puppeteer\.local-chromium\win64-686378\chrome-win\chrome.exe --user-data-dir=[...]\Local\Temp\karma-96064520 --enable-automation --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-background-timer-throttling --disable-renderer-backgrounding --disable-device-discovery-notifications http://localhost:9876/?id=96064520 --headless --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222
ChromeHeadless have not captured in 60000 ms, killing.
ChromeHeadless was not killed in 2000 ms, sending SIGKILL.
ChromeHeadless was not killed by SIGKILL in 2000 ms, continuing.
Process ChromeHeadless exited with code -1
Cleaning temp dir [...]\AppData\Local\Temp\karma-96064520
ChromeHeadless failed (timeout). Not restarting.

**Comment by alex2wong** [comment]
Maybe you need a proxy to access chromium resource.. but here's work around:
> npm config set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
> npm install

then, when launch chrome, pass your chrome.exe path such as "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe":

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"});
  const page = await browser.newPage();
  await browser.close();
})();
```

Or you can just use : https://www.npmjs.com/package/puppeteer-core

**Comment by ferdi-k** [comment]
Thanks, that's not it, but you pointed me in the correct direction. PUPPETEER_CHROMIUM_REVISION was manually set to the specific revision
