### ISSUE TITLE
Access to "protocol" in Response

### ISSUE THREAD

**Issue by rediche** [puppeteer/puppeteer#4948]
In the Chrome DevTools Protocol, [a "protocol" property is available on the response object](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Response).

This should in my opinion be exposed to the puppeteer response object, such that we will be able to verify if a request is sent over h2 or http/1.1.

**Comment by StephenFluin** [comment]
+1

**Comment by cristianvnica** [comment]
can you please reopen this? to be able to check the protocol would be useful
