### ISSUE TITLE
nth-child selector not working

### ISSUE THREAD

**Issue by lerayj** [puppeteer/puppeteer#495]
```
let test = await page.click('#leftNavContainer ul:nth-child(0n+2) li:nth-child(0n+1)');
console.log(test);
```
Does not work.

**Html:**

```
<div id="leftNavContainer">
  <ul>
    <li></li>
    <li></li>
  </ul>
  <ul>
    <li></li>
    <li></li>
  </ul>
  <ul>
    <li></li>
    <li></li>
  </ul>
  <ul>
    <li></li>
    <li></li>
  </ul>
</div>
```

**Output:**
`null
`
This make impossible to resolve some problem as following.

**Example:**

You want to click the the 2 `<li>` into the 3 `<ul>` in the page.

Solution 1: Use `ul:nth-child(0n+2) li:nth-child(0n+1)` => Does not work.

Solution 2: 

1. Select <ul> with` page.$$` then iterate on the 3rd `<ul>` _ElementHandle_.
2. with the `UlElementHandle` iterated, process a `ElementHandle.$$`
3. Iterate to the 2 <li> _ElementHandle_
4. Use `ElementHandle.click()`

=> Not possible to do it this way since we cannot do `ElementHandle.$$`.

Any idea how to achieve this?
If not, this would be a really useful feature.

**Comment by ebidel** [comment]
Not sure I completely follow from the examples given. 

The selector `'#leftNavContainer ul:nth-child(0n+1)'` doesn't match because the div needs `id=leftNavContainer`.

In your second example, if you wanted to click the 2nd `li` in the 3rd `ul`, wouldn't the selector be `#leftNavContainer ul:nth-child(3) li:nth-child(2)`?

**Comment by lerayj** [comment]
@ebidel Yep sorry I will edit, I went to fast, I wrote a fake example which is not matching with the current issue.
Anyway, the problem is the same: `div ul:nth-child(2) li:nth-child(1)` won't work it seems nth-child isn't supported.

**Comment by twalpole** [comment]
@lerayj But shouldn't it output null ?  `click` just returns a `Promise` that will resolve to null on success -- it would reject if the element wasn't found

**Comment by aslushnikov** [comment]
@lerayj the following outputs `'Has element!` for me.
```js
const puppeteer = require('.');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  let page = await browser.newPage();
  page.setContent(`<div id="leftNavContainer">
  <ul>
    <li></li>
    <li></li>
  </ul>
  <ul>
    <li></li>
    <li></li>
  </ul>
  <ul>
    <li></li>
    <li></li>
  </ul>
  <ul>
    <li></li>
    <li></li>
  </ul>
</div>`);

  let element = await page.$('#leftNavContainer ul:nth-child(0n+2) li:nth-child(0n+1)');
  console.log(element ? 'Has element!' : 'Failed to get element');
  browser.close();
})();
```

**Comment by lerayj** [comment]
Thanks @aslushnikov, everything is working. 

To conclude it is my bad, the real case scenario imply `<h4>` inbetween `<ul>`. In this case, I have to use `:nth-of-type(an+b)` and not `:nth-child(an+b)` which works only with same type.
I missed a point on` nth-*` things, nothing related to puppeteer.

Sorry and Thanks everyone.
