### ISSUE TITLE
Exporting html table to PDF 

### ISSUE THREAD

**Issue by jan0991** [puppeteer/puppeteer#4951]
[I also posted this to SO](https://stackoverflow.com/questions/57966682/puppeteer-pdf-export-table-headers) but think this could be a general puppeteer bug.

Anyway, exporting page to PDF messes up table headers and puts them on top of every page like so:

![](https://i.stack.imgur.com/ySm9E.png)

I need to solve this ASAP for a client, any ideas or quick workarounds?

**Comment by karatekaneen** [comment]
Also have the same problem. 
Did you find a solution since you closed the issue?

**Comment by blackhu0804** [comment]
Have you solved the problem? I also met the same problem.

**Comment by karatekaneen** [comment]
I solved it by changing to `display: block` and removing the format property and only assigning page width and height. Still quite fragile though but it works. Good luck!
