### ISSUE TITLE
Some DOM elements are visible to Puppeteer in 1.19 but invisible in 1.20 (with steps to reproduce)

### ISSUE THREAD

**Issue by alberto56** [puppeteer/puppeteer#4952]
Edit, see comment below.

**Comment by alberto56** [comment]
Edit, see comment below.

**Comment by alberto56** [comment]
OK reopening with steps to reproduce, in fact it has nothing to do with sessions, it's more that certain elements are invisible in 1.20, and visible in 1.19.

First, here is the output from Puppeteer 1.19 and 1.20
-----

Notice that the "Configure Block" and "Add organization" links in the sidebar are missing from 1.20.

![puppeteer-1 19](https://user-images.githubusercontent.com/808265/65182051-6f2bc100-da2e-11e9-87f2-d6448b52926c.png)
![puppeteer-1 20](https://user-images.githubusercontent.com/808265/65182052-6fc45780-da2e-11e9-937a-f1baab0bc6d2.png)

Here is the difference between the two environments 
-----

    $ diff 1.19 1.20 --context=1
    ***************
    *** 807,811 ****
          "puppeteer": {
    !       "version": "1.19.0",
    !       "resolved": "https://registry.npmjs.org/puppeteer/-/puppeteer-1.19.0.tgz",
    !       "integrity": "sha512-2S6E6ygpoqcECaagDbBopoSOPDv0pAZvTbnBgUY+6hq0/XDFDOLEMNlHF/SKJlzcaZ9ckiKjKDuueWI3FN/WXw==",
            "requires": {
    --- 807,811 ----
          "puppeteer": {
    !       "version": "1.20.0",
    !       "resolved": "https://registry.npmjs.org/puppeteer/-/puppeteer-1.20.0.tgz",
    !       "integrity": "sha512-bt48RDBy2eIwZPrkgbcwHtb51mj2nKvHOPMaSH2IsWiv7lOG9k9zhaRzpDZafrk05ajMc3cu+lSQYYOfH2DkVQ==",
            "requires": {
    ***************
    *** 901,908 ****
          "string.prototype.trimleft": {
    !       "version": "2.0.0",
    !       "resolved": "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.0.0.tgz",
    !       "integrity": "sha1-aLaqjhYsaoDnbjqKDC50cYbicf8=",
            "requires": {
    !         "define-properties": "^1.1.2",
    !         "function-bind": "^1.0.2"
            }
    --- 901,908 ----
          "string.prototype.trimleft": {
    !       "version": "2.1.0",
    !       "resolved": "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.1.0.tgz",
    !       "integrity": "sha512-FJ6b7EgdKxxbDxc79cOlok6Afd++TTs5szo+zJTUyow3ycrRfJVE2pq3vcN53XexvKZu/DJMDfeI/qMiZTrjTw==",
            "requires": {
    !         "define-properties": "^1.1.3",
    !         "function-bind": "^1.1.1"
            }
    ***************
    *** 910,917 ****
          "string.prototype.trimright": {
    !       "version": "2.0.0",
    !       "resolved": "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.0.0.tgz",
    !       "integrity": "sha1-q0pW2AKgH75yk+EehPJNyBZGYd0=",
            "requires": {
    !         "define-properties": "^1.1.2",
    !         "function-bind": "^1.0.2"
            }
    --- 910,917 ----
          "string.prototype.trimright": {
    !       "version": "2.1.0",
    !       "resolved": "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.1.0.tgz",
    !       "integrity": "sha512-fXZTSV55dNBwv16uw+hh5jkghxSnc5oHq+5K/gXgizHwAvMetdAJlHqqoFC1FSDVPYWLkAKl2cxpUT41sV7nSg==",
            "requires": {
    !         "define-properties": "^1.1.3",
    !         "function-bind": "^1.1.1"
            }

How to reproduce
-----

I have set up a Docker project specifically to reproduce this.

A. [Clone this project](https://github.com/alberto56/puppeteer-issue-4952)

B. Then run ./run-tests.sh 

C. Confirm that ./dom-captures/puppeteer-1.19.html and ./dom-captures/puppeteer-1.20.html are identical, this means that puppeteer sees the same markup whether it's 1.19 or 1.20.

D. Open ./screenshots/puppeteer-1.20.png and ./screenshots/puppeteer-1.19.png and you will see that with 1.20 some dom elements are missing.

**Comment by vdnsnkv** [comment]
We are experiencing the same issues. 
Here's output of page.pdf() function called on the exact same page in the same environment using versions 1.19.0 and 1.20.0.
**1.19.0**
![output_1.19.0](https://user-images.githubusercontent.com/16564474/65322666-23a12080-dbb0-11e9-8ef6-5309ef455dde.png)
**1.20.0**
![output_1.20.0](https://user-images.githubusercontent.com/16564474/65322664-23a12080-dbb0-11e9-88a0-476b473d84b8.png)
