### ISSUE TITLE
Heroku image out of place - ingoring CSS maybe

### ISSUE THREAD

**Issue by chrisdel101** [puppeteer/puppeteer#4953]
**Tell us about your environment:**

* Puppeteer version:
6.10.0
* Platform / OS version:
Ubuntu/Heroku

**What steps will reproduce the problem?**
On Heroku puppeteer images have begun to behave strangely and do not match the HTML/CSS that is on the page. This does not occur on my local environment. 

link to what image should look like: 
https://res.cloudinary.com/chris-del/image/upload/v1568762762/Screen_Shot_2019-09-17_at_5.23.18_PM_q8oltl.png
link to HTML version of image: 
https://f1-cards.herokuapp.com/team/mercedes
link to puppeteer image that's broken:
https://f1-cards.herokuapp.com/api/team/mercedes

**Please include code that reproduces the issue.**
Running on Heroku
```
const browser = await puppeteer.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox']
 })
await page.goto(`https://f1-cards.herokuapp.com/team/mercedes`)
await page.screenshot({ path: 'example.png' })
await browser.close()
```

**What is the expected result?**
Image should look like the one in the first link, and not like the one in the third.

**Comment by kblok** [comment]
I bet you can fix it changing the Viewport.

**Comment by chrisdel101** [comment]
Could you be a bit more specific re: those images I provided? The images themselves are positioned in the viewport correctly. It's the inside of one set of images that is off. I don't imagine the viewport is able to effect the inner part of the image is it? Or am I misunderstanding?
I need the third image to look like the first - both are puppeteer - only diff is one is mac other is heroku.

**Comment by chrisdel101** [comment]
Yep viewport issue.
