### ISSUE TITLE
How to check if an HTML tag has an attribute of 'disabled' or not?

### ISSUE THREAD

**Issue by vyomsrivastava** [puppeteer/puppeteer#4955]
``` <material-button animated="true" class="btn btn-yes _ngcontent-EXCHANGE-57 _nghost-EXCHANGE-2" tabindex="0" role="button" aria-disabled="false" elevation="4"><div class="content _ngcontent-EXCHANGE-2">Save</div><material-ripple class="_ngcontent-EXCHANGE-2"><div class="__acx-ripple" style="top: -116px; left: -83px; transform: translate(-13px, 6px) scale(0.364962);"></div></material-ripple></material-button> ```

``` <material-button animated="true" class="btn btn-no _ngcontent-EXCHANGE-57 _nghost-EXCHANGE-2" tabindex="0" role="button" aria-disabled="false" elevation="4" disabled><div class="content _ngcontent-EXCHANGE-2">Save</div><material-ripple class="_ngcontent-EXCHANGE-2"><div class="__acx-ripple" style="top: -116px; left: -83px; transform: translate(-13px, 6px) scale(0.364962);"></div></material-ripple></material-button> ```

I want to click on .btn-no or .btn-yes class when the disabled attribute gets removed. How to do that?

**Comment by kblok** [comment]
You can use `waitForSelector`:

```js
const yes = await page.waitForSelector(".btn-yes:not([disabled])");
await yes.click();
```

**Comment by vyomsrivastava** [comment]
thanks a lot for you answer @kblok , can we add some conditions? This process is being run in a loop so can we do it like this? 
``` const yes = await page.waitForSelector(".btn-yes:not([disabled])");
if(yes)
 await yes.click();
else
 continue;
```

**Comment by kblok** [comment]
Yes, you can. Remember that `waitForSelector` will throw a timeout error after 30 secs (default) if there is no `yes` button, so, technically speaking, `yes` will never be null, because the code will fail.

**Comment by vyomsrivastava** [comment]
using something like try-catch should solve the issue.

``` 
try{
   await page.waitForSelector(".btn-yes:not([disabled])");
   await page.click('.btn-yes');
}catch(err){
  console.log(err);
  continue;
}
```

**Comment by leiming** [comment]
Same problem.

Shall we get `disabled` attribute like `className` by `jsHandle._remoteObject.description`?

So we prefer obtaining the HTMLElement status accurately which be used to `loop` or `if conditions` to define `getElementProperty` or `isDisabledElement` to using `try-catch` block .

@vyomsrivastava , could we support this feature?

**Comment by vyomsrivastava** [comment]
@leiming  well I solved the issue by try and catch.

`try{
   await page.click('btn-yes);
}catch(err){
  await page.click('btn-no');
}
`

**Comment by szakhar** [comment]
> You can use `waitForSelector`:
> 
> ```js
> const yes = await page.waitForSelector(".btn-yes:not([disabled])");
> await yes.click();
> ```

Thanks man :)
