### ISSUE TITLE
Discrepancy in selector results from Puppeteer and Chrome

### ISSUE THREAD

**Issue by hubitor** [puppeteer/puppeteer#4957]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: Arch Linux
* URLs (if applicable): [https://www.amazon.com](url) (and others...)
* Node.js version: 10.16.1

**What steps will reproduce the problem?**
I'm trying to extract some page content with Puppeteer. When I use `document.querySelectorAll` in Chrome I get different results as when I use the same in Puppeteer. Also the language is different, e.g. the text in `input.placeholder` appears with Chrome in my local language whereas in Puppeteer in english. I tried several sites, for some there is consistency for some there isn't. Is there a way to ensure that a web page content is exactly the same with both Chrome and Puppeteer?

Here is an example for amazon:

```
const puppeteer = require("puppeteer");
const url = "https://www.amazon.com";

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto(url);
  const inputs = await page.evaluate(() =>
    [...document.querySelectorAll("input")].map(input => input)
  );
  console.log(inputs);
  //await browser.close();
})();
```
I tried with:

`await page.content();`

` await page.goto(url, { waitUntil: "networkidle2" });`

` await page.waitFor(60000);`

without success.

**What is the expected result?**

These are the array items I get in the Chrome console with:
`[...document.querySelectorAll("input")].map(input => input)`

```
0: input.nav-input
1: input#twotabsearchtextbox.nav-input
2: input#unifiedLocation1ClickAddress
3: input#ubbShipTo
4: input.a-button-input
5: input.a-button-input
6: input.a-carousel-firstvisibleitem
7: input#rwol-display-called
8: input.a-button-input
9: input
```

**What happens instead?**
These are the array items I get with Puppeteer:
```
[ { jQuery16408606549367568397: 99 },
  { jQuery16408606549367568397: 98 },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {} ]
```

**Comment by kblok** [comment]
`evaluate` won't serialize DOM elements. You could use `evaluateHandle`. But notice that `evaluateHandle` will return "pointers" to DOM elements on the Chromium side.

**Comment by hubitor** [comment]
Thanks. I found a similar issue here:
[https://github.com/GoogleChrome/puppeteer/issues/2609](url)
