### ISSUE TITLE
Puppeteer throwing ECONNRESET error while connecting to wsEndpoint

### ISSUE THREAD

**Issue by aftabnack1** [puppeteer/puppeteer#4958]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Alpine Linux - Edge
* Node.js version: 10

**What steps will reproduce the problem?**

I am trying to run my puppeteer tests within a docker.
1. I followed the [troubleshooting](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine) page and replicated the same dockerfile

```
FROM alpine:edge

# Installs latest Chromium (76) package.
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      openjdk8-jre \
      bash \
      nodejs \
      yarn

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

WORKDIR /usr/local/extranet

COPY ./ /usr/local/extranet

RUN yarn && yarn build

CMD ["yarn", "test:ci"]
```

2. I am running my tests using Jest + Puppeteer using `jest-puppeteer` package. Described in the example found in https://github.com/smooth-code/jest-puppeteer/tree/master/examples/create-react-app

3. I am running my testcases with `yarn test:ci` command which does the following.

- Start my local server, to serve my website
- Launch puppeteer with the following config:

```js
{
    headless: true,
    executablePath: '/usr/bin/chromium-browser',
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-background-timer-throttling', '--disable-backgrounding-occluded-windows', '--disable-renderer-backgrounding']
}
```

- Then extract the wsEndpoint using `browser.wsEndpoint()`
- Use that value in another place to do a `puppeteer.connect()` passing the `wsEndpoint` value

**What is the expected result?**

The test case ran successfully

**What happens instead?**

Getting an error: `connect ECONNREFUSED 127.0.0.1:36085`
The port keeps varying everytime.

**Comment by aftabnack1** [comment]
An update on this. On a hunch I tried downgrading the version of chrome & puppeteer.
It is working with Chrome 72. :fire: :fire: 

Here is my new dockerfile (taken from the history of the troubleshooting page), rest of the setup doesn't have any change.

```
FROM node:10-alpine

# Installs Chromium (72) package.
RUN apk update && apk upgrade && \
      echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
      echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
      apk add --no-cache \
      chromium@edge=~72.0.3626.121-r0 \
      nss@edge \
      freetype@edge \
      freetype-dev@edge \
      openjdk8-jre \
      bash \
      harfbuzz@edge \
      ttf-freefont@edge

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

WORKDIR /usr/local/extranet

COPY ./ /usr/local/extranet

RUN yarn && yarn build

CMD ["yarn", "test:ci"]
```

**Comment by aftabnack1** [comment]
Any update on this? Anything I can do to help move this along??

**Comment by pavelstudeny** [comment]
Same problem with 2.0.0 in a node:10-slim docker container running in Linux. The same container in MacOS runs OK.

**Comment by EXPEpaher** [comment]
Seeing the same issue, downgrade did not help. Tried puppeteer version 1.11.0 which comes with chromium_revision 609904. I think it corresponds to chrome-72 based on the version logs here,
https://www.npmjs.com/package/puppeteer

Running node v10.15.3 on a Linux machine. Could use some help please.

**Comment by joneslloyd** [comment]
Same here

**Comment by bboydflo** [comment]
same issue with latest puppeteer (10.2.0) and jest-puppeteer 5.0.4 :(

**Comment by raphamzn** [comment]
same issue here, any solution? =[

**Comment by mccool** [comment]
I had a similar error. I'm using pagedjs-cli which uses puppeteer:
```
"Error: Command failed: pagedjs-cli --browserArgs \"--no-sandbox,--no-zygote,--disable-gpu,--single-process,--font-render-hinting=none,--disable-font-subpixel-positioning\" --additional-script \"/var/task/assets/createToc.js\" -o /tmp/0b686965-8f2c-4297-8c79-f10ac965746f.pdf /tmp/934ac94f8d76a4412f37c43dacf329ee.html",
        "- Loading: /tmp/934ac94f8d76a4412f37c43dacf329ee.html",
        "ErrorEvent {",
        "  target: WebSocket {",
        "    _events: [Object: null prototype] { open: [Function], error: [Function] },",
        "    _eventsCount: 2,",
        "    _maxListeners: undefined,",
        "    _binaryType: 'nodebuffer',",
        "    _closeCode: 1006,",
        "    _closeFrameReceived: false,",
        "    _closeFrameSent: false,",
        "    _closeMessage: '',",
        "    _closeTimer: null,",
        "    _extensions: {},",
        "    _protocol: '',",
        "    _readyState: 3,",
        "    _receiver: null,",
        "    _sender: null,",
        "    _socket: null,",
        "    _bufferedAmount: 0,",
        "    _isServer: false,",
        "    _redirects: 0,",
        "    _url: 'ws://127.0.0.1:35615/devtools/browser/1c9e009e-368a-4a60-9269-c9b2652eb476',",
        "    _req: null,",
        "    [Symbol(kCapture)]: false",
        "  },",
        "  type: 'error',",
        "  message: 'socket hang up',",
        "  error: Error: socket hang up",
        "      at connResetException (internal/errors.js:639:14)",
        "      at Socket.socketOnEnd (_http_client.js:499:23)",
        "      at Socket.emit (events.js:412:35)",
        "      at endReadableNT (internal/streams/readable.js:1334:12)",
        "      at processTicksAndRejections (internal/process/task_queues.js:82:21) {",
        "    code: 'ECONNRESET'",
        "  }",
        "}",
```

I am running on aws lambda in a docker container and realized that I wasn't downloading the fonts required by my application. Added the fonts and the error is gone.
