### ISSUE TITLE
Unable to access cross domain iframes when not headless

### ISSUE THREAD

**Issue by tshmit** [puppeteer/puppeteer#4960]
After updating to v1.20 I'm unable to access iframes from a foreign domain with headless: false.

Here's a page with 4 iframes, 3 of which are cross domain:

```html
<html>
<body>
<iframe src="https://en.wikipedia.org/wiki/IFrame"></iframe>
<iframe src="http://example.com/"></iframe>
<iframe srcdoc="<p>Frame [2]</p>"></iframe>
<iframe src="http://www.htmlhelp.com/reference/html40/special/iframe.html"></iframe>
</body>
</html>
```

And some code that tries to access the frames:

```javascript
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();
    await page.goto('http://localhost: ... ');

    console.log('childFrames count:', page.mainFrame().childFrames().length);
    console.log('pageFrames count:', page.frames().length);

    const iframeHandles = await page.$$('iframe');

    console.log('contentFrame[0] is valid:', await iframeHandles[0].contentFrame() !== null);
    console.log('contentFrame[2] is valid:', await iframeHandles[2].contentFrame() !== null);

    await browser.close();
})();
```

Output with headless false:
```
childFrames count: 1
pageFrames count: 2
contentFrame[0] is valid: false
contentFrame[2] is valid: true
```

Output with headless true:
```
childFrames count: 4
pageFrames count: 9
contentFrame[0] is valid: true
contentFrame[2] is valid: true
```
**What is the expected result?**
I'd expect to be able to access cross domain iframes whether running headless or not (this was the case as of ~v1.15) Am I missing something?

**Comment by taeyoung4808** [comment]
same problem here !

**Comment by hi-ogawa** [comment]
It seems some workaround is already discussed here https://github.com/GoogleChrome/puppeteer/issues/2548#issuecomment-390077713 and it worked for me.

**Comment by tshmit** [comment]
Thanks for your reply, @hi-ogawa. 
You're right `--disable-features=site-per-process` does seem to fix the problem.

I'm perplexed as to why my code ran without flag until updating to 1.20, but that's ok, I'll take it! :-)

**Comment by gif-gif** [comment]
--disable-features=site-per-process does seem to fix the problem.
but my chormium is crashed by add this item when handless is false

**Comment by ClockRide** [comment]
Doesn't work for me. It's fucking disgusting!

**Comment by flashjames** [comment]
The correct args are:

await puppeteer.launch({headless: headless, devtools: true, args: ['--disable-web-security', '--disable-features=IsolateOrigins', ' --disable-site-isolation-trials']});

But puppeteer kept crashing.

The reason was that I used an old puppeteer version, puppeteer 1.8.0.
After upgrading to puppeteer@8.0.0, it works.

You can check that isolation is disabled in:
chrome://process-internals

Suggested in https://stackoverflow.com/a/51320323/337587

More information on the flag: https://www.chromium.org/Home/chromium-security/site-isolation

@tshmit I suggest you close this issue, since it fixed in some version since you had the problem.

**Comment by 8m0** [comment]
You don't even understand how sexy you are

> The correct args are:

**Comment by TheGP** [comment]
According to ChatGPT and my testing, this is what actually works:

```
.\chrome.exe --disable-site-isolation-trials
```
Then, when you go to `chrome://process-internals/#site-isolation` you will see `Site Isolation mode: Disabled`. Yay!
