### ISSUE TITLE
Puppeteer takes more and more memory over time

### ISSUE THREAD

**Issue by TomasKavaliauskas** [puppeteer/puppeteer#4961]
Hello, Im using puppeteer to keep my game room 24/7. I have such a script:

```
const puppeteer = require('puppeteer');
const fs = require('fs');

function sleep(ms){
    return new Promise(resolve=>{
        setTimeout(resolve,ms)
    })
}

(async () => {

    await puppeteer.launch({ 
        slowMo: 10,
        headless: true,
        args:[ 
            '--remote-debugging-port=9222',
            '--lang=en-US,en',
            '--no-sandbox',
            '--disable-setuid-sandbox',
        ], ignoreHTTPSErrors: true, dumpio: false }).then(async browser => {

            const page = await browser.newPage();

            try {
                page.on("pageerror", function(err) {  
                    theTempValue = err.toString();
                    console.log("Page error: " + theTempValue); 
                });
                
                page.on("error", function (err) {  
                    theTempValue = err.toString();
                    console.log("Error: " + theTempValue); 
                });

                await page.goto('https://haxball.com/headless', {timeout:90000});
                await page.waitFor(10000);
                await page.evaluate(fs.readFileSync('room.js', 'utf8'));

                while(true)
                {
                
                    await sleep(1000000000);
                
                }

            }catch(erro){

                await page.screenshot({path: 'error.png'});

            }

         });

})();
```

I noticed, that over time, this puppeteer script takes more and more memory:

![Screenshot from 2019-09-22 11-56-44](https://user-images.githubusercontent.com/13218137/65384872-2296fd00-dd30-11e9-8b93-cfe90e5d038b.png)

It slowly takes more and more memory. For example yesterday this script took about 18.3 percent of whole memory. Now this number is 20.8 and it gradually increases, until the point when I need to restart the room.

Im using pm2 to launch my script. I noticed that there are a lot of ongoing chromium processes. Not sure if this is a normal behavior.

**Comment by joaomirandas** [comment]
Any ideia of how to improve memory comsuption?! it still happening for me - more and more memory is necessary to keep exactly the same page open, only taking functions and firing over EMIT events on my NodeJS. 

![Captura de Tela 2020-02-27 às 16 42 20](https://user-images.githubusercontent.com/29043431/75480611-57168100-5980-11ea-9d9f-45c6b2bcd2e6.png)

**Comment by iamshouvikmitra** [comment]
Yup keeping puppeteer running for long is hogging memory in an pretty unpredictable nature. At tips?
My use case needs me to keep a page open and not disconnect or close the session! All suggestion I find tells us to reuse pages and stuff, but for me, I just need one website to be logged in 24*7, i.e, suffer very less down time. Is puppeteer suitable for that kind of work, if not could you please suggest me other options to puppeteer for the same, and if yes, what kind of optimizations do you guys recommend for such kind of workload?
