### ISSUE TITLE
window.performance.memory empty object when running headless

### ISSUE THREAD

**Issue by cjroebuck** [puppeteer/puppeteer#4962]
* Puppeteer version: 1.19
* Platform / OS version: Osx / Ubuntu
* URLs (if applicable): any
* Node.js version: any

`window.performance.memory`

**What is the expected result?**
MemoryInfo object with info about the memory usage of the page e.g.  `{totalJSHeapSize: 7506920, usedJSHeapSize: 6560960, jsHeapSizeLimit: 2197815296}`

**What happens instead?**
Get an empty object {} only in headless mode.

**Comment by gsai0205** [comment]
@cjroebuck This solution worked for me
https://stackoverflow.com/questions/38087467/is-it-possible-to-use-window-performance-memory-in-headless-chrome
