### ISSUE TITLE
Link to Slack channel is outdated

### ISSUE THREAD

**Issue by erwinheitzman** [puppeteer/puppeteer#4969]
Hi there, I am looking to join the Puppeteer Slack community but cannot join because of an outdated link in the readme and I could not find a working link anywhere else.

**Comment by chetanmadaan** [comment]
I'd also be interested in this!

**Comment by evanhalley** [comment]
Same here!

**Comment by mathiasbynens** [comment]
The new link is: https://join.slack.com/t/puppeteer/shared_invite/enQtMzU4MjIyMDA5NTM4LWI0YTE0MjM0NWQzYmE2MTRmNjM1ZTBkN2MxNmJmNTIwNTJjMmFhOWFjMGExMDViYjk2YjU2ZmYzMmE1NmExYzc

**Comment by marksteward** [comment]
This no longer works.

**Comment by AzySir** [comment]
@mathiasbynens would love an update here of the URL/Invite :)

**Comment by francovenica** [comment]
👍 I want the link too. Being able to share and ask question in real time would be helpful

**Comment by ayoola-moore** [comment]
This links no longer works for me as well

**Comment by Mattwmaster58** [comment]
Could you provide an updated link @mathiasbynens ?

**Comment by Granitosaurus** [comment]
Instead maybe migrating chat to something more open and accessible like Matrix would be a good idea which provides a static, never changing name for a channel
