### ISSUE TITLE
goto returns null sometimes

### ISSUE THREAD

**Issue by simlevesque** [puppeteer/puppeteer#4970]
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20
* Platform / OS version: Linux
* Node.js version: 12.3

**What steps will reproduce the problem?**

I'm using docker with the stock Dockerfile.

I'm having trouble reproducing the error, it is seemingly random. After a certain number of requests in a browser instance, goto starts to return null for no reason.

I've looked at other issues with the same problem (#1391, #2479) and I tried what they said.

First I tweaked the shm, it was at 64m and now it's at 2gb. With 2gb, the bug happens way later. If I set the shm at 16m, the bug happens almost right away. Seems like some sort of memory leak.

I tried a couple of other things such at waitFor: 'networkidle0' but that did not help. Then I found this comment: https://github.com/GoogleChrome/puppeteer/issues/2479#issuecomment-408263504

This workaround seems to have fixed the problem.

There's also this guy who has the same problem as me: https://github.com/yujiosaka/headless-chrome-crawler/issues/354

If you need anything just ask me.

**Comment by xavierraffin** [comment]
@simlevesque this URL return null for response of goto everytime: http://www.faalkaart.nl

I tried [#2479 (comment)](https://github.com/GoogleChrome/puppeteer/issues/2479#issuecomment-408263504) but it does not solve the issue.

**Comment by xavierraffin** [comment]
I posted a separate issue here #5011

**Comment by simlevesque** [comment]
Hi @xavierraffin, thank you very much for your input.

It's weird that the workaround does not fix it for you...

I'm wondering if it's the same issue.

The redirection seems like it could be part of the issue on my end too.

**Comment by AntonGsv** [comment]
page.goto returns null with some kind of URL dependency:
```
const puppeteer = require('puppeteer');

function check(responseOrNull, url) {
    if (!!responseOrNull) {
        console.log(`is response - ${url} ${responseOrNull.ok()} ${responseOrNull.status()}`);
    } else {
        console.log(`is null - ${url}`);
    }
}

async function runBrowser(urls) {
    const browser = await puppeteer.launch({headless: true});
    const page = await browser.newPage();
    console.log(await browser.version());

    for (const url of urls) {
        const response = await page.goto(url);
        check(response, url);
    }
    await browser.close();
}

(async () => {
    await runBrowser([`https://myip.com`, `https://myip.com#example=1`]);
    await runBrowser([`https://www.myip.com`, `https://www.myip.com#example=1`]);
    await runBrowser([`https://api.myip.com`, `https://api.myip.com#example=1`]);
})();
```
results:
```
HeadlessChrome/91.0.4469.0
is response - https://myip.com true 200
is response - https://myip.com#example=1 true 200
HeadlessChrome/91.0.4469.0
is response - https://www.myip.com true 200
is null - https://www.myip.com#example=1
HeadlessChrome/91.0.4469.0
is response - https://api.myip.com true 200
is null - https://api.myip.com#example=1

```

**Comment by mattparlane** [comment]
I've just been hit by this too. I can reliably reproduce @AntonGsv's error, but if I change the order of the URLs it works fine, also reliably:

```
await runBrowser([`https://api.myip.com#example=1`, `https://api.myip.com`]); // <-- reversed order
```

```
HeadlessChrome/93.0.4577.0
is response - https://api.myip.com#example=1 true 200
is response - https://api.myip.com true 200
```
