### ISSUE TITLE
How can I unref an instance launched with puppeteer.launch?

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#4971]
I'm trying to do something similar to this:
```javascript
const puppeteer = require('puppeteer')
const browser = await puppeteer.launch()
browser.process().unref()
```
But that doesn't close the node process after it is finished.

This actually works:
```javascript
const { spawn } = require('child_process')
const subprocess = spawn('top', {
  stdio: 'ignore'
})
subprocess.unref()
```
So I'm guessing setting the stdio to `ignore` is important. How can I do this? Preferably without having to use `connect`.

This also works:
```javascript
const subprocess = spawn('top')
subprocess.stdin.unref()
subprocess.stdout.unref()
subprocess.stderr.unref()
subprocess.unref()
```

But this doesn't:
```javascript
const browser = await puppeteer.launch()
browser.process().unref()
browser.process().stdin.unref()
browser.process().stdout.unref()
browser.process().stderr.unref()
```

**Comment by dmail** [comment]
Any news on this that would be awesome

**Comment by dmail** [comment]
I wanted to see how to properly unref a chrome instance and it seems doable but puppeteer would have to expose an internal called gracefullyCloseChrome.

https://github.com/puppeteer/puppeteer/blob/d17708ba1fc8411941bfd07f633aaf2fb5cb671e/lib/Launcher.js#L194

If it was exposed, let's say under a browser method called `unref` we could do something like
```js
const puppeteer = require("puppeteer")

const browser = await puppeteer.launch()
browser.unref()
```

I am not a contributor to puppeteer but to me it means adding

```js
browser.unref = gracefullyCloseChrome
```

Before

https://github.com/puppeteer/puppeteer/blob/d17708ba1fc8411941bfd07f633aaf2fb5cb671e/lib/Launcher.js#L185

Would be what we want.

I contact them on slack to know what they think about it.

**Comment by dmail** [comment]
That being said `unref` concept and `gracefullyCloseChrome` are not the same.

Calling `unref` means the ressource, here the chromium browser, must remain usable but does not keep node process alive.
`gracefullyCloseChrome` does not match this expectation.
