### ISSUE TITLE
Console Messages are not formatted correctly.

### ISSUE THREAD

**Issue by greggman** [puppeteer/puppeteer#4972]
In _addConsoleMessage(type, args, stackTrace)

this line

https://github.com/GoogleChrome/puppeteer/blob/e0c8d46af1ce2c063778b66aa29c4c00ab8aeba5/lib/Page.js#L627

Seems to do the wrong thing? The problem is `textTokens.join(' ')`

`console.log` [works like printf](https://developer.mozilla.org/en-US/docs/Web/API/Console/log) (or like node's [util.format](https://nodejs.org/api/util.html#util_util_format_format_args))

In other words

     console.log('Hello %s', 'World');    

In the browser prints

     Hello World 

but in puppeteer it ends up being

     Hello %s World

### Steps to reproduce

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();

  page.on('console', msg => {
    console.log(msg.text());   // prints 'hello %s world' but should print 'hello world'
  });

  await page.evaluate(() => console.log('hello %s', 'world'));
  await browser.close();
});

```

* Puppeteer version: 1.20.0
* Platform / OS version: MacOS 10.14.6
* URLs (if applicable): N/A
* Node.js version: 12.6.0

**Comment by akosyakov** [comment]
I've ended up using raw args and passing them to Node.js for formatting:
```js
page.on('console', async e => {
    const args = await Promise.all(e.args().map(a => a.jsonValue()));
    const log = e.type() === 'warning' ? console.warn : console[e.type()];
    log(args[0], ...args.slice(1));
});
```

**Comment by PFight** [comment]
It would be great to add method to ConsoleMessage, that formats message or do smth like @akosyakov suggested.
