### ISSUE TITLE
feat: non-blinking caret

### ISSUE THREAD

**Issue by manucorporat** [puppeteer/puppeteer#4974]
it would be very valuable to have an option to render non-blinking carets when an input is focused, this way developers can take screenshots while false mismatches.

Currently we use CSS to hide all the caret using css:
```css
* {
  caret-color: transparent !important;
}
```

But this solution is not ideal, since it completely hides the caret. A chrome flag like `--static-caret` or `--caret-mode=static` would be a great API.

### Steps to reproduce

Focus an input, and take several screenshots. 
Each screenshot might be different because of the blinking caret.

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: osx
* URLs (if applicable):
* Node.js version:

**Comment by DCzajkowski** [comment]
Can you reopen this @manucorporat?
