### ISSUE TITLE
Why is an ElementHandle equal to JSHandle@node?

### ISSUE THREAD

**Issue by hubitor** [puppeteer/puppeteer#4976]
Methods like page.$(selector) and page.$$(selector)  are supposed to return an ElementHandle.

When I try to check what kind of Object I've got by using the toString() method on such a result, I'm expecting to see something like: `<ElementHandle>` instead I see `JSHandle@node`.

So an ElementHandle is a JSHandle@node? Why is this so?

For example (taken from:)
[https://github.com/GoogleChrome/puppeteer/issues/2179](url)

```
"use strict";

const puppeteer = require("puppeteer");

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.setContent('<form data-form="personal">test</form>');

    console.log(await page.evaluate(() => document.body.outerHTML));

    console.log(
      await page.evaluate(
        () => document.querySelector('[data-form="personal"]').innerText
      )
    );

    const elementHandle = await page.$('[data-form="personal"]');
    console.log("elementHandle: ", elementHandle.toString());

    const jsHandle = await elementHandle.getProperty("innerText");
    console.log("jsHandle: ", jsHandle.toString());

    const json = await jsHandle.jsonValue();
    console.log(json);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

This is the output:

```
<body><form data-form="personal">test</form></body>
test
elementHandle:  JSHandle@node
jsHandle:  JSHandle:test
test
```

**Comment by peakyxi** [comment]
elementHandle extends from JShandle

**Comment by AnthonyCavanagh** [comment]
The most intelligent question on this subject, so of course no reply

**Comment by paddelboot** [comment]
Same problem. I run `page.$$( selector )` and get a bunch of `JSHandle@node` in return. I expected an `ElementHandle`, as defined in the [docs](https://pptr.dev/api/puppeteer.page.__), from which I could then retrieve child elements.

**Comment by OrKoN** [comment]
It's actually ElementHandle that is returned: check `handle.constructor.name`. The toString is only defined on the parent class of ElementHandle that is JSHandle and, by definition, an element handle is also a JSHandle. `JSHandle@node` means an element handle. Also, refer to the typescript types https://github.com/puppeteer/puppeteer/blob/main/src/common/Page.ts#L1075

**Comment by lowzyyy** [comment]
I have the same problem with this. $$eval is giving me JSHandle@node and i cant call $eval or $ on such element. I am trying to "pierce" for some shadow root elements but i cannot use this methods or node elements because they are something like a primitive?

**Comment by elliotching** [comment]
@AnthonyCavanagh 
ElementHandle and JSHandle by itself is different, so I need to do proper checking to differentiate both of them.

it is very disappointed there are no short answer to differentiate both of them.

```
const handleA = await page.evaluateHandle(()=>{
    return document.querySelector("div.example")
})
```

`handleA` = `JSHandle`


```
const handleB = await page.$x("div[@class='example']")
```

`handleB` = `ElementHandle`


so when I having following check , handleB will throws error, because it is a circular structure
```
// check element visibility
    if (jsHandle.toString() == "JSHandle@node") {
        const visibility = await page.evaluate((e) => {
            return getComputedStyle(e).visibility;
        }, jsHandle);
        const rect = await page.evaluate((e) => {
            return {
                bottom: e.getBoundingClientRect().bottom,
                top: e.getBoundingClientRect().top,
                left: e.getBoundingClientRect().left,
                right: e.getBoundingClientRect().right,
                width: e.getBoundingClientRect().width,
                height: e.getBoundingClientRect().height,
            };
        }, jsHandle);
        console.log(`${elementName} = (${visibility},${rect.width},${rect.height})...`);
        if (visibility != "visible" || !(rect.width && rect.height)) {
            return true;
        } else {
            console.log(`${elementName} = ${jsHandle} is FOUND!`);
            return false;
        }
        // true = hidden
        // true = rect data missing
    }
```

**Comment by OrKoN** [comment]
You should also be able to use instanceof checks in the latest versions of Puppeteer if your code is dealing with a single Puppeteer version.

```
import puppeteer, { ElementHandle } from 'puppeteer';

const browser = await puppeteer.launch();

const page = await browser.newPage();

await page.goto('https://example.com');

let handle = await page.evaluateHandle(() => window);

if (handle instanceof ElementHandle) {
  console.log('element')
} else {
  console.log('not element')
}

handle = await page.$('body')

if (handle instanceof ElementHandle) {
  console.log('element')
} else {
  console.log('not element')
}
```

**Comment by Lightning00Blade** [comment]
You can also use [asElement](https://pptr.dev/api/puppeteer.jshandle.aselement) on the `JSHandle`.
Considering there are two methods to verify this I will close this issue.
If you encounter any issue please file a new issue.
