### ISSUE TITLE
Popup windows will not close

### ISSUE THREAD

**Issue by krististepanek** [puppeteer/puppeteer#4977]
### Steps to reproduce
**Tell us about your environment:**
* Puppeteer version: 1.20.0
* Platform / OS version: windows 10
* URLs (if applicable):
* Node.js version: 10.15.1

**What steps will reproduce the problem?**
Function defined to get a popup window that opens:
```
getNewWindow = () => {
    const promise: Promise<Page> = new Promise(resolve => this.page.browser().once('targetcreated', async (target) => {
      resolve(await target.page());
    }));
    return promise;
  }
```
code executing in test:
```
await buttonElement.click(); // button that launches popup window
const newPage = await this.getNewWindow();
await (await newPage.$(inputFieldSelector)).type('text')); // interact with the popup window
await newPage.close();
```

**What is the expected result?**
The popup window closes

**What happens instead?**
Puppeteer hangs and the popup window does not close.  Eventually my jest runner times out.

This code has been in place and functioning for a few months.  Reverting to Puppeteer v1.19.0 makes the code work as expected.

**Comment by likemoody** [comment]
@kristibostrom try this:
```
page.on('dialog', async dialog => {
	await dialog.dismiss();
});
```

https://chercher.tech/puppeteer/alerts-puppeteer
