### ISSUE TITLE
When we set User-Agent to Page, it doesn't work in Service Worker

### ISSUE THREAD

**Issue by Emmazi** [puppeteer/puppeteer#4978]
When we set User-Agent to Page, it doesn't work in Service Worker.

Our company's website can change wap to web automatically.

When we set User-Agent, and click some elements to another page, 
it begin change wap from Service Worker to web,web to wap ,finally it go to Infinite loop.

**Comment by nicolasliendo** [comment]
Is there a solution for this? We are facing the same problem. When we set User-Agent, it does not propagate to service workers, and his requests go out with "headless chrome" what is a problem in our case.

**Comment by l0ca1** [comment]
Hello,the problem still exists.CDP "Network.setUserAgentOverride" not work in ServiceWorker.

**Comment by l0ca1** [comment]
`const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: ["--enable-experimental-web-platform-features"],
    headless: false,
  });
  browser.on("targetcreated", async (target) => {
    if (target.type() === "service_worker") {
      const client = await target.createCDPSession();
      if (!client) return;
      console.log("service worker set useragent");
      await client.send("Network.setUserAgentOverride", {
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
        "platform": "MacIntel",
        "userAgentMetadata": {
          "brands": [
            {
              "brand": "Chromium",
              "version": "100"
            },
            {
              "brand": "Google Chrome",
              "version": "100"
            },
            {
              "brand": ";Not A Brand",
              "version": "96"
            }
          ],
          "fullVersion": "100.0.4896.127",
          "platform": "Mac OS X",
          "platformVersion": "10_15_7",
          "architecture": "x86",
          "model": "",
          "mobile": false
        }
      });
      const worker = await target.worker();
      if (!worker) return;
      const data = await worker.evaluate(() => {
        if ('userAgentData' in navigator) {
          return navigator.userAgentData.brands;
        }
        return undefined;
      }).catch(e => {
        console.log(e.message);
        return undefined;
      });
      console.log("userAgentData: " + JSON.stringify(data));
    }
  });
  const page = await browser.newPage();
  await page.goto('https://abrahamjuliot.github.io/creepjs/');
  // await browser.close();
})();`

node version: v14.20.0
puppeteer version: v17.0.0

**Comment by Emmazi** [comment]
const browser = await puppeteer.launch({
    args: ["--enable-experimental-web-platform-features"],
    headless: false,
  });

> 
if it's possilbe, you can set the args below before launch the browser.
ServiceWorker is not necessary in most cases.

args: [
        '--disable-web-security',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-gpu',
        '--disable-dev-shm-usage',
        '--disable-setuid-sandbox',
        '--no-first-run',
        '--no-sandbox',
        '--no-zygote',
        '--single-process',
        '--unhandled-rejections=strict',
        '--trace-warnings'
    ]
