### ISSUE TITLE
Browser History

### ISSUE THREAD

**Issue by nigeon** [puppeteer/puppeteer#498]
Hi,

I would like to get the path (urls) taken to reach the end URL, after following all redirects. I tried using Response and it's headers, but this (of course) doesn't work with client-side redirects, and it's just a workarround...:

```
page.on('response', interceptedResponse => {
      console.log('Response on ' + interceptedResponse.url + '. Status: ' + interceptedResponse.status + ' -> ' + interceptedResponse.headers.get('Location'));
    });
```

Is there any way to get the "browser history"?

Thanks

**Comment by pavelfeldman** [comment]
You should be getting `Page.Events.FrameNavigated` events upon each navigation, which is more or less your browser history. Does this address it?

**Comment by nigeon** [comment]
Yes it does! This shows all frames navigated in the main frame:

```
page.on('framenavigated', frame => {
  if(frame.parentFrame() === null){
    console.log(frame._url);
  }
});
```

Thanks!
