### ISSUE TITLE
Chromium crashes when --disable-features=site-per-process and devtools: true

### ISSUE THREAD

**Issue by kujbol** [puppeteer/puppeteer#4989]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: MacOS 10.14.6
* Node.js version: v12.10.0

**What steps will reproduce the problem?**
1. run code 
```js
const puppeteer = require("puppeteer");

puppeteer.launch({
    headless: false,
    devtools: true,
    args: [
        '--disable-features=site-per-process',
    ],
});
```

**What is the expected result?**
Chromium should not crash

**What happens instead?**
Chromium crashes on start, removing the devtools parameter is resolving the issue

**Comment by gif-gif** [comment]
@participant I have seem problem when this args added

**Comment by zeicmann** [comment]
Same for me. And waitForSelector doesn't work within iframe without '--disable-features=site-per-process'

**Comment by sapshah** [comment]
Same for me
