### ISSUE TITLE
Puppeteer 1.17 not compatible with node alpine anymore

### ISSUE THREAD

**Issue by ouraios** [puppeteer/puppeteer#4990]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Docker version 18.03.1-ce, build 9ee9f40 with Docker image `node:10.16-alpine`

* Node.js version: 10.16.3

**What steps will reproduce the problem?**

Our docker image have chrome 73 but apparently Puppeteer 1.17 is not able to dialog with chromium 73 or not completely but i cant found why ...

My dockerfile is the following : 

```
FROM node:10.16-alpine

# Environnement de build de l'image
ARG NODE_ENV

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installs make, g++, python and Chromium (73) packages.
RUN apk update && apk upgrade && \
        echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/community >> /etc/apk/repositories && \
        echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/main >> /etc/apk/repositories && \
        apk add --no-cache \
        chromium@3.10=~73.0.3683.103 \
        nss@3.10 \
        freetype@3.10 \
        freetype@3.10 \
        harfbuzz@3.10 \
        ttf-freefont@3.10

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

COPY package.json ./
RUN npm install

# On installe cross-env seulement en environnement de test
RUN if [ "${NODE_ENV}" = "test" ]; then echo "installing cross-env" && npm install cross-env; fi
 
COPY . .
 
EXPOSE 3000
ENTRYPOINT [ "npm" ]
CMD ["run", "prod"]

```
The part of my which is crashing is the following : 

```js
        this.logger.info("Puppeter launch")
        const browser = await puppeteer.launch(puppeteerParams);
        this.logger.info("Puppeter launched successfully")
        const page = await browser.newPage();
        await page.setContent(html);
        const pdf = await page.pdf({ format: 'A4' });
        this.logger.info("pdf generated")
```

My logs are the following : 

```
2019-09-30T14:18:02.985Z [CORE] [/test] info: Puppeter launch
2019-09-30T14:18:03.133Z [CORE] [/test] info: Puppeter launched successfully
2019-09-30T14:18:03.308Z [CORE] [/test] error: 500 - b6a03eaf11bc4c669433d067418b5165 - Protocol error (IO.read): Invalid parameters handle: string value expected - /test - GET- 127.0.0.1
```

**Comment by semoal** [comment]
https://github.com/GoogleChrome/puppeteer/issues/4637
Some months ago, 1.17.0 was the latest stable with Docker and alpine.
` chromium@3.10=~73.0.3683.103 `
try to leave the version free, `chromium \ ` but keeping fixed on package.json pupetter to 1.17.0

**Comment by santoshvuppala** [comment]
I used the same configuration and got "Generate error: Error Failed to Launch Chrome. I tried using puppeteer version 1.20.0 but got the same error. 
Any other configuration that we have to change ?

**Comment by semoal** [comment]
> I used the same configuration and got "Generate error: Error Failed to Launch Chrome. I tried using puppeteer version 1.20.0 but got the same error.
> Any other configuration that we have to change ?

What i did is avoid using node10:alpine, and using alpine:edge
The main differences are bigger size, and you have to install npm youself.

```
FROM alpine:edge

RUN apk update && apk upgrade && apk add --no-cache \
      chromium \
      tzdata \
      nss \
      freetype \
      harfbuzz \
      ttf-freefont \
      python \ 
      npm
```

**Comment by ouraios** [comment]
Okay i found out what was the problem, in my `package.json` i had the following : 
`"puppeteer": "^1.12.2"` it means that it will be the last 1.x.x version being updated but it will stay `"puppeteer": "^1.12.2"` in the json but will currently instal 1.20.0.

To not have to update at each update when it breaks we fixed our version by doing so : 
* `npm uninstall puppeteer`
* `npm i puppeteer@1.12.2`

And our Dockerfile contain the following : 
**Becareful you'll have to manually update to the latest stable version, periodically**
```
RUN apk update && apk upgrade && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/community >> /etc/apk/repositories && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/main >> /etc/apk/repositories && \
    apk add --no-cache \
      make \
      g++ \
      python \
      harfbuzz@3.10 \
      freetype@3.10 \
      nss@3.10 \
      chromium@3.10=~73.0.3683.103
```

**Comment by santoshvuppala** [comment]
Thank you for the reply, I followed your instructions and installed puppeteer version as said,
 however I get the same "Generate error". Anything I am missing.
===================
FROM node:10-alpine
ARG app_version
LABEL app.version=${app_version}

RUN apk update && apk upgrade && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/community >> /etc/apk/repositories && \
    echo @3.10 http://nl.alpinelinux.org/alpine/v3.10/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@3.10=~73.0.3683.103 \
      nss@3.10 \
      freetype@3.10 \
      harfbuzz@3.10 \
      ttf-freefont@3.10 \
      curl \
      bash

# skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
==================

**Comment by Lucien-X** [comment]
I encountered the same issue , 
while using Aliyun Functional Compute Service, 
which is using **nodejs v10**.

Higher version of puppeteer is incompatable with that.
**So I downgrade my puppeteer-core to v1.16.0** . Works like magic ~ 🎉
