### ISSUE TITLE
Failed to launch chromium in Google Colaboratory

### ISSUE THREAD

**Issue by ggirou** [puppeteer/puppeteer#4991]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@1.20.0
* Platform / OS version: Google Colaboratory
* URLs (if applicable): https://colab.research.google.com/drive/1L_XCfYmynjYSvoPTrVypmEeTt9nJ0deB
* Node.js version: v8.11.3

**What steps will reproduce the problem?**

1. Open https://colab.research.google.com/drive/1L_XCfYmynjYSvoPTrVypmEeTt9nJ0deB
2. Run all blocks

**What is the expected result?**
Chromium should launch and puppeteer scenario should work

**What happens instead?**
(node:174) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
src/tcmalloc.cc:283] Attempt to free invalid pointer 0xa3af288aa20

I filed an issue to Chromium's tracker few months ago, maybe you could troubleshoot :)
https://bugs.chromium.org/p/chromium/issues/detail?id=987241

**Comment by EnisBerk** [comment]
I could make it work by installing chrome separately and telling puppeteer to use that one.

```!apt install chromium-chromedriver```
and change launch to 
```const browser = await puppeteer.launch({executablePath:"/usr/lib/chromium-browser/chromium-browser", args:['--no-sandbox']});```

example colab: https://drive.google.com/open?id=1Sx8CAFuxy4ykHU7NzQcL4ugvmbIzV0tM

I am using same solution with python port (pyppeteer)
```browser = await launch(executablePath="/usr/lib/chromium-browser/chromium-browser",args=['--no-sandbox'])```

**Comment by ggirou** [comment]
@EnisBerk Thanks for the workaround :)

**Comment by mattyweb** [comment]
Worked like a charm! 

But, FYI, I had to put an "!apt-get update" in my notebook to get chromium to install properly. I was getting some ubuntu security warnings before that which had that as a suggestion...

**Comment by urmzd** [comment]
@EnisBerk You wouldn't happen to have a notebook example for [ `pyppetter`](https://pypi.org/project/pyppeteer/), would you?

**Comment by yitelee** [comment]
For some reason I have to use firefox with puppeteer, so the workaround is not acceptable. After hours of exploration, I found the weird thing is, in colab you are a semi-root (file you created is with root privilege), but not actually a root. A simple firefox/chrome binary failed to execute with segfault, but OK if you sudo it. So...

!node test.js
_(node:3021) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f82b591d430 
Redirecting call to abort() to mozalloc_abort_

The solution:
!sudo /tools/node/bin/node test.js
_It worked!!_

https://colab.research.google.com/drive/1m4r2F3y_6iX2PYUxtLtazx-_kMZf4rFh?usp=sharing
