### ISSUE TITLE
ExceptionDetails doesn't handle Objects when doing error reporting

### ISSUE THREAD

**Issue by willrichboa** [puppeteer/puppeteer#4994]
This issue has to do with the handling of ExceptionDetails that uses objects instead of strings.

Example code that would generate an object instead of a string in an exception:
```
await page.evaluate(() => {
    return Promise.reject({foo:"bar"})
  })
```

how does Puppeteer handles this currently?
```
     Error: Evaluation failed: Error: [object Object]
```

What do I expect to happen?
```
     Error: Evaluation failed: Error: {"foo":"bar"}
```

I've tracked this back to one spot:
https://github.com/GoogleChrome/puppeteer/blob/master/lib/helper.js#L50

Just wrap those returned values in JSON.stringify and everything should work as expected.

**Comment by govindrai** [comment]
Any update on this? page#evaluate errors are very esoteric and unhelpful at the moment!
