### ISSUE TITLE
elementHandle.getProperties() returns an empty map - which i think is a bug

### ISSUE THREAD

**Issue by AionDev** [puppeteer/puppeteer#4995]
For the following html..
```
<form class="" action="index.html" method="post">
  <input type="text" name="some name" placeholder="some placeholder" value="">
</form>
```
Im trying to extract the properties like so: 
```
const formHandle = await page.$('form')
const inputs = await formHandle.$$('input')
const properties = await inputs[0].getProperties()
```
The relevant documentation is here: [elementHandle.getProperties()][1]
My `inputs[0]` is indeed an `elementHandle`, since it comes form the formHandle as shwon here: [elementHandle.$()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleselector-1)

But why is the `properties`  map empty then? Given that `html form` is supposed to contain : `name`, `type`, `placeholder` and `value`

If i use `await inputs[0].getProperty("placeholder")` then it works as expected. 

Does this mean that the `elementHandle.getProperties()` function is not actually working?!

  [1]: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlegetproperties

**Comment by jnd0** [comment]
Having the same issue here. 

For example when trying to extract an XPath from information link the following works just fine:

```javascript
        const [xpathResult] =  await this.page.$x(xpath);
   
        const link = await xpathResult.getProperty('href');

        console.log(await link.jsonValue());
```

However when trying to get all the properties:

```javascript
        const [xpathResult] =  await this.page.$x(xpath);

        const link = await xpathResult.getProperties();
    
        console.log(await link.get('href'));
```

Here link returns an empty map `Map(0) {}`and so I can't get the href property. 

I need a way to get all the properties from element handler as an object but I couldn't find any other way to do that other than getProperties

**Comment by tommyyong93** [comment]
Has anyone found any work arounds for this?

**Comment by shtse8** [comment]
I have the same issue. How can I get all properties of element?

**Comment by Fihy** [comment]
Same thing here.
