### ISSUE TITLE
Not a valid selector

### ISSUE THREAD

**Issue by rsc2015** [puppeteer/puppeteer#4998]
### Steps to reproduce

**environment:**

* Puppeteer version: puppeteer-core": 1.19.0
* Platform / OS version: Windows 10/ VERSION 1809/ OS build 17763.737
* URLs (if applicable):
* Node.js version: v10.16.3

**steps to reproduce the problem?**

_Please include code that reproduces the issue._

1. describe("registered user not signed in", () => {
2.     it("can login", async () => {
3.       let aouUrl = 'https://all-of-us-workbench-test.appspot.com/login';
4.       await goto(page, aouUrl);
5.       await signIn(page, userId, userPwd);
6.       let title = await page.title();
7.       expect(title).toMatch("All of Us Researcher Workbench");
8.       await page.screenshot({path:'logs/screenshots/workbench-homepage.png', fullPage: true});
9.       await page.waitFor(1000);
10.      let seeWorkspacesLinkSelectr = "//a[contains(text(), 'See All Workspaces')]";
11.       await page.waitForSelector(seeWorkspacesLinkSelectr);
12.         await page.click(seeWorkspacesLinkSelectr);
13.         console.log('click on link- See All Workspaces');
14.         let title2 = await page.title();
16.         expect(title2).toMatch("View Workspaces | [Test] All of Us Researcher Workbench");
17.         await page.waitFor(5000);
18.       console.log('View Workspaces');
19.       await page.screenshot({path:'logs/screenshots/workspace-list-page.png', fullPage: true});
20.         
21.       });
22. });

**What is the expected result?**
should click on the link(text): See all Workspaces.

**What happens instead?**
Keeps failing:
Evaluation failed: DOMException: Failed to execute 'querySelector' on 'Document': '//a[contains(text(), 'See All Workspaces')]' is not a valid selector.

**Comment by JonathanBristow** [comment]
I think you need to be using `waitForXPath` instead of `waitForSelector` on line 11.

**Comment by rsc2015** [comment]
@JonathanBristow thanks!

**Comment by rsc2015** [comment]
1. let seeWorkspacesLinkSelectr = '//a[normalize-space()="See All Workspaces"]';
2.      const clickSeeAllWorkspaces = await page.waitForXPath(seeWorkspacesLinkSelectr);
3.       await clickSeeAllWorkspaces.click();
4.       console.log('click on link- See All Workspaces');
5.       await page.waitForFunction(() => document.querySelector('title').textContent.includes('View Workspaces | [Test] All of Us Researcher Workbench'), {
6.       polling: 'mutation'
7.       });

This is what worked for me!

**Comment by DaYesahh** [comment]
> 
> 
> I think you need to be using `waitForXPath` instead of `waitForSelector` on line 11.

why?  Is there anything different between them?

**Comment by JonathanBristow** [comment]
@DaYesahh  waitForXPath uses a different type of selector from what I can work out.
