### ISSUE TITLE
headless_shell/headless build configuration

### ISSUE THREAD

**Issue by kobelb** [puppeteer/puppeteer#500]
Currently, puppeteer is running a full build of Chromium that is dynamically linked to X on Linux. Are there any plans to run something similar to the headless_shell or another application built with the headless configuration as referenced [here](https://chromium.googlesource.com/chromium/src/+/lkgr/headless#usage-as-a-c_library) to reduce the dependencies and be more similar to Phantom?

**Comment by pavelfeldman** [comment]
Puppeteer can run against `headless_shell`, I just checked that all the tests are passing against latest locally built shell:
```js
puppeteer.launch({executablePath: 'out/Release/headless_shell'})
```
We like bundling chromium and run it in the `--headless` mode primarily for the debugging ergonomics. Also, --headless on Linux is running the slim embedder, not the full chromium, so it does not compromise runtime performance.

**Comment by Guruhbk** [comment]
@pavelfeldman Hi. I launched browser as you said using headless_shell. But unfortunately i couldn't create a newPage using the browser. When i tried, `const page = await browser.newPage();`, The process stopped right there with no errors. Any suggestions?
