### ISSUE TITLE
Not getting Complete Screenshot. 

### ISSUE THREAD

**Issue by bv-deepak** [puppeteer/puppeteer#5000]
Hi,

While taking the full page screenshot of the website **http://www.supernetwork.it/** , I am getting only background image as a screenshot. Not getting other elements in the screenshot image.

![old](https://user-images.githubusercontent.com/40763742/66120162-ded9a880-e5f7-11e9-9513-de14b8d7d8a9.png)

**Comment by kblok** [comment]
Can you share your code?

**Comment by bv-deepak** [comment]
@kblok 
Hi,
This is the code i am using.

    'use strict'

    const puppeteer = require('puppeteer')
    const pageGotoOptions = {
      waitUntil: 'networkidle0',
      timeout: 40000
    }

    const launchChromeWithNewPage = async () => {
      const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true
      })
      const page = await browser.newPage()
      return {
        browser: browser,
        page: page
      }
    }

    const setViewPort = async (page, options={}) => {
      await page.setViewport({
        width: options.width || 1366,
        height: options.height || 768
      })
      return page
    }

    const captureScreenshot = async (url, path) => {
      let browser, pid, args, page
      try {
        let res = await launchChromeWithNewPage()
        browser = res.browser
        page = res.page
        pid = browser.process().pid
        page = await setViewPort(page)
        const response = await page.goto(url, pageGotoOptions)
        await page.waitFor(3000)
        await page.screenshot({type: 'jpeg', path: path, fullPage: true})
      } catch (err) {
        console.log(['SCREENSHOTERROR'], `SCREENSHOT_ERRORS-${url}-${pid}-${err.message}`)
        throw err
      } finally {
        try {
          await browser.close()
          console.log(['SCREENSHOT'],`BROWSER_CLOSED-${url}-${pid}`)
        } catch (err){
          console.log(['SCREENSHOTERROR'],`BROWSER_CLOSING_ERRORS-${url}-${pid}`)
        }
      }
    }

captureScreenshot("http://www.supernetwork.it", "/var/www/html/new.jpg")

**Comment by bv-deepak** [comment]
Hi @aslushnikov,

Can you please tell me why it is happening? Trying to find a solution for a long time.

**Comment by ajain-bst** [comment]
I am facing the same issue. The width _seems_ to be cut off when the vertical content is too long.

**Comment by bv-deepak** [comment]
@ajain-bst The issue is not with the height. The issue is with the background image and happens because of the CSS property of the background image. In such sites, height of the background image is like 100% or 100vh, so when we render the full page, it tries to cover the whole viewport and all the relative content shifted below. For these sites, you can not take the full page screenshot directly.
