### ISSUE TITLE
Feature Request : Protractor driver using puppeteer Authentication using same Session

### ISSUE THREAD

**Issue by vijaychowthri** [puppeteer/puppeteer#5004]
Am launching chrome using a protractor web-driver,  in selenium address (http://localhost:4444), my remote debugging port (21222) in config file, is there a way to force to use the session in puppeteer for authentication, then same session I could use it for test execution using the protractor?

seleniumAddress: 'http://localhost:4444/wd/hub',

**Config.js capability could be  :**

  capabilities: {
        browserName: 'chrome',
        directConnect: true,
        chromeOptions: {
            'useAutomationExtension' : false,
             'binary': require('puppeteer').executablePath(),
             'excludeSwitches': ['enable-automation'],
          args: [  '--incognito',  '--remote-debugging-port=21222' ],
        }
    },

**spec.js:** 

it('STEP#1 , Validate title', async function () {
let browser = await puppeteer.connect({
    headless: true,
    browserWSEndpoint: 'ws://localhost:21222' ,
    });

const page = await browser.newPage();  ---< newtab ??  instad of page ?? >
await page.authenticate({ username: user, password: password });  
await page.setExtraHTTPHeaders({
        'Accept-Language': 'en-US,en;q=0.9',
        headless: 'true',
    });
    
await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36');
    await page.goto("https://www.myapplication.org/info", {
      waitUntil: 'networkidle0'
     });      

 })
<here my protractor test follows authentication >

it('STEP#2 , Validate title', async function () {
browser.driver.get('https://www.myapplication.org/info');
var foo = element(by.css('text-input#prodLine div p'));
await expect(foo.getText()).toEqual('Inner text');
browser.sleep(10000);
 })

using same instance, i should able to execute rest of my test steps using a protractor.

**Comment by vijaychowthri** [comment]
resolved

**Comment by FranciscoKnebel** [comment]
> resolved

I'm trying to use protractor and puppeteer. Could you be more specific with "resolved"?

**Comment by vijaychowthri** [comment]
@FranciscoKnebel 

your config.js

   seleniumAddress: 'http://localhost:4446/wd/hub',
   
   capabilities: 
    {
        browserName : 'chrome',
        //directConnect : true,
        chromeOptions: {
            'useAutomationExtension' : true,
            'binary': require('puppeteer').executablePath(),
            'excludeSwitches': ['enable-automation'],
        prefs: {
                'credentials_enable_service': true,
            },  
          args: [
            '--headless:false',
            '--remote-debugging-port=21222',    
            '--start-maximized',
        ],

        }
    },
---------------------puppeteer code------------
this.pupLogin = async function (user, password, pageurl) {
        
        return puppeteer.launch(
              
              {  
                  headless: false, 
                  ignoreHTTPSErrors: true ,
                  browserWSEndpoint: 'http://localhost:21222/json' ,
                  devtools: false,
                  args: ['--incognito', `--ignore-certificate-errors`],
                  
              } ,
          ).then(async browser => {
              try {
                
  
                /*Main Page - Azure Logic  */
                const browserURL = 'http://localhost:21222';
                const browser = await puppeteer.connect({browserURL});
                var page = await browser.newPage();

                await page.authenticate({ username: user, password: encrypt.decrypt(password,process.env.UN01SK,256) });
                await page.setExtraHTTPHeaders({
                    'Accept-Language': 'en-US,en;q=0.9'
                });
                await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3359.181 Safari/537.36');
                await page.goto(pageurl);
                page.waitForNavigation({ 'waitUntil': 'networkidle2' });
                await page.waitFor(4500);
                
                await page.type("input[id=i0116]", user, {
                    delay: 50
                });
    
                var pagetitle = await page.title();
                await console.log("Page click before NEXT - "+pagetitle);
                let selector = 'input[id=idSIButton9]';

**Comment by 007-JB** [comment]
All that from 'resolved' ?

**Comment by vijaychowthri** [comment]
resolved
