### ISSUE TITLE
How to get the name of the downloaded file from popup ?

### ISSUE THREAD

**Issue by andrgn** [puppeteer/puppeteer#5006]
I want to implement the following scenario:

- Click on the file download button > get a native browser download popup with filename, path, etc.

- Take the filename from the popup and do some checks (don't need to download the file, this is an excess step, only need the filename)

How to get file name from popup ? Or is there another way to do this ?

**Comment by andreabisello** [comment]
@AndreyPermyakov have you tried with https://pptr.dev/#?product=Puppeteer&version=v1.20.0&show=api-class-filechooser ? normally this will used to upload contents, but maybe with this code

```
const [fileChooser] = await Promise.all([
  page.waitForFileChooser(),
  page.click('#upload-file-button'), // some button that triggers file selection
]);
```
you can debug the fileChooser constant and see if there are the file name you are searching for ...

**Comment by edelauna** [comment]
You could watch for a response after clicking the download button and try to parse the filename from the headers - something like:

    page.on('response', response => {
      //check for "Content-Disposition"
      const disposition = response.headers()['content-disposition'];

      if (disposition && disposition.indexOf('attachment') !== -1) {
        var filenameRegex = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/;
        var matches = filenameRegex.exec(disposition);
        if (matches != null && matches[1]) { 
          filename = matches[1].replace(/['"]/g, '');
        }
      }
    });

**Comment by alexander-schreiner-seobility** [comment]
> You could watch for a response after clicking the download button and try to parse the filename from the headers - something like:
> 
> ```
> page.on('response', response => {
>   //check for "Content-Disposition"
>   const disposition = response.headers()['content-disposition'];
> 
>   if (disposition && disposition.indexOf('attachment') !== -1) {
>     var filenameRegex = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/;
>     var matches = filenameRegex.exec(disposition);
>     if (matches != null && matches[1]) { 
>       filename = matches[1].replace(/['"]/g, '');
>     }
>   }
> });
> ```

@edelauna On some resources no `content-disposition` header is present, but a file download dialog is triggered: https://httpbin.org/drip
