### ISSUE TITLE
Uncaught (in promise) ReferenceError: Cannot access 'puppeteer' before initialization

### ISSUE THREAD

**Issue by MathiasEllegaardRitter** [puppeteer/puppeteer#5013]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: Windows 10
* Node.js version: 12.11.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
const puppeteer = require('puppeteer'); // This is where it says the mistake is
var BASE_URL = '';
<script src="ClipGetter.js" type="text/javascript"></script> 
        <script>
            BASE_URL = gamerBros[0].url;
            console.log(BASE_URL)
            getClipUrls()

**What is the expected result?**
I expect an url in the console.log

**What happens instead?**
i get this error Uncaught (in promise) ReferenceError: Cannot access 'puppeteer' before initialization

I'm buliding my first javascript, app, so sorry if i'm not clear, or this is an easy answer.

i could not find anything on stackoverflow 
![image](https://user-images.githubusercontent.com/39926815/66298454-172c0000-e8f2-11e9-8c4b-3e4bf7288a12.png)

**Comment by Alencastro** [comment]
found the solution? I also have this problem

**Comment by SharpRhyme** [comment]
I have the same problem. Any solutions?

**Comment by SharpRhyme** [comment]
never mind, I am doing javascript after a while and forgot to put quotation around puppeteer
