### ISSUE TITLE
Support MacOS Catalina

### ISSUE THREAD

**Issue by swftvsn** [puppeteer/puppeteer#5020]
Try to run in latest Catalina. Chromium won't even open. The problem is fixed simply by updating chromium version. I tried to run with 699988 and it works correctly.

**Comment by icodeforlove** [comment]
Thanks!

I edited the `node_modules/puppeteer/package.json`, and set the following

```
  "puppeteer": {
    "chromium_revision": "699988"
  },
```

Then ran an `npm install` and everything worked fine.

**Comment by qihangnet** [comment]
when will we release this version?

**Comment by sameersemna** [comment]
> Thanks!
> 
> I edited the `node_modules/puppeteer/package.json`, and set the following
> 
> ```
>   "puppeteer": {
>     "chromium_revision": "699988"
>   },
> ```
> 
> Then ran an `npm install` and everything worked fine.

Required me to run:
`PUPPETEER_CHROMIUM_REVISION=699988 npm install`

**Comment by mathiasbynens** [comment]
This will be fixed with the next Chromium roll. Hang in there!

**Comment by icodeforlove** [comment]
@sameersemna much better solution :), i had no idea about that ENV var.

**Comment by dziamid** [comment]
Upgrading to puppeteer 2.0 fixed my issues on Catalina
