### ISSUE TITLE
FreeBSD is not supported

### ISSUE THREAD

**Issue by ip75** [puppeteer/puppeteer#5034]
v1.20.0
puppeteer/lib/BrowserFetcher.js:
...

```

class BrowserFetcher {
  /**
   * @param {string} projectRoot
   * @param {!BrowserFetcher.Options=} options
   */
  constructor(projectRoot, options = {}) {
    this._downloadsFolder = options.path || path.join(projectRoot, '.local-chromium');
    this._downloadHost = options.host || DEFAULT_DOWNLOAD_HOST;
    this._platform = options.platform || '';
    if (!this._platform) {
      const platform = os.platform();
      if (platform === 'darwin')
        this._platform = 'mac';
      else if (platform === 'linux')
        this._platform = 'linux';
      else if (platform === 'win32')
        this._platform = os.arch() === 'x64' ? 'win64' : 'win32';
      assert(this._platform, 'Unsupported platform: ' + os.platform());
    }
    assert(supportedPlatforms.includes(this._platform), 'Unsupported platform: ' + this._platform);
  }


```
freebsd is not supported

**Comment by tarkhil** [comment]
puppeteer is dependent on headless chromium which is not available for FreeBSD, so it won't work anyway. 

Well, you can try to install headless browsers in linux emulator than patch BrowserFetcher, I will try it as soon as I'll have time.

Don't expect headless chromium ported to FreeBSD soon, all resources are distracted to more pressing issues - renaming master to main, Code of Conduct, inclusive naming and all that Extremely  Urgent And Important Stuff.

**Comment by ip75** [comment]
Chromium exists in standard ports collection of FreeBSD.
/usr/ports/www/chromium/

[ /usr/ports/www/chromium ] # cat pkg-descr
Chromium is an open-source browser project that aims to build a safer,
faster, and more stable way for all users to experience the web.

The Chromium website contains design documents, architecture overviews,
testing information, and more to help you learn to build and work with
the Chromium source code.

`--headless `
headless mode available since 2017

**Comment by tarkhil** [comment]
As far as I've checked (right now), headless build is not supported.

root@over:/usr/ports/www/chromium # grep -i headless *
Makefile.tests:         headless_unittests \
pkg-plist:%%DATADIR%%/headless_lib.pak
pkg-plist:%%DATADIR%%/resources/inspector/cm_headless/cm_headless.js

It only builds with everything on board ((

And my attempt to build headless remotely controlled firefox resulted in 
X-required uncontrollable one. I'd love to have spare time to 
investigate it more...

**Comment by drook** [comment]
Do you confuse headless build with headless launch on purpose ? Headless build means the chrome will be built without X11 support so you can run it only in headless mode. The standard build means you can run chrome in either way - with X11 or in headless mode. Furthermore, when building something with X11 this doesn't mean you even need running X11 to build it. 

In the end, you just need to install chromium from ports and slightly patch the install routine. No big deal.

**Comment by wohali** [comment]
With the attached diff (against `10.4.0`) I'm able to run puppeteer just fine (in my case, as a Grafana image renderer) on FreeBSD. It's running headless. Note that this 'pacifies' `BrowserFetcher.ts` because I am not sure how to pass the env var correctly using `yarn`, which the grafana image renderer uses instead of `npm`.

@jschfflr is this a PR you would consider accepting? If so I'll put one up. Cheers!

```diff
diff --git a/src/node/BrowserFetcher.ts b/src/node/BrowserFetcher.ts
index d5f25708..0407a5d5 100644
--- a/src/node/BrowserFetcher.ts
+++ b/src/node/BrowserFetcher.ts
@@ -43,6 +43,7 @@ const downloadURLs = {
     mac: '%s/chromium-browser-snapshots/Mac/%d/%s.zip',
     win32: '%s/chromium-browser-snapshots/Win/%d/%s.zip',
     win64: '%s/chromium-browser-snapshots/Win_x64/%d/%s.zip',
+    freebsd: '%s/dummy/%d/%s.zip',
   },
   firefox: {
     linux: '%s/firefox-%s.en-US.%s-x86_64.tar.bz2',
@@ -67,7 +68,7 @@ const browserConfig = {
  * Supported platforms.
  * @public
  */
-export type Platform = 'linux' | 'mac' | 'win32' | 'win64';
+export type Platform = 'linux' | 'mac' | 'win32' | 'win64' | 'freebsd';

 function archiveName(
   product: Product,
@@ -216,6 +217,7 @@ export class BrowserFetcher {
     const platform = os.platform();
     if (platform === 'darwin') this._platform = 'mac';
     else if (platform === 'linux') this._platform = 'linux';
+    else if (platform === 'freebsd') this._platform = 'freebsd';
     else if (platform === 'win32')
       this._platform = os.arch() === 'x64' ? 'win64' : 'win32';
     else assert(this._platform, 'Unsupported platform: ' + platform);
@@ -368,6 +370,8 @@ export class BrowserFetcher {
           archiveName(this._product, this._platform, revision),
           'chrome'
         );
+      else if (this._platform === 'freebsd')
+        executablePath = path.join('usr', 'local', 'bin', 'chrome');
       else if (this._platform === 'win32' || this._platform === 'win64')
         executablePath = path.join(
           folderPath,
diff --git a/src/node/Launcher.ts b/src/node/Launcher.ts
index 402ae0ad..283ad8cc 100644
--- a/src/node/Launcher.ts
+++ b/src/node/Launcher.ts
@@ -122,6 +122,9 @@ class ChromeLauncher implements ProductLauncher {
       // Chromium builds are available.
       if (os.platform() !== 'darwin' && os.arch() === 'arm64') {
         chromeExecutable = '/usr/bin/chromium-browser';
+      // Use ports tree chromium for FreeBSD.
+      } else if (os.platform() === 'freebsd') {
+        chromeExecutable = '/usr/local/bin/chromium';
       } else {
         const { missingText, executablePath } = resolveExecutablePath(this);
         if (missingText) throw new Error(missingText);
```

**Comment by drook** [comment]
As per my observations, chromium merely needs to be in PATH.
Plus this:

````
export PUPPETEER_SKIP_DOWNLOAD=yes 
````

All the fuss is really about the inability to fetch the binary, which isn't actually needed and can/should be obtained properly. Yeah, a slight patch for the platform support is still needed though.

**Comment by yaazkal** [comment]
> @jschfflr is this a PR you would consider accepting? If so I'll put one up. Cheers!

Nice if it lands as a PR and gets accepted, thanks @wohali

**Comment by dsh2dsh** [comment]
Hi!

Any news here?

**Comment by wohali** [comment]
@ip75 Any chance to look at this to help support https://github.com/grafana/grafana-image-renderer/issues/192 ? Thanks.

**Comment by OrKoN** [comment]
Hey, sorry but we are not going to support freebsd as there are no binaries published for it. For now you can use the PUPPETEER_SKIP_DOWNLOAD and executablePath parameters to run it there.
