### ISSUE TITLE
Sourcemaps for testing chrome extensions

### ISSUE THREAD

**Issue by avalanche1** [puppeteer/puppeteer#5035]
I'm building a chrome extension that operates on third-party pages' dom. Hence I've got content-scripts, that are loaded on each page.
My content-scripts are transpiled from typescript and have source-maps.
I use Puppeteer to drive testing in non-headless mode.
When I debug my content-scripts' code - there are no source maps, although chromium devtools say they are available.
Is this by design?

**Comment by stevenvachon** [comment]
#3570

**Comment by avalanche1** [comment]
Yep, but that issue looks abandoned. Maybe they'll notice the new one (this).

**Comment by ejames17** [comment]
my guess this is abandoned?

**Comment by avalanche1** [comment]
By the sheer amount of open issues - it looks like the whole project has gotten abandoned.
