### ISSUE TITLE
Dark mode support?

### ISSUE THREAD

**Issue by avalanche1** [puppeteer/puppeteer#5036]
Is there a way to run non-headless chromium in dark mode, without setting os to dark mode?

**Comment by mathiasbynens** [comment]
#5012

**Comment by avalanche1** [comment]
@mathiasbynens I don't see how this helps. Can you elaborate?
Namely, I would like Devtools panel to be dark w\o manually setting it on each run.

**Comment by sbrunner** [comment]
@avalanche1 see: https://pptr.dev/api/puppeteer.page.emulatemediafeatures

**Comment by DonnyVerduijn** [comment]
@avalanche1 you can configure devtools using puppeteer-extra-plugin-user-preferences. `puppeteer.use(
    preferences({
      userPrefs: {
        devtools: {
          preferences: {
            currentDockState: '"bottom"',
            'panel-selected-tab': '"console"',
            'ui-theme': '"dark"',
          }
       }}}))`
