### ISSUE TITLE
Cookie header not set

### ISSUE THREAD

**Issue by robertsLando** [puppeteer/puppeteer#5039]
### Steps to reproduce

* Puppeteer version: 1.20.0
* Platform / OS version: Ubuntu 18.04
* Node.js version: 8.15 LTS

**What steps will reproduce the problem?**

```js
async function makeReport(report) {
  try {

    var tmpDir ='./.tmp'

    const browser = await puppeteer.launch({ headless: false, ignoreHTTPSErrors: true, userDataDir: tmpDir }) 
    const page = await browser.newPage();

    await page.setRequestInterception(true);

    page.on('request', interceptedRequest => {
      if (interceptedRequest.url().indexOf("/tag/?") >= 0){
        // cookie header with session id is missing here and the session authentication fails
        console.log(interceptedRequest.headers());
        debugger
      }
    });

    await page.goto('https://localhost:' + port + '/report/' + report.id, { waitUntil: 'networkidle0' });

    // Page console log
    page.on('console', msg => {
      for (let i = 0; i < msg.args().length; ++i)
        console.log(`${i}: ${msg.args()[i]}`);
    });
    
    await page.waitFor(5000)

    await page.emulateMedia('screen');
    await page.pdf({ path: tmpDir + '/report' + report.id + '.pdf', format: 'A4' });

    await browser.close();

  } catch (error) {
    logger.error("Error while doing report", error.message)
  }
}
```

**What is the expected result?**

The request to have the cookie correctly set as follow:

![puppeteer1](https://user-images.githubusercontent.com/11502495/66809470-b160f900-ef2d-11e9-81da-0afc28a8f75e.png)

**What happens instead?**

The cookie header is not present on the request and this make the request fail. This are the headers sent when using pappeteer:

![Schermata da 2019-10-15 09-26-42](https://user-images.githubusercontent.com/11502495/66809619-03098380-ef2e-11e9-9c46-87632237d783.png)

**Comment by ritz078** [comment]
@robertsLando Can you please tell me how you solved this?

**Comment by robertsLando** [comment]
I'm sorry but I don't remember what fixed the problem, I can show you how I start puppeteer now (and it's working):

```js
const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox'],
      ignoreHTTPSErrors: true,
      userDataDir: tmpDir,
      executablePath: execPath
    })
```

**Comment by namanisupriya55** [comment]
@ritz078 Did you find any solution for this?

**Comment by ritz078** [comment]
@namanisupriya55 I fixed it using this hack https://github.com/puppeteer/puppeteer/issues/4918#issuecomment-663478790
