### ISSUE TITLE
Multiple examples on https://try-puppeteer.appspot.com/ no longer work

### ISSUE THREAD

**Issue by selckin** [puppeteer/puppeteer#5040]
- 'screenshot-fullpage.js' => 'ReferenceError: require is not defined'
- proxy.js => SyntaxError: Unexpected token }
- search.js => Error: No node found for selector: #searchbox input

**Comment by kblok** [comment]
Maybe you should report that here https://github.com/ebidel/try-puppeteer ?

**Comment by selckin** [comment]
Maybe not really familiar with this project, the link was in the readme of this project, and the scripts are in the examples/ directory of this repo

**Comment by selckin** [comment]
https://github.com/ebidel/try-puppeteer/issues/3
