### ISSUE TITLE
Node process not releasing the memory result of that getting OOM issues

### ISSUE THREAD

**Issue by ramakrishnagn** [puppeteer/puppeteer#5041]
Hi All,
We are using the following script to process the angular code and serve the response to crawlers, but when the script executed for few minutes node process consuming more memory and not at all releasing the memory. We have 8 GB RAM still the node process is consuming most of the memory and not at all releasing it result of that getting out of memory issues. Could you please help us whether the following code has any issue that might causing the OOM issues.

Thanks in advance!

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.19.0",
* Platform / OS version: CentOs
* URLs (if applicable):
* Node.js version: v10.16.3

**What steps will reproduce the problem?**
Executing the script for 15 minutes for different urls.
Running the node with the following command

sudo node  --max-old-space-size=6144 app.js &

_Please include code that reproduces the issue._

const block_ressources = ['image', 'stylesheet', 'media', 'font', 'texttrack', 'object', 'beacon', 'csp_report', 'imageset'];

async function bootstrap() {
    const browser = await puppeteer.launch({
        headless: true,
        handleSIGINT: false,
        handleSIGTERM: false,
        handleSIGHUP: false,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        userDataDir: '/tmp'
    });
    browserWSEndpoint = await browser.wsEndpoint();

}

bootstrap();
app.use(async (req, res) => {
    try {
        let url = req.url.split('url=')[1];
        const useragent = req.get('User-Agent');

           if (!browserWSEndpoint) {
                const browser = await puppeteer.launch({
                    headless: true,
                    handleSIGINT: false,
                    handleSIGTERM: false,
                    handleSIGHUP: false,
                    args: ['--no-sandbox', '--disable-setuid-sandbox']
                });
                browserWSEndpoint = await browser.wsEndpoint();

            }

            const browser = await puppeteer.connect({
                browserWSEndpoint
            });
            const page = await browser.newPage();

            try {

                await page.setRequestInterception(true);
                page.on('request', request => {
                    const requestUrl = request._url.split('?')[0].split('#')[0];
                    if (
                        block_ressources.indexOf(request.resourceType) > 0
                        ||
                        request._url.includes('.jpg') ||
                        request._url.includes('.jpeg') ||
                        request._url.includes('.png') ||
                        request._url.includes('.gif') ||
                        request._url.includes('.css') 

                    ) {
                        request.abort();
                    } else {

                        request.continue();
                    }
                });

               const response = await page.goto(url, {
                    waitUntil: 'load',
                    timeout: 0
                });
                const headers = response.headers();
                const status = headers['status'];
                if (status) {
                    res.status(status);
                }

                content = await page.content();
            } catch (e) {
                logger.info("ERROR WHILE PROCESSING PAGE DETAILS :" + e.message);
                res.send("ERROR");

            } finally {
                if (page) {
                    await page.close();
                }

            }
        } 

        res.send(content);
    } catch (e) {
        logger.info("ERROR DETAILS :" + e.message);
        res.send("ERROR");
    }
});

**What is the expected result?**

Memory usage should be consitent.
**What happens instead?**
Node consuming most of the memory and resulting with OOM.

**Comment by sejoker** [comment]
Are you running Puppeteer in Docker? If yes, it's a known issue: https://github.com/puppeteer/puppeteer/issues/615#issuecomment-330355210
