### ISSUE TITLE
Does Puppeteer support browser dialogs 

### ISSUE THREAD

**Issue by daminebenz** [puppeteer/puppeteer#5044]
Hi puppeteer users !

is there anyway to interact with the browser dialogs like this one in the picture below ??
![image](https://user-images.githubusercontent.com/33185490/66865597-ebea8600-ef6d-11e9-81c6-c217b10aad1e.png)

**Comment by kblok** [comment]
Isn't this related to this conversation #4238?

**Comment by daminebenz** [comment]
thanks for replying @kblok 
nope, it doesn't have anything to do with that case !
