### ISSUE TITLE
chromium always showing "about:blank" if launch options in jest-puppeteer.config.js

### ISSUE THREAD

**Issue by andreabisello** [puppeteer/puppeteer#5046]
* Puppeteer version: 1.20
* Platform / OS version: Windows 10 updated
* Node.js version: 10.16.3

i write a test : puppeteer will opens puppeteer website waiting for the selector #puppeteer present on page. 

it works, but there is a strange behaviour : in some case, chromium keep "about:blank" even the test is going on.

i think it is related to the options object for puppeteer.launch.

my project has a jest.puppeteer.config.js file in the root of the project containing

```
module.exports = {
    launch: {
		headless: false,
		defaultViewport: {width: 1366, height: 768},
		args: ["--start-maximized"],
		devtools: false
	},
	browserContext: "default" //potrebbe anche essere incognito
};
```
and it works,
because of running "jest" from the homepage of the test, changing from headless false to headless true, i obtain the correct behaviour.

this is the puppeteerHomepage.test.js

```

describe('puppeteer homepage', () => {

    let browser
    let page

    beforeAll(async () => {
        browser = await puppeteer.launch()
        page = await browser.newPage()
    })
/*
    afterAll(async () => {
        await browser.close()
    })
*/
    test("open puppeteer website and wait for puppeteer element", async () => {
        await page.goto("https://developers.google.com/web/tools/puppeteer", { waitUntil: 'networkidle0' })
        await page.waitForSelector("#puppeteer", { visible: true })
    })
}

```

i deactivated the browser.close for show the strange behaviour.

the test works, but , even the browser was closed by something, the chromium was opened with "about:blank" and i see nothing."

![image](https://user-images.githubusercontent.com/2149815/66910023-19870c00-f00e-11e9-871b-508f89b4a3a5.png)

now,

the same text,

i put the same options object in the puppeteer launch,

and i obtain the correct behaviour : 

i see what puppeter is making,

![image](https://user-images.githubusercontent.com/2149815/66910454-e2fdc100-f00e-11e9-8411-8c8e7eb6604f.png)

can someone help me understand what is going wrong?

other configuration files are

jest.config.js

```
module.exports = {
	preset: "jest-puppeteer",
    setupFilesAfterEnv: [  // NOT setupFiles
        "./custom-configuration.js"
    ],
	"reporters": [
		"default",
		["./node_modules/jest-html-reporter", {
			"pageTitle": "Test Report",
			"includeFailureMsg": true,
			"includeConsoleLog": true			
		}]
	]
};
```

custom-configuration.js

```
const { toMatchImageSnapshot } = require('jest-image-snapshot');
expect.extend({ toMatchImageSnapshot });
jest.setTimeout(10000)
```

this is the file positions

![image](https://user-images.githubusercontent.com/2149815/66910745-720ad900-f00f-11e9-8e2c-e52d0637cf8a.png)

problems are

* using jest-puppeteer.config.js , even if in the test i remove the browser.close afterAll, something is closing the browser
* using jest-puppeteer.config.js , browser still showing "about:blank"
* without using jest-puppeteer.config.js , i obtain 2 instances of chromium, one still blank, other show the test.

can someone help me please? i think there is something wrong with configuration files.

thanks.

**Comment by quafoo** [comment]
I encountered the same problem, finally I found the reason. Every time when you launch the browser, you create a new page instead of using the default page that created by the browser. Please try the snippets blow:
```
beforeAll(async () => {
    browser = await puppeteer.launch()
    // page = await browser.newPage()
    const pages = await browser.pages();
    const page = pages[0];
})
```

**Comment by leiDnedyA** [comment]
Is this a bug in puppeteer, or normal behavior? 3 years later, I'm getting the same problem.
