### ISSUE TITLE
Chromium download always stuck at 99%

### ISSUE THREAD

**Issue by binarykitchen** [puppeteer/puppeteer#5048]
```
.../node_modules/puppeteer ❯❯❯ npm install
> puppeteer@1.20.0 install .../node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [====================] 99% 0.0s
```

Always stuck. On latest yarn or npm. Removed cache and all lock files, still no difference.

**Comment by benjamingr** [comment]
@binarykitchen are you on windows by any chance? I've seen this happen because of eager firewalls in the past

**Comment by binarykitchen** [comment]
No, on MacOS here. Firewall issue? Then it shouldn't block at 99%, but rather at the beginning of the download.

I'd double check code in `install.js` for robustness, error handling, timeouts and so on.

**Comment by rndm2** [comment]
Same issue.
Did you resolve it?

**Comment by binarykitchen** [comment]
Still having the same issue :(

**Comment by ArunJRK** [comment]
Try installing it as tarball file

**Comment by ctjlewis** [comment]
Left a `yarn install` running only to find that the Puppeteer install script had been running for 12 hrs without gracefully failing. Have tried `yarn cache clean` to no avail.
