### ISSUE TITLE
Asking for help,How to solve the table pagination in PDF？

### ISSUE THREAD

**Issue by insist-git** [puppeteer/puppeteer#5050]
![image](https://user-images.githubusercontent.com/19404596/67007287-a23e9e80-f119-11e9-8307-b04ddf21daf9.png)

**Comment by kblok** [comment]
I think this is not related to Puppeteer. Is more how you build the HTML so it can be print-friendly.

**Comment by insist-git** [comment]
I think this is not related to Puppeteer. Is more how you build the HTML so it can be print-friendly.

_Originally posted by @kblok in https://github.com/GoogleChrome/puppeteer/issues/5050#issuecomment-543189892_

Thank you very much for your reply!
I used it to generate PDF for the first time. I don't know how to deal with HTML yet. I can't afford to add CSS. I hope you can give me some advice.
@page {
    table tr {
       word-break: break-all;
       page-break-before: always;
       page-break-after: always;
       page-break-inside: avoid;
     }
  }
