### ISSUE TITLE
I think this is not related to Puppeteer. Is more how you build the HTML so it can be print-friendly.

### ISSUE THREAD

**Issue by insist-git** [puppeteer/puppeteer#5051]
I think this is not related to Puppeteer. Is more how you build the HTML so it can be print-friendly.

_Originally posted by @kblok in https://github.com/GoogleChrome/puppeteer/issues/5050#issuecomment-543189892_

Thank you very much for your reply!
I used it to generate PDF for the first time. I don't know how to deal with HTML yet. I can't afford to add CSS. I hope you can give me some advice.
@page {
    table tr {
       word-break: break-all;
       page-break-before: always;
       page-break-after: always;
       page-break-inside: avoid;
     }
  }

**Comment by insist-git** [comment]
![image](https://user-images.githubusercontent.com/19404596/67059671-93450400-f18c-11e9-9b92-b0e33d3842c8.png)
 How to solve the problem of table Pagination？

**Comment by insist-git** [comment]
![image](https://user-images.githubusercontent.com/19404596/67059714-ba9bd100-f18c-11e9-8a54-c9520821c40c.png)

How to solve the problem of table Pagination？

**Comment by insist-git** [comment]
![image](https://user-images.githubusercontent.com/19404596/67059784-f20a7d80-f18c-11e9-81c6-6db49dc0be4e.png)

**Comment by insist-git** [comment]
How to solve the problem of table Pagination？

**Comment by benjamingr** [comment]
This is unrelated to puppeteer and will happen regardless of automation.
