### ISSUE TITLE
How to allow `<all_urls>` optional permission

### ISSUE THREAD

**Issue by Manvel** [puppeteer/puppeteer#5054]
I'm having trouble testing additional permission request of my extension.

The following is set as optional permission in the `manifest.json` file:
```
"optional_permissions": ["<all_urls>"],
```

And in the extension I do request and revoke the permission using:
```
chrome.permissions.request({"origins": ["<all_urls>"]}) // Request
chrome.permissions.remove({"origins": ["<all_urls>"]}); // Revoke
```

I would like to be able to test the extension behavior when permission is successfully requested and revoked, but there seem to be no way to fetch permission `dialog` event and accept, also it doesn't seem to be possible to do using `browserContext.overridePermissions `.

Any idea how that can be done?

**Comment by agomez0207** [comment]
Hello, we had a similar problem, there is no way to fetch permission dialog event and accept because that dialog is not triggered by any JS on the page, is triggered by Chrome API

`chrome.permissions.request`

We used [this ](https://www.npmjs.com/package/node-key-sender) library for nodejs in order to simulate tab and enter keys for allow/disallow the permission.

**Comment by guanbinrui** [comment]
> Hello, we had a similar problem, there is no way to fetch permission dialog event and accept because that dialog is not triggered by any JS on the page, is triggered by Chrome API
> 
> `chrome.permissions.request`
> 
> We used [this ](https://www.npmjs.com/package/node-key-sender) library for nodejs in order to simulate tab and enter keys for allow/disallow the permission.

@agomez0207 The permission dialog looks cannot approve by the keyboard.

**Comment by dbjpanda** [comment]
Any update here?

**Comment by smashedr** [comment]
Was this resolve? I can't find the documentation on this...
