### ISSUE TITLE
High severity vulnerability warning for https-proxy-agent dependency

### ISSUE THREAD

**Issue by onderceylan** [puppeteer/puppeteer#5055]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: macOS Mojave 10.14.5
* URLs (if applicable):
* Node.js version: 11.9.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. npm install puppeteer@latest

**What is the expected result?**
Puppeteer should use https-proxy-agent > v3 which fixes the reported vulnerability.

**What happens instead?**
npm warns for **high severity vulnerability** for the puppeteer dependency https-proxy-agent package - https://www.npmjs.com/advisories/1184.  

![image](https://user-images.githubusercontent.com/2641384/67151785-0bb1df00-f2cb-11e9-95f0-bfe3b8dc25a5.png)

**Comment by abrom** [comment]
It appears that this was already fixed last week in #5016, just awaiting a release.

Temporary solution (if you're willing to go bleeding edge) would be to specify the commit hash:

```
"puppeteer": "git+ssh://git@github.com/GoogleChrome/puppeteer.git#5b34028e63c9532349ac525fa4c14daeada05b94"
```

Only functional change since the 1.20.0 release appears to have been the `https-proxy-agent` bump

HTH

**Comment by warpech** [comment]
Thank you @abrom for a viable workaround.

Here's a version that uses HTTP to obtain a tarball (instead of SSH to obtain a Git clone):

```
"puppeteer": "https://api.github.com/repos/GoogleChrome/puppeteer/tarball/5b34028e63c9532349ac525fa4c14daeada05b94",
```

**Comment by onderceylan** [comment]
Fixed with v2 release
