### ISSUE TITLE
Error: Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by rhlr** [puppeteer/puppeteer#5056]
I'm trying to scrape some websites. The navigation is as follows:

1. Open the start page.
3. Click on each url one by one, log relevant information.
4. Go to next page, repeat the step 2.
5. Close the browser when no further next button is available.

The problem is after when I click on the first url from the listings and log some info, it stops it's execution by throwing the error `Error: Execution context was destroyed, most likely because of a navigation.` 

Is it possible to keep a deep clone of the previous page and use it somehow to click on the next url ? Or is there any other way I can acheive this navigation ?

Here's my code:

`index.js`

    const hatla2ee = require('./hatla2ee');

    (async () => {
    await hatla2ee.initialize();

    let results = await hatla2ee.getListings();
    debugger;   
    })(); 

`hatla2ee.js`

    const puppeteer = require("puppeteer");
    const chalk = require("chalk");
    var fs = require("fs");

    const error = chalk.bold.red;
    const success = chalk.keyword("green");

    const start_url = "https://eg.hatla2ee.com/en/car"

    const self = {
      browser: null,
      page: null,

      initialize: async () => {
        self.browser = await puppeteer.launch({ headless: false });
        self.page = await self.browser.newPage();
        self.pageNew = await self.browser.newPage();
        await self.page.setViewport({ width: 1440, height: 768 });

        await self.page.goto(start_url, { waitUntil: 'networkidle0' });
       },

     getListings: async () => {
        let results = [];
        
        do {
                let new_results = await self.getUrls();

                results = [results, ...new_results]
                console.log(results);
                let nextButton = await self.page.$x(`//div[@class='pagination pagination-right']/ul/li`);
                let nextPage = await nextButton[nextButton.length-1];
                let buttonText = (await(await nextPage.getProperty(`innerText`)).jsonValue());
                console.log(success(buttonText))
                if (buttonText.includes(`Next`)){
                    await nextPage.click();
                    await self.page.waitForNavigation({ waitUntil: 'networkidle0' });
                }else{
                    break;
                }
            }while (true);
            
            return results;
    },

    getUrls: async () => {
        let urls = await self.page.$x(`//a[@class='NewListTitle']`);

        let results = [];

        for (let url of urls) {
            url.click()
            await self.page.waitForNavigation({ waitUntil: 'networkidle0' });
            /*let href = await (await url.getProperty(`href`)).jsonValue()
            results.push(href)
            console.log(href)
            await self.page.goto(href, { waitUntil: 'networkidle0' });
            await self.page.waitForNavigation({ waitUntil: 'networkidle0' });
            */
            
        }

        return results;

      }
    }

    module.exports = self;

**Comment by celynjacobs** [comment]
I was having exactly the same issue. In my case, it was because I clicked a button before scraping in order to refresh the data. I didn't realized that when I clicked the button, it immediately navigated to a different home page that interrupted my scraping.
