### ISSUE TITLE
What is wrong with page.pdf() in Puppeteer?

### ISSUE THREAD

**Issue by pengyu** [puppeteer/puppeteer#5059]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 6.10.3
* Platform / OS version: Mac OS X 10.14.1
* Node.js version: v12.4.0

**What steps will reproduce the problem?**

https://github.com/GoogleChrome/puppeteer/blob/master/README.md

I am trying the following example from the above page.

```
#!/usr/bin/env node
// vim: set noexpandtab tabstop=2:

const puppeteer = require('puppeteer');

(async () => {
	//	const browser = await puppeteer.launch();
	const browser = await puppeteer.launch({headless: false});
	const page = await browser.newPage();
	await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle2'});
	await page.pdf({path: '/tmp/hn.pdf', format: 'A4'});
	await browser.close();
})();
```

**What is the expected result?**

No error.

**What happens instead?**

But I got the following error. Would you please let me know what is wrong and how to fix the problem? Thanks.

```
$  ./main.js 
(node:73800) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.printToPDF): PrintToPDF is not implemented
    at /usr/local/lib/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/local/lib/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page.pdf (/usr/local/lib/node_modules/puppeteer/lib/Page.js:977:39)
    at Page.<anonymous> (/usr/local/lib/node_modules/puppeteer/lib/helper.js:112:23)
    at main.js:11:13
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:73800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:73800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tom-s** [comment]
you need to be in headless true to use PDF

**Comment by JPtenBerge** [comment]
@tom-s: Headless, I'm running into [inconsistent font rendering](https://github.com/puppeteer/puppeteer/issues/2410). And that causes me to be a bit stuck. Headless, it's not giving me the results I want. WIth head, I'm not getting any results at all. I upvoted and downvoted your reply because you're right, but I don't want you to be :-)

**Comment by afshawnlotfi** [comment]
Loading extension only works when headless is set to false. And at the same time I need to set headless to true for PDF

**Comment by mathias22osterhagen22** [comment]
Is there any reason why it cannot be implemented on the headless false?

**Comment by jkryanchou** [comment]
Is this issue has been fixed?
