### ISSUE TITLE
Cannot access chromium remote debugging page when running puppeteer in docker

### ISSUE THREAD

**Issue by codyrin93** [puppeteer/puppeteer#5063]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: Windows 10 / CentOS 7 with Docker version 19.03.2
* URLs (if applicable):
* Node.js version: v10.15.1

**What steps will reproduce the problem?**

launch option of Puppeteer:
```
{
  "args": [
    "--remote-debugging-port=9222",
    "--window-size=1920,1080",
    "--mute-audio",
    "--disable-notifications",
    "--force-device-scale-factor=0.8",
    "--no-sandbox",
    "--disable-setuid-sandbox"
  ],
  "defaultViewport": {
    "height": 1080,
    "width": 1920
  },
  "headless": true
}
```

Dockerfile:

```yml
FROM node:10.16.3-slim

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
    && chmod +x /usr/sbin/wait-for-it.sh

WORKDIR /usr/app
COPY ./ ./
VOLUME ["......." ]

RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /usr/app \
    && npm install

USER pptruser

CMD npm run start

EXPOSE 3000 9222
```

Run the new container by :
```
docker run \ 
	-p 3000:3000 \ 
	-p 9222:9222 \ 
	pptr
```

**What is the expected result?**
The headless remote debugging page `http://localhost:9222/` should be able to access by Chrome. 
Endpoints like `http://localhost:9222/json` should be able to access as well

**What happens instead?**
Chrome will show the error `ERR_CONNECTION_REFUSED` when browsing `http://localhost:9222/` 
`http://localhost:9222/json` also cannot be accessed after I dockerize application.

But I can access the debugging page and those endpoints by start the application without docker: `npm run start`.

**Comment by gustavo-maxmilhas** [comment]
Hi @ringolin93 . Have you fixed this problem? i have the same issue

**Comment by eli-l** [comment]
@gustavo-maxmilhas 

I've been able to solve it by adding "--remote-debugging-address=0.0.0.0"

**Comment by mehmetaypar** [comment]
its basicaly adding :
      ,'--remote-debugging-port=9222',
      '--remote-debugging-address=0.0.0.0'

**Comment by yfsper233** [comment]
# --remote-debugging-address=0.0.0.0 在headless模式下可用
