### ISSUE TITLE
Puppeteer not detecting successful response

### ISSUE THREAD

**Issue by zeezeezeeezeee** [puppeteer/puppeteer#5066]
* Puppeteer version: 1.20.0
* Platform / OS version: MacOS Catalina
* Node.js version: v12.13.0

_Please include code that reproduces the issue._

```
 await page.goto('https://example.com/login/')
 await page.type('#email', 'email')
 await page.type('#pass', 'password')
 await page.click('#submit')
 await page.waitForResponse('https://example.com/loginPost/')
```

**What is the expected result?**
Submit login details and wait for the response from /loginPost before continuing.

**What happens instead?**
Login details are submitted and login is successful, but the script hangs at line 5 for 30 seconds before giving me a promise rejection

I have already made sure that I have the correct response url but I cant seem to get this to work.

**Comment by kblok** [comment]
I think that's a race condition. You could try something like this:

```
await page.goto('https://example.com/login/')
const responsePromise = page.waitForResponse('https://example.com/loginPost/')
await page.type('#email', 'email')
await page.type('#pass', 'password')
await page.click('#submit')
await responsePromise
```

**Comment by zeezeezeeezeee** [comment]
> I think that's a race condition. You could try something like this:
> 
> ```
> await page.goto('https://example.com/login/')
> const responsePromise = page.waitForResponse('https://example.com/loginPost/')
> await page.type('#email', 'email')
> await page.type('#pass', 'password')
> await page.click('#submit')
> await responsePromise
> ```

This fixed my issue, thanks
