### ISSUE TITLE
Missing documentation for page.waitForResponse

### ISSUE THREAD

**Issue by pengyu** [puppeteer/puppeteer#5069]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforresponseurlorpredicate-options

The doc only explains the options without explaining what this function actually does. My guess is that it will send the request to the URL and wait for its response, It is not to wait for something URL to be accessed due to some other cause (clicking a link). I am not sure if my understanding it correctly. Could anybody explain? Nevertheless, it is not proper to make a function without fully documenting it.

Also, could anybody provide a minimal working example (with a working URL, maybe via httpbin.org) on how to use this function? Thanks.

**Comment by kblok** [comment]
`waitForNavigation` returns a promise which will be resolved when a response with that URL is sent though the `response` event.
It's like listening to the network tab on the developer tools. It won't work with link navigations.
