### ISSUE TITLE
launch puppeteer causes cmd.exe popup

### ISSUE THREAD

**Issue by moryoav** [puppeteer/puppeteer#5070]
I'm using puppeteer through node-red-contrib-web-page-screenshot, which uses a fairly straightforward implementation here:
https://github.com/pokiiio/node-red-contrib-web-page-screenshot/blob/master/screenshot.js
The problem - "puppeteer.launch" causes a cmd.exe window (Windows 10) window to appear for a split second. This is incredibly annoying. Is there a way to completely launch chromium hidden without this cmd terminal popup window?

Edit 1 : 
This code:
https://github.com/GoogleChrome/puppeteer/blob/4c62e09a766593c7902a7068896caa6b690b55ba/lib/Launcher.js#L132
spawn should have the option: {windowsHide: true}.

Edit 2 :
The code should include windowsHide: true in the spawn, but it still does not work due to this bug:
https://github.com/nodejs/node/issues/21825 
so even after the addition of windowsHide, I'll need to wait for a nodejs fix I think.

**Comment by dimitryzub** [comment]
For anyone stumble upon this issue while Googling. I fixed the same issue (in my case it was opening 3 cmd.exe windows), and closes them only when everything is done, in headless mode. When headful, everything works alright.

I've fixed it with `--single-process`  argument.

For example:

```js
const getBrowserInstance = async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--window-size=1600,900", "--single-process"],
  });

**Comment by jochemstoel** [comment]
@dimitryzub 's solution worked for me too.

**Comment by AlaDyn172** [comment]
> For anyone stumbles upon this issue while Googling. I fixed the same issue (in my case it was opening 3 cmd.exe windows), and closes them only when everything is done, in headless mode. When headful, everything works alright.
> 
> I've fixed it with `--single-process` argument.
> 
> For example:
> 
> ```js
> const getBrowserInstance = async () => {
>   const browser = await puppeteer.launch({
>     headless: true,
>     args: ["--no-sandbox", "--disable-setuid-sandbox", "--window-size=1600,900", "--single-process"],
>   });
> ```

thanks, it worked!

**Comment by aboucodeur** [comment]
Thanks this solve the probleme but puppeteer take many time to download i'm using the technique to launch executable manualy is client machine like local application

**Comment by TimeRainStarSky** [comment]
In chromium v110 and above, --single-process will cause the browser to close. Is there any other way to hide cmd?
