### ISSUE TITLE
Search.js example not working in tryapp page

### ISSUE THREAD

**Issue by Matt-Foo-SL** [puppeteer/puppeteer#5071]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v1.9.0
* Platform / OS version: Windows 10/latest chrome ver
* URLs (if applicable): https://try-puppeteer.appspot.com/
* Node.js version: nil

**What steps will reproduce the problem?**

1. Go to https://try-puppeteer.appspot.com/
2. Select search.js from examples selection
3. Hit Run

_Please include code that reproduces the issue._

1. No code needed. Just try search example.

**What is the expected result?**
 Extract the results from the page.

**What happens instead?**
Error running your code. Error: No node found for selector: #searchbox input

**Comment by kblok** [comment]
I think you should report that here https://github.com/ebidel/try-puppeteer

**Comment by thomaschaplin** [comment]
@shilongfoo @kblok I've raised a PR to fix this issue.

https://github.com/puppeteer/puppeteer/pull/6471

It seems that https://github.com/ebidel/try-puppeteer scrapes the https://github.com/puppeteer/puppeteer repo `examples/` folder which means my PR will fix this issue.
