### ISSUE TITLE
Running Puppeteer in Docker (Google App Engine) - libcups2 missing

### ISSUE THREAD

**Issue by ajoorabchi** [puppeteer/puppeteer#5073]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.19
* Platform / OS version: App Engine Flex (NodeJS)
* Node.js version: 8

**What steps will reproduce the problem?**

I am trying to migrate my code from Google cloud functions to App Engine Flex to speed it up. I have followed the instructions for Running Puppeteer in Docker but one of the dependencies is missing: 

`
.
.
.
Step #1: Get:141 http://archive.ubuntu.com/ubuntu xenial/main amd64 fonts-thai-tlwg all 1:0.6.2-2.1 [7850 B]
Step #1: Fetched 120 MB in 52s (2283 kB/s)
Step #1: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/cups/libcups2_2.1.3-4ubuntu0.9_amd64.deb  404  Not Found [IP: 91.189.88.162 80]
Step #1: 
Step #1: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

app.yaml
`runtime: nodejs
env: flex`

package.json
```
{
  "name": "dialogflowFirebaseFulfillment",
  "description": "This is the default fulfillment for a Dialogflow agents using Cloud Functions for Firebase",
  "version": "0.0.1",
  "private": true,
  "license": "Apache Version 2.0",
  "author": "Google Inc.",
  "engines": {
    "node": ">=8.0.0"
  },
  "main": "index.js",
  "scripts": {
    "preinstall": "apt-get update && apt-get -y install wget && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'  && apt-get update && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf --no-install-recommends && rm -rf /var/lib/apt/lists/*",
    "start": "node index.js",
    "deploy": "gcloud app deploy",
    "lint": "eslint ."
  },
  "dependencies": {
    "actions-on-google": "^2.12.0",
    "firebase-admin": "^8.6.0",
    "firebase-functions": "^3.2.0",
    "dialogflow": "^0.12.0",
    "dialogflow-fulfillment": "^0.6.1",
    "puppeteer": "^1.19.0",
    "express": "^4.17.1",
    "body-parser": "^1.19.0"
  },
  "devDependencies": {
    "firebase-functions-test": "^0.1.6",
    "eslint-config-google": "^0.14.0",
    "eslint": "^6.5.1",
    "eslint-config-semistandard": "^11.0.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-node": "^5.0.0",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1"
  }
}
```

**Comment by fuck-you-linux** [comment]
You're doing nothing wrong, it's fucking Linux again. I had the same problem, installing via a preinstall key in package.json didn't work as well (something with permissions probably, apt update doesn't run properly either via that way). I fixed it by creating a custom Dockerfile, doing the dependencies in there and running via the custom runtime setting in app.yaml. Bill would never had let this happen.
