### ISSUE TITLE
Recursive $/$$

### ISSUE THREAD

**Issue by notgne2** [puppeteer/puppeteer#508]
Maybe add the ability to get child elements on `ElementHandle` instances, using `$`, and `$$`, syntax should work like:

```js
let $header = await page.$("div.header")
let $homeLink = await $header.$("a.home")

await $homeLink.click()
```

Along with `$$`, this would make iterating pages with recursive structures so much more easier, no longer requiring it all to be kept inside of `.evaluate` callbacks.

Such as:
```js
let $results = await page.$$(".result")

for (let $result of $results) {
    let $title = await $result.$(".title")

    let title await $title.evaluate(($) => $.innerText)
    console.log(`Title: ${title}`)

    let resUrl = await $title.evaluate(($) => $.href)
    console.log(`Result URL: ${resUrl}`)
    
    let $sourceLinks = await $result.$$(".sources")

    for (let $sourceLink of $sourceLinks) {
        let sourceUrl = await $sourceLink.evaluate(($) => $.href)
        console.log(`Source URL: ${sourceUrl}`)
    }
}
```
Don't think this would be too hard to implement, and work make automation a lot easier

**Comment by aslushnikov** [comment]
This gonna be a part of object handles story: #382

**Comment by kidwm** [comment]
@aslushnikov So when can we use something like `ElementHandle.$()`?

**Comment by aslushnikov** [comment]
@kidwm I'd be happy to review a pull request with tests and documentation. This should be easy to do similarly to the [`Frame.$`](https://github.com/GoogleChrome/puppeteer/blob/32398d1/lib/FrameManager.js#L235-L242) and [`Frame.$$`](https://github.com/GoogleChrome/puppeteer/blob/32398d1/lib/FrameManager.js#L276-L287). Check out the CONTRIBUTING.md for the tips on development and running tests.
