### ISSUE TITLE
Feature request : Add `scrollDown` boolean option to `page.pdf` API

### ISSUE THREAD

**Issue by loicraux** [puppeteer/puppeteer#5081]
## Original observation

While trying to generate a pdf from a page, I could not see some images in the generated pdf.
I eventually figured out that these images were lazyly loaded when the page is scrolled down and the image placeholder becomes visible.

While there are some workarounds like [this one](https://wiki.zegnat.net/cache/?md5=f7ce4fd73de0ac41f15ea708b4c8f20f) to manually scroll down and force the loading of these images, I also realized that if I simply made a call to `page.screenshot` _before_ my call to `page.pdf`, then the images are loaded and my pdf is fine.

## Environment

* Puppeteer version: 1.20.0
* Platform / OS version: Win 10
* URLs (if applicable): 
* Node.js version: 10.16.0
 
## Feature request

That'd be useful to have an extra `scrollDown` boolean option to pass to the `page.pdf` API to tell puppeteer to scroll down the entire page like it is somehow done in `page.screenshot` API so that content lazily loaded when page is scrolled down is loaded before the pdf page is generated.

Your thoughts ?

**Comment by kblok** [comment]
I think that wouldn't be so easy to generalize. e.g. you should also check that images were loaded before printing the PDF.

**Comment by a3gh** [comment]
> That'd be useful to have an extra `scrollDown` boolean option to pass to the `page.pdf` API to tell puppeteer to scroll down the entire page

This won't work for sites with infinite scrolling ([Consider imgur.com](https://imgur.com/)).
