### ISSUE TITLE
Get the active/visible page in headfull mode (non-headless)

### ISSUE THREAD

**Issue by luiso1979** [puppeteer/puppeteer#5084]
I don't find a way to get the active/visible page in a non-headless execution. 

I use `browser.pages()` to get the list of pages but there are no attributes (or a browser method) to retrieve the active/visible/focused page.

I'm missing something or this is a non existent functionality.

Thanks

**Comment by kblok** [comment]
You could evaluate the `document.visibilityState` of every page.

```js
var activePage;
for(const page of (await browser.pages())) {
  console.log(await page.evaluate(() => document.visibilityState));
  if ((await page.evaluate(() => document.visibilityState)) === 'visible') {
    activePage = page;
    break;
  }
}
console.log(activePage.url());
```

**Comment by alexsunday** [comment]
> 

cannot work on headless mode.
