### ISSUE TITLE
page.evaluate can't get Set back

### ISSUE THREAD

**Issue by gengjiawen** [puppeteer/puppeteer#5085]
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOS 10.15
* URLs (if applicable):
* Node.js version: 13

**What steps will reproduce the problem?**

page.evaluate can't get Set back
It works on array, not Set.

```ts
  const s = await page.evaluate(async () => {
    // @ts-ignore
    const urls = await global.hi()
    console.log(`urls`, urls)
  }
```

hi difinition:

```js
global.hi = function() {
  return new Promise(resolve => {
    setTimeout(()=> {
      const n = new Set()
      n.add(3)
	  // n (Set) is not working, c (Array type) is working
      const c = [3]
      resolve(c)
    }, 1 * 1000)
  })
}
```

**What is the expected result?**

**What happens instead?**

**Comment by kblok** [comment]
`evaluate` needs to serialize (a.k.a. `JSON.stringify`) the result to send that back to node.  The problem is that [a Set is not serializable](https://stackoverflow.com/questions/31190885/json-stringify-a-set). So you might need to use an array.

**Comment by benjamingr** [comment]
Alternatively - you can do the serialization yourself using a format that serializes set (so no JSON) and pass it as a string to JavaScript. That's what I ended up doing in several projects.

Unfortunately puppeteer can only pass strings quickly (as it will JSON.stringify any buffer you pass).

**Comment by gengjiawen** [comment]
Thanks.
