### ISSUE TITLE
What's new in 2.0?

### ISSUE THREAD

**Issue by avalanche1** [puppeteer/puppeteer#5087]
Looks like a major version bump.
Any plans for a blog post?

**Comment by benjamingr** [comment]
There is actually a changelog with features here: https://github.com/GoogleChrome/puppeteer/releases/tag/v2.0.0

**Comment by alixaxel** [comment]
One thing I noticed is that [`r705776`](https://crrev.com/705776) build version is 79.0.3945.0 but release notes state 79.0.3942.0.

FYI @mathiasbynens

**Comment by mathiasbynens** [comment]
Per [Omahaproxy](https://omahaproxy.appspot.com/):

> Commit 4528b050 initially landed in 79.0.3942.0
