### ISSUE TITLE
setExtraHTTPHeaders: support both object and Map as `headers` argument

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#509]
It would be nice to support passing an object literal into `setExtraHTTPHeaders` as well as a `Map`.

- The protocol already takes an object
- it'll reduce the (`new Map(Object.entries({}))`) boilerplate for users.
- objects are easier to work with.

this:
```js
await page.setExtraHTTPHeaders(new Map(Object.entries({
  'X-Header': 'blah blah' 
})));
```

to:
```js
await page.setExtraHTTPHeaders({
  'X-Header': 'blah blah' 
});
```

**Comment by pavelfeldman** [comment]
The use of Map is deliberate, it emphasizes that the order of the headers is going to be preserved. It does go through the object conversion, but we make sure order is intact.

**Comment by pavelfeldman** [comment]
```js
await page.setExtraHTTPHeaders(new Map([
  ['X-Header', 'blah blah']
]);
```

**Comment by ebidel** [comment]
Found https://github.com/GoogleChrome/puppeteer/commit/480547955cb9c0cf398cbc0b9a31840e271dc028 which supports that. However, there's a note in the docs that says order isn't guaranteed:

<img width="913" alt="screen shot 2017-08-23 at 8 36 41 pm" src="https://user-images.githubusercontent.com/238208/29648410-ceb1f30a-8842-11e7-9d8b-30e672a0aa5d.png">
