### ISSUE TITLE
How to detect the request come from Puppeteer?

### ISSUE THREAD

**Issue by kazaff** [puppeteer/puppeteer#5090]
Hi, there~

I wonder whether or not exists some flag or tag that the website can use it to detect the request come from Puppeteer?

When I ran my code based on Puppeteer to visit the target website, I found that the website seem like knew the request was made by Puppeteer. How can it do?

**Comment by kazaff** [comment]
I think it may be because of Chrome setup some header in the request when it runs under "automated test software" mode.
But I can't find that “header” in Dev-tools or fiddler~

And in order to test, I run the request by the same chromium manually, Everything is OK, The website does what I expected.

**Comment by benjamingr** [comment]
There are tons of ways to fingerprint but namely:

 - The language
 - The fact the request is coming from chromium and no chrome (so it has different codecs etc).
 - APIs
 - The fact the devtools is connected
 - timing of API calls and network calls 

And lots of other things - there are companies whose job is literally to detect puppeteer (and other automation) and deal with it :]

**Comment by kazaff** [comment]
@benjamingr  thank you~

I found a way to cross the limitation. It's an easy way:
```javascript
const browser = await puppeteer.launch({headless: false, ignoreDefaultArgs: ["--enable-automation"],});
```

This will let the browser to not setup `navigator.webdriver` variable.

**Comment by benjamingr** [comment]
@kazaff it would still be super easy to detect - for what it's worth :]

**Comment by pppluto** [comment]
if you don't care, try `headless: false`
