### ISSUE TITLE
Docs: no docs for puppeteer.defaultArgs()

### ISSUE THREAD

**Issue by avalanche1** [puppeteer/puppeteer#5094]
[puppeteer.defaultArgs()](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-puppeteerdefaultargs-options) mentionned [here](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-puppeteerlaunchoptions)

**Comment by kblok** [comment]
@avalanche1 are you looking for this? https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-puppeteerdefaultargsoptions

**Comment by avalanche1** [comment]
Yes. But the link mentioned here needs fixing.
![image](https://user-images.githubusercontent.com/10534563/68077645-57d74600-fdd8-11e9-98f6-9b53df350197.png)
