### ISSUE TITLE
Question: enable-developer-mode flag

### ISSUE THREAD

**Issue by avalanche1** [puppeteer/puppeteer#5095]
I'm testing my extension extensively (haha) with Puppeteer; but to debug background scripts I need each time to go to `chrome://extensions` and enable developer mode:
![image](https://user-images.githubusercontent.com/10534563/67759511-9ffd0e00-fa50-11e9-994a-9a4e352e46fd.png)
Maybe knowledgeable guys here know if there's a command line option for chromium that I can use in `puppeteer.launch()` to have this on by default? I googled it but didn't find any.

**Comment by marcio199226** [comment]
Me too need this flag

**Comment by avalanche1** [comment]
For the time being - here's a beautiful script I'm using rite now:
```js
  // Enable browser dev-mode for extensions.
  const [chromeExtenstionsTab] = await browserInstance.pages();
  await chromeExtenstionsTab.goto("chrome://extensions");
  await chromeExtenstionsTab.waitFor(100);
  const devModeToggle = await chromeExtenstionsTab.evaluateHandle(
    'document.querySelector("body > extensions-manager").shadowRoot.querySelector("extensions-toolbar").shadowRoot.querySelector("#devMode")'
  );
  await devModeToggle.click();
```

**Comment by nishaantShrm** [comment]
I also need this functionality, the workaround script works for headless = false, but when you go to headless = true, it throws an error that "page.goto: net::ERR_INVALID_URL at chrome://extensions/"
