### ISSUE TITLE
Unable to get multipart/form-data from POST requests with requestInterceptor

### ISSUE THREAD

**Issue by ivansieder** [puppeteer/puppeteer#5097]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOS 10.15 (19A602)
* URLs (if applicable): https://codesandbox.io/s/fervent-http-c24v7 (for the demo)
* Node.js version: v12.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Create a form with `enctype="multipart/form-data"`, e.g. https://codesandbox.io/s/fervent-http-c24v7
2. Open the page with puppeteer, add a request interceptor, add a file to the upload input and submit the form.
```javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);

  page.on("request", (interceptedRequest) => {
    if (interceptedRequest.method() === "POST") {
      console.log(interceptedRequest.postData());
    }

    interceptedRequest.continue();
  });

  await page.goto("https://c24v7.codesandbox.io/");
  const input = await page.$("#file_input");

  // a simple txt file with little just some dummy text
  await input.uploadFile("./file.txt");
  await page.click("#submit");
  
  await browser.close();
})().catch(console.error);
```

**What is the expected result?**
According to me, the multipart/form-data should be available inside the request interceptor (requestInterceptor.postData()).

**What happens instead?**
The requestInterceptor.postData() is undefined. Interestingly, when using puppeteer-firefox, this very same code works properly and the postData() is available inside the requestInterceptor.

**Comment by mathiasbynens** [comment]
Note that this is not new behavior in Puppeteer v2. Older versions behave similarly: `npm i puppeteer@chrome-74; node test.js`

**Comment by mathiasbynens** [comment]
For the POST request in the repro, `event.request` is the following:

```
{
  url: 'https://postman-echo.com/post',
  method: 'POST',
  headers: {
    Origin: 'https://c24v7.codesandbox.io',
    'Upgrade-Insecure-Requests': '1',
    'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarytQRK39gKpGgqsnw0',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/79.0.3945.0 Safari/537.36',
    'Sec-Fetch-User': '?1',
    Referer: 'https://c24v7.codesandbox.io/'
  },
  mixedContentType: 'none',
  initialPriority: 'VeryHigh',
  referrerPolicy: 'no-referrer-when-downgrade'
}
```

That is ,`event.request.postData` is missing (and thus `undefined`). https://github.com/GoogleChrome/puppeteer/blob/c2651c2b5cc888ebd0ca6be87063d9f98b9eb59c/lib/NetworkManager.js#L335

**Comment by ivansieder** [comment]
And as it's also not showing up in chrome's devtools, I guess it's related to the devtools @mathiasbynens ?

**Comment by edouardmercier** [comment]
From my experience, the fact that the `Request.postData()` does not give access to the body unless it is a string also applies in case of a simple HTTP POST with a binary body . This restriction may be due to the complexity to expose a blob or a buffer. The other ticket #4576 also refers to this topic.

I my case, the fact that intercepted HTTP POST request cannot access to their content when binary is a major penalty and forces me to encode base64 as an encoding on the original web services.

If puppeteer-firefox offers this feature, it would be great to have Chromium support it as well.

**Comment by hunter-tp** [comment]
i have same problem too...

**Comment by rgoldstein01** [comment]
Was this ever resolved? @ivansieder

**Comment by ivansieder** [comment]
I've switched to Firefox @rgoldstein01
