### ISSUE TITLE
Improve doc for elementHandle.toString()

### ISSUE THREAD

**Issue by dandv** [puppeteer/puppeteer#5104]
https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-elementhandletostring doesn't say much. I was looking for a method to return the text content of the element, similar to `page.content()`, but what I get is a useless constant, `JSHandle@node`. Is this method worth documenting even?

**Comment by menriquez** [comment]
@dandv `let textValue = await (await mainLink.getProperty('text')).jsonValue();` works for me
