### ISSUE TITLE
SIGINT event listener doen't work with handleSIGINT

### ISSUE THREAD

**Issue by drobnikj** [puppeteer/puppeteer#5106]
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version: 

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

const cleanup = async () => {
    console.log('Received kill. Cleaning up.');
    await new Promise((resolve => setTimeout(resolve, 3000)));
    console.log('This won\'t be logged.');

    process.exit(0);
};

process.on('SIGINT', cleanup);

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await new Promise((resolve => setTimeout(resolve, 10000)));
    await browser.close();
})();
```

Just emit SIGINT event right after the browser was launched.

I guest that this is because you exit process in SIGINT event listener.
https://github.com/GoogleChrome/puppeteer/blob/4c62e09a766593c7902a7068896caa6b690b55ba/lib/Launcher.js#L167

I know that I can disable it with `handleSIGINT ` option, but in this case, you will loose logic which killing browsers.

**What is the expected result?**
`console.log('This won\'t be logged.');` will log the message.

**What happens instead?**
There is no message.

**Comment by ehimiranov** [comment]
Well, you can set `cleanup` callback on `SIGINT` event inside your async module block and call `browser.close()` directly:
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        handleSIGINT: false
    });
    const page = await browser.newPage();
    await new Promise((resolve => setTimeout(resolve, 10000)));
    await browser.close();

    const cleanup = async () => {
        console.log('Received kill. Cleaning up.');
        await new Promise((resolve => setTimeout(resolve, 3000)));
        console.log('This won\'t be logged.');

        await browser.close();  // <--------- write here

        process.exit(0);
    };

    process.on('SIGINT', cleanup);
})();
```
Also you can see such solution here - https://github.com/GoogleChrome/puppeteer/issues/1225#issuecomment-357214851
