### ISSUE TITLE
importFunction

### ISSUE THREAD

**Issue by stevenvachon** [puppeteer/puppeteer#5108]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOS 10.15
* URLs (if applicable):
* Node.js version: 12.13.0

**What steps will reproduce the problem?**
This code *does* work, but it's not very convenient:
```js
let browser, page;

const fn = window => {};

before(async () => {
  browser = await puppeteer.launch({...});
  page = await browser.newPage();
  await page.addScriptTag({ content: `window.fn = ${fn.toString()}` }); // this line
});

it('browser test', () => page.evaluate(() => fn(window));

it('node.js test', () => {
  const {window} = new JSDOM('<!doctype html>');
  fn(window);
});
```

**What is the expected result?**
Something more convenient, such as:
```js
before(async () => {
  browser = await puppeteer.launch({...});
  page = await browser.newPage();
  await page.importFunction('fn', fn); // this line
});
```

**What happens instead?**

**Comment by avastel** [comment]
If I understand what you want to do, I guess it's already available with the Page.exposeFunction:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction

**Comment by stevenvachon** [comment]
`exposeFunction` does not run the function within the document where its globals would be available.

**Edit**: Notice the `window` argument in `fn`; it would be serialized with `exposeFunction`.
