### ISSUE TITLE
when page is too long ,it can not be scrolled to bottom

### ISSUE THREAD

**Issue by k19810703** [puppeteer/puppeteer#5109]
Here is my source code;
`
const puppeteer = require('puppeteer');

const launchConfig = {
  ignoreHTTPSErrors: true,
  headless: false,
  args: [
    // '--start-fullscreen',
    '--ignore-certificate-errors',
    '--ignore-certificate-errors-spki-list',
  ],
  slowMo: 30,
  // defaultViewport: null,
  defaultViewport: {
    width: 1280,
    height: 1024,
  },
};
(async () => {
  const browser = await puppeteer.launch(launchConfig);
  const page = await browser.newPage();
  await page.goto('https://github.com/GoogleChrome/puppeteer/blob/master/lib/DeviceDescriptors.js');
})().catch(error => console.error(error));
`

what happened:
Browser was opened but it can not be scrolled to bottom. 
<img width="1206" alt="图片" src="https://user-images.githubusercontent.com/19642360/68002602-98ce3e00-fca4-11e9-8673-61f3483e1f98.png">

**Comment by menriquez** [comment]
the page did exactly what you told it to do...you opened it with a width of 1280 and height of 1024...that's where on the page height 1024 goes to.   

if you want it got all the way to the bottom i would suggest height of 2048 maybe?  even more if needed.

**Comment by k19810703** [comment]
I think more than 1024(height) was shown on page but I can't got all page , and I can't got all page screen shot either.

Set to 2048 may fix some page, but when I got other long page such as heith more than 4000 , same problem appears. Is there a common way can fix all page. 

Selienum seems doesn't have the same problem , all paged can be handled rightly.

**Comment by k19810703** [comment]
Any one can help on this.
