### ISSUE TITLE
page.type() doesn't work with date inputs

### ISSUE THREAD

**Issue by avalanche1** [puppeteer/puppeteer#5118]
It's not really an issue with Puppeteer, but maybe you guys can advise 🙏 
I'm devving a chrome extension and it uses devtools protocol to emulate input to fill in forms.
I use `Input.insertText` - same as Puppeteer. The prob is - it works for text inputs, but not for date inputs (`<input type='date' />`). Inputs simply ignore it.
Wherein `Input.dispatchKeyEvent` works just fine. But then I have to iterate over all the text characters - which is not what was my intention.

I've tried Puppeteer's `.type` api with date inputs and it works as intended. I've checked out the source at https://github.com/GoogleChrome/puppeteer/blob/master/lib/Input.js#L158 and it uses `Input.insertText` - just like I do.

So how can it be - that Puppeteer's input goes through - and mine doesn't.

**Comment by uzair004** [comment]
same problem, puppeteer can't type or assign value to `input type='date'` fields.
tried
`await page.type("[name='j_idt31:an_ugly_form_input']", "17-02-2019");`
I am using `waitForNavigation` & `waitForSelector` before typing, so page is loaded well.
It open up calender picker as I can see in head-mode but can't type date into it.
looks like input box accept certain format or something.

P.S: I can easily type or assign value in developer console, tried `page.evaluate` as well.

**Comment by darakeon** [comment]
@uzair004 , maybe this is the format. If the fake browser you are using is in en-US, it will expect that you type 02/17/2019.

**Comment by uzair004** [comment]
@darakeon actually changing focus on `date field` then typing works for me, I realize there is `readonly` attribute I had to remove as well. 
Now the problem is `page.type` is messing up the text I am providing to write in `input` field. Sometimes characters order changes.

```
    await page.focus("[name='j_idt31:verisysForm:issuedate_input']");
    await page.$eval("[name='j_idt31:verisysForm:issuedate_input']", (e) =>
      e.removeAttribute("readonly")
    );
    await page.type("[name='j_idt31:verisysForm:issuedate_input']", issueDate);
```

**Comment by OrKoN** [comment]
Please re-try with the latest Puppeteer version and using the hints from other commenters. If it's still the issue, please re-open with a recent repro script.
