### ISSUE TITLE
Error: Navigating frame was detached

### ISSUE THREAD

**Issue by yevgeniy-belov** [puppeteer/puppeteer#5123]
### Steps to reproduce

Environment:

Puppeteer   2.0.0;
OS               Windows 10;
Node.js       12.0.0;

`const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });

    const page = await browser.newPage();
    page.on('framenavigated', (frame) => {
        console.log('Frame navigated: ' + frame.name());
    });

    page.on('framedetached', (frame) => {
        console.log('Frame detached: ' + frame.name());
    });

    await page.goto('http://example.com');
    await page.evaluate(() => {
        let iframe;
        iframe = document.createElement('iframe');
        iframe.name = 'my_frame';
        document.body.appendChild(iframe);
    });

    let frames = await page.frames();
    let my_frame = frames[1];

    try {
        await my_frame.goto('http://example.org');
    } catch (error) {
        console.log(error);
    }

    try {
        await my_frame.goto('http://example.net');
    } catch (error) {
        console.log(error);
    }
    
    await browser.close();

})();`

**What is the expected result?**
Navigation should be completed without errors.

**What happens instead?**
Error: Navigating frame was detached

**Comment by kblok** [comment]
The problem there is that `frame.goto` calls `navigate` which is a page action, and that will kill your child frame.

**Comment by yevgeniy-belov** [comment]
Well, this doesn't happen in versions prior to 1.20.0

**Comment by kblok** [comment]
My bad, `Page.navigate` is getting a frameId.

**Comment by dmnrmr** [comment]
I was struggling with similar problem (frame detaching) on version `2.0.0`. For whatever reason iframe I was interested for was detaching, and `page.frames()` returned an empty array and at the same time iframe was still there in the dom. So downgrading to `1.19.0` fixed the problem.

**Comment by kblok** [comment]
@cssberries @dmnrmr could you try disabling the `site-per-process` flag?
```js
const browser = await puppeteer.launch({headless: false, args: ['--disable-features=site-per-process']})
```

**Comment by yevgeniy-belov** [comment]
It seems like `'--disable-features=site-per-process'` does the trick. This is a good news!
The question though is what are the implications of this? What is the bad news?

**Comment by kblok** [comment]
@mathiasbynens I think you will have some insights related to this flag.
