### ISSUE TITLE
Headers keys specified in a request.respond are passed to the response in lower case

### ISSUE THREAD

**Issue by yamelyamel16** [puppeteer/puppeteer#5124]
Hi, im trying to change the name of  a giving file when im downloading it, but once i intercept the request and try to change its matching response, the content-disposition key, which contains this filename, is written in the response in lower case, which i guess i causing the web to refuse to download the file since its throwing an error:

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: Fedora 30
* URLs (if applicable): 
* Node.js version: v10.16.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
```node
const fs = require("fs");
const puppeteer = require('puppeteer');

(async () => {

    const browser = await puppeteer.launch({headless: false,args: ['--no-sandbox','--disable-setuid-sandbox']});
    const page = await browser.newPage();
    await page.setRequestInterception(true);

    page.on("request", interceptedRequest => {
        const url = interceptedRequest.url();
        const data = interceptedRequest.postData();
        if (/downloadHourlyHistZips/.test(data)) {
            interceptedRequest.respond({
                //headers: {"Access-Control-Allow-Origin": "*"},
                status: 200,
                headers: {"Access-Control-Allow-Origin": "*"},
                headers: {'Content-Disposition': 'attachment; filename="test.zip"'}
            });
        }else{
            interceptedRequest.continue();
        }
    });

    await page.goto('https://www.iso-ne.com/isoexpress/web/reports/load-and-demand/-/tree/demand-by-zone', {waitUntil: 'networkidle2'});

})();
```
2. Launch chromium

**What is the expected result?**

![2](https://user-images.githubusercontent.com/41320929/68138122-5321a780-ff28-11e9-9131-ed810a90e737.png)

Instead of historical.zip, i expect the name specified in the script

**What happens instead?**

![1](https://user-images.githubusercontent.com/41320929/68138130-561c9800-ff28-11e9-95b8-f7dc456c6c72.png)

![3](https://user-images.githubusercontent.com/41320929/68138271-91b76200-ff28-11e9-83f6-0b1208ac0151.png)

The web just doest not allow me to download the file due to some errors, obviously i guess..

**Comment by lolyinseo** [comment]
#7052
