### ISSUE TITLE
Unable to bypass CSP while trying to add script via page.addScriptTag

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5127]
### Steps to reproduce

Run the following gist: https://gist.github.com/VikramTiwari/dc791b0b4fcec300307b9d601c361111

* Puppeteer version: `^2.0.0`
* Platform / OS version: `macOS 10.15`
* URLs (if applicable): Tested on https://github.com/google
* Node.js version: `v12.13.0`

**What steps will reproduce the problem?**
Run the linked gist and look at the console to see the following error.
<img width="539" alt="Screen Shot 2019-11-05 at 10 51 26 AM" src="https://user-images.githubusercontent.com/1330677/68237343-c88a8800-ffbb-11e9-811f-025bf30fec16.png">

You can also check by opening the console in page and typing `window.vik` which should return `undefined`.

**What is the expected result?**
The console error shouldn't happen and `window.vik` should result in `true`

**Comment by VikramTiwari** [comment]
I tried it with latest chrome as well and seems like it works intermittently there based on different machines. Is this some experiment/flag that I need to enable/disable?

**Comment by codesorter2015** [comment]
@VikramTiwari,  Run the following gist: https://gist.github.com/codesorter2015/d40b9d5902e2c4fd14c81fb5c737db5a

**Comment by VikramTiwari** [comment]
@codesorter2015 Interesting. Thanks!

Also found the related samples in the tests https://github.com/GoogleChrome/puppeteer/blob/master/test/page.spec.js#L783-L840
