### ISSUE TITLE
Create an executable package for puppeteer.

### ISSUE THREAD

**Issue by vyomsrivastava** [puppeteer/puppeteer#5129]
So I wanted to create an executable file for my puppeteer code. I used nexe for this. It has created the package for my code but it doesn't include all the dependencies and chromium in it. So how can I create, you can say create executable file with all dependencies and chromium which will just start executing the puppeteer with just double click.

Nexe is good but I am not able to include all dependencies and chromium.  I want to give it to my team (who are non coders) who can just simply double click the executable file and it starts running. P.S. I am using MacOS and my team as well.

**Comment by tracure1337** [comment]
Good idea. Did you ever find a nice solution for this?

**Comment by Lord-Betto** [comment]
> So I wanted to create an executable file for my puppeteer code. I used nexe for this. It has created the package for my code but it doesn't include all the dependencies and chromium in it. So how can I create, you can say create executable file with all dependencies and chromium which will just start executing the puppeteer with just double click.
> 
> Nexe is good but I am not able to include all dependencies and chromium. I want to give it to my team (who are non coders) who can just simply double click the executable file and it starts running. P.S. I am using MacOS and my team as well.

im having the same problem in windows.
