### ISSUE TITLE
the installation failed on CentOS

### ISSUE THREAD

**Issue by JustinYi922** [puppeteer/puppeteer#513]
Some time ago，I tried to use headless Google,but the installation failed on CentOS 。I had to give up. The recent rise of puppeteer has failed again. Could you tell me when this can be used on CentOS?. Thank you

The following is a false report：

npm i puppeteer --save                       
                                                                                
> puppeteer@0.9.0 install /home/node/***/node_modules/puppeteer        
> node install.js                                                               
                                                                                
/home/node/***/node_modules/puppeteer/utils/ChromiumDownloader.js:89   
  downloadRevision: async function(platform, revision, progressCallback) {      
                          ^^^^^^^^                                              
SyntaxError: Unexpected token function                                          
    at Object.exports.runInThisContext (vm.js:78:16)                            
    at Module._compile (module.js:543:28)                                       
    at Object.Module._extensions..js (module.js:580:10)                         
    at Module.load (module.js:488:32)                                           
    at tryModuleLoad (module.js:447:12)                                         
    at Function.Module._load (module.js:439:3)                                  
    at Module.require (module.js:498:17)                                        
    at require (internal/module.js:20:19)                                       
    at Object.<anonymous> (/home/node/***/node_modules/puppeteer/instal
l.js:17:20)                                                                     
    at Module._compile (module.js:571:32)                                       
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ch
okidar/node_modules/fsevents):                                                  
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}
)                                                                               
npm ERR! Linux 2.6.32-642.15.1.el6.x86_64                                       
npm ERR! argv "/usr/local/node-v7.2.0-linux-x64/bin/node" "/usr/local/node-v7.2.
0-linux-x64/bin/npm" "i" "puppeteer" "--save"                                   
npm ERR! node v7.2.0                                                            
npm ERR! npm  v3.10.9                                                           
npm ERR! code ELIFECYCLE                                                        
                                                                                
npm ERR! puppeteer@0.9.0 install: `node install.js`                             
npm ERR! Exit status 1                                                          
npm ERR!                                                                        
npm ERR! Failed at the puppeteer@0.9.0 install script 'node install.js'.        
npm ERR! Make sure you have the latest version of node.js and npm installed.    
npm ERR! If you do, this is most likely a problem with the puppeteer package,   
npm ERR! not with npm itself.                                                   
npm ERR! Tell the author that this fails on your system:                        
npm ERR!     node install.js                                                    
npm ERR! You can get information on how to open an issue for this project with: 
npm ERR!     npm bugs puppeteer                                                 
npm ERR! Or if that isn't available, you can get their info via:                
npm ERR!     npm owner ls puppeteer                                             
npm ERR! There is likely additional logging output above.                       
                                                                                
npm ERR! Please include the following file with any support request:            
npm ERR!     /home/node/***/npm-debug.log

**Comment by aslushnikov** [comment]
Your node 7.2 doesn't support async/await. Currently, puppeteer requires Node 7.10 to work. You should update your node to 7.10 or higher.

Note: in a [near future](https://github.com/GoogleChrome/puppeteer/pull/484) it should be possible to use puppeteer with Node 6.

For further CentOS installation issues, please post to the #391

**Comment by JustinYi922** [comment]
@aslushnikov Thank you。Let me have a try
