### ISSUE TITLE
Puppeteer request interceptor not loggin m3u8 requests 

### ISSUE THREAD

**Issue by samuelkampf** [puppeteer/puppeteer#5130]
so i have noticed that the interceptor will not log any file with extension .m3u8 and i was wondering why this is ? ill give you an example on twitch.
Update i just realized that when this is enabled it just wont allow m3u8 to load period?
```
const puppeteer = require('puppeteer-extra');



(async () => {
  process.setMaxListeners(Infinity)
  const browser = await puppeteer.launch({
    headless: false,
    args: [  '--window-size=0x0','--ignore-certificate-errors', '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--disable-accelerated-2d-canvas',
    '--no-first-run',
    '--no-zygote',
    '--disable-gpu']
  }); 
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  const urls = [];
  page.on('request', request => {
    urls.push(request.url());
    console.log(urls)
    request.continue();
  });

// you may have to change the channel because idk if this guy will be on when this is looked at
  await page.goto('https://player.twitch.tv/?channel=r3ar3ntry', {
    timeout: 0,
    waitUntil: 'load'
  });
  try {
    await page.waitForSelector('button#mature-link', /*{ timeout: 5000 }*/)
    await page.click('button#mature-link')
    await page.addStyleTag({content: '.player{display: none}'})
  } catch (error) {
    await page.addStyleTag({content: '.player{display: none}'})
  }

})()
```

**Comment by samuelkampf** [comment]
anyone have any thoughts on this?

**Comment by samuelkampf** [comment]
can anyone help me with this?

**Comment by alexandresgf** [comment]
@samuelkampf any news about it? I have the same problem here, can't extract the M3U8 links from video tag embedded in an iframe.

**Comment by samuelkampf** [comment]
no news its been ages since I worked on this project I did find workarounds there is away to extract the data to a log file and then filter through the log file itself using string interp. But as far as using puppeteer for it this just cant be done at this time.

**Comment by samuelkampf** [comment]
@alexandresgf i replied to you but it wouldnt let me tag you in the last comment so i tagged you in this one in addition to my last post do you mind me asking where you are trying to extract m3u8 data from?

**Comment by alexandresgf** [comment]
@samuelkampf my problem is similar to yours. The difference is, the sites that I'm trying to extract the M3U8 link have two behaviors: (1) the site already load an `iframe` element with a `video` tag embedded on it or (2) you'll need to click in one of the buttons, which has the video resolution like HD, SD, etc, and then it loads an `iframe` element with a video embedded. I was able to extract it until the last week, but since this Monday (04.05.2020) it's just stopped to work.

Here is a screenshot that I took during my tests, in the black square is the iframe, where it should be the video player.

![aovivoclub](https://i.imgur.com/Nj6LV38.png)

So, my code is similar to yours, but I developed a service using JSON-RPC and Puppeteer-Cluster to enqueue and resolve the links sent by the crawlers. Follow the piece of code where I do the extractions.

**NOTE:** This specific piece of code is regarding the sites with the first behavior (it does not demand any clicks, it already load the `iframe` by default).

```
const { logger, cluster } = require('../config/settings');

module.exports = async (args, callback) => {
  let extractStream = async ({ page, data }) => {
    let streamURL = null;
    let url = data.url;
    let ext = data.ext;

    await page.setRequestInterception(true);

    page.on('request', (request) => {
      let regex = new RegExp(`.*\.${ext}.*`, 'i');
      let found = request.url().match(regex);

      logger.debug('Request intercepted to %s', request.url());

      if (found && !streamURL) {
        logger.debug('Match regex "%s" found: %O', regex, found);
        streamURL = found[0];
        request.abort();
      } else {
        request.continue();
      }
    });

    logger.info('Searching for %s stream in URL %s', ext, url);
    await page.setUserAgent(cluster.puppeteerOptions.userAgent);
    await page.goto(url, { waitUntil: 'networkidle0' });
    return streamURL;
  };

  try {
    logger.info('Enqueuing URL: %s', args.url);
    const streamURL = await args.puppeteer.execute(args, extractStream);
    logger.info(
      '%s stream %s in %s',
      args.ext,
      streamURL ? `found ${streamURL}` : 'not found',
      args.url
    );
    callback(null, streamURL);
  } catch (err) {
    logger.error(err);
    callback(null, null);
  }
};
```
And I already thought that could be a Puppeteer-Cluster error, but I just implemented another script with only the Puppeteer and the answer is the same. I did another try using the Pyppeteer (the port of the Puppeteer for Python) and no lucky either.

The sites are:

* [AoVivo.Club](https://aovivo.club/tvonline/)
* [TopCanais](https://topcanais.com/)
* [MultiCanais](https://multicanais.com/tvonlinegratis/)
* [CanaisGratis](https://canaisgratis.eu/)

Sorry, they are all in PT-BR language.

**Comment by iMagicKey** [comment]
Has anyone solved this problem?

**Comment by SwitchGM** [comment]
I'm having this same problem as well, puppeteer also isn't logging .ts file extensions either (an alternative to .m3u8)

**Comment by pironside44** [comment]
I just ran into this issue as well -- I believe this is an issue with how puppeteer does request interception (something with page navigation after the first intercepted request). A way around this is to use a CDP session. Here's a working example I used to grab the m3u8 from a stream:

`const puppeteer = require("puppeteer-extra");
let stealth = require("puppeteer-extra-plugin-stealth")();
puppeteer.use(stealth);

let chromePaths = require('chrome-paths');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        executablePath: chromePaths.chrome,
        defaultViewport: null
    });
    const page = await browser.newPage();


    const client = await page.target().createCDPSession();

    await client.send('Network.enable');
    await client.send('Network.setRequestInterception', {
        patterns: [{
            urlPattern: '*'
        }]
    });

    client.on('Network.requestIntercepted', async ({
        interceptionId,
        request,
        responseHeaders,
        resourceType
    }) => {
        if (request.url.includes('m3u8')) {
            console.log(request.url);
        }

        client.send('Network.continueInterceptedRequest', {
            interceptionId
        });
    });

    await page.goto('https://www.twitch.tv/videos/859777026');
})();`

**Comment by pironside44** [comment]
I just ran into this issue as well -- I believe this is an issue with how puppeteer does request interception (something with page navigation after the first intercepted request). A way around this is to use a CDP session. Here's a working example I used to grab the m3u8 from a stream:

https://gist.github.com/pironside44/307248e1c081ef4d27ec38fa0148d4d7

**Comment by SwitchGM** [comment]
> I just ran into this issue as well -- I believe this is an issue with how puppeteer does request interception (something with page navigation after the first intercepted request). A way around this is to use a CDP session. Here's a working example I used to grab the m3u8 from a stream:
> 
> https://gist.github.com/pironside44/307248e1c081ef4d27ec38fa0148d4d7

I used the same method as you, however I switched completly to CDP instead, with chrome-remote-interface and chrome-launcher

**Comment by XeO-tech** [comment]
A tip on getting video stream requests from iframes. Iframe is a separate target in terms of CDP, so you need to attach a CDP session to the iframe. You can use `browser.targets()` after page is loaded, then find one you need,  attach a session to it, and intercept requests. Hope this will be helpful for newcomers to this topic.  
Additional info: [https://stackoverflow.com/questions/63357370/capture-requests-xhr-js-css-from-embedded-iframes-using-devtool-protocol](url)
