### ISSUE TITLE
QuerySelector dont work with puppeteer but its works on Chrome Console

### ISSUE THREAD

**Issue by TCPPERFUSER** [puppeteer/puppeteer#5132]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7.0
* Platform / OS version: win2k8 R2 Enterprise
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
Code Snippet:
------------------------------------------------------------------------------------
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
//    await page.goto("https://tcp-perf.childrensplace.com/us/home", { waitUntil: 'networkidle0' });
    await page.goto("https://www.childrensplace.com/us/home", { waitUntil: 'networkidle0' });

    console.log("before")

    const subCategory = await page.evaluate(async () => {
      var subCategoryListArray = [];
      let subCategoryList = document.querySelectorAll('.navigation-level-one');
//  do a push here to the array here
        return subCategoryList;

    }).catch(err => console.log(err))

    console.log("subCategory :" + JSON.stringify(subCategory) );  

    await browser.close();
    console.log("after");
})();
---------------------------------------------------------
This works in chrome console -> document.querySelectorAll('.navigation-level-one')
![image](https://user-images.githubusercontent.com/43042256/68315338-9cd3d480-0085-11ea-83aa-a515462cd2f5.png) . But it is returning an error "undefined" 

![image](https://user-images.githubusercontent.com/43042256/68315523-e2909d00-0085-11ea-9a62-bfbda1835ed5.png)

**What is the expected result?**
I am new to puppeteer, and based on the examples that I saw online, this should be returning an array of data that should be available for me to parse and select an item (a category for this instance)

**What happens instead?**
subCategory has an "undefined" value.

**Comment by kblok** [comment]
Maybe you want to use [page.evaluteHandle](https://github.com/GoogleChrome/puppeteer/blob/v2.0.0/docs/api.md#pageevaluatehandlepagefunction-args) or [page.$$](https://github.com/GoogleChrome/puppeteer/blob/v2.0.0/docs/api.md#pageselector-1) ?

Keep in mind that there is a serialization process involved when you return some value from the `evaluate`.  On the other hand, `evaluteHandle` will return a `handle` to an object inside chrome.

**Comment by TCPPERFUSER** [comment]
@kblok thanks for the tip! page.$$ worked for my case.

**Comment by CrispusDH** [comment]
@TCPPERFUSER so close, please, this issue
