### ISSUE TITLE
Referencing object property inside custom await page.waitFor()

### ISSUE THREAD

**Issue by Mahanchello** [puppeteer/puppeteer#5133]
Hi, i'm facing with weird behavior when i'm trying to wait until user message disappears.
i have a function 
``` const checkImpersonationForbidden = async() => {
  await page.waitFor(selector => !document.querySelector(selector), selectors.overviewSel.forbiddenMsg);
  await helper.waitAndClick(selectors.overviewSel.impersonBtn);
  await tools.checkElementText(selectors.overviewSel.forbiddenMsg, "Error: Forbidden");
} 
```
function fails because element is still presented while `await tools.checkElementText(selectors.overviewSel.forbiddenMsg, "Error: Forbidden")` is executed . 
but when i use 
``` const checkImpersonationForbidden = async() => {
  await page.waitFor(() => !document.querySelector("[data-test-id='forbiddenMsg']"));
  await helper.waitAndClick(selectors.overviewSel.impersonBtn);
  await tools.checkElementText(selectors.overviewSel.forbiddenMsg, "Error: Forbidden");
} 
```
it does the trick. 
Will appreciate if you provide me some ideas on how to fix it or make it works 😅

**Comment by kblok** [comment]
The second argument of [page.waitFor](https://github.com/GoogleChrome/puppeteer/blob/v2.0.0/docs/api.md#pagewaitforselectororfunctionortimeout-options-args) is the options object. You could do something like this.

```js
await page.waitFor(selector => !document.querySelector(selector), {}, selectors.overviewSel.forbiddenMsg);
```
