### ISSUE TITLE
Wrong chromium version in v2.0.0 release notes (r706915 not r705776)

### ISSUE THREAD

**Issue by dr-js** [puppeteer/puppeteer#5136]
### Steps to reproduce

check: https://github.com/GoogleChrome/puppeteer/releases/tag/v2.0.0
currently it shows:
> Chromium 79.0.3942.0 (r705776)

and includes commit:
> 81d2600 - feat(chromium): roll Chromium to r705776 (#5058)

but in the commit, the version is changed to `"chromium_revision": "706915"` (https://github.com/GoogleChrome/puppeteer/pull/5058/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11)

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Windows10 (x64)
* URLs (if applicable):
* Node.js version: 13.0.1

For reference, the versions from the release notes is used in chromium pre-download script, and that's how I found the issue.

**What steps will reproduce the problem?**
**What is the expected result?**
**What happens instead?**

**Comment by mathiasbynens** [comment]
Whoops, fixed!
