### ISSUE TITLE
CSS.enable with request interceptor stops execution

### ISSUE THREAD

**Issue by pyatyispyatil** [puppeteer/puppeteer#5141]
Hello. I found an error while recording coverage and tracing data. The puppeteer stops at the CDP call “CSS.enable” and cannot continue execution if the request interceptor was previously enabled.

Code to reproduce the bug:
```js
const puppeteer = require('puppeteer');

const test = async () => {
  const browser = await puppeteer.launch({});
  const page = await browser.newPage();

  // if you remove the interceptor, the bug will not be reproduced
  await page.setRequestInterception(true);
  page.on('request', (interceptedRequest) => {
    interceptedRequest.continue();
  });

  await page.tracing.start({});
  await page.coverage.startCSSCoverage(); // <-- stayed here
  
  await page.goto('https://google.com');

  await page.coverage.stopCSSCoverage();
  await page.tracing.stop();
};

test();
```

* Puppeteer version: 2.0.0
* Platform / OS version: Windows 10 or MacOS 10.14.6
* Node.js version: 10.15.1, 12.13.0

**Comment by kblok** [comment]
I was able to reproduce this issue. I think this could work if you start the coverage before intercepting requests.

```js
await page.tracing.start({});
await page.coverage.startCSSCoverage();

await page.setRequestInterception(true);
page.on('request', (interceptedRequest) => {
    interceptedRequest.continue();
});
```

**Comment by pyatyispyatil** [comment]
Yes, this workaround works. But in my case, I want to use coverage more than once on one page.

**Comment by pyatyispyatil** [comment]
So, I had to first disable the interceptor to collect data and after turning on the coverage record, turn on the interceptor again. And it looks like a dirty hack.
https://github.com/pyatyispyatil/overlooker/blob/master/src/profiler/watching.js#L60

**Comment by sradu** [comment]
I'm seeing a similar situation where Chromium just freezes at the end of a long session. It works once we disable interception. Unfortunately I haven't been able to create a small scale reproduce-able test case.

Still wanted to do a +1 that there seems to be an issue with the latest build.
