### ISSUE TITLE
Not able to remove "\t" from scraped text in puppeteer

### ISSUE THREAD

**Issue by AnchitPhoenix** [puppeteer/puppeteer#5143]
While scraping a table using puppeteer, I came across an issue where one of the data cells contains a lot of space than the actual content.
When checked the webpage, one of the columns (Address) contains "\t\t\t\t\t" in the code before and after the text.

Can someone share how to remove all the "\t" from the text?

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:2.0.0
* Platform / OS version: Windows 10 Pro
* Node.js version: 12.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
1. 	const title = await page.$$eval('table tr th', ths => ths.map((th) => {return th.innerHTML;}));
2. 	const data = await page.$$eval('table tr td', tds => tds.map((td) => { return td.innerHTML; }));
3. 	for(var i=0; i<data.length; i++) { await console.log(title[i] + ': ' + data[i]); };

**What is the expected result?**
```Address:
"Area Name, City Name, State Name"
```

**What happens instead?**
```
Address:
"                                              Area Name, City Name, State Name                             "
```

**Comment by kblok** [comment]
I think this is not related with puppeteer. You can replace tabs with a regex `.replace(/\t/g,'')`.
