### ISSUE TITLE
elementHandle.evaluate not passing the argument to the pageFunction as expected

### ISSUE THREAD

**Issue by vineyyadav** [puppeteer/puppeteer#5144]
As per documentation [`page.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleevaluatepagefunction-args) takes pageFunction and a list of arguments which would be passed to the `pagFunction`. But a single argument passed is not available to the `pageFunction`.

This issue is specifically with `elementHandle.evaluate` and `elementHandle.evaluateHandle`. While checking the [code for `elementHandle.evaluate`](https://github.com/GoogleChrome/puppeteer/blob/fd43f9c23a0f14da19c1f85fa2ad892853f72f5f/lib/JSHandle.js#L54), I noticed that evaluate function is being passed `self` as the second argument which is causing this issue.

* Puppeteer version: v2.0.0
* Platform / OS version: Windows 10
* Node.js version: v10.16.0

**Comment by kblok** [comment]
Do you have some example?
If you use `elementHandle.evaluate`, puppeteer will pass the elementHandle as the first argument, that's the expected behavior.

**Comment by xpader** [comment]
I found that reason is the script in pageFunction have some error, any error will breaking pageFunction functionality, it looks like the arguments was not passed.
