### ISSUE TITLE
Chromium fails to start when calling puppeteer.launch() in Azure App Service

### ISSUE THREAD

**Issue by seangwright** [puppeteer/puppeteer#515]
The line `const chromeProcess = childProcess.spawn(chromeExecutable, chromeArguments, {});` in `puppeteer/lib/Launcher.js` is failing for me.

Line numbers in this stack trace might be off since I added logging to my local `Launcher.js`
```
{ Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at Object.exports.spawn (child_process.js:491:9)
    at Function.launch (D:\home\site\wwwroot\node_modules\puppeteer\lib\Launcher.js:86:40)
    at Function.launch (D:\home\site\wwwroot\node_modules\puppeteer\lib\Puppeteer.js:25:21)
    at __dirname (D:\home\site\wwwroot\server.js:39:29)
    ...
```

Environment:
Azure App Service
OS version: Microsoft Windows Server 2012 x64
Node: 8.1.4

`chromeExecutable` is `D:\home\site\wwwroot\node_modules\puppeteer\.local-chromium\win32-496140\chrome-win32\chrome.exe`

When I try to run `chrome.exe` from the command line inside the App Service I get 

`The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.`

When running locally (Windows 10 x64) I don't have this issue.

It seems this is related to the redistributables of C/C++ installed (or not) on the system
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/the-google-chrome-is-not-working-in-my-windows-10/8ecaed7a-e6e1-4097-970f-d32aaba5ec6f
https://bugs.chromium.org/p/chromium/issues/detail?id=380228

Is there an alternate version of `chrome.exe` that I can try uploading to see if it resolves the issue?

Thanks!

Edit --
It seems using this package in the [Azure App Service sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) might not be an option because of security / processing limitations.

**Comment by kaushiksundar** [comment]
I am getting the same issue while launching puppeteer. 
`{ Error: spawn UNKNOWN }`

Using Azure functions and Node 6.5.

**Comment by seangwright** [comment]
@kaushik-sundar This is where I was hoping to test functionality once support for Node 6.5 landed (which it has now). I'm not surprised some of the same issues appear in Azure Functions as well.

I've seen that many of the headless chrome projects in development had [explicitly stated](https://github.com/graphcool/chromeless/#faq) they support AWS Lambda but I don't know enough about headless Chrome, the compatibility ecosystem or Lambda to understand what needs to be done to support that environment or what needs to change to support Azure (which some of the libraries have stated is on their [roadmap](https://github.com/adieuadieu/serverless-chrome#roadmap)).

My use-case right now is a simple API for generating PDFs in a consistent way from a block of HTML and CSS (something that is difficult or impossible using browser based methods - like jsPDF).

**Comment by gaambo** [comment]
hi there, 
having the same problem on an azure app service/web app. also the chromium binaries couldn't be downloaded on npm install - dunno why, no error message. had to run the install.js in a cmd on the machine myself. 
now i'm getting the "spawn unknown" error. @sgwatgit thanks for your link to the azure app service sandbox restrictions, but i don't fully understand all of this. is there even a way we could get chromium/puppeteer to launch on azure?

**Comment by hdd42** [comment]
had same problem and tried to use linux as ops (while you create your web app or web app for container select linux instead of windows )
this solved first part of the problem (it took you out of sandbox restrictions) after that select built -in runtime for your app (in my case selected node 8.x)  and deployed it.

at that point  I have to install missing necessary shared library dependencies for chrome.   
[Running Puppeteer in Docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)

just use web ssh and install those deps maually

`
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
apt-get update &&\
apt-get install -y google-chrome-unstable
`

now everything ready to use  Headless Chrome with Puppeteer but one more gotcha in your code need to be done,
chrome has to be launched with no-sanbox flags
 
`let    browser = await puppeteer.launch({
                args: [
                    '--no-sandbox',
                    '--disable-setuid-sandbox'
                ]
            });`

this is the only workaround i could find, hope that helps to someone

**Comment by martingagne** [comment]
Anybody was able to start Puputter / Chrome from Azure App Services or Azure Functions? I am getting the same spawn error. Thanks!

```
const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer');
const os = require('os');

module.exports = function (context, req) {
    function failureCallback(error) {
        context.log("--> Failure = '" + error + "'");
    }

    const chromeDir = path.normalize(__dirname + "/../node_modules/puppeteer/.local-chromium/win64-508693/chrome-win32/chrome.exe");
    context.log("--> Chrome Path = " + chromeDir);

    const dir = path.join(os.tmpdir(), '/screenshots');

    if (!fs.existsSync(dir)){
        fs.mkdirSync(dir);
    }

    const screenshotPath = path.join(dir, "example.png");
    context.log("--> Path = " + screenshotPath);

    let browser, page;
    puppeteer.launch({ executablePath: chromeDir, headless: true, args: [ '--no-sandbox', '--single-process', '--disable-gpu' ] })
        .then(b => {
            context.log("----> 1");
            browser = b;
            return browser.newPage();
        }, failureCallback)
        .then(p => {
            context.log("----> 2");
            page = p;
            return p.goto('https://www.example.com');
        }, failureCallback)
        .then(response => {
            context.log("----> 3");
            return page.screenshot({path: screenshotPath, fullPage: true});  
        }, failureCallback)
        .then(r => {
            browser.close();

            context.res = {
                body: "Done!"
            };

            context.done();            
        }, failureCallback);
};
```

Below is the log:

```
2017-12-18T04:32:05  Welcome, you are now connected to log-streaming service.
2017-12-18T04:33:05  No new trace in the past 1 min(s).
2017-12-18T04:33:11.400 Function started (Id=89b31468-8a5d-43cd-832f-b641216dffc0)
2017-12-18T04:33:20.578 JavaScript HTTP trigger function processed a request.
2017-12-18T04:33:20.578 --> Chrome Path D:\home\site\wwwroot\node_modules\puppeteer\.local-chromium\win64-508693\chrome-win32\chrome.exe
2017-12-18T04:33:20.578 --> Path = D:\local\Temp\screenshots\example.png
2017-12-18T04:33:20.965 --> Failure = 'Error: spawn UNKNOWN'
2017-12-18T04:33:20.965 ----> 2
```

**Comment by seangwright** [comment]
I think. for the moment, this is not solvable due to the sandboxing that happens in App Service/Functions.

For my use-case, I switched to making a call to the https://wkhtmltopdf.org/ .exe in process, generating a pdf on disk and sending that via email to a recipient. Not as nice as headless chrome but webkit on the server at least has consistent resolutions/viewports.

Check out @hdd42's solution if you really need headless chrome in App Service.

**Comment by martingagne** [comment]
Thank you @sgwatgit! I am also currently running wkhtmltopdf, however the documents I have to render contain complex SVG and wkhtmltopdf is unable to render them properly. That's why I am looking again at Chrome Headless. I also considered using Azure Functions on Linux (as proposed by @hdd42), however this would add a ~$50 a months to my hosting bill because my current App Service is currently running on Windows.

**Comment by aslushnikov** [comment]
As I got from the thread, this is not a pptr issue: the root cause seems to be Azure's constrained environment.

Please don't hesitate to file new issues if you think we can somehow help here.

**Comment by leidegre** [comment]
The issue isn't that the Azure App Service sandbox the issue is almost always is that the software requires a user interactive session or user profile. Software that depend on APIs that depend on user context will just fail from within Azure App Service. You have to program against that.

Another thing to take into consideration is the process architecture. By default, Azure App Service is 32-bit and it's not like it's a 64-bit host running 32-bit software it's really a 32-bit OS which you can check with the Kudu tool.

[32-bit]:
~~~
D:\home>set PROCESS
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2d07
~~~

[64-bit]:
~~~
D:\home>set PROCESS
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2d07
~~~

If you fix the process architecture, this will fix the `spawn UNKNOWN` error.

**Comment by arjunpeddi** [comment]
I see this as closed thread. I am still facing same issue. tried with no sandbox, executable path etc. 
Does anyone have solution for this? Please let me know if any.
![image](https://user-images.githubusercontent.com/28701447/36274169-c5c95e58-123b-11e8-990b-523651040d4e.png)

**Comment by arjunpeddi** [comment]
So, In future, Is there any support for Puppeteer on Azure?

**Comment by leidegre** [comment]
@arjunpeddi unfortunately no.

https://github.com/Azure/azure-functions-host/issues/2417#issuecomment-366043565

This is an issue with the Azure Functions environment, official explanation in link above.

**Comment by leidegre** [comment]
I should add this.

Microsoft has something they call Azure Service Fabric, it can run containers. They will also make this a fully managed service. i.e. no VM hassle.

You can run puppeteer within such a container, no problem.

The Azure Function runtime also has a preview support for Linux. You should try this. I haven't but I recon it will work.

However, if you intend to run puppeteer/chrome headless on Windows specifically, I think your only option is Azure Service Fabric.

**Comment by RivaCode** [comment]
Or just use ACI (Azure container instances).

- Wrap your pptr into a docker (you need some index.js to start your http server and re-route the requests to pptr inside the docker using http-proxy) and upload the docker to ACI, 

- Use Azure-Mngt SDK instantiate the container instance

- Use pptr without installing chromium (you need to pass a flag) or install pptr-core

- In your function, connect pptr using **connect** function,  passing it your ACI instance IP and PORT to **browserWSEndpoint** options, in following format **ws://{ACI_IP}:{ACI:PORT}**

- your pptr is good to go

- **DO NOT** forget to use Azure-Mngt SDK to stop/delete the instance once you are done, cause your are billed by instance execution (in seconds)

**Comment by ghost** [comment]
> had same problem and tried to use linux as ops (while you create your web app or web app for container select linux instead of windows )
> this solved first part of the problem (it took you out of sandbox restrictions) after that select built -in runtime for your app (in my case selected node 8.x) and deployed it.
> 
> at that point I have to install missing necessary shared library dependencies for chrome.
> [Running Puppeteer in Docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)
> 
> just use web ssh and install those deps maually
> 
> `wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\ sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\ apt-get update &&\ apt-get install -y google-chrome-unstable`
> 
> now everything ready to use Headless Chrome with Puppeteer but one more gotcha in your code need to be done,
> chrome has to be launched with no-sanbox flags
> 
> `let browser = await puppeteer.launch({ args: [ '--no-sandbox', '--disable-setuid-sandbox' ] });`
> 
> this is the only workaround i could find, hope that helps to someone

**Comment by ghost** [comment]
I have same issue, i am on Azure linux, i am running this below command on webssh,in my /home/site/wwwroot .it is through a error like 
Warning: apt-key output should not be parsed (stdout is not a terminal)
-bash:  sh: command not found
-bash: OK: command not found
can you please help how to run this below command

`wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\ sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\ apt-get update &&\ apt-get install -y google-chrome-unstable`

**Comment by rajvith** [comment]
> I have same issue, i am on Azure linux, i am running this below command on webssh,in my /home/site/wwwroot .it is through a error like
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> -bash: sh: command not found
> -bash: OK: command not found
> can you please help how to run this below command
> 
> `wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\ sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\ apt-get update &&\ apt-get install -y google-chrome-unstable`

I am running into the same issue. were you able to solve this issue?
