### ISSUE TITLE
[CI] Run unit tests against Firefox Nightly

### ISSUE THREAD

**Issue by mjzffr** [puppeteer/puppeteer#5150]
(This depends on https://github.com/GoogleChrome/puppeteer/pull/5137)

Currently unit tests are run against the "Juggler" Firefox build together with the experimental puppeteer-firefox package. Let's also run the same unit tests against Firefox Nightly to test its [remote agent](https://wiki.mozilla.org/Remote), which is in active development.

**Comment by mathiasbynens** [comment]
Once this is done, we can start thinking about deprecating/removing the Juggler implementation in favor of the new approach in #5137.
