### ISSUE TITLE
Need to check 'aria-expanded' attribute of Xpath element

### ISSUE THREAD

**Issue by warnakey** [puppeteer/puppeteer#5155]
- Node version: v8.12.0
- Puppeteer version: 2.0.0
- Platform / OS version: Windows 10 Home, Version 10.0.18362 Build 18362 (I also test on a macbook sometimes)

----

I am trying to check to see if a box in the backend of a WordPress website is expanded or collapsed, however, I am having a lot of trouble.

Here is what the HTML looks like.

`<div id="wpseo_meta" class="postbox closed yoast wpseo-metabox">`
`    <button type="button" class="handlediv" aria-expanded="false">`
`    <span class="screen-reader-text">Toggle panel: Yoast SEO</span>`
`    <span class="toggle-indicator" aria-hidden="true"></span>`
`</button>`

I want to scrape that button and know what the value of the "aria-expanded" attribute is. (If its false, I will click the button to expand, if its true, I'll do nothing). I have to target this with Xpath because there are multiple buttons with the class 'handlediv' on the page.

What I am looking for is something that will look at that aria-expanded value on each page, then spit out either true or false.  var isBoxExpanded  == false.

Here is what I have tried so far:

`var element = await page.$x('//div[contains(@class, "wpseo-metabox")]/button[contains(@class, "handlediv")]');`
`var isYoastExpanded = await element.getAttribute("aria-expanded").jsonValue();`

The value of the first line is 'JSHandle@node' (which is no help to me), but the 2nd line fails and gives me the following error message:

> (node:16872) UnhandledPromiseRejectionWarning: TypeError: element.getAttribute is not a function
>     at line 2
>     at < anonymous >
>     at process._tickCallback (internal/process/next_tick.js:189:7)
> (node:16872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:16872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What can I do to get the value of that aria-expanded attribute?

**Comment by kblok** [comment]
You could do this

```js
var isYoastExpanded = await element.evaluate(el => el.getAttribute('aria-expanded'));
```

**Comment by warnakey** [comment]
Hi @kblok - that didn't work for me either, but thank you for replying. Maybe there is something else I could try.

![not-a-function](https://user-images.githubusercontent.com/16696576/68770022-62bd8200-05f3-11ea-9b45-552b5c27fe73.png)

**Comment by kblok** [comment]
Sorry, `$x` returns an array. `element[0]` should work.

**Comment by warnakey** [comment]
Could you show me how to implement that `element[0]` into my example code above? I'm unsure where that part goes. Thanks!

**Comment by kblok** [comment]
```js 
var element = await page.$x('//div[contains(@class, "wpseo-metabox")]/button[contains(@class, "handlediv")]');
var isYoastExpanded = await element[0].evaluate(el => el.getAttribute('aria-expanded'));
```

**Comment by warnakey** [comment]
That worked!

Thank you @kblok for being the true MVP.  🥇
