### ISSUE TITLE
Screenshots of really long pages

### ISSUE THREAD

**Issue by InvincibleDRT** [puppeteer/puppeteer#5157]
I have a really long page that i would like to take screenshot of without scrollbars. Right now all i am getting is whats visible on the page with

```
        await page.screenshot({
            path: `${Math.floor(Math.random() * 100)}.png`,
            fullScreen:true
        });
```

Is there any way to get the entire page content in the screenshot

**Comment by sr258** [comment]
Try

```
    await page.screenshot({
            path: `${Math.floor(Math.random() * 100)}.png`,
            fullPage: true
        });
```

**Comment by InvincibleDRT** [comment]
tried that! didnt work.... i disabled defaultviewport on launch and it started work as expected with clip param for screenshot

**Comment by ajain-bst** [comment]
I am having a similar issue.
However, for me, the `clip` param still leads to an internal server error, despite `defaultViewport` being set to `null`.

This is how I am setting the param:

```
"clip": {
		"x": 0,
		"y": 0,
		"width": 100,
		"height": 100
	}
```

Any ideas?

**Comment by InvincibleDRT** [comment]
There is additional params that you need to fill in when you use default viewport null. I think it's ismobileview or something like that
