### ISSUE TITLE
addScriptTag id

### ISSUE THREAD

**Issue by stevenvachon** [puppeteer/puppeteer#5166]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOS 10.15.1
* URLs (if applicable):
* Node.js version: 12.13.0

**What steps will reproduce the problem?**
```js
const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage();

await Promise.all([
    page.addScriptTag({
        content: someFunction.toString(),
        id: 'my-helpers'
    }),
    page.coverage.startJSCoverage({ reportAnonymousScripts: true })
]);

const coverage = await page.coverage.stopJSCoverage()
    .filter(({id}) => id !== 'my-helpers');
```
The goal is to filter `<script>` elements (containing helpers) from code coverage.

**What is the expected result?**
`id` attribute is added to the resulting `HTMLScriptElement`.

**What happens instead?**
Nothing. This is a feature request.

**Comment by noam3127** [comment]
This feature would be very useful for me as well. I don't mind making a PR if there's enough interest.

**Comment by rickhernandezio** [comment]
This would be great!
