### ISSUE TITLE
ReferenceError: cov_1hphpf4qcw is not defined

### ISSUE THREAD

**Issue by frantallukas10** [puppeteer/puppeteer#5175]
I have problem create test for my function
![image](https://user-images.githubusercontent.com/16817166/68999377-9a604e80-08bf-11ea-81ec-47869e7c183c.png)
here is my project https://github.com/frantallukas10/youtu-get
I try to create test for my function where I use puppeteer for get every title and id from youtube playlist
here is my test: https://github.com/frantallukas10/youtu-get/blob/master/tests/test.js
and here is my function: https://github.com/frantallukas10/youtu-get/blob/master/src/main.js

thank you for your help or information... =)

**Comment by kblok** [comment]
Can you point us to the evaluate call that is failing?

**Comment by frantallukas10** [comment]
> Can you point us to the evaluate call that is failing?

when I run my function everything work properly. My result is correct. but If I try to test my function I have the issue

**Comment by kblok** [comment]
Your code coverage tool is injecting code

```js 
console.log node_modules/puppeteer/lib/ExecutionContext.js:108
    () => {
          /* istanbul ignore next */
          cov_npcpcae6x.f[2]++;
          cov_npcpcae6x.s[19]++;
          window.scrollTo(0, document.getElementsByTagName('ytd-app')[0].getBoundingClientRect().height);
        }
    //# sourceURL=__puppeteer_evaluation_script__
```

That code is being sent and executed in Chromium. On the browser side, `cov_npcpcae6x` doesn't exist.

**Comment by frantallukas10** [comment]
thank you for your help!
how can I fix it? can I use another function from puppeteer? I need scroll down if all songs are not visible in YouTube playlist I can use another function for scroll down but I don't think that it will fix it

**Comment by kblok** [comment]
@frantallukas10 They talk about that here https://github.com/facebook/jest/issues/7962 and here https://github.com/facebook/jest/issues/6793

As a workaround, you can also send the function as a string, so no one gets in the middle.

**Comment by frantallukas10** [comment]
> Your code coverage tool is injecting code
> 
> ```js
> console.log node_modules/puppeteer/lib/ExecutionContext.js:108
>     () => {
>           /* istanbul ignore next */
>           cov_npcpcae6x.f[2]++;
>           cov_npcpcae6x.s[19]++;
>           window.scrollTo(0, document.getElementsByTagName('ytd-app')[0].getBoundingClientRect().height);
>         }
>     //# sourceURL=__puppeteer_evaluation_script__
> ```
> 
> That code is being sent and executed in Chromium. On the browser side, `cov_npcpcae6x` doesn't exist.

I trying

**Comment by frantallukas10** [comment]
`testPathIgnorePatterns`  helped me with my issue https://jestjs.io/docs/en/configuration#testpathignorepatterns-arraystring
I exported every puppeteer evaluate methods from file and added to `testPathIgnorePatterns` config

**Comment by frantallukas10** [comment]
maybe it will be better add this information for this error... @kblok

**Comment by pgoos** [comment]
@kblok could you elaborate on sending the function as a string, maybe with an example?
Right now the only workaround that I see is @frantallukas10 approach to add every file that uses `evaluate` methods into jest config property `testPathIgnorePatterns`

**Comment by kblok** [comment]
@pgoos the jest team added an explanation in their docs :) https://jestjs.io/docs/puppeteer

**Comment by dutscher** [comment]
`/* istanbul ignore next */` above `await page.evaluate(() => {` is this, which works to avoid `ReferenceError: cov_2lob143fxt is not defined`

thanks @Barzou
