### ISSUE TITLE
request.postData()  returns undefined

### ISSUE THREAD

**Issue by z1988hf** [puppeteer/puppeteer#5178]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:2.0.0
* Platform / OS version:win7 64 bits
* URLs (if applicable):
* Node.js version:10.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.   const loginRequest = loginResponse.request();
2.  let requestBody = JSON.parse(loginRequest.postData());

**What is the expected result?**
loginRequest.postData() return a string representing data posted.

**What happens instead?**
postData() returns undefined. 

This issue doesn't exist in puppeteer 1.2.0. But after I upgraded puppeteer to 2.0.0, it happens like this.

**Comment by kblok** [comment]
Can you make a [test like this](https://github.com/GoogleChrome/puppeteer/blob/8f8e77492dd91a00d53965b998b4199bcc5e29a3/test/network.spec.js#L143) so we can test?

**Comment by z1988hf** [comment]
> Can you make a [test like this](https://github.com/GoogleChrome/puppeteer/blob/8f8e77492dd91a00d53965b998b4199bcc5e29a3/test/network.spec.js#L143) so we can test?

const puppeteer = require('puppeteer');
var expect = require('chai').expect;

describe('Request.postData', async function () {
  this.timeout(50000);
  it('should work', async (done) => {
    const browser = await puppeteer.launch({
      headless: false
    });
    const page = (await browser.pages())[0];
    var http = require('http');

    server = http.createServer(function (req, res) {
      res.writeHead(200, { 'Content-Type': 'text/plain' });
      res.end('Hello, world!\n');
    }).listen(8080);
    page.goto('http://localhost:8080');
    let loginResponsePromise = page.waitForResponse(response => {
      return response.request().url().startsWith('http://localhost');
    });
    page.evaluate(() => fetch('http://localhost:8080/aa', { method: 'POST', body: JSON.stringify({ foo: 'bar' }) }));
    let response = await loginResponsePromise;
    let request = response.request()
    console.log(request.postData())
    expect(request.postData()).to.equal('{"foo":"bar"}');
    done();
  });
});

**Comment by kblok** [comment]
The problem with your example is that you are not awaiting the `goto`, and the `waitForResponse` is too generic, so it's returning the `goto`'s response.
It worked for me doing this change:

```js 
await page.goto('http://localhost:8080');
let loginResponsePromise = page.waitForResponse(response => {
  return response.request().url().startsWith('http://localhost:8080/aa');
});
```

**Comment by z1988hf** [comment]
> The problem with your example is that you are not awaiting the `goto`, and the `waitForResponse` is too generic, so it's returning the `goto`'s response.
> It worked for me doing this change:
> 
> ```js
> await page.goto('http://localhost:8080');
> let loginResponsePromise = page.waitForResponse(response => {
>   return response.request().url().startsWith('http://localhost:8080/aa');
> });
> ```

Thanks very much. I figured it out. Puppeteer 2.0.0 counts browser OPTIONS request while puppeteer 1.2.0 doesn't. So the response actually is browser OPTIONS request's response. Then request.postData() is undefined. I added **response.request().method() == 'POST';** then it works fine as before. 


const puppeteer = require('puppeteer');
var expect = require('chai').expect;

describe('Request.postData', async function () {
  this.timeout(50000000);
  it('should work', async (done) => {
    const browser = await puppeteer.launch({
      headless: false
    });
    const page = (await browser.pages())[0];
    var http = require('http');

    server = http.createServer(function (req, res) {
      if(req.url == 'http://localhost:8080/' || req.method == 'OPTIONS') {
        res.writeHead(200, { 'Content-Type': 'text/plain',
        'Access-Control-Allow-Origin':'*',
        'Access-Control-Allow-Headers': 'Content-Type'
       });
       res.end('Hello, world!\n');
      } else {
        res.writeHead(403, { 'Content-Type': 'text/plain',
       });
       res.end('Hello, world!\n');
      }
    }).listen(8080);
    await page.goto('http://localhost:8080/');
    let loginResponsePromise = page.waitForResponse(response => {
      return response.request().url().startsWith('http://contoso.com:8080/aa') && response.request().method() == 'POST'; // contoso.com points to 127.0.0.1 in hosts file
    });
    console.log('evaualte');
    page.evaluate(() => {
      var xmlhttp=new XMLHttpRequest();
      xmlhttp.open("POST", 'http://contoso.com:8080/aa' , true);
      xmlhttp.setRequestHeader("Content-type","application/json");
      xmlhttp.send(JSON.stringify({ foo: 'bar'}));
    });
    let response = await loginResponsePromise;
    console.log('response');
    let request = response.request()
    console.log(request.headers())
    console.log(response.status())
    expect(request.postData()).to.equal('{"foo":"bar"}');
    done();
  });
});

**Comment by z1988hf** [comment]
Figured out. It is not a bug.

**Comment by qingyangqiang** [comment]
According to what you said, I still return undefined, I hope to get an answer, thank you
  page.on("request",(httpRequest) => {
        let url = httpRequest.url();
        if (url.includes("n.gif")){
            if (httpRequest.method() === "POST"){
                console.log("xxxxx",httpRequest.postData())
            }
            httpRequest.continue()
        }else {
            httpRequest.continue()
        }
    })

**Comment by ggorlen** [comment]
I'm also a bit surprised by an undefined on `request.postData()` for JSON content types. Here's a minimal example:

```js
const puppeteer = require("puppeteer"); // ^13.5.1

const html = `
<body>
<script>
fetch("https://jsonplaceholder.typicode.com/todos", {
  method: "POST",
  body: JSON.stringify({foo: "bar"})
});
</script>
</body>
`;

let browser;
(async () => {
  browser = await puppeteer.launch({headless: true});
  const [page] = await browser.pages();
  const responsePromise = page.waitForResponse(response =>
    response.url() === "https://jsonplaceholder.typicode.com/todos"
  );
  await page.setContent(html);
  const response = await responsePromise;
  console.log(response.request().postData()); // => foo=bar
})()
  .catch(err => console.error(err))
  .finally(() => browser?.close())
;
```

The above code works as expected, logging `foo=bar`. But change the fetch code to:

```js
fetch("https://jsonplaceholder.typicode.com/todos", {
  method: "POST",
  headers: {
    "Accept": "application/json",
    "Content-Type": "application/json"
  },
  body: JSON.stringify({foo: "bar"})
});
```

while leaving the Puppeteer code the same and you'll see `undefined` logged. The culprit/delta seems to be `"Content-Type": "application/json"`.

**Comment by ggorlen** [comment]
I should have read the thread a bit more carefully, as [this answer](https://github.com/puppeteer/puppeteer/issues/5178#issuecomment-555801365) pretty clearly shows that ensuring the request method is POST will avoid an OPTIONS request taking over:

```js
const responsePromise = page.waitForResponse(response =>
  response.url() === "https://jsonplaceholder.typicode.com/todos" &&
  response.request().method() === "POST"
);
```

**Comment by hyl** [comment]
This is a bug that I also have experienced when using request interception: POST requests that are the result of an `OPTIONS` have an undefined return from `postData()`.

We have found that you can use the `client` object on the request to get the request post data directly via CDP:

```
const cdpBody = await request.client.send('Network.getRequestPostData', {requestId: request._requestId});
```
