### ISSUE TITLE
Chromium randomly crashes when popup is opened on the specific website

### ISSUE THREAD

**Issue by ssut** [puppeteer/puppeteer#5181]
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v2.0.0
* Platform / OS version: Windows 10 x64 1903
* URLs (if applicable): www.iros.go.kr
* Node.js version: v12 LTS

**What steps will reproduce the problem?**

I've just tried to click the button that triggers to open a popup on that website, and then it leads to crash the webpages including both the parent page and the popup.

The chromium launchOptions are as follows:

```
{
  executablePath: ...,
  args: [
    '--disable-gpu',
    '--disable-web-security',
    '--disable-popup-blocking',
    '--no-sandbox',
  ],
  headless: false,
  ignoreDefaultArgs: true,
}
``` 

**What is the expected result?**
**What happens instead?**

Expected no crashes at all. It was totally fine with the previous releases of puppeteer I've used before. (I recently updated the puppeteer version from v1.12.0 to v2.0.0.)

![image](https://user-images.githubusercontent.com/2366668/69119303-7f692680-0ad9-11ea-978c-131d61ceb684.png)

Please let me know if I did something wrong with launchOptions or else, otherwise let me know if there is an issue that is related to popup handling using puppeteer. I also submitted the crash report on `chrome://crashes`, the localcontext crash ID is `dc6ee664-2a06-4d66-a56f-0d36e8b0fe6b`.

+ Add:

I found '[Issue 1026053: Chrome Crashes when navigating before fully loaded](https://bugs.chromium.org/p/chromium/issues/detail?id=1026053&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)', and I think this issue may be related to that.

**Comment by ssut** [comment]
I temporarily solved this issue by using the previous chromium release. (in this case r686378.) after the downgrade, this issue never happens again so far.

**Comment by taewookim** [comment]
how did you do the downgrade?

**Comment by ssut** [comment]
@taewookim check the launchOptions. There is an option to set the executable path.
