### ISSUE TITLE
How to get the details in Network tab of DevTools?

### ISSUE THREAD

**Issue by InvincibleDRT** [puppeteer/puppeteer#5183]
I would like to record details of requests in Netword tab from puppeteer to a file. Is there a way to do that? 

Thanks!

**Comment by kblok** [comment]
[tracing](https://github.com/GoogleChrome/puppeteer/blob/v2.0.0/docs/api.md#tracingstartoptions) returns lots of information.

**Comment by InvincibleDRT** [comment]
Thanks! i will explore that...I was trying to record total lag of each request (db + server side rendering)

**Comment by kblok** [comment]
It won't be as pretty as in the network tab, but I bet all the info will be there.

**Comment by mathiasbynens** [comment]
The DevTools network panel is a visualization of this exact same data. So yes, if the raw data is what you want, then [`tracing.*`](https://github.com/GoogleChrome/puppeteer/blob/v2.0.0/docs/api.md#tracingstartoptions) is what you're looking for. +@sigurdschneider

**Comment by InvincibleDRT** [comment]
Is there any way to get just the XHR requests information to tracing. right now tracing has so much stuff and it cannot be imported to devtools in chrome

**Comment by UnforbiddenYet** [comment]
@InvincibleDRT it seems this functionality has been added to Puppeteer 2.0:

From the [docs](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#class-tracing):
> You can use tracing.start and tracing.stop to create a trace file which can be opened in Chrome DevTools or timeline viewer.

**Comment by Lancelight** [comment]
How can this be imported into DevTools if DevTools only accepts HAR files and not JSON?

![image](https://user-images.githubusercontent.com/7891142/152428149-a8235daf-5d4b-4f58-9d93-499445ab08de.png)
