### ISSUE TITLE
Drop Node.js 8 support

### ISSUE THREAD

**Issue by mathiasbynens** [puppeteer/puppeteer#5186]
Per https://github.com/nodejs/Release#release-schedule, Node.js 8 reaches EOL at December 31st, 2019. We should then drop support for Node.js 8 in Puppeteer.

- [ ] Update CI configurations
- [ ] Leverage modern JS features in source code where applicable. Some features that Node.js v10 has that weren't in Node.js v8 are RegExp named capture groups, Unicode property escapes, async generators, `for`-`await`-`of`, one-sided string trimming, and optional catch binding.

**Comment by mathiasbynens** [comment]
@hanselfmu Do you want to take a look? :)

**Comment by hanselfmu** [comment]
Yes no problem :)

**Comment by J-Palomino** [comment]
Does this mean it's a bad idea to try and run puppeteer on a codebase with newest node version being v8.12.0? If so how would one begin to execute that bad idea? 🤔
