### ISSUE TITLE
intermittent values - getAttribute returning string then returning null

### ISSUE THREAD

**Issue by inspiraller** [puppeteer/puppeteer#5189]
### Steps to reproduce

# environment
* Puppeteer 2.0.0
* Windows 10
* node 10.15.3

# steps

mytest.js
```
const { expect } = require("chai");
const puppeteer = require('puppeteer');

const gotoWebsite = (async (url) => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(url);
  const alt = await page.$eval('.fb_logo', el => (
    el.getAttribute('alt')
  ));
  console.log('alt = ', alt);
  expect(alt).to.eql('Facebook');
  await browser.close();
});

gotoWebsite('https://www.facebook.com');
```

**What is the expected result?**
Every test should console log - "Facebook" as that is the alt tag of the image.

**What happens instead?**
Sometimes the console log is null, and sometimes it is "Facebook"

**Comment by pavloKozlov** [comment]
If you open `https://www.facebook.com` in browser multiple times using different incognito tabs every time, you'll quickly realize that sometimes you're getting different html pages.
If you execute `document.querySelector('.fb_logo')` in developers console, for some pages, it returns an `<img>` element with attribute `alt` (in this case output of code sample is 'Facebook') (screenshot 1 and 2) and for some other pages it's an `<i>` element without `alt` attribute so sample code outputs `null` (screenshot 3).
So it's an issue not with the puppeteer but with web page itself.

<img width="1396" alt="Screenshot 2019-12-01 at 22 05 59" src="https://user-images.githubusercontent.com/1263270/69920487-efd45800-1488-11ea-9d7b-75c0d2f471dc.png">
<img width="1392" alt="Screenshot 2019-12-01 at 22 06 18" src="https://user-images.githubusercontent.com/1263270/69920490-f4007580-1488-11ea-89c3-da7161709c3b.png">
<img width="1401" alt="Screenshot 2019-12-01 at 22 05 43" src="https://user-images.githubusercontent.com/1263270/69920486-e9de7700-1488-11ea-9128-091edf81ffee.png">
