### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by shryta234** [puppeteer/puppeteer#5190]
Hello,

I'm trying to run a node.js script in Ubuntu, but I'm getting below error.
**Specification:-**
npm  = 6.12.1
node  = v13.1.0
Puppeteer = v1.20.0
Chromium-browser  = 65.0.3325.181 
OS =  Ubuntu 14.04.3 LTS

**Error :-**
kkadapa@homn:/vc-devgh-checkouts-1/screenshots$ node index.js 
Error: Failed to launch chrome!

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/vc-devgh-checkouts-1/screenshots/node_modules/puppeteer/lib/Launcher.js:348:14)
    at ChildProcess.<anonymous> (/vc-devgh-checkouts-1/screenshots/node_modules/puppeteer/lib/Launcher.js:338:60)
    at ChildProcess.emit (events.js:215:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:23327) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'newPage' of undefined
    at /vc-devgh-checkouts-1/screenshots/index.js:79:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:23327) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23327) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andreabisello** [comment]
@shryta234 can you share your code?

**Comment by jrandolf-google** [comment]
We no longer support Node < 14, please try this again with the latest version of Puppeteer and Node >= 14. If the issue still occurs, please reopen this issue and update the description :)
