### ISSUE TITLE
Generate pdf from dynamically loaded html via `setContent` doesn't load css resources.

### ISSUE THREAD

**Issue by jamil-alisgandarov** [puppeteer/puppeteer#5191]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.2
* Platform / OS version: MACOS
* URLs (if applicable):
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. I am generating html via `ejs`
2. Creating new page
3. `page.setContent(providedHtml)`
4. Generating pdf using `page.pdf`

**What is the expected result?**
CSS resources and imgs are not loaded.

**What happens instead?**
As I can see `setContent` using `document.write` in the background. But I need the page to load all resources provided in `html` when `setContent` is called. 

Github repo (example code):
https://github.com/jamil-alisgandarov/pdf-generator

```typescript
 public createPdf = async (
        templatePath: string,
        data: any
    ) => {
        const { page } = await this.getBrowserIntance();
        const html = await generateHtml(templatePath, data);

        await page.setContent(html, { waitUntil: ['load', 'domcontentloaded', 'networkidle0', 'networkidle2'] });

        const pdf = await page.pdf({ path: 'test.pdf' });

        page.close();

        return pdf;
    }
```

I asked question a few weeks ago in stackoverflow, but couldn't get any idea how can I force the page to load resources provided in `html`.  **Any ideas how can I do it?**

**Comment by kblok** [comment]
Where are the resources located? How are you referencing those in the HTML? Do you have any code example to test?

**Comment by jamil-alisgandarov** [comment]
@kblok  I have provided link in desc.

**Comment by kblok** [comment]
You will most likely get help if you share a little piece of code instead of a repo link.

**Comment by jamil-alisgandarov** [comment]
**Solved**

Created html file and redirected page to there using `page.goto`
