### ISSUE TITLE
Virtual scrolling. ElementHandle._clickablePoint: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by DJ-Glock** [puppeteer/puppeteer#5194]
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Windows 10
* URLs (if applicable): -
* Node.js version: v10.16.0

**What steps will reproduce the problem?**
Unfortunately I was not able to reproduce the issue using the same code and public website. I can only reproduce the issue using our internal project. Please let me know what information can I provide about our webpage to help you to identify the issue.

We have React website with a dropdown list with virtual scrolling. It works almost the same as Twitter, youtube scrollings. 
I wrote a function for searching for a desired list element (by selector) in the list. Algorythm is pretty simple:
1. Check if element exists by selector (if yes - exit)
2. Get all list elements by a wildcard selector.
3. Scroll to the last element using **hover** method. This will launch regeneration of visible list elements. New elements will be loaded, part of the old ones - removed.
4. Check if element exists by selector (if yes - exit)
5. End of the list? If not - go to 1, if yes - exit.

**What is the expected result?**
Hover method should work with no exceptions.

**What happens instead?**
The first iteration works fine. It scrolls to last element, no issues.
But the second iteration fails:
```
 Error: Node is either not visible or not an HTMLElement
  at ElementHandle._clickablePoint (D:\...\node_modules\puppeteer\lib\JSHandle.js:217:13)
-- ASYNC --
  at ElementHandle.<anonymous> (D:\...\node_modules\puppeteer\lib\helper.js:111:15)
  at ...scrollToSelector (D:\...\src\Pages\BasePageObject.ts:170:25)
```
Error occurs during an execution of _clickablePoint method which is part of hover method:
```
  async hover() {
    await this._scrollIntoViewIfNeeded();
    const {x, y} = await this._clickablePoint();
    await this._page.mouse.move(x, y);
  }
```
I am not allowed to share any plain source code. Problematic list looks like this:
![node_not_visible](https://user-images.githubusercontent.com/26511191/69636790-71328180-1068-11ea-91ae-4fdce1bde9dd.png)

I assume that issue might be caused by new version of Puppeteer/Chromium or because of DOM.getContentQuads. We did not face this issue before upgrading puppeteer to 2.0.0
Another interesting thing is that I am able to reproduce the issue locally in debug/headless modes every time. But when we run our tests in the TeamCity, using docker, most of the times everyting works fine. No exceptions.

I was thinking about the following workaround:
Extending JSHandle class with a simple scrollToView method, which will just scroll to element, without calling _clickablePoint. Unfortunately I faced another [issue with](https://stackoverflow.com/questions/59047535/typescript-extending-third-party-class-error-jshandle-only-refers-to-a-type-bu) TypeScript.

Please find below code. I have amended it to be project independent (only mocha required) and added example with twitter.com. It works with no isues.

```
import { ElementHandle, launch } from 'puppeteer';

describe('Google test.', () => {
  it('Google scrolling test', async () => {
    const opts = {
      dumpio: false,
      headless: false,
      slowMo: 100,
      timeout: 0,
      defaultViewport: null,
      args: [
        '--start-maximized',
        '--window-size=1920,1080',
        '--enable-logging',
      ],
    };

    const browser = await launch(opts);
    const [first] = await browser.pages();
    const page = first || (await browser.newPage());

    // Twitter - good example
    await page.goto("https://twitter.com/google", { waitUntil: "networkidle2" });
    const wildcardSelector = '[data-item-type="tweet"]'
    const selector = `[data-tweet-id="1156246828444278786"]`

    await page.waitFor(3000);

    const direction = "Down";
    console.log(
      `Going to scroll list ${direction} using wildcard selector ${wildcardSelector} until selector ${selector} is found.`
    );
    let elementExists = await page.$(selector)
    let previousLastElement: ElementHandle<Element> | undefined = undefined;
    while (!elementExists) {
      const elements = await page.$$(wildcardSelector);
      let lastElement: ElementHandle<Element>;
      if (direction === "Down") {
        lastElement = elements[elements.length - 1];
      } else {
        lastElement = elements[0];
      }

      await lastElement.hover();
      elementExists = await page.$(selector);

      if (lastElement === previousLastElement || elementExists) {
        break;
      } else {
        previousLastElement = lastElement;
      }
    }

    const element = await page.$(selector);
    const text = (await page.evaluate(e => e.textContent, element)) as string;
    console.log(text); // `Congratulations to all of the #GoogleScienceFair finalists!`);
  });
});
```

Any help will be much appreciated!

**Comment by DJ-Glock** [comment]
As a workaround I have implemented my own scrolling func based on scrollIntoView:

```
  public async scrollElementIntoView(
    element: ElementHandle<Element>,
    block: 'start' | 'center' | 'end' | 'nearest' = 'center',
    inline: 'start' | 'center' | 'end' | 'nearest' = 'nearest',
    behavior: 'auto' | 'smooth' = 'auto'
  ) {
    const error = await this.currentPage.evaluate(
      async (element, block, inline, behavior) => {
        if (!element.isConnected) return 'Node is detached from document';
        if (element.nodeType !== Node.ELEMENT_NODE) return 'Node is not of type HTMLElement';

        const visibleRatio = await new Promise(resolve => {
          const observer = new IntersectionObserver(entries => {
            resolve(entries[0].intersectionRatio);
            observer.disconnect();
          });
          observer.observe(element);
        });
        if (visibleRatio !== 1.0)
          element.scrollIntoView({ block, inline: inline, behavior: behavior });
        return false;
      },
      element.asElement(),
      block,
      inline,
      behavior
    );
    if (error) throw new Error(error);
  }
```

It works fine.

**Comment by rduboveckij** [comment]
I have a similar problem and after debugging I found that scroll is too slow. It is because 
`* {scroll-behavior: smooth;}`, but I thought JShandle should cover that case in
`element.scrollIntoView({block: 'center', inline: 'center', behavior: 'instant'});`
but it does not work like that. So I found a workaround for my self
`await this.page.addStyleTag({content: '* {scroll-behavior: unset}'});`
