### ISSUE TITLE
Return value from window event back to puppeteer

### ISSUE THREAD

**Issue by puneetas3** [puppeteer/puppeteer#5198]
A part of my code is this-	
	
```
	await page.exposeFunction('onCustomEvent', text => console.log(text));
	
	const content = await page.evaluate(() => {		
document.querySelector('iframe[src*="api"]').contentWindow.document.addEventListener("DOMSubtreeModified", function(e) {
			if(e.target.querySelector('.content')){
				if(e.target.querySelector('.content').innerText.includes('Top Coverage')) {
					window.onCustomEvent('Available');
				}
			}
		});
	});
	
	console.log(content);  //I want to return 'Available'
```

I am looking to return(not just output to console) the value 'Available' from windows event to puppeteer. How do I achieve this. I tried stackoverflow, but couldn't get clear idea on postmessage.

**Comment by kblok** [comment]
You could use a `Promise`. Something like

```js
const promise = new Promise(x => fulfill = x);
await page.exposeFunction('onCustomEvent', text => fulfill(text));
//More code
const content = await promise;
console.log(content);
```

**Comment by puneetas3** [comment]
@kblok thanks for the quick reply mate. I am not able to figure it out (new with this stuff) completely. How do I include my eventlistener code into your code. Regards

**Comment by puneetas3** [comment]
> You could use a `Promise`. Something like
> 
> ```js
> const promise = new Promise(x => fulfill = x);
> await page.exposeFunction('onCustomEvent', text => fulfill(text));
> //More code
> const content = await promise;
> console.log(content);
> ```

Thanks @kblok for quick response. I would like to provide more information on the actual code. The code solves audio recaptcha here https://www.google.com/recaptcha/api2/demo

```js
await page.waitForFunction(() => {
    const iframe = document.querySelector('iframe[src*="api2/bframe"]')
    if (!iframe) return false
    return !!iframe
})

const promise = new Promise(x => fulfill = x);
await page.exposeFunction('onCustomEvent', text => fulfill(text));

//More code
await page.evaluate(() => {
    document.querySelector('iframe[src*="api2/bframe"]').contentWindow.document.addEventListener("DOMSubtreeModified", function(e) {
        if (e.target.querySelector('.rc-doscaptcha-body-text')) {
            if (e.target.querySelector('.rc-doscaptcha-body-text').innerText.includes('Your computer or network may be sending automated queries')) {
                var a = 'block';
                window.onCustomEvent(a);
            }
        }
    });
});

const content = await promise;
console.log(content);  //return content and exit from code

//=========Step 1 - Click Captcha checkbox=================  
await clickCaptchaCheckbox(page)
//============End Step 1 - Click Captcha checkbox===============

//=============Step 2 - Click Audio Captcha link===============
await clickAudioCaptchaLink(page)
//============End Step 2 - Click Audio Captcha link==============

//============Step 3 - Submit Audio Captcha=================
await submitAudioCaptcha(page, 1)
//============End Step 3 - Submit Audio Captcha=================

//============Step 4 - Verify Captcha Success=================
const result = await verifyCaptchaSuccess(page)
//============End Step 4 - Verify Captcha Success=================

return result;
```

The iframe with src="api2/bframe" will load on page load. Its inner class ".rc-doscaptcha-body-text" is loaded conditionally if recaptcha block us, else it will not load. DOMSubtreeModified is listening when this class is added in iframe.

So the above promise is stuck indefinitely if there is no class ".rc-doscaptcha-body-text" and won't execute functions below it (Step 1,2,3 and 4). I can successfully submit captcha if I start with Step 1, but than there is no mechanism to check edge case of blocking.

I want to be able to listen to block event, while the below code (Step 1,2,3 and 4) keeps running. I hope I am making sense. Is it possible to point me in the right direction. Regards
