### ISSUE TITLE
page.setUserAgent is not quite working

### ISSUE THREAD

**Issue by dsheiko** [puppeteer/puppeteer#5199]
The methods really sets the user-agent for navigator.userAgent, but page.goto request doesn't pass it with headers.

I'm using the following code
```javascript
const browser = await puppeteer.launch({
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox'
        ]
    });

const page = await browser.newPage();
await page.setUserAgent( "Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox; Xbox One) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063" );
await page.goto('http://127.0.0.1');

console.log(await page.evaluate('navigator.userAgent'));

await browser.close();
```

Where on http://127.0.0.1 I'm running node.js server that logs the received user-agent ("koa-useragent") in a text file.

When I run the code, in the console everything is fine
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox; Xbox One) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063"

But the received user agent in the log file is 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/79.0.3945.0 Safari/537.36

what looks like Puppeteer overrides the user-agent info.

OS: Ubuntu 18
Version: puppeteer@2.0.0

**Comment by jesus6402** [comment]
@dsheiko What was the issue here? We're experiencing the same problem.

**Comment by dsheiko** [comment]
Within the project I missed Chromium arguments
```javascript
await puppeteer.launch({
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox'
        ]
    });
```
It doesn't override the UserAgent without them
