### ISSUE TITLE
elementHandle.click() doesn't work if the tab is in background

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5201]
Click doesn't work in background because intersection observer never returns `true` because intersection observer doesn't work in background tabs

`elementHandle.click()` tries to first bring element in view using internal method `_scrollIntoViewIfNeeded` which doesn't work because it uses [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). 

Code in question: https://github.com/puppeteer/puppeteer/blob/8b49dc62a62282543ead43541316e23d3450ff3c/lib/JSHandle.js#L191-L197

From API docs:
> If the intersection root is the implicit root (that is, the top-level Document), the root intersection rectangle is the viewport's rectangle.

This means that it won't work if tab is in background because then the element won't be in viewport.

But I also don't have a good suggestion on what else can we use here. Suggestions @mathiasbynens?

**Comment by kblok** [comment]
Did you try calling `click` inside an `evaluate` function?

**Comment by VikramTiwari** [comment]
Hey @kblok, `click` inside `evaluate` works, but that's not the same because of Trusted vs Untrusted events. https://github.com/puppeteer/puppeteer#q-whats-the-difference-between-a-trusted-and-untrusted-input-event

**Comment by hasse112** [comment]
So, this is still an issue.
I assume this means there is no way around it?
