### ISSUE TITLE
Svg is misplaced (down shifted to next page) in pdf when height overflow is close to page break

### ISSUE THREAD

**Issue by shivijais** [puppeteer/puppeteer#5202]
### Steps to reproduce
* Puppeteer version: 1.19.0 onwards (haven't checked with older version)
* Platform / OS version: mac OS
* URLs (if applicable):
* Node.js version: 10.11.0

**What steps will reproduce the problem?**

1. Use this html as target to generate pdf
```
<html>
<head>
    <style>
        body {
            margin: 0;
        }
        .page {
            height: 792px;
            width: 1122px;
            background-color: #fbffcd;
            outline: 2px solid red;
            page-break-after: always;
        }
        .tile {
            position: absolute;
            height: 752px;
            width: 200px;
            top: 20px;
            outline: 1px solid blue;
        }
        .tile1 {
            left: 10px;
        }
        .tile2 {
            left: 230px;
        }
        .tile3 {
            left: 450px;
        }
        .tile4 {
            left: 670px;
        }
        .tile5 {
            left: 890px;
        }
        svg {
            outline: green 2px solid;
        }
    </style>
</head>
<body>
    <div class="page">
        <div class="tile tile1">
            <svg height="772" width="200">
                <line x1="0" y1="80" x2="800" y2="600" stroke="black" />
                <text x="20" y="20">height=772</text>
            </svg>
        </div>
        <div class="tile tile2">
            <svg height="773" width="200">
                <line x1="0" y1="80" x2="800" y2="600" stroke="black" />
                <text x="20" y="20">height=773</text>
            </svg>
        </div>
        <div class="tile tile3">
            <svg height="780" width="200">
                <line x1="0" y1="80" x2="800" y2="600" stroke="black" />
                <text x="20" y="20">height=780</text>
            </svg>
        </div>
        <div class="tile tile4">
            <svg height="792" width="200">
                <line x1="0" y1="80" x2="800" y2="600" stroke="black" />
                <text x="20" y="20">height=792</text>
            </svg>
        </div>
        <div class="tile tile5">
            <svg height="793" width="200">
                <line x1="0" y1="80" x2="800" y2="600" stroke="black" />
                <text x="20" y="20">height=793</text>
            </svg>
        </div>
    </div>
    <div class="page">
    </div>
</body>
</html>
```

this html looks like -
<img width="377" alt="Screen Shot 2019-11-28 at 2 41 17 PM" src="https://user-images.githubusercontent.com/8709060/69792749-327a0400-11ed-11ea-95a5-3be8b2beaae1.png">
Red line is the page break. Blue box is the tile container. Green box is svg.

2. Generate pdf using puppeteer 
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true,
        args: ['--disable-gpu']
    });

    let page = await browser.newPage();
    await page.goto('file:///Users/path-to-the-html-above.html');
    await page.pdf({path: 'hn.pdf', format: 'A4', landscape: true});
    await browser.close();
})();
```

**What is the expected result?**
All tiles with svg should have rendered in the first page.

**What happens instead?**
svg within certain height range which overlaps with page break get shifted to next page. When using overflow:hidden, the svg doesn't show up for these boxes
<img width="379" alt="Screen Shot 2019-11-28 at 2 40 17 PM" src="https://user-images.githubusercontent.com/8709060/69792670-0d859100-11ed-11ea-9968-cddb53beadc8.png">

[hn.pdf](https://github.com/puppeteer/puppeteer/files/3900603/hn.pdf)

**Comment by kblok** [comment]
Do you get the same if you print this page to HTML using Chrome?

**Comment by shivijais** [comment]
Yes I get the same when I use print on chrome
<img width="1292" alt="Screen Shot 2019-11-28 at 7 13 29 PM" src="https://user-images.githubusercontent.com/8709060/69811041-37ea4500-1213-11ea-87c2-3d150614ba73.png">

**Comment by kblok** [comment]
@shivijais so this would be more an issue for Chromium than for Puppeteer.

**Comment by shivijais** [comment]
But it renders fine in Chrome and Chromium using print screen media.
