### ISSUE TITLE
Event 'response' doesn't trigger 

### ISSUE THREAD

**Issue by theArina** [puppeteer/puppeteer#5204]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Windows 10
* Node.js version: 2.0.0

**What steps will reproduce the problem?**

```
  browser.on('targetcreated', async target => {
    if (target.type() !== 'page') return;

    const page = await target.page();
    page.on('response', response => {
        // here goes code
    });
   });
```

So when puppeteer clicks on link and it opens in new tab, sometimes i don't receive any responses in that tab at all (sometimes i do).

**What is the expected result?**

Always receive every response in browser.

**Comment by zhangheng2022** [comment]
I had the same problem
