### ISSUE TITLE
How to get FINISH TIME using Puppeteer library.

### ISSUE THREAD

**Issue by navinchandrac** [puppeteer/puppeteer#5205]
How to get FINISH TIME (Chrome DevTools -> Network Tab ->FINISH TIME) using Puppeteer library.

![Chrome_Development_Tool_FINISH_TIME](https://user-images.githubusercontent.com/38746974/69871690-7b0eeb80-12d9-11ea-9b99-8b6d2ff8b65c.jpg)

**Comment by bala-v** [comment]
@navinchandrac Did you manage to figure out how to get finish time?. Does it also calculate the delays in async calls?.
