### ISSUE TITLE
Navigation failed because browser has disconnected! using Nodejs on Raspberry

### ISSUE THREAD

**Issue by omarpontis** [puppeteer/puppeteer#5207]
Hi,

i'm using node.js 10.15.2, on raspberry, and i'm trying to launch a browser and connect to a selected url, as below:

 const browser = await puppeteer.launch({executablePath: '/usr/bin/chromium-browser', args: ['--no-sandbox']});
  const page = await browser.newPage()
    await page.goto("www.google.com")
  
I'm always getting 
"Navigation failed because browser has disconnected!" error.

I've tried different ways (changing browser, changing pupeteer version, usinc puppeteer-core instead of puppeteer), but i cannot resolve the problem. Is it a known bug? Is there a way to fix the problem?

Thanks in advance

**Comment by mzubairsaleem** [comment]
Hi, Yes You can use 

Please follow the steps

**Install Chromium**

> wget https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
sudo dpkg -i chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
rm chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
wget https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
sudo dpkg -i chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
rm chromium-browser_72.0.3626.121-0+rpt4_armhf.deb

```
const browser = await puppeteer.launch({
			'args': [
				'--disable-web-security',
				'--allow-http-screen-capture',
				'--allow-running-insecure-content',
				'--disable-features=site-per-process',
				'--no-sandbox'
			],
			headless: true,
			executablePath: '/usr/bin/chromium-browser',
			// slowMo: 250, // slow down by 250ms
			// devtools: true
		});
```


I was able to use it well, but having just 1 problem with request interception.

I hope this will help.

**Comment by omarpontis** [comment]
Thanks, it works perfectly now :)

**Comment by laball** [comment]
> Hi, Yes You can use
> 
> Please follow the steps
> 
> **Install Chromium**
> 
> > wget https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
> > sudo dpkg -i chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
> > rm chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
> > wget https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
> > sudo dpkg -i chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
> > rm chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
> 
> ```
> const browser = await puppeteer.launch({
> 			'args': [
> 				'--disable-web-security',
> 				'--allow-http-screen-capture',
> 				'--allow-running-insecure-content',
> 				'--disable-features=site-per-process',
> 				'--no-sandbox'
> 			],
> 			headless: true,
> 			executablePath: '/usr/bin/chromium-browser',
> 			// slowMo: 250, // slow down by 250ms
> 			// devtools: true
> 		});
> ```
> 
> I was able to use it well, but having just 1 problem with request interception.
> 
> I hope this will help.

May I ask whitch version of puppeteer do you use?
I got this error too , and try some method but not wok;

**Comment by xiaoqiao112** [comment]
> Hi, Yes You can use
> 
> Please follow the steps
> 
> **Install Chromium**
> 
> > wget https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
> > sudo dpkg -i chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
> > rm chromium-codecs-ffmpeg_72.0.3626.121-0+rpt4_armhf.deb
> > wget https://archive.raspberrypi.org/debian/pool/main/c/chromium-browser/chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
> > sudo dpkg -i chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
> > rm chromium-browser_72.0.3626.121-0+rpt4_armhf.deb
> 
> ```
> const browser = await puppeteer.launch({
> 			'args': [
> 				'--disable-web-security',
> 				'--allow-http-screen-capture',
> 				'--allow-running-insecure-content',
> 				'--disable-features=site-per-process',
> 				'--no-sandbox'
> 			],
> 			headless: true,
> 			executablePath: '/usr/bin/chromium-browser',
> 			// slowMo: 250, // slow down by 250ms
> 			// devtools: true
> 		});
> ```
> 
> I was able to use it well, but having just 1 problem with request interception.
> 
> I hope this will help.

how did you handle the problem?  I can't use it

**Comment by mzubairsaleem** [comment]
Hi, 

I user chromium version 72 and this worked issue is with latest chromium releases.
