### ISSUE TITLE
Possible to give puppeteer browser window it's own title/icon?

### ISSUE THREAD

**Issue by robjmorrissey** [puppeteer/puppeteer#5208]
Just wondering how I would go about this. I initially suspected a chromium argument on startup would do the fix but to no avail.

**Comment by kblok** [comment]
You won't be able to do that.

**Comment by yuryturing** [comment]
For those looking at 2024. You can use command line argument https://peter.sh/experiments/chromium-command-line-switches/#window-name

```
`--window-name=MyWindow`
```
