### ISSUE TITLE
Improving performance and optimizing scripts

### ISSUE THREAD

**Issue by icarusmiles** [puppeteer/puppeteer#521]
**System** Ubuntu w/ Node v8.4.0

I am at a bit of a crossroads, I love Puppeteer's API and usage. However I am struggling to get the response times out of my scripts. I even ran my scripts on a dedicated 32GB RAM system with a 8 core processor. 

I have multiple scripts (different sources), all they do is lookup a product and add the item to cart and get the price data. This is user spawned, so speed is important - another issue is if two or more people spawn the process at the same time the resource usage is unreal and some say `Page has crashed` even on amazing specs. Also the cookies have to be independent per session/script.

On the best machine I could put my script on it took 9 seconds to complete by itself, if more than one person uses it obviously it begins to slow down very quickly. 

So with that being said, I have a few questions:

1. Is Puppeteer not really for this type of application processing?
2. Is there anyway to load sites in a little-to-no asset load? 
3. Cache all the assets locally for later use? (However allow sessions to have different cookies still)
4. Any alternative solutions? I used Chromeless in the past, it uses AWS Lambda - which was awesome. The palatalization/scaleability is nice, however 14 seconds response time guaranteed (max RAM) - that accumulates charges quickly.

My goal is to achieve 5 second or below timings with good scaleability. Preferably allow for good scaleability with as little resources as possible. 

In the end I'll have 7 websites that gets checked concurrently for a user, which as I mentioned is spawned by a user. I do have spam prevention and request control in the road-map, however want to achieve this first. I've read the documentation pretty extensively, but cannot find anything to improve speeds.

**Comment by aslushnikov** [comment]
> 1. Is Puppeteer not really for this type of application processing?
> 2. Is there anyway to load sites in a little-to-no asset load?

As #85 is implemented, you'll be able to create separate browser contexts for users. BrowserContexts are cheap to create, you'll avoid the necessity to launch separate chromes.

> 3. Cache all the assets locally for later use? (However allow sessions to have different cookies still)

This should be implementable as a separate caching service; this falls out of scope for puppeteer though.

> 4. Any alternative solutions? I used Chromeless in the past, it uses AWS Lambda - which was awesome. The palatalization/scaleability is nice, however 14 seconds response time guaranteed (max RAM) - that accumulates charges quickly.

I'm not aware of any.
