### ISSUE TITLE
data-focus-visible-added textarea attribute breaks page.type

### ISSUE THREAD

**Issue by OmarKhattab** [puppeteer/puppeteer#5211]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0
* Platform / OS version: Sierra
* URLs (if applicable):
* Node.js version: 8

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
await page.goto('https://www.instagram.com/p/B5eEZJlniqT/')

await page.type('textarea.Ypffh', 'Test Comment')
```
**What is the expected result?**
Type in text area

**What happens instead?**

No text is typed.

I noticed It only focuses when you manually click in the text area which then leads to a class being added to the textarea called 'focus-visible' as well as the attribute being added data-focus-visible-added

![Screen Shot 2019-11-30 at 9 57 58 PM](https://user-images.githubusercontent.com/26516889/69910245-c817be00-13bc-11ea-881d-1d462da4a325.png)

**Comment by OmarKhattab** [comment]
issue still exists had to use xpath to solve it

**Comment by kblok** [comment]
Your code worked for me.
