### ISSUE TITLE
chrome didn't shut down correctly

### ISSUE THREAD

**Issue by zenlykoi** [puppeteer/puppeteer#5212]
Hi there, i want to re open browser with puppeteer. But i got a popup have title is 'chrome didn't shut down correctly'. How can i re open browser and not have it? sorry my english not good!

**Comment by NPatch** [comment]
It also happened to me, but the reason was that I only called browser.CloseAsync and browser.DisposeAsync.
When I performed CloseAsync on all pages, I stopped getting a popup next time.
