### ISSUE TITLE
page.waitForElement [Feature Request]

### ISSUE THREAD

**Issue by hubitor** [puppeteer/puppeteer#5213]
I'm trying to make puppeteer wait for a button. All the examples I have seen so far use either page.waitForSelector() or page.waitFor() for this purpose. The problem is, I have already found the element (button) and I would like to use this for the wait. As I see in the docs, there is not such a method. 

Wouldn't make sense to have a wait method for elements?

**Comment by andreabisello** [comment]
@hubitor not able to understand what the problem is. if you already found the element, the element exists : what are you waiting for?

**Comment by hubitor** [comment]
I think, what I was trying to do, is limit the area to search for the button by using children and descendants. Something like that:

```
const puppeteer = require("puppeteer");

const PAGINATION_BLOCK_SELECTOR = "ul.pager";

puppeteer.launch({ headless: false }).then(async browser => {
  const page = await browser.newPage();
  await page.goto("http://books.toscrape.com/");
  let paginationBlock = await page.evaluateHandle(PAGINATION_BLOCK_SELECTOR => {
    return document.querySelector(PAGINATION_BLOCK_SELECTOR);
  }, PAGINATION_BLOCK_SELECTOR);
  let paginationBlockDescendants = await page.evaluateHandle(
    paginationBlock => {
      paginationBlockDescendants = paginationBlock.getElementsByTagName("*");
      console.log(paginationBlockDescendants);
      //paginationBlockDescendants[2].click()
      //return paginationBlockDescendants[2];
      return paginationBlockDescendants;
    },
    paginationBlock
  );
  console.log(await paginationBlockDescendants.jsonValue());
  //let button = await page.waitForXPath('//a[contains(text(),"next")]');
  //await button.click();
});

```
The button is the 3rd item:
`{ '0': {}, '1': {}, '2': {} }`

In this case, I can click on the button with: `paginationBlockDescendants[2].click()` and paginate without a problem, but I assumed that in general a button will not always be among the descendants. Maybe it's necessary to wait for it, but there is not a waitForElement() method. 
Of course I could use the a page.waitForSelector() but then it defeats the purpose of using children and descendants.
