### ISSUE TITLE
headless and not headless mode are rendering the same page in a little different mode

### ISSUE THREAD

**Issue by andreabisello** [puppeteer/puppeteer#5214]
### Steps to reproduce

**Tell us about your environment:**

```
C:\src\jest-image-snapshot-example>npm list --depth=0
jest-image-snapshot-example@1.0.0 C:\src\jest-image-snapshot-example
+-- jest@24.9.0
+-- jest-image-snapshot@2.11.1
`-- puppeteer@2.0.0
```

```
C:\src\jest-image-snapshot-example>node --version
v12.13.0
```

Windows 10 64 bit updated.

**What steps will reproduce the problem?**

1) clone this repository https://github.com/andreabisello/jest-image-snapshot-example and runs "headless-differences.test.js". OR
1) run this test, got the screenshot
2) activate headless mode, got the screenshot.

```

const puppeteer = require('puppeteer')
const { toMatchImageSnapshot } = require('jest-image-snapshot');
expect.extend({ toMatchImageSnapshot });

describe('headless differences Test', () => {

    test("headless and not headless screenshot should to be the same", async () => {
        jest.setTimeout(15000)
        browser = await puppeteer.launch({
            headless: false,
            defaultViewport: {width: 1800, height: 900},
            args: ["--start-maximized"],
            devtools: false
        })
        page = await browser.newPage()
        await page.goto("https://legaltest.solutiondocondemand.com", {
            timeout: 20000,
            waitUntil: ['load', 'domcontentloaded', 'networkidle0', 'networkidle2']
        })
        loginBox = await page.waitForSelector('#loginBox', {visible: true, timeout:30000})

        //removing time variant area
        await page.evaluate(() => {
            document.querySelector('#lblNow').style.visibility = "hidden"
        })

        //taking screenshot
        const loginBoxScreenshot = await loginBox.screenshot()
        expect(loginBoxScreenshot).toMatchImageSnapshot({
            failureThreshold: 0,
            failureThresholdType: "percent"
        })
        await browser.close()
    })
})


```

**What is the expected result?**

this test will open a url and take a screenshot of the login form. There should be no differences in the login form in headless or not headless mode.

**What happens instead?**

even i removed the time variant part of the page ( the one with the data ) , screenshot are ~1% different. 

Differences are

1) fonts rendering.
2) Login button have a kind of yellow border

![image](https://user-images.githubusercontent.com/2149815/69977719-983af880-152b-11ea-88aa-73ca4065c947.png)

**Comment by mykolavlasov** [comment]
I have tested it in my PC and the only 1 difference is that in headless mode the login button has a "focused" border effect when in the non-headless mode it isn't.
Mac OS 10.14.2

**Comment by mykolavlasov** [comment]
![](https://i.ibb.co/gRHrRGb/headless-differences-test-js-headless-differences-test-headless-and-not-headless-screenshot-should-to-be-the-same-1-diff.png)

**Comment by andreabisello** [comment]
@NickVlasov  thanks for your test.
so there is something related to the operative system, but there problem is that chromium is rendering the same website in a different way switching from headless or not headless,
and it should to render same ways, right?

**Comment by mykolavlasov** [comment]
> @NickVlasov thanks for your test.
> so there is something related to the operative system, but there problem is that chromium is rendering the same website in a different way switching from headless or not headless,
> and it should to render same ways, right?

logically, it should :)

**Comment by andreabisello** [comment]
I Will try using Chrome instead of chromium

Il Ven 20 Dic 2019, 22:18 NickVlasov <notifications@github.com> ha scritto:

**Comment by andreabisello** [comment]
@NickVlasov  i will also try this https://github.com/puppeteer/puppeteer/issues/665 (puppeteer-extra with puppeteer-stealth)

**Comment by andreabisello** [comment]
@NickVlasov not working for me.

**Comment by andreabisello** [comment]
@NickVlasov nothing changed also with chrome instead of chromium.
i updated the repository.

**Comment by alexdowad** [comment]
Same problem. On my dev machine, I found that the anti-aliased edges of fonts are slightly different when screenshots are taken in headless and non-headless Chrome. The difference is not noticeable unless the image is zoomed in.

**Comment by alexdowad** [comment]
I discovered a fix for my problem!

CLI arguments for Chrome:

```
--disable-font-subpixel-positioning
--disable-lcd-text
```

If it makes a difference for you, you could also add `--font-render-hinting=none`.

**Comment by andreabisello** [comment]
@alexdowad  good to know! i'm using chromium not chrome, i will try giving these parameters
https://peter.sh/experiments/chromium-command-line-switches/

**Comment by andreabisello** [comment]
@alexdowad  i tried


```
browser = await puppeteer.launch({
            headless: false,
            defaultViewport: {width: 1800, height: 900},
            args: ["--start-maximized", "--disable-lcd-text", "--font-render-hinting=none"],
            devtools: false
        })
```
but nothing changed :( 
i updated the demo repository.

i will try another library for image comparison.

**Comment by saratrionfetti** [comment]
I also have differences between same screenshots when I change the headless property. This is my case:

![diff](https://user-images.githubusercontent.com/92723440/150388751-d9c35f28-d6e5-4962-b662-b674ea71bdd4.png)

**Comment by alexdowad** [comment]
@stale, the issue is most definitely real. I have experienced it myself.

**Comment by somaalapati** [comment]
@Stale this is the annoying problem when used screenshot testing in Puppeteer. Please prioritize it to fix this issue.
![image](https://user-images.githubusercontent.com/40261789/180753055-bdacff56-6b3c-4532-b3dd-4cc7718be547.png)

**Comment by OrKoN** [comment]
Screenshots are already platform dependent (e.g., you would get slight differences on Mac vs Windows vs Linux) and different modes are not supposed to be identical. Also, please try using the new headless mode (`headless: chrome`) that is meant to be the same browser implementation as the headful mode. The old headless mode is actually a different browser underneath.

**Comment by KES777** [comment]
> and different modes are not supposed to be identical.

@OrKoN The problem still exists. Even if I generate screenshots when `headless: false`.

My test:
```javascript
describe('Screenshots', () => {
	let img;

	test('Full HD', async () => {
		await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36');
		await page.goto( SERVER+'example/p1.html', {waitUntil: 'domcontentloaded'} );
		img =  await page.screenshot({
			path: `${__dirname}/visualize/auth-login-full-hd.png`,
			fullpage: true,
			type: 'png'
		});

		expect( Buffer.from(img) ).toMatchImageSnapshot();
	});
});
```

![Image](https://github.com/user-attachments/assets/c85e5774-fa46-450a-abb0-e95faa3de7a5)

I noticed that during test the vertical scrollbar is blinking. Probably that is the issue.
