### ISSUE TITLE
requestInterception enabled causes puppeteer to be detected as bot

### ISSUE THREAD

**Issue by mursang** [puppeteer/puppeteer#5215]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  2.0.0
* Platform / OS version: MacOS 10.14.5
* URLs (if applicable): 
* Node.js version: v10.8.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Running puppeteer with `headless: false` on a url with PerimeterX protection seems to work fine
2. Enabling `setRequestInterception` causes puppeteer to go to captcha page because page is detecting it as bot. No matter what file type i'm intercepting, or even continuing every request, it will lead to captcha page.
3. Disabling it will get html without problems.

This is my code to test request interception
```
await page.setRequestInterception(true);
page.on('request', (request) => {
 request.continue();
});
```
Also tried this code with same result
```
await page.setRequestInterception(true);
  page.on('request', request => {
    if (request.resourceType() === 'image')
      request.abort();
    else
      request.continue();
  });
```

**Comment by kblok** [comment]
I don't think puppeteer should do anything around this. It is a bot.

**Comment by nicoandmee** [comment]
I have built a wrapper/framework on top of puppeteer to solve these kinds of issues: https://nicoandmee.github.io/puppeteer-theater/ check it out if interested.

**Comment by ordimans** [comment]
> I have built a wrapper/framework on top of puppeteer to solve these kinds of issues: https://nicoandmee.github.io/puppeteer-theater/ check it out if interested.

Your linked was removed.
Do you have a trick to avoid this ?
