### ISSUE TITLE
How to skip Google recaptcha in puppeteer?

### ISSUE THREAD

**Issue by vyomsrivastava** [puppeteer/puppeteer#5218]
So I am trying to access `https://my.outbrain.com/login` URL and whenever I enter the login and press enter, it shows Google ReCaptcha:
![Screenshot 2019-12-03 at 1 23 19 PM](https://user-images.githubusercontent.com/18082634/70031036-662fa200-15d0-11ea-9afa-80bc626d43ff.png)

How can I skip or bypass this ReCaptcha?

**Comment by andreabisello** [comment]
@vyomsrivastava i think you can't.
this is a behaviour of the website,
you cannot override the behaviour of the website.

**Comment by vyomsrivastava** [comment]
@andreabisello is there any way that the website doesn't detect puppeteer as a bot ??

**Comment by andreabisello** [comment]
@vyomsrivastava try forcing user agent

```

browser = await puppeteer.launch()
page = await browser.newPage()
await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36')


```

**Comment by nicoandmee** [comment]
> @andreabisello is there any way that the website doesn't detect puppeteer as a bot ??

please check [my framework](https://nicoandmee.github.io/puppeteer-theater/)

**Comment by paulogc** [comment]
@nicoandmee seems unavailable.

**Comment by japneetkaurbhatia** [comment]
@vyomsrivastava Can you please help me that how can I skip recaptcha ?
