### ISSUE TITLE
Request interception continue method probably not working with POST method

### ISSUE THREAD

**Issue by dsheiko** [puppeteer/puppeteer#5221]
I'm using Puppeteer 2.0.0 (Node.js v11.12.0) and want to perform a POST request.
When running the following code:

```javascript
const puppeteer = require("puppeteer");
const devices = require("puppeteer/DeviceDescriptors");

async function main() {
  const browser = await puppeteer.launch({
    args: ["--enable-features=NetworkService", "--no-sandbox"],
    ignoreHTTPSErrors: true
  });
  const page = await browser.newPage();

  await page.setRequestInterception(true);

  page.on("request", interceptedRequest => {
    const method = "POST", postData = "foo=FOO&bar=BAR";
    interceptedRequest.continue({ method, postData });
  });

  const response = await page.goto("https://postman-echo.com/post");

  console.log({
    url: response.url(),
    statusCode: response.status(),
    method: response.request().method(),
    body: await response.text()
  });

  setTimeout(async () => await browser.close(), 1000);
}

main();
```

I get statusCode: 200 and method: 'GET' like it wasn't intercepted.

What is even more confusing - when I try to do it with CDP Session:

```javascript
const puppeteer = require("puppeteer");
const devices = require("puppeteer/DeviceDescriptors");

async function main() {
  const browser = await puppeteer.launch({
    args: ["--enable-features=NetworkService", "--no-sandbox"],
    ignoreHTTPSErrors: true
  });
  const page = await browser.newPage();
  const session = await page.target().createCDPSession();

  await session.send( "Network.enable" );
  await session.send( "Network.setRequestInterception", {
      patterns: [{
        urlPattern: "*",
        interceptionStage: "HeadersReceived"
      }]
    });

  session.on( "Network.requestIntercepted", async ({ interceptionId, request, responseHeaders, resourceType }) => {

    await session.send( "Network.continueInterceptedRequest", {
      interceptionId,
      url: request.url,
      method: "POST",
      postData: "foo=FOO&bar=BAR"
    });
    session.detach();
  });

  const response = await page.goto("https://postman-echo.com/post");
  console.log({
    url: response.url(),
    statusCode: response.status(),
    method: response.request().method(),
    body: await response.text()
  });

  setTimeout(async () => await browser.close(), 1000);
}

main();
```
I get statusCode: 404 and method: 'GET'

Am I doing something wrong or is it an issue with Puppeteer?

**Comment by kblok** [comment]
`response.request` contains the original request being made. `request.continue` won't alter the `requests` array.
If you test that code using https://ptsv2.com/, you will see that you are getting posts on the other side.

```js
const response = await page.goto("https://ptsv2.com/t/wr1pa-1575457987/post");
```

![image](https://user-images.githubusercontent.com/2198466/70138414-02a88180-166f-11ea-8a5a-96115241d31e.png)

**Comment by dsheiko** [comment]
Thank you @kblok, I was suspecting something like that. But how can I obtain the details of the response by the modified request? I tried:
```javascript
  page.on("requestfinished", request => {
    console.log("requestfinished", request.method());
  });
  page.on("response", response => {
    console.log("response", response.request().method());
  });
```
both are not updated

**Comment by dsheiko** [comment]
What is more, I checked the server (endpoint) - it really receives the modified request method, but nothing in postData

**Comment by kblok** [comment]
The `request` has a `_requestId` which you can access both on the `request` or the `response` event. You could keep track of modified responses on your side.
You also know that the `response.request` object, it's the same reference you are getting in the `request` event.

>What is more, I checked the server (endpoint) - it really receives the modified request method, but nothing in postData.

That's weird, as you can see in my screenshot, I'm getting the postData you are using.

**Comment by dsheiko** [comment]
I got it with postData
```javascript
page.once("request", interceptedRequest => {
    interceptedRequest.continue({
      method: "POST",
      postData: "foo=FOO&bar=BAR",
      headers: {
        ...interceptedRequest.headers(),
        "Content-Type": "application/x-www-form-urlencoded"
      }
    });
  });
```

**Comment by dsheiko** [comment]
Oh, I see
```javascript
  page.on("response", async( response ) => {
    console.log("response", await response.text() );
  });
```
prints the server response body with the POST parameters in it. Thanks.

**Comment by ejames17** [comment]
> I got it with postData
> 
> ```js
> page.once("request", interceptedRequest => {
>     interceptedRequest.continue({
>       method: "POST",
>       postData: "foo=FOO&bar=BAR",
>       headers: {
>         ...interceptedRequest.headers(),
>         "Content-Type": "application/x-www-form-urlencoded"
>       }
>     });
>   });
> ```

thanks @dsheiko I got it working with your example. Seems that  for request to get properly it requires the method and headers. It doesn't seem to work just setting postData property.

ex.
```
request.continue({
method: 'POST',
postData: JSON.stringify({}),
headers: request.headers()
})
```

and not
 ```
request.continue({
 postData: JSON.stringify({})
})
```
