### ISSUE TITLE
in WSL in headless mode setContent throws after goto call

### ISSUE THREAD

**Issue by bmblb** [puppeteer/puppeteer#5225]
Not sure if this is a puppeteer of chromium issue. If it doesn't belong here, please advise.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Ubuntu under WSL on Windows 10
* URLs (if applicable):
* Node.js version: 10.17

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({ args : ['--no-sandbox'] })
const p = await browser.newPage();
await p.goto('http://localhost', { waitUntil : 'load' })
await p.setContent(html, { waitUntil : 'networkidle0' })
```
last line throws
```
(node:11900) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
(node:11900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What is the expected result?**
content to be set and later exported to PDF

**What happens instead?**
page crashes on setContent call.

This works with node on windows, but doesn't work with node in WSL.

**Comment by kblok** [comment]
Are you sure `http://localhost` goes to a valid page?

**Comment by bmblb** [comment]
Yes, I am. As I told, same script runs just fine in CMD with windows node/puppeteer, but when I run it via Ubuntu on WSL it throws.
