### ISSUE TITLE
Wait for network response to be completed

### ISSUE THREAD

**Issue by ramesh82** [puppeteer/puppeteer#5228]
This is in regards to #3649

How to wait for responses of multiple image types? 

`await page.waitForResponse(response => {
  return response.request().resourceType() === 'image';
});`

So basically we have multiple images that cannot be checked like the above

**Comment by andreabisello** [comment]
@ramesh82  maybe you can adapt this code

```
const waitForResponse = (page, url) => {
    return new Promise(resolve => {
        page.on("response", function callback(response){
            if (response.url() === url) {
                resolve(response);
                page.removeListener("response",callback)
            }
        })
    })
};
```
passing an array of url instead of a url,
and wait until all the url given a response,
something like this,
i'm not sure it will works because i don't know if the while loop will block the new response events

```
//this code need to be tested and fixed
const waitForResponse = (page, urls) => {
    return new Promise(resolve => {
        let urls = urls;
        page.on("response", function callback(response){
            while (urls.length > 0 && urls.includes(response.url()) {
                 urls = urls.filter(url => url !== response.url());
                 page.waitFor(500);
            }
             page.removeListener("response",callback)            
             resolve(response);
            
           
        })
    })
};

```

this **should** wait until every url of the urls array returned a response, then resolve the promise

**Comment by ramesh82** [comment]
> @ramesh82 maybe you can adapt this code
> 
> ```
> const waitForResponse = (page, url) => {
>     return new Promise(resolve => {
>         page.on("response", function callback(response){
>             if (response.url() === url) {
>                 resolve(response);
>                 page.removeListener("response",callback)
>             }
>         })
>     })
> };
> ```
> 
> passing an array of url instead of a url,
> and wait until all the url given a response,
> something like this,
> i'm not sure it will works because i don't know if the while loop will block the new response events
> 
> ```
> //this code need to be tested and fixed
> const waitForResponse = (page, urls) => {
>     return new Promise(resolve => {
>         let urls = urls;
>         page.on("response", function callback(response){
>             while (urls.length > 0 && urls.includes(response.url()) {
>                  urls = urls.filter(url => url !== response.url());
>                  page.waitFor(500);
>             }
>              page.removeListener("response",callback)            
>              resolve(response);
>             
>            
>         })
>     })
> };
> ```
> 
> this **should** wait until every url of the urls array returned a response, then resolve the promise

@andreabisello Thanks for your reply. Unfortunately I can't really check for the url because this is a hosted application (windows forms) which is getting served via terminal server and it's a single url where multiple content types are pushed to the client. I think I need to monitor for the network traffic. Is there anyway to check when the responses are finished coming through?
