### ISSUE TITLE
Request.continue(overrides) does not set cookie

### ISSUE THREAD

**Issue by evanrolfe** [puppeteer/puppeteer#5231]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Ubuntu
* Node.js version: 10.15.3

**What steps will reproduce the problem?**
Start a puppeteer browser with the request interception code:
```js
await page.setRequestInterception(true);
page.on('request', request => {
  // Override headers
  const headers = {cookie: 'hello=world;'};
  request.continue({headers});
});
```
Browse to a page which already has a cookie set by the browser, then check the request received by the server.

**What is the expected result?**
The server should receive the cookie header: "hello=world".

**What happens instead?**
The server receives receives the original cookie header set by the page, but it does not equal "hello=world" as it should. Setting the cookie header only works if the original request does not have a cookie set at all.

**What is the use case?**
I'm developing an app for pen-testing web apps, I need to let the user tamper with the request data i.e. changing header values (including cookies!), change POST data etc.

**Comment by gtsigner** [comment]
I have same problem, i can't solve it

**Comment by nicoandmee** [comment]
have a look at `fetchURLResponse()` function located in file puppeteer-bot-2a.js in my project: https://puppeteer.theater/

**Comment by gtsigner** [comment]
use page.setcookie

**Comment by ztob** [comment]
the same problem

**Comment by entrity** [comment]
This is still an issue for me on puppeteer v22.11.2. _However_, I find that I _can_ override cookies _if_ I use the stealth plugin:
```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());
```
