### ISSUE TITLE
DOM.describeNode doesn't work using Puppeteer's CDPSession

### ISSUE THREAD

**Issue by Ub1que** [puppeteer/puppeteer#5235]
* Puppeteer version: 1.20
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable): https://pptr.dev
* Node.js version: v12.13.0

Hi. I am trying to get `DOM.describeNode` through raw Chrome Devtools Protocol, but when I am connecting with `page.target().createCDPSession()` it doesn't work. The error is `Error: Protocol error (DOM.describeNode): Could not find object with given id`. But when I use `page._client.send` it works. Can you please explain is that an issue, or I'm doing something wrong?

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  const session = await page.target().createCDPSession();
  await session.send('DOM.enable');

  await page.goto('https://pptr.dev', { waitUntil: 'networkidle0' });
  await page.waitForSelector('h1');

  const element = await page.$('h1');

  // Doesn't work
  const nodeInfo = await session.send('DOM.describeNode', {
    objectId: element._remoteObject.objectId
  });

  // Works
  // const nodeInfo = await page._client.send('DOM.describeNode', {
  //   objectId: element._remoteObject.objectId
  // });

  console.log(nodeInfo);
})();
```

**What is the expected result?**
nodeInfo available

**What happens instead?**
 Error: Protocol error (DOM.describeNode): Could not find object with given id

**Comment by JohnGemstone** [comment]
Anyone figure how to fix this? Getting the same error trying to get a nodeId from `DOM.describeNode`

```ts
import type { CDPSession, ElementHandle } from "puppeteer";

async function getNodeIdFromElement(
  element: ElementHandle,
  session: CDPSession
): Promise<number> {
  const { objectId } = element.remoteObject();
  // objectId = -3492923574421999489.3.4

  const { nodeId } = await session.send("DOM.requestNode", {
    objectId,
  });

  // Protocol error (DOM.requestNode): Could not find object with given id
  
  return nodeId;
}

export { getNodeIdFromElement };
```

**Comment by JohnGemstone** [comment]
Figured a fix using the private client method instead of `createCDPSession` for the session

```ts
  // const session = await page.createCDPSession();
  const session = await page._client() as CDPSession
```
