### ISSUE TITLE
Freezing page.waitForNavigation() when automatically opening New tab

### ISSUE THREAD

**Issue by eradaningol** [puppeteer/puppeteer#5238]
### Steps to reproduce

* Puppeteer version: 2.0.0
* Platform / OS version: Linux Mint
* Node.js version: 10.6.0

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

(async () => {
  

  const browser = await puppeteer.launch();
  
  const page = await browser.newPage();
  
  page.on('dialog', async dialog => {
    await dialog.accept();
  });

  await page.goto('http://127.0.0.1:8000');

  await Promise.all([
    page.click('#alert'),
    page.waitForNavigation({ waitUntil: 'networkidle0'}), 
]);
  await page.screenshot({path: 'screenshot.png'});
  await browser.close();
})();

```
page HTML with confirmation alert:

```
<!DOCTYPE html>
<head>
<body>
<script>
    function confirmation() {
        if (!confirm("Please confirm")) return;
        window.open('https://google.com','width=400,height=400');
}
</script>
<h1>Click button underneath</h1>
<button id=alert onclick="confirmation()" >Click this button</button>
</body>
</head>
```

**What is the expected result?**
Very simple use case - open page, on click open and accept confirmation alert which opens new tab, screenshot tab and close

**What happens instead?**
Puppeteer freezes when it opens new tab from confirmation. I can't figure why, if page is actually in focus, it would not screenshot and close. And if it is a new page, how to call it. What am I missing?

**Comment by kblok** [comment]
`page.waitForNavigation` will wait for navigation on the "opener" page, it won't listen to new pages.
You could do something like this

```js
const createdTarget = new Promise(fulfill => browser.on('targetcreated', (target) => {
    if (target.url() === '<popup-url>') fulfill(target)
}));
page.on('dialog', async dialog => {
    await dialog.accept();
  });

  await page.goto('http://127.0.0.1:8000');
  await Promise.all([
    page.click('#alert'),
    createdTarget, 
]);
  const popup = await createdTarget.page();
  await popup.screenshot({path: 'screenshot.png'});
```

**Comment by eradaningol** [comment]
> `page.waitForNavigation` will wait for navigation on the "opener" page, it won't listen to new pages.
> You could do something like this
> 
> ```js
> const createdTarget = new Promise(fulfill => browser.once('targetcreated', (target) => {
>     if (target.url() === '<popup-url>') fulfill(target)
> }));
> page.on('dialog', async dialog => {
>     await dialog.accept();
>   });
> 
>   await page.goto('http://127.0.0.1:8000');
>   await Promise.all([
>     page.click('#alert'),
>     createdTarget, 
> ]);
>   const popup = await createdTarget.page();
>   await popup.screenshot({path: 'screenshot.png'});
> ```

I don't think it works, it still freezes on opening new page after confirming alert. Where is the 'popup-url' coming from? I can't find it anywhere in documentation. If I substitute it with the actual end URL, Puppeteer still freezes.

**Comment by kblok** [comment]
@eradaningol so `browser.once('targetcreated')` should be `on` not `once`. I changed that.
`targetcreated` will be emitted every time a new target is created, e.g. a popup. How do you know which is the target you need? the most common way is using the URL. You should should replace `<popup-url>` with the URL of your popup.

So when you click on `#alert` a new target should be created, the popup, which will resolve the `createTarget` promise, which will resolve the `Promise.all` promise. 
After that, you can request the page of that new target, using `await createdTarget.page()`.  With that page you can take the screenshot you need.

**Comment by eradaningol** [comment]
@kblok Thanks for the explanation, it makes perfect sense, but Puppeteer still freezes on new page. Could it be that `createTarget` should be waiting in `page.on('dialog')` instead? Because popup itself does not have a URL?
