### ISSUE TITLE
Cannot click button of type "submit"

### ISSUE THREAD

**Issue by jbdoster** [puppeteer/puppeteer#5240]
### Steps to reproduce

Ubuntu 18.04
Puppeteer 2.0.0

* Puppeteer version: 2.0.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

I tried these combinations of code I gathered from this repo's issues/stackoverflow/other various forums to "click" a button of type submit:

```
await page.$eval('button[type="submit"]', elem => elem.click());

    await page.click('button[submit]');
    await page.click('button[type=submit]', {waitUntil: 'domcontentloaded'});
    await page.evaluate((selector) => document.querySelector(selector).click(), process.hcPlatform.selectors.signup.submit); 
    await page.evaluate((selector) => document.querySelector(selector).click(), 'button.sc-gisBJw gVJias btn btn-default'); 

    await page.evaluate(() => document.querySelector('button[type="submit"]').scrollIntoView());
    await page.click('button[type="submit"]');

    await page.waitFor('button[type="submit"]');
    await page.$eval('button[type="submit"]', elem => elem.click());
    await page.click('button[type="submit"]', {waitUntil: 'domcontentloaded'});

    await page.waitFor(3000);
    await page.click('button[text="Sign Up"]')

    await page.focus('button[type="submit"]' )
    await page.keyboard.type('\n');

    await page.$$eval('button[type="submit"]', button => {
        button.click();
    });
```

**What is the expected result?**

Submit the form

**What happens instead?**

Either the checkbox above the submit button is DESELECTED and the submit button is ignored, or the submit button is simply ignored, or "no node is found".

**Comment by mmusil** [comment]
Got the same problem. Just in my case, I've also tried to use this code:
```
const loginButton = await page.$('button[type="submit"]');
if (loginButton) {
      await Promise.all([page.waitForNavigation(), loginButton.click()]);
}
```

**Comment by max-koa** [comment]
Did anyone find a solution to this issue? I am having the same issue. It says: 

`Node is either not visible or not an HTMLElement`

I've already verified that the element exists and is visible.

**Comment by Mottoweb** [comment]
On the same boat here, any news?

**Comment by max-koa** [comment]
> On the same boat here, any news?

It's been a while since I touched that code. But this is what I have at the end. Maybe it works for you?

`await Promise.all([global.page.waitForNavigation(), await page.$eval('form#user_register_form', (form) => form.submit())]);`

**Comment by Mottoweb** [comment]
> > On the same boat here, any news?
> 
> It's been a while since I touched that code. But this is what I have at the end. Maybe it works for you?
> 
> `await Promise.all([global.page.waitForNavigation(), await page.$eval('form#user_register_form', (form) => form.submit())]);`

Thanks for your help, I just found out that I don't have an actual form element, its plain button with a handler attached, which still does not work :/

**Comment by jjoocceeee** [comment]
Running into this issue also... any update?

**Comment by keithlowc** [comment]
Same issue here - Any ideas?

**Comment by RubenHalman** [comment]
I am still having this issue
