### ISSUE TITLE
Puppeteer incorrectly combines duplicate headers

### ISSUE THREAD

**Issue by molant** [puppeteer/puppeteer#5244]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0
* Platform / OS version: All
* URLs (if applicable): https://compo.sr
* Node.js version: 10.17

**What steps will reproduce the problem?**

Create a JS file with the following content and execute it:

```js
const puppeteer = require('puppeteer');

const composr = 'https://compo.sr/';

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    page.on('response', (response) => {
        if (response.url() === composr) {
            const headers = response.headers();

            console.log(headers['x-content-type-options']);
        }
    });

    await page.goto(composr);

    await browser.close();
})();
```

**What is the expected result?**

https://compo.sr sends the `x-content-type-options` twice with the same value.

According to [HTTP RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), duplicate headers can be combined respecting the order and using `,` to join them so I'd expect the output of the code above to be 

```
nosniff, nosniff
```

**What happens instead?**

The values are joined using `\n` so the output is:

```
nosniff
nosniff
```

**Comment by kblok** [comment]
Honestly, I don't think puppeteer should comply with HTTP RFC2616. Can't you get a workaround knowing that Chromium returns duplicated headers separated with a new line?

**Comment by molant** [comment]
>  I don't think puppeteer should comply with HTTP RFC2616

Can you please explain why?
This is how the headers should be processed when combined. If a proxy does what puppeteer is doing, it will be wrong.

> Can't you get a workaround knowing that Chromium returns duplicated headers separated with a new line

We can definitely split by line, but this seems like something that should be fixed upstream.

**Comment by kblok** [comment]
>Can you please explain why?

I'm not strong on this. But I don't see the need to comply with the HTTP protocol, being the fact that puppeteer is not doing an HTTP connection. Even more, if you would want to comply with the protocol, the headers should be a list of strings (name and value separated by a colon `:`)  instead of a dictionary. I know, this is too much, but it was an example.

>We can definitely split by line, but this seems like something that should be fixed upstream.

I thought about that before my first comment. If you want this fixed, you should report that in Chromium instead of in puppeteer.

**Comment by molant** [comment]
> you should report that in Chromium instead of in puppeteer.

Didn't think about looking what CDP returned 🤦‍♂️

I can see it in the protocol inspector:

![image](https://user-images.githubusercontent.com/606594/70836973-e7e4b400-1db6-11ea-8090-032975d79a7b.png)

It's going to be painful to update it there as it will be a breaking change and devtools and such will have to get updated. I think I'll just workaround our code and call it a day 😅

Thanks!
