### ISSUE TITLE
How to wait for a Recaptcha to load in Puppeteer?

### ISSUE THREAD

**Issue by namename-123** [puppeteer/puppeteer#5245]
I want to scrape a website and I'm having difficulties with the Recaptcha. I've already figured out a way to solve it but before that method starts I have to make sure Recaptcha is fully loaded, which is what I'm stuck at. 
I've tried ``page.waitForSelector('#captchaFormPart > td:nth-child(2) > script:nth-child(1)', options={'visible': True})``, I got that selector from the Recaptcha's checkbox, and it didn't work.

**Comment by sonyarianto** [comment]
Hi @virg1n I want to know you already solve this or not? If yes, can you share here?

**Comment by deepak-mali** [comment]
Hi @virg1n I am facing issue bypassing reCaptcha. Could you tell us your solution to deal with it?

**Comment by paulogc** [comment]
@deepak-mali how did you bypass reCaptcha?

**Comment by deepak-mali** [comment]
@paulogc
Try with `--enable-automation` flag.
```
 const browser = await puppeteer.launch({
   headless: false,
   args: [
     '--enable-automation',
   ],
 });

```
