### ISSUE TITLE
Feature request: should elementHandle.uploadFile accept buffer?

### ISSUE THREAD

**Issue by hlr1983** [puppeteer/puppeteer#5247]
Hi! Shouldn't elementHandle.uploadFile accept buffer or an array of objects like `{ name: String, content: Buffer, mimeType: String }` ?

The use case is that sometimes I have to take a screenshot and upload it. I wouldn't have to save to a file, read it, upload it and delete it. I would only store the screenshot in a buffer and upload it, making my procedure faster.

Would it be useful for more people?

Thanks.

**Comment by jrandolf-google** [comment]
You could just write a file to `/tmp` before uploading it. Closing as won't fix.
