### ISSUE TITLE
How to get request when click?

### ISSUE THREAD

**Issue by donywan** [puppeteer/puppeteer#5248]
How to make the request sent by the click element match it, and get all the requests when I click, `page.on ('response')` will get all the requests, which is very confusing. `page.waitForResponse (response, => response.ok ())` can only get one, what do I need to do?

**Comment by kblok** [comment]
What do you need to do with that request?

**Comment by donywan** [comment]
> What do you need to do with that request?

```
const puppeteer = require('puppeteer');
const url = require('url');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        // devtools: true,
        ignoreHTTPSErrors: true,
    });
    const page = await browser.newPage();
    const dcsurl = 'https://act.ahydnet.com/h/d/hd/AC20191029886969/index_app.html';

       page.on('response', response => {
           const requestUrl = response.url()
           if (requestUrl.toLowerCase().match(/dcs\.gif/)) {
             parseQuery(requestUrl).then(result => {
                 console.log(result)
             })
         }
     })
   
     await page.goto(dcsurl, { waitUntil: 'networkidle0' })
     // Close login dialog
     await page.click('.tclogin-xxx')

     await page.click('.zjd_price')
    
    // await page.waitFor(2000)
    // await page.waitForNavigation()
    await browser.close()
})();
async function waitResponse(page) {
    return new Promise((reslove, reject) => {
        page.waitForResponse(res => res.url().match(/dcs\.gif/)).then(result => {
            const requestUrl = result.url()
            reslove(result.url())
            parseQuery(requestUrl).then(resp => {
                console.log(resp)
            })
        })
    })
}
async function parseQuery(requestUrl) {
    if (requestUrl.match(/dcs\.gif/)) {
        const param = url.parse(requestUrl, true).query
        return param
    }
}
```
I want to get the corresponding 'dcs.gif' request when I click.Thanks. @kblok

**Comment by kblok** [comment]
Yeah, the only way I could think for solving this, would be a flag that you turn on before clicking and you turn off after getting the request, but that's not 100% accurate. You have to think that a single click might trigger lots of requests.

**Comment by donywan** [comment]
> Yeah, the only way I could think for solving this, would be a flag that you turn on before clicking and you turn off after getting the request, but that's not 100% accurate. You have to think that a single click might trigger lots of requests.

Yes,good idea,you are right.
