### ISSUE TITLE
Popup blocker detected in headless mode

### ISSUE THREAD

**Issue by OysterD3** [puppeteer/puppeteer#5250]
* Puppeteer version: v2.0
* Platform / OS version: MacOS v10.15.2
* URLs (if applicable):
* Node.js version: v10.16.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Enable headless mode
2. `args: ["--disable-popup-blocking", "--allow-popups-during-page-unload"],`

**What is the expected result?**
Should be disabling popup blocker

**What happens instead?**
Popup blocker enabled

**Comment by kblok** [comment]
According to [this post](https://stackoverflow.com/questions/47879469/chromedriver-switches-disable-popup-blocking-doesnt-work-using-ruby-in-headle). This was reported in [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=775911#c7)

**Comment by ysz** [comment]
It persists on 14.4.1

Same code works fine in headful and timeouts waiting for popup in headless
