### ISSUE TITLE
browser.close() does not close chrome from wsl

### ISSUE THREAD

**Issue by dorshinar** [puppeteer/puppeteer#5251]
### Steps to reproduce

I'm running puppeteer tests in WSL on a windows machine, and launching chrome.exe from on my windows environment in non-headless mode. For some reason `browser.close()` does not close the browser instance, leaving the `about:page` open, forcing me to run jest tests with `--forceExit` (which I prefer not to).

* Puppeteer version: 2.0.0
* Platform / OS version: Windows 10 1903, WSL 1
* URLs (if applicable):
* Node.js version: 12.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. launching the browser:
```js
browser = await puppeteer.launch({
  headless: false,
  ignoreDefaultArgs: ["--disable-extensions"],
  args: ["--no-sandbox"],
  executablePath: "chrome.exe"
});
```

**What is the expected result?**
The expected result is that running `browser.close()` will close the browser window, allowing jest to exit gracefully. 

**What happens instead?**
The browser window is left open, forcing me to use `--forceExit` after all tests are closed.

**Comment by axi92** [comment]
Were you able to fix your issue? @dorshinar 
I got the same problem right now.
