### ISSUE TITLE
page.deleteCookie() not working (?)

### ISSUE THREAD

**Issue by andreabisello** [puppeteer/puppeteer#5253]
OS : Windows 10 64 bit all updated
Node : v12.13.0
Puppeteer : 2.0.0

Temptative : delete a cookie.

What chromium see : 

![image](https://user-images.githubusercontent.com/2149815/70899510-0afda680-1ff7-11ea-8c82-fd3fbb9d731c.png)

what i want to do : 

delete the cookies named ".ASPXFORMSSD"

my code

```
beforeEach(async () => {
        console.log("cookies was")
        let before = await page.cookies()
        before.forEach(cookie => {
            console.log(cookie.name)
        })

        await page.deleteCookie({
            name : ".ASPXFORMSSD",
            domain : "integration.solutiondocondemand.com"
        })

        console.log("cookies are")
        let after = await page.cookies()
        after.forEach(cookie => {
            console.log(cookie.name)
        })

        await helpers.loadUrl(page, config.baseUrl)
    })

```

obtained : cookie is not deleted 

the log : 

console.log test/loginPage.test.js:21
    cookies was

  console.log test/loginPage.test.js:24
    .ASPXFORMSSD

  console.log test/loginPage.test.js:24
    ASP.NET_SessionId

  console.log test/loginPage.test.js:32
    cookies are

  console.log test/loginPage.test.js:35
    .ASPXFORMSSD

  console.log test/loginPage.test.js:35
    ASP.NET_SessionId

**Comment by kblok** [comment]
Removing `ASP.NET_SessionId` does work right?

**Comment by andreabisello** [comment]
my fault.
the domain was not the correct one.
test were pointing to another test environment.
i suggest to print also the cookie.domain to be sure about the cookie domain.

**Comment by SashaDesigN** [comment]
I use this to remove all cookies:

```
	async clearBrowser () {
		// clear cookies
		const client = await this.page.target().createCDPSession()		
		await await client.send('Network.clearBrowserCookies')
	}
```

**Comment by Ancorreapacheco** [comment]
> I use this to remove all cookies:
> 
> ```
> 	async clearBrowser () {
> 		// clear cookies
> 		const client = await this.page.target().createCDPSession()		
> 	        await client.send('Network.clearBrowserCookies')
> 	}
> ```

Thank you, It works
