### ISSUE TITLE
Hovered elements state doesn't displayed on the screenshots in non-headless mode

### ISSUE THREAD

**Issue by mykolavlasov** [puppeteer/puppeteer#5255]
In non-headless`{ headless: false }` mode when I hover an element with puppeteer and make a page screenshot, hovered elements state(background, color, etc.) doesn't display in the screenshots.
In headless`{ headless: true }` mode everything works fine.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Mac OS 10.14.2
* URLs (if applicable): git repo - https://github.com/NickVlasov/puppeteer-screenshot-on-hover
* Node.js version: 12.7.0

**What steps will reproduce the problem?**

1. Clone repo - https://github.com/NickVlasov/puppeteer-screenshot-on-hover
2. run `nvm use && npm i`.
To make screenshot in headless mode:
`npm run screenshot:headless`  
To make screenshot in non-headless mode
`npm run screenshot:non-headless`

Screenshot differs, but they should not.

If you just want a code:
```javascript
const puppeteer = require('puppeteer');
const APP_URL = 'https://59iox.csb.app/';
const HOVERED_ELEMENT_SELECTOR = '#line';

(async () => {
  const hash = +new Date();

  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto(APP_URL);

  const element = await page.$(HOVERED_ELEMENT_SELECTOR);

  await element.hover();
  await page.waitFor(100);
  await element.screenshot({
    path: `./screenshots/${hash}.png`,
  });

  await browser.close();
})()
```

**What is the expected result?**
Hovered element should have a another background and text color

**What happens instead?**
State of hovered element doesn't displayed in screenshot.

**Comment by andreabisello** [comment]
@NickVlasov  can be related with this ? https://github.com/puppeteer/puppeteer/issues/5214

**Comment by mykolavlasov** [comment]
> @NickVlasov can be related with this ? #5214

Not sure. I have run tests in your repo and the only one difference in screenshots is kind of the same as I have mentioned above

**Comment by andreabisello** [comment]
@NickVlasov  sure, but i think chromium should render the website same way even on headless or not mode.

**Comment by Nikschavan** [comment]
@NickVlasov - did you find any solution for this? I am hitting this error at the moment where when checking CSS properties (`color`) of any element on hover does not give correct values in headless mode but works as expected in interactive mode.

**Comment by mykolavlasov** [comment]
> @NickVlasov - did you find any solution for this? I am hitting this error at the moment where when checking CSS properties (`color`) of any element on hover does not give correct values in headless mode but works as expected in interactive mode.

Unfortunately, we weren't able to find a solution as far as I remember

**Comment by rvs24** [comment]
Hovered elements state doesn't displayed on the screenshots.
Giving screenshot of hovered element tooltip if we manually hover it in {headless : false} mode but if we hover the element using selector.hover() then not giving the hovered element tooltip in screenshot both in {headless : false} and {headless : true} mode.
Puppeteer version 15.5.0
Node 14.18.1

Code:-
`const browser = await puppeteer.launch({headless: false})
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle0' });
  const styleNumbers = await page.$$(".class");
  for( let styleNumber of styleNumbers ) {
       if (condition){
           await styleNumber.hover();
           await page.waitForTimeout(3000);
           await page.screenshot({path: 'image.png'});
         }
      }`
