### ISSUE TITLE
Can't get a simple page

### ISSUE THREAD

**Issue by skiiiks** [puppeteer/puppeteer#5256]
Hi:
I'm using a simple test in puppeteer playground: https://try-puppeteer.appspot.com/

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://es.linkedin.com/in/damienpeters');
console.log(await page.content());
await page.content();
await browser.close();

Response is:
Error running your code. Error: Execution context was destroyed, most likely because of a navigation.

What is wrong?

**Comment by sonyarianto** [comment]
@skiiiks hmmm I think LinkedIn page protection maybe? I tried with local Puppeteer it will not show the profile page, but somekind of page protection.

**Comment by skiiiks** [comment]
> @skiiiks hmmm I think LinkedIn page protection maybe? I tried with local Puppeteer it will not show the profile page, but somekind of page protection.

And then how can I retrieve the page? Any ideas? Suggestions? I've tried with different user-agent, and even with a resident IP (Luminati).

Also my question is how to get more information of that "destruction" ... what the reason was.

**Comment by kblok** [comment]
The execution context is being destroyed due because of navigation. That means that between the `goto` and `content` the page is being redirected to another place.

You could add a `waitForSelector` after the goto. Something generic:

```js
await page.waitForSelector('BODY')
````

But, as @sonyarianto said, you will hit a login wall.

**Comment by skiiiks** [comment]
If I open a browser and go to that URL, it works.
How can we simulate with Puppeteer that simple action ? ;-)

**Comment by kblok** [comment]
Keep in mind that Puppeteer doesn't use **your** browser by default. Ergo, it doesn't have all the cookies you have.

You can pass the executable path of your browser to a puppeteer though. Check out the [launch doc](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#puppeteerlaunchoptions).

**Comment by skiiiks** [comment]
> Keep in mind that Puppeteer doesn't use **your** browser by default. Ergo, it doesn't have all the cookies you have.
> 
> You can pass the executable path of your browser to a puppeteer though. Check out the [launch doc](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#puppeteerlaunchoptions).

I meant a incognito browser

**Comment by kblok** [comment]
This is what I get incognito
![image](https://user-images.githubusercontent.com/2198466/71085778-0bbd4680-2177-11ea-990d-f36f858c9906.png)

**Comment by skiiiks** [comment]
> This is what I get incognito
> ![image](https://user-images.githubusercontent.com/2198466/71085778-0bbd4680-2177-11ea-990d-f36f858c9906.png)

I have installed Chrome in a new computer (brought yesterday ;-)
First thing I do is to open a incognito window
Go to https://es.linkedin.com/in/damienpeters
And I see the public profile of that person

**Comment by skiiiks** [comment]
I'm in a apple store ... I'm opening incognito windows in different computers and Linkedin allows me to see the public profile of that person and click in other profiles with no problem. I never see the login window.
