### ISSUE TITLE
Chromium crashes if using a combination of headless, incognito, and single-process

### ISSUE THREAD

**Issue by lwillmeth** [puppeteer/puppeteer#5258]
Chromium crashes while using a combination of headless, incognito, and single-process.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: MacOs 10.14
* URLs (if applicable): N/A
* Node.js version: 12.13.0

**What steps will reproduce the problem?**

Launch puppeteer with options:

```
{
  headless: false,
  args: [
    '--incognito',
    '--single-process'
  ],
}
```

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

async function main() {
    const browser = await puppeteer.launch({
        headless: false,
        args: [
            '--incognito',
            '--single-process',
        ],
    });

    const page = await browser.newPage();

    await page.goto('https://google.com');
    const pageTitle = await page.title();
    console.log('Title:', title);
};

main().catch(err => console.error(err))
```

**What is the expected result?**

The title for google.com

**What happens instead?**

```
node example.js
Error: Protocol error (Target.createTarget): Target closed.
    at ~./demo/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (~./demo/node_modules/puppeteer/lib/Connection.js:73:12)
    at Browser._createPageInContext (~./demo/node_modules/puppeteer/lib/Browser.js:174:47)
    at BrowserContext.newPage (~./demo/node_modules/puppeteer/lib/Browser.js:367:26)
    at Browser.newPage (~./demo/node_modules/puppeteer/lib/Browser.js:166:33)
    at Browser.<anonymous> (~./demo/node_modules/puppeteer/lib/helper.js:112:23)
    at main (~./demo/example.js:12:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
{
  message: 'Protocol error (Target.createTarget): Target closed.'
}
```

The browser crash report begins with:
```
Process:               Chromium [61359]
Path:                  /Users/USER/*/Chromium.app/Contents/MacOS/Chromium
Identifier:            org.chromium.Chromium
Version:               79.0.3945.0 (3945.0)
Code Type:             X86-64 (Native)
Parent Process:        node [61358]
Responsible:           iTerm2 [274]
User ID:               502

Date/Time:             2019-12-18 14:10:36.107 -0800
OS Version:            Mac OS X 10.14.6 (18G1012)
Report Version:        12
Bridge OS Version:     3.0 (14Y906)
Anonymous UUID:        1088BFF9-4A27-D608-A8A1-5B98417C9077

Sleep/Wake UUID:       885BBD08-6441-4848-8BE3-464FF37CF99A

Time Awake Since Boot: 260000 seconds
Time Since Wake:       3600 seconds

System Integrity Protection: disabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
```

From what I can tell, these three pieces are related:

OK:
  headless=true
  headless=false, incognito XOR single-process
Crash:
  headless=false, incognito AND single-process

It may be worth noting that I'm successfully using this combination with the browser included in the [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) project, but only in a deployed aws lambda, not locally.  The browser included with puppeteer does not seem able to handle this combination.

Any tips are welcome, I'm open to user error as a possibility.

**Comment by lwillmeth** [comment]
Scratch that, I realized it's working in the other browser because it's running headless=true.

I can't use headless=false, incognito, and single-process together.

Can anyone else?  Is this just me?  Maybe it's just an undocumented and unsupported combination of flags?

**Comment by aha-oretama** [comment]
I think this is related to this, could you check it?
https://github.com/puppeteer/puppeteer/issues/2608#issuecomment-393955311
