### ISSUE TITLE
Is Puppeteer for Firefox maintained?

### ISSUE THREAD

**Issue by limonte** [puppeteer/puppeteer#5260]
The latest release of `puppeteer-firefox` was 10 months ago: https://www.npmjs.com/package/puppeteer-firefox

There are couple of fixes that have been made in the meantime, e.g. #4850

Is Puppeteer for Firefox maintained? If so, when can we expect the next release?

**Comment by Kradirhamik** [comment]
Also, curious about Edge on Chromium that is about to be released. Will it be maintained too?

**Comment by mathiasbynens** [comment]
The Juggler-based `puppeteer-firefox` is not actively maintained. Instead, Mozilla is collaborating with us to add Firefox support to the `puppeteer` project itself. @mjzffr has been leading this on the Mozilla side and here are some open issues: https://github.com/puppeteer/puppeteer/issues?q=is%3Aissue+is%3Aopen+firefox+label%3Afirefox

**Comment by limonte** [comment]
Thank you for the update @mathiasbynens and thanks for releasing `puppeteer-firefox@0.5.1`!
