### ISSUE TITLE
unable to take screenshots of img tags with svg source

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5261]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOS 10.15.2
* URLs (if applicable): https://cloud.google.com/automl-tables/
* Node.js version: v12.13.1

**What steps will reproduce the problem?**
Trying to take screenshot of an element:

```js
const element = await page.$x(
/html/body/div[1]/div[2]/div[2]/div/article/div[4]/section/div/div[1]/img')
const elementScreenshot = await element.screenshot({
      type: 'png',
      encoding: 'base64',
    })
```

**What is the expected result?**
Screenshot of the icon.

**What happens instead?**
Empty screenshot with white background.

More details:
What element:
<img width="73" alt="Screen Shot 2019-12-20 at 8 53 15 PM" src="https://user-images.githubusercontent.com/1330677/71303261-34a62d00-236b-11ea-95e3-a62adff77aa9.png">

What else have I tried:
- Screenshots of img tags itself works fine
- Screenshots of svg element's parent works fine

What's unique about this image:
The source is: `<img src="https://cloud.google.com/images/automl-tables/ic-retail.svg" alt="Retail">`
The src here has a `.svg` file. Maybe that's causing some issue with rendering.

**Comment by stringStar** [comment]
hi!I had the same problem
