### ISSUE TITLE
/lib64/libnss3.so: version `NSS_3.22' not found

### ISSUE THREAD

**Issue by Rovango** [puppeteer/puppeteer#5263]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: CentOS Linux release 7.3.1611 (Core)
* URLs (if applicable):
* Node.js version: v12.14.0

When I ran the example of puppeteer in CentOS 7.3:
`
let puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: ['--no-sendbox', '--disable-setuid-sandbox']
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
`
the error  below happens:

(node:22934) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
 /lib64/libnss3.so: version `NSS_3.22' not found 

I had tried to install all the dependencies advised in troubleshooting(https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix), by execute:
`
yum install -y alsa-lib.x86_64 atk.x86_64 cups-libs.x86_64 GConf2.x86_64 gtk3.x86_64 ipa-gothic-fonts libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXrandr.x86_64 libXScrnSaver.x86_64 libXtst.x86_64 pango.x86_64 wqy-unibit-fonts.noarch wqy-zenhei-fonts.noarch xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-fonts-cyrillic xorg-x11-fonts-misc xorg-x11-fonts-Type1 xorg-x11-utils
`

after that when ran `ldd chrome | grep no`
the result is still:  
./chrome: /lib64/libnss3.so: version `NSS_3.22' not found (required by ./chrome)

So how can I fix this problem and make the puppeteer work in CentOS7.

**Comment by Rovango** [comment]
`yum update nss -y`  is also be executed successfully. 
But it seems that I cant update my nss version larger than 3.21
```
Package nss-3.21.3-2.el7_3.x86_64 already installed and latest version
Nothing to do
```

**Comment by Rovango** [comment]
it seems that I cant udpate my nss to 3.22 in my system.  anyone knows that?

**Comment by xuefuyuan** [comment]
Have you solved this problem now?

**Comment by josephrocca** [comment]
Also having this problem on an old Ubuntu 16.04 server (with Node.js v16) that I can't currently upgrade.

I can't find any "requirements" page in the docs to say what minimum versions of Ubuntu/Debian are supported. @OrKoN, apologies for the ping, please ignore if there is no intention to document minimum Debian versions.

**Comment by OrKoN** [comment]
This is what we have https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux there is a link to what dependencies Chromium requires.

**Comment by OrKoN** [comment]
It is possible that Chromium needs some newer versions of some of those libraries so versions should match: https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/debian/dist_package_versions.json Note that Chromium does not seem to support Ubuntu 16 no more: https://source.chromium.org/chromium/chromium/src/+/32514ce9b414c0acd9298603160c71e9352cf73d

**Comment by josephrocca** [comment]
Ahh, that makes sense then. Thanks for your quick replies! :pray:
