### ISSUE TITLE
Prevent devtool debugger "pause on debugging" aka disable all breakpoints on devtools

### ISSUE THREAD

**Issue by r1si** [puppeteer/puppeteer#5265]
I need to scarping this page:
http://r1si.com/test.html
If you try to open devtools u see "Pause on debugging" on top of page. 
This because inside that page there is a code like this:
`var testR1si = setInterval(function(){
debugger;
console.log("go on");
},1000);`
As you can see there is a continuous debugger.

I need to scarping this page with headless mode, but when go to headless debug address (eg: http://127.0.0.1:9299 )  see the same problem. (Pause on debugging)

There is same method to prevent all debugger on page, or disable all breakpoints?

**Comment by r1si** [comment]
any advice?

**Comment by huanganqing** [comment]
This is useful for sites like http://wenshu.court.gov.cn/.

**Comment by r1si** [comment]
At this time, I think there isn't solution 👎

**Comment by Zebraslive** [comment]
You need to loop all intervals and timeouts and delete them.
```
await page.evaluateOnNewDocument(() => {
  function ffx() {
var id = window.setTimeout(function() {}, 0);

while (id--) {
   window.clearTimeout(id); // will do nothing if no timeout with id is present
}
            window.Activate = function(){};
    window.activate = function(){};
var interval_id = window.setInterval("", 9999); // Get a reference to the last
                                               // interval +1
for (var i = 1; i < interval_id; i++)
       window.clearInterval(i);
//for clearing all intervals

   }
   setInterval( ffx, 1000);
 });
```
this usually works but might need to run it at a certain time.

**Comment by howiezhao** [comment]
Does anyone have good methods and suggestions?

**Comment by pilate** [comment]
After spending some time trying to deal with this, I came across the [`Debugger.setBlackboxPatterns`](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setBlackboxPatterns) method. This seems to disable use of the debugger by scripts with a source URL matching specified patterns. 

I'm using a different library, but it should be something like this with puppeteer:

    client.send("Debugger.setBlackboxPatterns", {
        patterns: [".*"]
    });

**Comment by Zebraslive** [comment]
I just found this https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra 
              
the stealth plugin might help.
```
// Add stealth plugin and use defaults (all tricks to hide puppeteer usage)
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
```
