### ISSUE TITLE
Multiple Chrome instances randomly fail in Windows Server 2012

### ISSUE THREAD

**Issue by dviktorov** [puppeteer/puppeteer#5266]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Windows Server 2012 R2, RAM 256 GB, Xeon with 40 cores
* URLs (if applicable):
* Node.js version: 9.9.0
* Chrome version: 77.0.3865.120 (Official Build) (64-bit)

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run 100 parallel instances of any puppeteer test (e.g. in Java thread pool)
2. Tried using Chrome with different arguments but the result is still the same.
3. Using a unique user-data-dir argument doesn't change the issue.

**What is the expected result?**
All 100 parallel tests should be completed

**What happens instead?**
20-40 puppeteer instances randomly fail with message "Failed to launch Chrome!". The exception stack refers to message_window.cc(112): Failed to create a message only window: The parameter is incorrect (0x57)

The rest of puppeteer test instances completes correctly.

If number of puppeteer test instances is reduced to 50, then all of them succeed.

**Comment by nicoandmee** [comment]
I can't speak to the exact technical reasoning, but I had similar issues. As I recall, this has to do with running out of file handles for the puppeteer instances (I was running on Ubuntu at the time). That being said, you have some pretty good hardware, and you are on Windows, so that's very interesting. Perhaps @aslushnikov can help.

**Comment by dviktorov** [comment]
@nicoandmee Thank you for sharing your experience! To see if crashes are related to system limits, we tried running tests under another user (previously it was the 'local system account') and all 100 instances successfully started. We also tried 200 instances and all of them started as well. It seems only the system user has this issue.

**Comment by gorkemhacioglu** [comment]
Hi @dviktorov , 
I have the same issue. Do you have any update about this issue?

**Comment by alexandrereyes** [comment]
My problem was IIS! Even with admin account, my program couldn't launch too much instances....
The solution was: 
1) host my program through Windows Service https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio
2) Use IIS as reverse proxy
https://medium.com/@gusterwoei/how-to-configure-reverse-proxy-on-windows-iis-52a48b90163a
