### ISSUE TITLE
Cannot connect to running instance of chrome

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#5271]
I run chrome with :
`start chrome.exe --remote-debugging-port=9222 --no-first-run --no-default-browser-check`

Then I run this script
```
const puppeteer = require('puppeteer-core');
(async()=> {
    const browser = await puppeteer.connect({
        browserURL : "http://localhost:9222"
    });

})()

```
Got an error: 
`connect ECONNREFUSED 127.0.0.1:9222`

I also try to open localhost:9222 or 127.0.0.1:9229 in browsers: nothing happens.
Any idea ?

Regards

**Comment by tchan** [comment]
What do you see when you run `netstat -a -o` in your cmd terminal?

I've had this issue on a few work machines intermittently and it seems to be an issue with their firewall. You should check if 127.0.0.1:9222 is displayed in the output in a listening/established state
