### ISSUE TITLE
Puppeteer triggers captcha always and I can  never complete it..

### ISSUE THREAD

**Issue by ddm4313** [puppeteer/puppeteer#5273]
```
  puppeteer.launch({executablePath: "C:/Users/DDM/AppData/Local/Google/Chrome/Application/chrome.exe", headless: false, slowMo:10, ignoreDefaultArgs: ['--enable-automation'], args: ["--proxy-server=http://" + proxy]}).then(async browser => {
  const page = await browser.newPage()
```
These are my launch options, any site I try with captcha, it does not work. Tried Chromium and Chrome.

**Comment by nicoandmee** [comment]
Perhaps it might be helpful if you shared the site you are encountering that is presenting you with the captcha, and of what variety captcha it is. I'm happy to help but I'm also not sure what the rules are for issues, I suspect they don't encompass these kinds of problems (captcha can't be solved).

**Comment by ddm4313** [comment]
> Perhaps it might be helpful if you shared the site you are encountering that is presenting you with the captcha, and of what variety captcha it is. I'm happy to help but I'm also not sure what the rules are for issues, I suspect they don't encompass these kinds of problems (captcha can't be solved).

Any site that has captcha (recaptcha v2). captcha like this https://patrickhlauke.github.io/recaptcha/

**Comment by ddm4313** [comment]
It just says that i'm using a bot.

**Comment by nicoandmee** [comment]
Take a look at my repo: [puppeteer-theater](https://puppeteer.theater). Look specifically inside the `classes/puppeteer-bot-2a.js` file. Just chill it is a lot of code but I want to point out the functions you are looking for.

Search for `disguisePage` and feel free to copy it I guess, though you are going to run into problems if you can't understand at least the gist of what's going on here to disguise the bot. This function takes a page, browserContext, and some basic properties so it can be easily extracted from this class file.

Next, for solving captchas: Search for `resolveCaptcha` & `resolveAntiCaptchaTask`. Pull these out and implement them as you need. If you haven't realized yet, to get around this you will also need a captcha solving provider. I recommend AntiCaptcha. Find the docs here: https://anti-captcha.com/apidoc/image. 


You should want something like ` const { gRecaptchaResponse } = await resolveCaptchaTask({
      type: 'NoCaptchaTaskProxyless',
      websiteURL: page.url(),
      websiteKey,
    });`

gRecaptchaResponse here is the solution you need to set to `document.querySelector('#g-recaptcha-response').value` & `document.querySelector('#g-recaptcha-response').innerText`.

**Comment by nicoandmee** [comment]
To clarify the above:
Step (1): Implement antidetection in your code so you are less likely to even see a captcha.
Step (2): Add functions to handle solving captchas if you do see them.

**Comment by ddm4313** [comment]
> To clarify the above:
> Step (1): Implement antidetection in your code so you are less likely to even see a captcha.
> Step (2): Add functions to handle solving captchas if you do see them.

Thank you.

**Comment by geekbleek** [comment]
> Take a look at my repo: [puppeteer-theater](https://puppeteer.theater). Look specifically inside the `classes/puppeteer-bot-2a.js` file. Just chill it is a lot of code but I want to point out the functions you are looking for.
> 
> Search for `disguisePage` and feel free to copy it I guess, though you are going to run into problems if you can't understand at least the gist of what's going on here to disguise the bot. This function takes a page, browserContext, and some basic properties so it can be easily extracted from this class file.
> 
> Next, for solving captchas: Search for `resolveCaptcha` & `resolveAntiCaptchaTask`. Pull these out and implement them as you need. If you haven't realized yet, to get around this you will also need a captcha solving provider. I recommend AntiCaptcha. Find the docs here: https://anti-captcha.com/apidoc/image.
> 
> You should want something like ` const { gRecaptchaResponse } = await resolveCaptchaTask({ type: 'NoCaptchaTaskProxyless', websiteURL: page.url(), websiteKey, });`
> 
> gRecaptchaResponse here is the solution you need to set to `document.querySelector('#g-recaptcha-response').value` & `document.querySelector('#g-recaptcha-response').innerText`.

@nicoandmee is puppeteer-theater repo still available, or a recommended alternative? :) Thanks!!!

**Comment by paulogc** [comment]
I've seem these two soluctions, but both envolve [2captch](https://2captcha.com/?from=9148648) which is paid:

https://github.com/berstend/puppeteer-extra/tree/c5828dd01333b6dbb15d74e63d9b866b2b2ff2a6/packages/puppeteer-extra-plugin-recaptcha

https://medium.com/@jsoverson/bypassing-captchas-with-headless-chrome-93f294518337

**Comment by alexsokolianskiy** [comment]
@geekbleek https://github.com/dcubasoy/puppeteer-theater/blob/master/classes/puppeteer-bot-2a.js it is a link.
