### ISSUE TITLE
puppeteer is closing the browser before running all the jest tests

### ISSUE THREAD

**Issue by anikethsaha** [puppeteer/puppeteer#5274]
### Steps to reproduce

- `git clone https://github.com/anikethsaha/docsify`
- `git checkout`e2e-test-puppeteer`
- `npm i`
- `npm run test:e2e`
- **check the tests for `sideBar.spec.js`**

It will fail are running 31 tests out of 122 tests

**Tell us about your environment:**

- Puppeteer version: ^2.0.0
- Platform / OS version: windows 10
- URLs (if applicable): https://travis-ci.org/docsifyjs/docsify/jobs/631003978?utm_medium=notification&utm_source=github_status
- Node.js version: v10.15.3

**What steps will reproduce the problem?**
`npm run test:e2e`

_Please include code that reproduces the issue._

1. https://github.com/anikethsaha/docsify/blob/e2e-test-puppeteer/e2e/__tests__/sideBar.spec.js
2.
3.

**What is the expected result?**
It should run all the test cases 122

**What happens instead?**
But instead, its running only 31 tests and the browser is closing after that and then remaining 91 tests are not running

**Context**

I am using [`live-server`](https://github.com/tapio/live-server) to run a server that will serve my files and it is being done in a custom jest environment.
I have a `sideBar.spec.js` file which tests all the sidebar links by clicking them and then taking a snapshot using [`jest-image-snapshot`](https://github.com/americanexpress/jest-image-snapshot#readme).
In this test, I am clicking every possible anchor links using the `page.click` method.
it is not running the remaining 91 tests.
**I increased the timeout to 300 sec** but still, it's stopping before that.

I saw a weird behavior that is, the sidebar comes with a toggle button. So by default that sidebar is open. But before exiting of closing the browser, IDK but it's toggling the sidebar to close it and then closing the browser.
**check the tests for `sideBar.spec.js`**
You can find the behavior of the test here https://travis-ci.org/docsifyjs/docsify/jobs/631003978?utm_medium=notification&utm_source=github_status

**Comment by Kradirhamik** [comment]
I am facing the same issue on my project. I have traced this to a bigger issue where the waitForSelector and page.click trigger timeouts as well. But having a fix on Puppeteer + Jest would be a good starting point

**Comment by anikethsaha** [comment]
> I am facing the same issue on my project. I have traced this to a bigger issue where the waitForSelector and page.click trigger timeouts as well. But having a fix on Puppeteer + Jest would be a good starting point

Did you find the workaround?

**Comment by Kradirhamik** [comment]
Unfortunately, I have not.

Is puppeteer being actively maintained by someone from Google Chrome? Seems like the updates and fixes have slowed down.

**Comment by trusktr** [comment]
No reply here from anyone at Google in half a year, which isn't a good sign. This is normal for personal projects by individuals, but not for projects backed by big companies.

**Comment by Kradirhamik** [comment]
Project is being maintained again. Let's now just wait some years until they find this ticket 😃
