### ISSUE TITLE
Here is how I got around client cert authentication, hope it helps others.  Basically just intercept the request, then fire the request off yourself using your favorite httpclient lib, and repond to the intercepted request with the response info.

### ISSUE THREAD

**Issue by ElderVivot** [puppeteer/puppeteer#5275]
This post is asked how to successfully enter the digital certificate on a particular site that requires such authentication. I tried to do the @dapriett process with a slight modification which is changing the .crt and .key to the .pfx according to what @camjackson suggested but always gives the error below:

-----------------------------------------------------
{ Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
-----------------------------------------------------

my code looks like this:

```
'use strict';

const puppeteer = require('puppeteer')
const fs = require('fs')
const request = require('request');

(async() => {
    const browser = await puppeteer.launch()

    let page = await browser.newPage()

    await page.setViewport({ width:0, height:0 })
    
    await page.goto('http://nfe.sefaz.go.gov.br/nfeweb/sites/nfe/consulta-publica/principal')

    await page.setRequestInterception(true);

    const pfx = fs.readFileSync('C:/temp/agf_cert.pfx');
    const password = 'password'
    
    await page.waitFor(3000)

    page.on('request', interceptedRequest => {
        // Intercept Request, pull out request options, add in client cert
        const options = {
            uri: interceptedRequest.url(),
            method: interceptedRequest.method(),
            headers: interceptedRequest.headers(),
            body: interceptedRequest.postData(),
            pfx: pfx,
            passphrase: password,
        };

        // Fire off the request manually (example is using using 'request' lib)
        request(options, function(err, resp, body) {
            // Abort interceptedRequest on error
            if (err) {
                console.error(`Unable to call ${options.uri}`, err);
                return interceptedRequest.abort('connectionrefused');
            }

            // Return retrieved response to interceptedRequest
            interceptedRequest.get({
                status: resp.statusCode,
                contentType: resp.headers['content-type'],
                headers: resp.headers,
                body: body
            });
        });

    });

    await page.click("a[href*='nfe/consulta-publica'] button")
    
    await page.waitFor(2000)
    
    browser.close()
})()
```

Has anyone been able to log in with the certificate of agreement mentioned above without error? Or does anyone know how to resolve the error I mentioned above?

**Comment by carbuz2** [comment]
@ElderVivot try with these options:

        const options = {
          uri: interceptedRequest.url(),
          method: interceptedRequest.method(),
          headers: interceptedRequest.headers(),
          body: interceptedRequest.postData(),
          gzip: true,
          agentOptions: {
              pfx: pfx,
              passphrase: password,
              securityOptions: 'SSL_OP_NO_SSLv3'
          }
        };


It should fix your autentication problem... in my case however, for another website, I'm not able to dowload some resources (js, css files) after it

**Comment by Raffsx** [comment]
@carbuz2 
Hi, I tried the code you provided, but the following error occurs:


"Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
Process exited with code 1"

Has anyone managed to log in using certificate?

**Comment by carbuz2** [comment]
In the end I was not able to do it using puppeteer... 
I used casperjs instead (phantomjs worked as well if I remember correctly).
The terminal  command is: 

`casperjs --ssl-client-certificate-file=${pathCertPem}   --ssl-client-key-file=${pathKeyPem}  --ssl-client-key-passphrase=${passphrase}  --ignore-ssl-errors=true     ${yourCasperFile}`

**Comment by ldrahnik** [comment]
My workaroud is use headfull puppeter running in docker without GUI using xvfb:

## Docker

1. Install Google Chrome & xvfb

```
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update
RUN apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget x11vnc x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps
RUN apt-get install -yq xvfb google-chrome-stable
```

2. Add SSL certificate to Google Chrome

```
RUN apt-get install -yq libnss3-tools
RUN mkdir -p $HOME/.pki/nssdb
RUN pk12util -d sql:$HOME/.pki/nssdb -i /tmp/cert.pfx -w /tmp/cert.pfx.pass
```

3. Set up autoselecting added SSL certificate in Google Chrome

```
{ "AutoSelectCertificateForUrls": ["{\"pattern\":\"*\",\"filter\":{\"ISSUER\":{\"CN\":\"XY name\"}}}"]}

mkdir -p /etc/opt/chrome/policies/managed
cp policy.json /etc/opt/chrome/policies/managed
```

4. Run nodejs part with rendering redirected to xvfb

```
CMD xvfb-run --setver-args='-screen 0 1024x768x24" node index.js
```


## Nodejs

1. Install npm Puppeteer package

```
npm install puppeteer
```

2. Run Puppeteer

```
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome-stable', headless: false, args: [' - no-sandbox',' - disable-setuid-sandbox'] }); 
```

Tested on [render.com](http://render.com/). [Example project](https://github.com/PRO-OC/pro-oc-vzp-point-proxy).  [More detailed Medium story](https://medium.com/@ldrahnik/headfull-puppeter-running-in-docker-without-gui-12d983e50920)
