### ISSUE TITLE
Unable to generate PDF using Unicode on lambda

### ISSUE THREAD

**Issue by dhavalocked** [puppeteer/puppeteer#5276]
I have generated HTML by feeding data into the EJS template and then I created PDF using puppeteer to upload on s3.  Things work as expected locally However when I deploy my lambda using serverless generated PDF shows boxes instead of Unicode chars.

Here is the [sample HTML](https://pastebin.com/8GugUwL1) file that is generated using the EJS template.

Sample [PDF](https://recommended-tests.s3.ap-south-1.amazonaws.com/e955a5a1-c123-49ee-a799-bbdaeaf4a144) generated while running serverless offline.

Sample [PDF](https://recommended-tests.s3.ap-south-1.amazonaws.com/4fb424d3-483b-44df-8d66-ee34415ec966) generated after deploying my service to AWS lambda.

### Here is a code I used to convert HTML to PDF

```javascript
   const template = ejs.compile(file);
   const html = template({ data });
   // Generate html is provided as a sample file
   let browser = null;
    try {
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: executablePath
    });
    const page = await browser.newPage();
    page.setContent(html);
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '1cm', right: '1cm', bottom: '1cm', left: '1cm' }
    });
    return pdf;
  } catch (error) {
    console.log('ERROR creating PDF file => ', error);
  }
```

### upload to s3 function .
```javascript
AWS.config.setPromisesDependency(require('bluebird'));

  AWS.config.update({
    accessKeyId: process.env.ACCESS_KEY,
    secretAccessKey: process.env.SECRET_KEY
  });

  const s3 = new AWS.S3();

  const params = {
    ACL: 'public-read',
    Body: pdf, //returned by the code function above
    Bucket: process.env.BUCKET,
    Key: uuidv4(),
    ContentEncoding: 'base64',
    ContentType: `application/pdf`
  };
  try {
    const { Location, Key } = await s3.upload(params).promise();
    return Location;
  } catch (error) {
    console.log('ERROR S3 FILE UPLOAD => ', error);
  }
```

As puppeteer supports Unicode which is working correctly in local, Shouldn't it work similarly once I deploy?

**Comment by swapnil-shukla-cp** [comment]
Any update on this. facing the same issue.

**Comment by mayurcp** [comment]
> Any update on this. facing the same issue.

Let us know if you have any solution to this.
