### ISSUE TITLE
page break is not working!!! await page.emulateMediaType('screen') 

### ISSUE THREAD

**Issue by tmswartz12** [puppeteer/puppeteer#5277]
**I am attempting to create a PDF of my screen using** 
```
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    })
    console.log('browser has been opened')
    const page = await browser.newPage()
    page.setViewport({width: 1000, height: 1056})
    await page.waitFor(1000)
    await page.emulateMediaType('screen')
    await page.waitFor(5000)
    console.log('about to create PDF - standby')
    const pdf = await page.pdf({
      format: 'Letter',
      printBackground: true,
      path: MY PATH
    })
    console.log('pdf created')
    await browser.close()
    console.log('browser closed')
  }
```

 **Locally.. my PDF is returned to my browser with the proper sizing and formatting.. however. when running in production.. my formatting / margins are off..** 

This creates awkward page breaks in the middle of my content and is not suitable for my client!

I am using `"puppeteer": "^2.00.0"` and node version `8.16.2`

I am using heroku as my server.

Thanks in advance for your help!!!

**Comment by tmswartz12** [comment]
Here is a picture of my current PDF.. the page is not breaking in the appropriate place.. however it is working on my local machine!!

<img width="1082" alt="Screen Shot 2020-01-08 at 3 39 58 PM" src="https://user-images.githubusercontent.com/31495981/72014061-2aba7000-322d-11ea-8334-1d1df80f41d5.png">

**Comment by tmswartz12** [comment]
Seems like puppeteer has some issues with @media print.. I just tried updating my CSS to..
```
@media print {
    .page {
        page-break-after: always;
    }
}

No luck!!

**Comment by radonichn** [comment]
As for me, the problem was, that the .page was a flexbox. Check it out.

**Comment by tmswartz12** [comment]
Ahhhh. so flexbox and page-break-after aren't compatible? Will have to test it. 

Ultimately, I developed a work around that did not include Puppeteer. I just formatted my page components to be the size of the browser and then allow the user to print manually from chrome. Not as sexy as sending a scraped Puppeteer PDF being passed via Sendgrid... but got the job done!

**Comment by ghost** [comment]
You should remove flexbox style in parent element not the element itself.

```
<div style={{display: 'flex'}}> ---> you should change this one to non-flexbox style
  <div style={{pageBreakAfter: 'always'}}/>
  <div/>
<div/>
```

**Comment by RodolfoSilva** [comment]
@SeungjongHan Thanks for the tip, it worked great!

**Comment by FelipeRodriguesBonilha** [comment]
Removing display flex and grid from the div that I needed to implement the page break resolved it for me. For some reason, the puppeteer does not recognize the break when it has the previously mentioned displays.
