### ISSUE TITLE
Chrome zombie process on Ubuntu

### ISSUE THREAD

**Issue by Yangeok** [puppeteer/puppeteer#5279]
* Puppeteer version: 1.19.0
* Platform / OS version: Windows 10, Ubuntu 16
* URLs (if applicable):
* Node.js version: 12.13.1

The memory leak issue is caused by the chrome zombie process as shown below. Clearly, I closed the page and browser.

```sh
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:33268         0.0.0.0:*               LISTEN      16312/chrome
tcp        0      0 127.0.0.1:44663         0.0.0.0:*               LISTEN      6967/chrome
tcp        0      0 127.0.0.1:42206         0.0.0.0:*               LISTEN      13966/chrome
tcp        0      0 0.0.0.0:10022           0.0.0.0:*               LISTEN      1239/sshd
tcp        0      0 127.0.0.1:41864         0.0.0.0:*               LISTEN      4205/chrome
tcp        0      0 127.0.0.1:35405         0.0.0.0:*               LISTEN      5656/chrome
tcp        0      0 127.0.0.1:40624         0.0.0.0:*               LISTEN      4286/chrome
tcp6       0      0 :::3030                 :::*                    LISTEN      2597/index.js
tcp6       0      0 :::10022                :::*                    LISTEN      1239/sshd
```

`await browser.close()` works fine on windows, but on Linux it does not work intermittently, resulting in numerous zombie processes. So a memory leak occurred.

So, after using `browser.disconnect()` instead of `browser.close()`, I tried to handle it using the event listener as shown below. But it doesn't seem to work at all. `console.log ()` is not printed.

```js
browser.disconnect()
browser.on('disconnected', () => console.log('disconnected'))
```

If you have dprecated api please tell me.

===========
Reference: #1825

**Comment by ralyodio** [comment]
Am I doing this right?

```
async function spa(url) {
	let htm;

	try {
		const page = await browser.newPage();
		await page.goto(url, { waitUntil: "domcontentloaded" });
		htm = await page.content();
	} catch(err) {
		console.log(err, url);
	} finally {
		await browser.close();
		await browser.disconnect()
	}

	return htm;
}

```

I still get a ton of chrome instances not closing (docker/alpine)

**Comment by Yangeok** [comment]
I guess the `browser.disconnect()` method still does not work properly..

**Comment by ralyodio** [comment]
i get different errors now.

**Comment by Yangeok** [comment]
Can you show me the error log?

**Comment by alexellis** [comment]
I'm seeing similar with the [buildkite docker image](https://github.com/buildkite/docker-puppeteer) after using `await` with close and then disconnect.

```
...
app         2310       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2346       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2347       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2360       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2379       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2387       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2388       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2420       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2421       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2438       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2440       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2445       1  0 14:52 ?        00:00:00 [chrome] <defunct>
app         2530       0  0 14:53 pts/3    00:00:00 ps -ef
```

**Comment by Yangeok** [comment]
@alexellis 
I guess it was also caused by not enough memory to the container environment.

The issue I raised above doesn't happen if allocated machine memory higher. If there's no zombie process issue in [playwright](https://github.com/microsoft/playwright), I'mma migrate to it. You should consider it.

**Comment by alexellis** [comment]
I found a resolution and shared it on the linked issue

**Comment by ralyodio** [comment]
where?

**Comment by Yangeok** [comment]
@alex2844 
There's no linked issue T^T

**Comment by alexellis** [comment]
https://github.com/buildkite/docker-puppeteer/issues/142

And the repo

https://github.com/alexellis/openfaas-puppeteer-template

If you're interested in using faasd there's a blog post linked to it and it supports queuing and running on a low spec VPS too.

**Comment by alexellis** [comment]
@chovy @Yangeok

**Comment by xpader** [comment]
You should use tini as parent process, that resolve the problem.
