### ISSUE TITLE
page.setContent should invoke evaluateOnNewDocument?

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#528]
Consider:
https://github.com/GoogleChrome/puppeteer/blob/0791774faa78f2a6e2e3a5185c1e266feeecdc91/lib/Page.js#L324-L333

This is essentially creating a new document and replacing the current page with it. 

My assumption would be that calling `page.setContent()` would invoke `page.evaluateOnNewDocument`'s callback.

Thoughts?

**Comment by aslushnikov** [comment]
Current implementation doesn't recreate a document - it reopens it. I think it's fine for the `page.evaluateOnNewDocument` to not be called.

If you want `page.evaluateOnNewDocument` to be called, you can navigate to a data URL:
```js
await page.setContent(html);
// Another way
await page.goto('data:text/html,' + html);
```

**Comment by ebidel** [comment]
`document.open()` doesn't create a new document per se, but the effect is the same. Essentially you're starting from a fresh document. It nukes everything. From that perspective, "evaluateOnNewDocument" does make some sense.

I'm not 100% sold on this either. Just wanted to flag it b/c of the subtlety.

**Comment by aslushnikov** [comment]
(as discussed offline on puppeteer meeting)

**Comment by ebidel** [comment]
Maybe add a clarification/note in the docs that `setContent` reuses the existing document, so `Page.evaluateOnNewDocument` won't trigger?

**Comment by aslushnikov** [comment]
@ebidel sure!

**Comment by 4074** [comment]
I add a script tag in the html. It works.
```js
await page.setContent('<script>window.a = 1</script>' + html);
```
