### ISSUE TITLE
Set up network interface in a Puppeteer

### ISSUE THREAD

**Issue by lolo169** [puppeteer/puppeteer#5280]
Hi,

I need to run a puppeteer script on a website with different IPs.
(ads, prices etc depends on IP localisation).

I set up a server with various europeans IPs.
It works just fine testing it with curl --interface 

Is it possible to set up network interface in your puppeteer script?
(I've already tested --proxy-server argument with proxies vendor, it works but it's a bit expensive)   

Thanks for your help

**Comment by leaderiop** [comment]
i searching for the same solution too

**Comment by kblok** [comment]
The is nothing in puppeteer for that out-of-the-box. You will the to build something around puppeteer, like https://r1ch.net/projects/forcebindip.

**Comment by lolo169** [comment]
It's only for Windows.
The flag "netifs-to-ignore" to pass to Chromium doesn't work for me on Ubuntu.
It's strange there is no solution for what looks a common problem!

**Comment by AndreyBarzukov** [comment]
I have the same issue...

**Comment by esellier** [comment]
A bit late for that answer, but if I understand well you have many IPs (so many network interfaces I guess).
Then you may run a shell script (as root...) from the Node or before running Node and change the "source IP":


```
r=$(( $RANDOM % 5 ))
case $r in
	0) /sbin/ip route change default via __HERE YOUR DEFAULT GW__ dev eth0:1 src __IP OF ETH0:1__ ;;
	1) /sbin/ip route change default via __HERE YOUR DEFAULT GW__ dev eth0:2 src __IP OF ETH0:2__ ;;
	2) /sbin/ip route change default via __HERE YOUR DEFAULT GW__dev eth0:0 src __IP OF ETH0:0__ ;;
	3) /sbin/ip route change default via __HERE YOUR DEFAULT GW__dev eth0 src __IP OF ETH0__ ;;
	4) /sbin/ip route change default via __HERE YOUR DEFAULT GW__ dev eth0:3 src __IP OF ETH0:3__ ;;
	*) /sbin/ip route change default via __HERE YOUR DEFAULT GW__ dev eth0 src __IP OF ETH0__ ;;
esac
```
