### ISSUE TITLE
css box-shadow properties can not correct show in pdf

### ISSUE THREAD

**Issue by tanghuai** [puppeteer/puppeteer#5284]
* Puppeteer version:2.0.0
* Platform / OS version: 10.14.2
* URLs (if applicable):
* Node.js version:v12.13.0

Hello, I have a strange problem
when I create pdf file
I found css box-shadow properties  can not correct surport

in chrome 
![image](https://user-images.githubusercontent.com/6182916/71810804-33d10300-30ae-11ea-9963-e977b58b34ea.png)

but in pdf 
![image](https://user-images.githubusercontent.com/6182916/71810847-48ad9680-30ae-11ea-9940-928376095d20.png)

some dom element also have box-shadow properties
it can correct render
just like 
![image](https://user-images.githubusercontent.com/6182916/71810935-785c9e80-30ae-11ea-9bad-b80f3db025c2.png)

then I  write some test code 
![image](https://user-images.githubusercontent.com/6182916/71811254-29fbcf80-30af-11ea-9bba-56e9e4722f92.png)
![image](https://user-images.githubusercontent.com/6182916/71811276-38e28200-30af-11ea-8bda-96b7f6ddbcbe.png)

what's wrong?

**Comment by tanghuai** [comment]
I try  add -webkit-box-shadow ,but not work

**Comment by kblok** [comment]
Do you get this if you print to PDF using chrome?

**Comment by igwall** [comment]
get the same issue... did you find a solution ? 
Thanks 👍

**Comment by plaffitt** [comment]
I'm searching for a solution too

**Comment by marentdev** [comment]
Solution found for me via StackOverflow

```css
html {
    -webkit-print-color-adjust: exact;
    -webkit-filter: opacity(1);
}

**Comment by tanghuai** [comment]
> Solution found for me via StackOverflow
> 
> ```css
> html {
>     -webkit-print-color-adjust: exact;
>     -webkit-filter: opacity(1);
> }
> ```

is not work for me :(

**Comment by tanghuai** [comment]
> Do you get this if you print to PDF using chrome?

yes. chromium. headless mode

**Comment by bohdan-casafari** [comment]
**My case:** box-shadow: 2px 2px 15px rgba(0, 0, 0, .15); 

> Solution found for me via StackOverflow
> 
> ```css
> html {
>     -webkit-print-color-adjust: exact;
>     -webkit-filter: opacity(1);
> }
> ```

Thanks
Works for me)

**Comment by trantorLiu** [comment]
> Solution found for me via StackOverflow
> 
> ```css
> html {
>     -webkit-print-color-adjust: exact;
>     -webkit-filter: opacity(1);
> }
> ```

I tried

```css
html {
    -webkit-print-color-adjust: exact;
    -webkit-filter: opacity(1);
}
```
**But it causes links on PDF non-clickable for unknown reason.**

After I change it to the css below, both shadow and link problems are solved.
```css
.thing {
    -webkit-print-color-adjust: exact;
    -webkit-filter: blur(0);
}
```

**Comment by maxime-helen** [comment]
Beware below fix 
```
html {
    -webkit-print-color-adjust: exact;
    -webkit-filter: opacity(1);
}
```
 increased 6x pdf size (from 1.8MB to 12MB)

Narrowing down css assignment to where shadows are displayed fixed it

**Comment by wkndmarkt** [comment]
> Beware below fix
> 
> ```
> html {
>     -webkit-print-color-adjust: exact;
>     -webkit-filter: opacity(1);
> }
> ```
> 
> increased 6x pdf size (from 1.8MB to 12MB)
> 
> Narrowing down css assignment to where shadows are displayed fixed it

Agree !
This solution seems to wrap a screenshot into a pdf, thus increasing the size, and losing the vector benefits of a pdf file.

[edit]
From my last tests, as @trantorLiu suggested, just adding
> await page.addStyleTag({ content: '.box-shadow-class {-webkit-filter: blur(0);}'})

in the node script fixes the problem.

**Comment by duncan-oxd** [comment]
Experiencing this when running Puppeteer locally
Puppeteer v15.1.0
Mac OS 12.4 / Apple M1 Pro

`print-color-adjust: exact` mentioned above does make the box-shadows look better, but it makes the text unselectable and the size of the file much larger.

I never noticed this in the past on other systems with other versions of Puppeteer, for what it's worth.
~~edit: Doesn't seem to be happening in a serverless Linux environment with `puppeteer-core` and `chrome-aws-lambda`, so it could be an issue with Chrome on MacOS~~

edit 2: Oh, wait... Maybe it's just the "Preview" app that renders the shadows that way... They look okay if I open the PDF in Chrome or Firefox. Though the shadows are a bit darker in Firefox. I'm starting to question my understanding of what a PDF even is, if these shadows render so differently in each program.

**Comment by carstenschwede** [comment]
Bump.

**Comment by grishy** [comment]
You can use Firefox in this case. Works fine!

**Comment by john8329** [comment]
Sorry for deadposting, but I'm encountering the same. The workaround provided a temporary fix to this bug.

**Comment by mralston** [comment]
I don't think it's a Puppeteer problem, I believe it's headless Chromium.

I'm using [chrome-php/chrome](https://packagist.org/packages/chrome-php/chrome), which remote controls headless Chromium in the same way as Puppeteer, but without using Puppeteer. I'm observing the same problem.

**Comment by lahdekorpi** [comment]
For anyone hitting this same issue still in [enter current year], a good workaround is to use [Puppeteer's Firefox support](https://hacks.mozilla.org/2024/08/puppeteer-support-for-firefox/) as almost a drop-in replacement. Noticed that the file size went from tens of megabytes to 200KB in my case and the rendering uses actual vectors instead of rasterized contents.

Firefox has lots of rendering issues overall, completely outside of the scope of this, but if your goal is to render PDF on a controller environment, I would suggest giving it a try.
