### ISSUE TITLE
page.on( 'request' ) doesn't work

### ISSUE THREAD

**Issue by vrg-success** [puppeteer/puppeteer#5287]
### page.on( 'request' ) doesn't work if making ajax request

**Tell us about your environment:**
* Puppeteer version: 2.0.0
* Platform / OS version: Windows 10
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

```javascript
puppeteer
  .launch(options)
  .then(async browser => {
    const page = await browser.newPage();
    await page.goto('http://127.0.0.15:5500/index.html');

    // Listening all request
    page.on('request', request => console.log(request.url()));

    // Making ajax request, this button inserted from another JS file
    await page.click('#btn');
  })
```

**What is the expected result?**
Call console.log to show request url

**What happens instead?**
Nothing 😕

**Comment by kblok** [comment]
You have to call `await page.setRequestInterception(true);` first. [Example](https://github.com/puppeteer/puppeteer/blob/eddb23b52175a3dad8cec4a5e9b3c13e58f6f144/test/requestinterception.spec.js#L28)
