### ISSUE TITLE
Popup event does not fire when we do CMD + Click to open a page in new tab

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5296]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: OSX 10.15.2
* Node.js version: 12.14.0

**What steps will reproduce the problem?**
Run the following code

```
const puppeteer = require("puppeteer");

async function clickToOpenInNewTab(element, page) {
	await page.keyboard.down("MetaLeft");
	await element.click();
	await page.keyboard.up("MetaLeft");
	console.log("click to open in new tab");
}

(async () => {
	try {
		const browser = await puppeteer.launch({
			headless: false
		});

		const page = await browser.newPage();
		await page.goto("https://google.com/");

		console.log("on page and waiting for xpath");
		const aboutPath = "/html/body/div/div[4]/div[1]/a[1]";
		await page.waitForXPath(aboutPath);
		const elements = await page.$x(aboutPath);
		console.log("clicking and waiting for popup");
		const [popup] = await Promise.all([
			new Promise(resolve => page.once("popup", resolve)),
			clickToOpenInNewTab(elements[0], page)
		]);
		console.log("popup:", popup.url());
		console.log("all done");
	} catch (error) {
		console.log("error", error);
	}
})();

```

**What is the expected result?**
A `popup` event will fire.

**What happens instead?**
Promise to wait for `popup` fails.

Unsure if this is a chrome/chromium bug or puppeteer bug.

**Comment by kblok** [comment]
Opening a page with CMD click won't make it a popup.

**Comment by VikramTiwari** [comment]
@kblok I see! Is there some other way to ensure that I can capture the page that opened after I did CMD + Click?

```
const [newlyCreatedPage] = await Promise.all([
	new Promise(resolve => page.once("popup", resolve)), // something else here
	clickToOpenInNewTab(element, page)
]);
```

**Comment by kblok** [comment]
@VikramTiwari you could use the `waitForTarget` function on the browser class.

**Comment by VikramTiwari** [comment]
@kblok Yeah, but then `waitForTarget` fails to provide information about the opener because it's a top-level target. https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#targetopener I want a confirmation that the page that was opened, did open because of something that happened in current page.

**Comment by kblok** [comment]
I think you could do an evaluate and get the `window.opener`?

**Comment by VikramTiwari** [comment]
`window.opener` is always null in case of CMD + Click. I think `target.opener()` and `window.opener` share same origins.

**Comment by kblok** [comment]
So I'm afraid you won't be able to get that info :/

**Comment by VikramTiwari** [comment]
Hmm.. that's not ideal. If you don't mind, I will let this issue be open in case someone has a creative solution to this.
