### ISSUE TITLE
Return date from evaluate/evaluateHandle

### ISSUE THREAD

**Issue by Menighin** [puppeteer/puppeteer#5297]
Hi!

First, I've seen #376 and #382 that seems to be related to this problem.
What I understood from #382 is that now it should work fine...?

Anyway, I'm trying to return a `Date` from these methods but all I get is an empty object:

```
        const dateHandle = await page.evaluateHandle(() => new Date());
        const date = await dateHandle .jsonValue(); // {}

        const anotherDate = await page.evaluate(() => new Date()); // {}
```
I'm using `puppeteer 2.0.0`.

I'm doing some workaround returning the milliseconds and creating a date back on my node app, but that's ugly.

Is it a bug? How can I make this work? 😕 

Thanks!

**Comment by gerardnico** [comment]
As far as I can read, you cannot pass an object if it's not serializable.
https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args

Which means that you need to stringify the date before returning the value.
Then parse and reconstruct a new date object.

This is because it seems that the data is wired via the DevTools Protocol that does not support passing native javascript object.

**Comment by Menighin** [comment]
But Javascript Date is serializable, no? I mean, we can `JSON.stringify()` it... or even call `toJSON()`...

**Comment by gerardnico** [comment]
Ye, you need to do it yourself.

**Comment by Menighin** [comment]
I don't get it. You (and docs) pointed out I cannot pass an object if its not serializable. But Date objects ARE serializable. So why can't I pass it and need to serialize myself? 

And yes, I already have an workaround on this. I'm just imagining if this isnt a bug since @aslushnikov pointed out the same thing on #376 (and the issue was close as it was solved...?)

**Comment by gerardnico** [comment]
The definition of serializable for the evaluate function is an object that is stringified. You need to parse it again back yourself (It's what I understand)

I made a page especially for you that shows how I do it.
https://gerardnico.com/web/browser/puppeteer_date

**Comment by fkirc** [comment]
I was also facing the same issue.
The solution of @gerardnico works (serialize it as a JSON-string to pass through page.evaluate).
Nevertheless, I think that this should be fixed by either Puppeteer or Chromium.
