### ISSUE TITLE
Add Cookies API

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#53]
There should be an API to access cookies.

**Comment by paulirish** [comment]
FWIW the [async cookie API](https://github.com/WICG/async-cookies-api/blob/gh-pages/explainer.md) is gaining steam and being implemented in chrome. Don't know if the API there is a good match for these usecases though.

Separately, I don't think this should be in the 0.1. We can ship without this.

**Comment by aslushnikov** [comment]
Discussed with @paulirish, pulling cookies out of this milestone since they seem to be not that important.

**Comment by shellscape** [comment]
@paulirish something to bear in mind: chrome currently has no support for cookies and the `file://` protocol - something users leveraging this for automated tests will surely want. (it looks like the `--enable-file-cookies` flag does bupkis this days)

**Comment by Garbee** [comment]
What is the use-case to have a cookie associated with a local file serve?

**Comment by shellscape** [comment]
@Garbee off of the top of my head; running local mocha tests that include automation tests. there are a litany of modules which utilize headless (and visible) browsers for testing in the browser via mocha, jasmine, etc. I'm running into this particular problem in mocha-chrome, which isn't really meant for automation out of the box, and I can see people who need automation using puppeteer for testing + automation.

**Comment by shellscape** [comment]
fwiw, I'm presently getting around this by injecting the following, using `Page.addScriptToEvaluateOnLoad` with some logic to check the protocol:

```js
  Object.defineProperty(document, 'cookie', {
    get: function () {
      return this.value || '';
    },
    set: function (cookie) {
      cookie = cookie || '';

      const cutoff = cookie.indexOf(';');
      const pair = cookie.substring(0, cutoff >= 0 ? cutoff : cookie.length);
      const cookies = this.value ? this.value.split('; ') : [];

      cookies.push(pair);

      return this.value = cookies.join('; ');
    }
  });
```

It 'aint pretty, and I'm loathe to do it, but it gets me by.

**Comment by barbolo** [comment]
Is it possible to support multiple profiles (or multiple cookie jars) for a single chromium launch?

Usage example: choose a user profile (or cookie jar) when creating a new Page object.

**Comment by aslushnikov** [comment]
@barbolo this will be covered with #85

**Comment by shellscape** [comment]
@aslushnikov that's only half true - context/sessions will be supported but there's been no public statement about cookies for chrome.

**Comment by aslushnikov** [comment]
@shellscape browser contexts isolate cookies

**Comment by shellscape** [comment]
@aslushnikov see https://github.com/GoogleChrome/puppeteer/issues/53#issuecomment-322866154

**Comment by barbolo** [comment]
That's great, @aslushnikov.

Can you confirm if each page has a different cookies context or if they all share the same cookies?

**Comment by aslushnikov** [comment]
@barbolo they share the same context. The #85 will do the isolation.
