### ISSUE TITLE
Click doesn't take zoom into account

### ISSUE THREAD

**Issue by melissachang** [puppeteer/puppeteer#5307]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Mac
* URLs (if applicable):
* Node.js version: v10.15.0

**What steps will reproduce the problem?**

Sorry I didn't write a minimal repro. I figure this should be easy to repro. I'm happy to write one if you want, just let me know.

1. In pptr window, either zoom in or out by a lot
2. Get an ElementHandle to a text box
3. Click on ElementHandle

**What is the expected result?**

Click in text box

**What happens instead?**

Click in text box as if zoom were 100%
But because zoom is not 100%, the click is in the wrong place.

**Comment by IKoshelev** [comment]
Just had the same issue. Very frustrating, especially considering that there looks to be no way to control browser zoom level from puppeteer. 

To reproduce run below script once, notice that it works (you should get to English wikipedia main page). Now run it again, but this time once page opens - change zoom to 150%. Now link will not be clicked. In my scenario my browser simply started at 150% zoom level.  

```javascript
const puppeteer = require('puppeteer');

puppeteer
    .launch({
        headless: false,
        defaultViewport: null
    })
    .then((browser) => browser.newPage())
    .then((page) => {
        page.goto("https://www.wikipedia.org")
            .then(() => new Promise(resolve => setTimeout(resolve, 4000)))
            .then(() => page.$("a#js-link-box-en"))
            .then(linkToEnglishVer => linkToEnglishVer.click());
    });
```

**Comment by dancingbannana** [comment]
a potential workaround is to use the mouse api to click on where puppeteer thinks the element is for example,
```
   async function click(el){
      const box = await page.evaluate(el => {
        const {x, y, width, height} = el.getBoundingClientRect();
        return {x, y, width, height};
      }, el);
      let x = box.x + (box.width/2);
      let y = box.y + (box.height/2);
      x *= viewPort.ratio;
      y *= viewPort.ratio;
      return page.mouse.click(x,y);
    }
```
viewPort.ratio is the current zoom factor of the page where 1.2 represents a 120% zoom. (getting this value is a different story)

**Comment by nilson-lagos** [comment]
I can confirm this is still happening

**Comment by OrKoN** [comment]
I am unable to reproduce using the script from the second comment using the latest Puppeteer version.  Note that the workaround in the comment #3 does not account for elements inside the out-of-process iframes.  If the issue still happens, please re-open with the updated repro.
