### ISSUE TITLE
New download location for puppeteer-firefox 0.5.1 does not include windows build

### ISSUE THREAD

**Issue by aptomaKetil** [puppeteer/puppeteer#5310]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-firefox v0.5.1
* Platform / OS version: Windows
* Node.js version: 12.13.1

**What steps will reproduce the problem?**

Running `npm install puppeteer-firefox` on windows.

**What is the expected result?**

`puppeteer-firefox` downloads a build of Firefox as part of the install.

**What happens instead?**

The new download location added in #5293 returns 404 for the win32 build. Both mac and linux work as expected.

```
> puppeteer-firefox@0.5.1 install C:\<snip>\node_modules\puppeteer-firefox
> node install.js
ERROR: Failed to download Firefox rv0.0.1!
Error: Download failed: server returned code 404. URL: https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win32.zip
```

**Comment by Vyshakh-01** [comment]
I am also facing the issue, 0.5.1 is working fine on Linux but when I try to run on windows I am getting the same Error
