### ISSUE TITLE
Non-English characters are showing as rectangle boxes.

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#5311]
### Steps to reproduce

**Environment Details:**

* Puppeteer version: puppeteer-core : 2.0.0
* Platform / OS version: AWS Lambda
* URLs (if applicable): http://dir.hinkhoj.com
* Node.js version: 10

_Code that reproduces the issue._
```
  const browserConfig = {
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless
  }
  console.log('launching the browser');
  browser = await puppeteer.launch(browserConfig);

  const page = await browser.newPage();
  await page.goto('http://dir.hinkhoj.com');

  await page.screenshot({fullPage: true});
```

**What is the expected result?**
Website contains Hindi language fonts which are not rendering.

**What happens instead?**
It's showing Hindi fonts as rectangle boxes. It's happening on AWS Lambda only.

**Comment by kblok** [comment]
I think this is more related to the AWS environment. Did you take a look at posts like this https://stackoverflow.com/questions/46486261/include-custom-fonts-in-aws-lambda?

**Comment by imauryarahul** [comment]
@swngarg1308 Were you able to fix this issue. We have been facing a similar issue where we are not able to print Hindi text. It shows square boxes in place of Hindi text. If you were able to fix this, please reply. It will be a great help. Thank you.

**Comment by ghost** [comment]
@PoetWhoCode we were able to solve this issue. I've updated the solution [here](https://github.com/alixaxel/chrome-aws-lambda/issues/94#issuecomment-640012550). Let me know if it works for you.

**Comment by singhsterabhi** [comment]
I had the same issue when I was trying to print pdf using a headless chromium puppeteer function. This solution worked for me. [link](https://support.google.com/chrome/thread/5705492?hl=en&msgid=5711880)
