### ISSUE TITLE
Chromium API connection prevents from loading

### ISSUE THREAD

**Issue by Ganitzsh** [puppeteer/puppeteer#5313]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: MacOS, Alpine Linux
* URLs (if applicable): https://www.tiktok.com/@patroxofficial or any other tik tok profile
* Node.js version: 10.16.3

**What steps will reproduce the problem?**

Simply use `page.goto`. No matter it's headless or not

_Please include code that reproduces the issue._

```javascript
const puppeteer = require('puppeteer');

async function test() {
    const browser = await puppeteer.launch({
      headless: false,
      defaultViewport: {
        height: 1024,
        width: 1280
      }
    });

    const ctx = await browser.createIncognitoBrowserContext();

    const page = await ctx.newPage();

    await page.goto('https://www.tiktok.com/@9gag', {
      timeout: 30000,
      waitUntil: 'networkidle0'
    })

    await new Promise(resolve => setTimeout(resolve, 5000));
    await browser.close();
}

test();
```

**What is the expected result?**

![the full page with video feed](https://i.ibb.co/KKDnq3n/Screenshot-2020-01-15-at-15-43-15.png)

**What happens instead?**

![video feed not loading](https://i.ibb.co/sJTnfNx/Screenshot-2020-01-15-at-15-42-42.png)

I've been trying many things, also nothing shows up in the console or the network that could give any clue about what the problem is. The issue also occurs when running in a docker container.

I tried loading the page using the chromium binary provided with puppeteer but it's loading fine, as well as on any other browser connected to the same and any other network. Incognito or not.

So, the only thing that is left to suspect is the fact that the connection between Puppeteer and the binary is somehow causing the problem? Would it be possible? I'm not familiar with how it works in the background and looking at the code has not been a successful lead for me, and I'm really running out of ideas.

**Comment by RobertGrubb** [comment]
@Ganitzsh Hey there, I actually had this same problem today, and spent quite a few hours hashing it out. The way I was able to make it work (and I apologize if I shouldn't mention other packages here, or not) was to use `puppeteer-extra`, and make use of their stealth package.

**Comment by Ganitzsh** [comment]
Seems to do the trick! I was not aware of this package, thanks for the tip.
