### ISSUE TITLE
authenticate() not working on macOS

### ISSUE THREAD

**Issue by max-richter** [puppeteer/puppeteer#5315]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: macOS Catalina 10.15.2
* Node.js version: 12.14.0
```
    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
        args: ['--proxy-server=' + taskProxy]
    });
    const page = await browser.newPage();
    await page.authenticate({
        username: taskUser,
        password: taskPass
    });

    await page.goto(url);
```
**What is the expected result?**
Page will authenticate the proxy and the given URL will be loaded.

**What happens instead?**
Page won't authenticate and asks user to manually enter user/pass.

**Comment by kblok** [comment]
Authentication tests pass on my Mac. Which kind of authentication are you getting?

**Comment by max-richter** [comment]
Sorry for the late response, but my problem is that the proxy isn't authenticating at all. For example, on Windows, using authenticate() with the username and password arguments works as expected. The same project on macOS won't authenticate while given the correct user/pass.

I'm wondering if this could be a problem on my end, maybe some sort of port issue or proxy setting.

**Comment by gajus** [comment]
You can use https://github.com/gajus/puppeteer-proxy as an alternative to `--proxy-server`/ `page.authenticate`. With `puppeteer-proxy`, you just pass your `proxyUrl` in a format `http://username:password@proxy`.

**Comment by max-richter** [comment]
> You can use https://github.com/gajus/puppeteer-proxy as an alternative to `--proxy-server`/ `page.authenticate`. With `puppeteer-proxy`, you just pass your `proxyUrl` in a format `http://username:password@proxy`.

Wish I knew about this earlier, thanks!
