### ISSUE TITLE
On page context call puppeter function

### ISSUE THREAD

**Issue by ronniery** [puppeteer/puppeteer#5316]
Can i in page context call a function defined on puppeter? What i need is, load a page on puppeter and when an especific event occurs, some elements will be shown on the screen, so when this happen i need call puppeter function with that loaded elements.

There is a way to achieve that?

**Comment by kblok** [comment]
You can use [page.exposeFunction](https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#pageexposefunctionname-puppeteerfunction).
