### ISSUE TITLE
How to/feature request: Run Chrome as utility and browser

### ISSUE THREAD

**Issue by guest271314** [puppeteer/puppeteer#5317]
Preface

> For general technical questions or "how to" guidance, please search StackOverflow for questions tagged "puppeteer" or create a new post.

Am banned from SO for another 4 years. That is not going to happen any time soon.

Have previously asked the question at Chromium discuss, /r/chrome, and bugs.chromium

- [What is the canonical procedure to use --utility, --utility-cmd-prefix, --utility-startup-dialog, --enable-service-binary-launcher flags?](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/-mSK2JXyLuM)

- [What is the canonical procedure to use --utility, --utility-cmd-prefix, --utility-startup-dialog, --enable-service-binary-launcher flags?](https://www.reddit.com/r/chrome/comments/ej2p6r/what_is_the_canonical_procedure_to_use_utility/fei6cvx/?context=3)

- [Issue 1042473: How to use Chromium as utility and browser?](https://bugs.chromium.org/p/chromium/issues/detail?id=1042473)

Concept

- [SpeechSynthesis *to* a MediaStreamTrack or: How to execute arbitrary shell commands using inotify-tools and DevTools Snippets](https://gist.github.com/guest271314/59406ad47a622d19b26f8a8c1e1bdfd5)

Am trying to execute arbitrary shell scripts on the local machine without using a local server, Native Messaging, or `WebAssembly` to do so.

Execution of the local shell scripts and retrieval of the output as a file is not the issue.

Retaining the ability to use the browser even though launched as a utility is the issue.

Perhaps the developers here will be able to help. If not do not know where to ask the question next. 

If this issue is determined to be off-topic for this repository, kindly close the issue. 

> For issues, feature requests, or setup troubles with Puppeteer, file an issue right here!
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: N/A
* Platform / OS version: Linux
* URLs (if applicable): file:, and Web address
* Node.js version: 8.10.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

notify_directory_modifications.sh

```
#!/bin/bash
requestLocalScripts() {
  while true; do
    inotifywait -e attrib -e close $HOME/localscripts/run.txt | while read a c; 
      do 
        $HOME/localscripts/script.sh
        echo "$$ $a $c"
      done
  done
}

requestLocalScripts
```
script.sh

```
#!/bin/bash
/usr/bin/espeak-ng -m -f $HOME/localscripts/input.txt -w $HOME/localscripts/output.wav
```

run.txt

A  plain text file having `0` size. We write the file to local file system without content to observe `ATTRIB` event (modification date) dispatched by `inotifywait`.

HTML

```
<!DOCTYPE html>
<html>

<head>
<meta charset="utf-8"/>
  <title>Choose directory, get writable permission, write without executing close()</title>
</head>

<body>
  <p id="choose_directory_get_writable_permission">Choose directory, get writeable permission, execute script</p>
  <script>
    let input = `<voice name="Storm">Test</voice>`, dir, status, execFileHandle, inputFileHandle, outputFileHandle, writer;
    const ac = new AudioContext();

    document.getElementById("choose_directory_get_writable_permission").onclick = async e => {
      try {
        if (!(dir instanceof FileSystemDirectoryHandle && dir.name === "localscripts") && status !== "granted") {
          dir = await self.chooseFileSystemEntries({type:"openDirectory"});
          status = await dir.requestPermission({writable:true});
        }
        inputFileHandle = await dir.getFile("input.txt", {create:true});
        execFileHandle = await dir.getFile("run.txt", {create: true});   
        writer = await inputFileHandle.createWriter({keepExistingData: false});
        await writer.write(0, new Blob([input], {
          type: "text/plain"
        }));
        await writer.close();
        writer = await execFileHandle.createWriter({keepExistingData: false});
        await writer.write(0, new Blob([], {
          type: "text/plain"
        }));
        // wait 25 for file to be written
        await Promise.all([writer.close(), new Promise(resolve => setTimeout(resolve, 25))]);
        outputFileHandle = await dir.getFile("output.wav", {create: false});
        const buffer = await (await outputFileHandle.getFile()).arrayBuffer();
        await Promise.all(["input.txt", "output.wav"].map(fn => dir.removeEntry(fn)));
        const ab = await ac.decodeAudioData(buffer);
        const source = ac.createBufferSource();
        source.buffer = ab;
        source.onended = e => {
          source.disconnect();
          console.log(e);
        }
        source.connect(ac.destination);
        source.start();
      } catch (e) {
          console.error(e);
      }
    }
  </script>
</body>

</html>
```
1. Launch Chromium 81 with `--utility`, `--utility-and-browser` flags set
 `chromium-browser --utility-and-browser --utility-cmd-prefix="/path/to/notify_directory_modifications.sh" "/path/to/choose_directory_get_writable_permission_without_executing_close.html"`
2. Write arbitrary sheel script to local filesystem using Native File System.
3. Utilize `inotify-tools` to execute the arbitrary shell script and get output of command as file.

**What is the expected result?**

Ability to navigate to a Web address at a tab other than the local HTML doccument at `file:` protocol set as argument to Chromium executable.

**What happens instead?**

When attempting to naviagte to a Web URL at the new tab page the document does not load, instead the tab appears to remain in the request state, similar to requesting a _N_ GB resource, though does not ever conclude the request.

--

How to run Chromium, Chrome as both a utility and general browser?

**Comment by DeerSpotter** [comment]
Why was this closed

**Comment by guest271314** [comment]
No answers forthcoming.

The closest to what I describe is Native Messaging and https://github.com/guest271314/requestNativeScripts.

Technically, it is possible to run arbitrary, dynamic scripts and programs using Native Messaging and File System Access API.
