### ISSUE TITLE
exposeFunction doesn't work correctly with 3rd party function

### ISSUE THREAD

**Issue by linbudu599** [puppeteer/puppeteer#5320]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: windows10 1903
* URLs (if applicable): https://ts.xcatliu.com/
* Node.js version: 12.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. exposeFunction dosen't work correctly when calling a 3rd party method from modules, which cause unexpected error.
2. I had already searched in StackOverflow and Google, and disappointedly in vain.

```javascript
const removeSpItems = require("../helper/removeSpItems");
await page.exposeFunction("removeSpItems", (arr, idxArr) =>
    removeSpItems(arr, idxArr)
  );
let aLinkArr = await page.evaluate(async () => {
    const linkUl = document.querySelectorAll("ul.list-20526648")[4];
    let aLinks = [
      ...linkUl.querySelectorAll(
        "a.link-a079aa82--primary-53a25e66--link-faf6c434"
      )
    ];
    await window.removeSpItems(aLinks, [0, 1, 5, 16, 26]);
    return aLinks.map(a => {
      return {
        href: a.href.trim(),
        text: a.innerText.trim()
      };
    });
  });

// removeSpItems.js
function removeSpItems(arr, idxArr = []) {
  const len = idxArr.length;

  if (!Array.isArray(idxArr) || len === 0) {
    throw new Error("IdxArr Must Be An Array With At Least One Member!");
  }
  if (len === 1) {
    arr.splice(idxArr[0], 1);
    return arr;
  } else {
    let newIdx = idxArr.map((val, idx) => {
      return val - idx;
    });

    newIdx.forEach(idx => {
      arr.splice(idx, 1);
    });
    return arr;
  }
}
module.exports = removeSpItems;

```

**What is the expected result?**
`aLinks` is an array with several node like `<a><span>...</span></a>` , I try to use `removeSpItems` to remove special items in the array. 

**What happens instead?**
Unexpected Error Occured:

UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLAnchorElement'
    |     property '__reactInternalInstance$li019jk8fmm' -> object with constructor 'tu'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at window.<computed> (__puppeteer_evaluation_script__:13:22)
    at __puppeteer_evaluation_script__:11:18
    at ExecutionContext._evaluateInternal (C:\Users\归去来兮\Desktop\Praticing\Puppeteer-Pratices\node_modules\_puppeteer@2.0.0@puppeteer\lib\ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\归去来兮\Desktop\Praticing\Puppeteer-Pratices\node_modules\_puppeteer@2.0.0@puppeteer\lib\ExecutionContext.js:48:12) 
    at async C:\Users\归去来兮\Desktop\Praticing\Puppeteer-Pratices\src\ts-pdf.js:125:18
0@puppeteer\lib\helper.js:112:23)                     ing\Puppeteer-Pratices\node_
    at C:\Users\归去来兮\Desktop\Praticing\Puppeteer-P)                           -Pratices\node_modules\_puppeteer@2.0.0@puppeteer\lib\helper.js:111:15)ratices\src\ts-pdf.js:125:29                          ticing\Puppeteer-Pratices\noode_modules\_puppeteer@2.0.0@puppeteer\lib\DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/tas12:23)k_queues.js:93:5)

**Comment by kblok** [comment]
Chrome/Puppeteer will serialize data sent to and returned by your exposed function.
So you won't be able to pass an array of DOM elements.
