### ISSUE TITLE
Issue launching chromium on raspberry pi

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#5322]
I tried to launch the browser on my pi and got this error:

(node:1317) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/pi/project/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome: 1: /home/pi/project/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome: Syntax error: ")" unexpected

**Comment by kblok** [comment]
You should download a chromium version that works on your raspberry pi, and pass the path to that browser to the `launch` function.
