### ISSUE TITLE
End case when puppeteer  sometimes load certain element, and sometimes don't

### ISSUE THREAD

**Issue by suntong** [puppeteer/puppeteer#5324]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@2.0.0
* Platform / OS version: Ubuntu 18.04.2 LTS
* Node.js version: v12.9.1

**What steps will reproduce the problem?**

If you try the following simple example, you will find it is working without a problem:

```js
    const puppeteer = require('puppeteer');
    
    (async() => {
    
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      //await page.setViewport({width:800, height:800});
    
      const response = await page.goto(`https://finance.yahoo.com/chart/TSLA`, {waitUntil: 'networkidle2'});
    
      let selector = `div#chart-toolbar ul > li`
      page.waitForSelector(selector)
      selector = `div#chart-toolbar ul > li:nth-child( 7 ) > button` // > span > span
      page.click(selector)
    
      const inputElement = await page.$('div#fin-chartiq')
      await inputElement.screenshot({path: 'yahoo-finance.png'})
      await browser.close();
    
    })();
```

However, if you take off the comment and expose the `await page.setViewport`, you will find that it will error out with:

`UnhandledPromiseRejectionWarning: Error: No node found for selector: div#chart-toolbar ul > li:nth-child( 7 ) > button`

Why such huge different? 

**What is the expected result?**

The behavior is the same, with or without `page.setViewport`.

**What happens instead?**

The behavior is different.

**Comment by suntong** [comment]
As per [mbit](https://stackoverflow.com/users/11622802/mbit),

> if the click has an issue it's because puppeteer's click requires the element to be in the viewport. Try the HTML click instead of emulated click and it should work regardless of viewport setting.
there are many ways to do that, I'd usually do something like this:

```js
let element = await page.$(selector);
if (element)
await page.evaluate(el => el.click(), element);
```

**Comment by suntong** [comment]
The HTML click won't error out, but it didn't do anything either for me -- In the generated screenshot, the time should start with Feb last year, when `li:nth-child( 7 ) > button` would have been clicked. But mine start with Oct last year, the *same* without the `li:nth-child( 7 )` button being clicked.

I've confirmed that it is not the problem of whether the element is in the viewport or not. The problem is that, with or without page.setViewport, the returned page is different. I tried saving `page.content()` and did a comparison, and found the differences.

Note that such problem only exhibit in Ubuntu, not Mac, as mbit [is using](https://chat.stackoverflow.com/transcript/message/48381226#48381226) Mac and _"tested with both Nodejs 12.12.0 and v9.11.2"_ and both are fine. 

Will all above, I think it is a end cased that has fallen through the crack.

**Comment by phawxby** [comment]
@suntong try with `headless: false` and see if that makes it more consistent. I'm having similar issues and I think headless is a factor.
https://github.com/puppeteer/puppeteer#default-runtime-settings

**Comment by suntong** [comment]
Oh yes @phawxby, I forgot to mention that with `headless: false`, the problem would go away. 

So, yes indeed, headless is a factor.

**Comment by suntong** [comment]
ping. 

problem still exist

**Comment by OrKoN** [comment]
Hm, I believe you need `await` before `waitForSelector` and `click`. Also, a different viewport might have a different DOM (determined by the website) so you need to make sure the selector is valid. I don't think there is a bug here but feel free re-open the issue with a more recent repro (the currently mentioned selectors don't seem to exist on the page anymore).
