### ISSUE TITLE
Numbers being rearranged when using type

### ISSUE THREAD

**Issue by twigs67** [puppeteer/puppeteer#5326]
Hello all,

No idea if this is a bug with puppeteer or something else, but I wanted to report it and see if anyone else has experienced this issue. 

I have a form autofiller that I have created and on some websites numbers are typed in the incorrect order. For instance, if the number to be inputted in the input field is "123456", it will be typed "132476".

This doesn't happen all of the time (20%). I have it to auto-retry if it doesn't work, so it eventually does input it correctly after 10 tries. It only happens with numbers.

Has anyone experienced this?

* Puppeteer version: 2.0.0
* Platform / OS version: Ubuntu 18
* Node.js version: 10.17.0

**Comment by kblok** [comment]
Did you try passing some delay in the options?

**Comment by twigs67** [comment]
@kblok I have tried using delays before typing the whole thing, e.g.,

1. waitFor - 1000ms
2. type - 123456

I also tried typing them one at a time, e.g.,
1. type - 1
2. type - 2
etc...

When I type it one at a time, it happens less often, but still happens. One thing I noticed is that this only happens on specific websites, which makes me think they have some JS that's doing this and it's not puppeteer. 

But I will try adding a delay between each number as I type them and see how that works.

Thanks

**Comment by kblok** [comment]
You also have delay on the type function

```js
await page.type('12345', { delay: 500});
```

**Comment by twigs67** [comment]
Did not know about this. I will give it a try and report back. Thanks again

**Comment by twigs67** [comment]
@kblok Unfortunately, this did not work.

**Comment by RyanBaileySC** [comment]
@twigs67 Were you able to find a solution to this? 

I'm having the same issue (js on page for correct phone number formatting), and the only thing that I've found that works is running it in 'headless: false' mode with 'slowmo: 10.' It takes forever compared to headless with slowmo off, but I can't figure out a better way.

**Comment by twigs67** [comment]
@RyanBaileySC moved away from puppeteer. It wasn't the right use-case which is why we had so many issues with it.
