### ISSUE TITLE
Value of clip.scale is always reset to 1 for page.screenshot

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#5329]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0
* Platform / OS version: MacOS 10.14
* URLs (if applicable): 
* Node.js version: 12.1.0

**What steps will reproduce the problem?**
Using the `clip` option for `page.screenshot` with a scale of non `1` like:

_Please include code that reproduces the issue._
```
  await page.screenshot({path: 'screenshot.png', clip: { x: 100, y: 100, width: 400, height: 400, scale: 2 }});
```

**What is the expected result?**
Scaling factor gets correctly forwarded to Chrome.

**What happens instead?**
Value is reset to `1` here: https://github.com/puppeteer/puppeteer/blob/eddb23b52175a3dad8cec4a5e9b3c13e58f6f144/lib/Page.js#L968

**Comment by kawie** [comment]
Same issue! Would love if this was possible.

I think this also breaks the suggested workaround in #4419, as soon as you want to take a screenshot

**Comment by whimboo** [comment]
This is still not working with latest Puppeteer:

```
  puppeteer:protocol:SEND ►   '{"sessionId":"89053ED5BCD73984AC73A4E423112F08","method":"Page.captureScreenshot","params":{"format":"png","clip":{"x":100,"y":100,"width":400,"height":400,"scale":1},"captureBeyondViewport":true},"id":18}'
```

@OrKoN maybe it's not too hard to fix?

**Comment by OrKoN** [comment]
Let me take a look at this later.
