### ISSUE TITLE
"Browser.close" hangs & never succeeds if CDP WebSocket connection is lost

### ISSUE THREAD

**Issue by kingIZZZY** [puppeteer/puppeteer#5331]
* Puppeteer version: 2.0.0
* Platform / OS version: Ubuntu 18.04.3 LTS
* Node.js version: v12.14.1

**What steps will reproduce the problem?**

```
const browser = await puppeteer.connect({
    browserWSEndpoint: "...",
    defaultViewport: null
});

//// Kill Chrome, "cut the wires" or otherwise cause
//// "brute force" disconnect to the CDP websocket

var pages = await browser.pages();
...
```

1. Start puppeteer, in my case I am `connect`ing to an existing CDP websocket to an already running Chrome started with `--remote-debugging-port=0`
2. Sometime after successfully connecting and getting a `Browser`, kill/crash Chrome or cause the WebSocket connection to be lost. (In my case Ctrl+C in command line where Chrome was started)
3. Try cleaning up & closing puppeteer  `await browser.close()`

**Expected result**
Puppeteer should deal with situations where the websockets are suddenly gone, `Browser` should clean up any of its internals/resources, shut itself down, resolve the promise and continue execution.

**What happens instead**
`await browser.close();` **hangs** and never resolves, since the expected CDP responses from the browser (`Target.detachedFromTarget`, `Target.targetDestroyed`, CDP response to `Browser.close` etc.) are never coming because the debugging WebSocket is disconnected.
The call to `"Browser.close"` goes forever unresolved...

### 1. Normal Shutdown - WebSockets are operational till the end
```
BROWSER: {"method":"Inspector.detached","params":{"reason":"Render process gone."},"sessionId":"41ADCCDF5AC1052073D6FB08045F5EC5"}
BROWSER: {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"7AABA6DF71288AB76AB428D02C88966C","type":"other","title":"TITLE REDACTED","url":"https://URL-REDACTED","attached":false,"browserContextId":"E5E5104C7CB4FBD13BEC2FAF98B13F3E"}}}
BROWSER: {"method":"Target.detachedFromTarget","params":{"sessionId":"41ADCCDF5AC1052073D6FB08045F5EC5","targetId":"7AABA6DF71288AB76AB428D02C88966C"}}

// I handle exceptions/events indicating that the browser manually closed
// and issue the await browser.close() command

PUPPETEER: {"method":"Browser.close","params":{},"id":19}
// CDP responses!
BROWSER: {"method":"Target.targetDestroyed","params":{"targetId":"7AABA6DF71288AB76AB428D02C88966C"}}
BROWSER: {"id":19,"result":{}}
// `await browser.close()` resolves successfully and execution continues
```

### 2. Bad Shutdown - WebSockets are lost
```
BROWSER: {"method":"Inspector.detached","params":{"reason":"Render process gone."},"sessionId":"2859C3328B7390D66A3FEFA32F1C15D1"}
BROWSER: {"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"835D09DBD8D7365D79802A5B43ECEE70","type":"other","title":"TITLE REDACTED","url":"https://URL-REDACTED","attached":false,"browserContextId":"C9224BA452CFF993C4528F6FEBCE12D5"}}}
BROWSER: {"method":"Target.detachedFromTarget","params":{"sessionId":"2859C3328B7390D66A3FEFA32F1C15D1","targetId":"835D09DBD8D7365D79802A5B43ECEE70"}}

// I try closing browser

PUPPETEER: {"method":"Browser.close","params":{},"id":19}
// No CDP responses :(
```
The CDP response is never coming...

**Comment by kingIZZZY** [comment]
## Workaround

If you can intercept & send messages into the CDP debugging WebSocket connection, if you detect a "Browser.close" command and you can tell that the WebSocket is lost/closed/disconnected, simulate an appropriate response back to puppeteer through the WebSocket;
```
Puppeteer sends: {"method":"Browser.close","params":{},"id":19}
Browser CDP responds: nothing - dead connection
Then manually send puppeteer via the CDP WebSocket: {"id":19,"result":{},"btw":"this is spoofed!"}
```

**Comment by Kikobeats** [comment]
This is still a thing. In general, when the WebSockets connection is lost puppeteer can't handle the state accordingly  

my workaround was to attach a timeout related to `browser.newPage`

https://github.com/microlinkhq/browserless/pull/235

**Comment by Kikobeats** [comment]
forgot my comment; the thing you need to check is the browser connection is properly established _before_ open a new page

https://github.com/microlinkhq/browserless/commit/caf87acbd9f5192442e361979d63148663fb32c7#diff-0ab3a2b505d4a27b0bff809bb4d53dafa2d1329bb817d298096f044efefc8bdaR53
