### ISSUE TITLE
Missing some cookies when page is loaded with headless

### ISSUE THREAD

**Issue by AvManikanta** [puppeteer/puppeteer#5332]
HeadlessChrome/79.0.3945.0

While using headless:false I'm receiving all the cookies present in the given URL but if the headless is used then few cookies are missed in the result.

const browser = await puppeteer.launch({
        waitUntil: "networkidle2",
        timeout: 60000,
	//headless:false,
	ignoreHTTPSErrors: true,
        args: ['--no-sandbox',
		'--disable-setupid-sandbox',
		'--ignore-certificate-errors'
		],
        });

const page = await browser.newPage();
const res = await page.goto("https://"+domain, {
                  waitUntil: "networkidle2",
                  timeout: 30000
            })	
const cookies = await page.cookies();

Example: For a domain www.example.com there are 5 cookies.
If i didn't use headless, I was able to receive all the 5 cookies but if I use it as headless only few cookies are received

Will there be any difference while loading the pages with or without headless?

Help me out to fix this issue

**Comment by alete89** [comment]
If you got here in the future, try using
```js
puppeteer.launch({
    headless: "new", // "new" instead of true
  });
  ```

it worked for me
