### ISSUE TITLE
code stop executing halfway sometime

### ISSUE THREAD

**Issue by mrhaha80** [puppeteer/puppeteer#5335]
Dear Expert,

I need your help & advice.
I am newbie and i facing some issues when my code below.
The issue is that, the code stop executing halfway some time,
sometime it stop at **_await page.type('#Password', 'xxx')_**
sometime it stop at _**await page.evaluate((text) => { (document.getElementById('txt_UserName')).value = text; }, "0138622000");**_

sometime it can execute all code.

May i know why?

`const puppeteer = require('puppeteer');
(async () => {
 	const browser = await puppeteer.launch({headless:false});
 	const page = await browser.newPage();
  	await page.goto('http://sample/', { waitUntil: "networkidle0" });
  	await page.waitFor("#close1");  	
	await page.click("#close1");

  	await page.type('#UserName', 'STN_S28')
  	**_await page.type('#Password', 'xxx')_**
  	await page.click('#loginButton')
 	await page.waitForSelector("#txt_UserName")  	

	_**await page.evaluate((text) => { (document.getElementById('txt_UserName')).value = text; }, "0138622000");**_

  	await page.click("#Button_OK")

  	await page.screenshot({path: 'example.png'})

  	await browser.close();
})();`

Many thanks 
Ant

**Comment by mrhaha80** [comment]
Hi there,

can someone help me, please?

thanks

**Comment by RobertGrubb** [comment]
Is the website you are loading written in anything like React where the DOM elements are loaded dynamically? If so, is it possible that they are not making it into the DOM before your script executes? I would attempt to wrap the problematic blocks of code in a try catch and output what the error is that the promise is returning.

**Comment by mrhaha80** [comment]
> Is the website you are loading written in anything like React where the DOM elements are loaded dynamically? If so, is it possible that they are not making it into the DOM before your script executes? I would attempt to wrap the problematic blocks of code in a try catch and output what the error is that the promise is returning.

Hi RobertGrubb,
Many thanks for your reply.
I am using Laravel 6. Node JS is a plugins. I ran it via command prompt with c:\laragon\www\myproject\public\node\>node example.js
Much appreciated if you could show me a sample on how to write a try catch with my code above? Because I am new to puppeteer.

Thank you
Ant

**Comment by RobertGrubb** [comment]
I'll be honest, I haven't messed with php whilst making use of puppeteer. 

Have an example in the code of how Laravel runs the command? Are you using a normal `exec` or `shell_exec` to accomplish it? Or does Laravel have a method baked in to do that?

If you can get me an example, maybe we can find a way to log what the console returns, or an alternative is to have the output from `example.js` log to a file in general.

**Comment by mrhaha80** [comment]
Hi RobertGrubb,
is it possible to provide me your email? i will send you the example.js.

Thanks

**Comment by RobertGrubb** [comment]
No problem, feel free to send it to `matt@grubb.com`

**Comment by mrhaha80** [comment]
> No problem, feel free to send it to `matt@grubb.com`

Hi RobertGrubb

I have sent you the code via email couple days ago from `mrhaha80@gmail.com`. 

Many thanks for your help.

Ant
