### ISSUE TITLE
"headless should be able to read cookies written by headful" would fail upgrading to 725038

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#5336]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0
* Platform / OS version: Windows
* URLs (if applicable): None
* Node.js version: 

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Change the chromium revision to 725038
2. Run HEADFUL tests

**What is the expected result?**
It should be green.

**What happens instead?**
"headless should be able to read cookies written by headful" fails.

**Comment by kblok** [comment]
@mathiasbynens would you mind taking a look at this. I'm trying to run these tests on MS Edge and this one is the only one failing. Revision 725038 is the closest to MS Edge DEV revision I found.

**Comment by mathiasbynens** [comment]
Thanks for filing!

We should do a Chromium bisect with `good=706915` & `bad=725038` to figure out what broke this upstream. (The only complication is that this requires a Windows machine, since the issue only seems to affect Windows.)
