### ISSUE TITLE
Handling ALL chrome://settings with Puppeteer

### ISSUE THREAD

**Issue by ponzilover** [puppeteer/puppeteer#5339]
Since page.goto(chrome://settings) doesn't work (navigate method requires a scheme), how can we modify chrome://settings?Specifically, I want to allow sites to play protected content via chrome://settings/content/protectedContent
Short answer: we can use [flags](https://peter.sh/experiments/chromium-command-line-switches/)
Long answer: not all chrome://settings are handled by flags; hence, certain settings must be modified manually BUT puppeteer doesn't allow manual browsing to chrome://settings
I've already tried asking on [SO](https://stackoverflow.com/questions/59882213/how-to-modify-chrome-settings-via-puppeteer ) but it looks like it's impossible to handle all chrome://settings through Puppeteer..if it's true and I'm not wrong,please take this as a feature request.

**Comment by baj9032** [comment]
same feature I need as well

**Comment by bleszerd** [comment]
Same, I need to navigate to `chrome://newtab`, but I haven't found a way to use` headless: false` together

**Comment by MarcelleBond** [comment]
Did anyone manage to get this right?
