### ISSUE TITLE
Run multiple browsers in parallel (puppeteer-firefox)

### ISSUE THREAD

**Issue by nmoinard** [puppeteer/puppeteer#5340]
Hi guys, 

Just testing out puppeteer-firefox and I was not able to run multiple browsers at the same time. 

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-firefox
* Platform / OS version: Mac OS Mojave v10.14
* URLs (if applicable): none
* Node.js version: v10.16.3

When triggering two browsers at the same time, it should work (like on chromium) and run requests in parallel but instead, I get this error: 

"Close Firefox
A copy of Firefox is already open. Only one copy of Firefox can be open at a time."

I checked on stackoverflow but I can't really access firefox settings I guess it is handled by puppeteer. 

Do you have any ideas on how to fix this?

Thanks,

**Comment by mjzffr** [comment]
This looks like`--no-remote` Firefox argument is missing. You might be able to circumvent this by passing it in `args` in the Puppeteer launch options.
