### ISSUE TITLE
Is it possible to send data from browser to puppeteer - get function like in php ?

### ISSUE THREAD

**Issue by gandolfi974** [puppeteer/puppeteer#5342]
Hello,

i use Puppeteer for scrap.

I managed to transform a page written in javascript into an html page. I was then able to display this html page on my web server with the "createServer" function.
The problem is that the link to the javascipt page is written directly in the puppeteer script.

I would like puppeteer to be able to have a GET function, as in PHP, so that it can retrieve the http link that I send through the browser and then send me the page transformed into html.

For example:
http://myserver.com?link=http://link-to-transform-in-html

In puppeteer:

await page.goto ("http: // link-to-transform-in-html", {waitUntil: "networkidle2"});

is it possible?

thanks

**Comment by nicoandmee** [comment]
I am having trouble understanding your question, but if you want to make a GET/POST request within the browser context/puppeteer you can simply use `fetch()`. See: [https://blogs.missouristate.edu/cio/2016/01/14/fetching-data-over-http-with-nodejs-using-node-fetch/](Guide)

**Comment by gandolfi974** [comment]
hi, thanks for your answer. sorry for my english,  i'm french.
 I want to scrap the webpage whose "url" I send to my server. I can do this with SPLASPH
( http://<splash-server>:8050/render.html?url="http://websitetoscrap.com")

https://splash.readthedocs.io/en/stable/faq.html#render-html-doesnt-work

thanks

**Comment by jackfranklin** [comment]
Hello, 

I think StackOverflow will be a better source for questions like these; we try to use GitHub issues for feature requests and bug reports. Thanks!
