### ISSUE TITLE
space bottom of the page

### ISSUE THREAD

**Issue by senocak** [puppeteer/puppeteer#5343]
I am using puppeteer 2.0. I am making multiple pdfs and I want to add footer section in pdf by using footerTemplate. I stil see some space bottom of the page

`await page.pdf(
	{
		path: pdfFileName,
		format: 'A4',
		displayHeaderFooter: true,
		fitWindow: true,
		footerTemplate: '<div style="width:100%; margin-top:100px; text-align:center; font-size:10px; border-bottom: 20px solid #4e82c9;">Footer is here</div>',
		margin: {
			top: '0',
			bottom: '100px',
			right: '0',
			left: '0',
		},
	}
);`
https://i.stack.imgur.com/rr4j5.png
https://stackoverflow.com/questions/59918637/puppeteer-footer-does-not-at-the-bottom-of-the-page

**Comment by Lonniebiz** [comment]
@senocak Is that space coming from your CSS: `border-bottom: 20px solid #4e82c9;`?

**Comment by Lonniebiz** [comment]
Perhaps that space at the bottom is coming from `bottom: '100px'`?

**Comment by senocak** [comment]
> Perhaps that space at the bottom is coming from your CSS: `bottom: '100px'`?

I did change the margin of the bottom to zero, When i did that it just does not seen in the pdf.  

https://i.stack.imgur.com/jPLnj.png this image is happens when bottom is zero.

**Comment by Lonniebiz** [comment]
@senocak What happens when you omit the margin property altogether? It is supposed to default to "none".

If you set the bottom margin to 25px, does it decrease the amount of space you're seeing at the bottom at all (versus 100px)?

In CSS, zero doesn't require a unit to follow it. This isn't CSS though. The [documentation](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pagepdfoptions) doesn't explicitly say that the unit can be omitted if it is zero. So, I'd test `0px` if `0` alone is having no effect.

**Comment by senocak** [comment]
> @senocak What happens when you omit the margin property altogether? It is supposed to default to "none".
> 
> If you set the bottom margin to 25px, does it decrease the amount of space you're seeing at the bottom at all (versus 100px)?
> 
> In CSS, zero doesn't require a unit to follow it. This isn't CSS though. The [documentation](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pagepdfoptions) doesn't explicitly say that the unit can be omitted if it is zero. So, I'd test `0px` if `0` alone is having no effect.

When i remove margin property or set all to zero, I am not be able to see anything in footer but when i do search footer text in pdf page, I see that it is in pdf but not visible. This is happening : https://i.stack.imgur.com/jPLnj.png

And I did change the margin bottom almost every possible way I can think of like "no margin, bottom: 50, bottom:150 etc...", Nothings changed.

**Comment by Lonniebiz** [comment]
Your original post shows that you are setting a property called `footerTemplate2`. Shouldn't that be [`footerTemplate`](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pagepdfoptions)?

**Comment by senocak** [comment]
> Your original post shows that you are setting a property called `footerTemplate2`. Shouldn't that be [`footerTemplate`](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pagepdfoptions)?

Yep. I forgot the old guy there.  The original code is below;
> {
                    path: pdfFileName,
                    format: 'A4',
                    margin: {
                        bottom: '100px',
                    },
                    displayHeaderFooter: true,
                    /*footerTemplate2: "Something new here",*/
                    footerTemplate: `<div style="width:100%; margin-top:100px; text-align:center; font-size:10px; border-bottom: 20px solid #4e82c9;">Footer is here</div>`,
                    fullPage: true
                }

When i created this issue I just removed the wrong line. So problem still exists

**Comment by senocak** [comment]
Anyone here?
