### ISSUE TITLE
How to print pages/ page numbers/pagination in pdf puppeteer?

### ISSUE THREAD

**Issue by odykyi** [puppeteer/puppeteer#5345]

**Comment by odykyi** [comment]
Hey!

use attribute **footerTemplate** with **displayHeaderFooter** for show pages originally using puppeteer API


```
await page.pdf({
  path: 'hacks.pdf',
  format: 'A4',
  displayHeaderFooter: true,
  footerTemplate: '<div><div class='pageNumber'></div> <div>/</div><div class='totalPages'></div></div>'
});
```

https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagepdfoptions

>  > **footerTemplate** <string> HTML template for the print footer.


// Should be valid HTML markup with following **CSS classes** used to inject printing values into them:
//  - **date** formatted print date
//  - **title** document title
//  - **url** document location
//  - **pageNumber** current page number
//  - **totalPages** total pages in the document

**Comment by guilhemferr** [comment]
I was able to reproduce this issue. It turns out that the css variables are replaced correctly but the generated text was too small to be visible. For instance, if you try to increase the font size in your template as follows you should see the replaced text.
```
footerTemplate: "<div style='font-size: 16px'>...</div>"
```
As my requirement was to display the page numbering at the bottom right I've struggled a bit with the css. I've tried to use other way than inlined css but it didn't work. So I end up with this solution. Hope it helps.
```
await page.pdf({
  path: 'hacks.pdf',
  format: 'A4',
  displayHeaderFooter: true,
  headerTemplate: "<div/>",
  footerTemplate: "<div style=\"text-align: right;width: 297mm;font-size: 8px;\"><span style=\"margin-right: 1cm\"><span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></span></div>"
});
```

**Comment by AlexWayfer** [comment]
I guess, this issue should be closed?

**Comment by andreapernici** [comment]
I'm also trying to use it, but I can't see any page number
```

    const pdf = await page.pdf({
      path: 'test.pdf',
      format: 'A4',
      displayHeaderFooter: true,
      headerTemplate: "<div><div class='pageNumber'></div> <div>/</div><div class='totalPages'></div></div>",
      footerTemplate: "<div style=\"text-align: right;width: 297mm;font-size: 8px;\"><span style=\"margin-right: 1cm\"><span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></span></div>"

    });
```

The only thing I see is the word "of".

Which is the right syntax?

**Comment by PejmanNik** [comment]
As it was a pain, for now until the puppeteer let us customize the header/footer I create this. It uses puppeteer and let fully customize  header, footer, and pagination

https://github.com/PejmanNik/puppeteer-report#readme

**Comment by andreapernici** [comment]
I ended up using PagedJS https://www.pagedjs.org/documentation/ and then integrating Puppeter with it.

**Comment by mlarcher** [comment]
FWIW, in our case the issue was related to the margins passed in the option. You need to provide a bottom margin for the footer not to be covered by the page data, and if that margin is too small you may experience weird behavior, e.g. the `/` between `pageNumber` and `totalPages` being visible but not the values for those.

To be clear, we used the following syntax to make the footer work :
```js 
await page.pdf({
    format: 'A4',
    displayHeaderFooter: true,
    headerTemplate: ``,
    footerTemplate: `
    <div style="border-top: solid 1px #bbb; width: 100%; font-size: 9px;
        padding: 5px 5px 0; color: #bbb; position: relative;">
        <div style="position: absolute; left: 5px; top: 5px;"><span class="date"></span></div>
        <div style="position: absolute; right: 5px; top: 5px;"><span class="pageNumber"></span>/<span class="totalPages"></span></div>
    </div>
  `,
    // this is needed to prevent content from being placed over the footer
    margin: { bottom: '70px' },
  });
```

**Comment by wishfulthinkerme** [comment]
@mlarcher First answer that solved my issue completely. Thanks!

**Comment by KeithPoonNS** [comment]
this ticket is very useful, I tried Puppeteer and puppeteer-report
Puppeteer: (displayHeaderFooter, headerTemplate, footerTemplate)
go for if just need the simple header, footer

puppeteer-report:
go for if I need more customize on the header, footer

actually, both are pretty

**Comment by Bastardly** [comment]
I had a small placement issue, due to margins and lack of container height  - so I ended up with this solution:
(That still needs to cleaned up a bit.)

```
const footerHtml = `
<div style="width: 100%; font-size: 10px; margin: 0 1cm; color: #bbb; height: 30px; text-align: right;">
		<span class="pageNumber" style="font-size: 10px;"></span> / <span class="totalPages" style="font-size: 10px"></span>
</div>
`;
```

```
	const pdfBuffer = await page.pdf({
		format: 'a4',
		margin: {
			top: '3cm',
			bottom: '2cm',
			left: '1cm',
			right: '1cm',
		},
		headerTemplate: headerHtml,
		footerTemplate: footerHtml,
		displayHeaderFooter: true,
		scale: 1,
	});
```

**Comment by DEYROS** [comment]
Hello ! 
I am currently using [mdpdf ](https://www.npmjs.com/package/mdpdf). 
I wanted to add page numbers to my footer and I saw this : 
![image](https://user-images.githubusercontent.com/88462659/174995676-55155518-6e56-462a-ac93-42e78944300e.png)
So I tried this into a file called **index.js** :
```javascript
const path = require('path');
const mdpdf = require('mdpdf');

const options = {
	source: path.join("pdfFinal/", 'fichierConcatComp.md'), 
	destination: path.join("pdfFinal/", 'fichierConcatComp.pdf'), 
	styles: path.join("pdfFinal/", 'styles.css'), 
	ghStyle: false,
	defaultStyle: true,
	footer: path.join("pdfFinal/", 'footer.html'),
	header: path.join("pdfFinal/", 'header.html'),
	pdf: {
		format: 'A4', 
		orientation: 'portrait',
		quality: '100',
		header: {
			height: '25mm'
		},
		footer: {
			height: '17mm'
		},
		border: {
			top: '10mm',
			left: '20mm',
			bottom: '5mm',
			right: '20mm'
		},
	}
};

// Call convert which returns a thenable promise with the pdfPath
mdpdf.convert(options).then(pdfPath => {
	console.log('Fichier PDF créé :', pdfPath);
}).catch(err => {
    // Don't forget to handle errors
	console.error(err);
});
```

Here is the **footer.html**
```html
<footer>
    <div id="footer">
        <h1 class="txt">SpringCard</h1>
        <hr class="solid">
        <div class="nbPages">Page <span class="pageNumber"></span>/ <span class="totalPages "></span></div>
    </div>
</footer>
```

and the css for it : 
```css
.txt{
    font-family: Calibri;
    font-size:15px;
    text-align:center;
    margin-bottom:-5px;
    color: rgb(174, 121, 128); 
}

.footer{
    height:50px;
    display: flex;
    padding:15px;
}

.nbPages{
   font-family: Calibri;
   font-size:13px;
   color: rgb(174, 121, 128);
   text-align:right;
}

hr.solid {
  border-top: 1px solid rgb(174, 121, 128);
}
```
And my footer looked like this : 
![image](https://user-images.githubusercontent.com/88462659/174997521-5e5a56b0-7c90-4770-8650-3cf8c59a690d.png)
So it's great but as you can see I don't have the number of pages. I know I am doing something wrong but I don't know what. 
I would like to use puppeteer with the mdpdf library but I don't know how. Thanks in advance !

**Comment by ksenechal** [comment]
The issue is related to https://github.com/chromedp/chromedp/issues/922
Changing the browser lang to en-US solve the issue for me.

```
const browser = await puppeteer.launch({
      // lang en-US is important for puppeteer to render correctly pagination. See https://github.com/chromedp/chromedp/issues/922
      args: [...,'--lang=en-US']
 });
```

**Comment by nyousaf47** [comment]
Can we hide Footer on first page only?
Any one can help me to hide PDF Footer on first page only.
`let options = { 
      format: 'Letter',
      args: ['--no-sandbox'],
      displayHeaderFooter: true,
      preferCSSPageSize: true,
      printBackground: false,
      headerTemplate: css+html.header,
      footerTemplate: css+"<div style=\"text-align: center; font-family:'Georgia'; width: 100%; margin: 0 48px; margin-bottom:-8px; height: 15px; font-size: 12px;\" class=\"wcr-footer-container\"><span class=\"wcr-footer\">Pages <span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></span></div>"
  };`

**Comment by clakech** [comment]
> The issue is related to [chromedp/chromedp#922](https://github.com/chromedp/chromedp/issues/922) Changing the browser lang to en-US solve the issue for me.
> 
> ```
> const browser = await puppeteer.launch({
>       // lang en-US is important for puppeteer to render correctly pagination. See https://github.com/chromedp/chromedp/issues/922
>       args: [...,'--lang=en-US']
>  });
> ```

Thank you so much @ksenechal 
I do not understand at all why, even after reading the related issue on chromedp, but after adding lang config, now it works fine 🤯🥳

**Comment by outbackStack** [comment]
Ever since updating to version `22.2.0`, the page number no longer appears. Is anyone else experiencing this issue on a Debian server? It seems to be working fine on a Mac.

**Comment by David-Pena** [comment]
Is only happing to me that the pageNumber and totalPages render in white? I can't find a way to make it black. The only way for me to see it is by selecting it with my mouse :(

I've tried to rendere the footer people had posted here as examples like @mlarcher & @andreapernici

**Comment by dbssman** [comment]
> Can we hide Footer on first page only? Any one can help me to hide PDF Footer on first page only.
> 
> ```
> let options = { 
>       format: 'Letter',
>       args: ['--no-sandbox'],
>       displayHeaderFooter: true,
>       preferCSSPageSize: true,
>       printBackground: false,
>       headerTemplate: css+html.header,
>       footerTemplate: css+"<div style=\"text-align: center; font-family:'Georgia'; width: 100%; margin: 0 48px; margin-bottom:-8px; height: 15px; font-size: 12px;\" class=\"wcr-footer-container\"><span class=\"wcr-footer\">Pages <span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></span></div>"
>   };
> ```

Hey, did you manage to do this in the end?
