### ISSUE TITLE
Error installing puppeteer through web server

### ISSUE THREAD

**Issue by dvil88** [puppeteer/puppeteer#5346]
Well, this is a bit weird. I'm trying to install projects using a web interface based on nginx + php7.3-fpm. Using user and group www-data.
I've set home path to user www-data to `/var/www/npm` and modified some config in `/var/www/npm/.npmrc`:

```
prefix=~/.npm-global
shell="/bin/bash"
```
Here is the full config: [https://pastebin.com/yXpF9mYk](https://pastebin.com/yXpF9mYk)
Adding `puppeteer_skip_chromium_download=true` to .npmrc has no effect.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.20.0
* Platform / OS version: Ubuntu 16.04.6 LTS
* URLs (if applicable):
* Node.js version: v10.16.0

**What steps will reproduce the problem?**

Create file `testPup.php` in `/var/www/html` with following content:

```
<?php

$cmd = 'git clone https://gitlab.com/dvil88/puptest.git /tmp/pupTest 2>&1';
$out = $err = false;
exec($cmd, $out, $err);

if( $err != 0 ){
	print_r(implode("\n", $out));
	exit;
}


$cmd = 'cd /tmp/pupTest && npm install 2>&1';
$out = $err = false;
exec($cmd, $out, $err);

if( $err != 0 ){
	print_r(implode("\n", $out));
	exit;
}
echo 'Finished!'.PHP_EOL;
```

**What is the expected result?**

As we can see here I'm cloning this repository [https://gitlab.com/dvil88/puptest.git](https://gitlab.com/dvil88/puptest.git) in `/tmp/pupTest` and then run `npm install` to install dependencies. The repository is only a test to install puppeteer ^1.17.0 (I'm getting same result with ^2.0.0).

If I run php script through command line using my user or ww-data it works perfectly:

```
www-data@dvil-ubuntu:/var/www/html$ php testPup.php 
Finished!
```

**What happens instead?**

If I run it though web server (http://localhost/testPup.php) I get this result:

```
npm WARN lifecycle npm is using /usr/local/n/versions/node/10.16.0/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> puppeteer@1.20.0 install /tmp/pupTest/node_modules/puppeteer
> node install.js

npm WARN puptest@1.0.0 No description
npm WARN puptest@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn sh
npm ERR! file sh
npm ERR! path sh
npm ERR! errno ENOENT
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! spawn sh ENOENT
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/npm/.npm/_logs/2020-01-27T12_14_17_426Z-debug.log
```

Complete log can be found here [https://pastebin.com/DVs4NbtB](https://pastebin.com/DVs4NbtB)

BTW, regarding the first error:
```
www-data@dvil-ubuntu:/var/www/npm$ ls -al /usr/local/n/versions/node/10.16.0/bin/node
-rwxrwxr-x 1 500 500 41115408 may 29  2019 /usr/local/n/versions/node/10.16.0/bin/node
www-data@dvil-ubuntu:/var/www/npm$ /usr/local/n/versions/node/10.16.0/bin/node --version
v10.16.0
```
So the binary exists and runs correctly.

**Comment by chrise86** [comment]
@dvil88 what was the cause of this issue? Facing it myself

**Comment by dvil88** [comment]
@chrise86 the problem was in the PATH of PHP, just set that variable con `putenv()` and it's done
