### ISSUE TITLE
Best way to capture the main frame's Response after page.on('load')?

### ISSUE THREAD

**Issue by sradu** [puppeteer/puppeteer#535]
I'm using page.on('load') to trigger clicks on a page, which might or might not redirect to another page.

However, rarely, those pages trigger errors (eg if there isn't enough capacity), 500, 404, etc. If I watch the 'request' events there's too much noise and I'm not sure how to figure out which one is the main request.

What's the best way to capture the Response HTTP status code of the main frame after page.on('load')?

**Comment by aslushnikov** [comment]
@sradu you can store all the responses by their url and query the right one based on `page.url()`:

```js
const responses = new Map();
page.on('response', response => responses.set(response.url, response));
page.on('load', () => {
  const mainResource = responses.get(page.url());
  console.log('Main resource status: ' + mainResource.status);
});
```

**Comment by sradu** [comment]
Great, thx!

**Comment by jlmagee** [comment]
@aslushnikov  it turns out this is not an adequate solution.  There could be many requests with the same url, such as POSTs with different bodiies, such that these would not line up. 

It would be handy if there were a better way.

**Comment by darkguy2008** [comment]
Agree, I'm also looking for a way to get the HTTP status code for the main page load

**Comment by aslushnikov** [comment]
@darkguy2008 with new versions of pptr:

```js
const response = await page.goto('https://example.com');
console.log(response.status());
```

**Comment by Minyar2004** [comment]
> @darkguy2008 with new versions of pptr:
> 
> ```js
> const response = await page.goto('https://example.com');
> console.log(response.status());
> ```

Does not work when timeout is exceeded
