### ISSUE TITLE
Turn off Anti-aliasing

### ISSUE THREAD

**Issue by darkolacen** [puppeteer/puppeteer#5351]
Hi, is it possible to turn off anti-aliasing? 
I've tried doing it with css(-webkit-font-smoothing: none), but it doesn't work.

Thanks

**Comment by Firefox2005** [comment]
Did anyone find a solution for that?
`font-smooth: never;` doesn't work either.

**Comment by lacendarko** [comment]
Yes, I switched to firefox version. There you can simply set a user preference: `user_pref("gfx.text.disable-aa", true);`

**Comment by Firefox2005** [comment]
Thanks. But unfortunately that is not a solution for me. I run it on AWS Lambda and haven't succeeded in getting Firefox running there. Isn't there a user preference for Chromium that one can set?

**Comment by jeffreyvanhees** [comment]
Anyone who has figured it out yet? I print receipts on a thermal printer (via AWS lambda -> html -> base64 -> react native) and they come out somewhat blurry.
