### ISSUE TITLE
2.1.0 Windows regression: process stays open due to open sockets

### ISSUE THREAD

**Issue by AviVahl** [puppeteer/puppeteer#5356]
Project: https://github.com/wixplosives/mocha-pup

When [upgrading to 2.1.0](https://github.com/wixplosives/mocha-pup/pull/1), tests started failing (timeouts) on Windows CI. Containers got stalled.

My tests execute a CLI which:
- runs webpack
- starts an http server
- launches puppeteer and opens a page.
- checks stuff in the page.
- closes the browser.

Debugging revealed the CLI process never shuts down, as there are two sockets left open:
https://github.com/wixplosives/mocha-pup/runs/413725670

Further investigation suggested it has to do with the browser connection.

Switching to `pipe: true` made it work. :o

Best guess: the WebSocket connection stays open and never gets destroyed.
Suspected PR: https://github.com/puppeteer/puppeteer/pull/5137 (it refactored `Launcher.js`, which has the connection setup)

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.0
* Platform / OS version: Happens only on a CI which runs Windows Server 2019.
* URLs (if applicable): https://github.com/wixplosives/mocha-pup/pull/1
* Node.js version: 12.14.1

**What steps will reproduce the problem?**
I wish it was that easy. :(
I couldn't reproduce the issue locally. I use Fedora 31, and only had Windows 10 at my office (where issue didn't reproduce). Issue happened consistently in every Windows CI run.

_Please include code that reproduces the issue._
Apologies again. I'll try to create a smaller reproducible test-case.
(maybe a script that opens and closes puppeteer 10 times)

**What is the expected result?**
After calling browser.close(), no socket should stay open.

**What happens instead?**
Sockets get left behind, process never exits.

**Comment by AviVahl** [comment]
Still trying to get a smaller reproduction ready.
Meanwhile, I merged to `master`, with `pipe: true`, and opened a separate PR to see the issue:
https://github.com/wixplosives/mocha-pup/pull/2

**Comment by nemchik** [comment]
I believe I may be affected by a similar issue. I have a process in place that works perfectly fine with 2.0.0 but when upgrading to 2.1.0 or 2.1.1 I see intermittent failures with various things I'm doing.

I confirmed with my project that the only change was the version of puppeteer. Do you think it would be possible to confirm that downgrading puppeteer to 2.0.0 resolves your issue?

P.S. I'm not a contributor to this project, just another user 😄

**Comment by AviVahl** [comment]
Downgrading to v2.0.0 consistently works. It is a v2.1.0 regression (which also occurs in v2.1.1).
Saw it making processes getting stuck in both GitHub Actions and Travis containers.

Meanwhile, all projects using puppeteer in our stack have switched to `pipe: true`, as we want the latest Chromium available.

**Comment by nemchik** [comment]
I'll see if I can rig up some testing with `pipe: true` to try and confirm this resolves the issue for me, but hopefully a more permanent fix can be found, or documentation added to explain why `pipe: true` would be needed in some situations.

**Comment by gczobel** [comment]
I'm using a library that uses puppeter and experience the same issue.
I forced puppeter@2.0.0 in my project and consistently works

**Comment by AviVahl** [comment]
Fixed by `puppeteer@3.0.0` on my end. :)

I did have to add `libgbm-dev` to my linux ci for the new chromium version: https://github.com/wixplosives/mocha-pup/commit/07b1d925326e73af2912cb9666c111c38064b7de#diff-353995fb5bebaef307ec25fa5be39042R19
