### ISSUE TITLE
Failing in Travis (TestCafe browser)

### ISSUE THREAD

**Issue by AlexanderC** [puppeteer/puppeteer#536]
Hello `Puppeteer` Team,

We're using `Puppeteer` as [TestCafe](https://devexpress.github.io/testcafe) browser provider and it turned out that `Puppeteer` fails to run in `Travis`. Please refer to the [following](https://travis-ci.org/MitocGroup/recink/jobs/268280374)  `Travis Job`.

Error stack trace:
```
Was unable to open the browser "puppeteer:" due to error.
    
Error: Failed to launch chrome!
    /home/travis/build/MitocGroup/recink/node_modules/puppeteer/.local-chromium/linux-496140/chrome-linux/chrome: symbol lookup error: /home/travis/build/MitocGroup/recink/node_modules/puppeteer/.local-chromium/linux-496140/chrome-linux/chrome: undefined symbol: gtk_widget_get_scale_factor


    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    
        at Interface.onClose (/home/travis/build/MitocGroup/recink/node_modules/puppeteer/lib/Launcher.js:141:14)
        at emitNone (events.js:110:20)
        at Interface.emit (events.js:207:7)
        at Interface.close (readline.js:367:8)
        at Socket.onend (readline.js:147:10)
        at emitNone (events.js:110:20)
        at Socket.emit (events.js:207:7)
        at endReadableNT (_stream_readable.js:1059:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by aslushnikov** [comment]
HI @AlexanderC,

I don't remember this exact error, but we managed to make travis work for our own tests:
- Check out [our config](https://github.com/GoogleChrome/puppeteer/blob/master/.travis.yml) 
- We also [have to pass '--no-sandbox' flag](https://github.com/GoogleChrome/puppeteer/blob/4e3b6a1f57cba8fdfe941b2fd2b70bdeca942328/test/test.js#L50) to make it work on Travis

**Comment by AlexanderC** [comment]
@aslushnikov Thanks for reply, i'm already using `--no-sandbox` (@see https://github.com/MitocGroup/recink/pull/61/files#diff-99fe08f7050dc241613a52c9b792495eR43)

I see you're using `dist: trusty` since our's `dist: precise`, i'll try it to see if it affects puppeteer somehow.

**Comment by AlexanderC** [comment]
Yeah, setting `dist: trusty` in `travis.yml` did the trick!
`Puppeteer` Team, you definitely should have this specified somewhere in the README 😈  

https://travis-ci.org/MitocGroup/recink/jobs/268427887

**Comment by aslushnikov** [comment]
> Puppeteer Team, you definitely should have this specified somewhere in the README 😈

We'll add this somewhere if there are more questions about travis.

For now, the issue per se might be good-enough.

**Comment by avlapeto** [comment]
`dist: trusty` really help.
But have we some way to run tests with `dist: precise` ?

**Comment by gauntface** [comment]
Please reopen this issues as a docs issue and add this info to the faq

**Comment by aslushnikov** [comment]
@gauntface feel free to send a PR.

**Comment by reznord** [comment]
Hi,

We are facing a similar issue with puppeteer not launching on Travis CI only for node 12.

P.S: It is working perfectly fine with Node 13.

Please find the following travis job for reference: https://travis-ci.org/preactjs/preact-cli/jobs/656122013

[This](https://github.com/preactjs/preact-cli/blob/master/packages/cli/tests/lib/chrome.js#L5) is what we do for launching puppeteer instance.

I tried passing `{ args: ['--no-sandbox', '--disable-setuid-sandbox'] }` to puppeteer.launch() as suggested in the comments above, but it didn't work.

[Edit]

This is our `travis.yml` fille: https://github.com/preactjs/preact-cli/blob/master/.travis.yml
