### ISSUE TITLE
Recommend to use puppeteer-proxy

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#5362]
There are [many issues](https://github.com/puppeteer/puppeteer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+proxy+page) relating to use of Puppeteer with proxy.

The common topics are:

* Setting a different HTTP proxy for each Page (e.g. #678)
* Handling authentication (e.g. #3253)
* Removing proxies on the fly (e.g. #4890)

To address these issues I have published package [puppeteer-proxy](https://github.com/gajus/puppeteer-proxy).

puppeteer-proxy intercepts requests after it receives the request metadata from Puppeteer. puppeteer-proxy uses Node.js to make the HTTP requests. The response is then returned to the browser. When using puppeteer-proxy, browser never makes outbound HTTP requests.

The side-benefit of this implementation is that it allows to route all traffic through Node.js, i.e. you can use externally hosted Chrome instance to render DOM & evaluate JavaScript, and route all HTTP traffic through your Node.js instance.

The downside of this implementation is that it will introduce additional latency, i.e. requests will take longer to execute as request/ response will need to be always exchanged between Puppeteer and Node.js.

I believe it would benefit others if it was documented as a viable solution to using HTTP proxies with Puppeteer.

**Comment by gajus** [comment]
Remains relevant

**Comment by gajus** [comment]
Remains relevant

**Comment by OrKoN** [comment]
Hey, thanks for publishing and maintaining the package! I suggest that you include it to https://github.com/transitive-bullshit/awesome-puppeteer which is referenced from our README.
