### ISSUE TITLE
BREAKING - File upload doesn't work with 2.1.0 release

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5363]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.0
* Platform / OS version: any
* URLs (if applicable): any which shows a file input dialog box
* Node.js version: ~12

**What steps will reproduce the problem?**

- Run following script
```
const puppeteer = require("puppeteer");

(async () => {
	const browser = await puppeteer.launch({ headless: false });
	const page = await browser.newPage();
	await page.goto("https://cgi-lib.berkeley.edu/ex/fup.html", {
		waitUntil: "networkidle2"
	});
})();

```
- Click on the "choose file" button

Expectation: A file chooser dialog will appear
Result: Dialog box doesn't appear
End issue: Any upload that requires file chooser dialog breaks.
Possible reason: New changes with #5196

NOTE: It works fine with 2.0.0 release.

**Comment by gajus** [comment]
Related to: https://github.com/puppeteer/puppeteer/issues/5359

**Comment by mathiasbynens** [comment]
> Possible reason: New changes with #5196

`jsHandle.uploadFile` is not used in your example, so it's not likely to be related to #5196, but rather to the upstream changes in https://chromium-review.googlesource.com/c/chromium/src/+/1935410.

**Comment by mathiasbynens** [comment]
I've filed this upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1047107 Thanks for the report!

**Comment by zaki-yama** [comment]
@mathiasbynens 
I have a question about the current status.
I'm facing this problem in the library that uses puppeteer.
It seems related PR (#5369 ) has already been merged, are you going to release the fixed version (v2.1.1?) soon?

**Comment by Georgegriff** [comment]
Im finding the jsHandle.uploadFile is still failing in 2.1.1 is this related or a different issue?

**Comment by gziolo** [comment]
I wanted to integrate Puppeteer `2.1.1` but I see that `fileUpload` still doesn't work:
https://github.com/WordPress/gutenberg/pull/20268#issuecomment-587023772
