### ISSUE TITLE
wait too long to download Chromium, any workaround please?

### ISSUE THREAD

**Issue by videni** [puppeteer/puppeteer#5372]
> puppeteer@1.20.0 install /Users/john/www/acme-admin-ui1/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [==                  ] 8% 11212.5s

**Comment by womcauliff** [comment]
Seeing the same issue of significantly slow download for Chromium, it was downloading about 10% per hour till it just halted at 88%.

- macOS Catalina `10.15.3 (19D76)`
- Node `v10.16.3`
```
> puppeteer@1.20.0 install /Users/willmcauliff/Desktop/Projects/MyProject/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 110.2 Mb [==================  ] 88% 936.3s
```
