### ISSUE TITLE
Can't launch firefox 

### ISSUE THREAD

**Issue by meotimdihia** [puppeteer/puppeteer#5376]
I tried with 2.1.0 but it doesn't work.
```javascript
  const browser = await puppeteer.launch({'headless': false, 'product': 'firefox'})
```

> From Puppeteer v2.1.0 onwards, as an experimental feature, you can specify puppeteer.launch({product: 'firefox'}) to run your Puppeteer scripts in Firefox, without any additional custom patches.

**Comment by meotimdihia** [comment]
```javacript
const puppeteer = require('puppeteer');
(async () => {
          const browser = await puppeteer.launch({
                 'headless': false, 'product': 'firefox',
                  'executablePath': "C:\\Program Files\\Mozilla Firefox\\firefox.exe
          });
          const page = await browser.newPage();
})();
```


(node:23104) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\sources\test2\New folder\node_modules\puppeteer\lib\Launcher.js:751:14)
    at ChildProcess.<anonymous> (C:\sources\test2\New folder\node_modules\puppeteer\lib\Launcher.js:741:61)
    at ChildProcess.emit (events.js:215:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:23104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error: EBUSY: resource busy or locked, unlink 'C:\Users\meoti\AppData\Local\Temp\puppeteer_dev_firefox_profile-5ijv8F\key4.db'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\meoti\\AppData\\Local\\Temp\\puppeteer_dev_firefox_profile-5ijv8F\\key4.db'

**Comment by lfilho** [comment]
I also can't launch Firefox. But got different errors:

Using:
Puppeteer 2.1.0
Firefox 72.0.1
Node 13.5.0
MacOS 10.14.16


```js
    const USER_DATA_DIR = `/Users/${CURRENT_USER}/Library/Application\ Support/Firefox/Profiles/my-profile.default`;
    const BROWSER_PATH = '/Applications/Firefox.app/Contents/MacOS/firefox';

    const browser = await puppeteer.launch({
        product: 'firefox',
        headless: false,
        args: [`-profile "${USER_DATA_DIR}"`],
        // executablePath: BROWSER_PATH
    });

    const page = await browser.newPage();
```

### Error 1
If I leave the `executablePath` commented out as above, it actually opens **Chromium** (!!).

### Error 2
If I leave the `executablePath` line **not** commented out, then it opens Firefox, I briefly see the tab getting created, but then it immediately fails with:

```
Error: Protocol error (Page.setInterceptFileChooserDialog): Page.setInterceptFileChooserDialog RemoteAgentError@chrome://remote/content/Error.jsm:25:5
UnknownMethodError@chrome://remote/content/Error.jsm:108:7
execute@chrome://remote/content/domains/Domains.jsm:96:13
receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:69:45

    at <my-project-path>/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (<my-project-path>/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page._initialize (<my-project-path>/node_modules/puppeteer/lib/Page.js:138:20)
    at Function.create (<my-project-path>/node_modules/puppeteer/lib/Page.js:47:16)
    at <my-project-path>/node_modules/puppeteer/lib/Target.js:74:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser._createPageInContext (<my-project-path>/node_modules/puppeteer/lib/Browser.js:177:18)
    at async file://<my-project-path>/myPuppeteerScript:68:22
  -- ASYNC --
    at Target.<anonymous> (<my-project-path>/node_modules/puppeteer/lib/helper.js:111:15)
    at Browser._createPageInContext (<my-project-path>/node_modules/puppeteer/lib/Browser.js:177:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async file://<my-project-path>/myPuppeteerScript:68:22
  -- ASYNC --
    at Browser.<anonymous> (<my-project-path>/node_modules/puppeteer/lib/helper.js:111:15)
    at file://<my-project-path>/myPuppeteerScript:68:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'Protocol error (Page.setInterceptFileChooserDialog): Page.setInterceptFileChooserDialog RemoteAgentError@chrome://remote/content/Error.jsm:25:5\n' +
    'UnknownMethodError@chrome://remote/content/Error.jsm:108:7\n' +
    'execute@chrome://remote/content/domains/Domains.jsm:96:13\n' +
    'receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:69:45\n'
}
```

Note the **chrome://** protocol stuff.

**Comment by mjzffr** [comment]
Thanks for trying this out. You need to be using Firefox Nightly (74); and yes, the `executablePath` option is required for now.

**Comment by meotimdihia** [comment]
@mjzffr : I can do it now. Tried to `page.screenshot()` and `page.$x` does work too.
But `goto`  return null instead of `Response` object.

**Comment by Sue9445** [comment]
> 
> 
> ```
> const puppeteer = require('puppeteer');
> (async () => {
>           const browser = await puppeteer.launch({
>                  'headless': false, 'product': 'firefox',
>                   'executablePath': "C:\\Program Files\\Mozilla Firefox\\firefox.exe
>           });
>           const page = await browser.newPage();
> })();
> ```
> 
> (node:23104) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
> 
> ```
> at onClose (C:\sources\test2\New folder\node_modules\puppeteer\lib\Launcher.js:751:14)
> at ChildProcess.<anonymous> (C:\sources\test2\New folder\node_modules\puppeteer\lib\Launcher.js:741:61)
> at ChildProcess.emit (events.js:215:7)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> ```
> 
> (node:23104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:23104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [Error: EBUSY: resource busy or locked, unlink 'C:\Users\meoti\AppData\Local\Temp\puppeteer_dev_firefox_profile-5ijv8F\key4.db'] {
> errno: -4082,
> code: 'EBUSY',
> syscall: 'unlink',
> path: 'C:\Users\meoti\AppData\Local\Temp\puppeteer_dev_firefox_profile-5ijv8F\key4.db'

I solved this error by adding the "-wait-for-browser" arg.

**Comment by fabiomgoncalves** [comment]
I'm having the save using puppeteer 3.3.0.

@Sue9445 what is the -wait-for-browser argument? Where do you pass it?

**Comment by mjzffr** [comment]
`wait-for-browser` is a Firefox argument relevant to Windows. This might relevant to #5673

In the meantime, you can include `wait-for-browser` in the `args` option of `Puppeteer.launch`
