### ISSUE TITLE
The 'Set-Cookie' header is missing from the response headers list

### ISSUE THREAD

**Issue by vali-pavel** [puppeteer/puppeteer#5377]
### Steps to reproduce
Stackoverflow link related to this issue:
https://stackoverflow.com/questions/60037606/set-cookie-is-not-included-in-the-response-headers

**Tell us about your environment:**

* Puppeteer version: 2.1.0
* Platform / OS version: Linux
* Node.js version: 11.9.0

**What steps will reproduce the problem?**
https://stackoverflow.com/questions/60037606/set-cookie-is-not-included-in-the-response-headers

_Please include code that reproduces the issue._

1.  code.js
```
const puppeteer = require('puppeteer');

async function getResponseCookies() {
    function handleResponse(response) {
        const url = response.url();
        const headers = response.headers();
        const status = response.status();

        if(url.includes('https://bs.serving-sys.com/Serving/ActivityServer.bs')) {
            console.log('RESPONSE URL ', url)
            console.log('RESPONSE HEADERS ', headers)
        }
    }

    const browser = await puppeteer.launch({
        ignoreDefaultArgs: ["--enable-automation"],
        executablePath: "/usr/bin/google-chrome",
        headless: true,
        ignoreHTTPSErrors: true,
    });

    const page = await browser.newPage();

    await page.setUserAgent("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36");

    await page.on('response', async(response) => {
        await handleResponse(response);
    })

    const urls = [ 'https://www.southwest.com/' ];

    for(const url of urls) {
        await page.goto(url, { timeout: 0, waitUntil: 'networkidle0' });
    }
    await browser.close();
}

getResponseCookies();
```

**What is the expected result?**
The following `Set-Cookie` properties are present in the response headers:
Set-Cookie: **ActivityInfo2**=005E1Mw870_; expires=Sun, 03-May-2020 07:56:00 GMT; domain=.serving-sys.com; path=/
Set-Cookie: **eyeblaster**=; expires=Mon, 01-Jan-2000 00:00:00 GMT; domain=.serving-sys.com; path=/
Set-Cookie: **u2**=59ebe607-e46d-4d33-afbe-50154645e5484tT080; expires=Sun, 03-May-2020 07:56:00 GMT; domain=.serving-sys.com; path=/ 

**What happens instead?**
The response headers don't include the `Set-Cookie` properties:
```
{ pragma: 'no-cache',
  date: 'Mon, 03 Feb 2020 12:49:15 GMT',
  server: 'Microsoft-IIS/7.5',
  'x-powered-by': 'ASP.NET',
  p3p: 'CP="NOI DEVa OUR BUS UNI"',
  'access-control-allow-origin': '*',
  'cache-control': 'no-cache, no-store',
  'content-type': 'text/html; charset=UTF-8',
  'content-length': '0',
  expires: 'Sun, 05-Jun-2005 22:00:00 GMT' }
```

**Comment by hangaoke1** [comment]
same issue , Is there a solution ?

**Comment by RohanAntony** [comment]
Any update on this issue?

**Comment by vali-pavel** [comment]
According to https://github.com/puppeteer/puppeteer/issues/4918, it looks like puppeteer is not listening to the Network.responseReceivedExtraInfo event that contains the raw headers.

**Comment by robertm-97** [comment]
I found a solution for this, answer here: https://github.com/puppeteer/puppeteer/issues/4918#issuecomment-663478790
