### ISSUE TITLE
This package is not compatible with nodejs 6.x, unlike the engines in package.json claims

### ISSUE THREAD

**Issue by wereHamster** [puppeteer/puppeteer#538]
The package uses `Object.entries` which is not implemented in nodejs 6.x (tested with 6.11.1).

**Comment by AlexanderC** [comment]
@wereHamster you might fix it by using `require('object.entries').shim();` https://www.npmjs.com/package/object.entries

**Comment by aslushnikov** [comment]
We need to run CI tests against node6.

**Comment by aslushnikov** [comment]
We published v0.10.1 that fixes issue: https://github.com/GoogleChrome/puppeteer/releases/tag/v0.10.1
