### ISSUE TITLE
Emojis are not displayed in page.pdf 

### ISSUE THREAD

**Issue by MahaZaid** [puppeteer/puppeteer#5382]
I have a url that contains emojis, and I am trying to generate a PDF from this link, but the emojis are not displayed properly, they get displayed as boxes.
Is there any way to generate the Pdf properly with emojis ? 

Here is the code I use to generate the PDF.
```
return puppeteer.launch({
       pipe: true,
        args: [
            '--headless',
            '--disable-gpu',
            '--full-memory-crash-report',
            '--unlimited-storage',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
        ],})
            .then(response => {
                browser = response;
                return browser.newPage();
            })
            .then(response => {
                page = response;
                page.setDefaultNavigationTimeout(0);
                return page.goto(url, {
                    waitUntil: 'networkidle0'
                });
            })
            .then(() => pdf({
                 printBackground: true,
                 width: 1080,
                height: 920,
            }))
            .then(() => {
                browser.close();
                return name;
            });```

**Comment by jurgenwerk** [comment]
Have the same problem! Any solutions available?

**Comment by ymendelsohnYoobic** [comment]
+1

**Comment by sbocinec** [comment]
You haven't provided any further information about environment you are running puppeteer on (OS, puppeteer version, etc..). Though one of the reason might be missing font with emoji support installed on the system where the script is executed. Often fonts `fonts-noto-color-emoji` or also `fonts-opensymbol` are installed on Debian/ubuntu based systems to properly render emojis and symbols.

**Comment by vojkny** [comment]
Hi,

we are using pupeteer as a cloud function where is is not allowed to install anything directly on the machine. Is it somehow possible to include these fonts from package.json?

**Comment by sbocinec** [comment]
@knyttl you can use a workaround with downloading an emoji-supported font on render as mentioned in https://github.com/puppeteer/puppeteer/issues/4086#issuecomment-671385735

**Comment by dkMorlok** [comment]
If somebody using docker image (alpine) then for me works:

```
FROM node:16.14-alpine as base
RUN apk add font-noto-emoji
RUN apk add chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
```

and puppeteer created as:
```
const browser = await puppeteer.launch({
	executablePath: '/usr/bin/chromium-browser',
	args: ['--no-sandbox'],
})
```

Important was add font to image via `RUN apk add font-noto-emoji`.

**Comment by eminvegan** [comment]
> 

I am getting this error if I add RUN apk add font-noto-emoji

`
Step 4/21 : RUN apk add font-noto-emoji
 ---> Running in 5fcbf86f3acb
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  font-noto-emoji (missing):
    required by: world[font-noto-emoji]
The command '/bin/sh -c apk add font-noto-emoji' returned a non-zero code: 1
Error: Process completed with exit code 1.
`

**Comment by OrKoN** [comment]
It looks like you need to install the fonts for emoji. Feel free to re-open with a recent repro and more details if it's still an issue.
