### ISSUE TITLE
Problem with passing html text as 'data:text/html,' when html text contains #

### ISSUE THREAD

**Issue by DenisEke** [puppeteer/puppeteer#5383]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.0
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: v12.14.0

**What steps will reproduce the problem?**

1. Load an html file that contains a '#' with fs.readFileSync()
2. Pass it to page.goto with 'data:text/html,'
3. Notice that it only gets rendered until the '#'

NOTE: # are treated correctly when you pass the html as a file://

**What is the expected result?**
The expected result would be that the # which is included as text will be rendered as text

**What happens instead?**
If you console.log the page object and inspect the url it ends on the #

**Comment by samantp** [comment]
We faced the same issue.

**Comment by mikehemmings** [comment]
You must encode the uri components before passing it into the data:text/html stream

let html = encodeUriComponent({your rendered html});
i.e page.goto(`data:text/html;charset=UTF-8,${html}`, {waitUntil : "networkidle0"});
