### ISSUE TITLE
Unable to open X display.

### ISSUE THREAD

**Issue by fredsco** [puppeteer/puppeteer#5385]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.0
* Platform / OS version: centOS 7
* URLs (if applicable):
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
This is how I launch puppeteer:
```
exports.screenscrapefb = async function screenscrapefb(listingid){
	return new Promise((resolve, reject) => {
		api.getlisting(listingid).then((response) => {
		  response = response.data;
		  console.log(response.property.sellOrRent);
		  (async () => {
			const browser = await puppeteer.launch({
			  headless: true,
			  args: ['--no-sandbox', '--disable-setuid-sandbox'],
			});
```

And I call it:

```
screenscrape.screenscrapefb(id).then((response) => {

				res.send({
					status: 200,
					data: response
				})

				next();
				return;
			});
```

**What is the expected result?**
Screenscrape using pupeteer.

**What happens instead?**
When I run the screenscrape code on the server after doing a get request the logs shows: 

(node:9230) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[20112:20112:0204/070145.780469:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

This problem does not occur when running the script on my local machine. (headless is set to true)

**Comment by lonely2a** [comment]
have you figured out ? i have met the same problem

**Comment by smikodanic** [comment]
Try with headless: true in

puppeteer: {
    executablePath: executablePath,
    headless: false,
    devtools: false,  // Open Chrome devtools at the beginning of the test
    dumpio: false,
    slowMo: 130,  // Wait 130 ms each step of execution, for example chars typing
    args: [`--ash-host-window-bounds=${browserWidth}x${browserHeight}`, `--window-size=${browserWidth},${browserHeight}`, `--window-position=${offsetX},${offsetY}`]
  }

**Comment by Olivia5k** [comment]
I was able to solve a similar issue by granting permissions via `xhost`:

```bash
xhost +SI:localuser:$USER
```
