### ISSUE TITLE
Node.Js with Plesk Cant Run Puppeteer

### ISSUE THREAD

**Issue by ahgsql** [puppeteer/puppeteer#5386]
Puppeteer version: latest 
Platform / OS version: CENTOS 7
 URLs (if applicable):
 Node.js version: 12.4.0

**What steps will reproduce the problem?**

1.Created simple scraper application using puppeteer

```
const puppeteer = require('puppeteer');
var html;
html="osman";
(async () => {
    const browser = await puppeteer.launch({args: ['--ignore-certificate-errors',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--window-size=1920,1080',
            "--disable-accelerated-2d-canvas",
            "--headless",
            "--disable-gpu"]});
    const page = await browser.newPage();

    await page.goto('https://www.guleckeles.com');
    let bodyHTML = await page.evaluate(() => document.body.innerHTML);
    await browser.close();
    html=bodyHTML;

})();

const http = require('http');

const hostname = process.env.PORT;
const port = process.env.PORT;

const server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.end( html);
});

server.listen(port, hostname, () => {
    console.log(`Server running at http://${hostname}:${port}/`);
});

```

2. Deployed and installed dependencies on node.js with Plesk

3. Trying to run but webpage only shows "osman" which is default html value.

**What is the expected result?**

Scraped webpage inner html

**I can get screenshot with ssh in the _vhosts//httpdocs/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux_     ` ./chrome --headless --disable-gpu --no-sandbox --screenshot https://www.example.com`**

**Comment by HiptJo** [comment]
same issue here

**Comment by experimentalPrivateRepos** [comment]
Also having the same problem.

**Comment by co2nut** [comment]
Having the same problem, but I guess we need to find a way to install chrome in the server via ssh?

**Comment by experimentalPrivateRepos** [comment]
> Having the same problem, but I guess we need to find a way to install chrome in the server via ssh?

@co2nut 
I am currently trying to run the `npm install` command on a linux vm and then copying the `node_modules` folder to the plesk server (Cant use the node command in server terminal). Will report back if this works or not

**Comment by HiptJo** [comment]
after some research:
puppeteer spawns a sub-process (chrome headless at last)
as plesk uses passenger within nginx, it is not possible to spawn that process.

sorry - but that means, it is not possible to use the chrome headless engine and further on passenger within a plesk managed hosting instance

**Comment by co2nut** [comment]
Followed the instruction in https://github.com/puppeteer/puppeteer/issues/2857 

I somehow has no error when running it on plesk, but getting empty blob.

is it related?

**Comment by experimentalPrivateRepos** [comment]
@co2nut Have you checked on the server that pupeteer is actually running?  At first I also thought that it was working, but that was my hosting providers hiding of node logs, that masked the actual error.

**Comment by co2nut** [comment]
Yes, it is. 

Because I had some some js script on the browser that call my api for some logging purposes.

**Comment by experimentalPrivateRepos** [comment]
@co2nut have you tested the pupeteer code locally? Does it work as it expected & provide the correct result? This is very weird behaviour.

**Comment by co2nut** [comment]
Yes, it works on my local.

But my local is macOs

**Comment by younes-erraji** [comment]
Actually All You Have to do to make it happen is to pass an 'executablePath' property to the launch method:
  const browser = await puppeteer.launch({
    executablePath: 'Your Browser Path'
  });
and you need to install any browser you like to use.
as for me i installed chrome on the server so the 'executablePath' is: '/usr/bin/google-chrome-stable'

**Comment by fabianwohlfart** [comment]
For me it was installing missing libs on Ubuntu 22.04 LTS with Plesk

`sudo apt update && sudo apt install -y libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libnss3 libxcomposite1 libxcursor1 libxdamage1 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libpango-1.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libdrm2`

Not sure if this has any other implications for Plesk to run this directly from root, yet everything is still up and running.
