### ISSUE TITLE
Get transferSize, encodedBodySize and decodedBodySize for external resources.

### ISSUE THREAD

**Issue by Yivan** [puppeteer/puppeteer#5387]
Hello,

As it is my first post, first thanks for providing to us a such nice API. I really enjoy it.

This issue is about managing to get the main page metrics.  All work great to count number of ressources, get first paint, load time, etc... but i block on getting the total page (with resources) transferSize, encodedBodySize and decodedBodySize.
It works fine for internal resources (same domain), but don't work for external domains.
So making the sum of those metrics for each resource (+navigation) bring a result less than the one reported directly on Chrome DevTools.

It seems this is linked to CORS, cross-resource, please see https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/transferSize

I tested with an external image.
When i make a screenshot, **the resource is well displayed but the transferSize, encodedBodySize and decodedBodySize are all zero**. So it is not a CORS problem as brwoser download/display it. For information, connectStart and connectEnd are zero too.
So I arrive to the conclusion the browser download it and display it, but the `performance.getEntries` don't record it...

It tested with:
- params `'--no-sandbox', '--disable-setuid-sandbox', '--disable-web-security'`
- `await page.setBypassCSP(true);`
- `await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36');` (so it seems real browser)

, and all cache disabled:
```
const client = await page.target().createCDPSession();
await client.send('Network.setCacheDisabled', {
  cacheDisabled: true,
});
await page.setCacheEnabled(false);
```

So the question remains, did I forgot some parameters to allow this, in this case some documentation could be added to help people.
If not, is there any way to do it or can a new feature be added to report those ?

Thanks, best regards,

Thomas

**Comment by Yivan** [comment]
Waiting answer, I manage to get same result than Google Chrome Dev tools with this code, i post here so people wanting do this can base from this code (no-sandox is used as in Docker container):

```
const puppeteer = require("puppeteer");

function convertKoMo(number) {
  numberKo = (number / 1024).toFixed(0);
  if (numberKo >= 1024) return (numberKo / 1024).toFixed(2) + " Mo";
  else return (number / 1024).toFixed(0) + " Ko";
}

(async function() {
  const browser = await puppeteer.launch({args: ['--no-sandbox']});
  const page = await browser.newPage();
  await page.setCacheEnabled(false);
  await page.setBypassCSP(true);
  await page.setViewport({width: 1980, height: 1024});

  let nbRequest = 0;
  let contentLength = 0;
  let encodedDataLength = 0;
  let dataLength = 0;

  page._client.on('Network.dataReceived', (event) => {
    dataLength += parseInt(event.dataLength);
  });

  page._client.on("Network.responseReceived", data => {
    if (!data.response.url.startsWith('data:')) {
      nbRequest++;
      if (typeof data.response.headers['content-length'] !== 'undefined') contentLength += parseInt(data.response.headers['content-length']);
    }
  });

  page._client.on("Network.loadingFinished", data => {
    if (typeof data.encodedDataLength !== 'undefined') encodedDataLength += parseInt(data.encodedDataLength);
  });

  await page.goto("https://www.domain.com", { waitUntil: 'networkidle2' });
  await browser.close();

  // Display metrics
  console.log("Number of requests: " + nbRequest);
  //console.log("Sum of content-length headers: " + convertKoMo(contentLength));
  console.log("Data transfered: " + convertKoMo(encodedDataLength));
  console.log("Page size: " + convertKoMo(dataLength));

})();
```

Having transferSize, encodedBodySize and decodedBodySize would be the must, so I hope some people could help on this issue.
Thanks.

**Comment by uzprocode** [comment]
+1 same issue

**Comment by jstortz** [comment]
We also have the same issue

**Comment by alexkonst** [comment]
You need to add response header Timing-Allow-Origin: * as described here:
https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API#resource_loading_timestamps
