### ISSUE TITLE
PDF creation fails if the directory doesn't exist

### ISSUE THREAD

**Issue by manasesjesus** [puppeteer/puppeteer#5391]
* Puppeteer version: 2.1.1
* Platform / OS version: macOS
* Node.js version: 11.10.0

### Steps to reproduce

1. Specify a directory that doesn't exist

```js
options["path"] = "directory_not_exist_yet/mysavedfile.pdf";
await page.pdf(options);
```

**What is the expected result?**
It'd be great if the plugin itself validates that the directory exists and creates it otherwise.

**What happens instead?**

```
(node:19668) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'directory_not_exist_yet/mysavedfile.pdf'
```

**Comment by NaguFL** [comment]
Facing same issue but in my case directory exists( file yet to be created) but still facing same issue anyone can guide me 
Error: ENOENT: no such file or directory, open 'sample.pdf' puppeteer in heroku

  await webPage.goto(printUrl, { waitUntil: 'networkidle2',});
        await webPage.pdf({
            path: filePartOne,
            format: 'Letter',
            printBackground: true,
            preferCSSPageSize: true,
            displayHeaderFooter: true,
            footerTemplate:footer,
            headerTemplate:headerOne,
           margin: { 
                top: "30mm", 
                bottom: "25mm",
                right: "10mm",
                left: "15mm",
              },         
            pageRanges: '1-'+(headerStartPage-1),
          });
          
          await browser.close();
