### ISSUE TITLE
firefox-puppeteer v0.0.1 not found

### ISSUE THREAD

**Issue by francovenica** [puppeteer/puppeteer#5396]
So I tried to download this using the  "yarn add firefox-puppeteer" command but throws an error because this url:
https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip
shows a "not found"

**Comment by alii** [comment]
That's because it is called `puppeteer-firefox` :)

Reference: https://www.npmjs.com/package/puppeteer-firefox

**Comment by emiljas** [comment]
@aabbccsmith Same problem when you run "npm install puppeteer-firefox"

@mathiasbynens

**Comment by francovenica** [comment]
Sorry I messed up the title of the issue, but as "emiljas" said, the issue is still there with the proper command as well

**Comment by alii** [comment]
My apologies. In that case, I am unable to help you, I'm afraid.

**Comment by ibrahimalthomali** [comment]
I get this error as well during install....

![image](https://user-images.githubusercontent.com/46930956/74529835-8c52b600-4f20-11ea-9d70-ca81f0d9539e.png)
