### ISSUE TITLE
Deprecate puppeteer-firefox in transition to Firefox support in puppeteer

### ISSUE THREAD

**Issue by mjzffr** [puppeteer/puppeteer#5397]
As of [v2.1.0](https://github.com/puppeteer/puppeteer/releases/tag/v2.1.0) puppeteer has alpha-level support of Firefox Nightly via the protocol described at https://wiki.mozilla.org/Remote. 

Meanwhile, [puppeteer-firefox](https://www.npmjs.com/package/puppeteer-firefox) and the ["Juggler" fork of Firefox](https://github.com/puppeteer/juggler) that it depends on are no longer maintained for some time. 

- [x] Add a deprecation message to the puppeteer-firefox package, but keep it available for the time being.
- [x] Remove the code under `/experimental`
- [x] Remove unit test runs against Juggler from CI (#5136 )
- [x] Add deprecation message to Juggler repo; archive it.

**Comment by flogiston** [comment]
From my perspective FF's partial CDP implementation could also be considered experimental, as it misses critical parts of the API (e.g. request interception). So I think the `puppeteer-firefox` package should not be retired prematurely :-)

**Comment by mjzffr** [comment]
@mathiasbynens Proposed deprecation warning to add to puppeteer-firefox package:

> Firefox support is gradually transitioning to the puppeteer package. As of puppeteer v2.1.0 you can interact with Firefox Nightly. The puppeteer-firefox package will remain available until the transition is complete, but it is no longer actively maintained. For more information visit https://wiki.mozilla.org/Remote

**Comment by mjzffr** [comment]
@mathiasbynens What's left to do before the proposed deprecation warning is added?

**Comment by mathiasbynens** [comment]
I’ve added it: https://www.npmjs.com/package/puppeteer-firefox You also get this message when running `npm install puppeteer-firefox`.

**Comment by whimboo** [comment]
This work has been done by PR #8307.
