### ISSUE TITLE
How can I control the certificate dialog ?

### ISSUE THREAD

**Issue by anarko423** [puppeteer/puppeteer#5398]
How can I control the certificate dialog ?

* Puppeteer version: 2.1.1
* Platform / OS version: Windows 10.
* Node.js version: v12.15.0

![32716734-15c7d810-c892-11e7-9646-6561abed6346](https://user-images.githubusercontent.com/20326798/74069424-eb727100-49dc-11ea-84b1-917d2edc170b.png)

**Comment by JoseAngel1196** [comment]
Hey did you solved it?

**Comment by gepd** [comment]
Hey @anarko423 or @JoseAngel1196  can you tell me the steps to get that window? I've been not able to make chromium recognize a certificate, there a comment who seems to solver the problem of the dialog ( https://github.com/puppeteer/puppeteer/issues/540#issuecomment-394785965 ) I'd like to try it

**Comment by bramvanhoutte** [comment]
https://github.com/puppeteer/puppeteer/issues/540#issuecomment-394785965 doesn't work in headless chrome sadly enough.
