### ISSUE TITLE
Error Protocol Error Target Closed  with many type of reason

### ISSUE THREAD

**Issue by rawbin-** [puppeteer/puppeteer#5401]
### Steps to reproduce
it is an error occurs with probability, with the following script we can always see it

repro demo:
https://github.com/rawbin-/puppeteer-test/blob/master/protocol-error-target-closed-repo.js

`node protocol-error-target-closed-repo.js`
**Tell us about your environment:**

* Puppeteer version: 2.0.0/2.1.1/3.0.0
* Platform / OS version: CentOS/MacOS 10.15.3 (19D76)
* URLs (if applicable):  https://github.com/rawbin-/puppeteer-test/blob/master/protocol-error-target-closed-repo.js 
* Node.js version: 12.14

**What steps will reproduce the problem?**
`node protocol-error-target-closed-repo.js`

_Please include code that reproduces the issue._
https://github.com/rawbin-/puppeteer-test/blob/master/protocol-error-target-closed-repo.js

**What is the expected result?**
no Protocol error

**What happens instead?**
different exception occurs from time to time 
```
Error: Protocol error (Emulation.setDeviceMetricsOverride): Target closed.
Error: Protocol error (Target.setAutoAttach): Target closed.
Error: Protocol error (Page.setLifecycleEventsEnabled): Target closed.
Error: Protocol error (Target.setAutoAttach): Target closed.
Error: Protocol error (Log.enable): Target closed.
Error: Protocol error (Performance.enable): Target closed.
Error: Protocol error (Page.enable): Target closed.
Error: Protocol error (Target.attachToTarget): No target with given id found
Error: Protocol error (Page.getFrameTree): Target closed.
Error: Protocol error (Emulation.setTouchEmulationEnabled): Target closed.
Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.
```

![image](https://user-images.githubusercontent.com/8169783/74080707-e61b3200-4a81-11ea-8e3c-1717d233439d.png)

more detail：

        try{
            openPages = await broswer.pages(); // here throws differents exceptions
        }catch (e) {
            // console.warn(broswer.isConnected(),broswer,broswer.target(),broswer.wsEndpoint())
            console.warn('get pages failed:',e)
            await broswer.close();
            process.exit(1)
            return
        }

**Comment by dev-johnny-gh** [comment]
i'm facing the same issue here.

i run a simple service and running a headless chromium to render a simple poster. i guess it caused by memory used up.

here's the error stack:
```
Error: Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.
      at CDPSession.send (/node_modules/puppeteer/lib/Connection.js:180:29)
      at EmulationManager.emulateViewport (/node_modules/puppeteer/lib/EmulationManager.js:41:20)
      at Page.setViewport (/node_modules/puppeteer/lib/Page.js:763:54)
      at Page. (/node_modules/puppeteer/lib/helper.js:111:23)
      at handleTask (/poster-gen/src/generator.js:73:6)
      at Promise (/poster-gen/src/generator.js:105:7)
      at new Promise ()
      at htmlToImage (/poster-gen/src/generator.js:101:10)
      at Object.generate (/poster-gen/src/generator.js:195:28)
      at handler (/poster-gen/src/fission-poster.js:21:35)
    -- ASYNC --
      at Page. (/node_modules/puppeteer/lib/helper.js:110:27)
      at handleTask (/poster-gen/src/generator.js:73:6)
      at Promise (/poster-gen/src/generator.js:105:7)
      at new Promise ()
      at htmlToImage (/poster-gen/src/generator.js:101:10)
      at Object.generate (/poster-gen/src/generator.js:195:28)
      at handler (/poster-gen/src/fission-poster.js:21:35)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by alex-alecu** [comment]
Any updates on this? We're experiencing the same issue ⬆️

**Comment by SoraDaibu-Makip** [comment]
Any updates on this issue? We are experiencing the same error a few times for one crawling.

**Comment by jlvernam** [comment]
Same issue here, ran into it Today- Jun 28th. Any updates?

**Comment by yki-hong** [comment]
Same issue here, any updates?

**Comment by chrisdel101** [comment]
How can I fix this? Puppetter keeps crashing when I call it from inside a loop. Each call makes:
```
 const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--use-gl=egl'],
    })```

**Comment by OrKoN** [comment]
I was not able to repro in the latest version. It is possible that the page gets closed/shut down by the browser for whatever reason, in that case you can get those errors. Please re-open with a recent repro if it's still an issue.

**Comment by jacty** [comment]
Try to turn off headless mode to see if the page closed or crashed accidentally.
