### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by GWevroy** [puppeteer/puppeteer#5403]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by GWevroy** [comment]
Hi, I see this error has been reported before (but closed). I am having the same error. I am using Markdown in VS Code on Linux 18.04. When I click in the preview window and select Chrome (Puppeteer) -> PDF, I get told "Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

I have tried the suggestions in the earlier posting regarding this problem, but it doesn't help. Chromium is installed (version 79.0.3945.130) and I see the version number (though it's a different number with no decimal points) in the Node Modules .json file.

Sorry, I don't see where/how to view version info of either Puppeteer or Node.js. They are all latest installations though (as of the last few days). I know Puppeteer is installed as I can see the folder on my system, as well as the node modules (tried editing the launcher.js file as instructed on another forum page, to include the executable path for Chromium, but no luck either)

Any ideas?

**Comment by CluEleSsUK** [comment]
Also getting a similar error on Puppeteer 2.1.1:
```
Browser is not downloaded. Run \"npm install\" or \"yarn install\""
```
I'm running inside a docker container (node:10-slim) on an OSX host and have tried both installing chromium manually (using `npm install chromium`) and downloading `google-chrome-stable_current_amd64` as well as the necessary dependencies (I was getting a different error pre-dependencies)

**Comment by CluEleSsUK** [comment]
As an update to my woes - because my Dockerfile build was running on a mac, but the image itself was running alpine, the `RUN npm install` task was pulling the mac version of chromium, and the alpine container was then not finding it.
I mitigated this by installing chromium manually into my image, and telling puppeteer not to download a chromium like so:
```
RUN apk add -U --no-cache --allow-untrusted udev ttf-freefont chromium git
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser
```
and updated my usage of puppeteer as follows:
```
await puppeteer.launch({
    headless: true,
    executablePath: process.env.CHROMIUM_PATH,
    args: ['--no-sandbox'],
  })
```

Sorry if this is slightly off-topic, but it might help someone!

**Comment by aruprakshit** [comment]
@CluEleSsUK Are you using `puppeteer` or `puppeteer-core`? I installed:

```json
 "dependencies": {
    "chrome-aws-lambda": "^1.11.1",
    "express": "^4.17.1",
    "puppeteer-core": "^1.11.0"
  },
```
I am having the same issue as this ticket has in subject.

**Comment by ethans333** [comment]
Did anyone solve this issue?

**Comment by Manoj-nathwani** [comment]
Looks like I managed to fix this!

## Check out the official puppeteer <> docker docs:
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker

## Example project

`Dockerfile`
```
FROM node:12-slim

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH google-chrome-stable

ADD package.json package-lock.json /
RUN npm install

# configure puppeteer user
RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /node_modules
USER pptruser

COPY . /app
WORKDIR /app

CMD ["npm", "start"]
```

`package.json`
```
{
    "name": "Sample Project",
    "version": "1.0.0",
    "scripts": {
        "start": "node main.js"
    },
    "dependencies": {
        "puppeteer": "^5.3.0",
    }
}
```

`main.js`
```
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
	  executablePath: process.env.CHROMIUM_PATH,
	  args: ['--no-sandbox'],
  });
  const page = await browser.newPage();
  await page.goto('https://www.google.com');
  // other actions...
  await browser.close();
})();
```

**Comment by nhhockeyplayer** [comment]
This all of a sudden just broke on me

after upgrading to node.js 15
and angular 11
which both run fine

but puppeteer fails

all I have installed in my package.json is puppeteer-core

Is another package needed?

ERROR code=Error, message=Chromium revision is not downloaded. Run "npm install" or "yarn install"

Do I need 
"puppeteer": "^5.3.0",

in addition to puppeteer-core@5.3.0

?
