### ISSUE TITLE
codeceptjs/puppeteer cannot find ANY of the elements on a page, waitForNavigation never finishes

### ISSUE THREAD

**Issue by amustafa15** [puppeteer/puppeteer#5404]
### Steps to reproduce

So I cannot load or find a single element on a page. I use `I.amOnPage()` to navigate to the correct page. but when the code gets to `I.waitForNavigation` it never resolves. it just pauses there forever. I tried everything suggested [here](https://docs.w3cub.com/codeceptjs/helpers/puppeteer/) but nothing changes that. so I tried `I.waitForElement('.body')` and nothing. according to puppeteer/codeceptjs there is no body element on this page. it can find the iframe alright but it cannot find the body or any other element by text, css or xpath. it seems the only stuff it can find is the navigation menu. 

**Tell us about your environment:**

* Puppeteer version: whatever the latest version is
* Platform / OS version: Mac OS whatever the most recent is
* URLs (if applicable):
* Node.js version: most recent

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I.amOnPage('https://artemis-test2.atlassian.net/wiki/plugins/servlet/ac/com.nurago.confluence.plugins.treecopy/copy-page-tree-confluence?page.id=25821196&space.key=TEST1');

    I.waitForNavigation();
    I.wait(4);
    I.waitForElement('.ap-iframe');
    I.waitForElement('.body');

**What is the expected result?**
 the expected result is that after `I.waitForNavigation()` the code then interacts within the body element. as it stands now it says there is no body element on the entire page. it is impossible to interact with any of the elements on the page.

**Comment by Georgegriff** [comment]
I'm also a CodeceptJS uses i'd suggest that you open this issue on codecepts github: https://github.com/Codeception/CodeceptJS/issues Puppeteer project won't know anything about this syntax.
There is also a codeceptjs slack: http://bit.ly/chat-codeceptjs

**Comment by amustafa15** [comment]
I already posted it on the slack channel and haven't heard anything

**Comment by Georgegriff** [comment]
puppeteer will just close this because not relevant to them, so raise it there: 
From my experience you shouldn't use I.waitForNavigation like this because I.amOnPage waits for page load to have occurred so you don't need I.wantForNavigation afterwards.

**Comment by amustafa15** [comment]
I created a new issue on the codeceptjs. but even if I skip out on waitForNavigation() it still says there are no visible elements on the page. any experience with this issue?
