### ISSUE TITLE
Add support for BrowserContext 

### ISSUE THREAD

**Issue by alisterscott** [puppeteer/puppeteer#5408]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: macOS
* Node.js version: 13.8.0

** Puppeteer Feature Request **

Playwright introduces the concept of BrowserContext objects:

> Playwright also aims at being cloud-native. Rather than a single page, BrowserContext abstraction is now central to the library operation. BrowserContexts are isolated

It would be really nice to see these in Puppeteer as it allows you to run isolated independent tests using a single browser instance.

Example code:
```
		browser = await playwright.chromium.launch();
		context = await browser.newContext();
                page = await context.newPage( 'https://google.com' );
```

**Comment by seanpoulter** [comment]
Great suggestion @alisterscott. Would the dev team consider adding it? If so is that something you'd want to take on or would you welcome a PR?
