### ISSUE TITLE
[Question]Screenshots between Mac OS 10.12.5 and Ubuntu(travis) is different, is it a bug?

### ISSUE THREAD

**Issue by plantain-00** [puppeteer/puppeteer#541]
```js
      const puppeteer = require('puppeteer')
      const server = createServer()
      server.listen(8000)
      const browser = await puppeteer.launch()
      const page = await browser.newPage()
      await page.goto(`http://localhost:8000/demo/`)
      await page.screenshot({ path: `spec/test.png`, fullPage: true })
      server.close()
      browser.close()
```

The mac os X one is always 134KB

![vue](https://user-images.githubusercontent.com/7639395/29712009-46dd10d4-89ca-11e7-975e-2c73b04cfb15.png)

The travis one is 130KB

![a](https://user-images.githubusercontent.com/7639395/29712040-6bb7c93a-89ca-11e7-877a-987b5827bb03.png)

**Comment by aslushnikov** [comment]
Usually text rendering differs from platform to platform - this might be the reason in your case.
