### ISSUE TITLE
fullPage changes viewport size or changes element positions

### ISSUE THREAD

**Issue by ibrahimalthomali** [puppeteer/puppeteer#5411]
Puppeteer is apparently resizing the viewport size or changing element positions when taking a fullPage screenshot. Visually testing pages using the fullPage screenshot feature is currently problematic because they do not match pixel wise to the coordinates in the expected viewport size set prior to screenshot.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Windows 10
* Node.js version: 13.3.0
* NPM version: 6.13.4
* Browser: Packaged Chromium

**What steps will reproduce the problem?**
1. Visit web page and set viewport.
1. Take coordinates of an element.
2. Take screenshot using fullPage mode. (In headless or GUI)
3. Stroke rectangle around element in the fullPage Screenshot image.
4. Repeat with non fullPage mode and compare if neccessary.

**EXAMPLE 1:** 
Webpage Repository: https://github.com/redecheck/example-webpages/tree/master/3-Minute-Journal
Full-xpath-1: /HTML/BODY/DIV[3]/DIV/DIV[2]/DIV/DIV/DIV[2]/DIV[8]
Full-xpath-2: /HTML/BODY/DIV[3]/DIV/DIV[2]/DIV/DIV/DIV[2]

**Here is a screenshot using fullPage at viewport 992...**
![image](https://user-images.githubusercontent.com/46930956/74251804-94261680-4ce4-11ea-81a7-4d1855e197dd.png)

**Here is a normal screenshot  at viewport 992...**
![image](https://user-images.githubusercontent.com/46930956/74251867-b1f37b80-4ce4-11ea-8467-2d45b594d624.png)

**EXAMPLE 2:**
Webpage Repository: https://github.com/redecheck/example-webpages/tree/master/Pepfeed

Full-xpath-1: /HTML/BODY/DIV[2]/DIV[2]/DIV/DIV[2]/DIV/DIV[2]/DIV/DIV[2]
Full-xpath-2: /HTML/BODY/DIV[2]/DIV[2]/DIV/DIV[2]/DIV/DIV[2]/DIV/DIV/DIV[2]/DIV[3]
**Here is a screenshot using fullPage at viewport 950...**
![image](https://user-images.githubusercontent.com/46930956/74254440-5b883c00-4ce8-11ea-9e91-103f76129914.png)

**Here is a normal screenshot  at viewport 950...**
![image](https://user-images.githubusercontent.com/46930956/74254677-aefa8a00-4ce8-11ea-8395-ee68bb358a9e.png)

**What is the expected result?**
I expect that coordinates and viewport size remains the same during screenshots using fullPage.

**What happens instead?**
I assume viewport size changes.

**Comment by vasyl-design** [comment]
I also have this issue, and it's very annoying as it messes up some screenshots. 
For example, I need to take a screenshot of the drop-down menu that shows up upon hover. But when the puppeteer resizes viewport menu colapses. 
@ibrahimalthomali  do you have any suggestions to avoid viewport resizing?

**Comment by Padge91** [comment]
I experienced similar issues. A workaround that was sufficient for me was to change my code to take screenshots of the body element instead, which doesn't appear to fire the resize event (at least in my case).
`
const bodyElement = await page.$("body");
await bodyElement.screenshot({path:"out/example.png"});
`
