### ISSUE TITLE
Ubuntu 18.04 - Error: Failed to launch the browser process

### ISSUE THREAD

**Issue by radiolondra** [puppeteer/puppeteer#5412]
### Steps to reproduce

**Tell us about your environment:**
Installed puppeteer and all the dependencies.

* Puppeteer version: 2.1.1
* Platform / OS version: Ubuntu 18.04 32 bits
* URLs (if applicable):
* Node.js version: 8.16.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

const puppeteer = require('puppeteer');
(async () => {
        const browser = await puppeteer.launch({
                headless: false,
                args: ['--no-sandbox']
        });
        const page = await browser.newPage();
        await page.goto('https://example.com');
        await page.screenshot({
                path: 'example.png'
        });
        await browser.close();
})();

**What is the expected result?**

Open chrome and take a screenshot

**What happens instead?**

~/superScraper$ **node test.js**
(node:7891) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 1: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: �: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 1: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: ELF: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 2: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: p#: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 3: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: p#: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 4: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: @l�: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 5: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: pX: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 6: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: pX: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 4: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: ��q: not found
/home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 7: /home/vidguru/superScraper/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: Syntax error: "(" unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/vidguru/superScraper/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.helper.addEventListener (/home/vidguru/superScraper/node_modules/puppeteer/lib/Launcher.js:739:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
(node:7891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7891) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AviVahl** [comment]
Probably fails (not really sure) because OS is 32 bit?
https://itsfoss.com/google-ending-chrome-32-bit/

EDIT: The hint is "ELF: not found". According to Google, the system cannot run the binary, so it tries executing it as a bash script...

**Comment by radiolondra** [comment]
I tried the same script in a Ubuntu 64bits. Same result.
I had to transform a bit the script:

```
const puppeteer = require('puppeteer');
async function main() {
const browser = await puppeteer.launch({
headless: false,
args: ['--no-sandbox']
});
const page = await browser.newPage();
await page.goto('https://example.com');
await page.screenshot({
path: 'example.png'
});
await browser.close();
}

// Start the script
main();
```

and now it works (32 and 64 bits). Thanks @AviVahl 

So we can close this issue.

**Comment by leandroslemes** [comment]
UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0918/155121.241566:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.<anonymous> (/root/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
    at Interface.emit (events.js:412:35)
    at Interface.emit (domain.js:532:15)
    at Interface.close (readline.js:451:8)
    at Socket.onend (readline.js:224:10)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:532:15)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process![1631980379565]

**Comment by partiid** [comment]
Have the same problem on digitalocean droplet. How can i run the browser?

**Comment by martinl86** [comment]
> 

hey did you fix your issue, i have same problem
