### ISSUE TITLE
Issue launching chrome using puppeteer in Azure function App

### ISSUE THREAD

**Issue by SRIHABER** [puppeteer/puppeteer#5415]
**Tell us about your environment:**
I am trying to do create an automated report that logins to a  website and takes some screenshot s an send an email using puppeteer and setting up in Azure time trigger function App.

* Puppeteer version: 2.1.1
* Platform / OS version: windows 10
* URLs (if applicable):
* Node.js version: 10.16.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Make your puppeteer script as function app and move Azure Service 
2 When running the app on function it is failing with

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:533:9)
    at BrowserRunner.start (D:\home\site\wwwroot\node_modules\puppeteer\lib\Launcher.js:77:30)
    at ChromeLauncher.launch (D:\home\site\wwwroot\node_modules\puppeteer\lib\Launcher.js:242:12)

tried to implement docker image suggestion 
https://github.com/estruyf/azure-function-node-puppeteer

but it didnt help.. Any suggestion.

**Comment by SRIHABER** [comment]
I was able get this issue fixed by using linux function app with a docker image to get chromium installed and run the my automation scripts

**Comment by akshayDatacode** [comment]
same isssue
