### ISSUE TITLE
"Protocol error (Page.navigate): Cannot navigate to invalid URL undefined" when redirect location is a relative URL

### ISSUE THREAD

**Issue by FdezRomero** [puppeteer/puppeteer#542]
Hi!

When navigating to a page that redirects with a relative URL in the `Location` header, Puppeteer throws the error `Protocol error (Page.navigate): Cannot navigate to invalid URL undefined`.

**Example:**
https://savelist.co/about => https://savelist.co/about/en

```
$ curl -v https://savelist.co/about
*   Trying 104.208.246.229...
* TCP_NODELAY set
* Connected to savelist.co (104.208.246.229) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: savelist.co
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /about HTTP/1.1
> Host: savelist.co
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
< Server: nginx/1.13.4
< Date: Fri, 25 Aug 2017 11:44:06 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: /about/en/
< Strict-Transport-Security: max-age=15768000
< X-Server: savelist-web02
< X-Time: 0.000
<
* Connection #0 to host savelist.co left intact
```

Relative URLs in the Location header are supported in HTTP 1.1 ([RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.2)).

Thanks!

**Comment by aslushnikov** [comment]
What's your puppeteer script? The following works fine for me:
```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://savelist.co/about');
  console.log(page.url()); // prints "https://savelist.co/about/en/"
  browser.close();
})();
```

**Comment by FdezRomero** [comment]
Hi @aslushnikov, my test script was the same as yours, with the exception of using the request interceptor before navigating to the page:

```js
page.on('request', request => request.continue());
await page.setRequestInterceptionEnabled(true);
```

Whatever it was it's no longer happening in 0.10.1, or I'm not being able to reproduce it now.

Thanks!

**Comment by 296223944** [comment]
I met this problem too,  It seems this kind of  url can not access by "curl xxx" too.  It can not resolve the host locally, But this kind of url can be accessed in chrome browser.  When in puppeteer, It throws "protocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL". I tried to add ignoreHTTPSErrors:true in launch options but it not works.
