### ISSUE TITLE
page.waitForNavigation hangs forever

### ISSUE THREAD

**Issue by ecolss** [puppeteer/puppeteer#5422]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@2.0.0
* Platform / OS version: MacOS Catalina, 10.15.3 (19D76)
* URLs (if applicable): https://www.escentual.com/catalogsearch/result/?q=face
* Node.js version: v12.13.0

**What steps will reproduce the problem?**
Full code as follows, just trying to go to 10 pages by clicking the *next* link on each page.
```js
const pptr = require('puppeteer');

async function main() {
  const br = await pptr.launch({headless: false, defaultViewport: null});
  const page = await br.newPage();

  await page.goto(
    'https://www.escentual.com/catalogsearch/result/?q=face',
    {waitUntil: 'networkidle2'}
  );

  for (var i=0; i<10; ++i) {
    await Promise.all([
      page.waitForNavigation({waitUntil: 'load', timeout: 100000}),
      page.click('#adj-nav-container > div.category-products > div.toolbar > div > div.amount > div > ol > li.next > a'),
    ]);
    console.log(`waited, url=${page.url()}`);
  }
  await br.close();
}

main();
```

**What is the expected result?**
I was expecting the above code could go to `10` pages by clicking the *next* link on each page.

**What happens instead?**
However, the above code gets stuck at 2nd page forever, waiting `waitForNavigation` to finish forever.

**Comment by ecolss** [comment]
If I remove or replace the `page.waitForNavigation` in the above code, it works.
So I thought maybe there is no *navigation* event happening at all after the click?

But this speculation doesn't make sense, since according to the [waitForNavigation](https://pptr.dev/#?product=Puppeteer&version=v2.1.1&show=api-pagewaitfornavigationoptions) documentation, if the `page` navigates to a **new url**, it should have a navigation event, right?

**Comment by dariomx** [comment]
I just got the exact same issue. After trying all sort of options for the waitForNavigation (timeouts, network idle, etc); I found your post and tried the same trick of deleting the waitForNavitation ... and indeed it worked for me as well. 

Either we do not understand under what circumstances a navigation event is generated, or there is a bug somewhere that does not always generate that.

Thanks for the workaround though, hope this issue gets attended.

**Comment by bland328** [comment]
For what it's worth, I often run into this problem using both Puppeteer and the "Pyppeteer" Python port, and still have not figured out the "one true cure."  Any insight as to the potential root cause of this would be greatly appreciated.

**Comment by atin** [comment]
Is this issue resolved? I'm having the same problem.

**Comment by lesagi** [comment]
hi, any solution to this problem? it happens to me as well... is there a way to overcome this issue?
I assume waiting for 'load' and 'contentload' under some considerations won't work as it reacts to a fired event that doesn't necessarily happen if the page is already loaded. but what about networkidle?

Thanks

**Comment by mitchied** [comment]
Any updates on this one?

**Comment by ushuz** [comment]
> Either we do not understand under what circumstances a navigation event is generated, or there is a bug somewhere that does not always generate that.

I think it's a bug. Even if there's no navigation event, the wait should throw timeout error instead of hanging forever.

**Comment by ushuz** [comment]
> Either we do not understand under what circumstances a navigation event is generated, or there is a bug somewhere that does not always generate that.

I think it's a bug. Even if there's no navigation event, the wait should throw timeout error instead of hanging forever.

**Comment by alecsci** [comment]
Reproduced it with puppeteer: 10.0.0, node: 14.16.0, npm: 6.14.11.
I also tried the recommended best practice from the [official-docs](https://pptr.dev/#?product=Puppeteer&version=v10.0.0&show=api-pagewaitfornavigationoptions) and still hangs forever.
Similar behavior for page.waitForResponse

**Comment by darksectordds** [comment]
`"puppeteer": "^24.10.0"` issue still exists. Sometimes `page.waitForNavigation()` hanging forever.

I noticed a feature that after `page.click()`, which should open a new tab, the old link is still preserved.

I'm use `dirty hack` like

```js
    await Promise.all([
        page.goto( url, {waitUntil: 'load', timeout: 0}),
        page.waitForNavigation(),
    ])
```

I generate the url myself from the collected data on the page.
