### ISSUE TITLE
Please upgrade rimraf version in package.json to fix the exception by fixWinEPERM

### ISSUE THREAD

**Issue by dsheiko** [puppeteer/puppeteer#5425]
Currently (Puppeteer 2.1.1) on Windows 10 throws 
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:                                      
  assert(er instanceof Error)
  at fixWinEPERM (.\node_modules\rimraf\rimraf.js:175:5)
```
pretty much the same as described here https://github.com/isaacs/rimraf/issues/155

My guess, it happens when puppeteer removes tmp folder on this.proc exit event: 
https://github.com/puppeteer/puppeteer/blob/master/lib/Launcher.js#L99

However, if one updates the `rimraf` to the latest version, everything works fine.
E.g.
```
cd node_modules/puppeteer
npm i rimraf@latest
```
 
P.S. I'm running puppeteer with the following options:

```js
await puppeteer.launch(
    "product": "firefox",
    "headless": false,
    "devtools": false,
    "ignoreHTTPSErrors": false,
    "args": [
      "--wait-for-browser"
    ],
    "executablePath": "C:\\Program Files (x86)\\Nightly\\firefox.exe"
  });
```

**Comment by aslushnikov** [comment]
For the record: this was investigated in https://github.com/isaacs/rimraf/issues/208 and fixed with https://github.com/isaacs/rimraf/commit/aa50e0298f66b3375045e8d9d86992d696a56b09
