### ISSUE TITLE
Installation Failure -  releaseObject unexpected identifier exception

### ISSUE THREAD

**Issue by ghoroupi** [puppeteer/puppeteer#5428]
********
Installing puppeteer on Mac (Mojave 10.14.6), I'm getting the following exception even after installing updates to all dependencies:

➜  ~ npm install -g puppeteer

> puppeteer@2.1.1 install /usr/local/lib/node_modules/puppeteer
> node install.js

/usr/local/lib/node_modules/puppeteer/lib/helper.js:91
  static async releaseObject(client, remoteObject) {
               ^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/puppeteer/index.js:17:18)
    at Module._compile (module.js:541:32)
npm ERR! Darwin 18.7.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "puppeteer"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@2.1.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ghoroupian/npm-debug.log

**Comment by niamzor** [comment]
Got the exact same error with node v6.10.3 and npm v3.10.10.
Upgrading to a more recent version of node fixed the issue (v10.16.3 in my case).

**Comment by OnePlus7** [comment]
same error in node 6 and use v7.10.1 fixed the issue

**Comment by tyleryoungblood** [comment]
This error is back ... using Node v12.18.3. Anyone else? Should I downgrade Node?

**Comment by mohammadjavadnouri** [comment]
I had the same issue,
I read the error log completely and found that mine refers to lack of: "chromium 722234" so then I searched to how should I install that thing.
