### ISSUE TITLE
Headful mode doesn't launch (Unable to open X display.)

### ISSUE THREAD

**Issue by dundunn** [puppeteer/puppeteer#5429]
```
"version": "2.1.1"
```

```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

$ node -v
v12.14.1
```

### Steps to reproduce
```
$ mkdir test && cd test && npm install puppeteer

> puppeteer@2.1.1 install /home/dun/_workspace/test/node_modules/puppeteer
> node install.js

Downloading Chromium r722234 - 121.1 Mb [====================] 100% 0.0s
Chromium downloaded to /home/dun/_workspace/test/node_modules/puppeteer/.local-chromium/linux-722234
npm WARN saveError ENOENT: no such file or directory, open '/home/dun/_workspace/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/dun/_workspace/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ puppeteer@2.1.1
added 43 packages from 24 contributors and audited 51 packages in 13.217s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ touch test.js && echo "const puppeteer = require('puppeteer');
>
> (async () => {
>     const browser = await puppeteer.launch({
>         headless: false,
>         args: ['--no-sandbox']
>     });
> })();" >> test.js

$ node test.js
(node:24628) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[24639:24639:0219/092954.631392:ERROR:browser_main_loop.cc(1512)] Unable to open X display.
[0219/092954.642321:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/dun/_workspace/test/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/home/dun/_workspace/test/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:228:7)
    at Interface.close (readline.js:402:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:24628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
**What is the expected result?**
Puppeteer should launch in headful mode. 

**What happens instead?**
Puppeteer throws error and exits. 

I ran `$ sudo apt install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 l               ibgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 li               bx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libx               ss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils` and restarded my server but it didn't help.

**Comment by kevin8988** [comment]
@dundunn Set headless to true :)

**Comment by dundunn** [comment]
> @dundunn Set headless to true :)

That would be counterproductive if I wanted to start puppeteer in headful mode wouldn't it?

**Comment by chilipote** [comment]
I actually have the same error when running my puppeteer script with a regular user but It's working well when I'm running the same command as a root user.

I'm also interested in his error :)

**Comment by mooocer** [comment]
I'm facing a similar error when I try to run Puppeteer locally via cron:

```
Error: Failed to launch the browser process!
[6630:6630:0505/185507.905416:ERROR:browser_main_loop.cc(1485)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/vaibhav/projects/myproject/node_modules/puppeteer/lib/Launcher.js:615:20)
    at ChildProcess.<anonymous> (/home/vaibhav/projects/myproject/node_modules/puppeteer/lib/Launcher.js:606:67)
    at ChildProcess.emit (events.js:215:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
script.js
```

**Comment by adminbestbet** [comment]
+1

**Comment by adminbestbet** [comment]
I set up a piece of code, so it won't work:

`
env: { TZ: 'Europe/London', },
`

Normal operation after removal.

**Comment by lsayle** [comment]
+1

**Comment by salespaulo** [comment]
+1

**Comment by wawxxjm** [comment]
Similar issue but my puppeteer version is 3.1.0. If I just run chrome with --no-sandbox, it says Unable to open X display.
If I run my example.js with headless mode, it says Page crashed!
I am running on Ubuntu 16.04, but it works fine on my Mac.

**Comment by paulwongx** [comment]
I've spent countless days searching the internet on a solution for this. Everyone with this issue (including me) is probably using Windows and possibly WSL2. Issue is a compatibility issue with WSL2. Not sure how to fix as I still have the issue.

Edit: Solution seems to be to setup an X Display like vcXsrv so that the linux subsystem (WSL2) has a monitor to display on. But making it work with WSL2 is still not clear as many tutorials online are based on WSL1. I tried many tutorials to setup vcXsrv with latest WSL2 but couldn't get it to work. Alternatively, you can try running your script using a windows based terminal instead of wsl2.

**Comment by AlbertGozzi** [comment]
+1 to https://github.com/puppeteer/puppeteer/issues/5429#issuecomment-633785854, seems to be a compatibility issue with WSL. Switching from running the code on the WSL to Windows Powershell solved it for me.

**Comment by simonobe** [comment]
what is the status on this one?
EDIT: I also have the "Unable to open X display" problem. I am using Xubuntu 18 (Desktop version with display and stuff) but still get this error. 
Puppeteer version 3.1.0

**Comment by muglikar** [comment]
> what is the status on this one?
> EDIT: I also have the "Unable to open X display" problem. I am using Xubuntu 18 (Desktop version with display and stuff) but still get this error.
> Puppeteer version 3.1.0

+1

**Comment by laxsin** [comment]
Any solution to this error?
I am facing the same in GCP CentOS (NO GUI) system. I want to launch chrome but it says the above error. Have installed mentioned in link https://stackoverflow.com/questions/60304251/unable-to-open-x-display-when-trying-to-run-google-chrome-on-centos-rhel-7-5   answered by Hussian.

Need the solution badly. I don't have option to change OS as this is what my client wants me to use.

**Comment by laxsin** [comment]
maven users!

I added below dependencies in pom.xml

   
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<version>3.141.59</version>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-chrome-driver</artifactId>
			<version>3.141.59</version>
			<scope>main</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-api</artifactId>
			<version>3.141.59</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>25.0-jre</version>
		</dependency>

   
and removed below in my webdriver setup file:

options.setHeadless(true);
options.setAcceptInsecureCerts(true);


but, I passed these arguments as below then,
options.addArguments("--headless");




This above error (Unable to open X display) was gone! 
However, I have new error as "NoClassDefFoundError: org/openqa/selenium/virtualauthenticator/HasVirtualAuthenticator". 
Good luck!

**Comment by NegruGeorge** [comment]
> I actually have the same error when running my puppeteer script with a regular user but It's working well when I'm running the same command as a root user.
> 
> I'm also interested in his error :)

did you manage to fix it ?

**Comment by dbolger** [comment]
Is there any suggested way to fix this? I'm trying to view a headful browser while in VNC on Xfce. I'm able to view my desktop however I cannot, for my life, get headful mode to work. Google-fu isn't working.

Edit:
`export DISPLAY=:1.0` seems to be working.

**Comment by ayezinzu** [comment]
> Is there any suggested way to fix this? I'm trying to view a headful browser while in VNC on Xfce. I'm able to view my desktop however I cannot, for my life, get headful mode to work. Google-fu isn't working.
> 
> Edit:
> `export DISPLAY=:1.0` seems to be working.

wait, whats working ? can you explain how to make it work ?

**Comment by Kingwl** [comment]
@kevin8988 

> Set headless to true :)

Can't believe I spent an hour on this :XD

**Comment by Yorisoft** [comment]
@FivePixels Would very much appreciate if you could walk me through all that you did. I'm trying to do the same exact thing - run puppeteer inside a docker container user Xfce and pass in commands through jenkins pipeline. 

@AlbertGozzi  Im currently on ubuntu 20.04 using gnome-terminal. Running it on my local machine inside a docker container works fine. It's when I send it through the jenkins pipeline that I get the error. ( pipeline is also hosted on an ubuntu server).

**Comment by wontheone1** [comment]
this happens on my mac too

**Comment by Fabiomad85** [comment]
Same issue here, I am not able to solve it

**Comment by beemi** [comment]
`export $DISPLAY`

Chrome launch options need to set as below.

` args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-extensions-except=' + this.extensionPathBuildPath,
        '--load-extension=' + this.extensionPathBuildPath
      ]`

**Comment by juveria-manzar** [comment]
> I'm facing a similar error when I try to run Puppeteer locally via cron:
> 
> ```
> Error: Failed to launch the browser process!
> [6630:6630:0505/185507.905416:ERROR:browser_main_loop.cc(1485)] Unable to open X display.
> 
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
> 
>     at onClose (/home/vaibhav/projects/myproject/node_modules/puppeteer/lib/Launcher.js:615:20)
>     at ChildProcess.<anonymous> (/home/vaibhav/projects/myproject/node_modules/puppeteer/lib/Launcher.js:606:67)
>     at ChildProcess.emit (events.js:215:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> script.js
> ```

How did you resolve?

**Comment by Fabiomad85** [comment]
my solution was to allow xhost from remote with the command "xhost +"
before puppeteer ececution

**Comment by LukePammant** [comment]
I just installed vcxsrv by following this post: https://blog.nimamoh.net/wsl2-and-vcxsrv/

Rather than adding to the `/etc/profile.d/set-display.sh` I added those lines to my ~/.bash_profile and everything is working for me.

**Comment by DeyualSimu** [comment]
I hope that it would be useful to someone.
I had the same problem.
I use Intellij and noticed that I had disabled the system environment variables.

![image](https://user-images.githubusercontent.com/5728287/151719995-438e4a79-5791-4391-89ee-4eabdf25bc6b.png)

When I turned it back on it worked fine again.

**Comment by geommr** [comment]
Was having the same issue running it from a terminal inside vscode on Tumbleweed (not WSL), running directly from terminal (Konsole) worked.

**Comment by marcelo-amorim** [comment]
Got it working following those steps with vcXsrv Windows X Server:

- Install [vcXsrv](https://sourceforge.net/projects/vcxsrv/)
  - Once installed, run the LaunchX shortcut on your desktop.
  - You will have a choice of four viewport options. Let's choose 'Multiple Windows' for now and press Next.
  - “Start no client” and press Next.
  - Change the default options: uncheck NATIVE OPENGL and check the DISABLE ACCESS CONTROL box. That way you won't see permission problems.
  - Before Finalizing, you can save your settings for later adjustments.

You will likely be asked if you want to allow VcXsrv to access your network, you will have to click on the ‘Public network’ option and allow it through Windows Firewall or whatever firewall you use.

Now, I think this is the most important instruction I found in [Stackoverflow](https://stackoverflow.com/questions/61860208/wsl-2-run-graphical-linux-desktop-applications-from-windows-10-bash-shell-erro), in the best answer section:

> The networking subsystem in WSL2 is different than the used in WSL1. You must [consider the differences](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-network-applications) to access networking apps running on Windows and on Linux:

>In WSL1, Linux uses the same IP addresses than the Windows host, then, you can access the applications using localhost or 127.0.0.1
In WSL2, Linux runs on a lightweight virtual machine and has a different IP address. To access networking apps running on the Windows Host you must use the Windows IP address.
Checking the IP address of the Windows host
There are many ways to determine the IP addresses in the Windows host. You may run the following commands in your WSL Linux: [...]

So, the only configuration I had to do in this moment, was setting my local Windows IP with `route.exe print`. To do it, edit your `./bashrc` adding these two lines:

```
export DISPLAY=$(route.exe print | grep 0.0.0.0 | head -1 | awk '{print $4}'):0.0`
export LIBGL_AWAYS_INDIRECT=1
```

After that, try running your Puppeteer script to see if it works. This was the only solution I found in two days, hope it helps someone else.

Best regards,
Marcelo

**Comment by OrKoN** [comment]
To run headful without the display on Linux, you could use `xvfb`. There are probably solutions for other platforms.

**Comment by NoamGit** [comment]
I used this guideline to allow X11 from Mac->Ubuntu. It worked great!
https://www.businessnewsdaily.com/11035-how-to-use-x11-forwarding.html

**Comment by aditodkar** [comment]
> @dundunn Set headless to true :)

This worked for me :)

**Comment by alexrus123** [comment]
> To run headful without the display on Linux, you could use `xvfb`. There are probably solutions for other platforms.

A few steps here to run puppeteer non-headless on ubuntu:

Install and configure `xvfb` after this you should have $DISPLAY set to some value (`:1` or whatever its configured)

`printenv DISPLAY`

and launch puppeteer with 
```
puppeteer.launch({
  headless: false, 
  args: ["--display=<DISPLAY_VALUE>"],
  ...
```

I hope this will help someone.

**Comment by bobitza** [comment]
I haved same problem, the problem was i running command node test.js from ROOT user not adminuser ... strange thing
