### ISSUE TITLE
Experimental Firefox support appears to not work

### ISSUE THREAD

**Issue by foolip** [puppeteer/puppeteer#5437]
The `puppeteer.launch({product: 'firefox'})` pattern does not appear to launch Firefox.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: Debian 5.2.17 (gLinux)
* Node.js version: v10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer =  require('puppeteer');
const products = ['chrome', 'firefox'];

async function main() {
  for (const product of products) {
    const browser = await puppeteer.launch({product});
    const page = await browser.newPage();
    const ua = await page.evaluate('navigator.userAgent');
    console.log(`${product}: ${ua}`);
    await browser.close();
  }
}

main();
```

**What is the expected result?**

Different UA strings for Chrome and Firefox.

**What happens instead?**

It looks like Chrome is launched in both cases, that the `{product: 'firefox'}` option has no effect:

> chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/80.0.3987.0 Safari/537.36
> firefox: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/80.0.3987.0 Safari/537.36

**Comment by pavelfeldman** [comment]
:wave: @foolip. I could make it start via specifying the environment variables that I saw in the announcement tweet. But it failed (F), timed out (T), skipped (*) a bunch of tests until it died (pink dot):

![IMG_20200221_083105_823](https://user-images.githubusercontent.com/883973/75038545-8f9bf380-5484-11ea-9525-abef59789c41.jpg)

@mathiasbynens: is there a way to track the FF support status? Something like [isplaywrightready](https://aslushnikov.github.io/isplaywrightready/) would be handy.

**Comment by mjzffr** [comment]
Ah yeah, you have to specify the `executablePath` for Firefox. That won't be necessary anymore after PR https://github.com/puppeteer/puppeteer/pull/5467 is merged.
