### ISSUE TITLE
puppeteer solve captcha manually

### ISSUE THREAD

**Issue by KrisWu-188** [puppeteer/puppeteer#5439]
I met captcha when using headless mode.I want to capture google reCaptcha separately and solve it manually. I don't want to open the whole page. What should I do?

**Comment by margolisj** [comment]
Look into this plugin: https://www.npmjs.com/package/puppeteer-extra-plugin-recaptcha

**Comment by KrisWu-188** [comment]
@margolisj First of all, thank you very much for your answer. But you seem to understand my problem wrong. My purpose is not to solve it automatically or through captcha service provider. I want to capture the verification code and solve it manually. Is there any good solution?

**Comment by margolisj** [comment]
You'll have to do some research into how gcap works but basically there is a key for each webpage for their gcaptcha service. Take that key, you'll have to spoof their website via hosts spoofing or electron proxys and generate a spoofed captcha page. Solve it, have the call back do something with the answer, and then you'll have the code google uses to mark it as a confirmed answer.  This repo might point you in the right direction: https://github.com/TCWTEAM/Daptcha

**Comment by KrisWu-188** [comment]
@margolisj Thank you for your answer, but it's a little difficult for me. I'm a novice. I don't know how to interpret this library. Is there any example to see? thanks

**Comment by ordimans** [comment]
You mean a simple captcha with some letters after a slide bar ?
I did that, i slide the bar, and get the base64 image, and display in the console, to type (but you can make everything after you get the image).

**Comment by paulogc** [comment]
@KrisWu-188 maybe this article can be helpful for you, unfortunately it involves a payed service:

https://medium.com/@jsoverson/bypassing-captchas-with-headless-chrome-93f294518337
