### ISSUE TITLE
How to run js scripts with puppeteer

### ISSUE THREAD

**Issue by Tynael** [puppeteer/puppeteer#544]
Hey,

I can't seem to manage executing a .js file with `puppeteer`. I'm coming from PhantomJS and CasperJS environment and this shouldn't be a problem for me, but yet it is.

I have installed puppeteer and created a main.js file where I inserted one of your demo code from the documentation.

Now, when I `npm start` I get the following error:
```
C:\Bot\Puppeteer\main.js:3
(async () => {
       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

My folder structure looks like this:
->Bot
  --> node_modules
  --> main.js
  --> package.json

Is the `main.js` file supposed to be located in any other directory other than outside the `node_modules` or do I have to execute it through a chromium .exe?

My Node version is 6.11.2 and I'm running Chrome 60 (if that matters) on Windows 10.

Looking forward to hearing from you and sorry if this looks like a really rookie mistake but I've been struggling for the last couple of hours to execute a .js file with `puppeteer` and didn't succeed and it's kind of frustrating.

Thanks ^_^

**Comment by Garbee** [comment]
Node 6 is only recently supported in the npm build and you need to specifically require that build output iirc. The standard required files are all node 7+.

**Comment by Garbee** [comment]
Also, you need to currently use the bundled chromium build. Stable Chrome doesn't have the proper apis puppeteer requires.

**Comment by Tynael** [comment]
> Also, you need to currently use the bundled chromium build. Stable Chrome doesn't have the proper apis puppeteer requires.

Isn't the recent version of Chromium installed when you install `puppeteer` as it states in the `README.md` file? Why should I use a bundled chromium build?

**Comment by JoelEinbinder** [comment]
You can use node 6 with puppeteer, but all the examples are designed for node 8. You have to use promises instead of async await, or compile your code with Babel.

**Comment by Garbee** [comment]
> Isn't the recent version of Chromium installed when you install puppeteer as it states in the README.md file?

Yes. This is the "bundled" Chromium version.

> Why should I use a bundled chromium build?

I explained with:

> Stable Chrome doesn't have the proper apis puppeteer requires.

**Comment by aslushnikov** [comment]
@Tynael the problem is that node6 doesn't support `async/await`.

You can use the api with promises, e.g. try running the following snippet:
```js
const puppeteer = require('puppeteer');

let browser;
puppeteer.launch()
  .then(b => {
    browser = b;
    return browser.newPage();
  })
  .then(page => page.goto('https://www.google.com'))
  .then(response => {
    console.log('Page loaded with status code: ' + response.status);
    browser.close();
  });
```

**Comment by drmrbrewer** [comment]
@Tynael I'm interested... do you have any examples of executing a .js file with puppeteer?  I can't see anything in the docs... only loading an html page (which itself may execute js)... not running a .js file directly.

**Comment by Garbee** [comment]
@drmrbrewer Browsers don't execute JS when navigated to. They simply show the contents. Scripts are only executed when called into a page. If you just want to run JavaScript, then all you want is a normal node script, puppeteer won't help you there.

**Comment by drmrbrewer** [comment]
@Garbee sure, just checking I'm not missing another possible angle.  So the `main.js` in @Tynael 's post is just a node script, which includes code for invoking puppeteer?  If so, I can rest easy.

**Comment by tnolet** [comment]
@Tynael I cooked up a bunch of examples of running Puppeteer. You could clone this https://github.com/checkly/puppeteer-examples.git repo and follow the instructions. Hope it helps.

**Comment by Tynael** [comment]
Hey guys, this issue was solved a long time ago by installing Node 8.x because in my example I was using Node 6 which doesn't support `async/wait`.

@drmrbrewer you can find example scripts here https://github.com/GoogleChrome/puppeteer/blob/master/README.md and https://github.com/GoogleChrome/puppeteer/tree/master/examples
