### ISSUE TITLE
Puppeteer browserContext.setGeolocation is not working with permission override

### ISSUE THREAD

**Issue by zeroN1** [puppeteer/puppeteer#5442]
Problem: I am trying to emulate different locations using puppeteer while searching on google search. I am using country URLs for google search alongside location changing. This is what I have so far:

### Steps to reproduce

`
                    const ctx = browser.defaultBrowserContext();
                    const u = `${url}search?${makeQuery(kw)}`;
                    const page = await ctx.newPage();
                    await ctx.overridePermissions(url, ['geolocation']);
                    await page.goto(u, PAGE_OPTS);
                    await page.setGeolocation({
                        latitude: lat,
                        longitude: lng,
                        accuracy: 21
                    });
`

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: Opensuse Leap 15.1
* URLs (if applicable): https://google.be/search?q=<KEYWORD>
* Node.js version: 10.16.3

**What is the expected result?**

The page should load and show result from Google search from Belgium. 

**What happens instead?**

Asks for the location access and have to manually give permission for it.

**Comment by zeroN1** [comment]
I have resorted to using a `userDataDir` to save the permission on the initial run. From there onwards it works as expected.

**Comment by YusukeIwaki** [comment]
https://github.com/puppeteer/puppeteer/blob/09fca442f701e09929120e1b8abac8e49495ab2d/test/page.spec.ts#L336-L349

This spec seems to check setGeolocation after overridePermissions.
