### ISSUE TITLE
Set page content with multiple PDF pages

### ISSUE THREAD

**Issue by nyel-gh** [puppeteer/puppeteer#5444]
Is it possible to have multiple PDF pages on a single file?

I am thinking of doing:

```
const page1 = await browser.newPage();
await page1.setContent(html1);

const page2 = await browser.newPage();
await page2.setContent(html2);

const page3 = await browser.newPage();
await page3.setContent(html3);
```

and then print them all in just one single PDF file but with multiple pages?

**Comment by itereshchenkov** [comment]
It's a wrong approach to use `Page` for this case. You can consider Page object as a tab in the browser.
Please use css page-break to split the content into several pages, see https://css-tricks.com/almanac/properties/p/page-break/

**Comment by LordRampantHump** [comment]
@itereshchenkov but what if you want the content from multiple 3rd party pages in one pdf document? I have one for example that is over 800 pages.  As one file with css inline and images base64, it weighs in at 255mb

**Comment by itereshchenkov** [comment]
Yeah, in this case, puppeteer won't help much with combining the pages. You will need to generate pdf for each separate 3rd party page and afterwards put them all into a single document (as a separate process).

**Comment by xiarch-rahul** [comment]
> 

how to merge them in single pdf ?
