### ISSUE TITLE
add visible and exists function

### ISSUE THREAD

**Issue by softwarezhu** [puppeteer/puppeteer#545]
I think it's very common used for test if dom visible or exists. So can you add support for this two function?

**Comment by aslushnikov** [comment]
@softwarezhu: you can use [`page.$`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselector) for the `exists` function:
```js
const exists = !!(await page.$('div.container'));
```

Regarding the "visible" function, what kind of "visible" are you interested in? Is it attached to DOM, doesn't have `opacity: 0`, `display: none` or `visibility: hidden` css attributes, or is not covered with other DOM elements?

**Comment by softwarezhu** [comment]
@aslushnikov Yes, use `page.$` can achieve this, but have an "exists" function can be more friendly.  For "visible" function, it's enough for those attached to DOM, doesn't have opacity: 0, display: none and visibility: hidden css attributes.

**Comment by aslushnikov** [comment]
@softwarezhu We'll add the API if there are enough clients for it. I close this for now and will re-open once similar request surfaces in the bugtracker.

Meanwhile you can use the following snippet to check for the visibility of the dom element:
```js
const isVisible = await page.evaluate(() => {
  const e = document.querySelector('my-selector');
  if (!e)
    return false;
  const style = window.getComputedStyle(node);
  return style && style.display !== 'none' && style.visibility !== 'hidden' && style.opacity !== '0';
});
```

**Comment by softwarezhu** [comment]
@aslushnikov OK, thank you!

**Comment by sean-hill** [comment]
@aslushnikov I would like this API as well. Thanks!

**Comment by jamesmartinduffy** [comment]
I'd say that this is a common enough use case that it makes sense to include in the API.

`if (await page.exists(selector)) // do something` 

is a lot clearer than

`if (!!(await page.$(selector))) // do something`

**Comment by robertpallas** [comment]
@aslushnikov I would also love to have `.visible()`. Using it from Phatnom/Horseman scraping stack quite extensively. 

What would be the best way to extend puppeteer and have shorthand functions? Besides `.visible(string)` I would create and use `.waitFor(string[])` for waiting any of the elements to appear for cases where Error or Success may appear and quick `.click()` + `.type()` shortcut.

**Comment by aslushnikov** [comment]
@robertpallas  Although this is a little bit of a hack, you can require puppeteer classes and amend their prototypes:

```js
const Page = require('puppeteer/lib/Page');
Page.prototype.visible = ...
```

IF you want to publish your work as an npm module, it should be done as a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) to pptr

**Comment by ChristianDavis** [comment]
I think the few features in #967 cover most cases without having to think around the API

**Comment by dilipkumar2k6** [comment]
What is equivalent of `document.querySelector('my-selector')` for xpath?

**Comment by radhouen** [comment]
@dilipkumar2k6 
just use this code `page.$(my-selector)` to get one element or use this `page.$$('selector')`  that return all element have this selector

**Comment by sean-hill** [comment]
@aslushnikov were these features ever implemented? I can't seem to find any resolution here or any mention of it in the docs.

**Comment by AkA84** [comment]
+1

**Comment by ursulaclarke** [comment]
+1

**Comment by urban235** [comment]
+1

**Comment by aslushnikov** [comment]
> were these features ever implemented? I can't seem to find any resolution here or any mention of it in the docs.

@sean-hill for the `.exists`, you can just use the `page.$`:
```js
const exists = !!(await page.$('.foo'));
```

You can wait for the element to become visible using [`page.waitForSelector`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectorselector-options) together with  `visible` option.

There's nothing like `.visible` in the API; however, there's a [snippet](https://github.com/GoogleChrome/puppeteer/issues/545#issuecomment-325212388) you can use.

**Comment by ratkorle** [comment]
Hey guys I see you already have this discussion. I am wondering if you can help me to return only visible elements by given selector, not all of them. Here is my code:
1.First I am trying to assign it:
` await page.waitForSelector(actions.params.selector, {visible: true});
                     basicSelectorPath = actions.params.selector;
                     basicSelector = await page.$$(basicSelectorPath);` 
2.Then I would like to loop through all the elements with the same selector but I get error because some of them are hidden.
`for (let i = 0; i < basicSelector.length; i++) {
                                let resultObject = [];
                                let basicIndex = basicSelector[i];
                                for (let k = 0; k < otherSelectorsPath.length; k++) {
                                    let otherSelector = otherSelectorsPath[k];
                                    let otherSelectorText = await basicIndex.$eval(otherSelector, text => text.innerText);
                                    resultObject.push(otherSelectorText);
                                }
                                result.push({resultObject});
                            }`
I would be really happy if you can help me passing the right filter.
I tried:

> 

> `basicSelector = await page.$$eval(basicSelectorPath, style => {
           return style && style.display !== 'none' && style.visibility !== 'hidden' && style.opacity !== '0';
       });`

**Comment by Hypnosphi** [comment]
> what kind of "visible" are you interested in?

I want exactly the same logic that's used in `waitForSelector`

**Comment by GerryOnGithub** [comment]
has page.$ changed? it doesn't work anymore, it never ever returns null

**Comment by prantlf** [comment]
It is not clear what you mean by "visible". If you mean the general visibility somewhere the page, just the style of the element is not enough. You need to check, that the element is not hidden, because its containing ancestor is hidden. You can use the code used in the [jQuery pseudo-selector `:visible`](https://github.com/jquery/jquery/blob/3.4.1/src/css/hiddenVisibleSelectors.js#L12):

```js
function isElementVisible (page, selector) {
  return page.evaluate(selector => {
    const element = document.querySelector(selector)
    return !!(element && (element.offsetWidth || element.offsetHeight ||
      element.getClientRects().length))
  }, selector)
}
```

**Comment by hakunin** [comment]
Following up on the last message, you can also do this more elegantly I think with:
```
link.boundingBox() // returns null if non-visible
```

**Comment by debyauto** [comment]
> Following up on the last message, you can also do this more elegantly I think with:
> 
> ```
> element.boundingBox() // returns null if non-visible
> ```

This is what I'm looking for an elegant way to check visible elements exist! thank you!
Implement example:

```
const isVisibleElementExist = await page.$(`button[id="bidSearchForm:btnBidSearch"]`)
  ?.then((elementHandle) =>
    elementHandle?.boundingBox(),
  )
  ?.catch(() => false)
```
