### ISSUE TITLE
page.setRequestInterceptionEnabled(true) prevents page from fully loading all components

### ISSUE THREAD

**Issue by jhgeluk** [puppeteer/puppeteer#5452]
### Steps to reproduce

1. Create a page
2. Set request interception to true
3. Goto https://google.com/maps/search/google **with waitUntil: 'networkidle0'**
4. Place listing on the left hand side is not visible.

**Tell us about your environment:**

* Puppeteer version: **2.1.1**
* Platform / OS version: **MacOS Catalina (10.15.3)**
* URLs (if applicable): **https://google.com/maps/search/google**
* Node.js version: **v12.9.0**

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `const page = await this.browser.newPage();`
2. `await page.setRequestInterception(true);`
`page.on('request', (req) => {
req.continue();
 });`
3. `page.goto('https://google.com/maps/search/google');
`

**What is the expected result?**
To see the found listings/places on the left sidebar (open link in your own browser if you want to see what I mean)

**What happens instead?**
Left sidebar does not load when I use page.setRequestInterception(true);

**Comment by Bloodsucker** [comment]
Does anybody have any idea about this issue or how to solve it?
