### ISSUE TITLE
page.pdf result is different from printing to "save to PDF" in browser manually

### ISSUE THREAD

**Issue by Chimneytop** [puppeteer/puppeteer#5457]
As you can see from bellowing pictures, the result from puppeteer is different from expected. it can get the above fraction number printed correctly, but failed for the one bellow it. I tried emulate print or screen media, no help.
It is really weird, in the end, both operations should call the same piece of "pdf printing" code, why the results are different.
To walk around it, I would like to call browser print from Puppeteer, but seems browser printing is not exposed to Puppeteer.

from Printing to "save as PDF" manually 
![image](https://user-images.githubusercontent.com/4537302/75323461-e9028900-58af-11ea-8bf0-facdf4ca9a27.png)

from Puppeteer page.pdf()
![image](https://user-images.githubusercontent.com/4537302/75323522-0df6fc00-58b0-11ea-9a72-bb9a90b48059.png)

**Comment by Chimneytop** [comment]
because page.pdf only works in headless mode, so the discrepancy may resulted from inconsistent renderings of headless and headful modes.

**Comment by Chimneytop** [comment]
in headless screenshot, it is correct. so it is page.pdf is not working correctly.

**Comment by rawbin-** [comment]
![image](https://user-images.githubusercontent.com/8169783/77751502-d02cf500-7060-11ea-9bbf-7c79fade2756.png)

same problem
