### ISSUE TITLE
Need page.waitForColorInput

### ISSUE THREAD

**Issue by mmakrzem** [puppeteer/puppeteer#5460]
I have a color picker `<input type='color'></input>` on my page that I want to test with puppeteer, however when I click the input element, an OS native dialog pops up and I am unable to select a color or press ok using puppeteer.

The same problem was true for the file open dialog, but that has recently been fixed by adding a page.waitForFileChooser api https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-pagewaitforfilechooseroptions

I propose that a new api get created called page.waitForColorInput that would act in the same way as the FileChooser.

**Comment by calixteman** [comment]
@OrKoN could you reopen this issue ? or explain why you don't want to fix it and potentially provide a workaround.
Thank you.

**Comment by OrKoN** [comment]
It's not a priority for us right now and the workaround is to use evaluate() or locator().fill() that would fallback to the evaluate for non-typeable inputs. We are unlikely to support dialog interception for this.
