### ISSUE TITLE
Property 'waitForFileChooser' does not exist on type 'Page'.

### ISSUE THREAD

**Issue by prashantj93** [puppeteer/puppeteer#5462]
### Steps to reproduce
* Puppeteer version: 2.1.0

To trigger file choosing, I was using the following piece of code. However I am getting Property 'waitForFileChooser' does not exist on type 'Page'.

const [fileChooser] = await Promise.all([
  **page.waitForFileChooser(),**
  page.click('#upload-file-button'), // some button that triggers file selection
]);

**Comment by paullewis** [comment]
It's not possible to know what the issue is here, just because we don't have enough code to look at, but this snippet should work.

```
const puppeteer = require('../puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('about:blank');
  await page.setContent('<input type="file">');

  // Set up the Promise here *before* clicking on the input element.
  const chooser = page.waitForFileChooser();
  page.click('input');

  // Now await the chooser.
  const element = await chooser;
  console.log(element);
  await browser.close();
})();
```

Going to close because `waitForFileChooser` does exist.

**Comment by leegee** [comment]
The [official docs](https://pptr.dev/api/puppeteer.filechooser) mention the method that is above said to not exist?

![image](https://user-images.githubusercontent.com/512816/224673573-a36ad2ba-a1a4-4594-8646-bcadd7a54fa8.png)
