### ISSUE TITLE
Unstable behavior if system goes to sleep

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5463]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: OSX 10.15.2
* Node.js version: v12.14.0

**What steps will reproduce the problem?**
Putting system to sleep and then trying to resume run gives a lot of bugs:
Details here: https://gist.github.com/VikramTiwari/8aea5e523a4380a5bfd28fe12ebcf64d

**What is the expected result?**
Things should keep working after system wakes up

**What happens instead?**
Lots of bugs related to connectivity.

**Comment by jackfranklin** [comment]
I don't think this is something we're going to tackle I'm afraid, you could probably deal with this in your own code by detecting errors and re-starting Puppeteer, but this isn't something we're likely to support in the library any time soon.
