### ISSUE TITLE
Module not found: Error: Can't resolve 'ws'

### ISSUE THREAD

**Issue by Toso82** [puppeteer/puppeteer#5464]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: v13.9.0

**What steps will reproduce the problem?**

-  ng new test
-  cd test
- npm install puppeteer

_Please include code that reproduces the issue._

```typescript

import * as puppeteer from 'puppeteer';

 GeneraPdf() {
    (async () => {
      const browser = await puppeteer.launch();
      const page = await browser.newPage();
      await page.goto('https://google.com');
      await page.pdf({path: 'hn.pdf', format: 'A4'});
    
      await browser.close();
    })();
  }

```

**What is the expected result?**

Compile

**What happens instead?**

```powershell
PS C:\Users\Giacomo\Documents\Progetti\Angular\Testpuppeteer> ng serve

chunk {main} main.js, main.js.map (main) 13.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 10.1 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.75 MB [initial] [rendered]
Date: 2020-02-28T11:06:47.573Z - Hash: fed516f7933ffc2f9d0a - Time: 5671ms

ERROR in ./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Error: Can't resolve 'ws' in 'C:\Users\X\Documents\Progetti\Angular\Testpuppeteer\node_modules\puppeteer\lib'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

```

**Comment by goldpot** [comment]
Did you resolve this? I am getting the same! Pls help

**Comment by hengkx** [comment]
+1

**Comment by mjyg** [comment]
+1

**Comment by nesymno** [comment]
+1

**Comment by christian-bromann** [comment]
@Toso82 you can't bundle Puppeteer to run it in the browser. It requires primitives that are not compatible with a browser environment.

**Comment by mathiasbynens** [comment]
Note that `puppeteer-core` serves this use case (e.g. for Chrome extensions): https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core But yes, it requires special access to a CDP connection, so it doesn't make sense for general web app usage.

**Comment by navarrojandg** [comment]
So i was able to fix this issue by installing puppeteer-core and then in my webpack config adding

```
externals: {
  'puppeteer-core': 'require("puppeteer-core")'
}
```

so you would need to pass in the chrome executable path in order for launch / connect to work now

**Comment by hadi112** [comment]
Hi @navarrojandg  can you please elaborate that. Thank you

**Comment by pourya-zln** [comment]
> 

Works for me!
thanks man
