### ISSUE TITLE
test error in headless mode

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#5465]
` import login from '../mock/auth.json'

const timeout = 100000;
jest.setTimeout(timeout);

describe("Login functionality test", () => {

    beforeEach(async () => {
        await jestPuppeteer.resetBrowser();
        await page.setRequestInterception(true);

        page.on('request', request => {
          if (request.url() === "http://localhost:4000/api/user/login") {

            console.log(`REQUESTXXXXXXXXXX ${request.url()}`);
            request.respond({
                content: 'application/json',
                headers: {"Access-Control-Allow-Origin": "*"},
                body: JSON.stringify(login.successLoginMock)
            });

            // request.continue(); // for second screenshoot
        }
          else {
              request.continue();
          }
        });
        page.on('response', response => {
            if (response.url() === "http://localhost:4000/api/user/login") {
                response.text().then(value =>{
                    console.log(`RESPONSEXXXXXXXXXX ${value}`);
                })

            }
        });
        await page.goto(URL, { waitUntil: "domcontentloaded" });
    });

    test("enter dashboarad with right credentials test", async () => {
        await expect(page).toClick('[data-cy="login"]');
        await page.waitForSelector('[data-cy="forgetPassword"]');
        await expect(page.url()).toEqual("http://localhost:8080/login");

        await expect(page).toFillForm('[data-cy="loginForm"]', {
            username: 'mik',
            password: '1',
        });
        await expect(page).toClick('[data-cy="loginButton"]');
        await page.waitForSelector('[data-cy="profile"]',{timeout:30000});
    }, timeout);
});`

I used jest-puppeteer to configure jest and puppeteer. If i run above code with two different configuration {headless: true} and  {headless: false}. The test fail with first configuration because of reponse value is empty. i share two screenshot of console.
![screenshot1](https://user-images.githubusercontent.com/57099954/75548797-29dcd800-5a3f-11ea-9630-155f9049fa01.png)
![screenshot2](https://user-images.githubusercontent.com/57099954/75548814-2fd2b900-5a3f-11ea-8997-ddaa4de9189b.png)

how can i handle this situation in headless browser.

**Comment by rjdestigter** [comment]
I'm running into the same issue. Intercepting requests doesn't seem to work in headless:true mode:

```js
// script.js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: true, timeout: 60000});
  const page = await browser.newPage();

  const onRequest = async (interceptedRequest) => {
    const url = interceptedRequest.url();
    console.log('Intercept', url)
    if (/jsonplaceholder/.test(url)) {
      return interceptedRequest.respond({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({username: "tommy"})      
      });
    }

    return interceptedRequest.continue();
  }
  
  await page.goto('http://localhost:8081/index.html');
  await page.setRequestInterception(true);
  await page.on('request', onRequest)
  await page.click('#btn')
  await page.waitFor('[data-username="tommy"]')
  console.log("Done!")
})();
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div id="root"></div>
  <button id="btn">Go</button>
  <script>
    function run() {
      fetch('https://jsonplaceholder.typicode.com/users/1')
         .then(response => response.json()).then(json => {
        const el = document.getElementById('root')
        el.setAttribute('data-username', json.username)
      })
    }

    document.getElementById('btn').addEventListener('click', run)
  </script>
</body>
</html>
```

**Comment by rjdestigter** [comment]
After some painstaking debugging I found out it was a CORS issue. 🤕

**Comment by rjdestigter** [comment]
Adding
```ts
headers: {
    'Access-Control-Allow-Origin':  '*'
},
```
to my mocked response resolve it for me.

**Comment by ghost** [comment]
headless browser make an options request before making actual request. I found this issue by adding a piece of code to my mocking code. It is `&& request.method()!=="OPTIONS"`. Full code is below. @rjdestigter is right. This is CORS issue. But the peace of code doesn't solve my issue. Thanks for helping.
`page.on('request', request => {
            if (request.url() === "http://localhost:4000/api/user/login" &&
                request.method()!=="OPTIONS") {
                    // console.log(`TRUEXXXXXXXXXX ${request.url()}`);
                    request.respond({
                        status:200,
                        content: 'application/json',
                        headers: {"Access-Control-Allow-Origin": "*"},
                        body: JSON.stringify(login.successLoginMock)
                    });
                } `
