### ISSUE TITLE
 Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by thebetterjort** [puppeteer/puppeteer#5468]
```
puppeteer.launch().then(async function(browser) {
  const browse = await puppeteer.launch({ headless: true, ignoreHTTPSErrors: true, args: ['--disable-dev-shm-usage', '--no-sandbox'] });
```

```
 (node:31) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
leave-api    | [0228/235000.062941:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
leave-api    | #0 0x7fa211191879 base::debug::CollectStackTrace()
leave-api    | #1 0x7fa2110eec63 base::debug::StackTrace::StackTrace()
leave-api    | #2 0x7fa211103013 logging::LogMessage::~LogMessage()
leave-api    | #3 0x7fa21289d95e service_manager::ZygoteHostImpl::Init()
leave-api    | #4 0x7fa210d32adc content::ContentMainRunnerImpl::Initialize()
leave-api    | #5 0x7fa210d7e72c service_manager::Main()
leave-api    | #6 0x7fa210d310b1 content::ContentMain()
leave-api    | #7 0x7fa210d7d99d headless::(anonymous namespace)::RunContentMain()
leave-api    | #8 0x7fa210d7d70b headless::HeadlessShellMain()
leave-api    | #9 0x7fa20eb0e1b8 ChromeMain
leave-api    | #10 0x7fa205a452e1 __libc_start_main
leave-api    | #11 0x7fa20eb0e02a _start
leave-api    | 
leave-api    | Received signal 6
leave-api    | #0 0x7fa211191879 base::debug::CollectStackTrace()
leave-api    | #1 0x7fa2110eec63 base::debug::StackTrace::StackTrace()
leave-api    | #2 0x7fa211191401 base::debug::(anonymous namespace)::StackDumpSignalHandler()
leave-api    | #3 0x7fa20bbd40e0 <unknown>
leave-api    | #4 0x7fa205a57fff gsignal
leave-api    | #5 0x7fa205a5942a abort
leave-api    | #6 0x7fa211190265 base::debug::BreakDebugger()
leave-api    | #7 0x7fa211103461 logging::LogMessage::~LogMessage()
leave-api    | #8 0x7fa21289d95e service_manager::ZygoteHostImpl::Init()
leave-api    | #9 0x7fa210d32adc content::ContentMainRunnerImpl::Initialize()
leave-api    | #10 0x7fa210d7e72c service_manager::Main()
leave-api    | #11 0x7fa210d310b1 content::ContentMain()
leave-api    | #12 0x7fa210d7d99d headless::(anonymous namespace)::RunContentMain()
leave-api    | #13 0x7fa210d7d70b headless::HeadlessShellMain()
leave-api    | #14 0x7fa20eb0e1b8 ChromeMain
leave-api    | #15 0x7fa205a452e1 __libc_start_main
leave-api    | #16 0x7fa20eb0e02a _start
leave-api    |   r8: 0000000000000000  r9: 00007fffaef06650 r10: 0000000000000008 r11: 0000000000000246
leave-api    |  r12: 00007fffaef07908 r13: 00007fffaef068e8 r14: 00007fffaef068e8 r15: 00007fffaef06900
leave-api    |   di: 0000000000000002  si: 00007fffaef06650  bp: 00007fffaef06890  bx: 0000000000000006
leave-api    |   dx: 0000000000000000  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007fffaef066c8
leave-api    |   ip: 00007fa205a57fff efl: 0000000000000246 cgf: 0000000000000033 erf: 0000000000000000
leave-api    |  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
leave-api    | [end of stack trace]
leave-api    | Calling _exit(1). Core file will not be generated.
leave-api    | 
leave-api    | 
leave-api    | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
leave-api    | 
leave-api    |     at onClose (/home/node/app/node_modules/puppeteer/lib/Launcher.js:348:14)
leave-api    |     at Interface.helper.addEventListener (/home/node/app/node_modules/puppeteer/lib/Launcher.js:337:50)
leave-api    |     at Interface.emit (events.js:203:15)
leave-api    |     at Interface.close (readline.js:397:8)
leave-api    |     at Socket.onend (readline.js:173:10)
leave-api    |     at Socket.emit (events.js:203:15)
leave-api    |     at endReadableNT (_stream_readable.js:1145:12)
leave-api    |     at process._tickCallback (internal/process/next_tick.js:63:19)
leave-api    | (node:31) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
leave-api    | (node:31) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Dockerfile

```
FROM node:10-slim

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update 
RUN apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# If running Docker >= 1.13.0 use docker run's --init arg to reap zombie processes, otherwise
# uncomment the following lines to have `dumb-init` as PID 1
ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64  /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init

# Uncomment to skip the chromium download when installing puppeteer. If you do,
# you'll need to launch puppeteer with:
#     browser.launch({executablePath: 'google-chrome-unstable'})
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Install puppeteer so it's available in the container.
RUN yarn config set strict-ssl false
WORKDIR /home/node/app

RUN adduser node root
COPY . /home/node/app
RUN npm install puppeteer --unsafe-perm=true \
    && mkdir -p /home/node/app/public \
    && mkdir -p /home/node/app/forms \
    && mkdir -p /home/node/app/json \
    && chown -R node:root /home/node/app \
    && chmod -R 755 /home/node/app \
    && chown -R node:root /usr/local/lib/node_modules \
    && mkdir -p /usr/local/lib/node_modules \
    && mkdir -p /home/node/app/node_modules/ \
	&& chown node:root /home/node/app/node_modules/
    # RUN mkdir -p /home/node/app/public/json \
    # && mkdir -p /home/node/app/public/images \
    #     && mkdir -p /home/node/app/public/forms




#RUN npm -g config set user root

RUN npm config set strict-ssl false \
    && npm install -g json-server --unsafe-perm=true \
	&& npm install -g nodemon
RUN  npm i -ddd
COPY package.json package.json
RUN npm i

# Run everything after as non-privileged user.
USER node
#RUN groupmod -g 500 node && usermod -u 500 node





EXPOSE 7000
USER 1000
ENTRYPOINT ["dumb-init", "--"]
CMD ["npm", "run", "start"]

```

**Comment by imsalahdev** [comment]
headless should be `false`.
```js
puppeteer.launch().then(async function (browser) {
        const browse = await puppeteer.launch({ headless: false, ignoreHTTPSErrors: true, args: ['--disable-dev-shm-usage', '--no-sandbox'] });
    });
```

**Comment by kirill-kostenetskyi** [comment]
The same for me

**Comment by laosandegudai** [comment]
Yes,The same problem to me,But  i searched  a litttle useful words,
Dockerfile
`# First, we need to make sure all dependencies are there. If you are using docker, then the important dependencies are already present on most node images. 
FROM node:8

# To run Headful mode, you will need to have a display, which is not present in a server. 
# To avoid this, we will use Xvfb, and create a fake display, so the chrome will think there is a display and run properly. 
# So we just need to install Xvfb and Puppeteer related dependencies.
RUN apt-get update && apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget x11vnc x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps xvfb

# I am going to ignore dumb-init or such for now since it will add complexities to understand what is actually needed here. 

# Assuming we are working on /app folder, cd into /app
WORKDIR /app

# Copy package.json into app folder
COPY package.json /app

# Install dependencies
RUN npm install 

COPY . /app

# Start server on port 3000
EXPOSE 3000

# I'll also assume you are going to use root user, 
# and your script has `--no-sandbox` and `--disable-setuid-sandbox` arguments.
# We run a fake display and run our script.
# Start script on Xvfb
CMD xvfb-run --server-args="-screen 0 1024x768x24" npm start`

**Comment by laosandegudai** [comment]
I found a new blog.
[http://www.smartjava.org/content/using-puppeteer-in-docker/](url)

**Comment by imjeen** [comment]
**Is there any way to launch the host chrome by puppeteer  in docker ?**

By default, we could  set some params to launch the PC chrome ( anywhere we want):
```
launch({
   headless: false,
   executablePath: '<chrome_path>',
})
```
Then the code was running in docker,  and how dose it  launch the host  chrome? 

If it can launch host chrome, It will be  convenient to develop something useful.

**Comment by laosandegudai** [comment]
> **Is there any way to launch the host chrome by puppeteer in docker ?**
> 
> By default, we could set some params to launch the PC chrome ( anywhere we want):
> 
> ```
> launch({
>    headless: false,
>    executablePath: '<chrome_path>',
> })
> ```
> 
> Then the code was running in docker, and how dose it launch the host chrome?
> 
> If it can launch host chrome, It will be convenient to develop something useful.

You can see it.
[Puppeteer in Docker](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker)

**Comment by imjeen** [comment]
> Puppeteer in Docker

I know this. But I mean that It shouldn't install chrome in docker. I want to launch the chrome of host in docker.

**Comment by laosandegudai** [comment]
> > Puppeteer in Docker
> 
> I know this. But I mean that It shouldn't install chrome in docker. I want to launch the chrome of host in docker.

yes,you can also do it.

**Comment by impressto** [comment]
Here is what worked for me.  

In docker I added the following to the Docker file

`
RUN apt-get update && \
  apt-get install -y libgtk2.0-0 libgtk-3-0 libnotify-dev \
  libgconf-2-4 libnss3 libxss1 \
  libasound2 libxtst6 xauth xvfb \
  libgbm-dev`


In my call to puppeteer I added the argument --no-sandbox 

I am using Ubuntu 20 but this should work with any distro.

**Comment by Savita-pds** [comment]
Puppeteer in Docker Issue
Please help on this,
We have used below Docker file config :
FROM node:12-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

RUN mkdir -p /home/node/pdfFiles

RUN mkdir -p /home/node/uploads
WORKDIR /home/node/app

RUN chmod -R 777 /home/node/pdfFiles

COPY package*.json ./

USER node

RUN npm install

RUN npm install concurrently

RUN npm install chrome-aws-lambda

COPY --chown=node:node . .

EXPOSE 8019

CMD [ "npm", "run", "dev" ]


once we deploy application, when we run application its showing below error:
[1] error:- Error: Failed to launch the browser process! spawn /home/node/app/node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome ENOENT

Please help on this

[Dockerfile.txt](https://github.com/puppeteer/puppeteer/files/5422672/Dockerfile.txt)
