### ISSUE TITLE
Headers in Response/Request object are case sensitive

### ISSUE THREAD

**Issue by rolftimmermans** [puppeteer/puppeteer#547]
I am attempting to get the content-type of HTTP responses.

My code looks approximately like this:

```
page.on("response", response => {
  const contentType = response.headers.get("Content-Type")
})
```

Unfortunately the `response.headers` `Map` is case sensitive, so this only works if the header name is `Content-Type` (as opposed to, say, `content-type`).

I think all headers need to be lower cased before setting them in the map, or there needs to be an alternative API to retrieve headers.

The current API requires code to iterate over all headers just to normalise the case.

**Comment by Janpot** [comment]
@aslushnikov Did you consider using an interface like `Headers` in the Fetch API?
https://developer.mozilla.org/en-US/docs/Web/API/Headers
Also, I didn't fully review your solution, but did you consider that there are headers that can be defined more than once (`set-cookie`)?

**Comment by aslushnikov** [comment]
@Janpot we tried implementing Fetch API, but it turned out we can't implement match of the `Request`/`Response` interfaces. See #106

**Comment by Janpot** [comment]
yep, I figured. I'm just wondering because I've been bitten bitten more than once by naive header API implementations. There's just two cases that are always easily overlooked. first, header names are case insensitive. second, header names can appear more than once.
