### ISSUE TITLE
cannot get iframe element in youtube page

### ISSUE THREAD

**Issue by dinggewennuan** [puppeteer/puppeteer#5471]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version:  macOS High Sierra 10.13.6
* URLs (if applicable): https://www.youtube.com/channel/UC-3fLOkTRb7-tepOqxsDdDg/about
* Node.js version:8.11.4

**What steps will reproduce the problem?**
i want got email in this page,but when i clicked VIEW EMAIL ADDRESS ，the page insert a new iframe,but i can got it used every ways

![image](https://user-images.githubusercontent.com/20785023/75695385-f1f6be80-5ce4-11ea-9c90-0d986edd27d8.png)

![image](https://user-images.githubusercontent.com/20785023/75695933-c1fbeb00-5ce5-11ea-8265-0e59c17a5f9f.png)

_Please include code that reproduces the issue._

1.
2.
3.
`async function test2 () {
    const browser = await puppeteer.launch({
        headless: false,
        devtools: true,
        defaultViewport: {
            height: 1024,
            width: 1280
        }
    })

    const page = await browser.newPage();

    await page.goto('https://www.youtube.com/channel/UC-3fLOkTRb7-tepOqxsDdDg/about', {
        timeout: 0,
        waitUntil: 'networkidle0'
    })
    try {        
         await page.click('#details-container > table > tbody > tr:nth-child(1) > td:nth-child(2) > ytd-button-renderer > a')

        let iframes = await page.frames()
        // console.log("iframe  ", iframes)
        // await page.waitForSelector("#recaptcha-anchor")
        // await page.waitForSelector('#captcha-container iframe');
        // await page.waitForSelector('#captcha-container > form > button'
        let iframe = await page.frames().find(f => f.name())
       // cannot got everything
        for (const frame of page.mainFrame().childFrames()) {
            console.log("url is", frame.url(), frame.title())
            console.log("-------name------",frame.name())
        }
        
        await page.close();
        await browser.close();
        console.log("end--------------")
    } catch (error) {
        console.log("error is ", error)
    }
}`
**What is the expected result?**
i hope got  the final email 
![image](https://user-images.githubusercontent.com/20785023/75696160-18692980-5ce6-11ea-9c4b-11acc1280b52.png)

**What happens instead?**

**Comment by devjerry** [comment]
check out #4960
