### ISSUE TITLE
chromium launch fails w/ segmentation fault on Windows 10

### ISSUE THREAD

**Issue by diminutivesloop** [puppeteer/puppeteer#5478]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.2.1
* Platform / OS version: Windows 10
* Node.js version: 10.16.3

**What steps will reproduce the problem?**

1. Run [example.js script](https://github.com/puppeteer/puppeteer#usage) from project README.

**What is the expected result?**
The script should run without error.

**What happens instead?**
The following error is output to the console:
```
(node:15812) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (G:\projects\puppeteer-test\node_modules\puppeteer\lib\Launcher.js:750:14)
    at ChildProcess.helper.addEventListener (G:\projects\puppeteer-test\node_modules\puppeteer\lib\Launcher.js:740:61)
    at ChildProcess.emit (events.js:203:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
(node:15812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This appears to be caused by a bug in the Chromium version currently shipping with Puppeteer (722234). When I try to launch Chromium via `./node_modules/puppeteer/.local-chromium/win64-722234/chrome-win/chrome.exe` it fails to launch with the error message `Segmentation fault`. However if I directly install the latest version of Chromium (746903) I can launch it without any error.

**Comment by hanselfmu** [comment]
We will roll a newer version of Chromium (81) next week: #5493 , and I hope at that time your issue can be solved.
