### ISSUE TITLE
how can I  break Interception when I get response

### ISSUE THREAD

**Issue by younghunjung** [puppeteer/puppeteer#5480]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 
* Platform / OS version:
* URLs (if applicable):
* Node.js version: 13.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.  
        await page.setRequestInterception(true);

        page.on('request', interceptedRequest => {
             var data = {
                 'method' : 'POST',
                 'postData' : datas,
                 'headers' : { 'accept' : "application/json, text/javascript, */*; q=0.01", 'Content-Type' : "application/x-www-form-urlencoded", 'cache-control' : "no-cache", 'User-Agent' :'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'}
             };
             interceptedRequest.continue(data);
         });
        
        const response = await page.goto( url );
        const responseBody = await response.text();
       
        var temp = JSON.parse(responseBody);
        console.log(temp.orderCheckoutUrl.requestUrl);  // i wanna go but  it cant . bcuz intercepted
       
       		
        await page.goto(temp.orderCheckoutUrl.requestUrl, 300);
2.
3.

**What is the expected result?**
I want to page.goto( response url ) 

**What happens instead?**
url added   interception

**Comment by brutalzinn** [comment]
I'm with same problem. Are you already solved this issue?

**Comment by brutalzinn** [comment]
Hello, i discover the method on github issues.  [`Click here to go to github issue problem with this related issue`](https://github.com/puppeteer/puppeteer/issues/669#issuecomment-644891165)
