### ISSUE TITLE
How to run in headful mode, but keep browser minimized?

### ISSUE THREAD

**Issue by ecolss** [puppeteer/puppeteer#5484]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@2.0.0
* Platform / OS version: MacOS Catalina, 10.15.3 (19D76)
* URLs (if applicable): 
* Node.js version: v12.13.0

**What steps will reproduce the problem?**
I launched browser with following settings,
```
headless: false,
args: [
                '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
                '--disable-background-timer-throttling',
                '--disable-backgrounding-occluded-windows',
                '--disable-renderer-backgrounding',
            ]
```
**What is the expected result?**
The browser will run quietly, without jumping to the foreground.

**What happens instead?**
Whenever a page is opened, the browser jumps out to the foreground, which hinders me from doing other things on my computer.

**Comment by assopri** [comment]
did you solve it? I have the same issue https://github.com/puppeteer/puppeteer/issues/6606

**Comment by wangjue666** [comment]
@2milesaway @assopri hi,  I found the solution under windows system

1. Press "Win + R" to open the "run" window, enter the "regedit" command and press enter to open the registry;
2. Find HKEY_CURRENT_USER/Control Panel/Desktop/ForegroundLockTimeout
3. Change this value to any 6 digits or more in hexadecimal (the system defaults to 200000 milliseconds / hexadecimal 30d40)
4. If not, please create a new one;
5. After completion, exit the registry and **restart the computer** for the following settings to take effect.
6. **don't minimize the pop-up browser， Just overlay**
