### ISSUE TITLE
puppeteer-firefox pdf suppprt

### ISSUE THREAD

**Issue by Guidanz-Kishore** [puppeteer/puppeteer#5486]
Hi all,

When will the support for pdf will be released for puppeteer-firefox? Is it under the development process?

**Comment by mjzffr** [comment]
See https://github.com/puppeteer/puppeteer/issues/5397 -- the `puppeteer-firefox` npm package is not being worked on.

PDF support works in puppeteer + Firefox Nightly, but you need to provide your own executable path for Firefox Nightly until puppeteer v3 is released.
