### ISSUE TITLE
Request `continue` url doesn't do anything when you add a query param.

### ISSUE THREAD

**Issue by Georgegriff** [puppeteer/puppeteer#5488]
### Steps to reproduce
Intercept a request, as in the docs
![image](https://user-images.githubusercontent.com/9056958/76222671-d161c380-6212-11ea-9f31-3b4c014f39d9.png)
instead do this:
```
interceptedRequest.continue({
   url: `interceptedRequest.url()?myParam=${foo}`
});
```

I'm finding that `myParam` is not getting to the server. If i change the whole url that changes take effect.

**Tell us about your environment:**

* Puppeteer version: 2.1.0
* Platform / OS version: MAC OC
* URLs (if applicable):
* Node.js version: 12.X

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Follow example above

**What is the expected result?**
Query parameter should be silently added to the request, but it does not appear to be

**What happens instead?**
Request continues without additional query param

**Comment by dpmott** [comment]
You'd need to interpolate the URL as well:

```
interceptedRequest.continue({
   url: `${interceptedRequest.url()}?myParam=${foo}`
});
```
