### ISSUE TITLE
It´s possible use chrome of a different machine?

### ISSUE THREAD

**Issue by ruballos** [puppeteer/puppeteer#5495]
I want to create a service that lauch automatically the chrome of a user of my service and run some actions automatically....Can I use a executablePath with the IP of the PC that is consuming the service?

Some like this:

```
`let launchOptions = { headless: false, 
                                        executablePath: http://192.168.1.1/google-chrome-stable };

    const browser = await puppeteer.launch(launchOptions);`
```

**Comment by jackfranklin** [comment]
I don't believe we can support this, I'm afraid.
