### ISSUE TITLE
Upload Photo Instagram  Evaluation failed: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by brkrtp** [puppeteer/puppeteer#5503]
```
"dependencies": {
    "fs": "0.0.1-security",
    "path": "^0.12.7",
    "puppeteer": "^2.1.1"
 }
* Node.js version: v10.16.3
```

I'm trying to upload photo to instagram. I maked mobile screen with page.emulate(...);
And ı saw the mobile screen, ı can login with my account then i click plus icon (to add photo on browser)
with this code everythinks good until this line then crashed.
```
  let filePath = path.relative(process.cwd(), __dirname + '/test.jpg');
 const [fileChooser] = await Promise.all([
         page.waitForFileChooser(),
         page.click('div[data-testid=new-post-button]'), // INSTAGRAM PLUS BUTTON
      ]);
    await page.waitFor(1000);
       console.log("ok")
    await fileChooser.accept([filePath]); <--- CRASH THİS LİNE
```

<img width="546" alt="Screen Shot 2020-03-13 at 1 30 07 AM" src="https://user-images.githubusercontent.com/18514716/76572162-5a565480-64ca-11ea-8cbb-517283e13700.png">

```

(node:15845) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Failed to fetch
    at __puppeteer_evaluation_script__:4:32
    at ExecutionContext._evaluateInternal (/Users/bk/Desktop/bot/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/bk/Desktop/bot/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluateHandle (/Users/bk/Desktop/bot/node_modules/puppeteer/lib/JSHandle.js:63:42)
    at ElementHandle.<anonymous> (/Users/bk/Desktop/bot/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.uploadFile (/Users/bk/Desktop/bot/node_modules/puppeteer/lib/JSHandle.js:335:16)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/bk/Desktop/bot/node_modules/puppeteer/lib/helper.js:111:15)
    at main (/Users/bk/Desktop/bot/index.js:66:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15845) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15845) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by koresar** [comment]
I have identical error.
Node v12. Puppeteer v2.1.1

**Comment by koresar** [comment]
Just tried with Puppeteer 2.0.0. Exception is not thrown. 
This looks like a regression in v2.1.

**Comment by jacobmesu** [comment]
I have the same error here. Downgrade to 2.0.0 fixed it.

**Comment by DevMai90** [comment]
The same issue occurs when using `elementHandle.uploadFile(...filePaths)` 

I've been having the same issue and spent half the day trying to debug. Downgraded to Puppeteer 2.0.0 and now it works. Hopefully we can come up with a patched solution soon.

**Comment by brianbraunstein** [comment]
Same problem with elementHandle.uploadFile(), same workaround worked, downgrade to 2.0.0.

**Comment by pranavanrao** [comment]
same problem I was facing and I downgraded my puppeteer virsion to 2.0.0 and I have succeded to post. 
I have done the automation of twitter.... automatic login and file upload on twitter... 
https://github.com/pranavanrao/Automate/blob/master/tweet.js

**Comment by paullewis** [comment]
This should be fixed as of 532ae573d29063ffd081ed9ee340d71b25320dec as we changed the underlying implementation to use `DOM.setFileInputFiles`, which behaves a lot more as expected.  The previous implementation used Data URLs, which are likely to be blocked by CSP. Going to close this issue, but please let us know if it's not fixed.

**Comment by koresar** [comment]
Paul, which version will be fixed in?
Something like 3.1?

**Comment by paullewis** [comment]
I defer to @mathiasbynens on that, but I'm sure it'll make the next release.

**Comment by Anatoly-IVANOV** [comment]
Same here. Downgraded from 3.0.0 to 2.0.0 and solved the:

`TypeError: Failed to fetch at __puppeteer_evaluation_script__:4:40
`

while doing an  `await elementHandle.uploadFile()`.

Looking forward to @mathiasbynens answer regarding the release schedule, bitte. :)

**Comment by ShimonADMIN** [comment]
I have the same problem, I have the latest puppeteer version 
PLEASE HELP

**Comment by koresar** [comment]
@paullewis could your please reopen this issue? It was not fixed yet.

**Comment by paullewis** [comment]
Reopening as it seems this is persisting. @mathiasbynens I don't know that I will be able to look at this in the near future. Is the someone else who might be able to?

**Comment by mathiasbynens** [comment]
The screenshot in OP includes data URLs, which Puppeteer no longer uses since Paul's fix.

Those of you who are still experiencing this issue: please post a reduced test case we can use to reproduce the problem. Thanks!

**Comment by koresar** [comment]
@mathiasbynens it's quite trivial to reproduce. Just try uploading a file using the above mentioned API. 

https://pptr.dev/#?product=Puppeteer&version=v2.1.1&show=api-elementhandleuploadfilefilepaths

The API simply doesn't work.

**Comment by mathiasbynens** [comment]
@koresar You're linking to the v2.1.1 docs which is an old version. Please provide a JS test case that shows the breakage on the latest Puppeteer (v5.2.1).

**Comment by Beenyaa** [comment]
Hey I am also having a similar issue, also on instagram.

**Error msg:**
```
(node:1279) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'executionContext' of null
    at Page._onFileChooser (/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:211:37)
    at /home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:179:61
    at /home/pi/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/home/pi/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:43)
    at CDPSession.emit (/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:225:18)
    at Connection._onMessage (/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:101:25)
    at WebSocket.<anonymous> (/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WebSocketTransport.js:13:32)
    at WebSocket.onMessage (/home/pi/node_modules/ws/lib/event-target.js:125:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Environment:**
* Puppeteer version: 5.2.1
* Platform / OS version: Raspberry Pi 4 / Raspbian
* Node.js version: v14.6.0

**Code:**
```
const [fileChooser] = await Promise.all([
            page.waitForFileChooser(),
            page.tap('div > svg[aria-label="New Post"]'),
            await page.waitFor(1000) //just a pause
        ])

await fileChooser.accept([__dirname+`/../images/${selectedPicture}`]);
```

**EDIT:**
I made the script on my Mac where the script works fine with the same Puppeteer and Node.js version, but I am intending to deploy it on my Pi.

**Comment by galangel** [comment]
Still an issue

Puppeteer version: 5.4.0
node v12.16.0

**Comment by ghost** [comment]
This issue still exists.. 
I am using puppeteer version 5.5.0 and node v14.15.4.

**Comment by jacobmesu** [comment]
I'd recommend switching to Microsoft/Playwright. Almost the same api and the lead developers moved to Playwright as well.

**Comment by jrandolf-google** [comment]
Please try on the latest version of Puppeteer.
