### ISSUE TITLE
can't find iframe

### ISSUE THREAD

**Issue by fulfree** [puppeteer/puppeteer#5506]
* Puppeteer version: 2.1.1
* Platform / OS version: macOS High Sierra
* URLs (if applicable): https://login.1688.com/member/signin.htm?from=sm&Done=http://detail.1688.com/offer/597301351517.html
* Node.js version: 12.14.0

I am trying to get the login form in the iframe of this page, https://login.1688.com/member/signin.htm?from=sm&Done=http://detail.1688.com/offer/597301351517.html

```
<div id="loginchina">
--
  | <div class="china-signin-title">
  | </div>
  | <iframe width="412" scrolling="no" height="400" frameborder="no" border="0" allowtransparency="true" src="https://login.taobao.com/member/login.jhtml?style=b2b&amp;css_style=b2b&amp;from=b2b&amp;newMini2=true&amp;full_redirect=true&amp;redirect_url=https%3A%2F%2Flogin.1688.com%2Fmember%2Fjump.htm%3Ftarget%3Dhttps%253A%252F%252Flogin.1688.com%252Fmember%252FmarketSigninJump.htm%253FDone%253Dhttp%25253A%25252F%25252Fmember.1688.com%25252Fmember%25252Foperations%25252Fmember_operations_jump_engine.htm%25253Ftracelog%25253Dlogin%252526operSceneId%25253Dafter_pass_from_taobao_new%252526defaultTarget%25253Dhttp%2525253A%2525252F%2525252Fwork.1688.com%2525252F%2525253Ftracelog%2525253Dlogin_target_is_blank_1688&amp;reg=http%3A%2F%2Fmember.1688.com%2Fmember%2Fjoin%2Fenterprise_join.htm%3Flead%3Dhttp%253A%252F%252Fmember.1688.com%252Fmember%252Foperations%252Fmember_operations_jump_engine.htm%253Ftracelog%253Dlogin%2526operSceneId%253Dafter_pass_from_taobao_new%2526defaultTarget%253Dhttp%25253A%25252F%25252Fwork.1688.com%25252F%25253Ftracelog%25253Dlogin_target_is_blank_1688%26leadUrl%3Dhttp%253A%252F%252Fmember.1688.com%252Fmember%252Foperations%252Fmember_operations_jump_engine.htm%253Ftracelog%253Dlogin%2526operSceneId%253Dafter_pass_from_taobao_new%2526defaultTarget%253Dhttp%25253A%25252F%25252Fwork.1688.com%25252F%25253Ftracelog%25253Dlogin_target_is_blank_1688%26tracelog%3Dlogin_s_reg"></iframe>
  | </div>
```

tried this codes, all can't find the iframe in the page.
`await page.frames().find(frame => !!~frame.url().search("login.taobao"))`

`const iframeCount = await page.frames().length`
this always equals 1, only the main frame. so I can't try
`await page.frames()[1]`

and I tried the get it iframe elementHandle, and refer to the contentFrame
`let iframeHandle = await page.$('iframe')`
this step is correct, can find the selector successfully, but the next step comes null
`let iframe = iframeHandle. contentFrame()`

can anyone help?
thank you

**Comment by tolmasky** [comment]
Try:

```javascript
page.mainFrame().childFrames().find(frame => frame.url().includes("login.taobao"))
```

**Comment by stuartchris** [comment]
Child frames can also be referenced by their index, for example '[0]' returns the first child frame:
`const frame = await page.mainFrame().childFrames()[0];`
For second frame use '[1]', third frame use '[2]', etc.
