### ISSUE TITLE
Upload file doesn't work because website's CSP declines data urls

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5507]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: macOS
* URLs (if applicable): hire.lever.co/candidates (not public)
* Node.js version: 12.16.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Try to upload a file using elementHandle.uploadFile
2. It loads the file internally as a data URL before uploading the file
3. Look at the website's console log where we see the CSP error

![983029b6-b249-4e09-ba2d-32f6aa0a5163](https://user-images.githubusercontent.com/1330677/76650919-c6fc3e00-6520-11ea-9b23-d39d32a53b49.png)

**What is the expected result?**
File gets uploaded properly and is not blocked by CSP

I think this might be outside the scope of puppeteer team but I was wondering if there are ways to get around this. Thanks!

**Comment by VikramTiwari** [comment]
For folks coming to this, you can use [DOM.setFileInputFiles](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-setFileInputFiles) as a possible strategy. Though I would like to see puppeteer support that through it's methods rather than converting the file to data URL.

**Comment by mathiasbynens** [comment]
We could essentially revert 6091a34a360b0b8aec4d67f6190f131d7e8e3300 and continue to use `DOM.setFileInputFiles` like before. The other CDP changes w.r.t. file uploads did not need the changes in 6091a34a360b0b8aec4d67f6190f131d7e8e3300 after all.

**Comment by VikramTiwari** [comment]
I think that would be a good idea. A lot of issues have happened since that I think can be attributed to this change.

Also, I understand the commit message but I am unable to understand where is that case applicable. Was this causing issues when doing i18n input fields or something similar?

**Comment by VikramTiwari** [comment]
I am also very curious to understand why [page.setBypassCSP](https://github.com/puppeteer/puppeteer/blob/v2.1.1/docs/api.md#pagesetbypasscspenabled) didn't work for this.

**Comment by sivasait-opex** [comment]
@VikramTiwari how to use **DOM.setFileInputFiles** ? can you please help me in that. am having issues in upload folder only in headless mode. it works fine in non headless mode

**Comment by VikramTiwari** [comment]
Hey @sivasait-opex Here's a sample for using CDP for animations. https://github.com/puppeteer/puppeteer/blob/v2.1.1/docs/api.md#class-cdpsession

**Comment by sivasait-opex** [comment]
@VikramTiwari am using like this.

 const client = await this.page.target().createCDPSession();
      const objectId = element._remoteObject.objectId;
      console.log(objectId);
      await this.screenshot();
      await client.send('DOM.setFileInputFiles', {
        objectId,
        files
      });

The log prints **{"injectedScriptId":13,"id":16}** as **objectId**
I pass the same objectId to 'DOM.setFileInputFiles' 
but it throws error 

{ Error: Protocol error (DOM.setFileInputFiles): Could not find object with given id
        at Promise (/Users/sivasaithota/Documents/enframe_puppeteer/node_modules/puppeteer/lib/Connection.js:183:56)
        at new Promise (<anonymous>)
        at CDPSession.send (/Users/sivasaithota/Documents/enframe_puppeteer/node_modules/puppeteer/lib/Connection.js:182:12)
        at Browser.uploadFile (/Users/sivasaithota/Documents/enframe_puppeteer/autoframe/wrapper/browser.js:452:20)
      message:
       'Protocol error (DOM.setFileInputFiles): Could not find object with given id' }

any suggestions?

**Comment by VikramTiwari** [comment]
Sorry, the error is pretty self explanatory. You should be able to figure out more from the error message.

**Comment by mathiasbynens** [comment]
#5654

**Comment by paullewis** [comment]
This should be fixed as of 532ae573d29063ffd081ed9ee340d71b25320dec since we use `DOM.setFileInputFiles` internally again.
