### ISSUE TITLE
Possible to get PDF page number of a certain element?

### ISSUE THREAD

**Issue by gylaz** [puppeteer/puppeteer#5508]
I have a need to know what page an element ends up on in a PDF. This is to implement a Table of Contents with page numbers.

I figure since Puppeteer prints the number of the page, it might be possible to get that number for a given element (let's say with a unique HTML id). I couldn't find anyone doing anything like this already, but maybe there is some internal of undocumented way of getting the page number.

**Comment by Mattwmaster58** [comment]
As far as I can tell, no. The `Page.pdf()` method sends the `Page.printToPDF` command to the browser and returns the bytes. This means there is no way to get the page number of certain element without scraping the PDF.
