### ISSUE TITLE
WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by vikimaf** [puppeteer/puppeteer#5512]
STEP 1: Are you in the right place?

* Puppeteer version: 2.0.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: Docker node:13-slim

![image](https://user-images.githubusercontent.com/49949779/76700309-44fa4980-66c7-11ea-8d5c-99e701799aba.png)

code init brouser

```
            page.on('request', (request) => {
                if (['image', 'font'].indexOf(request.resourceType()) !== -1) {
//at Page.<anonymous> (/home/puppeteer/app/dist/lib/PrepareBrowser.js:52:33)
                    request.abort(); //i think on this line i get error 

                    return;
                }

                request.continue();
            });
```

**Comment by DaYesahh** [comment]
I have the same problem all the time. Have you finshed it?
