### ISSUE TITLE
Remove minimist dependency

### ISSUE THREAD

**Issue by comame** [puppeteer/puppeteer#5513]
### Steps to reproduce

* Puppeteer version: 2.1.1

**What steps will reproduce the problem?**

`minimist` has vulnerabilitiy [GHSA-7fhm-mqm4-2wp7](https://github.com/advisories/GHSA-7fhm-mqm4-2wp7). This is required via `extract-zip` and `mkdirp`.

**What is the expected result?**
Remove  `extract-zip` dependency. `extract-zip` is not updated since 2018.

**Comment by styfle** [comment]
Consider using [yauzl](https://www.npmjs.com/package/yauzl) and `fs.mkdir` with the `recursive` flag instead of `mkdirp`.

**Comment by styfle** [comment]
It looks like the latest version of `extract-zip` did just that, and it no longer depends on `mkdirp`.

https://github.com/maxogden/extract-zip/pull/89

Should I submit a PR to bump to `extract-zip@2.0.0`?

**Comment by comame** [comment]
@styfle 
Please make a PR. Thank you!

**Comment by styfle** [comment]
Looks like @TimvdLippe already did in PR #5610
