### ISSUE TITLE
Refresh ispuppeteerfirefoxready dashboard

### ISSUE THREAD

**Issue by digitarald** [puppeteer/puppeteer#5515]
*(Follow up from [Firefox's Remote meeting 2020-03-11](https://wiki.mozilla.org/Remote/Meetings/2020/03/11))*

We need to update our status communication of how compatible Firefox is with Puppeteer. Developers need to be able to tell which Puppeteer classes/methods are 1. supported now, 2. coming soon, and 3. not planned. 

**What to show?** The source of the [legacy dashboard](https://github.com/aslushnikov/ispuppeteerfirefoxready) was the Puppeteer test suite. Passing tests are a better status indicator than Firefox's remote protocol [MVP bug list](https://bugzilla.mozilla.org/show_bug.cgi?id=1545057) as they reflect the API that developers actually use.

@jgraham updated Puppeteer's Firefox tests to run as *Tier 2* ([not sheriff-managed](https://wiki.mozilla.org/Sheriffing/Job_Visibility_Policy#Overview_of_the_Job_Visibility_Tiers)) in treeherder. Failed tests are not being removed, in contrast to Puppeteer's own CI, which makes Firefox's tests-results the more accurate source. Test results are recorded in [remote/puppeteer-expected.json](https://hg.mozilla.org/mozilla-central/file/tip/remote/puppeteer-expected.json).

@jgraham offered to help with infrastructure and hooking up the test results. The dashboard should be hosted in the [puppeteer org](https://github.com/puppeteer) to be easily bootstrapped and updated by the existing contributors.

**Comment by mathiasbynens** [comment]
Would you like me to create (and give y’all access to) a new `puppeteer/ispuppeteerfirefoxready` repository, or would it be somehow easier to transfer the old one first (it sounds like it wouldn’t be)?

**Comment by digitarald** [comment]
That would help, thanks @mathiasbynens. Is there anything else that you believe the dashboard should track?

I have not spent much time thinking about implementation but it does make sense to start from @aslushnikov's dashboard (without the test runner) and switch over the data source. I don't want to reinvent the wheel for building the frontend.

**Comment by mathiasbynens** [comment]
@aslushnikov Would you be willing to transfer the repository to the puppeteer org? That way, any links to the old repo would nicely get redirected to the new one.

**Comment by mathiasbynens** [comment]
Alrighty then, in that case I'll set up a new repository instead: https://github.com/puppeteer/ispuppeteerfirefoxready @mjzffr @jgraham @digitarald I gave y'all access.

**Comment by aslushnikov** [comment]
Hey all, sorry for the long reply - missed it.

> Would you be willing to transfer the repository to the puppeteer org? That way, any links to the old repo would nicely get redirected to the new one.

@mathiasbynens I didn't know github page URL will get redirected. Is is the case?

**Comment by whimboo** [comment]
Shall we close this issue given that we have our own repository now?

**Comment by mathiasbynens** [comment]
@aslushnikov GitHub Pages-hosted content indeed won't get redirected, but we could change the HTML as follows:

```
<!DOCTYPE html>
<link rel="canonical" href="https://puppeteer.github.io/ispuppeteerfirefoxready/">
<meta http-equiv=refresh content="0;URL=https://puppeteer.github.io/ispuppeteerfirefoxready/">
```

Then we could also clear out the repository and leave a link in its README pointing to <https://github.com/puppeteer/ispuppeteerfirefoxready>. Would you be willing to take care of that please?

**Comment by aslushnikov** [comment]
> GitHub Pages-hosted content indeed won't get redirected, but we could change the HTML as follows

So if I understand correctly, the repository should stay where it is for this plan to work. Feel free to send a PR!

**Comment by mathiasbynens** [comment]
> Feel free to send a PR!

Actually, could you just give me admin rights to the repo? That way I can take care of everything without having to bother you all the time. Thanks!

**Comment by whimboo** [comment]
The dashboard has its own repository, so I think that we can close this out.
