### ISSUE TITLE
when i set headless=true i cannot get anything in centos7,but  headless=false can get it

### ISSUE THREAD

**Issue by dinggewennuan** [puppeteer/puppeteer#5521]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: centos7
* URLs (if applicable): https://www.youtube.com/channel/UCht8qITGkBvXKsR1Byln-wA/featured
* Node.js version: 8.11.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
when i set headless:true,i cannot get anything in centos7 ,i dont know why ?
const puppeteer = require('puppeteer')
try {
  (async () => {
    const browser = await puppeteer.launch({ args: ['--no-sandbox'], headless: true })
    const page = await browser.newPage()
    await page.goto('https://www.youtube.com/channel/UCht8qITGkBvXKsR1Byln-wA/featured')
    await page.waitFor(10000)
    await page.screenshot({ path: './xxxxxx.png' })
    await browser.close()
  })()
} catch (err) {
  console.error(err)
}
result like this
![image](https://user-images.githubusercontent.com/20785023/76987344-f924fa00-697d-11ea-85d7-379ecc74000a.png)

but when i test macos and set headless:false i can get data,so when i set headless:true,i also need set anything ? 

**What is the expected result?**
i want to get data like this,can someone help me?
![image](https://user-images.githubusercontent.com/20785023/76987112-9c294400-697d-11ea-9eea-b4bb0a64edc7.png)

**What happens instead?**

**Comment by pixelmund** [comment]
@dinggewennuan 
Same happens for me i dont know why

**Comment by pansj66** [comment]
Was defended, did anyone solve it

**Comment by dinggewennuan** [comment]
> @dinggewennuan
> Same happens for me i dont know why

use

**Comment by sunmasters** [comment]
Set wait for element and user agent.
