### ISSUE TITLE
Unable to upload folder in headless mode but works fine in non headless 

### ISSUE THREAD

**Issue by sivasait-opex** [puppeteer/puppeteer#5525]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:2.0.0
* Platform / OS version: 
* URLs (if applicable):
* Node.js version: 10.16.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. async uploadFile(element, path) {
    try {
      await element.uploadFile(path)
    } catch (error) {
      console.log(error)
    }
  }
2.
3.

**What is the expected result?**

it should upload folder. 
**What happens instead?**
it is not uploading folder. no error is thrown. tried adding logs,screenshot. everything works fine. no errors but folder is not getting uploaded in headless mode. This works perfectly fine in non headless mode

**Comment by sivasait-opex** [comment]
any updates on this?

**Comment by paullewis** [comment]
Can you try updating Puppeteer to master for me? `npm install https://github.com/puppeteer/puppeteer` and see if it is fixed for you?

**Comment by sivasait-opex** [comment]
@paullewis tried with the latest release . But that didn't help. Please let me know if you need more details on this. This is a blocker for me since months. Please help

**Comment by jrandolf-google** [comment]
Can't reproduce.
