### ISSUE TITLE
newPage() hangs in headless mode with incorrect DISPLAY environtment variable

### ISSUE THREAD

**Issue by saschanaz** [puppeteer/puppeteer#5528]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: Windows 10 19041 WSL Ubuntu
* URLs (if applicable):
* Node.js version: 13.11.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Set the `DISPLAY` environment to `example.com:0`.
2. Use the following code:

```js
const puppeteer = require("puppeteer");
const browser = await puppeteer.launch({ headless: true });
await browser.newPage();
```

**What is the expected result?**

Headless mode shouldn't depend on `DISPLAY` environment variable.

**What happens instead?**

`await newPage()` waits until the remote opens X server. (Hangs forever in this case.)

**Comment by jsanonymousfunction** [comment]
Likely a chromium issue
