### ISSUE TITLE
puppeteer spider nike web failure

### ISSUE THREAD

**Issue by gongxh13** [puppeteer/puppeteer#5529]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: lastest
* Platform / OS version: windows 10
* URLs (if applicable):https://www.nike.com/kr/launch/
* Node.js version: lastest

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.When I use puppeteer crawl nike web's products, the first page is succeed, but the next page will failure,  I want to know how to aviod the detect?
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by Mattwmaster58** [comment]
It's likely Nike rate limiting/limiting you in general for bot like behaviour. Try launching in headed mode to see what is going on.
