### ISSUE TITLE
case of "networkidle"

### ISSUE THREAD

**Issue by myakura** [puppeteer/puppeteer#553]
This is merely a question after spending about a minute figuring out the error I got.

Why the `networkidle` value which `waitUntil` takes is all lowercase while there are members (e.g.  `networkIdleTimeout`) whose case are lower camelcase?

**Comment by aslushnikov** [comment]
Indeed. Would you mind sending a PR to address this?

**Comment by myakura** [comment]
@aslushnikov sure!
looking at the [source code regarding `waitUntil`](https://github.com/GoogleChrome/puppeteer/blob/1f9b4fb4c8/lib/NavigatorWatcher.js#L20-L75), it appears the all-lowercase `networkidle` isn't quite used (used only in assertion).

so I guess we could just replace the value with one in lower camelcase. or do you want to keep supporting the all-lowercase value?

**Comment by aslushnikov** [comment]
@myakura I got confused, there's no need for PR.

>Why the networkidle value which waitUntil takes is all lowercase while there are members (e.g. networkIdleTimeout) whose case are lower camelcase?

The convention is that all string literals in API are in small caps.
For example:
- event names: `'requestfinished'`, `'requestfailed'`, ...
- options values: `'load'`, `'raf'`, `'networkidle'`, ...

**Comment by myakura** [comment]
@aslushnikov ah, got that. sorry for the noise!
