### ISSUE TITLE
Yo - which one of the Puppeteer Contributors wants to make some money?

### ISSUE THREAD

**Issue by daddydrac** [puppeteer/puppeteer#5534]
I could really careless because im not a tetser or a front end dev, I just need my spec to work in this stupid container, and I am really frustrated with your ecosystem.

How about I just pay someone for some peer coding to get this container running to my spec over google hangout for 2-3hrs? (I have Venmo and PayPal) 

FYI: puppeteer doesn’t work in containers

**Comment by joehoeller** [comment]
@benatkin ?

**Comment by joehoeller** [comment]
@jeresig @benatkin @slaskis @neerajdotname plz advise on how you’d like to proceed, I just want a working Docker container.

**Comment by corford** [comment]
@joehoeller This should contain enough hints to get you going: https://hub.docker.com/r/browserless/chrome/dockerfile

**Comment by daddydrac** [comment]
Don’t complain that open source doesn’t make money then.
