### ISSUE TITLE
UnhandledPromiseRejectionWarning running simple script (Chromium is working)

### ISSUE THREAD

**Issue by xl-tech** [puppeteer/puppeteer#5538]
Hello! 
I have simple script to save page to pdf:
```
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
    headless: true,
    ignoreHTTPSErrors: true,
    slowMo: 250
    args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--no-first-run',
        '--disable-gpu'
    ]
    });
  const page = await browser.newPage();
  await page.goto('https://www.example.org', {waitUntil: 'networkidle2'});

  await page.pdf({path: '/scrape/page1.pdf', format: 'A4'});

  browser.close();
```

Starting today I got 

> DEBUG=* /usr/local/bin/node page1.js
  puppeteer:launcher Calling /scrape/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-setuid-sandbox --no-first-run --disable-gpu --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-l9hBct +0ms
(node:3681) UnhandledPromiseRejectionWarning: #<ErrorEvent>
(node:3681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Nothing is changed on machine, no auto updates etc. 
I tried to update node and re download puppeteer, but got same error.
Chromium is working if I run it outside puppeteer.

In debug it stopping after first step, what else can I check? 

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version:  Ubuntu 18.04.4 LTS
* URLs (if applicable):
* Node.js version: v12.16.1.

**What steps will reproduce the problem?**
Cannot reproduce on another machine

**Comment by xl-tech** [comment]
Got it solved, it was wrong iptables rule

**Comment by dvxdxm** [comment]
**> (node:3681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)**

how to fixed  error this?
