### ISSUE TITLE
Sometimes the function page. Waitforxpath() does not detect the DOM that already exists

### ISSUE THREAD

**Issue by aixinalei** [puppeteer/puppeteer#5539]
I use puppeter to collect a website，I'll loop collect a lot of pages。
It was normal at the beginning，After collecting many pages of data，the function page.waitforxpath() does not detect the DOM that already exists.and throw error, such as:TimeoutError: waiting for XPath "//table[@class="hq_table"]/tbody/tr[position()>1]" failed: timeout 3000ms exceeded

i don't know how to deal it. It affected the speed of acquisition

**Comment by jnd0** [comment]
Same here I think it is the same issue that happened here: https://github.com/puppeteer/puppeteer/issues/4072 

The behaviour I'm having (my browser is always running in the background, I don't close it on each request):
- The first page works just fine
- The second try fails on waitForXPath() timing out
- Third page works 
- 4th fails, etc...

**Comment by SpamapS** [comment]
Seems unlikely that this is #4072 given that the issue was closed by devs a long, long time ago.  We saw this today, where a page presumably got faster, leading to the DOM being loaded sooner, and thusly, the waitForXpath never returns despite the xPath matching the existing content.

**Comment by dev-point-team** [comment]
same problem here 
( waitFor() % 2) == Timeout()

**Comment by LiamKarlMitchell** [comment]
I think I'm having the same issue, it's been quite a while since it was reported, any idea on a work around?

Seems to work in non headless mode.
```js
await browser.newPage({ context: 'context-' + Math.floor(Math.random() * 10000) })
```

**Comment by FishBlanche** [comment]
same problems here
i am using the latest version 15.4.0,but the problem is still there

**Comment by OrKoN** [comment]
Could someone provide a repro script?

**Comment by FishBlanche** [comment]
> I use puppeter to collect a website，I'll loop collect a lot of pages。 It was normal at the beginning，After collecting many pages of data，the function page.waitforxpath() does not detect the DOM that already exists.and throw error, such as:TimeoutError: waiting for XPath "//table[@Class="hq_table"]/tbody/tr[position()>1]" failed: timeout 3000ms exceeded
> 
> i don't know how to deal it. It affected the speed of acquisition

Have u fix this? I have same problem here (version 19.6.3)

**Comment by FishBlanche** [comment]
> 

what 's this workaround based on?

**Comment by SwapnilSoni1999** [comment]
Any fixes on this?
