### ISSUE TITLE
I can't get iframe and click element in iframe

### ISSUE THREAD

**Issue by tlqiao** [puppeteer/puppeteer#5540]
I found a tested website(https://codepen.io/bi11johnston/pen/bsGDf), the "select file" element is in iframe. I try to use below two ways to get iframe, but I can't get the iframe. could you please help to find the reason?
**first way to get the iframe**
await page.goto("https://codepen.io/bi11johnston/pen/bsGDf");
        await baseTest.sleep(10000);
        const iframe = await page.frames().find(f => f.name() === 'CodePen');
        await iframe.waitForSelector('.fileupload.fileupload-new');
        await iframe.click('div.fileupload.fileupload-new');
it will display error "Cannot read property 'waitForSelector' of undefined"

**I also try to get the iframe with below way, it also return error.**
const elementHandle = await page.$('iframe[name="CodePen"]');
        await console.log("this is log1"+elementHandle);
        const iframe = await elementHandle.contentFrame();

Thanks in advance.

**Comment by malithlk** [comment]
I'm getting a similar error and I think both are due to the same reason

code:
 const myframe = page.frames().find(frame => frame.name() === 'tool_content');
  await myframe.click('//span[contains(.,"Access now")]');

error:
TypeError: Cannot read property 'click' of undefined

any idea on this ?

**Comment by malithlk** [comment]
adding below tag into launch options fixed the issue for me:
    args: ['--disable-features=site-per-process']
  
@tlqiao please try this.

**Comment by tlqiao** [comment]
thanks, it works for me.
