### ISSUE TITLE
Can't acces the extension config file with error: err_blocked_by_client 

### ISSUE THREAD

**Issue by akaBilih** [puppeteer/puppeteer#5544]
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: Windows 10 Pro
* URLs (if applicable): chrome-extension://hapgiopokcmcnjmakciaeaocceodcjdn/options/main.html
* Node.js version: 12.16.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Create the following script
```
const puppeteer = require('puppeteer-extra');
const browser = await puppeteer.launch(chromeOptions);

const chromeOptions = {
    headless:false, 
    slowMo:5,
    defaultViewport: null,
    args:[
        "--start-maximized",
        '--disable-extensions-except=C:\\Users\\Biel\\Desktop\\Feina\\Fiverr\\cahernanolmo\\Recaptcha Solver',
        "--load-extension=C:\\Users\\Biel\\Desktop\\Feina\\Fiverr\\cahernanolmo\\Recaptcha Solver"
    ]
  };

(async function main() {

    const page = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) 
    AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1')

    await page.goto("chrome-extension://hapgiopokcmcnjmakciaeaocceodcjdn/options/main.html");
})
```
2.Execute it

**What is the expected result?**
That I enter the configuration page of the extension and I'm able to interact with it

**What happens instead?**
I get the err_blocked_by_client error

**Comment by bhanuone** [comment]
@akaBilih Were you ever able to solve this issue?

**Comment by akaBilih** [comment]
sadly, no :(
