### ISSUE TITLE
Choosing a value from drop down is not working with shadow root 

### ISSUE THREAD

**Issue by alpriya87** [puppeteer/puppeteer#5550]
My project uses shadow root, i'm trying to choose a drop down from the list available but, the result is not chosen. 

* Puppeteer version:2.1.1
* Platform / OS version: Mac
* Node.js version: 6.12.0

Drop down of shadow root. Here is the screen shot for the same:
 
<img width="738" alt="Screen Shot 2020-03-27 at 3 39 55 PM" src="https://user-images.githubusercontent.com/60447297/77798635-4b7eae80-7041-11ea-9d31-a84020308eac.png">

_Please include code that reproduces the issue._
Below is the complete js path: 
document.querySelector("body > portal-web").shadowRoot.querySelector("#sink > details-web").shadowRoot.querySelector("#release-status").shadowRoot.querySelector("#ink-select > option:nth-child(3)")

I used the below code :

const a = await this.page.evaluateHandle(() => {
       querySelectorShadowDom.querySelectorDeep("#ink-select option:nth-child(3)").selected=true;
    });

I tried other ways like using the example of click in the below git location: 
https://github.com/Georgegriff/query-selector-shadow-dom/blob/master/examples/puppeteer/clicking-elements.js

**What is the expected result?**

The drop down is not chosen, am i having this specific issue. Drop down option should be pretty simple. 
Since page.select cannot be used with shadow root. I'm having hard time choosing a drop down programmatically with puppeteer. Is there something that i'm missing ?

**Comment by alpriya87** [comment]
To be more clear the click is not happening, hence result is not displayed. 
When we do manually drop down is choosen and immediately results are displayed based on the option choosen. However, this code chooses the drop down but the click is not happening hence results are not displayed. Manually clicking on the drop down work and results are displayed. 

const a = await this.page.evaluateHandle(() => {
querySelectorShadowDom.querySelectorDeep("#ink-select option:nth-child(3)").selected=true;
});

**Comment by UsmanGhani-Emumba** [comment]
how did you solve the issue?

**Comment by UsmanGhani-Emumba** [comment]
I solved this issue by doing this:

 let selectorElement = page.evaluteHandle(()=>{
        return document?.querySelector() // your shadow path locator
}
let dropDown = selectorElement.asElement()
dropDown.select(value) 
)
