### ISSUE TITLE
abort requests inside an iframe

### ISSUE THREAD

**Issue by leem32** [puppeteer/puppeteer#5553]
I need to abort images and media/video requests inside iframes.
This is not for a specific iframe I need to abort the requests in every iframe.

The purpose of this is to remove adult content in some ads found inside iframes on mostly adult websites such as redtube.com and pornhub.com and then display the resulting screenshot.,

This is what I need to do inside iframes:

```javascript

  if (request.resourceType() == 'media' ||
      url.indexOf('.mp4') !== -1 ||
      url.indexOf('.avi') !== -1 ||
      url.indexOf('.flv') !== -1 ||
      url.indexOf('.mov') !== -1 ||
      url.indexOf('.wmv') !== -1) {
             request.abort();
   }

  if (request.resourceType() == 'image' && url.indexOf('.png') === -1 && url.indexOf('.svg') === -1 {
     request.abort();
  }

```

So, the question is how can I abort image and media requests inside all iframes?
If this is not possible, any ideas for an alternative to not displaying images and video inside iframes?

Note: I've tried to use adblockers such as "puppeteer-extra-plugin-adblocker", but it doesn't work for these types of ads in iframes.

Thanks :)

**Comment by gravi2** [comment]
@leem32 Did you get over this issue? Or any way you were able to block all iframes?
