### ISSUE TITLE
page.on('load') getting fired multiple times for a page

### ISSUE THREAD

**Issue by vaibhavtripathi** [puppeteer/puppeteer#5565]
* Puppeteer version: puppeteer-core@2.1.1
* Platform / OS version: MacOS Mojave
* Node.js version: v12.16.1

I tried to set up load event handler on page like this:
```
    const setupPageInstrumentation = function(page) {
        page.on('load', function() {
            logger.log(createLoadEvent(page))
        });
    }
    browser.on('targetchanged', function(target) {
        if (target.type() === "page") {
            target.page().then(function(page) {
                   setupPageInstrumentation(page);
             })
        }
    });
```

**What is the expected result?**
I should be able to see one load event per page.

**What happens instead?**
I am seeing two load events fired in quick succession.

Attaching the logs here:
1585666104612	{"eventType":"load","timestamp":1585666104612,"pageURL":"https://www.bing.com/covid/local/india"}
1585666109399	{"eventType":"load","timestamp":1585666109399,"pageURL":"https://www.covid19india.org/"}
1585666109400	{"eventType":"load","timestamp":1585666109400,"pageURL":"https://www.covid19india.org/"}

**Comment by iori2882** [comment]
Borrow your topic  ask, do you know how to turn off this load monitoring? When I confirm that no load monitoring is required, if it is still executed, it will cause the following error:Cannot set headers after they are sent to the client
