### ISSUE TITLE
The response.text() hangs with some requests

### ISSUE THREAD

**Issue by sarajaksa** [puppeteer/puppeteer#5567]
When parsing the body of some responses, the code hangs and stops executing. While I can access most of the methods for the response (.headers(), .status(),...) and print them correctly, I can not get the ones connected to the response body: .text(), .buffer() and .json().

**Tell us about your environment:**

* Puppeteer version: puppeteer@2.1.1 (works with version 1.20)
* Platform / OS version: Arch Linux
* Node.js version: v10.16.3

**What steps will reproduce the problem?**

Run the following code with node <file>.

```
const puppeteer = require("puppeteer");

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto("https://app.hubspot.com/login").catch(() => {});
    await page.waitForSelector("input#username");
    await page.type("input#username", "test@example.com");
    await page.type("input#password", "testpassword");
    await page.click(".private-checkbox__check");
    const mfaResponsePromise = page.waitForResponse(response =>
        response.url().includes("/login-api/v1/login?src=ui"),
    );
    await page.click("#loginBtn");
    const mfaResponse = await mfaResponsePromise;
    console.log("Response text");
    console.log(await mfaResponse.text());
    console.log("END");
    await browser.close();
})();
```

**What is the expected result?**
Response text
{"status":"INVALID_PASSWORD","message":"Invalid password.","correlationId":"alphanumberic","requestId":"alphanumberic"}
END

**What happens instead?**
It hangs after printing the Response text

**Comment by lallenlowe** [comment]
We're seeing the same issue.

**Comment by mhhf** [comment]
same here

**Comment by zsh-eng** [comment]
I'm also experiencing this issue with Puppeteer v14.4.1. After getting the response, the program is left indefinitely waiting on `await response.text()`

**Comment by andrebnf** [comment]
Same thing here, using Puppeteer 15.5.0. In my use case I call `await response.text()` right after a `page.waitForResponse` call. Also, calling it from inside `waitForResponse` body gives the same behavior: `TimeoutError: Timeout exceeded while waiting for event`

**Comment by jeffreyleblanc225** [comment]
Same issue here, random hangs when using this function

**Comment by ddofborg** [comment]
Same issue :( Anyone found a solution or a workaround?

**Comment by OrKoN** [comment]
Not able to reproduce in the latest version. The script prints the expected result.
