### ISSUE TITLE
request.respond times out when given malformed header with embedded carriage return

### ISSUE THREAD

**Issue by SeanMcMillan** [puppeteer/puppeteer#5570]
I'm scraping a client site to help migrate their content to a new CMS. To avoid stressing the source system, I did a little light caching, saving the previously scraped URL's header and body to my filesystem and intercepting the requests.

I was surprised to discover that some URLs timeout when served from my cache, but not when actually pulled from the source system. I tracked this down to a malformed header being produced by the source system: It contains an embedded carriage return.

Chrome handles this okay when it sees it in the wild. But when puppeteer echoes it back, the navigation times out.

In my actual scraper, I'm just removing the header, which is unnecessary. I've made a minimal test case:

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.1
* Platform / OS version: Windows 10
* URLs (if applicable): Any
* Node.js version: 12.16.1

**What steps will reproduce the problem?**

Intercept any URL and respond with a broken header that contains an embedded carriage return.

**Test Case**
```min.ts
import puppeteer from 'puppeteer';

const rootUrl = 'http://www.google.com/';

const spider = {
    browser: null as any,
    page: null as any,
    async setup(): Promise<any> {
        this.browser = await puppeteer.launch();
        this.page = await this.browser.newPage();

        this.page.setRequestInterception(true);

        this.page.on('request', (req: puppeteer.Request) => {

            (async (): Promise<any> => {
                const headers = {
                    'x-bogus-header': '1.1\n1.1' // This is the culprit
                };
                const body = "Test";


                await req.respond({
                    status: 200,
                    headers: headers,
                    body: body,
                })

            })();

        });
        await this.page.goto(rootUrl);
    },
    async teardown(): Promise<any> {
        await this.page.close()
        await this.browser.close();

    },
};

async function main(rootUrl: string): Promise<any> {

    await spider.setup();
    await spider.teardown();
}

main(rootUrl).catch(err => {
    console.log(`Top level Error: ${err}`);
    return spider.teardown();
}).then(() => { undefined; });

```
**What is the expected result?**
The intercepted fake response should load in the browser, as it does on the real site.

**What happens instead?**

Navigation times out.

`TimeoutError: Navigation timeout of 30000 ms exceeded`

**Comment by daolf** [comment]
Might be related to #6227
