### ISSUE TITLE
page.pdf generating  different and unexpected content with chrome print

### ISSUE THREAD

**Issue by rawbin-** [puppeteer/puppeteer#5577]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: macOS Catalina 10.15.4
* URLs (if applicable): https://github.com/rawbin-/puppeteer-test-pdf
* Node.js version: 12.14.0

**What steps will reproduce the problem?**

use https://github.com/rawbin-/puppeteer-test-pdf
see the data folder, or run the `test-from-html.js`

or you can do with the `ReadMe.md`

_Please include code that reproduces the issue._

```
const path = require('path')
const puppeteer = require('puppeteer')

const DEFAULT_ARGS = [
    '--disable-gpu',
    '--disable-dev-shm-usage',
    '--disable-setuid-sandbox',
    '--no-first-run',
    '--no-sandbox',
    '--no-zygote',
    '--disable-extensions',
    '--disable-webgl'];

const htmlPath = './data/test-simple.html'
const format = 'A5' // alt A5 A4
setTimeout(async () => {
    const htmlPathAb = path.resolve(htmlPath)
    const pdfPath = `${htmlPathAb}-${format}.pdf`

    const browser = await puppeteer.launch({
        args: DEFAULT_ARGS,
    });
    const page = await browser.newPage()
    console.log('opening the page')
    await page.goto(`file:///${path.resolve(htmlPath)}`, {
        waitUntil: 'networkidle0',
        timeout: 60000 * 10 // 尝试性加入最大等待时间，可能还不够。。。
    })
    console.log('waiting for the page')
    await page.waitForFunction(() => {
        return window.contentRenderFinished
    });
    console.log('generating pdf')
    await page.pdf({
        htmlPath: htmlPathAb,
        path: pdfPath,
        format: format,
        printBackground: true,
        landscape:true,
        margin: {
            top: '23.13mm',
            bottom: '25mm',
            left: '0mm',
            right: '0mm'
        }
    });
    await page.close();
    await browser.close()
    console.log('finished')
}, 5000)

```

**What is the expected result?**
chrome print ok
chromium print ok
puppeteer generate ok
no content splited into two pages
![image](https://user-images.githubusercontent.com/8169783/78270274-32906480-753d-11ea-9f71-3048df7762c2.png)

**What happens instead?**
chrome print ok
chromium print ok
puppeteer generate not
one line splited into two pages
![image](https://user-images.githubusercontent.com/8169783/78270276-32906480-753d-11ea-84d9-2968069e94b3.png)

**Comment by leiger** [comment]
The fonts are different.

**Comment by rawbin-** [comment]
> The fonts are different.

how did you see that?

**Comment by leiger** [comment]
> > The fonts are different.
> 
> how did you see that?
The font in the left pic might be 宋体? but the right is PingFang font.
By the way, to prevent word break inside the paragraph, try the css property `break-inside: avoid`

**Comment by xuwencheng** [comment]
I have this problem too, did you solve it?

**Comment by joshyu** [comment]
Any findings about this issue? I am meeting with the same problems.

**Comment by AlfonsoMobilia** [comment]
Hi,
we have the same issue... any findings?
thanks!

**Comment by rvdber** [comment]
Same issue here :-( Anyone suggestions?

**Comment by stevecj** [comment]
I have had a similar issue. When viewing a page in Chrome, for each character, the first font in the font stack that contains a glyph for the character is use. When generating PDF, however, the first font in the list that is available is used whether it has the glyph or not, and a box is displayed for each character that does not exist in that font.

**Comment by OrKoN** [comment]
Cannot reproduce using the latest Chrome.
