### ISSUE TITLE
Arabic signs not rendered correctly

### ISSUE THREAD

**Issue by Firefox2005** [puppeteer/puppeteer#5579]
**Issue**
When using arabic characters in puppeteer, the characters are not rendered correctly.

**Tested Versions**
We've been using V1.19.0 before, where it worked perfectly and were able to reproduce this issue in V1.20.0 and V2.1.1 (did not test V2.0.0, V2.1.0 but I assume that it is the same behaviour there).

**Tested Settings**
We've ben trying PDF as well as Image rendering and they both have the same result.

**Other References**
Following another discussion in issue #4424 it seems like it has been broken once before and then got fixed. And it seems like other guys are experiencing the same since V1.20:

It's broken again in 1.20. In 1.19 works fine
_Originally posted by @saintego in https://github.com/puppeteer/puppeteer/issues/4424#issuecomment-556003914_

**Comment by wavded** [comment]
Not sure if relates to your environment, but this resolved it for me:

https://support.google.com/chrome/thread/5705492?hl=en

Also embedding a custom font with support for the language worked too in my case.
