### ISSUE TITLE
Imported functions not working

### ISSUE THREAD

**Issue by ErezShahaf** [puppeteer/puppeteer#5586]
**Tell us about your environment:**

* Puppeteer version: The latest version
* Platform / OS version: Visual studio code windows 10
* Node.js version: The latest version

**What steps will reproduce the problem?**

**Importing a long JS function from a different file:**

**And then trying to use that function on the page.**
```
await page.exposeFunction("startTheShow",startTheShow);
await page.evaluate(async function() {
   await startTheShow('info','hi','banana');
})
```

**What is the expected result?**
The imported function will run on the page

**What happens instead?**
```
Error: Evaluation failed: TypeError: this._pageBindings.get(...) is not a function
```

Do you guys have an idea how I can fix this?

**Comment by ErezShahaf** [comment]
Hi, I realized that I first have to expose the function like this:
```
await page.exposeFunction("startTheShow",startTheShow);
await page.evaluate(async function() {
   await startTheShow('info','hi','banana');
})
```

But it will return this error:
`Error: Evaluation failed: TypeError: this._pageBindings.get(...) is not a function`
any idea?

**Comment by ErezShahaf** [comment]
I have also tried this syntax : 
```
await page.exposeFunction("startTheShow",async function() {await startTheShow;});
await page.evaluate(async () => {
  await startTheShow('hi','hi','hi');
```


It does not throw an error any more, but it will not run the function on the page

And also this syntax: 

```
await page.exposeFunction("startTheShow",startTheShow);
await page.evaluate(() => {
  startTheShow('hi','hi','hi');
```
which brings the same outcome, no error but nothing executes on the page

**Comment by jackfranklin** [comment]
Hey @ErezShahaf , are you running the latest published Puppeteer from npm or from this GitHub repo directly?

**Comment by jackfranklin** [comment]
Going to close this, but please open a new issue if you're still seeing this issue.

**Comment by comcomhanb** [comment]
I am using the latest published Puppeteer which is v1.18.1 and node v10.15.0. 
With this code, I am getting the exact same error, "VM1571:2 Uncaught (in promise) TypeError: this._pageBindings.get(...) is not a function". 

            await page.exposeFunction('finder', finder);
            await page.evaluateOnNewDocument(()=> {    
                document.addEventListener("click", function callback(e){
                    const selecotr = finder(e.target);
                    console.log(selecotr)
                } , true /* capture */);
                
            });

**Comment by Catsvilles** [comment]
Can confirm same error, got no idea how to fix this

**Comment by joshgrime** [comment]
Quick fix:
