### ISSUE TITLE
npm install puppeteer failed on Windows  Pro

### ISSUE THREAD

**Issue by irfandyj** [puppeteer/puppeteer#5587]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: last
* Platform / OS version: Windows 10 Pro / 1903
* URLs (if applicable):
* Node.js version: 12.11.0

**What steps will reproduce the problem?**

1. Do `npm i -D puppeteer`

**What is the expected result?**
It installed successfully

**What happens instead?**
This error log came out..
```
PS C:\Users\Lenovo\Documents\Projects\Udemy\Javascript\testing-01-starting-setup> npm i -D puppeteer
npm WARN js-testing-introduction@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename 'C:\Users\Lenovo\Documents\Projects\Udemy\Javascript\testing-01-starting-setup\node_modules\.staging\fsevents-d9f5de05\node_modules\concat-map' -> 'C:\Users\Lenovo\Documents\Projects\Udemy\Javascript\testing-01-starting-setup\node_modules\.staging\concat-map-923717af'

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! dest C:\Users\Lenovo\Documents\Projects\Udemy\Javascript\testing-01-starting-setup\node_modules\.agent-base.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Lenovo\Documents\Projects\Udemy\Javascript\testing-01-starting-setup\node_modules\agent-base' -> 'C:\Users\Lenovo\Documents\Projects\Udemy\Javascript\testing-01-starting-setup\node_modules\.agent-base.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-04-05T09_31_43_215Z-debug.log
```

**Comment by irfandyj** [comment]
Oops, was simply fixed by removing `node_modules` and installing back, then do `npm i -D puppeteer` again.

**Comment by guruchara** [comment]
D:\Dev_Assignment>npm i -D puppeteer
'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;
npm ERR! path D:\Dev_Assignment\node_modules\puppeteer
npm ERR! errno -4058
npm ERR! enoent spawn C:\Windows\system32\cmd.exe; ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Local\npm-cache\_logs\2022-02-25T15_45_30_024Z-debug-0.log

D:\Dev_Assignment>


how to solve this error
