### ISSUE TITLE
Page select

### ISSUE THREAD

**Issue by DenisDov** [puppeteer/puppeteer#5602]
I try to trim and uppercase all select option values before page.select:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://jackhammers.co.za/product/handymans-methylated-spirits-5l/');

  await page.evaluate(() => {
      document.querySelectorAll("option").forEach(opt => {
          if(opt.value) opt.value = opt.value.trim().toUpperCase();
          if(opt.innerText) opt.innerText = opt.innerText.trim().toUpperCase();
      });
  });

  const value = await page.$eval('#size option:nth-child(2)', el => el.value);
  console.log('value: ', value);
  await page.select('#size ', value)
  
  const price = await page.$eval('.single_variation_wrap .price .amount', elem => elem.textContent);
  console.log('price: ', price);

  await browser.close();
})();
```
if i added this piece of code:
```
await page.evaluate(() => {
      document.querySelectorAll("option").forEach(opt => {
          if(opt.value) opt.value = opt.value.trim().toUpperCase();
          if(opt.innerText) opt.innerText = opt.innerText.trim().toUpperCase();
      });
  });
```
i have an error `UnhandledPromiseRejectionWarning: Error: Error: failed to find element matching selector ".single_variation_wrap .price .amount"`. 

**Environment**

* Puppeteer version: 1.17.0
* Platform / OS version: Mac OS Mohave
* Node.js version: 11.15.0

**Why i can't retrieve value after modify option values?**

Or how to avoid page select case sensitive behavior, e.g. 
```
<option value="Vacuum " class="p-o-radio" title="Vacuum "> Vacuum </option>
```
in this example value contains whitespace so i can't use `await page.select(selector, 'Vacuum')`;
It would be great if i can select any value with `Vacuum, VACUUM,     VaCUUM `;

**Comment by AmmarYasir29** [comment]
### same error 
locally work fine BUT when upload to heroku not work and apear error `(node:4) UnhandledPromiseRejectionWarning: Error: Error: failed to find element matching selector ".tWeCl"
at ElementHandle.$eval (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:649:19)`
