### ISSUE TITLE
browser.close from puppeteer.connect() not closing Chromium

### ISSUE THREAD

**Issue by pocketjoso** [puppeteer/puppeteer#561]
~~_note_: I was testing on `0.9.0`, just upgraded to `0.10.1` now and testing and will report and update.~~ Same.

## Environment
Puppeteer: `0.10.1`
Node: `7.10.1`.
OS: `macOS Sierra`

## Works
```js
const launchedBrowser = await puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
// ... do stuff here, open pages etc - doesn't matter what in my tests
launchedBrowser.close()
```
The Chromium instance is closed, as expected.

## Does not work
```js
const launchedBrowser = await puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
const browserWSEndpoint = launchedBrowser.wsEndpoint()
// ... do stuff here, open pages etc - doesn't matter what in my tests

const connectedBrowser = await await puppeteer.connect({
      ignoreHTTPSErrors: true,
      browserWSEndpoint
    })
// the connection works, I can use this browser just as expected
// ... do stuff here, open pages etc - doesn't matter what in my tests

// however this does nothing.
connectedBrowser.close()
```

In this latter case the Chromium instance lives on (until process.exit) - `the close` call seems to have no effect.

**Comment by pocketjoso** [comment]
Following this up - realising that perhaps what you had intended; that only the code who executed the `puppeteer.launch` command has permission to close the browser, but if so the launch command should either not be available on the `connected` browser object, or give some kind of error. As it is right now is confusing.

**Comment by aslushnikov** [comment]
> In this latter case the Chromium instance lives on (until process.exit) - the close call seems to have no effect.

This is intended behavior: multiple puppeteer browsers might be connected (via the `puppeteer.connect`) to the same chrome process, so closing any of them should not terminate the process.

> if so the launch command should either not be available on the connected browser object, or give some kind of error. As it is right now is confusing.

Could you please elaborate on this?

**Comment by pocketjoso** [comment]
> This is intended behavior

Got it.

@aslushnikov 
> Could you please elaborate on this?

I mean that I am able to call `connectedBrowser.close()` without any error (although it does nothing). If it's not going to work, I expect an error or at least warning. ~~ `You cannot call browser.close on the browser objected received from puppeteer.connect. Only the browser object received from puppeteer.launch has this capability.` It would also be fine to just remove the method from the connected browser object.

**Comment by Garbee** [comment]
> It would also be fine to just remove the method from the connected browser object.

I don't see how this would be fine at all. An error with a property message as described is light-years better then dynamically adding or removing a method on an object. Errors provide useful debug information. Calling a non existent method will give you "call to undefined method" or similar which is not helpful at all.

**Comment by pocketjoso** [comment]
Well I meant to say that in either case the documentation should clearly state that the `browser.close` method is only available on the original browser object received from `puppeteer.launch`.

But I agree, an error message is better than removing the method.

**Comment by vsemozhetbyt** [comment]
Does `browser.close()` for `puppeteer.connect()` just let the `browser` object to be GC-ed?

**Comment by aslushnikov** [comment]
`browser` object holds a connection to the running browser; internally, the connection is a websocket. Calling `browser.close()` closes the connection.

If the browser was created with `browser.launch()`, then `browser.close()` additionally closes the chrome process.

> Does browser.close() for puppeteer.connect() just let the browser object to be GC-ed?

Yes, the `browser.close()` is required to cleanup resources.

> But I agree, an error message is better than removing the method.

Regardless of whether the browser is launched via `browser.launch` or `browser.connect`, it is recommended to call `browser.close()` in the end of the script.

**Comment by pocketjoso** [comment]
@aslushnikov Thanks for clearing it up! Hope this clarification can make it into the docs as well, would have saved me some time debugging. :)

**Comment by ali-habibzadeh** [comment]
When the browser is `browserWSEndpoint` via `puppeteer.connect`, each newPage is a newTab but browser.close does not close that respective tab and as a result many executions accumulates may tabs. 
What is the solution for close a tab after it was used?

**Comment by achyutjhunjhunwala** [comment]
This issue should be reopened.
I use web socket to run some code -

`    let browser = await puppeteer.connect({ browserWSEndpoint: 'ws://chrome:3000' });

    const page = await browser.newPage();

    await page.setViewport({
      width: resolution.x,
      height: resolution.y,
    });

    let scrappedData = {};

    try {
      await page.goto(this.url, { waitUntil: 'networkidle2' });
      await this.instantiateHelpers(page);
      scrappedData = await this.scrapeContent(page);
    } catch (e) {
      await page.close();
      await browser.close();
      browser = null;
    }

    let pages = await browser.pages();
    logger.info(`Pages : ${pages.length}`); // This one prints 2 ? Why ?
    await page.close();
    await browser.close();
    return scrappedData;
  }`

After the code execution has completed -
And i do `ps aux | grep chrome | wc -l`
It returns 4

I am using browserless/Chrome docker image and it always creates 5 instances and kills just 1 after job done.

**Comment by aslushnikov** [comment]
@achyutjhunjhunwala check out [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md), specifically the use of `dumb-init`. Running chrome in docker without `dumb-init` makes it impossible to kill chrome properly.

**Comment by upugo-dev** [comment]
Hey @aslushnikov I'm having issues with runaway puppeteer chrome processes after doing a browser.launch() and then running google lighthouse on the wsEndpoint().port

I close the browser doing a browser.close() and then after running netstat on the port that I run my node app on (in this case, localhost:3001) I get these strange TIME_WAIT processes: 

```
  Proto  Local Address          Foreign Address        State           PID
  TCP    0.0.0.0:3001           0.0.0.0:0              LISTENING       23940
  TCP    [::]:3001              [::]:0                 LISTENING       23940
  TCP    [::1]:3001             [::1]:62122            TIME_WAIT       0
  TCP    [::1]:62121            [::1]:3001             TIME_WAIT       0
```

These processes hang about for a while and then dissapear after say 1 minute. I have tried doing various combinations of process.kill(), using treekill, pstree and so on, no luck. 

The reason I have come across this issue is I am deploying this code to AWS Elastic Beanstalk where it recieves high traffic and spawns lots of puppetteer instances, and I eventually run into [issue 594](https://github.com/GoogleChrome/puppeteer/issues/594 ), which crashes my app server. The issue is not run into if there is sufficiently low traffic to the app, or sufficient time delay between requests (presumably to allow the ~1 minute required for the zomby processes to vanish).

If I ssh into the EB ubuntu instance during high/fatal levels of traffic, and run `top` I can see like >20 chrome processes, even after all the node processes have called browser.close() and exited themselves. 

Are the TIME_WAIT processes spawned by puppetteer usually? Is this a symtom of testing my code locally on a windows machine? Are these TIME_WAIT the ExitListener processes or something else?

**Comment by AlmogCohen** [comment]
@upugo-dev I have the EXACT same issue. Same installation, Elastic beanstalk, same high traffic loads and a puppeteer worker that suddenly goes blank after a while, with too many open `chrome` processes. Have you found a solution?

**Comment by meloman-a** [comment]
I have the same problem working with Puppeteer inside docker container! After browser.close() there are still too many processes!

**Comment by gelfandbein** [comment]
> @achyutjhunjhunwala check out [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md), specifically the use of `dumb-init`. Running chrome in docker without `dumb-init` makes it impossible to kill chrome properly.

thanks! it's fixed all my problems with processes of chrome in container

**Comment by achyutjhunjhunwala** [comment]
> @achyutjhunjhunwala check out [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md), specifically the use of `dumb-init`. Running chrome in docker without `dumb-init` makes it impossible to kill chrome properly.

Thanks alot mate. At that time the only solution i could work with was to run it on a dedicated EC2 machine but now i am happy, now i know the fix and what wrong i was doing

**Comment by atif-saddique-deel** [comment]
> @achyutjhunjhunwala check out [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md), specifically the use of `dumb-init`. Running chrome in docker without `dumb-init` makes it impossible to kill chrome properly.

Thanks, This helped me fix my problem. I was already using `dumb-init` in Dockerfile but in was being overwritten by command argument in kubernetes's helm chart. So the above answer helped me look into the right direction.
