### ISSUE TITLE
Puppeteer install hangs indefinitely

### ISSUE THREAD

**Issue by sbocinec** [puppeteer/puppeteer#5611]
I'm experiencing one weird issue with `npm install puppeteer` - the installation idenfinitely hangs on ` Downloading Chromium r662092 - 111.6 Mb [====================] 99% 0.0s`.

The same has been already reported in https://github.com/puppeteer/puppeteer/issues/4688 , but closed as automagically solved.

I couldn't believe there is any magic involved so I decided to troubleshoot it and found a solution to install the module on my environment without the installation hanging. Despite having solution, I can reliably replicate the issue. In short:
* the issue only occurs when I'm connected to a 802.11n 2.4GHz wifi SSID
* being connected to a 5GHz 802.11ac SSID configured on the same wifi access point, the `npm install puppeteer` works as expected.

Even it looks like the culprit might be in the misconfigured AP or some weird network connection/configuration, I think, the real culprit lies somewhere in the install scripts: `install.js` / `BrowserFetcher.js`, where downloading the last chunk of the chromium browser somehow never finish.

### Steps to reproduce

I'm worried you won't be able to replicate the issue, but I will provide as much as possible data so that it might be possible to find the bug inside the code despite not being able to replicate it on your own machine.

**Tell us about your environment:**

* Puppeteer version: 1.17.0, 1.18.0, 1.18.1, 1.19.0, .1.20.0
* Platform / OS version: Linux, 64bit, Ubuntu 19.10
* URLs (if applicable): https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/662092/chrome-linux.zip (the chromium artifact being downloaded)
* Node.js version: v12.16.1, v12.16.0, v12.13.0 (tried with all)

**What steps will reproduce the problem?**

1. Connect to my local 802.11n 2.4GHZ SSID. ( AP running OpenWRT v19.07.2)
2. Install puppeteer: `npm install puppeteer@1.17.0`
3. Installation hangs indefinitely with following output:
```
$ npm install puppeteer@1.17.0

> puppeteer@1.17.0 install /home/p/workspace/p/node_modules/puppeteer
> node install.js

Downloading Chromium r662092 - 111.6 Mb [====================] 99% 0.0s
```

The same is for other versions:
```
$ npm install puppeteer@1.18.1

> puppeteer@1.18.1 install /home/p/workspace/p/node_modules/puppeteer
> node install.js

Downloading Chromium r672088 - 112.1 Mb [====================] 99% 0.0s
```
4. Connect to a 5GHz 802.11ac SSID or 2.4GHz 802.11ac SSID and everything works:
```
$ npm install puppeteer@1.17.0

> puppeteer@1.17.0 install /home/p/workspace/p/node_modules/puppeteer
> node install.js

Downloading Chromium r662092 - 111.6 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/p/workspace/p/node_modules/puppeteer/.local-chromium/linux-662092
+ puppeteer@1.17.0
updated 1 package and audited 51 packages in 9.066s
found 0 vulnerabilities

```

**What is the expected result?**

```
$ npm install puppeteer@1.17.0

> puppeteer@1.17.0 install /home/p/workspace/p/node_modules/puppeteer
> node install.js

Downloading Chromium r662092 - 111.6 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/p/workspace/p/node_modules/puppeteer/.local-chromium/linux-662092
+ puppeteer@1.17.0
updated 1 package and audited 51 packages in 9.066s
found 0 vulnerabilities
```

**What happens instead?**
```
$ npm install puppeteer@1.17.0

> puppeteer@1.17.0 install /home/p/workspace/p/node_modules/puppeteer
> node install.js

Downloading Chromium r662092 - 111.6 Mb [====================] 99% 0.0s
```
And here it hangs indifinetly

**Other details**
I tried to debug the installation and used following code modifications to print content of downloadedByte, chunk size, etc when running the install on the `broken` SSID:

`install.js`: 
```
104,105d103
<   console.log(`delta: ${delta}`);
<   console.log(`lastDownloadedBytes: ${lastDownloadedBytes}`);
```

`lib/BrowserFetcher.js`:
```
249a250
>     console.log(`chunk.length: ${chunk.length}`);
250a252
>     console.log(`downloadedBytes: ${downloadedBytes}`);
```

Then running `node install.js` resulted in following output:
```
content-length: 116993080
totalBytes: 116993080
chunk.length: 279
downloadedBytes: 279
Downloading Chromium r662092 - 111.6 Mb [                    ] 0% 0.0s chunk.length: 1378
downloadedBytes: 1657
chunk.length: 1378
downloadedBytes: 3035
chunk.length: 1378
...
// lots of data
...
lastDownloadedBytes: 116914804
chunk.length: 16384
downloadedBytes: 116931188
delta: 16384
lastDownloadedBytes: 116931188
chunk.length: 16384
downloadedBytes: 116947572
delta: 16384
lastDownloadedBytes: 116947572
Downloading Chromium r662092 - 111.6 Mb [====================] 99% 0.0s chunk.length: 16384
downloadedBytes: 116963956
delta: 16384
lastDownloadedBytes: 116963956
chunk.length: 16384
downloadedBytes: 116980340
delta: 16384
lastDownloadedBytes: 11698034
```

And here it hangs indifinetely.
It looks it never finishes the download, never ticks onSuccess here..

Connecting to the `correct` SSID, running the `node install.js` again looks like this:

```
content-length: 116993080
totalBytes: 116993080
chunk.length: 267
downloadedBytes: 267
delta: 267
lastDownloadedBytes: 267
Downloading Chromium r662092 - 111.6 Mb [                    ] 0% 0.0s chunk.length: 1366
downloadedBytes: 1633
delta: 1366
lastDownloadedBytes: 1633
chunk.length: 1366
downloadedBytes: 2999
delta: 1366
lastDownloadedBytes: 2999
chunk.length: 1366
downloadedBytes: 4365
delta: 1366
lastDownloadedBytes: 4365
chunk.length: 1366
downloadedBytes: 5731
delta: 1366
...
// lots of data
...
lastDownloadedBytes: 116965376
chunk.length: 16384
downloadedBytes: 116981760
delta: 16384
lastDownloadedBytes: 116981760
chunk.length: 11320
downloadedBytes: 116993080
delta: 11320
lastDownloadedBytes: 116993080
Downloading Chromium r662092 - 111.6 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/p/workspace/p/node_modules/puppeteer/.local-chromium/linux-662092
```

Let me know if i can provide you any other information or test any fix, I'll be glad to test it on the `broken` SSID.

Thanks in advance for any help!

**Comment by ranman** [comment]
I can confirm this also happens for me on certain wifi networks. No idea why. Just switched to my phone hotspot and it installed correctly.

**Comment by jonathanpmartins** [comment]
I just used a VPN to be able to install via NPM. Whats going on?

**Comment by grantwhitaker06** [comment]
@ranman is on to something did the same thing and it worked. very frustrating, with no apparent reason.

**Comment by jonathanpmartins** [comment]
Only a VPN solved it for me!

**Comment by JMicheli** [comment]
I just experienced the same issue others are describing here. I was unable to install without it hanging on my desktop (Windows 10, wired), but installed without issue on my laptop (Mint, wifi). Same repo in both cases. After rebooting my router, however, I was able to install on the desktop.

**Comment by Amandixit10** [comment]
I am facing issue installing puppeteer ,  i tried a method mentioned above ,using phone hotspot over WIFI and volla , it worked !!

**Comment by GoroJR** [comment]
I am using Parrot OS, had the same issue while running:
`npm i puppeteer`

Solution: Open your Connections settings-->General configurations-->Check the  "Automatically connect to VPN box

I hope this helps you all.

**Comment by talhamirza1** [comment]
For me, the solution was to delete the package-lock.json file run npm install again using VS code's terminal

**Comment by mariavilaro** [comment]
After 3 days trying to run npm install, using different node and npm versions, deleting node_modules, package-lock, and doing all the possible variations, the process just stuck at different %, I changed my connection (normal ethernet connection) to a 4G mobile connected using USB and it just worked without any problem.

**Comment by jonathanpmartins** [comment]
Yep, it seem to block something unknown... The simple fact that this is being ignored for this long, tells a lot!

**Comment by gurgolo** [comment]
I am also experiencing this problem

**Comment by zirismetov** [comment]
again same problem

**Comment by vasani-arpit** [comment]
Same issue here. Using VPN works. so change your network if you are facing this issue.

**Comment by grantwhitaker06** [comment]
Is there any status update on this? Still occurs intermittently.

**Comment by jonathanpmartins** [comment]
It is happening for 2 years. Certainly an forced and ignored configuration!

**Comment by w0otness** [comment]
Just happened with me. `npm i` with PUPPETEER_SKIP_DOWNLOAD, then manually ran `node node_modules\puppeteer\install.js`
For me, on Windows10 it downloads chrome-win.zip to `node_modules\puppeteer\.local-chromium\chrome-win.zip` and when extract-zip runs all that is created is an empty dir. 

Seems extract-zip has a problem with the fs/promises `fs.realpath`. 
If I use fs:
```const fs = require('fs')
  fs.realpath(`R:\\node_modules\\puppeteer\\.local-chromium\\win64-1022525`,console.info)```
works fine.
If I use fs/promises:
```const { promises } = require('fs')
  promises.realpath(`R:\\node_modules\\puppeteer\\.local-chromium\\win64-1022525`).then(console.info)```
I get `Error: EISDIR: illegal operation on a directory`.

The fix? possibly use a different zip lib, or make a fix for extract-zip, or figure out why fs/promises realpath is different to fs.realpath. Strange as I've had it work on Windows before.

**Comment by zirismetov** [comment]
Hey, guys. Try to update node v16 and npm v8>. Worked for me

**Comment by OrKoN** [comment]
Unfortunately, I don't think we would be able to reproduce this issue and we download Puppeteer many times per day on GitHub Actions and locally. It might be that there is some kind of network misconfiguration or an issue between Node and OS. It's really difficult to say. If someone experiences the issue please, debug the downloadFile function here https://github.com/puppeteer/puppeteer/blob/341b669a5e45ecbb9ffb0f28c45b520660f27ad2/src/node/BrowserFetcher.ts#L317 which used Node's http module to see where it gets stuck. Please make sure to use the latest Node/NPM/Puppeteer version and report a new issue with the details. It could well be some Node issue that shows on certain networks/OSes.

**Comment by Rudxain** [comment]
I'm getting the same problem. Seems related to https://github.com/npm/cli/issues/4028

**Comment by bytes-commerce** [comment]
I have the same problem in npm 10.2.4!

**Comment by mifi** [comment]
I had this problem in Github Actions. Puppeteer download took 5 minutes on windows & linux, and on macos 13 it took 1hr+ (after which I cancel the job).

my command was:
```bash
npx @puppeteer/browsers install chrome@${{ env.CHROME_BUILD_NUMBER }} --path ${{ github.workspace }}/browser
```

replacing it with `yarn dlx` solved the problem, so it's definitely a problem with `npx`:
```bash
yarn dlx @puppeteer/browsers install chrome@${{ env.CHROME_BUILD_NUMBER }} --path ${{ github.workspace }}/browser
# takes 2-6 seconds on all os'es
```

**Comment by OrKoN** [comment]
> I had this problem in Github Actions. Puppeteer download took 5 minutes on windows & linux, and on macos 13 it took 1hr+ (after which I cancel the job).
> 
> my command was:
> 
> ```shell
> npx @puppeteer/browsers install chrome@${{ env.CHROME_BUILD_NUMBER }} --path ${{ github.workspace }}/browser
> ```
> 
> replacing it with `yarn dlx` solved the problem, so it's definitely a problem with `npx`:
> 
> ```shell
> yarn dlx @puppeteer/browsers install chrome@${{ env.CHROME_BUILD_NUMBER }} --path ${{ github.workspace }}/browser
> # takes 2-6 seconds on all os'es
> ```

are you using the latest version? i.e., npx @puppeteer/browsers@latest install ...? if not could you please, file a bug report with exact versions you are using.

**Comment by mifi** [comment]
I cannot reproduce the problem with a simple test case, I can only reproduce it by re-running this old Github Action:

https://github.com/mifi/reactive-video/actions/runs/12104497564/job/33771544221

it hangs every time i re-run that job. But I tried copying the stuff from tests.yml into a new branch but it cannot reproduce the problem there. I don't know what's going on but it seems the conditions to trigger this bug are hard to reproduce.

**Comment by jazzzz** [comment]
I had the issue, and found out it was a bug in `@puppeteer/browsers` fixed in version 2.2.0. Here is the PR that fixes it: [fix: don't keep connection alive after redirect by Lightning00Blade · Pull Request #12096 · puppeteer/puppeteer](https://github.com/puppeteer/puppeteer/pull/12096)

**Comment by boostpaal** [comment]
If you're using Docker, add to top of dockerfile:
```
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
```

Then
```
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google.asc] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
RUN apt-get update

RUN apt-get install \
  libxss1 \
  fonts-freefont-ttf \
  fonts-ipafont-gothic \
  fonts-kacst \
  fonts-thai-tlwg \
  fonts-wqy-zenhei \
  google-chrome-stable
```
(I think you need those fonts for Chrome to work)

If on Debian, your chrome will be located at `/usr/bin/google-chrome-stable`.

If using Javascript, open Puppeteer with:
```
const launchOptions: PuppeteerLaunchOptions = {
  executablePath: '/usr/bin/google-chrome-stable',
  // More options...
};
```

**Comment by fayezm** [comment]
Same issue today, had to connect to a 4G hotspot to get it installed. Very strange
