### ISSUE TITLE
CSS @page rule is not supported

### ISSUE THREAD

**Issue by codewithabhi17** [puppeteer/puppeteer#5613]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Mac OS
* URLs (if applicable):
* Node.js version: v10.16.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    
    <style>
    @page {
         @top-center { content: "Preliminary edition"; }
        @bottom-center { content: "Hi"; }
        }
    </style>
</head>
<body>

</body>
</html>

------------
PDF options:

        var options = {
            width: '1230px',
            displayHeaderFooter: false,
            margin: {
                top: '20px',
                bottom: '50px',
                right: '20px',
                left: '20px'
            },
            printBackground: true,
            format: 'A4',
        }

**What is the expected result?**
Generated pdf shows the @page options set above

**What happens instead?**
Generated pdf does not have @page options

**Comment by Juuldamen** [comment]
The CSS Paged media & fragmentation specifications are not fully supported by Chromium. See [this article](https://www.smashingmagazine.com/2019/06/create-pdf-web-application/) for more info, such as using [Paged.js](https://gitlab.pagedmedia.org/tools/pagedjs) as a polyfill for this kind of functionality.
