### ISSUE TITLE
setJavascriptEnabled throws

### ISSUE THREAD

**Issue by pocketjoso** [puppeteer/puppeteer#562]
Was looking forward to using `setJavascriptEnabled` from #464, but it crashes for me...

## Environment
Puppeteer: `0.10.1`
Node: `7.10.1`.
OS: `macOS Sierra`

### Setup
```js
const browser = puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
const page = await browser.newPage()
await page.setJavaScriptEnabled(false)
```
Given your tests I assume there must be something else going on here than just my code example - perhaps it's a platform problem?

### Error
```
Protocol error (Runtime.evaluate): Promise was collected undefined
    at Session._onMessage (/Users/pocketjoso/penthouse/node_modules/puppeteer/lib/Connection.js:197:25)
    at Connection._onMessage (/Users/pocketjoso/penthouse/node_modules/puppeteer/lib/Connection.js:98:19)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/Users/pocketjoso/penthouse/node_modules/ws/lib/WebSocket.js:143:47)
```

**Comment by JoelEinbinder** [comment]
I can't reproduce this on macOS Sierra, node 7.10.1.

```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
const page = await browser.newPage()
await page.setJavaScriptEnabled(false)
browser.close();
})();
```

**Comment by pocketjoso** [comment]
@JoelEinbinder Thanks for response - I will have to test further and come back with a reduced test case.

**Comment by pocketjoso** [comment]
Okay, so it seems like I cannot call `page.evaluate` after calling `page.setJavascriptEnabled(false)` -> this is what causes my crash reported in initial post.

My intention was to turn of only the JS included in the html of the web page I'm loading, but still for myself to be able to execute JS, a bit like when using the Chrome dev tools on top of a page that has been loaded with JS turned off (still works). 
So this doesn't seem supported - would it be possible to support it, or should I just give up on using `setJavascriptEnabled` for my use case (I need to use page.evaluate)?

**Comment by JoelEinbinder** [comment]
Can you send a reduced test case? We use `evaluate` after `setJavascriptEnabled` in our tests.
https://github.com/GoogleChrome/puppeteer/blob/master/test/test.js#L1774

**Comment by pocketjoso** [comment]
Hmm okay, will look into it again...

**Comment by pocketjoso** [comment]
reduced test case:

```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
const page = await browser.newPage()
await page.setJavaScriptEnabled(false)
const result = await page.evaluate(() => {
  // works
  // return new Promise(resolve => resolve()).then(() => [])
  // hangs - only when using page.setJavaScriptEnabled(false)
  return new Promise(resolve => setTimeout(resolve, 0)).then(() => [])
})
browser.close();
console.log('done')
})();
```

Not quite sure what's going on, any ideas?

**Comment by aslushnikov** [comment]
@pocketjoso AFAIU the timeouts won't fire with disabled javascript since noone spins page's javascript event loop. The synchronous execution should work just fine.

**Comment by pocketjoso** [comment]
You're saying timing api's don't function with javascript disabled? That's good to know - _would make sense to me to add this to docs for this method_. Any further info on this, f.e. what methods does this effect - just `setTimeout` and `setInterval`, or anything else?

**Comment by pocketjoso** [comment]
And just checking with you - do you happen to know any way to wait in JS without using the timing api? Perhaps polling in `requestAnimationFrame` until the time has passed.. assuming `requestAnimationFrame` still runs when JS is disabled?

And I guess since I really want to be blocking and don't have any end user in theory I could just run a for loop until my time has passed, as hacky and ugly as that would be.

Or I'll just put my timeout outside the page.evaluate, since it's currently just wrapping my code in this example. Probably the cleanest fix here.

guess there are enough workarounds for this. :)

**Comment by pocketjoso** [comment]
And I guess since I really want to be blocking and don't have any end user in theory I could just run a for loop until my time has passed, as hacky and ugly as that would be.

**Comment by pocketjoso** [comment]
Or - final comment, I'll just put my timeout outside the `page.evaluate`, since it's currently just wrapping my code in this example. Probably the cleanest fix here.

**Comment by aslushnikov** [comment]
> Perhaps polling in requestAnimationFrame until the time has passed.. assuming requestAnimationFrame still runs when JS is disabled?

I'd expect `requestAnimationFrame` to not run for the same reason as `setTimeouts`. General rule: no callbacks will be called when javascript is disabled.

> in theory I could just run a for loop until my time has passed, as hacky and ugly as that would be.

That would work. However, as you noted later, the best way is to measure time on puppeteer side.

**Comment by pocketjoso** [comment]
In case anyone else needs to ~~ use timeouts inside `page.evaluate` while having JS disabled, `requestAnimationFrame` _does run_, and I implemented a sleep function that will always work inside page.evaluate like this:

```js
function pollUntilTimePassed (start, timeToPass) {
    return new Promise(resolve => {
      requestAnimationFrame(() => {
        const timePassed = Date.now() - start
        if (timePassed >= timeToPass) {
          resolve()
        } else {
          resolve(pollUntilTimePassed(start, timeToPass))
        }
      })
    })
  }
  // not using setTimeout because does not work inside page.evaluate when JS is disabled
  function sleep (time) {
    const start = Date.now()
    return pollUntilTimePassed(start, time)
  }
```
