### ISSUE TITLE
(Docker, Percy.io, Puppeter, WDIO) Headless Chromium with Puppeteer doesn't work on macOS Mojave 

### ISSUE THREAD

**Issue by aabdullin** [puppeteer/puppeteer#5620]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: "dependencies": {  "puppeteer": "^2.1.1" } 
* Platform / OS version: macOS Mojave
* URLs (if applicable): 
* Node.js version: v12.16.1

**What steps will reproduce the problem?**
1. Follow instruction integration Percy with WDIO https://docs.percy.io/docs/webdriverio
2.
`➜  wdio git:(percy-vrt) ✗ make run-chrome-percy suite=smoke.basic.js
docker-compose -f docker/docker-compose.yml exec -T test_env_chrome bash -c "PERCY_TOKEN=<my_token> npx percy exec -- wdio wdio.conf.chrome.js --baseUrl=<IP> --spec smoke.basic.js"
[percy] created build #34: https://percy.io/CORP/contr_app/builds/4855585
Error: Failed to launch the browser process!
/workspace/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/workspace/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/workspace/node_modules/puppeteer/lib/Launcher.js:739:50)
make: *** [run-chrome-percy] Error 1`

Docker images:
`➜  wdio git:(percy-vrt) ✗ docker ps
CONTAINER ID        IMAGE                                                                                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
61ce92cdd18f        ********.com/**************/wdio/<CICDI>_chrome:latest              "docker-entrypoint.s…"   3 hours ago         Up 3 hours                                   docker_<CICDI>_chrome_1
7ad6b1c9ca0a        ********.com/**************/wdio/<CICDI>_firefox:latest             "docker-entrypoint.s…"   3 hours ago         Up 3 hours                                   docker_<CICDI>_firefox_1
ac44d1516327        ********.com/**************/wdio/selenium/node-firefox-debug:3.141   "/opt/bin/entry_poin…"   24 hours ago        Up 24 hours         0.0.0.0:5901->5900/tcp   docker_firefox_1
97b68a8651e8        ********.com/**************/wdio/selenium/node-chrome-debug:3.141    "/opt/bin/entry_poin…"   24 hours ago        Up 24 hours         0.0.0.0:5900->5900/tcp   docker_chrome_1
a73b59c1b256        ********.com/**************/wdio/selenium/hub:3.141                  "/opt/bin/entry_poin…"   24 hours ago        Up 24 hours         0.0.0.0:4444->4444/tcp   docker_selenium-hub_1`

Docker file:
`➜  docker git:(percy-vrt) ✗ cat Dockerfile
FROM node:13.5.0

RUN mkdir /workspace

WORKDIR /workspace/

RUN apt-get update && apt-get upgrade -y

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install -y openjdk-8-jdk && \
  apt-get install -y ant && \
  apt-get clean;

## Fix certificate issues
RUN apt-get update && \
  apt-get install ca-certificates-java && \
  apt-get clean && \
  update-ca-certificates -f;

## Install sshpass
RUN apt-get update && \
  apt-get install -y sshpass && \
  apt-get clean;

## Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

COPY package.json ./
COPY package-lock.json ./

RUN npm install

RUN npm i puppeteer \
    # Add user so we don't need --no-sandbox.
    # same layer as npm install to keep re-chowned files from using up several hundred MBs more space
    && groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /node_modules
COPY . .
USER pptruser
CMD ["tail", "-f", "/dev/null"]`

These solutions are not working:
https://github.com/atom/atom/issues/13176
https://askubuntu.com/questions/547151/error-while-loading-shared-libraries-libxss-so-1

**What is the expected result?**
Screenshot suppose to be saved on Percy.io

**What happens instead?**
`➜  wdio git:(percy-vrt) ✗ docker exec -it docker_chrome_1 bash
seluser@97b68a8651e8:/$ sudo apt-get install libxss1
Reading package lists... Done
Building dependency tree
Reading state information... Done
libxss1 is already the newest version (1:1.2.2-1).
libxss1 set to manually installed.`

![image](https://user-images.githubusercontent.com/14880970/78950467-a83b8980-7a83-11ea-8d8a-63c255347f6d.png)

**Comment by jogi-iween** [comment]
Hi,

even I'm getting the following error on linux server:

ERROR The function passed to Apify.main() threw an exception:
Error: Failed to launch the browser process!

Can anyone help me out with this please. In my windows pc it works fine.
