### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when making requests between docker containers

### ISSUE THREAD

**Issue by thiloilg** [puppeteer/puppeteer#5622]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: macOS Catalina, Puppeteer running inside Node Docker image 
* URLs (if applicable):
* Node.js version: 12

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Setup a docker compose service with the name api. It uses the official Docker Node image and has puppeteer installed.
2. Setup a docker compose service with the name app. It runs a simple Nginx web server.
3. Make a request within docker compose from the puppeteer against the Nginx container

**What is the expected result?**
I can curl the nginx from inside the Node api image like 'curl http://app:3000' and get the html response. Puppeteer should be able to access the service as well.

**What happens instead?**
Puppeteer throws the error:
```
(node:10845) UnhandledPromiseRejectionWarning: Error: net::ERR_SSL_PROTOCOL_ERROR at https://app:3000/login
at navigate (/root/node_modules/puppeteer/lib/FrameManager.js:120:37)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
 at FrameManager.navigateFrame (/root/node_modules/puppeteer/lib/FrameManager.js:94:17)
at Frame.goto (/root/node_modules/puppeteer/lib/FrameManager.js:406:12)
at Page.goto (/root/node_modules/puppeteer/lib/Page.js:672:12)
-- ASYNC --
at Frame.<anonymous> (/root/node_modules/puppeteer/lib/helper.js:111:15)
at Page.goto (/root/node_modules/puppeteer/lib/Page.js:672:49)
at Page.<anonymous> (/root/node_modules/puppeteer/lib/helper.js:112:23)
at DashboardService.<anonymous> (/root/src/features/dashboard/dashboard.service.ts:107:18)
at Generator.next (<anonymous>)
at fulfilled (/root/src/features/dashboard/dashboard.service.ts:5:58)
 at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10845) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10845) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
### Additional information

Dockerfile of the node image running puppeteer:

```
FROM node:12

WORKDIR /root

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN yarn

EXPOSE 80

HEALTHCHECK CMD ["node", "healthcheck.js"]

CMD [ "yarn", "start" ]
```

Javascript code to execute puppeteer:

```
const browser = await puppeteer.launch({
  headless: true,
  executablePath: '/usr/bin/google-chrome-unstable',
  args: ['--no-sandbox', '--unhandled-rejections=strict'],
})
const page = await browser.newPage()
await page.setViewport({
  width: 1280,
  height: 720,
  deviceScaleFactor: 1,
})

const ORIGIN = 'https://app:3000'

await page.goto(`${ORIGIN}/login`)
await page.type('#inputEmail', ADMIN_MAIL)
await page.type('#inputPassword', ADMIN_PASSWORD)
await page.click('#submitLogin')
await page.waitForNavigation()
await page.goto(`${ORIGIN}/dashboards/${id}?fullscreen`)
await page.waitFor(500)

let buf: Buffer = await page.screenshot({
  encoding: 'binary',
  type: 'jpeg',
  quality,
})

Logger.info(`Store thumbnail 1280x720/${imgName}`)
MinioClient.store(bucket, region, `1280x720/${imgName}`, buf)

buf = await sharp(buf)
  .resize(640, 360)
  .jpeg({ quality, force: false })
  .toBuffer()

Logger.info(`Store thumbnail 640x360/${imgName}`)
MinioClient.store(bucket, region, `640x360/${imgName}`, buf)

await browser.close()
```

**Comment by Kuzzy** [comment]
For those who came from google, solution is to rename service from `app` to something else. There is a funny bug in chrome, here is an explanation [Google Chrome implementing HSTS breaks dockerized application testing](https://medium.com/@alex.skrypnyk/google-chrome-implementing-hsts-breaks-dockerized-application-testing-55120e6d67bc)

**Comment by 296223944** [comment]
I am  troubled with this problem.
 Puppeeteer vesion: 15.5.0 

const browser = await puppeteer.launch({
  headless: true,
  args: [ '--single-process',
                    '--no-zygote',
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                    '--lang=zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6'],
})
... ... 
  const page = await browser.newPage();
  try{
  await page.goto("https://xxxxxx");
}catch(e){
 ... ... 
}

It throws exception:

Error: net::ERR_SSL_PROTOCOL_ERROR at  https://xxxxxx
    at navigate (/xxxx/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:194:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:170:21)
    at async Frame.goto (/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:589:16)
    at async Page.goto (/xxx/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1089:16)

**Comment by TingShine** [comment]
I am also troubled with this problem.
Puppeteer ^19.10.1.

I want to run my scripts at docker container, but meet this problem.

**Comment by omnicortex** [comment]
https://github.com/puppeteer/puppeteer/issues/5622#issuecomment-1042921429 help me when I test using Playwright.
