### ISSUE TITLE
How can I remove unnecessary info bar?

### ISSUE THREAD

**Issue by hasibdev** [puppeteer/puppeteer#5623]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version:  13

Sometimes we don't need this kind of info message. Like, chrome is being controlled by automated test, Set as Default browser and more.
I'm new to puppeteer so I just faced just these two. 
Please share some more unnecessary messages and solutions.

**Comment by balexandre** [comment]
for "how to" you should use a forum, like StackOverflow... I get it that you're stuck, but your question is not actually an issue.

**Comment by devingfx** [comment]
You may translate "How to" to "Issue: lack of documentation" though ! :stuck_out_tongue_closed_eyes:
