### ISSUE TITLE
element.click is not realiable when the element changes position between mousedown and mouseup events

### ISSUE THREAD

**Issue by SimonSchick** [puppeteer/puppeteer#5632]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1 and prior (no exact numbers)
* Platform / OS version: MacOS, Windows, Debian
* URLs (if applicable):
* Node.js version: v12.16.2, v13.11.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I have not been able to come up with a repro however we KNOW what is happening, see 
https://stackoverflow.com/questions/49979069/puppeteer-element-click-not-working-and-not-throwing-an-error/50032302#50032302
for more info.

In essence in the time between getting the button position and dispatching the click, (or between issuing the mousedown and up event) the button moves, therefor the mouseup is never dispatched on the element in the browser.

See https://github.com/puppeteer/puppeteer/blob/7a2a41f2087b07e8ef1feaf3881bdcc3fd4922ca/src/JSHandle.js#L282
and
https://github.com/puppeteer/puppeteer/blob/7a2a41f2087b07e8ef1feaf3881bdcc3fd4922ca/src/Input.js#L224

**What is the expected result?**

The button gets clicked.

**What happens instead?**

The button does not get clicked.

**Comment by jrandolf-google** [comment]
We no longer support Node < 14, please try this again with the latest version of Puppeteer and Node >= 14. If the issue still occurs, please reopen this issue and update the description :)
