### ISSUE TITLE
Discarded tabs cause browser.pages() to never resolve

### ISSUE THREAD

**Issue by surlyhacker** [puppeteer/puppeteer#5633]
To reproduce:

1. Run puppeteer with headless false and have several tabs open in the browser
2. Keep the browser and those tabs open for many days
3.  Wait for some of the tabs to be discarded (see chrome://discards)
4. Have puppeteer code that calls and awaits browser.pages()

**What is the expected result?**
The call actually returns before the universe's heat death

**What happens instead?**
The call "never" (for several minutes at least) returns (resolves the promise)

If you click on the discarded tabs and allow chrome to revive them, then new calls to browser.pages() after that will work just fine.

I am also fairly certain that browser.pages() is not the only method that fails to resolve its promise in this situation.  I think many methods will do this.  This took me way too long to figure out.

* Puppeteer version: 2.1.0
* Platform / OS version: Windows 10
* URLs (if applicable): various
* Node.js version:  8.5.0
* Using the built-in chromium that comes with puppeteer (v80.0.3987.0)

**Comment by surlyhacker** [comment]
Also it seems that there is no way to disable tab discarding.  

- There is no (longer) a chrome://flags item for it, 
- no chrome command line argument
- no puppeteer API, 
- and since puppeteer disables extensions, no way to install an extension that disables discarding.  

I guess workarounds could be
-  to write code that periodically brings every tab to front to try to avoid discarding.  
- Or manually prevent it by using the toggle on chrome://discards, 
- or perhaps by pinning tabs.  
- Or open devtools on each tab to prevent discarding.

**Comment by imckl** [comment]
Depends on [Or open devtools on each tab to prevent discarding](https://github.com/puppeteer/puppeteer/issues/5633#issuecomment-612779200), here's a workaround to prevent page being discarded

```ts
puppeteer.launch({
  headless: false,
  devtools: true
});
```

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/ChromeDevTools/chrome-devtools-mcp/issues/1230
