### ISSUE TITLE
Firefox Puppeteer not importing

### ISSUE THREAD

**Issue by hlawuleka** [puppeteer/puppeteer#5653]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.1.1
* Platform / OS version: MacOS Catalina 10.15.3
* URLs (if applicable):
* Node.js version: 12.6.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. import * as puppeteerFirefox from 'puppeteer-firefox'
2.
3.

**What is the expected result?**
The import should pull in puppeteer-firefox as `import puppeteer from 'puppeteer'` pulls puppeteer

**What happens instead?**
Could not find a declaration file for module 'puppeteer-firefox'. '/Users/<path>/node_modules/puppeteer-firefox/index.js' implicitly has an 'any' type.
  Try `npm install @types/puppeteer-firefox` if it exists or add a new declaration (.d.ts) file containing `declare module 'puppeteer-firefox';`

**Comment by mathiasbynens** [comment]
cc @mjzffr 

`puppeteer-firefox` is deprecated in favor of Firefox support in `puppeteer` itself. See https://github.com/puppeteer/puppeteer/tree/master/experimental/puppeteer-firefox#prototype-puppeteer-for-firefox.

**Comment by hlawuleka** [comment]
Thanks, but upgrading to version`3.0.0` results in the following error:

`Could not find browser revision latest. Run "npm install" or "yarn install" to download a browser binary.` - I did run yarn install and still get the same error when I run `yarn test:unit`

**Comment by mjzffr** [comment]
@hlawuleka Could you share detailed steps to reproduce for your scenario so we can investigate the problem?

**Comment by hlawuleka** [comment]
`yarn add puppeteer@next` and select version `3.0.0`

**Comment by mjzffr** [comment]
Ah, I think the 'Could not find browser message' might be a confusing.

If you want puppeteer to download Firefox as part of installation you should run something like `PUPPETEER_PRODUCT=firefox yarn add puppeteer@next`.

**Comment by hlawuleka** [comment]
Sure, this has changed things, now we get the following error, seems pretty close:

`Could not find browser revision 737027. Run "npm install" or "yarn install" to download a browser binary.`

**Comment by hlawuleka** [comment]
> Sure, this has changed things, now we get the following error, seems pretty close:
> 
> `Could not find browser revision 737027. Run "npm install" or "yarn install" to download a browser binary.`

Actually this was caused by using capital `F` for `profuct: 'firefox'`, but now I just get countless instances of Nightly opening and test timing out. This is strange

**Comment by mjzffr** [comment]
Firefox support is experimental so you will encounter timeouts for features that aren't supported yet. 

If you could share more information about your test suite (link to project?), including debug logs for a Chrome run (e.g. `DEBUG=puppeteer:* yarn:test unit`) that can help prioritize feature work in Firefox's remote protocol implementation.
