### ISSUE TITLE
Puppeteer 3.0.0 refuses to launch on CI

### ISSUE THREAD

**Issue by aduh95** [puppeteer/puppeteer#5661]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: Linux / ubuntu-latest (GH Actions CI)
* URLs (if applicable): https://github.com/aduh95/viz.js/runs/592728791
* Node.js version: 13.12.0

**What steps will reproduce the problem?**

`puppeteer.launch()`

**What is the expected result?**

The browser should launch headlessly.

**What happens instead?**

```
Error: Failed to launch the browser process!
/home/runner/work/viz.js/viz.js/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

      at onClose (node_modules/puppeteer/lib/Launcher.js:615:20)
      at Interface.<anonymous> (node_modules/puppeteer/lib/Launcher.js:605:56)
      at Interface.close (readline.js:424:8)
      at Socket.onend (readline.js:202:10)
      at endReadableNT (_stream_readable.js:1201:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
``` 

I didn't find `libgbm` listed on the [Troubleshooting page](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix), it's probably a requirement quite recent because I didn't have the issue on Puppeteer 2.x.

**Comment by miketimofeev** [comment]
@aduh95 it really looks like some new requirement - after installing libgbm in runtime everything works fine for me
```
        sudo apt-get update
        sudo apt-get install -y libgbm-dev
```

**Comment by martincostello** [comment]
Same issue on these three auto-PRs from dependabot to update puppeteer - they all fail on Linux:
  * https://github.com/martincostello/api/pull/336
  * https://github.com/martincostello/alexa-london-travel-site/pull/617
  * https://github.com/martincostello/website/pull/530

```sh
  17 04 2020 04:22:16.927:ERROR [launcher]: Cannot start ChromeHeadless
  	/home/runner/work/api/api/src/API/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

[Logs](https://github.com/martincostello/api/pull/336/checks?check_run_id=594291736#step:4:67)

**Comment by mathiasbynens** [comment]
https://github.com/puppeteer/puppeteer/pull/5667

**Comment by mirajshaikh** [comment]
> @aduh95 it really looks like some new requirement - after installing libgbm in runtime everything works fine for me
> 
> ```
>         sudo apt-get update
>         sudo apt-get install -y libgbm-dev
> ```

thanks, it really works. I spend days to find the solution but nothing works. but I tried your solution It really works. 🥳
