### ISSUE TITLE
Header/Footer template data injection not available for any external chromium build

### ISSUE THREAD

**Issue by chrisjpatty** [puppeteer/puppeteer#5663]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: Linux/Windows/Mac
* Node.js version: v10.20.1

**What steps will reproduce the problem?**

Here's a simple node script that will manifest the problem:
```js
const puppeteer = require("puppeteer-core")
const HTML = `<html><body><h1>Title of the Page</h1></body></html>`
const HEADER_TEMPLATE = `
<div>
  <h1 style="font-size:18px;" data-pagenumber=""></h1>
</div>
`
const main = async () => {
  const browser = await puppeteer.launch({
    executablePath: "./chrome-linux/chrome",
    args: [
      '--disable-setuid-sandbox',
      '--no-sandbox',
      '--export-tagged-pdf'
    ]
  })
  const page = await browser.newPage()
  await page.setContent(HTML)
  await page.pdf({
    path: "test.pdf",
    displayHeaderFooter: true,
    headerTemplate: HEADER_TEMPLATE,
    margin: {
      top: '.5in'
    }
  })
  await browser.close()
}
main()
```

1. Run puppeteer using any version of Chromium except the one bundled with puppeteer. This can be a custom build of chromium, or a build from any revision number.
2. Add a header or footer template using one of the injected class names like, "pageNumber":
```html
<div>
    <h1 class="pageNumber></h1>
</div>
```
3. Generate a PDF using this header or footer template. Observe that the page number was not injected.

**What is the expected result?**
The h1 element with the pageNumber class name should have been injected with the number of the current page.

**What happens instead?**
The element is blank and does not have the page number injected.

So, I understand that Puppeteer is only guaranteed to work with the version of Chromium that comes bundled with it, however this seems like an odd gap in the handling of header/footer templates. 

If you look at this file from chromium source, this is where elements are injected with the data that corresponds to those classes: [print_header_footer_template_page.html](https://source.chromium.org/chromium/chromium/src/+/master:components/printing/resources/print_header_footer_template_page.html)

This function is called with an options object that should include the data for those classes:
```js
83 | function setupHeaderFooterTemplate(options) {
```
And then they're used down below like this:
```js
107 | options.date = new Date(options.date).toLocaleDateString();
108 |   for (const cssClass of ['date', 'title', 'url', 'pageNumber', 'totalPages']) {
109 |     for (const element of document.querySelectorAll(`.${cssClass}`)) {
110 |       element.textContent = options[cssClass];
111 |       if (options.isRtl)
112 |         element.dir = 'rtl';
113 | 
114 |       if (elementIntersects(element, topMargin, bottomMargin, leftMargin,
115 |                             rightMargin)) {
116 |         element.style.visibility = 'hidden';
117 |       }
118 |     }
119 |   }
```

On the resulting PDF, interestingly enough, even the date injectable class name doesn't render. 

My question is this, is puppeteer doing something magical that makes this block of code work for the included chromium version, but for no other versions?

**Comment by chrisjpatty** [comment]
Sorry, I inadvertently published this before I was done editing it.

**Comment by chrisjpatty** [comment]
I've updated with all the required information and am reopening.

**Comment by chrisjpatty** [comment]
Still an issue :)

**Comment by OrKoN** [comment]
@chrisjpatty which exactly Chromium version are you running Puppeteer with? Not that we only officially support the bundled version and there is no backward compatibility? I.e., the latest Puppeteer version might not work with older Chromium versions. Does it happens with the latest Puppeteer version?
