### ISSUE TITLE
puppeteer downloads 64bit version of Chromium on 32bit Linux system

### ISSUE THREAD

**Issue by kyeno** [puppeteer/puppeteer#5665]
When installing default puppeteer with `npm` and no custom `ENV` options it auto-downloads 64bit executable of Chromium (x86-64), despite being ran on 32bit Linux system:

```bash
$ uname -srm
Linux 4.8.17-hardened-r2 i686
$ cat /etc/gentoo-release
Gentoo Base System release 2.6
$ node -v
v10.19.0
$ npm install --save puppeteer
> puppeteer@3.0.0 install /.../node_modules/puppeteer
> node install.js

Downloading Chromium r737027 - 123.7 Mb [====================] 100% 0.0s
```

index.js file literally from example on npm.js, just changed "example.com" to "google.com"
```js
'use strict';
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```

Execution:
```bash
$ node index.js
(node:7926) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/.../node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: /.../node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: cannot execute binary file
(...)
```

Proof:
```bash
$ file node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome
node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped
```

Workarounds:
Haven't tried that yet (filing this report beforehand), but I guess hand-downloading precompiled 32bit Chromium or compiling it myself, then either using "puppeteer-core" or "puppeteer" with `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` ENV variable set.

**Comment by kyeno** [comment]
Due to Chromium failing to compile on 32bits, here's a confirmed workaround (Gentoo):
```bash
# emerge www-client/firefox-bin
$ npm uninstall --save puppeteer
$ export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
$ export PUPPETEER_PRODUCT=firefox
$ export PUPPETEER_EXECUTABLE_PATH=/opt/firefox/firefox-bin
$ npm install --save puppeteer
```

What it means - you have to switch puppeteer to Firefox to be able to run it on 32bit machines.
This solution (or at least a warning) *should* be implemented in the post-install script.

**Comment by paullewis** [comment]
Hi, yes [Chromium no longer supports 32-bit on Linux](https://groups.google.com/a/chromium.org/g/chromium-dev/c/FoE6sL-p6oU) so I'll go ahead and close this bug.

**Comment by kyeno** [comment]
Quite sad to be honest...
Still, *precise* arch detection and Firefox as fallback could (and probably should) be default behavior in post-install (or maybe even runtime?), especially as puppeteer-firefox have been merged into the main branch and vast majority of the API is now supported.
