### ISSUE TITLE
Test install scripts on CI

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#5670]
Now that we have TypeScript involved it would be nice to have tests on CI that ensure you can install Puppeteer with no issues.

We should test the following scenarios:

* I can `npm install puppeter@X` from GitHub with no errors.
* I can `npm install github.com/puppeteer/puppeteer` with no errors.

The first release of V3 broke the second case and it'd be easy to check them on CI.

**Comment by mathiasbynens** [comment]
We could use one of [the examples](https://github.com/puppeteer/puppeteer/tree/master/examples) to verify not just the installation but also that basic Puppeteer functionality worked. Ideally we'd use an example that doesn't rely on any particular resource like Hacker News. Maybe navigating to a `data:` URL and saving it as a PDF?
