### ISSUE TITLE
Bundled puppeteer-web.js does not work as expected. ("puppeteer.connect" is not a function.)

### ISSUE THREAD

**Issue by lazybotter** [puppeteer/puppeteer#5675]
Hi, this is probably against the guideline but here goes. 

I am trying to run Puppeteer on the client side browser (VueJS App). The app will run a local express server to run the Chromium instance and expose the wsEndpoint to the client. The client will then connect to the web socket and control the browser on the server. I cannot get this to work!

I have followed the steps to bundle puppeteer for the web browser here:
https://github.com/puppeteer/puppeteer/tree/master/utils/browser

Here is my example VueJS components:

```
<template>
    <div>
        <button class="btn btn-success" @click="startBrowser">Launch Browser</button>
        <h5>WS Endpoint: {{wsEndpoint}}</h5>
    </div>
</template>

<script>
    import ApiService from "@/services/api.service";
    const puppeteer = require("@/puppeteer/utils/browser/puppeteer-web");

    export default {
        name : "browser-launcher",
        components:{},
        props: {},
        data() {
            return {
                wsEndpoint : ""
            }
        },
        methods: {
            startBrowser(){
                //Start browser on local server, expose wsEndpoint
                ApiService.post("/local/browser/launch").then(async res => {
                    try {
                        this.wsEndpoint = res.data.wsEndpoint;
                        const browser = await puppeteer.connect({
                            browserWSEndpoint: this.wsEndpoint
                        });
                        const page = await browser.newPage();
                        await page.goto("http://google.com",{waitUntil:"domcontentloaded"});
                    }catch (e) {
                        console.log(e);
                    }
                }).catch(err => console.log(err));
            }
        },
        async mounted(){
            console.log(puppeteer);
        }
    }
</script>
```

When running the "startBrowser()" method the Puppeteer browser fires up on the server and the "wsEndpoint" is passed with the response. 

The issue is with the "puppeteer.connect" I get the error: TypeError: "puppeteer.connect is not a function". How can i fix? 

When requireing the puppeteer object I get: {__esModule: true, Symbol(Symbol.toStringTag): "Module"}

Hope someone can help me with this, I have been trying for days!

Thanks
Carl

**Comment by jackfranklin** [comment]
Hey Carl,

You need to install `puppeteer-core` from `npm` and use that instead. That file on its own isn't quite all you need. Can you give that a go and do `const puppeteer = require('puppeteer-core')` ?

**Comment by jackfranklin** [comment]
@lazybotter hey, please ignore my last comment. I got myself in a muddle about puppeteer-core vs puppeteer-web. Puppeteer-web is old and not something we currently support so I'm not sure we're going to be able to help you here unfortunately.

**Comment by lazybotter** [comment]
Ok no worries, I decide to build my app with NWJs so can use the standard lib in node context. Thanks anyways 👍
