### ISSUE TITLE
Taking heap snapshot is 5-10X slower in headless mode

### ISSUE THREAD

**Issue by HL87-sys** [puppeteer/puppeteer#5680]
Hey,

**OS:** OSX v10.15.2
**Puppeteer:** v3.0.0
**Node:** v12.6.0

I am trying to get V8 heap snapshots in puppeteer. When `devtools` is set to `true`, each snapshot takes less than 1s, which is great. But when I run it in headless mode, it takes about 12s. That's 10X slower.. When the heap size is big (e.g., 70MB), it could take several minutes. I am using a remote server, which cannot run puppeteer in headful mode.

Is this a bug in puppeteer or headless Chromium? How can I start a headless Chromium with `devtools: true`? Thanks.

I also tried in the following setup and get a similar slowdown:
**OS:** Linux Ubuntu 18.04.4LT
**Puppeteer:** v2.1.1
**Node:** v12.6.0

Here is the code to reproduce it:
```javascript
(async () => {
  const puppeteer = require('puppeteer');
  const browser = await puppeteer.launch({
    devtools: true, // <--------------------- 10X slower when set to false
  });
  const page = await browser.newPage();
  await page.goto('https://www.apple.com');
  
  const start = Date.now();
  const cdpSession = await page.target().createCDPSession();
  cdpSession.on('HeapProfiler.addHeapSnapshotChunk', (data) => {
    // process data ...
  });
  await cdpSession.send('HeapProfiler.takeHeapSnapshot', {
    reportProgress: false,
  });
  await cdpSession.detach();
  const end = Date.now();

  console.log((end - start) + 'ms');
  await browser.close();
})();
```

**Comment by kendalsickels-wf** [comment]
This appears to happen whenever you attempt to take a snapshot with the dev tools panel not open. Running headful chrome with `devtools: false` also results in extreme slowness. I haven't found an option for this yet but is it possible to open the dev tools panel immediately before taking a snapshot as opposed to having it open on launch?
