### ISSUE TITLE
Node unable to find selector

### ISSUE THREAD

**Issue by Kampmann21** [puppeteer/puppeteer#5684]
I'm struggling to find the selectors inside my bank account page. 

I can identify and click the selector #sicherheitButtonId, which corresponds to the button shown on the image.

![css_selector_1](https://user-images.githubusercontent.com/23496126/79697094-008f3a00-8281-11ea-8b29-ed46987b4c82.png)

If I try to click a button inside the drop down menu, I keep getting the error no node found on selector.

The CSS selector looks like this: #sicherheitFormId\:j_id210

I figured this might not be a valid CSS selector, therefore I tried #sicherheitFormIdj_id210, but to no avail.

![css_selector_2](https://user-images.githubusercontent.com/23496126/79697248-ddb15580-8281-11ea-8310-48f4e8da2dd8.png)

Might it have to do with iFrames, nested div structures or CSS non-standard "ZOOM" properties used on that page?

* Puppeteer version: v1.9.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: v12.16.2

**Code**

`const puppeteer = require('puppeteer');

async function getKontoausz() {
  const browser = await puppeteer.launch({ignoreHTTPSErrors: true, headless: false});
  const page = await browser.newPage();

  await page.goto('https://banking.sparda-a.de/spm/?institut=7209');

  await page.type('input[name="LoginForm:userid"]', 'username');
  await page.type('input[name="LoginForm:password"]', 'password');

  await page.click ('#submitLoginForm > img:nth-child(1)');

  await page.waitFor (1500);
 
  await page.click ('#sicherheitButtonId')

  await page.waitFor (1500);

  await page.click ('#sicherheitFormIdj_id210);

  await page.waitFor (1500);

  await page.screenshot({path: './screesnhot_1.png', type: 'jpeg'})

  await browser.close();

}

getKontoausz();`

**What is the expected result?**
Puppeteer selects button in drop down menu.

**What happens instead?**
No node found on for the selector.

Thanks for any hints!

**Comment by Atif252** [comment]
Same problem when I try to fill **BrainTree** from with Puppeteer

**Comment by Kampmann21** [comment]
No longer valid.

**Comment by Shushang1999** [comment]
Hi I am having the same issue I am unable to find element using xpath or id or classname but when I inspect the element it shows the same id , class name and xpath. Can you guide me on how did you solve the issue ? It will be of great help
