### ISSUE TITLE
no ending yarn install - missing processbar while installing with yarn

### ISSUE THREAD

**Issue by muescha** [puppeteer/puppeteer#5685]
### Steps to reproduce

- i run `yarn install`

it stays hours at this place:

```
[4/4] 🔨  Building fresh packages...
[-/50] ⠠ waiting...
[-/50] ⠠ waiting...
[-/50] ⠠ waiting...
[-/50] ⠠ waiting...
[12/50] ⠠ puppeteer
```

also `npm_config_loglevel=warn yarn install` not print any hints whats going on here.

**Tell us about your environment:**

* Puppeteer version: ?? yarn not completes
* Platform / OS version: 10.15.3
* URLs (if applicable): install from gatsby repo
* Node.js version:v12.13.1
* yarn 1.21.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. - i run `yarn install`
2.
3.

**What is the expected result?**

some info what is happening (maybe a download processbar)

**What happens instead?**

i see nothing happening

**Comment by jackfranklin** [comment]
Hey @muescha, do you have a `package.json` file ? Does that list puppeteer (and the version you're using) in it?

**Comment by muescha** [comment]
in `package.json` it is not direct but here:

```shell
$ yarn why puppeteer
yarn why v1.21.0
[1/4] 🤔  Why do we have the module "puppeteer"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "puppeteer@1.20.0"
info Reasons this module exists
   - "_project_#gatsby-plugin-preload-fonts" depends on it
   - Hoisted from "_project_#gatsby-plugin-preload-fonts#puppeteer"
info Disk size without dependencies: "250.89MB"
info Disk size with unique dependencies: "251.71MB"
info Disk size with transitive dependencies: "253.36MB"
info Number of shared dependencies: 35
```

i using this repo: https://github.com/gatsbyjs/gatsby/

**Comment by muescha** [comment]
maybe it was some network glitches, today it works


but the issue here is more what i like to say: 

that with `yarn` do not print progress bar.

so i don't know what is happening and i don't know i just need to wait longer because of slow network/download server

**Comment by jackfranklin** [comment]
@muescha Puppeteer v1 is very out-dated - we just released v3. I'll see if we can get Gatsby (or the plugin) to upgrade their version.

**Comment by muescha** [comment]
that would be good.


but the progressbar is there since version 0.0.1 (https://github.com/puppeteer/puppeteer/commit/2cda8c18d10865d79d3e63b23e36aa7562098bf7)

can you help out how to print the processbar while installing with yarn?

**Comment by jackfranklin** [comment]
I will try to have a look if I get time but I can't make any guarantees. Would welcome any help having a look at this and debugging.

**Comment by LitileXueZha** [comment]
yarn doesn't show logs when install a package, even developer want it.
but npm will, just try `npm i puppeteer`.

take a glance at [this issue](https://github.com/yarnpkg/yarn/issues/5476) may help you.

**Comment by muescha** [comment]
the repo i use need yarn, so i can not install via npm :(
