### ISSUE TITLE
how to fire touch event in page.emulate(iPhone)

### ISSUE THREAD

**Issue by zenxds** [puppeteer/puppeteer#569]
I tried mouse.down but not fire touch event，what should i do

```
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.emulate(iPhone)

await page.mouse.down({ button: 'left' })
```

**Comment by zenxds** [comment]
I tried to enable `Emulation.setEmitTouchEventsForMouse`, touchevent fired but got another issue 

```
await page._client.send('Emulation.setEmitTouchEventsForMouse', {
    enabled: true
  })

await mouse.down({
    button: 'left'
})
```

`mouse.down` will hang up

**Comment by zenxds** [comment]
Thanks a lot. And what i want more is api like `touchScreen.touchStart` `touchScreen.touchMove` `touchScreen.touchEnd` to  emulate drag an element。Could support for it ?

**Comment by JoelEinbinder** [comment]
I'm working on it as part of #158

**Comment by NanYeYe** [comment]
> I tried to enable `Emulation.setEmitTouchEventsForMouse`, touchevent fired but got another issue
> 
> ```
> await page._client.send('Emulation.setEmitTouchEventsForMouse', {
>     enabled: true
>   })
> 
> await mouse.down({
>     button: 'left'
> })
> ```
> 
> `mouse.down` will hang up

@zenxds 请问这个挂起的问题有解吗？
