### ISSUE TITLE
twitch problem

### ISSUE THREAD

**Issue by Rokkiit** [puppeteer/puppeteer#5697]
When i try to watch livestream on twitch using puppeteer i got error #4000, sometimes error #1000 is there any way to fix that?

my simple code for this 

async function main(){
  const browser = await pup.launch({ headless: false})
    const page = await browser.newPage()
    await page.goto('https://www.twitch.tv/anomaly')
}
main()

**Comment by sungwoncho** [comment]
Same here. Is there any chrome flags or headers that puppeteer is injecting that might trigger this? I can confirm that twitch works from a manually launched Chromium.

**Comment by izaiasmachado** [comment]
## Why it happens?
Chromium, used by Puppeteer, does not have de capability of streaming video.

## How I solved?
I was struggling with the same thing, so I develop the following code. For this solution, you have to use Google Chrome. It pretty much does everything you'd want.

- Injects the auth cookie
- Accepts the mature content
- Unmute the stream
- Turn the video quality to the lowest, for purpuses of cpu.

I had to use this for a Headless Linux Machine, my personal Ubuntu Server. But it works for Windows too, I tried myself.

My code actually has more tweeks, but I think this should help you out.

Read the code and feel free to discuss here. 

```js
const puppeteer = require('puppeteer')

const main = async () => {
   const authToken = ""

   const browser = await puppeteer.launch({
        headless: true,
        executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe' // Windows
        // executablePath: '/usr/bin/google-chrome-stable' // Linux
    });
    const cookies = [{
        'name': 'auth-token',
        'value': authToken
    }]

    const page = await browser.newPage()
    await page.goto('https://twitch.tv/gaules')
    await page.evaluate(() => {
        localStorage.setItem('mature', 'true')
        localStorage.setItem('video-muted', '{"default":false}')
        localStorage.setItem('volume', '0.5')
        localStorage.setItem('video-quality', '{"default":"160p30"}')
    })

    await page.setViewport({ width: 1280, height: 720 })
    await page.setCookie(...cookies)
    await page.reload({
        waitUntil: ["networkidle2", "domcontentloaded"]
    })
}
```

**Comment by fattredd** [comment]
Where can I find my auth token?

**Comment by izaiasmachado** [comment]
Hi @fattredd 
I finished my Twitch application and I think I can help you with some reading. For information regarding their API I recommend reading the [official documentation](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth). Remember that for testing you can always get your token from browser cookies. 

Other than that, you should use [Tmi.js](https://github.com/tmijs/tmi.js) to develop your application other than Puppeteer, which isn't the best way to work around this problem. Tmi.js doesn't launch a browser and is really light weight even when you have to work with many accounts. It just launches socket connections using an event pattern.

If you need anything else just talk to me and I'll be glad to help you.

**Comment by JohnDotOwl** [comment]
> Hi @fattredd
> I finished my Twitch application and I think I can help you with some reading. For information regarding their API I recommend reading the [official documentation](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth). Remember that for testing you can always get your token from browser cookies.
> 
> Other than that, you should use [Tmi.js](https://github.com/tmijs/tmi.js) to develop your application other than Puppeteer, which isn't the best way to work around this problem. Tmi.js doesn't launch a browser and is really light weight even when you have to work with many accounts. It just launches socket connections using an event pattern.
> 
> If you need anything else just talk to me and I'll be glad to help you.

Yo, You're 18? Talent, definitely above average

**Comment by forestjaki** [comment]
> ## Why it happens?
> Chromium, used by Puppeteer, does not have de capability of streaming video.
> 
> ## How I solved?
> I was struggling with the same thing, so I develop the following code. For this solution, you have to use Google Chrome. It pretty much does everything you'd want.
> 
> * Injects the auth cookie
> * Accepts the mature content
> * Unmute the stream
> * Turn the video quality to the lowest, for purpuses of cpu.
> 
> I had to use this for a Headless Linux Machine, my personal Ubuntu Server. But it works for Windows too, I tried myself.
> 
> My code actually has more tweeks, but I think this should help you out.
> 
> Read the code and feel free to discuss here.
> 
> ```
> const fs = require('fs')
> const puppeteer = require('puppeteer')
> 
> const main = async () => {
>     const authToken = ""
> 
>    const browser = await puppeteer.launch({
>         headless: true,
>         executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe' // Windows
>         // executablePath: '/usr/bin/google-chrome-stable' // Linux
>     });
>     const cookies = [{
>         'name': 'auth-token',
>         'value': authToken
>     }]
> 
>     const page = await browser.newPage()
>     await page.goto('https://twitch.tv/gaules')
>     await page.evaluate(() => {
>         localStorage.setItem('mature', 'true')
>         localStorage.setItem('video-muted', '{"default":false}')
>         localStorage.setItem('volume', '0.5')
>         localStorage.setItem('video-quality', '{"default":"160p30"}')
>     })
> 
>     await page.setViewport({ width: 1280, height: 720 })
>     await page.setCookie(...cookies)
>     await page.reload({
>         waitUntil: ["networkidle2", "domcontentloaded"]
>     })
> }
> ```

How did you know some propaty ?
mature video-muted volume video-quality
