### ISSUE TITLE
size of pdf and printscreen is different

### ISSUE THREAD

**Issue by bewsbews** [puppeteer/puppeteer#570]
var puppeteer = require('puppeteer');
    module.exports = async function (callback, url, filePrefix) {

    const browser = await puppeteer.launch({
        headless: true
    });

    const page = await browser.newPage();

    
    await page.setViewport({ width: 1920, height: 1080 });
	await page.goto("https://www.svt.se/nyheter/", {waitUntil: 'networkidle'});
    await page.screenshot({path: 'example.png'});
    await page.pdf({ path: 'hn.pdf', printBackground: true, format: 'A4' });

    browser.close();
    }

![example](https://user-images.githubusercontent.com/31002287/29771143-941e4faa-8bf2-11e7-9a3a-0305c3c3f40f.png)
[hn.pdf](https://github.com/GoogleChrome/puppeteer/files/1256586/hn.pdf)

**Comment by JoelEinbinder** [comment]
This looks like it is working as intended. The page size is specified to be `A4`. You can use the `width` and `height` options of pdf to set its size.

```js
await page.pdf({ path: 'hn.pdf', printBackground: true, width: '1920px', height: '1080px'});
```
