### ISSUE TITLE
Dynamic height for footer and header

### ISSUE THREAD

**Issue by ssauriera** [puppeteer/puppeteer#5713]
Hello, 

I would like to ask if it's possible to print an HTML report with dynamic sizes of header and footer. Currently, I must specify the physical dimensions of both in pixels.

My problem is my footer can have differents heights, depending of its contents. If I set, for example, a fixed size of 180 pixels and the footer grows up, body will overlap the footer.

Is there any way to make the header and footer height dynamic so that I can print reports with different header and footer sizes, with a body that just print enough necessary table lines to fit up the whole document size.

Thank you in advance

**Comment by jmcollin78** [comment]
@ssauriera did you finally find a solution to your problem ?

I run in the same case and I cannot find a suitable solution.
Headers and footers are limited to 10px height. If the header / footer content is over 10px, it is cropped.
Any clues to resolve this will be greatly appreciated.

**Comment by jmcollin78** [comment]
I found that header and footer size are managed via the margin values.

I hopes this will help someone else.

**Comment by michelebenolli** [comment]
Why was this issue closed? Adjusting margins in the PDF body does not appear to be a dynamic approach to manage height of header and footer.
