### ISSUE TITLE
Puppeteer not working with node 14

### ISSUE THREAD

**Issue by DRoet** [puppeteer/puppeteer#5719]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:3.0.1
* Platform / OS version:docker (FROM:node:14.0.0-buster)
* URLs (if applicable):
* Node.js version: 14.0.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Upgrade node image from 13.13.0 -> 14.0.0
2. Run same codebase (`puppeteer.launch()`)

**What is the expected result?**
code runs without issues, just like on 13.13.0

**What happens instead?**
`Error: Failed to launch the browser process! spawn /opt/app/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome ENOENT`

**Comment by munrocket** [comment]
@DRoet only with node 14? Try `3.0.1-post`

**Comment by munrocket** [comment]
Try `3.0.1-post`

**Comment by DRoet** [comment]
> @DRoet only with node 14?

yes I just rebuild my images using `12.16.2` and that version also still works

**Comment by DRoet** [comment]
> Try `3.0.1-post`

how do I install this? doesn't seem to be a valid tag on the registry

**Comment by jsoverson** [comment]
It looks like it's a problem with extraction. A temporary workaround is to extract the downloaded chromium manually:

```shell
$ mv node_modules/puppeteer/.local-chromium/mac-737027 node_modules/puppeteer/.local-chromium/mac-737027.bak 
$ unzip node_modules/puppeteer/.local-chromium/chrome-mac.zip -d node_modules/puppeteer/.local-chromium/mac-737027
```

**Comment by nstepien** [comment]
Likely culprit: https://github.com/maxogden/extract-zip/issues/94

**Comment by jackfranklin** [comment]
Thanks for the debugging all; looks like `extract-zip` is indeed the culprit here. It would be nice if Puppeteer gave a more helpful message than `/opt/app/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome ENOENT` so I'll try to look into that.

We'll see if a fix lands in extract-zip and do some digging.

@DRoet you can install via the master branch on GitHub to get the very latest.

**Comment by jackfranklin** [comment]
It also looks like the suspected bug might have been in Node: https://github.com/nodejs/node/pull/32968.

In which case we may have to sit tight for a Node patch release. In the mean time I'll see if the error message from Puppeteer can be nicer.

**Comment by jackfranklin** [comment]
I have opened https://github.com/puppeteer/puppeteer/pull/5732 which at least fixes the silent failures and provides a helpful message.

**Comment by RollsBean** [comment]
Same issue troubled me, `puppeteer` `v3.0.1` doesn't support Node `v8.14`, i reduced the puppeteer version and it worked, but i don't what is the node minimum version of each `puppeteer` version.

**Comment by leecade** [comment]
same here

**Comment by AviVahl** [comment]
Fixed by Node 14.1.0. Verified on Linux/Mac/Windows.

**Comment by AviVahl** [comment]
Alright, it failed once in one of our projects because of the (node14-specific) timeout that was added to the extraction process. 10s is too low for our CI.

Workaround bites back. Any chance for it to be removed, now that Node is fixed?

FYI @jackfranklin

**Comment by DRoet** [comment]
Can confirm it is working again on `14.1.0`, but the new node14 timeout indeed fails sometimes on slower CI runs.

**Comment by nstepien** [comment]
It's also intermittently failing for us because of the short timeout.

**Comment by AviVahl** [comment]
@mathiasbynens saw you've just released a patch version which still has this issue. any chance for another one with the node14-specific-timeout removed? :) this is what blocks me from adding Node 14 tests to several projects.

**Comment by rootlinux2** [comment]
Hi guys, 
I'm facing similar problem I just installed Puppeteer but when I run node index.js nothing happens.
![image](https://user-images.githubusercontent.com/24574267/88054943-2cde7f00-cb2c-11ea-9de6-e26f0415ecf9.png)
 "puppeteer": "^5.2.0"
  node v14.5.0
This is the content of index.js
![image](https://user-images.githubusercontent.com/24574267/88055101-6b743980-cb2c-11ea-8908-8309d7c653d1.png)
