### ISSUE TITLE
Script evaluation throws sometimes with SyntaxError

### ISSUE THREAD

**Issue by jesusbotella** [puppeteer/puppeteer#572]
Hi!

I am experiencing an error when evaluating a script that _only sometimes_ throws an `Evaluation failed: SyntaxError: Unexpected token ,` error. It happens with several pages, not only one, and with and without headless mode.

I think it may be something from my code or the script that is evaluated but I couldn't find any clue to know why this is happening.

The puppeteer code is:

```js
const findImages = ('../browser/findImages');
const page = await browser.newPage();

await page.goto('http://www.mybkr.com/shop/#/productdetail/303/SPIKED_JET_500_ML', { waitUntil: 'networkidle' });

const images = await page.evaluate(findImages);

await page.close();
```

Debug in console shows this information about the error:
```js
puppeteer:protocol ◀ RECV {"method":"Target.receivedMessageFromTarget","params":{"sessionId":"78f7628f-712c-4339-a758-d4bd7288aff1:1","message":"{\"id\":24,\"result\":{\"result\":{\"type\":\"object\",\"subtype\":\"error\",\"className\":\"SyntaxError\",\"description\":\"SyntaxError: Unexpected token ,\",\"objectId\":\"{\\\"injectedScriptId\\\":3,\\\"id\\\":8}\"},\"exceptionDetails\":{\"exceptionId\":1,\"text\":\"Uncaught\",\"lineNumber\":199,\"columnNumber\":3,\"scriptId\":\"47\",\"exception\":{\"type\":\"object\",\"subtype\":\"error\",\"className\":\"SyntaxError\",\"description\":\"SyntaxError: Unexpected token ,\",\"objectId\":\"{\\\"injectedScriptId\\\":3,\\\"id\\\":9}\"}}}}","targetId":"78f7628f-712c-4339-a758-d4bd7288aff1"}}
puppeteer:session ◀ RECV {"id":24,"result":{"result":{"type":"object","subtype":"error","className":"SyntaxError","description":"SyntaxError: Unexpected token ,","objectId":"{\"injectedScriptId\":3,\"id\":8}"},"exceptionDetails":{"exceptionId":1,"text":"Uncaught","lineNumber":199,"columnNumber":3,"scriptId":"47","exception":{"type":"object","subtype":"error","className":"SyntaxError","description":"SyntaxError: Unexpected token ,","objectId":"{\"injectedScriptId\":3,\"id\":9}"}}}}
Error: Evaluation failed: SyntaxError: Unexpected token ,
    at Frame._rawEvaluate (/Users/jesus/Development/headless/node_modules/puppeteer/lib/FrameManager.js:231:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

I tried to find that line in the code that we inject/evaluate and I found nothing, the line number does not match any code, there is no file that long.

The thing is that it throws at random times, sometimes it returns the result and sometimes it throw with the same code.

Can you give me a clue or direction to debug the issue? Could it be that sometimes the script is not completely injected?
Thank you!

**Comment by aslushnikov** [comment]
@jesusbotella Could you please share the source of `findImages` file?

**Comment by jesusbotella** [comment]
@aslushnikov I'm afraid I cannot share the code here, but if you want to I am authorized to share it to you by email? What do you think?

**Comment by aslushnikov** [comment]
@jesusbotella sg, my email is lushnikov@chromium.org

**Comment by jesusbotella** [comment]
@aslushnikov I sent you a mail :)

**Comment by justincy** [comment]
For anyone who stumbles upon this problem while waiting for the bugfix to be released, it occurs when there are two or more arguments passed to evaluate and at least one of them is undefined. Despite the commit message saying it only fixes the case there the first arg is undefined, it actually solves all cases of any args being undefined.
