### ISSUE TITLE
FileChooser does not include the file's mime type in the event

### ISSUE THREAD

**Issue by macadev** [puppeteer/puppeteer#5728]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: mac OS Mojave - 10.14.6
* Node.js version: v13.12.0

**What steps will reproduce the problem?**

Thanks for all the hard work team. I love puppeteer. The issue I'm facing is that when using fileChooser to upload a file to \<input type="file"\> tags the event emitted doesn't include the file's mime type. Here's what I do in puppeteer:

```javascript
const [fileChooser] = await Promise.all([
      this.page.waitForFileChooser(),
      this.page.click('input[type="file"]'),
]);
await fileChooser.accept(['/tmp/pptr_devs_rock.png']);
```

My application code tries to parse the event and obtain the mime type:

```javascript
const file = event.target.files[0];
console.log(file.type);
```

This is what's logged when I run the code from above:

```javascript
File {
  name: "pptr_devs_rock.png",
  lastModified: 1587644046388,
  size: 20862,
  type: "",
  ...
}
```

When I **manually** select a file to be uploaded the event does have a defined 'type' property: 

```javascript
File {
  name: "pptr_devs_rock.png",
  lastModified: 1587644046388,
  size: 20862,
  type: "image/png", // What I want!
  ...
}
```

**What is the expected result?**

The file type is available when uploading a file using FileChooser.

**What happens instead?**

The file type is not available.

I'm not 100% certain this is a puppeteer problem, but after extensive searching I've come to believe that it is. Any help is greatly appreciated.

**Comment by mathiasbynens** [comment]
Can you try `puppeteer@3.0.1`? It included some fixes involving file uploads. Please let us know if the issue still exists in v3.0.1. cc @paullewis

**Comment by macadev** [comment]
You people are amazing! 3.0.1 fixed the issue. This is the quickest turn around I have ever experienced. Thank you!

**Comment by mathiasbynens** [comment]
Glad to hear :)
