### ISSUE TITLE
Any way to listen to events from the page?

### ISSUE THREAD

**Issue by Madd0g** [puppeteer/puppeteer#573]
Imagine there's something on the page that's happening on its own, maybe a video is playing or ajax calls happening on interval.

Is there a way, without polling, to push events back to puppeteer from the page? My goal is to inject some code from puppeteer into my page that will be able to independently send events back.

Is this possible?

p.s. I was also wondering about `postMessage`, would be nice to be able to hook up to that on frames.

**Comment by vsemozhetbyt** [comment]
Maybe [page.exposeFunction()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction) can help?

**Comment by ebidel** [comment]
We have [an example](https://github.com/GoogleChrome/puppeteer/blob/master/examples/custom-event.js) for this now! It shows how to listen for custom events fired on the page and pipe them back through puppeteer code.

> My goal is to inject some code from puppeteer into my page that will be able to independently send events back.

Yep, `page.exposeFunction()` is perfect for this use case.

**Comment by Madd0g** [comment]
perfect, thanks!

**Comment by Nicusor-Stoica** [comment]
Sorry for bringing this thread back from the dead, but that example is not working, even with `{headless : false}` .. it just closes as soon as the page is loaded.

**Comment by agugut** [comment]
0


Hello Team I need to add this code to a puppeteer test to listen in the page that I'm working the messages that the page which is opened automatically
```
window.addEventListener('message', event => {
            console.log(event
  });
```
I Try to use this code https://github.com/puppeteer/puppeteer/blob/main/examples/custom-event.js but this is not suitable for me. Any idea? Thanks
