### ISSUE TITLE
v3 renders sliders and select items incorrectly

### ISSUE THREAD

**Issue by mmakrzem** [puppeteer/puppeteer#5738]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.1
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 12.16.2

**What steps will reproduce the problem?**

I've noticed that a standard input slider and select group no longer render in the same way that they did in puppeteer v 2.1.1

```
<input type="range" value="0">
  
  <select>
  	<option>A</option>
  </select>
```

In v2.1.1 they used to render like this:
![testDefault](https://user-images.githubusercontent.com/1681264/80289590-66f6db00-870d-11ea-9839-be96211755d3.png)
![testDecreaseLengthFx](https://user-images.githubusercontent.com/1681264/80289596-770eba80-870d-11ea-9cab-f2f6dde2bbe6.png)

In v3.0.1
the slider looks like this (blue circle rather than grey rectangle thumb):
![testDefault](https://user-images.githubusercontent.com/1681264/80289603-8aba2100-870d-11ea-8dba-3883b8a6b9d9.png)
and the select group looks like this (not shape of downward arrow):
![testDecreaseLengthFx](https://user-images.githubusercontent.com/1681264/80289618-af15fd80-870d-11ea-99b6-7099323aed39.png)

I'm using puppeteer to capture screenshots in my test framework, but now all my tests are failing because the slider and selector look different.  How can I get them to render normally again?

**Comment by SimonSchick** [comment]
I believe this to be correct, see https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html
