### ISSUE TITLE
Fonts and widgets sometimes don't load

### ISSUE THREAD

**Issue by cronfy** [puppeteer/puppeteer#574]
I am using puppeteer to take screenshots of web pages at various resolutions.

There are problems:

 1. Sometimes fonts (from fonts.google.com) are not loaded.
 2. Sometimes widgets like facebook are represented as white squares (this means that widget script was loaded, but it did not load/render it's content).

Second problem was resolved by `networkIdleTimeout: 3000`. But I don't understand why it does not work with `networkIdleTimeout: 1000`. If I open same page in desktop Chrome with DevTools, I see (by waterfall) that all resources are loaded one by one without pauses until page is completely rendered.

And `networkIdleTimeout: 3000` does not help with fonts - sometimes I get screenshots with default fonts instead of linked via CSS.

How would I reliably detect that all page content is completely rendered? If I'd know that, I could, well, 'reload' the page to try again automatically.

Here is a simplified code:

```
const page = await browser.newPage()
await page.setViewport({width: width, height: 0})
for (const webpage of pages) {
    await page.goto(webpage.url, {waitUntil: 'networkidle', networkIdleTimeout: 3000 })
    await page.screenshot({path: `screenshots/${webpage.name}.png`, fullPage: true})
}
await page.close()
```

**Comment by aslushnikov** [comment]
@cronfy can you share the URLs of the pages you try to screenshot?

**Comment by cronfy** [comment]
Hmm, it is local.. I temporarily uploaded it here:

 * http://cronfy.ru/template/main.html - here I noticed problems with fonts at 320px/480px
 * http://cronfy.ru/template/contacts.html - here with VK and Facebook widgets at 1920px

Here is also an attach: 
[pages.tar.gz](https://github.com/GoogleChrome/puppeteer/files/1257833/pages.tar.gz)


Environment:

```
$ yarn list puppeteer
yarn list v0.27.5
└─ puppeteer@0.10.1

$ cat /etc/issue
Linux Mint 17.3 Rosa \n \l
```

**Comment by aslushnikov** [comment]
@pavelfeldman, would lifecycle events help in this case too?

**Comment by aslushnikov** [comment]
@cronfy this might work now with tip-of-tree puppeteer (v0.13.0). 

I'd appreciate if you can try and write back the results.
