### ISSUE TITLE
Simplify downloading multiple browsers

### ISSUE THREAD

**Issue by timvandermeij** [puppeteer/puppeteer#5743]
I'm introducing Puppeteer for Mozilla's PDF.js project in https://github.com/mozilla/pdf.js/pull/11807. One can use the `PUPPETEER_PRODUCT` environment variable to control which browser is downloaded, but `npm install` will always install either Chrome or Firefox. Is it possible to change this so that, for example, `PUPPETEER_PRODUCT` accepts a comma-separated list instead?

Now we install Puppeteer, which downloads Chrome, and have a separate post-install step that re-runs the Puppeteer installation script with `PUPPETEER_PRODUCT=firefox` to download Firefox too. This feels hacky.

**Comment by linquize** [comment]
I suggest to add a script to download an additional browser after the first `npm install puppeteer` is called.

**Comment by jackfranklin** [comment]
We have to do this same hack in our CI too and I agree it would be nicer to not do this.

I like the idea of the install script supporting a list of browsers. WDYT @mathiasbynens ?

**Comment by mathiasbynens** [comment]
The plan is for `npm i puppeteer` to auto-install all supported browsers. The only reason that’s not happening yet for Firefox because its support is still experimental. cc @mjzffr

**Comment by linquize** [comment]
```bash
npm install puppeteer
```
This will install puppeteer and download chromium by default.
Chromium will be put in `node_modules/puppeteer/.local-chromium`

```bash
cd node_modules/puppeteer
PUPPETEER_PRODUCT=firefox node install.js
```
This will download firefox.
Firefox will be put in `node_modules/puppeteer/.local-firefox`

**Comment by tukusejssirs** [comment]
I my opinion, browsers should be separate packages and _no_ browser should be installed by default. That way one could install one, many or all browsers supported by Puppeteer.

It would also solve the issue with browser versions. One might want to install the latest version, others an exact version they have tested with their app.

---

Related: #6680, #6586, #6894, #6371, #6283
