### ISSUE TITLE
headles timeouts, headed works fine

### ISSUE THREAD

**Issue by hikeislife** [puppeteer/puppeteer#5744]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.1
* Platform / OS version: windows 7
* URLs (if applicable): https://covid19.rs/ (but seems to be the case with other url's too)
* Node.js version: 12.14.1

it's the most basic setup, no code to share

**What is the expected result?**

in headless mode, page.goto() times out, but if headless: false is used, returns proper result within reasonable time frame.

**Comment by shubhams** [comment]
I don't know why, but when I install the Puppeteer version **2.0.0**, the problem seems to go away. Maybe, it's the Chromium version that is shipped with `puppeteer@2.0.0`.
