### ISSUE TITLE
chrome-win.zip not extracted during installation

### ISSUE THREAD

**Issue by shawnkhall** [puppeteer/puppeteer#5745]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.1
* Platform / OS version: Win64 v1909 (multiple devices)
* URLs (if applicable): 
* Node.js version: 14.0.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. npm i puppeteer
2. node demo.js

demo.js is:
```javascript
const puppeteer = require('puppeteer');
(async () => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.goto('https://example.com/');
 	await browser.close();
})();
```

**What is the expected result?**

Install puppeteer into "node_modules" as well as download and extract the current chrome-win.zip to `node_modules/puppeteer/.local-chromium/win64-nnnnnn/chrome-win`.

**What happens instead?**

Puppeteer is installed to `node_modules` and the current chrome-win.zip is downloaded to `node_modules/puppeteer/.local-chromium`, but *only* the manifest file is extracted to `node_modules/puppeteer/.local-chromium/win64-nnnnnn/chrome-win`. 

When attempting to run any script with a puppeteer dependency at this point results in the following error:
    *(node:2116) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn .\node_modules\puppeteer\.local-chromium\win64-nnnnnn\chrome-win\chrome.exe ENOENT*

Manually extracting chrome-win.zip to the chrome-win folder allows the script to operate as expected.

**Comment by jackfranklin** [comment]
@shawnkhall unfortunately Puppeteer does not yet work on Node 14 (see https://github.com/puppeteer/puppeteer/issues/5719).
