### ISSUE TITLE
guys..i have been using the puppeteer...and my aim is to achieve a different functionality when a alert message is shown because when the alert message is shown the actual selector tags(labels) will not be loaded and i am ending with time out error...can any one please help with this

### ISSUE THREAD

**Issue by umakanth-pendyala** [puppeteer/puppeteer#5754]
for (var i = 1; i <= semSetNo; i++) {
        //try {
        console.log(i);
        await page.type("#txtreg", rollNo);
        await page.select("#cbosem", i.toString());

        await page.waitForSelector("#Button1");
        await Promise.all([await page.click("#Button1")]);

      
        

        await page.waitForSelector("#lblgpa");
        await page.waitForSelector("#lblcgpa");
        var getData = await page.evaluate(() => {
          const gpa = document.querySelector("#lblgpa").innerHTML;
          const cgpa = document.querySelector("#lblcgpa").innerHTML;
          var scriptObject = {
            gpa: gpa,
            cgpa: cgpa,
          };
          return scriptObject;
        });
        console.log(getData);
        temp.push(getData);
        await page.waitForSelector("#Button1");
        await Promise.all([await page.click("#Button1")]);

      

        // } catch (error) {
        //   break;
        // }
      }

      var labels = [];
      var gpas = [];
      var cgpas = [];

      for (var i = 0; i < temp.length; i++) {
        temp[i].sem = "sem " + (i + 1);
        labels[i] = temp[i].sem;
        gpas[i] = temp[i].gpa;
        cgpas[i] = temp[i].cgpa;
      }
      console.log(labels, gpas, cgpas);
      console.log(temp);
      // console.log("GPA :\t" + JSON.stringify(results));
      // await page.screenshot({ path: "shot.png" });
      await browser.close();

**Comment by CedricBrandt** [comment]
I didn't look into your code much but I think to answer this I don't need to. I'm not quite sure if you mean an actual javascript alert message box or a css box. Either way this is simple to achieve: 

Css box:
Wait for both and mute the error of the one not showing up (preferably you choose timeouts for the waiting calls as small as possible) 
```
let boxShown = false;
await Promise.race([
    page.waitForSelector('box not shown').catch(),
    page.waitForSelector('box shown').then(()=>{boxShown = true}).catch()
]);
```

Alert:
You might wanna look into
`page.on('dialog', async dialog=>{}) `

**Comment by jackfranklin** [comment]
Hello, StackOverflow is a better place to get help using Puppeteer - I'd post there if you're still having problems. Thanks :)
