### ISSUE TITLE
Allow bypassing CSP in Firefox

### ISSUE THREAD

**Issue by l-abels** [puppeteer/puppeteer#5755]
When I switched to using Firefox with `puppeteer`, I began encountering `Evaluation failed: call to Function() blocked by CSP` in all of my tests.  I tried using `page.setBypassCSP(true)`, however that results in the following error:

```
    Protocol error (Page.setBypassCSP): Page.setBypassCSP RemoteAgentError@chrome://remote/content/Error.jsm:25:5
    UnknownMethodError@chrome://remote/content/Error.jsm:108:7
    execute@chrome://remote/content/domains/DomainCache.jsm:96:13
    receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:69:45
    MessageListener.receiveMessage*ContentProcessSession@chrome://remote/content/sessions/ContentProcessSession.jsm:27:25
    @chrome://remote/content/sessions/frame-script.js:12:1
```

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.1

**What steps will reproduce the problem?**

1. Navigate to any page with CSP enabled
2. `await page.waitForXPath ('Any XPath)';`

**What is the expected result?**

Produces the same behavior as `product: chromium`

**What happens instead?**

See error message above.

**Comment by mtatarau90** [comment]
same error here.

**Comment by mjzffr** [comment]
Thanks for the report. The implementation of `Page.setBypassCSP` in Firefox is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1549481

If you'd like to tell the team about how your project is using Puppeteer, it might help us prioritize upcoming work on Firefox support. You can reach out at https://wiki.mozilla.org/Remote

**Comment by kayleewright-bluescape** [comment]
Is there any workaround for this?

**Comment by Kiro369** [comment]
I've same problem, any workarounds?

**Comment by serg06** [comment]
STILL same problem, cannot use Firefox, any workaround?

**Comment by gotshadowbantempaccount** [comment]
LOL still no fix i know some important issue on Firefox got 15 years old - and then they cry why nobody use Firefox go woke go broke

**Comment by olsonpm** [comment]
For anyone still looking for a workaround, I [created a linux x86_64 build](https://github.com/olsonpm/gecko-dev/releases/tag/add-security-csp-enable_v0-1) which adds back the preference and got this working with puppeteer.

If you need it built for another target you should be able to pull my branch and build.  The build took around 20 minutes on my machine and mozilla's directions are mostly straight forward.
