### ISSUE TITLE
cannot use existing chrome session

### ISSUE THREAD

**Issue by ORESoftware** [puppeteer/puppeteer#5756]
I have this script:

```typescript
#!/usr/bin/env node
'use strict';

import * as  puppeteer from 'puppeteer-core'

(async () => {
  ///
  const browser = await puppeteer.launch({
    headless: true,
    executablePath: '/usr/bin/google-chrome',
    userDataDir: '/home/oleg/.config/google-chrome/Profile 1'
  });
  

  const page = await browser.newPage();
  await page.goto('https://meet.google.com');
  await page.setJavaScriptEnabled(true);

  {
    const joinOrStartMeeting = '/html/body/div[1]/c-wiz/div/div/div/div[2]/div[2]/div[2]/div/c-wiz/div/div/div/div[1]';
    await page.waitForXPath(joinOrStartMeeting, {timeout: 2000})
    const elements = await page.$x(joinOrStartMeeting);
    await elements[0].click();
  }

  {
    const continueBtn = '/html/body/div[1]/div[3]/div/div[2]/span/div/div[4]/div[2]/div/span/span';
    await page.waitForXPath(continueBtn, {timeout: 2000})
    const elements = await page.$x(continueBtn);
    await elements[0].click();
  }

  {
    const linkText = '/html/body/div[1]/c-wiz/div/div/div[3]/div[3]/div/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div/div[1]';
    await page.waitForXPath(linkText, {timeout: 2000})
    const elements = await page.$x(linkText);
    const title = await page.evaluate(el => el.innerHTML, elements[0]);
    console.log('title:', title);
  }
  await browser.close();
})()

```

I just want a way to quickly get a new ghangouts link. But this script doesn't work b/c I am not actually logged in, tmk. It's an anonymous chrome session, does not seem to use an existing session.

I understand there are some open issues for this including #411, but this doesn't seem to work, so just going to open a new ticket in protest.

**Comment by usamaejaz** [comment]
@ORESoftware I don't think Google products work in puppeteer. 

1. You cannot log-in to @gmail.com account on any Google product.
2. Even if you have an active session, Google will block the session and pretend as if you are logged out. 

That happened for me.

**Comment by DevKoenv** [comment]
you can use `puppeteer-extra-plugin-stealth`

**Comment by usamaejaz** [comment]
@GamingMineblox that also doesn't work for google sessions.

**Comment by DevKoenv** [comment]
@usamaejaz sorry I misread it. I thought that you said that you were unable to login into any Google products (I thought that you went if you use puppeteer browser)
