### ISSUE TITLE
page.pdf throws

### ISSUE THREAD

**Issue by Aralic** [puppeteer/puppeteer#576]
Puppeteer: 0.10.1
Node: v8.2.1.
OS: macOS Sierra 10.12.1 (16B2657)

# Setup

```javascript
const puppeteer = require('puppeteer');
const devices = require('puppeteer/DeviceDescriptors');

(async() => {

    const browser = await puppeteer.launch({
        headless: false
    });

    const page = await browser.newPage();

    await page.goto('https://www.baidu.com/', {
        waitUntil: 'networkidle'
    });

    console.log('start');

    await page.pdf({path: './1.pdf'});

    console.log('end');

})();
```

# Error

`(node:754) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Page.printToPDF): PrintToPDF is not implemented undefined

(node:754) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ebidel** [comment]
There's a note in the docs that's hard to miss:

> NOTE Generating a pdf is currently only supported in Chrome headless.

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions

**Comment by Aralic** [comment]
@ebidel thanks. I try agian, It's effective.
