### ISSUE TITLE
Choose browser platform

### ISSUE THREAD

**Issue by tiago-ctw** [puppeteer/puppeteer#5770]
As far as I know there have been some related feature requests already about providing more flexibility to choose the browser that puppeteer downloads.

My particular request is about providing a way to tell puppeteer (on install) which **browser platform** to use. BrowserFetcher on install.js defaults to current platform but it would be great to pass the platform to it, probably through another env variable.

The motivation is the same as other related requests, automation.

Thank you!

**Comment by linquize** [comment]
See also #5743
