### ISSUE TITLE
How to use puppeteer without nodejs and vscode ?

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#5772]
Hi everyone,
I have made a bot to automate a task using puppeteer and nodejs, but i want to use this on another computer where we dont have vscode etc. Is it possible to use puppeteer without it, may be chrome extension or a webpage with node installed on remote server, kindly help me.

**Comment by namename-123** [comment]
Convert it to .exe

**Comment by vickyRathee** [comment]
You can use https://chrome.agenty.com/

![puppeteer without nodejs](https://user-images.githubusercontent.com/6106479/80914672-af944100-8d6a-11ea-8dfe-d37d7e316980.png)
