### ISSUE TITLE
Is there a way to open local pages?

### ISSUE THREAD

**Issue by vlad-zhukov** [puppeteer/puppeteer#578]
I would like to open a page that includes CSS and JS files. Is it possible?

**Comment by ebidel** [comment]
Yes, this is possible. Generally, if you can open the page in Chrome, you can open the page using puppeteer :)

```js
await page.goto('file:///Users/.../page.html');
```

Just keep in mind that [`file://` has some security restrictions](https://stackoverflow.com/questions/29371600/chrome-browser-security-implications-of-allow-file-access-from-files). Depending on what the page does, not everything will work.

**Comment by MuYunyun** [comment]
It do effect:

```js
const url = `file://${process.cwd()}/...`
```
