### ISSUE TITLE
Restore page.userAgent tests

### ISSUE THREAD

**Issue by mathiasbynens** [puppeteer/puppeteer#5781]
https://github.com/puppeteer/puppeteer/pull/5780 disabled another page.userAgent test that appeared to flake in Firefox on the bots, e.g. here: https://travis-ci.com/github/puppeteer/puppeteer/jobs/325068079#L267

@mjzffr @whimboo Could you please take a look?

**Comment by whimboo** [comment]
@mathiasbynens can you give some links to such broken Travis CI jobs? We have a [very low intermittent faiilure](https://bugzilla.mozilla.org/show_bug.cgi?id=1635604) for the moment, but if that fails permanently something else is going wrong.

**Comment by mathiasbynens** [comment]
The link in OP used to point to such an example, but I guess restarting the CI job cleared the faulty output :( I looked but now cannot quickly find any other examples. Let’s close this for now.
