### ISSUE TITLE
possible queryObjects() regression in v3

### ISSUE THREAD

**Issue by chrisguttandin** [puppeteer/puppeteer#5788]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v3.0.2 (the problem exists since v3)
* Platform / OS version: macOS v10.14.6
* URLs (if applicable): https://github.com/chrisguttandin/standardized-audio-context/blob/master/test/memory/module.js
* Node.js version: v12.16.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Clone the repo https://github.com/chrisguttandin/standardized-audio-context
2. Install the dependencies `npm ci`.
3. Run the tests `grunt sh:test-memory`. The tests should pass.
4. Update puppeteer `npm i puppeteer@3`
5. Run the tests again `grunt sh:test-memory`. The tests should fail now.

**What is the expected result?**

I would expect the tests to pass before and after the update.

**What happens instead?**

The tests do fail. The number of objects returned by queryObjects() has changed.

The version of Chromium used before the update is r722234. The version downloaded by v3 is r737027.

My memory leak tests do test very complicated code which is why I'm not sure where the actual regression is. It could very well be a change in Chrome's Web Audio implementation which has nothing to do with puppeteer. I hope we can somehow debug this together. Please let me know what I can do to make this easier to reason about.

Is it for example possible to use puppeteer v2.x with the latest version of Chromium to check if the regression is inside of Chrome or puppeteer?

**Comment by chrisguttandin** [comment]
I just tested this with v4 and v5 of puppeteer. Unfortunately they all behave the same and the regression still persists.

**Comment by chrisguttandin** [comment]
I meanwhile updated to puppeteer to v5 and fixed the problem by [triggering the garbage collection manually](https://github.com/chrisguttandin/standardized-audio-context/commit/4d1da81029c222beb694b9aa1a06e5159f78d04f). However I still think this is a regression as I would expect `queryObjects()` to clean up the memory itself before querying the objects.

**Comment by chrisguttandin** [comment]
Unfortunately the problem still persists in v15.5.0.

**Comment by chrisguttandin** [comment]
I agree, it's difficult to say if the regression was introduced by changes in Puppeteer or Chromium itself. And even if it was Chromium it could be the `queryObjects()` API or the Web Audio API itself.

But since it works when calling the garbage collection explicitly a couple of times I thought the chances are high that `queryObjects()` somehow doesn't trigger a full garbage collection anymore before returning the results. Does that make sense?

**Comment by OrKoN** [comment]
I know that there are multiple phases/modes of gc and perhaps something has changed in V8. Naively looking at the code it appears as if it should gc'ed before querying objects https://source.chromium.org/chromium/chromium/src/+/main:v8/src/profiler/heap-profiler.cc;l=275;drc=13dced01cce80364299ad7663479ad65069db73d

**Comment by chrisguttandin** [comment]
I tried to dig into the code to find out if `GarbageCollectionReason::kHeapProfiler` somehow causes a major garbage collection run. But I couldn't find anything. Obviously that doesn't mean that it isn't doing it. I definitely don't claim to fully understand that code.

**Comment by OrKoN** [comment]
It does not look like we will be able to look into that. Would you mind filing an issue for crbug.com if it is still a problem? Puppeteer only queries `Runtime.queryObjects` and the implementation is in v8.
