### ISSUE TITLE
fetch doesn't work with proxies

### ISSUE THREAD

**Issue by namename-123** [puppeteer/puppeteer#5791]
```javascript
const HttpProxyAgent = require('http-proxy-agent');
const puppeteer = require('puppeteer');
async function run () {
    const browser = await puppeteer.launch({headless: false, slowMo: 10});
    page = await browser.newPage();
    await page.setRequestInterception(true);
    var Agent = new HttpProxyAgent('http://user:pass@ip:port');

    await page.evaluate((Agent) => {
        fetch('https://api.ipify.org?format=json', {agent: Agent}).then(response => response.json()).then(data => console.log(data))
    }))
```

The result is my real IP, instead of the proxy's. And I don't think there's anything wrong with my code, so could it be that fetch just refuses to use proxies?

**Comment by namename-123** [comment]
Hello can someone reply?

**Comment by ordimans** [comment]
Does't it work with socks5 proxy ?

**Comment by odysseymemoirs** [comment]
when fetching inside `page.evaluate()` it calls browsers fetch api which does not support proxies and there is on `agent` option,
you have to use proxy at puppeteer level, for example https://www.npmjs.com/package/puppeteer-page-proxy, which will proxify all request including page.evaluate's requests
