### ISSUE TITLE
Chrome Remains in the Ubuntu Background with Memory Use.

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#5795]
Puppeteer doesn't close the chrome headless browser.
Chrome Headless Remains in the background and it uses a lot of RAM from my Ubuntu Server.

I have added browser.close() after browser.open()

This is the code for puppeteer part.

` const browser = await puppeteer.launch({
      args: ['--no-sandbox']
});
const page = await browser.newPage();
...............................................................................
await browser.close();
`

![RAM](https://user-images.githubusercontent.com/60402458/80792455-21497080-8b5a-11ea-9b6c-0a05f8e14d71.png)

I think there would be a way for this

Looking forward to your help

Thanks

**Comment by ronaldohoch** [comment]
It's bring down my server today! :/

**Comment by ghost** [comment]
I have resolved this issue... 
Now it works fine.

**Comment by akshay-daffodil-93** [comment]
@george19871205 Can you please tell us how did you fixed this issue?

**Comment by ghost** [comment]
@akshay-daffodil-93, you need to get the pid for each puppeteer browser.
You can get it using this code

`pid = browser.process().pid`

Once you get this you can kill the process once you complete the process

Hope it helps your issue.
