### ISSUE TITLE
Page crashed! When there are multiple calls with large pages.

### ISSUE THREAD

**Issue by sinahwz** [puppeteer/puppeteer#5797]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: Docker container based on node:10-slim, Using ECS and Fargate
* URLs (if applicable):
* Node.js version: 10

**What steps will reproduce the problem?**

1.  Having an express server, and making multiple parallel calls
2.   `--disable-dev-shm-usage` is included when launching the browser.
3.   Tried also with the latest stable version of Chrome as in [https://github.com/puppeteer/puppeteer/issues/2725](2725)

**What is the expected result?**
Page should not crash

**What happens instead?**
Randomly getting `Page crashed!` for the same page

**Comment by munrocket** [comment]
If you can reproduce a bug, can you please find exact PR @sinahwz ?
I am also have some crashes in v3.

**Comment by smyth64** [comment]
I have the same problem. It just started when I rebuild my Dockerfile completely. I guess it has something to do with the Google Chrome Version

**Comment by munrocket** [comment]
@smyth64 can you reproduce this bug? This is probably appeared after typescript migration.

**Comment by smyth64** [comment]
It has nothing to do with puppeteer.

I found the problem, it's the Chrome Version.

I downgraded to 77.0.3824.6 and now everything works like before... Phew I'm so happy now!!! 
Spend > 12h on this problem.

Installing older Chrome Versions can be a hazzle, so here is the important part of my Dockerfile :)

```
RUN apt-get update && apt-get install -yq gdebi libgconf-2-4

ENV CHROME_VERSION=77.0.3824.6

RUN  apt-get update \
     && apt-get install -y wget gnupg ca-certificates apt-transport-https \
     && apt-get update -qqy \
     && wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-unstable/google-chrome-unstable_${CHROME_VERSION}-1_amd64.deb \
     && yes | gdebi google-chrome-unstable_${CHROME_VERSION}-1_amd64.deb

RUN google-chrome-unstable --version
```

**Comment by munrocket** [comment]
By the way, I am upgraded to puppeteer@3.1.0 and all is ok for me now.
