### ISSUE TITLE
waitForSelector failed for a popup element in headless mode

### ISSUE THREAD

**Issue by playgithub** [puppeteer/puppeteer#5802]
WebPage: http://www.cninfo.com.cn/new/index
Type something in the search box, it'll pop up a candidate window.
![Capture](https://user-images.githubusercontent.com/3665590/80944411-1a518500-8e1c-11ea-8878-6807139c9744.PNG)
While not in headless mode, it's successful to waitForSelector for the element marked with red pen.
But in headless mode, it failed.

**Comment by DaYesahh** [comment]
I have the same problem in react project.
