### ISSUE TITLE
How to copy data from Excel to Clipboard and paste in the browser using Pupeteer?

### ISSUE THREAD

**Issue by VertikaGoyal** [puppeteer/puppeteer#5803]
Using pupeteer , I want to test if an application executes its functionality correctly when data is copied from an Excel sheet into the browser  window of the application.I am able to read data from the Excel sheet, but not able to copy that data into the clipboard and then paste it into the browser window.
 
 beforeAll(async () => {
        browser = await common.getBrowser();
		page = (await browser.pages())[0];
        await common.logIn(process.env.USERNAME, process.env.PASSWORD, page);
    }, common.MAX_WAIT_TIME_OUT);

    afterAll(async () => {  
	await browser.close();
    }, common.GENERAL_WAIT_TIME);
	
	it('read-excel and print', async() => {
        jest.setTimeout(100000);
		 const XLSX = require('xlsx');
         myDataWorkbook = XLSX.readFile(filePath);
		 
		console.log(XLSX.utils.sheet_to_json(myDataWorkbook.Sheets[sheetName]));		// getting the correct data here 
        console.log(XLSX.utils.sheet_to_txt(myDataWorkbook.Sheets[sheetName]));			// getting the correct data here 
        console.log(XLSX.utils.sheet_to_csv(myDataWorkbook.Sheets[sheetName]));			// getting the correct data here 
		});

**Comment by Kripu77** [comment]
Have you figured out any solution?

I am having the same issue?
