### ISSUE TITLE
Puppeteer 3.0.2 loading events in Firefox Nightly 77 on Ubuntu 18

### ISSUE THREAD

**Issue by dsheiko** [puppeteer/puppeteer#5806]
I'm using the following configuration
```
puppeteer.launch({
    "product": "firefox",
    "headless": false,
    "devtools": false,
    "ignoreHTTPSErrors": true,
    "args": [
      ""
    ],
    "executablePath": "/etc/firefox-nightly/firefox"
  })
```
when calling 
```
 await page.goto( "http://todomvc.com/examples/react/#/", {"timeout":30000,"waitUntil":"load"} );
```
second time it waits forever. In Chrome the page is considered already loaded and the program jumps to the next step

**Comment by mtatarau90** [comment]
Hi dsheiko, i had the same issue, seems that waitUntil not work like in chrome. You can use domcontentloaded instead of load, and will work.

**Comment by dsheiko** [comment]
Unfortunately  the same problem with 
```
await page.goto( "http://todomvc.com/examples/react/#/", {"timeout":30000,"waitUntil":"domcontentloaded"} );
```

**Comment by mjzffr** [comment]
@dsheiko Could you share a minimal example script and a corresponding log from `DEBUG=puppeteer:*` set?

**Comment by dsheiko** [comment]
In script I'm doing two calls:
```
await page.goto( "http://todomvc.com/examples/react/#/", {"timeout":30000,"waitUntil":"load"} );
await page.goto( "http://todomvc.com/examples/react/#/?123", {"timeout":30000,"waitUntil":"networkidle2"} );
```
then run once with Firefox and once with Chromium
Here the Puppeteer logs
[firefox.log](https://github.com/puppeteer/puppeteer/files/4667422/firefox.log)
[chromium.log](https://github.com/puppeteer/puppeteer/files/4667424/chromium.log)

**Comment by whimboo** [comment]
Note that in Firefox we do not support `networkidle` yet, as such it would never resolve.

Also due the same document navigation you are most likely affected by [bug 1632649](https://bugzilla.mozilla.org/show_bug.cgi?id=1632649). It's somewhat high on our priority list to get implemented.

**Comment by whimboo** [comment]
> await page.goto( "http://todomvc.com/examples/react/#/", {"timeout":30000,"waitUntil":"load"} );
> await page.goto( "http://todomvc.com/examples/react/#/?123", {"timeout":30000,"waitUntil":"networkidle2"} );

When loading these two pages right after the other I can also see with Chrome that the full lifecycle of load events are handled. As the very last you can see one for `networkAlmostIdle`. Duping to issue #5841.
