### ISSUE TITLE
Can't Press CTRL+Shift+R

### ISSUE THREAD

**Issue by Somberor** [puppeteer/puppeteer#5812]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 12.03

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
await page.keyboard.down('Shift');
            await page.keyboard.down('Control');
            await page.keyboard.press('R');
            await page.keyboard.up('Shift');
            await page.keyboard.up('Control');
```

**What is the expected result?**
I was trying to Force - Refresh a page in order to get all the requests and the cached elemnts to refresh , but it did not work

**What happens instead?**
Nothing happens when I try this code
And I would like to know if there is any other way to make a force refresh of a page

**Comment by mai0li** [comment]
You're submitting the wrong hotkey combination - I suppose you're trying this on a MacOS environment, and for that you need _command_ + shift + R (not control).

Furthermore, you can force a page retrieval from the server by combining the evaluation method and the location object:

```
await page.evaluate(() => {
   location.reload(true)
})
```

[See location documentation](https://developer.mozilla.org/en-US/docs/Web/API/Location)

**Comment by Somberor** [comment]
> You're submitting the wrong hotkey combination - I suppose you're trying this on a MacOS environment, and for that you need _command_ + shift + R (not control).
> 
> Furthermore, you can force a page retrieval from the server by combining the evaluation method and the location object:
> 
> ```
> await page.evaluate(() => {
>    location.reload(true)
> })
> ```
> 
> [See location documentation](https://developer.mozilla.org/en-US/docs/Web/API/Location)

I'm sorry,  but I meant CTRL + F5 / CTRL + SHIFT + R which doesn't work for me (the page is not  being refreshed at all)
I do use windows ,
Also the location.reload(true) doesn't seem to do the work here :(
