### ISSUE TITLE
Issue with aws lambda Node.js 12 

### ISSUE THREAD

**Issue by dhruven08** [puppeteer/puppeteer#5817]
Running into the error :

" errorType": "Error",
    "errorMessage": "Failed to launch chrome!\n/tmp/headless_shell: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n",
    "stack": [
        "Error: Failed to launch chrome!",
        "/tmp/headless_shell: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory",
        "",
        "",
        "TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md",
        "",
        "    at onClose (/var/task/node_modules/puppeteer/lib/Launcher.js:348:14)",
        "    at Interface.helper.addEventListener (/var/task/node_modules/puppeteer/lib/Launcher.js:337:50)",
        "    at Interface.emit (events.js:203:15)",
        "    at Interface.EventEmitter.emit (domain.js:448:20)",
        "    at Interface.close (readline.js:397:8)",
        "    at Socket.onend (readline.js:173:10)",
        "    at Socket.emit (events.js:203:15)",
        "    at Socket.EventEmitter.emit (domain.js:448:20)",
        "    at endReadableNT (_stream_readable.js:1145:12)",
        "    at process._tickCallback (internal/process/next_tick.js:63:19)"

**Comment by saaduddin** [comment]
Try to install the library manually: `sudo apt-get install libnss3`

**Comment by saaduddin** [comment]
Or downgrade to v2.1.1: #5704
