### ISSUE TITLE
Failed to download Chromium r722234

### ISSUE THREAD

**Issue by Trinhlvtq** [puppeteer/puppeteer#5822]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: v2.1.1
* Platform / OS version: Google Cloud Functions (HTTP)
* URLs (if applicable):
* Node.js version: Nodejs 8

**What steps will reproduce the problem?**
I have use puppeteer in my function. When I deploy function on Cloud Functions for Firebase, i got this error. I just retried it a couple of times and eventually it would install correctly. Not really a fix but it may indicate it was just trying to install it on a malfunctioning serverless instance or something.

**What is the expected result?**
No error

**What happens instead?**
```
Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nERROR: Failed to download Chromium r722234! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\nError: end of central directory record signature not found\n    at /workspace/node_modules/yauzl/index.js:167:14\n    at /workspace/node_modules/yauzl/index.js:473:5\n    at /workspace/node_modules/fd-slicer/index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)\n  -- ASYNC --\n    at BrowserFetcher.<anonymous> (/workspace/node_modules/puppeteer/lib/helper.js:111:15)\n    at Object.<anonymous> (/workspace/node_modules/puppeteer/install.js:66:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppeteer@2.1.1 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the puppeteer@2.1.1 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-05-07T08_22_18_757Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "3F4C9440"}}
```

Sometime it's a other error
```
Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nERROR: Failed to download Chromium r722234! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.\nError: end of central directory record signature not found\n    at /workspace/node_modules/yauzl/index.js:167:14\n    at /workspace/node_modules/yauzl/index.js:473:5\n    at /workspace/node_modules/fd-slicer/index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)\n  -- ASYNC --\n    at BrowserFetcher.<anonymous> (/workspace/node_modules/puppeteer/lib/helper.js:111:15)\n    at Object.<anonymous> (/workspace/node_modules/puppeteer/install.js:66:16)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Function.Module.runMain (module.js:694:10)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! puppeteer@2.1.1 install: `node install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the puppeteer@2.1.1 install script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-05-07T08_22_18_263Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "8FDB325B"}}
```

**Comment by tomisavolainen** [comment]
We are also experiencing this.
 ```
> puppeteer@2.1.1 install /build/node_modules/puppeteer
 > node install.js
 
ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
 
Error: read ECONNRESET 
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
 
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/build/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/build/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by Norrismi** [comment]
I am having a similar issue.

`ERROR: Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.`

**Comment by dipto0321** [comment]
I am also having the same issue :slightly_frowning_face: Any solution? I have added
```
PUPPETEER_SKIP_DOWNLOAD=true
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
```
in `.env` but still having issue

**Comment by yescay** [comment]
Is there a resolution for this ? Facing a similar issue.

`sudo npm install puppeteer

> puppeteer@3.1.0 install /Users/kameswaran/Documents/workspace/scraping/node_modules/puppeteer
> node install.js

(node:19038) ExperimentalWarning: The fs.promises API is experimental
Downloading Chromium r756035 - 124.1 Mb [====================] 100% 0.0s 
ERROR: Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
{ Error: EEXIST: file already exists, mkdir '/Users/kameswaran/Documents/workspace/scraping/node_modules/puppeteer/.local-chromium/mac-756035'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/Users/kameswaran/Documents/workspace/scraping/node_modules/puppeteer/lib/helper.js:94:19)
    at fetchBinary (/Users/kameswaran/Documents/workspace/scraping/node_modules/puppeteer/install.js:148:8)
    at download (/Users/kameswaran/Documents/workspace/scraping/node_modules/puppeteer/install.js:54:9)
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path:
   '/Users/kameswaran/Documents/workspace/scraping/node_modules/puppeteer/.local-chromium/mac-756035' }
npm WARN notsup Unsupported engine for puppeteer@3.1.0: wanted: {"node":">=10.18.1"} (current: {"node":"10.8.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer@3.1.0
npm WARN notsup Unsupported engine for extract-zip@2.0.0: wanted: {"node":">= 10.12.0"} (current: {"node":"10.8.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: extract-zip@2.0.0
npm WARN enoent ENOENT: no such file or directory, open '/Users/kameswaran/Documents/workspace/scraping/package.json'
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN scraping No description
npm WARN scraping No repository field.
npm WARN scraping No README data
npm WARN scraping No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kameswaran/.npm/_logs/2020-05-27T05_13_22_649Z-debug.log`

**Comment by marcioscf** [comment]
Okay guys, so i had the same problem that @yescay, @dipto0321 and @Norrismi have and just found a workarround... There are many posts saying that you can try to install with the variable set to true with the command:

PUPPETEER_SKIP_DOWNLOAD=true npm install puppeteer

But after the installation, the package would not work properly. 
One way to resolve the problem, is to use firefox instead of chromium:
Install it with the command:
PUPPETEER_PRODUCT=firefox npm install puppeteer

And explicitly use the firefox browser when you want to use puppeteer:
puppeteer.launch(product: 'firefox');

**Comment by yescay** [comment]
The issue is resolved for me. It was a case of Prerequisites not met. The nodejs library on my system was 10.8.0. Once I upgraded the node version, the install went through ( I even wrote some samples using the library)

**Comment by dipto0321** [comment]
Thanks, @marcioscf . It works for me :bow:

**Comment by lechen26** [comment]
we are having the same issue and its a random thing which makes it pretty frustrating.
we have  dockerfile which failed during npm install on puppeteer with the exact same error.
rerun the build usually just works.

why installing chromiun is so unstable?

**Comment by marcioscf** [comment]
@lechen26 after further review, I found out it was something with the node version. After changing the version a couple a times and it worked just fine. You cant try both the 10.2 and the 14.3.
Recommendation: use NVM to manage your versions!

**Comment by ghost** [comment]
I found this thread because I was getting the `ERROR: Failed to set up Chromium r782078! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.` issue when trying to deploy to Google App Engine Flex via cloudbuild. I had to put `"PUPPETEER_SKIP_DOWNLOAD=true"` in the cloudbuild.yaml file and not the app.yaml in order to get this to work. eg:

```
steps:
    name: 'gcr.io/cloud-builders/yarn:node-10.10.0'
    args: ['install', '--production', '--ignore-engines']
    env:
        - 'PUPPETEER_SKIP_DOWNLOAD=true'
    dir: 'functions/autodeploy'
```

Hopefully this might help someone else

**Comment by hubingliang** [comment]
use --unsafe-perm.It works for me!
`npm i puppeteer -g --unsafe-perm`

**Comment by laconley** [comment]
@yescay 's answer worked for me. I had node version 10.4.1 installed and changed version to 12.18.4 and was then able to install puppeteer.

**Comment by dakshhmehta** [comment]
> use --unsafe-perm.It works for me!
> `npm i puppeteer -g --unsafe-perm`

Worked for me. Thanks. 

I have been facing issue on Node 14 on Ubuntu 18.04 so try it if on similar enviornment.
