### ISSUE TITLE
Error occurs when headless: false, but works fine for headless: true

### ISSUE THREAD

**Issue by supriyanta** [puppeteer/puppeteer#5833]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.4
* Platform / OS version: Ubuntu 20.04
* URLs (if applicable): 
* Node.js version: v14.2.0

**What steps will reproduce the problem?**
    I'm playing around with the api. I've used given snippet in github to take screenshot. It works fine when headless: true, but not works in headless: false;

1. This code produces error...
```javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto("https://google.com");
  await page.screenshot({ path: "example.png" });

  await browser.close();
})();
```
```
(node:18491) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Target closed.
    at /home/titin/Desktop/testrun/node_modules/puppeteer/lib/Connection.js:183:56
```

**What is the expected result?**
      In headless: false mode I should see opening up the browser.

**What happens instead?**
     Some error message, I cant understand.

**Comment by ugeshgupta000** [comment]
Give it as https://**www.**google.com

**Comment by ugeshgupta000** [comment]
http://**www**.google.com

**Comment by rajakrishna** [comment]
You just need to add the protocol. 
```javascript
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch({ headless: false });
	const page = await browser.newPage();
	await page.goto('https://google.com', {
		waitUntil: 'networkidle2',
	});
	await page.screenshot({ path: 'example.png' });
	await browser.close();
})();
```
