### ISSUE TITLE
undefined import from 'puppeteer/DeviceDescriptors'

### ISSUE THREAD

**Issue by laurentpayot** [puppeteer/puppeteer#5834]
### Steps to reproduce

Every was fine with puppeteer v3.0.2.

**Tell us about your environment:**

* Puppeteer version: 3.0.4
* Platform / OS version: Ubuntu 20.04
* URLs (if applicable):
* Node.js version: 13.8.0

**What steps will reproduce the problem?**

1. `import mobileDevices from 'puppeteer/DeviceDescriptors'`
2. `console.log("devices =", mobileDevices)`

**What is the expected result?**
`devices = <an object>`

**What happens instead?**
`devices = undefined`

**Comment by saaduddin** [comment]
Use the CommonJS syntax instead as ES6 isn't still fully supported by Node.js:

`const mobileDevices = require("puppeteer/DeviceDescriptors");`

Or better yet, if you already have the require("puppeteer") method, you can simply use:

`console.log(puppeteer.devices)`

And retrieve a device like:

`console.log(puppeteer.devices["iPhone X"])`

**Comment by laurentpayot** [comment]
@saad-uddin thanks for the proposals. I should have mentioned that I'm using Typescript:
```json
// tsconfig.json (partial)
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "moduleResolution": "node",
}
```
And anyway I never had the issue before. It seems the bug appeared after https://github.com/puppeteer/puppeteer/commit/4fdb1e3cab34310b4a1012c3024a94bc422b3b92

**Comment by laurentpayot** [comment]
Nevermind, I'm going to check my tsconfig files usage (I'm using more than one). It might be the cause of the bug. Thanks!

**Comment by NikolaiSilver** [comment]
I faced with the same issue, @laurentpayot   you fixed it ? Was it a problem in tsconfig? Thank's in advance for answer :pray:

**Comment by laurentpayot** [comment]
@NikolaiMaksimenkoPreply  As it was taking too much to time to find the cause of the bug and fix it, I decided to finally give [playwright](https://github.com/microsoft/playwright) a try. I'm using it now instead of Puppeteer.
Are you using more than one `tsconfig.json` file? If not then having more than one TS config file isn't the cause of this bug but https://github.com/puppeteer/puppeteer/commit/4fdb1e3cab34310b4a1012c3024a94bc422b3b92 may be.
