### ISSUE TITLE
Sporadic ECONNRESET on downloading Chromium r737027

### ISSUE THREAD

**Issue by sjmtan** [puppeteer/puppeteer#5835]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.3
* Platform / OS version: Debian Stretch
* URLs (if applicable):
* Node.js version: 12.x (using https://deb.nodesource.com/setup_12.x)

**What steps will reproduce the problem?**
1. npm ci - package.json (and package-lock.json) contains :
```
  "dependencies": {
    "commander": "^5.1.0",
    "puppeteer": "^3.0.3"
  },
```

**What is the expected result?**
Succeeds downloading

**What happens instead?**

```
> puppeteer@3.0.3 install /.../node_modules/puppeteer
 
> node install.js
 
ERROR: Failed to set up Chromium r737027! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
 
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/.../node_modules/puppeteer/lib/helper.js:82:19)
    at fetchBinary (/.../node_modules/puppeteer/install.js:114:27)
    at download (/.../node_modules/puppeteer/install.js:42:9) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.0.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

More details:
I'm building a Docker image based on Debian stretch. I've followed the instructions with regards to additional dependencies for Debian + the ones for Docker. I have some questions.

1) The docker instructions download `google-chrome-unstable`. Is this a build of Chromium? Is this expected to work with the Puppeteer API?
1a) Does this need to be installed if you do the install of puppeteer fully with no skip chromium download?
2) What happens if you do both - install google-chrome-unstable but don't skip Chromium download?
3) Is there perhaps a sporadic network issue with downloading this Chromium revision? I've seen it on a few times that I've built this docker container, but not a bunch of other times. This was more recent too, as of yesterday. I've been building this docker container regularly without issue for about 9 months now. I upgraded to 3.0.3, but it was already sporadically failing to download before that.

The reason why I'm submitting this here is that the docs regarding this are a bit confusing, and I'd love to clear up what the right download path is for Chromium for that Dockerfile. I'm happy to submit a PR to clarify as well.

**Comment by sjmtan** [comment]
Relevant portion of my Dockerfile.

```
# install ca roots
RUN apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates curl wget gnupg2 dumb-init

# Since we're running from Debian and not Node base image, we need to install Node + relevant libs
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs build-essential

# Install other dependencies missing for Debian
# https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
# list is alphabetical, there are some duplicates like ca-certificates and wget, but keeping it for consistency
RUN apt-get install -y ca-certificates fonts-liberation gconf-service libappindicator1 libasound2 libatk-bridge2.0-0 \
                       libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 \
                       libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 \
                       libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
                       libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release
                       wget xdg-utils --no-install-recommends

# install dependencies for PDF generation
# https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*
```

**Comment by CollapsedMetal** [comment]
Same happens to me **randomly** when i execute `npm install` using npm v6.14.5
Same deal via `docker-compose build`
![image](https://user-images.githubusercontent.com/5317311/86049947-10659000-ba21-11ea-9a91-82466b9ee174.png)

**Comment by deepaktatineni** [comment]
Removing one of the ways to install dependencies will solve the issue. However, from last week libxss1 is missing from chromium dependency list which might cause the failure of chromium launch.

**Comment by kemaric** [comment]
This is happening to me as well for my internal work project running Node14.15.0

**Comment by yilinjuang** [comment]
Having the same issue. Using
docker image node:12.18
puppeteer 5.5.0

```
ERROR: Failed to set up Chromium r818858! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

using a mirror chromium site might help
https://github.com/puppeteer/puppeteer/issues/1597#issuecomment-351945645

**Comment by cristi8** [comment]
Having a similar issue, receiving `Error: connect ETIMEDOUT` instead of connection reset.
The issue is definitely on google cloud storage being inconsistent.
Here is a quick test that i did:

```
$ while true; do if timeout 1 curl --ipv4 -I -s https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/961656/chrome-linux.zip -o /dev/null; then echo success; else echo fail; fi; done
success
success
success
success
success
success
success
success
success
fail
success
success
fail
fail
fail
success
success
success
success
success
fail
success
fail
success
success
fail
success
```

If i run the test at different times, i sometime get a lot of "success" outputs. I am guessing some IPs in the dns rotation have issues.

The best thing for puppeteer is to **retry the downloads**, at least 3 times, since the default download location is unstable.

You think this is a good solution, instead of having to use the `taobao` mirror in a production setting?

**Comment by cristi8** [comment]
Also, the Google Cloud Storage documentation recommends the `Truncated exponential backoff` retry strategy for TCP timeouts and disconnects: https://cloud.google.com/storage/docs/retry-strategy#retryable

**Comment by person1123** [comment]
I'm experiencing this. @shannontan-bolt is it possible to reopen this?

**Comment by jauhlmann** [comment]
I'm still experiencing this issue, can we reopen it?
