### ISSUE TITLE
How to download file to the specified path[/name]

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#584]
1. There are many link in one page to download files. How to save files to the specified path when click links?
2. If I have got the file URL, how to download the file and save it to the specified path with specified name by the URL but not click link?
I'm sorry for my be this is a very silly question. I hope your help. thanks.

**Comment by aslushnikov** [comment]
This is a dupe of #299

**Comment by ghost** [comment]
Thank you very much.

**Comment by DaveGeneral** [comment]
> This is a dupe of #299

Hi, the answer in #299 seems to solve the first problem, but don't solve the second one perfectly,
In #299, when the file is downloaded, use fs to rename it, but if I want to rename it before the downloading, how to get it? @aslushnikov

**Comment by subwaymatch** [comment]
In case anyone is still trying to deal with file downloads in puppeteer, take a look at [playwright](https://playwright.dev). Most of the APIs are almost identical, and it has built-in support for `download` events :ok_hand: ([https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=event-download](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=event-download)). Puppeteer's previous top contributors now work on playwright (source: [https://blog.logrocket.com/playwright-vs-puppeteer/](https://blog.logrocket.com/playwright-vs-puppeteer/)).
