### ISSUE TITLE
A couple of issues on a Raspberry PI trying to do WebRTC

### ISSUE THREAD

**Issue by neilyoung** [puppeteer/puppeteer#5840]
- Using HeadlessChrome/78.0.3904.108 on a Raspberry PI 3A+
- Had to setup puppeteer like shown here: https://www.youtube.com/watch?v=6LnJ1zW5464
- Testscript on the PI:

```
// PC
//const puppeteer = require('puppeteer');
// PI
const puppeteer = require('puppeteer-core');
var options = {
    headless: true,
    executablePath: '/usr/bin/chromium-browser',      // PI only
    args: [
        '--use-fake-device-for-media-stream',
        '--use-fake-ui-for-media-stream',
        '--remote-debugging-port=9222',
        '--remote-debugging-address=192.168.188.27',          // PI only
    ]
};

(async () => {
    const browser = await puppeteer.launch(options);
    const page = await browser.newPage();
    await page.goto('https://dragonfly-test.accuware.com:8443/?room=chromium&autoanswer=true', {  })
    page
       .on('console', message =>
             console.log(`${message.type().substr(0, 3).toUpperCase()} ${message.text()}`))
       .on('pageerror', ({ message }) => console.log(message))
       .on('response', response =>
            console.log(`${response.status()} ${response.url()}`))
       .on('requestfailed', request =>
            console.log(`${request.failure().errorText} ${request.url()}`))
})()
```

- Start the script above on the PI
- Having a counterpart here (open in a browser on the PC):

https://dragonfly-test.accuware.com:8443/?room=chromium

- Wait until the PI appears in the browser (dialog box).

- Press 'Call'. It will work with fake media.

- Comment `--use-fake-device-for-media-stream`, restart the PI script, call again. It will not work. 

- Fails with `NotFoundError: Requested device not found`. I'm just requesting `video`. 

Question: What is required in order to enable the PI to access the local camera?

EDIT: Additional problem: Even though I'm able to open the remote debugger, the content of the page is more or less empty.

**Comment by mxmaxime** [comment]
Hi, I have the same issue... I wanted to try to "connect" the CSI PI camera to webRTC to stream my camera, would be so nice.

**Comment by neilyoung** [comment]
I absolutely can recommend GStreamer 1.17 for this and a python script. Works like a charm. Alternatively you could use UV4L WebRTC extension. Works too, but is crashing the PI after a time.
