### ISSUE TITLE
Whitespace is getting added after custom header and before footer

### ISSUE THREAD

**Issue by vijayvamja** [puppeteer/puppeteer#5843]
**My code is as below:** 

```
    const browser = await this.Puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(`<html>
                            <body style="background-color: #434244; color: #fff">
                                <div>Page body</div>
                            </body>
                          </html>`);    
    const headerFooterCss = `<style>#header, #footer { padding:0;}</style>`;
    const options = {
      displayHeaderFooter: true,
      printBackground: true,
      preferCSSPageSize: false,
      headerTemplate: `
                   ${headerFooterCss}
                   <div style='width: 100%; height: 100%;-webkit-print-color-adjust: exact; background-color: #434244'>
                       <div style='text-align: center; height: 100%;color: #fff;background: #434244; font-size: 14px'> Header content</div>
                   </div>`,
      footerTemplate: `
                      ${headerFooterCss}
                     <div style='width: 100%; height: 100%;margin-bottom: 0;-webkit-print-color-adjust: exact; background-color: #434244''>
                         <div style='text-align: center; color: #fff;background: #434244; font-size: 14px'> Footer content</div>
                     </div>`,
      margin: {
        top: "30px",
        bottom: "30px",
      },
    };

    const buffer = await page.pdf(options);
```

**Output pdf:**

![pdf](https://user-images.githubusercontent.com/26439760/81559028-5cdf0880-93ac-11ea-9839-1de35733ef74.png)

It is adding some whitespace (notice small line in image) after header and before footer. I don't know which config I am missing/wrong. 
 
Please help me to figure it out.

**Note:** When I download the pdf and open in in chrome, it is not getting noticed. But If I open file in pdf viewer app like Previw in mac, I can see that whitespace

Thanks

**Comment by vamshi9** [comment]
Did you get the solution to this @vijayvamja ?
or any initial thoughts on it?

**Comment by vijayvamja** [comment]
> Did you get the solution to this @vijayvamja ?
> or any initial thoughts on it?

Nope, I didn't get any solution so far :(

**Comment by vamshi9** [comment]
If similar colors are there for two divisions which are next to each other, we are seeing this line. The hack you might want to look into is, have a different color for the boxes which are next to each other. May be you can take the nearest possible color code. It's trail and error again. 

I wish I could find the best possible solution for this. But right now, I can't dig into the package.

**Comment by vijayvamja** [comment]
@vamshi9  I've tried to apply neareast color but still its same result. Probably there is something to do with scalling/zooming. I am not 100% sure about that.

**Comment by pintusoliya** [comment]
Any update on this? I am also facing same issue

**Comment by halloweenman** [comment]
I'm also facing this serious issue.

It pretty much renders Puppeteer useless for when you need a full page background color (including margins). It seriously limits Puppeteers use for many types of documents as this is a very common use case.

I hope the Puppeteer team can fix this as a matter of urgency.
