### ISSUE TITLE
Launching an unsupported product launches Chrome

### ISSUE THREAD

**Issue by foolip** [puppeteer/puppeteer#5844]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.4
* Platform / OS version: macOS 10.15.4
* URLs (if applicable): N/A
* Node.js version: 10.16.3

**What steps will reproduce the problem?**

This script:
```js
const puppeteer =  require('puppeteer');

async function main() {
  const browser = await puppeteer.launch({product: 'pizza'});
  const page = await browser.newPage();
  const ua = await page.evaluate('navigator.userAgent');
  console.log(ua);
  await browser.close();
}

main();
```

**What is the expected result?**

The `puppeteer.launch` call should fail because the product isn't supported. When it does not, it's easier to miss a typo or think something is working when it isn't.

**What happens instead?**

Chrome launches, "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/81.0.4044.0 Safari/537.36" is logged.

**Comment by foolip** [comment]
I think the fix will be here:
https://github.com/puppeteer/puppeteer/blob/6099272612e9f998caaf7dc7c747b7643986da6c/src/Launcher.ts#L1029

Just throwing an error as the default case unsurprisingly leads to `npm test` failing, but I haven't dug in to figure out all that needs to change. Possibly this will be a breaking change since it has been possible to depend on `puppeteer.launch({product: 'pizza'})` to launch Chrome before :)

**Comment by jackfranklin** [comment]
Thanks  for the report, definitely something we should fix. I'll have a look at a PR that updates this to fail and gives a nice error message, or at least still launches Chrome but logs a warning to that effect.
