### ISSUE TITLE
Emoji's not exported to PDF

### ISSUE THREAD

**Issue by jelordreygulle** [puppeteer/puppeteer#5847]
I want to take a PDF export of my website that has emojis in it using puppeteer (that internally used Chromium). But natively, very few emojis are supported and that too in black and white. As you can see on the screenshot.

Thank you.

**Comment by JaLe29** [comment]
I have same problem with emoji's. Any workaround there?

Note: Its showing only on windows machine but not in Linux machine
 
![image](https://user-images.githubusercontent.com/22296816/132034830-10cbb207-4372-4394-a82d-d760191840f5.png)

**Comment by he5310** [comment]
1.  download  emoji  fonts  https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf
2. save NotoColorEmoji.ttf on your server :  /usr/share/fonts/win/NotoColorEmoji.ttf 
then it works.

**Comment by vojkny** [comment]
Hi,

we are using pupeteer as a cloud function where is is not allowed to install anything directly on the machine. Is it somehow possible to include these fonts from package.json?
