### ISSUE TITLE
Puppeteer does not work on RHEL 8.1 (inside a docker)

### ISSUE THREAD

**Issue by thinhbk** [puppeteer/puppeteer#5849]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
1.x (also tried with 2.x), neither of them works
* Platform / OS version:
Using registry.access.redhat.com/ubi8/ubi:8.1 as a base image, 
OS version: Red Hat Enterprise Linux release 8.1 (Ootpa)
* URLs (if applicable):
* Node.js version:
10.15.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
I did follow the [guideline ](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker), but it's for debian based docker image. (note: I was able to build and run puppeteer inside debian docker).
I also follow the [comment ](https://github.com/puppeteer/puppeteer/issues/560#issuecomment-325245136) , but seems like this is for Centos7.3, not for Centos8 or 8.1.

What I did was:

1. update the epel package for rhel 8
RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
2. Add google-chrome repo and import the pub key
RUN echo -e "\
[google-chrome]\n\
name=google-chrome\n\
baseurl=https://dl.google.com/linux/chrome/rpm/stable/\$basearch\n\
enabled=1\n\
gpgcheck=1\n\
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub" >> /etc/yum.repos.d/google-chrome.repo
3. Install dependencies for google-chrome
RUN yum install -y pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64
4. Install google-chrome-unstable
RUN dnf install -y google-chrome-unstable
**What is the expected result?**
Expect google-chrome-unstable should be able to installed.

**What happens instead?**
Got this error:
RUN dnf install google-chrome-unstable 
Updating Subscription Management repositories. Unable to read consumer identity This system is not registered to Red Hat Subscription Management. 
You can use subscription-manager to register. Last metadata expiration check: 0:00:13 ago on Wednesday 11 May 2020 06:22:08 AM EDT. 
Error: Problem: conflicting requests - nothing provides liberation-fonts needed by google-chrome-stable-81.0.4044.138-1.x86_64 - nothing provides libXss.so.1()(64bit) needed by google-chrome-stable-81.0.4044.138-1.x86_64 - nothing provides libappindicator3.so.1()(64bit) needed by google-chrome-stable-81.0.4044.138-1.x86_64 - nothing provides libvulkan.so.1()(64bit) needed by google-chrome-stable-81.0.4044.138-1.x86_64 (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

So, I switch to another approach, which just to download and install the google-chrome-unstall directly, and then install some of the font dependencies.

1. RUN wget https://dl.google.com/linux/direct/google-chrome-unstable_current_x86_64.rpm
RUN rpm_file=$(echo *.rpm) && echo "Downloaded ${rpm_file}" && rpm -ih --nodeps ${rpm_file} && rm ${rpm_file}
2. Install font dependencies:
RUN yum install -yq fontconfig-devel-2.13.1-3.el8.x86_64 fontpackages-filesystem-1.44-22.el8.noarch  vlgothic-fonts  urw-base35-gothic-fonts xorg-x11-font-utils xorg-x11-fonts-Type1 xorg-x11-proto-devel
Note: as per [comment](https://github.com/puppeteer/puppeteer/issues/560#issuecomment-325245136) and [here ](https://github.com/puppeteer/puppeteer/issues/391#issuecomment-324551649) a lot of font dependencies are not found in rhel 8, I try to check one by one for the matching.

Once using this approach, seems google-chrome-stable is installed.
However, once running it within puppeteer:
```
try {
        browser = await puppeteer.launch({
            executablePath: 'google-chrome-unstable',
            ignoreHTTPSErrors: true,
            args: [
                '--no-sandbox', '--disable-setuid-sandbox', '--allow-file-access-from-files', '--enable-local-file-accesses'
            ],
            headless: true
        });
    } catch (error) {
        logger.error(error);
        process.exit();
    }
```

Here is the error in the docker log:

{
  "message": "Failed to launch chrome!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n",
  "stack": "Error: Failed to launch chrome!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n\n    at onClose (/node-run/microservice-report-generation/node_modules/puppeteer/lib/Launcher.js:348:14)\n    at ChildProcess.helper.addEventListener (/node-run/microservice-report-generation/node_modules/puppeteer/lib/Launcher.js:338:60)\n    at ChildProcess.emit (events.js:194:15)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)",
  "level": "error"
}
Error: Failed to launch chrome!

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/node-run/microservice-report-generation/node_modules/puppeteer/lib/Launcher.js:348:14)
    at ChildProcess.helper.addEventListener (/node-run/microservice-report-generation/node_modules/puppeteer/lib/Launcher.js:338:60)
    at ChildProcess.emit (events.js:194:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

There's not much useful information showing in the exception anyway.
I doubt that google-chrome would need some more dependencies (which is lacking in rhel 8) to make it work properly, but unable to figure out what is missing.
Is puppeteer supposed to work in rhel 8 (as this [comment ](https://github.com/puppeteer/puppeteer/issues/391#issuecomment-324905628) makes me confused)?
What are the missing libraries?

**Comment by pierreminiggio** [comment]
Similar issue here on CentOS 8 :'(
(But not inside a docker)

```
npm --version # 7.6.3
node --version # v14.16.0
```

Test code I run : 
```javascript
'use strict';
import puppeteer from 'puppeteer';
import fs from 'fs';
(async () => {
  console.info("Starting browser");
  let browser;
  try {
    browser = await puppeteer.launch({});
  } catch (e) {
    console.info("Unable to launch browser mode in sandbox mode. Lauching Chrome without sandbox.");
    browser = await puppeteer.launch({args:['--no-sandbox']});
  }
  console.info("Browser successfully started");
  console.info("Closing browser");
  await browser.close();
  console.info("Done");
})();
```

```console
/var/www/html/facebook-poster-api/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/var/www/html/facebook-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/var/www/html/facebook-poster-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:91629) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:91629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
