### ISSUE TITLE
[BUG] Unable To Extract Page Data For URL which is Downloading Content Automatically

### ISSUE THREAD

**Issue by hassan91** [puppeteer/puppeteer#5854]
## Environment
* `chrome-aws-lambda` Version: 705776
* `puppeteer` / `puppeteer-core` Version: 2.0.*
* OS: AWS Lambda
* Node.js Version: 12.x
* Lambda / GCF Runtime: 2538

## Expected Behavior
page.goto should work

## Current Behavior
ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "[object Object]",
    "stack": [
        "Error: [object Object]",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)",
        "    at postError (/var/runtime/CallbackContext.js:30:54)",
        "    at done (/var/runtime/CallbackContext.js:57:7)",
        "    at fail (/var/runtime/CallbackContext.js:69:7)",
        "    at Object.fail (/var/runtime/CallbackContext.js:105:16)",
        "    at Runtime.exports.handler (/var/task/index.js:126:20)"
    ]
}

## Steps to Reproduce
https://www.malwaredomainlist.com/hostslist/yesterday_urls.php

**Comment by hassan91** [comment]
Reference: https://github.com/alixaxel/chrome-aws-lambda/issues/123

**Comment by dpmott** [comment]
Referenced code is no longer available (and is not hosted on an insecure site with an expired web certificate).
