### ISSUE TITLE
how can I get the arguments from executing the puppeteer code by the command line?

### ISSUE THREAD

**Issue by h4l-yup** [puppeteer/puppeteer#586]
I am using puppeteer for the automation of submitting customer information to a website.

So I made a puppeteer file (submit.chrome.js) and it would be executed by command line like 'node submit.chrome.js'. (It is a long story why I have to use command line to execute the puppeteer file.)

While doing this, I need to send some data to submit.chrome.js.

I was trying to use 'lodash' to map the data after receiving in the submit.js.

However, I can not find the way to get the data in submit.chrome.js which are sent from the command line, in form of arguments.

I had been used casperjs for doing the same task and there was 'casper.cli.args' to get the arguments from the command line.

Is there any way to get the data from the command line execution?

**Comment by vsemozhetbyt** [comment]
@kimseongyup-carson Can [`process.argv`](https://nodejs.org/api/process.html#process_process_argv) help here?

**Comment by h4l-yup** [comment]
@vsemozhetbyt  I had missed searching nodejs documents.

Thanks for your help!
