### ISSUE TITLE
Puppeteer doesnt start when compiled in electron [Windows]

### ISSUE THREAD

**Issue by approvedpr** [puppeteer/puppeteer#5867]
Puppeteer version: 3.0.4
Platform / OS version: Windows
Node.js version: v12.16.1.

The normal (raw) version of the script works perfectly fine but once I compile the whole code,
I get this error when trying to run the code:

```
Uncaught (in promise) Error: Failed to launch the browser process! spawn \node_modules\puppeteer\.local-chromium\win64-737027\chrome-win\chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose \node_modules\puppeteer\lib\Launcher.js:547:20)
    at ChildProcess.<anonymous> \node_modules\puppeteer\lib\Launcher.js:539:80)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I already read the doc and tried it with: 

- ignoreDefaultArgs: ['--disable-extensions'],
- disabled sandbox etc.
- updated puppeteer

Additional info:
I use puppeteer-extra aswell with various plugins

**Comment by ttibau** [comment]
@SentoxAIO  do u have solution for this? 

I've same problem.
