### ISSUE TITLE
Can't click on a <a> inside svg

### ISSUE THREAD

**Issue by rafaelp-silva** [puppeteer/puppeteer#5870]
Hello,

I'm getting crazy trying to click in <a> inside a <svg>. Follows the code page:

`<div id="singlevalue" class="single-value shared-singlevalue" data-cid="view19329" data-view="views/shared/singlevalue/Master" data-render-time="0" style="width: 100%; height: 100%; position: relative;">
<svg class="svg-container" style="position: absolute; top: 0px; left: 0px; height: 133px; width: 920px;"><g class="single-value-main-body" data-cid="view19916" data-view="views/shared/singlevalue/MainBody" data-render-time="0.004" transform="translate(0,93.10000000000001)">
<g class="single-value-labels" data-cid="view19918" data-view="views/shared/singlevalue/Labels" data-render-time="0.003">
<g class="main-label-group"><g class="single-value-label" data-name="display.visualizations.singlevalue.singleResult" data-cid="view19920" data-view="views/shared/singlevalue/Label" data-render-time="0.002">
<g class="single-result-group">
<g class="svg-label">
<a href="#" class="single-drilldown" style="text-decoration: none;"><text class="single-result" x="386.2" style="letter-spacing: -0.02em; font-weight: bold; fill: rgb(51, 51, 51); opacity: 1; font-size: 87.78px; text-decoration: none;">284</text>
</a></g></g></g></g></g></g></svg></div>`

I need to click at the "284" so a new div appers at the bottom with other informations.

![image](https://user-images.githubusercontent.com/54870765/81966780-5d67e100-95f0-11ea-85d4-87bbcbf35fee.png)

tried:

`await page.waitForNavigation({waitUntil: 'load'});
 await page.hover('text[class="single-result"]');
 await page.click("svg > g > g > g > g > g > g a");`

`await page.waitForNavigation({waitUntil: 'load'});
 await page.hover('text[class="single-result"]');
 await page.click('a[class="single-drilldown"]');`

Can help? Please!

**Comment by sfelice777** [comment]
Did you check to see if your element locator worked in the Chrome console?
Have you tried this-

await page.waitForNavigation({waitUntil: 'networkidle0'}); 
await page.click('a.single-drilldown');
