### ISSUE TITLE
Generating a PDF of a Vue page using Vuex store/state leads to blank pages.

### ISSUE THREAD

**Issue by vanjoechua** [puppeteer/puppeteer#5871]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: local machine Windows 10
* URLs (if applicable): N/A
* Node.js version: v10.16.0

**What steps will reproduce the problem?**
N/A

_Please include code that reproduces the issue._

1. for example this some code to generate the header in the invoice
```
<v-col cols="9" class="d-flex flex-column pt-3">
                    <div>
                        <span class="header-title">{{ Office__title  }}</span>
                        <span class="header-subtitle font-weight-bold" style="vertical-align: top">{{ '(' + Office__companyno + ')' }}</span>
                    </div>
                    <span class="header-subtitle pt-1 pb-0">{{ Office__address1  }}</span>
                    <span class="header-subtitle pt-1 pb-0">{{ [Office__address2, Office__city, Office__state, Office__country].join(', ')  }}</span>
                    <span class="header-subtitle pt-1 pb-0">{{ $t('message.tel') + ': ' + Office__contracttel  }}</span>
                    <span class="header-subtitle pt-1 pb-0">{{ $t('message.email') + ': ' + Office__contractemail + ' ' + $t('message.website') + ': ' + Office__website }}</span>
                </v-col>
```

2. The variables are obtained using this:
```
data() {
            return {
                appLogo: AppConfig.appSessionLogo,
                deliveryAddresses: [],
                loaded: false,
            };
        },
        computed: {
            ...mapFields('contract', {
                Contract__id: 'print.Contract.id',
                Contract__Bank_id: 'print.Contract.Bank.id',
                Contract__Bank_title: 'print.Contract.Bank.title',
                Contract__Bank_account: 'print.Contract.Bank.account',
                Contract__Bank_swiftcode: 'print.Contract.Bank.swiftcode',
                Contract__Bank_beneficiary: 'print.Contract.Bank.beneficiary',
                Contract__Deliveryaddress_address: 'print.Contract.Deliveryaddress.address',
         etc, etc....
```
Note: ...mapFields id from this package "maoberlehner/vuex-map-fields". Using standard ...mapGetters also replicates the issue.

**What is the expected result?**
PDF of the sales invoice should appear

**What happens instead?**
I get two blank pages. When I pdf.goto to another page in my site where no Vuex is used I get a render of the page.

If I pull directly from the API into the page without using Vuex the page is rendered. I would very much like to use the Vuex actions, state, mutations in the print page so I don't have to rewrite some of the code 2x. Does anyone have any experience doing this? I googled high and low and only found 1 or 2 postings but with no solution mentioned.

**Comment by MontolioV** [comment]
Most likely you are trying to use page.pdf(), while Vue hasn't finished to render the page. I think Vuex is not the case, just a slowdown trigger in particular environment. Puppeteer API and V8 runs concurrently. To be completely sure the content is rendered before printing, use page.exposeFunction() to inject a notification callback, or a WebSocket. Just await the notification on the Puppeteer thread. Consider the asynchronous nature of JS, it's up to you to find an exact trigger that the page is ready. 

```    
// Puppeteer API code
...
    const reportCreated = new Promise(async (resolve, reject) => {
      await page.exposeFunction('puppeteerNotifyReportReady', () => {
        resolve()
      },)
    })

    await page.goto(someURL,{waitUntil: 'networkidle2', timeout: 10 * 60 * 1000,})
    
    await reportCreated
    let result = await page.pdf({
      format: 'A4',
      printBackground: true,
    },)
...
```

```
// Vue code
...
mounted () {
    this.$nextTick(() => {
      /**
       * window.puppeteerNotifyReportReady function is injected with Puppeteer
       */
      if (window.puppeteerNotifyReportReady) {
        window.puppeteerNotifyReportReady()
      }
    },)
  },
...
```

**Comment by vanjoechua** [comment]
I was able to solve this by completely taking out vuex from the picture.I
loaded the data as usual by API and render only after all API calls have
been completed. I will try your solution on other print pages that I still
have to create.

Thanks!
