### ISSUE TITLE
Trying to store the Chrome console error messages into a variable but not working

### ISSUE THREAD

**Issue by 00000DeletedAccount** [puppeteer/puppeteer#5872]
Hi,

I am trying to run some page loading on the puppeteer, Once Chrome is loaded I want to check the browser console error messages. Also, I wanted to store those messages in some variables for the reporting purpose. I used the following. 

```
(async () => {
            await page.on('console', msg => console.log('PAGE LOG:', msg.text()));
            await page.evaluate(() => console.log(`Stats Are ${MILoggingStats.duration}`));
        })();
```

This prints the value in the code console. But the problem is that I want the same value stored in a variable. Since the direct variable assignment is not working tried like below.
```

(async () => {
            await page.on('console', msg => console.log('PAGE LOG:', msg.text()));
            var duration = await page.evaluate(() => console.log(`Stats Are ${MILoggingStats.duration}`));
        })();
```

Or 

```
(async () => {
            var duration = await page.evaluate(`Stats Are ${MILoggingStats.duration}`);
        })();

```
Fetching the log from the console looks working. but storing it into the variable seems not working. You can please guide me if I am missing anything.

**Comment by jribbens** [comment]
`page.on()` doesn't return a `Promise`, so you don't need to `await` its result. You don't seem to have included an example of your code that isn't working, but something like the following should work:
```javascript
const consoleLog = []
page.on('console', msg => consoleLog.push(msg.text()) )
// now make the page do something that emits console logs
console.log(`There were ${consoleLog.length} console log messages.`)
```

**Comment by szakhar** [comment]
> `page.on()` doesn't return a `Promise`, so you don't need to `await` its result. You don't seem to have included an example of your code that isn't working, but something like the following should work:
> 
> ```js
> const consoleLog = []
> page.on('console', msg => consoleLog.push(msg.text()) )
> // now make the page do something that emits console logs
> console.log(`There were ${consoleLog.length} console log messages.`)
> ```

It works.
Thanks, man. You are amazing!
