### ISSUE TITLE
Click does not work when puppeteer is connected to chrome

### ISSUE THREAD

**Issue by gilles-yvetot** [puppeteer/puppeteer#5873]
### Steps to reproduce
​
**Tell us about your environment:**
​
- Puppeteer version: 3.1.0
- Platform / OS version: 10.15.4
- URLs (if applicable): https://google.com
- Node.js version: 12.13.0
- Mac 16 inch
​
**What steps will reproduce the problem?**
​
```js
const puppeteer = require("puppeteer");
// click at 50, 50
const x = 50;
const y = 50;
​
(async () => {
	const browser = await puppeteer.connect({
		// TODO: replace with your websocket URL
		browserWSEndpoint: `ws://127.0.0.1:49641/devtools/browser/11b395bf-10d8-4e22-b674-06bbb7ae62eb`,
		defaultViewport: null,
	});
	// Incognito to ensure it's not one of the extensions
	const context = await browser.createIncognitoBrowserContext();
	const page = await context.newPage();
	await page.goto("https://google.com", { waitUntil: "networkidle2" });
​
	// add a click listener on the page to see where the click was actually performed along with other metadata
	await page.evaluate(() => {
		console.log(
			`innerWidth: ${window.innerWidth}, innerHeight: ${window.innerHeight}, dpr: ${window.devicePixelRatio}`
		);
		document.addEventListener(`click`, (e) => {
			console.log("e.clientX, e.clientY", e.clientX, e.clientY);
			console.log("e.screenX, e.screenY", e.screenX, e.screenY);
			console.log("e.pageX, e.pageY", e.pageX, e.pageY);
		});
	});
	await page.mouse.click(x, y);
	console.log("clicked on x,y", x, y);
})();
```
​
1. Run the above code on a macbook pro 16 inch
2. You will see that the click doesn't happen at the exact location that we asked it to happen
​
**What is the expected result?**
​
- Click should happen at 50, 50 and we should be able to see that from one of the event properties
  **What happens instead?**
- The click doesn't happen at 50, 50 and the None of the event properties show correct result
​
NOTE: Confirming that this only happens on MBP 16" and not other models.

**Comment by VikramTiwari** [comment]
Hey @mathiasbynens Any ideas on what might be happening here? We originally thought this was an issue with CDP.

cc: @paulirish @aslushnikov

**Comment by gilles-yvetot** [comment]
@jackfranklin any idea?

**Comment by gilles-yvetot** [comment]
Resetting all my settings in chrome made this disappear. I think it came from a transfer of setting from 2 macbooks while setting up one
