### ISSUE TITLE
Use the output outside of the browser

### ISSUE THREAD

**Issue by Jugoslav85** [puppeteer/puppeteer#5877]
Sorry if my question doesn't make much sense, I am new in puppeteer and JS in general.

I am trying to use the output from the evaluation outside of the browser, but I get an error that the variable is not defined.

What should i do?

`const puppeteer = require('puppeteer');
let userUrl = "https://www.scamstuff.com";

(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
  const page = await browser.newPage();
  await page.goto(userUrl, {waitUntil: "networkidle2"});
  let data = await page.evaluate("Shopify.theme.name");
    await browser.close();
})();
console.log(data)   // i get an error data is not defined`

**Comment by jribbens** [comment]
This is a JS question not a Puppeteer one, but the problem is that you have defined `data` to be local to the anonymous function, but are trying to access it from the global scope. Not to mention, even if it was a global variable, it wouldn't have received any value by the time the `console.log()` line was reached, because `async` functions are, er, asynchronous. Move the `log` line inside the function.

**Comment by Jugoslav85** [comment]
> This is a JS question not a Puppeteer one, but the problem is that you have defined `data` to be local to the anonymous function, but are trying to access it from the global scope. Not to mention, even if it was a global variable, it wouldn't have received any value by the time the `console.log()` line was reached, because `async` functions are, er, asynchronous. Move the `log` line inside the function.

Thanks for the reply. That was my question. I want to be able to access the data variable from outside async. For example, I want to create a different page where I will display the output of the data variable.

Again, sorry if it doesn't make sense what I am asking, this is my absolute first attempt to create a functional app.

**Comment by jribbens** [comment]
I think you need to do some reading up on asynchronous JavaScript, your question does indeed not make sense ;-) You can get the value of `data` out of the function easily by putting `return data` as the function's last line, but you still need to wait for the async function to complete, either by 'await'ing it from another async function, or by calling `then()` on the `Promise` that it returns, e.g.
```javascript
;(async userUrl => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] })
  const page = await browser.newPage()
  await page.goto(userUrl, { waitUntil: 'networkidle2' })
  const data = await page.evaluate('Shopify.theme.name')
  await browser.close()
  return data
})('https://greats.com/').then(data => {
  console.log(`The result was ${data}!`)
})
```
Although you should certainly try and remove the `--no-sandbox` option if you can.

**Comment by Jugoslav85** [comment]
Thanks a lot, I somehow made it work with your help. 

Yes, I am aware I need to read about asynchronous JavaScript (and so many more stuff:)), I didn't have a chance to learn anything about it yet, but I found an interesting idea for a practice project and this issue was in my way.
