### ISSUE TITLE
Question: merge with playwright

### ISSUE THREAD

**Issue by Meir017** [puppeteer/puppeteer#5885]
https://github.com/microsoft/playwright is effectively doing the exact same thing but they also support webkit

Are there plans for this project to eventually support webkit?
Are there plans to archive this project and continue the work in playwright?

**Comment by mathiasbynens** [comment]
> Are there plans for this project to eventually support webkit?

https://github.com/puppeteer/puppeteer#q-what-is-the-status-of-cross-browser-support

**Comment by Meir017** [comment]
@mathiasbynens are there plans for collaboration with the playwright project?

**Comment by mathiasbynens** [comment]
We don't control the Playwright fork but we're always open to collaboration.
