### ISSUE TITLE
CDPSession.on is missing from the documentation

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#5886]
The `CDPSession.on()` method is mentioned briefly in the documentation but has no actual entry of its own.

**Comment by jackfranklin** [comment]
Hi @jribbens , this is because it gets that method from the `EventEmitter` class. 

Is there a way we can make this clearer, do you think? I can see how it would be easily missed.

**Comment by jribbens** [comment]
Making the mention of `CDPSession.on` be a hyperlink to `#eventemitteronevent-handler` would be a simple change that would probably help.

**Comment by Vance-Raiti** [comment]
Hi, I had a similar issue and had to track down this issue to get an answer. Could the hyperlink to `EventEmitter.on` be added to the CDPSession doc when it mentions the `CDPSession.on` event
