### ISSUE TITLE
pdf always print two page. last page always blank。

### ISSUE THREAD

**Issue by ystop** [puppeteer/puppeteer#589]
l want full webpage  in a pdf page,so l use this:

await page.pdf({path: 'page.pdf', 'fullPage':true, "printBackground" : true, "height": "5000px"});

my webpage only 3000px, so one pdf page is good . but l always got two pdf page and last pdf page always blank.

**Comment by ystop** [comment]
css is html,body:100% .  l think it is the reason

**Comment by aslushnikov** [comment]
@ystop can you provide a repro? Ideally, the script that I'd be able to run and observe the misbehavior.

**Comment by ystop** [comment]
@aslushnikov l can't find some other website observe the misbehavior. My site can't be posted online. l think l find this due to my css, l change it and  seem good. Thanks.

**Comment by TOPS-Aman** [comment]
@ystop What changes you made in the CSS? Can you please provide what actually caused the issue?

**Comment by Michaelknigth** [comment]
I Think  i pick and colect some ítems and mueve ot

**Comment by TOPS-Aman** [comment]
@Michaelknigth Thanks. But I am unable to read your reply.

**Comment by code4jhon** [comment]
@ystop yeah please provide what changes you have made.

**Comment by Aleix11** [comment]
I had the same problem and resolved it by removing 'html, body { height: 100% }' in the page.

**Comment by 2yk** [comment]
I also managed to do it by a hack, as I am not sure in my case for body height.

```
const height = await page.evaluate(() => document.documentElement.offsetHeight);
await page.pdf({ path: 'my.pdf', height: `${height + 1} px`, printBackground: true });
```

I added 1 px in page height and it removed the blank page. I know it may not an elegant solution but seems to work for me.

**Comment by PlopTheReal** [comment]
I'm having the same issue but @theyeshu trick doesn't seems to work. Any idea?

**Comment by pgeimer** [comment]
This happens to me when the first page is almost full of content and its about to move to the second page. It seems like the second page gets added a bit too early. Playing around with the margins wasn't helping for me.

**Comment by pgeimer** [comment]
Adding this CSS solved it for me:
````
body {
    margin: 0;
}
````
And adding ``margin-bottom: 0;`` to the last element.

**Comment by CLantigua2** [comment]
I came across this issue as well and the above didn't help my case exactly. I have a `.page` container div which handles sizing and separating the pages, here's the styling for that.
```css
  .page {
    background: white;
    display: block;
    margin: 0 auto;
    margin-bottom: 8.5em;
    /* Size = A4 */
    width: 21cm;
    height: 29.7cm;
    padding: 5em 30px 0 30px;
    position: relative;
  }
```

my solution involved using `last-of-type` to grab the last rendered `.page` class and pull back on the `margin-bottom`.
```css
.page:last-of-type {
    margin-bottom: -1px;
  }`

**Comment by dwoodworth91** [comment]
Riffing off of @CLantigua2's solution, here is something that worked for me:

`body > :last-child: {
    margin-bottom: -1px;
    overflow: hidden;
}`

**Comment by hi-hai** [comment]
Has same issue. The above solutions can't help.

```
const browser = await puppeteer.launch();
const page = await browser.newPage();

const html = `<html>
<head>
	<meta charset="utf-8" />
	<style>
		html {
			-webkit-print-color-adjust: exact;
		}
		body {
			margin: 0;
			padding: 0;
			background-color: orange;
		}
		body > :last-child {
			margin-bottom: -1px;
			overflow: hidden;
		}
		.page {
			width: 107px;
			height: 95px;
			text-align: center;
			background-color: #ccc;
			margin-bottom: 0;
		}
		.title {
			padding-top: 2px;
			font-size: 19px;
			font-weight: bold;
			line-height: 1.1;
		}

		.content {
			font-size: 12px;
			line-height: 1.2;
			margin-bottom: 0;
		}

	</style>
</head>
<body>
<div class="page">
	<div class="title">AAAA</div>
	<div class="content">BBBB</div>
</div>
</body>
</html>`;

await page.setContent( html, { waitUntil: 'domcontentloaded' } );
await page.emulateMedia('screen');
await page.pdf( {
		width: '107px',
		height: '95px',
		path: `test.pdf`
} );	

await page.close();
await browser.close();

```

Paste the above code to https://try-puppeteer.appspot.com/ you will see it generated two pages.

**Comment by CLantigua2** [comment]
@hi-hai I was able to resolve your issue by adding the following to the css styling.
```cs
		body {
			margin: 0;
			padding: 0;
			background-color: orange;
                         height: 100%; <--- added height
		}
		
		.page:last-of-type { <--- added last of type
                         margin-bottom: -2px;
                 }
		
```

Worked in the sandbox so hopefully it will for your use case as well.
