### ISSUE TITLE
Running on IBM cloud: "Error: Failed to launch the browser process!"

### ISSUE THREAD

**Issue by Ben79543** [puppeteer/puppeteer#5891]
I am running puppeteer on a cloud foundry instance in IBM cloud (ex bluemix) environment. 
It works fine on my dev machine on win10 - I am using it to create pdfs. But when installed in the cloud instance, it fails.
I run puppeteer 3.0.  I tried adding the nosandbox argument - same result.

When I start the app in the cloud which is a container running nodejs 12.16.1 this is the output: 

`2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR Unhandled Rejection at: Error: Failed to launch the browser process!
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at onClose (/home/vcap/deps/0/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at Interface.<anonymous> (/home/vcap/deps/0/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at Interface.emit (events.js:322:22)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at Interface.EventEmitter.emit (domain.js:482:12)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at Interface.close (readline.js:409:8)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at Socket.onend (readline.js:187:10)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at Socket.emit (events.js:322:22)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at Socket.EventEmitter.emit (domain.js:482:12)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at endReadableNT (_stream_readable.js:1187:12)
   2020-05-19T01:59:28.30+0200 [APP/PROC/WEB/0] ERR     at processTicksAndRejections (internal/process/task_queues.js:84:21)
   2020-05-19T01:59:28.31+0200 [APP/PROC/WEB/0] OUT {"level":50,"time":1589846368307,"pid":133,"hostname":"891f2c3e-4d82-4ba3-62dd-4759","msg":"Unhandled 
Rejection at: Error: Failed to launch the browser process!\n/home/vcap/deps/0/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n\n    at onClose (/home/vcap/deps/0/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)\n  
  at Interface.<anonymous> (/home/vcap/deps/0/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)\n    at Interface.emit (events.js:322:22)\n    
at Interface.EventEmitter.emit (domain.js:482:12)\n    at Interface.close (readline.js:409:8)\n    at Socket.onend (readline.js:187:10)\n    at Socket.emit (events.js:322:22)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21) - message: Failed to launch the browser process!\n/home/vcap/deps/0/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n"}`

This is my code: 
`async function GenerateReport(app, siteID, fileName, transporter, destinees) {
  console.log("Starting report generation for ", siteID);
  var siteData = await repository.loadReportData(siteID);
  await app.render('pages/site_weekly_report_01', { ...siteData }, async function (err, html) {
    if (err) console.log("error", err);
    const browser = await puppeteer.launch({ args: ["--disable-web-security"], headless: true });
    const page = await browser.newPage();
    await page.setJavaScriptEnabled(true);
    await page.setContent(html, [{ waitUntil: 'load' }]);
    var pdf = await page.pdf({format: 'A4'});
        //await page.waitFor(2000); // To allow for  file closing
    await uploadPDF(pdf, fileName);
    await browser.close();`
}
'

**Comment by alixaxel** [comment]
Seems like Bluemix doesn't have xlib (see also [Troubleshooting](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-aws-lambda)).

If you're willing, I suggest giving [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) a try (it might not work out of the box).

**Comment by Ben79543** [comment]
What I don't understand is that this lib looks installed: on the console:
`vcap@94eb33ee-db42-4b3a-63f7-9fe5:~$ apt search libX11
Sorting... Done
Full Text Search... Done
libx11-6/now 2:1.6.4-3ubuntu0.2 amd64 [installed,local]
  X11 client-side library

libx11-data/now 2:1.6.4-3ubuntu0.2 all [installed,local]
  X11 client-side library

libx11-dev/now 2:1.6.4-3ubuntu0.2 amd64 [installed,local]
  X11 client-side library (development headers)

vcap@94eb33ee-db42-4b3a-63f7-9fe5:`

**Comment by Ben79543** [comment]
I have tried to add the recommended librairies here:
https://techoverflow.net/2018/06/05/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-cannot-open-shared-object-file-no-such-file-or-directory/

A few of them can't be found for somne reason:
```
Unable to correct missing packages.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/libpam-systemd_229-4ubuntu21.23_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libg/libgd2/libgd3_2.1.1-4ubuntu0.16.04.11_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Aborting install.
```

I am discovering the IBM cloud delivery pipeline so I am not too sure what I am doing here....

**Comment by Ben79543** [comment]
Ok I managed to install successfully ALL packages by adding in the "BUILD" job:
```
npm install
sudo apt-get update
sudo apt-get install -y --fix-missing gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

```

Installation is fine without errors. Then I start the APP and I still get the same error, like if they were not installed. I must be doing something wrong. 

Error: Failed to launch the browser process!\n/home/vcap/deps/0/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

**Comment by shirshak55** [comment]
u can see docker file for what you need to install for chrome to work. first verify you can open chrome or chromium ?

**Comment by Ben79543** [comment]
Chrome fails the same way when launching it with CLI:

```
vcap@6efd4cb8-4978-493a-502b-514c:~/app/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux$ ./chrome
./chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
vcap@6efd4cb8-4978-493a-502b-514c:~/app/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux$ 

```
With IBM I might be able to use personalised images, but I try to keep it as simple as possible...

**Comment by shirshak55** [comment]
have u installed dependencies properly. Clearly u are missing libX11 dependency.

**Comment by Ben79543** [comment]
The dependencies seem to install well. I have only one error :
``
Setting up systemd (229-4ubuntu21.28) ...
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
Operation failed: No such file or directory
``

everything around x11 seems ok: 
`Selecting previously unselected package libx11-protocol-perl.
Preparing to unpack .../libx11-protocol-perl_0.56-7_all.deb ...
Unpacking libx11-protocol-perl (0.56-7) ...
Selecting previously unselected package x11-apps.
Preparing to unpack .../x11-apps_7.7+5+nmu1ubuntu1_amd64.deb ...
Unpacking x11-apps (7.7+5+nmu1ubuntu1) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../x11-utils_7.7+3_amd64.deb ...
Unpacking x11-utils (7.7+3) ...
Selecting previously unselected package x11-xserver-utils.
Preparing to unpack .../x11-xserver-utils_7.7+7_amd64.deb ...
Unpacking x11-xserver-utils (7.7+7) ...
`

But it's like it is not installed chrome still can't find it. 
I'm checking with IBM if I am installing dependencies the right way...

**Comment by Ben79543** [comment]
Ok got it sorted: 

What I was doing above in the deployment jobs was useless. It is NOT what will be deployed with the APP.

Instead, you need to deploy "multi buildpack" with the standard nodejs buildpack and also a buildpack specially made to install debian dependencies : https://github.com/cloudfoundry/apt-buildpack. example here: https://ict.swisscom.ch/2019/11/no-root-access-no-debian-packages-on-cloud-foundry-thats-past-with-the-apt-buildpack/

So for my nodejs app it ends up with: 
1- a specific apt.yml files containing the list of dependencies (note I had to add a couple more eg libgbm-dev)
2- a specific multi-buildpack.yml containing the list of buildpacks

And that is it. I run the usual build and deploy jobs, and puppeteer starts now. (the result of the pdf generation is without image so I must have something else wrong...but...)

**Comment by Ilmans** [comment]
> Ok I managed to install successfully ALL packages by adding in the "BUILD" job:
> 
> ```
> npm install
> sudo apt-get update
> sudo apt-get install -y --fix-missing gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
> ```
> 
> Installation is fine without errors. Then I start the APP and I still get the same error, like if they were not installed. I must be doing something wrong.
> 
> Error: Failed to launch the browser process!\n/home/vcap/deps/0/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

how to install it in cpanel?
