### ISSUE TITLE
Unexpected token when installing package

### ISSUE THREAD

**Issue by kavv-hub** [puppeteer/puppeteer#5894]
![image](https://user-images.githubusercontent.com/38276947/82281036-e8672380-99c2-11ea-9cf6-99730aab215c.png)

This exception raised when i try to install puppeteer@3.1.0, exception raised from: **node_modules\puppeteer\install.js:175**

**Comment by jackfranklin** [comment]
@kavv-hub which version of Node are you running?

**Comment by kavv-hub** [comment]
@jackfranklin I've noticed that I'm not using a correct version of node.  Thank you for your help. I'll close this issue.

**Comment by mahnunchik** [comment]
Yep, we have to use Nodejs 10+ 😉 https://github.com/nodejs/Release#release-schedule

**Comment by akildemir** [comment]
@mahnunchik for all puppeteer versions?? I am still using node 8.12 for some weird reason :D is there any release that is compatible with this version?

**Comment by mahnunchik** [comment]
@akildemir Sorry, I don't know. I've just upgrade to Node 12 =)

**Comment by wkdhkr** [comment]
`npm i -S puppeteer@2.1.1`
