### ISSUE TITLE
Need page.authenticate() for puppeteer firefox as soon as possible to use proxy with login and pass

### ISSUE THREAD

**Issue by RainNHard** [puppeteer/puppeteer#5896]
Hello devs who works on firefox, many thanks for your work! I want to ask why page.authenticate() is not working with firefox? This is a very important function, I do not understand why it was not implemented.
I can’t use normal functionality to work with proxies :(

**Comment by mjzffr** [comment]
Hi :) Firefox support is experimental while the team implements more protocol support. Lots of features are important to different groups, so we prioritize work in part by gathering data about the impact of specific use cases. 

If you'd like to tell the team about how your project is using Puppeteer (by pointing to a repo, sharing debug logs, or anything else) please reach out at https://wiki.mozilla.org/Remote -- thanks.

**Comment by RainNHard** [comment]
It is sad to hear. I would use chromium, but with headless: true- it cannot run a program on a computer using url, when headless: false - then the program starts without confirmation to start

**Comment by muhammadammarr** [comment]
Just curious if there is a way to bypass basic auth in case of Puppeteer Firefox yet?
