### ISSUE TITLE
Cannot capture all request headers

### ISSUE THREAD

**Issue by GkqqNkKC** [puppeteer/puppeteer#5908]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: core 2.0.0
* Platform / OS version: Windows 10
* Node.js version: 12.14.1

**What steps will reproduce the problem?**

I want to capture headers from all requests sent from Chrome. Using `Page.on("request", ...)` or `Page.on("response", ...)` shows only a limited amount of headers compared to what dev tools gui provide. I read some others issues based on this problem, and following them I came upon the following structure:

```js
let cdp = await page.target().createCDPSession()
cdp.on("Network.requestWillBeSent", request => {
    // code never ran
})
cdp.on("Network.responseReceived", response => {
    // code never ran
})
```

I just fetch the `Page`, did `page._client.send('Network.setBypassServiceWorker', {bypass: true})`, and after the code mentioned above is nothing, so no additional configures are made such as `setRequestInterception()` (which shouldn't influence it in any way, plus I tested it in some cases). The first 2 events I mentioned at the very beginning of the post are working

**What is the expected result?**
The code inside the lambdas to run

**What happens instead?**
`// code never ran`

**Additional**
Here's all code involving Puppeteer:
```js
let browser = await puppeteer.connect({
    defaultViewport: null,
    browserWSEndpoint: wsEndpoint
})
/** @type {puppeteer.Page} */ let page
if(match) {
    let pages = await browser.pages()
    for(let i = 0; i < pages.length; i ++)
        if(pages[i].url().match(match)) {
            page = pages[i]
            break
        }
}
else page = await browser.newPage()
if(!page)
    throw new PageException;
page._client.send('Network.setBypassServiceWorker', {bypass: true})
let cdp = await page.target().createCDPSession();
cdp.on("Network.responseReceived", /** @param {tools.Response} response */ response => {
    console.log(0);
})
```

**Comment by GkqqNkKC** [comment]
Any updates?

**Comment by hwride** [comment]
I believe you need to send a network enable message first, like so:
```javascript
await cdpSession.send('Network.enable')
```

I was also trying to capture all request headers in Puppeteer recently and have written some code here which worked for me: https://stackoverflow.com/a/62232903/6912455
