### ISSUE TITLE
Puppeteer chrome.exe processes does not appear to be killed

### ISSUE THREAD

**Issue by sjmittal** [puppeteer/puppeteer#5911]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.18.1
* Platform / OS version: Windows 10 Pro
* URLs (if applicable):
* Node.js version: 12.16.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
var browser = await puppeteer.launch({ .. })
var page = await browser.newPage();
...
await page.close();
await browser.close();
```

**What is the expected result?**
I assume that each `puppeteer.launch` would create instances of `chrome.exe` processes and they should get killed when I do `browser.close()`.

**What happens instead?**
However I notice is that in some cases if I run above code snipped in a while loop it spawns many instances of `chrome.exe` processes and they does not seem to be getting killed.

I am not able to isolate this case as I am not able to figure out why in some cases older instances of 'chrome.exe` process linger on even after the browser is closed.
_Note that when the node program exist, all such processes are killed too._

Is there a way to debug this issue better, or somehow force kill the chrome processes.

**Comment by nflorentin** [comment]
It seems to be an expected behaviour as you can read here: https://github.com/puppeteer/puppeteer/blob/936ccdca2c215068491a0d8d207ad3bf279a36ce/src/common/Browser.ts#L488

```  
/**
   * Disconnects Puppeteer from the browser, but leaves the Chromium process running.
   * After calling `disconnect`, the {@link Browser} object is considered disposed and
   * cannot be used anymore.
   */
  disconnect(): void {
    this._connection.dispose();
  }
```

After a few days, I'm having thousands of chrome processes. They are killed if I restart my nodejs app. I would like them to be killed after browser.close() but I don't know how to do it.

**Comment by nflorentin** [comment]
If it can help someone else, I added `--no-zygote` and `--single-process` to `launch` args and it solved the problem.
