### ISSUE TITLE
puppeteer not interacting elements which is inside "webview" tag

### ISSUE THREAD

**Issue by BabuShoban** [puppeteer/puppeteer#5917]
Hi All,

In my project we are using electronjs application, i am planning to automate functional scenarios using puppeteer. but i am facing issues with interacting elements inside "webview" tag. In browser i can able to access element present in "webview" tag but when angular integrated to electron i am facing this issue.

kindly give any suggestion anything is missing here and how to interact elements using puppeteer.

My code snippet:

const electron = require("electron");
const pie = require("puppeteer-in-electron")
const puppeteer = require("puppeteer-core");

(async ()=>{
    try{
        //pie.initialize(app)
        const app = await puppeteer.launch(
          {
          executablePath :  "C://Program Files//WindowsApps//sample.exe",
          headless: false,
          args: ["."],
          })

    const pages = await app.pages();
    const [page] = pages;
    console.log(page)
    await page.setViewport({ width: 408, height: 552 });
    await page.waitFor(3000)
    await page.click("#w-checkbox-4 + label")
    await app.close()
  } catch (error) {
    console.error(error);
    }
})();

*DOM structure*:

 <div id="title-bar" class="title-bar">
                <div id="overlay" class="over-title-bar" style="display: block;"></div>
                <div id="title" runat="server" nodeintegration="true"></div>
                <div id="title-bar-btns" unselectable="on">
                        <button id="close-btn" title="">
                                <img src="../assets/Gadget/Close.png" width="12px" height="12px">
                        </button>
                </div>
        </div>
        <div id="content" style="background: rgba(0, 0, 0, 0.5);">
                <div class="webview-wrapper">
                        <webview webviewtag="true" visibility="visible" id="Load-url" src="https://***********.com"&amp; preload="../webviewPreload.js" enableremotemodule="false" nodeintegration="false"></webview>
                </div>
        </div>
        <script>
                var exports = {};
        </script>

**Comment by BabuShoban** [comment]
Hi Team,

Any update on this

**Comment by BabuShoban** [comment]
@jackfranklin @mathiasbynens can you please help on the above issue or suggest any workaround to access electron <webview> tag?

**Comment by jackfranklin** [comment]
Is it possible for you to reproduce this and put up an example repository or similar? It's going to be hard to figure out from this I'm afraid.

**Comment by BabuShoban** [comment]
Thanks for the replay @jackfranklin  , I will create a repo for sample electron project and try to give an example asap.
