### ISSUE TITLE
Use the devtools-protocol npm package

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#5919]
Rather than maintain our own generation script we should instead just use the protocol package that's published to npm: https://www.npmjs.com/package/devtools-protocol

The types it generates are the same but AFAICT some are named differently. So it _should_ be a renaming job more than anything else.

**Comment by mathiasbynens** [comment]
Sounds good!

How is `devtools-protocol` versioned exactly? We need to be able to get definitions for the exact Chromium revision we ship.

**Comment by jackfranklin** [comment]
I'm not sure - it looks like it's versioned but do they map to the exact revisions we're shipping? e.g. the latest version on npm is https://www.npmjs.com/package/devtools-protocol/v/0.0.770484

**Comment by mathiasbynens** [comment]
Ah, indeed looks like it. `0.0.770484` -> `r770484` -> Chromium 85.0.4151.0. Alright, it's a go then!
