### ISSUE TITLE
Take a PNG screenshot and PDF in parallel

### ISSUE THREAD

**Issue by lzaiko** [puppeteer/puppeteer#5921]
Hi guys

Is it possible to take a **PNG** screenshot and a **PDF** in parallel using `Promise.all`?

The issue I have is that whatever I try, one conflicts with the other. Ex. some images in the PDF are missing or vice-versa.

It's like a race condition is taking place when the two operations run in the same time. Maybe they are competing for the same (internal) resources?!?!?

The idea is to save time, in my case between 15-30sec (I've many many pages).
What's the best way to do this operation in parallel? Maybe clone the page in a new TAB?

Help appreciated...
Thanks

**Comment by yhafri** [comment]
@aslushnikov any thoughts on that?
