### ISSUE TITLE
Better handle Chrome extension errors on browser launch

### ISSUE THREAD

**Issue by mattzeunert** [puppeteer/puppeteer#5922]
### Steps to reproduce

**What steps will reproduce the problem?**

1. Launch Chrome with an extension that doesn't exist or has some sort of error in its manifest

```
const puppeteer = require("puppeteer")
puppeteer.launch({
  args: ["--load-extension=/tmp/doesnt-exist"],
  ignoreDefaultArgs: ["--disable-extensions"],
  headless: false
}).then(() => { })
```

**What happens?**

There's an exception:

> UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.

Chrome displays an alert modal:

<img width="414" alt="Screenshot 2020-05-26 at 22 06 16" src="https://user-images.githubusercontent.com/1303660/82950505-51d7cb00-9f9d-11ea-8858-a9392e2b1a2d.png">

**What is the expected result?**

It would be nice if puppeteer crashed with a meaningful error message.

I run into this issue every now and then when running Puppeteer in Docker, so I don't know that there's an alert message. Chrome also doesn't print anything about the error to the console, so it's hard to identify the issue.

Is there something that can be done to handle this type of error better? Maybe there's some Chrome flag to make Chrome crash or log an actual error?

**Comment by nickserv** [comment]
I'd like to set up an automated extension installation test, specifically so the build will fail when the extension is invalid (I keep getting UTF-8 errors on content scripts that slip past CI). Currently I'm relying on the built-in timeout to fail the script after 30 seconds, but an official error handling mechanism like what @mattzeunert suggested would be faster and more reliable.
