### ISSUE TITLE
Massive CPU/RAM usage caused by using UserDataDir

### ISSUE THREAD

**Issue by jardayn** [puppeteer/puppeteer#5923]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:  "puppeteer": "^3.1.0", (Updating to latest version didn't help)
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable): Any URL
* Node.js version: 12.16.3
* Hardware Info: 4690k + 32Gbs of RAM + Puppeteer running on a good SSD

**What steps will reproduce the problem?**
Adding userDataDir to launch options will produce the problem. 
It will make page loads slower, CPU usage much higher and it will start eating RAM.  
This happens on a number of pages. Behavior is pretty reliable. 
Task manager shows the CPU usage mainly by chrome. 

Deleting the dataDir doesn't change anything

Removing the setting results in dramatically lower CPU usage..

_Please include code that reproduces the issue._
```
const puppeteer = require('puppeteer');
var os = require('os-utils');
//This be a promise ,
const browserPromise = puppeteer.launch({ headless: true,userDataDir: './puppeteer_data'  }).then(async browser => {return browser})

function getCpuUsage(){
    os.cpuUsage(function(v){
        console.log( 'CPU Usage (%): ' + v );
    });
}

async function testScrape(url){
    console.log('processing: '+url)
    let r = Math.random().toString(36).substring(7);
    let browser = await browserPromise
    getCpuUsage()

    let page = await browser.newPage();

    await page.goto(url);
    console.log('went to url: '+url)
    getCpuUsage()

    await takeScreenShot(page,r+'initialLoad.png');
    getCpuUsage()
}

async function takeScreenShot(page,fileName){
    page.screenshot({path: 'screenshots/'+fileName,fullPage: true});
}

async function run(){
    await testScrape('https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md')
    await testScrape('https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md')
    console.log('Donezo')
}
run()

```

**What is the expected result?**
Expected it to not start abusing my CPU like there's no tomorrow

**What happens instead?**
It did it anyway.

**Comment by schelkun** [comment]
Can confirm this issue.
Headless mode with userDataDir is not working at all.

Example:

```js
(async () => {
    const browser = await puppeteer.launch({userDataDir: './test_user/', args: [
        '--no-sandbox'
    ]});
    
    const page = await browser.newPage();
    await page.goto('https://github.com/puppeteer/puppeteer');
 
    console.log('Loaded');
    
    console.log('Evaluate');
 
    for (let i = 0; i <= 10; i++) {
        await page.evaluate(() => {});
        console.log('Done evaluating #', i);
    }

    await browser.close();
})();

```

**Comment by NikolaiSilver** [comment]
I run tests at CI with latest Chrome in docker. Can confirm , that I had extremely test speed degradation ( from 3 min => to 20). Seems like it relates to CPU ( tests started fast and than I see speed degradation from test to test). So I used to rollback on Chrome 79 

Stack : 
Puppeteer v 3.1.0
Headless Chrome  in Docker 
Jenkins CI 
Jest 25.01

**Comment by suchcodemuchwow** [comment]
I had exact same issues that you guys mentioned. The solution worked out for me was changing userDataDir path to absolute path. Instead of this: `userDataDir: 'data'` use this: `userDataDir: '/Users/batu/Desktop/status/data'`

**Comment by lebanggit** [comment]
@suchcodemuchwow Thank you. You are saved me!!!

**Comment by nexcode** [comment]
@suchcodemuchwow Yes! Thank you very much!

**Comment by Write** [comment]
Can confirm the issue.
Thanks @suchcodemuchwow for the solution
