### ISSUE TITLE
Question - How to wait for await page.$('selector')

### ISSUE THREAD

**Issue by sfelice777** [puppeteer/puppeteer#5925]
I know how to use await page.waitForSelector('selector')

I want to do the same thing for await page'$('selector')

Here is what I have so far-

async getIsVisible(element) {
    If (await element === null) {
        return false
    }
    return Boolean(await element.evaluate(e => (s = window.getComputedStyle(e)) => s.display !== 'none' && s.visibility === 'visible' && s.opacity !== '0'))
}

I'd like to have it keep trying for 30 seconds.

It would be nice if I could just do this-
const element = page.$('selector')
await element.waitForSelector()
Or
await page.waitForSelector(element) 

Thanks!

**Comment by chenfan-fchen** [comment]
you can try
`await page.waitForSelector(`selector`)`
eg: await page.waitForSelector('input[type="email"]')

**Comment by sfelice777** [comment]
That's still using a string.
I don't want to use a string.
I want to use - await page'$('selector')

**Comment by mathiasbynens** [comment]
Use `page.waitFor` and pass your function that checks for visibility as the callback. https://github.com/puppeteer/puppeteer/blob/v3.3.0/docs/api.md#pagewaitforselectororfunctionortimeout-options-args

**Comment by sfelice777** [comment]
All of the examples on that page are still using a string.
