### ISSUE TITLE
Question - How do I pass "RegExp Object ??"

### ISSUE THREAD

**Issue by Ken099** [puppeteer/puppeteer#5926]
Regarding page.evaluate method...

I want to use "replace" method. But I can not pass RegExp objects....

example)
const result = await page.evaluate(x => {
  return Promise.resolve(8 * x);
}, 7);
console.log(result); // prints "56" <=SUCCESS!!

const result = await page.evaluate(x => {
  const a = "apple"
  return Promise.resolve(a.replace(x, "banana"));
}, "apple");
console.log(result); // prints "banana" <=SUCCESS!!

const result = await page.evaluate(x => {
  const a = "apple"
  return Promise.resolve(a.replace(x, "banana"));
}, /apple/);
console.log(result); // prints "apple" <= failure...

Thanks!

**Comment by sfelice777** [comment]
If I'm understanding you correctly-

You need the evaluation to give a result and then do something with the result.

const element = await page.$('selector')

const elementText = await element.evaluate(e => e.innerText)
const result = elementText * 8
console.log(result)

Or all in one line-
const result = await element.evaluate(e => e.innerText) * 8
console.log(result)

const elementText = await element.evaluate(e => e.innerText)
const result = elementText .replace('banana', 'apple')
console.log(result)

**Comment by dmathijs** [comment]
If I'm not mistaken, the object that you pass should be serializable. Since there is no canonical representation for a regex expression, this won't work. (https://pptr.dev/#?product=Puppeteer&version=v4.0.0&show=api-pageevaluatepagefunction-args)

You will have to define it in the scope of the evaluate function and apply some kind of strategy pattern.

**Comment by dpmott** [comment]
You could specify the regex pattern as a string, pass the string, and then pass that string to `new Regexp(pattern_string)` inside your  `page.evaluate()` function body.
