### ISSUE TITLE
Should page.url include the URL fragment?

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#5927]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.1.0
* Platform / OS version: Mac OS 10.15.4
* URLs (if applicable):
* Node.js version: v12

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://tools.ietf.org/html/rfc6265#section-8');
  console.log(page.url());
  console.log(await page.evaluate(() => document.location.href));
})();

```

**What is the expected result?**

Should `page.url()` include the URL fragment. If not, shouldn't we expose that somehow?

**What happens instead?**

URL Fragment is ignored.

I'm willing to push a PR implementing the final decision.

**Comment by jackfranklin** [comment]
@mathiasbynens WDYT?

**Comment by superzoey** [comment]
i have the same problem

**Comment by pf-joao-schmitt** [comment]
How can this be closed if nobody from the team answered?
