### ISSUE TITLE
Unable to catch page crash error when happening on browser.newPage

### ISSUE THREAD

**Issue by avner-solomon** [puppeteer/puppeteer#5928]
* Puppeteer version: 3.1.0
* Platform / OS version: Windows 2016 / Windows 10
* URLs (if applicable): no url
* Node.js version: 12.16.1
* Chrome version 83.0.4103.61 (Official Build) (64-bit) (but happens also on chromium)

There are no reproduction steps. I run a few thousands instances of our bot per server per day. We noticed though it randomly blocks and after further inspection we isolated that it happens at the browser.newPage() call. The issue here is that it throws Page crashed right away. Also there seems to be no way to intercept said page crash.

```
0|eater  | 28-05 04:21:26.054: here1
0|eater  | 28-05 04:21:26.055: Trace
0|eater  | 28-05 04:21:26.055:     at Object.runTask (C:\adwallet-eater\src\eater-puppeteer.js:478:18)
0|eater  | 28-05 04:21:26.055:     at runMicrotasks (<anonymous>)
0|eater  | 28-05 04:21:26.055:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|eater  | 28-05 04:21:26.055:     at async run (C:\adwallet-eater\src\eater.js:15:4)
0|eater  | 28-05 04:21:26.055: Trace
0|eater  | 28-05 04:21:26.055:     at Object.runTask (C:\adwallet-eater\src\eater-puppeteer.js:482:18)
0|eater  | 28-05 04:21:26.055:     at runMicrotasks (<anonymous>)
0|eater  | 28-05 04:21:26.055:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|eater  | 28-05 04:21:26.055:     at async run (C:\adwallet-eater\src\eater.js:15:4)
0|eater  | 28-05 04:21:26.056: here2
0|eater  | 28-05 04:21:26.056: here24
0|eater  | 28-05 04:21:26.277: Error: Page crashed!
0|eater  | 28-05 04:21:26.277:     at Page._onTargetCrashed (C:\adwallet-eater\node_modules\puppeteer\lib\Page.js:200:28
)
0|eater  | 28-05 04:21:26.277:     at CDPSession.<anonymous> (C:\adwallet-eater\node_modules\puppeteer\lib\Page.js:120:5
7)
0|eater  | 28-05 04:21:26.277:     at CDPSession.emit (events.js:311:20)
0|eater  | 28-05 04:21:26.277:     at CDPSession.EventEmitter.emit (domain.js:482:12)
0|eater  | 28-05 04:21:26.277:     at CDPSession._onMessage (C:\adwallet-eater\node_modules\puppeteer\lib\Connection.js:
166:18)
0|eater  | 28-05 04:21:26.277:     at Connection._onMessage (C:\adwallet-eater\node_modules\puppeteer\lib\Connection.js:
83:25)
0|eater  | 28-05 04:21:26.277:     at WebSocket.<anonymous> (C:\adwallet-eater\node_modules\puppeteer\lib\WebSocketTrans
port.js:25:32)
0|eater  | 28-05 04:21:26.277:     at WebSocket.onMessage (C:\adwallet-eater\node_modules\ws\lib\event-target.js:125:16)

0|eater  | 28-05 04:21:26.277:     at WebSocket.emit (events.js:311:20)
0|eater  | 28-05 04:21:26.277:     at WebSocket.EventEmitter.emit (domain.js:482:12)
```

My biggest worry for above output is that my code in this section is the following

```
console.log('here2')
console.trace()
let page = false
try {
	console.log('here24')
	page = await browser.newPage()
	page.on('error', err => {
		console.log('here4')
		console.error(err)
	})
} catch (e) {
	console.error(e)
	console.log('here25')
}
console.log('here3')
console.trace()
```

When above error happens the code never goes past the `browser.newPage()` line making impossible to intercept and attempt creating another page. Also nodejs just remains frozen in that state. TBH I do not really care what causes the page crash and why cause I can accept that chrome will randomly have stability issues out of the scope of puppeteer. My real issues is the inability to catch a page crash if it happens when creating a new page.

We are not reusing the browser. We start a new browser for each test case with
```
ignoreHTTPSErrors: true,
defaultViewport: {
	width: options.resolution.width,
	height: options.resolution.height
}
```
as the only flags

**Comment by avner-solomon** [comment]
the only solution for the time being i found at the moment (ugly as my it seem) is using a Promise.race on newPage() and a timeout and making retries when timeout is reached

**Comment by avner-solomon** [comment]
overall puppeteer 3.1.0 + chrome 83 seem really really unstable

**Comment by epexa** [comment]
#1454

**Comment by epexa** [comment]
#6277

**Comment by epexa** [comment]
#3709

**Comment by epexa** [comment]
@avner-solomon check this solution: https://github.com/puppeteer/puppeteer/issues/1454#issuecomment-945575831
