### ISSUE TITLE
something wrong with 'page.screenshot({path: `${guid}.png`, fullPage: true});'

### ISSUE THREAD

**Issue by ylscsdb** [puppeteer/puppeteer#593]
```javascript
const browser = await puppeteer.launch({
        headless: false    //have tried false or true
    });
const page = await browser.newPage();
await page.setCookie(
        {
            name:'id',
            value:'111'
        },
        {
            name:'ddd',
            value:'sss'
        }
    );
 // await page.emulate(devices['iPhone 6']);  //have tried used or not

await page.goto(url, {
        waitUntil: 'networkidle'
    });


await page.screenshot({path: `${guid}.png`, fullPage: true}); //using fullpage parameter 

```
The save page is also the current screen whether adjust the parameter of headless or device. Did i use it wrong?

**Comment by aslushnikov** [comment]
@ylscsdb I don't follow what's the problem with the script. What do you expect it to do and what happens instead?

**Comment by ylscsdb** [comment]
I know the problem. Because the navigator bar of my page is in the div of the body, can‘t capture the whole page using the "page.screenshot({path: `${guid}.png`, fullPage: true})".

**Comment by aslushnikov** [comment]
@ylscsdb I don't understand what's going on here. Could you please:
1. Tell if there's a bug or this issue could be closed
2. If there's a bug, share a full code snippet *including URL you try to load*
3. Explain what's the expected output of the script and what do you see instead
