### ISSUE TITLE
Need to take a screenshot from an iframe that loads the content from external sources

### ISSUE THREAD

**Issue by aadilwani** [puppeteer/puppeteer#5935]
I need to take a screenshot from an iframe that I am adding using page.SetContent('<iframe src="....">);. The issue is my Iframe is making external requests to get the content. Once all the content is received and displayed in the Iframe I need to take the screenshot.

**Comment by vsemozhetbyt** [comment]
You can try to find the frame by its URL among the `page.frames()` elements and then use `frame.waitForSelector()` with this frame waiting for some selector available on the iframe complete loading.

**Comment by aadilwani** [comment]
The content is dynamic i dont know what selectors are there.
