### ISSUE TITLE
Trying to click a div element which match my requirement in puppeteer

### ISSUE THREAD

**Issue by lmk07** [puppeteer/puppeteer#5936]
Hi guys, 
             i'm automating one web page and facing issue in clicking particular date in date picker. i need to click a date which is based on user input. here is the code which im using

      var date = '15'
        await page.$$eval(".week div",(elements)=> elements.map(item=>{
          if(item.textContent == date){
            item.click()
          }
        }))

here im not able to compare "temp" and "item.textContent". 

but if use a code like below its working fine.

 await page.$$eval(".week div",(elements)=> elements.map(item=>{
          if(item.textContent =='15'){
            item.click()
          }
        }))
but i need to compare as dynamic.
please help me to get out of this. thanks in advance

**Comment by sfelice777** [comment]
Normally, I do this in a for i loop checking the text of each element in the array[i].
Then if I find a match, I click the element based on [i].
Then break from the loop so it doesn't keep checking any more elements in the element array.

**Comment by vsemozhetbyt** [comment]
You need to send the `date` variable into the browser context of the evaluated function as an argument:
```js
var date = '15'
await page.$$eval(".week div", (elements, userDate) => elements.map(item => {
  if (item.textContent == userDate) {
    item.click()
  }
}), date)
```

**Comment by lmk07** [comment]
> ```js
> userDate
> ```

@vsemozhetbyt  Dude, ur help is lot to me dude, thanks for ur help, it worked...
