### ISSUE TITLE
Can't see any styles on debug mode (non headless and devtools)

### ISSUE THREAD

**Issue by Richacinas** [puppeteer/puppeteer#5939]
### Steps to reproduce

* Puppeteer version: 3.0
* Platform / OS version: Ubuntu 18.04 LTS
* URLs (if applicable):
* Node.js version: 10.14

1. Launch puppeter with `headless: false` and `devtools: true` parameters. Sourcemaps are enabled on settings.
2. When the Chromium instance opens up, try to inspect any of the elements of your dom.
3. As you can see on the image, styles tab is just blank. Empty. 

**What is the expected result?**

I would expect to be able to inspect, add, toggle styles as usual.

**What happens instead?**

Styles tab remains blank.

![56579965-c76eac00-65d1-11e9-9ef7-ba5cd4377603](https://user-images.githubusercontent.com/7046504/83244259-5ff53980-a19f-11ea-9d65-82593a3bd0ce.png)

Here, you can see all the JS and CSS resources loaded. They load, because everything looks in place just like expected, but styles tab remains blank.

![Captura de pantalla de 2020-05-29 11-28-17](https://user-images.githubusercontent.com/7046504/83244425-a0ed4e00-a19f-11ea-9fcc-52b1dea2707d.png)

**Comment by Richacinas** [comment]
I suspect this is an issue with Puppeteer. They replied here at Chromium and it seems that it should work ok:

https://bugs.chromium.org/p/chromium/issues/detail?id=1087786#c2

**Comment by goulu** [comment]
any news on this ? I really need to understand why my styles are not the same in puppeteer tests as in the app...

**Comment by shkleinik** [comment]
Styles seems to appear after page reload, at least it is the case for me 🤞
