### ISSUE TITLE
Page.screenshot results in "TypeError: mime.getType is not a function" with Puppeteer v3.2.0

### ISSUE THREAD

**Issue by xprudhomme** [puppeteer/puppeteer#5945]
**My environment:**

* Puppeteer version: v3.2.0
* Platform / OS version: Ubuntu  16.04.6 LTS
* Node.js version: v12.13.1

**What steps will reproduce the problem?**
- Open a webpage with Puppeteer, such as: https://www.tripadvisor.fr/Restaurants-g187147-Paris_Ile_de_France.html
- Then try to take a screenshot, such as:

```javascript
await page.screenshot({
   path: "/tmp/test-tripadvisor.png",
  fullPage: true,
);
```

**What is the expected result?**
- We should obtain the full-page screenshot saved at `/tmp/test-tripadvisor.png` (this is working perfectly fine with Puppeteer v3.0.0, I havent' tested with v3.1.0)

**What happens instead?**
- We obtain this error:

`(node:19576) UnhandledPromiseRejectionWarning: TypeError: mime.getType is not a function
    at Page.screenshot (/home/dev/node-ghost/node_modules/puppeteer/lib/Page.js:651:35)
    at Page.<anonymous> (/home/dev/node-ghost/node_modules/puppeteer/lib/helper.js:117:27)`

**Comment by mathiasbynens** [comment]
Could you please post the full script to reproduce the issue?

**Comment by caida-ricky** [comment]
I solved this problem by (re)installing the mime module
`npm i mime`

**Comment by sorveywu** [comment]
> I solved this problem by (re)installing the mime module
> `npm i mime`

thks, i reinstalled and it works!

**Comment by nicolas-t** [comment]
Reinstalling didn't work for me.

I fixed it by adding the `type` param : 

```js
await page.screenshot({
	path: "/tmp/test-tripadvisor.png",
	fullPage: true,
	type: 'png' // <-
})
```
