### ISSUE TITLE
Not selecting certificate with Chrome in Headless mode (not selecting at all for Chromium)

### ISSUE THREAD

**Issue by mpalavrov** [puppeteer/puppeteer#5946]
Dear all,

Currently, I have an issue with opening a website with Chromium and Chrome. The website has certificate.
For Chrome, I have the certification added in the registry "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\AutoSelectCertificateForUrls"
and is working with puppeteer with NON HEADLESS MODE (headless: false), but in HEADLESS mode (headless:true) it is not working.

The error I have is:
net::ERR_BAD_SSL_CLIENT_AUTH_CERT at https://XXXXXXXXXXXX.net

For Chromium, it is not working at all, as in NON Headless mode it is not taking the certificates as added in the registry, and for the headless is same.

Can you please assist?

Cheers,

**Comment by galegobr01** [comment]
I have the same problem

**Comment by mpalavrov** [comment]
@galegobr01, lets hope someone can assist here. If any additional details are needed in order someone to investigate, please let us know. Thank you guys.

**Comment by galegobr01** [comment]
Thanks

**Comment by mpalavrov** [comment]
Hello all, I hope someone that has more experience here can comment and assist?

**Comment by mpalavrov** [comment]
Someone any update here ? :(

**Comment by mpalavrov** [comment]
Hello guys,

Isn't there someone that can assist here?

Thank you.

Cheers,
Milen

**Comment by bramvanhoutte** [comment]
@mpalavrov I have been trying this as well.(I haven't found a solution either)
What I have come across in my struggles is that Chrome doesn't support setting policies in headless mode. So this goes a bit further then puppeteer. A kind of "nothing we can do" situation.

As for the reason it doesn't work in Chromium. Chrome and Chromium policies have to be set differently if i'm not mistaken, so you'll have to set another registry key for Chromium.

**Comment by mpalavrov** [comment]
@bramvanhoutte, Thanks for trying this one. I also already knows that it is actually not related to puppeteer, but isn't there any workaround to select certificates in Headless... :(

In regards the different registry keys for Chromium, I have found how to set them and it is working in NON Headless mode.

Thank you again.

Cheers,
MIlen

**Comment by miguelpieras** [comment]
@mpalavrov thank you for your input. Could you please detail how you set different registry keys for Chromium?

**Comment by mpalavrov** [comment]
Hello @miguelpieras,
As I don't have it configured now, please check this issue - https://stackoverflow.com/questions/31510054/chrome-certificate-settings-in-registry
and create the same Registry as for Chrome, but or Chromium
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chromium\AutoSelectCertificateForUrls]

Please check https://chromeenterprise.google/policies/#AutoSelectCertificateForUrls as well, again, just create the same for Chromium

**Comment by sidorvm** [comment]
The issue still happening
