### ISSUE TITLE
page.select() doesn't work for multi-select using variable

### ISSUE THREAD

**Issue by vickyRathee** [puppeteer/puppeteer#5948]
This works fine, when I am using static values in `page.select()` for multi-select

```
// Select multiple desserts
const response = await page.goto('http://demo.imacros.net/Automate/TestForm1');            
await page.select("#dessert", "chocolate cake", "apple pie");
await page.screenshot({path : 'form.png'});
```

This doesn't work when I am passing the `desserts` variable, I tried using join(), map() to make it comma separated string; also tried to use the array directly in select(). But none of them works.

```
// Select multiple desserts
const response = await page.goto('http://demo.imacros.net/Automate/TestForm1');            
let desserts= request.desserts.map(x => `'${x}'`).join(',');
console.log(desserts);  // 'chocolate cake','apple pie'
await page.select("#dessert", desserts);
await page.screenshot({path : 'form.png'});
```

Here is example code -
https://chrome.agenty.com/#/!/examples/9-auto-fill-web-form.js

![puppeteer](https://user-images.githubusercontent.com/6106479/83343984-e2f0ce00-a31e-11ea-9e3f-f17aba419828.png)

**Comment by vsemozhetbyt** [comment]
It seems, by docs, `page.select()` just needs separate arguments for each selected item - not a single string or array. You can use spread operator for this:
```js
// const desserts = ['chocolate cake', 'apple pie'];
await page.select("#dessert", ...desserts);
```

**Comment by vickyRathee** [comment]
@vsemozhetbyt thanks for the help. It's working fine, I've updated my example on github for other users. https://github.com/Agenty/puppeteer-examples/blob/master/function/9-auto-fill-web-form.js
