### ISSUE TITLE
Launching Firefox on Windows fails on CI

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#5955]
@whimboo @mjzffr we're seeing this test fail on Windows CI builds when launching FireFox: https://github.com/puppeteer/puppeteer/pull/5954

We initially disabled the test because our Windows CI was so flakey it was impossible to know if it was a genuine bug or not but it now does appear to be as our CI on Windows has been very stable until this test got re-enabled.

That PR above defers the test for another month, in the meantime would you mind having a look if you get a chance?  

Thanks!

**Comment by jackfranklin** [comment]
Update: there's actually two tests causing Windows issues : https://github.com/puppeteer/puppeteer/pull/5954/files

Would you mind looking at both? Please shout if I can help :)

**Comment by mjzffr** [comment]
@jackfranklin The one in headful.spec.js is under `describeChromeOnly` so you should probably take a look. :)

**Comment by whimboo** [comment]
@jackfranklin isn't that just a dupe of issue #5673?

**Comment by jackfranklin** [comment]
> @jackfranklin The one in headful.spec.js is under describeChromeOnly so you should probably take a look. :)

🤦 thank you! I guess I'll take that one ;)

**Comment by jackfranklin** [comment]
@whimboo good point, thanks. I'll close this one and we can track in there
