### ISSUE TITLE
Blank images when webgl rendering?

### ISSUE THREAD

**Issue by antucg** [puppeteer/puppeteer#5961]
* Puppeteer version: 3.3.0 / 3.2.0 / 3.1.0
* Platform / OS version: Linux (Docker)
* Node.js version: v10.15.3

The error I want to talk about is not about a specific piece of code or configuration. I am using puppeteer to render some images using the headless version of Chrome. It has been working fine until the newer versions have been release.

When the images have some filters applied to it (contrast, saturation, etc., from Fabric.js), they are rendered blank. If I remove these filters then they are rendered correctly. I have tried the versions I mention above this paragraph and none of them worked. I was on 3.0.0 and it was fine, now I am on 3.0.4 and it also works.

I think it is more a Chromium problem than puppeteer as in version 3.1.0 a new version was supported, so I guess it is automatically installed too.

Any idea if this is the real problem, and it is the case, where to report it?

Regards.

**Comment by clementmas** [comment]
Hey @antucg, I'm having the same issue taking screenshots of [Mapbox GL maps](https://www.mapbox.com/maps). It was working fine until a recent release.

Did you find the source of the problem? Did you manage to fix it?

Thanks!

**Comment by antucg** [comment]
Nope, the only solution I have (if you can call it like that), is to use puppeteer 3.0.4. This is the latest version that doesn't have the problem, and I guess it is due to the fact that is using an older version of Chromium that doesn't have that bug/problem.

**Comment by daveisfera** [comment]
I'm seeing this issue as well and here's a reproducer using docker:

1) Build the container following [these instructions](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker)
2) Run the container using the command in those instruction: `docker run -i --init --rm -v /tmp:/tmp puppeteer-chrome-linuxl node -e "$(cat yourscript.js)"`

Here's the contents of `yourscript.js` (NOTE: I've added `--no-sandbox` so `--cap-add=SYS_ADMIN` isn't needed when running the container):
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        args: ['--no-sandbox'],
        executablePath: '/opt/google/chrome/chrome',
    });
    const page = await browser.newPage();
    await page.goto('https://get.webgl.org/');
    await page.screenshot({ path: '/tmp/test_webgl.png' });
    await page.pdf({ path: '/tmp/test_webgl.pdf' });

    await browser.close();
})();
```

If you look the PNG has the WebGL content from the page but the PDF doesn't.

**Comment by daveisfera** [comment]
Since it was implied that this was caused by a recent version of chrome, I decided to try older versions and I'm seeing the same issue. Here's a `Dockerfile` that can be used to test old versions of chrome (NOTE: version 76 and before crash):
```
FROM node:12-slim

# Install the dependencies for installing chrome
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
                          fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libgbm1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6 xdg-utils \
                          lsb-release \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Install old version of chrome
#ARG CHROME_VERSION="81.0.4044.138-1"
#ARG CHROME_VERSION="80.0.3987.163-1"
#ARG CHROME_VERSION="79.0.3945.130-1"
#ARG CHROME_VERSION="78.0.3904.97-1"
ARG CHROME_VERSION="77.0.3865.120-1"
#ARG CHROME_VERSION="76.0.3809.132-1"
RUN wget --no-verbose -O /tmp/chrome.deb http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
  && apt install -y /tmp/chrome.deb \
  && rm /tmp/chrome.deb

# Skip the chromium download since chrome is already installed
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN npm i puppeteer@3.0.4

CMD ["google-chrome-stable"]
```
