### ISSUE TITLE
Can i bundle puppeteer to use it in an extension i'm building ?

### ISSUE THREAD

**Issue by babahadjsaid** [puppeteer/puppeteer#5963]
i'm trying to build a chrome extension to be able to scrape some data which requires to be fetched outside the users tab it's basically going to take a list of urls from a page that the user is and then tries to enter each url and scrape data from it know i'm trying to get puppeteer to do this but i can't find a way to bundle it so that i can use it to build the extension 
i also tried to download an older versions like bump-v2.1.0 i did managed to bundle this one 
but when i run the extension and tried to launch a browser it give me this error
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at bundle.js:9487
    at new Promise (<anonymous>)
    at promisified (bundle.js:9479)
    at ChromeLauncher.launch (bundle.js:5280)
    at module.exports.launch (bundle.js:8459)
    at Scraper (main.js:4)
    at main.js:10

the newer versions i couldn't even be able to bundle 'em they kept giving this error
> browserify -r ./index.js:puppeteer -o bundle.js
>>Error: module not found: "ws" from file /media/kali/tools/web_developments/extension/linkedin/puppeteer_core/node_modules/puppeteer-core/lib/WebSocketTransport.js
    at onresolve (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:182:30)
    at /usr/lib/node_modules/browserify/index.js:537:20
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/index.js:247:21
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:175:21)

any help

**Comment by lucaswalter** [comment]
+1 could also use some assistance with this.

**Comment by ghost** [comment]
can you give an example of something you want to do?

**Comment by person-al** [comment]
Hi! I'm also wondering when puppeteer-core will be bundled for the browser. According to puppeteer-core's documentation, the benefit of pupeteer-core is:
> puppeteer-core is intended to be a lightweight version of Puppeteer for launching an existing browser installation or for connecting to a remote one. Be sure that the version of puppeteer-core you install is compatible with the browser you intend to connect to.

However, as it's not currently bundled for the browser, it's not possible to use pupeteer-core in javascript tools built to run outside of node. When will we see puppeteer-core bundled for the browser?

**Comment by motasimmakki** [comment]
Hey there @babahadjsaid, I'm also facing the same issue now, could you help me that how did you deal with it?
