### ISSUE TITLE
Failed to launch the browser process! on windows with the default bundled chromium

### ISSUE THREAD

**Issue by niklass08** [puppeteer/puppeteer#5969]
### Steps to reproduce
Hello,
I'm trying to use puppeteer to navigate to a page and generate a pdf render of the said page. It works just fine on inside a docker with linux but I am encountering problems with the chromium that is bundled with puppeteer on windows.

**Tell us about your environment:**
* Puppeteer version: 3.3.0
* Platform / OS version: Windows 10 pro / version : 1903 / OS Version : 18362.836
* Node.js version: v12.16.3

**What steps will reproduce the problem?**
Just trying to launch the browser is enough.

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ignoreDefaultArgs: ['--disable-extensions']});
    const page = await browser.newPage();
    await page.goto('https://example.com');
    console.log(await page.content());
    await browser.close();
})();
```

**What is the expected result?**
Navigate to https://example.com and log the page content

**What happens instead?**
```
(node:21156) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (*****\reproduce puppeteer\node_modules\puppeteer\lib\launcher\BrowserRunner.js:159:20)
    at ChildProcess.<anonymous> (*****\reproduce puppeteer\node_modules\puppeteer\lib\launcher\BrowserRunner.js:150:76)
    at ChildProcess.emit (events.js:322:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
(node:21156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Thanks in advance for your help

**Comment by chenfan-fchen** [comment]
I'm running your script in my env, everything works fine.
My env: Mac 
```
 "puppeteer": "^2.1.1",
  node: v10.16.3
```
And I added the arg 
`const browser = await puppeteer.launch({ignoreDefaultArgs: ['--disable-extensions'], headless: false});`
I can see the page successfully loaded

**Comment by niklass08** [comment]
The issue seems to be on windows as I am able to run my script just fine inside of linux container.

On the other hand I dowgraded puppeteer to v1.20.0 and it seems to be the latest version that works on windows for me but it is not a solution to my issue as 1.20 dependencies are breaking other parts in my project ...
