### ISSUE TITLE
Puppeteer ignoring lang arg to launch

### ISSUE THREAD

**Issue by kahunacohen** [puppeteer/puppeteer#5970]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.10
* Platform / OS version: OSX 10.14.6
* URLs (if applicable):
* Node.js version: 10.9.0

**What steps will reproduce the problem?**

1. npm install puppeteer
2. run the following code:

```js
const puppeteer = require("puppeteer");

(async function() {
  const u = "https://www.google.com/search?q=foo"
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--lang="en-US"'],
  });
  page = await browser.newPage();
  await page.goto(u);
})();
```
4. I am in Israel the results are in Hebrew and sometimes German oddly enough. 
5. When I launch my local chromium like this:
`$ node_modules/puppeteer/.local-chromium/mac-756035/chrome-mac/Chromium.app/Contents/MacOS/Chromium  --lang="en-US"`
and search for "foo" my results are in English.

**What is the expected result?**
Chromium should be launched in the language specified by the lang arg.

**What happens instead?**
Chromium seems to launch in the language of my location and ignores the lang arg to launch.
<img width="878" alt="Screen Shot 2020-06-04 at 3 38 34 PM" src="https://user-images.githubusercontent.com/1248329/83757646-799ff080-a679-11ea-8649-da5ad3c55d4d.png">

**Comment by chenfan-fchen** [comment]
try to add one line code between your script like this:
```
page = await browser.newPage();
await page.setExtraHTTPHeaders({
        'Accept-Language': 'en'
    });
  await page.goto(u);
```

**Comment by kahunacohen** [comment]
Sorry, that doesn't work either, same results. I've heard other people have issues with Mac OSX and the language. See https://stackoverflow.com/questions/46908636/how-to-specify-browser-language-in-puppeteer. Full script now is this:

```js
const puppeteer = require("puppeteer");

(async function () {
  const u = "https://www.google.com/search?q=foo"
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--lang="en-US"']
  });
  page = await browser.newPage();
  await page.setExtraHTTPHeaders({
     'Accept-Language': 'en'
   });
  await page.goto(u);
})();
```

**Comment by kahunacohen** [comment]
Hi, any ideas?

**Comment by davidjgoss** [comment]
Per this comment https://bugs.chromium.org/p/chromium/issues/detail?id=755338#c14 seems this isn't really supposed to work and we should be using the `LANG` environment variable instead.

h/t @dom54

**Comment by UInIQ** [comment]
@davidjgoss Speaking as someone who just spent FAR longer than he'd like to have beating his head against this particular wall, I wanted to, with all the grateful sincerity I can muster, compliment you on your anal-retentive attention to detail, both in finding that little nugget, and then _remembering to come back here and post the update some three months after the initial question was posted and some two months after the most recent activity._

Wow, man. I can barely remember what I had for lunch on Sunday. My (evident) mnemonic shortcomings aside, though, honestly: thanks for taking the time. You just saved me a much larger headache than I'd already built up. You're appreciated. <3

**Comment by b11p** [comment]
I think this is due to a change of Chromium. The "lang" arg did work in 2019 and earlier, but it does not work now. The "Accept-Language" header works fine for me.

**Comment by weltonrodrigo** [comment]
Just to help people coming from google, the following works in macos ventura: https://osxdaily.com/2021/06/02/how-change-language-specific-apps-mac/

**Comment by GiveDaData** [comment]
"--lang=en-US" worked for me while '--lang="en-US"' does not. try removing the ""
