### ISSUE TITLE
headless:true with custom user profile = logged out

### ISSUE THREAD

**Issue by peixotorms** [puppeteer/puppeteer#5972]
Same situation as #921

Puppeteer 3.1.0 with Chrome beta v84.

```
const browser = await puppeteer.launch({
	headless: true,
	executablePath: 'C:\\Program Files (x86)\\Google\\Chrome Beta\\Application\\chrome.exe', // other browser
        args: [
	    '--user-data-dir=C:\\Users\\xxxxxx\\AppData\\Local\\Google\\Chrome Beta\\User Data',
            '--profile-directory=Default',
        ]
	});
```

Changing back to headless: false and I can login.
Using true, I am now logged out.
How to use headless true and reuse the profile and current cookies?

**Comment by sydney-d** [comment]
Up, 
Many people seem to be facing the same issue:
https://github.com/puppeteer/puppeteer/issues/921

At the moment it's not possible to reuse `user-data-dir` content for both headless and headfull

**Comment by sydney-d** [comment]
Hello,

Bug is still present with latest release (puppeteer@5.2.1).

**Comment by rainb3rry** [comment]
Hi @peixotorms have you find any solution so far?
