### ISSUE TITLE
Correct way to Load Temporary Add-on on launch firefox

### ISSUE THREAD

**Issue by obfuscatus** [puppeteer/puppeteer#5976]
Hello,
Is there anyone successfully load Temporary Add-on on launch firefox like argument **--load-extension=${extensions}** when launch chrome?
I found web-ext but I can not find how to use web-ext with puppeteer?

**Comment by adam-s** [comment]
Yes, this is an important question. Since Puppeteer is missing a lot of functionality in Firefox using extensions is a good way to overcome that. Simply create an extension with a set of tools. However, using unsigned extensions is futile.

**Comment by summergan** [comment]
so, how to load extensions when launch firefox

**Comment by fregante** [comment]
This seems to be how: https://github.com/puppeteer/puppeteer/issues/5532#issuecomment-706239839
