### ISSUE TITLE
how to judge the navigated page is loaded  

### ISSUE THREAD

**Issue by rawbin-** [puppeteer/puppeteer#598]
as the issue on ChromeDevTools

https://github.com/ChromeDevTools/devtools-protocol/issues/33

I rewrite the code 
```js
const puppeteer = require('puppeteer');

puppeteer.launch({
    headless:false
}).then(async browser => {
    const page = await browser.newPage();

    await page.goto('https://www.baidu.com');

    await page.evaluate(() => {
        const inputElement = document.getElementById('kw');
        inputElement.value = 'Web自动化 headless chrome';

        const submitElement = document.getElementById('su');
        submitElement.click();
    });
});
```
how to judge the search result page is loaded,is there a pagenavigated or load event would triggered?

**Comment by ebidel** [comment]
Telling when any page is "loaded" is subjective. It's hard to have a single event or signal. 

By default, `Page.goto()` waits for the page `load` event. But you can also use [`waitUntil: 'networkidle'`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options) and introduce a delay if that's not sufficient.

**Comment by rawbin-** [comment]
In browser when we refresh the page or click any link to open page on current tab, there is always an load event for every url，but in headless mode，when a page navigated to A page，and click link to any other page ，the `load` event only triggered for the first navitation,  it looks odd.

**Comment by aslushnikov** [comment]
@rawbin- the `load` is triggered on every navigation for me.

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('load', () => console.log("Loaded: " + page.url()));
  await page.goto('https://google.com');
  await page.goto('https://yahoo.com');
  await page.goto('https://bing.com');
  browser.close();
})();

```

**Comment by rawbin-** [comment]
when we use page.goto the `load` triggered is expected, when you change the location with js code  as above, it's triggered only the first page.goto call

**Comment by aslushnikov** [comment]
@rawbin- that's because the baidu is a single-page application that handles search request all client-side.

**Comment by rawbin-** [comment]
@aslushnikov  that's is the point, thank you very much.
the load event triggered twice as expected with the following code
```
const puppeteer = require('puppeteer');

puppeteer.launch({
    headless:false
}).then(async browser => {
    const page = await browser.newPage();


    page.on('load',() => {
        console.log('load event fired');
    });

    await page.goto('https://dujia.qunar.com').catch(() => {

    });

    await page.evaluate(() => {
        const inputElement = document.getElementById('arriveSearchText');
        inputElement.value = '三亚';

        const submitElement = document.querySelector('[item="commit"]');
        submitElement.click();
    });
    
    await page.waitFor('.dj-list-content').then(() => {
        page.evaluate(() => {
            let resultList = [];
            const linkBlocks = document.querySelectorAll('.unit.calendar-list-con');
            for (let block of Array.from(linkBlocks)) {
                let targetObj = block.querySelector('.has_title_dom');
                resultList.push({
                    title: targetObj.textContent,
                    link: targetObj.getAttribute('href')
                });
            }
            return resultList;
        }).then((searchResult) => {
            // console.log(searchResult)
            // browser.close();
        });
    })
});
```

**Comment by rageshpayyan** [comment]
@ebidel ,My application built in Angular, what is the page event when i click any of the link or change route? I tried using await page.on('framenavigated', frame => {...}); which is fired only at first time, after i clicked any of the links in page this event is not fired.

**Comment by Ge11ert** [comment]
@ebidel try to use `browser.on('targetchanged', ...)`. For me it works in React app as expected. Framenavigated works only for the first time too.

**Comment by aslushnikov** [comment]
@rageshpayyan see #257

**Comment by rageshpayyan** [comment]
@Ge11ert , Awesome, browser.on('targetchanged', ...) event working fine,  When i click any of the link in my Angualr App  this event fired. Thanks again.

**Comment by KeithStudley** [comment]
Hi,
@aslushnikov 
I am having difficulties waiting for an iframe to completely load.
We are thinking of moving our automation from Selenium to Puppeteer.
Thanks in advance for the advice.

**Comment by Un1xMida** [comment]
am having issue too 
i have this issue when i use the 
page.waitForNavigation({waitUntil: 'networkidle0'});
browser.close()
(node:504) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!

**Comment by lokiOdUa** [comment]
> am having issue too
> i have this issue when i use the
> page.waitForNavigation({waitUntil: 'networkidle0'});
> browser.close()
> (node:504) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!

you forgot to 'await' before 'page.waitForNavigation()'

**Comment by codeyourwayup** [comment]
try to use browser.on('targetchanged', ...). For me it works in React app as expected. Framenavigated works only for the first time too
