### ISSUE TITLE
page.waitForFunction not ending

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#5980]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.17.0
* Platform / OS version: Windows 7 Entreprise Version 6.1
* URLs (if applicable): 
* Node.js version: 12.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
let is_disabled;

const PB_dropdown = '#Selector[disabled]';
id_disabled = await page.$('Selector[disabled]') == null;
console.log(`Dropdown PB state is ${is_disabled}\r`); // -> Dropdown PB state is undefined


await page.waitForFunction(dropdown => document.querySelector(dropdown) == 'null', {}, PB_dropdown); // not working as expected

//await page.waitFor(4000); // works to replace waitForFunction but not a suitable solution


is_disabled = await page.$('Selector[disabled]') == null;
console.log(`Dropdown PB state is ${is_disabled}\r`); -> Dropdown PB state is true
```

**What is the expected result?**
I expect `page.waitForFunction` to execute the `document.querySelector(dropdown) == 'null'` until the test returns true.

**What happens instead?**
The code is stuck at the `page.waitForFunction` line, no Unhandled promise is returned. After a certain amount of time the selector status [disabled] disappear but my code stay at the `await page.waitForFunction` line.

**Found workaround**
Using `await page.waitFor(time in ms)`, after 2 seconds `await page.$('Selector[disabled]') == null;` returns true. Here the problem is that the operation depends on the server and if the server is busy I will get an error when after n milliseconds the next action is executed while the page doesn't permit it.

**Comment by vsemozhetbyt** [comment]
To be on the safe side. Are there 2 typos here:
```js
id_disabled = await page.$('Selector[disabled]') == null;
```
Maybe it should be:
```js
is_disabled = await page.$('#Selector[disabled]') == null;
```
The same for the second:
```js
is_disabled = await page.$('Selector[disabled]') == null;
```

**Comment by ghost** [comment]
@vsemozhetbyt thanks for answering !
The line that is causing me problems is : `await page.waitForFunction(dropdown => document.querySelector(dropdown) == 'null', {}, PB_dropdown);`. My code doesn't go past that line, puppeteer is looking for a selector indefinitly (because i discarded page timeout).

Concerning typos, both are working for the `is_disabled = await page.$()`

Maybe i should just try using while{} with `is_enabled = await page.$('Selector[disabled]') == null;` and wait for is_enabled to return true ?

I thought `page.waitForFunction` was suited for this context, but I may be using it the wrong way.

**Comment by vsemozhetbyt** [comment]
Maybe it is worth to provide a minimal complete code that reproduces the issue, with the real URL and selectors.

**Comment by ghost** [comment]
The website is situated on my company intranet. Real selectors are called by their id and are subject to status 'disabled' when the user isn't alllowed to click them.

I opened the issue to check if the problem I am encountering is caused by a bug or not.
As it seems that I won't get an answer on this point I will close and find a workaround. 
Thanks.
