### ISSUE TITLE
When will the webkit / Safari browser support roll out planned ?

### ISSUE THREAD

**Issue by grajesh690** [puppeteer/puppeteer#5984]
I could able to leverage my test automation in chrome easily and quicker. It would be great if webkit support is planned for puppeteer as playwright able to roll out the webkit support. Even though puppeteer is at more matured state.

**Comment by mathiasbynens** [comment]
https://github.com/puppeteer/puppeteer#q-what-is-the-status-of-cross-browser-support

Safari support is blocked on https://github.com/w3c/webdriver-bidi. We're working on it!

**Comment by anilsky** [comment]
any idea when would the puppeteer webkit support is released ?

**Comment by chang-ke** [comment]
> https://github.com/puppeteer/puppeteer#q-what-is-the-status-of-cross-browser-support
> 
> Safari support is blocked on https://github.com/w3c/webdriver-bidi. We're working on it!

is there any new update?

**Comment by OrKoN** [comment]
No new updates, but https://github.com/w3c/webdriver-bidi is in progress. The BiDi support will be announced in the release notes and documentation when it happens.

**Comment by NazCodeland** [comment]
Hey there @OrKoN, now that WebDriver BiDi protocol is supported starting with Puppeteer v21.6.0, are there any updates or discussions on when Safari might be supported?

Thank you

**Comment by OrKoN** [comment]
Here is a WebKit standards position on WebDriver BiDi https://github.com/WebKit/standards-positions/issues/240 and here is the latest implementation status across browsers https://wpt.fyi/results/webdriver/tests/bidi?label=experimental&label=master&aligned As soon as a sufficient number of features is supported in Safari, it should be possible to use it with Puppeteer. As for the specific timelines I do not have any information.
