### ISSUE TITLE
Unable to get all iframes in the page

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#5986]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.3.0
* Platform / OS version: 10.15.5
* URLs (if applicable): https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* Node.js version: 12.16.1

**What steps will reproduce the problem?**
```
const puppeteer = require("puppeteer");
const url = `https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe`;

(async () => {
	const browser = await puppeteer.launch({
		headless: false,
		defaultViewport: null,
	});
	const page = await browser.newPage();
	await page.goto(url);
	await new Promise((resolve) => setTimeout(resolve, 5000));
	const frames = await page.frames();
	console.log("frames", frames.length);
})();

```

1. Run the code
2. Logs

**What is the expected result?**
- 3 total frames. Page has two iframes in the page that you can see by using page's devtools and running `document.getElementsByTagName('iframe')`
<img width="529" alt="Screen Shot 2020-06-08 at 2 29 56 PM" src="https://user-images.githubusercontent.com/1330677/84082343-8df32e80-a994-11ea-9649-b8fd897c414b.png">

**What happens instead?**
- We get just one frame which is the top frame/page.

**Comment by VikramTiwari** [comment]
@mathiasbynens Any quick ideas about what I might be doing wrong here?

**Comment by terion-name** [comment]
iframe is not a frame. use `page.$$('iframe')`

**Comment by VikramTiwari** [comment]
Thanks @terion-name. I think I interpreted following from API docs page properly but might be mistaken.

> Page has at least one frame: main frame. There might be other frames created by iframe or frame tags.

What makes something a frame? My assumption was that any time there's an iFrame in the page, there should be a frame in the puppeteer. The use case here is to click inside those frames.

If those iframes are not pptr frames, then how would you perform a click in such iframes?

**Comment by vsemozhetbyt** [comment]
Strange difference between headless and headful sessions:
```js
const puppeteer = require('puppeteer');

(async function main1() {
  try {
    let browser = await puppeteer.launch({ defaultViewport: null });
    let [page] = await browser.pages();

    await page.goto('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe');

    console.log(await page.evaluate(() => document.querySelectorAll('iframe').length));
    console.log((await page.frames()).length);

    await browser.close();

    browser = await puppeteer.launch({ headless: false, defaultViewport: null });
    [page] = await browser.pages();

    await page.goto('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe');

    console.log(await page.evaluate(() => document.querySelectorAll('iframe').length));
    console.log((await page.frames()).length);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
2
5
2
1
```

**Comment by VikramTiwari** [comment]
@vsemozhetbyt Strange indeed. I was expecting at-least evaluate based methods to work consistently.

**Comment by summergan** [comment]
I have the same issue. 
(await frame.childFrames()).length // 0  when headless is false
(await frame.childFrames()).length // 1  when headless is true
Is there any solution to this issue？

**Comment by lionel126** [comment]
have a look thru #5123  there's a resolution . 
I tried and it works

**Comment by tokland** [comment]
This worked for me: https://github.com/puppeteer/puppeteer/issues/5123#issuecomment-559158303
