### ISSUE TITLE
Puppeteer is showing error after few successful requests 

### ISSUE THREAD

**Issue by KaruppananA** [puppeteer/puppeteer#5987]
**Tell us about your environment:**

* Puppeteer version: 1.19
* Platform / OS version:Linux / Azure APP Service 
* URLs (if applicable):
* Node.js version:v10.17.0

**What steps will reproduce the problem?**

I installed all dependencies need for run headless chromium running in app service. Initially i didn't face any issues while creating the screen shot of  browser after make to many requests suddenly server throughs the error "Failed to launch chrome!\n/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md". After i reinstall all dependancies its work fine. Could you please tell me the root cause of this issue and provide permanent solution for this issues. 

Dependencies I installed : 
apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

**What is the expected result?**
Expected output is screen shot capturing 

**What happens instead?**
Its through the error msg as "Failed to launch chrome!\n/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md".

**Comment by as20203** [comment]
Same issue occured for me as well. I installed adpendency libgtk-3-0  and it started working again. Kindly guide regarding this issue as to why it occured all of a sudden.

**Comment by KaruppananA** [comment]
The issue is happend because allocating new container every app getting auto scale or down. So it remove dependencies everytime. So implement the docker based solution and deploy the same in Azure app service. Now i am not facing the any isssues in Puppeteer.
