### ISSUE TITLE
Partial screenshots when taking screenshot from SPA gatsby site

### ISSUE THREAD

**Issue by plexcellmedia** [puppeteer/puppeteer#5989]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.3.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: v12.15.0

I'm trying to take screenshot of SPA site made with gatsby and I'm running into some problems with puppeteer.

Full code and example 1

```
const puppeteer = require("puppeteer");

const PUPPETEER_OPTIONS = {
  headless: true,
  args: [
    "--no-sandbox",
    "--lang=en-US,en",
    "-window-size=1920,1080",
    "--disable-gpu",
  ],
};

const closeConnection = async (page, browser) => {
  page && (await page.close());
  browser && (await browser.close());
};

const openConnection = async () => {
  const browser = await puppeteer.launch(PUPPETEER_OPTIONS);
  const page = await browser.newPage();

  await page.setExtraHTTPHeaders({
    "accept-language": "en-US,en;q=0.8",
  });

  await page.emulate({
    name: "Desktop 1280x800",
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36",
    viewport: {
      width: 1280,
      height: 800,
    },
  });

  return { browser, page };
};

exports.run = async (req, res) => {
  let url = "https://example.com";

  let { browser, page } = await openConnection();

  try {
    await page.goto(url, {
      waitUntil: "networkidle2",
    });

    await page.screenshot({
      fullPage: true,
      path: 'puppeteer/screenshot.png'
    });

  } catch (error) {
    console.log(error);
  } finally {
    await closeConnection(page, browser);
  }
};

require("make-runnable");

```
On example 1 I'm having problem with footer part of site, it gets displayed as white without any content. Only the screen viewport on top of screenshot is rendered.

Example 2

```
const frame = await page.mainFrame();
const element = await frame.$("body");

await element.screenshot({
  path: 'puppeteer/screenshot.png'
});

```
On example 2 viewport size of website gets stretched to whole body size, so top of website is rendered into fullheight screenshot.

Example 3
```

const frame = await page.mainFrame();
const element = await frame.$("body");
const box = await element.boundingBox();
const settings = {
  clip: {
    width: box.width,
    height: box.height,
    x: 0,
    y: 0
  },
  path: "puppeteer/screenshot.png",
};

await element.screenshot(bounds);
```

Example #3 same result as #1.

I have also tried to scroll bottom of site, then footer renders but top of site is white.

**What is the expected result?**

Fullpage screenshot

**What happens instead?**

Partial screenshot with half of page missing

**Comment by owenduncansnobel** [comment]
I am having the same problem. It will show full size of viewport but only content of what is at the very top of the page is displayed on screenshot.

**Comment by owenduncansnobel** [comment]
After a little digging, I found out if you are using the default browser 'chromium' / 'chrome' with the option: 'fullPage'. if the the page you are going to screenshots elements is using/has the CSS property 'min-height-screen' or 'height-screen' the elements are growing and will not be included in the viewport. A solution was to use puppeteer mozilla or potentially another browser as it does not grow will fullPage and vh/vw.

**Comment by Sunchunqing** [comment]
I am having the same problem
