### ISSUE TITLE
Error: Failed to launch the browser process! spawn /app/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome ENOENT

### ISSUE THREAD

**Issue by FlorentCmb** [puppeteer/puppeteer#5992]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^3.3.0
* Platform / OS version: Ubuntu 20.04 LTS
* URLs (if applicable):
* Node.js version: 12.16.1

**What steps will reproduce the problem?**

I know there's a lot of issues like this one, but I tried every solutions I saw, such as add `args` to the `.launch`, reinstall all required dependencies, reinstall puppeteer, reinstall Chromium, try Chrome... But I still get this error.

1. In backend :
`const puppeteer = require('puppeteer');
const router = require('express').Router();

router.get('/create', async (req, res) => {
    console.log("BEGINING PDF CREATION PROCESS");
    try {
        // Starting browser and got to a new page
        const browser = await puppeteer.launch({ headless: true });
        const page = await browser.newPage();
        await page.goto('https://google.com');
        // Define the media type
        await page.emulateMediaType('screen');
        // Create PDF with custom options
        const buffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            preferCSSPageSize: true
        });
        // Send PDF to front
        res.writeHead(200, {
            'Content-Type': 'application/pdf',
            'Content-Length': buffer.length
        });
        res.end(buffer);
        // Close browser
        await browser.close()
        console.log("ENDING PROCESS SUCCESSFULY");
    }
    catch (error) {
        console.log("ENDING PROCESS UNSUCCESSFULY");
        console.log(error);
    }
});

module.exports = router`
2. frontend :
`axios({
      method: 'get',
      url:'/pdf/create'
    })
    .then(res => {
      console.log("Response received")
      return res
        .arrayBuffer()
        .then(res => {
          const blob = new Blob([res], { type: 'application/pdf' })
          saveAs(blob, `${order._id}.pdf`)
        })
        .catch(error => console.log(error))
    })`
3.

**What is the expected result?**
It should send the PDF buffer to the front.

**What happens instead?**
I returns the error above.

**Comment by ibnujakaria** [comment]
I also got this problem after installing puppeteer `^3.3.0`

It seems the `node_modules/puppeteer/.local-chromium/chrome-linux.zip` file was not extracted properly.

After I extracted it manually the puppeteer worked as expected.

**Comment by xiaoqiao112** [comment]
> 安装人偶后我也遇到了这个问题 `^3.3.0`
How do you specifically solve this problem?

**Comment by mweitzel** [comment]
I'm experiencing this on osx as well. Yarn install creates an invalid application at
```
./node_modules/puppeteer/.local-chromium/mac-756035/chrome-mac/Chromium.app/
# directory sits around ~191.2MB, most files are missing
```

However, if manually extract
```
./node_modules/puppeteer/.local-chromium/chromium-mac.zip
```
and replace the resulting `chrome-mac/Chromium.app` (~279MB) with the corrupted one, puppeteer continues working.

I was able to reproduced this with the `example hello world` in an empty repository with `puppeteer` as the only dependency.

**Comment by mweitzel** [comment]
@qiaochunmei 这解决了问题. 祝好运.
```
unzip node_modules/puppeteer/.local-chromium/chrome-mac.zip
cp -r chrome-mac/Chromium.app/ ./node_modules/puppeteer/.local-chromium/mac-756035/chrome-mac/Chromium.app/
```

**Comment by marijnh** [comment]
I think I'm seeing the same issue (Debian Linux, puppeteer 4.0.0). After installing (no error shown to the console), the `.local-chromium` dir contains only `chrome-linux.zip` and `linux-756035/chrome-linux/chrome_100_percent.pak` files, suggesting that unzipping somehow failed.

**Comment by srsholmes** [comment]
> @qiaochunmei 这解决了问题. 祝好运.
> 
> ```
> unzip node_modules/puppeteer/.local-chromium/chrome-mac.zip
> cp -r chrome-mac/Chromium.app/ ./node_modules/puppeteer/.local-chromium/mac-756035/chrome-mac/Chromium.app/
> ```

This worked for me as a temporary work around.

**Comment by sgilligan** [comment]
same problem for me on macos, solved per the steps @mweitzel outlines.

**Comment by HarlesPilter** [comment]
Maybe this helps https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-is-downloaded-but-fails-to-launch-on-nodejs-14 Seems to be the same issue, even if its another version of node

**Comment by 0xtinkle** [comment]
I used to have problem for CI/CD of headful chrome extension testing and finally resolved with this package
https://github.com/mujo-code/puppeteer-headful
It also has docker file of headful setup process and this link would be helpful.

**Comment by johns10** [comment]
The error I was getting was: `spawn D:\Users\johns10\Documents\GitHub\userdocs_umbrella\apps\userdocs_web\assets\dist\win-unpacked\resources\app.asar\node_modules\puppeteer\.local-chromium\win64-856583\chrome-win\chrome.exe ENOENT`

I solved it like this:

```
async function openBrowser() {
  if (isDev) {
    var executablePath = puppeteer.executablePath()
  } else {
    var executablePath = puppeteer.executablePath().replace("app.asar", "app.asar.unpacked")
  }
  const browser = await puppeteer.launch({ executablePath: executablePath });

  return browser
}
```
