### ISSUE TITLE
Unable to pass `ReadableStream` object to `page.exposeFunction(name, puppeteerFunction)`

### ISSUE THREAD

**Issue by aksharj** [puppeteer/puppeteer#5998]
Hi All,

I am unable to pass `ReadableStream` object to `page.exposeFunction(name, puppeteerFunction)`

Below is my relevant code.

Since, the stream does not get passed, i get `Unsupported body payload object` error.

```
    await newPage.exposeFunction('uploads3', (stream) => {
      console.log(stream); // prints {}
      AWS.config.credentials.get(function(err) {
        let csvS3 = new AWS.S3;
        if (err) {
          console.log(err);
        } else {
          let uploadParams = {
            Bucket: 'staging',
            Key: "one.csv",
            Body: stream,
          };
          let s3Upload = csvS3.upload(uploadParams).promise();
          s3Upload.then(function(s3data){
            console.log(s3data);
          },function(err) {
            console.log(err);
          });
        }
      });
    });



    await newPage.waitForSelector("#data-0");
    await newPage.waitForSelector('.summary');
    const fetchData = await newPage.evaluate(async () => {
      let url = $('.summary').attr('href');
      const stream = await fetch(url);
      const myHash = await window.uploads3(stream.body);
    });
```

Any help to fix this would be really great.

**Comment by vsemozhetbyt** [comment]
Maybe as with the `page.evaluate()`, transferred arguments and returned values should be serializable. If so, the doc needs to be clarified.

**Comment by aksharj** [comment]
hi @vsemozhetbyt, thanks for your reply. is there any workaround where i can pass  readable stream to the exposeFunction?

**Comment by vsemozhetbyt** [comment]
Sorry, I do not know any(

**Comment by jackfranklin** [comment]
I'm afraid you can't do this for the reason @vsemozhetbyt mentions; the arguments have to be serialized. We welcome any documentation PRs if you would like to clear it up 👍

**Comment by pke** [comment]
@jackfranklin the docs and tests don't serialise complex objects though.

https://github.com/puppeteer/puppeteer/blob/a7fcde918190d8b2da358eec1690bc217a8626f8/test/src/page.spec.ts#L1210

I am getting a runtime error, when calling the exposed function with an object that says:
"Invalid arguments: should be exactly one string"
