### ISSUE TITLE
Puppeteer 3.3.0 and Firefox Nightly 79: response.text() never completes

### ISSUE THREAD

**Issue by fabiomgoncalves** [puppeteer/puppeteer#5999]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.3.0
* Platform / OS version: Windows 10
* Node.js version: 14.4.0

**What steps will reproduce the problem?**
Navigate to a page and try to extract the response text.

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({
                product: 'firefox',
                headless: false,
                devtools: false,
                ignoreHTTPSErrors: true,
                args: ['-wait-for-browser'],
                dumpio: true,
                extraPrefs: {
                    'remote.log.level': 'Trace',
                },
            });

const page = await browser.newPage();
const response = await page.goto('https://www.google.com/');
const text = await response .text();
```

**What is the expected result?**
Get the response text.

**What happens instead?**
response.text never completes, hanging the browser.

**Comment by rezemble** [comment]
Connection never receives (hence never fires) the Network.loadingFinished (or, for that matter, requestFinished) event, so the NetworkManager never resolves the Response content

**Comment by rezemble** [comment]
I traced it back to the Firefox code;
the NetworkObserver fires the events, is passed to the Network Domain through a Session, but the Network Domain only listens to the "request" and "response" events, hence only forwards those

**Comment by rezemble** [comment]
In Addition, the Network Domain doesn't seem to be set up to handle the `Network.getResponseBody` event

**Comment by jackfranklin** [comment]
CC @mjzffr @whimboo in case this is useful to dig into.

**Comment by mjzffr** [comment]
Thanks for the report. Some of the relevant work in Mozilla's protocol implementation is tracked at:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1590201
* https://bugzilla.mozilla.org/show_bug.cgi?id=1549510

The Network domain is high on our priority list.

**Comment by Rydgel** [comment]
It seems to hang as well when using functions like
`await page.goto(this.url, {waitUntil: 'networkidle2'})`

**Comment by whimboo** [comment]
Yes, we do not support `networkidle2` nor `networkidle0` yet.

**Comment by whimboo** [comment]
Closing issue for now given that the underlying network events as necessary to fulfill the request on this isse will most likely not be implemented in our partial CDP protocol in Firefox.
