### ISSUE TITLE
PuppeteerScript

### ISSUE THREAD

**Issue by benschwarz** [puppeteer/puppeteer#60]
I've been long thinking about scripting interactions using something similar to the [webpagetest test scripts](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting). 

It'd be great to have some interoperability with that preexisting script syntax/format/language. While I'm not a huge fan of the API, it has been established for some people already. 

I'm certain that Patrick would have some feels regarding this idea too. 

---

eg

```
visit https://google.com
focus #searchInput
type 'where is the world‘s best cheesecake?'
press button[type='submit']
screenshot my-image.jpg
```

Is this in scope for puppeteer? Or perhaps something that could just use puppeteer under the covers?

**Comment by aslushnikov** [comment]
Hi Ben!

>Is this in scope for puppeteer? Or perhaps something that could just use puppeteer under the covers?

There are no plans to support webpagetest scripts as a part of this project. But this seems to be certainly doable with puppeteer under the hood!
