### ISSUE TITLE
Support for dynamic selectors?

### ISSUE THREAD

**Issue by tomredman** [puppeteer/puppeteer#600]
I'm sorry if I've overlooked something here. Does Puppeteer have support for dynamic selectors? 

E.g., Ember framework provides each element with a unique id in the format `ember2599`. Is there a way to select the _nth_ `ember*` element? Another example are "salted" username and password selectors, e.g., `id='username-08b6c2e1'` where the random string changes on each reload. 

Thanks!

**Comment by aslushnikov** [comment]
Sounds like #382 will address this.

**Comment by tomredman** [comment]
Thanks @aslushnikov, I'll sit tight and wait for this. Puppeteer is awesome by the way!
