### ISSUE TITLE
CPU usage for downloading HTML content is very high.

### ISSUE THREAD

**Issue by Rajat-Sharma-2710** [puppeteer/puppeteer#6008]
CPU usage for downloading HTML content is very high
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-core@3.3.0
* Platform / OS version:Windows 10
* Node.js version:10.16.3

**What steps will reproduce the problem?**
I am trying to create a webcrawler that will download the HTML content of the provided URL.
While capturing the CPU usage with clinic js I am getting an average CPU usage of more than 100%.
Is there a way to optimize the CPU usage. I have tried all the solutions available on stackoverflow and other forums.

```
const puppeteer = require('puppeteer-core')
const list = ['array of URLs']

(async () => {

   try {
    const browser = await puppeteer.launch({

        executablePath: './chrome-win/chrome-win/chrome',
    
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    
      }); 

    const page = await browser.newPage()
// I have used simple 'for of' loop for assigning uri and getting response 
    const uri = 'http://www.example.com/'

    await page.goto(uri, { waitUntil: 'networkidle2' })

    const response = await page.content()

    await browser.close()

    console.log('----------', response)

  } catch (error) {

    console.log('our error***', error)

  }

})()

```

I am getting the expected results but at a very high CPU usage.
Can someone help me with minimizing CPU usage.

**Comment by wh81752** [comment]
@Rajat-Sharma-2710 - same for me on my Mac. Did you eventually figure out what the problem has been?
