### ISSUE TITLE
Error when calling an exposedFunction from within page.evaluateOnNewDocument

### ISSUE THREAD

**Issue by jonapgar** [puppeteer/puppeteer#6012]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.3.0
* Platform / OS version: Mac OS
* Node.js version: 14.0.0

**What steps will reproduce the problem?**

Calling an exposed function immediately inside evaluateOnNewDocument causes a JSON parsing error.

_Please include code that reproduces the issue._

```javascript
page.exposeFunction('foo',function(bar){ console.log(bar) })
page.evaluateOnNewDocument(function(){ window.foo('bar') })
```

**What is the expected result?**
"bar" is emitted from stdout

**What happens instead?**
An error is thrown when `Page._onBindingCalled` attempts to parse the value passed to the exposed function.
```
SyntaxError: Unexpected token b in JSON at position 1
    at JSON.parse (<anonymous>)
    at Page._onBindingCalled (/****/node_modules/puppeteer/lib/Page.js:405:42)
    at CDPSession.<anonymous> (/****/node_modules/puppeteer/lib/Page.js:126:60)
```

Note that awaiting page.exposeFunction seems to prevent this error, but I'm not sure if this is guaranteed. 
```javascript
await page.exposeFunction('foo',function(bar){ console.log(bar) })
page.evaluateOnNewDocument(function(){ window.foo('bar') })
```
Also note that deferring the call to the exposed function does not trigger the error.
```javascript
page.exposeFunction('foo',function(bar){ console.log(bar) })
page.evaluateOnNewDocument(function(){ 
  setTimeout(window.foo('bar'),0)
})
```

**Comment by lizryzhko** [comment]
Hi! Try to add a line with`/* istanbul ignore next */` before `page.evaluateOnNewDocument`

**Comment by jonapgar** [comment]
> Hi! Try to add a line with`/* istanbul ignore next */` before `page.evaluateOnNewDocument`

I don't see how this is related to this particular issue.

**Comment by joshxyzhimself** [comment]
Also getting this at `^3.3.0`

**Comment by joshxyzhimself** [comment]
Also at `4.0.0`

**Comment by joshxyzhimself** [comment]
Can confirm at `4.0.0` that awaiting it resolves it, but it's weird when doing one-time page.exposeFunction + page.evaluate
