### ISSUE TITLE
Unable to access input fields for nike login

### ISSUE THREAD

**Issue by Justin-Geisen** [puppeteer/puppeteer#6013]
Steps to reproduce

* Puppeteer version: Latest?
* Platform / OS version: Ubuntu 20.04 LTS
* URLs (if applicable): https://www.nike.com/login
* Node.js version: 6.14.4

I am trying to create code to automatically login in to the Nike website. However, I cannot access the inputs at the login page. 

Note:
This is my first time posting an issue in GitHub. If my post has anything that seems incorrect or I did not post enough information, please let me know and I will correct myself. 

Code:
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  
  await page.setViewport({
  width: 2000,
  height: 640,
  deviceScaleFactor: 1,
});
  
  await page.goto('https://www.nike.com/login');
  await page.type('[id="1ebe6ff6-e8f4-47c1-8971-7100d9a12081"]', 'myEmail@outlook.com', {delay: 110});

})();

Steps to reproduce

1. run code

Expected Result:
It should input text into the email address bar.

What happens instead?
There is no text in the email address bar.

**Comment by vsemozhetbyt** [comment]
It seems the id is generated randomly. Try another selector, for example:
```js
await page.type('[name="emailAddress"]', 'myEmail@outlook.com', { delay: 110 });
```

**Comment by Justin-Geisen** [comment]
Thank you so much!
