### ISSUE TITLE
Structure the API documentation by category

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#602]
I think it'd be valuable to restructure the API documentation to be categorized rather than alphabetical. 

For example, three cookie-related methods would be next to eachother. This would assist greatly to anyone learning the API surface for the first time. (And right now that's (obviously) most of our users :)

Another motivation: I'd like to have the room in the documentation to provide some guidance for certain areas. For example, providing an explanation and guidance to adopt elementHandles/evaluate rather than loading jsdom/cheerio. 

To start things off, below is a proposed TOC.
wdyt? 

<details style="font-size: 90%" border=10>
<summary>
<tt><b>Expand to see strawman proposal for new TOC structure</b></tt>

</summary>

<hr><hr><hr>
<blockquote>

#### Managing browsers and tabs

- [Puppeteer](#puppeteer)
  * [class: Puppeteer](#class-puppeteer)
    + [puppeteer.connect(options)](#puppeteerconnectoptions)
    + [puppeteer.launch([options])](#puppeteerlaunchoptions)
  * [class: Browser](#class-browser)
    + [browser.close()](#browserclose)
    + [browser.newPage()](#browsernewpage)
    + [browser.version()](#browserversion)
    + [browser.wsEndpoint()](#browserwsendpoint)
  * [class: Page](#class-page)
    + [page.close()](#pageclose)

#### Working with pages
  * [class: Page](#class-page)
    + [event: 'console'](#event-console)
    + [event: 'pageerror'](#event-pageerror)
    + [page.content()](#pagecontent)
    + [page.injectFile(filePath)](#pageinjectfilefilepath)
    + [page.pdf(options)](#pagepdfoptions)
    + [page.plainText()](#pageplaintext)
    + [page.screenshot([options])](#pagescreenshotoptions)
    + [page.setContent(html)](#pagesetcontenthtml)
    + [page.title()](#pagetitle)
    + [page.url()](#pageurl)

#### Navigation & waiting
  * [class: Page](#class-page)
    + [event: 'load'](#event-load)
    + [page.goBack(options)](#pagegobackoptions)
    + [page.goForward(options)](#pagegoforwardoptions)
    + [page.goto(url, options)](#pagegotourl-options)
    + [page.reload(options)](#pagereloadoptions)
    + [page.waitFor(selectorOrFunctionOrTimeout[, options])](#pagewaitforselectororfunctionortimeout-options)
    + [page.waitForFunction(pageFunction[, options, ...args])](#pagewaitforfunctionpagefunction-options-args)
    + [page.waitForNavigation(options)](#pagewaitfornavigationoptions)
    + [page.waitForSelector(selector[, options])](#pagewaitforselectorselector-options)

#### JavaScript
  * [class: Page](#class-page)
    + [event: 'error'](#event-error)
    + [page.addScriptTag(url)](#pageaddscripttagurl)
    + [page.evaluate(pageFunction, ...args)](#pageevaluatepagefunction-args)
    + [page.evaluateOnNewDocument(pageFunction, ...args)](#pageevaluateonnewdocumentpagefunction-args)
    + [page.exposeFunction(name, puppeteerFunction)](#pageexposefunctionname-puppeteerfunction)
    + [page.setJavaScriptEnabled(enabled)](#pagesetjavascriptenabledenabled)

#### DOM Elements
  * [class: Page](#class-page)
    + [page.$(selector)](#pageselector)
    + [page.$$(selector)](#pageselector)
  * [class: ElementHandle](#class-elementhandle)
    + [elementHandle.attribute(key)](#elementhandleattributekey)
    + [elementHandle.click([options])](#elementhandleclickoptions)
    + [elementHandle.dispose()](#elementhandledispose)
    + [elementHandle.evaluate(pageFunction, ...args)](#elementhandleevaluatepagefunction-args)
    + [elementHandle.hover()](#elementhandlehover)
    + [elementHandle.uploadFile(...filePaths)](#elementhandleuploadfilefilepaths)

#### Input (keyboard and mouse)
  * [class: Page](#class-page)
    + [page.click(selector[, options])](#pageclickselector-options)
    + [page.focus(selector)](#pagefocusselector)
    + [page.hover(selector)](#pagehoverselector)
    + [page.keyboard](#pagekeyboard)
    + [page.mouse](#pagemouse)
    + [page.press(key[, options])](#pagepresskey-options)
    + [page.type(text, options)](#pagetypetext-options)
  * [class: Keyboard](#class-keyboard)
    + [keyboard.down(key[, options])](#keyboarddownkey-options)
    + [keyboard.sendCharacter(char)](#keyboardsendcharacterchar)
    + [keyboard.up(key)](#keyboardupkey)
  * [class: Mouse](#class-mouse)
    + [mouse.click(x, y, [options])](#mouseclickx-y-options)
    + [mouse.down([options])](#mousedownoptions)
    + [mouse.move(x, y)](#mousemovex-y)
    + [mouse.up([options])](#mouseupoptions)

#### Network activity & interception
  * [class: Page](#class-page)
    + [event: 'request'](#event-request)
    + [event: 'requestfailed'](#event-requestfailed)
    + [event: 'requestfinished'](#event-requestfinished)
    + [event: 'response'](#event-response)
    + [page.setRequestInterceptionEnabled(value)](#pagesetrequestinterceptionenabledvalue)
    + [page.setExtraHTTPHeaders(headers)](#pagesetextrahttpheadersheaders)
  * [class: Request](#class-request)
    + [request.abort()](#requestabort)
    + [request.continue([overrides])](#requestcontinueoverrides)
    + [request.headers](#requestheaders)
    + [request.method](#requestmethod)
    + [request.postData](#requestpostdata)
    + [request.response()](#requestresponse)
    + [request.url](#requesturl)
  * [class: Response](#class-response)
    + [response.buffer()](#responsebuffer)
    + [response.headers](#responseheaders)
    + [response.json()](#responsejson)
    + [response.ok](#responseok)
    + [response.request()](#responserequest)
    + [response.status](#responsestatus)
    + [response.text()](#responsetext)
    + [response.url](#responseurl)

#### Viewport & mobile emulation
  * [class: Page](#class-page)
    + [page.emulate(options)](#pageemulateoptions)
    + [page.emulateMedia(mediaType)](#pageemulatemediamediatype)
    + [page.setUserAgent(userAgent)](#pagesetuseragentuseragent)
    + [page.setViewport(viewport)](#pagesetviewportviewport)
    + [page.viewport()](#pageviewport)

#### Working with frames
  * [class: Page](#class-page)
    + [event: 'frameattached'](#event-frameattached)
    + [event: 'framedetached'](#event-framedetached)
    + [event: 'framenavigated'](#event-framenavigated)
    + [page.frames()](#pageframes)
    + [page.mainFrame()](#pagemainframe)
  * [class: Frame](#class-frame)
    + [frame.$(selector)](#frameselector)
    + [frame.$$(selector)](#frameselector)
    + [frame.addScriptTag(url)](#frameaddscripttagurl)
    + [frame.childFrames()](#framechildframes)
    + [frame.evaluate(pageFunction, ...args)](#frameevaluatepagefunction-args)
    + [frame.injectFile(filePath)](#frameinjectfilefilepath)
    + [frame.isDetached()](#frameisdetached)
    + [frame.name()](#framename)
    + [frame.parentFrame()](#frameparentframe)
    + [frame.title()](#frametitle)
    + [frame.url()](#frameurl)
    + [frame.waitFor(selectorOrFunctionOrTimeout[, options])](#framewaitforselectororfunctionortimeout-options)
    + [frame.waitForFunction(pageFunction[, options, ...args])](#framewaitforfunctionpagefunction-options-args)
    + [frame.waitForSelector(selector[, options])](#framewaitforselectorselector-options)

#### Cookies
  * [class: Page](#class-page)
    + [page.cookies(...urls)](#pagecookiesurls)
    + [page.deleteCookie(...cookies)](#pagedeletecookiecookies)
    + [page.setCookie(...cookies)](#pagesetcookiecookies)

#### Performance
  * [class: Page](#class-page)
    + [page.tracing](#pagetracing)
  * [class: Tracing](#class-tracing)
    + [tracing.start(options)](#tracingstartoptions)
    + [tracing.stop()](#tracingstop)

#### Dialog prompts
  * [class: Page](#class-page)
    + [event: 'dialog'](#event-dialog)
  * [class: Dialog](#class-dialog)
    + [dialog.accept([promptText])](#dialogacceptprompttext)
    + [dialog.defaultValue()](#dialogdefaultvalue)
    + [dialog.dismiss()](#dialogdismiss)
    + [dialog.message()](#dialogmessage)
    + [dialog.type](#dialogtype)

</blockquote>
<hr><hr><hr>
</details>

**Comment by aslushnikov** [comment]
- Categorization looks beautiful! ❤️
- I don't like changing `api.md` to follow the new categorization - it will make doc writing harder
- It would be nice to have a website that presents the API with categorization and supports filters/search/etc. Will this work?

**Comment by ebidel** [comment]
>  have a website that presents the API with categorization and supports filters/search/etc. Will this work?

I can help with that.

**Comment by sukrosono** [comment]
>  It would be nice to have a website that presents the API with categorization and supports filters/search/etc. Will this work?

agreed number 3, hi @ebidel , on week end i have 2 hour free time maybe i can help too.
What about start new issue which focus on build the documentation to new website?
That i expect meet:
  -  tracking progress
  -  give ease to communicate internal progress with others

I like to discus or at least informed with the tools being use, because i have common interest.
>  i try building new small library, so i should learn to annotate javascript documentation

**Comment by ebidel** [comment]
@brutalcrozt awesome. We'd love the help. Please discuss tools and approach in that bug before you start in. We want to make sure everyone on the team is happy maintaining the docs :)

**Comment by sukrosono** [comment]
I have some experience on jekyll, but recently my friend told me that golang have hugo which [supported](https://gohugo.io/hosting-and-deployment/hosting-on-github/) by github webpage. 
> then i have bad experience with ruby syntax

I will make new issue  which focus on the building the site. I will list and options as proposal, since the internal team who have the right to choose.

**Comment by melbourne2991** [comment]
Sorry a little off topic but I'm just wondering what are the downsides to loading JSDOM/Cheerio if you're just looking at extract data from a page - is it that cheerio would be slower because it has to parse the markup that has already been parsed by the browser?

I'm asking because I am toying with the idea of building a scraping interface that would allow you to use the raw html source (driven with request + cheerio) for example, or alternatively what is rendered by the browser. The idea being for most use cases fetching the raw source might be enough - but in some cases you may need to extract data from SPAs etc in which case you would want to use headless chrome / puppeteer. 

Ideally the interface would be same for both "drivers". Using puppeteer to fetch and render the initial page and cheerio to actually extract the data would be easier because the interface could effectively just be cheerio itself with a light wrapper to handle the initial fetching / rendering.

**Comment by aslushnikov** [comment]
> what are the downsides to loading JSDOM/Cheerio if you're just looking at extract data from a page - is it that cheerio would be slower because it has to parse the markup that has already been parsed by the browser?

@melbourne2991 a few of them:
- cheerio/JSDOM would be slower; chrome is crazy fast at traversing DOM
- chrome has a well-tested spec-compliant DOM implementation that support every crazy scenario

So if you already have a chrome running in background, it makes sense to use it to interact with DOM.

Cheerio/JSDOM still make sense if you need something lightweight and not necessarily as bullet-proof as chrome's blink engine.

**Comment by melbourne2991** [comment]
@aslushnikov That makes sense, thanks!

**Comment by aslushnikov** [comment]
We don't have any plans to address this any time soon. Closing for now, we'll revisit this later as the necessity emerges.
