### ISSUE TITLE
Decode UTF8

### ISSUE THREAD

**Issue by sanchobouillant** [puppeteer/puppeteer#6027]
Puppeteer version V4.0.0
Node 14

Hi,

I have some URLs with UTF8 char. When I page.goTo with a UTF8, the character is encoded.

```
const testString = 'https://website.fr/urlwithspcialcharée'
        await page.goto(gotoUrl, {
            waitUntil: 'networkidle2'
        });
console.log(page.url()); -> https://website.fr/urlwithspcialchar%E9e

```
How can I handle this URL?

**Comment by mathiasbynens** [comment]
Normalize the URL by running `copy(new URL(url).toString())` in the DevTools Console, and then use the normalized version in your script. Does that help?

**Comment by sanchobouillant** [comment]
It doesn't. 

const testString = new URL("'https://website.fr/urlwithspcialcharée').toString() -> 'https://website.fr/urlwithspcialchar%C3%A9e'
        await page.goto(gotoUrl, {
            waitUntil: 'networkidle2'
        });
console.log(page.url()); -> https://website.fr/urlwithspcialchar%E9e -> chrome is still going to urlwithspcialchar%E9e instead of urlwithspcialcharée or urlwithspcialchar%C3%A9e

**Comment by zekekin** [comment]
Hey, were you able to solve this problem? I'm running into the same issue
