### ISSUE TITLE
Unable to deploy Puppeteer - Unzipped size must be smaller than 262144000 bytes. - AWS Lambda

### ISSUE THREAD

**Issue by kaushiksundar** [puppeteer/puppeteer#603]
While deploying a function to AWS Lambda I am getting this error. 

`Unzipped size must be smaller than 262144000 bytes.`

Dev Guide: [AWS Lambda Limits](http://docs.aws.amazon.com/lambda/latest/dg/limits.html#limits-list)

Is there any work-around for this?

Full deployment log

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (92.85 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred while provisioning your stack: HelloLambdaFunction - Unzipped size must be smaller than 262144000 bytes.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.2
     Serverless Version:     1.20.2

```

**Comment by ebidel** [comment]
The issue is that Chromium is being installed alongside Puppeteer and that ends up being quite large.

You can skip installing Chromium using:
`npm i --ignore-scripts puppeteer`

However, that'll require you to figure out how to download Chrome yourself and run it with Puppeteer. I've never used AWS Lambda, so maybe others have suggestions.

**Comment by homaily** [comment]
I see you have 2 options:
* Upload chrome to s3 and download it once Lambda function container is created.
* Upload chrome compressed (~92Mb) with your function code and unzip it once Lambda function container is created.

Both options will take time (~20 seconds) more or less but you don't have to do it on each request. Once you download \ unzip the file you will be able to use it in upcoming requests right away since it will be saved on the container disk.

If you're considering this I would suggest to keep your Lambda function warm.

https://read.acloud.guru/how-to-keep-your-lambda-functions-warm-9d7e1aa6e2f0
https://medium.com/@tjholowaychuk/dos-and-don-ts-of-aws-lambda-7dfcab7ad115

I'll be moving a project of mine in the next few weeks from EC2 to Lambda using puppeteer and I'll use the S3 approach. I'll upload Chrome gzipped to S3 and download it and unzip it in the download stream.

**Comment by homaily** [comment]
Another approach is Puppeteer expose a method to do the install as of npm install so you can trigger the install from your function.
@ebidel is this option fine by you and the core team?

**Comment by ebidel** [comment]
As a first step, there's an env variable coming to skip the chromium download when installing pptr.

https://github.com/GoogleChrome/puppeteer/pull/606

**Comment by icarusmiles** [comment]
Would you have to resort to using promises because AWS only supports Node v6.10 - doesn't it?

**Comment by kaushiksundar** [comment]
@homaily Thanks for you response. I am fairly new to AWS, Can you elaborate on your first option

> Upload chrome to s3 and download it once Lambda function container is created.

How do I actually do this? Is there any reference/doc, detailing these steps?

@miles-collier Yes we have to use promises.

**Comment by homaily** [comment]
@miles-collier Puppeteer now supports Node v6.4 and upwards in v0.10.0
https://github.com/GoogleChrome/puppeteer/releases/tag/v0.10.0

**Comment by homaily** [comment]
Hi @kaushik-sundar. I've wrote this sample on how to do it

https://gist.github.com/homaily/a432af95e5c3e72d3a584d435544bee0

The only external dependency you need is AWS-SDK and it's by default included in lambda functions.

**Comment by eknkc** [comment]
@homaily this will require a chrome build with shm disabled right? I believe we can not use the official builds on lambda because there is no /dev/shm provided.

**Comment by homaily** [comment]
@eknkc haven't tried it yet but I suppose (and hope) headless chrome will work on lambda. Did you have any issues doing that? Because there are other projects already doing that.

**Comment by icarusmiles** [comment]
I think the big leap here will be when Node 8 LTS comes out and when Lambda jumps to that. 

The [chromeless](https://github.com/graphcool/chromeless) project does just this for now all included in a easy to install package. Unfortunately I've found it to be shockingly slow, unsure as the reasoning behind it - however if your application doesn't require user input / response then it should work out well.

**Comment by joelgriffith** [comment]
There's also numerous other challenges that'll come up soon:

- The AWS message limit (easily hit with this protocol).
- Emoji's and other fonts not supported or working.
- General slowness that @miles-collier pointed out.

I've been building browserless.io that addresses these, and will be in beta soon. It doesn't solve your intermediate problem, but is meant to work as a solution to the issue you face (and others you'll soon face). [You can check it out here.](https://browserless.io)

**Comment by sambaiz** [comment]
I am using Puppeteer on Lambda,
but I am not using official build Chrome downloaded by Puppeteer.
That's because official build has some problems about running on Lambda (couldn't even launch for missing shared library).

So I decided to build it by myself same as [serverless-chrome](https://github.com/adieuadieu/serverless-chrome). 
As a result, it can be launched on Lambda.
And due to smaller size (compressed 47 MB), it also can be included in the package. 

Following includes built Chrome and minimum util scripts for starting Puppeteer on Lambda.
https://github.com/sambaiz/puppeteer-lambda-starter-kit

**Comment by eknkc** [comment]
@sambaiz Can you comment on the performance? Read about disabling SHM causing severe performance degredation but haven't tested myself.

**Comment by brafdlog** [comment]
Thanks @sambaiz I used your code as a base for my implementation and it works nicely.

**Comment by sambaiz** [comment]
@eknkc For now, I don't feel that it is so slow if Lambda is given enough resources.

### On local (MBP Early 2015) with Original Chrome 

- launch(): 0.827s
- newPage(): 0.434s
- goto(youtube): 2.889s
- click(): 0.137s

### On Lambda 512 MB (405 MB max used)

- (extract: 5.578s)
- launch(): 1.939s
- newPage(): 0.159s
- goto(youtube): 6.481s
- click() time: 0.559s

### On Lambda 1536 MB (Max)

- (extract: 1.873s)
- launch(): 0.688s
- newPage(): 0.056s
- goto(youtube): 2.154s
- click(): 0.116s

**Comment by icarusmiles** [comment]
@sambaiz I did all my requests with max memory, using chromeless was very slow. That request with max memory you gave as an example is not fast if it relies on user input/response. 4.9 seconds is poor considering half of that time deals with extraction and launch. This becomes more serious when you do slightly more complex functions. Mine weren't insane or anything and were processing at 13-14 seconds with max memory. On a local server I could do that with 2-3 seconds.

**Comment by eknkc** [comment]
@sambaiz thanks for the numbers, appreciate it. done my own tests and the results are similar so there is no noticable performance degredation. Also setting context.callbackWaitsForEmptyEventLoop and keeping the browser instance seems to work to avoid launch times in successive calls. 

One issue though, lambda does not provide a wide range of fonts so for exampla capturing baidu.com produces missing glyphs. Are there any known workarounds for this?

**Comment by homaily** [comment]
@sambaiz @miles-collier On lambda you need to install and open the browser only once per container. Then you just need to open a new page on each request and close it.
If you need your Lambda to response quickly then keep it warm so you don't need to do the install and launching again.

**Comment by gregorym** [comment]
@sambaiz I haven't tried but is [this](https://gist.github.com/gregorym/71ed4050e2791691c2b9f79cec7f8470) what you had in mind?

**Comment by sambaiz** [comment]
Thanks @eknkc @homaily @gregorym . I've fixed to launch only once at container startup.
@miles-collier If you keep Lambda warm but still late, I think it is good to try to measure which operation takes time.

**Comment by md97212** [comment]
@sambaiz @eknkc Any further insights into the "missing fonts" issue here? this will be a problem for screenshots (for ex) 
Is it feasible to use a version of chromium from s3 that doesn't have missing fonts?

**Comment by joelgriffith** [comment]
Missing fonts is more of an OS-type issue... You'd have to ensure your container is using something to install missing fonts or whatever else since Chrome uses what the system already has

**Comment by geertbrit** [comment]
@md97212:

Haven't tried this, so perhaps I'm missing something, but regarding the missing fonts issue: can't you 'just' use puppeteer's `evaluate` to inject a script that in turn loads in a bunch of web fonts? 

This would make the issue of Lambda not having some OS-level fonts moot, since it would just use the web fonts instead.

**Comment by md97212** [comment]
@gebrits @joelgriffith 
thanks for the tips, I will try 'evaluate'  when I get to that point.

**Comment by geertbrit** [comment]
@sambaiz : trying out your starter-kit and seems to work nicely all in all. However, sometimes (weirdly seems to be each 5th invocation?) I'm getting an error: 

````
{
  "errorMessage": "Protocol error (Runtime.enable): Target closed.",
  "errorType": "Error",
  "stackTrace": [
    "Session._onClosed (/var/task/node_modules/puppeteer/node6/Connection.js:313:23)",
    "Connection._onClose (/var/task/node_modules/puppeteer/node6/Connection.js:168:15)",
    "emitTwo (events.js:106:13)",
    "WebSocket.emit (events.js:191:7)",
    "WebSocket.emitClose (/var/task/node_modules/ws/lib/WebSocket.js:224:10)",
    "_receiver.cleanup (/var/task/node_modules/ws/lib/WebSocket.js:210:41)",
    "Receiver.cleanup (/var/task/node_modules/ws/lib/Receiver.js:520:15)",
    "WebSocket.finalize (/var/task/node_modules/ws/lib/WebSocket.js:210:22)",
    "emitNone (events.js:91:20)",
    "Socket.emit (events.js:185:7)"
  ]
}
`````

Have you seen this before?

**Comment by aslushnikov** [comment]
@gebrits looks like chrome crashes. We'll have a better support for this when the https://github.com/GoogleChrome/puppeteer/pull/960 lands.

**Comment by geertbrit** [comment]
@aslushnikov in the meantime to check my sanity would logs show up on crash using the 'dumpio' flag?

**Comment by aslushnikov** [comment]
@gebrits yes they should.

**Comment by aslushnikov** [comment]
Closing this since this [comment](https://github.com/GoogleChrome/puppeteer/issues/603#issuecomment-328936507) explains how to launch on lambda.

**Comment by rajanaggarwal1** [comment]
anyone found the solution? I'm still struggling with it

**Comment by gsbarreto** [comment]
I changed the `puppeteer` also the `puppeteer-core` and it worked successfully!
