### ISSUE TITLE
Page.screenshot never resolves in case of error

### ISSUE THREAD

**Issue by ejoebstl** [puppeteer/puppeteer#6031]
If an error happens inside `Page._screenshotTask` during taking a screenshot, the error is silenced and the `Page.screenshot` function never returns. This is due to incorrect error handling in the `ScreenshotTaskQueue` class, [found here](https://github.com/puppeteer/puppeteer/blob/e4de5f10d01b5bfb0ce686b6c32a38b57d80e12c/src/Page.ts#L152).

### Steps to reproduce

* Puppeteer version: 1.20.0 and latest
* Platform / OS version: Arch Linux
* Node.js version: 10.18.1

**What steps will reproduce the problem?**

Without digging into `_screenshotTask` itself, the following shows that `ScreeshotTaskQueue` silences errors and interrupts the promise chain:

```Javascript
// Copied from Page.ts
class ScreenshotTaskQueue {
  _chain: Promise<Buffer | string | void>;

  constructor() {
    this._chain = Promise.resolve<Buffer | string | void>(undefined);
  }

  public postTask(
    task: () => Promise<Buffer | string>
  ): Promise<Buffer | string | void> {
    const result = this._chain.then(task);
    this._chain = result.catch(() => {});
    return result;
  }
}

// Dummy function to simulate an error.
function throws(): Promise<Buffer | string> {
  throw new Error("Error")
}

async function main() {
  const queue = new ScreenshotTaskQueue()
  try {
  const res = await queue.postTask(throws)
    console.log("This is never exectued") 
  } catch(err) {
    console.log("An error happenend.")
  }
}

main()
```

**What is the expected result?**

For the example above, there should `An error happened` should be printed.

In general, the promise should reject in case of an error.

**What happens instead?**

Nothing. The program terminates without output.

**Comment by ejoebstl** [comment]
Nevermind - this was an issue with my environment. The code works as expected. Please disregard.

**Comment by fchwpo** [comment]
What was the issue like Im facing an issue where page.screenshot hangs i.e. not resolved nor rejected. What was the solution

**Comment by ejoebstl** [comment]
I found no solution, and I was unable to isolate/reproduce the issue cleanly. Best open a new issue with a good reproduction.
