### ISSUE TITLE
Node is detached from document

### ISSUE THREAD

**Issue by mahirhiro** [puppeteer/puppeteer#6033]
GOAL:
I currently am building a script that checks the last few messages in each conversation to see whether i can “mark as done” from a company account. The whole can loop through the list of people and get the messages but at soon as Its time to “mark a conversation as done” the next iteration of the loop breaks because of a “node is detached from the document”

* Puppeteer version: 
Chrome/83.0.4103.0
* Platform / OS version:
Chromium: Version 83.0.4103.0 (Developer Build) (64-bit)
* URLs (if applicable):
https://business.facebook.com/
* Node.js version:
v13.12.0

**What steps will reproduce the problem?**
1. Log in to a FB business account
2. mark more than 2 Facebook conversations as done using a certain ID

_Please include code that reproduces the issue._
```
for (let i = 0; i < section.length; i++) {
      try {
        await section[i].click();
        await page.waitForSelector('._suc._su6._5bpf');
        await page.$eval('._suc._su6._5bpf', form => form.click() ); // Here is where the issue happens
  } catch (err) {
    if ((err.message == 'Node is either not visible or not an HTMLElement' ||
      err.message == 'Node is detached from document')) {
        delay(2000);
    } else {
      stop = true;
    }
    console.log(Error(err), err.message, err.number);
  }
}
```

[**Screenshots**]
<img width="1197" alt="Screenshot 2020-06-17 at 13 49 26" src="https://user-images.githubusercontent.com/49659324/84883554-b5877c80-b0a1-11ea-8837-bba8e46ffe5b.png">
This selector will only have one occurrence for each page you are on so the ``` ('._suc._su6._5bpf') ``` only has once occurrence. until the conversation moves to another person in the list like this:
as it iterates:

<img width="808" alt="Screenshot 2020-06-17 at 13 54 35" src="https://user-images.githubusercontent.com/49659324/84883934-3b0b2c80-b0a2-11ea-9622-f6841d934e90.png">

**What is the expected result?**

I expect the for loop to continue checking the conversations 

**What happens instead?**

Error: Error: Node is detached from document
    at /Users/mahirhiro/headless-chrome/index.js:61:17 ...

**Comment by t1a2l** [comment]
@mahirhiro how did you solve this? I get the same issue on a simple button.

**Comment by mahirhiro** [comment]
@t1a2l I couldn't find a fix using puppeteer so I switched to selenium haha.

**Comment by KevinHCH** [comment]
I had the same problem, the error was the element was available inside the HTML, but not was available for puppeter, because puppeteer needs to "see" or "needs to have something visible" to touch it or click it.
The solution was to click through HTML  instead of puppeter
```js
//puppeteer handler
await row_element.click()

//html handler (solution)
await page.evaluate((element) => {
  element.click()
}, row_element)
```

**Comment by Ahmad-Hendi** [comment]
Hello everyone,

Thanks @KevinHCH for your solution i am trying to apply it on my project but i didn't get it yet

**Comment by gurudattgd04** [comment]
It’s basically same as stale element exception in selenium world.

Solution what i found is to use waitforselector and/or network idle wait.

Regards,
Gurudatt

**Comment by Ahmad-Hendi** [comment]
Thanks for your comment @gurudattgd04 , i will try it tomorrow !

**Comment by Rafik-Belkadi-Reccap** [comment]
I had the same Issue, here is what i did to solve this : 
```js 
        // launch broser
        const browser = await puppeteer.launch();
        // Launch page
        const page = await browser.newPage();
        // Navigate to url
        await page.goto(url);
        await page.waitForTimeout(2000);
        // Getting the parent element of my divs
        const parent = await page.$('div[class="more-options is-hidden-tablet"]').length
            ? await page.$('div[class="more-options is-hidden-tablet"]')
            : await page.$('div[data-name="language"]')
        // Array of Element Handle 
        const items = await parent.$$(':scope > .item > label')
        // loop through them for clicking
        for (let i = 1; i < items.length; i++) {
            // reseting the parent everytime i click so it doesn't throw "Detached from Node"
            // with the same operation
            const p = await page.$('div[class="more-options is-hidden-tablet"]').length
                ? await page.$('div[class="more-options is-hidden-tablet"]')
                : await page.$('div[data-name="language"]')
            const it = await p.$$(':scope > .item > label')
            let value = it[i]
            await value.click()
            await page.waitFor(1000)
            const lang = await value.evaluate(el => el.textContent)
            const firstComment = await (await page.$('#taplc_location_reviews_list_resp_rr_resp_0 > div > div')).$eval('a.title', el => el.children[0].textContent)
            console.log({ lang, firstComment })

        }
        await browser.close()
```

**Comment by VicentUCF** [comment]
In my case i use at the end of the for an a `await page.waitForTimeout(1000)` an it works perfect now

**Comment by malibu103** [comment]
> I had the same problem, the error was the element was available inside the HTML, but not was available for puppeter, because puppeteer needs to "see" or "needs to have something visible" to touch it or click it. The solution was to click through HTML instead of puppeter
> 
> ```js
> //puppeteer handler
> await row_element.click()
> 
> //html handler (solution)
> await page.evaluate((element) => {
>   element.click()
> }, row_element)
> ```

I had this same issue and this fixed it for me.  Thanks!

**Comment by jrandolf-google** [comment]
We no longer support Node < 14, please try this again with the latest version of Puppeteer and Node >= 14. If the issue still occurs, please reopen this issue and update the description :)
