### ISSUE TITLE
interceptor missing (not intercepting) multiple requests

### ISSUE THREAD

**Issue by BusDriver01** [puppeteer/puppeteer#6036]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.3.0
* Platform / OS version: Win10/64bit
* URLs (if applicable): kbb.com
* Node.js version: 10.16.3

**What steps will reproduce the problem?**
See code below. I expected that ALL requests will pass through the interceptor, but many requests that appear in DevTools are never acknowledged, thus no opportunity to "catch.". #4329 is similar, but was resolved via bugfix in 1.15, however I'm on 3.3.

_Please include code that reproduces the issue._
(code block below)

**What is the expected result?**
I expect that the call to `https://accounts.us1.gigya.com/accounts.login` to be intercepted.

**What happens instead?**
It is ignored in the interception code block `page.on('request', ...`  The request goes through without the opportunity to intercept. For debugging purposes, the interception block writes **all** URL's to console after we set `clicked=true`, but this URL doesn't appear there.

(the call to `https://accounts.us1.gigya.com/socialize.getSavedResponse` also fails to be recognized by the interception code block)

code:
```
const puppeteer = require('puppeteer');

const getPuppeteer = async () => {
  let browser = await puppeteer.launch({
    timeout: 120000,
    headless: false,
    devtools: true,
    //slowMo: 100,
  });
  return new Promise((resolve, reject) => {
    resolve(browser)
  });
}


async function kbb() {

  let exclusions = /\.gif|\.png|\.jpg|\.ttf|facebook|doubleclick|nr-data|foresee|demdex|pinterest|yimg|clarivoy|marinsm|mavenaudiences|go-mpulse|zemanta|esm1|adnxs|adsrvr|rockerbox|arrivalist|googleads|googlesyndication|google-analytics|googletagmanager/;

  let clicked = false;
  let browser = await getPuppeteer(); //cloud || false);
  try {
    const page = await browser.newPage();

    // this is our interceptor, where we capture the browser's POST 
    page.on('request', async(request) => {
      if (clicked) console.log(request.url() + "\n") // display ALL request URLs after the "Sign In" button was clicked
      if (request.url().search(/login/g) > 0) {
        // if (request.method == "POST") {
        // if (request.url().includes("accounts.login")) {
        console.log("yes!")
        console.log(request.url());
        console.log(request.method());
        let body = request.postData();
        console.log(body);
        request.abort();
      } else if (request.url().search(exclusions) > 0) {
        request.abort();
      } else {
        request.continue();
      }
    });


    await page.setRequestInterception(true);
    await page.goto("https://www.kbb.com/mykbb/");
    await page.waitForSelector(".mykbb-auth");

    await page.type("#loginEmail", 'githubuser@gmail.com');
    await page.type("#loginPassword", 'ilovecars');
    console.log("clicking...");
    clicked = true; // set to true just before clicking... for debugging we can set the interceptor to catch everything when true
    await page.click("#myKbbSignin");

  } catch(err) {
    console.log(err);
  } finally {
    if (browser) {
      // browser.close();
      // browser.disconnect();
    }
  }  
}

(async () => {
  let my_kbb = await kbb()
  console.log("done!")
})();

```

**Comment by dougwithseismic** [comment]
Similar issue here 
    "puppeteer": "^5.3.1"

Requests with type of 'document' are caught - all others aren't. On inspection, passing options when calling Puppeter.launch was causing this. Specifically userDataDir: './tmp'. Removing reference to userDataDir sorted it.

Hopefully this helps someone.

 ```
const args = [
  '--no-sandbox',
  '--disable-setuid-sandbox',
  '--disable-infobars',
  '--window-position=0,0',
  '--ignore-certificate-errors',
  '--ignore-certificate-errors-spki-list',
  '--user-agent="Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SCH-I535 Build/KOT49H)"'
]

const options = {
  args,
  headless: false,
  ignoreHTTPSErrors: true,
  userDataDir: './tmp' // Removing this let all intercepts work.
}

const browser = await Puppeteer.launch(options)```

**Comment by andrisi** [comment]
Same issue here, pptr 5.4.1 - I can send the site if a developer reaches out to me. Chromium debugger shows about 20 requests, some are intercepted (and aborted by me) but others are not intercepted at all. I'm not using the userDataDir option.

Might be something to do with the actual site watching if the devtools are open, because if it is not, then interception works as expected.

**Comment by SwitchGM** [comment]
Exact same issue as well, puppeteer 5.5.0. Seems to miss specific types of types. like .m3u8 or .ts (streaming files). #5130

**Comment by joojn1122** [comment]
If anybody is still having problems, using `await page.setBypassServiceWorker(true)` solves the problem!

**Comment by wisdomcsharp** [comment]
I'm having the issue as well, the solution above didn't work. 

You need to go lower level. 

here's what worked: 

```js
    const cdp = await page.target().createCDPSession();
    await cdp.send('Network.enable');

    cdp.on('Network.responseReceived', (params) => {
       console.log(params.response.url)
    });
    
     // Get the response body
    const response = await client.send('Network.getResponseBody', {
      requestId: params.requestId,
    });

    // Output the response body
    console.log(response.body); // This will be either the content or base64-encoded data depending on the response type
    // If the response is base64-encoded, you need to convert it
    if (response.base64Encoded) {
      const buffer = Buffer.from(response.body, 'base64');
      console.log('Decoded response:', buffer.toString());
    }

```

**Comment by althaf101** [comment]
If your browser already had cached the resource, puppeteer will not get to intercept it since the resource will directly be served from the cache. 
To disable the cache, use the below
`await page.setCacheEnabled(false)`
