### ISSUE TITLE
Puppeteer 4 prependListener removeListener replacement assistance (removed apis)

### ISSUE THREAD

**Issue by Georgegriff** [puppeteer/puppeteer#6051]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 4.0

**What steps will reproduce the problem?**

This is not a bug this is issue for assistance on migrating a module.
Our test code relies on the following NPM package: https://github.com/Netflix/pollyjs/tree/master/packages/%40pollyjs/adapter-puppeteer

This code makes use of removed APIs in 4.0, i was hoping someone might be able to offer some help in suggesting what is the correct approach to code that relied on these previously, in the hopes i can do a PR to the third party module.

https://github.com/Netflix/pollyjs/issues/345

This is their code that will no longer work:
https://github.com/Netflix/pollyjs/blob/1223ba0dad16bf504074510ac060e7394a4cbac9/packages/%40pollyjs/adapter-puppeteer/src/index.js#L50

https://github.com/Netflix/pollyjs/blob/1223ba0dad16bf504074510ac060e7394a4cbac9/packages/%40pollyjs/adapter-puppeteer/src/index.js#L50

I think their code is appending listeners to the page: `request` and `requestfinished` and `requestfailed` and `close`

e.g. ( think)

```javascript
page.prependListener('request', ()=>{})
```

any help would be much appreciated.

**Comment by benmccann** [comment]
I was able to change it to:

    page.on('request', ()=>{})
