### ISSUE TITLE
Puppeeteer with arabic words is showing weird characters in PDF!

### ISSUE THREAD

**Issue by RamiMZahran** [puppeteer/puppeteer#6071]
* Puppeteer version: 4.0.0
* Node.js version: 12.18
* Platform / OS version: Cloud Run with this Docker Image
```
FROM buildkite/puppeteer 
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY . ./
CMD [ "npm", "start" ]
```
_Please include code that reproduces the issue._

```
  const browser = await puppeteer.launch({
    defaultViewport: null,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await browser.newPage();
  const options = {
    format: 'A4',
    printBackground: true,
    preferCSSPageSize: true,
  };
  const temp = `<!DOCTYPE html>
  <html>
  <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Page Title</title>
  </head>
  <body>
  
  <h1>مرحبا</h1>
  
  </body>
  </html>`;
  await page.setContent(temp, {
    waitUntil: 'networkidle0',
  });

  const saved = await page.pdf(options);
  await browser.close();
```
**What is the expected result?**

The expected output would be a pdf file with h1 tag of the word "مرحبا"

**What happens instead?**

This is the output I am getting from the server.

![Screenshot from 2020-06-22 14-26-43](https://user-images.githubusercontent.com/27008775/85287445-910e1480-b494-11ea-8280-2c3ea09fb28e.png)

It works fine on local machine but this is the output from the server.

**Comment by bushev** [comment]
Hey @RamiMZahran, what was the solution?

**Comment by ahmad101khaled** [comment]
whats the solution @RamiMZahran

**Comment by RamiMZahran** [comment]
It was the docker image that didn't support the locale.
