### ISSUE TITLE
Unable to click on hyperlink via puppeteer

### ISSUE THREAD

**Issue by sayom88** [puppeteer/puppeteer#6072]
I am trying to automate https://www.tesco.com/groceries/ portal. In that there is a hyperlink click on the food elements like Fresh Food,Bakery etc. 

May I know how to can I automate this click event via Puppeteer.

Below is the code snipeet that i am using:

**_const [value1] = await page.$x("//span[contains(text(),'Frozen Food')]")
await  value1[0].click_**

This is not clicking. Can you please help.

**Comment by hkelly93** [comment]
It looks like you're missing the ()'s on your click. I'm not sure if thats from copying/pasting, but `click` is a function.

**Comment by vsemozhetbyt** [comment]
Also, `value1` in `const [value1] = await page.$x()` is already an `ElementHandle`, it is not an array, so you need not `[0]` index in the next line. Just try `await value1.click()`.

**Comment by sayom88** [comment]
okie thanks. Now it works. 

Another thing to ask here, when I run the test, I see there is a extra browser that get launched along with the browser where my application gets launched. Do you know how to remove this extra browser?
