### ISSUE TITLE
Remove `emulateMedia` in v5

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#6077]
The next release will also be a major version due to the removal of the `puppeteer/DeviceDescriptors` files. Given that, we could also remove `emulateMedia`, which has been deprecated a while? Especially as the fix is to swap to `emulateMediaType`.

@mathiasbynens WDYT?

**Comment by mathiasbynens** [comment]
SGTM

**Comment by christian-bromann** [comment]
This can be closed as it was fixed by https://github.com/puppeteer/puppeteer/pull/6084
