### ISSUE TITLE
page.waitForSelector doesn't work on baidu.com

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#609]
The following script fails with baidu.com:
```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://baidu.com');
  await page.waitForSelector('div');
  browser.close();
})();
```

The reason is that Baidu nullifies MutationObserver that is required for `waitForSelector`.

**Comment by aslushnikov** [comment]
As reported in #1668, `page.click(selector)` doesn't work if page redefines `window.Node`

**Comment by nylen** [comment]
Suggest renaming this issue to something more general, like: "Puppeteer methods break if pages redefine built-in global objects"

Is this sort of thing even possible to work around at the library level?  I did this in my code, which seems to work ok:

```js
await this.page.evaluate( () => {
    if ( ! window.Node ) {
        window.Node = {};
    }
    if ( ! Node.ELEMENT_NODE ) {
        Node.ELEMENT_NODE = 1;
    }
} );
```

**Comment by klichukb** [comment]
Any updates on this issue?
