### ISSUE TITLE
Add optional args to page.screenshot, to create directories if the provided path doesn't exists.

### ISSUE THREAD

**Issue by gattasrikanth** [puppeteer/puppeteer#6093]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: Mac 10.14.6
* URLs (if applicable):NA
* Node.js version: 12

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `` await page.screenshot({path: `results/screenshots/${projectname}/${date}/SiteAdded.png`}); ``

**What is the expected result?**
Clearly the path is dynamically generated and so path doesn't exist. It would be great if the directories can be crated and the file is saved in that location. OR Provide some additional flag to say create path if not found.

**What happens instead?**
`ENOENT: no such file or directory, open 'results/screenshots/...../SiteAdded.png'`

**Work around**
The work around isn't that bad or hard to implement, but it would be nice if Puppeteer does't it by default.
More discussion at: https://stackoverflow.com/questions/62427587

**Comment by jackfranklin** [comment]
@mathiasbynens WDYT about this? 

I'm on the fence; it would be an easy thing to add support for, but it's also easily dealt with in user land.

**Comment by DhirajKhot** [comment]
@jackfranklin @mathiasbynens 
Any update on this? I faced similar issue and it looks weird to have the empty directory created for the sake of saving the screenshots.
