### ISSUE TITLE
page.screenshot returns two different screenshot of the same page in headless or gui mode

### ISSUE THREAD

**Issue by andreabisello** [puppeteer/puppeteer#6101]
on an updated windows 10 with node 12.13.0 with everything updated

```
  "dependencies": {
    "jest": "latest",
    "puppeteer": "latest",
    "puppeteer-extra": "latest"
  }
```
page.screenshot()
returns different images switching from headless or gui mode.

as you can see in the images, the login button on the second one has a yellow border.

GUI MODE
![gui](https://user-images.githubusercontent.com/2149815/85701825-17696700-b6de-11ea-81fa-35cdeb0839e5.png)
HEADLESS MODE
![headless](https://user-images.githubusercontent.com/2149815/85701832-189a9400-b6de-11ea-8bba-585624d320b6.png)

to reproduce, 

clone this repository https://github.com/andreabisello/jest-image-snapshot-example
you will find this test

```

const puppeteer = require('puppeteer-extra')

describe('headless differences Test', () => {

    test("headless and not headless screenshot should to be the same", async () => {
        jest.setTimeout(60000)
        browser = await puppeteer.launch({
            headless: false,
            defaultViewport: {width: 1800, height: 900},
            args: ["--start-maximized"],
            devtools: false
        })
        page = await browser.newPage()
        await page.goto("https://legaltest.solutiondocondemand.com", {
            timeout: 20000,
            waitUntil: ['load', 'domcontentloaded', 'networkidle0', 'networkidle2']
        })
        await page.waitFor(5000)
        loginBox = await page.waitForSelector('#loginBox', {visible: true, timeout:30000})

        //removing time variant area
        await page.evaluate(() => {
            document.querySelector('#lblNow').style.visibility = "hidden"
        })

        await page.screenshot({
            path:"gui.png"
        })

        await browser.close()
    })
})

```

as you can see, the test simply open the page, wait for network activities, wait also other 5000ms only to be safe, remove the timestamp in the page (because it will change everytime) , and take a screenshot.

gui.png if headless is false, headless.png if headless is true.

the image should to be the same, but there is a difference.

**Comment by dpmott** [comment]
At first glance, it looks like the difference in the images is that the Login button has focus in headless mode.  Is that correct?

If you don't hide the `lblNow` element, do the images still differ in the same way (excluding differences in the time variant area)?
