### ISSUE TITLE
page.evaluate doesn't run the function, throws a TypeError

### ISSUE THREAD

**Issue by cozimacode** [puppeteer/puppeteer#6103]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 4.0.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: v12.13.0

**What steps will reproduce the problem?**

I am using **react-chat-widget** and want to run one of it's functions **addUserMessage** through puppeteer on the accessed page. I imported the function in my test file and passed it as a variable through **page.evaluate**. However it doesn't execute and I get a **TypeError** that addUserMessage is not a function.

Here's my test.js file

```
import React from "react";
import puppeteer from "puppeteer";
import { addUserMessage } from "react-chat-widget";
let browser;

beforeAll(
  async () =>
    (browser = await puppeteer.launch({
      headless: false,
      slowMo: 50,
      defaultViewport: null,
      args: ["--start-maximized"],
    }))
);

test("add a message", async () => {
  const context = await browser.createIncognitoBrowserContext();
  const page = await context.newPage();
  await page.goto("http://localhost:3000");
  await page.click(".rcw-launcher");
  await page.evaluate((addUserMessage) => addUserMessage("Hurray!"));
}, 10000);
```

**What is the expected result?**

To add the message "Hurray!". I am sure the function is correct cause it works in an onclick event.

**What happens instead?**

Evaluation failed: TypeError: addUserMessage is not a function

Any help would really be appreciated.

**Comment by vsemozhetbyt** [comment]
There are two issues here.

1. In `await page.evaluate((addUserMessage) => addUserMessage("Hurray!"));` the `addUserMessage` is undefined as you do not add the function as a parameter. This should be: `await page.evaluate((addUserMessage) => addUserMessage("Hurray!"), addUserMessage);`.

2. Even with this syntax, this function transferring is impossible: per docs, you can only transfer serializable values from Node.js (puppeteer) context into browser context, and functions are not serializable. If `react-chat-widget` can be imported in the web page context, you need to import it there first and then just call inside `page.evaluate()`.

 See `page.evaluate()` in docs for details.

**Comment by cozimacode** [comment]
> 
> 
> There are two issues here.
> 
>     1. In `await page.evaluate((addUserMessage) => addUserMessage("Hurray!"));` the `addUserMessage` is undefined as you do not add the function as a parameter. This should be: `await page.evaluate((addUserMessage) => addUserMessage("Hurray!"), addUserMessage);`.
> 
>     2. Even with this syntax, this function transferring is impossible: per docs, you can only transfer serializable values from Node.js (puppeteer) context into browser context, and functions are not serializable. If `react-chat-widget` can be imported in the web page context, you need to import it there first and then just call inside `page.evaluate()`.
> 
> 
> See `page.evaluate()` in docs for details.

Thanks @vsemozhetbyt. I guess I have to stick with shallow rendering using enzyme and passing props within.
