### ISSUE TITLE
Accentueded characters rendered with system font in pdf

### ISSUE THREAD

**Issue by simion314** [puppeteer/puppeteer#611]
Using some google fonts like dancing script and using accentuated characters like ę ą ł ó ś ć ń ź ś we get different results when rendered in chrome and when rendered in pdf, for some reason the accentuated "o" is rendered fine. I tested a different htmltopdf tool named wkhtmltopdf and I get same result

[temp.pdf](https://github.com/GoogleChrome/puppeteer/files/1263260/temp.pdf)
[temp.html.txt](https://github.com/GoogleChrome/puppeteer/files/1263267/temp.html.txt)

**Comment by aslushnikov** [comment]
This seems to be a chromium issue. I'd appreciate if you file it upstream to `crbug.com/new`.
