### ISSUE TITLE
Support Network.requestWillBeSentExtraInfo to get ALL request headers?

### ISSUE THREAD

**Issue by Cuadrix** [puppeteer/puppeteer#6117]
Maybe implement it so we can intercept requests with ALL the headers instead of the measly 2-3 that we get from the current [httpRequest.headers()](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#httprequestheaders) ?

Related:
- https://github.com/puppeteer/puppeteer/issues/5364
- https://github.com/puppeteer/puppeteer/issues/3436

**Comment by christian-bromann** [comment]
I am happy to take a stab at it but wonder what would be the best way to implement this. The `Network.requestWillBeSentExtraInfo` event always happen after the event listener for the network interception, e.g.

```js
  page.on('request', interceptedRequest => {
    // ...
  });
```

is triggered as `page.on('request', ...)` is executed on `Network.requestWillBeSent`. Also there is no guarantee that extra header infos are given for a certain resource. Therefor my suggestion is to enhance the `HTTPRequest.headers()` with a parameter like `waitForExtraHeaders` set to a default of e.g. 500ms that waits until these extra headers are sent or when timed out returns the headers it received from `Network.requestWillBeSent`.

Does that make sense?

**Comment by Cuadrix** [comment]
Wouldn't that 'block' the execution for 500ms then?
Someone might want the headers resolved before that.

What are the criteria for `Network.requestWillBeSentExtraInfo` to be fired when it's not guaranteed?
Why exactly is it not guaranteed?

**Comment by thomasm789** [comment]
@christian-bromann Did you have any success?
