### ISSUE TITLE
Using `userDataDir` overwrites `extraPrefsFirefox`

### ISSUE THREAD

**Issue by mjzffr** [puppeteer/puppeteer#6119]
When passing both `extraPrefsFirefox` as well as `userDataDir` options to the launcher, `extraPrefsFirefox` is effectively ignored. That is, the profile in `userDataDir` takes precedence over any default Firefox prefs provided by `FirefoxLauncher` as well as the `extraPrefsFirefox` option. 

This should be clarified in documentation. Perhaps `extraPrefsFirefox` should have the highest precedence.

**Comment by whimboo** [comment]
This has been fixed with my PR #7684.
