### ISSUE TITLE
add setAttribute to ElementHandle

### ISSUE THREAD

**Issue by Cyberpunkerplus** [puppeteer/puppeteer#612]
hi,all ,  i just find there has been a new API called getAttribute OF ElementHandle, so i just add setAttribute. It seems work fine.

[add setAttribute to ElementHandle](https://github.com/Cyberpunkerplus/puppeteer/commit/3aeedc4a6dfdffca844348831dc191981a311a02)

**Comment by aslushnikov** [comment]
@Cyberpunkerplus that's reasonable, feel free to send a PR

**Comment by aslushnikov** [comment]
@Cyberpunkerplus update: we've decided to implement #625, so there's no need for the setAttribute any more.
