### ISSUE TITLE
feature - Generating Password Protected PDF

### ISSUE THREAD

**Issue by rish-hub** [puppeteer/puppeteer#6120]
###  Generating Password Protected PDF
 
 Is there any way to generate password protected pdf using puppeteer

**Comment by cristofersr** [comment]
were you able to get it?

**Comment by jamieweavis** [comment]
Apparently not according to https://github.com/puppeteer/puppeteer/issues/657, this would be awesome if it was built into puppeteer though!

**Comment by Sparticuz** [comment]
You should generate the pdf, then use something like qpdf to encrypt it with a password

**Comment by OrKoN** [comment]
We don't have plans to support this in Puppeteer.
