### ISSUE TITLE
Can't install puppeteer > 3.0.0 with Node.js v8

### ISSUE THREAD

**Issue by barnu5** [puppeteer/puppeteer#6122]
### Steps to reproduce

* Puppeteer version:
>3.0.0
* Platform / OS version:
Windows
* URLs (if applicable):
* Node.js version: 8.16

**What steps will reproduce the problem?**
`npm install puppeteer` fails on puppeteer versions greater than 3.0.0

**Comment by jackfranklin** [comment]
Hi @barnu5 ,

We require at least Node 10.18 from v3 onwards, so you'll need to upgrade to install it.
