### ISSUE TITLE
Proposal: remove amount of supported environment variables

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#6123]
Puppeteer supports environment variables to allow people to configure things
like:

- where to download the browser from
- which product to download/run (Chrome/FF)
- which Chromium revision to download
- which browser to run (either via providing a product, or a binary executable)
- whether to skip the download of Puppeteer

These are all reasonable things that should be configurable, but I'd like to
propose that we slim down the number of ways we let people configure these.

For example, the `downloadBrowser` function in `install.ts` checks three
different places for environment variables:

```js
const product =
  process.env.PUPPETEER_PRODUCT ||
  process.env.npm_config_puppeteer_product ||
  process.env.npm_package_config_puppeteer_product ||
  'chrome';
```

I didn't even know until reading this code that `npm_config_*` variables
existed, and similarly for `npm_package_config`. I would wager that most people
are using environment variables if they need to configure Puppeteer's behaviour.

I would like to suggest we move to only supporting environment variables, so
that the code above would look like so:

```js
const product = process.env.PUPPETEER_PRODUCT || 'chrome';
```

We can do this incrementally to help users who do rely on the old settings:

1. Ship a release that logs a warning if we detect use of `npm_config_*` or
   `npm_package_*`.
2. In a future major version (giving people reasonable time to deal with the
   warnings) remove support for those environment variables.

Any thoughts welcome :) If you rely on `npm_config_*` or `npm_package_*`
variables please do let me know; I'd like to understand why those options are
preferable over environment variables.

**Comment by jackfranklin** [comment]
@mathiasbynens @OrKoN @hanselfmu please LMK WYT!

**Comment by OrKoN** [comment]
The advantage of using `npm_package_*` variables is that you can keep all your configuration in package.json instead of providing the variables in the script commands which might be messy. Do you know when and why it was added in the first place?

**Comment by jackfranklin** [comment]
That seems like a reasonable benefit; but it's not something I've seen anyone do across the community/ecosystem, so I'm wondering if anyone does take advantage of that. Even within devtools we use environment variables.

I'm not sure on the original context - maybe @mathiasbynens knows more?

**Comment by mathiasbynens** [comment]
> I'm not sure on the original context - maybe @mathiasbynens knows more?

This was introduced to address #648. (Environment variables were only introduced later, in #3190.) It seems this is a common/expected mechanism to support proxy configurations through `package.json`.

A more conservative version of this change would be to get rid of the `process.env.npm_` usage only for non-proxy settings, but I could see how that might be confusing as well.

I'm not sure what to think about this change, to be honest.

cc @mjzffr since this impacts the way `product` is determined -- would y'all be okay with this change?

**Comment by jackfranklin** [comment]
My main thought and motivation for suggesting this was that I was unaware of the `npm_*` environment variables and suspect few people rely on them or use them. If that's the case, it's a small bit of maintenance burden we can remove. If we're not sure, let's leave it be for sure. I may then invest some time writing some helpers to make it easier to support this set of config for each given environment variable that we care about.

**Comment by mjzffr** [comment]
I don't have a good sense of how these are used in the wild, but I've been surprised a couple of times by what some Puppeteer-based frameworks and test harnesses rely on. Maybe reach out to a few?

Another idea: what about refactoring the env checks into a general utility method to reduce the maintenance burden? So you could call e.g. `product = getEnv('puppeteer_product') || 'chrome'`

**Comment by OrKoN** [comment]
Perhaps it would make sense to deprecate the usage of these env variables for a few releases before removing? E.g., 

```
function deprecate(value) {
  if (value)
    console.log('Deprecated...');
  return value;
}

const product =
  process.env.PUPPETEER_PRODUCT ||
  deprecate(process.env.npm_config_puppeteer_product) ||
  deprecate(process.env.npm_package_config_puppeteer_product) ||
  'chrome';
```
