### ISSUE TITLE
https://pptr.dev/ has a 404 on the landing page

### ISSUE THREAD

**Issue by psmarshall** [puppeteer/puppeteer#6127]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: n/a
* Platform / OS version: Mac, Chrome
* URLs (if applicable): https://pptr.dev/
* Node.js version: n/a

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Go to https://pptr.dev/

**What is the expected result?**
See some useful information about puppeteer

**What happens instead?**
The main content of the page says '404: Not Found'

![Screen Shot 2020-06-30 at 2 57 40 pm](https://user-images.githubusercontent.com/7401419/86136322-3ad04f80-baec-11ea-8de3-4a16ee0ce2de.png)

**Comment by mathiasbynens** [comment]
Looks like a request to `https://pptr.dev/docs/assets/overview.png` is 404ing. I might have broken that here: c2d32b1c19de37c660e122b59a0f6e6b67044f2f

**Comment by mathiasbynens** [comment]
Ah, it actually broke after a84e07ceaa485e091881c4a0a9c3755a88707394.
