### ISSUE TITLE
page.screenshot hangs or freezes in headless mode for url and it gives an error Protocol error (Page.captureScreenshot): Unable to capture screenshot in case of non-headless mode

### ISSUE THREAD

**Issue by fchwpo** [puppeteer/puppeteer#6136]
url  = http://previewshop.jdomni.com/diamondsupermart?forScreenshot=true

const newPage = await browserInst.newPage();
	const finalSSOptions = {
		...getDefaultSSOption(),
		...options,
		type: 'fullpage',
		// waitFor: '1000',
		isMobile: true
	}
	console.log(finalSSOptions);
	if(!!finalSSOptions.isMobile){
		const device = devices['iPhone 6'];
		console.log('Emulating Device', device.name);
		await newPage.emulate(device)
	}
	console.log('Navigating')
	await newPage.goto(url, {
		waitUntil: finalSSOptions.waitUntill
	})
	console.log('Navigation Done')
	
	const waitFor = finalSSOptions.waitFor ? parseInt(finalSSOptions.waitFor) : defaultWaitTime;
	
	if(shouldAutoScroll(finalSSOptions.type as string)){
		console.log('Auto Scrolling Page')
		await autoScroll(newPage)
	}
	// await newPage.addStyleTag({content: 'div.edit-content {display: none;}'})
	if(waitFor){
		console.log('Waiting For ', waitFor, 'ms')
		await newPage.waitFor(waitFor)
	}
	const screenshotPath = `${folderOptions.dir}/${uuid()}.png`
	console.log('SS Started');
	const pageSSOptions: ScreenshotOptions = {
		path: screenshotPath,
		type: "png"
	}
	if(finalSSOptions.type == 'fullpage'){
		pageSSOptions.fullPage = true;
	}
	await newPage.screenshot(pageSSOptions)
	console.log('SS Done');

**Comment by fchwpo** [comment]
Promise is not resolved/rejected

**Comment by fchwpo** [comment]
I have fixed this issue it was because of shared memory size in my docker container. As I had to use old docker engine on some server with docker-engine 1.5.

**Comment by qubiack** [comment]
@fchwpo how did you solve this issue? I have something very similar with docker 19.03.9
