### ISSUE TITLE
Uncaught NodeError: The "original" argument must be of type function

### ISSUE THREAD

**Issue by javanf** [puppeteer/puppeteer#6149]
任意页面导入 import { xxx } from '../../puppeteer/test'
启动服务后，浏览器控制台就报错了

puppeteer2.1.1没有问题

puppeteer4.0.1/5.0.0都会报错

希望官方能给个解决方案。谢谢。

**Comment by Yangfan2016** [comment]
m

**Comment by Yangfan2016** [comment]
mark

**Comment by Yangfan2016** [comment]
> 任意页面导入 import { xxx } from '../../puppeteer/test'
> 启动服务后，浏览器控制台就报错了
> 
> puppeteer2.1.1没有问题
> 
> puppeteer4.0.1/5.0.0都会报错
> 
> 希望官方能给个解决方案。谢谢。

hxd, 仔细看文档里，有写

![image](https://user-images.githubusercontent.com/17830872/88453677-c34bd100-ce9b-11ea-8746-807b65fe040e.png)

**Comment by igtheshy1** [comment]
I seem to have the same problem with version 14.4.0
![image](https://user-images.githubusercontent.com/73973701/98761763-217fce00-2411-11eb-9b8c-08838ca728b0.png)

**Comment by DanielRibeiroPGMotta** [comment]
Me too I have v14.15.1, and had the same with 12.8.0, only by importing puppeteer, it already shows the error.

**Comment by fx1357** [comment]
Your answer doesn't help.
It is the same even if you upgrade all to the latest version.

**Comment by fx1357** [comment]
> > '../../puppeteer/test'에서 모든 페이지 가져 오기 {xxx} 가져 오기 
> > 서비스를 시작한 후 브라우저 콘솔이 오류를보고합니다.
> > puppeteer2.1.1 문제 없음
> > puppeteer 4.0.1 / 5.0.0은 오류를보고합니다.
> > 공무원이 해결책을 제시 할 수 있기를 바랍니다. 감사합니다.
> 
> hxd, 문서를주의 깊게 살펴보십시오.
> 
> ![영상](https://user-images.githubusercontent.com/17830872/88453677-c34bd100-ce9b-11ea-8746-807b65fe040e.png)

Your answer doesn't help.
It is the same even if you upgrade all to the latest version.

**Comment by fx1357** [comment]
> > 任意页面导入 import { xxx } from '../../puppeteer/test'
> > 启动服务后，浏览器控制台就报错了
> > puppeteer2.1.1没有问题
> > puppeteer4.0.1/5.0.0都会报错
> > 希望官方能给个解决方案。谢谢。
> 
> hxd, 仔细看文档里，有写
> 
> ![image](https://user-images.githubusercontent.com/17830872/88453677-c34bd100-ce9b-11ea-8746-807b65fe040e.png)

Your answer doesn't help.
It is the same even if you upgrade all to the latest version.
