### ISSUE TITLE
Failed at the puppeteer@5.0.0 install script.

### ISSUE THREAD

**Issue by simple-YoungBadBoy** [puppeteer/puppeteer#6156]
**Tell us about your environment:**

* Puppeteer version:puppeteer@5.0.0
* Platform / OS version:mac 10.15.5 (19F101)
* URLs (if applicable):nope
* Node.js version:v10.11.0

**What steps will reproduce the problem?**
npm:
sudo npm i puppeteer --unsafe-perm = true --allow-root
Use npm install to get this error.
![image](https://user-images.githubusercontent.com/20324269/86493560-90368600-bda4-11ea-80aa-8868b2a5f5b8.png)

I haven't found a solution for a long time, please help

**Comment by jackfranklin** [comment]
I think your Node version is too old; make sure you're using Node 10.18.1 or higher.

You could also remove that folder and try again - I'm not sure what's gone wrong there: `rm -r node_modules/puppeteer/.local-chromium`.
