### ISSUE TITLE
Error: No node found for selector

### ISSUE THREAD

**Issue by fromb2b** [puppeteer/puppeteer#6159]
Hi,
   I use the latest puppeteer version on Windows10.
  I try to access gmail with puppeter, but  I get Error: No node found for selector

***************************************

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

 
  await page.goto('https://gmail.com');
  await page.waitFor(1000);

  await page.click('.OabDMe cXrdqd Y2Zypf');
 /* await page.keyboard.type('email@gmail.com');
  await page.click('.RveJvd.snByac');
  await page.click('.AxOyFc.snByac');
  await page.keyboard.type('pass');*/
  await page.waitFor(1000);

  
  await page.screenshot({path: 'newsletter.png'});

  await browser.close();
})();

****************************

OabDMe cXrdqd Y2Zypf  is the classname I am targeting.
I tried different syntaxes like .OabDMe > .cXrdqd > .Y2Zypf but I keep getting the same error

Thank you for your recommandations.

**Comment by vsemozhetbyt** [comment]
Maybe `await page.waitFor(1000);` does not suffice. ~Try to use `await page.waitForSelector('.OabDMe cXrdqd Y2Zypf');` instead.~

P.S. It seems this should be ``await page.waitForSelector('.OabDMe .cXrdqd .Y2Zypf');``.

**Comment by photocherkaoui** [comment]
Where should I place it please, can you put it in the afore mentionned code?

**Comment by fromb2b** [comment]
After replacing it I still get this error:

 Navigation timeout of 30000 ms exceeded

**Comment by fromb2b** [comment]
I have another question regarding classnames:
For a class named:  DarkModeToggle__Layout-cfa1ot-0 exXfxw  , how can I point to it?

**Comment by vsemozhetbyt** [comment]
> Navigation timeout of 30000 ms exceeded

Then maybe browser behavior is different in headless mode. Try to use `puppeteer.launch({ headless: false});` and check the element in the console.

> For a class named: DarkModeToggle__Layout-cfa1ot-0 exXfxw , how can I point to it?

You can try `'[class="DarkModeToggle__Layout-cfa1ot-0 exXfxw"]'`.

**Comment by vsemozhetbyt** [comment]
And maybe use `'.OabDMe .cXrdqd .Y2Zypf'` instead of `'.OabDMe cXrdqd Y2Zypf'`.

**Comment by photocherkaoui** [comment]
Thank you, as you excpected, headless mode was ressponsible for slowing down the process.

However, I have a concern about speed in production: will it be the same as development mode? Or it depends on the user...
And how to optimize it in both cases?

**Comment by aidulcandra** [comment]
The problem may be the class names are auto generated, the next time you load the page the class names may be different. This is to prevent web crawlers. You should select the element not with the class names, but with the structures and the element types, if they have attributes you should use that too
