### ISSUE TITLE
China cannot installed when download chromium

### ISSUE THREAD

**Issue by davistsin** [puppeteer/puppeteer#6160]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

China's firewall makes it impossible to download chromium, I hope your outstanding team will produce a puppeteer-cn, just change the download address

**What happens instead?**

**Comment by dcomdjl** [comment]
cnpm

**Comment by davistsin** [comment]
I had found puppeteer-cn in npmjs,  close this issue.
By the way, I don't like to use cnpm
