### ISSUE TITLE
Typescript types a little wrong

### ISSUE THREAD

**Issue by patrickjh** [puppeteer/puppeteer#6162]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^5.0.0 @puppeteer/types ^3.0.1
* Platform / OS version: Windows
* URLs (if applicable):
* Node.js version: 12.16.3

**What steps will reproduce the problem?**

Using typescript types from @types/puppeteer
You are missing the frame() method on the ExecutionContext interface that you receive from ElementHandle.executionContext().
But the frame() method exists in the code base and documentation and it works. I am having to cast ExecutionContext to any and then call the frame() method and cast that to Frame, which is not great Typescript

_Please include code that reproduces the issue._

1.     const element = await this.page.waitFor('.whatever')
    element.executionContext().frame() //this last method frame() is marked as not a property in typescript.
// When I examine the index.d.ts, typescript is correct it is not there
2.
3.

**What is the expected result?**
There should be a frame() method on the ExecutionContext declaration in typescript as it is in your docs and it works. Should be on the index.d.ts file around line 865.

Should say something like: 

/** The class represents a context for JavaScript execution. */
export interface ExecutionContext extends JSEvalable {
  frame(): Frame | null; // this is missing
  queryObjects(prototypeHandle: JSHandle): Promise<JSHandle>;
}

**What happens instead?**
Typescript throws an error and underlines it.

**Comment by jackfranklin** [comment]
Hi,

Thanks for the bug report. We don't maintain `@types/puppeteer` and we're currently working on shipping our own built in types (see #6124). So hopefully once we ship that (hopefully in a not-too-distant-future release) this should be resolved.

In the mean time I'm going to mark this as closed as we don't maintain the 3rd party types.
