### ISSUE TITLE
evaluateOnNewDocument is broken on firefox

### ISSUE THREAD

**Issue by elharrak-bouygues** [puppeteer/puppeteer#6163]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.0.0 (and 3.3.0)
* Platform / OS version: MacOS 10.15.5
* Node.js version: v12.14.0

**What steps will reproduce the problem?**

1. Run this code
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    product: 'firefox',
  });
  const page = await browser.newPage();
  await page.evaluateOnNewDocument(() => {
    window.addEventListener('DOMContentLoaded', () => console.log('Loaded!'));
  });
  page.on('console', (msg) => console.log(msg.text()));
  await page.goto('http://example.com');

  await browser.close();
})();
```
**What is the expected result?**
Print `Loaded!`on console.

**What happens instead?**
It doesn’t print `Loaded!` 

**Note:**
It works on chrome.

**Comment by elharrak-bouygues** [comment]
Here is my console outputs when running with `dumpio: true`:

```
*** You are running in headless mode.
DevTools listening on ws://localhost:59266/devtools/browser/803e566d-14bb-074a-92df-37b0f55a82fa
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
Exiting due to channel error.
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
Exiting due to channel error.
Exiting due to channel error.
```

**Comment by jackfranklin** [comment]
@mjzffr @whimboo might be one for you :)

**Comment by mjzffr** [comment]
The corresponding protocol-level work in Firefox is tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1601695

**Comment by mjzffr** [comment]
@jackfranklin @mathiasbynens It would be helpful to have issue labels to distinguish client versus server browser-specific issues, e.g. `firefox-client` for an issue at the Puppeteer level, e.g. with launch/install and just `firefox` for protocol implementation such as this issue.

**Comment by elharrak-bouygues** [comment]
@mjzffr Thank you for the tracking link. 
If I understand correctly, it is not a bug, it is just not implemented yet! 
Since all this ticket dependencies are resolved, Do you know when to expect an implementation? and if there is a temporary workaround/hack?

**Comment by mjzffr** [comment]
@elharrak-bouygues That's right, Firefox support is still experimental. I'm not aware of a specific timeline, but this part of the protocol has a higher priority than other features.

**Comment by dev-point-team** [comment]
i hop this get high priority

**Comment by HMaker** [comment]
It's broken in Firefox Nightly r94.0a1 which is used by puppeteer 10.4.0 too. From what I saw in mozilla's bug tracker that bug was not assigned to anyone.

**Comment by whimboo** [comment]
Sorry but we don't have the bandwidth to actually implemement this requested feature in Firefox. As such closing the issue.

Note that we also track in on our side via https://bugzilla.mozilla.org/show_bug.cgi?id=1601695.
