### ISSUE TITLE
Getting value from dropdown menu?

### ISSUE THREAD

**Issue by thebetterjort** [puppeteer/puppeteer#617]
```
<select name="mainlist" onchange="refresh(this);MainList.change(this)" onkeydown="typeAhead()" class="">
		
<option value="Appeals             ">Courts - Appeals</option>
<option value="Bankruptcy          ">Courts - Bankruptcy</option>
<option value="District            ">Courts - District</option>
<option value="Prob/Pretrial       ">Courts - Prob/Pretrial</option>
<option value="Public Defender     ">Courts - Public Defender</option>
<option value="Other               ">Courts - Other</option>
<option value="OX">AO Director &amp; Executive Offices</option>
<option value="OA">AO Department of Administrative Services</option>
<option value="OP">AO Department of Program Services</option>
<option value="OT">AO Department of Technology Services</option>
<option value="JX">Federal Judicial Center</option>
		<option value="Non - US Courts     ">Non - US Courts</option></select>
```

Would I use page click to select the proper dropdown and would this be the correct DOM query element?
await page.click('select[name="mainlist"] option[value="District"]');

**Comment by aslushnikov** [comment]
the following should do the trick:

```js
await page.evaluate(() => {
  document.querySelector(`select [value="District"]`).selected = true);
});
```

**Comment by thebetterjort** [comment]
I'm afraid this didn't work.
```

await page.evaluate(() => {
  document.querySelector((`select [value="District"]`).selected = true);
});
```
Thank you.

**Comment by JoelEinbinder** [comment]
```js
await page.evaluate(() => {
  document.querySelector(`select[name="mainlist"]`).selectedIndex = 2;
});
```

**Comment by twalpole** [comment]
@thebetterjort Your  parentheses are in the wrong place and your option values have a ton of trailing spaces, so of course the CSS selector as written won't work.  Since you're doing an exact match on the value you either need to include the spaces or switch to a starts with attribute matcher

    await page.evaluate(() => {
      document.querySelector(`select [value="District            "]`).selected = true;
    });

or

    await page.evaluate(() => {
      document.querySelector(`select [value^="District"]`).selected = true;
    });

**Comment by owlyowl** [comment]
Is there a way to work out how to get a select option based on the display value rather than the underlying value stored?
Thanks

**Comment by harisibrahimkv** [comment]
Seems like you can use the `page.select()` method for this.

https://stackoverflow.com/a/47435873

**Comment by edycarreyes99** [comment]
await page.select('(the HTML selector of the select input)', 'District');
