### ISSUE TITLE
Unexcpected behaviour after entering data

### ISSUE THREAD

**Issue by fromb2b** [puppeteer/puppeteer#6171]
Hi,

I use the latest puppeter version in Windows 10.

I am trying to scrape some hotel data with puppeteer from Booking but unfortunatly I have a problem:

First I enter date and destination (everything runs smooth in non-headless mode), but after I click on 
Search and move to the results page, I find that my dates are not specified.

Here is my code

const puppeteer = require('puppeteer');
(async  () => {
const browser = await puppeteer.launch({headless: false, ignoreHTTPSErrors: true,
devtools: false});
//{headless: false}
const page = await browser.newPage();
//await page.setViewport({ width: 1900, height: 900 })
await page.setDefaultNavigationTimeout(0);
await page.setRequestInterception(true);
//, req.resourceType() === 'stylesheet' || req.resourceType() === 'font'
page.on('request', (req) => {
if(req.resourceType() === 'image'){
req.abort();
      }
else {
req.continue();
      }
  }); 

await page.goto('https://www.booking.com/index.html?label=gen173nr-1DCAEoggI46AdIM1gEaIwBiAEBmAENuAEXyAEM2AED6AEBiAIBqAIDuALcuI74BcACAdICJDVmYzZjMGRiLWVmYTMtNDIyZi04NzJkLTFhOTYwMTQ4Mjc0YdgCBOACAQ&sid=57134399afbf1275b5b3a4f5ed4f7f54&lang=en-us&sb_price_type=total&soz=1&lang_click=top;cdl=fr;lang_changed=1');

await page.click('.xp__input-group.xp__search');
await page.keyboard.type('Kuala Lumpur');
await page.click('.xp__dates-inner');
await page.$eval('[data-placeholder="Check-in"]', el => el.innerText=' Sept 10');
await page.$eval('[data-placeholder="Check-out"]', el => el.innerText='Sept 17');

await page.waitFor(4000);
await page.waitForSelector('.sb-searchbox__button ');
await page.click('.sb-searchbox__button ');

await page.waitFor(6000);
await page.waitForSelector('[data-id="class-4"]');
await page.click('[data-id="class-4"]');
await page.waitFor(5000);
await page.click('[data-id="review_score-80"]')
await page.waitFor(5000);

await page.click('[data-category="price"]');
await page.waitFor(5000);

await page.waitForSelector('.bui-price-display__value prco-text-nowrap-helper.prco-inline-block-maker-helper');
const hotels=[];
const prices=await page.$eval('.bui-price-display__value.prco-text-nowrap-helper.prco-inline-block-maker-helper', el => el.innerText);;
const scores=[];

const verified_guests=[];
await page.waitFor(4000);
await browser.close();
console.log(prices) 
})();

Thank you for any recommandations.

**Comment by vsemozhetbyt** [comment]
It seems the inner texts of the elements you set are not sent to the server. Instead, you need to change the values of the form inputs — they are sent to the server. For example, check the `document.querySelectorAll('[name^="checkin_"]')` and `document.querySelectorAll('[name^="checkout_"]')` elements and their values set after the calendar widget manipulation.
