### ISSUE TITLE
"Cannot read property 'getProperty' of undefined"

### ISSUE THREAD

**Issue by DarkDenims** [puppeteer/puppeteer#6173]
Been having this error, trying to scrape a website

(node:12904) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getProperty' of undefined
    at Object.scrapeChannel (C:\Users\XAVIER ROMANO\Desktop\Project\server\scraper.js:12:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\XAVIER ROMANO\Desktop\Project\server\index.js:30:23
(node:12904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

**Comment by christian-bromann** [comment]
@AlphaXexia can you share the code of your scraper?
