### ISSUE TITLE
UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r722234 is guaranteed to work.

### ISSUE THREAD

**Issue by memayank00** [puppeteer/puppeteer#6178]
### Steps to reproduce
Simply run the code after puppeteer installation

**Tell us about your environment:**

* Puppeteer version: 5.0.0
* Platform / OS version: window 10
* Node.js version: 10.15.3

**My running code is:**
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://www.flipkart.com/');
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();

**What is the expected result?**
UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r722234 is guaranteed to work.

**What happens instead?**
it should get the screenshot of expected URl

**Comment by xiaoqiao112** [comment]
Have you solved it?

**Comment by xiaoqiao112** [comment]
> ### Steps to reproduce
> Simply run the code after puppeteer installation
> 
> **Tell us about your environment:**
> 
> * Puppeteer version: 5.0.0
> * Platform / OS version: window 10
> * Node.js version: 10.15.3
> 
> **My running code is:**
> const puppeteer = require('puppeteer');
> (async () => {
> const browser = await puppeteer.launch();
> const page = await browser.newPage();
> await page.goto('https://www.flipkart.com/');
> await page.screenshot({path: 'example.png'});
> 
> await browser.close();
> })();
> 
> **What is the expected result?**
> UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r722234 is guaranteed to work.
> 
> **What happens instead?**
> it should get the screenshot of expected URl

Have you solved it?

**Comment by memayank00** [comment]
@qiaochunmei  yes i have resolved this.

**Comment by xiaoqiao112** [comment]
> @qiaochunmei yes i have resolved this.

How did you solve it? I have this problem, too? Local normal, error reported by centos7

**Comment by rokija** [comment]
@memayank00 @qiaochunmei  how did you solve it? 😄

**Comment by DanHelfman** [comment]
@memayank00 @qiaochunmei What was the resolution?

**Comment by xiaoqiao112** [comment]
> @qiaochunmei yes i have resolved this.

How did you solve it? I have this problem, too? Local normal, error reported by centos7

**Comment by sarcastic-verma** [comment]
dude, you did us all wrong

**Comment by sarcastic-verma** [comment]
> @qiaochunmei yes i have resolved this.

dude, you did us dirty
