### ISSUE TITLE
CDP's Page.getResourceContent API doesn't work as expected when request interception is enabled 

### ISSUE THREAD

**Issue by anywhim** [puppeteer/puppeteer#6182]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.0.0
* Platform / OS version: Linux penguin 5.4.40-04224-g891a6cce2d44 Debian Buster
* URLs (if applicable):
* Node.js version: v14.4.0

**What steps will reproduce the problem?**

```
const puppeteer = require("puppeteer");

(async function getGoogleLogo() {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  page.on("request", (request) => request.continue());
  await page.setRequestInterception(true);
  await page.goto("https://www.google.com");
  const googleLogoURL = await page.$eval("#hplogo", (node) => node.currentSrc);
  console.log(googleLogoURL);
  const CDPsession = await page.target().createCDPSession();
  await CDPsession.send("Page.enable");
  console.log(await CDPsession.send("Page.getResourceTree"));
  const { content: googleLogoIMG } = await CDPsession.send(
    "Page.getResourceContent",
    {
      frameId: page.mainFrame()._id,
      url: googleLogoURL,
    }
  );
  console.log(googleLogoIMG);
  await CDPsession.detach();
  await browser.close();
})();
```

**What is the expected result?**
Promise returned by CDPsession.send("Page.getResourceContent" ...) should settle.

**What happens instead?**
The promise doesn't settle until the page is reloaded. You can reload the page manually or be puppeteer's page.reload() then the promise settles immediately.

**Comment by rootgrandfather** [comment]
how does this problem solved?

**Comment by JJetmar** [comment]
I solved it by upgrading the version of Puppeteer from 10.04 to 20.08
