### ISSUE TITLE
Timeout on headless page loads - proxy-server solution not working 

### ISSUE THREAD

**Issue by devsi** [puppeteer/puppeteer#6185]
* Puppeteer version: 4.0.1
* Node.js version: 12.16.3, tried with 12.18.2 and 12.3.1 also. These were present on our various servers.

**What steps will reproduce the problem?**

```JavaScript
await page.click('#next-complete');
await page.waitForNavigation({
    waitUntil: ['networkidle0', 'load', 'domcontentloaded'],
});
```

```JavaScript
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome-unstable', args: ["--proxy-server='direct://'", '--proxy-bypass-list=*', '--no-sandbox', '--disable-setuid-sandbox'] });
const page = await browser.newPage();
await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36');
await page.setDefaultNavigationTimeout(60000);
```

So using the solution at #1718 has not helped me in this one. In fact I didn't see a decrease in page load times at all after doing this. I'm not sure what other solutions we need here. I also added a user-agent as some people found that helped, and nothing.

I have checked CPU utilization and it's super low so its not a resource issue.

At this point I can't figure out if it's puppeteer or the domain that I'm trying to work with. The domain is fairly slow even through a regular browser, but I've never had +60 second wait times. At most, manually navigating in Chrome directly I get 10 - 15 seconds wait time before the next page is complete.

I have logged the output and I can see the many requests and responses that the page load is doing, so I know it's definitely navigating. If I set an infinite timeout, it does eventually get there. On my local development environment it works but it gets close to the timeout value, and on occasion fails when it goes over.

If someone could help me with this that'd be amazing, I feel I've exhausted all the available options at this point.

**Here is an example of our log file:**

```txt
2020-07-06T23:35:46.209Z Logged in, waiting for navigation...
2020-07-06T23:35:54.636Z Doing some action...
...
2020-07-06T23:35:54.790Z Navigating to new page...
2020-07-06T23:36:02.181Z Searching for info
...
2020-07-06T23:36:02.264Z Confirming form submission...
2020-07-06T23:37:04.578Z (E) TimeoutError: Navigation timeout of 60000 ms exceeded
2020-07-06T23:37:05.098Z ^^ Script execution took 83.278s ^^
```

Previous page navigations have been around 8 - 10 seconds, but this last one on button click, is +60. As previously stated manually doing this through Chrome can take around 10 seconds.

**Comment by Waseemrajashaik** [comment]
+1

**Comment by kirbdee** [comment]
What environment are you experiencing this in by chance? I'm hitting very similar issues. In addition to degrading usage overtime on GCP (Google Cloud)
