### ISSUE TITLE
I have some problems with puppeteer to generate pdf files

### ISSUE THREAD

**Issue by langcastle** [puppeteer/puppeteer#6189]
I use puppeteer to generate pdf files. If you can only use puppeteer-core in the centos environment, the Windows environment reports an error: Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
Hope to reply as soon as possible, thank you.

**Comment by WangNingning1994** [comment]
Hi, same issue here, after many tries I found the solution is quite simple, just add  executablePath config when launch. `const browser = await puppeteer.launch({executablePath: '/usr/bin/google-chrome'});`

**Comment by langcastle** [comment]
> Hi, same issue here, after many tries I found the solution is quite simple, just add executablePath config when launch. `const browser = await puppeteer.launch({executablePath: '/usr/bin/google-chrome'});`

Thank you for the replay, I solved this problem by downloading a new Google installation package and placing it in the corresponding location.
