### ISSUE TITLE
Expose HTTPRequest class in public API

### ISSUE THREAD

**Issue by sgrimm** [puppeteer/puppeteer#6194]
Release 3.2.0 renamed the `Request` class to `HTTPRequest` and the release notes say it's not a breaking change because the class isn't exposed directly.

But it's the documented type of several events: https://github.com/puppeteer/puppeteer/blob/e67a860eb093c46fc33a5d265137f392c767b69d/docs/api.md#class-httprequest

It should be exposed in the public API so application code can use the correct type in event handlers.

**Comment by jackfranklin** [comment]
We don't yet expose the types for anything on purpose - we're working on shipping types very soon: #6124 . We're also working on new docs (#6118) - a combination of those will help with regards to types.
