### ISSUE TITLE
waitForFunction has no DOM references for: document, window

### ISSUE THREAD

**Issue by crh3675** [puppeteer/puppeteer#6196]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.2, also tested with 1.7 and 5.0.0
* Platform / OS version: OSX Mojave 10.14.6 (18G5033)
* URLs (if applicable):
* Node.js version: Tested with 8.9.0, 12.14.1, 14.5.0

**What steps will reproduce the problem?**
Assuming you have a frontend JS file running in a localhost application that loads JS inline:

```javascript
window.screenCaptureReady = false;

(function() {
   // some lengthy Ajax loading stuff here and then...
   window.screenCaptureReady = true;
}();
```

Then you have a NodeJS process that loads the page for the screenshot:

```javascript
const browser = await puppeteer.launch({
  headless: true,
  defaultViewport: {
    width: pageWidth,
    height: pageHeight,
    isLandscape: true
  },
  args: ['--no-sandbox', '--disable-web-security',
            '--hide-scrollbars', '--disable-setuid-sandbox']
});

const page = await browser.newPage();
await page.goto(filePath, {waitUntil: 'networkidle0', timeout: 60000});

const waitForFunction = 'window.screenCaptureReady';
await page.waitForFunction(waitForFunction);

const buffer = await page.screenshot({
  encoding: 'binary',
  type: 'png',
  fullPage: true
});

await page.close();
await browser.close();
// do something with buffer
```
Expected result is that `screenCaptureReady` becomes `true` and the screenshot renders.  However, the `waitForFunction` reaches a timeout and the screenshot never generates.  Upon inspection with some logging using:
```javascript
page.on('console', message => console.log(message.text());
```
Both `window` and `document` are  undefined within the `waitForFunction` context.  My workaround was to use a 

```javascript
await page.evaluate(() => {
  const captureCheck = function() {
    if (!screenCaptureReady) {
      setTimeout(captureCheck, 100);
    }
  }
})
````

Am I doing something wrong?

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with this simplified code. Can you?

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    await page.evaluate(() => {
      window.screenCaptureReady = false;
      setTimeout(() => { window.screenCaptureReady = true; }, 5000);
    });

    console.log(`window.screenCaptureReady is ${
      await page.evaluate(() => window.screenCaptureReady)
    }. Waiting...`);

    await page.waitForFunction('window.screenCaptureReady');

    console.log(`window.screenCaptureReady is ${
      await page.evaluate(() => window.screenCaptureReady)
    }.`);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

Output:

```
window.screenCaptureReady is false. Waiting...
window.screenCaptureReady is true.
```

Can there be any error in "some loading stuff here and then" preventing the execution of ` window.screenCaptureReady = true;`?

**Comment by vsemozhetbyt** [comment]
Also, can it be that this code (`window.screenCaptureReady = true;`) is executed in an iframe or a worker?

**Comment by crh3675** [comment]
Your code works for me fine. 

So I think I just uncovered a posible issue.  There is another `page.evaluate()` to call initialization code which runs before-hand that runs the long-running Ajax processes to change the status of `window.screenCaptureReady`.  I would assume that the `window` scope is somehow different.

Example:

```javascript
await page.evaluate(() => {
   setTimeout(() => {
     window.screenCaptureReady = true;
   }, 3000);
});
```

Key is, that the main `window.screenCaptureReady` is within an external JS file that is loaded in the page. EDIT: Still not sure that is the issue here...

**Comment by crh3675** [comment]
I am going to break it down to what I am precisely doing to see if I can replicate:

simple.html
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="simple.js"></script>
  </head>
  <body>
  </body>
</html>
```

```javascript
window.screenCaptureReady = false;
const App = {};

(function() {
  App.init = function(params) {
    setTimeout(() => {
      window.screenCaptureReady= true;
    }, 3000);
  };
})();
```

screenshot.js
```javascript
await page.goto('file:///simple.html, {waitUntil: 'networkidle0', timeout: 60000})
await page.evaluate((params) => {
  App.init(params);
}, params);

await page.waitForFunction('window.screenCaptureReady');
await page.close();
```

This all seems to work.  The real code has a lot more going on, probably some error but then why would `page.evaluate` work ok but not `waitForFunction`?

**Comment by crh3675** [comment]
It seems the timeout is related to the frontend code not resolving the Ajax requests in the Promises.  You can close this issue.
