### ISSUE TITLE
[Introduction] Smart Monkey - free recorder for puppeteer

### ISSUE THREAD

**Issue by nglthach** [puppeteer/puppeteer#6198]
Hi,

This is not an issue but I think it is worth to intro this tool here. If not, please close the issue.

I have added a functionality to Smart Money for exporting a project to Puppeteer code. Here is the video for demo: https://www.youtube.com/watch?v=eBzK85MOo-A

In the most of cases, you don't need to write any line of code for creating a test suite.

If you have any question, please comment!

Sincerely,
Thach

**Comment by hashseed** [comment]
This is pretty cool indeed! I'll play around with this a bit once I have some free time :)
