### ISSUE TITLE
devicePixelRatio works for screenshots, but not (entirely) for PDFs

### ISSUE THREAD

**Issue by davidmathlogic** [puppeteer/puppeteer#620]
My device has a retina display. 

page.screenshot produces the expected behavior: screenshots with devicePixelRatio = 1 have blurred images, while screenshots with devicePixelRatio = 2 have crisp images. 

However, page.pdf does not produce the expected behavior. Regardless of the devicePixelRatio set using page.setViewPort, images in the generated pdf file are pixellated -- not blurred, as in screenshots with the wrong devicePixelRatio, but grainy. Images with border-radius: 50% have jagged, grainy edges. 

I have attached two images below, demonstrating the issue. The first is from the generated pdf, the second from the generated png. 

![badcat](https://user-images.githubusercontent.com/18088182/29885220-10dc027a-8d84-11e7-946e-f0eb5bfffc26.png)
![goodcat](https://user-images.githubusercontent.com/18088182/29885219-10d8d80c-8d84-11e7-8b2f-0fcab7ba007c.png)

(Note: the screenshots having different zoom levels is not the issue. The difference in the images is apparent at any zoom, and the image I used had a resolution about 20 times greater than needed.) This issue occurs regardless of image used and regardless of the dimensions of the pdf. Maybe since page.pdf overrides the viewport options with its own width and height, it also removes the specified devicePixelRatio?

**Comment by JensVanhooydonck** [comment]
The problem for me was the grayscale filter. 
It seems that Chrome can't print the image at high quality when the following filter is applied:
`filter: grayscale(100%);`

**Comment by Nixes** [comment]
I can also reproduce this issue.

**Comment by rasmus93** [comment]
I also have such issue.
@JensVanhooydonck @Nixes do you have workaround to generate pdf file in grayscale properly?

**Comment by JensVanhooydonck** [comment]
> I also have such issue.
> @JensVanhooydonck @Nixes do you have workaround to generate pdf file in grayscale properly?

I didn't find any fix for this. I removed the grayscale filter, and added a function to convert images to grayscale on the backend when needed.

**Comment by SilverGaucho** [comment]
hey guys!

has someone ended up with a solution on this? I have the same issue, even with any CSS filter over the source
