### ISSUE TITLE
Microsoft Edge (Chromium) browser is not working in non-headless mode. It works in headless mode.

### ISSUE THREAD

**Issue by sriharsha-git** [puppeteer/puppeteer#6204]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.0.0
* Platform / OS version: Windows 10 Pro / 10.0. 19041
* URLs (if applicable):
* Node.js version: 12.18.0

**What steps will reproduce the problem?**
Below code is a simple test of Mocha for launching Microsoft Edge (Chromium). 
Reference URL https://docs.microsoft.com/en-us/microsoft-edge/puppeteer
Run the code from the command line. 

_Please include code that reproduces the issue._

const puppeteer = require("puppeteer");
const edgePaths = require("edge-paths");
const EDGE_PATH = edgePaths.getEdgePath();

describe("Execute Tests in Edge Browser", () => {
  it("Should launch Edge Browser", async () => {
    const browser = await puppeteer.launch({
      executablePath: EDGE_PATH,
      headless: true,
    });
    const page = await browser.newPage();
    await page.goto("https://www.google.com");
    await page.screenshot({ path: "example.png", fullPage: true });
    await browser.close();
  });
});

**What is the expected result?**
Test should execute without any errors.

**What happens instead?**
It throws error , Below is the console log.

Execute Tests in Edge Browser
    1) Should launch Edge Browser

  0 passing (30s)
  1 failing

  1) Execute Tests in Edge Browser
       Should launch Edge Browser:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Puppeteer-Udemy\tests\EdgeTest.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

[Error: EPERM: operation not permitted, unlink 'C:\Users\Nirbhay\AppData\Local\Temp\puppeteer_dev_chrome_profile-KTWrFj\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\Nirbhay\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-KTWrFj\\CrashpadMetrics-active.pma'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer-udemy@1.0.0 test: `node ./node_modules/mocha/bin/mocha --timeout=30000 ./tests/EdgeTest.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer-udemy@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nirbhay\AppData\Roaming\npm-cache\_logs\2020-07-10T16_13_06_471Z-debug.log

**Comment by rituraj-svmx-zz** [comment]
Hi @sriharsha-git , I'm also getting the same issue. Any help will be highly appreciated.
