### ISSUE TITLE
Different rendering of absolutely the same text

### ISSUE THREAD

**Issue by timocov** [puppeteer/puppeteer#6205]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.0.0
* Platform / OS version: I tried with [this docker image](https://hub.docker.com/layers/circleci/node/12-browsers/images/sha256-5391946853a85b8b59c104dfdaabac395913b3a33223cd4f01b88e75c7d6414f?context=explore), I guess it's Debian 9
* URLs (if applicable): NA
* Node.js version: 12.18.2

**What steps will reproduce the problem?**

I'm not sure whether this problem related to the puppeteer itself, but maybe I've missed something in the configuration. We have a test, which opens 2 pages, do something on that pages and takes screenshots, then compare them (screenshots tests).

Currently we got a strange result - there is very small difference between rendering the same text with the same font at the same coordinate, which cause test to fail.

Below you can see results for the same page opened twice:

|1st run|2nd run|Diff|
|---|---|---|
|![image](https://user-images.githubusercontent.com/3112183/87191572-5eba3f00-c2fd-11ea-9807-c79c309b3d9f.png)|![image](https://user-images.githubusercontent.com/3112183/87191589-6aa60100-c2fd-11ea-8b9f-1b66d9255c9d.png)|![image](https://user-images.githubusercontent.com/3112183/87191608-71347880-c2fd-11ea-8590-14309b6498da.png)|

_[Here](https://user-images.githubusercontent.com/3112183/87192091-6201fa80-c2fe-11ea-8292-40cfce6acda8.gif) you can see the gif with the difference_

Such kind of difference makes impossible to write screenshot-based tests with puppeteer. It's really floating issue with high rate of reproduction.

Quite possible I missed something and there is something I can configure to avoid this, but I didn't find it in the docs.

It's strange also because we already have similar tests in https://github.com/tradingview/lightweight-charts, and they works fine.

The issue looks related to https://github.com/puppeteer/puppeteer/issues/2410, but we don't compare headless and headful modes - it's all headless.

If you need any additional information, please tell me. It's a bit hard to prepare a repro for this (because it's non-public code atm and it takes some time to make it available without our internal stuff), but if it's important, I can do it.

**Comment by pladaria** [comment]
We also got issues when upgrading puppeteer to latest version (which uses chromium 87). Our screenshot tests failed due to different text rendering in local machine, github actions or inside a docker containers... 
We are using `--font-render-hinting=none` in all environments.

I spent an afternoon trying to workaround this and I finally gave up and reverted to Puppeteer v3.3.0 (chromium 83)
