### ISSUE TITLE
How can i load js code exactly before other js execute?

### ISSUE THREAD

**Issue by antstudio-git** [puppeteer/puppeteer#6211]
Here the case:

js with window objA

inject window objA

call objA.call method

----
how can i control the inject as sync mode

**Comment by vsemozhetbyt** [comment]
Maybe [`page.evaluateOnNewDocument()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevaluateonnewdocumentpagefunction-args) can help?
