### ISSUE TITLE
Error message: Protocol error (Target.setDiscoverTargets): Target closed

### ISSUE THREAD

**Issue by langcastle** [puppeteer/puppeteer#6216]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: npm dawnload
* Platform / OS version: centos7
* URLs (if applicable):
* Node.js version: v12.14.0

**What steps will reproduce the problem?**

 const browser = await puppeteer.launch({
            args: ['--disable-dev-shm-usage', '--no-sandbox']
        });
        const page = await browser.newPage();
        await page.setContent(html).catch(err => {
            console.log(err.message);
        });

**What is the expected result?**
Error message: Protocol error (Target.setDiscoverTargets): Target closed

**What happens instead?**
It is normal for me to use puppeteer to transfer html pages to pdf documents in centos7, but the following error appears after mapping the service to docker. I don’t know what caused it. Please answer it. Thank you very much.
Error message: Protocol error (Target.setDiscoverTargets): Target closed

**Comment by langcastle** [comment]
Why no one answers？？

**Comment by a-y-u-s-h** [comment]
I'm getting the same problem. Only thing common between our code is the argument '--disable-dev-shm-usage'. I'm running it on a DigitalOcean droplet.

**Comment by truesolarflame** [comment]
I am getting the same problem with nwjs on MacOs using puppeteer-core. I too am trying to use it to create PDFs. It worked with previous versions of nwjs and puppeteer. Unfortunately they don't work on the latest version of MacOS (Big Sur). For me, puppeteer only throws this error when trying to launch nwjs. Using the Chrome app or puppeteer's own chrome download seems to work fine, but that significantly bloats my app installs.

**Comment by Kocal** [comment]
I have the same issue but on AWS Lambda (runtime: `provided.al2`) with Serverless.

I'm using:
- puppeteer ~5.5.0
- chrome-aws-lambda ~5.5.0
- chrome args `--disable-dev-profile --user-data-dir=/dev/null` (+ all args defined here https://github.com/alixaxel/chrome-aws-lambda/blob/1395ee60ad1625d08306a4aad8b7b851b73a9a83/source/index.js#L84-L122)
- `pipe: true` 

**EDIT:** Well, I was able to fix my issue by switching to the runtime `provided`. I'm not a big fan but it's working. :man_shrugging:

**Comment by IgorKurkov** [comment]
check this comment please to fix this issue - https://github.com/puppeteer/puppeteer/issues/6258#issuecomment-799677511

**Comment by Ysiakowy** [comment]
"Solution for common dependences issues" should answer your problems

https://gist.github.com/winuxue/cfef08e2f5fe9dfc16a1d67a4ad38a01

**Comment by OrKoN** [comment]
Please make sure you have required dependencies for the Chromium binary in your environment (see troubleshooting.md or our Dockerfile).
