### ISSUE TITLE
Redirect is returning 200 instead of 302

### ISSUE THREAD

**Issue by alejandrofcarrera** [puppeteer/puppeteer#6219]
**Tell us about your environment:**

* Puppeteer version: 5.1.0
* Platform / OS version: 
  * Linux 4.19.76 (Debian 9) 
  * Docker Image ~ node:slim
* URLs (if applicable): https://go.topfxpro.com/visit/?bta=36097&nci=12872&campaign=&afp=
* Node.js version: latest

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({
    executablePath: 'google-chrome-unstable'
});
const page = await browser.newPage();
await page.setRequestInterception(true);
await page.setUserAgent('Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) ' +
    'AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 ' +
    'Mobile/15E148 Safari/604.1')
await page.setDefaultNavigationTimeout(120000);
await page.setViewport({
    width: 375, height: 1218, deviceScaleFactor: 3,
    isMobile: true, hasTouch: true, isLandscape: false
});
await page.setExtraHTTPHeaders({'Accept-Language': 'en'});
page.on('response', res => {
    if ([301, 302, 304].indexOf(res.status()) >= 0) console.log('<Response>', res.status(), res.url());
});
page.on('error', err => {
    console.log("[Page Error] ", err.message);
});
page.on('request', req => {
    if (req.resourceType() === 'document') console.log("Intercept " + req.resourceType() + " " + req.url());
    req.continue();
});
const result = await page.goto('https://go.topfxpro.com/visit/?bta=36097&nci=12872&campaign=&afp=');
await page.screenshot({path: 'screenshot.png'});
await browser.close();
```

**What is the expected result?**

The console log on the 'response' event must be shown on the output log. If you try this code (less the first line for the launch of the puppeteer with specific binary path of chrome) on https://try-puppeteer.appspot.com it is working well.

**What happens instead?**

The console log on the 'response' event is not showed and the screenshot is not well generated because the result is a blank empty page.

**Personal Notes**

The project is about generating a bunch of screenshots for URLs in order to do a healtcheck for the frontend side of some partners. I had using the same code with [puppeteer-cluster](https://github.com/thomasdondorf/puppeteer-cluster#usage) but the result was the same, some URLs are pretty fine, a lot of others are responding 200 with blank screenshot instead of 302 and the good screenshot for redirection. The code has been changed and aligned with https://try-puppeteer.appspot.com because this website is working and also i used the same Dockerfile, assets and scripts from the [github](https://try-puppeteer.appspot.com) but it is the same result on my local.

I want to deploy the Docker container on a cloud environment in order to link this micro-service with a lot of others to analyze the images, do stuff about it, upload them to S3.... a lot of things, so this is a crucial part of the BPM process.

I tried:
- puppeteer-cluster in order to speed up the crawling
- puppeteer-core to check if there is an issue with puppeteer package
- chrome-stable & chrome-unstable packages
- sandbox and not-sandbox mode
- headless and not-headless

**Comment by alejandrofcarrera** [comment]
Related with:

- https://github.com/puppeteer/puppeteer/issues/5672
- https://github.com/puppeteer/puppeteer/issues/5309
- https://github.com/puppeteer/puppeteer/issues/4383

**Comment by alejandrofcarrera** [comment]
No changes with the version 5.2.1

**Comment by hungnv-sr** [comment]
Still no changes. I encountered this on every environments, the status is always 200 instead of either 301 or 302

**Comment by alejandrofcarrera** [comment]
Any updates ?¿
