### ISSUE TITLE
Firefox installation instructions are not clear

### ISSUE THREAD

**Issue by LarsDenBakker** [puppeteer/puppeteer#6224]
https://github.com/puppeteer/puppeteer#default-runtime-settings explains how to use firefox and points to https://github.com/puppeteer/puppeteer/blob/v5.1.0/docs/api.md#puppeteerlaunchoptions for more information.

However neither mention the requirement to set an environment variable during installation. This is explained here in the FAQ: https://github.com/puppeteer/puppeteer#q-which-firefox-version-does-puppeteer-use

I think this is confusing to people, at least it was to me. A single section explaining how to use firefox with puppeteer would be great.

**Comment by christian-bromann** [comment]
@LarsDenBakker I created a PR trying to address your concerns. Can you review it to see if that would have improved your experience?

**Comment by LarsDenBakker** [comment]
Yeah, that looks good to me 👍

**Comment by jackfranklin** [comment]
Thanks @christian-bromann ! I'll close this and it'll be out in the next patch release of Puppeteer (which should be in the next few days).

**Comment by mathias22osterhagen22** [comment]
Can you please add that for a Windows install it needs to be  (PowerShell): 

```js
$env:PUPPETEER_PRODUCT = 'firefox'
npm i puppeteer
```
and to succeed to run it need an arg "-wait-for-borwser":
```js
const browser = await puppeteer.launch({ product:'firefox',  headless: false, args: ['-wait-for-browser']});
```

Thank you.
