### ISSUE TITLE
Seeing "Error: not opened at WebSocket.send" during simple usage

### ISSUE THREAD

**Issue by tannerlinsley** [puppeteer/puppeteer#623]
We have deployed a very simple instance of Puppeteer to the cloud using docker.  Everything works perfectly in the beginning:
- Chromium is built correctly
- Chromium is launched with no errors
- Requests to puppeteer are issued to:
  - Open a new page
  - Evaluates a very simple script (to scrape some text)
  - Then closes the page

I am able to get a few successful requests out of puppeteer, but after a bit, I see the following error
```
ERROR: Error: not opened at WebSocket.send (/usr/src/app/node_modules/ws/lib/WebSocket.js:355:18) at Connection.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:72:14) at Browser.newPage (/usr/src/app/node_modules/puppeteer/lib/Browser.js:44:47) at _callee$ (/usr/src/app/lib/utils/chrome.js:53:22) at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:65:40) at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:303:22) at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:117:21) at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30) at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13 at <anonymous>
```
and the chromium/puppeteer *appears* to crash (meaning I continually receive the same error when attempting to create a new page on a new request)

Any ideas here?

**Comment by tannerlinsley** [comment]
@derekperkins, you might be interested in this as well.

**Comment by aslushnikov** [comment]
@tannerlinsley any way we can repro this?

Also, it looks like you're using node6. Out of curiosity, does the same happen with node 8?

**Comment by derekperkins** [comment]
Here's the Dockerfile that we're using

```
FROM node:8-slim

# Install chromium dependencies
RUN apt-get update
RUN apt-get install -yq libx11-xcb1 libpangocairo-1.0-0 libxcomposite1 libxcursor1 \
 gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
 libpango-1.0-0 libstdc++6 libx11-6 libxcb1 \
 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
RUN apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

ENV NODE_PATH="/usr/local/share/.config/yarn/global/node_modules:${NODE_PATH}"

# includes puppeteer
RUN yarn
RUN yarn build
CMD yarn start
```

Puppeteer dependency in `yarn.lock`
```
puppeteer@^0.10.0:
  version "0.10.0"
  resolved "https://registry.yarnpkg.com/puppeteer/-/puppeteer-0.10.0.tgz#f0a95de4b2660608fa9dbc54f525d013ef6262e7"
  dependencies:
    debug "^2.6.8"
    extract-zip "^1.6.5"
    https-proxy-agent "^2.1.0"
    mime "^1.3.4"
    progress "^2.0.0"
    proxy-from-env "^1.0.0"
    rimraf "^2.6.1"
    ws "^3.0.0"
```

**Comment by derekperkins** [comment]
We've been able to reproduce the same results locally (2015 15" MBP w/ 16 GB RAM) and running on Google Compute Engine (1 core / 3.75 GB RAM). On the MBP, it died at about 20 req/sec, but on the cloud, it died around 3 req/sec.

**Comment by derekperkins** [comment]
Also, @tannerlinsley is seeing the same results locally outside of Docker, just running Node and Chrome natively on his MBP.

**Comment by tannerlinsley** [comment]
I've done some more testing in my docker container.

The node version it is currently running is `v8.4.0`
It's using an extremely simple express server to execute the following puppeteer flow on each request:
```javascript
let puppet = puppeteer.launch({
	args: ['--no-sandbox']
})

app.post('/', async (req, res, next) => {
	try {
		const browser = await puppet
		const page = await browser.newPage()
		await page.goto('http://google.com')
                await page.injectFile(path.resolve(__dirname, '../static/jquery.min.js'))
		await page.close()
	} catch (err) {
		next(err)
	}
})
```

My performance findings went like this:
- Only opening and closing a page got up to 50 req/sec (hit linux open files before puppeteer crashed, so really good)
- Only opening and navigating to google, then closing the page got up to about 20 req/sec before the 30 second navigation timeout starting kicking in
- As soon as we started injecting jQuery, the max req/sec only got up to about 10, at which point we experience the original error above.  

Not sure why this would be happening only when we choose to use `injectFile`, but that appears so far to be the case.

**Comment by derekperkins** [comment]
@aslushnikov Is there anything else you can think of that we might try, or is this something wrong with `injectFile`?

**Comment by aslushnikov** [comment]
@derekperkins how big is a file you inject?

**Comment by tannerlinsley** [comment]
Its the latest minified jQuery

**Comment by 3fuyu** [comment]
The same problem happened on me.  I use Node6 also. But because of business need. I can't update node8. Is there any other way? @aslushnikov

**Comment by 3fuyu** [comment]
@tannerlinsley  Did you fix it?

**Comment by tannerlinsley** [comment]
Nope. Still a problem even in node 8

**Comment by derekperkins** [comment]
To be clear, @tannerlinsley and I haven't ever used node 6 with puppeteer, only node 8

**Comment by nazieb** [comment]
I also got this error when injecting Puppeteer with jQuery and Mozilla [Readability](https://github.com/mozilla/readability).

In our case we even don't navigate to a URL. I just set the HTML using `setContent` with string we got from cache.

```javascript
await page.setContent(html);
```

**Comment by liutian** [comment]
The same problem happened on me. I use Node8.4.0 centos 7  
Linux centos 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

> await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
Error: not opened
      at WebSocket.send (/home/visionet/spa-seo/node_modules/ws/lib/WebSocket.js:355:18)
      at Connection.send (/home/visionet/spa-seo/node_modules/puppeteer/lib/Connection.js:72:14)
      at Browser.newPage (/home/visionet/spa-seo/node_modules/puppeteer/lib/Browser.js:44:47)
      at app.use (/home/visionet/spa-seo/index.js:20:30)
      at dispatch (/home/visionet/spa-seo/node_modules/koa-compose/index.js:42:32)
      at /home/visionet/spa-seo/node_modules/koa-compose/index.js:34:12
      at Server.handleRequest (/home/visionet/spa-seo/node_modules/koa/lib/application.js:136:14)
      at emitTwo (events.js:125:13)
      at Server.emit (events.js:213:7)
      at parserOnIncoming (_http_server.js:602:12)

**Comment by phawxby** [comment]
I'm getting the same on windows also using file injection. The first few passes work then I get.

```shell
    Message:
        not opened

        at WebSocket.send (C:\Users\Z269CJBB\Documents\GitHub\gulp-puppeteer-accessibility-audit\node_modules\ws\lib\WebSocket.js:355:18)
        at Connection.send (C:\Users\Z269CJBB\Documents\GitHub\gulp-puppeteer-accessibility-audit\node_modules\puppeteer\lib\Connection.js:72:14)
        at Browser.newPage (C:\Users\Z269CJBB\Documents\GitHub\gulp-puppeteer-accessibility-audit\node_modules\puppeteer\lib\Browser.js:46:47)
        at PuppeteerAccessibilityAudit.audit (C:\Users\Z269CJBB\Documents\GitHub\gulp-puppeteer-accessibility-audit\node_modules\puppeteer-accessibility-audit\index.js:44:33)
        at DestroyableTransform.through.obj [as _transform] (C:\Users\Z269CJBB\Documents\GitHub\gulp-puppeteer-accessibility-audit\index.js:27:33)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

Line 44 of puppeteer-accessibility-audit is.
```javascript
    let page = await this.browser.newPage();
```

**Comment by phawxby** [comment]
Running `yarn run test` for this project displays the error if you need a quick way to reproduce it
https://github.com/xeroxinteractive/gulp-puppeteer-accessibility-audit/tree/6703df8fba251857f7d1d51f6d75c69fedc4b9a1

**Comment by tpetry** [comment]
Having the same problem: Some of our docker puppeteer instances never had any problem and some are producing the error after some days.

**Comment by tannerlinsley** [comment]
@aslushnikov Any news on this bug? This is a huge blocker for us, and many others it seems :(

**Comment by derekperkins** [comment]
@aslushnikov Do you know if this is a puppeteer memory leak or an actual headless Chrome leak?

**Comment by wong2** [comment]
same here

**Comment by aslushnikov** [comment]
I can't reproduce this on 0.13.0-alpha, neither with jquery nor with the gulp-puppeteer-accessibility-audit.

If anyone has a script that reliably reproduces the issue, please share it - it would help a lot.

**Comment by 3fuyu** [comment]
@aslushnikov When will 0.13.0-alpha be released?

**Comment by GautierT** [comment]
@aslushnikov : Still have this problem on 0.13.0-alpha.
#1211

**Comment by smelukov** [comment]
The same problem

**Comment by panzerdp** [comment]
Unfortunately I have the same problem, which makes puppeteer hard to use.

Initially it works fine, but later the script starts throwing:  
```
Error: not opened 
at WebSocket.send (/app/node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:344:18) 
at Connection.send (/app/node_modules/puppeteer/lib/Connection.js:72:14) 
at Browser.newPage (/app/node_modules/puppeteer/lib/Browser.js:98:47)...
```
Puppeteer version `0.13.0`, node version `8.3`.

It would be really great to have this solved, or at least to apply a workaround. 

Thanks.

**Comment by lenaten** [comment]
I "solved" it by launch and close browser for every request.

**Comment by Vandivier** [comment]
This happened to me because I had a bug in my evaluationContext.evaluate(). I bypassed my function as a debugging trick and the issue went away:

```
async function fpScrapeInputRecord(sUrl) {
    const _page = await browser.newPage();
    let executionContext;
    let _$;
    let pageWorkingCompetitionPage;
    let poScrapeResult;

    await _page.goto(sUrl, {
        'timeout': 0
    }); // timeout ref: https://github.com/GoogleChrome/puppeteer/issues/782

    _$ = cheerio.load(await _page.content());
    _page.on('console', _fCleanLog); // ref: https://stackoverflow.com/a/47460782/3931488

    executionContext = _page.mainFrame().executionContext();
    /*
    poScrapeResult = await executionContext.evaluate((_iCurrentInputRecord) => {
        return _fpWait(900)
            .then(function () {
                let _sEmail = $('.emaillabel').parent().find('td span').text();
                let _arroAffiliations = [];

                return {
                    'sEmail': _sEmail,
                    'arroAffiliations': _arroAffiliations
                };
            })
            .catch(function (err) {
                console.log('fpScrapeInputRecord err: ', err);
            });

        // larger time allows for slow site response
        // some times of day when it's responding fast u can get away
        // with smaller ms; suggested default of 12.5s
        function _fpWait(ms) {
            ms = ms || 10000;
            return new Promise(resolve => setTimeout(resolve, ms));
        }
    });
    */

    _page.close();

    return Promise.resolve({
        'sEmail': '_sEmail',
        'arroAffiliations': '_arroAffiliations'
    });

    return poScrapeResult;

    function _fCleanLog(ConsoleMessage) {
        console.log(ConsoleMessage.text + EOL);
    }
}
```

**Comment by fengliner** [comment]
same problem when running in docker， but is fine running Node and Chrome natively

**Comment by panzerdp** [comment]
Most likely this issue is related with the small `/dev/shm` size (which defaults to 64MB in docker). Details here: https://github.com/c0b/chrome-in-docker/issues/1

**Comment by aslushnikov** [comment]
Some of the reports in the thread might be related to small `/dev/shm` size, please try running pptr with `--disable-dev-shm-usage` flag:

```js
const browser = await puppeteer.launch({
  args: ['--disable-dev-shm-usage']
});
```

Others might be related to the websocket keepalive bug: #1774.

Can someone please check and see if pptr v1.0.0 still fails for you in docker with `--disable-dev-shm-usage` flag?

**Comment by CommanderXL** [comment]
@aslushnikov Well, I add the arg: `--disable-dev-shm-usage`. It make it.

centos 7.6 docker
puppeteer 1.0.0

**Comment by tpetry** [comment]
`--disable-dev-shm-usage` solved the problem for our docker containers too 👍

Is there some documentation for the implication of this flag? Any drawbacks?

Edit: According to [Chromium bug #736452](https://bugs.chromium.org/p/chromium/issues/detail?id=736452) `/tmp` will be used instead of `/dev/shm` shared memory. So a small performance penalty has to be expected whenever `/tmp` would do reall file io to a hdd/ssd.

**Comment by CommanderXL** [comment]
@tpetry Thanks for you answer. But I didn't found the arg (`--disable-dev-shm-usage`) in the [chromium-cmd-line-doc](https://peter.sh/experiments/chromium-command-line-switches/)

**Comment by paambaati** [comment]
Tagging @beverloo ^

**Comment by aslushnikov** [comment]
> Is there some documentation for the implication of this flag? Any drawbacks?

@tpetry there's a note in [`troubleshooting.md`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#tips). 

Looks like this is fixed then.

**Comment by ruchit47** [comment]
I had the same error, I tried all of the above things but didn't work for me. 

**Solved it by deleting all files in the chrome data folder.**

I am storing the chrome data to the particular directory by specifying the directory  with   '--user-data-dir=data' 

Looked like the data folder had tones of files and puppeteer was enable to read it.
