### ISSUE TITLE
Travis CI install on latest version

### ISSUE THREAD

**Issue by benitogf** [puppeteer/puppeteer#6237]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 4.0.0
* Platform / OS version: ubuntu xenial (travis ci)
* URLs (if applicable): https://travis-ci.com/github/benitogf/katamari-client/builds/176006756
* Node.js version: 12

**What steps will reproduce the problem?**

the install script fails for any version above 2.1.1

_Please include code that reproduces the issue._

the travis configuration:

```
language: go

os:
  - linux

go:
  - 1.14.x

addons:
  chrome: stable

services:
  - xvfb

install:
  - npm install

script:
  - npm test
```

Using either 4.0.0 or 3.2.0 the error is the same, downgrading to 2.1.1 pass the installation but fails to run

**What is the expected result?**

Would be nice to have an example on how to use on travis ci with the lastest version

**What happens instead?**

Couldn't find a workaround or some example

**Comment by theDavidBarton** [comment]
Does _Running Puppeteer on Travis CI_ in the [Troubleshooting](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-travis-ci) document help? Anyway the provided link to the example `.travis.yml` is broken at the moment, if #6826 will be approved it will lead to the latest working Travis example, which is availble here: https://github.com/puppeteer/puppeteer/blob/v5.5.0/.travis.yml. May be useful for you.

**Comment by benitogf** [comment]
Sorry not sure why the link is broken, maybe it requires login, here's the output when using 3.3.0
![image](https://user-images.githubusercontent.com/1633813/107200589-dd619100-6a32-11eb-9812-a6c8ff2d1f6a.png)

Will try it again with 5.5.0 and see how it goes, thanks!

**Comment by mathiasbynens** [comment]
@benitogf You're using an outdated Node.js version.
