### ISSUE TITLE
Missing documentation about Gamepad API

### ISSUE THREAD

**Issue by FezVrasta** [puppeteer/puppeteer#6239]
This is not a bug report, but a documentation issue, I can't find any information about the [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API), where can I find information to know how to simulate a gamepad and trigger key presses with it?

**Comment by FezVrasta** [comment]
Not stale

**Comment by OrKoN** [comment]
I don't think we support that and currently it's not a priority for us, unfortunately.

**Comment by FezVrasta** [comment]
Thanks for the timely response 🙇‍♂️
