### ISSUE TITLE
Unneeded async/await usage throughout the library

### ISSUE THREAD

**Issue by devsnek** [puppeteer/puppeteer#624]
Functions like this create an unnecessary promise with the async/await which could have unknown performance implications depending on the js engine that the user's build of node is using.
![](https://gc.gy/.png)
![](https://gc.gy/蓼⛂.png)

**Comment by aslushnikov** [comment]
@devsnek unless there are real performance issues that might relate to this, we accept this in favor of code readability. Modern V8 versions make promise creation ridiculously fast, so the overhead is negligible.

**Comment by devsnek** [comment]
if you're going to pull up readability, then i must ask how
```js
async x() {
  return await y();
}
```
is more readable than
```js
x() {
  return y();
}
```

**Comment by ebidel** [comment]
It's true that we could remove some of the await/async, but the perf difference is negligible with any combination: http://jsbin.com/fovikazeli/edit?html,console

IMO, for readability, seeing `async` prefix a function is a clear signal that the func returns a promise. It's hard to know what this returns:

```
x() {
  return y();
}
```

**Comment by devsnek** [comment]
isn't that why you have docblocks over all your code?
```js
/**
 * @return {!Promise<String>}
 */
``` 
seems fairly clear

**Comment by bdistin** [comment]
Your test is flawed btw. Promises get thrown off the stack into the event queue, and loop back in when the stack is empty. In your test you start a timer for all three, then start resolving them one at a time, meaning the second resolved is effectively the sum of the first and second test being resolved, and the 3rd is effectively the sum of all 3 tests being resolved.

See this for a fair test: http://jsbin.com/wixohiwacu/edit?html,console

Edit: Added proof for my claims:
Original Test with added console.logs: http://jsbin.com/fuyikilelo/edit?html,console
New Fair test with added console.logs: http://jsbin.com/zihokalefe/edit?html,console

Edit2: For giggles, run the test a million times back to back to see which is really the most performant:
http://jsbin.com/qidiqilako/edit?html,console

**Comment by ebidel** [comment]
@bdistin good catch! Your example is a nicer too. What I notice is that these are essentially equivalent when run in isolation, and fast:

```js
function test2(tic) {
  return Promise.resolve(tic);
}

async function test3(tic) {
  return await Promise.resolve(tic);
}
```

Yea? While `async` by itself is much slower:

```js
async function test(tic) {
  return Promise.resolve(tic);
}
```

Puppeteer mostly uses test3's pattern. v8 must be doing some smarts for `test3()`, essentially making its async/await a noop.

But when I run your 1M times demo, `test2` is fastest.

**Comment by bdistin** [comment]
That is what I originally thought from the first test rewrite. However in the Edit2 rewrite running each test a million times I get results like (using chrome 60, so with the V8 optimizations):
```
"test: 2855.0000000000005 ms"
"test2: 2330.0049999999997 ms"
"test3: 3247.994999999999 ms"
```

**Comment by ebidel** [comment]
Right. v8 optimizations make everything harder to reason about with "tests" like this. It's probably the case that typical user code is never going to be calling the puppeteer API a million times :)

But now I'm curious....Check out what happens when you add a preliminary `await` to the top. That appears to kick v8 and normalize all of them:

```
"test: 0.010000000000001563 ms"
"test2: 0.010000000000001563 ms"
"test3: 0.020000000000003126 ms"
```

One run: http://jsbin.com/baronelego/edit?html,console

Guess we need some real code to test against :)
