### ISSUE TITLE
Strange char in remote debugging

### ISSUE THREAD

**Issue by r1si** [puppeteer/puppeteer#6246]
Only in last version of puppeeteer (v5.2.0) if i run some headless chorme with a --remote-debugging-port and then open it with my chrome, see a lot of strange char (no UFT8??) and don't work. 

If i perform a downgrade at 4.0.0 works.

here a code to reproduce the problem:
`const puppeteer = require('puppeteer');

(async () => {
	

	let link = "https://www.youtube.com/watch?v=Ym8JjY4fy-M";

	let number_borwser = 5;

	for (let i = 0; i < number_borwser; i++) {
		let browser = await puppeteer.launch({
			headless: true,
			ignoreHTTPSErrors: true,
			slowMo: 0,
			args: [
				'--start-fullscreen',
				'--remote-debugging-port=922' + i,
				'--no-sandbox',
				'--disable-setuid-sandbox',
				'--disable-dev-shm-usage',
				'--disable-accelerated-2d-canvas',
				'--no-first-run',
				'--no-zygote',
				'--disable-gpu'
			]
		});

		let actual_pages = await browser.pages();
		let crt_page = actual_pages[0];
		
		
		await crt_page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36");
		await crt_page.goto(link);

		// press play
		await crt_page.evaluate(() => {
			return document.querySelector(".ytp-play-button").click();
		});

		console.log("RUN http://localhost:922" + i);

	}

})();`

**Comment by SandratraRM** [comment]
I'm using 5.2.1 and getting the same issue as well.

**Comment by bmz1** [comment]
Same with 5.2.1
