### ISSUE TITLE
make page.evaluateOnNewDocument() cancelable

### ISSUE THREAD

**Issue by FranckFreiburger** [puppeteer/puppeteer#6261]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: win7
* Node.js version: 12.17

**What steps will reproduce the problem?**

With the aim of recycling pages, `evaluateOnNewDocument()` that has been set cannot be removed.

```
	await page.exposeFunction('test', (arg) => {
		console.log(arg)
	});

	await page.evaluateOnNewDocument(() => {
		test('foo')
	});

	await page.goto('http://www.example.com/')
	await page.goto('http://www.example.com/')
	await page.evaluateOnNewDocument(() => {}) // try to cancel
	await page.goto('http://www.example.com/')

```

**What is the expected result?**

console log:
	foo
	foo

**What happens instead?**

console log:
	foo
	foo
	foo

**Comment by jalovatt** [comment]
Same issue here - in our case, reusing a page to generate multiple screenshots of a React component that uses both fetched data and changes fed in via `evaluateOnNewDocument`.

Puppeteer does register `add` and `remove` commands with the client (Chromium + Linux here):
```
e.registerCommand("Page.addScriptToEvaluateOnNewDocument",[{name:"source",type:"string",optional:!1},{name:"worldName",type:"string",optional:!0}],["identifier"])
e.registerCommand("Page.removeScriptToEvaluateOnNewDocument",[{name:"identifier",type:"string",optional:!1}],[])
```
`remove` doesn't appear to be used anywhere though, much less exposed to users via Page. Would be handy. :)

----

In case it helps anyone with a similar use case to mine, I ended up providing the data via an exposed callback:
```js
class ScreenshotHandler {
  
  ...

  generateScreenshot = async (url, applyChanges) => {
    await this.page.exposeFunction('getChanges', () => applyChanges);

    await this.page.goto(url, {
      waitUntil: ['load', 'networkidle0'],
    });

    // screenshot vignette headless page
    return this.page.screenshot({ fullPage: true });
  };
```
The React page is then able to treat `window.getChanges` just like any other asynchronous fetch.
