### ISSUE TITLE
Protocol error Invalid InterceptionId on cancelled requests

### ISSUE THREAD

**Issue by nazieb** [puppeteer/puppeteer#627]
When I tried to implement the "naive" image blocking like the one shown in the [API reference page](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetrequestinterceptionenabledvalue) by enabling request interception, at one particular webpage I always encounter this error:

`
(node:73712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Network.continueInterceptedRequest): Invalid InterceptionId. undefined
`

After some digging I figured out that the error always happen when the Puppeteer intercepting request to one particular URL. And when I open that webpage on non-headless Chrome to debug the all requests being made, it turns out the request which cause the error has "canceled" status.

![screen shot 2017-08-31 at 7](https://user-images.githubusercontent.com/463775/29901383-e481c05e-8e21-11e7-8a7f-e40ccc83858c.png)

What I suspect is when I called `interceptedRequest.continue()`, the underlying Chromium process already "lost" the interception, which cause it to return [this error](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/lkcr/content/browser/devtools/devtools_url_request_interceptor.cc#121).

I tried to ignore that URL and don't call `abort` or `continue`, but it caused the whole page to "hang".

**Comment by aslushnikov** [comment]
@nazieb what's you puppeteer version? Current tip-of-tree has a fix for request interception.

Also, any chance you can share a URL so that I can reproduce the issue?

**Comment by nazieb** [comment]
@aslushnikov my yarn.lock show this:

```
puppeteer@^0.10.0:
  version "0.10.1"
  resolved "https://registry.yarnpkg.com/puppeteer/-/puppeteer-0.10.1.tgz#a26f7012ff0fcc9f21c70ff9e2a8c60cba568a83"
```

As of the URL, I'm sorry but I'm afraid I'm not allowed to expose both the main webpage and the canceled request URL. I'll try another public website to see whether this bug also happened.

**Comment by aslushnikov** [comment]
@nazieb It's unlikely, but this might be related to #558. Could you please install 0.10.2-alpha directly from github and check if the issue persists?

**Comment by nazieb** [comment]
@aslushnikov I've tried to install from master, but when I start the app I got this error:

```
$ node index.js 
module.js:471
    throw err;
    ^

Error: Cannot find module './node6/Puppeteer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/puppeteer/index.js:25:18)
```

What I did is just change the version in `package.json` to:
```
"puppeteer": "GoogleChrome/puppeteer#master",
```

and run `yarn upgrade`. Is there anything wrong with my steps?

**Comment by aslushnikov** [comment]
@nazieb ah, you're running with node6.

Could you please do the following after the install:
- go to the puppeteer directory: `node_modules/puppeteer`
- run `npm run build`

**Comment by nazieb** [comment]
@aslushnikov I've upgraded my node version to v8 and tested again on master branch. The error message still show up, but now it didn't cause the whole request to hang.

And I've found some public URL for you to try: https://www.merdeka.com/peristiwa/habib-rizieq-tegur-keras-presidium-alumni-212-karena-bela-hary-tanoe.html

It's an Indonesian website news, and it shows the exact same error message.

**Comment by aslushnikov** [comment]
@nazieb thanks so much for the link, it helps a lot!
