### ISSUE TITLE
Chromium and Firefox Nightly crashes wenn accessing microphone and camera on Mac OS

### ISSUE THREAD

**Issue by Xarno** [puppeteer/puppeteer#6271]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Mac OS 10.15.6
* URLs (if applicable):
* Node.js version: v14.5.0

**What steps will reproduce the problem?**

0. Take the amazon chime sdk demo: https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser and run it
1. Skript: 
```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: false}); 

    const context = browser.defaultBrowserContext();
    //await context.overridePermissions('http://127.0.0.1:8080/', ['camera','microphone']);

    const page = await browser.newPage();
    await page.goto('http://127.0.0.1:8080/');
    page.on('console', msg => console.log('PAGE LOG:', msg.text()));
    //await browser.close();
})();
```

2. start the script, enter meeting title and name, click continue
3. Browser crashes

**What is the expected result?**
No crash at all.
Even if i start the downloaded browser manually and grant the permissions in the browser and in macos manually they crash when controlled by puppeteer.
They do not crash if they are started standalone.

**What happens instead?**
Cromium and Firefox nightly crashes.

**Comment by Xarno** [comment]
Looks like an upstream problem. Happens with selenium webdriver and chromedriver/geckodriver too.

**Comment by xuanmiaoshuo** [comment]
My friend has same problem. I don't have any idea how to fix it. any updates about this?  @Xarno

**Comment by Xarno** [comment]
No, sadly we haven't gone further into testing.

**Comment by xuanmiaoshuo** [comment]
> No, sadly we haven't gone further into testing.

👌，Still very much appreciated
