### ISSUE TITLE
Catching net::ERR_INTERNET_DISCONNECTED

### ISSUE THREAD

**Issue by ProgramJack** [puppeteer/puppeteer#6277]
Hello. I was wondering if someone can help me catch the specific error "net::ERR_INTERNET_DISCONNECTED".

This only happens if I were to run the code when my internet is not connected. What happens afterwards is that once I do try to run my code, functions such as "page.reload()" are completely non-functional. I spent some time myself to try resolving. And I'm not sure exactly how to catch this and some other specific errors. Ideally this scenario would never happen if I were to try and start it up, but if for some reason I do and I do not catch it at that time, I would like to make it so that it would somehow restart itself if possible.

I tried using "browser.on()" and "page.on()", but it seems that once it does not work without internet connection the first time, nothing will be able to interact with it.

**Comment by epexa** [comment]
#3709

**Comment by epexa** [comment]
@ProgramJack check this solution: https://github.com/puppeteer/puppeteer/issues/1454#issuecomment-945575831
