### ISSUE TITLE
Puppeteer test hangs forever if alert appears on the page

### ISSUE THREAD

**Issue by sergtimosh** [puppeteer/puppeteer#6278]
In the app I'm testing there is a bug, there is an alert appearing randomly while test execution. The problem is that when this alert happens test never fail, even with timeout set. So it hangs all tests to be executed.
Setting error listener helps, but then this type of bugs can't be detected directly.  
`page.on('dialog', async dialog => {
    await dialog.dismiss();
	});`

![image](https://user-images.githubusercontent.com/26712442/88526517-b3033580-d004-11ea-8365-ca37d121a031.png)
Does anybody else hit into this issue? How to make test fail, no matter if there is any errors?

**Comment by christian-bromann** [comment]
> Does anybody else hit into this issue?

What test framework are you using? This should be definitely be caught by the framework timeout.
