### ISSUE TITLE
Collect element attributes from selector

### ISSUE THREAD

**Issue by muminoff** [puppeteer/puppeteer#628]
Beginner user here. Started playing with this project recently. Wanted to make simple scraper which can collect `href` attribute of all anchors on the page.

Tried this:
```javascript
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  await page.goto('http://kun.uz/');
  const anchors = await page.$$('a');
  for (const anchor of anchors) {
    console.log(anchor.attribute('href'));
  }
  browser.close();
})
```

Got:
```shell
(node:96762) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: anchor.attribute is not a function
(node:96762) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any suggestions how to handle this task?

**Comment by paulirish** [comment]
i think this would do it.

```js
const hrefs = await page.evaluate(() => {
  const anchors = document.querySelectorAll('a');
  return [].map.call(anchors, a => a.href);
});
```

And once #625 is implemented this will be...

```js
const hrefs = await page.$$eval('a', a => a.href);
```

(note i'm using the href _property_ which is a resolved URL and different from the unresolved href _attribute_ string. (that would be `a.getAttribute('href')`)  i think you want the property's value. :)

**Comment by muminoff** [comment]
@paulirish Thanks

**Comment by vsemozhetbyt** [comment]
@muminoff Your code seems also workable, you just need to add one `await`:
```js
    console.log(await anchor.attribute('href'));
```
and be sure you have the last version of puppeteer:
```console
npm install https://github.com/GoogleChrome/puppeteer/
```
But the code of @paulirish may be faster.

**Comment by muminoff** [comment]
@vsemozhetbyt Thanks for your suggestion. Adding `await` before `anchor.attribute(..)` solved the  issue. Of course, only with latest version. NPM version doesn't support it. Kudos!

**Comment by muminoff** [comment]
@vsemozhetbyt 

Main difference is @paulirish's code is collecting links with absolute path, the latest snippet is collecting with relative path.

**Comment by vsemozhetbyt** [comment]
@muminoff You can get relative paths with the `a.getAttribute('href')`. I also mean that @paulirish's code reduces async interaction between Node.js and Chromium and this can be faster than many `await` in the cycle.

**Comment by prideofconcept** [comment]
any idea why the following would cause an error for ```anchor.attribute is not a function```

`
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('http://kun.uz/', {waitUntil: 'networkidle'});
    const anchors = await page.$$('a');
    for (const anchor of anchors) {
        console.log(await anchor.attribute('href'));
    }
    await browser.close();
})();

`

**Comment by vsemozhetbyt** [comment]
@prideofconcept `elementHandle.attribute()` seems to be deleted in https://github.com/GoogleChrome/puppeteer/pull/638

I think the fastest way to get what you need is something like this:
```js
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('http://kun.uz/', { waitUntil: 'networkidle' });

  const hrefs = await page.evaluate(
    () => Array.from(document.body.querySelectorAll('a[href]'), ({ href }) => href)
  );

  for (const href of hrefs) {
    console.log(href);
  }
  await browser.close();
})();
```

**Comment by zoutepopcorn** [comment]
I use:

```javascript
 const hrefs = await page.$$eval('a', hrefs => hrefs.map((a) => {
      return a.href
 }));
 console.log(hrefs);
```

In v 0.0.13

**Comment by ctsstc** [comment]
I had issues with what @paulirish had above.
This is what ended up working for me (pretty much the same as @zoutepopcorn just a bit cleaner #oneLiner)

```javascript
const hrefs = await page.$$eval('a[href]', aTags => aTags.map(a => a.getAttribute("href")));
```

**Comment by Swiffers** [comment]
How to do with custom attribute? i.e `attr-meta`

**Comment by dalu** [comment]
Ok, the img version seems to be 
```js
const imgs = await page.$$eval('img[src]', imgs => imgs.map(img => img.getAttribute('src')));
```
but what about meta tags? they have more than 1 attrib to seek.

**Comment by vsemozhetbyt** [comment]
@dalu If you need several attributes, you can iterate over `element.getAttributeNames()`.  Here we get all attributes of all `meta` tags in https://example.org/ as an array of objects:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    console.log(await page.evaluate(() =>
      [...document.querySelectorAll('meta')]
        .map(elem => {
          const attrObj = {};
          elem.getAttributeNames().forEach(name => {
            attrObj[name] = elem.getAttribute(name);
          })
          return attrObj;
        })
    ));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```js
[ { charset: 'utf-8' },
  { 'http-equiv': 'Content-type',
    content: 'text/html; charset=utf-8' },
  { name: 'viewport',
    content: 'width=device-width, initial-scale=1' } ]
```

**Comment by dalu** [comment]
Thank you @vsemozhetbyt . Sorry for sidetracking, but it's hard to search for something like [page].
the `[page]` way to define a variable, is that a way to define a variable to represent an array ? `page[]`
I've never seen this before. I'm a former PHP guy and now Go for a few years. js or ecmascript has had a rapid development cycle with new releases in the last few years and I never really paid much attention to js.
Do you have a keyword to search for? Is that es2016?

And why is it
`const [page] = await browser.pages();`
browser.pages()?
I'm guessing this is the better way, instead of opening a new page, an initial page already exists when you launch().
And speaking of launch,
```js
        const browser = await puppeteer.launch({
            ignoreHTTPSErrors: true,
            headless: true,
            executablePath: '/usr/bin/chromium',
            args: ['--window-size=1280,1696']
        });
```
this args does nothing. Window size defaults to 800x600.
The bundled chromium segfaults, that's why I'm using the local one. (archlinux)

**Comment by vsemozhetbyt** [comment]
Yes, we use [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) to utilize the already opened first tab.

If `--window-size` does not work for you (and it seems it does not affect viewport anyway), try [`page.setViewport(viewport)`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport) and maybe `args: ['--start-maximized']` in addition, if you use headful browser.

**Comment by Shirkiss** [comment]
This will return a list of all hrefs:
`            const hrefs = await page.$$eval('a', anchors => [].map.call(anchors, a => a.href));
`

**Comment by JohnDotOwl** [comment]
> i think this would do it.
> 
> ```js
> const hrefs = await page.evaluate(() => {
>   const anchors = document.querySelectorAll('a');
>   return [].map.call(anchors, a => a.href);
> });
> ```
> 
> And once #625 is implemented this will be...
> 
> ```js
> const hrefs = await page.$$eval('a', a => a.href);
> ```
> 
> (note i'm using the href _property_ which is a resolved URL and different from the unresolved href _attribute_ string. (that would be `a.getAttribute('href')`) i think you want the property's value. :)

Nice, Thank you.

**Comment by oscar-corredor** [comment]
> This will return a list of all hrefs:
> ` const hrefs = await page.$$eval('a', anchors => [].map.call(anchors, a => a.href));`

Is there a specific reason why you use `[].map.call(anchors, a => a.href)` instead of `anchors.map(a => a.href)`?
