### ISSUE TITLE
Adjust Puppeteer unit tests to aid in adding further cross-browser support

### ISSUE THREAD

**Issue by mjzffr** [puppeteer/puppeteer#6283]
In anticipation of growing cross-browser support in Puppeteer, the Puppeteer unit tests can be reworked to make it easier to test more browsers (a.k.a "products") as their API support gradually increases. 

This is meant as a sort of meta-issue. Specific follow-up issues should be filed as needed and noted here.

Here are some ideas that have come to mind as we've worked on adding Firefox support:

- [x] Add support for configuring timeout for individual tests or test configurations (e.g by product)
- [ ] Skip specific tests depending on an arbitrary combination of conditions (beyond binary describeSomethingOnly or describeFailsX).
- [ ] Use mocks to avoid unnecessary browser launch or install
- [ ] Allow alternative binary to be configured for each product instead of just the BINARY environment variable
- [ ] Isolate install/environment/process-handling tests from API tests e.g. process-handling tests should only depend on basic CDP API, if at all.
- [ ] Distinguish tests that assume specific package/binary installation conditions

Beyond this, I think we can file specific issues whenever we notice lack of test isolation or tests that can be broken down into smaller units.

**Comment by jackfranklin** [comment]
>  Skip specific tests depending on an arbitrary combination of conditions (beyond binary describeSomethingOnly or describeFailsX).

For this one, would a `itUnless(predicateFunc)` (and the same for `describe`) solve this, where the test is run or skipped depending on the result of `predicateFunc`, or are you thinking of something else?

**Comment by mjzffr** [comment]
@jackfranklin Yeah I was thinking of something along those lines
