### ISSUE TITLE
Browser crashes as .org.chromium.Chromium* (deleted) files are taking large disk space

### ISSUE THREAD

**Issue by swasti7** [puppeteer/puppeteer#6286]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.0
* Platform / OS version: Lambda
* URLs (if applicable): https://www.google.com
* Node.js version: Node JS 10.x

**What steps will reproduce the problem?**
When running on Lambda, available disk capacity is restricted to 512 MB.
I noticed when loading a heavy url, df shows high usage percentage as compared to du.
Eg. code to reproduce the issue of high disk usage 

try {
        await page.goto("https://about.google/?fg=1&utm_source=google-US&utm_medium=referral&utm_campaign=hp-header", {waitUntil: ['load', 'networkidle0'], timeout: 30000});
} catch (error) {
}

**What is the expected result?**

Du and df result show comparable disk usage. 

**What happens instead?**
 
After loading very first URL: https://about.google/?fg=1&utm_source=google-US&utm_medium=referral&utm_campaign=hp-header, df shows 66% disk used. (DF minimum is 28% as chromium binary takes around 130MB)
However, du shows far less usage. 
 
DF output (df -m /tmp):

Filesystem     1M-blocks      Used      Available     Use%    Mounted on
/dev/vdd             526             320          196              63%        /tmp
 
 
DU output: 
 
DU 8.0K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/Code Cache/wasm/index-dir
16K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/Code Cache/wasm
8.0K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/Code Cache/js/index-dir
148K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/Code Cache/js
168K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/Code Cache
4.0K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/blob_storage/f86b4787-bad6-4642-942c-75d1f898a1de
8.0K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/blob_storage
40K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default/GPUCache
240K /tmp/puppeteer_dev_chrome_profile-pg9wQc/Default
248K /tmp/puppeteer_dev_chrome_profile-pg9wQc
4.0K /tmp/locales
3.2M /tmp/aws/lib
976K /tmp/aws/.fonts/Open_Sans
980K /tmp/aws/.fonts
4.2M /tmp/aws
8.0K /tmp/cache-dir/index-dir
1.5M /tmp/cache-dir
4.8M /tmp/swiftshader
140M /tmp ---------------> DU shows /tmp disk usage to be 140 M whereas DF shows 320MB is used.
 
On further investigation, found that chromium process has Chromium process FDs referencing deleted .org.chromium.Chromium.* files causing disk to run out of space.
For this instance, I found around 40 such files out of which 36 were 4MB each.
Total disk space occupied by these deleted files ~ 160MB. 

One such FD,
 
{
            "name": "/tmp/.org.chromium.Chromium.yJcyXV (deleted)",
            "fd": "101",
            "stat": {
                "dev": 65072,
                "mode": 33152,
                "nlink": 0,
                "uid": 496,
                "gid": 495,
                "rdev": 0,
                "blksize": 4096,
                "ino": 218,
                "size": 4198400,
                "blocks": 8200,
                "atimeMs": 1595902017813.3027,
                "mtimeMs": 1595902017853.3027,
                "ctimeMs": 1595902017853.3027,
                "birthtimeMs": 1595902017793.3027,
                "atime": "2020-07-28T02:06:57.813Z",
                "mtime": "2020-07-28T02:06:57.853Z",
                "ctime": "2020-07-28T02:06:57.853Z",
                "birthtime": "2020-07-28T02:06:57.793Z"
            }
        },
}

For long running scripts, disk finally reaches its full capacity and browser crashes.

**Comment by mifi** [comment]
FYI I have the same issue in https://github.com/mifi/reactive-video/issues/11

A workaround is to remove the flag `--disable-dev-shm-usage` from puppeteer which was added in #1834 in which case they will instead be stored in `/dev/shm`
