### ISSUE TITLE
Using peppeteer convert url to pdf, there is always a url in the bottom of every pdf page

### ISSUE THREAD

**Issue by martinko2009** [puppeteer/puppeteer#6288]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:5.2.1
* Platform / OS version:win7
* URLs (if applicable):
* Node.js version:10.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.node ./generatePdf.js url pdfpath
2.generatePdf.js
```
const puppeteer = require('puppeteer');

(async () => {
	puppeteer.launch({headless: true,
						args: ['--no-sandbox', '--disable-setuid-sandbox']}).then(async browser => {
		try{
			const page = await browser.newPage();
			const arguments = process.argv.splice(2);
			const url = arguments[0];
			const pdfPath = arguments[1];
			const landscape = arguments[2] == "1" ? true : false;
			const format = arguments[3];
			await page.setDefaultNavigationTimeout(180000);
			await page.goto(url, {waitUntil: 'networkidle2'});
			await page.emulateMediaType('screen');
			await page.addStyleTag({
				content: `
					body { margin-top: 1cm; }
					@page:first { margin-top: 0; }
				`,
			});
			await page.pdf({
				path: pdfPath,
				printBackground:true,
				format: format,  //'A4'
				landscape:landscape,
				margin: {
					top: '15mm',
					bottom: '17mm',
					left: '12mm',
					right: '12mm'
				}
			});
			await browser.close();
		}catch (e){
			console.error(e);
			browser.close();
		}
	})
})();
```

**What is the expected result?**
I can choose to display the url (we will convert the url to pdf) in the bottom of every pdf page or not

**What happens instead?**

**Comment by mstr-pezhang** [comment]
Not reproduced. The following command
`node generatePdf.js https://www.baidu.com baidu.pdf`
resulted in a PDF like this.
[baidu.pdf](https://github.com/puppeteer/puppeteer/files/4999440/baidu.pdf)

But if I add `displayHeaderFooter: true` to the PDF options.
[baidu2.pdf](https://github.com/puppeteer/puppeteer/files/4999443/baidu2.pdf)
