### ISSUE TITLE
Puppeteer executablePath returns non-existant path for firefox when PUPPETEER_PRODUCT = "firefox"

### ISSUE THREAD

**Issue by TwoAbove** [puppeteer/puppeteer#6292]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.2.0
* Platform / OS version: Docker, `FROM node:12.18` (stretch)
* URLs (if applicable):
* Node.js version: 12.18

**What steps will reproduce the problem?**

For the dockerfile,
```dockerfile
FROM node:12.18

WORKDIR /app

COPY package*.json ./

RUN npm ci

# To get Firefox too. This will not be needed once puppeteer firefox exits beta
RUN cd node_modules/puppeteer && PUPPETEER_PRODUCT=firefox node install.js

COPY . .
```

For the test, 
```js
index.js
const [chromePath, firefoxPath] = (() => {
  const oldEnvVar = "" + process.env.PUPPETEER_PRODUCT;

  process.env.PUPPETEER_PRODUCT = "chrome";
  const CHROME_BIN = puppeteer.executablePath();


  // puppeteer.executablePath() points to an
  // unexistent installation pathpuppeteer.executablePath
  process.env.PUPPETEER_PRODUCT = "firefox";
  const FIREFOX_BIN = puppeteer.executablePath();

  process.env.PUPPETEER_PRODUCT = oldEnvVar;
  return [CHROME_BIN, FIREFOX_BIN];
})();
console.log(firefoxPath);
```

_Please include code that reproduces the issue._

1. `docker build --tag bug .`
See that the output will be something like
```
Step 11/12 : RUN cd node_modules/puppeteer && PUPPETEER_PRODUCT=firefox node install.js
 ---> Running in f6ad952bd0bc
Requesting latest Firefox Nightly version from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central

Firefox Nightly (81.0a1) downloaded to /app/node_modules/puppeteer/.local-firefox/linux-81.0a1
```
2. `docker run -it bug node .`
See that the path is 
```
/app/node_modules/puppeteer/.local-firefox/linux-768783/firefox/firefox
```

**What is the expected result?**
They should be the same

**What happens instead?**

They are not the same

**Comment by whimboo** [comment]
@TwoAbove did you actually install Puppeteer with `PUPPETEER_PRODUCT=firefox`?

**Comment by whimboo** [comment]
Oh, please drop it. I see you did. Is the Chrome binary also located under `/app/node_modules/puppeteer/.local-chrome`? Does that path match?

**Comment by TwoAbove** [comment]
Hey @whimboo 
I can reproduce this using the code I provided. The chrome binary is available

**Comment by whimboo** [comment]
So when you run the tests, does puppeteer try to access Firefox from the same location as downloaded or another path?

**Comment by TwoAbove** [comment]
Yes, the paths are different. 

So much time passed between filing and now that I'll need to re-test. Give me a bit of time to do that and I'll get back to you.

**Comment by whimboo** [comment]
Ok, so it would be good to know if `npm install` or `npm run` reference the wrong path. Just compare it with what you get when running these commands for Chrome. Both binaries should be located within the same folder.

**Comment by whimboo** [comment]
No further reply from reporter for more than a year. Closing issue.
