### ISSUE TITLE
Getting pageBinding.get is not a function when I exposed imported module. 

### ISSUE THREAD

**Issue by comcomhanb** [puppeteer/puppeteer#6293]
* Puppeteer version:v1.18.1 
* Platform / OS version: mac 10.13.6
* URLs (if applicable):
* Node.js version: v10.15.0.

**What steps will reproduce the problem?**

With this code, I am getting the exact same error with https://github.com/puppeteer/puppeteer/issues/5586, "VM1571:2 Uncaught (in promise) TypeError: this._pageBindings.get(...) is not a function".

var finder = require('@medv/finder') 

        await page.exposeFunction('finder', finder);
        await page.evaluateOnNewDocument(()=> {    
            document.addEventListener("click", function callback(e){
                const selecotr = finder(e.target);
                console.log(selecotr)
            } , true /* capture */);
            
        });

**What is the expected result?**
Should able to call "finder." I imported the finder module but I think it fails to bind it. 

**What happens instead?**
 
throw ""VM1571:2 Uncaught (in promise) TypeError: this._pageBindings.get(...) is not a function" error

**Comment by joshgrime** [comment]
t
