### ISSUE TITLE
Firefox processes blocks reinstall Puppeteer

### ISSUE THREAD

**Issue by inoyakaigor** [puppeteer/puppeteer#6298]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Win 10 x64 (build 2004)
* URLs (if applicable):
* Node.js version: 14.4.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Install Puppeteer with FF (81.0a1)
2. Run script https://gist.github.com/inoyakaigor/19ae0eeabf93fbfc04c368ffa17b6efa
3. Then I got an error `Evaluation failed: call to Function() blocked by CSP`
4. Uninstall puppeteer and install it with Chromium

**What is the expected result?**
Install succefull

**What happens instead?**
Got an error `Rolling back puppeteer@5.2.1 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir '_my_project_path_\node_modules\puppeteer\.local-firefox\win64-81.0a1\firefox'`
```
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path _my_project_path_\node_modules\puppeteer
npm ERR! dest _my_project_path_\node_modules\.puppeteer.DELETE
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename '_my_project_path_\node_modules\puppeteer' -> '_my_project_path_\node_modules\.puppeteer.DELETE'
```
It is happens because firefox processes for each run is not shutdown:
![image](https://user-images.githubusercontent.com/1235286/89103847-8b093d00-d41d-11ea-85d3-1e2fbbace725.png)

**Comment by mjzffr** [comment]
Thank you for reporting. We're investigating a number of issues with Puppeteer's Firefox launcher on Windows.

**Comment by mjzffr** [comment]
@inoyakaigor Can you still reproduce the issue if you add `-wait-for-browser` to the arguments passed to Firefox? As in:

```js
 await puppeteer.launch({ product:'firefox', args: ['-wait-for-browser']}
```

**Comment by inoyakaigor** [comment]
@mjzffr Yes I can. I recorded a video showing what's going on https://www.youtube.com/watch?v=somgzTbCMlc
Forgot to mention: when I get an error about CSP I press ctrl+с to stop process.

Also now I think that main problem in the Firefox: if you pay attention to tree of Firefox processes in the video you can see that root process shutdowns correctly but child processes is not.

**Comment by mjzffr** [comment]
Thanks for checking. I'll track a fix for this over in https://bugzilla.mozilla.org/show_bug.cgi?id=1656962

**Comment by whimboo** [comment]
This should no longer be an issue with a recent Firefox Nightly build. @inoyakaigor could you please verify that? Thanks a lot!

**Comment by whimboo** [comment]
I'm closing the issue for now, but happy to reopen if that is still a problem.

**Comment by inoyakaigor** [comment]
@whimboo yeah, will check it little bit later

**Comment by inoyakaigor** [comment]
@whimboo I can't check because I get another one [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1734896). But even this error whole firefox processes tree ends correctly at least.

**Comment by whimboo** [comment]
That's great to hear. Thanks a lot for checking.
