### ISSUE TITLE
Srapping interactivity between 2 iFrames

### ISSUE THREAD

**Issue by jeremiebardon** [puppeteer/puppeteer#6299]
I know it's not a good place to post that, really sorry but I've already post that on [stackoverflow ](https://stackoverflow.com/questions/63041715/puppeteer-get-element-of-parent-iframe)without success....

### Steps to reproduce

 I have a page with multiples iframes.

- The first one (parent) contain a dynamic value in an HTML element.
- The second one contains a table of products.

For the moment I have successfully retrieved the name and price of the products on the second iframe. But I also want the quantity which is the dynamic value in the global iframe.

For triggering the dynamic value I have to simulate a click on the quantity input on a product in the second Iframe.

My problem in Image:
![4DqH3](https://user-images.githubusercontent.com/17425520/89105907-4072cb00-d3f3-11ea-8bfd-9c33014f969b.png)

So I'm looking for a workaround to get the dynamic value from the global iframe in the second iframe if it's possible. Maybe an another solution exist?
```
// Child Frame products
  const pageFrames = await page.frames();
  const productsFrame = await pageFrames.find(f => f.name() === "oOrderExpress");

  // Parent Frame with the dynamic value
  const parentFrame = await page.$('[data-is-page-iframe="true"]');
  const frame = await parentFrame.contentFrame();
  
  // Get the JSHandles of the dynamic value
  const qtySelector = await frame.$('#oQtyAvailableSimpleDiv');

  // Wait for the second iFrame loading
  await productsFrame.waitForSelector('#oucLoadingImage_oImageLoading', {hidden: true, timeout: 0});
  

  // Loop throught products and return value, passing qtySelector don't work because -> JSHandles can be evaluated only in 
  the context they were created!
  const getProducts = await productsFrame.evaluate(async (qtySelector) => {

    let items = Array.from(document.querySelectorAll('table.tableGridRow'));
    
    let results = []

    for(let [index, item] of items.slice(0, 3).entries()) {
      let quantity = qtySelector.getProperty('innerText')
      const name = item.querySelector(`div#oGridExpress_r${index}_c5`).textContent;
      const price = item.querySelector('span.gridCellPrice').textContent;
      let input = item.querySelector(`#oGridExpress_r${index}_c3`);
      
      // Click on input to trigger dynamic value on parent Iframe
      await input.click();
      await sleep(3000);

      results.push({
        name,
        price,
        quantity
      })
    }

    return results;
    
  }, qtySelector);

```

* Puppeteer version: 5.2.1
* Platform / OS version: Windows

**What is the expected result?**
Retrieve the result of the global iframe after an action of the second one (Click on input quantity)

**What happens instead?**
Impossile to access DOM of 2 iFrame in the same time (according to the docs.)

Have you a workaround to this?

**Comment by suchengyong** [comment]
<scritp>alert(1)</script>
