### ISSUE TITLE
Emulate offline

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#63]
(taken from https://github.com/gr2m/headless-chrome-test/issues/1)

Puppeteer should have an offline mode to test PWA's. For example:

```js
page.setOfflineMode(true);
```

Emulation of other network conditions might be useful as well, but we can wait with them until there are good scenarios.

**Comment by aslushnikov** [comment]
@paulirish @ebidel how do you guys feel about the `page.setOfflineMode`? This seems to be trivial to implement but really useful. We can add a `page.setNetworkConditions(condition)` method later if there's a need to, and keep the `setOfflineMode` as an alias for `setNetworkConditions('offline')`.

**Comment by aslushnikov** [comment]
This is blocked on Chrome Headless network emulation support: https://bugs.chromium.org/p/chromium/issues/detail?id=728451

**Comment by aslushnikov** [comment]
As discussed with @pavelfeldman, we should not do anything other then `setOfflineMode` - we're pretty bad at network shaping. There's a specific tooling which does this much better and on a much lower level.

**Comment by benjamingr** [comment]
@aslushnikov do you mind elaborating on this? I would love to be able to do network emulation to test scenarios in my app.

Alternatively, a docker container image that runs something that does do network condition throttling would be great.

For example I need to test a scenario where 2 clients are communicating with a server.

**Comment by paulirish** [comment]
@benjamingr  The devtools throttling has some issues: [Network Throttling &amp; Chrome - status](https://docs.google.com/document/d/1TwWLaLAfnBfbk5_ZzpGXegPapCIfyzT4MWuZgspKUAQ/edit)

> Alternatively, a docker container image that runs something that does do network condition throttling would be great.

I've discussed this with Pat Meenan of webpagetest and he indicates docker isn't a reliable solution for network shaping as you cannot modify the network interface within the container; the network interface is bridged with the host. This was unfortunate news to me as well. :)

Using dummynet to change the entire system's network shaping (and requiring sudo) are just required on the host machine for high quality throttling. Not ideal but that's what it is.

**Comment by Garbee** [comment]
If you don't want to run as root but still want to have some level of automated traffic shaping (even if low fidelity). Then what you'd want to do is setup a proxy for those tests. Do it where any tests that need throttling use an instance that is talking to your proxy that will handle the network manipulation. You'd pass the proxy in when launching an instance just like you would from the command line as an `arg` option.

```js
let instance = puppeteer.launch({
  args: [
   '--proxy-server=127.0.0.1:9876', // Or whatever the address is 
  ]
});
```

This allows you to use other external tools to manage the network shaping. Such as Charles Proxy on Mac OS. Finding a good cross-platform solution for testing is difficult though, as Windows in particular is dramatically different to talk to.

**Comment by benjamingr** [comment]
Thanks @Garbee that's very helpful.

@paulirish that makes sense. I think we'll go ahead with a proxy server solution.

**Comment by benjamingr** [comment]
@Garbee would that also intercept DataChannels traffic?

**Comment by Garbee** [comment]
A proxy should. Since that is an entire external man-in-the-middle between the program and the network interface.

**Comment by benjamingr** [comment]
Thanks, I think that this can be closed now.

**Comment by aslushnikov** [comment]
wait, we still want to have `page.setOfflineMode` implemented :)
