### ISSUE TITLE
using puppeteer to convert PDF, The style in the exported local PDF file is inconsistent with the style of the web page

### ISSUE THREAD

**Issue by ericpku** [puppeteer/puppeteer#6302]
**Tell us about your environment:**

* Puppeteer version:5.2.1
* Platform / OS version:macOS Catalina 10.15.4
* URLs (if applicable):http://ericpku.github.io/
* Node.js version:V12.18.1

**What steps will reproduce the problem?**

If I set a **custom width and height** when using puppeteer pdf export, there will be a problem of dislocation.
In addition, using **format: A4** setting won't cause this problem.

I guess there is a bug splitting the pdf pages when using custom size.
Thanks for your help. : )

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({
        headless: true,
        args: [
            '--disable-dev-shm-usage',
            '--disable-setuid-sandbox',
            '--no-first-run',
            '--no-sandbox',
            '--no-zygote',
            '--single-process',
        ],
        timeout: 3000,
    });
    const url = 'http://ericpku.github.io/';

    // create page
    const page = await browser.newPage();
    const slideNum = 3;
    const pageHeight = 540 * slideNum;
    page.setViewport({ width: 960, height: pageHeight, isMobile: false });
    await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36');

    // goto page
    await page.goto(url, { waitUntil: 'domcontentloaded' });
    await sleep(1000);

    // convert to pdf
    await page.pdf({
        path: './example.pdf',
        width: '960',
        height: '540',
        printBackground: true,
    });
    await page.close();
```

**What is the expected result?**
The original webpage is http://ericpku.github.io/.
The screenshot as below:
https://github.com/ericpku/ericpku.github.io/blob/master/expect.jpg

**What happens instead?**
The screenshot as below:
https://github.com/ericpku/ericpku.github.io/blob/master/wrongResult.jpg
The output pdf file with error:
https://github.com/ericpku/ericpku.github.io/blob/master/wrongResult.pdf

By comparing the content of the web page with the content of the pdf file, it is obvious that the position of the text has shifted.

**Comment by clpacheco90** [comment]
Hi,
I like to use this instead: https://github.com/mozilla/pdfjs-dist
Did you already tried it? 

```js
...
        pdf.getPage($scope.editor.components.current.page).then(function(page) {
          // Prepare canvas using PDF page dimensions
          var canvas = document.createElement('canvas');
          // var canvas = document.getElementById('canvasPDF');
          var context = canvas.getContext('2d');

          if (!$scope.editor.components.current.scale) $scope.editor.components.current.scale = 1;
          var viewport = page.getViewport({
            scale: $scope.editor.components.current.scale
          });
          canvas.height = viewport.height;
          canvas.width = viewport.width;

          // Render PDF page into canvas context
          var renderContext = {
            canvasContext: context,
            viewport: viewport
          };

          var renderTask = page.render(renderContext);
          renderTask.promise.then(function() {
            $scope.appPDF.src = canvas.toDataURL();
            $scope.$apply();
          });
        });
      }, function(reason) {
        // PDF loading error
        console.error(reason);
      });
...
```

**Comment by ericpku** [comment]
> Hi,
> I like to use this instead: https://github.com/mozilla/pdfjs-dist
> Did you already tried it?
> 
> ```js
> ...
>         pdf.getPage($scope.editor.components.current.page).then(function(page) {
>           // Prepare canvas using PDF page dimensions
>           var canvas = document.createElement('canvas');
>           // var canvas = document.getElementById('canvasPDF');
>           var context = canvas.getContext('2d');
> 
>           if (!$scope.editor.components.current.scale) $scope.editor.components.current.scale = 1;
>           var viewport = page.getViewport({
>             scale: $scope.editor.components.current.scale
>           });
>           canvas.height = viewport.height;
>           canvas.width = viewport.width;
> 
>           // Render PDF page into canvas context
>           var renderContext = {
>             canvasContext: context,
>             viewport: viewport
>           };
> 
>           var renderTask = page.render(renderContext);
>           renderTask.promise.then(function() {
>             $scope.appPDF.src = canvas.toDataURL();
>             $scope.$apply();
>           });
>         });
>       }, function(reason) {
>         // PDF loading error
>         console.error(reason);
>       });
> ...
> ```

Thanks for your advice. My aim is to export web content which looks like PPT to local PDF, not to display PDF online.
