### ISSUE TITLE
Proposal: Query by accessible name

### ISSUE THREAD

**Issue by johanbay** [puppeteer/puppeteer#6307]
## Motivation
Currently Puppeteer supports querying the DOM using CSS selectors. While this provides a versatile way to select DOM elements by for example id, tag, or class-attributes, these properties are often subject to change or even generated at build-time.
Alternatively, we could support querying the accessibility tree for accessible names.
This could provide the following benefits:
- Make selectors in test scripts more resilient to source code changes.
- Make test scripts more readable since the accessible names should carry semantic context.
- Motivate good practices for assigning accessibility properties to elements.

## Current state of affairs
Querying by accessible names is currently possible by implementing a custom query handler to traverse the DOM and check accessible names along the way. This is what [puppeteer/recorder](https://github.com/puppeteer/recorder) currently does. Since there is no direct way to get the computed accessible name and role from the browser-side, one has to compute those on demand which is not a trivial task.
One can instead access and traverse the accessibility tree through Puppeteer where the computed accessible names and roles are available. The catch then is that Puppeteer only gives access to a static snapshot of the accessibility tree. 
To support interaction, we need a mapping to live DOM nodes.

## Proposal
Extend Puppeteer to support querying the accessibility tree with support for interaction.
The steps for achieving this could be:
- [x] Implement CDP-level support for querying the accessibility tree.
Landed in https://github.com/chromium/chromium/commit/d557b1cd92b3c47dae01aaaddd7c6be0ceb6cb94
- [x] Restructure such that query handlers can query on the Puppeteer-level (as opposed to querying in the page context) 
Done in #6437.
- [x] Implement atlernative query handler for a11y-based querying
Done in #6459  and #6472.

**Comment by WickyNilliams** [comment]
Hey, sorry to jump on a closed issue - i'm wondering if there are any docs available for this feature? The [introductory blog post](https://developers.google.com/web/updates/2020/11/puppetaria) mostly explains about the internal implementation details, and doesn't explain the feature set. 

Love the idea here, I'm eager to put it to use in my test suite!

**Comment by mathiasbynens** [comment]
That's a good point. While we do have docs on [how to register custom query handlers](https://github.com/puppeteer/puppeteer/blob/v7.0.1/docs/api.md#puppeteerregistercustomqueryhandlername-queryhandler), we don't really document the built-in ones. Let’s use a new issue for this: #6822

**Comment by mathiasbynens** [comment]
Let’s use a new issue for this: #6822

**Comment by WickyNilliams** [comment]
Thanks @mathiasbynens!
