### ISSUE TITLE
Response is null after 2 navigations using the same Page Object

### ISSUE THREAD

**Issue by vibou** [puppeteer/puppeteer#631]
I create an browser instance and a page object.
I use goto to perform the first navigation. It is working fine and returns a Response Object

I use goto to perform a second navigation returns a null object. 

`const nav_response = await page.goto(url, this.navigationOptions);`
`const status = nav_response.status;`

Cannot read property 'status' of null.

What is weird is that chrome browser navigation is perfectly fine.

**Comment by vibou** [comment]
After further investigation, this bug appears only when setRequestInterceptionEnabled is set to true.

Here is a full test to reproduce the bug. May be I am missing something when declaring my events handlers. 

[test.js.zip](https://github.com/GoogleChrome/puppeteer/files/1266566/test.js.zip)

**Comment by aslushnikov** [comment]
Thanks for reporting this. This is definitely a bug, I can easily repro.

**Comment by yujiosaka** [comment]
@vibou (cc: @aslushnikov )

Seems this problem has been fixed on master branch.
The example code needs to be modified due to API changes.

The latest code should look like this:

```
const puppeteer = require('puppeteer');

async function attachEventsOn(page) {
  await page.setRequestInterception(true); // setRequestInterceptionEnabled => setRequestInterception
  page.on("request", function (request) {
    url = request.url;
    request.continue();
    // console.log("Request to " + url);
  });

  page.on("dialog", function (dialog) {
    dialog.dismiss();
  });

  page.on("requestfinished", function (request) {
    url = request.url;
    // console.log("Request finished to " + url);
  });

  page.on("requestfailed", function (request) {
    url = request.url;
    // console.log("Request failed to " + url);
  });

  page.on("load", function() {
    // console.log("Page is loaded");
  });
}

async function  test() {
  const args = {
    ignoreHTTPSErrors: true,
    headless: false,
    args: ["--disable-session-restore", "--no-sandbox"]
  };
  const settings = {
    "navigation": {
      timeout: 30000
    }
  };

  const browser = await puppeteer.launch(args);
  const page = await browser.newPage();
  attachEventsOn(page);

  const response1 = await page.goto("http://amazon.fr", settings.navigation);
  const response2 = await page.goto("http://google.fr", settings.navigation);

  console.log("Response 1: "+response1.status()); // status became a function
  console.log("Response 2: "+response2.status()); // status became a function
}

test();
```

**Result**
```
Response 1: 200
Response 2: 200
```

**Comment by aslushnikov** [comment]
Indeed, works fine for me on tip-of-tree.

**Comment by andreabisello** [comment]
> I create an browser instance and a page object.
> I use goto to perform the first navigation. It is working fine and returns a Response Object
> 
> I use goto to perform a second navigation returns a null object.
> 
> `const nav_response = await page.goto(url, this.navigationOptions);`
> `const status = nav_response.status;`
> 
> Cannot read property 'status' of null.
> 
> What is weird is that chrome browser navigation is perfectly fine.

i'm getting the same issue randomly on puppeteer 5.2.1 , this is the pseudo code

```

loadUrl: async function (page, url) {
        let caricamento
        try {
            caricamento = await page.goto(url, {
                timeout: 60000,
                waitUntil: ['load', 'domcontentloaded', 'networkidle0', 'networkidle2']
            })
            try {
                await page.waitForSelector('body', {
                    visible: true,
                    timeout: 10000
                })
            } catch (error) {
                throw new Error("url loaded, but body not present!")
            }

           expect(caricamento.status()).toBe(200)

        } catch (error) {
            let screenshot = await this.takeScreenshot(page)
            throw new Error("url " + url + " url not loaded -> " + error + " see screenshot : " + screenshot)
        }

```

sometime, in a casual game , caricamento.status() throw exception due status() of null, even browser is working as expected (i see in not headless mode)
