### ISSUE TITLE
How can I get style  value

### ISSUE THREAD

**Issue by kannjaki** [puppeteer/puppeteer#6313]
I wanna get style value.
HTML
`<div class="fullsize cover" style="background-image: url(&quot;https://vpic.mildom.com/download/image/jp/mildom/vpic/71b805dc4dd49e621626d8dee0ec29eb.jpg&quot;);"></div>`
My try code
`const surl = await (await item.getProperty('style')).jsonValue();`

**Comment by xgirma** [comment]
```javascript
try {
   const styleValue = await page.$eval(".fullsize.cover)", (el) => el.getAttribute("style"));
   const regexp = new RegExp('https.*?jpg')
   const result = regexp.exec(styleValue);
   const surl = result[0];
} catch (error) {
   console.error(error)
}
```
