### ISSUE TITLE
Can't interact with Instagram while headless.

### ISSUE THREAD

**Issue by sbr2567** [puppeteer/puppeteer#6318]
I have a crawler that visits Instagram, however it only works when the browser is not headless. For some reason Instagram won't load their pages unless the user is attentive on the page, and running chromium in headless mode isn't providing attentiveness to the page for some reason?

I've never run into such a problem, can someone please explain to me what is likely going on? And if so how to achieve this task headlessly.

Thank you

**Comment by Asmhan** [comment]
Try to edit the user agent:
        "await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36');"

**Comment by sbr2567** [comment]
Creative but it didn't solve the issue unfortunately. What's happening is after logging in, an instagram popup appears before seeing the feed, I was able to avoid this none headlessly by grabbing the selector of the popup and then clicking "not now". However the selector while running puppeteer headlessly returns an error because it can't find the popup. Some how puppeteer is not being attentive enough to register the popup headlessly.

**Comment by LabN36** [comment]
Hi @sbr2567 , were you able to resolve this issue ? I'm also facing the same issue.
in local machine(macos) when running with headless:true and headless:false both works fine, i am able to view any public post without login.
but in the Ubuntu VM 18 it shows the Login screen, is there any way to bypass ?

please help me with any help or suggestion.
Thanks

**Comment by hzburki** [comment]
I have the same issue. For logging in I use ```await page.waitForSelector('input[name=username]');``` to check if the input has been loaded before entering the username. 

This works fine on Windows 10 and macOS **(local machines)** with headless `true` and `false` both. However, the same code does not work on Ubuntu 18 **(AWS EC2 Instance)**. 

It times out on the `waitForSelector` statement

### Edit 1

Turns out it had nothing to do with Puppeteer. I was scrapping Instagram and they are pretty aggressive against bots. Instagram had just blocked my dummy account and was redirecting all requests to **Not Found Page**

**Comment by leonardobork** [comment]
> Try to edit the user agent:
> "await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36');"

Works fine here. Thanks!

**Comment by ayarrus** [comment]
Nice @Asmhan 
`await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36');` works fine!

**Comment by Swapnil-Dey1199** [comment]
> Try to edit the user agent:
> "await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36');"

I had been facing the same issue. This worked for me!!!

**Comment by matrixcloud** [comment]
> Try to edit the user agent:
> "await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36');"

Thanks. Save my day.

**Comment by SPYNARY** [comment]
I have a similar error when i go on the register page , change the user agent not working for me
