### ISSUE TITLE
Puppeteer not rendering output

### ISSUE THREAD

**Issue by weswitt** [puppeteer/puppeteer#6321]
My environment is Ubuntu 20.04 with the latest NodeJS and Puppeteer.

The problem I'm seeing is that Puppeteer does not render the output of a MapBox map.  If I drop back to using an older version of MapBox it works fine.  Also an interactive Chrome browser renders the page perfectly so this seems to be a headless problem (my guess).

To reproduce the problem use the code below.  I am using a hardcoded 10 second timeout, but the problem is not that the wait is too short. In the interactive browser it renders in about 5 seconds. Also you can increase the timeout and it will never render.

JS:
(async() => {
const puppeteer = require('puppeteer');
const browser = await puppeteer.launch({headless: true,userDataDir: "data"});
const page = (await browser.pages())[0];
await page.goto('file:///home/wesw/map.html');
await new Promise(resolve => setTimeout(resolve, 10000));
await page.setViewport({ width: 800, height: 480 });
await page.screenshot({path: 'radarmap.png'});
await browser.close();
})();

HTML:
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css" rel="stylesheet" />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:800px; height:480px; }
    </style>
</head>
<body>
<div id='map'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoid2Vzd2l0dCIsImEiOiJjanZwaXFna28yM2gwM3lxbHdnbG05ZmE0In0.Y9ChPI860gDZPyGV-6TPmA';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-122.3351,47.6080],
    zoom: 7
});
</script>
</body>

**Comment by gbuckingham89** [comment]
Hey @weswitt - did you ever find a solution? I'm experiencing the same issue with Mapbox GL JS and Puppeteer.
