### ISSUE TITLE
[idea][question] What about having a page.clickOn and page.typeOn and other page.functionOn

### ISSUE THREAD

**Issue by LucasAsafe** [puppeteer/puppeteer#6327]
Is there a chance of having my PR approved if i create new page methods that allows user to choose what selector he wants to perform certain actions like page.click, page.type, page.focus and others without having to create their own functions using eval, $, $$.

It would work like this
page.clickOn(typeOfSelector, selectorItself) where typeOfSelector = [ xpath | selector | id | name | classname ]

**Comment by OhadAr** [comment]
Hey, i think the easiest way is to use page.waitForSelector ('YOUR_SELECTOR').then((a) => {
        a.click()
})
