### ISSUE TITLE
How to handle this page error?

### ISSUE THREAD

**Issue by mat-twg** [puppeteer/puppeteer#6330]
Hello! Sometimes i got this page with error (screenshot), `page.on("error", error => {});` doesnt catch it.. how can i handle this issue?

![chrome_error](https://user-images.githubusercontent.com/64251479/89904990-438b6980-dbf2-11ea-8bf2-f0e02859ff80.png)

### Steps to reproduce
i dont know how to reproduce... randomly happens...

**Comment by epexa** [comment]
#5928

**Comment by epexa** [comment]
#1454

**Comment by epexa** [comment]
#6277

**Comment by epexa** [comment]
#3709

**Comment by epexa** [comment]
@mat-twg check this solution: https://github.com/puppeteer/puppeteer/issues/1454#issuecomment-945575831
