### ISSUE TITLE
page.goto always times out in Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by nullromo** [puppeteer/puppeteer#6332]
### Steps to reproduce
1. `mkdir puppeteer_test`
1. `cd puppeteer_test`
1. `npm init -y`
1. `npm i puppeteer`
1. `touch index.js`
1. put the following into index.js:
```js
const puppeteer = require('puppeteer');

main = () => {
    let browser;
    let page;
    return Promise.resolve()
        .then(() => {
            console.log('Launching browser');
            return puppeteer.launch({ args: ['--no-sandbox'] });
        })
        .then((result) => {
            browser = result;
        })
        .then(() => {
            return browser.newPage();
        })
        .then((result) => {
            page = result;
        })
        .then(() => {
            console.log('Navigating');
            return page.goto('https://github.com/puppeteer/puppeteer');
        })
        .then(() => {
            console.log('Taking screenshot');
            return page.screenshot({ path: 'test.png' });
        })
        .then(() => {
            if (browser) {
                console.log('Closing browser');
                return browser.close().then(() => {
                    console.log('Browser closed');
                });
            } else {
                return Promise.resolve();
            }
        })
        .catch((error) => {
            return Promise.reject(error);
        });
};

main()
    .then(() => {
        console.log('Completed successfully');
    })
    .catch((error) => {
        console.error(error);
    })
    .finally(() => {
        console.log('Done');
    });
```
7. `node index.js`

#### Environment
* Puppeteer version: ^5.2.1
* Platform / OS version: Windows Subsystem for Linux (WSL)
* Node.js version: v12.18.0

#### What is the expected result?
There should not be errors, and a screenshot should be taken.

#### What happens instead?
I get the following output:
```
Launching browser
Navigating
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /c/Users/*******/home/puppeteer_test/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
Done
```
and then the program hangs. This happens no matter what URL I enter.

**Comment by xgirma** [comment]
Launching browser
Navigating
Taking screenshot
Closing browser
Browser closed
Completed successfully
Done

try https://ourcodeworld.com/articles/read/1106/how-to-solve-puppeteer-timeouterror-navigation-timeout-of-30000-ms-exceeded

**Comment by nullromo** [comment]
@xgirma Is that the output you got from running the code above? Unfortunately, your suggested solution did not work. I changed 

```js
page.goto('https://github.com/puppeteer/puppeteer')
```

to

```js
page.goto('https://github.com/puppeteer/puppeteer', {
    waitUntil: 'load',
    timeout: 1000 * 60 * 5,
})
```

and it still timed out after 5 minutes. For reference, this page takes about 4 seconds to load in Chrome.

I think there is something else going on here besides just slow loading.

**Comment by xgirma** [comment]
Yes I get the output from running your code, when I try it it works just fine. 

npm install -S puppeteer
node index.js

**Comment by nullromo** [comment]
@xgirma Thank you for confirming that my code works. Because of this, I thought it might be a WSL issue. I tried installing npm in gitbash instead and it works as I expected it to. Not sure why it doesn't work in WSL, but perhaps I should look into that more or open a different issue with them.

**Comment by nullromo** [comment]
Based on [this comment](https://github.com/puppeteer/puppeteer/issues/1837#issuecomment-534075536) I found that this worked for me:

```js
return puppeteer.launch({
    args: [
        '--no-sandbox',
        '--no-zygote',
        '--single-process',
    ],
});
```

Further, I had to add the `--disable-gpu` flag to run in `headless: false` mode.

**Comment by patricktree** [comment]
In case this helps someone, I had random timeouts using Puppeteer or Playwright on WSL 2.  
It was actually a problem of WSL 2 itself, this workaround solved the issues: https://github.com/microsoft/WSL/issues/7254#issuecomment-905767204
