### ISSUE TITLE
There's no chrome-84 NPM distribution tag

### ISSUE THREAD

**Issue by eaviles** [puppeteer/puppeteer#6333]
The latest available chromium on alpine is 84.0.4147.105. I was trying to install puppeteer for this specific version but there's no "chrome-84" NPM distribution tag.
### Steps to reproduce

**What steps will reproduce the problem?**
1. `npm view puppeteer dist-tags`

**What is the expected result?**
I should see a "chrome-84" tag pointing to a version.

**What happens instead?**
There's no "chrome-84" tag, there's one for version 85 though.

Is this problem intentional?

**Comment by mathiasbynens** [comment]
@hanselfmu It looks like this was forgotten after publishing v5.1.0: https://github.com/puppeteer/puppeteer/blob/main/CONTRIBUTING.md#updating-npm-dist-tags Could you PTAL?

**Comment by eaviles** [comment]
@mathiasbynens I just checked again and the tag isn't there yet.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/182510/90026211-045a2880-dc85-11ea-9b61-3d56d0934856.png">

**Comment by paulirish** [comment]
the chrome-84 tag was added eventually.  

but the dist-tags are no longer being updated as per #6571
