### ISSUE TITLE
Inconsistent handling of date in Chrome and Firefox

### ISSUE THREAD

**Issue by ritz078** [puppeteer/puppeteer#6335]
### Steps to reproduce 

In FF:

The following gives a string

```js
await page.evaluate(() => new Date()) // '2020-08-12T13:36:31Z'
```

In Chrome

The following gives an empty object

```js
await page.evaluate(() => new Date()) // {}
```

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: MacOS Catalina
* URLs (if applicable):
* Node.js version: 12.16.2

**What steps will reproduce the problem?**

Code written above

**What is the expected result?**

Both should return the same result

**What happens instead?**

Chrome is returning an object while Firefox is returning a string.

**Comment by mjzffr** [comment]
@mathiasbynens Is this expected?

**Comment by mathiasbynens** [comment]
Hmm, this is not really documented precisely. The API docs refer to [`Serializable` on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description), which (currently) says:

> The instances of `Date` implement the `toJSON()` function by returning a string (the same as `date.toISOString()`). Thus, they are treated as strings.

So one might reasonably expect a string result here.
