### ISSUE TITLE
Firefox: page.touchscreen.tap throws Protocol error

### ISSUE THREAD

**Issue by ritz078** [puppeteer/puppeteer#6336]
### Steps to reproduce

Using `page.touchscreen.tap(x, y)` throws the following error in firefox

```
Protocol error (Input.dispatchTouchEvent): Input.dispatchTouchEvent RemoteAgentError@chrome://remote/content/Error.jsm:25:5
    UnknownMethodError@chrome://remote/content/Error.jsm:108:7
    execute@chrome://remote/content/domains/DomainCache.jsm:96:13
    receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:86:45
```

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: MacOS Catalina
* URLs (if applicable):
* Node.js version: 12.16.2

**Comment by mjzffr** [comment]
The protocol implementation in Firefox doesn't include `Input.dispatchTouchEvent` yet. The tracking bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1549445 

Please feel free to [get in touch](https://wiki.mozilla.org/Remote) about your use case; it can help us prioritize.
