### ISSUE TITLE
unable get all childFrames when headless is false(puppeteer version 1.20.0,4.0.1,5.0.2),when version is 1.19.0 it is ok.

### ISSUE THREAD

**Issue by summergan** [puppeteer/puppeteer#6338]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:1.20.0
* Platform / OS version:mac
* URLs (if applicable):
* Node.js version:10.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.(await frame.childFrames()).length // 0 when headless is false
  (await frame.childFrames()).length // 1 when headless is true
2.
3.

**What is the expected result?**
Setting headless true or false must return the same childFrames. 
when i test this code on puppeteer version 1.19.0 which return the same childFrames.
**What happens instead?**

**Comment by gyohza** [comment]
Just confirmed that it is working in `1.19.0`. Previously I had `5.5.0` and it indeed couldn't retrieve the iframes from headless browsing.

Can't anyone look into this?
