### ISSUE TITLE
`pdf` `headerTemplate` and `footerTemplate`

### ISSUE THREAD

**Issue by AlexWayfer** [puppeteer/puppeteer#6339]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `5.2.1`
* Platform / OS version: Arch Linux 
* URLs (if applicable): none for now.
* Node.js version: `14.7.0`

**What steps will reproduce the problem?**

```js
await page.pdf({
  path: path.join(compiledDir, `${profile.first_name} ${profile.last_name}.pdf`),
  displayHeaderFooter: true,
  headerTemplate: 'Compiled at <span class="date"></span>',
  footerTemplate: '<span class="pageNumber"></span> / <span class="totalPages"></span>',
  margin: { top: 40, bottom: 40, left: 40, right: 40 },
  format: 'A4'
})
```

**What is the expected result?**

Correct text in `headerTemplate` and `footerTemplate`.

**What happens instead?**

![image](https://user-images.githubusercontent.com/6510020/90322408-45d82580-df5c-11ea-9489-7b5dbd86c153.png)

![image](https://user-images.githubusercontent.com/6510020/90322405-378a0980-df5c-11ea-948f-d9aa6142dd1f.png)

**Comment by sandorvasas** [comment]
you need to include your css in the header & footer template code. it's a completely other html document, you cannot share styles between your main pdf html and footer htmls

**Comment by AlexWayfer** [comment]
OK, it's just font-size, I didn't understand that, thank you.
