### ISSUE TITLE
Bundled chromium not working on RHEL7.1?

### ISSUE THREAD

**Issue by szhangpitt** [puppeteer/puppeteer#634]
I was running the sample code on a RHEL 7.1 machine. I got the error below. 

It seems gtk_widget_get_scale_factor was introduced [since gtk 3.10](https://developer.gnome.org/gtk3/stable/api-index-3-10.html#api-index-3.10) but I have 3.8. Does it mean the bundled chromium has some external dependency? 

```
node test.js

(node:23509) UnhandledPromiseRejectionWarning:
...Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!

/home/rda-web/node_modules/puppeteer/.local-chromium/linux-496140/chrome-linux/chrome: 
symbol lookup error: /home/rda-web/node_modules/puppeteer/.local-chromium/linux-
...496140/chrome-linux/chrome: undefined symbol: gtk_widget_get_scale_factor


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:23509) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
Did you look into [troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)? There's a list of dependencies that might help

**Comment by vs4vijay** [comment]
I tried installing dependencies using: `sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

But getting the same error: 
```
(node:17608) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:17608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am using Amazon Linux, 64-bit. What might be the problem?

**Comment by aslushnikov** [comment]
@vs4vijay this looks like a debian issue, make sure to check discussion in #290.
