### ISSUE TITLE
Whitespace rendered over footer?

### ISSUE THREAD

**Issue by sandorvasas** [puppeteer/puppeteer#6342]
v5.2.1 
Except for the first and last pages, my footer is over-rendered by some unknown whitespace I cannot remove. Looks like this:
[https://i.imgur.com/E5JtRhp.png](https://i.imgur.com/E5JtRhp.png) 
I have no clue how to remove it, nor about why it works on the first and last pages. It's not my elements overriding it: if I set `body * { background: transparent }`, the problem still persists. 
The main document body's HTML/CSS should **not** have any effect on the footers, puppeeteer should force-render the footer on top and cut the page content where the footer starts.

**Comment by lonewolfaka9** [comment]
+1
