### ISSUE TITLE
Intercept CONNECT method on request interception

### ISSUE THREAD

**Issue by SandratraRM** [puppeteer/puppeteer#6343]
I use a proxy server with puppeteer and the use of that proxy require me to set some specific headers only on [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) method.
I tried to use `page.on("request, (request) => ...)` but it seems to only work on GET and POST methods.
How can i intercept/mutate or just execute CONNECT requests using puppeteer?
 
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.2.1

**What steps will reproduce the problem?**

```js
const puppeteer = require("puppeteer");
const proxy = {
    host : "http://the.proxyHost.com",
    port : 8080
};

puppeteer.launch({
    headless : true,
    args: [
        `--proxy-server=${proxy.host}:${proxy.port}`
    ]
}).then(async (browser) => {
    const page = await browser.newPage();
    page.setRequestInterception(true);
    page.on("request", (request) => {
        // Printing the intercepted requests but no CONNECT
        console.log(`${request.method()} : ${request.url()}`);
        request.continue();
    });
    await page.goto("https://www.google.com");
});


```
**What is the expected result?**
Should have CONNECT method

**What happens instead?**
Only GET and POST methods

**Comment by fnuttens** [comment]
I have the same use case, thus the same issue 😞

Is it even possible to intercept CONNECT requests in the first place? I mean, puppeteer relies on the DevTools protocol, and I don't believe those requests show when debugging a connection through a proxy.
