### ISSUE TITLE
Unable to access iframe in localhost

### ISSUE THREAD

**Issue by goyalakshay12** [puppeteer/puppeteer#6344]
I am writing a puppeteer test in which  I am accessing the iframe and then typing inside the iframe, the test is working  fine when I am using the cloud stack URL but when I am trying to run the same test using localhost URL it’s not picking the iframe hence failing the test, although the selector for iframe and selectors inside the frames are same in both cloud stack and localhost. I tried printing the iframe and iframe element handle value and following are my findings.

For localhost URL:-
QUnitNodeLogMessage: waiting for iframe with embedded form to be ready
 QUnitNodeLogMessage: Iframe is ready
 QUnitNodeLogMessage: JSHandle@node
 QUnitNodeLogMessage:

For Cloudstack URL:-
 QUnitNodeLogMessage: waiting for iframe with embedded form to be ready
 QUnitNodeLogMessage: Iframe is ready
 QUnitNodeLogMessage: JSHandle@node
 QUnitNodeLogMessage: [object Object]

So In the above statement you can see for localhost its returning the null value. Can you show some insights regarding this and point me potentially what I could be doing wrong.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 
* Platform / OS version: Wins64
* URLs (if applicable):
* Node.js version: v12.16.0

**What steps will reproduce the problem?**
While accessing the iframe, print the iframe value to check whether iframe has been accessed or not.

_Please include code that reproduces the issue._

1.const elementHandle = await page.$(
      'iframe'
    );
2.console.log("Iframe is ready");
3.console.log(elementHandle);
4.const frame = await elementHandle.contentFrame();
5.console.log(frame);

**What is the expected result?**
 QUnitNodeLogMessage: Iframe is ready
 QUnitNodeLogMessage: JSHandle@node
 QUnitNodeLogMessage: [object Object]

**What happens instead?**
 QUnitNodeLogMessage: Iframe is ready
 QUnitNodeLogMessage: JSHandle@node
 QUnitNodeLogMessage:

**Comment by ritz078** [comment]
This should work.

```js
const iframeHandle = page.mainFrame().childFrames()[0] 
```
