### ISSUE TITLE
Delete cookie only works in headfull but not in headless

### ISSUE THREAD

**Issue by CyberT33N** [puppeteer/puppeteer#6346]
I successfully can delete cookies in headfull mode by using:
```javascript
const client = await page.target().createCDPSession();
await client.send('Network.clearBrowserCookies');
await client.send('Network.clearBrowserCache');  
console.log( 'done..' );
```

As far as I understand the code above is using the dev tools to archive this. In headless instead this code is not working. Just nothing happens and the code stucks and the console.log will not come. I assume that in headless mode the dev tools is not started?

Is there a way to use the code from above in headless mode?

I currently do as workaround Incognito page each new url. However I would like to have a more clean solution like the code above.

Greets CyberT33N

**Comment by SashaDesigN** [comment]
I use this to remove all cookies:

```
	async clearBrowser () {
		// clear cookies
		const client = await this.page.target().createCDPSession()		
		await await client.send('Network.clearBrowserCookies')
	}
```
