### ISSUE TITLE
puppeteer@5.2.1 Protocol error (Target.createTarget): Target closed

### ISSUE THREAD

**Issue by DSzhe1021** [puppeteer/puppeteer#6347]
**Puppeteer version: 5.2.1
Platform / OS version: Centos7
Node.js version: v12.18.2**

@jeresig @envoked @benatkin @slaskis @neerajdotname 

**After successfully installing puppeteer@5.2.1, the project can also be started normally, but Chromium cannot be opened, the error message is as follows** 

    (node:3216) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.createTarget): Target closed.

**code show as below:**

    const browser = config.initPuppeteer.browser
    const context = await browser.createIncognitoBrowserContext()
    const page = await context.newPage()

**The above code can run normally in puppeteer@1.13.0，If you want to run on puppeteer@5.2.1, the code needs to be changed to the following code**

    const browser = config.initPuppeteer.browser
    const page = await browser.newPage()

**I want to know why this is the createIncognitoBrowserContext method will throw such an error after the puppeteer version is upgraded**

**Comment by ObviouslyGreen** [comment]
I was able to reproduce on debian, node 10, and tried both v5.3.0 and v5.2.1. 

I used the example code from the puppeteer docs:
```
(async () => {
  const browser = await puppeteer.launch();
  // Create a new incognito browser context.
  const context = await browser.createIncognitoBrowserContext();
  // Create a new page in a pristine context.
  const page = await context.newPage();
  // Do stuff
  await page.goto('https://example.com');
})();
```

Here was the full error:
```
(node:593) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.createTarget): Target closed.
    at Promise (/root/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:63)
    at new Promise (<anonymous>)
    at Connection.send (/root/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:70:16)
    at Browser._createPageInContext (/root/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:221:53)
    at BrowserContext.newPage (/root/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:499:30)
    at /root/test.js:19:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Seems like the method and parameters were passed in correctly in Connection.js:
```
Method: Target.createTarget 
Params: { url: 'about:blank', browserContextId: '15F8684F4F0D6A476DB23A6F70256DD5' }
```
