### ISSUE TITLE
rrweb使用的iframe播放dom树 报错Navigation timeout of 30000 ms exceeded，

### ISSUE THREAD

**Issue by huang-Lei1327** [puppeteer/puppeteer#6351]
报错Navigation timeout of 30000 ms exceeded；
然后就不能截图了，我想问一下怎么可以忽略报错信息，直接可以截图的方法；

**Comment by xgirma** [comment]
https://ourcodeworld.com/articles/read/1106/how-to-solve-puppeteer-timeouterror-navigation-timeout-of-30000-ms-exceeded

**Comment by huang-Lei1327** [comment]
Thank you, the problem has been solved;
