### ISSUE TITLE
How can i click on the link, which contains a text inside the span

### ISSUE THREAD

**Issue by shrmaky** [puppeteer/puppeteer#6356]
I am trying to click on the link, which contains a  text inside the span 

Code i tried

```
 page
      .waitForSelector('span[text=]')
     .then(() => page.click('span[text=dummy]'));

```

DOM
```
<a class="nt-card__headline" href="/test" tabindex="0" ">
              <span aria-hidden="true">
                         Some
                         <span class="white-space-pre"> </span>
                          dummy              
                         <span class="white-space-pre"> </span>
                          text to match            
                         </span>
              <span class="visually-hidden">Some dummy text to match</span>
</a>
```

Any suggestion how how can i do this?

**Comment by vsemozhetbyt** [comment]
If I understand correctly, you need to find a link by its text content to click on. If so, these are at least two ways:

```js
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false, defaultViewport: null });
    const [page] = await browser.pages();

    const textToFind = 'More information...';

    // Way 1.

    await page.goto('https://example.org/');

    const link1 = await page.evaluateHandle(
      text => [...document.querySelectorAll('a')].find(a => a.innerText === text),
      textToFind
    );
    await link1.click();
    await page.waitFor(3000);

    // Way 2.

    await page.goto('https://example.org/');

    const [link2] = await page.$x(`//a[text()="${textToFind}"]`);
    await link2.click();
    await page.waitFor(3000);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
````

**Comment by vsemozhetbyt** [comment]
If you need to find a partial match, you can use `includes()` instead of `===` in the first way and XPath `contains()` in the second way.

**Comment by shrmaky** [comment]
> If you need to find a partial match, you can use `includes()` instead of `===` in the first way and XPath `contains()` in the second way.

Tried this but doesn't work 

```
  const textToFind = "happy birthday";

  const link1 = await page.evaluateHandle(
    text => [...document.querySelectorAll('a')].find(a => a.innerText.includes(text)),
    textToFind
  );
  await link1.click();

```
  await page.waitFor(3000);

**Comment by shrmaky** [comment]
but mainly the text is inside the span of <a>, may be thats why its not able to fetch/compare the text

**Comment by vsemozhetbyt** [comment]
If this span is inside the link, the `innerText` of the link should contain it. Maybe you could provide the exact HTML code with text to find?

**Comment by shrmaky** [comment]
Am trying to fetch this exact element on Linkedin

![image](https://user-images.githubusercontent.com/39021707/90953386-1e152000-e47c-11ea-88ce-0d1011461c7a.png)

Following is exact html
```
<a class="nt-card__headline nt-card__text--3-line nt-card__text--word-wrap t-14 t-black t-normal" href="/notifications/Birthdays/urn%3Ali%3Afsd%5FnotificationCard%3A%28BIRTHDAY%5FPROP%2Curn%3Ali%3AuniqueSuffix%3A%28urn%3Ali%3Anone%2C2eCdx3a5Tr6kW23ak%2DQGDg%29%29?title=Birthdays" tabindex="0" data-ember-action="" data-ember-action-1083="1083">
              <span aria-hidden="true"><!---->Wish<span class="white-space-pre"> </span><!---->Ishujeet Panjeta<!----><span class="white-space-pre"> </span>and 9 others<span class="white-space-pre"> </span><strong><!---->happy birthday<!----></strong></span><span class="visually-hidden"><!---->Wish Ishujeet Panjeta and 9 others happy birthday<!----></span>
          </a>
```

I also tried fetching from this -
``` 
const [link2] = await page.$x("//a[@class='nt-card__headline']/span/strong[contains(.,'happy birthday')]");
```

**Comment by vsemozhetbyt** [comment]
Can you try `textContent` instead of `innerText` (`innerText` can be affected with CSS and element layout). Also, be sure there are no special spaces in the text (like nbsp). If no luck, try to post a minimum executable code that reproduces the issue so that others also can check and debug.

**Comment by vsemozhetbyt** [comment]
Also, be sure if the issue is in element finding (try to check if `link1` or `link2` is element handle) and not in element clicking.

**Comment by shrmaky** [comment]
no success lol

```
  const textToFind = "happy birthday";

  const link1 = await page.evaluateHandle(
    text => [...document.querySelectorAll('a')].find(a => a.textContent.includes(text)),
    textToFind
  );

  console.log(link1);
  await link1.click();
  await page.waitFor(3000);

```

**Comment by shrmaky** [comment]
but anyways thanks

**Comment by vsemozhetbyt** [comment]
(BTW, in XPath, with multiple classes, you need something like `"//a[contains(@class,'nt-card__headline')]"`).

**Comment by vsemozhetbyt** [comment]
If I use your HTML fragment in a test HTML with DevTools console, both ways (with second way corrected) find the element. So the issue may be in another place (for example, the element may not be created yet when you try to find it).

**Comment by brantley-clove757** [comment]
I defined the answer https://outdoorsmanedit-in-place.github.io/SyGLvFIQgS6j4KIlElw/
