### ISSUE TITLE
Can't load images from external source. 

### ISSUE THREAD

**Issue by itzikbenh** [puppeteer/puppeteer#6358]
Whenever I have an `img` tag inside a template I get `Error: Navigation failed because browser has disconnected!` and no image appears.

If I use `page.goto` instead of `page.setContent` it will load images, but I need to load my own template. 

Using ` "puppeteer": "^5.2.1"`

```js
async function printPDF() {
    const browser = await puppeteer.launch();

    const template = ejs.compile(fs.readFileSync("./src/template.ejs", "utf8"));
    const html = template();

    const page = await browser.newPage();

    page.setContent(html);

    await page.emulateMediaType('screen');

    const pdf = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: { top: "1cm", right: "1cm", bottom: "1cm", left: "1cm" },
    });

    await browser.close();

    return pdf;
}
```

Currently only tested this locally on my Mac. Any ideas what's wrong?

**Comment by dpmott** [comment]
If your images are not inline data, then they would need to be fetched over the network.  

I think you need an `await` in front of `page.setContent()`.  That would help it to wait until the content is loaded. But also, you may need to include another instruction to allow all of the network activity to resolve before rendering your PDF.  Look for something to which you can pass an option of `{ waitUntil: 'networkidle0' }`

**Comment by YangGuoXuan-0503** [comment]
hello David, did you solve it？

**Comment by techfortified** [comment]
I'm facing this same issue. anyone with solution to this?

**Comment by icheered** [comment]
Same issue here... Any updates?

**Comment by Guneetsinghtuli** [comment]
@icheered  Maybe you can try this as it worked for me
`await page.setContent(html, {
      waitUntil: ["load", "networkidle0", "domcontentloaded"],
    });`

**Comment by iamnayanmore** [comment]
Try to include image in  base64-encoded string format. you can use the following function to convert the image URL to a base64 string

```
async function getBase64FromUrl(url) {
  const response = await axios.get(url, { responseType: 'arraybuffer' });
  const buffer = Buffer.from(response.data, 'binary');
  return buffer.toString('base64');
}
```
`const logo = await getBase64FromUrl('/images/logo-placeholder.png');`

Once you have the base64 string, you can pass this to your header or footer template and use it as follows

`src="data:image/jpeg;base64,<%= logo %>"`

Its work for me. I hope its help you too.
