### ISSUE TITLE
Firefox: page.setRequestInterception throws protocol error.

### ISSUE THREAD

**Issue by ritz078** [puppeteer/puppeteer#6359]
## Steps to reproduce 

Using
```js
await page.setRequestInterception(true)
```

throws the following error

```
Protocol error (Fetch.enable): Fetch.enable RemoteAgentError@chrome://remote/content/Error.jsm:25:5
    UnknownMethodError@chrome://remote/content/Error.jsm:108:7
    execute@chrome://remote/content/domains/DomainCache.jsm:96:13
```

**Use Case**

Right now, cookies don't work correctly in puppeteer due to missing headers https://github.com/puppeteer/puppeteer/issues/4918, so it's impossible to test an application that uses authentication. In order to make it work, I tried using this hack https://github.com/puppeteer/puppeteer/issues/4918#issuecomment-663478790 and it worked in Chrome but doesn't work in firefox.

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Linux
* URLs (if applicable):
* Node.js version: 12.16.2

**Comment by mjzffr** [comment]
The protocol implementation in Firefox doesn't include `Fetch.enable` yet. The tracking bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1587857

Similarly, the workaround you're trying depends on `Network.responseReceivedExtraInfo`, which also [not yet implemented in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1591937).

Feel free to [get in touch](https://wiki.mozilla.org/Remote) about your use case; it can help us prioritize.

**Comment by minupalaniappan** [comment]
I really really really need this too!

**Comment by hirokith** [comment]
I've tried playwright with firefox using Network: https://playwright.dev/docs/network#handle-requests and it worked perfectly, I'm wondering what playwright has done with firefox. According to their docs: https://playwright.dev/docs/browsers, seems that they compiled customized browser binaries to operate with playwright, and I've tried puppeteer firefox using playwright firefox binary and it did not work. I'm wondering if anyone could investigate what playwright has done with firefox to support this feature?

**Comment by Ranguna** [comment]
+1
@mjzffr  my use case is that I need to perform a POST on the initial request instead of the usual GET to get the page. The page that I'm parsing needs to get info from the caller through the POST body, which then returns a page.
My workaround for now will be to use chrome instead of firefox.

**Comment by Ranguna** [comment]
@stale please leave it as confirmed. It's being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1587857

EDIT: should I make a bot that adds a comment here every 29 days ?

**Comment by Timileyin105** [comment]
hello i am having same issue

**Comment by shubRaj** [comment]
Same Issue

**Comment by dembal1990** [comment]
Same issue with version 20.9.0

**Comment by whimboo** [comment]
We are not going to implement network request interception for the CDP protocol in Firefox, but will work on it soon for the WebDriver BiDi backend.

**Comment by 0x0480** [comment]
> We are not going to implement network request interception for the CDP protocol in Firefox, but will work on it soon for the WebDriver BiDi backend.

But why?

**Comment by whimboo** [comment]
CDP is not a cross-browser protocol and our support in Firefox was always experimental. We are actually going to deprecate it over the next months because WebDriver BiDi is in a much better shape right now. You can already [use WebDriver BiDi with Puppeteer](https://hacks.mozilla.org/2023/12/puppeteer-webdriver-bidi/).

**Comment by 0x0480** [comment]
@whimboo That's great news! But It seems like request interception still not implemented in puppeteer, right?

"[Network interception is currently done for Webdriver BiDi](https://bugzilla.mozilla.org/show_bug.cgi?id=1552326#c11)"

**Comment by whimboo** [comment]
Oh that's right. @OrKoN should be able to give more details when it might be available through Puppeteer.

**Comment by OrKoN** [comment]
Yes, we are working on it.
