### ISSUE TITLE
elementHandle.attribute doesn't work

### ISSUE THREAD

**Issue by volny** [puppeteer/puppeteer#636]
Calling `.attribute` on elementHandles doesn't work.
 Even the example at <https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleattributekey> results in a "TypeError: inputElement.attribute is not a function".

**Comment by vsemozhetbyt** [comment]
The doc can a bit outstrip the current npm version, so you can try to update this way to check new API methods:
```
npm install https://github.com/GoogleChrome/puppeteer/
```

**Comment by vsemozhetbyt** [comment]
`elementHandle.attribute()` may be deleted in the https://github.com/GoogleChrome/puppeteer/pull/638

**Comment by aslushnikov** [comment]
The `elementHandle.attribute()` got removed in favor of `page.$eval` method:

```js
const idAttribute = await page.$eval('.box', e => e.id);
```

**Comment by Swiffers** [comment]
How to do with a custom attribute? i.e: `attr-meta`

**Comment by aslushnikov** [comment]
@Swiffers just use `getAttribute`:

```js
const metaAttribute = await page.$eval('.box', e => e.getAttribute('attr-meta'));
```

**Comment by laggingreflex** [comment]
But how to get an attribute from a particular `elementHandle`? I've obtained an `elementHandle` and now want to get an attribute from that particular `elementHandle`. Is `page.$eval` able to do that?

**Comment by iamso** [comment]
@aslushnikov I have the same problem as @laggingreflex, I have a list of `elementHandle` obtained through `page.$$()` and I need to get an attribute from each `elementHandle` while looping through the list. When I pass the `elementHandle` it crashes and tells me it's not valid selector.

Is there another way of getting an attribute?

**Comment by pavelsmolka** [comment]
I have the same problem - I need to access attributes of a specific element that I have available as `elementHandle`. I can easily access children elements of this `elementHandle` by calling `myElement.$eval('child-selector'`, but I cannot access attributes of the element itself. Is there any work-around? If this is a new feature, shall I set up a new ticket?

**Comment by vsemozhetbyt** [comment]
@pavelsmolka I have tried XPath approach, but it throws:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const linkElement = await page.$('a[href]');
    const hrefAttribute = await linkElement.$x('./@href');
    const hrefAttributeValue = await (
      await hrefAttribute.getProperty('value')
    ).jsonValue();
    console.log(hrefAttributeValue);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
TypeError: hrefAttribute.getProperty is not a function
    at main (test.js:15:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by vsemozhetbyt** [comment]
This variant seems OK though:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    const linkElement = await page.$('a[href]');
    const hrefAttributeValue = await page.evaluate(
      link => link.getAttribute('href'),
      linkElement,
    );
    console.log(hrefAttributeValue);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```
http://www.iana.org/domains/example
```

**Comment by pavelsmolka** [comment]
That works perfectly, thank you so much!

**Comment by yaakovyitzchak** [comment]
Hi it doesn't seem to get all of the properties, for example how do I get source of an Iframe, doing this code: 
```

var puppeteer = require("puppeteer");

(async() => {
    var browser = await puppeteer.launch();
    console.log("Got browser", browser);
    var page = await browser.newPage();
    console.log(page,"got page");
    await page.goto("https://docs.google.com/file/d/1Cyuh41yNfYZU_zL-MHLf_EPJCYnlT7oJ/preview?enablejsapi=1&playerapiid=player4");
    console.log("went to page..");
    
  
    var clickEl = ".ndfHFb-c4YZDc-aTv5jf-bVEB4e-RJLb9c";
    await page.click(clickEl);
    console.log("clicked")
    var frame = await page.waitForSelector("iframe[id=drive-viewer-video-player-object-0]");
    var props = await frame.getProperties();
    console.log(frame, "got video frame, props: ", props);
)();
```
 only prints: `'got video frame, props: ' Map {}` even though I know there are tons of more DOM properties like src ??

**Comment by vsemozhetbyt** [comment]
@yaakovyitzchak If you run:
```js
Object.getOwnPropertyNames(document.querySelector('iframe[id=drive-viewer-video-player-object-0]'));
```
or
```js
Object.keys(document.querySelector('iframe[id=drive-viewer-video-player-object-0]'));
```
in the browser console, you will get empty arrays as well. It seems all these properties are prototype getters and maybe because of that they are not retrieved. You can try to get attributes:

```js
    var frame = await page.waitForSelector("iframe[id=drive-viewer-video-player-object-0]");
    var props = await page.evaluate(
      element => Array.from(element.attributes, ({ name, value }) => `${name}: ${value}`),
      frame
    );
    console.log(props);
```
```
[ 'id: drive-viewer-video-player-object-0',
  'src: https://youtube.googleapis.com/embed/?..',
  'frameborder: 0',
  'width: 100%',
  'height: 100%',
  'allowfullscreen: true',
  'mozallowfullscreen: true',
  'webkitallowfullscreen: true' ]
```
Or you can use `for...in` cycle in `page.evaluate()` to get all prototype properties.
