### ISSUE TITLE
Firefox: page.on('dialog') only gets triggered once

### ISSUE THREAD

**Issue by ritz078** [puppeteer/puppeteer#6360]
### Steps to reproduce 

Take the following code

```js
page.on('dialog', async dialog => {
   console.log(dialog.message()) // This will get caught
   await dialog.dismiss()
})

await page.evaluate(() => {
   alert("This will get caught")
   alert("This dialog will remain open and won't be caught by the handler")
})
```

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Linux
* URLs (if applicable):
* Node.js version: 12.16.2

**What is the expected result?**
Just like chrome `page.on("dialog")` should be triggered every-time a new dialog opens.

**What happens instead?**
It only gets triggered once.

**Comment by mjzffr** [comment]
Thanks for the report. This requires some extra investigation. It would be helpful to post trace-level logs of your run with Firefox as in this [example](https://github.com/puppeteer/puppeteer/blob/main/examples/cross-browser.js#L20)

**Comment by dpmott** [comment]
How is the first dialog getting dismissed?

**Comment by ritz078** [comment]
The "dialog" even listener dismisses it

```js
page.on('dialog', async dialog => {
   console.log(dialog.message()) // This will get caught
   await dialog.dismiss() // <= here
})
```
