### ISSUE TITLE
Page.setCookie() not working when value is mixed with characters of different types

### ISSUE THREAD

**Issue by hijiangtao** [puppeteer/puppeteer#6361]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-core@1.20.0, as well as puppeteer@5.2.1
* Platform / OS version: macOS
* URLs (if applicable): Not necessary
* Node.js version: v10.18.0

**What steps will reproduce the problem?**

1. Initialize puppeteer and get `page` object;
2. Set cookie with following codes:

```javascript
const fakeCookieObjectThatWouldRaiseError = [{
	domain: '.google.com',
	name: 'nickname',
	value: ' 你好'
}];

const fakeCookieObjectThatWouldPass = [{
	domain: '.google.com',
	name: 'nickname',
	value: ' 你好'
}];

const fakeCookieObjectThatWouldPassToo = [{
	domain: '.google.com',
	name: 'nickname',
	value: 'English'
}];

try {
	await page.setCookie(...[fakeCookieObjectThatWouldRaiseError]);
} catch (e) {
	console.log(e);
}
```

3. API with https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-pagesetcookiecookies

**What is the expected result?**

`setCookie` could work and set Cookie correctly.

**What happens instead?**

The calling failed with following message:

```
Protocol error (Network.setCookies): Invalid cookie fields
```

### Discussion

I could give several examples to explain the bug. Besides the example described above, we can see that the following `value` property with pure Chinese characters or pure English characters can both got the expected result.

So it's just a situation that when value is characters with space and Chinese characters mixed together.

```javascript
const fakeCookieObjectThatWouldPass = {
	domain: '.google.com',
	name: 'nickname',
	value: ' 你好'
};

const fakeCookieObjectThatWouldPassToo = {
	domain: '.google.com',
	name: 'nickname',
	value: 'English'
};

try {
	// This is OK.
	await page.setCookie(fakeCookieObjectThatWouldPass, fakeCookieObjectThatWouldPassToo);
} catch (e) {
	console.log(e);
}
```

**If it's designed to raise error at this situation**, I think it should be added to unit test cases https://github.com/puppeteer/puppeteer/blob/main/test/cookies.spec.ts 

Or we should make some judgements with user input parameters in `value` property, to forbid throw invalid error to users directly. 

Otherwise, I can just guarantee expected result with `encodeURIComponent` operation once I test `value` property contains Chinese characters:

```javascript
const getSafeCookieValue = (rawString: string): string => {
    if (/.*[\u4e00-\u9fa5]+.*/.test(rawString)) {
        return encodeURIComponent(rawString);
    } else {
        return rawString;
    }
};
```

**Comment by dimatomp** [comment]
I have a similar issue when trying to set a cookie containing binary data.
```
await page.setCookie({
  name: cookieName,
  value: new Buffer(cookieValueBase64, 'base64').toString()
});
```
Any suggestions how to supply this kind of cookies to the browser?

**Comment by hijiangtao** [comment]
@dimatomp As I said in the issue, maybe you could try `encodeURIComponent` API to see if your code works.

**Comment by dimatomp** [comment]
Did not work for me - the buffer could be sent but was not parsed on the recipient side.

I ended up converting the buffer into hex representation and then just putting '%' in between - it worked :)

```
let urlEncodedCookie = '';
for (let i = 0; i < cookieHex.length; i += 2)
  urlEncodedCookie += `%${cookieHex.substr(i, 2)}`;
await browser.setCookies({
  name: cookieName,
  value: urlEncodedCookie,
});
```

**Comment by AlfieGoat** [comment]
I have the same issue when trying to set a PEM public key as a cookie value. It seems to not like the `\n`s

**Comment by arthurwolf** [comment]
I have the same issue, latest npm install version, the cookie looks like this:

output of 

```
        console.log(cookies, 'cookies');
```

is:

```
[
  {
    name: 'app_opened',
    value: 'j��@�W\rmWh�\x15\x100�[censored]$\x16\x00�\n�\x19�J2r\x0F�\t���',
    expires: 0,
    domain: 'app.[censored].com',
    path: '/'
  }
] cookies
```

**Comment by outOFFspace** [comment]
@arthurwolf  try to add `secure: true` to the cookie object

**Comment by akash-k-fst** [comment]
> @arthurwolf try to add `secure: true` to the cookie object

This works for me, Thanks .
