### ISSUE TITLE
Browser.pages() doesn't resolve for headless mode in v.5.2.1

### ISSUE THREAD

**Issue by levent91** [puppeteer/puppeteer#6364]
My script is working without any problem with headless: false, but in v.5.2.1 it doesn't start in headless mode. I have tried different solutions, but only downgrading my puppeteer version to 4.0.1 solved my problem. I'm curious of the root cause of this problem if anyone experienced a similar issue. Is it related with other dependencies that I use?

My dependencies are as following:

    "express": "^4.17.1",
    "node-fetch": "^2.6.0",
    "puppeteer": "^4.0.1",
    "puppeteer-extra": "^3.1.13",
    "puppeteer-extra-plugin-stealth": "^2.5.0",
    "tesseract.js": "^2.1.1"

Thanks in advance.

**Comment by deepak-mali** [comment]
We have same issue. Websites are not loading in headless mode but it loads in headless:false mode.
