### ISSUE TITLE
CSS "break-inside: avoid" is ignored when generating a PDF in headless mode.

### ISSUE THREAD

**Issue by joergd** [puppeteer/puppeteer#6366]
* Puppeteer version: 5.2.1
* Node.js version: 12.6.2

I am generating a multi-page PDF document.

I am using the following to ensure that the block element is not cut off at the page break:

```
.wrapper {
    float: left;
    break-inside: avoid;
}
```

I have set up other paged media stuff using `@page` (for instance using that to switch the page size from A4 to A3) to see that Puppeteer can deal with paged media. When I set these `@page` media queries, the resulting PDF is affected.

BUT my .wrapper block elements get cut off?

I have tried this with Pupetteer both emulating the screen and print. I get the same results. I have also tried to just print HTML page on Chrome - and the resulting PDF looks the same as on Puppeteer.

Is there something I am missing in my setup?

**Comment by joergd** [comment]
The problem was that the container element for my .wrapper elements was an inline-block.

This is by design according to the specification: https://www.w3.org/TR/css-break-3/#end-block

**Comment by vasco3** [comment]
I'm having this issue with flex and grid. Any ideas of what could be disabling `break-inside: avoid`? It works when I print from the browser to Pdf, but not when I use puppeteer pdf
