### ISSUE TITLE
page.$x returns elements which are not HTMLElement

### ISSUE THREAD

**Issue by DonaldRich** [puppeteer/puppeteer#6367]
### Steps to reproduce

The following code is executed:

let frames = await page.frames();
let frame = frames[2];                                       // After a check that frames has a third element
const elements = await frame.$x("//a");           // 58 elements returned
if(elements.length > 0) {
	await elements[0].click({delay: 500}).catch((error) => console.log(error));
}

resulting in the following error:

Error: Node is not of type HTMLElement

The elelement has the following attributes:
elements["0"] = ElementHandle {_disposed: false, _context: , _client: , _remoteObject: , _page: , ...}
 _client = CDPSession {eventsMap: , emitter: , _callbacks: , _connection: , _targetType: "page", ...}
 _context = ExecutionContext {_client: , _world: , _contextId: 13}
 _disposed = false
 _frameManager = FrameManager {eventsMap: emitter: , _frames: , _contextIdToContext: , _isolatedWorlds: , ...}
 _page = Page {eventsMap: , emitter: , _closed: false, _timeoutSettings: , _pageBindings: , ...}
 _remoteObject 
               className = "HTMLAnchorElement"
               description = "a#PageHeaderControl_lnkCorporateSite"
               objectId = "{"injectedScriptId":13,"id":3}"
               subtype = "node"
               type = "object"

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Windows 10 Home
* URLs (if applicable):
* Node.js version: v12.18.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

Above

**What is the expected result?**

Calling click() on the element should work.

**What happens instead?**

Calling click() on the element throws an error that the element is not of type HTMLElement. The element is of type HTMLAnchorElement instead of type HTMLElement.

**Comment by vsemozhetbyt** [comment]
Could there be that a click on a link triggers navigation so that another link is not available anymore and we just get a confusing error message?

**Comment by joshgrime** [comment]
The code for returning elements from XPATH is [here](https://github.com/puppeteer/puppeteer/blob/7b24e5435b8450a99445149e3395ac0642ca574e/src/common/JSHandle.ts#L922-L947):

```
  async $x(expression: string): Promise<ElementHandle[]> {
    const arrayHandle = await this.evaluateHandle(
      (element: Document, expression: string) => {
        const document = element.ownerDocument || element;
        const iterator = document.evaluate(
          expression,
          element,
          null,
          XPathResult.ORDERED_NODE_ITERATOR_TYPE
        );
        const array = [];
        let item;
        while ((item = iterator.iterateNext())) array.push(item);
        return array;
      },
      expression
    );
    const properties = await arrayHandle.getProperties();
    await arrayHandle.dispose();
    const result = [];
    for (const property of properties.values()) {
      const elementHandle = property.asElement();
      if (elementHandle) result.push(elementHandle);
    }
    return result;
  }
```

It is just returning all of the elements picked up by your XPATH selector. I don't think it is up to Puppeteer to have an opinion on the types of elements returned by this $x function.

However, digging a bit deeper, there is an additional function called as part of `elementHandle.click()` in [JSHandle.ts](https://github.com/puppeteer/puppeteer/blob/main/src/common/JSHandle.ts#L492-L496):

**elementHandle.click()**

```
    async click(options: ClickOptions = {}): Promise<void> {
    await this._scrollIntoViewIfNeeded();
    const { x, y } = await this._clickablePoint();
    await this._page.mouse.click(x, y, options);
  }
```

**_scrollIntoViewIfNeeded()** [link](https://github.com/puppeteer/puppeteer/blob/main/src/common/JSHandle.ts#L365-L410)

```
  private async _scrollIntoViewIfNeeded(): Promise<void> {
    const error = await this.evaluate<
      (
        element: Element,
        pageJavascriptEnabled: boolean
      ) => Promise<string | false>
    >(async (element, pageJavascriptEnabled) => {
      if (!element.isConnected) return 'Node is detached from document';
      if (element.nodeType !== Node.ELEMENT_NODE)
        return 'Node is not of type HTMLElement';
```

It looks like this is where your error message is coming from. The `click()` is not the issue, the element check in `_scrollIntoViewIfNeeded()`, which is called by `click()` is causing it to fail.

I am not sure why `element.nodeType !== Node.ELEMENT_NODE` is evaluating as false for your `HTMLAnchorElement`s.

Indeed, running the following in a console with links on the page console.logs true every time:

```
var iterator = document.evaluate(
          "//a",
          document,
          null,
          XPathResult.ORDERED_NODE_ITERATOR_TYPE
     );
var array = [];
let item;
while ((item = iterator.iterateNext())) array.push(item);

for (let x of array) {
    console.log(x.nodeType === Node.ELEMENT_NODE);
}
```

However, this is not in the Puppeteer environment, so I will do some more digging later and see if I can find anything.

**References**
- [HTMLAnchorElement Reference](https://html.spec.whatwg.org/multipage/text-level-semantics.html#htmlanchorelement)
- [Node type list](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType)

**Comment by DonaldRich** [comment]
Yes, I found the code you quote in JSHandle method _scrollIntoViewIfNeeded.

If I comment out the check for element.nodeType !== Node.ELEMENT_NODE the
click function works fine. It seems that minimally the test is overly
restrictive since the click() function works even if the test fails in the
original code.

Thank you.

**Comment by thiagodelgado111** [comment]
Hey folks, having the same issue:

```
Error: Node is not of type HTMLElement
    at ElementHandle._scrollIntoViewIfNeeded
```

It happens when I do:

```
const submitButton = await page.waitForXPath(SUBMIT_BUTTON, {
  visible: true,
});

await submitButton.click();
```

If I do:

```
await page.evaluate($submit => $submit.click(), submitButton)
```

It works! I think it's related to how `$x` works. Would it be ok to map `$x` array to something like that? :point_up:

**Comment by Rupeshiya** [comment]
Hey can anyone please have a look at it?
I am facing issue in detecting disabled button
https://stackoverflow.com/questions/66541493/how-to-check-the-disabled-property-on-an-element-handle-in-puppeteer

**Comment by sepehr** [comment]
Seconding this.

**Comment by tophep** [comment]
For those still struggling with this, here is a workaround if you know your node is definitely an HTMLElement 
`await (elements[0] as ElementHandle<HTMLElement>).click();`
