### ISSUE TITLE
Protocol error (Page.printToPDF): Show invalid printer settings error, thrown while printing pdfs

### ISSUE THREAD

**Issue by dbonchev42** [puppeteer/puppeteer#6368]
### Steps to reproduce
* Puppeteer version: 6.14.7
* Platform / OS version: Ubuntu 18.04.5 LTS
* Node.js version: v14.8.0
* local-chromium: linux-782078

**Prerequisites**
Have two similar methods, which generate pdf, calling page.pdf()
Example functions:
```
async printFolderQrCode(folderId) {
    const page = await this.openNewPage();
    const pdfPath = ...;

    const uri = new URL(...t);
    uri.search = ...;

    await page.goto(uri);
    await page.pdf({ path: pdfPath });
    await page.close();
    return pdfPath;
  }
`
`
  async printDocumentTypeQrCodes() {
    const page = await this.openNewPage();
    const pdfPath = ...;

    const uri = new URL(...);
    uri.search = ...;

    await page.goto(uri);
    await page.pdf({ path: pdfPath });
    await page.close();

    return pdfPath;
  }
```
**Execution**
Executed the functions in both ways sync and async (using Promeise.all()) 

**Expected result?**
Two pdfs are stored on the fs, and the methods return their paths. 

**Actual result**
Sometimes, the execution results in failure, with exception thrown:
```  
Error: Protocol error (Page.printToPDF): Show invalid printer settings error
      at /home/dbonchev/Documaster/wfc/software/automation/wfc-test-automation/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
      at new Promise (<anonymous>)
      at CDPSession.send (node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
      at Page.pdf (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1152:43)
```

**In 2/3 of the executions, everything is OK, and pdfs are printed, but in 1/3 of the cases the error above is thrown.**
This anomaly has appeared, once I updated the puppeteer version @latest.

**Comment by koga021** [comment]
I Have this problem. 1/3 of my run app return this erros. aleatory error, but i create a png.
```
at Page._screenshotTask (/home/application/current/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1152:43)
2020-10-14 00:01:28 -0300 [crontab][66bc8ca1e2cb]: at runMicrotasks (<anonymous>)
2020-10-14 00:01:28 -0300 [crontab][66bc8ca1e2cb]: at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-10-14 00:01:28 -0300 [crontab][66bc8ca1e2cb]: (Use `node --trace-warnings ...` to show where the warning was created)
2020-10-14 00:01:28 -0300 [crontab][66bc8ca1e2cb]: (node:223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-10-14 00:01:28 -0300 [crontab][66bc8ca1e2cb]: (node:223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by joamag** [comment]
I'm also seeing this non-deterministic behavior while trying to print PDF with version 5.3.1.

**Comment by koga021** [comment]
To resolve my problem, im using many of code (try/catch) validation and looping.
Every important code, im using while with try/catch , and break with my code if it not return error on my try catch.
Following this way, every error returned maping or not, go to my initial global looping and make all again and again.
```
async function(){
//global while true
while (true){
   try{
      //And more while(true) with try/catch with all parts of my code
     ///await puppeteer.launch , await page.goto, cut imagem, sender to s3, and database connection
     // all importants code i using while with try catch.
    break;
   }
   catch(error) {
      console.log("error, repeat all! initial code")
            
}


}

```



}

**Comment by dbonchev42** [comment]
> To resolve my problem, im using many of code (try/catch) validation and looping.
> Every important code, im using while with try/catch , and break with my code if it not return error on my try catch.
> Following this way, every error returned maping or not, go to my initial global looping and make all again and again.
> 
> ```
> async function(){
> //global while true
> while (true){
>    try{
>       //And more while(true) with try/catch with all parts of my code
>      ///await puppeteer.launch , await page.goto, cut imagem, sender to s3, and database connection
>      // all importants code i using while with try catch.
>     break;
>    }
>    catch(error) {
>       console.log("error, repeat all! initial code")
>             
> }
> 
> 
> }
> ```
> 
> }

This is really bad approach, which could lead to infinity loop

**Comment by gcandal** [comment]
This seems to be a problem with the Ubuntu driver, using anything else such as Debian, Windows or macOS solved the issue for us.

**Comment by joamag** [comment]
Found the original problem: We were calling `window.print()` at the start of the document load which creates a collision between puppeteer trying to "print" a PDF and the printing dialog created by Javascript call (`window.print()`).

**Comment by Gaius10** [comment]
> To resolve my problem, im using many of code (try/catch) validation and looping. Every important code, im using while with try/catch , and break with my code if it not return error on my try catch. Following this way, every error returned maping or not, go to my initial global looping and make all again and again.
> 
> ```
> async function(){
> //global while true
> while (true){
>    try{
>       //And more while(true) with try/catch with all parts of my code
>      ///await puppeteer.launch , await page.goto, cut imagem, sender to s3, and database connection
>      // all importants code i using while with try catch.
>     break;
>    }
>    catch(error) {
>       console.log("error, repeat all! initial code")
>             
> }
> 
> 
> }
> ```
> 
> }

I liked this approach, to avoid infinity loop just add 

```
let i = 0;
while (i++ < 3) { ... }
```

**Comment by dbdocumaster** [comment]
As [joamag](https://github.com/joamag) said, issue is caused because of the print modal open by js, once the page is loaded
> Found the original problem: We were calling `window.print()` at the start of the document load which creates a collision between puppeteer trying to "print" a PDF and the printing dialog created by Javascript call (`window.print()`).

In my case, calling `await page.setJavaScriptEnabled(false); ` before calling `await page.goto(uri);` solved the issue. By disabling JS on the page, before opening it, you block the print modal, which is causing this behavior.
