### ISSUE TITLE
Clicking a button within an iframe with puppeteer

### ISSUE THREAD

**Issue by nostar3** [puppeteer/puppeteer#6369]
Trying to click on the "I accept all cookies" button which is inside iFrame (The popup only show for EU country ip).
You can check here also jsfiddle.net/#&togetherjs=VgKpE0jfJF.

[![enter image description here][2]][2]

```
//index.js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless:false,
      ignoreHTTPSErrors: true,
      slowMo: 50,
      args: ['--window-size=1440,900', '--disable-gpu', "--disable-features=IsolateOrigins,site-per-process", '--blink-settings=imagesEnabled=true']
    });
  const page = await browser.newPage();
  await page.goto('https://www.oracle.com/cloud/cost-estimator.html');

  await page.waitFor(3000)
  const frame = page.frames().find(f => f.name() === 'iframe');
  const acceptBtn = await frame.$(`a[class="call"]`);
  await acceptBtn.click();

  await page.screenshot({path: 'example.png'});

  //await browser.close();
})();
```
The error i get

````
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '$' of undefined
    at
````

Please help. Thanks

  [2]: https://i.stack.imgur.com/W2rfv.png

**Comment by vsemozhetbyt** [comment]
As far as I can tell, this iframe has no name in the HTML code, so you can try its src (URL):

```js
const frame = page.frames().find(f => f.url().startsWith('https://consent-pref.trustarc.com/'));
```

**Comment by Azooze0533** [comment]
Hdhhs

**Comment by Azooze0533** [comment]
https://github.com/password_reset/AQYYMM672I6FR3QTTGP7AOS7JC43RBFFMVWWC2LMWFEXAMJRHA2EA2LDNRXXKZBOMNXW3JLGN5ZGGZOCWN2HO327MZQWG5DPOJPXMZLSNFTGSZLEYK5GM33SMNSWIX3XMVQWWX3QMFZXG53POJSF64TFONSXJQQ

**Comment by nostar3** [comment]
> As far as I can tell, this iframe has no name in the HTML code, so you can try its src (URL):
> 
> ```js
> const frame = page.frames().find(f => f.url().startsWith('https://consent-pref.trustarc.com/'));
> ```

Perfect, Thanks
