### ISSUE TITLE
How to block WebRtc?

### ISSUE THREAD

**Issue by s3rgeym** [puppeteer/puppeteer#6377]
How to block WebRtc or block all UDP traffic?

* headless true
* without extensions

**Comment by ClericPy** [comment]
Page.addScriptToEvaluateOnNewDocument

'navigator.mediaDevices.getUserMedia = navigator.webkitGetUserMedia = navigator.mozGetUserMedia = navigator.getUserMedia = webkitRTCPeerConnection = RTCPeerConnection = MediaStreamTrack = undefined;'

https://github.com/puppeteer/puppeteer/issues/4149#issuecomment-550333435

**Comment by liteCarma** [comment]
It is better to create a small extension. Because, the solution option that is above can cause errors and arouse suspicion
manifest.json
`{
    "name": "private",
   "background": {
      "scripts": ["./background.js"],
      "persistent": false
   },
   "version": "1.0",
   "manifest_version": 2,
   "permissions": [ "privacy" ]
}
`
background.js
`chrome.privacy.network.webRTCIPHandlingPolicy.set({
  value: 'disable_non_proxied_udp'
});
`

**Comment by aditodkar** [comment]
@liteCarma With new headless puppeteer + proxies I am not able to hide IP address. Any suggestions? I tested on pixelscan but it shows location is being spoofed or IP adddress leaked on webrtc test page.

**Comment by wilsonssss** [comment]
> @liteCarma With new headless puppeteer + proxies I am not able to hide IP address. Any suggestions? I tested on pixelscan but it shows location is being spoofed or IP adddress leaked on webrtc test page.

the same problem

**Comment by skateeveryday10** [comment]
> @liteCarma With new headless puppeteer + proxies I am not able to hide IP address. Any suggestions? I tested on pixelscan but it shows location is being spoofed or IP adddress leaked on webrtc test page.

Me too, I have been searching for a fix for this on headless browser for ages. Nothing seems to work
