### ISSUE TITLE
Error: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by xukaisjz** [puppeteer/puppeteer#6380]
use command "timecut replay.html --viewport=800,600 --fps=60 --duration=5 --frame-cache --output=video.mp4"

result:
Capturing Frame 297 to D:\makevideo\timecut-temp-1598920084322\image-000000297.png...
Capturing Frame 298 to D:\makevideo\timecut-temp-1598920084322\image-000000298.png...
Capturing Frame 299 to D:\makevideo\timecut-temp-1598920084322\image-000000299.png...
Capturing Frame 300 to D:\makevideo\timecut-temp-1598920084322\image-000000300.png...
Elapsed capture time: 84681
[0901/082936.815:WARNING:gpu_process_host.cc(1165)] The GPU process has crashed 1 time(s)
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-framerate',
    60,
    '-i',
    'D:\\makevideo\\timecut-temp-1598920084322\\image-%09d.png',
    '-pix_fmt',
    'yuv420p',
    '-y',
    'D:\\makevideo\\video.mp4'
  ]
}

**Comment by sllark** [comment]
Hi there, I am getting the same error.
Can you let me know if you fixed the error?

**Comment by xukaisjz** [comment]
Install ffmpeg on your computer

**Comment by sllark** [comment]
thanks, the error is gone.
