### ISSUE TITLE
Page freezes and return TimeoutError

### ISSUE THREAD

**Issue by 0snilcy** [puppeteer/puppeteer#6381]
### Steps to reproduce

* Puppeteer version: 5.2.1
* Platform / OS version: MacOS Catalina 10.15.6
* Node.js version: 13.13.0

**What steps will reproduce the problem?**

```js
this.browser = await puppeteer.launch();
this.page = await this.browser.newPage();

await this.page.setRequestInterception(true);

// this.page.on('request', (request) => request.continue());

this.page.on('domcontentloaded', () => console.log('domcontentloaded'));
this.page.on('load', () => console.log('load'));

await this.page.goto(`http://localhost:8080/`);
```

**Question?**
Is it normal, if i try navigate to page with `setRequestInterception(true);` without `request` event and page freezes and return TimeoutError?

**Comment by spiceee** [comment]
Yes. `setRequestInterception` requires you to handle the request event and either continue or abort it.

**Comment by 0snilcy** [comment]
It was unexpected for me, and I spent some time on the solution,
thanks for the answer.
