### ISSUE TITLE
Please allow puppeteer-core to use PUPPETEER_* env variables

### ISSUE THREAD

**Issue by jhudson8** [puppeteer/puppeteer#6387]
* Puppeteer version: puppeteer-core@2.1.1
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 12.9.1

**What steps will reproduce the problem?**

1. simulate a firewall (block the chromium CDN)
2. set the following environment variables
      PUPPETEER_EXECUTABLE_PATH = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = true
2. Create a storybook (https://github.com/storybookjs)
      `npx -p @storybook/cli sb init`
3. Build the storybook
      `node ./node_modules/@storybook/react/dist/server/build.js -s public`
4. Use the Storybook "extract" functionality to get JSON metadata
      `node ./node_modules/@storybook/cli/bin/index.js extract`

**What is the expected result?**
The storybook json file to be created

**What happens instead?**
puppetteer-core fails because it doesn't support PUPPETTEER_* environment variables
https://github.com/puppeteer/puppeteer/blob/main/src/node/Launcher.ts#L748

I have no ability to update the firewall rules and can't make storybook use puppetteer instead of puppetteer-core.

**Comment by cardner** [comment]
I'm having a similar issue when attempting to use the extract function as part of our CI tooling which explicitly doesn't allow install processes to reach out to external networks.
