### ISSUE TITLE
Puppeteer: element is visible, yet `page.waitForSelector` says it is NOT

### ISSUE THREAD

**Issue by stoplion** [puppeteer/puppeteer#6389]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: OS X
* URLs (if applicable):
* Node.js version: 10.22

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
await page.waitForSelector(".test", {
  visible: true,
});
```

I'm setting `headless: false`. 

I'm looking right at `.test` in the DOM of launched browser window.

And yet..

```
await page.waitForSelector(".test", {
  visible: true,
});
```

Never resolves. Why?

**OK, Let's try this another way..**

```
const d = await page.waitForSelector(".test", {
  timeout: 1222,
});
debugger;
try {
  await d.click(".test");
} catch (e) {
  debugger;
  console.log(e);
}
```

Again...

`Error: Node is either not visible or not an HTMLElement`

I'm SEEING `.test` element with my eyes. It's there. 

WHY does this fail??

**Comment by vsemozhetbyt** [comment]
Can it be that the element is inside an iframe?

**Comment by stoplion** [comment]
It's the table on https://coinmarketcap.com/
Doesn't appear to be in an iframe

**Comment by vsemozhetbyt** [comment]
Could you provide a minimal code that reproduces the issue?

**Comment by niveinii** [comment]
might just be a shot in the dark but try setting the viewport to a full screen:

`await page.setViewport({width: 1860, height: 1400});`

**Comment by zoffyzhang** [comment]
try `waitForFunction`, it works for me

```
const selector  = '.test'
await page.waitForFunction(selector => !!document.querySelector(selector), {}, selector);
```

**Comment by nickkarikh** [comment]
Confirm, same issue

**Comment by attila226** [comment]
I encountered a scenario where having an alert dialog messed up the `waitForSelector`. Not sure if it applies to others, but for me removing the alert rectified the issue for me.

**Comment by RenanGalvao** [comment]
Same here. But I found out something that might help you. Changing the page userAgent made it work for me. I don't know exactly what is going on here, but maybe the webpage render differently based on userAgent?

`await page.setUserAgent('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4427.0 Safari/537.36')`;

**Comment by JuanDSG** [comment]
Same issue!!! Nothing yet?

**Comment by Eyewais** [comment]
Same issue here, what can be the reason for this? Anyone able to find a fix so far?

**Comment by OrKoN** [comment]
Generally, the could be multiple reasons for this to fail: 1) the element is outside of the viewport 2) there are multiple elements with the same selectors and the one that gets queried for is not visible 3) the element has zero width/height but has visible children. Without a specific repro it's hard to say if there is a bug. Also, we have tests for this functions so it's working in general, but I won't rule out some edge cases. So please re-open the issue with a repro if it still happens in the latest version.

**Comment by cipri-tom** [comment]
@OrKoN that's amazing insight ! Thank you ! 

Especially point 2): 

> there are multiple elements with the same selectors and the one that gets queried for is not visible

I was under the impression that adding `{visible: true}` will choose among all the possible elements matching the selector the one that is visible. If this is not the case, it explains exactly why it's not working for me. 

Can you please detail how puppetteer decides which one to query ? 

And what would be the workaround? Currently, I do `page.$$(selector)` and then filter myself for visible:

```js
    const tables = await page.$$(selector);
    const visibleTables = [];
    for (let table of tables)
        if (await table.boxModel())
            visibleTables.push(table);

    if (visibleTables.length !== 1) {
        console.error('Wrong... exiting');
        process.exit(1);
    }
    const table = visibleTables[0];
```

I'd love if this was part of default API

**Comment by OrKoN** [comment]
@cipri-tom the visibility check is just not part of the CSS selector and the general algorithm for waitForSelector is to wait for an element matching the selector and then for the other conditions. The use case for this it to wait for the element identified by the selector to be visible, not to find an element that is visible and matching the selector.

**Comment by LucBerge** [comment]
> might just be a shot in the dark but try setting the viewport to a full screen:
> 
> `await page.setViewport({width: 1860, height: 1400});`

It fixed it for me but I do not understand why.

----------------

[Here is the `setViewPort` implementation](https://github.com/puppeteer/puppeteer/blob/0b0a74b10d8ef06b6694d8ac56f20da6598dc9e2/packages/puppeteer-core/src/bidi/Page.ts#L354).

The page is reloaded on condition at the bottom but In my case reloading the page instead of setting the viewport does not work.

**Comment by LucBerge** [comment]
I my case, the action I perform before the `waitForSelector` is a click on the UI. This click triggers navigation.
The solution is to `waitForNavigation` to be done before waiting.
````javascript
element.click();
page.waitForNavigation();
page.waitForSelector(selector);
```

**Comment by LucBerge** [comment]
If the element your are looking for is in an iframe, it is possible that puppeteer does not see it.
To solve this, do a race between frames, `page.frames()` already includes the main frame.

```typescript
const element = await Promise.race(
    page.frames().map(frame =>
        frame.waitForSelector(selector)
    )
);
```

**Comment by LucBerge** [comment]
I made a new investigation:

[`setViewport`](https://github.com/puppeteer/puppeteer/blob/faf18095aeb31839893673c247a30743ae23fd80/packages/puppeteer-core/src/bidi/Page.ts#L398) calls [`reload`](https://github.com/puppeteer/puppeteer/blob/faf18095aeb31839893673c247a30743ae23fd80/packages/puppeteer-core/src/bidi/Page.ts#L300) that reloads the DOM **with ignore cache set to true**.

So puppeteer is just getting the DOM from the cache instead of the real DOM that contains the newly dynamically added element... the solution is just to disable cache at the start when you open the page.

```javascript
await page.setCacheEnabled(false);
```
