### ISSUE TITLE
Error: Response body is unavailable for redirect responses

### ISSUE THREAD

**Issue by phanminhtai** [puppeteer/puppeteer#6390]
Hi, I am trying to use `response.buffer()` to download images redirected from http to https and get the error: `Response body is unavailable for redirect responses.`

It looks like puppeteer can't do this. Is there any way? Thanks!

![image](https://user-images.githubusercontent.com/53898609/92191445-054e3680-ee8e-11ea-855b-1603dfd13524.png)

**Comment by yonixw** [comment]
Maybe this will help? https://stackoverflow.com/a/48988718/1997873
![image](https://user-images.githubusercontent.com/5826209/99653962-5e2b7500-2a62-11eb-857d-552fc06020b1.png)

**Comment by CryptoDeDesign** [comment]
> Maybe this will help? https://stackoverflow.com/a/48988718/1997873 ![image](https://user-images.githubusercontent.com/5826209/99653962-5e2b7500-2a62-11eb-857d-552fc06020b1.png)

but i still get random errors

for example
```

C:\Users\<yourname>\Documents\<project name>\node_modules\puppeteer-core\lib\cjs\puppeteer\common\HTTPResponse.js:143
                    return Buffer.from(response.body, response.base64Encoded ? 'base64' : 'utf8');
                                                ^

TypeError: Cannot read properties of undefined (reading 'body')
    at C:\Users\<yourname>\Documents\<project name>\node_modules\puppeteer-core\lib\cjs\puppeteer\common\HTTPResponse.js:143:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I think that it is impossible to handle errors correctly and it is better to wrap them in something like this

```
const body = await response.buffer().catch(() => {});
if (!body) {
    return;
}
```
