### ISSUE TITLE
I have a local chromium，but failed to launch

### ISSUE THREAD

**Issue by Chinvaejay** [puppeteer/puppeteer#6392]
* Puppeteer version: 5.2.1
* Platform / OS version: mac
* URLs (if applicable):
* Node.js version: 13.14

I have a local chromium. 
when I run the command
`UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /Applications/Chromium.app EACCES`

**Comment by JanVanOostenrijk** [comment]
I had the same problem and found a solution for it.
You defined the application package as the path. You need, however, need to point to the binary.

It should be here: "/Applications/Chromium.app/Contents/MacOS/Chromium"
