### ISSUE TITLE
Firefox: page.on('console') returns array of messages instead of string

### ISSUE THREAD

**Issue by voluntadpear** [puppeteer/puppeteer#6393]
### Steps to reproduce

Take the following code

```js
page.on('console', msg => {
  console.log(msg.text());
});
```

On Chrome, the `text()` method returns a string (as expected according to [the docs](https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-consolemessagetext).

On Firefox, it returns an array containing the string.

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Linux
* URLs (if applicable):
* Node.js version: 12.16.2

**What is the expected result?**

The `consoleMessage.text()` method returns a string, as specified in the docs.

**What happens instead?**

On Firefox, it returns an array.

**Comment by mjzffr** [comment]
Thanks for the report. This is covered by https://github.com/puppeteer/puppeteer/issues/6255
