### ISSUE TITLE
download firefox and chrome binaries together

### ISSUE THREAD

**Issue by CyberT33N** [puppeteer/puppeteer#6395]
I´am able to download firefox binaries for my project by set the environment variable:
```bash
npm config set PUPPETEER_PRODUCT firefox npm i puppeteer
```

Then inside of my project I run:
```bash
npm i puppeteer
```

This works fine. However when I change it back to chrome and reinstall it:
```bash
npm config set PUPPETEER_PRODUCT chrome npm i puppeteer
npm i puppeteer
```

It will delete the firefox binaries and only install chrome again. I tried to run **npm update** after switching the **PUPPETEER_PRODUCT** environment variable however this doesn´t work and nothing gets updated.

How can I download firefox and chrome binaries together? That I can easily switch the product value?
```javascript
client = await puppeteer.launch({  product: 'firefox'  }); // or product: 'chrome'
```

Please notice that I can not just create a hello world project and set **product: 'firefox'** because the binaries does not exist and will not automatically downloaded. For any default puppeteer install only the chrome binaries will exist. 

Switching to firefox won´t work until you change the environment variable **PUPPETEER_PRODUCT** to **firefox** and reinstall puppeteer and download the firefox binaries.

**Comment by CyberT33N** [comment]
As it seems you can only not use on windows this command via terminal:
- PUPPETEER_PRODUCT=firefox npm install puppeteer

On linux you can run the command above and it will download the binaries. There is actually no need to use this on linux:
- npm config set PUPPETEER_PRODUCT firefox npm i puppeteer

**Comment by fregante** [comment]
Firefox is not downloaded next to Chrome, see https://github.com/puppeteer/puppeteer/issues/8215#issuecomment-1157299074

**Comment by bmaupin** [comment]
To download Chromium and Firefox at the same time:

> ```shell
> npm install puppeteer
> ```
> 
> This will install puppeteer and download chromium by default. Chromium will be put in `node_modules/puppeteer/.local-chromium`
> 
> ```shell
> cd node_modules/puppeteer
> PUPPETEER_PRODUCT=firefox node install.js
> ```
> 
> This will download firefox. Firefox will be put in `node_modules/puppeteer/.local-firefox`

Source: https://github.com/puppeteer/puppeteer/issues/5743#issuecomment-621664876
