### ISSUE TITLE
waitForSelector timeout option doesnt work with variables

### ISSUE THREAD

**Issue by IIRobotNinjaII** [puppeteer/puppeteer#6396]
I keep trying to use a variable as the timeout value but it never seems to work.

var b = data1.raw_time.split(' ');
console.log(b[1]);
let time = parseInt(b[1], 10) * 60000;
console.log(time);
message.channel.send('Server is in queue for ' + b[1] + ' minutes!');

try {
    await page.waitForSelector('.main #confirm', { timeout: time });
    await page.click('.main #confirm');
} catch (error) {
    message.channel.send('Server start sequence was aborted');
}
    }
Am i doing something wrong ? Thanks again.

**Comment by Sav-bit** [comment]
What's the error you're getting? and what's the outputs of the console logs?

Because i tried

`  let c = parseInt('2',10) * 60 * 1000;
  try{
    await page.waitForSelector('.fakeselector', { timeout: c });
  }catch (e){
    console.log('error', e);
 }`

and i got the error

`error TimeoutError: waiting for selector ".fakeselector" failed: timeout 120000ms exceeded`

which it was what i expected.

**Comment by dinhitcom** [comment]
I have the same issue with `puppeteer v20.1.0`.
When I use `waitForSeletor` with `timeout` option and pass the selector as a string variable it doesnt working. If I change the selector to an explicit string `#tcmst > table` it works, or if I remove the timeout option, it works.

- Not working:
```
const SELECTOR = {
    resultTable: '#tcmst > table'
}
let resultTable = await page.waitForSelector(SELECTORS.resultTable, {
     timeout: 1000,
 });
```
- Works:
```
let resultTable = await page.waitForSelector("#tcmst > table", {
     timeout: 1000,
 });
```
- Works:
```
const SELECTOR = {
    resultTable: '#tcmst > table'
}
let resultTable = await page.waitForSelector(SELECTORS.resultTable);
```
