### ISSUE TITLE
Element handles don't invalidate when the elements are removed from the DOM

### ISSUE THREAD

**Issue by twalpole** [puppeteer/puppeteer#640]
If the DOM elements that ElementHandle instances refer to are removed the DOM the ElementHandle doesn't know about it.  Is there any way to invalidate the handles once the DOM nodes are no longer part of the document?

```

const puppeteer = require('puppeteer');

(async() => {

const browser = await puppeteer.launch({headless: false});
const page = await browser.newPage();
await page.goto('https://github.com/GoogleChrome/puppeteer', {waitUntil: 'networkidle'});

const header = await page.$('.repohead-details-container');

let html = await header.evaluate( el => { return el.innerHTML; })
console.log(html);

await header.evaluate( el => { el.parentNode.removeChild(el); })
console.log("element gone ================= ")

html = await header.evaluate( el => { return el.innerHTML; });
console.log(html);
})();
```

**Comment by JoelEinbinder** [comment]
I'm curious as to how this would help you. The element still exists even though it is detached from DOM. What if it gets removed and re-added?

**Comment by twalpole** [comment]
@JoelEinbinder In the given example it can't actually be re-added, since there is no reference kept to it in the browser (but yes in some cases it may be removed and readded).  However, the only reason the element is still around in the example shown is because puppeteer maintains a reference to it, and I don't think that really makes sense.  It definitely gets in the way of automation tools knowing whether or not elements are still in the page without having to query for the same elements every time we want to use them, thereby killing performance, and still having a race condition that the element is removed from the document after finding it but before evaluating something on it.

**Comment by aslushnikov** [comment]
>  having a race condition that the element is removed from the document after finding it but before evaluating something on it.

This race condition is inherent to element handle design: element handles live out-of-process to the elements they represent. If you want to avoid this race condition, you should use `page.evaluate`: 

```js
await page.evaluate(() => {
  const element = document.querySelector('container');
  if (!element)
    throw new Error('Element not found!');
  return element.textContent;
});
```

> Is there any way to invalidate the handles once the DOM nodes are no longer part of the document?

If you're unsure of the state of element handle, you can check state in the beginning of `elementHandle.evaluate` method:

```js
await elementHandle.evaluate(e => {
  if (!e.ownerDocument.contains(e))
    throw new Error('Element got detached from dom!');
  // ...
});
```

Note: in a lot of cases it's totally valid to call methods on detached elements; e.g. in your case `el.innerHTML` makes sense:

```js
html = await header.evaluate( el => { return el.innerHTML; });
console.log(html);
```

**Comment by lvkins** [comment]
@aslushnikov 
I'm currently coding element staleness check method and thought of `el.isConnected` method... wouldn't it be faster in opposite to `el.ownerDocument.contains(el)`?

```
await elementHandle.evaluate(el => {
  if (!el.isConnected)
    throw new Error('Element got detached from dom!');
  // ...
});
```

**Comment by aslushnikov** [comment]
> I'm currently coding element staleness check method and thought of el.isConnected method... wouldn't it be faster in opposite to el.ownerDocument.contains(el)?

@lvkins definitely faster!

**Comment by avimar** [comment]
> await elementHandle.evaluate(el => {
>   if (!el.isConnected)
>     throw new Error('Element got detached from dom!');
>   // ...
> });

Excellent!

I've been searching for how to detect if an element handle is removed from the DOM.
I have a "next" button showing up from multiple steps because of transitions.

This code seems to work as a generic function:

```js
function sleep(ms) {
	return new Promise((resolve) => {
		setTimeout(resolve, ms);
		});
	}
async function waitForElementHandleToBeRemoved(elementHandle,waitMax=5000,waitStep=100){
	const timeStart = new Date().valueOf();
	var elementVisible = true;
	var timeNow=timeStart;
	while((timeNow-timeStart)<waitMax && elementVisible){
		await sleep(waitStep);
		elementVisible = await elementHandle.evaluate(el => el.isConnected);
		timeNow = new Date().valueOf();
		}
	if(!elementVisible) return true;
	throw new Error('element still visible after '+waitMax+'ms');
	}
```
