### ISSUE TITLE
Page.click and waitForNavigation are not working when defaultViewport is set to null.

### ISSUE THREAD

**Issue by dmitrysteblyuk** [puppeteer/puppeteer#6406]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.2.1
* Platform / OS version: Mac OS X 10.15.5
* URLs (if applicable): https://employee-master-data.demo.matterway.io/employee
* Node.js version: v14.7.0

**What steps will reproduce the problem?**
Run the code below.
It works hundred percent of the time only if specific non-zero values of `width`/`height` are set in `defaultViewport`.
Otherwise it often fails.

```
const puppeteer = require('puppeteer');

console.time('Success');

(async () => {
  const browser = await puppeteer.launch({
    executablePath: puppeteer.executablePath(),
    // FAILS:
    defaultViewport: null,
    // FAILS:
    // defaultViewport: {width: 0, height: 0},
    // WORKS:
    // defaultViewport: undefined,
    // WORKS:
    // defaultViewport: {width: 10000, height: 10000},
    headless: false
  });
  const page = await browser.newPage();

  const timeout = 10 * 1000;
  const visible = true;

  await Promise.all([
    page.waitForNavigation({timeout}),
    page.goto('https://employee-master-data.demo.matterway.io/employee'),
  ]);

  await (
    await page.waitForSelector('[name="uid"]', {timeout, visible})
  ).type('P19856');

  await Promise.all([
    // This also FAILS if `defaultViewport` is set to `null` or `{width: 0, height: 0}`:
    // page.waitForNavigation({timeout}),
    (
      await page.waitForXPath('//button[text()="Open"]', {timeout, visible})
    ).click()
  ]);

  await (
    await page.waitForSelector('input[name="tid"]', {timeout, visible})
  ).type('0010');

  await Promise.all([
    page.waitForNavigation({timeout}),
    (
      await page.waitForXPath('//button[text()="Open"]', {timeout, visible})
    ).click() // <-- this will FAIL
  ]);

  await page.waitForXPath('//button[text()="Edit selected record"]', {timeout, visible});
})()
.then(() => {
  console.timeEnd('Success');
  process.exit(0);
})
.catch((error) => {
  console.error(error);
  process.exit(1);
});
```

1. Run the code. It fails on second button click (most of times).
2. Uncomment different values of `defaultViewport` to make it work/fail.
3. Uncomment the second `page.waitForNavigation` to reproduce another issue with navigation (make sure defaultViewport is set to null or {width: 0, height: 0})

**What is the expected result?**
Automation successful result does not depend on value of `defaultViewport`.

**What happens instead?**
Automation works only when `width`/`height` in `defaultViewport` are set to non-zero values.
Otherwise `click` and `waitForNavigation` are failing.

**Comment by azproduction** [comment]
@jackfranklin could you please check? It seems to be a relevant issue.
