### ISSUE TITLE
Better way to cleanup puppeteer_dev_chrome_profile-*

### ISSUE THREAD

**Issue by mahnunchik** [puppeteer/puppeteer#6414]
### Steps to reproduce

Launch puppeteer for a long time. 

```bash
Error: ENOSPC: no space left on device, mkdtemp '/tmp/puppeteer_dev_profile-XXXXXX'
```

**Tell us about your environment:**

* Puppeteer version: 5.1.0
* Platform / OS version: Debian Stretch
* URLs (if applicable): -
* Node.js version: 12

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Launch puppeteer for a long time. 

**What is the expected result?**

Works without any issue.

**What happens instead?**

No space left on device because a lot of `puppeteer_dev_chrome_profile-*` files.

Related issues:

* https://github.com/puppeteer/puppeteer/issues/1791

**Comment by cenfun** [comment]
yes it's a problem, I used userDataDir option and empty custom-temp-dir after puppeteer job ends every time.
puppeteer.launch({
userDataDir: "path-to-custom-temp-dir"
});

**Comment by mahnunchik** [comment]
Similar or connected issues:

* https://github.com/puppeteer/puppeteer/issues/6286
* https://github.com/puppeteer/puppeteer/issues/6291

**Comment by elie222** [comment]
Any solution to this yet?

**Comment by KR3KZ** [comment]
?

**Comment by hoangfuongduy** [comment]
I encountered the same issue. Really curious if anyone has the solution.

**Comment by blue-int** [comment]
You can use `browser.createIncognitoBrowserContext()` and `context.newPage()`
> "Incognito" browser contexts don't write any browsing data to disk.

**Comment by elie222** [comment]
> You can use `browser.createIncognitoBrowserContext()` and `context.newPage()`
> 
> > "Incognito" browser contexts don't write any browsing data to disk.


Thanks. Seeing if this works.

You can also launch the browser in Incognito mode with:

```ts
const browser = await puppeteer.launch({
  args: [
    '--incognito',
  ],
});
```

**Comment by MahbbRah** [comment]
> 

That's false information I'm running it on incognito mode and it's still creating dev profile.

**Comment by hafizsheetab** [comment]
Any solution?

**Comment by rui-ys** [comment]
> You can use `browser.createIncognitoBrowserContext()` and `context.newPage()`

**Comment by elie222** [comment]
> > You can use `browser.createIncognitoBrowserContext()` and `context.newPage()`

As mentioned above this solution doesn't work:

> That's false information I'm running it on incognito mode and it's still creating dev profile.

**Comment by phpner** [comment]
It helped me
```
const browser = await  puppeteer.launch({
        userDataDir: '/dev/null'
    });
```

**Comment by UsVfxArtia** [comment]
> It helped me
> 
> ```
> const browser = await  puppeteer.launch({
>         userDataDir: '/dev/null'
>     });
> ```

Helped with what. I have tryend this arg but %TEMP% folder still raises

**Comment by wonkyungup** [comment]
The same problem is being identified. Do you have any solution?

**Comment by Roosteridk** [comment]
any update on this?

**Comment by AlexeyStadnik** [comment]
Unfortunately, none of this worked for me...

I ended up adding a cron job to clean all profiles that were created a day before (in my case I do not need anything older than 1 day)


Command to rm profiles:
```
find "/tmp/snap-private-tmp/snap.chromium/tmp" -name "puppeteer_dev_profile-*" -type d -mtime +0 -exec rm -rf "{}" \;
```

**Comment by wonkyungup** [comment]
Additional installation of chrome-aws-lambda solved the problem.

https://www.npmjs.com/package/chrome-aws-lambda

**Comment by avimar** [comment]
> Unfortunately, none of this worked for me...
> 
> I ended up adding a cron job to clean all profiles that were created a day before (in my case I do not need anything older than 1 day)
> 
> Command to rm profiles:
> 
> ```shell
> find "/tmp/snap-private-tmp/snap.chromium/tmp" -name "puppeteer_dev_profile-*" -type d -mtime +0 -exec rm -rf "{}" \;
> ```

Path and name are a bit different on my machine, and also the profile name changed? I was getting issues with the deletion too. Here's a slightly different version:

```shell
find /tmp -name "puppeteer_dev*" -type d -mtime +0 | xargs rm -rf
```

**Comment by Jakeroid** [comment]
I delete them by adding cron task with following command which deletes all files and directories with puppeteer in name. 

```
find /tmp/puppeteer* -mtime +15 -exec rm -rf {} \;
```

**Comment by WGH-** [comment]
Did you by any chance all forget to call `await browser.close()` inside a `finally` block? Because that was my problem, for example.

**Comment by davyzhang** [comment]
> Did you by any chance all forget to call `await browser.close()` inside a `finally` block? Because that was my problem, for example.

I am pretty sure that's the the issue. dev_profile folder still exists after await

**Comment by MeLoseAgain** [comment]
> I delete them by adding cron task with following command which deletes all files and directories with puppeteer in name.
> 
> ```
> find /tmp/puppeteer* -mtime +15 -exec rm -rf {} \;
> ```

find /tmp/snap-private-tmp/snap.chromium/tmp -maxdepth 1 -name "puppeteer_dev_*" -type d -exec sh -c 'echo "Deleting: {}" && rm -r {}' \;

you can add time

**Comment by OrKoN** [comment]
Puppeteer cleans up the temporary profiles if the browser is closed via `browser.close` so I am not able to reproduce the bug with the latest version.

**Comment by OrKoN** [comment]
@v-dev-cl are you using the init-process in your deployment? e.g., by starting the container with the `--init` flag?

**Comment by v-dev-cl** [comment]
> @v-dev-cl are you using the init-process in your deployment? e.g., by starting the container with the `--init` flag?

no, i'm using k3s and implemented other solution by manually deleting those files so its not a big deal

https://github.com/puppeteer/puppeteer/issues/1791#issuecomment-1311558279

**Comment by OrKoN** [comment]
@v-dev-cl if you do not have an init process in the container, the multi-process containers might not work as expected (e.g., the browser process might not get killed based on other users' reports) and in that case the cleanup won't happen since the process is still running.

**Comment by v-dev-cl** [comment]
> @v-dev-cl if you do not have an init process in the container, the multi-process containers might not work as expected (e.g., the browser process might not get killed based on other users' reports) and in that case the cleanup won't happen since the process is still running.

i've read that that only happens with puppeteer PID 1, in my case node has PID 1 and from node i'm instancing more browsers as required, the issue (profile files not deleted) only happens when i execute multiple request at the same time .

right now with --headless  + headless: 'new' arguments + manual deletion of profile files works as expected, althogh i still have  a memory leak (not sure as there are no more processes) but its far better than before (uses less memory)

top command after running 18 hours.

`Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s): 41.5 us,  3.5 sy,  0.0 ni, 51.6 id,  0.4 wa,  0.0 hi,  3.0 si,  0.0 st 
MiB Mem :  64103.4 total,   1385.6 free,   9125.7 used,  54523.1 buff/cache     
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  54977.8 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                              
 510695 root      20   0 1132.3g 157260 127928 S   5.0   0.2   0:00.15 chrome                                                                                                                                                                                                               
      1 root      20   0 1451220 227512  47632 S   3.7   0.3  26:44.30 node                                                                                                                                                                                                                 
 388127 root      20   0 1132.2g 162272 133636 S   0.3   0.2   0:43.45 chrome                                                                                                                                                                                                               
 433574 root      20   0 1132.2g 169724 140452 S   0.0   0.3   0:26.27 chrome                                                                                                                                                                                                               
 510481 root      20   0    8652   4760   2856 R   0.0   0.0   0:00.01 top   `

**Comment by gregg-cbs** [comment]
Guys 2024, still an issue. I am trying the above solutions along with tons of additional cache args to try fix this, will feedback in a few days.

**Comment by gregg-cbs** [comment]
### Digital Ocean Ubuntu Applet
Im using this comment as a place to put notes of findings over the next few weeks.

### userDataDir
This solution threw an error `command_line_handler.cc(120)] Could not create directory /dev/null: File exists (17)` and when changing the directory i got `Could not create directory /dev/puppeteer-temp: Permission denied (13)`. I could always log into the box and make the directory but if I move boxes its more to think about and i dont want that.
```js
const browser = await  puppeteer.launch({
  userDataDir: '/dev/null'
});
```

**Args**
Someone on Stackoverflow suggested to add these cache args, im busy trying these out at the moment (disk space seems to be creeping but its only been 24 hours as of 09 July 2024)
```
await puppeteer.launch({
  args: [
    // cache
    '--disable-dev-profile',
    '--aggressive-cache-discard',
    '--disable-cache',
    '--disable-application-cache',
    '--disable-offline-load-stale-cache',
    '--disable-gpu-shader-disk-cache',
    '--media-cache-size=0',
    '--disk-cache-size=0',
  ],
});
```

...more to follow

**Comment by SirLouen** [comment]
After 
```
userDataDir: '/dev/null'
```

```
Caught exception: Failed to launch the browser process! undefined
[20356:20356:0810/122604.113490:ERROR:process_singleton_posix.cc(335)] Failed to create /root/.config/google-chrome-for-testing/SingletonLock: File exists (17)
[20356:20356:0810/122604.114760:ERROR:chrome_main_delegate.cc(594)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.


TROUBLESHOOTING: https://pptr.dev/troubleshooting
```

**Comment by compwright** [comment]
Please re-open, as @gregg-cbs thoroughly covered, this is still an issue for many of us.

**Comment by OrKoN** [comment]
As @gregg-cbs mentioned, you need to catch exceptions for Puppeteer to handle the shutdown gracefully. If your process crashes or you terminate the process without calling browser.close(), there is a chance that the tmp user data dir will be left on disk. 

If you can reproduce the issue with tmp folders not being cleaned up during the normal workflow, feel free to file an issue with a minimal reproducible example and we will take a look.

**Comment by gregg-cbs** [comment]
I havent tried the catch. After trying many things the puppeteer_dev_chrome_profiles are still bloating the tmp folder. For now we manually clear the folder every month. We will solve this by writing a script that does this as suggested by another user however that should not be the solution to this problem.

Can anyone verify if wrapping the browser api in a try catch solves this problem?
```
try {
	const context = await browser.createIncognitoBrowserContext();
	const page = await context.newPage();
	await page.goto(url);
....
} catch (e) {
	process.exitCode = 1
	console.error(e);
}
```

**Comment by natanavra** [comment]
This started happening when I moved to Ubuntu 24 and upgraded puppeteer to latest version.
used to work on Amazon linux with pupeeteer version 12.

**Comment by jpagand** [comment]
For those using AWS lambda and puppeteer to generate PDFs, it seems AWS reuse context/ressources when lambda is invoked repeatedly: [source](https://stackoverflow.com/a/49895042/1753600)

In our case, the /tmp directory is not cleaned after each execution which lead to storage being full. So we tried to remove userDataDir once we are done and we no longer have this error

```
import {rm} from 'fs/promises';
import puppeteer from 'puppeteer-core';

const userDataDir = `/tmp/puppeeter-user-data-${randomBytes(4).toString('hex')}`;

try {
    browser = await puppeteer.launch({userDataDir})
    // [...]
} finally {
    try {
        await rm(userDataDir, {recursive: true, force: true});
    } catch (error) {
        logger.error(`Error cleaning up user data directory ${userDataDir}:`, error);
    }
}
```

Size of /tmp before fix
<img width="665" alt="Image" src="https://github.com/user-attachments/assets/23f741e6-82a7-427e-a648-fb5fad7114fe" />

Size of /tmp after fix
<img width="665" alt="Image" src="https://github.com/user-attachments/assets/fcea681f-090b-440f-930a-6c163c2ac0e1" />
