### ISSUE TITLE
Puppeteer rendering time

### ISSUE THREAD

**Issue by gituserjava** [puppeteer/puppeteer#6418]
We are using puppeteer to print a PDF. The chromium runtime does not send an acknowledgement of when the page is rendered completely so as to initiate the print. As of we are waiting 10sec assuming the page gets rendered internally after 10sec. Is there a way we can get confirmation from chromium that it has rendered the page? Please let us know.

**Comment by lgauthier1** [comment]
How about this settings:
https://pptr.dev/#?product=Puppeteer&version=v2.1.1&show=api-pagewaitfornavigationoptions
