### ISSUE TITLE
The problem of Chinese disorderly code

### ISSUE THREAD

**Issue by JustinYi922** [puppeteer/puppeteer#642]
A few days ago, in accordance with the requirements of doc/troubleshooting.md finally puppeteer can be installed in the centos. But there are some Chinese problems in the picture. I tried to download a lot of fonts. There is also an error, I do not know whether it led to the problem of Chinese disorderly code。

centos:7
node:v8.4

-----------------
DevTools listening on ws://127.0.0.1:54020/devtools/browser/f46d3fa5-8b49-4c38-97bc-09382c7c825b
[0831/101612.160813:ERROR:devtools_http_handler.cc(245)] Error writing DevTools active port to file

![29903373-285e632c-8e36-11e7-8286-446f8ebfec02](https://user-images.githubusercontent.com/12181444/29954499-f5531998-8f0a-11e7-9d7f-e7b99fd60dd9.png)

**Comment by JustinYi922** [comment]
好吧。我也不知道该下载哪些字体。所有干脆下载所有字体：yum -y install *-fonts-*。解决了渲染图片乱码的问题。
（不过上面的报错依然存在。）
![image](https://user-images.githubusercontent.com/12181444/29954493-dac3cf78-8f0a-11e7-9645-16a918ddd415.png)

**Comment by li2568261** [comment]
你好，我也遇到同样的问题，这个问题你现在解决了吗？

**Comment by li2568261** [comment]
我跑你这个命令，提示没有可以下载的包
