### ISSUE TITLE
Request interception problem on xslt file include

### ISSUE THREAD

**Issue by oguzkurumlu** [puppeteer/puppeteer#6424]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.0
* Platform / OS version: Windows
* Node.js version: 12.18.1

**What steps will reproduce the problem?**

I have a xml page which evaluates by xslt. And the main xslt file includes another xslt file. By default there is no problem. But if i enabled the request interception the main xslt request stays in pendings.
1.

    page = await browser.newPage();
    await page.setRequestInterception(true);
    page.on('request', (request) => {
        console.log(request.url());
        request.continue();
    });
    await page.goto('http://localhost/test.xml');

2. test.xml

`<?xml-stylesheet type="text/xsl" href="test.xslt"?>
<test>
	<var>Foo</var>
</test>
`
3. test.xslt

`
<xsl:output  method="html"  omit-xml-declaration="no"
	  doctype-system="http://www.w3.org/TR/xhtml1/DTD/strict.dtd" 
	  doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN" indent="no" />
	<xsl:include href="sub.xslt"/>
	<xsl:template match="/">
		<html>
			<head>
				<title>o</title>
			</head>
			<body scroll="yes" >
				<xsl:value-of select="$outVar"/>
			</body>
		</html>
	</xsl:template>
</xsl:output>
`
4. sub.xslt

`<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:variable name="outVar">deneme</xsl:variable>
</xsl:stylesheet>
`

**What is the expected result?**

I expected to intercept all requests. But its only intercepts test.xml and test.xslt

**What happens instead?**
![image](https://user-images.githubusercontent.com/6850015/93330990-4cdaa800-f828-11ea-9a06-a9e5a813cad9.png)

It doesnt intercept sub.xslt file.  

But page.setRequestInterception(false) version works.

![image](https://user-images.githubusercontent.com/6850015/93335574-57e50680-f82f-11ea-9782-e3e3ae709ce3.png)

**Comment by metroyanno** [comment]
Same with the iframes
