### ISSUE TITLE
When I pkg my file and include puppeteer in my dependencies I get an error when I run my application.

### ISSUE THREAD

**Issue by ethans333** [puppeteer/puppeteer#6425]
I am using just regular puppeteer not puppeteer-core. How do I properly add puppeteer to my pack.json dependencies so I wont get this error when running it in my terminal?
```
(node:36178) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 800071. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/Users/ethan/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:86:23)
    at async getArtist (/Users/ethan/Documents/html-js/SoundCloud-Terminal/searchArtist.js:13:21)
    at async /Users/ethan/Documents/html-js/SoundCloud-Terminal/searchArtist.js:57:23
(node:36178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by achanta3215** [comment]
https://stackoverflow.com/questions/62820586/error-could-not-find-browser-revision-756035-run-npm-install

**Comment by holesa** [comment]
<del>Same problem here. I also noticed that the command `npm i puppeteer` installs puppeteer but not chromium. I'm missing folder node_modules\puppeteer\ .local-chromium. This is happening only on Ubuntu on Digital Ocean. Locally on Windows is everything fine.</del>

Ok, the problem in my case was because of permission. When installing npm packages I used `sudo npm install` and it worked.

**Comment by ethans333** [comment]
@achanta3215 @holesa neither of these worked. I works flawlessly when I run it within my vscode terminal, it just returns errors when the project is built (with puppeteer added to the package.json file) and run as an exec file. Any other solutions?

**Comment by slumbering** [comment]
Remove node_modules then relaunch a yarn install did work for me. Thanks @achanta3215

**Comment by ethans333** [comment]
@slumbering after or before it's packaged? And would relaunch a yarn install for npm be ```npm install```?

**Comment by alekhrycaiko** [comment]
Has anyone else had other solutions come to mind besides reinstalling node modules? I've seen a couple cases of this arising via Docker runs, and haven't had any success with node_modules removal and reinstall.

**Comment by Tim-Fisher** [comment]
This is also an issue for me while using docker-compose.

Puppeteer works fine in a Docker container when I:
  * Use `docker build` / `docker run`.
  * Follow instructions [here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker)
  * Set `product: 'chrome'` options when when calling puppeteer.launch()

But, when I try to run the setup using docker-compose, it fails with the same message about Firefox.

Any suggestions? Is there a way to tell puppeteer to stop looking for Firefox?

**Comment by govza** [comment]
Using example of github action here
https://github.com/marketplace/actions/puppeteer-headful

was able to run in docker container providing
```
browser = await puppeteer.launch({
  executablePath: process.env.PUPPETEER_EXEC_PATH, // set by docker container
  headless: false,
  ...
});
```
Dockerfile entrypoint.sh:
export PUPPETEER_EXEC_PATH="google-chrome-stable"

**Comment by stormmuller** [comment]
For some reason I doubt this is the correct way to fix the issue, but here's what I had to do to get it working. I had to run chrome with `--no-sandbox`. Along with the solution @govza posted. 

``` js
  const browser = await puppeteer.launch({
    executablePath: process.env.PUPPETEER_EXEC_PATH,
    args: ['--no-sandbox']
  });
```

**Comment by uriiz** [comment]
same issue, and its also happend only after i pkg my files, someone have an idea?

**Comment by jgknott** [comment]
Having a similar issue.  Works fine on mac, just not on Linux and and Windows compiles (with Electron)

**Comment by mathiasmaerker** [comment]
I am onboard, puppeteer which worked previously in my Azure Functions stopped to work

**Comment by twigs67** [comment]
@govza @jgknott has anyone tried loading chrome extensions? I'm trying to automate testing of chrome extensions, but I can't get it to load the extension. Everything else is working thoughl

**Comment by LinkTree3** [comment]
@ethans333 Did you manage to find a solution for this? I am also having the same issue right now.

**Comment by MuYunyun** [comment]
> Having a similar issue. Works fine on mac, just not on Linux and and Windows compiles (with Electron)

Sadly, it doesn't work fine on my mac.
