### ISSUE TITLE
ElementHandle.waitForSelector - feature suggestion

### ISSUE THREAD

**Issue by Slawcio** [puppeteer/puppeteer#6427]
have a specific listing that contains the lazy-loading calendar for each record. I catch them by

 `docsPanels = await page.$$('[data-id = "result-item"]');`

and I don't know how big the `docsPanels` might be. Then I need to check if the calendar loads within the element I have from the list. Something like:

```
for (const panel of Object.values ​​(docsPanels)) {
   await panel.hover ({delay: 100});                  // scroll to the record
   panel.waitForSelector ('.lazy-calendar-slot');// checks the calendar within the element
};
```
I wonder if there is anything like this, cause the ElementHandle.$ ('selector') which is the closest to my solution is working immediately. Any workaround, solution for it?

**Comment by sunmasters** [comment]
It is best to find the length or count elements. 
Then wait for the last child length.
