### ISSUE TITLE
Monitor CPU utilization during the life of a page

### ISSUE THREAD

**Issue by honzajde** [puppeteer/puppeteer#6429]
I am trying to monitor CPU utilization with puppeteer. I can find handful relate solutions for page loading measurement and heap measuring but nothing to see the CPU utilization during the life of a page not only when the page is loading.

The same information is available in chrome under dev-tools/Performance monitor as "CPU usage"

(I have posted same question on SO and did not get any answer. That's why I am posting here - might be a feature request.)

**Comment by Nithanaroy** [comment]
Same here, I'm trying to obtain the CPU % usage at any given instant just like the values shown in "Performance Monitor" tab. 

![perf-monitor-cpu-usage](https://user-images.githubusercontent.com/670556/103376133-a641ac80-4a90-11eb-9dda-9e0471a3950b.png)

PS. I was able to compute the relative usage using `getMetrics` API of dev tools as shared [here](https://github.com/aslushnikov/tracium/issues/17#issuecomment-747526405) but I'm looking for standard CPU % numbers as it easier to understand and explain to others.

@aslushnikov, any thoughts? Thank you :)

**Comment by kalpeshchilka** [comment]
@Nithanaroy @honzajde Did you found any workaround to get this data or an actual solution. Please let me know, even I'm looking for similar data. Thanks!

**Comment by aidangoettsch** [comment]
Dug through the code and figured I would share since it doesn't seem like this explanation has surfaced anywhere.

It looks like the relevant code in devtools is here:
https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/third_party/devtools-frontend/src/front_end/core/sdk/PerformanceMetricsModel.js;l=43?q=requestMetrics&ss=chromium%2Fchromium%2Fsrc

```js
case "CumulativeTime" /* CumulativeTime */:
    value = (data.lastTimestamp && data.lastValue) ?
        Platform.NumberUtilities.clamp((metric.value - data.lastValue) * 1000 / (timestamp - data.lastTimestamp), 0, 1) :
        0;
    data.lastValue = metric.value;
    data.lastTimestamp = timestamp;
    break;
```

Devtools is polling for metrics, which appear to contain the cumulative time spent on a task since the metrics were enabled. CPU usage is the percent of time taken by all tasks since the last metrics request.

Sample code to log CPU usage over time:
```ts
interface CPUUsageSnapshot {
  timestamp: number,
  usage: number,
}

export interface CPUStats {
  average: number,
  snapshots: CPUUsageSnapshot[]
}

function processMetrics(metrics: GetMetricsResponse): {
  timestamp: number,
  activeTime: number
} {
  const activeTime = metrics.metrics.filter(m => m.name.includes("Duration")).map(m => m.value).reduce((a, b) => a + b)
  return {
    timestamp: metrics.metrics.find(m => m.name === "Timestamp")?.value || 0,
    activeTime
  }
}

async function logMetrics(cdp: CDPSession, interval: number): Promise<() => Promise<CPUStats>> {
  await cdp.send("Performance.enable", {
    timeDomain: "timeTicks"
  })

  const { timestamp: startTime, activeTime: initialActiveTime } = processMetrics(await cdp.send("Performance.getMetrics"))
  const snapshots: CPUUsageSnapshot[] = []
  let cumulativeActiveTime = initialActiveTime

  let lastTimestamp = startTime
  const timer = setInterval(async () => {
    const {timestamp, activeTime} = processMetrics(await cdp.send("Performance.getMetrics"))
    const frameDuration = timestamp - lastTimestamp
    let usage = (activeTime - cumulativeActiveTime) / frameDuration
    cumulativeActiveTime = activeTime

    if (usage > 1) usage = 1
    snapshots.push({
      timestamp,
      usage
    })

    lastTimestamp = timestamp
  }, interval)

  return async () => {
    clearInterval(timer)
    await cdp.send("Performance.disable")

    return {
      average: cumulativeActiveTime / (lastTimestamp - startTime),
      snapshots
    }
  }
}
```

**Comment by sondh0127** [comment]
any one know how can we get the JS Heap size 
![image](https://github.com/user-attachments/assets/5d1dc42d-2251-4339-a7d4-8f543d5f5d1b)

**Comment by sondh0127** [comment]
js_heap_size = next((m.to_json()["value"] for m in metrics if m.to_json()["name"] == "JSHeapUsedSize"), 0)

JSHeapUsedSize is the way guys
