### ISSUE TITLE
a

### ISSUE THREAD

**Issue by MMMzq** [puppeteer/puppeteer#643]

**Comment by MMMzq** [comment]
aaaaa

**Comment by MMMzq** [comment]
我才不告诉你我有阿里云优惠券-> http://izhuanyer.top

**Comment by Tynael** [comment]
What's this issue all about?
Could you please provide more information?
Cheers!

**Comment by aslushnikov** [comment]
Translation sounds like spam.

**Comment by Tynael** [comment]
Yup, he opened the same issue for other 8 repositories. Lol.

**Comment by Cyberpunkerplus** [comment]
it is a spam !

**Comment by MMMzq** [comment]
I am embarrassed by my previous behavior, I am very sorry.
