### ISSUE TITLE
puppeteer - Error: Page crashed! - Windows Container - mcr.microsoft.com/windows/servercore - Windows 10 Host

### ISSUE THREAD

**Issue by ben-praveen** [puppeteer/puppeteer#6430]
### Download project 
[sample.zip](https://github.com/puppeteer/puppeteer/files/5243919/sample.zip)

`# escape=`
`FROM mcr.microsoft.com/windows/servercore:1909

SHELL [ "powershell", "-Command" ]

USER ContainerAdministrator

ARG NODE_VERSION="12.18.3"

RUN mkdir C:\app; `
    mkdir C:\temp

RUN cd C:\temp; `
    Invoke-WebRequest -Uri https://nodejs.org/dist/v${Env:NODE_VERSION}/node-v${Env:NODE_VERSION}-x64.msi -OutFile C:\temp\node-v${Env:NODE_VERSION}-x64.msi; `
    if (! (Test-Path C:\temp\node-v${Env:NODE_VERSION}-x64.msi)) { echo "Unable to download Node!" }; `
    Start-Process msiexec.exe -ArgumentList @('/i', \"c:\temp\node-v${Env:NODE_VERSION}-x64.msi\", '/qn', '/quiet', '/norestart', 'ADDLOCAL=ALL', '/log', \"C:\temp\node-v${Env:NODE_VERSION}-x64.log\") `
                                        -RedirectStandardOutput "C:\temp\node-v${Env:NODE_VERSION}-x64_out.log" `
                                        -RedirectStandardError "C:\temp\node-v${Env:NODE_VERSION}-x64_err.log" `
                                        -NoNewWindow -Wait

RUN powershell -Command Add-WindowsFeature Web-WebSockets    

COPY package.json c:\app

RUN cd c:\app\; `
   ` npm install

`COPY server.js c:\app\

ARG PORT=8000
ENV PORT=$PORT
EXPOSE $PORT

WORKDIR C:/app
CMD [ "node", "server.js"]`

### server.js
`const express = require('express');
const puppeteer = require('puppeteer');
const app = express();
app.get('/', function (req, res) {
    res.send("ok");
});

app.get('/test', async function (req, res) {
    const browser = await puppeteer.launch({
        args: ['--no-sandbox', '--headless', '--disable-gpu']
    });
    const page = await browser.newPage();
    await page.goto('https://google.com', { waitUntil: 'networkidle2' });
    await page.pdf({ path: 'hn.pdf', format: 'A4' });

    await browser.close();
    return res.send('ok')
});
app.listen(8000, async () => {
    console.log("Puppeteer running.  Waiting for requests...");
});
`
## package.json
  `  "express": "*",
    "puppeteer": "2.0.0",`

##Error:
`(node:1800) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (C:\temp\Screenshot-New\node_modules\puppeteer\lib\Page.js:216:24)
    at CDPSession.<anonymous> (C:\temp\Screenshot-New\node_modules\puppeteer\lib\Page.js:124:56)
    at CDPSession.emit (events.js:315:20)
    at Connection._onMessage (C:\temp\Screenshot-New\node_modules\puppeteer\lib\Connection.js:112:17)
    at WebSocket.onMessage (C:\temp\Screenshot-New\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\temp\Screenshot-New\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:315:20)
(node:1800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1800) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\temp\Screenshot-New\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (C:\temp\Screenshot-New\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (C:\temp\Screenshot-New\node_modules\puppeteer\lib\Page.js:675:49)
    at Page.<anonymous> (C:\temp\Screenshot-New\node_modules\puppeteer\lib\helper.js:112:23)
    at C:\temp\Screenshot-New\screenshotServer.js:19:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

[sample.zip](https://github.com/puppeteer/puppeteer/files/5243919/sample.zip)

**Comment by WeihanLi** [comment]
I'm also using windows container, I also met some problems when I use `mcr.microsoft.com/windows/servercore:2004-amd64` image, seemed there's some dependencies missing, when I use `mcr.microsoft.com/windows:2004-amd64`, it works, but this image is too large.

Is there some guide for using windows container? Some necessary dependencies for windows container?

I'd posted a question on [StackOverflow](https://stackoverflow.com/questions/65487510/is-there-any-windows-container-guide-for-puppeteer)
