### ISSUE TITLE
[Question] Any plans on adding support for Deno without Npm?

### ISSUE THREAD

**Issue by ebebbington** [puppeteer/puppeteer#6433]
Any plans to port puppeteer over to Deno?

**Comment by zabakala** [comment]
Guys, Make it real. Puppeteer has typescript incorporated so there should be no major obstacle to make it compatible with Deno.

**Comment by jaydenseric** [comment]
Kinda duplicates https://github.com/puppeteer/puppeteer/issues/5953 .

Not state.

**Comment by OrKoN** [comment]
Hey, currently, there are no plans to support Deno. Happy to accept PRs to make it compatible if that does not break NodeJS.
