### ISSUE TITLE
which node version on ubuntu does it work best on ?

### ISSUE THREAD

**Issue by PManager1** [puppeteer/puppeteer#6434]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by petrvecera** [comment]
Latest LTS version
