### ISSUE TITLE
npm install puppeteer fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by kekearif** [puppeteer/puppeteer#6435]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v5.3.0
* Platform / OS version: Ubuntu 18.04 LTS
* URLs (if applicable):
* Node.js version: v8.10.0

**What steps will reproduce the problem?**

I try to install puppeteer on my Ubuntu 18.04 LTS instance using `npm install puppeteer`

_Please include code that reproduces the issue._

1. `npm install puppeteer`

**What is the expected result?**

Install is successful

**What happens instead?**

```
unhandledPromiseRejectionWarning: /home/kekearif/meh/node_modules/puppeteer/lib/cjs/puppeteer/install.js:138
                    catch {
                          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at download (/home/kekearif/meh/node_modules/puppeteer/install.js:35:7)
(node:11036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
meh@1.0.0 /home/kekearif/meh
└── puppeteer@5.3.0  extraneous

npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN meh@1.0.0 No description
npm WARN meh@1.0.0 No repository field.
```

Having issues installing puppeteer on Ubuntu as noted above, some advice on how to fix this would be much appreciated! Thanks

**Comment by AviVahl** [comment]
The version of Node.js (8) is outdated.
Current puppeteer versions support `"node": ">=10.18.1"`.

**Comment by luvletterldl** [comment]
> The version of Node.js (8) is outdated.
> Current puppeteer versions support `"node": ">=10.18.1"`.
node: 14.15.1 same issue
@AviVahl

**Comment by AviVahl** [comment]
> node: 14.15.1 same issue

`SyntaxError: Unexpected token {` means Node cannot parse puppeteer's code in order to evaluate it. It would only happen on Node 8 and older releases, as they do not support a lot of the newer syntax puppeteer uses.

Node 14.15.1 understands current puppeteer's code, so you might be experiencing a different issue or actually running an older Node version (`node -v`).

**Comment by luvletterldl** [comment]
> > node: 14.15.1 same issue
> 
> `SyntaxError: Unexpected token {` means Node cannot parse puppeteer's code in order to evaluate it. It would only happen on Node 8 and older releases, as they do not support a lot of the newer syntax puppeteer uses.
> 
> Node 14.15.1 understands current puppeteer's code, so you might be experiencing a different issue or actually running an older Node version (`node -v`).

![image](https://user-images.githubusercontent.com/26115291/100733602-6217a980-3409-11eb-93ab-5d23c982bebe.png)
@AviVahl

**Comment by AviVahl** [comment]
You are running sudo npm. run: sudo node -v
What does it say?

**Comment by luvletterldl** [comment]
> You are running sudo npm. run: sudo node -v
> What does it say?

thanks, reason is my Ubuntu server Lack of dependence
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
