### ISSUE TITLE
some websites block puppeteer access and show blank ad page

### ISSUE THREAD

**Issue by yuis-ice** [puppeteer/puppeteer#6436]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.0 
* Platform / OS version: Ubuntu 18.04 
* URLs (if applicable):
* Node.js version: v12.6.0 

**What steps will reproduce the problem?**

```node

var fs = require("fs");

const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

const repl = require('puppeteer-extra-plugin-repl')({ addToPuppeteerClass: false })
puppeteer.use(repl)

var sleep = require('sleep');

(async () => {

  const browser = await puppeteer.launch({
    

    headless: false,
    ignoreHTTPSErrors: true,

    args: [
        '--lang=en-US,en;q=0.9', 
        // '--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3419.0 Safari/537.36"', 
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-infobars',
        '--window-position=0,0',
        '--ignore-certifcate-errors',
        '--ignore-certifcate-errors-spki-list',
    ], 

    ignoreHTTPSErrors: true,
    userDataDir: './tmp', 

  });


  const page = await browser.newPage();


  const preloadFile = fs.readFileSync('./preload.js', 'utf8');
  await page.evaluateOnNewDocument(preloadFile);



  await page.setViewport({width: 1200, height: 720})

  await page.setDefaultNavigationTimeout(0);

  const navigationPromise = page.waitForNavigation()
  

  await Promise.all([
    page.goto('https://www.coingecko.com/en/coins/bitcoin', {timeout: 60000}), 
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
  ]);
  await sleep.sleep(5)

  await Promise.all([
    page.goto('https://www.coingecko.com/en/coins/ethereum', {timeout: 60000}), 
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
  ]);
  await sleep.sleep(5)


  await repl.repl(page)
  await sleep.sleep(5)

})();
```

**What is the expected result?**

normal behavior with no auto-redirection or such. 

**What happens instead?**

some (very popular) websites (I tried tweetdeck.twitter.com; reddit.com; coingecko.com) block (not sure really, so tell me what this actually is) puppeteer browser access, and they show me some blank page with an ad instead, as example screenshot image shown below. 
more technically, they show me a normal webpage once for less than few seconds but after that they auto-redirect to a blank page. You can return back to the normal page by doing back button on your mouse manually and if that case you can see the normal webpage in that session. 
also, while that time, `goto` a URL to auto-redirected to a blank page, puppeteer was unable to scrape any document in the page. 

![https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_fc9a4c49-6350-4051-84b4-8362070eb95d.png](https://yuis.xsrv.jp/images/ss/ShareX_ScreenShot_fc9a4c49-6350-4051-84b4-8362070eb95d.png)

**Comment by gulshansainis** [comment]
I do not see any issue

Tested on puppeteer version: "5.3.1" 

```
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();
  await page.setViewport({ width: 1200, height: 720 });

  await page.goto("https://www.coingecko.com/en/coins/bitcoin");
  await page.screenshot({ path: "screenshot1.png" });
  await page.goto("https://www.coingecko.com/en/coins/ethereum");
  await page.screenshot({ path: "screenshot2.png" });

  await browser.close();
})();
```

**Comment by sunmasters** [comment]
You have used puppeteer extra and it's plugins. But you have posted it in the puppeteer library. 

May be stealth plugin is blocked.
Check your script without stealth plugin enabled.

**Comment by petervoth** [comment]
I'm also having this same issue with accessing https://my.dogechain.info/ using puppeteer.

It will load the page initially and the "cloudflair DDoS protection, wait 5 seconds for the page to load" appears but never goes away / progresses to the actual site? It just hangs? 

When I manually try the link on Chrome it works fine and progresses to an actual login page. But when the Chromium page tries to visit that same link, it just hang on the initial cloudflair message. Any advice would be awesome!

**Comment by Rajat379** [comment]
@petervoth The site (https://my.dogechain.info/) you mentioned, for me as well, causes the puppeteer to take that redirecting page in account.

The initial visit to that site(https://my.dogechain.info/) also leads to the same response - "cloudflair DDoS protection, wait 5 seconds for the page to load". It is on further visits this response disappears.

This extra layer of security is in some sites, and cannot be accessed directly.

**Comment by Fanisus** [comment]
Same issue. When using without SteathPlugin my login attempt is given a 403 response while if i use stealthPlugin and login it work but then after loading all elements it truns to a white page and only ads are shown in inspect element

**Comment by OrKoN** [comment]
If the sites choose to block Puppeteer, there is not much we can do. As other suggested, try using the stealth plugin and perhaps it helps.
