### ISSUE TITLE
Maximize Firefox Nightly windows size

### ISSUE THREAD

**Issue by kevinxp919** [puppeteer/puppeteer#6442]
For issues, feature requests, or setup troubles with Puppeteer, file an issue right here!
Hi, i have been tried to use Firefox Nightly in my automation test scripts. However, it seems the Firefox Nightly does not support to enlarge or maximize the windows even I set the defaultViewPorts: Null or args['--window-size=1920,1080']
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: MAC OS
* URLs (if applicable):
* Node.js version: 12.16.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

puppeteer.launch(
        {
          executablePath: '/Users/p782881/Documents/Firefox Nightly.app/Contents/MacOS/firefox',
          product: 'firefox',
         args:['wait-for-browser'],
          defaultViewport: {
            width: 1920,
            height: 1080
            },
          extraPrefsFirefox: {
        },
        });

**What is the expected result?**
Expect to have 1920*1080 resolution

**What happens instead?**
it seems the size is still 800*600

**Comment by swissspidy** [comment]
`args: ['--width=1920', '--height=1080']` might work.
