### ISSUE TITLE
How to save the page in mhtml file format with puppeter?

### ISSUE THREAD

**Issue by fearlessxjdx** [puppeteer/puppeteer#6443]
How to save the page in mhtml file format with puppeter?

**Comment by vsemozhetbyt** [comment]
https://stackoverflow.com/questions/54814323/puppeteer-how-to-download-entire-web-page-for-offline-use/54817983#54817983

**Comment by fearlessxjdx** [comment]
> https://stackoverflow.com/questions/54814323/puppeteer-how-to-download-entire-web-page-for-offline-use/54817983#54817983

It works,thank you very much.
