### ISSUE TITLE
browser.pages() does not resolve when devtools is connected to a node process

### ISSUE THREAD

**Issue by CantGetRight82** [puppeteer/puppeteer#6452]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: MacOS 10.15.6
* URLs (if applicable):
* Node.js version: v14.10.1
* Chrome version: 85.0.4183.121

**What steps will reproduce the problem?**

1. Start a node process with --inspect (`node --inspect` will do)
2. Connect devtools to that node process (using the green cube in devtools)
3. Execute the following in a different node process:

```
const chromeLocation = require('chrome-location');
const puppeteer = require('puppeteer-core');

(async() => {
    const browser = await puppeteer.connect({
        defaultViewport: null,
        executablePath: chromeLocation,
        browserURL: 'http://localhost:9222',
    })
    const pages = await browser.pages();
    console.log('done');
})()
```

**What is the expected result?**
I expect browser.pages() to resolve.

**What happens instead?**
browser.pages() never resolves.

**Comment by Cinux-Chosan** [comment]
same problem!

**Comment by cognettings** [comment]
browser.pages() isn't resolving for me either.

2017 MacBook Pro: Ventura 13.6.4
Nodejs: v20.17.0
puppeteer-core: 23.3.0
Chrome: 128.0.6613.137 (Official Build) (x86_64)

I'm starting Chrome with: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222`

It prompts me to select a profile, so I do. Then I restore my tabs (about 30 of them). I see tabs listed when I go to http://localhost:9222/json/list but they're never resolved with browser.pages().

Here's the code that's running:
`import puppeteer from 'puppeteer-core';

const browser = await puppeteer.connect({
  defaultViewport: null,
  browserWSEndpoint: 'ws://127.0.0.1:9222/devtools/browser/ea9659fd-aebe-4a0e-bf26-ea4e85ca2265',
});

const pages = await browser.pages();
console.log(pages)

browser.disconnect();`
