### ISSUE TITLE
Puppeteer not using PulseAudio

### ISSUE THREAD

**Issue by ahmafi** [puppeteer/puppeteer#6466]
When I run chromium from a terminal it uses the PulseAudio without any problems. Even with using `PULSE_SINK` environment variable, I can choose the PulseAudio output device. But when I use puppeteer it doesn't send the audio to PulseAudio, so I can't use `PULSE_SINK`.  I have tried setting `--alsa-output-device=pulse` but I'll get an error which says` PcmOpen: pulse,Connection refused`
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: ubuntu 20.04.1
* Node.js version: 12.18.4

**What steps will reproduce the problem?**

1. Run a simple puppeteer with headless=false and open a sample webpage with an audio file 
2. Check PulseAudio devices (with pavucontrol for example)

**What is the expected result?**

Chrome should send the audio to PulseAudio

**What happens instead?**

It doesn't send audio to PulseAudio.

**Comment by codinger41** [comment]
Hey @ahmafi, thanks for putting this out. I'm currently experiencing this issue atm. Did you find any workaround?
