### ISSUE TITLE
Timeout when exec from PHP, Centos 7.8

### ISSUE THREAD

**Issue by phucnhfpt** [puppeteer/puppeteer#6468]
I've created a script file with contents below:

> const puppeteer = require('puppeteer');
(async() => {
  var domain = process.argv.slice(2)[0];
  const browser = await puppeteer.launch({      
      ignoreHTTPSErrors: true,
        dumpio: false,
        pipe: true,        
        args: [
            '--disable-gpu',
            '--disable-extensions',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--ignore-certificate-errors',
            '--proxy-server="direct://"',
            '--proxy-bypass-list=*',
            // `--disable-extensions-except=${ext}`,
            // `--load-extension=${ext}`
        ]
  });
  const page = await browser.newPage();  
  await page.setViewport({ width: 1024, height: 1024 });
  await page.goto('http://'+domain, {waitUntil: 'networkidle0', timeout: 0});
  await page.screenshot({path: 'thumbnails/' + domain + '.png'});
  await browser.close();
})();

Running that script file by terminal works, but running it from php via exec always show timeout error. 
Enviroment : PHP 7.3, CentOS Linux release 7.8.2003 (Core).

**Comment by maheshjukanti** [comment]
PHP does not wait for the response by default. await need some duration to wait to complete the task.
it is best to divide into sub tasks. Or create API.
Script 1. Generate hash (you are passing url)
Script 2. Check whether Image is created by puppeteer or not.

Then you are good to proceed.

Wait some time in between the scripts.(use javascript timeout).
