### ISSUE TITLE
“Start Chat” doesn't display using puppeteer but working fine in by writing script in Selenium. How to fix it in puppeteer?

### ISSUE THREAD

**Issue by muneebrana23** [puppeteer/puppeteer#6469]
@jeresig @envoked @benatkin 

I'm writing an automated script for a website using Puppeteer. It includes chat feature. In puppeteer node.js script "Start chat " button does not display. IF I run the script in Selenium then "start chat" display on which we can click and start chat. chat button display using selenium script

but running script in puppeteer this "Start chat" button doesn't  #display. Chat button doesn't display using puppeteer node.js

**Comment by sunmasters** [comment]
Please post some/part of code. Then only we can understand what error you are getting.

Maybe your script not set any user agent and using default.
