### ISSUE TITLE
Errors suppressed when downloading chromium through the install script

### ISSUE THREAD

**Issue by cleavera** [puppeteer/puppeteer#647]
When a connection issue occurs when downloading chromium during the install script the error is suppressed and fails silently.

This is caused by the following code:
```js
// line 98 ChromiumDownloader.js
return downloadFile(url, zipPath, progressCallback)
        .then(() => extractZip(zipPath, folderPath))
        .catch(err => err)
        .then(() => {
          if (fs.existsSync(zipPath))
            fs.unlinkSync(zipPath);
        });
```
I think it should be safe just to remove this catch as the `install.js` script catches it.

**Comment by aslushnikov** [comment]
Coincidentally, that just got fixed in https://github.com/GoogleChrome/puppeteer/pull/619
