### ISSUE TITLE
Throw an error when trying to open a page on a closed browser instance

### ISSUE THREAD

**Issue by doojin** [puppeteer/puppeteer#6474]
Here is an example (simplified) when I try to open a new page on an already closed browser instance:

```js
const browser = await puppeteer.launch()
await browser.close()
await browser.newPage()
console.log('this message is never printed')
```

The problem is that my `console.log` statement will never be reached. Also, no error is thrown during this program execution.

After small research I found out the following. If I create a promise which is never `resolved` neither `rejected`, the NodeJS is not able to track it whenever I try to `await` for it's result and exits. Example:

```js
(async () => {
  const promise = new Promise((resolve, reject) => {
    if (false) resolve(13)
  })

  await promise
  console.log('we never print this')
})()
```

This is exactly what is happening in my example. This promise:

```js
await browser.newPage()
```

is neither `resolved` nor `rejected` after browser instance is closed. I believe that the problem lies here:

https://github.com/puppeteer/puppeteer/blob/950ae334ca9c4c37b5a34dc61596a89596fd2bc6/src/common/Connection.ts#L81-L96

After I call `newPage` method, the `Connection.send` method is invoked. It creates a `Promise` which I receive (the one that never resolves). This promise's `resolve` and `reject` callbacks are assigned to internal `_callbacks` map. 

Then, there is `_onMessage` callback:

https://github.com/puppeteer/puppeteer/blob/950ae334ca9c4c37b5a34dc61596a89596fd2bc6/src/common/Connection.ts#L128-L137

It checks if a received message is an error or not and invokes either `resolve` either `reject`
This message is received through the `transport`:

https://github.com/puppeteer/puppeteer/blob/950ae334ca9c4c37b5a34dc61596a89596fd2bc6/src/common/Connection.ts#L61

The problem is that this message is never received since the browser connection is closed. Since message is never received, the `_onMessage` callback is never called. And since it's not called, we never call neither `resolve` nor `reject` and I can't `await` for my `Promise` since my NodeJS application exits.

Is it the desired behaviour? IMO, trying to open page on the closed/disconnected browser instance should lead to the error (like it was, actually, before).

puppeteer v2.0.0 throws an error in this case
puppeteer v3.0.0 is not throwing it already

**Comment by markfinn** [comment]
It seems like Connection.send should check if it is closed and reject.  I tired that by adding this as the first thing in Connection.send():

```javascript
if (this._closed)
            return Promise.reject(new Error(`Protocol error (${method}): Target closed.`));
```

This seems to work, and seems like the right thing to do to me.  This is a copy of what happens in Connection.onClose() to any in progress callbacks, but the effect currently doesn't get applied to future send/callbacks.
