### ISSUE TITLE
Proxy settings should be taken from npm config before environment variables

### ISSUE THREAD

**Issue by cleavera** [puppeteer/puppeteer#648]
Currently when installing behind a proxy to get the chromium downloader to respect the proxy settings you have to set the environment variables for `HTTP_PROXY` and `HTTPS_PROXY`.

For me personally I would expect the proxy settings to be taken from the npm config
e.g. 
```
npm config get https-proxy
npm config get proxy
```
And then to fall back on the environment variables if needed.

**Comment by aslushnikov** [comment]
@cleavera afaiu configuring global HTTP proxy with HTTP_PROXY env variable is the default approach - what are the scenarios when it doesn't work for you? NPM itself [respects them](https://docs.npmjs.com/misc/config#proxy).

**Comment by cleavera** [comment]
Hi there, @aslushnikov sorry for the slow reply.

When doing an `npm install` behind the proxy we have always had to specify the config variables directly for npm. This may have changed for npm5 (I'm not entirely sure) but the default behavior would still be npm config, then environment variables. Some members of my team have only had the npm config variables set and they have had no issue downloading other binaries such as phantomjs and node-sass, so I can only assume these libraries respect the npm config variables aswell.

For me npm should really be using the environment variables by default without having their own settings but I feel as long as npm respects those internal config variables then they should be all that is needed to complete a successful install.

**Comment by androidfanatic** [comment]
@cleavera which OS and terminal program are you guys working with?

**Comment by cleavera** [comment]
Combination of windows and mac. Powershell, cmd and bash

**Comment by cleavera** [comment]
Ta

**Comment by aslushnikov** [comment]
@cleavera does the fix work for you? (make sure to install puppeteer from github right away)
