### ISSUE TITLE
CMYK images converted to RGB

### ISSUE THREAD

**Issue by AdamGaskins** [puppeteer/puppeteer#6480]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: macOS 10.15.7
* URLs (if applicable):
* Node.js version: 12.16.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```js
// give puppeteer access to file
const express = require('express')
const app = express()
app.use(express.static(__dirname))
app.listen(3000)

// generate pdf
const puppeteer = require('puppeteer')
const html = `
<html>
    <body>
        <img src="http://localhost:3000/Channel_digital_image_CMYK_color.jpg">
    </body>    
</html>`
;(async () => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setContent(html)
    await page.pdf({ path: 'output.pdf' });
    console.log('done')
})()
```

Here is the CMYK image I used: https://upload.wikimedia.org/wikipedia/en/2/25/Channel_digital_image_CMYK_color.jpg

**What is the expected result?**
If I extract the image from the resulting pdf, it will remain in CMYK format.

**What happens instead?**
The image is converted to RGB, causing the PDF colors to be wrong when printed.

**Comment by lemonxtt** [comment]
I am also facing this problem

**Comment by anre** [comment]
> I am also facing this problem

Me too, we also need PDFs with CMYK colors for printing

**Comment by lemonxtt** [comment]
> Me too, we also need PDFs with CMYK colors for printing

now I'm using Ghostscript to convert pdf RGB to CMYK for printing

**Comment by AdamGaskins** [comment]
> > Me too, we also need PDFs with CMYK colors for printing
> 
> now I'm using Ghostscript to convert pdf RGB to CMYK for printing

Are you generating a pdf with puppeteer and and then running it through Ghostscript afterwards? The image will technically be CMYK, but they will not match the colors of the CMYK image in the initial HTML file.

**Comment by anre** [comment]
At the moment we are pre-calculating the RGB values using the same ICC color profile as our print-service and only use this RGB colors in our application.

> Are you generating a pdf with puppeteer and and then running it through Ghostscript afterwards? The image will technically be CMYK, but they will not match the colors of the CMYK image in the initial HTML file.

We also tried Ghostscript but as you say it will not be the same as the original picture and it is very slow.

**Comment by dpmott** [comment]
Have you tried specifying `-webkit-print-color-adjust:exact` ?

**Comment by rgevrek** [comment]
Due to the color systems lab and lch are becoming more GA in web standards, the support for exporting alternative color systems as cmyk and lab shall be able to get exported in Chrome and Puppeteer rather than close on inactivity.

**Comment by leemcdole** [comment]
Would like to see this issue re-opened.  I'm also experiencing this, and have confirmed that the image linked in the initial ticket has been converted to RGB when inserted into a pdf via puppeteer as in the example code.

Or has this functionality been added and there's a flag one needs to specify to preserve CMYK format?

**Comment by DavidVaness** [comment]
> Due to the color systems lab and lch are becoming more GA in web standards, the support for exporting alternative color systems as cmyk and lab shall be able to get exported in Chrome and Puppeteer rather than close on inactivity.

I am also in need for this. What is a good alternative solution to this? Need to generate PDF to CMYK spec

**Comment by hubertmuller** [comment]
Cmyk space is limited comparing to rgb. Isnt this good approach to convert all rgb images and rgb colors to safe rgb that will easily convert to cmyk versions?

**Comment by rgevrek** [comment]
If the image is originally created as cmyk then converting it to rgb to convert it to cmyk again while printing will affect color appearance of the print. But if you are capable of defining colors cmyk or even better lab* or lch, the right color tone will be used.
