### ISSUE TITLE
Event targetcreated does not trigger in headless mode

### ISSUE THREAD

**Issue by terius7** [puppeteer/puppeteer#6481]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: AWS Lambda
* URLs (if applicable):
* Node.js version: 12.x

**What steps will reproduce the problem?**
I followed what Joel recommended in this link https://github.com/puppeteer/puppeteer/issues/386#issuecomment-343059315. However, it cannot detect targetcreated event when puppeteer is set to headless. However, it works when it's changed to headful.

`const newPagePromise = new Promise(x => browser.once('targetcreated', target => x(target.page())));
            await row.click('td:nth-child(4) > a');
            const newPage = await newPagePromise;`

**What is the expected result?**
After the button is clicked, a new tab is opened and **targetcreated** event is triggered and detected.

**What happens instead?**
No **targetcreated** event is NOT detected when the new tab is opened in headless mode.

**Comment by vsemozhetbyt** [comment]
Are you sure the new tab is opened? Could it be an issue with the click in a headless mode?
