### ISSUE TITLE
Commitlint throws away commit message

### ISSUE THREAD

**Issue by TimvdLippe** [puppeteer/puppeteer#6489]
When I write a commit message for Puppeteer, I tend to forget the structure of commitlint. As such, when I finish writing my commit message, `husky` runs `commitlint` and starts to show errors. However, in the process of doing so it throws away my commit message.

Can we update our `commitlint` configuration to leave the commit message intact, to prevent accidental deletion of the commit message that I wrote?

**Comment by mathiasbynens** [comment]
Note that it prints the commit message you entered to stdout, so you could still grab it from there. 

Open to patches that improve this!
