### ISSUE TITLE
How to prevent images from loading?

### ISSUE THREAD

**Issue by sean-hill** [puppeteer/puppeteer#649]
Hey there, I'm coming from a Nightmare / Electron background. Within Nightmare I was able to set preferences like this to disable images from loading on the page:

```json
webPreferences: {
  "images": false
}
```

I was wondering if there is a way to do this as well with puppeteer instead of the block images example in the repo. Thanks!

**Comment by aslushnikov** [comment]
> I was wondering if there is a way to do this as well with puppeteer instead of the block images example in the repo.

So far there's no such option. Why doesn't the approach described in `block-images` work for you?

**Comment by sean-hill** [comment]
It doesn't work for me because the `request.resourceType` is `undefined` in every request that is made 😢

**Comment by ebidel** [comment]
@sean-hill `request.resourceType` hasn't made it to a release yet. It was[ added 4 days ago](https://github.com/GoogleChrome/puppeteer/pull/590) :) 

In the meantime, you can nom install from master or use the [demo's old approach ](https://github.com/GoogleChrome/puppeteer/pull/590/files#diff-27ffce13ddfe904190e4f878966614bbL27) for checking image requests.

**Comment by sean-hill** [comment]
Thank you!!!

**Comment by berstend** [comment]
I made a [plugin for resource blocking](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-block-resources), In case anyone else want's to avoid boilerplate as well:

```es6
puppeteer.use(require('puppeteer-extra-plugin-block-resources')({
  blockedTypes: new Set(['image', 'stylesheet'])
}))
```
