### ISSUE TITLE
ERROR: Failed to set up Chromium r800071! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by lilithebowman** [puppeteer/puppeteer#6492]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: N/A
* Platform / OS version: PopOS Linux
* URLs (if applicable):
* Node.js version:
```
# node -v
v10.19.0
# npm -v
6.14.8
```

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `npm install -g puppeteer`

**What is the expected result?**
It installs

**What happens instead?**
```
# npm install -g puppeteer

> puppeteer@5.3.1 install /usr/local/lib/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r800071! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@5.3.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@5.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-08T18_28_23_193Z-debug.log
# echo $PUPPETEER_SKIP_DOWNLOAD
true
```

**Comment by geongeorge** [comment]
Here's something that works for me: https://github.com/puppeteer/puppeteer/issues/5656#issuecomment-641412196

**Comment by lilithebowman** [comment]
I was able to get my Github Action to work with the latest version of puppeteer.

What a great tool when it works! I have it capturing every page of a site before / after commit and doing a diff using Imagemagick.

I'll close this now as I've figured it out. Thanks!

P.S. My script checks out the PR, then master, the runs a docker machine for LAMP for the first one, screenshots, shuts down docker, runs the 2nd docker instance on master, screenshots, then runs the diff, then JPEGs the diffs, then uploads them as an attachment to the action run. All of that takes 22-25 minutes and results in 22MB of JPEGs at 65% quality 😆 

(Yes I do the diff on the PNGs, before JPEGging, obviously)

**Comment by rosyid-grobogan** [comment]
> ### Steps to reproduce
> 
> **Tell us about your environment:**
> 
>     * Puppeteer version: N/A
> 
>     * Platform / OS version: PopOS Linux
> 
>     * URLs (if applicable):
> 
>     * Node.js version:
> 
> 
> ```
> # node -v
> v10.19.0
> # npm -v
> 6.14.8
> ```
> 
> **What steps will reproduce the problem?**
> 
> _Please include code that reproduces the issue._
> 
>     1. `npm install -g puppeteer`
> 
> 
> **What is the expected result?**
> It installs
> 
> **What happens instead?**
> 
> ```
> # npm install -g puppeteer
> 
> > puppeteer@5.3.1 install /usr/local/lib/node_modules/puppeteer
> > node install.js
> 
> ERROR: Failed to set up Chromium r800071! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
> { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium']
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'mkdir',
>   path: '/usr/local/lib/node_modules/puppeteer/.local-chromium' }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! puppeteer@5.3.1 install: `node install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the puppeteer@5.3.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-10-08T18_28_23_193Z-debug.log
> # echo $PUPPETEER_SKIP_DOWNLOAD
> true
> ```

I have same problem, and I try installation for solving my problem
```
npm i puppeteer
# or "yarn add puppeteer"
```

**Comment by lilithebowman** [comment]
I had to use --unsafe-perms to install it successfully

**Comment by nullromo** [comment]
*`--unsafe-perm`, not `--unsafe-perms` 😉

**Comment by ashish6194** [comment]
npm install --ignore-scripts puppeteer

**Comment by liby** [comment]
> npm install --ignore-scripts puppeteer

For yarn, `yarn add --ignore-scripts puppeteer`.

**Comment by piyushpalod** [comment]
For me this is working fine on local , but I got same error on Jenkins , any fix for that ?

**Comment by abubalo** [comment]
I set `export PUPPETEER_SKIP_DOWNLOAD=true` on bash terminal then reinstalled it and it work fine. If you are on windows, I think the syntax looks like this: `SET PUPPETEER_SKIP_DOWNLOAD=true`

**Comment by williamAdson** [comment]
> npm install --ignore-scripts puppeteer

This was the error I encountered when I used
`npm i puppeteer`
then I inserted ignore-scripts and it worked like a charm
`npm i --ignore-scripts puppeteer`

` 
npm i puppeteer
npm ERR! code 1
npm ERR! path C:\Users\zero\Projects\scrapeTheWeb\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! ERROR: Failed to set up Chrome r115.0.5790.102! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! [Error: EPERM: operation not permitted, mkdir 'C:\Users\zero\.cache'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Users\\zero\\.cache'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\users\zero\AppData\Roaming\npm-cache\_logs\2023-08-02T12_56_45_152Z-debug-0.log
`

**Comment by ygcedu** [comment]
I solve the problem use this config, `npm config set PUPPETEER_DOWNLOAD_BASE_URL https://cdn.npmmirror.com/binaries/chrome-for-testing`
