### ISSUE TITLE
How to select iframe with a selector?

### ISSUE THREAD

**Issue by sean-hill** [puppeteer/puppeteer#650]
Hey there, is there a way to use the `.childFrames()` function to lookup an iFrame with a CSS selector? For instance:

```html
<iframe class="super" src="http://iframe.com" />
```

I'd like to use `iframe.super` as my selector to switch frames with. Thanks!

**Comment by twalpole** [comment]
Duplicate of #433

**Comment by aslushnikov** [comment]
Thanks @twalpole
