### ISSUE TITLE
mocha-utils defaultBrowserOptions don't take values from mocha config into account

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#6500]
When running the Puppeteer unit tests we currently have setup a [timeout of 25s when connecting to Firefox](https://github.com/puppeteer/puppeteer/blob/main/mocha-config/puppeteer-unit-tests.js#L27). Sadly these values are [not taking into account by mocha-utils](https://github.com/puppeteer/puppeteer/blob/main/test/mocha-utils.ts#L79-L87).

As result some of the tests in browser.spec.ts are failing because these depend on a non set custom timeout value from the config.

@mathiasbynens or @jackfranklin is that something you could fix? I would kinda appreciate that. I don't see a reason why the default config values shouldn't be used here. Thanks!

**Comment by whimboo** [comment]
Not sure if this issue is still valid or not. The location of both files have been changed and I cannot see where the default settings from [.mocharc.cjs](https://github.com/puppeteer/puppeteer/blob/main/.mocharc.cjs) are actually used. @OrKoN maybe you have a pointer or idea?

**Comment by OrKoN** [comment]
There is .mocharc.cjs and test/src/mocha-utils.ts now. Could you see if this still reproduces? I have been running Firefox tests for refactoring recently and have not noticed anything unusual.

**Comment by whimboo** [comment]
I actually miss the connection between defined constants in the `.mocharc.cjs` file and where these are used? Eg. for the `timeout` of 25s I still cannot find a line of code where it is used for the browser startup. Could you maybe point me to that?

**Comment by OrKoN** [comment]
@whimboo I believe the file is imported by mocha via yargs package directly and the value of `timeout` because an option for the Mocha constructor.

**Comment by OrKoN** [comment]
i.e., I don't think it's used for the browser setup in any way. It's only used to configure Mocha: a test would be considered timed out if it does not resolve within 25 sec.

**Comment by whimboo** [comment]
Ok, so maybe that was an issue with the former `puppeteer-unit-tests.js` mocha config file then. Given that quite some time has been passed since the issue was filed I cannot fully remember. And with a single config file now the problem might no longer exist. I would suggest to close the issue.
