### ISSUE TITLE
UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r800071 is guaranteed to work.

### ISSUE THREAD

**Issue by Losh531** [puppeteer/puppeteer#6502]
Hello! I have an error: `UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r800071 is guaranteed to work.`
### Steps to reproduce
This is my code:
```
(async function example() {

  try {    
    let i = 0;
   
process.setMaxListeners(Infinity);
    while(i < 40){
   
  await delay(Math.floor((Math.random() * 4000) + 2000));
 const browser = await puppeteer.launch({ args: ['--no-sandbox']});;
  const page = await browser.newPage();
  await page.setDefaultNavigationTimeout(0); 
  await page.goto('https://example.com');
  await console.log("At Website")
i++;
    }
  } finally {
    await console.log("ending")
  }
})();
```
**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: Ubuntu-18.4-x86_64
* URLs (if applicable):
* Node.js version: 14.13.1 (Latest)

**What is the expected result?**
Just logs "At Website" 50 times

**What happens instead?**
Logs "At Website" a few times, then says "UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r800071 is guaranteed to work."

**Comment by Losh531** [comment]
Could someone please help???

**Comment by Manitej66** [comment]
Go to **BrowserRunner.js** and Comment the below lines

```js
function onTimeout() {
            //cleanup();
            //reject(new Errors_js_1.TimeoutError(`Timed out after ${timeout} ms while trying to connect to the browser! Only Chrome at revision r${preferredRevision} is guaranteed to work.`));
        }
```

**Comment by Losh531** [comment]
Hmm... @Manitej66 I have puppeteer as an npm package...so I can't edit it's actual files

**Comment by Manitej66** [comment]
> Hmm... @Manitej66 I have puppeteer as an npm package...so I can't edit it's actual files

You can find the BrowserRunner.js file in node_modules

**Comment by Losh531** [comment]
Hmm...If I do `cd node_modules/puppeteer`, and ls There are these files:
```cjs-entry-core.js  cjs-entry.js  install.js  lib  LICENSE  node_modules  package.json  README.md  typescript-if-required.js```
Which file/dir has BrowserRunner.js? I can't seem to find it.

**Comment by Manitej66** [comment]
> Hmm...If I do `cd node_modules/puppeteer`, and ls There are these files:
> `cjs-entry-core.js cjs-entry.js install.js lib LICENSE node_modules package.json README.md typescript-if-required.js`
> Which file/dir has BrowserRunner.js? I can't seem to find it.

**node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js**

**Comment by Losh531** [comment]
Alright thanks so much, it worked!

**Comment by qiaochunmei** [comment]
> Hello! I have an error: `UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r800071 is guaranteed to work.`
> 
> ### Steps to reproduce
> This is my code:
> 
> ```
> (async function example() {
> 
>   try {    
>     let i = 0;
>    
> process.setMaxListeners(Infinity);
>     while(i < 40){
>    
>   await delay(Math.floor((Math.random() * 4000) + 2000));
>  const browser = await puppeteer.launch({ args: ['--no-sandbox']});;
>   const page = await browser.newPage();
>   await page.setDefaultNavigationTimeout(0); 
>   await page.goto('https://example.com');
>   await console.log("At Website")
> i++;
>     }
>   } finally {
>     await console.log("ending")
>   }
> })();
> ```
> 
> **Tell us about your environment:**
> 
> * Puppeteer version: 5.3.1
> * Platform / OS version: Ubuntu-18.4-x86_64
> * URLs (if applicable):
> * Node.js version: 14.13.1 (Latest)
> 
> **What is the expected result?**
> Just logs "At Website" 50 times
> 
> **What happens instead?**
> Logs "At Website" a few times, then says "UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r800071 is guaranteed to work."

Did you solved it,how to solve this problem ?

**Comment by qiaochunmei** [comment]
> Alright thanks so much, it worked!

Did you solved it,how to solve this problem ?

**Comment by qiaochunmei** [comment]
> Alright thanks so much, it worked!

How did you deal with it

**Comment by Manitej66** [comment]
> > Alright thanks so much, it worked!
> 
> Did you solved it,how to solve this problem ?

    Go to **BrowserRunner.js** and Comment the below lines

```js
function onTimeout() {
            //cleanup();
            //reject(new Errors_js_1.TimeoutError(`Timed out after ${timeout} ms while trying to connect to the browser! Only Chrome at revision r${preferredRevision} is guaranteed to work.`));
        }
```

**Comment by SagarPanchasara** [comment]
Try passing timeout as 0. It solved my problem without tweaking the node_module file:
`
        await puppeteer.launch({
            headless: false,
            args: ['--no-sandbox'],
            timeout: 0,
        });
`
