### ISSUE TITLE
How to find id of element clicked on screen?

### ISSUE THREAD

**Issue by aizazansari** [puppeteer/puppeteer#6503]
I would like to click on elements and store their ids. I have the following code right now which is resulting in an empty event argument in the expose function. What's going wrong?

```
const puppeteer = require('puppeteer');
const fs = require('fs');

(async () => {
let browser = await puppeteer.launch({ headless: false });
let page = await browser.newPage();
// Expose a handler to the page
  await page.exposeFunction('onClick', (event) => {
    console.log(`Event fired: ${event}`);
});

// listen for events of type 'status' and
// pass 'type' and 'detail' attributes to our exposed function
await page.evaluateOnNewDocument(() => {
    window.addEventListener('click', (event) => {
        window.onClick(event);
    });
});

await page.goto("https://www.facebook.com/login");

})();
```

**Comment by vsemozhetbyt** [comment]
Something like this?

```js
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({ headless: false, defaultViewport: null });
    const [page] = await browser.pages();

    await page.goto('https://example.org/');

    await page.exposeFunction('processClick', (data) => {
      console.log(data); // Here you can save the data in Node.js context.
    });

    await page.evaluate(() => {
      document.addEventListener(
        'click',
        (event) => { window.processClick(event.target.innerHTML); }, // Here you can send the data to Node.js context.
      );
    });
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by aizazansari** [comment]
I tried something similar (and also what you mentioned) but event variable only contains {isTrusted: true} and no html content

**Comment by vsemozhetbyt** [comment]
Maybe you send unserializable data? Try to send only strings from browser context to Node.js context.

**Comment by aizazansari** [comment]
It works if I send just plain strings to the processClick function. However, I need to find the id of the element clicked and the event variable only has { isTrusted: true } stored inside. Any insight on this?

**Comment by vsemozhetbyt** [comment]
You can get the id in the browser context and send it: `window.processClick(event.target.id);`

**Comment by aizazansari** [comment]
event only has the isTrusted attribute and nothing else :/ 
Is there any other way to extract the element id?

**Comment by vsemozhetbyt** [comment]
Do you get the `innerHTML` in my example? For me it works.

**Comment by vsemozhetbyt** [comment]
Maybe you can provide your example with the issue? How do you check that event only has the` isTrusted` attribute and nothing else?

**Comment by aizazansari** [comment]
It's solved! The issue with my code at the beginning was that I was not getting the `event.target.id` in the browser context, like you mentioned. Furthermore, the empty values for event.target.id were a result of input fields not having id values; I used name values for them instead. Thanks for your help!
