### ISSUE TITLE
Make reviewing of `new-docs` easier by marking them as binary.

### ISSUE THREAD

**Issue by TimvdLippe** [puppeteer/puppeteer#6507]
The `new-docs` contains the generated output for the documentation website. However, this makes reading/reviewing PRs a bit more difficult, as a lot of it is "noise". Therefore, could the `new-docs` be marked as `binary` in the `.gitattributes` so that GitHub hides the diff?

If you still would want to review the `new-docs` output, a preview deployment GitHub action might be a good solution.

**Comment by mathiasbynens** [comment]
I agree there’s a lot of noise (more than we expected!) due to these `new-docs`. It would be nice to address this in some way, at least until the old docs are fully removed.

However, marking these as `binary` seems like the wrong solution — they’re not binary files. We could just `.gitignore` them (going against our earlier decision, @jackfranklin), and perhaps do a preview deployment as you suggest.

**Comment by jackfranklin** [comment]
The main thing I wanted to achieve with having them in the repo was to ensure that as people worked they didn't introduce any bugs/issues with the documentation. e.g. for each change, I wanted to force that the new-docs were able to be generated successfully and the diff looked reasonable.

What about if we:

1. `gitignore` the `new-docs` folder
2. Ensure on CI for each PR that the docs get generated successfully 
3. Try to add linting or something to ensure all new code is documented via the TSDoc comments
4. Add a GitHub preview deploy to each PR

And that way we'd still ensure the docs are in a good state but avoid the diff noise on each PR.

WDYT?

**Comment by TimvdLippe** [comment]
Since `new-docs` are machine-generated and we don't want git to merge any generated output (instead the docs should be regenerated), marking them as `binary` appears to be appropriate per the git documentation: https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#_binary_files

That said, adding them to the `.gitignore` with the other steps seems like a good solution as well 👍
