### ISSUE TITLE
Wait for a specified time before closing the browser

### ISSUE THREAD

**Issue by nisrulz** [puppeteer/puppeteer#651]
I am trying to wait for a few seconds before the `browser.close()` gets called, but haven't been able to do so in any way by following the api docs. 

I have tried to use just before the call to `browser.close()`
```
await page.evaluate(()=>{
  setTimeout(function () {
      return true;
    }, 3000);
})
```
and 
```
await page.waitFor(() => {
    setTimeout(function () {
      return true;
    }, 3000);
  });
```

What would be the best possible way to achieve a delay while the script is executing?

**Comment by vsemozhetbyt** [comment]
If I understand correctly, `page.evaluate()` here returns immediately after `setTimeout()` call, not after timer's callbak returns.

Maybe you just need something like this?
```js
setTimeout(() => { browser.close(); }, 3000);
```

**Comment by vsemozhetbyt** [comment]
If you do need an async delay, you can use something like this:
```js
function delay(timeout) {
  return new Promise((resolve) => {
    setTimeout(resolve, timeout);
  });
}

(async () => {
  console.log('start');
  console.time('delay');
  await delay(3000);
  console.timeEnd('delay');
})();
```

**Comment by nisrulz** [comment]
@vsemozhetbyt Thank you so much, it worked 😄  . I totally missed the part that I could use `setTimeout` as it is.

Closing this issue now.

**Comment by paulirish** [comment]
your page.evaluate attempt didnt work because the settimeout doesnt return a promise.

this probably the easiest tho:

```js
await page.waitFor(3000);
browser.close();
```

**Comment by IgorKurkov** [comment]
In 2021 puppeteer `waitFor` method is deprecated, so working code below
```
await page.waitForTimeout(3000);
browser.close();
```
