### ISSUE TITLE
Puppeteer hangs after "Invalid header" error is received

### ISSUE THREAD

**Issue by rluba** [puppeteer/puppeteer#6514]
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: currently puppeteer-core@5.2.1 (but observed on many other versions)
* Platform / OS version: Linux Debian "Buster"
* URLs (if applicable): -
* Node.js version: 12.16

**What steps will reproduce the problem?**
We’ve been noticing that Puppeteer sometimes hangs indefinitely after random commands, without ever triggering a time-out. This has been happening for over 6 months using various versions of Puppeteer.
We’ve enabled logging on the protocol level and noticed that whenever Puppeteer hangs, the last response received from Chrome is an "Invalid header" error:
```
puppeteer:protocol:RECV ◀ {"id":2228,"error":{"code":-32602,"message":"Invalid header"},"sessionId":"164907C6ED3C68C03A3CD77C9B22322E"}
puppeteer:error Error: Protocol error (Fetch.fulfillRequest): Invalid header
    at /home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at HTTPRequest.respond (/home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:283:14)
    at /home/app/app/lib/adapters/base.js:108:21
    at /home/app/app/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/home/app/app/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:43)
    at Page.emit (/home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:165:100
```
After that, whatever is the next command will hang indefinitely. In the example above, the next call was a `page.$x(…)` call, resulting in the following message sent:
```
puppeteer:protocol:SEND ► {"sessionId":"164907C6ED3C68C03A3CD77C9B22322E","method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(element, expression) => {\n            const document = element.ownerDocument || element;\n            const iterator = document.evaluate(expression, element, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE);\n            const array = [];\n            let item;\n            while ((item = iterator.iterateNext()))\n                array.push(item);\n            return array;\n        }\n//# sourceURL=__puppeteer_evaluation_script__\n","executionContextId":141,"arguments":[{"objectId":"{\"injectedScriptId\":141,\"id\":6}"},{"value":"//h1[contains(text(), \"Kein Suchergebnis\")]"}],"returnByValue":false,"awaitPromise":true,"userGesture":true},"id":2229}
```
After that, Puppeteer hangs indefinitely. But the actual call after the error doesn't seem to matter. We’ve also observed this with many other calls hanging indefinitely.

_Please include code that reproduces the issue._
It’s difficult to reproduce since it usually only occurs after _days_ of running various puppeteer tasks. We use a new puppeteer instance with a new chrome instance for every task, over many days – until one hangs. 

**What is the expected result?**
The call should at least acknowledge that something went wrong and throw/reject after a certain timeout.

**What happens instead?**
The process hangs indefinitely until killed.

**Comment by felixfbecker** [comment]
I have the same issue. The issue is that Puppeteer simply swallows any errors from `request.respond()`:

https://github.com/puppeteer/puppeteer/blob/d8932ca18722cb97811577277e4d7e3add250d10/src/common/HTTPRequest.ts#L383-L388
