### ISSUE TITLE
Function Ran in Puppeteer Evaluate Not Behaving the Same as in the Dev Console.

### ISSUE THREAD

**Issue by ShiromMakkad** [puppeteer/puppeteer#6517]
# Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: Windows 10 Running on Powershell
* URLs (if applicable):https://www.chegg.com/auth?action=login&redirect=https%3A%2F%2Fwww.chegg.com%2F (set your user agent to something that will definitely get flagged like Chromium on Linux)
* Node.js version: 14.3.0

**What steps will reproduce the problem?**

Go to [this ](https://www.chegg.com/auth?action=login&redirect=https%3A%2F%2Fwww.chegg.com%2F)site and make sure you get flagged as a bot (pretty easy). PerimeterX will show up and provide you with a captcha. I am solving the captcha with 2captcha, but I need to trigger the [data-callback](https://developers.google.com/recaptcha/docs/display#render_param) function which is `handleCaptcha('ANSWER')`. If I call this function in the dev console, it works properly and moves to the next page. If I call it using puppeteer evaluate, it just refreshes the page. 

```
global.browser = await puppeteer.launch({
        headless: false,
        slowMo: 20,
        userDataDir: 'C:\\userData',
    });

    global.page = await browser.pages();

    await page[0].goto("https://www.chegg.com/auth?action=login&redirect=https%3A%2F%2Fwww.chegg.com%2F", {
        waitUntil: 'networkidle2'
    });

twoClient = new Client(global.twocaptchakey, {
                timeout: 300000,
                polling: 5000,
                throwErrors: true
            });

            // This function takes between 10-300 seconds
            const response = await twoClient.decodeRecaptchaV2({
                googlekey: global.sitekey,
                pageurl: page[0].url()
            });

            const answer = response._text;

            console.log("Captcha Answer:");
            console.log(answer);
            //Here is the problem code
            page[0].evaluate(`handleCaptcha("${answer}")`);
            // page[0].evaluate(answer => {
            //     handleCaptcha(answer);
            // }, answer)
            
            //Make sure that no code running later interferes with this
            await page[0].waitFor(10000);
```

[Here](https://pastebin.com/yg1sk5sM)'s the full code in case you want it. 
[Here ](https://github.com/berstend/puppeteer-extra/issues/162) is the same issue popping up in a puppeteer library. It seems to only happen on perimeterX. 

**What is the expected result?**

For the function to work the same as if I put it in the dev console

**What happens instead?**

It simply refreshes the page. This is the same behavior as if you ran the function but passed the wrong argument. I checked to see if my method of passing the argument is fine by trying the alert function and that ran fine. Since this issue is also cropping up in a library and only on PerimeterX, I think there's more to it.

Is it possible for PerimeterX to interfere with the puppeteer evaluate function?

**Comment by duquej** [comment]
I'm running into the exact same issue. Have you found a solution yet?

**Comment by kevindapps** [comment]
Hey having the same issue, has anyone found a solution yet?
