### ISSUE TITLE
I have set the words' color white, but I have found the words in the PDF are gray.

### ISSUE THREAD

**Issue by justns** [puppeteer/puppeteer#6518]
**Tell us about your environment:**

* Puppeteer version:5.3.1
* Platform / OS version: macOS 10.15.6
* URLs (if applicable):
* Node.js version: 12.18.4

const puppeteer = require('puppeteer');
(async () => {
    const footerTemplate = `<div style="width:100%;">
        <div style="font-size: 6px;color:white;line-height: 10px;">04</div>
    </div>`;
    const browser = await puppeteer.launch({
       args: ['--disable-dev-shm-usage', '--no-sandbox']
    });
    const page = await browser.newPage();
    await page.goto('http://www.example.com');
    await page.pdf({
        path: '405.pdf',
        printBackground: true,
        '-webkit-print-color-adjust': 'exact',
        displayHeaderFooter: true,
        footerTemplate,
        margin: {
            top: 80,
            bottom: 80
        },
    })
    await browser.close();
})();

**What is the expected result?**
The words in the footer are white.

**What happens instead?**

The words in the footer are gray.

**Comment by zhinianling** [comment]
You can add "'-webkit-print-color-adjust': 'exact'" when using PDF function,
example：
      await page.pdf({
        '-webkit-print-color-adjust': 'exact'
      });

**Comment by isdigital-github** [comment]
Yes, the same issue here. Rendering white color text as gray and light green as dark green.
