### ISSUE TITLE
Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by BrothersWar** [puppeteer/puppeteer#6519]
### **Steps to reproduce**
**Tell us about your environment:**

Puppeteer version: v3.3.0
Platform / OS version: win64
URLs (if applicable):
Node.js version: v14

**What steps will reproduce the problem?**

1. Launch browser with { headless: false }
2. Scrape some page content
3. await page.close(); await browser.close(); return data;
4. Result processing and then do same things from step 1

**What is the expected result?**
Running app 24/7, relaunch browser (1 or 2) every ~10 sec and handle results

**What happens instead?**
If app runs with 1 browser then after 2+ hours there is an error: Error: spawn ENAMETOOLONG. So the browser won't restart. If it's 2 browsers an error will occurs after 1+ hour.

**Comment by alexandrucancescu** [comment]
I have the same problem when closing and starting browsers often. Only encountered this on windows.

**Comment by yuntao1997** [comment]
I have the same problem when closing and starting browsers often. Only encountered this on windows.
