### ISSUE TITLE
problem with rendering Angular 4 sample app Tour of Heroes

### ISSUE THREAD

**Issue by hekod777** [puppeteer/puppeteer#652]
Hi

When I tried to use rendertron and puppeteer to render the Angular 4 sample app Tours of Heroes, the angular 4 ngFor directives are ignored. All the content related to ngFor failed to render.

Due to the async request for heroes, Tour of Heroes actually has 2 stages of loading
1. load everything except for the ngFor stuff
2. load the ngFor stuff

It seems that headless chrome thinks that after stage 1 of loading, the page has already finished loading. that's why it only renders the stuff without those ngFor async request content.

 I want to know how to let puppeteer correctly detect if the page actually finished loading?

thx!

**Comment by ebidel** [comment]
A URL and code that repros the issue would be helpful.

**Comment by aslushnikov** [comment]
@hekod777 it's hard to judge without reproduction steps, but generally you can use `waitUntil: networkidle` option of the [`page.goto`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options) method. Most of the time it will wait until the page is "loaded enough".

**Comment by hekod777** [comment]
Never mind.

Found the problem.

It's because the tutorial Tour of Heroes actually used a thing called InMemoryWebApi to fake the api call and data. And headless Chrome was simply smart enough to figure out that it's a fake api call and ignored it!

that's why it failed to render those async request content.

thx everyone!
