### ISSUE TITLE
Stand-alone puppeteer app huge after pkg

### ISSUE THREAD

**Issue by FlashThunder** [puppeteer/puppeteer#6525]
Is there any way to make the executable max few megs after using pkg on simple puppeteer app? Right now its > 50MB. Could have used UPX, but it's generally being detected by most antiviruses as suspicious, and it's still > 20MB. Any ideas how could I reduce that? I got feeling that 90% of nodejs is not needed to use puppeteer stand-alone.

**Comment by markarupert** [comment]
Did you get an answer to this?

I just installed Puppeteer and my EXE when from ~80Mb to almost 500MB. Is there a way to take out some of the functionality that I don't need?

**Comment by FlashThunder** [comment]
nope, I didn't get an answer :/
