### ISSUE TITLE
Not able to write a file to disc when executing puppeteer

### ISSUE THREAD

**Issue by nisrulz** [puppeteer/puppeteer#653]
I have tried to use `fs` module to write to a csv file (append information), but it won't let me.
The issue I am getting is that I have a function outside the `run()` function  as below

```js
async function run () {
   // puppeteer code : init and other steps to load a webpage
   writeToFile("text1, text2, text3") // this results in error as shown in next code block
}

function writeToFile(data){
// javascript code to write to a file.
}

```

error
```
Error: Evaluation failed: ReferenceError: writeToFile is not defined
```

Can someone help me out with what I might be doing wrong? I am just trying to call javascript functions while puppeteer code is executing.

**Comment by vsemozhetbyt** [comment]
Can you provide a bit more detailed code, maybe some small complete example?

**Comment by nisrulz** [comment]
@vsemozhetbyt I will be traveling for some time. So will get back to you with an example code asap.

**Comment by Garbee** [comment]
Doing a quick test with that structure works here. So something smells fishy with your exact code setup and scoping.

<details>
<summary>Test</summary>

```javascript
async function run() {
  await Promise.resolve();
  writeToFile('hello');
}

function writeToFile(data) {
    console.log(data);
}

run();
```

</details>

**Comment by nisrulz** [comment]
@Garbee Thanks for the response. I can re check my code for scope issue and then respond back with the results.

**Comment by nisrulz** [comment]
@Garbee I figured out the solution and was able to write the file properly. Thank you for your help. Closing this issue now.
