### ISSUE TITLE
chrome of puppeteer installed on raspbian in 64bit

### ISSUE THREAD

**Issue by vay3t** [puppeteer/puppeteer#6531]
# Real issue
https://github.com/AliasIO/wappalyzer/issues/3423

### Steps to reproduce

* Puppeteer version: 5.3.1
* Platform / OS version:
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
* URLs (if applicable): https://google.com
* Node.js version: v14.13.1

_Please include code that reproduces the issue._

1. `sudo yarn global add wappalyzer`
2. `wappalyzer https://google.com -d`

**What is the expected result?**
run wappalyzer

**What happens instead?**
output:

```
wappalyzer | log | driver | Launching browser...
Error: Error: Failed to launch the browser process!
/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: 26: /usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: Syntax error: Unterminated quoted string


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at Driver.init (/usr/local/share/.config/yarn/global/node_modules/wappalyzer/driver.js:172:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/local/share/.config/yarn/global/node_modules/wappalyzer/cli.js:83:5
```

**Comment by QUDUSKUNLE** [comment]
I have a similar issue though with `"puppeteer-core": "2.0.0"`.
 
 `Error: Error: Failed to launch the browser process!
/var/folders/cz/f3b73p6n17q3klv5wy5q0p280000gn/T/chromium: /var/folders/cz/f3b73p6n17q3klv5wy5q0p280000gn/T/chromium: cannot execute binary file`


`TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md`

    `at Driver.init (/Users/andeladeveloper/D3/texAu/texau-lambda-functions/node_modules/wappalyzer/driver.js:178:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at module.exports (/Users/andeladeveloper/D3/texAu/texau-lambda-functions/src/wappalyzer/wappalyzer.js:32:5)
    at module.exports.wappalyzer (/Users/andeladeveloper/D3/texAu/texau-lambda-functions/handler.js:639:16)`
