### ISSUE TITLE
Failed to reserve memory for new V8 Isolate

### ISSUE THREAD

**Issue by migliori** [puppeteer/puppeteer#6532]
### Steps to reproduce

**Tell us about your environment:**

Linux Litespeed server with PHP 7.4

* Puppeteer version: 5.3.1
* Platform / OS version: Centos 7
* Node.js version: v12.19.0

**What steps will reproduce the problem?**

I got a script.js to scrape a webpage, I need to call it with PHP:

```
$ret = exec('/usr/bin/node --max-old-space-size=8192 /home/domain.com/api/script.js 2>&1', $out, $err);
var_dump($out);
```

The script:
- works perfectly in command line
- works perfectly with PHP Apache
- fails with a Timeout error when I enable the Litespeed server

When I kill the process before it returns the timeout I can see that the browser is launched successfully,
but `page = await browser.newPage()` fails.

Here's the output:

```
Starting browser
DevTools listening on ws://127.0.0.1:45999/devtools/browser/089d2bef-d221-4cbb-a6c8-c6ab80df8f67
Browser successfully started
#
Fatal error in , line 0
Fatal process out of memory: Failed to reserve memory for new V8 Isolate
#
FailureMessage Object: 0x7ffee0e8a5e0#0 0x556e1fb15f89

... etc
```

Thanks for your help

**Comment by julie0420** [comment]
I am having the exact same problem on Centos 7.8 and node.js V 14.12.0
`page = await browser.newPage()`
seems to be causing this problem.

I would love advise on this.

**Comment by migliori** [comment]
@julie0420 After trying everything without finding out how to fix this bug, including with the help of my hosting provider, I finally got around the issue.

The idea is that we can switch from Litespped to Apache and reverse with command line.

``` php
// switch to Apache
shell_exec('sudo /usr/local/lsws/admin/misc/cp_switch_ws.sh apache 2>&1; echo $?');

// call the script with PHP
$ret = exec('/usr/bin/node --max-old-space-size=8192 /home/domain.com/api/script.js 2>&1', $out, $err);

// revert to Litespeed
shell_exec('sudo /usr/local/lsws/admin/misc/cp_switch_ws.sh lsws 2>&1; echo $?');
```

I call this script once a day with a CRON task, it works perfectly well, hope the idea may help you
