### ISSUE TITLE
UserDataDir doesnt works on 5.3.1

### ISSUE THREAD

**Issue by rusikf** [puppeteer/puppeteer#6539]
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: true, userDataDir: './user_data_test' });
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.screenshot({path: 'example.png'});

  await browser.close();

 })();
```

Freeze with userDataDir, without - works excellent. On 2x works with userDataDir

**Comment by rusikf** [comment]
oops: works with absolute paths, not relative

**Comment by vsemozhetbyt** [comment]
Maybe regression after #6506 ?

**Comment by vsemozhetbyt** [comment]
May be fixed in https://github.com/puppeteer/puppeteer/pull/6506
Try to install tip-of-tree:
`npm install https://github.com/GoogleChrome/puppeteer`
or
`npm install puppeteer@latest`
