### ISSUE TITLE
Empty responses on second page visit in domain with setRequestInterception(true) on some SPA pages

### ISSUE THREAD

**Issue by dwsmart** [puppeteer/puppeteer#6541]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: Windows 10
* Node.js version: 12.16.3

**What steps will reproduce the problem?**

Attempting to use page.goto() on sites built in the sapper framework leads to null responses on second page visits, see sample code fetching from 2 different sapper sites.

```javascript
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setRequestInterception(true);
    page.on('request', async interceptedRequest => {
        try {
            await interceptedRequest.continue();
        } catch (err) {
            console.log(err);
        }
    });

    let r = null
    console.log('Site 1 first page...')
    r = await page.goto('https://tamethebots.com/', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // returns as expected
    console.log('Site 1 second page...')
    r = await page.goto('https://tamethebots.com/services', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // always returns null
    console.log('Site 2 first page...')
    r = await page.goto('https://formvalidation.io/', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // returns as expected
    console.log('Site 2 second page...')
    r = await page.goto('https://formvalidation.io/guide/validators', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // always returns null
    browser.close();
})();
```

**What is the expected result?**

main resource response is returned for all four page.goto() calls

**What happens instead?**
As per the comments, the second page.goto() for each site is always null, with no errors caught for page.goto()
This only happens if `await page.setRequestInterception(true);` is set.

I can't seem to find reason as to why this would happen?

EDIT:  looking at server logs (the first site is mine) there is a request for the second page, and associated resources, which received a 200 status.

**Comment by pvo13** [comment]
@dwsmart I added `page = await browser.newPage()` before every `page.goto` and that solves the error in your demo code. I don't have really a clue about puppeteer, so I'm not sure if it can be helpful.

**Comment by dwsmart** [comment]
@pvo13 Yes, that does seem to work, naturally changing the const = page to let = page. Interesting...

**Comment by dwsmart** [comment]
ah, actually, not quite as reassigning page that it no-longer has `page.setRequestInterception(true);`, adding that back in, same issue.

So you are getting the response, but you couldn't block a request if you needed to.

Only seems to work if you close the browser with  `browser.close();` and open an entire new browser instance. This does work, but you are surely adding to overhead opening and closing the browser?

```javascript
const puppeteer = require('puppeteer');

async function newBrowserPage() {
    let browser = await puppeteer.launch()
    let page = await browser.newPage()
    await page.setRequestInterception(true);
    page.on('request', async interceptedRequest => {
        try {
            await interceptedRequest.continue();
        } catch (err) {
            console.log(err);
        }
    });
    page.on("error", function(err) {
        theTempValue = err.toString();
        console.log("Error: " + theTempValue);
    });
    page.on('pageerror', pageerr => {
        console.log('pageerror occurred: ', pageerr);
    })
    page.on('console', msg => console.log('PAGE LOG:', msg.text()));
    return [browser, page];
}

async function closeBrowserPage(browser, page) {
    await page.close();
    await browser.close();
}

(async() => {
    let [browser, page] = await newBrowserPage();
    let r = null
    console.log('Site 1 first page...')
    r = await page.goto('https://tamethebots.com/', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // returns as expected
    await closeBrowserPage(browser, page);
    [browser, page] = await newBrowserPage();
    console.log('Site 1 second page...')
    r = await page.goto('https://tamethebots.com/services', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // returns as expected
    await closeBrowserPage(browser, page);
})();
```

**Comment by pvo13** [comment]
@dwsmart You are correct, right now the browser has to be closed and launched again to handle another page. I suspect this is not how it should work.

**Comment by dwsmart** [comment]
OK, so this appears to be service worker related, adding: 
`await page._client.send('Network.setBypassServiceWorker', { bypass: true });` solves the issue, here in context of the example:

```javascript
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page._client.send('Network.setBypassServiceWorker', { bypass: true });
    await page.setRequestInterception(true);
    page.on('request', async interceptedRequest => {
        try {
            await interceptedRequest.continue();
        } catch (err) {
            console.log(err);
        }
    });

    let r = null
    console.log('Site 1 first page...')
    r = await page.goto('https://tamethebots.com/', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // returns as expected
    console.log('Site 1 second page...')
    r = await page.goto('https://tamethebots.com/services', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // now returns as expected
    console.log('Site 2 first page...')
    r = await page.goto('https://formvalidation.io/', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // returns as expected
    console.log('Site 2 second page...')
    r = await page.goto('https://formvalidation.io/guide/validators', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
    console.log(r) // now returns as expected
    browser.close();
})();
```

**Comment by pvo13** [comment]
Your demo code also works for me, good work! Out of curiosity I added it to rendertron but it broke more than it fixed. I didn't try too hard though. But I think this could be good stating point.

**Comment by ntgussoni** [comment]
> OK, so this appears to be service worker related, adding: `await page._client.send('Network.setBypassServiceWorker', { bypass: true });` solves the issue, here in context of the example:
> 
> ```js
> const puppeteer = require('puppeteer');
> 
> (async() => {
>     const browser = await puppeteer.launch()
>     const page = await browser.newPage()
>     await page._client.send('Network.setBypassServiceWorker', { bypass: true });
>     await page.setRequestInterception(true);
>     page.on('request', async interceptedRequest => {
>         try {
>             await interceptedRequest.continue();
>         } catch (err) {
>             console.log(err);
>         }
>     });
> 
>     let r = null
>     console.log('Site 1 first page...')
>     r = await page.goto('https://tamethebots.com/', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
>     console.log(r) // returns as expected
>     console.log('Site 1 second page...')
>     r = await page.goto('https://tamethebots.com/services', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
>     console.log(r) // now returns as expected
>     console.log('Site 2 first page...')
>     r = await page.goto('https://formvalidation.io/', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
>     console.log(r) // returns as expected
>     console.log('Site 2 second page...')
>     r = await page.goto('https://formvalidation.io/guide/validators', { timeout: 20000, waitUntil: 'networkidle0' }).catch(e => console.error(e));
>     console.log(r) // now returns as expected
>     browser.close();
> })();
> ```

`await page._client.send('Network.setBypassServiceWorker', { bypass: true });`

worked in my case. Thanks!

**Comment by snehilshah** [comment]
Was facing the same issue due to response from service worker. In latest version `await page._client.send('Network.setBypassServiceWorker', { bypass: true });` is not available. 

Use `await page.setBypassServiceWorker(true)`.
