### ISSUE TITLE
Issues Installing Puppeteer on Manjaro Linux ARM 20.10 (Raspberry Pi 4B)

### ISSUE THREAD

**Issue by MrM21632** [puppeteer/puppeteer#6546]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.3.1
* Platform / OS version: Manjaro Linux ARM 20.10 Xfce on Raspberry Pi 4B 8GB
* URLs (if applicable): N/A
* Node.js version: 14.13.1 with NPM 6.14.7

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Simply run `npm install puppeteer` in a Node project folder.

**What is the expected result?**
Puppeteer should successfully install as a dependency for the given project.

**What happens instead?**
The following error is thrown:

```
> puppeteer@5.3.1 install /home/joshua/nvidia-snatcher/node_modules//puppeteer
> node install.js

The chromium library is not available for arm64:
If you are on Ubuntu, you can install with:

 apt-get install chromium-browser

/home/joshua/nvidia-snatcher/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
            throw new Error();
            ^

Error
    at /home/joshua/nvidia-snatcher/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
    at FSReqCallback.oncomplete (fs.js:181:21)
```

I'm currently not sure what its causing this issue, since Chromium is (AFAIK) correctly installed on my device:
```
$ chromium --version
86.0.4240.75 Arch Linux ARM
```

**Comment by Write** [comment]
It certainly not the right solution but i did a Symlink from chromium to chromium-browser for it to work.

`ln -s /usr/bin/chromium /usr/bin/chromium-browser`

And i also defined `puppeteer_skip_chromium_download` to `true` in npm settings

Like so : `npm set puppeteer_skip_chromium_download true`

**Comment by MrM21632** [comment]
Adding the symlink worked, as non-ideal of a solution as it is. Thanks!
