### ISSUE TITLE
Compatible issue with node@10.13 - node@10.17

### ISSUE THREAD

**Issue by Brooooooklyn** [puppeteer/puppeteer#6548]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `5.4.0`
* Platform / OS version: `macOS 10.15.17
* URLs (if applicable):
* Node.js version: `10.15.0`

`fs.promises` is experimental in `node@10.13 ~ node@10.17`, so the result of `Object.getOwnPropertyDescriptor(require('fs'), 'promises').enumerable` is `false`, which means https://github.com/puppeteer/puppeteer/blob/main/src/common/helper.ts#L322 this line would throw `Can not read property open from undefined`

**Comment by mathiasbynens** [comment]
Jack, this is related to the agnostification work. Could you PTAL?

**Comment by jackfranklin** [comment]
Ah, this is unfortunate. Our CI does run on 10.X but it runs on 10.19 so we managed to circumvent this problem.

I guess we can introduce a helper whilst we have to support <10.19 to ensure we get the import from the right place, #6549 looks like a good start, thanks!
