### ISSUE TITLE
eval vs evaluate && frame.eval.. vs page.eval..

### ISSUE THREAD

**Issue by uptownhr** [puppeteer/puppeteer#655]
Can someone please describe what the differences are and why page.$eval does not work? it seems only page.evaluate actually works.

**Comment by aslushnikov** [comment]
@uptownhr could you please post the code snippet that doesn't work for you?

**Comment by paulirish** [comment]
@uptownhr  just to make sure you're on >= 0.10.2?

**Comment by aslushnikov** [comment]
Speculatively closing this; feel free to write back if this doesn't work for you with puppeteer 0.10.2.
