### ISSUE TITLE
Page.PDF is wrapping text to a new line

### ISSUE THREAD

**Issue by stevesendsgit** [puppeteer/puppeteer#6554]
We're having an issue where text is wrapping when we render a PDF. The HTML previews ok and page.screenshot renders as expected, however, the output PDF has the text wrapped to a new line.

I've reproduced this locally on MacOS and have included a zip of the code to run.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.4.1
* Platform / OS version: MacOS Catalina (10.15.7) and node:12.13.0-stretch (Debian) Docker based env.
* Node.js version: 12.18.1 (MacOS), 12.13.0 (Linux)

**What steps will reproduce the problem?**
```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-gpu',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--homedir=/tmp',
      '--data-path=/tmp/data-path',
      '--disk-cache-size=0',
      '--disk-cache-dir=/tmp/cache-dir',
      '--font-render-hinting=none',
    ], // All mandatory
    ignoreHTTPSErrors: true,
  });
  const page = await browser.newPage();
  await page.goto('http://pptr-pdf-text-wrap.s3-website-us-east-1.amazonaws.com', {
    waitUntil: ['networkidle0', 'load'],
    timeout: 0
  });

  await page.waitForSelector('#page');
  await page.waitForTimeout(2000);

  const width = 1588;
  const height = 2246;

  await page.addStyleTag(
    {'content': `@page { size: ${width}px ${height}px; margin: 0; }`}
  )

  await page.setViewport({
    width: width,
    height: height,
  });
  await page.screenshot({
    path: 'text-wrap.png',
  });

  await page.pdf({
    path: 'text-wrap.pdf',
    printBackground: true,
    pageRanges: '1',
    width: width,
    height: height,
  });

  await browser.close();
})();
```

1. Unzip [pptr-pdf-text-wrap.zip](https://github.com/puppeteer/puppeteer/files/5455296/pptr-pdf-text-wrap.zip)
2. NPM install
3. Run node index.js

**What is the expected result?**
PDF has the text "Enter Text Here" on a single line as per the PNG and HTML preview
[text-wrap](https://user-images.githubusercontent.com/2760477/97507685-6f381780-19c9-11eb-8198-d261c0c7a6d3.png)

**What happens instead?**
PDF has text "Here" word wrapped to a new line. 
[text-wrap.pdf](https://github.com/puppeteer/puppeteer/files/5455303/text-wrap.pdf)

**Comment by stevesendsgit** [comment]
Bump... anyone run into this issue before?

**Comment by dpmott** [comment]
It's always boiled down to a CSS/HTML layout issue when I've had this issue.  

That is to say, the div holding your text might not be the full width of the page.  I believe that the images will still render at their full width unless you constrain them to resize into their div containers.

I suggest that you enable some type of border around your text to see what the actual shape of that bounding box really is.

**Comment by Florianbwdcon** [comment]
Hello,
I ran into a similar issue with Puppeteer. I render an EJS template in a Node.js app, and the layout looks fine as long as there’s no line break (e.g., in the title). When a line break occurs, the footer sometimes jumps to the second page of the PDF.

I first experimented with CSS, for example: 
`@page{ size:A4;  margin:5mm}`. 

That helped in some cases, but not consistently.

What ultimately worked was adding temporary debug lines at the end of components and adjusting the layout step by step until everything aligned correctly. I recommend using these debug lines; otherwise, you may spend many hours chasing layout glitches without a satisfying result.

Best regards,
Florian Berwald

Example: ` 
      const probe = document.createElement("div");
      probe.style.position = "absolute";
      probe.style.visibility = "hidden";
      probe.style.height = "297mm"; // A4-Höhe
      probe.style.width = "1px";
      pageEl.appendChild(probe);
      const firstPageHeightPx = probe.getBoundingClientRect().height;
      probe.remove();

      const cut = document.createElement("div");
      cut.className = "__debug_cut_abs";
      Object.assign(cut.style, {
        position: "absolute",
        left: 0,
        right: 0,
        top: firstPageHeightPx - 1 + "px", // letzter Pixel von Seite 1
        height: "1px",
        opacity: "0.9",
        pointerEvents: "none",
        zIndex: 999999,
        WebkitPrintColorAdjust: "exact",
        printColorAdjust: "exact",
      });
      pageEl.appendChild(cut);`
