### ISSUE TITLE
TypeError: page.setCookie is not a function

### ISSUE THREAD

**Issue by ystop** [puppeteer/puppeteer#656]
my code : 
‘’‘
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setCookie(
        {
            name :"aa",
            value : "bb",
            domain:".aa.cn",
            path: "/",
            expires: "2018-08-30T09:34:52.299Z",
        }
   await page.goto('xxxx', {waitUntil: 'networkidle'});
’‘’

**Comment by vsemozhetbyt** [comment]
@ystop Maybe you need to update puppeteer up to v0.10.2.

**Comment by aslushnikov** [comment]
@ystop indeed, what's your puppeteer version?

**Comment by ystop** [comment]
@vsemozhetbyt  @aslushnikov  l update  the version, it's good ! Thanks.

**Comment by UttakarshTikku** [comment]
Hi! I am using puppeteer version 1.0.0 and am unable to set cookies. Could you please help!
