### ISSUE TITLE
Could not find browser revision 809590

### ISSUE THREAD

**Issue by bonesoul** [puppeteer/puppeteer#6560]
* Puppeteer version: 5.4.1
* Platform / OS version: windows x64 & linux x64
* Node.js version: 15.0.1

With the above config, puppeteer reports

`Could not find browser revision 809590`

If I just downgrade it to 5.4.0, everything is fine.

**Comment by akaleeroy** [comment]
No version works, npm installs globally but there's no Chrome download step.

For example 

```
>npm install -g puppeteer@3.0.0
+ puppeteer@3.0.0
added 49 packages from 79 contributors in 4.594s
```

Running a puppeteer script dies with:

```
(node:1416) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 737027. Run "np
m install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (C:\Users\pc\AppData\Roaming\npm\node_modules\puppeteer\lib\Launcher.js
:200:23)
    at async startPuppeteer (D:\Dropbox\Agenda\INCFC\Barometru 2019\Practice culturale de timp liber
 in spatii publice\Sources\gulpfile.js:245:15)
    at async exportCharts (D:\Dropbox\Agenda\INCFC\Barometru 2019\Practice culturale de timp liber i
n spatii publice\Sources\gulpfile.js:259:5)
```
Node.js v13.13.0

I think the problem is `npm update` **no longer downloads and installs Chromium.** This fails to happen silently, and it fails on any version of Puppeteer. You think ah I'll just roll back and it'll work. But no version does because of this. 

Pretty scary bug... :jack_o_lantern: 

Workaround

```js
// gulpfile.js
// (...)
browser = await puppeteer.launch({
      // Point to existing Chrome install because NPM won't install Chromium
      executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'
    });
```

**Comment by cindyloo** [comment]
same here in mac os 10.13.6
chrome 86.0.4240.111 (Official Build) (x86_64)
node 14.15.0
puppeteer/-core 5.4.1

setting PUPPETEER_SKIP_DOWNLOAD has no effect

**Comment by josead** [comment]
My issue was on how I was setting the volumes on docker-compose. if I add 
```
   volumes:
      -  ./:/app
``` 

It throws that error. 
Hopefully it helps somebody.

**Comment by Eiluviann** [comment]
Not an issue for me but it happens for my client

**Comment by Eiluviann** [comment]
**Current workaround is to manually set executablePath**

**Comment by viglucci** [comment]
A workaround that worked for me was to manually set the executable path using ENV in my dockerfile.

`ENV PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable"`.

Additionally, you might like the https://www.npmjs.com/package/chrome-launcher NPM package which also worked.

**Comment by skliarovartem** [comment]
Same here...

**Comment by temberature** [comment]
> A workaround that worked for me was to manually set the executable path using ENV in my dockerfile.
> 
> `ENV PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable"`.
> 
> Additionally, you might like the https://www.npmjs.com/package/chrome-launcher NPM package which also workead.

also solved in windows use same method

**Comment by Xunnamius** [comment]
Getting this error in my Ubuntu GitHub Actions CI pipeline. I'm on version 5.5.0. Only a downgrade to 5.4.0 fixes things.

**Comment by QuarterLab93** [comment]
Try adding the following settings to package.json file.

`  "config": {
    "puppeteer_download_path": "./node_modules/puppeteer/.local-chromium"
  }`

In my Windows environment, the above code works.

**Comment by matthew-nash-cko** [comment]
i commented out the following line in our .npmrc file
`#puppeteer_skip_chromium_download=true`
deleted node modules, reinstalled
worked fine

**Comment by gnuschichten** [comment]
Using node 12 to install backstop fixed the error for me.

It occurred when I switched back with nvm to node 10 and installed backstop. So I removed it and installed it globally under node 12.

**Comment by pkong-ds** [comment]
Failed Attempts
- delete and reinstall node modules folder
- manually set `executablePath` as `~/Applications/Google\ Chrome.app`

Successful Attempt

- used Puppeteer official Chromium version manager `browserFetcher` 

Create browser instance as follows:

```
const puppeteer = require('puppeteer');
.
.
.
const browserFetcher = puppeteer.createBrowserFetcher();
const revisionInfo = await browserFetcher.download("some-chromium-version");
const browser = await puppeteer.launch({
  executablePath: revisionInfo.executablePath
});
```

[Puppeteer Documentation on browserFetcher](https://www.puppeteersharp.com/api/PuppeteerSharp.BrowserFetcher.html)
[Similar Issue on StackOverflow](https://stackoverflow.com/questions/62820586/error-could-not-find-browser-revision-756035-run-npm-install)

**Comment by ali-habibzadeh** [comment]
So much for drop in replacement. Same issue here on the mac

**Comment by sflahave** [comment]
In my case, the solution seems to be just upgrading from Puppeteer v5.4.1 to v9.0.0. That seems to fix it.  No need to download a specific Chromium and specify the executablePath.

**Comment by avazoodev** [comment]
> Try adding the following settings to package.json file.
> 
> ` "config": { "puppeteer_download_path": "./node_modules/puppeteer/.local-chromium" }`
> 
> In my Windows environment, the above code works.

This worked for me! thanks!

**Comment by shindmay** [comment]
I was recently updating the puppeteer from 1.x to the latest one version by another.
Observations:

- This issue arises in 6.0.0 and consists till 7.0.0
- The chrome version was 103.x
- When upgraded to 8.0.0 I also updated Chrome to latest 104.x

The issue is no more for me.
