### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by garosi** [puppeteer/puppeteer#6563]
[Error: EPERM: operation not permitted, unlink 'C:\Users\user\AppData\Local\Temp\puppeteer_dev_chrome_profile-LixSno\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',}]

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.4.1
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version : v14.13.0

**What steps will reproduce the problem?**
await browser.close()
I tried await page.close() but problem not solving

**Comment by Somberor** [comment]
Happens to me too .

**Comment by Jatz** [comment]
This also happens for me.

**Comment by danielshiloah** [comment]
Happens to me too, took me all the way back to 4.0.1 for it to stop happening.
It also leaves the chromium instance open in the background.

**Comment by gaspromov** [comment]
Happens to me too.

**Comment by TheRealMal** [comment]
### Same

**Comment by nikbeznosikov** [comment]
Same

**Comment by denisbrodbeck** [comment]
While this is annoying behaviour, there is a workaround: close *all* pages before closing the browser

```js
// close all pages, fix perm issues on windows 10 (https://github.com/puppeteer/puppeteer/issues/298)
let pages = await browser.pages();
await Promise.all(pages.map(page =>page.close()));
await browser.close();
```

**Comment by feijuncheng** [comment]
Happens to me too.

**Comment by rebelinnovator** [comment]
Same

**Comment by imbhaskarn** [comment]
This happened to me too but I got rid of this using this 
`await page.close();
 await browser.close()
`

**Comment by michael-lloyd-morris** [comment]
The above solutions work, but we also need to make sure this tear down process takes place on SIGINT, SIGUSR1 and SIGUSR2

```
// Make sure Chromium is told to shut down if we are interrupted!!
  process.on("SIGINT", async () => {
    await this.tearDown();
  });
  process.on("SIGUSR1", async () => {
    await this.tearDown();
  });
  process.on("SIGUSR2", async () => {
    await this.tearDown();
  });
```
this.tearDown in the above contains the code @denisbrodbeck gave above in addition to other tear down operations specific to my app.

**Comment by talles-coder** [comment]
Hello, I know it's not the prettiest thing, but I managed to solve this error using the home page that is created when using "puppeteer.launch()" instead of creating a new page,

I changed:

const page = wait browser.newPage();

for:

const pages = await browser.pages();
const firstPage = page[0]

By Cromium's rule, if all tabs/pages are closed it will also close so you don't need to use the command "await browser.close()"
at the end of it all.
