### ISSUE TITLE
Puppeteer Extensions (request handlers, custom methods, ...)

### ISSUE THREAD

**Issue by XavierGeerinck** [puppeteer/puppeteer#6567]
Hi Everyone!

I'm currently loving puppeteer and am using it daily! However while working with it - as with any product - it seems that my codebase is getting larger and larger making it quite hard to keep a correct overview 😊

Therefore I started using an abstraction layer on top of puppeteer called [`puppeteer-extra`](https://github.com/berstend/puppeteer-extra/) but am starting to think more and more that this should be in the official puppeteer repo for obvious extensibility reasons.

The most crucial parts that required extensibility for me while working with puppeteer are:
* Request handlers -> I would love to create multiple request handlers that each do their own thing (e.g. blocking resources, waiting for XHR calls in a custom way, ...)
* Custom methods -> I would love to add custom methods that allow me to for create simplified methods (e.g. clickAndWait, ...)

Is this something that was answered or thought about already? Would it make sense to start integrating extension possibilities within puppeteer? I'd love to hear your thoughts around this!

**Comment by jackfranklin** [comment]
Thanks for this issue and sorry for the lack of replies. I'll leave request handlers to #6735 as that's an ongoing discussion.

RE custom methods, it's not something we've really thought about to be honest. On projects we have that use Puppeteer (we write DevTools e2e tests with Pptr, for example) we have a lot of custom helpers that take the `page` object in:

```
function clickAndWait5Seconds(page: Page) {
  ...
}
```

Whilst that isn't quite as nice as defining custom methods, it's a nice way to build up a library of helpers and means we don't have to add the ability to define custom methods into pptr itself. It also means a developer jumping between two projects that use Pptr won't have to remember which methods are custom vs baked into the library itself.
