### ISSUE TITLE
browser.newPage() times out on Firebase Functions

### ISSUE THREAD

**Issue by danbockapps** [puppeteer/puppeteer#6568]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.4.1
* Platform / OS version: Firebase Functions
* URLs (if applicable):
* Node.js version: 12

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Initialize a new Firebase Functions project with TypeScript
2. Replace index.ts with this: https://github.com/danbockapps/firebase-puppeteer/blob/master/functions/src/index.ts
3. Deploy to Firebase

**What is the expected result?**
The code runs successfully

**What happens instead?**
The code stalls on browser.newPage() and times out after 9 minutes.

**Comment by faisalhakim47** [comment]
I also have this issue, running on nodejs version 10.

**Comment by faisalhakim47** [comment]
I resolved the issue by adding `args: [  '--no-sandbox',  '--disable-setuid-sandbox',]` to puppeteer.launch

I dont know why this is the case, it worked previously without that option.

**Comment by danbockapps** [comment]
@faisalhakim47 That works for me too. (Although I also wonder why it works, or if it's the best solution).

**Comment by lachlanmcdonald** [comment]
Also experiencing the issue on both Node 10 and 12 on `puppeteer@5.4.1`.

**Comment by Krisell** [comment]
I was experiencing the same problem on Firebase Functions. Downgrading Puppeteer worked, as well as the suggestion by @faisalhakim47 above

**Comment by migumelar** [comment]
I also experiencing this issue on `puppeteer@5.5.0` on Node 12. 
@faisalhakim47  suggestion resolved the issue

**Comment by migumelar** [comment]
The issue doesn't occur when I using `chrome-aws-lambda`, so I think the problems is on the chromium binary

**Comment by leoriviera** [comment]
@faisalhakim47, this saved me when using `puppeteer@5.5.0` on Node 12. Cheers, mate.

**Comment by saldous** [comment]
I'm having this issue too. Puppeteer 16.2.0, Firebase functions 3.18.0, Node 16. Works fine in emulator, as soon as I deploy to the cloud it gives "Navigation timeout of 30000 ms exceeded" error 90% of the time just trying to launch the browser. I've even tried increasing the memory to 8GB and makes no difference. Any ideas?
