### ISSUE TITLE
APIs to set pdf meta information and password protect

### ISSUE THREAD

**Issue by kaushiksundar** [puppeteer/puppeteer#657]
Is there a way to set the PDF meta information (the one shown in the below screenshot) and also add a password to open the document?

![screenshot](https://user-images.githubusercontent.com/5235298/29996502-63c20b42-901d-11e7-9ae8-78237084ace7.png)

**Comment by androidfanatic** [comment]
I believe Chrome devtools protocol only supports these options: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF

Anything beyond that is probably outside the scope of this library.

**Comment by ebidel** [comment]
Yep. Best handled by one of the many PDF libs out there.
