### ISSUE TITLE
Firefox version metadata download should respect HTTPS proxy config

### ISSUE THREAD

**Issue by benelliott** [puppeteer/puppeteer#6573]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.4.1
* Platform / OS version: Windows 10
* URLs (if applicable): N/A
* Node.js version: 12.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Use Puppeteer via a proxy
2. Provide proxy config via `HTTP_PROXY` / `HTTPS_PROXY` env vars and `proxy` / `https-proxy` NPM config 
3. Set `PUPPETEER_PRODUCT=firefox`

**What is the expected result?**

Puppeteer's `install.js` should use the provided proxy config when downloading Firefox version metadata from https://product-details.mozilla.org/1.0/firefox_versions.json

**What happens instead?**

Download fails with `ECONNREFUSED`.

===

The problem is that in [install.ts](https://github.com/puppeteer/puppeteer/blob/main/src/node/install.ts#L29), proxy options are configured for the binary data download but not for the Firefox metadata download.

This can be done via the `https-proxy-agent` package which is already a dependency (used in [BrowserFetcher.ts](https://github.com/puppeteer/puppeteer/blob/main/src/node/BrowserFetcher.ts#L581)). I'll look at submitting a PR.

**Comment by gamma032steam** [comment]
For anyone interested, I ended up switching to Playwright in order to work around this.
