### ISSUE TITLE
Injecting a script tag (or script code) to inside every iframe

### ISSUE THREAD

**Issue by gogo9th** [puppeteer/puppeteer#6575]
Hi,

My goal is to re-initialize certain Javascript read-only variables such as window.screen.pixelDepth for the entire page, including iframes in it. I can add a script tag to the top-level HTML by using this code:

```
await page.evaluate(scriptText => {
  const el = document.createElement('script');
  el.type = 'text/javascript';
  el.textContent = scriptText;
  document.head.prepend(el);
}, scriptToInject);
```

However, this does not get applied to the HTML pages loaded by <iframe> tags. I wonder how I can inject Javascript for all HTML pages inside iframes of a top-level page.

**Comment by vsemozhetbyt** [comment]
It seems [`page.evaluateOnNewDocument()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevaluateonnewdocumentpagefunction-args) can help.

**Comment by gogo9th** [comment]
Thanks a lot for your tip. This really works nicely! But now I have one issue that the following code raises an error:

```
Object.defineProperty(document.body, 'offsetWidth', {
   value: 1000, /*OVERRIDING VALUE*/
   writable: false,
   configurable: true
});
```

VM14:73 Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at <anonymous>:73:8


I am trying to overwrite document.body.offsetWidth. However, by the time page.evaluateOnNewDocument() is called, I think the <body> tag has not been parsed and thus the error occurs. Could there be a solution for this...?

**Comment by vsemozhetbyt** [comment]
Maybe add the overriding to the `'DOMContentLoaded'` event listener?

**Comment by gogo9th** [comment]
The problem with `'DOMContentLoaded' `is that this gets called after all tags (including <script> tags) in the `<body>` tag are parsed, but I need to initialize `document.body.offsetWidth` before any script tag in the `<body> `tag starts running...

**Comment by vsemozhetbyt** [comment]
Maybe something like this?

```js
(async function main() {
  await new Promise((resolve, reject) => {
    const interval = setInterval(
      () => {
        if (document.body) {
          clearInterval(interval);
          resolve();
        }
      },
      10,
    );
  });

  // Overriding

})().catch(console.error);
```

**Comment by gogo9th** [comment]
I tried the code, but `<script>` tags are executed before we get into the if statement. 

```
> Interval() called
> <body> tag's <script> tag executed
> Interval() called
> document.body created

```

**Comment by vsemozhetbyt** [comment]
Sorry, I give up)

**Comment by vsemozhetbyt** [comment]
Maybe somebody frome https://stackoverflow.com/questions/tagged/puppeteer can help with the use case.

**Comment by gogo9th** [comment]
Got it, thanks for sharing this link with me. I will try to ask there.

**Comment by vsemozhetbyt** [comment]
Another attempt:

```js
import puppeteer from 'puppeteer';
const browser = await puppeteer.launch();

try {
  const [page] = await browser.pages();

  await page.evaluateOnNewDocument(() => {
    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        if (Array.from(mutation.addedNodes).some(node => node.nodeName === 'BODY')) {
          observer.disconnect();
          Object.defineProperty(document.body, 'offsetWidth', {
             value: 1000,
             writable: false,
             configurable: true
          });
        }
      }
    })
    observer.observe(document, { childList: true, subtree: true });
  });

  await page.goto('https://example.org/');

  const data = await page.evaluate(() => {
    return document.body.offsetWidth;
  });
  console.log(data);
} catch(err) { console.error(err); } finally { await browser.close(); }
```

**Comment by gogo9th** [comment]
Yes, this works nicely. Thanks very much for your clever solution!

**Comment by leandroxmf** [comment]
I guess this is what you are looking for.

Listen to framenavigated event and then with the frame you evaluate your desired javascript.

`page.on("framenavigated", async frame => {
            const url = frame.url(); // the new url

            frame.evaluate(function () {
                alert(window.location.href);
            });

            console.log(url);
        });`
