### ISSUE TITLE
No usable sandbox on CentOS7 server

### ISSUE THREAD

**Issue by maitreya2954** [puppeteer/puppeteer#6576]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.4.1
* Platform / OS version: CentOS 7.8.2003
* URLs (if applicable):
* Node.js version: 12.19.0

**What steps will reproduce the problem?**

1. I am trying to launch the puppeteer with sandbox enabled in CentOS 7 server. So, I checked [TROUBLESHOOTING](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) doc.
2. Unfortunately, User namespace cloning is not supported in the kernel version installed, and moreover, due to restrictions it's not possible to update the kernel version
3. So, I have setup SETUID Sandbox as suggested in the doc. But, when I try to launch puppeteer without `--no-sandbox` and `--disable-setuid-sandbox` arguments, I get the error `No usable sandbox`
4. I couldn't find any working solution from https://github.com/puppeteer/puppeteer/issues/3451 or any google searches

**What is the expected result?**
To run chromium with sandbox without any issues

**What happens instead?**
Error saying **No usable sandbox**

**Comment by maitreya2954** [comment]
I was able to get it working by doing the following steps. Source:  [here](https://frugalisminds.com/how-to-setup-puppeteer-in-centos-7/)

* `cd <project-dir-path>/node_modules/puppeteer/.local-chromium/linux-<revision>/chrome-linux/`
* `sudo mv chrome_sandbox chrome-sandbox`
* `sudo chown root:root chrome-sandbox`
* `sudo chmod 4755 chrome-sandbox`

Chromium seems to automatically search and detect chrome-sandbox without setting CHROME_DEVEL_SANDBOX.

**Comment by oxycash** [comment]
> 

can you share the working docker image?
