### ISSUE TITLE
page.evaluate hangs on certain utf8 characters in args

### ISSUE THREAD

**Issue by pocketjoso** [puppeteer/puppeteer#658]
## Environment
Puppeteer: `0.10.2`
Node: `7.10.1`.
OS: `macOS Sierra`

Reduced test case - hangs forever:
**NOTE: cannot be reproduced via github as the character in question is lost :/**.
I can DM a text file containing it for you to reproduce.
```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
const page = await browser.newPage()
await page.setJavaScriptEnabled(false)
console.log('evaluate')
await page.evaluate(
  () => {},
{
  breaks: '￿' <- Note the character github displays here is _not_ the one that causes it to break.
  // works: 'whatever other characters'
})
console.log('evaluate DONE')
browser.close();
})();
```

**Comment by aslushnikov** [comment]
@pocketjoso can you post the character code? (e.g. ellipsis is `"\u2026"`)

**Comment by pocketjoso** [comment]
According to the file I found it in (not mine) it was `'\f042'`(not confirmed)

**Comment by aslushnikov** [comment]
@pocketjoso does it still fail for you? I failed to reproduce with the following script on current tip-of-tree (v0.13.0):

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true,
    args: ['--disable-setuid-sandbox', '--no-sandbox']
  });
  const page = await browser.newPage();
  await page.setJavaScriptEnabled(false);
  console.log('evaluate');
  await page.evaluate(() => {}, {
    breaks: '\uf042'
  });
  console.log('evaluate DONE');
  await browser.close();
})();

```

**Comment by pocketjoso** [comment]
Not sure that was the character, but I also don't have it at hand at the moment. Feel free to close and I will re-open if I come across the same problem again.
