### ISSUE TITLE
Firefox "connect" not possible

### ISSUE THREAD

**Issue by RobinKnipe** [puppeteer/puppeteer#6580]
### Steps to reproduce

**My environment:**

* Puppeteer version: `"puppeteer-core": "^5.4.1"`
* Platform / OS version: Linux, Kubuntu
* URLs (if applicable): any
* Node.js version: `v14.13.1`
* Browser: `$ firefox -v # Mozilla Firefox 82.0`

**What steps will reproduce the problem?**

1. open a firefox browser in debug mode:
    ```shell
    firefox --start-debugger-server <port>
    ```
2. try to connect to the browser with puppeteer:
    ```js
    puppeteer.connect({ browserWSEndpoint: `ws://localhost:${port}`, product: 'firefox' });
    ```
3. Firefox prompts the user to allow the remote control request:
![image](https://user-images.githubusercontent.com/7834222/98091416-558d4900-1e7d-11eb-93e0-8480b6d0b2d4.png)

**What is the expected result?**
Puppeteer should try and probe the websocket, or browser debug endpoint, but then wait for the user to confirmation with the browser before proceeding. Puppeteer will need to keep hold of the connection information it used (i.e. host/port) and use these same values for subsequent connection attempts. The default behaviour, is for each `connect` attempt to use a different (random) client port each time, instead the port needs to be the same as that authorised through the browser prompt.

**What happens instead?**
The control request prompt is displayed, but puppeteer fails with an error:
```js
ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    readyState: 3,
    protocol: '',
    _binaryType: 'nodebuffer',
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _closeCode: 1006,
    _extensions: {},
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    url: 'ws://localhost:9222',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'socket hang up',
  error: Error: socket hang up
      at connResetException (internal/errors.js:612:14)
      at Socket.socketOnEnd (_http_client.js:493:23)
      at Socket.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1252:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'ECONNRESET'
  }
}
```

**Comment by whimboo** [comment]
The underlying problem here is that Firefox gets started with `firefox --start-debugger-server <port>`. That command line option is not for the `Remote Protocol` but for the integrated Firefox debugger. To start Firefox with `Remote Protocol` (`CDP`) support you will have to use `--remote-debugging-port`.

Also there is #6796 so not sure if connecting to an already instance would work anyway.

**Comment by AlexLeoTW** [comment]
For people facing the same issue: 

- use `--remote-debugging-port` instead
- wait an extra little while before `.connect` since webext `.run` can resolve before `--remote-debugging-port` ready

```ts
await webExt.cmd.run(
  {
    sourceDir: extensionPath,
    firefox: firefoxExecutablePath,
    args: ["--remote-debugging-port=12345"],
  },
  {
    // do not exit firefox immediately
    shouldExitProgram: false,
  }
);

// wait for firefox remote debugging server to be ready
await sleep(1000);
const browser = await puppeteer.connect({
  browserURL: "http://127.0.0.1:12345",
});
```

tested on

- puppeteer@20.7.4
- web-ext@7.6.2
- Firefox `117.0a1` linux x64
