### ISSUE TITLE
Library Not Working In IBM Cloud Foundry

### ISSUE THREAD

**Issue by HussainAli27** [puppeteer/puppeteer#6581]
The library installs chromium package in node modules but can not access it.
The error message is:
/home/vcap/deps/0/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
When we used IBM cloud foundry SSH we were able to locate the above path and file but somehow the library is denied the access to it.

**Comment by hmhaider93** [comment]
I agree with this guy, I am also getting the same error message

**Comment by iojancode** [comment]
same here

**Comment by Pqoh** [comment]
Any solution?
