### ISSUE TITLE
Requesting location services on Chromium asks for OS-level permissions every time

### ISSUE THREAD

**Issue by RyanSchw** [puppeteer/puppeteer#6588]
Requesting location services on Chromium (using `.local-chromium` install) asks for OS-level permissions every time.

### Steps to reproduce

* Puppeteer version: 5.4.1
* Platform / OS version: macOS Catalina v10.15.7
* Running in `headless: false` mode

**What steps will reproduce the problem?**

I'm using `await context.overridePermissions(url, ['geolocation']);` to allow for the geolocation permissions. After I call this function, I get the OS-level permission notification shown below.

1. Load Chromium browser (using the Chromium install that comes with puppeteer) and navigate to a site that asks for permissions
2. macOS will ask for system-level permissions so that Chromium can get location services, accept. This will work, as I can now see my current location in the browser
3. Close out of Chromium, launch a new Chromium browser and go to the same site
4. You should see macOS ask for the same permissions you granted the last time

![image](https://user-images.githubusercontent.com/32225075/98392680-4c8bab80-2026-11eb-9807-96e763c96e9c.png)

I would expect to not see this message after the first time I accept. If I look at System Preferences > Security & Privacy > Privacy > Location Services, I do not see Chromium on that list. I would like to use the chromium install that comes with puppeteer instead of installing chromium on its own and linking the exePath.

**Comment by C2BB** [comment]
I'm running into the same issue!
