### ISSUE TITLE
How to check whether a popup has occurred

### ISSUE THREAD

**Issue by naossoan** [puppeteer/puppeteer#6589]
I'm trying to build a purchase tool for Amazon.

Sometimes when I click add to cart, a message/frame pops up asking me if I want to add some kind of protection, but not always.

https://i.imgur.com/mzeW2aY.jpg

I've read all the documentation regarding popups and read many issues and solutions on and off this git submission but I still don't understand it.

I've sorted something out to click the "no thanks" button if the window does pop up, but if it doesn't pop up, my code breaks and doesn't detect other elements properly to continue the checkout process.

basically I wrote this
```
if (await page.waitForSelector('#siNoCoverage-announce')) { //if it finds the button element for "no thanks"
    await page.click('#siNoCoverage-announce')                      //click the "no thanks" button
} else {
    await page.waitForSelector('#hlb-ptc-btn-native')              //wait for the next button in the process
}
```
What happens if this window doesn't pop up is it waits the timeout period before going to the "else" part of the if statement since it has a 30 second timeout, but if the window hasn't popped up, it doesn't detect the element, so the code breaks at that point.

Is there a way for me to detect specifically whether the popup happens or not, instead of trying to find the DOM button element?

As far as I can tell, it's not an "iframe," though there seems to be 3 empty iframes at the beginning of the body.

https://i.imgur.com/lpoqFw4.jpg

Edit: or if there is a way for me to tell Puppeteer to just click a specific spot on the screen, not an element that would make this slide disappear as well.

**Comment by RyanSchw** [comment]
Are you suggesting listening for an event that fires when the popup occurs? I don't think there's functionality for that, at least nothing that would be simpler than what you have. Also keep in mind [`waitForSelector`](https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pagewaitforselectorselector-options) has options to set the timeout to something less than 30 seconds.

To click a specific spot on the screen, you can use [`mouse.click(x, y[, options]`](https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-mouseclickx-y-options).
