### ISSUE TITLE
Chrome extension is not loaded on headless browser

### ISSUE THREAD

**Issue by tomerb78** [puppeteer/puppeteer#659]
running scenario with `headless:true` cause configured extension not to load.

```javascript
browser = await puppeteer.launch({headless:false,args:[
'--load-extension=/Path/to/extension'
], ignoreHTTPSErrors:true});
```
With the same code running with `headless:false` - the extension is loaded as expected.

Is there any limitation with chrome extension loading on headless browser?

**Comment by aslushnikov** [comment]
Chrome Headless doesn't support extensions.

**Comment by vitalets** [comment]
@aslushnikov any chance to get this feature in the future? 
It would be awesome for testing extensions!

**Comment by aslushnikov** [comment]
>  any chance to get this feature in the future?

@vitalets I'm not aware of any plans.

**Comment by vitalets** [comment]
Ok. Anyway after https://github.com/GoogleChrome/puppeteer/pull/774 extensions do not work even with `headless: false` option, so waiting for https://github.com/GoogleChrome/puppeteer/issues/872 to be shipped.

**Comment by simov** [comment]
@vitalets in the meantime you can use `--disable-extensions-except` to enable only the extensions that you want to test:

```js
var options = {
  headless: false,
  args: [
    '--disable-extensions-except=/path/to/extension/',
    '--load-extension=/path/to/extension/',
  ]
}
```

**Comment by ebidel** [comment]
Nice tip @simo!

**Comment by tlenclos** [comment]
In the meantime we are starting an xvfb server:

 `xvfb-run node test.js`

**Comment by dideler** [comment]
> Chrome Headless doesn't support extensions.

For anyone stumbling on this by searching for how to load extensions in headless Chrome, here's [more info about the decision to not (yet) support extensions in headless Chrome](https://stackoverflow.com/a/45372648/72321).

**Comment by mahnunchik** [comment]
Any news?

**Comment by unadlib** [comment]
So Puppeteer really not going to support the Google Chrome extension?
If that's the case, it's disappointing! 😞

**Comment by adrianmcli** [comment]
What's the current state of the art for testing with extensions then?

**Comment by vitalets** [comment]
> What's the current state of the art for testing with extensions then?

I'm using `headless:false` mode for testing extensions.

**Comment by Paul-Browne** [comment]
For loading **multiple** chrome extensions, you can pass a comma-seperated list;

```javascript
var options = {
  headless: false,
  args: [
    '--disable-extensions-except=/path/to/ext1/, /path/to/ext2/, /path/to/ext3/'
  ]
}
```

Also, i've found that in Version 67 at least, the `--load-extension` flag isn't needed, but in any case this flag will also accept a comma-seperated list.

**Comment by prashanth-sams** [comment]
@Paul-Browne but, this solution doesn't work with browser headless mode right?

Here is how I add the extension in ruby
```
'extension' => [
              Base64.strict_encode64(File.open("/path/your_extension.crx", 'rb').read)
          ]
```

**Comment by Paul-Browne** [comment]
@prashanth-sams No, this doesn't work in headless, just added this as a FYI, since this issue thread was the top google search result for "How to add extensions to puppeteer"

**Comment by purpleroc** [comment]
any news?

**Comment by imfht** [comment]
any news?

**Comment by rageshpayyan** [comment]
> @vitalets in the meantime you can use `--disable-extensions-except` to enable only the extensions that you want to test:
> 
> ```js
> var options = {
>   headless: false,
>   args: [
>     '--disable-extensions-except=/path/to/extension/',
>     '--load-extension=/path/to/extension/',
>   ]
> }
> ```

What is the path to extension for windows box

**Comment by stefan-jevtic** [comment]
Okay, the solution for running headless false  to load extensions is xvfb.
My question is: how can i run 3 browsers in parallel with one xvfb process?

**Comment by wwwsevolod** [comment]
@stefan-jevtic e.g. in 3 different docker containers...

**Comment by BlackHole1** [comment]
Any news?

**Comment by Rishabh570** [comment]
Just to make sure I understand it correctly, I can't use any script inside my chrome ext's logic which pulls up a headless browser?

**Comment by kiransiluveru** [comment]
Any Update??
Thanks....

**Comment by ghost** [comment]
Could I use puppeteer with firefox to use extensions headlessly?

**Comment by KaKi87** [comment]
Hello,

Extensions in non-headless mode are working for me, but not in headless mode.

Is it normal ?

Thanks

**Comment by unixfox** [comment]
Dude the second comment of **this issue** talks about that...

**Comment by KaKi87** [comment]
OP said :
> With the same code running with `headless:false` - the extension is loaded as expected.

**Comment by KaKi87** [comment]
Oups, I misread the OP's message. Sorry

**Comment by KaKi87** [comment]
However, is it planned ?

**Comment by KaKi87** [comment]
Or, is there any other way using NodeJS to make a window invisible in both Windows and Linux ?

**Comment by ghost** [comment]
@KaKi87 xvfb on linux, and for windows a virtual machine is all I can think of

**Comment by Prizrak11** [comment]
My question is about the use of extensions in the chrome web store, can i use extensions of this site? thanks

**Comment by twigs67** [comment]
I'm using xvfb, but the extension isn't running. Wondering if anyone can help a guy out over here?

**Comment by vogloblinsky** [comment]
This can also help : https://github.com/mujo-code/puppeteer-headful

**Comment by dword-design** [comment]
I finally got it running using [xvfb](https://github.com/Rob--W/node-xvfb) right in JS, restarting it each time before I create a puppeteer browser. Had serious permission issues when not running it on root, so I switchted back to root and fixed the permissions after the docker run. Now it works pretty flawlessly but it was a big headache. Maybe I'll write a blog article about it.

**Comment by deepak-mali** [comment]
Please write a blog. 🙏

**Comment by Tarjei400** [comment]
I am not sure if this will apply to puppeteer, but I had a use case I needed to launch selenium headful browser with loaded extension inside docker. You can try to follow my footsteps I described it here: 
https://techyon.dev/running-headfull-chrome-with-selenium-and-nodejs/

**Comment by Alm0g** [comment]
It looks like a possible solution was introduced:
https://bugs.chromium.org/p/chromium/issues/detail?id=706008#c36
It seems to be broken as for v109 but looks like it was working up until this point.

**Comment by Bezeerra** [comment]
In my case I managed to solve this problem by virtualizing the display.
I used xvnc (Virtual Network Computing), so it works invisibly without using a GUI.
Example in python:


```py
import asyncio
from playwright.async_api import async_playwright
from pyvirtualdisplay import Display


async def main():
  with Display(size=(960, 700), backend="xvnc") as disp:
          temp = tempfile.TemporaryDirectory()
          play = await async_playwright().start()
          browser = play.chromium
          args = [
              "--ignore-certificate-errors",
              f"--disable-extensions-except={path_to_extension}",
              f"--load-extension={path_to_extension}",
              "--load-guest-mode-test-extension"
          ]
          launch = await browser.launch_persistent_context(headless=False, user_data_dir=temp.name, args=args)
          page = await launch.new_page()
          response = await page.goto("https://www.google.com.br")
          play.stop()
          disp.stop()


asyncio.run(main())
```

**Comment by cantonalex** [comment]
It is definitely possible to run extensions with headless set to false. I did it with Chrome 120 and Puppeteer 19.7.5

**Comment by divyesh-puri** [comment]
@cantonalex How did you do it?

**Comment by fbuetler** [comment]
Running chrome in headless mode with extension enabled works for me with the following flags:

```js
args = [
    "--headless=new",
    "--disable-extensions-except=/path/to/extension/",
    "--load-extension=/path/to/extension/"
]
```
