### ISSUE TITLE
iframe loading hangs with setRequestInterception(true)

### ISSUE THREAD

**Issue by vkyt** [puppeteer/puppeteer#6592]
I'm facing an issue when loading a cross-region iframe on page.

I'm trying to set up a request interception to inject domain-specific headers in my tests, and there is a cross-region iframe on one of the pages.   

Currently if I enforce `--site-per-process` rule, the iframe loads fine since the requests will run on a separate process that doesn't get tripped by setRequestInterception.
If I disable `--site-per-process`, I can see the requests in the same process being intercepted but the iframe will not fully load.  

In the network calls, I noticed when the iframe successfully loads, there is a javascript call that occurs - 
<img width="1096" alt="Screen Shot 2020-11-08 at 4 10 58 PM" src="https://user-images.githubusercontent.com/5015168/98484552-5526e200-21de-11eb-984a-c61cb8e48723.png">

When the iframe hangs, here are the network calls -
<img width="948" alt="Screen Shot 2020-11-08 at 3 55 52 PM" src="https://user-images.githubusercontent.com/5015168/98484672-2eb57680-21df-11eb-889c-f039fa44dc2b.png">
Prior to the javascript call, there was a blob protocol that imports the script which doesn't seem to get executed when I setup request interception. 

When I log all requests that came thru the interception, I noticed the blob call was never captured even tho in the browser network tab I can see it being returned. 
```js
// setRequestIntereption code - 
      await page.setRequestInterception(true);
      page.on('request', (req) => {
        if (url.includes(domain)) {
           // ...insert headers, do something
          console.log(`Request with extra headers ${url}`)
        } else {
          interceptedRequest.continue();
          console.log(`Request no extra headers ${url}`)
        }
      });
```

**Tell us about your environment:**
* Puppeteer version: 5.4.1
* Platform / OS version: Mac 10.15.7
* URLs (if applicable):
* Node.js version: 10.21

**What is the expected result?**
setRequestInterception should not be blocking the iframe rendering.

**Comment by afaher** [comment]
Stay out of my shit
