### ISSUE TITLE
Sorry, home directories outside of /home are not currently supported.

### ISSUE THREAD

**Issue by JBtje** [puppeteer/puppeteer#6595]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.4.1 (latest)
* Platform / OS version: Ubuntu 20.04 TLS
* URLs (if applicable):
* Node.js version: v14.13.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Start an AWS t4g (ARM) instance with Ubuntu 20.04 (preconfigured with apache)
2. Create directory in home folder, e.g. test (as user "ubuntu)"
3. Create test file: __test.js__
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle2'});
  await page.pdf({path: 'test.pdf', format: 'A4'});

  await browser.close();
})();
```
4. install nvm
```
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
source ~/.profile
nvm install node
```
5. Install puppeteer `npm install puppeteer` (in the test folder)
6. Note: you get an error that the chromium binary does not exist, and the suggestion to install it yourself
7. Install chromium browser `apt-get install chromium-browser`
8. Install missing thing `apt install xdg-utils`
9. run the script: `node test.js`
10. A file is created `test.pdf`
11. All works fine!

12. Run the same script as www-data: `sudo -u www-data sh -c "/home/ubuntu/.nvm/versions/node/v14.13.1/bin/node /home/ubuntu/test/test.js"`
13. __Error...__

**What is the expected result?**
When i preform the exact same steps on a AWS t3 instance, the PDF is generated, even for the `www-data` account. I expected this to happen on the ARM instance as well.

**What happens instead?**
```
(node:13920) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
Sorry, home directories outside of /home are not currently supported.
See https://forum.snapcraft.io/t/11209 for details.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/ubuntu/test/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/home/ubuntu/test/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Based on https://forum.snapcraft.io/t/11209, the suggested solution would be to put the home directory of www-data in the /home folder. However, my assumption is that this will break quite a few other things, and on the t3 instance I didn't have to change anything (www-data home folder still is /var/www).

The t3 instance has content in the `.local-chromium` folder, namely `linux-782078/chrome-linux`, whereas this folder is empty on the ARM instance. My assumption is that this is key to solving the problem???

Any suggestion is welcome!

**Comment by Vanessa-wws** [comment]
hello， when I run docker in gitlab-runner，it also appear this sign. It works well in my PC. please help me

**Comment by sank3** [comment]
Facing same problem with t4g instance ubuntu-focal-20.04-arm64-server instance
