### ISSUE TITLE
psa - zero-dependency puppeteer-alternative in 700-line script

### ISSUE THREAD

**Issue by kaizhu256** [puppeteer/puppeteer#6598]
apologies beforehand for shameless plug ; )

here's a 700-line, zero-dependency gist-file @ https://gist.github.com/kaizhu256/8c91818ca8db033fc9dee4e48277c0ba
using raw websocket to directly task chrome-browser with:

1. create screenshot of https://www.amazon.com
2. scrape `document.documentElement` after webpage's `load` event
3. use `document.querySelectorAll()` to scrape all `href` links from page.

feel free to copy-and-edit the script to suit your current puppeteer-task.

script includes stripped-down hybi-websocket-implementation.
verified working in windows and linux (and likely macos).

feel free to close this issue at anytime.

![image](https://user-images.githubusercontent.com/280571/98747795-e4b6c700-237d-11eb-9254-d4b1c0310481.png)

**Comment by mathiasbynens** [comment]
Cool gist!
