### ISSUE TITLE
Suggestions from chrome-remote-interface

### ISSUE THREAD

**Issue by cyrus-and** [puppeteer/puppeteer#66]
I did a (very) quick survey of the [issues][1] submitted to [chrome-remote-interface][2] so far and selected some features that users seem to struggle with using the low-level Chrome Debugging Protocol API.

- Allow to ignore certificate errors ([`Security.handleCertificateError`]). Self-signed certificates in testing environments are quite common.

[`Security.handleCertificateError`]: https://chromedevtools.github.io/devtools-protocol/tot/Security/#method-setOverrideCertificateErrors

- Support browser contexts ([`Target.createBrowserContext`]) so to avoid launching multiple instances if one wants a pristine session (e.g., `browser.newIsolatedPage()` or even expose the context concept through the API).

[`Target.createBrowserContext`]: https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext

- Provide easy access to CSS rules (e.g., adding, toggling, etc.). This may be tricky and too broad to discuss but users particularly struggle with text-ranges.

These may or may not suit this project so I'm not I'm not filing multiple issues; this is mainly to have a place to discuss about them.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues
[2]: https://github.com/cyrus-and/chrome-remote-interface

**Comment by aslushnikov** [comment]
That's great. Thank you Andrea.

I'll leave references to the issues with actual user scenarios (and **solutions**!) for the record:
- Self-signed ssl certificates for testing: https://github.com/cyrus-and/chrome-remote-interface/issues/183
- Browser contexts to emulate multiple users logging into the service: https://github.com/cyrus-and/chrome-remote-interface/issues/118
- CSS api example: https://github.com/cyrus-and/chrome-remote-interface/issues/153.

Both SSL and BrowserContexts fit great with puppeteer, we should have them.

CSS editing seems to be quite a big and niche API which we might not want to touch now. This is a good candidate for a third-party project atop of puppeteer (and this might be a reason to have #31). It also might be that a simple puppeteer API like `Frame.injectCSS` will address majority of usecases.
