### ISSUE TITLE
How to get response out of puppeteer functions?

### ISSUE THREAD

**Issue by VikramTiwari** [puppeteer/puppeteer#660]
Scenario:
- I am running a test script in browser to test my website
- It's checking a value which is being fetched from database
- I need to get that value out of the puppeteer function to use further in my test suite outside of browser based tests

**Comment by androidfanatic** [comment]
Please post some code.

**Comment by VikramTiwari** [comment]
Was similar to https://github.com/GoogleChrome/puppeteer/issues/653. Closing. Thanks for quick response. 👍
