### ISSUE TITLE
No expected response in Puppeteer, but response visible when tested manually

### ISSUE THREAD

**Issue by pavelsaman** [puppeteer/puppeteer#6601]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.4.1
* Platform / OS version: Linux Manjaro 20.2 Nibia
* URLs (if applicable): https://alpinepro-outlet.cz/
* Node.js version: 15.0.1

**What steps will reproduce the problem?**

```javascript
const puppeteer = require('puppeteer');

const baseUrl = 'https://www.alpinepro-outlet.sk/';
const searchTerm = 'detská';

(async () => {
    const browser = await puppeteer.launch({ 
        headless: false,
        args: [                
            "--start-maximized"              
        ],
        defaultViewport: null
    });
    const page = await browser.newPage();     
    await page.goto(baseUrl);    
    await Promise.all([
        page.type('#fulltext-search-input', searchTerm),
        page.waitForResponse(
            response => response.status() === 200
                && response.url() === encodeURI(baseUrl 
                    + 'Product/Suggest?query=' + searchTerm + '&pageSize=10')
        )
    ]);

    await browser.close();
})();
```

**What is the expected result?**

I expect the script to pass, that is to see the response I'm awaiting with `waitForResponse()`.

**What happens instead?**

It seems puppeteer doesn't type the last "á" into the search field. If I launch a browser with `devtools: true` I never see a request for such a search term. But when, while waiting, I manually delete "á" and input the character again, the request is immediately there and the whole script passes.

I've tried changing the `searchTerm`, it goes like this:

- "šport" => script runs till the end with no error
- "detská" => no request-response, timeout eventually
- "detská " => script runs till the end with no error
- "š" => no request-response, timeout eventually
- "š " => script runs till the end with no error

I've also asked the same question on Stackoverflow [here](https://stackoverflow.com/questions/64757887/no-expected-response-in-puppeteer-but-response-visible-when-tested-manually), but havent's received any comment and/or answers for about 3 days now. That's why I'm eventually posting it here.

**Comment by dpmott** [comment]
I wonder if your search term variable needs to be encoded with a particular UTF encoding?  It's acting like it's expecting another character to follow your one unicode character.

You might be able to use Buffer.from().toString() to generate an output string with a UTF character encoding that will work.
