### ISSUE TITLE
stop dispalying "waitFor is deprecated and will be removed"  message

### ISSUE THREAD

**Issue by ahmedeldeeb25-zz** [puppeteer/puppeteer#6602]
I know that `waitFor` is deprecated and we need to replace it with `waitforX` functions, Although I'm not using `waitFor` anywhere this message keep appear again and again which causes to have a very large log file, and I can't check my logs.

any solution for this?

**Comment by AlexXanderGrib** [comment]
Now there is a 8 replacements of `waitFor` for many different cases. You must replace `waitFor` in your code to any relevant of these method. Here they are:

![`waitForFileChooser`, `waitForFunction`, `waitForNavigation`, `waitForTimeout`, `waitForSelector`, `waitForXPath`, `waitForRequest`, `waitForResponse`](https://user-images.githubusercontent.com/29816814/100391158-a2f77300-3043-11eb-86df-79f8a8291c15.png)

For more info, you can read this - [Docs of `page.waitFor` method, and his replacements](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitforselectororfunctionortimeout-options-args)

**Comment by DanielPadrinoInferstat** [comment]
Same problem. I already changed all uses of `waitFor` for the new recommended methods but I'm still getting logs like this:

![Selection_102](https://user-images.githubusercontent.com/73961527/110332088-aadd9080-7ffe-11eb-9398-fdb249d9a46a.png)

**Comment by omeriko** [comment]
Same problem.
