### ISSUE TITLE
browser.target().page() returns null

### ISSUE THREAD

**Issue by cdpark0530** [puppeteer/puppeteer#6603]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: (puppeteer-core): 5.4.1
* Platform / OS version: Windows 10 64bit / 19041.630 (build)
* URLs (if applicable): https://kor.lottedfs.com/kr/search?comSearchWord=2066576109&comCollection=GOODS&comSort=RANK%2FDESC&comListCount=20&txtSearchClickCheck=Y
* Node.js version: 14.15.0 (top level async is possible)

**What steps will reproduce the problem?**
_Please include code that reproduces the issue._

I wanted to make a backbone demo, but I think it's easier for you to just run this code.
```
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const browser = await puppeteer.launch({
	executablePath: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
	headless: false
});
const page = await browser.newPage();

let pendingTask = false;
page.on("response", async () => {
	pendingTask = false;
});

await page.goto("https://kor.lottedfs.com/kr/search?comSearchWord=2066576109&comCollection=GOODS&comSort=RANK%2FDESC&comListCount=20&txtSearchClickCheck=Y", {
	waitUntil: "networkidle0"
});
const productEl = await waitForSelector(".productMd > a");
await productEl.click({
	button: "right"
});
const newTabButton = await waitForSelector(".custom-contextmenu a");
browser.once("targetchanged", () => {
	pendingTask = false;
});
pendingTask = true;
await newTabButton.click(); // this will create a new tab
while (pendingTask) {
	console.log("Waiting on the product page to be loaded...");
	await sleep(1000);
}

const productPage = await browser.target().page(); // returns null
```

**What is the expected result?**
await browser.target().page() expected to return current page

**What happens instead?**
It returns null

**Comment by Simmyoungsub** [comment]
How about use below statement If you want to get new tab's page?
```
const productPage = await browser.pages().slice(-1)[0];
```
