### ISSUE TITLE
Puppeteer - avoid intercepting focus in headful mode

### ISSUE THREAD

**Issue by assopri** [puppeteer/puppeteer#6606]
When I create new page (in headful mode) it intercepts focus (from the current opened tab or from another applications depending where the focus is at the moment). Can I avoid that behavior (so the focus keep remaining where it was before creating the new page)?

`browser = await puppeteer.launch({
            headless: false,
            args: ["--disable-setuid-sandbox"],
            'ignoreHTTPSErrors': true
        });`

**Comment by vsemozhetbyt** [comment]
Maybe [`page.bringToFront()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagebringtofront) can help to restore the focus.

**Comment by assopri** [comment]
Actually my question is about smth like this https://stackoverflow.com/questions/60587166/how-to-keep-puppeteer-browser-running-background-without-jumping-to-foreground .

**Comment by wangjue666** [comment]
@assopri hi,  I found the solution under windows system

1. Press "Win + R" to open the "run" window, enter the "regedit" command and press enter to open the registry;
2. Find HKEY_CURRENT_USER/Control Panel/Desktop/ForegroundLockTimeout
3. Change this value to any 6 digits or more in hexadecimal (the system defaults to 200000 milliseconds / hexadecimal 30d40)
4. If not, please create a new one;
5. After completion, exit the registry and **restart the computer** for the following settings to take effect.
6. **don't minimize the pop-up browser， Just overlay**

**Comment by Divide-By-0** [comment]
This issue still exists and there's no Mac solution posted here, but this may help: https://stackoverflow.com/questions/60587166/how-to-keep-puppeteer-browser-running-background-without-jumping-to-foreground

**Comment by pirate** [comment]
Still happening on Node v22 with puppteer v22.10.0 (macOS).

Related:
- https://github.com/puppeteer/puppeteer/issues/7815#issuecomment-2143293587

**Comment by valgardgudni** [comment]
> This issue still exists and there's no Mac solution posted here, but this may help: https://stackoverflow.com/questions/60587166/how-to-keep-puppeteer-browser-running-background-without-jumping-to-foreground

The top answer does indeed fix the issue and mentions the following:

"Open Chromium's Info.plist (you may find it here node_modules/puppeteer/.local-chromium/mac-XXXXXX/chrome-mac/Chromium.app/Contents/Info.plist) in an editor and add the following piece after the first <dict> and before <key>:

<key>LSBackgroundOnly</key>
<string>True</string>"

In my case I used the command "node -e "console.log(require('puppeteer').executablePath())"" to get the path to the browser used by puppeteer.

**Comment by pirate** [comment]
Sweet thanks for sharing, do you happen to know the equivalent edits needed for Linux & Windows? @valgardgudni

**Comment by abraaoz** [comment]
The solution:
```js
puppeteer.launch({
  headless: true,
  args: ["--remote-debugging-port=9222"],
});
````
No window, no focus stealing. When you need to visually inspect what's happening, open Google Chrome and go to chrome://inspect/#devices, click "Configure..." and add localhost:9222. All pages appear with live screencast via DevTools.

Two additional things that helped for background tab rendering (so pages behave as if they're focused even in headless mode):
```js
// After creating a CDP session for each page:
await cdpSession.send("Emulation.setFocusEmulationEnabled", { enabled: true });
````
This makes the page think it always has focus, which is important if your automation depends on elements that Chromium lazy-renders only for active tabs.
