### ISSUE TITLE
Failed at the puppeteer@5.5.0 install script

### ISSUE THREAD

**Issue by rthangam** [puppeteer/puppeteer#6609]
Facing this issue while trying to install as root

sh-3.2# npm install -g puppeteer

> puppeteer@5.5.0 install /usr/local/lib/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r818858! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@5.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@5.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2020-11-19T05_52_30_535Z-debug.log

**Comment by 1eandro** [comment]
you have no write permission, the 'mkdir' is not working

you can try install with --save option, once you have a local npm project, which you get with 'npm init'

**Comment by web3-byte** [comment]
the problem may be caused by your internet can't download the newest Chromium，so you can use
`npm install puppeteer --ignore-scripts`  to skip download

and then，when you use the script ，you should set the **executablePath** like

```
const path = require('path');
// the browser path
const path = path.resolve('C:\Program Files\Google\Chrome\Application\chrome.exe')

const browser = await puppeteer.launch({
    executablePath: path
})
```

**Comment by rthangam** [comment]
Thanks guys issue is fixed now.

**Comment by MohamedJakkariya** [comment]
thanks, @xxg233 I have the same issue now fixed.

**Comment by mahdifadaee** [comment]
> 
> 
> the problem may be caused by your internet can't download the newest Chromium，so you can use
> `npm install puppeteer --ignore-scripts` to skip download
> 
> and then，when you use the script ，you should set the **executablePath** like
> 
> ```
> const path = require('path');
> // the browser path
> const path = path.resolve('C:\Program Files\Google\Chrome\Application\chrome.exe')
> 
> const browser = await puppeteer.launch({
>     executablePath: path
> })
> ```
Hello
Thank you for your solution. I did the first command (npm install puppeteer --ignore-scripts) and it worked well. But I do not know how to run this code/command. Could you please explain more? I am not familiar with that.
