### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by mahnunchik** [puppeteer/puppeteer#6610]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: macOS 10.15.7
* URLs (if applicable): -
* Node.js version: v14.15.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Open page
2. Wait for **non-existent** selector
3. Close page

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://example.com');

// not await!
page.waitForSelector('.non-existent').then(() => console.log('it should never happened));

await page.close();
```

**What is the expected result?**

Closing the page normally without errors.

**What happens instead?**

```bash
Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:200:50)
    at ExecutionContext.evaluateHandle (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:151:21)
    at WaitTask.rerun (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:37)
```

**Comment by mahnunchik** [comment]
It seams it may be related:

* https://github.com/puppeteer/puppeteer/issues/3064
* https://github.com/puppeteer/puppeteer/issues/5943
* https://github.com/puppeteer/puppeteer/issues/6594
* https://github.com/puppeteer/puppeteer/issues/3423
* https://github.com/puppeteer/puppeteer/issues/2269

**Comment by marr** [comment]
@mahnunchik Why didn't you `await` the `page.waitForSelector` call? If you add await there, it should fix the issue.

**Comment by mahnunchik** [comment]
@marr omitted `await` is important for the issue. It is simplified version of:

```
await Promise.race([
  page.waitForSelector('.existent').then(() => console.log('fire!')),
  page.waitForSelector('.non-existent').then(() => console.log('it should never happened')),
]);

await page.close();
```

When it is required to wait at least one element from set of elements.

**Comment by dpmott** [comment]
@marr still has a good point, in that you need know that each of those race operations are complete before closing the page out from under them.

Consider this:
```
  const operations = [ page.waitForSelector(...), page.waitForSelector(...), ];
  const winner = await promise.race(operations);
  // do something with the winner
  await Promise.all(operations); // wait for the rest of the operations to finish or time out
  await page.close();
```

It might also be possible to put a catch on each of your operations, so that their failure doesn't cause an error in your scripting:
```
  const operations = [ page.waitForSelector(...), page.waitForSelector(...), ];
  const winner = await promise.race(operations.map(op => op.catch(() => {})));
  // do something with the winner, but check to see if it's undefined first
  await page.close();
```

**Comment by taozuidesongshu** [comment]
The cause of the error has been found and the problem has been resolved
The specific reason is that the tab A you opened was opened when the business was not closed after running.
Then use target.close() to close tab A,
Because tab B and tab A have the same name as target, tab B is also closed by the way. Will explode this error
已找到错误原因，问题已解决
https://blog.csdn.net/Lifemustrough/article/details/119614026

**Comment by teoring** [comment]
I reproduced this issue in v10.2.0.
Node v14.17.1

My code is:

` const browser = await puppeteer.launch({
                    args: [
                        '--no-sandbox',
                        '--disable-setuid-sandbox', // Experimental [adding this 25/01 as it seems to resolve few known issues]
                        '--disable-dev-shm-usage', // Experimental [adding this 25/01 as it seems to resolve few known issues]
                        '--disable-background-timer-throttling',
                        '--disable-backgrounding-occluded-windows',
                        '--disable-renderer-backgrounding',
                        '--use-gl=egl',
                        '--disable-web-security',
                        '--proxy-server="direct://"', // Attempt to increase performance
                        '--proxy-bypass-list=*', // Attempt to increase performance
                        '--disable-features=IsolateOrigins,site-per-process', // Needed to enable iframes
                        '--lang=en-GB', // Experimental (to fix freezing)
                        '--ignore-certificate-errors', // Experimental (to fix freezing)
                        '--disable-accelerated-2d-canvas', // Experimental (to fix freezing)
                        '--disable-gpu' // Experimental (to fix freezing)
                    ],
                        // '--start-fullscreen' ], // Experimental
                    headless: ! cliOptions.headful,
                    handleSIGINT: false,
                    slowMo: conf.d_delayPageActions,
                });
                
                ....

                page.goto( sources[k].url ),
                page.waitForNavigation( { waitUntil: 'networkidle0' } ),
                page.waitForNavigation( { waitUntil: 'load' } )
                await page.waitForSelector( sources[k].accept_cookies_selector, { timeout: 20000, visible: true } );               
`

It was 100% reproducible, url: https://www.era.nl/huizenaanbod

        accept_cookies_selector: "body > div.cookiemelding2020 > div > div.cookieknoppenbar.col-12.col-md-3 > button.btn-success.cookieknop.mt-1",

waitForSelector was causing the behavior.

**Comment by OrKoN** [comment]
You should await the calls before you close the page. Otherwise, they will run on a closed target throwing the error.

**Comment by AmirzhanovRenat** [comment]
vc

**Comment by stramanu** [comment]
To all those who come across this issue, I am sharing my own personal resolution:

(typescript)

	class CPromise<T> {

		static promises: CPromise<any>[] = []
		static clearAll(name: string = null) {
			if (name == null) {
				for (const promise of this.promises) promise.clear();
			} else {
				for (const promise of this.promises.filter(p => p.name == name)) promise.clear();
			}
		}
		static $$<T>(promise: Promise<T>, name = '', ignoreCatch = true) {
			return new CPromise(promise, name, ignoreCatch).promise
		}

		promise: Promise<T>
		private cancelled = false

		constructor(
			public _promise: Promise<T>,
			public name = '',
			private ignoreCatch = false
		) {
			CPromise.promises.push(this)
			this.promise = new Promise((resolve, reject) => {
				_promise.then(a => {
					if (!this.cancelled) resolve(a)
				}).catch(e => {
					if (!this.cancelled && !ignoreCatch) reject(e)
				})
			})
		}

		clear() {
			this.cancelled = true
		}
	}

	const $$ = CPromise.$$

In this way, you can wrap all critical promises inside the CPromise.$$() function (or $$()) and cancel them before closing the page.
For example:

	await $$(page.waitForFunction(() => document.querySelector('#test'), { timeout: 10000000 }, '#asdasd'), 'group-id')

	// --------------------------

	CPromise.clearAll('group-id')
	await page.close()

**Comment by YBPrasad** [comment]
PDF Generation Issue After Upgrading to Node.js 22 (Lambda)

After upgrading our Lambda runtime from Node.js 18 (Amazon Linux 2) to Node.js 22 (Amazon Linux 2023), we started facing intermittent PDF generation failures using puppeteer-core + @sparticuz/chromium.

some pdfs are generating success but some are not below error occured.

TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
    at CallbackRegistry.clear (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72:36)
    at CdpCDPSession._onClosed (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:101:25)
    at #onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:166:21)
    at WebSocket.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:49:30)
    at callListener (/var/task/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (/var/task/node_modules/ws/lib/websocket.js:273:10)
    at Socket.socketOnClose (/var/task/node_modules/ws/lib/websocket.js:1346:15)
    at Socket.emit (node:events:519:28) {
  cause: ProtocolError
      at <instance_members_initializer> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
      at new Callback (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
      at CallbackRegistry.create (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
      at Connection._rawSend (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)
      at CdpCDPSession.send (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
      at #evaluate (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:358:50)
      at ExecutionContext.evaluate (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:273:36)
      at IsolatedWorld.evaluate (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:99:30)
      at CdpPage.createPDFStream (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:772:18)
      at CdpPage.pdf (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:804:37)
}
