### ISSUE TITLE
OAuth tokens instead of page cookies to preserve login state

### ISSUE THREAD

**Issue by agniiyer** [puppeteer/puppeteer#6615]
I'm using page cookies in Puppeteer to save my Google login state in Chrome. Is there a way I can do this using Google OAuth tokens instead of cookies? I've tried the following but it hasn't worked:

```
page.setExtraHTTPHeaders({
    'Authorization': 'Bearer ' + google_token.access_token,
});
```

**Comment by blhagadorn** [comment]
@agniiyer curious why you closed this, did it work?
