### ISSUE TITLE
Loading huge html file 

### ISSUE THREAD

**Issue by smstahir** [puppeteer/puppeteer#6618]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^5.3.1
* Platform / OS version: IBM cloud foundry 
* URLs (if applicable):
* Node.js version:14.15.0

**What steps will reproduce the problem?**
I have an HTML page which has around 500 to 700 A4 pages data. Basically, it is a compliance report which I want to convert from HTML to PDF file.
_Please include code that reproduces the issue._

                  let template = ejs.compile(htmlTemplateEjs);
                  let html = template(data);
                  let options = {
                    displayHeaderFooter: false,
                    margin: {
                      top: "10px",
                      bottom: "10px",
                    },
                    format: 'A4',
                    printBackground: true
                  };
                  const browser = await puppeteer.launch({
                    args: ["--no-sandbox", '--disable-setuid-sandbox'],
                    headless: true
                  });
                  let page = await browser.newPage();
                  page.setDefaultNavigationTimeout(0);
                  await page.setContent(html)
                  pdfFile = await page.pdf(options);
                  await browser.close();
                  return;

**What is the expected result?**
should return a pdf file

**What happens instead?**

RR Error: Protocol error (IO.read): Target closed.
     at /home/vcap/deps/1/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
     at new Promise (<anonymous>)
     at CDPSession.send (/home/vcap/deps/1/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
     at Object.readProtocolStream (/home/vcap/deps/1/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:176:39)
     at Page.pdf (/home/vcap/deps/1/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1229:41)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async pdfGeneration (/home/vcap/app/BLL/mtc.js:6876:29)

**Comment by AlexXanderGrib** [comment]
You may try inline your html as data url and using `page.goto`

**Example:**
```javascript
let template = ejs.compile(htmlTemplateEjs);
let html = template(data);
let options = {
  displayHeaderFooter: false,
  margin: {
    top: "10px",
    bottom: "10px"
  },
  format: "A4",
  printBackground: true
};

const browser = await puppeteer.launch({
  args: ["--no-sandbox", "--disable-setuid-sandbox"],
  headless: true
});
let page = await browser.newPage();
let base64 = Buffer.from(html, "utf8").toString("base64");

await page.goto(`data:text/html;UTF-8;base64,${base64}`);

pdfFile = await page.pdf(options);
await browser.close();

```

**Comment by cliftonlabrum** [comment]
I'm running into the same problem. I am using `goto` to point to a large, 72-page HTML document, but Puppeteer crashes and can't handle it. 

Has anyone found a good way to handle large PDF renderings?

**Comment by MaximilianSchon** [comment]
I was getting this and solved it by hosting a local nodejs server and navigating to localhost:3000 instead of setting the content. I did however also move from puppeteer to playwright (which did not solve the issue) as it seemed to be getting better memory usage, not sure if that actually helped solved the problem though.
