### ISSUE TITLE
Error: Evaluation failed: ReferenceError in waitForFunction

### ISSUE THREAD

**Issue by MarByteBeep** [puppeteer/puppeteer#6620]
When calling the following code:

```javascript
[...]
const options = {
	page: await browser.newPage()
};
await utils.fetchPage("someurl", ".some-selector", options);
```

with the following `fetchPage` implementation:

```javascript
async function fetchPage(p_url, p_waitForSelectors, p_options) {
	assert(p_options.hasOwnProperty('page'));

	await p_options.page.goto(p_url, {waitUntil: 'networkidle2'});

	if (p_waitForSelectors) {
		await p_options.page.waitForFunction(() =>
			document.querySelectorAll(p_waitForSelectors).length
		);
	}

	const html = await p_options.page.content();
	assert(html);
	return html;
}
```

I get the error:

```
[17:39:49] [ERROR]  Error: Evaluation failed: ReferenceError: p_waitForSelectors is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:4:30)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:4:57)
    at onRaf (<anonymous>:49:35)
    at pollRaf (<anonymous>:42:15)
    at waitForPredicatePageFunction (<anonymous>:7:22)
    at ExecutionContext._evaluateInternal (\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WaitTask.rerun \node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:528:23)
```

When replacing `p_waitForSelectors` with the explicit string literal `".some-selector"` all works fine:

```javascript
[...]
		await p_options.page.waitForFunction(() =>
			document.querySelectorAll(".some-selector").length
		);
[...]
```

Is this some weird JavaScript quirk that I somehow misunderstand? Or is this a genuine bug?

I'm using Puppeteer 5.5.0.

**Comment by vsemozhetbyt** [comment]
The function argument of `waitForFunction()` is executed in a browser context, while the `p_waitForSelectors` variable is defined in Node.js (puppeteer) context. You just need to transfer it as an explicit argument:

```js
		await p_options.page.waitForFunction(
			selector => document.querySelectorAll(selector).length,
			p_waitForSelectors
		);
```

**Comment by MarByteBeep** [comment]
Thanks for the reply! I tried that, but that results in a seemingly infinite stall. `waitForFunction` never completes. When using the explicit string, it does complete.

**Comment by vsemozhetbyt** [comment]
That is weird. Be sure you have no typos there. For example, add a `console.log(selector)` call and look into DevTools console:

```js
		await p_options.page.waitForFunction(
			(selector) => {
				console.log(selector);
				return document.querySelectorAll(selector).length;
			},
			p_waitForSelectors
		);
```

**Comment by vsemozhetbyt** [comment]
Oh, sorry, I had an error, [`waitForFunction()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitforfunctionpagefunction-options-args) needs options param before any params for the evaluated function. Try this:
```js
		await p_options.page.waitForFunction(
			selector => document.querySelectorAll(selector).length,
			{},
			p_waitForSelectors
		);
```

**Comment by MarByteBeep** [comment]
That fixed it! @vsemozhetbyt thanks so much for the help!

**Comment by cloydlau** [comment]
but that don't work with **function** type params
```js
function fn () {
}

await page.waitForFunction(
  () => {},
  {},
  fn
);
```
it seems function is not serializable, so what should I do in this situation?

is there a way to exchange data that is not serializable?

thanks

**Comment by vsemozhetbyt** [comment]
@cloydlau Can you describe with an example what you are trying to achieve? Why do you need a function argument for `waitForFunction` function?

**Comment by cloydlau** [comment]
Thanks for the reply.
I wrote a function that needs to be tested in broswer environment. Or from another perspective, this function needs a dom node as argument, so it's also feasible if puppeteer can somehow return a dom node.

**Comment by vsemozhetbyt** [comment]
Is there a way to make this function code a part of the code of the main `waitForFunction` function? If not, you can transfer this function as a string (via `func.toString()`) and recreate it via `new Function()`.

**Comment by cloydlau** [comment]
Ingenious idea, I tried that but run into a weired problem:
```ts
// fn.ts
function fn () {
    console.log(1);
}
```
```ts
// fn.test.ts
import fn from '../src/fn.ts'

fn.toString()
```
The result of ```fn.toString()``` becomes unusable like below in node environment:
```ts
`function fn () {
    /* istanbul ignore next */
    cov_mwhopiwvn().f[1]++;
    cov_mwhopiwvn().s[17]++;
    console.log(1);
}`
```
Which makes ```new Function('return ' + fn.toString())()()``` throws an error: ```cov_mwhopiwvn is not defined```

**Comment by cloydlau** [comment]
It finally works by adding:
```js
const fnStr = fn.toString()
  .replace(/\/\* istanbul ignore next \*\//g, '')
  .replace(/cov_.+\(\)\..+]\+\+;/g, '')
  .replace(/cov_.+\(\)\..+]\+\+,/g, '')

new Function('return ' + fnStr)()()
```

Now I'm working on how to get the result of ```fn```
