### ISSUE TITLE
Using WSL not returning expected Selector

### ISSUE THREAD

**Issue by TonyGemenie** [puppeteer/puppeteer#6623]
Running a simple script using wsl does not return the expected selector.

```
(async () => {

  'use strict';
  const puppeteer = require('puppeteer');
  let browser = await puppeteer.launch({ headless: true});
  let page = await browser.newPage();
  await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) 
    Chrome/73.0.3683.75 Safari/537.3');
  await page.goto('https://old.nasdaq.com/symbol/tsla/historicalm');
  let element = await page.$eval('#qwidget_lastsale');
  console.log(element);

})();
```

Using developer tools on the page delivers the correct element and requesting the entire page is also successful.
```let bodyHTML = await page.evaluate(() => document.body.innerHTML)```

**Comment by RyanSchw** [comment]
You probably need to wait for the element to appear, or the page hasn't entirely finished loading yet. Try adding after your goto
```js
const element = await page.waitForSelector('#qwidget_lastsale');
console.log(element);
```
Also, keep in mind [`page.$()`](https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pageselector) and [`page.$eval()`](https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pageevalselector-pagefunction-args-1) are two very different functions.

**Comment by ashnur** [comment]
```
 const browser = await puppeteer.launch({ headless: false, devtools: true });
 const page = await browser.newPage(); 
 await page.goto('http://localhost:9967', { waitUntil: 'domcontentloaded' });
 await new Promise((r) => setTimeout(r, 5000));
 console.log(await page.evaluate(
    () => {
      const ls = document.querySelector('[data-testid=app]');
      console.log('ls', ls);
      return ls;
    },
  ));
```
1. I tried using waitForSelector and waitForFunction, but kept timing out
2. with Promise setTimeout and headless false, devtools true, I could observe that puppeteer was blocking the app rendering (in this case anyway)
3. using the nested console logs I could verify that the console.log inside puppeteer finds the element and returns it correctly
4. but what comes back from the promise is 'undefined'
