### ISSUE TITLE
How can I run script part and get the content of the page

### ISSUE THREAD

**Issue by jasonkim7288** [puppeteer/puppeteer#6626]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: WSL Ubuntu / 18.04
* URLs (if applicable): https://twitter.com/MarkRober/status/1256956499286298625
* Node.js version: 12.16.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
          try {
            const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
            const page = await browser.newPage();

            await page.goto('https://twitter.com/MarkRober/status/1256956499286298625');
            await page.setJavaScriptEnabled(true);
            const fullContent = await page.content();
            await browser.close();
            console.log(fullContent.match(/.{10}og:.{25}/gi));
          } catch (err) {
            console.log('err:', err);
          }
```

**What is the expected result?**
[ 'property="og:site_name" content="Twitt' ,
  'property="og:url"...',
  'property="og:title"...',
  'property="og:image"...'
]

**What happens instead?**
Only returns [ 'property="og:site_name" content="Twitt' ]

I used the puppeteer not the puppeteer-core. When I see this website with 'inspect' of the browser, I could see those 'og's, but I have no idea how I can get these using puppeteer (I am going to use 'open-graph-scraper' to extract og tag after letting puppeteer run javascript part and get the HTML afterward). 
I tried to use page.setJavaScriptEnabled(true);, but it doesn't seem to do what I want. Is there any way that I can try in?

Thanks.

**Comment by dpmott** [comment]
That regular expression in your `.match()` looks pretty brittle.

Looks like you're searching for things like:
```
<meta property="og:site_name" content="Twitter" />
```

Consider using a regular expression which keys on the structure of the content:
`.match(/property="og:[^"]+"/g)`

If you wanted the whole meta tag, you could search for:
`.match(/<meta property="og:.+?[/]>/g)`

However, your bigger problem is [that page](https://twitter.com/MarkRober/status/1256956499286298625) (as of today) has no tags that match 
```
property="og:url"
property="og:title"
property="og:image"
```

So, Twitter has changed what you're scraping for.

Review the page content and change what metadata you're matching on?
