### ISSUE TITLE
UBUNTU - Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by romeshkosme** [puppeteer/puppeteer#6630]
error :::::::::::::    Error: Failed to launch the browser process!
[629:629:1126/174952.681098:ERROR:browser_main_loop.cc(1439)] Unable to open X display.
[1126/174952.703855:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/ubuntu/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/home/ubuntu/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:79)
    at ChildProcess.emit (events.js:323:22)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

**Comment by AlexXanderGrib** [comment]
Try passing `--no-sandbox` flag in `args` when calling `puppeteer.launch` as described in [Troubleshooting wiki](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox).

Here is a copypaste from here
```javascript
const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
```

**Comment by beemi** [comment]
> Try passing `--no-sandbox` flag in `args` when calling `puppeteer.launch` as described in [Troubleshooting wiki](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox).
> 
> Here is a copypaste from here
> 
> ```js
> const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
> ```

These options doesn't work on Ubuntu latest

**Comment by beemi** [comment]
`export $DISPLAY`

Should work

**Comment by janke184** [comment]
> `export $DISPLAY`
> 
> Should work

Sorry, but where do you put that line?

**Comment by zhongmeizhi** [comment]
The Linux needs to add some 'args'.

example:

```
let launchOptions;
    if (os.type() === "Linux") {
      launchOptions = {
        headless: true,
        slowMo: 1,
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-gpu",
          "--disable-dev-shm-usage",
          "--no-first-run",
          "--no-zygote",
          "--start-fullscreen",
        ],
      };
    } else {
      launchOptions = {
        headless: isHeadless === "1",
        slowMo,
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          isFullscreen === "1" && "--start-fullscreen",
        ].filter(Boolean),
        defaultViewport: {
          width: 1440,
          height: 768,
        },
      };
    }
```

**Comment by rags2riches-prog** [comment]
> 
> 
> Try passing `--no-sandbox` flag in `args` when calling `puppeteer.launch` as described in [Troubleshooting wiki](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox).
> 
> Here is a copypaste from here
> 
> ```js
> const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
> ```

This ain't working on Ubuntu 20.4 (from WSL 2.0 on Windows 11)

**Comment by beemi** [comment]
Use this if you are using Github actions as CI
https://github.com/marketplace/actions/puppeteer-headful-github-action

**Comment by rags2riches-prog** [comment]
I am not using GitHub actions or any other CI/CD pipeline in that respect. 
This is just a simple project with standard boiler plate code. When `headless` is set to false, (I am on Windows 11, running this specific project from Ubuntu 20.4 on WSL 2.0) thing goes south. 
Posting a new issue now
