### ISSUE TITLE
Question : chrumium load mobile view on linux, desktop view on windows  

### ISSUE THREAD

**Issue by anaskasmi** [puppeteer/puppeteer#6631]
I was working on automating some job posting tasks and made a script that works perfectly fine in my local environment (Windows 64) as soon as I uploaded the script to a Linux-server(Ubuntu) the website start to load a different view, a mobile view, (I did know that by taking a screenshot of the page in the server) 

What I tried :

used the same user agent in the local and server environment and the result still different (server load mobile view)
`await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.0 Safari/537.36');
`
I used the same height and width of the page as in my local environment (before visiting the URL)
`await page.setViewport({ width: 1920, height: 1058});
`
this is how I launch the browser
```
async function getNewBrowser() {
    return browser = await puppeteer.launch({
        headless: process.env.HEADLESS_MODE == "true" ? true : false,
        args: ['--start-maximized', '--no-sandbox','--window-size=1920,1058'],
        slowMo: 10
    });
}
```
[Mobile view image
](https://i.stack.imgur.com/9zd1G.jpg)
[desktop view image](https://i.stack.imgur.com/D0Muc.png)

what am I missing?

**Comment by buynao** [comment]
> 

I also encountered this problem, how did you solve it?

**Comment by anaskasmi** [comment]
The problem was that Indeed has multiple servers, one in usa and one in Europe, each one has a different UI (maybe because each region has different laws)
So locally I was seeing the Europe version
But when I host it on the vps I found another UI because the sever was in the USA, 
The solution was to use a vpn in my local environment to get the same UI as the server
Another solution is to use a proxy in you puppeteer script but sometimes it will make things slow
Hope that helps !
