### ISSUE TITLE
Timeout trying to navigate to a site

### ISSUE THREAD

**Issue by uriya2** [puppeteer/puppeteer#6635]
### Steps to reproduce
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://www.ronyohananov.com/', {waitUntil: 'networkidle2', timeout: 200000});
    console.log("done ok");
    await browser.close();
})();
**Tell us about your environment:**
* Puppeteer version:
 version "5.5.0"
 resolved "https://registry.yarnpkg.com/puppeteer/-/puppeteer-5.5.0.tgz#331a7edd212ca06b4a556156435f58cbae08af00"
* Platform / OS version:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
* URLs (if applicable):
https://www.ronyohananov.com/
* Node.js version:
v12.18.1
**What steps will reproduce the problem?**

const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://www.ronyohananov.com/', {waitUntil: 'networkidle2', timeout: 200000});
    console.log("done ok");
    await browser.close();
})();

**What is the expected result?**
Navigation to finish

**What happens instead?**
(node:24491) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 200000 ms exceeded
    ..../node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
(node:24491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24491) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Even with a large timeout the issue persist.

**Comment by saideepesh000** [comment]
@uriya2, (I think) try using timeout 0

**Comment by uriya2** [comment]
I did, didn't work :)

**Comment by andretunes** [comment]
Hello,
I can't reproduce the issue using Windows:
![image](https://user-images.githubusercontent.com/44337068/104852690-579b6b80-58f4-11eb-9896-946f84729f8b.png)
Can you try access that page with a browser (without using the module puppeteer)?

**Comment by uriya2** [comment]
@andretunes I can access the site with a regular browser, which puppeteer version did you use? did you use the same code as I did?

**Comment by andretunes** [comment]
The last version and the same code as you, maybe the problem comes from the Ubuntu side, do you have Anydesk or something else, so that I can take a look?

**Comment by uriya2** [comment]
I believe so but company policy will prohibit such an action :)

**Comment by andretunes** [comment]
Why? Is there any way that I can help you?

**Comment by andretunes** [comment]
Hi!
De Ubuntu server has Interface? If yes, can you disable the `headless` and see what happens?
