### ISSUE TITLE
page.goto (goBack, goForward) without waiting

### ISSUE THREAD

**Issue by nexcode** [puppeteer/puppeteer#6639]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: linux
* Node.js version: 14

**What steps will reproduce the problem?**

```
const response = await page.goto(url, {
    waitUntil: 'domcontentloaded',
});
```

**What is the expected result?**

Promise will resolved after `domcontentloaded` event.

**What happens instead?**

Is it possible to implement **waitUntil: 'immediately'** as in the example below? To get `<HTTPResponse>` as soon as possible without waiting for any events or networkidle?

```
const response = await page.goto(url, {
    waitUntil: 'immediately',
});
```

**Comment by vsemozhetbyt** [comment]
Maybe listening to [`'response'`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#event-response) event can help?

**Comment by nexcode** [comment]
Perhaps yes, but here question is rather the convenience of API. If you listen to the response event separately, you need to make additional checks that this response is exactly the one we are waiting for, etc.
