### ISSUE TITLE
Wrong assumption of Chrome exec path on Apple Silicon M1

### ISSUE THREAD

**Issue by kenny-y** [puppeteer/puppeteer#6641]
I'll make this as short as possible since it's very straightforward (I bet you like it this way for this particular issue)

In `Launcher.js:79`

```
        let chromeExecutable = executablePath;
        if (os.arch() === 'arm64') {
            chromeExecutable = '/usr/bin/chromium-browser';
        }
        else if (!executablePath) {
```

The path provided to puppeteer is: `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`

I'm using ARM64 Node.js v15 compiled by this link: https://www.reddit.com/r/apple/comments/jyfg4m/nodejs_running_native_on_apple_silicon_m1_mac_mini/

**Comment by nc** [comment]
+1

**Comment by yhatt** [comment]
Related: #6495 #6634

**Comment by bjornlll** [comment]
Thanks for pointing us all in the right direction, @kenny-y!
```
        // node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js L:73
        if (os.arch() === 'arm64' && false) {
            chromeExecutable = '/usr/bin/chromium-browser';
        }
```
👆 I patched it directly in my node_modules folder. Will do until an official fix comes out.

**Comment by jhoopmann** [comment]
+1 

and I almost wanted to remount my root as writable to link the chromium browser binary in /usr/bin. Still not fixed.

**Comment by schappim** [comment]
+1

**Comment by schappim** [comment]
What do you need to confirm?
