### ISSUE TITLE
can not get array of elements

### ISSUE THREAD

**Issue by Nuruddin999** [puppeteer/puppeteer#6644]
```
  await page.click("#react-root > section > main > div > div._2z6nI > article > div:nth-child(1) > div > div:nth-child(1) > div:nth-child(1) > a")
  let commentsPage = await page.evaluate(() => document.querySelectorAll("a.sqdOP.yWX7d._8A5w5.ZIAjV").textContent)
  console.log(JSON.stringify(commentsPage))
```
in browser console `document.querySelectorAll("a.sqdOP.yWX7d._8A5w5.ZIAjV")` shows node of 12 elements
but in puppeteer console shows indefined

**Comment by vsemozhetbyt** [comment]
[`document.querySelectorAll()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) returns `NodeList`, which has no `textContent` property.
