### ISSUE TITLE
How can I send a touchmovement? ###.tap can just click.What should I do if I want to drag a object from (X1,Y1) to (X2,Y2)?

### ISSUE THREAD

**Issue by jsjs0827** [puppeteer/puppeteer#6648]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by RyanSchw** [comment]
To drag via mouse, you can do:
```js
const drag = async (fromX, fromY, toX, toY) => {
  // drag from the current mouse location to the x, y coordinate
  await page.mouse.move(fromX, fromY);
  await page.mouse.down();
  await page.mouse.move(toX, toY);
  await page.mouse.up();
}
```

Keep in mind this won't scroll to any elements like you would see in `page.click`. As of `v5.5.0`, there is no functionality for dragging via `touchstart` and `touchend` events.

**Comment by jsjs0827** [comment]
Thank you for helping!  In my condition, operations such as mouse.down() up() do not work.I find another puppeteer module which realizes the touch event.

**Comment by iamstd** [comment]
> Thank you for helping! In my condition, operations such as mouse.down() up() do not work.I find another puppeteer module which realizes the touch event.

which peppeteer module you import ? can you show your way you use in your project ?
