### ISSUE TITLE
Using Puppeteer with Electron throws Could not find browser revision error. Runs fine with node.

### ISSUE THREAD

**Issue by dragonsnapx** [puppeteer/puppeteer#6652]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: Tested with 5.4.0, 5.4.1, 5.5.0
* Platform / OS version: Tested with Windows 10, Mac OS X 10.15.7
* URLs (if applicable): Local Electron App
* Node.js version: Tested with Node v12, v15.0.1, and v15.3.0

**What steps will reproduce the problem?**
In the main process of the electron, I tried:
```javascript
const puppeteer = require('puppeteer');
(async function(){
    const browser = await puppeteer.launch();
})();
```
which was called from `electron .` following user evoking the function. 

**What is the expected result?**
It shouldn't throw an error; when passing the `headless: false` parameter, it should show the browser to the user.

**What happens instead?**
This throws:
```
Uncaught (in promise) Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (Launcher.js:120)
    at async http:/localhost:8080/main.js:61295
```
Doing the two commands in the stack trace achieves nothing, neither does manually setting the path through the `executablePath` option, which just throws an `ENOENT` error. 

Strangely enough, though, if the script is run through `node scriptname.js`, it runs fine.

**Comment by xSeek-Neo** [comment]
I have same issue

**Comment by tangyue0924** [comment]
Same issue

**Comment by dragonsnapx** [comment]
For anyone having the same problems, I resolved it with the accepted answer that I wrote: https://stackoverflow.com/questions/65154317/using-puppeteer-with-electron-throws-could-not-find-browser-revision-error-ru.

Basically, move the logic to the ipcRenderer. Closing issue.
