### ISSUE TITLE
Ignore page.goto timeout

### ISSUE THREAD

**Issue by CyberMew** [puppeteer/puppeteer#6653]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: macOS
* URLs (if applicable):
* Node.js version: 12.18

**What steps will reproduce the problem?**

page.goto(url, { waitUntil: "domcontentloaded" });

Page loads (but still loading due to many subsequent calls on the page but due to network issues it takes a long while to finish loading). puppeteer then throws an error for being too long.

**What is the expected result?**

page loads the html with the selector I need, and I expect it not to throw error so I can proceed with my evaluate calls.

**What happens instead?**

page loads the html with the selector I need, but it throws an error so I cannot proceed with my page.evaluate calls.

How can I ignore the timeout and proceed with my javascript calls? I guess what I want to know is, I don't want `goto` to dictate whether a page is timedout or not but to use selector to determine it.

**Comment by RyanSchw** [comment]
I think you have a couple options:
1. `page.goto(url, { timeout: <longer>, waitUntil: "domcontentloaded" });`
1. `try/catch` around goto

Since you already have the earliest event for `goto` (`domcontentloaded`), I would recommend increasing the timeout.

**Comment by sunmasters** [comment]
try networkidle2 instead of dom load.
