### ISSUE TITLE
Google App Engine Custom flex issue error while loading shared libraries: libatk-1.0.so.0

### ISSUE THREAD

**Issue by sunildarji811** [puppeteer/puppeteer#6654]
* Puppeteer version: 5.5.0
* Platform / OS version: Google App Engine Flex 
* Node.js version: 12.0.0

**App.yaml**
runtime: custom
env: flex

**DockerFile**
FROM node:10-slim

RUN apt-get update && apt-get install

RUN apt-get -y install  libcurl3 \
  libexif-dev \
  libgconf-2-4 \
  libglib2.0-0 \ 
  libgl1-mesa-dri \
  libgl1-mesa-glx \
  libnspr4 \
  libnss3 \
  libpango1.0-0 \
  libv4l-0 \
  libxss1 \
  libxtst6 \
  libxrender1 \ 
  libx11-6 \ 
  libxft2 \ 
  libfreetype6 \ 
  libc6 \ 
  zlib1g \
  libatk1.0-0

RUN npm uninstall puppeteer -g

COPY . .
#COPY local.conf /etc/fonts/local.conf

RUN npm install

EXPOSE 8080

CMD ["/bin/sh", "entrypoint.sh"]

**entryPoint.sh**
npm run start

**Code**
      const browser = await puppeteer.launch({
        headless: true,
        args: [
          '--no-sandbox'
        ],
      })

**Comment by bmsherry** [comment]
Who can deal with it?I happened to encounter this problem

**Comment by manueledones** [comment]
Hi, I'm having a similar issue, but with libnss3. missing. I'm on google app engine (nodejs flex runtime), do i need to use a custom runtime with docker config just to install some missing libraries ?!

Thank you

**Comment by manueledones** [comment]
Ok, it's working. Since puppeteer needs additional libraries not included, a custom runtime should be used.

in the package.json I'm specifing node 14, just in case...
```
"engines": {
    "node": "14.x"
  },
...
...
    "puppeteer": "8.0.0",
```

app.yaml
```
runtime: custom
env: flex
```

Dockerfile
```
FROM gcr.io/google-appengine/nodejs

RUN apt-get update && apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 gconf-service libasound2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm ci

# Bundle app source
COPY . .

EXPOSE 8080

CMD ["npm", "run", "start:prod"]
```

my Nest.js controller
```
    const browser = await puppeteer.launch({ args: ['--no-sandbox'] })

    // create a new page
    const page = await browser.newPage()

    // set your html as the pages content
    const html = fs.readFileSync(path.resolve(__dirname, `../templates/sample.html`), 'utf8');
    await page.setContent(html, {
      waitUntil: 'domcontentloaded'
    })

    // create a pdf buffer
    const pdfBuffer = await page.pdf({
      format: 'A4'
    })

    // close the browser
    await browser.close()

    res.set({
      // pdf
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename=invoice.pdf',
      'Content-Length': pdfBuffer.length,

      // prevent cache
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': 0,
    })

    res.end(pdfBuffer)
```

Angular method to get the pdf and save it
```
this.httpClient.get(`path`, {
      responseType: 'blob',
      headers: {
        contentType: 'application/pdf'
      }
    }).subscribe(
      (response) => {
        var blob = new Blob([response], { type: 'application/pdf' });
        saveAs(blob, 'report.pdf');
      });
```
