### ISSUE TITLE
fileschooser : How to use fileschooser to upload file on ChromeOS.

### ISSUE THREAD

**Issue by wangw-1991** [puppeteer/puppeteer#6655]
I want to use puppeteer to upload file on ChromeOS. The codes are:

const file_path = '/home/chronos/user/MyFiles/Downloads/test-img-2.jpg';
const [fileChooser] = await Promise.all([
      page.waitForFileChooser(),
      page.click('#select-files-button')
]);
await fileChooser.accept([file_path]);

However, There is an error: /home/chronos/user/MyFiles/Downloads/test-img-2.jpg does not exist or is not readable. Can anyone help?

**Comment by wangw-1991** [comment]
Solved. So close it.

**Comment by mhamidch** [comment]
Would you please share how you have solved this problem.

**Comment by DMilushev** [comment]
> Would you please share how you have solved this problem.

Guess not 🤣
