### ISSUE TITLE
Does `click` also `waitForSelector` before clicking?

### ISSUE THREAD

**Issue by rodoabad** [puppeteer/puppeteer#6656]
I've always `waitForSelector` something before clicking on the element. I was wondering if we could make this a standard behaviour? Or does `click` already `waitForSelector` before clicking?

```tsx
const submitButton = await page.waitForSelector('[data-testid="submit-button"]');

await submitButton.click();
```

vs

```tsx
await page.waitForSelector('[data-testid="submit-button"]');
await page.click('[data-testid="submit-button"]');
```

vs

```tsx
await page.click('[data-testid="submit-button"]');
```

**Comment by sunmasters** [comment]
Make your function.

async function WaitToClick(selector){
//your methods
}

await WaitToClick(select);
