### ISSUE TITLE
puppeteer can't block request like "data:image"

### ISSUE THREAD

**Issue by landaida** [puppeteer/puppeteer#6662]
I tried to block all unused resources when I scraped some sites but I have the issue that can't block resources like "data:image", the same issue is described here https://github.com/ChromeDevTools/devtools-protocol/issues/105#issue-331934453

**Comment by sunmasters** [comment]
Data:image is not a url. So, puppeteer can not block. 
Maybe blocking images will work.

**Comment by katlim-br** [comment]
I am seeing the same behavior.

I have this code:

                const resourceType = request.resourceType();
                if (["font", "image", "imageset", "media", "stylesheet"].includes(resourceType)) {
                    return request.abort("failed", 1);
                }

which indirectly will "avoid" the requests to data:image urls, however, the response event for these are also triggered.

My expectation would be if I abort the request (of any type), then the response would not be called.
