### ISSUE TITLE
Puppeteer run extremely slow on page with large DOM

### ISSUE THREAD

**Issue by sfelice777** [puppeteer/puppeteer#6663]
I have many Puppeteer tests that execute very fast.
One page in the website I'm working on has a very large DOM.
Puppeteer slows way down when I get to the page.
My guess is that Puppeteer is running extremely slow because it takes more time to process this large DOM???
Or there is a problem with Puppeteer or one of my other npm packages.
It's much faster to manually test the page because of Puppeteer's slowness.

I am using the latest versions of all my npm packages, Puppeteer v5.5.0
Here is my package.json

"dependencies": {
    "@types/jest": "^26.0.15",
    "@types/jest-environment-puppeteer": "^4.4.0",
    "@types/mocha": "^8.0.4",
    "@types/puppeteer": "^5.4.0",
    "chai": "^4.2.0",
    "jest": "^26.6.3",
    "jest-puppeteer": "^4.4.0",
    "mocha": "^8.2.1",
    "mocha-junit-reporter": "^2.0.0",
    "mochawesome": "^6.2.1",
    "mochawesome-merge": "^4.2.0",
    "mochawesome-report-generator": "^5.1.0",
    "puppeteer": "^5.5.0",
    "shelljs": "^0.8.4"
  }

**Comment by sfeliceSNC** [comment]
This issue is always causing me trouble on the site I am working on.
I get a mix of passing and failing results without changing the code.
I can do some of the testing faster manually.
HELP!
