### ISSUE TITLE
Browsers with same userDataDir don't share cookies

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [puppeteer/puppeteer#6666]
I would expect that two Puppeteer windows, using the same profile directory and the same user data directory would share and thus synchronise cookies between each other.

My understanding is that in Puppeteer:
- opening a new browser means: running `puppeteer.launch()` with a new `userDataDir`
- opening a new window means: running `puppeteer.launch()` with the same `userDataDir` as the current browser instance
- opening a new tab means: running `browser.newPage()`

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v5.5.0
* Platform / OS version: OSX v10.14
* Node.js version: v13.7.0

**What steps will reproduce the problem?**

```typescript
import fs from 'fs';
import os from 'os';
import path from 'path';
import puppeteer from 'puppeteer';

(async () => {
  const userDataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'myfolder-'));
  const profileDir = 'profile1';

  const window1 = await puppeteer.launch({
    headless: true,
    userDataDir,
    args: [ `--profile-directory=${profileDir}` ]
  });
  const window2 = await puppeteer.launch({
    headless: true,
    userDataDir,
    args: [ `--profile-directory=${profileDir}` ]
  });

  const tab1 = await window1.newPage();
  const tab2 = await window2.newPage();

  // Expected: empty array
  // Returned: empty array
  console.log('(1) tab1 cookies:', await tab1.cookies());
  // Expected: empty array
  // Returned: empty array
  console.log('(1) tab2 cookies:', await tab2.cookies());

  await tab1.goto('https://httpbin.org/cookies/set/foo/bar');

  // Expected: array containing foo=bar cookie
  // Returned: array containing foo=bar cookie
  console.log('(2) tab1 cookies:', await tab1.cookies());
  // Expected: array containing foo=bar cookie
  // Returned: empty array
  console.log('(2) tab2 cookies:', await tab2.cookies());

  await window1.close();
  await window2.close();
})();
```

**What is the expected result?**

It's expected that `tab2.cookies()` return the same value as `tab1.cookies()` since both use the same `userDataDir` and `--profile-directory`.

**What happens instead?**

Instead `tab2.cookies()` returns an empty array.

**Comment by jrandolf-google** [comment]
We no longer support Node < 14, please try this again with the latest version of Puppeteer and Node >= 14. If the issue still occurs, please reopen this issue and update the description :)
