### ISSUE TITLE
Frame navigated event did not trigger.

### ISSUE THREAD

**Issue by kanishkadistill** [puppeteer/puppeteer#6671]
Details for the environment. 
Puppeteer version: 5.2.1
Platform / OS version: 	Ubuntu 18.04.5 LTS
URLs (if applicable):https://www.nokia.com/about-us/investors/investor-relations-events/
Node.js version: v10.22.0

**What steps will reproduce the problem?**
Framenavigated event does not trigger for few frames on this page.
Frame1 Upcoming events
Frame2 Past events

Code:
```
const browser = await puppeteer.launch({
        headless: false
    });
const page = await browser.newPage();
page.on("frameattached", (frame) => {
        console.log("frameattached", frame.url(), frame._id);
});
page.on("framenavigated", (frame) => {
        console.log("framenavigated", frame.url(), frame._id);
});
page.on("framedetached", (frame) => {
        console.log("framedetached", frame.url(), frame._id);
    });
await page.goto('https://www.nokia.com/about-us/investors/investor-relations-events/');
```
Expected result:
Frame navigated events for all the frames on the page.

Actual result:
Frame navigated event was triggered only for the mainframe.

**Comment by vsemozhetbyt** [comment]
I am not sure if `'framenavigated'` event is bubbled up to the main frame. Maybe you need to add `frame.on("framenavigated")` in `'frameattached'` handler.

**Comment by kanishkadistill** [comment]
Additionally, calling ```page.frames()``` does not return all the frames in a page.

@vsemozhetbyt framenavigated is fired for all frames in a page that is navigated.

**Comment by tokland** [comment]
This worked for me: https://github.com/puppeteer/puppeteer/issues/5123#issuecomment-559158303
