### ISSUE TITLE
Puppeteer MODULE_NOT_FOUND exception after being packaged by electron-packager

### ISSUE THREAD

**Issue by clementjuventin** [puppeteer/puppeteer#6676]
Hello,
My issue concerns a problem that echoes the following: https://github.com/puppeteer/puppeteer/issues/3681 
The problem is that in my case I wish to connect to an already existing browser. I will be clearer about this by showing my code...

* Puppeteer(-extra) version: 3.1.15
* Platform / OS version: Windows10
* Node.js version: 14.15.1

The code is:

```
        var browser = null;
	browser = await puppeteer.connect({
		browserWSEndpoint: WSEndpoint,
	});
```

I'm working on an electron application and when I make npm start everything works fine.
The problem is that once I have used the electron-packager command, the .exe doesn't perform any action on the existing browser. And I got a timeout error about the following .

code: MODULE_NOT_FOUND,
requireStack: C:\Users\myComputer\Desktop\celerity\celerity-win32-x64\resources\app\node_modules\puppeteer-extra\dist\index.cjs.js

I have read that sometimes it is necessary to specify the path to an executable when using puppeteer.lauch(). Unfortunately there is no field in the documentation of puppeteer.connect() that allows you to use this option.

Could someone help me?

**Comment by sunmasters** [comment]
Electron packager does not add chromium to package. 
Instead, pass path of installed Chrome.

**Comment by clementjuventin** [comment]
Thank you for your answer but If I remember well I can't give a path as an argument to puppeteer.connect(). Could you explain me a little bit more if you think I missed something in your answer?

**Comment by clementjuventin** [comment]
Woops I missed click

**Comment by sunmasters** [comment]
You can pass it to puppeteer.launch().

**Comment by clementjuventin** [comment]
I absolutely must connect my browser to an already running browser. I know that your method works but it is impossible for what I want to do to use puppeteer.launch().

**Comment by clementjuventin** [comment]
I had some trouble, but finally find a solution. I just copied the puppeteer class in my code and changed the vanilla puppeteer to require.
