### ISSUE TITLE
Digital Ocean Apps can't locate chromium directory for puppeteer

### ISSUE THREAD

**Issue by cneisen234** [puppeteer/puppeteer#6679]
I've been wrestling with this all day. I get the below error whenever I try to run my puppeteer script on Digital Ocean Apps.

/workspace/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

I did some research and found this helpful link below that seems to be the accepted solution.

https://github.com/puppeteer/puppeteer/issues/5661

However since I'm using digital ocean apps instead of the standard digital ocean droplets it seems I can't use sudo commands in the command line so I can't actually run these in the command line.

Does anyone know of anyway around this?

I'm using node.js by the way.

Thank you!!!!

**Comment by yongyi520** [comment]
were you able to find a fix to this issue? I encountered the same thing while deploying to heroku @cneisen234

**Comment by MANTENN** [comment]
Add these mock ENV variable. Im using node 16 and it works.


this one as long as it matches node 10, 12, 14, I think, I just mock set those variables to get it deployed 
`AWS_EXECUTION_ENV` = "AWS_Lambda_nodejs14.1"
the ones below can be anything
`AWS_LAMBDA_FUNCTION_NAME` = "server"
`FUNCTION_NAME` = 'badge'
`FUNCTION_TARGET` = 'server'
`FUNCTIONS_EMULATOR` = 'server'

**Comment by MANTENN** [comment]
Um commented in the wrong repo that was meant for chrome-aws-lambda. I had this same issue which I ran to install deps.

` sudo apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev`

**Comment by akramaskar** [comment]
Any way how to fix this other than deploying on a Droplet by defining our own Dockerfile?
