### ISSUE TITLE
Is the expected behavior for Puppeteer to only install one browser. 

### ISSUE THREAD

**Issue by caraya** [puppeteer/puppeteer#6680]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: MacOS Big Sur (11.0.1)
* URLs (if applicable):
* Node.js version: Tried with 12.19.1  and 14.15.2

**What steps will reproduce the problem?**

Install Puppeteer, it will install Chromium, then try `PUPPETEER_PRODUCT=firefox npm install`. It will not install Firefox Nightly but Chromium will work fine

run PUPPETEER_PRODUCT=firefox npm install puppeteer and then try install puppeteer. It will not install Chromium but Firefox will work fine

_Please include code that reproduces the issue._

Not applicable, this is not a code issue

**What is the expected result?**

I would expect Puppeteer to install both browsers and allow me to work with both browsers from Puppeteer scripts.

**What happens instead?**

Whatever browser is installed first works as expected and the other one doesn't install. I'm not certain if this is a bug or expected behavior (if it's expected then it should be documented, I wasn't able to find it documented anywhere)

**Comment by 787681277** [comment]
I also expect Puppeteer to install both browsers and allow me to work with both browsers from Puppeteer scripts.
Please fix this issue asap.
