### ISSUE TITLE
Puppeteer cant access HTTPS site with proxy server

### ISSUE THREAD

**Issue by syntaxhacker** [puppeteer/puppeteer#6681]
**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: ubuntu 19
* Node.js version: v12.16.0

answer my query which i already posted in stackoverflow :point_down: 
https://stackoverflow.com/questions/65372704/puppeteer-cant-access-https-site-with-proxy-server

**Comment by sunmasters** [comment]
It seems like https server not working.

**Comment by syntaxhacker** [comment]
@maheshjukanti  so , can you make that code working by using  working https proxies from here https://hidemy.name/en/proxy-list/?type=s#list ?

**Comment by sunmasters** [comment]
Yes

**Comment by syntaxhacker** [comment]
@maheshjukanti  can you please share it here

**Comment by syntaxhacker** [comment]
@maheshjukanti hello??

**Comment by sunmasters** [comment]
Use flag in puppeteer launch.
--proxy-server:proxyip:port

**Comment by syntaxhacker** [comment]
@maheshjukanti  already tried this but didnt work for me ..can you post that working code ?

**Comment by sunmasters** [comment]
const browser = await puppeteer.launch({
headless: false,
defaultViewport: { width: 1366, height: 768 },
args: [ '--proxy-server=192.168.1.12:1883' ]})

**Comment by syntaxhacker** [comment]
@maheshjukanti  i think you dont get it , i said i have already tried that . Cant you just send that full working code ??

**Comment by andretunes** [comment]
Hello!

You should use the module `proxyChain`, if you need a example just mention me.

Kind regards!

**Comment by syntaxhacker** [comment]
@andretunes yeah sure , will appreciate that

**Comment by andretunes** [comment]
Hello!
My mistake, there is no need to use the module `proxyChain`, in above example I used my Profile Page URL and the HTTPS Proxy `94.130.179.24:8003`, if you have any questions, feel free to ask!

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ args: ['--proxy-server="https=94.130.179.24:8003"'] });

    const page = await browser.newPage();
    await page.goto('https://github.com/andretunes', { waitUntil: 'networkidle2' });
    console.log('Powered by Andrezzz :)');

    await browser.close();
})();
```
