### ISSUE TITLE
It is no executed when focus the items in header's menu bar of Firefox Nightly browser during do automation testing

### ISSUE THREAD

**Issue by 787681277** [puppeteer/puppeteer#6684]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: macOS High Sierra 10.13.6
* URLs (if applicable):
* Node.js version:v12.16.1

**What steps will reproduce the problem?**
1)focus the items in header's menu bar of Firefox Nightly browser during do automation testing
2)It is pending when run below 2 lines' code in Firefox Nightly browser:

await page.keyboard.press('Tab');
let node = await page.$(":focus");

_Please include code that reproduces the issue._

1.await page.keyboard.press('Tab');
2.let node = await page.$(":focus");
3.

**What is the expected result?**
It should be executed like that in Chromium browser

**What happens instead?**
1.The issue can not reproduced when focus the items in <body> of firefox nightly browser

**Comment by whimboo** [comment]
It would be great to get a trace log attached. Therefore please set the `dumpio` option to `true` when launching the browser, and also set the Firefox preference `remote.log.level` to `Trace`. Then run your test again and attach the log output to this issue. Thanks!

**Comment by 787681277** [comment]
The log is attached.




[log 2.txt](https://github.com/puppeteer/puppeteer/files/6161455/log.2.txt)

**Comment by whimboo** [comment]
Sorry that this issue was forgotten. I had a look again and preventing interaction with the browser while puppeteer is running is nothing we will fix. If focus is important you might want to run your tests in headless mode instead. Closing issue.
