### ISSUE TITLE
How to debug page crash on pdf creation?

### ISSUE THREAD

**Issue by MickL** [puppeteer/puppeteer#6685]
For hours and hours I am trying to find out why the page is crashing when creating a pdf. Is there any way to get the exact error message?

```
const page = await this.browser.newPage();
await page.setContent(renderedHtml, { timeout: 10000, waitUntil: 'networkidle2' });

page.on('error', error => {
        console.log(error.message);
});

const pdfBuffer = await page.pdf(options);
await page.close();
```

This shows me `Page crashed!` and nothing more.

**Comment by MickL** [comment]
With trial and error I figured out the page crashes if there is just a h1 on the page but nothing else:

```
<h1>Hello world</h1>
```

But if I put something else it works:

```
<h1>Hello world</h1>
<div></div>
```

**Comment by dpmott** [comment]
What `options` are you passing to `page.pdf()` ?
