### ISSUE TITLE
docs don't mention that you can't run puppeteer on client side

### ISSUE THREAD

**Issue by steveja42** [puppeteer/puppeteer#6687]
It would be nice if the docs mentioned that you can't run puppeter on the client side, only on a server so newbies don't waste hours of time trying to do that, like I just did.

**Comment by Krisell** [comment]
The first sentence in the readme is `Puppeteer is a Node library`.
What do you mean by "client side"?

**Comment by steveja42** [comment]
By "client side", I mean not on a server. For example in a react app running in a users browser. Node libraries can generally run on a client or server.

**Comment by Krisell** [comment]
You're right, I'm sorry If I sounded rude or unhelpful. I suggest you make a PR and add something along the lines of this to the docs:

`Note that Puppeteer runs in a Node.js environment and can't be run inside of a web browser.`
