### ISSUE TITLE
Send POST request to a page and take screenshot

### ISSUE THREAD

**Issue by CaledoniaProject** [puppeteer/puppeteer#669]
I'm wondering if I can do a POST request, follow the 302 redirect and take a screenshot?

Is it possible?

**Comment by aslushnikov** [comment]
@CaledoniaProject you can do a post request with fetch api from the page:

```js
await page.evaluate(() => {
  fetch("/login", {
    method: "POST",
  });
});
```

Would it work for you?

**Comment by CaledoniaProject** [comment]
Can you elaborate on the example? I need to simulate `curl http://www.google.com -d 'a=b&c=d'`

**Comment by aslushnikov** [comment]
> Can you elaborate on the example? I need to simulate curl http://www.google.com -d 'a=b&c=d'

That was a speculative example :) I see now what you mean. Request Interception should do the job:

```js
await page.setRequestInterceptionEnabled(true);
page.on('request', request => {
  const overrides = {};
  if (request.url === 'http://www.google.com') {
    overrides.method = 'POST';
    overrides.postData = 'a=b&c=d';
  }
  request.continue(overrides);
});
await page.goto('http://www.google.com');
```

**Comment by CaledoniaProject** [comment]
Looks good, thanks!

**Comment by gajus** [comment]
> Request Interception should do the job:

That is extremely fragile. It assumes that there are no other requests happening between setting the `request` event handler and making `page.goto` call.

**Comment by gajus** [comment]
@CaledoniaProject an alternative solution is to:

1. Load a blank page
2. Create form HTML on the page
3. Submit the newly created form

Example (a naive implementation):

```js
const post = async (page: *, url: string, formData: URLSearchParams) => {
  const formDataEntries = formData.entries();

  let formHtml = '';

  for (const [name, value] of formDataEntries) {
    formHtml += `
      <input
        type='hidden'
        name='${name}'
        value='${value}'
      />
    `;
  }

  formHtml = `
    <form action='${url}' method='post'>
      ${formHtml}

      <input type='submit' />
    </form>
  `;

  await page.setContent(formHtml);

  const inputElement = await page.$('input[type=submit]');

  await inputElement.click();
};

```

**Comment by CaledoniaProject** [comment]
@gajus Can you provide a complete example?

I've tried the following with node 8.6.0, results in syntax error ...

```
const puppeteer = require('puppeteer');

const post = async (page: *, url: string, formData: URLSearchParams) => {
  const formDataEntries = formData.entries();

  let formHtml = '';

  for (const [name, value] of formDataEntries) {
    formHtml += `
      <input
        type='hidden'
        name='${name}'
        value='${value}'
      />
    `;
  }

  formHtml = `
    <form action='${url}' method='post'>
      ${formHtml}

      <input type='submit' />
    </form>
  `;

  await page.setContent(formHtml);
  const inputElement = await page.$('input[type=submit]');
  await inputElement.click();
};

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await post(page => page, url => 'https://www.baidu.com', formData => 'a=1&b=2');

    await page.screenshot({path: 'baidu.png'});
    browser.close();
})();
```

**Comment by gajus** [comment]
What is the syntax error? I am guessing you haven't stripped the types.

Change:

```diff
- (page: *, url: string, formData: URLSearchParams)
+ (page, url, formData)

```

**Comment by CaledoniaProject** [comment]
@gajus I still have problems

The screenshot works, but in the picture I only see the submit button, not the website I'm trying to access.

I guess I need to wait for the POST request, but the following code does not work

```
const puppeteer = require('puppeteer');

const post = async (page, url, formData) => {

  let formHtml = '';

  Object.keys(formData).forEach(function (name) {
      value = formData[name]
    formHtml += `
      <input
        type='hidden'
        name='${name}'
        value='${value}'
      />
    `;
  });

  formHtml = `
    <form action='${url}' method='post'>
      ${formHtml}

      <input type='submit' />
    </form>
  `;

    console.log(formHtml)

  await page.setContent(formHtml);
  const inputElement = await page.$('input[type=submit]');
  await inputElement.click();
};

(async () => {
    formData = {
        'a': 123,
        'b': 456
    }

    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await post(page, 'https://www.baidu.com', formData);

    await page.screenshot({path: 'baidu.png'});
    browser.close();
})();
```

**Comment by c-u-l8er** [comment]
@CaledoniaProject ty, worked for me after adding this under post()
```
await page.waitForNavigation() 
```

the `overrides.postData = 'a=b&c=d';` method wasn't working for me.

**Comment by michael-fearn** [comment]
I'm successfully sending post requests with  this snippet

    (async () => {
        const browser = await puppeteer.launch();
        const page = await browser.newPage();

        await page.setRequestInterception(true);
        page.on("request", interceptedRequest => {
            interceptedRequest.continue({
                method: "POST",
                postData: JSON.stringify({ test: "test" }),
                headers: { "Content-Type": "application/json" },
            });
        });

        const response = await page.goto("http://localhost:3005/test");
        console.log(await response.text());
        await browser.close();
    })();

**Comment by contralorogo** [comment]
> I'm successfully sending post requests with this snippet
> 
> ```
> (async () => {
>     const browser = await puppeteer.launch();
>     const page = await browser.newPage();
> 
>     await page.setRequestInterception(true);
>     page.on("request", interceptedRequest => {
>         interceptedRequest.continue({
>             method: "POST",
>             postData: JSON.stringify({ test: "test" }),
>             headers: { "Content-Type": "application/json" },
>         });
>     });
> 
>     const response = await page.goto("http://localhost:3005/test");
>     console.log(await response.text());
>     await browser.close();
> })();
> ```

¿How, send request GET after request POST ?

>     const response = await page.goto("http://localhost:3005/test");
>     console.log(await response.text());
      await page.goto('https://google.com')

Show error: (node:2584) UnhandledPromiseRejectionWarning: Error: Request is already handled!

**Comment by michael-fearn** [comment]
await page.setRequestInterception(true);
    // create a flag to only modify the initial request
    let reformatFirstRequest = true;

    page.on('request', interceptedRequest => {
      if (reformatFirstRequest) {
        console.log('first-request');
        reformatFirstRequest = false;
        interceptedRequest.continue({
          method: 'POST',
          postData: JSON.stringify(data),
          headers: { 'Content-Type': 'application/json' }
        });
      } else {
        interceptedRequest.continue();
      }
    });

**Comment by JohnDotOwl** [comment]
> ```
> await page.setRequestInterception(true);
> // create a flag to only modify the initial request
> let reformatFirstRequest = true;
> 
> page.on('request', interceptedRequest => {
>   if (reformatFirstRequest) {
>     console.log('first-request');
>     reformatFirstRequest = false;
>     interceptedRequest.continue({
>       method: 'POST',
>       postData: JSON.stringify(data),
>       headers: { 'Content-Type': 'application/json' }
>     });
>   } else {
>     interceptedRequest.continue();
>   }
> });
> ```

I can only get this to work if it's the first page.goto , when i try to activate this after i'm done with a few goto to retrieve data, it wouldnt send a post, it would just send a get request.

**Comment by PierreNoll** [comment]
> CaledoniaProject you can do a post request with fetch api from the page:
> 
> ```js
> await page.evaluate(() => {
>   fetch("/login", {
>     method: "POST",
>   });
> });
> ```
> 
> Would it work for you?

If you need to wait for the response of the request (in order to have the session cookie for exemple) I suggest to return the fetch promise, otherwise it will not wait for the response of your request.

```js
await page.evaluate(() => {
  return fetch("/login", {
    method: "POST",
  });
});
```

**Comment by RiccardoManzan** [comment]
If no relatively linked resources loades try this:
```js
const browser = await puppeteer.launch();
const page = await browser.newPage();

// Allows and FORCES you to intercept following requests
await page.setRequestInterception(true);

// Using 'on',  intercept handler will be triggered at ANY request, that's why i used 'once'
page.once("request", (interceptedRequest) => {
  interceptedRequest.continue(your_overrides);
  // Removes your duty to intercept requests
  page.setRequestInterception(false);
});
await page.goto(`http://insert-here-your-base-url`, { waitUntil: "networkidle0" });

//then do whatever you want with your page
```

And that's all folks

**Comment by geri777** [comment]
Have a look at packages like GOT. It makes life much easier - I would not suggest using puppeteer to send background requests.  

```
const {response , statusCode} = await got.post(remoteUrl, {postData});
if (statusCode !== 200) {
   throw new Error(response.error || 'Oops. Something went wrong! Try again please.');
} else {
   console.log (response.body);
}
```
