### ISSUE TITLE
Dynamically adding script tag is not getting executed

### ISSUE THREAD

**Issue by mitesh-agarwal-bh** [puppeteer/puppeteer#6691]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: 12.18.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. const htmlContent = '<html>' + headContent + bodyContent + '</html>';

2. Trying to add script.. using jsDOM to convert to dom.. as need to manipulate the html before setting content 
const script = `
    **console.log('need to execute this script')**
    document.getElementById('pageHeader').parentElement.parentElement.parentElement.parentElement.style.display = 'none'**
  `
const dom = new jsdom.JSDOM(htmlContent);
  var newScript = dom.window.document.createElement("script");
  newScript.setAttribute('async', true);
  var inlineScript = dom.window.document.createTextNode(script);
  newScript.appendChild(inlineScript); 
  dom.window.document.body.appendChild(newScript);
const htmlFinal = dom.serialize();

3. await page.setContent(htmlFinal, { waitUntil: ['networkidle2'] });

**What is the expected result?**
The script tag should execute so that we can do dom manipulation before setting content. Now, the pdf is getting generated but the script is not executed so DOM manipulation is not happening 
Or is there any other method to acheive this ?

**Comment by sunmasters** [comment]
Setting page content not execution of JavaScript. 
Create a function call after set content was done.
