### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'innerText' of null

### ISSUE THREAD

**Issue by nghilevi** [puppeteer/puppeteer#6694]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: Mac
* Node.js version: 14.14.14

**What steps will reproduce the problem?**

I tried this:

```
const puppeteer = require('puppeteer');

const url = 'https://www.etoro.com/people/cashflowstation/stats';
//const selector = '.instrument-navigation-link-top-name'; // working
const selector = '.info-procents'; // not working

const getInnerText = (selector) => document.querySelector(selector).innerText;

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto(url);

  const result = await page.evaluate(getInnerText, selector);
  
  console.log(result);

  await browser.close();
})();
```

**What is the expected result?**

it should log the text for both selectors: '.instrument-navigation-link-top-name' and  '.info-procents'

**What happens instead?**

only  '.instrument-navigation-link-top-name' works.

**Comment by vsemozhetbyt** [comment]
Not sure why, but the page produces some 403 HTTP errors and other warnings in the console when launched with the puppeteer in headful mode, and some parts of the page are missing.

**Comment by nghilevi** [comment]
I don't know why it does not work on Chromium but with Chrome and other browsers. The request is blocked somehow. I tried to make the API call directly using NodeJS (axios) and still got 403

**Comment by dpmott** [comment]
What is `document` in this case?  It doesn't look like it would refer to anything on any Puppeteer page.
