### ISSUE TITLE
Request interception causes importScripts in a worker to throw an error (RTL texts in Mapbox cannot be rendered)

### ISSUE THREAD

**Issue by mstr-pezhang** [puppeteer/puppeteer#6697]
### Steps to reproduce

* Puppeteer version: 5.5.0
* Platform / OS version: Windows 10, Ubuntu 18, MacOS Big Sur
* URLs (if applicable):
* Node.js version: 12.19.0

**What steps will reproduce the problem?**

1. Enable request interception and call `request.continue()` for each request.
1. Load the example page from Mapbox.com https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/
1. Wait until resources are loaded.
1. Take a screenshot of the map.
1. See the right-to-left texts (Arabic) are not displayed.
1. `self.importScripts()` is used in the RTL text plugin of Mapbox, but it cannot successfully import the script.

```typescript
import puppeteer from 'puppeteer';
import compare from '../util/compareImage';

const exampleUrl = 'https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/';
const baselinePath = 'output/mapbox-rtltext-normal.png';
const targetPath = 'output/mapbox-rtltext-request-interception.png';
const diffPath = 'output/mapbox-rtltext-diff.png';

let browser: puppeteer.Browser;
let page: puppeteer.Page;

test('Launch Chrome', async () => {
	browser = await puppeteer.launch();
});

test('Open example page', async () => {
	page = await browser.newPage();
	await page.goto(exampleUrl, { waitUntil: 'networkidle0' });
}, 30 * 1000);

test('Take a screenshot', async () => {
	const map = await page.$('#demo');
	await map.screenshot({
		path: baselinePath,
	});
	await page.close();
});

test('Enable request interception', async () => {
	page = await browser.newPage();
	await page.setRequestInterception(true);
	page.on('request', (req) => {
		req.continue();
	});
	await page.goto(exampleUrl, { waitUntil: 'networkidle0' });
}, 30 * 1000);

test('Take a screenshot', async () => {
	const map = await page.$('#demo');
	await map.screenshot({
		path: targetPath,
	});
	await page.close();
});

test('Compare 2 images', async () => {
	const diff = await compare(baselinePath, targetPath, diffPath);
	expect(diff.differences).toBe(0);
	expect(diff.dimension).toBeGreaterThan(0);
});

test('Close', async () => {
	await browser.close();
});
```

Example Project: https://github.com/mstr-pezhang/chromium-issue
1. Clone the project.
2. Open it in VS Code.
3. Open `mapbox-rtltext.spec.ts`
4. Switch to Debug tab and click `Debug Jest`.
5. 3 images will be generated in output folder. See the differences between `mapbox-rtltext-request-interception.png` and `mapbox-rtltext-normal.png`.

Execution Results in GitHub Actions: https://github.com/mstr-pezhang/puppeteer-issue/actions/runs/443832997

**What is the expected result?**
RTL texts can be loaded. `importScripts()` works well.

**What happens instead?**
`importScripts()` cannot successfully load the script.

**Comment by do-not-worry** [comment]
any update on this?

**Comment by wilsonssss** [comment]
facing the same issue bro

**Comment by xujiujiu** [comment]
try it ？
`
const worker = await new Promise(resolve => page.once('workercreated', resolve));
await worker.evaluate(script => importScripts(script));
`

**Comment by xujiujiu** [comment]
try it ?
```js
const worker = await new Promise(resolve => page.once('workercreated', resolve)); 
await worker.evaluate(script => importScripts(script));
```

**Comment by xujiujiu** [comment]
try it
```js
    const worker = await new Promise(resolve => page.once('workercreated', resolve));
    await worker.evaluate(script => importScripts(script));
```
