### ISSUE TITLE
Page.goto fulfills a string on timeout instead of an error

### ISSUE THREAD

**Issue by mikeys** [puppeteer/puppeteer#670]
The following code is in `lib/NavigatorWatcher.js`. It's being used internally by `Page.goto`:

```node
 async waitForNavigation() {
    this._requestIds = new Set();

    this._eventListeners = [];

    const watchdog = new Promise(fulfill => this._maximumTimer = setTimeout(fulfill, this._timeout))
        .then(() => 'Navigation Timeout Exceeded: ' + this._timeout + 'ms exceeded');
```

Note that the watchdog fulfills promise into a string as opposed to some kind of a rejected error (TimeoutError?).
Error handling is therefore not so elegant (need to check a string as opposed to catch a raised error inside a try/catch block).

Is this behavior by design?

**Comment by aslushnikov** [comment]
> Error handling is therefore not so elegant (need to check a string as opposed to catch a raised error inside a try/catch block).
>
> Is this behavior by design?

@mikeys Yes, it's by design. We avoid using errors and promise rejections to drive control flow.
