### ISSUE TITLE
How to intercept downloads of files generated in client side of website through puppeteer?

### ISSUE THREAD

**Issue by anupsunni** [puppeteer/puppeteer#6700]
I have a page on this link (https://master.d3tei1upkyr9mb.amplifyapp.com/report) with 3 export buttons. These export buttons generate XLSX, CSV, PDF on the frontend, and hence there are no URLs for XLSX, CSV, PDF.

I need puppeteer to be able to download or get or intercept the blobs or buffers of these files in my node backend.

I tried different ways to achieve this but still haven't figured out.

is it currently possible?

I am using Node.js Server.

**Comment by AHgPuK** [comment]
It is still actual. Please, describe how we can implement the subject.

**Comment by OrKoN** [comment]
I suggest you ask on stackoverflow as there are multiple ways how it can be implemented with Puppeteer and/or CDP. E.g., via https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior or https://pptr.dev/guides/request-interception if it's downloaded. Note that there is currently no API for setDownloadBehavior in Puppeteer and one needs to fallback to the raw CDP access. Also, see https://github.com/puppeteer/puppeteer/issues/8010
