### ISSUE TITLE
iFrame - Unable to move mouse. TypeError: Cannot read property 'move' of undefined

### ISSUE THREAD

**Issue by ray-bun** [puppeteer/puppeteer#6701]
Hi,

I hope someone can help, I'm not sure if it's a bug.  I'm able to click on links in the iframe but I'm unable to perform mouse move in an iframe. I'm getting: TypeError: Cannot read property 'move' of undefined. It's working if no Iframe but I need it to work in an iframe.

Could someone help me, please? Thanks

`const puppeteer = require('puppeteer')
const fs = require('fs').promises
const Jimp = require('jimp')
const pixelmatch = require('pixelmatch')
const { cv } = require('opencv-wasm')

async function findPuzzlePosition (frame) {
    let images = await frame.$$eval('.geetest_canvas_img canvas', canvases => canvases.map(canvas => canvas.toDataURL().replace(/^data:image\/png;base64,/, '')))

    await fs.writeFile(`./puzzle.png`, images[1], 'base64')

    let srcPuzzleImage = await Jimp.read('./puzzle.png')
    let srcPuzzle = cv.matFromImageData(srcPuzzleImage.bitmap)
    let dstPuzzle = new cv.Mat()

    cv.cvtColor(srcPuzzle, srcPuzzle, cv.COLOR_BGR2GRAY)
    cv.threshold(srcPuzzle, dstPuzzle, 127, 255, cv.THRESH_BINARY)

    let kernel = cv.Mat.ones(5, 5, cv.CV_8UC1)
    let anchor = new cv.Point(-1, -1)
    cv.dilate(dstPuzzle, dstPuzzle, kernel, anchor, 1)
    cv.erode(dstPuzzle, dstPuzzle, kernel, anchor, 1)

    let contours = new cv.MatVector()
    let hierarchy = new cv.Mat()
    cv.findContours(dstPuzzle, contours, hierarchy, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)

    let contour = contours.get(0)
    let moment = cv.moments(contour)

    return [Math.floor(moment.m10 / moment.m00), Math.floor(moment.m01 / moment.m00)]
}

async function findDiffPosition (frame) {
    await frame.waitFor(100)

    let srcImage = await Jimp.read('./diff.png')
    let src = cv.matFromImageData(srcImage.bitmap)

    let dst = new cv.Mat()
    let kernel = cv.Mat.ones(5, 5, cv.CV_8UC1)
    let anchor = new cv.Point(-1, -1)

    cv.threshold(src, dst, 127, 255, cv.THRESH_BINARY)
    cv.erode(dst, dst, kernel, anchor, 1)
    cv.dilate(dst, dst, kernel, anchor, 1)
    cv.erode(dst, dst, kernel, anchor, 1)
    cv.dilate(dst, dst, kernel, anchor, 1)

    cv.cvtColor(dst, dst, cv.COLOR_BGR2GRAY)
    cv.threshold(dst, dst, 150, 255, cv.THRESH_BINARY_INV)

    let contours = new cv.MatVector()
    let hierarchy = new cv.Mat()
    cv.findContours(dst, contours, hierarchy, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)

    let contour = contours.get(0)
    let moment = cv.moments(contour)

    return [Math.floor(moment.m10 / moment.m00), Math.floor(moment.m01 / moment.m00)]
}

async function saveSliderCaptchaImages(frame) {

    await frame.waitForSelector('[aria-label="Click to verify"]')
    await frame.waitFor(3000)

    await frame.click('[aria-label="Click to verify"]')

    await frame.waitForSelector('.geetest_canvas_img canvas', { visible: true })
    await frame.waitFor(1000)
    let images = await frame.$$eval('.geetest_canvas_img canvas', canvases => {
        return canvases.map(canvas => canvas.toDataURL().replace(/^data:image\/png;base64,/, ''))
    })

    await fs.writeFile(`./captcha.png`, images[0], 'base64')
    await fs.writeFile(`./original.png`, images[2], 'base64')
}

async function saveDiffImage() {
    const originalImage = await Jimp.read('./original.png')
    const captchaImage = await Jimp.read('./captcha.png')

    const { width, height } = originalImage.bitmap
    const diffImage = new Jimp(width, height)

    const diffOptions = { includeAA: true, threshold: 0.2 }

    pixelmatch(originalImage.bitmap.data, captchaImage.bitmap.data, diffImage.bitmap.data, width, height, diffOptions)
    diffImage.write('./diff.png')
}

async function solveCaptcha (frame) {
    console.log(frame)
    await saveSliderCaptchaImages(frame)
    await saveDiffImage()

    let [cx, cy] = await findDiffPosition(frame)

    const sliderHandle = await frame.$('.geetest_slider_button')
    console.log('sliderHandle: ' + sliderHandle)

    const handle = await sliderHandle.boundingBox()
    console.log('handle: ' + handle)

    await frame.waitFor(5000)
    console.log(handle)
    let xPosition = handle.x + handle.width / 2
    let yPosition = handle.y + handle.height / 2
    await frame.mouse.move(xPosition, yPosition)
    await frame.mouse.down()

    xPosition = handle.x + cx - handle.width / 2
    yPosition = handle.y + handle.height / 3
    await frame.mouse.move(xPosition, yPosition, { steps: 25 })
    console.log('test : '+test)
    await frame.waitFor(100)

    let [cxPuzzle, cyPuzzle] = await findPuzzlePosition(frame)

    xPosition = xPosition + cx - cxPuzzle
    yPosition = handle.y + handle.height / 2
    await frame.mouse.move(xPosition, yPosition, { steps: 5 })
    await frame.mouse.up()

    await frame.waitFor(3000)
    // success!

    await fs.unlink('./original.png')
    await fs.unlink('./captcha.png')
    await fs.unlink('./diff.png')
    await fs.unlink('./puzzle.png')

}

async function start(){
    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: { width: 1366, height: 768 },
        args: [ '--proxy-server=192.168.1.12:1883', '--disable-web-security',
        '--disable-features=IsolateOrigins,site-per-process'],

    })
   
    const page = await browser.newPage()
    //await page.authenticate({username: 'xxx',password: 'xxx',});

  
    await page.goto('https://bck.hermes.com/products?locale=au_en&category=WOMENBAGSBAGSCLUTCHES', { waitUntil: 'networkidle2' })
    await page.waitFor(1000)
    await page.content();

    try {
    innerText = await page.evaluate(() =>  {
        return JSON.parse(document.querySelector("body").innerText); 
    }); 
    }
    catch(err) {
        console.log('BLOCKED, we want to solve captcha here..')
        await page.waitFor(9000)
         // handle frame
        const frameHandle = await page.$("iframe");
        const frame = await frameHandle.contentFrame();
        console.log(frame)
        solveCaptcha(frame)
        console.log('HERE..')
        await page.waitFor(90000)
        

       // solveCaptcha(frame)
    }

    //console.log("innerText now contains the JSON");
    //console.log(innerText);
    

}
start()`

**Comment by sunmasters** [comment]
get frame with window.frames

**Comment by ray-bun** [comment]
I was able to solve it by passing the page. when performing mouse move action in an iframe. Performing mouse move in iframe context doesn't work, need to use page.

**Comment by tonoli** [comment]
@mrWiga could you please send the solution i'm faceing the same issue : 

```
abort(TimeoutError: waiting for selector `[aria-label="Click to verify"]` failed: timeout 30000ms exceeded)
```
