### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by sajadisam** [puppeteer/puppeteer#6702]
Issue has been solved.

**Comment by moises138** [comment]
e7c2382203

**Comment by sajadisam** [comment]
> e7c2382203

Sorry, whats that?

**Comment by ray-bun** [comment]
The captcha is in an iframe. Go into the frame.
Try:
 const frameHandle = await page.$("iframe");
 const frame = await frameHandle.contentFrame();
await frame.$('#recaptcha-audio-button');

**Comment by sunmasters** [comment]
You can also try.

window.frames

**Comment by sajadisam** [comment]
Solved.
