### ISSUE TITLE
XPath does not search for child of the element

### ISSUE THREAD

**Issue by clouedoc** [puppeteer/puppeteer#6710]
Hi,

Here is a weird bug I identified. I'm not sure if there is a bug in my code or if there is a problem with puppeteer. Maybe this will be a starting point for others experiencing the same problem.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Big Sur (11.0.1)
* URLs (if applicable): N/A
* Node.js version: v15.3.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```typescript
// Create an ElementHandle to a parent element (here, using XPath)
// We want to select a child of the second occurence found
const [buggyEl, targetedEl] = await page.$x(`xpath expression`)

// So, we want a child of targetedEl. We'll see that selecting a child of targetedEl using XPath will actually return a match in buggyEl

// search for a child of `targetedEl` using XPath: 
const [xpathChild] = await targetedEl.$x(`second xpath expression`)

// search for a child of `targetedEl` using selector
const selectorChild = await targetedEl.$(`child selector`)

// finally, compare the two.
```

**What is the expected result?**

`selectorChild` is child of `targetedEl`
`xpathChild` is child of `targetedEl` as well

**What happens instead?**

`xpathChild` is child of `buggyEl`

**Comment by vsemozhetbyt** [comment]
I can suppose that you may miss the context node in XPath: it seems we need to set the context node explicitly for `elementHandle.$x()`.

For example, this code is OK:

```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();

const html = `
  <!doctype html>
  <html>
    <head><meta charset='UTF-8'><title>Test</title></head>
    <body>
      <p><span>buggy</span></p>
      <p><span>targeted</span></p>
    </body>
  </html>`;

try {
  const [page] = await browser.pages();
  await page.goto(`data:text/html,${html}`);

  const [buggyEl, targetedEl] = await page.$x(`//p`);

  const [xpathChild] = await targetedEl.$x(`.//span`); // Context node is set.
  const selectorChild = await targetedEl.$(`span`);

  console.log(await xpathChild.evaluate(node => node.innerText)); // targeted
  console.log(await selectorChild.evaluate(node => node.innerText)); // targeted
} catch(err) { console.error(err); } finally { await browser.close(); }
```

But if we do not set the context node, we will have the first matched element in the first matched parent:


```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();

const html = `
  <!doctype html>
  <html>
    <head><meta charset='UTF-8'><title>Test</title></head>
    <body>
      <p><span>buggy</span></p>
      <p><span>targeted</span></p>
    </body>
  </html>`;

try {
  const [page] = await browser.pages();
  await page.goto(`data:text/html,${html}`);

  const [buggyEl, targetedEl] = await page.$x(`//p`);

  const [xpathChild] = await targetedEl.$x(`//span`); // Context node is not set.
  const selectorChild = await targetedEl.$(`span`);

  console.log(await xpathChild.evaluate(node => node.innerText)); // buggy
  console.log(await selectorChild.evaluate(node => node.innerText)); // targeted
} catch(err) { console.error(err); } finally { await browser.close(); }
```

**Comment by vsemozhetbyt** [comment]
Here is the implementation, you can see the element as the context node, so we need it in the expression as well: https://github.com/puppeteer/puppeteer/blob/d901696e0d8901bcb23cf676a5e5ac562f821a0d/src/common/JSHandle.ts#L893-L908

**Comment by clouedoc** [comment]
@vsemozhetbyt I did not expect someone to answer so fast! Thank you for your help. I think that you are right though I switched to using placeholders for the task I was trying to achieve.

For anyone else struggling to see the difference between the two snippets you posted, here is a diff:
![image](https://user-images.githubusercontent.com/13921610/103417678-fc474a80-4b8b-11eb-955b-d54a9ac91a70.png)

**Comment by mathiasbynens** [comment]
This is now documented thanks to @vsemozhetbyt in #6711 🥳
