### ISSUE TITLE
Nested Modules Import in page.evaluate()

### ISSUE THREAD

**Issue by Bogdan1001** [puppeteer/puppeteer#6719]
* Puppeteer version: 5.4.1
* Platform / OS version: MacOS Catalina
* URLs (if applicable):
* Node.js version: v12.18.2

Hello!

I'm trying to do "nested import" of nodejs modules into page.evaluate().

By nested I mean that the modules which I importing to there do import some dependencies inside yourself.

```
const imported_module = require("./imported_module.js);

await page.addScriptTag({ path: "./engine/imported_module.js" });

await page.evaluate((a) => {
imported_module(a)
}, a)
```

So inside the `imported_module`

```
const fun = require("../helpers/fun.js");

const imported_module = (a) => {
return fun(a)
}

module.exports = imported_module;
```

As a result I get : `Evaluation failed: ReferenceError: imported_module is not defined`

However if I do change the imported_module, and remove the nested dependencies - all works.

```
const imported_module = (a) => {
console.log(a)
}

module.exports = imported_module;
```

Is there're some methods that can help to fix the issue?

**Comment by damianobarbati** [comment]
@Bogdan1001 how did you solve?
