### ISSUE TITLE
Failed to download Chromium r497674! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by ystop** [puppeteer/puppeteer#672]
mac 10.12.5
node v8.4.0
npm 5.3.0
puppeteer  0.10.2

when l " npm install", l get this:

ERROR: Failed to download Chromium r497674! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
npm WARN backendbrowser@1.0.0 No repository field.
npm WARN backendbrowser@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxx/.npm/_logs/2017-09-04T02_50_51_507Z-debug.log

**Comment by JoelEinbinder** [comment]
what happens if you run 
```bash
wget https://storage.googleapis.com/chromium-browser-snapshots/Mac/497674/chrome-mac.zip
```
Maybe you are behind a proxy or there is some other reason that the download is failing.

**Comment by ystop** [comment]
@JoelEinbinder Thanks. Due to network, l do nothing, but  it's all right now.

**Comment by mcrowder65** [comment]
Is there an alternative to this? I am trying to use this for pdf generation but our servers are pretty locked down to only using npm... is there an alternative download directly on npm?

**Comment by mcrowder65** [comment]
oh i found that my http_proxy and https_proxy's weren't set on jenkins :)

**Comment by Mr-LiuDC** [comment]
Hi bro. I also got this error on Windows 7. I have set the proxy host，and sure it's correct.

Failed to download Chromium r497674 ! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

Is there any suggestions？

Thanks.
@JoelEinbinder @ystop

**Comment by ystop** [comment]
@Mr-LiuDC Due to network!Trust me. I'm Chinese, too.

**Comment by renmoqiqi** [comment]
我也是个原因

**Comment by henryatman** [comment]
@JoelEinbinder , what should i do if i donwloaded this zip by manual，where its should be?

btw, what if ubuntu system what zip could download?

**Comment by Robothy** [comment]
Here has a similar problem https://github.com/GoogleChrome/puppeteer/issues/1597

**Comment by oeliok** [comment]
Can I complete the download manually? And what should I configure? I can't download it directly because of the wall

**Comment by Mr-LiuDC** [comment]
@oeliok @renmoqiqi 

links below are useful.

[https://github.com/GoogleChrome/puppeteer/issues/1597](https://github.com/GoogleChrome/puppeteer/issues/1597)

[https://github.com/cnpm/cnpmjs.org/issues/1246](https://github.com/cnpm/cnpmjs.org/issues/1246)
