### ISSUE TITLE
can't set webdriver

### ISSUE THREAD

**Issue by keyiis** [puppeteer/puppeteer#6725]
**my environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: win10 x64
* URLs (if applicable):
* Node.js version: v14.15.0

**What steps will reproduce the problem?**
```
let browser = await puppeteer.launch({
    ignoreDefaultArgs: ['--enable-automation']
});
let page = (await browser.pages())[0];
await page .evaluateOnNewDocument(() => {
        Object.defineProperty(window.navigator, 'webdriver', {
          get: () => false,
        });
      });
await this.currentPage.goto('https://www.baidu.com');
```
When I execute the above code, I get the following error
```
VM50:6 Uncaught TypeError: Cannot redefine property: webdriver
    at Function.defineProperty (<anonymous>)
    at <anonymous>:6:28
    at <anonymous>:10:19
(anonymous) @ VM50:6
(anonymous) @ VM50:10

```
I don't know what caused it

**Comment by keyiis** [comment]
It's work fine after I downgraded the puppeteer to version 5.4.1,so new version not support defineProperty?

**Comment by kum1ko** [comment]
Same problem.

**Comment by banggua** [comment]
Same problem.

**Comment by qujinqiang** [comment]
same to me, chrome version 88.0.4324.96

**Comment by vabaly** [comment]
You can try to add argument `--disable-blink-features=AutomationControlled` when launch the browser:

```js
const browser = await launch({
    // ...
    ignoreDefaultArgs: ['--enable-automation'],
    args: ['--disable-blink-features=AutomationControlled'],
    // ...
 })
```
It works to me

**Comment by yufd1986** [comment]
> You can try to add argument `--disable-blink-features=AutomationControlled` when launch the browser:
> 
> ```js
> const browser = await launch({
>     // ...
>     ignoreDefaultArgs: ['--enable-automation'],
>     args: ['--disable-blink-features=AutomationControlled'],
>     // ...
>  })
> ```
> 
> It works to me

yes,it works

**Comment by justin-mc-lai** [comment]
it no't works to me

**Comment by yhl452493373** [comment]
> You can try to add argument `--disable-blink-features=AutomationControlled` when launch the browser:
> 
> ```js
> const browser = await launch({
>     // ...
>     ignoreDefaultArgs: ['--enable-automation'],
>     args: ['--disable-blink-features=AutomationControlled'],
>     // ...
>  })
> ```
> 
> It works to me

awasome!it works on chrome 88.0.4324.192

**Comment by thephucit** [comment]
this flag `--disable-blink-features=AutomationControlled` is unsupported on Chromium :(

**Comment by thephucit** [comment]
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/873cfbf3-3c2a-4bde-92d3-c8f5d3d71e16">
