### ISSUE TITLE
Ways to 'freeze' browser ?

### ISSUE THREAD

**Issue by glinford** [puppeteer/puppeteer#674]
Hi,

It would be nice to add browser.freeze() / browse.unfreeze()  methods, to completely freeze the actions

Eg:

```javascript
page.on('pageerror', (e) => {
browser.freeze() 
log(e)
// take screenshots
// do bunch of api calls
// more ...
browser.unfreeze() 
})

await page.click('.clickthis') // all good
await page.click('.clickthisthrowanerror') // pageerror event handler will freeze the browser
await page.click('.clickthis') // will wait until the browser is unfreezed to execute
```

Typically we would need to lock this._connection.send() in Connection.js when the browser is 'freezed' to avoid more actions to be done in the 'frozen' state.

If this is something that you would think it's worth to add but you maintainers are too busy with other tasks, I'll be happy to have a try on working on this.

**Comment by JoelEinbinder** [comment]
I don't understand how this is supposed to work. How does the second `page.click('.clickthis')` know to wait, but all of the screenshots and api calls resolve?

**Comment by glinford** [comment]
Typically the second ```await page.click('.clickthis')``` will wait (or timeout) whenever browser.unfreeze() is called to execute.

My scenario is as follow:
- I have a set of actions,  If an action throws an error I want to freeze the browser (= not do next actions) to do necessary api checks
```
page.on('pageerror', (e) => {
browser.freeze() Calling this method will lock action 4
log(e)
await myApiCheck();
await someFailureChecks();
browser.unfreeze() // calling this method will unlock Action 4
})

await page.click('.clickthis') // Action 1 
await page.click('.clickthis') // Action 2
await page.click('.clickthisthrowanerror') // Action 3
await page.click('.clickthis') // Action 4
```

I hope my use case is clear ^^

**Comment by JoelEinbinder** [comment]
Instead of `browser.freeze`, it looks like you'd want `await page.click` to throw an error if clicking caused an error on the page.

It isn't that pretty, but you can replace your async function with a generator, and all `await` with `yield`. Then repeatedly `await generator.next().value`, but stop if an error occurs in between.

**Comment by glinford** [comment]
Ah didn't think of generators, that would probably fulfill my use case.
