### ISSUE TITLE
Reloading pages fill up the memory with strings, and arrays

### ISSUE THREAD

**Issue by Grsz** [puppeteer/puppeteer#6742]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: MacOS Big Sur 11.1
* URLs (if applicable): any
* Node.js version: 12.13.0

**What steps will reproduce the problem?**

 1. run the below code with `node --inspect-brk`
 2. go to chrome://inspect/#devices
 3. click Inspect
 4. run the debugger
 5. while the code running, take snapshots of the memory - memory tab in chrome devtools

```
const randomUseragent = require('random-useragent');
const puppeteer = require('puppeteer');

const USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36';

const initPage = async (browser) => {
  const page = await browser.newPage();

  //Skip images/styles/fonts loading for performance
  await page.setRequestInterception(true);
  page.on('request', (req) => {
    if (req.resourceType() == 'stylesheet' || req.resourceType() == 'font' || req.resourceType() == 'image') {
      req.abort();
    } else {
      req.continue();
    }
  });

  await page.evaluateOnNewDocument(() => {
    // Pass webdriver check
    Object.defineProperty(navigator, 'webdriver', {
      get: () => false,
    });
  });

  await page.evaluateOnNewDocument(() => {
    // Pass chrome check
    window.chrome = {
      runtime: {},
      // etc.
    };
  });

  await page.evaluateOnNewDocument(() => {
    //Pass notifications check
    const originalQuery = window.navigator.permissions.query;
    return window.navigator.permissions.query = (parameters) => (
      parameters.name === 'notifications' ?
        Promise.resolve({ state: Notification.permission }) :
        originalQuery(parameters)
    );
  });

  await page.evaluateOnNewDocument(() => {
    // Overwrite the `plugins` property to use a custom getter.
    Object.defineProperty(navigator, 'plugins', {
      // This just needs to have `length > 0` for the current test,
      // but we could mock the plugins too if necessary.
      get: () => [1, 2, 3, 4, 5],
    });
  });

  await page.evaluateOnNewDocument(() => {
    // Overwrite the `languages` property to use a custom getter.
    Object.defineProperty(navigator, 'languages', {
      get: () => ['en-GB', 'en'],
    });
  });

  return page;
};

const runPage = async (page, url) => {
  //Randomize User agent or Set a valid one
  const userAgent = randomUseragent.getRandom();
  const UA = userAgent || USER_AGENT;
  await page.setUserAgent(UA);

  //Randomize viewport size
  await page.setViewport({
    width: 1920 + Math.floor(Math.random() * 100),
    height: 3000 + Math.floor(Math.random() * 100),
    deviceScaleFactor: 1,
    hasTouch: false,
    isLandscape: false,
    isMobile: false,
  });
  //Disable cache
  await page.setCacheEnabled(false);

  for (let i = 0; i < 100; i++) {
    await page.goto(url, { timeout: 0 })
  }
}

const runSession = (url) => async (browser) => {
  const page = await initPage(browser, url);
  await runPage(page, url);
}

const amazonSession = runSession("https://www.amazon.co.uk/");

(async () => {
  while (true) {
    const browser = await puppeteer.launch({
      headless: false,
      args: [
        '--disable-web-security',
        '--disable-features=IsolateOrigins,site-per-process'
      ]
    });
    await amazonSession(browser)
    await browser.close()
  }
})();
```

After I was running my code (its base is basically the above code), and noticed that as time goes, my computer, and the process itself as well gets slower and slower. I was trying to do research of the problem, and what I've found is to relaunch the browser, and disable cache for the tab/page. Then I dug deeper, and realised that the memory leak is caused by storing more and more arrays and strings. The strings contain scripts, ad tags, JSON, etc. - definitely from the pages being reloaded.

**What is the expected result?**
Those should be cleared when the browser gets relaunched.

**What happens instead?**
Arrays, and strings coming from the pages are stored even when relaunching the browser.
<img width="1792" alt="Screenshot 2021-01-09 at 21 59 58" src="https://user-images.githubusercontent.com/39468871/104109467-26081c00-52c6-11eb-8dc5-b349580d3e8c.png">
<img width="1792" alt="Screenshot 2021-01-09 at 22 00 04" src="https://user-images.githubusercontent.com/39468871/104109470-286a7600-52c6-11eb-8f12-06a6dadb6355.png">
<img width="1792" alt="Screenshot 2021-01-09 at 22 00 08" src="https://user-images.githubusercontent.com/39468871/104109472-2e605700-52c6-11eb-9ea7-e5731944d41a.png">
<img width="1792" alt="Screenshot 2021-01-09 at 22 00 12" src="https://user-images.githubusercontent.com/39468871/104109473-30c2b100-52c6-11eb-9dee-71286e8d8097.png">
<img width="1792" alt="Screenshot 2021-01-09 at 22 00 16" src="https://user-images.githubusercontent.com/39468871/104109477-34563800-52c6-11eb-87e6-b89c0fff786b.png">

**Comment by ivictbor** [comment]
@Grsz I figured out that even reusing one browser for many calls of newPage always leaks, in v14.2.1 I lost near 150 MiB of RAM within 2 hours just by opening random websites in new pages (one site one page):

![image](https://user-images.githubusercontent.com/1838656/174672035-5a8669ed-4bc5-4126-a0d7-e3c21400c897.png)
[code of the above experiment](https://devforth.io/blog/how-to-simply-workaround-ram-leaking-libraries-like-puppeteer-universal-way-to-fix-ram-leaks-once-and-forever/)

However I must admit that in v14.2.1 simple browser recreating solves many cases of various leaks:

```
await browser.close();
browser = await Puppeteer.launch()
```

**Comment by OrKoN** [comment]
I don't think anything survives relaunch of the browser (except for things that are stored in the user profile): which exactly strings are leaking? I am wondering if it's still an issue in the latest Puppeteer version?

**Comment by sandro-macrometa** [comment]
@Grsz, @OrKoN. Have you solved this problem on your side?
Here, I'm launching the browser once and keeping a page pool. This is causing the same "strings in memory" problem. It seems to be fixed If I open/close new tabs every time instead of using a page pool. Any thoughts?
