### ISSUE TITLE
--netifs-to-ignore doesn't work

### ISSUE THREAD

**Issue by NinoSkopac** [puppeteer/puppeteer#6744]
### Steps to reproduce
* Puppeteer version: 5.5.0
* Platform / OS version: ubuntu 20 (5.4.0-1032-aws)
* URLs (if applicable):
* Node.js version: 14.15.4

**What steps will reproduce the problem?**

```javascript
const browser = await puppeteer.launch({headless: true, args: ['--netifs-to-ignore=ens5 tun0 lo']});
//  I have also tried
const browser = await puppeteer.launch({headless: true, args: ['--netifs-to-ignore=ens5,tun0,lo']});
```

**What is the expected result?**
Connection to `tun1`, which is the only remaining nic.

**What happens instead?**
It connects to ens5 (usually called `eth0` outside AWS)

Also, the [Chromium page](https://peter.sh/experiments/chromium-command-line-switches/#netifs-to-ignore) doesn't describe how should a list look like, so I tried two variations.

**Comment by barrosa1987** [comment]
Same issue here. Not working..

**Comment by atalantus** [comment]
Same problem. Has anyone found a workaround for this?
