### ISSUE TITLE
Puppeteer behaves differently on Ubuntu Desktop and Ubuntu Server

### ISSUE THREAD

**Issue by wizo06** [puppeteer/puppeteer#6747]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: Ubuntu 20.04.1 (Desktop and Server)
* URLs (if applicable):
* Node.js version: 15.5.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Run puppeteer in Ubuntu Desktop, go to Instagram link, capture screenshot.
2. Run puppeteer (same code) in Ubuntu Server, go to the same link, capture screenshot.
3. Compare both screenshots. They are different.
  - Screenshot from Desktop: it was able to land on the link without problem.
  - Screenshot from Server: it gets re-directed to login page. (No, I'm not logging in on the Desktop either)

**What is the expected result?**
Puppeteer should behave the same way in both Ubuntu Desktop and Ubuntu Server.

**What happens instead?**
Puppeteer behaves differently depending on the platform.

### Snippet of code
```js
const browser = await puppeteer.launch({ headless: true, defaultViewport: { width: 800, height: 1440 }});
const page = await browser.newPage();
await page.goto(link);
await page.waitForTimeout(5000);
await page.screenshot({path: 'ss.png'});
```

**Comment by andretunes** [comment]
Hello!

In a way to try help you out, can I see the screenshots and/or the link?

Kind regards!

**Comment by wizo06** [comment]
@andretunes 
Screenshot from Ubuntu Server: https://cdn.discordapp.com/attachments/538282303093473292/801117933480181770/ss.png
Screenshot from Ubuntu Desktop: https://cdn.discordapp.com/attachments/538282303093473292/801118301178560532/ss.png

Link: `https://www.instagram.com/instagram/`

**Comment by andretunes** [comment]
Hi!
In your Ubuntu Server do you have interface? If yes, could you disable the headless and check what route it takes?

**Comment by andretunes** [comment]
If you prefer talk in Discord I will leave here my Discord server and my Username:
> Discord server: [https://andrezzz.pt/discord](https://andrezzz.pt/discord)
> Username: Andrezzz#0018

**Comment by wizo06** [comment]
@andretunes 
My server is running "Ubuntu Server". Meaning it has no GUI. It's actually a DigitalOcean *Droplet*.

**Comment by andretunes** [comment]
Hello!
Perhaps this comes from the fact that the IP is from a server and Instagram does this redirection.
I will need to debug so that I can tell you...

**Comment by hzburki** [comment]
I have the same issue. The code I have to log in on Instagram works on local machines (macOS and Windows 10) but does not work on AWS EC2 Ubuntu 18 servers.

### Edit 1
Turns out it had nothing to do with Puppeteer. I was scrapping Instagram and they are pretty aggressive against bots. Instagram had just blocked my dummy account and was redirecting all requests to **Not Found Page**

**Comment by wizo06** [comment]
@hzburki your issue is a little different from mine. When i run the code on my local machine, I can actually navigate all of instagram WITHOUT having to login. However, if i run the same code on my DigitalOcean VPS, i always get re-directed to the login page no matter where i try to navigate to.

**Comment by wizo06** [comment]
Closing this issue. Apparently Instagram is redirecting **everyone** to login before they can see any profile or post. My local machine just happens to have an IP address where this enforcement hasn't been "rolled out" yet (I'm assuming it's IP based).
