### ISSUE TITLE
Ship Puppeteer as JavaScript modules

### ISSUE THREAD

**Issue by mathiasbynens** [puppeteer/puppeteer#6753]
As Jack points out in https://twitter.com/Jack_Franklin/status/1349780548848390144, once [even the oldest maintenance LTS version of Node.js](https://github.com/puppeteer/puppeteer#usage) supports JavaScript modules, we can ship Puppeteer as pure JavaScript modules.

🥳 

https://2ality.com/2021/06/typescript-esm-nodejs.html

**Comment by mathiasbynens** [comment]
We might want to wait for https://github.com/microsoft/TypeScript/pull/45884 to make it into a TypeScript release.

**Comment by mathiasbynens** [comment]
As a first step, of course we should ship modules (in a way that Node.js can directly consume) alongside CommonJS. Then in the future, we can consider moving to modules-only.

**Comment by OrKoN** [comment]
> As a first step, of course we should ship modules (in a way that Node.js can directly consume) alongside CommonJS. Then in the future, we can consider moving to modules-only.

any suggestions on how we do that?

**Comment by mathiasbynens** [comment]
The link in my top post has some info.

**Comment by mathiasbynens** [comment]
Also https://2ality.com/2019/10/hybrid-npm-packages.html

**Comment by mathiasbynens** [comment]
Also https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77
