### ISSUE TITLE
how to set proxy auth ?

### ISSUE THREAD

**Issue by WG-Com** [puppeteer/puppeteer#676]
my proxy server has authentication 
```
(async() => {
    const browser = await puppeteer.launch({
    args: [  '--proxy-server='+proxyServer+'','--no-sandbox', '--disable-setuid-sandbox' ]
});
const page = await browser.newPage();
await page.goto('https://www.google.com/');
await page.screenshot({path: 'full.png', fullPage: true});
browser.close();
```

**Comment by juanchristensen** [comment]
+1

**Comment by pg1671** [comment]
+1

**Comment by bogdan0083** [comment]
+1. I still can't find a way to authenticate proxy using puppeteer. I tried to do auth like this:
```javascript
const browser = await puppeteer.launch({
    args: ['--proxy-server=IP:LOGIN:PASSWORD']
});
```
but then chromium just crashes and nothing happens.

**Comment by aslushnikov** [comment]
Dupe of #426

**Comment by WG-Com** [comment]
can you put it into example folder ? i add proxy-Auth.... header ， not work , many people care about this question  @aslushnikov

**Comment by tmpace** [comment]
+1

**Comment by androidfanatic** [comment]
Definitely +1. 
Currently using a local CNTLM installation to avoid auth.

**Comment by aslushnikov** [comment]
@androidfanatic @WG-Com @tmpace [`page.authenticate`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageauthenticatecredentials) has landed in current alpha.

**Comment by adarmanto** [comment]
Not sure, `page.authenticate` is not working for me, and I used `page.setExtraHTTPHeaders` to workaround:

````javascript
const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true, 
    args: ['--proxy-server=example.com:8080']
});
const page = await browser.newPage();
await page.setExtraHTTPHeaders({
    'Proxy-Authorization': 'Basic ' + Buffer.from('user:pass').toString('base64'),
});
````

**Comment by jancurn** [comment]
@adarmanto This will only work for HTTP websites, but not HTTPS. Here's a blog post describing a workaround - https://medium.com/@jancurn/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212

**Comment by adarmanto** [comment]
@jancurn Awesome! But I forgot to mention about `ignoreHTTPSErrors` option to work with HTTPS for my solution above (edited).

**Comment by Robertzewen** [comment]
@adarmanto  I added ignoreHTTPSErrors in args ,but also not work.

**Comment by Robertzewen** [comment]
@aslushnikov 
const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true, 
    args: ['--proxy-server=example.com:8080']
});
const page = await browser.newPage();
//await page.authenticate({'username':username,'password':password});
await page.setExtraHTTPHeaders({
    'Proxy-Authorization': 'Basic ' + Buffer.from('user:pass').toString('base64'),
});
This will only work for HTTP websites, but not HTTPS. What should I do？thanks

**Comment by greenorigin** [comment]
This actually works like a charm to me. 

const browser = await puppeteer.launch({
       args: [
        '--proxy-server=**YOUR-PROXY-SERVER:PORT**'
       ],
  });

After Pupperteer Launch use following parameters to authenticate.

await page.authenticate({
    username: '**USER-NAME**',
    password: '**PASSWORD**',
});

**Comment by ChenYCL** [comment]
global how to set?like page1,page2,page3..
