### ISSUE TITLE
Puppteer can not bypass the Custom url popup dialog

### ISSUE THREAD

**Issue by samikang** [puppeteer/puppeteer#6762]
* Puppeteer version: 5.5.0
* Platform / OS version: Winodws 10
* Node.js version: v14.15.4

**What steps will reproduce the problem?**
We want to use Puppteer for our web automation. 
During Login, on Web, one of a redirect URL will redirect to this custom url: "testapplauncher://login/callback?code=_WDzjhCkaheiRe4ZEV2n7gV5knTWnOegNnVVO7Yl".

we have a testapp and custom url registered in Windows register “**Computer\HKEY_CLASSES_ROOT\TestAppLauncher**”
![image](https://user-images.githubusercontent.com/22393010/105037861-94ed2e00-5a99-11eb-9378-571e915985f8.png)

we notice Puppteer can not auto-close the pop up Dialog, when the URL is a custom redirect url, such as:

![image](https://user-images.githubusercontent.com/22393010/105037126-789cc180-5a98-11eb-95f1-5c3d0931189b.png)

the html example:
![image](https://user-images.githubusercontent.com/22393010/105038058-d1208e80-5a99-11eb-8ea5-01b4c0db0c22.png)

We try several method to bypass the Dialog, but all fail
1. try to use Puppeteer Class Dialog APIs, but no use.
 page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.accept();
  });  

2. Try to set windows register： [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\URLWhitelist]
"1"="testapplauncher://*"
but no use for Puppeteer, **this method works on Selenium** 

This is blocking for us. Please provide a workaround or suggestion.
Thank you.

**Comment by igorski89** [comment]
hey @samikang I am trying to workaround the same scenario issue, have you found a solution already by any chance?

UPD: the issue does appear only in `headless: false` mode, still would be nice to find a solution

**Comment by niksonnet** [comment]
Hey @igorski89 ,
As also facing the same problemas @samikang is facing. I have tried to run in `headless: false` mode, but the issue still persist.

Any workaround or suggestion would be appreciated.

**Comment by sovetski** [comment]
Same here...
