### ISSUE TITLE
Error when running Puppeteer on Linux 20.04

### ISSUE THREAD

**Issue by Jeannito** [puppeteer/puppeteer#6763]
Linux 20.04
Puppeteer 5.3.0
Node 11.15
Running from the VSCode terminal

Hi everyone, when I run the project using Puppeteer on my Linux 20.04, I got the following error :

`Error: Puppeteer was unable to kill the process which ran the browser binary.
This means that, on future Puppeteer launches, Puppeteer might not be able to launch the browser.
Please check your open processes and ensure that the browser processes that Puppeteer launched have been killed.
If you think this is a bug, please report it on the Puppeteer issue tracker.`

The project is working on the precedent versions of Linux.

Here is the executable path fir chromium-browser : `executablePath: '/usr/bin/chromium-browser'`

Do anyone have the same issue or had it and found a solution ?

**Comment by Jeannito** [comment]
It works when I run it from a simple terminal prompt.

**Comment by ls84** [comment]
it happens on node and chromium installed using snap

**Comment by incoming-th** [comment]
Just joining the thread. This issue is surely caused by the fact Chromium is using snap now. No issue with google-chrome.
