### ISSUE TITLE
missing puppeteer@chrome-87 tag

### ISSUE THREAD

**Issue by Zhann** [puppeteer/puppeteer#6767]
Hi,

Is it possible to do a version release for chrome-87? https://www.npmjs.com/package/puppeteer

`puppeteer@chrome-87`.

I think this was possibly an oversight. Let me know if this is not the place for me to raise this as an issue.

### Steps to reproduce

* Puppeteer version: 5.4.0
* Platform / OS version: Debian 10

**What steps will reproduce the problem?**

`npm install --global puppeteer@chrome-87`

**What is the expected result?**

installs

**What happens instead?**

version doesn't exist (we install `puppeteer@5.4.0` as workaround)

**Comment by Zhann** [comment]
same is true for `chrome-88`. Assuming 5.5.0, cfr. https://github.com/puppeteer/puppeteer/pull/6526.

**Comment by jeroenj** [comment]
This is still the case for `chrome-89` which should point to [6.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v6.0.0): https://github.com/puppeteer/puppeteer/pull/6797.

**Comment by connorjclark** [comment]
And for all recent versions.

Very useful for a certain class of bisect scripts I have to write :)

```
97 12.0.0
93 10.2.0
92 10.0.0
91 9.0.0
90 8.0.0
89 6.0.0
88 5.5.0

```

**Comment by mathiasbynens** [comment]
We stopped tagging releases in this manner, as users generally shouldn’t depend on older Puppeteer/Chromium versions.

For your use case, you could use the information in https://github.com/puppeteer/puppeteer/blob/09426e5931fdad89f0b7ad59014f7bf766b60bb2/versions.js#L17, but note that we don’t officially support this.

**Comment by connorjclark** [comment]
Oh boy that's a great file. thanks!
