### ISSUE TITLE
(node:xxxx) UnhandledPromiseRejectionWarning TimeoutError: waiting for target failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by rahul1597** [puppeteer/puppeteer#6768]
### Steps to reproduce
This is my docker code----

COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 80
CMD [ "node", "server.js" ]

**Tell us about your environment:**

* Puppeteer version:  "puppeteer": "^5.5.0"
* OS :- Windows
Using this docker Image:- stefanscherer/node-windows

**What steps will reproduce the problem?**
Code for Puppeteer:----
![image](https://user-images.githubusercontent.com/22730148/105342859-e535ce80-5c06-11eb-9dc8-b133966ba23d.png)

1. Running the above code inside docker is giving an error

**What is the expected result?**
There should be no error, After running the app with headless true inside docker. It is working on my local machine.

**What happens instead?**
![image](https://user-images.githubusercontent.com/22730148/105343258-65f4ca80-5c07-11eb-97fd-90b14a06428c.png)

I am trying to solve it from the solution available on google but didn't help.

Solution Tried:- 
1. Increasing ram to 1GB of the docker container.
2. Adding the timeout parameter in puppeteer.launch().
3. Added sandbox, disable-extensions, and few others didn't help.

**Comment by rupadana** [comment]
i have same problem

**Comment by AhmedAbdoOrtiga** [comment]
I have same issue on image mcr.microsoft.com/windows/servercore:1809-amd64
it works fine on image mcr.microsoft.com/windows:1809-amd64

**Comment by rahul1597** [comment]
The issue is not with the puppeteer library. The issue is running chrome headlessly.
Issue:- Fonts are missing while running chrome headlessly.
Solution:- I solved my issue by downloading fonts using this command in the Docker file. you can get the **FontsToAdd.tar** on Github just search this term on google

Command:-
--- download fonts necessary for chrome to run
ADD FontsToAdd.tar /Fonts/
WORKDIR /Fonts/
RUN ./Add-Font.ps1 Fonts
