### ISSUE TITLE
Consider using Typescript strict flag

### ISSUE THREAD

**Issue by danilofuchs** [puppeteer/puppeteer#6769]
Great job on the [Typescript Migration](https://developers.google.com/web/updates/2021/01/puppeteer-typescript)!

`strict` is one of the most useful Typescript flags to catch `cannot access key of undefined` errors early on.

## Flag documentation
https://www.typescriptlang.org/tsconfig#strict

## Migration process

Having worked on migrating a big non-strict project to strict mode, I know it is quite the undertaking. Typescript does not allow to apply a flag to a single file, so enabling it directly would mean porting the entire codebase at once, which is very error-prone.

However, I have used [`ts-strictify`](https://github.com/cschroeter/ts-strictify) to run an additional CI check if enabling `strict` flag would break any **changed files**. This way, we can be sure any new code is strict.

**Comment by jackfranklin** [comment]
Would definitely like to do this and it's unfortunate we can't turn it on file by file.

I wonder if rather than immediately leaping to strict: true, if we could turn on all the flags that `strict: true` implies one-by-one in PRs? That way we might not have to fix ~400 errors all at once and might be able to bring it down.

**Comment by OrKoN** [comment]
We could turn the flag on locally and fix issues, then submit those patches with strict: false. In the end, we'd hopefully only need to fix a few regressions in the final PR that turns on strict true. We can also go by individual components but I am afraid most of errors are about getting data from hash maps.
