### ISSUE TITLE
Different screenshot between { headless: false } and { headless: true } for page.setContent

### ISSUE THREAD

**Issue by ledge74** [puppeteer/puppeteer#677]
When running puppeteer headless and using the setContent method, I observe a large difference in rendering for certain pages. Example attached for Dior landing page https://www.dior.com/home/fr_fr

**Headless false:** 
![issue](https://user-images.githubusercontent.com/6603944/30021324-47f40744-9167-11e7-8cda-87bbae4d1ea9.png)
**Headless true:** 
![issue](https://user-images.githubusercontent.com/6603944/30021346-58e53a8c-9167-11e7-9ef0-08e532dea357.png)

**Code in gist:** https://gist.github.com/ledge74/6985e4914db3bd3e494576ccd7696bb4
Puppeteer version 0.10.2
tested on MacOS 10.12.6 and Ubuntu 16.04

**Comment by aslushnikov** [comment]
If you add these lines right after `browser.newPage()`, it will work as expected:

```js
await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36');
await page.setExtraHTTPHeaders({
  'accept-language': 'en-US,en;q=0.8'
});
```

Looks like Dior doesn't respond with css unless there's a `accept-language` header.
