### ISSUE TITLE
Try catch (error / typo) in node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:707

### ISSUE THREAD

**Issue by rcdk** [puppeteer/puppeteer#6770]
![image](https://user-images.githubusercontent.com/3657898/105422398-f94bf100-5c43-11eb-988b-ec6de4d96a2f.png)

Ups :-)

node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:707

**Comment by hipoyang** [comment]
I met this trouble too.  you need upgrade your node, maybe node v12+ (in my case). GOOD LUCK

**Comment by annaelizabeth2019** [comment]
Bumping this as it is causing me problems as well

**Comment by marsaud** [comment]
Up. This is so easy to fix. Please.

**Comment by marsaud** [comment]
Same here. I have blocking problems to upgrade my node to 12+ immediatly.

**Comment by mathiasbynens** [comment]
As [the README states](https://github.com/puppeteer/puppeteer#usage):

> Puppeteer follows the latest [maintenance LTS](https://github.com/nodejs/Release#release-schedule) version of Node.

I'd recommend upgrading to Node.js 12 at a minimum, since Node.js 12 is not even LTS anymore these days.
