### ISSUE TITLE
Playing audio not working in headless mode (using Chrome)

### ISSUE THREAD

**Issue by Bojack92160** [puppeteer/puppeteer#6774]
I'm trying to play spotify via puppeteer. Because Chromium seems to not like audio file, I use chrome. 

In headful mode, everything work well, but when I switch to headless mode, the song doesn't play at all (as if I was using Chromium??).

I though headless would had the same feature than headfull.  I also tested with Edge but same problem.

Here is my code 

```
var puppeteer = require('puppeteer');
var util = require("./util.js");

async function initBrowser(){
  let browser = await puppeteer.launch({
    headless: false, //permet de voir
    slowMo: 15,
    executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    //
    //args: (url)?[ `--proxy-server=${url}`]:[]
  });
  return browser;
}


exports.main = async function(){
  let browser = await initBrowser();
  let webPage = await browser.newPage();
  await webPage.goto("https://accounts.spotify.com/en/login/", { waitUntil: "load", timeout: 30000});
  //login
  await webPage.type('#login-username', 'LOGIN');
  await webPage.type('#login-password', 'PSWD');
  await webPage.click('#login-button');
  await util.sleep(1000);

  //music
  await webPage.goto("https://open.spotify.com/artist/3nFkdlSjzX9mRTtwJOzDYB", { waitUntil: "load", timeout: 30000});
  await util.sleep(2500);
  await webPage.click('#onetrust-accept-btn-handler'); //accept cookie
  await util.sleep(1000);
  await webPage.click('div[data-testid="action-bar-row"] button[data-testid="play-button"]'); //click on play
  await webPage.screenshot({ path: 'test.png' })
}
```

Am I really still using Chrome in headless mode?

**Comment by theDavidBarton** [comment]
Yes, you are still using Chrome in headless. However: **headless mode by default uses the [`--mute-audio`](https://peter.sh/experiments/chromium-command-line-switches/#mute-audio) switch** in its `defaultArgs`, see: [/src/node/Launcher.ts#L198](https://github.com/puppeteer/puppeteer/blob/v7.0.1/src/node/Launcher.ts#L198).

According to the [api docs](https://github.com/puppeteer/puppeteer/blob/v7.0.1/docs/api.md#puppeteerlaunchoptions) it can be re-enabled with `ignoreDefaultArgs`. Can be also useful to set `--autoplay-policy=no-user-gesture-required`. E.g.:

```javascript
const browser = await puppeteer.launch({
    ignoreDefaultArgs: ['--mute-audio'],
    args: ['--autoplay-policy=no-user-gesture-required']
  })
```
I believe audio should work both in Chrome and Chromium.

**Comment by guest271314** [comment]
@theDavidBarton 

I am trying to run Chromium in headless mode from the command line, launching with
```
$HOME/chrome-linux/chrome \
--headless \
--autoplay-policy=no-user-gesture-required \
--disable-gpu \
--disable-accelerated-video-decode \
--disable-accelerated-video-encode \
--disable-software-rasterizer \
--user-data-dir=$HOME/test \
$HOME/localscripts/audio.html
```
where

```
[0620/094228.257242:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
```

is printed at terminal. 

Do you know how to avoid headless mode existing with the above message?

**Comment by theDavidBarton** [comment]
@guest271314 unfortunately I am not familiar with the above command line switches and what are their possible side-effects using them together. I suggest trying to search for the error msg on StackOverflow, (it is off-topic here under this Puppeteer issue).   
Some similar questions-answers already available: https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled, it seems that headless mode does not go hand-in-hand with the above Chrome command line switches.

**Comment by guest271314** [comment]
@theDavidBarton 

> unfortunately I am not familiar with the above command line switches and what are their possible side-effects using them together.

Chromium switches https://peter.sh/experiments/chromium-command-line-switches/

I am banned from SO for a few more years. 

I just read that SO question/answer along with several others, including https://www.reddit.com/r/chrome/comments/n6qywt/hardware_acceleration_fail_in_chrome_on_linux/.

I am using Chromium from https://download-chromium.appspot.com attempting to create solutions for this feature request https://bugs.chromium.org/p/chromium/issues/detail?id=1131236. I am experimenting with different approaches, this one is uses headless.

I can install and use Puppeteer to be "on-topic" here, yet the goal is to use as little 3d party code as possible.

**Comment by guest271314** [comment]
@theDavidBarton FWIW I filed this Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1221905.
