### ISSUE TITLE
Puppeteer is return [object Promise] in querySelector

### ISSUE THREAD

**Issue by SoloQTKiller** [puppeteer/puppeteer#6779]
* Puppeteer version: 5.5.0
* Platform / OS version: Win 10 Pro
* Node.js version: 12.16.2

_My code_

```
setTimeout(function(){
    var fgx=  page.evaluate(() => {
      //id="ctl00_ContentPlaceHolder1_dgTelefone"
      let tempo = document.querySelector("#ctl00_ContentPlaceHolder1_txtFgx").value
      return tempo
    });
    console.log(" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> " + fgx)
  }, 10000);
```

_HTML CODE_

`<input name="ctl00$ContentPlaceHolder1$txtFgx" type="text" value="07078932670" readonly="readonly" id="ctl00_ContentPlaceHolder1_txtFgx" class="CamposMd Pequeno4">
`

**Expected result?**

`07078932670`

**My code return this:**

`[object Promise]`

**Comment by vsemozhetbyt** [comment]
You just forgot await: `var cpf =  await page.evaluate(...`.
