### ISSUE TITLE
Error: Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by nwbkhan** [puppeteer/puppeteer#6780]
### Steps to reproduce
 This happens usually on Lambda, mostly after large number of requests - 300-400, and whenever any request starts to fail then all requests instantly gets failed, Sometimes fail due to Error: **Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.**
Protocol error (Emulation.setDeviceMetricsOverride): Target closed.","trace":["Error: Protocol error (Emulation.setDeviceMetricsOverride): Target closed.,    
at /opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63,
at new Promise (<anonymous>),
at CDPSession.send (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16),
at EmulationManager.emulateViewport (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EmulationManager.js:20:26),
at Page.setViewport (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:952:58),
at Runtime.exports.handler (/var/task/index.js:148:24),
at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Tell us about your environment:**

- **Puppeteer version** - 5.2.1
- **Platform** - AWS Lambda
- **NodeJs** - 12.0
- **Lambda Memory** - 4GB

**Code**
[scratch_9_.txt](https://github.com/puppeteer/puppeteer/files/5865846/scratch_9_.txt)

**What steps will reproduce the problem?**
It will occur some time and some time not, i don't think there is is any code problem and i have written await while doing _browser.close()_, I found other issues as well related to Page close and Session close, i think i noticed that on Lambda when i checked for **/tmp** folder and found that lots of **.org.chromium.Chromium.xxxxxx**, i don't know why it is not getting deleted, **that may be the case**. There are around 5-10 concurrent request from BE to call this Lambda, but i don't think so it can cause problem. **And sometime it run without any error for all of the cases without any change.** 

**What is the expected result?**
Page should visit without any problem

**What happens instead?**
Throws error **Page Navigation failed because browser has been disconnected** 
<img width="1511" alt="Screenshot 2021-01-20 at 6 12 09 PM" src="https://user-images.githubusercontent.com/10138429/105692087-03137400-5f24-11eb-96be-1fd940521b8f.png">
It also throws **ERR::INSUFFICIENT_RESOURCES**.

**Comment by nwbkhan** [comment]
The logs of /**tmp** for chrome files- 
<img width="1459" alt="Screenshot 2021-01-25 at 4 13 49 PM" src="https://user-images.githubusercontent.com/10138429/105695792-7e772480-5f28-11eb-82c4-2a2fc148cd0e.png">
FileName => size
as Lambda have /tmp with 512MB(default) it might be cause to terminate browser windows by Lambda.

**Comment by NelsonFrancisco** [comment]
Getting a similar error but in GCloud Run service

I am using the same instance of browser after `await puppeteer.launch()` and opening and closing lots of pages with the same browser instance.

I noticed I bumped to 13.5.1 version when this started happening. Downgraded back to version 13.2.0 and no more problems.
