### ISSUE TITLE
Uncaught (in promise) TypeError: puppeteer.launch is not a function

### ISSUE THREAD

**Issue by wasd345** [puppeteer/puppeteer#6781]
Uncaught (in promise) TypeError: puppeteer.launch is not a function

**Comment by orlov-vo** [comment]
Check how you import `puppeteer`? Maybe you use wildcard or asterisk import instead of default named import?
```ts
import puppeteer from 'puppeteer';
puppeteer.launch(...)
```

**Comment by wasd345** [comment]
> Check how you import `puppeteer`? Maybe you use wildcard or asterisk import instead of default named import?
> 
> ```ts
> import puppeteer from 'puppeteer';
> puppeteer.launch(...)
> ```
I'm using it in Vue

**Comment by k-yle** [comment]
I've made a PR to fix this: #6827
