### ISSUE TITLE
Error setting test environment variable

### ISSUE THREAD

**Issue by IvanSavoskin** [puppeteer/puppeteer#6783]
To run a specific test, I need to set an environment variable in process.env in my application. I tried to do this in several ways and none of them gave a result. Some of them worked in a very non-obvious way. Below are the options I tried:

Code:
```
await page.evaluateOnNewDocument(() => { process.env = { ...process.env, TEST: "test" }; });
await page.goto(testAddress);
```
Result:
```
Error: ReferenceError: process is not defined
```
---
Code:
```
await page.evaluateOnNewDocument(() => { process.env.TEST = "test"});
await page.goto(testAddress);
```
Result:
```
Error: Navigation failed because browser has disconnected!
```
---
Code:
```
await page.evaluateOnNewDocument(() => Object.defineProperty(process.env, "TEST", {
            get() {
                return "test";
            }
        }));
await page.goto(testAddress);
```
Result:
```
SyntaxError: Unexpected end of input
```
---
Code:
```
 await page.evaluateOnNewDocument(() => Object.defineProperty(process.env, "TEST", {
            get: function() {
                return "test";
            }
        }));
await page.goto(testAddress);
```
Result:
```
Error: Navigation failed because browser has disconnected!
```
---
Code:
```
await page.evaluateOnNewDocument(() => Object.defineProperty(process.env, "TEST", "test"));
await page.goto(testAddress);
```
Result:
```
Error: Navigation failed because browser has disconnected!
```
---

My environment:
* Puppeteer version: 5.4.2
* Platform / OS version: macOS 10.15.7
* Node.js version: v12.16.1

Is there some working way to set an environment variable in process.env? 
And for some reason, some of the options I've tried throw the "Navigation failed because browser has disconnected!"?

**Comment by vsemozhetbyt** [comment]
The callback function of the `page.evaluateOnNewDocument()` is executed in the browser (page, document) context, where there is no `process`. `process` exists only in the Node.js (puppeteer) context. If you need to trigger some code in the Node.js (puppeteer) context from the browser (page, document) context, you can use [`page.exposeFunction()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageexposefunctionname-puppeteerfunction), optionally transferring some arguments between contexts:

```js
await page.exposeFunction('setEnv', (key, value) => {
  process.env[key] = value;
});

await page.evaluateOnNewDocument(async () => {
  await window.setEnv('TEST', 'test');
});
```

**Comment by IvanSavoskin** [comment]
@vsemozhetbyt 
```
await page.exposeFunction("setEnv", (key, value) => {
        process.env[key] = value;
    });
    await page.evaluateOnNewDocument(async () => {
        // @ts-ignore
        await window.setEnv("TEST", "test");
    });
    await page.goto(testAddress);
```
This option also doesn't work. When switching to the page, the test crashes with the following error
```
Error: ReferenceError: fn is not defined
```

**Comment by vsemozhetbyt** [comment]
Maybe there is a race condition between `page.exposeFunction()` and `page.evaluateOnNewDocument()`. Let's hope puppeteer developers can  help.

**Comment by IvanSavoskin** [comment]
@vsemozhetbyt Thanks for the help.  Let's wait for the developers

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+. If the issue still occurs, please reopen this issue and update the description :)
