### ISSUE TITLE
puppeteer-core support firefox 85 ?

### ISSUE THREAD

**Issue by wuchuguang** [puppeteer/puppeteer#6796]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-core@next
* Platform / OS version: win10
* URLs (if applicable):  
* Node.js version:  node14

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. cant connect firefox (version 85)

**What is the expected result?**
const browser = await puppeteerCore.launch({
  product: 'firefox',
            headless: false,
            devtools: false,
            defaultViewport: {
                width: 1920,
                height: 1080,
            },
            args: [ '-wait-for-browser' ],
}); // timeout

**What happens instead?**
 UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 90000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.

puppeteer-core support firefox version 85 ?

**Comment by whimboo** [comment]
@jschfflr what would be necessary to get Firefox support for puppeteer-core?

**Comment by jschfflr** [comment]
Not sure but I'm happy to find out!

**Comment by sudeepraovm** [comment]
Hi @jschfflr, any updates on this?

**Comment by jschfflr** [comment]
@sudeepraovm Sorry for the late reply. 
Using firefox with puppeteer-core works for me. 
Could you verify if the error still occurs for you with the latest versions of both puppeteer-core and firefox?

**Comment by whimboo** [comment]
No further reply from the reporter for more than a year. Closing the issue.

**Comment by amhoba2014** [comment]
@jschfflr 
Please provide the working source code. Mine aint work:

```js
    browser = await puppeteer.launch({ 
      product: 'firefox',
      executablePath: '/usr/bin/firefox',
      headless: false
    });
```

**Comment by whimboo** [comment]
@amhoba2014 Firefox is supported for a very long time. So maybe you haven't correctly installed puppeteer to have downloaded Firefox? It's hard to tell without any further log details.
