### ISSUE TITLE
page.screenshot scrollbar artifacts

### ISSUE THREAD

**Issue by ngryman** [puppeteer/puppeteer#68]
Hey,

I noticed that when taking a full page screenshot, we can see random scrollbar artifacts.

Is there a chance that this is related to `Emulation.setVisibleSize`?

![image](https://user-images.githubusercontent.com/892048/28041838-27bc61aa-65cb-11e7-92dd-adf95db5eb69.png)

![image](https://user-images.githubusercontent.com/892048/28041876-44da4dce-65cb-11e7-8888-7768c7863260.png)

**Comment by aslushnikov** [comment]
That's definitely a bug.

@pavelfeldman is doing a heavy rewrite of screenshotting functionality deep inside chromium. I'd expect things to change a lot, so we'll revisit this bug as he's done.

**Comment by paulirish** [comment]
FWIW the `--hide-scrollbars` flag exists for headless mode (and ONLY headless mode).
but I guess it'll at least hide the problem for now. :)

**Comment by adamchenwei** [comment]
@aslushnikov @paulirish is there any way to hide the scrollbar in also visual mode?
Its creation discrepancy and can be confusing when try to run test visually instead.

Any help will be appreciated thanks!
