### ISSUE TITLE
 I cant set cookie name that starts with underscore

### ISSUE THREAD

**Issue by PBird** [puppeteer/puppeteer#6806]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: manjaro linux
* URLs (if applicable):
* Node.js version: node14

**What steps will reproduce the problem?**

When i try to set cookie name that starts with underscore 
it gives me Invalid cookie fields error  : Error: Protocol error (Network.setCookies): Invalid cookie fields

but when i set name 'Secure-3PSID' error gone. 

_Please include code that reproduces the issue._

```
 page.setCookie( {
  name: '__Secure-3PSID', // when i change to Secure-3PSID. error gone.
  value: '6geGZkm12Zkasdfsmp-adfsdfasdfsda_Nadsfdf_U4Cg.',
  domain: 'www.google.com.tr',
  path: '/'
})
```

**What is the expected result?**

I want to set cookie name that starts with underscore

**What happens instead?**

it gives me  Error: Protocol error (Network.setCookies): Invalid cookie fields

**Comment by blackcid** [comment]
It's the hypen, not the underscore. And I don't know why this happens or how to solve it.

**Comment by PBird** [comment]
> Have you tried to add __Secure3PSID?
> Because I'm having a problem with a cookie similar to it, I tested without the Hyphen and it worked.

i tested many times with underscore does not work. But  when i set cookie name 'Secure-3PSID' it is working(with hyphen). So i did not solve this problem yet.

**Comment by livingroot** [comment]
Same problem, its does not work with double underscore

**Comment by livingroot** [comment]
Cookie, which starts with __ (double underscore) must have a secure field

**Comment by vobloeb** [comment]
> Cookie, which starts with __ (double underscore) must have a secure field

setting `secure` helped with cookies prefixed with `__Secure-`
But setting cookie with name `__Host-GMAIL_SCH` is still impossible :(
