### ISSUE TITLE
Having trouble getting typing/pressing to work

### ISSUE THREAD

**Issue by Madd0g** [puppeteer/puppeteer#681]
I'm not sure what I'm doing wrong, I even tried to add logging in `up()` in `lib/Input.js` to see if my commands end up in there (they do).

I tried using `page.keyboard.down/page.keyboard.up` and `page.press`, while having an input/textarea element focused. But nothing got typed in the input.

I used something like: `page.press("keyA")`

Is there a special trick for getting these to work? Anything I can do to debug?

Thanks

**Comment by JoelEinbinder** [comment]
did you try `page.type("some text")`?

**Comment by Madd0g** [comment]
I saw it, but haven't tried that or `sendCharacter` because I'm working from keycodes.

I tried it now and it _does work_.

**Comment by Madd0g** [comment]
why close? `page.type()` is not what I need.

**Comment by JoelEinbinder** [comment]
`page.type()` sends the proper keycodes. If you aren't trying to do something fancy, `page.type("a")` is probably what you want. See https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-keyboard

`"keyA"` is not a valid key, you want just `"A"`.

**Comment by Madd0g** [comment]
I actually am trying to do something fancy, like holding keys :)
I thought I was supposed to send the `"code"` you get from a keyboard event (MetaLeft, keyA, keyS).

I tried sending just `"Meta"` and `"a"` instead, tried with `press/up/down` and none of them work for me. When I accidentally passed null in there, I got an error, so supposedly the values I'm sending are getting somewhere without error.

**Comment by aslushnikov** [comment]
@Madd0g if you want to down "A", do

```js
page.keyboard.down('A');
```

If you want to down "meta", do
```js
page.keyboard.down('Meta');
```

Same for `up`/`press`. Is this what you need?
We also have a lot of [tests](https://github.com/GoogleChrome/puppeteer/blob/51a507b2361bed942a9cc1aa384c9350cc834286/test/test.js#L1292) to check that keyboard works as expected. Tests run many different scenarios, you might find some of them useful.

Also, the full list of keys could be found on MDN: [key values](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values).

**Comment by Madd0g** [comment]
Thank you for your reply.

From reading the tests, it seems I have misunderstood `press(key, [options])`, I thought it was a combination of down/up (down holds a key and up releases it which causes a character to appear), but it only actually types if `text` is passed as part of the options?

I see this in the tests, what does 'a' do here? The test only expects 'f' to appear.

```
await page.press('a', {text: 'f'});
expect(await page.evaluate(() => document.querySelector('textarea').value)).toBe('f');
```

Maybe I'm misunderstanding down/up as well - should the following commands result in "abc" being typed? if not - why not?

```
await page.down('a');
await page.up('a');
await page.down('b');
await page.up('b');
await page.down('c');
await page.up('c');
```

**Comment by JoelEinbinder** [comment]
by default, down just sends a `keydown`, but not a corresponding `input`/`keypress`

consider
```js
await page.keyboard.down('1', {text: '!'});
```

this sends the key `1`, but inputs the text `!` if the `keydown` was not canceled. Key presses and text input are related, but they aren't the same thing. Depending on your keyboard layout, stranger things could happen.

**Comment by aslushnikov** [comment]
> Maybe I'm misunderstanding down/up as well - should the following commands result in "abc" being typed? if not - why not?

You don't misunderstand anything, this will produce "abc".
Note though: you should use `page.keyboard.down` and `page.keyboard.up` methods, there are no `page.down` and `page.up`.  The [`page.press`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepresskey-options) is just a shortcut for `page.keyboard.down` and `page.keyboard.up` (check out [implementation](https://github.com/GoogleChrome/puppeteer/blob/51a507b2361bed942a9cc1aa384c9350cc834286/lib/Page.js#L702-L707)).

So your snippet is equivalent to this:
```js
await page.press('a');
await page.press('b');
await page.press('c');
```

Let me know if it doesn't work for you.

> I see this in the tests, what does 'a' do here? The test only expects 'f' to appear.

Like you noticed, the following code snippet indeed yields "f" as a text:
```js
await page.press('a', {text: 'f'});
```

Keyboard might have different [functional layouts](https://en.wikipedia.org/wiki/Keyboard_layout), making the same key on the keyboard produce different text. For example, consider pressing `;` in two keyboard layouts: English and Spanich
- in English layout, `;` key yields `;` (naturally)
- in Spanish layout, `;` key yields `ñ` 

Consider the following example: 
```js
// Press key in english layout
await page.press(';');
// Pretend to press key in spanish layout
await page.press(';', {text: 'ñ'});
```

**Comment by Madd0g** [comment]
Thank you for the detailed explanations.

>Note though: you should use page.keyboard.down and page.keyboard.up methods, there are no page.down and page.up. The page.press is just a shortcut for page.keyboard.down and page.keyboard.up (check out implementation).

Sorry, I have been using the correct `page.press` and `page.keyboard.down` (and up), I just messed them up in that "abc" example.

>So your snippet is equivalent to this:

>await page.press('a');
>await page.press('b');
>await page.press('c');

>Let me know if it doesn't work for you.

It doesn't work. I couldn't get any press/up/down command to go through. 
I was passing my own keypresses to puppeteer (at first I was passing `event.code`, like "MetaLeft/keyA", then I switched to `event.key`, which looks like "Meta" and "a").

I tried with keydown/keyup listeners (sending two commands) and with a keypress listener (sending only one) and neither approach worked. I tried sending with `page.type()` per Joel's suggestion and that did work, but I want to support holding modifier keys.

**Comment by aslushnikov** [comment]
@Madd0g could you please share the exact script that fails to do what you want? This will help a lot with debugging.

**Comment by Madd0g** [comment]
I actually dug deeper now to see why the `page.type()` works while other methods don't. It uses this:

```
this.press(char, {text: char, delay});
```

It also passes the `{text: char}` for every keypress.
So I tried that and now `press()` works for me! Now my keypress (one message) does go through and gets typed, but it only works for letters, not any special keys.

@aslushnikov - I was really hoping I was doing something obviously wrong. I will try to make a reproducible example.

EDIT: I also looked in Input.js and it seems like the code does either `keyDown` or `rawKeyDown` based on this passed `text` option. Could rawKeyDown somehow be affected by the fact that I'm pressing keys at roughly the same time it tries typing?

**Comment by Madd0g** [comment]
Aha, new discovery! Arrows work! If I press ArrowLeft, the keyboard down/up thing works. It doesn't work with letters or modifier keys (I tried ~~Shift~~/Meta). ~~So Shift+ArrowLeft does not select text like expected, but it does move one character to the left.~~

Correction: Shift works (possible to select text with Shift+ArrowLeft), meta doesn't (doesn't jump to beginning of text on CMD+ArrowLeft).

@JoelEinbinder said:
>Key presses and text input are related, but they aren't the same thing

It seems to me now like all the things I got to work are definitely covered by the tests but the things that don't work for me are not really covered, so either they don't work or not intended to be used like I'm trying to use them (presses and input are not the same thing but I'm trying to use them like they are?)

**Comment by thetutlage** [comment]
I having some issues when trying to hold the `Shift` key and type. Ofcourse I may be doing it wrong.

```js
  const browser = await puppeteer.launch({ headless: false })
  const page = await browser.newPage()

  await page.goto('http://localhost:4000')
  await page.focus('[name="username"]')
  await page.keyboard.down('Shift')
  await page.type('hello')
  await browser.close()
```

Using the above I was expecting `hello` to be all uppercase, but it's all lowercase

**Comment by Madd0g** [comment]
Sorry it took so long, my isolated test case shows the same problems:

```js
const puppeteer = require('puppeteer');
const assert = require('assert');

(async () => {
    let browser = await puppeteer.launch({
        headless: false, // default is true
    });
    
    let page = await browser.newPage();
    await page.evaluate(() => {
        let el = document.createElement('textarea');
        document.body.appendChild(el);
        
        el.focus();
    });
    let myValue = 'abc';
    // THIS WORKS
    // await page.type('abc');

    // THIS DOESN'T
    // await page.press('a');
    // await page.press('b');
    // await page.press('c');

    //THIS DOESN'T
    await page.keyboard.down('a');
    await page.keyboard.up('a');
    await page.keyboard.down('b');
    await page.keyboard.up('b');
    await page.keyboard.down('c');
    await page.keyboard.up('c');

    
    let value = await page.evaluate(() => {
        return document.getElementsByTagName('textarea')[0].value;
    });
    console.log('value is', value);
    assert.equal(value, myValue);
})();
```

**Comment by JoelEinbinder** [comment]
@thetutlage Shift doesn't actually cause letters to be uppercase (sounds crazy, I know). Consider if the user had capslock pressed on their keyboard.

@Madd0g you have to specify the text that should be generated for the keypress. By default, `page.press` does not send an input event. 
```js
await page.press('a', {text: 'a'});
```

**Comment by Madd0g** [comment]
Thank you, I understand, you said it before but I did not really understand, now I do.

**Comment by aslushnikov** [comment]
For the record: filed https://github.com/GoogleChrome/puppeteer/issues/723 to address keyboard API confusion.

**Comment by elenaoat** [comment]
I am also having troubles with key presses. For example, I've typed some text with type, then I want to press "Enter" in order to search for some term. However, nothing happens.

**Comment by SunshowerC** [comment]
Same problem with key press . 
I test `page.keyboard.press()` at [key-event-viewer](http://w3c.github.io/uievents/tools/key-event-viewer), found there is no `keypress` event but just only `keydown` and `keyup` event.
![image](https://user-images.githubusercontent.com/13402013/31896384-329899ae-b846-11e7-9534-a58195242dee.png)

while press `enter` manually, there exist `keypress` event.
![image](https://user-images.githubusercontent.com/13402013/31896494-8042ec68-b846-11e7-9a3c-714bb289f347.png)
