### ISSUE TITLE
pdf size not completely  equal to the page.  （l can repeat）

### ISSUE THREAD

**Issue by ystop** [puppeteer/puppeteer#683]
this is my html:

```
<style>
*{margin:0}
</style>
<html>
  <body style="height:11600px;background:#000"></body>
</html>

```
when my option is : 
{ printBackground: true, width: 1920, height: '2900' }  
l should have 4(11600/2900 =4) pages and it is good.(see attachment one)

but when my option is :
{ printBackground: true, width: 1920, height: '1450' }
l should have 8(11600/1450 =8)  pages,but it give me 9 page and last one is blank page..(see attachment two).

[x1.pdf](https://github.com/GoogleChrome/puppeteer/files/1277110/x1.pdf)
[x2.pdf](https://github.com/GoogleChrome/puppeteer/files/1277113/x2.pdf)

**Comment by ystop** [comment]
export pdf, 
my web page's html : 

```
<style>
*{margin:0}
</style>
<html>
  <body style="height:11600px;background:#000"></body>
</html>
```
my page.pdf's options:
```
{ printBackground: true, width: 1920, height: '1450' }
```
 it give me 9 page and last one is blank page..  it should  8(11600/1450 =8) pages

**Comment by aslushnikov** [comment]
@ystop do you observe the same behavior with headful chrome and it's "save as pdf" feature?

**Comment by tglines** [comment]
Also getting the extra empty last page in PDF issue.

The quick solution to this problem is just setting the page ranges to print by setting the `pageRanges` param.

**Comment by aslushnikov** [comment]
@ystop @tglines this looks like a chrome's save-as-pdf issue. I'd appreciate if you file it upstream to the chromium: https://crbug.com/new and paste a bug link here.

**Comment by Alex1990** [comment]
I have come cross the same issue.

```html
<!doctype>
<html>
<body>
  <div class="slide cover"></div>
  <div class="slide"></div>
</body>
</html>
```

```css
.slide {
  width: 1080px;
  height:  810px;
}

.cover {
  background: #6c8efb;
}
```

The `Page.pdf()` options:

```js
await page.pdf({
  path: 'file.pdf',
  width: '1080px',
  height: '810px',
  printBackground: true
});
```

Then, the below image shows the result.

![image](https://user-images.githubusercontent.com/3141679/34428934-b374f660-ec8c-11e7-8e4b-c25c1f3e04d1.png)

And, then there is one extra page.

**Comment by HuyNguyen100** [comment]
Please fix this issue :(

**Comment by jbprat** [comment]
In this case, it seems to be a rounding issue while converting pixel to inches. 
I did my own conversion to inches to the upper number in js instead of relying on Puppeteer.

```
    const convertPixelToInches = (value) => {
      let inches = (Math.ceil(value/ 96 * 1000) / 1000) + 0.25;
      return `${parseFloat(inches).toFixed(3)}in`; // Calculate inches value and round it up.
    }
    const pageWidth = convertPixelToInches(height);
```

**Comment by aslushnikov** [comment]
This seems to be a dupe of #4015. @Nik-Voelker did a nice explanation on PDF sizes [here](https://github.com/GoogleChrome/puppeteer/issues/4015#issuecomment-470514965).
