### ISSUE TITLE
waitForSelector("…:focus") doesn’t resolve on focus change

### ISSUE THREAD

**Issue by andersk** [puppeteer/puppeteer#6830]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.1
* Platform / OS version: NixOS
* URLs (if applicable):
* Node.js version: 14.15.4

**What steps will reproduce the problem?**

```js
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.evaluate(() => {
    const e = document.createElement("input");
    document.body.append(e);
    setTimeout(() => e.focus(), 1000);
  });
  await page.waitForSelector("input:focus");
  await browser.close();
})();
```

**What is the expected result?**

`waitForSelector("input:focus")` should resolve when focus changes to the input element.

**What happens instead?**

`waitForSelector("input:focus")` hangs and times out. I think this is because it’s only listening to DOM mutations, which a focus change is not.

If I `await page.waitForSelector("input:focus", { visible: true })` instead, that resolves as expected.

**Comment by andersk** [comment]
Still reproduces in Puppeteer 15.1.0.

**Comment by andersk** [comment]
Still reproduces in Puppeteer 17.0.0.

**Comment by OrKoN** [comment]
It looks like it does not work because Puppeteer is using the mutation observer to determine when to re-query things. The workarounds are to use `await page.waitForSelector("input:focus", {visible:true})` which should switch to RAF-based polling to `await page.waitForFunction` that polls are regular intervals.
