### ISSUE TITLE
Google login not working ?

### ISSUE THREAD

**Issue by carefulcomputer** [puppeteer/puppeteer#6832]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.1
* Platform / OS version: MacOS Catalina
* URLs (if applicable): google.com
* Node.js version:12.20.1

**What steps will reproduce the problem?**
Try login into https://hangouts.google.com/
After entering username, getting message 

`Couldn't sign you in This browser or app may not be secure. Learn more Try using a different browser. If you're already using a supported browser, you can refresh your screen and try again to sign in.
`

Here are puppeteer options:

```
const browser = await puppeteer.launch({
    headless: false,
    userDataDir: <profileName>,
    excludeSwitches: 'enable-automation',
    ignoreDefaultArgs: ["--enable-automation"],
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    slowMo: 50,
  });
```

**Comment by mrceperka** [comment]
Try `puppeteer-extra-plugin-stealth`

**Comment by FurriousFox** [comment]
or add `ignoreDefaultArgs: ['--enable-automation', '--disable-extensions', '--disable-default-apps', '--disable-component-extensions-with-background-pages'],` to your puppeteer launch options

**Comment by corzani** [comment]
@FurriousFox your approach doesn't work anymore. Do you know any other trick to be able to login in google via puppeteer?

**Comment by OrKoN** [comment]
Please file a new issue if there is a still a problem.
