### ISSUE TITLE
Puppeteer not installing on AWS ElasticBeanstalk instance

### ISSUE THREAD

**Issue by onamission** [puppeteer/puppeteer#685]
I am attempting to install Puppeteer using an automated build script on AWS ElasticBeanstalk and am getting a failure that I can't reproduce on a nearly identical local Vagrant server when using the same version of nodejs, npm and puppeteer. The AWS server logs begins with:
```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/node',
1 verbose cli   '/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/npm',
1 verbose cli   '--production',
1 verbose cli   'rebuild' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 info readInstalled object
```
and ends like this:
```
9742 info lifecycle puppeteer@0.10.0~install: puppeteer@0.10.0
9743 verbose lifecycle puppeteer@0.10.0~install: unsafe-perm in lifecycle false
9744 verbose lifecycle puppeteer@0.10.0~install: PATH: /opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/tmp/deployment/application/node_modules/puppeteer/node_modules/.bin:/tmp/deployment/application/node_modules/.bin:/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin:/opt/elasticbeanstalk/lib/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
9745 verbose lifecycle puppeteer@0.10.0~install: CWD: /tmp/deployment/application/node_modules/puppeteer
9746 silly lifecycle puppeteer@0.10.0~install: Args: [ '-c', 'node install.js' ]
9747 silly lifecycle puppeteer@0.10.0~install: Returned: code: 1  signal: null
9748 info lifecycle puppeteer@0.10.0~install: Failed to exec install script
9749 verbose stack Error: puppeteer@0.10.0 install: `node install.js`
9749 verbose stack Exit status 1
9749 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
9749 verbose stack     at emitTwo (events.js:106:13)
9749 verbose stack     at EventEmitter.emit (events.js:191:7)
9749 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
9749 verbose stack     at emitTwo (events.js:106:13)
9749 verbose stack     at ChildProcess.emit (events.js:191:7)
9749 verbose stack     at maybeClose (internal/child_process.js:891:16)
9749 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
9750 verbose pkgid puppeteer@0.10.0
9751 verbose cwd /tmp/deployment/application
9752 error Linux 4.9.38-16.35.amzn1.x86_64
9753 error argv "/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.1-linux-x64/bin/npm" "--production" "rebuild"
9754 error node v6.11.1
9755 error npm  v3.10.10
9756 error code ELIFECYCLE
9757 error puppeteer@0.10.0 install: `node install.js`
9757 error Exit status 1
9758 error Failed at the puppeteer@0.10.0 install script 'node install.js'.
9758 error Make sure you have the latest version of node.js and npm installed.
9758 error If you do, this is most likely a problem with the puppeteer package,
9758 error not with npm itself.
9758 error Tell the author that this fails on your system:
9758 error     node install.js
9758 error You can get information on how to open an issue for this project with:
9758 error     npm bugs puppeteer
9758 error Or if that isn't available, you can get their info via:
9758 error     npm owner ls puppeteer
9758 error There is likely additional logging output above.
9759 verbose exit [ 1, true ]
```
The only way I can replicate those last few lines (where the error occurs) on my local Vagrant environment is to use an older version of nodejs (pre 6.4). 

My AWS is running on Linux 4.9.38-16.35.amzn1.x86_64
My local Vagrant is using Linux 4.4.0-93-generic

Any insight would be appreciated. (Also, let me know if the full logs would be helpful, I can provide those as well.)

**Comment by johnferro** [comment]
Can you check in the eb-activity log and see if there's any output from the install script?

**Comment by onamission** [comment]
BAM!

Thanks @johnferro I found this in there -- which would be an issue:

```
puppeteer@0.10.1 install /tmp/deployment/application/node_modules/puppeteer
  Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/puppeteer/.local-chromium'
      at Object.downloadRevision (/tmp/deployment/application/node_modules/puppeteer/utils/ChromiumDownloader.js:97:10)
      at Object.<anonymous> (/tmp/deployment/application/node_modules/puppeteer/install.js:28:12)
```

**Comment by onamission** [comment]
And, for anyone like me, who is new to this, here is how to fix this issue is to change your gulp script to include hidden (.dot) files ([see here)](https://stackoverflow.com/questions/32826200/gulp-src-include-files-but-ignore-all-folders)
```
gulp.task('createBuild', function() {
    gulp.src(['.ebextensions/nginx.config', '.ebextensions/mount.config' ])
        .pipe(gulp.dest('dist/.ebextensions/'));
    return gulp.src(['**', '**/.*' ])
        .pipe(gulp.dest('dist/'));
});

gulp.task('zip', function() {
    return gulp.src(['dist/**/*', 'dist/.*/**', 'dist/**/.*'])
        .pipe(zip('dist.zip'))
        .pipe(gulp.dest('./'));
```

**Comment by johnferro** [comment]
@onamission 👍 Glad you figured it out! Just wanted to note that you can be using elasticbeanstalk without gulp so your solution might not work for other people and a more general solution might be to make an ebextension that ensures the folder has the proper permissions in order to make the .local-chromium directory.  But as long as your solution is working for you I'd recommend closing this issue out.

**Comment by DiegoRBaquero** [comment]
Looking for a general solution, has anyone figured it out?

@onamission why does including dot files in the build help? I'm deploying with `eb deploy` but running into the same error.

Tried assigning the app folder to nodejs user with `chown` but still, `node_modules` would belong to root when `npm install` was executed.

**Comment by DiegoRBaquero** [comment]
It seems to work with node 6.11 and 7.10, doesn't in 8+. Must have to do with npm.

Related: https://forums.aws.amazon.com/thread.jspa?messageID=795165#795165

**Comment by chimmelb** [comment]
For those still running into this: I created this gist to load this as an .ebextensions config file. https://gist.github.com/chimmelb/6342504893b2b9fce0f4a8efd096ae60

**Comment by nomankt** [comment]
+1

**Comment by Aditya-ds-1806** [comment]
For those still facing the issue, I suggest going through your logs. If you have a permission denied error similar to @onamission, just include a `.npmrc` file in the root directory and include this:
`unsafe-perm=true`

**Comment by amarinediary** [comment]
> For those still facing the issue, I suggest going through your logs. If you have a permission denied error similar to @onamission, just include a `.npmrc` file in the root directory and include this:
> `unsafe-perm=true`

So that actually did it for me tho i'm running in a second issue `error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory`.

Apparently that solution is just a bypass for the first problem.

**Comment by kylewetton** [comment]
> For those still facing the issue, I suggest going through your logs. If you have a permission denied error similar to @onamission, just include a `.npmrc` file in the root directory and include this: `unsafe-perm=true`

This isn't make any difference for me unfortunately

**Comment by kylewetton** [comment]
> https://github.com/amarinediary/Puppeteer-AWS-Elastic-Beanstalk-Deployment-Hotfix

Thanks mate, that does fix the installation error however I'm presented with this error when running the app

``` 
Mar  4 06:00:14 ip-172-31-27-198 web: (node:4324) UnhandledPromiseRejectionWarning: Error: Could not find Chromium (rev. 1095492). This can occur if either
Mar  4 06:00:14 ip-172-31-27-198 web: 1. you did not perform an installation before running the script (e.g. `npm install`) or
Mar  4 06:00:14 ip-172-31-27-198 web: 2. your cache path is incorrectly configured (which is: /home/webapp/.cache/puppeteer).
Mar  4 06:00:14 ip-172-31-27-198 web: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
```
