### ISSUE TITLE
v7.0.4 bloats Serverless Functions

### ISSUE THREAD

**Issue by vasco3** [puppeteer/puppeteer#6853]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.4
* Platform / OS version: Vercel.com 
* URLs (if applicable): 
* Node.js version: 14+

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Next.js app running with Serverless Functions for transforming a loaded page with puppeteer into a pdf
2. upgrade to puppeteer-core v7.0.4
3. redeploy to Vercel

**What is the expected result?**
It should deploy correctly

**What happens instead?**
The deployment fails because the Serverless lambda functions exceed the AWS limit of 50MB.
Somehow the new puppeteer bloats this Serverless Functions.

**Comment by luizwhite** [comment]
Same happening to me
I had to downgrade both to 5.5.0

**Comment by luizwhite** [comment]
Besides, I am having this problem too https://github.com/alixaxel/chrome-aws-lambda/issues/82

**Comment by vasco3** [comment]
Closing because I just moved it to it's own project so it has more room. Feel free to re-open if needed

**Comment by luizwhite** [comment]
If you could re-open..
The problem exists, and it appeared only after i used puppeteer screenshot feature
@vasco3

 I will monitor it
