### ISSUE TITLE
TS2724: puppeteer has no exported member named ScreenshotOptions

### ISSUE THREAD

**Issue by jdanil** [puppeteer/puppeteer#6866]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.4
* Platform / OS version: Windows
* Node.js version: 14.15.5

**What steps will reproduce the problem?**
 
1. `import { ScreenshotOptions } from "puppeteer";`

**What is the expected result?**

`tsc` compiles successfully.

**What happens instead?**

```
error TS2724: '"node_modules/puppeteer/lib/types"' has no exported member named 'ScreenshotOptions'.
```

**Comment by nikolasrist** [comment]
The same issue for BinaryScreenshotOptions: 
```
src/exports/exports.service.ts:6:10 - error TS2305: Module '"../../node_modules/puppeteer/lib/types"' has no exported member 'BinaryScreenShotOptions'.

6 import { BinaryScreenShotOptions, Page } from 'puppeteer';```

**Comment by jdanil** [comment]
Thanks for the quick fix @jackfranklin!
