### ISSUE TITLE
Inserting into a dialog with prompt? (Question)

### ISSUE THREAD

**Issue by td0m** [puppeteer/puppeteer#687]
Hey, I would like to insert some data into a JS prompt [like this one](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt). Is that possible with puppeteer? 
Thanks 😎

**Comment by JoelEinbinder** [comment]
Yes. https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-dialog

**Comment by aslushnikov** [comment]
There's a snippet in the API: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-dialog

```js
const puppeteer = require('puppeteer');

puppeteer.launch().then(async browser => {
  const page = await browser.newPage();
  page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.dismiss();
    browser.close();
  });
  page.evaluate(() => alert('1'));
});
```

**Comment by td0m** [comment]
@aslushnikov Thank you so much 😉
