### ISSUE TITLE
How to scroll up (go to top) using puppeteer?

### ISSUE THREAD

**Issue by chanakaDe** [puppeteer/puppeteer#6872]
Hello guys, 

I'm looking for a way to scroll up using puppeteer. There are many solutions to go down. But nothing to up in the page using puppeteer. Is there any way to do that? Or puppeteer is not capable to handle page scroll up? 

Please let me know. 

Thank you in advance.

**Comment by vsemozhetbyt** [comment]
Something like this?
```js
await page.evaluate(() => { window.scroll(0,0); });
```
