### ISSUE TITLE
[7.0.4] Missing types on import

### ISSUE THREAD

**Issue by spinlud** [puppeteer/puppeteer#6873]
* Puppeteer version: 7.0.4
* Node.js version: 12.x

```ts
import { Request } from 'puppeteer';  // <--- Missing types
```

See also https://github.com/puppeteer/puppeteer/issues/6816, https://github.com/puppeteer/puppeteer/issues/6820, https://github.com/puppeteer/puppeteer/issues/6829

**Comment by thomassuckow** [comment]
`Request` is now `HTTPRequest`

**Comment by jackfranklin** [comment]
@thomassuckow thank you - you're correct. `Request` conflicted with other types in the platform so we swapped to `HTTPRequest`. See also `Worker` => `WebWorker` and `Response` => `HTTPResponse`
