### ISSUE TITLE
Better types for page.evaluate()

### ISSUE THREAD

**Issue by thomassuckow** [puppeteer/puppeteer#6874]
**Tell us about your environment:**

* Puppeteer version: 7.0.4

`page.evaluate()` currently expects a function that takes at least one argument but because of the generic with default to any it doesn't really require that argument. The args provided to evaluate don't have to match at all, there is no checking.

**What is the expected result?**

Types of function arguments should be checked and enforced. Ideally inferred when possible.

Here is an initial pass at making it handle the types. One limitation is that it does not understand too many arguments being passed to evaluate unless you explicitly provide the function type as the first generic arg. The upside to this is that the function arguments can be inferred from those passed to evaluate.

The more important missing piece is this does not handle wrapping / unwrapping JSHandles. Though this should be possible with variadic generics.

[Playground](https://www.typescriptlang.org/play?#code/PTAqAsEsGcAIdgOwPYBdavAU1gJywIYA2GAngA5YA0sAVgK7TqrKwC2BA1jpglgB4E25IjgDuyXJwBQA8pPQATLAGMiBfGUqwAyllyRikAF4EARqIDyuAFI6AEgUSLRsALxJ6bM-tgAfWCYDRABzf1gzZGRRJ3DEeiIiAG5paRAAISwQyERYclxkeWgsRVgVcCcQrGhZfnlcJVV1TVQKHABRADdiegJULAAxRAAeAEFYAX7nOD0DI1MLLGs7R2dRAG0AXXdYJ1IAPh2gnLCAgAozgDprjRDoAC5YUYBKd0O955S5BVhlNQ0eG1YF0en1BogAEpYVD0XCIUBtYagCb8KaKOAgoi9fpDQ4eZGTLDTWBXG64O6PPZbV5uQ45ABmvghsAA-LBmY96IhOCgxIgvnUfn9moDtJjseDRuToEiUWiMd0sWDcTsCaiieiSddLrcHvBEIzcE8ae9EKRWU9YI9ZoYiCZzFZbA4nC4sFsUtJ6VyVKhIMhclhFRLhgM5RqFaCcSNRvsaONCcSbfMHUsnatXVsduLlYgpXcQ-t9mcvYgVI8BjRtbrHi9HgAFApsGBYYbZqNQmFwhGUAth4kN5BN4oAGUg3GGDN8AFVDmyp1bgUGcx3YfDEQNC7AAN7SWB7sr+phlAhMPNwDy63YzfS2+2LZbOtZuzYpfewEAQHCRRTmmCIADk6CQMIChOKgu77ioh7RFglxEMgITFt6lwsDoqDBIhzyVtcKgnqgZ6fBBe6QPSZytJQyD0rAJYqO4bgeP+NG+v6-6vDub5vvgna5AOQ6wfg0DRJ0WAXDRV6wAM3rMYgzykpcuGntKzyEW+AC+ExEMU25ERxXGrrAvHNpcAlCSJrwngZjbNsMez7K++6qdIjkgO0ziWYUyDFKUADCFShNUqTSFBiBHvSUQ7IGkYiQARGFyDRYRwWhVEABMEVLv0ZyxVE0U0NFBC5bAKWJYe6BmBo6VRRcBA0GYJq7LAADUEQ0AAjDQxUpElZUaGlHiRUqmVnDVET1QQTUtbA7VFTQADMJUhT1uCzZVg0tsN9zxN4+i1ZtXg+Lg9VbQdRbDbVY0TWYbUdXNC1Hrh6D9RlIlnPV9LEMU11FYR0jkTg6QVR4bbgiuXaIhtx07REe3bYdbyeLDdlpMAf2wADRoeJDuC-UC6Nnlmz1DGewwQ-tUNmDDB1HWTuBIyAqN49KOzrAQjxY7tCMHZsQA)

**Comment by jackfranklin** [comment]
Thanks for opening this issue. The current `evaluate` types are taken from the old @types package but also aren't as fully featured yet. I plan to revisit this soon and your examples will come in handy - thanks!

**Comment by thomassuckow** [comment]
Doesn't work but a little more effort : [Playground](https://www.typescriptlang.org/play?ts=4.1.3#code/PTAqAsEsGcAIdgOwPYBdavAU1gJywIYA2GAngA5YA0sAVgK7TqrKwC2BA1jpglgB4E25IjgDuyXJwBQ0gMZEC0OACkAygAkCiACajYAbwC+shUrgBRUWyyJUW3aIA8F2ANS2dl67dQA+N34PXVVNbT0cY3lFZVgAMXpEOVRIZEQHCKc4wOCveMTk1MQA909QjP0o6QFySXQdLDN8MkpYNSxcSGJIAC8CACN9AF4kejZ+jtgAH1gmTsQAc2nYfuRkUW1lxHoiIgBuav5a3HrGxWbUChx2zu6+wawAeVx1CpwRm66iXoH9GdfwqIDjU6rAGk0eFdYG9fu9YFYsDY7MsEkkUmlgUdQeDzpDWp87rDnjCHrAPh0vj9STMSUDZCCTmCzgQLlCAOq4AjkAGOLAuHJlaGAwgPAIjVylELwnzIgD80sRvjeLgCAC54ZjjqcIS0cABVRBiTncsK8-mSvI8iJi+ECqUIpH2YVOSCIABmk1AAXloFg6osB2kIAZ2txutgHK5AEFcAsnFG7XkANqgGgAOgzACUALo0X0WuAE773UTE4WwsltCmEh5l3mwmiZxOF6vFom4WlYJPZytFqmljvlh7dm1NguwbuweVJyPkPslp6D+sPJxenvqmfG+ftzurvzpjOzmNxzN+bMHYNYxk4ll4nBH2PQePNqu3Nu1pcRWEjysPuNRvxAxDJkdUuVo-yfUB6BEHBx23D9Ox-EYDAnABJXQBHgRBYG4UhkDdWAoJg7N1SI0Qk3Qhp+B7cdOynCNjStZwyK7SiBGzNVCOg8i2Oo2AjE1bFmVZVoDSNaNH1XbjYKCQV4IHJiuw4ysUIojD+CwnCsDwgiWJIriYLUqiaNkqVFPosTGNNTIWKM9jONs3iewE2QQAAISwBZXVgchcGQWpoCwHRYDkcBtAWLBoEOLUQLDMCcAsAA3Yh6AIDw4kQZ84NbftF0QnsRm0UgbTmV0lhmAAKCqMzTFkFmgdUowASjJAIiqawTr2Eu94WSohUvSxBMywVB6FwRBQCuVcXySlK0qwDKbXzUy8mqjM6oa2Aiu7FqhgCV0PVwWAm3lJt1USTgUDERBOtDW9w1m-r5oy49IJmvqBoW4pK2W3I4DW2rH3VA7Jma1qtsQUh6ITdV5LyodyPPWQ3QKdFsKwD75qyd65sGytHs+jKnANCD4z8fdYATbK31y55FMnEZSYJ57EFerJyb8CqUaSdU4gPQH6sapr1QABT8tgYD5ZnBuG0bxsmyh2ZfMXkAlwKABlIG4F13UmPVvVgPU-V63GvtlsaJqmuJycMaRYHtkK0iYEKlFQV7Kw2raWxphc6esxGDgd2AQAgHBVh0KGYEQABydBIGEOptFQO2HbkJ31iwNMiGQBYuYKNMWDUVB5lzpr+bkV3Xo6lP7cgN0Kvi-DYG5uQySGEZo5btHo5agwa6DvARot2AVbVzP8GgdZEqwKqW69-I0SKJqAYrpgq+roOjDcIhAttgeHfwOXsNHyW0wnqeZ5apQR-FyWnCKwD+5MEwQAsXQb-85BAuCgBhMLFkisjVGRQtqPlAJFVAWUVre0pL7T8GxhwcQBhtIW6pSYAT3g7TAfkxBICwLgiwuA-K4AqgAIgAHJoFgKhYQMoPA6FIdXEw0gu4gMSBtcBTAoF-VfLA9s9MkE1RQZTYWhtDTGjZhgvuQdsHIFwYgfB8IiGSDIZQ9ANCYKOiCowg4zD5BO3QHCBRBC6EVWrmnRAzssDgErMYhUjplQOl8JzcxBiMAQI9mAiBFUACMNBo4EGjjQLArjLHMAgQAJk8fVThqAAYeCYKE52CTUAAGZKzsK8UweJEDq76LCc3NYlYMamzIW6NYOj8nO3KcgKJIwSlPQ8GUipNBSEEFITQCJST0D9BZMUzGTSKoEBoP0GgchdptVgAAahWDQPxsAInBPAN0lYLI6luAGTPIZIyJlbWmbM2A8zFmwFSSs3puB0n1M2U4IZqptjjA6CMu5YwJi4F2fc15nNtkrF2QQfZozDmdJoKcg4FjnYV3QFc0pZjwZumIIFOZnS8nxVgG5Pp4pNkZXNvLKatyPmPJWM8h5bzwb4twI-EAKK0VHRGGS6QVKWTuwxabF6kk8UvIJf0Ilrz3kcvJReYADLcBMonAQdUZKnmjGJdmIAA)

May be possible with some sort of overloading the method, not sure if it can include generics then.
