### ISSUE TITLE
New session and cookies for each new page

### ISSUE THREAD

**Issue by abokizh** [puppeteer/puppeteer#6875]
I am using headless chromium in incognito mode. I need to auth on a website with different account using one single browsers with separate pages simultaniously

```
async function newPageWithNewContext(browser) {
    const { browserContextId } = await browser._connection.send('Target.createBrowserContext');
    const { targetId } = await browser._connection.send('Target.createTarget', { url: 'about:blank', browserContextId });
    var targetInfo = { targetId: targetId }
    const client = await browser._connection.createSession(targetInfo);
    const page = await browser.newPage({ context: 'another-context' }, client, browser._ignoreHTTPSErrors, browser._screenshotTaskQueue);
    page.browserContextId = browserContextId;
    return page;
}
```

I use this function to create a new page

`
const page = await newPageWithNewContext(browser);
`

but pages still share cookies and sessions. How can I turn it off?

**Comment by mrceperka** [comment]
Try to create incognito browser contexts `browser.createIncognitoBrowserContext()`.

**Comment by abokizh** [comment]
@mrceperka I had `--incognito` in my browser args, but I additionally tried to add `browser.createIncognitoBrowserContext()`, but still, tabs share cookies and sessions...

**Comment by mrceperka** [comment]
@abokizh If you want to have independent/incognito page, you have to do following:
```js
// 1.
const context = await browser.createIncognitoBrowserContext()
// 2.
const page = await context.newPage()
```

If you want another incognito page, you have to repeat these steps -> create another context

This way it works for me, hopefully it will work for you as well.

**Comment by abokizh** [comment]
Thank you! It worked!

**Comment by abokizh** [comment]
@mrceperka Just in case, it creates TABS with separate sessions and cookies, right, or does it create separate windows/browsers?

**Comment by mrceperka** [comment]
@abokizh AFAIK it does NOT create separate browsers. So it should be more efficient solution than launching many incognito browsers.

**Comment by abokizh** [comment]
@mrceperka I tried this code, it indeed creates tabs with separate sessions but those tabs are in different browsers. The this that I want is to have a single browser, with bunch of tabs opened that have separate sessions, so I can log in on the same website as different users. 

I tried code mentioned in this [ISSUE](https://github.com/puppeteer/puppeteer/issues/85). It creates tabs on the same browser with different cookies, but, when I login in one tab, other tab logs in as the same user.  

Any ideas on how I could accomplish this?

**Comment by mrceperka** [comment]
I don't think it's possible to do what you want. More precisely, I don't know how :D

_Thoughts:_
_Maybe it is possible (maybe lower level api could help, dunno), but it sounds kinda weird._

_Try to imagine that you are using regular browser.
You open a browser, create first tab and then the second tab (in the same window/context) and you want those 2 tabs to be independent._

**Comment by sir-reynolds** [comment]
@mrceperka in regular browser you can use sessionbox extension to create multi session on each tab

**Comment by RaxoCoding** [comment]
So is it possible to do this?

**Comment by joebetmutia** [comment]
stumbled to a requirment that needs this..


@abokizh may i ask if you had accomplish this please? care to share your approach. thank you

**Comment by j4gd33p** [comment]
Looking for same behaviour like SessionBox extension do. But did not succeed so far. 
Can we control sessionbox with Puppeteer if there is no direct solution.
and I think `createIncognitoBrowserContext()` is not part of API in latest versions.
