### ISSUE TITLE
[7.0.4] Can't import  type Viewport

### ISSUE THREAD

**Issue by uyamazak** [puppeteer/puppeteer#6876]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.4
* Platform / OS version: Mac OS 11.1
* Node.js version: v14.14.0
* TypeScript version: 4.1.5

**What steps will reproduce the problem?**

```
import { Viewport } from 'puppeteer'
// Module '"../../node_modules/puppeteer/lib/types"' has no exported member 'Viewport'.ts(2305)
```

**What is the expected result?**
import this type without any error

**What happens instead?**

I neeedd this type.
```
https://github.com/puppeteer/puppeteer/blob/main/src/common/PuppeteerViewport.ts
```
but it seems not to be exported in  `node_modules/puppeteer/lib/types.d.ts:24210`
```
declare interface Viewport {
    width: number;
    height: number;
    deviceScaleFactor?: number;
    isMobile?: boolean;
    isLandscape?: boolean;
    hasTouch?: boolean;
}
```

**see also**
https://github.com/puppeteer/puppeteer/issues/6873
https://github.com/puppeteer/puppeteer/issues/6816
https://github.com/puppeteer/puppeteer/issues/6820
https://github.com/puppeteer/puppeteer/issues/6829

**Comment by jackfranklin** [comment]
Thanks. #6881 will resolve this so marking this as closed.
