### ISSUE TITLE
`page.waitForFunction` types

### ISSUE THREAD

**Issue by jackfranklin** [puppeteer/puppeteer#6884]
Our TS defs don't give much help to `page.waitForFunction` and doesn't infer as much as I'd like.

See this example:

```ts
frontend.waitForFunction((msg: string, ln: Element) => ln.textContent === msg, {timeout: 0}, message, line));
```

It would be nice to not have to explicitly type those arguments.

**Comment by amprew** [comment]
Happy to help out with this if it's available? Did you mean inferring the types from the spread arguments? I put together a little mock for it:

```ts
  waitForFunction<Args extends SerializableOrJSHandle[]>(
    pageFunction: ((...args: Args) => boolean) | string,
    options: {
      timeout?: number;
      polling?: string | number;
    } = {},
    ...args: Args
  ): Promise<JSHandle> {
```
