### ISSUE TITLE
Hover after hover

### ISSUE THREAD

**Issue by khaitranhq** [puppeteer/puppeteer#6886]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.1
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: 12.20.1

**What steps will reproduce the problem?**

Run script below
```typescript
const Puppeteer = require('puppeteer');

(async () => {
  const browser = await Puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('https://juno.vn/');

  await page.hover('[data-anmation="1"]');
  await page.hover(
    '[data-value="Xanh lá"]'
  );

  await browser.close();
})();
```

**What is the expected result?**
The running script doesn't show errors, I can trigger hover event after hovering another element. 

**What happens instead?**
```
UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
```

Maybe after the hovering command did, the mouse moveout that element, so elements appearing when the hovering event trigger were not show

**Comment by vsemozhetbyt** [comment]
Can reproduce, but only in headless mode.

**Comment by lioaslan** [comment]
Any update on this problem?
