### ISSUE TITLE
这个能运行在云服务器上吗？

### ISSUE THREAD

**Issue by charmby** [puppeteer/puppeteer#6897]
这个能运行在云服务器上吗？

**Comment by feijuncheng** [comment]
当然可以，不过要注意下系统，centos版本不能太低，尽量7+

**Comment by charmby** [comment]
> 当然可以，不过要注意下系统，centos版本不能太低，尽量7+

嗯嗯，非常感谢回复，不过好像没找到教程，你这边有链接、api或者demo吗？谢谢哈
