### ISSUE TITLE
executablePath() is not recognized

### ISSUE THREAD

**Issue by SebaM90** [puppeteer/puppeteer#6899]
* Puppeteer version: 7.1.0
* Puppeteer Types version: 5.4.3
* Platform / OS version: Windows 10
* Node.js version: 14.15.3

After updating Puppeteer no longer recognizes the **executablePath()** method:

![image](https://user-images.githubusercontent.com/39964514/108210720-ad894c00-710a-11eb-8429-53225beb9f7c.png)

**Comment by Niek** [comment]
Can confirm the same issue.

**Comment by SebaM90** [comment]
I solved it temporarily by changing
`... = puppeteer.executablePath();`
to this:
`... = (puppeteer as any).executablePath();`

☺

**Comment by ItWorksOnMyMachine** [comment]
Same issue with createBrowserFetcher

**Comment by baruchiro** [comment]
Maybe related #7100

**Comment by thw0rted** [comment]
I'm having this issue and noticed that the type definitions include a class `PuppeteerNode`.  The comments for that class say that, when you `import puppeteer from "puppeteer"` or the equivalent `const puppeteer = require("puppeteer");`, the result should be typed as `PuppeteerNode`.  Instead, I think it's just typing as `Puppeteer`, which has a similar interface but with fewer methods.  `executablePath()` is one of those missing methods.

Either that needs to be fixed, or something about my project configuration is causing TS to use the wrong type for the imported module.  In the meantime, this is a safer version of the cast above:

````ts
import puppeteer from "puppeteer"

process.env.CHROME_BIN ||= (puppeteer as any as puppeteer.PuppeteerNode).executablePath();
````
