### ISSUE TITLE
Clicking on link does not navigate page

### ISSUE THREAD

**Issue by namuorg** [puppeteer/puppeteer#6900]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.1.0
* Platform / OS version: macOS Big Sur 11.2
* URLs (if applicable): https://www.starterstory.com/explore
* Node.js version: 14.15.1

**What steps will reproduce the problem?**

This script clicks the first case study link on [Starter Story](https://www.starterstory.com/explore):

```javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 250,
  });
  const page = await browser.newPage();
  await page.goto("https://www.starterstory.com/explore");

  await page.click(".explore-container > div > .link-overlay");
})();
```

**What is the expected result?**

The first case study summary is clicked, which navigates the page to the case study.

**What happens instead?**

The first case study summary is clicked, but the page does not navigate and the clicked element shows the hover state.

### Investigation

The click occurs as expected when [Puppeteer's `click` implementation](https://github.com/puppeteer/puppeteer/blob/v7.1.0/src/common/Input.ts#L416) is changed to wait for each mouse function rather than using `Promise.all`:

```typescript
await this.move(x, y);
await this.down(options);
await this.up(options);
```

instead of

```typescript
await Promise.all([
  this.move(x, y),
  this.down(options),
  this.up(options),
]);
```

Is there a reason why `Promise.all` is preferred over waiting for each step?

#### Steps to test implementation change

1. Clone puppeteer
2. Make code change as described above in `Input.ts`
3. Run `npm install && npm run build`
4. Run `npm link`
5. Go to repository with test code as given in issue
6. Run `npm link puppeteer`
7. Run `node index.js`

**Comment by ddoonngg** [comment]
Hi, it seems that you forgot to hover the that `div` to enable the link element before you click it.
Please try:
```javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 250,
  });
  const page = await browser.newPage();
  await page.goto("https://www.starterstory.com/explore");

  const linkSelector = ".explore-container > div > .link-overlay";
  const linkHanlder = await page.waitForSelector(linkSelector, {
    visible: true,
  });
  await linkHanlder?.hover();
  await linkHanlder?.click();
})();

```

**Comment by ddoonngg** [comment]
> ### Steps to reproduce
> **Tell us about your environment:**
> 
> * Puppeteer version: 7.1.0
> * Platform / OS version: macOS Big Sur 11.2
> * URLs (if applicable): https://www.starterstory.com/explore
> * Node.js version: 14.15.1
> 
> **What steps will reproduce the problem?**
> 
> This script clicks the first case study link on [Starter Story](https://www.starterstory.com/explore):
> 
> ```js
> const puppeteer = require("puppeteer");
> 
> (async () => {
>   const browser = await puppeteer.launch({
>     headless: false,
>     slowMo: 250,
>   });
>   const page = await browser.newPage();
>   await page.goto("https://www.starterstory.com/explore");
> 
>   await page.click(".explore-container > div > .link-overlay");
> })();
> ```
> 
> **What is the expected result?**
> 
> The first case study summary is clicked, which navigates the page to the case study.
> 
> **What happens instead?**
> 
> The first case study summary is clicked, but the page does not navigate and the clicked element shows the hover state.
> 
> ### Investigation
> The click occurs as expected when [Puppeteer's `click` implementation](https://github.com/puppeteer/puppeteer/blob/v7.1.0/src/common/Input.ts#L416) is changed to wait for each mouse function rather than using `Promise.all`:
> 
> ```ts
> await this.move(x, y);
> await this.down(options);
> await this.up(options);
> ```
> 
> instead of
> 
> ```ts
> await Promise.all([
>   this.move(x, y),
>   this.down(options),
>   this.up(options),
> ]);
> ```
> 
> Is there a reason why `Promise.all` is preferred over waiting for each step?
> 
> #### Steps to test implementation change
> 1. Clone puppeteer
> 2. Make code change as described above in `Input.ts`
> 3. Run `npm install && npm run build`
> 4. Run `npm link`
> 5. Go to repository with test code as given in issue
> 6. Run `npm link puppeteer`
> 7. Run `node index.js`

Hi, it seems that you forgot to hover the `div` to enable the link element before you click it.
Please try:
```javascript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 250,
  });
  const page = await browser.newPage();
  await page.goto("https://www.starterstory.com/explore");

  const linkSelector = ".explore-container > div > .link-overlay";
  const linkHanlder = await page.waitForSelector(linkSelector, {
    visible: true,
  });
  await linkHanlder?.hover();
  await linkHanlder?.click();
})();
```

**Comment by namuorg** [comment]
Thanks, that worked!

**Comment by namuorg** [comment]
Note: The `click` implementation was changed: https://github.com/puppeteer/puppeteer/pull/7097
