### ISSUE TITLE
Chrome fails to lauch on nodejs 14.15.4

### ISSUE THREAD

**Issue by boydkelly** [puppeteer/puppeteer#6902]
Seems to be the same as what is described for nodejs 14.0
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-is-downloaded-but-fails-to-launch-on-nodejs-14

But this is node 14.15.4   (Has there been regression or is there maybe some other problem?)  

Thank you.

### Steps to reproduce
install nodejs (14.15.4) on alpine image
(using asciidoctor/docker-asciidoctor)

* Puppeteer version: 7.1.0
* Platform / OS version:  Alpine linux edge
* URLs (if applicable):
* Node.js version: 14.15.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
image: asciidoctor/docker-asciidoctor
variables:
  OUTPUT: book
  DOC: ${OUTPUT}
  DIR: "_build"
  OUTPUT_FOLDER: "--destination-dir=${DIR}"
  STYLE: "-a stylesheet=./_resources/css/${OUTPUT}.css"
  TEMPLATE: "--template-require=./_resources/js/${OUTPUT}.js"
  HTML: "--backend=html5 -a max-width=55em"
pdf:
  stage: build
  script:
    - apk add --update npm
    - npm i -i
    - node --version
      #- npm i -i @asciidoctor/core asciidoctor-pdf puppeteer
    - npx asciidoctor-web-pdf ${STYLE} ${TEMPLATE} ${OUTPUT_FOLDER} --out-file=${DOC}.pdf ${DOC}.adoc

```
**What is the expected result?**
Chromium runs

**What happens instead?**
```
$ npm i -i
> puppeteer@5.5.0 install /builds/diarrayouss2/contes_africains/node_modules/asciidoctor-pdf/node_modules/puppeteer
> node install.js
Chromium (818858) downloaded to /builds/diarrayouss2/contes_africains/node_modules/asciidoctor-pdf/node_modules/puppeteer/.local-chromium/linux-818858
> puppeteer@7.1.0 install /builds/diarrayouss2/contes_africains/node_modules/puppeteer
> node install.js
Chromium (848005) downloaded to /builds/diarrayouss2/contes_africains/node_modules/puppeteer/.local-chromium/linux-848005
...
...
$ npx asciidoctor-web-pdf ${STYLE} ${TEMPLATE} ${OUTPUT_FOLDER} --out-file=${DOC}.pdf ${DOC}.adoc
Unable to generate the PDF - Error: Error: Failed to launch the browser process! spawn /builds/diarrayouss2/contes_africains/node_modules/asciidoctor-pdf/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome ENOENT
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md


```

**Comment by radoslavkarlik** [comment]
Also does not work on 14.16. Did you find a solution? It did not work for me because I was bundling puppeteer (previously worked with puppeteer-core) and I could not make it work even when using an explicit path for the chromium, either the default one or one I installed by myself. Without bundling it works.

**Comment by boydkelly** [comment]
Let me get back to this....   But just in the mean time.  Yes I did get it to work.  I believe it was switching the base container image from Alpine to Fedora minimal.  Was there something else?   Not sure at this point.
