### ISSUE TITLE
puppeteer-core types differ from puppeteer

### ISSUE THREAD

**Issue by Niek** [puppeteer/puppeteer#6904]
I'm maintaining the puppeteer add-on [ghost-cursor](https://github.com/Xetera/ghost-cursor ) and while upgrading the dependency to puppeteer@7 I noticed some strange differences between `puppeteer` and `puppeteer-core` types. For example the `Page` class is not interchangeable:
```bash
 error TS2345: Argument of type 'import("node_modules/puppeteer/lib/types").Page' is not assignable to parameter of type 'import("node_modules/puppeteer-core/lib/types").Page'.
  Types have separate declarations of a private property '_closed'.
```

Strange enough I can't find the differences in the generated `types.d.ts` files:
```bash
$ diff node_modules/puppeteer/lib/types.d.ts  node_modules/puppeteer-core/lib/types.d.ts | wc -l
       0
```

Any idea how this can be fixed? I would prefer to keep using puppeteer-core in the library while users most of the time use the regular puppeteer library.

**Comment by web-padawan** [comment]
I noticed this too, while trying to upgrade `puppeteer` version for [@web/test-runner-puppeteer](https://www.npmjs.com/package/@web/test-runner-puppeteer) package.

See https://github.com/modernweb-dev/web/pull/1295#pullrequestreview-596042949 for one example where it caused TS compilation errors.

**Comment by web-padawan** [comment]
@jackfranklin as you mentioned that you are going through the types https://github.com/puppeteer/puppeteer/issues/6979#issuecomment-821972179, could you please check this one too?

**Comment by JakeTompkins** [comment]
Is there any progress on this? I'd like to use chrome-aws-lambda which uses puppeteer-core with a custom fork of html-pdf-node-ts which uses puppeteer, but I can't reconcile the types of Browser between the two

**Comment by kldzj** [comment]
This is still an issue.

**Comment by luna-fire-dev** [comment]
This is because `import('puppeteer').Page` and `import('puppeteer-core').Page` are two different classes defined in two different js files from two different modules (so are the two types in two d.ts files). I am wondering why `puppeteer` doesn't import `puppeteer-core` as a dependency and re-use the classes from `puppeteer-core`.

**Comment by OrKoN** [comment]
@luna-fire-dev that'd be our plan but it's not how it was originally set up (when it was JS with no typescript in sight) so it will take some time to untangle it.

**Comment by rpodwika** [comment]
any updates on that?

**Comment by OrKoN** [comment]
That should work in the latest versions as puppeteer-core is a dependency for puppeteer now.

**Comment by andrewgarneau** [comment]
I'm using puppeteer & puppeteer-core version 24.12.0 and still running into this issue with the `Page` and `Browser` types specifically. Seems like both are creating their own definitions, so there are two types.d.ts files still.

`Argument of type 'import("{path}/$node_modules/.deno/puppeteer@24.12.0/$node_modules/puppeteer/lib/types").Page' is not assignable to parameter of type 'import("{path}/$node_modules/.deno/puppeteer-core@24.12.0/$node_modules/puppeteer-core/lib/types").Page'.`
