### ISSUE TITLE
How to set full width of viewport

### ISSUE THREAD

**Issue by lancejpollard** [puppeteer/puppeteer#6905]
I have the arg set `'--window-size=1920,1080'`, but I am seeing this [here](https://icis.corp.delaware.gov/ecorp/entitysearch/namesearch.aspx).

<img width="1436" alt="Screen Shot 2021-02-18 at 7 58 03 AM" src="https://user-images.githubusercontent.com/28718/108384023-2fd34800-71bf-11eb-9067-7af4a8608e28.png">

How to fix?

**Comment by vsemozhetbyt** [comment]
Try `puppeteer.launch({ defaultViewport: null });`
