### ISSUE TITLE
Support .omitBackground as option to .pdf()

### ISSUE THREAD

**Issue by rentalhost** [puppeteer/puppeteer#6906]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: m85 (remote) / m90 7.1.0 (local)
* Platform / OS version: browserless.io (remote) / Windows 10 x64 (local)
* Node.js version: 14.15.1 (local) and 15.9.0 (local)

**What steps will reproduce the problem?**

`.pdf()` cannot generate a transparent output to be used as watermark.

I have uploaded a .zip containing all tests with a valid output and an invalid output (via puppeteer).

My suggestion is allow `omitBackground` property (like `.screenshot()`) with the `.pdf()` method. So outputs could be used as watermark.

It was discussed here: https://github.com/puppeteer/puppeteer/issues/2545 and a workaround here https://github.com/puppeteer/puppeteer/issues/2545#issuecomment-397590569. It works, but is a hacky way and could stop works at anytime. So a definitive solution is better via `options`.

**What is the expected result?**

Generated PDF output be optionally transparent.

**What happens instead?**

PDF have a opaque background.

**Test**

1. Run `npm i puppeteer`
2. Download pdfbox to use `OverlayPDF` tool.
3. Following example doc, run `node example.js` to generate a PDF via puppeteer. You could set `background-color: transparent`, but it will not help.
4. Run `java -jar pdfbox.jar OverlayPDF puppeteer-output.pdf original.pdf output.pdf` (`original.pdf` is just any PDF document to be overlayed, the "original document" to be watermarked with the puppeteer PDF output)

The zip attached contains all files to test.

Expected output:

![output-valid](https://user-images.githubusercontent.com/421851/108387844-c2d6a700-71ec-11eb-9cf6-ffbb78f411cb.png)
[puppeteer-test.zip](https://github.com/puppeteer/puppeteer/files/6004295/puppeteer-test.zip)

**Comment by gavin310** [comment]
+1. Supporting transparent backgrounds should definitely be a feature without having to use hacks.

**Comment by d-buckner** [comment]
I've added this functionality in the PR above (forgot to update this issue before). It's included in [v9.0.0](https://pptr.dev/#?product=Puppeteer&version=v9.0.0&show=api-pagepdfoptions).

**Comment by gavin310** [comment]
> I've added this functionality in the PR above (forgot to update this issue before). It's included in [v9.0.0](https://pptr.dev/#?product=Puppeteer&version=v9.0.0&show=api-pagepdfoptions).

Woohoo!!!

**Comment by rentalhost** [comment]
I think that is was fixed a long time ago.
