### ISSUE TITLE
Interception and req.continue({url: ...}) on insecure content (and some secure content) no longer works as of Puppeteer v6.0.0

### ISSUE THREAD

**Issue by bluepeter** [puppeteer/puppeteer#6910]
To repro:

- Crawl http://www.mixedcontentexamples.com/Test/NonSecureImage
- Turn on interception
- Attempt to replace the image with some other random image on the web using `request.continue({ url: <some random jpg> })`
- It won't load. Catching network errors in Puppeteer reveals: `ERR_BLOCKED_BY_CLIENT`.

In summary, insecure images that are `continue`d with anything but themselves won't load.

These interceptions used to work reliably without issues on all Puppeteer versions <6, but, as of 6 (and in all subsequent releases), interception and replacing sources on non-SSL pages does not work.

**Comment by bluepeter** [comment]
Note that this issue is also occurring on some secure content too.

**Comment by bluepeter** [comment]
Bump.

**Comment by haresh-k** [comment]
I am facing the same issue with my redirect logic. Browser throws `ERR_BLOCKED_BY_CLIENT` for all of my browser requests(like CSS,js and img files). 

> Is there any update on this issue?

**Comment by haresh-k** [comment]
> I am facing the same issue with my redirect logic. Browser throws `ERR_BLOCKED_BY_CLIENT` for all of my browser requests(like CSS,js and img files).
> 
> > Is there any update on this issue?

I fixed this issue of mine. Passing the header as part of overridden request helped.

`const headers = request.headers();
request.continue({url : redirectUrl, headers : headers});`

**Comment by bluepeter** [comment]
Thanks @haresh-k we tried your idea but it did not work for us, unfortunately.
