### ISSUE TITLE
setRequestInterception disables caching. I need it not to do that.

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#6915]
The documentation says that `page.setRequestInterception` disables "page caching", without explaining what "page caching" is or why it is being disabled. Firstly, it looks like it actually means it disables all caching. Secondly, I need it not to do that. Why does it happen? There is no obvious connection between the two things. If I were to do:
```javascript
  await page.setRequestInterception(true)
  page.on('request', request => request.continue())
  await page._client.send('Network.setCacheDisabled', { cacheDisabled: false })
```
would anything bad happen, and if so, what?

**Comment by whalderman** [comment]
On why that happens: https://github.com/puppeteer/puppeteer/issues/2905#issuecomment-406128495
Also see #6996

**Comment by jribbens** [comment]
I think they're saying that the only problem is that if caching is not disabled, then requests served from the cache will not be intercepted? If so then it would be very much worth saying so in the documentation - I think for my application that wouldn't be a problem at all (if I didn't want to block or alter the request the first time it was issued, I'm unlikely to want to do so on subsequent occasions).

**Comment by Androbin** [comment]
#7060 was just merged, it solves the issue that originally led to the decision to disable the cache

**Comment by jribbens** [comment]
> #7060 was just merged, it solves the issue that originally led to the decision to disable the cache

Excellent, hopefully there will now be a patch to allow request interception with cache enabled :-)

**Comment by Androbin** [comment]
@jribbens See #6996, and #7217

**Comment by jribbens** [comment]
This issue was fixed in Puppeteer version 9.
