### ISSUE TITLE
puppeter does not work with travis-ci and node 15

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#6917]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.1.0
* Platform / OS version: Ubuntu 16.04.6
* URLs (if applicable):
* Node.js version: 15

**What steps will reproduce the problem?**

`.travis.yml`:
```yaml
language: node_js
node_js:
  - 14
  - 15
script:
  - npm run check-puppeteer
```
`package.json`:
```json
{
  "scripts": {
    "check-puppeteer": "node check-puppeteer"
  },
  "dependencies": {
    "puppeteer": "^7.1.0"
  }
}
```
`check-puppeteer.js`:
```javascript
'use strict'

const puppeteer = require('puppeteer')

;(async () => {
  const browser = await puppeteer.launch()
  const context = await browser.createIncognitoBrowserContext()
  const page = await context.newPage()
  await page.goto('http://example.com')
  await browser.close()
})()
```

**What is the expected result?**

Travis success on both node 14 and node 15.

**What happens instead?**

Travis success on node 14 but failure on node 15:

```
/home/travis/build/example/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:80
                    throw new Error(missingText);
                          ^
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
    at ChromeLauncher.launch (/home/travis/build/example/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:80:27)
    at async /home/travis/build/example/check-puppeteer.js:6:19
```

**Comment by DrewRidley** [comment]
Maybe add a `npm install` to the CI as a step before the actual execution? That might clear up the issue.

**Comment by jribbens** [comment]
> Maybe add a `npm install` to the CI as a step before the actual execution? That might clear up the issue.

Yeah I had tried that and it made no difference... however today, the problem seems to have disappeared. So I'll close this ticket on the assumption that it was a temporary problem at Travis' end.
