### ISSUE TITLE
Puppeteer Headless send captcha to another screen

### ISSUE THREAD

**Issue by swassapparel1** [puppeteer/puppeteer#6919]
Hi everyone! How can I send the captcha to another screen on headless mode? Attached is a sample screen that I’m referring. Thanks!

https://m.youtube.com/watch?v=SmOfCVkzyBM%2F&t=3m04s&feature=youtu.be

![Uploading 8AE59B2D-8CF3-4BA2-8721-BAFC2E4FE25B.png…]()

**Comment by DrewRidley** [comment]
I highly doubt this is anything that is in the scope of puppeteer. I am fairly certain the video you linked uses an embedded web browser to render that window. and I suspect that it isnt puppeteer.

**Comment by swassapparel1** [comment]
Any idea on how can I achieve this?

**Comment by DrewRidley** [comment]
Not really sure this is in the scope of puppeteer and this issue might take attention away from actual issues with puppeteer itself, and there are plenty of resources out there that show you how to use chromium embedded framework (CEF). Its highly discouraged by the captcha providers to do this, and likely is against their TOS, so I do not feel comfortable providing an answer to your question.
