### ISSUE TITLE
Could not find browser on Elastic Beanstalk AWS

### ISSUE THREAD

**Issue by nvquangth** [puppeteer/puppeteer#6920]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.1
* Platform / OS version: Linux on Elastic Beanstalk AWS
* URLs (if applicable):
* Node.js version: 12.16.1

**What steps will reproduce the problem?**
Try the demo code to launch puppeteer

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
```

**What is the expected result?**
It is able to start in my local. When I deployed in my Elastic Beanstalk AWS I am getting this error.

**What happens instead?**
It throws error

```
Error: Could not find browser revision 848005. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.

at ChromeLauncher.launch (/var/app/current/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:80:27)
```

**Comment by amarinediary** [comment]
@nvquangth Did you manage to fix that issue on your end? How did you do it if you don't mind sharing?
