### ISSUE TITLE
Failed to launch the browser process

### ISSUE THREAD

**Issue by nvquangth** [puppeteer/puppeteer#6922]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.1.0
* Platform / OS version: Linux on Elastic Beanstalk AWS
* URLs (if applicable):
* Node.js version: 12.16.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
```

**What is the expected result?**
It is able to start in my local. When I deployed in my Elastic Beanstalk AWS I am getting this error.

**What happens instead?**
```
Error: Failed to launch the browser process!

/var/app/current/node_modules/puppeteer/.local-chromium/linux-848005./chrome-linux/chrome: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

at onClose (/var/app/current/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)

at Interface.<anonymous> (/var/app/current/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)

at Interface.emit (events.js:323:22)

at Interface.close (readline.js:409:8)

at Socket.onend (readline.js:187:10)

at Socket.emit (events.js:323:22)

at endReadableNT (_stream_readable.js:1204:12)

at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by simonhammes** [comment]
@nvquangth Can you maybe share how you solved your issue? That might help other people. Thank you.

**Comment by nvquangth** [comment]
Hi @simonhammes,
my issue fixed by install some missing packages: libxkbcommon, ...
I follow by article in [medium](https://medium.com/mockingbot/run-puppeteer-chrome-headless-on-ec2-amazon-linux-ami-6c9c6a17bee6#)

The steps I did:
1. Connect to my EC2 instance on Amazon Linux 2 AMI

2. Access to your project: cd your_project_path

2. Install puppeteer: npm install puppeteer

2.1 If you can not install puppeteer with log: permission denied, let's view this [issue](https://github.com/puppeteer/puppeteer/issues/367#issuecomment-499315095): 
(I used: npm install -g puppeteer --unsafe-perm=true)

3. cd node_modules/puppeteer/.local-chromium/linux-508693/chrome-linux (508693 is version I used, depend on you)

4. Check some missing packages: ldd chrome | grep not

Ex: I missing packages: libxkbcommon, libpng12, libwayland-cursor, libasound...

After, I install those  packages using RPM. I find its in https://pkgs.org/.

Ex: rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/libwayland-cursor-1.15.0-1.el7.x86_64.rpm

5. After of all installed, I check again: ldd chrome | grep not. And I no see missing packages.

6. Run code again, I resolved this issue.

You can try it. Good luck

**Comment by amarinediary** [comment]
This is related to #5379. Here is my answer after struggling for 12 hours, https://github.com/puppeteer/puppeteer/issues/5379#issuecomment-887123260.

**Comment by samarth-shah-einfochips** [comment]
I am testing my lambda function getting such error 
{
  "errorType": "Error",
  "errorMessage": "Failed to launch the browser process!\nprctl(PR_SET_NO_NEW_PRIVS) failed\n[1130/053424.372615:FATAL:zygote_communication_linux.cc(269)] Cannot communicate with zygote\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n",
  "trace": [
    "Error: Failed to launch the browser process!",
    "prctl(PR_SET_NO_NEW_PRIVS) failed",
    "[1130/053424.372615:FATAL:zygote_communication_linux.cc(269)] Cannot communicate with zygote",
    "",
    "",
    "TROUBLESHOOTING: https://pptr.dev/troubleshooting",
    "",
    "    at Interface.onClose (file:///opt/node_modules/@puppeteer/browsers/lib/esm/launch.js:262:24)",
    "    at Interface.emit (node:events:529:35)",
    "    at Interface.close (node:internal/readline/interface:534:10)",
    "    at Socket.onend (node:internal/readline/interface:260:10)",
    "    at Socket.emit (node:events:529:35)",
    "    at endReadableNT (node:internal/streams/readable:1368:12)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
  ]
}

any idea ?

i am using @sparticuz/chromium

**Comment by rooselle** [comment]
@nvquangth thanks !! Your solution worked for me. :pray:

**Comment by VishalPathriya29** [comment]
Connect EC2 to ssh than run following command:-

cd home

cd webapp

cd .cache

cd puppeteer

cd chrome

cd linux-123.0.6312.58

cd chrome-linux64

after that run command:- ldd chrome | grep not
//this command check which dependencies are not installed

after than install following dependencies:- sudo yum install -y alsa-lib.x86_64 atk.x86_64 cups-libs.x86_64 gtk3.x86_64 ipa-gothic-fonts libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXrandr.x86_64 libXScrnSaver.x86_64 libXtst.x86_64 pango.x86_64 xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-fonts-cyrillic xorg-x11-fonts-misc xorg-x11-fonts-Type1 xorg-x11-utils
