### ISSUE TITLE
Failed to build a path to Chromium executable on Windows 10

### ISSUE THREAD

**Issue by VagrantAI-c** [puppeteer/puppeteer#6926]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.1.0
* Platform / OS version: Windows 10 Pro version 2004 build 19041.789
* URLs (if applicable): any url
* Node.js version: 14.15.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `npm i puppeteer`
2. run `await puppeteer.launch();`

**What is the expected result?**
Puppeteer to be launched without errors and local Chromium is used (the one installed to node_modules)

**What happens instead?**
Chromium r848005 was succesfully installed to `node_modules/puppeteer/.local-chromium`, and I can validate it physically on FS. However, launching a program throws next error:
```
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
    at ChromeLauncher.launch (%%absolute path to project%%\dist\server.js:233643:27)
```
I tried to debug a little and found that next function seems to be the source of the problem: https://github.com/puppeteer/puppeteer/blob/main/src/node/BrowserFetcher.ts#L417
It returns `'%%absolute path to project%%\\.local-chromium\\win64-848005'` but should return `'%%absolute path to project%%\\node_modules\\puppeteer\\.local-chromium\\win64-848005'` instead

**Comment by VagrantAI-c** [comment]
Still reproducible on puppeteer@8.0.0 and node 15.14.0,
```
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).
    at ChromeLauncher.launch
```

**Comment by sr258** [comment]
I can confirm that this happens with CircleCI's cimg/node:15.14-browsers docker image and puppeteer@8.0.0.

**Comment by VagrantAI-c** [comment]
The funny thing is, that I can't build minimal repro (yet) because it works fine in a separate project. Maybe it's something environmental. Still investigating...

**Comment by sr258** [comment]
The problem seems to have disappeared with Puppeteer 9.1.0 - for me at least.

**Comment by Schahen** [comment]
For me it haven't with puppeeteer-core@9.1.1 I can still see this exactly problem.

**Comment by VagrantAI-c** [comment]
Can validate that on `puppeteer@10.1.0` the error persists due to https://github.com/puppeteer/puppeteer/blob/main/src/node/BrowserFetcher.ts#L199 resolves to `/%project_root%/.local-chromium` , however the real path to folder should be `/%project_root%/node_modules/puppeteer/.local-chromium`

BTW, found out that this is due to webpack bundling or Typescript compilation, since launching
```javascript
const puppeteer = require('puppeteer');
async function launch() { await puppeteer.launch(); }
launch().then(() => console.log('success')).catch((e) => console.error(e));
```
completes successfully, but the same code in typescript and compilation to dist folder fails

**Comment by VagrantAI-c** [comment]
I resolved the problem by adding 
```
node: {
  __dirname: true,
},
```
to webpack config. Because that webpack bundles puppeteer to main bundle, all paths should be mocked with this option. Reference: https://webpack.js.org/configuration/node/

Please reopen with a new issue if someone still has this problem and it doesn't relate to webpack configuration
