### ISSUE TITLE
For firefox the events "targetchanged", "targetcreated" aren't firing

### ISSUE THREAD

**Issue by luiso1979** [puppeteer/puppeteer#6932]
### Steps to reproduce

* Puppeteer version: 7.1.0 (w/ Firefox Nightly 88.0a1)
* Platform / OS version: Macos 11.2.1
* URLs (if applicable): 
* Node.js version: 12.15

**What steps will reproduce the problem?**

    const browser = await launch({product: "firefox", headless: false});

    browser.on("targetchanged", console.log);
    browser.on("targetcreated", console.log);

    const page = await browser.newPage();
    await page.goto('https://example.com');
    await browser.close();

**What is the expected result?**

It should print to console the fired event objects.

**What happens instead?**

It does nothing

**Comment by whimboo** [comment]
It won't work for `targetchanged` because the [Target.targetInfoChanged](https://bugzilla.mozilla.org/show_bug.cgi?id=1610855) API from CDP hasn't been implemented yet. But the event for `targetcreated` should be received.

Mind enabling `dumpio` when launching Firefox and setting the Firefox preference `remote.log.level` to `Trace`? That would give us more details in the logs. Please attach them here. Thanks.

**Comment by luiso1979** [comment]
@whimboo sorry to disturb you, but trying to workaround problem, I tried to get all the pages every X milliseconds and for each page to execute: `await page.evaluate(() => document.location.href)`, everything works well for the pages opened directly from puppeteer (or derived from it) but for the new tabs opened using the + in firefox (headless: false) the `evaluate` never returns. 

Do you know if the tabs opened by hand (using +) are not controllable by puppeteer and if something can be done to:
- prevent opening new tabs that way OR
- allow puppeteer to somehow control those tabs

Thanks in advance and sorry for the trouble,

Regards
Luis

**Comment by whimboo** [comment]
Sorry but we do not have the bandwidth to actually fix cases when a user interacts with the Firefox UI while Puppeteer is running. As workaround I would suggest that you run in headless mode so that no interaction can take place.
