### ISSUE TITLE
localStorage is not defined

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#6938]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.11.0-next.1547527073587
* Platform / OS version: Windows 10
* Node.js version: 14.15.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

`const config = require("./config.json");

const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto("https://discord.com/app");
  await page.evaluate(() => {
    localStorage.clear();
  });
  await page.goto("https://discord.com/app");
})();`

**What is the expected result?**
Localstorage should be cleared.

**What happens instead?**
(node:9372) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: localStorage is not defined
    at __puppeteer_evaluation_script__:2:5

**Comment by vsemozhetbyt** [comment]
If you enter `localStorage` in the browser console while on https://discord.com/app you get the same error. It seems one of the site scripts deletes the `window.localStorage` property.

**Comment by ghost** [comment]
> If you enter `localStorage` in the browser console while on https://discord.com/app you get the same error. It seems one of the site scripts deletes the `window.localStorage` property.

Thank you for response! Discord actually deletes `window.localStorage`. Is any way to bypass it in puppeteer?

**Comment by vsemozhetbyt** [comment]
Try [`page.evaluateOnNewDocument()`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevaluateonnewdocumentpagefunction-args):

> The function is invoked after the document was created but before any of its scripts were run. This is useful to amend the JavaScript environment...

Maybe you will manage to save the `window.localStorage` reference in some other global variable and then use this variable instead when the original `window.localStorage` is deleted.

**Comment by mattys0229** [comment]
I'm trying this on the same site and it only works when you change the Javascript context from "top" to "__puppeteer_utility_world__" but i have no idea how to change the contexts in Puppeteer

**Comment by mattys0229** [comment]
if you still didn't resolve your issue
https://gist.github.com/Mathspy/55614eb2e9b8fc86c1dc814e50470ab1
can help you if you want to read from localStorage
