### ISSUE TITLE
Error while loading libatk-bridge-2.0.so.0 on a shared hosting platform

### ISSUE THREAD

**Issue by Kathleen2911** [puppeteer/puppeteer#6941]
I am trying to deploy my Node.js app, which is using Puppeteer, on a shared hosting platform (Linux Server), but I got the following error:
Error: Failed to launch the browser process!\n/var/app/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: **error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file:** No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"

I know I could fix it by installing the missing libatk-bridge dependency, but the problem is, I don't have the rights to do so on the shared hosting platform.

Is there any workaround to solve the issue? Or is there a way to embed the library as a static library instead of a shared library?

**Comment by Pqoh** [comment]
Any solution?

**Comment by shammahk** [comment]
Any solution yet? facing similar issue
