### ISSUE TITLE
version missing

### ISSUE THREAD

**Issue by bboydflo** [puppeteer/puppeteer#6943]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Mac OS
* URLs (if applicable): -
* Node.js version: v12.21.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. open https://github.com/puppeteer/puppeteer/blob/main/versions.js
2. inspect map

**What is the expected result?**
1. version 8.0.0 included in the map

**What happens instead?**
1. version 8.0.0 missing

**Comment by OrKoN** [comment]
The map includes only versions when the Chromium binary was updated and not all Puppeteer versions. A clarification to the docs added here https://github.com/puppeteer/puppeteer/pull/8016
