### ISSUE TITLE
Cleanup errors in browser.close hang indefinitely

### ISSUE THREAD

**Issue by SnirBroshi** [puppeteer/puppeteer#6946]
In `browser.close()` puppeteer tries to rimraf the user-data-dir. This often fails on Windows due to EPERM (#298).
If `rimraf` fails here, puppeteer logs the error to the console, and then the `browser.close()` promise is left hanging forever, not resolved or rejected:

https://github.com/puppeteer/puppeteer/blob/0c26301bee0d07f314831fc8f1f4e5a1d31e5e9d/src/node/BrowserRunner.ts#L101-L103

the `catch` callback is the problem, it should resolve or reject the promise.

Also it seems like node somehow detects that there's no code left to run, since we're waiting for a promise that can't resolve, and kills the process, so any further code is never ran.

(the repro is irrelevant here since I'm talking about any potential error that `rimraf` can throw, but #298 is one such repro)

* Puppeteer version: 8.0.0
* Platform / OS version: Windows 10 64bit
* Node.js version: 12.18.1

**Comment by alamothe** [comment]
It's a pretty big problem that `browser.close` just hangs. If there is an important error, it should throw. If it's unimportant, it should ignore it (since it's closing). 

How big of an issue is that these files do not get removed?

**Comment by alamothe** [comment]
Just patched `puppeteer` and can confirm it fixes the issue. I just fulfilled the promise in the `catch` block

**Comment by tx46** [comment]
This is still happening to me. I'm trying to work around it but after a few shots with Puppeteer over the course of a few days, I have to reboot the system because I either have to a) block forever in my code because Puppeteer will never exit (at least according to the promise) or b) leave dangling instances of Puppeteer running.
