### ISSUE TITLE
Multiple incognito context crashes browser on Twitch

### ISSUE THREAD

**Issue by voed** [puppeteer/puppeteer#6948]
* Puppeteer version: 8.0.0
* Platform / OS version: Windows 10 20H2
* URLs (if applicable): 
* Node.js version: 13.8.0

**What steps will reproduce the problem?**

Running multiple incognito instances of twitch player crashes the browser. Not sure if that's puppeteer problem or chromium bug, it caused by widevine i guess, but it crashes even on pure chromium without widevine plugin. 
```
const Puppeteer = require('puppeteer');

(async function() {
    // run chromium
    const browser = await Puppeteer.launch({
        headless: false
    });
    
    // parallel navigate
    await Promise.all([
        goPage(browser),
        goPage(browser),
        goPage(browser),
    ]);

})();

async function goPage(browser) {
    const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();

    await page.goto('https://twitch.tv');
}
```

**Comment by sergiojgm** [comment]
Hope this helps... I had the same problem with 2 or 3 pages. On my case the pages had multiple embed videos that was crashing the chromium, probably due lack of video memory or related with GPU. Adding disable gpu didn't help. Adding on request then abort video worked for me... Probably something on the delay clean-up on incognito mode
