### ISSUE TITLE
Blank space is being added after a div when printing to PDF.

### ISSUE THREAD

**Issue by meghamukim** [puppeteer/puppeteer#6951]
I am trying to print the question heading div and it's answer table in the same page in PDF. If the table has a lot of content I would expect it to start on the same page as the question and then continue on to the next page. But the table itself starts on a new page leaving the 2-line question heading on one full page.

I tried using different height/width combinations for viewports for the browser as well. It shows up fine on the Chrome but Printing is a different story all together! I have tried using different combinations of CSS to overcome this but in vain. Below is what are the options I tried at different times:

```
.sm-questionview-no-page-break-block { //question heading div
    border: 1px solid blue;
    break-after: avoid;
}

.ta-export-container { // table content div
    margin: 20px 0 0 0;
    border: 1px solid red;
    break-before: avoid;
}

@media print {
    .ta-export-container {
        break-before: avoid;
        /* prevent blank page at end */
        table: { break-before: avoid; }
        html, body {
            height: 100%;
        }
    }
    .sm-questionview-no-page-break-block {
        break-after: avoid;
    }
}
```

### Steps to reproduce

**Tell us about your environment:**

* Platform / OS version: Mac OS Catalina
* Node.js version: 12.16.0

**What steps will reproduce the problem?**

```
// code that launches the browser:
return await puppeteer.launch({
      executablePath: '/usr/bin/chromium-browser',
      ignoreHTTPSErrors: true,
      args: [
          '--no-sandbox',
          '--ignore-certificate-errors',
          '--ignore-ssl-errors',
          '--single-process'
      ],
      defaultViewport: {
        'width': 1000,
        'height': 1
      }
    });

// PDF printing. Dimensions are usually A4/A3 
class PDFExport extends Export {
  constructor(args) {
    super();
    this.requiredArgs = [
      'url',
      'cookie',
      'authorization',
      'filename',
      'zoomFactor',
      'headerHeight',
      'footerHeight',
      'marginTop',
      'marginBottom',
      'orientation',
      'dimension',
      'header',
      'footer',
      'timeout'
    ];
    this.settings = this._getSettings(args);
  }

  async print(page) {
    const settings = this.settings;
    await super.print(page)
    await page.pdf({
      path: settings.filename,
      format: settings.dimension,
      margin: {
        top: settings.marginTop,
        bottom: settings.marginBottom,
        left: '10mm',
        right: '10mm'
      },
      scale: settings.zoomFactor,
      landscape: settings.orientation.toLowerCase() === 'landscape',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: settings.header,
      footerTemplate: settings.footer
    });
  }
}
```

**What is the expected result?**
This was prior to using Puppeteer. The div & table starts on the same page.
![Expected outcome](https://user-images.githubusercontent.com/10327789/109864003-51591880-7c30-11eb-866c-3a24e82ed426.png)

**What happens instead?**
The div stays on one page and table starts on another page. If more responses are added then the table continues to flow into another page (which is expected).
![Blank space](https://user-images.githubusercontent.com/10327789/109863997-4f8f5500-7c30-11eb-9179-f78b8597b681.png)
![Table-newpage](https://user-images.githubusercontent.com/10327789/109864010-5322dc00-7c30-11eb-93bf-964a315d5259.png)

**Comment by dpmott** [comment]
Try using `break-inside: avoid;` instead of `break-after` or `break-before` directives.

**Comment by ubersant** [comment]
Hi @dpmott 

Can you please help me how this can be resolved ? Helps a lot 

![fade](https://user-images.githubusercontent.com/11734961/126738689-fa1291e0-aad3-4b71-bc9f-2ca5eb290d67.PNG)

This black line appears whenever there's table is huge and goes over to next page as well.

**Comment by ubersant** [comment]
Update 

@dpmott 

Thanks for your previous comment 

fade is gone but the closing is also gone at the end of the page for the row. Blue line is showing what's missing 

![fade2](https://user-images.githubusercontent.com/11734961/126739230-8047e335-e16f-4f99-9eca-fc4dcd5844d2.PNG)

Also, the header which used to repeat in the next page is also gone.
