### ISSUE TITLE
page.evaluate* functions typings don't accept readonly arrays

### ISSUE THREAD

**Issue by n10v** [puppeteer/puppeteer#6953]
**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: macOS 11.2
* Node.js version: 12.18.1
* TypeScript version: 3.8.3

**What steps will reproduce the problem?**

```
const browser = await puppeteer.launch()
const page = await browser.newPage()

const readonlyArray: readonly string[] = ['a']
page.evaluate(() => {}, readonlyArray)
```

**What is the expected result?**
No error

**What happens instead?**
Error at the last line:
```
Argument of type 'readonly string[]' is not assignable to parameter of type 'SerializableOrJSHandle'.
  Type 'readonly string[]' is not assignable to type 'JSONObject'.
    Index signature is missing in type 'readonly string[]'.ts(2345)
```
<img width="974" alt="Screen Shot 2021-03-04 at 13 35 53" src="https://user-images.githubusercontent.com/13235519/109964906-8cba1c80-7cee-11eb-9cd4-e3102e122f95.png">

**Comment by ddoonngg** [comment]
Agree with you. The readonly array should also treated as an `Serializable` from my understanding.
We have to use `as`
```typescript
page.evaluate(() => {}, readonlyArray as SerializableOrJSHandle);
```

**Comment by n10v** [comment]
@ddoonngg thanks for your tip, but it doesn't work for me. I still get the same error. I do following:
`(readonlyArray as unknown) as string[]`

**Comment by n10v** [comment]
I would like to make a PR for it.
