### ISSUE TITLE
PUPPETEER_EXECUTABLE_PATH ignored on arm64 machines

### ISSUE THREAD

**Issue by marvinhagemeister** [puppeteer/puppeteer#6957]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: MacOS Big Sur (Macbook Air M1)
* URLs (if applicable): -
* Node.js version: 15.11.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

1. `brew install chromium`
2. `npm install puppeteer`
3. Save the above script as `index.js`
4. `PUPPETEER_EXECUTABLE_PATH="/opt/homebrew/bin/chromium" node index.js`

**What is the expected result?**

It should try to use `/opt/homebrew/bin/chromium` as the path to the browser executable.

**What happens instead?**

Puppeteer always overwrites the executable path specified via the environment variable internally and falls back to `/usr/bin/chromium-browser`. Setting `executablePath` explicitly in launch options works though:

```js
// works, only setting via env var doesn't work
await puppeteer.launch({ executablePath: "/opt/homebrew/bin/chromium" });
```

**Comment by talisto** [comment]
In my case setting `executablePath` in the `launch()` method didn't seem to have any effect either.  I spent hours trying to fix this in my docker container, and eventually decided to just created a symbolic link from my actual chromium binary to `/usr/bin/chromium-browser`.

**Comment by marvinhagemeister** [comment]
ping (to avoid stale bot)

**Comment by Saibamen** [comment]
This same on PuppeteerSharp 8.0.0 and Google Chrome 100.0.4896.127-1

**Comment by ntraut** [comment]
Updating puppeteer to version 19.4.1 solved the issue for me.

**Comment by Saibamen** [comment]
> Updating puppeteer to version 19.4.1 solved the issue for me.

From which version?

**Comment by ntraut** [comment]
> > Updating puppeteer to version 19.4.1 solved the issue for me.
> 
> From which version?

I had the bug in puppeteer 8.

**Comment by harshjv** [comment]
Can confirm, when using arm64, the bug still exists on `23.3.0`.
