### ISSUE TITLE
Getting computed styles

### ISSUE THREAD

**Issue by kaushiksundar** [puppeteer/puppeteer#696]
Is there a way to get the computed styles for an element?

**Use case:**
Testing UI consistencies - If I am able to get the computed styles for all the buttons in the page or application and do a comparison, I can say whether the buttons are consistent across the application.

**Comment by odeds** [comment]
you can query the dom and use getComputedStyle inside a page.evaluate
you can apply something similar for querySelectorAll

```
const button = await page.evaluate(() => {
            const btn = document.querySelector('.button');
            return getComputedStyle(btn);
});
```

**Comment by JoelEinbinder** [comment]
So unfortunately there is a bug with `page.evaluate` where you don't get all properties of some native objects. For now, you can hack around it like this:
```js
const button = await page.evaluate(() => {
            const btn = document.querySelector('.button');
            return JSON.parse(JSON.stringify(getComputedStyle(btn)));
});
```

**Comment by tommedema** [comment]
What I would like to know is if there is a way to get the "active styles", rather than the final "computed styles". For example taking this case:

<img width="544" alt="screen shot 2018-02-28 at 13 49 47" src="https://user-images.githubusercontent.com/331833/36788474-4b0780e8-1c8e-11e8-943d-82b019471a2f.png">

The `height` and `width` are greyed out because they are computed, whereas the `word-wrap` style is not greyed out because it is "active". I.e.  I would like to get a list of all combined CSS properties that are active for a given component, excluding properties like `height` and `width` because these are dynamically computed but not actively set. Does this make sense?

**Comment by aslushnikov** [comment]
@tommedema you can achieve this with [CSS domain](https://vanilla.aslushnikov.com/#CSS) with some post-processing, similarly to what [devtools does](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/sdk/CSSMatchedStyles.js#L591-L632)

**Comment by rjhilgefort** [comment]
I'm just curious why this was closed? @JoelEinbinder's solution worked, but it was a bit of a head scratcher and still seems like an issue.

**Comment by ssivanatarajan** [comment]
@tommedema  Are you able to get the active styles?

**Comment by tommedema** [comment]
@ssivanatarajan no, I wasn't. I gave up ;)

**Comment by giuseppeg** [comment]
fwiw it is possible to simulate `:active` this way

```js
async function active(page, selector, doSomething) {
  const el = await page.$(selector)
  const { top, left } = await page.evaluate(el => {
    el.scrollIntoViewIfNeeded()
    const { top, left } = el.getBoundingClientRect()
    return { top, left }
  }, el)
  await page.mouse.move(top + 1, left + 1)
  await page.mouse.down()
  await doSomething()
  await page.mouse.up()
}
```

`doSomething` is a function of yours where you for example get the computed styles. Hope this helps.

**Comment by gieoon** [comment]
> @tommedema you can achieve this with [CSS domain](https://vanilla.aslushnikov.com/#CSS) with some post-processing, similarly to what [devtools does](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/sdk/CSSMatchedStyles.js#L591-L632)

Now moved [here](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/core/sdk/CSSMatchedStyles.ts)
