### ISSUE TITLE
Save Screenshots as AVIF images

### ISSUE THREAD

**Issue by Lonniebiz** [puppeteer/puppeteer#6963]
According to the 10.4.0 [documentation](https://github.com/puppeteer/puppeteer/blob/v10.4.0/docs/api.md#pagescreenshotoptions), a `page` instance has a `screenshot` method that accepts an object where you can set the `type` property (which is the image format) to `png`, `jpeg`, or `webp`.

These days, instead of `png`, `jpeg`, or `webp`, I try to use the `avif` image format as much as possible:

- [jakearchibald.com/2020/avif-has-landed/](https://jakearchibald.com/2020/avif-has-landed/)
- [en.wikipedia.org/wiki/AV1#AV1_Image_File_Format_(AVIF)](https://en.wikipedia.org/wiki/AV1#AV1_Image_File_Format_(AVIF))
- [https://caniuse.com/avif](https://caniuse.com/avif)
- [Convert images to AVIF using Squoosh](https://squoosh.app/)

Please add support for saving screenshots in the `avif` image format. This would also require making the `quality` option-property applicable to `avif` (in addition to its current support for only `jpeg` and `webp`), allowing you to set the quality of a `avif` screenshot.

**Comment by tomByrer** [comment]
I was about to suggest this, but AVIF lossless files are huge, often bigger than PNG.  JpegXL might be better, or even more aggressive compression of PNG (eg OxiPNG)

**Comment by tomByrer** [comment]
AVIF.to may be using 4:4:2 color ratio which will make minor color shifts.

Yes, lossy AVIF seems to have the smallest file size of them all, but seems at a cost of [color shifting](https://github.com/GoogleChromeLabs/squoosh/issues/960).  I'm trying to isolate the problem.  Ironically using puppeteer to automate screenshotting how AVIFs look in Chrome (saving as PNG & then color-diff).

**Comment by Lonniebiz** [comment]
@tomByrer I've read some about color shifting in these Firefox Bugs:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1682995
- https://bugzilla.mozilla.org/show_bug.cgi?id=1443863

I thought it was a Firefox issue.

**Comment by simison** [comment]
Related, saving files in WebP format: https://github.com/puppeteer/puppeteer/issues/5348#issuecomment-629238838

**Comment by tomByrer** [comment]
@Lonniebiz In [my pixel diffs](https://github.com/test-images/avif-results/blob/main/202105/diff/squoosh/20210603T043648663Z.report.json), Firefox is worse at color-shifting vs Canary.

@simison Good suggestion!  But I wonder if AVIF or JpegXL are better compression for the CPU?

**Comment by Lonniebiz** [comment]
`avif` lossy images produce the smallest file size I've seen at a given quality. I'm frankly amazed by the perceived **quality to file size ratio**. See for yourself using [squoosh](https://squoosh.app/).

I use puppeteer to cache thousands of screenshots. Once puppeteer adds support for `avif`, those screenshots are going to (collectively) take up much less space, and they're going to transfer from server to client in a fraction of the time.

Outside of puppeteer, I had this one `jpeg` image that I was using as a background image of a web application. That `jpg` was **631.2 KiB**, which was by far the largest resource served within the app.

In the past, I had tried other image formats to reduce the image's size. Yet, each format I used (to reduce the size) produced a quality that wasn't good enough.

Eventually, I was able to produce a quality I was satisfied with using `webp`, but the file size was only reduced to **276.6 KiB**.

Now, with `avif`, I'm able to produce an acceptable quality at only **63.8 KiB**, and the app has never loaded more instantly. Amazing!

**Comment by jschfflr** [comment]
Feel free to open a feature request on https://crbug.com to add avif support for the screenshot command on the Chromium side :)

**Comment by Lonniebiz** [comment]
I did, but it isn't pretty:
https://bugs.chromium.org/p/chromium/issues/detail?id=1254336
@jschfflr 

I wish I could edit it.

**Comment by Lightning00Blade** [comment]
Closing this as the Chromium bug clearly states that this will not be supported.
