### ISSUE TITLE
Invalid Slack Link in README

### ISSUE THREAD

**Issue by akashgp09** [puppeteer/puppeteer#6967]
### Steps to reproduce

Click the "slack channel" link at the bottom of the readme

**What is the expected result?**

You get invited to the Slack channel.

**What happens instead?**

<img width="702" alt="Screenshot 2021-03-10 033127" src="https://user-images.githubusercontent.com/55311336/110544317-8cd47500-8151-11eb-8628-a4172c8b31d5.png">

**Comment by akashgp09** [comment]
Can anyone provide me the updated link so that i can Update the README with the valid link

**Comment by plocket** [comment]
I'd appreciate an updated link as well.

**Comment by plocket** [comment]
I think @snitin315 removed it from github March 15 in 56f17fe4819b5081ee17aad3a4e73a49ebaa2a5d. Is there no longer a Slack channel? If not, is there another place for chat?

**Comment by OlegBabakov** [comment]
https://github.com/puppeteer/puppeteer/issues/5535#issuecomment-917695699
https://discord.gg/tbY6tYTPUv
