### ISSUE TITLE
Cannot login into Gmail "The browser is not secure"

### ISSUE THREAD

**Issue by 64chevy** [puppeteer/puppeteer#6973]
Apparently we cannot login into Gmail with Puppeteer? There are other websites like Google who can detect if we are using a third party app to control Chrome i-e TikTok. I tried Playwright webkit and everything works fine but with Puppeteer it gives this error when logging into Gmail:

![puppe](https://user-images.githubusercontent.com/7713710/110756560-3019ad00-826c-11eb-9537-33ffb08d3c60.png)

I have been working on a project for so long and this thing has made me go mad. I switched from Playwright to Puppeteer because Playwright do not work on CentOS 7. Would be great if someone can help.

**Comment by 64chevy** [comment]
Figured out it.

**Comment by 675076143** [comment]
> Figured out it.

how? any help would be appreciated.
