### ISSUE TITLE
Centos 7 - Unable to launch chromium

### ISSUE THREAD

**Issue by abhidev54** [puppeteer/puppeteer#6978]
I am getting below error in centos 7 and i tried many options on internet but nothing is working

Starting browser
Unable to launch browser mode in sandbox mode. Lauching Chrome without sandbox.
(node:7975) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
../../base/allocator/partition_allocator/partition_address_space.cc(41) Check failed: reserved_base_address_

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/xyz/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/home/xyz/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

** I tried every option on issue https://github.com/puppeteer/puppeteer/issues/2857 but nothing is working for me

**Comment by allandiego** [comment]
I got the same error, chromium was installed in node_modules/puppeteer/.local-chromium/linux-856583
and I have installed all Dependencies
```sh
yum install alsa-lib.x86_64 atk.x86_64 cups-libs.x86_64 gtk3.x86_64 ipa-gothic-fonts libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXrandr.x86_64 libXScrnSaver.x86_64 libXtst.x86_64 pango.x86_64 xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-fonts-cyrillic  xorg-x11-fonts-misc org-x11-fonts-Type1 xorg-x11-utils
```

I have tried to manually download and extract the current used version r856583 and got same behavior

https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F856583%2Fchrome-linux.zip?alt=media 

Tried the previous version too used in puppeteer v7 chromium r848005
https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F848005%2Fchrome-linux.zip?alt=media 

This version hangs in the launch process 
```ts 
await puppeteer.launch()
```
 without erros and dont execute the rest of the script

**Comment by michaellwatson** [comment]
Im also getting the same error
```

/home/public_html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
../../base/allocator/partition_allocator/partition_address_space.cc(41) Check failed: reserved_base_address_


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/public_html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/home/public_html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
```

The command runs fine on my root account, but not any of the sub accounts, any help would be appreciated as it worked before the update

**Comment by michaellwatson** [comment]
This fixed it for me.

1. Make sure all dependencies in package.json are up to date
2. Install all the dependencies here https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md (one by one so none are missed)
3. https://developers.google.com/web/tools/puppeteer/troubleshooting#setting_up_chrome_linux_sandbox including adding the path to bashrc
4. Restart

For me it was already working on root, but not sub accounts, after following the instructions above, it works on sub accounts

**Comment by nyxomniac** [comment]
I am getting the same issue as well, whether  I try to launch chromium directly or via nodejs and puppeteer. I tried with sandbox disabled as well.

../../base/allocator/partition_allocator/partition_address_space.cc(41) Check failed: reserved_base_address_

**Comment by JKelly423** [comment]
Ran into same issue as well.
`
(node:1536463) UnhandledPromiseRejectionWarning: Error: Unable to launch browser, error message: Failed to launch the browser process!
../../base/allocator/partition_allocator/partition_address_space.cc(68) Check failed: false
`

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
`
    at Cluster.<anonymous> (/nfs/nfs7/home/kelly14/ffl/node_modules/puppeteer-cluster/dist/Cluster.js:119:23)
    at Generator.throw (<anonymous>)
    at rejected (/nfs/nfs7/home/kelly14/ffl/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by jsaubon** [comment]
got same error, anyone solved this ?

**Comment by michaellwatson** [comment]
@jsaubon did you try my fix (above)?

**Comment by boardmain** [comment]
Same error.. tried all

**Comment by boardmain** [comment]
Same error.... unable to fix... if i run the script from shell it work....
if i try to call the process via express app ( same user running the process )
i have the error

~~~

Failed to launch the browser process!
../../base/allocator/partition_allocator/partition_address_space.cc(99) Check failed: false

~~~

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by boardmain** [comment]
i did before open add a comment

**Comment by almivision** [comment]
same problem on "puppeteer": "^19.7.5" and node v16.19.0
