### ISSUE TITLE
SPA page crash.

### ISSUE THREAD

**Issue by CommanderXL** [puppeteer/puppeteer#698]
Well, there are three pages in a spa web app.In the second page, it use the code to click a button, and it send a http request.I should jump to the third page correctly. But the current behavior is the page crashed. And the terminal print :

```javascript
Unhandled promise rejection (rejection id: 2): Error: Protocol error (Runtime.callFunctionOn): Target closed.
```

I was confused. If I delete the code 

```javascript
browser.close();
```

The page jump to the three correctly.But the test code can't run properly like it can't click any element.

Code:

the click action works: 
```javascript
 await page.waitForSelector('.ticket-list-page .bottom-btn-wrapper .mf-btn')
  await page.evaluate(() => {
    const nextBtn = document.querySelector('.ticket-list-page .bottom-btn-wrapper .mf-btn')
    nextBtn.click()
  })
```
the click action doesn't work: 
```javascript
await page.waitForSelector('.ticket-list-page .bottom-btn-wrapper .mf-btn')
const nextBtn = await page.$('.ticket-list-page .bottom-btn-wrapper .mf-btn')
nextBtn.click()
```

**Comment by JoelEinbinder** [comment]
are you awaiting `nextBtn.click()`?

**Comment by aslushnikov** [comment]
@CommanderXL indeed, it looks like awaiting the `nextBtn.click()` should do the job.
Speculatively closing this, feel free to write if things still don't work for you.
