### ISSUE TITLE
Page flashes when taking screenshot with puppeteer

### ISSUE THREAD

**Issue by ericmackrodt** [puppeteer/puppeteer#6985]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Ubuntu 20.04 x64
* URLs (if applicable):
* Node.js version: 12

**What steps will reproduce the problem?**

I have a node js express server that keeps pages in memory and I control the page via HTTP requests.
I have an endpoint that returns a screenshot that looks like this:

    app.get("/ss/:id/*", async (req, res) => {
      const { id } = req.params;
      const page = await getPage(id);
    
      const { resolution } = req.cookies;
    
      let [width, height] = (resolution as string)
        .split("x")
        .map((o) => parseFloat(o));
    
      width = Math.max(width, 1) - 4; // for netscape;
      height = Math.max(height, 1) - 4; // for nestcape;
    
      const ss = await page.screenshot({
        quality: 100,
        encoding: "binary",
        type: "jpeg",
        clip: { x: 0, y: 0, width, height },
      });
    
      res.type("jpg");
      res.send(ss);
    });

**What is the expected result?**

I expect that a screenshot is going to be taken without the web page being disturbed in any way.

**What happens instead?**

Here's a video of what's happening:

https://youtu.be/FlgROI85y2E

This causes some weird issues where, on some websites where there are menus or popups that close when you click outside, when you take a screenshot, that popup or menu disappears.

Here's another example with the google about page that illustrates that:

https://youtu.be/tXqyCO8oAHg

I have tried to use PNG instead of jpeg, I have also tried without the clip. With and without setting the viewport.

I did try to ask this question on StackOverflow but I had no answers.

Thanks in advance for the help.

**Comment by acuper** [comment]
Hi

Recently I upgraded puppeteer to latest version and also noticed strange issues related to screenshots.
I had to downgrade to version 6.0.0 to achieve expected behavior.
Based on my research captureBeyondViewport: true introduced the issue. 
https://github.com/puppeteer/puppeteer/pull/6805

I'm not sure if this is a bug or now we have to use page.screenshot in different way...

**Comment by pycraft114** [comment]
@acuper u saved me 👍
