### ISSUE TITLE
Feature request: debugging inside test runners

### ISSUE THREAD

**Issue by trevordmiller** [puppeteer/puppeteer#699]
First, thanks for building such a great tool! Puppeteer is making end-to-end tests fun to write without all the flakiness of traditional e2e tests.

The debugging options are awesome:

```javascript
const browser = await puppeteer.launch({
  headless: false,
  slowMo: 250 // slow down by 250ms
})
```

However, Chrome isn't launched when this code is inside of a test runner; for example, with Jest:

```javascript
import puppeteer from 'puppeteer'

const appUrlBase = 'http://localhost:4000'

let browser
let page

beforeAll(async () => {
  const options = process.env.NODE_ENV === 'testDebug'
    ? {
        headless: false,
        slowMo: 250 // slow down by 250ms
      }
    : {}
  browser = await puppeteer.launch(options)
  page = await browser.newPage()
})

test('user sees browser title', async () => {
  await page.goto(appUrlBase)
  const browserTitle = await page.title()
  expect(browserTitle).toBe('ropig')
})

test('user is redirected to login when logged out on private routes', async () => {
  await page.goto(appUrlBase)
  await page.waitForSelector('[data-testId="userLoginForm"]')
})

afterAll(async () => {
  browser.close()
})
```

Right now I'm using `page.plainText()` to debug output, but having the non-headless and slowMo options would be fantastic if possible. Thank you.

**Comment by JoelEinbinder** [comment]
Does this code throw an error, or just not work? Or it works but you want it baked into Puppeteer?

Assuming Chrome isn't working, can you add `dumpio: true` to the options and see if there is anything useful in its output? Thanks!

**Comment by trevordmiller** [comment]
@JoelEinbinder It wasn't working and a `dumpio: true` didn't have any useful output so I tried wiping and reinstalling `node_modules` and that did the trick: it is working now. So this doesn't seem to be a problem in Puppeteer, sorry for the issue. Closing now.
