### ISSUE TITLE
Make a sane README.md

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#7]
There should be a nice README which 
- explains Puppeteer's motivation and goals
- provides FAQ
- points to other useful resources, such as API documentation

**Comment by aslushnikov** [comment]
@ebidel, I've updated README.md in 10e28a9b to make it more relevant. There are still a few TODO's left here and there. Let me know if you have any ideas how it could be further improved!

**Comment by ebidel** [comment]
Still needs more love, but I did some basic polish in https://github.com/GoogleChrome/puppeteer/pulls.

**Comment by aslushnikov** [comment]
This seems to be good enough, closing this. If there are any concerns, feel free to submit an issue / PR.
