### ISSUE TITLE
Error: window is not defined - in page.evaluate function

### ISSUE THREAD

**Issue by zaalgol** [puppeteer/puppeteer#7000]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Ubuntu 18.04.2 
* Node.js version: 12.21.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

    const assert = require("assert");
    const puppeteer = require("puppeteer");
   
    const assertOnLeft = async (predicate) => {
      const asserterOk = assert.ok;
      await page.exposeFunction("predicate", predicate);
      await page.evaluate((asserterOk) => { // creates Error: Evaluation failed: ReferenceError: window is not defined
            return predicate(asserterOk)
       }, asserterOk)
        .catch((e) => console.log("error", e));
    }
    
    // this code is given And can't be changed!
    assertOnLeft(function (asserter) {
                asserter(window.location.href.indexOf("XXX:3000/regression_test_pages/links_page.html") == 0,
                 "Address should be links_page.html");
     });
**What is the expected result?**
Test that the current URL is "XXX:3000/regression_test_pages/links_page.html"

**What happens instead?**
print :

    error Error: Evaluation failed: ReferenceError: window is not defined

**Comment by vanstline** [comment]
I have a similar problem

**Comment by LeifAndersen** [comment]
FWIW, I also am having this issue. :(

**Comment by LeifAndersen** [comment]
Ugg...okay, I think I found a solution. The thing is pupeteer seems to rely on the _dynamic_ value of `this`, which is statically kept with the arrow syntax `() => {...}`, which is what you want 99.99999% of the time. But **NOT** for the older `function(){...}` syntax.

Switching to the `function(){...}` syntax seems to fix the problem:

```
const assert = require("assert");
const puppeteer = require("puppeteer");

const assertOnLeft = async (predicate) => {
  const asserterOk = assert.ok;
  await page.exposeFunction("predicate", predicate);
  await page.evaluate(function(asserterOk) { // Note the different syntax
        return predicate(asserterOk)
   }, asserterOk)
    .catch((e) => console.log("error", e));
}

// this code is given And can't be changed!
assertOnLeft(function (asserter) {
            asserter(window.location.href.indexOf("XXX:3000/regression_test_pages/links_page.html") == 0,
             "Address should be links_page.html");
 });
```

IMO the documentation _really_ should address this.
