### ISSUE TITLE
SyntaxError on some of the source files when trying to run puppeteer with npm <filename>

### ISSUE THREAD

**Issue by drodriguezIE** [puppeteer/puppeteer#7004]
### Steps to reproduce

The code:
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```
When I run `npm index.js`
I get the error:
```
/home/daniel/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:712
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/daniel/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:19:19)
```

**Tell us about your environment:**
Recently updated npm version to lastest
Fresh install of puppeteer v8.0.0 (also tried with v7.1.0 I get the same error)

* Puppeteer version: 8.0.0
* Platform / OS version: Ubuntu 18.04.5 LTS x86_64
* URLs (if applicable): N/A
* Node.js version: 8.10.0

**What is the expected result?**
Run the example

**What happens instead?**
I get an error from the source files, everywhere were there is a "try/catch" where the catch is missing a parenthesis:
example:
in  `.../puppeteer/lib/cjs/puppeteer/common/Page.js` line 712
```js
...
async _onBindingCalled(event) {
        let payload;
        try {
            payload = JSON.parse(event.payload);
        }
        catch { // <-- This is the line where I get the error
            // The binding was either called by something in the page or it was
            // called before our wrapper was initialized.
            return;
        }
...
```

_**WORKARROUND THIS ISSUE:**_
I used VS code to search and replace every file, inside `/home/daniel/node_modules/puppeteer/lib/`, where the `catch {` is missing a parenthesis (`catch (e) {`) so that the code above for example would look as follow:
```js
...
async _onBindingCalled(event) {
        let payload;
        try {
            payload = JSON.parse(event.payload);
        }
        catch (e) { // <-- FIX
            // The binding was either called by something in the page or it was
            // called before our wrapper was initialized.
            return;
        }
...
```
![image](https://user-images.githubusercontent.com/54848250/111632483-e6304a00-87ca-11eb-8a51-9fe72a13153a.png)

**Comment by pranayaryal** [comment]
@drodriguezIE can you try to upgrade your Node version and test?

**Comment by drodriguezIE** [comment]
Sorry for the late response, the issue was solved by updating to the latest Node version (node@15.10.0 in my case).
