### ISSUE TITLE
Overcome Cloudflare's blocking: Please turn JavaScript on and reload the page.

### ISSUE THREAD

**Issue by suntong** [puppeteer/puppeteer#7006]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Ubuntu 20.04 LTS
* URLs (if applicable):
* Node.js version: v10.21.0

**What steps will reproduce the problem?**

```
    const response = await page.goto(`https://finviz.com/news.ashx`, {
      waitUntil: 'networkidle0'
    });
    console.log(await page.content());
```

**What is the expected result?**

Get normal page

**What happens instead?**

Got, 

```
Please turn JavaScript on and reload the page
Please enable Cookies and reload the page.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…

            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>

```

The url has been working fine for ages, until it broke just a day or two before.

Any way to by-pass it? Thx

**Comment by suntong** [comment]
So many similar questions on SO that don't have an answer, however, I did find out an article

https://dev.to/rubengmurray/using-cookies-puppeteer-nodejs-to-mirror-a-chrome-profile-on-macos-1l6m

which seems quite promising...

**Comment by suntong** [comment]
it works

**Comment by suntong** [comment]
Nope, only works when `headless: false`, :(

**Comment by suntong** [comment]
The only change is from `headless: true` to `headless: false` and script would work magically. How strange!

Seems to me that Cloudflare is able to detect when I'm using `headless: true` and send the alternative blocking html, with `Please turn JavaScript on and reload the page`. 

Even if I trigger `page.reload` myself won't help. 

Any idea anything else I can try, to make `headless: true` working?

**Comment by mrceperka** [comment]
https://www.npmjs.com/package/puppeteer-extra-plugin-stealth might help... :crossed_fingers:

**Comment by mathiasbynens** [comment]
This is not a problem with Puppeteer but rather with the web page.

**Comment by suntong** [comment]
Thanks a lot @mrceperka for sharing that well-kept secret, really appreciate it!!! Horay!

**Comment by mtatarau90** [comment]
Hi @suntong 
You found any solution to bypass this "issue" ? I encountered the same issue and puppeteer-extra is not enough. 

Thanks

**Comment by suntong** [comment]
read my last comment again, @mtatarau90.
If you don't get it, read it again, and again, until you get it -- what my last sentence and those up-votes means.

That's all I want to say on this.

**Comment by garora1212** [comment]
following

**Comment by basetta** [comment]
thanks @suntong and @mrceperka :D

**Comment by 10111282** [comment]
> https://www.npmjs.com/package/puppeteer-extra-plugin-stealth might help... 🤞

Worked for me to fix the issue 
<img width="348" alt="Screen Shot 2022-03-04 at 1 23 43 PM" src="https://user-images.githubusercontent.com/8945334/156746045-589cf63e-626b-4a80-a9ea-dff4036ce4f7.png">

**Comment by batrachophagous1** [comment]
this is happening to me as well

**Comment by yurist38** [comment]
Same here. Also experiencing this issue only in non-headless mode (even when using puppeteer extra + stealth plugin).

**Comment by abdellah711** [comment]
setting user agent using `page.setUserAgent` fixed the issue for me

**Comment by kishorek01** [comment]
With the new version of puppeteer tried this. This only happens when the puppeteer applies controller to the browser pages. The sites will work fine even in headless mode if you are using the default blank page the puppeteer creates without the controller. I tried it with the existing browser by connection wsendpoint. As i get the pages from the browser it applies all the default puppeteer values and controller to all the webpages . So we need to find out how cloudfare and other bot detection sites finds the controller from puppeteer.
