### ISSUE TITLE
How to navigate to "chrome://newtab/" url?

### ISSUE THREAD

**Issue by bleszerd** [puppeteer/puppeteer#7009]
In my case, I need to navigate to "chrome://newtab" in Brave browser, but `page.goto( )` only allows navigations to `http` routes, how can I get around this problem?

my code:
```js
const browser = await puppeteer.launch({
   executablePath: path.resolve('src/Browser/brave_browser/brave'),
})

const page = await browser.newPage()
await page.goto("chrome://newtab") // Error with "headless true" at puppeteer launch function
```

Error: `Error: net::ERR_INVALID_URL at chrome://newtab`

with `headless: false` on `puppeteer.launch` options this works well.

Note: I can't use X server like gnome or KDE after deploy!

**Comment by wuyeguangming** [comment]
I have the same problem when `page.goto("chrome://downloads/")` on win10
ps: "puppeteer": "^11.0.0"
