### ISSUE TITLE
How to count opened browsers (not pages)?

### ISSUE THREAD

**Issue by abokizh** [puppeteer/puppeteer#7010]
I am using this code to create tabs with separate sessions:
```
async function closePage(browser, page) {
    if (page.browserContextId != undefined) {
        await browser._connection.send('Target.disposeBrowserContext', { browserContextId: page.browserContextId });
    }
    await page.close();
}



async function newPageWithNewContext(browser) {
    const { browserContextId } = await browser._connection.send('Target.createBrowserContext');
    const { targetId } = await browser._connection.send('Target.createTarget', { url: 'about:blank', browserContextId });
    var targetInfo = { targetId: targetId }
    const client = await browser._connection.createSession(targetInfo);
    const page = await browser.newPage({ context: 'another-context' }, client, browser._ignoreHTTPSErrors, browser._screenshotTaskQueue);
    page.browserContextId = browserContextId;
    return page;
}
```
I use it with ```--incognito``` browser and I wanted to make sure that this code actually creates TABS with separate sessions, not new incognito browsers. I can't check it visually, because this code work only in headless mode. So I wanted to add a line of code that would show how many browsers did puppeteer open so I am sure that my code actually creates TABS not browsers.

**Comment by awxlfy** [comment]
Did you get it figured out? I'm trying to do something similar where I am able to track browsers and associate them to certain tasks so would love to know what you did if you got it working.

**Comment by abokizh** [comment]
> Did you get it figured out? I'm trying to do something similar where I am able to track browsers and associate them to certain tasks so would love to know what you did if you got it working.

Unfortunately no(

**Comment by awxlfy** [comment]
I was able to easily track browsers within react but I've had no success otherwise. If you're using react you can actually set a component state to the browser object and you can associate that to that particular component. Still trying to find a workaround for doing it normally within node though.
