### ISSUE TITLE
Failing to launch process

### ISSUE THREAD

**Issue by Lucetia** [puppeteer/puppeteer#7018]
Currently I am trying to run a program called "destreamer" on Raspbian OS.  The program itself uses puppeteer from the looks of it.  When I go to run the command I get the following error:

```
Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process!
/home/pi/destreamer/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/destreamer/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/pi/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.helper_js_1.helper.addEventListener (/home/pi/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I tried running the `ldd chrome | grep not` command and at first gave an error of `ldd: ./chrome: No such file or directory` so I have to dig through the folders in the file system and then copy/paste it to cd into it at the command line.  Once I did that it now returns `**not** a dynamic executable`

Puppeteer looks like it is on version 5.5.0 based on the info it gives when I do a `npm i puppeteer`.  Nodejs looks like it is on version 10.24.0.

After doing some googling, I found it is likely due to dependencies so I found `npm i puppeteer` to reinstall it and same result.  Then next I ran `sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget` that would install most of the dependencies it would need with the same result occuring.

Most of the things I am finding are in regards to program your application which in this case wouldn't apply since I'm running one and that doesn't seem to be the problem.

**Comment by mhazy** [comment]
You're more likely to get a response if you report this on destreamer's issue queue (https://github.com/snobu/destreamer/issues)

**Comment by Lucetia** [comment]
> You're more likely to get a response if you report this on destreamer's issue queue (https://github.com/snobu/destreamer/issues)

Thanks for the reply!  I figured I would throw it here since it looked like it was a puppeteer issue based on where it mentioned to troubleshoot.  I'll put it up there on their site too and see if I can snag a response.

Thanks again!
