### ISSUE TITLE
'"puppeteer"' has no exported member 'puppeteer' using Typescript

### ISSUE THREAD

**Issue by anphetamina** [puppeteer/puppeteer#7028]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0 / 7.1.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version: 14.16.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Install `puppeteer` and `@types/puppeteer 5.4.3`
2. Create a `.ts` file with the following code

```
import { puppeteer } from "puppeteer";

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://news.ycombinator.com', {
    waitUntil: 'networkidle2',
  });
  // page.pdf() is currently supported only in headless mode.
  // @see https://bugs.chromium.org/p/chromium/issues/detail?id=753118
  await page.pdf({
    path: 'hn.pdf',
    format: 'letter',
  });

  await browser.close();
})();
```

3. Get the error `Module '"puppeteer"' has no exported member 'puppeteer'.ts(2305)` at the first line

**What is the expected result?**

**What happens instead?**

**Comment by nik-here** [comment]
just remove the curly braces:

```js
import puppeteer from "puppeteer";
```

**Comment by max-hk** [comment]
> just remove the curly braces:
> 
> ```js
> import puppeteer from "puppeteer";
> ```

But if we do that TypeScript fail to find the module's types.

```
error TS1192: Module '".../node_modules/puppeteer/lib/types"' has no default export.
```

**Comment by nik-here** [comment]
Try to add following in your tsconfig.json:
```json
"compilerOptions": {
  "allowSyntheticDefaultImports": true,
},
```

**Comment by max-hk** [comment]
> Try to add following in your tsconfig.json:
> 
> ```json
> "compilerOptions": {
>   "allowSyntheticDefaultImports": true,
> },
> ```

Thx. It works.

**Comment by anphetamina** [comment]
> 
> 
> Try to add following in your tsconfig.json:
> 
> ```json
> "compilerOptions": {
>   "allowSyntheticDefaultImports": true,
> },
> ```

why is that needed?

**Comment by nik-here** [comment]
If you open the following file "node_modules/@types/puppeteer/index.d.ts", you will notice there is no default export. Instead each class, interface, etc. are exported just with the "export" statement. So if you want to import something from puppeteer and you are using ES6 Modules, you have to use curly braces. e.g.:
```javascript
import { launch } from "puppeteer"
```
[More Infos](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

However, Typescript offers the feature "allowSyntheticDefaultImports". Basically it allows to import everything as default if there is no default export in the file.
