### ISSUE TITLE
Protocol error (Network.deleteCookies): Invalid parameters Failed to deserialize params.name - BINDINGS: mandatory field missing at position 58544

### ISSUE THREAD

**Issue by abokizh** [puppeteer/puppeteer#7029]
* Puppeteer version: 5.4.3
* Platform / OS version: Centos 7
* URLs (if applicable):
* Node.js version: v12.16.3

1. To save cookie I use: ```let cookie = await page.cookies(); return JSON.stringify(cookie);``` and store this string in my database
2. To load cookies I use ``` const cookieJSON = JSON.parse(cookie);
    const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();
    await page.setCookie(cookieJSON);```

**Expected result**

To have cookies injected into the page and no need to login to the website anymore

**What happens instead**
```
UnhandledPromiseRejectionWarning: Error: Protocol error (Network.deleteCookies): Invalid parameters Failed to deserialize params.name - BINDINGS: mandatory field missing at position 6968
```

Any ideas of what is going wrong?

**Comment by mattparlane** [comment]
You can't call `page.setCookie` with an array of cookies, it needs to be called separately for each cookie. Try:

```
for (let i = 0; i < cookieJSON.length; i++) {
  await page.setCookie(cookieJSON[i]);
}
```

**Comment by weigu123** [comment]
The problem is still there

**Comment by juan-mesh** [comment]
> You can't call `page.setCookie` with an array of cookies, it needs to be called separately for each cookie. Try:
> 
> ```
> for (let i = 0; i < cookieJSON.length; i++) {
>   await page.setCookie(cookieJSON[i]);
> }
> ```

Worked for me

**Comment by randybastian777** [comment]
i already try all of above.

still error:
ProtocolError: Protocol error (Network.setCookies): Invalid parameters Failed to deserialize params.cookies.expires - BINDINGS: double value expected at position 222.

any update?

**Comment by filippopassalacqua** [comment]
Same errore

Protocol error (Network.deleteCookies): Invalid parameters Failed to deserialize params.partitionKey - BINDINGS: string value expected at position 26

**Comment by taukirsheikh** [comment]
This problem occurs when you have `"expires":null` in your cookies, which the whole cookies as invalid, so either completely remove it from cookies array or put `"expires":-1`

**Comment by moeinrahimi1** [comment]
simply use like below:
cookies is a array of objects like this:
``` javascript
const cookies = [
{
        "name": "night_mode",
        "domain":".x.com",
        "path":"/",
        "value": "2"
    }
]
browser.setCookie(...cookies)
```
