### ISSUE TITLE
Full page screenshot is not using viewport size for `vw` and `vh` CSS.

### ISSUE THREAD

**Issue by yuliyan** [puppeteer/puppeteer#703]
Using `fullPage: true` option with [Page.screenshot](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagescreenshotoptions) seems to be messing `vw` and `vh` CSS units, even though page size is set with [Page.setViewport](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport).

**Comment by aslushnikov** [comment]
@yuliyan could you please share with us a reproduction scenario, including script, page you try to screenshot and actual/expected outcomes?

This would save us a ton of time figuring what's going on.

**Comment by yuliyan** [comment]
An example page that's using `vh` CSS units - http://jsbin.com/fawerivecu/edit?html,css,output.

**Script:**
```Javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://output.jsbin.com/fawerivecu');
  await page.setViewport({
  	width: 1920,
  	height: 1080
  });
  await page.screenshot({ path: 'example.png', fullPage: true });

  browser.close();
})();
```

**Expected Result:**
![expected_result](https://user-images.githubusercontent.com/2722412/30196887-9eb06188-946c-11e7-95d5-a46ba6f6e5ea.png)

**Actual Result:**
![actual_result](https://user-images.githubusercontent.com/2722412/30196890-a84bd6a0-946c-11e7-8021-967e415f1ac0.png)

**Comment by aslushnikov** [comment]
Thanks, that's a bug with full page screenshots. Filed upstream: [crbug.com/763421](https://bugs.chromium.org/p/chromium/issues/detail?id=763421)

**Comment by gtroshin** [comment]
Hey!
Any progress here? :) Maybe somebody knows the workaround?

**Comment by tcjr** [comment]
The only workaround I have been able to get working is to change this line
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L713
from this:

```
const width = Math.ceil(metrics.contentSize.width);
```

to this:

```
const width = this._viewport.width;
```

The current code is resizing the height correctly because you want a full-height screenshot, but it's also resizing the screenshot's width to the size of the content, ignoring the viewport settings.  I think the width should maintain the desired viewport size.

**Comment by schnerd** [comment]
My current workaround – instead of using `fullPage` I measure the body bounding box and use that as a clipping argument:

```
const bodyHandle = await page.$('body');
const { width, height } = await bodyHandle.boundingBox();
const screenshot = await page.screenshot({
  clip: {
    x: 0,
    y: 0,
    width,
    height
  },
  type: 'png'
});

await bodyHandle.dispose();
```

**Comment by faithworksio** [comment]
@schnerd - That worked like a charm for me! Exactly what I needed. Big Thanks

**Comment by joshferrell** [comment]
I saw that this was tasked as a Chromium bug. Is there a issue associated with this [there](https://bugs.chromium.org) where this can be tracked?

**Comment by whoisjuan** [comment]
For what's it's worth, I don't think this is an actual bug, but rather the expected behavior of the viewport. If you open a Chrome page in a vertical monitor at full height, and you open a website using 100vh in a section (for example the hero), the section will take the entire height of the screen (as expected). When people implement their websites with Viewport units, they don't account for supermassive vertical screens, so it doesn't make sense to think in a scenario where the page isn't visualized with at least one screen fold scroll.

There are many ways to get around this but not all the strategies will cover 100% of the cases. The solution that puppeteer could provide is to receive an extra parameter besides the fullPage=true, with a pseudo-viewport height in pixels, then when rendering before snapping it should swap any references that are using 100vh, to the passed pseudo-viewport height in pixels.

There's actually a PostCSS plugin that does that to fix an issue with a CMS. Not the same problem but within the same realm of what's going on here: https://www.npmjs.com/package/postcss-vh-to-px

**Comment by ratkorle** [comment]
Can anyone help me with this issue:

https://stackoverflow.com/questions/54828240/why-viewport-is-changing-on-page-screenshot-puppeteer

**Comment by morteza-fsh** [comment]
This package may help you: 
https://github.com/morteza-fsh/puppeteer-full-page-screenshot

**Comment by konsalex** [comment]
The vh and vw are really a pain.

I wrote a piece of code as a way around, that works most of the times. The way it works is that it get all the active stylesheets if permitted, then find and replaces `vh` and `vw` values with respect to the viewport of the browser (before screenshooting).

You can find the code [here](https://gist.github.com/konsalex/9d34aab28d488e9d75b4e568007e34f0)

**Comment by Kikobeats** [comment]
I'm experiencing the same issue and the thing that worked to me is setup a tiny viewport.

This is a screenshot using a MacBook pro 13 viewport:
https://api.microlink.io/?url=https://draftbit.com/&screenshot&fullPage&embed=screenshot.url

And this is the same but setting up iPad viewport
https://api.microlink.io/?url=https://draftbit.com/&screenshot&device=ipad&fullPage&embed=screenshot.url

**Comment by mathias22osterhagen22** [comment]
Experiencing the same issue with a website that have "accordion" div on the bottom of the page. Opening them all + taking a screenshot get me only one part of the page.

I finally succed to manage it on this tricky way (my viewport is set of 800 x 600), half based on the [package here](https://www.npmjs.com/package/puppeteer-full-page-screenshot) (pretty bad btw):
```js
const MergeImg = require('merge-img');
const Jimp = require('jimp');

class ScreenshotFixer {
    async fullPageScreenshot(page, options = {}) {
        //viewport was manually set at width: 800 x height: 600
        //Get the max scroll : 
        let maxscroll = await page.evaluate(() => {
            window.scrollTo(0, Number.MAX_SAFE_INTEGER)
            let max = document.documentElement.scrollTop;
            window.scrollTo(0, 0);
            return max;
        });
        //Get the number of time to scroll
        let pagesCount = Math.ceil(maxscroll / 600);
        //Get the extra pixel (too much pixel on the last pict)
        let extratocrop = (maxscroll - ((pagesCount - 1) * 600));
        const images = [];
        for (let index = 0; index <= pagesCount; index += 1) {
            if (options.delay) {
                await page.waitFor(options.delay);
            }
            const image = await page.screenshot({ quality: 60, fullPage: false, type: "jpeg", });
            await page.evaluate((index) => {
                window.scrollTo(0, 600 * index); //avancer de 600
            }, (index + 1));
            images.push(image);
        }
        //Only one page fast process
        if (pagesCount === 0) {
            const image = await Jimp.read(images[0]);
            if (options.path) image.write(options.path);
            return image;
        }
        //Remove extra pixels if needed
        if (extratocrop > 0) {
            // crop last image extra pixels
             const cropped = await Jimp.read(images.pop())
                 .then(image => image.crop(0, 600 - extratocrop, 800, extratocrop))
                 //.then(image => image.crop(0, extratocrop, 800, 600 - extratocrop))
                 .then(image => image.getBufferAsync(Jimp.AUTO));
             images.push(cropped);
        }
        const mergedImage = await MergeImg(images, { direction: true });
        if (options.path) mergedImage.write(options.path);
        return mergedImage;
    };
}

module.exports = new ScreenshotFixer();
```

**There is the logical step:**
1.  Before to call this function I open all the accordion div, wait 1 sec and call the `await ScreenshotFixer.fullPageScreenshot(page);`function
2. It scroll to the bottom of the page
3. It save the current scroll position (its the max one)
4. It calculate how many screen will be needed (current scroll position / height size of the viewport)
5. It takes the screenshot
6. Crop the extra pixel if needed (the last page usually is totally on bottom then there is some of the previous screenshot part above it)
7. It merge them and save them if there is a path provided

*Note:* That the quality was set to 60 (own personal needs)

Hope this can help someone while waiting for this issue.

**Comment by msadougi** [comment]
add this code before screenshot to fix:

`await page.evaluate(async () => {
                var allElems = window.document.getElementsByTagName("*");
                for (var i = 0, max = allElems.length; i < max; i++) {
                    var hEleme = window.getComputedStyle(allElems[i]).height;
                    if(hEleme != 'auto'){
                        var numdEleme = Number(hEleme.slice(0, -2));
                        if(numdEleme > 100 && numdEleme < 1000){
                            allElems[i].style.setProperty("height", numdEleme + 'px', "important");
                        }
                    }
                }
                return true;
            });`

**Comment by BennyAlex** [comment]
@sadoghes 
Hey, can you explain why you need `if(numdEleme > 100 && numdEleme < 1000)`, please?

**Comment by mittster** [comment]
@msadougi 
> await page.evaluate(async () => { var allElems = window.document.getElementsByTagName("*"); for (var i = 0, max = allElems.length; i < max; i++) { var hEleme = window.getComputedStyle(allElems[i]).height; if(hEleme != 'auto'){ var numdEleme = Number(hEleme.slice(0, -2)); if(numdEleme > 100 && numdEleme < 1000){ allElems[i].style.setProperty("height", numdEleme + 'px', "important"); } } } return true; });


Would also like to hear about why `if(numdEleme > 100 && numdEleme < 1000)` is used?

**Comment by OrKoN** [comment]
I am closing this issue because accumulated many discussion comments. The original Chromium issue was fixed (crbug.com/763421) and another issue linking here has been marked as won't fix: https://crbug.com/923417 If you still experience an issue with taking fullscreen screenshots, please open a new issue with a minimal reproducible example using the latest Puppeteer so that we can investigate again.

**Comment by FlopiFlow** [comment]
> My current workaround – instead of using `fullPage` I measure the body bounding box and use that as a clipping argument:
> 
> ```
> const bodyHandle = await page.$('body');
> const { width, height } = await bodyHandle.boundingBox();
> const screenshot = await page.screenshot({
>   clip: {
>     x: 0,
>     y: 0,
>     width,
>     height
>   },
>   type: 'png'
> });
> 
> await bodyHandle.dispose();
> ```

Sometimes html and body heights are set to 100% and the height value returned bodyHandle.boundingBox() is not always the real height of the page.

If you have this problem and want to get the real page height, you can try to use the scrollHeight properties of body like this:
`
const scrollHeight = await page.evaluate(() => {
  return document.body.scrollHeight;
});

await page.screenshot({
    path: "/path/to/save",
    clip: {
        x: 0,
        y: 0,
        width,
        height: scrollHeight
    }
});
`
