### ISSUE TITLE
Why is the readme showing how to open a new tab instead of using the initial one?

### ISSUE THREAD

**Issue by Annihil** [puppeteer/puppeteer#7035]
```
const page = await browser.newPage();
```
instead of
```
const page = (await browser.pages())[0];
```

I dislike having two tabs open when using all the examples provided, because of memory usage consumption, it's also just strange to have an empty tab lying around, or is it OCD?
I always have to dig into previous projects or the documentation to find the right method to use.
Is there any specific reason for that?

**Comment by littlezigy** [comment]
Thanks for this! The extra tab was really bothering me too. The readme should have this in it.
