### ISSUE TITLE
Pupeteer is downloading unrequested files that consume bandwidth and cannot be intercepted or stopped

### ISSUE THREAD

**Issue by alexandrucancescu** [puppeteer/puppeteer#7042]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0 or 8
* Platform / OS version: macOS Big Sur
* URLs (if applicable):
* Node.js version: 14.15.1

I am using Puppeteer along a proxy service, and after getting unexplainable high bandwidth usage I started to use a local proxy server to monitor the requests that were generating this bandwidth. I discovered that almost 90% of the traffic was used to request some **crx** file.

My project requires me to open a a few thousand browsers every hour, in order to keep each task with it's own cookies and proxy. Every Chromium browser I open will eventually download ~10MB of files, through the proxy that is passed as arg to `puppeteer.launch`. This requests cannot be intercepted using `page.setRequestInterception(true)` and `this.page.on("request", ...)`. 

Using my own proxy server that mostly acts as a middle man to monitor the requests made by chrome, I blocked the first domain that Chromium was using to download these **crx** files, but Chromium started to download them from another domain, and so on. This domains and URLs are:

1. http://redirector.gvt1.com/edgedl/chromewebstore/L2Nocm9tZV9leHRlbnNpb24vYmxvYnMvYjFkQUFWdmlaXy12MHFUTGhWQUViMUVlUQ/0.57.44.2492_hnimpnehoodheedghdeeijklkeaacbdc.crx
2. http://dl.google.com/chromewebstore/L2Nocm9tZV9leHRlbnNpb24vYmxvYnMvYjFkQUFWdmlaXy12MHFUTGhWQUViMUVlUQ/0.57.44.2492_hnimpnehoodheedghdeeijklkeaacbdc.crx
3. https://google.com/dl/something/something
4. There were even more

This files are getting downloaded for every new browser launched, using expensive proxy bandwidth.

1. **Is there a way to stop these downloads, or at least make chrome only download it once? This happens for both v5.5.0 and v8.0.0**
2. **Can I at least instruct chrome to download these files without using the proxy?**

**Comment by imflexwala** [comment]
I facing the exact same issue, high bandwidth usage when chrome is relaunched.
It's eating up very expensive proxy bandwidth.
Please provide some solution

**Comment by OrKoN** [comment]
How do you run the browser instance? do you use the bundled Chromium binary or the regular Google Chrome?
