### ISSUE TITLE
Can't install Firefox Puppeteer on Windows 10

### ISSUE THREAD

**Issue by Somberor** [puppeteer/puppeteer#7044]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version:  v12.16.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I was trying to install Firefox By the command:
PUPPETEER_PRODUCT=firefox  npm install puppeteer

**What is the expected result?**

got the next error:
`PUPPETEER_PRODUCT=firefox : The term 'PUPPETEER_PRODUCT=firefox' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.`

**What happens instead?**

It didn't work

What am I doing wrong?
(I tried on linux and it worked fine , but I need it to work on Windows 10)

**Comment by EAIS-PY** [comment]
This helped me:

**npm config set puppeteer_product=firefox**

**npm install puppeteer**

**Comment by mbehzad** [comment]
it think on windows you have to set env var in cmd like:
`set PUPPETEER_PRODUCT=firefox&& npm install puppeteer`

**Comment by whimboo** [comment]
That is right. As such we should be able to close this issue. Please let us know if that is still not working for you, and we can reopen.

**Comment by sharjeelfaiq** [comment]
Hello. I'm unable to install the npm package puppeteer. I don't know why. It gives the following error
![asc](https://user-images.githubusercontent.com/63894149/149999034-13955c14-226f-4231-8cb9-2e388fbabc2a.PNG)
.

**Comment by whimboo** [comment]
@mrmalik16 this has nothing to do with this issue. You are basically encountering network issues as the error message states. Please check your proxy settings if one is set, and maybe try yourself to reach `registry.npmjs.org`. As it looks like this URL is blocked.
