### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by Iswaryasl** [puppeteer/puppeteer#7046]
### Steps to reproduce

* Puppeteer version: 3.0.4
* Platform / OS version:MAC OS X / 10.9.5
* Node.js version: v12.11.0
* Npm version : v6.11.3

**What steps will reproduce the problem?**

```javascript
var opt = {}; 
  if(os == "linux") { 
      opt.args = [ 
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-gpu',
          '--disable-dev-shm-usage',
          '--no-first-run',
          '--no-zygote'
      ]; 
  } 
  opt.headless = true;
  var browser = await puppeteer.launch(opt) 
  ```

**What happens instead?**
UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
   TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
    at onClose   node_modules/puppeteer/lib/Launcher.js:547:20)
   at Interface.<anonymous> node_modules/puppeteer/lib/Launcher.js:537:65)
   at Interface.emit (events.js:215:7)
   at Interface.close (readline.js:403:8)
   at Socket.onend (readline.js:180:10)
  at Socket.emit (events.js:215:7)
  at endReadableNT (_stream_readable.js:1183:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by paulbrzeski** [comment]
I'm having this issue on a Ubuntu box at the moment. Ran fine for months but I did install some new packages and updates via apt earlier so it could be a number of things.

OK, made some progress. Looks like the default path for chrome is incorrect. It thinks it's "chrome" but the required file may not be in the folder. The two _sandbox and -wrapper files don't seem to work.

Removing the node_modules folder and reinstalling seemed to do the trick :) 

![image](https://user-images.githubusercontent.com/951100/115083725-6bc62780-9f3a-11eb-85b0-79ba2b415f87.png)
