### ISSUE TITLE
Feature Request: frame does not support keyboard input

### ISSUE THREAD

**Issue by huck-fastpay** [puppeteer/puppeteer#7049]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Mac OS
* URLs (if applicable): N/A
* Node.js version: v12.13.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I need to remove/delete text in an iFrame via puppeteer.  I can do it easily using the page method/object, i.e.

    await page.click(cssSelectorInput);
    for (let i = 0; i < settings._30; i++) {
        await page.keyboard.press('Backspace');
    }

The above will remove 30 characters or less from the CSS Selector cssSelectorInput.
But, when I try:

    // Get the iFrame in Signle Sign On page
    const frameHandle = await page.$('iframe[id="sso-iframe"]');
    const frame = await frameHandle.contentFrame();

    await frame.click(cssSelectorInput);
    for (let i = 0; i < settings._30; i++) {
        await frame.keyboard.press('Backspace');
    }

Yes, I know, looking at the puppeteer, frame.keyboard is not there.  So, how can I remove text from an input box via puppeteer?

**What is the expected result?**
frame.keyboard.press should provide with a method of inputting keyboard selections

**What happens instead?**
nada

**Comment by webhype** [comment]
I concur, there's no apparent solution to send keypresses to frames/iframes.

**Comment by pierreminiggio** [comment]
I face the same issue, TikTok introduced an iframe on their upload page (they moved the whole form there), which means I can't erase the input anymore.
I'm using a for loop that presses backspace multiple times just like OP.

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.

**Comment by pierreminiggio** [comment]
Hello, I found a workaround, you can use
 frame.focus to focus on the HTML Element,
 And then you can use page.keyboard.press :
 Exemple here : https://github.com/pierreminiggio/tiktok-poster/blob/38a51876afce48066751a07b0e45b41d0ea28a53/main.js#L108
