### ISSUE TITLE
We either navigate top level or have old version of the navigated frame

### ISSUE THREAD

**Issue by zloirock** [puppeteer/puppeteer#7050]
I'm trying to get `core-js` usage statistics in the wild and check the top 10000 sites by `puppeteer` (1 browser, pages by the number of CPUs), [script](https://github.com/zloirock/core-js/blob/9cb108949eb0855a95adb13c4613500357a56d0d/scripts/usage.js). In most cases, after some thousands of checked sites, I have this error and I can't catch it. Looks like an equal of #3309.
```
/***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: We either navigate top level or have old version of the navigated frame
    at Object.assert (/***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at FrameManager._onFrameNavigated (/***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:196:21)
    at /***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:57:64
    at /***/core-js/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/***/core-js/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (/***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:225:18)
    at Connection._onMessage (/***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:101:25)
    at WebSocket.<anonymous> (/***/core-js/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
```

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: M1, MacOS 11.2.3
* Node.js version: 15.12

**What steps will reproduce the problem?**

1. Copy script by the link above
2. Install dependencies
3. Run with param `-l=10000`

**Comment by Saranya-v60** [comment]
@zloirock ,I am also getting the same issue as above. Please let me know how this issue is resolved

**Comment by zloirock** [comment]
@Saranya-v60 I solved it for myself by a restart of a browser each some pages.

**Comment by Saranya-v60** [comment]
@zloirock ,Thanks for the reply.
My scenario is ,I have 35 e2e test files and each file has approx. 2-7 test cases. for each test file, I am opening the new browser and closing after test cases execution. In pipeline some of the test files itself not running and giving error as "We either navigate top level or have old version of the navigated frame". 
If I want to do the restart of browser means for each test case I need to open new browser instead of each test file?

**Comment by dashjuthika** [comment]
Is there any alternative solution for this? in my scenario, i can not restart my browser/puppeteer
I am using latest puppeteer i.e.  13.0.1

**Comment by pinnick** [comment]
Also getting this error with puppeteer version 13.1.1
Tried downgrading to 13.0.1, didn't work

**Comment by tyurin-ilya** [comment]
Same error on puppeteer-core version 13.1.3

**Comment by vkalchuk** [comment]
I have the same error sporadically popping on different pages, version 13.4.1.

**Comment by j-wsl** [comment]
Did anyone find a solution to this?

**Comment by Sanqui** [comment]
My best solution was to create a wrapper, run the script invoking Puppeteer as a subproccess, and restart it when this error was encountered.  It is possible to catch and recognize this error on the `uncaughtExceptionMonitor` signal, but the process cannot recover so I had it send a signal to the parent process to be restarted.  This does require setting up the capacity to save and resume state, which you might desire anyways but is extra work.

I have since moved onto working with a single page application where I don't encounter this error.

**Comment by j-wsl** [comment]
Wrapping as a subprocess is the only way I can think of solving it - at the moment I'm only using a single page just grabbing `pages()[0]`, how would that make any difference?

**Comment by Sanqui** [comment]
A single page application doesn't involve using traditional links to traverse content, instead relying on JavaScript fetches of data and transforming the DOM (think Google Docs or Slack).  The fact that this error doesn't occur while working with one implies that it has something to do with the browser's handling of hyperlinks.  I don't have much information beyond that.

**Comment by Bitate** [comment]
> @Saranya-v60 I solved it for myself by a restart of a browser each some pages.

I just found that without restarting the browser but just creating a new page before jumping into that page will work.

**Comment by 1799** [comment]
Anyone has solution for this?

**Comment by Pashted** [comment]
> Anyone has solution for this?

you can try the solution, described there https://github.com/apify/apify-js/pull/1348
(launch with `--disable-site-isolation-trials` arg)
it fixed the same issue for me

but browsing may become less secure. google it.

**Comment by benjamins5335** [comment]
Bumping this as I am also getting this error. Does anyone know exactly what brings on the error? I know very little about the error message itself

**Comment by VedantGonnade** [comment]
In my case, the error was resolved by using "load" and providing a timeout of 3 seconds:
`await page.goto(<url>, { waitUntil: ["load", "domcontentloaded", "networkidle2"], timeout: 120000 });
                await page.waitForTimeout(3000);`

**Comment by qWazi-pro** [comment]
How can I remove it or not to stop the process? try-catch doesn't help

**Comment by OrKoN** [comment]
@ggorlen are you still able to reproduce this issue? Latest versions do not have that assertion anymore and I was not able to reproduce it using the script you provided.

**Comment by OrKoN** [comment]
Alright, thanks, I am going to mark this one as closed then. Please file a new issue if there is a reproducible example for a similar issue. It does sound like it was a race condition. There is a similarly sounding issue with a newer versions https://github.com/puppeteer/puppeteer/issues/11246 but I have troubles reproducing it.
