### ISSUE TITLE
Puppeteer Getting Redirected from Targeted Pages

### ISSUE THREAD

**Issue by PostAlmostAnything** [puppeteer/puppeteer#7051]
Some of the sites I am trying to scrape have a feature that redirects Puppeteer from the targeted pages to different pages. How do I stop that redirect and scrape the target pages?

I tried this, but it just terminates the thing if a redirection is detected. That is not good enough. I need to stop the redirect and scrape the targeted page:

await page.setRequestInterception(true);

page.on('request', request => {
  if (request.isNavigationRequest() && request.redirectChain().length !== 0) {
    request.abort();
  } else {
    request.continue();
  }
});

**Comment by C-Duv** [comment]
Same here, running with `node --trace-warnings` shows `UnhandledPromiseRejectionWarning: Error: net::ERR_FAILED at ...` errors.
