### ISSUE TITLE
Way to check if the page navigation is currently happening?

### ISSUE THREAD

**Issue by scythargon** [puppeteer/puppeteer#7055]
Hey! I've asked at SO, I've went through the documentation, googled a ton, but could not find a way to determine if the page is currently being loaded. The analogue of the "refresh button" state. If there is no such thing - may be you would not mind to give some clues where do I dig to implement such a thing and send a PR. Thank you.

**Comment by canonic-epicure** [comment]
Hi, try checking the `document.readyState` may be? https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

**Comment by scythargon** [comment]
That might work! Thank you!
