### ISSUE TITLE
Get 'timeout ' error if headless set to true

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#707]
`const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
  	headless:false
  });
  const page = await browser.newPage();

    
   browser.close();
})();`

when i change 'headless' to 'false' everything is 'ok'

actually,headless mode is too slow,it take 8minuites to open page
in full head mode only take 30sec

**Comment by Garbee** [comment]
This looks to be something with your system configuration or network. It runs in a sane amount of time for me.

<details>
<summay>Time with headless</summary>

```
~/test $ time -v node test.js
	Command being timed: "node test.js"
	User time (seconds): 1.91
	System time (seconds): 0.42
	Percent of CPU this job got: 28%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:08.31
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 105816
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 23077
	Voluntary context switches: 8359
	Involuntary context switches: 1178
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

</details>

<details>
<summary>Time without headless</summary>

```
~/test $ time -v node test.js
	Command being timed: "node test.js"
	User time (seconds): 5.02
	System time (seconds): 1.27
	Percent of CPU this job got: 63%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:09.84
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 204688
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 2
	Minor (reclaiming a frame) page faults: 108746
	Voluntary context switches: 22375
	Involuntary context switches: 6978
	Swaps: 0
	File system inputs: 0
	File system outputs: 11800
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

</details>

**Comment by aslushnikov** [comment]
@Luthfifs I can't repro this as well. It does look like something's going on with your environment.

Closing this for now. If there's a good reproduction scenario, feel free to write here.

**Comment by ghost** [comment]
Yeah,something wrong with my environment
I test in other computer ,everything is 'ok'

**Comment by corinblaikie** [comment]
I had the same issue, and it turned out to be proxy settings.

When headless: false was set, the system proxy settings went missing.

I resolved this by setting the `--proxy-server` arg

`browser = await puppeteer.launch({`
`        headless: true,        `
``        args: [`--proxy-server=${proxyServer}:${proxyPort}`]``
`      });`
