### ISSUE TITLE
page.screenshot() throws error if fullPage is set to true

### ISSUE THREAD

**Issue by RaresGeo** [puppeteer/puppeteer#7070]
* Puppeteer version: 8.0
* Platform / OS version: Windows 10
* Node.js version: 14.15.5

**What steps will reproduce the problem?**

If option.fullPage is true it will throw an error but work as expected if it is false.

```js
const options = {
    path: 'test.png',
    fullPage: false,
    clip: {
        x: 0,
        y: 400,
        width: 1000,
        height: 2500
    }
}


const puppeteer = require('puppeteer');
(async() => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.goto(start, {
        waitUntil: 'networkidle0',
    })
    await page.screenshot(options)
    await browser.close()
})();
```

This is where it runs into the issue: https://github.com/puppeteer/puppeteer/blob/13f73b5b3a279f18313630e0f58c3c17fb0cef66/lib/Page.js#L830

**What is the expected result?**
I expected it to simply take a screenshot of the full page

**What happens instead?**
Error: options.clip and options.fullPage are exclusive

**Comment by RaresGeo** [comment]
First time submitting an issue. I can't seem to get the code formatting to work.

**Comment by nik-here** [comment]
You have to delete the "clip" in options. You can use fullpage **or** clip, not both at the same time.

```js
const options = {
  path: 'test.png',
  fullPage: true,
};

const start = 'https://github.com';
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(start, {
    waitUntil: 'load',
  });
  await page.screenshot(options);
  await browser.close();
})();
```

**Comment by nik-here** [comment]
here is a link to format code on gihub: [Creating and highlighting code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

**Comment by RaresGeo** [comment]
Oh, exclusive as in mutually exclusive. I feel silly.
