### ISSUE TITLE
Page.goto response is null on some websites when using request interception

### ISSUE THREAD

**Issue by Schaka** [puppeteer/puppeteer#7073]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 6.0.0-8.0.0 (tried several, but this was a problem on older versions too)
* Platform / OS version: MacOS 11.2, Alpine/Debian Linux inside Docker
* Node.js version: 14.x-15.x, tried several

**What steps will reproduce the problem?**

Use the following class (typescript) create an instance, call the start method and observe the log. 
```
export class Crawler {

    public _browser: puppeteer.Browser;

    public async start(): Promise<void> {
        this._browser = await puppeteer.launch();

        for(var i=0; i<10; i++) {
            var response = await this.openPage('customer-user-agent', 'https://www.lights.ie/ceiling-lights/');
            this.logResult(response);
        }
    }

    public async openPage(userAgent: string, url: string): Promise<puppeteer.HTTPResponse> {
        const page: puppeteer.Page = await this._browser.newPage();
        await Promise.all([page.setUserAgent(userAgent), page.setViewport(VIEWPORT), page.setRequestInterception(true)]);

        page.on('request', (request: puppeteer.HTTPRequest) => request.continue());

        var response = await page.goto(url, {
            timeout: 60000,
            waitUntil: []
        });

        await page.waitForTimeout(5000);
        await page.close();

        return response;
    }

    private logResult(response: puppeteer.HTTPResponse) {
        if (response == null) {
            console.dir('Failure getting response');
        } else {
            console.dir('Successfully navigated to website');
        }
        return response;
    }
}
```

First of all, this does not seem to appear with all websites. It also seems that sometimes you can open the same URL twice or thrice before the error appears. But once it appears, it never goes away until you restart the browser. My best guess is a caching issue, but I couldn't find the problem. Without the `page.waitForTimeout`, the issue also doesn't seem to occur.

**What is the expected result?**
I should be able to receive the initial response the server sends.

**What happens instead?**
The response is null. I need both the final URL (after potential redirects) as well as the status code and in some cases the body of the initial response.

**Comment by Sharlaan** [comment]
Same issue with Node16, Puppeteer10, Windows10
against url
[original dynamic paginated url](https://www.p2r-expert.com/fr/63-pneumatiques#/manufacturer-michelin_m/page-3)
which resolves into :
[redirected url](https://www.p2r-expert.com/modules/blocklayered/blocklayered-ajax.php?layered_manufacturer_45=45&id_category_layered=63&orderby=relevance&orderway=desc&page_name=category&selected_filters=/manufacturer-michelin_m/page-3&_=1624974927452)

what solution to apply to `page.goto` ?

what happens is that it gets the first page properly, but fails to detects next ones (goto returns `null`),
leading to wrong behaviors like `page.waitForSelector` returning true while still being on previous page ...

My system is based on 2 loops :
- 1st main one generating 1 tab per targeted site (parallel process), calling browser.newPage
- 2nd one using same "site-tab" for the various tested pages (synchronous tests), calling page.goto
It works flawlessly for sites using "static" urls, but completely fails when one is using redirections ...

==>  what solution to apply to `page.goto` ?
