### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by haidang666** [puppeteer/puppeteer#7085]
**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: macos
* URLs (if applicable): any urls
* Node.js version: 12.21.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

This is related to tsconfig or webpack, cos it works without ts.
The way I use puppeteer
```node
async function getData(url, filePath) {
  const browser = await puppeteer.launch({
    headless: true,
  });
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle0' });
}
```

**What is the expected result?**
page loaded

**What happens instead?**
in electron
```node
index.js:118 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117)
    at Object.join (path.js:1039)
    at new BrowserFetcher (BrowserFetcher.js:161)
    at resolveExecutablePath (Launcher.js:441)
    at ChromeLauncher.launch (Launcher.js:78)
    at async getData (src.js:92)
```
in console
```unix
@nuclear/main:     main › renderer › TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
@nuclear/main:     at validateString (internal/validators.js:117:11)
@nuclear/main:     at Object.join (path.js:1039:7)
@nuclear/main:     at new BrowserFetcher (webpack:///./node_modules/@nuclear/core/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js?:161:22)
@nuclear/main:     at resolveExecutablePath (webpack:///./node_modules/@nuclear/core/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js?:441:28)
@nuclear/main:     at ChromeLauncher.launch (webpack:///./node_modules/@nuclear/core/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js?:78:57)
@nuclear/main:     at async getData (webpack:///./node_modules/@nuclear/core/node_modules/extract-sptf-playlist/src.js?:92:19)
```

**Comment by YTvW** [comment]
did you manage to fix this? I am running into this issue as well

**Comment by haidang666** [comment]
No I didn't, I don't use it with `ts`

**Comment by garethrhughes** [comment]
Currently getting this too.

**Comment by JiriTrecak** [comment]
Same, getting the issue when trying to run even the simplest script with TS:

```
(async () => {
  const browser = await puppeteer.launch();
})();
```

Tried with multiple node versions to no avail. Thank you for any help!

**Comment by garethrhughes** [comment]
I was getting this issue because it couldn't locate chromium. I originally had assumed it was expecting a URL when rendering a page from HTML.

**Comment by VictorGobel** [comment]
Also having this issue, any news ?

**Comment by codydaig** [comment]
Bumping this thread as I am having the exact same issue with no luck. 

Running the file directly with ts-node works, but running it within the entire application bundled by webpack fails.
