### ISSUE TITLE
Running Puppeteer is giving an error

### ISSUE THREAD

**Issue by Jassi10000-zz** [puppeteer/puppeteer#7088]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^8.0.0
* Platform / OS version: Windows
* URLs (if applicable): 
* Node.js version: v14.15.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.  I simply ran my  .js file with node and it gave me the error 
2. My file name is index.js  so after doing node index.js it's showing this error
3.

**What is the expected result?**
I expected that my automated code will run smoothly to give expected results

**What happens instead?**

I got this error :

Images for UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r856583 is guaranteed to work. at Timeout.onTimeout (C:\Users\dell\OneDrive\Desktop\Side Projects\My-Puppeteer-Projects\Project2\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:204:20) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7) (Use `node --trace-warnings ...` to show where the warning was created) (node:4368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:4368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by LuanPiresBresolla** [comment]
I have same problem. I'm not found a solution.
