### ISSUE TITLE
Feature Request: wait for selectors array (race)

### ISSUE THREAD

**Issue by avimar** [puppeteer/puppeteer#709]
I often wait for one of multiple possible selectors -- an success or error result. I'm assuming this is a pretty common use case. (It's a `race`, not `all`.)

I write a helper function like so:

`page.waitForFunction("document.querySelector('#email') || document.querySelector('#success')");`

Is there instead a way to do pass an array to `waitForSelector`?

Preferably, the `Promise` would return _which_ selector was available. Because I have to do figure that out too.

I'd offer to do a PR, but I can't figure out how `waitForSelector` works in the code...

**Comment by andrewodri** [comment]
I was just looking the code for `waitForFunction` and `waitForSelector` myself; from what I gather, refactoring `waitForSelector` to accept arrays would requiring introducing an additional parameter defining whether the the array of promises should be a race or all, and of course all the logic that goes along with it.

It looks like [waitForSelector ](https://github.com/GoogleChrome/puppeteer/blob/64124df62f4e81999fe1a0ab45c6fb9718a0e413/lib/FrameManager.js#L346) calls [waitForFunction](waitForFunction), which [returns the native Promise object from WaitTask](https://github.com/GoogleChrome/puppeteer/blob/64124df62f4e81999fe1a0ab45c6fb9718a0e413/lib/FrameManager.js#L422)... Would this be an acceptable solution?

```javascript
Promise.race([
    page.waitForSelector('#email'),
    page.waitForSelector('#success')
])
```

As far as returning the specific selector... it looks like promises are only resolved in `WaitTask` based on the boolean result of [predicateCode](https://github.com/GoogleChrome/puppeteer/blob/64124df62f4e81999fe1a0ab45c6fb9718a0e413/lib/FrameManager.js#L372). I'd be happy to put a PR together, but I'd like to ensure that it would be in harmony with the direction the team wants to go with this. (Disclaimer: I haven't contributed to this project yet :stuck_out_tongue:). Again, there is a workaround in the meantime, but it's ugly:

```javascript
let mappedSelectors= [
    page.waitForSelector('#email'),
    page.waitForSelector('#success')
].map(
    (currentValue, index) => currentValue.then(result => [index])
)
```

This essentially maps the index of the resolved promise, so that when you dump it into `Promise.race`, you'll get a resolved index. That should form a bit of basis until we get a little more direction of whether we want non-boolean promise resolution in `WaitTask` (and `helper.evaluationString`).

**Comment by avimar** [comment]
Thanks for the ideas!
I have to make sure I even know what you're doing with the promises there...

**Comment by twalpole** [comment]
A much simpler solution is to just use the CSS comma 

    page.waitForSelector('#email, #success')

**Comment by paulirish** [comment]
@twalpole nice solution. it'll look for all of those and match the first time there's a satisfactory element. 

https://github.com/GoogleChrome/puppeteer/blob/272fb4d9935552ff6eb1e6aae39b4f745cbed977/lib/FrameManager.js#L353-L361

**Comment by andrewodri** [comment]
@paulirish I have no idea on the project roadmap (or how lean puppeteer is intended to be), but is there any desire to resolve the the promise with the `remoteObject` returned by `document.querySelector`?

Just eyeballing it, but it seems like success variable in the `rerun` function would already have a copy of the serialized `remoteObject` in it.

https://github.com/GoogleChrome/puppeteer/blob/64124df62f4e81999fe1a0ab45c6fb9718a0e413/lib/FrameManager.js#L441-L474

**Comment by paulirish** [comment]
i don't make the call, but i personally wouldn't expect this feature to be landed.
seems better for an external "puppeteer plugin" module to introduce it.

**Comment by avimar** [comment]
My usual `waitForSelector` doesn't necessarilyl mean that I'll be working with that selector. But sometimes I do.
What are the considerations for landing something like this? Returning the element would surely provide a truthy result. So, is there a performance consideration?

**Comment by avimar** [comment]
What is this "puppeteer plugin" module you mention? Is there some mechanism/best practice for releasing supplemental functions?

**Comment by aslushnikov** [comment]
@andrewodri we're considering returning result values from `page.waitForSelector` and `page.waitForFunction`.

**Comment by aslushnikov** [comment]
@avimar you can do a module with a peer dependency to puppeteer.

**Comment by techsin** [comment]
It should be possible to wait for n selectors and know which one showed up. Lot of times you want to write logic if this then this else if this then this. right now i just wait for selector to time out.  Also im using xpath selector to instead of comma I use | ch

**Comment by charlieclark** [comment]
@techsi I've been using this to conditionally run behavior based on which selector matches first:

```javascript
const raceSelectors = (page, selectors) => {
  return Promise.race(
    selectors.map(selector => {
      return page
        .waitForSelector(selector, {
          visible: true,
        })
        .then(() => selector);
    }),
  );
};

...

const selector = await raceSelectors(page, ['#foo', '#bar']);

if (selector === '#foo') {
  // do something
} else if (selector === '#bar') {
  // do something else
}
```

**Comment by jelizarovas** [comment]
> @techsi I've been using this to conditionally run behavior based on which selector matches first:
> 
> ```js
> const raceSelectors = (page, selectors) => {
>   return Promise.race(
>     selectors.map(selector => {
>       return page
>         .waitForSelector(selector, {
>           visible: true,
>         })
>         .then(() => selector);
>     }),
>   );
> };
> 
> ...
> 
> const selector = await raceSelectors(page, ['#foo', '#bar']);
> 
> if (selector === '#foo') {
>   // do something
> } else if (selector === '#bar') {
>   // do something else
> }
> ```

I'm very surprised this hasn't been referenced anywhere else. I think it is the cleanest solution. Reason i try to use puppeteer is so i can access websites, input data and expect results. I was tearing my hair for months that I couldn't find anywhere if this selector loads do this, and if other do that. I had implemented Promise.any approach, but it was just so messy. Thumbs up for this one, thank you @charlieclark

**Comment by KhanhHH** [comment]
> @techsi I've been using this to conditionally run behavior based on which selector matches first:
> 
> ```js
> const raceSelectors = (page, selectors) => {
>   return Promise.race(
>     selectors.map(selector => {
>       return page
>         .waitForSelector(selector, {
>           visible: true,
>         })
>         .then(() => selector);
>     }),
>   );
> };
> 
> ...
> 
> const selector = await raceSelectors(page, ['#foo', '#bar']);
> 
> if (selector === '#foo') {
>   // do something
> } else if (selector === '#bar') {
>   // do something else
> }
> ```
Great, work like a charm. Why docs doesn't mention this, lol 🤣

**Comment by matheusdalteixeira** [comment]
> Uma solução muito mais simples é usar apenas a vírgula CSS
> 
> ```
> page.waitForSelector('#email, #success')
> ```

não funciona no meu

**Comment by louisho5** [comment]
> @techsi I've been using this to conditionally run behavior based on which selector matches first:
> 
> ```js
> const raceSelectors = (page, selectors) => {
>   return Promise.race(
>     selectors.map(selector => {
>       return page
>         .waitForSelector(selector, {
>           visible: true,
>         })
>         .then(() => selector);
>     }),
>   );
> };
> 
> ...
> 
> const selector = await raceSelectors(page, ['#foo', '#bar']);
> 
> if (selector === '#foo') {
>   // do something
> } else if (selector === '#bar') {
>   // do something else
> }
> ```

The best solution found so far. It works in almost all situations. Thank you!
