### ISSUE TITLE
userDataDir doesn't keep credentials "/Default/Login Data" and cookies "/Default/Cookies" across two windows users

### ISSUE THREAD

**Issue by landaida** [puppeteer/puppeteer#7091]
Hi created a profile using puppeteer userDataDir and work perfect but the idea is open the same profile from multiple windows user session using "windows enterprise multisession with RDP" but when a second user try to open the share "profile" (not simultaneously) the both file are recreated ("Login Data" and "Cookies"), only the windows user that I used to create the profile can access the credentials and cookies, some idea how can solved this?

**Comment by tyurin-ilya** [comment]
Same issue. I try to copy userDataDir folder to second windows PC, but no data saves when open puppeteer...
How to transfer browser data from one PC to another?
