### ISSUE TITLE
[TypeScript] Using `waitForResponse` with a predicate causes `TS7006: Parameter 'response' implicitly has an 'any' type.` error

### ISSUE THREAD

**Issue by TonalidadeHidrica** [puppeteer/puppeteer#7093]
I suggest changing the signature of `waitForResponse` from
```typescript
    waitForResponse(urlOrPredicate: string | Function, options?: {
        timeout?: number;
    }): Promise<HTTPResponse>;
```
to something like 
```typescript
    waitForResponse(urlOrPredicate: string | ((response: HTTPResponse) => boolean | Promise<boolean>), options?: {
        timeout?: number;
    }): Promise<HTTPResponse>;
```
as the current type definition causes `any` error.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: MacOS Big Sur 11.2.3
* URLs (if applicable):
* Node.js version: 15.13.0
* TypeScript version: 4.2.4

**What steps will reproduce the problem?**

```typescript
import { Page } from "puppeteer";

const myFunction = (page: Page) => {
    await page.waitForResponse(response => response.url().contains("wonderful.domain"));
}
```
It is expected to compile without error.

**What happens instead?**

`TS7006: Parameter 'response' implicitly has an 'any' type.`

**Comment by TonalidadeHidrica** [comment]
So I should send a PR as long as I remember it...

**Comment by TonalidadeHidrica** [comment]
But I didn't remember it...

**Comment by OrKoN** [comment]
Does it still reproduce? there have been a lot of TypeScript work done, including the strict mode which is on by default now.

**Comment by TonalidadeHidrica** [comment]
I didn't check it recently because it's been long since I needed puppetter the last time.   Do I need to close the issue until I reconfirmed that the issue still persits?

**Comment by OrKoN** [comment]
Yes, please re-open if it's still an issue for you as I don't seem to be able to reproduce it with the latest version.
