### ISSUE TITLE
Not launching chrome

### ISSUE THREAD

**Issue by iwantpizza10** [puppeteer/puppeteer#7095]
So, my laptop is a **school** laptop, and um...

Any app is blocked, unless it's in the `appdata` folders (or in a flash drive)
I can't figure out where the declaration of the `chrome.exe` is, so I can't run it, and I also can't move the app to let it run (causes more errors...

Can someone tell me what file the declaration is? Please tell me

**Comment by muskan3006** [comment]
if you are using puppeteer I don't think you need to give the path for chrome.exe
and if you are using puppeteer-core 
you can install it, using `npm install chromium` and then as a launchargument you can give it's path.
The chromium will be at following path: `node_modules/chromium/lib/chromium/chrome-win/chrome.exe`

It will look something like this
`let browser = await puppeteer.launch({ executablePath: launchArgument, headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu'] });`
where launchargument should be relative path to chromium path mentioned above.

I hope this helps you and this is what you were asking.
