### ISSUE TITLE
Property 'createBrowserFetcher' does not exist on type 'typeof puppeteer'

### ISSUE THREAD

**Issue by muuvmuuv** [puppeteer/puppeteer#7100]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8
* Platform / OS version: macos 11.2.3
* URLs (if applicable):
* Node.js version: 14.x

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Typescript file
2. `const browserFetcher = puppeteer.createBrowserFetcher()`
3. Property 'createBrowserFetcher' does not exist on type 'typeof import("/Volumes/Development/aqua-filter/node_modules/puppeteer/lib/types")'.ts(2339)

**What is the expected result?**

Correctly exported

**What happens instead?**

```
Property 'createBrowserFetcher' does not exist on type 'typeof import("/Volumes/Development/aqua-filter/node_modules/puppeteer/lib/types")'.ts(2339)
```

**Comment by baruchiro** [comment]
After a high-level bisect, it seems the problem is between `v7.0.3` (good) and `v7.1.0` (bad).

https://github.com/puppeteer/puppeteer/compare/v7.0.3...v7.1.0

I can't continue my research. I wanted to bisect each commit with `npm link`, but I can't build in Windows.

**Update:**

I bet on this commit: 6a0eb7841fd82493903b0b9fa153d2de181350eb

**Comment by atjn** [comment]
FYI this seems to affect all functions defined in the [`NodePuppeteer`](https://github.com/puppeteer/puppeteer/blob/d70f60e0619b8659d191fa492e3db4bc221ae982/src/node/Puppeteer.ts#L68) interface. The best workaround I found, is to manually tell TypeScript to load the extra definitions:
```js
const browserFetcher = ((puppeteer as unknown) as puppeteer.PuppeteerNode).createBrowserFetcher();
```

**Comment by thw0rted** [comment]
No idea why you got downvoted, I suggested the same fix over in #6899 .  I haven't had time to put together a reproduction but I think it's a bug introduced in the type changes that Baruch linked to above.  For some reason when I `const puppeteer = require("puppeteer")` in a JS file, VSCode gets the right type info, but when I `import puppeteer = require("puppeteer");` in a TS file it types as Puppeteer (and is missing those other methods).

I realized that the TS file where I had the problem actually had very little type information, so I just changed it to JS and added 2-3 inline JSDoc annotations for the same effect.  I'd still like to see the issue solved, though.

**Comment by muuvmuuv** [comment]
@thw0rted should have better commented. I just don`t like such workarounds. And they are obvious if you want to ignore it.

**Comment by atjn** [comment]
If anybody wants to see this running in a real codebase, I just added it to pwa-asset-generator:

https://github.com/onderceylan/pwa-asset-generator/blob/cc9cbf2676417d16fbd32d4d866089861f8d600d/src/helpers/installer.ts#L30-L33

You can trigger this code by running `npm run build`. It will work fine as-is, but if you remove the workaround, it fails.

We are currently using version 9.1.1, but I also tested it on the latest version as of writing (10.1.0) and it still failed.

**Comment by creemy0cheesekake** [comment]
Adding a file called `puppeteer.d.ts` with the following contents:
```
import puppeteer from "puppeteer";
declare module "puppeteer" {
	class Puppeteer {
		constructor();
	}
	export = Puppeteer as unknown as puppeteer.PuppeteerNode;
}

```
fixed it for me :)

**Comment by Alireza17224** [comment]
Same issue here

**Comment by OrKoN** [comment]
`createBrowserFetcher` is no longer part of Puppeteer's API.

**Comment by MuratColyaran** [comment]
@OrKoN did they announced any replacement for `createBrowserFetcher ` ?
