### ISSUE TITLE
How can we enter our User Id and Password in a windows Popup using Puppeteer?

### ISSUE THREAD

**Issue by sindhujabanka** [puppeteer/puppeteer#7104]
<img width="768" alt="loginPage" src="https://user-images.githubusercontent.com/48412579/115226383-ce7f1500-a12c-11eb-89f7-d8e2f857e6a4.png">

After the page is redirected I was not able to generate a pdf as I was not able to mention my User Id and password in the windows popup dialog box as mentioned in the image.

Tried to use "await page.keyboard.type('xyz@abc.com');" but the text is not getting dumped into the Username field.
How can we enter our details in that dialog box in order to move to the next page?
Looking for help if we have any another way of entering our details in the windows popup and proceeding further?

**Comment by subhendu-de** [comment]
The following code solves the issue.

```javascript
const puppeteer = require('puppeteer');
(async () => {
    const baseUrl = 'http://abc.com/';	
	const browser = await puppeteer.launch({headless: false});
	const context = await browser.createIncognitoBrowserContext();
	const page = await context.newPage();	

    function delay(time) {
	    return new Promise(function(resolve) { 
        setTimeout(resolve, time)
	    });
	}

	await page.goto(baseUrl);

	await page.waitForSelector('[name="logindata"]');
	await page.type('[name="logindata"]', 'sampleuser@abc.com');
	await page.click('[type="submit"]');
	delay(1000);
        await page.authenticate({username: `sampleuser@abc.com`, password: `xxxxxxxxx`});

    await delay(20000); 
    await page.goto(baseUrl + 'data/'+ Id +'/samples/todo')
    await delay(20000); 
    await page.pdf({ path: 'todosamples.pdf', format: 'a4' });

    browser.close();
})()
```

**Comment by sindhujabanka** [comment]
The above code solves the given issue.
Thank You @subhendu-de
