### ISSUE TITLE
Ubuntu puppeteer 'executablePath' and launch issue

### ISSUE THREAD

**Issue by mityok** [puppeteer/puppeteer#711]
I'm running puppeteer on ubuntu and i'm having issue with the latest chromium (62.0.3188.0) the puppeteer installs, for some reason it doesn't support ffmpeg, i've tried to use other revisions and pointing it to another (chrome) installation via 'executablePath'. but then the puppeteer just launches the browser and gets stuck on the launch.

any help would be greatly appreciated

**Comment by ebidel** [comment]
Chromium doesn't support codecs like mp3 out of the box. You'll need an official distribution for that. 

In the past, I've had success on ubunutu with the latest chrome package (chrome 62 now):

```sh
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
apt-get update &&\
apt-get install -y google-chrome-unstable
```

You're using `browser.launch({executablePath: 'google-chrome-unstable'});`?

**Comment by mityok** [comment]
thank you! that really solved it.

**Comment by Garbee** [comment]
MP3 support should be coming to Chromium soon though. The patents have now expired to it. Not sure when the work on that is planned (having a hard time finding the issue in crbug.) But, Google Legal as I understand it has approved bringing it to the open-source side.

EDIT:

And found the [tracking issue](https://bugs.chromium.org/p/chromium/issues/detail?id=746579) on MP3 coming to chromium. For posterity. This doesn't really help the immediate issue now though, but in the future at least it won't be a problem in this context.
