### ISSUE TITLE
Use Uint8Array instead of Node `Buffer`

### ISSUE THREAD

**Issue by lucacasonato** [puppeteer/puppeteer#7115]
In multiple places (for example the return type of `screenshot()` or `pdf()`, a Node `Buffer` is returned. This is unfortunate, because `Buffer` is not portable outside of Node, for example when running in the browser, or in Deno. It would be very cool if puppeteer used the web standard Uint8Array for all byte slices, instead of using `Buffer`.

This change should be relatively trivial to implement, in fact I have already done it in http://deno.land/x/puppeteer. Is there any interest for me to upstream this change?

Thanks!

**Comment by WGH-** [comment]
If it's just a change from `Buffer` to `Uint8Array`, why not?

**Comment by philc** [comment]
Bump. @lucacasonato 's Puppeteer Deno port has drifted from upstream (v9 vs. v13.6). It would be great to merge in the Uint8Array modifications so the two projects require far fewer modifications to keep in sync.

**Comment by OrKoN** [comment]
I think the change makes sense, and I will be happy to review a PR on this! (thanks for the ping)
