### ISSUE TITLE
page.setExtraHTTPHeaders not working

### ISSUE THREAD

**Issue by SkeLLLa** [puppeteer/puppeteer#713]
### Steps to reproduce

* Puppeteer version: latest
* Platform / OS version: linux

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. call `page.setExtraHTTPHeaders({'x-my-header': '1'})` assuming page is apropriate object

**What is the expected result?**
Puppeteer will set extra headers

**What happens instead?**
```
Exception is thrown
TypeError: undefined is not a function
    at new Map (native)
    at NetworkManager.setExtraHTTPHeaders (.../node_modules/puppeteer/lib/NetworkManager.js:53:30)
    at Page.setExtraHTTPHeaders
```
### Steps to fix

Change documentation according to code:
```
page.setExtraHTTPHeaders([
   ['x-my-header', '1'],
]);
```

Or change puppeteer code according to docs in order to support objects as parameters.

PS: 
```
page.setExtraHTTPHeaders([
   ['x-my-header', '1'],
]);
```
not throwing exception, but it seems that it doesn't work as described in docs (the header isn't added to request).

**Comment by aslushnikov** [comment]
@SkeLLLa Puppeteer 0.10.2 started using objects instead of maps for headers: https://github.com/GoogleChrome/puppeteer/releases/tag/v0.10.2

You probably use Puppeteer < 0.10.2?

**Comment by SkeLLLa** [comment]
I'll check it again, but if it's a definitely breaking change why "patch" version changed?

**Comment by aslushnikov** [comment]
@SkeLLLa that's by mistake. Next time we'll bump minor in this kind of situation. Sorry about the inconvenience!

**Comment by aslushnikov** [comment]
@SkeLLLa any updates on this?

**Comment by SkeLLLa** [comment]
I've checked for object - now it's ok. But never the less extra headers aren't passed to requests. The code is pretty simple:
```js
      const page = await browser.newPage();
      await page.setExtraHTTPHeaders(
        {'x-update': 1},
      );
      await page.setUserAgent('Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)');
      await page.goto(url);
```

Setting useragent is working well, but http headers missing.

**Comment by aslushnikov** [comment]
@SkeLLLa thanks, I can repro. This happens because `page.setExtraHTTPHeaders` expects only strings as header values.

I've sent a patch that validates this precondition and clarifies documentation. (#781)

**Comment by SkeLLLa** [comment]
@aslushnikov I've tried with strings as well (I mean `'1'`). And it not worked too.

**Comment by aslushnikov** [comment]
@SkeLLLa how exactly it didn't work for you? The following test passes for me (to run the test, add it to the `test/test.js`):

```js
    fit('should work', SX(async function() {
      await page.setExtraHTTPHeaders({
        'x-update': '1'
      });
      await page.setUserAgent('Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)');
      const [request] = await Promise.all([
        server.waitForRequest('/empty.html'), // wait for server to receive request
        page.goto(EMPTY_PAGE),
      ]);
      expect(request.headers['x-update']).toBe('1');
    }));
```

**Comment by SkeLLLa** [comment]
I've rechecked and now it's working. But on prevoius version with maps it not worked. Thanks.

**Comment by NoahCardoza** [comment]
This seems to be broken again with Firefox. (#6221)
