### ISSUE TITLE
Puppeteer process wont exit.

### ISSUE THREAD

**Issue by codenoid** [puppeteer/puppeteer#715]
hi, i run `node mypuppeteerapp.js` from another app (looping app), and when puppeteer has finished the process, he doesn't exit the process, and just like, like i run some process with `&` , thanks

**Comment by codenoid** [comment]
```
(node:20068) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: waiting failed: timeout 30000ms exceeded
(node:20068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
.
 `with a non-zero exit code.` 
.
.
and nothing

**Comment by ebidel** [comment]
We'll need more details. Code that reproduces the issue would be helpful.

**Comment by aslushnikov** [comment]
@codenoid looks like you hit exception and the script fails to complete (so `browser.close()` is never run).

**Comment by codenoid** [comment]
```
'use strict';
const puppeteer = require('puppeteer');
const request = require('request');
const fs = require('fs');

if (process.argv.length < 3) { 
  console.log('Usage: node ' + process.argv[1] + ' URL');
  process.exit(1);
}

var url = process.argv[2];
run(url);

function send(sentedData) {
  if(sentedData){
    request.post(config.url.apiurl, {form:{data:sentedData}});
  }
}

function run(url) {
  (async() => { // puppeteer async function
    const browser = await puppeteer.launch(({args: ['--no-sandbox', '--disable-setuid-sandbox']}));
    const page = await browser.newPage();
    await page.goto(url, {waitUntil: 'networkidle',timeout: 50000}); 
    await page.waitForSelector('.someselector');
    const links = await page.evaluate(() => {
      const anchors = Array.from(document.querySelectorAll('.someselector'));
      return anchors.map(anchor => anchor.href); 
    });
    links.forEach(function(v) {
      ts = v
      send(ts);
    });
    browser.close(); 
  })();
}
```
both in OSX & Ubuntu

**Comment by aslushnikov** [comment]
the `await page.waitForSelector('.someselector');` doesn't ever succeeds unless your website has an element matching the selector.

This causes the function to throw. As a result, `browser.close()` never happens.

**Comment by codenoid** [comment]
oh, thanks @aslushnikov  i'll try

**Comment by codenoid** [comment]
@aslushnikov i just remove that await selector, but it's same, , puppeteer wont exit.,
```
Running Process
Running Process
(node:36736) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 50000ms exceeded
(node:36736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@codenoid please post exact code that doesn't work for you

**Comment by codenoid** [comment]
@aslushnikov related to #740  , my code :https://gist.github.com/codenoid/54d10dd7dd783f94fe35dc94f423927a

**Comment by syabro** [comment]
I've wrapped the code into and now it doesn't hang
```javascript
try {
  // do your stuff here

} catch(e) {
  console.log(e)
  process.exit()
}
finally {
  browser.close()
}
```

**Comment by ArtixZ** [comment]
@syabro I'm having this issue as well. But the browser acutally is successfully closed. Still the function doesn't exit.

**Comment by itayalon** [comment]
> @syabro I'm having this issue as well. But the browser acutally is successfully closed. Still the function doesn't exit.

Hi @ArtixZ, any luck with the issue? i'm having the same problem

**Comment by szymond** [comment]
I am having similar problem. I am running Puppeteer on window's ubuntu VM. I am running some example code which only does a screenshot (it works), but the process won't finish. For me problem solves adding ` '--no-zygote', '--single-process'` as launch parameters.
