### ISSUE TITLE
retry feature ?, (puppeteer won't run after hit timeout in goto() )

### ISSUE THREAD

**Issue by codenoid** [puppeteer/puppeteer#716]
hi, i run `node mypuppeteerapp.js` from another app (looping app), and when my puppeteer hit the timeout, he showing a message then nothing else happens, and the following process are not run

**Comment by dcy0701** [comment]
+1
but `async ` is  inconvenient for retry

**Comment by aslushnikov** [comment]
@codenoid if there's a timeout, then you should handle it gracefully.

It's hard to say anything more than that since there's no repro and no code.

**Comment by codenoid** [comment]
@aslushnikov btw, how to disable async in puppeteer ?
