### ISSUE TITLE
self signed certificate in certificate chain Error during install

### ISSUE THREAD

**Issue by d-dipalma** [puppeteer/puppeteer#7167]
* Puppeteer version: 5.5.0
* Node.js version: v12.13.1

**What steps will reproduce the problem?**

npm install puppeteer

**What is the expected result?**

Install Puppeteer without errors.

**What happens instead?**

npm ERR! code 1
npm ERR! path E:\BitBucket\test\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r818858! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: self signed certificate in certificate chain
npm ERR!     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
npm ERR!     at TLSSocket.emit (events.js:210:5)
npm ERR!     at TLSSocket._finishInit (_tls_wrap.js:794:8)
npm ERR!     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
npm ERR!   code: 'SELF_SIGNED_CERT_IN_CHAIN'
npm ERR! }

We would like to install Chromium as part of the install, so we do not want to set the "PUPPETEER_SKIP_DOWNLOAD" variable.

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.
