### ISSUE TITLE
How to use Browser.downloadProgress?

### ISSUE THREAD

**Issue by kazaff** [puppeteer/puppeteer#7173]
Env:
* Puppeteer version:  9.0.0
* Platform / OS version: win10 64bit
* Node.js version: 16.0.0

Hi, there.
I need to wait for the download completed, then close the browser.
But as you guessed, I can not get a notification about this.

In Chrome DevTools Protocol, I see `Browser.downloadProgress` event, But I can not find any more details.
Can anyone give me some code fragments?

Thanks all.

**Comment by kazaff** [comment]
```javascript
...
let DOWNLOAD:number = 0;
let session:puppeteer.CDPSession = await browser.target().createCDPSession();
    session.on('Browser.downloadWillBegin', ()=>{
        DOWNLOAD++;
    });
    session.on('Browser.downloadProgress', (event:{guid:string, totalBytes:number, receivedBytes:number, state:string}):void=>{
        if(event.state == 'completed' || event.state == 'canceled'){
            DOWNLOAD--;
        }
    });
...
```

I am sure the code above does not work.

I can't even.

**Comment by ZekeLu** [comment]
It seems that it is a bug in the browser that the `Browser.downloadWillBegin` and `Browser.downloadProgress` events are not emitted. I have filed a bug here:  https://bugs.chromium.org/p/chromium/issues/detail?id=1204880 .

As of now, the workaround is to listen to the `Page.downloadWillBegin` and `Page.downloadProgress` events.

**Comment by ZekeLu** [comment]
It turned out that this is not a bug. I sent the `Browser.setDownloadBehavior` to the wrong target.

If you haven't sent the `Browser.setDownloadBehavior` command, you should send it first.

```js
const browser = await puppeteer.launch({executablePath: '/path/to/the/browser'});
const session = await browser.target().createCDPSession();
await session.send('Browser.setDownloadBehavior', {
    behavior: 'allowAndName',
    downloadPath: '/tmp',
    eventsEnabled: true
});
```

**Comment by aliraza948** [comment]
import {launch} from 'puppeteer'
(async ()=>{
    const b=await launch({headless:false})
    const p=await b.newPage()
    const l="hg"
    await p.goto('https://www.google.com')
    const pc=await p.createCDPSession()
    let session = await b.target().createCDPSession();
    let DOWNLOAD = 0;
    await session.send('Browser.setDownloadBehavior', {
        behavior: 'allowAndName',
        downloadPath: '/pny',
       eventsEnabled:true
    });
    session.on('Browser.downloadWillBegin', ()=>{
        DOWNLOAD++;
        console.log('start ')
    })
    session.on('Browser.downloadProgress', (event)=>{
        if(event.state == 'completed' || event.state == 'canceled'){
            DOWNLOAD--;
            console.log("it's done")
        }
    });

      await p.goto('https://www.google.com')

})()
it's working well as event listener for download

**Comment by Yzedank** [comment]
Aha

**Comment by Yzedank** [comment]
> `import {launch} from 'puppeteer' (async ()=>{ const b=await launch({headless:false}) const p=await b.newPage() const l="hg" await p.goto('https://www.google.com') const pc=await p.createCDPSession() let session = await b.target().createCDPSession(); let DOWNLOAD = 0; await session.send('Browser.setDownloadBehavior', { behavior: 'allowAndName', downloadPath: '/pny', eventsEnabled:true }); session.on('Browser.downloadWillBegin', ()=>{ DOWNLOAD++; console.log('start ') }) session.on('Browser.downloadProgress', (event)=>{ if(event.state == 'completed' || event.state == 'canceled'){ DOWNLOAD--; console.log("it's done") } }); await p.goto('https://www.google.com') })()`
> 
> it's working well as event listener for download

```javascript

```
