### ISSUE TITLE
The test "Page.click - should double click the button" is repeatedly failing for Firefox on main

### ISSUE THREAD

**Issue by jschfflr** [puppeteer/puppeteer#7175]
One example invocation: https://github.com/puppeteer/puppeteer/runs/2448603012?check_suite_focus=true
@whimboo Could you take a look at this?

**Comment by whimboo** [comment]
@jschfflr do you know when this exactly started to fail and how often it fails? Also due to the missing details for this failure in CI it's hard to see what exactly is broken here. Is there a chance to get a more detailed report? When running this test locally on Mac it works all fine, and I cannot get it to fail.

**Comment by jschfflr** [comment]
When looking at https://github.com/puppeteer/puppeteer/actions, the last succeeding run was https://github.com/puppeteer/puppeteer/actions/runs/773433539 which enabled a single test on ff. 
I'm also not experiencing any problems locally but I'll try to revert that and see if it works on the bot.

**Comment by jschfflr** [comment]
Testing on https://github.com/puppeteer/puppeteer/pull/7182

**Comment by whimboo** [comment]
@jschfflr I assume that triggering any job right now would still get a recent Firefox Nightly build. So maybe we could run a job purely with this affected test enabled (`it.only`), and enable `dumpio` and setting the Firefox preference `remote.log.level=Trace`. That should give enough information to hopefully identify the problem.

When I read the output correctly the failure is that only a single click is tracked?

**Comment by jschfflr** [comment]
@whimboo There is now a run with tracing enabled: 
https://github.com/puppeteer/puppeteer/pull/7182/checks?check_run_id=2464956662
Can you take this from here?

**Comment by whimboo** [comment]
Interesting. So previously it failed for both Windows and MacOS, but with the above job and tracing enabled the job now passed on MacOS.

First I thought the MacOS issue might have been related to our recently landed support for [double-tap to zoom](https://bugzilla.mozilla.org/show_bug.cgi?id=674371) in Firefox Nightly. But given that it works now the problem should be different.

I just triggered again to see if the status stays the same.

I'm kinda swamped with work right now, but I will try to figure that out. I will try at least locally with a Surface book if I can reproduce it on Windows.

**Comment by whimboo** [comment]
@jschfflr I re-run the complete set of tests across platforms multiple times via Github actions, but I was not able to get any failures at all. Do you remember how often this particular test was failing?

Maybe only running this single test makes it just work. Or the extra logging output invalidates a possible race condition.

**Comment by jschfflr** [comment]
Hmm, that's interesting. I triggered a new run of something that landed on main already but failed in CQ:
https://github.com/puppeteer/puppeteer/actions/runs/788429853 let's see if the problem persists or if it solved itself.
In the meantime, I'll also trigger a test run without the tracing.

**Comment by jschfflr** [comment]
I changed the cl to disable the test for firefox for now to get the main working again. We can then investigate further on a separate branch.

**Comment by whimboo** [comment]
So it means it's still failing. In that case I'll try to find some time next week to have a look if I can reproduce it.

**Comment by whimboo** [comment]
I assume the PR that disables the test is #7182.

**Comment by jschfflr** [comment]
@whimboo Yes, that's right. I wanted to add you as a reviewer but selected the wrong account instead -.-
The issue still persists - it's just disabled now. Therefore I'm opening this issue again.

**Comment by jschfflr** [comment]
It looks like there is another test with clicks failing on Firefox now: https://github.com/puppeteer/puppeteer/runs/2492271033?check_suite_focus=true.
I'll disable that one too. 
Let me know how I can help you resolve these failing tests!

**Comment by whimboo** [comment]
We got the same failure now in our own CI:
https://bugzilla.mozilla.org/show_bug.cgi?id=1711743

Lets see how often it actually happens and maybe I have a chance to finally investigate the problem.

**Comment by jschfflr** [comment]
Thanks for keeping an eye out on this!

**Comment by whimboo** [comment]
I've identified the problem and a fix is coming along via https://bugzilla.mozilla.org/show_bug.cgi?id=1740798. Once fixed I'll re-enable the disabled tests.

**Comment by whimboo** [comment]
That is actually fixed. Closing the issue.
