### ISSUE TITLE
Unable to catch exceptions when headless is turned off

### ISSUE THREAD

**Issue by adamblok** [puppeteer/puppeteer#718]
Hello,

There is a simple code:

```javascript
(async () => {
    try {
        const browser = await puppeteer.launch({
            headless: true
        });
        const page = await browser.newPage();
    
        await page.goto('http://example.com');

        browser.close();
    } catch (error) {
        console.log(error);
    }
})();
```

And in case of any error I still have message about **unhandled promise rejection**.

Interesting fact is that, when I turn off the headless mode, everything works well then. It looks like a bug.

**Comment by aslushnikov** [comment]
@adamblok can you please paste a snippet that produces this `unhandled promise rejection`?

**Comment by adamblok** [comment]
Sure, here you are:

```javascript
const puppeteer = require('puppeteer');

(async () => {
    try {
        const browser = await puppeteer.launch({
            headless: true
        });
        const page = await browser.newPage();

        page.on('response', request => {
            console.log(request);

            // do some stuff
            throw 'invalid response';
        });

        await page.goto('http://example.com');

        browser.close();
    } catch (error) {
        console.log(error);
    }
})();
```

And the result is:
https://www.screencast.com/t/KK6GzsxN

**Comment by aslushnikov** [comment]
@adamblok this code yields "unhandled promise rejection" regardless of chrome being in headless or headful mode.

The try-catch statement you put will catch exceptions thrown by one of the `await` calls.
You, however, throw inside an event listener, which is executed asynchronously, so noone handles it.
