### ISSUE TITLE
Can't install puppeteer@5.5.0 on a Macbook with M1 chip

### ISSUE THREAD

**Issue by faresd** [puppeteer/puppeteer#7180]
### Steps to reproduce

Simple, when trying to Install puppeteer@5.5.0 such as "npm install puppeteer@5.5.0" in an empty project on an M1 MacBook you get this error:

`npm install puppeteer@5.5.0

npm ERR! code 1

npm ERR! path /Users/patrick/Code/node_modules/puppeteer

npm ERR! command failed

npm ERR! command sh -c node install.js

npm ERR! The chromium binary is not available for arm64:`

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version:  macos
* URLs (if applicable):
* Node.js version: Node 14 and 15 with nvm.

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.npm install puppeteer@5.5.0
2.
3.

**What is the expected result?**
install correctly

**What happens instead?**

`npm install puppeteer@5.5.0

npm ERR! code 1

npm ERR! path /Users/patrick/Code/node_modules/puppeteer

npm ERR! command failed

npm ERR! command sh -c node install.js

npm ERR! The chromium binary is not available for arm64:`

**Comment by ghost** [comment]
https://stackoverflow.com/questions/65928783/puppeteer5-5-0-install-node-install-js-on-m1

**Comment by davidbielik** [comment]
@faresd I'm able to get Puppeteer running on an M1 (though not such an old version of 5.5)

For Docker, try and specify the platform in your `Dockerfile`

```
FROM --platform=linux/amd64 node:16
```

If you're not using Docker, you can try following a guide like this: https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/

I'm having trouble actually opening pages in Docker and opened #7916
