### ISSUE TITLE
response does not contain count values in production mode

### ISSUE THREAD

**Issue by warlock1996** [puppeteer/puppeteer#7184]
Hi, 

just started using pupeteer
I have a scraping code which gets the follower count from facebook and instagram from the url i send with request body

everything works fine locally, but when i move it heroku or google app engine , its giving a success response without facebook or instagram follower count !

i have tried almost everything ! i just can't figure out what is the issue here in production!

`app.post("/followers", getFollowers);`

handler is 👇 

`exports.getFollowers = async (req, res, next) => {
  let facebook_followers, instagram_followers;

  try {
    if (!req.body.facebookURL || !req.body.instagramURL) {
      return res.json({
        message: "must include facebook and instagram urls in request body.",
      });
    }

    const browser = await puppeteer.launch({
      headless: true,
      timeout: 9000,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const facebook = await browser.newPage();
    const instagram = await browser.newPage();

    facebook.on("console", (msg) => {
      for (let a = 0; a < msg.args.length; ++a)
        console.log(`${a}: ${msg.args[a]}`);
    });
    instagram.on("console", (msg) => {
      for (let b = 0; b < msg.args.length; ++b)
        console.log(`${b}: ${msg.args[b]}`);
    });

    await facebook.goto(req.body.facebookURL);
    await instagram.goto(req.body.instagramURL);

    const spanElements = await facebook.$$("span");
    const spans = await instagram.$$("a");
    for (let j = 0; j < spanElements.length; j++) {
      const element = spanElements[j];
      const txt = await facebook.evaluate(
        (element) => Promise.resolve(element.textContent),
        element
      );
      console.log(txt);
      if (txt.includes("followers")) {
        facebook_followers = txt.split(" ")[0];
      }
    }

    for (let i = 0; i < spans.length; i++) {
      const element_i = spans[i];
      const txt_i = await instagram.evaluate(
        (element_i) => Promise.resolve(element_i.textContent),
        element_i
      );
      console.log(txt_i);
      if (txt_i.includes("followers")) {
        instagram_followers = txt_i.split(" ")[0];
      }
    }
    await browser.close();
    return res.json({
      success: true,
      facebook: facebook_followers,
      instagram: instagram_followers,
    });
  } catch (error) {
    console.log(error);
    res.json({
      success: false,
      error: error,
      facebook: facebook_followers,
      instagram: instagram_followers,
    });
  }
};
`

**Comment by Devalfaz** [comment]
Facing the same issue . Have you found any solutions yet?

**Comment by warlock1996** [comment]
@Devalfaz not yet, i think its puptr , it api is not widely supported i think
