### ISSUE TITLE
I can't install puppeteer on Ubutnu 20.04

### ISSUE THREAD

**Issue by DadaHumpa01** [puppeteer/puppeteer#7186]
I can't install puppeteer on linux

Ubuntu 20.04 LTS
Node.js version: v10.19.0

I used the guide inside the Puppeteer github,
npm install puppeteer
but i get these errors and i can't use puppeteer!

Downloading Chromium r869685 - 135.6 Mb [====================] 100% 0.0s 
Chromium (869685) downloaded to /home/ciao/Desktop/test/node_modules/puppeteer/.local-chromium/linux-869685
npm WARN saveError ENOENT: no such file or directory, open '/home/ciao/Desktop/test/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/ciao/Desktop/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
**What is the expected result?**

**Comment by ghost** [comment]
have you even tried googling the error?

**Comment by WallisonLima** [comment]
try to install it with root permission

**Comment by ghost** [comment]
https://stackoverflow.com/questions/45531633/npm-warn-enoent-enoent-no-such-file-or-directory-open-c-users-nuwanst-packag

**Comment by WallisonLima** [comment]
`sudo npm install puppeteer`

**Comment by Razan-Poudel** [comment]
ok i got it 
it was because of the node version which puppeteer didnt support.
my bad

**Comment by OrKoN** [comment]
Node 10 is not supported and I am unable to reproduce the issue with the latest version.
