### ISSUE TITLE
Overriding postData in request interception

### ISSUE THREAD

**Issue by ojame** [puppeteer/puppeteer#7187]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@9.0.0 
* Platform / OS version: MacOS 10.14.5
* URLs (if applicable):
* Node.js version: 14.5.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```javascript
await page.setRequestInterception(true);

page.on("request", (request) => {
  if (request.method() === "POST") {
    const originalFormData = request.postData();

    if (originalFormData) {
      const decodedInput = decodeURI(originalFormData);
      const searchParams = new URLSearchParams(decodedInput);

      searchParams.set("foo", 'bar');

      request.continue({ postData: searchParams });
    }
  }
});
```
**What is the expected result?**
The body (formData) of the POST request is modified so it has the key/value pair of `foo: bar`

**What happens instead?**
It has the original body in tact with no modification.

----

Puppeteer doesn't error and I can confirm interception works correctly as I can modify headers. The [documentation](https://pptr.dev/#?product=Puppeteer&version=v9.0.0&show=api-httprequestcontinueoverrides) says `postData <string> If set changes the post data of request.`

**Comment by rafakwolf** [comment]
same here
