### ISSUE TITLE
How to overwrite requestInterception :  Request is already handled!

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#7189]
**Tell us about your environment:**

Puppeteer version: 9.0.0
Platform / OS version: Windows
URLs (if applicable): None
Node.js version: v14.15.4

**What steps will reproduce the problem?**
https://pastebin.com/raw/iG7UvMST

**What is the expected result?**
Being able to cancel first request, or overwrite its content

**What happens instead?**
Second function call creatte error because request is already handled
(node:17688) UnhandledPromiseRejectionWarning: Error: Request is already handled!

**Comment by webadmin2021** [comment]
Hi @xPythh,

In your script, the async function was never called, also, can you highlight the function that throws the error?

Do you mean the callback passed to `page.on('req')` or the `useProxy` function?

**Comment by ghost** [comment]
It is actualy called...
https://i.imgur.com/0EYjpUA.png
I am talking about the callback page.on('req')

**Comment by webadmin2021** [comment]
Then, I assume you are getting the problem from `useProxy`. Can we see the definition of `useProxy`?

The problem is likely caused from how useProxy handles the `req` object. You may want to show the stack trace as well

**Comment by ghost** [comment]
The error doesn’t append because of use proxy, but because i create a new time the page.on(‘request’) forom the page when im Calling again the function

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Feyisola ***@***.***>
Envoyé le :dimanche 2 mai 2021 00:53
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [puppeteer/puppeteer] How to overwrite requestInterception : Request is already handled! (#7189)


Then, I assume you are getting the problem from useProxy. Can we see the definition of useProxy?

The problem is likely caused from how useProxy handles the req object. You may want to show the stack trace as well
