### ISSUE TITLE
Error: Evaluation failed: DOMException: Blocked a frame with origin

### ISSUE THREAD

**Issue by ruevers** [puppeteer/puppeteer#7190]
Error: Evaluation failed: DOMException: Blocked a frame with origin

all error

Error: Evaluation failed: DOMException: Blocked a frame with origin "http://web.trf3.jus.br" from accessing a cross-origin frame.
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:8:37)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:9:7)
    at onRaf (<anonymous>:49:35)
    at pollRaf (<anonymous>:42:15)
    at waitForPredicatePageFunction (<anonymous>:7:22)
    at ExecutionContext._evaluateInternal (D:\tj\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at async WaitTask.rerun (D:\tj\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:528:23)

code

while (true) {
      try {
        await page.waitForFunction(() => {
          const iframe = document.querySelector('iframe[src*="api2/bframe"]')
          if (!iframe) return false

          return !!iframe.contentWindow.document.querySelector('.rc-audiochallenge-tdownload-link')
        }, { timeout: 1000 })
      } catch (error) {
        console.log('download link not found')
        return null
      }

      const audioLink = await page.evaluate(() => {
        const iframe = document.querySelector('iframe[src*="api2/bframe"]')
        return iframe.contentWindow.document.querySelector('#audio-source').src
      })

try use parameter  --disable-web-security in issue 

https://github.com/puppeteer/puppeteer/issues/2813

but not work.

**Comment by ghost** [comment]
You can't access an <iframe> with different origin using JavaScript, it would be a huge security flaw if you could do it. For the same-origin policy browsers block scripts trying to access a frame with a different origin.

Ex : You put a youtube iframe on any personal iframe, and would be capable to read data from it and steal users informations.

Workaround
Even though same-origin policy blocks scripts from accessing the content of sites with a different origin, if you own both the pages, you can work around this problem using window.postMessage and its relative message event to send messages between the two pages, like this:

In your main page:

const frame = document.getElementById('your-frame-id');
frame.contentWindow.postMessage(/*any variable or object here*/, 'http://your-second-site.com');
The second argument to postMessage() can be '*' to indicate no preference about the origin of the destination. A target origin should always be provided when possible, to avoid disclosing the data you send to any other site.

In your <iframe> (contained in the main page):

window.addEventListener('message', event => {
    // IMPORTANT: check the origin of the data! 
    if (event.origin.startsWith('http://your-first-site.com')) { 
        // The data was sent from your site.
        // Data sent with postMessage is stored in event.data:
        console.log(event.data); 
    } else {
        // The data was NOT sent from your site! 
        // Be careful! Do not use it. This else branch is
        // here just for clarity, you usually shouldn't need it.
        return; 
    } 
}); 
This method can be applied in both directions, creating a listener in the main page too, and receiving responses from the frame. The same logic can also be implemented in pop-ups and basically any new window generated by the main page (e.g. using window.open()) as well, without any difference.
