### ISSUE TITLE
Get all forms and childrens

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#7194]
I don't want to the whole stuff of listing, my problem is : NO solutions are working.
I would like to get all forms in a page, then being able to get all childs from any of the forms i gathered before.

I am not asking anything more.
I want to find the form with a filter either `form` or `form[id="hello"]`

That's all i am asking.

**Comment by LaurenceJJones** [comment]
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  // Replace URL_FORMS with the URL you need it to go to
  await page.goto(URL_FORMS);
  const forms = await page.$$('form') // Selects all form elements on the page
  // Loop over each form
  forms.forEach( async form => {
     // Grab all children elements of the form
      const formChildren = await page.evaluateHandle(el => el.children, form);
      // Do what you want with form children per form.
  })
  await browser.close();
})();
```

Writing this without testing but this is what you are looking for. Please look at the puppeteer API documentation for the functions I have used and the descriptions to expand this further.
