### ISSUE TITLE
PDF generation ignores backdrop-filter css rule

### ISSUE THREAD

**Issue by felbsn** [puppeteer/puppeteer#7198]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer@5.5.0 and puppeteer@9.0.0
* Platform / OS version: Window 10
* URLs (if applicable):
* Node.js version: v14.15.4

**What steps will reproduce the problem?**

1.  Running following code is enough to reproduce problem
2.  Change SOME_PATH variable with some actual pdf file path to see results.
```js
 const puppeteer = require('puppeteer');
(async ()=>
{
    const browser = await puppeteer.launch({headless:true});
    const page = await browser.newPage();
    await page.setContent(`
    <!DOCTYPE html>
    <html>
    <head>
        <style media="all">
            html,body
            {
                margin: 0;
                height: 100%;
                backdrop-filter: invert(100%);
            }   
        </style>
    </head>
    <body>
    <h1>This text should not be seen</h1>
    </body>
    </html>
    `);
    var buffer = await page.pdf({
      format: "a4",
      width: 794,
      path :  SOME_PATH,
      printBackground: true
    })
    browser.close();
})();
```

**What is the expected result?**
 
With invert filter, expected result is a complete black page. 

**What happens instead?**

Normal, blank white page appears. In other words back-drop filter didn't affect at all.

**Note**
I tried this with other filters such as sepia, blur etc. But still it didn't work. 
So i picked invert filter because it is easy to demonstrate.

Btw without enabling headless option the back-drop filter works fine.

**Comment by minured** [comment]
page-break-after didn't affect

**Comment by stouch** [comment]
@felbsn Did you find an alternative / solution to this ?
