### ISSUE TITLE
Widevine support?

### ISSUE THREAD

**Issue by russitto** [puppeteer/puppeteer#720]
I'm try to test dash+cenc+widevine via shaka player but DRM is not enabled in chromium.

I copy **libwidevinecdmadapter.so** and **libwidevinecdm.so** to _.local-chromium/linux-497674/chrome-linux_ dir, but it does not work.

How can I use widevine?
Thx

**Comment by aslushnikov** [comment]
@russitto Quick googling gave me the following link: https://wiki.archlinux.org/index.php/chromium#Widevine_Content_Decryption_Module_plugin

**Comment by aslushnikov** [comment]
Closing since the question is about chromium rather then puppeteer.

**Comment by paulirish** [comment]
Would also recommend looking at https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions to use Chrome instead of Chromium.

**Comment by noeRls** [comment]
I run into the same issue recently and here is my launch config to have DRM

```
const browser = await puppeteer.launch({
    ignoreDefaultArgs: [
        '--disable-component-update',
    ],
    channel: 'chrome'
});
```
