### ISSUE TITLE
page.screenshot() always gives empty page

### ISSUE THREAD

**Issue by sidh01** [puppeteer/puppeteer#7213]
### Steps to reproduce

**Tell us about your environment:**

"puppeteer-core": "^9.0.0",
 "chrome-aws-lambda": "^8.0.2",
 nodejs12.x

code :
    const param = JSON.parse(event.body);
    console.log("param", param);
    const { url, viewPort, options } = param;

    let response={
        statusCode:200,
        body:"",
        isBase64Encoded:true,
        contentType:options.type?"image/"+options.type:"image/png"
    }
    
      const executablePath = event.isOffline ? "/usr/bin/google-chrome" : await chromium.executablePath;
     //  const executablePath = "/usr/bin/google-chrome" 

     console.log("executablePath",executablePath);
    const browser = await puppeteer.launch({
        args: chromium.args,
        executablePath,
        headless: true
    })

    try {

        const page  = (await browser.pages())[0];
        if (viewPort) {
            await page.setViewport({
                width: viewPort.width,
                height: viewPort.height,
            });
        }

        
        

        await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/85 Version/11.1.1 Safari/605.1.15');
       
        await page.setExtraHTTPHeaders({
            'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
        });

        await page.goto(url, {
            timeout:options.timeout?options.timeout:30, 
            waitUntil:"load"         
        });

        await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/85 Version/11.1.1 Safari/605.1.15');

        await page.setExtraHTTPHeaders({
            'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
        });

        await page.setViewport({
            width: 300,
            height:300,
        });

       
        let responseBuffer = await page.screenshot({...options }); 

        if(options.encoding=="base64")
        response.body=responseBuffer
        else
        response.body= responseBuffer.toString('base64')

**What is the expected result?**
image buffer

**What happens instead?**
blank image

json body to pass
{
    "url":"http://google.com/",
    "viewPort":{"width":1000,"height":1200},
    "options":{"timeout":"30000"}
}

**Comment by Andrew-web-coder** [comment]
I am experiencing the same issue after upgrading to v9.1

**Comment by sidh01** [comment]
Any update on this ?

**Comment by sadym-chromium** [comment]
Is the problem still persist in v10.1.0?

**Comment by djkramnik** [comment]
I have had continual troubles with this particular use case -- I want to take screenshots of elements but with some customizable padding around them.  I was trying something like this: 
```
const rect = await page.evaluate((elementHandle) => {
  return elementHandle.getBoundingClientRect()
}, elementHandle)

await page.screenshot({
  path,
  clip: {x: rect.left - 5, y: rect.top - 5, width: rect.width + 10, height: rect.height + 10},
})
```
^ note the use of clip option to add some padding around the element screenshot. 

However this did not work when the element is not in the initial viewport.  Then I would just get a blank screenshot.  And no combination of setting the window size and viewport, scrolling the page, using elementHandle.hover, elementHandle.screenshot could work to achieve my use-case. Closest try was using elementHandle.screenshot(), however, that will give you just the element itself with no option to add padding. 

So what I have resorted to now is -- for each element I want to perform a padded screenshot with, hover the element or otherwise scroll it into view, and take a non clipped screenshot of the entire viewport (i.e. `page.screenshot({path})`).  Then I record the clip info and then perform the crop using ffmpeg.  Not ideal, but at least automate-able and I don't have to continue bashing my head against the wall with this finicky screenshot behaviour.

**Comment by sadym-chromium** [comment]
@djkramnik using [`captureBeyondViewport` flag](https://github.com/puppeteer/puppeteer/blob/4d8dfabf2c95411513d958eaa28bf628f8462d1b/docs/api.md#pagescreenshotoptions) lets you skip scrolling to the element. Hopefully it can help your use-case. The flag `captureBeyondViewport` was introduced in April, it was added to the documentation just recently.

**Comment by jsjett** [comment]
> Is the problem still persist in v10.1.0?

my dear borther ; this bug still in v10.1.0,  I don't know how to solve it；can you help me ?

**Comment by jsjett** [comment]
> Is the problem still persist in v10.1.0?

look this ；Half of this image is blank, and this is a large image. In addition, I also have images with a height of less than 1000 pixels, all of which are white; Please help me see; The puppeter renders normally when rendering; bug in page.screenshot method

[https://cdn.nlark.com/yuque/0/2021/jpeg/1297850/1628154220508-8a175dc1-4112-4f9d-8af9-7c74f8e17f1c.jpeg](url)

**Comment by sidh01** [comment]
In my case the issue was of header

**Comment by sadym-chromium** [comment]
@jsjett could you please provide more details of what you do? Ideally provide a minimum repro script.

**Comment by jsjett** [comment]
> @jsjett could you please provide more details of what you do? Ideally provide a minimum repro script.

My program is to use the puppeter screenshot. There are many screenshots. One hundred screenshots will be taken from a highly high web page at one time; Among the 100 images intercepted, there are white images; The URL above is an example of a white map; The code is nothing special; Not 100% recurrence; It is occasional, and the probability and number of white pictures are different every time the work is repeated

**Comment by jsjett** [comment]
> @jsjett could you please provide more details of what you do? Ideally provide a minimum repro script.

My program is to use the puppeter screenshot. There are many screenshots. One hundred screenshots will be taken from a highly high web page at one time; Among the 100 images intercepted, there are white images; The URL above is an example of a white map; The code is nothing special; Not 100% recurrence; It is occasional, and the probability and number of white pictures are different every time the work is repeated

**Comment by sidh01** [comment]
> @jsjett could you please provide more details of what you do? Ideally provide a minimum repro script.

pass header Accept; image/png 

in your service or in the code where you have implemented puppeteer 
![puppeteer-snapshot-fix-with-accept](https://user-images.githubusercontent.com/37957105/128501505-d9789511-2bd5-46ab-ae3f-b185a96dc222.jpg)
