### ISSUE TITLE
Feature Request: Connect Options - Allow Authorization Header

### ISSUE THREAD

**Issue by dylanlive** [puppeteer/puppeteer#7218]
### Feature Request

I'd like to connect to a `browserWSEndpoint` that is protected by authentication. It would be nice to be able to provide an `Authorization Bearer <token>` on the connection, and every request thereafter to that endpoint.

I'm specifically wanting the Authorization Header, but this probably could just be generic to allowing any headers on all requests.

I vision within the `connect` options, provide a `headers` option
https://github.com/puppeteer/puppeteer/blob/v9.1.1/docs/api.md#puppeteerconnectoptions

Example:
```
browser = await puppeteer.connect({
      browserWSEndpoint: "ws://my.server",
      headers: {
        Authorization: "Bearer hunter2"
      },
});
```

I'd imagine the change would happen here:
https://github.com/puppeteer/puppeteer/blob/943477cc1eb4b129870142873b3554737d5ef252/src/common/BrowserWebSocketTransport.ts#L21

To be something similar to:
https://github.com/websockets/ws/issues/473#issuecomment-240074672

I did see `page.setExtraHTTPHeaders(headers)`, but I don't think this what I'm looking for as it shouldn't just be for a specific page, but for all websocket requests to the server.
https://github.com/puppeteer/puppeteer/blob/v9.1.1/docs/api.md#pagesetextrahttpheadersheaders

**Comment by jayflo** [comment]
Been looking into this myself.  It seems like it may only be relevant when used from Node.js.  

In the browser, this uses the javascript websocket (https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) 

https://github.com/puppeteer/puppeteer/blob/89a85b428d6edd86cf0d02371b11fbc85abc9dc1/src/common/BrowserWebSocketTransport.ts#L21

which doesn't allow you to set headers.

Within Node.js it uses the https://github.com/websockets/ws package

https://github.com/puppeteer/puppeteer/blob/89a85b428d6edd86cf0d02371b11fbc85abc9dc1/src/node/NodeWebSocketTransport.ts#L22

which should allow you to set headers (https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) via Node.js's http(s).request options.

**Comment by dylanlive** [comment]
Please leave open :)

**Comment by dylanlive** [comment]
still valid

**Comment by dylanlive** [comment]
@jayflo Good catch! Finally got around to experimenting with some local changes using `patch-package` and I can confirm the correct area to add the headers to is https://github.com/puppeteer/puppeteer/blob/f42336cf83982332829ca7e14ee48d8676e11545/packages/puppeteer-core/src/common/NodeWebSocketTransport.ts#L30-L32

Would be great to be able to optionally configure additional headers from `puppeteer.connect()` to that function
