### ISSUE TITLE
Recommendation for pulling resources off the loaded page

### ISSUE THREAD

**Issue by Madd0g** [puppeteer/puppeteer#722]
I need to look at some of the resources loaded by the page, namely a background image referenced by a page CSS.

I managed to grab the background-image data from the network request. Alas that approach doesn't work if it comes from the browser cache.

I'm wondering, since this lib is working through a debugging protocol, if there's a cool hidden trick to access things we normally don't have access to, like:

1) Bodies of cached responses
2) Access to cross-domain resources loaded by the page that JS can't access directly
3) Other devtool features that are not available from JS (like being able to know the link between element styles and where the styles came from, like in the elements tab, styles section)

Thanks!

**Comment by aslushnikov** [comment]
> Bodies of cached responses

There's a handful of methods to poke into response body, e.g. [`response.text()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#responsetext).

> Access to cross-domain resources loaded by the page that JS can't access directly

You should probably be able to load them server-side

> Other devtool features that are not available from JS (like being able to know the link between element styles and where the styles came from, like in the elements tab, styles section)

Some of the features are exposed with pptr api; however, we scope the api to automation, so CSS and DOM domains are not exposed at all.

Hope this helps!
