### ISSUE TITLE
Enable 'Share audio' on Desktop capture prompt

### ISSUE THREAD

**Issue by markito12** [puppeteer/puppeteer#7220]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Windows 10 17763.475
* URLs (if applicable):
* Node.js version: v14.13.0

**What steps will reproduce the problem?**

![Screenshot_30](https://user-images.githubusercontent.com/31602075/117527464-a7389c80-afa2-11eb-8443-45db814b6f63.png)

The code gets a discord bot inside a voice channel and uses 'share screen' button which prompts desktop capture, but it's imposible to enable 'share audio' (mouse click (ppt), api interaction, launch args...).

**What is the expected result?**

Be able to click or interact with the prompt

**What happens instead?**

Not able to interact with desktop capture prompt by any means.

**Comment by OmerSabic** [comment]
Hello, I have a similar problem on another website, have you found the answer yet?

**Comment by markito12** [comment]
sorry for the late response, but no.

you could build chromium and modify that value on the source o use a clicking package and do it manually with cords

**Comment by yoshinorihisakawa** [comment]
@markito12 

> you could build chromium and modify that value on the source o use a clicking package and do it manually with cords

Could you please elaborate on alternative methods?
