### ISSUE TITLE
DOMException: The element has no supported sources.

### ISSUE THREAD

**Issue by yidongw** [puppeteer/puppeteer#7222]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9.1.1
* Platform / OS version: macOS 13.6
* URLs (if applicable): 
* Node.js version: v12.18.4

**What steps will reproduce the problem?**
1. launch chromium from puppeteer
2. go to page https://music.163.com/#/song?id=1834698830
3. click "play" - 播放
![image](https://user-images.githubusercontent.com/12843927/117602037-554e6d00-b182-11eb-902d-ee4331ce6eda.png)

**What is the expected result?**
music should play as expected

**What happens instead?**
from the console, we can see it throws an error `DOMException: The element has no supported sources.`

**Notes**
It above flow works in the chrome. music will play as intended, but It didn't work in chromium. I have done quite a lot of googling trying to solve this problem but none of the solutions seems to be working, I'm not sure if this is a chromium issue or puppeteer issue.

Thanks in advance

**Comment by yidongw** [comment]
My work is entirely blocked by this. I'll appreciate it if someone can help or point me to the right people

**Comment by yidongw** [comment]
I notice that the request header is missing `origin: https://music.163.com`, and `sec-fetch-mode` is `no-cors` instead of `cors`.

I think it is a cors problem, so I used the following code, but it didn't work
```
  const browser = await puppeteer.launch({
    headless: false,
    devtools: true,
    args: ['--disable-web-security', '--disable-features=IsolateOrigins', ' --disable-site-isolation-trials']
  });
```

**Comment by heartsuit** [comment]
看到你给我CSDN发的私信（只能回复三条信息。。），Chromium由于版权原因，本身是不支持远程音视频播放的，参考：https://github.com/puppeteer/puppeteer#q-what-features-does-puppeteer-not-support
![图片](https://user-images.githubusercontent.com/8071981/119800727-9fb84380-bf0f-11eb-8b29-72a1430b2c1d.png)

1. 如果不是必须要使用Chromium的话，可以采用官方建议的，通过executablePath使用外置的Chrome，我测试了一下，可以实现音频的播放，eg:
`        return __awaiter(this, void 0, void 0, function* () {
            config_1.log.verbose('PuppetWebBridge', 'initBrowser()');
            const headless = this.options.head ? false : true;
            const browser = yield puppeteer_1.launch({
                executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
                headless,
                args: [
                    '--audio-output-channels=0',
                    '--disable-default-apps',
                    '--disable-extensions',
                    '--disable-translate',
                    '--disable-gpu',
                    '--disable-setuid-sandbox',
                    '--disable-sync',
                    '--hide-scrollbars',
                    // '--mute-audio',
                    '--no-sandbox',
                    "--autoplay-policy=no-user-gesture-required",
                ],
            });
            const version = yield browser.version();
            config_1.log.verbose('PUppetWebBridge', 'initBrowser() version: %s', version);
            return browser;
        });`
测试地址：
https://music.163.com/#/song?id=1834698830

2. 如果必须使用Chromium的话，需要进行重新编译，以开启对音视频的播放支持，可参考：https://www.zhihu.com/question/19721512
具体如何操作，还需要自己摸索，加油(•̀ᴗ•́)و

**Comment by heartsuit** [comment]
另一个测试地址：https://gk.lka.hu/old2/html5/

**Comment by yidongw** [comment]
Thank you so much!
