### ISSUE TITLE
Keyboard API is confusing 

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#723]
Keyboard API is very powerful but confusing.

Questions/clarifications:
- [x] Why's there no `keyboard.press()`?
- [x]  Explain the difference between `keyboard.press('a')` and `keyboard.press('a', {text: 'a'})`. Also, should there be a difference?
- [x] Explain why `await keyboard.down('Shift'); await keyboard.type('hello');` **does not** produce 'HELLO'.

**Comment by thetutlage** [comment]
Any chance to get some updates on it?

**Comment by aslushnikov** [comment]
@thetutlage no real updates so far; but @JoelEinbinder has something in works for this.

**Comment by thetutlage** [comment]
Oh that’s nice. Thanks for sharing

**Comment by aslushnikov** [comment]
For this issue to be closed: 
- add API example
- explain why await keyboard.down('Shift'); await keyboard.type('hello'); does not produce 'HELLO'

**Comment by christophby** [comment]
any news on this?
