### ISSUE TITLE
Puppeteer not rendering correctly pages.

### ISSUE THREAD

**Issue by workadn** [puppeteer/puppeteer#7231]
Hello everyone,

I am trying to take screenshots of some webpages but Puppeteer is not rendering the entire content.
It seems that other tools using chromium based browsers (Screaming Frog, even Google Bot) are having the same issue.

Puppeteer version: 9.1.1
Platform / OS version:  CentOS-7"
URLs (if applicable): https://www.foxnews.com/
Node.js version: v15.8.0

What steps will reproduce the problem?
Take a screenshot with puppeteer of https://www.foxnews.com/ or https://edition.cnn.com/world - mobile viewport, full page (HEAD to FOOTER)

What is the expected result?
A complete screenshot of the page. From top to bottom. Images included.

What happens instead?
The screenshot does not contain the full page. It will stop mid-page. In most cases it will not even show all the images.
waitingFor elements, waiting for 20-30 seconds, or timeout increase will not help this in any way.

Can anyone help me understand why this is happening?

Thank you very much!

**Comment by murilozilli** [comment]
instead of using full page, try to use the selector "body", I believe I had the same issues with fullpage in the past

**Comment by workadn** [comment]
Thank you! The idea is to have a full screenshot of the entire page. Tools like Screaming Frog or even Google Bot are having the same issue as they are rendering the full page. I was wondering if this is a chromium issue or, something with Puppeteer.
Thank you!

**Comment by djkramnik** [comment]
I was able to pull full page of foxnews fine.  Do you call page.screenshot like this?
```
  await page.screenshot({
    fullPage: true,
    path,
  });
```
@workadn

**Comment by sadym-chromium** [comment]
The task is considered solved. Please fill free to reopen with more details, if you still experience the problem.
