### ISSUE TITLE
Cache the Chromium binary to avoid unnecessary downloads on repeated installs on the same machine

### ISSUE THREAD

**Issue by canonic-epicure** [puppeteer/puppeteer#7233]
We have a continuous integration server, which performs a clean build for every change. It starts the build with the `npm i` command. And on every such command puppeteer downloads the Chromium binary and unpacks it. This takes a lot of time and bandwidth. I believe this is sub-optimal and can be improved.

Much better flow would be to cache the downloaded binary somewhere and on install only unpack the archive.

**Comment by mathiasbynens** [comment]
Use `PUPPETEER_DOWNLOAD_PATH`: https://github.com/puppeteer/puppeteer/pull/6014

**Comment by canonic-epicure** [comment]
@mathiasbynens Thanks for the info! Missed that variable somehow.
