### ISSUE TITLE
Handling File Input Dialogs

### ISSUE THREAD

**Issue by WallisonLima** [puppeteer/puppeteer#7235]
Is there any way to handle File Input Dialogs in Firefox?

When I click an element on the page, it opens up the upload file dialog.

I can not use elementHandle.uploadFile as it is not an input[type="file"]. Plus, #1376 will not help as, dragging and dropping in the file upload field does not work, instead, dragging and dropping opens up the file in the browser tab.

I am using Linux.

So, can you provide some example code on how would I go about doing that? Thanks!

**Comment by whimboo** [comment]
`JSHandle.uploadFile` is based on the `DOM.setFileInputFiles` Chrome-DevTools-Protocol API. We have an [implementation bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1553847) filed for it but we might not get this implemented.

**Comment by SajawalFareedi** [comment]
Is there any workaround in chromium for doing this?
