### ISSUE TITLE
Browser size and location

### ISSUE THREAD

**Issue by MrYZhou** [puppeteer/puppeteer#7237]
I wanted to set the size and location of the running browser, I looked at the documentation, but for this piece of setting I could only set it in the startup parameters.How can I set a running browser instance.

**Comment by subject-21** [comment]
About the size of browser when its already running, did you try `puppeteer.connect(options)`?
you can send the option `defaultViewport` with custom size..
see https://pptr.dev/#?product=Puppeteer&version=v9.1.1&show=api-puppeteerconnectoptions
