### ISSUE TITLE
cannot access window.document on exposed Function

### ISSUE THREAD

**Issue by perrefe** [puppeteer/puppeteer#724]
Hi,

Apparently, is not possible to access window.document object from within a exposed function as this

~~~
await page.exposeFunction('myExposedFunction', () => {
  const anchors = Array.from(document.querySelectorAll('a'));
}
~~~

When this function is evaluated I get:

```(node:25104) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: document is not defined```

* Puppeteer version: 0.10.2
* Platform / OS version: MacOS 10.12.6

**Comment by vsemozhetbyt** [comment]
If I understand this correctly, functions exposed in this way have access to the Node.js context, not the browser (`window`) context.

**Comment by aslushnikov** [comment]
@vsemozhetbyt nailed it.

**Comment by adamchenwei** [comment]
@vsemozhetbyt but if so, then what's the alternative to allow function has access to the browser context, without writing spagetti code inside the page.evaluate block?

**Comment by vsemozhetbyt** [comment]
@adamchenwei Sorry, I do not know. `page.evaluate()` seems for me to be the simplest way, jsHandle API is more complicated.

**Comment by motin** [comment]
> @vsemozhetbyt but if so, then what's the alternative to allow function has access to the browser context, without writing spagetti code inside the page.evaluate block?

I use this workaround:
```ts
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const exposeDepsJs = (deps: Record<string, (...args: any) => any>): string => {
  return Object.keys(deps)
    .map((key) => {
      // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
      return `window["${key}"] = ${deps[key]};`;
    })
    .join("\n");
};
```

Used as such, somewhere before the page.evaluate call that should have access to the functions:

```ts
await page.evaluate(exposeDepsJs({ fooFunction }));
```

The dependencies will be exposed on the window object in the browser context, similar to exposeFunction, but only in the browser context without any bridging.

**Comment by KevinHCH** [comment]
This problem still appearing in puppeteer or playwright.
As the people say, when you use the `await page.exposeFunction` method, you are using the function you defined inside the Node.js environment. Therefore, if you try to use `document.querySelector`, it will fail, and you will encounter the error message: **"document is not defined."**
The solution I found is use the function: `await page.addScriptTag`
```js
//browser-functions.js
//all the functions here should be functions you will use in the browser console
const $ = (selector) => document.querySelector(selector)
const $$ = (selector) => [...document.querySelectorAll(selector)]
const getText = (selector) => $(selector)?.innerText.trim() || null
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
```

```js
//puppeteer.js
//launch browser, open url...
await page.addScriptTag({path: './browser-functions.js'})
//use that functions inside the browser
const details = await page.evaluate(() => {
  const title = document.title
  const links = $$("a").map(link => link.href)
  const header = getText("h1")
  return { title, headerText: header, links }
})
console.log(details)
```
This is valid for playwright and puppeteer :)
