### ISSUE TITLE
【API Bug？】 page.screenshot out picture has lines 

### ISSUE THREAD

**Issue by 1927970608** [puppeteer/puppeteer#7259]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9.1.1
* Platform / OS version: win10 
* URLs (if applicable):
* Node.js version: 12.19.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by sadym-chromium** [comment]
Could you please provide a little more details?
