### ISSUE TITLE
Where to deploy puppeteer projects ? (question)

### ISSUE THREAD

**Issue by jasan-s** [puppeteer/puppeteer#726]
Heroku, GAE, AWS Beanstalk ?  I'd prefer something like Google cloud functions, where I only pay for the usage the task runs. However I tried on Cloud functions, Heroku and GAE. But it failed on all three. With 502 Error on Heroku and GAE

**Comment by ebidel** [comment]
My understanding with Google Cloud functions (and others) is that there are a couple of limitations:

1. Their env is Node 6. Puppeteer now works on Node 6, but any async/await code that you write would need to be transpiled before it's deployed. AWS Lambda and Firebase Functions have a similar limitation atm.
2. the version of Chromium that Puppeteer installs is missing shared libs on Linux and you have no way to install them. Unlock Docker, GCF only support node deps in a package.json.
3. Running on Linux requires [launching Chrome with the `--no-sandbox`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues) flag (and possibly others).

The solution is to use something like Heroku, App Engine Flex, Google Compute Engine, or AWS where you have full control over the environment. Docker being an excellent choice.

We just put up an [example Dockerfile](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) that shows how to install the correct version of Chrome to make Puppeteer work with Chrome headless (Linux).

Related issues: 
- AWS Lambda Functions - https://github.com/GoogleChrome/puppeteer/issues/323
- Firebase Functions - https://github.com/GoogleChrome/puppeteer/issues/557

**Comment by jasan-s** [comment]
Thanks @ebidel , I'm not familiar with Docker. but I also tried to deploy to Vultr Ubuntu 16.04 x64
today, and received the following error:

```
Error: Failed to launch chrome!
/root/mysite/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by Garbee** [comment]
@jasan-s You need to make sure the requirements are installed. Check the `docs/troubleshooting.md` file for more details.

**Comment by timleland** [comment]
I wrote a simple guide that includes the steps to get an app running puppeteer on Heroku: https://timleland.com/headless-chrome-on-heroku/

**Comment by cemheren** [comment]
Not sure if anyone'd be interested but, I started providing Puppeteer as a service. Take a look at https://konvoy.io/. There is a good Free tier which is hopefully enough for most experimental workloads.

**Comment by ebidel** [comment]
https://konvoy.io/playground/ looks familiar :p

**Comment by cemheren** [comment]
Haha, you were my inspiration :D

**Comment by Robula** [comment]
How about App Engine? 
https://cloud.google.com/appengine/docs/standard/nodejs/using-headless-chrome-with-puppeteer

**Comment by reco** [comment]
with the new node8 you can deploy it on google cloud functions

https://stackoverflow.com/questions/43732991/possible-to-run-headless-chrome-chromium-in-a-google-cloud-function

**Comment by SaiSaharsh** [comment]
How can I deploy my test automation code in dev environment and run it using puppeteer?

**Comment by max-programming** [comment]
@jasan-s How much do you pay on GCF for your Puppeteer project?
