### ISSUE TITLE
Save all cookies in puppeteer-firefox

### ISSUE THREAD

**Issue by abokizh** [puppeteer/puppeteer#7263]
I could get all cookies in regular puppeteer suing ```let cookie = await page._client.send('Network.getAllCookies');```. How can I do that with puppeteer-firefox?

**Comment by whimboo** [comment]
Do not use `puppeteer-firefox`. That's a deprecated package. Instead [install the regular Puppeteer package by defining Firefox as product](https://github.com/puppeteer/puppeteer#q-which-firefox-version-does-puppeteer-use). That API is available since a couple of Firefox releases.
