### ISSUE TITLE
response.buffer() is sometimes neither resolved nor rejected

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#7294]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9.1.1
* Platform / OS version: any
* URLs (if applicable): Any MP3 file
* Node.js version: 16.1.0

**What steps will reproduce the problem?**

```javascript
'use strict'

const puppeteer = require('puppeteer')

;(async function () {
  const browser = await puppeteer.launch()
  const context = await browser.createIncognitoBrowserContext()
  const page = await context.newPage()
  let bodies = 0
  let responseCount = 0
  page.on('response', (response) => {
    const url = response.url()
    if (/^data:/i.test(url)) return
    const count = ++responseCount
    console.log(`response ${count}: ${url}`)
    bodies++
    response.buffer().then(body => {
      bodies--
      console.log(`response ${count}: received ${body.length} bytes`)
    }).catch(error => {
      console.log(`response ${count}: error: ${error}`)
    })
  })
  await page.goto('https://unequivocal.eu/mp3.mp3')
  await new Promise(resolve => setTimeout(resolve, 10 * 1000))
  console.log(`missing bodies: ${bodies}`)
  await page.close()
  await context.close()
  await browser.close()
})()
```

**What is the expected result?**
```
response 1: https://unequivocal.eu/mp3.mp3
response 1: received 72 bytes
missing bodies: 0
```

**What happens instead?**
```
response 1: https://unequivocal.eu/mp3.mp3
response 2: https://unequivocal.eu/mp3.mp3
response 2: received 72 bytes
missing bodies: 1
```

Note that the MP3 being used is a trivial 72-byte example. If a larger MP3 is used instead then neither response body resolves and you get `missing bodies: 2`.

It may be that it's simply not practicable to get the response body for something like an MP3 file, but in that case `response.buffer()` should be rejecting, or resolving to `undefined`, or something. Or at the *very least*, there should be a documented way to know in advance that `response.buffer()` is going to stall and thus avoid calling it in the first place. (If there is an undocumented way, that would be useful to know also!)

**Comment by jribbens** [comment]
This issue is not stale, it has just been totally ignored. It still happens with puppeteer 15.5.0.

**Comment by Reggino** [comment]
I'm running into the exact same issue when loading image files.
