### ISSUE TITLE
[Question] Calling `evaluateOnNewDocument` multiple times

### ISSUE THREAD

**Issue by jloleysens** [puppeteer/puppeteer#7301]
**Environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: macOS
* Node.js version: 14.17.0
* Running Chromium only

I would like to make 2 or more calls to `evaluateOnNewDocument` and just wanted to clarify the intended behaviour since the documentation I found ([here](https://pptr.dev/#?product=Puppeteer&version=v9.1.1&show=api-pageevaluateonnewdocumentpagefunction-args)) does not explicitly speak about it (I might be missing something!).

The reason for wanting to do this is because one of the functions I would like to call on new page is not in the control of the code where I want to register the function.

Is it the intended behaviour now, and moving forward, that multiple calls to `evaluateOnNewDocument` will register functions in an additive way. For example:

```js
await page.evaluateOnNewDocument(() => console.log('this will run'));
await page.evaluateOnNewDocument(() => console.log('this will also run'));
await page.evaluateOnNewDocument(() => console.log('even this'));
```

Specifically, it will not overwrite a previous call to `evaluateOnNewDocument`. Happy to move this to StackOverflow if more appropriate but this is intended for the maintainers of the lib.

Thanks in advance!

**Comment by mathiasbynens** [comment]
This is working as intended. “Evaluate `$a` on any new document” + “Evaluate `$b` on any new document” does in no way suggest that `$a` would no longer be evaluated on new documents.
