### ISSUE TITLE
Xpath selector not valid but valid in actual browser

### ISSUE THREAD

**Issue by parmonov98** [puppeteer/puppeteer#7303]
### Steps to reproduce

a bunch of div elements with `sku_item` class
there are other elements with class `photo_no_QV`
sometimes the div with `photo_no_QV` may contain another div with class `oos_label`, sometimes not. 
I need the ones that don't contain div with class `oos_label` 

my expression xpath = //div[contains(@class, "sku_item")]//div[contains(@class, "photo_no_QV") and not(div[contains(@class, "oos_label")])]

**Tell us about your environment:**

* Puppeteer version:  ^9.1.1
* Platform / OS version: KUbuntu 20.04
* URLs (if applicable): https://www.officedepot.com/catalog/search.do?Ntt=Mac+Book
* Node.js version: 14

**What steps will reproduce the problem?**
you can find the elements on the provide page
_Please include code that reproduces the issue._

let elements = await page.$$eval('//div[contains(@class, "sku_item")]//div[contains(@class, "photo_no_QV") and not(div[contains(@class, "oos_label")])]');
  // let elements = await page.$$('.sku-item-list .sku-item button.add-to-cart-button.btn-leading-ficon');
  console.log(elements.length);

  while (elements.length == 0) {
    await page.reload({ waitUntil: 'domcontentloaded', timeout: 0 });
    elements = await page.$$('//div[contains(@class, "sku_item")]//div[contains(@class, "photo_no_QV") and not(div[contains(@class, "oos_label")])]');
  }

1. 
2.
3.

**What is the expected result?**
number of elements

**What happens instead?**

![image](https://user-images.githubusercontent.com/24564577/120250692-88bf7b80-c298-11eb-92f7-3539b01461ce.png)

**Comment by hanayashiki** [comment]
you should use `$x`, `$$` is for query selectors.
