### ISSUE TITLE
why? google chrome ok, puppeteer Nginx forbidden.

### ISSUE THREAD

**Issue by programmerWhite** [puppeteer/puppeteer#7307]
link url : http://q.10jqka.com.cn/gn/index/field/addtime/order/desc/page/1/ajax/1/

puppeteer browser:
![image](https://user-images.githubusercontent.com/17827176/120412855-dd8eef00-c389-11eb-92c2-5e545240f43d.png)

chrome browser: 
![image](https://user-images.githubusercontent.com/17827176/120412912-f7303680-c389-11eb-975a-944e210678d3.png)

please tell why? thanks

**Comment by figo-fe** [comment]
这个问题我解决了，加v交流 23335628
