### ISSUE TITLE
Page.addStyleTag with disabled JavaScript causes Puppeteer to hang 

### ISSUE THREAD

**Issue by archfurry** [puppeteer/puppeteer#7314]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.0.0
* Platform / OS version: Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux
* Node.js version: v15.14.0

**What steps will reproduce the problem?**
```
const puppeteer = require("puppeteer");
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setJavaScriptEnabled(false);
  await page.addStyleTag({
    content: " ",
  });
  await page.close();
  await browser.close();
})();
```
**What is the expected result?**
Just clean exit

**What happens instead?**
It just hangs.

**What causes this behavior?**
To perform addStyleTag Puppeteer uses function addStyleContent (in this case) with following code (filename: puppeteer/src/common/DOMWorld.ts)
```
async function addStyleContent(content) {
            const style = document.createElement('style');
            style.type = 'text/css';
            style.appendChild(document.createTextNode(content));
            const promise = new Promise((res, rej) => {
                style.onload = res;
                style.onerror = rej;
            });
            document.head.appendChild(style);
            await promise;
            return style;
        }
```
And because the JavaScript is disabled on the page the Promise is never resolved nor rejected.
I think this is unexpected behavior and this should be fixed or at least documented.
Thank You for your attention!

**Comment by er-dev** [comment]
Also ran across this issue today. Can confirm using `page.setJavascriptEnabled(false); page.addStyleTag(...)` causes Jest to timeout.

**Comment by OrKoN** [comment]
Not reproducible anymore. 

```
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.goto(
    'https://example.com'
  )
  await page.setJavaScriptEnabled(false);
  await page.addStyleTag({
    content: "* { color: red; }",
  });
})();
```
