### ISSUE TITLE
How to get a url(pdf file) response and save to disk?

### ISSUE THREAD

**Issue by wideweide** [puppeteer/puppeteer#7320]
STEP 1: Are you in the right place?

my question start with how to ,but I think something wrong with puppeteer...

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:2.1.1
* Platform / OS version:win10
* URLs (if applicable): a page with html: <iframe src='./test.pdf'>
* Node.js version:v12.18.3

**What steps will reproduce the problem?**

1. prepare a page and pdf
page.html
```
<p> this page has a iframe to show pdf</p>
<iframe src='./test.pdf'></iframe>

```
2. write some code to get pdf's response and save to disk
```

(async () => {
    const fs = require('fs')
    const puppeteer = require("puppeteer")

    const browser = await puppeteer.launch({
        headless: false,
        args: [
            '--disable-web-security',
            '--disable-features=IsolateOrigins,site-per-process', 
        ]
    });
    const page = await browser.newPage();

    page.goto('...page.html') 

    page.on('request', request => {
        let url = '...test.pdf'
        if (request.url() === url) {
            page.on('response', response => {
                if (response.url() === url) {
                    console.log('down', request, response)

                    response.buffer().then(buffer => {
                        fs.writeFileSync('./test.pdf', buffer, function (err) {
                            console.log(err)
                        });
                    })
                }
            })
        }
    })
})()

```
3. run code to save test.pdf

**What is the expected result?**
response.buffer() can get the pdf's real content

**What happens instead?**

`<!doctype html><html><body style='height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(82, 86, 89);'><embed style='position:absolute; left: 0; top: 0;'width='100%' height='100%' src='about:blank' type='application/pdf' internalid='B37C968E605651E3FA1E5945C8CDE282'></embed></body></html>`

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.
