### ISSUE TITLE
launch chrome failed

### ISSUE THREAD

**Issue by xianfeng95** [puppeteer/puppeteer#7321]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9.1.1
* Platform / OS version: debain 4.1.4
* URLs (if applicable):
* Node.js version: 16

**What steps will reproduce the problem?**
run puppeteer in headless mode

```js
    _brower = await puppeteer.launch({
      headless: _headless,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-web-security",
        "--disable-gpu",
        "--disable-dev-shm-usage",
      ],
      env: {
        FONTCONFIG_PATH: `${path.resolve(__dirname, "../public/font")}`,
        LD_LIBRARY_PATH: `${path.resolve(__dirname, "../extra/usr/lib")}`,
      },
    });
```

I failed to run puppeteer
the error show below
`
error while loading shared libraries: libgnutls.so.30: cannot open shared object file: No such file or directory
`

**Comment by Eren-Dexter** [comment]
### Dependencies Issue of Chromium | Puppeteer | Repl.it
I am recently working on a fun project in **repl.it** where I need to use **puppeteer** as a browser automation tool. And after adding this package in my **repl** some error showed up saying,

> Failed to launch the browser process! /home/runner/WhatsAppBot/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory.

When I went to check the missing dependencies, I got a huge list containing those missing libraries. As I don't have the root permission, I couldn't able to install them.

Is there any way to solve this problem?

> NOTE: I tried installing some previous versions of puppeteer and chromium but didn't work out for me.

Here are some lines of my index.js

````
require("./server");
const pptr = require("puppeteer");

async function send() {
  const brwoser = await pptr.launch({
    //userDataDir: "./User_Data",
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'] 
  });
  const page = await brwoser.newPage();
  await page.setUserAgent(
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"
  );
  await page.setViewport({ width: 1000, height: 728 });
  await page.goto("https://web.whatsapp.com");
  await page.waitForTimeout(5000);
````
**Missing Dependencies:**

![Capture](https://user-images.githubusercontent.com/85707110/121607711-510fbb00-ca72-11eb-8698-8e8b34fde184.PNG)

**Comment by rishabh2408** [comment]
@xianfeng95 Any solution for this? I am also facing the same issue...

**Comment by slezercc** [comment]
I have the same issue.
