### ISSUE TITLE
### Dependencies Issue of Chromium | Puppeteer | Repl.it

### ISSUE THREAD

**Issue by Eren-Dexter** [puppeteer/puppeteer#7322]
### Dependencies Issue of Chromium | Puppeteer | Repl.it
I am recently working on a fun project in **repl.it** where I need to use **puppeteer** as a browser automation tool. And after adding this package in my **repl** some error showed up saying,

> Failed to launch the browser process! /home/runner/WhatsAppBot/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory.

When I went to check the missing dependencies, I got a huge list containing those missing libraries. As I don't have the root permission, I couldn't able to install them.

Is there any way to solve this problem?

> NOTE: I tried installing some previous versions of puppeteer and chromium but didn't work out for me.

Here are some lines of my index.js

````
require("./server");
const pptr = require("puppeteer");

async function send() {
  const brwoser = await pptr.launch({
    //userDataDir: "./User_Data",
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'] 
  });
  const page = await brwoser.newPage();
  await page.setUserAgent(
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"
  );
  await page.setViewport({ width: 1000, height: 728 });
  await page.goto("https://web.whatsapp.com");
  await page.waitForTimeout(5000);
````
**Missing Dependencies:**

![Capture](https://user-images.githubusercontent.com/85707110/121607711-510fbb00-ca72-11eb-8698-8e8b34fde184.PNG)

_Originally posted by @erendexter in https://github.com/puppeteer/puppeteer/issues/7321#issuecomment-859141705_

**Comment by Wxh16144** [comment]
I use Remote Development in vscode to develop, and when I run it in a container, I have exactly the same problem as you.

**Comment by Tzvetelin88** [comment]
Same here

**Comment by jrandolf-google** [comment]
This is not an issue. Chromium requires certain libraries to exist on the host machine (in this case, Replit's container) which seems to not exist in this case. Since Puppeteer requires Chromium, the above error is given.

**Comment by AlonsoK28** [comment]
there are some solution for this?

**Comment by ujjwal313** [comment]
@jrandolf Is there any solution to run puppeteer on repl.it ?
