### ISSUE TITLE
Clip rectangles with odd-numbered height and width dimensions produce even-sized images.

### ISSUE THREAD

**Issue by mbloch** [puppeteer/puppeteer#733]
### Steps to reproduce
* Puppeteer version: 0.10.2
* Platform / OS version: Mac OS Sierra, Node v8.4.0

**What steps will reproduce the problem?**

When calling `page.screenshot()` with a clip rectangle, odd-sized pixel widths and heights are rounded to even sizes. For example, a .png image created using the rectangle `{x: 0, y: 0, width: 305, height: 121}` is 306x122 pixels.

**Comment by aslushnikov** [comment]
@mbloch thank you for the report!

Reproduction case (expected `clip.png` to be 11x11, actual is 12x12):
```js
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.screenshot({
    clip: {
      x: 0,
      y: 0,
      width: 11,
      height: 11
    },
    path: 'clip.png'
  });
  await page.close();
  browser.close();
})();
```

Filed upstream [crbug.com/763657](https://bugs.chromium.org/p/chromium/issues/detail?id=763657)

**Comment by positlabs** [comment]
I can confirm this is a bug in the protocol. I'm having the same issue using https://www.npmjs.com/package/chrome-remote-interface
