### ISSUE TITLE
Add support to drag and drop files

### ISSUE THREAD

**Issue by jschfflr** [puppeteer/puppeteer#7330]
Now that support for drag and drop operations landed, it would be great to add an api to drag and drop files.

**Comment by jschfflr** [comment]
@danparksf Do you want to take a look at this?

**Comment by danpark-salesforce** [comment]
@jschfflr will pass for now, thanks for asking.

**Comment by jschfflr** [comment]
@danparksf No problem, I'll take care if this. Looks like we need a Chromium change to allow this feature after all...
