### ISSUE TITLE
CORS error when intercepted browser request with url override gets a redirection response

### ISSUE THREAD

**Issue by alexpozzi** [puppeteer/puppeteer#7336]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: v10.0.0
* Platform / OS version: Debian 9 stretch (Docker container)
* URLs (if applicable): -
* Node.js version: v14.17.0

**What steps will reproduce the problem?**

When intercepting browser's requests and overriding the original url (as described here https://github.com/puppeteer/puppeteer/blob/v10.0.0/docs/api.md#httprequestcontinueoverrides) changing the domain of the original request, if the called service returns a redirection (to the same  overridden domain) I get the following CORS error.
```
Access to fetch at 'http://overridden-domain/path (redirected from 'http://original-domain/path') from origin 'http://origin' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://origin' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
CORS headers are correctly set and, if I remove the url override everything works fine.
It seems that the issue is caused by the browser seeing a redirection from the original domain to the overridden domain which is not permitted on CORS requests.

My goal is to override my SPA calls to the api calling the internal Docker api name instead of the public one (to speed up the page rendering). Everything works fine until I don't get any redirection from the api.

In my codebase I do something like the following
```javascript
function getPageHtml(page, url) {
  await page.setRequestInterception(true)
  page.on('request', req => req.continue({ url:  req.url().replace(/^http:\/\/original-domain/, 'http://overridden-domain') })
  
  await page.goto(url, {
    waitUntil: 'networkidle0',
    timeout: 30000,
  })

  return await page.content()
}
```

**What is the expected result?**

The Puppeteer's documentation states `If set changes the request URL. This is not a redirect. The request will be silently forwarded to the new URL. For example, the address bar will show the original URL.` so I'm expecting that when changing the original request domain, I wouldn't get a CORS error if a redirect response is returned to the same overridden domain.

I understand why the issue is happening and I understand that it's the correct browser behavior as, indeed, it's seen as CORS request redirection to a different domain but, is there a way to get around it and still be able to use the internal domain name to make requests to the api?

Thank you in advance :slightly_smiling_face:

**Comment by hdsuperman** [comment]
I have the same problem, request failed when override request domain.

**Comment by lucassilvas1** [comment]
I'm still experiencing this today
