### ISSUE TITLE
firefox response.json() not work

### ISSUE THREAD

**Issue by luqihao** [puppeteer/puppeteer#7344]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.0.0
* Platform / OS version: macOS Big Sur 11.4
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```
const browser = await puppeteer.launch({
        product: 'firefox',
        headless,
        slowMo,
        executablePath: await findChrome(),
        defaultViewport: null,
        dumpio: true,
})
const page = await browser.newPage()
page.on('response', async resp => {
        if (resp.url().includes('order/searchlist')) {
              console.log(1, resp.url())
              console.log(3, resp.status())
              try {
                  // will not console
                  console.log(4, await resp.text())
                  console.log(2, await resp.json())
              } catch (error) {
                  // will not console
                  console.log('丢你', error)
              } finally {
                   // will not console
                  console.log('lala')
              }
        }
})
await page.goto(`******`)
```

**What is the expected result?**

**What happens instead?**

**Comment by whimboo** [comment]
The `response` event seems to be depending on `Network.responseReceived` that we support in Firefox. Would you mind to attach a debug log that shows the problem? To do that just add `DEBUG="puppeteer:*"` before your command invocation on the command line. Thanks!

**Comment by whimboo** [comment]
No response from reporter within the last year. Closing the issue.
