### ISSUE TITLE
JS is not executed

### ISSUE THREAD

**Issue by bmblb** [puppeteer/puppeteer#7346]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.0.0 (same happens on 5.5.0)
* Platform / OS version: WSL1, Windows 10 2004 build 19041.1052
* URLs (if applicable):
* Node.js version: 14.17.0

**What steps will reproduce the problem?**

1. checkout this simple js app: https://github.com/bmblb/puppeteer-script-bug
2. cd to the directory, run `npm i`
3. run `npm run serve &` to start local http server in bg mode
4. run `npm run test` to execute script

**What is the expected result?**
Script should log `app.js` to the console

**What happens instead?**
Script doesn't log anything
```
puppeteer-script-bug$ npm run test

> puppeteer_test@1.0.0 test /mnt/f/work/bryntum/tmp/puppeteer-script-bug
> node ./index.js

301
http://localhost:5000/index.html
301
http://localhost:5000/index
200
http://localhost:5000/
200
http://localhost:5000/app.js
```

Now, if you uncomment line 9 `--single-process` script will run just fine:
```
puppeteer-script-bug$ npm run test

> puppeteer_test@1.0.0 test /mnt/f/work/bryntum/tmp/puppeteer-script-bug
> node ./index.js

301
http://localhost:5000/index.html
301
http://localhost:5000/index
200
http://localhost:5000/
200
http://localhost:5000/app.js
0: JSHandle:app.js
```

I don't really understand what's going on, I couldn't find any report on javascript not running in puppeteer in WSL1. I was looking through other puppeteer bug reports and was just trying random flags that worked for other people, this one helped.

Could you please explain what's happening?

**Comment by sadym-chromium** [comment]
Didn't get into details, but at the first glance it looks like a side effect of the OOPiF: https://github.com/puppeteer/puppeteer/issues/2548

**Comment by bmblb** [comment]
Not using any iframes there though. Just a regular page which loads JS
