### ISSUE TITLE
How to use puppeteer with my current chrome

### ISSUE THREAD

**Issue by NitinGola** [puppeteer/puppeteer#7347]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9.1.1
* Platform / OS version: Windows 10
* URLs (if applicable): 
* Node.js version: 12.16.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. I want to fetch JS coverage report using puppeteer api when user open page  and need to send back to server.
2. Since user will already have chrome browser open so want to use same browser to get coverage report.
3.

**What is the expected result?**

**What happens instead?**

**Comment by YusukeIwaki** [comment]
We can use existing browser by using 'puppeteer-core' package and specifying exexutablePath.
https://stackoverflow.com/questions/59786319/configure-puppeteer-executablepath-chrome-in-your-local-windows

**Comment by NitinGola** [comment]
On the end user system seem its imposible to get chrome exe path.
and also puppeteer api to run on client's browser do we need to do something? I'm getting error because node module is empty.

also get below error while building
ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
Module not found: Error: Can't resolve 'child_process' in 'D:\repo\Client_Health_Hub\pcf\node_modules\puppeteer\lib\cjs\puppeteer\node'
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js 85:34-58
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js
Module not found: Error: Can't resolve 'child_process' in 'D:\repo\Client_Health_Hub\pcf\node_modules\puppeteer\lib\cjs\puppeteer\node'
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js 65:34-58
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/chownr/chownr.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\chownr'
 @ ./node_modules/chownr/chownr.js 3:11-24
 @ ./node_modules/tar-fs/index.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/extract-zip/index.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\extract-zip'
 @ ./node_modules/extract-zip/index.js 8:17-30
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/fd-slicer/index.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\fd-slicer'
 @ ./node_modules/fd-slicer/index.js 1:9-22
 @ ./node_modules/yauzl/index.js
 @ ./node_modules/extract-zip/index.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\fs.realpath'
 @ ./node_modules/fs.realpath/index.js 8:9-22
 @ ./node_modules/glob/glob.js
 @ ./node_modules/puppeteer/node_modules/rimraf/rimraf.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\fs.realpath'
 @ ./node_modules/fs.realpath/old.js 25:9-22
 @ ./node_modules/fs.realpath/index.js
 @ ./node_modules/glob/glob.js
 @ ./node_modules/puppeteer/node_modules/rimraf/rimraf.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/glob/glob.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\glob'
 @ ./node_modules/glob/glob.js 42:9-22
 @ ./node_modules/puppeteer/node_modules/rimraf/rimraf.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/glob/sync.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\glob'
 @ ./node_modules/glob/sync.js 4:9-22
 @ ./node_modules/glob/glob.js
 @ ./node_modules/puppeteer/node_modules/rimraf/rimraf.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts

ERROR in ./node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in 'D:\repo\Client_Health_Hub\pcf\node_modules\mkdirp'
 @ ./node_modules/mkdirp/index.js 3:9-22
 @ ./node_modules/tar-fs/index.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js
 @ ./node_modules/puppeteer/lib/cjs/puppeteer/node.js
 @ ./node_modules/puppeteer/cjs-entry.js
 @ ./coverageReportControl/index.ts
