### ISSUE TITLE
Font issue on Mac

### ISSUE THREAD

**Issue by CaledoniaProject** [puppeteer/puppeteer#735]
I'm using the following code on Mac OS (nodejs `8.4.0`)

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setRequestInterceptionEnabled(true);
    page.on('request', request => {
        const overrides = {};
        if (request.url === 'https://www.baidu.com') {
            overrides.method = 'POST';
            overrides.postData = 'a=b&c=d';
        }
        request.continue(overrides);
    });
    await page.goto('https://www.baidu.com');
    await page.screenshot({path: 'baidu.png'});

    browser.close();
})();
```

When I take a screenshot of `baidu.com`, I got the following result:

![baidu](https://user-images.githubusercontent.com/1357701/30245533-5e4101ee-960f-11e7-8837-452983740506.png)

When I do it again with Google Chrome,

![screen 2017-09-10 at 10 01 03](https://user-images.githubusercontent.com/1357701/30245528-4480c758-960f-11e7-9266-2cb4137e9039.jpg)

The one toke with puppeteer is different from the real browser, the font looks blured

Any ideas?

**Comment by CaledoniaProject** [comment]
If this can't be resolved, perhaps I can use another instance of Google Chrome to do the job?

**Comment by ebidel** [comment]
See https://github.com/GoogleChrome/puppeteer/issues/571#issuecomment-325404760.

**Comment by CaledoniaProject** [comment]
Awesome!
