### ISSUE TITLE
Extremely slow screenshot times on large viewports

### ISSUE THREAD

**Issue by mikeys** [puppeteer/puppeteer#736]
Some background - I'm building a service which converts SVGs into PNGs.
Up until now I've been spawning [Electron](https://github.com/electron/electron) workers (with Xvfb). The actual rendering worked great, but communicating with the Electron workers was a hassle and the fact that it isn't truly headless is resource consuming.

Needless to say that puppeteer + headless Chromium seems very ideal for my use case. 
The coding needed for implementing the same logic with puppeteer was very small and very clear.
The problem is that large screenshots (~5000x5000 pixels) which previously took 5 seconds, now take 30 seconds, and in more complex SVGs, can even get above 1 minute. Additionally - the actual screenshot image looks great.

**NOTE**: in Mac OSX, using `headless: false` flag, I get reasonable times. Unfortunately that's not the case in both Mac (with `headless: true`), Linux (with both `headless: true` with `Xvfb` and `headless: false`).

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Ubuntu Linux 
* URLs (if applicable): https://github.com/mikeys/puppeteer-slow-svg-example

**What steps will reproduce the problem?**

A very simple example code can be found at the following repository which was created to showcase this issue:
https://github.com/mikeys/puppeteer-slow-svg-example

1. Create a simple (single shaped) SVG document with an image pattern ([example](https://raw.githubusercontent.com/mikeys/puppeteer-slow-svg-example/master/pattern.svg))
2. Embed the SVG as part of an HTML document. Make sure to use large width/height (5000/5000) values for the embedded element ([example](https://raw.githubusercontent.com/mikeys/puppeteer-slow-svg-example/master/pattern.html))
3. Use the following code to take the desired screenshot (excerpt from [here](https://raw.githubusercontent.com/mikeys/puppeteer-slow-svg-example/master/index.js)):
```node
const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();
const url = `file://${__dirname}/pattern.html`
await page.goto(url);
await page.screenshot({path: 'example.png', clip: { width: 5000, height: 5000, x: 0, y: 0 }});
```

**What is the expected result?**
Screenshot finishes in reasonable time (~5 seconds).

**What happens instead?**
Screenshot takes a very long time (> 30 seconds).

**Comment by mikeys** [comment]
@aslushnikov @pavelfeldman guys, I know you got your hands full but I was wondering if there's any progress regarding this?

**Comment by CommanderXL** [comment]
I think that the speed of screenshot is related in the machine performance？I use Mac pro to screenshot for a 375 * 750 pic, It takes about 1s.

**Comment by mikeys** [comment]
@CommanderXL Give a try to my example project above. Let me know of your findings.

**Comment by pavelfeldman** [comment]
It takes 5s on my MBP. Trying to figure out where the bottleneck is: could you specify `type: 'jpeg'` and see how that affects the time?

**Comment by mikeys** [comment]
@pavelfeldman `jpeg` does not rectify the problem. Mac OSX is faster. In linux the results are much worse (30s +).

**Comment by eliseumds** [comment]
On MacOS, taking JPEG screenshots and decoding them with [node-jpeg-turbo](https://github.com/sorccu/node-jpeg-turbo) gave us a speed-up of ~60% on our regression tests. Most of the gains definitely came from the file format change (and not the decoding library).

**Comment by tcz** [comment]
I can confirm, I have the same issue. Large screenshots take an extreme amount of time.
Trying to render 7200x10800, takes more than 4 minutes!

In my case this had to do with the device scale factor that I sent to a rather large, irrational value such as 7,272727272727273.

If instead, I use `page.evalue` to scale the root element using CSS, it magically works fast.

```
await page.evaluate(function(factor) {
  var root = document.querySelector('html');

  root.style.transform='scale(' + factor + ')';
  root.style.transformOrigin='top left';
}, factor);
```

**Comment by zubson** [comment]
Hi @mikeys , did you find a way to work around this problem? I have the same problem in my project, on the big viewport (height ~ 12000px) screenshot can last ~ 10s on osx and ~ 40 on ubuntu.

**Comment by ansorre** [comment]
No new on this? I'm also getting more than one minute per screenshot even with just a 3000 x 3000 px viewport. Both on Windows and Linux.

**Comment by ziyunfei** [comment]
try `ignoreDefaultArgs: ['--disable-dev-shm-usage']` https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-puppeteerlaunchoptions

**Comment by dickie81** [comment]
> try `ignoreDefaultArgs: ['--disable-dev-shm-usage']` https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-puppeteerlaunchoptions

this worked for me... many thanks!

**Comment by surlyhacker** [comment]
> try `ignoreDefaultArgs: ['--disable-dev-shm-usage']` https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-puppeteerlaunchoptions

Would this have any effect on Windows?  (where there is no such thing as /dev/shm)

**Comment by omerman** [comment]
> I can confirm, I have the same issue. Large screenshots take an extreme amount of time. Trying to render 7200x10800, takes more than 4 minutes!
> 
> In my case this had to do with the device scale factor that I sent to a rather large, irrational value such as 7,272727272727273.
> 
> If instead, I use `page.evalue` to scale the root element using CSS, it magically works fast.
> 
> ```
> await page.evaluate(function(factor) {
>   var root = document.querySelector('html');
> 
>   root.style.transform='scale(' + factor + ')';
>   root.style.transformOrigin='top left';
> }, factor);
> ```

@tcz Most underrated comment here. thanks man.
