### ISSUE TITLE
could I use puppeteer to visit `chrome-devtools://devtools/bundled/inspector.html` ?

### ISSUE THREAD

**Issue by atian25** [puppeteer/puppeteer#737]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: mac
* URLs (if applicable): `chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/__ws_proxy__`

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I'm writing a lib to proxy `chrome-devtools` protocol, when write unittest for it, need to access it's debug page.

```js
// just use `node --inspect index.js` to find a debug url
const url = 'chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/__ws_proxy__';
await page.goto(url, { waitUntil: 'networkidle' });
```

**What is the expected result?**
- could visit `chrome-devtools` page at puppeteer
- could click some thing.

**What happens instead?**

> Error: Failed to navigate: chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__

**Comment by atian25** [comment]
Update:

```js
const browser = await puppeteer.launch({
  // only success at `headless: false` even args is allow
  headless: false,
  args: [ '--allow-file-access-from-files' ],
});
```

**Comment by aslushnikov** [comment]
@atian25 out of curiosity, why would you want to open devtools remote debugging front-end?

**Comment by atian25** [comment]
for some test purpose, we are writing a inspector proxy, and I wonder whether use `puppeteer` to write some test for it.

https://github.com/whxaxes/inspector-proxy

if could, I will try to kill node process, then check if there is a `Reconnect` button, then click it to reconnect.

![image](https://user-images.githubusercontent.com/227713/30262655-4e702df8-9704-11e7-81f0-8dcd1e8d8a9c.png)

**Comment by aslushnikov** [comment]
@atian25 no, `chrome-devtools://devtools/bundled/inspector.html` is not accessible in headless.

However, devtools front-end is just a web-app, you can host your own version of it.

**Comment by dwelle** [comment]
For anyone interested, you can use an electron for this purpose. E.g. [nightmare](https://github.com/segmentio/nightmare) will do fine:

```js
const Nightmare = require("nightmare");
const inspector = require("inspector");

inspector.open( 9230 );

const night = Nightmare({
    show       : true,
    alwaysOnTop: false
});

const inspectorUrl = inspector.url().replace("ws://", "ws=");

night.goto(`chrome-devtools://devtools/bundled/inspector.html?${inspectorUrl}`)
    .then();
```

**Comment by aslushnikov** [comment]
@dwelle well, if headless mode is not needed, then pptr will work as well:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.goto('chrome-devtools://devtools/bundled/inspector.html');
  // Success!..
})();
```
