### ISSUE TITLE
Cant catch errors with .goto

### ISSUE THREAD

**Issue by privatenumber** [puppeteer/puppeteer#738]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: mac 10.12.6

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');

puppeteer.launch({ headless: false }).then(async function(browser) {

	const newPage = await browser.newPage();

	// newPage.goto('http://google.com', { timeout: 1 })
	// 	.catch(function(err) {});

	// newPage.goto('http://google.com', { timeout: 1 })
	// 	.then(function() {}, function(err) {});

	try {
		await newPage.goto('http://google.com', { timeout: 1 });
	} catch (e) {}
});
```

**What is the expected result?**
To be able to silence the error.

**What happens instead?**
The error isn't caught.
```
(node:33288) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 1ms exceeded
(node:33288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33288) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

Listening to `unhandledRejection` on the process returns this:
```
Promise {
  <rejected> Error: Navigation Timeout Exceeded: 1ms exceeded
    at NavigatorWatcher.waitForNavigation (./node_modules/puppeteer/lib/NavigatorWatcher.js:74:13)
    at <anonymous> }
```

**Comment by kaushiksundar** [comment]
Here is a related issue. #718

**Comment by ebidel** [comment]
Looks like this too: https://mobile.twitter.com/thejameskyle/status/905921542906712064

**Comment by privatenumber** [comment]
@kaushik-sundar 
Doesn't look related... The reason why that error is happening in that Issue is explained in the last post by @aslushnikov. Unlike the code there, I am trying to try-catch an error from a function call that is prepended by `await`.

@ebidel 
> Always `return await` or if you wrap with try-catch it won't be caught

I am using `await`. Don't think returning it will make a difference but I can try later.

**Comment by zubair-saif** [comment]
*Zubair Saif*

**Comment by aslushnikov** [comment]
@hirokiosame that's a bug, thanks for reporting!

**Comment by indooorsman** [comment]
@aslushnikov I'm sorry but i still meet this bug with puppeteer v1.4, node v10.1:

<img width="1130" alt="wx20180524-130605 2x" src="https://user-images.githubusercontent.com/4919405/40465459-55c75d02-5f53-11e8-8e30-6c0520fc5b12.png">
