### ISSUE TITLE
puppeteer and addScriptTag : This document requires 'TrustedScript' assignment

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#7381]
Since latest chrome update, I am not able to inject Jquery any more: 

https://stackoverflow.com/questions/68140810/puppeteer-and-addscripttag-this-document-requires-trustedscript-assignment

ALl these fail:

```
await page.addScriptTag({url: "https://code.jquery.com/jquery-3.2.1.min.js" });

await page.addScriptTag({ path: './jquery-3.2.1.min.js' });

await page.addScriptTag({ content: jquery });
```

Any idea ?

**Comment by mathiasbynens** [comment]
Which page are you trying to inject jQuery in? Does it have a CSP set? In that case, you might wanna try `await page.setBypassCSP(true)`.
