### ISSUE TITLE
how to load extension using puppeteer.connect() method?

### ISSUE THREAD

**Issue by fajarikhsan22** [puppeteer/puppeteer#7385]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.0.0
* Platform / OS version: windows 8.1 and Ubuntu
* URLs (if applicable):
* Node.js version:  14

**What steps will reproduce the problem?**
i use gologin service. gologin is a browser antidetect service where I can fake my browser identity / can manage browser fingerprint. so I can freely do web-scrapping without being detected.

in this case I want to be able to **load my extension into that browser** using the puppeteer.connect() method.

here's the code:

`const puppeteer = require('puppeteer-core');
const GoLogin = require('gologin');

(async () => {
  const GL = new GoLogin({
    token: 'yU0token',
    profile_id: 'yU0Pr0f1leiD',
  });

  const { status, wsUrl } = await GL.start();
  const browser = await puppeteer.connect({
    browserWSEndpoint: wsUrl.toString(),
    ignoreHTTPSErrors: true,
  });

  const page = await browser.newPage();
  await page.goto('https://myip.link/mini');
  console.log(await page.content());
  await browser.close();
  await GL.stop();
})();

**What is the expected result?**
i want the browser to be able to load the extension like for example:

`const customArgs = [
        '--load-extension=./path/to/extension'
    ]

const browser = await puppeteer.connect({
    browserWSEndpoint: wsUrl.toString(),
    ignoreHTTPSErrors: true,
    ignoreDefaultArgs: ["--disable-extensions", "--enable-automation"],
    args: **customArgs**

  });

**What happens instead?**
I think it's also worth trying that way. but I don't think it's the right way.

I've also thought about trying to override **puppeteer.defaultArgs()**. but in the **puppeteer.connect()** method there is no **args** object for me to pass **'--load-extension'** as in the **puppeteer.launch()** method.

please help me solve this problem

**Comment by Slava-stack** [comment]
I have a similar issue rightnow. And it's all about how to interact with chrome extension over puppeteer.connect. 
Have you been successful with your interactions?
