### ISSUE TITLE
AttributeError: 'Browser' object has no attribute 'setDefaultNavigationTimeout'

### ISSUE THREAD

**Issue by batpurev** [puppeteer/puppeteer#7393]
Hi Gurus,

I having this error message whenever trying to set the timeout of the either browser or the page.

`AttributeError: 'Browser' object has no attribute 'setDefaultNavigationTimeout'`

Following is my code snippet:
from bs4 import BeautifulSoup
from playwright.sync_api import sync_playwright
import validators
import os
import asyncio
from playwright.async_api import async_playwright
from pprint import pprint

pages = set()
```

# Use sync version of Playwright
def get_links(page_url):
    global pages
    valid=validators.url(page_url)
    if valid==True:
        #with async_playwright() as p:
        with sync_playwright() as p:
            # Launch the browser
            browser = p.chromium.launch()
            #browser.setDefaultTimeout(0)
            browser.setDefaultNavigationTimeout(0)
            # Open a new browser page
            page = browser.new_page()
            page.setDefaultTimeout(0)
            # Open our test file in the opened page
            page.goto(page_url)
            page_content = page.content()
```

both of browser.setDefaultNavigationTimeout(0) and  page.setDefaultTimeout(0) is throwing above error while the manual provided on [https://playwright.dev/docs/api/class-page#page-set-default-timeout](https://playwright.dev/docs/api/class-page#page-set-default-timeout) page says one can SET the time out but it appears I am doing it wrong. Please advise me how to set the time out. 

thanks

**Comment by batpurev** [comment]
here is screen shot of the error message.
![image](https://user-images.githubusercontent.com/3252495/124217095-389f3780-db2a-11eb-8d5f-234a5d270c69.png)

**Comment by KaleemArshad** [comment]
Hello,

browser.setDefaultNavigationTimeout(0)  _**# browser have litteraly no attribute setDefaultNavigationTimeout**_

**_Its The Page which Have this Attribute:_**
await page.setDefaultNavigationTimeout(0)

And You also have to use "**_Async awai_**t" and have to wait whenever anything is returning a Promise, You can also use "**_then and catch_**" for **_Promise Handling_**.
