### ISSUE TITLE
`await page.content()` stuck forever?

### ISSUE THREAD

**Issue by ecolss** [puppeteer/puppeteer#7395]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.1.0
* Platform / OS version: macOS Big Sur, 11.4
* URLs (if applicable): https://venturebeat.com/
* Node.js version: v14.15.1

**What steps will reproduce the problem?**
Just copy and run the following code:
```js
import pptr from "puppeteer";

async function main(args) {
    let browser = await pptr.launch({
        headless: false,
        defaultViewport: null,
    });

    const url = "https://venturebeat.com/";
    let page = await browser.newPage();
    page.on('console', consoleObj => console.log(consoleObj.text()));

    await page.goto(url, { waitUntil: "networkidle2", timeout: 10000 })
      .catch(err => console.log(`page.goto rejected, err: ${err}`)),
    console.log(`stop loading`);

    // NOTE: seems stuck here forever?
    let contentSize = (await page.content()).length;
    console.log(`content size = ${contentSize}`);

};

main();
```

**What is the expected result?**
Since `page.goto` would timeout, so `.catch` handles the error.
After that I expect page content size on console, i.e. reach and run the following line of code
```js
console.log(`content size = ${contentSize}`)
```

**What happens instead?**
Never print anything, code stuck right at the `await page.content()`, forever.

**Comment by Poyoman39** [comment]
Seems linked to #4011
