### ISSUE TITLE
Error launching Chromium: Passthrough is not supported, GL is swiftshader

### ISSUE THREAD

**Issue by Rendez** [puppeteer/puppeteer#7408]
`[21581:259:0706/131446.110056:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader`

Big Sur: 11.4 (20F71)
Puppeteer: 10.1.0
Node: 16.0.0

```
launch: {
  headless: false,
  args: [
    '--remote-debugging-port=9222',
    '--no-sandbox',
    '--no-zygote',
    '--disable-gpu',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--disable-breakpad',
    '--enable-logging',
    '--no-first-run',
    '--start-maximized',
    '--disable-default-apps'
  ],
  browserContext: 'incognito'
}
```

**Comment by Rendez** [comment]
I thought this was the main problem I was facing when updating to 10.1.0, but this is a Chromium error, but didn't crash Chromium nor affect the puppeteer launch. In my case it was something else (host/port problem).

**Comment by doujiaocs** [comment]
So how did you solve it in the end？I have the same problem as you

**Comment by doujiaocs** [comment]
> 

So how did you solve it in the end？I have the same problem as you
