### ISSUE TITLE
How do I click a Google Pay Button element?

### ISSUE THREAD

**Issue by chalitbkb** [puppeteer/puppeteer#7426]
STEP 1: How do I click a Google Pay Button element? 
![image](https://user-images.githubusercontent.com/32437546/125858603-248de193-6852-4916-aa94-35298edf1137.png)
 (Basic example)

- I can press the pay button. But the Next button cannot be pressed because the element is in iframe format.

https://developers.google.com/pay/api/web/guides/resources/demos

**Comment by qinglong-zeng** [comment]
You can read this document. May be help you.
https://github.com/puppeteer/puppeteer/blob/v10.1.0/docs/api.md#class-frame
