### ISSUE TITLE
Firefox not working in latest version

### ISSUE THREAD

**Issue by marianomd** [puppeteer/puppeteer#7437]
Hello, I'm trying to use Firefox browser without luck.

Puppeteer version: 10.1.0
Firefox version: linux-92.0a1 (installed by Puppeteer)

Error: Timed out after 30000 ms while trying to connect to the browser! 

Enabling dumpio, I have this output:

```
Exit Code: 1(General error)

Working directory: /var/www/html/webroot

Output:
================
38107
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL initialize failed
[GFX1-]: No GPUs detected via PCI
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt


Error Output:
================
*** You are running in headless mode.
```

**Comment by kirkkonen** [comment]
@marianomd have you managed to make it work? If yes, could you please share the parts of package.json and package-lock.json that are related to Puppeteer? Mine doesn't work at all and I'm wondering maybe the installation went wrong.
