### ISSUE TITLE
page.click(selector[, options]),clickCount  doesn't work

### ISSUE THREAD

**Issue by xuxk1** [puppeteer/puppeteer#7442]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:9.1.1
* Platform / OS version:mac 10.15.7
* URLs (if applicable):
* Node.js version:10.16.3

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1."compos.lsspacing_add",for page elements
2.const lsspacing_btn = await this.page.waitForSelector(compos.lsspacing_add); await lsspacing_btn.click({clickCount: 4});
3.set clickCount  doesn't work

**What is the expected result?**
Able to click the number of times set
**What happens instead?**
Actually setting the number of clicks does not work

**Comment by UsmanGhani-Emumba** [comment]
@xuxk1  Did you get the solution of it? because i have the same issue.

**Comment by xuxk1** [comment]
> @xuxk1 Did you get the solution of it? because i have the same issue.

Use "puppeteer": "^9.1.1" to resolve the problem

**Comment by xuxk1** [comment]
> @xuxk1 Did you get the solution of it? because i have the same issue.

await this.page.click(Po.tool_zoomInput, { clickCount: 2 });
await this.page.click(Po.tool_zoomInput, { clickCount: 2 });
Like executing twice can be solved

**Comment by UsmanGhani-Emumba** [comment]
what is Po.tool_zoomInput? You selector? so basically click count is not working. You are using the click statement twice
