### ISSUE TITLE
With Firefox some `framenavigated` events are not arriving

### ISSUE THREAD

**Issue by luiso1979** [puppeteer/puppeteer#7444]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.1.0 (FIREFOX)
* Platform / OS version: Macos 11.4
* URLs (if applicable): https://www.youtube.com and any video (e.g. https://www.youtube.com/watch?v=H1HlUe886Hs)
* Node.js version: v14.17.0

**What steps will reproduce the problem?**

Use the following code to log the visited URLs

    import {Frame, launch, Target} from "puppeteer";

    (async () => {
        const browser = await launch({headless: false, product: "firefox", defaultViewport: null});

        const pageOld = (await browser.pages())[0];

        browser.on("targetcreated", async (target: Target) => {
            const page = await target.page();
            page?.on("framenavigated", (frame: Frame) => {
                if (frame.parentFrame() === null) {
                    console.log(`URL Frame = ${frame.url()}`);
                }
            });
            console.log(`URL = ${page?.url()}`);
        });

        await browser.newPage();
        await pageOld.close();

        await new Promise(resolve => setTimeout(resolve, 100000));
    })();

Run the script and visit https://www.youtube.com , then after landing on the page with the videos, open one video (e.g. https://www.youtube.com/watch?v=H1HlUe886Hs)

**What is the expected result?**

The script should log at least both: 
- https://www.youtube.com
- https://www.youtube.com/watch?v=H1HlUe886Hs. (the selected video)

**What happens instead?**

The selected video (e.g.: https://www.youtube.com/watch?v=H1HlUe886Hs) is never logged. Therefore, I suppose no `framenavigated` was fired for the video URL.

Is there something missing with Firefox? This problem doesn't happen with Chrome. 

Thanks in advance, 
Regards
Luis

**Comment by MatteoScapin** [comment]
I'm having exactly the same issue

**Comment by frasuri94** [comment]
Please fix it, I have the same issue.
