### ISSUE TITLE
How to use puppeteer with nordVPN proxies ?

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#7447]
Hello,
Just trying to use puppeteer with nordVPN

I tried: 

```
page = await browser.newPage();
await useProxy(page, `socks5://myEmail:password}@fr806.nordvpn.com:1080`);
I also tried in args = []

'--proxy-server=socks5://myEmail:password@fr806.nordvpn.com:1080'
```

With no success. Any idea ?

**Comment by liukaigsx** [comment]
try `'--proxy-server=socks5://fr806.nordvpn.com:1080'` or `'--proxy-server=http://fr806.nordvpn.com:1080'`
and then
`await page.authenticate({
    username: myEmail,
    password: password
});`
