### ISSUE TITLE
Feature request: Run browser process as different user

### ISSUE THREAD

**Issue by Janpot** [puppeteer/puppeteer#745]
I'd like to be able to run the browser as a different user. That way I can apply a set of outbound firewall rules to it to prevent it from accessing anything in the internal network while still allowing the node process to do that.
The use-case for this lies in `rendertron`-like services that expose some of the browser functionality to the outside world. It could be a security threat if those were able to access internal IPs.

**Comment by aslushnikov** [comment]
@Janpot you can run the browser yourself and connect to it later with the [`puppeteer.connect`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerconnectoptions) method. At the very least you'd need to pass the `--remote-debugging-port` flag to the browser and parse its stdout to extract the browser target. Check out the [Launcher](https://github.com/GoogleChrome/puppeteer/blob/66676c0/lib/Launcher.js) implementation for an example.

The only thing that is missing is the executable path of the bundled browser.

**Comment by Janpot** [comment]
@aslushnikov That's roughly my current setup. we currently use `chrome-remote-interface` and `chrome-launcher` to do what you describe. I'm currently looking into replacing a few of our abstractions with `puppeteer`.

**Comment by Janpot** [comment]
By the way, I don't mind creating a PR that passes `uid` to the childprocess if that's something you would support. Or you would rather expose the path of bundled chromium, so the consumer can craft some custom command to pass to `executablePath `?

**Comment by aslushnikov** [comment]
@Janpot I'd rather expose executable path since it gives more freedom and makes API more "round".

**Comment by Janpot** [comment]
@aslushnikov I was thinking about this a bit more. I might be overthinking it a bit but in order for this to work for me I guess I'd need to do something like:
```sh
CHROME_PATH=$(node -e "console.log(require('puppeteer').executablePath())")
runuser headlessuser -c "$CHROME_PATH $@"
```
in my script. then pass this to `puppeteer.launch()`.

Another solution which could work without changing public API and which would simplify the above script would be to provide the `CHROME_PATH` directly to the environment when you spawn the child_process. the `options` object of the `spawn` method has a `env` property which could be used for this.
https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
In fact this would speed up launching the browser since it doesn't need to spin up a node process just to get out a path.

**Comment by aslushnikov** [comment]
@Janpot these scripts look scary.

Would it help you if we add a `uid` option to the `puppeteer.launch`? The option would be passed over to the internal `spawn` method.

```js
const browser = await puppeteer.launch({uid: headlessuserid}); 
```

**Comment by aslushnikov** [comment]
@Janpon the `puppeteer.executablePath()` lets you spawn your own chromium isntance with `child_process.spawn` method, if there's a need to. You'll be able to pass in the `uid` and `gid`.

Let me know if this would work for you.

**Comment by Janpot** [comment]
>Would it help you if we add a `uid` option to the `puppeteer.launch`?

That's basically my feature request in this ticket. What would also work for me is passing through `env` to the internal spawn. then I could do:

```js
const browser = await puppeteer.launch({
  executablePath: path.resolve(__dirname, 'start-chrome.sh'),
  env: { 
     CHROME_PATH: puppeteer.executablePath()
  }
}); 
```
and in the `start-chrome.sh`:
```sh
runuser headlessuser -c "$CHROME_PATH $@"
```

The problem with taking over launching the child process is that I also have to take over its lifecycle management. Not that that's impossible, it just defeats some of the purpose of using a utility library like `puppeteer`.

Anyway, I understand if you want to close this issue, I think I can craft something with the new API.

**Comment by aslushnikov** [comment]
@Janpot By default spawned process inherits environment  from `process.env` – so you should be able to do the following:

```js
process.env.CHROME_PATH = puppeteer.executablePath();
const browser = await puppeteer.launch({
  executablePath: path.resolve(__dirname, 'start-chrome.sh'),
}); 
```

**Comment by Janpot** [comment]
Ah yes, good idea, didn't think about that yet. Thanks!

**Comment by dbauszus-glx** [comment]
Are you still looking into the request for adding the uid as an option to the launch command?

**Comment by aslushnikov** [comment]
> Are you still looking into the request for adding the uid as an option to the launch command?

@dbauszus-glx we don't. The scenario described here was solved without introducing new API's.

If you have a need for the functionality, I'll appreciate if you create a new issue and describe your usecase there.
