### ISSUE TITLE
How to open the URL in incognito mode in brave browser?

### ISSUE THREAD

**Issue by byteshiva** [puppeteer/puppeteer#7450]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:10.1.0
* Platform / OS version: 5.8.0-3-amd64  SMP Debian 5.8.14-1~mx19+2 
* URLs (if applicable):
* Node.js version:v16.0.0

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    executablePath:"/usr/bin/brave-browser-stable",
    headless: false,
    args: [' --incognito']
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

_Please include code that reproduces the issue._
1. Additional Question: 
Brave browser is going to release a command-line argument to open Tor from brave-browser CLI. Therefore, I'd like to know how to open the URL in Tor Tab. 
2.
3.

**What is the expected result?**
It should open in incognito mode 
![image](https://user-images.githubusercontent.com/10637299/127680024-0ad954ab-aec3-4031-bc4e-fb1e4416dd69.png)

**What happens instead?**
It opens in normal tab mode.
![image](https://user-images.githubusercontent.com/10637299/127679997-488e3466-1bc2-4f2d-88a4-4b2a1a385024.png)

**Comment by mathiasbynens** [comment]
Use `browser.createIncognitoBrowserContext()`.

**Comment by byteshiva** [comment]
```
const puppeteer = require('puppeteer');

(async () => {
     const browser = await puppeteer.launch({
        headless: false,
     });
      // Create a new incognito browser context.
      const context = await browser.createIncognitoBrowserContext();
      // Create a new page in a pristine context.
      const page = await context.newPage();
      // Do stuff
      page.setJavaScriptEnabled(false)

      console.log(context.isIncognito());
      await page.goto('https://example.com');
      await page.screenshot({path: 'example.png', fullPage: true});
    //   await context.close();
    //   await browser.close();
})();   
    
```
Chrome Browser opens in incognito mode. I'm using Chromium Version 92.0.4512.0 (Developer Build) (64-bit)


![image](https://user-images.githubusercontent.com/10637299/127901359-8d004779-07f8-471a-814a-e36b5b65d2ee.png)



```
const puppeteer = require('puppeteer');

(async () => {
     const browser = await puppeteer.launch({
         executablePath: '/usr/bin/brave-browser-stable',
        headless: false,
     });
      // Create a new incognito browser context.
      const context = await browser.createIncognitoBrowserContext();
      // Create a new page in a pristine context.
      const page = await context.newPage();
      // Do stuff
      page.setJavaScriptEnabled(false)

      console.log(context.isIncognito());
      await page.goto('https://example.com');
      await page.screenshot({path: 'example.png', fullPage: true});
    //   await context.close();
    //   await browser.close();
})();   
    
```

brave browser (Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)) doesn't open in incognito mode.

![image](https://user-images.githubusercontent.com/10637299/127901627-8dbde07f-eb4c-4fbf-9d94-18a6c0504277.png)

**Comment by byteshiva** [comment]
> Use `browser.createIncognitoBrowserContext()`.

Hi @mathiasbynens 
This works only in chrome browser, it doesn't seem to work in the brave browser.
