### ISSUE TITLE
Set custom name on chrome address bar

### ISSUE THREAD

**Issue by nguyenhopquang** [puppeteer/puppeteer#7462]
Hi,
I'm using puppeteer lastest version and saw someone can set custom name on chrome address bar like this
How can i set this using puppeteer?
Thanks
![image](https://user-images.githubusercontent.com/16518296/127992932-63c77639-1ad0-48ab-9e94-238ff5e9a246.png)

**Comment by mathiasbynens** [comment]
Puppeteer doesn’t have any built-in API for this. I think what you're seeing there is a custom TLS certificate?

**Comment by nguyenhopquang** [comment]
I dont think so because it show even when i visit http website.
When i click on this, it show the current website certificate and nothing named like this custom text
