### ISSUE TITLE
PDF is not rendering SVGs when the container is offset

### ISSUE THREAD

**Issue by stevesendsgit** [puppeteer/puppeteer#7474]
Images (SVG in this case) are being dropped from PDF snaphots when the containing div has its top/left offset. PNG files are captured perfectly fine.

In the provided example, the withBleed page has the `#page` element with a `top: 32px` and `left: 32px`. This renders exactly as expected for the PNG output. The PDF output is missing the 2 large red SVG images.

The script will also render a `withoutBleed.pdf` file for comparison. This PDF is captured from a html page that has had the `top` and `left` values reset to `0px`.
 
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.1.0 (Have also tried every version up to and including v10)
* Platform / OS version: MacOS and Amazon Linux 2.
* URLs (if applicable):
* Node.js version: v12.18.1

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `mkdir -p /tmp/test-p && cd /tmp/test-p`
2. `yarn init`
3. `yarn add puppeteer`
4. `vim ./index.js`
```
const puppeteer = require('puppeteer');

/**
 * Capture both PNG and PDF page renders for comparison
 */
const snapshotPage = async (browser, url, name) => {
  const page = await browser.newPage();
  // Missing Image Example
  await page.goto(url, {
    waitUntil: ['networkidle0', 'load'],
    timeout: 0
  });
  await page.setDefaultTimeout(0);

  console.debug('Waiting for selector');
  await page.waitForSelector('#page');
  console.debug('Waiting for timeout');
  await page.waitForTimeout(4000);

  const width = 1675;
  const height = 1210;

  await page.addStyleTag(
    {'content': `@page { size: ${width}px ${height}px; margin: 0; }`}
  )

  await page.setViewport({
    width: width,
    height: height,
  });

  const pathPrefix = './';

  const filePath = `${pathPrefix}${name}.png`;
  console.debug(`Capturing screenshot ${filePath}`);
  await page.screenshot({
    path: filePath,
  });

  const pdfFilePath = `${pathPrefix}${name}.pdf`;
  console.debug(`Capturing screenshot ${pdfFilePath}`);
  await page.pdf({
    path: pdfFilePath,
    printBackground: true,
    pageRanges: '1',
    width: width,
    height: height,
  });
}

// Run the script
(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-gpu',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--homedir=/tmp',
      '--data-path=/tmp/data-path',
      '--disk-cache-size=0',
      '--disk-cache-dir=/tmp/cache-dir',
      '--font-render-hinting=none',
      '--no-first-run', // Perf
    ],
    ignoreHTTPSErrors: true, 
  });
  
  await snapshotPage(browser, 'http://pptr-pdf-missing-elements.s3-website-us-east-1.amazonaws.com/missing_images_with_bleed.html', 'withBleed');
  await snapshotPage(browser, 'http://pptr-pdf-missing-elements.s3-website-us-east-1.amazonaws.com/missing_images_without_bleed.html', 'withoutBleed');

  await browser.close();
})();
```
5. `node index.js`

**What is the expected result?**
The `withBleed.pdf` visually matches the `withBleed.png` file

**What happens instead?**
The `withBleed.pdf` file is dropping the red images.

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.

**Comment by stevesendsgit** [comment]
This still occurs with the latest version of Puppeteer and Node 14.
