### ISSUE TITLE
 interact with dom in waitForSelector handler  

### ISSUE THREAD

**Issue by vivien7512** [puppeteer/puppeteer#748]
in waitForSelector handler I have an issue :
when I want to interact with DOM, it triggers me an error

My code is bellow:
```
page
  .waitForSelector('input[value=update]')
  .then(() => {
    const inputValidate = await page.$('input[value=update]');
  });
```

Print me in co,sole text bellow:

> const inputValidate = await page.$('input[value=update]'); ^^^^
> 
> SyntaxError: Unexpected identifier at createScript (vm.js:74:10) at Object.runInThisContext (vm.js:116:10) at Module._compile (module.js:537:28) at Object.Module._extensions..js (module.js:584:10) at Module.load (module.js:507:32) at tryModuleLoad (module.js:470:12) at Function.Module._load (module.js:462:3) at Function.Module.runMain (module.js:609:10) at startup (bootstrap_node.js:158:16) at bootstrap_node.js:598:3

Howewer , ther are no worries if I don't want to interact with DOM in handler:
Code bellow works:
```
page
  .waitForSelector('input[value=update]')
  .then(() => {
    console.log('this is');
    console.log('it');
  });

```

Is it a bug or a bad usage?

**Comment by aslushnikov** [comment]
@vivien7512 you're missing `async` in your arrow function:
```js
page
  .waitForSelector('input[value=update]')
  .then(async () => { // <== note this "async". It is necessary to use await inside
    const inputValidate = await page.$('input[value=update]');
  });
```
