### ISSUE TITLE
How can i click a "special" button? 

### ISSUE THREAD

**Issue by Manyou99** [puppeteer/puppeteer#7489]
Hey guys, i want to code a bot. But i can't click a button on the website.

My Code:

```
async function checkout(){
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto(product_url);
    await page.waitFor(3000);
    await page.click("button[Class='sc-gtsrHT gqGzpd']", elem => elem.click());
}
```

the following code also doesen't work:
` await page.click('[aria-label="Alles akzeptieren"]',elem => elem.click());`
or
`await page.click('[data-testid="uc-accept-all-button"]',elem => elem.click());`

Error Message: 
`
No node found for selector: button[Class='sc-gtsrHT gqGzpd']
`

Element Info:
`
<button aria-label="Alles akzeptieren" role="button" data-testid="uc-accept-all-button" class="sc-gtsrHT gqGzpd">OK</button>
`

Pictures:
- https://i.stack.imgur.com/BYOnx.png (Button Info)
- https://i.imgur.com/of9Rjgo.png (Button)

Does anyone know what I'm doing wrong and how to do it right?

**Comment by ErtanOzdemir** [comment]
`await page.click("button[class='sc-gtsrHT']");`

Maybe lowercase 'c' helps you
