### ISSUE TITLE
Page.once doesn't clean up request interceptors

### ISSUE THREAD

**Issue by HitkoDev** [puppeteer/puppeteer#7495]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.2.0
* Platform / OS version: all
* URLs (if applicable): N/A
* Node.js version: 16

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```js
const interceptor = (request) => console.log(request.url())
page.once("request", interceptor)
page.goto(`http://google.com`)
```

**What is the expected result?**

Logs URL of the first request (http://google.com), then removes interceptor.

**What happens instead?**

Logs all URLs, including subsequent requests (e.g. CSS stylesheets).

**Comment by zeen** [comment]
This is likely due to the now fixed https://github.com/puppeteer/puppeteer/issues/7572 and seems to no longer be happening in `12.0.0`.
