### ISSUE TITLE
How to Bypass Cloudflare "Press and Hold" captcha?

### ISSUE THREAD

**Issue by taewookim** [puppeteer/puppeteer#7498]
Screenshot: https://i.postimg.cc/sfTznvgy/image.png

Cloudflare is adding 10-15'ish iframes.. so i thought i could get just around with it by  sending page.down().. but that's failing.

Tried querying the iframe html  and looking for the selector.. but that's not working either.

I tried Puppeter-extra w/stealth plugin. Still hit or miss randomly.

Has any one been able to consistently bypass this ?

**Comment by clouedoc** [comment]
Did you try to use CDP to execute the mouse action?

**Comment by taewookim** [comment]
> Did you try to use CDP to execute the mouse action?

can you give me an example?
