### ISSUE TITLE
Incognito context doesn't set cookies

### ISSUE THREAD

**Issue by btecu** [puppeteer/puppeteer#7505]
### Environment
* Puppeteer version: 10.1.0
* Platform / OS version: AWS Lambda
* Node.js version: 14

### Issue
Making a request with cookies using an incognito context does not appear to send the cookies:
```js
let context = await browser.createIncognitoBrowserContext();
let page = await context.newPage();
await page.setCookie({ name, value, domain });
```

If instead I use `let context = browser.defaultBrowserContext();` it works fine.

**Comment by Deniied** [comment]
Why do you need to use incognito? The normal browser doesn't save anything after it's closed.

**Comment by btecu** [comment]
I don't want to close the browser.
