### ISSUE TITLE
page.screenshot() hangs forever in Puppeteer@5.5.0

### ISSUE THREAD

**Issue by deepak-mali** [puppeteer/puppeteer#7507]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: Windows 10(64-bit)
* URLs (if applicable):
* Node.js version: v14.17.0

**What steps will reproduce the problem?**
I am migrating from Puppeteer 1.20.0 to 5.5.0 and during testing I found, Puppeteer hangs to capture the screenshot and websnapshot in headless mode.

When I take a screenshot with `fullPage: true` Puppeteer sends `Page.getLayoutMetrics` event to calculate the clip points like x, y coordinates on screen, width, height, and scale for the screenshot. This event hangs for some reason until the browser closes. Once the browser closes, it returns a response saying target closed.
With `fullPage: false:` In this case, Puppeteer does not calculates the clips for screenshots and sends the `Page.captureScreenshot` event to capture the screenshots but Puppeteer returns us an `internal error.`

I would not able to share the exact code but my code looks something like mentioned below.

_Please include code that reproduces the issue._
~~~
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    "args": [
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--disable-popup-blocking",
      "--no-sandbox",
      "--unlimited-storage",
      "--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36",
      "--window-size=1366,768"
    ],
    "executablePath": null,
    "devtools": false,
    "headless": true,
  });
  const page = await browser.newPage();
  await page.goto('https://example.com'); //
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
~~~

**What is the expected result?**
Puppeteer should not hang and return the response or error.

**What happens instead?**
Puppeteer hangs until browser closes.

**Comment by themarcel** [comment]
I fixed this downgrading to 7.0.1

**Comment by sadym-chromium** [comment]
Is the issue persists on the latest version?

**Comment by themarcel** [comment]
> Is the issue persists on the latest version?

Yes, for me it still happens with `puppeteer@10.4.0` and `puppeteer@8.0`

**Comment by patrickhulce** [comment]
In case it helps anyone else, I've run into this in a number of scenarios and these are the two workarounds I've needed.

- Bring page to foreground `await page.bringToFront()` (anecdotally, only necessary in headful? 🤷 )
- Force a rAF `await page.evaluate(() => requestAnimationFrame(() => {}))` (essential on linux when `--disable-frame-rate-limit` is used)

**Comment by acsbendi** [comment]
This is still an issue in the latest version. @patrickhulce's first fix works though, but I think it should be done by Puppeteer automatically.

**Comment by 4skinSkywalker** [comment]
Still an issue

**Comment by sumdy-c** [comment]
Все еще актуально для     "puppeteer": "^24.4.0",
