### ISSUE TITLE
Mac M1 Chromium non headless mode crashes very often. Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by aelzhanova** [puppeteer/puppeteer#7511]
I use codeceptjs 3.1.0 with puppeteer 3.0.0. On Mac not M1 all tests are good, on the M1 when I run tests the browser (chromium) crashed in any moment, and I see the error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. And the same situation for all my colleagues on my work - the same tests are work on mac not m1, and chromium crashes on mac m1 for each my colleague. Chromium crashes in most cases of run. So test can pass without error in 1 case from 10 runs. It's very interferes with work

The important thing is non headless mode
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 3.1.0
* Platform / OS version: Mac M1 2020 (air and pro both)
* URLs (if applicable):
* Node.js version: 14.17.5

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I open page, login, open page by url using some mocks and then made screen of page and compare with etalon screen

**What is the expected result?**
test passed from begin to end

**What happens instead?**
test failed because chromium crashed in any moment of test

**Comment by GmBodhi** [comment]
I think you're explicitly closing the page in between some processes. It'll be helpful if you could share the relevant code.
