### ISSUE TITLE
Error on Google Cloud Run

### ISSUE THREAD

**Issue by nzakas** [puppeteer/puppeteer#7519]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.2.0
* Platform / OS version: node14-slim
* URLs (if applicable):
* Node.js version: 14

**What steps will reproduce the problem?**

Create a Node.js application that runs Puppeteer and deploy to Google Cloud Run. The default Node.js build pack will show this error when attempting to start Chromium:

> Failed to launch the browser process!
>/usr/src/app/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
>
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

I can also reproduce using this Dockerfile:

```
FROM node:14-slim

# Create and change to the app directory.
WORKDIR /usr/src/app

# ia32-libs missing
RUN apt-get update && apt-get install -y lib32z1 lib32ncurses5

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production

# Copy local code to the container image.
COPY . ./

# Run the web service on container startup.
CMD [ "npm", "start" ]
```

**What is the expected result?**

Chrome starts up and Puppeteer runs.

**What happens instead?**

Error message described above.

**Comment by acro5piano** [comment]
Did you try install every dependencies?

```Dockerfile
# They are required to run Puppeteer in a Docker container
RUN apt -y update && apt -y install \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    ibatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    lsb-release \
    wget xdg-utils \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by nzakas** [comment]
That worked, thanks! I'm going to send a pull request to update the troubleshooting docs for this.
