### ISSUE TITLE
DOH Domain Over HTTPS Secure DNS using Puppeteer How to?

### ISSUE THREAD

**Issue by raakyat** [puppeteer/puppeteer#7525]
How to use DOH in puppeteer? i want to change my DNS to 1.1.1.1 cloudflare for example to bypass internet connection censorship

**Comment by NN-Binary** [comment]
Same issue here, no one seems to reply on stack as well. Anyone?

**Comment by RuralDependencies** [comment]
It appears that you can't do it with Puppeteer, you would have to modify manually the Chrome Profile (in the Settings) in order to do it.

**Comment by jschfflr** [comment]
@raakyat Thanks for taking the time to report this issue!
Please take a look at https://bugs.chromium.org/p/chromium/issues/detail?id=799753#c8
and pass the command line arguments to the `args` parameter in `puppeteer.launch` like this:

```js
puppeteer.launch({
  args: [
    '--enable-features="dns-over-https<DoHTrial"',
    ' --force-fieldtrials="DoHTrial/Group1"',
    '--force-fieldtrial-params="DoHTrial.Group1:server/https%3A%2F%2Fcloudflare-dns%2Ecom%2Fdns-query/method/POST'
  ]
})
```
Closing this for now but feel free to reopen if that doesn't work!

**Comment by chocotar** [comment]
> @raakyat Thanks for taking the time to report this issue! Please take a look at https://bugs.chromium.org/p/chromium/issues/detail?id=799753#c8 and pass the command line arguments to the `args` parameter in `puppeteer.launch` like this:
> 
> ```js
> puppeteer.launch({
>   args: [
>     '--enable-features="dns-over-https<DoHTrial"',
>     ' --force-fieldtrials="DoHTrial/Group1"',
>     '--force-fieldtrial-params="DoHTrial.Group1:server/https%3A%2F%2Fcloudflare-dns%2Ecom%2Fdns-query/method/POST'
>   ]
> })
> ```
> 
> Closing this for now but feel free to reopen if that doesn't work!

unfortunately it dosesn't work
