### ISSUE TITLE
after goto, queryselectorall return null, why

### ISSUE THREAD

**Issue by bgachip** [puppeteer/puppeteer#7532]
You can see the code below.
1. step: Login Page
2. Car models list, href there is the valid url to within car's category list
3. I can see the category list the popup chromium but the element is not detected, i tried a lot of methods but there were unsuccessfull

Maybe it is working wrong because of a bot blocker?

`

      const puppeteer = require("puppeteer");
      const nodeConsole = require("console");
      const parser = require("xml2json");
      const http = require("http");
      const Apify = require("apify");
      
      // This is where we'll put the code to get around the tests.
      const preparePageForTests = async (page) => {
        // Pass the User-Agent Test.
        const userAgent =
          "Mozilla/5.0 (X11; Linux x86_64)" +
          "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.39 Safari/537.36";
        await page.setUserAgent(userAgent);
      };
      
      (async () => {
        try {
          var myConsole = new nodeConsole.Console(process.stdout, process.stderr);
          myConsole.log("Hello World!");
      
          const browser = await puppeteer.launch({ headless: true });
      
          const page = await browser.newPage();
          await preparePageForTests(page);
          // Pass the User-Agent Test.
      
          await page.setViewport({
            width: 1366,
            height: 768,
          });
      
          // 1.step Login Page
          await page.goto(
            "https://weborders.tepper.nl/websolutions/?username=#USERNAME&password=PW"
          );
      
          // logout check
          await page.waitForSelector(
            "#MainContent_WSLoginStatus1_WSLoginStatus_1461_hyperlinkLogout"
          );
         
          // models page navigation
          await page.goto(
            "https://weborders.tepper.nl/websolutions/default.aspx?wsmt=wscontent&code=zoeken%20op%20automerk%20en%20model"
          );
      
          await page.waitForSelector(
            "#MainContent_ModuleContent_WSModule1_WSContent_1461_pnlPrint"
          );
      
          myConsole.log("A");
          const promise = page.waitForNavigation({ waitUntil: "domcontentloaded" });
      
          await page.goto(
            "https://weborders.tepper.nl/websolutions/default.aspx?wsmt=wsitemlist&wssicatnavcategory=MMC&wssicatnavproductgroup=020&wssicatnavsearchstringempty=1"
          );
      
          await promise;
      
          myConsole.log("B");
      
          //category list block, it exists
          var lvl2category = await page.evaluateHandle(() => {
            return document.querySelectorAll(".ws-search-list-grp");
          });
      
          myConsole.log(lvl2category.length); // result is undefined but it should be 20(browser console length check is 20), lvl2category is undefined
        } catch (error) {
          console.error(error);
        }
      })();

`

**Comment by jschfflr** [comment]
@bgachip 
Thanks for taking the time to report this issue!

The `page.evaluateHandle` returns a handle to something in Chromium. Please use the following snippet instead:
```
var lvl2category = await page.evaluate(() => {
  return document.querySelectorAll(".ws-search-list-grp").length;
});
```
