### ISSUE TITLE
element.screenshot() capture wrong screen area

### ISSUE THREAD

**Issue by 3wweiweiwu** [puppeteer/puppeteer#7533]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.2.0
* Platform / OS version: Windows 10
* URLs (if applicable): www.google.com
* Node.js version:v14.17.5

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
        let option = {
            "executablePath": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
            headless: false,
            defaultViewport: null
        }
        const browser = await puppeteer.launch(option)

        const page = await browser.newPage();           // open new tab
        await page.goto('https://google.com');          // go to site

        await page.waitForSelector('#hplogo');          // wait for the selector to load
        const element = await page.$('#hplogo');        // declare a variable with an ElementHandle
        await element.screenshot({ path: 'google.png' }); // take screenshot element in puppeteer
        await browser.close();       

**What is the expected result?**
The screenshot is taken at a wrong place
![image](https://user-images.githubusercontent.com/14018114/131235901-a5d1ebc8-74fd-4a80-b2fb-afb7fc1247d0.png)

**What happens instead?**
![google](https://user-images.githubusercontent.com/14018114/131235877-f11ca24a-17d0-4b1e-b916-fec68a7770c2.png)

**Comment by 3wweiweiwu** [comment]
This work around seems to be working fine.

`        let option = {
            "executablePath": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
            headless: false,
            defaultViewport: null
        }
        const browser = await puppeteer.launch(option)

        const page = await browser.newPage();           // open new tab
        await page.goto('https://google.com');          // go to site

        // Далее #hplogo - требуемый нам селектор
        await page.waitForSelector('#hplogo');          // wait for the selector to load
        const element = await page.$('#hplogo');        // declare a variable with an ElementHandle
        let pos = await element.boundingBox()
        await element.screenshot({ path: 'google.png' }); // take screenshot element in puppeteer
        await page.screenshot({ path: 'hplogo.png', clip: { x: pos.x, height: pos.height, y: pos.y, width: pos.width } })
        await browser.close();                          // close browser`

**Comment by xuxk1** [comment]
me tooI also encountered a similar problem

**Comment by xuxk1** [comment]
I also encountered a similar problem

**Comment by fmoessle** [comment]
Me too.

**Comment by hottomato-c** [comment]
Hey folks, would you like to give a go using `headless: true` ?

**Comment by 3wweiweiwu** [comment]
In my case, I cannot use headless:true because my use case require UI to be displayed while taking the screenshot. I end up taking a screenshot and them crop it with 3rd party javascript library.

**Comment by hottomato-c** [comment]
👍 good to see you got the workaround. Alternatively I think there are some other options would work: 
1. use v9.1.0 as I believe the issue is caused by this [commit](https://github.com/puppeteer/puppeteer/commit/859135adb638a5c30e468718173d25b3ed4c0fba) in release v10.0.0 sadly. (can switch back to latest version once this issue is fixed)
2. use latest version and Firefox as browser

**Comment by fmoessle** [comment]
Downgrading to 9.1.1 solved the issue for me.

**Comment by PeterCassell92** [comment]
Have encountered this issue whilst using puppeteer 13.0.1 and when headless: false is used.

I may try downgrading to 9.1.1 as suggested though it is not essential for me as I can still run my tests without using headless: false

**Comment by ali-habibzadeh** [comment]
This issue is still happening in 2023

**Comment by juliansyahrifqi** [comment]
I'm using v22.2.0 and solve by using ``boundingBox`` function. See [https://pptr.dev/api/puppeteer.elementhandle.boundingbox](https://pptr.dev/api/puppeteer.elementhandle.boundingbox)

The ``boundingBox`` is return ``{ x: positionX, y: positionY, width: widthOfElement, height: heightOfElement }``. It can use for the ``clip`` option for the ``screenshot`` function

```javascript
const element = await mainFrame.$("element-selector");
const boundingBox = await element.boundingBox();

if (boundingBox) {
  const clip = {
    x: boundingBox.x,
    y: boundingBox.y,
    width: boundingBox.width,
    height: boundingBox.height,
  };
  await page.screenshot({ path: "image.png", clip: clip });
}

```
