### ISSUE TITLE
Puppeteer fails to capture the downloaded file

### ISSUE THREAD

**Issue by v-akash-freightwalla** [puppeteer/puppeteer#7535]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: puppeteer-extra(3.1.16)
* Platform / OS version: ubuntu
* URLs (if applicable):
* Node.js version: v12

**What is the expected result?**

1. I am trying to download a PDF document using puppeteer from a website.
2. On click of the download icon, the PDF file must get downloaded using the page._client.send('Page.setDownloadBehavior', {}); 

**What happens instead?**

1. But, when we click on the PDF file, new tab navigation occurs & the file is not downloaded.
2. No error occurs, the script executes fine, but the file does not get downloaded.

Kindly provide any solution, if applicable.

**Comment by jeasoncc** [comment]
could you provide the website url?
i will try

**Comment by jschfflr** [comment]
Using Puppeteer to download files is currently not properly supported. Please see #299 for details.
