### ISSUE TITLE
[Question] Measuring memory consumption since chrome 91

### ISSUE THREAD

**Issue by krausest** [puppeteer/puppeteer#7536]
I ran into an issue with getting correct data from chrome and I'm looking for help though this issue isn't unique to puppeteer and may not even be considered a bug. So it would be fair to just close this issue again as it's rather not a puppeteer bug, but I hope somebody has an idea that helps me.

Background: I'm the maintainer of the js-framework-benchmark. This is a benchmark for a few frameworks that measures the duration and memory consumption for simple table operations. For the latter I got a [bug report ](https://github.com/krausest/js-framework-benchmark/issues/916) that for a few frameworks the memory consumption wasn't correct since chrome 91. The benchmark currently uses chromedriver so I hoped that using puppeteer resolves this issue, but it didn't and showed the same characteristics. This is why this issue isn't unique to puppeteer, but I'm desperate enough to ask for help here...

Steps to reproduce:

1. Manual testing:
Open https://stefankrause.net/chrome-perf/frameworks/keyed/domvm/index.html and click "create 1,000 rows" 15 times.
Inspect JS heapsize

![Screenshot from 2021-08-30 21-49-27](https://user-images.githubusercontent.com/3374055/131397683-72885e31-09ea-42ad-9e10-a01d56a047d3.png)

Note that memory goes up and down as expected.

2. Automatic testing
create a new directory:
`npm install puppeteer` which installs version 10.2.0 
run the follwing code to automate the manual testing:
```
const puppeteer = require('puppeteer');

const countObjects = async (page) => {
    const prototypeHandle = await page.evaluateHandle(() => Object.prototype);
    const objectsHandle = await page.queryObjects(prototypeHandle);
    const numberOfObjects = await page.evaluate((instances) => instances.length, objectsHandle);

    await Promise.all([
        prototypeHandle.dispose(),
        objectsHandle.dispose()
    ]);

    return numberOfObjects;
};

async function runPuppeteer24(url, name)
{
    const width = 1200;
    const height = 800;
    const browser = await puppeteer.launch(
        { headless: false, 
            ignoreDefaultArgs: ['--enable-automation'],
        args: [
            `--window-size=${ width },${ height }`,
        ],
        defaultViewport: {
            width,
            height
        }});
    const page = await browser.newPage();
    await page.goto(url);

    for (let i = 0; i < 15; i++) {
        await page.click('#run');
        let element = await page.waitForXPath('//tbody/tr[1000]/td[1]');
        let value = await page.evaluate(el => el.innerText, element)
        let expected = (1000 * (i + 1)).toFixed();
        if (expected != value) {
            console.log("**** assertion failed");
            return;
        }
        await page.waitForTimeout(1000);
        // let count2 = await countObjects(page);
        let metrics = await page.metrics();
        let memory24_after_GC = metrics.JSHeapUsedSize;
        console.log("heap size:",memory24_after_GC);
    }

    await browser.close();
}

async function main() {
    const u = {name:'domvm', url:'https://stefankrause.net/chrome-perf/frameworks/keyed/domvm/index.html'};
    //const u = {name:'vanilla', url:'https://stefankrause.net/chrome-perf/frameworks/keyed/vanillajs/index.html'};
    await runPuppeteer24(u.url, u.name);
}

main().then(() => {
    console.log("finished");
})
```
it reports (for the domvm implementation):
```
heap size: 3720992
heap size: 5171740
heap size: 6504404
heap size: 7830648
heap size: 9109288
heap size: 10859196
heap size: 12506356
heap size: 14252100
heap size: 14796444
heap size: 15746384
heap size: 17526844
heap size: 19313244
heap size: 21039016
heap size: 21356628
heap size: 22990020
```
Looks like memory is never reclaimed by the gc.
In the code above you find two commented out lines. The first calls page.queryObjects() which should force a GC. Results are a bit lower, but still increasing.
The second commented out line is for another implementation (vanilla Javascript). This results in:
```
heap size: 2562572
heap size: 2321596
heap size: 2687216
heap size: 2470604
heap size: 2836084
heap size: 2458300
heap size: 2815468
heap size: 3172908
heap size: 2803100
heap size: 3160380
heap size: 1316404
heap size: 1673720
heap size: 2031032
heap size: 2388528
heap size: 2745800
```
At some point the GC kicks in and the values go up and down as expected.

There are multiple things I don't understand here and I'd be very thankful for any help:

1. for domvm and page.queryObjects commented out: Why doesn't the GC kick in as in the chrome timeline? (It does for vanillajs, but not for domvm. Changing the timeout value doesn't change that).

2. For domvm with page.queryObjects forcing a GC. Why is the heap size still increasing? If you force a GC when  testing manually in chrome the heap size behaves completely differently and memory goes down after each GC.

Thanks a lot for any help!

**Comment by mathiasbynens** [comment]
@OrKoN @szuend @mlippautz, any idea what's going on here?

**Comment by OrKoN** [comment]
I am not sure exactly what's going on but it might be useful to take a heap snapshot between iterations (see https://chromedevtools.github.io/devtools-protocol/tot/HeapProfiler/#method-takeHeapSnapshot, https://chromedevtools.github.io/devtools-protocol/tot/HeapProfiler/#event-addHeapSnapshotChunk). One thing that takeHeapSnapshot would do is trigger a complete GC. Also you would be able to see what exactly is retaining objects if there is a memory leak.

**Comment by krausest** [comment]
Running in chrome and taking a heap snapshot after each "create 1,000 rows" looks like that:
<img width="569" alt="Bildschirmfoto 2021-08-31 um 22 23 55" src="https://user-images.githubusercontent.com/3374055/131570937-342c2a1c-99d4-41c2-830a-038d742ef6c4.png">
And taking the heap snapshots via puppeteer creates the following:
<img width="878" alt="Bildschirmfoto 2021-08-31 um 22 28 04" src="https://user-images.githubusercontent.com/3374055/131571415-474e081b-e750-417d-95c7-c249df8eba6c.png">

It somehow seems odd. In chrome there's no indication of a memory leak and in puppeteer it looks like a memory leak.

I could easily provide the heap snapshots if that helps.
The code for running with puppeteer can be found on https://gist.github.com/krausest/d6c604fc0966bf67aad0055cbf48f8d4

**Comment by krausest** [comment]
I'm trying to make sense out of the heap snapshots, but honestly I'm not sure how to achieve that.
The statistics view shows that for the puppeteer run the system objects memory is increasing:
After 1st click on create 1,000 rows:
<img width="401" alt="Bildschirmfoto 2021-08-31 um 22 44 34" src="https://user-images.githubusercontent.com/3374055/131573514-65b42cc0-8968-4258-9f5e-eaa52f5c4282.png">
After 3rd click on create 1,000 rows:
<img width="401" alt="Bildschirmfoto 2021-08-31 um 22 44 43" src="https://user-images.githubusercontent.com/3374055/131573531-2ac790ed-a8dc-40d4-aa9e-32eb0c4bd097.png">

For the manual test in chrome the system objects amount does not grow (much):
After 1st click on create 1,000 rows:
<img width="420" alt="Bildschirmfoto 2021-08-31 um 22 49 08" src="https://user-images.githubusercontent.com/3374055/131573812-0604aaff-7477-4649-889b-b7d1fdeb5bf6.png">
 After 3rd click on create 1,000 rows:
<img width="389" alt="Bildschirmfoto 2021-08-31 um 22 49 39" src="https://user-images.githubusercontent.com/3374055/131573872-511a762b-5519-4314-9d01-d005ee0c2d70.png">

**Comment by krausest** [comment]
Not sure if I'm doing this correctly, but this appears be the retainer tree for the largest retained object from the puppeteer run:
<img width="976" alt="Bildschirmfoto 2021-08-31 um 23 02 06" src="https://user-images.githubusercontent.com/3374055/131575546-63093e54-73bc-475a-95cf-3d95dffb6f3c.png">

**Comment by OrKoN** [comment]
From the last screenshot it looks like something is retained by console.log'ing HTMLTableCellElement somewhere.

**Comment by OrKoN** [comment]
I think it's caused by not disposing the element handle after assertions. `await element.dispose();`

**Comment by krausest** [comment]
@OrKoN Ouch - yes, that makes a difference. Thanks a lot! 
That makes a big difference for that framework. Heap size is now reported as
```
heap size: 2735616
heap size: 2749872
heap size: 2783636
heap size: 2812896
heap size: 2762364
heap size: 2785904
heap size: 2784300
heap size: 2788592
heap size: 2798024
heap size: 2987704
```
and looks now way more constant. I'm closing this issue.
