### ISSUE TITLE
The Javascript coverage

### ISSUE THREAD

**Issue by theprodev** [puppeteer/puppeteer#7537]
Hello, 

I tried the page.coverage to get the used javascript only. It works fine but it gives results in 'Per Block' mode. I need the coverage javascript based on the 'Per function' mode. How to do it? My code is given below;

Thanks for your help.

```
		await Promise.all([
			page.coverage.startJSCoverage()
		]);
		await page.goto('https://example.com');
		
		const jsCoverage = await Promise.all([
			page.coverage.stopJSCoverage()
		]);
		
		const js_coverage = [...jsCoverage];	console.log(js_coverage);
		let js_used_bytes = 0;		let js_total_bytes = 0;		let covered_js = "";
		
		for (const entry of js_coverage[0]) {
			js_total_bytes += entry.text.length;
			console.log(`Total Bytes for ${entry.url}: ${entry.text.length}`);
			for (const range of entry.ranges){
				console.log(range);
				js_used_bytes += range.end - range.start - 1;
				covered_js += entry.text.slice(range.start, range.end);// + "\n";
			}       
		}
```

**Comment by jschfflr** [comment]
@theprodev Thanks for taking the time to report this issue! Unfortunately it's currently not possible to change the `detailed` flag when collecting coverage. But feel free to create a pull request to add that behaviour :)
