### ISSUE TITLE
[Question] Frame html content

### ISSUE THREAD

**Issue by datasunny** [puppeteer/puppeteer#754]
Hi all,
Not sure if it's right place to ask question, how can I get frame content (HTML before and after JS rendering). I see page.content() method, but not such thing for frame. Thanks for your time!

**Comment by ArielBadilla** [comment]
I have the same problem,

**Comment by aslushnikov** [comment]
it should be easy now to move page's `content` and `setContent` methods into frame, which will give `frame.content()` and `frame.setContent()`. Page should keep the `page.content()` and `page.setContent` methods and just call the main frame's counterparts.

**Comment by trentmwillis** [comment]
I've opened a PR to fix this according to @aslushnikov's comment.
