### ISSUE TITLE
Checking If the Website Uses Specific Function

### ISSUE THREAD

**Issue by harunoz** [puppeteer/puppeteer#7540]
Hello, I am trying to check if the website uses specific function (i.e., **window.showOpenFilePicker()**). My aim is I will open the website and I want to get a True boolean value only if the website uses  **window.showOpenFilePicker()** function. As suggested by @vsemozhetbyt I am using ` page.evaluateOnNewDocument()`. However, the code as shown in below, always returns False and I am getting this error:

```
VM14:4 Uncaught TypeError: Cannot read property 'bind' of undefined
    at <anonymous>:4:65
    at <anonymous>:9:9
```

My code is: 
```

'use strict';

const puppeteer = require('puppeteer');


(async function main() {

   const browser = await puppeteer.launch({ headless: false, defaultViewport: null });

    try {
 
    
      const [page] = await browser.pages();
    
    await page.evaluateOnNewDocument(() => {
        window.showOpenFilePickerIsCalled = false;
    
        const oldShowOpenFilePicker = window.showOpenFilePicker.bind(window);
        window.showOpenFilePicker = function (...args) {
        window.showOpenFilePickerIsCalled = true;
         return oldShowOpenFilePicker(...args);
        };
      });
    
      await page.goto('https://example.org/');
    
      const check1 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check1); // false
    
   // const fileName = await page.evaluate(async () => {
   //     console.log("asd")
    //    return (await window.showOpenFilePicker())[0].name;
    //  });
     // console.log(fileName); // picked file name
    
      const check2 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check2);// true
    } 
    catch(err) { console.error(err); } finally { 
        //await browser.close(); 
    }
})();
```

How can I solve this issue? 
Thanks.

**Comment by vsemozhetbyt** [comment]
@harunoz Can there be that you try to use this code on HTTP sites? 

See [Window.showOpenFilePicker()](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker):

> This feature is available only in secure contexts (HTTPS)...

**Comment by harunoz** [comment]
Hello thank you for your answer, I tried to use in 'https://example.org/' and I still get the same error.  I think the problem is we need to inject that function to evaluate by using exposeFunction utility as stated in [here](https://www.google.com/url?q=https://stackoverflow.com/questions/48281130/why-cant-i-access-window-in-an-exposefunction-function-with-puppeteer&sa=D&source=hangouts&ust=1630614129837000&usg=AOvVaw2-d_bguMrRHwawDUI98XnW) and [here](https://github.com/puppeteer/puppeteer/issues/6718). But I could not figure out how am I going to achieve this.

**Comment by harunoz** [comment]
Hello, no if I run the code in `https://example.org/` I am still getting the same error. I think we need to inject window function to evaluate by using `exposeFunction` as stated in [here](https://stackoverflow.com/questions/48281130/why-cant-i-access-window-in-an-exposefunction-function-with-puppeteer). But I could not figure out how.

**Comment by vsemozhetbyt** [comment]
It is strange: I get no errors with `https://example.org/`. Do you use the last version of Chrome shipped with the last version of `puppeteer`? Do you use the code without any changes?

**Comment by harunoz** [comment]
I am using the above code without any change and I am running it with node. Note that, I commented await browser.close(). So, I am not closing the browser. While the browser is opened by the puppeteer I am seeing the error via dev-tools console. Specifically,

`VM14:4 Uncaught TypeError: Cannot read property 'bind' of undefined
    at <anonymous>:4:65
    at <anonymous>:9:9`

Don't you see this error?

**Comment by vsemozhetbyt** [comment]
No, I get no errors, just the expected output. Your error means there is no `window.showOpenFilePicker` function in the site context. What puppeteer and Chrome version do you use?

**Comment by harunoz** [comment]
Hello I believe that my problem is related with this. I am downloading puppeteer with `npm install puppeteer` and it automatically downloads `Chrome/78.0.3882.0 ` which is the old version of Chrome. How can I update the Chrome that comes with the Puppeteer?

**Comment by vsemozhetbyt** [comment]
You can try `npm install puppeteer@latest` to install the last puppeteer version with the last available Chrome.

**Comment by harunoz** [comment]
Hello it worked, I am not seeing any errors. However, in the above code opens `filePicker ` for every website. 
What I am trying to do this, I want puppeteer to continuously check if the showOpenFilePicker function (or any other function) is invoked by a website or user. If this function is invoked, my aim is to interrupt the website's activity and run my function. Is this possible?
For example if you run this code, it opens a file picker for `google.com`
```
'use strict';

const puppeteer = require('puppeteer');


(async function main() {

   const browser = await puppeteer.launch({ headless: false, defaultViewport: null });

    try {
 
    
      const [page] = await browser.pages();
      const version = await page.browser().version();
      console.log(version)
    
    await page.evaluateOnNewDocument(() => {
        window.showOpenFilePickerIsCalled = false;
    
        const oldShowOpenFilePicker = window.showOpenFilePicker.bind(window);
        window.showOpenFilePicker = function (...args) {
        window.showOpenFilePickerIsCalled = true;
         return oldShowOpenFilePicker(...args);
        };
      });
    
      await page.goto('https://google.com');
    
      const check1 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check1); // false
    
    const fileName = await page.evaluate(async () => {
        console.log("asd")
        return (await window.showOpenFilePicker())[0].name;
      });
      console.log(fileName); // picked file name
    
      const check2 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check2);// true
    } 
    catch(err) { console.error(err); } finally { 
        //await browser.close(); 
    }
})();
```

**Comment by vsemozhetbyt** [comment]
Maybe something like this?
```
    await page.evaluateOnNewDocument(() => {
        window.showOpenFilePickerIsCalled = false;

        const oldShowOpenFilePicker = window.showOpenFilePicker.bind(window);
        window.showOpenFilePicker = function (...args) {
        window.showOpenFilePickerIsCalled = true;
         return oldShowOpenFilePicker(...args);
        };

        const checker = setInterval(() => {
          if (window.showOpenFilePickerIsCalled) {
            clearInterval(checker);
            console.log('There we go...');
            // your code or function call
          }
        }, 1000);
      });
```

**Comment by harunoz** [comment]
I really lost in this step. I am really appreciate your help I tried code shown in below but it did not work. Where should I locate this code snippet? 


```
'use strict';

const puppeteer = require('puppeteer');


(async function main() {

   const browser = await puppeteer.launch({ headless: false, defaultViewport: null });

    try {
 
    
      const [page] = await browser.pages();
      const version = await page.browser().version();
      console.log(version)
    
      await page.evaluateOnNewDocument(() => {
        window.showOpenFilePickerIsCalled = false;

        const oldShowOpenFilePicker = window.showOpenFilePicker.bind(window);
        window.showOpenFilePicker = function (...args) {
        window.showOpenFilePickerIsCalled = true;
         return oldShowOpenFilePicker(...args);
        };

        const checker = setInterval(() => {
          if (window.showOpenFilePickerIsCalled) {
            clearInterval(checker);
            console.log('There we go...');
            // your code or function call
          }
        }, 1000);
      });
      await page.goto('https://mburakerman.github.io/file-system-access-api-demo/');
    
      const check1 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check1); // false
    
    const fileName = await page.evaluate(async () => {
        //page.setJavaScriptEnabled(false)
        return (await window.showOpenFilePicker())[0].name;
      });
      console.log(fileName); // picked file name
    
      const check2 = await page.evaluate(() => {
        return window.showOpenFilePickerIsCalled;
      });
      console.log(check2);// true
    } 
    catch(err) { console.error(err); } finally { 
        //await browser.close(); 
    }
})();

```

**Comment by vsemozhetbyt** [comment]
I am a bit lost too) Maybe you can describe what you really need to do after file dialog is closed?

**Comment by harunoz** [comment]
Okay, what I am trying to do this, let's say we do have a website that uses `Window.showDirectoryPicker()` function stated in [here](https://web.dev/file-system-access/). I would like first check if the user and/or website invokes `Window.showDirectoryPicker()` function. If the website uses that function, I would like to check whether the website tries to delete the user's files via `removeEntry()` function again stated in [here](https://web.dev/file-system-access/).

So, my idea is I want to implement hooking technique to both `Window.showDirectoryPicker()` and `removeEntry()` functions to check if a website uses them. When I am able to find out that these functions are called by the website, I will interrupt the activities that the website is doing, and perform some operations on the files according to my research purposes.

**Comment by vsemozhetbyt** [comment]
If I have figured it out correctly, this is a possible solution with a test (assuming you have `1.txt` file in the test directory):
```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({ headless: false, defaultViewport: null });

try {
  const [page] = await browser.pages();

  await page.exposeFunction('_notifyShowDirectoryPicker', (directoryName) => {
    console.log(`showDirectoryPicker was called. Selected directory: ${directoryName}`);
  });
  await page.exposeFunction('_notifyRemoveEntry', (name) => {
    console.log(`removeEntry was called for ${name}.`);
  });

  await page.evaluateOnNewDocument(() => {
    const _oldShowDirectoryPicker = window.showDirectoryPicker.bind(window);
    window.showDirectoryPicker = async function newShowDirectoryPicker() {
      const directoryHandle = await _oldShowDirectoryPicker();
      window._notifyShowDirectoryPicker(directoryHandle.name);
      return directoryHandle;
    };

    const _oldRemoveEntry = FileSystemDirectoryHandle.prototype.removeEntry;
    FileSystemDirectoryHandle.prototype.removeEntry = async function newRemoveEntry(name, options) {
      // Uncomment to not prevent the deletion.
      // await _oldRemoveEntry.call(this, name, options);
      window._notifyRemoveEntry(name);
    };
  });

  await page.goto('https://example.org/');

  await page.evaluate(async () => {
    const directoryHandle = await window.showDirectoryPicker();
    await directoryHandle.removeEntry('1.txt');
  });
} catch (err) { console.error(err); } finally { await browser.close(); }
```

**Comment by harunoz** [comment]
This code is work as intended. Now I would like to implement my own logic based on your code. I would like to hook to close() functions described in [here](https://web.dev/file-system-access/). I want to prevent the `writable.close()` operation invoked by a website. I changed the code and add these two functions, but it doesn't work. How can I solve this issue? 

To notify the close event
```
  await page.exposeFunction('_notifyWriteClose',(name) => {
    console.log('`WriteClose was called for ${name}.`')
  })

```

and prevent close operation

```
    const _oldWriteClose = FileSystemWriter.prototype.close;
    FileSystemWriter.prototype.close = async function newCloseEntry(name,options){
      await _oldWriteClose.call(this, name, options);
      window._notifyWriteClose(name)
    };
```

```

const puppeteer = require("puppeteer");

(async () => {
const browser = await puppeteer.launch({ headless: false, defaultViewport: null });

try {
  const [page] = await browser.pages();

  await page.exposeFunction('_notifyShowDirectoryPicker', (directoryName) => {
    console.log(`showDirectoryPicker was called. Selected directory: ${directoryName}`);
  });
  await page.exposeFunction('_notifyRemoveEntry', (name) => {
    console.log(`removeEntry was called for ${name}.`);
  });

  await page.exposeFunction('_notifyWriteClose',(name) => {
    console.log('`WriteClose was called for ${name}.`')
  })

  await page.evaluateOnNewDocument(() => {
    const _oldShowDirectoryPicker = window.showDirectoryPicker.bind(window);
    window.showDirectoryPicker = async function newShowDirectoryPicker() {
      const directoryHandle = await _oldShowDirectoryPicker();
      window._notifyShowDirectoryPicker(directoryHandle.name);
      return directoryHandle;
    };



    const _oldRemoveEntry = FileSystemDirectoryHandle.prototype.removeEntry;
    FileSystemDirectoryHandle.prototype.removeEntry = async function newRemoveEntry(name, options) {
       //Uncomment to not prevent the deletion.
      await _oldRemoveEntry.call(this, name, options);
      window._notifyRemoveEntry(name);
    };

    const _oldWriteClose = FileSystemWriter.prototype.close;
    FileSystemWriter.prototype.close = async function newCloseEntry(name,options){
      await _oldWriteClose.call(this, name, options);
      window._notifyWriteClose(name)
    };

  });

  await page.goto('https://example.org/');

 // await page.evaluate(async () => {
  //  const directoryHandle = await window.showDirectoryPicker();
   // await directoryHandle.removeEntry('1.txt');
  //});
} catch (err) { console.error(err); } finally {   await new Promise(done => setTimeout(done, 100000));
    await browser.close(); }

})();
```

**Comment by harunoz** [comment]
Hello thank you for your help, I was working on the code and I utilized a hooking for `write()` function as described below. I am able to perform the hooking however how can I get the file name that is called for write function? 


```
  await page.exposeFunction('_notifyWrite',(name) => {
    console.log(`Write was called for ${name}.`)
  });


    const _oldCreateWrite = FileSystemWritableFileStream.prototype.write;

    FileSystemWritableFileStream.prototype.write = async function newWrite(name,options) {

      await _oldCreateWrite.call(this,name,options);
      page.setJavaScriptEnabled(false)

      window._notifyWrite(name);

```

**Comment by jschfflr** [comment]
Hey, @harunoz Thanks for using Puppeteer! Unfortunately, we can't provide support outside of issues with Puppeteer itself. I'll close this issue as it's not actionable from my side but feel free to head over to stackoverflow to get your questions answered - I'm sure that will be helpful for other users as well :)
