### ISSUE TITLE
[Bug]: TimeoutError is erroneously declared in multiple locations in typedefs

### ISSUE THREAD

**Issue by lostfictions** [puppeteer/puppeteer#7545]
### Bug description

When using Puppeteer, I encountered a `TimeoutError`. I thought I'd handle it in a catch-block:

```js
import puppeteer from "puppeteer";

try {
  // do puppeteer things
} catch (e) {
  if (e instanceof TimeoutError) {
    // handle it
  } else {
    throw e;
  }
}
```

This seems pretty reasonable, right? When I typed out `TimeoutError`, VS Code suggested an import, which I accepted. My import statement for Puppeteer then looked like this:

```js
import puppeteer, { TimeoutError } from "puppeteer";
```

I'm using TypeScript, but there were no complaints about using this in an expression position -- that is, TypeScript believes the imported `TimeoutError` is not an interface or a type, but a valid JavaScript value. However, if I try to run this code, this happens:

```
TypeError: Right-hand side of 'instanceof' is not an object
```

Sure enough, at runtime `TimeoutError` is.... `undefined`. It's defined in the typings with an `export declare`: 

```ts
// file: node_modules/puppeteer/lib/types.d.ts, line 6581
export declare class TimeoutError extends CustomError {
}
```

...but the build process does not actually result in an artifact that exports this class in this location, so the declaration is making false promises. (You can see the [declaration file on unpkg](https://unpkg.com/puppeteer@10.2.0/lib/types.d.ts) -- just search for `TimeoutError`.) 

I went to https://pptr.dev and checked the docs, and [TimeoutError](https://pptr.dev/#?product=Puppeteer&version=v10.2.0&show=api-class-timeouterror) is listed as part of the top-level public API; I'd definitely expect VS Code's suggested import to work.

I also tried `puppeteer.TimeoutError` (ie. a property on the default export rather than a named export). **This is also defined in the typings** and passes typechecking when used as a value, but also results in `undefined` at runtime.

Finally, poking around more in the docs, I saw that the correct way to access the error is via `puppeteer.errors`. I think I stumbled over two issues in tandem:

1. The top-level API documentation for `TimeoutError` should ideally include a usage example with how to import it, since currently there's not much there:
    ![image](https://user-images.githubusercontent.com/567041/132103618-43f5c628-e00f-4ee4-985a-d7091f6992dc.png)
2. The generated type declarations should not `export declare` a non-existent class, which in TypeScript means "I promise this will exist at runtime." This causes any tooling that uses the TypeScript Language Server to suggest it as a valid import. (This includes writing vanilla JS in VS Code and other tools, since it uses existing typedefs to provide suggestions.)

    I understand the temptation to do this in TypeScript if a class is namespaced under an object, which makes it difficult to reference it in a type position. This is exacerbated in the case of `TimeoutError`, since the namespace is [declared as a record type](https://github.com/puppeteer/puppeteer/blob/10e847404e83781cea6e624431798e2792fa440e/src/common/Errors.ts#L39-L48) even though it's a constant, making it impossible to export in typings even as something like

    ```
    export type TimeoutError = typeof puppeteer.errors.TimeoutError
    ```

    I'd suggest simply removing the type `PuppeteerErrors`, which is worse than nothing -- the inferred value on the export would be much better in this case. I'm not actually sure how the `export declare`s are being generated (otherwise I'd submit a PR) but I'd suggest they should simply be removed as well.

    EDIT: realizing other types like `Page` are also `export declare`d in this way too -- pretty unfortunate.

---

Steps to reproduce the problem:

1. Install Puppeteer.
2. Run `node` for a REPL.
3. Type `require('puppeteer').TimeoutError`. The REPL returns `undefined`.

### Puppeteer version

10.2.0

### Node.js version

16.6.2

### npm version

7.20.3

### What operating system are you seeing the problem on?

Linux

**Comment by TBG-FR** [comment]
I confirm this is still an issue. Faced it today (`ERROR TypeError: Right-hand side of 'instanceof' is not an object`) and someone else too earlier in June https://stackoverflow.com/questions/76492488/instanceof-not-working-when-exception-raised-from-a-shared-node-module

**Comment by OrKoN** [comment]
<img width="314" alt="Screenshot 2023-07-19 at 17 24 32" src="https://github.com/puppeteer/puppeteer/assets/399150/29e52fbf-e043-42bb-b829-9433bca6153c">

unable to repro using the latest puppeteer. Please open a new issue if you believe the bug persists.

**Comment by TBG-FR** [comment]
Thank you for the blazing fast answer 🚀 I'll do if I reproduce it when moving to the latest version 😉
