### ISSUE TITLE
Cannot set _productName of undefined

### ISSUE THREAD

**Issue by aakashgarg19** [puppeteer/puppeteer#7548]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.5.0
* Platform / OS version: Windows 10
* URLs (if applicable):
* Node.js version:12.18.3

**What steps will reproduce the problem?**
Calling launch method of puppeteer.

_Please include code that reproduces the issue._

await launch({
            args: ['--start-maximized'],
            headless: true,
            product: 'chrome',
            timeout: 300000,
            ignoreHTTPSErrors: true
          });

**What is the expected result?**
browser should launch without any error.

**What happens instead?**
Gives Error **"Cannot set _productName of undefined** if i remove product from launch configuration gives error **"Cannot set launcher of undefined"**

**Comment by aakashgarg19** [comment]
any updates on this?

**Comment by aakashgarg19** [comment]
anyone looking into this?

**Comment by maxwrlr** [comment]
Hey @aakashgarg19, I had the same issue and fixed it by amending the import statement.
Still, I am not sure what caused it so suddenly.

Not working:
```typescript
import {launch} from 'puppeteer-core';
launch(...)
```

Working:
```typescript
import * as puppeteer from 'puppeteer-core';
puppeteer.launch(...)
```

**Comment by aakashgarg19** [comment]
> Hey @aakashgarg19, I had the same issue and fixed it by amending the import statement. Still, I am not sure what caused it so suddenly.
> 
> Not working:
> 
> ```ts
> import {launch} from 'puppeteer-core';
> launch(...)
> ```
> 
> Working:
> 
> ```ts
> import * as puppeteer from 'puppeteer-core';
> puppeteer.launch(...)
> ```

Thanks @maxwrlr this seems to work.
