### ISSUE TITLE
page.accessibility.snapshot method returns element roles outside HTML/ARIA spec

### ISSUE THREAD

**Issue by jamalmazrui** [puppeteer/puppeteer#7549]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

I am writing a program that analyzes the accessibility tree returned by page.accessibility.snapshot() (with the default option of interestingOnly= true).  This analysis would work better if the element roles conformed to the ARIA specification.  Can the results be changed accordingly or  an option for ARIA conformance be added?

**Comment by jschfflr** [comment]
@jamalmazrui  Thanks for taking the time to report this issue! Could you share a list of the roles that don't match and/or a minimal reproduction? Thanks!
