### ISSUE TITLE
How to wait for a period of time after clicking?

### ISSUE THREAD

**Issue by zhuyangping** [puppeteer/puppeteer#7550]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9.1.1
* Platform / OS version: win 10
* URLs (if applicable): 
* Node.js version: 14.14.44

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. I'm crawling for content. It needs to be obtained after clicking, and then it needs to wait for a period of time before the content can be displayed.After clicking, there is no network request, just execute the page content.I tried some methods, but I failed.What I can think of is to wait for some time before getting the content, because there is no special selector after clicking.

2. code: await page.click("div.a > ul.a > li:nth-child(2)", {delay:4000});
  await page.evaluate(() => {...

**What is the expected result?**
I hope that after clicking, I can wait for some time, and then I can get the content.

**What happens instead?**
I tried this method, but I failed.

**Comment by gnefna1** [comment]
you can try waitForSelector()

**Comment by Criselin** [comment]
u should try page.waitForTimeout(ms)

**Comment by iamkarsoft** [comment]
```
   await  page.waitForNavigation({
        waitUntil: 'networkidle0',
    })
```

**Comment by jschfflr** [comment]
@zhuyangping Thanks for taking the time to report this issue!
Please use `waitForTimeout` or even better `waitForSelector` for this.
