### ISSUE TITLE
Security concerns to automate chrome browser using puppeteer's wsEndpoint to reconnect to opened window[Bug]: 

### ISSUE THREAD

**Issue by Sridhar-Ranganaboina** [puppeteer/puppeteer#7551]
### Bug description

We have concerns from security team to automate chrome browser using puppeteer and it's web socket endpoint.Their concern is "When webSocket is enabled at the given port. This WebSocket provides access to the remote debugging protocol, which offers control over the whole browser. This results in scripting access to arbitrary websites, the ability to read local files, write to local files, and launch external programs". Can anyone please help me how to fix this issue.

```
//disconnecting from and reconnecting to a Browser
(async () => {
  const browser = await puppeteer.launch("chrome path");
  // Store the endpoint to be able to reconnect to Chrome
  const browserWSEndpoint = browser.wsEndpoint();
  // Disconnect puppeteer from Chrome
  browser.disconnect();

  // Saving WSEndpoint somewhere in user tem folder and Using the endpoint to reestablish a connection. This is to connect to pages which already opened by user manually
  const browser2 = await puppeteer.connect({browserWSEndpoint});
  // Close Chromium
  await browser2.close();
})();
```

### Puppeteer version

10.2.0

### Node.js version

16.9.0

### npm version

7.x

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by jschfflr** [comment]
Please take a look at https://stackoverflow.com/questions/54922756/what-are-the-advantages-and-disadvantages-of-connecting-puppeteer-over-pipe-inst for an explanation of the different options.
