### ISSUE TITLE
[Bug]: debugger statement inside `<handle>.evaluate` shows no source code

### ISSUE THREAD

**Issue by d3lm** [puppeteer/puppeteer#7559]
### Bug description

I am trying to debug my tests by adding a `debugger` statement inside the `.evaluate` callback, and it does halt the execution but Chrome DevTools don't show any source code as seen in the following screenshot:

![image](https://user-images.githubusercontent.com/12571019/132949701-2371ce71-4815-45ca-86f4-888c7eba86b7.png)

This is the code inside my test:
```ts
const myClassHandle: JSHandle<MyClass> = await page.waitForFunction('window.MyClass');

await myClassHandle.evaluate((MyClass) => {
  const myClass = new MyClass();
  debugger;
});
```
I would expect to see at least the following code inside the DevTools:
```js
const myClass = new MyClass();
debugger;
```
I have created a [demo project](https://github.com/d3lm/puppeteer-demo) on GitHub that reproduces the issue.

Is this a known issue or is there something I can do to fix it?

### Puppeteer version

10.2.0

### Node.js version

v14.16.0

### npm version

6.14.11

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
/
```

**Comment by jschfflr** [comment]
@d3lm Thanks for taking the time to report this issue!
I'm happy to look into this!

**Comment by d3lm** [comment]
Thanks for looking into this!

Quick update: I noticed that I was resizing the browser window before the test(s) started. If I don't resize it, it seems to show the code in the DevTools.

**Comment by jschfflr** [comment]
@d3lm I feel like this is probably more of a DevTools issue than a Puppeteer issue. 
Could you file a bug for this on https://crbug.com/ and reference this issue?
Thanks!

**Comment by d3lm** [comment]
Will do. Thanks for digging into this.
