### ISSUE TITLE
[Bug]: no headers if the status is 304

### ISSUE THREAD

**Issue by chuoke** [puppeteer/puppeteer#7561]
### Bug description

no headers if the status is 304.

### Puppeteer version

v10

### Node.js version

v14

### npm version

-

### What operating system are you seeing the problem on?

Linux

**Comment by jschfflr** [comment]
@chuoke Could you provide a minimal reproduction for this error?

**Comment by chuoke** [comment]
Sorry, I can't. 
The thing is the same URL, repeated requests, subsequent requests the browser uses cached data from disk, and give status code 304, in this case, there is no headers info in the response.
I hope I made that clear. Sorry again.

If disable the cache feature there is no problem. That is my current solution.

**Comment by jschfflr** [comment]
@josepharhar Could this be resolved by your recent change already?

**Comment by josepharhar** [comment]
Yes, it maybe could be fixed by my change.
Does this puppeteer version include the breaking change?
