### ISSUE TITLE
Unittests not working with latest Firefox version

### ISSUE THREAD

**Issue by jschfflr** [puppeteer/puppeteer#7568]
### Bug description

It looks like unittests started failing consistently for Firefox with the following error:
```
Page
       "before each" hook for "should return the page title":
     Error: Protocol error (Target.createTarget): Unexpected tab opened: about:blank createTarget@chrome://remote/content/cdp/domains/parent/Target.jsm:93:13
```

Example run: 
https://github.com/puppeteer/puppeteer/actions/runs/1234822893

### Puppeteer version

HEAD

### Node.js version

-

### npm version

-

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by whimboo** [comment]
@jschfflr, I had a quick look and on Linux it seems that the code check task is failing, so this issue is Windows only, right? Do you know when this exactly started? What's the last passing and the first failing CI job? That would help me a lot to figure out what has been changed in Firefox itself.

**Comment by whimboo** [comment]
Note that we haven't made any changes to our CDP implementation. The exact failure here is:

```
       "before each" hook for "should return the page title":
     Error: Protocol error (Target.createTarget): can't access property "addTab", this.gBrowser is undefined addTab@chrome://remote/content/shared/TabManager.jsm:24:17
createTarget@chrome://remote/content/cdp/domains/parent/Target.jsm:90:28
```

So the window that the test is interacting with here doesn't seem to be a browser window.

**Comment by whimboo** [comment]
Hm, the latest push to the repository that happened 8h ago seem to be fine:
https://github.com/puppeteer/puppeteer/runs/3609620354

So maybe that was just a broken Nightly build?

**Comment by jschfflr** [comment]
Yeah, it looks like things a working again. So it was probably a broken nightly build. 
I'll close this bug again for now :)
