### ISSUE TITLE
[Bug]: Fatal error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long

### ISSUE THREAD

**Issue by limzykenneth** [puppeteer/puppeteer#7570]
### Bug description

Steps to reproduce the problem:

1. Clone p5.js repo: https://github.com/processing/p5.js
2. Change puppeteer dependency version to 10.2.0 and install dependencies with node 16 and npm 7
3. Run build and test using `npm test`

The tests eventually error with message: `Fatal error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long`

We came across this problem before and updating puppeteer version worked last time but not this time. Seemed to be related to #2746.

### Puppeteer version

10.2.0

### Node.js version

16.4.1

### npm version

7.18.1

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by jschfflr** [comment]
@limzykenneth Thanks for taking the time to report this issue!
I'm happy to take a look at this!

**Comment by limzykenneth** [comment]
If it helps, the error seems to be caused by logging certain objects and arrays. By converting the objects and arrays into strings it helps as shown in this PR: https://github.com/processing/p5.js/pull/5415

**Comment by jschfflr** [comment]
@limzykenneth Could you find a minimal example that reproduces this problem without checking out p5.js?
Thanks!

**Comment by limzykenneth** [comment]
@jschfflr I'll try to put something together, might take awhile though as I got a few things going on at the moment.

**Comment by limzykenneth** [comment]
@jschfflr I managed to put something together and in the process found the problem, at least on our end. The problem is that there's a cyclic reference in the object created via `createVector()` in the example below and when attempting to get the value back to the terminal with the `jsonValue()` function I presume there's an attempt at stringifying the object which will fail.

For our end, we may look into this cyclic reference problem but the error thrown by puppeteer doesn't directly reference this to be the case, which will be very useful if something like this pop up again. At the bottom I'll also include the full error I see in the terminal when running the code below.

The reason we only see this when running on node 16 is because before it used to throw a non fatal error when there are unhandled promise rejection and we just ignored those messages but from node 15 onwards the errors are fatal now.

```javascript
const puppeteer = require('puppeteer');

(async () => {
	const browser = await puppeteer.launch();
	const page = await browser.newPage();
	await page.addScriptTag({
		url: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.min.js"
	});

	page.on('console', async msg => {
		msg.args().forEach(async (v) => {
			console.log(await v.jsonValue());
		});
	});

	await page.evaluate(() => {
		let sketch = function(p){
			p.setup = function(){
				let regularArr = p.createVector();
				console.log(regularArr);
			};
		};

		new p5(sketch);
	});

	await browser.close();
})();
```

```
/Users/kennethlim/Dropbox/Sites/puppeteer-debug/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /Users/kennethlim/Dropbox/Sites/puppeteer-debug/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/kennethlim/Dropbox/Sites/puppeteer-debug/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:216:16)
    at JSHandle.jsonValue (/Users/kennethlim/Dropbox/Sites/puppeteer-debug/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:176:49)
    at /Users/kennethlim/Dropbox/Sites/puppeteer-debug/main.js:15:24
    at Array.forEach (<anonymous>)
    at /Users/kennethlim/Dropbox/Sites/puppeteer-debug/main.js:14:14
    at /Users/kennethlim/Dropbox/Sites/puppeteer-debug/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/kennethlim/Dropbox/Sites/puppeteer-debug/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
```

**Comment by OrKoN** [comment]
So looks like it's not reproducible anymore after you fixed the data structure? Feel free to create a new issue if there is still a bug.
