### ISSUE TITLE
what is the correct way to simulate double click , 

### ISSUE THREAD

**Issue by Kname80** [puppeteer/puppeteer#7576]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):
* Node.js version:

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by Kname80** [comment]
I tried this code , it stop working because initEvent is deprecated
await page.evaluate(selector => {
  var targLink = document.querySelector(selector);
  var clickEvent = document.createEvent('MouseEvents');
  clickEvent.initEvent('dblclick', true, true);
  targLink.dispatchEvent(clickEvent);
}, selector)

also I tried :
const selector = "#elementID";

const rect = await page.evaluate((selector) => {
  const element = document.querySelector(selector);
  if (!element) return null;
  const { x, y } = element.getBoundingClientRect();
  return { x, y };
}, selector);
still not working , any other solutions ?

**Comment by gurudattgd04** [comment]
Did you try element.click({count:2}) ?

**Comment by Kname80** [comment]
yes I did
await page.mouse.click(rect.x, rect.y, { clickCount: 2, delay: 100 });
https://stackoverflow.com/questions/64384430/how-to-double-click-in-puppeteer

**Comment by jschfflr** [comment]
@Karim10k Thanks for taking the time to report this issue!
Could you explain why the proposed solution didn't work for you?

**Comment by jschfflr** [comment]
Closing this for now as the problem seems to be resolved. If not, feel free to reopen!
