### ISSUE TITLE
[Bug]: While creating the PDF the single page is splitted into two page 

### ISSUE THREAD

**Issue by jeyashree-n** [puppeteer/puppeteer#7577]
### Bug description

I am using A4 paper this is the margin details --> top: '40px', right: '40px', bottom: '60px', left: '40px'.
<img width="821" alt="Screenshot 2021-09-17 at 8 46 24 PM" src="https://user-images.githubusercontent.com/84894261/133815529-25b61cea-b388-448b-ad51-e40061f20d5d.png">
 

### Puppeteer version

1.8.0

### Node.js version

10.13.0

### npm version

6.4.1

### What operating system are you seeing the problem on?

macOS

**Comment by jschfflr** [comment]
@jeyashree-n Thanks for taking the time to report this issue!
To me, this looks like it's working as intended. Could you explain what you'd expect instead and why?

**Comment by jschfflr** [comment]
Closing this for now as it seems to be related to Chromium itself. Please file a bug on https://crbug.com/ and link to this issue there. Thanks!
