### ISSUE TITLE
[Issue]: WebRTC Peer Remote Streams are not played in Headless Chrome

### ISSUE THREAD

**Issue by anishsrinivasan** [puppeteer/puppeteer#7581]
I'm planning to use Puppeteer as a Ghost Participant (GP) Recorder for WebRTC video calls between 2 clients. 
Something similar to [https://www.apollo350.com/post/how-to-live-stream-from-a-twilio-video-conference](https://www.apollo350.com/post/how-to-live-stream-from-a-twilio-video-conference)

### Steps :
1) Connect 2 Peers in a room using WebRTC & PeerJS
2) Join the third user as a ghost participant (GP) in the same room using Puppeteer running as headless mode. 
3) Take 2 videos streams received from the peers in Puppeteer and by using MediaRecorder sending the frames to NodeJS Server for further processing with FFMPEG. 

----

### Outcomes: 
**1) Works fine on local macOS (Google Chrome + Puppeteer)**
Both Headless & Headful mode. 

NodeJS : V12.22.1
Puppeteer: ^10.2.0
Google Chrome 93.0.4577.82 

**2) Not working on Linux (Server)**
Tried in Headless mode, with the executable path as GoogleChrome Stable. 

NodeJS : V16.9.1
Puppeteer: ^10.2.0
Google Chrome 93.0.4577.82

----

Sample Code from Client Recorder
```
export const start = (videoStream: any) => {
  const recordingStart = (window as any).recordingStart;
  
  const mediaRecorder = new MediaRecorder(videoStream, {
    mimeType: "video/webm;codecs=h264",
    videoBitsPerSecond: 3 * 1024 * 1024,
  });


  mediaRecorder.start(1000);

  mediaRecorder.ondataavailable = async function (e: any) {
    if (e.data && e.data.size > 0) {
      const message = "Sending Recording ~ " + new Date().toISOString();
      const buffer = await e.data.arrayBuffer();
      const data = arrayBufferToString(buffer);
      recordingStart(message, data);
    }
  };

  ```

Sample Code from Server Recorder

```
this.ffmpeg = child_process.spawn("ffmpeg", []); // removed extra args, if needed please let me know will include.

await page.exposeFunction(
        "recordingStart",
        (text: string, chunk: Buffer) => {
             const data = Buffer.from(str2ab(chunk));
             this.ffmpeg.stdin.write(data);
        }
      );
  ```

**Comment by jschfflr** [comment]
@anishsrinivasan Thanks for your bug report! Not sure what's going on here but I'm happy to take a look at it!

**Comment by jschfflr** [comment]
@anishsrinivasan Could you elaborate what exactly is going wrong here? With the provided information, I'm unable to reproduce the problem unfortunately.

**Comment by jschfflr** [comment]
I'll close this as it's currently not actionable from the puppeteer side. Please feel free to reopen if new information emerges!

**Comment by jschfflr** [comment]
I'll close this as it's currently not actionable from the puppeteer side. Please feel free to reopen if new information emerges!
