### ISSUE TITLE
[Bug]: isNavigationRequest does not detect page navigation in some sites (npr.org)

### ISSUE THREAD

**Issue by naveennazimudeen** [puppeteer/puppeteer#7584]
### Bug description

Steps to reproduce the problem:

1.  Log isNavigationRequest as shown below: 

```const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();

  const url = 'https://www.npr.org';

  page.on('request', req => {
    if (req.isNavigationRequest() && req.frame() === page.mainFrame()) {
      console.log('navigation request')
    }
    req.continue();
  });
  await page.setRequestInterception(true);
  await page.goto(url, {timeout: 0})
})();
```

2. Click on any article link on the page. isNavigationRequest() does not return true and so no matching logs in the console.
3. Go to nytimes.com instead, and click on any link. isNavigationRequest() returns true and there are  matching logs. 

### Puppeteer version

10.2

### Node.js version

15.4

### npm version

7.16

### What operating system are you seeing the problem on?

macOS

**Comment by jschfflr** [comment]
@naveennazimudeen Thanks for your bug report! To me it sounds like something that has recently regressed in Chromium. I'll verify my suspicion and update the issue accordingly!

**Comment by jschfflr** [comment]
I tried to reproduce your bug report and it seems like `npr.org` is not actually doing navigation requests but instead uses [history.pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState).
Could you verify (maybe by logging `req.url()`) that the request that you expect are actually sent?

**Comment by jschfflr** [comment]
@naveennazimudeen Closing this as I think its working as expected. Feel free to reopen if needed!
