### ISSUE TITLE
[Bug]: Puppeteer 10.4.0 ignores the proxy-server launch argument

### ISSUE THREAD

**Issue by anjackson** [puppeteer/puppeteer#7589]
### Bug description

Steps to reproduce the problem:

1. Install 10.4.0
2. Run this script, which sets a non-existent proxy server:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: [ '--proxy-server=http://non-existent-domain:8000' ]
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

Earlier versions will fail (correctly!) because the proxy server is not there.  10.4.0 ignores the proxy setting and runs as if the setting was not there.

### Puppeteer version

10.4.0

### Node.js version

16.8.0

### npm version

7.21.0

### What operating system are you seeing the problem on?

macOS

**Comment by Ha2ryZhang** [comment]
maybe this
```
  const context = await browser.createIncognitoBrowserContext({proxyServer:"http://127.0.0.1:7890"});
```

**Comment by jschfflr** [comment]
@anjackson Thanks for your bug report! Not sure why the `--proxy-server` argument doesn't work anymore. I'll look into it!

**Comment by anjackson** [comment]
Ah, looks like I messed up the test case.  Sorry about that.

The failing case uses `createIncognitoBrowserContext`, like this:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: [ '--proxy-server=http://localhost:18000', '--no-sandbox' ]
  });

  const context = await browser.createIncognitoBrowserContext();
  const page = await context.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();      
```

Looking through the 10.2.0 > 10.4.0 diff, I think a default of `proxyServer=''` is being set [here](https://github.com/puppeteer/puppeteer/compare/puppeteer:v10.2.0...puppeteer:v10.4.0#diff-2fb2a2631063a3779bee361f5aeb2148b320092239bced39f2ac0fb63fed7debR318) when an Incognito session is created. Perhaps `proxyServer=null` would have the intended effect of defaulting to whatever the overall configuration is?

**Comment by anjackson** [comment]
Hmm, that link into the diff didn't seem to work very well. [Here's the line I'm referring to.](https://github.com/puppeteer/puppeteer/blame/5631d3aebc73cc418824a569fe71781eec83f00a/src/common/Browser.ts#L318)

**Comment by jschfflr** [comment]
Please feel free to create a pull request for this change and I'm happy to get it landed :)

**Comment by anjackson** [comment]
I'm not a JavaScript programmer and frankly I can't even work out how to run the above example code against the puppeteer version in my forked repo.  I'll come back to it when I have time.
