### ISSUE TITLE
[Bug]: File gets downloaded in headless:false but not in headless:true

### ISSUE THREAD

**Issue by v-akash-freightwalla** [puppeteer/puppeteer#7590]
### Bug description

A PDF file when tried to download via headless:false mode, gets downloaded in the browser but when same thing is tried via headless:true mode, the file is not downloaded. 

### Puppeteer version

puppeteer-extra(3.1.16)

### Node.js version

12

### npm version

6.14

### What operating system are you seeing the problem on?

Linux

**Comment by jschfflr** [comment]
I'll look into this issue to figure out how puppeteer could improve its support!

**Comment by Arcadia64** [comment]
I too have been running into this problem. Have not found a good workaround.

**Comment by jschfflr** [comment]
Unfortunately, there is a difference in how headless and headfull handle downloads. 
We are tracking this in https://github.com/puppeteer/puppeteer/issues/299
