### ISSUE TITLE
[Question]: What is the difference in configuration between headless:true and headless:false

### ISSUE THREAD

**Issue by v-akash-freightwalla** [puppeteer/puppeteer#7591]
### Bug description

Hi, I wanted to know the difference between headless:false & headless:true mode?

This can help me to figure out why certain functionalities such as downloading a pdf etc, works in headless:false but not in headless:true.

Can someone please help? Or provide some configuration/setup details?

### Puppeteer version

puppeteer-extra(3.1.16)

### Node.js version

12

### npm version

6.14

### What operating system are you seeing the problem on?

Linux

**Comment by iamkarsoft** [comment]
Headless:true runs puppeteer in the background without opening a new browser page in contrast Headless: false opens a new browser page for you to see the process running

**Comment by jschfflr** [comment]
Please check https://developers.google.com/web/updates/2017/04/headless-chrome for an overview.
