### ISSUE TITLE
[Bug]: Chromium download over http proxy fails

### ISSUE THREAD

**Issue by fairbanksg** [puppeteer/puppeteer#7597]
### Bug description

Steps to reproduce the problem:

1. Have a proxy server setup, and set HTTP_PROXY and HTTPS_PROXY environment variables to point to it, both as http:// urls.
2. Install puppeteer
3. Download of Chromium during install fails with ERR_INVALID_PROTOCOL

It appears that this is happening because we are proxying HTTPS over an HTTP proxy.

### Puppeteer version

5.5.0

### Node.js version

16.9.1

### npm version

7.21.1 (but we use yarn, version 1.22.5)

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
2021-09-23T19:25:57.805Z puppeteer:fetcher Downloading binary from https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/818858/chrome-linux.zip
ERROR: Failed to set up Chromium r818858! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at Object.request (node:https:353:10)
    at httpRequest (<REDACTED>/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:488:17)
    at downloadFile (<REDACTED>/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:357:21)
    at BrowserFetcher.download (<REDACTED>/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:239:19)
    at async downloadBrowser (<REDACTED>/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:48:5) {
  code: 'ERR_INVALID_PROTOCOL'
}
```

**Comment by fairbanksg** [comment]
https://github.com/puppeteer/puppeteer/blob/f2e19276acb80e596ff5c781c9ae2bc2f2a8f363/src/node/BrowserFetcher.ts#L608-L611

In our setup, the download url is https, and the proxy url is http. This line chooses whether to use the http or https module based on the protocol of the download url, not the proxy url, so it is choosing https but passing a http url.

**Comment by fairbanksg** [comment]
Actually it looks like this is a bug in https-proxy-agent
https://github.com/TooTallNate/node-https-proxy-agent/issues/126

**Comment by jschfflr** [comment]
@fairbanksg Thanks for reporting this problem. We are in the process of improving our proxy support (
https://github.com/puppeteer/puppeteer/pull/6274) and I hope this will fix the problem.

**Comment by wjq990112** [comment]
Same problem.

**Comment by daemon110282** [comment]
Same problem.

**Comment by dragonfist453** [comment]
Same problem.

**Comment by dnltsk** [comment]
Same problem. Using npm 8.11.0.

**Comment by guellaeq** [comment]
Same problem. Using node 16.5.0. npm 7.19.1.

**Comment by willyboy** [comment]
Same

**Comment by abozas** [comment]
+1 for node 16 and 18

**Comment by Nexyll** [comment]
Same problem. Using node 16.14.2 and npm 8.5.0

**Comment by anthony-hull** [comment]
I worked around this by adding this to my package.json:
```
  "overrides": {
    "agent-base": "^6.0.2"
  }
```

**Comment by CoaxVex** [comment]
> We're marking this issue as unconfirmed because it has not had recent activity and we weren't able to confirm it yet. It will be closed if no further activity occurs within the next 30 days.

Confirming that this is still a problem.

**Comment by noproxy** [comment]
This line need to be fixed: 

`
 options.agent = new ProxyAgent(proxyOptions);
            options.rejectUnauthorized = false;
`

A `HttpsProxyAgent` is required if the `https.request` is used. 

See more here: https://stackoverflow.com/a/71482233

**Comment by boindil** [comment]
+1

would be neat if this could be fixed.

**Comment by OrKoN** [comment]
I am unable to reproduce, it seems to be downloading fine with a proxy server I tried. The https-proxy-agent has been fixed.
If someone experiences this issue, please share the proxy setup for troubleshooting.

**Comment by icy0307** [comment]
@OrKoN  
node v16.14.2 
pnpm 8.3.1  
pnpm config set https-proxy ANY_HTTP_PROXY 

and this would reproduce this problem

**Comment by simin75simin** [comment]
if you have direct connection to Chinese npm mirrors, turn off vpn and do:
```npm install cnpm -g --registry=https://registry.npmmirror.com```
```cnpm install puppeteer```
windows 11, node 20.12.2, npm 10.5.0
