### ISSUE TITLE
[Bug]: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by huynt0** [puppeteer/puppeteer#7598]
### Bug description

Steps to reproduce the problem:

1. Using docker alpine `FROM node:current-alpine`
2. Run `const browser = await puppeteer.launch({
        executablePath: '/usr/bin/chromium-browser',
        ignoreDefaultArgs: ['--disable-extensions'] ,
        args: ['--no-sandbox', '--disable-setuid-sandbox','--headless', '--disable-gpu']
      })`

### Puppeteer version

v10.0.0

### Node.js version

v14.17.6

### npm version

6.14.10

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Failed to launch the browser process!
Error relocating /usr/lib/libnspr4.so: gettid: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_drop_hints: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_retain_gids: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_subset: symbol not found
```

**Comment by jschfflr** [comment]
Please take a look at our troubleshooting guide - you have to install some additional dependencies:
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine
