### ISSUE TITLE
[Bug]: getting error with install puppeteer

### ISSUE THREAD

**Issue by saurabsuraj11** [puppeteer/puppeteer#7599]
### Bug description

Steps to reproduce the problem:

1. …I have to install html-pdf-node with command - npm install html-pdf-node@1.0.7.
it loads the puppeteer dependencies and getting the error - 
![Screenshot (1820)](https://user-images.githubusercontent.com/91321064/134663866-e98340f3-da18-4440-a74d-cefaf3ad2d68.png)

 async function download() {
            syntax error: Unexpected token function

### Puppeteer version

5.5.0

### Node.js version

14.16.0

### npm version

6.14.11

### What operating system are you seeing the problem on?

Linux

**Comment by jschfflr** [comment]
@saurabsuraj11 Could you verify that you are in fact running Node.js v14.16.0 when installing the package? 
Because the error looks like the Node version you use doesn't support `async/await` yet.

**Comment by saurabsuraj11** [comment]
I have checked it again. We are using node 14.16.0 only

**Comment by jschfflr** [comment]
Unfortunately, I can't reproduce the problem. 
Could you maybe verify that everything is working with the latest puppeteer version?

**Comment by saurabhsuraj** [comment]
Hii, Now I have successfully installed the puppeteer at the server with some basic commands. I am facing the issue with installing the browser on the server. now I resolved it.
Thank you for your support.

**Comment by jschfflr** [comment]
Happy to help!
