### ISSUE TITLE
Translate API support in near future?

### ISSUE THREAD

**Issue by ganapativs** [puppeteer/puppeteer#760]
In need of website translate support. Will there be support anytime soon?

**Comment by ebidel** [comment]
Can you elaborate on the request? Chrome's translation service isn't a public API and would need to be supported by the DevTools protocol for it to be exposed in Puppeteer.

There are good 3rd party libs/services like https://cloud.google.com/translate/docs/ that do translation. 

@aslushnikov @JoelEinbinder, on a similar note, [chrome-launcher turns off the service](https://github.com/GoogleChrome/lighthouse/blob/43baee69702d3c85a53e96ab52b0f73d3548af95/chrome-launcher/flags.ts#L10) when we launch Chrome. Should we do that too?

**Comment by ganapativs** [comment]
That makes sense, we wanted a way to convert other language sites into English before taking screenshot. Think we have to use translate API from google cloud. Thanks mate 👍
