### ISSUE TITLE
[Bug]: Proxy does not seem to work with Firefox

### ISSUE THREAD

**Issue by bjermeland** [puppeteer/puppeteer#7600]
### Bug description

1. Tried to use puppeteer-proxy:

```
import { proxyRequest } from 'puppeteer-proxy';

const browser = await puppeteer.launch({product:'firefox'});
const page = await browser.newPage();

await page.setRequestInterception(true);

page.on('request', async (request) => {
  await proxyRequest({
    page,
    proxyUrl: 'http://127.0.0.1:3000',
    request,
  });
});

await page.goto('https://www.google.com');
```

But getting this error on `await page.setRequestInterception(true)`:

```
Error: Protocol error (Fetch.enable): Fetch.enable RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
UnknownMethodError@chrome://remote/content/cdp/Error.jsm:112:7
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:98:13
receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45
```

2. Tried extraPrefsFirefox, but no way to authenticate the proxy. page.authenticate() does not work. Proxy does not seem to work either with no authentication.

```
import { proxyRequest } from 'puppeteer-proxy';

const browser = await puppeteer.launch({product:'firefox', extraPrefsFirefox: { 'network.proxy.socks': 'localhost', 'network.proxy.socks_port': 9050, 'network.proxy.socks_version': 5, 'network.proxy.proxy_over_tls': true }});
const page = await browser.newPage();

await page.goto('https://www.google.com');
```

### Puppeteer version

10.4.0

### Node.js version

14.14.0

### npm version

6.14.8

### What operating system are you seeing the problem on?

macOS

**Comment by jschfflr** [comment]
@bjermeland Thanks for taking the time to report this issue!
Unfortunately, Firefox doesn't support the `Fetch` domain in CDP yet. 
Closing this as it's currently not actionable from the Puppeteer side.

**Comment by yael-daum** [comment]
@bjermeland I have the same problem, did you find any solution or workaround for using proxy in Firefox browser?
