### ISSUE TITLE
waitForSelector always timesout in headless mode

### ISSUE THREAD

**Issue by jijojosephk** [puppeteer/puppeteer#7603]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 10.4.0
* Platform / OS version: Ubuntu Budgie 20.04.3 LTS
* URLs (if applicable):
* Node.js version: 14.17.6

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. Launch browser in headless mode.
2. Create new page.
3. Go to a specific URL in the page.
4. Call waitForSelector method

const browser = await puppeteer.launch({
        headless: false
    });

    const page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 800 });

    try {
        await page.goto(url);    // This is a parameter in the function
        await page.waitForSelector('[data-type="avatar"]', {
            timeout: 10000
        });

        const result = await page.$$eval('[data-type="avatar"]', el => {
            return el.map(x => {
                return x.getAttribute('src');
            });
        });
    }
    catch (e) {
        console.log(e);
    }

**What is the expected result?**
It should successfully match the waitForSelector.

**What happens instead?**
It always timesout.

**Comment by jijojosephk** [comment]
Could someone acknowledge? Not looking for a fix now. But at least confirm is it a issue or not?

**Comment by ngillen21** [comment]
Same issue here.  I am NOT running with headless mode turn on but when I kick off the script with a scheduled task it runs as a background process and seems act like it is running in headless with all the issues that it causes.   I get no errors thrown so not even sure what is going wrong.

**Comment by jijojosephk** [comment]
@ngillen21 It's possible the it automatically switch to headless mode otherwise, it fails to launch browser which is GUI but it's not possible running as a service. I'm really breaking my head to find the solution. Hope someone acknowledges this as a bug provide a fix.

**Comment by bartmanskyi** [comment]
Same issue
`HEADLESS: false` does not work as expected. Browser does not appear, and works in headless mode
I have found that this is related to browser version. v93 looks ok, but v94 does not work as expected in headless mode

**Comment by jschfflr** [comment]
@jijojosephk Thanks for taking the time to report this issue!
Unfortunately, I can not reproduce the problem. Could you share the url on which the problem occurs?
Thanks!

**Comment by bartmanskyi** [comment]
@jschfflr 
```
const chromium = require('chrome-aws-lambda'); // 10.1.0 - ver 92
(async () => {

  const browser = await chromium.puppeteer.launch({
    args:[
      '--allow-running-insecure-content',
      '--autoplay-policy=user-gesture-required',
      '--disable-component-update',
      '--disable-domain-reliability',
      '--disable-features=AudioServiceOutOfProcess,IsolateOrigins,site-per-process',
      '--disable-print-preview',
      '--disable-setuid-sandbox',
      '--disable-site-isolation-trials',
      '--disable-speech-api',
      '--disable-web-security',
      '--disk-cache-size=33554432',
      '--enable-features=SharedArrayBuffer',
      '--hide-scrollbars',
      '--ignore-gpu-blocklist',
      '--in-process-gpu',
      '--mute-audio',
      '--no-default-browser-check',
      '--no-pings',
      '--no-sandbox',
      '--no-zygote',
      '--use-gl=swiftshader',
      '--start-maximized',
      '--window-size=1920,1080'
    ],    
    headless: false,
    defaultViewport: chromium.defaultViewport,
    ignoreHTTPSErrors: true,
    executablePath: '/usr/bin/chromium-browser', // ver 94
    userDataDir: '/tmp/chromium_cache/',
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

**Comment by jijojosephk** [comment]
@jschfflr I'd take the example of instagram. replace url with an instagram profile llink.

	const browser = await puppeteer.launch({
		headless: true // true does not work during development and while deployed. false works while development because it launches browser and GUI is supported once deployed in a remote server, no GUI and it does not work same as true.
	});
	let avatarUrl;

	const page = await browser.newPage();
	await page.setViewport({ width: 1280, height: 800 });

	try {
		await page.goto(url);
		await page.waitForSelector('[data-testid="user-avatar"]', {
			timeout: 10000
		});

		const result = await page.$$eval('[data-testid="user-avatar"]', el => {
			return el.map(x => {
				return x.getAttribute('src');
			});
		});
		avatarUrl = result[0];
	}
	catch (e) {
		console.log(e);
	}

	browser.close();
	return avatarUrl;

**Comment by jijojosephk** [comment]
@jschfflr @bartmanskyi Did you try with the code I provided? I just wanted to know if this is really bug worth waiting the fix for. I badly need it working. I'd be happy to see you acknowledge this as a bug. Fix can come at anytime we'd happily wait for it. If it's acknowledged, I can stop breaking my head over this issue. Thanks for the understanding

**Comment by jschfflr** [comment]
@jijojosephk I tried the example you provided and it successfully returns the url both with headless: true and false.
Could you maybe use `page.screenshot`  or something similar to make sure that the page is actually showing what you expect it to show when the `waitForSelector` call fails? And maybe also check `page.content` to make sure that the element you expect is present?

**Comment by jschfflr** [comment]
I'll close this for now as its currently not reproducible. Feel free to reopen when there are new information!
