### ISSUE TITLE
[Bug]: TypeError: this._environment.runScript is not a function

### ISSUE THREAD

**Issue by hosseind88** [puppeteer/puppeteer#7604]
### Bug description

Steps to reproduce the problem:

1. I installed puppeteer and I can't run my tests because of this issu
<img width="650" alt="Screen Shot 2021-09-26 at 15 53 10" src="https://user-images.githubusercontent.com/72156162/134807849-27bf658e-5844-4307-a0e1-03498704b102.png">
e

### Puppeteer version

10.4.0

### Node.js version

15.3.0

### npm version

7.0.14

### What operating system are you seeing the problem on?

macOS

**Comment by suzaku056** [comment]
@hosseind88 Hi, How did you solve this problem?
