### ISSUE TITLE
[Bug]: Seems page.$x doesn't work on Cloud function

### ISSUE THREAD

**Issue by packlikez** [puppeteer/puppeteer#7611]
### Bug description

I can't use page.$x in cloud function but in local and firebase simulator are working

### Puppeteer version

10.4.0

### Node.js version

14

### npm version

7.21.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
It just wait tills timeout
```

**Comment by jschfflr** [comment]
@packlikez Thanks for taking the time to report this issue!
Could you share a script that reproduces the problem?
And also maybe run Puppeteer with `DEBUG=puppeteer:*` and past the log here? Thanks!

**Comment by packlikez** [comment]
it works now because I increased memory, Thank you for your response

**Comment by jschfflr** [comment]
Thanks for your feedback!
