### ISSUE TITLE
[Bug]: jest don't fail when expect fails in page on request

### ISSUE THREAD

**Issue by hosseind88** [puppeteer/puppeteer#7612]
### Bug description

```
function logRequest(interceptedRequest) {
     expect(2).toEqual(6);
}
page.on('request', logRequest);
```

I expect that test fails and don't continues after this happens but it resumes and gets succeed 

### Puppeteer version

10.4.0

### Node.js version

15.3.0

### npm version

7.0.14

### What operating system are you seeing the problem on?

macOS

**Comment by jschfflr** [comment]
@hosseind88 Thanks for taking the time to report this issue!

Please keep in mind that you are registering an event handler which might be running later.
The pattern we use in our unit tests is the following:
```js
const requests = [];
page.on('request', (request) => requests.push(request));
await page.goto(server.EMPTY_PAGE);
expect(requests.length).toBe(1);
expect(requests[0].url()).toBe(server.EMPTY_PAGE);
```

Closing this as it's not actionable from the Puppeteer side.
