### ISSUE TITLE
[Bug]: not working on github actions

### ISSUE THREAD

**Issue by liron-navon** [puppeteer/puppeteer#7621]
### Bug description

Steps to reproduce the problem:

1. install puppeteer
2. try running puppeteer in GitHub actions

tried running chrome, chromium-browser, and chrome-latest-stable, and the default downloaded chromium version, nothing works

### Puppeteer version

10.4.0

### Node.js version

16

### npm version

7.24.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: /usr/bin/google-chrome-stable
```

**Comment by jschfflr** [comment]
@liron-navon 
Thanks for taking the time to report this issue!
Could you give a little more context about what you are doing / trying to achieve? 
With the provided information, I'm unable to reproduce the problem.

**Comment by liron-navon** [comment]
@jschfflr I tried running puppeteer tests with jest-puppeteer on Github actions, I know it used to work since there are tutorials, but currently with the new version of GitHub actions it doesn't, and I couldn't make it work...

My workaround was to run my actions inside a container

https://github.com/liron-navon/docker-puppeteer-container

**Comment by jschfflr** [comment]
Unfortunately, I'm unable to reproduce the problem. Could you maybe provide a minimal reproduction?

**Comment by jschfflr** [comment]
Unfortunately, I'm unable to reproduce the problem. Could you maybe provide a minimal reproduction?

**Comment by jschfflr** [comment]
Sorry, bad internet connection here 📶
