### ISSUE TITLE
[Bug]: Audio glitches. Chromium, Node js server for serving static files, Raspberry Pi

### ISSUE THREAD

**Issue by kwaziphi** [puppeteer/puppeteer#7622]
### Bug description

Hello there. Looking for advice/help.

I am using puppeteer to automate playing my web-player (wrote on js with Howler library).

When I manually open Chromium, then go to http://localhost:8080 and click on #play-button - music plays well.
When I reproduce such a behaviour with puppeteer - I am getting glitches, pausing (even for 1-2sec) during playing.
Don't know how to solve it and where to look for an answer.
I am using pre-installed Chromium (v 88.0.4324.127) on my Raspberry Pi.

Steps to reproduce the problem:
1. Turn on http-server on node js (goal - serving local music mp3 files)
2. Run puppeteer script in headless or headful mode. (command in terminal "node puppeteer-script.js". tried also with "&" at the end - didnt work, everything stoped after 10-30 seconds)

Puppeteer script itself:

const puppeteer = require ('puppeteer-core');

(async () => {
	const browser = await puppeteer.launch ({
		headless: false,
		executablePath: '/usr/bin/chromium-browser'
	});
	const page = await browser.newPage();
	await page.setDefaultNavigationTimeout(0);
	await page.goto('http://localhost:8080');
	await page.setCacheEnabled(false);
	
	await page.waitForSelector('#play-button').then(()=> page.click('#play-button'));

})();	

### Puppeteer version

puppeteer-core 10.4.0

### Node.js version

16.10.0

### npm version

-

### What operating system are you seeing the problem on?

Linux

**Comment by kwaziphi** [comment]
Here is my Player code:
``` function loadingSound1 (i, playingList) {
		var intervaller;

		sound1 = new Howl ({
			src: [playingList[i]],
			preload: true,
			html5: true,
			onplay: function() {
						var time1 = sound1.duration();
						var timetoswitch1 = time1 - fadeTime;

						intervaller = setInterval(() => {
							if (sound1.seek() >= timetoswitch1) {
								sound2.play();
								clearInterval(intervaller);
							};
						},500);						
						},
			onpause: function () {clearInterval(intervaller)},			
			onend: function () {
						console.log('i = ' + i + 'k = ' + k);

						sound1.unload();

						listLength = playingList.length;
						i = i + 2;
				 		loadingSound1 (i, playingList);		
			}
		})
}

function loadingSound2 (k, playingList) {
		var intervaller;

		sound2 = new Howl ({
			src: [playingList[k]],
			preload: true,
			html5: true,
			onplay: function() {
				var time2 = sound2.duration();
				var timetoswitch2 = time2 - fadeTime;
				
				intervaller = setInterval(() => {

					if (sound2.seek() >= timetoswitch2) {
						sound1.play();
						clearInterval(intervaller);
								};
						},500);					
					},
			onend: function () {
						listLength = playingList.length;

						sound2.unload();

						k = k + 2;
			 			loadingSound2 (k, playingList);
			}
		})
	}	``

**Comment by jschfflr** [comment]
@kwaziphi Thanks for taking the time to report this issue! Unfortunately, I can't reproduce your setup on my local machine. Could you host your player somewhere online so that I can just navigate to a given url to reproduce the problem? Thanks!

**Comment by jschfflr** [comment]
@kwaziphi I'm closing this as it's currently not actionable for me. Please feel free to reopen once there's a minimal reproduction available :)
