### ISSUE TITLE
[Bug]: page.pdf() doesn't work in web due to "hard" node stream dependency

### ISSUE THREAD

**Issue by joelgriffith** [puppeteer/puppeteer#7623]
### Bug description

Steps to reproduce the problem:

1. Import puppeteer's esm web build into a web-app.
2. Use it and try to generate a pdf.
3. Always errors with `Cannot create a stream outside of Node.js environment.`.

Here's an example html payload that illustrates this (feel free to substitute the connect call for something else).

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>puppeteer client pdf demo</title>
    <script type="module">
      import puppeteer from 'https://unpkg.com/puppeteer-core@10.4.0/lib/esm/puppeteer/web.js';
      (async () => {
        const browser = await puppeteer.connect({ browserWSEndpoint: 'wss://chrome.browserless.io' });
        const page = await browser.newPage();
        await page.goto('https://example.com');
        const pdf = await page.pdf();
        console.log('wont be reached', pdf);
      })();
    </script>
  </head>
  <body>
  </body>
</html>
```

*Possible PRs I'm happy to do*

After reading through the code it's apparent that the team is awaiting the arrival of the [node stream api](https://nodejs.org/api/webstreams.html), which functionally implements the same browser-equivalent. This is present now in Node >16, which I assume is what's holding this TODO up. However, given the LTS of 14, I think we should find a liveable solution and not leave the web build as broken. Possible fixes I'm happy to do a PR for:

- Re-implement how page.pdf() (not pdf-streams) is implemented to avoid using streams. It'll be functionally equivalent to how it's operating in now since I see there's a Buffering helper in place, however it adds yet another condition + code to remove in the future (plus all the tests and other maintenance therein).

- Move pdf methods off of the "legacy-at-some-time" nodejs stream's onto the whatwg stream interface. This would mean dropping node versions < 15, which I'm guessing is too early since 14 is still in LTS until at least 2023.

- ...some other fix?

*Other thoughts*

The `page.screenshot` method no longer functions as well as it requires a Buffer polyfill (which is easily done in build systems, ie webpack). Unfortunately, it's not easy to fix this streams issue since there's a global `isNode` check to see if the environment is node or not. If we consider the web build to be a first-class citizen, perhaps puppeteer should take a more incremental approach to loading modules versus a one-size-fits all approach with the process and process.version lookups. For example, if a method uses a node-specific API perhaps try and load a browser-specific one instead like `ArrayBuffer`. Alternatively, since consumers already have to polyfill Buffer, perhaps we can get rid of most of the `isNode` checks where possible, and just naively assume that a polyfill will be provided by a build system. In any event, what's in place now isn't nearly the same off-the-shelf experience that node enjoys, so I'd like to make the web experience better.

Happy to chat more about this, but unfortunately it's been a somewhat painful experience getting puppeteer to work in the browser, and maintaining it in future versions. 

### Puppeteer version

>8.0.0

### Node.js version

14.x.x,16.x.x

### npm version

7.20.3

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Error: Cannot create a stream outside of Node.js environment.
```

**Comment by joelgriffith** [comment]
Checking in to see if anyone has any thoughts on the above?

**Comment by jschfflr** [comment]
Assigning to @jackfranklin as he's leading the agnostification project.

**Comment by jschfflr** [comment]
@jackfranklin gentle ping to see if you have any thoughts on this?

**Comment by joelgriffith** [comment]
Checking in on this -- happy to help out if need be, just want to be clear on direction since there's a few ways this can be tackled.

**Comment by joelgriffith** [comment]
Anything I can do to help here? Would love to get this in and don't mind spending time on a PR, just want to know if there's an overall sense of direction I can go that aligns with puppeteer's goals.

**Comment by joelgriffith** [comment]
@jschfflr let me know your thoughts on this issue (printing PDFs in the web-browsers ESM build). Happy to do the work, just need some consensus on what strategy to take so I can get the PR closer to what y'all would like to see.

**Comment by joelgriffith** [comment]
@OrKoN it appears you've taken over ownership of puppeteer judging by the commit logs. Do you have any input on the above, namely should puppeteer be more environment-sensitive and use browser-based APIs when ran in the browser? More of a incremental approach versus "node or not" hammer?

**Comment by OrKoN** [comment]
@joelgriffith sorry, just got pinged about it now. Yes, I think it'd be great for Puppeteer to be more environment-sensitive and use web APIs if available. We do want to support the LTS node versions though (e.g., v14). Unfortunately, we won't be able to dedicate time to this project but happy to review the PRs!

**Comment by joelgriffith** [comment]
@OrKoN I wouldn't mind doing the work for a web-based build. I think puppeteer today is pretty close to supporting it out-of-the-box, but I don't want to go through the effort if it's not a longer-term roadmap item. The alternative to this is forking puppeteer to support a web-based bundle, which I'm very hesitant to do.

We'd benefit a bit from this as we run puppeteer in a browser environment in a few places (which was supported back to about version 8 or 9).

**Comment by Lightning00Blade** [comment]
With the release of Puppeteer v23, this should work, as the change for the Buffer has been changed at https://github.com/puppeteer/puppeteer/pull/12823, if there are further issue please open a new bug.
