### ISSUE TITLE
[Bug]: page.screenshot() take too long time to complete when too many Browser/Page instance running

### ISSUE THREAD

**Issue by ddoonngg** [puppeteer/puppeteer#7625]
### Bug description

Hi there,

I am developing a website monitoring application using puppeteer and there are many Browser/Page instance running  at the same time.  In this case, `page.screenshot()` sometime takes too long time to complete and it may block my program. 

Is it reasonable provide a timeout option for `page.screenshot()` method?

Thanks

### Puppeteer version

10.0.0

### Node.js version

14.18.0

### npm version

6.x

### What operating system are you seeing the problem on?

Linux

**Comment by jschfflr** [comment]
@ddoonngg Thanks for taking the time to report this issue! Unfortunately, it doesn't seem possible to add a timeout to the underlying Chromium command that does the actual work of creating the screenshot. So adding one on the Puppeteer side would not really unblock anything. The only option might be to reduce the number of screenshots you are trying to capture at the same time or to launch multiple browser instances at the same time. 

Closing this as it's not really actionable atm but feel free to reopen if you have an idea on how to solve this!

**Comment by ddoonngg** [comment]
> Closing this as it's not really actionable atm but feel free to reopen if you have an idea on how to solve this!

It's a good idea to restrict screenshot on puppeteer. Thanks for the information and tips!
