### ISSUE TITLE
[Bug]: setRequestInterception not intercepting some xhr requests => forever pends.

### ISSUE THREAD

**Issue by EedoCelsius** [puppeteer/puppeteer#7627]
### Bug description

Steps to reproduce the problem:

```
const puppeteer = require("puppeteer");
(async () => {
    const browser = await puppeteer.launch({ headless: false, devtools: true })
    const page = await browser.newPage()
    await page.setRequestInterception(true)
    page.on("request", (req) => {
        req.continue()
    })
    await page.goto("https://www.google.com/maps")
})()
```
This should allow all requests to be continued, however as you can see from the devtools network tab, there are some xhr type requests that pends forever. (If you click and move through the map more pending requests will show up.) I've noticed that those requests that pends forever does not get intercepted by puppeteer and therefore could not get through the 'req.continue()' command. 

I heard there was a bug fix related to this in 10.2.0 or 10.0.0, but it seems like there still are problems.
This problem is same w/ and w/o 'page.setCacheEnabled(false)' command.

### Puppeteer version

10.4.0

### Node.js version

v14.16.0

### npm version

6.14.11

### What operating system are you seeing the problem on?

Windows

**Comment by jschfflr** [comment]
@EedoCelsius Thanks for taking the time to report this issue!
Could you share a screenshot of the Network panel in DevTools?
To me, it looks like the pending requests all originate from a service worker but I'd like to verify that before continuing to investigate.

**Comment by jschfflr** [comment]
I think this is a valid bug report - the requests should not be paused.
I just wanted to make sure that this only affects requests from the service worker to pinpoint the problem!

**Comment by EedoCelsius** [comment]
Network panel in devTool shows only requests with gear icon pending (which I believe represents the service worker requests).

-------------------------------------------------------------------------

But aside from what devtool shows I think there MIGHT be other non-service-worker requests that are pending. Because, as I know service workers should be designed not to affect what is happening on the mainframe, however there are components on mainframe that are not being loaded when interception is on even with every requests continued, therefore google map search is not working properly. I know almost nothing about service workers so consider this as just an opinion plz.
