### ISSUE TITLE
[Bug]: Screenshot is different from screen view

### ISSUE THREAD

**Issue by maksimr** [puppeteer/puppeteer#7632]
### Bug description

Steps to reproduce the problem:

1. Install puppeteer@10.2.0
2. Add markup with text-decoration: underline, font-size=12px
3. Take a screenshot with default options ([window.screenshot](https://github.com/maksimr/karma-image-snapshot/blob/master/src/snapshot-launcher.js#L64-L69) exposed screenshot function to window object)

ER: Screenshot should be the same as what we see on the screen

Note: Problem reproduced only on M1 MacBook, on Linux or Intl version it works fine.

https://user-images.githubusercontent.com/616193/136177939-44cabc63-a027-4fdf-b82b-798bc261ec2b.mov

OS - **macOS Big Sur (M1, 2020)**
Chromium - Version 93.0.4577.0 (Developer Build) (x86_64 translated) **Installed by puppeteer automatically**
Font - [Custom font](https://github.com/maksimr/foo-font)

### Puppeteer version

10.2.0

### Node.js version

14.17.6

### npm version

6.14.15

### What operating system are you seeing the problem on?

macOS

**Comment by jschfflr** [comment]
@maksimr Thanks for taking the time to report this issue! As Linux and Intl versions are working fine, this is most likely a problem with Chromium itself. Please file a bug on https://crbug.com/ and feel free to link to this issue there. 
I'll close this issue for now but feel free to reopen if it turns out to be related to puppeteer after all.

**Comment by maksimr** [comment]
@jschfflr I have investigated the problem and the reason Intl version of Chromium which shipped with puppeteer on Apple M1. Chrome with native support M1 works as expected. As I see, Chromium v94.0.4589.0 should also natively support M1, and it's already [stable version](https://chromiumdash.appspot.com/releases?platform=Mac)
Why puppeteer use old one version of Chromium?

**Comment by maksimr** [comment]
https://github.com/puppeteer/puppeteer/pull/7546
