### ISSUE TITLE
[Bug]: Chromium version in 10.4.0 is not working

### ISSUE THREAD

**Issue by AviadBelulu** [puppeteer/puppeteer#7638]
### Bug description

Steps to reproduce the problem:

use latest chrome
run the tests

Original:
Object.defineProperty(exports, "__esModule", { value: true });
exports.PUPPETEER_REVISIONS = void 0;
exports.PUPPETEER_REVISIONS = {
    chromium: '901912',
    firefox: 'latest',
};

I tried to update it manually in the node modules to
Object.defineProperty(exports, "__esModule", { value: true });
exports.PUPPETEER_REVISIONS = void 0;
exports.PUPPETEER_REVISIONS = {
    chromium: '911268',
    firefox: 'latest',
};

and it works

### Puppeteer version

10.4.0

### Node.js version

14.16.0

### npm version

7.8.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Current browser version is 93.0.4577.0 with binary path node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome

  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 4.15.0-154-generic x86_64)

[15:12:53] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 94

Current browser version is 93.0.4577.0 with binary path node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome

  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 4.15.0-154-generic x86_64)


[15:12:53] E/launcher - Process exited with error code 199

script returned exit code 1
```

**Comment by jschfflr** [comment]
@AviadBelulu Thanks for taking the time to report this bug! Unfortunately, I'm not sure I can follow along. Could you explain how to reproduce what you tried to do?

**Comment by AviadBelulu** [comment]
sure @jschfflr ,
I updated to the latest version op Puppeteer (10.4.0)
which is using the chrome revision of 901912,
the result is this chrome version:
node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome
(as it is in the \node_modules\puppeteer\lib\cjs\puppeteer\revisions.js)
Current browser version is 93.0.4577.0 

and when I run it I get the issue of chrome driver
my machine chrome version is higher:
Driver info: chromedriver=94.0.4606.61 


which is what in the log
[15:12:53] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 94

Current browser version is 93.0.4577.0 with binary path node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome


so the solution was to update the chrome version inside
\node_modules\puppeteer\lib\cjs\puppeteer\revisions.js

but if I do it manually it effects only my machine,
I need that the package will be updated to the version of chrome :)

thank you

**Comment by jschfflr** [comment]
Ah ok, I see. So this is about chrome driver not working with the Chromium version that we're currently shipping.
We are currently working on rolling Puppeteer to the latest Chromium version but ran into some problems. You can read more about it here: https://github.com/puppeteer/puppeteer/issues/7458
Closing this as a duplicate. But thanks for reporting this anyways!
