### ISSUE TITLE
[Bug]: browser process hangs forever trying to interact with default XML style

### ISSUE THREAD

**Issue by Kikobeats** [puppeteer/puppeteer#7641]
### Bug description

![CleanShot 2021-10-07 at 00 00 37@2x](https://user-images.githubusercontent.com/2096101/136289522-cfbc8420-90b7-49ec-8948-eca69107b565.png)

I noted puppeteer hangs forever if you add a custom stylesheet to an XML URL that already has the default Chrome style (this is very common for sitemaps)

Steps to reproduce the problem:

```js
const puppeteer = require('puppeteer')
const termImg = require('term-img')

;(async () => {
  const browser = await puppeteer.launch()
  const context = await browser.createIncognitoBrowserContext()
  const page = await context.newPage()

  await page.goto('https://leerob.io/sitemap.xml')
  await page.addStyleTag({ content: 'body{background: red}' })

  const buffer = await page.screenshot()

  console.log(termImg(buffer))

  await browser.close()
})()
```

Running puppeteer in a non-headless way I can see how the stylesheet is actually added to the page, but the buffer with the content is never returned at the code level, it hangs there forever.

Note it's only happening with the default Chrome style for XML! 

If you target an XML that is not using the default Chrome style (for example [this](https://softkube.com/sitemap.xml), it's working fine.

<img width="419" alt="CleanShot 2021-10-07 at 00 02 30@2x" src="https://user-images.githubusercontent.com/2096101/136289763-e419dd5e-adda-4342-b7cd-745cebb1eed8.png">

Also, it's not a thing related to screenshotting. I used `page.screenshot()` to make it evident but the same behavior is there even you use `page.content()`

### Puppeteer version

10.4.0

### Node.js version

14.18.0

### npm version

6.14.15

### What operating system are you seeing the problem on?

Tested the error is present on Linux and macOS

**Comment by jschfflr** [comment]
It looks like blink is treating the xml document differently when there is no style information attached: 
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/xml/parser/xml_document_parser.cc;l=1576;drc=1bbf8ac9caa7e57a52a71deec56bf1b6f683c6bd;bpv=1;bpt=1

I will mark this as won't fix for puppeteer but feel free to file a bug on https://crbug.com if you feel like this should be possible!

**Comment by Kikobeats** [comment]
@jschfflr do you know if is it a way (maybe a flag?) to disable the XML default style behavior? that will resolve the issue

**Comment by jschfflr** [comment]
From looking at the code, it doesn't seem possible unfortunately. But you could maybe try to use request interception to modify the response to get it into rendering custom styles.

**Comment by Kikobeats** [comment]
I tried to intercept the requests, however, the the `stylesheet` content type is not emitted since the style is adding by the browser itself 😭

**Comment by jschfflr** [comment]
I thought maybe it would be possible to add a reference to the stylesheet when intercepting the xml response.
