### ISSUE TITLE
Puppeteer not saving every userData(Cookies)

### ISSUE THREAD

**Issue by sijomonbenny** [puppeteer/puppeteer#7643]
While using useDataDir
```
const browser = await puppeteer.launch({
        ...launch_options,  
        userDataDir: "./userDirectory",  
      });
```
Its not actually storing every cookies for a website. While inspecting that, Its observed that it is not storing the cookies of the subdomain. It only stores the cookies of the main domain.

**Comment by jschfflr** [comment]
@sijomonbenny Thanks for taking the time to file this issue!
Could you share a snippet that reproduces the problem?

**Comment by jschfflr** [comment]
@sijomonbenny I'm gonna close this as it's currently not actionable.
Feel free to reopen with a reproduction! Thanks!
