### ISSUE TITLE
Puppeteer 10.4.0 not works with firefox nigtly

### ISSUE THREAD

**Issue by Rasanjika** [puppeteer/puppeteer#7647]
### Bug description

Steps to reproduce the problem:

1. …
Automate script . 
Add click event
It waits for the selector and time out

### Puppeteer version

10.4.0

### Node.js version

v14.17.3

### npm version

6.14.13

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Waits to capture the UI element button and time out
```

**Comment by whimboo** [comment]
@Rasanjika can you please re-check with latest Firefox Nightly? Is it still a problem? If yes please provide a minimal test case that reproduces the failure. Thanks.

**Comment by whimboo** [comment]
No reply from the reporter. Closing the issue.
