### ISSUE TITLE
Test times out if slowMo:100 is not enabled

### ISSUE THREAD

**Issue by SMJ93** [puppeteer/puppeteer#766]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Mac OS Sierra 10.12.6
* Node: 8.1.0
* NPM: 5.4.1

**What steps will reproduce the problem?**

We are using React Widgets [DateTimePicker](http://jquense.github.io/react-widgets/api/DateTimePicker/). If we use `slowMo: 100` the test runs successfully as expected. If we don't use slow mo it fails because it times out because it can't find the month selector.

Code:

```
export default async (page, element) => {

  await page.click(`${element} button`);

  await page.click(`button${element}_cal_calendar_label`);
  await page.click(`button${element}_cal_calendar_label`);

  await page.click(`${element} button.rw-btn-left.rw-btn`);
  await page.click(`${element} button.rw-btn-left.rw-btn`);

  await page.waitForSelector(`table${element}_cal_calendar tbody tr td${element}_cal_calendar__decade_1993 span`);
  await page.click(`table${element}_cal_calendar tbody tr td${element}_cal_calendar__decade_1993 span`);

  // Note: Month click breaks it if not in slowMo
  await page.waitForSelector(`table${element}_cal_calendar tbody tr td${element}_cal_calendar__year_1993-7 span`)
  await page.click(`table${element}_cal_calendar tbody tr td${element}_cal_calendar__year_1993-7 span`);

  // Day
  await page.waitForSelector(`table${element}_cal_calendar tbody tr td${element}_cal_calendar__month_7-18 span`);
  await page.click(`table${element}_cal_calendar tbody tr td${element}_cal_calendar__month_7-18 span`);

  return page;
}
```

To Reproduce:
1. Run a test against the date picker [here](http://jquense.github.io/react-widgets/api/DateTimePicker/) using the code above.

**What is the expected result?**
The test should pass without sloMo.

**What happens instead?**
If times out if sloMo isn't enabled.

**Comment by SMJ93** [comment]
The animation from the Date picker resulted in weird behaviour.

In case anyone else has this problem, we fixed this by creating our own `wait(ms)` function.
```
export default ms => new Promise(resolve => setTimeout(resolve, ms));
```

Use case:
```
await page.click(`button${element}_cal_calendar_label`);
await page.click(`button${element}_cal_calendar_label`);

await delay(100);
await page.click(`${element} button.rw-btn-left.rw-btn`);
await page.click(`${element} button.rw-btn-left.rw-btn`);
```

**Comment by ebidel** [comment]
@SMJ93 protip: `waitFor` also supports a ms value:

`await page.waitFor(100);`

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectororfunctionortimeout-options
