### ISSUE TITLE
waitForNavigation is flaky

### ISSUE THREAD

**Issue by thetutlage** [puppeteer/puppeteer#767]
When redirects happens, the `waitForNavigation` at times returns `null`. This is not happening for 100% of times, but happens suddenly.

After debugging more, I found that the value of `waitForNavigation` relies on `mainFrame().url()`, which still returns the correct value.

```js
await page.click('a')
const response = await page.waitForNavigation()
const url = page.mainFrame().url()
```

1. Now let's say `a` takes me to a different URL
2. At times `response` is null.
3. And `url` shows the new url of the redirected page

**Comment by aslushnikov** [comment]
@thetutlage that might be because awaiting the `page.click` already triggered the navigation (and we missed the main resource response).

Would the following work for you?
```js
const [response] = await Promise.all([
  page.waitForNavigation(),
  page.click('a')
]);
```

**Comment by thetutlage** [comment]
Yup that works. Thanks 😄
