### ISSUE TITLE
[Bug]:  page.off("request") is messed up because of interceptCooperative mode

### ISSUE THREAD

**Issue by EedoCelsius** [puppeteer/puppeteer#7675]
### Bug description

Steps to reproduce the problem:

PAGE.JS
```
on(eventName, handler) {
    if (eventName === 'request') {
        return super.on(eventName, (event) => {
            event.enqueueInterceptAction(() => handler(event));
        });
    }
    return super.on(eventName, handler);
}
```

This is the page.on() method. Because it is overriding the handlers for events with eventName "request", the original handler is not removable by 

INDEX.JS
```
off(type, handler) {
    const handlers = all.get(type); 
    if (handlers) {
        handlers.splice(handlers.indexOf(handler) >>> 0, 1);
    }
}
```
and I'm wondering what ' >>> 0' is needed for.

### Puppeteer version

10.4.0

### Node.js version

v14.16.0

### npm version

6.14.11

### What operating system are you seeing the problem on?

Windows

**Comment by EedoCelsius** [comment]
works great when
```
on(eventName, handler) {
    if (eventName === 'request') {
        return super.on(eventName, (event) => {
            event.enqueueInterceptAction(() => handler(event));
        });
    }
    return super.on(eventName, handler);
}
```
deleted from PAGE.JS (cooperative wouldn't work probably)

**Comment by jpxzp** [comment]
fixed https://github.com/puppeteer/puppeteer/pull/7624

**Comment by franksoong** [comment]
i still can see the same issue with "puppeteer": "13.5.2",
