### ISSUE TITLE
[Bug]: puppeteer 10.4.0 with headless: false does not show the browser (it works like headless: true) 

### ISSUE THREAD

**Issue by bartmanskyi** [puppeteer/puppeteer#7685]
### Bug description

puppeteer 10.4.0 with `headless: false` does not show the browser (it works like `headless: true`) 

Steps to reproduce the problem:
```

const chromium = require('chrome-aws-lambda'); // 10.1.0 - ver 92
(async () => {

  const browser = await chromium.puppeteer.launch({
    args:[
      '--allow-running-insecure-content',
      '--autoplay-policy=user-gesture-required',
      '--disable-component-update',
      '--disable-domain-reliability',
      '--disable-features=AudioServiceOutOfProcess,IsolateOrigins,site-per-process',
      '--disable-print-preview',
      '--disable-setuid-sandbox',
      '--disable-site-isolation-trials',
      '--disable-speech-api',
      '--disable-web-security',
      '--disk-cache-size=33554432',
      '--enable-features=SharedArrayBuffer',
      '--hide-scrollbars',
      '--ignore-gpu-blocklist',
      '--in-process-gpu',
      '--mute-audio',
      '--no-default-browser-check',
      '--no-pings',
      '--no-sandbox',
      '--no-zygote',
      '--use-gl=swiftshader',
      '--start-maximized',
      '--window-size=1920,1080'
    ],    
    headless: false,
    defaultViewport: chromium.defaultViewport,
    ignoreHTTPSErrors: true,
    executablePath: '/usr/bin/chromium-browser', // ver 94
    userDataDir: '/tmp/chromium_cache/',
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

Using browserfetcher revision **r894212** it works good
Revision **r901912** does not work as expected (headless: false does not work)

### Puppeteer version

10.4.0

### Node.js version

12.15.0

### npm version

6.14.2

### What operating system are you seeing the problem on?

Linux

**Comment by pankhiprasher** [comment]
hey @bartmanskyi i am running crawlsite.js function from puppeteer/examples/crawlsite.js path in their git repo and i am seeing the exact same issue - 
[186875:186875:0318/202225.133327:ERROR:ozone_platform_x11.cc(234)] Missing X server or $DISPLAY
[186875:186875:0318/202225.133388:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237:20)
    at Interface.<anonymous> (/root/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:227:68)
    at Interface.emit (node:events:539:35)
    at Interface.close (node:internal/readline/interface:529:10)
    at Socket.onend (node:internal/readline/interface:258:10)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1342:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)


I dont know why it works in headless true but as soon as i change it to headless false it doesnt launch chrome browser and gives this error. 
Can anyone please help?
