### ISSUE TITLE
can not click extension icon

### ISSUE THREAD

**Issue by viponedream** [puppeteer/puppeteer#7697]
### Bug description

i load an extension. 
and the extension need some click , some text to fill. 
how to click the icon on the  toolbar?

it doesn't work in page or target mode.  
like chrome-extension://kapldphlnoaojkfljhlamabejclblpch/home.html#settings/networks  -->> doesn't work.

only click the toolbar icon works. 

How can i control the icon on toolbar?

Steps to reproduce the problem:

1. …

### Puppeteer version

last

### Node.js version

last

### npm version

last

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
see above
```

**Comment by jrandolf-google** [comment]
Cannot reproduce.
