### ISSUE TITLE
Document `Page.setSize()` method

### ISSUE THREAD

**Issue by addyosmani** [puppeteer/puppeteer#77]
Thanks for the awesome module 🏆  

I realize the docs are a WIP.

From the README:

> Puppeteer sets an initial page size to 400px x 300px, which defines the screenshot size. The page size can be changed with Page.setSize() method

`setSize()` does not however appear to have any API docs over in https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md. Looking through the repo via [code-search](https://github.com/GoogleChrome/puppeteer/search?utf8=%E2%9C%93&q=setsize&type=) the README entry for this method appears to be the only one in there :)

Is there another issue tracking adding docs for methods like this?

**Comment by paulirish** [comment]
Hah, that's a bug/typo. The method is called `page.setViewportSize` and it's documented.

We actually have some tooling in place to make sure every method in the public API has a heading in api.md, but it didn't catch this sort of mistake. :)

**Comment by aslushnikov** [comment]
Thanks, fixed.
