### ISSUE TITLE
No argument is passed to waitForFunction/waitFor

### ISSUE THREAD

**Issue by entrptaher** [puppeteer/puppeteer#770]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ^0.10.2
* Platform / OS version: Ubuntu 16.04.2 LTS

**What steps will reproduce the problem?**

## Problem 1: arguments passed to waitFor is undefined:
1. Pass any argument to waitFor or waitForFunction.
2. Get/Call that argument inside the function.
3. It's `undefined`.

## Problem 2: `arguments` property inside page.evaluate is undefined.
1. Call `arguments` inside any page.evaluate function.
2. It's undefined and results in TypeError.

```js
const puppeteer = require('puppeteer');
(async() => {
  const browser = await puppeteer.launch({headless: false});

  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.waitForFunction((args) => {
     
    // some tests to show what is happeneing.
    console.log([
      args, // should show args
      arguments, // should not have 0 elements
      Array.isArray(args), // should return True
      Array.isArray([1, 2, 3, 4]) // should return True
    ]);

    return Array.isArray(args);
  }, [1, 2, 3, 4]); // no matter what you pass, it's still undefined;

  await page.screenshot({path: 'example.png'});
  //browser.close();
})();
```

Meanwhile, the evaluate method shows `arguments` as undefined while the args provided is working properly.
```js
await page.evaluate((args) => {
    // shows `ReferenceError: arguments is not defined`
    console.log(arguments)

    // runs properly
    console.log([
      args,
      Array.isArray(args),
      Array.isArray([1, 2, 3, 4])
    ]);

    return Array.isArray(args);
  }, [1, 2, 3, 4]);
```

**What is the expected result?**
It should behave like `page evaluate` and the arguments should be passed properly.

**What happens instead?**
Arguments are not passed.
Waits are timed out.

Screenshot of console with the code ran thru.
![image](https://user-images.githubusercontent.com/8284972/30393307-71b73e58-98e1-11e7-9d1d-15f7cc32f637.png)

**Comment by vsemozhetbyt** [comment]
> Problem 1: arguments passed to waitFor is undefined:

It seems you missed the [`options` argument](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforfunctionpagefunction-options-args).

Try to replace this line:
```js
  }, [1, 2, 3, 4]); // no matter what you pass, it's still undefined;
```
with this one;
```js
  }, {}, [1, 2, 3, 4]); // no matter what you pass, it's still undefined;
```

**Comment by vsemozhetbyt** [comment]
> Problem 2: arguments property inside page.evaluate is undefined

[Arrow functions do not bind an `arguments` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_arguments). Try this line in the browser console:
```js
(() => { console.log(arguments); })(true);
```

**Comment by vsemozhetbyt** [comment]
What seems unexpected is that in the first case `arguments` is defined:

![1](https://user-images.githubusercontent.com/10393198/30395500-18798218-98cf-11e7-8738-baf468fa3f35.png)

Are functions for `.waitForFunction()` and `.evaluate()` handled differently?

**Comment by vsemozhetbyt** [comment]
Maybe in the `.waitForFunction()` case the arrow function is wrapped in some common function and gets its `arguments`:
```js
(function () {(() => { console.log(arguments); })(true); })()
```
```console
[callee: ƒ, Symbol(Symbol.iterator): ƒ]
```

**Comment by JoelEinbinder** [comment]
@vsemozhetbyt is right about `arguments`. For `waitForFunction` the function is wrapped in another function `waitForPredicatePageFunction`. So the `arguments` will be from the outer function.

As mentioned above, the problem was that you were missing the `options` object in between the function and the `..args`.

**Comment by vsemozhetbyt** [comment]
@JoelEinbinder It seems that currently `frame.waitForFunction()` and `page.waitForFunction()` are only two functions with 2 optional parameters, when omitting the first optional parameter is forbidden if the second is used. Maybe in these cases, you can format the signature as Node.js docs do (compare [`assert.fail(actual, expected[, message[, operator[, stackStartFunction]]])`](https://nodejs.org/api/assert.html#assert_assert_fail_actual_expected_message_operator_stackstartfunction) and [`assert.doesNotThrow(block[, error][, message])`](https://nodejs.org/api/assert.html#assert_assert_doesnotthrow_block_error_message)):

`page.waitForFunction(pageFunction[, options[, ...args]])`

`frame.waitForFunction(pageFunction[, options[, ...args]])`

**Comment by vsemozhetbyt** [comment]
And maybe some examples are needed to state what is appropriate as a filler of `options` argument (`{}`, `null`, `undefined`).

**Comment by entrptaher** [comment]
I tried that already and then created this issue. 
Yeah seems like a silly mistake about the evaluate and arrow function :D .

Maybe because I did not provide anything in the optional argument, that's why it happened.
What if I want to use the default options instead of providing it myself? Providing an empty one results in same error.

![image](https://user-images.githubusercontent.com/8284972/30402948-4054b730-9901-11e7-8b92-56d9c397ce38.png)

More silly problems?
This is the only one that worked,
```
  await page.waitForFunction(function(args){
    return Array.isArray(args);
  }, {timeout: 60000}, [1, 2, 3, 4]); 
```

But I will say, the docs are misleading then. It does not say that *I cannot provide empty object to that optional param* when providing additional arguments.

`  }, {}, [1, 2, 3, 4]); `

Why should this fail then? :/

Am I making more silly mistakes?

**Comment by vsemozhetbyt** [comment]
@entrptaher In your last screenshot, you use `waitFor()`, which [does not support](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectororfunctionortimeout-options) arguments transferring currently, unlike `waitForFunction()`.

**Comment by vsemozhetbyt** [comment]
It seems `waitFor()` will support arguments transferring after https://github.com/GoogleChrome/puppeteer/pull/775 is landed.

**Comment by aslushnikov** [comment]
> Maybe in these cases, you can format the signature as Node.js docs do

@vsemozhetbyt i'd love this. Would you mind sending a PR?

**Comment by vsemozhetbyt** [comment]
@aslushnikov It seems this is already done in the https://github.com/GoogleChrome/puppeteer/pull/775

**Comment by entrptaher** [comment]
Great, the docs were so incomplete and misleading that I ended up having problem. 

```js
  await page.waitForFunction(function(args){
    return Array.isArray(args);
  }, {}, [1, 2, 3, 4]);
```

This above works as well. :+1: 
I will close this issue for now since everything is going as expected.
And thanks for the PR.
