### ISSUE TITLE
Communication Channel

### ISSUE THREAD

**Issue by adimon91** [puppeteer/puppeteer#7705]
I wish to start a communication channel for this project. As a student I'm looking to contribute but it's hard to know where to start. I think having a communication channel would really help encourage new contributors! If this is something the project managers think would benefit Puppeteer, comment on this issue and I can set up a Discord or Slack and update the ReadMe appropriately. Thank you!

**Comment by OrKoN** [comment]
Thanks for the suggestion but for now we have no capacity to manage an official discussion channel.
