### ISSUE TITLE
[Bug]: different format in function  string.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) comma instead of dot in thousands of places

### ISSUE THREAD

**Issue by viny701** [puppeteer/puppeteer#7712]
### Bug description

using a string.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) is getting me commas instead of dots in the thousands place. I use puppeteer with ejs, can someone help me with this little problem?
This error started to appear after I updated the dependencies, I don't remember which version it was in before.

### Puppeteer version

6.14.6

### Node.js version

v12.18.4

### npm version

6.14.6

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.
