### ISSUE TITLE
[Bug]: Puppeteer seems to not work with proxys

### ISSUE THREAD

**Issue by iJoris** [puppeteer/puppeteer#7719]
### Bug description

Steps to reproduce the problem:

1. … Find an IP:PORT HTTP proxy
2. Run simple puppeteer example
3. see ERR_TUNNEL_FAILED

```
const puppeteer = require("puppeteer");

(async () => {

  let proxyserver = "--proxy-server=" + '127.0.0.1:2882';

  const browser = await puppeteer.launch({
    args: [proxyserver],
    headless: false,
    ignoreHTTPSErrors: true,
  });

  const page = await browser.newPage();
  await page.goto("https://www.whatismyip.com/");
  await page.screenshot({ path: "example.png" });
})();
```

### Puppeteer version

10.2.0

### Node.js version

14.7

### npm version

6.14

### What operating system are you seeing the problem on?

Windows

**Comment by phmLabs** [comment]
Have the same issue. Started with Puppeteer 10.

**Comment by adrianmihalko** [comment]
I have same problem.

I am trying to use local tor proxy with puppeteer, but for some reason it is not using it:

```
const puppeteer = require('puppeteer');

async function getPic(arg){
    console.log(arg);
    const browser = await puppeteer.launch({
    args: [
      '--proxy-server=socks5h://127.0.0.1:9050',
    ],
    });
    var gh = 0;
    while(gh < 1000){
      const context = await browser.createIncognitoBrowserContext();

      const page = await context.newPage();

    await page.goto('http://ipinfo.io/',{waitUntil: 'networkidle2'});
    await page.screenshot({path: 'screenshot.png'});

    console.log("done for" + gh);
    gh++;
  }
    await browser.close();
}

getPic(process.argv[2]);
```

As a result I still see my original IP on the result screenshot. Proxy is working correctly, I checked with curl.

**Comment by phmLabs** [comment]
Did somebody check if this is a Chrome or a Puppeteer issue? Did Chrome perhaps change the parameter?

**Comment by mzalazar** [comment]
💥💥 Tor PROXY doesn't work when using incognito mode 💥💥

**Comment by iJoris** [comment]
Found out that my local ISP blocked the proxy. When I turned on an vpn the proxy worked perfectly. 

Please note that the last working version of puppeteer is 10.2, any above that the incognito proxy function is still broken.

https://github.com/puppeteer/puppeteer/pull/7770
