### ISSUE TITLE
[Bug]: Installation script error

### ISSUE THREAD

**Issue by renardspark** [puppeteer/puppeteer#7725]
### Bug description

I have encountered a problem during the installation of puppeteer with `npm install puppeteer`. When it try to launch install.js, it crash with error : command failed

Here is the log file created :
[2021-10-27T09_43_21_025Z-debug.log](https://github.com/puppeteer/puppeteer/files/7425102/2021-10-27T09_43_21_025Z-debug.log)

However, I can install puppeteer with `npm install --ignore-scripts puppeteer` and launch install.js manually after that, but I think it's not normal to have this error.

### Puppeteer version

10.4.0

### Node.js version

14.18.1

### npm version

8.1.1

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
npm ERR! code 1
npm ERR! path /home/remi/nodejs/octopart/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/remi/.npm/_logs/2021-10-27T09_43_21_025Z-debug.log
```

**Comment by allandiego** [comment]
im facing same error with nvm node 16.1 and puppeteer 11.0.0

**Comment by azatmagdeev** [comment]
Ubuntu 18.04.6 LTS
node v16.15.1
npm 8.11.0
puppeteer 15.1.0

failed npm install

```
npm ERR! code 1
npm ERR! path /home/node_js/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
```

UPD! This error on nodejs intalled by snap
SOLUTION: #7383 install nodejs from NodeSource

**Comment by OrKoN** [comment]
It looks like it's a problem with a node installation? Please re-open if it still happens.

**Comment by Theiremi** [comment]
It no longer happens to me thanks.
However, I have switched to NodeSource, and maybe it's the reason why it's patched, like @azatmagdeev have noticed.

**Comment by holocronweaver** [comment]
I also had this error on a clean Ubuntu 22.04 install using node from snap.
```
$ npm install puppeteer
npm ERR! code 1
npm ERR! path /home/jesse/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
```

npm ERR! A complete log of this run can be found in: /home/jesse/.npm/_logs/2023-04-10T22_12_53_023Z-debug-0.log

And as original poster mentioned, installing without scripts works:
```
$ npm install --ignore-scripts puppeteer

added 86 packages, and audited 87 packages in 674ms

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

No issues installing any other node packages, just puppeteer.
