### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) vulnerability through ms

### ISSUE THREAD

**Issue by emadehsan** [puppeteer/puppeteer#773]
Snyk.io's test shows that Puppeteer carries a low severity vulnerability "Regular Expression Denial of Service (ReDoS)" through `ms` package:

https://snyk.io/test/github/GoogleChrome/puppeteer

**Comment by Garbee** [comment]
This is through the `extract-zip` package which is only used to unzip the archive downloaded to run Chromium from. All of it's uses within puppeteer are known extents therefore low probability that any attack could be carried out through using this package version.

**Comment by emadehsan** [comment]
Yup
