### ISSUE TITLE
[Bug]: Failed to launch the browser process! spawn /usr/src/app/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome 

### ISSUE THREAD

**Issue by qubitts** [puppeteer/puppeteer#7733]
### Bug description

Steps to reproduce the problem:

I am using puppeteer in a MERN application, locally this package works fine but when I deployed my application on AWS EC2. I got the error and I deployed my MERN application on EC2 using Docker container. Basically a docker container of my application is running on AWS EC2 and when I try to download the pdf I got this error:

`Failed to launch the browser process! spawn /usr/src/app/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome ENOENT\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n`

I don't know How to solve this error. Please share the solution to this problem with me.

Thanks

### Puppeteer version

10.4.0

### Node.js version

14.17.1

### npm version

6.14.13

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Failed to launch the browser process! spawn /usr/src/app/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome ENOENT\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n
```

**Comment by amarinediary** [comment]
see #5379
