### ISSUE TITLE
[Bug]: Raspberry Pi - Error: Failed to launch the browser process! ... Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by just-rich** [puppeteer/puppeteer#7736]
### Bug description

Steps to reproduce the problem:

I'm not a developer, so apologies if this is long- just want to explain as much I can to be understood.

Running this on `Raspbian GNU/Linux 10 (buster)` - I had a developer make a discord bot that automatically relays messages from a channel onto a social media platform, it also takes a screenshot of the message and uploads it with the post. I can also manually post using the bot and upload an image.

The manual posting works perfectly fine, with image upload too. But it's crashing when trying to do the auto-posting. I've upgraded node.js like the troubleshoot guide said, but still didn't work. Not sure what this error is related to and how to fix.

Any suggestions would be great 

### Puppeteer version

10.4.0

### Node.js version

10.24.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
/home/pi/discordbots/peggy/stocktwits/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/home/pi/discordbots/peggy/stocktwits/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: 1: /home/pi/discordbots/peggy/stocktwits/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: Syntax error: ")" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/pi/discordbots/peggy/stocktwits/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.<anonymous> (/home/pi/discordbots/peggy/stocktwits/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by rich1488** [comment]
someone, please?

**Comment by rich1488** [comment]
can someone help??

**Comment by EqualMa** [comment]
Run into the same situation on `Raspbian GNU/Linux 11 (bullseye)` with `puppeteer@13.0.0`, even after reinstalling all apt dependencies listed [here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix).

But I found a workaround with `puppeteer-core`:

```js
const puppeteer = require("puppeteer-core");
const browser = await puppeteer.launch({ executablePath: "chromium-browser" });
```

**Comment by mattinatux** [comment]
Ran into this one today on a fresh install of Node.JS on a fresh Raspberry Pi (ARM v8), with the same bandaid working.

node -v
v20.5.1
