### ISSUE TITLE
[Bug]: API link doesn't work

### ISSUE THREAD

**Issue by sulthan-ahmed** [puppeteer/puppeteer#7738]
### Bug description

Steps to reproduce the problem:

1. go to the github puppeteer page
2. click on the api link which is pointing to https://github.com/puppeteer/puppeteer/blob/v11.0.0/docs/api.md it returns a 404

### Puppeteer version

NA

### Node.js version

NA

### npm version

NA

### What operating system are you seeing the problem on?

macOS

**Comment by harshagrawal523** [comment]
Hi @sulthan-ahmed ! Can I work on this issue?

**Comment by sulthan-ahmed** [comment]
Hi @harshagrawal523 looks like someone has fixed it maybe it was yourself. Thank you either way 🙂
