### ISSUE TITLE
[Bug]: page.goBack() only works in headless mode 

### ISSUE THREAD

**Issue by javierfuentesm** [puppeteer/puppeteer#7739]
### Bug description

The following code only runs successfully in headless mode 
`const puppeteer = require('puppeteer')

describe('Mi primer test de puppeteer', () => {
	it('Debe abrir y cerrar el navegador el navegador', async () => {
		const browser = await puppeteer.launch({
			headless: false,
			defaultViewport: null,
		})
		const page = await browser.newPage()

		await page.goto('http://automationpractice.com/index.php')
		// await page.waitForTimeout(5000)
		await page.waitForSelector('img')
		await page.reload()
		await page.waitForSelector('img')
		await page.goto('https://www.platzi.com/')
		await page.waitForSelector(
			'#home-public > div > div.Header-v2.Header-v2-content.is-dark-header > div.Logo > div > a > div > figure.LogoHeader-name > img'
		)
		await page.goBack()

		await page.waitForSelector('img')

		//Navegar hacia adelante
		await page.goForward()
		await page.waitForSelector(
			'#home-public > div > div.Header-v2.Header-v2-content.is-dark-header > div.Logo > div > a > div > figure.LogoHeader-name > img'
		)

		const page2 = await browser.newPage()
		await page2.goto('https://www.google.com/')

		//esperar por texto en la pagina
		await page2.waitForSelector('img')
		await page.bringToFront()
		await page.waitForSelector(
			'#home-public > div > div.Header-v2.Header-v2-content.is-dark-header > div.Logo > div > a > div > figure.LogoHeader-name > img'
		)
		await page.waitForTimeout(5000)

		await browser.close()
	}, 300000)
})
`

but if you disabled the headless mode sometimes passes but sometimes it doesn't.The error is in the instruction page.goBck()
![image](https://user-images.githubusercontent.com/19244527/139940624-c4af6aae-8b81-49ec-8844-44481f0eae17.png)

even if you comment everything else after that instruction keeps failing there , i think the error is that it doesn't detect the page after going back like if it was stored on cache and it fails even though the navigation back was successfully

### Puppeteer version

"^10.4.0"

### Node.js version

v12.18.2

### npm version

7.20.1

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
TimeoutError: Navigation timeout of 30000 ms exceeded

      22 |              )
      23 |              //Navegar hacia atras
    > 24 |              await page.goBack({ waitUntil: 'networkidle2' })
         |              ^
      25 |
      26 |              await page.waitForSelector('img')
      27 |

      at node_modules/puppeteer/src/common/LifecycleWatcher.ts:204:18
      at FrameManager.waitForFrameNavigation (node_modules/puppeteer/src/common/FrameManager.ts:212:19)
      at Frame.waitForNavigation (node_modules/puppeteer/src/common/FrameManager.ts:673:12)
      at Page.waitForNavigation (node_modules/puppeteer/src/common/Page.ts:1801:12)
          at async Promise.all (index 0)
      at Page._go (node_modules/puppeteer/src/common/Page.ts:2050:20)
      at Object.<anonymous> (__tests__/navegador.test.js:24:3)
```

**Comment by bartmanskyi** [comment]
It looks similar with these issues
https://github.com/puppeteer/puppeteer/issues/7685
https://github.com/puppeteer/puppeteer/issues/7743
I found out that it had happened in puppeteer v10.2.0, when Chromium was rolled up to ver 93
@javierfuentesm Can you try to run your code with puppetter v 10.1.0?

**Comment by javierfuentesm** [comment]
@bartmanskyi it keeps failing with that version , i think it is related that the first page is not https ,I switched the page to a https for example yahoo and it works fine with the version. `10.1.0` , but it also works fine with the version		`"puppeteer": "^10.4.0"` if I use yahoo and I add this to the puppeteer.launch it also works :

 `		const browser = await puppeteer.launch({
			headless: false,
			defaultViewport: null,
			args: ['--no-sandbox', '--disable-dev-shm-usage', '--enable-features=NetworkService'],
			ignoreHTTPSErrors: true,
			dumpio: false,
		})`

So this is super weird

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.
