### ISSUE TITLE
Should `HTTPRequest`'s `interceptResolution` be public?

### ISSUE THREAD

**Issue by Tyler-Murphy** [puppeteer/puppeteer#7745]
https://github.com/puppeteer/puppeteer/blob/07febca04b391893cfc872250e4391da142d4fe2/src/common/HTTPRequest.ts#L208

`api.md` makes it sound like it should be public, and I'd like to be able to use it so I can decide whether to act on a request or not, based on its resolution.

**Comment by benallfree** [comment]
Fixed in #7813
