### ISSUE TITLE
Typo in `InterceptResolutionStrategy`

### ISSUE THREAD

**Issue by Tyler-Murphy** [puppeteer/puppeteer#7747]
https://github.com/puppeteer/puppeteer/blob/07febca04b391893cfc872250e4391da142d4fe2/src/common/HTTPRequest.ts#L210

I think it should be `already-handled`.

Because there must be code out there that relies on this typo, I think this'll need to be a major version bump.

**Comment by harshagrawal523** [comment]
I tried changing it , please let me know is this is correct? 

https://github.com/puppeteer/puppeteer/pull/7780

**Comment by benallfree** [comment]
Fix in #7813
