### ISSUE TITLE
[Bug]: Link on the website is broken

### ISSUE THREAD

**Issue by kitarp29** [puppeteer/puppeteer#7751]
### Bug description

Steps to reproduce the problem:

1. Visit [Website](https://puppeteer.github.io/puppeteer/)
2. Just before 'Getting Started' the link in  'Give it a spin: https://try-puppeteer.appspot.com/' does to work.
3. Link redirects to a page with Error 404

### Puppeteer version

latest

### Node.js version

latest

### npm version

latest

### What operating system are you seeing the problem on?

Linux

**Comment by kitarp29** [comment]
@jeresig Please look into it

**Comment by harshagrawal523** [comment]
Hi @kitarp29 ! Can I work on this issue?

**Comment by kitarp29** [comment]
I am also trying to help with this.
Just waiting for getting assigned to this, and some help from the maintainers.
@jeresig @envoked

**Comment by kitarp29** [comment]
ping
