### ISSUE TITLE
[Bug]: unable to link puppeteer

### ISSUE THREAD

**Issue by pawel-id** [puppeteer/puppeteer#7753]
### Bug description

Steps to reproduce the problem:

1. install puppeteer globally `npm install -g puppeteer@11.0.0`
2. create empty node project `npm init --yes`
3. link global puppeteer into the project `npm link puppeteer` fails with an error `sh: husky: command not found`

The error is not happening on previous puppeteer versions.

This kind of setup we are using to have single global puppeteer within docker and few node projects reusing the global puppeteer to keep docker image reasonably small size.

### Puppeteer version

11.0.0

### Node.js version

v14.17.4

### npm version

7.24.2

### What operating system are you seeing the problem on?

Linux, macOS

### Relevant log output

```shell
npm ERR! code 127
npm ERR! path /Users/pawlik/.nvm/versions/node/v14.17.4/lib/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node typescript-if-required.js && husky install
npm ERR! sh: husky: command not found
```

**Comment by pawel-id** [comment]
I think it is because this https://github.com/puppeteer/puppeteer/pull/7727 adding husky call here https://github.com/puppeteer/puppeteer/blob/v11.0.0/package.json#L20

**Comment by timmhayes** [comment]
@pawel-id I'm having the same issue with a similar workflow. Did you find a way around this?

**Comment by pawel-id** [comment]
@timmhayes  workaround: install husky globally before puppeteer `npm i -g husky`

**Comment by timmhayes** [comment]
@pawel-id Thanks, I'll give that a try.
