### ISSUE TITLE
Keyboard shortcuts don't work on Mac

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#776]
The following script doesn't select text:

```js
const puppeteer = require('puppeteer');
(async () => {
  // Launch headful so that we see what's going on
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  // Add textarea
  await page.setContent('<textarea>hello</textarea>');
  await page.focus('textarea');
  // Try to select all text in textarea
  await page.keyboard.down('Meta');
  await page.keyboard.press('a');
  await page.keyboard.up('Meta');
  // By now, text should be selected in the text area.
  // It doesn't on Mac.
})();
```

First reported in #761.

**Comment by JoelEinbinder** [comment]
The first bug here is that we don't send nativeKeyCodes, so no real OSX events get made. When sending the nativeKeyCodes, "a" is keyCode 0 and protocol decides not to send a falsey keyCode. After these are fixed, OSX doesn't like to perform keyboard shortcuts unless the application has the foreground. And lastly, if Chromium has the foreground, we send the nativeKeyCode, and protocol processes it, the shortcut gets captured by the address bar instead of the page.

**Comment by niftylettuce** [comment]
Also, `page.select` is not a function on Mac (at least from my test).

<https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageselectselector-values>

**Comment by olitaylor** [comment]
I've also found the page.select to not be working on mac 
`page.select is not a function`

**Comment by aslushnikov** [comment]
@niftylettuce @olitaylor `page.select` was added in v0.12 which has not been released yet. You can install from github to dogfood the bleeding edge.

**Comment by focusaurus** [comment]
In light of this bug, is there any working technique or workaround to replace the value in a text input in the current puppeteer release? From the docs it seems like `.select()` is not relevant. I was also trying the "select all then hit Backspace" approach described in this bug and at the moment I can't find a workaround.

**update 2** Based on the other bug, here's my workaround function (should work in input and textarea elements):

```js
async function clear(page, selector) {
  const value = await page.$eval(
    selector,
    el => el.value || el.innerText || ""
  );
  await page.focus(selector);
  for (let i = 0; i < value.length; i++) {
    await page.keyboard.press("Backspace");
  }
}
```

**Comment by aslushnikov** [comment]
@focusaurus you should be able to just assign empty value to the input:

```js
// Clear input with class '.input'
await page.$eval('.input', input => input.value = '');
```

Regarding the bug itself: it turned out that MacOS X has a special handling for shortcuts: in OS X world, the Cmd-A is handled by operating system, not chrome. As a result, it depends on focused application and other factors, and that's why we can't emulate the behavior precisely.

@JoelEinbinder can you please add this to the documentation of the Keyboard namespace? After that, the issue can be closed.

**Comment by focusaurus** [comment]
@aslushnikov ah brilliant! I had keystroke emulation on the brain but that's a great solution.

**Comment by minodisk** [comment]
As [#776 (comment)](https://github.com/GoogleChrome/puppeteer/issues/776#issuecomment-329589760), I tried adding `nativeVirtualKeyCode` [at `send('Input.dispatchEvent')` in `Keyboard.down()`](https://github.com/GoogleChrome/puppeteer/blob/fc2fc0de5d7050437f623f808ddff3488c895b72/lib/Input.js#L51-L62):

```diff
    await this._client.send('Input.dispatchKeyEvent', {
      type: text ? 'keyDown' : 'rawKeyDown',
      modifiers: this._modifiers,
      windowsVirtualKeyCode: description.keyCode,
+     nativeVirtualKeyCode: description.keyCode,
      code: description.code,
      key: description.key,
      text: text,
      unmodifiedText: text,
      autoRepeat,
      location: description.location,
      isKeypad: description.location === 3
    });
```

And shortcuts were executed successfully in OSX with: 

```js
const browser = await puppeteer.launch({
  headless: false                                              // required!
});
const page = await browser.newPage();
await page.bringToFront();                                     // required!
await page.keyboard.press("Meta", {text: "a"}));
```

But this is painful, isn't it? 😭

**Comment by minodisk** [comment]
Yay, I finally sent a pull request 😄

**Comment by ttridon** [comment]
It's still not working on my Mac

const transmission = 'select[name=AutomaticGear]';
  await page.click(transmission);
  await page.keyboard.down('ArrowDown', { delay: 25 });
  await page.keyboard.press('Enter', { delay: 25 });

the select field is opened but the key arrowdown is not executed
