### ISSUE TITLE
[Bug]: Some hyperlinks are unable to be clicked in PDF generated for HTML with multi-line hyperlink

### ISSUE THREAD

**Issue by v-sean** [puppeteer/puppeteer#7769]
### Bug description

When generating a PDF for an HTML with a hyperlink spanning two lines, previous hyperlinks in those lines will be unable to be clicked on in the resulting PDF. Any text in the two lines that are spanned are also clickable to navigate to the multi-lined hyperlink's url.

Steps to reproduce the problem:

1. Create an HTML with a single and multi line hyperlink and save it. For example, `example.html`:
```
<!doctype html>
<html>
<head>
    <title>Example Page</title>
</head>
<body>

<div style="max-width: 500px">
    <a href="https://github.com/">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit, sed do <a
        href="https://www.google.com">eiusmod tempor</a> incididunt ut labore et dolore magna aliqua.
</div>

</body>
</html>
```

2. In the same directory, create a `save_to_pdf.js` with the following contents:
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();
    await page.goto(`file://${__dirname}/example.html`, { waitUntil: 'networkidle0', timeout: 60000 });
    await page.pdf({
        path: 'out.pdf',
        printBackground: true
    });

    await browser.close();
})();
```

3. Run `node save_to_pdf.js`.

4. Open `out.pdf` in any program and try to click on the first hyperlink. The expected result would be to navigate to https://github.com/, but the actual result is that it navigates to https://www.google.com/. In fact, clicking any text on those two lines navigates to https://www.google.com/.

### Puppeteer version

11.0.0

### Node.js version

10.18.1

### npm version

6.13.4

### What operating system are you seeing the problem on?

Windows

**Comment by carstenschwede** [comment]
Can confirm, a multi-line hyperlink will break **all hyperlinks** in the same paragraph by linking the whole paragraph to the multi-lined one. Very annoying.

**Comment by carstenschwede** [comment]
Bump, still valid.

**Comment by neilpelow** [comment]
Seeing the same behaviour in Puppeteer v21.11.0 generated PDFs
