### ISSUE TITLE
[Bug]: Can someone help me with how to create a table of content while creating a pdf? 

### ISSUE THREAD

**Issue by dean-g** [puppeteer/puppeteer#7778]
### Bug description

Can someone help me with how to create a table of content while creating a pdf? 

is there a way I can click the table of content and redirect to the corresponding page using puppeteer? 

### Puppeteer version

9.0.0

### Node.js version

16.13.0

### npm version

6.14.13

### What operating system are you seeing the problem on?

macOS

**Comment by harshagrawal523** [comment]
Hi @dean-g ! Can I work on this issue?

**Comment by dean-g** [comment]
Thanks for responding. 

@harshagrawal523 Can you please give your suggestion on this? do you have any working examples to which I can refer?
