### ISSUE TITLE
[Bug]: Unhandled rejected promises in source/helper.js#getReadableFromProtocolStream causes puppeteer crash

### ISSUE THREAD

**Issue by heragu** [puppeteer/puppeteer#7781]
### Bug description

The error happened in the nodejs AWS lamdba runtime while using headless puppeteer browser to render PDFs. The unhandled rejected promise makes the lambda runtime to crash all together without the possibility of responding in a controlled manner. 

I created [this repository](https://github.com/heragu/unhandled-rejected-promise-causes-puppeteer-crash) with steps to reproduce it together with a proposal on how to resolve it

### Puppeteer version

10.4.0

### Node.js version

v14.17.4

### npm version

6.14.14

### What operating system are you seeing the problem on?

Linux, macOS

### Relevant log output

```shell
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Protocol error (IO.close): Target closed.","trace":["Runtime.UnhandledPromiseRejection: Error: Protocol error (IO.close): Target closed."," at process.<anonymous> (/var/runtime/index.js:35:15)"," at process.emit (events.js:400:28)"," at processPromiseRejections (internal/process/promises.js:245:33)"," at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
```

**Comment by sgronblo** [comment]
We are seeing a similar problem (also in the context of rendering pdfs in Docker in AWS Lambda). The callstack is slightly different.

We are currently using `puppeteer-core` together with `chrome-aws-lambda` after a large amount of trial and error.

Our code is currently starting up a new browser and closing it for each request. We are seeing about a 25% error rate. For example we might see a pattern like SUCCESS, SUCCESS, SUCCESS, ERROR, SUCCESS.

puppeteer-core@10.4.0
not sure how to check which version of Chrome has actually been installed by chrome-aws-lambda.
base image: node:14.18.2-alpine

The exact error we are seeing is:

```
2021-12-10T01:37:35.537Z	9b16ed12-e46f-59f5-abb3-b73e55f1cf41	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Protocol error (IO.close): Target closed.",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Protocol error (IO.close): Target closed.",
        "message": "Protocol error (IO.close): Target closed.",
        "stack": [
            "Error: Protocol error (IO.close): Target closed.",
            "    at /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:217:63",
            "    at new Promise (<anonymous>)",
            "    at CDPSession.send (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:16)",
            "    at Readable.read [as _read] (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/helper.js:281:30)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Protocol error (IO.close): Target closed.",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:400:28)",
        "    at process.emit (domain.js:475:12)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}
```

**Comment by evan-morgan** [comment]
Any update on this? Experiencing the same as sgronblo

**Comment by sgronblo** [comment]
@Signo-Alaris We were able to make it work in the end without too much trickery by using the base node image provided for Lambda by AWS + standard Puppeteer (not puppeteer-chrome) by applying all the flags used by puppeteer-chrome https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.ts#L94
