### ISSUE TITLE
[Bug]: Puppeteer 11 goto PDF not hitting PuppeteerLifeCycleEvents -> timeout

### ISSUE THREAD

**Issue by CComparon** [puppeteer/puppeteer#7783]
### Bug description

Steps to reproduce the problem:

The following code with `"puppeteer": "^11.0.0"` and `"puppeteer-extra": "^3.2.3"` ends up with a timeout exception. Any pdf will do.

```ts
import pupExtra from "puppeteer-extra";
import * as pup from "puppeteer";

const browser = await pupExtra.launch({
  executablePath: "/usr/bin/google-chrome-stable",
  headless: false,
});
const page: pup.Page = await browser.newPage();
const url = "https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/agriculture-and-seafood/animal-and-crops/animal-production/bee-assets/api_fs103.pdf";
await page.goto(url, { waitUntil: ["domcontentloaded", "networkidle2"] });

```
Using Chrome 96.0.4664.45 on Ubuntu 20.10 x64.
Works fine with `"puppeteer": "^10.4.0"`.

Thanks!
Cyril

### Puppeteer version

11.0.0

### Node.js version

v16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Ubuntu 20.04 x64

**Comment by BayanBennett** [comment]
I'm not sure why it worked in 10 and not 11, but this ended up fixing the issue: https://github.com/puppeteer/puppeteer/issues/299#issuecomment-668087154

I think this ticket can be closed.
