### ISSUE TITLE
[Bug]: Calls to `page.mouse.move()` with off-screen arguments hangs indefinitely in Firefox

### ISSUE THREAD

**Issue by trotzig** [puppeteer/puppeteer#7793]
### Bug description

Hi there! We use Puppeteer at happo.io to take screenshots in Firefox. As I was updating some dependencies today I noticed that our Firefox test suite was timing out. It turns out that a call to `page.mouse.move(-100, -100)` was hanging. 

# Steps to reproduce the problem:
I made a reproduction repository with instructions in the readme: 
https://github.com/trotzig/puppeteer-mouse-move-firefox-issue

If you use x and y values that fit inside the viewport, everything works. E.g. `page.mouse.move(10, 10)` works, whereas `page.mouse.move(40000, 40000)` does not.

While I understand that placing the mouse off-screen is somewhat strange (we do it to prevent hover effects in screenshots), the freezing behavior can't be right. I suggest throwing some kind of error instead.

### Puppeteer version

11.0.0

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by taewookim** [comment]
i have the same issue. 
page.mouse.hover / click  all seem to hang. also, page.keyboard.XXX hangs as well

are you using browserless? when I migrated to puppeteer (i.e. no dockerization), the problem goes away

**Comment by trotzig** [comment]
Nope, not using browserless. We are using docker however.

**Comment by taewookim** [comment]
which docker image are u using?

**Comment by trotzig** [comment]
It's a custom one based on `node:14-slim`.

**Comment by taewookim** [comment]
I am not 100% certain but dockerizing seems to alter pupeteer chromium's behavior. According to their [readme](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md):

`Getting headless Chrome up and running in Docker can be tricky. The bundled Chromium that Puppeteer installs is missing the necessary shared library dependencies.
`
we're considering migrating out of any dockerized puppeteers b/c of this issue

**Comment by taewookim** [comment]
one thing you might want to try

 ```
await page.setCacheEnabled(false);
 await page.setBypassCSP(true);
```
