### ISSUE TITLE
Add convenience method for dumping body innerHTML

### ISSUE THREAD

**Issue by s3ththompson** [puppeteer/puppeteer#78]
This library is sweet!

It would be awesome to add a convenience method to dump the innerHTML of the `body` element.

**Comment by aslushnikov** [comment]
Hey Seth!

There's in-flight [pull request](https://github.com/GoogleChrome/puppeteer/pull/75) to introduce `page.$` method. It would allow you to write the following code:

```js
let html = await page.$('body', body => body.innerHTML);
```

Would it be good enough for your?
