### ISSUE TITLE
Firefox: For some sites puppeteer times out on second page.goto

### ISSUE THREAD

**Issue by petervannes** [puppeteer/puppeteer#7809]
### Bug description

Steps to reproduce the problem:

1. Set puppeteer launch properties such that Firefox is the browser

```
let launchProperties = {
		headless: false,
		ignoreHTTPSErrors: true,
		args: ['--no-sandbox', '--disable-setuid-sandbox'],
		product: 'firefox',
	};
```

2. Run the following script

```
	await this.page.goto(this.config.urlBase + '/');
	await this.page.goto(this.config.urlBase + '/fiets/fiets-aankooptips');
	console.log('navigation done');
```

2.  Page navigates to '/' and subsequently '/fiets/fiets-aankooptips'
3.  Second `page.goto` times out though browser has successfully rendered page
     (logging statement is never executed)

4. When running same script with different urls it does not timeout

```
	await this.page.goto('https://www.duckduckgo.com');
	await this.page.goto('https://www.duckduckgo.com/app');
	console.log('navigation done');
```

5. Run the initial script with longer timeout does not resolve the issue

```
	await this.page.goto(this.config.urlBase + '/', { timeout: 60000});
	await this.page.goto(this.config.urlBase + '/fiets/fiets-aankooptips',{ timeout: 60000});
	console.log('navigation done');
```

After loading the second url, no more network activity is registered in the developer network console

Probably related to #5504

### Puppeteer version

11.0.0

### Node.js version

14.18.1

### npm version

6.14.15

### What operating system are you seeing the problem on?

macOS

**Comment by petervannes** [comment]
Also tested with `{ waitUntil: 'load' }` option, to rule out timeout issues.
No luck though

**Comment by gitamineHM** [comment]
hello @petervannes 

can you test this : 

    await page.goto("https://www.google.fr", {
        waitUntil: "networkidle2",
        timeout: 40000,
      });
    }
