### ISSUE TITLE
page.bringToFront() sometimes causes actual browser window to come to front (non-headless, Windows)

### ISSUE THREAD

**Issue by surlyhacker** [puppeteer/puppeteer#7815]
### Bug description

Steps to reproduce the problem:

1. Have code that calls `page.bringToFront()` (in my case in an infinite loop that does other things and also waits for some time)
2. Use Puppeteer on Windows in non-headless mode
3. Witness that sometimes (not always), when `page.bringToFront()` is called, the entire browser window comes to the front (takes focus).  The documentation for this method says "Brings page to front (activates tab)".  So it doesn't say anything about the browser window focus changing.

I don't know if it's relevant, but I am running this code from within VS Code in the debugger (running Node).
I have no idea what the circumstances are that result in this call bringing the browser to the front vs not.  As far as I can see, there is no difference in code execution path between times when it happens and times when it does not.  

Also may be noteworthy that I am using `puppeteer.connect()` in the relevant code to connect to one that was `puppeteer.launch()`'ed in another Node process on the same machine.

### Puppeteer version

11.0.0

### Node.js version

v12.16.3

### npm version

6.14.4

### What operating system are you seeing the problem on?

Windows

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.

**Comment by surlyhacker** [comment]
Happens to me in Node 16.13.2 with Puppeteer 13.1.1.

**Comment by pirate** [comment]
This is happening to me on node v22.2.0 with puppeteer v22.10.0. Can it be re-opened @jrandolf?
