### ISSUE TITLE
Constantly getting Navigation Timeout Error

### ISSUE THREAD

**Issue by dustyhorizon** [puppeteer/puppeteer#782]
### Steps to reproduce

* Puppeteer version: 0.10.2
* Platform / OS version: Ubuntu / node v8.5.0
* URLs (if applicable): https://www.883jia.com.sg, https://www.power98.com.sg/

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', (...args) => {
    for (let i = 0; i < args.length; ++i)
    console.log(`${i}: ${args[i]}`);
  });
  page.on('error', err => {
    console.log(err)
  })
  await page.goto('https://www.883jia.com.sg/');
  console.log(page.url());
  browser.close();
})()
```

**What is the expected result?**

Successful logging of page.url() then closure of the instance.

**What happens instead?**

```
0: JQMIGRATE: Migrate is installed, version 1.4.1
Error: Navigation Timeout Exceeded: 30000ms exceeded
```

Not really sure what happened, pretty new to this and all, do let me know what other information is needed. Would suspect that it is due to the JQMIGRATE message from the website though.

**Comment by paambaati** [comment]
The page just seems to be incredibly heavy. It has roughly 135 requests, and a majority of them being large images.

**Comment by kaushiksundar** [comment]
@dustyhorizon 

Pass timeout value in options. You can also use `networkIdleTimout` in case if you have gaps between your requests(ajax)

[Doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options)

```
await page.goto('https://www.883jia.com.sg/', {
                networkIdleTimeout: 5000,
                waitUntil: 'networkidle',
                timeout: 3000000
            });
```

**Comment by aslushnikov** [comment]
`timeout` option should accept the `0` value to disable timeout.
Let me know if anybody is interested in making a PR.

**Comment by sukrosono** [comment]
@aslushnikov did you mean PR to the documentation?

**Comment by aslushnikov** [comment]
@brutalcrozt PR to the codebase, you can't currently pass `timeout: 0` to disable timeout for navigation

**Comment by sukrosono** [comment]
@aslushnikov ok i got it, i might try that, But i really unfamiliar with the codebase, can you give me some direction? Maybe a couple file which involved with that action. :smile:

**Comment by aslushnikov** [comment]
@brutalcrozt: check out the [lib/NavigatorWatcher](https://github.com/GoogleChrome/puppeteer/blob/master/lib/NavigatorWatcher.js) for the actual code. Also, the [Contributing.md](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md) has some tips on how to run and debug tests

**Comment by SashaDesigN** [comment]
`networkIdleTimeout` is no longer supported in Puppeteer 1.8.0
But longer timeout solve my issue, thanks @kaushiksundar

**Comment by whitehorsesoft** [comment]
> @dustyhorizon
> 
> Pass timeout value in options. You can also use `networkIdleTimout` in case if you have gaps between your requests(ajax)
> 
> [Doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options)
> 
> ```
> await page.goto('https://www.883jia.com.sg/', {
>                 networkIdleTimeout: 5000,
>                 waitUntil: 'networkidle',
>                 timeout: 3000000
>             });
> ```

In version 1.11.0, `networkIdleTimeout` is [no longer supported](https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-pagegotourl-options).

However, that being said, adding `timeout` option alone (without `networkIdleTimeout` and without `waitUntil`) alleviated the navigation timeout error for me.

**Comment by proton1k** [comment]
@dustyhorizon  @SashaDesigN @aslushnikov 
I'm handling this by simply `catch`ing the `TimeoutError` and recursively calling same function to reload the page several times before the app crashes. At least I'm able to drop some cases of occasional packets lost for unrecognizable network reasons. But this does not allow to handle specific errors. For example once I had a case with multiple images to be loaded by separate http requests and only one image failed to load (response was not returned) thus throwing 504 timeout.

**Comment by generalsystems** [comment]
To Solve this pass `timeout:0` to the launch method
`const browser = puppeteer.launch({timeout:0})
const page = await browser.newPage();
`
I hope that helps

**Comment by johnwaweru** [comment]
The best solution is to use a `try catch` block to catch the timeout error. If you're in a loop simply use `continue` if you wish to ignore the section you're in. Alternatively, as mentioned somewhere in the thread, you can recursively call the function you were executing but _only for a finite number of times_. 

You can combine this with a healthy amount of a wait period before an error is thrown by using `setDefaultNavigationTimeout`. Here's an example:

```
const page = await browser.newPage();
// set navigation timeout to 4 minutes
await page.setDefaultNavigationTimeout(240000);
await page.goto("http://example.com");
for (let i = 0; i < count; i++) {
  try {
      // execute a block of code here
    } catch (e) {
      // continue with the loop if there's an error
      continue;
  }
}
```
