### ISSUE TITLE
中文api文档里page.emulateMedia没有更新成page.emulateMediaType

### ISSUE THREAD

**Issue by jc1144096387** [puppeteer/puppeteer#7821]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 12.0.1
* Platform / OS version:
* URLs (if applicable):
* Node.js version: 16.6.0

**What steps will reproduce the problem?**
![image](https://user-images.githubusercontent.com/32624612/144532603-2c9fac83-bfaa-4566-be4b-220871881941.png)

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**
![image](https://user-images.githubusercontent.com/32624612/144532518-55179070-7d8e-46f2-899f-f6bb7b033c6c.png)

**Comment by OrKoN** [comment]
This website is provided by this repo https://github.com/zhaoqize/puppeteer-api-zh_CN It's worth opening an issue there. This repo only contains the English version of the API documentation.
