### ISSUE TITLE
Examples: add src2png

### ISSUE THREAD

**Issue by LasaleFamine** [puppeteer/puppeteer#783]
Maybe could be nice to add also https://github.com/mplewis/src2png to the README of the `examples` folder? Maybe under a **Rendering** section?
cc/ @ebidel

**Comment by ebidel** [comment]
I think it makes sense to add resources when we don't provide examples. Or bigger end to end explainers. Since we already have a couple of screenshot examples, I'm inclined to leave this one out.

Pretty cool though!

**Comment by LasaleFamine** [comment]
Ok, actually makes sense to not "overload" the users with multiple examples of the same feature. 
Thanks for the feedback!
