### ISSUE TITLE
[Feature request] allow to destroy all browser targets before close

### ISSUE THREAD

**Issue by Minyar2004** [puppeteer/puppeteer#7831]
### Bug description

There is no way to destroy all targets of a browser before closing it...

Steps to reproduce the problem:

```
browser.on('targetcreated', function (target) {
    console.log(target.type() + ' was created');
});
```

or

`browser.targets()`

puppeteer does not allow to properly manage the targets of a given browser (except of "page" type : target.page().close())

### Puppeteer version

9.1.1

### Node.js version

12.16.1

### npm version

6.13.4

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
FYI you can try using CDP directly to close the target:
- https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-closeTarget 
- https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#class-cdpsession

Feature request is still valid, Puppeteer does not offer a dedicated API for this.

**Comment by Devhercule** [comment]
The idea is to close all targets within a browser not only a target of a page.
In puppeteer, a target can have several types <"page"|"background_page"|"service_worker"|"shared_worker"|"other"|"browser">

**Comment by Devhercule** [comment]
How is it possible to close a target using cdpsession (a cdpsession is attached to a target)

**Comment by Minyar2004** [comment]
`Target.closeTarget` does not obviously work: "targetdestroyed" event is never emitted.

the targetdestroyed event is emitted when I call `page.close()` but not when I use the script below :

A target can be <"page"|"background_page"|"service_worker"|"shared_worker"|"other"|"browser">

```
browser.on('targetcreated', async target => {
    browserTargets.push(target);
});
browser.on('targetdestroyed', async target => {
    browserTargets.splice(browserTargets.findIndex(a => a._targetId === target._targetId) , 1);
});

for (const target of browserTargets) {
    targetClient = await target.createCDPSession();
    await targetClient.send('Target.closeTarget');
}
```

**Comment by Rajkumar0718** [comment]
while i am connect to browser through websocket and i used this method Target.setDiscoverTargets for target creation.sometime it work fine but some time target will destroying why   
it my output                                                                                                                                                            
"{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"128c8ff6-a1bb-46cc-9ef8-7bfe4f737d41","type":"browser","title":"","url":"","attached":true,"canAccessOpener":false}}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"447BC996BD655AC97E844E1791AE9FE9","type":"page","title":"New Tab","url":"chrome://newtab/","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"9805946A029A5789082D5F03F2CB994A","type":"background_page","title":"Google Network Speech","url":"chrome-extension://neajdppkdcdipfabeoofebfddakdcjhd/_generated_background_page.html","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"9BAA60A1DC027766BF111B0C3B56EB26","type":"background_page","title":"Google Hangouts","url":"chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"id":1607898415,"result":{}}
{"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"5734D15CC4C3A01DA62589892C4699F2","type":"iframe","title":"","url":"","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetInfoChanged","params":{"targetInfo":{"targetId":"5734D15CC4C3A01DA62589892C4699F2","type":"iframe","title":"chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=","url":"chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=","attached":false,"canAccessOpener":false,"browserContextId":"E39A3D669A8ED5EF56B7FC943FE1DC71"}}}
{"method":"Target.targetDestroyed","params":{"targetId":"9BAA60A1DC027766BF111B0C3B56EB26"}}
{"method":"Target.targetDestroyed","params":{"targetId":"9805946A029A5789082D5F03F2CB994A"}}
"

**Comment by OrKoN** [comment]
`Target.closeTarget` requires a target ID as a parameter. We are likely not going to support this for all targets: pages can already be closed and now workers can be closed too https://pptr.dev/api/puppeteer.webworker.close/ Since some target types cannot be destroyed in a good way (e.g., iframes or browser) it does not make sense to support it for all targets.
