### ISSUE TITLE
Where to write this code

### ISSUE THREAD

**Issue by karlosRivera** [puppeteer/puppeteer#784]
see the code first

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({path: 'example.png'});

  browser.close();
})();
```

the above code is pure js code ?

where to write this code in browser console or just the run the code when user click on any button of a web page ?

please guide me.

**Comment by vsemozhetbyt** [comment]
@karlosRivera 
You need the last version of [Node.js](https://nodejs.org/en/) installed.
Then you need to install puppeteer: `npm install puppeteer`.
Then you save this code in a file, say, `test.js`.
Then you launch it as `node test.js`.

**Comment by hbakhtiyor** [comment]
in paper

**Comment by eruca** [comment]
I use node 8.5 and puppeteer 0.10.2 url = 'https://github.com', it block at 
```js
await page.screenshot({page:'example.png'})'
```
any reason?

**Comment by vsemozhetbyt** [comment]
@eruca It seems the option [should be `path`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagescreenshotoptions), not `page`:
```js
await page.screenshot({ path: 'example.png' });
```
