### ISSUE TITLE
[Bug]: Missed offset in elementHandler.click

### ISSUE THREAD

**Issue by mnakhaei** [puppeteer/puppeteer#7850]
### Bug description

There is offset parameter in element Handler [click](https://pptr.dev/#?product=Puppeteer&version=v13.0.0&show=api-elementhandleclickoptions) but it missed in ClickOptions.

### Puppeteer version

10.2.0

### Node.js version

v16.5.0

### npm version

8.1.4

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
![Screenshot 2021-12-22 at 08 58 44](https://user-images.githubusercontent.com/399150/147056746-d0a115bc-2ded-49d3-86c3-3286b779c4b7.png)

I see it, do you mean it's missing elsewhere?
