### ISSUE TITLE
[Bug]: stopJSCoverage returns incorrect coverage ranges (does not match Chrome Coverage)

### ISSUE THREAD

**Issue by ethaniel** [puppeteer/puppeteer#7859]
### Bug description

Steps to reproduce the problem:

1. Download .zip file.
2. In the file `puppeteer_coverage.json` find the ranges for the `js.js` file and see how they don't match `chrome_coverage.json` (which was generated by Chrome manually)
3. **If needed:** run `node ./puppeteer.js` to regenerate `puppeteer_coverage.json`.
4. **If needed:** regenerate `chrome_coverage.json` manually from your local Chrome's Coverages tab. Compare the ranges for the `js.js` file.

[bug.zip](https://github.com/puppeteer/puppeteer/files/7740931/bug.zip)

### Explanation

I've just started playing with Puppeteer to automatically generate the Coverage ranges so I could automatically remove unneeded lines in my Javascript (I know, it's a bad idea, but still).
I've noticed that the ranges returned by Puppeteer do not match the ranges returned by Chrome, which results in broken blocks of code.

**Puppeteer ranges:**
![image](https://user-images.githubusercontent.com/941973/146677988-534665be-98a5-4772-878e-1d7bc21fd555.png)

**Chrome ranges:**
![image](https://user-images.githubusercontent.com/941973/146677983-cff3dbeb-1400-47eb-a031-b26552e30a0c.png)

### Puppeteer version

13.0.0

### Node.js version

17.0.1

### npm version

8.1.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
No errors in logs.
```

**Comment by KiranBestie** [comment]
Exported the coverage json of https://armia.com website
Used code shown in the dev tools coverage tab doesn't fall in the range of exported json range.
I'm trying to extract only used code from a file for example; 
https://dlrvetgp71ck5.cloudfront.net/vendor/js/jquery-ui-output.min.js

Due in correct range(start and end values) I couldn't extract them as expected. 

Sample code used;

const puppeteer = require("puppeteer");
const fs = require("fs");
const util = require("util");
const reportJson = require("./Coverage-20220822T155929.json");

const jsCoverage = reportJson.filter(function (item) {
  return item.url.indexOf("jquery-ui-output.min.js") !== -1;
});

console.log(jsCoverage);
let final_css_bytes = "";
let total_bytes = 0;
let used_bytes = 0;

for (const entry of jsCoverage) {
  total_bytes += entry.text.length;
  for (const range of entry.ranges) {
    used_bytes += range.end - range.start - 1;
    final_css_bytes += entry.text.slice(range.start, range.end) + "\n";
  }
}

fs.writeFile("./main.js", final_css_bytes, (error) => {
  if (error) {
    console.log("Error creating file:", error);
  } else {
    console.log("File saved " + total_bytes);
  }
});
