### ISSUE TITLE
Failed to download Chromium r497674!

### ISSUE THREAD

**Issue by Orecic** [puppeteer/puppeteer#786]
hi,
  I am from China ,I can't download Chromium from 'https://storage.googleapis.com/chromium-browser-snapshots/Mac/%d/chrome-mac.zip'. Is there any other source? thank you very much.

**Comment by ebidel** [comment]
You could [download Chrome Canary (official build)](https://www.google.com/chrome/browser/canary.html) and use `executablePath` when calling `page.launch()`. Would that work?

**Comment by Orecic** [comment]
I used proxy，now it works, thank you.

**Comment by yzhang-gh** [comment]
@Orecic Could you please tell me how to use proxy within cmd or PowerShell?
I used a PAC but it seems that PowerShell won't use that configuration.
