### ISSUE TITLE
remove `isNode` check from `getReadableFromProtocolStream` and other similar usages

### ISSUE THREAD

**Issue by tiholic** [puppeteer/puppeteer#7861]
as the PR is now landed: https://github.com/nodejs/node/pull/39062 (https://github.com/nodejs/node/pull/39062#issuecomment-871685340)
https://github.com/puppeteer/puppeteer/blob/5b792de7a97611441777d1ac99cb95516301d7dc/src/common/helper.ts#L345-L353

**Comment by OrKoN** [comment]
I believe this has happened.
