### ISSUE TITLE
[Bug]: Headless mode hangs indefinetly on Browser#newPage()

### ISSUE THREAD

**Issue by asciidude** [puppeteer/puppeteer#7867]
### Bug description

Steps to reproduce the problem:

1. Create a browser variable - `const browser = await puppeteer.launch({ headless: true });`
2. Create a new page with that browser variable - `const page = await browser.newPage();`

### Puppeteer version

13.0.1

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
I am unable to reproduce. `await browser.newPage()` resolves successfully. Do you call `browser.close()` from your script to shutdown the headless browser? If you don't close the browser the node script will continue waiting for the browser to close even if the entire script has been executed.

**Comment by asciidude** [comment]
> I am unable to reproduce. `await browser.newPage()` resolves successfully. Do you call `browser.close()` from your script to shutdown the headless browser? If you don't close the browser the node script will continue waiting for the browser to close even if the entire script has been executed.

I made sure to close the browser at the end of the script, perhaps I will just have to deal with non-headless mode.

**Comment by CodyEakins** [comment]
I've encountered this issue when running Puppeteer with Lambda, inside a container.
The first invocation of the Lambda fails; it hangs indefinitely (until the Lambda's timeout is reached) when either `browser.newPage()` or `browser.pages()` is called. However, every subsequent invocation runs without issue if the Lambda is still "hot".

In this environment, calling `browser.launch()` and `browser.close()` does not cause any hang ups. I always tear down the browser before the script ends.

Maybe it's related?
