### ISSUE TITLE
AssertionError [ERR_ASSERTION]: `true` is expected, but it is `false`

### ISSUE THREAD

**Issue by Junkern** [puppeteer/puppeteer#787]
Sometimes I am getting this error: 
```js
{
"generatedMessage":false,
"name":"AssertionError[ERR_ASSERTION]",
"code":"ERR_ASSERTION",
"actual":false,
"expected":true,
"operator":"=="
}
```
I am using puppeteer in version 0.10.2.

I am running my puppeteer web-scraping script in a docker container, and when I execute the container locally on my computer, it runs just fines. However, when the container is deployed to e.g. AWS, it repeatedly throws the above error.

My assumption is, that somehow my connection is being lost/resetted and that I run in either https://github.com/GoogleChrome/puppeteer/blob/42fa3af659f0b9a9931a2e8d4098918e05f9174e/lib/Connection.js#L94 or https://github.com/GoogleChrome/puppeteer/blob/42fa3af659f0b9a9931a2e8d4098918e05f9174e/lib/Connection.js#L198 (Other web scraping scripts run just fine, it's just one which produces the error. That's why I am assuming the connection to the website is weird)

Is it possible to give all `console.assert()` a error message so I can trace the errors better? All other `console.assert` have error messages attached to them.

Or is my issue something totally different?

**Comment by aslushnikov** [comment]
Usually assertion errors come with stack traces that you should be able to get.

Other then that, feel free to send a PR that adds messages to the assertions, I'd be happy to review!
