### ISSUE TITLE
Why Puppeteer v13 is missing from "versions.js" ?

### ISSUE THREAD

**Issue by RopoMen** [puppeteer/puppeteer#7870]
### Bug description

Hi, 

I noticed that Puppeteer v13 is missing from `https://github.com/puppeteer/puppeteer/blob/main/versions.js` is this intentional? I checked that in v12 release that version.js contained Puppeteer v12.

### Puppeteer version

13

### Node.js version

-

### npm version

-

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
I think there were no Chromium rolls included in v13 and therefore it's not listed in versions.js.

**Comment by mathiasbynens** [comment]
Correct.
