### ISSUE TITLE
[Bug]: Failed to capture background image in screenshot

### ISSUE THREAD

**Issue by yxiong20** [puppeteer/puppeteer#7871]
### Bug description

Steps to reproduce the problem:

1. Use website: https://www.kathabineider.de/
2. Use the usual puppeteer js script, try capture the screenshot of the page, not the background image failed to be captured. I tried a few things:
 - put a delay(2s, 5s, 10s etc) after loading the page before taking screenshot
 - force scroll to the end, load all img from the DOM 
 none of those worked
 3. The usual script works fine for many other sites I tried, just not working for this site
 
 What could be the problem? 

### Puppeteer version

12.0.1

### Node.js version

17.0.1

### npm version

8.1.0

### What operating system are you seeing the problem on?

macOS

**Comment by phanikumar1** [comment]
We had similar experience with a different website. I had to change captureBeyondViewport to false for it to work. 

return await this.page.screenshot({
        type: this.IMAGE_FORMAT,
        encoding: 'base64',
        captureBeyondViewport : false
      // this option is hanging the api for some websites
      });

**Comment by yxiong20** [comment]
Unfortunately this option does not help with this website.

**Comment by yxiong20** [comment]
This might be due to WebGL content on the page, similar to https://github.com/puppeteer/puppeteer/issues/5961.
