### ISSUE TITLE
[Bug]: Puppeteer gives error that Error: Failed to launch the browser process! when the user profile path is given

### ISSUE THREAD

**Issue by kartik30369** [puppeteer/puppeteer#7875]
### Bug description

Steps to reproduce the problem:

1. Copy paste the code but replace the user profile path.

I am getting the browser launch failure because I am loading my user profile from a file path. Can someone tell me how to fix this and why am i getting this error?

Here's the code:
This code gives me the error:

```
const puppeteer = require('puppeteer');



async function start() {
    const browser = await puppeteer.launch({
        headless: false,
        executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
        args: ['--start-maximized', '--user-data-dir=C:\\Users\\anirudha tiwari\\AppData\\Local\\Google\\Chrome\\User Data\\'
        ]
        //ignoreDefaultArgs: ['--disable-extensions'] 
    });

    const page = await browser.newPage();
    await page.setViewport({
        width: 0,
        height: 0
    });
    
    await page.goto('https://www.webnovel.com/', { "waitUntil": "networkidle0" });
   
};
}


start();
```

But if u comment the user profile path the code runs fine.

By the way, when I tried the second code snippet the browser opened with the specified profile but it didn't go to the page specified which would be 'www.webnovel.com'. Is there a problem with files in the specified path?. If so how do I fix my google profile files? Thanks in advance.

### Puppeteer version

13.0.1

### Node.js version

16.13.0

### npm version

8.1

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
here is the error:

node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:229
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
```

**Comment by rockgabi** [comment]
Did you find a solution for this? having the same problem

**Comment by zeeskhan1990** [comment]
I was having the same issue today. Didn't really got to know why, but I copied all of User Data directory to another folder and then pointed the `--user-data-dir` to that new folder and it's working now

**Comment by sun-m00n** [comment]
Same issue here
needed help

**Comment by sun-m00n** [comment]
Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\Users\it\Desktop\nodejs PROJECTs\src\fake usr in yt v2\production_v3\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:290:20)       
    at ChildProcess.<anonymous> (C:\Users\it\Desktop\nodejs PROJECTs\src\fake usr in yt v2\production_v3\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:281:24)
    at ChildProcess.emit (node:events:525:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by DevShoesed** [comment]
I have the same problem, if i remove `userDataDir` it works but in `Person 1` profile and not with specific profile.

Failed to launch the browser process!
`
      {
       executablePath: '/Program Files/Google/Chrome/Application/chrome.exe',
      userDataDir: '/Users/XXXXX/AppData/Local/Google/Chrome/User Data',
      args: [ '--profile-directory=Profile 6', '--ignore-certificate-errors' ]
      }
`

**Comment by OrKoN** [comment]
Please report the issue upstream to crbug.com if the browser does not start with custom arguments. Not much we can do in Puppeteer.

**Comment by samalyxx** [comment]
I have the same issue I can't run the puppeteer within my existing chrome profile ..
```js
(async () => {
  const browser = await puppeteer.launch({
    executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe",
    headless: false,
    args: [ '--user-data-dir=C:/Users/acer/AppData/Local/Google/Chrome/User Data/','--profile-directory=Default', '--ignore-certificate-errors',"--disabled-setupid-sandbox"],
  });
  const page = (await browser.pages())[0];;

  await page.goto("https://developer.chrome.com/");

  await browser.close();
})();```

**Comment by thurdev** [comment]
> I was having the same issue today. Haven't really come to understand why, but I copied all of User Data directory to another folder in a different drive and then pointed the `--user-data-dir` to that new folder and it's working now

If someone still have the same issue, just do what @zeeskhan1990 said.

At least for me it worked, thanks 👍

**Comment by guizsantos** [comment]
Same here. However, the following workaround did not help too.

> > I was having the same issue today. Haven't really come to understand why, but I copied all of User Data directory to another folder in a different drive and then pointed the `--user-data-dir` to that new folder and it's working now
> 
> If someone still have the same issue, just do what @zeeskhan1990 said.
> 
> At least for me it worked, thanks 👍

Also tried downgrading puppeter, also did not help.

**Comment by miksch123** [comment]
System processes through gitlab run into the issue that they have no access to other paths like the install paths of browsers. this affects all browsers.
