### ISSUE TITLE
Passing RegExp objects as params to evaluate method destroy the regex object (empty)

### ISSUE THREAD

**Issue by xprudhomme** [puppeteer/puppeteer#788]
** Environment:**

Puppeteer version: v0.10.1
Node version: v8.4.0
Platform / OS version: Ubuntu 14.04

**Problem**

Whenever I want to pass RegExp objects as parameters to evaluate functions, it looks like the object being actually passed result in an empty object (it's no more a RegExp).

**Code example to reproduce the error**
```
async testRgx(rgx) {

        console.log("Testing regex constructor : " + rgx.constructor.name);
        console.log("Testing regex : " + rgx.test("com/in/megwhitman/"));
        console.log("Testing regex properties: " + Object.getOwnPropertyNames(Object(rgx)));

        await page.evaluate( rgx => {

          console.log(" [In evaluate] Testing regex constructor : " + rgx.constructor.name);
          console.log(" [In evaluate] Testing regex : " + rgx.test("com/in/megwhitman/"));
          console.log(" [In evaluate] Testing regex properties: " + Object.getOwnPropertyNames(Object(rgx)));

        }, rgx);

}

// Run the following:
testRgx(/com\/in\/(.+)/i)
```

**Results**

Testing regex constructor : RegExp
Testing regex : true
Testing regex properties: lastIndex
PAGE LOG:  [In evaluate] Testing regex constructor : Object

(node:20737) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Evaluation failed: TypeError: rgx.test is not a function    at rgx (<anonymous>:4:63)    at <anonymous>:7:11

(node:20737) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

As we can see, there is no doubt that the _rawEvaluate method from the Frame object somehow modify the RegExp object when passing it as an argument...

Maybe the answer is here ?
```
const { exceptionDetails, result: remoteObject } = await this._client.send('Runtime.callFunctionOn', {
      functionDeclaration: pageFunction.toString(),
      executionContextId: this._defaultContextId,
      arguments: args.map(convertArgument.bind(this)),
      returnByValue: false,
      awaitPromise: true
    });
```
Or here?
```
function convertArgument(arg) {
      if (Object.is(arg, -0))
        return { unserializableValue: '-0' };
      if (Object.is(arg, Infinity))
        return { unserializableValue: 'Infinity' };
      if (Object.is(arg, -Infinity))
        return { unserializableValue: '-Infinity' };
      if (Object.is(arg, NaN))
        return { unserializableValue: 'NaN' };
      if (arg instanceof ElementHandle) {
        if (arg._frame !== this)
          throw new Error('ElementHandles passed as arguments should belong to the frame that does evaluation');
        const objectId = arg._remoteObjectId();
        if (!objectId)
          throw new Error('ElementHandle is disposed!');
        return { objectId };
      }
      return { value: arg };
    }
```

**Comment by vsemozhetbyt** [comment]
@Xavatar [According to the doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args), parameters should be serializable, i.e. [JSON-able](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description). `RegExp` cannot be saved and restored by `JSON`:
```js
> JSON.stringify(/\w/g)
'{}'
```
You may pass `regexp.source` and `regexp.flags` and recreate `RegExp` in the browser context:

```js
async function testRgx(rgx) {
  await page.evaluate((source, flags) => {
    const re2 = RegExp(source, flags);
  }, rgx.source, rgx.flags);
}
```

**Comment by xprudhomme** [comment]
Thanks @vsemozhetbyt , you are right, unfortunately for me.. But that would do the job anyway : )
