### ISSUE TITLE
[Bug]: 当我监听 targetcreated 时,我应该如何获取targetcreated窗口里request请求或者是response请求

### ISSUE THREAD

**Issue by Liuyilin-ai** [puppeteer/puppeteer#7884]
### Bug description

Steps to reproduce the problem:

1. …
How do I get request or Response requests in the TargetCreated window when I'm listening to targetCreated  
2...
When I do this, the system prompts me
node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPResponse.js:129
                        throw new Errors_js_1.ProtocolError('Could not load body for this request. This might happen if the request is a preflight request.');

3. this is my code
            context.on("targetcreated", async (target) => {
                const newPagePromise = new Promise(x => x(target.page()));
                await newPagePromise.on('response',async (login_msg)=>{
                    if (login_msg.url()===''){
                        const login_body = await login_msg.text()
                        console.log(login_body)
                    }else {
                        console.log(login_msg.url())
                    }
                })

### Puppeteer version

13.0.0

### Node.js version

v16.13.1

### npm version

...

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
throw new Errors_js_1.ProtocolError('Could not load body for this request. This might happen if the request is a preflight request.');
                              ^

ProtocolError: Could not load body for this request. This might happen if the request is a preflight request.
    at F:\project\tlm-cluster\node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPResponse.js:129:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTTPResponse.text (F:\project\tlm-cluster\node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPResponse.js:141:25)
    at async F:\project\tlm-cluster\main.js:228:52
```

**Comment by andreizet** [comment]
ran into the same issue these days. I've managed to get it working using the `--disable-web-security` flag.

**Comment by MarkusPint** [comment]
Seeing same issue. @andreizet suggestion didnt work. Version 13.3.2

**Comment by zionpapa0131** [comment]
Is there a solution to this problem yet?
The same problem is in the 13.5.1 version.

**Comment by dcrystalj** [comment]
looks like this has nothing to do with version. tried puppeteer v12.0.1 and didn't work as well.

**Comment by freecorvette** [comment]
I'm getting these as well. Version 13.3.2.

```
[path-to-app]/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:129
                        throw new Errors_js_1.ProtocolError('Could not load body for this request. This might happen if the request is a preflight request.');
                              ^

ProtocolError: Could not load body for this request. This might happen if the request is a preflight request.
    at /home/nodejs/apps/licenseguard/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:129:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  originalMessage: ''
}
```

**Comment by redii** [comment]
I have the same issue on macOS with node v16.15.1 and puppeteer v15.3.0...

when I try to submit a login form he send out 3 requests and I guess on the last one I get the same error:

```
/Users/akmann/dev/icann_download/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:148
                        throw new Errors_js_1.ProtocolError('Could not load body for this request. This might happen if the request is a preflight request.');
                              ^

ProtocolError: Could not load body for this request. This might happen if the request is a preflight request.
    at /Users/akmann/dev/icann_download/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:148:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTTPResponse.text (/Users/akmann/dev/icann_download/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:160:25)
    at async HTTPResponse.json (/Users/akmann/dev/icann_download/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:173:25)
    at async /Users/akmann/dev/icann_download/index.js:8:30 {
  originalMessage: ''
}
```

I already tried to set the following args: 
```
args: [
   "--disable-web-security",
   "--disable-features=IsolateOrigins",
   "--disable-site-isolation-trials",
],
```

**Comment by gbanusi** [comment]
I had the same problem, my seems like it is a chrome problem (https://stackoverflow.com/questions/38924798/chrome-dev-tools-fails-to-show-response-even-the-content-returned-has-header-con), where it redirects before providing body of the request to third party libs? I managed it so that every redirect is waiting 1 second before triggered again... After that every body is loaded.

This is how I overcome the problem:
      
      page.on('request', req => {
            if (req.isNavigationRequest()
                && req.frame() === page.mainFrame()
                && req.url().startsWith(this.clientUrl)
                && !req.url().includes('cdn-cgi')
                && !set.has(req.url())) {
                req.abort('aborted');
                set.add(req.url());
                new Promise(resolve => {
                    setTimeout(resolve, 1000);
                }).then(() => {
                    page.goto(req.url());
                });
            } else {
                set.delete(req.url());
                req.continue()
            }
        })

**Comment by anniechnn** [comment]
I've also been having the same issue on macOS don't know why it's happening so inconsistently. The preflight error shows up sometimes, while other times the code works perfectly without any errors. I'm on Puppeteer 15.2.0 and npm 8.5.5

**Comment by e-onux** [comment]
I'm getting this error with Puppeteer 19.1.0.
`/home/user/projectfolder/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPResponse.js:148
                        throw new Errors_js_1.ProtocolError('Could not load body for this request. This might happen if the request is a preflight request.');
                              ^

ProtocolError: Could not load body for this request. This might happen if the request is a preflight request.
    at /home/user/projectfolder/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPResponse.js:148:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by OrKoN** [comment]
Please reopen as a new issue with an executable repro script using the latest version and please translate into English.
