### ISSUE TITLE
[Bug]: Clipboard Access not working in headless mode

### ISSUE THREAD

**Issue by vezaynk** [puppeteer/puppeteer#7888]
### Bug description

Steps to reproduce the problem:

Code snippet:

```js
const browser = puppeteer.launch({ headless: true });
const page = browser.then((browser) => browser.newPage());
const blank = page.then((page) => page.goto("https://example.com"));
const context = browser.then((browser) => browser.defaultBrowserContext())
.then((context) =>
  context.overridePermissions("https://example.com", ["clipboard-read"])
);

await blank;
await context;
await page
    .evaluate(() => navigator.clipboard.readText())
    .then((a) => console.log(a));
```

Run the code snippet with `headless: false`, it outputs your clipboard. run with `headless: true` and it outputs an empty line.

### Puppeteer version

Latest

### Node.js version

Latest

### npm version

Latest

### What operating system are you seeing the problem on?

Windows

Still an issue btw

**Comment by elen-ita** [comment]
I have also encountered this issue. (I am running on mac)

**Comment by mai0li** [comment]
Have you tried reloading page after overriding permissions?

**Comment by AndrewPahomovOtto** [comment]
> Have you tried reloading page after overriding permissions?

Yep, but not work. 

os: macOS Monterey v12.0.1 M1
puppeteer: v13.5.2

when I create the default or incognito context, the browser has `clipboard-write: granted`, `clipboard-read: prompt`
after I `overridePermissions`, `clipboard-write`, `clipboard-read` or both, I have both permissions for the clipboard `denied`

headless and with the head

**Comment by vezaynk** [comment]
This is still an issue

**Comment by vezaynk** [comment]
Reopen pls?

**Comment by vezaynk** [comment]
Opened a "new" issue: #8692 because stalebot is broken and stupid, or dare I say, [harmful?](https://drewdevault.com/2021/10/26/stalebot.html)
