### ISSUE TITLE
[Bug]: To give an extension access to this site Click it

### ISSUE THREAD

**Issue by saas-developer** [puppeteer/puppeteer#7889]
### Bug description

Test code is available at https://github.com/s16h/puppeteer-tab-capture-repro

1. Run the repo.
2. Try the code from the docs under `Working with Chrome Extensions` -> https://pptr.dev/#?product=Puppeteer&version=v13.0.1&show=api-working-with-chrome-extensions
3. BUG: No background page targets are returned

What is happening?

Background page is only returned after clicking the extension. Look at the screenshot below:
![click-extension-access](https://user-images.githubusercontent.com/58209961/147990478-6e8a553d-2210-44d6-96a9-44ba79c66477.png)

### Expectation
Since extension was whitelisted, it should be automatically enabled and have access to all sites.

### Puppeteer version

13

### Node.js version

14

### npm version

6.14.7

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
No log available as background_page is not available.
```

**Comment by tanchekwei** [comment]
I am also facing this issue after update to puppeteer version 14.1.0 .

The previous puppeteer version I used was 1.11.0, which able to get target background_page.

**Comment by OrKoN** [comment]
I think it's basically the same issue as the feature request https://github.com/puppeteer/puppeteer/issues/5001 The extension testing/debugging story is not great currently.
