### ISSUE TITLE
[Question] Handling iFrames better

### ISSUE THREAD

**Issue by TotusSomnium** [puppeteer/puppeteer#789]
Just beginning to look at puppeteer, but am currently using phantomjs for automated testing. The main question I have is how to switch to a frame. So phantomjs has a switchToFrame() method, is there anything similar to that in puppeteer that I'm missing? Basically the site I test is built with iframes and 3 or 4 can be stacked on top of each other, terrible, I know. However, phantomjs has made it easy to switch between them with that method. Currently with puppeteer, I figured out I could interact with a frame like so: 

```javascript
var selectorID = '#btnSave';  
var frames = await page.frames();  
var myframe = await frames.find(f => f.name() === "Frame Name");  
const iFrame= await myframe.$(selectorID);  
await myframe.evaluate(`$("${selectorID}").text()`)
    .then(function (resp) {  
        tempValue = resp;  
        console.log(`It worked: ${tempValue}`)  
    }).catch(function (error) {  
        console.log(`FAIL Get text from ${selectorID}'s  : ${error}`);  
    });
```  

What i would like to do is something like: 
```javascript
await page.switchToFrame("Frame Name");
```

And then be able to do something like:
```javascript
await page.evaluate(`$("${selectorID}").text()`)
      .then(function (resp) {
        tempValue = resp;
      }).catch(function (error) {
        console.log(`FAIL Get text from ${selectorID}'s  : ${error}`);  
      });
```

And it would perform that on the frame we selected with the new `page.switchToFrame()` method. 

Is this possible? I would imagine anyone that uses phantomJS or casperJS and has frames on their webpage is going to be wondering this as well if they are planning to switch to puppeteer. Any help is greatly appreciated.

**Comment by aslushnikov** [comment]
@TotusSomnium Do you lack some capabilities with Puppeteer's API, or you just find the `switchToFrame` api more pleasant?

**Comment by TotusSomnium** [comment]
@aslushnikov I don't think I'm necessarily lacking any capabilities, but I haven't dug very deep yet. I think its much more pleasant to write blocks of code without passing frame back and forth all the time between functions. If something like `switchToFrame()` existed, it just makes things cleaner in my opinion. From most of the tools I've used (selenium, casperJS, sahi) they all have this functionality, which doesn't mean its right, just easy to use.

**Comment by aslushnikov** [comment]
@TotusSomnium I see. We want Puppeteer API to be lean, so we don't want to have both `switchToFrame` method and frames API.

The good thing is, the `switchToFrame` functionality is implementable atop of our current API, so you can have a shim for yourself if there's a need to.
