### ISSUE TITLE
[Bug]: headless_shell takes 100% CPU on start-up (loop or race condition?) in 96 (94 is OK)

### ISSUE THREAD

**Issue by assen-totin** [puppeteer/puppeteer#7892]
### Bug description

Steps to reproduce the problem:

1. We run Chromium headless on RHEL-8 virtual machines.
2. We start Chromium from NodeJS code in a very standard way, by calling puppeteer.launch() with an empty config (all defaults). The main purpose of Chromium is to print PDF files.
2. The NodeJS service is started by systemd as a "simple" unit (again, pretty straightforward). 
2. We use the EPEL RPM packages for Chromium and Driver. While we were on v. 94, everything was fine.
3. Once we upgraded to v. 96, headless_shell started taking 100% of one CPU core on each boot - and stays there forever even when the system is completely idle. On v. 94, the load average was close to 0 when the system was idle. This upgrade did not touch the puppeteer version, only the Chromium/Driver ones.

Inspecting the process list, it seems that two particular instances of the headless_shell get locked: 
- The one that is started with --type=renderer 
- The one that is stared without the --type option (but has --disable-background-networking and many other options) - likely the "main" process?

It does seem that these two somehow get interlocked, possibly by some race condition. This could explain the fact that occasionally (after manual restart of the whole app) they would start normally - but in more than 50% of the cases they would get interlocked at 100% of one CPU core.

A downgrade to 0.94 resolved the issue, so this is likely something in either Chromium or Chromedriver. However, since this only happens when running it headless, we decided to open the ticket with you. 

### Puppeteer version

2.0.0

### Node.js version

10.x

### npm version

6.14

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
No log output to show - two headless_shell process get stuck on the same core, consuming it on 100%.  The processes look like these two:

/usr/lib64/chromium-browser/headless_shell --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_profile-gtsWDI

/usr/lib64/chromium-browser/headless_shell --type=renderer --headless --lang=en-US --disable-dev-shm-usage --disable-background-timer-throttling --disable-breakpad --enable-automation --force-color-profile=srgb --remote-debugging-port=0 --allow-pre-commit-input --ozone-platform=headless --field-trial-handle=2872467996602483998,1561577570800212603,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=BlinkGenPropertyTrees,PaintHolding,TranslateUI --lang=en-US --num-raster-threads=1 --renderer-client-id=2 --shared-files=v8_snapshot_data:100
```

**Comment by kelp404** [comment]
Do we have a solution to lock Chromium version?
I got issues after auto-upgrade of Chromium a lot of times.
