### ISSUE TITLE
[Bug]: Puppeter very slow when converting html to pdf

### ISSUE THREAD

**Issue by Richacinas** [puppeteer/puppeteer#7897]
### Bug description

Having a bit html which results in 50-60 pages pdf, my puppeteer takes more than 20 seconds to convert it to pdf (`page.pdf`).

Here are my args:

```
'--no-sandbox',
'--disable-setuid-sandbox',
'--disable-dev-shm-usage',
'--hide-scrollbars',
'--disable-gpu',
'--full-memory-crash-report',
'--mute-audio',
"--proxy-server='direct://'",
'--proxy-bypass-list=*'
```

What could be the problem? Is there any issue with fonts, images, or anything like that that could be slowing down the process?

Thanks a lot

### Puppeteer version

13.0.1

### Node.js version

14.16.0

### npm version

6.14.11

### What operating system are you seeing the problem on?

Linux

**Comment by Richacinas** [comment]
I noticed that the parts of my html that make Puppeteer take a very long time are `table`.

So, it looks like Puppeteer is slow rendering this kind of element?

**Comment by Richacinas** [comment]
They are really long `table`s, so maybe the problem is that Puppeteer just cant make it faster when there is so much html to render?

**Comment by Richacinas** [comment]
After a lot of testing, I can't manage to bring the generation time down, so I'm assuming that Puppeteer just can't handle very well a few pages of pdf.

I will try finding another libraries or options to generate our pdfs.

**Comment by akitaTian** [comment]
Do you have any progress?

**Comment by Richacinas** [comment]
> akitaTian

None at all. I managed to bring down the html generation time. That is, the execution of my spa in the browser.

After that, when I use `page.pdf`, it takes about 15 seconds to finish a 65 page document. I think it is insane, however, if I try to do `CTRL+P` on my Chrome browser, it takes about the same time to give me the preview so I assumed that this is as far as we can go with Chrome/Puppeteer.

I'm sure there is some CSS that is making this process slower, maybe the `tables` (I have 18 on this document).

**Comment by akitaTian** [comment]
My html document is about 600 pages,  it takes about 40 seconds by chrome browser or firefox browser
. Maybe i should find another way to convert.  Thanks for your work. -.-

**Comment by Richacinas** [comment]
I've read on many places about converting to pdf using page ranges, and then using another library/tool to merge the pages. That could bring down your time.

Before puppeteer, we used wkhtmltopdf and it was quite faster. However, you'll have to do css adjustments as it doesn't run a Chromium browser under the hood. It runs QTBrowser.

Check it out.

**Comment by akitaTian** [comment]
Thanks for you answer!   i used wkhtmltopdf like this
```
time wkhtmltopdf  --enable-local-file-access  ~/Desktop/some.html  ~/Desktop/some.pdf
```
My html document needs  access to some css and js,. The result is also slow, and takes about 90 sec for the same page numbers。 

if don‘t load js and css files, it only takes about 10 seconds 

------------ long time

There is a text-rendering property in my css file、 I changed the  value from optimizeLegibility to optimizeSpeed、 
Conversion times are greatly improved、 about 19 seconds.  wkhtmltopdf is quite faster.

**Comment by micstem** [comment]
Regarding performance I have created the following Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1277420

Long story short, performance implodes when using header/footer and the page has high memory usage.

**Comment by hjardines** [comment]
They just lowered the priority, sad news. This is important and is a major feature in all Chrome browsers.

https://bugs.chromium.org/p/chromium/issues/detail?id=1277420

**Comment by ViniciusCestarii** [comment]
I'm using Puppeteer to create PDFs as well, and I noticed a significant difference in generation time depending on the content. In my case, having an <img> element in both the header and footer increased the time to generate a 32-page PDF (containing table) from 1.32 seconds to 9.59 seconds. Removing these images dramatically improved the performance.

I will try svg instead of img

**Comment by ViniciusCestarii** [comment]
Update: i tried with svgs and its much faster! from 9.59 seconds to 1.93seconds

**Comment by nstdspace** [comment]
In my case, puppeteer in docker takes about 1 second to render a blank page without any content. It quickly becomes a few seconds when a few simple html elements are added...

**Comment by ndbrgleo** [comment]
I'm suffering from timeouts, on dev testing the 53 oages take like 5 sec, in production live, well... nothing
