### ISSUE TITLE
Can puppeteer run in a client side environment?

### ISSUE THREAD

**Issue by umaar** [puppeteer/puppeteer#790]
Since a client side web page can communicate over WebSockets, which is also what the DevTools protocol uses, is it possible to control a remote browser, via Puppeteer, from a client side web page?

**Comment by aslushnikov** [comment]
@umaar I don't see any immediate road blockers for this. Certain features won't work, like those requiring `fs` module, but should be feasible overall.

**Comment by sun293529884** [comment]
ERROR in ./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Error: Can't resolve 'ws' in 'C:\CIO_Workspace\PPDEMO\Puppeteer-DEMO\node_modules\puppeteer\lib'
 @ ./node_modules/puppeteer/lib/WebSocketTransport.js 16:18-31
 @ ./node_modules/puppeteer/lib/Launcher.js
 @ ./node_modules/puppeteer/lib/Puppeteer.js
 @ ./node_modules/puppeteer/index.js
 @ ./src/app/main.ts
