### ISSUE TITLE
[Bug]: Puppeter with Firefox works locally on Windows, but doesnt work on docker container.

### ISSUE THREAD

**Issue by guilhermebentomarques** [puppeteer/puppeteer#7901]
### Bug description

I have a project that runs nodejs locally on windows without problem. The firefox is downloaded automatically from npm install puppeteer@latest in the node_modules/puppeteer/.local-firefox

```
const puppeteer = require('puppeteer');  
    const browser = await puppeteer.launch({
            product: 'firefox',
            headless: true,
            defaultViewport: {
                width: 3544,
                height: 3544,
            },
        });
```

The problem is when I try to do the same on docker.

```
    const puppeteer = require('puppeteer');
    
    const browser = await puppeteer.launch({
          product: 'firefox',
          headless: true,
          defaultViewport: {
            width: pageSizePx.width,
            height: pageSizePx.height,
          },
        });
```

Docker File

```
# base image
FROM node:12.15-alpine

# ENV CHROME_BIN="/usr/bin/chromium-browser"\
#     PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
########## 
## Update and Install packages
##########
RUN set -x \
    && apk update \
    && apk upgrade \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    # add the packages
    ## g++: used to install NodeJS related packages
    ## chromium: used to run Puppeteer
    && apk add --no-cache g++ firefox 

WORKDIR /scripts
WORKDIR /app

RUN apk add --no-cache curl bash
#RUN npm install -g ts

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
```

And That's the result on docker linux.

![image](https://user-images.githubusercontent.com/10928446/149581754-1011ed87-310d-4338-a005-0cab3b597e2e.png)

The installation is normal, the firefox is there in the same place. node_modules/puppeteer/.local-firefox

### Puppeteer version

13.0.1

### Node.js version

12.15.0

### npm version

6.13.14

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
[20:27:27 error] Failed to launch the browser process! spawn /app/node_modules/puppeteer/.local-firefox/linux-98.0a1/firefox/firefox ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

**Comment by sbland** [comment]
I have been working getting a docker container working today. The following docker file and nodejs setup worked for me.

dockerfile
```dockerfile

FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN apk update && apk add --no-cache nmap && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache \
    chromium \
    harfbuzz \
    "freetype>2.8" \
    ttf-freefont \
    nss

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

```

run.js
```js
(async () => {
  const browser = await puppeteer.launch({
    executablePath: "/usr/bin/chromium-browser",
    headless: true,
    args: ["--disable-dev-shm-usage", "--no-sandbox", "--disable-gpu"],
  });
})();

```

**Comment by guilhermebentomarques** [comment]
> I have been working getting a docker container working today. The following docker file and nodejs setup worked for me.
> 
> 
> 
> dockerfile
> 
> ```dockerfile
> 
> 
> 
> FROM node:12.2.0-alpine
> 
> 
> 
> # set working directory
> 
> WORKDIR /app
> 
> 
> 
> # add `/app/node_modules/.bin` to $PATH
> 
> ENV PATH /app/node_modules/.bin:$PATH
> 
> 
> 
> RUN apk update && apk add --no-cache nmap && \
> 
>     echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
> 
>     echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
> 
>     apk update && \
> 
>     apk add --no-cache \
> 
>     chromium \
> 
>     harfbuzz \
> 
>     "freetype>2.8" \
> 
>     ttf-freefont \
> 
>     nss
> 
> 
> 
> ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
> 
> 
> 
> ```
> 
> 
> 
> run.js
> 
> ```js
> 
> (async () => {
> 
>   const browser = await puppeteer.launch({
> 
>     executablePath: "/usr/bin/chromium-browser",
> 
>     headless: true,
> 
>     args: ["--disable-dev-shm-usage", "--no-sandbox", "--disable-gpu"],
> 
>   });
> 
> })();
> 
> 
> 
> ```

Hi, thank you @sbland for the response. With chromium I have no problem but in my case It must work with Firefox. Because in my project I work with images and I have an issue in chromium related to the image orientation but this issue doesn't exist in firefox. So in chromium it works normally for me as well but it's not enough. 

Cheers.

**Comment by oxycash** [comment]
Did you try installing firefox separately and giving executable path?

**Comment by guilhermebentomarques** [comment]
@oxycash  I was able to make it work with the executablePath, and I was having the problem with the printscreen (target closed). But then I realized the problem was memory and after use the container with free memory limit, the printscreen was working.

The solution was install the firefox-esr on alpine and use the executable path 'usr/bin/firefox'. 

Thank you.
