### ISSUE TITLE
Page.setContent (or Page.screenshot) does not wait for SVG to fully render

### ISSUE THREAD

**Issue by mbergal** [puppeteer/puppeteer#791]
Puppeteer does not correctly capture page containing SVG without timeout between setContent and page.screenshot. Please note, all resources are local and nothing is fetched over network.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Mac OS X 10.12.6/Ubuntu Trusty

**What steps will reproduce the problem?**

See my repo https://github.com/mbergal/puppeteer-svg-rendering.

Essentially, given simple not loaded over network SVG, executing this w/o 1 second timeout between `page.setContent` and `page.screenshot` produces empty image and when 1 second timeout is uncommented screenshot renders fine.
```

  var browser = await puppeteer.launch({ headless: false });
  var page = await browser.newPage();
  await page.setContent(testContent);

//   await timeout(1000); // Makes all the difference

  var imageBuffer = await page.screenshot({
    type: "jpeg",
    fullPage: true
  });
  fs.writeFileSync(outputFileName, imageBuffer);
```
**What is the expected result?**

Screnshot contains rendered SVG:

![test-with-timeout](https://user-images.githubusercontent.com/167835/30446060-ab746924-994d-11e7-8896-4fe103480937.jpg)

**What happens instead?**

Screnshot is empty:

![test](https://user-images.githubusercontent.com/167835/30446050-a68e5d16-994d-11e7-97ca-a1745c7b0334.jpeg)

**Comment by frantz** [comment]
I think you have to wait for page load before making screenshot.
```javascript
await page.waitForNavigation({
  waitUntil: 'load'
});
```

**Comment by mbergal** [comment]
Thanks!

This seems to work best:

```
const loaded = page.waitForNavigation({
  waitUntil: 'load'
});
await page.setContent(testContent);
await loaded
```

**Comment by Create-Peace** [comment]
why not take effect using this method？Screnshot is empty:
```
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const html = `
  <!DOCTYPE html>  
<html>
<head>  
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
<style>
html{height:100%}    
body{height:100%;margin:0px;padding:0px}    
#container{height:100%; background: red}
</style>
<title>Hello, World</title>  
</head>  
<body>  
<div id="container">12312312</div> 
</body>  
</html>
  `;

  const loaded =  page.waitForNavigation({
    waitUntil: 'load'
  });

  await page.setContent(html);
  await page.setViewport({isMobile: true, width: 375, height: 667});
  await loaded
  await page.screenshot({path: 'test1.png', clip: {x: 0, y: 300, width: 375, height: 259}});

  await browser.close();
})();
```

**Comment by nibiru2O12** [comment]
a workaround https://github.com/GoogleChrome/puppeteer/issues/728#issuecomment-334301491
