### ISSUE TITLE
[Bug]: Cannot run browser in Firefox on Ubuntu

### ISSUE THREAD

**Issue by markcellus** [puppeteer/puppeteer#7910]
### Bug description

Steps to reproduce the problem:

1. Ran `PUPPETEER_PRODUCT=firefox npm i puppeteer`
2. Attempt to run on my Ubuntu server: `await puppeteer.launch({ product:'firefox'});`
3. `const page = await browser.newPage()`
4. `await page.goto('http://example.com');`

I expected to navigate to URL, but getting this error instead:

```
Error: Failed to launch the browser process!
XPCOMGlueLoad error for file /home/<redacted>/www/node_modules/puppeteer/.local-firefox/linux-98.0a1/firefox/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/<redacted>/www/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at Interface.<anonymous> (/home/<redacted>/www/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:219:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

NOTE: Couldn't find anything on troubleshooting page.

### Puppeteer version

13.1.0

### Node.js version

16.13.1

### npm version

8.1.2

### What operating system are you seeing the problem on?

Linux

**Comment by jbielick** [comment]
It sounds like you're missing an OS package dependency. Does installing `gtk3` make a difference? 

Some brief installation instructions (dependent on your linux):
https://stackoverflow.com/a/50768180/3543371

**Comment by markcellus** [comment]
Sure maybe I missed that requirement. I will try once I get some time (likely this weekend). In the meantime, is that dependency documented as a requirement somewhere on this project? If so, can you point me to that? I'd like to know all dependencies that are required if possible. Thanks!
