### ISSUE TITLE
[Bug]: Browser.close() doesn't close Chromium if there are open pages

### ISSUE THREAD

**Issue by akornatskyy** [puppeteer/puppeteer#7922]
### Bug description

Steps to reproduce the problem (Windows only):

1. Launch browser in headless mode with options `--in-process-gpu` and `--use-gl=swiftshader`.
2. Open a new page and go to some URL.
3. browser.close() - hangs and doesn't exit.

It works as expected when `headless` is `false` or above options are used alone (not together) or using Linux.

Workaround: close all pages before call to `browser.close()`.

### Puppeteer version

13.1.1

### Node.js version

17

### npm version

8.3.1

### What operating system are you seeing the problem on?

Windows

**Comment by yf-hk** [comment]
Same issue here. `await browser.close()` got stuck if it's in headless mode, and with `--single-process` option.

**Comment by codingchili** [comment]
using puppeteer `13.5.1` on windows, when running headless - closing all pages doesn't close the browser either, as it does when headless is false. this used to close the browser in both cases. closing all pages and closing the browser, successfully shuts down puppeteer in headless mode.

```
const args = puppeteer.defaultArgs().filter(arg => arg !== '--disable-gpu');
            args.push('--use-gl=desktop');
            args.push('--headless');
            browser = await puppeteer.launch({
                ignoreDefaultArgs: true,
                args
            });
```
closing the only page and the browser as part of my test case cleanup.

```
after(async () =>{
        await page.close();
        await browser.close();
    });
```

**Comment by sanjaykumar27** [comment]
Still not working

**Comment by Ahmad-Abdalmageed** [comment]
Any updates on this ?

**Comment by Kihoshi** [comment]
Hi , may try to close all the pages first before browser.close()
```
        const pages = await browser.pages();
        for (let i = 0; i < pages.length; i++) {
          await pages[i].close();
        }
          await browser.close();
```

**Comment by kaisellgren** [comment]
I could not get Puppeteer Browser to close even after trying to close its pages first. The only thing I got to work was to kill the child process:

```typescript
const childProcess = browser.process()
if (childProcess) {
  childProcess.kill(9)
}
```

**Comment by Bloodsucker** [comment]
I have also experience random hangs of the browser instance. Most specially, it seems to hang when trying to create a new incognito context (`Browser#createIncognitoBrowserContext()`). Trying to close the browser with `browser.close()` also causes the promise to hang, potentially indefinitely. I was using this for unit testing, so what I ended up doing was to kill the browser's process in order to close it (@kaisellgren solution), instead of closing it cleanly. I also do that on every test, which significantly slow-downs the whole testing process as this seems to solve the random hangs of `createIncognitoBrowserContext` call.

**Comment by caycewilliams** [comment]
This is still happening. I find that when it tries to open a site repeatedly that crashes, it then hangs on closing after about 40 tries to open the site.

"puppeteer": "^21.5.2"

**Comment by javier-sauma-rocketlab** [comment]
> I could not get Puppeteer Browser to close even after trying to close its pages first. The only thing I got to work was to kill the child process:
> 
> ```ts
> const childProcess = browser.process()
> if (childProcess) {
>   childProcess.kill(9)
> }
> ```

I had the same issue, my endpoint return timeout after 30 sec but continue working on the background. 
I put a console.log before and after browse.close() and have more than 1 minute of difference between them.

I tried to do page.close() but not changes. 
Finally, killing the child process work for me.

**Comment by lowzyyy** [comment]
> > I could not get Puppeteer Browser to close even after trying to close its pages first. The only thing I got to work was to kill the child process:
> > ```ts
> > const childProcess = browser.process()
> > if (childProcess) {
> >   childProcess.kill(9)
> > }
> > ```
> 
> I had the same issue, my endpoint return timeout after 30 sec but continue working on the background. I put a console.log before and after browse.close() and have more than 1 minute of difference between them.
> 
> I tried to do page.close() but not changes. Finally, killing the child process work for me.

Did you do this after `browser.close()` or are you using this **instead** of `browser.close()`

**Comment by caycewilliams** [comment]
@lowzyyy If browser.close fails or stalls, I abort that via a promise and do a kill process. But you could just kill the process. Unsure of any downsides to that approach.

**Comment by javier-sauma-rocketlab** [comment]
> > > I could not get Puppeteer Browser to close even after trying to close its pages first. The only thing I got to work was to kill the child process:
> > > ```ts
> > > const childProcess = browser.process()
> > > if (childProcess) {
> > >   childProcess.kill(9)
> > > }
> > > ```
> > 
> > 
> > I had the same issue, my endpoint return timeout after 30 sec but continue working on the background. I put a console.log before and after browse.close() and have more than 1 minute of difference between them.
> > I tried to do page.close() but not changes. Finally, killing the child process work for me.
> 
> Did you do this after `browser.close()` or are you using this **instead** of `browser.close()`

Im using it instead. In my case when the browser.close()` it's called take more than 1 minute in finish.

My code is something like this
   try {
      results = await Promise.all(promises)<-- Open and use pupp here
    } catch (error) {
      console.log('catch Error', error)
    } finally {
      await closeBrowser(browser) <-- This is the function to kill the process
    }

**Comment by TheGP** [comment]
Why its not fixed yet?

**Comment by demilsson** [comment]
Can confirm this is still an issue. Killing the process seems more reliable.

**Comment by jaimeiniesta** [comment]
I can also confirm this is still an issue. I'm also trying to kill the process if it doesn't respond to `browser.close()` in a timely manner. Seems to help a bit but it causes a lot of trouble in AWS Lambda.

I'm using the latest versions of Puppeteer, Chromium, and NodeJS.

Saw this in the logs, in case it helps:

```
 Nov 29th 03:39:59pm ERRO staging 86b908c Error closing resources: TargetCloseError: Protocol error (Target.closeTarget): Target closed
  Nov 29th 03:39:59pm ERRO staging 86b908c     at CallbackRegistry.clear (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:73:36)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at #onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:165:25)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at WebSocket.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:49:30)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at callListener (/var/task/node_modules/ws/lib/event-target.js:290:14)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:220:9)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at WebSocket.emit (node:events:518:28)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at WebSocket.emitClose (/var/task/node_modules/ws/lib/websocket.js:272:10)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at Socket.socketOnClose (/var/task/node_modules/ws/lib/websocket.js:1341:15)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at Socket.emit (node:events:518:28)
  Nov 29th 03:39:59pm ERRO staging 86b908c     at TCP.<anonymous> (node:net:343:12) {
  Nov 29th 03:39:59pm ERRO staging 86b908c   cause: ProtocolError
  Nov 29th 03:39:59pm ERRO staging 86b908c       at <instance_members_initializer> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:94:14)
  Nov 29th 03:39:59pm ERRO staging 86b908c       at new Callback (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:98:16)
  Nov 29th 03:39:59pm ERRO staging 86b908c       at CallbackRegistry.create (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:23:26)
  Nov 29th 03:39:59pm ERRO staging 86b908c       at Connection._rawSend (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:90:26)
  Nov 29th 03:39:59pm ERRO staging 86b908c       at Connection.send (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:81:21)
  Nov 29th 03:39:59pm ERRO staging 86b908c       at CdpPage.close (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:855:34)
  Nov 29th 03:39:59pm ERRO staging 86b908c       at async /var/task/app.js:15:21
  Nov 29th 03:39:59pm ERRO staging 86b908c       at async closeResources (/var/task/app.js:12:5)
  Nov 29th 03:39:59pm ERRO staging 86b908c       at async analyze (/var/task/app.js:115:7)
```

**Comment by ikerya** [comment]
> Same issue here. `await browser.close()` got stuck if it's in headless mode, and with `--single-process` option.

Same. No issues after removing the argument. Really strange behavior for puppeteer and most importantly for its team who wouldn't respond for months to an incredibly confusing bug.
