### ISSUE TITLE
[Bug]: Puppeteer fails to scroll using Input.synthesizeScrollGesture

### ISSUE THREAD

**Issue by ericaho** [puppeteer/puppeteer#7928]
### Bug description

Puppeteer fails to scroll using a .send() command on Input.synthesizeScrollGesture using gestureSourceType of 'touch'. This code snippet below had worked as an example for some time, but sometime within the last month or so, is failing to behave as expected.   

Steps to reproduce the problem:

1. Using Chrome Version 97.0.4692.99 on Windows 10
2. Example Code:
` 
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  const client = await page.target().createCDPSession();
  const iPhone = puppeteer.devices['iPhone 11 Pro Max'];
  
  await page.emulate(iPhone);
  await page.goto('https://www.wikipedia.org/');
  await client.send("Input.synthesizeScrollGesture",{
    x: 100,
    y: 300,
    repeatCount: 4,
    yDistance : -400,
    gestureSourceType: 'touch'
  });
  await browser.close();
})();
`
3. Run example code ( node ./examplecode.js )
4. Note that no scrolling action(s) take place.
5. Changing gestureSourceType to 'default' or 'mouse' appears to make the scrolling action function, however 'touch' does not work.

### Puppeteer version

13.11.1

### Node.js version

16.13.1

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
I think it's a bug in Chromium, not in Puppeteer https://bugs.chromium.org/p/chromium/issues/detail?id=1286658
