### ISSUE TITLE
[Bug]: __dirname points to root

### ISSUE THREAD

**Issue by codydaig** [puppeteer/puppeteer#7932]
### Bug description

Steps to reproduce the problem:

1. In a project that uses webpack and typescript, depending on configuration of other node/webpack items, __dirname points to `/`. This results in a TypeError tracing back to the Browser Launch. 

Further investigations show that initializePuppeteerNode isn't setting puppeteerRootDirectory. 

The fix for this is to fall back to process.cwd() when pkgDir.sync(__dirname) comes back undefined.

### Puppeteer version

13.1.2

### Node.js version

14.18.0 & 16

### npm version

6.14.15

### What operating system are you seeing the problem on?

Linux, macOS, Windows

### Relevant log output

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
     at new NodeError (internal/errors.js:322:7)
     at validateString (internal/validators.js:124:11)
     at Object.join (path.js:1148:7)
     at new BrowserFetcher (webpack:////Users/codydaig/dev/opensource/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js?:162:22)
     at resolveExecutablePath (webpack:////Users/codydaig/dev/opensource/puppeteer/lib/cjs/puppeteer/node/Launcher.js?:610:28)
     at ChromeLauncher.launch (webpack:////Users/codydaig/dev/opensource/puppeteer/lib/cjs/puppeteer/node/Launcher.js?:107:57) {
   code: 'ERR_INVALID_ARG_TYPE'
 }
```

**Comment by apoteet** [comment]
Not sure if this is related, but I was getting this error running a webpack-bundled express server. The puppeteer 13.2 update replaced the above error with `Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (961656). at ChromeLauncher.launch` 
I was able to resolve this by specifying puppeteer as an external library, in addition to the fact that we were already following the link OrKoN posted on the proposed bugfix https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92

```
module.exports = {
    entry: { server: path.resolve(__dirname, './index.ts') },
    target: 'node',
    mode: 'none',
    node: {
        __dirname: false,
        __filename: false,
    },
    externals: [
        { puppeteer: 'puppeteer' }
    ],
...
```

**Comment by apoteet** [comment]
Not sure if this is related, but I was getting this error running a webpack-bundled express server. The puppeteer 13.2 update replaced the above error with Error: Could not find expected browser (chrome) locally. Run 'npm install' to download the correct Chromium revision (961656). at ChromeLauncher.launch
I was able to resolve this by specifying puppeteer as an external library, in addition to the fact that we were already following the link OrKoN posted on the proposed bugfix https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92

module.exports = {
    entry: { server: path.resolve(__dirname, './index.ts') },
    target: 'node',
    mode: 'none',
    node: {
        __dirname: false,
        __filename: false,
    },
    externals: [
        { puppeteer: 'puppeteer' }
    ],
...
}

**Comment by OrKoN** [comment]
This should be solved via https://github.com/puppeteer/puppeteer/pull/8003
