### ISSUE TITLE
[Bug]: --auth-server-whitelist="_" arg is not working for headless mode

### ISSUE THREAD

**Issue by pehguerra** [puppeteer/puppeteer#7934]
### Bug description

--auth-server-whitelist="_" arg is only working with headed mode. I tried with many puppeteer versions and I noticied that this arg in headless mode is not working anymore as of 12.0.0 version.

This args will ignore ntlm authentication

### Puppeteer version

13.1.2

### Node.js version

16.13.1

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

**Comment by RafaelSantana97** [comment]
I am facing the same issue. Even incognito mode is forcing the NTLM Authentication in newer versions

**Comment by OrKoN** [comment]
Have you tried `--auth-server-allowlist=`? See https://bugs.chromium.org/p/chromium/issues/detail?id=1142696
