### ISSUE TITLE
[Bug]: Timeout error when running puppeteer in multiple concurrent instances of a node app on GCP VM (debian)

### ISSUE THREAD

**Issue by aberibeiro-jellyfish** [puppeteer/puppeteer#7935]
### Bug description

I am using child_process (fork) to run multiple concurrent instances of my node app, which initialises puppeteer.launch()

On my local machine (Mac) this works fine, but when running on a linux (Debian 10) VM on GCP, I get timeout errors ("Navigation timeout of 30000 ms exceeded") for all the instances except the most recent, leading me to believe that something behind the scenes is not liking concurrent running of puppeteer?

Is there a way to get this to work like it does on my Mac?

In case it is relevant, I had to install the following packages on the linux VM to get puppeteer to run:

- libnss3
- libatk1.0-0
- libatk-bridge2.0-0
- libcups2
- libdrm2
- libxkbcommon0
- libxcomposite1
- libxdamage1
- libxrandr2
- libgbm1
- libpango-1.0-0
- libcairo2
- libxshmfence1
- libasound2

And launch() it with these flags:

args: [
      '--ignore-certificate-errors',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-accelerated-2d-canvas',
      '--disable-gpu'
    ],
pipe: true,

### Puppeteer version

10.4.0

### Node.js version

17.1.0

### npm version

8.1.2

### What operating system are you seeing the problem on?

Linux

**Comment by gitamineHM** [comment]
Hello @aberibeiro-jellyfish

Network latency may put loading op multiple puppeteer page to be longer,

try to add  this line for infinite navigation timeout : 

    var pages = await browser.pages();
    var page = pages[0];
    await page.setDefaultNavigationTimeout(0);   //Infinite navigation timeout
