### ISSUE TITLE
can i get AJAX/XHR response data

### ISSUE THREAD

**Issue by codenoid** [puppeteer/puppeteer#794]
hi, can i get (specific) AJAX/XHR response data ?

**Comment by codenoid** [comment]
request.response, still trying

**Comment by codenoid** [comment]
```
    page.on('response', response => {
      console.log('fa')
      console.log(response.text())
    })
```

`Promise { <pending> } ` ??

**Comment by codenoid** [comment]
something wrong with the web

**Comment by arsen-sargsyan** [comment]
@codenoid try this

```javascript
 page.on('response', response => {
        response.text().then(function (textBody) {
            console.log(textBody);
        })
    })
```

**Comment by dbauszus-glx** [comment]
I have the same problem.

An ajax request is going from script in puppeteer to the backend and the backend responds by sending json to the puppeteer browser.

I use page.on('reponse') which errs with following message.

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Protocol error (Network.getResponseBody): No data found for resource with given identifier undefined

**Comment by dbauszus-glx** [comment]
Soz... last comment was rubbish. Got there in the end by making launching puppeteer with a head for debugging to notice that my ajax had a CORS issues.

**Comment by npetr** [comment]
Thank you for the hint @arsen-sargsyan. These two variants work for me:

**Variant 1** (with ".then")
```javascript
const puppeteer = require('puppeteer');

// Puppeteer page event types to catch
const pevents = [
    'console',
    'dialog',
    'load',
    'domcontentloaded',
    'error',
    'pageerror',
    'frameattached',
    'framenavigated',
    'framedetached',
    'request',
    'requestfinished',
    'requestfailed',
    'response'
];

async function main() {
    // Create headless session
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    const client = await page.target().createCDPSession();

    // Log puppeter page notifications
    pevents.forEach((peventName) => {
        page.on(peventName, async (plistenerFunc) => {
            console.log({ peventName, plistenerFunc });
            if (peventName == 'response') {
                await plistenerFunc.text()
                    .then((textBody) => {
                        console.log('textBody:', textBody);
                    }, (err) => {
                        console.error(plistenerFunc, err);
                        console.log(plistenerFunc, err);
                    })
                ;
            }
        });
    });

    // Open a page, than close
    await page.goto('https://www.google.com', { waitUntil: ['networkidle2', 'load', 'domcontentloaded'], timeout: 100000 });
    await page.close();
    await browser.close();
}

main();
```
**Variant 2** (with 2x await)
```javascript
// cut here (same as Variant 1)
            console.log({ peventName, plistenerFunc });
            try {
                if (peventName == 'response') {
                    const textBody = await plistenerFunc.text();
                    await console.log('textBody:', textBody);
                }
            } catch (err) {
                console.error(plistenerFunc, err);
                console.log(plistenerFunc, err);
            }
        });
    });
// cut here (same as Variant 1)
```

**Note**
On some pages (e.g. forbes.com) does not work as smooth as expected, please see #2258.

**Comment by tim8917** [comment]
Hi guys. Have a related to the topic problem with multiple page.clicks and page.on('response') XHR requests catches.

I'm iterating over elements and clicking each one. A click on each of them invokes just xhrs and no navigation. I need to catch all the xhrs that appear while clicking those elements. Here is my code: 

        

       page.on('response', response => {
            // allow XHR only
            if ('xhr' !== response.request().resourceType()){
                return ;
            }
            console.log(response.url());
        });

        let popupLinks = await page.evaluate(() => document.querySelectorAll('span.just-xhrs-no-navigation'));
        for (let k=1; k<=popupLinks.length; k++){
                await Promise.all([
                    page.click('span:nth-child(' + k+ ')'),
                    page.waitForSelector('#popup.shown')
                ]);
         }


But page.on('response') 's console.log shows info just for the very first click.

**Comment by nei** [comment]
I still can't get the response from the ajax calls. I am trying this https://github.com/nei/rico-puppeteer/pull/1/files I've also tried some of the tips posted here but nothing worked.

I am using node v9.11.1, and puppeteer": "^1.6.0"

**Comment by beyondverage0908** [comment]
```
page.on('response', response => {
        // allow XHR only
        if ('xhr' !== response.request().resourceType()){
            return ;
        }
        response.json().then((res) => {
             console.log("===>>> ", res);
        });
});
```
