### ISSUE TITLE
[feature]: hand over a File/DirectoryHandle to the client easier

### ISSUE THREAD

**Issue by jimmywarting** [puppeteer/puppeteer#7941]
### Bug description

Handing over a file system access handle to the page that it can work with is nothing but problematic...
there is no easy way to hand a file or a directory over other than using the legacy fileChoose picker/intercepter (that i know of?)

there are new ways to open and pick using `showOpenFilePicker` or `showDirectoryPicker` but it's not covered by the `Page.setInterceptFileChooserDialog`... so the only round about way i found was to emulate a drag and drop with files and then use `item.getAsFileSystemHandle()`

Here is my current workaround:
```js
  await page.evaluate(() => {
    document.body.draggable = true
    globalThis.ondragover = evt => evt.preventDefault()
    globalThis.ondrop = evt => {
      globalThis.ondrop = globalThis.ondragover = null
      document.body.draggable = false
      globalThis.root = evt.dataTransfer.items[0].getAsFileSystemHandle()
    }
  })
  await page.setDragInterception(true)
  const draggable = await page.$('body')
  const dropzone = await page.$('body')
  const data = await draggable.drag({ x: 0, y: 0 })
  data.files = [ filepath ]
  await dropzone.dragEnter(data)
  await dropzone.drop(data)
  await page.evaluate(() => {
    return globalThis.root.then(root => {
      globalThis.root = root
      console.log(root)
    })
  })
```

can this be simplified somehow?
I have also speculations if you somehow can pre-populate a IndexedDB record with a handle somehow...

### Puppeteer version

puppeteer-core 13.1.2

### Node.js version

v17.4.0

### npm version

8.3.1

### What operating system are you seeing the problem on?

macOS

**Comment by miroljub1995** [comment]
Can we reopen this issue since it is not resolved yet?
