### ISSUE TITLE
[Bug]: await page.keyboard.press("LeftArrow") not firing!

### ISSUE THREAD

**Issue by AntoCrasher** [puppeteer/puppeteer#7943]
### Bug description

Steps to reproduce the problem:
```
const puppeteer = require('puppeteer-core');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    });

    const page = await browser.newPage();
    await page.goto("https://youtube.com");
    await page.waitForNavigation();
    await page.keyboard.press("F12");
})();
```

### Puppeteer version

13.1.2

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
there are no errors in the log it just doesn't press f12
```

**Comment by rubiconjosh** [comment]
The title says '`page.keyboard.press("LeftArrow")` not firing' and the example shows `page.keyboard.press("F12")`. Are you having issues with LeftArrow or F12?

Are you trying to open Dev Tools with keyboard.press()? It does not work that way. The key press will be sent to the page, but the browser will not open Dev Tools.

You can set devtools to true in the [launcher options ](https://pptr.dev/#?product=Puppeteer&version=v13.1.2&show=api-puppeteerlaunchoptions) to open devtools.

**Comment by AntoCrasher** [comment]
I am trying to press left arrow and then enter, i just used f12 so i can see it better. But nothing works with `page.keyboard.press()`. I am doing this because when i press the play button on roblox.com, it asks me if i want to launch roblox with a popup. 

<img width="583" alt="CleanShot 2565-01-31 at 11 16 50@2x" src="https://user-images.githubusercontent.com/48983909/151738240-496b1261-53f8-4d2b-9622-15dd84b08f5d.png">

I also tried using `page.on("dialog", () => {});` but it doesnt fire at all

**Comment by tfa346** [comment]
@rubiconjosh  It's because the code is ArrowLeft, not LeftArrow
