### ISSUE TITLE
[Bug]: img src URLs without a protocol scheme are not intercepted

### ISSUE THREAD

**Issue by mgrant0** [puppeteer/puppeteer#7944]
### Bug description

Steps to reproduce the problem:

1. Load a page with an img tag like this:

```
<img src="192.168.69.91/53697882.png" /> 
```

2. try to intercept the request to get the image:

```
await page.setRequestInterception(true);
page.on('request', (interceptedRequest) => {
  console.log("got here with url:" + interceptedRequest.url());
});
```

3. the 'got here with url' never written when the src doesn't start with 'http://' or 'https://'.

### Puppeteer version

13.1.0

### Node.js version

16

### npm version

8

### What operating system are you seeing the problem on?

Linux

**Comment by Zakichanu** [comment]
Hi,

Instead of using "setRequestInterception" method, did you try with evaluate method? I got a snippet for you that works for me

```js
const imgs = await page.$("img[src]");
const imgURL = await page.evaluate((img) => img.getAttribute("src"), imgs);

console.log("URL of image :" + imgURL);
```

I'm not familiar with setRequestInterception method but I don't think it's the best way to get URL of an image source

**Comment by mgrant0** [comment]
I see what you're driving at.  What you sent only seems to get at the first img but outside the browser context.  I took it a bit further getting at the array of imgs inside the browser context but it still doesn't work.

```
const content = await page.$("body");
const imgs = await page.$("img[src]");
await page.evaluate((img) => {
  let src = img.getAttribute("src");
  console.log("in evaluate url: "+src);
  if (! (src.startsWith('http://') || src.startsWith('https://') )) {
    img.setAttribute('src', 'http://'+src);
  }
}, imgs);
```

The problem here it seems is that the page is already loaded without the images because they lacked a scheme (http or https).

What I was originally hoping (and perhaps someone can chime in here) is how to intercept the request to fix the url before the request fails?

The docs for at least `page` say the url should contain a scheme but unfortunately there's a lot of html out there that contains links that don't and this is what I'm trying to work around above.  It would seem like there should be a default scheme or a way to specify a default scheme but I couldn't find anything on that.  Many browsers and email apps like gmail which runs in the browser are lenient in this treatment of src urls.

**Comment by Zakichanu** [comment]
Yeah, it seems that is a bug and you have to find a solution to bypass it, I'm investigating on it, I will post a comment if I find something to solve that

**Comment by mgrant0** [comment]
This is still an issue.  Seems like it should not be too difficult to fix.

**Comment by OrKoN** [comment]
I am not able to reproduce with the latest versions.
