### ISSUE TITLE
[Bug]: Focus do not switch

### ISSUE THREAD

**Issue by MrDelik** [puppeteer/puppeteer#7952]
### Bug description

Hi guys, have some trouble selecting fields and typing in it. The focus is not on the second field when i click on it.

Steps to reproduce the problem:

1. Opening the page
```JavaScript
const browser = await puppeteer.launch({headless: false});
const [page] = await browser.pages();
await page.goto('someUrl');
const { keyboard, mouse: mousePointer } = page;
```

2. getting a field
```JavaScript
await page.$('#email', {visible: true});
await mousePointer.click(fieldPos[0], fieldPos[1]);
```

2. Typing in the field
```JavaScript
await keyboard.type('text');
```

3. Switch field to type in it
```JavaScript
await page.$('#email', {visible: true});
await mousePointer.click(otherFieldPos[0], otherFieldPos[1]);
```

if i type now with `await page.keyboard.type('text');` it will type in the first field, because the first field is still focused. The focus change just for a very tiny moment but comme back on the first field.

There is no error thrown, nothing in the console.

Am i missing something ? 
I tripple checked the positions, they are correct.
I wait for the first field to be in the DOM to be able to write in it.

### Puppeteer version

13.1.1

### Node.js version

17.2.0

### npm version

8.1.4

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Hey, try using the element handle to click and type:

```
const el = await page.$('#email', {visible: true});
await el.type('abc');
await el.click(); 
```

The page.keyboard is a global class that just dispatched keyboard events (like a real keyboard). So the typing will happen where the focus is. Alternatively, you can call .focus() on elements to make sure they are focused. 

I hope it helps. Otherwise, please submit a test page/script so that we can reproduce it.

**Comment by MrDelik** [comment]
Unfortunately it does the same thing :/
