### ISSUE TITLE
[Question]: Instagram screenshot redirects to login

### ISSUE THREAD

**Issue by iamtortue001101** [puppeteer/puppeteer#7955]
### Bug description

Hello, I want to take screenshots of people's profile pages for instagram and twitter, but they want me to login. Below is the user agent I use. I can send this request from my own computer without any problems, but it wants me to log in through my server.

User agent;

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36`

```
const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
  await page.setViewport({
        width: 1300,
        height: 600,
        deviceScaleFactor: 1
      });
```

**The result I got when I tried it on my own computer;**

![54352](https://user-images.githubusercontent.com/46280838/151983244-95ad7f85-e161-4cd4-8fd3-846c581b482a.jpg)

**The result I got when I tried it on the server;**

![167917](https://user-images.githubusercontent.com/46280838/151983395-05197152-834b-42a1-93f9-ee02c254e491.jpg)

`Note: the server is hosted on amazon.`

### Puppeteer version

13.1.3

### Node.js version

14.17.6

### npm version

8.3.0

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Hey! You should try asking the question on StackOverflow https://stackoverflow.com/questions/tagged/puppeteer
It does not look like a bug in Puppeteer and probably it is Instagram doing some geo/ip analysis.
