### ISSUE TITLE
[Bug]: startCSSCoverage doesn't respect `resetOnNavigation: false`

### ISSUE THREAD

**Issue by oscarmarcelo** [puppeteer/puppeteer#7972]
### Bug description

Steps to reproduce the problem:

1. Run the following script:
```js
const puppeteer = require('puppeteer');
const pti = require('puppeteer-to-istanbul');

const paths = [
    'https://npmjs.com/',
    'https://npmjs.com/package/puppeteer',
];

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await Promise.all([
        page.coverage.startCSSCoverage({
            resetOnNavigation: false
        })
    ]);

    for (const path of paths) {
        await page.goto(path, {
            waitUntil: "networkidle0",
            timeout: 45000
        });

        // Doing other things to ensure that all CSS meant to be used in the current page is triggered.
        // Viewport resizes, scroll, hover/focus, clicks, etc.
    }

    const [cssCoverage] = await Promise.all([
        page.coverage.stopCSSCoverage()
    ]);

    const coverage = [...cssCoverage];

    pti.write(coverage);

    await browser.close();
})();
```

2. Generate report with Istanbul: `nyc report --reporter=html`

## Results

The report will only show coverage results for the last page.

If you try to run the script again, but using only the last link in `paths`, you'll see that the results are exactly the same. as the previous one containing multiple links.

Also, trying to invert the order and then running the script with just the last link in that new order, the results will always reflect only the last link in `paths`.

### Puppeteer version

13.2.0

### Node.js version

16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

macOS

**Comment by nu111** [comment]
Same issue on puppeteer `13.6.0` and node.js `v18.0.0`

**Comment by nu111** [comment]
Issue confirmed on puppeteer `15.5.0` and node `v18.5.0`.

**Comment by OrKoN** [comment]
I am not able to reproduce if the sites are different, e.g., `example.com` and `wikipedia.org`. I think in the case of npm URLs the coverage is just very similar. The flag is definitely respected in the latest versions https://github.com/puppeteer/puppeteer/blob/3e1e419fe6358e624ff79b2a1c17a7cab13a65ba/packages/puppeteer-core/src/cdp/Coverage.ts#L380
