### ISSUE TITLE
[Bug]: element screenshot not vertically aligned with element

### ISSUE THREAD

**Issue by travisgroth** [puppeteer/puppeteer#7999]
### Bug description

When selecting an element and then taking a screenshot, I consistently get screenshots that are a fair number of pixels further down the page than the element I'm targeting.

Steps to reproduce the problem:

```typescript
import puppeteer from 'puppeteer';

const run = async () => {
  const browser = await puppeteer.launch({
    headless: false,
  }); 
  const page = await browser.newPage();
  await page.goto('https://stackoverflow.com/');

  const header = await page.waitForSelector('body > header');
  await header?.screenshot({ path: 'header.png' });
  await browser.close();
};

run();
```

This is the page itself:

![image](https://user-images.githubusercontent.com/6198562/153434531-513cd2c1-2a93-4292-8015-7e88763a9ddc.png)

Given the selector, I'd expect a result like this:

![image](https://user-images.githubusercontent.com/6198562/153434718-ed66f0b9-191a-4e0a-aa2e-99411016e883.png)

Instead, I get something like this from the code above:

![image](https://user-images.githubusercontent.com/6198562/153434837-33a2c1ef-e1c3-477a-93fe-ce298190e9e6.png)

It's clearly just below the header.  If the element is large enough, I'll get most of the element but the top will be missing and I'll have content from below it included.  It's like everything is vertically offset by 100-200 pixels.

This is consistent across several sites I've tried.  The reproduction is intentionally contrived on a stable selector.

### Puppeteer version

13.3.0

### Node.js version

v16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
N/A
```

**Comment by travisgroth** [comment]
Additional data point - if I manually use Chrome dev tools to take a screenshot of the node, I get the expected result:

![image](https://user-images.githubusercontent.com/6198562/153437306-ea25f0fb-5542-4273-814a-81f673a43add.png)

**Comment by OrKoN** [comment]
cc @sadym-chromium

**Comment by lowvisiondave** [comment]
I am experiencing this also with 13.3.1

**Comment by khanisak** [comment]
Same issue even on simple html with only one paragraph.
Works fine if I use puppeteer v10.1 and below.

Seems a bug from v10.2 and newer.

**Comment by ali-habibzadeh** [comment]
I have this issue too. Screenshoting elements is just completely broken and takes random screenshots
