### ISSUE TITLE
New project name

### ISSUE THREAD

**Issue by paulirish** [puppeteer/puppeteer#80]
While "puppeteer" is apt, there are a few downsides: 3 syllables (and kinda a mouthful), difficult spelling (surprisingly), kinda plain, the npm name is taken. There's been an interest amongst a few folks to retitle the project before shipping. 

I have collected a few possibilities below. 

I'm not explaining each name for simplicity, I'd rather them stand on their own. However, most have connotations and associations with things like: legend of sleepy hollow, headlessness, phantom of the opera, scientific method/testing, shadow puppets.

------------------

`blacksmith`
`silhouette`
`christine`
`theremin`
`bradshaw`
`dudley`
`leroux`
`sobaka`
`irving`
`mombi`
`scrim`
`curie`

------------------

Any other proposals? Comment and I will integrate new ones into the list above.

**Comment by aslushnikov** [comment]
`sobaka` comes with a slogan:

> Sobaka: Web Developer's best friend.

(because 'sobaka' is a 'dog' in russian)

A few short words came to mind recently:
- `shoom` (visually nice, but resembles 'shroom')
- `priz`

**Comment by JoelEinbinder** [comment]
`vampire`

**Comment by JoelEinbinder** [comment]
`theremin`

**Comment by aslushnikov** [comment]
A few ideas which follow the lead of `blink` (which is about tag which doesn't exist) and `chrome` (which is about component which chrome doesn't have):
- `ceann`
- `headfull`
- `caput`

**Comment by paulirish** [comment]
Looks like **`blin`** is the winner.

Mock:

![image](https://user-images.githubusercontent.com/39191/28296646-5a083e56-6b1e-11e7-8beb-eba5ca70c776.png)

----------

EDIT: a day later, there's not much enthusiasm anymore for `blin`.. 😢

**Comment by paulirish** [comment]
`carbon`

**Comment by JoelEinbinder** [comment]
`sponge`
![sponge](https://user-images.githubusercontent.com/4624233/28391320-613135e6-6c92-11e7-8cd3-cd93ea0b40c0.png)

**Comment by aslushnikov** [comment]
`Opium` - liberates from (automation) pain. Both the name and the logo nicely correlate with chromium

![image](https://user-images.githubusercontent.com/746130/28406342-f7cdeb78-6ce4-11e7-8c91-0cd122b20898.png)

**Comment by drufball** [comment]
Curie or Carbon both sound good to me.

Personally I would vote for Curie because I'm just guessing that Carbon is probably taken by something somewhere already :)

Picking names is always hard though - maybe it's easier just to ask if anyone wants to veto Curie or Carbon?

**Comment by aslushnikov** [comment]
`carbon` feels good to me - it's lightweight and robust. 

However, looks like there are both `carbon` and `curie` packages on npm.

**Comment by drufball** [comment]
There doesn't seem to be an `irving` package and that has a nice headless theme. Are there any vetoes for that?

**Comment by ebidel** [comment]
IMO, we should stay clear of proper nouns. It makes talking about the project more confusing when referencing it in material, talks, conversation, etc. SEO is also something we care about.

Something to consider is using the @google namespace on npm or prefixing with "google-". Then we could use any package name. It's also nice for devs discovering the module. They see "Google" and knows it's official.

Fwiw, I sent the owner of the "puppeteer" package a couple of emails about a month ago. According to the npm policy, we should be able to grab that package name since the existing project is very old and inactive.

**Comment by ebidel** [comment]
**Update** -  Chris is willing to hand over the "puppeteer" package name when he gets back from vacation.

<img width="454" alt="screen shot 2017-07-21 at 11 58 40 am" src="https://user-images.githubusercontent.com/238208/28454314-d8cc5890-6e0b-11e7-8541-a63b48ccaae3.png">

**Comment by JoelEinbinder** [comment]
`wasabi`

**Comment by Garbee** [comment]
I feel like Puppeteer is just fine. Spelling is an issue but we have auto-correct most places for that. The only thing I'd urge to do is grab the easy mis-spelling NPM packages and forward them to the main one to prevent [typosquatting](http://incolumitas.com/2016/06/08/typosquatting-package-managers/).

**Comment by Garbee** [comment]
"Chrome Actor" could be a thing. but this would mean making the one word name a two-word one. That may not be the best choice. Current search results look mundane though, so fairly open for take-over by a project.

**Comment by Garbee** [comment]
And just found a previous Google project with the same name. https://github.com/google/puppeteer

**Comment by aslushnikov** [comment]
So while we have this open...

![llama](https://user-images.githubusercontent.com/746130/28583815-5a465752-711f-11e7-841c-2dc9eaef41f5.png)

`llama`. Llamas are cool and hipsty. Also, `llama.org` is free.

**Comment by JoelEinbinder** [comment]
`llama` is my favorite. I can spell it I think.

**Comment by Garbee** [comment]
If `llama` makes it I promise to always facepalm while giving a talk and introducing it.

**Comment by aslushnikov** [comment]
@Garbee that might be a good ice-breaker for the audience :)

**Comment by paulirish** [comment]
I spoke with the owner of the `carbon` NPM package and he agreed to hand it over. 👍 💯

**Comment by drufball** [comment]
carbon seems like a solid pick - easy to spell, catchy, and kind of science themed.

I propose we go with carbon unless anyone *really* hates it. There are always a million good options for names so in the interest of decisiveness only veto if you really don't like carbon, not if there's just another name you like a bit more!

**Comment by Garbee** [comment]
`carbon` would be my preferred choice of all the apparent options.

For giving talks about that we can also intro with talking about biological resources which would be nifty. Talking about llama's and why they try to be cool is certainly not as entertaining. :smile:

**Comment by ebidel** [comment]
IMO, I don't think the reasons listed merit a name change. We'll be able to get the npm package and users only type the name once. "Puppeteer" is also a more descriptive name, less common, and what the project actually is. It would also have the neatest logo!

But if others think a name change is a good idea, "carbon" would be my preference too. But we should check that there aren't a ton of existing projects with similar names. It's a common name.

**Comment by pavelfeldman** [comment]
I agree with Eric. Puppeteer sounds more engaging, authentic and unique. Carbon is a perfect name on its own, but it extremely generic and neutral, hence banal and uninviting. I would have voted for Carbon if we did not have a sound alternative, but we seem to have one. Also, no need to rename anything :)

**Comment by aslushnikov** [comment]
I especially like the 'no need to rename anything' bit.

**Comment by JoelEinbinder** [comment]
Someone has to talk to https://github.com/google/puppeteer then. I vote not me.

**Comment by aslushnikov** [comment]
Creative take on puppeteer's logo. Would look nice on stickers 
![screen shot 2017-07-28 at 12 44 30 am](https://user-images.githubusercontent.com/746130/28707653-0eaf35dc-732e-11e7-948b-2eb732ba11fc.png)

**Comment by JoelEinbinder** [comment]
That is horrifying.

**Comment by aslushnikov** [comment]
> Someone has to talk to https://github.com/google/puppeteer then. I vote not me.

I contacted someone responsible for https://github.com/google/puppeteer, we'll see how it goes.

**Comment by aslushnikov** [comment]
I talked to @progressnerd who is the owner of [google/puppeteer](https://github.com/google/puppeteer). He is totally fine with putting a note at the top of his README, saying something like:

> If you are looking for chrome headless automation library, go to [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer).

I'll send him PR once we go public. 

And since no one has voiced any new concerns about the "Puppeteer" name...
Congratulations, everybody! 🎉 Looks like we have agreed on a beautiful name for the project.
