### ISSUE TITLE
Clip not works well in centos

### ISSUE THREAD

**Issue by RitterHou** [puppeteer/puppeteer#800]
* Puppeteer version: 0.10.2
* Platform / OS version: centos7

I want to clip one web page into lots of images so I can put the images on my home page to replacing the origin HTML.

The following code is trying clip images from one page, it works well in OSX. When I put the code into the server(server is running centos7), a weird thing happens, some images are not in the right size, just like the pic under the code.

```javascript
const browser = await puppeteer.launch({
    dumpio: true,
    args: ["--no-sandbox"],
    timeout: 10000
});
const page = await browser.newPage();
await page.emulate(iPhone);
await page.goto(url);

const dimensions = await page.evaluate(() => {
    return {
        width: document.documentElement.clientWidth,
        height: document.documentElement.clientHeight
    };
});

var htmlHeight = dimensions.height
var htmlWidth = dimensions.width

var clipHeight = 300
var y = 0 
var index = 1;
var imageArray = []
console.log(chalk.green('generating images....'))
while (y < htmlHeight) {
    var clip = {
        x: 0,
        y: y,
        width: htmlWidth,
        height: clipHeight
    }
    index++
    var data = await page.screenshot({ type: 'jpeg', quality: 90, clip: clip })
    data = data.toString('base64')
    imageArray.push(data)
    y += clipHeight

    if (y + clipHeight > htmlHeight)
        clipHeight = htmlHeight - y
}

var head = '<html><head></head><style>img {max-width: 100%;}</style><body>'
var images = '';
imageArray.forEach(img => {
    images = images + '<div><img src="data:image/png;base64, ' + img + '" /></div>'
})
var foot = '</body></html>'
var html = head + images + foot
```
### The wrong clip:
![2017-09-15 18 28 20](https://user-images.githubusercontent.com/11351442/30486562-8fbff3f2-99f6-11e7-836c-2c8a1b525ea2.png)

### The right clip should be like this:
<img width="378" alt="2017-09-15 22 25 08" src="https://user-images.githubusercontent.com/11351442/30487056-e6bfdc2a-99f7-11e7-9d58-a8e7830dd463.png">

As it shows in the pic, the image I highlighted is not in the right size. It looks a little small.

This phenomenon never happens on my Mac, but it happens in Linux. I can't understand why this happens...

**Comment by positlabs** [comment]
Similar issue to #802

**Comment by RitterHou** [comment]
It seems I have found the reason for this phenomenon...

My Linux device performance is better than my Mac, so the code in Linux is running faster than Mac. As far as I can see, if the clip of a page in Mac need 15s, the same operation in Linux may just need 2s~3s.

Maybe the operation running too fast caused this bug? An idea comes to my mind by chance, So I change the clip code to this
**before**
```javascript
var data = await page.screenshot({ type: 'jpeg', quality: 90, clip: clip })
```
**after**
```javascript
var data = await doScreenshot(page, clip)

var doScreenshot = (page, clip) => {
  return new Promise(resolve => {
    setTimeout(() => {
      page.screenshot({ type: 'jpeg', quality: 90, clip: clip }).then(data => {
        resolve(data)
      })
    }, 200); // wait 200ms between every clip
  })
}
```
I added intervals between every clip, so the operation speed in Linux is slowed. After changing the source code, I tested A dozen times and the bug is gone.

I am feeling strange of this, and I think my new way is a dirty hack, I can't understand why the speed 
 too fast can make this question.

**Comment by positlabs** [comment]
My workaround was to check the image size, and re-render if it was incorrect.

Your idea about something happening too fast is consistent with how the bug manifested for me. It works mostly fine on my local machine (in a 4cpu docker container), but running on a 16 cpu vm, it happens much more often.

**Comment by RitterHou** [comment]
May I ask how to check the image size?

**Comment by positlabs** [comment]
There are various node modules that do this. Quick googling will help you

**Comment by Kenith** [comment]
try to set: `await page.setJavaScriptEnabled(false);` 
or set the chrome flags: `--blink-settings=scriptEnabled=false`
I have same issue and this works...

**Comment by aslushnikov** [comment]
@RitterHou is this still an issue? Can you please try on the latest puppeteer and see if it works.
