### ISSUE TITLE
[Bug]: Puppeteer not launching browser in Ubuntu

### ISSUE THREAD

**Issue by MoKhajavi75** [puppeteer/puppeteer#8007]
### Bug description

Steps to reproduce the problem:

1. Install Puppeteer with [pnpm](https://pnpm.io): `pnpm add puppeteer`
2. Try to launch the browser
3. Error:

```
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (961656).
```

Try with `executablePath: './node_modules/puppeteer/.local-chromium'`:

```
Error: Failed to launch the browser process! spawn ./node_modules/puppeteer/.local-chromium EACCES
```

### Puppeteer version

13.3.1

### Node.js version

v16.13.2

### npm version

I use [pnpm](https://pnpm.io)

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (961656).
```

Try with `executablePath: './node_modules/puppeteer/.local-chromium'`:

```
Error: Failed to launch the browser process! spawn ./node_modules/puppeteer/.local-chromium EACCES
```

**Comment by OrKoN** [comment]
`executablePath: './node_modules/puppeteer/.local-chromium'` is not correct: it should lead to the actual binary not the folder where the binaries are downloaded too. 

Installation using `pnpm` also worked for me on Mac. Unfortunately, I cannot test on Ubuntu but if the binary is not found in the right directory after the installation, I think you should file a bug with pnpm.

**Comment by MoKhajavi75** [comment]
> `executablePath: './node_modules/puppeteer/.local-chromium'` is not correct: it should lead to the actual binary not the folder where the binaries are downloaded too.
>
> Installation using `pnpm` also worked for me on Mac. Unfortunately, I cannot test on Ubuntu but if the binary is not found in the right directory after the installation, I think you should file a bug with pnpm.

What's the directory for binary?

**Comment by OrKoN** [comment]
@MohamadKh75 It looks like this `node_modules/puppeteer/.local-chromium/linux-961656/chrome-linux/chrome`. But it should work without specifying the executablePath. Can you try to install with npm and see if the same problem happens? Maybe download fails for some reason?

**Comment by MoKhajavi75** [comment]
> @MohamadKh75 It looks like this `node_modules/puppeteer/.local-chromium/linux-961656/chrome-linux/chrome`. But it should work without specifying the executablePath. Can you try to install with npm and see if the same problem happens? Maybe download fails for some reason?

Looks like it's fixed in 13.3.2 🤔
Thanks!

**Comment by pankajpj07** [comment]
C:\snapshot\Rose_V.4_1\node_modules\puppeteer-core\lib\cjs\puppeteer\node\Launcher.js:88
                    throw new Error(missingText);
                          ^

Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).
    at ChromeLauncher.launch (C:\snapshot\Rose_V.4_1\node_modules\puppeteer-core\lib\cjs\puppeteer\node\Launcher.js:88:27)
    at PuppeteerNode.launch (C:\snapshot\Rose_V.4_1\node_modules\puppeteer-core\lib\cjs\puppeteer\node\Puppeteer.js:125:31)
    at PuppeteerExtra.launch (C:\snapshot\Rose_V.4_1\node_modules\puppeteer-extra\dist\index.cjs.js:129:41)
    at async C:\snapshot\Rose_V.4_1\index.js

**Comment by pankajpj07** [comment]
I am getting this error. Please help me with this.

**Comment by xiaoang** [comment]
> 

i'm so sad that my  puppeteer version is  13.4.1, but my problem is also appear。

**Comment by btea** [comment]
@pankajpj07 I also encountered the same problem, have you solved it?

**Comment by nowodev** [comment]
cd ./node_modules/puppeteer
npm run install

**Comment by onyx-nxt** [comment]
> cd ./node_modules/puppeteer npm run install

didn't work for me

**Comment by hajsf** [comment]
I had the same issue:

![image](https://github.com/puppeteer/puppeteer/assets/98168280/81386540-7e04-42e2-be79-8c658e057b68)

I tried to install as requested:

```bash
cd ./node_modules/puppeteer
npm install
```

But also failed:

![image](https://github.com/puppeteer/puppeteer/assets/98168280/3c7ff334-7d64-459a-8f6e-1c74d712eafc)

But I started getting hope after installing `nodejs` using [this](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm) guide.

![image](https://github.com/puppeteer/puppeteer/assets/98168280/930a5525-4483-48c5-949d-44f87b74e551)

But I got `sh: 1: husky: Permission denied`

![image](https://github.com/puppeteer/puppeteer/assets/98168280/c11a4ada-2a6a-4f96-a0a7-818889c4c906)
