### ISSUE TITLE
[Bug]: different screenshot quality with and without plugged power source

### ISSUE THREAD

**Issue by Kreeg** [puppeteer/puppeteer#8009]
### Bug description

Steps to reproduce the problem:

1. Plug the power source
2. Save screenshot
3. Unplug the power source.
4. Save screenshot
5. Consider the difference

I am using Apple M1 Macbook Pro (and Macbook Pro 13" late 2013) and I've tried to run test (we're using screenshot testing) with notebook in my bed and magically they all stopped working. The next day on the same docked notebook they magically became green (tests succeded). Then i've tried to plug/unplug the power source.

First file (plugged) **20.65KB** 200x407, 192dpi, RGB with Alpha, Noninterlaced
![изображение](https://user-images.githubusercontent.com/1666622/153775596-32c5ad03-c219-4f62-b029-63bbbca980d0.png)

Second file (unplugged) **20.64KB** 200x407, 192dpi, RGB with Alpha, Noninterlaced
![изображение](https://user-images.githubusercontent.com/1666622/153775618-f93d87fd-3258-4ea6-ada6-96ee4cb1427e.png)

I consider that result may differ from OS to OS, but I think getting different quality screenshots on the same machine from time to time is 100% inappropriate.

### Puppeteer version

13.3.1

### Node.js version

16.13.0

### npm version

8.3.0

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
That's an interesting case. I wonder what happens when you unplug the power source? Does the laptop (or just chrome) switch to some different GPU or CPU rendering? Do you run the browser in the headless or headful mode? Is there any difference if you run with `--disable-gpu` flag?

**Comment by Kreeg** [comment]
@OrKoN I used headless mode. I can't tell if laptop switches between GPU and CPU renderer. I'll try with that flag, thank you!

**Comment by OrKoN** [comment]
Another thought: are there any animations on the page or is it completely static?

**Comment by Kreeg** [comment]
@OrKoN hello!
I've tried with `--disable-gpu` mode but the results are the same.
The page is static, there is no animations.

**Comment by OrKoN** [comment]
@Kreeg did you end up using playwright? do you have the same issue with screenshots there? I imagine it should affect all Chromium browsers.

**Comment by Kreeg** [comment]
@OrKoN yes, we switched to playwright. It was OK until the recent update. Now I need to test different chromium versions, I just need some time. I'm closing this issue, but if you want, you can follow updates on this issue https://github.com/microsoft/playwright/issues/14460 (I'll link new issue there)
