### ISSUE TITLE
Downloading PDF files using Puppeteer 

### ISSUE THREAD

**Issue by ags4436** [puppeteer/puppeteer#8010]
I am trying to download PDF files using puppeteer, when .pdf URLs are hit the chrome opens the pdf in the tab, instead I want the pdf to be downloaded. This can be achieved through changing the user-preferences of browser and  **Sites automatically follow this setting when you visit them** by default it is **Open PDFs in Chrome**.

I found that we can use puppeteer-extra for downloading the PDF files. Is that a legit NPM which I could use in my project instead of puppeteer-core ?

Is there any alternatives available from Puppeteer itself ?

**Comment by OrKoN** [comment]
I believe it should be possible to use CDP's setDownloadBehaviour https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior but there is no dedicated API in Puppeteer for this yet: 

```
await  page._client.send('Page.setDownloadBehavior', {
	behavior: 'allow',
	downloadPath: tempFolderPath,
})
```

**Comment by ags4436** [comment]
This allows us to set the download path while downloading the files. PDFs will open in the tab itself in this case as well.

**Comment by OrKoN** [comment]
I see. It looks like puppeteer-extra writes those settings into the user profile directory and to me it looks like the approach might be a bit fragile if the structure of the directory changes. But I am not aware of any other way to achieve this. Most likely, it's possible to replicate what puppeteer-extra does and create the profile with the right setting but I think using puppeteer-extra is fine too.

**Comment by MrXyfir** [comment]
Really surprised puppeteer still doesn't support this. Playwright does.

**Comment by nros** [comment]
Because of PR [8506](https://github.com/puppeteer/puppeteer/pull/8506)  (since release 14.4.0), it's not `_client` anymore but it is `_client()`. So use:
```JavaScript
await page._client().send('Page.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath: tempFolderPath,
})
```

See: [Page.ts](../blob/main/src/common/Page.ts)

**Comment by Korak-997** [comment]
I had to twick a lot till i found this solution :smile: 
but it works perfectly for me.

And Downloads the pdf automatically which means you do not need to do anything else

```js
// WAITS TILL THE OBJECT IS RENDERED
await page.waitForSelector('SELECTOR FOR PDF OBJECT')
   //SET DOWNLOAD PATH
    await page._client.send("Page.setDownloadBehavior", {
      behavior: "allow",
      downloadPath: PATH,
    })
    
  
    await page.evaluate(() => {
      const pdfObj = document.querySelector("SELECTOR FOR PDF OBJECT")
      const btn = document.createElement("a")
      btn.setAttribute("href", pdfObj.data)
      btn.setAttribute("download","FILE_NAME")
      btn.click()
      })
```

**Comment by OrKoN** [comment]
We will definitely need a better API for this.

**Comment by Kle0s** [comment]
> I had to twick a lot till i found this solution 😄 but it works perfectly for me.
> 
> And Downloads the pdf automatically which means you do not need to do anything else
> 
> ```js
> // WAITS TILL THE OBJECT IS RENDERED
> await page.waitForSelector('SELECTOR FOR PDF OBJECT')
>    //SET DOWNLOAD PATH
>     await page._client.send("Page.setDownloadBehavior", {
>       behavior: "allow",
>       downloadPath: PATH,
>     })
>     
>   
>     await page.evaluate(() => {
>       const pdfObj = document.querySelector("SELECTOR FOR PDF OBJECT")
>       const btn = document.createElement("a")
>       btn.setAttribute("href", pdfObj.data)
>       btn.setAttribute("download","FILE_NAME")
>       btn.click()
>       })
> ```

This is also not a perfect solution, since you should technically use `Browser.setDownloadBehavior` but accessing `browser._connection` does not work anymore as well (I think since release 14.4.0). Is there a way to bypass that and receive the `CDPSession` used by the browser like there is with the page (`Page._client()`)?

**Comment by Kle0s** [comment]
Do we have a plan for this feature? I will gladly take part in the implementation if this is relevant

**Comment by Kle0s** [comment]
I thought it might be more useful to have it exposed via the BrowserContext class as well, in a similar way to https://pptr.dev/api/puppeteer.browsercontext.overridepermissions. What do you think of that?

**Comment by OrKoN** [comment]
> I thought it might be more useful to have it exposed via the BrowserContext class as well, in a similar way to https://pptr.dev/api/puppeteer.browsercontext.overridepermissions. What do you think of that?

is there a use case for changing the value dynamically? I do not see one so I think it makes sense to do this when launching a browser or creating a new browser context. Currently, the WebDriver BiDi standard does not define this functionality and Puppeteer aims to be compatible with the WebDriver BiDi standard eventually, therefore, I would not add a separate setter as I feel it might not end up being specified that way in the standard.

**Comment by Kle0s** [comment]
#13309 was merged, so this one can be closed :)

**Comment by ags4436** [comment]
Thanks @OrKoN @Kle0s for making this feature live. It will be really helpful.
