### ISSUE TITLE
[Bug]: chromium use large virtual memory

### ISSUE THREAD

**Issue by zhazhaxia** [puppeteer/puppeteer#8014]
### Bug description

Steps to reproduce the problem:

1. I try to use puppeteer to launch headless chrome, to record a webGl page,and convert the page to video.
2. But, from the monitor, the mechine( linux ),warning that virtual memory increase to 160G(origin 20G).

What should I do. Is there has any way to optimize my program?

### Puppeteer version

13.3.1

### Node.js version

14.15.3

### npm version

3.10.10

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
virtual memory info

1	02-14 17:19:00	106.40G
2	02-14 17:18:00	106.40G
3	02-14 17:17:00	106.40G
4	02-14 17:16:00	106.40G
5	02-14 17:15:00	106.40G
6	02-14 17:14:00	106.39G
7	02-14 17:13:00	106.39G
8	02-14 17:12:00	106.39G
9	02-14 17:11:00	106.39G
10	02-14 17:10:00	106.39G
11	02-14 17:09:00	106.39G
12	02-14 17:08:00	106.39G
13	02-14 17:07:00	106.39G
14	02-14 17:06:00	106.39G
15	02-14 17:05:00	106.39G
16	02-14 17:04:00	240.71G
17	02-14 17:03:00	240.71G
18	02-14 17:02:00	240.71G
19	02-14 17:01:00	240.71G
20	02-14 17:00:00	240.71G
21	02-14 16:59:00	199.41G
22	02-14 16:58:00	199.41G
23	02-14 16:57:00	199.41G
24	02-14 16:56:00	199.41G
25	02-14 16:55:00	199.41G
26	02-14 16:54:00	106.40G
27	02-14 16:53:00	106.40G
28	02-14 16:52:00	106.40G
29	02-14 16:51:00	106.40G
30	02-14 16:50:00	106.40G
```

**Comment by Black2vs2** [comment]
Can you share code?

**Comment by zhazhaxia** [comment]
> Can you share code?

```js
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    args: ['--no-sandbox']
  });
  const page = await browser.newPage();
  await page.goto("https://baidu.com");
  await page.screenshot({ path: "baidu.png" });
  await page.close()
  await browser.close();
})();

```

**Comment by OrKoN** [comment]
I suggest to direct this bug report to crbug.com with as many details as possible. It does not looks like in the code you shared you are capturing the video? In any case, it's not something we can fix in puppeteer.
