### ISSUE TITLE
[Bug]: Can't control keyboard in local computer

### ISSUE THREAD

**Issue by imkrishnendu92** [puppeteer/puppeteer#8030]
### Bug description

Steps to reproduce the problem:

1. …await page.keyboard.press('ArrowLeft'); -> when I execute this code its only have control on browser page but i want to control over local computer through keyboard command. 
@OrKoN please help me to get of this problem

### Puppeteer version

13.3.2

### Node.js version

16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
keyboard.press('Enter');
  ^

ReferenceError: keyboard is not defined
    at D:\Puppeteer\test_keyboard.js:22:3
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by OrKoN** [comment]
Puppeteer is not meant to automate desktop applications. It's expected that the input events only work inside the target web page.
