### ISSUE TITLE
[Bug]: some svg in page missing in exported pdf 

### ISSUE THREAD

**Issue by rawbin-** [puppeteer/puppeteer#8033]
### Bug description

Steps to reproduce the problem:

1. get APP_URL 
- git clone https://github.com/rawbin-/chrome-webkit-svg-print-debug to APP_DIR
- run `yarn && yarn dev` in the dir and get the APP_URL
2. get SERVICE_URL
- git clone https://github.com/rawbin-/puppeteer-export-pdf-svg-blank to SERVICE_DIR
- run `yarn && yarn dev` in the dir and get the SERVICE_URL
3. visit the SERVICE_URL/api/report with param url=APP_URL
- like`curl http://localhost:3000/api/report --data-urlencode url=http://localhost:8001/index`
4. we got the `report.pdf` in the root of SERVICE_DIR
5. compare the page and the pdf exported，page with svg and pdf not(expected to be the same)

### Puppeteer version

13.3.2

### Node.js version

16.13.1

### npm version

8.5.0

### What operating system are you seeing the problem on?

macOS

**Comment by rawbin-** [comment]
same [issue for chronium](https://bugs.chromium.org/p/chromium/issues/detail?id=1298795)

**Comment by doktorfish0078** [comment]
Если у кого-то с Puppeteer пропадают изображения в pdf или скриншоте, может у вас стоит не networkidle0
У меня было так)))
```
 await page.goto(param.url, {
        //  "networkidle2" - херня, не догружаются все иконки SVG
        waitUntil: "networkidle0",
        timeout: 30000,
      });
```
