### ISSUE TITLE
[Bug]: MacOS prompts for location every time i open chromium 

### ISSUE THREAD

**Issue by mecirmartin** [puppeteer/puppeteer#8036]
### Bug description

Whenever i start chromium and try to allow page to use my location, i get popup from chromium, if i click allow, i have to set location for chromium in my Mac's system preferences...
<img width="460" alt="Screenshot 2022-02-19 at 17 52 56" src="https://user-images.githubusercontent.com/55835379/154810513-7961d1e7-2e66-4431-bda0-b50dd9daff66.png">

Outside chromium in my System preferences i have granted access for  location for chromium

My macOS is Monterey 12.2.
This is probably relevant to this issue:
https://apple.stackexchange.com/questions/411279/permanently-allow-chrome-to-access-location

### Puppeteer version

13.3.2

### Node.js version

v14.17.3

### npm version

6.14.13

### What operating system are you seeing the problem on?

macOS

**Comment by mai0li** [comment]
Have you tried loading a specific user profile (where you'd previously allow access) using `userDataDir` argument on `puppeteer.launch`? Maybe it records your allowed access preferences.

**Comment by uttu-316** [comment]
Any update on this?
