### ISSUE TITLE
changing jsHeapSizeLimit in headless chromium

### ISSUE THREAD

**Issue by mityok** [puppeteer/puppeteer#804]
i'm trying to increase jsHeapSizeLimit for the chromium browser (I'm passing quite large amount of data to it) and for some reason whatever parameter i set i launch args it's getting ignored.
I've tried setting it to 128 or 4096 but i still get 2GB when i print jsHeapSizeLimit.
launching browser with parameters works:

`/Applications/Chromium.app/Contents/MacOS/Chromium --enable-precise-memory-info --js-flags="--max-old-space-size=128"`

this is the setup i'm using:

`await puppeteer.launch({
    args: [
    "--enable-precise-memory-info",
    "--js-flags=\"--max-old-space-size=4096\""
    ]
});`

**Comment by mityok** [comment]
not sure if it's related but after adding `dumpio:true` i've got this error:
`[0917/154738.953084:ERROR:http_connection.cc(37)] Too large read data is pending: capacity=104857600, max_buffer_size=104857600, read=104857600`

**Comment by aslushnikov** [comment]
@mityok: could you please share your usage scenario?

**Comment by mityok** [comment]
i'm using puppeteer to create video recording from an html animation.
i'n order to do so i'm using json file with up to several hundreds of MB as setup data.
and sometimes the puppeteer just freezes without errors even with `env DEBUG`.
so i'm trying to figure if it's a memory issue

**Comment by vsemozhetbyt** [comment]
@mityok FWIW, but did you check the buffer and string maximums for Node.js and v8?

https://nodejs.org/api/buffer.html#buffer_buffer_constants

There may be problems with parsing big JSON files with v8:

https://github.com/nodejs/node/issues/9489
https://github.com/nodejs/node/issues/13465

**Comment by aslushnikov** [comment]
@mityok this looks like a memory issue. Did you have any progress with it?

**Comment by bruceCzK** [comment]
This is because puppeteer communicates with chromium using websocket, and in chromium core, websocket has an 256MB data size limit (seems depend on platform). So you can try launch puppeteer in `pipe` communication mode, which I think has no such limitation. I just solve a pdf exporting problem by changing the option.

**Comment by sudip10028** [comment]
getting the same problem .My usecase si I am converting a large hrml file into a pdf file.
below is my js file which took a html file and name of pdf file as input.

```js
const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

(async () => {
  try {
    if (process.argv.length < 4) {
      console.log("Usage: node generate-pdf.js input.html output.pdf");
      return;
    }
    const inputFilePath = path.resolve(process.argv[2]);
    const outputFilePath = path.resolve(process.argv[3]);

    if (!fs.existsSync(inputFilePath)) {
      console.log("Input HTML file does not exist.");
      return;
    }

    // Create a browser instance
    const browser = await puppeteer.launch({   args: ['--no-sandbox','--disable-dev-shm-usage'], pipe:true, headless: 'new', dumpio: true })

    // Create a new page
    const page = await browser.newPage();

    // Get HTML content from HTML file
    const html = fs.readFileSync(inputFilePath, 'utf-8');
    await page.setContent(html, { waitUntil: 'domcontentloaded' });

    // To reflect CSS used for screens instead of print
    await page.emulateMediaType('screen');
    await page.waitForTimeout(4000)
    // Download the PDF
    const pdf = await page.pdf({
      path: outputFilePath,
      margin: { right: '50px',  left: '50px' ,top: '10px', bottom: '10px'},
      printBackground: true,
      format: 'A3',
    });

    console.log(`PDF saved to ${outputFilePath}`);

    // Close the browser instance
    await browser.close();
  } catch (error) {
    console.error("An error occurred:", error);
  }
})();

```
I have root volume size 80 gb & /dev/shm shareable memory is 8gb.
My html file size is around 90 mb.


<img width="460" alt="Screenshot 2024-01-23 at 2 46 07 PM" src="https://github.com/puppeteer/puppeteer/assets/45460249/90f4ee72-44d5-4466-ae5f-f186668d9acf">

Too large read data is pending: capacity=104857600, max_buffer_size=104857600, read=104857600
[2697:2760:0123/091340.159676:ERROR:devtools_pipe_handler.cc(327)] Connection closed, not enough capacity
