### ISSUE TITLE
[Bug]: auth using pfx cert

### ISSUE THREAD

**Issue by ldrahnik** [puppeteer/puppeteer#8055]
### Bug description

Hello,

at first. Do not know if it is bug of pupeteer or my misunderstood or server issue. Code is used below. I try automate signing in with cert. Manualy picking cert works.

How is developed signing page via cert in frontend is mentioned on [Setting up certificate sign in in Single Page applications](https://medium.com/vzp-engineering/setting-up-certificate-sign-in-in-single-page-applications-7c88aa2f5249)

```
'use strict';

const puppeteer = require('puppeteer');
const request = require('request');
const fs = require('fs');

test();

async function test() {
    const browser = await puppeteer.launch({ headless: false, args: ['--no-sandbox','--disable-setuid-sandbox', '--ignore-ssl-errors=true'] });
    let page = await browser.newPage();

    // Enable Request Interception
    await page.setRequestInterception(true);

    // Client cert files
    const pfx = fs.readFileSync(__dirname + '/cert/cert.pfx');

    page.on('request', interceptedRequest => {
        // Intercept Request, pull out request options, add in client cert
        const options = {
            uri: interceptedRequest.url(),
            method: interceptedRequest.method(),
            headers: interceptedRequest.headers(),
            body: interceptedRequest.postData(),
            gzip: true,
            agentOptions: {
                pfx: pfx,
                passphrase: '<password>',
                securityOptions: 'SSL_OP_NO_SSLv3'
            }
        };

        // Fire off the request manually (example is using using 'request' lib)
        request(options, function(err, resp, body) {
            // Abort interceptedRequest on error
            if (err) {
                console.error(`Unable to call ${options.uri}`, err);
                return interceptedRequest.abort('connectionrefused');
            }

            // Return retrieved response to interceptedRequest
            interceptedRequest.respond({
                status: resp.statusCode,
                contentType: resp.headers['content-type'],
                headers: resp.headers,
                body: body
            });
        });
    });

    await page.goto('https://auth.vzp.cz/signin');

    const submitButtonElements = await page.$$('button[type="submit"]');

    submitButtonElements[1].click();
}
```

GET & POST `https://auth.vzp.cz/certificate/obtain` 200 OK
POST `https://auth.vzp.cz/signin/certificate`  was sent with payload certificate & certificateAuthToken but returned 500.

`{
  "code": "EG-500",
  "message": "500 Internal Server Error"
}`

Thanks a lot

Best

Lukas

### Puppeteer version

13.3.2

### Node.js version

v10.19.0

### npm version

6.14.4

### What operating system are you seeing the problem on?

Linux

**Comment by igorovisk** [comment]
Did it work?

**Comment by ldrahnik** [comment]
@igorovisk Project mentioned in my post on medium did work but I have not used the project for 2 years almost https://medium.com/@ldrahnik/headfull-puppeter-running-in-docker-without-gui-12d983e50920

**Comment by igorovisk** [comment]
Thanks, ill give it a try, Im trying to intercept the request, but I am getting and error that syas the request was already handled

**Comment by igorovisk** [comment]
Can I do it without docker?
