### ISSUE TITLE
[Bug]: Unable to Bypass Chrome's CORS policy

### ISSUE THREAD

**Issue by 3wweiweiwu** [puppeteer/puppeteer#8056]
### Bug description

Recently, Chrome change the behavior when trying to access private network. Current approach require change registry to bypass that.Is there anyway to enable private network access via puppeteer flag?

https://stackoverflow.com/questions/71018461/chrome-98-private-network-access-problem-w-disabled-web-security-request-had-n
Reference: https://developer.chrome.com/blog/private-network-access-update/

### Puppeteer version

13.4.0

### Node.js version

v16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

**Comment by 3wweiweiwu** [comment]
I think I resolved this issue. It should goes to chromium folder for chromium. Having said that, is there anyway that we can achieve this without modifying the registry?

![image](https://user-images.githubusercontent.com/14018114/155240902-c6603a9f-faac-4dfe-a181-f4be2ca39912.png)

**Comment by drizzef** [comment]
I have this issue as well.
i set my browser with the following arguments:
`const browser = await puppeteer.launch({
      headless: false,
      args: [
        '--disable-gpu',
        '--disable-dev-shm-usage',
        '--disable-setuid-sandbox',
        '--no-sandbox',
        '--disable-web-security',
        '--disable-features=IsolateOrigins',
        '--disable-site-isolation-trials',
        '--disable-features=BlockInsecurePrivateNetworkRequests',
      ],
      devtools: true,
      defaultViewport: {
        hasTouch: true,
        isMobile: true,
        height: 1080,
        width: 1920,
      },
    });`
    
    npm version: 8.3.1
    node version: v16.14.0
    Operation System: MacOS 10.15.7
    puppeteer version: 13.4.1

**Comment by Black2vs2** [comment]
Just add to the launch args
```javascript
'--disable-web-security'
```

Then make sure to do
```javascript
await page.setBypassCSP(true)
```
before entering the page where you need to bypass cors

**Comment by drizzef** [comment]
> Just add to the launch args
> 
> ```js
> '--disable-web-security'
> ```
> 
> Then make sure to do
> 
> ```js
> await page.setBypassCSP(true)
> ```
> 
> before entering the page where you need to bypass cors

works like a charm! thx!

**Comment by raphaellueckl** [comment]
For everyone not getting it, this is what you need:

```js
  const browser = await puppeteer.launch({
    args: ["--disable-web-security"],
  });
```
