### ISSUE TITLE
[Bug]: Chromium browser got crashed while using tracing.start in M1 MacBook Pro(2021) 

### ISSUE THREAD

**Issue by raviregina** [puppeteer/puppeteer#8058]
### Bug description

Steps to reproduce the problem:

1. Launch the chromium browser
2. Call **page.tracing.start({ path: 'trace.json' });**
3. Go to some random url

Finally the browser thorws the error like in below screenshot.

<img width="1198" alt="Screenshot 2022-02-23 at 4 39 48 PM" src="https://user-images.githubusercontent.com/41115011/155308345-56042c33-a678-40bd-8179-5d0569b05061.png">

### Puppeteer version

13.3.2

### Node.js version

16.13.2

### npm version

8.1.2

### What operating system are you seeing the problem on?

macOS

**Comment by spankyed** [comment]
Still an issue.

**Comment by sanelen** [comment]
still an issue
