### ISSUE TITLE
[Bug]: Undocumented breaking behavior for userDataDir between puppeteer v11.x and >= 12.x

### ISSUE THREAD

**Issue by vladfrangu** [puppeteer/puppeteer#8059]
### Bug description

An undocumented (in the changelog) breaking change was done between v11 and v12, where you must now ensure that the folder you point userDataDir to is created, which feels like a regression.

Steps to reproduce the problem:

1. Provide an absolute value to userDataDir to a folder that doesn't exist

Expected result:

It launches chrome pointing at that data directory and the folder gets autogenerated 

Actual result:

An fs error related to the folder not existing is thrown instead, which goes against what the chrome binary does (which is generating the folder for the user)

### Puppeteer version

13.4.0

### Node.js version

v16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Thanks for the report. It looks like a regression slipped in with Firefox related changes around user-data-dir: https://github.com/puppeteer/puppeteer/pull/7684

**Comment by vladfrangu** [comment]
Thanks! As this was fixed (and released), I'll close the issue :D
