### ISSUE TITLE
[Bug]: Proxy server and createIncognitoBrowserContext does not work on Windows after 10.2

### ISSUE THREAD

**Issue by iJoris** [puppeteer/puppeteer#8065]
### Bug description

Run the following code on Windows 10 on puppeteer 10.2 and a version later than 10.2.

```
(async () => {
const browser = await puppeteer.launch({
    args: [
        "--proxy-server=" + "http://127.0.0.1:2991"
    ],
    headless: false
});

const context = await browser.createIncognitoBrowserContext();

const page = await context.newPage();

await page.goto('https://www.whatismyip.org/');

await new Promise(() => {
    setTimeout(() => {
      //resolve();
    }, 1000000);
  });
})();
```

Seems that the proxy get's ignored in the newest versions when using an incognito browsercontext.

Seems that this is the same issue: https://github.com/puppeteer/puppeteer/issues/7589#issuecomment-927182049

### Puppeteer version

13.4

### Node.js version

16.4

### npm version

8.3.1

### What operating system are you seeing the problem on?

Windows

**Comment by anjackson** [comment]
I think this is [fixed in versions 13.5.0 and up](https://github.com/puppeteer/puppeteer/commit/3feca325a9472ee36f7e866ebe375c7f083e0e36). Works for me with 14.4.1.

**Comment by zasnool** [comment]
createIncognitoBrowserContext() ignores proxyServer argument. Although I am not sure if the proxy should be set for the parent(not incognito) browser. I thought that you could set a different proxy individually for each (incognito)context.

**Comment by OrKoN** [comment]
Looks like this has been fixed. The problem with proxyServer in createIncognitoBrowserContext() is a different one and there is a known issue when it does not work on Windows (https://crbug.com/1310057).
