### ISSUE TITLE
[Bug]: Error when parsing page to PDF: ProtocolError: Protocol error (Page.printToPDF): Printing failed

### ISSUE THREAD

**Issue by sefasenturk95** [puppeteer/puppeteer#8070]
### Bug description

I am trying to generate a pdf from a big html file with lots of images. The HTML file itself is 15MB and the total amount of images it is trying to load is ~500MB. When trying this on my local machine it works. But when trying to execute the script in a lambda or as a Docker container it outputs this error constantly.

Steps to reproduce the problem:

1. Build the docker image. You can find my Dockerfile: https://gist.github.com/sefasenturk95/0eb0f4feead25c236e059b5afd18f75a and the code that I'm running here: https://gist.github.com/sefasenturk95/cc85f18aa53bf56c816a5b12cd9ec04f
2. Run the docker image
3. After a while the script stops and outputs the error.

### Puppeteer version

13.4.0

### Node.js version

14.16.1

### npm version

6.14.12

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
➜  pdf-gen git:(develop) ✗ docker run pdf-gen
{"level":30,"time":1645893676687,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"starting puppeteer"}
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[0226/164117.009189:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0226/164117.009584:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:45607/devtools/browser/95372895-7025-4e0c-9b2b-d3d2aaffc70a
[0226/164117.038525:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
{"level":30,"time":1645893677087,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"done starting puppeteer"}
{"level":30,"time":1645893677087,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"new page"}
[0226/164117.104284:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
{"level":30,"time":1645893677153,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"done new page"}
{"level":30,"time":1645893677153,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"emulate media type"}
{"level":30,"time":1645893677154,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"done emulate media type"}
{"level":30,"time":1645893677154,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"go to page"}
{"level":30,"time":1645893702349,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"done go to page"}
{"level":30,"time":1645893702350,"pid":8,"hostname":"5200a5499cd2","name":"app-name","msg":"generate pdf"}
(node:8) UnhandledPromiseRejectionWarning: ProtocolError: Protocol error (Page.printToPDF): Printing failed
    at /node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
    at Page.createPDFStream (/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2074:50)
    at Page.pdf (/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2103:37)
    at /index.js:77:20
    at Generator.next (<anonymous>)
    at fulfilled (/index.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by smilingleo** [comment]
I encountered the same issue, is there any workaround to print large HTML files to PDFs?

And in my case, the HTML doesn't contain any image, just a huge `<table>` with 500K `<tr>`

### Sample HTML Table

```
<table>
    <tr>
        <td>0</td>
        <td>0</td>
        <td>2022-03-25T08:19:57.434</td>
        <td>41b03d4b-c20b-44a0-b0c2-aeb8797575c6</td>
        <td>eb517af1-afd7-4dcf-82ad-e479c36a9ed8</td>
        <td>ac5239cb-cde2-4e9d-a5a5-f92a248047c1</td>
    </tr>
    ...
</table>
```

### 100K rows

| Tables | Rows Per Table | Columns Per Row | HTML File Size | PDF File Size | Execution Time |
| --- | --- | --- | --- | --- | --- | 
| 1 | 100,000 | 3 | 9.4Mb | 143Mb | 7:04 min |
| 2 | 50,000 | 3 | 9.4Mb | 143Mb | 4:21 min |
| 10 | 10,000 | 3 | 9.4Mb | 143Mb | 2:26 min |
| 100 | 1,000 | 3 | 9.4Mb | 143Mb | 2:06 min |
| 1 | 100,000 | 6 | 19Mb | 276Mb | 10:15 min |

### 150K rows

Tables | Rows Per Table | Columns Per Row | HTML File Size | PDF File Size | Execution Time
---|---|---|---|---|---
30 | 5,000 | 3 | 14Mb | 216Mb | 3:29 min
15 | 10,000 | 3 | 14Mb | N/A | 
30 | 5,000 | 6 | 29Mb | N/A | Failed after 2:15 min

### 250K rows

Tables | Rows Per Table | Columns Per Row | HTML File Size | PDF File Size | Execution Time
---|---|---|---|---|---
50 | 5,000 | 3 | 24Mb | N/A | Failed after 2:04 min
250 | 1,000 | 3 | 24Mb | N/A | Failed after 1:59 min

From above, we can roughly tell:

* the size of a single HTML element (`table` in this case) impacts the execution time.
* `Page.printToPDF` starts failing when the total row number increased to about 150K.

**Comment by sefasenturk95** [comment]
Hey @smilingleo, this problem is still very much limiting our ability to create a big pdf in one go. It is too slow on one hand when the html file is big and on the other hand like you say when the html file gets too big I get this error. 

We ended up counting our table rows and splitting them in multiple html files. For us the sweet spot was like 500 table rows per html file.. But we are still playing and experimenting with it. After the the generation of multiple pdf's we merge all the pdf's into one. This really improved our performance. A downside is that on the last page of every sub-pdf you can have some white space because you are merging multiple pdf's..

**Comment by shibumi-bangera** [comment]
I was running into the same problem and reverted to an older version of Puppeteer. I have not extensively tested the versions but 10.4.0 works for the table sizes I'm working with.

**Comment by kevinbeal** [comment]
This happened to me when I (unintentionally) closed the page prior to finishing the PDF conversion. (I forgot to `await` the `.pdf()` call).

**Comment by simonc** [comment]
This is still an active issue.

On our side (running on Lambda) it seem to happen frequently when our users load pages that contain more than 50MB of images. I don't have an exact number regarding the tota  weight or the number of images, but we do see it freqently.

At least a more accurate error message would be useful 🙂

**Comment by liaddrori1** [comment]
This is working for me on my local machine ( which is linux) 
but don't work on docker
any one was able to slove this?

**Comment by fbiayna** [comment]
In our case, is not working running on Cloud Run.

We did some tests where all resources were increased (more RAM, CPU...) and so increasing the memory requests and limits, but the problem is persisting...

Is there any news related to this bug? Anyone who could solve this?

**Comment by phu-dangn-otsv** [comment]
I got the same issue when printing the huge report. Any solution until now?

**Comment by joe455** [comment]
We are facing same issue printing large reports. Anyone have solution for this?

**Comment by simonc** [comment]
@abhinehra Hi. Nope, still very much an issue for us.

**Comment by abhinehra** [comment]
Hi @simonc thanks for the reply

I have solved this by using **chrome-aws-lambda** module,
the issue is generating only when I use **puppeteer.connect** , I belive it is not using its all feature when used in this way.

I tried to used puppeteer.launch but as we are running on lambda function it has some limitation

so I use **chrome-aws-lambda** npm module which is kind of wrapper around puppeteer and provide all the function need for **puppeteer.launch**  funciton.

if you are also using the puppeteer on lambda function then try to use this module,
 its almost same you don't need to change anything.
and I one more thing try to test it on aws lambda as it only work on aws lambda for me not on my local

**Comment by jonyjalfon94** [comment]
Any update on this issue?

I'm also facing this bug with large HTML files

**Comment by abhinehra** [comment]
@jonyjalfon94 try to use puppeteer.launch or if your funciton is on lambda then try to use chrome-aws-lambda

**Comment by vidya-hub** [comment]
I am also facing the same issue with large no of data like more than 1000 table records (Rows)

**Comment by apexdodge** [comment]
I found an old docker container from a year ago and it works on a payload that is failing today. So the bug must have been introduced in the last year some time. In the mean time I'll use my old container.

**Comment by brombomb** [comment]
@apexdodge 
> I found an old docker container from a year ago and it works on a payload that is failing today. So the bug must have been introduced in the last year some time. In the mean time I'll use my old container.

Any insight in to what changed in your docker image?

**Comment by aovcina** [comment]
Hi folks, did any manage to fix stated issue?

**Comment by aovcina** [comment]
Not sure if you guys have tried the latest released versions (<3). I've succeeded in generating about 350+ pages of pretty complex table data, which raw HTML data results in 800+ thousands of DOM Nodes.

@OrKoN, would you mind me expanding **[docker](https://github.com/puppeteer/puppeteer/tree/main/docker)** directory, with examples for building Node application, instead of just Puppeteer's instance? Also, may consider including a **tini** script for killing zombie processes.

**Comment by vmarksabelita** [comment]
> chrome-aws-lambda

are you running on AWS Lambda or Docker container, can you please provide your chromium npm version and puppeteer version ?

**Comment by Adeloyd** [comment]
Unable to print html file larger than 1Mb. This is a bug in Chrome for Testing version 114.0.5735.90. If you take Chromium 116.0.5834.0, then everything works.

**Comment by Adeloyd** [comment]
> @Adeloyd how did you make puppeteer to work with this version? It's too new and not supported yet. Checked here https://github.com/puppeteer/puppeteer/blob/main/versions.js

You can download the desired version of Chromium and run it through the puppeteer. Not on the list doesn't mean it won't work. This means it has not been tested on this version of chromium.

**Comment by Janka55** [comment]
> > @Adeloyd how did you make puppeteer to work with this version? It's too new and not supported yet. Checked here https://github.com/puppeteer/puppeteer/blob/main/versions.js
> 
> You can download the desired version of Chromium and run it through the puppeteer. Not on the list doesn't mean it won't work. This means it has not been tested on this version of chromium.

I try to use Chromium 116.0.5834.0 to print html file, however it also failed. My html contains 200+ images that load ~2g.

**Comment by JavaScriptDude** [comment]
That is massive. Did you try doing it by hand to see the resulting size?  This does not sound like a pypeteer bug. There may be more efficient ways of generate such a huge PDF. Back in the 2001 I generated such PDFs using VBA with over a thousand pages and hundreds of images by staging through postscript. Size was never an issue.

**Comment by Adeloyd** [comment]
[Janka55](https://github.com/Janka55)
If chrome prints your html in windowed mode, then the puppeteer should. Where can i see your file?

**Comment by rodrigoaguilera** [comment]
I found this error and tracked it down to a CSS line:
```css
  background: radial-gradient(closest-side, white 80%, transparent 80% 100%), conic-gradient(var(--progress-color) calc(var(--progress-value) * 1%), var(--progress-color-bg) 0);
```

Silly me I didn't try to print the page in PDF on a desktop browser before running puppeteer. On a desktop browser the gradients where ignored. 

I'm aware that there is some chromium bugs involved to be able to print gradients on PDFs but on the puppeteer side it would be a great addition to be able to mimic the desktop behaviour of just printing the PDF with errors. I think the error is more visual that way instead of the ProtocolError.

**Comment by Janka55** [comment]
> [Janka55](https://github.com/Janka55) If chrome prints your html in windowed mode, then the puppeteer should. Where can i see your file?

Sorry, my file contains lots of private information, I can't provide it to you. What is windowed mode? Do you mean non-headless mode? I have set ```headless: true``` to launch my broswer.

**Comment by shunkica** [comment]
I am encountering this issue when trying to create a PDF from a 40000 row table (the html file is about 6Mb)
The program crashes about 15 seconds into execution with this error:

```
kernel: traps: chromium-browse[58189] trap invalid opcode ip:55fe01295dfd sp:7fff902c7120 error:0 in chromium-browser[55fe01249000+a5fc000]
systemd[1]: Started Process Core Dump (PID 58231/UID 0).
systemd-coredump[58232]: Resource limits disable core dumping for process 58189 (chromium-browse).
systemd-coredump[58232]: Process 58189 (chromium-browse) of user 2038 dumped core.
systemd[1]: systemd-coredump@12-58231-0.service: Succeeded.
node[58111]: ProtocolError: Protocol error (Page.printToPDF): Printing failed
node[58111]:    at <instance_members_initializer> (/opt/html2pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:96:14)
node[58111]:    at new Callback (/opt/html2pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:100:16)
node[58111]:    at CallbackRegistry.create (/opt/html2pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:32:26)
node[58111]:    at Connection._rawSend (/opt/html2pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:91:26)
node[58111]:    at CdpCDPSession.send (/opt/html2pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:78:33)
node[58111]:    at CdpPage.createPDFStream (/opt/html2pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:820:63)
node[58111]:    at CdpPage.pdf (/opt/html2pdf/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:847:37)
node[58111]:    at html2pdf (/opt/html2pdf/html2pdf.js:30:28)
node[58111]:    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node[58111]:    at async /opt/html2pdf/server.js:20:25

```

For comparison, `wkhtmltopdf` successfully converts this html to pdf in about 16 seconds.

**Comment by bipinkh** [comment]
anyone found a fix? i have the same issue!

**Comment by shunkica** [comment]
> anyone found a fix? i have the same issue!

There is no fix, browsers are bad at converting large html files to pdf.

**Comment by MrLugh** [comment]
puppeteer@19.7.0
node@18.18.2

`ProtocolError: Protocol error (Page.printToPDF): Printing failed
    at /usr/src/app/node_modules/puppeteer-core/src/common/Connection.ts:400:16
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/usr/src/app/node_modules/puppeteer-core/src/common/Connection.ts:396:12)
    at CDPPage.createPDFStream (/usr/src/app/node_modules/puppeteer-core/src/common/Page.ts:1515:46)
    at CDPPage.pdf (/usr/src/app/node_modules/puppeteer-core/src/common/Page.ts:1549:33)`

**Comment by OrKoN** [comment]
Reading over comments, there are multiple issues here:

1) make sure you await the pdf call and do not close the browser too early.
2) make sure the browser has sufficient memory and cpu, especially, if the generation works locally but not working once deployed to a different environment.

If after that you get a Protocol error (Page.printToPDF): Printing failed please file an issue for Chrome at https://crbug.com and include the HTML page it fails to print. Also, please try printing to PDF using the regular print dialog in the desktop chrome.

**Comment by Eriktse** [comment]
I'm facing this issue, too, I feel confused, sorry.

**Comment by jeremiascBTS** [comment]
> I increased the memory requests and limits of the pod and was able to render A large HTML with big tables

Still having the same problem, it takes a few weeks but sooner or later it starts returning a timeout in every request. When we deploy again is fixed until next weeks

**Comment by zza19900808** [comment]
i'm facing the same issue ,now i am preparing to split the page into multiple pdfs and then merge them

**Comment by ccottingham-presinet** [comment]
I am having the same issue.
 basic table w  approx 40k rows each with 9 column

**Comment by ericky0** [comment]
i had a file with 316 pages and this solved my problem

thank me later ✌️

`
    const pdfChunks = await this.generatePDFInChunks({
      pagesChunk: 60,
      browser,
      options,
      fileName,
    });

    return this.mergePDFChunks(pdfChunks);
`

`
  async generatePDFInChunks(config: GeneratePDFInChunksConfig) {
    const { browser, pagesChunk, options, fileName } = config;

    const pdfChunks: Uint8Array[] = [];

    const firstLoadPage = await this.openPage(browser, fileName);

    const totalPages = await this.getTotalPages(firstLoadPage);

    for (
      let currentPage = 1;
      currentPage <= totalPages;
      currentPage += pagesChunk
    ) {
      // avoid extra load
      const page =
        currentPage === 1
          ? firstLoadPage
          : await this.openPage(browser, fileName);

      await page.setViewport({
        width: 720,
        height: 1200,
        deviceScaleFactor: 1,
      });

      const endPage = Math.min(currentPage + pagesChunk - 1, totalPages);

      const pdfBuffer = await page.pdf({
        ...options,
        pageRanges: `${currentPage}-${Math.min(endPage, totalPages)}`,
      });

      pdfChunks.push(pdfBuffer);

      await page.close();
    }

    await browser.close();

    return pdfChunks;
  }

  async mergePDFChunks(pdfChunks: Uint8Array[]) {
    const mergedPdf = await PDFDocument.create();

    for (const chunk of pdfChunks) {
      const pdf = await PDFDocument.load(chunk);
      const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
      copiedPages.forEach((page) => mergedPdf.addPage(page));
    }

    return mergedPdf.save();
  }


  getTotalPages(page: Page) {
    return page.evaluate(() => {
      const bodyHeight = document.body.scrollHeight;
      const pageHeight = 1200;
      return Math.ceil(bodyHeight / pageHeight);
    });
  }

  getPageConfig(fileName: string) {
    const url = `file://${PATH_DATAFILES}html/${fileName}.html`;
    const goToOptions: GoToOptions = {
      waitUntil: 'networkidle0',
      timeout: 0,
    };

    return { url, goToOptions };
  }

  async openPage(browser: Browser, fileName: string) {
    const { goToOptions, url } = this.getPageConfig(fileName);

    const page = await browser.newPage();

    await page.goto(url, goToOptions);

    return page;
  }
`

**Comment by sandilya-45** [comment]
I am trying to move a legacy code that does Page.pdf(). The legacy code was written in `Puppeteer version 18.2.1`. I am facing same protocol error issue & i tried with 22.9.0, 23.0.0, 23.5.0, 24.0.0 & 24.4.0. Can someone help me in identifying the issue please? Thank you.

**Comment by CallMeLaNN** [comment]
I have a **small** img src `data:image/png;base64,...` with a single pixel in it and plenty of RAM for an empty HTML content.

Tested on:
- Previous version: v23.3.1 (2025-03-03) with Chrome/133.0.6943.141 OK
- Latest version: v24.4.0 (2025-03-05) with Chrome/134.0.6998.35 Crash with error as per this title

Latest v24.4.0 exactly makes **no** image is possible in PDF header.

Reproduce:
- Add small base64 data in image src in `headerTemplate`. e.g.
   ```html
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="test" />
   ```
- `page.setContent()` with just basic HTML hello world.

This should be reopen for tracking upstream chrome.

Since the latest version, any image on PDF header is impossible.

**Comment by anass01** [comment]
`puppeteer.launch({headless: true,args: ['--no-sandbox']});` fixed the issue for me
