### ISSUE TITLE
[Bug]: page.cookies() get empty

### ISSUE THREAD

**Issue by zzzgit** [puppeteer/puppeteer#8077]
### Bug description

Steps to reproduce the problem:

1. const cookie = await evo_page.cookies() // got []
2. const cookie = await evo_page.evaluate(()=>document.cookie) // got correctly

what's the difference?

### Puppeteer version

newest

### Node.js version

16

### npm version

8.4.0

### What operating system are you seeing the problem on?

macOS

**Comment by Black2vs2** [comment]
```javascript
evo_page.cookies()
```
returns only the page cookies

```javascript
evo_page.evaluate(()=>document.cookie)
```
does return 3rd party too
