### ISSUE TITLE
Page.setExtraHTTPHeaders has no effect

### ISSUE THREAD

**Issue by michaeljho** [puppeteer/puppeteer#808]
`page.setExtraHTTPHeaders(headers)` does not have any effect in version 0.10.2. Works as expected in 0.10.1.

**Comment by ebidel** [comment]
The `headers` arg changed from being an Map to an Object in 0.10.2. Check that you're using the updated signature.

https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#pagesetextrahttpheadersheaders

**Comment by michaeljho** [comment]
Hi Eric,

Thanks for that -- I didn't think to double check the signature. Confirmed working with 0.10.2 now after adjusting on my end. Sorry for the noise.

-M
