### ISSUE TITLE
Puppeteer Freezes Forever With No Error

### ISSUE THREAD

**Issue by DilipSingh06** [puppeteer/puppeteer#8084]
We are using puppeteer to log into our application URL and take a screenshot as per requirement for a particular selector. This flow we are testing as a part of load testing where we are serving almost 100 requests, 3 at a time. Once these 3 requests are finished then the other 3 requests are served. This process continues till all the requests are not completed. We are having a node setup with a master process and 4 child processes. Child processes are responsible for serving the requests.

This works perfectly fine for some 40-50 requests and sometimes even for 90 requests. After that the puppeteer freezes at different different positions, sometimes at page.evaluate, sometimes at page.waitForNavigation and thereafter does not perform any operation and neither gives any error nor gets timed out. Ideally its expected to timeout after 30 seconds which is the default timeout but even that does not happen.

We were using low version of puppeteer, v1.8.0. We thought it might be fixed in the latest versions of puppeteer so we upgraded to the latest version which is v13.4.1, still the issue is reproducible.

**Tell us about your environment:**

- Puppeteer version: 13.4.1
- Platform / OS version: Windows
- Node.js version: 12.16.1

**What is the expected result?**
- Its expected that the puppeteer should not freeze and it should serve all the requests properly, if by chance some application is not loaded within the specified then it should get timed out or give some error, rather than hanging forever.

Is anyone else facing this kind of issue. If yes then what was the reason and how were you able to resolve that?

Note : Its not an issue with the application URL, it could be reproducible even with some general URL like www.google.com

**Comment by Junyan** [comment]
Can you provide a reproducible example?

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.
