### ISSUE TITLE
Consolidate best practices in Docker section of troubleshooting document 

### ISSUE THREAD

**Issue by pwnall** [puppeteer/puppeteer#809]
The Docker section in [puppeteer/docs/troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) suggests some undesirable flags. Instead, please consider recommending better solutions found by the community.

- [x] https://github.com/jessfraz/dockerfiles/blob/master/chrome/stable/Dockerfile shows how to set up a dedicated `chrome` user, so sandboxing can remain on
- [x]  https://github.com/c0b/chrome-in-docker/issues/1 documents that setting up a larger `/dev/shm` size can help eliminate crashes when rendering large pages.
  * Current fix: in the `docker run` add `--shm-size=1gb`

Thank you!

**Comment by ebidel** [comment]
Thanks for the suggestions. We'll add the `chrome` user. For some reasons, I recall that not fixing the `--no-sandbox` issues but will check again.

For `/dev/shim`, unfortunately it looks Google Cloud doesn't allow you to customize the `docker run` command. At least, I couldn't find anything. Also not sure about other cloud container platforms. The [fix is to add a flag in headless Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=736452).

**Comment by ebidel** [comment]
To follow up on the `chrome` user...it looks like it does work without `--no-sandbox` on Google App Engine Flex! However after some research, running the container from the CLI needs `docker run --cap-add=SYS_ADMIN` to account for usernames.

**Comment by hbakhtiyor** [comment]
also don't forget font issues at docker container

**Comment by ebidel** [comment]
The published Dockerfile doesn't give me any font errors. That may be specific to using other base images?

**Comment by hbakhtiyor** [comment]
not errors, but displays different compare without docker

**Comment by Garbee** [comment]
Yes, because fonts are entirely os dependent. And containers are very minimal. So they will of course be different, just like rendering in all 3 major desktop platforms are each different in subtle ways.

**Comment by aslushnikov** [comment]
@ebidel also, using [dumb-init](https://github.com/Yelp/dumb-init) in docker should help for proper chrome termination (see https://github.com/GoogleChrome/puppeteer/issues/615)

**Comment by davidwindell** [comment]
Also, a suggestion to save on disk space if using the built-in Chrome binary, only install the required deps of `google-chrome-unstable` and not the ~50mb package itself:

`apt-get install -y $(apt-cache depends google-chrome-unstable | awk '/Depends:/{print$2}') --no-install-recommends`

To save a bunch more disk space, the RUN commands should be merged into one to avoid the extra layers (especially from the chown)

**Comment by aslushnikov** [comment]
Does anyone want to take care of this? cc @ebidel

**Comment by ebidel** [comment]
@davidwindell https://github.com/GoogleChrome/puppeteer/pull/1235 adds more Docker info and a tips section. Feel free to send a PR with that suggestion as an additional tip.
