### ISSUE TITLE
[Bug]: Property 'value' does not exist on type 'Element'.ts(2339)

### ISSUE THREAD

**Issue by zzzgit** [puppeteer/puppeteer#8097]
### Bug description

Steps to reproduce the problem:

1. in ts project
2. `await page.$eval('input#OTP-1', (el, value) => el.value = value, "pwd")`
3 got lint error: `Property 'value' does not exist on type 'Element'.ts(2339)`

### Puppeteer version

newest

### Node.js version

16

### npm version

8.4.0

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
You need to cast the generic element as HTMLInputElement. Otherwise, TS does not know which element is returned by the eval.
