### ISSUE TITLE
[Bug]: PDFs now include tags by default since version 11.0.0

### ISSUE THREAD

**Issue by rossgp** [puppeteer/puppeteer#8100]
### Bug description

Not a bug but a request to update docsto highlight this change that's not mentioned in the Change log 
Steps to reproduce the problem:

1. … Generate a large HTML - I was testing with one resulting 539 pages once converted to PDF.
```
const browser = await puppeteer.launch({});
const page = await browser.newPage();
await page.goto('/tmp/test.html', { waitUntil: 'networkidle0'});
const pdfConfig =  {  printBackground: true,  format: 'A4',  path: '/tmp/202224-3829867-1lzcb4v.zeix.pdf' }
await page.pdf(pdfConfig);
await browser.close();
```

Prior to version 11.0.0 (10.4.0) this was producing a 1.5Mb file. In version 11.0.0 this resulted in a 45.7Mg file.

The source of the difference was this pull [5337](https://github.com/puppeteer/puppeteer/pull/5337) that landed in 11.0.0.

Agree this is a sensible default to support accessibility via tags, but perhaps could have had a corresponding update to the [Changelog](https://github.com/puppeteer/puppeteer/blob/main/CHANGELOG.md)

Once I found this I was able to disable this default using ignoreDefaultArgs options:

`const browser = await puppeteer.launch({ignoreDefaultArgs : ['--export-tagged-pdf']})`

If nothing else hope this issue helps saves others some time :)

Cheers,
Ross

### Puppeteer version

11.0.0

### Node.js version

16.3.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Linux

**Comment by imuller** [comment]
@rossgp We added the ignoreDefaultArgs attribute with the `--export-tagged-pdf` option but nothing happens. The pdf-file still adds the tags. Do you have any idea why this happens?

**Comment by lostsource** [comment]
> @rossgp We added the ignoreDefaultArgs attribute with the `--export-tagged-pdf` option but nothing happens. The pdf-file still adds the tags. Do you have any idea why this happens?

Try adding `--disable-pdf-tagging` when launching Chromium. 

https://source.chromium.org/chromium/chromium/src/+/main:headless/lib/switches.cc;l=40;drc=5c24012fd8a558a9c0686b98ba34d253527ce904
