### ISSUE TITLE
[Bug]: Sandbox setup failing on arm64

### ISSUE THREAD

**Issue by dmzobel** [puppeteer/puppeteer#8101]
### Bug description

Steps to reproduce the problem:

1. We build and run our Puppeteer test environment using Docker
2. My Dockerfile is essentially a combination of `apt-get install`ing the Debian dependencies [listed here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) in addition to `apt-get install chromium`, followed by the sandbox setup instructions [listed here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox)
3. Historically, we've relied on the ["alternative" sandbox setup](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#alternative-setup-setuid-sandbox) using x86 architecture. However, we are trying to use arm64 machines, and the Docker build fails at the `chown root:root chrome_sandbox` step because the directory does not exist. In fact, `node_modules/puppeteer/.local-chromium` is an empty directory on arm64.
    * Note: The ["recommended" sandbox setup](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#recommended-enable-user-namespace-cloning) does not work for us; it fails with this error on both x86 and arm64: `sysctl: setting key "kernel.unprivileged_userns_clone": Read-only file system`
4. I've tried removing the sandbox setup completely, but then the Puppeteer tests fail to execute with this error: `Error: Failed to launch the browser process! [0304/141411.012105:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox!`

A few other things to note:

- `chromium-browser` has no installation candidate
- We do not follow the example Dockerfile in the [Docker instructions](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) because `Package 'google-chrome-stable' has no installation candidate`
- We have _not_ tried using `--no-sandbox` because it is strongly discouraged

So my questions are:
- Is there a way to setup the sandbox on arm64 arch? Or is `--no-sandbox` the only option for running on arm64?
- Are there workarounds for installing `chromium-browser` or `google-chrome-stable`?
- Is the error generated by following the [recommended sandbox instructions](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#recommended-enable-user-namespace-cloning) (shown above) commonly encountered, or is this possibly unique to my environment? And if the error is common, do the setup instructions need to be updated? Here's the error again: `sysctl: setting key "kernel.unprivileged_userns_clone": Read-only file system`

### Puppeteer version

10.4.0

### Node.js version

14.9.0

### npm version

6.14.16

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by Bloodsucker** [comment]
I had the same issue but I've managed to solve it following the instructions I've added to my own asnswer in StackOverflow: https://stackoverflow.com/a/71452266/1604261

> We have not tried using --no-sandbox because it is strongly discouraged

The `--no-sandbox` is about secure access to URL outside of a controlled environment, from what I've understood from the documentation. So as long as you do that you should be just fine. But I agree this is a silly issue that should be corrected by the team.

**Comment by jaschaio** [comment]
This issue still exists and as far as I can see nobody has actually tried to confirm it but several people have run into this

**Comment by nimas0** [comment]
having same issue. trying to run on mac m1 with arm64 docker image

**Comment by OrKoN** [comment]
Puppeteer currently does not offer binaries for arm64 and so it can only use the binaries installed by the OS (how exactly to install the chromium/chrome package and if at all it's available for a given distro/docker image depends on that). I don't think we will be able to anything else except improving the documentation around arm64. If you believe there is an issue with  the `--no-sandbox` flags consider opening an issue at crbug.com.
