### ISSUE TITLE
A certain site does not open (403 https Forbidden)

### ISSUE THREAD

**Issue by DanLudan** [puppeteer/puppeteer#8104]
Vie puppeteer emulator, site m.ligastavok.ru and www.ligastavok.ru do not open with  http error 403, what could be the problem?

Check my code:

`const puppeteer =require("puppeteer");`

`async function start() {`
     `const browser = await puppeteer.launch({ headless: false });`
     `const page = await browser.newPage();`

  `await page.goto("https://www.ligastavok.ru/");`
`}`
`start();`

**Comment by OrKoN** [comment]
It looks like the problem with the site, not with Puppeteer.

**Comment by afzdev13** [comment]
you can set the user Agent like this:
```js
  await page.setUserAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36")
```

in example i put a fixed agent but you also can use a random agent with the lib user-agents [https://www.npmjs.com/package/user-agents](url) and set like this:

```js
  await page.setUserAgent(userAgent.random().toString())
```
