### ISSUE TITLE
[Bug]: Default font fallback on GCF not working well when font glyph missing.

### ISSUE THREAD

**Issue by AlexTinyTap** [puppeteer/puppeteer#8109]
### Bug description

Hey there,
I'm trying to screenshot a webpage that uses Arabic fonts in it and I noticed that some fonts aren't rendered properly - it seems to be fallback to 'monospace' font instead of the default font set in page (Arial, sans-serif) (in css).

I tried to reproduce it with different fonts and languages - but it seem to be specific to fonts that miss Arabic glyphs in them (Varela Round for example)

When I try to screenshot the same page on my local env it works well, same with chromium headless screenshot - but not with Google's Cloud Function Puppeteer.

You can check the live page I try to screenshot here:
https://staging.tinytap.it/community/creator/slideRender/5289688/c08b18e0-8a79-11ec-89f3-030ff1f299ec/photo1/
(or manual screenshot here: ![Screenshot](https://user-images.githubusercontent.com/69107225/157039968-a675ad49-4ea5-4210-b407-36844c4ef9a1.png)
)

while the image I get from puppeteer is:
![photo1/full.jpg](https://storage.googleapis.com/staging.tintap-creator.appspot.com/games/c08b18e0-8a79-11ec-89f3-030ff1f299ec/photo1/full.jpg?ts=1646643929918kj87l)

**What is the expected result?**
the image should render all the fonts exactly as they are on frontend - if it fail > render default font from css (not monospace)

**What happens instead?**
some of the fonts in the page don't support Arabic glyphs so it fallback to monospace chrome instead of the "Arial"/'sans-serif' fonts that I fallback the page to.

I think it may be connected to this issue, but I really not sure:
https://github.com/puppeteer/puppeteer/issues/4086

here is my screenshot code:

```
const getScreenshot = ({ userId, gameId, slideId, opts }: { userId: string, gameId: string, slideId: string, opts?: any }) =>
    F.tryP(() => puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        defaultViewport: {
            width: 1024,
            height: 768
        }
    })
        .then(async browser => {
            const url = '${PathNames.createAppBase}/slideRender/${userId}/${gameId}/${slideId}';
            console.log(url);
            const page = await browser.newPage();
            await page.goto(url, {
                waitUntil: "networkidle0"
            });

            await page.evaluateHandle("document.fonts.ready");
            await page.waitFor(() => !!document.querySelector('.stage-children'));
            const imageBuffer = await page.screenshot(opts != null ? opts : {
                type: "jpeg",
                quality: 90
            });
            await browser.close();
            return imageBuffer
        })) as FutureInstance<any, any>
```

Hope you can help me with that one...

### Puppeteer version

currently 5.5.0 - tried with lower and upper versions as well

### Node.js version

nodejs14 (updated from nodejs10)

### npm version

not sure what's running on GCF

### What operating system are you seeing the problem on?

Linux

**Comment by amkoehler** [comment]
Any luck with this? Ran into a similar issue.

**Comment by fractalawareness** [comment]
Same here. Any workaround?

**Comment by OrKoN** [comment]
I believe you would need to install the missing fonts in your environment. They are probably pre-installed on your local system and not int the GCF.
