### ISSUE TITLE
Timeout when loading HTML string

### ISSUE THREAD

**Issue by BkSouX** [puppeteer/puppeteer#811]
Hi,

I am trying to optimize my function. It takes an HTML as string and return a screenshot buffer.

Here is the function:
```javascript
async function screenshotHtml(html, width, height) {
  const id = nanoid();
  const fullpageImage = `./fullpage-${id}.png`;

  logger.info(`SCREENSHOT ${id} - Start`);
  const browser = await getBrowser();
  const page = await browser.newPage();
  await page.setJavaScriptEnabled(false);
  logger.info(`SCREENSHOT ${id} - Page is opened`);
  await page.goto(`data:text/html,${html}`); // TIMEOUT HERE
  logger.info(`SCREENSHOT ${id} - HTML is loaded`);
  await page.screenshot({
    path: fullpageImage,
    fullPage: true,
  });
  logger.info(`SCREENSHOT ${id} - Screenshot done`);
  await page.close();

  const thumbnail = await sharp(fullpageImage)
    .resize(width, height)
    .crop(sharp.gravity.north)
    .toBuffer();
  await fs.remove(fullpageImage);
  logger.info(`SCREENSHOT ${id} - Screenshot resized ${width}px*${height}px`);
  logger.info(`SCREENSHOT ${id} - End`);

  return thumbnail;
}
```

The function is a part of a web service so it can be called simultaneously by multiple request. The setContent and screenshot function are often slow (few seconds). I don't know if i'm doing it well (maybe an issue with async await ?) or if there's an issue with Puppeteer.

Maybe someone have an idea ?

**Comment by ebidel** [comment]
Can you provide more details on the html? If the page is resource-heavy, the culprit is probably `waitForNavigation`, which is going to wait for the page's `load` event to fire. 

Not sure there's much you can do if you're running this as a webservice and don't know the structure of the page ahead of time.

**Comment by BkSouX** [comment]
Well, it can be an HTML with multiple images ( base64 or URL ). 
Sometimes I have errors like a 30s timeout (with the page.goto) method, and "Error: Page crashed!".

```
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at NavigatorWatcher.waitForNavigation (/opt/thumbnailgenerator/node_modules/puppeteer/lib/NavigatorWatcher.js:74:13)
```

Sample of HTML here http://gist.github.com/BkSouX/3c95179a849f45a87e93aeb74bae19ef ( beautiful HTML intended to emails :wink: )

edit : update the first post with the full function

**Comment by BkSouX** [comment]
Sample of HTML here https://gist.github.com/BkSouX/3c95179a849f45a87e93aeb74bae19ef ( beautiful HTML intended to emails :wink: )

**Comment by ebidel** [comment]
I see. So you're using `goto` with a huge data url and not `setContent` :) Generally there are max limits to URL length, so you may be hitting that with loading the data url for a larger page.

Why not `await page.setContent(html);` instead of `page.goto(`data:text/html,${html}`);`? The latter takes 1-2 for me while the former takes 21ms. There's no need to navigate to a url.

**Comment by BkSouX** [comment]
I tried but the page crashes with some html and the exception is not catched.

```javascript
  try {
    await page.setContent(html);
    logger.info(`SCREENSHOT ${id} - HTML is loaded !`); // log is displayed
  } catch (e) {
    logger.error(`SCREENSHOT ${id} - Error while loading HTML ${html.replace(/(\r\n|\n|\r|\t)/gm, ' ')}`, e);
    await page.close();
    throw e;
  }
 try {
    await page.screenshot({
      path: fullpageImage,
      fullPage: true,
    });
    logger.info(`SCREENSHOT ${id} - Screenshot done`); // not displayed
  } catch (e) {
    logger.error(`SCREENSHOT ${id} - Error while doing screenshot ${html.replace(/(\r\n|\n|\r|\t)/gm, ' ')}`, e); // not displayed
    await page.close();
    throw e;
  }
```

In the second try-catch; I don't see any of these logs (info & error), juste that 
```(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Page crashed!``` but I don't know from where it comes.

It works if I remove the ```fullPage:true``` but I don't know why. 
Maybe there is a memory issue because the fullPage works on my computer but not in the container with 256Mb of ram.

**Comment by ebidel** [comment]
Definitely could be related to the container shared memory size. In the future, please include code and all the details like that when creating an issue. We could have saved a couple of days off back and forth!

**Comment by ebidel** [comment]
Closing in favor of that issue

**Comment by BkSouX** [comment]
Ok thanks @ebidel 
When I have created the issue, I had no idea of what was going on :smile:

**Comment by ebidel** [comment]
Fair enough :)
