### ISSUE TITLE
[Bug]: can't catch net::ERR_INVALID_AUTH_CREDENTIALS error when headless:true

### ISSUE THREAD

**Issue by Peatechen** [puppeteer/puppeteer#8116]
### Bug description

can't catch net::ERR_INVALID_AUTH_CREDENTIALS error when headless:true

```
try{
 await page.goto("https://www.facebook.com", {
        timeout: ms("60s"),
      });
} catch (err) {
      if (
        err.message.startsWith("net::ERR_INVALID_AUTH_CREDENTIALS")
      ) {
        console.log("network error");
      }
}
```
print when headless:false,but headless:ture not

### Puppeteer version

13.4.0

### Node.js version

v16.14.0

### npm version

8.3.1

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by KnightSlayer** [comment]
@Peatechen  hi! did you find any solution or explanation? I face same issue

**Comment by Peatechen** [comment]
> @Peatechen hi! did you find any solution or explanation? I face same issue
This issue was not resolved. It's a rare and occasional problem in my project, and we eventually ignored it. As a result, an error is thrown during the next step after accessing the page, such as failing to find a certain HTML element after visiting the page
