### ISSUE TITLE
browser.close not returning a Promise

### ISSUE THREAD

**Issue by gojko** [puppeteer/puppeteer#812]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: MacOS 10.12.6
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```
$ node
> let browser;
> const puppeteer = require('puppeteer');
> puppeteer.launch().then(t => browser = t).then(() => console.log('launched'))
Promise { <pending> }
launched
> browser.close().then(() => console.log('closed'))
TypeError: Cannot read property 'then' of undefined
```

**What is the expected result?**

`browser.close` to return a Promise, as per [documentation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserclose)

**What happens instead?**

`browser.close` returns `undefined`

**Comment by vsemozhetbyt** [comment]
`browser.close()` returns promise in the latest `v0.11.0-alpha` (see [the version in the top of the doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-api-v0110-alpha)) — [unlike v0.10.2](https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#browserclose)
