### ISSUE TITLE
[Bug]: TypeError: bufferUtil.mask is not a function, Uncaught TypeError: isValidUTF8 is not a function

### ISSUE THREAD

**Issue by arasmussen** [puppeteer/puppeteer#8121]
### Problem 

It would seem that `puppeteer` uses optional dependencies from `ws` in certain cases but does not have those deps in its own `package.json`.

Those optional dependencies are:
- `bufferutil` (getting `TypeError: bufferUtil.mask is not a function`)
- `utf-8-validate` (getting `Uncaught TypeError: isValidUTF8 is not a function`)

I can make these errors go away by depending on those two libs in my own project, but it seems like since `puppeteer` is the one using them, `puppeteer` should add those deps to its package.json.

### Steps to reproduce

**Tell us about your environment:**

- Puppeteer version: 13.5.1
- Platform / OS version: macOS
- URLs (if applicable): n/a
- Node.js version: 14.15.1
- NPM version: 6.14.11

**What steps will reproduce the problem?**

Unfortunately I don't have repro steps. It is failing for our test suite. I am not sure in which cases `puppeteer` uses `bufferutil` and `utf-8-validate` and in which cases it doesn't.

**What is the expected result?**
Importing puppeteer also imports all deps that puppeteer relies on, so that puppeteer can be used without crashing, debugging, and adding optional deps to my project.

**What happens instead?**
Using stock puppeteer crashes in certain cases, which causes the developer to have to debug, figure out that optional deps are missing, and add them manually.

**Comment by arasmussen** [comment]
https://github.com/puppeteer/puppeteer/issues/1224 is a related issue, but the problem still exists and the recommended solution isn't helpful.

**Comment by OrKoN** [comment]
hm, I don't find usages of these functions in Puppeteer codebase. Are these functions called by `ws`?

**Comment by arasmussen** [comment]
> hm, I don't find usages of these functions in Puppeteer codebase. Are these functions called by `ws`?

Yes. They are [optional dependencies of `ws`](https://github.com/websockets/ws#opt-in-for-performance). It's unclear in which cases Puppeteer does/doesn't use these libs, but since in certain cases Puppeteer does use them, it seems to me that Puppeteer should include them in its own `package.json`.

The user experience for me was pretty rough otherwise:

- Get random failures when using Puppeteer
- Google obscure error messages related to bufferUtil / isValidUTF8
- Find random GitHub issues and documentation about these modules
- Finally realize that these are optional deps of `ws` that `puppeteer` is using
- Add them to my own package.json

Alternatively, it would be nice to opt-out of using them by default, and be able to opt-in somehow, knowing that I need to require these deps in my project.

**Comment by OrKoN** [comment]
Well, the dependencies are not required so ws should not call them. I think it's actually a ws bug as I don't think Puppeteer calls those directly. Are you perhaps bundling the code with a bundler that breaks some ws checks for the dependencies?

**Comment by OrKoN** [comment]
I think this release of `ws` should fix it: https://github.com/websockets/ws/releases/tag/8.8.0

`ws` adds two more env variables `WS_NO_BUFFER_UTIL` and `WS_NO_UTF_8_VALIDATE` to make sure that optional dependencies are not invoked. The PR bumping the ws version on our side is https://github.com/puppeteer/puppeteer/pull/8503.
