### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Node is either not clickable or not an HTMLElement 

### ISSUE THREAD

**Issue by CodersDevv** [puppeteer/puppeteer#8122]
### Steps to reproduce

**Tell us about your environment:**

- Puppeteer version: "13.4.0",
- Platform / OS version: Ubuntu 20.04.3 LTS
- URLs (if applicable): 
- Node.js version: Node.js v14.19.0.

Here is Code 
```js 
(async () => {
  const puppeteer = require('puppeteer');
  let browser = await puppeteer.launch({ headless: false });
  let page = await browser.newPage();
  await installMouseHelper(page);
  const cursor = createCursor(page);
  await page.goto('https://xyz.com/', { waitUntil: 'networkidle2' });
  await page.waitForTimeout(1000);
  await page.waitForSelector('input[id="year-2022"]')
  await page.click('input[id="year-2022"]');
})();
```

Here is Error Message  
![image](https://user-images.githubusercontent.com/101318850/157614894-4175679f-dd49-4e6d-8f92-b245fdfd2627.png)

**Comment by OrKoN** [comment]
The error means that the element with this selector is not visible on the screen and, thus, not clickable. Is `https://xyz.com/` the actual website you are testing with?

**Comment by aashankhanalpha** [comment]
I am also facing the same issue and my code is the same as of @CodersDevv [CodersDevv](https://github.com/CodersDevv)
![image](https://user-images.githubusercontent.com/97453217/165588429-4bcba805-e102-4512-8f18-9c2b77507fba.png)
