### ISSUE TITLE
[Bug]: TimeoutError: Timed out after 10000 ms while trying to connect to the browser!

### ISSUE THREAD

**Issue by wszymanski** [puppeteer/puppeteer#8129]
### Bug description

Steps to reproduce the problem:

1. Clone [`Handsontable` repository](https://github.com/handsontable/handsontable).
2. Navigate to `handsontable` directory **inside already downloaded directory** (there is a [`handsontable` directory](https://github.com/handsontable/handsontable/tree/master/handsontable) inside the repo).
3. I'm running `npm run test:e2e` on macOS with Apple M1 Pro chip.
4. The script throws an error while everything works works on `CI` and for some another environment.

```
ls ./node_modules/puppeteer/.local-chromium
mac-970485
```

Note: Above npm script uses `npm run test:e2e.puppeteer` which often (**but not always**) works while run separately.

### Puppeteer version

13.5.0 / 10.4.0

### Node.js version

16.13.0

### npm version

8.3.2

### What operating system are you seeing the problem on?

macOS with Apple M1 Pro chip

### Relevant log output

```shell
> node test/scripts/run-puppeteer.mjs test/E2ERunner.html

/Users/aviox/apps/handsontable/handsontable/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:248
            reject(new Errors_js_1.TimeoutError(`Timed out after ${timeout} ms while trying to connect to the browser! Only Chrome at revision r${preferredRevision} is guaranteed to work.`));
                   ^

TimeoutError: Timed out after 10000 ms while trying to connect to the browser! Only Chrome at revision r970485 is guaranteed to work.
    at Timeout.onTimeout (/Users/aviox/apps/handsontable/handsontable/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:248:20)
```

**Comment by sag1v** [comment]
Keep open as this is still an issue.

**Comment by Amit0617** [comment]
I confirm this issue
