### ISSUE TITLE
[Bug]: line break cause blank line before next text in exported PDF

### ISSUE THREAD

**Issue by jofomah** [puppeteer/puppeteer#8142]
### Bug description

Steps to reproduce the problem:

1. Have a div whose width and length contains a text and has line height set to `1em`.
2. The HTML preview looks fine
![screenshot-ampifire com-2022 03 17-08_52_41](https://user-images.githubusercontent.com/5929681/158762817-ea7f1a10-ce9f-4d0a-b19a-0631a8f9d760.png)

3. When you print the page, it will have a line. example:
![Screenshot (17)](https://user-images.githubusercontent.com/5929681/158763464-8f0d30d4-9a8c-4c88-91f1-712bace49392.png)
![Screenshot (19)](https://user-images.githubusercontent.com/5929681/158764238-947cb5ac-9237-41f8-8044-6112be196997.png)

### Puppeteer version

1.17.0

### Node.js version

v12.14.1

### npm version

N/A

### What operating system are you seeing the problem on?

Linux

**Comment by jrandolf-google** [comment]
We no longer support Node 12, please try this again with the latest version of Puppeteer and Node 14+.

**Comment by jofomah** [comment]
@jrandolf Thanks for the response. I updated to Puppeteer  version `15.3.0` and NodeJS version `16.15.0` and i got this same issue. I think this issue should be reopened unless it is not a Puppeteer specific issue. Thanks
