### ISSUE TITLE
Should response.status 304 make response.ok false?

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#815]
### Steps to reproduce
* Puppeteer version: v0.11.0-alpha
* Platform / OS version: Windows 7 x64

Doc for `response.ok` [states](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#responseok): 

> Contains a boolean stating whether the response was successful (status in the range 200-299) or not.

Should the status 304 (Not Modified), while not in the range 200-299, mean not successful request?

**Comment by ebidel** [comment]
FWIW, Puppeteer's `Response` was modeled after the https://developer.mozilla.org/en-US/docs/Web/API/Response/ok. Not sure that we should deviate from the platform API semantics much more than we already do.
