### ISSUE TITLE
omitBackground does not work with header or footer template

### ISSUE THREAD

**Issue by vishalquant** [puppeteer/puppeteer#8152]
Versions:
puppeteer: "^10.1.0"
Node: v14.17.5

The code works fine and give me the perfect transparent PDF using `omitBackground:true`. But when I use `headerTemplate` or `footerTemplate` I lost the transparency of the PDF, looks like using `omitBackground:true` with `headerTemplate` or `footerTemplate` does not work. When I comment the code for `headerTemplate` or `footerTemplate`, I get perfect transparent PDF but I need headers and footers too.

Below is the sample pdfOptions I am using for PDF generation
```
const pdfOptions = {
   displayHeaderFooter: true,
   footerTemplate: 
   '<div style="color: lightgray; border-top: solid lightgray 1px; font-size: 10px; padding-top: 5px; text-align: center; width: 100%;
        background:transparent !important; background-color:rgba(0,0,0,0) !important;">
        <span>This is a test message</span> - <span class="pageNumber"></span>
   </div>',
   format: 'A4',
   margin: {
        bottom: 70, // minimum required for footer msg to display
        left: 25,
        right: 35,
        top: 30,
   },
   printBackground: true,
   omitBackground:true
}
```
```
  await page.pdf(pdfOptions);
  await page.close();

```

I tried to use css to transparent the background by setting 
`"background:transparent !important,background-color:rgb(0,0,0,0) !important`
to the footertemplate html, but It did not work.

**Comment by aman-quo** [comment]
> Versions: puppeteer: "^10.1.0" Node: v14.17.5
> 
> The code works fine and give me the perfect transparent PDF using `omitBackground:true`. But when I use `headerTemplate` or `footerTemplate` I lost the transparency of the PDF, looks like using `omitBackground:true` with `headerTemplate` or `footerTemplate` does not work. When I comment the code for `headerTemplate` or `footerTemplate`, I get perfect transparent PDF but I need headers and footers too.
> 
> Below is the sample pdfOptions I am using for PDF generation
> 
> ```
> const pdfOptions = {
>    displayHeaderFooter: true,
>    footerTemplate: 
>    '<div style="color: lightgray; border-top: solid lightgray 1px; font-size: 10px; padding-top: 5px; text-align: center; width: 100%;
>         background:transparent !important; background-color:rgba(0,0,0,0) !important;">
>         <span>This is a test message</span> - <span class="pageNumber"></span>
>    </div>',
>    format: 'A4',
>    margin: {
>         bottom: 70, // minimum required for footer msg to display
>         left: 25,
>         right: 35,
>         top: 30,
>    },
>    printBackground: true,
>    omitBackground:true
> }
> ```
> 
> ```
>   await page.pdf(pdfOptions);
>   await page.close();
> ```
> 
> I tried to use css to transparent the background by setting `"background:transparent !important,background-color:rgb(0,0,0,0) !important` to the footertemplate html, but It did not work.

We tried every possible way to overcome this issue but in-vein. Can anyone raise us a helping hand here?
We are in the IST timezone.

**Comment by SiberianCMS** [comment]
Same issue here,

Without header/footer backgrounds are printed ok, as sonn as displayHeaderFooter: true, the background turns white no matter what.

file:///home/anders/Pictures/Screenshot_20221201_162907.png
file:///home/anders/Pictures/Screenshot_20221201_162844.png

**Comment by albertmatyi** [comment]
This issue still persists with chromium 113 used for rendering. 
When manually using Chromium 113 to render PDF with footer/header the PDF comes out w transparent background
