### ISSUE TITLE
Override eval() function in evaluateOnNewDocument

### ISSUE THREAD

**Issue by datasunny** [puppeteer/puppeteer#816]
Try to override eval() function to print out the actual code that get eval-ed. The following code prints out what sent to eval() but those code didn't get run (oldEval.call() should do it). Anything I did wrong? TIA.

```
  page.on('console', async msg => {
    console.log(msg);
  });

  page.evaluateOnNewDocument(() => {
    var oldEval = eval;
    eval = function(arg) {
      console.log('eval() called:\n'+arg);
      oldEval.call(window, arg);
    };
  });
```

**Comment by paulirish** [comment]
that looks mostly right but you'll probably want a `return` on the oldEval.call line...

but aside from that, I don't know exactly why it doesnt work.

i would run with headless off and then open devtools on the page (while puppeteer is connected) to debug it further.

**Comment by datasunny** [comment]
@paulirish adding 'return' did the trick! Please close the issue.
