### ISSUE TITLE
[Bug]: Puppeteer keeps freezing

### ISSUE THREAD

**Issue by generated** [puppeteer/puppeteer#8163]
### Bug description

Initialize puppeteer:
```
const browser = await puppeteer.launch({
    headless: true,
    devtools: true,
    args: [
        '--ignore-certificate-errors',
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-accelerated-2d-canvas',
        '--disable-gpu'
    ]
});
```
do some
```
await page.click('button.swiper-button-next');
```
and
```
const refreshedHtml = await page.evaluate(() => document.documentElement.innerHTML);
```
and the project hangs on random occasions (and random spots).

### Puppeteer version

13.5.1

### Node.js version

16.14.0

### npm version

8.3.1

### What operating system are you seeing the problem on?

Linux, Windows

### Relevant log output

```shell
Sadly no error thrown and no log output
```

**Comment by Junyan** [comment]
@generated Can you provide a reproducible example?
