### ISSUE TITLE
Puppeteer crashes on "http://google.com" when setRequestInterceptionEnabled is enabled

### ISSUE THREAD

**Issue by adamblok** [puppeteer/puppeteer#818]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Windows 10 Pro and Ubuntu Server 16.04
* URLs (if applicable): http://google.com

**What steps will reproduce the problem?**

The code below produces the problem quite every time I run it:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true
  });

  const page = await browser.newPage();

  await page.setRequestInterceptionEnabled(true);
  
  page.on('request', request => {
    request.continue();
  });

  await page.goto('http://google.com');
  await browser.close();
})();
```

**What is the expected result?**

The code above does nothing, but in my project I work on I have to process every request so I need to enable `setRequestInterceptionEnabled` option.

**What happens instead?**

> (node:1004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Network.continueInterceptedRequest): Target closed.
> (node:1004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vsemozhetbyt** [comment]
@adamblok I cannot reproduce with your code and `v0.11.0-alpha`, but maybe this change can help:
```js
  page.on('request', async request => {
    await request.continue();
  });
```

**Comment by vsemozhetbyt** [comment]
I can reproduce with `v0.10.2` with or without proposed change.

**Comment by vsemozhetbyt** [comment]
It may be connected with `browser.close();` not returning Promise yet on `v0.10.2` so that cannot be `await`ed.

**Comment by adamblok** [comment]
@vsemozhetbyt the change with `await request.continue();` doesn't work for me either.

You're probably right. When I comment the `browser.close();` line, then everything works fine. It looks like the browser closes a connection too early, so it causes this problem.

**Comment by Garbee** [comment]
No, it's the await on close as pointed out earlier. In 0.10 it doesn't return a promise.

**Comment by Alexandredc** [comment]
Same problem. Is it possible to install v0.11.0-alpha ? I didn't find it on npm or github.
Thanks

**Comment by Garbee** [comment]
@AlexandreAWE Unreleased versions are the current `master` branch. So you'd require the GH repo vs the NPM version.

**Comment by Alexandredc** [comment]
I confirm that v0.11.0-alpha fix the problem

**Comment by adamblok** [comment]
Thank you for your quick response guys. Do you know what is a release date?

**Comment by aslushnikov** [comment]
For the record: the v0.11.0 [was released](https://github.com/GoogleChrome/puppeteer/releases/tag/v0.11.0) a few days ago.
