### ISSUE TITLE
Render Emoji when running on Azure Functions and other cases with just `puppeteer`

### ISSUE THREAD

**Issue by SushritPasupuleti** [puppeteer/puppeteer#8180]
### Steps to reproduce

**Tell us about your environment:**

- Puppeteer version: 13.5.2
- Platform / OS version: Azure Functions Linux Instance (Consumption Plan)
- URLs (if applicable):
- Node.js version: 14/12 (tried both)

**What steps will reproduce the problem?**

1. Setup a basic Azure Function of type HTTP Request
2. Enter the following code in the `index.js` file of the function.

```js
const puppeteer = require("puppeteer");

// inside the HTTP Request function body //
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.goto(url);

const buffer = await page.screenshot({
     fullPage: true,
});

// return the buffer with image/jpeg header //

```

**What is the expected result?**

The above code will work perfectly. However, when it comes to content with emojis, as the underlying Linux image of Azure Functions has no bundled font with emojis, these will render as blank boxes.

**What happens instead?**

Normally you would want a way to bundle a font with emoji support.

This is done in the case of `chrome-aws-lamba` within the launch options like so:

```js
import chrome from 'chrome-aws-lamba'
import core from 'puppeteer-core'

const browser = await puppeteer.launch({
     args: chrome.args,
     executablePath: await chrome.executablePath,
     headless: chrome.headless,
     font: await chrome.font('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf'),
});
/// rest of the code is the same as above to screenshot and return the image
```

Now I understand these 2 approaches use completely different dependencies but I think it would be nice to configure the bundled chrome version that ships with `puppeteer` could be configured the same way with a font target, something like shown below:

```js
const browser = await puppeteer.launch({
     font: await fontFromURL('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf'),
});
```

Any alternatives to get this working are appreciated as well :)

**Comment by milosponj** [comment]
I'm tackling the same issue, something like you proposed would work wonders

**Comment by SushritPasupuleti** [comment]
> I'm tackling the same issue, something like you proposed would work wonders

I had to settle for deploying a custom docker image with an apt install to install the fonts before running my code. The plan for deploying custom docker images as functions on Azure is pricier but it gets the job done for me. Wish this got looked at.

**Comment by dancherb** [comment]
This is still an issue for azure functions - deploying as a custom docker image is a workaround, not a solution.
