### ISSUE TITLE
[Bug]: Puppeteer freezes if a bfcache eligible page is loaded using a page.goBack() function

### ISSUE THREAD

**Issue by giacomozecchini** [puppeteer/puppeteer#8182]
### Bug description

Steps to reproduce the problem:

When visiting a first_url and then moving to a second_url, then if the first_url is bfcache eligible, the page doesn't fire any PuppeteerLifeCycleEvent events, and Puppeteer freezes

`await page.goto(first_url, {waitUntil: 'networkidle2'});`
`await page.goto(second_url, {waitUntil: 'networkidle2'});`
`await page.goBack({waitUntil: 'networkidle2'})`

If first_url is bfcache eligible and you use a timeout in the `page.goBack` function, a TimeoutError is fired instantaneously.

Pages to test:
[https://developer.google.com](https://developer.google.com)
[https://www.google.com](https://www.google.com)
[https://en.wikipedia.org/wiki/Cat](https://en.wikipedia.org/wiki/Cat)
[https://en.wikipedia.org/wiki/Zombie](https://en.wikipedia.org/wiki/Zombie)

### Puppeteer version

13.5.2

### Node.js version

17.8.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
Could you please provide the complete script that reproduces the problem? The following appears to be working fine for me.

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: true
  });
  const page = await browser.newPage();
  page.setDefaultNavigationTimeout(5000);
  await page.goto('https://en.wikipedia.org/wiki/Cat', {waitUntil: 'networkidle2'});
  await page.goto('https://en.wikipedia.org/wiki/Zombie', {waitUntil: 'networkidle2'});
  await page.goBack({waitUntil: 'networkidle2'});
  await browser.close();
})();
```

**Comment by giacomozecchini** [comment]
Hi Alex, this doesn't work for me:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  page.setDefaultNavigationTimeout(5000);
  await page.goto('https://en.wikipedia.org/wiki/Cat', {waitUntil: 'networkidle2'});
  await page.goto('https://www.google.com', {waitUntil: 'networkidle2'});
  await page.goBack({waitUntil: 'networkidle2'});
  await browser.close();
})();
```

**Comment by OrKoN** [comment]
I have disabled bfcache in the built-in launcher so Puppeteer should not freeze anymore (next release) when the browser is started by Puppeteer. See the linked issue for tracking the support for bfcache in Puppeteer.
