### ISSUE TITLE
Unhandled promise rejection (rejection id: 1): Error: Page crashed!

### ISSUE THREAD

**Issue by Vwings** [puppeteer/puppeteer#819]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Windows 7

**What steps will reproduce the problem?**
1.Try the demo code
```
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch();
    console.log(await browser.version());
    const page = await browser.newPage();
    await page.goto('https://developer.mozilla.org');
    await browser.close();
})();
```

**What happens instead?**
output:
HeadlessChrome/62.0.3198.0
(node:11192) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
>(node:11192) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11192) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Navigation Timeout Exceeded: 30000ms exceeded

**Comment by vsemozhetbyt** [comment]
I cannot reproduce with v0.10.2 or v0.11.0-alpha on Windows 7 x64.

**Comment by adamblok** [comment]
It works well for me too. Maybe is it related to a language version of this page?

@Vwings Please provide full URL to this page including a language version, for example: https://developer.mozilla.org/en-US/#

**Comment by ebidel** [comment]
I'm also unable to repro this. "Navigation Timeout Exceeded: 30000ms exceeded" makes it seem like you had a connection issue fetching the page...?

**Comment by colshacol** [comment]
Also having this issue.

macOs Sierra (10.12.6)
puppeteer@0.11.0
npm@5.4.2
node@8.7.0

<img width="771" alt="screenshot 2017-10-12 21 00 15" src="https://user-images.githubusercontent.com/19484365/31527145-fb7d9d2e-af90-11e7-84f4-c0731ad0e4a5.png">

Browser never gets launched. It just... does nothing when I run it, haha.

**Comment by VenPot** [comment]
Was this issue figured out ? I still get the same error intermittently. how do we handle an error when the time out happens? i am taking screenshots of multiple pages and dont want the process to hang when one the url times out or does not resolve

**Comment by aslushnikov** [comment]
@VenPot two options:
1. You should try-catch the exception
2. You can use `timeout: 0` option for `page.goto` if you're fine with waiting for ever.

**Comment by VenPot** [comment]
Thank you, I mostly get this when I try to take a full page screenshot.
When I open it in chrome the page loads in like less than 5 sec but through
puppeteer I get the 30 second time out. If I turn off the full page option,
it works fine. But I need full page screenshots.

**Comment by aslushnikov** [comment]
@VenPot this might be a bug; please, file a new issue with a script and url so that we can reproduce it locally.

**Comment by guotie** [comment]
https://club.autohome.com.cn/bbs/thread-c-4206-69395910-1.html

when i request this url, the same error occurs.

**Comment by nickzheng1994** [comment]
i already closed the page ,but  the errors show me "UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Navigation Timeout Exceeded: 30000ms exceeded",
