### ISSUE TITLE
[Bug]: Full page screenshot is not working properly on long page

### ISSUE THREAD

**Issue by Rana-xD** [puppeteer/puppeteer#8193]
### Bug description

I try to screenshot this site: https://www.nasnet.co.jp/service/security/vulnerability-check.html
But, the image was missing some part in the bottom. 
Below is my code 

```
let browser = await puppeteer.launch({
    args: [
        '--disable-gpu',
        '--disable-dev-shm-usage',
        '--disable-setuid-sandbox',
        '--no-first-run',
        '--no-sandbox',
        '--no-zygote',
        '--single-process',
    ],
    timeout: 300000,
    defaultViewport: {
        width: viewportWidth,
        height: viewportHeight
    }
});
let page = await browser.newPage();

await page.goto(url, {
    timeout: 0
});

const bodyHandle = await page.$('body');
const { height } = await bodyHandle.boundingBox();

const scrollHeight = await page.evaluate(() => document.body.scrollHeight);

let siteHeight = (height > scrollHeight) ? height : scrollHeight;

// Scroll one viewport at a time, pausing to let content load
let viewportIncr = 0;

while (viewportIncr + viewportHeight <= siteHeight) {
    await page.evaluate(_viewportHeight => {
        window.scrollBy(0, _viewportHeight);
    }, viewportHeight);
    await wait(500);
    viewportIncr = viewportIncr + viewportHeight;
}

// Scroll back to top
await page.evaluate(_ => {
    window.scrollTo(0, 0);
});

// Wait for a specific period before capture
await new Promise((resolve, reject) => {
    setTimeout(resolve, (parseInt(waitTime) * 1000));
});

await page.screenshot({
    path: `./${fileName}`,
    fullPage: true
});

await page.close();
await browser.close();
```

Expected Result: 

![089fe8f8-9b31-44db-bf56-d34092ae4630-min](https://user-images.githubusercontent.com/18557407/161768327-2afc7d1e-dfb8-4eb5-9a54-96a7918a1af9.png)

Actual Result: 

![d154e738-04f0-4888-87d6-6bd11d739977](https://user-images.githubusercontent.com/18557407/161771160-8ae3ec81-1db8-4d9c-a102-27728242bdb3.png)

Could I know the alternative way to screenshot full page of that site? 
Thank you.

### Puppeteer version

13.0.1

### Node.js version

14.17.3

### npm version

6.14.13

### What operating system are you seeing the problem on?

macOS

**Comment by CodyEakins** [comment]
I'm willing to bet this is environment specific, rather than an issue with Puppeteer itself. Your code for scrolling the page might be problematic too. I'll try to replicate this behavior.

Are you using Docker or a Lambda function? Is your Mac cloud based? Intel or M1? MacOS version?
