### ISSUE TITLE
[Feature]: Support bfcache in Puppeteer

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#8197]
Issue #8182 revealed that Puppeteer does not work well with navigations to bfcache-eligible pages. Therefore, in #8196 bfcache feature was disabled by default. This issue should be used to track the work required to support bfcache in Puppeteer with sufficient test coverage.

**Comment by OrKoN** [comment]
@mathiasbynens @ergunsh @jrandolf FYI

**Comment by rviscomi** [comment]
I'm interested in bfcache support in Puppeteer. Is there any ETA on when it'll be supported?

**Comment by OrKoN** [comment]
We now have a basic bfcache support as covered by tests here https://github.com/puppeteer/puppeteer/blob/main/test/src/cdp/bfcache.spec.ts
