### ISSUE TITLE
waitForPromised

### ISSUE THREAD

**Issue by JOEAV** [puppeteer/puppeteer#820]
Hi guys , so i'm having this scenario which i'm trying to inject a promise to the page context but found that i can inject only regular functions.
Scenario: 
e2e testing environment 
Use case:
1.open a new page (great)
2.goto the test url (awesome)
3.wait for the test to finish(lets say i have this predicate on window.jasmine which tells me the test has finished) 
4. get the test result by an object from the page context to the puppeteer context(guess ill have to use .evaluate in order to get the object)(got it)

Thing is , i want to run this mechanism concurrently/parallel 
second thing , task number 3 should be done in a interval promise(with retries and an interval) as i need to poll the predicate until it's done. let
moreover , i must do task number 3 in a non-blocking manner , such as "fire & forget" in order to keep open new test urls instead of waiting for each one of them , resulting in blocking the others and not running parallel.
Any ideas how can i achieve this ? thanks in advance!

**Comment by ebidel** [comment]
For general technical questions or "how to" guidance, please search StackOverflow for questions tagged "puppeteer" or create a new post.
