### ISSUE TITLE
Puppeteer closes down before actual work is complete

### ISSUE THREAD

**Issue by dchoigt** [puppeteer/puppeteer#8202]
### Bug description

1. I am using Puppeteer to call to an sso login screen in order to login. This works great! 
2. After the login screen work finishes, try additional work. This fails as browser shuts down. Even after adding waitForTimeout(30000) it shuts down before the rest of the code after logging has a chance to run.

`const puppeteer = require('puppeteer');

module.exports = async function Login(options = {}) {
    const browser = await puppeteer.launch({
        headless: false, //options.headless,
        args: options.args || ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const page = await browser.newPage();
    console.log("new page created")
    try {
        await page.setViewport({ width: 1280, height: 800 });
        await page.setRequestInterception(true);
        page.on('request', preventApplicationRedirect(options.callbackUrl));
        //console.log("try prevent redirect success!")
        await page.goto(options.loginUrl);

        await writeUsername({ page, options });
        await writePassword({ page, options });

        const response = await clickLogin({ page, options });        
        if (response.status() >= 400) {
            throw new Error(`Login with user ${options.username} failed, error ${response.status()}`);
        }
        const url = response.url();
        //console.log("url", url);
        //if (url.indexOf(options.callbackUrl) !== 0) {
            //throw new Error(`User was redirected to unexpected location: ${url}`);
        //}
        page.waitForTimeout(30000); // this line is ignored

        const { cookies } = await page._client.send('Network.getAllCookies', {});
        return {
            callbackUrl: url,
            cookies
        };
    } finally {
        await page.close();
        await browser.close();
    }
}

async function writeUsername({ page, options } = {}) {
    console.log("type username", options.username);
    const selector = '[name=email]';
    await page.waitForSelector(selector, { timeout: 0 });
    await page.waitForTimeout(2000);
    await page.type(selector, options.username);
}

async function writePassword({ page, options } = {}) {
    console.log("type password");
    const selector = '[name=password]';
    await page.waitForSelector(selector, { visible: true });    
    await page.type(selector, options.password);
}

async function clickLogin({ page } = {}) {    
    const selector = '.auth0-lock-submit';
    await page.waitForSelector(selector, {
        visible: true,
        timeout: 5000
    });
    console.log("attempt login click");
    const [response] = await Promise.all([page.waitForNavigation({ waitUntil: 'networkidle0', timeout: 0 }), page.click(selector)]);
    console.log("login click response");
    return response;
}

async function acceptElsaAuth0Usage({ page } = {}) {
    console.log("start accept auth0 usage");
    const selector = 'button[name=action]'
    await page.waitForSelector(selector, { visible: true, timeout: 0 });
    await page.waitForTimeout(2000);
    console.log("accept auth0 usage in elsa click");
    const [response] = await Promise.all([page.waitForNavigation({ waitUntil: 'networkidle0', timeout: 0 }), page.click(selector)]);
    await page.waitForTimeout(2000);
    console.log("accept auth0 usage in elsa response", response);
    return response;
}

function preventApplicationRedirect(callbackUrl) {
    console.log("try prevent redirect");
    return request => {
        const url = request.url();
        
        if (request.isNavigationRequest() && url.indexOf(callbackUrl) === 0) {
            console.log("preventApplicationRedirect url", url);
            request.respond({ body: url, status: 200 });
        } else {
            request.continue();
        }
    }
}`

### Puppeteer version

13.5.2

### Node.js version

14

### npm version

6.14

### What operating system are you seeing the problem on?

macOS

**Comment by kashif-ghafoor** [comment]
I am facing the same issue. browser closes before other operations are completed. and following error is thrown. 
ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
when I comment `await browser.close()` line logic works fine.

**Comment by OrKoN** [comment]
You need to make sure that the operations you started have finished as the `browser.close()` closes the browser unconditionally. In the original post, there is also `await` is missing before waitForTimeout and probably that's why it's ignored. If you believe that Puppeteer still throws an error after all of the user scheduled tasks have been resolved, please re-open the issue and provide the repro script.

**Comment by frknasir** [comment]
To ensure that the browser and page instances are not closed prematurely, you need to wait for all asynchronous operations to complete before closing the browser. This means handling the promises correctly and using Promise.all to wait for all operations to finish.
