### ISSUE TITLE
Programmatically access compatible Chromium revision number

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#8203]
I’m trying to programmatically access the chromium revision number that is listed in the package.json file. I used to read it from the package.json file, but now that I’ve switched to ES module syntax, that is quite challenging. Is this or can this be exposed in an API? 

Puppeteer should be able to tell you what chromium revision it prefers in an API

PS: I don’t want to download a browser or spin up a browser to find this number

**Comment by vasani-arpit** [comment]
I think you might be looking for this 

```javascript
const revision = require('puppeteer/lib/esm/puppeteer/revisions.js').PUPPETEER_REVISIONS.chromium;
```

**Comment by vasani-arpit** [comment]
You can also get it from here 

https://omahaproxy.appspot.com/

you can have it in json using https://omahaproxy.appspot.com/all.json

you can also pass arguments in query params to get desired channel or platform

**Comment by forrestab** [comment]
revisions.js is located here, "puppeteer-core/lib/[cjs|esm]/puppeteer/revisions.js", as of puppeteer@19.5.2 for me. But ideally this would be a property or method on the exported puppeteer object.

**Comment by tsullivan** [comment]
> I think you might be looking for this
`const revision = require('puppeteer/lib/esm/puppeteer/revisions.js').PUPPETEER_REVISIONS.chromium;`

Hi, @vasani-arpit as of Puppeteer 20.1.0, this method no longer works. The revisions.js file now contains a Chrome release version string, not a revision number. I don't see a way to programmatically access the Chromium revision number.

**Comment by vasani-arpit** [comment]
@tsullivan Yes. one can use https://chromiumdash.appspot.com to get the required data. 

here is a request which might give what one needs. https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Windows&num=1

#### Response 

```json
[
  {
    "channel": "Stable", 
    "chromium_main_branch_position": 950365, 
    "hashes": {
      "angle": "343b7bb57268e1cb47da26fcb0ed40fe47e8ff5d", 
      "chromium": "cab11adacc41ee856c79e669c2fd38d8864e52c4", 
      "dawn": "1b1b658d365591b6a8d4bfb0c3524832c89afc99", 
      "devtools": "b6f648d8921ea8be8f2b32c2061fec7503b56610", 
      "pdfium": "27cabf3dae38d0634a53316da0ad069bf0413495", 
      "skia": "a6986cd7224f104044fd5bc29cb5f80796d76f5a", 
      "v8": "db77a493a5595b835655b243202ac0c2fb1898a6", 
      "webrtc": "a6b138d6b4ef3a5b2c87f899b67f3b5c8dd3c002"
    }, 
    "milestone": 98, 
    "platform": "Windows", 
    "previous_version": "98.0.4758.81", 
    "time": 1643754840000, 
    "version": "98.0.4758.82"
  }
]
```

**Comment by Lightning00Blade** [comment]
The latest version exposes the `revisions.js` file. 
```ts
import { PUPPETEER_REVISIONS } from "puppeteer"; // Note the can't use default export here.

console.log(PUPPETEER_REVISIONS);
```
But as pointed  https://github.com/puppeteer/puppeteer/issues/8203#issuecomment-1535088987 it's the Chrome version.
As Puppeteer now uses [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing).
So closing this as won't fix.

**Comment by baruchiro** [comment]
For those who come here after years (like me), here is a solution:

```typescript
const platform = detectBrowserPlatform();
const buildId = await resolveBuildId(Browser.CHROMIUM, platform, 'latest');

install({
  cacheDir: installPath,
  browser: Browser.CHROMIUM,
  buildId,
})
```

**Comment by SaadiSave** [comment]
@baruchiro 

How important is getting the exact PUPPETEER_REVISION? Will 'latest' always work?
