### ISSUE TITLE
goto and screenshot

### ISSUE THREAD

**Issue by MaxDesplanches** [puppeteer/puppeteer#821]
Hi there !

I have an issue on loading html with data text in goto, the screenshot is failing 1 times on 10 screenshots approximately (setContent have the same result)

Thanks for your help

### Steps to reproduce

**Environment:**

* Puppeteer version: 0.10.1
* Platform / OS version: Docker on Mac with container node:6.10.3

**What steps will reproduce the problem?**

1. Have a string in html, with css and html with style tag
2. the goto doesn't seems to work properly: The html contains 5 lines and a picture: sometimes when it is executed (1 / 10), the response jpg and the screenshot file does not have title (see attachment), only a white space instead (the line is an underline text in html)

![sample](https://user-images.githubusercontent.com/990954/30584114-12d6ad5a-9d29-11e7-8437-f720209238e0.jpeg)

Here is the function for screenshot, in a typescript class:

```
    async screenshot(Task: task) {
            await this.page.goto(`data:text/html,${Task.html}`, { timeout: 2000 }).then(() => {}, (error:Error) => {
                console.log(`Error on goto: ${error.message}`)
                return;
            })
            await this.page.setViewport({ width: Task.width, height: Task.height }).then(() => { }, function (error: Error) {
                console.log(`Error on setViewport: ${error.message}`)
            });
            await this.page.screenshot({path: `${config.cache}${Task.filename}`}).then((result: Buffer) => {
               // callback to return http 200 with image in jpg format
            })
    }
```

Thanks in advance,

Max.

**Comment by paulirish** [comment]
Related to #809.... try your `docker run` with `--shm-size=1gb`

**Comment by MaxDesplanches** [comment]
added in docker compose as shm-size: 1gb, same result

![sample2](https://user-images.githubusercontent.com/990954/30585290-a9db3f4c-9d2c-11e7-822c-dcf8ba3a9fe7.jpeg)

The viewport size is 440x290

**Comment by paulirish** [comment]
oh sorry. i didn't read all of your words. :)  

Looks like the webfont isn't finishing loading.  I would set the `waitUntil` option to `networkidle`  and `networkIdleInflight` to 0.

**Comment by MaxDesplanches** [comment]
its works like a charm, you're the best !
