### ISSUE TITLE
[Bug]: Headless mode will start with a blank page

### ISSUE THREAD

**Issue by ysmood** [puppeteer/puppeteer#8216]
### Bug description

Steps to reproduce the problem:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const pages = await browser.pages();
  console.log(pages.length)
})();
```

Expect to print 0, but got 1.

On headful mode we can use the launch flag `--no-first-run` and `--no-startup-window` to disable the startup blank page, but these flags don't work for headless mode. Besides, the code below will get stuck forever, no output at all:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false,
    args: ['--no-startup-window', '--no-first-run'],
  });
  const pages = await browser.pages();
  console.log(pages.length)
})();
```

### Puppeteer version

10.4.0

### Node.js version

v16.0.0

### npm version

8.1.1

### What operating system are you seeing the problem on?

macOS

**Comment by noe132** [comment]
Don't know if this is related, I open 3 pages with `browser.newPage()` but `browser.pages()` always give 2. after I close all pages, program would not exit automatically.
If running in `headless: false`, there are some window with only a `about:black` page was not closing.

**Comment by ysmood** [comment]
Please take a look at this issue

**Comment by OrKoN** [comment]
Flags now work in both the headless (new, enabled by default) and headful modes. `waitForInitialPage: false` to stop waiting for the initial page if args configure that.

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: ['--no-startup-window', '--no-first-run'],
    waitForInitialPage: false,
  });
  const pages = await browser.pages();
  console.log(pages.length) // prints 0
})();
´´´
