### ISSUE TITLE
Failed to navigate

### ISSUE THREAD

**Issue by Alexandredc** [puppeteer/puppeteer#822]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Mac OSX 10.12.6 (same on Docker image => node:8.1)

**Example**
```javascript 
const puppeteer = require('puppeteer');

(async() => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://www.nordictrack.com');
    await browser.close();
})();
```
**Error**
```javascript
(node:11965) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to navigate: https://www.nordictrack.com
(node:11965) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I try to use Chrome Headless with command line and it works great : 
```bash
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
  --headless \
  --disable-gpu \
  --remote-debugging-port=9222 \
 https://www.nordictrack.com
```

It seem that this problem is related to this web site :  https://www.nordictrack.com but i don't know what happen with it.

Thanks.

**Comment by paulirish** [comment]
try loading that site in Chrome Canary.
![image](https://user-images.githubusercontent.com/39191/30585283-51d17cc2-9d67-11e7-8bdf-476f41010099.png)

ERR_SPDY_SERVER_REFUSED_STREAM ... looks like misconfigured h2.

**Comment by Alexandredc** [comment]
Thanks for your help

**Comment by mifi** [comment]
Got the same issue with a page:
https://gfx.nrk.no/

Seems it's fixed in chromium
https://bugs.chromium.org/p/chromium/issues/detail?id=751642

**Comment by mifi** [comment]
I solved the problem by disabling HTTP2
```
await puppeteer.launch({ args: ['--disable-http2'] });
```

Edit: Seems this flag only works with `headless: false`

**Comment by niftylettuce** [comment]
I'm attempting to use `page.goto()` with a valid URL, and I received a similar issue:

```sh
[1005/013631.984177:WARNING:spdy_session.cc(2915)] Received HEADERS for invalid stream 13
```

Your fix @mifi suppressed this error from showing, however the page still did not load and there's no clear reason why at the moment.

**Comment by niftylettuce** [comment]
Here's some other output captured via `requestfailed`:

```sh
    ℹ requestfailed: https://js.driftt.com/dist/static/fonts/c1b472c36be832ed15b190a41b15f0bd.otf null {
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/63.0.3205.0 Safari/537.36",
        "referer": "https://js.driftt.com/dist/assets/widget-11b381e65844bdf0a6068382d9c4eb42-prod.css",
        "origin": "https://js.driftt.com"
      } Other
    ℹ requestfailed: https://js.driftt.com/dist/static/images/978c1bee49d7ad5fc1a4d81099b13e18.png null {
        "referer": "https://js.driftt.com/dist/assets/widget-11b381e65844bdf0a6068382d9c4eb42-prod.css",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/63.0.3205.0 Safari/537.36"
      } Other
    ℹ requestfailed: https://js.driftt.com/dist/static/fonts/d5e252ed23dde9520a0cb00bfbf01a6e.otf null {
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/63.0.3205.0 Safari/537.36",
        "referer": "https://js.driftt.com/dist/assets/widget-11b381e65844bdf0a6068382d9c4eb42-prod.css",
        "origin": "https://js.driftt.com"
      } Other
    ℹ requestfailed: https://js.driftt.com/dist/static/fonts/cc4e72bde1aa38ceeb75e0c140ffa99c.otf [object Object] {
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/63.0.3205.0 Safari/537.36",
        "referer": "https://js.driftt.com/dist/assets/widget-11b381e65844bdf0a6068382d9c4eb42-prod.css",
        "origin": "https://js.driftt.com"
      } Other
    ℹ requestfailed: https://js.driftt.com/dist/static/fonts/89fdab2e1f6bc815c0df0e055515a4df.otf null {
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/63.0.3205.0 Safari/537.36",
        "referer": "https://js.driftt.com/dist/assets/widget-11b381e65844bdf0a6068382d9c4eb42-prod.css",
        "origin": "https://js.driftt.com"
      } Other
```

**Comment by murilozilli** [comment]
I am facing the same issue: Failed to navigate: https://www.thebay.com

**Comment by aslushnikov** [comment]
@murilozilli can't reproduce with the following script and puppeteer 0.13-alpha

```js
const puppeteer = require('.');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const response = await page.goto('https://www.thebay.com');
  console.log(response.status);
  await browser.close();
})();
```

Feel free to file a new issue if you have a stable repro

**Comment by murilozilli** [comment]
@aslushnikov How can I download this version 0.13-alpha? There is no release/tag with this name

**Comment by murilozilli** [comment]
@aslushnikov how do I install this version? There is no tag/release. I tried  `npm install https://github.com/GoogleChrome/puppeteer
` to install the master branch but it didn't work.

**Comment by aslushnikov** [comment]
`npm install https://github.com/GoogleChrome/puppeteer` should work just fine; I'm not sure why it wouldn't work.

**Comment by murilozilli** [comment]
@aslushnikov It installed it but I couldn't use the normal way. It would always try to use the `node6` folder which is inexistent on the master branch apparently throwing an fatal error even though I use node v8.9.0. I tried to change the index.js file but without success.

**Comment by aslushnikov** [comment]
@murilozilli in case of node-6, you'd need to do additional step (sorry about this, we've never documented this anywhere):

1. goto `node_modules/puppeteer`
2. run `npm run build`

**Comment by daddydrac** [comment]
> @murilozilli in case of node-6, you'd need to do additional step (sorry about this, we've never documented this anywhere):
> 
> 1. goto `node_modules/puppeteer`
> 2. run `npm run build`

Is this still the case in 2020?
