### ISSUE TITLE
innerText fall back to textContent in evaluated function

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#825]
### Steps to reproduce
* Puppeteer version: v0.11.0-alpha
* Platform / OS version: Windows 7 x64
* URLs (if applicable): https://nodejs.org/api/

1. If you open this URL in the very Chromium puppeteer use and run the commands in the console, you can see these results:

![1](https://user-images.githubusercontent.com/10393198/30598572-c07c142a-9d62-11e7-8770-9caf380a8887.png)

2. But this code gives other results:

```js
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://nodejs.org/api/');
  const textContent = await page.evaluate(() =>
    document.body.querySelector('#intro a[href]').textContent);
  const innerText = await page.evaluate(() =>
    document.body.querySelector('#intro a[href]').innerText);

  console.log(JSON.stringify({ textContent, innerText }));

  browser.close();
})();
```
```console
{"textContent":"\n          Node.js\n        ","innerText":"\n          Node.js\n        "}
```

The same results appear with `{ headless: false }`.

This behavior is similar to some tools that do not support layout, only main DOM structure (like JSDOM).

Also, IIRC, this fallback happens in XMLHttpRequest documents because of lack of layout support (they are not rendered).

 Does puppeteer have issues with document layout?

**Comment by pavelfeldman** [comment]
This page has a media query breakpoint, so layout is different in your browser and in puppeteer. Puppeteer defaults to 800x600, while the sidebar you inspect shows up for >1024px. Try adding 

```js
await page.setViewport({width: 1025, height: 768});
```
before `page.goto` in your script and you'll get expected results.

**Comment by vsemozhetbyt** [comment]
@pavelfeldman Thank you!

1. Is there any way to programmatically check these breakpoints' existence on a page?
2. Does `page.setViewport()` call after `page.goto()` update the layout and prevent fallbacks?

**Comment by pavelfeldman** [comment]
> Is there any way to programmatically check these breakpoints' existence on a page?

There is, but media queries are dynamic, so this detection would be racy

> Does page.setViewport() call after page.goto() update the layout and prevent fallbacks?

It updates the layout, but it is hard to tell when MQ-specific resources are loaded, so it is safer to fall back to the navigation-based readiness tracking for consistency.

I understand that these are not the greatest answers, but that's what it is.
