### ISSUE TITLE
Add support for msedge channels

### ISSUE THREAD

**Issue by Meir017** [puppeteer/puppeteer#8259]
Follow-up on #7389.

similar to playwright's ability to use specific edge executables.

the ability to launch msedge:

```js
await puppeteer.launch({
    channel: 'msedge'
});
```

see https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/registry/index.ts

**Comment by jrandolf-google** [comment]
This is not feasible since we cannot guarantee the msedge version uses the same upstream version of chromium. In particular, if we used any random latest version, we could not guarantee Puppeteer will work (hence we will get bug reports out of our control).
