### ISSUE TITLE
There is no way to close script opened windows.

### ISSUE THREAD

**Issue by zxsoft** [puppeteer/puppeteer#826]
**Tell us about your environment:**

* Puppeteer version: v0.10.2
* Platform / OS version: all platforms
* URLs (if applicable): n/a

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. I 'goto' a page(Page A) that will open a new window(advertisement).
2. Because the chrominium don't have adblock installed, the window just opened.
3. I 'goto' another page(Page B). the ad window stay opened.

There for, the window forever stays there, opened.

**What is the expected result?**

1. I want a 'window.open' event. Then I can listen to it and judge wether it will open. 
2. I want a page handler to handle that window. Maybe I need to inspect content in that window,or I can close it using page.close() manually;

**What happens instead?**

I can't find a way preventing the window from opening, neither can I find a way closing the opened window. Please help me out.

P.S. How Can I get the default opened Page handler(the initial about:blank one)?

Thanks!!

**Comment by ebidel** [comment]
We're working on an APIs for enumerating the open pages and catching events when pages open: https://github.com/GoogleChrome/puppeteer/pull/554

Will that work for you?

**Comment by zxsoft** [comment]
YES!!

That's exactly what I'm looking for! And the browser.pages() ! I'd love that!

Thanks so much!  I will close this issue and be looking forward to #554
