### ISSUE TITLE
frame.title() throws protocol error when used with framenavigated

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#827]
Repro: 

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();

page.on('framenavigated', async frame => {
  console.log(await frame.title());
  browser.close();  
});

await page.goto('https://example.com');
```

Produces:

```
Error: Protocol error (Runtime.evaluate): Cannot find context with specified id undefined
```

**Comment by jose920405** [comment]
+1

**Comment by gajus** [comment]
Might be related, https://github.com/GoogleChrome/puppeteer/issues/1325.

**Comment by schelkun** [comment]
Look at Puppeteer and browser ◀ RECV {"method":"Runtime.executionContextDestroyed","params":{"executionContextId":1}}
1510821913549 ◀ RECV {"method":"Runtime.executionContextsCleared","params":{}}

1510821913549 ◀ RECV {"method":"Page.frameNavigated","params":{"frame":{"id":"(18AA6B65BF4D232A98D4234ADE302876)","loaderId":"3902379.2","url":"https://example.com/","securityOrigin":"https://example.com","mimeType":"text/html"}}}

1510821913550 SEND ► {"id":15,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"() =>  document.title","executionContextId":1,"arguments":[],"returnByValue":false,"awaitPromise":true}}

1510821913550 ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":2,"origin":"https://example.com","name":"","auxData":{"isDefault":true,"frameId":"(18AA6B65BF4D232A98D4234ADE302876)"}}}}

1510821913550 ◀ RECV {"method":"Network.loadingFinished","params":{"requestId":"3902379.1","timestamp":1374155.700265,"encodedDataLength":1450}}
1510821913551 ◀ RECV {"method":"Page.domContentEventFired","params":{"timestamp":1374155.704123}}
1510821913551 ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(18AA6B65BF4D232A98D4234ADE302876)","loaderId":"3902379.2","name":"DOMContentLoaded","timestamp":1374155.704123}}
1510821913555 ◀ RECV {"method":"Page.loadEventFired","params":{"timestamp":1374155.704757}}
1510821913557 ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(18AA6B65BF4D232A98D4234ADE302876)","loaderId":"3902379.2","name":"load","timestamp":1374155.704757}}
1510821913557 ◀ RECV {"method":"Page.frameStoppedLoading","params":{"frameId":"(18AA6B65BF4D232A98D4234ADE302876)"}

1510821913557 ◀ RECV {"error":{"code":-32000,"message":"Cannot find context with specified id"},"id":15}

(node:3902334) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
```

**Comment by schelkun** [comment]
Look at Puppeteer and browser communication:
```
◀ RECV {"method":"Runtime.executionContextDestroyed","params":{"executionContextId":1}}
◀ RECV {"method":"Runtime.executionContextsCleared","params":{}}

◀ RECV {"method":"Page.frameNavigated","params":{"frame":{"id":"(18AA6B65BF4D232A98D4234ADE302876)","loaderId":"3902379.2","url":"https://example.com/","securityOrigin":"https://example.com","mimeType":"text/html"}}}

SEND ► {"id":15,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"() =>  document.title","executionContextId":1,"arguments":[],"returnByValue":false,"awaitPromise":true}}

◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":2,"origin":"https://example.com","name":"","auxData":{"isDefault":true,"frameId":"(18AA6B65BF4D232A98D4234ADE302876)"}}}}

◀ RECV {"method":"Network.loadingFinished","params":{"requestId":"3902379.1","timestamp":1374155.700265,"encodedDataLength":1450}}
◀ RECV {"method":"Page.domContentEventFired","params":{"timestamp":1374155.704123}}
◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(18AA6B65BF4D232A98D4234ADE302876)","loaderId":"3902379.2","name":"DOMContentLoaded","timestamp":1374155.704123}}
◀ RECV {"method":"Page.loadEventFired","params":{"timestamp":1374155.704757}}
◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"(18AA6B65BF4D232A98D4234ADE302876)","loaderId":"3902379.2","name":"load","timestamp":1374155.704757}}
◀ RECV {"method":"Page.frameStoppedLoading","params":{"frameId":"(18AA6B65BF4D232A98D4234ADE302876)"}

◀ RECV {"error":{"code":-32000,"message":"Cannot find context with specified id"},"id":15}

(node:3902334) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
```
`executionContextCreated` recieved after `Page.frameNavigated`, maybe this is the bug?
