### ISSUE TITLE
CORS on iFrame causes waitForSelector to indefinitely block

### ISSUE THREAD

**Issue by matthewerwin** [puppeteer/puppeteer#828]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Mac/ Sierra - 10.12.6
* URLs (if applicable): 

**What steps will reproduce the problem?**

1. Use page.setContent( ) to write an iFrame into the browser
e.g.
```
await page.setContent(
      '<iframe id="map" src="https://www.google.com/maps/embed/v1/place?q=TEST&zoom=12&key=" height="1200px" width="1200px"></iframe>');
```
2. Call page.waitForSelector
```
await page.waitForSelector('.place-name', {timeout: 500});
```

**What is the expected result?**
Expect the waitForSelector to either return or throw a timeout

**What happens instead?**

waitForSelector call indefinitely blocks -- this only occurs when using the "." for a class selector -- seems to be okay when using "#"

**Comment by yanivefraim** [comment]
@aslushnikov, @matthewerwin  - I cannot reproduce this (using both Puppeteer 1.4 and 0.10.2):

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.setContent(
    '<iframe id="map" src="https://www.google.com/maps/embed/v1/place?q=TEST&zoom=12&key=" height="1200px" width="1200px"></iframe>');
  await page.waitForSelector('.place-name', {timeout: 500});

  await browser.close();
})();
```

I get:

```bash
(node:8448) UnhandledPromiseRejectionWarning: Error: waiting failed: timeout 500ms exceeded
```

**Comment by aslushnikov** [comment]
Thanks @yanivefraim
