### ISSUE TITLE
can i disable async ?

### ISSUE THREAD

**Issue by codenoid** [puppeteer/puppeteer#829]

**Comment by ebidel** [comment]
I assume you mean not use async/await? Your can you regular promises (.then) calls if that's what you prefer.

**Comment by codenoid** [comment]
@ebidel can you give me example from screenshot code example ?

**Comment by ebidel** [comment]
```
const puppeteer = require('puppeteer');
puppeteer.launch().then(browser => {
  browser.newPage()
      .then(page => page.goto('https://example.com'))
      .then(resp => page.screenshot({path: 'example.png'}))
      .then(buffer => browser.close());
});
```

https://developers.google.com/web/fundamentals/getting-started/primers/async-functions is a good resource.

**Comment by matthew-churcher** [comment]
Awesome, should add this to the code examples. Aws lambda just released nodejs 6.10

**Comment by lydiali9** [comment]
It`s really useful for me

**Comment by datasunny** [comment]
@ebidel code doesn't seem working with node v10.4.1 + puppeteer v1.5.0:

(node:19155) UnhandledPromiseRejectionWarning: ReferenceError: page is not defined
    at browser.newPage.then.then.resp (~/program/puppeteer/test.js:5:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by evll** [comment]
Here is a working version of the code above (fixed UnhandledPromiseRejectionWarning):

```
const puppeteer = require('puppeteer');

puppeteer.launch().then(browser => {
  browser.newPage()
    .then(page => {
      page.goto('https://www.google.com')
        .then(resp => page.screenshot({path: 'example.png'}))
        .then(buffer => browser.close());
    });
});
```

**Comment by karthigb** [comment]
This isn't a clean option for some use cases. I'm trying to migrate from Selenium (Java) to Puppeteer so that I can take advantage of headless Chrome in GC Functions. However, Selenium code in Java is way easier to maintain if you require synchronicity.  If I were to convert my code to synchronous Puppeteer, there'd be nested promises trailing off to the right.

**Comment by aslushnikov** [comment]
@karthigb we strongly recommend using `async/await` when working with Puppeteer; this should make migration much easier. The only case where you can't use `async/await` is running in Node6, but Node6 [will be end-of-lifed](https://nodejs.org/en/blog/release/v6.9.0/) in half a year, so I'd suggest to not use it for anything new.

**Comment by karthigb** [comment]
@aslushnikov Thank you :)

I have a Selenium script that automates web application form processing. I have it stepping through a twenty page application process that must be done sequentially. 

How can I accomplish this cleanly with `async/await`?

**Comment by TomasHubelbauer** [comment]
@karthigb You need to rewrite it to the equivalent APIs of Puppeteer anyway, when it comes to `async`/`await`, you just add the keyword between any Puppeteer API call, if I may simplify. If you are imagining any processes will run in parallel, that's not the case. The processing will still be sequential, just asynchronous.

**Comment by karthigb** [comment]
Asynchronous presents a problem for me.

I have 10-15 questions that need to be answered across numerous pages. The questions must be answered in the right order. The number of questions answered, and the question pagination will depend on the answers provided.

Selenium for Java works. Selenium for Node does not.

I would love to move on to GCF, but fear this is a blocker.

**Comment by aslushnikov** [comment]
> Selenium for Java works. Selenium for Node does not.

@karthigb Puppeteer has no relation to Selenium; Puppeteer is a separate product with a separate codebase.

> I have 10-15 questions that need to be answered across numerous pages. The questions must be answered in the right order. The number of questions answered, and the question pagination will depend on the answers provided.

This is a typical scenario for puppeteer; I'd encourage you to give it a try.

**Comment by karthigb** [comment]
@aslushnikov  Puppeteer has no relation to Selenium? Crap, seriously!?!?!

**Comment by karthigb** [comment]
@aslushnikov I'll give it another go ;)
But I'm also running into this:
https://github.com/GoogleChrome/puppeteer/issues/3223

**Comment by karthigb** [comment]
@aslushnikov I owe you a big thanks. Everything works beautifully. Puppeteer is much faster and more reliable than Selenium. Being able to run it from GCF will save me a lot of overhead. Thank you!

**Comment by Atharv-Chaudhari** [comment]
> Here is a working version of the code above (fixed UnhandledPromiseRejectionWarning):
> 
> ```
> const puppeteer = require('puppeteer');
> 
> puppeteer.launch().then(browser => {
>   browser.newPage()
>     .then(page => {
>       page.goto('https://www.google.com')
>         .then(resp => page.screenshot({path: 'example.png'}))
>         .then(buffer => browser.close());
>     });
> });
> ```

Hello can i have on help please here, how can I fill input in search-box of the website in this code ? giving me few errors... like 
throw new Error('Execution context was destroyed, most likely because of a navigation.');
              ^

Error: Execution context was destroyed, most likely because of a navigation.
