### ISSUE TITLE
[Bug]: Don't emit Page.load relying on Page.loadEventFired

### ISSUE THREAD

**Issue by kblok** [puppeteer/puppeteer#8300]
### Bug description

I've got [on issue](https://github.com/hardkoded/puppeteer-sharp/issues/1841) on puppeteer-sharp, reporting that some `load` events are missing under heavy load.

I say that [playwright doesn't rely on the Page.loadEventFired](https://github.com/microsoft/playwright/blob/c0f097905597c8b5d16fd5532872cd85c885ccdc/packages/playwright-core/src/server/frames.ts#L570) CDP event, but on the lifecycle event.

What do you think about that? Is something to review on chromium? Would you accept a PR changing that behavior?

### Puppeteer version

13.7

### Node.js version

14

### npm version

6

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
Hey, thanks for the report. It'd be great to have a reproduction of what's going on to make sure we fix the right thing. In general, I think we could rely on lifecycle events only, especially, if it makes the code simpler so happy to take a look at a PR.
