### ISSUE TITLE
Puppeteer fails in Docker when an emulator is used and a full-page screenshot is taken

### ISSUE THREAD

**Issue by Jeiwan** [puppeteer/puppeteer#831]
We have a Puppeteer script that takes screenshots of web pages. We want to have mobile device emulation and take full-page screenshots. On my Mac Book Pro everything works fine, but the script fails in a Docker container.  And it fails when both the emulation and full-page features are enable.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Debian Stretch, kernel 4.9.49-moby (Docker image)

**What steps will reproduce the problem?**
I prepared a Docker image: https://github.com/Jeiwan/pup-emulator-bug You need to clone the repo and run `make docker-run`. It will build an image and run the script inside a container, but the script will fail.

If the `fullPage: true` option is removed, the script works fine. It also works fine locally on my MacBook when `fullPage` is `true`.

**What is the expected result?**
It should take a screenshot of a page.

**What happens instead?**
It fails with:

```
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The fail is also reproducible on https://www.washingtonpost.com/

**Comment by ebidel** [comment]
Perhaps related to the shared memory space being very limited (64mb) when running Chrome in docker. There's a suggestion on https://github.com/GoogleChrome/puppeteer/issues/809 that may help.

**Comment by BkSouX** [comment]
Related to my issue #811 as well

**Comment by Jeiwan** [comment]
Seems like increasing `shm-size` helped! I'll run more tests and reply with results in a couple of days.

**Comment by Jeiwan** [comment]
Confirmed, it works! I added `--shm-size=1gb` flag to `docker run`.
@ebidel Thank you!

**Comment by luoyjx** [comment]
if you are using k8s contianer , maybe you can `launch` with arg `--disable-dev-shm-usage`, working for me.
