### ISSUE TITLE
how to close one page

### ISSUE THREAD

**Issue by tamtc84** [puppeteer/puppeteer#832]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

const page = await browser.newPage();

**What is the expected result?**
when i create many page by "browser.newPage()", i want to close one page, not close page. 
How to do it, please? 
Thank you very much.

**What happens instead?**

**Comment by Khady** [comment]
What is wrong with [`page.close`](https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#pageclose) for this use case?
