### ISSUE TITLE
node install.js failed on CentOS7. node v8.4.0 & npm v5.3.0

### ISSUE THREAD

**Issue by wj-1993** [puppeteer/puppeteer#833]
> puppeteer@0.10.2 install /home/wxjg/nodetask/node_modules/puppeteer
> node install.js

/home/wxjg/nodetask/node_modules/puppeteer/install.js:35
    .then(() => Promise.all(allRevisions.map(({platform, revision}) => Downloader.removeRevision(platform, revision))))
                                              ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
npm WARN nodeserver@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ebidel** [comment]
Please make sure you're using node 7+.

**Comment by VonJie** [comment]
@ebidel node 8.4.0

**Comment by wj-1993** [comment]
@ebidel you're right.There are two node on CentOS
