### ISSUE TITLE
[Bug]: Failed to launch the browser process!

### ISSUE THREAD

**Issue by msrumon** [puppeteer/puppeteer#8343]
### Reproduction Steps

1. Clone <https://github.com/msrumon/puppeteer-browser-launch-issue>.
2. Follow the `README`.

### Sample Code

```javascript
import Puppeteer from 'puppeteer';
const browser = await Puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://www.google.com');
await page.screenshot({ path: './out/google.png' });
await page.close();
await browser.close();
```

### Puppeteer version

14.1.0

### Node.js version

16.15.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Failed to launch the browser process! spawn /app/node_modules/puppeteer/.local-chromium/linux-991974/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

**Comment by OrKoN** [comment]
I think the error like this could have many reasons and is likely to have nothing to do with Node 14. I recommend checking out https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker and modifying the docker file accordingly. The script you provided works without Docker so it's the matter of the docker file configuration and installing missing dependencies most likely. The work on the official Docker image for Puppeteer can be tracked here https://github.com/puppeteer/puppeteer/pull/8315 Until that is finished the troubleshooting md doc is the best we have.
