### ISSUE TITLE
cannot get valid href from $$eval()

### ISSUE THREAD

**Issue by GeraldTrost** [puppeteer/puppeteer#8349]
artmiami.com uses "a href='/admin'" on many pages.
pg.$$eval('a', (El) => El.map((el) => el.href)) 
returns results links like "artmiami.com/hotels/admin" or  "artmiami.com/logos/admin"
when it should return "/admin" or "artmiami.com/admin"
I could work around if it were possible to get the el.html() in $$eval()

**Comment by GeraldTrost** [comment]
info:
I managed to workaround with el.getAttribute('href')
anyway, the use of el.href should not generate INVALID url.

**Comment by OrKoN** [comment]
I does not look like an issue with Puppeteer. I think that's just the difference between attributes and properties in DOM: https://stackoverflow.com/a/6004028/601499
