### ISSUE TITLE
Verizon Integration - Complaining about the browser

### ISSUE THREAD

**Issue by sean-hill** [puppeteer/puppeteer#835]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2 and 0.11.0-alpha
* Platform / OS version: Mac OSX

**What steps will reproduce the problem?**

I'm creating a Verizon integration to fetch my data. When using `page.setRequestInterceptionEnabled(true)`, after submitting my credentials, Verizon complains with this:

![example](https://user-images.githubusercontent.com/1205866/30658586-0b6b7bbe-9df0-11e7-96fa-7063dc80cb90.png)

If I remove the `page.setRequestInterceptionEnabled(true)` code, everything works dandy. Here's a script to reproduce, obviously fill in your Verizon credentials, if you don't use Verizon, darn it.

```js
const puppeteer = require('puppeteer')

const run = async () => {
  const browser = await puppeteer.launch({
    headless: false
  })
  const page = await browser.newPage()

  // Comment this out to have the Verizon dashboard page load dandy
  await page.setRequestInterceptionEnabled(true)
  page.on('request', interceptedRequest => {
    // I'd like to add some custom code here to keep track of requests,
    // but for now, just continue every request
    interceptedRequest.continue()
  })
  // End problem section

  await page.goto('https://login.verizonwireless.com/amserver/UI/Login')
  await page.focus('#IDToken1')
  await page.type('YOUR_USERNAME', { delay: 20 })
  await page.click('#login-submit')
  await page.waitFor('#loginForm,.o-emergency-notice,#challengequestion')
  await page.waitFor(1000)
  const mfa = await page.$('#challengequestion')

  if (mfa) {
    await page.focus('#IDToken1')
    await page.type('YOUR_MFA_ANSWER', { delay: 20 })
    await page.click('#challengequestion button.o-red-button[type="submit"]')
    await page.waitFor('.o-emergency-notice,.o-icon-sign-out,#IDToken2')
  }

  await page.focus('#IDToken2')
  await page.type('YOUR_PASSWORD', { delay: 20 })
  await page.click('#loginForm button[class="o-red-button"]')
  await page.waitFor(
    '.o-emergency-notice,.o-icon-sign-out,#challengequestion,#modifyprofile,#main-header,#IDToken6,.fios-welcome',
    { timeout: 30000 }
  )

  await page.waitFor(2000)
  await page.screenshot({ path: 'example.png' })
  await browser.close()
}

run()
  .then(() => process.exit())
  .catch(() => process.exit())
```

Include this script in a folder where `puppeteer` is installed, and then run `node scriptname.js`.

**What is the expected result?**

I expect Verizon to let me into my data without complaining, even if I'm keeping track of my requests.

**What happens instead?**

Verizon states `You may be experiencing an issue with your browser`.

**Comment by Garbee** [comment]
Smells like a duplicate of #662.

**Comment by aslushnikov** [comment]
This seems to be a dupe of #686: request interception is not doing a good job sending all the right headers.

**Comment by Clinton-Cochrane** [comment]
I know this is closed, but I am trying to figure out how to handle MFA. How did you do it?
