### ISSUE TITLE
Can't install Firefox puppeteer on Windows 10

### ISSUE THREAD

**Issue by Ibexlol** [puppeteer/puppeteer#8354]
### Bug description

I'm on windows 10, and i can't install firefox puppeteer for some reason
every way i've tried i get the same error on and on again can anyone help?

### Puppeteer version

v13.5.2

### Node.js version

v17.0.1

### npm version

8.1.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
PUPPETEER_PRODUCT=firefox : The term 'PUPPETEER_PRODUCT=firefox' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PUPPETEER_PRODUCT=firefox:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by ergunsh** [comment]
Hey hey, thanks for the catch and sorry for the confusion!

`npm i puppeteer` uses `PUPPETEER_PRODUCT` environment variable to decide which browser to install. In Windows PowerShell, you can set this environment variable for the PowerShell session with `$Env:PUPPETEER_PRODUCT = 'firefox'`. After setting this environment variable, the run for `npm install puppeteer` will install firefox.

So, you can run these commands in sequence to install Puppeteer with Firefox in Windows PowerShell.
1. `$Env:PUPPETEER_PRODUCT = 'firefox'`
2. `npm install puppeteer`

Let me know if it doesn't work for you and feel free to reopen the bug in that case :)

**Comment by Ibexlol** [comment]
Hi so i've been trying to make an image scraper for my discord bot (the installation worked fine thanks for that) but i keep on getting a certain error with it
![image](https://user-images.githubusercontent.com/77413092/169715955-ec244fb6-18ff-498b-978f-7c767b5955cf.png)
