### ISSUE TITLE
Page.printToPDF timeout

### ISSUE THREAD

**Issue by caozku** [puppeteer/puppeteer#8356]
### Steps to reproduce

**Tell us about your environment:**

- Puppeteer version: ^14.1.0
- Platform / OS version: win10
- URLs (if applicable):
- Node.js version: 16.13.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.html file size 68M
2.TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded
3.

**What is the expected result?**

**What happens instead?**

**Comment by caozku** [comment]
why close my issue

**Comment by jrandolf-google** [comment]
We cannot debug the problem with the given information. Please fill the form comprehensively, otherwise we must close the issue as a `wontfix`.
