### ISSUE TITLE
PDF tags

### ISSUE THREAD

**Issue by cyrusho100** [puppeteer/puppeteer#8380]
### Bug description

I am using page.pdf to convert HTML content to PDF document. Is there any method to return where particular element, e.g. "H2", locates in the output? or adding "Page" tag to wrap all the other tags on the page.

![example](https://user-images.githubusercontent.com/52916238/169470119-46ee0bd6-c83e-437d-abbf-ee8049ebf324.png)

### Puppeteer version

13.7.0

### Node.js version

16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
I am not aware of anything to achieve this. I guess it's a feature request then? Puppeteer just asks the browser to generate a PDF and we don't parse/process the PDF output in any way.

**Comment by jrandolf-google** [comment]
This is out of scope for Puppeteer. In particular, there doesn't seem to be a valid use case considering `pdf` testing is not a thing (you would manually look at it anyway).
