### ISSUE TITLE
Could not find browser revision latest

### ISSUE THREAD

**Issue by Ibexlol** [puppeteer/puppeteer#8384]
### Bug description

I'm making a image scraper discord bot and i keep on getting errors here's the code:
![image](https://user-images.githubusercontent.com/77413092/169716656-f7729bbe-f46d-4d72-8837-5046b0522395.png)

### Puppeteer version

v14.1.1

### Node.js version

v17.0.1

### npm version

v8.1.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Error: Could not find browser revision latest. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at FirefoxLauncher.launch (C:\Users\Administrator\Desktop\Simba\discordbotz\node_modules\images-scraper\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:193:23)    at async GoogleScraper.scrape (C:\Users\Administrator\Desktop\Simba\discordbotz\node_modules\images-scraper\src\google\scraper.js:53:21)
    at async Object.execute (C:\Users\Administrator\Desktop\Simba\discordbotz\commands\image.js:18:31)
```

**Comment by OrKoN** [comment]
So did you run `npm install` with the specified env variables as the error message suggests?

**Comment by Ibexlol** [comment]
Yes i have, and i still get the error

**Comment by OrKoN** [comment]
@Ibexlol what is the log output of the npm install command with the `PUPPETEER_PRODUCT=firefox` command? Note that on Windows you probably need to use a different syntax to set env variables depending on whether you use PowerShell or Command Prompt.

**Comment by Ibexlol** [comment]
I do set the PUPPETEER_PRODUCT=firefox as an env variable it installs of course, but when i run the command i still get the same error
