### ISSUE TITLE
[Bug]: M1 run firefox test error...

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [puppeteer/puppeteer#8385]
### Bug description

I'm try to ..

```
import puppeteer, { Product, LaunchOptions, Browser, Page } from 'puppeteer-core';
const launch  = async function(url: string ,options) {
  let brower: Browser
  let page: Page
  const _opts = {
    // args: ['--no-sandbox', '--disable-setuid-sandbox'],
    // executablePath: process.env.PUPPETEER_EXECUTABLE_PATH,
    args: ['-wait-for-browser'],
    executablePath: '/Applications/Firefox.app/Contents/MacOS/firefox',
    product: "firefox" as Product,

    ...options,
  }
  brower = await puppeteer.launch(_opts)
  page = await brower.newPage()
  page.goto(url)
  return {
    brower,
    page,
    close: () => {
      brower.close()
    }
  }
}

export default launch

```
It run the fixfox but error

```
ProtocolError: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id callFunctionOn@chrome://remote/content/cdp/domains/content/Runtime.jsm:218:15
    execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
    receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45
```

 test('show page', async() => {
    > 18 |     const text  = await ctx.page.$eval('h3', node => node.outerHTML)

### Puppeteer version

14.1.1

### Node.js version

v14.18.2

### npm version

8.8.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
$ jest
 FAIL  __tests__/firefox.ts
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (../../../node_modules/@jest/core/build/TestScheduler.js:175:18)
      at ../../../node_modules/@jest/core/build/TestScheduler.js:304:17
      at ../../../node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.Typed.emit (../../../node_modules/emittery/index.js:258:23)

 FAIL  __tests__/components.spec.ts (5.873 s)
  ● new page › show page

    ProtocolError: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id callFunctionOn@chrome://remote/content/cdp/domains/content/Runtime.jsm:218:15
    execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
    receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.jsm:84:45

      16 |   })
      17 |   test('show page', async() => {
    > 18 |     const text  = await ctx.page.$eval('h3', node => node.outerHTML)
         |                   ^
      19 |     // console.log(text);
      20 |     expect(text).toEqual('Components')
      21 |     // await ctx.page.reload({

      at node_modules/puppeteer-core/src/common/Connection.ts:304:16
      at CDPSession.send (node_modules/puppeteer-core/src/common/Connection.ts:300:12)
      at ExecutionContext._evaluateInternal (node_modules/puppeteer-core/src/common/ExecutionContext.ts:254:44)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer-core/src/common/ExecutionContext.ts:193:17)
      at ElementHandle.evaluateHandle (node_modules/puppeteer-core/src/common/JSHandle.ts:194:42)
      at Object.internalHandler.queryOne (node_modules/puppeteer-core/src/common/QueryHandler.ts:68:38)
      at ElementHandle.$ (node_modules/puppeteer-core/src/common/JSHandle.ts:1072:25)
      at ElementHandle.$eval (node_modules/puppeteer-core/src/common/JSHandle.ts:1110:38)
      at DOMWorld.$eval (node_modules/puppeteer-core/src/common/DOMWorld.ts:212:21)
      at Object.<anonymous> (__tests__/components.spec.ts:18:19)

Test Suites: 2 failed, 2 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.511 s, estimated 8 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by whimboo** [comment]
@Kujo-Jotaro-AAAAA you should await the call to `page.goto`. Does that fix the issue for you?

**Comment by Kujo-Jotaro-AAAAA** [comment]
> @Kujo-Jotaro-AAAAA you should await the call to `page.goto`. Does that fix the issue for you?

no..   page.goto has been timeout

```
TimeoutError: Navigation timeout of 30000 ms exceeded

      56 |                 case 2:
      57 |                     page = _a.sent();
    > 58 |                     return [4, page.goto('http://localhost:1234', {
         |                                     ^
      59 |                             waitUntil: 'networkidle0'
      60 |                         })];
```

**Comment by Kujo-Jotaro-AAAAA** [comment]
I'm use `PUPPETEER_PRODUCT=firefox npm i puppeteer`
puppeteer v14.1.1

```
expect(await ctx.page.title()).toEqual("my-title")
```

It reported a mistake

```bash
ProtocolError: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id callFunctionOn@chrome://remote/content/cdp/domains/content/Runtime.jsm:218:15
```

It's my config
```bash
 const browser = await puppeteer.launch({
    args: ['-wait-for-browser'],
    executablePath: '/Applications/Firefox.app/Contents/MacOS/firefox',
    product: "firefox" as Product,
  })
```

**Comment by whimboo** [comment]
> TimeoutError: Navigation timeout of 30000 ms exceeded
> 
>       56 |                 case 2:
>       57 |                     page = _a.sent();
>     > 58 |                     return [4, page.goto('http://localhost:1234', {
>          |                                     ^
>       59 |                             waitUntil: 'networkidle0'
>       60 |                         })];

In your original message you didn't mention that you are using `networkidle0`. Note that this setting is not supported with Firefox. And as such it's expected to run into a timeout because this specific event will never be sent out by Firefox. See issue #5841 for details covering this scenario.

> ```shell
> ProtocolError: Protocol error (Runtime.callFunctionOn): Cannot find context with specified id callFunctionOn@chrome://remote/content/cdp/domains/content/Runtime.jsm:218:15
> ```

What kind of URL are you loading here? Is it the one from `localhost` or another one that you may wanna share with us? 

It would be great to get a trace log attached. Therefore please [set the `dumpio` option to `true` when launching the browser, and also set the Firefox preference `remote.log.level` to `Trace`](https://github.com/puppeteer/puppeteer/blob/main/examples/cross-browser.js#L20-L25). Then run your test again and attach the log output to this issue. Thanks!

**Comment by Kujo-Jotaro-AAAAA** [comment]
> set the `dumpio` option to `true` when launching the browser, and also set the Firefox preference `remote.log.level` to `Trace`

I update my options

```
    const _opts = {
      args: ['-wait-for-browser'],
      product: "firefox" as Product,
      headless: false,
      slowMo: 250,
      dumpio: true,
    }
```

it can't worked...

```bash
  ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.

    > 22 |     const iframeHandle = await page.$('body')
```

**Comment by whimboo** [comment]
I don't see that you have set the mentioned Firefox preference. The log output should then give way more lines. And I would need a bit more than just this single line. To reproduce a small testcase would be helpful as well.

**Comment by realivanjx** [comment]
im using flaresolverr and got this same error on my raspberry pi 4. works fine on my desktop pc (amd64)

**Comment by whimboo** [comment]
@realivanjx which URL are you navigating to? Is it causing a COOP navigation? See https://github.com/puppeteer/puppeteer/issues/8385#issuecomment-1135470259 in how to generate a log file that could be used to further investigate the issue.

Also not sure what you are referencing with `this same error`. Is it `Cannot find context with specified id`?
