### ISSUE TITLE
`frame.evaluate` freezes / hangs

### ISSUE THREAD

**Issue by AlbertoFDR** [puppeteer/puppeteer#8399]
### Steps to reproduce

**Tell us about your environment:**

- Puppeteer version: 14.1.1
- Platform / OS version: Debian GNU/Linux 11
- URLs (if applicable): https://www.nytimes.com/video
- Node.js version: v17.9.0

**What steps will reproduce the problem?**
Repro code:
```
const puppeteer = require("puppeteer");
const url = "https://www.nytimes.com/video" 

function sleep(ms) {
    return new Promise((resolve) => {
        setTimeout(resolve, ms);
    });
}

(async () => {
    const browser = await puppeteer.launch({
        executablePath: '/usr/bin/google-chrome',
        headless: false
    });
    const page = await browser.newPage();
    await page.goto(url);
    await sleep(5000);

    for (const frame of page.frames()){
        console.log(frame._url);
        console.log(frame._loaderId);
        console.log(frame._id);
        let result = await frame.evaluate(() => console.log('Look! I am inside iframe!'));
        console.log("#######");
    }
    console.log("Finished!");

    await browser.close();
})();
```

**What is the expected result?**
The expected result is to execute the evaluation code inside each of the frames.

**What happens instead?**
The `frame.evaluate` gets freeze on the 5th frame always.

Thanks :)

**Comment by jrandolf-google** [comment]
This can happen if the frame is [lazy-loaded](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes). Can you check that all frames in the link are not lazy-loaded? In particular, I believe this can be fixed if you scroll to the frame.

**Comment by AlbertoFDR** [comment]
Could you please give me more info about how to debug/find that? :) 
I have tried doing manually interaction (scrolling down...) on the website before evaluating JS inside iframes but it doesn't work. Some of the attributes of the problematic iframe are empty such as URL (url = ''") and if I use methods like `problematic_iframe.content()` it gets stuck so Idk how to debug that iframe. Apart from that, I have searched the `loading="lazy"` on all the iframe's using the browser console.

My guess is the problem occurs with the following nested iframes. The first iframe that appears on the screenshot is the parent of the problematic iframe but it shouldn't get stuck.
![image](https://user-images.githubusercontent.com/21290259/172425848-011d53b1-2856-49dd-8925-28f50219bf69.png)
