### ISSUE TITLE
Allow to ignore certificate errors during navigation

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#84]
There should be a capability to ignore certificate errors during navigation. See https://github.com/GoogleChrome/puppeteer/issues/66 for proposal and https://github.com/cyrus-and/chrome-remote-interface/issues/183 for original discussion.

For example, we can add `ignoreSSL` navigation option:

```js
page.navigate('https://example.com', { ignoreSSL: true })
```

**Comment by paulirish** [comment]
naming pedantry: SSL (which is dead and now really TLS these days) is about the connection, whereas certificates are about identification. So it turns out certificate errors aren't really TLS issues. In order to simplify all this, folks normally just call the whole kit-and-kaboodle "HTTPS" which seems generally agreeable.

So I'd start with calling this `ignoreHTTPSerrors`, but a shorter name could be something like:`pardonBadHTTPS`

**Comment by aslushnikov** [comment]
Thanks Paul!

I like the `ignoreHTTPSErrors`. Or how about ironic `pardonHTTPS`?

**Comment by aslushnikov** [comment]
It would be troublesome to implement this per navigation; i'm leaning towards the
```js
page.setIgnoreHTTPSErrors(true);
```

**Comment by Garbee** [comment]
I'd urge it be more tedious to ignore per navigation since you really shouldn't be ignoring problems like that. Even in a test suite, it's not something to encourage.

**Comment by aslushnikov** [comment]
@Garbee do you have any api suggestion?

Having the setter on the page level would allow one to ignore HTTPS errors for the renderer-initiated navigations (those initiated with javascript's `window.location.href = ...`), which is valuable

**Comment by Garbee** [comment]
hmm. If the page level API solves a problem that the navigation function level doesn't, then that's the way to go. I simply didn't want to see it as "cleaner" than needing to repeat it on all the manual navigation from the puppeteer script.

**Comment by aslushnikov** [comment]
More details on this.
The certificates behave a little surprising - once a certain certificate error was "ignored" via protocol's `Security.handleCertificateError`, the certificate would not trigger any errors in future.

This would result in inability to do `Page.setIgnoreHTTPSErrors(false)`, which causes the test failure in the #176.

Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=751204. We spent half a day with @allada debugging the issue but it didn't get us anywhere.

To move on with this, since there's no practical need to do `setIgnoreHTTPSErrors(false)`,  we can have a browser option to ignore HTTPS errors:
```js
const {Browser} = require('puppeteer');
const browser = new Browser({ignoreHTTPSErrors: true});
...
```
