### ISSUE TITLE
Ability to pin version

### ISSUE THREAD

**Issue by michaelgmiller** [puppeteer/puppeteer#840]
It would be great to have the ability to pin the Chromium version. I know it's possible to say `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`, but I'd like to maintain the auto-download functionality while also pinning the version.

**Comment by Garbee** [comment]
We pin the version since it is updated as new features are added/fixed that the new versions use. If you'd like to pin a specific version, then specify an exact `puppeteer` version since that will give you the build of this module with the Chromium package known to work with it.

**Comment by michaelgmiller** [comment]
Oh, didn't realize the version is pinned in `package.json`. Pinning the puppeteer version is a perfect solution for us, thanks!
