### ISSUE TITLE
[QA]: How can I configure PUPPETEER_PRODUCT=firefox into the project?

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [puppeteer/puppeteer#8402]
### Bug description

sorry about then,i don't know how to config this to my project..

`PUPPETEER_PRODUCT=firefox npm i puppeteer`

### Puppeteer version

14.1.1

### Node.js version

14

### npm version

5

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
It is expected that the correct Firefox version can be downloaded when `npm i` or `yarn` is executed
```

**Comment by jrandolf-google** [comment]
Cannot reproduce. Just use `PUPPETEER_PRODUCT=firefox npm i puppeteer` and it should install.
