### ISSUE TITLE
Skip downloading interactive_ui_tests.exe to reduce footprint

### ISSUE THREAD

**Issue by abbr** [puppeteer/puppeteer#842]
* Puppeteer version: 0.10.2
* Platform / OS version: Win 10 x64

On my os platform, Puppeteer folder size is 281mb after downloading latest chromium, of which 107mb is file *interactive_ui_tests.exe*. This file seems only used by chromium for internal tests b/c after deleting it my karma tests still work. 
Can Puppeteer skip downloading it by default, or at least provide an option? Disk/network overhead is a concern to me, comparing to PhantomJS 9mb footprint.

**Comment by Garbee** [comment]
This is a part of the chromium zip itself. No way to get around having to downloaded.

**Comment by Garbee** [comment]
Oh, and to get around it you'd need to install Google Chrome with the Unstable branch and manually call to that when launching puppeteer. Then set the ENV as described in the docs to disable downloading the chromium zip internally completely.

**Comment by abbr** [comment]
I thought *interactive_ui_tests.exe* was separable when looking at specific release [folder](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/503430/). But after downloading only *chrome-win32.zip*, I found the file is also included, so I agree now it's not trivial.

**Comment by entrptaher** [comment]
@Garbee, maybe we can delete the file after downloading? 
`interactive_ui_tests.exe`
It takes 100mb space for no reason.
