### ISSUE TITLE
`page.evaluate` doesn't wait for Promise with setInterval?

### ISSUE THREAD

**Issue by jarib** [puppeteer/puppeteer#844]
* Puppeteer version: 0.10.2
* Platform / OS version: OS X Sierra 10.12.4

I'm trying to scroll incrementally through a page in order to deal with lazy loaded elements. The code works as expected if pasted into the Chrome console, but wrapped in `page.evaluate`, it appears to return instantly – before the scrolling happens or the promise resolves.

```javascript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();

    await page.goto('https://www.nytimes.com/');

    console.log('Scrolling through page');

    await page.evaluate(() => {
        return new Promise((resolve, reject) => {
            try {
                let lastScroll = Number.MAX_SAFE_INTEGER;
                const interval = setInterval(() => {
                    if (lastScroll === document.body.scrollTop) {
                        clearInterval(interval);
                        resolve();
                    } else {
                        lastScroll = document.body.scrollTop;
                        window.scrollBy(0, 100);
                    }
                }, 100);
            } catch (err) {
                console.log(err);
                reject(err.toString());
            }
        });
    });

    console.log('Finished scrolling');
    await browser.close();
})();
```

**Comment by vsemozhetbyt** [comment]
@jarib Some considerations:
1. `document.body.scrollTop` is allways `0` here, so `document.documentElement.scrollTop` could be used instead.
2. You assign `scrollTop` to `lastScroll` each iteration, so `lastScroll = Number.MAX_SAFE_INTEGER` becomes useless and `lastScroll === .scrollTop` is always `true` (so iterations stop after the first cycle).
3. `page.evaluate()` awaits only for the getting function return value wich is unresolved Promise in this case, you should await inside the function.

This code seems to work:
```js
'use strict';

const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();

    await page.goto('https://www.nytimes.com/');

    console.log('Scrolling through page');

    await page.evaluate(async () => {
        await new Promise((resolve, reject) => {
            try {
                const maxScroll = Number.MAX_SAFE_INTEGER;
                let lastScroll = 0;
                const interval = setInterval(() => {
                    window.scrollBy(0, 100);
                    const scrollTop = document.documentElement.scrollTop;
                    if (scrollTop === maxScroll || scrollTop === lastScroll) {
                        clearInterval(interval);
                        resolve();
                    } else {
                      lastScroll = scrollTop;
                    }
                }, 100);
            } catch (err) {
                console.log(err);
                reject(err.toString());
            }
        });
    });

    console.log('Finished scrolling');
    await browser.close();
})();
```

**Comment by jarib** [comment]
Fantastic. Using `await` inside the function and switching to `document.documentElement` did the trick. Thanks!

**Comment by ebidel** [comment]
Pro tip: use `document.scrollingElement` to find the scrolling element of the page. Usually, that's body or html.

**Comment by chenxiaochun** [comment]
`autoScroll()`, the below is my implementation:

```javascript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.goto('https://www.jd.com');
  await page.setViewport({
  	width: 1200,
  	height: 800
  });

  await autoScroll(page);
  
  await page.screenshot({
  	path: 'jd.png',
  	fullPage: true
  });

  await browser.close();
})();


function autoScroll(page){
    return page.evaluate(() => {
        return new Promise((resolve, reject) => {
            var totalHeight = 0;
            var distance = 100;
            var timer = setInterval(() => {
                var scrollHeight = document.body.scrollHeight;
                window.scrollBy(0, distance);
                totalHeight += distance;

                if(totalHeight >= scrollHeight){
                    clearInterval(timer);
                    resolve();
                }
            }, 100);
        })
    });
}
```

**Comment by liormarga** [comment]
what about 
page.keyboard.press('ArrowDown');

**Comment by ericcirone** [comment]
@vsemozhetbyt Thanks a lot! Your code was exactly what I was looking for.

**Comment by wilbyang** [comment]
@vsemozhetbyt I run your snippets, it runs well with 'https://www.nytimes.com/'. But if I change it be 'https://www.pinterest.se/'. The  browser just exit without reason and warning or error. Do you know why? Would you please give me a clue?

**Comment by vsemozhetbyt** [comment]
@wilbyang Do you use a new Chrome profile? With a new profile, I see the page with a login form that seems to block any page interaction (`window.scrollBy(0, 100)` does not work so the script thinks the max scroll limit is reached).

If I use a more definite URL, like https://www.pinterest.se/search/pins/?q=Photography, the login dialog does not appear and the script works properly (however I cannot wait until scroll end).

**Comment by usworked** [comment]
Great! Thank you!! 

If only there was a way now to scroll through a specific div instead of the entire page :/

**Comment by chenxiaochun** [comment]
@ubaidseth 

For example, there is a div element in body.

```html
<div class="box"></div>
```

```css
.box{
    width: 200px;
    height: 200px;
    border: 1px solid green;
    overflow: scroll;   
}
```

I think you can set it's scrollTop in order to scroll it:

```js
var box = document.querySelector('.box');
var n = 0;

var t = setInterval(() => {
    ++n
    box.scrollTop = n;
    if(n > top.scrollHeight){
        clearInterval(t)
    }
})
```
