### ISSUE TITLE
How to catch a "Permission request" dialog event?

### ISSUE THREAD

**Issue by xfumihiro** [puppeteer/puppeteer#846]
![screen shot 2017-09-21 at 7 37 02 pm](https://user-images.githubusercontent.com/12194969/30693950-6bde622a-9e97-11e7-8b2c-9f3ae0fd6e93.png)

**Comment by ebidel** [comment]
There's a feature request upstream to add devtools protocol API sfor granting/denying these types of permissions: https://bugs.chromium.org/p/chromium/issues/detail?id=631464

In Lighthouse, we used to [capture API calls](https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L942-L965) that invoke the prompts. We used that to determine when prompts were being showed.  However, there's no way to block/deny it programmatically.

**Comment by aslushnikov** [comment]
@xfumihiro out of curiosity, what's your usage scenario for this?

**Comment by xfumihiro** [comment]
@aslushnikov I was trying to catch if the "request permission" is issued on the auth/login flow. (Better UX - iff user asked for it 😃 )

**Comment by hotNoder** [comment]
@ebidel Hi, I have a question about the Notification. I use puppeteer to visit a site which alert the notification. If I don't close the notification manually, the program wouldn't go forward.
So there's no way to avoid the notification programmatically?

**Comment by ebidel** [comment]
No there's not. That's the feature request in https://bugs.chromium.org/p/chromium/issues/detail?id=631464.

**Comment by saselovejulie** [comment]
i need geolocation permission... hope this will be release soon

**Comment by CommanderXL** [comment]
@saselovejulie  I try overwrite the method of `getCurrentPosition`, and it work well:

```javascript
navigator.geolocation.getCurrentPosition = function (cb) {
  setTimeout(() => {
    cb({
      'coords': {
        accuracy: 21,
        altitude: null,
        altitudeAccuracy: null,
        heading:null,
        latitude: 23.129163,
        longitude: 113.264435,
        speed:null
      }
    })
  }, 1000)
}
```

**Comment by Skagoo** [comment]
I personally suggest to use a custom user profile that has accepted te prompt before.
You could set this up by running chrome from the command line with the following argument:
`--user-data-dir=/path/to/your/custom/profile`

If the given profile path does not exist it will be created.

Now go to the website that requires you to accept this dialog, accept it manually and close the chrome window.
Now you automatically saved this choice in the custom profile.

Now it is as simple as using the custom profile for your chrome driver, again with the same argument:
`--user-data-dir=/path/to/your/custom/profile`

e.g. In C# Using a Chromedriver with ChromeOptions this would be:
```csharp
ChromeOptions options = new ChromeOptions();
options.AddArgument("--user-data-dir=/path/to/your/custom/profile");
ChromeDriver driver = new ChromeDriver(options);
```

**Comment by ebidel** [comment]
@aslushnikov are you tackling this from the protocol-side? We're getting more inbound requests for an API and it's an important one to have for testing lots of different APIs.

**Comment by aslushnikov** [comment]
> are you tackling this from the protocol-side?

@ebidel yeah, this is in my queue after the browser contexts.

**Comment by ralyodio** [comment]
Any update on this? I'm doing some process of a large list of urls and it renders headless mode basically useless after 2 minutes of scraping if you encounter enough of these.

**Comment by andresilveirah** [comment]
Having the same issue. When launching with `headless: false`, Puppeteer gets stuck when asked for permission for notifications.

**Comment by ralyodio** [comment]
Only way I found was to set headless to true.

**Comment by shmdhussain** [comment]
@aslushnikov @ebidel Is this feature available in Pupeeteer to allow or reject notification prompt? 

If there is, I have one scenario, If you allow the automated browser to accept or deny the notification prompt, every time a new notification prompt is accepted uid is created and  this will cause problems for the web sites who subscribed to the third party notification service where they are capped to limits for number of notifications UIDs

**Comment by andycaramba** [comment]
Adding `--disable-notifications` to Pupeeteer `launch()` args works for me in relation to current issue.  According to [this link](https://peter.sh/experiments/chromium-command-line-switches/#disable-notifications) this argument `Disables the Web Notification and the Push APIs.` but it's ok for my purposes

**Comment by 0x11-dev** [comment]
You can permit geo location api via the new api introduced in v1.8.0. https://pptr.dev/#?product=Puppeteer&version=master&show=api-browsercontextoverridepermissionsorigin-permissions Y
