### ISSUE TITLE
Chrome Headless doesn't work with Google Maps 3D or Google Earth - "Google Earth isn't supported in your browser"

### ISSUE THREAD

**Issue by robjbrain** [puppeteer/puppeteer#847]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: Ubuntu 14.04.5 LTS
* URLs (if applicable):
https://www.google.co.uk/maps/@51.6506889,-0.4041839,40a,35y,113.57h,73.36t/data=!3m1!1e3
https://earth.google.com/web/@51.6499525,-0.40162489,64.98644774a,251.31324967d,35y,111.968

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

async function run() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.setViewport({width:2880, height:1800});
    await page.goto('https://www.google.co.uk/maps/@51.5516152,0.7010375,66a,35y,170.86h,79.21t/data=!3m1!1e3', {"waitUntil" : "networkidle"});
    await page.screenshot({ path: './example-2d.png' });

    browser.close();
}

run();
```
**What is the expected result?**

I expect the result to render the same way as it does in the Chrome Browser for desktop.

**What happens instead?**

For the google maps link it renders in 2D rather than 3D.

For google earth an error message is given:

> Aw Snap! The new Google Earth isn't supported by your browser yet. Try this link in Chrome instead. If you don't have Chrome installed, download it here

**Comment by ebidel** [comment]
I got the 3d version on Mac. Since Puppeteer uses`--disable-gpu` by default, I wonder if that affects the 3d webgl version of maps on Linux.

**Comment by robjbrain** [comment]
Ah that may be it, I may have been using disable-gpu from the command line out of habit as well, I'll try it again

**Comment by ebidel** [comment]
Closing in favor of https://stackoverflow.com/questions/46343607/chrome-headless-doesnt-work-with-google-maps-3d-or-google-earth
