### ISSUE TITLE
[Bug]: page.goto returns null for some urls when setRequestInterception is set to true

### ISSUE THREAD

**Issue by namdardn** [puppeteer/puppeteer#8474]
### Bug description

Steps to reproduce the problem:
```
const puppeteer = require('puppeteer');

const URL = 'https://www.amazon.in';

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on('request', req => req.continue());
  for (var i = 0; i < 10; i++) {
     await page.goto(URL);
     const resp = await page.goto(URL);
     console.log("response: " + resp);
  }
}

main();
```

Returns a response for the first request but all subsequent requests return null
```
response: [object Object]
response: null
response: null
response: null
response: null
response: null
response: null
response: null
response: null
response: null
```

Setting `setRequestInterception` to false or creating a new context for each request using `createIncognitoBrowserContext` fixes the issue. 

The issue only occurs for certain websites. 

### Puppeteer version

14.2.1

### Node.js version

v14.18.0

### npm version

6.14.15

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
Able to reproduce with v16.0.0. It looks though that navigating to the same URL might not trigger the network request/response again? Need to investigated this.

**Comment by OrKoN** [comment]
Not reproducible anymore.
