### ISSUE TITLE
[Bug]: Gmail hangs when setRequestInterception(true)

### ISSUE THREAD

**Issue by nodated** [puppeteer/puppeteer#8479]
### Bug description

Steps to reproduce the problem:

1. Run the code
2. Chromium opens about:blank page and keep loading until timed out
3. Works fine if set interception to false

### Puppeteer version

14.2.1

### Node.js version

16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
const puppeteer = require("puppeteer");

(async() => {
    const browser = await puppeteer.launch({
        headless: false
    })
    const page = await browser.newPage();
    await page.setRequestInterception(true);
    page.on('request', (request) => {
        request.continue();
    });
    await page.goto(`https://mail.google.com/`);
})()
```

**Comment by OrKoN** [comment]
I am able to reproduce on Mac too.

**Comment by OrKoN** [comment]
it turns out that the AcceptCHFrame feature of Chromium is not properly reporting network events.
