### ISSUE TITLE
Error: unexpected server response (500)

### ISSUE THREAD

**Issue by Tin-Nguyen** [puppeteer/puppeteer#848]
I'm facing an issue when running the tool on server for my API service

```sh
2017-09-21 13:31:50.011, [log,ERROR,318e5dea-bac7-431a-a4e5-a45ee059b62c] message: unexpected server response (500), stack: Error: unexpected server response (500)
    at ClientRequest._req.on (/rendering/node_modules/ws/lib/WebSocket.js:656:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:563:20)
```
It doesn't happen on my local (MacOS), but happens on my server (using AWS Linux).

The scenarios I did:
- Chrome instance running in Docker (same host)
- Service using NodeJS 7.7.4

**Comment by Tin-Nguyen** [comment]
I just did try a check by running a command below
```sh
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: echo.websocket.org" -H "Origin:http://www.websocket.org" http://localhost:9222/devtools/page/a79335f8-574d-47>
```
And I received the same error
```sh
HTTP/1.1 500 Internal Server Error
Content-Length:54
Content-Type:text/html
```

Is there a problem with Chrome websocket connection? Anyone know how to fix it?

**Comment by ebidel** [comment]
Can you add dumpio: true to your launch call? That might have more details.
What does your docker run call look like?

**Comment by Tin-Nguyen** [comment]
I don't use `launch` function, I use `connect` since I have a Chrome instance running in Docker already.

**Comment by ebidel** [comment]
Ok, it would be helpful to have more logging from Chrome. Any way to try that?

The reason I ask for the `docker run` command is because some kernels have features shut off. You may have some luck with https://github.com/GoogleChrome/rendertron#connection-error-econnrefused.

**Comment by Tin-Nguyen** [comment]
I'm trying to figure out a way to get the logs from Chrome now. Will get back to you soon if I find out any things.

**Comment by Tin-Nguyen** [comment]
@ebidel , I have just figured out some more information:
If I restart the docker container, and do a request to my service. I will not see the error, instead I see the process is pending on `puppeteer.connect()` command. There is nothing happen after that line.

If I do another request, I will see the error 
```sh
message: unexpected server response (500), stack: Error: unexpected server response (500)
```

Below is the websocket endpoint of Chrome my service attempted to connect
```
ws://localhost:9222/devtools/page/2cd24da2-448c-4462-9055-b63dc234b50d
```

I tried to run docker Chrome instance on my local (MacOS), my service works well with it. Not sure why.

**Comment by Tin-Nguyen** [comment]
Figured out some more:
- I did run my service locally and connect to the docker Chrome instance on server. I got the same issue, I also got the error in logging.

```sh
Connecting to Chrome instance at ws://localhost:9223/devtools/page/a0ef9418-29bf-4e75-a652-d1dfc55bbf39
(node:27314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: object is not defined
(node:27314) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: object is not defined
(node:27314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ReferenceError: object is not defined
(node:27314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): ReferenceError: object is not defined
```

Here is my code:
```javascript
if (this.wsChromeEndpoint) {
    console.log(`Connecting to Chrome instance at ${this.wsChromeEndpoint}`);
    browser = await puppeteer.connect({
      browserWSEndpoint: this.wsChromeEndpoint
    });
  } else {
    browser = await puppeteer.launch({
      dumpio: this.debugMode,
      headless: true
    });
  }

  const page = await browser.newPage();

  page.on('console', console.log);
  ...
}
```
The code is probably proceeded after `connect` call and it stoped at `const page = await browser.newPage();`

**Comment by Tin-Nguyen** [comment]
Got more error on `browser.newPage()`:
```
(node:27424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: path must be a string or Buffer
(node:27424) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: object is not defined
(node:27424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ReferenceError: object is not defined
(node:27424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): ReferenceError: object is not defined
(node:27424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): ReferenceError: object is not defined
```

**Comment by aslushnikov** [comment]
@Tin-Nguyen there's not much I can suggest here; the problem might be anywhere in your service or puppeteer.

Since the issue doesn't repro for you without the docker container, it looks like something's wrong with the environment you're running in - this we can't help with.
