### ISSUE TITLE
[Bug]: page.select not working when the first option has no value

### ISSUE THREAD

**Issue by Narias1999** [puppeteer/puppeteer#8508]
### Bug description

Steps to reproduce the problem:

I have this html markup
```
 <select id="test">
    <option></option>
    <option value="test">Test</option>
    <option value="test2">Test2</option>
    <option value="test3">Test3</option>
    <option value="test4">Test4</option>
  </select>
```
I'm trying to select the Test2 option with the following code:

```
const browser = await puppeteer.launch({ headless: false });
const page = await browser.newPage();
await page.goto('http://127.0.0.1:5500/test.html');
await delay(1000);
const res = await page.select('#test', 'test2');
```

**Result**
The default option (none). Remains selected.

If in the markup I remove the first <option> element (The one that has no value defined), the code works as intended and the test2 option gets selected.
 

### Puppeteer version

14.3.0

### Node.js version

16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

macOS

**Comment by Lorenzras** [comment]
Same issue on windows.

I temporally use the following until this issue got fixed. I tend to stick to this version as it solves other issues for me.

_Typescript_

```
const select = (
  {page, selector, value} :
  {
    page: Page,
    selector: string
    value: string
  },
) => page.$eval(
  selector,
  (el, value) => (<HTMLSelectElement>el).value = <string>value,
  value,
);
```

**Comment by jrandolf-google** [comment]
Fixed in latest release.
