### ISSUE TITLE
[Bug]: waitForNavigation({ waitUntil: 'networkidle0' }); does not behave the same as await page.waitForNetworkIdle

### ISSUE THREAD

**Issue by Josehower** [puppeteer/puppeteer#8509]
### Bug description

Working with puppeteer in Linux environment i have found `await page.waitForNavigation({ waitUntil: 'networkidle0' })`; does not behave the same as `await page.waitForNetworkIdle();`

`await page.waitForNavigation({ waitUntil: 'networkidle0' })` seems to not wait until the images are fully loaded. after using this in a personal project and trying to 

```
cosnt imageWidth= await imageElementHandle.evaluate(
      (imageDomElement) => imageDomElement.naturalWidth,
    )
```

`await page.waitForNavigation({ waitUntil: 'networkidle0' }) ` is not waiting for the image to be fully loaded and it cause `imageWidth` to be `0`

in opposition `await page.waitForNetworkIdle();` properly wait until the image is loaded and define `imageWidth` with the propper width of the image

### Puppeteer version

"puppeteer": "14.3.0"

### Node.js version

v16.15.0

### npm version

8.9.0

### What operating system are you seeing the problem on?

Linux

**Comment by nishanthr93** [comment]
Hi @Josehower 
pass the options in array its should works.
 `await page.[waitForNavigation](''url")({ waitUntil: ['networkidle2'] })`

**Comment by OrKoN** [comment]
Do you have a script to reproduce the issue? I think there is a difference in that waitForNavigation seems to be using the backend/chromium events and waitForNetworkIdle has it own logic for seeing if there are any network events reported.

**Comment by ProchaLu** [comment]
Hi @OrKoN! 
I hope you're doing well. I saw the issue @Josehower posted about the differences between the waitForNetworkIdle and waitForNavigation methods when searching for an image. 

I wrote a small script using Puppeteer to compare the two methods. Here's the test script I used:

```js
import { launch } from 'puppeteer';

(async () => {
  const browser = await launch();
  const page = await browser.newPage();

  await page.goto('https://www.google.com');

  // Wait for the image to load using waitForNetworkIdle()
  const imageElementHandle1 = await page.$('img');
  await page.waitForNetworkIdle();
  const imageWidth1 = await imageElementHandle1.evaluate(
    (img) => img.naturalWidth,
  );
  console.log('Image Width (waitForNetworkIdle):', imageWidth1);

  await page.goto('https://www.google.com');

  // Wait for the image to load using waitForNavigation()
  await page.waitForNavigation({
    waitUntil: 'networkidle0',
    timeout: 3000,
  });

  const imageElementHandle2 = await page.$('img');
  const imageWidth2 = await imageElementHandle2.evaluate(
    (img) => img.naturalWidth,
  );
  console.log('Image Width (waitForNavigation):', imageWidth2);

  await browser.close();
})();
```

After running the script, I found that the first console.log for using waitForNetworkIdle logs:
```
Image Width (waitForNetworkIdle): 272
```

The second method using waitForNavigation throws an error:
```
TimeoutError: Navigation timeout of 3000 ms exceeded
```

I hope this helps provide more information on the issue.

**Comment by OrKoN** [comment]
@ProchaLu these two lines are likely flaky

```
await page.goto('https://www.google.com');

  // Wait for the image to load using waitForNavigation()
  await page.waitForNavigation({
    waitUntil: 'networkidle0',
    timeout: 3000,
  });
```

navigation might happen before page.waitForNavigation is called and there is no second nav so it never resolves.

**Comment by OrKoN** [comment]
`await page.waitForNetworkIdle();` is not flaky because it waits for the state (no requests within 500ms) and not for a navigation event reporting networkidle0

**Comment by OrKoN** [comment]
The following works for me:

```
import { launch } from 'puppeteer';

(async () => {
  const browser = await launch();
  const page = await browser.newPage();

  await page.goto('https://www.google.com');

  // Wait for the image to load using waitForNetworkIdle()
  const imageElementHandle1 = await page.$('img');
  await page.waitForNetworkIdle();
  const imageWidth1 = await imageElementHandle1.evaluate(
    (img) => img.naturalWidth,
  );
  console.log('Image Width (waitForNetworkIdle):', imageWidth1);

  const nav = page.waitForNavigation({
    waitUntil: 'networkidle0',
    timeout: 3000,
  });
  await page.goto('https://www.google.com');
  // Wait for the image to load using waitForNavigation()
  await nav;

  const imageElementHandle2 = await page.$('img');
  const imageWidth2 = await imageElementHandle2.evaluate(
    (img) => img.naturalWidth,
  );
  console.log('Image Width (waitForNavigation):', imageWidth2);

  await browser.close();
})();
```

So to summarise: my opinion is that in this example it works as expected. These are different methods checking slightly different but related things.

**Comment by karlhorky** [comment]
Interesting approach with starting the `page.waitForNavigation` promise early:

```ts
const nav = page.waitForNavigation({ waitUntil: 'networkidle0', timeout: 3000 });
await page.goto('https://www.google.com/');
await nav;
```

Would `Promise.all` be another option? I think I've seen this pattern also in the docs:

```ts
await Promise.all([
  page.waitForNavigation({ waitUntil: 'networkidle0', timeout: 3000 }),
  page.goto('https://www.google.com/'),
])
```

**Comment by OrKoN** [comment]
yes, the Promise.all pattern also works (it's practically the same).

**Comment by anmol5varma** [comment]
```
  {
    const targetPage = page;
    const promises = [];
    const startWaitingForEvents = () => {
      promises.push(targetPage.waitForNavigation());
    }
    await puppeteer.Locator.race([
      targetPage.locator('div.zm-message-box__wrapper button.zm-button--primary > span')
    ])
      .setTimeout(timeout)
      .on('action', () => startWaitingForEvents())
      .click({
        offset: {
          x: 11.453125,
          y: 9,
        },
      });
    await Promise.all(promises)
  }
  ```
  
  This code gives me an error 
  TimeoutError: Navigation timeout of 60000 ms exceeded
    at new Deferred (/Users/anmolvarma/projects/scripting/wfm_req/automation/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
    at Deferred.create (/Users/anmolvarma/projects/scripting/wfm_req/automation/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
    at new LifecycleWatcher (/Users/anmolvarma/projects/scripting/wfm_req/automation/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:66:60)
    at CdpFrame.waitForNavigation (/Users/anmolvarma/projects/scripting/wfm_req/automation/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:184:29)
    at CdpFrame.<anonymous> (/Users/anmolvarma/projects/scripting/wfm_req/automation/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.waitForNavigation (/Users/anmolvarma/projects/scripting/wfm_req/automation/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:616:43)
    at startWaitingForEvents (/Users/anmolvarma/projects/scripting/wfm_req/automation/util/zoom.js:362:32)
    at /Users/anmolvarma/projects/scripting/wfm_req/automation/util/zoom.js:368:27
    at /Users/anmolvarma/projects/scripting/wfm_req/automation/node_modules/puppeteer-core/lib/cjs/third_party/mitt/mitt.js:62:7
    at Array.map (<anonymous>)
    
If I use sleep then it works fine. I have used it in the same way as described in the comments. Ideally it should wait for the page to load and then run the action.
