### ISSUE TITLE
[Bug]: `puppeteer.devices` is undefined on 13.4.0

### ISSUE THREAD

**Issue by PythonCoderAS** [puppeteer/puppeteer#8518]
### Bug description

Steps to reproduce the problem:

1. Install puppeteer 13.4.0
2. Try to use a device

The devices is `undefined` so I cannot access any properties.

### Puppeteer version

13.4.0

### Node.js version

v18.3.0

### npm version

8.11.0

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by huajie2020** [comment]
> ### Bug description
> 
> Steps to reproduce the problem:
> 
> 1. Install puppeteer 13.4.0
> 2. Try to use a device
> 
> The devices is `undefined` so I cannot access any properties.
> 
> 
> ### Puppeteer version
> 
> 13.4.0
> 
> ### Node.js version
> 
> v18.3.0
> 
> ### npm version
> 
> 8.11.0
> 
> ### What operating system are you seeing the problem on?
> 
> Linux, macOS
> 
> ### Relevant log output
> 
> _No response_

**Comment by sugar700** [comment]
It appears that `require('puppeteer').default.devices` (rather than `require('puppeteer').devices`) is necessary now, which is a breaking change that was likely unintended.

I recommend deprecating 13.4.0, as this is a breaking change as far semver is concerned.

**Comment by jrandolf-google** [comment]
Yes, this will be deprecated soon. We are waiting for some changes on our deprecation bot, but once this is ready, we will deprecate < 14. Please use the latest version.

[EDIT] We will not be deprecating it right now. It is still using a stable version of chromium.
