### ISSUE TITLE
Launch non-headless Chrome minimized

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#852]
I cannot find the command line arg to launch non-headless Chrome minimized. Is there any other cross-platform way to do this? Can this be implemented in puppeteer?

**Comment by ebidel** [comment]
It looks like you might be able to configure this on [Windows](https://stackoverflow.com/questions/36667714/start-chrome-minimized). Not sure about other platforms. While not actually minimized, `--window-position` and/or `--window-size` could be used to position the window offscreen :p

flags: https://peter.sh/experiments/chromium-command-line-switches/#window-position

You probably want to file a feature request against Chromium ([new.crbug.com](http://new.crbug.com)). What's the use case exactly?

**Comment by vsemozhetbyt** [comment]
@ebidel I regularly ran a script with links validity check (HTTP-wise and #hash-wise) in a document set (~50 source documents, ~11500 links to ~600 documents, duration ~10–15 min). I need non-headless Chrome [to check links to PDF](https://github.com/GoogleChrome/puppeteer/issues/830). But it would be handy to have the window minimized from the beginning, not to obstruct the console and not to hinder in other work.

**Comment by vsemozhetbyt** [comment]
BTW, would `--window-position` and/or `--window-size` affect the viewport? I need a big one [to collect a valid `.innerText` from all links rendered](https://github.com/GoogleChrome/puppeteer/issues/825).

**Comment by ebidel** [comment]
`--window-position` won't. That's the physical position of the window on the screen.

**Comment by vsemozhetbyt** [comment]
Upstream feature request: https://bugs.chromium.org/p/chromium/issues/detail?id=767873

**Comment by vsemozhetbyt** [comment]
The request was rejected, but a link to extension API was provided. I do not know if this API can help in supporting the feature via DevTools protocol inside the puppeteer.

**Comment by zmarffy** [comment]
Ugh, this is frustrating. I'd love to have this feature.

**Comment by aslushnikov** [comment]
Closing this in favor of #852: there should be a reasonable way to work with navigations that return PDF's.

**Comment by vsemozhetbyt** [comment]
(https://github.com/GoogleChrome/puppeteer/issues/830 was probably meant)
