### ISSUE TITLE
[Bug]:`devices` is undefined on 14.4.0

### ISSUE THREAD

**Issue by alopix** [puppeteer/puppeteer#8521]
### Bug description

Steps to reproduce the problem:

Install puppeteer 14.4.0 (an earlier bug from someone today mentioned 13.4 in issue #8521 which I assume was a typo in their end)
Try to use a device

The devices is undefined so I cannot access any properties.

`import { devices } from 'puppeteer';` is undefined

### Puppeteer version

14.4.0

### Node.js version

14.19.1

### npm version

8.10.0

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf-google** [comment]
Can you please write the version this was last working? Was this a publicly-available API?

**Comment by OrKoN** [comment]
I think it’s a public API https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerdevices

**Comment by alopix** [comment]
It was working in v14.3.0

**Comment by payephyoeaung87** [comment]
npmjs.com is it OK to open an account and use it

၂၀၂၂၊ ဇွန် ၁၄၊ အင်္ဂါ ညနေ ၁၁:၅၉ တွင် Dustin ***@***.***> က
ရေးခဲ့သည်−

**Comment by jrandolf-google** [comment]
Fixed in https://github.com/puppeteer/puppeteer/commit/cba58a12c4e2043f6a5acf7d4754e4a7b7f6e198.
