### ISSUE TITLE
Domains like start with www. is clickable even though i didn't setup the hyperlink 

### ISSUE THREAD

**Issue by dean-g** [puppeteer/puppeteer#8526]
Domains like start with www. are clickable even though I didn't set up the hyperlink 

My pdf contents have a few entries as follows, 
- www.google.com
- www.abc.com
- www.hacker.com

and so on 

If I open the pdf in the chrome browser, those domains were clickable. Is there a way I can limit those click events? 

Please advise if there is any configuration from the puppeteer to help me prevent this clickable

**Comment by vezaynk** [comment]
You're going to have to go dig in the Chromium API / configuration options for that. There might not be such an option.

You could potentially do something with JavaScript though.

**Comment by dean-g** [comment]
Yeah. thanks for your advice @knyzorg!. 

I moved that into an anchor tag and href to href="javascript:void(0)" which help me to prevent from clicking. but now the problem is the anchor tag got the cursor pointer. Is there a way to change the anchor cursor from pointer to text for pdf? 

I tried using CSS styles but it doesn't work with the pdf editor. 

Please advise.

**Comment by vezaynk** [comment]
You could try to replace the a tags with span tags. They will make them not clickable at all.

**Comment by dean-g** [comment]
if I move that to a span tag. the pdf editor on chrome it allowing them to click by default.

**Comment by vezaynk** [comment]
What does your JS look like?

**Comment by OrKoN** [comment]
Hey, thanks for the report. It does not look like it's directly a Puppeteer issue (perhaps a Chromium headless/Chromium issue). Could you please include the reproduction scripts for the issue and the version information this is happening with?

**Comment by dean-g** [comment]
Thanks, @knyzorg, and @OrKoN for looking at this issue!. 

My codebase initially looks like this: 
`<td>  www.google.com </td> `

to avoid clicking, i changed that to 
```
<td>
 <a href="href="javascript:void(0)">www.google.com </a>
</td>
```
now I am getting the hand cursor even though I restricted that from a CSS class as a text. 

I am using the following version, 
"puppeteer": "^9.0.0",

**Comment by OrKoN** [comment]
@dean-g could you try it with the latest Puppeteer?

**Comment by dean-g** [comment]
I upgraded the same but no luck

**Comment by OrKoN** [comment]
Could you please provide the entire script to reproduce?
