### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vindhya124** [puppeteer/puppeteer#8528]
### Bug description

Steps to reproduce the problem:

1. I am using puppeteer to render a pdf  file from html and send as an attachment to email. The text in the pdf is grey and too small. I have used  html {
        -webkit-print-color-adjust: exact !important;
    } as an inline style but didn't worked

![image](https://user-images.githubusercontent.com/38023844/173974255-6a0f31a9-da89-4247-8f17-07a2a1526c6a.png)

### Puppeteer version

7.0.0

### Node.js version

16.15.0

### npm version

4.0.1

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Please try using the latest version of Puppeteer (and the latest Chromium) as version 7.0.0 is deprecated. I am not sure if it will work in the newer version but there is a chance. Please also include a complete reproduction (e.g., HTML/CSS + Puppeteer script).

**Comment by vindhya124** [comment]
> Please try using the latest version of Puppeteer (and the latest Chromium) as version 7.0.0 is deprecated. I am not sure if it will work in the newer version but there is a chance. Please also include a complete reproduction (e.g., HTML/CSS + Puppeteer script).

Thank you for your quick response. I have updated to the latest version and it worked.
