### ISSUE TITLE
[Bug]: Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by bambooom** [puppeteer/puppeteer#8530]
### Bug description

Steps to reproduce the problem:

1. install puppeteer latest
2. run this script `node test.js`

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('https://www.google.com');

})();
```

I'm using Mac mini (M1, 2020) with macOS Monterey (12.4)

### Puppeteer version

14.4.0

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at BrowserRunner.start (/Users/bn/OpenResty/dev/navlang/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:112:34)
    at ChromeLauncher.launch (/Users/bn/OpenResty/dev/navlang/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:108:16)
    at async /Users/bn/OpenResty/dev/navlang/test.js:5:19 {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

**Comment by OrKoN** [comment]
I think you should try installing puppeteer with the environmental variable `PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM` set to true. M1 support is currently experimental as GitHub Actions still lack support for Mac ARM cpus.

**Comment by bambooom** [comment]
I've tried to install with `PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM` as:

```
PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM=true npm i puppeteer
```
![Screen Shot 2022-06-21 at 10 25 48](https://user-images.githubusercontent.com/14840170/174703240-7df912b3-6749-4d0c-9194-e24220579614.png)

But I run the above `test.js` with another error:

```
➔ node test.js
/Users/bn/OpenResty/dev/navlang/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:111
                throw new Error(missingText);
                      ^

Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1002410).
    at ChromeLauncher.launch (/Users/bn/OpenResty/dev/navlang/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:111:23)
    at async /Users/bn/OpenResty/dev/navlang/test.js:5:19
```

**Comment by OrKoN** [comment]
What happens if you run `PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM=true node test.js`?

**Comment by bambooom** [comment]
@OrKoN  It stucked without any error reporting or any other information.

**Comment by OrKoN** [comment]
hm, could you run `DEBUG=puppeteer.* PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM=true node test.js` and post the log?

**Comment by bambooom** [comment]
@OrKoN  The log is here: https://gist.github.com/bambooom/4d6880dc3df7f918cd9c6fc56d8bfe64

**Comment by Madurba** [comment]
copy/paste this into the terminal of your project's directory :

```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium
```

**Comment by OrKoN** [comment]
@bambooom I don't see any errors in the log: it looks like the browser is sending and receiving CDP messages without problems in that run? There is one error but it's not the one from your original report.

**Comment by kena0ki** [comment]
I had the same error. In my case I resolved the issue with [this workaround](https://linguinecode.com/post/how-to-fix-m1-mac-puppeteer-chromium-arm64-bug), although installation itself hadn't failed though.

In step2 of the above link, I couldn't open chromium, so I needed to remove “quarantine” attribute from downloaded files.
https://www.reddit.com/r/MacOS/comments/q9d772/homebrew_chromium_is_damaged_and_cant_be_openend/

**Comment by OrKoN** [comment]
@bambooom is it still an issue? the log looks good, perhaps you are missing a `browser.close()` call in your script and it looks hanging? closing the issue for now. Feel free to comment if any of the workaround posted worked for you.

**Comment by fantomblackstar** [comment]
I encountered the same issue with `puppeteer-core` on my MacBook M1. Here's the solution that worked for me:

1. **Install Chromium via Homebrew:**
   ```bash
   brew install chromium --no-quarantine
   ```

2. **Update the `executablePath` in your launch configuration:**
   ```js
   import chromium from "@sparticuz/chromium";
   import puppeteerCore, { Browser, PDFOptions } from "puppeteer-core";

   const browser: Browser = await puppeteerCore.launch({
       args: chromium.args,
       defaultViewport: chromium.defaultViewport,
       executablePath:
           process.env.NODE_ENV === "local"
               ? "/opt/homebrew/bin/chromium"
               : await chromium.executablePath(),
       headless: chromium.headless,
   });
   ```
