### ISSUE TITLE
[Bug] error Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1002410).

### ISSUE THREAD

**Issue by wuttichowcho** [puppeteer/puppeteer#8532]
Hello

I user Lambda by image package type. I use "npm install puppeteer" in image. When I call function using puppeteer for generate pdf , it throw error `"error Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1002410)."` on Lambda.

this is my code 

```
const puppeteer = require("puppeteer");
async convertHTMLtoBase64PDFViaPopperteer(html) {
    try {
        const browser = await puppeteer.launch();
        const page = await browser.newPage();
      
        await page.setContent(html);
      
        const pdfBuffer = await page.pdf({
            format: "A4",
            printBackground: true,
            margin: { top: "1cm", right: "1cm", bottom: "1cm", left: "1cm" },
          });
      
        await page.close();
        await browser.close();
      
        return pdfBuffer.toString("base64");
    } catch (error) {
      throw error;
    }
  }
}
```

Have you got any idea for solve ? Or do I done something wrong ?
thank you and best regard.

**Comment by jrandolf-google** [comment]
Please check our FAQ.

**Comment by wuttichowcho** [comment]
@jrandolf Can you guild me how to find FAQ ?

**Comment by menottiRicardo** [comment]
I couldn't find anything on the FAQ

**Comment by InsOpDe** [comment]
@jrandolf if you're referring to https://pptr.dev/faq/ then there is nothing to find to that matter.

**Comment by jrandolf-google** [comment]
Please see [the troubleshooting docs](https://pptr.dev/troubleshooting).
