### ISSUE TITLE
[Bug]: page client.on doesn't works

### ISSUE THREAD

**Issue by hajunwon** [puppeteer/puppeteer#8533]
### Bug description

client.on("Network.webSocketFrameSent", ({ requestId, timestamp, response }) => {
           ^

TypeError: client.on is not a function

why?

```
var puppeteer = require("puppeteer");

(async () => {
    var browser = await puppeteer.launch({
        args: [
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-infobars",
            "--window-position=0,0",
            "--window-size=1366,768"
        ],
        defaultViewport: null,
        ignoreHTTPSErrors: true,
        headless: false
    });
    var MainPage = await browser.newPage();
    var client = MainPage._client;
    client.on("Network.webSocketFrameSent", ({ requestId, timestamp, response }) => {
        console.log("[1]");
    });
})();
```

### Puppeteer version

14.4.0

### Node.js version

16.13.0

### npm version

8.1.2

### What operating system are you seeing the problem on?

Windows

**Comment by jumoog** [comment]
`MainPage._client` isn't accessible anymore since https://github.com/puppeteer/puppeteer/commit/6c960115a3230e247de628b85dea7c1c02582d6d

**Comment by jrandolf-google** [comment]
You can use _client(), but please remember all internal APIs are subject to breakage without notification.

**Comment by 1kaiser** [comment]
FROM 👍:
`await page._client.send("Page.setDownloadBehavior", {
            behavior: "allow",
            downloadPath: folderName,
          });`

LATEST:

`await page._client().send("Page.setDownloadBehavior", {
            behavior: "allow",
            downloadPath: folderName,
          });`
