### ISSUE TITLE
[Bug]: Puppeteer's boundingBox method returns null after it enounters a react portal

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#8539]
### Bug description

Steps to reproduce the problem:

1. Parse through the page's elements
2. Call the boundingBox method on each of those elements.
3. Encounter a react portal which doesn't render anything on the browser meaning the boundingBox will return null
4. All the boundingBox calls following this null result give null result even if they are rendering something on the screen.

### Puppeteer version

13.4.0

### Node.js version

16.14.0

### npm version

8.12.1

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Could you please provide a test page and a test script to reproduce this?
