### ISSUE TITLE
profiling javascript on webpage 

### ISSUE THREAD

**Issue by datasunny** [puppeteer/puppeteer#854]
Hi all,
Is there a way to profile target page's javascript in puppeteer? say which functions are called and time spend for each function call?

Thanks.

**Comment by ebidel** [comment]
The devtools protocol has these capabilities, but they're not exposed in puppeteer yet.
https://chromedevtools.github.io/devtools-protocol/tot/Profiler/.

Once https://github.com/GoogleChrome/puppeteer/issues/31 lands, you could access the protocol APIs directly. Puppeteer could also have a higher level API someday.

**Comment by paulirish** [comment]
The page.tracing.start/stop methods can capture a trace. https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-tracing

with `disabled-by-default-v8.cpu_profiler` turned on you can get JS sampling profiler data in the trace. this category is [already enabled](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Tracing.js) in puppeteer's settings..

(optionally also capturing `disabled-by-default-v8.cpu_profiler.hires`  will get higher resolution)

**Comment by datasunny** [comment]
@paulirish Could you explain how to turn on 'disabled-by-default-v8.cpu_profiler' and 'disabled-by-default-v8.cpu_profiler.hires' in puppeteer? Thanks.

**Comment by paulirish** [comment]
> Could you explain how to turn on 'disabled-by-default-v8.cpu_profiler' and 'disabled-by-default-v8.cpu_profiler.hires' in puppeteer?

Currently you cannot. https://github.com/GoogleChrome/puppeteer/blob/5e154dc835fcacdec6e680a695630352dae959dc/lib/Tracing.js#L36-L55

perhaps there should be a new option added like: `page.tracing.start({sampling:true})`.

**Comment by paulins** [comment]
(file); await this._client.send

2017-11-06 21:15 GMT+01:00 Paul Irish <notifications@github.com>:

**Comment by aslushnikov** [comment]
@datasunny @paulirish filed https://github.com/GoogleChrome/puppeteer/issues/1300 for this, looks like a good-first-bug
