### ISSUE TITLE
Requests are not visible in "on" event

### ISSUE THREAD

**Issue by JaLe29** [puppeteer/puppeteer#855]
* Puppeteer version: "puppeteer": "^0.10.2"
* Platform / OS version: win 10, 64b

expected: request to home https://www.example.net/ and https://www.example.com/'

actual:
REQUEST TO : https://www.example.net/
GET 200 https://www.example.net/
REQUEST TO : https://www.example.net/favicon.ico
(node:4640) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Network.continueInterceptedRequest): Invalid InterceptionId. undefined
(node:4640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
REQUEST TO : https://www.example.com/favicon.ico
GET 404 https://www.example.com/favicon.ico

In log, there is not request to REQUEST TO : https://www.example.com/ only on https://www.example.com/favicon.ico

See code:

```
const puppeteer = require('puppeteer')
const path = require('path')

const URL = 'https://www.extrategy.net/en/values'

const run = async (browser) => {
	const page = await browser.newPage()
	page.setRequestInterceptionEnabled(true) 
	
	page.on('request', request => {
		console.log("REQUEST TO : " + request.url);
		request.continue(); // pass it through.
	});

	page.on('response', response => {
		const req = response.request(); 
		console.log(req.method, response.status, req.url);
	});
		
	await page.goto('https://www.example.net/') 
	await page.goto('https://www.example.com/') 

}

(async () => {
  const browser = await puppeteer.launch({headless: false})
  await run(browser)
  //return browser.close()
})()
```

**Comment by vsemozhetbyt** [comment]
Strangely, the second response is `null`, despite document opening in the browser (puppeteer v0.11.0-alpha or v0.12.0-alpha):
```js
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  await page.setRequestInterceptionEnabled(true);

  page.on('request', (request) => {
    console.log(`REQUEST TO: ${request.url}`);
    request.continue();
  });

  page.on('response', (response) => {
    const req = response.request();
    console.log(req.method, response.status, req.url);
  });

  const resp1 = await page.goto('https://www.example.net/');
  console.log(resp1 && resp1.status);
  const resp2 = await page.goto('https://www.example.com/');
  console.log(resp2 && resp2.status);

  // await browser.close()
})();
```
```console
REQUEST TO: https://www.example.net/
GET 200 https://www.example.net/
200
REQUEST TO: https://www.example.net/favicon.ico
null
REQUEST TO: https://www.example.com/favicon.ico
GET 404 https://www.example.com/favicon.ico
```

**Comment by sukrosono** [comment]
I am not sure but sometime when requesting to https://google.com i got error.

![puppeter req to a logo err highlight](https://user-images.githubusercontent.com/3001652/31216726-d1be25ba-a9de-11e7-85a3-4d2f6f572884.png)

[full console](https://user-images.githubusercontent.com/3001652/31216624-7ae64574-a9de-11e7-828c-7449b90b11e3.png)

**Comment by aslushnikov** [comment]
THis seems to be fixed on tip-of-tree. Please try installing puppeteer@next to verify

```
npm install --save puppeteer@next
```
