### ISSUE TITLE
[Bug]: "UNKNOWN CONSOLE TYPE: warn" log spam

### ISSUE THREAD

**Issue by Torgen** [puppeteer/puppeteer#8563]
### Bug description

My Meteor.js app uses puppeteer as the headless browser driver for its client-side tests. The Meteor client side test driver proxies log messages to the server so they end up in STDERR. Consecutive commits on my project bump Puppeteer to [14.3.0](https://github.com/Torgen/codex-blackboard/commit/c2eaa2fd730427904c30bcff3160899ac032a47a) and [14.4.0](https://github.com/Torgen/codex-blackboard/commit/2fc3b8f05818c268bc4b02c5ab30999ed8c5d420). The [logs for the 14.4.0 test run](https://github.com/Torgen/codex-blackboard/runs/7036020146?check_suite_focus=true) are full of "UNKNOWN CONSOLE TYPE: warn" messages; no such messages appear in the [logs for the 14.3.0 test run](https://github.com/Torgen/codex-blackboard/runs/6805692502?check_suite_focus=true). I've run the tests on my home machine under WSL and see the same thing, so it's not just Github Actions. (Expand the "Test coverage.full.lcov" task in the Github Actions run to see the test logs.)

### Puppeteer version

14.4.0

### Node.js version

14.19..3

### npm version

6.14.17

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Hm, I don't think we added any console.warn messages or any logging at all. Here is the diff for the versions you mention https://github.com/puppeteer/puppeteer/compare/v14.3.0...v14.4.0 I don't see anything special there. Could you please see what module/code prints this message?

**Comment by Torgen** [comment]
There were a convenient number of changes for me to binary search them. The behavior change happened at 6c960115a3230e247de628b85dea7c1c02582d6d.

**Comment by Torgen** [comment]
https://github.com/Meteor-Community-Packages/meteor-browser-tests/blob/4b1a18a48c77535d3dbdca787e8a807be8c24b85/browser/puppeteer.js#L48 Meteor browser tests depended on the private field name.

**Comment by OrKoN** [comment]
Thanks! But I still don't see anything specific: probably it has to do with the private properties? Can you see the exact place where the log messages are produced (e.g., which API etc)? We don't see these log messages when running our own tests.

**Comment by OrKoN** [comment]
Ah, I see, thanks for figuring it. Let's see if there is an alternative API for meteor-browser-tests to use or if we need to expose and properly document this.

**Comment by OrKoN** [comment]
It looks like `meteor-browser-tests` should just use `msg.type()`

**Comment by Torgen** [comment]
There is a type() method they probably should have used; it seems like it's existed for a while.

**Comment by OrKoN** [comment]
I assume that we can close this issue? Let me know if there is anything to help with here.
