### ISSUE TITLE
[Bug]: The puppeteer@15.0.0 not support WebGL?

### ISSUE THREAD

**Issue by zhazhaxia** [puppeteer/puppeteer#8566]
### Bug description

Steps to reproduce the problem:

1 I upgrade puppeteer@15.0.0,and then run my program on GPU machine, the log shows  that "This device is not support webGL"

2 And then I use the older version puppeteer@13.1.3, it works and use GPU resource.

So whats wrong with puppeteer@15.0.0? Why this version not support webGL?

My args config is "'--use-gl=egl'"

### Puppeteer version

15.0.0

### Node.js version

14.15.3

### npm version

6.14.9

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
0====puppeteer kongzhan==== [system] UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/103.0.5058.0 Safari/537.36
4====puppeteer kongzhan==== [system] UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/103.0.5058.0 Safari/537.36
3====puppeteer kongzhan==== [system] UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/103.0.5058.0 Safari/537.36
1====puppeteer kongzhan==== [system] UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/103.0.5058.0 Safari/537.36
2====puppeteer kongzhan==== This device does not support webgl
0====puppeteer kongzhan==== This device does not support webgl
3====puppeteer kongzhan==== This device does not support webgl
2====puppeteer kongzhan==== JSHandle@error
4====puppeteer kongzhan==== This device does not support webgl
1====puppeteer kongzhan==== This device does not support webgl




mark:
0====puppeteer kongzhan==== is my custom log
```

**Comment by OrKoN** [comment]
This is more likely caused by the newer Chromium binary as Puppeteer does not do anything special for GPU/WebGL (perhaps only setting some command line arguments but I think there were no changes there).

**Comment by OrKoN** [comment]
Do you have a reproduction script?

**Comment by zhazhaxia** [comment]
> Do you have a reproduction script?

Okk,the following code is

```js

const puppeteer = require("puppeteer");
(async () => {
  const browser = await puppeteer.launch({
    userDataDir: './cache',
    args: [
      '--no-sandbox',
      '--use-gl=egl',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox'
    ]
  });
  const tabsNumber = 1;
  for (let i = 0; i < tabsNumber; i++) {
    goToPage(browser)
  }
})();

async function goToPage(browser) {
  const page = await browser.newPage();
  page.setViewport({
    width: 667,
    height: 375,
  });
  page.on("console", async (msg) => {
    console.log("==puppeteer log==", msg.text())
  });
  page.on("pageerror", async (err) => {
    console.log("==error==", err)
  });
  await page.goto("http://pixi-game.herokuapp.com/", {
    timeout: 120000
  });
}
```

**Comment by OrKoN** [comment]
What is the expected/actual output for you? I get

```
==puppeteer log==
 %c %c %c Pixi.js 3.0.10 - ✰ WebGL ✰  %c  %c  http://www.pixijs.com/  %c %c ♥%c♥%c♥

 background: #ff66a5; padding:5px 0; background: #ff66a5; padding:5px 0; color: #ff66a5; background: #030307; padding:5px 0; background: #ff66a5; padding:5px 0; background: #ffc3dc; padding:5px 0; background: #ff66a5; padding:5px 0; color: #ff2424; background: #fff; padding:5px 0; color: #ff2424; background: #fff; padding:5px 0; color: #ff2424; background: #fff; padding:5px 0;
==puppeteer log== DOM is ready
```

And I don't get an error.

**Comment by zhazhaxia** [comment]
> What is the expected/actual output for you? I get
> 
> ```
> ==puppeteer log==
>  %c %c %c Pixi.js 3.0.10 - ✰ WebGL ✰  %c  %c  http://www.pixijs.com/  %c %c ♥%c♥%c♥
> 
>  background: #ff66a5; padding:5px 0; background: #ff66a5; padding:5px 0; color: #ff66a5; background: #030307; padding:5px 0; background: #ff66a5; padding:5px 0; background: #ffc3dc; padding:5px 0; background: #ff66a5; padding:5px 0; color: #ff2424; background: #fff; padding:5px 0; color: #ff2424; background: #fff; padding:5px 0; color: #ff2424; background: #fff; padding:5px 0;
> ==puppeteer log== DOM is ready
> ```
> 
> And I don't get an error.


There is my Log.

```
This device does not support webgl
====puppeteer kongzhan==== JSHandle@error
```
Maybe this problem only happen on my machine?

**Comment by OrKoN** [comment]
yeah, it's possible. I am running on a macbook here.

**Comment by zhazhaxia** [comment]
> yeah, it's possible. I am running on a macbook here. 

I running on centos7 with Nvida Gpu. I try to use another machine later.
Thx.
