### ISSUE TITLE
File Uploads

### ISSUE THREAD

**Issue by pemrouz** [puppeteer/puppeteer#857]
Hi, I'm trying to test form submissions with file uploads. Is there an easy way to select file(s) on `input[type="file"]`?

**Comment by ebidel** [comment]
`input.files` gets you the list of files selected on an input. https://developer.mozilla.org/en-US/docs/Web/API/FileList.

Not sure this will serialize correctly, so you may need to read the files as arraybuffers or strings and return that from $eval:

`const files = page.$eval('input[type="file"]', input => console.log(input.files));`

**Comment by pemrouz** [comment]
Sorry, wasn't very clear: I know I can select `input.files` and get the `FileList`, but it's an empty `FileList`! Is there a way to populate it with some files? Currently I'm faking it by creating something like quacks like a `FileList` (an array of `File`s that also passes `instanceof FileList`).

PS. Just wanted to say this project is absolutely amazing 👌. Thanks for all you work :)

**Comment by ebidel** [comment]
I see. Hmm, yea. You can't set files programmatically on an `input type=file` due to security restrictions. What you're doing is probably the best approach. If this is part of an existing form submission, you could use `FormData`, attach `Blob`s, and submit the form to the same endpoint.

**Comment by aslushnikov** [comment]
@pemrouz There's a [`elementHandle.uploadFile`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandleuploadfilefilepaths) method to populate input of type "file".

**Comment by ceyhun** [comment]
Also `elementHandle.uploadFile`'s `filePaths` are resolved relative to _current working directory_ (`cwd`)

So if you have:
```
ui-tests/
├── assets/
│   └── file-to-upload.txt
├── xyz.test.js
```

From `xyz.test.js` you should do:

```js
const filePath = path.relative(process.cwd(), __dirname + '/assets/file-to-upload.txt');
const input = await page.$('input[name=something]');
await input.uploadFile(filePath);

**Comment by ThibaultJanBeyer** [comment]
I don’t manage to get this working…
There is no error message but it’s not uploading either.
I tried both, with an absolute path and also with a relative path as in your example.
:(

**Comment by wurde** [comment]
Maybe related to #1957?

**Comment by rotimi-best** [comment]
@ThibaultJanBeyer  I had just the same situation as you had, but I later realized the problem. It was because I was not targeting the input tag correctly, so it couldn't locate the input tag.

**I had something like this initially:**
```javascript
const fileInput = await page.$('input[type=file]');
```

**Then I changed it to:**
```javascript
const fileInput = await page.$('.messsage-container .messsage-form__upload-attachment input[type=file]');
```

And it then worked :+1:

**Comment by loxator** [comment]
> Also `elementHandle.uploadFile`'s `filePaths` are resolved relative to _current working directory_ (`cwd`)
> 
> So if you have:
> 
> ```
> ui-tests/
> ├── assets/
> │   └── file-to-upload.txt
> ├── xyz.test.js
> ```
> From `xyz.test.js` you should do:
> 
> ```js
> const filePath = path.relative(process.cwd(), __dirname + '/assets/file-to-upload.txt');
> const input = await page.$('input[name=something]');
> await input.uploadFile(filePath);
> ```

Thank you so much for this! Just in case someone else stumbles, I had to concatenate the paths using ```path.join()``` instead of the ```+``` operator.

**Comment by jamsmd** [comment]
Is there also a way to close the file picker dialog afterwards?

**Comment by OmarKhattab** [comment]
@ceyhun How can I solve the issue of if i have a folder photos and I have 200 photos in it but I only want to upload 3 is there a way to specify three paths in the input.uploadFile() params?

**Comment by Versiani-R** [comment]
Did no one fix it ? I'm trying to upload an image to facebook

html: input accept="image/*"  type="file" class="_n _5f0v" id="js_4w"

and i can't figure it out a way to upload an image to this, i'm so sad

**Comment by azakero** [comment]
> Did no one fix it ? I'm trying to upload an image to facebook
> 
> html: input accept="image/*" type="file" class="_n _5f0v" id="js_4w"
> 
> and i can't figure it out a way to upload an image to this, i'm so sad

Hey man. Did you figure it out?
