### ISSUE TITLE
[Bug]: Printing is not available

### ISSUE THREAD

**Issue by wangrongding** [puppeteer/puppeteer#8574]
### Bug description

Steps to reproduce the problem:

1. connect my browser
```js
const browser = await puppeteer.connect({
    browserWSEndpoint: webSocketDebuggerUrl,
});
```

2. go to a page
```js
const [page] = await browser.pages();
  await page.setDefaultNavigationTimeout(0);
  await page.goto("https://github.com/", {
    waitUntil: "networkidle0",
});
await sleep(1000);
```
3. generate PDF
```js
await page.pdf({
  path: "xxxx.pdf",
});
```

4. ERROR  'Printing is not available'  

## If I use the headless way it works. How to work without headless mode?

```sh
ReferenceError: printPdf is not defined
    at main (E:\Noah-Programs\puppeteer-demo\test.js:31:3)
PS E:\Noah-Programs\puppeteer-demo> node .\test.js
E:\Noah-Programs\puppeteer-demo\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:268    
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Page.printToPDF): Printing is not available
    at E:\Noah-Programs\puppeteer-demo\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:268:24
    at new Promise (<anonymous>)
    at CDPSession.send (E:\Noah-Programs\puppeteer-demo\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:264:16)
    at Page.createPDFStream (E:\Noah-Programs\puppeteer-demo\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:1834:85)
    at Page.pdf (E:\Noah-Programs\puppeteer-demo\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:1864:37)
    at main (E:\Noah-Programs\puppeteer-demo\test.js:31:14) {
  originalMessage: 'Printing is not available'
}
```

### Puppeteer version

15.0.0

### Node.js version

v16.13.2

### npm version

8.4.1

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
What browser/browser version do you connect to? Old chrome versions might not have pdf printing in headful.

**Comment by wangrongding** [comment]
> What browser/browser version do you connect to? Old chrome versions might not have pdf printing in headful.

### Thank's for your reply, I use chrome v103.0.5060.53

Here is all my code👇:

```js
const chromeLauncher = require("chrome-launcher");
const axios = require("axios");
const puppeteer = require("puppeteer-core");

(async () => {
  // Initializing a Chrome instance manually
  const chrome = await chromeLauncher.launch({
    chromePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
  });

  // connect to a Chrome instance running on localhost:xxxx
  const response = await axios.get(
    `http://localhost:${chrome.port}/json/version`
  );
  const { webSocketDebuggerUrl } = response.data;
  const browser = await puppeteer.connect({
    browserWSEndpoint: webSocketDebuggerUrl,
  });
  const [page] = await browser.pages();
  await page.setDefaultNavigationTimeout(0);
  await page.goto("https://github.com/", {
    waitUntil: "networkidle0",
  });

  // Here 👇 ❌
  await page.pdf({
    path: "xxxx.pdf",
  });
})();

```

**Comment by wangrongding** [comment]
🚞🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃🚃...

**Comment by frank-dspeed** [comment]
at last the puppeteer code says clear that it is only supported in headless mode in headfull mode we use the browser api's and that do not contain at present ways for the devtools to print to the pdf printer or real printers. 

but thats what i am seeing as needed. 

will Maybe start the process of a proposal to integrate the printer api with devtools so we can print something via it in headfull to real printers or the pdf printer.

Some one got a similar issue in electron there the printer api also does not work well when that would get shifted to devtools it would enable a lot of app scenarios via a uniqe api 

https://gist.github.com/saugatdai/5ba400d42e3fa4be66d323b2d826fe50

**Comment by OrKoN** [comment]
ah sorry, @frank-dspeed is right. I was under impression that it was implemented but it looks like the issue is still open: https://bugs.chromium.org/p/chromium/issues/detail?id=753118 That makes this issue to be an upstream issue and a duplicate of #6220. You'd need to use headless mode for PDF printing for now.
