### ISSUE TITLE
[Bug]: ElementHandle is no longer exported

### ISSUE THREAD

**Issue by ldiqual** [puppeteer/puppeteer#8576]
### Bug description

Take the following function that compiles with puppeteer v14:

```typescript
import { Page, ElementHandle } from 'puppeteer'
export async function getFoo(page: Page): Promise<ElementHandle | null> {
  return page.$('#foo')
}
```

Upgrade to puppeteer v15. The code no longer compiles:

```
Module '"puppeteer"' declares 'ElementHandle' locally, but it is not exported.ts(2459)
types.d.ts(1489, 15): 'ElementHandle' is declared here.
```

I believe this is a side effect of https://github.com/puppeteer/puppeteer/pull/8547, but I'm not sure if it was intended. Are we supposed to use another return type? Or was this type supposed to stay public?

### Puppeteer version

15.1.0

### Node.js version

v16.15.1

### npm version

Yarn 3.2.1

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf-google** [comment]
Fixed in e0198a79e06c8bb72dde554db0246a3db5fec4c2
