### ISSUE TITLE
Re-enable TS typing tests

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#8581]
Let's re-enable the TS tests and make sure they capture major expectations on how to work with Puppeteer's types: e.g., what is inferred, what is not and in what situations. 

Disabled in https://github.com/puppeteer/puppeteer/pull/8550

**Comment by jrandolf-google** [comment]
After investigating this a bit, there is a framework [recommended even by Microsoft (see README)](https://github.com/microsoft/dtslint) that we can use for type testing that *actually* makes sense. See https://github.com/SamVerschueren/tsd.

**Comment by OrKoN** [comment]
This looks great! Should we introduce this before you proceed with the next typing refactoring?
