### ISSUE TITLE
[Bug]: Failed to launch the browser process!

### ISSUE THREAD

**Issue by julianv22** [puppeteer/puppeteer#8597]
### Bug description

Error: Failed to launch the browser process!
/home/runner/Replit-Bot/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/runner/Replit-Bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.<anonymous> (/home/runner/Replit-Bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)

### Puppeteer version

"images-scraper": "^6.4.0"

### Node.js version

"node": "^16.14.2"

### npm version

"npm-run-path": "^4.0.1"

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
I dont know what is that error
```

**Comment by OrKoN** [comment]
Hey, it looks like you don't have dependencies installed on your system. Please follow the troubleshooting guide and make sure all chromium dependencies are installed.

P.S. you say it's on Windows but I think you are using linux.

**Comment by julianv22** [comment]
Idk what is it's OS. 'cause I'm using replit.com to do that. So, what can I do to fix this err?

**Comment by OrKoN** [comment]
You should open an issue with replit. The missing lib is libgobject-2.0, it needs to be installed on the OS.

**Comment by sun-m00n** [comment]
Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\Users\Abhishek\Desktop\nodejs-projects\src\fake usr in yt v2\v4\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:290:20)     
    at ChildProcess.<anonymous> (C:\Users\Abhishek\Desktop\nodejs-projects\src\fake usr in yt v2\v4\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:281:24)
    at ChildProcess.emit (node:events:525:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)

**Comment by sun-m00n** [comment]
why childprocess is anonymous?
    at ChildProcess.<anonymous>

**Comment by EnriqueGS88** [comment]
> Idk what is it's OS. 'cause I'm using replit.com to do that. So, what can I do to fix this err?

Did you manage to make it work on replit.com ?

**Comment by Kikope** [comment]
Hey Julian, How are you, u fixed that problem somehow? I have the exact same problem. Can you help me? please :(

**Comment by lcylwik** [comment]
Hello @julianv22 or @Kikope,  u fixed that problem ? I have the same issue.

Failed to launch the browser process!
/home/node/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

with node 14.16.0 and puppeteer 19.8.5

Can you help me? please

**Comment by Kikope** [comment]
Hello Lianet!!

I couldn't fix that problem, but in my case was a problem with the server.
I was using the replit.io to run my code, and replit do not accept the
puppeteer lib for privacy and security reasons.

**Comment by isal-prismhr** [comment]
Getting this error, could you please help me to fix it?
"Failed to launch the browser process!\n/root/.cache/puppeteer/chrome/linux-116.0.5845.96/chrome-linux64/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n"

**Comment by MohammadAmaan14** [comment]
I also am stuck on the same problem

**Comment by isal-prismhr** [comment]
@MohammadAmaan14 First you have to find the chrome path then update the executablePath.It would work.
     const browser = await puppeteer.launch({
        headless: "new",
        executablePath: "/usr/bin/google-chrome",
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
      });

**Comment by Saranpjs727** [comment]
I have same problem

/root/.cache/puppeteer/chrome/linux-129.0.6668.100/chrome-linux64/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

My docker file:

FROM node:18-slim
RUN npx puppeteer browsers install chrome
ENV PUPPETEER_CACHE_DIR='/root/.cache/puppeteer/chrome/linux-129.0.6668.100/chrome-linux64/chrome'
COPY dist/build  /app/build -- copying build artifact
WORKDIR /app/build
EXPOSE 8080
USER 1000
CMD ["node","index.js"]

----

const browser = await puppeteer.launch(
    {
      headless: true,
      executablePath: /root/.cache/puppeteer/chrome/linux-129.0.6668.100/chrome-linux64/chrome,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
