### ISSUE TITLE
waitForNavigation timeout exceeded

### ISSUE THREAD

**Issue by petarthewizard** [puppeteer/puppeteer#860]
I am making a wrapper around Puppeteer which is to be used for taking screenshots/pdfs of urls, you can see the code I am using here: https://bitbucket.org/petarvasilev/puppeteer-screenshots

I am having a problem on line 122 of screenshot.js where I am using .waitForNavigation to wait until all lazy load images are loaded and then proceed with the rest of the script; however when there are no lazy load images the script fails with timeout 30000ms exceeded error.

You can replicate the error by running the script using the following command:

node app.js --url=http://sailsjs.com/ --lazyLoad=true

note that it works without the lazy load part. 

I am not sure but maybe I am using 'waitForNavigation' incorrectly. Also, maybe a new method can be implemented like: 'waitForNetworkIdle()' which would more accurately reflect what I am trying to do.

**Comment by aslushnikov** [comment]
@petarvasilev91 yes, this is a known issue. @pavelfeldman has some patch in works that implements lifecycle events support and that should address this issue.

**Comment by petarthewizard** [comment]
Will that patch be implemented in the official version?

**Comment by pvtulsiram538** [comment]
--disable-timeouts-for-profiling will work for sure

**Comment by pvtulsiram538** [comment]
--disable-timeouts-for-profiling will work for sure

**Comment by aslushnikov** [comment]
> I am making a wrapper around Puppeteer which is to be used for taking screenshots/pdfs of urls, you can see the code I am using here: https://bitbucket.org/petarvasilev/puppeteer-screenshots

@petarvasilev91 It looks like the privacy settings don't let me see your code.

> Will that patch be implemented in the official version?

It's already implemented in v0.13.0-alpha (current tip-of-tree)

**Comment by petarthewizard** [comment]
@aslushnikov I've made it public again you can take look. Thanks

**Comment by aslushnikov** [comment]
@petarvasilev91 The v1.0.0 was released with support for lifecycle events. The images should not be loaded.

Please don't hesitate to write back/file new issue if it still doesn't work for you.
