### ISSUE TITLE
[Bug]: Proxy changed to DIRECT when running Chromium through Puppeteer

### ISSUE THREAD

**Issue by KennyAmex** [puppeteer/puppeteer#8603]
### Bug description

I call `puppeteer.launch` with the following options:
```
        launch: {
            executablePath: process.env.PUPPETEER_EXECUTABLE_PATH,
            headless: headless,
            args: [
                `--window-size=${width},${height}`,
                `--log-net-log=my_logfile`,
                `--proxy-pac-url=my_corporate_proxy.pac`,
            ],
            defaultViewport: null,
            slowMo: 0,
            devtools: true,
            env: {},
        },
        browserContext: 'incognito'
```

I expect my tests to run fine, however I observe that trying to fetch any URLs other than `localhost` does not work. Requests hang until timeout. I also get the same behavior if I open a new tab on the puppeteer chromium instance and try to navigate to `google.com`.

When capturing net logs, I initially see a PROXY_CONFIG_CHANGED event with the information I expect:
```
11: NONE
PROXY_CONFIG_CHANGED
Start Time: 2022-06-30 16:36:09.876

t=1645 [st=0]  PROXY_CONFIG_CHANGED
               --> new_config =
                      PAC script: my_corporate_proxy.pac
```

However after this, I see another event where proxy config is changed to use DIRECT connections:
```
23: NONE
PROXY_CONFIG_CHANGED
Start Time: 2022-06-30 12:54:40.226

t=1720 [st=0]  PROXY_CONFIG_CHANGED
               --> new_config =
                      Use DIRECT connections.
```

The launch command from the net log is: 
```
...my_project_path/node_modules/puppeteer/.local-chromium/mac-950341/chrome-mac/Chromium.app/Contents/MacOS/Chromium 
--disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess 
--disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad 
--disable-client-side-phishing-detection 
--disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage 
--disable-extensions --disable-features=Translate --disable-hang-monitor --disable-ipc-flooding-protection 
--disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync 
--force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic 
--use-mock-keychain --enable-blink-features=IdleDetection --export-tagged-pdf --auto-open-devtools-for-tabs 
--window-size=1200,1000 --log-net-log=my_net_log.json --proxy-pac-url=my_corporate_proxy.pac 
--remote-debugging-port=0 
--user-data-dir=/var/folders/3t/w37y325d5g9b4h2bgn399cph0000gn/T/puppeteer_dev_chrome_profile-kE0o7C 
--flag-switches-begin --flag-switches-end 
--file-url-path-alias=/gen=...my_project_path/node_modules/puppeteer/.local-chromium/mac-950341/chrome-mac/gen 
--flag-switches-begin --flag-switches-end about:blank
```

If I copy/paste this same command into a terminal and run it, I have no issues connecting to proxy. Instead of getting configured to use DIRECT connections, I see this from the net logs in my non-puppeteer session, and it does not get reconfigured to DIRECT:
```
11: NONE
PROXY_CONFIG_CHANGED
Start Time: 2022-06-30 11:38:20.931

t=643 [st=0]  PROXY_CONFIG_CHANGED
              --> new_config =
                     PAC script: my_corporate_proxy.pac
```

### Puppeteer version

13.1.1

### Node.js version

14.18.2

### npm version

6.14.15

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
Do you have the same issue if you just run Chromium with those flags? I don't think Puppeteer is doing anything w.r.t. to proxy configuration and it looks like a chromium issue.

**Comment by KennyAmex** [comment]
The strange thing is I do _not_ encounter the same issue if I run Chromium (from the same binary) with those flags. It runs just fine when I run it directly from my terminal.

As an additional data point, I also tried running the Chromium directly with all of the aforementioned flags _except_ for `--proxy-pac-url`, and this also did not encounter the same issue. To reiterate, in this experiment I deleted my proxy argument and Chromium was still able to connect, with net logs showing it successfully using `my_corporate_proxy.pac`, which is configured in my Mac system settings.

Is it possible that when I run Chromium directly, it is pulling in some additional system settings that it can't access when run via Puppeteer?

**Comment by OrKoN** [comment]
> Is it possible that when I run Chromium directly, it is pulling in some additional system settings that it can't access when run via Puppeteer?

Hm, it's possible although I am not an expert on proxy settings configuration in Chromium. One thing that might be affecting this is if you are running with a fresh profile or not (the --user-data-dir param): when you run manually make sure that an empty folder is provided via --user-data-dir. 

Also, is the behaviour any different in the latest Puppeteer (with Chromium 104.0.5109.0)? Is there any difference between the headless/headful/chrome-headless?

**Comment by KennyAmex** [comment]
I encounter the same issue headless/headful. I'm not sure what chrome-headless is so I may need to try that. I'll experiment with --user-data-dir and updating Puppeteer and get back to you.

**Comment by KennyAmex** [comment]
I updated to Puppeteer to 15.2.0 and now it works as expected. Unclear what root cause was, but I'm glad it's working now. Thanks for your help!
