### ISSUE TITLE
[Bug]: https://pptr.dev is down

### ISSUE THREAD

**Issue by tony19** [puppeteer/puppeteer#8607]
### Bug description

The [website link](https://pptr.dev) shown in [`puppeteer`'s repo description](https://github.com/puppeteer/puppeteer) is down.

### Steps to reproduce the problem:

1. Open https://pptr.dev
2. Observe the 404

### Puppeteer version

n/a

### Node.js version

n/a

### npm version

n/a

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf-google** [comment]
Should be up now (you may need to wait a few hours/refresh your cache)
