### ISSUE TITLE
[Bug]: https://try-puppeteer.appspot.com/ is down

### ISSUE THREAD

**Issue by tony19** [puppeteer/puppeteer#8608]
### Bug description

The ["Try Puppeteer" link](https://try-puppeteer.appspot.com/) from the [Google Developer docs for Puppeteer](https://developer.chrome.com/docs/puppeteer/) is down.

### Steps to reproduce the problem:

1. Open https://try-puppeteer.appspot.com/
2. Observe the 404

### Puppeteer version

n/a

### Node.js version

n/a

### npm version

n/a

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
Thanks for the report. The site is no longer maintained and we will remove the mention from the docs: https://github.com/GoogleChrome/developer.chrome.com/pull/3134
