### ISSUE TITLE
WaitForFileChooser() never resolves but fileChooser opens up

### ISSUE THREAD

**Issue by justotherel** [puppeteer/puppeteer#8615]
### **Use case**

When trying to upload file through file chooser using the code presented in the [docs](https://pub.dev/documentation/puppeteer/latest/puppeteer/FileChooser-class.html), we encountered situation where waitForFileChooser() never resolves and fails on timeout, but file chooser opens up and is not torn down after executions ends.

### **Steps to reproduce**

Puppeteer version: 13.3.2
Platform / OS version: Windows 10
Node.js version: 12.22.4

Running this code from the docs

```
var futureFileChooser = page.waitForFileChooser();
// some button that triggers file selection
await page.click('#upload-file-button');
var fileChooser = await futureFileChooser;

await fileChooser.accept([File('myfile.pdf')]);
```
or, alternatively: 
```
const [fileChooser] = await Promise.all([
  page.waitForFileChooser(),
  page.click('#upload-file-button'),
]);
await fileChooser.accept([File('myfile.pdf')]);
```
results in execution failing with following error: ` TimeoutError: waiting for waiting for file chooser failed: timeout 30000ms exceeded`. `WaitForFilesChooser()` never resolves, but actual file chooser opens up and is not torn down when execution ends. 

While looking into similar issues, we assumed there might be some race condition preventing data from click() action to be received in time. But by the time click() invokes, nothing on the page may cause that. Furthermore, following code was working fine on puppeteer 4.0.0 before we updated the package to 13.3.2. 

From what we observe, it seems that file chooser is not being intercepted, as it would not appear on the screen otherwise. It opens but not reported by the browser over CDP. 

Is there something we're doing wrong or we stumbled upon a bug?

**Comment by jrandolf-google** [comment]
Please check out the latest Puppeteer version and documentation at `pptr.dev`. The docs you pointed to are not official.

**Comment by justotherel** [comment]
> Please check out the latest Puppeteer version and documentation at `pptr.dev`. The docs you pointed to are not official.

One of the code snippets in the report is identical to what is used in the [official docs on FileChooser](https://pptr.dev/api/puppeteer.filechooser#remarks) you shared. Running provided code:
```
const [fileChooser] = await Promise.all([
  page.waitForFileChooser(),
  page.click('#upload-file-button'), // some button that triggers file selection
]);
await fileChooser.accept(['/tmp/myfile.pdf']);
```
still produced the same error as in the original post

**Comment by sohaieb** [comment]
I had the same issue before, however my issue was that the clicked element selector is wrapped by a root-shadow, so to solve it I used something like: 
```
page.click('>>> #upload-file-button')
```

**Comment by braniubojni** [comment]
Do we have any solution for this. Encountering same issue.

**Comment by pierreminiggio** [comment]
I had the same issue in an older version of Puppeteer, then upgrading the versions got me stuck into a different bug `Protocol error (DOM.resolveNode): Either nodeId or backendNodeId must be specified.,` that I see there is there is another issue opened for here :
https://github.com/puppeteer/puppeteer/issues/7234#issuecomment-2481698839
