### ISSUE TITLE
[Bug]: error TS2577: Return type annotation circularly references itself.

### ISSUE THREAD

**Issue by IvanPizhenko** [puppeteer/puppeteer#8621]
### Bug description

Steps to reproduce the problem:

1. Try to use puppeteer from Typescript.

Versions:
```
    "puppeteer": "15.3.0",
    "ts-node": "^10.8.1",
    "typescript": "4.7.4"
```
Getting error in puppeteer type definitions:
```
node_modules/puppeteer/lib/types.d.ts:3071:60 - error TS2577: Return type annotation circularly references itself.

3071         ]>>(pageFunction: Func | string, ...args: Params): Promise<Awaited<ReturnType<Func>>>;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:3090:60 - error TS2577: Return type annotation circularly references itself.

3090         ]>>(pageFunction: Func | string, ...args: Params): Promise<HandleFor<Awaited<ReturnType<Func>>>>;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

### Puppeteer version

15.3.0

### Node.js version

16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

Linux

**Comment by IvanPizhenko** [comment]
Problem is here:
```ts
        /**
         * This method passes this handle as the first argument to `pageFunction`. If
         * `pageFunction` returns a Promise, then `handle.evaluate` would wait for the
         * promise to resolve and return its value.
         *
         * @example
         * ```ts
         * const tweetHandle = await page.$('.tweet .retweets');
         * expect(await tweetHandle.evaluate(node => node.innerText)).toBe('10');
         * ```
         */
        evaluate<Params extends unknown[], Func extends EvaluateFunc<[this, ...Params]> = EvaluateFunc<[
        this,
        ...Params
        ]>>(pageFunction: Func | string, ...args: Params): Promise<Awaited<ReturnType<Func>>>;
```
and here
```ts
        /**
         * This method passes this handle as the first argument to `pageFunction`.
         *
         * @remarks
         *
         * The only difference between `jsHandle.evaluate` and
         * `jsHandle.evaluateHandle` is that `jsHandle.evaluateHandle` returns an
         * in-page object (JSHandle).
         *
         * If the function passed to `jsHandle.evaluateHandle` returns a Promise, then
         * `evaluateHandle.evaluateHandle` waits for the promise to resolve and
         * returns its value.
         *
         * See {@link Page.evaluateHandle} for more details.
         */
        evaluateHandle<Params extends unknown[], Func extends EvaluateFunc<[this, ...Params]> = EvaluateFunc<[
        this,
        ...Params
        ]>>(pageFunction: Func | string, ...args: Params): Promise<HandleFor<Awaited<ReturnType<Func>>>>;
```

**Comment by jrandolf-google** [comment]
Could you write `@ts-nocheck` at the top of the `types.d.ts` file to see if that removes the warning and still allows intellisense?

**Comment by OrKoN** [comment]
I am not able to reproduce the issue with the default typescript config (both with skipLibCheck=true and with skipLibCheck=false). How does your tsconfig.json look like? It'd be great if you could share a repository reproducing this issue.

**Comment by dobesv** [comment]
This happened in our project.  I tried to reproduce this in a fresh project and couldn't.  

If these are the *only* typescript errors you are getting and you are using incremental builds, you could try deleting all your tsbuildinfo files and see if that helps.  If you have other errors, this error might be a side-effect of them.

You could also take a look at any calls to `evaluate` and `evaluateHandle` and add type annotations for parameters and return types.  Maybe the typescript checker is trying to infer a type and ending up in a loop that way.  For example if the return type of the function passed to `evaluate` seems to depend on the return type of `evaluate` itself, that might be the sort of thing that could lead to this error.

**Comment by dobesv** [comment]
Deleting `tsbuildinfo` files seemed to fix it for me, I think maybe the typescript compiler isn't always invalidating those properly when a dependency changes.

**Comment by IvanPizhenko** [comment]
Hi, I've also faced the same - after fixing something in my project, the problem has gone.

**Comment by codr1** [comment]
This currently happens to me the first time after I compile after I delte the dist directory.  Second run, the errors are gone.  I can reproduce on demand.

**Comment by OrKoN** [comment]
@codr1 pls provide a repro in a new issue.
