### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rylaz** [puppeteer/puppeteer#8622]

**Comment by OrKoN** [comment]
Please provide the test script to reproduce. It looks like the URL you are using is timing out though so it's likely not a bug in Puppeteer.

**Comment by rylaz** [comment]
> Please provide the test script to reproduce. It looks like the URL you are using is timing out though so it's likely not a bug in Puppeteer.

Hi, can we maybe talk in private so we can try a way to fix it together, I've tested the script with https://www.google.com it's still timing out

**Comment by OrKoN** [comment]
Navigating to google.com works fine for me so I am unable to reproduce. Please re-open an issue with a reproduction script or try asking for help on StackOverflow https://stackoverflow.com/questions/tagged/puppeteer.
