### ISSUE TITLE
waitUntil: continue with loaded page after timeout

### ISSUE THREAD

**Issue by mittster** [puppeteer/puppeteer#8626]
Puppeteer has a handy option for waiting until just 2 network requests are executed in the last 500ms:

`let response = await page.goto(url, { waitUntil:"networkidle2" , timeout:10000});
`

I use a timeout so that I am not stuck forever. The problem with timeout is that it throws an error when no time is left. Instead, I'd like to continue with the page I currently have. I can start a new page.goto, but now I have wasted precious time.

Is it possible to configure puppeteer to not throw when the timeout is passed and just assign to response what is currently loaded?

**Comment by OrKoN** [comment]
I think this feature already exists. There is a [waitForNavigation](https://pptr.dev/api/puppeteer.page.waitfornavigation) function that allows to do the following:

```
const [error, response] = await Promise.all([
    page.waitForNavigation({ waitUntil:"networkidle2" , timeout:10000}).then(() => {}).catch(err => err),
    page.goto('https://example.com'),
]);
```

This way the error would indicate if there was a timeout with networkidle2 and the response would be the response of the navigation. If the navigation without networkidle2 fails, it should still throw. 

Please try it out and see if it works for your use case.
