### ISSUE TITLE
[Bug]: The "--use-gl=egl" parameter is invalid in headless mode

### ISSUE THREAD

**Issue by Vinlic** [puppeteer/puppeteer#8638]
### Bug description

`const puppeteer = require("puppeteer-core");

(async () => {
    const browser = await puppeteer.launch({
        channel: "chrome",
        headless: true,
        args: ["--use-gl=egl"]
    });
    const page = (await browser.pages())[0];
    await page.goto("chrome://gpu/");
    await page.screenshot({
        type: "jpeg",
        path: "./gpu.jpg"
    });
    await browser.close();
})()
.catch(err => console.error(err));`

![gpu](https://user-images.githubusercontent.com/20235341/177502743-59be71f0-657e-425a-8eaf-aa2859ec707c.jpg)

### Puppeteer version

15.3.1

### Node.js version

16.14

### npm version

8.4.1

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by OrKoN** [comment]
Hey, thanks for the bug report! `--use-gl=egl` works as expected on my MacOS system for headless. I suspect the issue it could be OS-specific according to the OSes listed in your report (or the hardware acceleration could be not available for various machine-specific reasons). Anyway it looks like a bug in Chromium headless: could you please report
 the issue via http://crbug.com/new (the right component would be Internals->Headless)?

![gpu](https://user-images.githubusercontent.com/399150/177518659-ead18bb0-0413-4d90-9e70-f385c952b12d.jpg)

**Comment by Vinlic** [comment]
@OrKoN 
Thank you for your reply. Chrome on MacOS doesn't seem to support the real headless mode. Can you test the GPU acceleration of headless mode in Linux.

**Comment by OrKoN** [comment]
@Vinlic what do you mean by the real headless mode? Anyway the issue is better reported to the crbug.com to the team that works on headless.

**Comment by Vinlic** [comment]
@OrKoN It may be related to this:
![image](https://user-images.githubusercontent.com/20235341/177573782-24e8cb02-aed0-4d1f-8d83-f8b053fda810.png)

**Comment by OrKoN** [comment]
@Vinlic have you tried the new headless mode? `headless: 'chrome'` instead of `headless: true` in Puppeteer?

**Comment by Vinlic** [comment]
@OrKoN I just tried, but I still can't enable GPU acceleration on windows or Linux.

**Comment by Vinlic** [comment]
@OrKoN 
It seems that there is a little change. I set headless: "Chrome" and remove --use gl=egl, which shows that it supports GPU acceleration.

I don't quite understand why.....

const puppeteer = require("puppeteer-core");

(async () => {
    const browser = await puppeteer.launch({
        channel: "chrome",
        headless: "chrome",
        // args: ["--use-gl=egl"],
        ignoreDefaultArgs: []
    });
    const page = (await browser.pages())[0];
    await page.goto("chrome://gpu/");
    await page.screenshot({
        type: "jpeg",
        path: "./gpu.jpg"
    });
    await browser.close();
})()
.catch(err => console.error(err));

![gpu](https://user-images.githubusercontent.com/20235341/177577269-bf6e37fe-5169-45bc-9e9a-683e9b53e723.jpg)

**Comment by Vinlic** [comment]
@OrKoN 
I tried "--use-angle=vulkan" which can successfully start GPU acceleration :D
