### ISSUE TITLE
Certain useful TypeScript types no longer exposed since 15.2.0

### ISSUE THREAD

**Issue by niieani** [puppeteer/puppeteer#8639]
Affected version: 15.2.0+

Creating an issue by request of @jrandolf.

At least two issues were caused by #8584:
- not possible to access the `RemoteObject` of a JSHandle anymore ([details](https://github.com/puppeteer/puppeteer/pull/8584#issuecomment-1169017683))
- `Protocol` is longer re-exported, meaning the consumer needs to keep `devtools-protocol` version in sync with the one used by puppeteer, at least if they don't want to reach into a transitive dependency (i.e. undeclared in package.json).

Example where this is an issue: [niieani/puppeteer-intercept-and-modify-requests#4 (files)](https://github.com/niieani/puppeteer-intercept-and-modify-requests/pull/4/files)

**Comment by OrKoN** [comment]
I suggest we expose the remote object on JSHandle as an official documented API and  make the protocol types available so that you don't need to install the devtools-protocol package yourself.
