### ISSUE TITLE
Is there a way to open DevTools progammaticaly?

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#864]
* Puppeteer version: v0.12.0-alpha
* Platform / OS version: Windows 7 x 64

These hotkeys seem not to work:
```js
  page.press('F12');

  // or

  page.keyboard.down('Control');
  page.keyboard.down('Shift');
  page.keyboard.down('I');
  page.keyboard.up('I');
  page.keyboard.up('Shift');
  page.keyboard.up('Control');
```

**Comment by aslushnikov** [comment]
@vsemozhetbyt I don't think there's a way now. Why would you want this?

**Comment by vsemozhetbyt** [comment]
@aslushnikov To save some actions on debugging.

Does [`contents.openDevTools()`](https://electron.atom.io/docs/api/web-contents/#contentsopendevtoolsoptions) in Electron uses something unavailable for DevTools protocol?

**Comment by aslushnikov** [comment]
> Does contents.openDevTools() in Electron uses something unavailable for DevTools protocol?

I believe this is a c++ binding to devtools_window.

I just figured there's a chromium flag for this: `--auto-open-devtools-for-tabs`.
If you have time, I'd appreciate a PR that adds `devtools` option to the `puppeteer.launch`, nightmare has it.

**Comment by max-buranbaev** [comment]
Thanks for the this feature guys. Also It would be amazing if you could add a new param for opening particularly tab e.g. 'Console' or 'Network'

Thanks a lot.

**Comment by xXACCEXx** [comment]
Hey, I found this as a good solution.
`await puppeteer.launch({ devtools: true });`
this also forces the headless mode false.

found in the docs for v1.7. https://github.com/GoogleChrome/puppeteer/blob/v1.7.0/docs/api.md#puppeteerlaunchoptions

**Comment by aslushnikov** [comment]
> Also It would be amazing if you could add a new param for opening particularly tab e.g. 'Console' or 'Network'

@max-buranbaev why do you guys want some specific panel opened? What's your workflow?

**Comment by mihaimartalogu** [comment]
> @max-buranbaev why do you guys want some specific panel opened? What's your workflow?

@aslushnikov Here's my use case for this feature: displaying the console messages while running Cypress.io tests. Cypress is a great tool, but it lacks a way of getting the console logs of an automated test run, which makes errors that only occur in CI difficult to debug.
By opening devtools with the console panel at Cypress startup, the console logs would be visible in the video recording Cypress generates (https://docs.cypress.io/guides/core-concepts/screenshots-and-videos.html)

**Comment by dwelle** [comment]
Opening devtools with `console` panel open would be great indeed.

**Comment by zoutepopcorn** [comment]
For me this 
```
const SETTINGS = {
    headless: false,
    userDataDir: './data',
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--auto-open-devtools-for-tabs' ]
}
```

is working. 

Chromium remembers the last tab. It's not the 'perfect' solution, but it works :+1: 

I need the network tab open before the page load (else I need to reload the page again...)

**Comment by jeffhall-wk** [comment]
@mihaimartalogu I have a very similar use case: Recording a puppeteer script with ffmpeg and want to see the console rolling in the video. Would be awesome if there was a way to default to a certain tab in dev tools so I can see it recordings.

**Comment by jeffhall-wk** [comment]
@mihaimartalogu I got a little bit closer with this https://github.com/GoogleChrome/puppeteer/issues/3699

It gives me another browser tab that I can switch to/from and can use puppeteer keyboard commands to switch to the console pane.

**Comment by supdev1111** [comment]
i was able to open devtools the default Elements tab, how can i switch to console tab to send commands. anyone ?

**Comment by deadcoder0904** [comment]
I have a use-case where I have to inject some script in the DOM & after that run some JS. Did anyone solve this?

**Comment by jeffhall-wk** [comment]
@supdev1111 Closest I got was with this here https://github.com/GoogleChrome/puppeteer/issues/3699 Gives you a tab in chrome that is the devtools for another tab. Then you can issue puppeteer commands to it just like any other page. Not perfect because I have to write statements into my test to switch tabs at the right time to catch console logs in a video during test.

**Comment by gtkpr** [comment]
what class or object does `contents.openDevTools()` belong to exactly???

**Comment by BLamy** [comment]
> @max-buranbaev why do you guys want some specific panel opened? What's your workflow?

I'm building an internal developer tool in electron which logs to the console. I'd like to add a "logs button" in the app which pops open the chrome developer tools to the console tab. That way it's less confusing for people who have never used the app before. 

Sure I can go through the trouble of creating my own "logs page" inside the application but that's a lot of work for what i'm building; I'd rather just call `console.log`.

**Comment by deadcoder0904** [comment]
Stumbled upon this again 😂

Would love to have `Console` tab open directly instead of doing it manually all the time :)

Edit: Found https://github.com/puppeteer/puppeteer/issues/1352#issuecomment-486411215 in the other thread

**Comment by TobiasPfeifer** [comment]
Is there a way to open DevTools of the DevTools tab?
Need it to capture websocket frames: https://gist.github.com/signed/68f61bbebdd3375d6463d12d68e5a299

**Comment by lacvietanh** [comment]
Sat Nov 26, 2022
### Still can't find a way to open console tab directly... 😂
3 days walking around on google 🥲

**Comment by scythargon** [comment]
I need to open the network tab, guys :D

**Comment by matt-** [comment]
the following is working for me:
```javascript
	const targets = await browser.targets();
	const devtoolsTarget = targets.find((t) => {
	  return t.type() === 'other' && t.url().startsWith('devtools://');
	});
	const client = await devtoolsTarget.createCDPSession()
	await client.send('Runtime.enable');
	await client.send('Runtime.evaluate', {
		expression:`
			window.UI.viewManager.showView("network");
			window.UI.dockController.setDockSide("bottom")
		`
	});
```

**Comment by sovetski** [comment]
@matt- it did not work for me :/

**Comment by karlpothast** [comment]
This should work if you are using Linux :

exec('xdotool getactivewindow key ctrl+shift+i', (err) => {
});
