### ISSUE TITLE
[Bug]: page._client.send is not a function

### ISSUE THREAD

**Issue by ArtHoff** [puppeteer/puppeteer#8640]
### Bug description

Hi,
I'm attempting to take screenshots of large pages and kept getting this error:
`Protocol error (Network.getResponseBody): Request content was evicted from inspector cache`

Looking through the list of bug reports I found this solution and it worked just fine.
```
await page._client.send('Network.enable', {
      maxResourceBufferSize: 1024 * 1204 * 100,
      maxTotalBufferSize: 1024 * 1204 * 200,
    })
```
However with more recent versions of Puppeteer, this no longer works and I receive the following error:
`page._client.send is not a function`
Now, since `page._client.send` is no longer available, I am wondering whether something has replaced it that I should be using instead?

Thank you for your help with this.

### Puppeteer version

15.3.0

### Node.js version

16.15.1

### npm version

8.13.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
TypeError: page._client.send is not a function
    at myFunction (.../myprog.js:170:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by OrKoN** [comment]
Hey, there is a getter getter `_client()` to get access to the page's CDP session. Note that it's still not a public officially-supported API.

**Comment by ArtHoff** [comment]
Hello @OrKoN 

Thank you for this information. However this does not work for me. 

I've replaced my original code from:
`
await page._client.send('Network.enable', {
    maxResourceBufferSize: 1024 * 1204 * 100,
    maxTotalBufferSize: 1024 * 1204 * 200,
})
`

To: 
`
const client = await page.target().createCDPSession();
await client.send('Network.enable', {
    maxResourceBufferSize: 1024 * 1204 * 100,
    maxTotalBufferSize: 1024 * 1204 * 200,
});
`
However, now I'm back to my original problem:
`ProtocolError: Protocol error (Network.getResponseBody): Request content was evicted from inspector cache
    at /myProg/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:278:24`

It appears that maxResourceBufferSize and maxTotalBufferSize are not working when using this construct.

Is there anything else I need to do?

**Comment by OrKoN** [comment]
I think that command is coming too late when the request content has been already evicted. What is the complete code to reproduce? I believe to send the Network.enable command before you trigger the request. Please open a separate issue with the complete code to reproduce.
