### ISSUE TITLE
Can't set path to screenshot

### ISSUE THREAD

**Issue by wlxle** [puppeteer/puppeteer#8646]
### Bug description

Steps to reproduce the problem:

When I used the example，got this error message： “Error: Screenshots can only be written to a file path in a Node-like environment.”

`const puppeteer = require('puppeteer');`

`(async () => {`
  `const browser = await puppeteer.launch({headless: false});`
  `const page = await browser.newPage();`
  `await page.goto('https://example.com');`
  `await page.screenshot({path: 'example.png'});`

  `await browser.close();`
`})();`

### Puppeteer version

14.4.1

### Node.js version

10.12.0

### npm version

7.19.1

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Error: Screenshots can only be written to a file path in a Node-like environment.
```

**Comment by OrKoN** [comment]
Node version 10.12.0 is not supported. Please make sure you run using Node 14+ and the latest Puppeteer version.
