### ISSUE TITLE
[Bug]: Puppeteer @14.3.0 cannot creating browser instance. Reference error: URL is not defined

### ISSUE THREAD

**Issue by Royaladvisor26** [puppeteer/puppeteer#8658]
### Bug description

Steps to reproduce the problem:

1. Upgrading from puppeteer 1.9.0 to 14.3.0
2. Run `const browser = await Promise.race([puppeteer.launch({headless: false, executablePath: 'path\to\local\chrome'}), new Promise((resolve, reject) => setTimeout(reject, 10000))]);`
3. Get `URL is not defined` error at `NodeWebSocketTransport.ts` from `puppeteer`, console warning as shown below

<img width="663" alt="image" src="https://user-images.githubusercontent.com/68893035/178294668-f3923a85-c771-475c-8e88-c5df929539bf.png">

If someone could just point me towards why URL is not defined, that would be great. I'm not sure if any other params is needed in launch function to pass in the URL since I have seen tutorials without any. Sorry if this is a repeated issue else where but I have combed the repo and so far no issues with the same errors and I have been looking for a solution for days :(

P.s. I understand that the version of node and npm might not be compatible but I'm looking for a solution that doesn't require upgrading these as well. Thanks a lot in advance!

### Puppeteer version

14.3.0

### Node.js version

10.19.3

### npm version

6.14.17

### What operating system are you seeing the problem on?

Windows

**Comment by jrandolf-google** [comment]
Your node version is no longer supported. Please upgrade to 14+.

**Comment by Royaladvisor26** [comment]
@jrandolf I have upgraded my node version to `14.19.3` (originally `10.15.3`) but still having the same error. Could you reopen the issue? 
P.s. I have also cleared cache, deleted `node_modules`, `package-lock.json` and restarted the IDE to make sure the current node version is 14+.

**Comment by jrandolf-google** [comment]
Could you also upgrade Puppeteer. We no longer maintain < 15.

**Comment by Royaladvisor26** [comment]
Could I also check if version 15+ could work with chromium version 101.0.4951.64 (Official Build) (64-bit) ?

**Comment by Royaladvisor26** [comment]
@jrandolf I have upgraded to puppeteer version `15.3.0` and node `14.19.3` but still the same issue :( Could you reopen this?

**Comment by Royaladvisor26** [comment]
@jrandolf I hope it's okay if I open a new issue regarding this with the updated version so you don't have to reopen this issue again :)
