### ISSUE TITLE
Work on predefined profile

### ISSUE THREAD

**Issue by lockevn** [puppeteer/puppeteer#866]
I know Puppeteer creates a fresh user profile (it creates its own Chromium user profile which it cleans up on every run)

**What is the expected result?**
I would like to request it should have one more option to work with **predefined profile**
 - We might save a few moment for setup
 - We might not have to see **welcome screen** every time we run it, waste 1 tab for it
 - We might keep all authenticated cookie and site data, for recurring processing (say: 24/7 crawler), with hot reload.

**Comment by vsemozhetbyt** [comment]
@lockevn See `userDataDir` option in the [`puppeteer.launch([options])`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions).

**Comment by lockevn** [comment]
Yes, I was fooled by README "Puppeteer creates a fresh user profile" and missed that option.

For others:
 - run Puppeteer
 - on Windows, it creates temp profile in "C:\Windows\Temp\puppeteer_dev_profile-oaDUGz". You can see yours current running profile by go to `chrome://version`
 - make your setting, bypass welcome screen, login to your site, install extension ... at your wish
 - copy the profile to another folder (you can ignore error "file is in-used by another process")

so next time you can run with your pre-configured profile
```
const browser = await puppeteer.launch({
        userDataDir: `C:\usrdata\puppeteer_crawler_profile`
    });
```

**Comment by vsemozhetbyt** [comment]
@lockevn You can also do this for the first run with an empty pre-created folder:
```js
const browser = await puppeteer.launch({
        userDataDir: 'C:\\usrdata\\puppeteer_crawler_profile'
    });
```
After closing the Crome, all the user data will remain in the folder.

**Comment by szebenyib** [comment]
On Arch Linux the folder got created automatically

**Comment by pswzyu** [comment]
in my experiment, userDataDir only works if I use absolute path, using a relative path will only save things related to "crashpad"? into the folder, but all others are lost

**Comment by vsemozhetbyt** [comment]
@pswzyu See also https://github.com/GoogleChrome/puppeteer/issues/3453
