### ISSUE TITLE
[Bug]: npm install fails to run a second time if failures have been detected

### ISSUE THREAD

**Issue by whimboo** [puppeteer/puppeteer#8667]
### Bug description

Steps to reproduce the problem:

1. Clone the Puppeteer repository
2. Modify some source code to trigger eg linter failures
3. Run `npm install` and see it fail
4. Revert the code changes from step 2
5. Try to run `npm install` again

Step 5 will always fail now until you actually remove the `lib/` folder manually. The error that I get is the following

### Puppeteer version

14.4.1

### Node.js version

18.1.0

### npm version

8.8.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
$ npm install

> puppeteer@14.4.1 install
> node install.js

node:internal/modules/cjs/loader:939
  const err = new Error(message);
              ^

Error: Cannot find module './lib/cjs/puppeteer/node/install.js'
Require stack:
- /Users/henrik/code/puppeteer/install.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at download (/Users/henrik/code/puppeteer/install.js:35:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/henrik/code/puppeteer/install.js' ]
}

Node.js v18.1.0
npm ERR! code 1
npm ERR! path /Users/henrik/code/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
```
```

**Comment by jrandolf-google** [comment]
I'm not sure if we can consider this a bug. The install script needs to be compiled, so it's expected that after pulling in the source code, you will need to run `npm install` immediately.

**Comment by whimboo** [comment]
I have to reopen the issue given that I now have a better step to run into this problem. Similar as the last time I was on the `14.1.0` release and did a `git pull upstream` now to get the latest sources. Once done I wanted to install Puppeteer via `npm install` but that failed:

```
➜  puppeteer git:(main) ✗ npm install                                                                                                                git:(main|…2

> puppeteer@16.1.1 install
> node install.js

node:internal/modules/cjs/loader:939
  const err = new Error(message);
              ^

Error: Cannot find module 'pkg-dir'
Require stack:
- /Users/henrik/code/puppeteer/lib/cjs/puppeteer/initializePuppeteer.js
- /Users/henrik/code/puppeteer/lib/cjs/puppeteer/puppeteer.js
- /Users/henrik/code/puppeteer/lib/cjs/puppeteer/node/install.js
- /Users/henrik/code/puppeteer/install.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/henrik/code/puppeteer/lib/cjs/puppeteer/initializePuppeteer.js:19:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/henrik/code/puppeteer/lib/cjs/puppeteer/initializePuppeteer.js',
    '/Users/henrik/code/puppeteer/lib/cjs/puppeteer/puppeteer.js',
    '/Users/henrik/code/puppeteer/lib/cjs/puppeteer/node/install.js',
    '/Users/henrik/code/puppeteer/install.js'
  ]
}
```

I was only able to install the new version after manually removing the `lib/` folder from the local checkout. Given that I didn't invalidate any source before this seems to be a valid use case which should be fixed.

**Comment by OrKoN** [comment]
I have also seen this issue. I believe it only affects us as Puppeteer contributors. I wonder if we could automatically clean the build dir on git pull via Husky hooks?

**Comment by OrKoN** [comment]
We now have a clean step which has to be run manually if there are complication issues. It's unlikely we will prioritize changes here.
