### ISSUE TITLE
[Bug]: Screenshot is missing all css except inline styles

### ISSUE THREAD

**Issue by JoeVanGundy** [puppeteer/puppeteer#8686]
### Bug description

Steps to reproduce the problem:

When my node server takes a screenshot, all styles that are not inline are lost.
I've doubled check that my bundle is correct, and when I'm not using puppeteer it works perfectly.

Is there something I'm missing, or some flag I may need to use in order to include css to puppeteer?
If not, could it be something with how ReactDOMServer.renderToString is handling it?

Here is my configuration

```
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    const page = await browser.newPage();

    await page.setViewport({
      width: 1002,
      height: 402,
      deviceScaleFactor: 2,
    });

    const node = (
      <html>
        <body
          style={{
            width: "1000px",
            minWidth: "1000px",
            height: "400px",
            padding: "0 !important",
            margin: "0 !important",
            overflow: "hidden !important",
          }}
        >
          <PlotRenderer plotData={plotData} />
        </body>
      </html>
    );
    const svgString = ReactDOMServer.renderToString(node);

    await page.setContent(svgString);
    const image = await page.screenshot();```

### Puppeteer version

10.1.0

### Node.js version

16.15.1

### npm version

8.11.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

_No response_

**Comment by OrKoN** [comment]
Hey, please try out with the latest Puppeteer version/Chrome as it 10.1.0 is somewhat stale. From the code you provided it does not look there is any CSS expect from the inline styles. If the CSS styles are loaded from the server that should be running, and you should watch out that the styles are available cross-site as you a setting the HTML content for an internal about:blank page. As it does not look like it's a bug with Puppeteer, please ask on StackOverflow how to achieve what you need.
