### ISSUE TITLE
[Docs] API reference should show inherited public methods 

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#8689]
If you look at https://pptr.dev/api/puppeteer.elementhandle/, you'd see that only the public methods defined on the ElementHandle class are shown and to see the inherited methods from JSHandle, one has to navigate to a different page. I think it might make sense to show inherited properties in the API reference for a class as well.

cc @jrandolf

**Comment by akashchouhan16** [comment]
Is this issue being worked upon? @OrKoN If not, I would love to pick this up 📜

**Comment by OrKoN** [comment]
@akashchouhan16 currently no one works on it. Happy to review a PR if you figure it out.
