### ISSUE TITLE
[Bug]: Clipboard Access not working in headless mode

### ISSUE THREAD

**Issue by vezaynk** [puppeteer/puppeteer#8692]
Stalebot closed my previous issue. Posting this as a substitute for the now closed #7888

### Bug description

Steps to reproduce the problem:

Code snippet:

```js
const browser = puppeteer.launch({ headless: true });
const page = browser.then((browser) => browser.newPage());
const blank = page.then((page) => page.goto("https://example.com"));
const context = browser.then((browser) => browser.defaultBrowserContext())
.then((context) =>
  context.overridePermissions("https://example.com", ["clipboard-read"])
);

await blank;
await context;
await page
    .evaluate(() => navigator.clipboard.readText())
    .then((a) => console.log(a));
```

Run the code snippet with `headless: false`, it outputs your clipboard. run with `headless: true` and it outputs an empty line.

### Puppeteer version

Latest

### Node.js version

Latest

### npm version

Latest

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
headless has a different clipboard implementation https://source.chromium.org/chromium/chromium/src/+/main:headless/lib/browser/headless_clipboard.h;l=20;drc=5666ff4f5077a7e2f72902f3a95f5d553ea0d88d (which seems to be used on Windows only and might be the source of the difference in behaviour) so we should file a crbug.com issue for that as it is not something we can fix in Puppeteer itself. The snippet works fine on Mac though but not in the headful mode as I get an exception that 'Document is not focused'.

**Comment by OrKoN** [comment]
```
const puppeteer = require('puppeteer');

(async function main() {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();
    await page.goto("https://example.com");
    const context =  browser.defaultBrowserContext();
    await context.overridePermissions("https://example.com", ["clipboard-read"])
    const data = await page.evaluate(() => navigator.clipboard.readText());
    console.log(data);
    await browser.close();
})();
```

**Comment by OrKoN** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1347380

**Comment by OrKoN** [comment]
This is working as expected according to the authors of the headless mode: https://bugs.chromium.org/p/chromium/issues/detail?id=1347380
