### ISSUE TITLE
[Bug]: Page.waitForSelector errors in Google Cloud Function, after 15.5.0 update

### ISSUE THREAD

**Issue by metamas** [puppeteer/puppeteer#8694]
### Bug description

Steps to reproduce the problem:

1. Setup a Google Cloud Function (GCF) that runs Node.js 16
2. Setup a project that depends on Puppeteer `=15.3.2` and uses various `Page.waitForSelector` calls
3. Ensure the script successfully deploys and executes in the GCF environment
4. Change your Puppeteer dependency to `^15.3.2` and redeploy your GCF
5. Upon execution, it is likely that your GCF script will throw errors that it previously didn't

**NOTE:** This occurred for me after initially setting up a GCF project with Puppeteer `^15.3.2`, but I only noticed the errors after the `15.5.0` release. Given the timing, and the particular changes in that release, I'm making the speculation that this bug occurred in `15.5.0`, not `15.4.0`. But I haven't confirmed that theory with testing.

### Puppeteer version

15.5.0

### Node.js version

16.16.0

### npm version

8.11.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: failed to find element matching selector "table#some-id"
at ElementHandle.$eval (/workspace/node_modules/puppeteer/lib/cjs/puppeteer/common/ElementHandle.js:663:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Object.scrapePreforeclosures (/workspace/scraper.js:96:26)
at async exports.subscription (/workspace/main.js:12:5)
```

**Comment by OrKoN** [comment]
Could you please share the entire script that demonstrates the issue? In 15.5.0 we only bumped the version of Chromium.

**Comment by metamas** [comment]
@OrKoN 

```javascript
const puppeteer = require("puppeteer");
const dayjs = require("dayjs");

async function main() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('https://www.example.com');

  const now = dayjs();
  const startDate = now.subtract(6, 'day').toDate().toLocaleDateString('en-US');
  const endDate = now.toDate().toLocaleDateString('en-US');

  await page.select('select[name=example', 'Example');
  await page.type('input[name=start]', startDate);
  await page.type('input[name=end]', endDate);
  await Promise.all([
      page.waitForNavigation(),
      page.click('input[type=submit]')
  ]);
  const results = await page.$$('table#example-table-a tbody tr td:last-child');

  if (results.length == 0) {
      await browser.close();
      return;
  }
  

  for (let i = 0; i < results.length; i++) {
      let hasError = false;
      
      const [resultTab] = await Promise.all([
          browser.waitForTarget(target => target.url() === 'https://www.example.com/data/example.php'),
          results[i].$eval('input[name=submit]', button => button.click())
      ]).catch(error => {
          hasError = true;
          console.error("Navigation to data page failed.\n", error);
      });
      if (hasError) continue;

      const resultPage = await resultTab.page();
      await resultPage.waitForNetworkIdle();
      const button = await resultPage.waitForSelector('input[src="icons/example.png"]')
      await Promise.all([
          resultPage.waitForNavigation(),
          button.click()
      ]).catch(error => {
          hasError = true;
          console.error("Navigation to details page failed.\n", error);
      });
      if (hasError) continue;

      // NOTE: The following call is where an error is thrown after updates
      await resultPage.waitForSelector('table#example-table-b');
      const dataRaw = await resultPage.$eval(
          'table#example-table-b tbody tr:nth-child(2) td:nth-child(2)',
          data => data.innerHTML
      ).catch(error => {
          hasError = true;
          console.error("Scraping data failed.\n", error);
      });
      if (hasError) continue;

      // ...parse data and send to database

      await resultPage.close();
  }

  return browser.close();
};
```

**Comment by metamas** [comment]
> Could you please share the entire script that demonstrates the issue? In 15.5.0 we only bumped the version of Chromium.

@OrKoN The breaking change for my situation could have happened in 15.4. As I mentioned, I did not test between 15.4 and 15.5, I only confirmed that rolling back to 15.3.2 fixed the issue.

**Comment by OrKoN** [comment]
@metamas the script you provided fails in the version 15.3.2 as well: with the error `Error: No element found for selector: select[name=example`. Could you please provide a working script? It does not look like example.com has all those elements that are expected.

**Comment by metamas** [comment]
@OrKoN That is expected if you are running the script exactly as I posted it. I replaced URLs and selectors that would identify the information I am actually scraping with dummy replacements (e.g. `select[name=example`). My intention was to show you how my script uses `puppeteer`, not exactly what I am using it on. Trust me that my script runs without error on 15.3.2.

**Comment by OrKoN** [comment]
@metamas the thing is that there were no changes in https://github.com/puppeteer/puppeteer/compare/v15.3.2...v15.5.0 except for the chromium roll. So to understand what is going on I need a complete repro. The error you posted "failed to find element matching selector" also comes not from waitForSelector but from $eval. So I would check if the selectors are still correct or if perhaps the page is very dynamic and in the new chromium build the race condition between waitForSelector and $eval is revealed. Anyway it does not look actionable for me at the moment. Please feel free to post the exact repro and then I can take a look.

**Comment by metamas** [comment]
@OrKoN I understand, but unfortunately my client was clear that they didn't want me publicly sharing specifics on the data my scripts are gathering for them. Perhaps, at least, others that run into this issue with their Cloud Functions will find this post useful. In any case, thanks for the time and attention on this.

The selectors I'm using are definitely correct, so I'd bet your second theory about a race condition being revealed is correct.
