### ISSUE TITLE
Puppeteer button click is not working when tests are run in parallel

### ISSUE THREAD

**Issue by vigneshcbv** [puppeteer/puppeteer#8696]
I use the code below to click the login button, and it works perfectly on a single browser. When the code is executed simultaneously in several browsers the login button is clicked, however navigation doesn't occur in some browser instances. 

```
 try {
      const login = await page.waitForSelector(loginButton, { visible: true });
      await login.click(loginButton);
      console.log('Login button clicked');
     
    } catch (err) {
      console.log('Login button Not clicked');    
     }
```

**Comment by OrKoN** [comment]
Could you please provide the entire script to reproduce the issue? Also, please specify all the version information (OS, node, npm, puppeteer, browser versions).
