### ISSUE TITLE
[Bug]: request.respond does not abort the request!

### ISSUE THREAD

**Issue by nokitoino** [puppeteer/puppeteer#8699]
### Bug description

When using  `page.on('request', request => {
        });` and intercept a request one can request.abort it, and it prevents the the request reaching the server. Now if one wants to feed the request by request.respond `puppeteer` does replace the file, but the request still reaches the server and the browser unnecessarily downloads the file. 
Now one cannot use request.abort and request.response in one swing, it will yield:
`Error: Request is already handled!`.

### Puppeteer version

puppeteer@15.5.0

### Node.js version

v16.3.0

### npm version

7.15.1

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Could you please provide a reproduction script? thanks!

**Comment by nokitoino** [comment]
I want this bug issue to be closed/deleted.
https://requestbin.com/r/enrfrq0kujnao/2CUDuDQVFKRIlENlNJTrqzVsz5L
`const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
        headless:true
    });
    const page = (await browser.pages())[0];
    await page.setRequestInterception(true);

    page.on('request', request => {

        if(request.url()==='https://enrfrq0kujnao.x.pipedream.net/'){

            request.respond({
                status: 200,
                contentType: 'text/html; charset=utf-8',
                body:'<html>Test</html>'
            });
            console.log("test");
            //request.abort();
        }else{
            request.continue();
            console.log("test2");
        }

        console.log(request.url());
    });

    await page.goto('https://enrfrq0kujnao.x.pipedream.net');

    await browser.close();

})();`. I found this site to test if the server really receives the GET requests. I thought so because my application used so much datavolume (by other things), that it appears to be downloading the big HTML/JavaScript files that I parse manually. But it is not if I am not mistaken by this reproduction I just made.
