### ISSUE TITLE
for a waterfall website ,can you set a function for auto scroll down until "selector" shown?

### ISSUE THREAD

**Issue by Wolke** [puppeteer/puppeteer#870]
as title
or how to scroll down ?

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by aslushnikov** [comment]
@Wolke you'll have to implement this on your end knowing the specifics of the website you're working on. There's no general way to do that.

In some cases, you'll be able to scroll down with the `window.scrollTo`:
```js
window.scrollTo(0,document.body.scrollHeight);
```

**Comment by vsemozhetbyt** [comment]
Maybe this issue can help a little: https://github.com/GoogleChrome/puppeteer/issues/844
