### ISSUE TITLE
[Bug]: Mouse Wheel has no effect on Canvas

### ISSUE THREAD

**Issue by nokitoino** [puppeteer/puppeteer#8703]
### Bug description

I get the mouse wheel to work if it's simply DOM elements to be scrolled. But within a canvas it seems like I can't get the emulation to work.

```
const puppeteer = require('puppeteer');
(async () => {
    const browser = await puppeteer.launch({
        headless:false
    });
    const page = (await browser.pages())[0];

    await page.goto('http://phrogz.net/tmp/canvas_zoom_to_cursor.html');
    const elem = await page.$('canvas');
    const boundingBox = await elem.boundingBox();

    await page.mouse.move(
        boundingBox.x + boundingBox.width / 2,
        boundingBox.y + boundingBox.height / 2
    );
    await page.waitForTimeout(3000);
    await page.mouse.wheel({ deltaY:-100 });
    await page.screenshot({path: 'example.jpg'});
    await page.waitForTimeout(3000);
    await browser.close();

})();
```
If you open the URL you see an image that you can zoom in by "scrolling" with your mouse. Isn't this feature simulating a real mouse wheel event?

### Puppeteer version

puppeteer@15.5.0

### Node.js version

v16.3.0

### npm version

7.15.1

### What operating system are you seeing the problem on?

Windows

**Comment by nokitoino** [comment]
I still found a workaround to use evaluate and using the WheelEvent, say something like this: `var scroll_evt = new WheelEvent('wheel', {
    deltaY:   - 1012.0,
    deltaMode: WheelEvent.DOM_DELTA_LINE,
    clientX:   -222,
    clientZ:   -111,
    bubbles: true,
    cancelable: false,
});
window.document.getElementsByTagName('canvas')[0].dispatchEvent(scroll_evt);`. Also there are three kind of "wheel" events I was confronted with. One can substitute here "wheel" with "mousewheel", and there also exists DOMMouseScroll.

**Comment by OrKoN** [comment]
Thanks the report. I am able to reproduce but it looks like some issue with the Chromium backend. Will have to investigate there.

**Comment by OrKoN** [comment]
Actually, I think it's the issue with the website. I verified via the protocol monitor that the wheel event is properly dispatched to canvas but CDP dispatches the wheel event and not mousewheel event that is deprecated and should not be used https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event I believe if the page listens to `canvas.addEventListener('wheel',handleScroll,false);` in addition to `canvas.addEventListener('mousewheel',handleScroll,false);` the automation should work as expected. As the mousewheel is deprecated, I don't think we are going to fix this.
