### ISSUE TITLE
[Bug]: Puppeteer not handling table data properly; produces white spaces between rows

### ISSUE THREAD

**Issue by rishikalokesh2512** [puppeteer/puppeteer#8707]
### Bug description

Steps to reproduce the problem:
Puppeteer functionality:
 const browser = await puppeteer.launch({
      headless: true
    });
    const page = await browser.newPage();
    await page.goto(BASE_URL, { waitUntil: 'networkidle2', timeout: 0 });
 const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      margin: {
        top: '40px',
        right: '0px',
        bottom: '60px',
        left: '0px'
      },
 headerTemplate:'<div>Header</div>',
footerTemplate:'<div>Footer</div>'
    });
await browser.close();
    return pdf;

Had a table in the BASE_URL page
Expected to produce table without any issues. Instead getting random spaces in between rows of random height.
Have added page-break-inside:avoid for all table elements
![Capture](https://user-images.githubusercontent.com/77378808/181567889-37b2279f-4553-4933-bea9-d94245259135.PNG)

### Puppeteer version

 "puppeteer": "^15.3.2",

### Node.js version

14.17.4

### npm version

6.14.14

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Hey, could you please provide the complete script to reproduce the issue including the HTML/CSS files that you want to print?

**Comment by rishikalokesh2512** [comment]
Its a simple table actually. attaching a snippet here:
` <div className="pdf-table-container">

          <table className="pdf-esop-table">

            <tbody>

              <tr>

                {headerValues.map((item, idx) => (

                  <th

                    key={`hvalues-${idx}`}

                    scope="col"

                    className="th_text th_color"

                    style={typeof item === 'object' && item.style ? item.style : { fontWeight: 400 }}

                  >

                    {item}

                  </th>

                ))}

              </tr>

              <tr style={{ height: '0px !important' }} />

              {!isAccordion &&

                !isEditable &&

                grantsInfo == null &&

                tableData.map((item, idx) => (

                  <React.Fragment key={`tableComponent-accordion-${idx}`}>

                    {!isScrollable && !isCollapsable && (

                      <tr className={item.isDisable ? 'disabled opacity-50' : ''}>

                        {headerKeys.map((key, map_key) => (

                          <td

                            tabIndex={0}

                            key={`headerKey-${map_key}`}

                            style={rowStyle.get(key)}

                            className={

                              'td_text no-outline ' +

                              (item.class ? item.class : '') +

                              (typeof handleClick == 'function' &&

                              map_key === 0 &&

                              (key === 'employeeName' || 'person_name' || 'employee_name')

                                ? 'employee_name'

                                : '') +

                              (item.shareholderName === 'Unalloted' ||

                              item.investorName === 'Unalloted Pool' ||

                              item.name === 'Unalloted Pool'

                                ? 'unalloted'

                                : '')

                            }

                            onClick={() => {

                              map_key === 0 && typeof handleClick == 'function' && handleClick(item);

                            }}

                          >

                            {item[key]}

                          </td>

                        ))}

                      </tr>

                    )}

                  </React.Fragment>

                ))}

            </tbody>

          </table>`


CSS: is simple, just some background colors and padding. Have added 
table,
th,
tr,
td {
  page-break-inside: avoid;
  page-break-after: auto;
}

**Comment by OrKoN** [comment]
@rishikalokesh2512 could you please provide a snippet we can run? this seems to be an excerpt from a React project that would be difficult for us to reproduce.

**Comment by rishikalokesh2512** [comment]
`<table>
<tbody>
<tr>
<th>Column1</th>
<th>Column2</th>
<th>Column3</th>
</tr>
<tr>
<td>Value 1</td>
<td>Value 2</td>
<td>Value 3</td>
</tr>
<tr>
<td>Value 1</td>
<td>Value 2</td>
<td>Value 3</td>
</tr>
<tr>
<td>Value 1</td>
<td>Value 2</td>
<td>Value 3</td>
</tr>
</tbody>
</table>`

CSS: table, tr, th, td { page-break-inside: avoid;
page-break-after: auto;}
 
This is the basic structure followed.

**Comment by sayo96** [comment]
Does anyone have an update on this? I'm running into a similar problem with page breaks as well even  though
1. I have proper styles to prevent page breaks 
2. None of the containers within which the table lives have `display: flex / grid` ( ie they are block level elements)

**Comment by OrKoN** [comment]
@sayo96 I don't think it is the same issue.

@rishikalokesh2512 I am unable to reproduce the issue with the HTML/CSS you provided. The printed PDF has no white space between rows. I used the following HTML page:

```
<style>
  table,
  tr,
  th,
  td {
    page-break-inside: avoid;
    page-break-after: auto;
  }

  table, th, td {
    border: 1px solid black;
  }

</style>
<table>
  <tbody>
    <tr>
      <th>Column1</th>
      <th>Column2</th>
      <th>Column3</th>
    </tr>
    <tr>
      <td>Value 1</td>
      <td>Value 2</td>
      <td>Value 3</td>
    </tr>
    <tr>
      <td>Value 1</td>
      <td>Value 2</td>
      <td>Value 3</td>
    </tr>
    <tr>
      <td>Value 1</td>
      <td>Value 2</td>
      <td>Value 3</td>
    </tr>
  </tbody>
</table>
```
and the following script:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.emulateMediaType('screen')
  let url = 'file:///Users/alexrudenko/pptr-test/tableBreak.html'
  await page.goto(url, {
    waitUntil: 'networkidle2',
  });
  await page.pdf({
    path: 'test.pdf',
    format: 'A4',
    printBackground: true,
    displayHeaderFooter: true, margin: {
      top: '40px',
      right: '0px',
      bottom: '60px',
      left: '0px'
    }, headerTemplate: `
  Header
  `,
    footerTemplate: `
  Footer
  `
  });
  await browser.close();
})();
```

**Comment by surajmestha89** [comment]
@rishikalokesh2512  This issue was Raised due to CSS styling. page-break-inside is not working if the current tag or parent tag has display flex or grid property. make the display property block.
Example: 
<tr>
    <td>
        <div style="display:block;page-break-inside: avoid;">data</div>
    </td>
</tr>

**Comment by daviatorstorm** [comment]
Check Pritset. It uses DOCX as a template. At least that worked for me.
