### ISSUE TITLE
[Bug]: Page break within table doesn't work

### ISSUE THREAD

**Issue by sayo96** [puppeteer/puppeteer#8708]
### Bug description

Steps to reproduce the problem:

1. I had a very simple html table. I have tried using `break-inside: avoid` in all the td , tr , table tags but the table appears to be cut in the middle in the exported pdfs 

### Puppeteer version

13.0.1

### Node.js version

14.19.1

### npm version

8.14.16

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
@sayo96 could you please share the HTML table you had and the script you used to print to PDF?

**Comment by sayo96** [comment]
Thanks for the swift response. I'm away from the computer now and ill be back on Tuesday. I will post the snippet that time. 

It was just a simple table and i was following everything that was mentioned as per the docs. I tried to use media queries / inline styles to prevent page breaks from the table but it didn't work :(

**Comment by sayo96** [comment]
@OrKoN I have a lot of fields in the page that i'm printing. 
 
 I'm actually printing a view with a lot of fields. It has display:flex in the parent. 
 
Here are my failed attempts to fix the page break:
 - I tried Changing the display :flex to display :block / inline since i read online that flex /grid have an issue with page breaks
 - I tried changing the view port based on page context
 
 
 
Script to print the pdf:
```
 const browser = await puppeteer.launch({
    ignoreHTTPSErrors: true,
    headless: true,
    args: puppeteerConstants.args,
    defaultViewport: puppeteerConstants.viewport,
  });
```
  
```
const pdfTitle = guid();
  const pdfName = opts.fileName || pdfTitle;
  const date = new Date();
  const day = date.getDay();
  const month = date.getMonth();
  const year = date.getYear();
  const pdfFilePath = path.resolve(TEMP_PATH, `${pdfTitle}.pdf`);

  const pdfOptions = {
    path: pdfFilePath,
    format: 'Letter',
    preferCSSPageSize: false,
    scale: 1,
    displayHeaderFooter: true,
    margin: { top: 20, bottom: 60 },
    headerTemplate: "<div/>",
    footerTemplate: "<div style=\"text-align: right;width: 297mm;font-size: 8px;\"><span style=\"margin-right: 1cm\"><span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></span></div>"
  };

 await page.pdf(pdfOptions);
```

 

Output:
![Screenshot 2022-08-03 at 2 59 37 pm](https://user-images.githubusercontent.com/26695583/182627109-cab50814-1eff-48f5-bf3d-88194bab215e.png)

What i need to achieve:
- I want a way to prevent the table / other fields from being cut due to page break

**Comment by OrKoN** [comment]
Could you share an example HTML file containing the table so that we could run tests on it? Does it happen when printing in the regular desktop browser too?

**Comment by sayo96** [comment]
@OrKoN Thank you for the swift response 🙏 . 
I have not tried  to printing using a regular browser like chrome.  I'm not printing a HTML File. 

- I have a view created by React within which the table is present.
The table data we have is like 
```
return (
    <StyledTD
      ref={(e) => { if (onRef && e) onRef(e); }}
      {...props}
      border={border}
      borderRight={borderRight}
    >
      {children}
    </StyledTD>
  );
```
Styles: 
```
const StyledTD = styled.div`
  background-color: transparent;
  font-size: ${(props) => (props.fontSize !== undefined ? `${props.fontSize}px` : DefaultStyles.fontSize)};
  color: ${(props) => props.fontColor || DefaultStyles.fontColor};
  font-style: ${(props) => props.fontStyle || 'normal'};
  font-weight: ${(props) => props.fontWeight || 'normal'};
  text-align: ${(props) => props.textAlign || 'left'};
  text-transform: ${(props) => props.textTransform || 'none'};
  text-decoration: ${(props) => props.textDecoration || 'none'};
  border-right: ${(props) => props.borderRight};
  ${(props) => (props.border ? `border: ${props.border};` : '')}
  padding: ${(props) => (props.padding !== undefined ? `${props.padding}px` : '3px')};
  resize: none;
  ${(props) => (props.textOverflow ? `text-overflow: ${props.textOverflow};` : '')}
  ${(props) => (props.textOverflow === 'ellipsis' ? 'white-space: nowrap;' : '')}
  ${(props) => (props.textOverflow === 'ellipsis' ? 'overflow: hidden;' : '')}
  max-width: ${(props) => (props.width !== undefined ? `${props.width}px` : 'initial')};
  min-width: ${(props) => (props.width !== undefined ? `${props.width}px` : 'initial')};
  vertical-align: top;
  cursor: ${(props) => (props.disabled ? 'not-allowed' : 'pointer')};
```

It happens to table fields and all other fields like simple text input as well.

**Comment by sayo96** [comment]
@OrKoN Please let me know if there is any update on this. None of the page break styles are working and this is holding our project from being deployed. Please help 🙏

**Comment by OrKoN** [comment]
Unfortunately, we need a complete repro (HTML/CSS/JS files of the page + a Puppeteer script) with a minimal example reproducing the issue. The issue is likely in the browser implementation (as Puppeteer just asks the browser for PDFs) so we will need the repro to file the bug upstream at crbug.com. We don't have capacity to reverse engineer the React snippets to get a working repro. If you could provide the repro, it'd be great.

**Comment by sayo96** [comment]
@OrKoN I'm not able to provide those since my code can't be shared in public. I will take the basic example mentioned in puppeteer and try to recreate my bug so you guys could work on it. Thanks a lot for responding to my comments over here. I appreciate it. I will keep you posted 👍

**Comment by Hideman85** [comment]
Getting the same issue and in fact when I use mys system chrome to print it does the job. I'm looking forward for the update :slightly_smiling_face:

**Comment by albinbrengesjo** [comment]
This is still a problem. I've read multiple threads where the answer is to not use flexbox. Just got rid of the all flex but the problem remains. Version 18.2.1

**Comment by istisiki** [comment]
This issue is still happening for me as well.
When using the browser print function, `break-inside: avoid` works. But not for the one made via puppeteer.

**Comment by HenrINC** [comment]
I encountered a similar issue when using `page.setContent`. However, I managed to resolve it by using `page.goto` with the HTML content encoded in a Base64 URL. Here's how I did it:

```javascript
const b64 = Buffer.from(HTMLContent).toString('base64');
await page.goto(`data:text/html;base64,${b64}`);
```

I would also like to mention that, for some unknown reason, I don't encounter this issue on Chromium version 102. So, it might be worth checking the behavior there too.

Additionally, I also experienced this issue even when I was solely using the Chrome DevTools Protocol without any wrapper. This leads me to believe that the issue originates from Chrome/Chromium itself, not Puppeteer.

**Comment by OrKoN** [comment]
Without a complete reproducible example, it's difficult to fix the issue. If you have a test page that demonstrates the issue in the latest Chrome version, please post an issue at crbug.com (Puppeteer usually only forwards PDFs created by the browser).

**Comment by casperski07** [comment]
hi @sayo96 , i just want to know if you fixed your issue with regards to table getting cut during page break?. I'm currently having trouble with it and can't find a clear answer or solution how to fix it . Thank you

**Comment by rakeshsahni** [comment]
> @OrKoN I have a lot of fields in the page that i'm printing.
> 
> I'm actually printing a view with a lot of fields. It has display:flex in the parent.
> 
> Here are my failed attempts to fix the page break:
> 
> * I tried Changing the display :flex to display :block / inline since i read online that flex /grid have an issue with page breaks
> * I tried changing the view port based on page context
> 
> Script to print the pdf:
> 
> ```
>  const browser = await puppeteer.launch({
>     ignoreHTTPSErrors: true,
>     headless: true,
>     args: puppeteerConstants.args,
>     defaultViewport: puppeteerConstants.viewport,
>   });
> ```
> 
> ```
> const pdfTitle = guid();
>   const pdfName = opts.fileName || pdfTitle;
>   const date = new Date();
>   const day = date.getDay();
>   const month = date.getMonth();
>   const year = date.getYear();
>   const pdfFilePath = path.resolve(TEMP_PATH, `${pdfTitle}.pdf`);
> 
>   const pdfOptions = {
>     path: pdfFilePath,
>     format: 'Letter',
>     preferCSSPageSize: false,
>     scale: 1,
>     displayHeaderFooter: true,
>     margin: { top: 20, bottom: 60 },
>     headerTemplate: "<div/>",
>     footerTemplate: "<div style=\"text-align: right;width: 297mm;font-size: 8px;\"><span style=\"margin-right: 1cm\"><span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></span></div>"
>   };
> 
>  await page.pdf(pdfOptions);
> ```
> 
> Output: ![Screenshot 2022-08-03 at 2 59 37 pm](https://user-images.githubusercontent.com/26695583/182627109-cab50814-1eff-48f5-bf3d-88194bab215e.png)
> 
> What i need to achieve:
> 
> * I want a way to prevent the table / other fields from being cut due to page break

Thanks, bro. Now I've resolved the margin and page break issues. The only things I have to remove are:

```javascript
args: puppeteerConstants.args,
defaultViewport: puppeteerConstants.viewport,

// because I don't know these variables in the given code.

const browser = await puppeteer.launch({
  ignoreHTTPSErrors: true,
  headless: true,
  // args: puppeteerConstants.args,  (removed)
  // defaultViewport: puppeteerConstants.viewport,  (removed)
});```
