### ISSUE TITLE
[Bug]: if scripts in a page using 'debugger' , page.goto will waiting all the time, how to solve it? 

### ISSUE THREAD

**Issue by libofei2004** [puppeteer/puppeteer#8714]
### Bug description

Steps to reproduce the problem:

I use page.goto(url, {timeout:20000, waitUntil: 'networkidle0'}) or page.waitForTimeout to load a page, if there is a 'debugger' statement in js in the page, the page.goto statement  will  waiting all the time , event if the waiting time is already over the 'timeout' time.
how can I solve this problem?

for example:
<html>
<title>tttt</title>
<script>
debugger
document.write("121212121212");
</script>
</html>

### Puppeteer version

12

### Node.js version

16

### npm version

8

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
@libofei2004 I am unable to reproduce. Are you running Puppeteer with DevTools open or in some other way enable the Debugger domain in CDP? https://chromedevtools.github.io/devtools-protocol/tot/Debugger/

**Comment by libofei2004** [comment]
@OrKoN  DevTools  is not open in my code. Is there any other way to enable the Debugger? I did nothing about it.

<img width="488" alt="pp1" src="https://user-images.githubusercontent.com/10001548/182312516-3f6ba110-21dc-4818-a4ac-fed93a9443bb.PNG">

I use this page to test.
<img width="293" alt="pp2" src="https://user-images.githubusercontent.com/10001548/182312943-cccd08c5-fbdd-44f4-a41b-3c7e2ee202cc.PNG">

In headless:false mode, the chrome has loaded and show the page completely.

<img width="296" alt="pp5" src="https://user-images.githubusercontent.com/10001548/182313117-b36a3155-795d-42e6-8736-668236debabd.PNG">

But my programme  is still waiting all the time.
 
<img width="530" alt="pp3" src="https://user-images.githubusercontent.com/10001548/182313306-d679ae73-eebf-4e6c-81a6-97c5075914f6.PNG">

<img width="169" alt="pp4" src="https://user-images.githubusercontent.com/10001548/182313342-18f3d8af-597a-46c3-965d-03b2d957a7b4.PNG">

**Comment by OrKoN** [comment]
@libofei2004 could you please share the entire program (with the test HTML file) to reproduce the issue? you can upload multiple files to gist.github.com and share the URL here.

**Comment by libofei2004** [comment]
@OrKoN You mind me! my programme is too big,  I simplify its main process and find what was wrong.
this is the code :
page.on('response', async (httpResponse) => {
    ......
    fs.mkdirSync(dir, {recursive: true},(err)=>{
        console.log("mkdir="+err);
   }   
 });
when mkdirSync is running, dir sometimes has invalid character，such as “:”, so the process  is not going on.
I have 2 questions:
1. why a Sync statement mkdirSync  in page.on('response') event can stop main process ?
2. why (err)=>{ } event  do not trigger when the dir is wrong?

**Comment by OrKoN** [comment]
@libofei2004 perhaps you could create a minimal reproduction to demonstrate the issue? Otherwise, I am unable to reproduce.

**Comment by libofei2004** [comment]
@OrKoN Thanks a lot, I have solved this issue，its not cauesd by debugger,  An error  is caused by doing fs.mkdirSync in response event because of invalid character  in filepath.
error code is:
page.on('response', async (httpResponse) => {
    let resurl = httpResponse.url();
    let args = getDirAndFile(resurl ,  ...);

    // dir is generated from resurl , so if resurl is "localhost:8081/...",then dir is "C:/sites/localhost:8081", 
   // invalid character ":" in dir.
    let dir = args.dir; 

   //Error is caused in this step with invalid dir, but only stop running ahead, not throw exception, 
  //so the main process is stopped.
    fs.mkdirSync(dir, {recursive: true},(err)=>{   
        console.log("mkdir="+err); //this message is not printed, I dont understand why
    });
});
await page.goto(url, { timeout:30000 , waitUntil: 'networkidle0'});
