### ISSUE TITLE
Unable To Load IFrames With Cross-Origin-Opener-Policy

### ISSUE THREAD

**Issue by timtrinidad** [puppeteer/puppeteer#8732]
I have been using puppeteer to screen-scrape home.nest.com. It's been working fine, but it seems that they recently changed how they manage oauth tokens. home.nest.com now calls https://accounts.google.com/o/oauth2/iframe which has the following headers set:

```
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: cross-origin
```

While desktop Chrome doesn't have any problems navigating the site and loading that iframe URL, puppeteer (even non-headless) blocks that URL with the following error:
```
(blocked:CoopSandboxedIframeCannotNavigateToCoopPage)
This document was blocked from loading in an iframe with a sandbox attribute because this document specified a cross-origin opener policy.
Learn more (https://web.dev/coop-coep/?utm_source=devtools)
```

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/2067202/182452491-eb0ffc2d-c2c2-466c-a83a-be90ab157fca.png">

I have tried passing all fo the following flags to `getBrowser`, with the same results:
```
--disable-web-security
--disable-features=IsolateOrigins
--disable-site-isolation-trials
--disable-features=site-per-process
--no-sandbox
--user-data-dir=/tmp/chrome
```
Has anyone else run into this yet? Is there any workaround at the moment?

**Comment by OrKoN** [comment]
Could you try running the desktop browser with the --remote-debugging-port parameter and connect to that instance using borwser.connect(). If the issue does not reproduce, it should be due to the flags Puppeteer starts the browser with. Also, could you provide the Puppeteer/browser version you are testing with and a basic script to reproduce the issue?

**Comment by timtrinidad** [comment]
I upgraded puppeteer/chrome and the issue no longer appears. I'll reopen if the error pops up again. Thank you for the response!
