### ISSUE TITLE
[Bug]: Old versions of Puppeteer API Docs inaccessible on documentation website

### ISSUE THREAD

**Issue by Dgarc359** [puppeteer/puppeteer#8733]
### Bug description

The earliest version available on the https://pptr.dev/ website is 15.3.0
I am trying to access docs for version: 10.1.0
Reason: This is the latest puppeteer version supported by AWS Synthetics
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html#CloudWatch_Synthetics_runtimeversion-nodejs-puppeteer-3.6

### Puppeteer version

10.1.0

### Node.js version

14

### npm version

-

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf** [comment]
Older versions of docs are no longer available on pptr.dev. Please check out the tagged repository for the version you are looking for and look for `api.md` in there.

**Comment by Dgarc359** [comment]
Thanks!

**Comment by KingCastillo** [comment]
Yes I would like to get in touch with the person who came up with the codes that actually went into my phone and to the person that received the coach because they stole all my IDs my credit cards and fraudulent using them and you helped him

**Comment by KingCastillo** [comment]
c8065485818@outlook.com

**Comment by PoolloverNathan** [comment]
@KingCastillo What do you mean?
