### ISSUE TITLE
[Bug]: The words are cutting in half across page breaks in PDF

### ISSUE THREAD

**Issue by cnj125** [puppeteer/puppeteer#8734]
### Bug description

Steps to reproduce the problem:

1. The words are cutting in half across page breaks while exporting in PDF

### Puppeteer version

15.4.0

### Node.js version

v16.15

### npm version

8.5.5

### What operating system are you seeing the problem on?

Windows

**Comment by jrandolf** [comment]
Could you provide a script to reproduce?

**Comment by cnj125** [comment]
I used the code below to generate the PDF file. The HTML page is created by WordPress, I tried to minimized the HTML and zipped the files. Please change the local path in the code to the test.html page. 

[HTML files](https://drive.google.com/file/d/16B3UYlUM2UJWSGJ990GDpo2rOZYvrg4p/view?usp=sharing)

`const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.emulateMediaType('screen')
  let url = 'file:///C:/your_local_path/test.html'
  await page.goto(url, {
    waitUntil: 'networkidle2',
  });
  await page.pdf({path: 'test.pdf', format: 'a4',scale: 0.52,
  margin: {
      top: '38.5px',
      right: '38.4px',
      left: '38.4px',
      bottom: '38.5px',
  },});
  await browser.close();
})();`

**Comment by jrandolf** [comment]
AFAIU, this looks expected to me. If the DOM element is too large, it will get cut. Could you also write your expectation?

**Comment by cnj125** [comment]
May I know if it is expected the words will be cut in half like the image below? Is there any way to prevent a word is cut into two pages?
[Sample Image](https://drive.google.com/file/d/1M2xDqSsa8rXdcLbg4blpFw26eHg_dhjR/view?usp=sharing)

Thanks a lot

**Comment by jrandolf** [comment]
There can be several reasons that the text is cut. The most common one is the DOM element is too large for the page, so the text may overflow poorly because the page size is Letter here. You can either increase the page size or make your DOM more page-friendly by using smaller DOM elements.

**Comment by OrKoN** [comment]
I am able to reproduce with the standard print dialog. So there is probably a workaround that can be done with CSS but also looks like an upstream bug in the PDF printing. When printed via Firefox, the lines are not truncated as well.

**Comment by OrKoN** [comment]
It'd be nice if someone could report it to crbug.com

**Comment by adisharma29** [comment]
Any solution or workaround for this?

**Comment by CavalcanteLeo** [comment]
any news on this?

**Comment by bnjab** [comment]
I'm getting the same error. @CavalcanteLeo's fix did not work for me.

<img width="444" alt="image" src="https://github.com/puppeteer/puppeteer/assets/87999090/46c31d28-d53b-4924-a4c1-3933fbfa7c5c">

I've tried setting margins and adjusting scale on puppeteer, margins on `@page`, and nothing seems to fix it.

**Comment by OrKoN** [comment]
Not reproducible in the latest version.

**Comment by feijuncheng** [comment]
the lastest version is ok, bug its hard for me, because of centos7 and node version

**Comment by diegoalmada** [comment]
Hello guys,

It has a same problem when I print the screen using puppeteer (v22.9.0) and chromium (v122.0.0). But It doesn't always happen this situation.


![Image](https://github.com/puppeteer/puppeteer/assets/704744/2edb01bd-c6de-46a5-9374-32fdcea9f658)

What do you know to happen this situation?
