### ISSUE TITLE
raspberry pi ELF: not found

### ISSUE THREAD

**Issue by happyDemon** [puppeteer/puppeteer#874]
### Steps to reproduce
on a raspberry pi  I installed puppeteer (the installation itself didn't give any error). 
Trying to start chromium I got 'ELF: not found'

**Tell us about your environment:**

* Puppeteer version: latest
* Platform / OS version: Debian 8.9
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

Not much to say here, installed it, tried to run it

**What is the expected result?**
a working process

**What happens instead?**
ELF: not found
node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: cannot open S: No such file
node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: �hP��PôPô����: not found
node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: @�: not found

**Comment by aslushnikov** [comment]
Unfortunately, puppeteer doesn't download chrome for arm.
See #550 for broad discussion.
