### ISSUE TITLE
[Bug]: Puppeteer v16 won't connect to browser servers created by Playwright

### ISSUE THREAD

**Issue by andyMrtnzP** [puppeteer/puppeteer#8747]
### Bug description

Steps to reproduce the problem:

1. Launch a Chromium server with Playwright (tested on 1.23.4 and 1.24.2)
```js
const { chromium } = require("playwright");
const getPort = require("get-port");

(async () => {
  const port = await getPort();

  chromium.launchServer({
    args: [
      `--remote-debugging-port=${port}`,
    ],
  });
  console.log(`Get wsEndpoint at ${`http://127.0.0.1:${port}/json/version`}`);
})();
```
2. Get the `webSocketDebuggerUrl` from the `/json/version` endpoint
3. Connect Puppeteer to the endpoint
```js
// pptr.js
const puppeteer = require('puppeteer-core');

(async () => {
  const browser = await puppeteer.connect({
    browserWSEndpoint: "ws://127.0.0.1:53866/devtools/browser/d7975090-196a-47a1-b5fe-bd2f723bef5e"
  });
  const page = await browser.newPage();
  await page.goto("https://example.com/");
  console.log(await page.title());

  await browser.close();
})().catch(console.error);

```

Using Puppeteer v15.5.0 it executes as expected
``` sh
>  node .\pptr.js
Example Domain
```

Using Puppeteer v16.0.0, it doesn't finish the connection, nor throws an exception

### Puppeteer version

v16.0.0

### Node.js version

v16.14, v16.15.1

### npm version

v8.5.5, v8.12.2

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by OrKoN** [comment]
I am able to reproduce and I have a fix in mind but I am also curious about the use case: what's the use case behind connecting to the browsers started by Playwright using Puppeteer?

**Comment by joelgriffith** [comment]
@OrKoN use case is having puppeteer start/provision chrome and use it's APIs to allow other clients to connect and do what they need. The primary failure is with playwright atm, but we also support any CDP-based libraries so I can see potential impacts there as well.

**Comment by OrKoN** [comment]
@joelgriffith thanks for the details! I think it's a bug on Puppeteer's side so it should not affect other CDP-based clients.
