### ISSUE TITLE
how to get page's threadId  which the page object belongs.

### ISSUE THREAD

**Issue by genglukuan** [puppeteer/puppeteer#8749]
Is there a way for me to get the number of the process to which the page object belongs? I want to use puppeteer to get the loading error of a page resource, but I can't find the correspondence between the intercepted error request and the page object. I found that the _requestId of the intercepted request is combined using the process ID, so I want to get the process number of the process to which the page object belongs.

**Comment by OrKoN** [comment]
Hey, I am not sure something like this exists. I suggest you try asking this question on StackOverflow: https://stackoverflow.com/questions/tagged/puppeteer perhaps someone there has an answer. There is a CDP command to get all process IDs https://chromedevtools.github.io/devtools-protocol/tot/SystemInfo/#method-getProcessInfo perhaps it might be useful to what you try to achieve.
