### ISSUE TITLE
How to insert custom pages using puppeteer?

### ISSUE THREAD

**Issue by viper-afi** [puppeteer/puppeteer#8752]
Hi, 

Good Day!

I am trying to convert a webpage into pdf, it was working fine. Here is it possible to inject custom pages in first page of PDF? Because In first page i have to write my name along with some details. These details are not present in the portfolio. Is it possible to create custom page? only on first index?

**Comment by OrKoN** [comment]
Hey, that's not possible in Puppeteer. Puppeteer only exports the PDF as provided by the browser's print function. To add custom pages to the PDF, you need to use some PDF modification library or modify your source page to include all information you need.
