### ISSUE TITLE
Exception when scraping some urls, TypeError Cannot read properties of null (reading innerHTML)

### ISSUE THREAD

**Issue by PortableDiag** [puppeteer/puppeteer#8756]
Whenever I scrape some urls, and specifically google news urls, I get the exception below. This is the latest available v15.5.0 on node v14LTS when using npm install puppeteer. 
This url also causes puppeteer to throw the exception many times: 
https://news.google.com/articles/CBMiLWh0dHBzOi8vZmFjdGNoZWNrLmFmcC5jb20vZG9jLmFmcC5jb20uMzJGVTlGVNIBAA?hl=en-US&gl=US&ceid=US%3Aen

Exception scraping url. Closing page. url:  https://news.google.com/articles/CBMiaGh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3dvcmxkL2FzaWEtcGFjaWZpYy9wZWxvc2ktZXhwZWN0ZWQtYXJyaXZlLXRhaXdhbi10dWVzZGF5LXNvdXJjZXMtc2F5LTIwMjItMDgtMDIv0gEA?hl=en-US&gl=US&ceid=US%3Aen
Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'innerHTML')
    at pptr://__puppeteer_evaluation_script__:1:22
    at ExecutionContext._ExecutionContext_evaluate (/root/scraper/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/root/scraper/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
    at async Scraper.waitTillHTMLRendered (/root/scraper/Scraper.js:96:26)
    at async /root/scraper/Scraper.js:154:11
    at async /root/scraper/Scraper.js:27:66
    at async Promise.all (index 0)
    at async mapIntoObjectAsync (/root/scraper/Scraper.js:27:19)
    at async Scraper.scrape (/root/scraper/Scraper.js:131:31)
    at async doTheScrape (/root/scraper/scraperservice.js:725:22)

**Comment by OrKoN** [comment]
Could you please share the minimal reproduction script?

**Comment by PortableDiag** [comment]
Here's the function in which it crashes, let me know if you need more of the code to reproduce.
It fails on: let bodyHTMLSize = await page.evaluate(() => document.body.innerHTML.length); of the following function:

 ```
async waitTillHTMLRendered(page, timeout = 30000) {
    const checkDurationMsecs = 1000;
    const maxChecks = timeout / checkDurationMsecs;
    let lastHTMLSize = 0;
    let checkCounts = 1;
    let countStableSizeIterations = 0;
    const minStableSizeIterations = 3;

    while(checkCounts++ <= maxChecks){
      let html = await page.content();
      let currentHTMLSize = html.length;

      let bodyHTMLSize = await page.evaluate(() => document.body.innerHTML.length);

      console.log('last: ', lastHTMLSize, ' <> curr: ', currentHTMLSize, " body html size: ", bodyHTMLSize);

      if(lastHTMLSize != 0 && currentHTMLSize == lastHTMLSize)
        countStableSizeIterations++;
      else
        countStableSizeIterations = 0; //reset the counter

      if(countStableSizeIterations >= minStableSizeIterations) {
        console.log("Page rendered fully..");
        break;
      }

      lastHTMLSize = currentHTMLSize;
      await page.waitForTimeout(checkDurationMsecs);
    }
  };
```

**Comment by OrKoN** [comment]
@PortableDiag could you please provide a complete script that reproduces the issue (along with the website URL)? Could you also check if the body is there? e.g., `await page.evaluate(() => document.body ? document.body.innerHTML.length : 0);` Perhaps for some reason the page has no document body.
