### ISSUE TITLE
No code execution after browser launch

### ISSUE THREAD

**Issue by Guest124** [puppeteer/puppeteer#8762]
### Bug description

After the line "const browser = await puppeteer.launch();" no further code execution occurs. There are no errors.
In Console output, only the line "11". The process in memory starts and does not stop. Chromium 92.0.4515.98
Code:
```
const puppeteer = require('puppeteer-core');
(async () => {
    console.warn('11');
  const browser = await puppeteer.launch({
    executablePath: '/usr/bin/chromium-browser',
    });
    console.warn('22');
  const page = await browser.newPage();
await page.goto('https://www.example.com');
..........
```

### Puppeteer version

16.1.0

### Node.js version

16.16.0

### npm version

8.11.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
11
```

**Comment by OrKoN** [comment]
I am unable to reproduce with the pinned version of Chromium. Note that 92.0.4515.98 is an old version and it is no compatible with the latest puppeteer. For example, v16.1.0 requires the 105.0.5173.0 version.
