### ISSUE TITLE
[Bug]: puppeteer page to pdf is not keeping anchors links 🔗

### ISSUE THREAD

**Issue by AurelienLoyer** [puppeteer/puppeteer#8778]
### Bug description

Generating a PDF using the node version of puppeteer, we are not able to keep internal links (anchor links working 😢)

![Aug-12-2022 09-55-21](https://user-images.githubusercontent.com/3717296/184310538-52da6f71-599b-4725-84f8-763fff4fd4ad.gif)

## Steps to reproduce the problem:

1. Create a simple html file 
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <a href="https://www.google.fr/maps/@50.6288598,3.0621533,14z">Google.fr maps</a>

    <ul>
      <li><a href="#test1">Test 1</a></li>
      <li><a href="/#test2">Test 2</a></li>
      <li><a href="./#test3">Test 3</a></li>
      <li><a href="./#test4">Test 4</a></li>
      <li><a href="#test5">Test 5</a></li>
    </ul>

    <h1 id="test1" style="margin-bottom: 500px">Test 1 title</h1>
    <h1 id="test2" style="margin-bottom: 500px">Test 2 title</h1>
    <h1 id="test3" style="margin-bottom: 500px">Test 3 title</h1>
    <h1 id="test4" style="margin-bottom: 500px">Test 4 title</h1>
    <h1 id="test5" style="margin-bottom: 500px">Test 5 title</h1>
  </body>
</html>
```

3. Serve the page using random server

2. Generate a pdf using the Node.js version of puppeteer

```ts
// ....
page.pdf({
              format: 'a4',
              printBackground: true,
              displayHeaderFooter: true,
});
// ....
```

🙏🙏🙏

### Puppeteer version

10.2.0

### Node.js version

14.17.6

### npm version

7.24.2

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by AurelienLoyer** [comment]
New information, i did a test using the last version of puppeteer 16.1.0, same issue 😢

**Comment by OrKoN** [comment]
@AurelienLoyer I am unable to reproduce: all links are clickable for me in the PDF I generated.

``` 
import puppeteer from 'puppeteer';

(async () => {
    const browser = await puppeteer.launch({
        headless: true,
    });

    const page = await browser.newPage();

    await page.goto('http://localhost:8080/print.html');

    await page.pdf({
      path: 'printPdf.pdf',
      format: 'a4',
      printBackground: true,
      displayHeaderFooter: true,
    });

    await browser.close();
})();

```

**Comment by OrKoN** [comment]
Is there anything I am missing? have you tried a different PDF viewer? Links work for me in the Chrome's built-in PDF viewer.

**Comment by AurelienLoyer** [comment]
You right 😅 it works using your snippet ! Thanks, i've plenty others parameters for the generation of the PDF like:
```
format: 'a4',
printBackground: true,
displayHeaderFooter: true,
pageRanges: '1',
headerTemplate: '',
footerTemplate: ``,
margin: ``,
```
I will investigate more thanks, i will be back with the reason!

**Comment by AurelienLoyer** [comment]
I found my problem, it came from the fact that we generated our pdf in two steps, a first page without header and footer and the others, then the whole was merged 

Because of that the links between page 1 and the others were broken...

Moral of the story, prefer the one shop generation of pdf! 

🙏 Thanks for the help !

**Comment by ticmaidev** [comment]
> Moral of the story, prefer the one shop generation of pdf!

it seems to be chrome thing. I was able to reproduce manually (ctrl + P). firefox is even worse...

i'm wondering if anyone has got any workarounds for this. generate 1 single PDF at once doesn't seem trivial.

**Comment by saran-surya** [comment]
So what actually happens is that, while printing there is a method from SKIA PDF that actually flattens out the PDF, and when we are restricting it to a particular page range, the trace of the destination link is missing, thus not rendering the internal links to the PDF. This might sound like a bug, But is working as intended. Maybe if they can control it with a flag parameter, it will be helpful while generating PDF's.
