### ISSUE TITLE
node-fetch@2.6.7 security vulnerable library

### ISSUE THREAD

**Issue by redwoodxiao** [puppeteer/puppeteer#8780]
Got a security vulnerable library from the scan for node-fetch@2.6.7. The recommended version of node-fetch is 3.2.10

└─┬ puppeteer-core@16.1.0
  └─┬ cross-fetch@3.1.5
    └── node-fetch@2.6.7 

similar issue 

https://github.com/lquixada/cross-fetch/issues/143

**Comment by jrandolf** [comment]
Thanks, once that bug resolves, we'll be sure to update our dependencies.
