### ISSUE TITLE
[Bug]: Style is not applied when using addStyleTag to generate PDF

### ISSUE THREAD

**Issue by NenadJovicic** [puppeteer/puppeteer#8781]
### Bug description

Steps to reproduce the problem:

I am using `puppeteer-core` package to generate pdf.
I am running docker container with installer browser, and generating PDF works fine, but I can't get css style applied.

My code looks like this
```typescript
    const browser: Browser = await launch({ executablePath: '/usr/bin/chromium-browser', args: ['--no-sandbox'] });
    const page: Page = await browser.newPage();
    await page.addStyleTag({
      content: `.section {
      width: 100%;
      margin: 5px 0px;
      background-color: red;
      border: 1px solid green;
      text-align: center;
    }`,
    });
    const pdfOptions: PDFOptions = this.getPdfOptions();
    await page.setContent('<div class="section">Some text</div>');
    const pdf: Buffer = await page.pdf(pdfOptions);
```

I have also tried with 
```typescript
await page.addStyleTag({ path: './assets/pdf.css' });
```
And it was throwing an error if I put some other path, saying that file does not exist, which means it loads file properly

But when I read page content after setting it with
```typescript
console.log(await page.content())
```
I get log like this
```html
<html><head></head><body><div class="section">Some text</div></body></html>
```

So, there is no style applied to html page.

PDF looks like this when I request it through Postman
![image](https://user-images.githubusercontent.com/2767416/184449775-3238e60d-7d83-4f05-abcc-98f2f7a6aa52.png)

### Puppeteer version

15.3.0

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Linux

**Comment by MatthiasKunnen** [comment]
[`page.setContent`](https://pptr.dev/api/puppeteer.page.setcontent) sets the full HTML of the page, not just the `body` so the problem you are having is that while your style gets applied successfully, you immediately overwrite it.

Try executing `page.setContent` immediately after `await browser.newPage()`.

**Comment by NenadJovicic** [comment]
Thanks for explanation.
It works now when I add styling after setting content
