### ISSUE TITLE
[Bug]: Having a hash symbol in a tag breaks eval and .content()

### ISSUE THREAD

**Issue by scdev0** [puppeteer/puppeteer#8784]
Steps to reproduce the problem:
```
const minHTML = `
<html>
    <body>
    <table>
        <tbody>
            <tr #>
                <td>
                    Table data in first row
                </td>
            </tr>
            <tr>
                <td>
                    Table data in second row
                </td>
            </tr>
        </tbody>
    </table>
    </body>
</html>`;

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(`data:text/html,${minHTML}`);
  console.log(await page.content());
  await browser.close();
})();
```
This logs out:
```
<html><head></head><body>
    <table>
        <tbody>
            </tbody></table></body></html>
```
But if I remove the '#' in the first `tr` tag then it works as expected.
This can be reproduced by having the '#' in other tags as well. I ran into this when the html had `<svg><use xlink:href="...#..."></use></svg>` and narrowed it down to the hash symbol.

### Puppeteer version

16.1.0

### Node.js version

v14.17.3

### npm version

6.14.13

### What operating system are you seeing the problem on?

Windows

**Comment by scdev0** [comment]
It might be the await page.goto(data:text/html,${minHTML}); that's the issue because if I replace it with await page.setContent(minHTML); then the page.getContent() outputs fine.

**Comment by stevenwdv** [comment]
`#` starts the fragment part of the URL, so the rest of the document is ignored, try `await page.goto(data:text/html,${encodeURIComponent(minHTML)});` instead.

**Comment by stevenwdv** [comment]
You say 'an actual URL', but a valid `data:` URL does not contain '#' in the data, or newlines for that matter, so you need to escape them like above. A regular valid URL also does not contain unescaped '#' except before the fragment. This is not a bug with Puppeteer.

**Relevant specs:**

- URLs in general: https://url.spec.whatwg.org/#valid-url-string (or https://datatracker.ietf.org/doc/html/rfc2396#section-4)
- `data` URL scheme: https://datatracker.ietf.org/doc/html/rfc2397#section-3

**Comment by scdev0** [comment]
What I meant is if I go to an URL e.g. `https://www.exampleurl.com` that returns `#` in the HTML response some where, then `page.content` or `page.$$eval` will not return the correct full HTML due having `#`. How can I fix going to the URL and getting the full HTML response?

**Comment by stevenwdv** [comment]
A '#' in the page content inside some HTML element? That shouldn't be a problem, is it?

**Comment by scdev0** [comment]
It is a problem. That's how I came across this issue.
1. The URL I go to using `await page.goto(URL)` has bunch of `<svg><use xlink:href="...#..."></use></svg>`
2. When using `await page.content()` or `await page.eval(...)` it doesn't have the full HTML content of the page, only up till the level depth before the first `<svg><use xlink:href="...#..."></use></svg>`. So a lot of content was missing.

**Comment by jrandolf** [comment]
Based on this discussion, it seems this is a non-issue.

**Comment by stevenwdv** [comment]
@scdev0 I'm not sure what you're doing, when I do this it prints the whole SVG doc:
```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('file:///path/to/some/svg-with-hash.svg');
console.log(await page.content());
```

**Comment by scdev0** [comment]
@stevenwdv Retested the page again. It does seem okay. Thanks!
