### ISSUE TITLE
how to load more extension?

### ISSUE THREAD

**Issue by viponedream** [puppeteer/puppeteer#8791]
### Bug description

how can we load more than 1 extension?
in many test, we need to load 2 or more extension.
how to do that, thanks

### Puppeteer version

last

### Node.js version

last

### npm version

last

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
how can we load more than 1 extension?
in many test, we need to load 2 or more extension.
how to do that, thanks
```

**Comment by jrandolf** [comment]
Could you get away with launching new instances per extension rather than one instance with many extensions?

**Comment by viponedream** [comment]
in many times we have to use two extensions, 
like
in a website,  we need to connect to to wallet to transfer,  each wallet has his own extension.

**Comment by OrKoN** [comment]
Have you tried to comma-separate the extensions in the --load-extension argument? See https://peter.sh/experiments/chromium-command-line-switches/#load-extension

I think we won't provide anything on top of what Chromium provides currently, therefore, closing as not planned for now.
