### ISSUE TITLE
[Bug]: The fullPage option is unavailable for some website

### ISSUE THREAD

**Issue by Baciii** [puppeteer/puppeteer#8797]
### Bug description

Steps to reproduce the problem:

1. The page.screenShot option ‘fullPage’ is unavailable for 'https://qapm.qq.com'

### Puppeteer version

13.5.2

### Node.js version

16.15.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
await page.screenshot({
      path: `xxx.png`,
      fullPage: true,
      type: "png",
    });
```

**Comment by OrKoN** [comment]
Could you please provide a minimal repro documenting expected and actual results?
