### ISSUE TITLE
Emulation API proposal

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#88]
Currently we have the following api to emulate devices:
```js
let names = page.emulatedDevices(); // to get list of emulatable devices
page.emulate('iphone 6'); // to emulate "iphone 6"
```

Problems with this api:
- having `emulatedDevices()` as a getter and under a page makes me feel that the device list might change over time and from page to page.
- it's hard to introspect what kind of options are actually set for the device, e.g. to see device's screen size
- it's hard to do my own device, or import someone's pre-made from npm

How about:
```js
// Puppeteer defines the "Device" class
class Device {
  constructor(name, userAgent, viewport, isMobile = true, hasTouch = true) {
    this.name = name;
    this.userAgent = userAgent;
    this.viewport = viewport;
    this.isMobile = isMobile;
    this.hasTouch = hasTouch;
  }
}

// The Device class and a list of all available devices are exposed
// in the top-level require
const {Browser, Device, devices} = require('puppeteer');

// `devices` list is an array with additional string properties. Devices
// could be both iterated and accessed via device names
devices[0];
devices.nexus5;

// If needed, a hand-made device could be done
let myDevice = new Device('handmade', 'handmade-webkit', {
  width: 100,
  height: 100,
  dpi: 2,
});

// Devices would be convenient to import from npm
let exoticDevice = require('list-of-exotic-devices-for-puppeteer');

// Finally, page can start emulating a device
page.emulateDevice(device);
page.emulatedDevice(); // returns currently-emulated device

// And we can change page's orientation
page.setOrientation('landscape'); // also could be 'portrait'
```

This kind of API would make emulation a first-class citizen in Puppeteer - which makes a lot of sense since devtools device emulation is very comprehensive.

**Comment by aslushnikov** [comment]
@paulirish @pavelfeldman guys, guys. WDYT?

**Comment by pavelfeldman** [comment]
Not sure if this makes things any better. Today, device is a pair or {viewport, userAgent}. It seems that the only change that you suggest is merging them into a single device entity and introducing a new `emulateDevice` method? Although that is fine with me, it makes UA emulation redundant (you already have specific methods for UA emulation). Looks like super-minor sugar overall. Today you can do:

```js

// If needed, a hand-made device could be done
let device = {
  width: 100,
  height: 100,
  deviceScaleFactor: 2
});

page.setViewport(device);
// When I want UA,
page.setUserAgent(deviceUserAgent);

```

**Comment by aslushnikov** [comment]
> It seems that the only change that you suggest is merging them into a single device entity and introducing a new emulateDevice method?

That's right. Here's a summary of the changes:
- make `page.emulateDevice(deviceConfig)` instead of `page.emulate(deviceName)` so that there's a single entry point for device emulation
- make `page.setOrientation` method so that orientation is not a part of a viewport
- expose pre-built devices as structs in the top-level require to make it simple to inspect devices and their emulation configs

> Although that is fine with me, it makes UA emulation redundant (you already have specific methods for UA emulation).

It's still nice to have both `setUserAgent` and `setViewport` methods - they might come handy at times. However, I think that a lot of times those who use `page.setUserAgent` or `page.setViewport` would rather emulate some device.

**Comment by pavelfeldman** [comment]
```js
const samsungDevices = requires(./sd);
const devices = require(puppeteer/DeviceDescriptors);

await page.emulateDevice(samsungDevices['GSIII_landscape']);
  await page.setViewport(device.viewport);
  await page.setUserAgent(device.ua));
```

**Comment by aslushnikov** [comment]
With the last patch, everything we've discussed is done. There's no `page.emulateDevice` for now, instead it's suggested to use `setViewport` / `setUserAgent` methods explicitly.

I've updated the doc to explain about emulation: [emulation](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#emulation)
