### ISSUE TITLE
INTERNAL ERROR: failed to find request for interception redirect

### ISSUE THREAD

**Issue by Khady** [puppeteer/puppeteer#880]
When I try to access this url, I get an assertion error. If I remove or change the user agent, the problem seems to disappear. Maybe the website has a different behavior for this UA, but it shouldn't crash puppeteer.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 9b0a06216e5b364aecaef6931d7844a91bebe46e
* Platform / OS version: debian stretch
* URLs (if applicable): https://tucsonfoodie.com/2016/07/18/truland-burgers-greens-a-choice-greens-graze-premium-burger-combined-concept-now-open/

**What steps will reproduce the problem?**

just run this code:

```
'use strict';

const puppeteer = require('puppeteer');

const USERAGENT = "Mozilla/5.0 (compatible;)";

(async() => {
  process.on("uncaughtException", (e) => {
    console.error("Unhandled exeption:", e);
    cont = false;
  });
  process.on("unhandledRejection", (reason, p) => {
    console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
    // application specific logging, throwing an error, or other logic here
    cont = false;
  });
  const args = [
    "--disable-gpu",
    "--disable-setuid-sandbox",
    "--force-device-scale-factor",
    "--ignore-certificate-errors",
    "--no-sandbox",
  ];
  const options = {
    args,
    headless: true,
    ignoreHTTPSErrors: true,
  };
  const browser = await puppeteer.launch(options);
  let cont = true;
  let n = 0
  while (cont) {
    console.log(n);
    n++
    try {
      const page = await browser.newPage();
      page.setUserAgent(USERAGENT);
      await page.setRequestInterceptionEnabled(true);
      page.on("request", (request) => {
        if (request.resourceType === "Image") {
          request.abort();
        } else {
          request.continue();
        }
      });
      await page.goto('https://tucsonfoodie.com/2016/07/18/truland-burgers-greens-a-choice-greens-graze-premium-burger-combined-concept-now-open/');
      await page.screenshot({ path: 'example.png' });
      await page.close();
    } catch (error) {
      console.error("exception", error);
    }
  }
  await browser.close();
})();
```

**What is the expected result?**

The program should run forever

**What happens instead?**

```
Unhandled Rejection at: Promise Promise {
  <rejected> { AssertionError [ERR_ASSERTION]: INTERNAL ERROR: failed to find request for interception redirect.
    at Console.assert (console.js:171:23)
    at NetworkManager._onRequestIntercepted (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/NetworkManager.js:134:15)
    at emitOne (events.js:115:13)
    at Session.emit (events.js:210:7)
    at Session._onMessage (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Connection.js:199:12)
    at Connection._onMessage (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Connection.js:98:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/home/team/prod/bin/test_server/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/home/team/prod/bin/test_server/node_modules/ws/lib/Receiver.js:389:14)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } } reason: AssertionError [ERR_ASSERTION]: INTERNAL ERROR: failed to find request for interception redirect.
    at Console.assert (console.js:171:23)
    at NetworkManager._onRequestIntercepted (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/NetworkManager.js:134:15)
    at emitOne (events.js:115:13)
    at Session.emit (events.js:210:7)
    at Session._onMessage (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Connection.js:199:12)
    at Connection._onMessage (/home/team/prod/bin/test_server/node_modules/puppeteer/lib/Connection.js:98:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/home/team/prod/bin/test_server/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/home/team/prod/bin/test_server/node_modules/ws/lib/Receiver.js:389:14)
```

**Comment by Khady** [comment]
Another URL: 
https://newwest.net/topic/article/cutthroat_habitat_faces_collapse/C41/L41/

**Comment by pvtulsiram538** [comment]
Hi bro i am also facing the same issue

**Comment by aslushnikov** [comment]
Thanks for filing this. I can repro with the following script:

```js
const puppeteer = require('.');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setUserAgent("Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/)");
  await page.setRequestInterceptionEnabled(true);
  page.on('request', (request) => request.continue());
  let n = 0
  while (true) {
    console.log(n++);
    await page.goto('https://newwest.net/topic/article/cutthroat_habitat_faces_collapse/C41/L41/');
  }
  await page.close();
  await browser.close();
})();
```

**Comment by perkfly** [comment]
I also encountered this issue

Edit:
sorry, my problem is that I intercepted the request twice...

**Comment by speedcom** [comment]
+1 Me too

**Comment by pg1671** [comment]
+1

**Comment by SpicySpaceman** [comment]
Same...

**Comment by Khady** [comment]
This bug appears very often for me. If the main team doesn't have time to fix it, could we have leads on where to look to try to fix it?

**Comment by speedcom** [comment]
For me the biggest reason for getting such errors was to be not possible to handle some resources but when started aborting them explicitly with puppeteer everything was ok.

**Comment by FdezRomero** [comment]
@speedcom What kind of resources did you start aborting? This may give the rest an idea on where to look...

**Comment by HanXHX** [comment]
any tip to bypass this issue?

**Comment by qpongo** [comment]
I am also experiencing the same issue -- headless and visible.

For me it's intermittent, maybe on the 3rd call and it happens during:
     **await page.waitForNavigation({ timeout: 10000, waitUntil: 'networkidle2' });**

**Assertion failed: INTERNAL ERROR: failed to find request for interception redirect**

NetworkManager.js - line 151 - request is null
```
  _onRequestIntercepted(event) {
...
    if (event.redirectStatusCode) {
151: const request = this._interceptionIdToRequest.get(event.interceptionId);
      console.assert(request, 'INTERNAL ERROR: failed to find request for interception redirect.');
      this._handleRequestRedirect(request, event.redirectStatusCode, event.redirectHeaders);
      this._handleRequestStart(request._requestId, event.interceptionId, event.redirectUrl, event.resourceType, event.request);
      return;
    }

```
Yes, I do abort 'image' type with:
```
 await page.waitForNavigation({ timeout: 10000, waitUntil: 'networkidle2' });
 page.on('request', (request) => {
    if (noImages && request.resourceType === 'image') request.abort();
```

> MyPuppeteerHtmlPage.js:117
Assertion failed: INTERNAL ERROR: failed to find request for interception redirect.
NetworkManager.js:152
    at _onRequestIntercepted ( \node_modules\puppeteer\lib\NetworkManager.js:152:14)
    at emitOne (events.js:116:12)
    at emit (events.js:211:6)
    at _onMessage ( \node_modules\puppeteer\lib\Connection.js:210:11)
    at _onMessage ( \node_modules\puppeteer\lib\Connection.js:105:18)
    at emitOne (events.js:116:12)
    at emit (events.js:211:6)
    at _receiver.onmessage ( \node_modules\ws\lib\WebSocket.js:143:46)
    at dataMessage ( \node_modules\ws\lib\Receiver.js:389:13)
    at getData ( \node_modules\ws\lib\Receiver.js:330:11)
    at startLoop ( \node_modules\ws\lib\Receiver.js:165:15)
    at add ( \node_modules\ws\lib\Receiver.js:139:9)
    at _ultron.on ( \node_modules\ws\lib\WebSocket.js:139:21)
    at emitOne (events.js:116:12)
    at emit (events.js:211:6)
    at addChunk (_stream_readable.js:263:11)
    at readableAddChunk (_stream_readable.js:250:10)
    at Readable.push (_stream_readable.js:208:9)
    at onread (net.js:594:19)

**Comment by Glennvd** [comment]
+1

**Comment by Glennvd** [comment]
Since there doesn't seem to be much progress on this issue, in the meantime, is it possible to just drop these requests and log the errors instead of fatally crashing on this? I've been generating screenshots of a website and it happens once every 10 requests or so. Not a blocking issue but annoying nonetheless.

**Comment by Khady** [comment]
> is it possible to just drop these requests and log the errors instead of
fatally crashing on this

I have been doing this by catching the exception, logging it but not
stopping the process. I don't know if it is sane, but at least I can use
pptr for more than one page in a row.

**Comment by aslushnikov** [comment]
@Khady @Glennvd can you guys please try installing puppeteer@next and see if the fix works for you?

```
npm install --save puppeteer@next
```
(puppeteer@next is auto-published from our tip-of-tree)

**Comment by Glennvd** [comment]
Hi @aslushnikov, I just gave @next a try but I can't really tell if this has fixed it. As I said I only have it around 10% of requests but @next pretty much broke my setup altogether. Receiving timeouts for around 50% of requests. Figuring out whats going wrong.

**Comment by aslushnikov** [comment]
@Glennvd the biggest change while migrating from 0.13.0 onto @next would be substitution of all getters with methods. Please see https://github.com/GoogleChrome/puppeteer/commit/b73737302a5dbfc5cd67f37be8460e53ab4f417f for details

**Comment by Glennvd** [comment]
Hey @aslushnikov, thanks for the tip, with some changes I got it to work. The fix for this issue seems to have drastically reduced the amount of occurrences. (From 12% to 3% to be exact). I haven't managed to reproduce the exact conditions when it occurs but for me personally, a 3% failure rate is acceptable.

**Comment by aslushnikov** [comment]
@Glennvd thanks for the update. I'm curious what are these 3% of failures?

**Comment by Glennvd** [comment]
Not 100% sure as I can't consistently reproduce it. We also have plenty of puppeteer boilerplate code that does all kind of things using requestInterception. I'll let you know if I stumble upon an actionable stacktrace
