### ISSUE TITLE
[Bug]: regression on browser.waitForTarget time out on v16, target.type() not returning valid value

### ISSUE THREAD

**Issue by danielcaldas** [puppeteer/puppeteer#8800]
### Bug description

Steps to reproduce the problem:

Run the following:
```js
const browser = await puppeteer.launch({
    headless: false,
    args: [
      `--disable-extensions-except=${pathToExtension}`,
      `--load-extension=${pathToExtension}`,
    ],
  });
  const backgroundPageTarget = await browser.waitForTarget(
    target => target.type() === 'service_worker'
  );
```

See the statement `waitForTarget` will timeout on `v16.1.1`. Same code snippet was working for puppeteer `v15.5.0`. I believe the target worker is no longer being considered a target.

### Puppeteer version

16.1.1

### Node.js version

14.16.1

### npm version

8.1.4

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
TimeoutError: waiting for target failed: timeout 30000ms exceeded

      45 |   let extensionTarget;
      46 |
    > 47 |   await browser.waitForTarget(x => x.type() === 'service_worker' || x.type() === 'worker');
         |                 ^
      48 |   const targets = await browser.targets();
      49 |   extensionTarget = targets.find(target => target.type() === 'service_worker');
      50 |

      at waitWithTimeout (../node_modules/puppeteer/src/common/util.ts:394:24)
      at Browser.waitForTarget (../node_modules/puppeteer/src/common/Browser.ts:663:35)
      at boot (../e2e/boot.js:47:17)
      at Object.<anonymous> (../e2e/tests/importExport.spec.js:24:21)
```

`console.log`ing the `target.type` I get only `browser` and `page`:

```
console.info
    !!!!!!!!!! browser

      at ../e2e/boot.js:47:44
          at Array.forEach (<anonymous>)

  console.info
    !!!!!!!!!! page

      at ../e2e/boot.js:47:44
          at Array.forEach (<anonymous>)
```
```

**Comment by OrKoN** [comment]
Thanks for the report. Could you provide an executable repro? We do have a test that waits for the service_worker and that is passing: https://github.com/puppeteer/puppeteer/blob/main/test/src/target.spec.ts#L186 so I wonder what is difference. How do you know that the type() is returning a wrong value? it looks like the target is simply not detected?

**Comment by danielcaldas** [comment]
Aargh 😔 You're right, my bad. My actual code had a typo, I had the below line a few lines above to grab the target.

```javascript
const target = targets.find(target => target.type === 'service_worker');
```

☝️  `type` is a function and not a property.

I think you can go ahead and close this one @OrKoN

**Comment by danielcaldas** [comment]
Yes. You can check this repo - https://github.com/tweak-extension/puppeteer-test-browser-ext/pull/2. The setup is straightforward, the example is very minimal.

**Comment by LittleMoonkk** [comment]
i get the same problem, it helps me!

**Comment by OrKoN** [comment]
@danielcaldas thanks for the repro! It looks like we were missing test coverage for this.

**Comment by LittleMoonkk** [comment]
@OrKoN Hello, now i use puppeteer-core v17.0.0 and got the same problem,is that a bug?
