### ISSUE TITLE
[Bug]:  Error: New navigation request was received

### ISSUE THREAD

**Issue by shtse8** [puppeteer/puppeteer#8811]
### Bug description

I can't catch this error and crash my application

https://github.com/puppeteer/puppeteer/blob/2a0eefb99f0ae00dacc9e768a253308c0d18a4c3/src/common/LifecycleWatcher.ts#L183

```
Error: New navigation request was received
    at LifecycleWatcher._LifecycleWatcher_onRequest (D:\project\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:136:139)
    at D:\project\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:68
    at Array.map (<anonymous>)
    at Object.emit (D:\project\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at NetworkManager.emit (D:\project\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at NetworkManager._NetworkManager_onRequest (D:\project\node_modules\puppeteer\lib\cjs\puppeteer\common\NetworkManager.js:311:10)
    at NetworkManager._NetworkManager_onRequestPaused (D:\project\node_modules\puppeteer\lib\cjs\puppeteer\common\NetworkManager.js:264:97)
    at D:\project\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:68
    at Array.map (<anonymous>)
    at Object.emit (D:\project\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)

```

I am awaiting `goBack` while the page is trying to redirect through js with some delay. this error was thrown and crash my application even the catch is wrapped the whole function.

example url: https://healow.com/apps/healow/download.jsp
`goback` action executes before it redirects

### Puppeteer version

puppeteer@16.1.1

### Node.js version

18.7

### npm version

18.7

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
@shtse8 could you please provide a minimal script to reproduce? Thanks!

**Comment by namma-lux** [comment]
```
await page.goto(SOME_URL);
await page.type('input[name=keywords]', 'hello world');
await Promise.all([
    page.waitForNavigation(),
    page.keyboard.press('Enter'),
]);
```

It typed the keywords, and redirect after pressing Enter.
Then it throw the error [New navigation request was received].

**Comment by shtse8** [comment]
> @shtse8 could you please provide a minimal script to reproduce? Thanks!

it's hard to reproduce, may need some time to find a best case.
anyway, the point is we can't catch all exception unless we use `process.onuncaughtexception`.

**Comment by OrKoN** [comment]
@shtse8 the problem why it fails is that event is not expected from the Puppeteer's perspective and it indicates a bug in Chromium or some unexpected scenario that we don't cover yet. Basically, the crash happens when Puppeteer receives two navigation requests instead of a single expected request. Since it all happens asynchronously there is no error handler for that exception. So a repro would be really helpful here.

**Comment by shtse8** [comment]
> @shtse8 the problem why it fails is that event is not expected from the Puppeteer's perspective and it indicates a bug in Chromium or some unexpected scenario that we don't cover yet. Basically, the crash happens when Puppeteer receives two navigation requests instead of a single expected request. Since it all happens asynchronously there is no error handler for that exception. So a repro would be really helpful here.

Understandable. Since the error goes out of scope so it's hard to be covered by the logic, we also need to catch all uncaught exceptions to prevent app crash. Mostly, evaluating something when the target page is being redirected, which I thought the exception should be thrown from the `evaluate` so that I can retry the action, but the exception sometimes (not must, that's why hard to reproduce. ) go out of scope and crash my application.
