### ISSUE TITLE
[Bug]: `Frame#content()` hangs and `Frame#url()` is empty for mixed-content frame (HTTP frame in HTTPS website)

### ISSUE THREAD

**Issue by stevenwdv** [puppeteer/puppeteer#8812]
### Bug description

Steps to reproduce the problem:

1. Set up an HTTPS&HTTP server serving the following files:

`index.html`:
```html
<!--not https:-->
<iframe src="http://your/server/frame.html"></iframe>
```

`frame.html`:
```html
hi
```

2. Execute:
```js
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://your/server/index.html');
const [, frame] = page.frames();
console.log('URL: ', frame.url());  // prints an empty URL
console.log('location:', await frame.evaluate(() => location));  // basically prints about:blank
console.log('content:', await frame.content());  // never prints: hangs
```

---
I'm not sure what the exact desired behavior is, but a hanging method doesn't seem intended in any case.

### Puppeteer version

16.1.1

### Node.js version

18.7.0

### npm version

8.17.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
URL: 
location: {
  ancestorOrigins: { '0': 'https://your/server' },
  href: 'about:blank',
  origin: 'null',
  protocol: 'about:',
  host: '',
  hostname: '',
  port: '',
  pathname: 'blank',
  search: '',
  hash: '',
  assign: {},
  reload: {},
  replace: {},
  toString: {}
}

```

**Comment by OrKoN** [comment]
@stevenwdv do you have a running server we can test it with? I was unable to reproduce with our test server setup.

**Comment by stevenwdv** [comment]
@OrKoN Sort-of, I used https://s-randomfiles.s3.eu-west-1.amazonaws.com/mixed-content.html

**Comment by OrKoN** [comment]
Yep, able to reproduce:

```

const puppeteer = require('puppeteer');

(async function main(){
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://s-randomfiles.s3.eu-west-1.amazonaws.com/mixed-content.html');
  const [, frame] = page.frames();
  console.log('URL: ', frame.url());  // prints an empty URL
  console.log('location:', await frame.evaluate(() => location));  // basically prints about:blank
  console.log('content:', await frame.content());  // never prints: hangs
})();

```

**Comment by OrKoN** [comment]
So it looks like the following happens: mixed content is blocked and therefore a new document is not created (the document remains to be about:blank), that leads for the execution context not being created that was supposed to be created by the `Page.addScriptToEvaluateOnNewDocument` call. The content() call requires the execution context and keeps waiting for it forever, thus, leading to the hanging. cc @jrandolf

**Comment by OrKoN** [comment]
Not able to reproduce the issue anymore, I suspect the issue was fixed either by changes in Puppeteer or in CDP.
