### ISSUE TITLE
[Bug]: AWS S3 bucket images are not rendered in generated PDF file.

### ISSUE THREAD

**Issue by karthika-ks98** [puppeteer/puppeteer#8816]
### Bug description

This is the function I use for generating the pdf.  

  const browser = await puppeteer.launch({ args: ['--no-sandbox'] });

  const page = await browser.newPage();
  const { token } = query;
  await page.setExtraHTTPHeaders({ authorization: token });
  await page.setRequestInterception(true);

  // add header for the navigation requests
  page.on('request', (request) => {
    if (!request.isNavigationRequest()) {
      request.continue();
      return;
    }

    // Add a new header for navigation request.
    const headers = request.headers();
    headers['X-Just-Must-Be-Request-In-Main-Request'] = 1;
    request.continue({ headers });
  });

  await Promise.all([
    page.goto(query.link, { waitUntil: ['domcontentloaded', 'networkidle0'] }),

  ]);
  await page.emulateMediaType('screen');

  const pdfShare = await page.pdf({
    path: 'puppeteerStackOverflow.pdf',
    width: 1920,
    height: 1080,
    printBackground: true,
  });
  await browser.close();

  return pdfShare;

The image get method returns a 400 error message.

### Puppeteer version

^16.1.0

### Node.js version

v14.16.0

### npm version

8.12.1

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Please provide a minimal reproducing script.
