### ISSUE TITLE
[Bug]: Puppeteer headless mode unable to play video in fullscreen

### ISSUE THREAD

**Issue by Himly1** [puppeteer/puppeteer#8819]
### Bug description

Steps to reproduce the problem:
1. set the argument **headless** to false of the code below and run it
2. you will see it playing the video in fullscreen
3. set the argument **headless** to true of the code below and run it again
4. check the youtube.png file in the current path you will see it not playing the video in fullscreen

code
```
const fullscreenButton = '.ytp-fullscreen-button'
async function main() {
    const browser = await puppeteer.launch(
        {
            /*
            set this value to your chrome or chormium(if you using linux) executable path
            the default is my chrome executable path on windows
             */
            executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
            headless: true, 
            args: ['--start-maximized'],
            userDataDir: './userData',
            ignoreDefaultArgs: ["--enable-automation"]
        })
    const page = await browser.newPage()
    let currentScreen = await page.evaluate(() => {
        return {
            width: window.screen.availWidth,
            height: window.screen.availHeight,
            deviceScaleFactor: 1
        };
    });
    
    await page.setViewport(currentScreen);
    await page.setDefaultNavigationTimeout(0)
    await page.goto('https://www.youtube.com/watch?v=aXuTt7c3Jkg&list=PLD8E5F0D70B62BEFE&index=2')
    await page.waitForSelector(fullscreenButton)
    await page.click(fullscreenButton)
    await page.waitForTimeout(2000)
    await page.screenshot({path: 'youtube.png'})
    await page.close()
    await browser.close()
}

main()

### Puppeteer version

^16.1.0

### Node.js version

v16.13.0

### npm version

8.1.4

### What operating system are you seeing the problem on?

Windows

### Relevant log output

_No response_

**Comment by Himly1** [comment]
In the first run of the code, you may need to click the play icon to skip the Ad and run the code again then it will work otherwise it will be stuck

**Comment by Himly1** [comment]
Here is the script
[script.zip](https://github.com/puppeteer/puppeteer/files/9387752/script.zip)

**Comment by OrKoN** [comment]
It looks like a problem in the headless implementation upstream. Try using the experimental `headless: 'chrome'` mode as this use case seems to work there.

**Comment by Himly1** [comment]
> It looks like a problem in the headless implementation upstream. Try using the experimental `headless: 'chrome'` mode as this use case seems to work there.

Thanks, it works for me.

**Comment by OrKoN** [comment]
The new headless mode is now the default mode used by Puppeteer.
