### ISSUE TITLE
screenshots are being cut after few runs when using emulation for mobile devices

### ISSUE THREAD

**Issue by sharonass** [puppeteer/puppeteer#882]
OS : Ubuntu 16.04
Puppeteer version: 0.10.2 heppens also in 0.12.0-alpha

When taking screenshots  several times with emulations after some time the screenshot returns cut image - possible  scale factor issues (see details below)

here is sample code for how im taking the screenshot:

const devices = require('puppeteer/DeviceDescriptors');
let browserInst = await puppeteer.launch(options);
const page = await browserInst.newPage();
await page.emulate(devices['Nexus 6P']);
await page.goto("http://download.cnet.com/archive/3000-2239_4-12795060.html",{waitUntil: 'networkidle'});
let screenshoot = await page.screenshot({fullPage : true});

the results are ok in the first few calls (first screenshot below) , but after some more calls I start to get wrong screenshots (second screenshot below) 
I've investigated furtur and found that if I used the emulation but overrides the scale factor (in above emulation its 3.5) to 1 or 0 it works well

success screenshot: 

![138211353034_621045_siteserved_appcelerate_mobile_200x200_1 3](https://user-images.githubusercontent.com/15667363/30815801-e1b4af80-a21c-11e7-99e3-7648cd72f10d.jpg)

failed screenshot: 

![138211353034_621045_siteserved_appcelerate_mobile_200x200_11 2](https://user-images.githubusercontent.com/15667363/30815711-a1b2c07a-a21c-11e7-8c02-6a551b418fe3.jpg)

**Comment by jamesrealweb3** [comment]
Maybe your UA information too old, try to change it (DeviceDescriptors.js) .

**Comment by wj-1993** [comment]
i have the same question, how to resolve

**Comment by sharonass** [comment]
I've resolved it to set manually the scalefactor to 0 or 1

**Comment by sharonass** [comment]
Actually the problem is there, scale factor 0 wont cut the screenshot but also the result page is not mobile

Any idea on how to resolve this, it happens only when I emulate mobile devices and also not always, but sporadically

**Comment by sharonass** [comment]
My screenshots emulations  are taken  from DeviceDescriptors.js - that's the  problem

**Comment by aslushnikov** [comment]
Seems to be a dupe of #477
