### ISSUE TITLE
Take the variable that gets the window scope in the browser

### ISSUE THREAD

**Issue by LLLLLamHo** [puppeteer/puppeteer#883]
I have a variable in the browser, the variable name is "a", how do I get it in puppeteer

**Comment by vsemozhetbyt** [comment]
@LLLLLamHo 
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    console.log(await page.evaluate(() => a));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**Comment by LLLLLamHo** [comment]
@vsemozhetbyt 

wow~ thanks!!!

**Comment by hi-hai** [comment]
@vsemozhetbyt 
This can't work in my case. Can you guide how to use that `3` in evaluate? Thanks.

```js
const puppeteer = require('puppeteer');

var a = 3 ;

(async function main() {
  try {
    const browser = await puppeteer.launch( { args: [ '--no-sandbox' ] });
    const page = await browser.newPage();

    console.log(await page.evaluate(() => a));

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

Error:

```
Error: Evaluation failed: ReferenceError: a is not defined
```

**Comment by vsemozhetbyt** [comment]
@hailite You have a different case: how to use a variable from Node.js (puppeteer) context in a browser context. You can transfer it via second `page.evaluate()` parameter:
```js
console.log(await page.evaluate(aFromNode => aFromNode, a));
```

**Comment by undrafted** [comment]
@vsemozhetbyt im trying the sample above to access the 'dataLayer'  window object - I understand that I need to wait for the GTM scripts to be attached here. But Im still getting undefined, any idea why/how this could happen? Although I could see the 'dataLayer' object on the browser console itself

```js
 const dataLayer = await page.evaluate('dataLayer');
    if (!dataLayer) {
        throw new Error('no datalayer found');
    }
```

**Comment by vsemozhetbyt** [comment]
@undrafted If `dataLayer` is a complex unserializable object, it can be transferred as `undefined`. From the doc:

> If the function passed to the `page.evaluate` returns a non-Serializable value, then `page.evaluate` resolves to `undefined`.

You can check if `dataLayer` is available by something like this:
```js
 const dataLayer = await page.evaluate('typeof dataLayer');
```

**Comment by undrafted** [comment]
thanks @vsemozhetbyt , would there be another way to get these complex objects from the window in puppeteer? - although the object could get pretty complex fast and could result to errors on serialization like ```JSON.stringify(datalayer) -> TypeError: Converting circular structure to JSON``` 

and weirdly enough in some cases typeof is an object, but its getting resolved to undefined :(

**Comment by vsemozhetbyt** [comment]
@undrafted Well, it seems you have two options: either extract all needed serializable data from `dataLayer` in the browser context and transfer this data to the puppeteer context, or get the [`JSHandle`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-jshandle) of this object and manipulate it via this handle's API.

**Comment by undrafted** [comment]
thanks for these ideas @vsemozhetbyt 👍
