### ISSUE TITLE
[Bug]: adding clip to `element.screenshot` creates invalid outputs

### ISSUE THREAD

**Issue by klebs6** [puppeteer/puppeteer#8834]
### Bug description

Greetings folks! I am attempting to screenshot an element with its `margin`, not the default clip settings.

Unfortunately, I am getting some odd behavior when I try to set the `clip` setting of `screenshot`.

I would have expected setting clip to bbox (in the screenshot below) to be a no-op:

<img width="835" alt="Screen Shot 2022-08-24 at 1 13 28 AM" src="https://user-images.githubusercontent.com/92199902/186334423-22f85a3b-a1e8-4f90-8649-e085720ff418.png">

Instead, the screenshots output are in many cases empty:

<img width="313" alt="Screen Shot 2022-08-24 at 1 15 48 AM" src="https://user-images.githubusercontent.com/92199902/186334722-742ea431-2fdd-4b3e-9bff-664a543941e6.png">

If I comment the line that says `clip: bbox`, I get the expected behavior -- although, if I comment this line, I don't know of another way to configure the screenshot clipping behavior to use the element margins.

I appreciate any help! Is this a bug? am I calling the API incorrectly? Is any more information required to properly diagnose the situation?  Thanks!!

### Puppeteer version

zenika-alpinechrome-withpuppeteer@1.0.0 , @cliqz/adblocker-puppeteer@1.23.9, puppeteer@6.0.0

### Node.js version

v18.7.0

### npm version

8.18.0

### What operating system are you seeing the problem on?

macOS

**Comment by klebz** [comment]
<img width="830" alt="Screen Shot 2022-08-24 at 1 36 43 AM" src="https://user-images.githubusercontent.com/92199902/186337504-e8a480d9-04e1-48e6-a6ba-8fabfae505b2.png">


This way works.. the only issue is that I don't yet know how to screenshot elements with margins

**Comment by jrandolf** [comment]
Could you provide a sample script?

**Comment by klebz** [comment]
This can probably be merged with #8833 because it is roughly the same problem
