### ISSUE TITLE
What is the reason of using a sync version of writeFile for pdf save?

### ISSUE THREAD

**Issue by tsabolov** [puppeteer/puppeteer#884]
https://github.com/GoogleChrome/puppeteer/blob/9b0a06216e5b364aecaef6931d7844a91bebe46e/lib/Page.js#L588
Why wasn't async version of `writeFile` used for writing the pdf?

**Comment by paulirish** [comment]
I presume there isn't a strong reason.. :)

If you wanted to change it, I'm sure the eng team would appreciate a pull request.

**Comment by Garbee** [comment]
If you do use the async version, it is still going to be `await`ed for processing. So is there any functional difference between the two at that juncture from the point of view of code operation?

**Comment by paulirish** [comment]
@Garbee reading [lib/fs](https://github.com/nodejs/node/blob/master/lib/fs.js) and [this post](http://www.daveeddy.com/2013/03/26/synchronous-file-io-in-nodejs/) it seems like the big difference is that the node event loop is blocked with sync, so any events coming from the chrome child_process (for example) would not be recognized until after. 

And there's [this issue](https://github.com/nodejs/node-v0.x-archive/issues/5596) suggesting that sync will always have inferior performance characteristics.

i can't think of a reason we NEED sync here, so might as well do the right thing.

**Comment by Garbee** [comment]
> big difference is that the node event loop is blocked with sync

SGTM then.

**Comment by paulirish** [comment]
Ah. there's already a PR for this: #879
