### ISSUE TITLE
Give support for selecting Chromium profile language instead of system default

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#885]
* Puppeteer version: 0.10.2
* Platform / OS version: macOS

Hi!
I'm trying to run the browser of puppeteer in Spanish, but my system is on English. Even I am Spanish I like to use my OS in English. 
But some mates in my team are using the OS in Spanish, so the webpage content is different for me and some of them! How can I normalize this by setting the language of the profile?
As on every launch puppeteer is creating a new profile, I can not configure it to choose a profile with Spanish, and also I can not specify the language by parameter. I tried --lang=ES and --profile-directory but as you know it removes the previous profile created, so even creating a new profile with headless to false, the next time won't be available.

**Comment by vsemozhetbyt** [comment]
You can try to pre-create an empty folder (say, `es-profile`) and launch the browser for the first time this way:
```js
puppeteer.launch({ headless: false, userDataDir: 'es-profile' });
```
not calling `browser.close()`.

Then set the profile language and send `Ctrl+C` to the node console to close the browser and exit script gracefully.

Then you can use the same `userDataDir` option in any other scripts if needed.

**Comment by ghost** [comment]
Thanks a lot! It works.
