### ISSUE TITLE
[Discussion]: Streaming audio in call

### ISSUE THREAD

**Issue by MrSelfisH01** [puppeteer/puppeteer#8850]
While searching for this, i found many questions and answers about joining a audio call or meeting. And recording audio streams from them.
But is it possible to send audio stream in the call/meeting itself?

I mean joining as a bot in the call. And then streaming from an audio file.

**Comment by OrKoN** [comment]
I don't think that is currently possible on the CDP level (and, thus, not in Puppeteer). But you can probably play the audio through the means provided by the operating system.

**Comment by OrKoN** [comment]
It's not something we are going to support any time soon, so I am going to mark the issue as closed.
