### ISSUE TITLE
[Bug]: failed to solve: failed to compute cache key: "/puppeteer-latest.tgz" not found: not found

### ISSUE THREAD

**Issue by 1011382654** [puppeteer/puppeteer#8851]
### Bug description

1、在第四步出现错误：
ERROR [4/5] COPY puppeteer-latest.tgz /home/pptruser/puppeteer-latest.tgz

2、如何获取puppeteer-latest.tgz文件

3、使用以下Dockerfile构建
https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile

### Puppeteer version

latest

### Node.js version

16.16

### npm version

8.11

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Are trying to build a custom Docker image? In that case make sure that puppeteer-latest.tgz is provided. You can use https://github.com/puppeteer/puppeteer/blob/main/docker/pack.sh to package the local version of Puppeteer for the Docker image.

**Comment by 1011382654** [comment]
> 
Thanks!

**Comment by 1011382654** [comment]
> Are trying to build a custom Docker image? In that case make sure that puppeteer-latest.tgz is provided. You can use https://github.com/puppeteer/puppeteer/blob/main/docker/pack.sh to package the local version of Puppeteer for the Docker image.

Thanks!

**Comment by timothydowd** [comment]
> Are trying to build a custom Docker image? In that case make sure that puppeteer-latest.tgz is provided. You can use https://github.com/puppeteer/puppeteer/blob/main/docker/pack.sh to package the local version of Puppeteer for the Docker image.

I get this error:  COPY failed: file not found in build context or excluded by .dockerignore: stat puppeteer-latest.tgz: file does not exist  

I am not using a dockerignore file

**Comment by michaelklopf** [comment]
@OrKoN 
Hey, I have no idea how to handle Docker properly, so I get that the tgz is not available, but where do you put the steps from that shell command? In the Dockerfile?

**Comment by jdeanff** [comment]
> Are trying to build a custom Docker image? In that case make sure that puppeteer-latest.tgz is provided. You can use https://github.com/puppeteer/puppeteer/blob/main/docker/pack.sh to package the local version of Puppeteer for the Docker image.

I am trying to build an image based on the `Dockerfile`.

From the root of the project directory I ran `./docker/pack.sh` but got the error:
```
> puppeteer@19.8.2 prepack
> wireit

sh: wireit: command not found
npm ERR! code 127
npm ERR! path <path-to-repo>/puppeteer/packages/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- wireit
```
Am I doing something wrong?

**Comment by locvfx** [comment]
@jdeanff , you need to init nodejs project file which has package.json, and install those dependencies
here are the commands:

cd docker
npm init --yes
npm install puppeteer puppeteer-core @puppeteer/browsers

after you have the fodler and files, run the script pack.sh
