### ISSUE TITLE
What is the right way of `click`ing an `ElementHandle<Node>` since v15.3.1

### ISSUE THREAD

**Issue by Qlub53** [puppeteer/puppeteer#8852]
I used to use [page.$x(expression)](https://github.com/puppeteer/puppeteer/blob/v13.4.0/docs/api.md#pagexexpression) and [elementHandle.click([options])](https://github.com/puppeteer/puppeteer/blob/v13.4.0/docs/api.md#elementhandleclickoptions) with puppeteer v13.4 just fine.
```ts
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto('https://example.com');
const handles = await page.$x('xpath');
await handles[0].click();
```

But now since the API signatures have changed ([$x(expression)](https://github.com/puppeteer/puppeteer/blob/v16.2.0/docs/api/puppeteer.page._x.md) and [click(this, options)](https://github.com/puppeteer/puppeteer/blob/v16.2.0/docs/api/puppeteer.elementhandle.click.md)), the above usage ends up with the following `tsc` compilation error:
```
error TS2684: The 'this' context of type 'ElementHandle<Node>' is not assignable to method's 'this' of type 'ElementHandle<Element>'.

7 await handles[0].click();
        ~~~~~~~~~~
```

How shall I transit from using `Element` to using `Node`?

_Originally posted by @Qlub53 in https://github.com/puppeteer/puppeteer/issues/8552#issuecomment-1229396443_

**Comment by OrKoN** [comment]
I think this is expected since XPath selectors might return not only elements. Try the following: `await (handles[0] as ElementHandle<Element>).click();` if the selector is guaranteed to contain an element.

**Comment by Qlub53** [comment]
Yeah, I circumvented it with type casting, too.
But having to type cast every single time makes the code really unpleasant to read.

Maybe this is one of few occasions where javascript is more attractive than typescript. 😂

**Comment by OrKoN** [comment]
@jrandolf What do you think? Can we do something to be type-correct but also make it easier for xpath users? e.g., maybe infer the type from the selector?

**Comment by jrandolf** [comment]
There are no plans to fix this anytime soon. See https://github.com/puppeteer/puppeteer/issues/8579 for potential alternatives being discussed.
