### ISSUE TITLE
[Bug]: Lighthouse crashes using puppeteer and request interception

### ISSUE THREAD

**Issue by mxkyb** [puppeteer/puppeteer#8868]
### Bug description

Steps to reproduce the problem:

See https://github.com/GoogleChrome/lighthouse-ci/issues/789

### Puppeteer version

17.0.0

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
See https://github.com/CosticaPuntaru/lighouse-ci-puppeteer-error
```

**Comment by OrKoN** [comment]
Do you have a repro without lighthouse-ci? If it does not repro, I believe lighthouse CI team should take a look first.
