### ISSUE TITLE
[Bug]: puppeteer-core trying to load package.json "Cannot find package directory"

### ISSUE THREAD

**Issue by lennybakkalian** [puppeteer/puppeteer#8896]
### Bug description

Steps to reproduce the problem:

1. create project with puppeteer-core dependency
2. build app and start without package.json in folder

why does this error occur? I have debugged the app and for reasons unknown to me, puppeteer tried to load a package.json. It can not be that you should push the package.json with a deployment, right?

if i build and run the app locally it works, but only because the package.json exists.

### Puppeteer version

16.2.0

### Node.js version

16.10.0

### npm version

7.24.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Cannot find package directory
    at exports.getPackageDirectory (/app/main.js:2:1175154)
    at exports.initializePuppeteer (/app/main.js:2:1115914)
    at Object.2056 (/app/main.js:2:1172454)
    at __webpack_require__ (/app/main.js:2:1730339)
    at Object.7157 (/app/main.js:2:578353)
    at __webpack_require__ (/app/main.js:2:1730339)
    at Object.5052 (/app/main.js:2:575175)
    at __webpack_require__ (/app/main.js:2:1730339)
    at Object.6828 (/app/main.js:2:574225)
    at __webpack_require__ (/app/main.js:2:1730339)
```

**Comment by OrKoN** [comment]
Puppeteer uses package.json to locate the Puppeteer's installation directory because it's where the downloaded browser binaries are stored by Puppeteer. If this functionality is not required for you, you can use the `puppeteer-core` package.

**Comment by imtiger** [comment]
i pack a electron app using puppeteer,in development envirement ,but when the app run at another computer,it not work.the error info in the picture.
![WechatIMG6204](https://user-images.githubusercontent.com/2855042/188278327-e7be6ae6-3380-4dae-976f-30fe62a2ce9d.jpeg)

**Comment by lennybakkalian** [comment]
@OrKoN unfortunately the same error also occurs with puppeteer-core.

I haven't read through the code much, but it looks like in puppeteer-core.ts the method [initializePuppeteer](https://github.com/puppeteer/puppeteer/blob/f9e758e31d71c75458d2b60ce692b290c4c3a841/src/puppeteer-core.ts#L24) is called, where getPackageDirectory is called, which leads to this error.

**Comment by OrKoN** [comment]
Oh, I was under impression, that puppeteer-core would not need this logic at all. Let me double check, if there is no real need, this might be a bug.

**Comment by imtiger** [comment]
> 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/2855042/188381136-5518485f-45d0-4c27-8009-852a3aa6a86f.png">

this is my package.json dependencies,i use puppeteer not puppeteer-core.

https://github.com/puppeteer/puppeteer/blob/eb6cea4f575467beca9a952ddf3045b7a38c44d5/src/util/getPackageDirectory.ts

this method throws the exception.
