### ISSUE TITLE
[Feature]: improve Docusaurus docs output to properly nest classes in sidebar

### ISSUE THREAD

**Issue by bert-w** [puppeteer/puppeteer#8897]
### Bug description

The docs on https://pptr.dev are barely readable with the very long sidebar. It would be nice if all elements are nested under their parent with a simple dropdown (like under "Guides", see below). I have no knowledge about Docusaurus so I cant really send in a PR (without wasting a lot of my time).

![image](https://user-images.githubusercontent.com/10498595/188270164-7ddc9614-2e7a-462e-9946-a88b07f1cd3a.png)

### Puppeteer version

latest (since the docs update)

### Node.js version

N/A

### npm version

N/A

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
This has been implemented now.

**Comment by bert-w** [comment]
Great! much appreciated
