### ISSUE TITLE
[Bug]: page.#timeoutSettings is not accessible anymore

### ISSUE THREAD

**Issue by GuillaumeGomez** [puppeteer/puppeteer#8901]
### Bug description

I used to rely on `page._timeoutSettings` but it was turned into a private field when upgrading my puppeteer version. Would it be possible to add a getter so I can still get it? I can even make a PR for it if you want.

Thanks in advance!

### Puppeteer version

17.1.1

### Node.js version

v14.19.3

### npm version

6.14.17

### What operating system are you seeing the problem on?

Linux, macOS, Windows

**Comment by OrKoN** [comment]
Thanks for opening the issue! We were not aware that someone relies on it. Could you please share the use case for getting access to #timeoutSettings? Do you intend to only read existing values or mutate them too?

**Comment by OrKoN** [comment]
So adding the following getter to the `Page` would be sufficient? 

```
getDefaultTimeout(): number {
    return this.#timeoutSettings.timeout();
}
```

**Comment by GuillaumeGomez** [comment]
Absolutely!

**Comment by GuillaumeGomez** [comment]
Sending a PR right away then. Thanks for the quick replies!
