### ISSUE TITLE
handleImageLoadError is not defined

### ISSUE THREAD

**Issue by pvtulsiram538** [puppeteer/puppeteer#891]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version:
* Platform / OS version:
* URLs (if applicable):

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by pvtulsiram538** [comment]
handleImageLoadError is not defined  when  interceptedRequest .abort() calls

**Comment by aslushnikov** [comment]
@pvtulsiram538 please, re-file this issue, filling in the issue questionnaire. This would help us to see what's going on.
