### ISSUE TITLE
[Bug]: no scrollbar, headelss false

### ISSUE THREAD

**Issue by t1a2l** [puppeteer/puppeteer#8910]
### Bug description

Steps to reproduce the problem:

testing with puppeteer and mocha 

const opts = {
    headless: false,
    slowMo: 100,
    timeout: 10000,
    args: ['--disable-web-security']
}

browser = await puppeteer.launch(opts);
page = await browser.newPage();

page does not have scrollbar at all.

cant scroll using the mouse.

browser that is opening is chromium. 

if i open another tab i see a scrollbar.

only the controlled tab does not have a scrollbar. and cannt be scrolled.

### Puppeteer version

13.1.0

### Node.js version

v12.22.10

### npm version

8.10.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Could you please try using the latest version of Puppeteer? Also, could you please clarify what you mean by the absent scrollbar? the empty page that is opened by default might not have enough content to show a scrollbar.

**Comment by kashif-ghafoor** [comment]
Have you tried setting defaultViewport: null. It worked for me.
