### ISSUE TITLE
How to select the current element using `$eval` and/or `$$eval`?

### ISSUE THREAD

**Issue by Qlub53** [puppeteer/puppeteer#8913]
I know I can do this by [$()](https://github.com/puppeteer/puppeteer/blob/v16.2.0/docs/api/puppeteer.elementhandle._.md) and [$$()](https://github.com/puppeteer/puppeteer/blob/v16.2.0/docs/api/puppeteer.elementhandle.__.md). But do I have to specify something other than the current element as the `selector` parameter of [$eval()](https://github.com/puppeteer/puppeteer/blob/v16.2.0/docs/api/puppeteer.elementhandle._eval.md) and [$$eval()](https://github.com/puppeteer/puppeteer/blob/v16.2.0/docs/api/puppeteer.elementhandle.__eval.md)?
I haven't found the _css selector_ that represents current element.

It'd be great if puppeteer could provide a workaround.
For example, making `selector` optional and thus selecting the current element by default.
```ts
tweetHandle.$eval(node => node.innerText);
```

**Comment by Qlub53** [comment]
Is it by design that
```ts
tweetHandle.$eval('selector', node => node.innerText);
```
is the combination of
```ts
tweetHandle.$('selector');
```
and
```ts
tweetHandle.evaluate(node => node.innerText);
```
?

**Comment by OrKoN** [comment]
yes, $eval is a shortcut for that that also disposes the intermediate element handle
