### ISSUE TITLE
[Bug]: pdf link error

### ISSUE THREAD

**Issue by jiawei397** [puppeteer/puppeteer#8918]
### Bug description

Recently, I used puppeteer to generate PDF files, but I found a bug. 
The phenomenon is that when there are two links, the second link will wrap. At this time, the display of the first link will also become the second, and there will be errors when clicking.
The following is the reproduced code.
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  // The following `here way` text breaks, and the generated bb.pdf is problematic
  await page.setContent(`Most things that you can do manually in the browser can be done using Puppeteer!<a href="https://example.com/aa.html">here</a>, and <a href="https://example.com/bb.html">here way</a>.`,
  );
  await page.pdf({
    path: 'aa.pdf',
    printBackground: true,
    format: 'a4',
    margin: {
      top: '20mm',
      right: '20mm',
      bottom: '20mm',
      left: '20mm',
    },
  });

  // Add a few words and squeeze `here way` to the next line, which is no problem
  await page.setContent(`Most things that you can do manually in the browser can be done using Puppeteer!<a href="https://example.com/aa.html">here</a>, and this is <a href="https://example.com/bb.html">here way</a>.`,
  );
  await page.pdf({
    path: 'bb.pdf',
    printBackground: true,
    format: 'a4',
    margin: {
      top: '20mm',
      right: '20mm',
      bottom: '20mm',
      left: '20mm',
    },
  })

  await browser.close();
})();
```

The following is the link display when moving to PDF:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/19886374/189046980-6774bfe3-d4c8-4978-90ad-8e641109f640.png">

<img width="988" alt="image" src="https://user-images.githubusercontent.com/19886374/189047028-f30563f3-4d3e-4d97-beea-c20052169c9f.png">

This is a very strange thing. I hope I can get help. Thanks!

### Puppeteer version

17.1.2 and 16.1.0

### Node.js version

16.16.0

### npm version

8.11.0

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by OrKoN** [comment]
Does it happen with the regular print(save to pdf) dialog in the headful mode?

**Comment by jiawei397** [comment]
> Does it happen with the regular print(save to pdf) dialog in the headful mode?

Thank you for your reply. It's a sad thing. When I export my web page with chrome and safari, it's the same.
Is this a browser problem or a PDF problem?

**Comment by OrKoN** [comment]
I am not sure but if the issue happens with the regular Chrome print dialog, the best way is to file an issue to crbug.com

**Comment by jiawei397** [comment]
OK. I get it. 
By the way, https://bugs.chromium.org/ Is it one with crbug.com?

**Comment by OrKoN** [comment]
yes, it's the same website: specifically https://bugs.chromium.org/p/chromium/issues

**Comment by jiawei397** [comment]
Thanks. I'm going to mention this issue. 
However, just now I came up with a solution to my business bug. Just add a style ` word-break: keep-all` to my `<a>` tag to force it to wrap lines, although it is not elegant enough.
