### ISSUE TITLE
[Bug]: Can't use `puppeteer-core` anymore due to error `_projectRoot is undefined. Unable to create a BrowserFetcher`

### ISSUE THREAD

**Issue by christian-bromann** [puppeteer/puppeteer#8919]
### Bug description

I am using Puppeteer within WebdriverIO to run commands through DevTools. Unfortunately it is not possible anymore to use `puppeteer-core` only as utility to launch browser (chrome and firefox). However [the docs](https://pptr.dev/#puppeteer-core) clearly suggest that this is still possible:

> When using puppeteer-core, remember to change the include line:
> 
> const puppeteer = require('puppeteer-core');
> 
> You will then need to call [puppeteer.connect](https://pptr.dev/api/puppeteer.puppeteer.connect) or [puppeteer.launch](https://pptr.dev/api/puppeteer.puppeteernode.launch) with an explicit executablePath or channel option.

Steps to reproduce the problem:

1. Create a new folder, e.g. `cd /tmp && mkdir pptrtest && cd pptrtest`
2. Install `puppeteer-core` via `npm i puppeteer-core`
3. Create the following script:

```js
const puppeteer = require('puppeteer-core');

(async () => {
    const pathToExtension = require('path').join(__dirname, 'my-extension');
    const browser = await puppeteer.launch({
        product: 'firefox',
        executablePath: '/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin',
        headless: true,
        defaultViewport: {
            width: 1200,
            height: 900
        }
    });
    await page.goto('https://webdriver.io');
    console.log(await page.title());
    // Test the background page as you would any other page.
    await browser.close();
})();
```

4. Run via `node test.js`

### Puppeteer version

latest

### Node.js version

18.6.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
/private/tmp/pptrcore/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:125
                throw new Error('_projectRoot is undefined. Unable to create a BrowserFetcher.');
                      ^

Error: _projectRoot is undefined. Unable to create a BrowserFetcher.
    at FirefoxLauncher._updateRevision (/private/tmp/pptrcore/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:125:23)
    at FirefoxLauncher.launch (/private/tmp/pptrcore/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:70:20)
    at async /private/tmp/pptrcore/test.js:5:21
```

**Comment by christian-bromann** [comment]
The bug got recently introduced with https://github.com/puppeteer/puppeteer/issues/8919

**Comment by christian-bromann** [comment]
Thanks for the quick fix!

**Comment by clarkmcc** [comment]
I'm still seeing this issue when running on fly.io.

```
2022-09-13T21:40:07.751 app[ad36132e] sea [info] Browser creation: Error: _projectRoot is undefined. Unable to create a BrowserFetcher.
2022-09-13T21:40:07.751 app[ad36132e] sea [info] at resolveExecutablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:128:15)
2022-09-13T21:40:07.751 app[ad36132e] sea [info] at ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:68:100)
2022-09-13T21:40:07.751 app[ad36132e] sea [info] at async logIn (/workspace/ivie.js:11:19)
2022-09-13T21:40:07.751 app[ad36132e] sea [info] at async /workspace/index.js:216:28
```

Here's the Dockerfile
```dockerfile
FROM node:slim
RUN apt-get update \
  && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install google-chrome-stable -y --no-install-recommends \
  && apt-get remove google-chrome-stable -y \
COPY *.json ./
RUN npm install --frozen-lockfile
COPY . ./
CMD node index.js
```

And launching puppeteer
```javascript
const browser = await puppeteer.launch({
	headless: true,
	args: [
		// Required for Docker version of Puppeteer
		'--no-sandbox',
		'--disable-setuid-sandbox',
		// This will write shared memory files into /tmp instead of /dev/shm,
		// because Docker’s default for /dev/shm is 64MB
		'--disable-dev-shm-usage',
	]
});
```

And package.json version
```
"puppeteer-core": "^17.1.3"
```

**Comment by OrKoN** [comment]
@clarkmcc I believe you are missing the executablePath or channel when using puppeteer-core: [`You will then need to call [puppeteer.connect](https://pptr.dev/api/puppeteer.puppeteer.connect) or [puppeteer.launch](https://pptr.dev/api/puppeteer.puppeteernode.launch) with an explicit executablePath or channel option.`](https://pptr.dev/#puppeteer-core:~:text=You%20will%20then%20need%20to%20call%20puppeteer.connect%20or%20puppeteer.launch%20with%20an%20explicit%20executablePath%20or%20channel%20option.)

**Comment by clarkmcc** [comment]
> @clarkmcc I believe you are missing the executablePath or channel when using puppeteer-core: [`You will then need to call [puppeteer.connect](https://pptr.dev/api/puppeteer.puppeteer.connect) or [puppeteer.launch](https://pptr.dev/api/puppeteer.puppeteernode.launch) with an explicit executablePath or channel option.`](https://pptr.dev/#puppeteer-core:~:text=You%20will%20then%20need%20to%20call%20puppeteer.connect%20or%20puppeteer.launch%20with%20an%20explicit%20executablePath%20or%20channel%20option.)

Same issue with the [env variable](https://www.npmjs.com/package/puppeteer-core)
```javascript
const browser = await puppeteer.launch({
	executablePath: process.env.PUPPETEER_EXECUTABLE_PATH,
	headless: true,
	args: [
		// Required for Docker version of Puppeteer
		'--no-sandbox',
		'--disable-setuid-sandbox',
		// This will write shared memory files into /tmp instead of /dev/shm,
		// because Docker’s default for /dev/shm is 64MB
		'--disable-dev-shm-usage',
	]
});
```

**Comment by OrKoN** [comment]
@clarkmcc what is the value of `PUPPETEER_EXECUTABLE_PATH` that you set?

**Comment by clarkmcc** [comment]
@OrKoN, apparently it's undefined. I thought it was provided by the Docker image I was using. Sorry for the false alarm, I'll keep noodling on the env variable/Docker image side of things.
