### ISSUE TITLE
Add `addStyleTag(url)` API

### ISSUE THREAD

**Issue by SamVerschueren** [puppeteer/puppeteer#892]
Puppeteer has a [`addScriptTag(url)`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageaddscripttagurl) method, it would be nice to have a `addStyleTag(url)` as well to easily add external styles.

// @kevva @sindresorhus

**Comment by aslushnikov** [comment]
Sounds reasonable. This is easy to implement similarly to `addScriptTag` [implemention](https://github.com/GoogleChrome/puppeteer/blob/215b3497c755cfe77d0a264535cf9d4c516002c2/lib/FrameManager.js#L346).

I'd appreciate if someone sends a PR for this (with a test and documentation).

**Comment by SamVerschueren** [comment]
Thanks for pointing to that location. Would like to take this one :).

**Comment by SamVerschueren** [comment]
Added a PR!
