### ISSUE TITLE
[Bug]: chrome in puppeteer can't play video

### ISSUE THREAD

**Issue by libofei2004** [puppeteer/puppeteer#8924]
### Bug description

Steps to reproduce the problem:
 I use puppeteer with "headless: false" mode to visit a page with video, the url is https://tv.cctv.com/2020/02/06/VIDEQdsZLhKCkQSAhAqG9wQG200206.shtml,
but after the page has loaded, the video can't play.
![image](https://user-images.githubusercontent.com/10001548/189119728-e6f89a5d-cb30-4c88-a726-6b86e09e5cab.png)

My code is as follows:
var browers = await puppeteer.launch({
         //headless: headless,
       headless: false,
      defaultViewport: {width: 1440, height: 800}
  });
...

### Puppeteer version

12.0.0

### Node.js version

16.13.0

### npm version

8.1

### What operating system are you seeing the problem on?

Windows

**Comment by libofei2004** [comment]
@OrKoN I use v17.1.3 to play video but still failed. The page url is https://mp.weixin.qq.com/s/WGFSzJ0IDZmzRaV5qE_-jQ

![image](https://user-images.githubusercontent.com/10001548/190648277-1fd55756-e6a2-49b0-b4f3-1c3e4a9fe2f4.png)

**Comment by OrKoN** [comment]
@libofei2004 I am able to reproduce. But I think there is not much we can do: the Chromium binary might not have all codecs required to play a video. I see that the same happens with YouTube https://stackoverflow.com/questions/60307750/puppeteer-unable-to-play-video so I think this site as well as YouTube require some proprietary codecs that only exist in the Chrome binary. You can provide a custom executable path to a Chrome binary to have it working.

**Comment by libofei2004** [comment]
@OrKoN Thank you, I'll try to use Chrome to solve it.

**Comment by libofei2004** [comment]
@OrKoN I use ' let videos =  await page.$$eval('video', eles=>eles.map(ele=>ele.src)) ' to get video src in the page is aslo failed, the length of videos is 0, Is it caused by the same reason?

**Comment by OrKoN** [comment]
@libofei2004 I believe the page might be removing the video tag from the page if the playback failed

**Comment by libofei2004** [comment]
@OrKoN I think you are right.

**Comment by libofei2004** [comment]
@OrKoN I think you are right.
