### ISSUE TITLE
Get data attribute contains selector

### ISSUE THREAD

**Issue by llllOllOOll** [puppeteer/puppeteer#8935]
All queries work perfectly, except select queries using data-*.
All queries work perfectly, except select queries using data-*.

All attached queries work perfectly when run directly in the browser console, but return undefined when run with Puppeteer.

ex: See on the line 18, it return undefined.
![image](https://user-images.githubusercontent.com/49413017/189399444-66ea0806-76a8-45c2-89d6-14a77308cd4b.png)

![image](https://user-images.githubusercontent.com/49413017/189399527-054eb4ec-cf5b-4d3f-969a-8eea6018b875.png)

**Comment by 7b3tech** [comment]
Solved!
