### ISSUE TITLE
[Bug]: Puppeteer keeps crashing

### ISSUE THREAD

**Issue by kieranoreilly** [puppeteer/puppeteer#8937]
### Bug description

Steps to reproduce the problem:

1. Run npm install
2. Run npm start
3. Only occurs on my mac book, but not on my other computer

### Puppeteer version

17.1.3

### Node.js version

16.0.0

### npm version

7.10.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
/path/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:285
            return Promise.reject(new Error(`Protocol error (${method}): Session closed. Most likely the ${__classPrivateFieldGet(this, _CDPSession_targetType, "f")} has been closed.`));
                                  ^

Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.
    at CDPSession.send (/path/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:285:35)
    at next (/path/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSession.send (/path/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at Page._Page_screenshotTask (/path/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2634:59)
    at /path/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2006:93
```

**Comment by OrKoN** [comment]
Is you macbook using M1 (or arm64) processor?

**Comment by sahdbashkdbj** [comment]
Any update with this bug ?

**Comment by OrKoN** [comment]
@sahdbashkdbj I am not sure it's the bug, very likely the binary is for the wrong platform architecture. Waiting for the reporter to provide the details about their macbook and a repro.

**Comment by ad-on-is** [comment]
I'm experiencing this same issue on a google cloud run instance.

**Comment by lutzklai** [comment]
I ran into this issue on my AWS lambda. This error would happen sometimes when I tried to take a screenshot. I couldn't figure out why it worked most of the time but threw this error for certain scenarios.

I was on a node16 lambda & using the @sparticuz/chromium@109.0.0 & puppeteer@19.4 packages.

I ended up downgrading the lambda node version to 14 and things seem to be working so far.

**Comment by d3ric3** [comment]
Hi, I'm experiencing this same issue on MacBook Air M2

**Comment by Abhishek-Nebel** [comment]
@d3ric3 
Did you find something for it? Any work around, I'm facing the same issue on my mac m2

**Comment by d3ric3** [comment]
@Abhishek-Nebel updating the puppeteer npm package to version 22.5.0 help to reduce the crash issue on my M2. I notice there is a latest version 22.12.1. You may try switching between the puppeteer npm package version. At the moment I am only using my program at Windows 11 and Ubuntu, working fine at these OS.
