### ISSUE TITLE
[Bug]: SyntaxError: The requested module 'puppeteer' does not provide an export named 'ElementHandle'

### ISSUE THREAD

**Issue by Qlub53** [puppeteer/puppeteer#8938]
### Bug description

Steps to reproduce the problem:

1. source code

**app.ts**
```ts
import { ElementHandle, Page } from 'puppeteer';

class CustomElement {
	print(): void {
		console.log(`${Page.name} ${ElementHandle.name}`);
	}
}

const elem = new CustomElement();
elem.print();
```
**package.json**
```json
{
	"module": "./app.js",
	"types": "./app.d.ts",
	"type": "module",
	"dependencies": {
		"puppeteer": "^16.2.0",
		"ts-node": "^10.9.1",
		"typescript": "^4.7.4"
	}
}
```
**tsconfig.json**
```json
{
	"compilerOptions": {
		"declaration": true,
		"declarationMap": true,
		"sourceMap": true,
		"moduleResolution": "node",
		"module": "ESNext",
		"target": "ESNext",
		"lib": [
			"ESNext",
			"DOM",
		],
		"allowSyntheticDefaultImports": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"esModuleInterop": true,
	},
	"exclude": [ "node_modules" ],
}
```

2. run the program
`$(npm bin)/ts-node --esm app.ts`
or
`node --loader ts-node/esm app.ts`
 

### Puppeteer version

16.2.0

### Node.js version

16.8.0

### npm version

7.14.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
user@MacBook-Pro app % $(npm bin)/ts-node --esm app.ts

file://app.ts:1
import { ElementHandle, Page } from 'puppeteer';
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'puppeteer' does not provide an export named 'ElementHandle'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

**Comment by Qlub53** [comment]
Either workaround below
```ts
import puppeteer from 'puppeteer';

class CustomElement {
	print(): void {
		console.log(`${puppeteer.Page.name} ${puppeteer.ElementHandle.name}`);
	}
}
```
```ts
import puppeteer from 'puppeteer';
const { ElementHandle, Page } = puppeteer;

class CustomElement {
	print(): void {
		console.log(`${Page.name} ${ElementHandle.name}`);
	}
}
```
_(2nd workaround inspired by https://stackoverflow.com/a/47277956)_

will solve these particular errors:
`SyntaxError: The requested module 'puppeteer' does not provide an export named 'ElementHandle'`
`SyntaxError: The requested module 'puppeteer' does not provide an export named 'Page'`

but will introduce another error:
```
                console.log(`${Page.name} ${ElementHandle.name}`);
                      ^
TypeError: Cannot read property 'name' of undefined
```

**Comment by Qlub53** [comment]
Either workaround below
```ts
import puppeteer from 'puppeteer';

class CustomElement {
	print(): void {
		console.log(`${puppeteer.Page.name} ${puppeteer.ElementHandle.name}`);
	}
}
```
```ts
import puppeteer from 'puppeteer';
const { ElementHandle, Page } = puppeteer;

class CustomElement {
	print(): void {
		console.log(`${Page.name} ${ElementHandle.name}`);
	}
}
```
_(2nd workaround inspired by https://stackoverflow.com/a/47277956)_

will solve these particular errors:
`SyntaxError: The requested module 'puppeteer' does not provide an export named 'ElementHandle'`
`SyntaxError: The requested module 'puppeteer' does not provide an export named 'Page'`

but will introduce another error:
```
                console.log(`${Page.name} ${ElementHandle.name}`);
                      ^
TypeError: Cannot read property 'name' of undefined
```

**Comment by Qlub53** [comment]
Similarly,
```ts
import { ElementHandle, Page } from 'puppeteer';

class CustomElement {
	verify(obj: any): boolean {
		return obj instanceof Page || obj instanceof ElementHandle;
	}
}

const elem = new CustomElement();
elem.verify({});
```
leads to 
`SyntaxError: The requested module 'puppeteer' does not provide an export named 'ElementHandle'`
and
`SyntaxError: The requested module 'puppeteer' does not provide an export named 'Page'`

which may only be surppressed by either
```ts
		return obj instanceof puppeteer.Page || obj instanceof puppeteer.ElementHandle;
```
or
```ts
import puppeteer from 'puppeteer';
const { ElementHandle, Page } = puppeteer;
```

but will end up with a new error:
```
TypeError: Right-hand side of 'instanceof' is not an object
```

**Comment by OrKoN** [comment]
I don't think we export those classes. We only export types for them. You can implement duck-typing currently but not the instanceof checks, e.g., 

```
class CustomElement {
	verify(obj: puppeteer.Page|puppeteer.ElementHandle): boolean {
		if ('goto' in obj) { // likely a Page
		   return true;
                 }
                 if ('click' in obj) { // likely an ElementHandle
                    return true;
                 }
                 return false;
	}
}
```

**Comment by Qlub53** [comment]
Thank you very much @OrKoN  
But as to what you mentioned:
> I don't think we export those classes. We only export types for them.

I think I'm quite confused by the source code:

- Both [ElementHandle.ts](https://github.com/puppeteer/puppeteer/blob/21cc961df9bba14a06c07e6c8e60744add4b8ee3/src/common/ElementHandle.ts#L71) and [Page.ts](https://github.com/puppeteer/puppeteer/blob/21cc961df9bba14a06c07e6c8e60744add4b8ee3/src/common/Page.ts#L446) are exporting `class`es instead of `type`s, i.e.
	`export class ElementHandle` and `export class Page`

- **types.ts** also says it exports everything from [ElementHandle](https://github.com/puppeteer/puppeteer/blob/6fd05d963ef6c08c07b5b61ab21dfeef88fc8ac8/src/types.ts#L16) and [Page](https://github.com/puppeteer/puppeteer/blob/6fd05d963ef6c08c07b5b61ab21dfeef88fc8ac8/src/types.ts#L35)

Not sure what I'm missing here.

**Comment by OrKoN** [comment]
@Qlub53 the entry point is https://github.com/puppeteer/puppeteer/blob/main/src/puppeteer.ts#L39 where you can see what is exported by the module. I believe you use a deep import you might be able to import ElementHandle.js or Page.js directly but it's not part of the default export. `types.ts` is not used for the module entrypoint and, thus, only provides type information.

**Comment by Qlub53** [comment]
Thank you @OrKoN for the insight.
Would you mind sharing links to where `ElementHandle` and `Page` are exported as types, too?

**Comment by OrKoN** [comment]
See types.d.ts in the build output. tsc generates the .d.ts file based on types.ts.

**Comment by Qlub53** [comment]
Therefore, after all, 
- I can only use `ElementHandle` and `Page` as `type`s to facilitate type checking at compile time, 
- but cannot access their `class` information, e.g. `ElementHandle.name`, at any time

Please feel free to correct me if you find any mistakes.

**Comment by pecampelo** [comment]
I have made use of the Page and ElementHandle types for type assertion with TS and JSDoc, and can attest that the class instantiation for both is not accessible outside the puppeteer object, due to it being glued to a Browser instance.
