### ISSUE TITLE
Does waitForFunction support async function

### ISSUE THREAD

**Issue by popomore** [puppeteer/puppeteer#895]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: MacOS
* URLs (if applicable):

**What steps will reproduce the problem?**

I want to wait an async code, for example

```js
await page.waitForFunction(async () => {
  await new Promise(resolve => setTimeout(resolve, 1000));
});
```

**What is the expected result?**

It should wait until the function return true;

**What happens instead?**

it doesn't.

**Comment by aslushnikov** [comment]
It shouldn't. You can use `page.evaluate` for this.

```js
await page.waitForFunction(async () => {
  await new Promise(resolve => setTimeout(resolve, 1000));
});
```

**Comment by cloydlau** [comment]
Both evaluate and waitForFunction throw the same error when using ```async```:
```js
 Evaluation failed: ReferenceError: tslib_1 is not defined

      at __puppeteer_evaluation_script__:1:16
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/src/common/Executi
onContext.ts:273:13)
      at ExecutionContext.evaluate (node_modules/puppeteer/src/common/ExecutionContext
.ts:138:12)

```
