### ISSUE TITLE
Images overflow to next page in PDF export in screen mode

### ISSUE THREAD

**Issue by astefanutti** [puppeteer/puppeteer#896]
Environment:

* Puppeteer version: 0.11.0
* Platform / OS version: Mac OS X

While running the following script:

```
const puppeteer = require('puppeteer');

(async () => {
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.emulateMedia('screen');
await page.setViewport({
    width: 1024,
    height: 768,
 });
await page.goto('file:///test.html', {waitUntil: 'load'});
await page.screenshot({
    path           : 'test.png',
    fullPage       : false,
});
await page.pdf({
  path: 'test.pdf',
  width: '1024px',
  height: '768px',
});
await browser.close();
})();
```

With the following page:

```
<html style="height: 100%;">
    <body style="height: 100%; overflow: hidden;">
    <div style="position: absolute; top: 500px; border-style: dotted">
         <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1024px-Google_2015_logo.svg.png">
     </div>
    </body>
</html>
```

The image gets printed in a second page in the PDF: [test.pdf](https://github.com/GoogleChrome/puppeteer/files/1340334/test.pdf)

While it is should be positioned in the first page as per the screenshot: ![test](https://user-images.githubusercontent.com/366207/30960078-3c523418-a442-11e7-817a-8ab8dd32df4a.png)

**Comment by theevilhead** [comment]
Hi @astefanutti  its the problem of your html page.. you have absolute positioned it to top : 500px which makes it to be pushed down and thus looks like its in the next page. change you html file to top : 0px and it works.
Hope that helps

**Comment by astefanutti** [comment]
@girishpatil the thing is that it renders as expected when exporting as PNG, while it renders incorrectly when exporting as PDF.

**Comment by sinedied** [comment]
I'm also experiencing something similar: the image is being pushed to the next page when it's in an absolutely positioned layer, instead of being cropped up as it should by the css rules.

**Comment by Jmille65** [comment]
I think this is from Chromium 774970: [Headless Print to PDF - entire image clipped when it overflows page](https://bugs.chromium.org/p/chromium/issues/detail?id=774970&q=pdf%20image&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).
