### ISSUE TITLE
[Bug]: Website incorrectly breaks out of the viewport using iPhone 5 device emulation 

### ISSUE THREAD

**Issue by andywaite** [puppeteer/puppeteer#8966]
### Bug description

Steps to reproduce the problem:

```
    const browser = await puppeteer.launch({
      headless: false
    })
    const page = await browser.newPage()
    await page.emulate(devices['iPhone 5'])
    await page.goto('https://main--darling-sprinkles-f403fa.netlify.app/')
    await page.waitForSelector('body')
    await page.close()
```

With most sites, this code will render the site roughly equivalent to the device emulator in Chrome developer tools. Here are a couple of sites that work as expected:

BBC news in dev tools:
<img width="522" alt="Screenshot 2022-09-15 at 21 15 49" src="https://user-images.githubusercontent.com/6773151/190501538-cef1af9e-dbcc-4001-8e4e-ce224e0d84fa.png">

BBC news in Puppeteer:
<img width="1203" alt="Screenshot 2022-09-15 at 21 08 41" src="https://user-images.githubusercontent.com/6773151/190501562-004dd7af-1268-403e-89b9-5dbe28d4ccc6.png">

http://www.taylorganson.com/ in dev tools:
<img width="531" alt="Screenshot 2022-09-15 at 21 15 08" src="https://user-images.githubusercontent.com/6773151/190501638-ff32e0cf-5af9-4225-8ee9-f482c41fb2c2.png">

http://www.taylorganson.com/ in Puppeteer:
<img width="1205" alt="Screenshot 2022-09-15 at 21 14 35" src="https://user-images.githubusercontent.com/6773151/190501741-b037f85f-c3dd-4c72-b1fc-a39dc87b9a31.png">

However, for the website https://main--darling-sprinkles-f403fa.netlify.app - while dev tools renders it correctly:
<img width="504" alt="Screenshot 2022-09-15 at 20 47 04" src="https://user-images.githubusercontent.com/6773151/190501274-2128c7e8-bf55-4d38-8c85-2ed4c2b2c6d1.png">

With Puppeteer it breaks out of the viewport:
<img width="1200" alt="Screenshot 2022-09-15 at 21 08 08" src="https://user-images.githubusercontent.com/6773151/190501335-c96f9fc5-3f60-4809-b4f0-3a80f0231c19.png">

### Puppeteer version

17.1.3

### Node.js version

v16.13.1

### npm version

8.1.2

### What operating system are you seeing the problem on?

Linux, macOS

**Comment by gamersindo1223** [comment]
Any error?

**Comment by OrKoN** [comment]
I don't think there is a bug here: Puppeteer emulation just does not hide what's rendered outside of viewport. In DevTools, the emulation frame hides that. If you do:

```
  console.log(await page.evaluate(() => {
    return {
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
    }
  }));
  console.log(puppeteer.devices['iPhone 5'])
  ```
  
  you will see that the values are the same as set by the emulation. The difference compared with other websites is that the website does not adapt properly to the emulated viewport size.
