### ISSUE TITLE
Archive the websites for the previous versions of Puppeteer

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#8969]
Currently, we only generate the website for the latest + next versions of Puppeteer because docusaurus is slow when it needs to generate many versions: https://github.com/facebook/docusaurus/discussions/3132#discussioncomment-3517711

Instead we need to find a way to archive a website version without re-building it. Currently, we only link to the markdown documentation for the old versions that is not so great.

**Comment by sttrutsa185** [comment]
- [ ]
