### ISSUE TITLE
No browser websocket endpoint in /json/version?

### ISSUE THREAD

**Issue by IanChen83** [puppeteer/puppeteer#897]
I want to use `puppeteer.connect` function to connect to an opened headless chrome (a system-wise one, not the one downloaded with puppeteer). However, there is no `webSocketDebuggerUrl` entry in `http://${host}:${port}/json/version`, as the [doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserwsendpoint) says.

Does this entry only exist when using a specific version of chrome?

This is what I got in `/json/version/`

````
{
   "Browser": "HeadlessChrome/61.0.3163.100",
   "Protocol-Version": "1.2",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/61.0.3163.100 Safari/537.36",
   "V8-Version": "6.1.534.41",
   "WebKit-Version": "537.36 (@57c9d07b416b5a2ea23d28247300e4af36329bdc)"
}
````

**Comment by paulirish** [comment]
This was added a little bit ago so I don't believe its in Chrome 61. It's likely there in Chrome 62, though.
