### ISSUE TITLE
> Please see https://pptr.dev/troubleshooting#running-on-alpine (happy to review a PR to update the troubleshoot doc if some instructions can be updated).

### ISSUE THREAD

**Issue by ShnAlmighty** [puppeteer/puppeteer#8974]
> Please see https://pptr.dev/troubleshooting#running-on-alpine (happy to review a PR to update the troubleshoot doc if some instructions can be updated).

I integrated the changes in my Dockerfile but I am still getting `504 Gateway Time-out` error in my API response.

Also, the image I am using in Dockerfile is `node:14.16.1-alpine`.

I have tried changing the nginx config file also to allow more processing time for the API before sending response and also made the changes in the express app for the same but still getting the same error. 

The API works by scrapping 30 pages and then sending back relevant data. Locally it is working fine but for some reason when using in Docker container, it is failing in the first page only after scrapping just 4 data sets.

_Originally posted by @ShnAlmighty in https://github.com/puppeteer/puppeteer/issues/8964#issuecomment-1249200810_

**Comment by OrKoN** [comment]
`504 Gateway Time-out` is a server-sent error so not related to Puppeteer. Perhaps you are sending to many requests and the API goes down.

**Comment by ShnAlmighty** [comment]
@OrKoN The API is not receiving to many requests and the nginx configured also has a timeout of more than one minute which is the time after which Puppeteer stops scrapping and stops abruptly due to which the API sends back this response.
