### ISSUE TITLE
chromium can not download files when click download link

### ISSUE THREAD

**Issue by libofei2004** [puppeteer/puppeteer#8976]
### Bug description

I want to use await page.$$eval('a', (eles) =>eles.map(ele=>{  ele.click();}));to download files from page http://www.geodoi.ac.cn/WebCn/down.aspx?fileID=8046&size=252567
but failed, even if I use mouse to click the  download link directly. The  chromium  version is 106.0.5249.0,The  chromium  shows:
![image](https://user-images.githubusercontent.com/10001548/190971848-e51add37-08c2-4e13-ac8f-65fc508305c4.png)
It means there is a little problem in downloading.

### Puppeteer version

17.1.3

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Please provide a complete script to reproduce the issue. Also, take a look at the existing issues that could be related https://github.com/puppeteer/puppeteer/issues/8010

**Comment by libofei2004** [comment]
@OrKoN From issues/8010  I find the reason, my downloadPath is wrong, I set it in relative path, but It seems to only support a absolute path.I change it into absolute path and fix it.Thanks.
