### ISSUE TITLE
Windows binaries broken

### ISSUE THREAD

**Issue by canonic-epicure** [puppeteer/puppeteer#899]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11
* Platform / OS version: Windows 7, Windows 10

**What steps will reproduce the problem?**

1. Install puppeteer from npm
2. Go to the chromium installation directory: node_modules/puppeteer/.local-chromium/win32-499413/chrome-win32
3. Launch chrome.exe
4. Enter some url in the browser address area

**What is the expected result?**
The web page of that url should open.

**What happens instead?**
The content area of the chromium browser remains empty. Same website opens fine in IE:
![rootcause_step_7](https://user-images.githubusercontent.com/72431/30969454-1ada48f6-a46b-11e7-9e2c-d18c7d2be258.jpg)

**Comment by canonic-epicure** [comment]
Basically 0.11 completely does not work on Windows for me (Linux is fine)..

**Comment by aslushnikov** [comment]
0.12 seems to be fine.
