### ISSUE TITLE
[Bug]: click in a loop is not  correctly excuted

### ISSUE THREAD

**Issue by libofei2004** [puppeteer/puppeteer#8990]
### Bug description

I want to use 'click' to download files automatically, my code is as follows:
 await page.$$eval('a', (eles) => {
            eles.forEach(ele=>{
                let url = ele["href"];
                if( url&&url.toLowerCase().includes("download")){
                    ele.click();
                }
            })
        });
But when it is running in a page which has more than one download links, it always only downloads the last file, I don't
know why? My test page is http://www.geodoi.ac.cn/WebCn/doi.aspx?Id=3131
![image](https://user-images.githubusercontent.com/10001548/191262278-aa5615b0-4e9b-4b38-98de-70bed85ac56c.png)

### Puppeteer version

17.1.3

### Node.js version

16.13.0

### npm version

8.1.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
You are probable clicking too fast and one download is cancelled by the next click.

**Comment by libofei2004** [comment]
@OrKoN Thank you，I fixed it with setTimeout().
