### ISSUE TITLE
Firefox: overridePermissions issue

### ISSUE THREAD

**Issue by Neformaln** [puppeteer/puppeteer#8995]
### Bug description

It was tested on:
MacOS 12.2.1
Ubuntu 20.04.2 LTS
Puppeteer version 10.2.0
We also tried to check this on **puppeteer v.18.0.4** and it didn't help us. The errors still appear.

Hi all! We have an implementation of test scenario on Puppeteer for Chrome browser. We are  currently trying to implement it on Firefox. 
I installed an additional package for Firefox context using this command on the terminal:
`PUPPETEER_PRODUCT=firefox node install.js`
Also I added `product: firefox` to `puppeteer.launch` arguments. After that I tried to run the code to check if everything ok. 

Code looks like:    
```js
let browser = await puppeteer.launch({
        product: 'firefox',
        headless: false,
        defaultViewport: null,
    });
```

 ```js
   let context = await browser.defaultBrowserContext();
    return context.overridePermissions("https://testing.com", ["microphone", "camera", "notifications"])
        .then(() => {
            return browser;
        } );
```
But I faced an issue with `overridePermissions` method.  When I try to run the code, I get the following message:

`Protocol error (Browser.grantPermissions): Browser.grantPermissions RemoteAgentError@chrome://remote/content/cdp/Error.jsm:31:5\nUnknownMethodError@chrome://remote/content/cdp/Error.jsm:114:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:100:13\nexecute@chrome://remote/content/cdp/sessions/Session.jsm:66:25\nonPacket@chrome://remote/content/cdp/CDPConnection.jsm:252:36\nonMessage@chrome://remote/content/server/WebSocketTransport.jsm:91:18\nhandleEvent@chrome://remote/content/server/WebSocketTransport.jsm:73:14\n`

Could you help us to fix this issues?

### Puppeteer version

10.2.0

### Node.js version

v16.15.1

### npm version

8.13.2

### What operating system are you seeing the problem on?

Linux, macOS

### Relevant log output

```shell
Protocol error (Browser.grantPermissions): Browser.grantPermissions RemoteAgentError@chrome://remote/content/cdp/Error.jsm:31:5\nUnknownMethodError@chrome://remote/content/cdp/Error.jsm:114:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:100:13\nexecute@chrome://remote/content/cdp/sessions/Session.jsm:66:25\nonPacket@chrome://remote/content/cdp/CDPConnection.jsm:252:36\nonMessage@chrome://remote/content/server/WebSocketTransport.jsm:91:18\nhandleEvent@chrome://remote/content/server/WebSocketTransport.jsm:73:14\n
```

**Comment by jrandolf** [comment]
The error implies FireFox does not support `Browser.grantPermissions`. @whimboo may be able to provide more insight to this.

**Comment by whimboo** [comment]
Yes, our implementation doesn't support this API and it will also most likely not be implemented. I would propose to wontfix the issue.

You might want to wait until Puppeteer uses WebDriver BiDi and we have a WebDriver conformant API implemented.
