### ISSUE TITLE
[Bug]: '_projectRoot is undefined. Unable to create a BrowserFetcher.' ( v18.0.4 )

### ISSUE THREAD

**Issue by cenfun** [puppeteer/puppeteer#8999]
### Bug description

Steps to reproduce the problem:

```
const puppeteer = require('puppeteer-core');
const browserFetcher = puppeteer.createBrowserFetcher({
        path: 'to-my-path'
    });
```
throw a error:
node_modules\puppeteer-core\lib\cjs\puppeteer\node\Puppeteer.js:206
            throw new Error('_projectRoot is undefined. Unable to create a BrowserFetcher.');
                  ^
Error: _projectRoot is undefined. Unable to create a BrowserFetcher.

API createBrowserFetcher broken, it's works on previous version

### Puppeteer version

v18.0.4

### Node.js version

v16.17.0

### npm version

8.18.0

### What operating system are you seeing the problem on?

Windows

**Comment by jrandolf** [comment]
See https://github.com/puppeteer/puppeteer/issues/8919

**Comment by jtymes** [comment]
I am running into this issue. I am using puppeteer-core only to use its `BrowserFetcher` to download a known-good revision. As it stands right now, the change introduced in #8907 completely breaks the `createBrowserFetcher` functionality with puppeteer-core, because `_projectRoot` will always be undefined. I don't think #8919 offers a solution for that. 

One way to fix this could be if `path` is being passed in the `FetcherOptions`, it should skip the check on `_projectRoot`.

**Comment by jtymes** [comment]
We likely can switch to puppeteer, with a bit of additional configuration. It still leaves puppeteer-core with a broken `createBrowserFetcher` function that comes back as part of the `PuppeteerNode` class. If that's the intent, I think it should at least be documented.

**Comment by cenfun** [comment]
thanks @jrandolf 
Here's some background
Why puppeteer-core, because we don't want to download chromium when running "npm install", and the chromium size is very large (400M unzipped)
Why createBrowserFetcher, because we want to download chromium to a different directory like user directory but not node_modules, so it can be cached
So puppeteer-core + createBrowserFetcher can solve these usage scenarios very well, but it is broken now
However we can directly call BrowserFetcher to solve it
```js
//fix '_projectRoot is undefined. Unable to create a BrowserFetcher.'
const { BrowserFetcher } = require('puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js');
const createBrowserFetcher = (options) => {
    return new BrowserFetcher('', options);
};
```
It's just that BrowserFetcher is not a public API, we still hope to fix the public API createBrowserFetcher, thanks again.

**Comment by bm2ilabs** [comment]
Just remove node_modules/puppeteer-core/ if you are using puppeteer-extra
