### ISSUE TITLE
Implement POST navigation

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#9]
There's a need to navigate to URL with a `POST` method rather then `GET` method, e.g. to simulate form submission. 

For this, the `page.navigate()` method should accept `options` object with `method` parameter.

**Comment by JoelEinbinder** [comment]
It doesn't look like there is POST in the protocol. I can hack it in by creating a form inside of the page and submitting it, but it will be fragile.

**Comment by aslushnikov** [comment]
Would [request interception](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Request.js) possibly help you?

**Comment by JoelEinbinder** [comment]
Request interception works, but the patch isn't very pretty. See 6998b3302808e858eda9953c3831dbbbcc8f8bd5

Other options would be to inject a form into the page, or adding more options to navigate in the protocol.

**Comment by aslushnikov** [comment]
Closing this since there are no plans to implement this.
