### ISSUE TITLE
Provide reason for failed requests

### ISSUE THREAD

**Issue by ks07** [puppeteer/puppeteer#901]
The 'requestfailed' event is similar to PhantomJS' onResourceError event, but in Puppeteer the event handler receives only a Request object. There should be a way for a requestfailed handler to determine what the cause of the failure was - for example, a timeout vs an unresolvable hostname.

**Comment by Janpot** [comment]
Exactly! `Failed to navigate: <url>` isn't very useful. I mean, I already know what url I've put in.
I'd rather want to see something like `Failed to navigate: net::ERR_NAME_RESOLUTION_FAILED`. If possible with `net::ERR_NAME_RESOLUTION_FAILED` as a `.code` property of the error.

Edit: Hmm, seems like we're talking about different things. I meant the result from a failing `.goto(<url>)`. Sounds like a similar problem though.

**Comment by ks07** [comment]
@Janpot Yes different but closely related situations - it would also be very useful to have the error code set by `goto`!

**Comment by KristerV** [comment]
just to chime in. In my case the website has a `$.post()` request in it and it always fires the `requestfailed` event. Not error, pageerror or response.

`page.on('requestfailed', (a) => console.log('Failed:', a.url, a.response() ))`

There is no response. Can't find a way to figure out what's making the request fail.

edit: through `env DEBUG="*"` I found that the reason was `net::ERR_ABORTED`.

**Comment by vbakke** [comment]
Just a quick an dirty look at the callback:
```
Connection.js: _onMessage(message)
- message.params.errorText:"net::ERR_NAME_NOT_RESOLVED"
- message.method:"Network.loadingFailed"
- const object = JSON.parse(message);
- ...
- this.emit(object.method, object.params);

NetworkManager.js:  _onLoadingFailed(event)
- event.errorText:"net::ERR_NAME_NOT_RESOLVED"
- const request = this._requestIdToRequest.get(event.requestId);
- ...
- this.emit(NetworkManager.Events.RequestFailed, request);   //  <--- The 'event' is not passed on
```

Looks like the reason for the event, stops propagating in NetworkManager.js:  _onLoadingFailed(event).
