### ISSUE TITLE
Contributing: Can't push PR

### ISSUE THREAD

**Issue by pecampelo** [puppeteer/puppeteer#9012]
I have made some commits to a local branch and wanted to add a bit of extra documentation, keeping up with the conventional-commits and what not. I have generated SSH keys and added them to my SSH and GPG keys in Github, however, I have been receiving this message through the command line 

```
ERROR: Permission to puppeteer/puppeteer.git denied to pecampelo.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Looking at the GitHub website, it says that the [permission to add a PR should be given by the repo owner.](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-to-userrepo-denied-to-other-user) 

Is there anywhere I should open a request for write access? Looking to get some help in contributing here.

Pedro

**Comment by jrandolf** [comment]
You must create a fork and submit a PR across forks. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by pecampelo** [comment]
Ok, @jrandolf, thanks for the elucidation, i will be sure to get on it.
