### ISSUE TITLE
[Bug]: Intermittent Navigation issue : Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r856583 is guaranteed to work.

### ISSUE THREAD

**Issue by amrutha95** [puppeteer/puppeteer#9024]
### Bug description

We run puppeteer instances on an azure function to perform checks on progressive web apps and test if they have all the required components to be a high quality PWA (PWABuilder.com).

Intermittently, about a few times a day, we get logs with this error "Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r856583 is guaranteed to work." and the function errors out. The website "https://webboard.app" is an example of a site that faces this issue. 

I can't seem to find the right solution to this problem. It's very difficult to reproduce locally, but it is definitely a problem for us in production. 

### Puppeteer version

8.00

### Node.js version

14.19.1

### npm version

6.14.16

### What operating system are you seeing the problem on?

Linux

**Comment by jrandolf** [comment]
As much as you don't know the situation, we don't know more :) I suggest updating Puppeteer since your version is incredibly old.
