### ISSUE TITLE
[Bug]: Not all requests show up when using page.on

### ISSUE THREAD

**Issue by sabindev** [puppeteer/puppeteer#9026]
### Bug description

`Not all requests show up when using page.on, requests show up in network tab but not in console.

           const page = await browser.newPage()
            page.on('request', async (req) => {
                console.log(req.url())
            });
            await page.goto('https://www.twitch.tv/esl_csgo');
            await page.waitForTimeout(30000);`

### Puppeteer version

17.1.3

### Node.js version

18.1.0

### npm version

8.8.0

### What operating system are you seeing the problem on?

Windows

**Comment by sabindev** [comment]
update: this does not happen in playwright

**Comment by OrKoN** [comment]
Note enough information to reproduce: which requests are missing? DevTools shows many requests that might not come from the page. Also, please retry using the latest Puppeteer version as there have been changes.
