### ISSUE TITLE
[Bug]: EventBreakpoints not implemented.

### ISSUE THREAD

**Issue by Mohsen7s** [puppeteer/puppeteer#9031]
### Bug description

Acording to [https://chromedevtools.github.io/devtools-protocol/tot/EventBreakpoints/](https://chromedevtools.github.io/devtools-protocol/tot/EventBreakpoints/) we should be able to set breakpoint on events where they dong belong to DOM. But when you send a cdp command you will get  `EventBreakpoints.setInstrumentationBreakpoint' wasn't found` .
I have searched this repository github and didnt found anything about EventBreakpoints.

It could be the upstream devtools which throws error since I dont get error in typescript which could mean puppeteer and devtools/types are working as normal. 

Steps to reproduce the problem:

```
    var browser = await launch();
    var page = await browser.newPage();
    var cdp = await page.target().createCDPSession();

    var dbgId = (await cdp.send('Debugger.enable', {})).debuggerId;
    try {
        var res = await cdp.send('EventBreakpoints.setInstrumentationBreakpoint', { eventName: 'beforeBidderWorkletBiddingStart' });
    } catch (e) {
        console.log(e);
    }
    
```
### Puppeteer version

18.0.5

### Node.js version

16

### npm version

Any

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
C:\Users\Owner\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:329
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (EventBreakpoints.setInstrumentationBreakpoint): 'EventBreakpoints.setInstrumentationBreakpoint' wasn't found
    at C:\Users\Owner\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (C:\Users\Owner\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:325:16)
    at C:\Users\Owner\source\repos\NodejsConsoleApp2\NodejsConsoleApp2\app.js:101:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalMessage: "'EventBreakpoints.setInstrumentationBreakpoint' wasn't found"
}
```

**Comment by jrandolf** [comment]
It looks like `EventBreakpoints` was migrated to https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger/#method-setInstrumentationBreakpoint. Just replace `EventBreakpoints` with `DOMDebugger`
