### ISSUE TITLE
[Bug] Failed to launch the browser process! in the docker

### ISSUE THREAD

**Issue by Rafurus** [puppeteer/puppeteer#9034]
When using n8n docker and installing puppeteer as a community node (https://www.npmjs.com/package/n8n-nodes-puppeteer-extended) 

Error shows:
`Error: Failed to launch the browser process! spawn /home/node/.n8n/nodes/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/node/.n8n/nodes/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:286:20)
    at ChildProcess.<anonymous> (/home/node/.n8n/nodes/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:280:24)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

As far as i know from n8n community, installing Puppeteer in docker does not install all needed dependencies. 

Can you provide a solution for this?

**Comment by Juno-Wang** [comment]
I'm hitting the same problem in Jenkins running the snapshot test. Any idea of this?

**Comment by Jazeb** [comment]
see the error is ENOENT which means chrome executable file does not exist.
For that you can install chrome separately using
```
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
apt-get -y update && \
apt-get install -y \
google-chrome-stable && \
apt-get install -yqq unzip && \
wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip && \
unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
```
and in your code provide the chrome launch path as 
`/usr/local/bin/chrome` OR `/usr/local/bin/chrome-stable` not sure whichever is.

puppeteer will launch chrome from that path

**Comment by Rafurus** [comment]
@Jazeb 
After executing the code what you provided the only thing I have in /usr/local/bin is chromedriver.
On the other hand, I found it in the path /usr/bin/google-chrome and /usr/bin/google-chrome-stable so I tested these two options in the application while both return the same error.

How is the application inside the docker container supposed to access chrome data from outside the container?

**Comment by jrandolf** [comment]
Please file a bug with `n8n-nodes-puppeteer-extended`
