### ISSUE TITLE
[Bug]: docs + config need updates

### ISSUE THREAD

**Issue by tobwen** [puppeteer/puppeteer#9035]
### Bug description

Although 18.x is out for a while, most docs are stuck at v17.1.0:

https://github.com/puppeteer/puppeteer/blob/c0c7878adc5ea4186ec5d86805b50c0418302e82/versions.js#L17-L20

https://github.com/puppeteer/puppeteer/blob/c0c7878adc5ea4186ec5d86805b50c0418302e82/website/versioned_docs/version-18.0.5/chromium-support.md?plain=1#L9-L11

https://github.com/puppeteer/puppeteer/blob/c0c7878adc5ea4186ec5d86805b50c0418302e82/docs/chromium-support.md?plain=1#L9-L11

### Puppeteer version

18.x

### Node.js version

n/a

### npm version

n/a

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
This places only mention when the new chromium binary was first rolled. The later versions assume the same Chromium binary version: i.e., `106.0.5249.0` is still used with v18.

**Comment by tobwen** [comment]
Okay, I'll better parse this then: https://github.com/puppeteer/puppeteer/blob/6e9a47a6faa06d241dec0bcf7bcdf49370517008/src/revisions.ts#L21
