### ISSUE TITLE
[Bug]: Firefox doesn't have DRM related plugins (Widevine, OpenH264) enabled

### ISSUE THREAD

**Issue by Timileyin105** [puppeteer/puppeteer#9037]
### Bug description

Steps to reproduce the problem:

1. …
i added an executable path to my puppeteer Firefox to launch my server Firefox browser, it worked fine but i am having some issues, the browser plugins are not being added to the browser.
how do i make Puppeteer load the default browser settings, plugins etc or how i can add the plugins while launching puppeteer browser.
thanks

### Puppeteer version

latest version

### Node.js version

latest version

### npm version

latest version

### What operating system are you seeing the problem on?

Linux

**Comment by jrandolf** [comment]
Not sure if plugins are possible on Firefox. @whimboo Does Firefox support the extension API from Puppeteer?

**Comment by whimboo** [comment]
@jrandolf which CDP APIs do those correspond to? AFAIK we don't have support for that and also won't add it. Target here to get such a feature would be WebDriver BiDi.

**Comment by Timileyin105** [comment]
i was trying to use browserWSEndpoint, running the extension on a port but it wasnt connection to that port, im having error connection refused
           
              //creates port for on the server
              const CDPPort = await getPort();
              //runs the extension on the port
              await webExt.cmd.run(
                {
                  sourceDir: '/home/ziurime/grabber/widevine',
                  firefox: 'path',
                  args: [`-juggler=${CDPPort}`]
                },
                {
                  shouldExitProgram: false
                }
             );
            
            browser = await puppeteer.connect({
              headless: false,
              product: 'firefox',
              executablePath: 'path',
              userDataDir: userDataDir,
              browserWSEndpoint: `ws://62.210.207.19:${CDPPort}`
            }).catch(e => {
              console.log(e);
            });

**Comment by whimboo** [comment]
If it's not about interacting with an extension (I don't know what `webExt.cmd.run` is doing) but Puppeteer not being able to connect on startup you might want to provide some debug logs like with the `DEBUG="puppeteer:*" environment variable set, or even better by setting the following Firefox preference: `remote.log.level=Trace`.

**Comment by Timileyin105** [comment]
hello, i have thesame issue from this [opened issue](https://github.com/puppeteer/puppeteer/issues/8873)

**Comment by Timileyin105** [comment]
when i go to the firefox nightly directory and run, the plugins and needed things already installed and loaded in it but when launched by puppeteer it doesnt load all the default plugin and extensions on the firefox nightly , its starting with a new profile or maybe i say settings

**Comment by Timileyin105** [comment]
yes i added the path to the firefox executable file on my linux server
note: using the default path without specifying path still does same thing(launches the browser with the preconfigured settings and plugin there but if launched directly without puppeteer those plugins and extensions all available in the browser)

**Comment by whimboo** [comment]
This is not what I was asking. Again, where does `userDataDir` point to? I'm fairly sure it's not the Firefox profile that Puppeteer should use.

**Comment by Timileyin105** [comment]
kinldy reference this [page](https://github.com/puppeteer/puppeteer/issues/3737#issuecomment-493385493) as regards the pref settings
thanks

**Comment by Timileyin105** [comment]
Thanks for your help all while
i am trying to add Widevine Content Decryption Module provided by Google Inc. and 
OpenH264 Video Codec provided by Cisco Systems, Inc.  plugin
![image](https://user-images.githubusercontent.com/83769790/194560707-c57d77f9-f3cc-47e7-bec3-41265a09b4a2.png)

by default this plugins are available when i launch the browser executable file directly without puppeteer
thanks

**Comment by Timileyin105** [comment]
in puppeteer when launched 
![image](https://user-images.githubusercontent.com/83769790/194569451-7d79e0bf-ba06-4450-9df6-f05c699c919a.png)
 tries to download the plugin again but wont download

**Comment by whimboo** [comment]
Ah, that's more helpful now. So if this is all about the DRM related plugins then those are [disabled by default in the Firefox launcher](https://github.com/puppeteer/puppeteer/blob/a032583b6c9b469bda699bca200b180206d61247/packages/puppeteer-core/src/node/FirefoxLauncher.ts#L422-L423). If you want to use them you will have to override this preference by setting its value to true like:

```
    const browser = await puppeteer.launch({
      product: "firefox",
      extraPrefsFirefox: {
        'media.gmp-manager.updateEnabled': true,
      },
    });
```

The plugins will be downloaded when the first DRM related content is accessed. If that's too late for you then you will hvae to use an already provisioned Firefox profile.

**Comment by Timileyin105** [comment]
big thanks,  it worked. the plugin was downloaded this time unlike before.
one question  please,  how do i load previous profile because i could see that after launching the browser again it started re-downloading the plugins again

**Comment by whimboo** [comment]
You can follow these steps:
1. Create an empty folder
2. Start Firefox from the command line with `--profile path_to_folder`
3. Run all the steps to prepare the profile
4. Quit Firefox
5. For Puppeteer set the `userDataDir` option to this folder

**Comment by Timileyin105** [comment]
thats awesome. thanks for your assistance

**Comment by kkm** [comment]
Great but why not use with Chrome? Chrome doesnt support with remote-debug?

**Comment by fokkerone** [comment]
using Chrome/Canary with headless: false on MacOS Ventura also not enables Widevine as reported here https://niespodd.github.io/browser-fingerprinting/, when visitig the site on puppeteer controlled Window. 
same browser , different fingerprint 
Left started from dock, right side via Puppeteer. As you can see Puppeteer Chrome is without Widewine

<img width="1426" alt="Bildschirm­foto 2023-02-26 um 11 13 34" src="https://user-images.githubusercontent.com/96452/221404498-4eb84fda-fddc-46b8-8875-a90e6f993993.png">

Any ideas how to start it with widewine enabled?

**Comment by whimboo** [comment]
@fokkerone when this is about Chrome please file a new issue. This one is closed and only for Firefox.
