### ISSUE TITLE
[Bug]: Cannot intercept ServiceWorker/WebWorker request

### ISSUE THREAD

**Issue by luneice** [puppeteer/puppeteer#9041]
### Bug description

[In this case](https://github.com/puppeteer/puppeteer/issues/4041), there is solution about how to intercept `ServiceWorker/WebWorker` request. But that puppeteer version was lower, and the `Page` has `_client` property
, but when `puppeteer` version is higher, the `_client` was deprecated. So the same way as follows:
```ts
const client = await page.target().createCDPSession();
await client.send("Network.setBypassServiceWorker", { bypass: true });
```
But the `ServiceWorker/WebWorker` request cannot intercept.

### Puppeteer version

^18.0.5

### Node.js version

v18.8.0

### npm version

8.18.0

### What operating system are you seeing the problem on?

macOS, Windows

**Comment by LastPlayerTR** [comment]
Still cannot intercept webworker traffic.
