### ISSUE TITLE
Post Form with data and Header Properties

### ISSUE THREAD

**Issue by priyankapuranik** [puppeteer/puppeteer#905]
I am doing some web scraping using puppeteer.I came across a href link(in "form" format) which i need to download.I need to use the http post method to post a form and also specify the request header !How do I do that?
URL: https://www.xyz.com
Method: POST
Headers: 

Accept: text/html, application/xhtml+xml, */*
Referer: https://www.xyz.com
Accept-Language: en-US
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Host: 
Content-Length: 5035
Connection: Keep-Alive
Cache-Control: no-cache
Cookie:

**Comment by GuilloOme** [comment]
@priyankapuranik, Why did you close it? How did you manage to do that?

**Comment by Garbee** [comment]
You just use a normal `fetch` or `XMLHttpRequest` to do the data submission. Nothing special in puppeteer to make it work.
