### ISSUE TITLE
[Bug]: 18.2.0 puppeteer expected incorrect puppeteer-core file structure

### ISSUE THREAD

**Issue by ckychris** [puppeteer/puppeteer#9061]
### Bug description

Steps to reproduce the problem:

1. Run `puppeteer.launch`

Looking for `puppeteer-core/internal/common` but in `node_modules` it's `puppeteer-core/lib/cjs/common`

### Puppeteer version

18.2.0

### Node.js version

16.17.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
Cannot find module 'puppeteer-core/internal/common/DeviceDescriptors.js' from 'node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js'

    Require stack:
      node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
      src/launchPuppeteer.ts
      src/launchPuppeteer.spec.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/puppeteer/src/puppeteer.ts:18:1)
```

**Comment by jrandolf** [comment]
Seems like you are using a third party resolver that does not resolve against the [`exports` field of `package.json`](https://nodejs.org/api/packages.html#exports) (a feature which exists in Node all the way back to 12). According to a quick gSearch, updating jest past `v28.0.0-alpha.3` will resolve this.
