### ISSUE TITLE
page.setContent(html, {waitUntil: 'networkidle'});

### ISSUE THREAD

**Issue by graingert** [puppeteer/puppeteer#907]
I'd like to be able to wait for network idle in:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetcontenthtml

I'd like to be able to do:

```js
await page.setContent('<img src="http://example.com/foo.jpg" />', {waitUntil: 'networkidle'});
```

because currently:

```js
await page.setContent('<img src="http://example.com/foo.jpg" />');
const buff = await page.pdf(); // produces a blank PDF.
```

**Comment by graingert** [comment]
my workaround is to use:

```js
await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle' });
```

**Comment by graingert** [comment]
closing as duplicate of https://github.com/GoogleChrome/puppeteer/issues/728

**Comment by lukasvarkalis** [comment]
> my workaround is to use:
> 
> ```js
> await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle' });
> ```

Networkidle is no longer supported. You use 'networkidle2' instead

**Comment by lukasvarkalis** [comment]
> my workaround is to use:
> 
> ```js
> await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle' });
> ```

Networkidle is no longer supported. You should use 'networkidle2' instead

**Comment by cosmith** [comment]
For anyone still using this workaround, now `await page.setContent('<img src="http://example.com/foo.jpg" />', {waitUntil: 'networkidle0'});` works. (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetcontenthtml-options) 

Using ```page.goto(`data:text/html,${html}`)``` led to some issues with special characters for us, setContent is definitely a better solution!
