### ISSUE TITLE
[Bug]: Puppeteer won't build when running yarn PnP

### ISSUE THREAD

**Issue by nemanja-tosic** [puppeteer/puppeteer#9076]
### Bug description

Steps to reproduce the problem:

1. set up yarn for pnp
2. run yarn

### Puppeteer version

18.2.1

### Node.js version

16.17.1

### npm version

yarn 3.2.4

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
# This file contains the result of Yarn building a package (puppeteer@npm:18.2.1)
# Script name: postinstall

ERROR: Failed to set up Chromium r1045629! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: EROFS: read-only filesystem, mkdir '/node_modules/puppeteer-core/.local-chromium'
    at makeError$1 (/home/ntosic/Projects/app/.pnp.cjs:40445:24)
    at EROFS (/home/ntosic/Projects/app/.pnp.cjs:40472:10)
    at ZipFS.mkdirSync (/home/ntosic/Projects/app/.pnp.cjs:42380:13)
    at ZipFS.mkdirPromise (/home/ntosic/Projects/app/.pnp.cjs:42374:17)
    at /home/ntosic/Projects/app/.pnp.cjs:43441:26
    at /home/ntosic/Projects/app/.pnp.cjs:43623:81
    at ZipOpenFS.getZipPromise (/home/ntosic/Projects/app/.pnp.cjs:43730:22)
    at ZipOpenFS.makeCallPromise (/home/ntosic/Projects/app/.pnp.cjs:43623:23)
    at ZipOpenFS.mkdirPromise (/home/ntosic/Projects/app/.pnp.cjs:43438:23)
    at VirtualFS.mkdirPromise (/home/ntosic/Projects/app/.pnp.cjs:42724:24) {
  code: 'EROFS'
}
```

**Comment by dobesv** [comment]
You may be able to workaround it by running `yarn unplug -R puppeteer-core`.  But there's probably a way that puppeteer-core could tell yarn to do this by default, as this used to work with the old package structure.

**Comment by dobesv** [comment]
Although after doing that I now get an error `Cannot find module 'devtools-protocol' or its corresponding type declarations.`  Not sure if that's something unrelated, though.

**Comment by nemanja-tosic** [comment]
Thanks @dobesv, `yarn unplug -R puppeteer-core` works fine as far as i can tell.

I've no subsequent errors either, so i'm not sure why you get the `Cannot find module 'devtools-protocol' or its corresponding type declarations` one.

Yarn PnP was unplugging puppeteer without any additional settings, I wonder what the difference is between puppeteer and puppeteer-core that force us to explicitly unplug it.

**Comment by nemanja-tosic** [comment]
@jrandolf clearing the cache didn't do the trick for me. The error occurs on a clean install as well (double check if yarn initializes with the pnp linker after running this, i'm not sure what the default is for what version):

```
yarn init -i=latest
yarn add puppeteer

...
➤ YN0000: ┌ Link step
➤ YN0007: │ puppeteer@npm:18.2.1 must be built because it never has been before or the last one failed
➤ YN0009: │ puppeteer@npm:18.2.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-1d5a19a8/build.log)
➤ YN0000: └ Completed in 0s 464ms
```

Running

```
yarn unplug -R puppeteer-core
```

fixes the issue in the clean install scenario as well.

**Comment by dobesv** [comment]
For me, both errors occurred in the CI, which is always using a clean install.

**Comment by paulwongx** [comment]
I'm encounter this issue with `^18.2.1`. Older versions didn't have this problem. 
When I try `yarn unplug -R puppeteer-core`, it doesn't work as per below:
```
error Packages can only be unplugged when Plug'n'Play is enabled.
info Visit https://yarnpkg.com/en/docs/cli/unplug for documentation about this command.
```
The error when trying to install puppeteer is...
```
Output:
ERROR: Failed to set up Chromium r1045629! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
[Error: 13592:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:677:] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'decryption failed or bad record mac',
  code: 'ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC'
}
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
Using windows 10.
Open to suggestions...

**Comment by dobesv** [comment]
> I've no subsequent errors either, so i'm not sure why you get the Cannot find module 'devtools-protocol' or its corresponding type declarations one.

Are you using typescript ?

**Comment by wegry** [comment]
@dobesv I'm using TS and seeing the error in 

```
.yarn/unplugged/puppeteer-npm-19.7.0-264de65101/node_modules/puppeteer/lib/types.d.ts:4:26 - error TS2307: Cannot find module 'devtools-protocol' or its corresponding type declarations.

4 import { Protocol } from 'devtools-protocol';
                           ~~~~~~~~~~~~~~~~~~~

.yarn/unplugged/puppeteer-npm-19.7.0-264de65101/node_modules/puppeteer/lib/types.d.ts:5:33 - error TS2307: Cannot find module 'devtools-protocol/types/protocol-mapping.js' or its corresponding type declarations.

5 import { ProtocolMapping } from 'devtools-protocol/types/protocol-mapping.js';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by aultac** [comment]
This bug still appears to exist as of January 2024.  For fellow travelers, you can fix this by using yarn (not classic yarn) to correct the missing dependency in puppeteer.  Put the following into your `.yarnrc.yml` file:

```yaml
packageExtensions: {
  puppeteer@*: {
    dependencies: {
      devtools-protocol:  "*"
    }
  }
}
```
and then it should work and compile in typescript as expected.  Be sure to re-run `yarn` after making the change.  If puppeteer adds the devtools-protocol to its dependencies, then this should no longer be needed.
