### ISSUE TITLE
[Bug]: `DOM.requestNode` returns `nodeId=0`

### ISSUE THREAD

**Issue by stevenwdv** [puppeteer/puppeteer#9077]
### Bug description

Steps to reproduce the problem:

1. Visit a page with an element with id=demo_id and open a CDP session
2. Obtain the `RemoteObjectId` of the node, using `Runtime.evaluate` with `{expression:"demo_id"}`
3. Request the corresponding `NodeId` using `DOM.requestNode`
4. **Issue: Get back `nodeId=0`..?**
To compare: execute the following in the experimental Protocol Monitor console in the Chromium devtools:
5. `{"command":"Runtime.evaluate", "parameters":{"expression":"demo_id"}}`
6. `{"command":"DOM.requestNode", "parameters":{"objectId":"<RemoteObjectId just obtained>"}}`
7. Get back the actual nonzero `NodeId`
(If you execute this in the same browser as the previous steps, you will notice that that the `RemoteObjectId` obtained in step 5 is the same as in step 2. However, if you execute step 6 without executing step 5 you will get back `Could not find object with given id`. Not sure if this is by CDP design?)

This may well be an upstream issue, but I'm not sure what causes it to work fine in the devtools and not via Puppeteer.

Script:
```js
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({headless: false});
const page    = await browser.newPage();
await page.goto('data:text/html,' + encodeURIComponent('<input id=demo_id />'));

const cdp = await page.target().createCDPSession();
await cdp.send('Runtime.enable');
await cdp.send('DOM.enable');
const {result: {objectId}} = await cdp.send('Runtime.evaluate', {expression: 'demo_id'});
console.log(objectId);  // Correct id
const {nodeId} = await cdp.send('DOM.requestNode', {objectId});
console.log(nodeId);  // 0 ??
```

### Puppeteer version

18.2.1

### Node.js version

18.9.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
3462418028677997700.3.1
0
```

**Comment by jrandolf** [comment]
I'm not sure what you are expecting here. Shouldn't the expression be `document.getElementById('demo_id')`?

**Comment by stevenwdv** [comment]
@jrandolf That's equivalent, see https://html.spec.whatwg.org/multipage/window-object.html#dom-window-nameditem

**Comment by OrKoN** [comment]
In general, `nodeId`s exist only for the DevTools frontend and implement the mechanism by which the DevTools frontend gets updates for a subtree of elements. It appears that `requestNode` only returns an ID if the node is already known to the frontend. E.g., if you add `await cdp.send('DOM.getDocument', {depth: 10});` before `requestNode`. I am not sure why it works like this but there are probably reasons. In any case, I think you should report this via crbug.com as it's not something we can fix within Puppeteer.

**Comment by stevenwdv** [comment]
@OrKoN Ok thanks, that might be the cause, I guess I'll report it there then. I need the `NodeId` for `DOMDebugger.setDOMBreakpoint` btw.

**Comment by stevenwdv** [comment]
(Chromium bug is now at https://crbug.com/1374241. Your workaround using `DOM.getDocument` seems to work, even with `depth=0`)
