### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by vukasin992** [puppeteer/puppeteer#9089]
Guys I am getting this error after installation: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/common/DeviceDescriptors.js' is not defined by "exports" in /usr/src/app/node_modules/puppeteer-core/package.json

**Comment by jrandolf** [comment]
Could you provide an explanation of your setup? We don't use `./internal/common` anywhere in our code, so this must be coming from your codebase.

**Comment by JMMFL** [comment]
I have encountered this error and "Failed to launch browser". 

I tried the following troubleshoots:
- Following the Troubleshoot Guide
- Setting Node to 16x LTS
- Downgrading Node to 14.1.0
- Installing Chromium manually via install.js (after exporting/unsetting PUPPETEER_SKIP_DOWNLOAD)

I'm using WSL: Ubuntu 20.04 LTS on Windows 11.

**Comment by JMMFL** [comment]
Fixed my issues by installing the Ubuntu dependencies listed in Troubleshoot Guide :)

**Comment by Dvdhan** [comment]
> Fixed my issues by installing the Ubuntu dependencies listed in Troubleshoot Guide :)

Can you share the details about the Troubleshoot Guide to fix the problem ??

**Comment by CeceliaYu** [comment]
request for the Troubleshoot Guide too.

**Comment by leonardow-unep-wcmc** [comment]
Here is the Troubleshoot Guide: https://pptr.dev/troubleshooting#cannot-find-module-puppeteer-coreinternal

**Comment by joelvanpatten** [comment]
I just had this same issue.  In my case I was able to fix it with these two commands:

`npm update
npm audit fix`

**Comment by amanemsboy** [comment]
Make sure you are not using unnecessary imported packages.
like this :  
const { Connection } = require("mysql2/typings/mysql/lib/Connection");
