### ISSUE TITLE
 Error: Failed to launch the browser process! on AWS EC2 , working fine on local

### ISSUE THREAD

**Issue by sakshibhatiaVE** [puppeteer/puppeteer#9092]
### Bug description

/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory

this is the error I am facing when pushed code on AWS server. Code is working fine on local machine.
Tried a lot of puppeteer version i.e 18.2.1, 18.0.5, 15.5.0.

### Puppeteer version

18.2.1, 18.0.5, 15.5.0

### Node.js version

16.10.0

### npm version

7.24.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Failed to launch the browser process!
0|app      | /var/www/html/bptreat/api/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory
0|app      |
0|app      |
0|app      | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|app      |
0|app      |     at onClose (/var/www/html/bptreat/api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:286:20)
0|app      |     at Interface.<anonymous> (/var/www/html/bptreat/api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:274:24)
0|app      |     at Interface.emit (node:events:539:35)
0|app      |     at Interface.close (node:internal/readline/interface:529:10)
0|app      |     at Socket.onend (node:internal/readline/interface:258:10)
0|app      |     at Socket.emit (node:events:539:35)
0|app      |     at endReadableNT (node:internal/streams/readable:1345:12)
0|app      |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by OrKoN** [comment]
Have you tried installing dependencies listed in [https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md ? ](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) ? I believe your host is missing libsound and probably other dependencies.

**Comment by sakshibhatiaVE** [comment]
> Have you tried installing dependencies listed in [https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md ? ](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) ? I believe your host is missing libsound and probably other dependencies.

Most of the dependencies mentioned in the page do not exist anymore.
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci

**Comment by OrKoN** [comment]
@sakshibhatiaVE do you mean they don't exist for AWS Server? They seem to be available for Ubuntu/Debian. In that case, you would need to build missing dependencies yourself or figure out how to add them to your distro.

**Comment by sakshibhatiaVE** [comment]
My local machine is Windows, and puppeteer is working fine for Windows but my server is on AWS EC2. There I am facing a lot of problem. I tried installing chromium and libasound separately but no luck.

**Comment by sakshibhatiaVE** [comment]
Its working finally. I tried there two commands.

sudo amazon-linux-extras install epel -y
sudo yum install -y chromium

Thanks @OrKoN

**Comment by AliHewiagh** [comment]
any facing still facing this issue: 
https://stackoverflow.com/questions/66214552/tmp-chromium-error-while-loading-shared-libraries-libnss3-so-cannot-open-sha/67117619#67117619
