### ISSUE TITLE
Generalize page.waitFor, make waitForSelector a utility on top of it.

### ISSUE THREAD

**Issue by pavelfeldman** [puppeteer/puppeteer#91]
Rationale: waitForSelector is rarely useful on its own. I have a DOM element, but it is off screen / display:none, etc.

We can make waitFor generic and execute it either upon every task (by default) or upon tasks that had specific activities in them (optional).

```js

utilitites.waitForSelector = (selector) => {
  return page.waitFor(() => document.querySelector(selector), ['style'], selector);
}

utilitites.waitForLayout = () => {
  return page.waitFor(() => true, ['layout']);
}

utilitites.waitForFrame = () => {
  return page.waitFor(() => true, ['frame']);
}

```

**Comment by JoelEinbinder** [comment]
Just for reference, Nightmare has a generic `.wait` method that takes a number, selector, or function. It polls every 250ms to see if that function returns true, or if there is an element matching that selector.

**Comment by aslushnikov** [comment]
We've spent some time discussing this and here's what we've agreed upon so far:

```js
await page.waitFor(1000); // to wait for 1000ms
await page.waitFor('body div'); // to wait for the 'body div' selector in body
await page.waitFor(() => Math.random() < 0.5); // to wait for the predicate

await page.waitForSelector('body div'); // the same as page.waitFor('body div')
// wait for the 'body div' to be present and visible in the page:
await page.waitForVisible('body div');
```

**Comment by aslushnikov** [comment]
Since `page.waitFor` should timeout after some time, and since the timeout should be customizable, the `page.waitFor` will have an options object:

```js
await page.waitFor('body div', {timeout: 10000}); // timeout after 10s
await page.waitFor('body div', {visible: true}); // wait for element to be present and visible
```

**Comment by jenni** [comment]
Any news about...?

```
// wait for the 'body div' to be present and visible in the page:
await page.waitForVisible('body div');
```

This would be a great addition.

**Comment by aslushnikov** [comment]
@jen-v you can already use the `visible` option in [`page.waitForSelector`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforselectorselector-options) method

**Comment by JakubMatyka** [comment]
I stuck on scenario when modal occurs and a button should be clicked. `page.waitForSelector` with flag `visible: true` does not work in this situation. The only way is to set timeout but I hate those
