### ISSUE TITLE
[Feat] BiDi/Page implements `goto`

### ISSUE THREAD

**Issue by sadym-chromium** [puppeteer/puppeteer#9101]
As part of the #9100, BiDi/Page should implement [`goto`](https://github.com/puppeteer/puppeteer/blob/8acafe2fd91b70b8bbbe10467b6a0b5894b964bb/packages/puppeteer-core/src/api/Page.ts#L1410) method returning null (as [network logging](https://github.com/w3c/webdriver-bidi/issues/196) is not specified nor implemented yet).

**Comment by thiagowfx** [comment]
https://pptr.dev/api/puppeteer.page._
