### ISSUE TITLE
[Feat] BiDi/Page implements `$`

### ISSUE THREAD

**Issue by sadym-chromium** [puppeteer/puppeteer#9102]
As part of the #9100, BiDi/Page should implement [`$`](https://github.com/puppeteer/puppeteer/blob/8acafe2fd91b70b8bbbe10467b6a0b5894b964bb/packages/puppeteer-core/src/api/Page.ts#L769).

**Comment by thiagowfx** [comment]
https://pptr.dev/api/puppeteer.page._

**Comment by thiagowfx** [comment]
<img width="1040" alt="image" src="https://github.com/puppeteer/puppeteer/assets/2840106/6a2c6680-48f4-4645-9667-dda20448001e">

**Comment by thiagowfx** [comment]
Ah, sorry, there's `Page.$` but not in BiDi: https://github.com/puppeteer/puppeteer/blob/8acafe2fd91b70b8bbbe10467b6a0b5894b964bb/packages/puppeteer-core/src/common/bidi/Page.ts#L40

**Comment by thiagowfx** [comment]
Nik maybe you may want to tackle this :-) Feel free to unassign otherwise.
