### ISSUE TITLE
[Feat] BiDi/Page implements `evaluate`

### ISSUE THREAD

**Issue by sadym-chromium** [puppeteer/puppeteer#9103]
As part of the #9100, BiDi/Page should implement [`evaluate`](https://github.com/puppeteer/puppeteer/blob/8acafe2fd91b70b8bbbe10467b6a0b5894b964bb/packages/puppeteer-core/src/api/Page.ts#L2013) method with proper serialization / deserialization.

**Comment by thiagowfx** [comment]
Is this done?

**Comment by sadym-chromium** [comment]
I assume so: https://github.com/puppeteer/puppeteer/blob/8acafe2fd91b70b8bbbe10467b6a0b5894b964bb/packages/puppeteer-core/src/common/bidi/Page.ts#L40
