### ISSUE TITLE
Extension of  TestExpectations.json file

### ISSUE THREAD

**Issue by lutien** [puppeteer/puppeteer#9118]
The Firefox team would be really happy to use [TestExpectations.json](https://github.com/puppeteer/puppeteer/blob/main/test/TestExpectations.json) internally in mozilla ci instead of our custom solution, but right now most of the tests for Firefox which don't pass marked as skipped, which doesn't give us a good overview if it's a correct behavior. 
Would you be open to have in this file more of `fail`, `timeout`, `fail-pass` expectations? Or there is any specific reason why you would rather skip them?
If you are fine with the suggestion, we are ready to contribute an initial setup for it.

As a reference, this is how it looks now in mozilla repo: https://searchfox.org/mozilla-central/source/remote/test/puppeteer-expected.json

**Comment by OrKoN** [comment]
@lutien the reason for using skip is that many of those tests are timing out which takes a long time to run on CI. We could unskip some tests if that does not dramatically increase the time needed to run them.
