### ISSUE TITLE
[Bug]: PDF (file size) created by puppeteer is increased after upgrading it to 12.0.0 

### ISSUE THREAD

**Issue by yogeshhrathod** [puppeteer/puppeteer#9124]
### Bug description

I have been using puppeteer 9.0.0 previously and the size of the PDF generated by an HTML was 3MB after up upgrading it to the new version or ^11.0.0 PDF generated by the same HTML is 16MB.

has anyone Idea about why this is happening.

I have also inspected both PDFs in itext_rups and I found that

![image](https://user-images.githubusercontent.com/46518134/196150720-b8e53ed1-06a1-4362-b8a7-9a55af21aae5.png)
*Structure of PDF generated by puppeteer 10.2.0, (3MB)*

![image](https://user-images.githubusercontent.com/46518134/196150583-e653fdca-bd06-41af-8352-d05e0f544215.png)
*Structure of PDF generated by puppeteer 12.0.0, (16MB)*

both PDF structure is almost the same except the "**/StructRootTree**" is present in 16MB PDF and which is causing most of the **extra storage**

**Is there any solution/flag so we can generate PDF in small size even new version of Puppeteer**

### Puppeteer version

12.0.0

### Node.js version

16.15.1

### npm version

8.12.1

### What operating system are you seeing the problem on?

Windows

**Comment by pecampelo** [comment]
I would only give a suggestion as to the scope of the problem for you to describe in the issue title that the _size_ is increased dramaticcally, not the PDF itself.

**Comment by OrKoN** [comment]
@pecampelo could you try with the latest version? Also note that Puppeteer does not generate the PDF on its own, it delivers what the browser produces. Newer versions of Puppeteer simply bundle a newer version of the browser. If the issue is confirmed in the latest browser, the bug should be filed via crbug.com for either the pdf print or headless teams.

**Comment by yogeshhrathod** [comment]
Yes, issue exist in the latest version of puppeteer that is 18.

**Comment by OrKoN** [comment]
@yogeshhrathod do you also get the increased size if you print using the built-in print dialog in the headful browser?

**Comment by OrKoN** [comment]
Also, could you please provide a repro for filing a crbug.com issue?

**Comment by yogeshhrathod** [comment]
> @yogeshhrathod do you also get the increased size if you print using the built-in print dialog in the headful browser?

I have checked that PDF generated 15 MB PDF is generated.

Chrome version: 106.0.5249.119 (Official Build) (64-bit)

**Comment by aleksmurfitt** [comment]
Skia in newer Chromium produces tagged PDFs which are much larger than non-tagged PDFs but I doubt it would produce a 5x size increase.

**Comment by OrKoN** [comment]
Thanks for the details, was not aware of that. Then I believe it's indeed not a bug as we would prefer generate compliant PDFs by default. I think the size can be optimized by other solutions if the size is critical for the use case. You should use `ignoreDefaultArgs : ['--export-tagged-pdf']` if you want not tagged PDFs.
