### ISSUE TITLE
[Bug]: response.json times out in Firefox

### ISSUE THREAD

**Issue by Timileyin105** [puppeteer/puppeteer#9129]
### Bug description

`page.on('response', async response => {`
`    console.log(response); // returns HTTPResponse {}`
`    if (response.url().includes('api/info')){`
`     let jsn =  await response.json(); //never ending promise`
`    }`
`})`

puppeteer firefox returns empty  response object HTTPResponse {} but works fine in chrome
kinldy help in checking this out
im trying to get a request response

### Puppeteer version

latest version

### Node.js version

latest version

### npm version

latest version

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Could you please provide a repro script? Note that Firefox support is still experimental and somewhat limited and that might be an existing limitation.

**Comment by Timileyin105** [comment]
pardon my bad formatting  🙂

**Comment by OrKoN** [comment]
It looks like a problem with Firefox's implementation of CDP. Firefox team won't extend the functionality of their CDP implementation given the focus on WebDriver BiDi, therefore, closing this issue.

**Comment by licong-site** [comment]
I have the same problem,  response.json()  response.text()  times out in Firefox.
