### ISSUE TITLE
[Bug]: Cant get return out of page.on, returns undefined

### ISSUE THREAD

**Issue by UsVfxArtia** [puppeteer/puppeteer#9145]
### Bug description

Steps to reproduce the problem:

page.on return not works :c 
```
import puppeteer from "puppeteer-extra";
import StealthPlugin from 'puppeteer-extra-plugin-stealth'

async function ProductAPI() {
        puppeteer.use(StealthPlugin())
        const browser = await puppeteer.launch({headless: true});
        const page = await browser.newPage();

        page.on('response', async (response) => {
            if(response.url().includes('some_link_here')){
            console.log('XHR response received');
            const HTMLdata = await response.text()
            console.log(HTMLdata) // If you just try to display the log, then everything works, but return returns undefined
            return "fine!" // Not works!
            
        };});

        await page.goto('some_link_here');

}        
await ProductAPI().then((data) => {
    console.log(data)});
```

console.log(data) gives undefined, instead of "fine!", I tried different options, but I can't get the necessary return.

### Puppeteer version

3.2.2

### Node.js version

16.18.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Windows

**Comment by jrandolf** [comment]
You need to use a promise that resolves when the page response is fine. You need to wrap it with a promise constructor like so:

```ts
import puppeteer from 'puppeteer-extra';
import StealthPlugin from 'puppeteer-extra-plugin-stealth';

async function ProductAPI() {
  puppeteer.use(StealthPlugin());
  const browser = await puppeteer.launch({headless: true});
  const page = await browser.newPage();

  return new Promise(resolve => {
    page.on('response', async response => {
      if (response.url().includes('some_link_here')) {
        console.log('XHR response received');
        const HTMLdata = await response.text();
        console.log(HTMLdata); // If you just try to display the log, then everything works, but return returns undefined
        resolve('fine!');
      }
    });

    page.goto('some_link_here');
  });
}
await ProductAPI().then(data => {
  console.log(data);
});
```

**Comment by UsVfxArtia** [comment]
> You need to use a promise that resolves when the page response is fine. You need to wrap it with a promise constructor like so:
> 
> ```ts
> import puppeteer from 'puppeteer-extra';
> import StealthPlugin from 'puppeteer-extra-plugin-stealth';
> 
> async function ProductAPI() {
>   puppeteer.use(StealthPlugin());
>   const browser = await puppeteer.launch({headless: true});
>   const page = await browser.newPage();
> 
>   return new Promise(resolve => {
>     page.on('response', async response => {
>       if (response.url().includes('some_link_here')) {
>         console.log('XHR response received');
>         const HTMLdata = await response.text();
>         console.log(HTMLdata); // If you just try to display the log, then everything works, but return returns undefined
>         resolve('fine!');
>       }
>     });
> 
>     page.goto('some_link_here');
>   });
> }
> await ProductAPI().then(data => {
>   console.log(data);
> });
> ```

Thank you very much!
