### ISSUE TITLE
[Bug]:    Connection. _rawSend   Added the option to send objects instead of just strings

### ISSUE THREAD

**Issue by 274820472** [puppeteer/puppeteer#9147]
### Bug description

To use this library for browser extensions, you need   **puppeteer.connect({   transport  });**

In the source code, **Connection. _rawSend** needs to convert the object to a string.

But in the browser, chrome.  The **chrome.debugger.sendCommand**   is object,

On our end, we need **JSON.parse(message)**, which wastes performance,

If  **Connection. _rawSend**  sends objects directly, you can save performance...

### Puppeteer version

puppeteer-core/lib/cjs/puppeteer/web

### Node.js version

chrome.debugger

### npm version

0

### What operating system are you seeing the problem on?

Windows

**Comment by 274820472** [comment]
\puppeteer-core\lib\esm\puppeteer\common\Connection.js   
This file
Connection._rawSend

**Comment by jrandolf** [comment]
`_rawSend` converts the entire payload (not just the data) into a string for WebSocket transport.
