### ISSUE TITLE
[Bug]: Target.getTargets inconsistent results

### ISSUE THREAD

**Issue by spinlud** [puppeteer/puppeteer#9148]
### Bug description

I have this code which clicks on an apply button on a Linkedin job. The click will open a new tab (target). I want to use [CDP Target.getTargets](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-getTargets) to get available targets after the button click. This has worked fine until `Puppetter 15.x.x`, but it doesn't work reliably in newer versions.

```ts
import puppeteer from 'puppeteer';

(async () => {
    const url = 'https://www.linkedin.com/jobs/search/?currentJobId=3326678695&f_TPR=r86400&keywords=Data%20Engineer&location=Canada&sortBy=DD';
    const applyBtnSelector = 'a.apply-button';
    
    const browser = await puppeteer.launch({
        headless: false,
        slowMo: 200,
        args: [
            "--enable-automation",
            "--start-maximized",
            `--window-size=1472,828`,
            "--lang=en-GB",
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage",
            "--disable-gpu",
            "--disable-accelerated-2d-canvas",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage",
            "--proxy-server='direct://",
            "--proxy-bypass-list=*",
            "--allow-running-insecure-content",
            "--disable-web-security",
            "--disable-client-side-phishing-detection",
            "--disable-notifications",
            "--mute-audio",
        ],
        defaultViewport: null,
        pipe: true,
    });
    
    await (await browser.pages())[0].close();
    const context = await browser.createIncognitoBrowserContext();
    const page = await context.newPage();
    const cdp = await page.target().createCDPSession();

    await page.goto(url, { waitUntil: 'networkidle0' });

    // Click apply button: should open a new tab (target)
    const clickResult = await
        page.evaluate((applyBtnSelector: string) => {
            const applyBtn = document.querySelector(applyBtnSelector) as HTMLButtonElement;

            if (applyBtn) {
                applyBtn.click();
                return true;
            }

            return false;
        }, applyBtnSelector);

    console.log('Clicked', clickResult);

    const targetsResponse = await cdp.send('Target.getTargets');
    console.log(JSON.stringify(targetsResponse, null, 2));
    
    await browser.close();
})();
```

The following is the output using `puppeteer@15.5.0`:

```
Clicked true
{
  "targetInfos": [
    {
      "targetId": "D35EB9D71B10CB7F506C23F956563F85",
      "type": "page",
      "title": "",
      "url": "https://www.linkedin.com/jobs/view/externalApply/3326678695?url=https%3A%2F%2Fde%2Ejobsyn%2Eorg%2F6fac17d0f22c407f887dd60ab605ef535073&urlHash=NdgD&trk=public_jobs_apply-link-offsite",
      "attached": false,
      "openerId": "331B23D9D62F6DC7D9C9CA27BF6FF563",
      "canAccessOpener": false,
      "openerFrameId": "331B23D9D62F6DC7D9C9CA27BF6FF563",
      "browserContextId": "76A8FEB03C54D31E5DD1B972C6910A3C"
    },
    {
      "targetId": "331B23D9D62F6DC7D9C9CA27BF6FF563",
      "type": "page",
      "title": "246 Data Engineer jobs in Canada (246 new)",
      "url": "https://www.linkedin.com/jobs/search/?currentJobId=3326678695&f_TPR=r86400&keywords=Data%20Engineer&location=Canada&sortBy=DD",
      "attached": true,
      "canAccessOpener": false,
      "browserContextId": "76A8FEB03C54D31E5DD1B972C6910A3C"
    }
  ]
}
```

This output is correct. There are two targets, one is the main page (currently attached with `attach=true`) and the other is the apply page opened with the click (`attached=false`). As a side note, this is also the output I get using `Selenium` and `chromedriver` doing the same thing.

The following is instead the output using `puppeteer@19.1.0`:

```
Clicked true
{
  "targetInfos": [
    {
      "targetId": "AFB5B97FFEFB841F6F84D6C8FD5A2EF0",
      "type": "page",
      "title": "",
      "url": "",
      "attached": true,
      "openerId": "09CF5BBD445BA21661519849A6D9CCB1",
      "canAccessOpener": false,
      "openerFrameId": "09CF5BBD445BA21661519849A6D9CCB1",
      "browserContextId": "C1FD6F09A8E17977C96AC338149D1EA6"
    },
    {
      "targetId": "09CF5BBD445BA21661519849A6D9CCB1",
      "type": "page",
      "title": "336 Data Engineer jobs in Canada (336 new)",
      "url": "https://www.linkedin.com/jobs/search/?currentJobId=3326678695&f_TPR=r86400&keywords=Data%20Engineer&location=Canada&sortBy=DD",
      "attached": true,
      "canAccessOpener": false,
      "browserContextId": "C1FD6F09A8E17977C96AC338149D1EA6"
    }
  ]
}
```

This output doesn't seem correct. We have two targets, both with `attached=true`. One target doesn't have url set on it.

### Puppeteer version

19.1.0

### Node.js version

16.17.0

### npm version

8.15.0

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
@spinlud in the new versions, Puppeteer attached to all targets that are not filtered out by the target filter. This is needed in order to use CDP's auto-attach mechanism that allows race-free configuration of new targets. That would explain difference w.r.t. to the attached flag. The rest should be not affected and you get what the browser reports. Do you have the same results if you run Target.getTargets via Protocol Monitor in DevTools?

**Comment by spinlud** [comment]
> @spinlud in the new versions, Puppeteer attached to all targets that are not filtered out by the target filter. This is needed in order to use CDP's auto-attach mechanism that allows race-free configuration of new targets. That would explain difference w.r.t. to the attached flag. The rest should be not affected and you get what the browser reports. Do you have the same results if you run Target.getTargets via Protocol Monitor in DevTools?

Hi, I did the same test (open url, click apply button, send `Target.getTargets` command) using Protocol Monitor on Chrome `106.0.5249.119` and Chromium (Puppeteer `19.1.2`), these are the results (I have filtered out entries that are not of type `page`):

`Chrome 106.0.5249.119`
```json
{
    "targetInfos": [
        {
            "targetId": "A55209EC28FA21308A55DF73721A1AC3",
            "type": "page",
            "title": "Data Analytics Instructor - Fusemachines - Career Page",
            "url": "http://jobs.fusemachines.com/apply/8tLFLTXZYo/Data-Analytics-Instructor?source=DIREC",
            "attached": false,
            "openerId": "6E16A6FCAF9AFFD72655E45DE9140B1A",
            "canAccessOpener": false,
            "openerFrameId": "6E16A6FCAF9AFFD72655E45DE9140B1A",
            "browserContextId": "741621777A114C48AB93E71D1AE1B607"
        },        
        {
            "targetId": "6E16A6FCAF9AFFD72655E45DE9140B1A",
            "type": "page",
            "title": "692 Data Engineer jobs in Canada (692 new)",
            "url": "https://www.linkedin.com/jobs/search/?currentJobId=3326678695&f_TPR=r86400&keywords=Data%20Engineer&location=Canada&sortBy=DD",
            "attached": true,
            "canAccessOpener": false,
            "browserContextId": "741621777A114C48AB93E71D1AE1B607"
        },        
    ]
}
```

`Chromium Puppeeter 19.1.2`
```json
{
    "targetInfos": [
        {
            "targetId": "8A17812FA194BDBD76B65ED053714A1C",
            "type": "page",
            "title": "Data Analytics Instructor - Fusemachines - Career Page",
            "url": "http://jobs.fusemachines.com/apply/8tLFLTXZYo/Data-Analytics-Instructor?source=DIREC",
            "attached": true,
            "openerId": "5E96109DB5FD68335D324BCEF7B104C5",
            "canAccessOpener": false,
            "openerFrameId": "5E96109DB5FD68335D324BCEF7B104C5",
            "browserContextId": "D900FAE132C7A0FB0E30D6928BC82268"
        },        
        {
            "targetId": "5E96109DB5FD68335D324BCEF7B104C5",
            "type": "page",
            "title": "12,000+ Data Engineer jobs in United States (12,633 new)",
            "url": "https://www.linkedin.com/jobs/search/?currentJobId=3326678695&f_TPR=r86400&keywords=Data%20Engineer&location=Canada&sortBy=DD",
            "attached": true,
            "canAccessOpener": false,
            "browserContextId": "D900FAE132C7A0FB0E30D6928BC82268"
        }
    ]
}
```

It seems the `attached` flag has a different behaviour between Chrome and Chromium. Also using the Protocol Monitor the url is set for both targets, while using `Puppeteer 19.x.x` the second target doesn't have any url set.

**Comment by OrKoN** [comment]
@spinlud what if you add a delay before calling getTargets on click with Puppeteer?

**Comment by spinlud** [comment]
> @spinlud what if you add a delay before calling getTargets on click with Puppeteer?

Yes, getting the targets after a delay seems to help, but it is not a reliable solution for me. Essentially what I am traying to do here is to extract the dynamic generated url after click. I don't care about page loading, I just need the url (after redirections). For this I need to know which is the active page (`attached` flag) and the target url after any 301/302. I am using raw CDP here because I need this to be fast.

**Comment by OrKoN** [comment]
@spinlud to make it reliable you should probably listen for at least the targetInfoChanged event https://chromedevtools.github.io/devtools-protocol/tot/Target/#event-targetInfoChanged or better for the Page.lifecycleEvent with the type `load`. Otherwise, you always have the timing issue since the backend only knows the URL once the target has finished loading. As for the difference, w.r.t. to the attached flag, I think that is working as expected.
