### ISSUE TITLE
[Bug]: Runs perfectly well on Docker Container inside my machine but kept erroring inside Cloud Run

### ISSUE THREAD

**Issue by IskandarAlex2** [puppeteer/puppeteer#9149]
## Before I begin
I am sorry if the way I explain or info details aren't that great, I not really good at explaining problems.

## Steps to reproduce the problem

1. Make a normal Puppeteer nodejs script with express
2. Deploy it to the Cloud Run and see the problem

## Explanation
I have an express nodejs app that serves as API, I am using Puppeteer for OG Image API, and the way the API works is simple and straightforward, it takes the User ID from the given query of the HTTP request, takes the user data from Firestore, render the dynamic SVG and screenshot it and send the buffer as the response, this issue started when I tried to launch browser which is `Error: Run "npm install" to download the correct Chromium revision (1045629)` or when I even tried to run `puppeteer.executablePath()`, although all of these issues don't seem to appear when the Docker Container is running inside my machine and serve it's purpose perfectly as intended.

## My Dockerfile
```Dockerfile
FROM node:16-slim

WORKDIR /usr/src/app

# They are required to run Puppeteer in a Docker container
RUN apt -y update && apt -y install \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    ibatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libgcc1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    lsb-release \
    wget xdg-utils \
    && rm -rf /var/lib/apt/lists/*

ENV PORT 8080
ENV HOST 0.0.0.0
ENV NODE_ENV PRODUCTION

# Copying package.json
COPY package*.json ./

# install dependencies
RUN npm ci --omit=dev

# copy the entire repository
COPY . .

# Font for Puppeteer
COPY ./Assets/Fonts/zekton.ttf /usr/share/fonts/TTF/

# start the app
CMD npm start
```

### Puppeteer version

^19.1.0

### Node.js version

16-slim

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux, Windows

### Relevant log output

```shell
Error: Run `npm install` to download the correct Chromium revision (1045629)
```

**Comment by jrandolf** [comment]
Seems related to https://github.com/puppeteer/puppeteer/issues/9128. See the comments for the solution.

**Comment by abdalem** [comment]
@IskandarAlex2 Hi! Did you find any solutions ? I am stuck about a week on the same problem...
