### ISSUE TITLE
Image position issue in PDF compared to screenshot in screen mode

### ISSUE THREAD

**Issue by astefanutti** [puppeteer/puppeteer#915]
Environment:

* Puppeteer version: 0.11.0
* Platform / OS version: Mac OS X

While running the following script:

```
const puppeteer = require('puppeteer');

(async () => {
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.emulateMedia('screen');
await page.setViewport({
    width: 1024,
    height: 768,
 });
await page.goto('file:///test.html', {waitUntil: 'load'});
await page.screenshot({
    path           : 'test.png',
    fullPage       : false,
});
await page.pdf({
  path: 'test.pdf',
  width: '1024px',
  height: '768px',
});
await browser.close();
})();
```

With the following page:

```
<html style="height: 100%;">
    <body style="height: 100%;">
        <div style="position: absolute; top: 50%;">
            <div style="position: absolute; transform: translate(0, -50%);">
                <img style="height: 500px;" src="http://peter.bourgon.org/postmodernism/img/rembrandt-self-portrait.jpg">
            </div>
        </div>
    </body>
</html>
```

The image is not centered in the page in the PDF: [test.pdf](https://github.com/GoogleChrome/puppeteer/files/1344927/test.pdf)

While it is as in the screenshot PNG: 
![test](https://user-images.githubusercontent.com/366207/31024109-51fa7670-a53e-11e7-88e3-b80baaa4eb8a.png)

**Comment by jonathan-g** [comment]
I am encountering the same problem with pdf generation. Does anyone have any ideas about how to work around or fix it?

**Comment by pkgw** [comment]
I found that [increasing the page size](https://github.com/astefanutti/decktape/issues/127#issuecomment-352370496) (with the `-s` argument) can help with this sort of problem. Sometimes this leads to problems related to insufficient shared memory inside the Docker container, though, which can be fixed with [the --shm-size argument](https://github.com/GoogleChrome/puppeteer/issues/1321#issuecomment-342883872) to Docker.

**Comment by astefanutti** [comment]
I think it needs to be reported to upstream Chromium project, as it hosts the PDF component development.

**Comment by DanySK** [comment]
This long-standing issue is hitting me as well in 2020, it's most definitely still an issue. :disappointed:

**Comment by jonathan-g** [comment]
This is still an issue for me too, and increasing the page size does not fix it for me.

However, if I use the chrome or chromium executable from the command-line using
```
chrome --headless --run-all-compositor-stages-before-draw --disable-gpu --virtual-time-budget=10000 --print-to-pdf=foo.pdf http://localhost:8000
```
while serving my content to `localhost:8000`, then I get a correct PDF without these problems.

**Comment by Maximvdw** [comment]
Still an issue in 2021

**Comment by pkgw** [comment]
Based on the most recent comments, I think that @stale is incorrect here ...

**Comment by Maximvdw** [comment]
Definitely still an issue...

**Comment by pkgw** [comment]
@stale is there a way to get you to not auto-close confirmed issues?

(Yes I realize that I am talking to a robot)

**Comment by OrKoN** [comment]
I am not able to reproduce with the latest Chrome.

**Comment by astefanutti** [comment]
I confirm it's been fixed with recent versions of Chrome. Thanks.
