### ISSUE TITLE
Chrome Headless doesn't launch on Ubuntu Linux Server

### ISSUE THREAD

**Issue by applecool** [puppeteer/puppeteer#916]
Environment: 

- Platform: `Ubuntu Linux Server 14.04.5 LTS`, `Ubuntu Linux Server 16.04.3 LTS`
- Puppeteer Version: Tried both `0.10.2` and `0.11.0 (latest)`

Unable to launch chromium on `Ubuntu Linux Server 14.04.5 LTS` (both the mentioned platform versions). I even tried to launch the chromium manually using the following command: `node_modules/puppeteer/.local-chromium/linux-499413/chrome-linux/chrome -v --headless --no-sandbox --disable-setuid-sandbox` 
But it doesn't start or launch. It just throws me back to the prompt. 

Times out every time with the following:
```
25 09 2017 13:56:19.075:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/build/
25 09 2017 13:56:19.076:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
25 09 2017 13:56:19.080:INFO [launcher]: Starting browser Chrome
25 09 2017 13:56:19.263:INFO [HeadlessChrome 0.0.0 (Linux 0.0.0)]: Connected on socket zDM7md2A7Je8kqsPAAAA with id 1679961
25 09 2017 13:58:19.552:WARN [HeadlessChrome 0.0.0 (Linux 0.0.0)]: Disconnected (1 times), because no message in 120000 ms.
HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
  Disconnected, because no message in 120000 ms.
```
**Note:** The same exact configuration works and runs all the tests perfectly on OSX without any problems. But unable to make it work on Ubuntu. 

Here are the related packages in my `package.json`:

 ```
 "karma": "1.7.1",
 "karma-chrome-launcher": "2.2.0",
 "karma-htmlfile-reporter": "0.3.5",
 "karma-jasmine": "1.1.0",
 "karma-junit-reporter": "1.2.0",
 "puppeteer": "0.11.0"
```
Here's my configuration:

```
const ChromiumRevision = require('puppeteer/package.json').puppeteer.chromium_revision;
const Downloader = require('puppeteer/utils/ChromiumDownloader');
const revisionInfo = Downloader.revisionInfo(Downloader.currentPlatform(), ChromiumRevision);

process.env.CHROME_BIN = revisionInfo.executablePath;
module.exports = function (config) {
    config.set({
        basePath: 'build/',
        frameworks: ['jasmine'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
        ],
        customLaunchers: {
            'ChromeHeadless': {
                base: 'Chrome',
                flags: [
                    '--headless',
                    '--disable-gpu',
                    // Without a remote debugging port, Google Chrome exits immediately.
                    '--remote-debugging-port=9222',
                    '--no-sandbox',
                    '--disable-setuid-sandbox'
                ],
                debug: true
            }
        },
        autoWatch: false,
        browsers: ['ChromeHeadless'],
        singleRun: true,
        browserNoActivityTimeout: 120000,
        urlRoot: '/build/'
    })
}
```

**Expected Result:** 
The Chrome headless should launch and the tests should run like they do on the Mac OSX. 

**Note:**
I have installed all the debian/linux dependencies which have been mentioned across all the other related issues. Looking for some suggestions and workarounds. Thank you. ✌️

**Comment by hparadiz** [comment]
Try updating to the latest puppeteer. You should have Chromium r503964 with puppeteer@0.12.0-alpha

**Comment by hparadiz** [comment]
What version of NSS do you have installed?

**Comment by applecool** [comment]
@hparadiz You mean `libnss3` ?

**Comment by applecool** [comment]
@hparadiz By the way I am unable to install the `0.12.0-alpha`.  On `npm install` I get the following:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for puppeteer@0.12.0-alpha
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
```

**Comment by hparadiz** [comment]
@applecool Yes, libnss3 needs to be at least version 3.26

npm install or npm update should push up to 0.12.0

I think you need to skip `-alpha` when using npm

**Comment by applecool** [comment]
@hparadiz The `libnss3` version is `3.28.4`. And I did skip the -alpha and tried it. Didn't work. :( I mean, its still giving me the same error, no matching version found for `puppeteer@0.12.0`. My npm version is `5.4.2`

**Comment by aslushnikov** [comment]
@applecool the `0.12.0-alpha` is not published to npm. It's a bleeding edge, you should be able to install it from github. However, I don't think it's necessary for this usecase, the `0.11.0` should be just good enough.

Regarding the linux box, try installing puppeteer without karma and just running some examples from `exampels/` folder. This should give you a better understanding of what's going on.

Also, make sure to sheck out the following resources:
- [Troubleshooting.md](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)
- #290 discussion

If this still doesn't work, please post to #290. There are a lot of people who have figured a lot of linux issues.
