### ISSUE TITLE
[Bug]: new .cache folder not opening Chrome

### ISSUE THREAD

**Issue by mo-rocks** [puppeteer/puppeteer#9164]
### Bug description

Steps to reproduce the problem:

1. composer require spatie/browsershot
2. npm install puppeteer
3. Call Browsershot with .pdf(), e.g. Browsershot::html(..some view..)->pdf();

Browsershot uses puppeteer under the hood, but puppeteer can't seem to find the Chromium that it downloaded into the .cache directory. Going into the node_modules/puppeteer folder and running npm install gives the output: 
"Chromium is already in [ ..local path.. ]\.cache\puppeteer\chrome\win64-1045629; skipping download."

Downgrading Puppeteer for v15.5 with no other changes fixes the probem.

### Puppeteer version

19.0.0

### Node.js version

19.0.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Error: Could not find expected browser (chrome) locally. Run npm install to download the correct Chromium revision (1022525)
```

**Comment by jrandolf** [comment]
I would run this by Browsershot since this is more of a compatibility issue with Browsershot and the latest version of Puppeteer.
