### ISSUE TITLE
Global navigation timeout? (useful for redirecting clicks and other similar events)

### ISSUE THREAD

**Issue by sradu** [puppeteer/puppeteer#917]
In phantom we could set up a default timeout across all requests. This is useful as sometimes performing certain actions trigger redirects and it's not always obvious when to waitForNavigation.

I think it would be useful to be able to set up a per page or a per browser timeout.

**Comment by aslushnikov** [comment]
@sradu I'm not sure I understand. Could you please give an example of phantom script?

**Comment by sradu** [comment]
Of course!

See resourceTimeout at http://phantomjs.org/api/webpage/property/settings.html, and potentially the http://phantomjs.org/api/webpage/handler/on-resource-timeout.html event.

Here is a random example I found on stackoverflow about this feature:
https://stackoverflow.com/questions/16854788/phantomjs-webpage-timeout

And another one:
https://github.com/ariya/phantomjs/issues/12180

While .goto and others have 'timeout' built in, redirects can happen on various events. For instance, a site could have three different checkboxes, and two of them are inline, and the third redirects to another page.

Having a default timeout ensures that the script won't hang.

**Comment by aslushnikov** [comment]
@sradu The [`page.setDefaultNavigationTimeout`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetdefaultnavigationtimeouttimeout) method was implemented and is available in puppeteer v1.0.0.

**Comment by sradu** [comment]
Thanks @aslushnikov! I noticed the commit, but from the docs I understood that it only affects the puppeteer methods like page.goto(), and not redirects done by the site.

I'll try it out!
