### ISSUE TITLE
[Bug]: using specific image urls makes the browser crash

### ISSUE THREAD

**Issue by orangecoloured** [puppeteer/puppeteer#9177]
### Bug description

Steps to reproduce the problem:

1. have Fedora 36
2. have `chrome-aws-lambda v10.1.0`
3. use this link as an `src` for image
```
https://res.cloudinary.com/practicaldev/image/fetch/s--eWHDNB9_--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/950352/5bd2098b-feaa-4f8e-8f8f-e3a8f5d17734.png
```
4. see `page.setContent` crashes

### Puppeteer version

puppeteer-core v10.1.0

### Node.js version

18.11.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
Error: Navigation failed because browser has disconnected!
    at /node_modules/puppeteer-core/src/common/LifecycleWatcher.ts:111:13
    at /node_modules/puppeteer-core/vendor/mitt/src/index.ts:88:75
    at Array.map (<anonymous>)
    at Object.emit (/node_modules/puppeteer-core/vendor/mitt/src/index.ts:88:56)
    at CDPSession.emit (/node_modules/puppeteer-core/src/common/EventEmitter.ts:102:18)
    at CDPSession._onClosed (/node_modules/puppeteer-core/src/common/Connection.ts:340:10)
    at Connection._onClose (/node_modules/puppeteer-core/src/common/Connection.ts:177:60)
    at WebSocket.<anonymous> (/node_modules/puppeteer-core/src/node/NodeWebSocketTransport.ts:50:38)
    at WebSocket.onClose (/node_modules/ws/lib/event-target.js:136:16)
    at WebSocket.emit (node:events:513:28)
```

**Comment by OrKoN** [comment]
chrome-aws-lambda has not been updated for a while.  v10.1.0 corresponds to 92.0.4512.0 which is not supported anymore. Also, note that chrome-aws-lambda builds are custom statically linked builds and might not work as expected. Do you reproduce the same issue using the latest version of Puppeteer and the bundled Chromium binary (without AWS Lambda)?

**Comment by orangecoloured** [comment]
> Do you reproduce the same issue using the latest version of Puppeteer and the bundled Chromium binary (without AWS Lambda)?

Hm, yeah, probably aws-lambda has nothing to do with it. Because locally, for debugging, the Chromium version the puppeteer installs is used.

**Comment by OrKoN** [comment]
@orangecoloured could you provide a script using the bundled Chromium version that demonstrates the problem?

**Comment by GordonHPepBoys** [comment]
> > Do you reproduce the same issue using the latest version of Puppeteer and the bundled Chromium binary (without AWS Lambda)?
> 
> Hm, yeah, probably aws-lambda has nothing to do with it. Because locally, for debugging, the Chromium version the puppeteer installs is used.

Have you found a solution to this? It looks like we are having the same issue.

**Comment by orangecoloured** [comment]
> Have you found a solution to this? It looks like we are having the same issue.

We moved to using [satori](https://github.com/vercel/satori).
