### ISSUE TITLE
[Bug]: style is not defined interfaces in puppeteer

### ISSUE THREAD

**Issue by zzzgit** [puppeteer/puppeteer#9185]
### Bug description

![image](https://user-images.githubusercontent.com/1060733/198581661-f09c3a45-75a7-4059-9dba-691a86fecadd.png)

I can't use `style` in Typescript. It will cause an error like this:

> Property 'style' does not exist on type 'Element'.ts(2339)

So, how to resolve it?

### Puppeteer version

newest

### Node.js version

newest

### npm version

newest

### What operating system are you seeing the problem on?

macOS

**Comment by zzzgit** [comment]
Anyone think it’s worth to concern?

**Comment by jrandolf** [comment]
Unrelated.

**Comment by zzzgit** [comment]
Is typescript officially supported in puppeteer?
