### ISSUE TITLE
[Bug]: Memory leak in `NetworkEventManager` causing crashes

### ISSUE THREAD

**Issue by Crunkle** [puppeteer/puppeteer#9186]
### Bug description

Using 18.0.5 but reproduced on a variety of versions with no resolution. It appears that navigating away from a page before it has finished loading causes request maps, such as `#requestWillBeSentMap`, to consume memory until the heap is exhausted.

```js
const browser = await puppeteer.launch(options);
const page = await browser.newPage();

await page.setRequestInterception(true);

page.on(
    'request',
    request => {
        const resourceType = request.resourceType();

        // Simple hook to remove any images or fonts
        if (resourceType === 'image' || resourceType === 'font') {
            request.abort();
        } else {
            request.continue();
        }
    },
);

// Navigate to and from URLs that trigger larger network requests
```

This is especially prevalent with larger payloads and often leads to a hard crash within a few hours. You may need to load a page that sends many large payloads to reproduce effectively.

### Puppeteer version

18.0.5

### Node.js version

16.18.0

### npm version

1.22.19 (Yarn)

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by OrKoN** [comment]
@Crunkle it'd be great if you could provide a test script that demonstrates the memory growth? The NetworkManager code indeed relies heavily on backend events and if events arrive in unexpected order that might lead to a memory leak.

**Comment by Crunkle** [comment]
Sure, I will try and get around to it this weekend. A simple page navigate loop should suffice.

**Comment by OrKoN** [comment]
@Crunkle thanks for the script! Unfortunately, I don't seem to be able to repro: `SHOULD_MEMORY_LEAK = true` my memory usage gets to the peak of 43.1 MB and stays the same (I ran the script for a few minutes). I am on Mac and Node 18.

**Comment by OrKoN** [comment]
@Crunkle do you run Puppeteer@19.2.2?

**Comment by Crunkle** [comment]
@OrKoN I was originally on 18 but am able to reproduce on the latest 19 release under Windows. I have not tested recently but can confirm this was an issue under Linux as well, but perhaps Chromium has updated since my last test. You may need to marginally increase the timeout to ensure the fetch is executed before navigate.

See [this video](https://giant.gfycat.com/CautiousSaltyGordonsetter.mp4) for a Windows demo.

**Comment by OrKoN** [comment]
Still not able to repro (tried different time outs up to 2000ms): in my case, if I look into the CDP log I get `Network.loadingFailed` events upon navigation that are handled by the network event manager and clears all local data. I wonder if you see those events in the CDP log too? ('env DEBUG=puppeteer:*')

**Comment by Crunkle** [comment]
I see one `Network.loadingFailed` per request being sent in the log, which I am guessing is the correct behavior. This event does not seem to trigger any clearing of the `#requestWillBeSentMap` though, at least for me, and the data is retained within. If you are still unsure then I can have a dig at the Puppeteer source myself to try and pinpoint the issue. I am pretty confident after testing in an isolated container that it is on the Puppeteer side, and I have a hunch #9283 is the same issue.

**Comment by OrKoN** [comment]
@Crunkle I wonder if `Network.loadingFailed` events are being only sometimes missed, causing the leak? It'd be hard to isolate the issue then. In general, copying the Network events in the order they arrive from the log into a test https://github.com/puppeteer/puppeteer/blob/main/test/src/NetworkManager.spec.ts#L39 should help to reproduce the issue.

**Comment by karthikuj** [comment]
Is there any update on this or any workarounds? I am also facing this issue.

I use the request interception feature for scope management in my project https://github.com/karthikuj/sasori
In a couple websites too many requests get stored in the heap and then it crashes with `JavaScript heap out of memory` error.

I am not sure why it only happens in a couple websites and not all of them :/

**Comment by OrKoN** [comment]
@karthikuj do you have an example to reproduce the leak? would you be able to add a test case to https://github.com/puppeteer/puppeteer/blob/9ec5f25ea6f9e60d250c7413e122a5c32faeb3f9/packages/puppeteer-core/src/cdp/NetworkManager.test.ts#L37 with the requests that you find leaking?

**Comment by karthikuj** [comment]
@OrKoN I don't have a clear understanding of why this is happening, and the website I found this on is a bit confidential, but I will try reproducing it with some testcase whenever I get the time.

**Comment by OrKoN** [comment]
Still not able to reproduce. If anyone is able to reproduce with a minimal example, please post it here or feel free to file a new issue.
