### ISSUE TITLE
Very slow performance when connected to VPN

### ISSUE THREAD

**Issue by eng3** [puppeteer/puppeteer#9189]
Background:  Win10 with HyperV with a Win10 VM and a linux/docker VM (with official node docker (lts-slim:latest) with xvfb based on https://github.com/beemi/puppeteer-headful).  Both are configured with PIA VPN (win10 using their app, linux/docker using openvpn)

See test code below:

```
const puppeteer = require('puppeteer')  // version 19.2.0

async function getpage() {
    const browser = await puppeteer.launch({ executablePath: process.env.PUPPETEER_EXEC_PATH, headless:false, args: ['--no-sandbox', '--disable-setuid-sandbox', '--font-render-hinting=none', '--disable-dev-shm-usage' ], ignoreDefautArgs: ["--enable-automation"]})
    const page = await browser.newPage()
    await page.setDefaultNavigationTimeout(0);
    console.log(new Date().toLocaleTimeString())
    await page.goto('https://www.stackoverflow.com', {waitUntil: 'networkidle0'})
    console.log(new Date().toLocaleTimeString())
    await page.close()
    await browser.close()
}

getpage()
```

 - Win10VM connected to VPN takes 3 seconds
 - dockerVM connect to VPN takes 132 seconds
 - dockerVM not connect to VPN takes  1 second

note that headless false/true does not seem affect time.

Since the Win10VM is fast, I don't think there is any issue with the VPN.  I've tried to curl a large file inside the docker with the VPN and I get fast speeds so I don't think its an issue with the container (or the VPN).  I've also tried a variety of different modern websites and get similar results some taking nearly 10min.

For some reason, puppeteer does not seem to like going through a vpn?

**Comment by OrKoN** [comment]
@eng3 I think the problem is somewhere in the docker/vpn as Chromium and Puppeteer don't have any special handling for VPNs.
