### ISSUE TITLE
Can executablePath be google-chrome-stable, not just chromium

### ISSUE THREAD

**Issue by zenxds** [puppeteer/puppeteer#919]
I'm writing a puppeteer tool, after package into an executable with [pkg](https://github.com/zeit/pkg), I got spawn chromium error。

so i want to use the installed google-chrome, after I pass the google-chrome-stable path find by `chrome-launcher/chrome-finder`, the launcher timeout。

Can executablePath must be chromium path ?

**Comment by aslushnikov** [comment]
@zenxds what kind of path do you pass in? It should be an actual path to the executable, so on MacOS it is something that ends with `Chromium.app/Contents/MacOS/Chromium`.

**Comment by zenxds** [comment]
@aslushnikov  if i pass a chrome path, such as `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`, not chromium path，i got a timeout from puppeteer

**Comment by Garbee** [comment]
Stable won't currently work since it doesn't have all the right API changes landed yet.

You need to use Dev Channel at the least currently to puppeteer to work well.

**Comment by chanlvh** [comment]
is there somewhere to track if those api changes landed on stable yet?
