### ISSUE TITLE
[Bug]: Content following a split image in PDF appears on wrong page.

### ISSUE THREAD

**Issue by Flamenco** [puppeteer/puppeteer#9191]
### Bug description

Steps to reproduce the problem:

1. Create a page with an image that will span more than 1 printed page
2. Add text below the image
3. Save as PDF

I seems the image is split correctly, but the destination page is not updated to reflect the additional pages created.

In the following screenshot, you can see the text should be placed on the page following the image.

SOURCE:

<img width="336" alt="Screenshot 2022-10-30 at 9 53 14 AM" src="https://user-images.githubusercontent.com/819940/198882307-dbaa9417-c493-4160-81b6-8f9fec2eadd1.png">

GENERATED:

<img width="483" alt="Screenshot 2022-10-30 at 9 52 54 AM" src="https://user-images.githubusercontent.com/819940/198882310-5a48bfec-62d1-46eb-a352-f9f256415ecd.png">

### Puppeteer version

19.2

### Node.js version

16

### npm version

8

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Does it happen with the regular print to PDF dialog in the headful browser?

**Comment by Flamenco** [comment]
It is running in a headless vm, so I am not currently able to check.  I did not see any related bugs posted to chromium, so I posted it here.

**Comment by jrandolf** [comment]
Could you provide a [mvce](https://stackoverflow.com/help/minimal-reproducible-example) in a separate repo?

**Comment by OrKoN** [comment]
I believe this might have been fixed in the latest Chromium (there were quite a few regression with the new printing layout algorithm). Please re-open if still happens.

**Comment by Flamenco** [comment]
@OrKoN Thanks for the update, I will add a note after I review.

**Comment by Flamenco** [comment]
Yes, fixed in latest chromium.  💯

**Comment by Flamenco** [comment]
I spoke too soon.  Still broken.

**Comment by OrKoN** [comment]
@Flamenco can you provide a test page?
