### ISSUE TITLE
[Bug]: border breaks / strange behavior with multipage tables

### ISSUE THREAD

**Issue by mvaDevelop** [puppeteer/puppeteer#9194]
### Bug description

Steps to reproduce the problem:

1. create a document with the following layout
[test.txt](https://github.com/puppeteer/puppeteer/files/9900228/test.txt)
2. display this document on a web page
3. save the document as a pdf
4. This results in border breaks of the table after certain page break(s) (see https://github.com/spiritix/php-chrome-html2pdf/issues/46)

### Puppeteer version

19.2.0

### Node.js version

v16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Does it reproduce if you use the browser's built-in print to PDF dialog?

**Comment by mvaDevelop** [comment]
Yes, it seems to add a border break on the second page (visually seems to be at the bottom of where the page header would end)

**Comment by OrKoN** [comment]
In that case, the issue is in the browser's PDF printing functionality and we'd need to open an issue on crbug.com to track that. Would you like to re-report the issue there?

**Comment by mvaDevelop** [comment]
> In that case, the issue is in the browser's PDF printing functionality and we'd need to open an issue on crbug.com to track that. Would you like to re-report the issue there?

Yes please

**Comment by OrKoN** [comment]
The issue can only be solved by the Chromium team: please report it at crbug.com if it persists in the latest version.
