### ISSUE TITLE
[Bug]: MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by Sed9yDataBank** [puppeteer/puppeteer#9195]
### Bug description

What did I do:

1. Implemented a Puppeteer API endpoint that launches 10 concurrent headless Chromium browsers at the same time to XYZ stuff, they run until I send another HTTP request to kill the processes related to each one of these browsers using `process.kill(chromePID)`.

What did you expect to happen:

1. No console warning or errors

What actually happened instead:

1. I get this warning when I start my node server and launch the 10 headless Chromium browsers 

```
(node:16511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected
```

Questions:

1. My script still operates well, but the warning is giving me bad vibes, can this actually cause memory leaks when I deploy this in a Docker container?

### Puppeteer version

v13.1.3

### Node.js version

v16.13.1

### npm version

v8.1.2

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```Shell
(node:16511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at process.addListener (node:events:487:10)
    at Object.addEventListener (/Users/blueish/Documents/puppeteer-work/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:97:13)
    at BrowserRunner.start (/Users/blueish/Documents/puppeteer-work/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:146:32)
    at ChromeLauncher.launch (/Users/blueish/Documents/puppeteer-work/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:113:16)
```

**Comment by OrKoN** [comment]
Please try using the latest Puppeteer version.

**Comment by meerawisniewski** [comment]
We have the same issue and updating Puppeteer did not fix the issue.

**Comment by OrKoN** [comment]
Could you provide a repro script?

**Comment by Sed9yDataBank** [comment]
> Please try using the latest Puppeteer version.

I will try using the latest Puppeteer version and get back to you.

For the repo script, I will check on that as well.

**Comment by julian-george** [comment]
Any updates on this? Getting the same problem while running a dozen or so puppeteer instances. I doubt an actual memory leak is happening, but launching a bunch of browsers at the same time must make nodejs think there is.

**Comment by SegoviaDanielDev** [comment]
[NODEJS - UBUNTU] -I detected the same issue, but also an active memory leak on Ubuntu 20.04.5 server. 

i execute a node child process which calls puppeteer to create pdf. after that, i'm trying to kill the process with proc.kill('SIGKILL') and it's returns false, and then the leak is on 

### child process who calls puppeteer
```
export const runChildProcess = async(fileName: string, data: string) =>
{
    let stdoutData: any = '';
    return await new Promise((resolve, reject) => {

        const controller = new AbortController();
        const { signal } = controller;

        const proc = fork(path.resolve(__dirname, fileName), ['child'], { signal });
        proc.send({data})

        proc.on('message', (data) => {
            if(data){
                stdoutData = data;
                proc.send({exit: true})
            }
            else {
                reject(`error on generate remito document`)
            }
        });
        proc.on('close', async (code) => {});
        proc.on('exit',  (code) => {
            console.log(new Date(), "- Subprocess finished with code:", code); //always 0

            const res = proc.kill('SIGKILL');
            console.log(new Date(), '- process deleted', res); //always false

            controller.abort();
            resolve(Buffer.from(stdoutData.data));
        });
    });
}
```

### the puppeteer code on filename fork process

```
async function createPDF(html:any) {
    try{
        const browser = await puppeteer.launch({
            // executablePath: '/usr/bin/google-chrome-stable',
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-accelerated-2d-canvas',
                '--no-first-run',
                '--no-zygote',
                '--single-process',
                '--disable-gpu',
                '--security-opt',
                '--disable-dev-shm-usage',
                '--disable-dev-shm-usage'
            ]
        });

        const page = await browser.newPage();
        await page.setContent(html.data, {
            waitUntil: 'domcontentloaded'
        })
        const pdf = await page.pdf({landscape: true});

        await page.close();
        await browser.close();

        console.log("generando doc", browser.process().pid) // try to kill this pid always throw exception

        return pdf;
    }
    catch(e){
        console.log(`${typesLogs.createFile}${typesLogs.remito} - ${bodyLogs.createFileErr} ${e.message}`, new Date());
        return null;
    }
}
```

### this code results the next memory leak without docker instance every invoces
![image](https://user-images.githubusercontent.com/52482005/212336105-6960cf70-54e7-4c3d-a77a-8284f91881f1.png)

**Comment by SegoviaDanielDev** [comment]
> ### Bug description
> What did I do:
> 
> 1. Implemented a Puppeteer API endpoint that launches 10 concurrent headless Chromium browsers at the same time to XYZ stuff, they run until I send another HTTP request to kill the processes related to each one of these browsers using `process.kill(chromePID)`.
> 
> What did you expect to happen:
> 
> 1. No console warning or errors
> 
> What actually happened instead:
> 
> 1. I get this warning when I start my node server and launch the 10 headless Chromium browsers
> 
> ```
> (node:16511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected
> ```
> 
> Questions:
> 
> 1. My script still operates well, but the warning is giving me bad vibes, can this actually cause memory leaks when I deploy this in a Docker container?
> 
> ### Puppeteer version
> v13.1.3
> 
> ### Node.js version
> v16.13.1
> 
> ### npm version
> v8.1.2
> 
> ### What operating system are you seeing the problem on?
> macOS
> 
> ### Configuration file
> _No response_
> 
> ### Relevant log output
> ```shell
> (node:16511) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
>     at _addListener (node:events:465:17)
>     at process.addListener (node:events:487:10)
>     at Object.addEventListener (/Users/blueish/Documents/puppeteer-work/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:97:13)
>     at BrowserRunner.start (/Users/blueish/Documents/puppeteer-work/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:146:32)
>     at ChromeLauncher.launch (/Users/blueish/Documents/puppeteer-work/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:113:16)
> ```

On Nodejs documentation (https://nodejs.org/api/events.html#emittersetmaxlistenersn), they says this: 

"By default EventEmitters will print a warning if more than 10 listeners are added for a particular event. This is a useful default that helps finding memory leaks. The emitter.setMaxListeners() method allows the limit to be modified for this specific EventEmitter instance. The value can be set to Infinity (or 0) to indicate an unlimited number of listeners.

Returns a reference to the EventEmitter, so that calls can be chained."

i guess it's not really a bug or something like that, it's only a little reminder

**Comment by seth2810** [comment]
For everyone who is still interested in:

https://github.com/puppeteer/puppeteer/blob/main/packages/browsers/src/launch.ts#L220-L229

**Comment by insanehong** [comment]
We have the same issue and updating Puppeteer did not fix the issue.

**Comment by OrKoN** [comment]
> It seems that the clearListeners method is not called in all cases when work with the browser is ended.
By the way, this may well be when it crashes or an error occurs while working with it

it is called when the browser process exit https://github.com/puppeteer/puppeteer/blob/main/packages/browsers/src/launch.ts#L220 To verify, run with `DEBUG=puppeteer:browsers:launcher` and look for a line `Browser process PID onExit`

I do not think it is a bug in Puppeteer. node just warns you if multiple handlers are attached for the same event and Puppeteer needs to attach a handler for each launched instance. So set the number of max listeners to the number of concurrent browser processes you plan to launch:

```
process.setMaxListeners(30); // e.g., if you launch fewer than 30 processes.
```
