### ISSUE TITLE
[Bug]: page.goto hangs, never returning

### ISSUE THREAD

**Issue by jribbens** [puppeteer/puppeteer#9196]
### Bug description

Steps to reproduce the problem:

1. `page.setRequestInterception(true)`
2. Add a `request` handler which calls `request.continue()` on the first request it sees but `request.abort()` on the second.
3. `page.goto()` a page which says `<script>window.location = 'something'`
4. puppeteer loads the first page, that request is allowed, it then tries to load the second page, that request is aborted, `page.goto` hangs forever and never returns.

Sample code to reproduce:

```javascript
'use strict'

const puppeteer = require('puppeteer')

async function test () {
  const browser = await puppeteer.launch()
  const context = await browser.createIncognitoBrowserContext()
  const page = await context.newPage()
  await page.setRequestInterception(true)
  page.on('request', (request) => {
    const url = new URL(request.url())
    if (request.isInterceptResolutionHandled()) return
    if (request.isNavigationRequest() &&
        request.frame() === page.mainFrame() &&
        url.pathname === '/') {
      console.log(`aborting ${url}`)
      request.abort('aborted', 0)
    } else {
      console.log(`allowing ${url.href}`)
      request.continue(request.continueRequestOverrides(), 0)
    }
  })
  console.log('requesting page')
  // the following URL contains "<script>window.location='/'</script>"
  await page.goto('https://unequivocal.eu/location.html')
  console.log('page loaded')
  await context.close()
  await browser.close()
}

test()
```

### Puppeteer version

19.2.0

### Node.js version

16.14.0

### npm version

8.3.1

### What operating system are you seeing the problem on?

Linux, Windows

### Relevant log output

```Shell
requesting page
allowing https://unequivocal.eu/location.html
aborting https://unequivocal.eu/
... hangs ...
```

**Comment by jribbens** [comment]
Doing `request.continue({ url: 'data,' }, 0)` as an alternative method of 'aborting' the request also causes a hang. But `request.continue({ method: 'HEAD' }, 0)` doesn't hang.

**Comment by OrKoN** [comment]
It looks to be the same as https://github.com/puppeteer/puppeteer/issues/9175 Could you please confirm?

**Comment by jribbens** [comment]
It looks like it almost certainly is, yes. It will be proven when 19.2.1 is released, if it fixes my problem ;-)
