### ISSUE TITLE
Running with chrome rather than chromium [Ubuntu]

### ISSUE THREAD

**Issue by zerosdev** [puppeteer/puppeteer#9197]
### Bug description

Steps to reproduce the problem:

1. Set executablePath to /usr/bin/google-chrome

It works fine when there is no executablePath. But I want to launch Chrome instead of Chromium. When executablePath fills up, Chrome launches but just a white screen and then force closes

### Puppeteer version

13.0.1

### Node.js version

16.18.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
0|app      |     at /home/ubuntu/Desktop/my-project/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230:24
0|app      |     at new Promise (<anonymous>)
0|app      |     at CDPSession.send (/home/ubuntu/Desktop/my-project/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:16)
0|app      |     at Page._initialize (/home/ubuntu/Desktop/my-project/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:177:26)
0|app      |     at Function.create (/home/ubuntu/Desktop/my-project/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:169:20)
0|app      |     at /home/ubuntu/Desktop/my-project/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:73:88
0|app      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|app      |     at async Promise.all (index 0)
0|app      |     at async BrowserContext.pages (/home/ubuntu/Desktop/my-project/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:494:23)
0|app      |     at async Promise.all (index 0) {
0|app      |   originalMessage: ''
0|app      | }
```

**Comment by jrandolf** [comment]
Please try with the latest version of puppeteer.

**Comment by zerosdev** [comment]
> Please try with the latest version of puppeteer.

Hi, I'm trying to upgrade my puppeteer version to the latest one and set the executablePath as follows

executablePath: process.platform === 'linux' ? '/usr/bin/google-chrome' : 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';

But still can't launch chrome, open then force close
Btw I tested the new code on local with Windows but I think it will also work on Ubuntu VPS if it works on local. Is there a mistake?

**Comment by OrKoN** [comment]
@zerosdev you need to make sure that the executablePath is correct and that the chrome version you have is compatible with [the version of Puppeteer](https://pptr.dev/chromium-support) you are using. Also, make sure that the Chrome is not running as it might prevent it from being started by Puppeteer.

**Comment by zerosdev** [comment]
I finally found the troublemaker, it's because the --single-process, btw what is this for? What is the effect when I use it or when I don't use it?

**Comment by zerosdev** [comment]
Is it like it will consume more RAM if I don't use it? Btw I want to run multiple chrome windows at the same time

**Comment by jrandolf** [comment]
I'm not sure this is related to the flag you mentioned. 

See https://superuser.com/questions/654565/how-to-run-google-chrome-in-a-single-process for more information on that flag.

This looks like a problem of your Chrome version being incompatible with Puppeteer. Could you tell us your Chrome version?
