### ISSUE TITLE
mutation example?

### ISSUE THREAD

**Issue by ramusbucket** [puppeteer/puppeteer#920]
I'm not able to understand `page.waitForFunction(pageFunction[, options[, ...args]])` 

is `pageFunction` a predicate/condition to wait for? if yes, then I do not understand what the Polling of it means. If I use `{ polling: 'mutation' }` - it says it will execute `pageFunction` on every DOM mutation. So this is confusing for me. 

Let's say I want to get do this - 
`page.waitForFunction(DoSomeWork, { polling: 'mutation' });` Will that call DoSomeWork function everytime there is a DOM mutation?  if yes, any example to get the DOM changes only?

```
let value = await page.waitForFunction((x) => document.querySelector(x).textContent, { polling: 'mutation' }, selector);
console.log(value);
```

Even after there are many changes on the pages, I don't see anything printed on console.

**Comment by ramusbucket** [comment]
As I understand this `waitForFunction` seems to b a misnomer. I can understand `waitForNavigation`, `waitFor(Selector...)` to be loaded in the DOM but `waitForFunction(...)` does not appeal. IMHO, `waitForFunction` should be in `evaluate`. For example, `evaluate(function, [onPollingInterval or 
mutation])` - second argument is optional. If second argument is not provided, instant evaluation happens.

**Comment by aslushnikov** [comment]
> is pageFunction a predicate/condition to wait for? if yes, then I do not understand what the Polling of it means.

It is a predicate. The `polling` predicate defines how often should puppeteer check for the condition. The `polling: 'mutation'` means that the predicate will be evaluated on every dom mutation. The `polling: 'raf'` means that the predicate will be evaluated on every animation frame.
