### ISSUE TITLE
[Bug]: Angular builds failing due to puppeteer package.json missing export install.js

### ISSUE THREAD

**Issue by tusharpatil2912** [puppeteer/puppeteer#9215]
### Bug description

Getting below error in our Angular 12.0.2 application since yesterdays new puppeteer v19.2.1 release.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/node/install.js' is not defined by "exports" in......../node_modules/puppeteer/package.json
at applyExports (internal/modules/cha/loader.js:491:9)

### Puppeteer version

19.2.1 & 19.2.2

### Node.js version

12.18.2

### npm version

6.14.5

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/node/install.js' is not defined by "exports" in......../node_modules/puppeteer/package.json
at applyExports (internal/modules/cha/loader.js:491:9)
```

**Comment by OrKoN** [comment]
Node 12 is not supported anymore. Please make sure you use at least node 14 and a recent version of NPM.

**Comment by tusharpatil2912** [comment]
@OrKoN Thanks for the quick reply.
As per your suggestion I tried using node v14.18.3 but still I'm getting same error. 
Adding to that, we didn't made any code changes, the build was working for same code without any error before few days with node 12, now with same code, the build is failing since puppeteer 19.2.1 release.

**Comment by OrKoN** [comment]
@tusharpatil2912 do you clean and re-install node_modules? In 19.2.1 there was nothing released that could have solved it. Are you using jest? https://pptr.dev/troubleshooting#cannot-find-module-puppeteer-coreinternal

**Comment by OrKoN** [comment]
Also, did you update npm? `npm i npm -g`?
