### ISSUE TITLE
[Bug]: puppeteer doesn't download local-chrome since v18.0.0

### ISSUE THREAD

**Issue by JiPaix** [puppeteer/puppeteer#9219]
### Bug description

Steps to reproduce the problem:

1. `npm install puppeteer`
2. use default settings (no executable path)
3. **Get Error**: _Unable to launch browser, error message: An `executablePath` or `channel` must be specified for `puppeteer-core`_
4. **check** `/node_modules/puppeteer/.local-chromium`, its empty

[v17.1.3](https://github.com/puppeteer/puppeteer/releases/tag/v17.1.3) and previous versions are working fine.

### Puppeteer version

19.2.2

### Node.js version

18.12.0

### npm version

8.19.3

### What operating system are you seeing the problem on?

Linux

### Configuration file

```JavaScript
const { env } = require('process');
const { resolve } = require('path');

module.exports = {
  userDataDir: resolve(env.USER_DATA, '.cache', 'puppeteer'),
  headless: env.MODE === 'development' ? false : true,
  args: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-infobars',
    '--window-position=0,0',
    '--ignore-certifcate-errors',
    '--ignore-certifcate-errors-spki-list',
    '--disable-gpu',
  ],
}
```

### Relevant log output

```Shell
Unable to launch browser, error message: An executablePath or channel must be specified for puppeteer-core.
```

**Comment by xcbaojian** [comment]
![image](https://user-images.githubusercontent.com/96899734/200150558-e36be240-839c-4992-a2e9-f3220d14e000.png)
hi i think this can helf for you
