### ISSUE TITLE
path to run chrome wrong

### ISSUE THREAD

**Issue by matheustorsani** [puppeteer/puppeteer#9220]
### Bug description

I use linux, and for some reason, the chrome execution path is like windows, check it out
![image](https://user-images.githubusercontent.com/68620332/200131685-3999c305-63b3-42c2-ac9e-f969b2e43bed.png)

### Puppeteer version

latest

### Node.js version

19.0.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

**Comment by matheustorsani** [comment]
i tried putting executePath to `/usr/share/applications/google-chrome.desktop`, it gave access denied.
(im new to linux)

**Comment by jrandolf** [comment]
From looking at your terminal, it looks like you are using a windows terminal, not a Linux terminal.

We recommend posting this in Stackoverflow.
