### ISSUE TITLE
[Bug]: centos 无法启动 Puppeteer

### ISSUE THREAD

**Issue by Alifetimelove** [puppeteer/puppeteer#9229]
### Bug description

Steps to reproduce the problem:

1. Error: Failed to launch the browser process!
2. ../../base/allocator/partition_allocator/partition_address_space.cc(63) Check failed: false
3. TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

### Puppeteer version

^13.0.1

### Node.js version

v16.17.1

### npm version

8.15.0

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```Shell
0|npm star | Error: Failed to launch the browser process!
0|npm star | ../../base/allocator/partition_allocator/partition_address_space.cc(63) Check failed: false
0|npm star | 
0|npm star | 
0|npm star | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|npm star | 
0|npm star |     at onClose (/usr/project/5.0/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
0|npm star |     at Interface.<anonymous> (/usr/project/5.0/puppeteer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
0|npm star |     at Interface.emit (node:events:539:35)
0|npm star |     at Interface.close (node:internal/readline/interface:529:10)
0|npm star |     at Socket.onend (node:internal/readline/interface:258:10)
0|npm star |     at Socket.emit (node:events:539:35)
0|npm star |     at endReadableNT (node:internal/streams/readable:1345:12)
0|npm star |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by jrandolf** [comment]
Please use the latest version of Puppeteer.

**Comment by boardmain** [comment]
same problem with the last

**Comment by jrandolf** [comment]
Please provide a MVP (minimal viable product).

**Comment by xcbaojian** [comment]
我的是ubuntu ，我和你一样也出了类似 问题吧。
这个问题是路径 的问题。Puppeteer 19.0以后。它的路径是存在根目录下的.cache里。你在linux下路径 要设置这个路径 ，不然不是调不出来浏览器的。

**Comment by xcbaojian** [comment]
我觉得这个团队自从弄了这个更新以后，linux的玩家，一大堆的问题在issue里了。

**Comment by Alifetimelove** [comment]
Update to puppeteer, the same problem

**Comment by Alifetimelove** [comment]
> 我的是ubuntu ，我和你一样也出了类似 问题吧。 这个问题是路径 的问题。Puppeteer 19.0以后。它的路径是存在根目录下的.cache里。你在linux下路径 要设置这个路径 ，不然不是调不出来浏览器的。

可以详细描述一下嘛？
