### ISSUE TITLE
setUserPreferences on puppeteer?

### ISSUE THREAD

**Issue by floydtagle** [puppeteer/puppeteer#923]
How to set setUserPreferences on puppeteer? Like download.default_directory, download.directory_upgrade, download.prompt_for_download and plugins.always_open_pdf_externally? Please help... Thanks..

**Comment by vsemozhetbyt** [comment]
@floydtagle You can set them manually using `userDataDir` in the [`puppeteer.launch()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) with a pre-defined profile.

**Comment by floydtagle** [comment]
Thanks! Its not that easy but thanks anyway.. @vsemozhetbyt
