### ISSUE TITLE
[Bug]: puppeteer.DEFAULT_INTERCEPT_RESOLUTION_PRIORITY is undefined

### ISSUE THREAD

**Issue by dukei** [puppeteer/puppeteer#9236]
### Bug description

Steps to reproduce the problem:

1. Try to enable cooperative request interception by using DEFAULT_INTERCEPT_RESOLUTION_PRIORITY as doc says: https://pptr.dev/guides/request-interception/
2. Cooperative request interception is not enabled, because it turns out that DEFAULT_INTERCEPT_RESOLUTION_PRIORITY is undefined!

the following code outputs `undefined`
```typescript
import puppeteer from "puppeteer";
console.log(puppeteer.DEFAULT_INTERCEPT_RESOLUTION_PRIORITY);
```

test project is attached
[test-puppeteer.zip](https://github.com/puppeteer/puppeteer/files/9972985/test-puppeteer.zip)

### Puppeteer version

19.2.2

### Node.js version

16.16.0

### npm version

8.11.0

### What operating system are you seeing the problem on?

Windows

**Comment by jrandolf** [comment]
@OrKoN PTAL

**Comment by Condence** [comment]
de momento usen 

npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list
