### ISSUE TITLE
Erratic screenshots (rectangular area not 'painted'). Potential bug. Only happens with headless=true

### ISSUE THREAD

**Issue by geertbrit** [puppeteer/puppeteer#926]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0 (also on 0.10.x)
* Platform / OS version: Macbook Pro Retina early 2015 / OS X Yosemite 10.10.5
* URLs (if applicable): http://bbc.com

**What steps will reproduce the problem?**

Running the following snippet wil reproduce the problem. NOTE: the problem is erratic; sometimes it will exhibit the correct behavior. 

```
const puppeteer = require('puppeteer');

(async() => {

  const browser = await puppeteer.launch({ headless: true });

  const page = await browser.newPage();
  await page.goto("http://bbc.com");
  await page.evaluate(() => window.scrollBy(0, document.body.clientHeight));
  // await page.setViewport({ width: 1280, height: 1024 }); //uncommenting seems to expose the erratic behavior more often
  await page.screenshot({ fullPage: true, path: 'screenshot.png' });

  await browser.close();

})();


```
**What is the expected result?**

Doing a fullpage screenshot should result in a complete screenshot of the page without rectangular areas that are not 'painted'.

**What happens instead?**

There's an erratic issue with the produced screenshot, clearly visible at the bottom of the screenshot (the footer of bbc.com homepage). It appears as if chrome doesn't do a complete paint, which results in a rectangular area to be entirely white. 

Note: this only happens when using `{headless:true}`. Doing `{headless:false}` produces the correct result. 

I included 2 screenshots, please check the bottom of the screenshots for the clear difference. To be clear: I'm NOT concerned with images that not have been loaded. Also: using `{headless: true}` produces different results each time. In about 10% of cases I'm getting a correct result. The other 90% differ from a screenshot as shown (a rectangular area missing from the paint) to the footer not displayed at all. 

I have not seen this with any other page and I've checked quite a few. Looking at the bbc.com source, I can't see a clear reason why this specific one is failing.

**Screenshot showing the CORRECT behavior (`{headless:true: false}`)**

![bbc headless false correct](https://user-images.githubusercontent.com/393259/31056757-65d1b65a-a6d7-11e7-933c-b4f3f80d53fd.png)

**Screenshot showing the ERRATIC behavior (`{headless:true}`)**

![bbc headless true erratic](https://user-images.githubusercontent.com/393259/31056741-2c2ae8fe-a6d7-11e7-8293-bc99fb1f8ba1.png)

**Comment by geertbrit** [comment]
Showing only the footers for easy comparison. Note: the trailing white in the incorrect screenshot is actually part of the actually produced screenshot. This leads me to think that even in the erratic case the dimensions are properly determined, it's just that the entire viewport is not completely 'painted in'. 

**correct `{headless: false}`**

![screen shot 2017-10-01 at 18 42 55](https://user-images.githubusercontent.com/393259/31056809-5f7590e6-a6d8-11e7-8560-f8e47823a049.png)



**incorrect `{headless: true}`**

![screen shot 2017-10-01 at 18 43 48](https://user-images.githubusercontent.com/393259/31056829-7d53c0ec-a6d8-11e7-95d5-c00acfb1428d.png)

**Comment by vsemozhetbyt** [comment]
FWIW, `window.scrollBy(0, document.body.clientHeight)` would be more effective.
```js
> document.documentElement.clientHeight
413
> document.body.clientHeight
7653
```

**Comment by geertbrit** [comment]
@vsemozhetbyt , yep you're correct. I'll update. Doesn't make a difference for this problem though.

**Comment by valstu** [comment]
I'm having exactly the same issue at the moment. Tested both v0.11 and 0.12-alpha.

**Comment by geertbrit** [comment]
probably similar to #477

**Comment by geertbrit** [comment]
Taking multiple clipped screenshots and stitching them together as per https://github.com/GoogleChrome/puppeteer/issues/933 seems to have solved things. 

Got good results using [sharp ](https://github.com/lovell/sharp) for stitching

**Comment by aslushnikov** [comment]
> Taking multiple clipped screenshots and stitching them together as per #933 seems to have solved things.

This seems to be giving page enough time to render.

Dupe of #477.

**Comment by geertbrit** [comment]
@aslushnikov I'm satisfied with the workaround but still curious to the underlying reason (and a potential way to fix properly): 

> This seems to be giving page enough time to render.

Is it that the chrome is rasterizing the screen at a certain frames/sec but the screen it too large for the cpu to keep up or something?

**Comment by aslushnikov** [comment]
@gebrits rasterization is done in chunks, and we don't wait enough time for rasterizer to complete
