### ISSUE TITLE
[Bug]: Weird behavior when using bundled Chromium in non-headless mode

### ISSUE THREAD

**Issue by KMatuszak** [puppeteer/puppeteer#9263]
### Bug description

Page.click throws an error in non-headless mode if another maximized window is covering browser window. This doesn't happen if browser window is focused or just covered by another window that is not maximized, or in headless mode. Also `waitForSelector` before `click` passes fine. Additionally, this problem does not occur when I set `executablePath` to `C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe`, so it seems to be a problem with the bundled Chromium version.

Chromium version:
![image](https://user-images.githubusercontent.com/86327285/201551257-953ae787-6960-4e6a-8144-27b3f02bcccc.png)

Edge version:
![image](https://user-images.githubusercontent.com/86327285/201551269-6f25453a-fa75-4325-8d89-e832c4fd6a54.png)

Windows version:
![image](https://user-images.githubusercontent.com/86327285/201551281-d0103386-29d3-40ad-9d5d-01869f5c7edf.png)

### Puppeteer version

19.2.2

### Node.js version

19.0.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

Windows

### Configuration file

```JavaScript
without config
```

### Relevant log output

```Shell
Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (...\node_modules\puppeteer-core\src\common\ElementHandle.ts:547:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ElementHandle.click (...\node_modules\puppeteer-core\src\common\ElementHandle.ts:637:20)
    at IsolatedWorld.click (...\node_modules\puppeteer-core\src\common\IsolatedWorld.ts:340:5)
    at Timeout._onTimeout (...\src\Main.ts:165:5)
```

**Comment by Lightning00Blade** [comment]
@KMatuszak Tried reproducing this issue on my Linux machine without success, likely Windows only bug. Can you provide a minimal reproducible code where this happens in the meantime, to verify against?
