### ISSUE TITLE
[Bug]: Puppeteer launch intermittently fails due to browser not being downloaded

### ISSUE THREAD

**Issue by viditganpi** [puppeteer/puppeteer#9274]
### Bug description

This happens intermittently, where the puppeteer fails to launch with browser not downloaded error. There is no specific setup or steps to reproduce this, though.

Steps to reproduce the problem:

1. 

### Puppeteer version

2.1.1

### Node.js version

16.10.0

### npm version

7.24.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```Shell
Error: Browser is not downloaded. Run "npm install" or "yarn install"
ERR!     at ChromeLauncher.launch (<Path to workspace>\.store\puppeteer@2.1.1-65456f516912b7650b9a\node_modules\puppeteer\lib\Launcher.js:236:15)
```

**Comment by jrandolf** [comment]
Please follow the issue template for filling out a bug.
