### ISSUE TITLE
[Bug]: Puppeteer launch intermittently fails due to browser not being downloaded

### ISSUE THREAD

**Issue by viditganpi** [puppeteer/puppeteer#9275]
### Bug description

Steps to reproduce the problem:

```js
import { Page } from "puppeteer";
export const generateStyles = async () => {
  const puppeteer = require("puppeteer");
  const browser = await puppeteer.launch({
    args: ["--single-process"],
    headless: true,
  });
  const page = await browser.newPage();
  await page.addScriptTag({
    path: <some path>,
  });
  await Promise.all([
    // some method execution
    page.addScriptTag({ path: "<some path>" }),
  ]);
  await browser.close();
};
```
This will fail intermittently on launch

### Puppeteer version

2.1.1

### Node.js version

16.10.0

### npm version

7.24.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```Shell
Error: Browser is not downloaded. Run "npm install" or "yarn install"
ERR!     at ChromeLauncher.launch (<Path to workspace>\.store\puppeteer@2.1.1-65456f516912b7650b9a\node_modules\puppeteer\lib\Launcher.js:236:15)
```

**Comment by OrKoN** [comment]
Hey, puppeteer@2.1.1 is not supported anymore. Please try using the latest version and see https://pptr.dev/guides/configuration if you want to change the default cache folder.

**Comment by viditganpi** [comment]
@OrKoN I updated the puppeteer version to `18.1.0` the issue still did not resolve the issue, and this is failing intermittently

**Comment by OrKoN** [comment]
@viditganpi the latest version is 19.4.0 though. Feel free to update this issue with the reproduction details for the latest puppeteer version and include the npm logs for the installation.

**Comment by viditganpi** [comment]
Updating to the latest version, is not a possibility due to dependency on jest, but this version, should also work well right?

**Comment by OrKoN** [comment]
@viditganpi it should work yes, but if it only happens in that version and does not happen in the latest, we are not going to fix it. Could you create a fresh project, install puppeteer@18.1.0 there and run a basic script? If that works, it means that there is some problem with your specific set up.
