### ISSUE TITLE
[Bug]: No proper types for `$eval` and `$$eval`

### ISSUE THREAD

**Issue by max-programming** [puppeteer/puppeteer#9280]
### Bug description

In TypeScript, if I try to use the `$eval` or `$$eval` method, it does not let me type the element correctly.

I can't type it explicitly and I also can't pass it in a generic.

Different Situations:

> When no types are used
![image](https://user-images.githubusercontent.com/51731966/202220713-ef254830-326b-47c5-af6c-8853ea8c5c1d.png)

> When a generic is used
![image](https://user-images.githubusercontent.com/51731966/202220809-309c38e4-5abb-4af4-95e9-5c29251b4be3.png)

> When explicit types are used
![image](https://user-images.githubusercontent.com/51731966/202220912-8027396d-7d5f-419e-8c39-2208900e3a48.png)

### Puppeteer version

19.2.2

### Node.js version

16.17.1

### npm version

8.15.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
I believe the docs got outdated here: the recommended way is to cast/typecheck the element: e.g., `el => (el as HTMLInputElement).value` or `if (el instanceof HTMLInputElement) { // action } else { //error }`. In some cases Puppeteer can infer the type based on the selector but not in this case. The generic approach was less safe and we moved away from it.

**Comment by max-programming** [comment]
@OrKoN The `as` and `instanceof` definitely works. But is not efficient.

It adds up to more extra code that could be fixed with explicit typings.

**Comment by OrKoN** [comment]
Documented in https://pptr.dev/guides/query-selectors#css
