### ISSUE TITLE
[Bug]: Bundled Chromium ignore policy directory from which non-bundled Chromium loads policy

### ISSUE THREAD

**Issue by ldrahnik** [puppeteer/puppeteer#9282]
### Bug description

Steps to reproduce the problem:

1. `npm install puppeteer`
2. create file in `/etc/chromium-browser/policies/managed/`, in my case `foo.json` `{
  "AutoSelectCertificateForUrls": ["{\"pattern\":\"*\",\"filter\":{\"ISSUER\":{\"CN\":\"I.CA Public CA/RSA 07/2015\"}}}"]
}`
3. when I start chromium in standard way policy is loaded and used, means `const browser = await puppeteer.launch({` with line `executablePath: '/usr/bin/chromium-browser'` but when is line with setting parameter executablePath missing, is used bundled Chromium and policy is not loaded

### Puppeteer version

19.2.2

### Node.js version

v14.21.1

### npm version

6.14.17

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
The documentation seems to suggest a different path: https://www.chromium.org/administrators/linux-quick-start/#set-up-policies have you tried it?

**Comment by ldrahnik** [comment]
My bad, `/etc/chromium/policies/managed/foo.json` works for bundled
