### ISSUE TITLE
[Bug]: Chrome browser requests leak memory when running with Puppeteer

### ISSUE THREAD

**Issue by SLKnutson** [puppeteer/puppeteer#9283]
### Bug description

Steps:
1. Load a page in Chrome using puppeteer
1. Start executing requests from that page.
1. After about 30 seconds, you will see `Chromium Helper (Renderer)` memory starting to tick up by ~ 0.5 megabytes/second

Seems to happen on Mac and Windows.
Doesn't seem to happen in Firefox. Doesn't seem to happen if you disconnect puppeteer after setup.

Reproduction (run in node, requires Puppeteer):
```
require('http')
  .createServer(function (request, response) {
    console.log('received request');
    response.end('booyah');
  })
  .listen(20547);

const runPuppeteer = async () => {
  const browser = await require('puppeteer').launch();
  const page = await browser.newPage();

  const html = `<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
    <script>
      setTimeout(async () => {
        console.log('starting fetching');
        while (true) {
          await fetch('http://localhost:20547/anything', {mode: 'no-cors'});
        }
      }, 100);
    </script>
  </body>
</html>
`;
  await page.setContent(html);
};

runPuppeteer();

// Make run forever
setTimeout(() => {
  console.log('done');
}, 100000000);

```

### Puppeteer version

19.2.2, think it is present in older versions too

### Node.js version

18.11.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
Sounds a lot like https://github.com/puppeteer/puppeteer/issues/9186 Probably network manager is leaking some request content.

**Comment by SLKnutson** [comment]
When I remove the `.send('Network.enable')` command from NetworkManager, I no longer have this issue. Sending `'Network.disable'` afterwords also works, but I don't know of any way to get the CDPSession for the page without manually modifying puppeteer.
It seems like the memory is leaking within Chrome itself when the network is enabled. I don't see anything in the Chrome DevTools Protocol about disposing of requests. Does it just hold onto them indefinitely?

**Comment by OrKoN** [comment]
there is `page._client()` I think, although it's an internal method, it should not require modifying puppeteer. So you are saying that if you invoke `Network.disable` after requests have been made, the memory gets freed? Chrome definitely has a cache for all network requests because you can get request data `Network.getResponseBody` but I don't think holds onto them indefinitely. That should be also configurable via Network.enable params although Puppeteer uses the default configuration: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-enable

**Comment by SLKnutson** [comment]
I'm using `Network.disable` proactively, calling it once right after I open the page. It looks like that clears out any existing request data and stops any more from being held onto.

I think chrome must otherwise hold onto requests indefinitely. I took a quick look at the chromium codebase, but I didn't see an obvious spot confirming that. I can see that being a good default for use with automated testing, but for long-running production instances it is problematic.

**Comment by Crunkle** [comment]
I believe this is the same issue as #9186. You should check the [memory usage with inspector](https://nodejs.org/en/docs/guides/debugging-getting-started/) to find the leak location.

**Comment by SLKnutson** [comment]
I don't think this is something you can debug with the memory usage inspector because the leak occurs in the chrome process itself, not javascript.

**Comment by gregg-cbs** [comment]
i am noticing this slow memory leak when deploying a small puppeteer server to digital ocean:
![image](https://github.com/puppeteer/puppeteer/assets/57114335/074fe682-f2b3-4a34-98e0-aecc66f46db9)

i am trying to work around this and looking for any solutions if anyone has.

**Comment by OrKoN** [comment]
@gregg-cbs memory usage might not be a problem on its own, the memory might get released later, e.g., if it becomes really low. Do you actually see out of memory crashes or swapping?

**Comment by gregg-cbs** [comment]
> @gregg-cbs memory usage might not be a problem on its own, the memory might get released later, e.g., if it becomes really low. Do you actually see out of memory crashes or swapping?

No I have not seen that yet because i keep restarting the server to reduce ram consumption. The ram is on 73%, up 2% from yesterday.

My worry is that I dont have much ram left to operate with and this server is expected to do quite a lot of processing so if without any computations we are sitting at 70-80% ram usage then what is going to happen when traffic starts coming and the server has to work? 

This server is going to fall over for sure because if I test this locally and process 100 pages to pdf the ram spikes up to 360mbs, this box only has 51mbs spare.

**Comment by OrKoN** [comment]
@gregg-cbs there is not reason for the server not to use available memory so pure memory usage is not a good stat (e.g., Linux caches files by default so generally the memory usage always grows but the memory can be freed up if needed), the OS and v8 would free up memory as soon as it is needed for something. In general, if you open a page/do things/close the page and do not have many concurrent pages open, it should be alright. In general, 512mb is not much for a browser dealing with many pages at once. So you want to rate limit. Also, you can stress test this locally and see if there are any out of memory errors.  Additional tip is to use `browser.createBrowserContext` to isolate the pages even better.

**Comment by gregg-cbs** [comment]
> Each open tab requires at least 30-40 MB of memory, so you cannot open 30 pages at the same time on that server. You need to make sure that you only process 1 (or N) pages at a time and queue other HTTP requests.

Yesterday was emotional. I changed the puppeteer server to have a queue and to response via a webhook. So now i process 3 pdfs at a time ensuring i only use x amount of ram. That was a nice and necessary change so thank you for the suggestion.

The ram leak is still apparent and will catch me out at some point so I will have to investigate chrome versions and linux stuff to see how to alleviate it.

**Comment by OrKoN** [comment]
I played with the example a little more and although I see the memory increase in Chrome, I think it is expected since CDP retains request data to implement methods like https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-getResponseBody that provide network data after responses completed.

I believe Chrome will clean it up if it runs low on memory and I do not think it will cause crashes.

Re-opening a page would also force release network data:

```
const puppeteer = require('puppeteer');

async function main() {
  require('http')
    .createServer(function (request, response) {
      console.log('received request');
      response.end('booyah');
    })
    .listen(20547);

  const browser = await require('puppeteer').launch();
  let page = await browser.newPage();

  const runPuppeteer = async () => {
    await page?.close();
   page = await browser.newPage();
    const html = `<!DOCTYPE html>
  <html lang="en">
    <head></head>
    <body>
      <script>
        setTimeout(async () => {
          console.log('starting fetching');
          while (true) {
            await fetch('http://localhost:20547/anything', {mode: 'no-cors'});
          }
        }, 100);
      </script>
    </body>
  </html>
  `;
    await page.setContent(html);
  };

  runPuppeteer();

  setInterval(() => {
    runPuppeteer();
  }, 10000);

  // Make run forever
  setTimeout(() => {
    console.log('done');
  }, 100000000);
}

main()
```

**Comment by gregg-cbs** [comment]
@OrKoN - Thats what you/someone said "I believe Chrome will clean it up if it runs low on memory and I do not think it will cause crashes." - I can confirm memory and disk space is not released and I have experience both disk and memory full issues.

I cant remember what I did but i have solved the memory issue, i think i disabled some chrome functionality with args.

File space still becomes an issue because of dev profiles not being deleted and it seems the only way to clear dev profiles is to run a bash script every day that removes all profiles. On my server I ran through 24GBs of space because of this issue.

**Comment by OrKoN** [comment]
@gregg-cbs the clean up of the profile should be happening on the browser process exit https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/node/BrowserLauncher.ts#L114 in the normal course of action, is it not invoked for you?  (disk issue is a different our though)

**Comment by gregg-cbs** [comment]
Looking at my code im not doing a browser exit after every page completion because the overhead of opening and closing the browser for every request is too much for my little server.

So what i do is shut down the browser every 2 hours. However this does not alleviate the file space issue and looking at the code suggested by this [comment](https://github.com/puppeteer/puppeteer/issues/1791#issuecomment-1969252626) i dont think thats going to solve my problem either.

However this thread is for the memory leak so lets keep the discussion of disk space issue at the appropriate thread over [here](https://github.com/puppeteer/puppeteer/issues/6414#issuecomment-2313252612)

**Comment by Jo5h** [comment]
So I have been working on a scraper that even after aggressively calling the Bun.gc() and setting everything to undefined after returning, was still leaking.

I seem to have finally found a solution that works.

My compiled server runs at a nice 40-70MBs, and while it does spike with use, it now always returns to normal.

Up until this point I was having a lot of extra stuff just sticking around in memory.  After making sure I was cleaning up absolutely everything in my own code, down to the injected function to grab the URLs I am scraping for, I was left investigating heaps.

When I was researching the problem I noticed ALOT of ChromeDevtoolProtocol strings.

Around this time I found the Network.disable CDP session command. This stabilized my memory growth completely. However I was still growing.

Yesterday I decided to see how many other commands could assist in my complete memory wipe goal.

```
let page: Page | undefined = await browser.newPage();
let session = await page.createCDPSession();

    await session.send("Debugger.disable");
    await session.send("Log.clear");
    await session.send("Log.disable");
    await session.send("ServiceWorker.disable");
    await session.send("Network.disable")
```

I am running this before I call goto and immediately after page creation. This seemed to slow down the memory growth even more, and had less CDP strings in my heapsnapshots.

While researching I found the following worked perfectly for my try{ return } finally { clean } paradigm I had started utilizing to track it better

```
try {
  return videoElement;
} finally {
  await session.send("Memory.forciblyPurgeJavaScriptMemory");
  await session.detach();
  page.removeAllListeners();
  await page.close();
  browser.removeAllListeners();
  await browser.close();
  page = undefined
  browser = undefined;
  videoURLs = undefined;
  cleanURL = undefined;
  alreadyGrabbed = undefined;
  url = undefined;
  videoElement = undefined;
  defaultError = undefined;
  Bun.gc(true);
  // writeHeapSnapshot("metaScrape"+snapshotCount()+".heapsnapshot");
}
```

While I have some spikes I always get back down to within 1-20 MB of my launch size. That's honestly the fetch I am using for cheerio for a different endpoint.

You could possibly switch to a full CDP session, but I like the default page methods.

This post comes up every time I searched memory leaks and puppeteer. Figured I'd be the change I wanted to see in the world and respond how I fixed something I read repeatedly while searching.

Also calling a browser at server launch and reusing it with new pages.

The following launch args are maintaining a solid 70-120MB for chrome.

```
await puppeteer.launch({
	channel: "chrome",
	headless: false,
	defaultViewport: null,
	userDataDir: 'myUserDataDir',
	networkEnabled: false,
	args: ["--remote-debugging-port=9222", "--no-first-run", "--disable-infobars", " --hide-crash-restore-bubble",
		"--disk-cache-size=50000000", "--disable-site-isolation-trials", "--no-sandbox", '--disable-dev-profile',
		'--aggressive-cache-discard',
		// '--disable-cache',
		'--disable-application-cache',
		'--disable-offline-load-stale-cache',
		'--disable-gpu-shader-disk-cache',
		// '--media-cache-size=0',
		// '--disk-cache-size=0',
		// performance
		"--disable-infobars",
		"--no-sandbox",
		"--disable-gpu",
		'--disable-setuid-sandbox',
		'--no-zygote',
		"--disable-web-security",
		"--disable-extensions",
		"--disable-plugins",
		"--headless",
		"--disable-breakpad",
		"--disable-client-side-phishing-detection",
		"--disable-sync",
		"--disable-translate",
		"--no-experiments",
		'--disable-default-apps',
		'--mute-audio',
		'--no-default-browser-check',
		'--disable-background-timer-throttling',
		'--disable-backgrounding-occluded-windows',
		'--disable-notifications',
		'--disable-background-networking',
		'--disable-component-update',
		'--disable-domain-reliability',
		'--autoplay-policy=user-gesture-required',
		'--disable-component-extensions-with-background-pages'],
	timeout: 6000
});
```

<img width="381" height="179" alt="Image" src="https://github.com/user-attachments/assets/94b88693-b38b-4239-b248-5a9a96b12295" />

Also just found this, and testing to confirm, but when I had everything but 
```
  await session.send("Memory.forciblyPurgeJavaScriptMemory");
  await session.detach();
```

It went 58 hours and only grew 100 megs.  This instance hasn't grown at all outside of server fetch being leaky.

Only side effect thus far has been trying to close a detached frame

```
ProtocolError: Protocol error (Target.closeTarget): No target with given id found
    at new PuppeteerError (B:/~BUN/root/devServer:32494:12)
    at new ProtocolError (unknown:1:28)
    at new Callback (B:/~BUN/root/devServer:38353:17)
    at create (B:/~BUN/root/devServer:38283:34)
    at <anonymous> (B:/~BUN/root/devServer:108894:30)
    at processTicksAndRejections (native:7:39)
```

**Comment by Jo5h** [comment]
13 hours later.

<img width="376" height="184" alt="Image" src="https://github.com/user-attachments/assets/db108b62-b921-4c4c-89c9-5c6839e53966" />

<img width="605" height="355" alt="Image" src="https://github.com/user-attachments/assets/1f0a3654-adb7-46db-8266-cafe5e89a0c0" />

2 frames closed before I could clean. It's my code causing as well. Just haven't recompiled for a new stability test yet.

Not sure how effective it is under stress, but for my use case of puppeteer it appears at this juncture to maintain a very low memory footprint.

Edit : Recovered more while typing this.

<img width="360" height="187" alt="Image" src="https://github.com/user-attachments/assets/d6a89e5d-dceb-4134-9d92-975028fc9ad9" />
