### ISSUE TITLE
[Bug]: Partially generated PNG screenshot 

### ISSUE THREAD

**Issue by rongxin-liu** [puppeteer/puppeteer#9285]
### Bug description

Steps to reproduce the problem:

Attempt to produce a screenshot of the webpage using a headless chrome browser but the generated PNG was incomplete, compared to the generated PDF, which was complete.

For example, if generating PDF, we would see the complete result:

<img width="857" alt="Screen Shot 2022-11-16 at 19 25 40" src="https://user-images.githubusercontent.com/10591665/202324042-9adee7ff-4689-4e33-b821-e54ab5db1d4a.png">

But the generated PNG was incomplete:

<img width="680" alt="Screen Shot 2022-11-16 at 19 26 10" src="https://user-images.githubusercontent.com/10591665/202324112-c51141bd-8d2e-44df-8121-4d412ccfdc4c.png">

The relevant code snippet is the following:

```js
        const browser = await puppeteer.launch({
            args: ['--no-sandbox'],
            executablePath: '/usr/bin/google-chrome',
            userDataDir: '/dev/null'
        });
        const page = await browser.newPage();
        await page.setContent(stdin, {waitUntil: ['load', 'networkidle0']});
        let buffer;
        if (process.argv[2] == 'pdf') {
            buffer = await page.pdf({
                pageRanges: '1',
                preferCSSPageSize: true,
                printBackground: true
            });
        }
        else if (process.argv[2] == 'png') {
            await page.setViewport(Object.assign(page.viewport(), {
                deviceScaleFactor: 2
            })); 
            buffer = await page.screenshot({
                fullPage: true
            });
        }
        await browser.close();
        process.stdout.write(buffer);
```
The exact same code running with puppeteer@19.1.2 does not run into this issue. Is there perhaps something that changed in version 19.2.2, or anything I'm missing?

### Puppeteer version

19.2.2

### Node.js version

v18.9.0

### npm version

8.19.1

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
The only relevant difference between those two versions is the update of the bundled Chromium version. 19.1.2 comes with M107 and 19.2.2 with M108. I recall there were some changes to screenshots so make sure that /usr/bin/google-chrome is at least M108.

**Comment by thibseisel** [comment]
I've got the same problem. It seems that the `fullPage` option is ignored.
Note that the `clip` option is still working.

I'm using `puppeteer-core` v19.3.0 with a stable Google Chrome `107.0.5304.121`.
I was able to workaround the issue by reverting to `puppeteer-core` v18.2.1.

**Comment by OrKoN** [comment]
@thibseisel version 19.3.0 requires at least chrome 108.0.5351.0
