### ISSUE TITLE
Screenshots of long pages get cut

### ISSUE THREAD

**Issue by m9dfukc** [puppeteer/puppeteer#929]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: macOS Sierra v. 10.12.6
* URLs (if applicable): http://www.spiegel.de/

**What steps will reproduce the problem?**

```javascript
const browser = await Puppeteer.launch();
const page = await browser.newPage();
await page.goto('http://www.spiegel.de');
await page.setViewport({
  width: 1280,
  height: 1000,
  deviceScaleFactor: 1
});
const buffer = await page.screenshot({fullPage: true});
```

**What is the expected result?**

![screenshot_01](https://user-images.githubusercontent.com/551597/31072561-b8bb5fa6-a768-11e7-8209-946c4292b9e2.jpg)

**What happens instead?**

![screenshot_00](https://user-images.githubusercontent.com/551597/31072519-8fc7d426-a768-11e7-8c02-8a071476adcc.png)

**Note**

It looks like screenshots higher than 16374 pixels get cut.

**Comment by valstu** [comment]
This could be related to #926?

**Comment by paulirish** [comment]
@valstu you can follow this pattern: https://github.com/GoogleChrome/puppeteer/issues/933#issuecomment-333615224

**Comment by m9dfukc** [comment]
Related to https://github.com/GoogleChrome/puppeteer/issues/359

**Comment by aslushnikov** [comment]
Closing as a dupe of #359
