### ISSUE TITLE
I'm using WSL2 and this is what worked for me!

### ISSUE THREAD

**Issue by kleber-ar** [puppeteer/puppeteer#9297]
I'm using WSL2 and this is what worked for me!
Follow [these steps](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#install-google-chrome-for-linux) from Microsoft to install Chrome on WSL.

> 1. Change directories into the temp folder: cd /tmp
> 2. Use wget to download it: sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> 3. Get the current stable version: sudo dpkg -i google-chrome-stable_current_amd64.deb
> 4. Fix the package: sudo apt install --fix-broken -y
> 5. Configure the package: sudo dpkg -i google-chrome-stable_current_amd64.deb

If you are able to execute `google-chrome` from terminal, then your code should work

_Originally posted by @vuhuucuong in https://github.com/puppeteer/puppeteer/issues/1837#issuecomment-1189353248_

**Comment by Lightning00Blade** [comment]
Thank you for bringing this up @Kleber-ar! I think this could be a good addition to the Troubleshooting page.
I would be happy to review a PR for this change. You can check how on ["Contributing"](https://pptr.dev/contributing).

**Comment by OrKoN** [comment]
Duplicate https://github.com/puppeteer/puppeteer/issues/1837
