### ISSUE TITLE
[Bug]: Page doesn't work after timeout error

### ISSUE THREAD

**Issue by kiber-io** [puppeteer/puppeteer#9321]
### Bug description

I am writing a crawler for websites and I came across the fact that if there is at least one link on the page that will give a TimeoutError error, then I can't handle it in such a way that I just ignore it and go on collecting - no link opens anymore.

Steps to reproduce the problem:

1. Trying to go to a page that takes a very long time to open (ok)
2. Getting a TimeoutError (ok)
3. We are trying to go to another page (which already opens very easily) in the same tab by simply calling page.goto with a different url (ok)
4. **_We get TimeoutError again_**, although in normal Chrome, after the same procedure, the second page opens calmly and quickly (wtf?!)

I tried manually stopping the loading of the tab (because this does not happen automatically after an error) using Page.stopLoading - the final result does not change :(
If you immediately try to open a "quick" (second) page, then there are no problems.

### Puppeteer version

puppeteer-core 18.0.5

### Node.js version

16.15.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Could you please provide a repro for the issue?

**Comment by OrKoN** [comment]
Also, please try with the latest puppeteer-core version and make sure that the browser version is compatible: https://pptr.dev/chromium-support

**Comment by kiber-io** [comment]
Thank you for your quick response!
But I solved the problem, it's not related to chromium or puppeteer. This site was working intermittently. I apologize for the trouble :(
