### ISSUE TITLE
[Question] Interact with extension under devtools panel

### ISSUE THREAD

**Issue by vinodreddy-bs** [puppeteer/puppeteer#9327]
I need to write e2e tests for an accessibility extension. Our extension is loaded in the devtools panel and I would like to interact with it via UI.

Have a library [puppeteer-devtools](https://github.com/dequelabs/puppeteer-devtools) which will provide us the extension panel as a frame and can interact with it (puppeteer version used in this library is deprecated). However, this is not supported with latest puppeteer version and I cannot go with this.

Is there a way I can get it worked. I am not looking for loading the extension in a separate page (this will not work for my extension as it should be loaded under active page/tab). Our extension manifest is v3

**Comment by OrKoN** [comment]
Whatever is possible with [puppeteer-devtools](https://github.com/dequelabs/puppeteer-devtools) should be still possible. Perhaps try updating the library to use the latest Puppeteer version.

**Comment by OrKoN** [comment]
In general, starting Puppeteer with `devtools: true` and waiting for a page with the DevTools URL should give you the DevTools page. Then you should be able to use `waitForFrame` to get the extension frame. Perhaps it would require reaching out to some Puppeteer internals as I don't think Puppeteer would automatically attach to DevTools targets.

**Comment by vinodreddy-bs** [comment]
Is it possible to provide an example? After upgrading to latest puppeteer
version, puppeteer-devtools library doesn’t work. My chrome extension is
using manifest v3 and not sure how to work with service_worker

**Comment by OrKoN** [comment]
I think it'd be best to ask if someone has an example on StackOverflow.
