### ISSUE TITLE
[Docs] Algolia search does not work after a new version release

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#9329]
Let's try to make it keep the index for the current version by giving it a static docausarus tag name? e.g., `current`?

**Comment by OrKoN** [comment]
Alternatively, can we always use the next version for search?

**Comment by jrandolf** [comment]
The crawler has been updated to run every day at 12:00AM. We could also set Algolia to search only on the `next` tag (as suggested internally), but this probably isn't safe for those who want to search the current latest version. Users can always set the version to next and search after.

**Comment by OrKoN** [comment]
The problem is not solved still. Released a version yesterday and still no index. @jrandolf let's find a reliable solution.
