### ISSUE TITLE
[feat]: shared cross context module resolution worker also can be used as serviceWorker and IPC between both

### ISSUE THREAD

**Issue by lemanschik** [puppeteer/puppeteer#9332]
# Tracking progress will issue PR for module resolution
This will refactor puppeteer to offer and use a shared resolution worker inside nodejs 19.1+ 
as also expose this worker directly inside other contexts. Feature unified resolve cross context.

## Closes:
- [ ] ... collect additional bugs or add more usecases like loading backend modules in a frontend context.
- [ ] This Bug build process less priority gets fixed by other issue. description

Steps to reproduce the problem:

build esm modules then bundle them see:

The main problem that takes longer is that browserFetcher is in a none Typesave handwritten state hard to correct 
maybe complet rewrite is much more faster with current nodejs.

```js

import NodeWebSocket from 'ws';
import * as childProcess from 'child_process';
import { exec as exec$1 } from 'child_process';
import extractZip from 'extract-zip';
import * as fs$1 from 'fs';
import fs__default, { existsSync, readdirSync, createReadStream, createWriteStream, accessSync } from 'fs';
import { mkdir, unlink, chmod, readdir, mkdtemp } from 'fs/promises';
import * as http from 'http';
import * as https from 'https';
import createHttpsProxyAgent from 'https-proxy-agent';
import * as os from 'os';
import os__default, { tmpdir } from 'os';
import * as path from 'path';
import path__default, { join } from 'path';
import { getProxyForUrl } from 'proxy-from-env';
import removeFolder from 'rimraf';
import tar from 'tar-fs';
import bzip from 'unbzip2-stream';
import * as URL$1 from 'url';
import * as util from 'util';
import { promisify } from 'util';
import * as readline from 'readline';
```

## Current

```js
import NodeWebSocket from 'ws';
import fs$2, { createReadStream as createReadStream$1, createWriteStream as createWriteStream$1, accessSync as accessSync$1, existsSync as existsSync$3, readdirSync as readdirSync$1, promises } from 'node:fs';
import removeFolder from 'rimraf';
import extractZip$1 from 'extract-zip';
import { extract } from 'tar-fs';
import bzip$1 from 'unbzip2-stream';
import { join, basename, resolve } from 'node:path';
import * as http from 'node:http';
import http__default from 'node:http';
import * as https from 'node:https';
import https__default from 'node:https';
import createHttpsProxyAgent from 'https-proxy-agent';
import { getProxyForUrl as getProxyForUrl$1 } from 'proxy-from-env';
import { tmpdir, release } from 'node:os';
import { exec } from 'node:child_process';
import { format } from 'node:util';
import URL$1 from 'node:url';
import * as childProcess from 'child_process';
import * as fs$1 from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { promisify } from 'util';
```

solution:

will make small PR that corrects the imports mainly related to the node/* parts of the code base where import * gets used and not explicitly the namedExports.

### Puppeteer version

current

### Node.js version

nightly

### npm version

nightly

### What operating system are you seeing the problem on?

Linux, macOS, Windows

**Comment by OrKoN** [comment]
Hey thanks for report but it’s not something that aligns with our priorities currently.

**Comment by lemanschik** [comment]
@OrKoN that issue was not for you i am rolling out something new i call it web-modules . In fact i have large parts of the chromium platform already completed building in the browser it self out of git modules without a server.

i now shape the existing ecosystem to match up. This deprecates anything that got done on servers. before. i even build directly v8 in v8 via tcc
