### ISSUE TITLE
In puppeteer, how to share virtual window screen and should ignore fake media default video

### ISSUE THREAD

**Issue by ssk512** [puppeteer/puppeteer#9336]
In puppeteer added below arguments

args: [
    '--use-fake-device-for-media-stream',
    '--use-fake-ui-for-media-stream',
    '--use-file-for-fake-audio-capture='+audioFilePath,
    '--use-file-for-fake-video-capture='+videoFilePath,
    '--enable-usermedia-screen-capturing',
    '--allow-http-screen-capture',
    '--no-sandbox',
    '--auto-select-desktop-capture-source="Entire screen"',
    '--allow-file-access'
    
  ]
For video and audio using fake video and audio, but for sharing need to share virtual windows screen but sharing fake media default video. how to fix it?

**Comment by jrandolf** [comment]
Please use the [bug form](https://github.com/puppeteer/puppeteer/issues/new?assignees=&labels=bug&template=bug.yml&title=%5BBug%5D%3A+) if you are filing a bug. Otherwise, it's probably better to ask this on StackOverflow.
