### ISSUE TITLE
[Bug]: viewport() returns null all the time

### ISSUE THREAD

**Issue by masonalan** [puppeteer/puppeteer#9343]
### Bug description

Steps to reproduce the problem:

1. Create a page

```
browser = await puppeteer.launch({
  	headless: false,
  	executablePath: executablePath()
});
page = await browser.newPage();
await page.goto('any url');
```

2. Try to do get the viewport. I expected this to work but

`page.viewport()` returns `null`.
`await page.viewport()` doesn't work either.

The docs specify that this value is optional but there is absolutely no explanation of when this object might be null (apparently that's all the time). 

### Puppeteer version

most recent

### Node.js version

16.14

### npm version

8.3.1

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf** [comment]
Could you write a concrete script? See https://stackoverflow.com/help/minimal-reproducible-example
