### ISSUE TITLE
Can't resolve iframes in VSCode

### ISSUE THREAD

**Issue by amlanbiswas** [puppeteer/puppeteer#9347]
I am working on testing a VSCode extension using Extension Development Host.

After selecting the iframe, I cannot resolve the content within the iframe:

`await vscode.Page.waitForSelector('iframe');
 const f = await vscode.Page.$("iframe.webview.ready");
 const x = await f.contentFrame();`

This is coming up as null. The iframe in question is as follows:

`<iframe name="31af8060-a20c-43b5-9bc4-2e0907beb675" class="webview ready" sandbox="allow-scripts allow-same-origin allow-forms allow-pointer-lock allow-downloads" allow="cross-origin-isolated; clipboard-read; clipboard-write;" src="vscode-webview://15p9bvij4mfrnhuk8i83rio1oji5609me4l6cj09abkcjtll7asl/index.html?id=e7e197b0-ad2f-4033-adc6-e0a045447be5&amp;origin=1b8ed955-2a8f-49d8-9f39-1c1d5b80e870&amp;swVersion=4&amp;extensionId=hehe&amp;platform=electron&amp;vscode-resource-base-authority=vscode-resource.vscode-cdn.net&amp;parentOrigin=vscode-file%3A%2F%2Fvscode-app" style="border: none; width: 100%; height: 100%; pointer-events: auto;"></iframe>`

While Chrome has a argument for --disable-web-security, VSCode does not have anything of that sort. Also, I am not sure if that is the problem here. Any sugestions?

**Comment by OrKoN** [comment]
Have you tried using `page.waitForFrame`? please provide a script and a sample extension to reproduce the bug report https://stackoverflow.com/help/minimal-reproducible-example But It looks like you could you could ask this question on StackOverflow instead.
