### ISSUE TITLE
how to get complete disk-cache rather than the simple disk-cache

### ISSUE THREAD

**Issue by CoyPan** [puppeteer/puppeteer#9350]
my code:

`
const browser = await puppeteer.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disk-cache-dir=./dcache'],
  }); 
`
`
const page = await browser.newPage(); 
`
`
await page.goto('https://google.com', {
    waitUntil: 'load'
});
`

I get disk-cache like this：

<img width="414" alt="image" src="https://user-images.githubusercontent.com/11265718/205011738-e860d72d-de1d-4c74-a923-a1d9bca28204.png">

but I realy want something like this:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/11265718/205012005-03c26ed2-da0d-4727-b375-b127803bef14.png">

so how can I get the complete disk cache ?

**Comment by OrKoN** [comment]
Hey, it looks like this would be out of scope for Puppeteer and not something we support currently. Check out Chromium flags reference to see if some flags do what you need https://peter.sh/experiments/chromium-command-line-switches/
