### ISSUE TITLE
Top-level domain is not rendered properly www.example.store renders only www.example.sto as part the URL link

### ISSUE THREAD

**Issue by jofomah** [puppeteer/puppeteer#9351]
Issue: 
When a URL that has top-level domain part that is longer than 3 characters is used in a webpage, the generated PDF doesn't render the full top-level domain part...

- `https://example.store` is rendered as [https://example.sto](https://example.sto)re

See attached picture:
![screenshot-ampifire com-2022 11 30-16_25_24](https://user-images.githubusercontent.com/5929681/205045892-615f6592-0378-45ce-acde-0f2cc889b263.png)

Code:
```

    const browser = await openBrowser();
    try {
        const page = await browser.newPage();
        await page.goto(url);
        await page.pdf({path: path, preferCSSPageSize: true});
        await page.close();    
        await browser.close();
    } catch (e) {
        debug(e)
        await browser.close();
    } finally {
        shell.exec('pkill chrome'); // zombie chromes
    }

```

**Comment by jrandolf** [comment]
Please file a new issue with the improved bug form. We will try to reproduce it there.
