### ISSUE TITLE
[Bug]: Turkish Lira not rendering correct symbol

### ISSUE THREAD

**Issue by swar-mukh** [puppeteer/puppeteer#9353]
### Bug description

The ₺ symbol gets rendered as &prime;&prime; (two `prime` characters). But when the two `prime` characters are copied from a PDF viewer and pasted somewhere else, the text that gets pasted is the ₺ symbol.

Add the following lines of code:

```html
<div>HTML Symbol: ₺</div>
<div>HTML Code: &#8378;</div>
<div>HTML Hex Code: &#x20BA;</div>
```

All of them gets rendered as:

<pre>
HTML Symbol: &prime;&prime;
HTML Code: &prime;&prime;
HTML Hex Code: &prime;&prime;
</pre>

All other currencies extracted from Toptal along with each of their HTML symbol, HTML code and HTML hex code works fine, except for the Turkish lira.

### Puppeteer version

13.3.2

### Node.js version

16.14.2

### npm version

8.5.0

### What operating system are you seeing the problem on?

Linux, macOS, Windows

### Configuration file

```
PUPPETEER_CHROMIUM_REVISION=961656
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
```

**Comment by Lightning00Blade** [comment]
Hey @swarmukhdefault I tried reproducing it on the latest version of `puppeteer` and it seems to work there, so please update your version.

I will be closing this, but if the issue persist on latest version feel free to reopen this issue.
