### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'iPhone 6')

### ISSUE THREAD

**Issue by tomatobybike** [puppeteer/puppeteer#9355]
### Bug description

Steps to reproduce the problem:

  const iPhone = puppeteer.devices['iPhone 6'];
                                  ^

TypeError: Cannot read properties of undefined (reading 'iPhone 6')

`
 import puppeteer from 'puppeteer'

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const iPhone = puppeteer.devices['iPhone 6'];
  console.log('iPhone', iPhone);
  await page.emulate(iPhone);
  await page.goto('https://www.baidu.com/');
  await page.screenshot({path: './doc/full.png', fullPage: true});
  await browser.close();
})();
`

### Puppeteer version

19.3

### Node.js version

16.17.1

### npm version

8.15.0

### What operating system are you seeing the problem on?

macOS

### Configuration file

```JavaScript
import puppeteer from 'puppeteer'


(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const iPhone = puppeteer.devices['iPhone 6'];
  console.log('iPhone', iPhone);
  await page.emulate(iPhone);
  await page.goto('https://www.baidu.com/');
  await page.screenshot({path: './doc/full.png', fullPage: true});
  await browser.close();
})();
```

### Relevant log output

```Shell
const iPhone = puppeteer.devices['iPhone 6'];
                                  ^

TypeError: Cannot read properties of undefined (reading 'iPhone 6') at 25:35
```

**Comment by Lightning00Blade** [comment]
@tomatobybike to fix your issue you have to you to either like `import * as puppeteer from 'puppeteer'` then `puppeteer.KnownDevices` or `import puppeteer, { KnownDevices } from 'puppeteer'` . I am showing you example with `KnownDevices` as `devices` is deprecated.

**Comment by OrKoN** [comment]
@Lightning00Blade is looking into an issue related to this report, potentially not correct types that we generate for cjs modules.
