### ISSUE TITLE
How to set the font size of the browser is less than 12px?

### ISSUE THREAD

**Issue by liyangyangi** [puppeteer/puppeteer#9359]
How to set the font size of the browser is less than 12px? My page has some text 8px, bug at puppeteer is 12px.

**Comment by Lightning00Blade** [comment]
Hello @liyangyangi can you please follow provided template for bug reports and also provide a minimal reproducible code?

**Comment by liyangyangi** [comment]
thanks, It seems that there is no problem，the online server is ok.

**Comment by liyangyangi** [comment]
@Lightning00Blade
