### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by julien-c** [puppeteer/puppeteer#936]
Is someone already working on Typescript typings for `puppeteer`?

Given the quality of the [doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md) (auto-generated from the code?) it seems like it would be pretty easy to write/maintain typings for this project.

Thoughts?

**Comment by julien-c** [comment]
Ok found this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19827

**Comment by Khady** [comment]
This one in definitelytyped seems to be "old" already (0.10, but 0.11 has been released).

This has been discussed a few times and IIUC the solution is https://github.com/GoogleChrome/puppeteer/pull/219

Previous discussions:
- https://github.com/GoogleChrome/puppeteer/pull/371
- https://github.com/GoogleChrome/puppeteer/pull/739

**Comment by aslushnikov** [comment]
@julien-c the #219 is our approach to typescript typing.
