### ISSUE TITLE
[Bug]: Chrome Extension always reinstall when startup puppeteer App

### ISSUE THREAD

**Issue by freewong** [puppeteer/puppeteer#9362]
### Bug description

I have installed this extension below
https://chrome.google.com/webstore/detail/microsoft-editor-spelling/gpaiobkfhnonedkhhfjpmhdalgeoebfa
I can see, the chrome browser will reinstalling the extension for every time when you run the code below.

```
(async function(){
const browser = await puppeteer.launch({
userDataDir:'C:\\Users\\xxxxxx\\AppData\\Local\\Google\\Chrome\\User Data',
executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
headless:false,
ignoreDefaultArgs:['--enable-automation'],
args:['C:\\Users\\xxxxxx\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Extensions\\gpaiobkfhnonedkhhfjpmhdalgeoebfa\\1.2211.1007_0' ]
});
    const pages=await browser. Pages();
    const page=pages[0];
   await page.goto("https://www.bing.com/");
})();
```

Additionally, if you make an extension by yourself there is have same issue.
```
chrome.runtime.onInstalled.addListener((reason) => {
const t = Date.now();
console.log('chrome.runtime.onInstalled','reason',reason,t);
chrome.tabs.create({ url: `https://www.google.com/?${t}` });  		
  }	
);
```

### Puppeteer version

19.3.0

### Node.js version

14.17.0

### npm version

6.14.13

### What operating system are you seeing the problem on?

Windows

**Comment by Lightning00Blade** [comment]
Hey @freewong this is not a thing puppeteer has control over, so I will be closing the issue. You can feel free to open this issue on the Chrome bug report - https://bugs.chromium.org/p/chromium/issues/list.
