### ISSUE TITLE
[Bug]: pdf with full page width/height generating additional page

### ISSUE THREAD

**Issue by rafma0** [puppeteer/puppeteer#9365]
### Bug description

Trying to generate a pdf using the full width/height of the content, sometimes generates one additional page

Steps to reproduce the problem:

1. run this code

```js
const fs = require('fs/promises')
const puppeteer = require('puppeteer')

async function main() {
  const html = `
    <html>
    <head>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        .container {
          width: 76px;
          height: 123px;
          margin: 0 auto;
          background: blue;
        }
      </style>
    </head>
    <body>
      <div class="container"></div>
    </body>
    </html>
  `

  await fs.writeFile('test.html', html)

  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto(__dirname + '/test.html', { waitUntil: 'networkidle0' })
  await page.emulateMediaType('screen')
  const { width, height } = await page.evaluate(() => ({
    width: document.querySelector('.container').offsetWidth,
    height: document.querySelector('.container').offsetHeight
  }))

  await page.pdf({ path: 'test.pdf', printBackground: true, width, height })
  await browser.close()
}

main()
```

2. look at the pdf

![pupp](https://user-images.githubusercontent.com/28578847/205930110-d8aa72bd-2556-497d-a56a-fa1370435c63.jpg)

similar to https://github.com/puppeteer/puppeteer/issues/8280 https://github.com/puppeteer/puppeteer/issues/5590

### Puppeteer version

^19.3.0

### Node.js version

v18.4.0

### npm version

yarn 1.22.18

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
The pixel value gets converted to inches and I guess that is why the value is not very accurate. If you increase the height by a bit, I think it works. Although, there is still a whitespace at the bottom of the page there. Would you mind filing this on crbug.com as it looks like print layout issue?

**Comment by rafma0** [comment]
Yes, in this example increasing the height by 1px keeps everything in one page. In my actual code I needed to add 20px to work with all different cases I tested. I guess I'll probably add a few more pixels just to be safe :x

I also tried changing in the style 76px to 0.79in and 123px to 1.28in and passing those values manually to width and height, but it still creates two pages.

One thing I noticed is every pdf generated by Chrome using the Destination "Save as PDF" have that blank space at the bottom of every page, but for the most part you can only notice at much higher zoom levels, like 3200% or 6400% using Adobe Acrobat. If you change the Destination to "Microsoft Print to PDF" the blank space gets added to the left of every page. Generating a PDF using Adobe Acrobat I don't see this whitespace anywhere.

I filled a bug here https://bugs.chromium.org/p/chromium/issues/detail?id=1396392 , hope its in the right place.

**Comment by Vizzr** [comment]
Just to add to this issue:

For anyone running the browserless/chrome docker:
The bug is included in browserless/chrome:1.57.0-puppeteer-19.2.2

Using browserless/chrome:1.56.0-puppeteer-18.0.5 works well.

**Comment by RyonMB** [comment]
Any update on this?

**Comment by OrKoN** [comment]
The issue is not reproducible in the latest version and the upstream issue has been fixed.
