### ISSUE TITLE
[Bug]: TypeScript TS2503 error in v19.3.0

### ISSUE THREAD

**Issue by Juneezee** [puppeteer/puppeteer#9366]
### Bug description

Minimal code to reproduce:

```typescript
import puppeteer from "puppeteer";

let browser: puppeteer.Browser;
let page: puppeteer.Page;
```

|                  | TypeScript 4.8.4 | TypeScript 4.9.3 |
|------------------|:----------------:|:----------------:|
| Puppeteer 19.2.0 |         ✔️        |         ✔️        |
| Puppeteer 19.3.0 |         ❌        |         ❌        |

On Puppeteer 19.3.0, it gives `TS2503: Cannot find namespace 'puppeteer'.`

This is my `tsconfig.json`, hope it helps.

```json
{
  "compilerOptions": {
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "exactOptionalPropertyTypes": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "strict": true,
    "noEmit": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "target": "ES2022",
    "incremental": true,
    "skipLibCheck": true
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

_Originally posted in https://github.com/puppeteer/puppeteer/issues/9241#issuecomment-1331824345 and https://github.com/puppeteer/puppeteer/issues/9241#issuecomment-1339208040_

### Puppeteer version

19.3.0

### Node.js version

18.12.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Able to repro, thanks for posting this issue separately. Unfortunately, yeah, it looks like an unexpected breaking change but I think we will not fix it because the types are correct in the latest version and the actual classes are exported too so you can do `page instanceof puppeteer.Page`, for example, which is often desired. The recommended way to import classes would be:

```
import puppeteer, {Browser, Page} from "puppeteer";

let browser: Browser;
let page: Page;
```

or 

```
import * as puppeteer from "puppeteer";

let browser: puppeteer.Browser;
let page: puppeteer.Page;
```
