### ISSUE TITLE
[API request] Expose the Chrome DevTools target as a `page`

### ISSUE THREAD

**Issue by elliette** [puppeteer/puppeteer#9371]
### Bug description

Filing a new issue instead of reopening https://github.com/puppeteer/puppeteer/issues/4247 where this was first proposed (it was closed in 2019 because it was believed the reporter was the only client trying to use Puppeteer to test a panel added to Chrome DevTools by their Chrome extension, from the comments / recently opened issues it seems that is no longer the case). 

As described in https://github.com/puppeteer/puppeteer/issues/4247#issue-429876229, currently the only way to interact with a panel added to Chrome DevTools by a Chrome extension is to use a hack to set the target type to `page`:

```
devtoolsTarget._targetInfo.type = 'page';
```

This hack is used by the `puppeteer-devtools` library ([code pointer](https://github.com/dequelabs/puppeteer-devtools/blob/e21867534231ca059b285007b01f3c023d8b94be/src/index.ts#L44)) which was recently cited in https://github.com/puppeteer/puppeteer/issues/9327 as a way to test a Chrome Extension devtools panel. 

**Why this doesn't work for my use case:**

I'm using the [Dart language wrapper of Puppeteer](https://github.com/xvrh/puppeteer-dart) to test my Chrome extension (which is also written in Dart). Because Dart is a strongly-typed language that prevents access to `private` members (such as `_targetInfo`), this hack is not possible. I could ask the owner of the Dart Puppeteer implementation to expose this hack in their API, but it seems like a better solution for Puppeteer itself to support this as a real use case and not as a hack. 

From https://github.com/puppeteer/puppeteer/issues/4247#issuecomment-482396308, it sounds like supporting this as an actual use case would be possible. 

Thank you!

### Puppeteer version

N/A

### Node.js version

N/A

### npm version

N/A

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
It should be possible to re-define what Puppeteer considers to be a page via the isPageCallback: https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/services/puppeteer/PuppeteerConnection.ts;l=90;drc=a30fb93648955c875c7fac7d30eee58d2dd80819

Although accessing the callback requires using some internal APIs, would it work for your use case in general?

**Comment by elliette** [comment]
> It should be possible to re-define what Puppeteer considers to be a page via the isPageCallback: https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/services/puppeteer/PuppeteerConnection.ts;l=90;drc=a30fb93648955c875c7fac7d30eee58d2dd80819
> 
> Although accessing the callback requires using some internal APIs, would it work for your use case in general?

This would potentially work. However, unless I'm misunderstanding, it seems like the client would then have determine whether any target is a page or not, not just the Chrome DevTools target? Ideally it would be nice to have a way to defer back to Puppeteer if we are uninterested in specifying whether the target is a page. Eg:

```
function isPageTargetCallback(target) {
  if (target.url.startsWith('devtools://devtools') {
    return true;
  }
  // Defer to Puppeteer:
  return isPageTargetByDefault(target);
}

**Comment by OrKoN** [comment]
@elliette that's why it's not a public API yet

**Comment by elliette** [comment]
Adding @xvrh who owns https://github.com/xvrh/puppeteer-dart - thoughts on `isPageCallback`? This might be something the Dart Puppeteer package could add itself, even without Puppeteer opening it up as a public API

**Comment by OrKoN** [comment]
@elliette if I recall correctly, DevTools in undocked mode is reported as a page. Perhaps that would be helpful but I am not sure if you can start it undocked.

**Comment by OrKoN** [comment]
Related https://github.com/puppeteer/puppeteer/issues/9262

**Comment by elliette** [comment]
> @elliette if I recall correctly, DevTools in undocked mode is reported as a page. Perhaps that would be helpful but I am not sure if you can start it undocked.

In experimenting with this, I was able to simulate undocking DevTools by getting its URL and then opening a new page with that URL. However, this new DevTools in a page does not have the panels added by my Chrome Extension.

**Comment by thuey** [comment]
Any updates on this? The workaround mentioned in the OP is no longer possible for JavaScript either. I do see there is an "internal" `_isPageTarget` on the `BrowserConnector`, though, that might be another workaround: https://github.com/puppeteer/puppeteer/blob/19111be8d0a7db4d5f1e9c9b9c59fa90bdf5a062/packages/puppeteer-core/src/common/BrowserConnector.ts#L56

**Comment by OrKoN** [comment]
@thuey no updates
