### ISSUE TITLE
How to force Puppeteer to download a file instead of opening it ?

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#9374]
I am trying to download HLS (0001.ts file)
ex:

`page.goto('https://eedols.com/m3u8/20221205130402-SiBOhsUsJbTdZLP-DfqGGLn5cF-6-l_1080p_00001.ts')`

However Chromium opens that file instead of downloading it. 
Is there a way to force downloading some type of files (like .ts) instead of opening it inside chromium ?

**Comment by OrKoN** [comment]
I think if you have the direct URL you should be able to download the file directly from node. For example, using https://github.com/axios/axios or node Fetch API. If you need credentials to access the URL and thus the download needs to be performed by the browser, there is a feature request for this https://github.com/puppeteer/puppeteer/issues/8010 and some workarounds found by the community. Also, you can try evaluating fetch calls to download the file (https://stackoverflow.com/questions/49245080/how-to-download-file-with-puppeteer-using-headless-true).
