### ISSUE TITLE
[Bug]: link click with download attribute does not download the file

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#9379]
### Bug description

when you have a 

`<a href="link" download="download.file">click here</a>`

clicking on a inside puppeteer opens the link and does not download it as it does in chrome.

```
const puppeteer = require('puppeteer');
var browser;
var page;

async function download(url) {
	await page.evaluate((url) => {
		const btn = document.createElement('a');
		btn.setAttribute('href', url);
		btn.setAttribute('download', 'download.ts');
		btn.click(); // should download the file and not open it in browser 
	}, url);
}

(async function () {
	browser = await puppeteer.launch({
		headless: false,
	});
	page = await browser.newPage();
	await page.setViewport({width: 1200, height: 800});
	await download('https://eedols.com/m3u8/20221205130402-SiBOhsUsJbTdZLP-DfqGGLn5cF-6-l_1080p_00001.ts');
	await page.waitForTimeout(300000);
})();
```

### Puppeteer version

19.3.0

### Node.js version

18.1

### npm version

7.21

### What operating system are you seeing the problem on?

Windows

**Comment by Lightning00Blade** [comment]
This was already answered and close in #9374, please do not create multiple issue for the same question.

**Comment by yarekc** [comment]
It is not the same case at all and it is not the same question at all.

This one is really an issue for me: clicking on a link with download attribute does not download the link. 
It works for some extensions like .csv, but if extension is .ts, it does not download the file, but opens it.

**Same script works as expected inside chrome, firefox, but creates an unexepcted behaviour in Puppeteer**

**Comment by OrKoN** [comment]
> download only works for [same-origin URLs](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), or the blob: and data: schemes.

from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

Try downloading it from the same origin URL instead of `about:blank` page. I don't think it works as expected in Chrome if you on a page with a different origin. In general, this kind of question is better suited for StackOverflow.

**Comment by yarekc** [comment]
It is not an origin issue or cors issue.

This snippet works fine in chrome (it downloads the file).
But in puppeteer, it OPENS the .TS file in the browser instead of downloading it


```
const btn = document.createElement('a');
btn.setAttribute('href', url);
btn.setAttribute('download', 'download.ts');
btn.click(); // should download the file and not open it in browser 
```

**Comment by OrKoN** [comment]
@yarekc how do you run it in the browser?

**Comment by OrKoN** [comment]
In any case, I think this issue would be the same as https://github.com/puppeteer/puppeteer/issues/299 since we don't have an API support for file downloads (yet).

**Comment by yarekc** [comment]
Just create a page and script inside
Notice that the download link eso not point to the same domain

```
<script>
$('#btn1').click(function() {
	const btn = document.createElement("a");
	let url = "https://eedols.com/m3u8/20221205130402-SiBOhsUsJbTdZLP-DfqGGLn5cF-6-l_1080p.m3u8";
	btn.setAttribute("href", url);
	btn.setAttribute("download", "zazaz.ts"); // in Chrome, it DOWNLOADS the file. In Puppeteer it OPENS it !
	btn.click()
});
</script>
```

**Comment by OrKoN** [comment]
your script works for me with Puppeteer if I configure the download behaviour and navigate to the target site before clicking the download.

**Comment by Fatema-Nawrin** [comment]
<a  href="javascript:void(0);">click here</a>
What solution will work for elements like this?
