### ISSUE TITLE
[Bug]: Syntax Error: "(" unexpected

### ISSUE THREAD

**Issue by PoolloverNathan** [puppeteer/puppeteer#9384]
### Bug description

Steps to reproduce the problem:

1. install puppeteer
2. wait
3. try to start (through jest if that helps)

### Puppeteer version

puppeteer@19.4.0

### Node.js version

v19.2.0

### npm version

8.19.3

### What operating system are you seeing the problem on?

Linux

### Configuration file

```JavaScript
(unmodified)
```

### Relevant log output

```Shell
Failed to launch the browser process!
    /home/nathan/.cache/puppeteer/chrome/linux-1069273/chrome-linux/chrome: 1: Syntax error: "(" unexpected


    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

      at onClose (node_modules/puppeteer-core/src/node/BrowserRunner.ts:328:9)
      at Interface.<anonymous> (node_modules/puppeteer-core/src/node/BrowserRunner.ts:314:16)
```

**Comment by OrKoN** [comment]
@Lightning00Blade could you try on a linux?

**Comment by PoolloverNathan** [comment]
I am on linux (linux -> ssh -> raspberry pi)

**Comment by PoolloverNathan** [comment]
```
nathan@nathanpi:~ $ script
Script started, output log file is 'typescript'.
nathan@nathanpi:~ $ ls /home/nathan/.cache/puppeteer/chrome/linux-1069273/chrome-linux/chrome
/home/nathan/.cache/puppeteer/chrome/linux-1069273/chrome-linux/chrome
nathan@nathanpi:~ $ ls /home/nathan/.cache/puppeteer/chrome/linux-1069273/chrome-linux/
chrome                   chrome_sandbox  libEGL.so             locales                nacl_irt_x86_64.nexe  v8_context_snapshot.bin
chrome_100_percent.pak   chrome-wrapper  libGLESv2.so          MEIPreload             product_logo_48.png   vk_swiftshader_icd.json
chrome_200_percent.pak   ClearKeyCdm     libvk_swiftshader.so  nacl_helper            resources             xdg-mime
chrome_crashpad_handler  icudtl.dat      libvulkan.so.1        nacl_helper_bootstrap  resources.pak         xdg-settings
nathan@nathanpi:~ $ exit
exit
Script done.
```

**Comment by OrKoN** [comment]
ah actually it seems to be this issue https://github.com/puppeteer/puppeteer/issues/550

**Comment by OrKoN** [comment]
also possibly related https://github.com/puppeteer/puppeteer/issues/2924

**Comment by PoolloverNathan** [comment]
#550 is it not downloading, but it looks like it is getting downloaded for me. #2924 looks more accurate, but I am getting a `(`, not a `|`.

**Comment by OrKoN** [comment]
We don't support arm64 on linux because Chromium project does not provide binaries for that architecture on Linux at the moment.

**Comment by jjyuhub** [comment]
I just had the same issue on Apple Silicon, people on StackOverflow seem to suggest to turn on Rosetta emulation inside Docker: https://stackoverflow.com/a/76093840

**Comment by eybel** [comment]
I am using Amazon Linux arm64. if isnt compatible, is something I could do or I just need to use some other library for my PDF creation on backend?

**Comment by AyoobMH** [comment]
> I am using Amazon Linux arm64. if isnt compatible, is something I could do or I just need to use some other library for my PDF creation on backend?

Yeah, I'm facing the same issue, and puppeteer docs say it's not compatible with arm64
https://pptr.dev/troubleshooting/
