### ISSUE TITLE
[Bug]: Cannot get all cookies that were sent to the server in the 'cookie' header of the request.

### ISSUE THREAD

**Issue by yarekc** [puppeteer/puppeteer#9387]
### Bug description

Cannot get all cookies

```
	page = await browser.newPage();
	await page.setRequestInterception(true);
	page.on('request', interceptedRequest => {
		const headers = interceptedRequest.headers();
		headers.cookie = cookies;
		console.log('headers', headers);
		interceptedRequest.continue();
	});
```

Cookies that were sent to the server
https://prnt.sc/v2-_3W3vqm4U

And here are the cookies I can retrieve
https://prnt.sc/hrSNMk6jRw9U

### Puppeteer version

19.3.0

### Node.js version

18.1

### npm version

7.21

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
Please provide a minimal executable example to repro the problem. You mention that you cannot get all cookies but the code snippet only sets the cookies?

**Comment by jrandolf** [comment]
Please file a new issue with the improved bug form. We will try to reproduce it there.
