### ISSUE TITLE
Protocol eror(Network.setCookies) nvald parameters Failed to deserialize params.cookies.expires - BINDINGS: double value expected at position 6673[Bug]: 

### ISSUE THREAD

**Issue by bowen-huang1** [puppeteer/puppeteer#9391]
### Bug description

Protocol eror(Network.setCookies) nvald parameters Failed to deserialize params.cookies.expires - BINDINGS: double value expected at position 6673

### Puppeteer version

^14.4.1

### Node.js version

v14.17.0

### npm version

6.14.13

### What operating system are you seeing the problem on?

Windows

**Comment by Lightning00Blade** [comment]
Hello @bowen-huang1, can you please try updating to the latest version of Puppeteer and try again.
If the issue persist to help you we would the puppeteer code and sample page that reproduces the same issue.

**Comment by bowen-huang1** [comment]
Only a few cookies will have this error

**Comment by OrKoN** [comment]
The error means that cookie parameters are not valid. Try using the latest version and make sure that the browser is compatible with Puppeteer. Please re-open if you are able to provide a repro https://stackoverflow.com/help/minimal-reproducible-example

**Comment by bowen-huang1** [comment]
Cookies are obtained through page. cookies (). Cookies are available
