### ISSUE TITLE
[Bug]: Puppeteer doesn't launching from class constructor

### ISSUE THREAD

**Issue by Lokilife** [puppeteer/puppeteer#9392]
### Bug description

I were developing backend on NestJS and ran into a problem. I noticed that Puppeteer doesn't launching when I launch it from class constructor/method called from class constructor. Here is no error but the execution doesn't continues. I looked at troubleshooting guide and found "Chrome headless doesn't launch on Windows" but it's not a solution and Puppeteer successfully launching when called outside class constructor. Maybe I'm missing something but I will submit this issue.

Steps to reproduce the problem:
1. Create file `test.ts`.
2. Paste the following code:
```ts
import puppeteer, { Browser } from 'puppeteer';

class A {
  private _initialized = false;
  browser: Browser;

  constructor() {
    this.initializePuppeteer();

    while (!this._initialized) {}

    console.log("I'm initialized!");
  }

  async initializePuppeteer() {
    console.log('Starting initialization!');
    const browser = await puppeteer.launch();
    console.log('Yes!');
    this.browser = browser;

    this._initialized = true;
  }
}

(async () => {
  const a = new A();
  const page = await a.browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({
    path: 'test.png',
  });
  await page.close();
})();
```
3. Install TypeScript and Puppeteer (`yarn add --dev typescript`, `yarn add puppeteer`).
4. Compile and run it (`yarn tsc test.ts --target esnext --moduleResolution node --module commonjs`, `node test.js`).

### Puppeteer version

^19.4.0

### Node.js version

v16.17.0

### npm version

8.15.0 and yarn version is 1.22.19

### What operating system are you seeing the problem on?

Windows

### Configuration file

```JavaScript
*No configuration file*
```

### Relevant log output

```Shell
Starting initialization!
{And that's all, no errors or other logs}
```

**Comment by OrKoN** [comment]
You seem to have an infinite loop that never resolves: while (!this._initialized) {}
