### ISSUE TITLE
[Bug]: Frame not found for the given storage id

### ISSUE THREAD

**Issue by tzbo** [puppeteer/puppeteer#9393]
### Bug description

Steps to reproduce the problem:
```
        const handle = (request: HTTPRequest) => {
                return request.respond({ status: 200, body: `<html></html>` });
        };
        await this.page0.setRequestInterception(true);
        page0.on('request', handle);
        const session = await page0.target().createCDPSession();
        const url = new URL('http://a.b.c');
        await page0.goto(url.origin);
        const items = await session.send('DOMStorage.getDOMStorageItems', {
            storageId: { isLocalStorage: true, securityOrigin: url.origin }
        });
```

### Puppeteer version

19.4.0

### Node.js version

18

### npm version

8.4

### What operating system are you seeing the problem on?

macOS

**Comment by OrKoN** [comment]
Please share a code that we can execute https://stackoverflow.com/help/minimal-reproducible-example

**Comment by tzbo** [comment]
Sorry, this bug is invalide.

**Comment by tzbo** [comment]
```
    const pptr = await puppeteer.launch({ headless: false, executablePath: executablePath() });
    const ctx = await pptr.createIncognitoBrowserContext();
    const page = await ctx.newPage();
    await ctx.newPage();
    const handle = (request: HTTPRequest) => {
        return request.respond({ status: 200, body: `<html></html>` });
    };
    await page.setRequestInterception(true);
    page.on('request', handle);
    const session = await page.target().createCDPSession();
    const url = new URL('http://a.b.c');
    await page.goto(url.origin);
    const items = await session.send('DOMStorage.getDOMStorageItems', {
        storageId: { isLocalStorage: true, securityOrigin: url.origin }
    });
    console.log(items);
```
ProtocolError: Protocol error (DOMStorage.getDOMStorageItems): Frame not found for the given storage id

**Comment by OrKoN** [comment]
Since Puppeteer does not support this method, it could be a problem with CDP or more likely that the storage ID is not correct as the error says. I suggest you file a bug at crbug.com if you believe the storage ID is correct.

**Comment by tzbo** [comment]
No problem for 19.3.0.

**Comment by OrKoN** [comment]
@tzbo Chromium version was updated in 19.4.0 (perhaps something has changed in Chromium).

**Comment by OrKoN** [comment]
![Screenshot 2022-12-15 at 18 09 05](https://user-images.githubusercontent.com/399150/208091442-4bd1fa5e-eede-47b1-bd56-6fc438c3231e.png)

Looks like it also happens without Puppeteer at all. Perhaps you could file a crbug.com report for this, I am not sure if it is expected or not.

**Comment by tzbo** [comment]
Thanks, I have opend a issue on crbug.

**Comment by bluepeter** [comment]
I am also having this issue. Any update on a fix would be welcome!

**Comment by LegitTrevorTiernan** [comment]
This appears to be the ticket and has been fixed?
https://issues.chromium.org/issues/40884867
