### ISSUE TITLE
Add referrerPolicy support for page.goto

### ISSUE THREAD

**Issue by schelkun** [puppeteer/puppeteer#9394]
As we can see [Page.goto](https://pptr.dev/api/puppeteer.page.goto/) method does not support `referrerPolicy` parameter.
DevTools protocol documentation says, that we can specify `referrerPolicy` for navigation with specified referer: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate
https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-ReferrerPolicy

Any plans to add referrerPolicy support?

**Comment by OrKoN** [comment]
No plans, happy to review a PR.

**Comment by Lightning00Blade** [comment]
Closing as completed by #9561
