### ISSUE TITLE
Error: Unsupported platform: android

### ISSUE THREAD

**Issue by iixn** [puppeteer/puppeteer#9398]
### Bug description

I was trying to install puppeteer in android device but i got a problem.Puppeteer don't support android.I was investigating on how to install it and i saw people clonating repositories of github,too i saw something about puppeteer-core but i don't really know how it works.Can someone explain me?

### Puppeteer version

14.1.1

### Node.js version

v19.2.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
Hey, that's right we currently don't support Android because we have no mechanism to download browser binaries for it. Try using puppeteer-core and connect to/launch an existing browser instance.

**Comment by iixn** [comment]
> Hey, that's right we currently don't support Android because we have no mechanism to download browser binaries for it. Try using puppeteer-core and connect to/launch an existing browser instance.

yea i tried installing puppeteer-core with npm but it throws an error, the same as puppeteer,unsupported platform

i don't really know if im installing it right or not. Puppeteer-core installs with npm?
