### ISSUE TITLE
[Bug]: PDF generator should not take in account hidden overflow contents leftover

### ISSUE THREAD

**Issue by maxcuttins** [puppeteer/puppeteer#9408]
### Bug description

Steps to reproduce the problem:

1. Create an html document with a div with exact width of the page (100%) and "overflow:hidden".
2. Place some nested DIV partially outside of the parent div with overflow hidden.
5. Generate a PDF with puppeteer

I have create 2 case.
One with right behaviour
One with wrong behaviour triggered by an absolute element that overflow outside document page.

## CASE A) Right Behaviour
if the absolute elements are completly within the page, puppeteer will create a 1 page per 1 DIV document with the same size of the viewport.
- Test page:  https://team-hfshoes.com/_test/test-case-A.html
- Test output: https://team-hfshoes.com/_test/test-case-A.php

## CASE B) Wrong Behaviour
If an absolute element is partially outside the page, puppeteers will create a document with higher width even if forced to do not (page width + hidden overflow elements leftover). This will force the document to scale the width and will break the entire document.
- Test page:  https://team-hfshoes.com/_test/test-case-B.html
- Test output: https://team-hfshoes.com/_test/test-case-B.php

Puppetters should NOT take in account hidden contents to size the page.

 

### Puppeteer version

19.4.0

### Node.js version

17.9

### npm version

8.5.5

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
@maxcuttins does the issue reproduce without using Puppeteer using the browser's print to pdf dialog?

**Comment by OrKoN** [comment]
It looks like it does reproduce with the built-in print dialog. Could you please open an issue with crbug.com in this case? Puppeteer has no PDF generator and only forwards PDFs generated by the browser.

**Comment by OrKoN** [comment]
I am unable to repro with Chrome 111.0.5559.0 (let's check after Puppeteer gets the update).

**Comment by borriglione** [comment]
I can reproduce it with `"puppeteer": "22.15.0"` and can confirm @maxcuttins case
