### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#9416]
### Bug description

I run the puppeteer in head mode to see his work. I specify the line "--disable-save-password-bubble", but I still see a window with a suggestion to save the password. What is the way to disable this?

### Puppeteer version

19.2.2

### Node.js version

18.12

### npm version

9.1.2

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
This is out of scope for Puppeteer. See the list of the browser flags here https://peter.sh/experiments/chromium-command-line-switches/ You can send the flags via the `args` array of the `puppeteer.launch` function.
