### ISSUE TITLE
[Bug]: TS typings broken for v19.3.0 and later with default import

### ISSUE THREAD

**Issue by burtek** [puppeteer/puppeteer#9417]
### Bug description

```ts
import puppeteer from 'puppeteer';
```

Using typescript `~4.9.4`, when I install `puppeteer` of version `19.2.0` this works well and I can use both `puppeteer.launch` method as well as `puppeteer.Borwser` / `puppeteer.Page` types.

When I install `19.3.0` or later (including latest), types are broken - `puppeteer.launch` works well, but references to `puppeteer.Borwser` / `puppeteer.Page` break with `Cannot find namespace 'puppeteer' ts(2503)`

![image](https://user-images.githubusercontent.com/2940958/207845300-bd86fb01-0114-4180-a0e7-56c7ba8b1ff4.png)

The syntax of `import * as puppeteer from ...` works well in all versions

### Puppeteer version

19.3.0 and later

### Node.js version

18.1.0

### npm version

8.8.0

### What operating system are you seeing the problem on?

Windows

**Comment by OrKoN** [comment]
In 19.3.0, we fixed the exports so that the types match what actually is imported. `import puppeteer from 'puppeteer';` is the default import that has a few methods but does not actually have `puppeteer.Browser|puppeteer.Page` classes. To import the classes and their types properly, do the following `import puppeteer, {Page, Browser} from 'puppeteer'` or use the star import.

**Comment by burtek** [comment]
I wish that was pointed out in the changes in [Releases](https://github.com/puppeteer/puppeteer/releases) page. Kind of a breaking change for typescript...

**Comment by OrKoN** [comment]
@burtek wish so too but it went unnoticed from our side unfortunately because we didn't have TS coverage for the Page/Browser imports https://github.com/puppeteer/puppeteer/blob/main/test-d/puppeteer.test-d.ts

**Comment by burtek** [comment]
No worries, thanks for explanation. Changed all imports to match updated exports, works well.
