### ISSUE TITLE
[Feature Request]: use CHROME_BIN if present as a source for configuration.executablePath

### ISSUE THREAD

**Issue by EvanCarroll** [puppeteer/puppeteer#9418]
### Bug description

Currently Puppeteer forces the use of `PUPPETEER_EXECUTABLE_PATH`,

I think it's subpar to name it `_PATH` either way, but the convention for images that also must host selenium, or protractor, karma, or other utilities is `CHROME_BIN`. I would suggest using or adopting this convention, or at the least sourcing from the environmental variable `CHROME_BIN`.

This request is to add `CHROME_BIN` to this https://github.com/puppeteer/puppeteer/blob/4bf338b26d6cceae2dc718074ed9839e905905f2/packages/puppeteer/src/getConfiguration.ts#L49

### Puppeteer version

current

### Node.js version

current

### npm version

current

### What operating system are you seeing the problem on?

Linux

**Comment by jrandolf** [comment]
We don't do any special sourcing in Puppeteer. In particular, there is an expectation that the executablePath is absolute, so I don't see how this would be relevant.

We could maybe add this to the resolution algorithm for channels. What's the structure of CHROME_BIN?

**Comment by EvanCarroll** [comment]
@jrandolf that's on me, I need to file another bug on another project that's related to this. See if the update clarifies things though.

**Comment by jrandolf** [comment]
Gotcha. All for it, just send a PR!

**Comment by EvanCarroll** [comment]
This is going to require work on the CI files too, because currently our testing assumes,

* If `CHROME_BIN` is set, ignore it.

And that's a problem because we're using `ubuntu-latest` which is built with `google-chrome.sh`  which actually has this `CHROME_BIN` set...

https://github.com/actions/runner-images/blob/fb484d95309e2fdb6b943ba345c0e0975de10e68/images/linux/scripts/installers/google-chrome.sh#L61

So in light of this, this is technically a non-breaking change. Anyone who has `CHROME_BIN` set in an image and was relying on it **NOT** being used, like our pipeline tests will magically find out that it's being used. @jrandolf I'm thinking we can ignore this even if we're effected by it and just use `feat` though? Will fix tests.

**Comment by OrKoN** [comment]
@EvanCarroll this definitely complicates things. Thanks for the comment and the research! We will discuss it internally.

**Comment by OrKoN** [comment]
So we think the cost is too high to enable this by default given that it's easy for anyone to re-map one variable to the puppeteer-specific one. The only opportunity to ship it would by making this new behaviour an opt-in mechanism: e.g., `PUPPETEER_USE_CHROME_BIN_CONVENTION=true` would make Puppeteer look into CHROME_BIN & FIREFOX_BIN variables.

**Comment by EvanCarroll** [comment]
Opinion on this
====
Cool, I'll close the issue then but I expect to see it pop up if `CHROME_BIN` or `FIREFOX_BIN` is set I'm going to guess 100% of people do not_want_ these utilities downloaded it so we're at an impasse and have a different understanding. Even in this case where it is set in image creation, the reason is because _no one_ is going to want their image to download a newer copy. And if they do want a newer copy, what they'd do is pull down ubuntu-latest, layer a newer chrome in the same place by rerunning the same `google-chrome.sh`.

Images for runners are supposed to be fully baked. If they're not the result isn't reproducible. The idea that a testing framework has an environment not known until execution that based on the executable on Chrome's server seems like an un-ideal defalt.

Remember, if `CHROME_BIN` and `FIREFOX_BIN` are NOT set nothing changes.

Other potential solution
====
 I mean if they do want that... maybe some do. They should be setting the flag to enable the download regardless of  `CHROME_BIN` set. For example, let's say an image was baked with

```
CHROME_BIN=/foo/bar/baz
FIREFOX_BIN=/foo/bar/qux
```

What is `puppeteer`

* default to CHROME_BIN
* could be run with `PUPPETEER_PRODUCT=firefox puppeteer` to use to `FIREFOX_BIN`
* could download as it currently does with `PUPPETEER_FORCE_DOWNLOAD=1`

Regardless I'm good now, I'm just trying to save everyone using this stuff in a pipeline at a company from running into these problems.
