### ISSUE TITLE
[Bug]: configuration.skipDownload should factor in whether the configuration.executablePath is set in the evironment.

### ISSUE THREAD

**Issue by EvanCarroll** [puppeteer/puppeteer#9419]
### Bug description

Currently if the user is providing the binary location of Chromium, the user must also say _not_ to download chrome through a different environmental variable.

```
  configuration.skipDownload = Boolean(
    process.env['PUPPETEER_SKIP_DOWNLOAD'] ??
      process.env['npm_config_puppeteer_skip_download'] ??
      process.env['npm_package_config_puppeteer_skip_download'] ??
      process.env['PUPPETEER_SKIP_CHROMIUM_DOWNLOAD'] ??
      process.env['npm_config_puppeteer_skip_chromium_download'] ??
      process.env['npm_package_config_puppeteer_skip_chromium_download'] ??
      configuration.skipDownload
  );
```

https://github.com/puppeteer/puppeteer/blob/4bf338b26d6cceae2dc718074ed9839e905905f2/packages/puppeteer/src/getConfiguration.ts

In my opinion `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` should default to on if `configuration.executablePath` is set with any of those environmental variables. Why would you ever want to download Chrome if the user is telling you to source on the system a specific pre-installed copy of Chrome?

### Puppeteer version

current

### Node.js version

current

### npm version

current

### What operating system are you seeing the problem on?

Linux

**Comment by jrandolf** [comment]
Sounds reasonable! Would you like to submit a PR?

**Comment by EvanCarroll** [comment]
Sure. On the way.
