### ISSUE TITLE
Page break within table doesn't work 

### ISSUE THREAD

**Issue by ShaileshDeveloper** [puppeteer/puppeteer#9435]
If you see in the red box , the page break is not working properly , half of the line is cut .
Please provide help for this
![image](https://user-images.githubusercontent.com/74795973/208399244-8c72e1f5-7350-4d7a-8e76-66c54c6fdb38.png)

**Comment by jrandolf** [comment]
Please file a new issue with the improved bug form. We will try to reproduce it there.
