### ISSUE TITLE
[Bug]: [Firefox] proxy port is not set by extraPrefsFirefox

### ISSUE THREAD

**Issue by kiber-io** [puppeteer/puppeteer#9437]
### Bug description

Absolutely the same situation with the http(s) proxy.

Steps to reproduce the problem:

1. Run the code below
```javascript
import { launch } from 'puppeteer-core';

(async () => {
    await launch({
        product: 'firefox',
        executablePath: '/usr/bin/firefox',
        headless: false,
        extraPrefsFirefox: {
            // successfully set
            'network.proxy.socks': '127.0.0.1',
            // it is not set in any way
            // an attempt to set the port as int did not lead to success
            'network.proxy.socks_port': '8888'
        }
    });
    console.log('launched');
})();
```
2. Check **about:config**
3. **_network.proxy.socks_port_** equals 0

Screenshot:
![изображение](https://user-images.githubusercontent.com/60169133/208437186-7003c143-1ae3-4b2e-a744-cf92e55026b7.png)

### Firefox version

102.5.0esr

### Puppeteer version

19.4.1

### Node.js version

16.15.0

### npm version

9.1.2

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
cc @whimboo

**Comment by whimboo** [comment]
Please note that `network.proxy.socks_port` is a number pref and as the testcase above shows a string value gets set.

I'm fairly sure it will work with `'network.proxy.socks_port': 8888`.

**Comment by kiber-io** [comment]
I had such an idea, so I specifically indicated in the initial message that I had already tried to do this and it did not lead to a result:
> ```js
> // an attempt to set the port as int did not lead to success
> ```

**Comment by whimboo** [comment]
I tested myself with a recent Firefox Nightly build and Puppeteer 19.1.4. It works just fine. But I just saw that you are using a kinda old Firefox build. Would you mind checking with a Firefox 110 Nightly build?

**Comment by whimboo** [comment]
Note that we do not officially support other Firefox versions than Nightly for Puppeteer / CDP.

**Comment by kiber-io** [comment]
> But I just saw that you are using a kinda old Firefox build

I just installed the version from the centos repository :D 


> Would you mind checking with a Firefox 110 Nightly build?

I will test it tomorrow, at the same time I will check again to set exactly the numeric value

**Comment by whimboo** [comment]
Running `PUPPETEER_PRODUCT=firefox npm install` within the puppeteer folder should get you the latest Firefox Nightly build.

**Comment by kiber-io** [comment]
I'm a fool : (
still, a string was passed to me, although for some reason I was sure that there was a number there. everything worked and even on the stable 102 version

**Comment by whimboo** [comment]
Great to hear!
