### ISSUE TITLE
[Bug]: Puppeteer cannot launch on Firebase Scheduled Functions (GCP)

### ISSUE THREAD

**Issue by silvanohirtie** [puppeteer/puppeteer#9441]
### Bug description

Hi, I'm trying to run my Puppeteer version `19.4.1` code on Firebase (Google Cloud Function Scheduler). 

But I'm getting the 
`Error: Could not find Chromium` error in the CGP logs.

My settings for the browser are:
```
    headless: true,
    args: [
    	'--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
        "--no-sandbox", 
        "--disable-setuid-sandbox",
      ],
     ignoreDefaultArgs: ["--disable-extensions"]
```
I tried setting the executablePath to `/usr/bin/chromium` which is the path of the chromium app I got from GCP terminal.
This lead to an error saying puppeteer failed to spawn chromium browser from that directory (ENOENT, so I assume it is unable to get that path).
I even tried using puppeteer-core, but got the same issues.

My last try was creating a .puppeteer.cjs with the following code inside:

```
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

But that just gives the `Unable to find Chromium` error again.

### Puppeteer version

19.4.1

### Node.js version

16.19.0

### npm version

8.19.3

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf** [comment]
Configuration files are only read for Puppeteer, not Puppeteer Core.

**Comment by silvanohirtie** [comment]
i used the config file with puppeteer, not the core version. I solved the issue by using **_puppeteer-chromium-resolver_** (PCR), but I would like to know if there's any solution without using other dependencies. The executable is in **_/usr/bin/chromium_**, but even PCR cannot find that and installs a new chromium executable from a mirror at every execution, I believe GCP does not allow you to store data outside the /tmp/ directory

**Comment by jrandolf** [comment]
I recommend asking this on Stackoverflow since this looks to be related with setup in GCP rather than a Puppeteer bug.

**Comment by janikga** [comment]
Ran into the same issue as OP (now with `node 18` and `puppeteer 20.4.0`). It looks like the team is aware that running puppeteer on Google Cloud Functions is generally an issue (see this [section](https://pptr.dev/troubleshooting#running-puppeteer-on-google-cloud-functions) in troubleshooting).
I also had no success with https://www.npmjs.com/package/puppeteer-chromium-resolver; it seems like the latest Cloud Functions runtimes indeed do not have all the required dependencies to run Chromium.
What worked for me was to switch to [Google Cloud Run](https://cloud.google.com/run/docs/) instead, where you can run containerized jobs. Here, I made use of the official [puppeteer docker image](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer) (do not forget to include a [.puppeteerrc.cjs file](https://pptr.dev/troubleshooting#could-not-find-expected-browser-locally) as well) together with my source code. You can then publish it to the image registry and set up a Google Run job that executes the image (follow [these steps](https://cloud.google.com/run/docs/quickstarts/jobs/build-create-nodejs)), and combine it with a scheduling trigger. Hope this helps someone!

**Comment by jedrivisser** [comment]
I got this working 

In addition to the `puppeteer.config.cjs` of:

```
// Based on https://pptr.dev/troubleshooting#could-not-find-expected-browser-locally
// And https://pptr.dev/troubleshooting#running-puppeteer-on-google-cloud-functions
// Also update package.json with a postinstall script: "scripts": { ..., "postinstall": "npx puppeteer browsers install chrome" },
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, 'node_modules', '.puppeteer_cache'),
};
```

You also need to add a postinstall script to your package.json:

```
{
  "scripts": { 
   ...snip...
    "postinstall": "npx puppeteer browsers install chrome"
  },
  ...snip...
}
```

You will then also see in the execution logs that you need to increase you function memory for it to work, something like

```
// Set memory limit based on: https://firebase.google.com/docs/functions/manage-functions#set-timeout
export const myCron = onSchedule(
  {
    ...snip...
    memory: "1GiB",
  },
  async () => {
    await toStuff();
  }
);
```
