### ISSUE TITLE
[Bug]: Calling brower.newPage() from within a loop can result in silent OOM

### ISSUE THREAD

**Issue by JohnnyRacer** [puppeteer/puppeteer#9442]
### Bug description

Hello, I had some code that was calling `brower.newPage()` in a recursive loop. The code would sometimes freeze without any warnings or core dumps. I realized that puppeteer would silently crash if the process OOMs, as I observe the memory usage by node.js increase incrementally until it uses all available system memory.

```javascript
import puppeteer, {executablePath} from "puppeteer";

(async (url:string) => {
    const browser = await puppeteer.launch({
        headless: true,
        executablePath:executablePath(),
    }); 

    while (true) {
        // Using an infinite loop as an extreme example, the same OOM happens for large iterations of recursive.
        let page = await browser.newPage();
        await page.goto(url);
        await page.$('#some-element'); // An example of having the page do something
    };

    await browser.close();
        
})('www.example.com');
```
The code fails silently.

```javascript
import puppeteer, {executablePath} from "puppeteer";

(async (url:string) => {
    const browser = await puppeteer.launch({
        headless: true,
        executablePath:executablePath(),
    }); 

    while (true) {
        // Using an infinite loop as an extreme example, the same OOM happens for large iterations of recursive.
        let page = await browser.newPage();
        await page.goto(url);
        await page.$('#some-element'); // An example of having the page do something
        await page.close();
    };

    await browser.close();
        
})('www.example.com');
```
This code will not use up all the memory.

### Puppeteer version

19.4.1

### Node.js version

v18.12.1

### npm version

9.1.3

### What operating system are you seeing the problem on?

Linux

**Comment by OrKoN** [comment]
I would say this is expected:

1) you have to dispose element handles you receive from querying the page https://pptr.dev/api/puppeteer.jshandle/
2) creating an infinite number of pages without closing them will obviously consume all memory in the browser as well as in the Puppeteer's process.
