### ISSUE TITLE
[Bug]: Unsupported platform: openbsd

### ISSUE THREAD

**Issue by anoduck** [puppeteer/puppeteer#9445]
### Bug description

Steps to reproduce the problem:

1. Select one of the many nodejs packages that require puppeteer as a dependency.
2. Attempt to install it using `?(sudo) npm i -g $PACKAGE`
3. Hit the enter key.
4. Wait with anticipation. 
5. Almost complete installation.
6. Watch as installation throws error status, stating platform is unsupported.

### Puppeteer version

@latest

### Node.js version

16.17.1

### npm version

8.15.0

### What operating system are you seeing the problem on?

Linux, macOS

### Configuration file

```JavaScript
N/A
```

### Relevant log output

```Shell
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh /tmp/postinstall-65edf4a1.sh
npm ERR! /usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
npm ERR!         throw new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Unsupported platform: openbsd
npm ERR!     at assert (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
npm ERR!     at new BrowserFetcher (/usr/local/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:215:44)
npm ERR!     at downloadBrowser (/usr/local/lib/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:49:28)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/puppeteer/install.js:40:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1126:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1004:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-12-21T06_57_52_749Z-debug-0.log
```

**Comment by OrKoN** [comment]
openbsd is not supported indeed (what does running `node -e "console.log(process.platform)"` outputs on your system?). I doubt you would see it on linux or mac as you report and I am unable to reproduce that.

**Comment by anoduck** [comment]
> openbsd is not supported indeed (what does running `node -e "console.log(process.platform)"` outputs on your system?). 

`openbsd`

> I doubt you would see it on linux or mac as you report and I am unable to reproduce that.

Ok... as to be expected, and as it should, since you are not running OpenBSD. May I ask, "Why?". Is there something preventing compatibility?
