### ISSUE TITLE
[Bug][Firefox]: page.evaluate hangs when executed on a page with an open image

### ISSUE THREAD

**Issue by kiber-io** [puppeteer/puppeteer#9446]
### Bug description

Steps to reproduce the problem:

1. Run the code (there can be absolutely any code in evaluate, for example, I took the simplest)
```js
import { launch } from 'puppeteer';

(async () => {
    const browser = await launch({
        product: 'firefox',
        headless: false,
    });
    const page = await browser.newPage();
    await page.goto('https://uprostim.com/wp-content/uploads/2021/05/image014-7.jpg');
    let result = await page.evaluate('1+1');
    console.log(result);
})();
```
2. Wait for console log (he won't be there). Execution hangs on the line marked in the screenshot.

Also does not work
```js
let result = await page.evaluate(() => 1+1);
```

![изображение](https://user-images.githubusercontent.com/60169133/208882727-4d00bcd4-1a10-455b-a29e-4b3b1b9f2d85.png)

### Puppeteer version

19.4.1

### Node.js version

16.15.0

### npm version

9.1.2

### What operating system are you seeing the problem on?

Linux

### Firefox version
Nightly 110.0a1 (2022-12-20)
this version was automatically downloaded along with the installation of puppeteer.
The same problem on Stable 102.5.0esr

**Comment by OrKoN** [comment]
cc @whimboo

**Comment by whimboo** [comment]
I'm fairly sure this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1706353.

**Comment by whimboo** [comment]
Updating summary to reflect the situation.

**Comment by kiber-io** [comment]
But it's not .goto that hangs. It works out correctly and execution proceeds to the next line (page.evaluate) after which it hangs.
This is easily tracked using a debugger

**Comment by whimboo** [comment]
Well, I cannot see in the logs that the evaluate command `1+1` is send to Firefox. So it might be a combination of `page.goto` and `page.evaluate` then, and maybe it hangs somewhere in Puppeteer waiting for an event?

Sadly I don't have the time to further investigate it in the Puppeteer code and our CDP support in Firefox is currently in maintenance-only mode. As such some further help would be appreciated.  Lets revert the summary for now.

**Comment by OrKoN** [comment]
I don't think it will be addressed so closing as not planned.
