### ISSUE TITLE
[Bug]: Unexpected behavior using IDs with Typescript

### ISSUE THREAD

**Issue by DoormatIka** [puppeteer/puppeteer#9449]
### Bug description

I use Typescript (dev dependency - 4.9.4) and use ts-node (10.9.1) as a runner
Steps to reproduce the problem:

1. I loaded the page using this function: `await page.goto("https://chooseyourstory.com/Stories/top.aspx", { waitUntil: "domcontentloaded" });`

2. I went to one of the "stories" using this function: `await page.goto(link, { waitUntil: "load" });`

3. I tried catching the popup when the "Play (story name here)" button gets clicked.
```
const newPagePromise = new Promise<puppeteer.Page>(x => page.once("popup", x));
const startButton = await page.$("#ct119 input")
await startButton?.click();
const newPage = await newPagePromise;
await newPage.close();
```
The button does not get clicked. Puppeteer takes no action.
However, replacing the ID with a class works. I tried `[id=id here]` and `#idhere` but still no luck.

### Puppeteer version

19.4.1

### Node.js version

v18.12.1

### npm version

9.2.0

### What operating system are you seeing the problem on?

Windows

### Configuration file

```JavaScript
tsconfig.json
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "ES2020",
    "moduleResolution": "Node16",
    "esModuleInterop": true, 
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "ts-node": {
    "esm": true
  }
}

package.json
{
  "name": "web-scraper",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "npx ts-node index.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lowdb": "^5.0.5",
    "puppeteer": "^19.4.1"
  },
  "devDependencies": {
    "typescript": "^4.9.4"
  },
  "type": "module"
}
```

**Comment by Lightning00Blade** [comment]
Hey @DoormatIka from the look I took it seems to work. I did spot that in your code you use `#ct119 input` while the website you mentions has `#ctl19 input` (The first `1` should be lower case `L`). Pasting my snippet down bellow for reference:
```
  await page.goto("https://chooseyourstory.com/story/eternal", {
    waitUntil: "load",
  });

  const popUpPromise = new Promise<Page>((resolve) =>
    page.once("popup", (popup) => resolve(popup))
  );
  const startButton = await page.$("#ctl19 input");
  await startButton?.click();
  const popUp = await popUpPromise;
  // Need if you want to do something on the popup
  await popUp.waitForNetworkIdle();

  await browser.close();
```

If the issue persist reopen and provide a Minimal, Reproducible Example. You can find more info on how to do this on [https://stackoverflow.com/help/minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example).
