### ISSUE TITLE
[Feature]: Use Node.js 18 (LTS) as Docker base image

### ISSUE THREAD

**Issue by meyfa** [puppeteer/puppeteer#9453]
### Feature description

Given that Node 18 is now LTS, it might make sense to update `docker/Dockerfile` to use `FROM node:18` instead of `FROM node:16`, to support use cases that depend on newer Node.js features.

**Background:**

Our team is trying to use internal testing libraries inside the Puppeteer Docker image. They have a requirement of Node v18 or newer, though, and the following issue comes up on `npm ci` (npm install):

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '<REDACTED>',
npm WARN EBADENGINE   required: { node: '>=18', npm: '>=7' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```

**Additional info:**

Note that Node 16 has its end-of-life at 2023-09-11, while 18 has its end-of-life at 2025-04-30 (https://github.com/nodejs/release#release-schedule). So, in 8 months at the latest, this change would have to be made either way.

**Comment by tailgo** [comment]
I created a image with node-18 (no published), you can checkout [my repo](https://github.com/tailgo/puppeteer/tree/feat/use-nodejs18-as-docker-base-image/docker) to build your own image.
After checkout repos, typing those comands below:

``` shell
npm install
npm run build
./docker/pack.sh
cd docker && docker build -t puppeteer-chrome-linux .
```

you can modify your docker image name as you want.

And the pr #9456  has been created. Waiting for acceptance.
