### ISSUE TITLE
[Bug]: When executablePath contains UNC file path for windows, chrome pops up and closes immediately.

### ISSUE THREAD

**Issue by webnoob** [puppeteer/puppeteer#9454]
### Bug description

Steps to reproduce the problem:

Launch with a UNC path:

```js
browser = await puppeteer.launch({
      headless: false,
      executablePath: '\\?\C:\some\path\to\chrome.exe'
})

page = (await browser.pages())[0]
await page.goto('https://google.com', {
  waitUntil: 'networkidle0',
});
```

When launching this way (with `\\?\` ) the browser window pops up very briefly and closes immediately leaving the connection waiting (which times out after the default 30 seconds)

If you remove the `\\?\` part of the path, everything works as expected (assuming you use the correct chrome path)

### Puppeteer version

16.2.0

### Node.js version

14.19.0

### npm version

6.14.16

### What operating system are you seeing the problem on?

Windows

**Comment by Lightning00Blade** [comment]
Hey @webnoob is the issue reproducible on the latest version?

**Comment by jrandolf** [comment]
Please file a new issue with the improved bug form. We will try to reproduce it there.
