### ISSUE TITLE
Provide 'DOMContentLoaded' option for waitUntil in page.goto()

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#946]
It would be a faster variant for cases when the DOM tree suffices to retrieve some info.

https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

**Comment by jamesmartinduffy** [comment]
+1, this would be great. When parallel crawling some resource-heavy pages, waiting for a full `load` event before starting navigation significantly slows down the rate of the crawler.

**Comment by gajus** [comment]
@aslushnikov Is PR accepted for this?

**Comment by gregoirepuget** [comment]
Not seems to work : UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError [ERR_ASSERTION]: Unknown value for options.waitUntil: domcontentloaded

**Comment by vsemozhetbyt** [comment]
@gregoirepuget It is available only from the v0.13.0-alpha. You can upgrade by `npm install https://github.com/GoogleChrome/puppeteer/`
