### ISSUE TITLE
[Regression]: Launching Chrome after Firefox breaks due to a regression in version 19.1.0

### ISSUE THREAD

**Issue by timvandermeij** [puppeteer/puppeteer#9461]
### Bug description

During the upgrade of Puppeteer from version 19.0.0 to version 19.1.0 in Mozilla's PDF.js project (https://github.com/mozilla/pdf.js/issues/15865) we ran into the issue that our two browsers (Firefox and Chrome) didn't start correctly anymore. I found out that this is a regression and will provide a reduced test case and what I think is the location of the bug below.

Steps to reproduce the problem:

1. Create a file called `reduced.js` wit the following reduced test case code:

```javascript
const puppeteer = require("puppeteer");

async function startBrowser(browserName) {
  const options = {
    product: browserName,
    headless: false,
  };
  await puppeteer.launch(options);
}

async function startBrowsers() {
  for (const browserName of ["firefox", "chrome"]) {
    await startBrowser(browserName);
  }
}

startBrowsers();
```

2. Install Puppeteer 19.0.0.
3. Run `node reduced.js` and notice that Firefox and Chrome start.
4. Install Puppeteer 19.1.0.
5. Run `node reduced.js` and notice that Firefox starts but Chrome errors with `Tried to find the browser at the configured path (/home/timvandermeij/.cache/puppeteer/chrome/linux-110.0a1/chrome-linux/chrome) for revision 110.0a1, but no executable was found.`. Notice that Puppeteer erroneously puts the Firefox revision in the Chrome path.
6. Switch Firefox and Chrome around in the array in the reduced test case code. Notice that Firefox and Chrome now start just fine again. Therefore, the order suddenly matters.

I traced this back to a regression in commit https://github.com/puppeteer/puppeteer/commit/ec201744f077987b288e3dff52c0906fe700f6fb which landed in version 19.1.0. I think the bug is here: https://github.com/puppeteer/puppeteer/commit/ec201744f077987b288e3dff52c0906fe700f6fb#diff-545f1eb6b4d2825410b4be2eb6f6baa65ab44841c7ef5ff444bb01a5ece66c2aR198. The `FirefoxLauncher` class needs to translate the "latest" revision, which is the default for Firefox, to a concrete revision such as "110.0a1". However, this line overrides the revision globally instead of putting it in a private member variable like before, so from now on any Chrome revision that was set during the intialization of Puppeteer is overwritten with the Firefox revision. Therefore, if you start Chrome next, it will try to use the Firefox revision because in the `ChromeLauncher` code there is no code to set the revision back. If you reverse the browsers in the reduced test case code it doesn't happen anymore because Firefox is last, so any global `this.puppeteer` object mutations it does are still done, but just not used anymore.

/cc @jrandolf as the author of the commit who might have an idea on how to best resolve this issue.

### Puppeteer version

19.1.0

### Node.js version

19.3.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by jrandolf** [comment]
There was never an expectation that Puppeteer would work with more than one browser at the same time since there would generally be a runner to instantiate separate instances of the running script for each browser in separate environments. Could you provide more context into why we should have this?

**Comment by timvandermeij** [comment]
The use case for Mozilla's PDF.js is that we have a test runner that spawns an instance of Chrome and Firefox, runs regression tests in both of them at the same time (because doing it in series would take much longer) and collects the statistics at the end (number of passed/failed tests and logs). The test runner script basically uses the code posted above to launch the browsers and then opens a URL that runs all tests using the Jasmine test runner.

I haven't found documentation on why that shouldn't be possible, also because this worked just fine before 19.1.0. If there is a better way to do this I'm also fine with changing the test runner if you have suggestions, but in general I still feel that this is in fact a regression because this used to work fine and the API usage in the code posted above also feels very logical to me at least, so I can imagine that this is basically how more people would approach this.

**Comment by OrKoN** [comment]
I think we should keep the support for launching multiple possible different browsers. @jrandolf could you PTAL?

**Comment by timvandermeij** [comment]
Thank you for fixing this! We'll upgrade to the most recent version once the release is made.
