### ISSUE TITLE
[Bug]:  puppeteer.launch() is taking too long

### ISSUE THREAD

**Issue by fjpedrosa** [puppeteer/puppeteer#9464]
### Bug description

When starting puppeteer, it takes too long on execute puppeteer.lanch(). Too long means an arbitrary time above 5 mins, but it can be 5 min, 10min or 30min.

Run puppeteer by launching the browser with this settings:

```
const args = [
  '--no-sandbox',
  '--disable-setuid-sandbox',
  '--window-size=1920,1080',
  '--disable-infobars',
  '--window-position=0,0',
  '--ignore-certifcate-errors',
  '--ignore-certifcate-errors-spki-list',
  '--user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36"',
];

  const browser = await puppeteer
    .launch({
      headless: true,
      args,
      timeout: 0,
      ignoreDefaultArgs: [],
      ignoreHTTPSErrors: true,
    })
    .catch((err) =>
      console.log(chalk.red('Error launching puppeteer: ', err))
    );
```

However, if I ser "headless: false" everything runs instantly
### Puppeteer version

19.3.0

### Node.js version

16.18.1

### npm version

8.19.2

### What operating system are you seeing the problem on?

macOS

**Comment by jrandolf** [comment]
Please file a new issue with the improved bug form. We will try to reproduce it there.
