### ISSUE TITLE
[Bug]: Missing scripts

### ISSUE THREAD

**Issue by g-yonchev** [puppeteer/puppeteer#9469]
### Bug description

Hi, I am experiencing an issue with puppeteer when I try to fetch the scripts on a webpage. It seems there are missing ones.

Steps to reproduce the problem:
```
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://www.astrazeneca.vn/');
  const scripts = await page.evaluate(() => Array.from(document.scripts, ({ src }) => src));
  
  // actual output:
  // [
  //   '',
  //   'https://www.astrazeneca.vn/static/js/2.2921daa2.chunk.js',
  //   'https://www.astrazeneca.vn/static/js/main.c9a7ada2.chunk.js'
  // ]
  console.log(scripts);
  await browser.close();
})();
```

And from the image below you can see that on that page there is a script missing from the output:
<img width="1004" alt="Screenshot 2023-01-06 at 14 16 31" src="https://user-images.githubusercontent.com/10466562/211019608-9623b3ae-e619-4af2-9aba-5c9e8818c3b8.png">

### Puppeteer version

19.4.1

### Node.js version

19.3.0

### npm version

9.2.0

### What operating system are you seeing the problem on?

macOS

**Comment by karliky** [comment]
Is it fixed if you `waitForNavigation` after calling goto?
