### ISSUE TITLE
[Bug]: TS2503: Cannot find namespace 'puppeteer' after updating package from 8.2.1 to 9.0.0

### ISSUE THREAD

**Issue by mrink1074** [puppeteer/puppeteer#9471]
### Bug description

Steps to reproduce the problem:

1. Update package from 8.2.1 to 9.0.0
2. After update completed, all references to puppeteer showed as cannot find namespace, suggested to add import statement.  
import puppeteer from 'puppeteer'; already exists
Example: export const getScreenshot = async (page: puppeteer.Page): Promise<string> => {
3. Revert back to 8.2.1, errors go away

### Puppeteer version

9.0.0

### Node.js version

18.12.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

Windows

**Comment by mrink1074** [comment]
Looks like Page and Browser are now separate exports.  Resolved by change import statement to the following:
import puppeteer, { Page, Browser } from 'puppeteer';

Then changing puppeteer.Page and puppeteer.Browser to just Page and Browser respectively.

**Comment by OrKoN** [comment]
I believe it's the same issue as https://github.com/puppeteer/puppeteer/issues/9417
