### ISSUE TITLE
[Bug]: .puppeteerrc.cjs is ignored in monorepo context

### ISSUE THREAD

**Issue by abdalem** [puppeteer/puppeteer#9479]
### Bug description

Steps to reproduce the problem:

1. Initiate a monorepo with turborepo and yarn
2. Add a workspace
3. Add a .puppeteerrc.cjs file to this workspace that rewrite the cacheDirectory
4. Run yarn from the root of the monorepo

As I mentionned it in the title, .puppeteerrc.cjs configs are ignored when install command is run elsewhere than the location of the package.json file that installs puppeteer. In a monorepo context, install commands are performed at the root, not in a workspace. It would be great to have some of the configs available through envs, like cacheDirectory.

### Puppeteer version

19.5.0

### Node.js version

16

### npm version

yarn 1

### What operating system are you seeing the problem on?

Linux, Windows

**Comment by jrandolf** [comment]
See https://pptr.dev/guides/configuration#environment-variables
