### ISSUE TITLE
Is there a way to catch switching to download mode?

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#948]
* Puppeteer version: v0.12.0-alpha
* Platform / OS version: Windows 7 x64
* URLs (if applicable): any with non-openable  content type

A stright attempt just throws a timeout (the file is downloaded successfully though):

```js
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    const response = await page.goto('https://nodejs.org/dist/v8.6.0/node-v8.6.0.tar.gz');

    console.log(response.status);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
```console
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at NavigatorWatcher.waitForNavigation (puppeteer\lib\NavigatorWatcher.js:73:20)
    at <anonymous>
```

**Comment by ks07** [comment]
Also affected by this - navigating to a URL with an unsupported content-type such as `application/octet-stream` always causes navigation to hit the timeout, regardless of how quickly the server responds to the request.

@vsemozhetbyt I hadn't noticed that the files were downloaded, where are they stored?

**Comment by vsemozhetbyt** [comment]
@ks07 If you do not use preallocated user data dir with download dir defined, there are default places, like `c:\Users\%username%\Downloads\` on Windows.

**Comment by ks07** [comment]
After upgrading to puppeteer 0.13.0 this problem has gotten worse. Previously, using 0.12.0, I found it was possible to listen to the `response` event on the page object and determine based on the response headers (i.e. content-type) whether the goto failure was due to an actual timeout or because the URL triggered a download. In 0.13.0 the `response` event is seemingly no longer triggered when visiting a download URL, so it's not possible to detect when this is happening any more.

**Comment by ks07** [comment]
A slight adjustment to the example script posted by @vsemozhetbyt shows how the behaviour has changed:

```javascript
const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({args: ['--no-sandbox']});
    const page = await browser.newPage();

    page.on('response', (resp) => {
        console.log('Got a response.');
    });
    page.on('requestfailed', (req) => {
        console.log('Request failed.');
    });
    page.on('requestfinished', (req) => {
        console.log('Request finished.');
    });

    const response = await page.goto('https://nodejs.org/dist/v8.6.0/node-v8.6.0.tar.gz');

    console.log(response.status);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

With puppeteer@0.12.0:
```
$ node index.js
Got a response.
Got a response.
Request failed.
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at NavigatorWatcher.waitForNavigation (/home/george/chromedltest/node_modules_12/puppeteer/lib/NavigatorWatcher.js:76:20)
    at <anonymous>
```

With puppeteer@0.13.0:
```
$ node index.js
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/home/george/chromedltest/node_modules_13/puppeteer/lib/NavigatorWatcher.js:69:21)
    at <anonymous>
```

This means there's no longer a way to detect when navigation has triggered a download vs a normal timeout. This is unfortunate seeing as we now have a fix for #901

**Comment by ks07** [comment]
I've tried playing with the setDownloadBehavior API mentioned in https://github.com/GoogleChrome/puppeteer/issues/299#issuecomment-342133535 but regardless of whether `behavior` is set to `allow` or `deny` the navigation times out and the various response events aren't triggered.

You could use a combination of `allow` and checking for the existence of a new file in the specified download location, as a hacky workaround.

**Comment by aslushnikov** [comment]
@vsemozhetbyt @ks07 can you please share your usecases? Do I understand correctly that this is different from #299?

**Comment by vsemozhetbyt** [comment]
@aslushnikov I have a script that checks all the links in a doc set. I can use `response.ok` and `response.status()` for openable URLs, but cannot check if non-openable URLs are valid (not 404 or likes).

**Comment by aslushnikov** [comment]
@vsemozhetbyt ah makes sense, thank you for sharing.

**Comment by aslushnikov** [comment]
This behaves much better now. Chromium aborts navigation to resource if it causes a download. With pptr 1.4.0, this kind of navigation results in ERR:Aborted being thrown; with #299 in place we'll also get a download event.
