### ISSUE TITLE
[Bug]: Header font size doesn't not work properly when generating a pdf from html

### ISSUE THREAD

**Issue by marcelocastrillo** [puppeteer/puppeteer#9481]
### Bug expectation

I generated a PDF file from html, using headerTemplate option. The html has font-size:10px, but when I check on the pdf, the font size looks a lot bigger.
 

### Bug behavior

- [ ] Flaky
- [x] No error
- [x] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer')

let browser;
const launchBrowser = async () => {
    if (browser) return;
    browser = await puppeteer.launch();
};

async function printPDF() {
  
  let body = '<!DOCTYPE html><html><head><style>body{font-family: sans-serif !important;font-size: 10px;}</style></head><body><table><tbody><tr><td><table style="width: 100%;" class="pruebaBreak" ><tr><th>SKU</th><th>Product</th><th>Quantity</th><th>Price</th></tr></table></td></tr></tbody></table></body></html>';

  await launchBrowser();
  const page = await browser.newPage();
  await page.setContent(body.toString());
  
  const pdf = await page.pdf({
     format: 'A4', 
     path: "test.pdf", 
     displayHeaderFooter:true, 
     headerTemplate: '<div  class="page-header" ><table><tr><td style="text-align: center;font-size: 10px;font-weight:bold" >TEST</td></tr></table></div>',
     footerTemplate: '<div><span>test</span></div>',
     margin: {
        top: '15px',
        bottom: '1px'
     }
    });
 
  await browser.close();

  return pdf
}

printPDF();
```

### Error string

no error

### Puppeteer version

19.4.1

### Node version

v18.12.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by JJTee** [comment]
@marcelocastrillo I am experiencing the same issue, did you manage to find a workaround?

**Comment by OrKoN** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1430749

**Comment by codeart1st** [comment]
Since Chrome 117+ it's fixed. No need to scale the content with 1.333f

https://github.com/chromium/chromium/commit/f6529c7990744370869e4ab2794caae6c46ba044
