### ISSUE TITLE
[Bug]: Letter Spacing inconsistent when using puppeteer

### ISSUE THREAD

**Issue by DeftEye** [puppeteer/puppeteer#9483]
### Bug expectation

I expected puppeteer to turn my html into a pdf and keep the letter spacing as in my html file sent.

This is what i send to puppeteer : 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/45700361/211770923-b5645efb-be55-49f6-9a08-1ae57fe1af61.png">

This is what puppeteer uploads : 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/45700361/211771473-369066f1-af29-4c11-aac8-a8a189d02ffa.png">

As we can see, the letter spacing is inconsistent between characters.

### Bug behavior

- [ ] Flaky
- [ ] No error
- [x] PDF

### Minimal, reproducible example

```TypeScript
To reproduce this error i run the command shown below and upload the buffer as a byte64.
```

### Error string

Visual bug

### Puppeteer configuration

```TypeScript
const puppeteer = require('puppeteer');

module.exports = {
  generatePdf: async function (htmlContent) {
    const browser = await puppeteer.launch({
      args: [
        // Required for Docker version of Puppeteer
        '--no-sandbox',
        '--disable-setuid-sandbox',
        // This will write shared memory files into /tmp instead of /dev/shm,
        // because Docker’s default for /dev/shm is 64MB
        '--disable-dev-shm-usage',
        '--single-process',
        '--font-render-hinting=none'
      ]
    });
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    const buffer = await page.pdf({ format: 'A4', printBackground: true });
    browser.close();

    return buffer;
  },
```

### Puppeteer version

19.5.0

### Node version

14.19.0

### Package manager

npm

### Package manager version

9.1.2

### Operating system

Windows

**Comment by OrKoN** [comment]
@DeftEye is the letter spacing consistent if you print to pdf using the browser's built-in print dialog?

**Comment by bumbummen99** [comment]
I'm currently experiencing the exact same issue.

@OrKoN When i get the HTML back from puppeteer, manually open that and print it, it does look just fine. However if i use the Page.pdf method the letter spacing and fonts are all messed up.
