### ISSUE TITLE
[Bug]: Im trying to start puppeteer in headless:false mode. It's working on my local machine but when i push it to my server and try to start it i get this error

### ISSUE THREAD

**Issue by AllenChinese** [puppeteer/puppeteer#9486]
### Bug expectation

{
	"msg": "Failed to launch the browser process!\n./chrome-mac/Chromium.app/Contents/MacOS/Chromium: ./chrome-mac/Chromium.app/Contents/MacOS/Chromium: cannot execute binary file\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
	"errors": "Error: Failed to launch the browser process!\n./chrome-mac/Chromium.app/Contents/MacOS/Chromium: ./chrome-mac/Chromium.app/Contents/MacOS/Chromium: cannot execute binary file\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/home/xiaoju/cdx-open-server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)\n    at Interface.<anonymous> (/home/xiaoju/cdx-open-server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)\n    at Interface.emit (events.js:327:22)\n    at Interface.close (readline.js:424:8)\n    at Socket.onend (readline.js:202:10)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
	"code": "1"
}

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const path = require('path');

module.exports = async (ctx, params) => {
  try {
    const { url, width = 375, height = 667 } = params;
    const browser = await puppeteer.launch({
      headless: false,
      executablePath: path.join(__dirname, '../chrome-mac/Chromium.app/Contents/MacOS/Chromium'),
      // path.resolve('../cdx-open-server/chrome-mac/Chromium.app/Contents/MacOS/Chromium'),
    });
    const page = await browser.newPage();
    await page.setViewport({ width, height });
    await page.goto(url);
    const imgBuffer = await page.screenshot({
      type: 'png',
    });
    const base64Str = imgBuffer.toString('base64');
    browser.close();
    return {
      status: 10000,
      data: `data:image/png;base64,${base64Str}`,
      msg: '海报生成成功',
    };
  } catch (error) {
    return {
      msg: error.message,
      errors: error.stack,
      code: '1'
    }
  }
}
```

### Error string

{ 	"msg": "Failed to launch the browser process!\n./chrome-mac/Chromium.app/Contents/MacOS/Chromium: ./chrome-mac/Chromium.app/Contents/MacOS/Chromium: cannot execute binary file\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n", 	"errors": "Error: Failed to launch the browser process!\n./chrome-mac/Chromium.app/Contents/MacOS/Chromium: ./chrome-mac/Chromium.app/Contents/MacOS/Chromium: cannot execute binary file\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/home/xiaoju/cdx-open-server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)\n    at Interface.<anonymous> (/home/xiaoju/cdx-open-server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)\n    at Interface.emit (events.js:327:22)\n    at Interface.close (readline.js:424:8)\n    at Socket.onend (readline.js:202:10)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)", 	"code": "1" }

### Puppeteer version

15.2.2

### Node version

14.15.0

### Package manager

npm

### Package manager version

8.11.0

### Operating system

Linux

**Comment by ASGdev** [comment]
I think you should update the `executablePath` pointing to correct Chrome binary on your server, as it may not be the same than the path you use on your local machine (I suspect from your example you are using a Mac installation). For instance, on one of my Linux server, the Chrome binary is located at `/bin/google-chrome` after usual installation procedure.

**Comment by OrKoN** [comment]
also, on the server you cannot run headless:false if it does not have a window environment...

**Comment by OrKoN** [comment]
I am unable to repro the issue locally. I believe the problem is specific to the server environment or the configuration like @ASGdev suggested.
