### ISSUE TITLE
Replace `injectFile` to `injectScript` and add `injectCSS`

### ISSUE THREAD

**Issue by SamVerschueren** [puppeteer/puppeteer#949]
When browsing trough the docs and using the API, I noticed that Puppeteer has an `injectFile` method. The name might be confusing, because you might think it works for a CSS file as well. I think it would be better to rename this method to `injectScript` and also add a `injectCSS` method.

Just an idea though :).

**Comment by vsemozhetbyt** [comment]
CSS injecting seems to be possible when https://github.com/GoogleChrome/puppeteer/pull/947 is landed.

**Comment by aslushnikov** [comment]
@vsemozhetbyt `injectFile` injects from file system, whereas `addStyleTag` adds a url. I'd rather unify the two methods since it's confusing.

Something like:

```js
page.addScriptTag({
  url: '...', // either URL or PATH could be specified
  path: '..',
});
```

**Comment by SamVerschueren** [comment]
`addScriptTag` and `addStyleTag` currently already work with a local file path, that's what the tests do as well. Not sure if it's a good idea though, that's probably the reason why `injectFile` exists.

If we would go with your solution, an object with `url` and `path`, it might be nice to have a `content` option as well.

```js
page.addScriptTag({
  url: '...',
  path: '..',
  content: `document.write('Hello World')`
});
```

**Comment by SamVerschueren** [comment]
@aslushnikov Let me know what the preferred path forward is for this. Happy to do a PR to fix this.

**Comment by aslushnikov** [comment]
> @aslushnikov Let me know what the preferred path forward is for this. Happy to do a PR to fix this.

@SamVerschueren Your suggestion with url/path/content options sounds good to me:

```js
page.addScriptTag({
  url: '...',
  path: '..',
  content: `document.write('Hello World')`
});
```

if you have time, I'd be happy to review a PR. (note: please make sure to use sourceURL for the 'content' option of the addScriptTag/addStyleTag methods).

If you're short on time, I'd rather do it myself: this is one of the bugs that we'd like to have closed soon.

**Comment by SamVerschueren** [comment]
I'll try to work on it today.

Can you elaborate on
> make sure to use sourceURL for the 'content' option of the addScriptTag/addStyleTag methods

Or do you mean 
> make sure to use sourceURL for the `path` option

**Comment by aslushnikov** [comment]
>Or do you mean
>
>>make sure to use sourceURL for the path option

That's right, I meant `path` option.

**Comment by SamVerschueren** [comment]
PR send!
