### ISSUE TITLE
[Bug]: Request Timeout

### ISSUE THREAD

**Issue by francescomezzapesa** [puppeteer/puppeteer#9494]
### Bug expectation

I installed puppeteer on my server and created a script for generating a screenshot.
When I run the request I get this error: "Request Timeout
This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.".

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const express = require("express");
const puppeteer = require('puppeteer');

const app = express();

app.get("/pdf", async (req, res) => {

    const browser = await puppeteer.launch({
        headless: true,
      ignoreHTTPSErrors: true,
      args: [`--window-size=1920,1080`],
      defaultViewport: {
        width:1920,
        height:1080
      }
    });
    const page = await browser.newPage();
    await page.goto('https://www.youtube.com/');
    await page.screenshot({path: 'example.png'});

    await browser.close();

});

app.listen(6795, () => {
    console.log("Server started");
});
```

### Error string

Request Timeout
This request takes too long to process, it is timed out by the server. If it should not be timed out, please contact administrator of this web site to increase 'Connection Timeout'.

### Puppeteer version

19.5.0

### Node version

14.20.1

### Package manager

npm

### Package manager version

6.14.12

### Operating system

Linux

**Comment by OrKoN** [comment]
Unable to reproduce. The problem is likely with your server environment: you need to make sure it has all dependencies for running chromium and that is has enough memory and cpu to launch and stop the browser within a single request.
