### ISSUE TITLE
Table row gets split between PDF pages

### ISSUE THREAD

**Issue by NeelakantanS** [puppeteer/puppeteer#9499]
### Bug description:

When printing a long table as PDF, individual rows get split between 2 pages.
Using `page-break: always`, or `break-inside: avoid` styling on all tr elements didn't help.

### Steps to reproduce the problem:
The entire issue has been reproduced in this repository, with a sample PDF file generated.
https://github.com/NeelakantanS/puppetteer-page-break.git

### Puppeteer version
18.0.5

### Node.js version
16.6.0

### npm version
7.19.1

**Comment by OrKoN** [comment]
Does it reproduce if you print the page using the regular chrome browser?

**Comment by NeelakantanS** [comment]
@OrKoN no, it doesn't.

**Comment by OrKoN** [comment]
@NeelakantanS can you try using the latest puppeteer version?

**Comment by OrKoN** [comment]
@NeelakantanS could you try in the latest version? some PDF fixes has been done in the latest Chromium,
