### ISSUE TITLE
How to install dependencies?

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#950]
I'm using an Ubuntu 14.04 (64 bit) and when I try to launch puppeteer i get this error message:

```
Error: Failed to launch chrome!
/home/cabox/workspace/node_modules/puppeteer/.local-chromium/linux-499413/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory
```

I read in other issues that there is some kind of a problem with shared libraries in Linux. I'm haven't used Linux much before and I don't really know how to install dependencies but I did see in troubleshooting.md that I'm supposed to check that all dependencies are installed. How can I install libpangocairo?

**Comment by Garbee** [comment]
Use the package manager (`apt-get` for 14.04) in your terminal to install the packages listed in the troubleshooting document.

You may want to reach out to an Ubuntu support area such as AskUbuntu or the Ubuntu IRC channel for support with that if you need more guidance.

**Comment by curran** [comment]
For reference: [troubleshooting document](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)
