### ISSUE TITLE
[Bug]: Why cant i pass function as argument to $$eval ?

### ISSUE THREAD

**Issue by lowzyyy** [puppeteer/puppeteer#9509]
### Bug expectation

I expected that i could use function inside $$eval but node js is telling me that function is undefined.
Its a little bit messy to have ton of code sitting inside map function so i tried to use/pass function to clean the code

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const foo = (e) => e;
  const details = await page.$$eval(
    "section div details",
    (details, f) =>
      details.map((el) => {
        // cant even map elements to numbers
        const mainDetails = f(10);
        return { mainDetails };
      }),
    foo
  );
```

### Error string

Error: Evaluation failed: TypeError: f is not a function

### Puppeteer version

19.5.2

### Node version

16.15.0

### Package manager

npm

### Package manager version

8.5.5

### Operating system

Windows

**Comment by OrKoN** [comment]
Take a look at the guide here https://pptr.dev/guides/evaluate-javascript#passing-arguments-to-the-evaluate-function The arguments have to be primitive values (numbers, strings) or JSHandles.

Try the following:

```
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch();
const page = await browser.newPage();

await page.setContent(`<div><div>`);

const foo = await page.evaluateHandle(() => {
    return (num) => num;
});

const details = await page.$$eval(
    "div",
    (divs, f) => {
        return f(1);
    },
    foo
);

console.log(details)

await browser.close()
```
