### ISSUE TITLE
Add possibility to configure download mirror

### ISSUE THREAD

**Issue by r3dDoX** [puppeteer/puppeteer#951]
Currently the URL "https://storage.googleapis.com/chromium-browser-snapshots/..." is hardcoded.
Since we would like to use this package behind a firewall which is blocking downloads, we need to be able to configure the download mirror.

An option like the ENV variable in the phantomjs wrapper package: "PHANTOMJS_CDNURL" would be useful for us.

**Comment by aslushnikov** [comment]
The CDN env variable is not flexible enough; that has been discussed here: https://github.com/GoogleChrome/puppeteer/pull/752#issuecomment-329341243

There's also a script that was used to download a proper chromium:

```bash
chromium_download_dir="/tmp/"
chromium_install_dir="/tmp/chrome-linux/"
CUSTOM_URL=http://my.url.com

if [ ! -d "${chromium_install_dir}" ]; then
  echo 'chromium not downloaded, downloading...'
  CHROMIUM_REVISION=`curl -s 'https://raw.githubusercontent.com/GoogleChrome/puppeteer/v0.11.0/package.json' | grep -oP '(?<="chromium_revision": ")[^"]*'`
  wget -q $CUSTOM_URL/Linux_x64/$CHROMIUM_REVISION/chrome-linux.zip
  echo 'Chrome Downloaded.'
  unzip -q chrome-linux.zip -d $chromium_download_dir
  echo 'Chrome unzipped.'
else
    echo "chromium already downloaded in ${chromium_install_dir}, skipping download"
fi

export CHROMIUM_BIN=/tmp/chrome-linux/chrome
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
```

Would this work for you?

**Comment by r3dDoX** [comment]
Thanks for your answer and sorry that I didn't see the existing discussion about this topic.

We could probably implement something like this script that would work. But if possible I would not want to maintain such a script on our own. We cannot guarantee that this will work in the future. It would be nicer if we could rely on download location calculation of puppeteer.

I don't quite see why the env var would need that much flexibility. Overwriting the prefix of the url should be sufficient for the case of firewalls that have to be proxied. So basically this part: "https://storage.googleapis.com/chromium-browser-snapshots/" being overwritten would allow us to specify some proxy to go through while not preventing anything else. Wanting to download chrome from a completely other location should not be handled in this package IMO.

We could name it PUPPETEER_DOWNLOAD_CHROMIUM_URL_PREFIX to make it clear that this will only change the prefix. What do you think?

**Comment by r3dDoX** [comment]
I made a small PR to show what I mean. #958

**Comment by aslushnikov** [comment]
> We could probably implement something like this script that would work. But if possible I would not want to maintain such a script on our own. We cannot guarantee that this will work in the future. It would be nicer if we could rely on download location calculation of puppeteer.

Imagine some time in the future we migrate to a different url: `https://cdn.pptr.io/r543043/mac.zip` There's no good way for us to redefine the suggested `PUPPETEER_DOWNLOAD_CHROMIUM_URL_PREFIX` variable, so the change will break clients and will still require a maintenance effort on their side.

**Comment by r3dDoX** [comment]
Surely, having a solution by routing through a proxy will always break when you change the host. But at least we would be safe against any changes to the versioning structure and operating system dependent naming.
Reducing the effort of maintenance to only when you switch to a complete different host would be a nice solution for us.

**Comment by r3dDoX** [comment]
So what do you think, any chance of having this functionality built into the package?

**Comment by aslushnikov** [comment]
@r3dDoX would the `PUPPETEER_DOWNLOAD_HOST` instead work for you? The `_PREFIX` is pretty vague.

**Comment by r3dDoX** [comment]
@aslushnikov sure that sounds good 👍

**Comment by r3dDoX** [comment]
I updated my PR accordingly

**Comment by melikhov-dev** [comment]
Can you add `process.env.npm_config_puppeteer_download_host` for supporting .npmrc configuration? like 
```
const DOWNLOAD_HOST = process.env.PUPPETEER_DOWNLOAD_HOST 
|| process.env.npm_config_puppeteer_download_host 
|| 'https://storage.googleapis.com';
```

**Comment by r3dDoX** [comment]
Sure 👍 Didn't know that.
PR is updated

**Comment by axetroy** [comment]
Anyone can provide Chinese download mirror?

I will be thanksful

**Comment by kunalshah** [comment]
Help needed for Chinese mirror. We can't get this to work in China at the moment!

**Comment by gucong3000** [comment]
> Any one can provider Chinese download mirror?

I'd like to do this.

**Comment by nooop3** [comment]
@axetroy @kunalshah try this:
export PUPPETEER_DOWNLOAD_HOST=https://npm.taobao.org/mirrors/

**Comment by gucong3000** [comment]
I developed tools to manage puppeteer and other mirrored addresses for npm modules:
https://github.com/gucong3000/mirror-config-china
