### ISSUE TITLE
[Bug] [Typescript]: page.screenshot with dubious return type

### ISSUE THREAD

**Issue by rhuanbarreto** [puppeteer/puppeteer#9512]
### Bug expectation

I expected `page.screenshot({ encoding: "binary" })` to return me a `Buffer` type but instead I got the union type `string | Buffer`.

So now I need to coerce the type doing `page.screenshot({ encoding: "binary" }) as Buffer` in order to deal with it in the code.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const imageBuffer = await page.screenshot({ encoding: "binary" }) // Type is string | Buffer. Correct should be Buffer
  const imageString = await page.screenshot({ encoding: "base64" }) // Type is string | Buffer. Correct should be string
  console.log({imageBuffer, imageString});
})();
```

### Error string

no error

### Puppeteer version

19.5.2

### Node version

18.12.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by rhuanbarreto** [comment]
@OrKoN can you pause the github action?

**Comment by OrKoN** [comment]
@rhuanbarreto sorry for the messages, it only runs on edits and I see @Lightning00Blade edited it.

**Comment by Lightning00Blade** [comment]
Sorry about the noise. GitHub allows you to click checkboxes without entering edit mode, and I accidentally did just that.

**Comment by OrKoN** [comment]
We had someone propose this feature in a PR before https://github.com/puppeteer/puppeteer/pull/9385 It didn't look like a useful change to me back then but this issue highlights the problem well and I think we should re-consider.

**Comment by rhuanbarreto** [comment]
Thanks @OrKoN! I opened a new issue (#9541) for the waitForXPath method that is very similar to this.
