### ISSUE TITLE
[Bug]: Page.mouse.move only works when window is in view (non-headless)

### ISSUE THREAD

**Issue by lelly8484** [puppeteer/puppeteer#9513]
### Bug expectation

When I run something like this, it doesnt work until the window is in view. If it's minimized or if the window is on another desktop that is not in view, it won't run and only proceeds when in view. Doesn't have to be focused but window has to be in view of the human user. Why? Viewport is set as well so element is in view

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
`                    await page.mouse.move(bounding.x + (bounding.width/2), bounding.y + (bounding.height/2), {"steps": getRandomInt(50,200)})
`
```

### Error string

Just doesn't work until window in view

### Puppeteer version

19.5.2

### Node version

14.18.1

### Package manager

npm

### Package manager version

6.14.15

### Operating system

Windows

**Comment by jrandolf** [comment]
This is expected behavior. It's part of process throttling within Chromium. At the moment, there is no workaround for this.
