### ISSUE TITLE
[Bug]: Unhandled Promise rejection in CDPPage

### ISSUE THREAD

**Issue by muodov** [puppeteer/puppeteer#9514]
### Bug expectation

I'm investigating some strange crashes in the puppeteer-based crawler that loads lots of random web pages on scale. One of the causes I found is the unhandled rejection caused by async functions in CDP event listeners.

This was actually reported in https://github.com/puppeteer/puppeteer/issues/2811, but I'm not sure the [proposed workaround](https://github.com/puppeteer/puppeteer/issues/2811#issuecomment-403669356) works. You see, the [handlers in Page.ts](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/Page.ts#L731) are async functions, but they are [passed](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/Page.ts#L226) to `mitt`, which [does not seem to care](https://github.com/developit/mitt/blob/main/src/index.ts#L105) about promise results.
As a result, when these handlers throw, this crashes the whole node process (by default [since v15](https://nodejs.org/api/cli.html#--unhandled-rejectionsmode)). And (correct me if I'm wrong) there's no way to attach a handler to this outside of the puppeteer code, apart from a catch-all `unhandledRejection`.

The original issue argues that it's up to the developer to await for each and every command, but in our case we want to have timeouts for each page, when we forcibly close it. After that we don't care about any unfinished processing, but obviously we don't want the crawler to crash.

Right now it seems like a workaround is to set `--unhandled-rejections=warn`, but I wonder if it'd be better to handle this inside puppeteer code. I mean, so far it doesn't seem like it was the intention to crash in this case...or was it?

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// sorry, I don't have a good repro for this race condition
```

### Error string

Error: INTERNAL ERROR: missing context with id = ...

### Puppeteer version

19.5.2

### Node version

v18.12.1

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Linux

**Comment by muodov** [comment]
@aslushnikov @JoelEinbinder just wondering if something has changed since https://github.com/puppeteer/puppeteer/issues/2811?

**Comment by jrandolf** [comment]
The developers you mentioned are no longer maintainers of Puppeteer. In any case, this seems like a feature. Could you file a new issue for a feature and close this?

**Comment by muodov** [comment]
@jrandolf I'm ok with re-submitting, but could you elaborate why you think it's a feature?..

The problem here is that these exceptions can crash the whole node process, and unless it's the expected behaviour, I'd say it is a bug

**Comment by OrKoN** [comment]
@muodov I think we should handle that inside the puppeteer code if your app has proper try/catches and we throw on internal events processing but we would need a repro to figure out what is causing the error: sometimes browser sends event Puppeteer does not expect and, in this case, it's correct to throw an unhandled error because internal Puppeteer state might be broken leading to unexpected results later on. In this case, the correct way is to restart your worker.

**Comment by muodov** [comment]
@OrKoN that makes sense. Let me see if I can come up with a repro script, and if that doesn't work I'll close this

**Comment by OrKoN** [comment]
@muodov were you able to reproduce?

**Comment by muodov** [comment]
@OrKoN I don't have a stable script reproducing it, but we see it pretty consistently when running large crawls with https://github.com/duckduckgo/tracker-radar-collector/tree/selenium-grid. `--unhandled-rejections=warn` seems to mitigate the crash in our case, so I'm pretty sure that the flow I described is correct.

We see this more often with the latest puppeteer version, but it's also reproducible with an older v10.2.0, where those message handlers were not `async` yet, but some calling functions up the stack are. On the new version, the usual culprit is [this line](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/common/Page.ts#L750) (the context seems to not exist). On the old version, I've seen it failing at [this assert](https://github.com/puppeteer/puppeteer/blob/v10.2.0/src/common/FrameManager.ts#L288). Not sure if it's helpful 🤷🏻‍♂️

I didn't give up yet, so if I see some pattern I'll try to extract a small repro script

**Comment by OrKoN** [comment]
@muodov thanks for the details. In this case, it looks like console messages not having a context for some reason might be expected. I will open up a PR for discussion.

**Comment by muodov** [comment]
@OrKoN After running several tests, I don't see this error anymore, so assuming that your fix did the trick 👍🏼 Thank you!
I'm closing this for now, feel free to reopen if the issue still reproduces.
