### ISSUE TITLE
[Bug]:  Error: Failed to launch the browser process! error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sravanth-space** [puppeteer/puppeteer#9515]
### Bug expectation

I have deployed my node api to Azure. It is working locally and on other cloud platforms but for Azure, it's failing.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
async (req, res) => {
    // Create a browser instance
    const browser = await puppeteer.launch({
        args: ["--no-sandbox", "--disabled-setupid-sandbox"],
    });

    // Create a new page
    const page = await browser.newPage();

    //Get HTML content from HTML file
    const html = pdfTemplate(req.body)
.....
}
```

### Error string

Error: Failed to launch the browser process!

### Puppeteer configuration

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

19.5.2

### Node version

16.18.0

### Package manager

npm

### Package manager version

6.14.15

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Closing as this looks like a set-up issue rather then a Puppeteer one. Those look like Linux packages. I recommend you checkout our own [Docker image](https://pptr.dev/guides/docker) or take a look inside the the [Docker file](https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile) itself to see what we install before running puppeteer.
Something similar may be found in [throubleshooting](https://pptr.dev/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux) for the WSL as well.
