### ISSUE TITLE
Add `browser.closed` and `page.closed` events

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#952]
- Fire `browser.closed` event when the underlying browser process gets closed / crashes
- Fire `page.closed` event when the page gets closed / crashes

This will help to build reliable scripts that restart browser or reopen pages when they crash.

**Comment by sukrosono** [comment]
currently no PR to this right? Is it ok if i just take `page.closed` ?

**Comment by sukrosono** [comment]
Hi @aslushnikov , please correct me if i am wrong. With
> Fire browser.closed event when the underlying browser process gets closed / crashes

My attempt was to close the browser when the page got crashed. But the result was 370 specs, 309 failures, This is what my [attempt](https://github.com/brutalcrozt/puppeteer/commits/tmp) looks like. Here the travis build [failure](https://travis-ci.org/brutalcrozt/puppeteer/builds/287885828), and the [raw log](https://api.travis-ci.org/jobs/287885830/log.txt?deansi=true) (too many error so the summary only available on raw log). Gladly awaiting your response :smile: .

**update**
Sorry to brother you i just found [Browser.close](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-close) via #1027. I will try use that, even i don't know the impact yet. When you have free time, please give me some direction, a couple of word help me alot.

**Comment by aslushnikov** [comment]
For this to be closed, the 'page.disconnected' is also necessary.

**Comment by gebrits** [comment]
> For this to be closed, the 'page.disconnected' is also necessary.

@aslushnikov: is this currently in the works? If not I might be able to take a crack at it.

**Comment by aslushnikov** [comment]
We now have `browser.disconnected` and `page.close` events.

**Comment by natsu90** [comment]
is there anyway i can know either the browser is crashed or closed from the `disconnected`  event? i only want to relaunch the browser when it crashes, not when i called `browser.close()`
