### ISSUE TITLE
[Bug]: Memory snapshot failed

### ISSUE THREAD

**Issue by null-ref-0000** [puppeteer/puppeteer#9522]
### Bug expectation

Running puppeteer on Google Cloud run in a container. 

Was expecting to be able to scrape a site using puppeteer but I am receiving the following error:

[32mINFO[39m [33m PuppeteerCrawler:[39m Starting the crawl
[31mERROR[39m Memory snapshot failed.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const crawler = new PuppeteerCrawler({
        // Here you can set options that are passed to the launchPuppeteer() function.
        launchContext: {
            launchOptions: {
                headless: true,
                args: ['--no-sandbox', '--disable-gpu', 'disable-dev-shm-usage'],
                executablePath: 'google-chrome'
            },
        },
```

### Error string

[31mERROR[39m Memory snapshot failed.

### Puppeteer version

19.5.2

### Node version

v16.17.0

### Package manager

npm

### Package manager version

6.14.8

### Operating system

Linux

**Comment by jrandolf** [comment]
We recommend asking this on Stackoverflow. Thanks!

**Comment by keanesf** [comment]
Thanks. I have followed your recommendation and asked on stack.

https://stackoverflow.com/questions/75154388/puppeteer-memory-snapshot-failed
