### ISSUE TITLE
[Bug]: Page.goto() throws error for HTTP status code 4xx, 5xx etc.

### ISSUE THREAD

**Issue by VoidMonk** [puppeteer/puppeteer#9523]
### Bug expectation

Official [documentation](https://pptr.dev/api/puppeteer.page.goto#remarks) for `Page.goto()` says:

```
page.goto will throw an error if: there's an SSL error (e.g. in case of self-signed certificates). - target URL is invalid. - the timeout is exceeded during navigation. - the remote server does not respond or is unreachable. - the main resource failed to load.

page.goto will not throw an error when any valid HTTP status code is returned by the remote server, including 404 "Not Found" and 500 "Internal Server Error". The status code for such responses can be retrieved by calling response.status(). 
```

But, in headful mode, `Page.goto()` throws an error if the response status code if 404, 503 etc. and the body is empty. If the mode is headless or body is not empty (e.g. some HTML or text) then it doesn't throw an error.

Expected behavior is that `Page.goto()` should not throw an error for 4xx, 5xx status codes, irrespective of the launch mode (headless or headful) and the response body content.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

// scenario 1: test page returns HTTP 404 without a body
// result: puppeteer throws an error
(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto('https://httpbin.org/status/404');

  await browser.close();
})();

// scenario 2: test page returns HTTP 404 with a body
// result: puppeteer doesn't throw an error
(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto('https://httpbin.org/notfound');

  await browser.close();
})();
```

### Error string

net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://httpbin.org/status/404

### Puppeteer configuration

```
{
  headless: false
}
```

### Puppeteer version

19.5.2

### Node version

18.13.0

### Package manager

npm

### Package manager version

9.2.0

### Operating system

Windows

**Comment by Rafael-Martins** [comment]
I have been able to replicate the issue, would it be possible for me to attempt to resolve it?

**Comment by Rafael-Martins** [comment]
Hey we merged a pr that fix this behavior! @VoidMonk

**Comment by Rafael-Martins** [comment]
I think that we can close this!
