### ISSUE TITLE
[Bug]:  Cannot find module when running using ESM

### ISSUE THREAD

**Issue by Codypinto23** [puppeteer/puppeteer#9530]
### Bug expectation

I am trying to run a very basic script to load a test page using Puppeteer.
However, my script is crashing on load and i'm getting the error: MODULE_NOT_FOUND

This error only occurs when I kick off my script using "-r esm" in my script. 
If I run node using the "--experimental-modules" flag instead, then it runs fine.
It runs fine if I kick it off using babel-node as well.

Why would "-r esm" and the "--experimental-modules" flag be giving different results?

This is my package.json:
```
{
  "name": "PuppeteerTest",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "clean": "rm -rf build && mkdir build",
    "build": "babel -d ./build ./src -s --copy-files",
    "startesm": "yarn clean && yarn run build && NODE_ENV=production node -r esm ./build/server.js",
    "starttest": "babel-node src/server.js",
    "startexperimental": "yarn clean && yarn run build && NODE_ENV=production node --experimental-modules  ./build/server.js"
  },
  "dependencies": {
    "esm": "^3.2.25",
    "express": "^4.18.1",
    "handlebars": "^4.7.7",
    "puppeteer": "^19.5.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.15.4",
    "@babel/core": "^7.15.5",
    "@babel/node": "^7.15.4",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/preset-env": "^7.15.4"
  },
  "babel": {
    "presets": [
      "@babel/preset-env"
    ]
  }
}
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
console.log("puppeteer",puppeteer)

async function functionTest(){
const browser = await puppeteer.launch();

// Create a new page
const page = await browser.newPage();

// Website URL to export as pdf
const website_url = 'https://www.google.com';
}
functionTest()
```

### Error string

Error: Cannot find module 'puppeteer-core/internal/common/DeviceDescriptors.js'Error: Cannot find module 'puppeteer-core/internal/common/DeviceDescriptors.js'

### Puppeteer version

19.5.2

### Node version

16.18.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
@Codypinto23 could you share the complete test repo including the package-lock/yarn-lock files? In general, it looks like babel is not correctly building things. Using your code and running it directly in nodejs with modules works without issues.

**Comment by Codypinto23** [comment]
Hi @OrKoN ,

Here's the complete [test repo](https://github.com/Codypinto23/Puppeteer-Esm)

**Comment by OrKoN** [comment]
Thanks, I have looked into it and I think the problem is that babel compiles the code to commonjs and then you try to run it with esm. I am not sure why node has different behaviour here but I guess that would be an issue for node?

<img width="650" alt="Screenshot 2023-01-25 at 09 56 14" src="https://user-images.githubusercontent.com/399150/214520378-472a93de-69c3-4034-86b6-bdb6dfc1e699.png">
