### ISSUE TITLE
[Bug]: Error: Could not find Chromium (rev. 1069273)

### ISSUE THREAD

**Issue by AlcantaraMC** [puppeteer/puppeteer#9533]
### Bug expectation

I expected to successfully run puppeteer, as it always did in prior versions.

I instead got an error:
<code>
Error: Could not find Chromium (rev. 1069273). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/sysadm/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/var/www/html/oas-restapi-fork1/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:119:27)
    at ChromeLauncher.executablePath (/var/www/html/oas-restapi-fork1/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:205:25)
    at ChromeLauncher.launch (/var/www/html/oas-restapi-fork1/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:93:37)
</code>

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript

"use strict";

const puppeteer = require ('puppeteer');

async function main () {

    try {

        // instantiate puppeteer
        console.log (`Launching puppeteer`);
        const browser = await puppeteer.launch ();

        // create new page:
        console.log (`Creating page`);
        const page = await browser.newPage ();

    } catch (err) {

        console.log (err);

    }

}

main ();
```

### Error string

Error: Could not find Chromium (rev. 1069273)

### Puppeteer configuration

```TypeScript

```

### Puppeteer version

19.6.0

### Node version

v16.19.0

### Package manager

npm

### Package manager version

9.3.0

### Operating system

Linux

**Comment by OrKoN** [comment]
How did you upgrade Puppeteer? binary installation happens in the `postinstall` npm script and we expect npm to call it but it looks like npm didn't do that in your case.

**Comment by OrKoN** [comment]
As a workaround it should be possible to run `node node_modules/puppeteer/install.js` to download the binary. It's the same file that npm is supposed to invoke.

**Comment by WashingtonInoveApps** [comment]
Hello, is there any solution for this problem?

**Comment by OrKoN** [comment]
I could not reproduce the issue but I think I found a related issue that might explain the missing binaries.

**Comment by chirale** [comment]
Very random but persistent issue. It seems not reproducible if you run a single script with no concurrency. Try with concurrency and long running scripts like in a real world scenario. When it breaks (and it breaks during script execution), it is not recoverable until a new npm ci. And then, it can breaks after 26 minutes or after 3 minutes, but when it breaks it will not recover even if you re-run the same script.

**Comment by jacobg** [comment]
I was having this error for revision 1069273, then bumped to puppeteer 19.6.2, deployed to Google Cloud Function, and the error went away. Then a little later I did another deployment for an unrelated reason, and the error came back again on a new revision 1083080.

So it doesn't seem that 19.6.2 fixes the issue.

**Comment by bartek2341** [comment]
Same error here. I can't do `node_modules/puppeteer/install.js` as terminal says it's already installed. Everything works on v18. Any updates on this? I can't use the latest version of puppeteer.

**Comment by varun-nambiar** [comment]
Got this error after upgrade, tried cleaning cache and this got resolved for me.
```console
foo@bar:~$ npm cache clean --force
```

**Comment by gerardparareda** [comment]
It's not working for me either. 
I can see chrome is installed here `/home/erp/.cache/puppeteer/chrome/linux-1095492`.

```
throw new Error(`Could not find Chromium (rev. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chromium (rev. 1056772). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/erp/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/home/erp/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:120:27)
    at ChromeLauncher.executablePath (/home/erp/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:166:25)
    at ChromeLauncher.launch (/home/erp/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:70:37)
    at async /home/erp/src/erp/addons/gisce/Misc/report_puppeteer/js/get_pdf.js:29:21

Node.js v18.14.0
```
I just checked the file `/home/erp/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js` line 120 and after a console.log of `this.puppeteer.configuration.executablePath`, it appears as `undefined`. So either there's no default configuration file or Puppeteer's not finding the default configuration.

**Comment by mon-jai** [comment]
I got this error complaining couldn't found Chromium 1095492, but in fact the installed version is 1083080.

```
Error: Could not find Chromium (rev. 1095492). This can occur if either
     1. you did not perform an installation before running the script (e.g. `npm install`) or
     2. your cache path is incorrectly configured (which is: C:\Users\MyUserName\.cache\puppeteer).
    For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
```

```
PS C:\Users\MyUserName\.cache\puppeteer\chrome> ls


    Directory: C:\Users\MyUserName\.cache\puppeteer\chrome


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         3/11/2023  11:12 AM                win64-1083080
```

**Comment by karim-dev-coder** [comment]
`
HttpException: Could not find Chromium (rev. 1069273). This can occur if either
`

Command solved it 'npm install puppeteer'

**Comment by stuisme** [comment]
I had this issue with `^19.8.0` on cloud functions. The issue was the build layer used when deploying cloud functions contains the chromium, however cloud functions uses a different base container image for the runtime. The trick was the set the cache directory inside the application source directory. Using `puppeteer.config.js` file in the root and the sample from the docs: 

```
const { join } = require("path");

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, ".cache", "puppeteer"),
};
```

GCP Functions copies the source code directory to the runtime container allowing it to find the cache. Cheers.

**Comment by martincomputershare** [comment]
Hello,

- I just created a new empty directory and ran `npm install puppeteer` inside it. This installed version `^19.8.5` according to the `package.json`.

- I copied the example from the getting started page to take a screenshot:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

- I ran `node src/example.js` => `Could not find Chromium (rev. 1108766).`

- I added a `puppeteer.config.cjs` file to my project:

```js
const { join } = require("path")

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
	// Changes the cache location for Puppeteer.
	cacheDirectory: join(__dirname, ".cache", "puppeteer"),
}
```

- I ran `node node_modules/puppeteer/install.js` :

```
Chromium (1108766) downloaded to C:\Users\...MyProject\.cache\puppeteer\chrome\win32-1108766
```

- But `ls "C:\Users\...MyProject\.cache\puppeteer\chrome"` says there is nothing there.

**Comment by OrKoN** [comment]
@martincomputershare can you file a fresh issue? there have been refactoring as we transition to https://pptr.dev/browsers-api/ and that does not look like the original issue. 

Are you using WSL on which Windows version? I just tested on Windows and unable to reproduce this.

**Comment by martincomputershare** [comment]
Hi. Please never mind me. It was a VPN issue.

**Comment by MarcusOtter** [comment]
Created an issue above for the VPN thing - I just ran into it as well.

**Comment by mikejackowski** [comment]
`node node_modules/puppeteer/install.js` helped me with this issue (i run pptr on EC2). I think it's worth adding to docs somewhere

**Comment by jsandeepm** [comment]
npm clean-install

this installed the *"cache\puppeteer\chrome\win64-1095492"* and solved my problem.

**Comment by chirale** [comment]
I've solved since 19 downloading separately Chromium then using [executablePath](https://pptr.dev/api/puppeteer.launchoptions/#properties). This method is useful i.e. on docker where a separate layer for browser download and unzip can be cached without forcing download at every npm ci.

**Comment by gerardparareda** [comment]
So far nothing in this issue worked for me. I "found" that my chromium installation was like so:
`.cache/puppeteer/chrome/linux-113.0.5672.63/chrome-linux64/`

And my error said the following: 
`Could not find Chromium (rev. 1069273). This can occur if either`

So I renamed my chromium folder and it worked:
```
mv .cache/puppeteer/chrome/linux-113.0.5672.63/ .cache/puppeteer/chrome/linux-1069273/
mv .cache/puppeteer/chrome/linux-1069273/chrome-linux64/ .cache/puppeteer/chrome/linux-1069273/chrome-linux
```

I am not using a project. I am using NVM and installing puppeteer globally, so I really have no clue where to put the said `.puppeteerrc.cjs`. Maybe in `/home/erp/.nvm/versions/node/v16.20.0/lib/node_modules/npm/`? That said I tried using the environtment variables and they didn't work either:

`PUPPETEER_CACHE_DIR="/home/erp/.cache" ...`
`PUPPETEER_CACHE_DIR="/home/erp/.cache/puppeteer" ...`

**Comment by OrKoN** [comment]
Revisions like `1069273` were used before [a breaking change in v20](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v20.0.0). So it looks like you have the installation done by the newer version of Puppeteer (i.e., `113.0.5672.63` versioning) and use an old version to actually run on the cache folder.

**Comment by gerardparareda** [comment]
Definitely looks like it. Could it be an issue with NVM? It is a fresh install after all. The revision `1069273` is expected by puppeteer but `npm install -g puppeteer` installs the `113.0.5672.63` revision.

**Comment by aditodkar** [comment]
Solved the issue after using these commands:

1) npm cache clean --force

2) npm install puppeteer

**Comment by RoelLeal** [comment]
> npm clean-install

I copy this from a guy here and works for me using puppeteer

npm -v 
9.7.1

node -v
v20.2.0

**Comment by nandopinheiro** [comment]
I am beyond frustrated. I spent several hours trying to figure out why on Google Cloud Functions, puppeteer can't find Chrome no matter what. I did everything above. I am beyond frustrated, I don't know what I am doing wrong, using Google Cloud Function gen 2. Nothing seems to work, it simply can't find the headless browser. I've tried adding ExecutePath, it just can't find the function /.cache/puppeteer no matter what. 


Package.json
`{
    "name": "sample-http",
    "version": "1.0.0",
    "description": "",
    "main": "function.js",
    "scripts": {
        "gcp-build": "node node_modules/puppeteer/install.js"
    },
    "devDependencies": {
        "@google-cloud/functions-framework": "^1.8.0"
    },
    "dependencies": {
        "puppeteer": "^20.7.3"
    },
    "engines": {
        "node": "18.x"
    }
}
`
Fuction code
`const puppeteer = require('puppeteer');

let browserPromise = puppeteer.launch({
    
    headless: "new",
  args: ['--no-sandbox','--disable-setuid-sandbox']
});

exports.scrapeProductPrice = async (req, res) => {
  try {
    const url = req.body.url;
    console.log('URL:', url);
    console.log('Testing console.log statement');

    const browser = await browserPromise;
    console.log('Browser launched');

    const context = await browser.createIncognitoBrowserContext();

    const page = await browser.newPage();
    console.log('New page created');

    await page.goto(url,{ timeout: 60000 });
    console.log('Page loaded');

    const priceElement = await page.$x("/html/body/div[@id='__next']/div[@class='en-US']/main[@class='p_productPage__0n7Zp']/div[@class='p_productPage__top__WvHGB innerContainer']/div[@class]");

    if (priceElement.length > 0) {
      console.log('Price element found');

      const rawPrice = await page.evaluate((el) => el.innerText.trim(), priceElement[0]);
      const price = extractNumericValue(rawPrice);
      console.log('Scraped price:', price);

      await browser.close();
      console.log('Browser closed');
      res.status(200).send({ price: price });
    } else {
      console.error('Price element not found');
      throw new Error('Price element not found');
    }
  } catch (error) {
    console.error('Error occurred during scraping:', error);
    res.status(500).send({ error: 'An error occurred during scraping' });
  }
};

function extractNumericValue(rawPrice) {
  // ...
}`

**Comment by nandopinheiro** [comment]
> > npm clean-install
> 
> I copy this from a guy here and works for me using puppeteer
> 
> npm -v 9.7.1
> 
> node -v v20.2.0

@RoelLeal man, how did you do it? I spent 3 days. This fucker no matter what, can't find the headless chrome. It deploys normally but when I test the function I always get the same error. 

I use Google Cloud Functions. There is nothing on Google Cloud for Puppeteer v.20.x everyone says that works fine, but always older versions.

**Comment by RoelLeal** [comment]
> > > npm clean-install
> > 
> > I copy this from a guy here and works for me using puppeteer
> > 
> > npm -v 9.7.1
> > 
> > node -v v20.2.0
> 
> @RoelLeal man, how did you do it? I spent 3 days. This fucker no matter what, can't find the headless chrome. It deploys normally but when I test the function I always get the same error. 
> 
> I use Google Cloud Functions. There is nothing on Google Cloud for Puppeteer v.20.x everyone says that works fine, but always older versions. 

I had that problem and it fixes it by changing the version and updating the cache but I don't know how to do it in Google cloud functions

**Comment by sfitzmaurice** [comment]
For those using cloud run, I fixed this issue in my cloud run container by uninstalling puppeteer, then reinstalling puppeteer, **_after_** the new config file .puppeteer.cjs was copied to the container. For example:

Dockerfile
```
FROM node:16.14

WORKDIR /usr/src/app

COPY package*.json ./

# Install production dependencies.
RUN npm ci --omit=dev

# Copy local code to the container image.
COPY . ./

RUN npm uninstall puppeteer

RUN npm i puppeteer
```

**Comment by sindelio** [comment]
Cleaning the cache worked for me, as mentioned by @aditodkar 

```
yarn cache clean
yarn install
```

**Comment by nanounanue** [comment]
None of the above suggestions worked for me:

```
npm -v
9.7.2
node -v
v20.4.0
```

**Comment by sassanh** [comment]
I actually noticed the main issue does not say anything about cloud functions, but since resolving the issue on a machine you have terminal access to is very easy, I think the actual problem here is to fix the issue for cloud function runners like AWS lambda or Firebase functions.

**Comment by NoiseEee** [comment]
I'm not sure how much "cloud" has anything to do with this; I have given up wasting hours of my time and reverted back to Puppeteer < `v.19` for my sanity

**Comment by sassanh** [comment]
The thing is if you can run a terminal on the machine having this issue, you can probably fix it by above solutions or at least that’s how it works for me. But if it is on the cloud, or for any other reason you can’t reliably run commands on the machine you are stuck.
I think this package should be able to take care of invalidating old cache and making sure to have a working chromium instance instead of relying on a human being to manually take care of these things.

**Comment by josecd** [comment]
**I solved it like this to be able to deploy in the cloud**

In my Dockerfile 

RUN apk add --no-cache udev ttf-freefont chromium git
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser

To start the browser

puppeteer.launch({
  executablePath: process.env.CHROMIUM_PATH,
  args: ['--no-sandbox'], // This was important. Can't remember why
});

**Comment by sassanh** [comment]
.Thanks for sharing but sometimes you don’t even have a dockerfile, for example in AWS lambda functions and in firebase functions. They just install your package.json,

I don’t understand why this library suddenly doesn’t work out of the box and needs extra work after being installed.

**Comment by smithkyle** [comment]
FWIW I have puppeteer running in a Google Cloud Function using Puppeteer 21.0.2 and Node v20 following [these directions](https://medium.com/@jackklpan/run-puppeteer-in-google-cloud-functions-v2-b18a353e609b). The three main bits are:

1. adding `gcp-build` to `scripts` in `package.json`
2. adding the `.puppeteerrc.cjs` file
3. make sure the function has at least 1gb of ram

**Comment by AmichayMiara** [comment]
BTW @smithkyle solution works also with 1st gen functions...

**Comment by VanDerCroix** [comment]
> **I solved it like this to be able to deploy in the cloud**
> 
> In my Dockerfile
> 
> RUN apk add --no-cache udev ttf-freefont chromium git ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true ENV CHROMIUM_PATH /usr/bin/chromium-browser
> 
> To start the browser
> 
> puppeteer.launch({ executablePath: process.env.CHROMIUM_PATH, args: ['--no-sandbox'], // This was important. Can't remember why });

This one worked for me, thanks!

**Comment by estatistics** [comment]
SOLVED
path was /home/USER/.cache/puppeteer/chrome/linux-117.0.5938.92/chrome-linux64/
path copied as /home/USER/.cache/puppeteer/chrome/linux-1108766/chrome-linux/

Please add in script to print the expected path that puppeeter is searching chromium.

note that running as sudo yarn PROGRAM is searching in root/.cache while yarn PROGRAM in /home/user...
but the latest was throwing errors

So, `sudo npm run build --loglevel=error` or `sudo yarn run build --loglevel=error` and then `yarn start` or `npm start`

**Comment by tomcatmwi** [comment]
In a Windows environment, a global installation of Puppeteer solved the problem:

`npm i puppeteer -g`

**Comment by issudn** [comment]
> As a workaround it should be possible to run `node node_modules/puppeteer/install.js` to download the binary. It's the same file that npm is supposed to invoke.

Yep, that worked for me, thank you!

**Comment by dineshkumar14062001** [comment]
Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either
2023-12-21 12:41:43.177 IST
 1. you did not perform an installation before running the script (e.g. npx puppeteer browsers install chrome) or
2023-12-21 12:41:43.177 IST
 2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer).
2023-12-21 12:41:43.177 IST
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
2023-12-21 12:41:43.177 IST
    at ChromeLauncher.resolveExecutablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:288:27)
2023-12-21 12:41:43.177 IST
    at ChromeLauncher.executablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:219:25)
2023-12-21 12:41:43.177 IST
    at ChromeLauncher.computeLaunchArguments (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:113:37)
2023-12-21 12:41:43.177 IST
    at async ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
2023-12-21 12:41:43.177 IST
    at async /usr/src/app/routes/services/common-service.js:340:31
    
    
    
    same issue for me what can I do, I have use goggle cloud function.
    any one please tell me how to solve this issue, I have more than 2 weeks

**Comment by jena-cameron** [comment]
I'm still experiencing this issue despite trying all the workarounds. My issue specifically is that we can't get this to work in an AWS lambda.

**Comment by nariman-z-k** [comment]
You can manually download Chromium (e.g. via [this page](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html) or [this page](https://download-chromium.appspot.com/)) and then set the executablePath when launching it:

const browser = await puppeteer.launch({
    executablePath: 'path/to/your/chrome.exe'
});

**Comment by nariman-z-k** [comment]
first install puppeteer with escape download:
npm install --ignore-scripts puppeteer

then You can manually download Chromium (e.g. via [this page](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html) or [this page](https://download-chromium.appspot.com/)) and then set the executablePath when launching it:

const browser = await puppeteer.launch({
    executablePath: 'path/to/your/chrome.exe'
});

**Comment by nariman-z-k** [comment]
> Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either 2023-12-21 12:41:43.177 IST
> 
>     1. you did not perform an installation before running the script (e.g. npx puppeteer browsers install chrome) or
>        2023-12-21 12:41:43.177 IST
> 
>     2. your cache path is incorrectly configured (which is: /home/.cache/puppeteer).
>        2023-12-21 12:41:43.177 IST
>        For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
>        2023-12-21 12:41:43.177 IST
>        at ChromeLauncher.resolveExecutablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:288:27)
>        2023-12-21 12:41:43.177 IST
>        at ChromeLauncher.executablePath (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:219:25)
>        2023-12-21 12:41:43.177 IST
>        at ChromeLauncher.computeLaunchArguments (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:113:37)
>        2023-12-21 12:41:43.177 IST
>        at async ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28)
>        2023-12-21 12:41:43.177 IST
>        at async /usr/src/app/routes/services/common-service.js:340:31
>        same issue for me what can I do, I have use goggle cloud function.
>        any one please tell me how to solve this issue, I have more than 2 weeks

you can install puppeteer :
npm install --ignore-scripts puppeteer

then You can manually download Chromium (e.g. via [this page](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html) or [this page](https://download-chromium.appspot.com/)) and then set the executablePath when launching it:

const browser = await puppeteer.launch({
    executablePath: 'path/to/your/chrome.exe'
});
