### ISSUE TITLE
[Bug]: Invalid path to pupetter-core internal path in commonJS module resolution via `main` field

### ISSUE THREAD

**Issue by Hotell** [puppeteer/puppeteer#9535]
### Bug expectation

Puppeteer should work in non ESM environment that is unable to process export maps.

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/1223799/213125110-97493fc5-71b2-4b6f-bef9-6f2c936e8296.png">

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

1. checkout https://github.com/Hotell/fluentui/tree/hotell/build/scripts/puppeter-tweaks-v18-19-bug
2. `yarn`
3. `yarn workspace @fluentui/scripts-puppeteer test`

### Error string

 Cannot find module 'puppeteer-core/internal/puppeteer-core.js' from '../../node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js'

### Puppeteer version

starting v18

### Node version

16.16.0

### Package manager

yarn

### Package manager version

1

### Operating system

macOS

**Comment by OrKoN** [comment]
> Puppeteer should work in non ESM environment that is unable to process export maps.

Do you have a solution in mind? We currently require export maps to be able to import some classes from core that we don't want to make public.

**Comment by Hotell** [comment]
So this is mainly caused by jest 26 (AFAIK `exports` work starting version 28 ).

This workaround works with Puppeteer 18 and 19:

```
// jest config
moduleNameMapper: {
    '^puppeteer-core/internal/(.*)': '<rootDir>/../../node_modules/puppeteer-core/lib/cjs/puppeteer/$1',
  },
```

> Do you have a solution in mind? 

Unless you expose those api I dunno ATM, but with current releases you ship basically invalid package which is not good.

**Comment by OrKoN** [comment]
I see. Since you mentioned jest, we actually have this issue documented https://pptr.dev/troubleshooting#cannot-find-module-puppeteer-coreinternal I don't think we gonna support older versions of Jest.

**Comment by Hotell** [comment]
>  don't think we gonna support older versions of Jest.

yeah and I don't think you should. that's the other tool issue for sure.  

but following problem is still valid `but with current releases you ship basically invalid package which is not good` . Maybe you should remove `main` fields completely in 18,19+ releases to be very explicit about API. 


anyways, thanks for quick responses ! should I close this one or you wanna keep it open for tracking purposes ?

**Comment by OrKoN** [comment]
Yeah we could remove main I think. Let's try that out.

**Comment by OrKoN** [comment]
Main seems to be used still (judging by test failures https://github.com/puppeteer/puppeteer/actions/runs/3949479180/jobs/6760739298) so I guess it is not completely replacable by export maps.
