### ISSUE TITLE
Puppeteer Screenshot Fullpage: top part of the page is getting repeated at the bottom

### ISSUE THREAD

**Issue by ys-asalud** [puppeteer/puppeteer#9536]
Im having trouble with the screenshot function of puppeteer. but for some reason the bottom of the page seem to repeat the top one. Does anyone have an idea how or why this happens?

![driftbugtest](https://user-images.githubusercontent.com/54834859/213137354-0b1345b5-df6b-4a4c-a399-23d7a3f4c12c.jpg)

**Comment by saludangelito** [comment]
I call the function like this: `await this.client.client.screenshot({ type: 'jpeg', encoding: 'binary', quality: 40, fullPage: true });`

![Screenshot-2023-01-18-17-35-10](https://user-images.githubusercontent.com/54834859/213137980-88d1353d-28d6-4502-b8ba-f8cdb96c0591.jpeg)

**Comment by OrKoN** [comment]
I believe it's the same as https://github.com/puppeteer/puppeteer/issues/1576 If not please, provide a repro according to the bug template.
