### ISSUE TITLE
ERR_CONNECTION_REFUSED (localhost:3000 only w/ignoreHTTPSErrors)

### ISSUE THREAD

**Issue by niftylettuce** [puppeteer/puppeteer#954]
It's really hard to debug puppeteer, at least connection errors.  Related to #822, I get a `ERR_CONNECTION_REFUSED` error.  Even with `DEBUG=*`, there's nothing in the puppeteer logs that shows why the request failed.  No stack trace, no weird error, no output from my server, nothing.  The only output in Chromium inspector console and puppeteer CLI debug output was `ERR_CONNECTION_REFUSED` as mentioned.

I also tried the link in Chrome Canary and Chromium on its own, worked OK.

Also, I noticed that I have to manually unset the following header, even though I had set `ignoreHTTPSErrors: true`; shouldn't this header get removed if this option is `true` by default?

```js
page.setExtraHTTPHeaders({ 'upgrade-insecure-requests': '0' });
```

I think that this is a `localhost` or a `port` issue.  My server is running at `http://localhost:3000` and I have `ignoreHTTPSErrors: true` option set as mentioned.

**I changed the URL I'm navigating to with our production URL and it worked fine.**

**Comment by niftylettuce** [comment]
Per https://github.com/GoogleChrome/puppeteer/issues/84#issuecomment-319467105 I read the Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=751204 and this exactly describes my usage.  I navigate to a page, then navigate once more (see the Chromium issue's step 5). Not sure if this is related or not.

**Comment by niftylettuce** [comment]
Another update - I've also tried to use self-signed certs and https protocol.  This does not work either.

**Comment by niftylettuce** [comment]
Figured it out - port was wrong on the link that was being crawled, and it wasn't obvious at first since port wasn't showing in logs 🤦‍♂️

**Comment by amazzoccone** [comment]
Hey @niftylettuce how you fixed it? I couldn't make it work successfully. I look over all the issues, but none of the solutions resolve the problem.

**Comment by PavelShalahai** [comment]
> Hey @niftylettuce how you fixed it? I couldn't make it work successfully. I look over all the issues, but none of the solutions resolve the problem.

In my case application running inside a container. When it launched with ports `-p 8080:80` for example, I got this error. Running a container with `-p 80:80` fixed this issue.

**Comment by Iamcerba** [comment]
In my case, I forgot that the application is running in VS Code dev container and localhost is not visible from the container. I have to replace "localhost" with "host.docker.internal".
