### ISSUE TITLE
Memory leakage after OMD upgrade

### ISSUE THREAD

**Issue by Vani2468** [puppeteer/puppeteer#9540]
### Feature description

After OMD upgrade to 5.00, we have observed that more memory is using by chrome process (almost 400 process running at the back end and leaving behind with out clearing old processes) resulting more memory usage (~6GB). This causing the communication issue with service now due to low memory and not creating any tickets in servicenow.

Below are few chrome processes running at the backend

site1 3145 0.0 0.1 342650721 38372 ? Ssl 08:14 0:01 /omd/versions/5.00-labs-edition/lib/node_modules/puppeteer-core/.local-chromium/linux-123876/chrome-linux/chrome --allow-pre-commit-input --disable-background-networking --enable-features=NetworkServiceInProcess2 --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable features=Translate,BackForwardCache,AcceptCHFrame,AvoidUnnecessaryBeforeUnloadCheckSync --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --enable-blink-features=IdleDetection --export-tagged-pdf --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-setuid-sandbox --window-size=900,200 --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-ghkjl site1 3165 0.0 0.1 342650721 38580 ? Ssl 08:14 0:01 /omd/versions/5.00-labs-edition/lib/node_modules/puppeteer-core/.local-chromium/linux-123876/chrome-linux/chrome --allow-pre-commit-input --disable-background-networking --enable-features=NetworkServiceInProcess2 --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Translate,BackForwardCache,AcceptCHFrame,AvoidUnnecessaryBeforeUnloadCheckSync --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --enable-blink-features=IdleDetection --export-tagged-pdf --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-setuid-sandbox --window-size=900,200 --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-LBJjjjdG site1 3166 0.0 0.1 342650721 38280 ? Ssl 08:14 0:01 /omd/versions/5.00-labs-edition/lib/node_modules/puppeteer-core/.local-chromium/linux-123876/chrome-linux/chrome --allow-pre-commit-input --disable-background-networking --enable-features=NetworkServiceInProcess2 --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Translate,BackForwardCache,AcceptCHFrame,AvoidUnnecessaryBeforeUnloadCheckSync --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --enable-blink-features=IdleDetection --export-tagged-pdf --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --disable-setuid-sandbox --window-size=900,200 --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-InhlukK.

Kindly let us know if there is any option to clear the processes to reduce the memory usgae.

It should clear the chrome processes automatically but it is not happening.

**Comment by OrKoN** [comment]
This is not a feature request. If you see a memory leak in Chrome processes and not the Puppeteer/Node process, please report it to crbug.com
