### ISSUE TITLE
[Bug] [Typescript]: page.waitForXPath with dubious return type 

### ISSUE THREAD

**Issue by rhuanbarreto** [puppeteer/puppeteer#9541]
### Bug expectation

Very similar to #9512.

I expected `page.waitForXPath('//button')` to return me a `Promise<ElementHandle<Node>>` type but instead I got the union type `Promise<ElementHandle<Node> | null>`.

So now I need to coerce the type doing `(await page.waitForXPath('//button')) as ElementHandle<Node>` in order to deal with it in the code.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const shouldBeNull = await page.waitForXPath("//button", { hidden: true }); // Type is ElementHandle<Node> | null. Correct should be null
  const shouldBeElementHandle = await page.waitForXPath("//body"); // Type is ElementHandle<Node> | null. Correct should be ElementHandle<Node>
  console.log({ shouldBeNull, shouldBeElementHandle });
  browser.close();
  process.exit();
})();
```

### Error string

no error

### Puppeteer version

19.5.2

### Node version

18.12.1

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by Rafael-Martins** [comment]
Hey, @rhuanbarreto I'm new here, just trying to help!

Based on my research, the union type `Promise<ElementHandle<Node> | null>` appears to be suitable for the `waitForXPath` implementation, as it accounts for the potential null response due to varying reasons.

Perhaps you could use the `!` syntax instead of `await page.waitForXPath('//button')) as ElementHandle<Node>` in your code. like:
```js
 import puppeteer, { ElementHandle } from "puppeteer";

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const shouldBeNull = await page.waitForXPath("//button", { hidden: true }); // Type is ElementHandle<Node> | null. Correct should be null
  const shouldBeElementHandle = await page.waitForXPath("//body"); // Type is ElementHandle<Node> | null. Correct should be ElementHandle<Node>
  console.log({ shouldBeNull, shouldBeElementHandle });

  const functionThatReceivesElementHandle = (element: ElementHandle<Node>) => {}

  functionThatReceivesElementHandle(shouldBeElementHandle!)

  browser.close();
  process.exit();
})();
```

Does this make sense to you? I am eager to join in and assist with resolving this.

**Comment by rhuanbarreto** [comment]
Hi @Rafael-Martins you can do the same as #9529 using overloads. Then the problem gets fixed.

**Comment by rhuanbarreto** [comment]
Hi @Rafael-Martins you can do the same as #9529 using overloads. Then the problem gets fixed.

**Comment by rhuanbarreto** [comment]
Hi @Rafael-Martins you can do the same as #9529 using overloads. Then the problem gets fixed.

**Comment by Rafael-Martins** [comment]
I've completed the changes you requested, but I have one question: Can this function return null even if we have `{hidden: false}`?

**Comment by jrandolf** [comment]
We typically don't like usage of `waitForXPath`. It's possible to use `waitForSelector` directly. If you can send up a PR adding type monomorphism in `waitForSelector`, that would be awesome.

**Comment by OrKoN** [comment]
Yeah, bringing the type inference to other selector types in waitForSelector would be great. But we can also improve `waitForXPath` since we continue to offer this method.

**Comment by Rafael-Martins** [comment]
We modified the documentation to reflect the current behavior and added some tests to further demonstrate the same! (please check discussion on #9583) Can we close this? @rhuanbarreto @OrKoN
