### ISSUE TITLE
[Bug]: launch headless chrome with arg --use-gl=egl(to enable hardware acceleration); webgl app render error

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9544]
### Bug expectation

i test my webglapp by using puppeteer to launch headless chrome  which run in a docker ,used nvidia/opengl:1.2-glvnd-devel-centos7 as my dockerfile base.<br>
when i run my webapp in the container,shader is not correct.<br>
![abnormal](https://user-images.githubusercontent.com/19261291/213411959-5d9643cf-07a8-46ca-b0e7-c4187e65b5a4.png)

 
which should be as following:<br>
 
![normal](https://user-images.githubusercontent.com/19261291/213412039-fee5a2c3-b22c-4f45-94e3-3298b7bd89c5.png)

puppeteer launch args are as following:
```
 args: [
            '--start-maximized',
            // '--start-fullscreen',
            '--enable-precise-memory-info',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            // 测试iframe需要添加该参数
            '--disable-features=site-per-process',
            '--use-gl=egl',
            '--use-cmd-decoder=validating',
            '--enable-webgl',
            '--enable-webgl-developer-extensions',
            '--enable-webgl-draft-extensions',
            '--enable-webgl-image-chromium',
            '--ignore-gpu-blocklist',
            '--enable-gpu-rasterization',
            '--enable-zero-copy',
            '--enable-webgpu-developer-features ',
            '--enable-gpu-debugging',
            '--enable-gpu-driver-debug-logging',
          ],
```
chrome gpu screenshot:<br>
![screenshotgpu](/uploads/bd238a0af9c8fbc9b2f1304d04ae162c/screenshotgpu.png)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
our site is https://www.kujiale.com/.<br>
it's a webapp using threejs.
```

### Error string

no error provided

### Puppeteer version

5.4.1

### Node version

16.14.2

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
You are using an old version of Puppeteer and presumably the browser. Try using the latest version. If you still still the problem with hardware acceleration, please open a bug at crbug.com as it is outside of the Puppeteer's scope.
