### ISSUE TITLE
[Feature]: Support moz-extension pages

### ISSUE THREAD

**Issue by chrmod** [puppeteer/puppeteer#9548]
### Feature description

With help of `web-ext` it is relatively simple to load a webextension into browser controller by Puppeteer. Sadly, Puppeteer is unable to perform any operations on extension pages, methods like `page.goto`, `page.click` timeout. 

Here is a minimal repo to reproduce the problem: https://github.com/chrmod/puppeteer-webextension-test

**Comment by chrmod** [comment]
This issue is a duplicate of https://github.com/puppeteer/puppeteer/issues/6616 but example runs with latest `puppeteer` and `web-ext`.

**Comment by OrKoN** [comment]
Is it Firefox specific?

**Comment by OrKoN** [comment]
cc @whimboo do you have CDP support for extension targets?

**Comment by whimboo** [comment]
No we don't and most likely won't have. I think it's something that we might have to focus on for BiDi at some point. But we don't have time to get it implemented for CDP, sorry.

**Comment by OrKoN** [comment]
I will keep the feature request open then to see how many users are interested.

**Comment by whimboo** [comment]
Closing issue given that it's not something that we will have for CDP but is on the roadmap for WebDriver BiDi.
