### ISSUE TITLE
[Feature]: Get the total page count

### ISSUE THREAD

**Issue by jesben** [puppeteer/puppeteer#9550]
### Feature description

Thanks for an awesome lib!

Is it possible to get the total page count from puppeteer, right now I'm using another lib for that, but if puppeteer can provide it, I'd rather use that?

`const buffer = await page.pdf({
            format: 'A4',
            margin: {
                top: '86px',
                right: '46px',
                bottom: '74px',
                left: '46px'
            }
        });`

**Comment by OrKoN** [comment]
This is out of scope for Puppeteer: using a third party PDF library is the way to go.

**Comment by KalanaPerera** [comment]
PDF library Solution:

npm install pdf-lib

----

const { PDFDocument } = require('pdf-lib');


const buffer = await page.pdf({ format: 'A4', margin: { top: '86px', right: '46px', bottom: '74px', left: '46px' } });


const pdfDoc = await PDFDocument.load(buffer);
const pageCount = pdfDoc.getPages().length;
console.log(`Number of pages: ${pageCount}`);
