### ISSUE TITLE
[Bug]: Localization is not working while uploading file (eg. Hubzähler.txt) in automation test

### ISSUE THREAD

**Issue by arpitgoyal43** [puppeteer/puppeteer#9552]
### Bug expectation

I am using pnpm npm package with nodejs version 14.19 in debian unix operating system. Testcases are written using mocha framework and using webdriver.io for integration with puppeteer.

While uploading the files in automation test with any localized string name like Hubzähler.txt or 逐諾辰虫.txt, testcase is failing continously. 

I tried to change the locale for the shared docker image and passing the prefrences to chrome browser from webdriver.io configuration arguments but nothing is working. 

Can anyone have worked on similar usecase or can suggest any approach ?

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example
 Open any website with upload workflow and upload file with localized file name. Use below webdriver.io capabilities
```TypeScript

```

### Error string

ERROR: waitUntil condition failed with the following reason: Can't call getCellForColumn on element with selector "//*[contains(@class,'upload-file-sample')]//*[contains(@class,'sample-table')]//tbody/tr[descendant::*[contains(@class,'item-label')][contains(text(),'Hubzähler.txt')]]" because element wasn't found
   at Object.uploadFiles

### Puppeteer configuration

```TypeScript
capabilities: [{
    maxInstances: 10,
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
        args: [
            '--no-sandbox',
            '--disable-infobars',
            '--headless',
            '--disable-gpu',
            '--window-size=1440,735'
        ],
        prefs: {
          'intl.accept_languages': 'en, EN, de, DE'
        }
    }
  }],
```

### Puppeteer version

19.5.2

### Node version

14.19

### Package manager

pnpm

### Package manager version

7.25.1

### Operating system

Linux

**Comment by OrKoN** [comment]
It does not look like a bug with Puppeteer directly but more like an issue in your project. It's better to ask this kind of questions on https://stackoverflow.com If you isolate a bug in Puppeteer, please re-open with the minimal reproducible example.
