### ISSUE TITLE
launch headless chrome with arg --use-gl=egl(to enable hardware acceleration); webgl app render error

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9555]
Bug expectation
i test my webglapp by using puppeteer to launch headless chrome which run in a docker ,used nvidia/opengl:1.2-glvnd-devel-centos7 as my dockerfile base.

when i run my webapp in the container,shader is not correct.
![abnormal](https://user-images.githubusercontent.com/19261291/213847209-3615a9da-b217-47af-bff2-a6d15a7c6c16.png)

which is expected to be look like as following:

![normal](https://user-images.githubusercontent.com/19261291/213847213-83021552-2003-4ff4-8c7c-cc7fb83ac8dc.png)

puppeteer launch args are as following:

 args: [
            '--start-maximized',
            // '--start-fullscreen',
            '--enable-precise-memory-info',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            // 测试iframe需要添加该参数
            '--disable-features=site-per-process',
            '--use-gl=egl',
            '--use-cmd-decoder=validating',
            '--enable-webgl',
            '--enable-webgl-developer-extensions',
            '--enable-webgl-draft-extensions',
            '--enable-webgl-image-chromium',
            '--ignore-gpu-blocklist',
            '--enable-gpu-rasterization',
            '--enable-zero-copy',
            '--enable-webgpu-developer-features ',
            '--enable-gpu-debugging',
            '--enable-gpu-driver-debug-logging',
          ],
chrome gpu screenshot:
![screenshotgpu](https://user-images.githubusercontent.com/19261291/213847231-1eef0dd9-1a83-4d3e-b071-f7dd46b8e0ce.png)

**Comment by OrKoN** [comment]
Please don't open the same issue twice, thanks!
