### ISSUE TITLE
How can I type in Quill Editor Div

### ISSUE THREAD

**Issue by umwdeveloper** [puppeteer/puppeteer#9556]
How can I type in the following div. This is Quill Editor div element for typing text

`<div class="ql-editor ql-blank" data-gramm="false" contenteditable="true" data-placeholder="Enter text here..."><p><br></p></div>`

**Comment by Sosyetekadir** [comment]
****

**Comment by OrKoN** [comment]
Please ask this kind of question on StackOverflow, thanks!
