### ISSUE TITLE
page.pdf not saving files with / in their name

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#956]
The steps to reproduce are quite simple. Just try to save a pdf file with ```/``` in it's name.

Can we make it that we pass the filename as a parameter to page.pdf?

![image](https://user-images.githubusercontent.com/1344020/31224053-a9ca72fa-a9cc-11e7-82e4-b0bc279d735e.png)

**Comment by vsemozhetbyt** [comment]
I think it is because the folder `example-with` does not exist. If the path contains an existing folder before the `/`, then PDF is successfully created.

**Comment by ghost** [comment]
The issue that I'm raising is not about the folder in which the PDF should
be saved. It's about the actual name of the PDF file and the fact that you
cannot save PDFs that will have a / character in their name.

In this particular use case I want to save a file in the same folder with
my puppeteer script, but page.pdf believes that my file name also contains
the folder path.

**Comment by vsemozhetbyt** [comment]
Can you create a file with a `/` character in your operating system (without puppeteer)?

**Comment by ghost** [comment]
I'm on OS X and yes I can create a file with / in the name.

**Comment by ghost** [comment]
The problem is that ```page.pdf``` path parameter is interpreted as the path (folder in which the file is going to be saved) + the filename. Ideally we should be able to pass these 2 as different parameters.

```js
await page.pdf({
  path: 'a-folders-name'.
  filename: 'file-name-that-can-/contain/any-valid/char.pdf',
  format: 'A4'
});
```

Later edit: I'm closing this issue because what I want is not possible (currently) because [internally we use ```fs.writeFileSync```](https://github.com/octasimo/puppeteer/blob/master/lib/Page.js#L648) which [doesn't accept more than a filename or file descriptor](https://github.com/nodejs/node/blob/master/lib/fs.js#L1305).
