### ISSUE TITLE
[Bug]: Request interception does not capture oopif iframe subresources

### ISSUE THREAD

**Issue by viperlucror** [puppeteer/puppeteer#9567]
### Bug expectation

I expected `await page.setRequestInterception(true);` to also intercept the subresource requests from iframes, even if they are out-of-process. 

[This test](https://github.com/puppeteer/puppeteer/blob/e13e9647fc0d917da94af8851a09ed318fb0e07c/test/src/oopif.spec.ts#L307) implies that that is the intended functionality, but it doesn't actually check for subresource interception.

The attached example to reproduce is inspired by the equivalent [Playwright Test](https://github.com/microsoft/playwright/blob/caec93ef42b4b93185cf63ecc95fb78cadb2fcf1/tests/library/chromium/oopif.spec.ts#L139).

```diff
diff --git a/test/assets/dynamic-oopif.html b/test/assets/dynamic-oopif.html
--- a/test/assets/dynamic-oopif.html
+++ b/test/assets/dynamic-oopif.html

<script>
window.addEventListener('DOMContentLoaded', () => {
  const iframe = document.createElement('iframe');
  const url = new URL(location.href);
  url.hostname = url.hostname === 'localhost' ? '127.0.0.1' : 'localhost';
-   url.pathname = '/oopif.html';
+  url.pathname = '/grid.html';
  iframe.src = url.toString();
  document.body.appendChild(iframe);
}, false);
</script>
```

```diff 
diff --git a/test/src/oopif.spec.ts b/test/src/oopif.spec.ts
--- a/test/src/oopif.spec.ts
+++ b/test/src/oopif.spec.ts

  it('should load oopif iframes with subresources and request interception', async () => {
     const {server} = getTestState();
+    let intercepted = false;
 
     const frame = page.waitForFrame(frame => {
-      return frame.url().endsWith('/oopif.html');
+      return frame.url().endsWith('/grid.html');
     });
     await page.setRequestInterception(true);
     page.on('request', request => {
+      if (request.url().endsWith('/digits/0.png')) {
+        intercepted = true;
+      }
       return request.continue();
     });
     await page.goto(server.PREFIX + '/dynamic-oopif.html');
     await frame;
     expect(oopifs(context).length).toBe(1);
+    expect(page.frames().length).toBe(2);
+    expect(intercepted).toBe(true);
   });
```

If oopif has not been disabled, this modified test now fails with:
```
 1) OOPIF-debug
       OOPIF
         should load oopif iframes with subresources and request interception:
     Error: expect(received).toBe(expected) // Object.is equality

Expected: true
Received: false
      at Context.<anonymous> (/workspaces/puppeteer/test/src/oopif.spec.ts:327:25)
```

While workarounds exist like passing in `--disable-site-isolation-trials`, it seems like a very heavy hammer and perhaps is a bug in how request interception is intended to work.

Thanks for taking a look!

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
(added inline)
```

### Error string

(added inline)

### Puppeteer version

19.6.0

### Node version

18.13.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Linux

**Comment by OrKoN** [comment]
Thanks for the report. It looks like the network manager might be only working on the page target so it does not attach itself to OOPIFs.

**Comment by lucassardois** [comment]
I think I got the same issue the `--disable-site-isolation-trials` doesn't change anything. For me, the Origin of request which are not intercepted is from `chrome-extension://aapocclcgogkmnckokdopdmhomfmgoek`.

**Comment by szy54** [comment]
I observed different behavior depending on whether I run the puppeteer headless or headed.
While headless I can observe much more requests than headed, probably the difference is the ones from an iframe.
