### ISSUE TITLE
[Bug]: Pupeteer throws "Error: Can't open display" when in headless mode

### ISSUE THREAD

**Issue by jahilldev** [puppeteer/puppeteer#9572]
### Bug expectation

When running Pupeteer in **headless** mode, inside a docker container, I'm getting the following error:
```
Error: Can't open display:

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

Error: Failed to launch the browser process!
Error: Can't open display:

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I wouldn't expect this given I'm running in headless mode.

For reference, here's my `Dockerfile`:

```
FROM node:16

ENV NODE_ENV=production

# Pupeteer Setup
# ---------------------------------------------------
RUN apt-get update && apt-get install -y chromium

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
# ---------------------------------------------------

WORKDIR /app

COPY ["package.json", "yarn.lock", "./"]

RUN yarn

COPY . .

RUN yarn build

EXPOSE 3000

ENTRYPOINT ["node", "dist/main.js"]
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: true,
  args: [
    '--headless',
    '--single-process',
    '--disable-gpu',
    '--disable-dev-shm-usage',
    '--disable-setuid-sandbox',
    '--no-sandbox',
  ],
});
```

### Error string

Failed to launch the browser process! Error: Can't open display:

### Puppeteer configuration

```TypeScript
n/a
```

### Puppeteer version

19.6.0

### Node version

16.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS (M1 Chip)

**Comment by OrKoN** [comment]
@jahilldev we have our official docker image and we run the headless chromium in CI https://github.com/puppeteer/puppeteer/actions/runs/3998289622/jobs/6860735694 

I am not sure why it does not work for you but perhaps you could try using the official image from here: https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer Apart from that, the issue has to with the Chromium browser and not Puppeteer directly so we cannot be of much help.

**Comment by tomw1808** [comment]
@OrKoN I am having the same issue. I started building an application on Windows WSL with google chrome installed. 

The issues started using a new Mac M2. 

Chrome isn't available (to my best knowledge) for arm, so the target needs to be amd64. After fiddling around, I thought I just try to standard chromium instead of chrome. 

Chromium does not come up at all building with the target arm - no error, just sits there forever. Then I changed the target to amd64 `--platform=linux/amd64` when building the image. After running it. this is where I get

```
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
Error: Can't open display: 


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Might need to warrant re-opening the issue.

**Comment by tomw1808** [comment]
Update: the issue with the hanging chromium goes away when using `node:18-slim`, which means, I can use the target platform arm now

**Comment by maheshbansod** [comment]
I get this issue on running in a docker container on Apple M1 with puppeteer in deno.
