### ISSUE TITLE
[Bug]: Page not loading when using Puppeteer 16.x+ and the included chromium version

### ISSUE THREAD

**Issue by mdhont** [puppeteer/puppeteer#9579]
### Bug expectation

Hi, 

As a Bitnami developer, I am running a test script to log in to the Odoo admin page. However, upon submitting the login form, the page remains blank and no errors are shown. I have checked that the issue is not caused by the script or changes in selectors.

Our testing shows that the script fails when using Puppeteer version 16.x and the included Chromium version. We have also tried using Chrome and changing the user agent, but the issue persists. The script works with a previous version of Puppeteer (15.x) when using the included Chromium version or a newer one (110.0.5478.0 (Developer Build) (64-bit)). This suggests that the issue is caused by a change in version 16.0.0 of Puppeteer. Additionally, Puppeteer version 19.x works with an old version of Chromium (105.0.5173.0 (Developer Build) (64-bit)), the same version used by Puppeteer 15.x.

The testing environment is Linux x64 - Ubuntu 18.04.6 LTS and Nodejs version: 16.18.1. Please let me know if further information is needed.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// Launch the latest Odoo version
git clone https://github.com/odoo/docker.git
cd docker/16.0
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:13
docker run -p 8069:8069 --name odoo --link db:db -t odoo

//Visit localhost:8069, fill in setup form

//Login with Puppeteer:

async function login(page) {
  await page.waitForSelector('input#login');
  await page.click('input#login');
  await page.keyboard.type(USERNAME);
  await page.click('input#password');
  await page.keyboard.type(PASSWORD);
  await page.click('input[name$="password"]');
  await page.click('button[type="submit"]');
  await page.waitForXPath('//span[contains(text(), "Administrator")]');
  const adminButton = await page.$x('//span[contains(text(), "Administrator")]');
  if (adminButton.length > 0) {
    page.odooVersion = await getOdooVersion(page);
  }
  await page.screenshot({path: 'login-1-logged-in.png'});
}
```

### Error string

Blank page

### Puppeteer configuration

```TypeScript
// puppeteer options
let opts = {
  headless: false,
  slowMo: 100,
  devtools: true,
  timeout: 500000,
  args: ['--no-sandbox'],
};
```

### Puppeteer version

19.0.0

### Node version

v18.10.0

### Package manager

npm

### Package manager version

9.2.0

### Operating system

Linux

**Comment by mdhont** [comment]
Yes, sorry, I forgot to mention that it also occurs with the latest version 19.6.0.

I've created a script you can use to run Puppeteer:

```
const puppeteer = require('puppeteer');

(async () => {
  const opts = {
    headless: false,
    slowMo: 100,
    timeout: 10000,
    executablePath: '/home/user/.cache/puppeteer/chrome/linux-1083080/chrome-linux/chrome',
    //executablePath: '/usr/bin/google-chrome',
    args: ['--no-sandbox'],
  };

  const browser = await puppeteer.launch(opts);
  page = await browser.newPage();
  await page.setViewport({width: 1280, height: 720});
  await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36');
  await page.goto(`http://localhost/web/login`);
  await page.waitForSelector('input#login');
  await page.click('input#login');
  await page.keyboard.type('USERNAME');
  await page.click('input#password');
  await page.keyboard.type('PASSWORD');
  await page.click('input[name$="password"]');
  await page.waitForTimeout(1000);
  await page.click('button[type="submit"]');
  await page.waitForXPath('//span[contains(text(), "Administrator")]');
  console.log('Success!');
})();
```

**Comment by OrKoN** [comment]
Looks like the shared worker target on that page is not being properly resumed.

**Comment by mdhont** [comment]
Ok. is there a hotfix we can apply, as it is working with older versions?

**Comment by OrKoN** [comment]
Use the older version for now?

**Comment by OrKoN** [comment]
I will look into this in the next weeks. It looks like the bug is in the browser. Perhaps we will find a workaround on Puppeteer side while the browser issue gets fixed.

**Comment by mdhont** [comment]
Ok, thanks

**Comment by mdhont** [comment]
Has this issue been addressed or is there some kind of workaround?

**Comment by OrKoN** [comment]
I was looking into the bug but unfortunately I was not able to get to the bottom of it. I wonder if it started to working with the latest Chrome versions.

**Comment by OrKoN** [comment]
Please try using the latest version if it is still relevant.
