### ISSUE TITLE
[Bug]: puppeteer ships invalid typings for older versions of Typescript 4.3

### ISSUE THREAD

**Issue by Hotell** [puppeteer/puppeteer#9582]
### Bug expectation

We are on TypeScript 4.3.5. Puppeteer repo is on 4.9. 

we try to migrate to v19 but following Typescript errors started to occur (migrating from v17 to v19)

```
src/utils/visitPage.ts:40:9 - error TS2589: Type instantiation is excessively deep and possibly infinite.

await page.waitForSelector('#root-provider');
```

The cause of this is recursive mapped type provided as return type of `waitForSelector` which is `Promise<ElementHandle<NodeFor<Selector>> | null>`.

**Workaround:**

Annotate every puppeteer api call that's causing issues via `@ts-ignore` (which will add significant technical dept to the codebase)

**Solution:**

- change the types complexity (might be not possible)
- start using `typeVersions` to support older TypeScript version ( which is a standard OSS practice )
- explicitly state that you don't support particular versions of TypeScript and provide lowest possible ts version as peerDependency to puppeteer

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

- TS error: https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=283432&view=logs&j=258ec178-2d8b-5611-7b9b-60c5c95dae55&t=254ee48e-1503-524f-f75e-e2c69d0380f5

- PR where we ran into the issue: https://github.com/microsoft/fluentui/pull/26475

### Error string

Type instantiation is excessively deep and possibly infinite.

### Puppeteer version

19.6.0

### Node version

16.16.0

### Package manager

yarn

### Package manager version

1.23.34

### Operating system

macOS

**Comment by Hotell** [comment]
cc @OrKoN

**Comment by OrKoN** [comment]
Thanks for the report but we won’t offer a backward compatibility with older TypeScript versions.

**Comment by OrKoN** [comment]
Let’s see if we can mitigate this.

**Comment by Hotell** [comment]
> Thanks for the report but we won’t offer a backward compatibility with older TypeScript versions.

that's fair. I'd suggest to communicate lowest supported version though for better transparency

**Comment by Hotell** [comment]
> 



> Another workaround should be:
> 
> ```
> const selector = '#root-provider';
> await page.waitForSelector(selector);
> ```

that doesn't work. it's pretty much the same construct from TS type system POV

**Comment by OrKoN** [comment]
What about 

```
```

**Comment by Hotell** [comment]
none of these work.

as I mentioned the main culprit is recursive mapped type `NodeFor` , there is no way around that by using assertions, only ts-ignore,ts-expect-error
