### ISSUE TITLE
*BSD's completely not supported.

### ISSUE THREAD

**Issue by anoduck** [puppeteer/puppeteer#9586]
openbsd is not supported indeed (what does running `node -e "console.log(process.platform)"` outputs on your system?). I doubt you would see it on linux or mac as you report and I am unable to reproduce that.

Oh, you were trying to be cute there. My bad.

_Originally posted by @OrKoN in https://github.com/puppeteer/puppeteer/issues/9445#issuecomment-1360947665_

**Comment by OrKoN** [comment]
Chromium does not offer binaries for openbsd and it's not a priority platform for us.
