### ISSUE TITLE
Fullpage Screenshot Problem with some Single Page Websites

### ISSUE THREAD

**Issue by grafaerig** [puppeteer/puppeteer#959]
**Tell us about your environment:**
* Windows10
* puppeteer 0.11.0

**Problem?**

Fullpage screenshots of single page websites will not be displayed correctly.
I tried to clip areas,  scrolling through the page and **waitForNavigation**. 

Similiar problems with navalia, chromeless and phantomjs.

Is there anything else i can do?

**Steps reproduce**

`const puppeteer = require('puppeteer');
var url = "http://thehenhouse.com.au/";   // page url
var name = "the"
var resWidth = 1366;                // width of screenshot
var resHeight = 1000; 

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage()
  await page.goto(url, {waitUntil: 'load'});
  // await page.waitForNavigation({waitUntil: 'networkidle'});
  await page.setViewport({width: resWidth, height: resHeight});
  await page.emulateMedia('screen');
  await page.screenshot({path: name + '-' + resWidth + '.jpeg', type: 'jpeg', fullPage: true});
  console.log("screenshot done");
  
  await browser.close();
})();`

![the-1366](https://user-images.githubusercontent.com/32541809/31228659-82be459e-a9de-11e7-8713-a50e9cb3c375.jpeg)

**Comment by Kalliser** [comment]
+1 I encounter same bug on mobile version of a website, in a ubuntu environnement.

**Comment by rohmanhm** [comment]
Seems they have lazy load image.

**Comment by riston** [comment]
Scrolling with some wait time didn't solve the issue?

**Comment by rohmanhm** [comment]
For now, I solved my problem with image lazy load by set page viewport height as max as possible.

```ts
await page.setViewport({
      width: 1440,
      height: 10000 // set whatever you want
})
```

**Comment by grafaerig** [comment]
Scrolling with wait time and declare the height of the viewport to a large number does not solve the problem with some pages, e.g. http://thehenhouse.com.au/

**Comment by cjroebuck** [comment]
Use something like urlbox.io? Handles full-height backgrounds ok in full screen mode. https://api.urlbox.io/v1/ca482d7e-9417-4569-90fe-80f7c5e1c781/f1dec2f00eee0b46452e2519b48c660a36d09eb9/png?url=http%3A%2F%2Fthehenhouse.com.au%2F&full_page=true

**Comment by tommedema** [comment]
@cjroebuck this is not a solution as some of us may be trying to create services similar to urlbox.io using puppeteer.

**Comment by tommedema** [comment]
I believe the problem here is that Puppeteer is naively increasing the client height. This is not the same as making an actual screenshot of content below the fold (scrollbar), because content dynamically adjusts based on the client height (e.g. if you use `vh` sizing in CSS).

Therefore we need an actual "screenshot content below the fold" feature, rather than a hack that is simply making the screen size larger temporarily.

**Comment by xavierraffin** [comment]
+1 same issue on https://evo.ca

**Comment by msadougi** [comment]
add this code before screenshot to fix:

`await page.evaluate(async () => {
                var allElems = window.document.getElementsByTagName("*");
                for (var i = 0, max = allElems.length; i < max; i++) {
                    var hEleme = window.getComputedStyle(allElems[i]).height;
                    if(hEleme != 'auto'){
                        var numdEleme = Number(hEleme.slice(0, -2));
                        if(numdEleme > 100 && numdEleme < 1000){
                            allElems[i].style.setProperty("height", numdEleme + 'px', "important");
                        }
                    }
                }
                return true;
            });`

**Comment by ernests** [comment]
> add this code before screenshot to fix:
> 
> `await page.evaluate(async () => { var allElems = window.document.getElementsByTagName("*"); for (var i = 0, max = allElems.length; i < max; i++) { var hEleme = window.getComputedStyle(allElems[i]).height; if(hEleme != 'auto'){ var numdEleme = Number(hEleme.slice(0, -2)); if(numdEleme > 100 && numdEleme < 1000){ allElems[i].style.setProperty("height", numdEleme + 'px', "important"); } } } return true; });`

This works for some cases. I'm still getting long pages. By the way, instagram.com is one of them!

**Comment by zakariamouhid** [comment]
using last version of puppeteer (version **8.0.0**) seems to work.
it works using `--window-size` argument but not working using `viewport`.
```javascript
const puppeteer = require('puppeteer');
const height = 720, width = height * 16 / 9;
const url = 'https://thehenhouse.com.au/';
const options = {
    args: [
      '--window-size=' + width + ',' + height,
    ],
    devtools: false,
    headless: true,
    defaultViewport: null,
};
const browser = await puppeteer.launch(options);
const page = await browser.newPage();
await page.goto(url);
await page.screenshot({
  path: 'example.png',
  fullPage: true
});
```
example in replit
https://replit.com/@zakariamouhid/puppeteer-test-bash#main.js

**Comment by ar-naseef** [comment]
I tried with puppeteer 8.0.0 and it works. Wondering if I can get the AWS lambda layer for Puppeteer 8.0.0?
