### ISSUE TITLE
[Feature]: Preset and set opener 

### ISSUE THREAD

**Issue by guest271314** [puppeteer/puppeteer#9603]
### Feature description

I am working on transferring data, including infinite streams using Streams API, from an extension `ServiceWorker` to arbitrary Web page.

Problems:
- When using an `<iframe>` appended to the current `document` as a bridge with `postMessage()` the `<iframe>` can be removed from the `document` using `DOMNodeInserted` or `MutationObserver`;
- When using `window.open()` there is no way that I am aware of to set the `width` and `height` to `0` so that the `window` does not flash before using extension code to set focus on the `opener` and set the `height` and `width` of the opened `window` to `0` - Chromium always reduces the opened window dimensions to some amount greater than `0` and keeps the `window` in the viewport;
- When using an offscreen document (https://developer.chrome.com/blog/Offscreen-Documents-in-Manifest-v3/) there is no way to set the `opener` of the offscreen document

Since Puppeteer can launch a new Chromium session  and/or attach to an existing target it would be helpful for the ability to preset and dynamically set the `opener` of a `window`. In this case preset the `opener` of an offscreen document to an arbitrary Web page, so we can use `opener.postMessage()` in the offscreen document target to establish a direct communication channel with the arbitrary Web page.

**Comment by jrandolf** [comment]
The word `arbitrary` is very dangerous; this feature would not only break spec, but also break security barriers placed in by design.

**Comment by guest271314** [comment]
> The word `arbitrary` is very dangerous; this feature would not only break spec, but also break security barriers placed in by design.

I don't think so. What spec are you referring to?

We can already achieve the feature request using several means, including `window.open()`, e.g., https://github.com/guest271314/sw-transfer-stream, https://github.com/guest271314/offscreen-webrtc. Just cumbersome. Chrome extensions in MV2 provided a means to do that [setSelfAsOpener](https://developer.chrome.com/docs/extensions/reference/windows/#:~:text=ignored%20for%20panels.-,setSelfAsOpener,-boolean%C2%A0optional). Since we are dealing with performing all sorts of arbitrary operations using Puppeteer, such as intercepting all requests I don't see how this would break anything. Can you kindly cite what sections of which specification or standards you think would break?
