### ISSUE TITLE
[Bug]: Puppeteer Firefox CDP error

### ISSUE THREAD

**Issue by galaczi** [puppeteer/puppeteer#9605]
### Bug expectation

I set up a Puppeteer project via the CLI and tried to use Firefox. I got a CDP issue, which I think a Chromium only feature.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// For more information, see https://crawlee.dev/
import { PuppeteerCrawler, log } from 'crawlee';
import { router } from './routes.js';

const startUrls = ['https://crawlee.dev'];

const crawler = new PuppeteerCrawler({
    requestHandler: router,
    launchContext: {
        launchOptions: {
            product: 'firefox',
            headless: false,
        }
    }
});

await crawler.run(startUrls);
```

### Error string

WARN  PuppeteerCrawler: Reclaiming failed request back to the list or queue. Protocol error (Page.setDeviceMetricsOverride): Page.setDeviceMetricsOverride RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5 UnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7 execute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13 receiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45

### Puppeteer version

19.6.2

### Node version

v19.0.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Linux

**Comment by OrKoN** [comment]
Thanks for the report. Firefox does not implement all of CDP features and there are no plans to improve that due to the focus on the WebDriver BiDi protocol.

**Comment by OrKoN** [comment]
cc @whimboo

**Comment by whimboo** [comment]
Note that `[Page.setDeviceMetricsOverride](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDeviceMetricsOverride)` is deprecated. Instead `[Emulation.setDeviceMetricsOverride](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride)` should be used. The latter one is implemented in Firefox and only misses support for the `mobile` and `screenOrientation` arguments.
