### ISSUE TITLE
[Bug]: puppeteer.launch does not work on wsl

### ISSUE THREAD

**Issue by shunsock** [puppeteer/puppeteer#9608]
### Bug expectation

I want to use puppeteer on wsl, but `puppeteer.launch()` does not work. 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    timeout: 30000*10,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--no-first-run',
      '--no-zygote',
      '--single-process',
    ]
  });
  const page = await browser.newPage();
  await page.goto('https://www.example.com');
})();
```

### Error string

TimeoutError: Timed out after 300000 ms while trying to connect to the browser

### Puppeteer version

19.6.2

### Node version

18.13.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Hello @ShunDeveloper, please refer to the [WSL Troubleshooting](https://pptr.dev/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux) and the tread that it links.
