### ISSUE TITLE
[Bug]: hardware accelerate but at reduced performance[19.6.2]

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9611]
### Bug expectation

I expect 'hardware accelerate' as following(which i used 15.4.0):<br>
![15 4 0](https://user-images.githubusercontent.com/19261291/215942787-a7013224-90ae-4af7-b6db-6d7c92ee02d4.png)
But when i upgrage to 19.6.2,i get:<br>

![19 6 2](https://user-images.githubusercontent.com/19261291/215943217-23812f5c-6b1e-4835-b546-07034700a565.png)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
 headless: true,
  args: ["--use-gl=egl",'--no-sandbox'],
  })
  const page = await browser.newPage()

  // set the viewport so we know the dimensions of the screen
  await page.setViewport({ width: 800, height: 600 })

  // go to a page setup for mouse event tracking
  await page.goto('chrome://gpu')

  }
```

### Error string

no error reported

### Puppeteer version

19.6.2

### Node version

16.19.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Linux

**Comment by OrKoN** [comment]
Thanks for the report: could please re-open it as crbug.com? Puppeteer does not do more than forwarding custom flags to the browser.
