### ISSUE TITLE
[Bug]: Multiple pages time out on MacOS

### ISSUE THREAD

**Issue by LeviPesin** [puppeteer/puppeteer#9613]
### Bug expectation

Hello!

I'm currently [trying to add in-browser parallelism to the Three.js' Puppeteer E2E test](https://github.com/mrdoob/three.js/pull/25386) by using multiple pages in a browser.

Unfortunately, at every MacOS run (no problem on Windows or Ubuntu!) some examples tested (about 1-7) [fail randomly](https://github.com/mrdoob/three.js/actions/runs/4061723848/jobs/6992021029) with the "TimeoutError: Navigation timeout of 90000 ms exceeded" error.
I've though it might be https://github.com/puppeteer/puppeteer/issues/8693 -- and indeed the issue [seems to resolve](https://github.com/mrdoob/three.js/actions/runs/4061348198/jobs/6991276750) (fails are not from TimeoutError but rather from differences between rendering headless and headful) when running in headful mode, but [**does not** resolve](https://github.com/LeviPesin/three.js-1/actions/runs/4061619290/jobs/6991819394) when using multiple browsers instead of multiple pages.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
Sorry, unable to make a minimal example -- please see https://github.com/LeviPesin/three.js-1/blob/875492ceffc599051ffeeeb2ba7430942a427f40/test/e2e/puppeteer.js
```

### Error string

TimeoutError: Navigation timeout of 90000 ms exceeded

### Puppeteer version

19.6.2

### Node version

16.19.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

macOS

**Comment by OrKoN** [comment]
Thanks for the report: it'd be get to minimize the repro, otherwise, it's practically in-actionable for us. Also, you say that it works on other platforms: perhaps there is just not enough resources on Mac or it's a bug in the Chromium version. If we have a minimal repro, we can judge if it is a problem with Puppeteer or if we need forward the report to crbug.com.

**Comment by LeviPesin** [comment]
It seems that increasing the timeout resolves the issue... So maybe it's just slow on Mac. Thank you!

**Comment by LeviPesin** [comment]
It seems that sometimes it fails even with an extremely large timeout... For example, in https://github.com/mrdoob/three.js/actions/runs/4081675133/jobs/7035276477.

**Comment by OrKoN** [comment]
Interesting, what happens if you reduce the concurrency?

**Comment by OrKoN** [comment]
You use the hosted macos runners, right? I know that they only have 4 cores so running multiple concurrent processes might not work too well. Is it reproducible for you in the local runs?

**Comment by LeviPesin** [comment]
> Interesting, what happens if you reduce the concurrency?

Will test. With 16 pages and 5 minute timeout it broke on about 10th run.

> You use the hosted macos runners, right? I know that they only have 4 cores so running multiple concurrent processes might not work too well.

I checked [GitHub documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) and it seems like Mac runners have more resources (3 cores and 14 GB RAM) than Windows and Ubuntu (2 cores and 7 GB RAM), but only Mac fail.

> Is it reproducible for you in the local runs?

Unfortunately I don't have a Mac myself -- but I will ask someone t test.

**Comment by OrKoN** [comment]
What could be also happening is that the node process that runs Puppeteer and tests gets busy (are there cpu-intensive things on the node process?). If that happens, the timeouts will fire while the browser is navigating normally because the node process was doings smth else and could not process messages from the browser.

**Comment by LeviPesin** [comment]
> are there cpu-intensive things on the node process?

No, the Node process only runs Puppeteer tests.

**Comment by OrKoN** [comment]
@LeviPesin tests could also get busy if many browser instances send many events and perhaps tests try to parse/re-process screenshots etc.

**Comment by LeviPesin** [comment]
Seems like for 8 pages and 1.5 minutes network timeout it [also](https://github.com/mrdoob/three.js/actions/runs/4082043041/jobs/7035979021) [fails](https://github.com/LeviPesin/three.js-1/actions/runs/4082042719/jobs/7035978452) [almost](https://github.com/LeviPesin/three.js-1/actions/runs/4082042719) on every run (2 fails from 3 runs), but for 4-1.5 or 8-5 -- mostly succeeds (3 successes from 3 runs). So it seems to be related to concurrency...
I will try to make a minimal example.
