### ISSUE TITLE
[Bug]: Chromium should ignore single sign on user identity in incognito and guest modes if it is running in headless mode

### ISSUE THREAD

**Issue by zoltan-boros** [puppeteer/puppeteer#9615]
### Bug expectation

Observed, unexpected behavior:
Chromium preserves single sign on user identity despite incognito and guest modes if it is running in headless mode.

Expected behavior:
Chromium ignores single sign on user identity in incognito and guest modes if it is running in headless mode

Details:
In corporate network I am logged in to a Windows computer with my own user and drive Chromium using Puppeteer. About to access a web app that belongs to the corporate single sign on domain. However, I would like to authenticate some other user's behalf, not my own. Therefore I start the browser either in incognito mode, or with guest account. (in order the browser to ignore my own user's identity)

```javascript
puppeteer.launch({
  args: [ '--incognito' ],
  // ...
});
```

or

```javascript
puppeteer.launch({
  args: [ '--guest' ],
  // ...
});
```

Then, set credentials for authentication:

```javascript
page.authenticate({
  username: '...', // some other user than my own
  password: '...',
});
```

Afterwards, open the URL that points to the web app. (This loads the login page, since the request didn't contain auth token.) Fill in username, then click next.
Authentication takes place through some redirections and finally the web app gets loaded.
However, the user, that gets logged in, dependes on if browser is running in headless, or headful mode.
In headful mode, browser respects the incognito/guest modes. i.e. ignores the user that is logged in to the host computer; the other user (specified by credentials) gets logged in to the web app. - As expected.
In headless mode, browser ignores incognito/guest modes and the supplied credentials of other user. In the web app I see that my own user is logged in. - Wrong.

I would expect, that behavior is the same in headless and headful modes.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({
    // headless: false, // It works as expected in headful mode.
    headless: true, // It works wrong in headless mode.
    // Either
    args: [ '--incognito' ],
    // or
    args: [ '--guest' ],
    ignoreDefaultArgs: false,
  });

  const page = (await browser.pages())[0];

  const username = 'user.other.than.the.one.logged.in.to.the.host.computer@mycorporate.com';

  await page.authenticate({
    username,
    password: '...',
  });

  await page.goto('some-web-app.mycorporate.com');

  await page.type('#username', username);
  await page.click('#next');

  // Wait for login procedure to complete, then check which user is logged in.
})();
```

### Error string

no error

### Puppeteer version

19.6.3

### Node version

14.19.0

### Package manager

npm

### Package manager version

8.5.5

### Operating system

Windows

**Comment by jrandolf** [comment]
Just to confirm, you're saying cookies from headful/normal mode are being read from headless/incognito mode, right?

**Comment by zoltan-boros** [comment]
Headful and headless runs are independent from each other, cookies are not shared between these runs.

**Comment by OrKoN** [comment]
Headless is already using an incognito profile by default if no user-data-dir flag is specified so I guess the profile gets re-used because both times it's run with the user data dir (no --user-data-dir because of ignoreDefaultArgs)? Could you verify that the user data dir is the same in both launches by providing the logs produced with the env var `DEBUG=puppeteer:launcher`? 

After that we can send it to crbug.com as it is not directly related to Puppeteer's functionality.

**Comment by jrandolf** [comment]
> Headful and headless runs are independent from each other, cookies are not shared between these runs.

I understand this, but I'm trying to understand your claim. Is your claim that headless mode is taking data from your normal browser? Data can be anything from a cookie to indexeddb info.

Note that SSO is really just a cookie/user data stored on the browser.

**Comment by jrandolf** [comment]
@OrKoN This issue should be independent of --user-data-dir since incognito mode is explicitly specified.

**Comment by jrandolf** [comment]
We are not able to reproduce with our own SSO. Please add a full MVCE for us to continue. Otherwise, we will not be able to help.

**Comment by zoltan-boros** [comment]
Sorry for phrasing unclear.

@OrKoN, I set env var as you suggested ( `set "DEBUG=puppeteer:launcher"` ), then started my script in the same console window, however I cannot see any log printed in console.
I tried enable logging by adding `--enable-logging --v=1` args to `puppeteer.lauch()` props. This didn't print any debug to the console. After some search on the internet I found, that it logs to user directory, but that is to be figured out.

Let me come up with examples to clarify the issue.

**Initial state for each scenario:**
I am logged in with my own user to my Windows computer within corporate network. (Active Directory? Windows domain?)

**Scenario 1 - done manually:**

1. I start normal Chrome
2. In normal window (i.e. non-incognito, non-guest window) open app.my-corporate.com - An html page appears, that contains merely an email field and a next button.
3. I enter my corporate email address, then click next
4. After some redirections, the initially requested page (app.my-corporate.com) appears. - As expected.

**Scenario 2 - done manually:**

1. I start normal Chrome
2. Open a new _incognito_ window
3. Open app.my-corporate.com - An html page appears, that contains merely an email field and a next button.
4. I enter my corporate email address, then click next
5. After some redirections, browser's native authentication dialog appears, asking for username + password. I enter them, then click OK.
6. Finally, the initially requested page (app.my-corporate.com) appears. - As expected.

**Scenario 3 - done by Puppeteer:**

(Basically, the scenario is the same as before, but this time it is done by Puppeteer.)

1. Start Chromium in headless, incognito mode:

```javascript
const browser = await puppeteer.launch({
    headless: true,
    args: [ '--incognito' ],
});
const page = (await browser.pages())[0];
```

2. I would expect, that setting credentials for browser's native authentication dialog is necessary, however intentionally skipped.
```javascript
// Code would be the following, however, for the sake of demoing the issue, intentionally skipped.
// await page.authenticate({
//     username: '...',
//     password: '...',
// });
```

3. `await page.goto('app.my-corporate.com');`

4. Enter my corporate email address, then click  next:
```javascript
await page.type('#email', '...');
await page.click('#next');
```

5. Authentication successfully passed (!?) the page requested at step 3 appears. (logged in user: my user) - Unexpected.

The same happend as in Scenario 1, despite incognito mode.
In incognito mode I would expect that the same authentication is required as in Scenario 2 step 5.
Consequently, Scenario 3 should not work without its step 2.
What is wrong?
