### ISSUE TITLE
[Feature]: Move chromium mac_arm out of experimental and into normal support

### ISSUE THREAD

**Issue by epreston** [puppeteer/puppeteer#9630]
### Feature description

Hello.

Setting up chromium to use the `mac intel` build on `mac arm` by default is starting to show issues and differences.  

You guys planned ahead and have been offering an experimental, yet required, way to change this using the `BrowserFetcherOptions` for more than a year.  

> **That's impressive.**

Here's the issues:

- Since the proper release and support of the chromium arm build, the crossover is not getting the same level of attention and testing from the chromium project.
- It's not recommended and when there are issues that are fixed in the supported arm release, that's the recommendation you get.  Use the supported build for your platform.  
- As you know it's relying on Rosetta emulation. Rosetta is not installed by default but activated on first use which can give the wrong impression about puppeteers speed.
- It causes some tests to fail in a situation that users will not experience.
- It causes developer friction and confusion which I've seen people lose time to.  For example: you need to know the setting hidden in the docs, it has the mental model of running win_32 on win64 by default unless you give a special setting.. 

Suggested Outcome:

Is it time to remove the notes from the source and other materials about it being `experimental` and put it into regular support ?  

Maybe even make it default for the `BrowserFetcher`'s chromium install to deploy `mac_intel on mac_intel` and `mac_arm on mac_arm` the way nature and google intended ?  

I couldn't recommend leaving a method to continue to cross them as its unsupportable.

Thank you for your time.

**Comment by OrKoN** [comment]
We are still lacking GitHub Actions support for MacOS ARM (AFAIK it's still in beta https://github.com/github/roadmap/issues/528). We will try to unexperiment it as soon as we can though.

**Comment by epreston** [comment]
That makes sense.  Yes, that is a limiting factor for your validation tests running on GH Actions to in-turn validate that it will maintain the same quality for others.  Looks like they set a date at least.

Thank you.

**Comment by Nate-Asmare** [comment]
I can't even install the latest puppeteer library through `npm i puppeteer` on my M1 mac.

Even after I managed to install it through yarn I can not run the app. I'm getting the below error. Can any of you help?


`Error: EACCES: permission denied, open '/Users/nate/.config/puppeteerrc'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at readFileSync (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/readFile.js:45:33)
    at ExplorerSync.loadSearchPlaceSync (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/ExplorerSync.js:69:48)
    at ExplorerSync.searchDirectorySync (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/ExplorerSync.js:55:32)
    at run (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/ExplorerSync.js:35:27)
    at cacheWrapperSync (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18)
    at ExplorerSync.searchFromDirectorySync (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/ExplorerSync.js:47:49)
    at run (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/ExplorerSync.js:39:21)
    at cacheWrapperSync (/Users/nate/Documents/Projects/remote_job_scout/node_modules/cosmiconfig/dist/cacheWrapper.js:28:18) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/nate/.config/puppeteerrc'
}`

I'm using node v18.14

**Comment by epreston** [comment]
@Nate-Asmare  How about raising an issue about it instead of putting it in some random feature request ?

**Comment by LeviPesin** [comment]
It seems sometimes GPU (or maybe just WebGL) doesn't work properly with ARM build -- see https://github.com/mrdoob/three.js/pull/25504#issuecomment-1429458541. /ping @mrdoob

**Comment by epreston** [comment]
@LeviPesin puppeteer doesn't develop chromium and when they use it, they distribute a specific version.

**Comment by OrKoN** [comment]
This should be now properly supported in v20.0.0 (although we still don't have GitHub Actions support)

**Comment by 7rulnik** [comment]
@OrKoN arm runners were launched today. Can we use them?
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
