### ISSUE TITLE
customize font size

### ISSUE THREAD

**Issue by zicao88** [puppeteer/puppeteer#9633]
Puppeteer can change the customize font size of  the browser ? 
![image](https://user-images.githubusercontent.com/54791452/217489288-dec1e30c-de1a-41d6-8178-c8d93e80ef0d.png)
What shall I do?

**Comment by zicao88** [comment]
I want to change the settings

**Comment by OrKoN** [comment]
Try using community plugins such as puppeteer-extra-plugin-user-preferences to set the browser settings:  https://github.com/berstend/puppeteer-extra/tree/523b2efe7dc000536ef6bd608810d4e01e206504/packages/puppeteer-extra-plugin-user-preferences or try using CDP methods to configure fonts for a page: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setFontSizes
