### ISSUE TITLE
[Docs]: Headless 'chrome' mode changed

### ISSUE THREAD

**Issue by MoKhajavi75** [puppeteer/puppeteer#9653]
### Bug expectation

Hey

As mentioned on [this](https://pptr.dev/guides/chrome-extensions) page, I used `chrome` mode to have extensions in headless mode.
I guess we had a breaking change that it's not documented because the `chrome` mode is no longer available:

```ts
Type '"chrome"' is not assignable to type 'boolean | "new" | undefined'
```

What's the `new` mode which is on [this](https://pptr.dev/api/puppeteer.browserlaunchargumentoptions) page?

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
it's docs issue!
```

### Error string

Type '"chrome"' is not assignable to type 'boolean | "new" | undefined'

### Puppeteer version

19.6.3

### Node version

18.14.0

### Package manager

pnpm

### Package manager version

7.27.0

### Operating system

macOS

**Comment by MohamadKh75** [comment]
Sorry to mention but this is an issue in docs.

cc @OrKoN
