### ISSUE TITLE
[Feature]: Add "dontBlockOnDialog" to click options to prevent click() blocking on dialog

### ISSUE THREAD

**Issue by SEUH** [puppeteer/puppeteer#9666]
### Feature description

Hello,

the current Page/ElementHandle click() functions block until an opening dialog is completed. This is a massive issue when writing a synchonous API for puppeteer. I don't think the click function should ever block on a dialog but i guess that this is due to the devtools protocol waiting for the dialog to complete until it returns. I don't understand why it would handle it like that. In the "real world" a user can release the mouse and only therefore the dialogue can open (if called in onclick e.g.). So i am not sure why the devtools protocol would block on `mouseReleased`.

A possible solution would be to:

1. mouse.down()
2. clickUpPromise = mouse.up()
3.
```js
page.on('dialog', () => {
  // check if clickUpPromise is already fullfilled/rejected
  if (clickUpPromise) {
    // if not, fullfill it as most likely the opening dialog was because of the previous mouse.down() call
    clickUpPromise.fullfill();
  }
));
```
I know this is a messy solution which also has the problem that in the time mouse.up() is called and the page opens a dialog, the click promise would fullfill immediately without ever clicking anything.

I understand that this solution is too messy to implement in a solid library, so is this maybe a feature request for the devtools protocol? Because it would be great to have this natively supported by puppeteer.

Any other ideas are very welcome 

Edit:
I guess the actual problem is that mouse.up() blocks because the opening dialog stops the excecution of the javascript and the devtools protocol calls the click in the runtime. So now it makes sense that the `dispatchMouseEvent` type is called `mouseReleased` because it actually waits for the mouse to be released. Thats annoying. Now i don't see any way someone would implement this. Even in the webdriver protocol spec they register an "user prompt handler"... I guess this can be closed since this is a niche feature although this would be needed to enable a "good" synchronous dialog api (that doesn't need to register a dialog handler beforehand).

**Comment by OrKoN** [comment]
The dialogs do block JS and event handler. I have not exactly understood what the issue is but looks like you found a solution/understanding. And the click would likely to get resolved only after the dialog has been handled so you should not probably check if the click that caused the dialog succeeded.

**Comment by SEUH** [comment]
The issue is that click blocks if a dialog opens. This behaviour is not compatible with a synchronous API except if you register a dialog handler before you make a click (but that is a bad design).

> after the dialog has been handled so you should not probably check within the dialog handling if the click that caused the dialog succeeded

thas not possible in a (good) synchronous way, thats the problem. It would be great to have the option to control the blocking behaviour of a dialog opening on click, hence this feature request. But like i said above, this is a niche feature, but a big problem when you want to support programming languages that don't have native asynchronous capabilities. I understand that this will most likely never be implemented due to the limitation on the devtools protocol and webdriver protocol, thats why i understand that this feature request gets closed.
