### ISSUE TITLE
Intercept and modify code from native javascript eval function

### ISSUE THREAD

**Issue by tokiodeo** [puppeteer/puppeteer#9668]
### Feature description

I would like to see and modify some of the code that will be injected via `eval`, not sure if it can be done puppeteering if anyone knows how I can do it please comment.

**JSHandle.js** class generates text of console.log.

**Comment by OrKoN** [comment]
Please ask this kind of questions on StackOverflow: https://stackoverflow.com/questions/tagged/puppeteer
