### ISSUE TITLE
[Bug]: undefined symbol: gbm_bo_get_modifier

### ISSUE THREAD

**Issue by yujun-0127** [puppeteer/puppeteer#9669]
### Bug expectation

I use puppeteer-core with chrome-linux from https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1095492/chrome-linux.zip.

![image](https://user-images.githubusercontent.com/9698838/218697054-7d2bf1aa-c0a7-4e37-bfff-2c6b663fb8e1.png)

I excute `node index.js`, then the error came out.  How can i resolve it?

```JavaScript
(node:32513) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
./chrome-linux/chrome: symbol lookup error: ./chrome-linux/chrome: undefined symbol: gbm_bo_get_modifier


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/xxx/example/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at Interface.<anonymous> (/opt/xxx/example/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```JavaScript
// index.js

const puppeteer = require('puppeteer-core');
(async () => {
  const browser = await puppeteer.launch({ headless: true, executablePath: './chrome-linux/chrome', args: ['--no-sandbox'] });
  const page = await browser.newPage();

  await page.goto('https://www.baidu.com/');

  // Set screen size
  await page.setViewport({ width: 1080, height: 1024 });

  await browser.close();
})();
```

### Error string

undefined symbol: gbm_bo_get_modifier

### Puppeteer version

19.7.0

### Node version

14.21.1

### Package manager

npm

### Package manager version

6.14.17

### Operating system

Linux

**Comment by Lightning00Blade** [comment]
Where are you running this? I can see a similar issue #9223. Also please do check our [Troubleshooting](https://pptr.dev/troubleshooting#chrome-headless-doesnt-launch-on-unix). That section may help.

**Comment by yujun-0127** [comment]
> Where are you running this? I can see a similar issue for docker in #9223. Also please do check our [Troubleshooting](https://pptr.dev/troubleshooting#chrome-headless-doesnt-launch-on-unix). That section may help your case.

I run this in linux virtual machine, not in a docker. The system version is `EulerOS release 2.0 (SP2)` based on CentOS.  I have checked [Troubleshooting](https://pptr.dev/troubleshooting#chrome-headless-doesnt-launch-on-unix) but not found a solution.

**Comment by yujun-0127** [comment]
After the Linux system version is upgraded, this problem is solved.

**Comment by wozuiyangqi** [comment]
there is also a way to uninstall libgbm and reinstall libgbm with chrome

**Comment by wozuiyangqi** [comment]
reinstalling libgbm can solve this problem
