### ISSUE TITLE
[Bug]:  Chromium issues "Aw snap" error code 5 page while navigating pages and grabbing urls from those pages

### ISSUE THREAD

**Issue by dwillisgh** [puppeteer/puppeteer#9677]
### Bug expectation

for most urls we scrape the code works fine.
for a few urls chromium issues the  "Aw snap" error code 5 page  and seems to hang the puppeteer script.
I am guessing chromium isnt returning back to puppeteer

The chromium issue happens in a different page in each script run on the await page.$x

console.log("before jobLookUpCriteria: " + jobLookUpCriteria);
    let urlElements = await page.$x(jobLookUpCriteria);
    console.log("after jobLookUpCriteria: " + jobLookUpCriteria);

Here is the end of the output
exact numeric page match//a[.='37'] length[1]
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27

Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27

<--- Last few GCs --->

[98560:0x124013a8000]   150521 ms: Scavenge 281.1 (304.8) -> 275.8 (305.0) MB, 1.07 / 0.00 ms  (average mu = 0.981, current mu = 0.976) task; 
[98560:0x124013a8000]   151057 ms: Scavenge 281.6 (305.0) -> 276.6 (305.8) MB, 1.19 / 0.00 ms  (average mu = 0.981, current mu = 0.976) task; 
[98560:0x124013a8000]   151687 ms: Scavenge 282.3 (305.8) -> 277.2 (306.0) MB, 1.32 / 0.00 ms  (average mu = 0.981, current mu = 0.976) task; 

<--- JS stacktrace --->

[98560:259:0216/100147.150728:ERROR:v8_initializer.cc(750)] V8 process OOM (Oilpan: Reserving memory.).
before jobLookUpCriteria: //a
/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Runtime.callFunctionOn): Target crashed
    at /Users/dwillis/Documents/GitHub/jobs-node-crawler-service/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
    at ExecutionContext._ExecutionContext_evaluate (/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:207:46)
    at async Object.internalHandler.queryAll (/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/node_modules/puppeteer-core/lib/cjs/puppeteer/common/QueryHandler.js:71:30)
    at async CDPElementHandle.$$ (/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ElementHandle.js:141:17)
    at async getCrawledUrlsByCriteria (/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/src/main/testhang.js:194:23)
    at async extractUrls (/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/src/main/testhang.js:104:42)
    at async crawlByCompany (/Users/dwillis/Documents/GitHub/jobs-node-crawler-service/src/main/testhang.js:76:33)
    at async /Users/dwillis/Documents/GitHub/jobs-node-crawler-service/src/main/testhang.js:51:23

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {
const options = {
    headless: false,
    dumpio: true,
    args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage"
    ]
};
const browser = await puppeteer.launch(options);

let page = await browser.newPage();

// set user agent (override the default headless User Agent)
await page.setUserAgent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4427.0 Safari/537.36');

// indicate we are a desktop page
const device_width = 1920;
const device_height = 1080;
await page.setViewport({width: device_width, height: device_height})

page.on('console', consoleObj => console.log(consoleObj.text()));

// this url manifests the issue
let url = "https://jobs.vioc.com/";

// below is a url that works
//let url =  "https://17012017.staging.softgarden.io/es/vacancies";
let response;

// 1st try a goto waitUntil networkidle0
try {
    response = await page.goto(url, {timeout:  45000, waitUntil: "networkidle0"});
} catch (err) {
    // 2nd try a goto waitUntil load
    console.log("Failed to connect to url:" + url + " with networkidle0 error:" + err + " will try goto waitUntil load");
    try {
        response = await page.goto(url, {timeout: 45000, waitUntil: "load"});
    } catch (err) {
        // at this point we give up
        console.log("Failed to connect to url:" + url + " error:" + err);
        throw err;
    }
}

console.log(`url is ${url} opened`);

let numCrawledUrls =  await crawlByCompany(
    url,
    page
);

console.log("NumCrawledUrls:" + numCrawledUrls);

if (page) {
    await page.close();
}
if (browser) {
    await browser.close();
}
})();

const crawlByCompany = async (
    url,
    page
) => {

    let crawledUrls = [];
    let jobLookUpCriteria = "//a";

    try {

        let extractUrlsResult = await extractUrls(page,
            jobLookUpCriteria,
            2500
        );

        crawledUrls = extractUrlsResult.crawledUrls;

    } catch (error) {
        throw error;
    }

    return crawledUrls.length;
};

async function extractUrls (page,
                            jobLookUpCriteria,
                            timeout
) {
    let crawledUrls = [];
    let pageNum = 0;
    let nextPage = null;
    let nextPageElementHandle = null;

    do {
        pageNum++;
        nextPage = null;

        // get urls from current page
        let crawledUrlsFromCurrentPage = await getCrawledUrlsByCriteria(
            page,
            jobLookUpCriteria
        );

        // if the urs are already in our list of urls collected we stop
        if (compareArraysInclude(crawledUrlsFromCurrentPage, crawledUrls)) {
            console.log("Current Page urls match existing collected urls, terminating pagination");
            let extractUrlsResult = {
                numPagesCrawled: pageNum - 1,
                crawledUrls: [...new Set(crawledUrls)]
            };
            return extractUrlsResult;
        }

        crawledUrls.push(...crawledUrlsFromCurrentPage);

        // get the next numeric page element
        nextPageElementHandle = await getNextPageElementHandle(
            page,
            pageNum
        );

        // click the next numeric page elemnt if we found one
        if (nextPageElementHandle) {
            nextPage = true;

            // companycrawling use click or navigation promise.race
            await applyClickToPage(page,nextPageElementHandle,timeout);

           // problem was I wants disposing the element handle. thanks [OrKoN](https://github.com/OrKoN)
           nextPageElementHandle.dispose();
        }
    } while (nextPage);

    crawledUrls = [...new Set(crawledUrls)];

    console.log("crawlerhelper.extractUrls() numPagesCrawled: " +
        pageNum +
        ", crawledUrls size: " +
        crawledUrls.length);

    let extractUrlsResult = {
        numPagesCrawled: pageNum,
        crawledUrls: crawledUrls
    };

    return extractUrlsResult;
};

// look for element on page that matches pageNum
async function getNextPageElementHandle(page, pageNum) {
    // using context item expression "."
    // order is important here. Originally we only looked for //a
    const elementsToFind = ['//a', '//button','//li', '//input'];
    const nextPageNum = pageNum + 1;
    let nextPageElementHandle = [];
    let nextPageContainsElementHandles = [];

    for(let elementToFind of elementsToFind) {

        // exact match for elementsToFind equals nextPageNum
        const nextPageCriteria = `${elementToFind}[.='${nextPageNum}']`;
        nextPageElementHandle = await page.$x(nextPageCriteria);
        if(nextPageElementHandle.length) {
            console.log("exact numeric page match" + nextPageCriteria + " length[" + nextPageElementHandle.length + "]");
            return nextPageElementHandle[0];
        }
        console.log(nextPageCriteria + " not matched");
    }

    // means we didnt find a matching html elment
    return nextPageElementHandle[0];
}

// click the element that matched the next page number
async function applyClickToPage(page, elementHandle,timeout) {

    await Promise.race([

        page.evaluate(nextPageLink => nextPageLink.click(), elementHandle),
        page.waitForNavigation({ timeout:  timeout, waitUntil: 'networkidle0' })
    ]);

}

// get all the urls from the page
async function getCrawledUrlsByCriteria(page, jobLookUpCriteria) {
    let crawledUrls = [];

    await new Promise(r => setTimeout(r, 2500));

    console.log("before jobLookUpCriteria: " + jobLookUpCriteria);
    let urlElements = await page.$x(jobLookUpCriteria);
    console.log("after jobLookUpCriteria: " + jobLookUpCriteria);
    for (let urlElement of urlElements) {
        let crawledUrl = await page.evaluate((el) => el.href, urlElement);
        crawledUrls.push(crawledUrl);
    }
    // check if there are childframes and if yes, try to get urls from those child frames
    // we can also try page.frames() if we are seeing issues here
    const childFrames = page.mainFrame().childFrames();
    //const childFrames = await page.$$('iframe');
    if (childFrames && childFrames.length > 0) {
        console.log("Child Frames:", childFrames.length);
        for (let childFrame of childFrames) {

            let childPageFrameName = childFrame.name();
            // note all iframes might not have names
            console.log("Child Frame Name:", childPageFrameName);
            // checking for presence of url, might need to add check for document content of iframe as well
            if (!childFrame.url()) {
                continue;
            }
            let urlElements = await childFrame.$x(jobLookUpCriteria);
            for (let urlElement of urlElements) {
                let crawledUrl = await childFrame.evaluate((el) => el.href, urlElement);
                crawledUrls.push(crawledUrl);
            }
        }
    }
    return crawledUrls;
}

function compareArraysInclude(array1, array2) {
    if (
        array1.every((value, index) => array2.includes(value))
    ) {
        return true;
    }
    return false;
}
```

### Error string

no error

### Puppeteer configuration
No response

### Puppeteer version

19.7.0

### Node version

v16.19.0 

### Package manager

npm

### Package manager version

8.19.3

### Operating system

macOS

**Comment by dwillisgh** [comment]
Can I get more information on why the bug needs more feedback?

**Comment by OrKoN** [comment]
@dwillisgh the automatic analyser was not able to run https://github.com/puppeteer/puppeteer/actions/runs/4184679853/jobs/7250702120

Can you please provide a **minimal** reproduction? we want be able to debug such a long script for you. Thanks.

**Comment by dwillisgh** [comment]
I shrunk it down more and added some comments.

**Comment by OrKoN** [comment]
@dwillisgh do you dispose element handles? If you don't call `.dispose()` on the element handles they might cause the memory to retained and it looks like it fails with out of memory errors.

**Comment by dwillisgh** [comment]
I didnt know that was a thing :-) Thank you

**Comment by dwillisgh** [comment]
I updated the example with the dispose in case it helps someone else

**Comment by ochiribogaz** [comment]
Hi. I have a similar issue. Sometimes I'm getting "Aw, Snap! Something went wrong while displaying this webpage. Error code: 11". I'll try using the dispose function, as my code is getting stucked when i get this error.

**Comment by ochiribogaz** [comment]
> Hi. I have a similar issue. Sometimes I'm getting "Aw, Snap! Something went wrong while displaying this webpage. Error code: 11". I'll try using the dispose function, as my code is getting stucked when i get this error.

However, I would like to know if there is away throw an error or set a timeout when this happens.
