### ISSUE TITLE
[Bug]: Sometimes the function page. Waitforxpath() does not detect the DOM that already exists

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9682]
### Bug expectation

Sometimes the function page. Waitforxpath() does not detect the DOM that already exists
https://github.com/puppeteer/puppeteer/issues/4072
I have the problem in the latest puppeteer version 19.6.3.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
our own demo..
```

### Error string

TimeoutError: Waiting for selector `.//div[@style='visibility: visible;']//*[contains(@class,'tui-dropdown')]//*[text()='全局替换']` failed: Waiting  failed: 3000ms exceeded

### Puppeteer version

19.6.3

### Node version

16.19.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by FishBlanche** [comment]
This problem does not exist in version 5.4.1(which i currently use).
But because this problem https://bugs.chromium.org/p/chromium/issues/detail?id=1412653#makechanges,
i need to use latest chromium.
Is there any possibility that without upgrading puppeteer but using the latest chromium?

**Comment by OrKoN** [comment]
Please provide a minimal reproducing example demonstrating the bug: a sample test page and a sample puppeteer script. Otherwise, we cannot help you with this.

**Comment by FishBlanche** [comment]
> 



> 

Could it be possible that i demonstrate it in my computer?  
If it's possible,when will u be available？

**Comment by FishBlanche** [comment]
I wonder what's the differences between run browser in top view and not run browser in top view?
My case succeeds when i watch it runs but failed when i don't watch it run....quite strange.
This video recorded that after i launched the test,I just leave the browser backend.The case failed because :
const elXpath =  await this.pageDriver.page.waitForXPath(selectorOrTimeout, options);
![waitfor_failed](https://user-images.githubusercontent.com/19261291/219545691-93a1caca-a224-490f-8aef-6212adcf8d11.png)

https://user-images.githubusercontent.com/19261291/219544385-65d9a0f7-84dd-4d70-81f1-280089e53788.mp4

This video recorded that after i launched the test,I watched it run.The case succeeds.
https://user-images.githubusercontent.com/19261291/219544517-bda2b47a-cb2f-4378-8143-eaa232968b23.mp4

**Comment by OrKoN** [comment]
the browser in headful mode can do all sorts of optimizations if the window is closed and tab is no active. Could you try if it works in headless? Also, try calling `page.bringToFront()` before doing actions on the page.

**Comment by OrKoN** [comment]
Can you try/catch the timeout error and print out the web page DOM structure to see if the element is actually there?

**Comment by FishBlanche** [comment]
> 

It works ok in headless mode.
Also it works in headful mode in version 5.4.1(which i currently use).
But in higher version (19.6.3),it has problem

**Comment by MaciekLeks** [comment]
This error is not a rare thing using proxy:
```
        TimeoutError: waiting for XPath `//h2[text()[contains(.,'Podsumowanie')]] | //h1[. ='Podsumowanie'] | //div[@class[contains(.,'oneContent active')]]//h1/*[text()='Podsumowanie'] | //h2/span[text()='Podsumowanie'] | //*[@data-tab and @title='Podsumowanie'] | //c-lwc-fns-consumption-summary-wrapper//*[text()='Podsumowanie']` failed: timeout 30000ms exceeded
            at new WaitTask (/pickle/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:636:34)
            at DOMWorld.waitForXPath (/pickle/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:547:26)
            at Frame.waitForXPath (/pickle/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1005:51)
            at Page.waitForXPath (/pickle/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2272:33)
            at getElement (/pickle/features/support/actions.js:18:26)
            at World.seeElement (/pickle/features/support/actions.js:344:9)
            at World.<anonymous> (/pickle/features/step-definitions/generic.js:117:20)
```

The error comes from cucumber and it devastes our tests :(
