### ISSUE TITLE
[Bug]: Error: Cannot find module 'puppeteer-core/internal/puppeteer-core.js'

### ISSUE THREAD

**Issue by mondersky** [puppeteer/puppeteer#9689]
### Bug expectation

on linux server, when I run
`node /home/userx/public_html/myscript.js`
all work fine. but as soon as I try run this as a cron job I get the error  Cannot find module 'puppeteer-core/internal/puppeteer-core.js'
it looks like a relative path issue however all my other node modules load fine when I remove any puppeteer related code.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
```

### Error string

 Cannot find module 'puppeteer-core/internal/puppeteer-core.js'

### Puppeteer version

19.7.1

### Node version

18.14.0

### Package manager

npm

### Package manager version

9.3.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Does the following help https://pptr.dev/troubleshooting#cannot-find-module-puppeteer-coreinternal ?

**Comment by mondersky** [comment]
no unfortunately. the link suggest to update node while my node version is 18.14.0

**Comment by OrKoN** [comment]
@mondersky are you using jest or babel?

**Comment by OrKoN** [comment]
How do you install node? it looks like it does not work only in cron so I would assume that node version used by cron might be different. Could you confirm the version that cron launches by outputting the node version to a log file?

**Comment by mondersky** [comment]
Thank you, in fact I did as you said and found out that cron uses an old version of node
I changed the cron command to 
`*/1 * * * * /root/.nvm/versions/node/v18.14.0/bin/node /home/userx/public_html/myscript.js`
and it's working fine now
