### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mondersky** [puppeteer/puppeteer#9690]
### Bug expectation

on linux server, when I run
node /home/userx/public_html/myscript.js
all work fine. but as soon as I try run this as a cron job I get the error Cannot find module 'puppeteer-core/internal/puppeteer-core.js'
it looks like a relative path issue however all my other node modules load fine when I remove any puppeteer related code.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
```

### Error string

Cannot find module 'puppeteer-core/internal/puppeteer-core.js'

### Puppeteer version

19.7.1

### Node version

v18.14.0

### Package manager

npm

### Package manager version

9.3.1

### Operating system

Linux

**Comment by OrKoN** [comment]
Does the following help https://pptr.dev/troubleshooting#cannot-find-module-puppeteer-coreinternal ?
