### ISSUE TITLE
[Bug]: App mode is not showing page title correctly, only url

### ISSUE THREAD

**Issue by luiscuriel** [puppeteer/puppeteer#9691]
### Bug expectation

I expected the window title to be the page title when on --app mode

but I am getting the url

It worked a couple of days ago.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
args: ['--app=https://web.whatsapp.com/']
```

### Error string

no error

### Puppeteer version

1

### Node version

16.0.0

### Package manager

npm

### Package manager version

1

### Operating system

Windows

**Comment by OrKoN** [comment]
Thanks for the report but it is outside of the Puppeteer scope. Could you file a issue with crbug.com that some of the Chromium's custom argument does not work as expected?

**Comment by luiscuriel** [comment]
Thanks a lot for answering my report. I will do as you suggest. Cheers!
