### ISSUE TITLE
[Bug]: Optional peer dependency "typescript >= 4.7.4" breaks pnpm users

### ISSUE THREAD

**Issue by mikeharder** [puppeteer/puppeteer#9698]
### Bug expectation

An optional peer dependency `typescript >= 4.7.4` was added in #9618:

https://github.com/puppeteer/puppeteer/blob/256856ed3a30c64ad259136368ca8cf539d85c43/packages/puppeteer-core/package.json#L178-L184

This is a breaking change for repos using `pnpm` with older versions of `typescript`:

```
$ npm install -g pnpm@7.27.0

$ pnpm config set strict-peer-dependencies true

$ pnpm install puppeteer-core@19.7.1 typescript@4.7.3
 WARN  Issues with peer dependencies found
.
└─┬ puppeteer-core 19.7.1
  └── ✕ unmet peer typescript@">= 4.7.4": found 4.7.3
  
$ pnpm upgrade
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
.
└─┬ puppeteer-core 19.7.1
  └── ✕ unmet peer typescript@">= 4.7.4": found 4.7.3
```

Even if a peer dependency is optional, `pnpm` fails with an error if `strict-peer-dependencies=true` and the versions do not match.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
$ npm install -g pnpm@7.27.0

$ pnpm config set strict-peer-dependencies true

$ pnpm install puppeteer-core@19.7.1 typescript@4.7.3
 WARN  Issues with peer dependencies found
.
└─┬ puppeteer-core 19.7.1
  └── ✕ unmet peer typescript@">= 4.7.4": found 4.7.3
  
$ pnpm upgrade
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
.
└─┬ puppeteer-core 19.7.1
  └── ✕ unmet peer typescript@">= 4.7.4": found 4.7.3
```

### Error string

ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

### Puppeteer version

19.7.1

### Node version

18.14.0

### Package manager

pnpm

### Package manager version

7.27.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Thanks for the report. We don't guarantee/test Puppeteer with older TypeScript versions and other users reported that it might not work (https://github.com/puppeteer/puppeteer/issues/9582) requesting that we define the TypeScript version we need more strictly. It looks like the workaround is to upgrade TypeScript or to disable strict dependencies in pnpm.
