### ISSUE TITLE
await browser.close() occasionally hanging for 10 minutes+

### ISSUE THREAD

**Issue by jamesmartinduffy** [puppeteer/puppeteer#970]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0
* Platform / OS version: macOS Sierra 10.12.6

**What steps will reproduce the problem?**

My code is complicated and the error only happens occasionally, so I've been working on condensing it down into a minimal script that will reliably reproduce the issue. I'll update this thread with that code when I have it narrowed down, but for now I'll just describe the issue here in case someone has any ideas what may be happening.

Basically I'm doing some web-scraping, which involves running hundreds of sessions using bluebird's `Promise.map` with concurrency. 

Each session creates a new `browser` with `puppeteer.launch()` (until #85 is implemented, I need to launch a separate browser for each session to keep cookies & session data separate). The session then performs some navigations across a couple pages, collects some data, and exits the session with `await browser.close()`.

The issue is, in one in every 50 sessions or so, `await browser.close()` seems to hang... I thought it was indefinitely, but I just let the script continue running once and it seems to have resolved after almost 20 minutes. Because my script is using `Promise.map()`, it waits for all sessions to finish, so the entire script hangs if one browser doesn't exit properly.

I'm put a log function with a timestamp before and after `await browser.close()` to better understand what's happening:

```
    log.info(`user${this.index}:`, "Exiting...")
    await this.browser.close()
    log.verbose(`user${this.index}:`, "Browser closed")
```

Running the script with `DEBUG=*,-puppeteer:protocol,-puppeteer:session,-puppeteer:mouse node test.js` to get some extra debug info, I can see the following in the console:

**What is the expected result?**

On most sessions, this is what happens:

```
03:23:44.63 - info: user49: Exiting...
  puppeteer:browser browser.close() +889ms
03:23:44.68 - verbose: user49: Browser closed
```

`browser.close()` takes a fraction of a second to return.

**What happens instead?**

On the problematic session, I get the following:

```
03:23:41.70 - info: user47: Exiting...
  puppeteer:browser browser.close() +939ms
// a bunch of logs from other sessions, massive delay where the script seems to hang indefinitely, then finally:
03:41:07.41 - verbose: user47: Browser closed
```

As you can see from the timestamps, in this case it took almost 20 minutes to return. But I've run this multiple times, and there are no other DEBUG outputs after `puppeteer:browser browser.close()` from that session — so I have no idea what it's doing during that time. 

Opening Mac's Activity Monitor also shows no instances of Chromium running, so it has successfully closed the browser. I'm not sure why the promise doesn't resolve.

Any hunches? I'll continue my debugging, and update this issue with a script when I have one that is able to isolate and replicate the problem.

**Comment by jamesmartinduffy** [comment]
Just had one hang for a couple hours.

But after doing some more split testing, this seems to only happen in headful mode (`headless: false`). 

Doing a `ps aux | grep chromium` while the script is hanging, I see the following in the list:

```
duffx            67851   0.0  0.0  2509544   2212   ??  S    12:59AM   0:00.03 /Users/duffx/test/node_modules/puppeteer/.local-chromium/mac-499413/chrome-mac/Chromium.app/Contents/Versions/63.0.3205.0/Chromium Framework.framework/Helpers/crashpad_handler --monitor-self --monitor-self-annotation=ptype=crashpad-handler --database=/Users/duffx/Library/Application Support/Chromium/Crashpad --metrics-dir=/Users/duffx/Library/Application Support/Chromium --annotation=plat=OS X --annotation=prod=Chromium_Mac --annotation=ver=63.0.3205.0 --handshake-fd=8
```

So I think the issue is possibly caused by a crash reporting tool when Chrome is in headful mode?

Anyway, I've switched my script back to `headless: true` and haven't run into the issue again. (I only switched to `headless: false` while I was building my script to see what was happening on the page).

Since I have this working for my use case, I'm going to stop trying to isolate the issue into a minimal script that reproduces it. So you can go ahead and close this issue if you'd like, unless someone else wants to look into it.

**Comment by ebidel** [comment]
Thanks for reporting @jamesmartinduffy. 

I think your diagnosis makes sense. IIRC, headless turns off reporting  by default and Puppeteer also [disables](https://github.com/GoogleChrome/puppeteer/blob/c225b93037c7948607f5bb9b414149c50f0d19e1/lib/Launcher.js#L30) some of that plumbing.

**Comment by squarism** [comment]
Would adding `--disable-crash-reporter` keep `headless: false` while debugging from spinning up a bunch of zombie processes?  My load went nuts and I realized I had 140 chromium instances in the background.  I have no idea where they came from but individual runs don't cause a pid to stick around.  I wonder if it happens while debugging or doing breakpoints.

**Comment by Mehuge** [comment]
I am using puppeteer in head mode and hitting this issue.  Two process exist while its hung both `crashpad_handler`.  I added `--disable-breakpad` command line switch and it seems to have solved the problem.

**Comment by Mehuge** [comment]
I am hitting this issue in `headless: false` mode, and adding `--disable-crash-reporter` and/or `--disable-breakpad` doesn't solve it.

**Comment by brdacost** [comment]
I am currently having the same issue even running in headless: true mode.... Any advices?

**Comment by qkxie** [comment]
same issue. running in headless: false

**Comment by iamkhalidbashir** [comment]
any fixes?
