### ISSUE TITLE
[Bug]: headless mode Error: net::ERR_INVALID_URL at chrome://system

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9707]
### Bug expectation

i launched puppeteer in headless mode and wanna goto chrome://system.
 Error: net::ERR_INVALID_URL at chrome://system
Same with chrome://version

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
    headless: true,
    defaultViewport: { width: 1200, height: 800 },
    args: [ 
      '--start-maximized',
      // '--start-fullscreen',
      '--enable-precise-memory-info',
      '--no-sandbox',
      ]
  })
  const page = await browser.newPage()
  await page.goto('chrome://system')
  await page.screenshot({ path: 'sys.png' })
```

### Error string

Error: net::ERR_INVALID_URL at chrome://system

### Puppeteer version

19.6.3

### Node version

16.19.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by OrKoN** [comment]
Hey, thanks for the report but it is outside of Puppeteer's scope. Would you file a report for the headless chromium at crbug.com? I am not sure if it is a bug though as it might be done for security reasons in the headless mode that is often used for automation.

**Comment by FishBlanche** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1417533
