### ISSUE TITLE
/home/vcap/app/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory[Bug]: 

### ISSUE THREAD

**Issue by rajeshpotturu** [puppeteer/puppeteer#9718]
### Bug expectation

We are trying to deploy Node.js application in Cloud Foundary(PCF) but getting an error No directory found.

### Bug behavior

- [X] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.setContent(decodeContent);
            const pdf = await page.pdf({
                margin: { top: '10px', right: '50px', bottom: '100px', left: '50px' },
                printBackground: true,
                format: 'A4',
                displayHeaderFooter: true,
                footerTemplate:"<div style=\"text-align: right;width: 297mm;font-size: 8px;\"><span style=\"margin-right: 1cm\"><span class=\"pageNumber\"></span> of <span class=\"totalPages\"></span></span></div>"
              });
```

### Error string

Failed to launch the browser process!\n' + 2023-02-21T15:42:27.054+05:30 [APP/PROC/WEB/0] [OUT] '/home/vcap/app/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

### Puppeteer configuration

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

19.7.0

### Node version

16.15.1

### Package manager

npm

### Package manager version

8.11.0

### Operating system

Linux

**Comment by rajeshpotturu** [comment]
Node version : 18.13.0
Npm version : 8.19.3

**Comment by OrKoN** [comment]
Thanks for the report. libnss3 is required to run Chromium. Please install it on your system.

**Comment by OrKoN** [comment]
Then I am afraid you need a different hosting provider that allows running custom Docker images or installing custom libs in another way, or ships with all libs required by Chromium by default. We currently don't have statically linked binaries and it is not likely that the Chromium project will provide those any time soon.

**Comment by rajeshpotturu** [comment]
> Then I am afraid you need a different hosting provider that allows running custom Docker images or installing custom libs in another way, or ships with all libs required by Chromium by default. We currently don't have statically linked binaries and it is not likely that the Chromium project will provide those any time soon.

we are pushing application directly into PCF using manifest file.
applications:
- name: app-name
  memory: 2072M
  disk_quota: 2072M
  instances: 1
  env:
    SERVICE_ENVIRONMENT: dev
  buildpacks:
    - https://github.com/cloudfoundry/nodejs-buildpack
  routes:
    - route: b2c-p2o-pdf-generator.apps.np.sdppcf.com
  command: node server.js
  health-check-type: process

**Comment by rajeshpotturu** [comment]
> Thanks for the report. libnss3 is required to run Chromium. Please install it on your system.

Thanks for Replay. I have upgraded to 19.7.2 but error still coming.

**Comment by rajeshpotturu** [comment]
> This issue has an outdated Puppeteer version: `19.7.0`. Please verify your issue on the latest `19.7.2` version. Then update the form accordingly.
> 
> [Analyzer run](https://github.com/puppeteer/puppeteer/actions/runs/4231771762)

Thanks for Replay. I have upgraded to 19.7.2 but error still coming.
