### ISSUE TITLE
Security: prevent navigations to file://

### ISSUE THREAD

**Issue by ebidel** [puppeteer/puppeteer#972]
From https://github.com/ebidel/try-puppeteer/issues/6.

Should pptr prevent navigations to URLs other than`https?:` or `about:`?

This would be similar to using web platform apis in chrome. Users need `--allow-file-access-from-files` to be able to navigate to (or read content from) `file:///` urls. In pptr, they could reenable access by passing that flags in `args`.

**Comment by hparadiz** [comment]
To be honest I don't think it's very prudent to surface systems like this on the public internet where anyone can run code without a great deal of penetration testing.

The approach outlined makes sense but there are other internal chrome-only pages which might be useful. What about all of the links listed in `chrome://about/`?

**Comment by ebidel** [comment]
`about:` is an alias for `chrome:`. I'd imagine we'd be ok with any of those pages. Then again, other than `about:blank`, I can't think of a use case for needing any of the others.

**Comment by JoelEinbinder** [comment]
I don't think the try-puppeteer is a use case we should support. It isn't safe to run arbitrary puppeteer code on your computer.

**Comment by aslushnikov** [comment]
Navigating to file urls comes handy in a few scenarios; one example is a cli tool to render SVGs to PNGs.

Regarding the issue, i think the right solution would be to run chrome under the user that can't read any of the host files.

**Comment by ebidel** [comment]
Wouldn't `page.setContent()` be more appropriate for those cases? IOW, why does navigation need to come into play?

**Comment by ebidel** [comment]
try-puppeteer is not something we should support. Just a specific example where this shows up. 

That said, how would you run chrome as a specific user? The [Dockerfile](https://github.com/ebidel/try-puppeteer/blob/master/backend/Dockerfile#L52) defines a user with limited permissions but Chrome is still able to navigate to file like `/etc/hosts` and render it.

<img width="1284" alt="screen shot 2017-10-06 at 3 14 24 pm" src="https://user-images.githubusercontent.com/238208/31300612-78036000-aaa9-11e7-93bb-fee5515009e9.png">

**Comment by aslushnikov** [comment]
@ebidel ah, right. The `/etc/hosts` is world-readable by default - it looks like it's harmless to read. You can change this with `chmod` if there's a need to.
