### ISSUE TITLE
[Bug]: Polyfill errors when using Angular CLI 15.1.5, Node: 16.16.0 and TypeScript.

### ISSUE THREAD

**Issue by Erik-Peet** [puppeteer/puppeteer#9720]
### Bug expectation

I am using MacOS Ventura 13.1.

Installing puppeteer works just fine via "npm install puppeteer".
I start the app via "ng serve" in Terminal.
I can import it via import "puppeteer from 'puppeteer';", nothing happens yet.

Then when I add the following code

`(async () => {
     puppeteer.launch();
    })`
    
   I get the following errors in my Terminal:
   
   `./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserFetcher.js:34:0-25 - Error: Module not found: Error: Can't resolve 'os' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserFetcher.js:35:0-29 - Error: Module not found: Error: Can't resolve 'path' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserFetcher.js:36:0-27 - Error: Module not found: Error: Can't resolve 'url' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserFetcher.js:37:0-29 - Error: Module not found: Error: Can't resolve 'util' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:29:0-46 - Error: Module not found: Error: Can't resolve 'child_process' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:30:0-25 - Error: Module not found: Error: Can't resolve 'fs' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:31:0-29 - Error: Module not found: Error: Can't resolve 'path' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:32:0-37 - Error: Module not found: Error: Can't resolve 'readline' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

./node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:33:0-33 - Error: Module not found: Error: Can't resolve 'util' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:8:0-32 - Error: Module not found: Error: Can't resolve 'fs' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:9:0-38 - Error: Module not found: Error: Can't resolve 'fs/promises' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:10:0-20 - Error: Module not found: Error: Can't resolve 'os' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:11:0-24 - Error: Module not found: Error: Can't resolve 'path' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/FirefoxLauncher.js:2:0-20 - Error: Module not found: Error: Can't resolve 'fs' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

./node_modules/puppeteer-core/lib/esm/puppeteer/node/FirefoxLauncher.js:3:0-20 - Error: Module not found: Error: Can't resolve 'os' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/FirefoxLauncher.js:4:0-24 - Error: Module not found: Error: Can't resolve 'path' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:28:0-32 - Error: Module not found: Error: Can't resolve 'fs' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

./node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:29:0-32 - Error: Module not found: Error: Can't resolve 'os' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:30:0-28 - Error: Module not found: Error: Can't resolve 'path' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

./node_modules/puppeteer-core/lib/esm/puppeteer/node/PuppeteerNode.js:28:0-28 - Error: Module not found: Error: Can't resolve 'path' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer-core/lib/esm/puppeteer/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

./node_modules/puppeteer/lib/esm/puppeteer/getConfiguration.js:1:0-29 - Error: Module not found: Error: Can't resolve 'os' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer/lib/esm/puppeteer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }

./node_modules/puppeteer/lib/esm/puppeteer/getConfiguration.js:2:0-28 - Error: Module not found: Error: Can't resolve 'path' in '/Users/erikpeeters/Git/compare-site/node_modules/puppeteer/lib/esm/puppeteer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }`

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
    await puppeteer.launch();
})
```

### Error string

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.

### Puppeteer version

19.7.2

### Node version

16.16.0

### Package manager

npm

### Package manager version

9.2.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Thanks for the report. From the error message, it looks like you need configure proper polyfills for your webpack version. Also, if you want to run Puppeteer in the Browser you probably don't need to include the node subfolder into the webpack.
