### ISSUE TITLE
[Bug]: Console windows opening with error written inside while headless browser is open

### ISSUE THREAD

**Issue by DNAScanner** [puppeteer/puppeteer#9726]
### Bug expectation

I expected, that when i set "headless" to "true", i wont be seeing any windows opening / closing except for those that were there before starting the browser. What is actually happing right now, is that a few (4) chromium console-styled windows open when launching the browser, and when the browser is closed (`browser.close()`), those windows are gone again.

Here is a short video:
https://cdn.discordapp.com/attachments/1008876585107066940/1077757065881206924/2023-02-22_01-47-33.mp4

This is the text visible in the windows:
[0222/015709.056:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
      const browser = puppeteer.launch({
            headless: true,
            args: ["--no-sandbox", "--disable-setuid-sandbox"],
      });
})();
```

### Error string

no error

### Puppeteer version

19.7.2

### Node version

v18.14.0

### Package manager

npm

### Package manager version

8.6.0

### Operating system

Windows

**Comment by OrKoN** [comment]
headless=true is for the browser itself. Here it looks like Windows creates a window for every started browser process (presumably to show stdout). Which Windows version is that? Is there an option to configure this behaviour on Windows? The browser processes are launched via https://nodejs.org/api/child_process.html#child_processspawncommand-args-options so Puppeteer does not do anything extra here.

**Comment by OrKoN** [comment]
There is one difference though for a 32bit windows. Is it a 32bit version?

**Comment by DNAScanner** [comment]
Im currently on Windows 11 22H2 22621.1265 64bit. Nodejs is also running in 64bit. As far as i know, there is no option to configure that behaviour

**Comment by jrandolf** [comment]
This is an upstream bug. The fix will come out around M112.

**Comment by DNAScanner** [comment]
Do i just have to wait til theres a new update then?

**Comment by jrandolf** [comment]
Yes.

**Comment by DNAScanner** [comment]
Ok, thank you very much

**Comment by Zepeng-Zheng** [comment]
Lowering the puppeteer version to v18.2.1 solves the problem.
`yarn remove puppeteer`
`yarn add puppeteer@v18.2.1`
