### ISSUE TITLE
[Bug]: Firebase / Puppeteer Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1095492 is guaranteed to work

### ISSUE THREAD

**Issue by Anthony2539** [puppeteer/puppeteer#9745]
### Bug expectation

Hello, I'am using Puppeteer in Firebase Cloud Function and i have this error when method **launch** is called :

"Exception from a finished function: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1095492 is guaranteed to work."

It's work in Windows local...

Thx for help :)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';
import * as functions from "firebase-functions";

exports.scheduledFunction = functions.pubsub.schedule('* * * * *').onRun((context) => {
  (async () => {
    const browser = await puppeteer.launch({args: ['--no-sandbox'],headless: true});
    const page = await browser.newPage();
  
    await page.goto('https://developer.chrome.com/');
  
    await browser.close();
  })();
});
```

### Error string

Only Chrome at revision r1095492 is guaranteed to work

### Puppeteer configuration

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

### Puppeteer version

19.7.2

### Node version

18.12.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Linux

**Comment by mlahp7** [comment]
I had the same issue a while back. The newer major of Puppeteer doesn't seem to work with google cloud functions anymore. 
It looks like the puppeteer team has updated their troubleshooting docs, https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-google-cloud-functions

They suggest setting up with Cloud Run if you are having trouble in cloud functions.

Alternatively, I was able to get my case working by downgrading to puppeteer version 18.2.1

good luck!

**Comment by Anthony2539** [comment]
@mlahp7 i tried with version puppeteer 18.2.1 but i have this error: 

`Exception from a finished function: Error: Failed to launch the browser process!`

`/workspace/node_modules/puppeteer-core/.local-chromium/linux-1045629/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

**Comment by mlahp7** [comment]
> 

Maybe it's your node runtime. Can you try changing your nodejs runtime to Node 16 instead of 18?

**Comment by Anthony2539** [comment]
@mlahp7 unfortunatelly with Node 16

`Exception from a finished function: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1045629 is guaranteed to work.`

**Comment by mlahp7** [comment]
> @mlahp7 unfortunatelly with Node 16
> 
> `Exception from a finished function: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1045629 is guaranteed to work.`
> 
> ![image](https://user-images.githubusercontent.com/5879052/221255672-ac11aa36-6fff-40e3-9c5a-df737311a5a1.png)


Odd, my package.json is very similar, minus the postinstall line. 

The only other things that you could confirm:
- Check in https://console.cloud.google.com/functions/list and confirm that your function is actually on runtime of Node 16
- Confirm that the package-lock has the correct version of puppeteer 
- (Nuclear option) remove your node_modules and package-lock and try for a reinstall

If you're still having trouble, setting up something with Cloud Run might be an option

**Comment by Anthony2539** [comment]
@mlahp7 i removed my node_modules and package-lock and i reinstalled all
this is my package-lock: 
![image](https://user-images.githubusercontent.com/5879052/221354456-2c19aec4-1df0-46e5-a27f-c11026922f43.png)

The function deployed on Node 16
![image](https://user-images.githubusercontent.com/5879052/221354504-4833445e-394f-4a61-a070-28edde8db2ff.png)

but i have always this error in my Google Cloud Function Scheduler :(

![image](https://user-images.githubusercontent.com/5879052/221354585-683d52d8-8796-4a3d-a84f-5e6ea4a4e05f.png)

`Exception from a finished function: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r1045629 is guaranteed to work.`

should i try with another version of puppeteer ?

**Comment by OrKoN** [comment]
Yeah, libnss3 is required by chromium and it is apparently missing in the latest cloud function runtimes. Consider filing a request for this runtime with Cloud or try using Cloud Run which allows specifying additional dependencies via a Dockerfile.

**Comment by Jbz797** [comment]
Some news about this issue ?

**Comment by humanismusic** [comment]
It looks like libnss3.so has been added to Node 18: [Add libnss3.so to Node 18 runtime so that Puppeteer can work. 
](https://issuetracker.google.com/issues/266279679?pli=1)

**Comment by itismejy** [comment]
any fixes?
