### ISSUE TITLE
Table is being cut off upon page break, and continues onto the next page

### ISSUE THREAD

**Issue by agiri1991** [puppeteer/puppeteer#9764]
**Bug description**

**Steps to reproduce the problem:**

I have some html code as shown below (including the node js used to invoke puppeteer), and then I'm running that through puppeteer which generates the issue shown in the screen shot below; whereby the table is cut off between the pages. I have attempted a lot of the standard css solutions found across the internet, using 'page-break-inside: avoid;' on the rows/table/tds etc. None of it has worked.

My goal is for the table to have a line at the bottom to 'complete' it on page break, and then have a line drawn at the top of the second page it spills onto, so it does not look as if its been cut off. Is this currently possible with puppeteer, I found a similar issue raised here in 2022 however it seems to have been closed: https://github.com/puppeteer/puppeteer/issues/8708? 

Any help appreciated, cheers

**_HTML used to produce the pdf:_**

<img width="984" alt="Screenshot 2023-03-02 at 17 22 25" src="https://user-images.githubusercontent.com/126806705/222504486-5f99a817-f001-4608-a002-6725ba4cbfa1.png">

**_node js code invoking puppeteer_**

<img width="747" alt="Screenshot 2023-03-02 at 17 21 06" src="https://user-images.githubusercontent.com/126806705/222504134-7ad086b6-c525-4060-90b9-fb938b18f4f0.png">

Screen shot: 
<img width="2554" alt="Screenshot 2023-03-02 at 17 07 22" src="https://user-images.githubusercontent.com/126806705/222501404-ba27e801-ce98-4251-9762-83c7f8605fb3.png">

Puppeteer version
^10.1.0

Node.js version
nodejs14.x

What operating system are you seeing the problem on?
macOS, using chrome to download the pdf.

**Comment by Lightning00Blade** [comment]
Hey, can you observe the same issue when you try to create PDF though Chrome itself? As Puppeteer just calls the same browser method. Also it seems you are using an older version of Puppeteer. Updating to the latest will make Puppeteer download a newer browser for it to use.

I would appreciate if you can provide the Raw HTML. 

Note: Using code blocks for text makes it easier for us to review - [Quoting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by agiri1991** [comment]
Hello, thanks for replying.

I will upgrade my puppeteer version and post the results here - please keep this issue open for now as I'm currently tied up with other things but I will get back eventually. 

thanks.

**Comment by casperski07** [comment]
Hi @agiri1991  are you able to solve this issue? i encountered this with my current project and i can't seem to find a fix for it . hoping for your response . Thank you
