### ISSUE TITLE
[Bug]: ReferenceError: cov_2os11p00jv is not defined 

### ISSUE THREAD

**Issue by eugene0928** [puppeteer/puppeteer#9771]
### Bug expectation

I have written e2e tests and run them. All test cases are passed. 

But, when I try to get coverage report via gulp [ gulp coverage ], I got an error and server returns 500 status code instead of 200

### Bug behavior

- [ x ] Flaky
- [ ] PDF

### Minimal, reproducible example

```JavaScript
import puppeteer from 'puppeteer';

const username = 'xxxx';
const passwd = 'xxxx';

const browser = await puppeteer.launch({
      headless: false,
      defaultViewport: false,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
    });

const page = await browser.newPage();
await page.goto('https://my.example.com/'); // just for show case

await page.$eval('#AccountUsername',(el, val) => el.value = val, username); // error comes from here
await page.$eval('#AccountPassword',(el, val) => el.value = val, passwd);
await page.click('input[type=image]');
```

### Error string

Error: Evaluation failed: ReferenceError: cov_2os11p00jv is not defined     at pptr://__puppeteer_evaluation_script__:1:16

### Puppeteer version

19.7.2

### Node version

18.14.0

### Package manager

npm

### Package manager version

9.3.1

### Operating system

Linux

**Comment by jrandolf** [comment]
Without a proper example, we cannot determine the reason for error. Could you create a MVCE in a repo and comment a link here?

**Comment by eugene0928** [comment]
@jrandolf I could not create a repo for this and I did not get what MVCE is
