### ISSUE TITLE
[Bug]: xpath prefix is not evaluated relative to the elementHandle

### ISSUE THREAD

**Issue by jespertheend** [puppeteer/puppeteer#9772]
### Bug expectation

The documentation states in several places that:

> The method evaluates the XPath expression relative to the elementHandle. If `xpath` starts with `//` instead of `.//`, the dot will be appended automatically.

However, when I ran `elementHandle.$$("xpath///div")` I received all divs on the page.

Similarly, `elementHandle.$("xpath///div")` gave me the first div on the page.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
	const browser = await puppeteer.launch({
		headless: false,
		devtools: true,
	});
	const page = await browser.newPage();
	await page.goto("https://example.com");

	function logEl(el) {
		console.log(el);
		page.evaluate(el => {
			console.log(el);
		}, el);
	}

	const firstP = await page.$("p");
	logEl(firstP);

	const a1 = await firstP.$("a");
	logEl(a1);

	const a2 = await firstP.$("xpath///a");
	logEl(a2);
	if (a2) {
		throw new Error("Expected a to not be found")
	}
})()


// After running, check the console, a1 is null as expected, a2 is not
```

### Error string

Expected a to not be found

### Puppeteer version

19.7.2

### Node version

18.5.0

### Package manager

npm

### Package manager version

8.12.1

### Operating system

macOS

**Comment by jespertheend** [comment]
Note that adding the dot manually is a good workaround:
```
elementHandle.$("xpath/.//a");
```
So simply updating the documentation might also be a good fix.

**Comment by jrandolf** [comment]
Thanks for the issue. The documentation you pointed at was for `$x` not `$$`, however your assumption that the assumptions that apply to `$x` should transfer sounds reasonable.

We won't be changing behavior since the expected behavior of `//` is correct. You can just not use `//` and your example will work!

**Comment by ImTemporaryHere** [comment]
thank  u for pointig that xpath for child element should have   . before and be like .//
