### ISSUE TITLE
Switching to New Tab?

### ISSUE THREAD

**Issue by floydtagle** [puppeteer/puppeteer#978]
Is there a way to switch to a new Tab and go back to the current tab? It seems I cannot find a way to handle multiple  page/tab on one browser using puppeteer. Thanks

**Comment by vsemozhetbyt** [comment]
There may be soon: https://github.com/GoogleChrome/puppeteer/pull/554

**Comment by floydtagle** [comment]
@vsemozhetbyt I see.. Thanks a lot.

**Comment by aslushnikov** [comment]
Dupe of #386
