### ISSUE TITLE
[Docs]: Document the recent Angular @puppeteer/ng-schematics

### ISSUE THREAD

**Issue by jecfish** [puppeteer/puppeteer#9793]
Missing docs. This feature did not get documented and mention anywhere. Developers should know about this goodies!

Idea on documentation:

- Add a `Recipe` section similar to `Guides`, then add a page under it with title `Using Puppeteer with Frameworks`.
- In the page mention `Angular` then explain  `ng add @puppeteer/ng-schematics`

**Comment by jecfish** [comment]
@Lightning00Blade happy to review if you draft that.

**Comment by Lightning00Blade** [comment]
Closing as complete by #10768 and docs are on the website in the suggested format.
