### ISSUE TITLE
[Feature]: Puppeteer Schematics on bootstrap `ng e2e`

### ISSUE THREAD

**Issue by jecfish** [puppeteer/puppeteer#9794]
### Feature description

Refer to the screenshot below. At the moment, when I run `ng e2e` on a new Angular repo `v15.2`. It doesn't show Puppeteer as an option. Can we add that in?

This is a good way to surface our integration to developers.

<img width="937" alt="Screenshot 2023-03-07 at 9 55 01 AM" src="https://user-images.githubusercontent.com/5917927/223377660-7b49d5dc-f451-401f-84a5-9bb6da41a507.png">

**Comment by jecfish** [comment]
@Lightning00Blade FYI

**Comment by Lightning00Blade** [comment]
Closed with https://github.com/angular/angular-cli/pull/25690
