### ISSUE TITLE
Document cookie.session property

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#980]
[`page#cookies`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagecookiesurls) returns array of objects representing cookies. The cookie object contains a boolean `session` property, e.g.

```js
{
  name: 'ASP.NET_SessionId',
  value: 'rejdisgd32padetl1kmblpn3',
  domain: '.myvue.com',
  path: '/',
  expires: 0,
  size: 41,
  httpOnly: true,
  secure: false,
  session: true
}

```

The purpose of the `session` property is unclear. The property is not documented in the Puppeteer API.

* https://stackoverflow.com/questions/46100100/how-to-pass-session-cookies-from-one-tab-to-another-in-headless-chrome
* https://stackoverflow.com/questions/46631333/how-to-recreate-a-page-with-all-of-the-cookies

Furthermore, whenever `session=true`, expires is `0`.

**Comment by aslushnikov** [comment]
@JoelEinbinder, could you please take a look?
