### ISSUE TITLE
[Bug]: Puppeteer crashes while running in production

### ISSUE THREAD

**Issue by JosiasAurel** [puppeteer/puppeteer#9802]
### Bug expectation

I am trying to build a scoring service for an open-source game using puppeteer.

I am not sure if this is a bug or not.

When developing locally, the scoring service (using puppeteer) works fine and returns result as expected (an object { expression, T, level } but when I deploy it on a hosting service it doesn't work and seem to crash.

Here are the logs from one of the runs on railway.app https://pastebin.com/HWCf9mA0

Here is the source code for the scoring service https://github.com/JosiasAurel/sinerider/tree/leaderboard/scoring

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
export const playLevel = async (levelUrl) => {
  // init page record
  // const recorder = new PuppeteerVideoRecorder()

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  })
  const page = await browser.newPage()
  await page.setViewport({ width: 1280, height: 720 })
  await page.setRequestInterception(true)

  page.on('request', (req) => {
    if (req.resourceType() === 'media') {
      const sound = readFileSync(
        path.join(process.cwd(), '/Assets/', 'Sounds/blood_1.mp3'),
      )
      req.respond({ body: sound })
    } else if (req.resourceType() === 'image') {
      const image = readFileSync(
        path.join(process.cwd(), '/Assets/', 'Images/benny_float.webp'),
      )
      req.respond({ body: image })
    } else req.continue()
  })

  page.on('console', (msg) =>
    console.log(`${msg.type()}; \n ${msg.text()} \n\n`),
  )

  // init page recorder with page
  // recorder.init(page, './')

  // selectors
  const clickToBeginSelector = '#loading-string' // will have to wait until page is fully loaded before clicking
  const runButtonSelector = '#run-button'
  // const victoryLabelSelector = '#victory-label'

  // goto and wait until all assets are loaded
  await page.goto(levelUrl, { waitUntil: 'networkidle0', timeout: 0 })

  await browser.close()

  let expression = "";
  let T = 2.3;
  let level = "HELLO_WORLD";
  
  return { expression, T, level }
}
```

### Error string

'{"method":"Target.targetCrashed","params":{"targetId":"7DDE44426160D6C0CFE76766863FBFFB","status":"killed","errorCode":9}}'

### Puppeteer version

19.6.3

### Node version

v18.30.0

### Package manager

npm

### Package manager version

8.19.3

### Operating system

Linux

**Comment by OrKoN** [comment]
@JosiasAurel it looks like it might be running out of memory or some other resources constraints or some browser bug that causes the tab to crash. The targetCrashed event is emitted in only one place when the tab process is gone: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/target_handler.cc;l=1251;drc=bec0ef46974cd9a6bc0f1f1ae34baa11913f77af Try increasing memory/cpu in your environment or if you believe it is crashing because of the web content in the tab, report an issue at crbug.com.

**Comment by OrKoN** [comment]
Perhaps also try to minimize the repro and figure out which part causes crashing: i.e., does it work without any request interception and so on.

**Comment by JosiasAurel** [comment]
> Perhaps also try to minimize the repro and figure out which part causes crashing: i.e., does it work without any request interception and so on.

Nope it doesn't work even without request interception.

**Comment by OrKoN** [comment]
which hosting service do you use? maybe the environment there does not have all dependencies need for chromium. Is the game using webgl/gpu or smth like this? Maybe it is not available on the server? See https://pptr.dev/troubleshooting for common problems deploying Puppeteer.

**Comment by JosiasAurel** [comment]
I use railway.app for hosting. I've tried Digital Ocean as well but it still hanged

**Comment by JosiasAurel** [comment]
Confirmed that using a droplet with more memory fixes the issue.
