### ISSUE TITLE
Release v0.12.0-alpha

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#981]
The API documentation links to an unreleased v0.12.0-alpha version.

Release the v0.12.0 version under the alpha tag.

**Comment by vsemozhetbyt** [comment]
You can install (or update to) v0.12.0-alpha with `npm i https://github.com/GoogleChrome/puppeteer/`

**Comment by gajus** [comment]
Thats not the same. I want to be able to use my dependency version package manager to be able to inform me when the next version changes (e.g. `npm-check-updates`). For this, the package needs to be present in the registry.

**Comment by vsemozhetbyt** [comment]
But the alpha version is cutting-edge, it is changed daily, it seems it is just a synonym of the master branch.

**Comment by Garbee** [comment]
I think the better action here is to refactor the docs to say `master` or something resembling the current dev state instead of the next version.

**Comment by gajus** [comment]
I see. Indeed, "alpha" gives an impression that is a tagged release.
