### ISSUE TITLE
[Bug]: headless: true renders page as white.

### ISSUE THREAD

**Issue by goldingdamien** [puppeteer/puppeteer#9811]
### Bug expectation

I expected the page to be rendered, but it was rendered as a white screenshot.
Problem page: https://theopenweb.info

I tried on 3 pages, a popular page, the problem page, a page on the same domain as the problem page.
Only the problem page has the issue.
The issue only happens when headless is true.

This page has had similar issues in a few libraries using puppeteer.
This page seems to have indexing issues on Google. Does Google use puppeteer in headless mode for indexing?

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; // TS/ESM are all supported.
// const puppeteer = require('puppeteer')

(async () => {
// const url = 'https://news.google.com/news/'
const url = 'https://theopenweb.info'
// const url = 'https://theopenweb.info/apps/'

async function test(headless = false) {
  const browser = await puppeteer.launch({ headless });
  const page = await browser.newPage();
  await page.goto(url);
  await page.screenshot({path: (headless ? 'headless_' : '') + 'screenshot.png', fullPage: true});
  await browser.close();
}
await test(true) // headless
await test(false) // not headless
})();

// SAME
// "puppeteer": "1.20.0"
// "puppeteer": "19.7.3"
```

### Error string

no error

### Puppeteer version

19.7.3

### Node version

v18.14.1

### Package manager

npm

### Package manager version

9.3.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Hey, thanks for the report but I am unable to reproduce. I get the full screenshot in both modes.
![headless_theopenweb](https://user-images.githubusercontent.com/399150/223946980-ecae631f-2769-4cd2-8172-2b64d7dfcb4b.png)

**Comment by OrKoN** [comment]
I am on a Mac machine and I don't have a Windows machine to try it on. Could you try on a different machine?

**Comment by goldingdamien** [comment]
@OrKoN 
Ok, I'll try.
I am using Windows 11.

**Comment by goldingdamien** [comment]
@OrKoN 
I executed through Node.js using require('puppeteer'). Should I be using TS/ESM instead?

**Comment by OrKoN** [comment]
We support both versions so it should not matter.

**Comment by goldingdamien** [comment]
Checked on another computer with Windows 10 and it is working fine.

**Comment by goldingdamien** [comment]
Seems to be different:

[0309/162958.690:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0309/162958.693:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.

**Comment by goldingdamien** [comment]
Related:
https://github.com/puppeteer/puppeteer/issues/1610
https://github.com/lucacasonato/deno-puppeteer/issues/5
https://github.com/puppeteer/puppeteer/issues/1260

**Comment by goldingdamien** [comment]
However, why does this only happen on https://theopenweb.info but not on https://news.google.com/news/ or https://theopenweb.info/apps/ ?
Different CSS requires GPU?

**Comment by goldingdamien** [comment]
For https://theopenweb.info/apps/ the same error occurs, but the page is loaded.

```txt
$ node ./examples/puppeteer-test.js

DevTools listening on ws://127.0.0.1:64003/devtools/browser/3a413254-74f9-4c5a-88ac-d291354fbe69
[0309/165140.813:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0309/165140.814:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0309/165143.732:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

200 https://theopenweb.info/apps/
200 https://theopenweb.info/apps/style.css
200 https://theopenweb.info/apps/img/source_white_24dp.svg
200 https://theopenweb.info/apps/data/submissions/theopenweb-client-screenshot/2021-4-25_11-15-56_No-00.png
200 https://theopenweb.info/apps/data/submissions/resume-maker-screenshot/2021-4-25_10-59-53_No-00.png
200 https://theopenweb.info/apps/data/submissions/browser-capabilities-screenshot/2021-4-25_11-16-30_No-00.png
200 https://theopenweb.info/apps/img/web_white_24dp.svg
200 https://bootswatch.com/4/cyborg/bootstrap.min.css
200 https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap
200 https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxK.woff2
200 https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmWUlfBBc4.woff2
200 https://theopenweb.info/apps/data/submissions/data-converter-screenshot/2021-4-25_11-17-42_No-00.png
200 https://theopenweb.info/apps/data/submissions/homepage-screenshot/2021-4-25_11-15-21_No-00.png
200 https://theopenweb.info/apps/data/submissions/commew-screenshot/2021-4-25_11-14-18_No-00.png
```

**Comment by OrKoN** [comment]
Thanks for the details. Since it is not reproducing well on other machines, perhaps it's some problem with the current machine. In any case, it does sound like it's the browser's gpu problem. And, actually, I seem to be able to reproduce without Puppeteer on the Canary build of Chromium:

```
/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --headless --screenshot --timeout=10000 https://theopenweb.info
```

on Windows it would be

```
path\to\chrome.exe --headless --screenshot --timeout=10000 https://theopenweb.info
```

I will file the issue with crbug.com.

**Comment by OrKoN** [comment]
Filed https://crbug.com/1423254 but not 100% sure it is the same issue.

**Comment by OrKoN** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1423254#c5
