### ISSUE TITLE
[Bug]: Can't run Puppeteer on windows server (2019)

### ISSUE THREAD

**Issue by ghost** [puppeteer/puppeteer#9819]
### Bug expectation

I expected to run from 2 to 5 tests at the same time.
By the way, everything works fine on my home pc, but on the test server - I get these errors: 
`[14812:27896:0307/192701.724: ERROR: process_singleton win.cc(420)] Lock file can not be created! Error code: 3 [14812:27896:0307/192701.724:EFtFtOR:chrome_main_delegate.cc(732)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption. TROUBLESHOOTING: https://github.com/puppeteer/puppeteeriblob/main/docs/troubleshooting.md `

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
    args: ['--no-sandbox', `--proxy-server=${getProxy()}`,'--ignore-gpu-blocklist', '--enable-gpu-rasterization', '--enable-zero-copy', '--disable-web-security', '--window-position=0,0', '--window-size=1,1', '--no-zygote', '--no-xshm', '--use-gl=desktop'], //
    headless: false,
    ignoreHTTPSErrors: true,
    executablePath: executablePath(),
  })
```

### Error string

Something went wrong

### Puppeteer version

19.7

### Node version

18.12

### Package manager

npm

### Package manager version

9.4

### Operating system

Windows

**Comment by OrKoN** [comment]
I don't think we can provide an additional help other than linking to https://pptr.dev/troubleshooting to see if there are some solutions for your environment because this has to do with running chromium on a specific environment rather than Puppeteer. Are you able to run a regular Chromium/Chrome browser on that server?

**Comment by mirikking** [comment]
> I don't think we can provide an additional help other than linking to https://pptr.dev/troubleshooting to see if there are some solutions for your environment because this has to do with running chromium on a specific environment rather than Puppeteer. Are you able to run a regular Chromium/Chrome browser on that server?

Yea, Chrome and Chromium working :(

**Comment by OrKoN** [comment]
Can you test if the basic puppeteer example without custom arguments and options works on the server?

**Comment by OrKoN** [comment]
The error message indicates that you run multiple browser instances on the same user data directory. Chromium does not support that but I don’t see you customize the data dir path. Is it happening in your code? Puppeteer should create a temporary dir by default. Also which version of the browser do you run? I see that you customize the executable path. Puppeteer is only guaranteed to work with the matching version of Chrome.

**Comment by mirikking** [comment]
>  Chromium does not support that but I don’t see you customize the data dir path. Is it happening in your code?
The settings I provide are all I use. Nothing will change inside the code...
I'm not changing the chrome version, I think Puppeteer is running the latest xD

**Comment by mirikking** [comment]
> The error message indicates that you run multiple browser instances on the same user data directory. Chromium does not support that but I don’t see you customize the data dir path. Is it happening in your code? Puppeteer should create a temporary dir by default. Also which version of the browser do you run? I see that you customize the executable path. Puppeteer is only guaranteed to work with the matching version of Chrome.

The settings I provide are all I use. Nothing will change inside the code...
I'm not changing the chrome version, I think Puppeteer is running the latest xD

**Comment by OrKoN** [comment]
@mirikking your snippet says otherwise

```
const browser = await puppeteer.launch({
    args: ['--no-sandbox', `--proxy-server=${getProxy()}`,'--ignore-gpu-blocklist', '--enable-gpu-rasterization', '--enable-zero-copy', '--disable-web-security', '--window-position=0,0', '--window-size=1,1', '--no-zygote', '--no-xshm', '--use-gl=desktop'], //
    headless: false,
    ignoreHTTPSErrors: true,
    executablePath: executablePath(),
  })
```

Please provide the complete minimal example that does not work for you. Otherwise, I think we are not able to help here. The error message from the browser seems correct so you should follow the advise given there. Feel free to open a crbug.com issue if you think the browser is not working well here.

**Comment by mirikking** [comment]
> @mirikking your snippet says otherwise
> 
> ```
> const browser = await puppeteer.launch({
>     args: ['--no-sandbox', `--proxy-server=${getProxy()}`,'--ignore-gpu-blocklist', '--enable-gpu-rasterization', '--enable-zero-copy', '--disable-web-security', '--window-position=0,0', '--window-size=1,1', '--no-zygote', '--no-xshm', '--use-gl=desktop'], //
>     headless: false,
>     ignoreHTTPSErrors: true,
>     executablePath: executablePath(),
>   })
> ```
> 
> Please provide the complete minimal example that does not work for you. Otherwise, I think we are not able to help here. The error message from the browser seems correct so you should follow the advise given there. Feel free to open a crbug.com issue if you think the browser is not working well here.

I fixed it by using chrome, not chromium.
But here is new issue, the code does not launch a new browser, but a new tab, and the code falls into an error. Here is a piece of code.

`const browser = await puppeteer.launch({
    args: ['--no-sandbox', "--disabled-setupid-sandbox", '--no-zygote', '--window-size=1,1'], 
    headless: false,
    ignoreHTTPSErrors: true,
    ignoreDefaultArgs: ['--disable-extensions'],
    userDataDir: '/dev/null',
    executablePath: [[CHROME]] === 'Use Chrome' ? [[CHROME_PATH]] : executablePath()
  })

  console.log(await browser.version())

  const page = await browser.newPage()
  await page.setBypassCSP(true);
  await page.setViewport({
    width: 640,
    height: 720,
  });

  try {
    // Go to page

    await page.goto('*', {
      waitUntil: 'networkidle2', timeout: 45000
    }).catch(async () => {
      await browser.close()
      throw new Error('connection failed')
    })...
    `
