### ISSUE TITLE
allow to pass a parameterized funciton as a string to page.evaluate

### ISSUE THREAD

**Issue by gajus** [puppeteer/puppeteer#982]
```js
await page.evaluate(`console.log(arguments);`, 'FOO');

```

produces `ReferenceError: arguments is not defined` error and as far as I can tell, there is no way to pass a parameterised function as a string to `page.evaluate`.

I have tried `await page.evaluate(`(a) => { console.log('a', a); }`, 'FOO');` as well, with no luck.

Meanwhile, stringifying methods at runtime produces unexpected results when used in combination with traspilers such as Babel, e.g.

```js
import fetch from 'fetch';

await page.evaluate(() => {
  fetch();
});

```

In this case, the code will be transpiled to `() => {_xfetch2()}`. `xfetch2` does not exist in the browser scope.

One workaround is to prefix all clashing variables with `window.`, though this approach is error prone.

**Comment by entrptaher** [comment]
How about simply exposing the `fetch` function?

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction

**Comment by aslushnikov** [comment]
@gajus the following works just fine for me:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', msg => console.log(msg.text));
  await page.evaluate((a) => { console.log('a', a); }, 'FOO');
  await page.close();
  await browser.close();
})();
```

**Comment by entrptaher** [comment]
@aslushnikov, Didn't he want to expose `Fetch` from the fetch library? :/

**Comment by aslushnikov** [comment]
@entrptaher not sure. It also can be that the issue is in interop with babel.

@gajus: you can use string interpolation to inject "arguments" to string literals passed as functions:
```js
const arg = 'FOO';
await page.evaluate(`console.log(${arg});`);
```

**Comment by gajus** [comment]
> @entrptaher not sure. It also can be that the issue is in interop with babel.

It says right there in the original issue:

> Meanwhile, stringifying methods at runtime produces unexpected results when used in combination with traspilers such as Babel, e.g.

The intention of the code is to access [`fetch` API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).

However, because a transpiler sees import of `fetch` in the scope of the function, it tries to assign a local reference to the code.

If it is still not clear, here is an example of the transpilation.

https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAMwKYwMYAtFQiOByZNdPAbgCgywBDAcyQDokA3KgGwFcqYkAKHgSjgBeAHxwA3mTiIUGAeQC-_EkA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0

For this reason, it is unsafe to stringify function body at a runtime.

**Comment by entrptaher** [comment]
I keep the injected and main codes separate for such reason. I was having similar problem with scopes. But passing a promise/function with all scope related information seems like an overkill to me. The node scope and the browser scope both has different api for same things.

Example code to keep things tidy.

```js
const puppeteer = require('puppeteer');
const pageFunctions = require("pageFunctions");

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await page.evaluate(pageFunctions['fetchThingsForMe']);
    await browser.close();
})();
```

btw, what's wrong with naming things this way to simplify the problem?

```js
import _fetch from 'fetch';
page.evaluate(() => {
  fetch();
});
```

where it applied as below,
```js
import puppeteer from 'puppeteer';
import _got from 'got';

puppeteer.launch({headless: false}).then(async(browser) => {
    const page = await browser.newPage();
    page.on('console', msg => console.log(msg));

    await page.goto("http://example.com");
    await page.exposeFunction('got', async(...args) =>{
        let data = await _got(...args);
        return data.body;
    });
    await page.evaluate(() => {
        got("http://echo.jsontest.com/key/value/one/two").then(response => console.log(response));
    });
});
```

I get the result,
![image](https://user-images.githubusercontent.com/8284972/31379984-c87d2392-add1-11e7-8124-2dadbbf6d447.png)

The question is more related *to how to ignore a function in babel*.

If I remember correctly, some other library had this function where one could access both scope from each other. ie, casperJS.

**Comment by gajus** [comment]
You can just do:

```js
import fetch from 'fetch';

page.evaluate(() => {
  window.fetch();
});

```

Thats not the point. This approach is error prone.

I would much rather be able to do this:

```js
import fetch from 'fetch';

await page.evaluate(`() => {
  fetch();
}`);

```

and avoid all the uncertainty from the start.

Implicit behaviour is never good.

**Comment by entrptaher** [comment]
So you want this behaviour,
```js
var links = [];
var casper = require('casper').create();

function getLinks() {
    var links = document.querySelectorAll('h3.r a');
    return Array.prototype.map.call(links, function(e) {
        return e.getAttribute('href');
    });
}

casper.start('http://google.fr/', function() {
   // Wait for the page to be loaded
   this.waitForSelector('form[action="/search"]');
});

casper.then(function() {
   // search for 'casperjs' from google form
   this.fill('form[action="/search"]', { q: 'casperjs' }, true);
});

casper.then(function() {
    // aggregate results for the 'casperjs' search
    links = this.evaluate(getLinks);
    // now search for 'phantomjs' by filling the form again
    this.fill('form[action="/search"]', { q: 'phantomjs' }, true);
});

casper.then(function() {
    // aggregate results for the 'phantomjs' search
    links = links.concat(this.evaluate(getLinks));
});

casper.run(function() {
    // echo results in some pretty fashion
    this.echo(links.length + ' links found:');
    this.echo(' - ' + links.join('\n - ')).exit();
});
```
Which is specified on this line https://github.com/casperjs/casperjs/blob/master/modules/casper.js#L786

Great. Let's make the solution then. :)

**Comment by gajus** [comment]
Wrong issue thread?

**Comment by gajus** [comment]
All I want is to be able to pass a parameterised function as a string to the `page.evaluate` method.

**Comment by entrptaher** [comment]
This is really interesting, I wanted to do the same, but ended up splitting the files and code, 
if you look at the example I showed of casperjs, you can see there is this line where you are basically executing a function on the browser scope. We can create a simple wrapper or use browserify to overcome this problem for now.

**Comment by entrptaher** [comment]
Try this way. Expose the function properly and then stringify whatever you want to run.

```js
import puppeteer from 'puppeteer';
import cryptoRandomString from 'crypto-random-string';

// Some functions that is available on NODE environment
function myAwesomeFunction(){
	return arguments;
}

(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();


  await page.goto("http://example.com");
  await page.exposeFunction('cryptoRandomString', cryptoRandomString);
  await page.exposeFunction('myAwesomeFunction', myAwesomeFunction);
  await page.evaluate(`
		// Now I'm inside BROWSER environment

		// my function is there, and it's promised
		myAwesomeFunction({foo: "bar"}).then((data)=>console.log(data))

		// chain
		cryptoRandomString(20).then((data)=>console.log(data));

		// async-await
		(async() => {
		  let awecrypto = await cryptoRandomString(20);
		  console.log(awecrypto); // should produce a 20 char string
		})()
		`);
})();

```

Result:
![image](https://user-images.githubusercontent.com/8284972/31427147-1f4f428e-ae88-11e7-91bb-cf2bd7b1e7db.png)

so for your function above, you just have to modify it this way,

```js
import fetch from 'fetch';
await page.exposeFunction('fetch', fetch); // expose it
await page.evaluate(`fetch()`); // use it
```

Exposing is there for you if you want.
If this still does not solve your problem, then you probably want to share all context at same scope.
Puppeteer uses DevTools Protocol, which requires you to pass a stringified function. You have to pass the whole function or expose it to the browsers context.

Maybe some other experts can help you if this still doesn't feel like solving your problem. 

While sharing the context is an interesting idea, I don't know if the developers at puppeteer will want to change the core just for saving one line. You can try to create a fork or a PR if you want. I'd like to test it out. :) .

On another hand, If you are thinking of doing the reverse, like using the **browsers fetch api** in the **NODE** context, for example, then, it's not as simple as how you think it is.

**Comment by entrptaher** [comment]
I don't feel like helping anymore when I go such length and get dislikes. :) I'm out of here. :D

**Comment by aslushnikov** [comment]
The https://github.com/GoogleChrome/puppeteer/issues/982#issuecomment-335706623 provides a reasonable solution for the issue.

**Comment by gajus** [comment]
This solution does not address the inherent design flaw in Puppeteer – converting a function to a string at runtime is not safe.

There is no guarantee that `function myAwesomeFunction () { return arguments; }` is not compiled into an incompatible expression at the compile time.

**Comment by entrptaher** [comment]
This is a very simple issue, try this in your babelrc, and the code I mentioned or any code that you want. But expose the function, that's how you can keep things seperate.

.babelrc
```
{
  "presets": ["es2015", "react"],
  "plugins": [
    "transform-es2015-function-name", ["transform-es2015-modules-commonjs-simple", {
      "noMangle": true
    }]
  ]
}
```

Don't rename, don't do anything, just use the **proper babel plugin** and expose whatever you want to expose to that page.

![image](https://user-images.githubusercontent.com/8284972/31433475-4d8e7f44-ae9b-11e7-9f9b-9b22011a90c6.png)

Related Babel issue:
- https://github.com/babel/babel/issues/6456

And, I mentioned a casperjs example above where you can expose the node to browser without any exposeFunction stuff.

If you have the solution feel free to share :) 
Peace.

**Comment by gajus** [comment]
> If you have the solution feel free to share :)

I do. Allow to pass a parameterised function as a string, e.g.

```js
page.evaluate(`(foo) => {
  console.log(foo);
}`, 'FOO');

```

You are evaluating string provided to `page.evaluate` anyway.

Before returning the result of evaluating `page.evaluate`, check if the result is a `Function`. If it is – call *that* function with the provided parameters and return the result.

It is that simple.

**Comment by gajus** [comment]
There is no point in asking someone to provide a solution if there is no follow up feedback.

**Comment by entrptaher** [comment]
It could be because people had a hard time understand the concept. Or they forgot to reply. 
I forgot to reply :D

**Comment by entrptaher** [comment]
And I simply lack the knowledge to implement the solution you provided. It went above my head. :D

**Comment by gajus** [comment]
ping @aslushnikov

**Comment by aslushnikov** [comment]
> This solution does not address the inherent design flaw in Puppeteer – converting a function to a string at runtime is not safe.

@gajus if passing in functions doesn't work for you, you can always pass in a string. There's no need to add parameters to the string since you can use [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to embed them: https://github.com/GoogleChrome/puppeteer/issues/982#issuecomment-335392002

**Comment by gajus** [comment]
I have tried your suggestion.

```js
const arg = 'FOO';
await page.evaluate(`console.log(${arg});`);

```

Gives:

```
Error: Evaluation failed: ReferenceError: FOO is not defined
    at <anonymous>:1:13
    at ExecutionContext.evaluateHandle (/Users/gajus/[..]/node_modules/puppeteer/lib/ExecutionContext.js:54:15)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by aslushnikov** [comment]
@gajus I forgot quotes around `console.log` argument.

The following works for me:

```js
const pptr = require('puppeteer');

(async() => {
  const browser = await pptr.launch();
  const page = await browser.newPage();
  await page.on('console', msg => console.log(msg.text));
  const arg = 'FOO';
  await page.evaluate(`console.log('${arg}');`);
  await browser.close();
})();
```

**Comment by gajus** [comment]
This method is limited to strings. It is not passing anything. It is interpolating the value.

**Comment by gajus** [comment]
Anyway, if anyone else stumbles upon this, a reasonable workaround is to use `new Function`, e.g.

```js
await page.evaluate(new Function('foo', 'console.log(foo);'), {foo: 'bar'});

```

**Comment by maxbates** [comment]
I too am running into issues with Babel processing code I want to run in the browser.

Is it possible to pass a string to `page.evaluate` which can reference `ElementHandle`s passed as args?

I'd like to run (and use the element reference):

```js
return page.evaluate((el, index) => { 
      const reader = new FileReader();
      const promise = new Promise((resolve) => { reader.onload = resolve; });
      reader.readAsText(el.files[index]);
      return promise.then(() => reader.result);
    }, input, index);
```

Currently, I get the error `Evaluation failed: ReferenceError: _promise2 is not defined`

I have to run:

```js
      const script = `
      const el = document.querySelector('${selector}');
      const reader = new FileReader();
      const promise = new Promise((resolve) => { reader.onload = resolve; });
      reader.readAsText(el.files[${index}]);
      promise.then(() => reader.result);
    `;

    return page.evaluate(script);
```

**Comment by entrptaher** [comment]
@maxbates, this easy tweak does not help?
https://github.com/GoogleChrome/puppeteer/issues/982#issuecomment-335756760

**Comment by jdolle** [comment]
I am having the same issue as the OP.
I would like to ["[use] the browsers fetch api in the NODE context"](https://github.com/GoogleChrome/puppeteer/issues/982#issuecomment-335706623).

I am writing a browser extension and want to test it in the context of the browser rather than mock chrome/other APIs. So for example, I have code that uses the MutationObserver and want to evaluate that function.

The code I have that does not work is:
```ts
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.setContent(html) // just an html string
await page.exposeFunction('myFunction', myFunction) // my function sets up a MutationObserver to watch for dom elements
await page.evaluate(async () => {
  const selector = '.example'
  const win = window as Window & WithReady
  win.myFunction(selector, () => {
    console.log('FOUND!')
  })
})
```
Am I thinking about this package all wrong? Is it meant more for integration tests with already published code?

I have also attempted to eval the code as a string, but because I am compiling it with babel first I'm having some issues -- specifically that it is missing the commonjs method `require` and `export` is undefined.

This code looks like:
```ts
// import { transformFileSync } from 'babel-core'
const codeString = transformFileSync(path.join(__dirname, './example.ts'), { }).code
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.evaluate(codeString)
await browser.close()
```

**Comment by entrptaher** [comment]
@jdolle, maybe you can use `.evaluateOnNewDocument` for that purpose. 

I noticed several things in your code,

For example, 
```js
const win = window as Window & WithReady
```
Does the code run properly without puppeteer? I mean, can you manually execute the code first on your browser and see what happens?

and, is `myFunction` a promise? page.evaluate will just evaluate something and if it's a promise it'll wait for the promise to return. So if myFunction is not a promise, you are expecting the wrong return.

And, you sure you want to expose fetch api in node context? If that's possible, then we would be able to use window and domelements and whatnot in node context just like that. But sounds more complex to me.

**Comment by jdolle** [comment]
@entrptaher Sorry, I should have specified or probably just converted my example -- my project is in TypeScript. `myFunction` is actually just called `ready` in my code, so `WithReady` is the type I made that contains ready specifically to add it to the Window type. As stated, I'm compiling everything with Babel (7 specifically, which has TS support), and that compiled code runs perfectly in my browser.
I'll give `evaluateOnNewDocument` a shot and report back. Thanks for the suggestion.

**Comment by jdolle** [comment]
Sadly, I'm not able to get `evaluateOnNewDocument` to even run it seems. My test is as simple as possible:
```
it('can call done', async (done) => {
  const page = await browser.newPage()
  await page.evaluateOnNewDocument(done)
  await page.goto('http://example.com/')
})
```

**Comment by entrptaher** [comment]
```js
it('fires when the element already exists', async () => {
  const page = await browser.newPage();
  await page.goto('http://example.com/');
  const elementExists = !!(await page.$('selector'));
  expect(elementExists).toBe.true // or whatever condition it is, or however you write it
})
```

**Comment by jdolle** [comment]
That's very different -- hence I don't know if I'm thinking about this tool properly.
What I'm trying to do is call a function that has been imported by my test, within the context of the page. So say I have a function called `selectElement` that just calls `document.querySelector` for an element and returns that value so that I can check it in an assertion. Is that possible?

**Comment by entrptaher** [comment]
Whatever your function is, if you can return the value, you can use it and check it in assertion.
Just make sure the function you are running actually returns something when you run it.

```
const thisValueReturned = await page.evaluate(codeString);
expect(thisValueReturned).to.be.(string)
```

**Comment by jdolle** [comment]
Hm. I think transforming the code causes issues here -- I am running it through babel and instrumenting w/nyc. Also, it seems impossible to determine coverage if you're eval-ing strings. Unfortunately I think mocking is my only option. Thank you for your help.

**Comment by oliviertassinari** [comment]
> This approach is error prone.

For the record in case someone else face this issue. I agree with @gajus's statement.
I have been facing an issue with `@babel/plugin-transform-runtime`. This plugin is hoisting some functions leading to errors like:
```js
Evaluation failed: ReferenceError: _from is not defined
```

I ended-up skipping this Babel plugin for the puppeteer test files.

**Comment by jay-deshmukh** [comment]
**not recommended for production but works best for dev**

```
const puppeteer = require('puppeteer')
const fnsArr = [
    `hello = () => {
        return "Hello"
    }`,
    `returnX = (x) => {
        return x
    }`
    
]
const run = async() =>{
    const browser = await puppeteer.launch({headless : false});
    const page = await browser.newPage();
    await page.goto('https://www.google.com/');
    const ans = await page.evaluate((arr)=>{
        const fn1 = eval(arr[1]);
        let x = "You are Awesome"
        return fn1(x);
    },fnsArr)
    console.log(ans);
}
run();
```

**Comment by gajus** [comment]
The best practise for this is documented here:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#code-transpilation-issues

**Comment by JohnDotOwl** [comment]
> ```js
> const arg = 'FOO';
> await page.evaluate(`console.log(${arg});`);
> ```

 Error: Evaluation failed: ReferenceError: FOO is not defined

**Comment by jay-deshmukh** [comment]
> > ```js
> > const arg = 'FOO';
> > await page.evaluate(`console.log(${arg});`);
> > ```
> 
> Error: Evaluation failed: ReferenceError: FOO is not defined

Try the following 

```
const arg = 'FOO';
await page.evaluate((arg) => {
 console.log(arg);
}, arg);
```

@rainbowhat

**Comment by ghost** [comment]
I've used eval with success
```
        await page.evaluateOnNewDocument((mockProperty) => {
          mockProperty = eval(mockProperty)
          mockProperty('window.navigator.platform', 'Win32')
        }, mockProperty.toString())
```

**Comment by schrufygroovy** [comment]
@aslushnikov  Could you add this restriction to the documentation of page.evaluate()?

If given pageFunction is of type string, the args are NOT passed to the pageFunction? Because current documentation only states: 'Arguments to pass to pageFunction' - which is actually not true

**Comment by Lemonymelon** [comment]
Just giving this a wee bump...
Tried the most reasonable looking solutions:

https://github.com/puppeteer/puppeteer/issues/982#issuecomment-503452846
https://github.com/puppeteer/puppeteer/issues/982#issuecomment-338746321

 ...to no avail. Anything from the devs? I'm trying to get something along the lines of:
{
const evaluatedElement = await element.evaluate(x => x[DOMElementPropertyArg]);
}
...on the go, rather than having to have separate functions to get hrefs, outerHTML, etc.

No biggie if not, just unfortunate.

**Comment by Lemonymelon** [comment]
Oh, in case it helps any weary travellers, this is the solution I settled on. Did what I wanted it do to so eh, victory, I guess.

const evalFunctions = {
  outerHTML: x => {
    return x.outerHTML;
  },
  innerHTML: x => {
    return x.innerHTML;
  }
};

const getDOMProp = async (page, CSSSelector, evalProp) => {
  const puppetArray = await page.$$(CSSSelector);
  const promises = await puppetArray.map(async element => {
    const evaluatedElement = await element.evaluate(evalFunctions[evalProp]);
    return evaluatedElement;
  });
  const resolvedPromises = await Promise.all(promises);
  return resolvedPromises;
};

const list = await getDOMProp(
    page, // puppeteer page,
    "#faq-left-nav > ul > li",
    "outerHTML"
  );

**Comment by Lemonymelon** [comment]
Oh, in case it helps any weary travellers, this is the solution I settled on. Did what I wanted it do to in that I can reuse my main function, even if I have to write a bunch of mini ones, so meh, victory, I guess. Woo.

const evalFunctions = {
outerHTML: x => {
return x.outerHTML;
},
innerHTML: x => {
return x.innerHTML;
}
};

const getDOMProp = async (page, CSSSelector, evalProp) => {
const puppetArray = await page.$$(CSSSelector);
const promises = await puppetArray.map(async element => {
const evaluatedElement = await element.evaluate(evalFunctions[evalProp]);
return evaluatedElement;
});
const resolvedPromises = await Promise.all(promises);
return resolvedPromises;
};

const list = await getDOMProp(
page, // puppeteer page,
"#left-nav > ul > li",
"outerHTML"
);

**Comment by dpw1** [comment]
How could I potentially use moment.js in Puppeteer's evaluate? exposing the function is not working for me.

**Comment by jay-deshmukh** [comment]
@dpw1 
> How could I potentially use moment.js in Puppeteer's evaluate? exposing the function is not working for me.

```js
await page.evaluate((momentJsfn) => {
 console.log(momentJsfn);
}, momentJsfn);
```

**Comment by mrseanryan** [comment]
Not sure if this helps or not - but this is what I did.

The best practice gave me this idea:

FROM:

```
await page.evaluate(`(async() => {
   console.log('1');
})()`);
```

TO:

```

const createBrowserCode = (x, y) => `
{
    const x = ${x};
    const y = ${y};
    return x * y;
}`;

const x = 10, y = 20;
await page.evaluate(`(async() => {
  ${createBrowserCode(x, y)};
})()`);
```

Allowing for args.
Possibly createBrowserCode() could read from a JavaScript file ...
