### ISSUE TITLE
[Bug]:  Unable to use on Netlify "Evaluation failed: ReferenceError: import_from is not defined"

### ISSUE THREAD

**Issue by priyankcommits** [puppeteer/puppeteer#9827]
### Bug expectation

Expected puppeteer to run but it crashed.
The script works fine on local M1 Mac but not Netlify Linux Functions.

Chrome Version: 109

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");
const chromium = require("@sparticuz/chromium");

(async () => {
  const path = await chromium.executablePath();
  const browser = await puppeteer.launch({
    // Required
    executablePath: path,

    // Optional
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    headless: chromium.headless,
  });
  const bargain = "oppo reno 8T 5G";
  const page = await browser.newPage();
  await page.goto(`https://www.google.co.in/search?q=${bargain}&tbm=shop`);

  await page.waitForSelector(".iXEZD");
  const goto = await page.evaluate(() => {
    return document.querySelector("a.iXEZD").href;
  });
  console.log("gotolink", goto);
  await page.goto(goto);
  await page.waitForSelector(".UxuaJe.shntl.FkMp");
  const modelName = await page.evaluate(() => {
    return document.querySelector("div.f0t7kf").textContent;
  });
  console.log("modelName", modelName);
  let data = await page.evaluate(() => {
    let rows = Array.from(document.querySelectorAll("tr.sh-osd__offer-row"));
    console.log("rows==>", rows);
    rows = rows.map((r) => {
      let source = r.querySelector("td > div > a")?.text;
      if (source) {
        source = source.split("Opens")[0];
      }
      let link = r.querySelector("td:nth-child(5) > div > a")?.href;
      if (link) {
        link = link.split("q=")[1].split("%")[0].split("&")[0];
      }
      const price = r.querySelector("td:nth-child(4) > div > div")?.innerText;
      return { source, link, price };
    });
    console.log(rows);
    return rows;
  });

  data = data.filter((d) => d.link.includes("http"));
  console.log("data==>", data);
  //   return links;
  // });
  await browser.close();
})();
```

### Error string

{"errorType":"Error","errorMessage":"Evaluation failed: ReferenceError: import_from is not defined\n    at pptr://__puppeteer_evaluation_script__:2:32","stack":["Error: Evaluation failed: ReferenceError: import_from is not defined","    at pptr://__puppeteer_evaluation_script__:2:32","    at ExecutionContext._ExecutionContext_evaluate (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async ExecutionContext.evaluate (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)","    at async Runtime.exports.handler (/var/task/api/dist/functions/getBargainLinks-background.js:66:14)"]}

### Puppeteer version

^19.7.4

### Node version

16.12.0

### Package manager

npm

### Package manager version

8.1.0

### Operating system

Linux

**Comment by OrKoN** [comment]
@jrandolf could you try to repro? it looks like it might be coming from the minified code

**Comment by priyankcommits** [comment]
Is there any known work around to get puppeteer to work serverlessly ?

Netlify does have an option to "not minify" but it doesn't seem to be honouring it at the moment.

**Comment by jrandolf** [comment]
> Is there any known work around to get puppeteer to work serverlessly ?

It depends where you want to run it. Our troubleshooting doc has a lot of info on this: https://pptr.dev/troubleshooting

Otherwise, it's dependent on your stack and we recommend asking on Stackoverflow.
