### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by janswist** [puppeteer/puppeteer#9830]
### Bug expectation

Expected to have installed Vue Devtools and shown browser.

What is happening is browser not showing up, only icon on the desktop menu.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');
const path = require('path');

(async () => {
  const extVueDevTools = path.join(process.cwd(), '/Users/janswist/library/application\ support/bravesoftware/brave-browser/default/extensions/nhdogjmejiglipccpnnnanhbledajbpd/6.5.0_0/')

  const browser = await puppeteer.launch({
    headless: 'new',
    // devtools: true,
    args: [
      `--disable-extensions-except=${extVueDevTools}`,
      `--load-extension=${extVueDevTools}`,
    ]
  });

  const page = await browser.newPage();

  await page.goto('https://vuejs.org/');
  
  await page.waitForSelector('title');

  // await page.evaluate(() => {
  //   // Inject Vue Devtools script into the page
  //   const script = document.createElement('script');
  //   script.setAttribute('src', 'https://cdn.jsdelivr.net/npm/@vue/devtools@latest');
  //   document.head.appendChild(script);
  // });

  // // Wait for Vue Devtools to load
  // await page.waitForFunction('!!(window.__VUE_DEVTOOLS_GLOBAL_HOOK__)');

  // // Open Vue Devtools
  // await page.evaluate(() => {
  //   window.Vue;
  // });
  // await page.evaluate(() => {
  //   window.__VUE_DEVTOOLS_GLOBAL_HOOK__.openDevTools();
  // });

  await browser.close();
})();
```

### Error string

no error shown

### Puppeteer version

19.7.4

### Node version

16.13

### Package manager

npm

### Package manager version

8.5.3

### Operating system

macOS

**Comment by janswist** [comment]
I literally said the browser is not not opening. How did you expect it to be reproducible?

**Comment by OrKoN** [comment]
Please provide the extension code or instructions how to get it.

**Comment by janswist** [comment]
Sure @OrKoN - it's here: https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd (official Vue.js dev tools extenstion)

**Comment by OrKoN** [comment]
Unable to repro, the script starts the browser and exits without problems:

```
const puppeteer = require('puppeteer');

(async () => {
  const extVueDevTools = '/Users/alexrudenko/Downloads/vue-extension'

  const browser = await puppeteer.launch({
    headless: 'new',
    args: [
      `--disable-extensions-except=${extVueDevTools}`,
      `--load-extension=${extVueDevTools}`,
    ]
  });

  const page = await browser.newPage();

  await page.goto('https://vuejs.org/');
  
  await page.waitForSelector('title');

  // await page.evaluate(() => {
  //   // Inject Vue Devtools script into the page
  //   const script = document.createElement('script');
  //   script.setAttribute('src', 'https://cdn.jsdelivr.net/npm/@vue/devtools@latest');
  //   document.head.appendChild(script);
  // });

  // // Wait for Vue Devtools to load
  // await page.waitForFunction('!!(window.__VUE_DEVTOOLS_GLOBAL_HOOK__)');

  // // Open Vue Devtools
  // await page.evaluate(() => {
  //   window.Vue;
  // });
  // await page.evaluate(() => {
  //   window.__VUE_DEVTOOLS_GLOBAL_HOOK__.openDevTools();
  // });

  await browser.close();
})();
```

**Comment by OrKoN** [comment]
Note, that the headless means that the browser window is not visible. You need to use headless:false if you need the browser with shown windows.

**Comment by janswist** [comment]
When I use `headless: false` I get `manifest.js was unable to read` error:
![image](https://user-images.githubusercontent.com/5583954/224642644-0451a2c4-8f21-407f-990e-bc8ae057da42.png)

When I use `headless: 'new'` and uncomment this section:
```
await page.evaluate(() => {
    window.__VUE_DEVTOOLS_GLOBAL_HOOK__.openDevTools();
  });
```

I get this error:
```
/Users/janswist/Developer/vue-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'openDevTools')
    at pptr://__puppeteer_evaluation_script__:2:41
    at ExecutionContext._ExecutionContext_evaluate (/Users/janswist/Developer/vue-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/janswist/Developer/vue-puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)
    at async /Users/janswist/Developer/vue-puppeteer/index.js:37:3
```

I recon from that that in the end Devtools were not loaded (or how am I able to check it? Possibly I'm doing it wrong)

**Comment by OrKoN** [comment]
I am not sure where __VUE_DEVTOOLS_GLOBAL_HOOK__ is coming from but it looks like openDevTools is not there. I have stringified __VUE_DEVTOOLS_GLOBAL_HOOK__ and got `{"devtoolsVersion":"6.0","Vue":null,"_buffer":[],"_bufferMap":{},"_bufferToRemove":{},"store":null,"initialState":null,"storeModules":null,"flushStoreModules":null,"apps":[]}`. So it looks like smth is working but I am not sure if the workflow is correct. Why do you need to evaluate the DevTools in the page context? If you use the new headless and open DevTools, the Vue extension should be loaded there and you should be able to access it by finding its target.

**Comment by OrKoN** [comment]
I don't get the error `manifest.js was unable to read` perhaps your path to the extension is not correct?

**Comment by OrKoN** [comment]
<img width="1201" alt="Screenshot 2023-03-13 at 09 21 07" src="https://user-images.githubusercontent.com/399150/224645327-dddb4633-224f-410a-b6af-691992c84bca.png">

This is what I get in the headful mode (seems like it's installed fine but I am not sure if other Vue-specific things work as expected)

**Comment by janswist** [comment]
What I intend to do is to be able to automate if provided websites are using Vue.js on their site. Using extension seems to be the easiest route. Will dive more into it - if it's working for you (especially that you use the same Mac machine) then it should work for me as well.

Will get back when I will get somewhere. Thank you for such a fast assistance, I appreciate it a lot!

**Comment by janswist** [comment]
Figured it out! You were right, there was something with extension path so to make sure I just copied it to the same folder folder as code I'm developing. Thank you again and have a fantastic day!
