### ISSUE TITLE
[Bug]: selectionchange event is not fired

### ISSUE THREAD

**Issue by alexpozzi** [puppeteer/puppeteer#9839]
### Bug expectation

I'm trying to write some end-to-end tests using Puppeteer and Chromium Browser to cover some specs on a WYSIWYG editor.
In particular, the feature I'm trying to cover is the styling of selected text using a menu that appears when the user makes a text selection.
In order to decide or not if this menu has to render or not I'm listening the `selectionchange` event and take the decision depending on the selected text.
Problem is that this event doesn't seems to be fired when I'm changing the text selection.
In oredr to change the text selection I followed the instructions described in [this project's documentation](https://pptr.dev/api/puppeteer.mouse/#remarks).

Is this a bug?
Is there a way to have the `selectionchange` event fire?

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
await page.evaluate(() => {
    const paragraphToBeSelected = document.querySelector('#editor-id > p')
    const range = document.createRange()
    range.selectNodeContents(paragraphToBeSelected)

    const selection = document.getSelection()
    selection.removeAllRanges();
    selection.addRange(range);
})
```

### Error string

no error

### Puppeteer version

18.1.0

### Node version

18.15.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by jrandolf** [comment]
I'm don't think programmatically changing the selection will launch a `selectionchange` event. Usually events in general are initiated as a result of user-initiated actions. In this case, it most likely is. I recommend launching the event manually if you need to trigger it. See https://developer.mozilla.org/en-US/docs/Web/API/Document/selectionchange_event
