### ISSUE TITLE
[Bug]: Puppeteer is not installed in Cache Directory

### ISSUE THREAD

**Issue by ackava** [puppeteer/puppeteer#9843]
## Installation of puppeteer in Cache Folder has stopped working after 19.5.2;

Till version 19.5.2, this was working correctly. Following is the config file `puppeteer.config.cjs`.

```javascript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, 'node_modules', 'puppeteer-chromium'),
};
```

**But now, in latest version `19.7.4` it is not working**, I will try to backtrack, but I see there is no difference in readme file for configuration and you can verify the contents of `puppeteer.config.cjs` at https://github.com/neurospeech/puppeteer-lambda-layer/blob/main/puppeteer.config.cjs , it has not been changed recently.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
You can try cloning https://github.com/neurospeech/puppeteer-lambda-layer and change the action 
https://github.com/neurospeech/puppeteer-lambda-layer/blob/main/.github/workflows/nodejs.yml#L23

## From

- run: npm install puppeteer@19.5.2
``

## To
yml
- run: npm install puppeteer
```

It fails with an error that folder `node_modules/puppeteer-chromium` is not found.
```


### Error string

File or folder `node_modules/puppeteer-chromium` is not found.

### Puppeteer configuration

```TypeScript
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, 'node_modules', 'puppeteer-chromium'),
};
```

### Puppeteer version

19.7.4

### Node version

18

### Package manager

npm

### Package manager version

??

### Operating system

Linux

**Comment by jrandolf** [comment]
I was not able to replicate this locally. This doesn't look actionable on our side. Please make sure to use fresh installs.
