### ISSUE TITLE
[Feature]: Not able to run puppeteer extension on AWS EC2 instance 

### ISSUE THREAD

**Issue by chandanray876** [puppeteer/puppeteer#9850]
### Feature description

I have tried to run puppeteer extension on AWS EC2 instance using XVFB but it not running and also not running the background JS file.
On local machine Ubuntu it running perfectly using XVFB. I try to capture chorme stream using XVFB.
Please suggest any thing why it's not working on AWS EC2 instance.

Ubuntu 20.04
XVFB
Puppeteer

**Comment by OrKoN** [comment]
Please follow https://pptr.dev/guides/chrome-extensions to test extensions and fill out a bug form if you believe there is a bug. Ask your question on StackOverflow if you are not sure how to implement a specific deployment. Closing as it is not a feature request.
