### ISSUE TITLE
[Bug]: Not able to run puppeteer extension on AWS EC2 instance

### ISSUE THREAD

**Issue by chandanray876** [puppeteer/puppeteer#9857]
### Bug expectation

I have tried to run puppeteer extension on AWS EC2 instance using XVFB but it not running and also not running the background JS file.
On local machine Ubuntu it running perfectly using XVFB. I try to capture chorme stream using XVFB.
Please suggest any thing why it's not working on AWS EC2 instance.

Ubuntu 20.04
XVFB
Puppeteer

To run the code I am using below command

xvfb-run -a --server-args="-screen 0 1x1x24 -ac -nolisten tcp +extension RANDR" yarn serve

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import isRoot from 'is-root'
import path from 'path'
import { fileURLToPath } from 'url'
import puppeteer from 'puppeteer'

const dirname = path.dirname(fileURLToPath(import.meta.url))

const extension = path.join(dirname, 'extension')
console.log("Path extension", extension);
const extensionId = 'aahdpjnamionemlcfkodembopehdcipg'
const eventBlacklist = ['page', 'background_page']

const cdp = async (page) => {
  const client = await page.target().createCDPSession()

  client.send('Page.setDownloadBehavior', {
    behavior: 'deny'
  })
}

export default async (options) => {
  const width =  options.width //1280

  const height = Math.trunc(width / options.ratio) //options.height //Math.trunc(width / options.ratio)

  const browser = await puppeteer.launch({
    args: [
      '--block-new-web-contents',
      '--disable-breakpad',
      '--disable-dev-shm-usage',
      `--disable-extensions-except=${extension}`,
      `--file-url-path-alias=/=${path.join(dirname, 'forbidden')}/`,
      '--hide-crash-restore-bubble',
      '--kiosk',
      '--ignore-gpu-blocklist',
      `--load-extension=${extension}`,
      '--no-crash-upload',
      '--no-default-browser-check',
      '--no-first-run',
      '--no-recovery-component',
      isRoot() ? '--no-sandbox' : '',
      isRoot() ? '--no-zygote' : '',
      '--noerrdialogs',
      '--suppress-message-center-popups',
      `--use-gl=${process.env.GPU_GL || 'swiftshader'}`,
      `--user-data-dir=chrome-user-data/${options.token}`,
      `--window-size=${width},${height + 90}`,
      `--whitelisted-extension-id=${extensionId}`,
    ],
    defaultViewport: { width, height },
    // defaultViewport: null,
    executablePath: process.env.CHROMIUM_EXECUTE_PATH || undefined,
    // devtools: true,
    headless: 'chrome',
    ignoreDefaultArgs: [
      '--disable-popup-blocking',
      '--enable-automation',
      '--mute-audio',
    ]
  })

  const page = (await browser.pages())[0]
  await page.setUserAgent(options.userAgent);

  cdp(page)

  browser.on('targetcreated', async (target) => {
    if (!eventBlacklist.includes(target.type())) {
      return
    }

    await page.goto(target.url())

    (await target.page()).close()
  })

  return { browser, page }
}
```

### Error string

no error

### Puppeteer version

19.7.5

### Node version

18.13.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
Could you use `dumpio: true` flag on the launch and  the env var`DEBUG=puppeeteer:*` and provide the resulting log?

**Comment by chandanray876** [comment]
I have add what you suggested and got the log, I am sharing the log screen shot.

![Screenshot from 2023-03-15 14-10-28](https://user-images.githubusercontent.com/67946312/225254109-3ad3dabb-c0c0-47c2-9b42-df0d87f0d47d.png)

**Comment by OrKoN** [comment]
It looks like you might not have gpu and you provide some custom attributes that are not compatible with your system. Try leaving out those attributes.

**Comment by OrKoN** [comment]
Try using `--enable-gpu` instead of `--use-gl`

**Comment by chandanray876** [comment]
Hello @OrKoN I have successfully run this project on local machine using Ubuntu 20.04 but it not working on AWS EC2 instance. 

After adding --enable-gpu I have got below log:-  

![Screenshot from 2023-03-15 14-33-12](https://user-images.githubusercontent.com/67946312/225259748-8fa62901-494a-490b-b601-736878d036be.png)

**Comment by OrKoN** [comment]
Unfortunately, we cannot provide further guidance. The problem is definitely in the AWS EC2 environment. Checkout the available CLI flags https://peter.sh/experiments/chromium-command-line-switches/ and known issues https://pptr.dev/troubleshooting#running-puppeteer-on-aws-ec2-instance-running-amazon-linux It looks like the problem is related to the GPU not being available on the EC2 instance. If you believe it is a Chromium bug, please report it to crbug.com.

Also, I noticed that you use `headless: 'chrome'` and that is outdated. The correct version is `headless: 'new'`  (see https://pptr.dev/guides/chrome-extensions)
