### ISSUE TITLE
PDF is not generating for huge HTML file (approx. 31MB) using pupeteer (version 19.6.0)

### ISSUE THREAD

**Issue by Ashishy1** [puppeteer/puppeteer#9858]
I am facing a problem where HTML file is not converted into PDF. Size of HTML file is 31MB. My HTML file contains tables and rows (approx. 400k rows)

Puppeteer version
version 19.6.0

Node.js version
16.14.2

npm version
8.5.0

What operating system are you seeing the problem on?
Linux

**This is my code**
   
```javascript
(async () => {
      const browser = await puppeteer.launch({ignoreHTTPSErrors: true});
      const page = await browser.newPage();
      const html = fs.readFileSync(path.join(__dirname , 'test.html'), 'utf-8');
      await page.setContent(html, { waitUntil: 'domcontentloaded' });
      const pdf = await page.pdf({
                  path: 'report.pdf',
                  margin: { top: '100px', right: '50px', bottom: '100px', left: '50px' },
                  printBackground: true,
                  format: 'A4',
                  displayHeaderFooter: true,
                  pageRanges: "",
                  timeout:0,
      });

      await browser.close();
})();
```
**I am getting error at `await page.pdf()` line and the error is:** 
**Error Log:**
Error generating PDF:  ProtocolError: Protocol error (Page.printToPDF): Printing failed
    at D:\ETMS\ETMSBACKEND\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (D:\ETMS\ETMSBACKEND\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:325:16)
    at CDPPage.createPDFStream (D:\ETMS\ETMSBACKEND\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:746:88)
    at CDPPage.pdf (D:\ETMS\ETMSBACKEND\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:772:37)
    at D:\ETMS\ETMSBACKEND\src\services\report\report-details\report-details.service.js:454:60
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by OrKoN** [comment]
Please report the issue to crbug.com providing a full repro and the logs produced by the `dumpio: true` flag. I am not sure if PDF generation is optimized for printing large HTML documents but this is out of scope for Puppeteer.
