### ISSUE TITLE
[Bug]: Puppeteer with Firefox, `page.goto()` never resolves

### ISSUE THREAD

**Issue by utkarshgupta2504** [puppeteer/puppeteer#9860]
### Bug expectation

Initially was working with chrome, everything was working fine, switched to firefox due to the capability of firefox to run web.whatsapp in headless mode.
Wrote the sample code, navigate to google and get the screenshot, expected a screenshot of the Website.

Got Error: 
`TimeoutError: Navigation timeout of 30000 ms exceeded`

Set timeout to 0, and tried with all the `waitFor` values that puppeteer provides, the promise still never resolves, have waited for upto 5 minutes

Interestingly though, if I run it in a non-headless format, I do see the page being navigated to, and get loaded, but the promise still never resolves.

Config:
Puppeteer: 19.7.5
Firefox: mac-113.0a1

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
	product: 'firefox'
  });
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

### Error string

TimeoutError: Navigation timeout of 30000 ms exceeded

### Puppeteer version

19.7.5

### Node version

16.13.2

### Package manager

npm

### Package manager version

8.19.2

### Operating system

macOS

**Comment by OrKoN** [comment]
cc @whimboo

**Comment by utkarshgupta2504** [comment]
The actions error logs say that Firefox is not installed, where should I add it in the issue?

**Comment by OrKoN** [comment]
@utkarshgupta2504 the bot does not support Firefox so please ignore that.

**Comment by OrKoN** [comment]
Thanks for the quick triage, @whimboo. Likely the same issue as https://bugzilla.mozilla.org/show_bug.cgi?id=1706353
