### ISSUE TITLE
[Bug]: Not able to run puppeteer extension on AWS EC2 instance also using GPU

### ISSUE THREAD

**Issue by chandanray876** [puppeteer/puppeteer#9869]
### Bug expectation

I have tried to run puppeteer extension on AWS EC2 instance using XVFB but it not running and also not running the background JS file.
On local machine Ubuntu it running perfectly using XVFB. I try to capture chorme stream using XVFB.
Please suggest any thing why it's not working on AWS EC2 instance.

Ubuntu 20.04
XVFB
Puppeteer
GPU

To run the code I am using below command

xvfb-run -a --server-args="-screen 0 1x1x24 -ac -nolisten tcp +extension RANDR" yarn serve

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import isRoot from 'is-root'
import path from 'path'
import { fileURLToPath } from 'url'
import puppeteer from 'puppeteer'

const dirname = path.dirname(fileURLToPath(import.meta.url))

const extension = path.join(dirname, 'extension')
console.log("Path extension", extension);
const extensionId = 'aahdpjnamionemlcfkodembopehdcipg'
const eventBlacklist = ['page', 'background_page']

const cdp = async (page) => {
  const client = await page.target().createCDPSession()

  client.send('Page.setDownloadBehavior', {
    behavior: 'deny'
  })
}

export default async (options) => {
  const width =  options.width //1280

  const height = Math.trunc(width / options.ratio) //options.height //Math.trunc(width / options.ratio)

  const browser = await puppeteer.launch({
    args: [
      '--block-new-web-contents',
      '--disable-breakpad',
      '--disable-dev-shm-usage',
      `--disable-extensions-except=${extension}`,
      `--file-url-path-alias=/=${path.join(dirname, 'forbidden')}/`,
      '--hide-crash-restore-bubble',
      '--kiosk',
      '--ignore-gpu-blocklist',
      `--load-extension=${extension}`,
      '--no-crash-upload',
      '--no-default-browser-check',
      '--no-first-run',
      '--no-recovery-component',
      isRoot() ? '--no-sandbox' : '',
      isRoot() ? '--no-zygote' : '',
      '--noerrdialogs',
      '--suppress-message-center-popups',
      `--user-data-dir=chrome-user-data/${options.token}`,
      `--window-size=${width},${height + 90}`,
      `--whitelisted-extension-id=${extensionId}`,
      '--no-sandbox', 
      '--disable-setuid-sandbox', 
      '--single-process',
      '--ignore-gpu-blocklist',
      '--enable-gpu-rasterization',
      '--enable-oop-rasterization',
      '--disable-gpu-driver-bug-workarounds',
      '--enable-accelerated-video-decode',
      '--use-gl=desktop',
      '--enable-zero-copy',
    ],
    defaultViewport: { width, height },
    // defaultViewport: null,
    executablePath: process.env.CHROMIUM_EXECUTE_PATH || undefined,
    // devtools: true,
    headless: 'chrome',
    dumpio: true,
    ignoreDefaultArgs: [
      '--disable-popup-blocking',
      '--enable-automation',
      '--mute-audio',
    ]
  })

  const page = (await browser.pages())[0]
  await page.setUserAgent(options.userAgent);

  cdp(page)

  browser.on('targetcreated', async (target) => {
    if (!eventBlacklist.includes(target.type())) {
      return
    }

    await page.goto(target.url())

    (await target.page()).close()
  })

  return { browser, page }
}
```

### Error string

GpuChannel: Failed to create SharedImageStub, Failed to create GLES3 context, fallback to GLES2., ContextResult::kFatalFailure: Failed to create shared context for virtualization.

### Puppeteer version

19.7.5

### Node version

18.15.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by chandanray876** [comment]
This is whole error string:-

DevTools listening on ws://127.0.0.1:41695/devtools/browser/c240d856-6058-46b0-a966-2403fd658d33
[0316/183145.321585:ERROR:devtools_http_handler.cc(306)] Error writing DevTools active port to file
[0316/183145.352460:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0316/183145.354773:ERROR:gpu_channel_manager.cc(869)] Failed to create GLES3 context, fallback to GLES2.
[0316/183145.354841:ERROR:gpu_channel_manager.cc(880)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0316/183145.354853:ERROR:shared_image_stub.cc(473)] SharedImageStub: unable to create context
[0316/183145.354875:ERROR:gpu_channel.cc(589)] GpuChannel: Failed to create SharedImageStub
[0316/183145.354938:ERROR:gpu_channel_manager.cc(869)] Failed to create GLES3 context, fallback to GLES2.
[0316/183145.354947:ERROR:gpu_channel_manager.cc(880)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[0316/183145.354954:ERROR:shared_image_stub.cc(473)] SharedImageStub: unable to create context
[0316/183145.354961:ERROR:gpu_channel.cc(589)] GpuChannel: Failed to create SharedImageStub
[03-16 18:31:45.390] [LOG]   ::ffff:111.93.41.194 launch {
  token: '4727bd99-6cb7-46fa-8c05-d160ce7d5aaa',
  ratio: 2.3797909407665507,
  height: 574,
  width: 1366
}

**Comment by OrKoN** [comment]
You should try using the `--enable-gpu` flag instead of all other flags. In general, it is not possible for us to guarantee any sort of functionality when so many custom flags are used. I'd suggest bisecting the flags and reporting the issue to crbug.com if some of the flags cause gpu issues.

**Comment by JMTK** [comment]
FWIW, this ended up being a red herring for me and I just needed to ensure that my `.Xauthority` was in the `~/` of the **user I was currently running as** when I was ssh'd and running these commands
