### ISSUE TITLE
[Bug]: With Chromium, there is no way to accept or dismiss a beforeunload dialog

### ISSUE THREAD

**Issue by kspeers-r7** [puppeteer/puppeteer#9871]
### Bug expectation

Expected: when a beforeunload dialog is triggered, that the dialog can either be accepted (to allow the navigation) or dismissed (to deny the navigation) and that the dialog disappears

Actual: beforeunload dialog is triggered and caught by page.on('dialog'). The navigation happens and neither accepting or dismissing the dialog closes the dialog

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false })  //launch browser in headless mode
  const page = await browser.newPage()  //browser new page
  await page.setViewport({ width: 1920, height: 1080 })

  page.on('dialog', async dialog => {   //on event listener trigger
    console.log(`Found dialog. Type: ${dialog.type()}, message: ${dialog.message()}`); // get dialog type and message
    await dialog.dismiss(); // neither dismiss or accept work
  })

  await page.goto('https://example.com')
  await page.addScriptTag({ content: 'window.onbeforeunload = (evt) => { evt.preventDefault(); evt.returnValue = ""}' })
  await page.click('body') // chromium requires a user gesture to enable beforeunload
  await page.evaluate('window.location="https://www.iana.org/domains/reserved"') // trigger a navigation
  await page.waitForTimeout(10000) // wait to be sure the dialog doesn't disappear
  await browser.close()
})()
```

### Error string

no error

### Puppeteer version

19.7.5

### Node version

16.16.0

### Package manager

npm

### Package manager version

8.11.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Filed https://crbug.com/1432619
