### ISSUE TITLE
[Bug]: Not printing the image that is inside my ejs file.

### ISSUE THREAD

**Issue by Femish-Bhalodiya** [puppeteer/puppeteer#9872]
### Bug expectation

When I am trying to print a pdf with the help of Puppeteer and ejs template it can't wait for resolving paths. So it will print the page before the path of styles, and the image is resolved. As a result, it will print only data without CSS and images

### Bug behavior

- [ ] Flaky
- [X] PDF

### Minimal, reproducible example
index.ejs file
```HTML
<link rel="stylesheet" href="/css/style.css">
<div class="logo-img">
    <img style="margin-left: 200px;" src="/img/tree.jpg" width=300px height=250px>
  </div>
```

```TypeScript
for (let i = 1; i < response.length; i++) {
        (async () => {
          const browser = await puppeteer.launch();
          const [page] = await browser.pages();
          const html = await ejs.renderFile('views/index.ejs', {
            data: response[i],
          });
          await page.setContent(html, { waitUntil: 'domcontentloaded' });
          const pdf = await page.pdf({
            path: `result-${i}.pdf`,
            printBackground: true,
            format: 'A4',
          });
          await browser.close();
        })();
      }
```

### Error string

no error

### Puppeteer version

19.7.5

### Node version

18.14.0

### Package manager

npm

### Package manager version

9.3.1

### Operating system

Windows

**Comment by OrKoN** [comment]
Try using the `load` or better `networkidle` events before getting a PDF. DOMContentLoaded is wrong here because it does not wait for images.

**Comment by Femish-Bhalodiya** [comment]
> Try using the `load` or better `networkidle` events before getting a PDF. DOMContentLoaded is wrong here because it does not wait for images.

Still the problem is not resolved
If I use an external image link, it will print on my pdf but the problem is with resolving the path of local files.

**Comment by OrKoN** [comment]
This is not the issue with Puppeteer. You need to make sure that local files are resolvable by either having them locally, adding the image inline as a data URL or serving them from a server.

**Comment by Femish-Bhalodiya** [comment]
Then how can i make puppeteer to wait until my ejs load image or resolve image or CSS path

**Comment by OrKoN** [comment]
I recommend posting this sort of question on StackOverflow, there are multiple ways to achieve what you need.

**Comment by blue-collarpittance** [comment]
I think you might benefit from this https://nodejser.space/questions/printing-cookies-in-the-ejs-view-engine-is-simple-and-easy-just-follow-these
