### ISSUE TITLE
[Bug]: Can't run nodejs app from terminal as normal user. Just from root

### ISSUE THREAD

**Issue by almivision** [puppeteer/puppeteer#9907]
### Bug expectation

I dont know can i do to fix that, i tried from others tickets, but it doesn't work.

[nutrisential@server bewell]$ node export_awb_to_pdf.js
/home/nutrisential/dev.nutrisential.ro/wp-content/themes/bewell/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:302
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
../../base/allocator/partition_allocator/partition_address_space.cc(103) Check failed: false

TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at onClose (/home/nutrisential/dev.nutrisential.ro/wp-content/themes/bewell/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:302:20)    at Interface.<anonymous> (/home/nutrisential/dev.nutrisential.ro/wp-content/themes/bewell/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:290:24)    at Interface.emit (node:events:525:35)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const args = process.argv;

  const browser = await puppeteer.launch({
      headless: false,
    ignoreDefaultArgs: ['--disable-extensions'],
    args: ['--no-sandbox', '--disable-setuid-sandbox'],

  });
  
  const page = await browser.newPage();

  await page.setViewport({width: 1900, height: 1000});

  await page.goto('/wp-content/themes/bewell/test.html',  {waitUntil: ['networkidle2']});
  
  await page.waitForSelector('.awb-title');
  
  await page.emulateMediaType('screen');

  console.log('pdf');

  await page.pdf({ path: '/home/nutrisential/dev.nutrisential.ro/wp-content/themes/bewell/exported_html.pdf', format: 'A4', printBackground: true, scale: 0.8});

  await browser.close();

})();
```

### Error string

Error: Failed to launch the browser process! ../../base/allocator/partition_allocator/partition_address_space.cc(103) Check failed: false

### Puppeteer version

19.7.5

### Node version

v16.19.0

### Package manager

npm

### Package manager version

19.7.5

### Operating system

Linux

**Comment by OrKoN** [comment]
Have you tried the following steps https://github.com/puppeteer/puppeteer/issues/6978#issuecomment-811150081 ?

**Comment by almivision** [comment]
> Have you tried the following steps [#6978 (comment)](https://github.com/puppeteer/puppeteer/issues/6978#issuecomment-811150081) ?

Hello, i tried.. but no chance to make it to work
