### ISSUE TITLE
[Bug]: Puppeteer does not display the Video Thumbnail when I convert the URL to PDF

### ISSUE THREAD

**Issue by sathiyapriyaG** [puppeteer/puppeteer#9909]
### Bug expectation

I expected the YouTube and Twitter thumbnails to appear in the generated PDF using Puppeteer, but I received the following instead. Additionally, I tried the following lines in my code

**page.emulateMediaType("screen");**

**await iframe.contentFrame();**

But it's not working. Sometimes the text fonts size and font weight also not matched the original one

### Bug behavior

- [ ] Flaky
- [X] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://www.yansmedia.com/blog/best-website-videos');
    await page.emulateMediaType("screen");

    const options = {
      format: "A4",
      footerTemplate: footerContent,
      padding: {
        left: 0,
        right: 0,
      },
      scale: 0.85,
      timeout: 0,
    };
    const page2 = await page.pdf({
        ...options,
        margin: {
          top: 20,
          left: 0,
          right: 0,
          bottom: 48,
        },
        displayHeaderFooter: true,
        path: "result.pdf",
      });
    await browser.close();
});
```

### Error string

Timeout

### Puppeteer version

19.7.1

### Node version

18.12.1

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by sathiyapriyaG** [comment]
After updating the puppeteer version 19.7.1 to 19.7.5, the issue is not fixed.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/32445438/227467973-3f1153fc-e2e3-4fa6-ac43-e8c00200eee8.png">

**Comment by Lightning00Blade** [comment]
Hey @sathiyapriyaG, usually you have to set `printBackground: true` so the images are shown. Due to this being related to Media you may also want to read the limitation Puppeteer - [FAQ](https://pptr.dev/faq#q-what-features-does-puppeteer-not-support). A workaround would be to dig in the DOM and replace the Player with the thumbnail it has.
