### ISSUE TITLE
Browser unreachable after a couple of hours - how to debug?

### ISSUE THREAD

**Issue by kdekooter** [puppeteer/puppeteer#991]
I am monitoring a bunch of websites using puppeteer. Instead of starting a new browser for every request I launch puppeteer once and `connect` to that instance for further requests.

However after a couple of hours connecting fails without any prior warning. I am at a loss debugging this issue. Is there any way I can switch on more logging to see what is going on?

**Comment by aslushnikov** [comment]
@kdekooter there's a `dumpio` flag to the `puppeteer.launch`. It will dump the stdout of the chrome in case there are any errors happening.
