### ISSUE TITLE
[Bug]: v19.8.0 introduced issue with ignored timeout setting in methods like waitForSelector & gotTo

### ISSUE THREAD

**Issue by dekelev** [puppeteer/puppeteer#9927]
### Bug expectation

Running the _gotTo_ or _waitForSelector_ methods with the timeout option or with a default page timeout that is set to a value higher than 30000 will timeout after 30 seconds regardless of the timeout setting.

Expected behavior is to consider the timeout option or the default page timeout value.

### Minimal, reproducible example

Issue does not reproduced with the previous version 19.7.5 and with v19.8.0 it can be reproduce with the following example code:

package.json:
```
{
  "name": "test-puppeteer-upgrade",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "express": "^4.18.2",
    "puppeteer": "19.8.0",
    "sleep-promise": "^9.1.0"
  }
}
```

index.html
```
<!DOCTYPE html>
<html>
<body>
    <h1 id="title" style="display: none">Test</h1>
</body>
<script>
    setTimeout(() => {
        document.getElementById('title').removeAttribute('style')
    }, 35000)
</script>
</html>
```

index.js
```
const puppeteer = require('puppeteer');
const express = require('express');
const path = require('path');
const sleep = require('sleep-promise');

const app = express();
const port = process.env.PORT || 8080;

app.get('/', async function (req, res) {
    await sleep(35000)

    res.sendFile(path.join(__dirname, '/index.html'));
});

app.listen(port);

console.log('Server started at http://localhost:' + port);

(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();

    await page.setDefaultTimeout(180000)

    try {
        await page.goto(`http://localhost:${port}`);
        await page.waitForSelector('#title', { visible: true/*, timeout: 180000*/ })
    } catch (err) {
        console.error(err);
    }

    await browser.close();
})();
```

This example will get this navigation timeout error after 30 seconds:
```
Page.navigate timed out.
```

When removing the sleep before responding with the HTML page, you can test for the waitForSelector issue that will timeout after 30 seconds:
```
Waiting for selector `#title` failed: Runtime.callFunctionOn timed out.
```

### Error string

Page.navigate timed out.

### Puppeteer configuration

```TypeScript
{
  headless: false
}
```

### Puppeteer version

19.8.0

### Node version

18.12.1

### Package manager

npm

### Package manager version

8.19.2

### Operating system

macOS

**Comment by OrKoN** [comment]
Unfortunately, it is not possible to consider this timeout settings on the protocol client level. I am gonna bump the default timeout in the next release and for now the workaround is to configure the `protocolTimeout` to be 0 (for no timeout) or to a value that is higher than any timeouts you use.

**Comment by dekelev** [comment]
Thanks @OrKoN

BTW waitForSelector throw timeout after 30 seconds even when the timeout option is set directly (through the method's options object) to a higher value.

I downgraded puppeteer in my project to v19.7.5 for now, since I don't really need the 19.8.0 version specifically and everything seems to work well in v19.7.5.

**Comment by dekelev** [comment]
I can confirm that setting the v19.8.0 puppeteer launch option, `protocolTimeout`, to the highest timeout that I use in my project solved the issue.

**Comment by OrKoN** [comment]
The new timeout setting applies to all CDP calls (see https://github.com/puppeteer/puppeteer/issues/9801 and there were similar feature requests) and `waitForSelector ` calls `evaluate` internally. We are going to stick with 180s timeout by default with an option to change that.

**Comment by nirinsanity** [comment]
@OrKoN  Please update the [corresponding doc page](https://pptr.dev/api/puppeteer.framewaitforfunctionoptions) to reflect these changes. I spent close to half a day trying to figure out what was wrong with my code, after updating to v19.8.0.

**Comment by OrKoN** [comment]
The doc you linked is not related to this change and it is not configurable on the waitForFunction methods, the timeout applies globally and it is documented in the changelog and here https://pptr.dev/api/puppeteer.browserconnectoptions/#properties

**Comment by nirinsanity** [comment]
@OrKoN  Please help me understand what the issue is, as I thought I was facing the same issue as OP was. The code `await page.waitForFunction('window.someFlag === true', { timeout: 45000 })` works on v19.7.5 but not on v19.8.0.

**Comment by OrKoN** [comment]
@nirinsanity please open a bug with a reproduction scripts and a test page specifying all details.

**Comment by nirinsanity** [comment]
Sorry, I would love to do all that procedure, but my company, which uses puppeteer, doesn't pay me nearly enough to do all that. I'll stick to v19.7.5 for now, thanks.
