### ISSUE TITLE
[Feature]: Unable to handle Page breaks, text overflows with Custom Header and footer

### ISSUE THREAD

**Issue by szyth** [puppeteer/puppeteer#9929]
### Feature description

I have a dynamically generated HTML content. This content has several headings/titles.

For each corresponding heading there is a div tag ( which represents a Page ) with a custom header and footer, because puppeteer header couldn't have images and complex styling.

Inside each div tag, a sub div tag holds the body of content which is a dynamic data.

Current Behavior:  when this content overflows the page, the content is moved to the new page along with the custom footer. 

Expected Behavior: is to keep the Custom footer fixated to bottom and add a new page with the overflowed content.

Im using angular to manage the dynamic data.
Suggest ways to fix the issue.

**Comment by OrKoN** [comment]
Please report this issue for PDF printing in Chromium to https://crbug.com. On the Puppeteer-level, we cannot address how exactly the printing is handled. Puppeteer just delivers the PDF that the browser generates. If you feel there is a bug in Puppeteer handling of the data, please open a bug report including a minimal reproducible example.
