### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by draugael** [puppeteer/puppeteer#9930]
### failed: Runtime.callFunctionOn timed out error

I expect puppeteer to wait until the "Captions (c)" aria-label appears on the browser.

instead I got an error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

(async () => {
    await puppeteer.launch({
        headless: false,
        executablePath: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    }).then(async browser => {
        const page = await browser.newPage();
        await page.setDefaultTimeout(0);
        await page.setViewport({ width: 1280, height: 720 })
        await page.goto(
            'https://player.twitch.tv/?parent=twitch.tv&video=1774449542&autoplay=true',
            { waitUntil: ["networkidle2", "domcontentloaded"] }
        );
        await page.waitForSelector(
            'aria/Captions (c)',
            { timeout: 0 }
        );
    })
})();
```

### Error string

ProtocolError: Waiting for selector `Captions (c)` failed: Runtime.callFunctionOn timed out.

### Puppeteer version

19.8.0

### Node version

18.15.0

### Package manager

npm

### Package manager version

8.19.2

### Operating system

Windows

**Comment by OrKoN** [comment]
This is the same issue as https://github.com/puppeteer/puppeteer/issues/9927

**Comment by draugael** [comment]
I see, I found a way to temporarily solve my issue.

`
// use a while loop to increase because timeout not working properly (https://github.com/puppeteer/puppeteer/issues/9927)
let element;
while (!element) {
    try {
        element = await page.waitForSelector('aria/Captions (c)');
        await element?.click();
    } catch (error) {
        console.log(error);
    }
}
`

**Comment by OrKoN** [comment]
You can also set the `protocolTimeout: 0` or `protocolTimeout: sufficientlyHighValue` in the launch function.

**Comment by draugael** [comment]
I have maybe done something wrong. Indeed It's working thanks :)
