### ISSUE TITLE
[Bug]: v19.8.1

### ISSUE THREAD

**Issue by WilcoFiers** [puppeteer/puppeteer#9940]
### Bug expectation

Puppeteer to run when upgrading from 19.8.0 to 19.8.1.

It looks like a cache problem. When I install 19.8.1 without cache I get this error. If I look at the cache the revision it says it needs is there. It doesn't seem to pick up on it. When I install 19.8.0 first, and then install 19.8.1 on top things do work.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  let browser;
  try {
    browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://www.google.com/');
  } finally {
    if (browser) await browser.close();
  }
})().catch(err => {
  console.error(err.stack);
  process.exit(1);
});
```

### Error string

Could not find Chromium (rev. 1108766). This can occur if either  1. you did not perform an installation before running the script (e.g. `npm install`) or  2. your cache path is incorrectly configured (which is: /home/wilco/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

### Puppeteer configuration

```TypeScript
None, just the default.
```

### Puppeteer version

19.8.1

### Node version

v16.15.0

### Package manager

npm

### Package manager version

8.19.1

### Operating system

macOS

**Comment by OrKoN** [comment]
Thanks for the report. This is being addressed with https://github.com/puppeteer/puppeteer/pull/9939. Originally reported in https://github.com/puppeteer/puppeteer/pull/9917#issuecomment-1488327379
