### ISSUE TITLE
[Bug]: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by xiaolizi9** [puppeteer/puppeteer#9941]
### Bug expectation

<img width="895" alt="image" src="https://user-images.githubusercontent.com/46665565/228776335-51967888-7be2-4a78-bd72-6a99b8a38dfc.png">

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch({
    // Optional, if you want to see the tests in action.
    headless: false,
    slowMo: 50,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
    executablePath: process.env.CHROMIUM_PATH,
  });
  const page = await browser.newPage();
```

### Error string

Failed to launch the browser process!

### Puppeteer version

19.8.2

### Node version

v16.17.0

### Package manager

npm

### Package manager version

19.8.2

### Operating system

Windows

**Comment by OrKoN** [comment]
Hey, are you trying to run a headful browser on a server? Make sure that you have all dependencies installed on the system (some tips are here https://pptr.dev/troubleshooting#chrome-headless-doesnt-launch-on-unix) and use a tool like xvfb-run to run headful in a virtual X server environment (https://manpages.ubuntu.com/manpages/xenial/man1/xvfb-run.1.html). Also, it does not look like you run on Windows? is it WSL? (see https://pptr.dev/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux)
