### ISSUE TITLE
[Feature]: How can I set the default font-family for Chrome browser to Ping Fang SC

### ISSUE THREAD

**Issue by shuizhongxiong** [puppeteer/puppeteer#9942]
### Feature description

How can I set the default font-family for Chrome browser to Ping Fang SC, instead of setting it in CSS.

**Comment by OrKoN** [comment]
Can you describe the feature in more details? What is CS?

**Comment by OrKoN** [comment]
You can try using `Page.setFontFamilies` directly https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setFontFamilies:

```
const cdp = await page.target().createCDPSession();
await cdp.send('Page.setFontFamilies', {...params... });
```

**Comment by shuizhongxiong** [comment]
> You can try using `Page.setFontFamilies` directly https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setFontFamilies:
> 
> ```
> const cdp = await page.target().createCDPSession();
> await cdp.send('Page.setFontFamilies', {...params... });
> ```

Yes, this is exactly what I wanted. Thank you very much.
