### ISSUE TITLE
[Bug]: TLSSocket.socketErrorListener

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9944]
### Bug expectation

09:00:45  error C:\uiautotest\workspace\jenkins-ui-prod\node_modules\puppeteer: Command failed.
09:00:45  Exit code: 1
09:00:45  Command: node install.js
09:00:45  Arguments: 
09:00:45  Directory: C:\uiautotest\workspace\A\node_modules\puppeteer
09:00:45  Output:
09:00:45  node:events:505
09:00:45        throw er; // Unhandled 'error' event
09:00:45        ^
09:00:45  
09:00:45  Error: 4396:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:677:
09:00:45  
09:00:45  Emitted 'error' event on ClientRequest instance at:
09:00:45      at TLSSocket.socketErrorListener (node:_http_client:454:9)
09:00:45      at TLSSocket.emit (node:events:527:28)
09:00:45      at TLSSocket._emitTLSError (node:_tls_wrap:902:10)
09:00:45      at TLSWrap.onerror (node:_tls_wrap:434:11) {
09:00:45    library: 'SSL routines',
09:00:45    function: 'ssl3_get_record',
09:00:45    reason: 'decryption failed or bad record mac',
09:00:45    code: 'ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC'
09:00:45  }

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
yarn 
and then error occured
```

### Error string

09:00:45  error C:\uiautotest\workspace\jenkins-ui-prod\node_modules\puppeteer: Command failed. 09:00:45  Exit code: 1 09:00:45  Command: node install.js 09:00:45  Arguments:  09:00:45  Directory: C:\uiautotest\workspace\A\node_modules\puppeteer 09:00:45  Output: 09:00:45  node:events:505 09:00:45        throw er; // Unhandled 'error' event 09:00:45        ^ 09:00:45   09:00:45  Error: 4396:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:677: 09:00:45   09:00:45  Emitted 'error' event on ClientRequest instance at: 09:00:45      at TLSSocket.socketErrorListener (node:_http_client:454:9) 09:00:45      at TLSSocket.emit (node:events:527:28) 09:00:45      at TLSSocket._emitTLSError (node:_tls_wrap:902:10) 09:00:45      at TLSWrap.onerror (node:_tls_wrap:434:11) { 09:00:45    library: 'SSL routines', 09:00:45    function: 'ssl3_get_record', 09:00:45    reason: 'decryption failed or bad record mac', 09:00:45    code: 'ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC' 09:00:45  }

### Puppeteer version

19.8.2

### Node version

16.19.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by FishBlanche** [comment]
This occurs occasionaly.Any solution?

**Comment by OrKoN** [comment]
I am not able to reproduce and it looks like the issue is in the openssl library installed (which is probably used by Node). I think you should try to reproduce on a different machine and maybe fix/update openssl/Node.
