### ISSUE TITLE
Exported PDF is not recognised by Voiceover on iOS

### ISSUE THREAD

**Issue by runmyservice** [puppeteer/puppeteer#9946]
I'm not sure if this is a puppeteer problem, a chromium problem, or an iOS problem.

When I export a basic html page using puppeteer, VoiceOver for MacOS reads the PDF correctly, but **VoiceOver on iOS ignores the content or the PDF** completely.

Here is the html I'm testing :

```html
<!DOCTYPE html>
<html>
  <body>
    <h1>This is a test heading</h1>
    <p>This is some text in a paragraph</p>
    <h2>This is a test heading level 2</h2>
    <p>This is some text in a paragraph</p>
    <p>Another paragraph</p>
  </body>
</html>
```

And the code to generate the PDF :  
```ts
    const browser = await puppeteer.launch({
      args: ['--disable-dev-shm-usage', '--headless',  '--no-sandbox', '--export-tagged-pdf'],  
      headless: true
    });

   const html = `${ HTML FROM ABOVE EXAMPLE }`;

   const page = await browser.newPage();
   await page.goto(`data:text/html;charset=UTF-8,${html}`, {
        waitUntil: 'networkidle0'
   });

   const snapshot = await page.accessibility.snapshot();
   console.log(snapshot);

   result = await page.pdf();

   // ...save the resulting buffer to disk
```

As you can see, I print the accessibility snapshot and all seems correct : 

```js
{
  role: 'RootWebArea',
  name: '',
  children: [
    { role: 'heading', name: 'This is a test heading', level: 1 },
    { role: 'StaticText', name: 'This is some text in a paragraph' },
    {
      role: 'heading',
      name: 'This is a test heading level 2',
      level: 2
    },
    { role: 'StaticText', name: 'This is some text in a paragraph' },
    { role: 'StaticText', name: 'Another paragraph' }
  ]
}
```

Perhaps someone can see a setting or something that I may be missing ?

Using Puppeteer 19.7.0.

**Comment by OrKoN** [comment]
Thanks for the report. It looks like a problem with the iOS voice over. But perhaps you could open an issue at crbug.com first? Especially, if it reproduced with PDFs printed using the regular browser window (without Puppeteer). We have no means of fixing this issue inside Puppeteer because we only deliver the PDFs generated by the browser.

**Comment by runmyservice** [comment]
> Thanks for the report. It looks like a problem with the iOS voice over. But perhaps you could open an issue at crbug.com first? Especially, if it reproduced with PDFs printed using the regular browser window (without Puppeteer). We have no means of fixing this issue inside Puppeteer because we only deliver the PDFs generated by the browser.

Thank you for your reply, especially the suggestion about just printing using the regular browser. I did exactly that with the HTML above, and lo and behold, VoiceOver does not read it on iOS.

I'll elevate the issue to Chromium and/or Apple !
