### ISSUE TITLE
[Bug]: Could not find Google Chrome executable for channel 'chrome' at '/opt/google/chrome/chrome'

### ISSUE THREAD

**Issue by FishBlanche** [puppeteer/puppeteer#9949]
### Bug expectation

Could not find Google Chrome executable for channel 'chrome' at '/opt/google/chrome/chrome'

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
config: {
         timeout: 50000,
       
        headless: true,          
        defaultViewport: {width: 1920, height: 1080},
        channel:'chrome',
         args: [
            '--start-maximized',
             '--enable-precise-memory-info',
            '--no-sandbox',
            '--disable-setuid-sandbox',
             '--disable-features=site-per-process',
            '--use-angle=gl-egl',
            '--enable-unsafe-webgpu'
        ],
    },
```

### Error string

[Bug]: Could not find Google Chrome executable for channel 'chrome' at '/opt/google/chrome/chrome'

### Puppeteer version

19.8.2

### Node version

16.19.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Linux

**Comment by OrKoN** [comment]
Do you have the browser installed at `/opt/google/chrome`?

**Comment by OrKoN** [comment]
I assume that the browser is not installed to that location as it is how the channel feature works: it picks some known locations where the browser has to be installed to upfront.
