### ISSUE TITLE
touchscreen

### ISSUE THREAD

**Issue by LLLLLamHo** [puppeteer/puppeteer#995]
in iphone mode use `touchscreen.tap`，but browser no scrolling screen，hope to answer，thanks。

**The configuration file**
```javascript
try {
  await page.emulate( iPhone );
  await staticRequest(page, opt.pageName);

  await page.goto( opt.url );

  resolve( {
    pageObj: page,
    browserObj: browser
  } );
} catch ( e ) {
  console.log( 'sf err:', e );
  reject( null );
}
```
**Using the file**

```
await page.touchscreen.tap(500, 400)
```

**Comment by entrptaher** [comment]
Maybe because you are not scrolling?

**Comment by fhmd4k** [comment]
The puppeteer has too many bugs.
I think the best way that change the code follow your need.

**Comment by aslushnikov** [comment]
@LLLLLamHo `.tap` doesn't scroll the screen; it sends a touch event for the locations - "taps" a point.
