### ISSUE TITLE
[Bug]: getQueryHandlerAndSelector - TypeError: Cannot read property 'startsWith' of undefined 

### ISSUE THREAD

**Issue by shubham-shewale** [puppeteer/puppeteer#9955]
### Bug expectation

I expected getQueryHandlerAndSelector to run with default configuration if selector was undefined !! quoting this w.r.t current version we are using which is. 13.1.2

As we are process in the migration to the latest Puppeteer release, we are facing issue where the selector is getting passed as undefined which results in the following error: 
Cannot read property 'startsWith' of undefined 

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript


//config foo and bar is been merged with commonHTMLSelector on based on the custom logic.
//In case if the logic satisfies foo then it gets merge with the commonHTMLSelector the eList property would be undefined, //Thus will result in the failure of race with TypeError `Cannot read property 'startsWith' of undefined `

import puppeteer from 'puppeteer'
(async () => {
try{const browser = await puppeteer.launch();
const page = await browser.newPage();
let commonHTMLSelector = {eDocs: 'default-selector'}
let config ={ foo: {commonHTMLSelector : {eDocs: 'navigation-with-keyboard'}}, bar: {commonHTMLSelector:{eList:'invalid-selector'}}} 

Object.assign(commonHTMLSelector, config.foo)
await page.goto('https://pptr.dev/');
let result = await Promise.race([page.waitForSelector(commonHTMLSelector.eList), page.waitForSelector(commonHTMLSelector.eDocs)]);
await browser.close();
} catch (err){
throw err;}
})();
```

### Error string

Cannot read property 'startsWith' of undefined 

### Puppeteer version

19.18.2

### Node version

18.15.0

### Package manager

npm

### Package manager version

9.6.3

### Operating system

Windows

**Comment by OrKoN** [comment]
It appears that you provide an undefined as a selector to one of the functions (eList is not defined anywhere in the code you shared).

**Comment by shubham-shewale** [comment]
In earlier version, which I am aware of  i.e. 13.1.2, On passing selector as undefined the logic was not breaking !!
In case of selector as undefined default queryHandler was returned, But in the latest version it fails,

Can we return default queryHandler Instead ? incase of undefined selector 

Updated the code, Object.assign depends on the value provided in API !!
If foo is provided then it get's merged with commonSelector same with bar ...
