### ISSUE TITLE
[Bug]: could not yarn add

### ISSUE THREAD

**Issue by hlau-square** [puppeteer/puppeteer#9956]
### Bug expectation

Hi, I tried to run:

```
yarn add puppeteer
```

and got this error

```
error An unexpected error occurred: "ENOENT: no such file or directory, symlink '../../lib/cjs/main-cli.js' -> '/Users/hlau/Library/Caches/Yarn/v5/npm-@puppeteer-browsers-0.3.1-21d43c49f6f8bb5fa905b322d73c11fca9b515bd/node_modules/@puppeteer/browsers/.bin/@puppeteer/browsers'".
```

![Screenshot 2023-04-01 at 11 43 59 PM](https://user-images.githubusercontent.com/72578332/229337057-3febf13d-316f-4574-b392-4c8192161722.png)

any idea why? because i googled around and don't see any results

@OrKoN @Lightning00Blade
does this error message look familiar to you? Because I see you made edits in the last few days related to @puppeteer/browsers

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
yarn add puppeteer -W
```

### Error string

error An unexpected error occurred: "ENOENT: no such file or directory, symlink '../../lib/cjs/main-cli.js' -> '/Users/hlau/Library/Caches/Yarn/v5/npm-@puppeteer-browsers-0.3.1-21d43c49f6f8bb5fa905b322d73c11fca9b515bd/node_modules/@puppeteer/browsers/.bin/@puppeteer/browsers'".

### Puppeteer version

latest

### Node version

16

### Package manager

yarn

### Package manager version

1.19.0

### Operating system

macOS

**Comment by OrKoN** [comment]
Looks like a bug in yarn? It works for me with yarn `1.22.19`.
