### ISSUE TITLE
[Bug]: Page.goto returns unexpected spliced response if last page in redirect chain is cached

### ISSUE THREAD

**Issue by dbjorge** [puppeteer/puppeteer#9965]
### Bug expectation

Today, we were using Puppeteer to test a page with the following pattern of redirects:

1. `https://site-under-test/` responds 200. It requires authorization and contains a script which invokes `window.location.assign('https://auth-provider/authorize?redirect_uri=https://site-under-test')` on load
2. `https://auth-provider/authorize` responds with a 302 redirect back to `https://site-under-test#code=123`
3. `https://site-under-test/` responds 200 with the same content as the first time. This time, its auth script sees the `#code` fragment and does not do any further redirects

In this scenario, we asked Puppeteer is asked to perform

```js
const response = await page.goto('https://site-under-test/', { waitUntil: 'networkidle2' });
```

...and wanted to test some properties of the `response`.

The [documented behavior](https://pptr.dev/api/puppeteer.page.goto) of Page.goto's return value in the case of redirects is:

> Promise which resolves to the main resource response. In case of multiple redirects, the navigation will resolve with the response of the last redirect.

I wasn't sure exactly what the expected behavior should be here; this reads a bit ambiguously to me. My initial reading of this would be that it should probably resolve with a response representing step 3 above, but I could imagine someone interpreting the docs to mean that it ought to resolve with the response from step 2, and I could also imagine this being intended only to cover 30X redirects and not script-based redirects.

If `https://site-under-test/`'s response does not allow caching, you consistently receive the response from step 3 above, which seems reasonable and is within expectations.

However, **if `https://site-under-test/` allows caching**, the actual behavior is very confusing; you end up with a response which splices together attributes of the responses from step 2 and step 3. Specifically, the resulting response has:

* `fromCache() === true`, `url()`, and `text()` from step 3
* `status() === 302` and `headers()` from step 2 (!!)

The self-contained repro below:

* Starts a localhost server that implements the pattern described above (`http://localhost:3000/` is cached and does a script-redirect to `http://localhost:3000/redirect`, which does a 302 redirect to `http://localhost:3000/#from-redirect`)
* A minimal puppeteer script that performs `await page.goto('http://localhost:3000/')` and dumps the resulting response to the console
* Leaves the test server running in case you'd like to verify the request/response pattern manually afterwards

The original motivating issue is https://github.com/microsoft/accessibility-insights-service/issues/2413, though the specific original motivating site is internal-only and redacted from the issue. The original motivating case was using an older version of Puppeteer (18.1.0), but I've verified that the minimal repro below still reproduces the issue in the current version as of writing (19.8.3).

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
// REPRO SETTINGS
const enableCache = true; // Issue repros iff this is true
const keepAliveAfterTest = false; // set to true to leave test server up afterwards for manual testing
const port = 3000;

// REPRO IMPL
const util = require('node:util');
const http = require('node:http');

let browserLauncher = require('puppeteer');
let waitUntil = 'networkidle2';

const server = http.createServer((req, res) => {
    if (req.url === '/redirect') {
        res.setHeader('Location', `http://localhost:${port}/#from-redirect`)
        res.writeHead(302);
        res.end();
        return;
    } else {
        res.setHeader("Content-Type", "text/html; charset=utf-8");
        if (enableCache) {
            res.setHeader('Cache-Control', 'max-age=5');
        }        
        res.writeHead(200);
        res.end(`
        <!DOCTYPE html>
        <h1>Inside index.html</h1>
        <div id="client-root">Haven't yet detected redirect...</div>
        <script>
        window.addEventListener('load', () => {
            if(window.location.hash !== '#from-redirect') {
                console.log('Initiating redirect via window.location.assign...')
                window.location.assign('redirect')
            } else {
                document.getElementById('client-root').innerText = 'Detected as from redirect'
                history.replaceState("", document.title, window.location.pathname);
            }
        });
        </script>
        `);
    }
});

server.listen(port, 'localhost', async () => {
    console.log(`Server listening on port ${port}, starting test`);

    const browser = await browserLauncher.launch({ headless: false });
    const page = await browser.newPage();

    console.log(`await page.goto('http://localhost:${port}/')`)
    const response = await page.goto(`http://localhost:${port}/`, { waitUntil });

    console.log('Return value of page.goto:')
    const request = response.request();
    responseDebugInfo = {
        url: response.url(),
        status: response.status(),
        statusText: response.statusText(),
        headers: response.headers(),
        redirectChainUrls: request.redirectChain?.()?.map(req => req.url()) ?? undefined,
        fromCache: response.fromCache?.(),
        text: await response.text()
    };
    console.log(util.inspect(responseDebugInfo));
    await browser.close();

    const actualResponseStatus = response.status();
    console.log(`The actual final response should have been a 200, was: ${response.status()}`);

    if (keepAliveAfterTest) {
        console.log(`Leaving test server running at http://localhost:${port} for manual testing, Ctrl+C to exit`);
    } else {
        server.close(() => {
            if (actualResponseStatus !== 200) {
                throw new Error(`The actual final response should have been a 200, was: ${actualResponseStatus}`);
            }
        });
    }    
});

```

### Error string

The actual final response should have been a 200, was: 302

### Puppeteer configuration

```TypeScript
```

### Puppeteer version

19.8.3

### Node version

18.15.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

Windows

**Comment by jrandolf** [comment]
So your flow is a little awkward. To be precise about what we mean by "redirect", we mean server redirects, i.e. you send a GET request to `some-site.com` and you receive a 302 response. Your example is a client-side redirect since the original request is `some-site.com` and you receive a 200, but then your JS code triggers a redirect.

Client-side redirects are pretty much impossible to detect from within Puppeteer since we would never know when your JS code triggers it redirect. For example, the redirect can occur 1 minute later. In theory, we can maybe have a `waitForUrl` that waits for some subset of the URL to match your desired one, but it'd be difficult to get the specific request. Perhaps a combination of request interception and a `waitForUrl` may work. WDYT?

**Comment by dbjorge** [comment]
I think it would be reasonable for Puppeteer to not attempt to include client-side redirects as part of `Page.goto`'s output - this is essentially what Playwright already does, for example (it returns the response from step 1 in the listed scenario). Mostly, what I want as a user is for Puppeteer's behavior to be consistent and clearly documented.

But I want to be clear that **that's orthogonal to the bug this issue is tracking**; I used a client-side redirect because it's involved in the motivating case, but you get the same sort of incorrectly-spliced response if you do the following pattern with no client-side redirect involved:

1. `page.goto('https://site-under-test/')` such that it becomes cached. This time, it performs no client-side redirect.
2. `page.goto('https://redirecting-site')`, which responds with a 302 back to `https://site-under-test`
3. The browser follows the 302 and uses the cached response from step 1.

In this scenario, the `goto` from step 2 still returns a spliced response with the `text()` of the cached `https://site-under-test` response but the `status()` of the 302 response.

**Comment by OrKoN** [comment]
It sounds more like a bug to me too. IIRC the current behaviour expects the client-side redirects to be considered in page.goto as well but the mix up with responses sounds like a bug.

**Comment by OrKoN** [comment]
So if I read CDP logs right, there are 3 CDP responses detected with the following statuses: 200, 302, 302 and two requestIds with the last two requests sharing the same request ID. It looks like the last response should be status 200 as it should be the cached response from the first request. We do receive an extra Network.responseReceivedExtraInfo event with the status 302 from the browser though. So it looks like the bug might be upstream or we would need to work around that.

**Comment by dbjorge** [comment]
Possibly-related upstream bug which Playwright's network manager references: https://bugs.chromium.org/p/chromium/issues/detail?id=1340398
