### ISSUE TITLE
Cannot type into an iframe element

### ISSUE THREAD

**Issue by SMJ93** [puppeteer/puppeteer#999]
## Problem

Issue #684 has been resolved so we can now select elements inside the iframe. Great work guys!

But we can't seem to type after selecting / focussing on the element.

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**What steps will reproduce the problem?**

* Select an input element inside an iframe
* Then try and type
* Notice the element is in focus, but typing does nothing.

_Please include code that reproduces the issue._

```
  const frames = await page.frames();
  let iframe = frames.find(f => f.name() === 'any_iframe');
  const textInput = await iframe.$('#textInput');
  textInput.click(); // this focusses on the element
  page.type('6'); // tried several solutions for typing mentioned in the API
```

**What is the expected result?**

We should be able to type into a focusses element inside an iframe

**Comment by chris-jansen** [comment]
I'm having the same issue.

**Comment by mboeser** [comment]
attaching '.type' to the textInput.type('6') instead of page.type worked for me. Try it out and let us know if that worked for you. I'm unsure if this is a bug or if this then is the proper way to use it...

**Comment by JoelEinbinder** [comment]
I think this is a duplicate of #684 which was fixed in #971. Clicking the `textInput` wasn't actually focusing it, which is why click+type didn't work but `textInput.type` did work.

**Comment by SMJ93** [comment]
@mboeser I've tried textInput.type('6') but nothing happens. What version of puppeteer are you using?

@JoelEinbinder nice fix! When will this get released?

**Comment by mboeser** [comment]
@SMJ93 I was using the recent GitHub version: npm i https://github.com/GoogleChrome/puppeteer/

**Comment by chris-jansen** [comment]
textInput.type is not a function for now. 
@JoelEinbinder Do you know the ETA of the #801 fix?

**Comment by gajus** [comment]
Is there a workaround for this?

**Comment by JoelEinbinder** [comment]
The next release should have the fix for this in it. You can checkout directly from GitHub in the meantime.

**Comment by gajus** [comment]
> The next release should have the fix for this in it. You can checkout directly from GitHub in the meantime.

I have just tried using master.

```js
await (await paymentFrame.$('#cardNumber')).type(String(purchaseOrder.paymentCard.cardNumber));

```

Gives no error and does not update the input value.

**Comment by gajus** [comment]
Note that focus does work.

```js
const cardElement = await paymentFrame.$('#cardNumber');

// Input is focused.
await cardElement.focus();

// Text is not typed into the input.
await page.keyboard.type('123');

```

**Comment by gajus** [comment]
Interesting. It looks like there is some delay between an element in an iframe can be selected and when it can by typed to.

```js
await paymentFrame.waitForSelector('#cardContent #cardNumber');

// Adding the delay after `waitForSelect` made the `type` work as expected.
await delay(1000);

await (await paymentFrame.$('#cardNumber')).type(String(purchaseOrder.paymentCard.cardNumber));

```

**Comment by JoelEinbinder** [comment]
@gajus are you sure something else isn't going on?

The implementation of `element.type` is:
```js
await this.focus();
await this._page.keyboard.type(text, options);
```

**Comment by aslushnikov** [comment]
@gajus might be facing a different problem; I'd appreciate if a separate issue would be filed for it with a full repro with url. Otherwise it's impossible to reproduce and hard to reason about.

Typing in iframe should be working fine now since we've fixed clicking inside iframes. This is fixed.
