### ISSUE TITLE
[Bug]: 30-50% performance drop since v19.7.1

### ISSUE THREAD

**Issue by feesler** [puppeteer/puppeteer#9993]
### Bug expectation

Similar to https://github.com/puppeteer/puppeteer/issues/8650 but not so dramatic.

**Steps to reproduce the problem:**
1. Install puppeteer v19.7.0 dependency
2. import puppeteer from 'puppeteer';
3. Run some script and measure performance
4. Update puppeteer to v19.7.1 and repeat step 3

Updated https://github.com/feesler/puppeteer-perf package to test this issue.
Script will download Chromium revision 1095492 to discard possible difference in browser performance.
Try to run several times to avoid caching effects or give URL with more elements on page.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
git clone https://github.com/feesler/puppeteer-perf.git
cd puppeteer-perf
npm install
npm test
npm install puppeteer@19.7.1
npm test
```

### Error string

no error

### Puppeteer version

19.8.5

### Node version

19.8.1

### Package manager

npm

### Package manager version

8.13.2

### Operating system

Windows

**Comment by OrKoN** [comment]
@jrandolf ptal, it is probably the new selector querying engine. I think 30-50% is too much so perhaps there is a bug (or generators are that much slower in Node just like ESM imports were last time).

**Comment by jrandolf** [comment]
This depends on how many elements are being queried. We typically batch queried elements with a default size of 20 which may be why this query takes so long (there are 120~ elements). I've amortized the logic related to this so the performance should be fixed.
