### ISSUE TITLE
[Bug]: Pages are not closed even page.close() is called

### ISSUE THREAD

**Issue by ahmednaser94** [puppeteer/puppeteer#9999]
### Bug expectation

I am using puppeteer to render HTML content and first i launch a browser and then launch a page to take screenshot from it after rendering HTML content then close page
This was working fine for last couple of months, but now after upgrading from version 19.7.2,  pages are not closed!!

![image](https://user-images.githubusercontent.com/39867467/231070459-7abc8eeb-80b1-42fa-87aa-23c596b78f50.png)

screenshot from the server processes 

<img width="737" alt="image" src="https://user-images.githubusercontent.com/39867467/231070800-871e8de2-933c-4bdc-ba7f-24caac3b8d9b.png">

<img width="950" alt="image" src="https://user-images.githubusercontent.com/39867467/231070902-b09481b7-860a-4729-a48e-ef2481c6db06.png">

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; // TS/ESM are all supported.
let browser;
(async () => {
    try {
      if (!browser) {
        browser = await puppeteer.launch({
          headless: true,
          args: ['--disable-gpu', '--no-sandbox'],
        });
      }
      const page = await browser.newPage();
      await page.setViewport({ width: 860, height: 860 });
      await page.goto('https://google.com/');

      const imageBuffer = await page.screenshot({ type: 'jpeg' });
      await page.close();
      return imageBuffer;
    } catch (err) {
      logger.error('Error while generating image in browser', { message: err.message, stack: err.stack, __filename });
      if (browser) await browser.close();
      return null;
    }
  });
```

### Error string

No errors are thrown

### Puppeteer configuration

```TypeScript
headless: true,
args: ['--disable-gpu', '--no-sandbox'],
```

### Puppeteer version

19.8.5

### Node version

18.15.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Linux

**Comment by OrKoN** [comment]
I am unable to reproduce it. If you mean that the process 380 is retained, this is probably the default empty about:blank page that is being automatically created when the browser launches. Which version are you updating from?
